### ISSUE TITLE
docs on "google_tpu_tensorflow_versions" is misleading

### ISSUE THREAD

**Issue by sairajm** [hashicorp/terraform-provider-google#10009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I was going through the docs in https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/tpu_tensorflow_versions and I tried to generate a plan. The plan kept complaining that the project wasn't set for "data "google_tpu_tensorflow_versions" "available". 

The exact error was 
```
Error: project: required field is not set

  on tpu.tf line 24, in data "google_tpu_tensorflow_versions" "available":
  24: data "google_tpu_tensorflow_versions" "available" {
```
The docs say that the project and zone are optional. But it looks like both of them are required.
Once I resolved the error above by adding the project, it said the same thing about zone as well.

I did notice that 
`data.google_tpu_tensorflow_versions.available.versions[0]` gave me the oldest version available. It would be helpful if there was a notice that says this goes in the ascending order and gave me a link to find all the versions. I had to manually increment the index until I found the right version.

### New or Affected Resource(s)

* google_tpu_tensorflow_versions
* google_tpu_node

### References
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/tpu_tensorflow_versions

**Comment by edwardmedia** [comment]
@sairajm do you have environment variable `GOOGLE_PROJECT` configured on your machine? The `project` is optional if you have it. Otherwise, it is required.  Please review the [doc]. (https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project). This is the behavior cross the board. Let me know if that make sense to you.

**Comment by edwardmedia** [comment]
@sairajm is this still an issue?

**Comment by edwardmedia** [comment]
@sairajm closing assuming this is no longer an issue

**Comment by sairajm** [comment]
@edwardmedia My apologies on such a late reply. My org recently moved to Office 365 and all of my GitHub mails have been going to trash. 
I do not have `GOOGLE_PROJECT` set as an environment variable. I have multiple projects that I work with and it's not convenient to have that fixed for me. I think calling this out in the docs would be helpful for folks.
