### ISSUE TITLE
GKE Sandbox support for google_container_node_pool

### ISSUE THREAD

**Issue by artemijspavlovs** [hashicorp/terraform-provider-google#10008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, only `node_config` of the `google_container_cluster` supports a `sandbox_config` property but according to [Terraform documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config), using it is not the recommended way. According to [Google Cloud Hardening documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/sandbox-pods) it is possible to enable the [GKE Sandbox](https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods) when creating a new node pool on an existing cluster.

I would appreciate the ability to add `sandbox_config` property to a `google_container_node_pool` resource.

### New or Affected Resource(s)

`google_container_node_pool`

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "primary" {
  name       = "primary"
  location   = var.region
  project    = var.project
  cluster    = google_container_cluster.main.name

  node_config {
//  ... 
    
    sandbox_config {
      sandbox_type = "gvisor"
    }
  }
}

```

**Comment by rileykarson** [comment]
Fields under `node_config` are supported by both resources, so this should already work. Note you'll need `provider = google-beta` on the node pool, as the feature is still at beta.
