### ISSUE TITLE
`google_compute_region_network_endpoint_group` - Error: project: required field is not set

### ISSUE THREAD

**Issue by andrewmackett** [hashicorp/terraform-provider-google#10016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.82.0
+ provider registry.terraform.io/hashicorp/google-beta v3.82.0
```

### Affected Resource(s)

* `google_compute_region_network_endpoint_group`

### Terraform Configuration Files

```tf
// https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#example-usage---region-network-endpoint-group-cloudrun

// Cloud Run Example
resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
  name                  = "cloudrun-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"
  cloud_run {
    service = google_cloud_run_service.cloudrun_neg.name
  }
}

resource "google_cloud_run_service" "cloudrun_neg" {
  name     = "cloudrun-neg"
  location = "us-central1"

  template {
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### Debug Output

[GitHub Gist containing the debug output.](https://gist.github.com/andrewmackett/791774e2a3faac8cf06708e7ef1832a5)

### Panic Output

N/A

### Expected Behavior

* The `google_compute_region_network_endpoint_group` resource should be created without a project being defined (the documentation for this resource says that the `project` field is optional).
* The resource should also be created if a value for the `project` field is defined.

### Actual Behavior

Terraform returns an error:
```
Error: project: required field is not set
│ 
│   with google_cloud_run_service.cloudrun_neg,
│   on main.tf line 12, in resource "google_cloud_run_service" "cloudrun_neg":
│   12: resource "google_cloud_run_service" "cloudrun_neg" {
```

This error is produced even when a project ID value is defined in the `google_compute_region_network_endpoint_group` resource.

### Steps to Reproduce

1. `terraform apply` will produce the error
2. Add `project = "PROJECT_ID"` line to the `google_compute_region_network_endpoint_group` resource (with a valid project ID)
3. `terraform apply` will produce the same error

### Important Factoids

N/A

### References

 * Terraform docs - [`compute_region_network_endpoint_group` example code](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#example-usage---region-network-endpoint-group-cloudrun)
 * Terraform docs - [`compute_region_network_endpoint_group` `project` field is optional](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#project)

**Comment by edwardmedia** [comment]
@andrewmackett did you provide `project` in the `provider` block or have the environment variable `GOOGLE_PROJECT`? It is optional if you have either of one available. Please review below doc that might be help.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#configuring-the-provider

**Comment by andrewmackett** [comment]
@edwardmedia yes, after hitting this issue I added the `project` to the google provider block which is a successful work around.

However I believe there's still an issue here because setting a `project` value on the `google_compute_region_network_endpoint_group` resource has no effect and it shouldn't be necessary to set the project in the provider if the project is already defined on the resource.

**Comment by edwardmedia** [comment]
@andrewmackett is this still an issue?

**Comment by edwardmedia** [comment]
@andrewmackett closing assuming it is no longer an issue
