### ISSUE TITLE
Redis Instance Update timeout is too low

### ISSUE THREAD

**Issue by philipp-hb** [hashicorp/terraform-provider-google#10031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.82.0

### Affected Resource(s)

* google_redis_instance

### Expected Behavior

When upgrading a Redis Instance from Version REDIS_5_0 to REDIS_6_X, terraform should wait until update is completed

### Actual Behavior

After 10 minutes elapsed, Terraform fails with "Error waiting for Updating Instance: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 10m0s)".

Basic Redis instances usually upgrade within less than 10 minutes. Standard instances take longer. According to the Google UI, Upgrade may take up to 4h.

### Steps to Reproduce

Upgrade a Standard Tier Redis Instance from REDIS_5_0 to REDIS_6_X

**Comment by edwardmedia** [comment]
@philipp-hb while I am going to extend the default timeout, can you try to overwrite it suggested below?

https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts

**Comment by philipp-hb** [comment]
@edwardmedia sorry for the late answer, I was on vacation.
Thanks for fixing
