### ISSUE TITLE
Clarify difference between gce_persistent_disk_csi_driver_config omitted vs disabled

### ISSUE THREAD

**Issue by micimize** [hashicorp/terraform-provider-google#10035]
The docs state that [gce_persistent_disk_csi_driver_config] defaults to disabled, however it is instead [left unconfigured](https://github.com/hashicorp/terraform-provider-google-beta/blob/3c56207d8f524b26773492153e2ebe4da031dc17/google-beta/resource_container_cluster.go#L2917-L2923). This results in the CSI Driver being [enabled by default by GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver#enabling_the_on_a_new_cluster) for newer cluster versions.

> [gce_persistent_disk_csi_driver_config] - (Optional, Beta). Whether this cluster should enable the Google Compute Engine Persistent Disk Container Storage Interface (CSI) Driver. Defaults to disabled; set enabled = true to enable.

[GKE docs](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver#enabling_the_on_a_new_cluster):
> Note: The Compute Engine persistent disk CSI Driver is enabled by default on newly created clusters for the following versions: Linux clusters: GKE version 1.18.10-gke.2100 or later, or 1.19.3-gke.2100 or later.

[gce_persistent_disk_csi_driver_config]: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#gce_persistent_disk_csi_driver_config

This seems like fine behavior to me but should be documented/rephrased as it means setting the documented default explicitly results in different behavior than not setting it at all

b/299312323

**Comment by rileykarson** [comment]
Tagged as breaking change as we may want to break to align with the API in the future

**Comment by hao-nan-li** [comment]
doc updated https://github.com/GoogleCloudPlatform/magic-modules/pull/8912

**Comment by c2thorn** [comment]
Decision was to keep current behavior and only update the docs. Closing.
