### ISSUE TITLE
TF plan always shows changes on google_monitoring_alert_policy

### ISSUE THREAD

**Issue by tm185187** [hashicorp/terraform-provider-google#10042]
### Affected Resource(s)

* google_monitoring_alert_policy

Hello,

On use of resource "google_monitoring_alert_policy" TF google resource to create a alerting policy with Terraform, it always shows + cross_series_reducer = "REDUCE_NONE getting added and TF plan shows has been changed.

```
resource "google_monitoring_alert_policy" "backend_restart_count_alert" {
  project               = var.project
  combiner              = "OR"
  display_name          = "Backend pod keeps restarting"
  notification_channels = []
  conditions {
    display_name = "Restart count"
    condition_threshold {
      filter          = "metric.type=\"logging.googleapis.com/user/BB_ENT_PRD_A_child_container_failed_during_start_catalina\" resource.type=\"gce_instance\""
      duration        = "60s"
      comparison      = "COMPARISON_GT"
      threshold_value = 5
      aggregations {
        alignment_period     = "60s"
        per_series_aligner   = "ALIGN_RATE"
        cross_series_reducer = "REDUCE_NONE"
      }
    }
  }
}
```

Plan output
```
resource "google_monitoring_alert_policy" "logging_alert_policy" {
        id                    = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117"
        name                  = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117"
        # (7 unchanged attributes hidden)

      ~ conditions {
            name         = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117/conditions/16007304137780151806"
            # (1 unchanged attribute hidden)

          ~ condition_threshold {
                # (4 unchanged attributes hidden)

              ~ aggregations {
                  + cross_series_reducer = "REDUCE_NONE"
                    # (3 unchanged attributes hidden)
                }

                # (1 unchanged block hidden)
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

b/275101455

**Comment by slevenick** [comment]
Are you sure this cross series reducer type of `REDUCE_NONE` is applicable for this policy? The docs note that 

"Not all reducer functions may be applied to all time series, depending on the metric type and the value type of the original time series."

I'm guessing that if it is not applicable for some reason the API does not save the input value? I'm saying this because we have tests that set the cross_series_reducer field and it seems to work correctly in some cases

**Comment by tm185187** [comment]
This only happens when you have selected cross_series_reducer as REDUCE_NONE for log-based metric alerting. Other aggregators are fine.

**Comment by melinath** [comment]
This was the same issue as https://github.com/hashicorp/terraform-provider-google/issues/12721, which has been resolved.
