### ISSUE TITLE
Support new serverless NEG for API gateway via new serverlessDeployment property

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#10061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The latest beta api for the regional network endpoing groups that is used for serverless NEG now supports a new property serverlessDeployment that allows setting a serverless NEG to point to API gateway. 
 It would be nice if this was useable via terraform (https://cloud.google.com/compute/docs/reference/rest/beta/regionNetworkEndpointGroups)

### New or Affected Resource(s)

google_compute_region_network_endpoint_group

### Potential Terraform Configuration

```tf
resource "google_compute_region_network_endpoint_group" "apigateway_neg" {
  name                  = "apigateway-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"
  serverless_deployment {
    platform = "apigateway.googleapis.com"
    resource = <gateway_id>
  }
}
```

### References

https://cloud.google.com/compute/docs/reference/rest/beta/regionNetworkEndpointGroups
* #0000

**Comment by roaks3** [comment]
Per https://github.com/hashicorp/terraform-provider-google/issues/10729, this is now implemented in the beta provider.
