### ISSUE TITLE
Data Block for Compute Disk Resources in Terraform for GCP Provider

### ISSUE THREAD

**Issue by anupam-sy** [hashicorp/terraform-provider-google#10069]
### Community Note

- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request.
- Please do not leave +1 or me too comments, they generate extra noise for issue followers and do not help prioritize the request.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment. If an issue is assigned to the modular-magician user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to hashibot, a community member has claimed the issue already.

### Description
I would like to use boot disk to create an image, but didn't find any data source to fetch the self link for boot disk. Currently I'm hardcoding self link URL for creating a machine image.
Moreover I didn't find any data source block for compute disk. Is this gonna come soon in upcoming release. or is there any alternate way to achieve this?

```
resource "google_compute_image" "example" {
  name = "example-image"

  source_disk = <self_link_url>
}
```

> I found one more resource for creating machine image i.e. "google_compute_machine_image". So there are two options available, which one is best to opt for and why? Is anyone of them is gonna deprecate soon. Suggestions and comments are appreciated.

**Comment by edwardmedia** [comment]
@anupam-sy not available yet. Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) to request. Closing this then
