### ISSUE TITLE
google_compute_global_forwarding_rule creates service directory in fixed region, us-central-1

### ISSUE THREAD

**Issue by steven-edgar** [hashicorp/terraform-provider-google#10076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a google_compute_global_forwarding_rule, per the instructions at 

[https://registry.terraform.io/providers/hashicorp/google/3.82.0/docs/resources/compute_global_forwarding_rule#example-usage---private-service-connect-google-apis](url)

A few Service Directory resources are automatically created, including I believe a service_directory_namespace, service_directory_endpoint and service_directory_service. 

This service directory namespace has its location set to us-central1, with no options visible in the google_compute_global_forwarding_rule to influence that. My current client is in a highly regulated industry that requires all resources to be within Europe, and therefore we are unable to use this code as it stands. 

We need either a flag to set the location that the namespace will exist in, to be consistent with the gcloud command, or an option to prevent Service Directory resources being automatically created if the GCP API supports that. 

I notice that the equivalent gcloud command, documented at 
[https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#gcloud_1](url)
is 
```
gcloud compute forwarding-rules create ENDPOINT_NAME \
  --global \
  --network=NETWORK_NAME \
  --address=ADDRESS_NAME \
  --service-directory-registration=REGION_URI
  --target-google-apis-bundle=API_BUNDLE
```

It would appear that the service-directory-registration field is the one that is missing from this Terraform resource. 

The REGION_URI fed to "--service-directory-registration" takes a URI of format "projects/PROJECT_NAME/locations/REGION". 

### New or Affected Resource(s)

* google_compute_global_forwarding_rule

### Potential Terraform Configuration

```tf
resource "google_compute_global_forwarding_rule" "default" {
  ...
   service_directory_registration = "projects/${google_project.my-project.id}/locations/europe-west1"
}
```
OR
```tf
resource "google_compute_global_forwarding_rule" "default" {
  ...
   create_service_directory = false
}
```
### References

* #0000

**Comment by trowdan** [comment]
I have the same problem, any news about that? Is there any workaround I can do to create that namespace in another region?

**Comment by prankin272** [comment]
hi, is there any update on this? as it is, currently blocked on using this and can't use the service directory module since it is still in beta

**Comment by roaks3** [comment]
It looks like this was _very_ recently fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/9485. Closing as fixed, but it will not go live until the next release (likely to be ~Dec 4)
