### ISSUE TITLE
Apigee Organization Properties are Reset on Resource Update

### ISSUE THREAD

**Issue by danistrebel** [hashicorp/terraform-provider-google#10075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.84.0
```

### Affected Resource(s)

* google_apigee_organization

### Terraform Configuration Files

```tf
resource "google_apigee_organization" "org" {
  project_id = "my-apigee-org"
  analytics_region   = "europe-west1"
  runtime_type= "HYBRID"
}
```

### Expected Behavior

Apigee hybrid org should respect the existing org properties at apply

### Actual Behavior

Terraform apply removes non-default org properties.

From what I gathered so far:

Terraform provider [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/blob/a488d43e49a70a2556fb118064dd31980c1a2bb0/mmv1/products/apigee/api.yaml#L67) does not have the Apigee org `properties` defined that are set on the Apigee Org API resource e.g. :

```json
"properties": {
    "property": [
      {
        "name": "features.hybrid.enabled",
        "value": "true"
      },
      {
        "name": "features.mart.connect.enabled",
        "value": "true"
      }
    ]
  }
```

as a TF resource property and therefore updates reset the properties on the organization. This currently removes the `features.mart.connect.enabled` property that is required for Apigee hybrid.

### Steps to Reproduce

1. create an Apigee hybrid org via API
1. check the org property via: `curl -H "Authorization: Bearer $TOKEN"  -H "content-type:application/json" https://apigee.googleapis.com/v1/organizations/my-apigee-org` and validate that the `features.mart.connect.enabled` property is set.
1. tf import the existing Apigee org `terraform import google_apigee_organization.org organizations/my-apigee-org`
1. make sure there are diffs that would require an org update
1.`terraform apply`
1. check the org property via: `curl -H "Authorization: Bearer $TOKEN"  -H "content-type:application/json" https://apigee.googleapis.com/v1/organizations/my-apigee-org` and find that the `features.mart.connect.enabled` property is no longer set.

**Comment by pdallecarbonare** [comment]
This problem seems to affect only Apigee Org's created before version 1.4.x.

**Comment by edwardmedia** [comment]
@danistrebel that is a new field. Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) to request it. closing the issue then

**Comment by danistrebel** [comment]
@pdallecarbonare the issue also exists with 1.5 and 1.6 orgs.
