### ISSUE TITLE
google_cloudbuild_trigger not accepting repository-related information when using webhook_config and filename

### ISSUE THREAD

**Issue by giefferre** [hashicorp/terraform-provider-google#10085]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.84.0
````

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "webhooktrigger" {
  name = format("%s-myapp-webhook-trigger", var.environment)

  webhook_config {
    secret = google_secret_manager_secret_version.webhook.name
  }

  filename = format("cloudbuild/%s.yaml", var.cloudbuild_filename)

  # There is no way I can specify the repository (in this case on 
  # Github, but same happens for GCP hosted repos)
  # neither the branch name or tags to trigger the build for.
  # This is in fact possible using the GCP console in the browser!
}
```

### Expected Behavior

I expected to have a way to specify the source repository configuration for the webhook to use for the build.

### Actual Behavior

The webhook has been created but it does not point to a repository configuration (name AND branch or tag).

This is in fact possible using the online console, please see attached screenshot

<img width="528" alt="Screenshot 2021-09-16 at 16 22 01" src="https://user-images.githubusercontent.com/1171932/133629754-9dd57f54-faa7-442c-92d6-33e1d80b6a4c.png">

### Steps to Reproduce

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger

**Comment by edwardmedia** [comment]
@giefferre have you checked out [trigger_template](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#trigger_template) to see if that helps?

**Comment by giefferre** [comment]
> @giefferre have you checked out [trigger_template](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#trigger_template) to see if that helps?

Hi @edwardmedia and thanks for the prompt reply.

Of course I had checked, but as the reference you linked says:

> One of trigger_template, github, pubsub_config or webhook_config must be provided.

So it is NOT compatible as the `webhook_config` is present.

**Comment by edwardmedia** [comment]
@giefferre can you try something like below?

```tf
resource "google_cloudbuild_trigger" "webhook-trigger" {
  webhook_config {
      secret = "projects/573164781234/secrets/webhook-secret/versions/1"
  }
  name = "tfbuild"
    build {
        step {
        name = "gcr.io/cloud-builders/gsutil"
        args = ["cp", "gs://mybucket/remotefile.zip", "localfile.zip"]
        timeout = "120s"
        }
        source {
            repo_source {
                repo_name = "https://github.com/edwardmedia/cbloud"
                branch_name = "master"
            }
        }
    }
}
```

**Comment by giefferre** [comment]
@edwardmedia this would not be the same.

I specifically need the `filename` property as the Cloud Build steps are defined in such a file (located on the github repo).

If I also add the `build` block and keep the `filename` Terraform errors as

> Either a filename or build template must be provided.

**Comment by edwardmedia** [comment]
@giefferre I see. Currently this is not supported in the provider. `sourceToBuild` needs to be added to be like below request payload.  Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) to request the feature. Closing this issue accordingly

```
{
 "sourceToBuild": {
    "ref": "master",
    "uri": "https://github.com/edwardmedia/cbloud",
    "repoType":"GITHUB"
 },
 "filename": "cloudbuild.yaml",
 "name": "tfbuild2",
 "webhookConfig": {
  "secret": "projects/573164781234/secrets/webhook-secret/versions/1"
 }
}
```
