### ISSUE TITLE
Multiple attachments to the same apigee environment or instance failing

### ISSUE THREAD

**Issue by irina-gherman-db** [hashicorp/terraform-provider-google#10084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

google_apigee_instance_attachment

### Terraform Configuration Files

```tf
resource "google_apigee_instance" "apigee_instance" {
  name     = "tf-test%{random_suffix}"
  location = "us-central1-b"
  org_id   = google_apigee_organization.apigee_org.id
}
resource "google_apigee_environment" "env_1" {
  name        = "tf-test%{random_suffix}"
  description = "Apigee Environment 1"
  displayName = "environment-1"
  org_id      = google_apigee_organization.apigee_org.id
}

resource "google_apigee_environment" "env_2" {
  name        = "tf-test%{random_suffix}"
  description = "Apigee Environment 2"
  displayName = "environment-2"
  org_id      = google_apigee_organization.apigee_org.id
}

resource "google_apigee_instance_attachment" "attachment_1" {
  instance_id  = google_apigee_instance.apigee_instance.id
  environment  = google_apigee_environment.env_1.name
}

resource "google_apigee_instance_attachment" "attachment_2" {
  instance_id  = google_apigee_instance.apigee_instance.id
  environment  = google_apigee_environment.env_2.name
}
```

### Expected Behavior

Both environments are attached to the apigee instance

### Actual Behavior

One of the attachments will fail as there is a lock, while the rest are failing. 
google_apigee_instance_attachment.attachment_1: Creating...
google_apigee_instance_attachment.attachment_2: Creating...
google_apigee_instance_attachment.attachment_1: Still creating... [10s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [20s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [30s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [40s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [50s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m0s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m10s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m20s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m30s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m40s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [1m50s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [2m0s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [2m10s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [2m20s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [2m30s elapsed]
google_apigee_instance_attachment.attachment_1: Still creating... [2m40s elapsed]
google_apigee_instance_attachment.attachment_1: Creation complete after 2m47s [id=organizations/<myorgid>/instances/<myinstancename>/attachments/<uuid-attachment-id>]

Error: Error creating InstanceAttachment: googleapi: Error 400: the resource is locked by another operation: opid-opid-opid
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.RequestInfo",
    "requestId": "myrequestid"
  }
]

This behaviour forces us to re-run the pipeline multipline times until all the environments are attached to the instance. 

The same behaviour is encountered while de-attaching multiple environments at the same time.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by matt-hottinger** [comment]
FWIW, the same exact problem exists when attempting to create multiple instances. 

**Provider Version**
hashicorp/google v3.90.0

**Affected Resource(s)**
google_apigee_instance

**Expected Behavior**
Both Apigee Instance are created successfully

**Actual Behavior**
```
google_apigee_instance.apigee_instance["region1"]: Creating...
google_apigee_instance.apigee_instance["region2"]: Creating...
google_apigee_instance.apigee_instance["region1"]: Still creating... [10s elapsed]
google_apigee_instance.apigee_instance["region1"]: Still creating... [20s elapsed]
google_apigee_instance.apigee_instance["region1"]: Still creating... [30s elapsed]
google_apigee_instance.apigee_instance["region1"]: Still creating... [40s elapsed]
....
google_apigee_instance.apigee_instance["region1"]: Still creating... [23m50s elapsed]
google_apigee_instance.apigee_instance["region1"]: Still creating... [24m0s elapsed]
google_apigee_instance.apigee_instance["region1"]: Still creating... [24m10s elapsed]
google_apigee_instance.apigee_instance["region1"]: Creation complete after 24m19s [id=organizations/my-apigee-org/instances/region1]
error	01-Nov-2021 14:06:54	[31m│[0m [0m[1m[31mError: [0m[0m[1mError creating Instance: googleapi: Error 400: the resource is locked by another operation: guid-guid-guid-guid
error	01-Nov-2021 14:06:54	[31m│[0m [0mDetails:
error	01-Nov-2021 14:06:54	[31m│[0m [0m[
error	01-Nov-2021 14:06:54	[31m│[0m [0m  {
error	01-Nov-2021 14:06:54	[31m│[0m [0m    "@type": "type.googleapis.com/google.rpc.RequestInfo",
error	01-Nov-2021 14:06:54	[31m│[0m [0m    "requestId": "rqId"
error	01-Nov-2021 14:06:54	[31m│[0m [0m  }
error	01-Nov-2021 14:06:54	[31m│[0m [0m][0m
error	01-Nov-2021 14:06:54	[31m│[0m [0m
error	01-Nov-2021 14:06:54	[31m│[0m [0m[0m  with google_apigee_instance.apigee_instance["region2"],
error	01-Nov-2021 14:06:54	[31m│[0m [0m  on main.tf line 66, in resource "google_apigee_instance" "apigee_instance":
error	01-Nov-2021 14:06:54	[31m│[0m [0m  66: resource "google_apigee_instance" "apigee_instance"
```

Since the problem seems to be similar enough, I though it would be sufficient to consider this an "Interesting Factoid" on the original bug report, but since they are technically different resources I could see the necessity to create a separate bug report. Open to either, just let me know.

**Comment by ScottSuarez** [comment]
Fixed, please create a separate issue topic fo `google_apigee_instance`
