### ISSUE TITLE
Track Apigee Organization Properties

### ISSUE THREAD

**Issue by danistrebel** [hashicorp/terraform-provider-google#10083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Terraform apply removes non-default Apigee org properties.

From what I gathered so far:

Terraform provider [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/blob/a488d43e49a70a2556fb118064dd31980c1a2bb0/mmv1/products/apigee/api.yaml#L67) does not have the Apigee org properties defined that are set on the Apigee Org API resource e.g. :
```json
"properties": {
    "property": [
      {
        "name": "features.hybrid.enabled",
        "value": "true"
      },
      {
        "name": "features.mart.connect.enabled",
        "value": "true"
      }
    ]
  }
```  
as a TF resource property and therefore updates reset the properties on the organization. This currently removes the features.mart.connect.enabled property that is required for Apigee hybrid.

### New or Affected Resource(s)

* google_apigee_organization

### Potential Terraform Configuration

Add the `references` field to the [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/blob/a488d43e49a70a2556fb118064dd31980c1a2bb0/mmv1/products/apigee/api.yaml#L67) config.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/10075

**Comment by bartdw** [comment]
We are managing quite some apigee orgs with terraform. After some troubleshooting it turns out this issue is breaking our setup from time to time. Is there any progress on finding a solution for this bug?

**Comment by danistrebel** [comment]
Hi @bartdw, thanks for the +1.

We are still looking into this.

Until the fix is in place, the recommended approach for you would be to use the lifecycle attributes to ignore changes on the Apigee Organization resource and treat it as immutable to prevent the resource from breaking your setup.

**Comment by xuchenma** [comment]
Trying to fix this by https://github.com/GoogleCloudPlatform/magic-modules/pull/5556
