### ISSUE TITLE
google_vertex_ai_featurestore_entitytype:  Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'

### ISSUE THREAD

**Issue by jefersonrjrn** [hashicorp/terraform-provider-google#10100]
### Terraform Version

Terraform 1.0.3

### Affected Resource(s)

* google_vertex_ai_featurestore_entitytype

### Terraform Configuration Files

```tf
resource "google_vertex_ai_featurestore" "featurestore" {
  provider = google-beta

  name     = "featurestore${var.environment}"
  project = var.project
  region   = "us-east1"
  online_serving_config {
    fixed_node_count = var.fixed_node_count
  }
}

resource "google_vertex_ai_featurestore_entitytype" "entity" {
  provider = google-beta

  name     = var.entity_type_id
  featurestore = google_vertex_ai_featurestore.featurestore.id
}
```

### Debug Output

![image](https://user-images.githubusercontent.com/59900069/133846308-8949eba9-beaa-4167-b8c4-908a87442c9f.png)

### Expected Behavior

Created a new Entity Type resource.

### Actual Behavior

The Entity Type resource cannot be created.

### Steps to Reproduce

1. `terraform apply`

### Additional information

In Terraform Registry for the *google_vertex_ai_featurestore_entitytype* there is no arguments to input a region.
Reference: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype

**Comment by imrannayer** [comment]
Seems like `google_vertex_ai_featurestore_entitytype` is missing region parameter. Adding parameter to provider works fine but it is not a desirable way of deploying resource.
