### ISSUE TITLE
Implement monitoring metrics scope and monitored project resources

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#10113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_monitoring_monitored_project
* google_monitoring_metrics_scope

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_monitoring_monitored_project" "primary" {
  metrics_scope = google_monitoring_metrics_scope.basic.name
  name          = google_project.basic.name
}

resource "google_project" "basic" {
  project_id = "id%{random_suffix}"
  name       = "id%{random_suffix}"
  org_id     = "%{org_id}"
}

resource "google_monitoring_metrics_scope" "basic" {
  name = "%{project_name}"
}
```

**Comment by mikemeiercb** [comment]
I see you submitted a corresponding PR for this (thanks!). I would recommend to keep the naming of the resources consistent with the [documentation ](https://cloud.google.com/monitoring/settings#visibility) that it be called a google_monitoring_scoping_project instead of a metrics_scope to be more clear.

**Comment by philip-harvey** [comment]
Looking into getting monitoring scopes and monitored projects working as part of a larger GCP migration project and excited to find this is in progress.  Should this issue be re-opened since it was reverted?

**Comment by ndmckinley** [comment]
It was un-reverted and will be released on the 4th.  :)

**Comment by philip-harvey** [comment]
I thought only google_monitoring_monitored_project was un-reverted and that google_monitoring_metrics_scope is not yet implemented?  Or am I misunderstanding?  Thanks.

**Comment by ndmckinley** [comment]
No, that's correct, but `monitored_project` is the only resource - `metrics_scope` does not contain any data or editable fields, once `monitored_project` exists, so there's no need for `metrics_scope`.

**Comment by philip-harvey** [comment]
Any ideas on where to find documentation on how to use this now that it is in the Beta provider?  Thanks.

**Comment by philip-harvey** [comment]
I think I managed to work out what it is looking for.
```
resource "google_monitoring_monitored_project" "monitored-project" {
  provider = google-beta
  metrics_scope = google_project.scoping-project.name
  name = google_project.monitored-project.name
}
```

**Comment by ndmckinley** [comment]
Yep!  Unfortunately due to https://github.com/hashicorp/terraform-provider-google/issues/10252, we currently only show docs for this on the beta provider page, and it is not easy to find.  Here it is:

https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/monitoring_monitored_project

And the relevant example is also not being generated well - your example is better than what winds up on that page.  We'll look into that as part of #10252.

**Comment by amitcodex** [comment]
Has anyone else run into this issue? ```Error: Error creating MonitoredProject: Resource already exists - apply blocked by lifecycle params: &beta.MonitoredProject{Name:(*string)(0xc000d271f0), CreateTime:(*string)(0xc000bd3950), MetricsScope:(*string)(0xc000d270f0)}.```

I destroyed the project I was using to monitor (with `terragrunt destroy`) and reinitialized it.
