### ISSUE TITLE
Filestore: Shared VPC Not Supported

### ISSUE THREAD

**Issue by rbuttiero-lvmh** [hashicorp/terraform-provider-google#10116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.85.0
+ provider registry.terraform.io/hashicorp/google-beta v3.85.0
```

### Affected Resource(s)

* google_filestore_instance

### Terraform Configuration Files

```tf
resource "google_filestore_instance" "instance" {
  project  = "service-project"
  name     = "test-instance"
  zone     = "europe-west1-b"
  tier     = "BASIC_HDD"

  file_shares {
    name        = "share1"
    capacity_gb = 1024
  }

  networks {
    network = "projects/host-project/global/networks/shared-vpc"
    modes   = ["MODE_IPV4"]
  }
}
```

### Expected Behavior

A Filestore instance in the service-project using the Shared VPC should be deployed.

### Actual Behavior

The terraform apply command fails :

```bash
google_filestore_instance.instance: Creating...
╷
│ Error: Error creating Instance: googleapi: Error 400: invalid value for "network name": "projects/host-project/global/networks/shared-vpc". Must be a match of regex "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$", (ID must start with a lowercase letter followed by up to 62 lowercase letters, numbers, or hyphens, and cannot end with a hyphen).
│ 
│   with google_filestore_instance.instance,
│   on filestore.tf line 30, in resource "google_filestore_instance" "instance":
│   30: resource "google_filestore_instance" "instance" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #5228 (previous issue, closed because GCP didn't support it at the time)
* <https://cloud.google.com/filestore/docs/shared-vpc>

**Comment by omarkammoun** [comment]
Hello,
I'm having the same issue, I'm forced to manually create and import the filestore instance while this is not resolved.
Thanks to anyone working on this.
Rergards,
Omar

**Comment by omarkammoun** [comment]
Bonjour,
On a shared VPC, the filestore only works with a `private service access`
It is therefore necessary to add the attribute `connect_mode = "PRIVATE_SERVICE_ACCESS" `
At the moment, it only works with the Beta provider, since it's only the Google Beta APIs that can do this.
So you have to add `provider = google-beta` and of course you have to declare the provider googe-beta 
```provider "google-beta" {
}```

**Comment by sgarciajaramillo** [comment]
@omarkammoun  thanks a lot for the code details.
I've tried it as below (variables and data resources OK) and I'm getting the following error.

Thanks a lot!

```
Terraform v0.15.5, v1.0.7, v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.88.0
+ provider registry.terraform.io/hashicorp/google-beta v3.88.0
```

> ---[ REQUEST ]---------------------------------------
POST /v1beta1/projects/SERVICE-PROJECT-ID/locations/us-central1-b/instances?alt=json&instanceId=NAME HTTP/1.1
Host: file.googleapis.com
User-Agent: Terraform/1.0.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/3.88.0
Content-Length: 458
Content-Type: application/json
Accept-Encoding: gzip

>{
 "fileShares": [
  {
   "capacityGb": 1024,
   "name": "NAME",
  }
 ],
 "labels": {
  "env": "dev",
  "provisioner": "terraform"
 },
 "networks": [
  {
   "connectMode": "PRIVATE_SERVICE_ACCESS",
   "modes": [
    "MODE_IPV4"
   ],
   "network": "https://www.googleapis.com/compute/v1/projects/host-project/global/networks/net-name",
   "reservedIpRange": "filestore-addr"
  }
 ],
 "tier": "BASIC_HDD"
}

>-----------------------------------------------------: timestamp=2021-10-17T15:56:17.094-0700
2021-10-17T15:56:17.392-0700 [INFO]  provider.terraform-provider-google-beta_v3.88.0_x5: 2021/10/17 15:56:17 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 500 Internal Server Error
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 17 Oct 2021 22:56:17 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

>{
  "error": {
    "code": 500,
    "message": "An internal error has occurred (6ba97048-bbcc-4ea6-8d90-f001510c7e7f)",
    "status": "INTERNAL"
  }
}

```tf
resource "google_compute_global_address" "filestore" {
  name          = "filestore-addr"
  purpose       = "VPC_PEERING"
  address       = "X.X.X.X"
  address_type  = "INTERNAL"
  prefix_length = 24
  network       = data.google_compute_network.shared_vpc_network.id
  project       = var.shared_vpc_project_id
}

resource "google_service_networking_connection" "private_service_access" {
  provider                = google-beta
  network                 = data.google_compute_network.shared_vpc_network.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.filestore.name]
}

resource "google_filestore_instance" "instance" {
  provider = google-beta
  project = service-project.project_id
  name = "NAME"
  zone = var.zone
  tier = "BASIC_HDD"
  labels = var.labels
  
  file_shares {
    capacity_gb = var.capacity_gb
    name        = "NAME"
  }

  networks {
    network = data.google_compute_network.shared_vpc_network.self_link
    modes   = ["MODE_IPV4"]
    connect_mode = "PRIVATE_SERVICE_ACCESS"
    reserved_ip_range = google_compute_global_address.filestore.name
  }

  lifecycle {
    ignore_changes = [
      networks[0].reserved_ip_range
    ]
  }
 depends_on = [google_service_networking_connection.private_service_access]
}
```
