### ISSUE TITLE
improve handling of service agents with  google_project_iam_policy and google_iam_policy

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#10110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is a request to improve service agent handling when setting project-level IAM policy via the resource google_project_iam_policy and the data source google_iam_policy.  Currently unless you explicitly include service agents when setting google_project_iam_policy (via bindings defined in a coresponding data source google_iam_policy) the bindings of service agents will be removed.  I'm proposing some way of using this which would allow declarative setting of all other project bindings without interfering with the default service agent bindings.

This may not be possible in terraform without changing the underlying GCP APIs (though I don't know where to log an issue for that)

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by slevenick** [comment]
I don't think this is something we will reasonably be able to handle within the provider. Unfortunately the logic around which service accounts permissions need to exist for the default service accounts to work is somewhat complex, as some services need more permissions than the default to work correctly.

We likely don't want to add complex logic around what default roles should exist for specific service agents, as this may change over time and fall out of date. If this was provided by the API it would be a more reasonable undertaking, but lacking support on that I'm going to close this as infeasible.

You can request API changes here: https://cloud.google.com/support/docs/issue-trackers#trackers-list
