### ISSUE TITLE
google_bigquery_table is missing the use_avro_logical_types field

### ISSUE THREAD

**Issue by chlirre** [hashicorp/terraform-provider-google#10119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Trying to Terraform the [creation of a hive partitioned external BigQuery table](https://cloud.google.com/bigquery/docs/hive-partitioned-loads-gcs) I ran in to the problem of 

> [BigQuery ignores the logicalType attribute for most of the types and uses the underlying Avro type instead](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#loading_hive-partitioned_avro_data). 

From the command-line or API, this is resolved by setting `use_avro_logical_types=true`. See docs: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#AvroOptions

### New or Affected Resource(s)

* google_bigquery_table
* * external_data_configuration
* * * avro_options (NEW)
* * * * use_avro_logical_types (NEW)

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "external_table" {
  ...
  external_data_configuration {
    ...
    avro_options {
      use_avro_logical_types = true
    }
  }
}
```

### References

* https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#AvroOptions
* https://cloud.google.com/bigquery/docs/hive-partitioned-loads-gcs
* https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#loading_hive-partitioned_avro_data
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_job#use_avro_logical_types

**Comment by melinath** [comment]
b/245987699
