### ISSUE TITLE
"google_apigee_instance" should support a "peering_cidr_range" values from /16 through /20 

### ISSUE THREAD

**Issue by jaredweeks** [hashicorp/terraform-provider-google#10112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Apigee paid org runtime instances now support provisioning with any peering CIDR range from /16 through /20. My company needs to provision various sized runtime instances to meet our needs. Currently we can't do this in Terraform and need to break the instance create code into shell scripting and making the calls through the API via CURL. Not ideal.

### New or Affected Resource(s)

* google_apigee_instance

### Potential Terraform Configuration

resource "google_apigee_instance" "apigee_instance_us_east4" {
 depends_on = [ google_kms_crypto_key_iam_binding.apigee_sa_keyuser_runinst ]         
 name                     = "us-east4"
 location                 = "us-east4"
 description              = "Terraform-managed Apigee Runtime Instance USEAST4"
 display_name             = "us-east4"
 org_id                   = google_apigee_organization.org.id
 peering_cidr_range       = **"SLASH_18"**
 disk_encryption_key_name = google_kms_crypto_key.apigee_cryptokeyruninst_us4.id
}

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by matt-hottinger** [comment]
Hey @ScottSuarez, could you provide a general timeline for when this will be published in a future release?

**Comment by ScottSuarez** [comment]
This should be released today
