### ISSUE TITLE
Docs clarification for compute_instance settings

### ISSUE THREAD

**Issue by scarolan** [hashicorp/terraform-provider-google#10133]
This suggested replacement is for this page:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance

**This section:**

The network_interface block supports:
network - (Optional) The name or self_link of the network to attach this interface to. Either network or subnetwork must be provided.
subnetwork - (Optional) The name or self_link of the subnetwork to attach this interface to. The subnetwork must exist in the same region this instance will be created in. If network isn’t provided it will be inferred from the subnetwork. Either network or subnetwork must be provided.

**Should be updated to be more clear on how the provider behaves:**

The network_interface block supports network and subnetwork options. Only one of these should be specified.
network - The name or self_link of the network to attach this interface to. If you use network there must be a matching subnet with the same name in your target region. Google creates a subnet called default in every region, so this is a good option if you’re using the default network.
subnetwork - The name or self_link of the subnetwork to attach this interface to. The subnetwork must exist in the same region this instance will be created in. With this option the provider will automatically determine the network from the subnetwork name. If you are using anything other than the default network in your project, you should choose this option.

**Comment by melinath** [comment]
It's not clear to me that this proposed change is an improvement - for now I'm closing this ticket[1], but please feel free to post here with the following information:

- What about the current documentation is confusing or incomplete?
- What about the new documentation is better?
- (if it's not answered by one of those) Why should you use subnetwork if you're not using the default network?

If you have specific changes you want to suggest, you can also make a PR that alters this file: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/website/docs/r/compute_instance.html.markdown

[1] I will also open a PR referencing this ticket that updates the field docs to more closely match the API docs.
