### ISSUE TITLE
google_bigquery_dataset_access disappears after editing google_bigquery_dataset_iam_*

### ISSUE THREAD

**Issue by StefanN-Otto** [hashicorp/terraform-provider-google#10156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.85.0

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_bigquery_dataset_iam_*
* google_bigquery_dataset_access

### Terraform Configuration Files

before the change:

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

provider "google" {
  project = var.project
}

variable "project" {}
variable "viewer" {}

resource "google_bigquery_dataset" "private" {
  dataset_id = "private"
}

resource "google_bigquery_dataset" "public" {
  dataset_id = "public"
}

resource "google_bigquery_table" "test_data" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  table_id = "test_data"
  deletion_protection = false

  schema = jsonencode([
    {
      mode: "REQUIRED",
      name: "name",
      type: "STRING"
    },
	{
      mode: "REQUIRED",
      name: "secret_id",
      type: "STRING"
    }
  ])
}

resource "google_bigquery_table" "view" {
  dataset_id = google_bigquery_dataset.public.dataset_id
  table_id = "test_data"
  deletion_protection = false
  view {
    use_legacy_sql = false
    query = <<SQL_STATEMENT
        SELECT name FROM private.test_data
    SQL_STATEMENT
  }
}

resource "google_bigquery_dataset_access" "view_access" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  view {
    project_id = var.project
    dataset_id = google_bigquery_dataset.public.dataset_id
    table_id = google_bigquery_table.view.table_id
  }
}

/*
resource "google_bigquery_dataset_iam_member" "viewer" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  member = "user:${var.viewer}"
  role = "roles/bigquery.dataViewer"
}
*/
```

after the change:

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

provider "google" {
  project = var.project
}

variable "project" {}
variable "viewer" {}

resource "google_bigquery_dataset" "private" {
  dataset_id = "private"
}

resource "google_bigquery_dataset" "public" {
  dataset_id = "public"
}

resource "google_bigquery_table" "test_data" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  table_id = "test_data"
  deletion_protection = false

  schema = jsonencode([
    {
      mode: "REQUIRED",
      name: "name",
      type: "STRING"
    },
	{
      mode: "REQUIRED",
      name: "secret_id",
      type: "STRING"
    }
  ])
}

resource "google_bigquery_table" "view" {
  dataset_id = google_bigquery_dataset.public.dataset_id
  table_id = "test_data"
  deletion_protection = false
  view {
    use_legacy_sql = false
    query = <<SQL_STATEMENT
        SELECT name FROM private.test_data
    SQL_STATEMENT
  }
}

resource "google_bigquery_dataset_access" "view_access" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  view {
    project_id = var.project
    dataset_id = google_bigquery_dataset.public.dataset_id
    table_id = google_bigquery_table.view.table_id
  }
}

// new resource
resource "google_bigquery_dataset_iam_member" "viewer" {
  dataset_id = google_bigquery_dataset.private.dataset_id
  member = "user:${var.viewer}"
  role = "roles/bigquery.dataViewer"
}
```

### Debug Output

https://gist.github.com/StefanN-Otto/ff7d433a6db9c544bc90824a7bc40698

### Panic Output

<None>

### Expected Behavior

The Dataset IAM Member should be added, thus giving him read access to the Dataset. Nothing else should change.

### Actual Behavior

The Dataset IAM Member is added, thus giving him read access to the Dataset. Also the Authorized View is dropped.

When redoing terraform apply there is a new diff:
`# google_bigquery_dataset_access.view_access will be created`
Full output: https://gist.github.com/StefanN-Otto/9448822d2286511006da6dd3022a4bbc

After that everything is as expected.

### Steps to Reproduce

1. Start with the first terraform file. Apply it to a project of you choice with yourself as viewer:

```
terraform init
terraform apply -var=project=<project> -var=viewer=<your google account>
```

2. remove the comment around the last resource
3. reexecute terraform:

```
terraform apply -var=project=<project> -var=viewer=<your google account>
```

### Important Factoids

In the example provided above, I only added a google_bigquery_iam_member, but any editing of google_bigquery_iam_* resources leads to this beahaviour

### References

the view parts of the access structure are ignored in iam_bigquery_dataset.go, thus removing them:
https://github.com/hashicorp/terraform-provider-google/blob/d14962be434a56e6802f6d242c7ad41bc0ccc7ef/google/iam_bigquery_dataset.go#L131

**Comment by melinath** [comment]
Unfortunately, this is just how these resources interact. You need to choose either IAM or the dataset_access resource. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam for details:

> [bigquery_dataset_iam_*] resources cannot be used with google_bigquery_dataset_access resources or the access field on google_bigquery_dataset or they will fight over what the policy should be.
