### ISSUE TITLE
At least some sweepers are sweeping empty resources

### ISSUE THREAD

**Issue by nat-henderson** [hashicorp/terraform-provider-google#10151]
### Affected Resource(s)

* google_*

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### issue

Thomas spotted this in the logs for a sweeper test earlier today - there seem to be a significant number of these resources where the project (or other parent) are empty, and therefore we get 404 responses from the server - which the sweeper takes to mean that nothing needs to be done, rather than returning an error.

```
 ---[ REQUEST ]---------------------------------------
11:47:23
  GET /v2//deidentifyTemplates?alt=json HTTP/1.1
11:47:23
  Host: dlp.googleapis.com
11:47:23
  Content-Type: application/json
11:47:23
  Accept-Encoding: gzip
11:47:23
```

Bug is to investigate - is this happening a lot?  Maybe start by searching `//` and `/?`, which are two strings that show up a lot with empty-name issues but rarely show up when things are working correctly.  If it's happening a lot, broad fix, if rarely, point fix.

**Comment by hao-nan-li** [comment]
I think this sweeper has been disabled previously, closing this.
