### ISSUE TITLE
Cloud Run - how to allocate always-on CPU

### ISSUE THREAD

**Issue by mattcollier** [hashicorp/terraform-provider-google#10154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP has recently introduced always-on CPU allocation for Cloud Run into public preview.  Is it already possible to enable this feature via a metadata annotation?

https://cloud.google.com/blog/products/serverless/cloud-run-gets-always-on-cpu-allocation

**Comment by c2thorn** [comment]
This should be available via metadata annotation:
https://cloud.google.com/run/docs/configuring/cpu-allocation#yaml

From the documentation, it seems setting `run.googleapis.com/cpu-throttling` to `false` is the way to go
