### ISSUE TITLE
Provider 3.75.0 and higher at least to 3.87.0 not handling change of big query table keys to versions correctly

### ISSUE THREAD

**Issue by MikeMoore63** [hashicorp/terraform-provider-google#10163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.75.0
+ provider registry.terraform.io/hashicorp/google-beta v3.75.0
+ provider registry.terraform.io/hashicorp/local v1.4.0

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```
resource "google_bigquery_table" "eimtables" {
  provider = google.deploy_provider
  for_each = local.eimtables
  dataset_id = google_bigquery_dataset.eim_dataset.dataset_id
  friendly_name = each.key
  table_id = each.key
  labels = each.value["labels"]
  schema = file(each.value["schema"])
  clustering = each.value["clustering"]
  expiration_time = each.value["expiration_time"]
  project = local.eimproject["region1"]
  description = each.value["description"]

  dynamic "time_partitioning" {
    for_each = each.value["time_partitioning"] != null ? [
      each.value["time_partitioning"]] : []
    content {
      type = time_partitioning.value["type"]
      expiration_ms = time_partitioning.value["expiration_ms"]
      field = time_partitioning.value["field"]
      require_partition_filter = time_partitioning.value["require_partition_filter"]
    }
  }
  encryption_configuration {
    kms_key_name = local.bqkeyconfidentiatlitylow
  }

}
```
### Debug Output

Not releavnt

### Panic Output

Not relevant

### Expected Behavior

No changes as already configured correctly

### Actual Behavior

```
# google_bigquery_table.eimtables["CCSServerCompliance"] will be updated in-place
Step #2 - "terraform":   ~ resource "google_bigquery_table" "eimtables" {
Step #2 - "terraform":         id                  = "projects/xxxxx-162815/datasets/eimforseti2/tables/CCSServerCompliance"
Step #2 - "terraform":         # (18 unchanged attributes hidden)
Step #2 - "terraform": 
Step #2 - "terraform":       ~ encryption_configuration {
Step #2 - "terraform":           ~ kms_key_name    = "projects/xxxxxx-162815/locations/global/keyRings/bigQuery/cryptoKeys/bigQueryConfidentialityLow/cryptoKeyVersions/10" -> "projects/xxxxx-162815/locations/global/keyRings/bigQuery/cryptoKeys/bigQueryConfidentialityLow"
Step #2 - "terraform":             # (1 unchanged attribute hidden)
Step #2 - "terraform":         }
Step #2 - "terraform": 
Step #2 - "terraform":         # (1 unchanged block hidden)
Step #2 - "terraform":     }
```
Is comparing key version and key Big query has been updated to return version but it is for the right key. Docs have come out from google about this change and version 3.75.0 is supposed to handle this but appears it isn't Luckily it does update which is thankfully harmless but should be no changes.

### Steps to Reproduce

Create terraform big query table with encryption key 
Then once done run apply again will only fail if project has new upgraded behavior

### Important Factoids

This project on early release from google of the upgrade because when google announced we thought we would see issues.

Update your KMS-enabled BigQuery tools by September 1, 2021, to parse cryptoKeyVersions tokens.
Dear Google Cloud Platform Customer,

We are writing to let you know that starting September 1, 2021, BigQuery will start reporting the cryptoKeyVersions of Cloud Key Management Service (KMS) keys. This key is used to protect BigQuery tables and models. After September 1, 2021, the EncryptionConfiguration kmsKeyName field in the table and model metadata will display KMS key names in the following format:

projects/.../locations/.../keyRings/.../cryptoKeys/.../cryptoKeyVersions/...
The previous format was:

projects/.../locations/.../keyRings/.../cryptoKeys/...

**Comment by edwardmedia** [comment]
@MikeMoore63 can you create a minimum config that can repro the issue (your config uses `local` which make it hard to guess)? Also please share the debug log.

**Comment by edwardmedia** [comment]
@MikeMoore63 is this still an issue?

**Comment by MikeMoore63** [comment]
and with latest same issue
```
variable "project" {
  description = "The project to deploy with"
  default     = ""
  type        = string
}
variable "assume_role" {
  description = "The service account to impersonate if reuired"
  default     = ""
  type        = string
}
variable "kmskey" {
  description = "the cmek key to use"
  default     = ""
  type        = string
}
locals {
  eimtablelist             = [
    {
      table_id          = "table1",
      schema            = jsonencode([
        {
          name = "field1",
          type = "STRING",
          mode = "NULLABLE"
        }
      ]),
      description       = null
      time_partitioning = {
        type                     = "DAY",
        field                    = null,
        require_partition_filter = false,
        expiration_ms            = 94608000000,
      },
      expiration_time   = null
      clustering        = [
      ],
      labels            = {
      }
    }
  ]
  eimproject               = {
    region1 = var.project
  }
  eimtables                = {for table in local.eimtablelist : table["table_id"] => table}
  bqkeyconfidentiatlitylow = var.kmskey
}


terraform {
  required_providers {
    google      = {
      source  = "hashicorp/google"
      version = "~> 3.87.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 3.87.0"
    }
    local       = {
      source  = "hashicorp/local"
      version = "~> 1.4.0"
    }
  }
}

provider "google" {
  project = var.project
  scopes  = var.assume_role == "" ? [
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/pubsub",
    "https://www.googleapis.com/auth/cloud-platform.read-only",
    "https://www.googleapis.com/auth/source.read_only",
    "https://www.googleapis.com/auth/devstorage.full_control",
    "https://www.googleapis.com/auth/compute",
    "https://www.googleapis.com/auth/cloudkms"
  ] : [
    "https://www.googleapis.com/auth/cloud-platform.read-only"
  ]
}

provider "google-beta" {
  project = var.project
  scopes  = var.assume_role == "" ? [
    "https://www.googleapis.com/auth/cloud-platform"
  ] : [
    "https://www.googleapis.com/auth/cloud-platform.read-only"
  ]
}

data "google_client_config" "default" {

}

data "google_service_account_access_token" "assume_role" {
  count                  = var.assume_role == "" ? 0 : 1
  provider               = google
  target_service_account = var.assume_role
  scopes                 = [
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/pubsub",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/source.read_only",
    "https://www.googleapis.com/auth/devstorage.full_control",
    "https://www.googleapis.com/auth/compute",
    "https://www.googleapis.com/auth/cloudkms"
  ]
  lifetime               = "2500s"
}

provider "google" {
  alias        = "deploy_provider"
  project      = var.project
  access_token = var.assume_role == "" ? data.google_client_config.default.access_token : data.google_service_account_access_token.assume_role[0].access_token
}

provider "google-beta" {
  alias        = "beta_deploy_provider"
  project      = var.project
  access_token = var.assume_role == "" ? data.google_client_config.default.access_token : data.google_service_account_access_token.assume_role[0].access_token
}

resource "google_bigquery_dataset" "eim_dataset" {
  provider   = google.deploy_provider
  dataset_id = "example_dataset"
  location   = "EU"

}

resource "google_bigquery_table" "eimtables" {
  provider        = google.deploy_provider
  for_each        = local.eimtables
  dataset_id      = google_bigquery_dataset.eim_dataset.dataset_id
  friendly_name   = each.key
  table_id        = each.key
  labels          = each.value["labels"]
  schema          = each.value["schema"]
  clustering      = each.value["clustering"]
  expiration_time = each.value["expiration_time"]
  project         = local.eimproject["region1"]
  description     = each.value["description"]

  dynamic "time_partitioning" {
    for_each = each.value["time_partitioning"] != null ? [
      each.value["time_partitioning"]
    ] : []
    content {
      type                     = time_partitioning.value["type"]
      expiration_ms            = time_partitioning.value["expiration_ms"]
      field                    = time_partitioning.value["field"]
      require_partition_filter = time_partitioning.value["require_partition_filter"]
    }
  }
  encryption_configuration {
    kms_key_name = local.bqkeyconfidentiatlitylow
  }

}
```

**Comment by MikeMoore63** [comment]
so looks to fail in all versions so yes it is very much an issue

**Comment by MikeMoore63** [comment]
Only 2 variables are required projectid and key i.e.
project="projectid"
kmskey="cryptokey"

thats it
There are no errors at all just does it the debug log will have my project in not interested in sharing this. You can repeat the test yourself so not sure why you need me to do it I have provided an exact implementation that repeats the error. So should be able toget the debug yourself.

**Comment by MikeMoore63** [comment]
I am aware the output field has been added but not sure how this helps. I don't want to have to care about this change from a terrafom perspective and expecting not to have too.

**Comment by edwardmedia** [comment]
@MikeMoore63 using below config, it seems I can't repro the issue. In your config, it seems `local.bqkeyconfidentiatlitylow` is static. Am I right? What format of its data do you see?

```
  encryption_configuration {
    kms_key_name = "projects/myproject/locations/global/keyRings/issue10163keyring/cryptoKeys/issue10163key"
  }
```

```
  encryption_configuration {
    kms_key_name = local.bqkeyconfidentiatlitylow
  }
```

**Comment by MikeMoore63** [comment]
yes my key is exactly of that form to reproduce the issue. Note the roll out of change has to have happened on your project by Google. If you have not had the change rolled out the problem cannot be reproduced.

**Comment by MikeMoore63** [comment]
You can tell if its rolled out by using table get if you get the version back it has happened if you do not it has not.

**Comment by marktru** [comment]
Internal issue: [http://b/216801885](http://b/216801885)

**Comment by marktru** [comment]
@megan07 if you've got cycles this onduty do you mind taking a look at this?

Thanks!
