### ISSUE TITLE
google_service_directory_endpoint cannot be updated with a new service, errors with "The update_mask must be set, and must contain a non-empty paths list"

### ISSUE THREAD

**Issue by zlatina-lazarova-db** [hashicorp/terraform-provider-google#10177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 v0.14.11

### Affected Resource(s)

* google_service_directory_endpoint

### Debug Output

Error: Error updating Endpoint "projects/someproject/locations/somelocation/namespaces/example/services/example/endpoints/example": googleapi: Error 400: The update_mask must be set, and must contain a non-empty paths list.

### Expected Behavior

Endpoint should be updated with new service

### Actual Behavior

Error on Apply

### Steps to Reproduce

Create google_service_directory_service (let's call it service_X)
Create google_service_directory_service (let's call it service_Y)
Create a google_service_directory_endpoint with a specific google_service_directory_service (service_X)
Apply changes above
Remove google_service_directory_service (service_X) and update the endpoint to use google_service_directory_service (service_Y)
On apply of the above you should see an error 

### References

https://cloud.google.com/service-directory/docs/reference/rpc/google.cloud.servicedirectory.v1beta1#updateendpointrequest

**Comment by edwardmedia** [comment]
@zlatina-lazarova-db can you share the config are you using? Also please share the debug log as well.

**Comment by zlatina-lazarova-db** [comment]
Apply the below

```
resource "google_service_directory_namespace" "example" {
  provider     = google-beta
  namespace_id = "example-namespace"
  location     = "us-central1"
}

resource "google_service_directory_service" "example_X" {
  provider   = google-beta
  service_id = "example-service-x"
  namespace  = google_service_directory_namespace.example.id
}

resource "google_service_directory_service" "example_Y" {
  provider   = google-beta
  service_id = "example-service-y"
  namespace  = google_service_directory_namespace.example.id
}

resource "google_service_directory_endpoint" "example" {
  provider    = google-beta
  endpoint_id = "example-endpoint"
  service     = google_service_directory_service.example_X.id

  address = "1.2.3.4"
  port    = 5353
} 
```

Update the config and remove service_X and try to apply again but using service_Y in the endpoint. And at this point this errors.

```
resource "google_service_directory_namespace" "example" {
  provider     = google-beta
  namespace_id = "example-namespace"
  location     = "us-central1"
}

resource "google_service_directory_service" "example_Y" {
  provider   = google-beta
  service_id = "example-service-y"
  namespace  = google_service_directory_namespace.example.id
}

resource "google_service_directory_endpoint" "example" {
  provider    = google-beta
  endpoint_id = "example-endpoint"
  service     = google_service_directory_service.example_Y.id

  address = "1.2.3.4"
  port    = 5353
} 
```

The problem seems to be specifically when the endpoint tried to be updated. It's fine if it's recreated completely, but on update it fails.

Unfortunately I don't have access to the debug logs at this point in time.
