### ISSUE TITLE
Failing test(s): TestAccNotebooksInstance unable to extract CPU cores from machine type

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10208]
Failure rate: 100% since Sept. 14

Impacted tests:
- TestAccNotebooksInstance_notebookInstanceBasicContainerExample
- TestAccNotebooksInstance_notebookInstanceBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/208057?buildTab=tests&expandedTest=7820053237238386387

Message:

```
Error: Error creating Instance: googleapi: Error 400: unable to extract CPU cores from machine type
on terraform_plugin_test.tf line 2, in resource "google_notebooks_instance" "instance":
2: resource "google_notebooks_instance" "instance" {
```

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/10161
