### ISSUE TITLE
gcloud_compute_routers BgpPeer new options

### ISSUE THREAD

**Issue by marktru** [hashicorp/terraform-provider-google#10206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://docs.google.com/document/d/1D-IMrmGeQQkSHoqb_XrNoCbqPnaOjdNHXsi335Y6fWU/preview?resourcekey=0-hehZXmny85NTnWJQ2MLlFA

### New or Affected Resource(s)

* gcloud_compute_routers BgpPeer

### References

b/129429513

**Comment by drebes** [comment]
This has been fixed by GoogleCloudPlatform/magic-modules#3258
