### ISSUE TITLE
Failing test(s): TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10219]
Failure rate: 100% since added

Impacted tests:
- TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/208265?buildTab=tests&pager.currentPage=1&status=failed&expandedTest=-2298775931028285021

Message:

```
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
Failed to instantiate provider "registry.terraform.io/hashicorp/google" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/google"
```

Notes:
- Not using the correct plugin
- Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/5183 as part of a new c.g.c example

**Comment by megan07** [comment]
This appears to be fixed with the change here https://github.com/GoogleCloudPlatform/magic-modules/pull/5405
