### ISSUE TITLE
Add support for customer-managed encryption keys (CMEK) for Cloud Run

### ISSUE THREAD

**Issue by framilocvt** [hashicorp/terraform-provider-google#10213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please add the recent CMEK feature onto Google Cloud Run Terraform. google_cloud_run_service

Currently the only way to implement this feature is via the GCP portal, which is a problem if you have this type of resource already deployed via IaC.

One of the greatest products that GCP provides to it's customers, and another reason to keep using Terraform for multi-cloud encivironment, make it even more the standard tool for Infrastructure IaC.

### New or Affected Resource(s)
GCP Cloud Run

* google_cloud_run_service  CMEK  container images protection

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/run/docs/securing/using-cmek

**Comment by upodroid** [comment]
@rileykarson We can close this.

CMEKs can be set by adding an annotation which is already supported

https://cloud.google.com/run/docs/securing/using-cmek#enabling_cmek_for_a_service
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-sql

**Comment by megan07** [comment]
Closing given the comment above, this can be set in the `annotations` block.
