### ISSUE TITLE
Failing test(s): TestAccMonitoringMonitoredProject_BasicMonitoredProject

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10218]
Failure rate: 100% since day after adding

Impacted tests:
- TestAccMonitoringMonitoredProject_BasicMonitoredProject (beta)

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/208265?buildTab=tests&pager.currentPage=1&status=failed&expandedTest=-5478096038333557051

Message:

```
------- Stdout: -------
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
Failed to instantiate provider "registry.terraform.io/hashicorp/google" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/google"
```

Notes:

Using the incorrect provider. Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/5235

**Comment by rileykarson** [comment]
Fixed by @trodge w/ https://github.com/GoogleCloudPlatform/magic-modules/pull/5265
