### ISSUE TITLE
Failing test(s): TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10221]
Failure rate: 100% since Sept. 3 2021

Impacted tests:
- TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/208265?buildTab=tests&pager.currentPage=1&status=failed&expandedTest=-1276239178058950263

Message:

```
=== RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample
=== PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample
=== CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample
provider_test.go:278: Step 2/2 error running import: exit status 1
Error: Error when reading or editing BigqueryConnectionConnection "projects/projects/locations/<project-id omitted>/connections/locations": googleapi: Error 403: Permission denied on resource project projects.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.Help",
"links": [
{
"description": "Google developer console API key",
"url": "https://console.developers.google.com/project/projects/apiui/credential
}
]
},
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"domain": "googleapis.com",
"metadata": {
"consumer": "projects/projects",
"service": "bigqueryconnection.googleapis.com"
},
"reason": "CONSUMER_INVALID"
}
]
--- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionBasicExample (714.99s)
```

Notes:
- Possibly related to https://github.com/hashicorp/terraform-provider-google/issues/10220

**Comment by edwardmedia** [comment]
The issue is `connection_id` is nil at https://github.com/hashicorp/terraform-provider-google-beta/blob/46757a596f1480e979a621e7b18da8d787498a53/google-beta/resource_bigquery_connection.go#L208. Need to move this [block](https://github.com/hashicorp/terraform-provider-google-beta/blob/46757a596f1480e979a621e7b18da8d787498a53/google-beta/resource_bigquery_connection.go#L214) to ahead of it
