### ISSUE TITLE
allow lookup of google managed service-accounts

### ISSUE THREAD

**Issue by tony-kerz** [hashicorp/terraform-provider-google#10268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

unable to lookup google managed service accounts.

sometimes gcp creates [service-accounts for internal use](https://cloud.google.com/iam/docs/service-accounts#google-managed), see [this example](https://cloud.google.com/composer/docs/composer-2/create-environments#grant-permissions)

currently when i attempt to lookup such a service-account (even with the `Service Account Admin` role), i see:

> `│ Error: Error when reading or editing Service Account "projects/-/serviceAccounts/service-{project-number}@cloudcomposer-accounts.iam.gserviceaccount.com": googleapi: Error 403: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccounts/service-{project-number}@cloudcomposer-accounts.iam.gserviceaccount.com., forbidden`

### New or Affected Resource(s)

[`google_service_account`](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/data-sources/service_account)

### Potential Terraform Configuration

```tf
data "google_project" "this" {}

// fail
//
data "google_service_account" "this" {
  provider   = google-beta
  account_id = "service-${data.google_project.this.number}@cloudcomposer-accounts.iam.gserviceaccount.com"
}

resource "google_project_iam_member" "composer2" {
  role   = "roles/composer.ServiceAgentV2Ext"
  member = "serviceAccount:${data.google_service_account.this.email}"
}

```

**Comment by ndmckinley** [comment]
Hi,

Thanks for your report.  I think the error message is most likely correct - I suspect that your Terraform user does not have permission to perform this operation.  I do not think there's anything that Terraform can do to ensure that your permissions are set correctly - this sort of access does appear to work and is used routinely in our integration tests, so I would ask you to double-check your permissions.  Please comment again if you are certain that your permissions are set correctly, and I'll reopen and investigate - ideally in that case you'd provide debug logs.

Best,
Nat
