### ISSUE TITLE
`google_client_openid_userinfo` fails when used with `billing_project`

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-google#10260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.81.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.4.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tfe v0.26.1
```

### Affected Resource(s)

* [`google_client_openid_userinfo`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_openid_userinfo)

### Terraform Configuration Files

```terraform

# Ensure `USER_PROJECT_OVERRIDE` and `GOOGLE_BILLING_PROJECT` is set to some project

data "google_client_openid_userinfo" "self" {}
```

### Debug Output

```
Error: error retrieving userinfo for your provider credentials. have you enabled the 'https://www.googleapis.com/auth/userinfo.email' scope? error: googleapi: Error 403: User must be authenticated when user project is provided Details: [ { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "domain": "googleapis.com", "metadata": { "consumer": "projects/<project-id-here>", "service": "openidconnect.googleapis.com" }, "reason": "USER_PROJECT_DENIED" } ]
with data.google_client_openid_userinfo.self
on google-folder-factory.tf line 1, in data "google_client_openid_userinfo" "self":
```

### Panic Output

N/A

### Expected Behavior

It should have retrieved the current service account's email address.

### Actual Behavior

It failed with the error noted in "Debug Output".

### Steps to Reproduce

1. `USER_PROJECT_OVERRIDE=true GOOGLE_BILLING_PROJECT=some-project-id terraform plan`

### Important Factoids

I believe this is due to a previous fix that I had requested which causes the HTTP client to always specify the billing project. Following the call stack, `google_client_openid_userinfo` calls:

https://github.com/hashicorp/terraform-provider-google/blob/release-3.81.0/google/data_source_google_client_openid_userinfo.go#L28

https://github.com/hashicorp/terraform-provider-google/blob/26ff814b39d07b56b657eeb92e0abf423077be58/google/utils.go#L498-L506

which calls:

https://github.com/hashicorp/terraform-provider-google/blob/26ff814b39d07b56b657eeb92e0abf423077be58/google/transport.go#L43-L45

which calls:

https://github.com/hashicorp/terraform-provider-google/blob/26ff814b39d07b56b657eeb92e0abf423077be58/google/transport.go#L47

which uses this client:

https://github.com/hashicorp/terraform-provider-google/blob/26ff814b39d07b56b657eeb92e0abf423077be58/google/transport.go#L83

which has the quota project header set:

https://github.com/hashicorp/terraform-provider-google/blob/26ff814b39d07b56b657eeb92e0abf423077be58/google/config.go#L396-L398

I have granted `roles/serviceusage.serviceUsageConsumer` to the service account on the project specified in the `GOOGLE_BILLING_PROJECT` environment variable.

I looked for `openidconnect.googleapis.com` in the APIs tab of the Cloud Console UI to see if it was an API I needed to enable, but I'm fairly certain this is an internal-only Google API.

I'm not sure if this is a bug with the Google API, but it's probably safe to have the provider not set the `X-Goog-User-Project` for this one particular request. Let me know if I should file a support case instead.

### References

None that I could find.

**Comment by ndmckinley** [comment]
Interesting - I also am having trouble finding documentation on enabling this API.  I will look more deeply next week.

**Comment by ndmckinley** [comment]
I have not been able to figure out how to enable this api, and I'm leaving the team, so, unassigning.  @melinath since you're the closest person on the bug I'm assigning to you.

**Comment by melinath** [comment]
unassigning to put it back into the work queue
