### ISSUE TITLE
Only github and trigger_template should be mutually exclusive with google_cloudbuild_trigger

### ISSUE THREAD

**Issue by brtkwr** [hashicorp/terraform-provider-google#10277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.0.8

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "portals-pubsub-test-1" {

  name = "portals-pubsub-test-1"
  description = "Deploy portals production image to test env"

  github {
    name = "demo-portals"
    owner = "demo"
    push {
      branch = "staging"
      invert_regex = false
    }
  }

  pubsub_config {
    topic = "projects/demo-api/topics/cloud-builds"
  }

  substitutions = {
    _ENVIRONMENT = "test"
  }

  filename = "cloudbuild-pubsub.yaml"
}
```

### Expected Behavior

SUCCESS

Based on the docs, only triggerTemplate and Github are mutually exclusive, others should be allows.

### Actual Behavior

```
"webhook_config": only one of `github,pubsub_config,trigger_template,webhook_config` can be specified, but `github,pubsub_config` were specified.
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform-provider-google/issues/9936
* b/270750855

**Comment by abhinavrau** [comment]
This has been fixed with PR GoogleCloudPlatform/magic-modules#5738. Take a look at the example [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#example-usage---cloudbuild-trigger-pubsub-config) on how to create a pub/sub build with git repo.

**Comment by rileykarson** [comment]
Closing based on https://github.com/GoogleCloudPlatform/magic-modules/pull/5738
