### ISSUE TITLE
Data Catalog Tagging: plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by sephethus** [hashicorp/terraform-provider-google#10288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Occurs on both 1.0.8 and 0.14.4

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files
```
resource "google_bigquery_table" "management_zone_views" {
  for_each = toset( [
    "mi_dhhs_outreach_wic_kayak",
    "md_dhs_snap_redet_outreach_view",
    "md_dhs_snap_redet_outreach_client_view"
  ])
  view {
    query = templatefile("${path.module}/sql_views/management_zone/${each.key}.sql", { project-id = var.project-id })
    use_legacy_sql = false
  }
  description = "Management zone view ${each.key}"
  dataset_id = google_bigquery_dataset.standard_datasets["management_zone"].dataset_id
  table_id = each.key
  labels = {
    env = terraform.workspace
  }
}

```
### Debug Output

https://gist.github.com/sephethus/2e2ff2fc23667937dff2c68d04ccf311

### Expected Behavior

It should have applied tags.

### Actual Behavior

Doesn't even plan. Constant repeated RPC errors

`plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Canceled desc = context canceled`

### Steps to Reproduce

Take any google_bigquery_table with a json schema, add a Data Catalog tag link from a taxonomy tag, and watch it fail.

1. `terraform plan` or `terraform apply`

### Important Factoids

We are trying to terraform data catalog tags into our bigquery schemas.

### References

* #0000

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer an issue
