### ISSUE TITLE
Terraform support for Regional External HTTP(S) Load Balancer

### ISSUE THREAD

**Issue by jlporter** [hashicorp/terraform-provider-google#10285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for the new Regional External HTTP(S) Load Balancer, now in public preview. See https://cloud.google.com/load-balancing/docs/https/setting-up-reg-ext-https-lb for more details.

### New or Affected Resource(s)

* google_compute_forwarding_rule: `purpose = "EXTERNAL_MANAGED"`
* google_compute_backend_service: `load_balancing_scheme = "EXTERNAL_MANAGED"`
* google_compute_subnetwork: `purpose = "REGIONAL_MANAGED_PROXY"`

### Potential Terraform Configuration

The setup should be very similar to the example on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#example-usage---internal-http-lb-with-mig-backend, except with an external IP address reserved, `purpose=REGIONAL_MANAGED_PROXY` for the Envoy subnet, and `EXTERNAL_MANAGED` for the backend service and forwarding rule.

### References

* https://cloud.google.com/load-balancing/docs/https/setting-up-reg-ext-https-lb

**Comment by bluemalkin** [comment]
Any timeline for this please ? I would be super-handy.

**Comment by jlporter** [comment]
I'm working on magic module PR to support this.

**Comment by jlporter** [comment]
@bluemalkin if you get a chance to try this out, let me know!

**Comment by murphye** [comment]
@jlporter This works for me. Here is a project that I created that uses it: 

- https://github.com/murphye/cheap-gke-cluster
- https://github.com/murphye/cheap-gke-cluster/blob/main/terraform/load-balancer.tf

I even implemented a retry_policy. Thanks for implementing this. Very timely for me.
