### ISSUE TITLE
Failing test(s): Folder not found issues

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10286]
Failure rate: ???

Impacted tests:
- TestAccLoggingFolderSink_described
- TestAccLoggingFolderSink_disabled
- TestAccLoggingFolderSink_update
- TestAccLoggingFolderSink_removeOptionals
- TestAccLoggingFolderSink_folderAcceptsFullFolderPath
- TestAccLoggingFolderSink_updateBigquerySink
- TestAccLoggingFolderSink_heredoc
- TestAccLoggingFolderSink_basic
- TestAccFolderOrganizationPolicy_list_update
- TestAccFolderOrganizationPolicy_list_allowSome
- TestAccFolderOrganizationPolicy_list_denySome
- TestAccFolderOrganizationPolicy_restore_defaultTrue
- TestAccFolderOrganizationPolicy_boolean
- TestAccFolderIamPolicy_auditConfigs
- TestAccFolderIamMember_basic
- TestAccFolderIamMember_multiple
- TestAccFolderIamMember_remove
- TestAccFolderIamBinding_basic
- TestAccFolderIamBinding_update
- TestAccFolderIamBinding_remove
- TestAccFolderIamBinding_multiple
- TestAccFolderIamBinding_multipleAtOnce
- TestAccFolder_rename
- TestAccFolder_moveParent
- TestAccComputeFirewallPolicy_update
- TestAccComputeFirewallPolicyRule_multipleRules
- TestAccFolderIamAuditConfig_basic
- TestAccFolderIamAuditConfig_updateNoExemptMembers
- TestAccFolderIamAuditConfig_remove
- TestAccFolderIamAuditConfig_addFirstExemptMember
- TestAccFolderIamAuditConfig_removeLastExemptMember
- TestAccFolderIamAuditConfig_update
- TestAccFolderIamAuditConfig_multiple
- TestAccFolderIamAuditConfig_multipleAtOnce
- TestAccDataSourceGoogleFolders_basic
- TestAccDataSourceGoogleFolder_lookupOrganization
- TestAccDataSourceGoogleActiveFolder_dash
- TestAccDataSourceGoogleActiveFolder_space
- TestAccDataSourceGoogleActiveFolder_default

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=6317277238467567837

PR builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr/209386?buildTab=tests&expandedTest=-7514914581837289937

Message:

```
Error: Error creating folder 'tf-test-folder-gkug6e9og8' in 'organizations/*******': Error waiting for creating folder: Error code 9, message: Folder reservation failed for parent [organizations/*******], folder [] due to constraint: The folder operation violates fanout constraints.
```

Fanout contraints are documented here: https://cloud.google.com/resource-manager/reference/rest/v3/folders/create

> The addition of the folder must not cause the total number of folders under its parent to exceed 300.

This probably means something is going wrong with sweeping test folders?

**Comment by ndmckinley** [comment]
Also
- TestAccLoggingFolderExclusion
- TestAccFolderOrganizationPolicy_*
- TestAccFolderIamAuditConfig_*


and a whole ton of others.  i'll just go delete em myself real quick.

**Comment by ndmckinley** [comment]
Hm, easier said than done.  I got a few dozen with

```
for fid in $(gcloud resource-manager folders list --organization $ORG_ID | grep "^tf-test-" | awk '{print $3}'); do gcloud resource-manager folders delete $fid; done; 
```

but that's not enough, I mostly got "folder not empty".  Which would explain why we're having sweeper problems!  That's where I'd look next.

**Comment by rileykarson** [comment]
Marking as large because we probably need a bigger solution than we've currently got (and a manual cleanup will probably fix it for a while, but the problem will recur)

**Comment by rileykarson** [comment]
Note: fanout constraints are resolved, but we're seeing issues finding folders in tests

**Comment by ScottSuarez** [comment]
There looks to be some sort of latency between a folder being created and a folder being searchable on the API.

I've created b/94275557

**Comment by melinath** [comment]
Looks like the recommendation is to use List to instead of Get for a strongly consistent view of folders: https://cloud.google.com/resource-manager/reference/rest/v3/folders/list That will not resolve this issue.

**Comment by melinath** [comment]
based on the response - It looks like getFolderIamPolicyByParentAndDisplayName uses Folders.Search, which is eventually consistent. Switching to [Folders.List](https://cloud.google.com/resource-manager/reference/rest/v3/folders/list) might work better since it's strongly consistent.
