### ISSUE TITLE
Failing test(s): TestAccContainerNodePool_ephemeralStorageConfig

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#10305]
Failure rate: Consistently since 10/8

Impacted tests:
- TestAccContainerNodePool_ephemeralStorageConfig

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/210229?buildTab=tests&expandedTest=-6735754406430096182

Message:

```
Error: googleapi: Error 400: No valid versions with the prefix "1.18" found., badRequest
```

Seems we need to update a version in the test.

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/5404
