### ISSUE TITLE
Failing test(s): TestAccGkeHubFeatureMembership_gkehubFeatureAcm

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#10304]
Failure rate: Consistently since 10/5

Impacted tests:
- TestAccGkeHubFeatureMembership_gkehubFeatureAcmAllFields
- TestAccGkeHubFeatureMembership_gkehubFeatureAcmUpdate

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/210229?buildTab=tests&expandedTest=838033674041769552

Message:

```
Error: Error creating FeatureMembership: googleapi: Error 400: InvalidValueError for field version: unsupported version 1.6.2 for Membership tf-test10t0nt9v7av
on terraform_plugin_test.tf line 124, in resource "google_gke_hub_feature_membership" "feature_member_1":
124: resource "google_gke_hub_feature_membership" "feature_member_1" {
```

Looks like we just need to update a version in the test.

**Comment by shuyama1** [comment]
@rileykarson Sorry, I accidentally picked up this issue and did not see you were assigned to this.

**Comment by rileykarson** [comment]
Oh, you're all good! Seeing as how you've sent a fix, reassigning
