### ISSUE TITLE
Serverless Network Endpoint Group

### ISSUE THREAD

**Issue by s-dschro** [hashicorp/terraform-provider-google#10314]
Hey guys,

I checked the docs how to create a serverless network endpoint group on terraform:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group

And I saw that apigateway is currently not supported. Do you plan to add this feature even that it is a preview product?
https://cloud.google.com/api-gateway/docs/gateway-serverless-neg

Would be really helpful. Otherwise I would have to go for an internet network endpoint group.

Thx in advance.

**Comment by rileykarson** [comment]
Hey! Can you file a new issue w/ the template? Thanks!
