### ISSUE TITLE
Error creating AlertPolicy: googleapi: Error 404: The metric referenced by the provided filter is unknown. Check the metric name and labels.

### ISSUE THREAD

**Issue by casperakos** [hashicorp/terraform-provider-google#10325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v3.88.0
+ provider registry.terraform.io/hashicorp/google-beta v3.88.0

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_logging_metric" "cloudtask_last_attempt_failed" {
  for_each = local.all_project_ids

  project = local.all_project_ids[each.key]

  name = join("/", compact([
    deducted,
    deducted,
    "deducted-${each.key}",
  ]))

  filter = <<EOT
    resource.type=cloud_tasks_queue AND
    logName=projects/${local.all_project_ids[each.key]}/logs/cloudtasks.googleapis.com%2Ftask_operations_log AND
    jsonPayload.attemptResponseLog.status!=ok AND
    NOT jsonPayload.attemptResponseLog.retryTime:*
  EOT

  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    labels {
      key         = "task_name"
      description = "Task name is a unique task identifier formatted as xxx"
    }
  }

  label_extractors = {
    "task_name" = "EXTRACT(jsonPayload.task)"
  }
}

resource "google_monitoring_alert_policy" "cloudtask_last_attempt_failed" {
  for_each = local.all_project_ids

  project = var.env.deducted
  display_name = join("/", compact([
    deducted,
    deducted,
    "deducted-${each.key}",
  ]))

  notification_channels = [
    var.env.deducted,
  ]

  combiner = "OR"

  conditions {
    display_name = join("/", compact([
      xxx,
      xxx,
      "xxx-${each.key}",
    ]))

    condition_threshold {
      comparison      = "COMPARISON_GT"
      duration        = "0s"
      threshold_value = "0"
      filter = join(" ", [
        "metric.type=\"logging.googleapis.com/user/${deducted}/${deducted}/deducted-${each.key}\"",
        "resource.type=\"cloud_tasks_queue\"",
      ])
    }
  }

  documentation {
    mime_type = "text/markdown"
    content   = "Last attempt of a cloud task failed. This cloud task failed and will not be retried anymore."
  }
}
```

### Expected Behavior

Alert policy should be created

### Actual Behavior

Error: Error creating AlertPolicy: googleapi: Error 404: The metric referenced by the provided filter is unknown. Check the metric name and labels.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This was working until now, seems that after upgrading to v3.88.0 we are facing this issue. The metric is successfully created but the alerting policy fails because is not recognise the metric.

Also using gcloud I can see the metric with the exact same value as the one alert policy resource is using in terraform apply.
### References

* #0000

**Comment by eliastsironis** [comment]
> Using `join` here seems to be fine. 
> 
> @eliastsironis I am not super clear about the `filter`. How did you come up with your combination of `metric.type` and `resource.type`? Any links? 

Thanks @edwardmedia , the issue is solved as I had to include the project that has the metric to the project that has the alert. I did this manually and it failed for some reason but it succeeded in the second try and now everything works as expected.
