### ISSUE TITLE
google_container_cluster - panic: interface conversion: interface {} is []interface {}, not []string

### ISSUE THREAD

**Issue by bobleujr** [hashicorp/terraform-provider-google#10336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.88.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.0
### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name                = "${var.project_id}-${var.env}-gke"
  project             = "${var.project_id}" 
  location            = "${var.region}"
  monitoring_service  = "monitoring.googleapis.com/kubernetes"
  
  remove_default_node_pool = true
  initial_node_count       = 1

  node_locations  = var.node_locations

  network    = google_compute_network.vpc.name
  subnetwork = google_compute_subnetwork.subnet.name

  addons_config {
    horizontal_pod_autoscaling {
      disabled = "false"
    }

    http_load_balancing {
      disabled = "false"
    }

    network_policy_config {
      disabled = "true"
    }
  }

  cluster_autoscaling {
    enabled = "false"
  }

  database_encryption {
    state = "DECRYPTED"
  }

  default_max_pods_per_node   = "110"
  enable_binary_authorization = "false"
  enable_intranode_visibility = "false"
  enable_kubernetes_alpha     = "false"
  enable_legacy_abac          = "false"
  enable_shielded_nodes       = "false"
  enable_tpu                  = "false"

  ip_allocation_policy {
    cluster_ipv4_cidr_block  = "${var.cluster_ipv4_cidr_block}"
    services_ipv4_cidr_block = "${var.services_ipv4_cidr_block}"
  }

  logging_config {
    enable_components = ["SYSTEM_COMPONENTS", "WORKLOADS"]
  }

  logging_service = "logging.googleapis.com/kubernetes"

  master_auth {
    client_certificate_config {
      issue_client_certificate = "false"
    }
  }

  monitoring_config {
    enable_components = ["SYSTEM_COMPONENTS"]
  }

  network_policy {
    enabled = "false"
  }

  networking_mode = "VPC_NATIVE"

  release_channel {
    channel = "STABLE"
  }

  maintenance_policy {
    daily_maintenance_window {
        start_time  = "03:00"
    }
  }
}
```

Vars example
```tfvars
project_id = "projectid"
region     = "us-central1"
env        = "dev"
state_bucket = "mybucketname" 
service_account_id = "account-id"
node_locations = ["us-central1-b", "us-central1-c", "us-central1-f"]
#cluster_ipv4_cidr = "10.40.0.0/14"
cluster_ipv4_cidr_block = "10.40.0.0/14"
services_ipv4_cidr_block = "10.0.32.0/20"
ip_cidr_range = "10.128.0.0/20"
helm_account_name = "defaultacc"
```

### Debug Output

> google_compute_network.vpc: Creating...
> google_compute_network.vpc: Still creating... [10s elapsed]
> google_compute_network.vpc: Creation complete after 12s [id=projects/swiftera-sandbox/global/networks/swiftera-sandbox-dev-vpc]
> google_compute_subnetwork.subnet: Creating...
> google_compute_subnetwork.subnet: Still creating... [10s elapsed]
> google_compute_subnetwork.subnet: Still creating... [20s elapsed]
> google_compute_subnetwork.subnet: Creation complete after 21s [id=projects/swiftera-sandbox/regions/us-central1/subnetworks/swiftera-sandbox-dev-subnet]
> google_container_cluster.primary: Creating...
> ╷
> │ Error: Plugin did not respond
> │ 
> │   with google_container_cluster.primary,
> │   on gke.tf line 2, in resource "google_container_cluster" "primary":
> │    2: resource "google_container_cluster" "primary" {
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
> │ details.

### Panic Output

> Stack trace from the terraform-provider-google_v3.88.0_x5 plugin:
> 
> panic: interface conversion: interface {} is []interface {}, not []string
> 
> goroutine 162 [running]:
> github.com/hashicorp/terraform-provider-google/google.expandMonitoringConfig(...)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_container_cluster.go:3050
> github.com/hashicorp/terraform-provider-google/google.resourceContainerClusterCreate(0xc000ca0480, 0x3c4eb80, 0xc0005dee00, 0x0, 0x0)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_container_cluster.go:1313 +0x44b3
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008a4c40, 0x41a9540, 0xc000d84c80, 0xc000ca0480, 0x3c4eb80, 0xc0005dee00, 0x0, 0x0, 0x0)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:318 +0x1ee
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008a4c40, 0x41a9540, 0xc000d84c80, 0xc0009fd340, 0xc000f6dbe0, 0x3c4eb80, 0xc0005dee00, 0x0, 0x0, 0x0, ...)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:456 +0x67b
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d590, 0x41a9540, 0xc000d84c80, 0xc0015ae820, 0xc000d84c80, 0x3b94e80, 0xc000f49300)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:955 +0x8ef
> github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000ac9d80, 0x41a95e8, 0xc000d84c80, 0xc0009fd1f0, 0xc000ac9d80, 0xc000f49380, 0xc000b8cba0)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
> github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x3b94e80, 0xc000ac9d80, 0x41a95e8, 0xc000f49380, 0xc000a9faa0, 0x0, 0x41a95e8, 0xc000f49380, 0xc00098ac00, 0x1052)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a1340, 0x41e7b58, 0xc000001800, 0xc000a57c20, 0xc000438930, 0x50b7b40, 0x0, 0x0, 0x0)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
> google.golang.org/grpc.(*Server).handleStream(0xc0004a1340, 0x41e7b58, 0xc000001800, 0xc000a57c20, 0x0)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
> google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a07c0, 0xc0004a1340, 0x41e7b58, 0xc000001800, 0xc000a57c20)
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0xab
> created by google.golang.org/grpc.(*Server).serveStreams.func1
>         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd
> 
> Error: The terraform-provider-google_v3.88.0_x5 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

### Expected Behavior

It should've created the cluster ?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@bobleujr is this still reproducible? Is still an issue?

**Comment by bobleujr** [comment]
@edwardmedia as I mentioned, it won't work with the options (monitoring_config and logging_config) enabled, it will give this error. I don't have the debug log near but the reproduction steps seem very much described in the issue. It's up to you to close it or not this issue. I just commented the two lines for now (which is not a proper solution to the error but it lets my pipelines finish)

**Comment by edwardmedia** [comment]
@bobleujr I can't repro the issue. Per your suggestion, let's close this issue now. Please reopen once you experience the issue again with the repro steps & debug log. Thanks
