### ISSUE TITLE
google_cloud_run_service is missing "tag" in traffic block

### ISSUE THREAD

**Issue by mbleigh** [hashicorp/terraform-provider-google#10341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Cloud Run service Terraform resource appears to be missing the `tag` and output-only `url` fields from the [TrafficTarget](https://cloud.google.com/run/docs/reference/rest/v1/TrafficTarget) resource. This means that it is currently not possible to use Terraform to manage tagged revisions of a Cloud Run service.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_cloud_run_service" "default" {
  traffic {
    percent       = 25
    revision_name = "cloudrun-srv-green"
  }

  traffic {
    percent       = 75
    # This revision needs to already exist
    revision_name = "cloudrun-srv-blue"
  }

  traffic {
    percent       = 0
    revision_name = "cloudrun-srv-staging"
    tag = "staging"
  }
}
```

/cc @steren

**Comment by a-zen** [comment]
@mbleigh thx for raising this. Tried to migrate gcloud run deploy commands to terraform and hit this issue.

**Comment by tblakers** [comment]
Highly related: https://github.com/hashicorp/terraform-provider-google/issues/8654

**Comment by hsblhsn** [comment]
Hi, is there any update on it?

**Comment by c2thorn** [comment]
looks like this was closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/5772
