### ISSUE TITLE
An argument named "scheduler_count" is not expected here

### ISSUE THREAD

**Issue by arpitran** [hashicorp/terraform-provider-google#10348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.5.0

### Affected Resource(s)

* google_XXXXX

google_composer_environment

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_composer_environment" "example" {
  name   = "gcp-project"
  region = "us-central1"

  config {
    node_count = 4

    node_config {
        zone = "us-central1-a"
        network = google_compute_network.test.id
        subnetwork = google_compute_subnetwork.test.id
    }
    software_config {
        image_version = "composer-1.17.2-airflow-2.1.2"
        airflow_config_overrides = {
          core-load_examples = "True"
        }          
        env_variables = {
            DEPLOYMENT = var.DEPLOYMENT
            DEPLOYMENT2 = var.DEPLOYMENT2
        }
        scheduler_count = 1
    }
  }
}

```

### Debug Output

│ Error: Unsupported argument
│ 
│   on main.tf line 61, in resource "google_composer_environment" "example":
│   61:         scheduler_count = 1
│ 
│ An argument named "scheduler_count" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Gercho4** [comment]
I had the same issue and tried with the latest provider 4.6.0 and it works.

**Comment by megan07** [comment]
Closing as I see `scheduler_count` was added to the google provider in version [`3.87.0`](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.87.0).
