### ISSUE TITLE
Bug in Markdown documentation generator

### ISSUE THREAD

**Issue by remko** [hashicorp/terraform-provider-google#10347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Description

(Sorry for skipping all the fields, but since this is a documentation bug, probably in a script not in Terraform, I didn't include this info).

I'm guessing the markdown docs are generated, and there seems to be a bug in the generator. [The `url_mask` section of `compute_region_network_endpoint_group`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#url_mask) says:

> For example, request URLs "foo1.domain.com/bar1" and "foo1.domain.com/bar2" an be backed by the same Serverless Network Endpoint Group (NEG) with URL mask ".domain.com/".

I assume the < and > got interpreted as HTML and stripped, and this should have been:

> For example, request URLs "foo1.domain.com/bar1" and "foo1.domain.com/bar2" an be backed by the same Serverless Network Endpoint Group (NEG) with URL mask "`<tag>.domain.com/<service>`".

**Comment by edwardmedia** [comment]
@remko the descriptions of `url_mask` appears to match the ones of their APIs (below). From their doc, I don't see `<tag>` and `<service>`. Do I miss your point?

https://cloud.google.com/compute/docs/reference/rest/beta/regionNetworkEndpointGroups

**Comment by remko** [comment]
@edwardmedia The URL mask in those docs is wrong as well. You can tell if you inspect the HTML of that page:

        can be backed by the same Serverless NEG with URL mask 
        "<code translate="no" dir="ltr"><service>-dot-appname.appspot.com/<version></code>".

The `<service>` and `<version>` are not properly HTML encoded. 

It's not clear to me whether the terraform docs have the same bug as the API docs, or whether the bug is higher up in the chain (in the source of the documentation). From your question, I am guessing the latter?

**Comment by edwardmedia** [comment]
@remko generally the provider follows what API defines.  For the doc of this particular resource, here is the source code. Do you see `<service>` somewhere?

https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/compute_region_network_endpoint_group.html.markdown
