### ISSUE TITLE
Failing test(s): TestAccSqlUser_postgresIAM

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#10355]
Failure rate: 100% since 10/18

Impacted tests:
- TestAccSqlUser_postgresIAM

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/211570?buildTab=tests&status=failed&expandedTest=-8931663425942659432
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/220058?buildTab=tests&expandedTest=-8931663425942659432

Message:

```
------- Stdout: -------
=== RUN   TestAccSqlUser_postgresIAM
=== PAUSE TestAccSqlUser_postgresIAM
=== CONT  TestAccSqlUser_postgresIAM
provider_test.go:270: Step 2/2 error running import: exit status 1
Error: Cannot import non-existent remote object
While attempting to import an existing object to google_sql_user.user, the
provider detected that no object exists with the given id. Only pre-existing
objects can be imported; check that the id is correct and that it is
associated with the provider's configured region or endpoint, or use
"terraform apply" to create a new remote object for this resource.
--- FAIL: TestAccSqlUser_postgresIAM (746.12s)
FAIL
```

Seems to be test-only, from https://github.com/hashicorp/terraform-provider-google/pull/10322/files

**Comment by melinath** [comment]
This issue no longer seems to happen
