### ISSUE TITLE
Cannot edit a network_endpoint_group resource if used by a load balancer backend service

### ISSUE THREAD

**Issue by kkr16** [hashicorp/terraform-provider-google#10359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.54.0
```

### Affected Resource(s)

* google_compute_region_network_endpoint_group
* google_compute_backend_service

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.54.0"
    }

    google-beta = {
      source  = "hashicorp/google-beta"
      version = "3.54.0"
    }
  }
}

provider "google" {
  project = var.project
}

provider "google-beta" {
  project = var.project
}

variable "project" {
  type    = string
  default = "test-project-1234"
}

variable "domain" {
  type    = string
  default = "test.example123.com"
}

variable "region" {
  type    = string
  default = "us-east1"
}

resource "google_service_account" "minimal" {
  account_id = "minimal-service-account"
  display_name = "Minimal Service Account"
}

resource "google_project_service" "run" {
  service = "run.googleapis.com"
}

resource "google_project_service" "compute" {
  service = "compute.googleapis.com"
}

resource "google_cloud_run_service" "regions" {
  name     = var.region
  location = var.region
  
  template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale" = "3" // Control costs.
        "run.googleapis.com/launch-stage"  = "BETA"
      }
    }
    spec {
      service_account_name = google_service_account.minimal.email
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
        env {
          name  = "REGION"
          value = var.region
        }
      }
    }
  }
  lifecycle {
    ignore_changes = [
      // This gets added by the Cloud Run API post deploy and causes diffs, can be ignored...
      template[0].metadata[0].annotations["run.googleapis.com/sandbox"],
    ]
  }
  traffic {
    percent         = 100
    latest_revision = true
  }

  depends_on = [google_project_service.run]
}

resource "google_cloud_run_service_iam_member" "allUsers" {
  service  = google_cloud_run_service.regions.name
  location = google_cloud_run_service.regions.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}

resource "google_compute_region_network_endpoint_group" "regions" {
  name                  = google_cloud_run_service.regions.name
  network_endpoint_type = "SERVERLESS"
  region                = google_cloud_run_service.regions.location

  cloud_run {
    service = google_cloud_run_service.regions.name
  }
  depends_on = [google_project_service.compute]
}


resource "google_compute_global_address" "global" {
  name = "address"
}

resource "google_compute_global_forwarding_rule" "global" {
  name       = "global"
  target     = google_compute_target_https_proxy.global.id
  port_range = "443"
  ip_address = google_compute_global_address.global.address
}

output "global" {
  value = google_compute_global_address.global.address
}

resource "random_id" "certificate" {
  byte_length = 2
  prefix      = "global-"
}

resource "google_compute_managed_ssl_certificate" "global" {
  provider = google-beta

  name = random_id.certificate.hex
  managed {
    domains = [var.domain]
  }
  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_target_https_proxy" "global" {
  provider = google-beta

  name             = "global"
  url_map          = google_compute_url_map.global.id
  ssl_certificates = [google_compute_managed_ssl_certificate.global.id]
}

resource "google_compute_url_map" "global" {
  provider = google-beta

  name            = "global"
  description     = "a description"
  default_service = google_compute_backend_service.global.id
}

// Create a global backend service with a backend for each regional NEG.
resource "google_compute_backend_service" "global" {
  name       = "global"
  enable_cdn = true

  // Add a backend for each regional NEG.
  backend {
      group = google_compute_region_network_endpoint_group.regions.id
    }
  }
```

### Debug Output

https://gist.github.com/kkr16/11c6cd9ca3496849ea0e3a9b8d51c402

### Panic Output

n/a

### Expected Behavior

A new Cloud Run service is created in us-east4.
A new Serverless NEG `us-east4` is created, using the Cloud Run service in us-east4
The Load Balancer backend service is updated to add the new us-east4 NEG as a backend
The NEG for the us-east1 Cloud Run service is destoyed
The Cloud Run service for us-east1 is destroyed

### Actual Behavior

The NEG for the us-east1 Cloud Run service destruction is attempted, and fails as it's still in use by the Load Balancer back end.
Execution fails.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply --var="region=us-east4"`

### References

* #7311

**Comment by edwardmedia** [comment]
@kkr16 it seems you mix use of `regional` and `global` resources. Is this intentional? Can you try `google_compute_region_backend_service` instead?

**Comment by edwardmedia** [comment]
@kkr16 does `lifecycle.create_before_destroy` help? Is this still an issue?

**Comment by kkr16** [comment]
@edwardmedia - thank you for your patience. As far as I remember, lifecycle.create_before_destroy didn't help - I'll make time to test it again this weekend, and revert back.

**Comment by kkr16** [comment]
`lifecycle.create_before_destroy` did it. 
For some reason, I had to manually destroy my LB, then have TF recreate it - this allowed TF to then modify the Backends to point to the NEGs. I'll try to repro when I have time.
Closing this as my primary issue is resolved. Thanks!
