### ISSUE TITLE
Redis Update timeout too low

### ISSUE THREAD

**Issue by philipp-hb** [hashicorp/terraform-provider-google#10360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform v1.0.9
hashicorp/google v3.89.0...

### Affected Resource(s)

google_redis_instance

### Expected Behavior

When resizing a redis instance, terraform should wait until resize is complete

### Actual Behavior

Timeout after 20min

### Steps to Reproduce

Resize a Redis Standard instance (that has some load) from 30GB to 40GB
Result: Error waiting for Updating Instance: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 20m0s)
The instance is successfully resized, but the resize takes more than 20min

### Important Factoids

Followup of issue #10031. The operation leading to the timeout is different, but fix should be the same. According to the Google UI, upgrading can take up to 4h. For resizing, I didn't find a documentation that mentions duration

### References

* #10031 
* #10037

**Comment by edwardmedia** [comment]
@philipp-hb have you tried to provide the `timeout` by yourself? Is this still an issue?

**Comment by philipp-hb** [comment]
@edwardmedia sorry, I was unavailable in the meantime, so I also didn't try it.

Furthermore, I don't think overwriting it manually is a solution, since you never know beforehand, if the operation will take longer or not. I agree, that setting it to 4h for default sounds a bit ugly, but I don't know how we could determine beforehand how long the operation will take and which timeout is suitable

**Comment by edwardmedia** [comment]
@philipp-hb I get your point. But doesn't the size of data play a role? 4 hours is too long and 20 mins is too short. What is the number that is appropriate? Personally I prefer short as most users have not reported that is an issue, plus too long timeout could lead bad consequences. In your case, you can overwrite it as you know at least the size of data...

**Comment by philipp-hb** [comment]
I guess size and load are important factors on this.

Of course we can overwrite it, but I think the tf provider should be of universal use without the need to overwrite timeouts for normal routine operations.

I don't know how complicated it is: Since tf also knows the size, could it be an option to set the timeout in proportion to the size?
e.g. <10GB: 20 minutes, 10-20GB: 30 minutes, 20-30GB 40 minutes , ....

**Comment by edwardmedia** [comment]
@philipp-hb it would be nice to do it dynamically but unfortunately it is impossible to implement at the provider level. Closing the issue now. Feel free to reopen if you want to continue the conversation. Thank you
