### ISSUE TITLE
Bigquery: Alter Table using Terraform

### ISSUE THREAD

**Issue by mdideles** [hashicorp/terraform-provider-google#10362]
I am altering a bigquery table to rename a column name using the terraform.
Is there a way to prevent terraform from destroying the table when I am just renaming the column name?

**Comment by mdideles** [comment]
this looks like a bug to me.  I saw some bug report on this before but it is not clear to me what is the fix.

**Comment by edwardmedia** [comment]
@mdideles is this still an question?

**Comment by edwardmedia** [comment]
@mdideles closing assuming this is no longer a question

**Comment by mdideles** [comment]
Thanks.  This can be closed
