### ISSUE TITLE
wait_for_instances not working as expected

### ISSUE THREAD

**Issue by circa10a** [hashicorp/terraform-provider-google#10396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`0.14.11`

### Affected Resource(s)

* `google_compute_region_instance_group_manager`

### Terraform Configuration Files

```tf
resource "google_compute_region_instance_group_manager" "nat" {
  count                     = var.build_nats ? 1 : 0
  name                      = local.nat_mig_name
  base_instance_name        = "nat"
  distribution_policy_zones = local.zones
  region                    = var.region
  wait_for_instances        = true

  update_policy {
    type                         = "OPPORTUNISTIC"
    minimal_action               = "RESTART"
    instance_redistribution_type = "PROACTIVE"
    max_unavailable_fixed        = length(local.zones)
  }

  version {
    instance_template = google_compute_instance_template.nat[0].self_link
  }
}
```

### Expected Behavior

Terraform should not have exited successfully until instances were available

### Actual Behavior

Terraform exited immediately and did not wait until instances were available.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- provider version: `3.89.0`
- 

### References

* https://github.com/hashicorp/terraform-provider-google/issues/3378

**Comment by rileykarson** [comment]
Closing as stale- there's not enough information to infer why this happened, and there haven't been other similar bug reports.
