### ISSUE TITLE
gpu_partition_size is not treated as optional in v3.90.0

### ISSUE THREAD

**Issue by andy-caruso** [hashicorp/terraform-provider-google#10415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.11
google v3.90.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Supplied to google_container_node_pool as 

```tf
      guest_accelerator = []
```

### Debug Output

`terraform plan` fails with the following message

```
    | each.value.guest_accelerator is empty list of object

Inappropriate value for attribute "guest_accelerator": incorrect list element
type: attribute "gpu_partition_size" is required.
```

### Expected Behavior

gpu_partition_size as per the documentation should be optional

### Actual Behavior

Setting `guest_accelerator = []` fails with this error

### Steps to Reproduce

1. `terraform plan` using a resource that was created previously

**Comment by edwardmedia** [comment]
@andy-caruso does this make sense?

**Comment by andy-caruso** [comment]
I can't say that "An empty list requires optional values to be specified" makes sense. It's counterintuitive to the meaning of optional.

Did we resolve the issue? Yes, by supplying `gpu_partition_size = null` and merging that with the list. Although it's unclear what this means for an empty list.

```tf
    guest_accelerator = [
      for acc in each.value.guest_accelerator:
        merge({ gpu_partition_size = null }, acc)
    ]
```
