### ISSUE TITLE
google_sql_database_instance  - add option to select Allocated IP Range from Private Service Connection

### ISSUE THREAD

**Issue by tomekzielins** [hashicorp/terraform-provider-google#10417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add in google_sql_database_instance option to select manually "Allocated IP range" as its possible in GCP console. 

Currently terraform resource google_sql_database_instance chose automatically which range is used for SQL instances connection from IP ranges defined in Private Service Connection and there is no option to do it manually. However in scenarios when we have multiple allocated subnets and want to deploy couple of SQL instances in multiple regions I need to have possibility to chose exactly which IP range should be used in which region. This option is available in Console  as "Allocated IP range (optional)". 

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

resource "google_sql_database_instance"
    ...
    ip_configuration    = {
                        ipv4_enabled = XXX
                        private_network = "XXX"
                        require_ssl = XXX
                        **ip_range = "my-allocated-ip-range"**  // (optional) name of allocated ip range 
                        authorized_networks = [XXX]
                        }

**Comment by rileykarson** [comment]
Dupes https://github.com/hashicorp/terraform-provider-google/issues/9986, I believe
