### ISSUE TITLE
Cloud storage bucket retries slowing state refreshes

### ISSUE THREAD

**Issue by NicholasAzar** [hashicorp/terraform-provider-google#10423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v3.90.0_x5

### Affected Resource(s)

terraform-google-modules/cloud-storage/google//modules/simple_bucket

### Debug Output

https://gist.github.com/NicholasAzar/dbd961da7df00699a07f5a5f0517600a

### Expected Behavior

Bucket state retry shouldn't occur during state refresh

### Actual Behavior

Bucket retries, causing a much slower apply

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Only noticed this behaviour since yesterday.

**Comment by edwardmedia** [comment]
@NicholasAzar is this still an issue?

**Comment by edwardmedia** [comment]
@NicholasAzar closing this assuming it is no longer an issue

**Comment by NicholasAzar** [comment]
Just for an update on this, while I haven't yet been able to work on a standalone reproduction case, we've found that this is an issue introduced in 3.89.0 that's not reproducible in 3.88.0.

Vague steps are (in case they're helpful):
1. Create bucket with terraform tracked state
2. Manually delete bucket from gcp
3. Rerun apply/plan

Hopefully I'll be able to work on some better reproduction steps in the near future. For now we're just pinning on 3.88.0 to meet a deadline.

**Comment by NicholasAzar** [comment]
Yeah this is definitely reproducible with this standalone example:

Define main.tf similar to this with the values filled in:
```
terraform {
  required_version = ">=0.14"
  required_providers {
    google      = "= 3.89.0"
  }
  backend "gcs" {
    bucket = "{STATE BUCKET}"
  }
}

module "a_bucket" {
  source  = "terraform-google-modules/cloud-storage/google//modules/simple_bucket"
  version = "~> 1.4"
  name       = "{NEW BUCKET}"
  project_id = "{PROJECT ID}"
  location   = "us-central1"
}
```

Commands: 
1. terraform init
2. terraform plan -> See that it returns the plan immediately.
3. terraform apply
4. delete the bucket from gcp manually and wait for the delete to complete.
5. run terraform plan -> see that it takes 20 minutes.

**Comment by NicholasAzar** [comment]
@edwardmedia did you have a chance to take another look at this?

**Comment by turkenh** [comment]
Having this issue as well, tested both with `v4.0.0` and `v4.2.1`.

@edwardmedia could we reopen this?
