### ISSUE TITLE
Cannot specify `trigger_template` and `webhook_config` using `google_cloudbuild_trigger`

### ISSUE THREAD

**Issue by finlaye** [hashicorp/terraform-provider-google#10434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Currently when using the `google_cloudbuild_trigger` resource you can only specify one of `webhook_config` and `trigger_template`. This is not the same as in the console where you can select a source repo where you want to store your `cloudbuild.yaml` config AND you can configure a webhook. When attempting to specify both, this is the error shown

```bash
│ Error: ExactlyOne
│ 
│   with module.core_triggers.google_cloudbuild_trigger.example_trigger,
│   on triggers.tf line 6, in resource "google_cloudbuild_trigger" "example_trigger":
│    6: resource "google_cloudbuild_trigger" "example_trigger" {
│ 
│ "github": only one of
│ `github,pubsub_config,trigger_template,webhook_config` can be specified,
│ but `trigger_template,webhook_config` were specified.

```

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "filename-trigger" {
  trigger_template {
    branch_name = "master"
    repo_name   = "my-repo"
  }

  webhook_config {
    secret = "projects/123456789/secrets/example-secret/versions/1"
  }

  substitutions = {
    _FOO = "foo-bar"
    _BAZ = "qux"
  }

  filter = "_FOO.matches(\".*-bar\")"

  filename = "cloudbuild.yaml"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger

**Comment by jrmanes** [comment]
Hi there! @finlaye  @rileykarson 

I'm having the same issue, I cannot specify the repository when use a `pubsub_config` 
Did you find any workaround?

**Comment by finlaye** [comment]
> Hi there! @finlaye @rileykarson
> 
> I'm having the same issue, I cannot specify the repository when use a `pubsub_config` Did you find any workaround?

Nope, no work around unfortunately :(

**Comment by bbhoss** [comment]
Bummer. It seems like creating a scheduled cloud build job currently isn't possible with Terraform? :(

**Comment by jrmanes** [comment]
@bbhoss  nope... so far is not possible to do it :face_exhaling:

**Comment by ManuelLR** [comment]
Same error found using `github` + `webhook_config`

**Comment by dinagraves** [comment]
+1 same issue

**Comment by shirakiya** [comment]
I would like the google provider to be able to request the `sourceToBuild` parameter described in this GCP document.
https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger

**Comment by amacarrilla** [comment]
Same problem here!!
Another one looking forward this feature

Thanks in advance

**Comment by mikelvizz** [comment]
+1

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon
