### ISSUE TITLE
google_artifact_registry_repository location appears to be required

### ISSUE THREAD

**Issue by aaron-lane** [hashicorp/terraform-provider-google#10436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.89.0
+ provider registry.terraform.io/hashicorp/google-beta v3.89.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/vancluever/acme v2.6.0

### Affected Resource(s)

* google_artifact_registry_repository

### Terraform Configuration Files

```tf
resource "google_artifact_registry_repository" "main" {
  provider = google-beta

  format        = "DOCKER"
  repository_id = "main"

  description = "A repository of images."
  labels      = {
    env = "test"
  }
}

```

### Output

```
Error: Error creating Repository: googleapi: Error 400: Request contains an invalid argument.
with google_artifact_registry_repository.main
on artifact-registry.tf line 1, in resource "google_artifact_registry_repository" "main":
resource "google_artifact_registry_repository" "main" {
```

### Expected Behavior

The repository is created with the location inherited from the provider region, as the `location` argument is [documented](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository#location) as optional.

### Actual Behavior

The repository is not created because GCP rejects the request due to an invalid argument, as the location argument is required and not necessarily equivalent to any region.

### Steps to Reproduce

This issue was reported in https://github.com/hashicorp/terraform-provider-google/issues/10184. I confirmed that the [workaround](https://github.com/hashicorp/terraform-provider-google/issues/10184#issuecomment-938481699) of adding the `location` argument solved the problem.

### References

b/272798286

**Comment by henkka** [comment]
This seems to be bug caused from https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_artifact_registry_repository.go#L186 as there's no functionality that defaults the `location` to provider region when `location` is not passed, and thus, the location ends up being empty string.

In such case the path used for the API call is
```
/v1/projects/project-name/locations//repositories?repository_id=repo-name
```

(notice `//`)

I'll see whether I manage to fix it and create pull request for it

**Comment by Carlos4ndresh** [comment]
Encountered the Same behaviour, adding the `location` did the trick
