### ISSUE TITLE
master_global_access_config does not apply on existing private cluster

### ISSUE THREAD

**Issue by dansiviter** [hashicorp/terraform-provider-google#10444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.90.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* `google_container_cluster`

### Terraform Configuration Files

```tf
resource "google_container_cluster" "foo" {
  ...
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_ipv4_cidr_block  = "something/28"

    master_global_access_config {  # first create without this block, then add
      enabled = true
    }
    ...
}
```

### Debug Output
N/A

### Panic Output

N/A

### Expected Behaviour

When adding the `master_global_access_config` to the cluster is should update and enable it. 

### Actual Behaviour

In Plan, TF does know that it needs to update it. However, on apply it doesn't seem to do anything. Subsequent plans continue to identify that this needs needs updating but it never happens. It's confirmed by the Console and gCloud that the flag has not taken effect. On the same cluster I then ran `gcloud containers update <name> --enable-master-global-access` which successfully applied the flag and this no longer showed up in the terraform plan.

### Steps to Reproduce

1. Create a private cluster without `master_global_access_config`,
2. Modify the cluster by adding `master_global_access_config.enabled=true`

### Important Factoids

This flag does work if building the cluster from scratch. It's only the update that appears to be a problem.

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_global_access_config
* b/298513478

**Comment by ScottSuarez** [comment]
could you provide the debug logs for this request? potentially scrubbed of any PII

You can do so by enabling TF_LOG=DEBUG and TF_LOG_PATH=`path-to-file`

**Comment by yiyinglovecoding** [comment]
This should already be fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/6932 and https://github.com/GoogleCloudPlatform/magic-modules/pull/8314
