### ISSUE TITLE
Add support for Google Container Filesystem (GCFS)

### ISSUE THREAD

**Issue by paulbsch** [hashicorp/terraform-provider-google#10451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Container Filesysem (GCFS) recently went GA and GcfsConfig is now available with the release of google-api-go-client v0.60.0:
https://github.com/googleapis/google-api-go-client/releases/tag/v0.60.0

This feature allows fast image pulling. With a shorter image pulling time, you'll get the benefit of faster auto-scaling, less latency of pulling large images, and a quicker pod startup on the general use.

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_container_node_pool" "np" {
  name               = "terraform-gcfs"
  location           = "us-central1-a"
  cluster            = google_container_cluster.cluster.name
  initial_node_count = 1

  node_config {
    machine_type = "n1-standard-8"
    image_type = "COS_CONTAINERD"
    gcfs_config {
      enabled = true
    }
  }
}

```

### References

* #0000

**Comment by paulbsch** [comment]
Here is a pull request that implements `gcfs_config`:
https://github.com/GoogleCloudPlatform/magic-modules/pull/5398

**Comment by paulbsch** [comment]
With the pull request having been merged, it would seem that this is complete @rileykarson.  Just let me know if there's anything else that needs to be done to get it into the next release.  Thanks!

**Comment by rileykarson** [comment]
Nope, nothing else needed. This should go out in `4.1.0` next ~Monday, provided nothing comes up! Closed w/ https://github.com/GoogleCloudPlatform/magic-modules/pull/5398
