### ISSUE TITLE
Documentation indicates `provider` of `network_policy` is optional

### ISSUE THREAD

**Issue by socketbox** [hashicorp/terraform-provider-google#10461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.9                                                     
on linux_amd64                                                       
+ provider registry.terraform.io/hashicorp/google v3.79.0            
+ provider registry.terraform.io/hashicorp/google-beta v3.79.0       
+ provider registry.terraform.io/hashicorp/null v3.1.0               
+ provider registry.terraform.io/hashicorp/random v3.1.0             

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

 
```tf
resource "google_container_cluster" "cluster" {
  provider    = google-beta
  <snip>
  addons_config {
    network_policy_config {
      disabled = false
    }
  }

  network_policy {
    enabled   = true
  }
 <snip>
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The documentation should indicate that `provider` is required, and that its value should be that of `CALICO`.

### Actual Behavior

Provider docs indicate that a `provider` is optional, and that the default is `PROVIDER_UNSPECIFIED`. 

### Steps to Reproduce

1. Create a cluster without enabling network configuration.
2. Enable the `network_policy_config` with
```
addons_config {            
  network_policy_config {  
    disabled = false       
  }                        
}
```
3. On the existing cluster, attempt to enable network policy without specifying a provider, or specifying a provider of `PROVIDER_UNSPECIFIED`.

### Important Factoids

The provider `CALICO` is referred to in at least two GitHub issues which contain manifest excerpts:
* https://github.com/hashicorp/terraform-provider-google/issues/3673#issuecomment-494486080
* https://github.com/hashicorp/terraform-provider-google/issues/860

### References
Doc in question: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_network_policy

**Comment by edwardmedia** [comment]
@socketbox where did you get your expected behavior. Can you provide a link? The following is a link to k8s which does not specify  `CALICO` should be chosen as the default. 

> The documentation should indicate that provider is required, and that its value should be that of CALICO.

https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-policies

**Comment by socketbox** [comment]
@edwardmedia I'm describing my experience with GKE, that's why I referred to the Google provider docs initially.

**Comment by edwardmedia** [comment]
@socketbox I am not sure if we should change the behavior.

**Comment by ScottSuarez** [comment]
changing this would be breaking change for users who have 

```hcl
  network_policy {
    enabled  = false
	provider = "PROVIDER_UNSPECIFIED"
  }
```

admittedly this would be a smaller edge case... what do you think @rileykarson

**Comment by rileykarson** [comment]
We should definitely not make a breaking change, which a move to required or a removal of the default would be. I think the config you've provided highlights a case where `PROVIDER_UNSPECIFIED` is appropriate. Additionally, users can specify the following, indicating that the field being optional seems correct.

```
network_policy {
  enabled  = false
}
```

**Comment by ScottSuarez** [comment]
closing this as we won't be changing the behavior
