### ISSUE TITLE
can not specify current project image for google_compute_image

### ISSUE THREAD

**Issue by jachenyp** [hashicorp/terraform-provider-google#10464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.0

### Affected Resource(s)

* google_compute_image

### Terraform Configuration Files

```tf

resource "google_compute_instance" "vm_instance" {
 
  boot_disk {
    initialize_params {
      image = var.image_project!= "" ? data.google_compute_image.other_project_image.self_link : var.image_name
      type = var.disk_type
      size = var.disk_size
    }
  }

}


data "google_compute_image" "other_project_image" {
  name  = var.image_name
  project = var.image_project!= "" ? var.image_project : var.image_name
}
```

### Debug Output

terraform plan  -out=terraform_plan.out
Acquiring state lock. This may take a few moments...
╷
│ Error: error retrieving image information: googleapi: Error 404: The resource 'projects/gcp-mmprd-nprd-80388/global/images/centos-7-v20200403' was not found, notFound
│
│   with module.instance.data.google_compute_image.other_project_image,
│   on modules/instance/main.tf line 52, in data "google_compute_image" "other_project_image":
│   52: data "google_compute_image" "other_project_image" {

### Expected Behavior

AS <a href="https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_image">documentation </a> said:
project - (Optional) The project in which the resource belongs. If it is not provided, the provider project is used. If you are using a public base image, be sure to specify the correct Image Project.

There is the image in the project gcp-mmprd-nprd-80388, and it should be found

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by ScottSuarez** [comment]
Does the SA provisioning the compute instance has access to this image?

This doesn't seem like an issue with terraform but an access/permission issue as the correct image url is being found and supplied to the compute api.

**Comment by ScottSuarez** [comment]
I would recommend trying to poll `projects/gcp-mmprd-nprd-80388/global/images/centos-7-v20200403` directly with gcloud commands. Make suer there is no reference issue here.

**Comment by edwardmedia** [comment]
No response. Closing assuming it is no longer an issue
