### ISSUE TITLE
Log Sink description Bug -- Terraform 0.14.11

### ISSUE THREAD

**Issue by deepak-pradeep-db** [hashicorp/terraform-provider-google#10473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.11

### Affected Resource(s)

*google_logging_folder_sink
google_logging_project_sink
google_logging_organization_sink

### Expected Behavior

I have created few project and Folder leve sinks.

Need to update the Log sinks description

### Actual Behavior

A few days later, I tried to update the log sink description but when I applied the changes, The description value became null (in both state file and GCP console). 

If I trigger terraform plan, it is gain showing the changes. I tried applying 10 times. still showing the same changes. but no error

Could you please check and let us know . How Can I get my descriptions back.

**Comment by edwardmedia** [comment]
@deepak-pradeep-db can you repro? If yes, please provide the configs and the steps.

**Comment by deepak-pradeep-db** [comment]
Let me tell. What I did step by step.

Step 1 : 

I created a sink you Terraform v0.14.11

`resource "google_logging_project_sink" "my-sink" {
  name                           = "sink-for-description-test"
  description                  = "Test Sink Description"
  destination                  = "pubsub.googleapis.com/projects/<MT DESTINATION>"
  filter                             = "resource.type = gce_instance"
  unique_writer_identity = true
}`


Step 2: I'm changing the Sink Description

`resource "google_logging_project_sink" "my-sink" {
  name                           = "sink-for-description-test"
  description                  = "Description Change "     ####I chaged my Description
  destination                  = "pubsub.googleapis.com/projects/<MT DESTINATION>"
  filter                             = "resource.type = gce_instance"
  unique_writer_identity = true
}`

Terraform plan showing the Changes and Terraform Apply successfull.

Now In GCP console. The description became empty and also in state file.

Now I'm triggering Terraform Plan with modifying the Terraform configuration file and Terraform plan again showing the same chanegs. Again Terraform apply successfull but sink description is still empty in both GCP console and state file.

I triggered the terraform apply for 10 time and applied 10 time successfully but still descriptions are empty. 

Note: I have even tried with latest Google provider version and terraform version. As well as I have tried in different accounts and CLIs.

Please let me know if you need more clarity.

**Comment by edwardmedia** [comment]
@deepak-pradeep-db I see where the problem is. I will open a PR for it

**Comment by deepak-pradeep** [comment]
@edwardmedia 

When I can see the changes or which version I have to use to see the changes.

Thanks in advance.
