### ISSUE TITLE
google_secret_manager_secret_version -> googleapi: Error 400: Field [payload] is required on empty secret_data field

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform-provider-google#10475]
**terraform version**
```terraform
terraform version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.86.0
+ provider registry.terraform.io/hashicorp/google-beta v3.86.0
```

**terraform configuration**
```terraform
resource "google_secret_manager_secret" "secret" {
  provider = google-beta

  secret_id = "secret"
  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "secret-version-data" {
  provider = google-beta

  secret      = google_secret_manager_secret.secret.name
  secret_data = "" //var.secret_data
}
```
**result**
```terraform
╷
│ Error: Error creating SecretVersion: googleapi: Error 400: Field [payload] is required.
│ 
│   with google_secret_manager_secret_version.secret-version-data,
│   on secret.tf line 12, in resource "google_secret_manager_secret_version" "secret-version-data":
│   12: resource "google_secret_manager_secret_version" "secret-version-data" {
│ 
╵
```
**question**
I do understand that `secret_data` field has to be set, otherwise the corresponding `payload` field will be absent, but what if I have to set and empty string `secret_data` in order to have an empty string `payload`? Is there any way to achieve this?

**refs**
- https://github.com/hashicorp/terraform-provider-google/issues/8766#
- https://cloud.google.com/secret-manager/docs/reference/rest/v1/SecretPayload

**Comment by edwardmedia** [comment]
@lwsanty the error is from API. I don't think any other client tools that can workaround it. Does this make sense? 

> googleapi: Error 400

**Comment by lwsanty** [comment]
@edwardmedia please correct me if I'm wrong, but I have a feeling that if tf variable `secret_data` is empty, then during composing a request to GCP API we do not set a `payload` field at all, and that causes a
 > googleapi: Error 400

so, I'm just wondering if we set a `payload` field in the request with an empty string instead of not setting it at all, that should  bypass the request validation on GCP API side

**Comment by lwsanty** [comment]
@edwardmedia yes, thanks for your help
