### ISSUE TITLE
How to create serverless neg for API-gateway

### ISSUE THREAD

**Issue by ricardolpd** [hashicorp/terraform-provider-google#10476]
I am trying to configure an load balancer for API-gateway 

The goal for us is to to aggregate over different url paths, different gateways, and for this I am trying to follow this [tutorial](https://cloud.google.com/api-gateway/docs/gateway-serverless-neg)

in which i have to create the equivalent serveless-neg of the following command, but i can't find an example for this in this page [compute_region_network_endpoint_group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group)

```
gcloud compute network-endpoint-groups create api-gateway-serverless-neg
   --region=us-central1 \
   --network-endpoint-type=serverless \
   --serverless-deployment-platform=apigateway.googleapis.com \
   --serverless-deployment-resource=my-gateway
```

Is the above not currently supported? If not when will it be added, is there another work around to use api-gateway with load balancer and terraform?

I would appreciate any help with this.

**Comment by beninada** [comment]
Seeing the same issue here too. Running the command via CLI returns:
```sh
ERROR: (gcloud.compute.network-endpoint-groups.create) unrecognized arguments:
  --serverless-deployment-platform=apigateway.googleapis.com
  --serverless-deployment-resource=...
```

**Comment by beninada** [comment]
Using `gcloud beta` resolved this for me.

**Comment by ricardolpd** [comment]
Sorry i was busy with other work, its good that you managed to get it working, but my question was more of how do I achieve the equivalent of the gcloud command with terraform. I can seem to find a serverless neg for the api-gateway within the terraform modules.

**Comment by ivoilic** [comment]
@ricardolpd as you may have guessed, this feature is not available yet. 
There have been multiple requests for this to be added: #10061 #9907
Hopefully one of these will be implemented soon.

**Comment by ivoilic** [comment]
@ricardolpd Since the PR for this is taking some time to get merged, one alternative is to use the [gcloud command within terraform ](https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest)directly.

**Comment by roaks3** [comment]
Per https://github.com/hashicorp/terraform-provider-google/issues/10729, this is now implemented in the beta provider.
