### ISSUE TITLE
google_container_cluster shared vpc network has a project ID mixup

### ISSUE THREAD

**Issue by jimsnab** [hashicorp/terraform-provider-google#10489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.10
on linux_amd64

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource google_container_cluster "my_cluster" {
  project = "my-service-project"
  network = "projects/my-shared-vpc-project/regions/us-central1/networks/my-vpc"
  subnetwork = "projects/my-shared-vpc-project/regions/us-central1/subnetworks/my-subnet"
  ...
```

or

```tf
resource google_container_cluster "my_cluster" {
  project = "my-service-project"
  network = "projects/my-shared-vpc-project/us-central1/networks/my-vpc"
  subnetwork = "projects/my-shared-vpc-project/us-central1/subnetworks/my-subnet"
  ...
```

### Expected Behavior

A correct error why the cluster can't be created.

### Actual Behavior

The project of the cluster (`my-service-project`) is incorrectly reported in the error message, instead of the project specified in the self link (`my-shared-vpc-project`). This incorrect context makes a small problem difficult to understand.

First example (network specified in a region, when it is actually global)

`Error: googleapi: Error 400: Project in network field "my-service-project" does not match project in subnetwork field "my-shared-vpc-project"., badRequest`

Second example (missing `region` in the path)

`Error: googleapi: Error 404: Not found: project "my-service-project" does not have a subnetwork named "my-subnet" in region "us-central1"., notFound`

### Steps to Reproduce

1. Create a host project and a service project.
2. Share a global VPC with region subnets in the host project to the service project.
3. Use the script fragment above and fill in the rest of the details according to your setup.

### Important Factoids

You should be able to reproduce this without going through the effort of setting up a shared VPC. If it is pointed at a non-existent shared vpc, it should error more correctly.

This is a correct, working tf script that matches the 'global' location for the network, and the regional subnetwork.

```tf
resource google_container_cluster "my_cluster" {
  project = "my-service-project"
  network = "projects/my-shared-vpc-project/global/networks/my-vpc"
  subnetwork = "projects/my-shared-vpc-project/regions/us-central1/subnetworks/my-subnet"
  ...
```

### References

* #7545

**Comment by edwardmedia** [comment]
@jimsnab I can repro the issue, but I am not sure if we should fix this (make error clearer) with the way how the provider currently is implemented. In general, there are numerous GCP resources that are on either `global` or `regional`. To them easier to be used and support validation, the [code](https://github.com/hashicorp/terraform-provider-google/blob/e4c9cdca4075d18b41c4a99b748e919312cd447d/google/field_helpers.go#L118) proactively looks for the keywords `global` and `regions`. If they are missing, the code assumes that is on purpose and thus adds the `global` and `regions` for you. In your both examples, both `network` and `subnetwork` are **reconstructed** with the `default` project_id. That is the logic for vast majority use cases.  I do not see there is a good way that can serve both cases nicely. Based on the evaluation, I would say no fix for this.  Does this make sense?

**Comment by jimsnab** [comment]
I understand. Is there an opportunity to soften the error text to provide a hint that the resource could be in another project?

```
Error: googleapi: Error 400: Projects do not match project in subnetwork field "my-shared-vpc-project"., badRequest
```

Less info is better than wrong info.

**Comment by jimsnab** [comment]
Another option is a TF_LOG WARN hint when global or region is missing and default is assumed. Is there such a message already?

**Comment by edwardmedia** [comment]
@jimsnab the message (`googleapi`) is from api, not generated inside the provider. It might not be a super good idea to modify the upstream error message. For TF_LOG, yes we can add more debug info. But in this case, everything seems to be legit until calling the API. TF_LOG might not help much. Closing this issue now. Feel free to reopen if you want to continue the conversation. Thank you
