### ISSUE TITLE
##critical - google_cloud_run_service - Not deploying the newer versions from registry automatically

### ISSUE THREAD

**Issue by sasemb** [hashicorp/terraform-provider-google#10485]
Hi Team,

We are deploying one of our services into cloud run engine 

It was working previously as expected . So the actual problem is as part of our CI/CD process , For any changes going into codebase , we build a new docker image
and push to google container registry with latest tag and the same artifacts will trigger our deployment where terraform will read the latest image from registry
and deploy a new version into cloud run services. 

Currently user reported that they are not able to see the latest changes from cloud run services . Further checking , I observed that the state file has updated
with latest container image checksum but the latest revision is not deployed in cloud run . 

Please note that we are using docker provider and data to fetch the latest image url and checksum from registry

data "docker_registry_image" "image_name" {
  name = "gcr.io/${ var.project_id }/${ var.serviceName}:${ var.tagName }"
}

**Affected resources:** 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service

**Terraform Block:**

resource google_cloud_run_service default {
  name = optimization
  location = us-central1
  autogenerate_revision_name = true
  project = "confidential"

  template {
    spec {
      container_concurrency = 80
      
     
      

      containers {
        image = gcr.io/qa-peso-na-measurement/optimization:latest

        resources {
          limits = {
            cpu = "2056m"
            memory = "2056Mi"
          }
        }

      } 
      
    }
       

   

  metadata {
    annotations = {
      "autoscaling.knative.dev/maxScale" = 20
      "autoscaling.knative.dev/minScale" = 1
     
    }
  }      
      
   }

  
}

**Expected behavior**  - Terraform should deploy a new version when there is a new image present in the container registry. 

**Actual behavior** - Only terraform state file gets updated with latest container id but there is no deployment in cloud run revisions.

**Comment by edwardmedia** [comment]
@sasemb do you trigger `terraform apply` in an automation fashion?

**Comment by edwardmedia** [comment]
This is dup of https://github.com/hashicorp/terraform-provider-google/issues/10185. Use #10185 to track the progress. Closing this

**Comment by sasemb** [comment]
@edwardmedia  Hi , This is related to cloud run where it's not deploying the latest container images.

#10185 is more related to google flex app engine  .

So there are two issues. Request you to reopen this issue again
