### ISSUE TITLE
google_storage_bucket - Change in lifecycle_rule's condition is not recognised 

### ISSUE THREAD

**Issue by rohitvyavahare** [hashicorp/terraform-provider-google#10480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform Version
Terraform v0.15.3
on darwin_amd64

- provider registry.terraform.io/hashicorp/google v3.82.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "bucket" {
  name          = "my-bucket"
  location      = "europe-west1"
  storage_class = "STANDARD"

  versioning {
    enabled = true
  }

  lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      days_since_custom_time = 30
      with_state                 = "ARCHIVED"
    }
  }
}
```

### Expected Behavior

I decided to update lifecycle_rule's condition days_since_custom_time to 35.
I expected Terraform to recognize the change.

### Actual Behavior

No changes were identified.

### Steps to Reproduce

```tf
resource "google_storage_bucket" "bucket" {
  name          = "my-bucket"
  location      = "europe-west1"
  storage_class = "STANDARD"

  versioning {
    enabled = true
  }

  lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      days_since_custom_time = 35
      with_state                 = "ARCHIVED"
    }
  }
}
```

1. `terraform apply`

### Important Factoids

Change days_since_custom_time to 35.
Run terraform plan or terraform apply again.

### References

* #0000

**Comment by ScottSuarez** [comment]
This is a question/issue for terraform-core. Please redirect this issue to them 
https://github.com/hashicorp/terraform
