### ISSUE TITLE
google_project resource cannot have null for org_id and goes into a modify cycle

### ISSUE THREAD

**Issue by parabolic** [hashicorp/terraform-provider-google#10495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```sh
terraform version
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.0.0
+ provider registry.terraform.io/terraform-providers/sumologic v2.11.0
```

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
resource "google_project" "project" {
  billing_account = var.billing_account

  name       = var.name
  project_id = local.project
  folder_id  = var.folder_id # null by default
  org_id     = var.org_id # null by default

  auto_create_network = var.auto_create_network
  skip_delete         = var.skip_delete

  labels = var.labels
}

```

### Debug Output
Due to security considerations I am not able to share the debug output :(

### Expected Behavior

Terraform reports no changes.

### Actual Behavior

Terraform want's to remove `org_id` (modify `google_project.project`). After a successfull apply it wants to modify the resource again, meaning `org_id` cannot be removed. [^1]

[^1]:![image](https://user-images.githubusercontent.com/2648043/140304092-4c10f7d4-f614-4dc6-960f-6456fdf12bda.png)

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

I've tried manually removing the `"org_id": null,` from the state but it re-appears again upon running `terraform apply`. This started happening after I upgraded terraform and the GCP provider to the latest versions. A possible fix would be to pass the org_id as a variable but it would be nice if I don't have to do it to retain the previous behavior. The org_id is an optional parameter according to the documentation [^2].

[^2]:https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project#org_id

**Comment by edwardmedia** [comment]
@parabolic when we create a project, a parent is required, either `folder_id` or `org_id`, but not both. That is why both fields are defined as `optional`.  Which one did you provide? Can you repro with a single `google_project`?

**Comment by parabolic** [comment]
Hi @edwardmedia thanks for the answer. 
That's interesting, I was suspecting that one of those params is required, but we haven't had this issue so far and we were using neither. Let me try and create another project with the latest provider and I'll get back to you.

**Comment by edwardmedia** [comment]
@parabolic let me know what you found.

**Comment by parabolic** [comment]
@edwardmedia I was able to create a new project without providing `org_id` nor `folder_id`. We only pass the `id` and the `billing_id` for the project, and as to my knowledge those are the only 2 required parameters.[^1]

Closely reading the documentation there's no hint that any of those 2 params (org_id, folder_id) are required:
>Only one of org_id or folder_id may be specified. If the org_id is specified then the project is created at the top level. 

A second run of `terraform apply`, shows the same removal of `org_id` even for the new project. [^2]
Please advise.

[^1]:https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project
[^2]:![image](https://user-images.githubusercontent.com/2648043/140487705-d68e2a23-b74c-474c-932a-b4413c7e2124.png)

**Comment by edwardmedia** [comment]
@parabolic Interesting. You can create a project without specifying a parent. Can you share the full debug log that contains all api requests & responses?

**Comment by parabolic** [comment]
@edwardmedia That is interesting. 
I haven't switched accounts and me and my team are using the gsuite authentication. 
We execute `gcloud auth login` and then my gsuite email is  set as active when I run `gcloud auth list` [^1]
Are you using a service account ? I can create a service account and try an apply with it.

[^1]:![image](https://user-images.githubusercontent.com/2648043/140549973-6f123349-0015-4128-85ed-30403e7da8ce.png)

**Comment by edwardmedia** [comment]
@topfunky I do see it is possible that a project can be created without providing folder or org. (yes, must use a non service account) That is not enterprise. But in your case, gcp assigns a org_id even you did not provide one? Interesting use case

**Comment by parabolic** [comment]
@edwardmedia so the takeaway is, if one uses a service account then `org_id` or `folder_id` must be provided. With the gsuite (`gcloud auth login`) authentication the `org_id` somehow is automatically assumed. 

>But in your case, gcp assigned an org_id even you did not provide one?

To answer your question, no I haven't provided a `org_id`. I  just provide the `name`  and the `billing_id` parameters. 
For us ( I imagine for other companies) using Service Accounts makes no sense unless absolutely necessary (e.g. Workloads outside of GCP). I don't envision using them in the near future.
Hope this helps.
Thanks for the support.

**Comment by edwardmedia** [comment]
@parabolic please review the GCP [Resource hierarchy](https://cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy) A project should be created either under a folder or directly under a org. Like what you did, a project may be created without an org or folder, but this is not for enterprise. As a tool targeting enterprise, I don't think this needs to be supported. To resolve this, if you have a legit org_id, I think you should explicitly add it in the config. 
Does this make sense?

**Comment by edwardmedia** [comment]
@parabolic I am closing this issue now. Feel free to reopen if you see it differently

**Comment by parabolic** [comment]
@edwardmedia sorry I got distracted and completely forgot about replying.

>please review the GCP Resource hierarchy A project should be created either under a folder or directly under an org.

I know the resource hierarchy well enough, I have even written a blog post based on it [^1]. 

>We don't want to suppress this error

It is not an error. I guess we can call it mild annoyance. Terraform reports constant plan changes, which it shouldn't do to my understanding, that is all. 


It used to work without an issue and it only started showing the cyclic plans when the provider was upgraded to `4.0.0`. We had `3.38.0` previosly.

[^1]:https://cloudlad.io/terraform-0-13-and-google-cloud
