### ISSUE TITLE
gcp_compute_firewall source_ranges is never deleted (in favor of source_tags)

### ISSUE THREAD

**Issue by bmsareias** [hashicorp/terraform-provider-google#10496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.7
hashicorp/google v4.0.0
hashicorp/google-beta v4.0.0

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

1st config
```tf
resource "google_compute_firewall" "some-rule" {
  provider       = google-beta
  name           = "some-rule"
  network        = google_compute_network.network.self_link
  project        = google_compute_network.network.project
  direction      = "INGRESS"
  priority       = 10

  source_ranges  = [
    "192.168.0.0/24",
  ]

  source_tags = [
    "foo",
  ]

  target_tags = [
    "bar",
  ]
  
  allow {
    protocol = "all"
  }
}
```

2nd config
```tf
resource "google_compute_firewall" "some-rule" {
  provider       = google-beta
  name           = "some-rule"
  network        = google_compute_network.network.self_link
  project        = google_compute_network.network.project
  direction      = "INGRESS"
  priority       = 10

  source_tags = [
    "foo",
  ]

  target_tags = [
    "bar",
  ]
  
  allow {
    protocol = "all"
  }
}
```

### Expected Behavior

After running the second config, the `sources_range` should be removed completely as shown in the plan/apply output.

### Actual Behavior

After running the second config, the `sources_ranges` is kept unchanged even if:

```tf
resource "google_compute_firewall" "some-rule" {
  (...)
  source_ranges  = null
  (...)
}
```

or

```tf
resource "google_compute_firewall" "some-rule" {
  (...)
  source_ranges  = []
  (...)
}
```

which according to [issue/8076](https://github.com/hashicorp/terraform-provider-google/issues/8076), `sources_range = []` should actually delete the `sources_range`, however at this time it doesn't delete it AT ALL, therefore I'm forced to either delete that Manually or taint the resource.

### Steps to Reproduce

1. `terraform apply` on the first TF code
2. `terraform apply` on the second TF code

### Extra info

This behaviour should have been fixed by release `v4.0.0`, as the previous bug ([issue/8076](https://github.com/hashicorp/terraform-provider-google/issues/8076)) was `closed`, however this is still reproducible.

Furthermore, this was tested with both `v4.0.0 google` and `v4.0.0 google-beta` providers

**Comment by ritmas** [comment]
I'm facing kind of similar issue related to `source_ranges` on v4.0.0 with both google & google-beta providers.

- I have a rule with 45 items (I guess it can be of any size) in `source_ranges`
- Upgraded providers from v3.89.0 to v4.0.0
- Added one more IP range

While applying the changes terraform shows it will add new item and the rest of them will be unchanged, but actually all existing IP ranges are being deleted and just the newest one remains.
```bash
      ~ source_ranges           = [
          + "x.x.x.x/32",
            # (45 unchanged elements hidden)
        ]
```

Now, it gets interested when re-applying the same config again all previous IP ranges are being rollbacked and the newest one is removed.
```bash
      ~ source_ranges           = [
          + "x.x.x.x/32",
           #   <45 items in total>
          + "x.x.x.x/32",
            # (1 unchanged elements hidden)
        ]
```

Downgrading providers from v4.0.0 to v3.89.0, terraform behaves as intended.
