### ISSUE TITLE
Add support to advancedOptionsConfig(jsonParsing and logLevel) to a google_compute_security_policy

### ISSUE THREAD

**Issue by yagince** [hashicorp/terraform-provider-google#10497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to add `json-parsing` and `log-level` settings to `google_compute_security_policy`.

Currently, I think the only way to set this up is with a command like the following
````
❯ gcloud compute security-policies update xxxx-policy --json-parsing=STANDARD --log-level=VERBOSE
````

### New or Affected Resource(s)

* `google_compute_security_policy`

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "policy" {
  name = "my-policy"
  
  advanced_options_config {
    json_parsing = "STANDARD"
    log_level = "VERBOSE"
  }
}
```

### References

- https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/insert

**Comment by matdtr** [comment]
Hi, 

Any ETA on this?

**Comment by roobert** [comment]
I'm not sure if this might affect the priority of this feature but it's recommended to enable this option as part of the log4shell fix when dealing with JSON: https://cloud.google.com/blog/products/identity-security/cloud-armor-waf-rule-to-help-address-apache-log4j-vulnerability
