### ISSUE TITLE
How to define app engine entrypoint that is required required, for purely hosting static files?

### ISSUE THREAD

**Issue by gsipos** [hashicorp/terraform-provider-google#10505]
In the recent v4 version there was a breaking change that broke our pipelines.
> appengine: marked google_app_engine_standard_app_version entrypoint as required (#10425)

I only want to host static files on app engine. I don't have any runnable server code.
What do I have to define in the `entrypoint` block in this case?

Could I just write something like this:
```
  entrypoint {
    shell = "node -v"
  }
```
This feels hacky and wrong. Any help is appreciated!

**Comment by gsipos** [comment]
It seems that the `entrypoint` is required but the value of the shell property can be empty like:
```
  entrypoint {
    shell = ""
  }
```

Can someone confirm that this is the correct way to configure this?

**Comment by edwardmedia** [comment]
@gsipos here is the original api doc that explains how to use it. 

https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#Entrypoint

**Comment by edwardmedia** [comment]
@gsipos does that work? Is this till a question?

**Comment by gsipos** [comment]
Yes the `shell` is required by terraform, but the value can be empty like `shell = ""`. This solves the issue.

It is confusing, because contradicting the documentation here: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#runtime_and_app_elements
Which states that the entrypoint is just optional.

**Comment by edwardmedia** [comment]
@gsipos glad it works for you. Closing this question then
