### ISSUE TITLE
Safe user detection not working in some (all?) cases

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10506]
See https://pantheon.corp.google.com/cloud-build/builds/60d23ca1-ff2b-4f1b-823e-33d2f80dca90;step=23?project=graphite-docker-images. This was for a PR that was made by a safe user, but the CI pipeline didn't detect them properly as such and so didn't automatically run the VCR tests. Possibly something is wrong with the detection code, or something changed about Github - it's unclear from the output.

**Comment by rileykarson** [comment]
Closing as outdated since we've changed this system substantially twice since this was filed.
