### ISSUE TITLE
Hi Hashicorp Team,

### ISSUE THREAD

**Issue by bhagyashreemohan** [hashicorp/terraform-provider-google#10504]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by bhagyashreemohan** [comment]
I tried picking registry for AutoML GCP in terraform but major registry is missing please release it soon.Cuurently i'm trying to test Automl in gcp using terraform using infra creation.

**Comment by edwardmedia** [comment]
The release is on schedule. Please looking for next one.
