### ISSUE TITLE
create_before_destroy lifecycle propagated to the dependent objects

### ISSUE THREAD

**Issue by tejavar** [hashicorp/terraform-provider-google#10512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Product Version: TF 0.14.2, `google` 3.51.0

### Affected Resource(s)

* create_before_destroy

### Terraform Configuration Files

```main.tf
provider "google" {
  project = "abc"
  credentials = "xx"
}
 
resource "google_storage_bucket" "b" {
  name          = "test-bucket"
  location      = "US"
  force_destroy = true
  uniform_bucket_level_access = true
}
 
resource "google_storage_bucket_object" "bo" {
  name = "bucket_object"
  #content = "bucket_object_contents"
  content = "bucket_object_contents_changed"
  bucket = google_storage_bucket.b.name
  lifecycle {
    create_before_destroy = true
  }
}

```

### Expected Behavior

A bucket object should be able to use `create_before_destroy`, or at least the deletion after apparent create should not happen.

### Actual Behavior

A `create_before_destroy` lifecycle cannot be used with a `google_storage_bucket_object` when the name does not change. The bucket object is "created", then deleted, however the ID of the bucket object is the name, and being the same results in the bucket object being deleted.

### Steps to Reproduce

Use the attached configuration. Set up the google provider so that it works for you. Apply. Edit the configuration and change the `content` argument for the bucket object (change is provided in a comment). Apply. Observe that the apply says 1 created and 1 destroyed, however the bucket object no longer exists. This can be seen in the GCP console, or by using `gcloud`, or by using `terraform refresh` followed by `terraform state list`. 

1. `terraform apply`

### References

Additional Context : 

> The order of operation is causing us an issue. We have a google_compute_instance_template resource which has a create before destroy lifecycle event.

> "In order to effectively use an Instance Template resource with an Instance Group Manager resource, it's recommended to specify create_before_destroy in a lifecycle block." (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template)

> We pass a bucket object in metadata.startup-script-url field in the instance template that creates the dependency. When we update the instance template and bucket object the bucket object is deleted from the bucket. Which is causing the compute instance to fail to start properly.

So there is a real side-effect to this behavior that results in errors. We did not reproduce this scenario, but once we diagnosed what the root cause was we could avoid this problem. I think it is unfortunate enough that TF will appear to successfully apply while deleting the thing it said it was creating.

* #0000

[](url)

**Comment by megan07** [comment]
Closing per internal discussion.
