### ISSUE TITLE
google_monitoring_alert_policy: support "Incident autoclose duration" (also known as Incident auto-close duration)

### ISSUE THREAD

**Issue by ronisec** [hashicorp/terraform-provider-google#10523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There's an option to configure the "Incident autoclose duration" when creating an alert from the Cloud Console UI. When creating an alert through Terraform this value is always equal to 7-days. For some alerts we want to configure this to a shorter time period (such as 30-minutes or 1-hour as is possible through the UI).

### New or Affected Resource(s)

* google_monitoring_alert_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by Ubaldo-Brea** [comment]
Hi there, we need this feature in our project to set up this time on our alerts with terraform. When we cmay have this improved? Thank you!

**Comment by dgteixeira** [comment]
Hello all, this is a good issue, we would like to use it for our terraform GCP projects.
I see that it is already appointed to a milestone, however, there are no ETA's attached due to lower priority.

Any ideia on when this could be implemented?

Thanks!

**Comment by melinath** [comment]
This seems to now be implemented: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#auto_close
