### ISSUE TITLE
Support to add transit_encryption_mode in google_redis_instance to the google GA provider

### ISSUE THREAD

**Issue by sanmmishra** [hashicorp/terraform-provider-google#10530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This attribute `transit_encryption_mode` is not supported in the GA provider, but it worked as expected in the google-beta provider. Can we migrate this to the GA provider?

The error we get otherwise through GA provider is 

```
  on main.tf line 28, in resource "google_redis_instance" "instance":
  28:   transit_encryption_mode = var.transit_encryption_mode # need to add

An argument named "transit_encryption_mode" is not expected here.
```

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```
resource "google_redis_instance" "instance" {
 # provider = google-beta  # feature should work without reference to google-beta

  project                 = var.project
  alternative_location_id = var.alternative_location_id
  authorized_network      = var.authorized_network
....
  transit_encryption_mode = var.transit_encryption_mode
```

### References

* #0000

**Comment by rileykarson** [comment]
note: Not sure if this is actually GA yet

**Comment by sanmmishra** [comment]
The gcloud command (GA) one refers to it in this [link ](https://cloud.google.com/memorystore/docs/redis/enabling-in-transit-encryption#creating_a_redis_instance_with_in-transit_encryption).. Is that a reliable indicator

**Comment by rileykarson** [comment]
That works, thanks!

**Comment by sanghaniJ** [comment]
b/263934913

**Comment by sanghaniJ** [comment]
I've gone through this issue and this issue ticket requests to promote `transit_encryption_mode` in resource `redis_instance`. 
- It seems like a [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/4838) was done for the same and was merged. 
- After checking the [terraform doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance#transit_encryption_mode) we can see that the field is GA-ed. 
Hence, closing this issue.
