### ISSUE TITLE
google_scc_notification_config -  Error 403: Security Command Center API has not been used 

### ISSUE THREAD

**Issue by pfilourenco** [hashicorp/terraform-provider-google#10534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.0.0
+ provider registry.terraform.io/hashicorp/google-beta v4.0.0

### Affected Resource(s)

google_scc_notification_config

### Terraform Configuration Files

```tf

provider "google" {
  project = "xxxxxostprj-x-xxx353"
  region  = var.region
}


resource "google_scc_notification_config" "custom_notification_config" {
  config_id    = "my-config"
  organization = "1xxxxxxxx4"
  description  = "My custom Cloud Security Command Center Finding Notification Configuration"
  pubsub_topic = google_pubsub_topic.scc_notification.id

  streaming_config {
    filter = "category = \"OPEN_FIREWALL\" AND state = \"ACTIVE\""
  }
}

```

### Debug Output

```
╷
│ Error: Error creating NotificationConfig: googleapi: Error 403: Security Command Center API has not been used in project <project_number> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/securitycenter.googleapis.com/overview?project=<project_number> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.Help",
│     "links": [
│       {
│         "description": "Google developers console API activation",
│         "url": "https://console.developers.google.com/apis/api/securitycenter.googleapis.com/overview?project=<project_number>"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/<project_number>",
│       "service": "securitycenter.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ 
│   with google_scc_notification_config.custom_notification_config,
│   on pub_sub.tf line 5, in resource "google_scc_notification_config" "custom_notification_config":
│    5: resource "google_scc_notification_config" "custom_notification_config" {
│ 
╵
2021-11-10T09:04:53.351Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-11-10T09:04:53.352Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.0.0/linux_amd64/terraform-provider-google_v4.0.0_x5 pid=6786
2021-11-10T09:04:53.352Z [DEBUG] provider: plugin exited
```

### Expected Behavior

- Apply at the correct project ID. 

### Actual Behavior

- ERROR with project ID that I Have not configured and have no idea what is this project ID. 

### Steps to Reproduce

Enable SCC premium at org level
Enable SCC API at project level
1. `terraform apply`

### References

* #0000

**Comment by c2thorn** [comment]
@pfilourenco To confirm, you have applied the `securitycenter` API at the project listed in your provider schema?

The number returned by the API here is probably your project "number", not your project "ID". Can you confirm the number of your project?

**Comment by pfilourenco** [comment]
Hi @c2thorn,

Yes, I have the API enabled in my project (I can go to the api and see the security center without any problems) and this is not the project number. I have no idea which project this number is.

Project number:
95xxxxxx75

API:
![image](https://user-images.githubusercontent.com/64209266/141267851-6346ec76-b0e0-4513-a008-7200e87cc3f8.png)

**Comment by pfilourenco** [comment]
note: if I change the organization parameter, I still have the same problem.

**Comment by pfilourenco** [comment]
Hello,

@c2thorn found out the "problem". SCC API does not accept auth with gcloud user.

The solution: 
- SA Creation with SCC IAM privilegies  
- Impersonate that SA on TF

    
```tf
/******************************************
  This provider is used to get SA used for impersonation
  
  This is required to use SCC API : 

- Error creating NotificationConfig: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the securitycenter.googleapis.com. 
- We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. 
- For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.
 *****************************************/
provider "google" {
  alias   = "tokengen"
  project = var.project_id
}
data "google_client_config" "default" {
  provider = google.tokengen
}
data "google_service_account_access_token" "sa" {
  provider               = google.tokengen
  target_service_account = "<name>@<project_id>.iam.gserviceaccount.com"
  lifetime               = "600s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
  ]
}
/******************************************
  GA Provider configuration
 *****************************************/
provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
}
```

**Comment by c2thorn** [comment]
@pfilourenco I'm glad you were able to find a solution. This is surprising to me. How did you find that the API was not using your gcloud auth?

**Comment by pfilourenco** [comment]
> @pfilourenco I'm glad you were able to find a solution. This is surprising to me. How did you find that the API was not using your gcloud auth?

I tried it on a new clean gcp project and this was the first error that came up.

`Error creating NotificationConfig: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the securitycenter.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.`
