### ISSUE TITLE
google_redis_instance add support for Read replicas (beta)

### ISSUE THREAD

**Issue by ErikMoller** [hashicorp/terraform-provider-google#10549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is new feature out for Read replicas Redis GCP. Super nice! 
It's currently in preview state and not yet supported in terraform module. 
When you run all infrastructure in Terraform it would also be great to be able to use the new features as quickly as possible. 

Thanks,

Doc: 
- https://cloud.google.com/memorystore/docs/redis/read-replicas
- https://cloud.google.com/memorystore/docs/redis/managing-read-replicas

**Comment by roaks3** [comment]
This appears to be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5449, and was promoted to GA with https://github.com/GoogleCloudPlatform/magic-modules/pull/5838
