### ISSUE TITLE
add bfd to google_compute_router_peer

### ISSUE THREAD

**Issue by ccschmid9** [hashicorp/terraform-provider-google#10554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It doesn't appear bfd can be configured with google_comput_router_peer.  

The enhancement would be useful since Google's default for bfd is Disabled. Bfd should be used for optimal routing convergence in a highly available bgp environment. 

### New or Affected Resource(s)

* google_compute_router_peer
*    bfd (optional)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_router_peer" "peer" {
  name                      = "my-router-peer"
  router                    = "my-router"
  region                    = "us-central1"
  peer_ip_address           = "169.254.1.2"
  peer_asn                  = 65513
  advertised_route_priority = 100
  interface                 = "interface-1"
  bfd                       = {
    session_initialization_mode = enum
    min_transmit_interval       = integer
    min_receive_interval        = integer
    multiplier                  = integer
  }
}

```

### References
https://cloud.google.com/compute/docs/reference/rest/v1/routers
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_peer

* #0000

**Comment by c2thorn** [comment]
added in https://github.com/hashicorp/terraform-provider-google/pull/10487
