### ISSUE TITLE
Unable to import module.sql-db.google_sql_database.default[0] resource using terraform

### ISSUE THREAD

**Issue by ayushmankoul** [hashicorp/terraform-provider-google#10564]
I am trying to import module.sql-db.google_sql_database.default[0] resource from gcp using following command 

> terraform` import module.sql-db.google_sql_database.default[0] prj-dev-psi/mcdefrand011

`module.sql-db.google_sql_database.default[0]: Importing from ID "prj-dev-psi/mcdefrand011"...
module.sql-db.google_sql_database.default[0]: Import prepared!
  Prepared google_sql_database for import
module.sql-db.google_sql_database.default[0]: Refreshing state... [id=projects/prj-dev-psi/instances/prj-dev-psi/databases/mcdefrand011]
Error: Cannot import non-existent remote object While attempting to import an existing object to "module.sql-db.google_sql_database.default[0]", the provider detected that  
no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is   
associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for     
this resource.
╵`

What could be the right import command for this resource?
Project name = prj-dev-psi
Instance = mcdefrand011
name = "default"

**Comment by melinath** [comment]
Hi! The accepted import formats are documented here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database#import it looks like the format you're using (`{{project}}/{{instance}}`) is not an accepted format. Try `{{project}}/{{instance}}/{{name}}` instead - i.e. `prj-dev-psi/mcdefrand011/default`

**Comment by melinath** [comment]
Feel free to reopen if that doesn't work for you!
