### ISSUE TITLE
Failing test(s): TestAccEventarcTrigger_BasicHandWritten

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10581]
Failure rate:
- 100% since Nov 11

Impacted tests:
- TestAccEventarcTrigger_BasicHandWritten

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/220033?buildTab=tests&expandedTest=858419126038598454

Message:

```
Error: Error creating Service: googleapi: Error 400: metadata.name: Resource name must use only lowercase letters, numbers and '-'. Must begin with a letter and cannot end with a '-'. Maximum length is 63 characters.
```

Notes:
- It looks like this is because the service name [now uses underscores](https://ci-oss.hashicorp.engineering/repository/download/GoogleCloud_ProviderGoogleCloudGoogleProject/220033:id/debug-google-cd8f297-TestAccEventarcTrigger_BasicHandWritten.log) (previously [it used dashes](https://ci-oss.hashicorp.engineering/repository/download/GoogleCloud_ProviderGoogleCloudGoogleProject/216976:id/debug-google-5e4496e-TestAccEventarcTrigger_BasicHandWritten.log).) (Search logs for `POST /apis/serving.knative.dev/v1/namespaces/`

**Comment by melinath** [comment]
This is probably test-only; the change was introduced in https://github.com/hashicorp/terraform-provider-google/commit/82e5f7ed12b8aa0c1492e8a55a98d240c677fb43

**Comment by melinath** [comment]
It looks like the [MM PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5325/files#L421) flipped the logic for determining whether to use `-` or `_`

**Comment by ndmckinley** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5477.
