### ISSUE TITLE
Missing Private Service Connection related attributes

### ISSUE THREAD

**Issue by mmf55** [hashicorp/terraform-provider-google#10588]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Currently, the way to create a Private Service Connection (PSC) is using the `google_compute_global_forwarding_rule` resource, but after the resource creation, not all the PSC-related attributes are available. One example is the PSC connection ID.

### New or Affected Resource(s)

* google_compute_global_forwarding_rule

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_forwarding_rule" "fr" {
  name   = "test-fr"
  region = var.region

  target                = "projects/project1/regions/us-central1/serviceAttachments/attachment1"
  load_balancing_scheme = "" # need to override EXTERNAL default when target is a service attachment
  network               = "network1"
  ip_address            = google_compute_address.gcaddr.id
}

output "psc_connection_id" {
  value = google_compute_forwarding_rule.fr.psc_connection_id
}
```

### References

[Configuring Private Service Connect to access services](https://cloud.google.com/vpc/docs/configure-private-service-connect-services)
[Compute Forwarding rule documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_forwarding_rule)

**Comment by Zawadidone** [comment]
What other options are there now using this provider to receive the `PSC Connection ID`?

**Comment by midu-git** [comment]
Is there any progress on this issue? This is a quite important feature for us.

I would be happy to support, if someone points me into the right direction.

**Comment by shuyama1** [comment]
Features added in https://github.com/GoogleCloudPlatform/magic-modules/pull/6124 and the PR just got merged. Therefore, closing this now.
