### ISSUE TITLE
google_cloud_run_service run.googleapis.com/ingress always missing

### ISSUE THREAD

**Issue by yanc0** [hashicorp/terraform-provider-google#10589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.11
on linux_amd6

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "api" {
  provider = google-beta

  name                       = "api"
  location                   = var.region
  autogenerate_revision_name = true

  template {
    metadata {
      annotations = {
        "run.googleapis.com/ingress"              = "internal-and-cloud-load-balancing"
        "run.googleapis.com/launch-stage"         = "ALPHA"
        "run.googleapis.com/vpc-access-connector" = "projects/${var.project}/locations/${var.region}/connectors/${var.vpc_connector_name}"
        "run.googleapis.com/vpc-access-egress"    = "all"
        "run.googleapis.com/cpu-throttling"       = "false" // cpu always on
        "autoscaling.knative.dev/minScale"        = "1"
        "autoscaling.knative.dev/maxScale"        = "6"
        "client.knative.dev/user-image"           = var.docker_image
      }
    }
[...]
```

### Debug Output

```
 ~ resource "google_cloud_run_service" "fleet_management_api" {
        id                         = "locations/europe-west1/namespaces/hprod-dev/services/api"
        name                       = "api"
        # (4 unchanged attributes hidden)


      ~ template {
          ~ metadata {
              ~ annotations = {
                  + "run.googleapis.com/ingress"              = "internal-and-cloud-load-balancing"
[...]
```

### Expected Behavior

No change is expected. Cloud Run Service is correctly configured.

### Actual Behavior

A change is made continuously.

### Steps to Reproduce

Create a service with `"run.googleapis.com/ingress"              = "internal-and-cloud-load-balancing"` like documented here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service

Search for "ingress". If you look at the REST API reference, you may see a specific behaviour concerning the "ingress" annotation.

### References

* [Terraform Documentation - cloud_run_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service)
* [CloudRun REST API](https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services#Service)
* b/272080267

**Comment by edwardmedia** [comment]
Related to https://github.com/hashicorp/terraform-provider-google/issues/8312

**Comment by jmotex** [comment]
+1

**Comment by mservidio** [comment]
+1

**Comment by zimbatm** [comment]
The metadata "internal" annotation is actually on the service level, not the template level. I know, because I did the same mistake :)

```tf
resource "google_cloud_run_service" "api" {
  name                       = "api"
  location                   = var.region
  autogenerate_revision_name = true

  metadata {
    annotations = {
      # Move it here  
      "run.googleapis.com/ingress" = "internal-and-cloud-load-balancing"
    }
  }

  template {
    metadata {
      annotations = {
        # "run.googleapis.com/ingress"              = "internal-and-cloud-load-balancing"
        "run.googleapis.com/launch-stage"         = "ALPHA"
        "run.googleapis.com/vpc-access-connector" = "projects/${var.project}/locations/${var.region}/connectors/${var.vpc_connector_name}"
        "run.googleapis.com/vpc-access-egress"    = "all"
        "run.googleapis.com/cpu-throttling"       = "false" // cpu always on
        "autoscaling.knative.dev/minScale"        = "1"
        "autoscaling.knative.dev/maxScale"        = "6"
        "client.knative.dev/user-image"           = var.docker_image
      }
    }

```

**Comment by sorenhansendk** [comment]
@zimbatm Thank you for the tip. It works perfectly for me! 👍

**Comment by mr-pascal** [comment]
@zimbatm 
thanks for answering this issue.

I have the same issue with the ` "run.googleapis.com/launch-stage"` property. it's always in the terraform plan as "change".

I can see, that in your example you have it in the "template.metatadata.annotations" instead of "metadata.annotations".
I have it in the "metadata.annotations" since it's also located there in the official examples (using v3.90.1 of the provider) at https://registry.terraform.io/providers/hashicorp/google/3.90.1/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables

![image](https://user-images.githubusercontent.com/4190798/200856905-8a951e8e-90aa-4fc1-9711-4195319eb8e5.png)

So could I assume that the dos are just bad in that case? 🤔

**Comment by yanweiguo** [comment]
Cloud Run Admin API documents some supported system annotations and on which resources they are accepted: https://cloud.google.com/run/docs/reference/rest/v1/ObjectMeta. `run.googleapis.com/ingress`  is only accepted on Service resource so it must be set on `google_cloud_run_service.metadata.annotations`.

RE https://github.com/hashicorp/terraform-provider-google/issues/10589#issuecomment-1308852906, `run.googleapis.com/launch-stage` is accepted on Service and Job resources. The launch stage setting in this old [example](https://registry.terraform.io/providers/hashicorp/google/3.90.1/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables) was a mistake.
