### ISSUE TITLE
Failing test(s): error waiting for creating dataproc cluster: subnetwork is not ready

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10585]
Failure rate:

TestAccDataprocCluster_withImageVersion:
- 6% in Oct 2021
- 23% from Nov 1-17 2021

TestAccDataprocCluster_withServiceAcc:
- 3% in Oct 2021
- 17% from Nov 1-17 2021

TestAccDataprocCluster_withConfigOverrides:
- 10% in Oct 2021
- 17% from Nov 1-17 2021

TestAccDataprocCluster_withAccelerators:
- 3% in Oct 2021
- 5% from Nov 1-17 2021

Impacted tests:
- TestAccDataprocCluster_withImageVersion
- TestAccDataprocCluster_withServiceAcc
- TestAccDataprocCluster_withConfigOverrides
- TestAccDataprocCluster_withAccelerators

Nightly builds:
-https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/220033?buildTab=tests&expandedTest=5694668569733713838

Message:

```
Error waiting for creating Dataproc cluster: Error code 3, message: The resource 'projects/project-id/regions/us-central1/subnetworks/default' is not ready
```

**Comment by rileykarson** [comment]
We retry when APIs return a 400 w/ this message, we can ask the API team to fix the error code

**Comment by shuyama1** [comment]
The tests have passed successfully for the past 2 months, so I am closing this issue. Will reopen it if the tests start to fail again.
