### ISSUE TITLE
Failing test(s): TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10583]
Failure rate:
- 100% since Oct 28 2021

Impacted tests:
- TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/220033?buildTab=tests&expandedTest=5403825055001777426

Message since Nov 2:

```
Error: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 10m0s)
```

Previous message:
```
Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 13, message: An internal error occurred while processing task /app-engine-flex/flex_await_healthy/flex_await_healthy>2021-10-28T09:58:56.522Z279634.in.0: Backend service aef-appengine--network--endpoint--group-v1-bs not found in project project-id while getting instances for ManagedInstanceGroup.
```

**Comment by shuyama1** [comment]
Removing the old service via console seems to make the test pass for the last two nightly builds. Will come back to update the success rate.

**Comment by shuyama1** [comment]
Success rate: 100% since Dec 9 2021 
https://ci-oss.hashicorp.engineering/test/5403825055001777426?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E
Therefore I will close this issue.
