### ISSUE TITLE
Failing test(s): TestAccComposerEnvironment_* (Error waiting for Creating Environment)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10594]
### Affected Resource(s)

* google_composer_environment

Failure rate:
- ~10% each in Oct 2021

Impacted tests:
- TestAccComposerEnvironment_withMaintenanceWindow
- TestAccComposerEnvironment_privateWithWebServerControl
- TestAccComposerEnvironment_withWebServerConfig
- TestAccComposerEnvironment_basic
- TestAccComposerEnvironment_update
- TestAccComposerEnvironment_withEncryptionConfig
- TestAccComposerEnvironment_withEncryptionConfigComposer2
- TestAccComposerEnvironment_private
- TestAccComposerEnvironment_withSoftwareConfig
- TestAccComposerEnvironment_withDatabaseConfig

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/220058?buildTab=tests&expandedTest=201055918623426561

Message:

```
Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 3, message: Http error status code: 400
Http error message: BAD REQUEST
Errors in: [Web server]; Error messages:
  Failed to deploy the Airflow web server. This might be a temporary issue. You can retry the operation later.
```

withEncryptionConfig also sometimes fails with:

```
provider_test.go:309: Step 1/3 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
# google_project_iam_member.kms-project-binding2 will be created
+ resource "google_project_iam_member" "kms-project-binding2" {
+ etag    = (known after apply)
+ id      = (known after apply)
+ member  = "serviceAccount:service-<project number>@compute-system.iam.gserviceaccount.com"
+ project = "<project id>"
+ role    = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
}
```

**Comment by rileykarson** [comment]
Note: We should reach out to the Composer team, I suspect this is an API issue and not a Terraform one based on the error message received.

**Comment by c2thorn** [comment]
Other teams experience this, and the composer team has b/209640939 filed

**Comment by c2thorn** [comment]
I'm not sure anything can be done on our end.

**Comment by c2thorn** [comment]
Reopening to avoid duplicates

**Comment by melinath** [comment]
The withEncryptionConfig kms message could be related to the IAM contention issues we've been seeing - attn @roaks3

**Comment by SarahFrench** [comment]
I'm going through test failures as part of BOD - glad the new KMS/IAM issue has been spotted already! 
I've seen it happen for `TestAccComposerEnvironment_withEncryptionConfigComposer2` so I'll add it to the PR description and some details below:

```
------- Stdout: -------
=== RUN   TestAccComposerEnvironment_withEncryptionConfigComposer2
=== PAUSE TestAccComposerEnvironment_withEncryptionConfigComposer2
=== CONT  TestAccComposerEnvironment_withEncryptionConfigComposer2
vcr_utils.go:144: Step 1/3 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
# google_kms_crypto_key_iam_member.iam will be created
+ resource "google_kms_crypto_key_iam_member" "iam" {
+ crypto_key_id = "projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1"
+ etag          = (known after apply)
+ id            = (known after apply)
+ member        = "serviceAccount:service-1234567890@gs-project-accounts.iam.gserviceaccount.com"
+ role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
}
Plan: 1 to add, 0 to change, 0 to destroy.
--- FAIL: TestAccComposerEnvironment_withEncryptionConfigComposer2 (1684.74s)
FAIL
```

**Comment by melinath** [comment]
I'm marking this as resolved - it looks like we're no longer seeing these errors at this frequency. `TestAccComposerEnvironment_basic` had a similar error once in September, `TestAccComposerEnvironment_withEncryptionConfigComposer1` had one in October, and `TestAccComposerEnvironment_update` had one in November.
