### ISSUE TITLE
Failing test(s): TestAccMemcacheInstance_update

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10599]
### Affected Resource(s)

* google_memcache_instance

Failure rate:
- 10% in October 2021

Impacted tests:
- TestAccMemcacheInstance_update

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/220058?buildTab=tests&expandedTest=9212193369445625188

Message:

```
provider_test.go:278: Step 3/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
# google_compute_global_address.service_range will be created
+ resource "google_compute_global_address" "service_range" {
+ address            = (known after apply)
+ address_type       = "INTERNAL"
+ creation_timestamp = (known after apply)
+ id                 = (known after apply)
+ label_fingerprint  = (known after apply)
+ name               = "tf-test5051118588212832189"
+ network            = "projects/project-id/global/networks/tf-bootstrap-net-memcache-update"
+ prefix_length      = 16
+ project            = (known after apply)
+ purpose            = "VPC_PEERING"
+ self_link          = (known after apply)
}
Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by rileykarson** [comment]
Note: Some other tests fail in the same way, failing to see a GCE global address

**Comment by sanghaniJ** [comment]
b/261698611

**Comment by roaks3** [comment]
This test had a 100% failure rate of `Error code 13, message: an internal error has occurred` until Feb 5, 2023 when they resolved. Since then we haven't seen any errors, so there's a good chance this one is resolved.

**Comment by roaks3** [comment]
Confirmed this issue has continued to pass successfully, so considering it resolved.
