### ISSUE TITLE
enable_endpoint_independent_mapping option in compute_router_nat should probably be disabled by default

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#10609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_router_nat

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.

resource "google_compute_router_nat" "default" {
  enable_endpoint_independent_mapping = null
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Per Google documentation, setting is _disabled_ by default when creating a new Cloud NAT.  

### Actual Behavior

Setting is _enabled_ by default, per Terraform documentation.

### Steps to Reproduce

1. Create Cloud NAT with `enable_endpoint_independent_mapping = null`
2. Cloud NAT will have Endpoint-Independent Mapping enabled

### Important Factoids

I haven't been able to find a real-world scenario where enabling this setting would be recommended.  It causes problems especially when outbound HTTP or SMTP proxies are operating behind Cloud NAT

### References

* #[Applicable RFCs](https://cloud.google.com/nat/docs/overview#specs-rfcs)
* [Simultaneous port reuse and Endpoint-Independent Mapping](https://cloud.google.com/nat/docs/ports-and-addresses#ports-reuse-endpoints)
* [Endpoint-Independent Mapping conflict](https://cloud.google.com/nat/docs/ports-and-addresses#example-conflict-eim)

**Comment by ndmckinley** [comment]
It's an easy change - and I agree with you - but I need to check whether this would officially be a breaking change or not.  I think changing a default does count as a breaking change, and therefore can only be made at a major version - which means a long wait.

**Comment by ndmckinley** [comment]
Yep - that was correct.  We'll hold off on this until the next major version.

Thanks for the report, sorry that there will be a long delay.

**Comment by jeheyer** [comment]
Is that next major version of Terraform, or the Provider? 

Doesn't matter for me personally at this point as I've already updated my internal module.  I'm just letting you know because it did cause problems for us and could cause problems for others.

**Comment by ndmckinley** [comment]
The next major version of the provider, yes.  I've added the Breaking Change label and we'll know to make this change at that time.

**Comment by c2thorn** [comment]
Closing in favor of https://github.com/hashicorp/terraform-provider-google/issues/10547
