### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_withAutoscalingPolicy (DISKS_TOTAL_GB quota)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10600]
### Affected Resource(s)

* google_dataproc_cluster
* google_dataproc_autoscaling_policy

Failure rate:
- 22% in Nov 2021
- previously 0% due to this failure

Impacted tests:
- TestAccDataprocCluster_withAutoscalingPolicy
- TestAccDataprocCluster_withKerberos

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/220058?buildTab=tests&expandedTest=-2215167958386659364

Message:

```
Error: Error creating Dataproc cluster: googleapi: Error 400: Insufficient 'DISKS_TOTAL_GB' quota. Requested 3000.0, available 925.0., badRequest
```

**Comment by rileykarson** [comment]
Note: We should investigate the leaked resources here

**Comment by sanghaniJ** [comment]
- TestAccDataprocCluster_withAutoscalingPolicy 
[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-2215167958386659364&tab=testDetails) - 51.1% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=-2215167958386659364&tab=testDetails) - 69.7% failure

- TestAccDataprocCluster_withKerberos
[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=901654534608049958&tab=testDetails) - 34.1% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=901654534608049958&tab=testDetails) - 41.6% failure

**Comment by sanghaniJ** [comment]
b/261700247

**Comment by roaks3** [comment]
Something happened around Dec 2 that resolved this. However, a sweeper is still missing for this resource, so we will want to add one. I've created a separate ticket for that: https://github.com/hashicorp/terraform-provider-google/issues/13676.
