### ISSUE TITLE
Changing can_ip_forward forces VM instance replacement

### ISSUE THREAD

**Issue by ArsenyBelorukov** [hashicorp/terraform-provider-google#10612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.1.0
```

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.1.0"
    }
  }
}

provider "google" {
  project = var.project
  zone    = var.zone
}

resource "google_compute_instance" "instance1" {
  name         = "instance1"
  machine_type = "e2-micro"
  boot_disk {
    initialize_params {
    image = "debian-cloud/debian-10"
    }
  }
  network_interface {
    network = "default"
  }
  can_ip_forward = true
}
```

### Debug Output

https://gist.github.com/ArsenyBelorukov/95c5c3c3007c4bc2d75f7315c30bbf84

### Panic Output

N/A

### Expected Behavior

can_ip_forward will be changed without recreating VM

### Actual Behavior

changing can_ip_forward forces recreating VM

### Steps to Reproduce

1. Create instance with can_ip_forward = false (default)
2. Change can_ip_forward to true
3. `terraform apply`

### Important Factoids

N/A

### References

According to doc, `canIpForward` could be changed even without requiring the instance to restart.
https://cloud.google.com/compute/docs/instances/update-instance-properties#updatable-properties

Changing works via `gcloud`:
```
✗ gcloud compute instances export instance1 \
    --project $project \
    --zone us-central1-a \
    --destination=instance1_export
Exported [instance1] to 'instance1_export'.
✗ gsed -i'' 's/canIpForward: true/canIpForward: false/g' instance1_export
✗ gcloud compute instances update-from-file ipdbshw1 \
    --project $project \
    --zone us-central1-a \
    --source=instance1_export \
    --most-disruptive-allowed-action REFRESH
Updated [https://www.googleapis.com/compute/v1/projects/XXXX/zones/us-central1-a/instances/instance1].
```

**Comment by c2thorn** [comment]
It's likely `canIpForward` was not updatable during its initial implementation in the provider. Making a field updatable is generally treated as an enhancement, marking it as such.

**Comment by ndmckinley** [comment]
Ah, shoot, forgot to mark myself as working on this one, sorry about that Cameron, your comment reminded me that I ought to.

**Comment by rileykarson** [comment]
Note: I believe this is blocked on https://github.com/hashicorp/terraform-provider-google/issues/6857
