### ISSUE TITLE
Don't require oauth client secret for turning on IAP for backend service 

### ISSUE THREAD

**Issue by DawPawel** [hashicorp/terraform-provider-google#10614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In Google Cloud console there is an option to "just" turn on/off IAP for specific backend service. What it means - it doesn't require passing any oauth2_client_{id, secret} configuration in opposite to terraform resource **google_compute_backend_service**. So this step, when done through console, doesn't require any secret manipulation (thus doesn't give opportunity to expose those secrets).

When we turn on IAP for \<backend-service\> for the first time, it will automatically:
1. Create required OAuth 2.0 Client ID (with name IAP-\<backend-service\>)
2. Configure it's Authorized redirect URIs
3. Make our backend service use that oauth2_client_id

So it's not only **safer** but it requires **less configuration**.

Currently i have create IAP client config through console (i didn't find any option to specify required Authorized redirect URIs through terraform resource - **google_iap_client** - but maybe i've missed something?).

So to enable IAP for some specific backend service, instead of just specifying boolean, i have to:
1. Create IAP client config through console
2. Extract its id and use terraform datasource **google_iap_client** for further usage in terraform.
3. Pass IAP configuration (including **secret**!) to **google_compute_backend_service**

Which isn't a very automatic solution. 
One thing is to live with such manual process, but another thing is that I can't live with unnecessary possibility for exposing secrets. I don't need them for anything - everything should be handled internally by Google (and it's how it's done in Google console). 
Even though most of the people have to keep secrets in terraform state anyway, we should still always aim to limit number of places where we store that secrets. I believe it should be handled in terraform the same way it's handled through google console, or at least shouldn't require storying **oauth2_client_secret** in terraform state. 

### New or Affected Resource(s)

* google_compute_backend_service
* google_iap_client

### Potential Terraform Configuration

Instead of passing (in **google_compute_backend_service**)

```
  iap {
    oauth2_client_id = <id>
    oauth2_client_secret = <secret>
  }
```

Have option to either configure just client_id

```
  iap {
    oauth2_client_id = <id>
  }
```

or 

```
  iap {
    enabled = true/false
  }
```

**Comment by slevenick** [comment]
Is this possible through the existing APIs? On the Terraform side we can only interact with the APIs that exist, so if this is a feature request for the API in general we can't do much. If the APIs do exist though, we could potentially handle this

**Comment by slevenick** [comment]
I believe this are API-side constraints requiring the client secret to enable IAP for this resource. If you can do this through another tool or through the API directly without specifying the secret then we can reopen and examine this issue
