### ISSUE TITLE
Functions Memory Limit

### ISSUE THREAD

**Issue by TGTGamer** [hashicorp/terraform-provider-google#10611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Regression of #7654 - GCF now supports 8192MB. 

### New or Affected Resource(s)

google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  name    = var.name
  runtime = "nodejs14"

  available_memory_mb   = 8192
}
```

### References

[* Google Cloud Quotas](https://cloud.google.com/functions/quotas)
[* #7654](https://github.com/hashicorp/terraform-provider-google/issues/7654)

**Comment by rileykarson** [comment]
Note: We can just stop validating this field, it keeps changing on us (or consider validating for any power of 2)

**Comment by upodroid** [comment]
We can close this. You removed validation back in April.


https://github.com/GoogleCloudPlatform/magic-modules/pull/4702
