### ISSUE TITLE
google_apigee_environment support for `ARCHIVE` deployment type

### ISSUE THREAD

**Issue by emarcotte** [hashicorp/terraform-provider-google#10635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add the ability to create `google_apigee_environment` resources with [`ARCHIVE` deployment type](https://cloud.google.com/apigee/docs/api-platform/deploy/manage-archive-deployments#apigee-api).

In order to be able to provision an environment that can then be deployed to via gcloud command line the deployment type attribute needs to be set.

I actually dont understand if `preview` resources should show up in beta provider. If not sorry for the noise :(

### New or Affected Resource(s)

* `google_apigee_environment`

### Potential Terraform Configuration

```tf

resource "google_apigee_environment" "env" {
  name           = "my-env"
  description    = "Apigee Environment"
  displayName    = "environment-1"
  org_id         = google_apigee_organization.apigee_org.id
  deploymentType = "ARCHIVE" 
}
```

### References

* https://cloud.google.com/apigee/docs/api-platform/deploy/manage-archive-deployments#apigee-api

**Comment by xuchenma** [comment]
This feature is included in https://github.com/hashicorp/terraform-provider-google/issues/11379 and is live now: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment
