### ISSUE TITLE
GKE NodePool Pod Secondary Address Config

### ISSUE THREAD

**Issue by xyphanajay** [hashicorp/terraform-provider-google#10645]
### Terraform Version
Terraform v1.0.11

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "node_pool_1" {
name = "${var.pool_name_1}"
location = var.cluster_location
node_locations = [
    var.pool_zone,
    ]
cluster = "app-${var.cluster_name}"
# node_count = 1
max_pods_per_node = 10

autoscaling {
    min_node_count = 1
    max_node_count = 300
}
## 1
network = "projects/shared-project-1/global/networks/shared-network-1"
subnetwork = "projects/shared-project-1/regions/${var.region}/subnetworks/k8s-subnet"
network_config {
    create_pod_range = true
    pod_range = "pods2"
}
## 
node_config {
    ## Preemptive Node Pool
    preemptible = true
    machine_type = var.machine_pv_e1

    metadata = {
        disable-legacy-endpoints = "true",
        owner = "abc",
        project = "app1",
        team = "spirit"
    }

    labels = {
        app = "prod-${var.app1}",
        pool = "n2",
        pool_type = "pv",
        zone = "d",
        env = "prod"
    }
    service_account = "app-sa@project101.iam.gserviceaccount.com"
    oauth_scopes = [
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_write"]

    tags = [var.node_tag]
}
}
```

### Debug Output
For ## 1 
│ Error: Unsupported argument
│ 
│   on app_pool_pv_e2.tf line 16, in resource "google_container_node_pool" "app_pool_pv_e2":
│   16:     network = "projects/shared-project-1/global/networks/shared-network-1"
│ 
│ An argument named "network" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on app_pool_pv_e2.tf line 17, in resource "google_container_node_pool" "app_pool_pv_e2":
│   17:     subnetwork = "projects/shared-project-1/regions/${var.region}/subnetworks/k8s-subnet"
│ 
│ An argument named "subnetwork" is not expected here.
╵
╷
│ Error: Unsupported block type
│ 
│   on app_pool_pv_e2.tf line 18, in resource "google_container_node_pool" "app_pool_pv_e2":
│   18:     network_config {
│ 
│ Blocks of type "network_config" are not expected here.

### Expected Behavior

Configure network settings for the node pool. 
[Terraform Google Provider Official Document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#network_config)

Trying to configure NodePool Pod Address Range during node pool creation via terraform.
![GKE Node Creation Console UI](https://i.stack.imgur.com/lThuy.jpg)
![GKE Node Creation Console UI](https://i.stack.imgur.com/lThuy.jpg)
[GKE API Official Documentation](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters.nodePools#nodenetworkconfig)

### Actual 

Unsupported flag under node pool resource.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

**Comment by sdif** [comment]
Hey, are you using last provider version and using the `google-beta` one ?

**Comment by ChrisRussell92** [comment]
Experiencing the same problem. Only difference is I'm trying to assign a pre-existing secondary range, rather than create a new one.

> network_config {
>     create_pod_range = false
>     pod_range = "pods-range"
> }

> │ Error: Unsupported block type
> │ 
> │   on gke.tf line 160, in resource "google_container_node_pool" "primary_node_pool":
> │  160:   network_config {
> │ 
> │ Blocks of type "network_config" are not expected here.

Version:
Terraform v1.1.0
Terragrunt v0.31.0
google: 4.20.0
google-beta: 4.20.0

Also tried with a number google/google-beta versions from 3.70.0 to 4.20.0

**Comment by smitha-ap** [comment]
Hi, I am facing the same issue with both google and google_beta providers used. Was there any resolution for the issue?.

**Comment by c2thorn** [comment]
Hey folks, sorry you've run into this issue. For clarity:
`network` and `subnetwork` fields are not supported at all in the providers
`network_config` is only in the google-beta provider.

Given that, if you are running into `Blocks of type "network_config" are not expected here.` using an updated google-beta provider, please post a sanitized debug log as I am unable to reproduce myself.

**Comment by edward-lui-exa** [comment]
I changed the provider and it works for me now.
