### ISSUE TITLE
Add support for Handwritten Resource in C.G.C snippet generation

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#10651]
PR that pointed out the need for this: https://github.com/GoogleCloudPlatform/magic-modules/pull/5463

We need a way to include handwritten resources in the C.G.C example process. This includes:

- testing the example
- including it in documentation
- exporting it to https://github.com/terraform-google-modules/terraform-docs-samples

**Comment by betsy-lichtenberg** [comment]
This issue is a blocker for us moving forward with basic samples on CGC. Do you have an ETA to resolve this?

**Comment by c2thorn** [comment]
Hi @betsy-lichtenberg,

I hope to have something ready for you early next week.

**Comment by c2thorn** [comment]
Proposed workaround:

We create a fake product in MMv1 here: https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/products
and have a fake/empty resource that isn't used except for having a terraform.yaml file to hold *all* Handwritten example blocks used for cgc.

This would mean:
- cgc snippet still gets created
- automated tests get created
- terraform.io documentation does not get automatically updated

For terraform.io documentation to get updated, the submitter will have to manually update the handwritten documentation file like this one: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/website/docs/r/sql_database_instance.html.markdown

This is a bit more complicated to do, but we could leave it as an optional step.

**Comment by betsy-lichtenberg** [comment]
Thanks for the workaround!
