### ISSUE TITLE
Managing multi google_dns_record_set resources with same dns_name doesn't pop an error

### ISSUE THREAD

**Issue by valtos** [hashicorp/terraform-provider-google#10661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.11

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
data "google_compute_network" "shared-vpc" {
  name    = var.vpc_name
  project = var.host_project_id
}

resource "google_dns_managed_zone" "test-internal_zone" {
  project     = var.host_project_id
  name        = "test-internal"
  dns_name    = "test.internal."

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = data.google_compute_network.shared-vpc.self_link
    }
  }

}

resource "google_dns_record_set" "rr1" {
  name = "rr1.${google_dns_managed_zone.test-internal_zone.dns_name}"
  managed_zone = google_dns_managed_zone.test-internal_zone.name
  type = "A"
  ttl  = 300
  rrdatas = ["1.2.3.4"]
}

resource "google_dns_record_set" "rr2" {
  name = "rr1.${google_dns_managed_zone.test-internal_zone.dns_name}"
  managed_zone = google_dns_managed_zone.test-internal_zone.name
  type = "A"
  ttl  = 300
  rrdatas = ["1.2.3.5"]
}
```

### Debug Output

I can't share the debug output because of confidential informations, it's a simple configuration easy to reproduce.

### Expected Behavior

An error should say the resource already exists when creating another records with same dns_name.

### Actual Behavior

If you create both records with same dns_name in same time, it create the first record then pop an error saying the dns_name already exists => This is normal behavior.

But if you create first record (with terraform apply) then second record (with another apply), the first record is just erased and replaced by second one ! without any error saying it already exists !

### Steps to Reproduce

1. `Comment resource record block "google_dns_record_set" "rr2" `
2.  `terraform apply`
3. `Unomment resource record block "google_dns_record_set" "rr2" `
4. `terraform apply`

b/319824590

**Comment by mabushey** [comment]
If you put both A records in the same rrdatas (rrdatas = [ "1.2.3.4", "1.2.3.5" ]) and apply, it will show ...`Creating...` for both IPs. Both IP's will be added to the A record in GCP. Terraform will show one of the IPs as `Creation complete after 1s`. The other IPs will error with `│ Error: Error creating ResourceDnsRecordSet: googleapi: Error 409: The resource 'entity.rrset' named 'xxx.com. (A)' already exists, alreadyExists`. It creates the records, but the state is all mangled.

**Comment by slevenick** [comment]
Closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/11622 by adding a mutex.
