### ISSUE TITLE
Pub/sub push_config attributes seems ignored

### ISSUE THREAD

**Issue by bakuljajan** [hashicorp/terraform-provider-google#10669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v4.1.0

### Affected Resource(s)

* google_pubsub_subscription

### Terraform Configuration Files

```tf
resource "google_pubsub_subscription" "example" {
  name  = "example-subscription"
  topic = "abc"

  ack_deadline_seconds = 20

  labels = {
    foo = "bar"
  }

  push_config {
    push_endpoint = "https://example.com/push"

    attributes = {
      x-goog-version = "v1beta1"
    }
  }
}
```

### Debug Output

https://gist.github.com/bakuljajan/c85c771de02e086caa20c59424178a40

### Expected Behavior

push_config should contain attributes as configured in terraform code.

### Actual Behavior

No attributes are configured even when using examples in the docs.

### Steps to Reproduce

1. `terraform apply`

b/301066090

**Comment by kamalaboulhosn** [comment]
`v1beta1` was replaced by `v1beta2` (which became `v1`) over 8 years ago (before Pub/Sub went GA). is there a reason to still rely on this extremely old version? Without setting `attributes`, it will use the `v1` version.

**Comment by bakuljajan** [comment]
> ```terraform
> google_pubsub_subscription
> ```

Because of the example I think. Honestly, it's been a long time, and I don't remember much.

**Comment by kamalaboulhosn** [comment]
To which example are you referring? I'd like to remove it from there.

**Comment by bakuljajan** [comment]
> To which example are you referring? I'd like to remove it from there.

I think it's already updated. Also since `x-goog-version = "v1"` is the default as you said earlier, I think the issue is not important anymore.
