### ISSUE TITLE
CMEK for Secret Manager depends on replication, but it shouldn't 

### ISSUE THREAD

**Issue by vsoloviov** [hashicorp/terraform-provider-google#10679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.1.0
+ provider registry.terraform.io/hashicorp/google-beta v4.1.0

```

### Affected Resource(s)

* google_secret_manager_secret

### Expected Behavior
In UI `replication` and `customer_managed_encryption` are independent options, you can leave replication to be global and choose global KMS key.

```tf
resource "google_secret_manager_secret" "secret" {
   ...
   replication {
       user_managed {
           location = vars.location
      }
   }
   customer_managed_encryption {
      kms_key_name = vars.kms_key_name
    }
}
```
or 
```tf
resource "google_secret_manager_secret" "secret" {
   ...
   replication {
       automatic = true
   }
   customer_managed_encryption {
      kms_key_name = vars.kms_key_name
    }
}
```

### Actual Behavior

Currently `customer_managed_encryption` works only inside `replication -> user_managed` block 
```tf
resource "google_secret_manager_secret" "secret" {
   ...
   replication {
       user_managed {
           location = vars.location
           customer_managed_encryption {
               kms_key_name = vars.kms_key_name
           }
      }
  }
}
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
The Terraform schema matches the API as far as I can tell- what is there to correct?

**Comment by rileykarson** [comment]
Ah, never mind- got it now. The CMEK field appears twice, so the following config you shared would work:

```
resource "google_secret_manager_secret" "secret" {
   ...
   replication {
       user_managed {
           location = vars.location
      }
   }
   customer_managed_encryption {
      kms_key_name = vars.kms_key_name
    }
}
```

**Comment by vsoloviov** [comment]
> Ah, never mind- got it now. The CMEK field appears twice, so the following config would work:
> 
> ```
> resource "google_secret_manager_secret" "secret" {
>    ...
>    replication {
>        automatic = true
>        automatic_customer_managed_encryption {
>          kms_key_name = vars.kms_key_name
>        }
>    }
> }
> ```

Right, it _should_ work, but 
```hcl
╷
│ Error: Unsupported block type
│ 
│   on ../../../../../../../../modules/secrets-manager/main.tf line 50, in resource "google_secret_manager_secret" "secret":
│   50:     customer_managed_encryption {
│ 
│ Blocks of type "customer_managed_encryption" are not expected here.
╵

```

so, currently `customer_managed_encryption` block may be added only under `user_managed` block which is not correct behavior b/c encryption and replication are independent features.

**Comment by kutysam** [comment]
+1 This is a bug. It is not supporting global field for location.
