### ISSUE TITLE
Error installing provider "google"

### ISSUE THREAD

**Issue by will-gant** [hashicorp/terraform-provider-google#10671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.12.31

### Affected Resource(s)

```
provider "google" {
  credentials = <REDACTED>
}
```

### Debug Output

https://gist.github.com/will-gant/5ac91bc8177e16d8a902e99161a506d2

### Expected Behavior

Something like this:

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 4.2.0...

...
* provider.google: version = "~> 4.2"

Terraform has been successfully initialized!
```
### Actual Behavior

`Error installing provider "google": failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported.`

### Steps to Reproduce

1. `terraform init`

### Important Factoids

I believe this is the first time we've tried to run `terraform init` against v4.2.0 of the provider, which was [released](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.2.0) two hours before I wrote this issue.

**Comment by will-gant** [comment]
Solved by upgrading `terraform` to v0.14.11.

This caused a new error:

```
Error: Could not load plugin

...

Failed to instantiate provider "registry.terraform.io/-/google" to obtain
schema: unknown provider "registry.terraform.io/-/google"
```

That one I solved by running `terraform state replace-provider 'registry.terraform.io/-/google' 'registry.terraform.io/hashicorp/google'` and then manually uploading the updated state file to my backend.

**Comment by PatrickDale** [comment]
@will-gant Can you re-open this issue? We experienced the same error today on terraform version `0.12.31`.

**Comment by will-gant** [comment]
@PatrickDale Done

**Comment by gnubibi33** [comment]
Same issue with tf 0.12.31

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 4.2.0...

Error installing provider "google": failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


Error: failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported
```

**Comment by ahmedbilal** [comment]
All previous releases are released by developers, but this one (4.2.0) is released by `github-action` i.e using automation. So, most probably automation messes something up.

**Comment by OliverUrsell** [comment]
> 

We're getting the exact same issue.

**Comment by andygreenoughLBG** [comment]
Also getting the issue with tf 0.12.31

**Comment by macieys** [comment]
Same problem here. Terraform 12.31, provider 4.2.0.
Provider 4.1.0 is working fine.

**Comment by yousafsyed-bg** [comment]
Seeing the same error terraform 0.12.31

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 4.2.0...

Error installing provider "google": failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

- Downloading plugin for provider "google-beta" (hashicorp/google-beta) 4.2.0...

Error installing provider "google-beta": failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


Error: failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported



Error: failed to find installed plugin version 4.2.0; this is a bug in Terraform and should be reported
```

**Comment by satrox28** [comment]
Google Provider 4.2.0 requires Terraform 0.13+.

**Comment by macieys** [comment]
> Google Provider 4.2.0 requires Terraform 0.13+.

Could you tell me where this is documented? README still shows Terraform 12+, and changelog does not mention about this

**Comment by satrox28** [comment]
You can check here under Use Provider.


How to use this provider

To install this provider, copy and paste this code into your Terraform configuration. Then, run terraform init.

Terraform 0.13+

terraform { required_providers { google = { source = "hashicorp/google" version = "4.2.0" } } } provider "google" { # Configuration options }


https://registry.terraform.io/providers/hashicorp/google/latest/docs

**Comment by macieys** [comment]
> You can check here under Use Provider section. https://registry.terraform.io/providers/hashicorp/google/latest/docs
> 
> How to use this provider
> 
> To install this provider, copy and paste this code into your Terraform configuration. Then, run terraform init.
> 
> **Terraform 0.13+**
> 
> terraform { required_providers { google = { source = "hashicorp/google" version = "4.2.0" } } } provider "google" { # Configuration options }

Thanks, I know how to use the provider and I've seen this in the dropdown ;)
If that's really the case then I would expect backwards compatibility to be announced in changelog rather then be hidden in UI.

**Comment by rileykarson** [comment]
We weren't aware of new Core version requirements as part of this release, as far as I'm aware- as https://github.com/hashicorp/terraform-provider-google/issues/10671#issuecomment-985271479 points out we used a new release process for the build (which was also why the release went out later in the week rather than Monday) and we believed the change in release tooling would have no effect on end users.

I don't have access to the release systems/registry to dig into this myself but I'll get the right folks looking at this!

**Comment by rxp1997** [comment]
> You can check here under Use Provider section. https://registry.terraform.io/providers/hashicorp/google/latest/docs
> 
> How to use this provider
> 
> To install this provider, copy and paste this code into your Terraform configuration. Then, run terraform init.
> 
> **Terraform 0.13+**
> 
> terraform { required_providers { google = { source = "hashicorp/google" version = "4.2.0" } } } provider "google" { # Configuration options }

Actually all providers will say that you need Terraform 13+, so as a "head-up" notification its lousy

Terraform 0.13+
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "1.0.0"
    }
  }
}

provider "google" {
  # Configuration options
}

**Comment by c2thorn** [comment]
Hi folks,

We've pushed out `v4.2.1` of the `google` and `google-beta` providers using our previous release process. These releases should be the same as `v4.2.0` but without the Terraform 0.13+ requirement. Please try them out.

**Comment by PatrickDale** [comment]
Thanks @c2thorn! `v4.2.1` works for me on Terraform 0.12.31!
