### ISSUE TITLE
Add implicit dependencies to Secret Manager resources to prevent race conditions

### ISSUE THREAD

**Issue by ace-n** [hashicorp/terraform-provider-google#10682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.7
on darwin_amd64
```
### Affected Resource(s)

* google_secret_manager_secret_iam_member

### Terraform Configuration Files
Here's a snippet from my Terraform config file. Note that _this_ resource is **not** explicitly dependent on any APIs and/or `google_secret_manager_secret` resources.
```tf
resource "google_secret_manager_secret_iam_member" "my_secret_iam" {
  project    = data.google_project.ops_project.project_id
  secret_id  = "oauth-client-secret"
  role       = "roles/secretmanager.secretAccessor"
  member     = "serviceAccount:cloud-run-manager@${data.google_project.stage_project.project_id}.iam.gserviceaccount.com"
  depends_on = [google_service_account.stage_cloud_run_manager]
}
```

### Debug Output

https://gist.github.com/ace-n/650c38c7af49709a252af4eaad845d20

### Expected Behavior

- `google_secret_manager_secret_iam_member` should have an implicit dependency on the associated `google_secret_manager_secret`
- `google_secret_manager_secret` should likewise depend on the appropriate `google_project_service` resource that enables the Secret Manager API

### Actual Behavior

Neither of these dependencies exist implicitly, which causes race conditions. These result in various mixtures of "resource not found" and/or "API not enabled" errors, both of which can be fixed by _explicitly_ specifying the dependencies mentioned above.

### Suggested Fix

If Terraform supports it, we should specify "implicit" dependencies as stated in the **Expected Behavior** section above.

**Comment by shuyama1** [comment]
Hi @ace-n! Thanks for filing the issue! Unfortunately, this is a feature that we are not able to add in the provider, since the only way to add a dependency in Terraform is to do it explicitly w/ `depends_on` or an interpolation. Therefore I will close this issue.

**Comment by ace-n** [comment]
Is there some alternative approach to resolve race conditions?

Two other solutions that might be better-supported:
1) `google_secret_manager_secret` creation should be delayed (under the hood) long enough that the API has time to be enabled
2) If Terraform has an internal prioritization system (IDK if it does), could we mark APIs as "P0 resources" and `google_secret_manager_secret` objects as "P1 resources"?

Barring that, maybe we should add a note about explicitly specifying this dependency [to the documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret)?

**Comment by shuyama1** [comment]
> 1) `google_secret_manager_secret` creation should be delayed (under the hood) long enough that the API has time to be enabled

API only needs to be enabled the first time it is being used in a project based on my understanding, so I do not believe delay the `google_secret_manager_secret` creation in all cases would be the best solution here (also I may need to confirm if we are even able to support such behavior).

> 2) If Terraform has an internal prioritization system (IDK if it does), could we mark APIs as "P0 resources" and `google_secret_manager_secret objects` as "P1 resources"?

Terraform does not have an internal prioritization system or support such behavior AFAIK.

**Comment by ace-n** [comment]
> API only needs to be enabled the first time it is being used in a project based on my understanding

This is fair, but that does **not** prevent race conditions from occurring on project setup - right?

As I mentioned above - if there's no clean _technical_ solution to this, I think we should at least document it.

**Comment by shuyama1** [comment]
Yeah, adding a dependency explicitly with `depends_on` seems to be the most feasible solution in this case. 
Also, thanks for the suggestion of clean documentation! I'll discuss with the team about it, as it may sound like a documentation we want to add in a general case.

**Comment by ace-n** [comment]
Following up on this - @shuyama1 is that linked PR good to go?

(Happy to LGTM it, if you'd like me to.)

**Comment by ace-n** [comment]
@shuyama1 wording LGTM, PR merged.

We've had some race condition issues with the **Artifact Registry API** (see b/217779689), but other than that we're good.
