### ISSUE TITLE
resource google_cloud_ids_endpoint

### ISSUE THREAD

**Issue by omelnyk1** [hashicorp/terraform-provider-google#10694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New resource

With new resource I'd like to create/remove/update cloud IDS endpoint. Link on service: https://cloud.google.com/intrusion-detection-system
* google_cloud_ids_endpoint

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

# Create new Cloud IDS endpoint: https://cloud.google.com/intrusion-detection-system/docs/configuring-ids#api

resource "google_cloud_ids_endpoint" "this" {
  name                = "foobar"
  network             = "main"
  zone                = "us-central1-a"
  severity            = "MEDIUM"
  description         = "This is an example how to configure Cloud IDS endpoint"
  enable_traffic_logs = "true"

  labels = {
    env    = "staging"
    tenant = "main"
  }
}

```
**Argument Reference**
- `name` - (Required) Name of the Cloud IDS endpoint.
- `network` - (Required) Name of the VPC network that is connected to the IDS endpoint. This can either contain the VPC network name itself (like "src-net") or the full URL to the network (like "projects/{project_id}/global/networks/src-net"). This field is required when creating the endpoint.
- `zone` - (Required) The zone of the endpoint.
- `severity` - (Required) The minimum alert severity level that is reported by the endpoint. Possible values are as follows:
  - INFORMATIONAL
  - LOW
  - MEDIUM
  - HIGH
  - CRITICAL

- `description` - (Optional) Description of the endpoint.
- `enable_traffic_logs` - (default: `false`) Whether to enable traffic logs on the endpoint. Enabling traffic logs can generate a large number of logs which can increase costs in Cloud Logging.
- `labels` - (Optional) List of label KEY=VALUE pairs to add.

**Attributes Reference**
- `self_link` - Name of the endpoint in the format projects/{project_id}/locations/{locationId}/endpoints/{endpointId}.
- `endpoint_forwarding_rule` - URL of the endpoint's network address to which traffic is to be sent by Packet Mirroring.
- `endpoint` - Internal IP address of the endpoint's network entry point.

### References
https://cloud.google.com/intrusion-detection-system/docs/configuring-ids#api

* #0000

**Comment by FalconerTC** [comment]
Would love to see this get made 🙏

**Comment by kwsorensen** [comment]
+1 on getting this made. Any status update?

**Comment by smbugua** [comment]
would love to help work on this too. trying out this tool but would love it on tf

**Comment by MarioIshac** [comment]
+1 on this, often IDS is required for compliance, and having it configurable via Terraform makes it reproducible.

**Comment by saburo9** [comment]
+1 me too!  IDS is required for compliance,

**Comment by melinath** [comment]
b/198475470

**Comment by melinath** [comment]
This was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6617

**Comment by smbugua** [comment]
Awesome
