### ISSUE TITLE
Error on attempt to modify dataset with authorized datasets, authorized routines or deleted accounts in access

### ISSUE THREAD

**Issue by Ziemowit-LH** [hashicorp/terraform-provider-google#10716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.3.0
+ provider registry.terraform.io/hashicorp/google-beta v4.3.0

### Affected Resource(s)

google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "dataset" {
  dataset_id                      = "dataset_name"
  labels = {
    env = "int"
  }
   project = "project_id"
}

```

### Debug Output
https://gist.github.com/Ziemowit-LH/21f136e9de728a10ef18160698b645ec

### Expected Behavior

Apply changes.

### Actual Behavior

Error and stop execution.

### Steps to Reproduce

1. `terraform apply` to create dataset
2. Add an authorized dataset via the console.
3. Change a property, like the contents of the label
4. `terraform apply`

### Important Factoids

Regular access via account impersonation, works everywhere else.

### References

* #10698
* #10555

b/301066184

**Comment by slevenick** [comment]
Hm, yeah it looks like authorized datasets get set to empty objects because the provider doesn't know how to interpret them to be able to send them back in the request. Not ideal

**Comment by MartinNowak** [comment]
Have a similar problem with deleted users.
They get shown as `deleted:user:email@example.com?uid=518307170512354568` under `iamMember`.
Terraform doesn't recognize those during refresh and thus tries to write an empty permissions when updating the resource.
The update subsequently fails.

> Error updating Dataset "projects/my-gcp-project/datasets/my-dataset": googleapi: Error 400: An access entry must have exactly one of userByEmail, groupByEmail, domain, specialGroup defined, view, routine, or dataset., invalid

**Comment by 600lyy** [comment]
This issue should have been resolved in v5 in which terraform can interpret users under iamMember
https://github.com/hashicorp/terraform-provider-google/issues/16288

**Comment by Ziemowit-LH** [comment]
It is late but I confirm it works fine with
```terraform version
Terraform v1.9.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v6.5.0```
