### ISSUE TITLE
Failing sweeper: OSConfigOs_policy_assignment

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10726]
### Affected Resource(s)

* google_os_config_os_policy_assignment

Failure rate: ???

Impacted sweepers:
- OSConfigOs_policy_assignment

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/229665?logFilter=debug

Message:

```
Sweeper Tests ran unsuccessfully:
20:06:12
    - OSConfigOs_policy_assignment: googleapi: Error 400: Request contains an invalid argument.
```

I originally noticed this when running a manual test against a PR.

**Comment by megan07** [comment]
This looks to be an issue with the DCL

**Comment by melinath** [comment]
This is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13338
