### ISSUE TITLE
Support for Api Gateway in Serverless NEG

### ISSUE THREAD

**Issue by cgrotz** [hashicorp/terraform-provider-google#10729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
At the moment Serverless NEGs can be configures with AppEngine, Cloud Functions and CloudRun. Api Gateway is also going to be supported in the future (https://cloud.google.com/api-gateway/docs/gateway-serverless-neg). The configuration approach for Api Gateway also seems to be more general compared to the current creation parameters.
 
It would be great if this could be added to the terraform resource for Serverless NEGs. Ideally reflecting the same more general approach that can be seen in gcloud sdk.

### New or Affected Resource(s)

* google_compute_region_network_endpoint_group

### Potential Terraform Configuration
```tf
resource "google_compute_region_network_endpoint_group" "example_neg" {
  name                  = "example-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"
  serverless  {
    deployment-platform = "apigateway.googleapis.com"
    deployment-resource = "12345"
    deployment-url-mask = "..."
    deployment-version = "...unused by api gw..."
  }
}
```

### References
* This issue is a duplicate for #10314

**Comment by ivoilic** [comment]
There is an open PR that implements this that requires further review/feedback:
https://github.com/GoogleCloudPlatform/magic-modules/pull/5434
Here are some duplicate requests for this feature: #10476 #10061 #9907

**Comment by roaks3** [comment]
Yep, that PR has been merged, and this is currently available in the beta provider. Thanks for linking the duplicates for us as well!
