### ISSUE TITLE
Cloud Media Edge

### ISSUE THREAD

**Issue by marktru** [hashicorp/terraform-provider-google#10722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Feature Name: Cloud Media Edge GA

[API documentation](https://cloud.google.com/media-edge/docs/reference/rest)

#### Missing features:

The EdgeCacheOrigin.retryConditions field is missing the FORBIDDEN enum value.
The EdgeCacheOrigin.timeout field is missing the readTimeout field.
The EdgeCacheService.disableHttp field is missing.
The EdgeCacheService.pathMatchers.routeRules.routeAction.cdnPolicy.cacheKeyPolicy is missing the includedCookieNames field.

#### Bug:

*The EdgeCacheService has a field sslPolicy that is not part of our API.

The comments and documentation is out of date:

* EdgeCacheOrigin:
** originAddress doc is inaccurate (we don't require brackets for IPv6, and the GCS canonicalization is not exactly true)
** maxAttempts: bad documentation 503 versus 502.
timeout:
*** max_attempts_timeout: bad default documentation
*** response_timeout: bad default & range documentation

* EdgeCacheService:
** routing:
*** hostRules
**** hosts: we don't allow ports. The documentation for * is inaccurate.
*** pathMatchers
**** routeRules:
***** route_action:
****** cdnPolicy:
******* defaultTtl: max allowed value is wrong
******* maxTtl: max allowed value is wrong

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

**Comment by justin-mp** [comment]
I believe the following pull requests have fixed this issue:
* #11333 
* #11277 
* #11258 
* #11222 

Can we close this issue?

**Comment by melinath** [comment]
Closing based on the above comment.
