### ISSUE TITLE
data.google_iap_client not working due to permission issue

### ISSUE THREAD

**Issue by phumberdroz** [hashicorp/terraform-provider-google#10731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/aiven/aiven v2.1.11
+ provider registry.terraform.io/deviavir/gsuite v0.1.62
+ provider registry.terraform.io/elastic/ec v0.1.1
+ provider registry.terraform.io/hashicorp/aws v3.52.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/google v4.3.0
+ provider registry.terraform.io/hashicorp/google-beta v4.3.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.5.2
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.2
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

Your version of Terraform is out of date! The latest version
is 1.1.0. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* data.google_iap_client

### Terraform Configuration Files

```tf
data "google_iap_client" "project_client" {
  brand     = google_iap_brand.project_brand.name
  client_id = local.iap_client_id_map[terraform.workspace]
}
```

### Expected Behavior

being able to use the data resource

### Actual Behavior

Error: Error when reading or editing IapClient "<snipped resource identifier>": googleapi: Error 403: The caller does not have permission

### Steps to Reproduce

1. oauth application in console
2. try receiving said application via data resource
3. `terraform plan`

### Important Factoids

i do believe this is not an issue with the terraform provider itself but with google cloud. I created a bug ticket here https://issuetracker.google.com/issues/210099288 I am opening this issue primarily here to provide visibility if someone runs into the same issue

**Comment by slevenick** [comment]
Are you using the same credentials to access the console as you are to run the terraform commands?

Terraform has several possible ways to authenticate, so is it possible that you are authenticated as a user that doesn't have access to this resource?

**Comment by phumberdroz** [comment]
I tried multiple credentials. (Service account with owner permission, and my own credentials)

The biggest tell for me is that it also is not working in the linked documentation api explorer.

**Comment by slevenick** [comment]
Ah, yeah then it's definitely not a Terraform-specific problem. I believe the ticket you opened in the issue tracker is the right place to address this. I'm going to close this as there isn't a provider based solution possible

**Comment by phumberdroz** [comment]
All good I just opened the issue here for transparency. 👍
