### ISSUE TITLE
Cloud Function deployment fails with "Failed to retrieve function source code"

### ISSUE THREAD

**Issue by yeweidaniel** [hashicorp/terraform-provider-google#10734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.14.8

### Affected Resource(s)

"terraform-google-modules/event-function/google//modules/repository-function"

* google_XXXXX

### Terraform Configuration Files

```tf
module "batch_cf" {
  source                = "terraform-google-modules/event-function/google//modules/repository-function"
  version               = "2.1.0"
  name                  = "batch-function"
  project_id            = module.project.project_id
  description           = "Cloud Function to initiate batch pipeline"
  timeout_s             = 540
  entry_point           = "launch_batch_pipeline"
  service_account_email = "${google_service_account.function_runner.account_id}@${module.project.project_id}.iam.gserviceaccount.com"

  source_repository_url = "https://source.developers.google.com/projects/<myproject>/repos/<myrepo>/fixed-aliases/v1.0.0"
  runtime               = "python37"

  region = "us-central1"

  event_trigger = {
    event_type                         = "google.storage.object.finalize"
    resource                           = "<mybucketname>"
    event_trigger_failure_policy_retry = true
  }

  environment_variables = {
    LOCATION                   = "us-central1"
    TEMPLATE_FILE_GCS_LOCATION = "gs://<path to file>.json"
  }
}
```

### Expected Behavior

Output a useful error message. We can not make any actions based on the existing error message.

Also retry usually fixes this problem.

### Actual Behavior

```
Step #2 - "Apply": Error: Error waiting for Creating CloudFunctions Function: Error code 7, message: Failed to retrieve function source code
Step #2 - "Apply": 
Step #2 - "Apply":   on .terraform/modules/flattening_cf_group_admin/modules/repository-function/main.tf line 17, in resource "google_cloudfunctions_function" "main":
Step #2 - "Apply":   17: resource "google_cloudfunctions_function" "main" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by slevenick** [comment]
Looks like this is an issue with the module that you are using, so that repos issue tracker is a better place to file this. The error message comes directly from the API, so we don't really have many options from within the provider to give a better one.

I'm going to close this as I don't think there is a problem in the provider here
