### ISSUE TITLE
google_data_loss_prevention_job_trigger timespan_config should not require start_time or end_time if enable_auto_population_of_timespan_config is set

### ISSUE THREAD

**Issue by atsui-bay1** [hashicorp/terraform-provider-google#10745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.3.0
```

### Affected Resource(s)

* google_data_loss_prevention_job_trigger

### Terraform Configuration Files

```tf
resource "google_data_loss_prevention_job_trigger" "trigger" {
  parent       = "projects/${var.project}"

  triggers {
    schedule {
      recurrence_period_duration = "2592000s"
    }
  }

  inspect_job {
    inspect_template_name = google_data_loss_prevention_inspect_template.basic.id
    storage_config {
      big_query_options {
        table_reference {
          project_id = var.project
          dataset_id = "dataset"
          table_id   = "table"
        }
      }

      timespan_config {
        timestamp_field {
          name = "timestamp"
        }
        enable_auto_population_of_timespan_config = true
      }
    }

    actions {
      save_findings {
        output_config {
          table {
            project_id = var.project
            dataset_id = "output"
          }
        }
      }
    }
  }
}
```

### Expected Behavior

This is allowed due to `enable_auto_population_of_timespan_config = true`

### Actual Behavior

```
│ "inspect_job.0.storage_config.0.timespan_config.0.start_time": one of `inspect_job.0.storage_config.0.timespan_config.0.end_time,inspect_job.0.storage_config.0.timespan_config.0.start_time` must be specified
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The `end_time` field states that `If set to zero, no upper time limit is applied.`, however attempting `end_time = 0` results in the error:
```
{
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value at 'job_trigger.inspect_job.storage_config.timespan_config.end_time' (type.googleapis.com/google.protobuf.Timestamp), Field 'endTime', Illegal timestamp format; timestamps must end with 'Z' or have a valid timezone offset.",
│         "field": "job_trigger.inspect_job.storage_config.timespan_config.end_time"
│       }
│     ]
│   }

```

### References

* #0000

b/305278588

**Comment by davcen** [comment]
Also the `timespan_field`nested block should not be mandatory, because is needed only for bigquery or datastore storage kind (not for cloud storage bucket, for example).

I've just opened a new PR that fixes these non-optimal defaults
