### ISSUE TITLE
Data Source - vpc_access_connector

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#10756]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We have a requirement to reference VPC serverless connectors created in a central manner. 
Sadly there's no data source to reference them. This would be a handy feature. 

### New or Affected Resource(s)

* google_vpc_access_connector

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector

**Comment by melinath** [comment]
b/247006238

**Comment by rileykarson** [comment]
Dupes https://github.com/hashicorp/terraform-provider-google/issues/8827 (which was just closed)
