### ISSUE TITLE
google_compute_instance_template metadata marked as changed every time

### ISSUE THREAD

**Issue by sashokbg** [hashicorp/terraform-provider-google#10757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.0.11-1

### Affected Resource(s)

google_compute_instance_template

### Terraform Configuration Files
```tf
resource "google_compute_instance_template" "gitlab_runner_instance_template" {
  provider = google-beta
  
  lifecycle {
    create_before_destroy = true
  }

  name                 = "gitlab-runner-instance-template2"
  description          = "This template is used to create gitlan runner instances."
  project              = var.project
  region               = var.region
  instance_description = "description assigned to instances"
  machine_type         = var.gitlab_runner_instance_type
  can_ip_forward       = "false"
  enable_display       = "false"
  tags                 = ["allow-iap-ssh", "gitlab-runner-master"]

  scheduling {
    automatic_restart   = "true"
    min_node_cpus       = "0"
    on_host_maintenance = "MIGRATE"
    preemptible         = "false"
  }

  disk {
    auto_delete  = "true"
    boot         = "true"
    device_name  = "gitlab-runner-instance-template"
    disk_size_gb = var.gitlab_runner_instance_disk_size
    disk_type    = "pd-ssd"
    mode         = "READ_WRITE"
    source_image = var.gitlab_runner_instance_os
    type         = "PERSISTENT"
  }

  network_interface {
    access_config {
      network_tier = "PREMIUM"
    }
    network            = var.network
    subnetwork         = var.subnetwork
    subnetwork_project = var.project
  }

  service_account {
    email  = var.control_plane_service_account
    scopes = ["cloud-platform"]
  }

  confidential_instance_config {
    enable_confidential_compute = "false"
  }

  reservation_affinity {
    type = "ANY_RESERVATION"
  }

  shielded_instance_config {
    enable_integrity_monitoring = "false"
    enable_secure_boot          = "false"
    enable_vtpm                 = "false"
  }

  metadata = {
    startup-script                 = templatefile("${path.module}/files/gitlab_runner_startup_script.sh", {
      config_toml               = templatefile("${path.module}/files/config-template.toml.tpl", {
        name_prefix     = "gitlab-runner"
        network_tags    = "gitlab-runner-nodes"
        subnet          = var.subnetwork
        network         = var.network
        zone            = var.zone
        project         = var.project
        service_account = var.runner_service_account
      })
      certificate               = var.gitlab_self_signed_certificate
      gitlab_url                = var.gitlab_url
      gitlab_registration_token = var.gitlab_registration_token
    })
    enable-oslogin                 = "TRUE"
  }
}
```

### Debug Output
https://gist.github.com/sashokbg/a767a8149dcc290fdeccd4258a6f1204

![image](https://user-images.githubusercontent.com/10643824/146211978-d0e017df-7ceb-4d09-af32-8f162ba38981.png)

### Expected Behavior

Do not replace the instance template since the metadata did not change

### Actual Behavior

Instance template is marked as "to be replaced" due to metadata being falsely detected as changed.

**Comment by slevenick** [comment]
Are you able to reproduce this with a startup script that you can share? I'm unable to reproduce it with a simple startup script, and I imagine there could be something in that complex templated output that could be changing.

**Comment by sashokbg** [comment]
Problem somehow resolved itself.
I also tried reproducing in a separate test project with a metadata with nested templatefiles calls but still cannot reproduce.
Closing for now
