### ISSUE TITLE
Bigtable Auto-scaling support for google_bigtable_instance

### ISSUE THREAD

**Issue by ronanbarrett** [hashicorp/terraform-provider-google#10758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Bigtable autoscaling is GA since Q4 2021 it would be great to have terraform support. The documentation for the implementation is at https://cloud.google.com/bigtable/docs/autoscaling

### New or Affected Resource(s)

* google_bigtable_instance

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance

# References

* b/209613092

**Comment by shanemhansen** [comment]
Does this use mmv2/DCL? I messed around with adding data to mmv1 ( https://github.com/GoogleCloudPlatform/magic-modules/compare/master...shanemhansen:master )

But when I run:

bundle exec compiler -a -v "ga" -e terraform -o "$HOME/src/terraform-provider-google"

I don't see any updates in terraform-provider-google/google/resource_bigtable_*

Perhaps I'm using nested NestedObjects wrong?
