### ISSUE TITLE
configure  Event Arc Pub/Sub subscriptions with additional feature

### ISSUE THREAD

**Issue by vrutvi** [hashicorp/terraform-provider-google#10755]
I was looking for the terraform script  to configure  Event Arc Pub/Sub subscriptions of the cloud run  to have additional features like 
setting the dead letter topic(Dead lettering) ,setting Acknowledgement deadline, retry policy. 

Currently since terraform does not support this feature for time being we  are doing using the gcloud command is it possible to add this feature to terraform(currently terraform don't have this feature)?

gloud command to  for the above feature

<gcloud pubsub subscriptions update ${self.transport[0].pubsub[0].subscription} --ack-deadline 30 --min-retry-delay 60 --dead-letter-topic ${google_pubsub_topic.dead_letter.id}">

below is the terraform document link to create the event arc for cloud run with basic feature

[https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger]

**Comment by slevenick** [comment]
Terraform does support these features on PubSub subscriptions directly: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription

Is that what you are looking for?

**Comment by slevenick** [comment]
If you want to update the settings on the subscription managed by the EventArc resource itself you may need to request that feature from the API team themselves, or import the existing subscription into Terraform.

Currently the API does not support managing the PubSub subscription via the EventArc API

**Comment by vrutvi** [comment]
no I was looking for something  to update the settings on the subscription managed by the EventArc resource
