### ISSUE TITLE
Add numeric ID to google_compute_backend_service

### ISSUE THREAD

**Issue by mellowplace** [hashicorp/terraform-provider-google#10775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Allow access to the `google_compute_backend_service` numeric ID rather than just the name based one.

### New or Affected Resource(s)

* google_compute_backend_service

### Potential Terraform Configuration

```tf
google_compute_backend_service.numeric_id
```

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/backendServices

b/322602047

**Comment by shuyama1** [comment]
Hi @mellowplace, just want to confirm, is `id` on the [API doc](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) the field you request?

**Comment by mellowplace** [comment]
> Hi @mellowplace, just want to confirm, is `id` on the [API doc](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) the field you request for?

Yes it is

**Comment by shuyama1** [comment]
Thanks for the clarification!

**Comment by ScottSuarez** [comment]
Note for the service team. 

This should be pretty simple to do. We just need to add the following attribute.
```YAML
  - !ruby/object:Api::Type::String
    name: 'numeric_id'
    description: |
      The numeric id for this field. Equivalent to the API's id field.
    output: true
    api_name: 'id'
```
