### ISSUE TITLE
Cloudbuild trigger tied to a github repo, but invoked manually.

### ISSUE THREAD

**Issue by jgunnink** [hashicorp/terraform-provider-google#10779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Creating a cloudbuild trigger that is tied to a github repo, but invoked manually.

I am trying to build a cloudbuild trigger that is tied to a github repo, but is triggered manually. When code changes occur I do not want the build job to start, there’s a separate process that invokes the trigger and causes the build to start.

At the moment, the [github block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#nested_github) requires the user to:
```
Specify only one of pullRequest or push
```
In the console, it is possible to create a cloudbuild trigger that is tied to github and invoked manually. Observing the request and reading the [API Documentation](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers/create), it is possible to do this via the API also. Although, not via the gcloud CLI.

Calling POST at `https://cloudbuild.googleapis.com/v1/projects/{projectId}/triggers` with the sample payload:
```json
{
  "name": "test",
  "description": "a test trigger that is tied to github but invoked manually",
  "disabled": false,
  "sourceToBuild": {
    "uri": "https://github.com/owner/repo",
    "repoType": "GITHUB",
    "ref": "refs/heads/master"
  },
  "gitFileSource": {
    "uri": "https://github.com/owner/repo",
    "repoType": "GITHUB",
    "revision": "refs/heads/master",
    "path": "cloudbuild.yaml"
  }
}
```

Results in a 200, with the following response:
```json
{
  "id": "a5c98ecc-364f-4248-ab2b-4e9746f9c4c4",
  "createTime": "2021-12-20T23:59:27.657698307Z",
  "description": "a test trigger that is tied to github but invoked manually",
  "name": "test",
  "gitFileSource": {
    "path": "cloudbuild.yaml",
    "uri": "https://github.com/owner/repo",
    "repoType": "GITHUB",
    "revision": "refs/heads/master"
  },
  "sourceToBuild": {
    "uri": "https://github.com/owner/repo",
    "ref": "refs/heads/master",
    "repoType": "GITHUB"
  }
}
```

### New or Affected Resource(s)

resource_cloubuild_trigger.go

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "my-manual-trigger-github" {
  name        = "my-manual-trigger-github"
  description = "Run terraform plan on pull requests against master"

  github {
    owner   = var.repo_owner
    name    = var.repo_name
    trigger = "manual"
  }

  filename = "cloudbuild.yaml"
}

```

### References

* https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers/create
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger

**Comment by c2thorn** [comment]
It seems like this feature request boils down to to a request for `gitFileSource` and `sourceToBuild` fields.

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon
