### ISSUE TITLE
ERROR: Unsupported block type: Blocks of type "adaptive_protection_config" are not expected here

### ISSUE THREAD

**Issue by safag05** [hashicorp/terraform-provider-google#10776]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
tried with 0.14.4
Also with 1.1.2

### Affected Resource(s)
`google_compute_security_policy`
[Link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy)

### Terraform Configuration Files
https://github.com/safag05/gcp_security_policy

### Expected Behavior
It should create cloud armor with adaptive protection `enabled`

### Actual Behavior
When you run `terraform plan` it provides you an error: `Error: Unsupported block type: Blocks of type "adaptive_protection_config" are not expected here`. Does not create cloud armor due to `adaptive_protection_config` being not supported.

### Steps to Reproduce
1. Clone https://github.com/safag05/gcp_security_policy
2. Create a new GCP project or use an existing one. Create a service account and a key for it. Input the key to the `account.json` file
3. change the `project_id` environmental variable.
4. update `version.tf` file as necessary 
5. `terraform init`
6. `terraform plan -var-file dev.tfvars`

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? 
https://github.com/hashicorp/terraform-provider-google/issues/8984

**Comment by shuyama1** [comment]
Hi @safag05! Looks like `adaptive_protection_config` in a beta-only feature, could you try to specify it to use the beta provider by add `provider = google-beta` to `cloud_armor.tf` file and see if that works?

**Comment by safag05** [comment]
Hi @shuyama1 yes that worked! I thought having the `google-beta` provider on the under the `main.tf` file would have been enough but guess not. Thanks again!

**Comment by shuyama1** [comment]
Yeah, beta provider needs to be specified, otherwise GA provider will be used. Glad your problem solved!
