### ISSUE TITLE
google_bigquery_data_transfer_config missing documentation on data transfer of various source types, e.g. Dataset Copy

### ISSUE THREAD

**Issue by christopherchong94** [hashicorp/terraform-provider-google#10791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

For BigQuery data transfer, GCP UI/bq/API allows the definition of different sources, e.g. Dataset Copy, GCS...however on terraform documentation page ((https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config) there is no instruction on how to create terraform for data transfer, but there is only example on how to create scheduled queries.

Initially I thought this is because data transfer is not supported, but I managed to create terraform for Dataset Copy by using the bq flags specified here https://cloud.google.com/bigquery/docs/copying-datasets#setting_up_a_dataset_copy.

Below's a sample terraform code. It will be extremely helpful if the documentation page contains some examples of data transfer terraform.

```
resource "google_bigquery_data_transfer_config" "test-dataset-transfer" {
  display_name           = "test-dataset-transfer"
  location               = var.region
  data_source_id         = "cross_region_copy"
  schedule               = "every day 00:00"
  destination_dataset_id = "test003"
  project                = var.gcp_project
  params = {
    source_dataset_id = "test002"
    source_project_id = var.gcp_project
    overwrite_destination_table = true
  }
  service_account_name   = google_service_account.scheduled_query_svc_account.email
  schedule_options {
    start_time           = "2021-12-22T23:00:00Z"
  }
}
```

* #0000

**Comment by rileykarson** [comment]
@megan07: If this is missing fields / descriptions can you take a look as onduty? Otherwise if it's a request for examples we can likely let it sit or close it.
