### ISSUE TITLE
UREQ_SERVICE_REQUIRES_PROCUREMENT

### ISSUE THREAD

**Issue by tianmarin** [hashicorp/terraform-provider-google#10793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.0

### Affected Resource(s)

- [google_project_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service)

### Terraform Configuration Files

```tf
services = [
    "compute.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "cloudbilling.googleapis.com",
    "iam.googleapis.com",
    "stackdriver.googleapis.com",
    "logging.googleapis.com",
    "storage-api.googleapis.com",
    "serviceusage.googleapis.com",
    "cloudkms.googleapis.com",
    "cloudvolumesgcp-api.netapp.com",
  ]
resource "google_project_service" "services" {
  for_each           = toset(var.services)
  service            = each.key
  project            = google_project.project.project_id
  disable_on_destroy = false
}

```

### Panic Output

```
Error: Request `Enable Project Service "cloudvolumesgcp-api.netapp.com" for project "xxx-xxx-xxx"` returned error: failed to send enable services request: googleapi: Error 400: The service 'cloudvolumesgcp-api.netapp.com' in project '123456789012' can only be enabled after first procuring in the Marketplace. Please visit: http://console.cloud.google.com/apis/api/cloudvolumesgcp-api.netapp.com.
│ Help Token: Ae-hA1PrCKaXXXP3B9dfqZrDCWcdwO8usjE-mbcXezDHU_0V6Lk1nymaw2IRg9OxySBNYk_LWlCYZ1lr0bggOnHCS9eI9Y-lCOwRLuCZs_iox4ir
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "?error_code=390000\u0026service_name=cloudvolumesgcp-api.netapp.com\u0026project=123456789012",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "metadata": {
│       "project": "123456789012",
│       "service_name": "cloudvolumesgcp-api.netapp.com"
│     },
│     "reason": "UREQ_SERVICE_REQUIRES_PROCUREMENT"
│   }
│ ]
│ , failedPrecondition
│ 
```
### Expected Behavior

Activate the service

### Actual Behavior

Error when activating service

### Important Factoids

My configuration files are too big and dependent of modules, so i've trimmed a lot for focusing on the issue.
The message error: *The service 'cloudvolumesgcp-api.netapp.com' in project '123456789012' can only be enabled after first procuring in the Marketplace*.

However, how can this be achieved in an automated fashion? My main goal is to create projects and resources in a complete automated way.

The Netapp Cloud Volumes Service (`cloudvolumesgcp-api.netapp.com`) is available under `gcloud services list --available`

b/304725286

**Comment by roaks3** [comment]
Per the internal team, this is working as expected. There are a small number of Marketplace services that must be procured through Marketplace before they can be enabled.
