### ISSUE TITLE
Add Label argument for google_monitoring_dashboard

### ISSUE THREAD

**Issue by moektel** [hashicorp/terraform-provider-google#10796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Given the cloud operation's monitoring ability to apply [user labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels) to a dashboard via the console, it would be helpful to also include this functionality in the TF resource too.

The way it's done in [google_monitoring_alert_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy), for example, would be perfect.

### New or Affected Resource(s)

* [google_monitoring_dashboard](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_dashboard)

### Potential Terraform Configuration

```tf
# Using the basic example from the docs
resource "google_monitoring_dashboard" "dashboard" {
  dashboard_json = <<EOF
{
  "displayName": "Demo Dashboard",
  "gridLayout": {
    "widgets": [
      {
        "blank": {}
      }
    ]
  }
}

EOF

# proposed addition example 
user_labels = {
    foo = "bar"
  }
}
```

### References

* b/275113172

**Comment by melinath** [comment]
Label support was added directly to the dashboard JSON - if there's a use case for a separate Terraform field, please open a new ticket with details about the requested feature! :-)
