### ISSUE TITLE
Managed instance group won't perform update if group is in unhealthy state

### ISSUE THREAD

**Issue by danjamesmay** [hashicorp/terraform-provider-google#10792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

`google_compute_region_instance_group_manager`

### Terraform Configuration Files

```tf
resource "google_compute_region_instance_group_manager" "test" {
  name = "test"

  base_instance_name = "test"

  version {
    instance_template = google_compute_instance_template.test.id
  }

  target_pools = [google_compute_target_pool.test.id]

  auto_healing_policies {
    health_check      = google_compute_health_check.test.id
    initial_delay_sec = local.seconds_to_healthy
  }

  update_policy {
    type                         = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REPLACE"
    max_surge_fixed              = 5
    max_unavailable_fixed        = 0
    replacement_method           = "SUBSTITUTE"
  }

  wait_for_instances        = true
  wait_for_instances_status = "STABLE"
}
```

### Debug Output

```sh
Installing hashicorp/google v4.5.0...
Terraform has been successfully initialized!
google_compute_instance_template.test: Creating...
google_compute_instance_template.test: Still creating... [10s elapsed]
google_compute_instance_template.test: Creation complete after 12s [id=test]
google_compute_region_instance_group_manager.test: Modifying... [id=test]
...... 15 mins later
google_compute_region_instance_group_manager.test: Still modifying... [id=test, 14m50s elapsed]
╷
│ Error: timeout while waiting for state to become 'created' (last state: 'creating', timeout: 15m0s)
│ 
│   with google_compute_region_instance_group_manager.test,
│   on loadbalancer.tf line 47, in resource "google_compute_region_instance_group_manager" "test":
│   47: resource "google_compute_region_instance_group_manager" "test" {
│ 
╵
```

### Expected Behavior

Terraform initiates rolling update to new version of instance template (after creating new instance template), despite instance group health being unhealthy (timeout).

### Actual Behavior

Terraform `apply` times out. Instance group remains unhealthy, meaning I cannot perform an update that has a fix to make my instance group healthy again. I have to manually apply the update by pointing to the new instance template.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #10648 
* https://github.com/GoogleCloudPlatform/magic-modules/pull/5506
* https://github.com/GoogleCloudPlatform/magic-modules/pull/5057

**Comment by danjamesmay** [comment]
Hi - is there a way to determine what version of the provider caused this regression?

**Comment by rileykarson** [comment]
Closing as outdated- this was changed significantly a while ago, in https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.32.0
