### ISSUE TITLE
Improve documentation for localityLbPolicy in google_compute_region_backend_service and google_compute_backend_service resources

### ISSUE THREAD

**Issue by dgteixeira** [hashicorp/terraform-provider-google#10806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Improve documentation for localityLbPolicy in google_compute_region_backend_service and google_compute_backend_service resources based on these links below.
API Documentation here for regional backend: https://cloud.google.com/compute/docs/reference/rest/v1/regionBackendServices
API Documentation here for global backend: https://cloud.google.com/compute/docs/reference/rest/v1/backendServices

Tried with providers google and google-beta

### New or Affected Resource(s)

* google_compute_region_backend_service 
* google_compute_backend_service

### Terraform Configuration

```tf
resource "google_compute_backend_service" "external_lb_https" {
  provider                        = google-beta
  project                         = var.project_id
  name                            = "external-lb-https-backend"
  description                     = "This is the External Load Balancer backend where we target the EPGREPO MIG."
  protocol                        = "HTTP"
  load_balancing_scheme           = "EXTERNAL"
  port_name                       = "http"          # this is used for named_port backend service connection
  session_affinity                = "NONE"          # Type of session affinity to use.
  locality_lb_policy              = "LEAST_REQUEST" # An O(1) algorithm which selects two random healthy hosts and picks the host which has fewer active requests.
  connection_draining_timeout_sec = 60              # Time for which instance will be drained (not accept new connections, but still work to finish started).

}

resource "google_compute_region_backend_service" "internal_lb_tcp" {
  provider                        = google-beta
  name                            = "internal-lb-tcp"
  description                     = "Internal Load Balancer for Interconnect incoming requests"
  network                         = data.google_compute_subnetwork.shared.network
  region                          = var.region
  protocol                        = "TCP"
  session_affinity                = "NONE"          # Type of session affinity to use.
  locality_lb_policy              = "LEAST_REQUEST" # An O(1) algorithm which selects two random healthy hosts and picks the host which has fewer active requests.
  connection_draining_timeout_sec = 60              # Time for which instance will be drained (not accept new connections, but still work to finish started).

}
```

### Error output

The error is the same while using normal or beta provider:

```
╷
│ Error: Error updating BackendService "projects/XXXXX/global/backendServices/external-lb-https-backend": googleapi: Error 400: Invalid value for field 'resource.localityLbPolicy': 'LEAST_REQUEST'. Locality LB policy is not supported., invalid
│
│   with google_compute_backend_service.external_lb_https,
│   on elb.tf line 75, in resource "google_compute_backend_service" "external_lb_https":
│   75: resource "google_compute_backend_service" "external_lb_https" {
│
╵
╷
│ Error: Error updating RegionBackendService "projects/XXXXX/regions/europe-west1/backendServices/internal-lb-tcp": googleapi: Error 400: Invalid value for field 'resource.localityLbPolicy': 'LEAST_REQUEST'. Locality LB policy is not supported., invalid
│
│   with google_compute_region_backend_service.internal_lb_tcp,
│   on ilb.tf line 20, in resource "google_compute_region_backend_service" "internal_lb_tcp":
│   20: resource "google_compute_region_backend_service" "internal_lb_tcp" {
│
```

EDIT: Changed the scope of the issue from lack of support (wrongly determined) to documentation improvement

**Comment by melinath** [comment]
@dgteixeira that value is supported by the provider; it looks like those error messages are 400 errors, which means it's a validation error from the API. It looks like the [latest version of the API docs](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) states:

```
[localityLbPolicy] is applicable to either:

* A regional backend service with the serviceProtocol set to HTTP, HTTPS, or HTTP2, and loadBalancingScheme set to INTERNAL_MANAGED.
* A global backend service with the loadBalancingScheme set to INTERNAL_SELF_MANAGED.
```

Is your service one of those? If not, that could explain the error. It looks like the TF provider docs are out of date compared to the API docs, so the fix here might be a docs update.

**Comment by dgteixeira** [comment]
hello @melinath , how are you? Happy New Year 🤘

First of all, thanks for the response!

I actually read that documentation, and I got confused.
I was wondering if that description was for the `MAGLEV` enum or for the entire field.

I am currently using 2 backend services. Both are HTTP.
However, one is EXTERNAL, so it should not work if that description is for the complete localityLbPolicy.

The other one, that I use for an Internal Load Balancer, I set the load_balancing_scheme as "INTERNAL" and is a regional backend service.

` load_balancing_scheme = "INTERNAL"`

It should work, right? Or `"INTERNAL"` is different from `"INTERNAL_MANAGED"` ?

Thanks again!

**Comment by melinath** [comment]
@dgteixeira they're different - here are the docs describing the different values that load_balancing_scheme can take: https://cloud.google.com/load-balancing/docs/backend-service

**Comment by dgteixeira** [comment]
@melinath thanks for the response!

Then it's a big fail on my part, sorry. 
It actually makes sense that I can't specify an http-based rule on a TCP Load Balancer (INTERNAL_MANAGED is for the Internal HTTP Load Balancer).

In conclusion this issue is only for improving the documentation. I was a bit confused, but this actually helped me out!

Thanks!
