### ISSUE TITLE
google_artifact_registry_repository is GA

### ISSUE THREAD

**Issue by kelly-brown** [hashicorp/terraform-provider-google#10814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Artifact registry is no longer a beta only product but it has not been moved into the google provider.  Please move the google_artifact_registry_repository resource into the google provider as it is only available in the google-beta provider at this time.

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository

https://cloud.google.com/blog/products/devops-sre/artifact-registry-is-ga

**Comment by DrFaust92** [comment]
ill take a look
