### ISSUE TITLE
Add support for the "--enable-service-externalips" flag in google_container_cluster

### ISSUE THREAD

**Issue by marktru** [hashicorp/terraform-provider-google#10824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

See [documentation](https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/create#:~:text=pod%2Dsecurity%2Dpolicies.-,%2D%2Denable%2Dservice%2Dexternalips,-Enables%20use%20of).

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "my_cluster" {
  name               = "my-cluster"
  location           = "us-central1"
  initial_node_count = 1

  network_config {
    service_external_ips_config {
      enabled = true
    }
  }
  # other settings...
}
```

### References

* Internal issue: [b/211467605](http://b/211467605)

**Comment by c2thorn** [comment]
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#serviceexternalipsconfig

**Comment by roaks3** [comment]
Appears to be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6392
