### ISSUE TITLE
regional backend service - "capacity_scaler" cannot be set for non-managed backend service error

### ISSUE THREAD

**Issue by linjie333** [hashicorp/terraform-provider-google#10837]
I am trying to create a regional backend service for use with Network Load Balancer, the resource looks like this:
```
resource "google_compute_region_backend_service" "default" {
  provider              = google-beta
  name                  = "xlb-network-backend-service"
  region                = var.location_id
  protocol              = "TCP"
  port_name             = "tcp"
  load_balancing_scheme = "EXTERNAL"
  health_checks         = [google_compute_region_health_check.default.id]
  backend {
    group           = google_compute_instance_group_manager.mig.instance_group
    balancing_mode  = "UTILIZATION"
    capacity_scaler = 1.0
  }
}
```

but I got the error: `Error: "capacity_scaler" cannot be set for non-managed backend service, found value 1`

Based on the docs, the capacity_scaler is supposed to be required for all load_balancing_scheme except INTERNAL, so I don't understand why this isn't working. Can anyone tell me where I did wrong? Thanks!

**Comment by linjie333** [comment]
Also tried to change the load_balancing_scheme to EXTERNAL_MANAGED
but got: `Error: expected load_balancing_scheme to be one of [EXTERNAL INTERNAL INTERNAL_MANAGED ], got EXTERNAL_MANAGED`

however, in the doc, it says `Default value is INTERNAL. Possible values are EXTERNAL, EXTERNAL_MANAGED, INTERNAL, and INTERNAL_MANAGED.`

i am so confused, is this a bug? Please advise! thank you!

**Comment by melinath** [comment]
I'd recommend reading through https://cloud.google.com/load-balancing/docs/backend-service - it goes through a few different ways of configuring your load balancer corresponding to different load_balancing_scheme values and other settings. 

It might also be useful to read through https://cloud.google.com/load-balancing/docs/backend-service.

This is not an area I'm super familiar with, and I'm not able to quickly find a clear statement about this one way or another on either of those pages; however, this seems unlikely to be a bug. The load balancer setup is complex.

Something else you can try is adding [`TF_LOG=TRACE`](https://www.terraform.io/internals/debugging) to your `terraform apply` call - that will output all the API calls, which might help you figure out what's going on!

For now I'm going to close this issue, but it would be great to know what you find out, and feel free to open up a new bug or documentation ticket if you end up feeling there's an issue here.
