### ISSUE TITLE
Add support for gVNIC in GKE node pools

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/terraform-provider-google#10836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

gVNIC is supported in GKE, but there is no way to define it using the Google Cloud Terraform provider. Please add support for specifying gVNIC on node pools.

https://cloud.google.com/kubernetes-engine/docs/how-to/using-gvnic

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "gvnic_pool" {
  name       = "my-gvnic-pool"
  cluster    = google_container_cluster.primary.id
  node_count = 1

  node_config {
    machine_type = "n2-standard-8"
    enable_gvnic = true
  }
}
```

* Internal issue: [http://b/218092620](http://b/218092620)

**Comment by rileykarson** [comment]
b/218092620

**Comment by ScottSuarez** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/5789
