### ISSUE TITLE
Unable to declare a dynamic value for source_ranges for google_compute_firewall

### ISSUE THREAD

**Issue by tnguyen14** [hashicorp/terraform-provider-google#10833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.7

Plugin version: 4.5.0

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "subnet" {
  name = "my-subnet"
  region = "europe-west3"
  network = "my-network"
  ip_cidr_range = var.ip_cidr_range
}

resource "google_compute_firewall" "fw" {
  name = "my-firewall"
  network = "my-network"
  allow {
    protocol = "tcp"
    ports = ["8080"]
  }
  source_ranges = [google_compute_subnetwork.subnet.ip_cidr_range]
  target_tags = var.target_tags
}
```

### Debug Output

```
2022/01/04 21:09:37 [ERROR] eval: *terraform.EvalDiff, err: 1 error occurred:
	* one of source_tags, source_ranges, or source_service_accounts must be defined
```
### Expected Behavior

No error

### Actual Behavior

Terraform fails to run plan

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The run would work if I hard-code the source_ranges to the actual CIDR string, but not if it's referencing another resource attribute.

### References

The comment in https://github.com/hashicorp/terraform-provider-google/issues/1845#issuecomment-413038485 seems to suggest that this should work

**Comment by tnguyen14** [comment]
I've narrowed down this issue a bit more - this happens when the subnet's `ip_cidr_range` comes from a dynamic resource attribute. It doesn't happen if the `var.ip_cidr_range` is just a string. An example of such is:

```tf
resource "solidserver_ip_subnet" "subnet" {
  space = "ip-space"
  block = "ip-block"
  name = "subnet-range"
  prefix_size = "24"
}

resource "google_compute_subnetwork" "subnet" {
  name = "my-subnet"
  region = "europe-west3"
  network = "my-network"
  ip_cidr_range = solidserver_ip_subnet.subnet.prefix
```

**Comment by grantyoung** [comment]
We're also seeing this issue in our code.

Are there any plans to fix this? It's a little worrying this looks to be a bug since 4.0 with no fix.

**Comment by jeroenj** [comment]
It seems to be happening as soon as there's at least one range in there that's dynamic.

E.g. the following fails too:

```hcl
resource "google_compute_subnetwork" "subnet" {
  name = "my-subnet"
  region = "europe-west3"
  network = "my-network"
  ip_cidr_range = var.ip_cidr_range
}

resource "google_compute_firewall" "fw" {
  name = "my-firewall"
  network = "my-network"
  allow {
    protocol = "tcp"
    ports = ["8080"]
  }
  source_ranges = ["10.0.0.1/32", google_compute_subnetwork.subnet.ip_cidr_range]
  target_tags = var.target_tags
}
```

**Comment by melinath** [comment]
marking resolved per above comment.
