### ISSUE TITLE
Cloud Composer 2 uses the Default Compute Engine service account for GKE Autopilot nodes

### ISSUE THREAD

**Issue by mikejuliettetango** [hashicorp/terraform-provider-google#10842]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If this is a bug report (for when something is there, but doesn't work how it should), please use the [bug issue template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md) instead.

If this is an enhancement / feature request (for when something (a resource, field, etc.) is missing, and should be added), please use the [enhancement template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md) instead.

If you have a support request or question, please check out the other resources listed [here](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md).

If your issue does not fit into one of the above templates, please fill out the following:

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version

  *  terraform <= 1.1.2

### Affected Resource(s)

* [google_composer_environment](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#argument-reference---cloud-composer-2)

### Issue Description

Because Composer 2 uses the Default Compute Engine service account and Workload Identity to manage the GKE Autopilot clusters, you may not specify a service account for your GKE Nodepool as an optional argument as currently stated:

```
service_account - (Optional) The Google Cloud Platform Service Account to be used by the node VMs. If a service account is not specified, the "default" Compute Engine service account is used. Cannot be updated. If given, note that the service account must have roles/composer.worker for any GCP resources created under the Cloud Composer Environment.
```

### References
* https://cloud.google.com/composer/docs/composer-2/create-environments#grant-permissions

b/301065829

**Comment by radogost** [comment]
Correct me if I misunderstood your question, but it seems that it is possible to specify a service account: https://cloud.google.com/composer/docs/composer-2/create-environments#service-account

**Comment by radogost** [comment]
Please close this issue @rileykarson
