### ISSUE TITLE
google_apigee_instance location seems to be only a region now

### ISSUE THREAD

**Issue by matihost** [hashicorp/terraform-provider-google#10849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 1.1.2
Google Provider Version: 4.5.0

### Affected Resource(s)

* google_apigee_instance

### Terraform Configuration Files

```tf
resource "google_apigee_instance" "apigee_instance" {
  ...
  location = "us-central1-b"  # zone instead of region
  ...
}
```

### Expected Behavior

It seems Apigee instance can be deployed only in region now, not a zone - even for evaluation subscription.

### Actual Behavior

When zone is provided to `location` field, the resulting Apigee instance location points to a region. 

So second terraform apply sees a change in location field (current region vs desired a zone) and it tries to delete instance and create it again.

**Comment by melinath** [comment]
If Apigee is no longer available as a zonal resource, we should probably update the docs to reflect that.

**Comment by rileykarson** [comment]
@xuchenma: This is due to a breaking change in the Apigee API and not a change in the Terraform provider, right?

**Comment by xuchenma** [comment]
Yes, the change in Apigee API has made the Terraform tests to fail.

**Comment by c2thorn** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/5872 also fixed the documentation
