### ISSUE TITLE
Failing test(s): Quota 'NVIDIA_V100_GPUS' exceeded

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10851]
Failure rate: 100% since Dec. 23 2021

Impacted tests:
- TestAccNotebooksRuntime_notebookRuntimeBasicGpuExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/239645?buildTab=tests&expandedTest=-7620613107265079483

Message:

```
Quota 'NVIDIA_V100_GPUS' exceeded
```

**Comment by AlfatahB** [comment]
b/261700286
