### ISSUE TITLE
Unable to destroy [tf created] resource

### ISSUE THREAD

**Issue by mabushey** [hashicorp/terraform-provider-google#10861]
TF version:
```
✗  terraform -v    
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/carlpett/sops v0.5.2
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/google v4.1.0
+ provider registry.terraform.io/hashicorp/google-beta v4.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

Your version of Terraform is out of date! The latest version
is 1.1.3. You can update by downloading from https://www.terraform.io/downloads.html
```

lol. I'm using the Hashicorp apt repo. Maybe someone should file a bug on this.

Trying to destroy a module that has bigquery stuff in it gives me:
```
Error: cannot destroy instance without setting deletion_protection=false and running `terraform apply`
```
I've tried setting a variable block for the `deletion_protection` var but it doesn't fix it. I found a few other github tickets regarding this, but they do not not deal with the issue and are locked.. :/

Someone needs to add a `--force` flag to TF, or at least make the `deletion_protection` var work.

**Comment by melinath** [comment]
Hi @mabushey - please open a new bug using the [bug template](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=bug&template=bug.md) and be sure to include a sample terraform configuration that reproduces the issue you're having (the simpler the better) and [debug output](https://www.terraform.io/internals/debugging) demonstrating the issue. Thanks!
