### ISSUE TITLE
Support Private services connect in google_compute_forwarding_rule with service directory namespace

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#10873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a private services connect connection to a third-party managed service there is the option when creating the forwarding rule of providing an service directory namespace (see: https://cloud.google.com/vpc/docs/configure-private-service-connect-services#create-endpoint).  The APIs support this already (the `serviceDirectoryRegistrations` property, see: https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules).  This does not yet have support in the `google_compute_forwarding_rule` resource.  This is a request to add that support

### New or Affected Resource(s)

`google_compute_forwarding_rule`

### Potential Terraform Configuration

```tf
resource "google_compute_forwarding_rule" "elastic_psc_fwd_rule" {
  name            = "managed-es-psc-fwd-rule"
  ...
  service_directory_registrations {
    namespace = "service-directory-namespace-name"
  }
}
```

### References

* #0000

**Comment by ggprod** [comment]
Actually, the resource seems to not support Private services connect at all.  I am not able to create a private services connect configuration for a regional forwarding rule (as I could with command line or APIs directly as here: https://cloud.google.com/vpc/docs/configure-private-service-connect-services#create-endpoint).  Whatever I try for configuration of the resource for this regional PSC ends in an error

**Comment by slevenick** [comment]
b/213945697

**Comment by ayush-jain1** [comment]
Any update on this ? this is a bare minimum feature to develop and rollout PSC for enterprises

**Comment by rmjamess** [comment]
As long as you are ok with keeping the default google namespace, it is possible although not very documented. See https://github.com/hashicorp/terraform-provider-google/issues/11225 for the code.

I agree though that this resource should support creating a PSC endpoint natively including specifying a namespace.
