### ISSUE TITLE
Composer 2 - storage_gb larger than 10GB

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#10879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
resource "google_composer_environment" "test" {
  name   = "example-composer-env-tf-c2"
  region = "us-central1"
  config {

    software_config {
      image_version = "composer-2.0.0-preview.3-airflow-2.1.2"
    }

    workloads_config {
      scheduler {
        cpu        = 0.5
        memory_gb  = 1.875
        storage_gb = 1
        count      = 1
      }
      web_server {
        cpu        = 0.5
        memory_gb  = 1.875
        storage_gb = 10
      }
      worker {
        cpu = 0.5
        memory_gb  = 1.875
        storage_gb = 1
        min_count  = 1
        max_count  = 3
      }


    }
    environment_size = "ENVIRONMENT_SIZE_SMALL"

    node_config {
      network    = google_compute_network.test.id
      subnetwork = google_compute_subnetwork.test.id
      service_account = google_service_account.test.name
    }
  }
}
```

### Debug Output

```bash
Error 400: Found 1 problem:
	1) You have to specify Web Server storage not larger than 10GB., badRequest
╷
│ Error: googleapi: Error 400: Found 1 problem:
│ 	1) You have to specify Web Server storage not larger than 10GB., badRequest
```

If you specify the web server as 10 then you get the above error, its a bit misleading since its not larger than 10gb. This should be included in the documentation to explicitly state the max value.
Also the same for worker nodes and the scheduler nodes.

### Steps to Reproduce

1. Use the example on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment 
2. Specify any of the storage gb to be 10. 

### References

* #0000

**Comment by shuyama1** [comment]
Hi @drandell! Thanks for filing the issue. I was not able to reproduce the error using the configuration provided. Would you mind retrying it and see if the problem still occurs? If you still see the error, would mind sharing the full debug log? Thanks!

**Comment by drandell** [comment]
Hi @shuyama1 , i will am just trying to re-produce this now will edit this with the config if/when i can :). 
For additional context i was using Google-Beta 4.5.0, but have since moved to Google 4.6.0 (since composer 2 has gone GA with this version).
