### ISSUE TITLE
Attempt to create serverless vpc connector in shared vpc host project yields strange error

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#10891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

tried with 1.1.2 and 1.1.3
Tried with google-beta provider 3.65.0, 3.70.0, 3.90.1, 4.0 and later

### Affected Resource(s)

google_vpc_access_connector

### Terraform Configuration Files

```tf
resource "google_vpc_access_connector" "serverless_vpc" {
  provider = google-beta
  project = google_project.host.id. # shared vpc host project
  name    = "serverless-vpc-connector"
  region = var.serverless_vpc_subnet_region  # us-central1
  subnet {
    name = google_compute_subnetwork.serverless_vpc[var.serverless_vpc_subnet].name  #subnet is in shared vpc and us-central1
  }
  machine_type = "e2-micro"
  min_instances = 2
  max_instances = 6
}
```

### Debug Output
```
**oogle_vpc_access_connector.serverless_vpc: Creating...
╷
│ Error: Error creating Connector: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1beta1/projects/projects/tealbook-dev-vpc/locations/us-central1/connectors?alt=json&amp;connectorId=serverless-vpc-connector</code> was not found on this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_vpc_access_connector.serverless_vpc,
│   on main.tf line 63, in resource "google_vpc_access_connector" "serverless_vpc":
│   63: resource "google_vpc_access_connector" "serverless_vpc" {**
```
### Expected Behavior

Created a serverless vpc connector in the specified subnet of the specified shared vpc

### Actual Behavior
error

### Steps to Reproduce

`terraform apply`

### References

* #0000

**Comment by ggprod** [comment]
Not sure if it related to the bug or not but the error has the path `v1beta1/projects/projects/tealbook-dev-vpc/locations/us-central1/connectors?alt=json&amp;connectorId=serverless-vpc-connector</code> was not found on this server.` which looks incorrect with the `projects/projects` part.. not sure how that is happening

**Comment by shuyama1** [comment]
Hi @ggprod! Could you try using `google_project.host.project_id` instead? I guess it will solve your problem.

**Comment by ggprod** [comment]
thanks @shuyama1 and apologies for the time waste.. not sure how I missed that.. I must be tired

**Comment by shuyama1** [comment]
No worries! Glad you got the problem solved!
