### ISSUE TITLE
Cloud Functions support for buildWorkerPool flag

### ISSUE THREAD

**Issue by vponnam** [hashicorp/terraform-provider-google#10897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In some cases Cloud functions are required to be deployed on CloudBuild Custom workers for VPCSC compatibility reasons, hence it helps to add support for `buildWorkerPool` flag to the provider.

This flag is currently supported by [gcloud](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--build-worker-pool
) and [functionsAPI](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#:~:text=can%20reach%20it.-,buildWorkerPool,-string)

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  name        = "function-test"
  description = "My function"
  runtime     = "nodejs14"
  build_worker_pool = "projects/{project}/locations/{region}/workerPools/{workerPool}"

  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  trigger_http          = true
  entry_point           = "helloGET"
}
```

### References

* [google_cloudfunctions_function](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function)

**Comment by raihan1khan** [comment]
Any status regarding this one

**Comment by kiewel** [comment]
What is the status?

**Comment by jsekar3** [comment]
how long it will take to merge fix PR?
