### ISSUE TITLE
Artifact Registry: Add version policy

### ISSUE THREAD

**Issue by lpzdvd-packlink** [hashicorp/terraform-provider-google#10904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When you create a Maven repository in Artifact Registry, you can specify a Maven version policy in the UI (none, snapshot, release)  It will be nice to do it from terraform.

### New or Affected Resource(s)

google_artifact_registry_repository

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_artifact_registry_repository" "releases" {
  provider      = google-beta
  project       = var.project
  location      = var.location
  repository_id = "my-repository"
  description   = "lorem ipsum dolor sit amet"
  format        = "MAVEN"
  
  # proposed change here
  maven_config {
    version_policy = "RELEASE"
  }
}



```

### References

https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories#versionpolicy

**Comment by shuyama1** [comment]
Hi @lpzdvd-packlink. Thanks for filing the issue. Looks like `policy ` is not supported in the API (https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories), so we are not able to implement this feature currently. Please correct me if I am wrong.

**Comment by lpzdvd-packlink** [comment]
Thank you for your response !

You're right. I was assuming it was supported in the API as it can be chosen in the UI.

Sorry for the confusion. It'll have to wait !!

**Comment by rpolyano** [comment]
@shuyama1 That link you posted (https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories#MavenRepositoryConfig) does seem to have a version policy (and snapshot overwrites) fields. Are these not the ones you are referring to?

**Comment by lpzdvd-packlink** [comment]
@rpolyano looking at your comment it seems we got confused.
Your link states that [version policy](https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories#versionpolicy) is indeed supported but @shuyama1 was expected the field at a "top level" ?

So, I guess it can be implemented if accepted.
Regards !

**Comment by shuyama1** [comment]
Thanks @rpolyano! Looks like it is supported in the API. 
@lpzdvd-packlink Sorry for missing it in the first place! Removed the upstream label.

**Comment by DrFaust92** [comment]
seems to be supported already https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository#version_policy

**Comment by shuyama1** [comment]
Thanks @DrFaust92! Yeah! Looks like the feature got implemented in https://github.com/GoogleCloudPlatform/magic-modules/pull/5294. Closing this issue then.
