### ISSUE TITLE
data.google_client_config._.project is an empty string

### ISSUE THREAD

**Issue by jpetazzo** [hashicorp/terraform-provider-google#10907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.5.0
```

### Affected Resource(s)

* google_client_config

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.5.0"
    }
  }
}

data "google_client_config" "_" {}

output "project" {
  value = data.google_client_config._.project
}
```

### Debug Output

https://gist.github.com/jpetazzo/0fbbb6b596b8428586d1039bd64a3338

### Expected Behavior

output should contain the current default project configured in the `gcloud` SDK

### Actual Behavior

output contains an empty string, even though I have a project configured in `gcloud` SDK:

```
$ gcloud config list
[core]
account = jerome.petazzoni@gmail.com
disable_usage_reporting = True
project = prepare-tf

Your active configuration is: [default]
```

### Steps to Reproduce

Set up `gcloud`, authenticate, set a default project, apply the configuration above.

### Important Factoids

/

### References

/

**Comment by edwardmedia** [comment]
@jpetazzo this is for the provider. Here is the [detail](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#configuration-reference) you may want to review.

To test, can you try to add environment variables like GOOGLE_PROJECT to see the result?

```
export GOOGLE_PROJECT=prepare-tf
```

**Comment by jpetazzo** [comment]
Hi, thanks for the quick response and for taking the time to look at this!

However, I don't understand what you mean. According to the documentation that you linked:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#primary-authentication

> If you are using Terraform on your workstation we recommend that you install gcloud and authenticate using User Application Default Credentials ("ADCs") as a primary authentication method. You can enable ADCs by running the command gcloud auth application-default login.

(Alright, that's what I did, I think?)

> Google Cloud reads the quota project for requests will be read automatically from the core/project value. 

Since that sentence is invalid, I suppose that it was edited and perhaps some content was lost in the process, but as it is written right now, I understand that if I'm authenticating with gcloud (which is the case) it will read the project from core/project value, which, in my case, is correctly set to `prepare-tf` (as shown by `gcloud config list`).

However, according to my tests, the project **must** be specified either in the provider block, or within each resource individually.

So it makes me wonder if the quoted paragraph above is invalid, or if perhaps "project" and "quota project" are two different things in GCP? (Sorry, I'm not super familiar with its terminology.)

Or - I was assuming that I was using "ADC" but perhaps ADC is something completely different and I am not, in fact, using it? (I tried to run `gcloud auth application-default login` and it made me authenticate again, but after trying to `terraform apply` one more time, it still requires the project to be set at the provider- or resource-level).

Just to give you a high-level view of what I'm trying to achieve: I'm working with multiple projects, and in a perfect world, I would like to switch with a single command (e.g. `gcloud config set`) and avoid hard-coding the project name in my Terraform configurations - and/or find a safe way to make sure that it doesn't go out of sync with gcloud configuration. (As it is right now, if I use a TF variable, it could go out of sync with the gcloud config.)

**Comment by edwardmedia** [comment]
@jpetazzo below command is good for the authentication. For the configuration used for Terraform **provider**, currently it does not look at the ones created via gcloud. They are different. Does this make sense? 

```
gcloud auth application-default login
```

**Comment by jpetazzo** [comment]
Got it, that makes sense. Do you think this could be added to the docs somehow? It's tricky because the information is spread across multiple pages; but basically I was wondering "how can I get Terraform to use `gcloud`'s configuration" and when I found the data source I was thinking "haha! victory!" and ended up thinking this was a bug 😅

It would be even better if the provider could get the value from the gcloud configuration; do you know if there is a good reason for why it doesn't do it?

Thanks again!

**Comment by jpetazzo** [comment]
Btw if you think either of these options is acceptable (edit the docs / patch the provider) I could give it a try. Just trying to figure out if that kind of PR would be acceptable!

**Comment by edwardmedia** [comment]
@jpetazzo I think the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#configuration-reference) has made it clear. One could has missed the keyword Provider which is specific.

I don't think there is a plan that support reading the configs provided by **gcloud** in the near future.

I glad it makes sense to you now. Closing the issue then
