### ISSUE TITLE
Stateful IP address support in MIG

### ISSUE THREAD

**Issue by rosmo** [hashicorp/terraform-provider-google#10908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently the managed instance group manager (`google_compute_instance_group_manager` and `google_compute_region_instance_group_manager`) only supports stateful disks. There is support for IP addresses in preview: https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-ip-addresses-in-migs

### New or Affected Resource(s)

* `google_compute_instance_group_manager`
* `google_compute_region_instance_group_manager`

### Potential Terraform Configuration

```tf
resource "google_compute_instance_group_manager" "computer_blue" {
  name               = "darling-picky"
  base_instance_name = "darling-picky"
  zone        = "europe-west4-c"
  target_size = 2

  version {
    instance_template = google_compute_instance_template.instance_template_blue.id
  }

  # IPv6 is not supported yet but maybe in the future
  stateful_address_ipv4 {
     interface = "nic0" # Optional, default: nic0
     type = "INTERNAL" # Enum: INTERNAL, EXTERNAL (or address_type?)
     auto_delete = "ON_PERMANENT_INSTANCE_DELETION" # Enum: ON_PERMANENT_INSTANCE_DELETION, NEVER (default)
  }
}
```

### References

* [Configuring stateful IP addresses in MIGs](https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-ip-addresses-in-migs)

**Comment by espala** [comment]
It was pretty good work. We had such a problem and we have been waiting for this feature for a long time. We hope it will be active quickly and we can use it on terraform.

**Comment by espala** [comment]
up.

I hope it will be prioritized. :)

**Comment by leocurrie** [comment]
It would also be helpful to be able to specify an address to use, for example:

```tf
resource "google_compute_address" "static_internal_ip" {
  name         = "instance-1-address"
  address_type = "INTERNAL"
}

resource "google_compute_instance_group_manager" "computer_blue" {
  name               = "darling-picky"
  base_instance_name = "darling-picky"
  zone        = "europe-west4-c"
  target_size = 2

  version {
    instance_template = google_compute_instance_template.instance_template_blue.id
  }

  stateful_address_ipv4 {
     type = "INTERNAL" 
     address = google_compute_address.static_internal_ip.self_link
}
```

**Comment by ynrn** [comment]
up.
I hope it will be added and we can use it soon

**Comment by mdzierzecki** [comment]
up!

Any updates on this issue? :(

**Comment by melinath** [comment]
b/175683748

**Comment by melinath** [comment]
@hao-nan-li

**Comment by JunchengL** [comment]
up
Any news for this stateful ip support?

**Comment by alexh2o17** [comment]
+1
