### ISSUE TITLE
Crash with InstanceTemplates

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-provider-google#10918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.0.1

### Affected Resource(s)

* google_compute_instance_template

### Terraform Configuration Files

```tf
```

### Panic Output

panic: interface conversion: interface {} is nil, not *google.Config

goroutine 84 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceComputeInstanceTemplateRead(0xc000a3db80, 0x0, 0x0, 0x3fe1280, 0xc000070400)
        github.com/hashicorp/terraform-provider-google/google/resource_compute_instance_template.go:1259 +0x28b3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0005af960, 0x31abb20, 0xc000a21a40, 0xc000a3db80, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005af960, 0x31abb20, 0xc000a21a40, 0xc000a3e4d0, 0x0, 0x0, 0xc000a69b28, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d890, 0x31abb20, 0xc000a21a40, 0xc000a21a80, 0xc000a21a40, 0x40ba05, 0x2a90460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000d7d500, 0x31abbc8, 0xc000a21a40, 0xc000b40240, 0xc000d7d500, 0xc000b428d0, 0xc00064cba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2be9440, 0xc000d7d500, 0x31abbc8, 0xc000b428d0, 0xc000b401e0, 0x0, 0x31abbc8, 0xc000b428d0, 0xc000a94c00, 0x1268)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020e540, 0x31e06f8, 0xc000102d80, 0xc000d59680, 0xc000cc89c0, 0x3f9e7d0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00020e540, 0x31e06f8, 0xc000102d80, 0xc000d59680, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028cb00, 0xc00020e540, 0x31e06f8, 0xc000102d80, 0xc000d59680)
        google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-google_v4.3.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Not crash

### Actual Behavior

Crashed

### Steps to Reproduce

Not sure how to

1. `terraform destroy -target foo.bar`

### References

* #0000

**Comment by edwardmedia** [comment]
@AndreasBergmeier6176 can you share the config that can be used to repro this issue?

**Comment by melinath** [comment]
closing due to no response.
