### ISSUE TITLE
Automatically detect schema changes in PRs

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#10922]
### Affected Resource(s)

* google_*

In an attempt to reduce the amount of maintainer effort in PRs, we can add an automatic Magician step that compares the schemas of resources changed in the PR and links to the diff.
We can adapt the existing schema diff tool.

**Comment by melinath** [comment]
@c2thorn do you happen to know what kind of thing you might have been thinking of for this? For example, we could generate collapsed section of the comment that lists all the changed resources and fields?

**Comment by c2thorn** [comment]
As far as remember, it was relevant work to https://github.com/hashicorp/terraform-provider-google/issues/10923 that I thought could be separated out. We technically are doing it now. There may be other applications for using it, but that could be its own more specific issue. I'll close this for now unless you think otherwise @melinath

**Comment by melinath** [comment]
SGTM
