### ISSUE TITLE
Cloud Run service is not updated when Docker image in Artifact Registry changes

### ISSUE THREAD

**Issue by haroldadmin** [hashicorp/terraform-provider-google#10920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v1.1.3
on darwin_arm64
```

### Affected Resource(s)

* google_cloud_run_service
* google_artifact_registry_repository

### Terraform Configuration Files

```tf
resource "google_artifact_registry_repository" "policy_data_export" {
  provider = google-beta

  project       = var.project
  location      = var.region
  repository_id = var.artifact_registry_repo # "policy-data-export"
  format        = "DOCKER"
}

resource "google_cloud_run_service" "policy_data_export" {
  name     = var.cloud_run_service
  location = var.region

  metadata {
    annotations = {
      "run.googleapis.com/client-name" = "terraform"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }

  template {
    spec {
      containers {
        # image_url = "austalia-southeast1-docker.pkg.dev/<project-id>/policy-data-export/policy-data-export"
        image = local.image_url
      }
    }
  }
}
```

### Expected Behavior

Whenever a new image is uploaded to the Artifact Registry, Terraform should update the Cloud Run service to use the new image on running `terraform apply`

### Actual Behavior

Terraform does not detect that a new image has been uploaded to Artifact Registry and therefore does not update the Cloud Run service

### Steps to Reproduce

- `terraform apply`
- Create new docker image and push it to the Artifact Registry
- `terraform apply` -> No change detected for the Cloud Run service

### Important Factoids

None

### References

A similar issue existed for Container Registry, but it was closed without a satisfactory solution (#6706)

**Comment by megan07** [comment]
@haroldadmin I'm sorry you're experiencing this issue. Unfortunately, as stated in the other issue, we have no way of reading the docker info. You'll want to follow the previously suggested solutions and use the [docker provider](https://www.terraform.io/docs/providers/docker/d/registry_image.html).

- https://github.com/hashicorp/terraform-provider-google/issues/6706
- https://github.com/hashicorp/terraform-provider-google/issues/6635
