### ISSUE TITLE
Detect breaking changes in PRs

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#10923]
To both reduce the amount of maintainer effort required for PRs and add another layer of protection, we can automatically detect breaking changes in resource schema.
Likely, we can utilize https://github.com/hashicorp/terraform-provider-google/issues/10922 as a step towards this.

**Comment by ScottSuarez** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6642
