### ISSUE TITLE
google_cloud_run_service doesn't respect/process certain annotations

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#10958]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.4.0
+ provider registry.terraform.io/hashicorp/google-beta v4.4.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

`google_cloud_run_service`

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "savings" {
  provider = google-beta
  project = data.terraform_remote_state.savings_core.outputs.project_id
  name     = "savings-service"
  location = var.savings_service_location

  template {
    spec {
      containers {
        image = var.savings_service_container_image
        resources {
          limits = {
            cpu = var.savings_service_container_cpu
            memory = var.savings_service_container_memory
          }
        }
        dynamic "env" {
          for_each = merge(var.savings_secrets, { "db-addr" = "${data.terraform_remote_state.savings_core.outputs.savings_postgres_ip}:5432" })
          content {
            name = replace(upper(env.key), "-", "_")
            value_from {
              secret_key_ref {
                name = split("/", google_secret_manager_secret.savings_secrets[env.key].id)[3]
                key = "latest"
              }
            }
          }
        }
      }
      service_account_name = data.terraform_remote_state.savings_core.outputs.savings_sa
    }

    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale" = var.savings_service_max_instances
        "run.googleapis.com/vpc-access-connector" = data.terraform_remote_state.savings_core.outputs.serverless_vpc_connector_name
        "run.googleapis.com/vpc-access-egress" = "private-ranges-only"
        "run.googleapis.com/ingress" = var.savings_service_ingress_rule // variable set to "internal-and-cloud-load-balancing"
      }
    }
  }
  autogenerate_revision_name = true
}
```

### Expected Behavior

the deployed cloud run service should have the annotation `run.googleapis.com/ingress: internal-and-cloud-load-balancing`

### Actual Behavior

the deployed cloud run service has the default annotation `run.googleapis.com/ingress: all`

### Steps to Reproduce

Any `terraform apply`

### References

This may be related to the fact the cloud run service configuration has two different metadata sections and different annotations go in each, but the terraform resource only has a single metadata section

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: savings-service
  namespace: '688642586917'
  selfLink: /apis/serving.knative.dev/v1/namespaces/688642586917/services/savings-service
  uid: 8de19a0a-4d75-4807-9abe-8a729bdafe23
  resourceVersion: AAXWSC2NOdI
  generation: 10
  creationTimestamp: '2022-01-08T02:13:35.033785Z'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: ***
    serving.knative.dev/lastModifier: ***
    client.knative.dev/user-image: ***
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/vpc-access-connector: savings-svpc-connector
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ***
      containers:
      - image: ***
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-name
        - name: PT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: pt-password
        - name: PLAID_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: plaid-secret
        - name: PLAID_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: plaid-url
        - name: IDS_BUCKET
          valueFrom:
            secretKeyRef:
              key: latest
              name: ids-bucket
        - name: PRIME_TRUST_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: prime-trust-url
        - name: PT_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: pt-username
        - name: PT_JWT
          valueFrom:
            secretKeyRef:
              key: latest
              name: pt-jwt
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-pwd
        - name: PLAID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: plaid-client-id
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-addr
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-user
        resources:
          limits:
            cpu: 1000m
            memory: 512M
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 10
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2022-01-23T23:26:13.772754Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2022-01-22T03:30:45.994687Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2022-01-23T23:26:13.772754Z'
  latestReadyRevisionName: savings-service-v4r9l
  latestCreatedRevisionName: savings-service-v4r9l
  traffic:
  - revisionName: savings-service-v4r9l
    percent: 100
    latestRevision: true
  url: https://savings-service-wzwkzdk5bq-uc.a.run.app
  address:
    url: https://savings-service-wzwkzdk5bq-uc.a.run.app
```

* #0000

**Comment by prabhu34** [comment]
This is not an issue, but rather use of the annotations in the correct metadata blocks for Ingress. If interested, use the [Cloud Run Terraform Module](https://github.com/googlecloudplatform/terraform-google-cloud-run).

Metadata blocs are supported on the existing resource for both service and the containers. Use the `metadata {}` block outside of the `template {}` block.

```
resource "google_cloud_run_service" "main" {
  provider = google-beta
  .
  .
  metadata {
    annotations =  {
        "run.googleapis.com/ingress" = "internal-and-cloud-load-balancing"
    }
  }

  template {
    spec {
      containers {}
    } // spec
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale" = var.savings_service_max_instances
        "run.googleapis.com/vpc-access-connector" = data.terraform_remote_state.savings_core.outputs.serverless_vpc_connector_name
        "run.googleapis.com/vpc-access-egress" = "private-ranges-only"
      }
    }
  } // template
}
```

**Comment by ggprod** [comment]
> This is not an issue, but rather use of the annotations in the correct metadata blocks for Ingress. If interested, use the [Cloud Run Terraform Module](https://github.com/googlecloudplatform/terraform-google-cloud-run).
> 
> Metadata blocks are supported on the existing resource for both service and the containers. Use the `metadata {}` block outside of the `template {}` block.
> 
> ```
> resource "google_cloud_run_service" "main" {
>   provider = google-beta
>   .
>   .
>   metadata {
>     annotations =  {
>         "run.googleapis.com/ingress" = "internal-and-cloud-load-balancing"
>     }
>   }
> 
>   template {
>     spec {
>       containers {}
>     } // spec
>     metadata {
>       annotations = {
>         "autoscaling.knative.dev/maxScale" = var.savings_service_max_instances
>         "run.googleapis.com/vpc-access-connector" = data.terraform_remote_state.savings_core.outputs.serverless_vpc_connector_name
>         "run.googleapis.com/vpc-access-egress" = "private-ranges-only"
>       }
>     }
>   } // template
> }
> ```

Yes, that works, thanks!  It wasn't clear this was possible from the documentation and samples
