### ISSUE TITLE
Router_Interface import does not import due to required "project" variable

### ISSUE THREAD

**Issue by ivayloivanov388** [hashicorp/terraform-provider-google#10956]
TF version: 1.1.4

We have a few existing HA VPN tunnels configure.I tried importing the configurations using terraform import command line  _"terraform import google_compute_router_interface.foobar us-central1/router-1/interface-1"_
from https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_interface

but the import requires project and doesn't accept 4th variable

For example:
"terraform import testdata europe-west1/router1/interface1"
it says: **_Error: project: required field is not set_**

When i try to use project before the region
terraform import testdata project-test/europe-west1/router1/interface1
it says: **_Invalid router interface specifier. Expecting {region}/{router}/{interface}_**

**Comment by c2thorn** [comment]
This is an older resource with an outdated import function, so it'll need to be updated to allow `project`.

As a workaround @ivayloivanov388, you should be able to set your default project via a provider block or environment variable. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference

**Comment by c2thorn** [comment]
Closing as this is really a fine-grained resource and doesn't have a similar self link as other resources. The default project should be defined and the same as the router parent.
