### ISSUE TITLE
Add support for image type configuration on the GKE Node Auto provisioning

### ISSUE THREAD

**Issue by mrvarmazyar** [hashicorp/terraform-provider-google#10957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since one of the [image streaming requirements](https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming#requirements) is having Container-Optimized OS with containers as node image and on the other side, if we use the [Node Auto Provisioning](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning), there's not any possibility to config `auto_provisioning_defaults` to set up the [default image type to cos_containerd](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#default-image-type). 

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
cluster_autoscaling {
    enabled             = true
    autoscaling_profile = "OPTIMIZE_UTILIZATION"

    auto_provisioning_defaults {
        image_type = "cos_containerd" (Valid values: cos_containerd, cos, ubuntu_containerd, ubuntu)
    }
}
```

### References

* #0000

**Comment by megan07** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5644
