### ISSUE TITLE
google_storage_transfer_job is replaced when schedule is updated

### ISSUE THREAD

**Issue by psvaiter** [hashicorp/terraform-provider-google#10967]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.3

### Affected Resource(s)

* google_storage_transfer_job

### Terraform Configuration Files

Before the change
```tf
resource "google_storage_transfer_job" "load_from_s3" {
  description = "${local.table_name} (.${local.file_format})"

  transfer_spec {
    transfer_options {
      overwrite_objects_already_existing_in_sink = false
      delete_objects_unique_in_sink              = false
      delete_objects_from_source_after_transfer  = false
    }

    aws_s3_data_source {
      bucket_name = var.bucket_name
      aws_access_key {
        access_key_id     = var.aws_access_key_id
        secret_access_key = var.aws_secret_access_key
      }
    }

    object_conditions {
      min_time_elapsed_since_last_modification = "600s"
      max_time_elapsed_since_last_modification = null
      
      include_prefixes = ["${local.bucket_path}/"]
      exclude_prefixes = []
    }

    gcs_data_sink {
      bucket_name = var.bucket_name
    }
  }

  schedule {
    schedule_start_date {
      year  = 2022
      month = 1
      day   = 1
    }
    start_time_of_day { # UTC
      hours   = 23
      minutes = 0
      seconds = 0
      nanos   = 0
    }
  }
}
```

After the change
```tf
resource "google_storage_transfer_job" "load_from_s3" {
  description = "${local.table_name} (.${local.file_format})"

  transfer_spec {
    transfer_options {
      overwrite_objects_already_existing_in_sink = false
      delete_objects_unique_in_sink              = false
      delete_objects_from_source_after_transfer  = false
    }

    aws_s3_data_source {
      bucket_name = var.bucket_name
      aws_access_key {
        access_key_id     = var.aws_access_key_id
        secret_access_key = var.aws_secret_access_key
      }
    }

    object_conditions {
      min_time_elapsed_since_last_modification = "600s"
      max_time_elapsed_since_last_modification = null
      
      include_prefixes = ["${local.bucket_path}/"]
      exclude_prefixes = []
    }

    gcs_data_sink {
      bucket_name = var.bucket_name
    }
  }
}
```

### Debug Output

The command `terraform plan` already shows it'll replace the resource:
```tf
  # module.ingestion_raw.module.data_transfer["instruments"].google_storage_transfer_job.load_from_s3 must be replaced
-/+ resource "google_storage_transfer_job" "load_from_s3" {
      ~ creation_time          = "2022-01-19T22:00:08.576629132Z" -> (known after apply)
      ~ deletion_time          = "" -> (known after apply)
      ~ id                     = "my-project/9414670201285386631" -> (known after apply)
      ~ last_modification_time = "2022-01-19T22:00:08.576629132Z" -> (known after apply)
      ~ name                   = "transferJobs/9414670201285386631" -> (known after apply)
      ~ project                = "my-project" -> (known after apply)
        # (2 unchanged attribute hidden)

      - schedule {
          - schedule_start_date { # forces replacement
              - day   = 1 -> null # forces replacement
              - month = 1 -> null # forces replacement
              - year  = 2022 -> null # forces replacement
            }
          - start_time_of_day {
              - hours   = 23 -> null # forces replacement
              - minutes = 0 -> null
              - nanos   = 0 -> null
              - seconds = 0 -> null
            }
        }
      ~ transfer_spec {
          ~ gcs_data_sink {
              + path        = (known after apply)
                # (1 unchanged attribute hidden)
            }
          ~ object_conditions {
                # (3 unchanged attributes hidden)
            }
            # (2 unchanged blocks hidden)
        }
    }
```

### Panic Output

None

### Expected Behavior

The resource should be updated in-place, as it's allowed through UI (Cloud Console).

### Actual Behavior

The resource has been recreated and the transfer run history has been lost.

### Steps to Reproduce

1. `terraform apply` using the configuration with a schedule specified
2. Change the config file by removing the schedule
3. `terraform plan` will show the output with "forces replacement" warnings

The opposite change also causes it to replace the resource, i.e. informing a schedule in a config where it doesn't exist.

### Important Factoids

None

### References

* The fix #10942 allowed me to remove schedule from config, but it triggers a replacement.
* It seems like it's [possible to update schedule through API](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/patch) using `updateTransferJobFieldMask`.

**Comment by c2thorn** [comment]
`schedule` does not seem to appear in one of the 5 fields available to update in the API: https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/patch.

Without the API support, this will not be possible. Also, labelling as `enhancement` considering this is an update behavior request.

**Comment by psvaiter** [comment]
It's not listed in documentation, but it is available to update. I could verify it with the "Try this API" feature. I attached two screenshots below (I redacted the projectId). So the API supports this field.

I thought this was a bug because it should not behave like that, and that was not foreseen when enabling this field. Don't you agree?

![image](https://user-images.githubusercontent.com/16355712/151853057-bbc529f7-c76a-4097-912e-eff05e32c5a7.png)
![image](https://user-images.githubusercontent.com/16355712/151853169-60b588bf-3f33-42c2-ad57-c18a30e61501.png)

**Comment by psvaiter** [comment]
Any update on this knowing that it's available in API, @c2thorn?

**Comment by c2thorn** [comment]
@psvaiter thank you for checking manually, this is unfortunate documentation from the API side. I'll amend this feature request as possible to do with the note to maintainers that the API team should be notified when this feature is implemented.

**Comment by psvaiter** [comment]
@c2thorn any update on this? Do you think it will be fixed?

**Comment by melinath** [comment]
b/261994417

**Comment by melinath** [comment]
@trodge you may need to assign yourself here as well.
