### ISSUE TITLE
Empty `pem_certificates` field on google_privateca_certificate

### ISSUE THREAD

**Issue by keithmattix** [hashicorp/terraform-provider-google#10966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.4

### Affected Resource(s)

* google_privateca_certificate

### Terraform Configuration Files

```tf
resource "google_privateca_certificate" "sign-intermediate-csr" {
  pool = "my-pool"
  location = "us-central1"
  certificate_authority = "my-root-ca"
  project = "my-project"
  lifetime = "157680000s"
  name = "my-csr"
  
  pem_csr = vault_pki_secret_backend_intermediate_cert_request.intermediate-csr.csr
}
```

### Debug Output

Using Terraform Cloud at the moment

### Expected Behavior

The `pem_certificates` field on a `google_privateca_certificate` should contain the entire certificate chain

### Actual Behavior

The `pem_certificates` field is an empty list

### Steps to Reproduce

Create any google_privateca_certificate and check TF state; the `pem_certificates` field will be empty

### Important Factoids

  * I'm 99% sure this issue is because the REST API reference is [incorrect](https://github.com/hashicorp/terraform-provider-google/blob/51686cec843e2c9f685b83b183ab1d722b3fda17/google/resource_privateca_certificate.go#L1093). The code looks for a key of `pemCertificates` when the [REST docs](https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificates#Certificate) indicate a key name of `pemCertificateChain`. This is preventing Terraform users from accessing the full CA chain for Google CAS resources.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/7657#issuecomment-823433435

**Comment by mitj04** [comment]
b/216472740
