### ISSUE TITLE
data.google_compute_address filter addresses by the status IN_USE|RESERVED

### ISSUE THREAD

**Issue by drdkadtr** [hashicorp/terraform-provider-google#10982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to filter out only addresses where  "status": "RESERVED"

### New or Affected Resource(s)

* data.google_compute_address

### Potential Terraform Configuration

```tf
data "google_compute_address" "my_ips" {
  count  = 12
  region = local.region
  name   = format("%s-nat-external-address-%s", var.project_id, count.index)
  
  # Some filter options here: ..... 
}
```

### References

* #0000

**Comment by rileykarson** [comment]
This resource refers to a single address, and the name must be provided- we're not able to filter within the provider. Providers can't interact w/ the `count` meta-argument unfortunately! There's an issue for plural datasources kicking around that would partially resolve this w/ provider logic, possibly, but it isn't scheduled work.
