### ISSUE TITLE
google_compute_security_policy supporting rate limiting

### ISSUE THREAD

**Issue by Charles546** [hashicorp/terraform-provider-google#10992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The [Cloud Armor Rate Limiting](https://cloud.google.com/armor/docs/rate-limiting-overview) is a useful feature. We need a way to manage the [policy with rate limiting rule](https://cloud.google.com/armor/docs/configure-security-policies#rate-limiting) through terraform. Maybe it can be added to the beta provider first since the feature itself is still pre-GA.

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/10020
