### ISSUE TITLE
Storage Bucket IAM Members

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-google#10994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.3
+ provider registry.terraform.io/hashicorp/google v4.8.0

### Affected Resource(s)

* google_storage_bucket_iam_member

### Terraform Configuration Files

```tf
resource "google_storage_bucket_iam_member" "storage_bucket_iam_additive" {
  bucket  = "foo"
  members = ["foo", "bar"]
  role    = "roles/storage.objectAdmin"
}
```

### Expected Behavior

Based on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam#argument-reference, particularly 
![image](https://user-images.githubusercontent.com/67290882/151450796-637cefd9-a40c-458a-ab13-8864e3f5a3ab.png)
I would have expected that we could add multiple members and it would succeed in granting the relevant permissions.

### Actual Behavior

```
Error: Missing required argument
...
The argument "member" is required, but no definition was found.

Error: Unsupported argument
...
An argument named "members" is not expected here. Did you mean "member"?
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

A couple of factors are in play here. The simplest way to look at this is as a documentation bug where it requires adding a warning that `members` is not available if you are using `google_storage_bucket_iam_member`, only for `google_storage_bucket_iam_policy` and `google_storage_bucket_iam_binding`. However, I think that there is a strong case for at least considering a fix to enable `members` in `google_storage_bucket_iam_member` (or adding a new `google_storage_bucket_iam_members` resource). 

First off, I am unable to use `google_storage_bucket_iam_policy` or `google_storage_bucket_iam_binding` because the way that my Terraform directories are structured is not conducive to authoritative IAM grants. I might be able to rework our directory structures and everything in a way that allows me to use authoritative at some point, but that would require a ton of rework and trade-offs in user experience and ease of management. That leaves me stuck with `google_storage_bucket_iam_member` as the only option that is additive.

The reason that I would like to use `members` instead of doing a `for_each` over  `google_storage_bucket_iam_member` is that I am also using conditions and conditions have a relatively low character limit that I have previously hit. As a result, it would be far more desirable if the policy could contain the condition once and apply it to X members instead of having to have X conditions and all of the character count limitations associated with that. 

Please let me know if there's something I'm missing there and if under the hood it would de-duplicate the X copies of the conditional so that at the end of the day the policy only contains a single copy of the conditional.

### References

* #0000

**Comment by slevenick** [comment]
I'm unclear on why for_each doesn't work for this use case. How does using for_each cause the condition to hit a character limit?

I don't think we want to support member *and* members in the same resource, it would end up being confusing and likely cause issues

**Comment by joe-a-t** [comment]
> I'm unclear on why for_each doesn't work for this use case. How does using for_each cause the condition to hit a character limit?

We have X number (100+) GSAs that we want to grant access to a specific directory within a bucket. When we want to grant all of those GSAs separate access to the bucket with their own conditional, we have previously hit a character limit because the bucket policy got too long with all of the copies of the conditional we had. 

> I don't think we want to support member and members in the same resource, it would end up being confusing and likely cause issues

I'm completely fine if this results in a new `google_storage_bucket_iam_members` resource. The issue is that there is no way to additively grant access to multiple members with a single conditional that governs all of them.

I also think there's some doc clarification needed related to the screenshot I included to specify which resources have `member` and which have `members`.

**Comment by slevenick** [comment]
How would having a `members` field on this resource help with this use case? My understanding is that you want to have a separate conditional for each member, and that when creating these conditionals you are running into character limits enforced by the API. The `bindings` resource or similarly an unauthoritative `members` resource will just be different ways of making the same requests, so I think you would run into the same issue?

**Comment by joe-a-t** [comment]
> My understanding is that you want to have a separate conditional for each member

I do not want a separate conditional for each member. My desired state is that we have a single conditional that applies to a list of members. I'm not sure if this is possible with the Google API constraints or not, but if the API allows for creating a policy where a single conditional can apply to a list of members instead of just a single member, that would be extremely helpful from a character limit perspective.

**Comment by slevenick** [comment]
You can already do that with a binding, and if it includes a conditional it won't overwrite any other roles unless they have the exact same conditional. I think that will solve your issue here, just use the IAM binding resource with your conditional.

You can test out that it won't overwrite existing members on that role without that conditional to make sure, but I'm almost positive that is what you are looking for

**Comment by joe-a-t** [comment]
Ok, so at the end of day you're saying that the answer to my question about de-duplication in the original issue is that the conditional will indeed be de-duplicated, which helps with the character limits?

> Please let me know if there's something I'm missing there and if under the hood it would de-duplicate the X copies of the conditional so that at the end of the day the policy only contains a single copy of the conditional.

**Comment by slevenick** [comment]
No, I'm saying that you should use the `bucket_iam_binding` resource that allows setting a collection of members for a particular role + binding. See: https://cloud.google.com/iam/docs/conditions-overview

Particularly this part:
Note: Conditional role bindings do not override role bindings with no conditions. If a principal is bound to a role, and the role binding does not have a condition, then the principal always has that role. Adding the principal to a conditional binding for the same role has no effect.

So when you use this resource without wanting to override other IAM config for that role it should work because you can add a unique conditional for this role+members

**Comment by joe-a-t** [comment]
Ok, so to clarify what you are saying, you are saying that 
![image](https://user-images.githubusercontent.com/67290882/153274873-c7887699-6a18-47cf-9e98-e1ef3910c94f.png)
should actually be `Authoritative for a given role and conditional combination`? Is that a correct understanding?

**Comment by slevenick** [comment]
Yup, role + condition

**Comment by joe-a-t** [comment]
Great, thanks a lot. Is that something where it would make sense to update the Terraform docs to clarify that?

**Comment by jos-** [comment]
Similar issue for e.g. `google_spanner_database_iam_member` and `google_runtimeconfig_config_iam_member`.

Using `for_each` seems not always doable, since the arguments of for_each have to be known before applying. E.g. a service account `email` attribute is only known after applying.
