### ISSUE TITLE
Support logging for managed public zones

### ISSUE THREAD

**Issue by indypinball** [hashicorp/terraform-provider-google#10990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The [dns_managed_zone resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone) does not have the ability to set if logging is enabled or not. When looking at the [documentation of the managedZones api](https://cloud.google.com/dns/docs/reference/v1/managedZones) the field is supported by the api

Please update the resource so that enabling logging on public zones can also be made. 

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration

```tf
resource "google_dns_managed_zone" "domain" {
  name        = "example-zone"
  dns_name    = "example-${random_id.rnd.hex}.com."
  description = "Example DNS zone"
  dnssec_config {
    state = "on"
  }
  labels = {
    foo = "bar"
  }
  logging = { 
    enabled = true
  }
}
```

### References

https://cloud.google.com/dns/docs/reference/v1/managedZones

**Comment by melinath** [comment]
the top-level field would be `cloud_logging_config` to match the API better. If `kind` is required, we would ideally not require users to set it; I'm not sure what that would look like. Requiring users to set it would probably be better than a complex workaround, though.

**Comment by melinath** [comment]
b/245982965
