### ISSUE TITLE
Error destroying google_compute_network_endpoint

### ISSUE THREAD

**Issue by wouterdegeus** [hashicorp/terraform-provider-google#10997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.7.0
+ provider registry.terraform.io/hashicorp/google-beta v4.7.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* google_compute_network_endpoint

### Terraform Configuration Files

```tf
resource "google_compute_network_endpoint" "neg" {
  for_each = local.negs

  network_endpoint_group = format("https://www.googleapis.com/compute/v1/projects/%s/zones/%s/networkEndpointGroups/test-%s-%s", var.project_id, each.value.zone, each.value.backend, each.value.zone)
  port                   = 443
  ip_address             = each.value.ip
  zone                   = each.value.zone
  instance               =  ""
}
```

### Expected Behavior

Terraform properly creates and destroys google_compute_network_endpoint as specified.

### Actual Behavior

Creation worked fine (but note we were required to provide it with an empty instance), but on a destroy we got this error:
```
Error: Error when reading or editing NetworkEndpoint: googleapi: Error 400: Invalid value for field 'networkEndpoints[0].instance': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

We are using this endpoint in a hybrid network endpoint group as created by:
```
gcloud compute network-endpoint-groups create <name>   --network-endpoint-type=non-gcp-private-ip-port
```
(since Terraform does not support this type of NEG yet we have to do this manually, see referenced ticket).
However, adding this google_compute_network_endpoint through terraform works fine on the manually created hybrid NEG.
The deletion fails - probably because it tries to send an instance attribute that is empty and thus fails the regexp.

### References

* #10040

**Comment by slevenick** [comment]
Weird... I think you're supposed to only use the `name` of the NEG when creating the network endpoint. 

If you remove the `https://www.googleapis.com/compute/v1/projects/%s/zones/%s/networkEndpointGroups` part of the NEG identifier and add back the instance name does it work?

**Comment by wouterdegeus** [comment]
I don't see how the name is the problem here, it's clearly complaining about the instance attribute. It also managed to create properly using these attributes.

>  and add back the instance name does it work?

What instance name?
In case you missed it, this is for a hybrid connectivity endpoint group, the entire point of this exercise is to get (through interconnect) on-prem resources serving traffic, so there is no GCE instance involved. Only IP address and port combinations.

**Comment by slevenick** [comment]
Ah, so the problem is likely that the API sees the empty string for `instance` and attempts to validate it. If the instance wasn't specified you think the delete would work?

I think this should be tackled as part of #10040 as this is a currently unsupported use case
