### ISSUE TITLE
google_privateca_certificate_authority access_urls output lacks CRL url 

### ISSUE THREAD

**Issue by dmnfortytwo** [hashicorp/terraform-provider-google#10991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/consul v2.14.0
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.24.1
```

### Affected Resource(s)

* google_privateca_certificate_authority

### Terraform Configuration Files

```tf
resource "vault_generic_secret" "privateca-crl-url" {
  path      = "puppet-kv2/projects/${var.project}/common/privateca-crl-url"
  data_json = jsonencode({ "value" = google_privateca_certificate_authority.default.access_urls[0]["crl_access_url"] })
}
```

### Expected Behavior

I expect to have CRL URL put into my vault secret

### Actual Behavior

I get empty string there.

Here is how whole output looks like:
```
- ca_certificate_access_url: http://MY_SUPER_BUCKET.storage.googleapis.com/LONG_CERT_ID/ca.crt
  crl_access_url: ''

```

### Steps to Reproduce

1. `terraform apply`

**Comment by c2thorn** [comment]
This seems to have been addressed in `4.3.0`: https://github.com/hashicorp/terraform-provider-google/pull/10577
Please update your provider version and try it out.
