### ISSUE TITLE
Error creating FeatureMembership: diffs exist after apply: [Field Configmanagement.Version: got 1.10.1, want ]

### ISSUE THREAD

**Issue by stewartshea** [hashicorp/terraform-provider-google#10996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.77.0
+ provider registry.terraform.io/hashicorp/google-beta v3.77.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/integrations/github v4.13.0
```

### Affected Resource(s)

google_gke_hub_feature_membership.feature_member
- configmanagement

* google_XXXXX

### Terraform Configuration Files

*Not* Functioning Config

```tf
resource "google_gke_hub_feature_membership" "feature_member" {
  location = "global"
  feature = google_gke_hub_feature.feature.name
  membership = google_gke_hub_membership.lab.membership_id
  configmanagement {
    config_sync {
      git {
        sync_repo = github_repository.acm.ssh_clone_url
        sync_branch = "main"
        secret_type = "ssh"
        policy_dir = "./acm"
      }
    }
    policy_controller {
      enabled                    = true
      template_library_installed = true
      referential_rules_enabled  = true
    }
  }
  provider = google-beta
}
```

*Functioning Config* - Specify v1.10.0 explicitly since 1.10.1 is causing the issue
 
```tf
resource "google_gke_hub_feature_membership" "feature_member" {
  location = "global"
  feature = google_gke_hub_feature.feature.name
  membership = google_gke_hub_membership.lab.membership_id
  configmanagement {
    version = "1.10.0"
    config_sync {
      git {
        sync_repo = github_repository.acm.ssh_clone_url
        sync_branch = "main"
        secret_type = "ssh"
        policy_dir = "./acm"
      }
    }
    policy_controller {
      enabled                    = true
      template_library_installed = true
      referential_rules_enabled  = true
    }
  }
  provider = google-beta
}
```

### Expected Behavior

Feature memebership should have been created. 

### Actual Behavior

Creation of the feature membership failed in terraform and partially completed in the GCP console. The following error was produced: 
```
Error creating FeatureMembership: diffs exist after apply: [Field Configmanagement.Version: got 1.10.1, want ]
   with google_gke_hub_feature_membership.feature_member,
│   on main.tf line 98, in resource "google_gke_hub_feature_membership" "feature_member":
│   98: resource "google_gke_hub_feature_membership" "feature_member" {
│ 
```

### Steps to Reproduce

Create a new GKE hub membership without explicitly specifying a version, which will default to the latest (1.10.1 as of yesterday). 

1. `terraform apply`

**Comment by slevenick** [comment]
b/217451754

**Comment by melinath** [comment]
This should now be resolved.
