### ISSUE TITLE
Support for Cloud Resource Manager Settings

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#11016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
You can now [set an expiry](https://cloud.google.com/iam/docs/service-accounts#key-expiry) time for all newly created service account keys in your project, folder, or organization. Expiry time can be done setting up `settings/iam-serviceAccountKeyExpiry` in  Resource Manager setting. Terraform provider support will help automating this task with project or folder deployment. 

### New or Affected Resource(s)

* google_resource_manager_settings

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* [Resource Manager Settings](https://cloud.google.com/resource-manager/docs/resource-settings/manage-resource-settings)

**Comment by rileykarson** [comment]
API reference: https://cloud.google.com/resource-manager/docs/reference/resource-settings/rest

**Comment by nstogner** [comment]
Going to take a stab at this

**Comment by nstogner** [comment]
Trying to generate `api.yaml` for resource settings API. I am trying to use `tools/builder` in magic modules to do this. I am getting errors, can someone point me in the right direction?

```sh
$ ruby tools/builder/run.rb -p resourcesettings -u 'https://resourcesettings.googleapis.com/$discovery/rest?version=v1' -o GoogleCloudResourcesettingsV1Setting && cat api.yaml
Traceback (most recent call last):
        6: from tools/builder/run.rb:45:in `<main>'
        5: from /Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:244:in `product'
        4: from /Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:220:in `resources'
        3: from /Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:220:in `map'
        2: from /Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:220:in `each'
        1: from /Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:223:in `block in resources'
/Users/nick/work/GoogleCloudPlatform/magic-modules/mmv1/tools/builder/api.rb:190:in `resource': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by rileykarson** [comment]
I don't think `tools/builder` works- it was written in some spare cycles by a former team member and committed, and worked at the time for an extremely limited use case, but wasn't supported past that. Roughly the same is true for `tools/doc-parser`.

The discovery documents don't have enough information to be useful past basic structure of the resource, in practice, so any similar tool will save a little bit of time typing and copy-pasting, but not a significant amount of actual development time.

**Comment by nstogner** [comment]
In the [resourcesettings API](https://cloud.google.com/resource-manager/docs/reference/resource-settings/rest), the Settings resource can be applied at the project, folder, and org level. Trying to follow existing conventions in the tf provider here. I see two options:

1. Create separate terraform resources for each parent type: `google_project_resource_settings`, `google_folder_resource_settings`, `google_organization_resource_settings`. This is similar to [google_project_iam](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam).
2. Create a single terraform resource `google_resource_settings` with a `parent` field that contains a string with the parent type in it (example: `projects/<project/settings/<id>`). This is similar to [google_folder](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder).

I am leaning towards option 1. Any preferences here?

**Comment by rileykarson** [comment]
Based on the shape of the API (where they are represented as split up) I'd lean towards 1 as well. We haven't set a strict standard here, and either would be accepted by our team- the decision falls on the implementer.

**Comment by imrannayer** [comment]
It is now possible using [org policy constraint [constraints/iam.serviceAccountKeyExpiryHours](https://cloud.google.com/iam/docs/service-account-creds#key-expiry)
