### ISSUE TITLE
Rate Limiting Rules - Security Policy 

### ISSUE THREAD

**Issue by dawsonpaul** [hashicorp/terraform-provider-google#11014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Rate Limiting Rules made available within Security Policy creation

Rate Based Throttling and Rate Based Bans added to resource_compute_security_policy.go

[Rate Based Throttling](https://cloud.google.com/armor/docs/configure-security-policies#rate-limiting-throttling)
[Rate Based Bans](https://cloud.google.com/armor/docs/configure-security-policies#rate-limiting-bans)

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
#Throttling Rule Potential
  rule {

    action      = "throttle"
    description = "rate limiting rule"
    preview     = "false"
    priority    = "100"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = [
          "1.2.3.0/24",
        ]
      }
    }
    rateLimitOptions {
      conformaction = "allow"
      enforceonkey  = "IP"
      exceedaction  = "deny(429)"
      rateLimitThreshold {
        count       = "100"
        intervalsec = "60"
      }

    }

  }

#Banning Rule Potential
rule {
  
  action = "rate_based_ban"
  description = "rate based banning rule"
  kind = "compute_securityPolicyRule"
  match{
    config {
      srcIpRanges = "0.0.0.0/0"
      }
    versionedExpr = "SRC_IPS_V1"
  }
  preview = false
  priority = 102
  rateLimitOptions {
    banDurationSec= 600
    banThreshold{
      count = 500
      intervalSec = 600
      }
    conformAction = "allow"
    enforceOnKey = "ALL"
    exceedAction = "deny(429)"
    rateLimitThreshold{
      count = 20
      intervalSec = 60
    }
  }
}




```

### References

* #0000

**Comment by rileykarson** [comment]
I believe this duplicates https://github.com/hashicorp/terraform-provider-google/issues/10020, which was recently closed!
