### ISSUE TITLE
google_service_account_id_token example from docs not working

### ISSUE THREAD

**Issue by andrewrothstein** [hashicorp/terraform-provider-google#11011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
arothste@DESKTOP-KRMEID5:~/tf-gcloud-bug$ terraform --version
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.9.0
```
### Affected Resource(s)

* google_service_account_id_token

### Terraform Configuration Files

```tf
provider "google" {}

data "google_service_account_id_token" "oidc" {
  target_audience = "https://foo.bar/"
}

output "oidc_token" {
  value = data.google_service_account_id_token.oidc.id_token
}
```

### Expected Behavior

The same output as `gcloud auth print-identity-token`

### Actual Behavior

```
arothste@DESKTOP-KRMEID5:~/tf-gcloud-bug$ terraform plan
╷
│ Error: error calling iamcredentials.GenerateIdToken: googleapi: got HTTP response code 404 with body:
│
│   with data.google_service_account_id_token.oidc,
│   on main.tf line 3, in data "google_service_account_id_token" "oidc":
│    3: data "google_service_account_id_token" "oidc" {
│
╵
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

```
# logged in as an Owner of the account
arothste@DESKTOP-KRMEID5:~/tf-gcloud-bug$ gcloud auth list
      Credentialed Accounts
ACTIVE  ACCOUNT
*       andrew.rothstein@gmail.com
```

### References

* #0000

**Comment by slevenick** [comment]
Is your Terraform authenticated with GCP using either a service account or application default credentials? See https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials

I'm able to use the provided config to get a token and output it.

**Comment by andrewrothstein** [comment]
I followed the instructions and did the `gcloud auth application-default login`

**Comment by slevenick** [comment]
Can you create other resources from within the this Terraform config? Just to make sure that everything is authenticated correctly?

**Comment by andrewrothstein** [comment]
Yes I can and have created other resources from within this Terraform config. `gcloud auth print-identity-token` produces the token correctly. I'm doing something so obviously wrong I can't see it.

**Comment by rileykarson** [comment]
I think you're authenticated as a user account, while this retrieves the id of a service account. It can infer the SA when using JSON creds, but not gcloud ones. You'll need to use https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account_id_token#target_service_account the specify the account you want an id token for.

I forget exactly what differentiates an id and access token offhand, but https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config#access_token may be closer to what you want. That returns a token for the identity Terraform is authenticated as.

**Comment by edwardmedia** [comment]
@andrewrothstein closing this assuming it is no longer an issue. Feel free to reopen if you have the answer
