### ISSUE TITLE
`google_project_service` should not return until underlying API is enabled

### ISSUE THREAD

**Issue by ace-n** [hashicorp/terraform-provider-google#11020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.7
on darwin_amd64
```
### Affected Resource(s)

* `google_project_service` (with `artifactregistry.googleapis.com`)

### Terraform Configuration Files
Here's a snippet from my Terraform config file.
```tf
data "google_project" "main" {
  project_id = var.google_ops_project_id
}

resource "google_project_service" "artifactregistry" {
  service = "artifactregistry.googleapis.com"
  project = data.google_project.main.project_id
  # Artifact Registry is only available in the Beta provider.
  provider = google-beta
}

resource "google_artifact_registry_repository" "website_docker" {
  format        = "DOCKER"
  location      = var.region
  repository_id = "website"
  project       = data.google_project.main.project_id
  provider      = google-beta

  depends_on = [
    # BUG: this does not work on a **brand-new** project
    # WORKAROUND: use `time_sleep` to add a 10-second delay
    google_project_service.artifactregistry
  ]
}

```

### Debug Output

https://gist.github.com/ace-n/4c01175fbc17be0efe460d3f25f85a71

### Expected Behavior

1) `google_artifact_registry_repository` should have an implicit dependency on the associated `google_project_service`
2) `google_project_service` should not be marked complete until the underlying API has been fully enabled

### Actual Behavior

Though the first item may well be the case already, the lack of the second results in race conditions. The race conditions can be identified by various mixtures of "resource not found" and/or "API not enabled" errors, both of which can be worked around by _adding a 10 second delay via `time_sleep`_ as a dependency of `google_artifact_registry_repository`.

### Suggested Fix

`google_project_service` resources should not be marked "complete" until the underlying API is _actually_ enabled.

**Comment by slevenick** [comment]
Unfortunately, my answer will be similar to https://github.com/hashicorp/terraform-provider-google/issues/11023.

We cannot tell when an API is *actually* enabled in Terraform. We can issue the request to enable an API, and the API will return a success, but that doesn't mean the API is fully enabled & propagated across the system. From Terraform we can't tell how long it will take for it to be fully enabled. We could theoretically implement some kind of polling/wait for X successful requests to an arbitrary endpoint before returning, but that would likely cause more problems than it solves.

As we don't have a way to handle this in the provider I'll close this

**Comment by ace-n** [comment]
@slevenick thanks for clarifying!

This seems like something the API management folks could address.

Bearing that in mind: would you mind reopening this issue, or creating an (internal) bug against that team?

Thanks!
