### ISSUE TITLE
Add enable_binary_authorization option to google_composer_environment 

### ISSUE THREAD

**Issue by alexander-kondratiev-db** [hashicorp/terraform-provider-google#11027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently the Binary Authorization of the Kubernetes Engine Cluster that is created within the composer environment is set to **disabled** by default. For better security in large teams it is advisable to turn on the Binary Authorization.

Possible workarounds include:

1. Manually enabling the Binary Authorization by running: 
`gcloud container clusters update ${name_of_gke_cluster} --zone ${var.zone} --enable-binauthz`
_Problem_: Manual work defeats the purpose of terraform. Moreover, it might not be allowed by compliance regulations to set things manually. 

2. Using the terraform-google-gcloud module to run the above command.
_Problem_: The module would require service account credentials which can not simply be given due to compliance regulations.

3. Using a VM instantiated via terraform that has the cloud console enabled to run the command.
_Problem_: Running a VM or similar for the purpose of a single line of code is inefficient in terms of building and pricing.

### New or Affected Resource(s)

* google_composer_environment
* enable_binary_authorization 

### Potential Terraform Configuration

Something along the lines of the following code snippet (line 10, it's within the node_config). It might be interesting to configure different nodes with or without Binary Authorization but not sure if that is of interest.

```tf
resource "google_composer_environment" "test" {
  name   = "example-composer-env"
  region = "us-central1"
  config {
    node_count = 4

    node_config {
      zone         = "us-central1-a"
      machine_type = "n1-standard-1"
      enable_binary_authorization = true

      network    = google_compute_network.test.id
      subnetwork = google_compute_subnetwork.test.id

      service_account = google_service_account.test.name
    }

    database_config {
      machine_type = "db-n1-standard-2"
    }

    web_server_config {
      machine_type = "composer-n1-webserver-2"
    }
  }
}
```

**Comment by rileykarson** [comment]
This would need to be supported by the API to get supported as a field in Terraform.
