### ISSUE TITLE
google_compute_security_policy - Rules with 'expr' block being re-created unnecessarily 

### ISSUE THREAD

**Issue by KB30497** [hashicorp/terraform-provider-google#11034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.4
on windows_amd64
provider registry.terraform.io/hashicorp/google v4.8.0

### Affected Resource(s)

* google_compute_security_policy

### Terraform Configuration Files

```tf
resource "google_compute_security_policy" "policy" {
  name = "my-policy"
  rule {
    action   = "deny(403)"
    priority = "1000"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["192.0.2.1/32"]
      }
    }
    description = "Test Rule #1 (Config)"
  }
  rule {
    action   = "deny(403)"
    priority = "2000"
    match {
      expr {
        expression = "evaluatePreconfiguredExpr('xss-stable')"
      }
    }
    description = "Test Rule #2 (Expr)"
  }
  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "default rule"
  }
}
```

### Expected Behavior

Modifying the configuration of the first rule (priority 1000) should only re-create that specific rule
```tf
  rule {
    action   = "deny(403)"
    priority = "1000"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["192.0.2.1/32","192.0.2.2/32"]
      }
    }
    description = "Test Rule #1 (Config)"
  }
```
### Actual Behavior

The second rule (priority 2000) is being re-created with the same configuration
```tf
~ resource "google_compute_security_policy" "policy" {
	name        = "my-policy"
	# (3 unchanged attributes hidden)

	+ rule {
	  + action      = "deny(403)"
	  + description = "Test Rule #1 (Config)"
	  + preview     = (known after apply)

	  + priority    = 1000

	  + match {
		  + versioned_expr = "SRC_IPS_V1"

		  + config {
			  + src_ip_ranges = [
				  + "192.0.2.1/32",
				  + "192.0.2.2/32",
				]
			}
		}
	}
	- rule {
	  - action      = "deny(403)" -> null
	  - description = "Test Rule #1 (Config)" -> null
	  - preview     = false -> null
	  - priority    = 1000 -> null

	  - match {
		  - versioned_expr = "SRC_IPS_V1" -> null

		  - config {
			  - src_ip_ranges = [
				  - "192.0.2.1/32",
				] -> null
			}
		}
	}
	- rule {
	  - action      = "deny(403)" -> null
	  - description = "Test Rule #2 (Expr)" -> null
	  - preview     = false -> null
	  - priority    = 2000 -> null

	  - match {

		  - expr {
			  - expression = "evaluatePreconfiguredExpr('xss-stable')" -> null
			}
		}
	}
	+ rule {
	  + action      = "deny(403)"
	  + description = "Test Rule #2 (Expr)"
	  + preview     = false
	  + priority    = 2000

	  + match {

		  + expr {
			  + expression = "evaluatePreconfiguredExpr('xss-stable')"
			}
		}
	}
	# (1 unchanged block hidden)
}
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This only happens with Cloud Armor policies using 'expression' rules, policies with only IP-based rules do not have the issue.

**Comment by melinath** [comment]
I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9084
