### ISSUE TITLE
Add support for Wildcard SSL certs via Certificate Manager which google have now added

### ISSUE THREAD

**Issue by BuckinghamIO** [hashicorp/terraform-provider-google#11037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Recently google added support for Wildcard certificates via their certificate manager under the beta api, I was curious to know if this is in the pipeline or just raise it as a feature to be added as I currently believe the resource is blocking this as it does not expect wildcards to be accepted by the API.

Google blog post: https://cloud.google.com/blog/products/identity-security/simplify-saas-scale-tls-certificate-management

Looks as if GA issuer is the primary auth with Lets encrypt being the secondary which will take over if Wildcards are requested from what I can gather.

I would be interested to know if this will be on the cards to be added soon or if this feature is too new to implement yet?

### New or Affected Resource(s)

resource "google_compute_managed_ssl_certificate"

### Potential Terraform Configuration

```tf
resource "google_compute_managed_ssl_certificate" "wildcard-managed-certificate" {
  name = "wildcard-managed-certificate-${local.environment}"

  managed {
    domains = ["*.my-domain.com"]
  }
}
```

### References

* #0000

b/312697155

**Comment by rileykarson** [comment]
@BuckinghamIO does this fail if specified currently? I don't think we validate those strings, so it should be possible at the Terraform layer

**Comment by BuckinghamIO** [comment]
> 

It does yes, the response is the following. I've assumed this is TF validation but I could be wrong:

`[1m[31mError: [0m[0m[1mError creating ManagedSslCertificate: googleapi: Error 400: Invalid value for field 'resource.managed.domains[0]': '*.qa-keylabs.com'. Wildcard domains not supported., invalid[0m`

**Comment by eriksw** [comment]
@rileykarson This is not an upstream issue. The initial issue may have been unclear, but this is an entirely new service/api: https://cloud.google.com/certificate-manager/docs/reference/rpc

The existing resource is interacting with the compute api, which presumably won't ever support wildcard managed certs—this provider needs to add resources for the new service/api. There's new concepts involved like certificate maps, etc...

**Comment by MoinTom** [comment]
@eriksw yes we would need new resources to define `DnsAuthorization`, `Certificate`, `CertificateMap` and `CertificateMapEntry`.

I guess a possible first step would be to add the possibility to define `certificateMap` ([targetHttpsProxies-API](https://cloud.google.com/compute/docs/reference/rest/beta/targetHttpsProxies/insert)) for `google_compute_target_https_proxy` resources. As of right now it's not possible to create a certificate map (by hand as described here: [Deploy a Google-managed certificate](https://cloud.google.com/certificate-manager/docs/deploy-google-managed)) and attach it to a `target-https-proxies` via terraform.

**Comment by smehboub** [comment]
@MoinTom Thank you very much for your work. 

Do you know when your pr would be merge ? 

Thanks in avance.
Rgs,

**Comment by smehboub** [comment]
> @eriksw yes we would need new resources to define `DnsAuthorization`, `Certificate`, `CertificateMap` and `CertificateMapEntry`.
> 
> I guess a possible first step would be to add the possibility to define `certificateMap` ([targetHttpsProxies-API](https://cloud.google.com/compute/docs/reference/rest/beta/targetHttpsProxies/insert)) for `google_compute_target_https_proxy` resources. As of right now it's not possible to create a certificate map (by hand as described here: [Deploy a Google-managed certificate](https://cloud.google.com/certificate-manager/docs/deploy-google-managed)) and attach it to a `target-https-proxies` via terraform.

@MoinTom Thank you very much for your work. 

Do you know when your pr mentioned would be merge ? 

Thanks in avance.
Rgs,

**Comment by MoinTom** [comment]
@smehboub I am waiting more or less on feedback. I still have a few questions about some of my changes. 
However i should still improve my test coverage and maybe add one example that works with the new `certificate_map` field .

**Comment by tjun** [comment]
Hi, I found Certificate Manager resources were added before🤔 
https://github.com/hashicorp/terraform-provider-google/pull/9540/files

And removed.
https://github.com/hashicorp/terraform-provider-google/pull/9562/files

Is it possible to restore these changes?

**Comment by alen-z** [comment]
Looking forward for Certificate Manager integration.

**Comment by imrannayer** [comment]
Is there an ETA for this?

**Comment by tjun** [comment]
released with 4.22.0?
https://github.com/hashicorp/terraform-provider-google/blob/e2a76cd9cf0ea484e43a200eb2a2226ebe1f528c/CHANGELOG.md#4220-may-24-2022

**Comment by Sytten** [comment]
@tjun No this is only the certificate manager itself, see the draft PR above for the integration with the load balancer.

**Comment by MoinTom** [comment]
My PR is currently a bit stuck, since i am unable to write a test for the added `certificate_map` (`compute_target_https_proxy`), due to missing `CertificateMap` and `CertificateMapEntry` resources. The newly released `google_certificate_manager_certificate` and `google_certificate_manager_dns_authorization` resources, aren't sufficient for the usage with a load balancer.

I am currently quite occupied and won't have enough time to look into that. However maybe one of you likes to tackle `CertificateMap` and `CertificateMapEntry` for us :)

**Comment by pawel-grz-krawczyk** [comment]
`CertificateMap` and `CertificateMapEntry` were added 3 days ago: https://github.com/GoogleCloudPlatform/magic-modules/pull/6203

**Comment by gcp-3223** [comment]
Is this issue still open or has it been addressed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6447 ?

**Comment by fbozic** [comment]
I've managed to issue a wildcard cert, assign it to the cert map and attach that cert map to HTTPs LB. All done with Terraform.

**Comment by alen-z** [comment]
Seems to still be missing `certificate_map` in `google_compute_region_target_https_proxy` (regional) GLB, like there is in `google_compute_target_https_proxy` (global) GLB.

**Comment by zs-codex** [comment]
> I've managed to issue a wildcard cert, assign it to the cert map and attach that cert map to HTTPs LB. All done with Terraform.

@fbozic would you be able to include a working example code block of your terraform resources?

**Comment by fbozic** [comment]
> > I've managed to issue a wildcard cert, assign it to the cert map and attach that cert map to HTTPs LB. All done with Terraform.
> 
> @fbozic would you be able to include a working example code block of your terraform resources?

@zs-codex Yeap sure. I have that spread across two modules (one for wildcard cert, one for GCLB) while cert map and cert map entry are standalone resources. I use a patched Google GCLB HTTP module because they do not support yet certificate_map. Here is an issue and you can see how to patch it: https://github.com/terraform-google-modules/terraform-google-lb-http/issues/267


Wildcard cert module, only `main.tf`. The module outputs `certificate_id`.
```
resource "google_certificate_manager_dns_authorization" "domain" {
  project = var.project_id
  name    = "${var.name}-dns-authorization"
  domain  = var.domain
}

resource "google_dns_record_set" "authorization_record" {
  project      = var.project_id
  name         = google_certificate_manager_dns_authorization.domain.dns_resource_record[0].name
  type         = "CNAME"
  ttl          = 30
  managed_zone = var.managed_zone_name
  rrdatas      = [google_certificate_manager_dns_authorization.domain.dns_resource_record[0].data]
}

resource "google_certificate_manager_certificate" "certificate" {
  project = var.project_id
  name    = "${var.name}-wildcard-certificate"
  scope   = "DEFAULT"
  managed {
    domains = [
      google_certificate_manager_dns_authorization.domain.domain,
      "*.${google_certificate_manager_dns_authorization.domain.domain}",
    ]
    dns_authorizations = [
      google_certificate_manager_dns_authorization.domain.id,
    ]
  }

  depends_on = [
    google_dns_record_set.authorization_record
  ]
}
```

Creation of wildcard module and addition to cert map.
```
module "wildcard_certificate" {
  source = "../../modules/gcp-wildcard-certificate-0.0.0"

  project_id        = local.current_project
  name              = "gcp"
  domain            = local.managed_zone_domain
  managed_zone_name = local.managed_zone_name
}

resource "google_certificate_manager_certificate_map" "emissary_public_lb" {
  name        = "emissary-public-lb-cert-map"
  description = "Emissary ingress public LoadBalancer certificate map"
}

resource "google_certificate_manager_certificate_map_entry" "emissary_public_lb_gcp_wildcard" {
  name         = "emissary-public-lb-gcp-wildcard-cert-map-entry"
  map          = google_certificate_manager_certificate_map.emissary_public_lb.name
  certificates = [module.wildcard_certificate.certificate_id]
  hostname     = "*.${local.managed_zone_domain}"
}
```

Now that you have certificate_map you should be able to attach it to your GCLB. Here is only https proxy snipet from GCLB module. 
```
resource "google_compute_target_https_proxy" "default" {
  project = var.project
  count   = var.ssl ? 1 : 0
  name    = "${var.name}-https-proxy"
  url_map = local.url_map

  certificate_map  = var.use_certificate_map ? "https://certificatemanager.googleapis.com/v1/${var.certificate_map}" : null
  ssl_certificates = !var.use_certificate_map ? compact(concat(var.ssl_certificates, google_compute_ssl_certificate.default.*.self_link, google_compute_managed_ssl_certificate.default.*.self_link, ), ) : null
  ssl_policy       = var.ssl_policy
  quic_override    = var.quic ? "ENABLE" : null
}
```

Hope this helps. 

Side note:
If you have worked with AWS ACM in the past, the DNS authorization resource will halt terraform execution until a certificate is validated and active. GCP works differently, terraform apply is fast and it doesn't wait for a certificate to become ACTIVE. You can still provision everything in one go, but it is not as intuitive as AWS ACM provisioning is.

**Comment by sorenhansendk** [comment]
> @alen-z: Seems to still be missing certificate_map in google_compute_region_target_https_proxy (regional) GLB, like there is in google_compute_target_https_proxy (global) GLB.

I don't think certificates generated by the Certificate Manager is supported by the regional load balancers.

> Certificate Manager lets you acquire and manage Transport Layer Security (TLS) (SSL) certificates for use with the following load balancer types in Google Cloud:
> 
> External HTTP(S) load balancer (Classic) supports target HTTPS proxies and target SSL proxies.
> Global external HTTP(S) load balancer only supports target HTTPS proxies.

Please check out this documentation: https://cloud.google.com/certificate-manager/docs/overview

**Comment by alen-z** [comment]
@sorenhansendk you're right. Been some time since I've checked that reference in documentation (forgotten) — I've suspected the same feature should be available for regional GLB. Based on this, no Terraform resource expected for sure. All good.

**Comment by hallvors** [comment]
Trying to do something very close to https://github.com/hashicorp/terraform-provider-google/issues/11037#issuecomment-1362628852 with the normal Terraform Google provider (current version 4.48.0) with a configuration where I'm already using classic load balancer-provisioned certificates, I get an error message saying the HTTPS proxy must have either `certificate_map` or `ssl_certificates`. When I enable tracing, I see that although Terraform is trying to apply a configuration where `certificate_map` is added, it appears to try to delete `ssl_certificates` first, causing backend to respond with this error.

I'm not sure if this should be reported as a separate bug.. This issue is still open although the feature seems released (though maybe with some imperfections? :) )

**Comment by rootsher** [comment]
@fbozic I have an external domain ([domains.google](https://domains.google/)), I have my own dns zone configured, records set up in it (A, CAA, CNAME), and my server names point to this created zone. Below is the code that implements this:
```tf
// ./infrastructure/terraform/domain/dns/main.tf
locals {
  dns_name              = "${var.cli.domain}."
  record_a_rrdatas      = [var.module_domain_k8s.config.ip]
  record_caa_rrdatas    = ["0 issue \"letsencrypt.org\"", "0 issue \"pki.goog\""]
  dns_resource_record_0 = var.module_domain_security.ssl.dns_authorization.dns_resource_record[0]

  records = [
    { name = "*.${local.dns_name}", type = "A", ttl = 3600, rrdatas : local.record_a_rrdatas },
    { name = local.dns_name, type = "A", ttl = 3600, rrdatas : local.record_a_rrdatas },
    { name = "*.${local.dns_name}", type = "CAA", ttl = 300, rrdatas : local.record_caa_rrdatas },
    { name = local.dns_name, type = "CAA", ttl = 300, rrdatas : local.record_caa_rrdatas },
    { name = local.dns_resource_record_0.name, type = "CNAME", ttl = 300, rrdatas : [local.dns_resource_record_0.data] }
  ]
}

resource "google_dns_managed_zone" "dns_zone" {
  name        = "dns-zone"
  description = "DNS zone"
  dns_name    = local.dns_name

  dnssec_config {
    state = "on"
  }
}

resource "google_dns_record_set" "dns_record" {
  for_each = {
    for index, record in local.records : "${index}.${record.type}" => record
  }

  name         = each.value.name
  type         = each.value.type
  ttl          = each.value.ttl
  managed_zone = google_dns_managed_zone.dns_zone.name
  rrdatas      = each.value.rrdatas
}

// ./infrastructure/terraform/domain/security/ssl/main.tf
resource "google_certificate_manager_certificate" "certificate" {
  name = "certificate"

  managed {
    domains = [
      var.cli.domain,
      "*.${var.cli.domain}",
    ]

    dns_authorizations = [
      google_certificate_manager_dns_authorization.dns_authorization.id
    ]
  }
}

resource "google_certificate_manager_dns_authorization" "dns_authorization" {
  name   = "dns-authorization"
  domain = var.cli.domain
}

// ./infrastructure/terraform/domain/security/ssl/output.tf
output "certificate" {
  value = google_certificate_manager_certificate.certificate
}

output "dns_authorization" {
  value = google_certificate_manager_dns_authorization.dns_authorization
}
```
**I have a question for everyone - how can I connect the current configuration to Ingress? Below is its configuration:**
```tf
resource "kubernetes_ingress_v1" "gke_ingress_gateway" {
  wait_for_load_balancer = true

  metadata {
    name      = "gateway"
    namespace = var.config.namespace
    annotations = {
      # This annotation can be set only when external https balancer is fully programmed.
      # "kubernetes.io/ingress.allow-http"       = false
      "networking.gke.io/managed-certificates" = var.module_domain_security.ssl.certificate.name // <-- NOT WORKING
    }
  }

  spec {
    rule {
       .....
    }
  }
}
```
I tried various annotations, but still without success. I don't see any possibility to connect via Ingress at the moment. Maybe you @fbozic see any possibility?

PS. Feel free to use my code snippet - I hope there will be someone to which I have solved a problem :)

**Comment by fbozic** [comment]
@rootsher I'm pretty sure you can not do that. GCP Ingress is quite opinionated and supports a very small subset of features. 
But I can recommend an alternative maybe. You can provision LB with terraform and use [autoneg controller](https://github.com/GoogleCloudPlatform/gke-autoneg-controller) to populate the backend service.

**Comment by romans-ovo** [comment]
> @sorenhansendk you're right. Been some time since I've checked that reference in documentation (forgotten) — I've suspected the same feature should be available for regional GLB. Based on this, no Terraform resource expected for sure. All good.

Looks use of `certificate_map` is now supported for regional internal and external load balancer (https://cloud.google.com/certificate-manager/docs/overview) - but the feature is marked as `Preview`

**Comment by roaks3** [comment]
Note: I'm forwarding this to the service team to confirm, but I believe as-written, this issue is now fixed.

**Comment by melinath** [comment]
Based on the discussion above and internally, this seems to be completed. See documentation on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/certificate_manager_certificate and https://cloud.google.com/certificate-manager/docs/deploy-google-managed-dns-auth#terraform regarding usage. Thanks!
