### ISSUE TITLE
Support for routingPolicy in DNS Routing policies

### ISSUE THREAD

**Issue by kaushalringle** [hashicorp/terraform-provider-google#11038]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

How can I add DNS routing policies to `google_dns_record_set` for WRR routing policy which can be seen here https://cloud.google.com/dns/docs/zones/manage-routing-policies , Terraform resource only shows options for `rrdatas` here https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set#rrdatas. 

for eg I want add `routingPolicy` instead of `rrdatas` so the options like  weight can be added, snap of the API call looks like this 
```
"routingPolicy": {
        "wrr": {
          "item": [
            {
              "weight": .5,
              "rrdata": [
                "10.X.X.A"
              ]
            },
            {
              "weight": .5,
              "rrdata": [
                "10.X.X.B"
              ]
            }
          ]
        }
      }
```

### New or Affected Resource(s)

* google_dns_record_set

### Potential Terraform Configuration

Which would look something like this 
```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_dns_record_set" "a" {
  name         = "backend.${google_dns_managed_zone.prod.dns_name}"
  managed_zone = google_dns_managed_zone.prod.name
  type         = "A"
  ttl          = 300

  routingPolicy = {
        "wrr": {
          "item": [
            {
              "weight": .5,
              "rrdata": [
                "10.X.X.A"
              ]
            },
            {
              "weight": .5,
              "rrdata": [
                "10.X.X.B"
              ]
            }
          ]
  }
}

resource "google_dns_managed_zone" "prod" {
  name     = "prod-zone"
  dns_name = "prod.mydomain.com."
}
```

### References

Google Docs --> https://cloud.google.com/dns/docs/zones/manage-routing-policies 
Terraform Resource --> https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set#adding-an-a-record

* [Internal issue](http://b/225902325)

**Comment by rileykarson** [comment]
Note: Our implementation of this resource is not based on the `ResourceRecordSet` API, so this may required a new resource. @c2thorn to investigate.

**Comment by c2thorn** [comment]
This field is only available via the `v1beta1` or `v2beta1` versions of the DNS client library. Right now, both `google` and `google-beta` providers use the `v1` version, so implementing this would require extensive testing to make sure the `google-beta` version does not break users. Otherwise, it should be possible via the same resource

**Comment by erikjoh** [comment]
Hi!
Looks like `routingPolicy` is now available in `v1`.
https://cloud.google.com/dns/docs/reference/v1/resourceRecordSets
In addition to `routingPolicy.wrr` we would be interested in `routingPolicy.geo` as well (and I assume that field would also be supported).

**Comment by rosmo** [comment]
I'd suggest a more Terraform'y approach:

```
routing_policy {
  wrr {
    item {
      rrdatas = [ "10.X.X.A" ]
      weight = 0.5
    }
    item {
      rrdatas = [ "10.X.X.B" ]
      weight = 1.0
    }
  } 
  geo {
    item {
      rrdatas = [ "10.X.X.C" ]
      weight = 1.0
    }
  } 
}
```

**Comment by ms185570** [comment]
Would this issue also cover the geo-based option for DNS records?

**Comment by kanata2** [comment]
I'm working on this issue at https://github.com/GoogleCloudPlatform/magic-modules/pull/5909.
 Please feel free to comment if you have any input on the implementation.
