### ISSUE TITLE
Failing test(s): TestAccComposerEnvironment_UpdateComposerV2 (could not successfully initialize the Airflow database)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11077]
### Affected Resource(s)

* google_composer_environment

Failure rate: 22.9% from Dec 24 2021 to Feb 9 2022 (48 days)

Impacted tests:
- TestAccComposerEnvironment_UpdateComposerV2

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=2679961116525026753

Message:

```
Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 9, message: Your environment could not complete its creation process because it could not successfully initialize the Airflow database. This can happen when the GKE cluster is unable to reach the SQL database over the network.
```

**Comment by rileykarson** [comment]
Note: We believe these Airstream issues are upstream issues

**Comment by AlfatahB** [comment]
TestAccComposerEnvironment_UpdateComposerV2
    [Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=2679961116525026753&tab=testDetails) - 10.1% failure
    [Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=2679961116525026753&tab=testDetails) - 10% failure

**Comment by AlfatahB** [comment]
b/261824843
