### ISSUE TITLE
Failing test(s): Os Policy Assignment: operation not done

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11070]
### Affected Resource(s)

* google_os_config_os_policy_assignment

Failure rate:
- ~0.6% in Jan 2022
- 55.6% in Feb 2022

Impacted tests:
- TestAccOsConfigOsPolicyAssignment_FixedOsPolicyAssignment
- TestAccOsConfigOsPolicyAssignment_PercentOsPolicyAssignment

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=7114228571965012755

Message:

```
Error: Error updating OSPolicyAssignment: operation not done.
```

**Comment by rileykarson** [comment]
@slevenick to forward to DCL if appropriate / unassign otherwise

**Comment by roaks3** [comment]
This appears to be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7012
