### ISSUE TITLE
Failing test(s): TestAccApigeeInstance_apigeeInstanceIpRangeTestExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11071]
### Affected Resource(s)

* google_apigee_instance

Failure rate:
- 100% since Jan 22 2022 (previously 100% for other reasons)
- Still 100% Jun 16 2022

Impacted tests:
- TestAccApigeeInstance_apigeeInstanceIpRangeTestExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=-1518294496116307382

Message:

```
Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 2, message: Error in allocating IPs to use for the Instance. Please verify the network configuration provided for the Instance and try again.
```

**Comment by melinath** [comment]
Still 100%

**Comment by AlfatahB** [comment]
TestAccApigeeInstance_apigeeInstanceIpRangeTestExample
    [Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-1518294496116307382&tab=testDetails) - 100% failure
    [Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=-1518294496116307382&tab=testDetails) - 100% failure

**Comment by AlfatahB** [comment]
b/261817856

**Comment by roaks3** [comment]
Note that this occurred on the first run in our new project, and this error only ever seems to be present on this specific test, so it seems unlikely to be due to resources accumulating in some way over time.

**Comment by roaks3** [comment]
This appears to be an issue with the configuration for the `ip_range` feature, which I am not fully clear on. https://cloud.google.com/apigee/docs/api-platform/get-started/install-cli#service-networking has some more info that I'm working through, but it appears there is some issue with the way we are reserving IPs, either with the network connection, or the apigee instance.

So far, I've tried using `prefix_length = 16`, to provide the network connection with more IP space, which did not work. Next I'm trying to replace the hard-coded `"10.87.8.0/22"` to see if that is the issue.
