### ISSUE TITLE
Failing test(s): TestAccAppEngineFlexibleAppVersion_update

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11073]
### Affected Resource(s)

* google_app_engine_flexible_app_version

Failure rate: 100% since 

Impacted tests:
- TestAccAppEngineFlexibleAppVersion_update

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=7385344304796565941

Message:

```
Error: Error uploading object requirements.txt: googleapi: Error 403: Project 'project_number:<number>' not found or deleted.
```

Possibly related to https://github.com/hashicorp/terraform-provider-google/issues/11072

**Comment by sanghaniJ** [comment]
TestAccAppEngineFlexibleAppVersion_update

[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=7385344304796565941&tab=testDetails) - 69.7% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=7385344304796565941&tab=testDetails) - 72% failure

**Comment by sanghaniJ** [comment]
b/261838329

**Comment by roaks3** [comment]
This issue appears to have been resolved
