### ISSUE TITLE
Feature Request: Anthos Configuration Management

### ISSUE THREAD

**Issue by Voidwalker0x79** [hashicorp/terraform-provider-google#11083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I think adding the GCP anthos API to the GCP terraform provider would be widely beneficial. Various teams are leveraging the Anthos Configuration Management service to have standardized GKE deployments across organizational folders/projects. 

### New or Affected Resource(s)

* google_anthos_configuration_register

### Potential Terraform Configuration

```tf
resource google_anthos_configuration_register {
   cluster_names = [data.google_container_cluster.name]
    project_ID = "<project_id>"
}
```

### References

* #0000

**Comment by slevenick** [comment]
Hey @0xvoidw can you point me at the API that is used for this feature?
