### ISSUE TITLE
public_access_prevention documentation missing

### ISSUE THREAD

**Issue by mans0954** [hashicorp/terraform-provider-google#11088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
terraform -v
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.10.0
+ provider registry.terraform.io/hashicorp/google-beta v4.10.0
```

### Affected Resource(s)

* `google_storage_bucket`
### Terraform Configuration Files
```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google-beta"
      version = "4.10.0"
    }
  }
}

resource "google_storage_bucket" "bucket" {
  name = "csh-test-pap"
  location = "us-east1"
  project = "****"
  public_access_prevention = "enforced"
}
```

### Expected Behavior

I would expect the `public_access_prevention` parameter to be documented in the latest docs:
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/storage_bucket

Also, I would expect this feature to be in the (non-beta) google provider since the corresponding `gsutil pap` commands don't have the `beta` label.

### Actual Behavior

The `public_access_prevention` parameter does not appear in the documentation, yet it works in practice:
```
gsutil pap get gs://csh-test-pap
gs://csh-test-pap: enforced
```

### Steps to Reproduce

1. `terraform apply`

### References

#9519
https://github.com/hashicorp/terraform-provider-google-beta/pull/3919

**Comment by husseyd** [comment]
Ahoy - I was looking to use this toggle and only confirmed it was available in TF by finding this issue!
Please add it to the docs

**Comment by ekhaydarov** [comment]
When is this due to come out of beta?
