### ISSUE TITLE
"terraform-google-modules/gcloud/google" module not invoking destroy entrypoint (and body)

### ISSUE THREAD

**Issue by crandall-chow-bl** [hashicorp/terraform-provider-google#11103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

In an attempt to use the [terraform-google-modules/gcloud/google](https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest) module to build out some GCP resources using the `gcloud` CLI, I've come across odd behavior where it's not calling my custom destroy entrypoint.  For example, if I add a stanza to create my GCP resource, the `create_cmd_entrypoint` and body are called to build the resource, great!  If I then were to change the TF configuration for that module, it should replace the resource by calling the custom `destroy_cmd_entrypoint` first (set up in the previous apply) followed by calling `create_cmd_entrypoint` again to recreate the resource.  Creates are doing as expected, calling the configured entrypoint, but destroys are not.  The `.tfstate` data is indeed created and destroyed as expected, but the custom entrypoints are never getting invoked.

### Terraform Version
Terraform v1.1.5
on darwin_amd64

### Affected Resource(s)
terraform-google-modules/gcloud/google
3.1.0

### Terraform Configuration Files
```tf
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.90.0"
    }
  }
}

provider "google" {
  region      = "us-central1"
  project     = "my-xxx"
  credentials = "my-xxx-account.json"
}

# comment out the module below after "create" to get TF to "destroy"
module "my_xxx_tester" {
  source  = "terraform-google-modules/gcloud/google"
  version = "3.1.0"

  create_cmd_endpoint = "gcloud"
  create_cmd_body        = "version"
  destroy_cmd_body      = "gcloud"
  destroy_cmd_body       = "version"
}
```

### Debug Output
https://gist.github.com/crandall-chow-bl/b5a427c276f6c2c6be0d402304affe53

### Panic Output
n/a

### Expected Behavior
On "destroy" the configured `destroy_cmd_entrypoint` and `destroy_cmd_body` should be invoked, similar to what happens on create, where the `create_cmd_entrypoint` and `create_cmd_body` are clearly invoked.  (I'm using `gcloud version` as a simple example here. In my actual code, I'm calling a shell script.)

### Actual Behavior
The resource in the `.tfstate` is deleted, but the configured `destroy_cmd` entrypoint and body are not invoked.

### Steps to Reproduce
1. `terraform apply` with the TF file above to "create"
2. Comment out the module in the TF file
3. `terraform apply" with the TF file above to "destroy"
4. Note that the destroy entrypoint/body do not get invoked

### Important Factoids
n/a

### References
n/a

**Comment by rileykarson** [comment]
I'd suggest filing a bug against that repo instead! Our team doesn't work on it and afaik no `google` provider resources are in use.
