### ISSUE TITLE
Add automated notifications for downstream builder failures

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#11107]
When the downstream builder fails, the maintainers should be automatically notified in some way (email, chatbot, etc). This is likely to be done directly in cloud build..

**Comment by rileykarson** [comment]
Note: DCL is interested in this as well, and may solve it / piggyback on our solution (fyi @SirGitsalot)

**Comment by shuyama1** [comment]
Set up a chat alert that automatically notify the maintainers for downstream build failures using [Google Chat notifier](http://github.com/GoogleCloudPlatform/cloud-build-notifiers/tree/master/googlechat). More info: https://cloud.google.com/build/docs/configuring-notifications/configure-googlechat
