### ISSUE TITLE
Adaptive_Protection to be enabled via TF, says complete but does not enable.

### ISSUE THREAD

**Issue by azaadrin** [hashicorp/terraform-provider-google#11120]
Every time I run plan/apply it lists the block below, states the policy was changed. however adaptive protection never gets enable, and every time I run plan it shows the same thing.

+ adaptive_protection_config ***
          + layer_7_ddos_defense_config ***
              + enable          = true
              + rule_visibility = "PREMIUM"
            ***
        ***

For reference, if enabled via console, then I get the following block during every apply
+ adaptive_protection_config ***
          + layer_7_ddos_defense_config ***
              + rule_visibility = "PREMIUM"
            ***
        ***

**Comment by rogierlommers** [comment]
Watching this; since we're facing the same issue.
