### ISSUE TITLE
google_secret_manager_secret_iam_member fails to save state when adding a conditional iam role

### ISSUE THREAD

**Issue by michyliao** [hashicorp/terraform-provider-google#11127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
`Terraform v0.14.11`

### Affected Resource(s)

* google_secret_manager_secret_iam_member

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret_iam_member" "secret_manager_iam_additive" {
  project   = PROJECT_ID
  secret_id = SECRET_KEY
  role      = "roles/iam.securityReviewer"
  member    = "group:XXX@mail.com"
  condition {
    title       = "XXXXXX"
    description = "XXXXXX"
    expression  = "request.time < timestamp(\"2022-03-01T00:00:00Z\")"
  }
}
```

### Expected Behavior

Successful resource applied.

### Actual Behavior
```bash
Error: Provider produced inconsistent result after apply

When applying changes to
module.XXXXXX,
provider "registry.terraform.io/hashicorp/google" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

After I had ran apply and it returned the error posted above, I've verified if that permissions was added or not. I ran the following and can confirm the permission was applied even though terraform return an error report.

```bash
gcloud secrets get-iam-policy SECRET_KEY
bindings:
- condition:
    description: XXXXX
    expression: request.time < timestamp("2022-03-01T00:00:00Z")
    title: XXXXXX
  members:
  - group:XXX@mail.com
  role: roles/iam.securityReviewer
etag: XXXXX
version: 3
```

I've also upgraded to the latest google provider and tried google-beta

b/322602060

**Comment by rileykarson** [comment]
These issues typically point towards capitalization issues, more than anything else- we've got a few fields that we consider the "identity" of the resource and do raw comparisons between those to identify the resource. If the API has transformed their values, we don't find a match and Terraform removes the resource from state. That results in this error.

I've got a pretty limited ability to help without debug logs, which you're likely not comfortable to post here due to principals being email addresses. If you're able to review them on your own, they should indicate what we aren't finding a match for; the fields of note are the `condition` (incl. subfields), `member`, and `role`. The first one I'd investigate personally would be the `condition.0.expression`.

**Comment by michyliao** [comment]
I've verified the same inputs with `google_project_iam_member` with the same inputs i had for `google_secret_manager_secret_iam_member`
```
resource "google_secret_manager_secret_iam_member" "secret_manager_iam_additive" {
  project   = PROJECT_ID
  secret_id = SECRET_KEY
  role      = "roles/iam.securityReviewer"
  member    = "group:XXX@mail.com"
  condition {
    title       = "XXXXXX"
    description = "XXXXXX"
    expression  = "request.time < timestamp(\"2022-03-01T00:00:00Z\")"
  }
}
```
And was successful for the `google_project_iam_member` creation, whereas the `google_secret_manager_secret_iam_member` still failed. I figured I double check the expression format on the project level vs the secret resource level. 

Here are the debug logs from the apply of `google_secret_manager_secret_iam_member` - https://gist.github.com/michyliao/9d0420b6f776279a3c55db174a0b5b91

**Comment by rileykarson** [comment]
Unusual- the API seems to be transforming the role. You're sending the following and getting it back on first response:

```
---[ REQUEST ]---------------------------------------
POST /v1/projects/PROJECT_ID/secrets/SECRET_ID:setIamPolicy?alt=json HTTP/1.1
Host: secretmanager.googleapis.com
User-Agent: Terraform/0.14.11 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/dev
Content-Length: 320
Content-Type: application/json
Accept-Encoding: gzip

{
 "policy": {
  "bindings": [
   {
    "condition": {
     "description": "description",
     "expression": "request.time \u003c timestamp(\"2022-03-01T00:00:00Z\")",
     "title": "conditional_binding_example"
    },
    "members": [
     "group:valid@email.com"
    ],
    "role": "roles/secretmanager.viewer"
   }
  ],
  "etag": "REDACTED",
  "version": 3
 }
}

-----------------------------------------------------: timestamp=2022-02-18T09:05:11.862-0800
2022-02-18T09:05:12.108-0800 [INFO]  plugin.terraform-provider-google-beta_v4.11.0_x5: 2022/02/18 09:05:12 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 18 Feb 2022 17:05:12 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "version": 3,
  "etag": "REDACTED",
  "bindings": [
    {
      "role": "roles/secretmanager.viewer",
      "members": [
"group:valid@email.com"
      ],
      "condition": {
        "expression": "request.time \u003c timestamp(\"2022-03-01T00:00:00Z\")",
        "title": "conditional_binding_example",
        "description": "description"
      }
    }
  ]
}
```

But then, a later GET returns it shaped differently:

```
---[ REQUEST ]---------------------------------------
GET /v1/projects/PROJECT_ID/secrets/SECRET_ID:getIamPolicy?alt=json HTTP/1.1
Host: secretmanager.googleapis.com
User-Agent: Terraform/0.14.11 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/dev
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-02-18T09:05:13.110-0800
2022-02-18T09:05:13.264-0800 [INFO]  plugin.terraform-provider-google-beta_v4.11.0_x5: 2022/02/18 09:05:13 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 18 Feb 2022 17:05:13 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "version": 1,
  "etag": "REDACTED",
  "bindings": [
    {
      "role": "roles/secretmanager.viewer_withcond_XXXXXXXXX",
      "members": [
"group:valid@email.com"
      ]
    }
  ]
}
```

I noticed that we aren't sending a policy version on the Get request, using the https://cloud.google.com/secret-manager/docs/reference/rest/Shared.Types/GetIamPolicyRequest#GetPolicyOptions parameter. So while the initial request is at `v3` (when conditions were added), the later Get is at `v1,` which represents the resource differently.

I'm gonna double-check with a teammate who was working on similar version-related work, as this may tie in w/ preexisting work or will need a fairly broad fix.

**Comment by michyliao** [comment]
Hey @rileykarson , I was wondering if there has been any update with fixing the feature?

**Comment by DannyPat44** [comment]
Would love this to be fixed!

**Comment by fathom-parth** [comment]
Is there a workaround for assigning conditional iam bindings to a specific secret?

**Comment by michyliao** [comment]
Hey @rileykarson , following up on this bug!

**Comment by LucaPrete** [comment]
I'm on this. I might have found a solution. Testing... can you please assign it to me in the meantime?

**Comment by fathom-parth** [comment]
Fwiw, we've found a workaround by using project-level bindings and using IAM conditions to narrow the scope of the permissions to the particular `Secret` + `SecretVersion`.
