### ISSUE TITLE
google_filestore_instance resource - Could be great if the documentation about the beta options can be improved. 

### ISSUE THREAD

**Issue by peatonet** [hashicorp/terraform-provider-google#11139]
### Terraform Version
$ terraform -v
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google-beta v4.11.0

### Affected Resource(s)
google_filestore_instance

#### versions.tf
terraform {
  required_version = ">= 1.1.6"
  required_providers {
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~>4.11.0"
    }
  }
}

#### main.tf
resource "google_filestore_instance" "instance" {
  provider    = google-beta
...
...

### Issue Description
I was getting the below error trying to use the 'nfs_export_options' block:

user@os:~/filestore/provider-test$ terraform plan
╷
│ Error: Unsupported block type
│ 
│   on main.tf line 22, in resource "google_filestore_instance" "instance":
│   22:     nfs_export_options {
│ 
│ Blocks of type "nfs_export_options" are not expected here.

Then, I noticed that we have to add this line to set again the beta provider inside the resource definition:

resource "google_filestore_instance" "instance" {
  provider    = google-beta
...
...

So adding the beta provider here in the required_providers block it's not enough, and could be great if we can add it to the documentation (the explanation, not just the line of code in the "Example Usage - Filestore Instance Full" [1]) to avoid confusion.

terraform {
  required_version = ">= 1.1.6"
  required_providers {
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~>4.11.0"
    }
  }
}

------
[1]: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_instance#example-usage---filestore-instance-full

**Comment by slevenick** [comment]
I don't believe we want to add the `terraform` block to examples. It ends up being a significant amount of duplicated information, especially as most of the information contained in that block is very environment specific. We don't want to give the impression that the provider only works with >= 1.1.6 of Terraform for example
