### ISSUE TITLE
Add support for shared VPC architecture in google_dataproc_cluster resource

### ISSUE THREAD

**Issue by josephmilla** [hashicorp/terraform-provider-google#11135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the module `google_dataproc_cluster` doesn't support a shared VPC architecture wherein a network could be hosted in a completely different project than the dataproc cluster itself. 
  
### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
cluster_config {
    gce_cluster_config {
      zone = "us-central1-a"

      # One of the below to hook into a custom network / subnetwork
      network    = google_compute_network.dataproc_network.name
      subnetwork = google_compute_network.dataproc_subnetwork.name
      
      # Specify the host project. If not specified, use the current project
      network_host_project = xxx

      tags = ["foo", "bar"]
    }
  }
```

In `cluster_config.gce_cluster_config`, there should be an additional parameter where you could specify the host project for the network (perhaps something like `network_host_project`).

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster#nested_gce_cluster_config

**Comment by rileykarson** [comment]
@josephmilla: Are you able to specify a full self-link for `network`, or is the `project` field required by the API? (Sorry, don't have the docs pulled up as I write this 🙂 )

**Comment by roaks3** [comment]
It looks like you can specify these fields with a full self-link instead of just the name (https://cloud.google.com/dataproc/docs/reference/rest/v1/ClusterConfig#GceClusterConfig), which should support the use of networks in other projects.

Closing because this has been in a waiting state for a while, and most likely can be resolved by using self-link.
