### ISSUE TITLE
Add storage_location for google_compute_image

### ISSUE THREAD

**Issue by caieo** [hashicorp/terraform-provider-google#11148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add `storage_location` to `google_compute_image`. [Google API REST documentation here](https://cloud.google.com/compute/docs/reference/rest/v1/images). Looking at the [resource documentation](https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images#create_image), it looks like this field should help specify where the user wants the image to be stored. 

We had a customer run into the following error message while trying to create a ComputeImage, and determined that it might be due to this missing field. 
```
Error creating Image: googleapi: Error 412: Location us violates constraint constraints/gcp.resourceLocations on the resource projects/prj-prd-security-tools/global/images/dev-ops-rhel7-blnk-img-autmn-001., conditionNotMet
```

### New or Affected Resource(s)

* google_compute_image

**Comment by Yannic** [comment]
Sent #11257
