### ISSUE TITLE
Unsupported argument with "google_app_engine_application" and database_type

### ISSUE THREAD

**Issue by clive-h-townsend** [hashicorp/terraform-provider-google#11162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.5.0
+ provider registry.terraform.io/hashicorp/google-beta v4.11.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
### Affected Resource(s)

* google_app_engine_application

### Terraform Configuration Files

```
variable "project_name" {
  default = "asdfasdf-test-"
}

resource "random_id" "id" {
  byte_length = 4
  prefix      = var.project_name
}


terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.5.0"
    }
  }
}

provider "google" {
  credentials = file("terraform-sa-cred.json")

}

provider "google-beta" {
  credentials = file("terraform-sa-cred.json")
}

resource "google_folder" "testing" {
  display_name = "Testing"
  parent       = "organizations/12818XXXXXXX"
}

resource "google_project" "project" {
  name            = random_id.id.hex
  project_id      = random_id.id.hex
  folder_id       = google_folder.testing.name
  billing_account = "XXX-XXX-XXXX-1A2B"
}

resource "google_app_engine_application" "app" {
  project     = google_project.project.project_id
  location_id = "us-central"
  database_type = "CLOUD_FIRESTORE"
}
```

### Debug Output

https://gist.github.com/clive-h-townsend/913acafab8983912e707ced2cb572c17

### Expected Behavior

Create an app engine with Cloud Firestore

### Actual Behavior

Erroro

### Steps to Reproduce

1. `terraform apply`
2. Get error

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_application#database_type

**Comment by ScottSuarez** [comment]
It looks like you're using an old version of the provider `provider.terraform-provider-google_v3.5.0`

Could you update to a more current instance and retry?

**Comment by clive-h-townsend** [comment]
Hi @ScottSuarez : That worked. Thanks so much for the quick response. I might recommend updating: https://learn.hashicorp.com/tutorials/terraform/google-cloud-platform-build?in=terraform/gcp-get-started#write-configuration

Thanks so much! Please close.

**Comment by ScottSuarez** [comment]
Happy to help !

@rileykarson @megan07 , I'm not sure we can change the documentation/tutorial as pinning the version is important for stability of the tutorial.
