### ISSUE TITLE
Add `redirect` rule.action for google_compute_security_policy

### ISSUE THREAD

**Issue by caieo** [hashicorp/terraform-provider-google#11160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies 
ComputeSecurityPolicy has a `redirect` rule.action that should be a supported action. 

### New or Affected Resource(s)

* google_compute_security_policy 

### References

* https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/612

**Comment by roaks3** [comment]
I think this was actually resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/5691. The `action` field used to include client-side validation to only allow certain values (which did not include `redirect`), but that validation has been removed.
