### ISSUE TITLE
google_cloud_identity_group_membership fails on membership validation

### ISSUE THREAD

**Issue by vponnam** [hashicorp/terraform-provider-google#11171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/google v4.11.0
+ provider registry.terraform.io/hashicorp/google-beta v4.11.0

### Affected Resource(s)

- google_cloud_identity_group_membership

### Terraform Configuration Files

```tf
resource "google_cloud_identity_group_membership" "cloud_identity_group_membership_basic" {

  group    = var.group_id

  preferred_member_key {
    id = "user@project.iam.gserviceaccount.com"
  }

  roles {
      name = "MEMBER"
  }
}
```

### Actual Behavior
1. Above resource adds member to the group.
2. Remove the service account from GCP, which will also remove the SA from cloud_identity_group
3. Running a TF plan fails as below

```
$ tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.google_service_account_access_token.default: Refreshing state... [id=projects/-/serviceAccounts/user@project.iam.gserviceaccount.com]
module.add_members_to_group.google_cloud_identity_group_membership.cloud_identity_group_membership_basic["user@project.iam.gserviceaccount.com"]: Refreshing state... [id=groups/{ID}/memberships/{ID}]

Error: Error when reading or editing CloudIdentityGroupMembership "groups/{ID}/memberships/{ID}": googleapi: Error 403: Error(2028): Permission denied for resource groups/{ID}/memberships/{ID} (or it may not exist).
```

### Steps to Reproduce

1. Use above resource to add a member to the group.
2. terraform apply 
3. Successful apply will add the SA to the group
4. Manually delete the SA from GCP, which will also remove the SA from cloud_identity_group
5. terraform plan/apply fails

### Important Factoids

- It is my understanding that [resourceCloudIdentityGroupMembershipRead](https://github.com/hashicorp/terraform-provider-google/blob/5e61d2b2f5ccd7926a4791d953e05597bc078334/google/resource_cloud_identity_group_membership.go#L229-L232) issues a GET call to list members, and when member no longer exist in the group(as deleting member from GCP also removes the member from group) terraform/client receives the below error.

```
googleapi: Error 403: Error(2028): Permission denied for resource groups/{ID}/memberships/{ID} (or it may not exist)
```
I understand it's not easy to distinguish between `403 - Permission denied` and `it may not exist`, but improving the provider level validation is required in using `google_cloud_identity_group_membership` resource for membership management.

### References
- https://cloud.google.com/identity/docs/how-to/memberships-google-groups#listing_memberships_of_a_google_group

**Comment by ScottSuarez** [comment]
Does your service account you are using have the authority to manage this resource?

This sounds like an ACL issue.

**Comment by vponnam** [comment]
@ScottSuarez Yes, the SA/Identity used by TF has the necessary permissions to manage groups(for testing I assigned groups admin role to the SA). Updated `Steps to Reproduce`, so #3 works fine, meaning the SA/Identity used by the TF has necessary permissions, but #5 fails.

**Comment by danninov** [comment]
I've encountered this bug too. Terraform plan fail when the cloud identity member removed outside terraform. Need to manually remove member from tfstate.

**Comment by ScottSuarez** [comment]
>  understand it's not easy to distinguish between 403 - Permission denied and it may not exist

It's actually not possible to distinguish these scenarios. Unfortunately if it was bad actors could try to detect resource allocations.

Could you perhaps post a debug stack if possible using TF_LOG=DEBUG

**Comment by JRolfe-Gen** [comment]
Still a bug - It can't be that hard to reproduce yourself.

**Comment by ScottSuarez** [comment]
This is an issue where the underlying API returns a 403 instead of a 404, so Terraform isn't able to do much. I'd suggest filing an issue at [cloud.google.com/support/docs/issue-trackers](https://cloud.google.com/support/docs/issue-trackers), and linking that issue here so that the provider maintainers can keep track as well.

[issuetracker.google.com/issues/new?component=356842&template=0](https://issuetracker.google.com/issues/new?component=356842&template=0).

**Comment by chalmagr** [comment]
> This is an issue where the underlying API returns a 403 instead of a 404, so Terraform isn't able to do much. I'd suggest filing an issue at [cloud.google.com/support/docs/issue-trackers](https://cloud.google.com/support/docs/issue-trackers), and linking that issue here so that the provider maintainers can keep track as well.
> 
> [issuetracker.google.com/issues/new?component=356842&template=0](https://issuetracker.google.com/issues/new?component=356842&template=0).

Seems there was no traction here and really need this to be done... so I've created an issue - I am unable to see the component mentioned earlier... hopefully this is good as well

https://issuetracker.google.com/issues/238667783

**Comment by rileykarson** [comment]
@ScottSuarez: For some APIs it's correct to return a 403 instead of a 404, I'll share internal guidance on a related thread. A brief summary of that guidance is that an API should return a 404 if a user has permission to determine the existence of the resource, and a 403 otherwise. For most project-scoped resource, a user who can make calls against the project will always have permission to determine the existence of resources in the project. That's what influenced our default behaviour- treat a 404 like a resource doesn't exist, and a 403 like an error.

However, for APIs that are org-scoped or lie in custom scopes, it's much more likely that 403s mean the same thing as 404 and we should treat them the same. See https://github.com/hashicorp/terraform-provider-google/pull/1900 for what I'd imagine is a similar case to this one.

**Comment by roaks3** [comment]
Whoops, this one isn't crosslinked yet, but I had started on it with the internal ticket:

b/223239823
