### ISSUE TITLE
Getting 403 when getting IAM policy (example from the docs)

### ISSUE THREAD

**Issue by ep4sh** [hashicorp/terraform-provider-google#11186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.8.0
+ provider registry.terraform.io/hashicorp/google-beta v4.8.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/vault v3.2.1

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* google_storage_bucket
* google_iam_policy
* google_storage_bucket_iam_policy

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "my_storage" {
  name     = "storage"
  location = "EU"

  website {
    main_page_suffix = "index.html"
    not_found_page   = "404.html"
  }
}


data "google_iam_policy" "admin" {
  binding {
    role = "roles/storage.admin"
    members = [
      "user:jane@example.com",
    ]
  }
}

resource "google_storage_bucket_iam_policy" "policy" {
  bucket = google_storage_bucket.default.name
  policy_data = data.google_iam_policy.admin.policy_data
}
```

### Panic Output

module.mymodule.google_storage_bucket_iam_policy.policy: Creating...
╷
│ Error: Error when reading or editing Resource "storage bucket \"b/my_storage\"" with IAM Policy: Error retrieving IAM policy for storage bucket "b/my_storage": googleapi: Error 403: <REDACTED> does not have storage.buckets.getIamPolicy access to the Google Cloud Storage bucket., forbidden

### Expected Behavior

All resources are created 

### Actual Behavior

Terraform throws 403 error, then I must remove all resources from the state manually to cleanup.

### Steps to Reproduce

1. `terraform apply`

### References

All resources are created from the documentation page:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam#google_storage_bucket_iam_policy

In GCP I do have full (owner) permissions

* #0000

**Comment by shuyama1** [comment]
Hi @ep4sh!  Looks like the `owner` role does not have the `storage.buckets.getIamPolicy` permission (https://cloud.google.com/storage/docs/access-control/iam-roles#basic-roles-intrinsic). Would you mind try granting the `storage.admin` role to your account and see if that works?

**Comment by shuyama1** [comment]
Closing this issue. Please feel free to reopen it if this issue happens again!
