### ISSUE TITLE
The requested URL ... managedZones ... was not found on this server

### ISSUE THREAD

**Issue by black-snow** [hashicorp/terraform-provider-google#11198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.12.0
+ provider registry.terraform.io/hashicorp/google-beta v4.12.0
```

I also checked 4.11 and 4.10.

### Affected Resource(s)

`google_dns_managed_zone`

### Terraform Configuration Files

```
resource "google_dns_managed_zone" "private-dns-zone" {
  project     = google_project.project.id
  name        = "internal-shared-zone"
  dns_name    = "int."
  description = ""

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = google_compute_network.vpc.id
    }
  }
}
```

### Debug Output

Sorry, I cannot provide the full output at this point.

```
  # module.networking.google_dns_managed_zone.private-dns-zone will be created
  + resource "google_dns_managed_zone" "private-dns-zone" {
      + description   = ""
      + dns_name      = "int."
      + force_destroy = false
      + id            = (known after apply)
      + name          = "internal-shared-zone"
      + name_servers  = (known after apply)
      + project       = "projects/xxx"
      + visibility    = "private"

      + private_visibility_config {
          + networks {
              + network_url = "projects/xxx/global/networks/xxx"
            }
        
```

### Panic Output

Again, sorry for posting the output here. But it's not much and hopefully the issue is easy to spot.

```
module.networking.google_dns_managed_zone.private-dns-zone: Creating...
╷
│ Error: Error creating ManagedZone: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-rep
eat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/go
oglelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.
google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100%
 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/dns/v1/projects/projects/xxx/managedZones?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
│
```

### Expected Behavior

DNS zone created.

### Actual Behavior

DNS zone not created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I had the zone created before. TF had to delete it because the project ID changed from the project name to the project ID (project/X instead of just X) but now it fails to recreate it.

**Comment by black-snow** [comment]
Weird, it works with `project = google_project.x.name` but not with it's ID, although the docs state:

> The ID of the project in which the resource belongs. If it is not provided, the provider project is used.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone#project

**Comment by shuyama1** [comment]
Hi @black-snow! Could you try using `google_project.project.project_id` instead of `google_project.project.id` and see if that works, as `id` is an identifier for the project with the format `projects/{{project}}`, while `project_id` is the real project ID we usually talk about. I know they are confusing sometimes. Sorry about that!

**Comment by black-snow** [comment]
@shuyama1 that did the trick, thanks for the hint!
