### ISSUE TITLE
Required 'compute.globalAddresses.list' permission for 'projects/xxxxx'

### ISSUE THREAD

**Issue by stefaneacsu** [hashicorp/terraform-provider-google#11195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.78.0
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1

### Affected Resource(s)

* .google_service_networking_connection.google_psa

### Terraform Configuration Files

```tf
resource "google_compute_global_address" "private_ip_alloc" {
  for_each      = var.private_service_access
  project       = var.project
  network       = var.network
  name          = each.key
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  address       = each.value.ip_address
  prefix_length = each.value.prefix
}

resource "google_service_networking_connection" "google_psa" {
  for_each                = var.private_service_access
  network                 = var.network
  service                 = each.value.service
  reserved_peering_ranges = [google_compute_global_address.private_ip_alloc[each.key].name]
}
```

### Debug Output

```tf
{
 "name": "operations/pssn.p24-419629503507-5ce6d340-59c5-4364-8afb-26f7219e8c97",
 "done": true,
 "error": {
  "code": 7,
  "message": "Required 'compute.globalAddresses.list' permission for 'projects/419629503507'\nHelp Token: Ae-hA1NQrQ_NJK42JWXOAMu6Z7NQdDWd-hOC4qMsgaSbh3Y7jGZYc3RSDJ4WD0xOD6gP13Kdi3lN7jidHDh20znI5WnRy9YAy326HiHDGKHxvSk0",
  "details": [
   {
    "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
    "violations": [
     {
      "type": "googleapis.com",
      "subject": "120002"
     }
    ]
   },
   {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "reason": "COMPUTE_IO_EXTERNAL",
    "domain": "servicenetworking.googleapis.com"
   }
  ]
 }
}

```

### Expected Behavior

Work as intended

### Actual Behavior

Fails even though I have permissions set up incorrect place. I searched and looked in the documentation on what roles contain the following permissions and I found the following ones:
```shell
  "roles/compute.networkAdmin",
        "roles/compute.networkViewer",
        "roles/compute.instanceAdmin.v1",
        "roles/compute.viewer"
```

In this situation since I added networkAdmin and networkViewer and it still did not work, also tried to add all of them to the specific project in order to make it work and to no avail.

I am not sure exactly what is the problem VPC Peering works fine, NAT, etc only the Private Service Connection fails from UI side and also in Terraform as well.

### Steps to Reproduce

1. `terraform apply`

**Comment by slevenick** [comment]
Your service networking connection doesn't specify the project it's under, so it is inheriting the default value. Is that the same as `var.project`? This is likely not a Terraform bug, but a mixup in your configuration/project/IAM settings

**Comment by stefaneacsu** [comment]
@slevenick yes, I did not include all the Terraform code but it's in the correct project. The other infrastructure is set up in the correct project.

**Comment by slevenick** [comment]
Can you look at the debug logs for the failing request and make sure it is hitting the right project? Unfortunately I don't think there is much for us to do from the provider side here, this is clearly a permissions error coming from the API, and if the Terraform resource is acting on the correct project then the error is most likely correct.

If Terraform was attempting to call extra APIs in the project or use an incorrect project then we could fix that, but it appears to be trying to do the right thing.

You note that: "Private Service Connection fails from UI side and also in Terraform as well." does this mean creating the service networking connection from the UI fails?

**Comment by stefaneacsu** [comment]
Hey, the project was correct. It was an issue that even though I had enabled the Service Networking API the SA was not attributed with the Service Networking Service Agent role.

I re-enabled the service and disabled and now everything is fine.

**Comment by slevenick** [comment]
Reopening for workaround documentation

**Comment by betsy-lichtenberg** [comment]
The Data Guy has posted an article with a workaround. I personally tried it, and confirmed that it worked in my project. Here is the article: https://thedataguy.in/cloudsql-shared-vpc-private-ip-and-servicenetworking.serviceagent-role/

TL;DR: here is the workaround:

```
gcloud projects add-iam-policy-binding YOUR_HOST_PROJECT_NAME \
  --member=[serviceAccount:service-HOST_PROJECT_ACCOUNT_NUMBER@service-networking.iam.gserviceaccount.com](mailto:serviceAccount%3Aservice-HOST_PROJECT_ACCOUNT_NUMBER@service-networking.iam.gserviceaccount.com) \
  --role=roles/servicenetworking.serviceAgent
```
