### ISSUE TITLE
Update   google_cloud_scheduler_job documentation regarding App Engine dependency

### ISSUE THREAD

**Issue by marktru** [hashicorp/terraform-provider-google#11192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Scheduler with HTTP and PubSub targets no longer require the presence of an App Engine app and are no longer limited to being located in App Engine regions.  See https://cloud.google.com/scheduler/docs/schedule-run-cron-job for updated info.

The current doc ([https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job](https://www.google.com/url?q=https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job&sa=D&usg=AOvVaw08TJEVsC51ChaNpcAGZWkK)) incorrectly indicates that the GAE app is required.

### New or Affected Resource(s)

* google_cloud_scheduler_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* Internal issue: [http://b/221914654](http://b/221914654)

**Comment by rileykarson** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5764 (thanks @betsy-lichtenberg!)
