### ISSUE TITLE
Add support for RBD snapshots in google_redis_instance

### ISSUE THREAD

**Issue by pipyy** [hashicorp/terraform-provider-google#11197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is an option to enable RDB snapshots on redis instance: 
https://cloud.google.com/memorystore/docs/redis/rdb-snapshots
Settings are available in "persistenceConfig":
https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#persistenceconfig 

It would be great if this (preview) feature was supported, because we currently have redis instances defined in terraform which means we cannot enable persistence mode (it needs to be set at instance creation). 
Thanks!

**Comment by saifulwebid** [comment]
RDB snapshots are now in GA: https://cloud.google.com/memorystore/docs/redis/release-notes#August_03_2022, so would appreciate if this feature can be supported on this Terraform provider.

**Comment by melinath** [comment]
b/241977656

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6528
