### ISSUE TITLE
Add support for user_labels in google_monitoring_slo

### ISSUE THREAD

**Issue by matsr** [hashicorp/terraform-provider-google#11204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The [Service Level Objective resource](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives) in Cloud Monitoring API v3 has support for user labels. This is missing in the `google_monitoring_slo` Terraform resource in the Google provider.

### New or Affected Resource(s)

* google_monitoring_slo

### Potential Terraform Configuration

```tf
data "google_monitoring_app_engine_service" "default" {
  module_id = "default"
}

resource "google_monitoring_slo" "appeng_slo" {
  service = data.google_monitoring_app_engine_service.default.service_id

  slo_id = "ae-slo"
  display_name = "Terraform Test SLO for App Engine"

  goal = 0.9
  calendar_period = "DAY"

  user_labels = {
    foo = "bar"
  }

  basic_sli {
    latency {
      threshold = "1s"
    }
  }
}
```

### References

The `user_labels` argument was added to `google_monitoring_alert_policy` in 2019. Can something similar be done for `google_monitoring_slo`?

* #3494
* b/224637233

**Comment by sanghaniJ** [comment]
b/263759842

**Comment by sanghaniJ** [comment]
I've gone through this issue and the request is for supporting attribute `user_labels` in `google_monitoring_slo`. The [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6070) for the same has been merged. Hence, closing this issue ticket.
