### ISSUE TITLE
 google_dataproc_job panic in flatten/expand

### ISSUE THREAD

**Issue by tejavar** [hashicorp/terraform-provider-google#11212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
TF v1.0.3  
google v4.11.0
google-beta 4.11.0

### Affected Resource(s)

 google_dataproc_job

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output
This happens in the dataproc job and also in the workflow template, in both expand and flatten function for, for example, the logging config.

In short, providers shouldn't crash for any reason, but in this case it looks like the provider is struggling with what the service could be sending back. The issue is presenting itself in similar ways in other resources (this is -beta):

https://github.com/hashicorp/terraform-provider-google/issues/10280

What we know from the error is that:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
```

The provider is expecting there to be a map of strings and found nothing. That happens here, in code that hasn't been modified in 4 years:

https://github.com/hashicorp/terraform-provider-google/blame/master/google/utils.go#L323

What this code tells us is that there is an `m[0]`, but the contents of `m[0]` is `nil`. That call is coming from here, in code that again hasn't been modified in 4 years:

https://github.com/hashicorp/terraform-provider-google/blame/master/google/resource_dataproc_job.go#L541

What this tells us is that it pertains to the `logging_config` argument to the resource. The implication is that there is a logging config, but it's empty and therefore producing `nil`.

They might be able to work around this by changing the value of their logging_config argument in the resource configuration.

### Expected Behavior

The short version is that there appears to be a code generation issue in the google provider where an array/slice is checked for one entry (length == 0), and, if there is one, it is accessed. However, the entry is `nil` so the provider panics.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by slevenick** [comment]
Closing this as it should be fixed by the linked PRs
