### ISSUE TITLE
Add support for Composer image version aliases like composer-2

### ISSUE THREAD

**Issue by swalkowski** [hashicorp/terraform-provider-google#11217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Composer is adding support for Composer major version aliases within image version specification, like `composer-1` and `composer-2`. This will enable requesting a Cloud Composer 2 without specifying the full semantic version.

We should support these aliases in Terraform.

### New or Affected Resource(s)

* google_composer_environment

### Potential Terraform Configuration

```tf
resource "google_composer_environment" "test" {
  name   = "example-composer-env"
  region = "us-central1"
 
 config {
    software_config {
      image_version = "composer-2-airflow-2.2.3"
    }
  }
}
```

**Comment by swalkowski** [comment]
I have prepared a [code change](https://github.com/swalkowski/magic-modules/commit/0167647611068e6c15c70a74801487422fd2abe3) for this, will send out a PR soon.

**Comment by c2thorn** [comment]
Note to the TF team: It looks like this will be supported by the API, however we have some regex in the provider that would have blocked it. The regex will need to be updated at the very least.

**Comment by swalkowski** [comment]
I have updated the regexp in a few places in https://github.com/GoogleCloudPlatform/magic-modules/pull/5787 draft, please let me know if there is anything I've missed.
