### ISSUE TITLE
Support Managed Service for Prometheus

### ISSUE THREAD

**Issue by mbarrien** [hashicorp/terraform-provider-google#11224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP recently announce the general availability of [Google Cloud Managed Service for Prometheus](https://cloud.google.com/blog/products/devops-sre/easy-managed-prometheus-metrics-service-for-kubernetes). This is not yet supported in the Terraform provider. This is currently a beta feature (it uses the v1beta1 api), so I hope to see this in the Beta provider (if not the main one, if it is truly generally available).

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration
Following the structure that I see in the API at https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters (this can obviously be simplified)
```tf
resource "google_container_cluster" {
  monitoring_config {
    managed_prometheus {
      enabled = true
    }
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters

**Comment by loeffel-io** [comment]
Any update?
