### ISSUE TITLE
google_container_cluster.network_policy.provider PROVIDER_UNSPECIFIED is invalid network policy provider

### ISSUE THREAD

**Issue by kerma** [hashicorp/terraform-provider-google#11244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.6 on darwin_arm64

### Affected Resource(s)

* google_container_cluster.network_policy

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.12.0"
    }
}

resource "google_container_cluster" "primary" {
  # redacted
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "172.18.0.0/28"
  }
  network_policy {
    enabled = true
  }
  addons_config {
    network_policy_config {
      disabled = false
    }
  }
}
```

### Debug Output

https://gist.github.com/kerma/a8b7269f8ad310d9c12fbcf8dea754c8

### Expected Behavior

Successful apply.

### Actual Behavior

Error: googleapi: Error 400: Invalid network policy provider., badRequest

### Steps to Reproduce

1. Create a new cluster without `network_policy` block
1. Update cluster config to include `network_policy` block
1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_network_policy
* #10461
https://github.com/hashicorp/terraform-provider-google/blob/4d0739074109312947e965140afeb7068b309d7f/google/resource_container_cluster.go#L690-L697

---

Apply completes successfully with CALICO:

```tf
  network_policy {
    provider = "CALICO"
    enabled  = true
  }
```

**Comment by c2thorn** [comment]
Based on https://github.com/hashicorp/terraform-provider-google/issues/10461#issuecomment-961316920, I think the only course of action would be to move the default entirely, which is a breaking change.

**Comment by daniele-dynabase** [comment]
same here with Terraform v1.2.8

unfortunately adding the provider leads to the error message

`googleapi: Error 400: The network policy addon must be enabled before updating the nodes., badRequest`

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8965
