### ISSUE TITLE
Labels on snapshot_properties of google_compute_resource_policy cannot be updated in-place (or at all)

### ISSUE THREAD

**Issue by mponton-cn** [hashicorp/terraform-provider-google#11260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.13.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/vmware/vra v0.3.11

### Affected Resource(s)

* `google_compute_resource_policy`

### Terraform Configuration Files

```tf
# [...snip...]
resource "google_compute_resource_policy" "snapshot-policy" {
  provider = google.impersonated
  count    = (var.vm_enable_backups_os || var.vm_enable_backups_data) ? 1 : 0

  name    = "${var.vm_hostname}-snapshot-policy"
  region  = local.google_region
  project = data.google_projects.vm_project.projects[0].project_id

  snapshot_schedule_policy {
    schedule {
      weekly_schedule {
        day_of_weeks {
          day        = local.vm_final_backup_day
          start_time = var.vm_backup_time
        }
      }
    }
    retention_policy {
      max_retention_days = 60
      on_source_disk_delete = "APPLY_RETENTION_POLICY"
    }
    snapshot_properties {
      # NOTE: This line is the problem. Here "module.deployment_labels.labels" is simply a list of "standardized" labels.
      labels = module.deployment_labels.labels
      storage_locations = [local.vm_final_backup_location]
      guest_flush = var.vm_backups_use_vss
    }
  }
}
# [...snip...]
```

### Debug Output

I can't provide any at this time because I would have to sanitize it first but this can be easily reproduced and I am not sure debug output would provide anything useful that is not already here. Still, let me know if needed and I will create a simpler reproducer.

### Expected Behavior

`google_compute_resource_policy` provides a way through `snapshot_properties` to set labels on the disk snapshots of a VM. We'd expect to be able to _change_ these labels "in-place" so that information like charge-back codes can be updated simply and safely.

### Actual Behavior

After deployment, if you change one of the labels, Terraform will not do a in-place update but instead it will do a _REPLACE_ on the `google_compute_resource_policy` resources:

```
  # module.gcp_win_vm_minimal.google_compute_resource_policy.snapshot-policy[0] must be replaced
-/+ resource "google_compute_resource_policy" "snapshot-policy" {
      ~ id        = "projects/__PROJECT_ID__/regions/northamerica-northeast1/resourcePolicies/__VM_NAME__-snapshot-policy" -> (known after apply)
        name      = "__VM_NAME__-snapshot-policy"
      ~ region    = "https://www.googleapis.com/compute/v1/projects/__PROJECT_ID__/regions/northamerica-northeast1" -> "northamerica-northeast1"
      ~ self_link = "https://www.googleapis.com/compute/v1/projects/__PROJECT_ID__/regions/northamerica-northeast1/resourcePolicies/__VM_NAME__-snapshot-policy" -> (known after apply)
        # (1 unchanged attribute hidden)

      ~ snapshot_schedule_policy {


          ~ snapshot_properties {
              ~ labels            = { # forces replacement
                  ~ "some_label"      = "foo" -> "bar"
                    # (9 unchanged elements hidden)
                }
                # (2 unchanged attributes hidden)
            }
            # (2 unchanged blocks hidden)
        }
    }
```

Moreover this will fail:

```
    │ Error: Error when reading or editing ResourcePolicy: googleapi: Error 400: The resource_policy resource 'projects/__PROJECT_ID__/regions/northamerica-northeast1/resourcePolicies/
    ╵-snapshot-policy' is already being used by 'projects/__PROJECT_ID__/zones/northamerica-northeast1-a/disks/__VM_NAME__-datadisk-0', resourceInUseByAnotherResource
```

### Steps to Reproduce

1. Create a GCP project to deploy a VM, enable disk snapshots and set labels via the `snapshot_properties.labels` field of the `google_compute_resource_policy` resource.
2. `terraform apply`
3. Modify a label on the `snapshot_properties.labels` field of the `google_compute_resource_policy` resource
4. `terraform apply`

### Important Factoids

I'm unaware of anything special in our setup that would cause this issue. This can be reproduced from Windows and Linux hosts deploying both Windows and RHEL VMs in GCP.

**Comment by megan07** [comment]
Hi @mponton-cn, I'm sorry that you're running into this issue. I tried to reproduce it and was able to update the label. Unfortunately, there is no way to update the resource policy in place, so the resource policy will need to be destroyed and recreated. That being said, looking further into the error message (`resourceInUseByAnotherResource`), it seems as though your resource policy is currently in use, so Google will not allow it to be destroyed. I believe you'll need to unattach the resource policy first in order to update your labels. Let me know if that helps or if you're still having issues and we can look into it further then. Thanks!

**Comment by mponton-cn** [comment]
Hi @megan07, so if I understand correctly, the limitation is on the Google API side of things, not with the provider implementation. For us to update labels on a `google_compute_resource_policy` we'd be forced to detach it first and Terraform via the provider would then need to delete it and recreate it. Again, due to the underlying GCP API implementation.

We're working with both Google and Hashicorp right now and will bring up the issue with the proper vendor to see what they recommend. We're being asked to label all resources for our FinOps team (mainly) and this behavior breaks any update of labels (without us jumping through hoops first 😄 ).

I appreciate your help with this! Thanks for the prompt response and please let me know if I got this wrong.

**Comment by megan07** [comment]
@mponton-cn yes, that sounds correct. If there was a way to update it in place (via the API) we could do it on our end, but unfortunately I only see `insert`, `get` and `delete`: https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies

**Comment by mponton-cn** [comment]
@megan07 Thanks for the link. I'll reach out to the Google team about this. Curious to see if there is any interest to improve this endpoint and how they suggest we address the problem considering they are themselves pushing IaC practices. Again thank you for helping with this. I'll close this ticket since it is clearly not a provider issue. I'll update later if I have any feedback that may benefit others and should be included here or if the API is improved eventually. Cheers!
