### ISSUE TITLE
should port 43 be instead 443 for the firewall rule?

### ISSUE THREAD

**Issue by ibenrodriguez** [hashicorp/terraform-provider-google#11276]
https://github.com/hashicorp/terraform-provider-google/blob/3591fda41a38fa5fd0a5a669d28e862f11957301/examples/cloud-armor/main.tf#L44

should port 43 be instead 443 for the firewall rule?

**Comment by rileykarson** [comment]
We may want to delete the `examples` folder altogether in favour of some of the newer examples repositories under `terraform-google-modules`

**Comment by rileykarson** [comment]
Closing as stale
