### ISSUE TITLE
kms key no longer has self_link for google_compute_instance.boot_disk.kms_key_self_link 

### ISSUE THREAD

**Issue by k4leung4** [hashicorp/terraform-provider-google#11272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.13.0

### Affected Resource(s)

* google_compute_instance
* google_kms_crypto_key

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

```
resource "google_kms_key_ring" "keyring" {
  name     = "keyring-example"
  location = "global"
}

resource "google_kms_crypto_key" "example-key" {
  name            = "crypto-key-example"
  key_ring        = google_kms_key_ring.keyring.id
  rotation_period = "100000s"

  lifecycle {
    prevent_destroy = true
  }
}

resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  tags = ["foo", "bar"]

  boot_disk {
    kms_key_self_link = google_kms_crypto_key.example-key.self_link
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  // Local SSD disk
  scratch_disk {
    interface = "SCSI"
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral public IP
    }
  }

  metadata = {
    foo = "bar"
  }

  metadata_startup_script = "echo hi > /test.txt"

  service_account {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    email  = google_service_account.default.email
    scopes = ["cloud-platform"]
  }
}

```
### Debug Output

https://gist.github.com/k4leung4/2b0a26afd936fa45569bd8349eb92dd0

### Expected Behavior

A way to specify the KMS key to use with encrypting boot disk. 

### Actual Behavior

```
Error: Unsupported attribute
│ 
│   on main.tf line 29, in resource "google_compute_instance" "default":
│   29:     kms_key_self_link = google_kms_crypto_key.example-key.self_link
│ 
│ This object has no argument, nested block, or exported attribute named "self_link".
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

self_link was deprecated in the Google Terraform provider in release 4.0
https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_4_upgrade#resource-google_kms_crypto_key

### References

* #0000

**Comment by megan07** [comment]
@k4leung4 , I'm sorry for the confusion, can you please try `google_kms_crypto_key.example-key.id` and see if that works? Thanks!
