### ISSUE TITLE
GKE Maintenance exclusion scope

### ISSUE THREAD

**Issue by bcleenders** [hashicorp/terraform-provider-google#11274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We'd like to be able to specify scopes when specifying maintenance exclusion windows for GKE clusters.

The current Terraform config supports maintenance exclusion windows, but does not expose the `scope` field yet. Scopes are documented [here](https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions#scope_of_maintenance_to_exclude).

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
maintenance_policy {
  recurring_window {
    start_time = "2019-08-01T02:00:00Z"
    end_time = "2019-08-01T06:00:00Z"
    recurrence = "FREQ=DAILY"
  }

  maintenance_exclusion{
    exclusion_name = "holiday data load"
    start_time = "2019-05-01T00:00:00Z"
    end_time = "2019-05-02T00:00:00Z"

    # New - one of: no_upgrades / no_minor_upgrades / no_minor_or_node_upgrades.
    scope = "no_upgrades"
  }
}
```

### References

* #7214 adds support for maintenance windows
* [GKE docs on configuring Maintenance exclusion for an existing cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions#configuring_a_maintenance_exclusion)

Google partner issue tracker ID: 176226590
Internal TF issue: [http://b/226564350](http://b/226564350)

**Comment by 600lyy** [comment]
I'm working on this issue and the PR is at https://github.com/GoogleCloudPlatform/magic-modules/pull/5914.
Please feel free to comment if you have any opinion about the implementation.

Proposed Terraform Template:

```
maintenance_policy {
  recurring_window {
    start_time = "2019-08-01T02:00:00Z"
    end_time = "2019-08-01T06:00:00Z"
    recurrence = "FREQ=DAILY"
  }

  maintenance_exclusion{
    exclusion_name = "holiday data load"
    start_time = "2019-05-01T00:00:00Z"
    end_time = "2019-05-02T00:00:00Z"
    
    exclusion_options {
      #New - one of: no_upgrades / no_minor_upgrades / no_minor_or_node_upgrades.
      scope = "no_upgrades"
    }
  }
}
```

**Comment by thibaultserti** [comment]
It seems now that you can have a maximum of 20 maintenance exclusion (with always a max of 3 NO_UPGRADES) but the provider only support a maximum of 3.
https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions#exclusions


Is this why this PR is not closed ?

**Comment by bcleenders** [comment]
Will close the issue - the referenced PR resolved the issue for us.

If adding support for up to 20 maintenance exclusions is required by anyone, they can start a follow-up issue.

Thanks for adding this support! 💯
