### ISSUE TITLE
Dependency problem between alerts and metrics upon metric destroy

### ISSUE THREAD

**Issue by gnthibault** [hashicorp/terraform-provider-google#11289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

We are trying to setup a monitoring system on google cloud platform, within [google cloud operations](https://cloud.google.com/products/operations) framework. To do so, we rely on terraform enterprise to declare custom metrics ([google_monitoring_metric_descriptor](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_metric_descriptor)), as well as alert policies ([google_monitoring_alert_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy)).

However, whenever we decide to change the definition of one metric, it seems that the destroy/create policy in terraform does not take into account properly the dependencies between google_monitoring_alert_policy and google_monitoring_metric_descriptor, i.e google API returns an error when one tries to remove a metric, as some alert depends on it.

### Terraform Version
V1.1.5 on linux_amd64
regarding UI:
Terraform Enterprise v202112-2
© 2022 HashiCorp, Inc.

### Affected Resource(s)
* google_monitoring_metric_descriptor
* google_monitoring_alert_policy

### Terraform Configuration Files

A typical MWE configuration looks like this:

```tf
resource "google_monitoring_metric_descriptor" "with_alert" {
  description = "Daily sales records from all branch stores."
  project      =  PUT_YOUR_PROJECT_NAME_HERE
  display_name = "metric-descriptor"
  type = "custom.googleapis.com/stores/daily_sales"
  metric_kind = "GAUGE"
  value_type = "DOUBLE"
  unit = "{USD}"
  launch_stage = "BETA"
}
resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "metric-descriptor"
  project      = PUT_YOUR_PROJECT_NAME_HERE
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"${google_monitoring_metric_descriptor.with_alert.type}\" AND resource.type=\"gce_instance\""
      duration        = "0s"
      comparison      = "COMPARISON_LT"
      threshold_value = 100
      trigger {
        count = 1
      }
    }
  }
  depends_on = [
    google_monitoring_metric_descriptor.with_alert
  ]
}
```

### Debug Output
Concretely it result in the following error when applying a plan:
![error_apply](https://user-images.githubusercontent.com/5237397/158641169-46f56a67-10db-496f-8222-8c4f09f9b96d.png)

Full log output here: https://gist.github.com/gnthibault/c383a9887c7dba10d72358ef126fe252

### Expected Behavior
From what I understand, whenever I update a custom metric, it needs to be destroyed, then, recreated by terraform. As it is a common usecase for resource be dependent on other resources, I would expect terraform to build the dependy graph, and satisfy each dependency destruction upon destroying a resource, then performing the resource allocation in the reverse order to make sure no dependency rule is broken.

### Actual Behavior
I think terraform simply destroy the metric, without checking for dependent resources (alert), hence generating an error on google api.

### Steps to Reproduce
Use previous configuration, then slighty change the metric description(Here, I changed unit = "{USD}" to unit = "%"), for something like the following, and apply

```tf
resource "google_monitoring_metric_descriptor" "with_alert" {
  description = "Daily sales records from all branch stores."
  project      =  PUT_YOUR_PROJECT_NAME_HERE
  display_name = "metric-descriptor"
  type = "custom.googleapis.com/stores/daily_sales"
  metric_kind = "GAUGE"
  value_type = "DOUBLE"
  unit = "%"
  launch_stage = "BETA"
}
resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "metric-descriptor"
  project      = PUT_YOUR_PROJECT_NAME_HERE
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"${google_monitoring_metric_descriptor.with_alert.type}\" AND resource.type=\"gce_instance\""
      duration        = "0s"
      comparison      = "COMPARISON_LT"
      threshold_value = 100
      trigger {
        count = 1
      }
    }
  }
  depends_on = [
    google_monitoring_metric_descriptor.with_alert
  ]
}
```

b/275110447

**Comment by megan07** [comment]
Sorry for my delay on this! I believe this to be related to the upstream terraform sdk issue here: https://github.com/hashicorp/terraform-plugin-sdk/issues/122

**Comment by melinath** [comment]
https://github.com/hashicorp/terraform-plugin-sdk/issues/122 has been resolved by adding support for the [`replace_triggered_by` lifecycle meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by). You can use it as follows:

```hcl
resource "google_monitoring_metric_descriptor" "with_alert" {
  description = "Daily sales records from all branch stores."
  display_name = "metric-descriptor"
  type = "custom.googleapis.com/stores/daily_sales"
  metric_kind = "GAUGE"
  value_type = "DOUBLE"
  unit = "%"
}

resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "metric-descriptor"
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"${google_monitoring_metric_descriptor.with_alert.type}\" AND resource.type=\"gce_instance\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
    }
  }
  lifecycle {
    replace_triggered_by = [
      google_monitoring_metric_descriptor.with_alert
    ]
  }
}
```

Note that this will recreate the alert policy every time the metric descriptor _changes_, not just when the metric descriptor is recreated. If that is a problem, you could limit the `replace_triggered_by` to explicitly fields on  the metric descriptor that trigger recreation.

This is the recommended path forward for this kind of situation, where Terraform doesn't have a way to otherwise understand the relationship between the two resources. See the discussion on https://github.com/hashicorp/terraform-plugin-sdk/issues/122 for more details.
