### ISSUE TITLE
google_compute_region_instance_group retrieve wrong value for 'region' parameter

### ISSUE THREAD

**Issue by ducretje-evooq** [hashicorp/terraform-provider-google#11281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.1.7
on darwin_amd64

### Affected Resource(s)

* `google_compute_region_instance_group`

Using `google`provider v4.14.0

### Actual Behavior

Trying to retrieve an instances list from a MIG, terraform returns the following error

```sh
│ Error: Error when reading or editing Region Instance Group "gke-(xxx)": googleapi: Error 400: Invalid value for field 'region': 'europe-west6-b'. Unknown region., invalid
```

Actualy value `europe-west6-b` refers to a zone, not to a region.
The cluster is created without any issue, and the VM instances are accessible and avaiblable. The zones are correct, it's just it should not be there

### Steps to Reproduce

```tf
resource "google_container_cluster" "primary" {
  name                     = local.cluster_name
  location                 = local.region
  remove_default_node_pool = true
  initial_node_count       = 1
  network                  = module.gke_vpc.network_name
  subnetwork               = module.gke_vpc.subnetwork_name
  project                  = local.project
  dns_config {
    cluster_dns        = "CLOUD_DNS"
    cluster_dns_scope  = "VPC_SCOPE"
    cluster_dns_domain = local.cluster_name
  }
}

resource "google_container_node_pool" "primary_nodes" {
  name       = local.node_pool_name
  location   = local.region
  cluster    = google_container_cluster.primary.name
  node_count = local.node_count
  project    = local.project

  node_config {
    oauth_scopes = var.project_oauth_scopes
    labels = {
      env = local.project
    }
    machine_type = local.node_type
    tags         = ["gke-node", local.cluster_name]
    metadata = {
      disable-legacy-endpoints = "true"
    }
  }
}

data "google_compute_region_instance_group" "all" {
  for_each = toset(google_container_node_pool.primary_nodes.instance_group_urls)
  self_link = each.key
}
```

1. `terraform apply`

**Comment by megan07** [comment]
Hi @ducretje-evooq , it appears as though GKE creates zonal instance groups. Could you try `google_compute_instance_group` and see if that works for you?

**Comment by ducretje-evooq** [comment]
Hi @megan07, and thanks for your feedback.

Following your advice, I tried with 

```tf
data "google_compute_instance_group" "all" {
  for_each = toset(google_container_node_pool.primary_nodes.instance_group_urls)
  self_link = each.key
}
```

And got 

```plain
Error: A zone must be specified
│ 
│   with module.gke-dev.data.google_compute_instance_group.all["https://www.googleapis.com/compute/v1/project/myproject/zones/europe-west6-a/instanceGroupManagers/gke-cluster-cc9937ab-grp"],
│   on ../modules/gke/main.tf line 69, in data "google_compute_instance_group" "all":
│   69: data "google_compute_instance_group" "all" {
```

(I changed the name of the project and resources name)

I don't understand why it asks for zones, reading [the documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_instance_group#zone)

> If referencing the instance group by name and zone is not provided, the provider zone is used

I don't reference the zone in my provider definition since we work on several zones (a, b and c) but I expected it wouldn't be mandatory to define it since I use the `self_link`, not the `name`.

I tried with

```tf
data "google_compute_instance_group" "all" {
  for_each = toset(google_container_node_pool.primary_nodes.instance_group_urls)
  self_link = each.key
  zone = split("/", split("zones/", each.key)[1])[0]
}
```

> I noticed that the zone actually appears in the URI, so I try this trick to isolate it

And get

```plain
│ Error: Conflicting configuration arguments
│ 
│   with module.gke-prod.data.google_compute_instance_group.all["https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west6-a/instanceGroupManagers/gke-cluster-cc9937ab-grp"],
│   on ../modules/gke/main.tf line 72, in data "google_compute_instance_group" "all":
│   72:   zone = split("/", split("zones/", each.key)[1])[0]
│ 
│ "zone": conflicts with self_link
```

It makes more sense reading the doc, but I'm stucked again

**Comment by megan07** [comment]
@ducretje-evooq well this is really odd, it worked for me, and after further looking it's because i have `GOOGLE_ZONE` defined in my environment. However, looking at my state file, the zone (and everything else) for this data source is `null`. Then upon further digging...I see that I'm getting an error with this zone and Terraform is showing success. I'll dig into this a bit further. Sorry for this!

**Comment by megan07** [comment]
@ducretje-evooq ah ha! I found the problem - it looks like the urls that you are passing are for the [managed instance groups](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#instance_group_urls), and you'll really want
`for_each = toset(google_container_node_pool.primary_nodes.managed_instance_group_urls)`

I'm going to keep this open to look into why it wasn't throwing an error for me, but this should hopefully get you unstuck. Thanks for your patience!

**Comment by ducretje-evooq** [comment]
Thanks a lot @megan07 , it worked everything is OK now 👍
