### ISSUE TITLE
Error 400: Updating a deleted transfer job is not allowed., failedPrecondition

### ISSUE THREAD

**Issue by davidedironza** [hashicorp/terraform-provider-google#11288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

12.31

### Affected Resource(s)

* google_storage_transfer_job

### Terraform Configuration Files

```tf
resource "google_storage_transfer_job" "gcs-bucket-backup" {
  for_each = local.backup_buckets
  project     = var.project_id
  description = "Frequent backup of ${each.key} gcs bucket"
  status = try(each.value.backup.status, "ENABLED")
  ...
}
```

### Debug Output

The command terraform plan already shows it'll update the resource:

```tf
# module.storage_buckets.google_storage_transfer_job.gcs-bucket-backup["backup-test"] will be updated in-place
  ~ resource "google_storage_transfer_job" "gcs-bucket-backup" {
        creation_time          = "2022-03-15T08:19:25.437266985Z"
        deletion_time          = "2022-03-16T06:54:49.205758824Z"
        description            = "Frequent backup of backup-test gcs bucket"
        ...
    }
```

### Panic Output

None

### Expected Behavior

Create the job.

### Actual Behavior

Wants to update the job.

### Steps to Reproduce

1. Create a job with terraform
2. Delete the job on the UI
3. rerun terraform plan

### Important Factoids

None

### References

None

**Comment by pgruetter** [comment]
Is this fix included in 4.15.0? Just stumbled upon the exact same error. Judging from the commits, I think it should be included in 4.15.0 but it's not in the Changelog and I quickly tried to upgrade and still get the same error.
