### ISSUE TITLE
google_project_service can't enable service earthengine.googleapis.com. Error 403: Permission denied.

### ISSUE THREAD

**Issue by intotecho** [hashicorp/terraform-provider-google#11303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.11.0
+ provider registry.terraform.io/hashicorp/google-beta v4.11.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

google_project_service

### Terraform Configuration Files

The plan reports it will add the following resource. i.e. enable the earthengine.googleapis.com on my project.

```tf
resource "google_project_service" "earth_engine_apis" {
      + disable_dependent_services = true
      + disable_on_destroy         = true
      + id                         = (known after apply)
      + project                    = "my_project_id"
      + service                    = "earthengine.googleapis.com"
    }
```

### Expected Behavior

I expect the terraform apply to enable the API. This works fine for many other APIs.

### Actual Behavior

Error: Request `Enable Project Service "earthengine.googleapis.com" for project "my_project_id"` returned error: Batch request and retried single request "Enable Project Service \"earthengine.googleapis.com\" for project \"my_project_id\"" both failed. Final error: failed to send enable services request: googleapi: Error 403: Permission denied to enable service [earthengine.googleapis.com]
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "110002",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "reason": "AUTH_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden│

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I can enable earthengine.googleapis.com on the GCP console for this project. 
Then when I run apply, the state synchronises without issue and I can disable it with terraform, but I can't reenable it.

I am authenticating as a service account which can enable other APIs. It has been granted these roles:
       "roles/serviceusage.serviceUsageAdmin".
      "roles/iam.serviceAccountUser",
      "roles/iam.roleAdmin",
      "roles/earthengine.admin"
      "roles/serviceusage.serviceUsageAdmin",
      "roles/iam.serviceAccountAdmin",
      "roles/resourcemanager.projectIamAdmin"

**Comment by intotecho** [comment]
I believe that this is a bug, not a question, because
 

1. I can enable other APIs in the script, just not the Earth Engine API. So unlikely an issue with the credentials used by TF.
2. I can enable and disable the Earth Engine API with the console.
3. If enabled, the TF script successfully reads that the API is in enabled state.
4. If disabled again with the console, the 403 error recurs.

I agree that its likely not a bug in the google provider but in the google api itself or even in earth engine.
If anyone can either verify this is an issue or report that they can enable the API from TF then please comment.

**Comment by bmistry12** [comment]
Jumping on this issue - facing the same issue with two different APIs (but others work fine with the same terraform config). Seems to also vary from project to project. For some projects, I am able to enable the same set of APIs with no issues despite having the same IAM permissions across the board. Error log for the Places API:
```
│ Error: Request `Enable Project Service "places.googleapis.com" for project "xxx"` returned error: Batch request and retried single request "Enable Project Service \"places.googleapis.com\" for project \"xxx\"" both failed. Final error: failed to send enable services request: googleapi: Error 403: Permission denied to enable service [places.googleapis.com]
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "?error_code=110002\u0026service=servicemanagement.googleapis.com\u0026permission=servicemanagement.services.bind\u0026resource=xxx",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "metadata": {
│       "permission": "servicemanagement.services.bind",
│       "resource": "xxx",
│       "service": "servicemanagement.googleapis.com"
│     },
│     "reason": "AUTH_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden

```

**Comment by ScottSuarez** [comment]
Issue appears to have been fixed after attempting locally. Please reopen if you still encounter this.
