### ISSUE TITLE
Updating Composer image_version Fails in Terraform

### ISSUE THREAD

**Issue by hspak** [hashicorp/terraform-provider-google#11300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.14.0
+ provider registry.terraform.io/hashicorp/google-beta v4.14.0

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
# Updating `composer_version` version from `composer-2.0.6-airflow-2.1.4` to `composer-2.0.6-airflow-2.2.3`
resource "google_composer_environment" "main" {
  project = var.project_id

  name   = var.name
  region = "us-central1"

  config {
    software_config {
      image_version = var.composer_version
    }
  }
}
```

### Debug Output

`TF_LOG=debug` snippet of the request to apply the composer change: https://gist.github.com/hspak/716f179ea03bbb88d7897a15c3e0b5f0

### Panic Output

N/A

### Expected Behavior

The composer image version should be updated.

### Actual Behavior

We get an HTTP 400 Bad Request error.
```
╷
│ Error: googleapi: Error 400: Invalid field mask. Updating the selected field(s) is not supported., badRequest
│
│   with module.composer_airflow.google_composer_environment.main,
│   on ../../../modules/composer/composer.tf line 1, in resource "google_composer_environment" "main":
│    1: resource "google_composer_environment" "main" {
│
╵
```

### Steps to Reproduce

1. Update the `config.software_config.image_version` on a `google_composer_environment` resource.
1. `terraform apply`

### Important Factoids

- I can apply this version update manually in the GCP web console without issues.

### References

N/A

**Comment by megan07** [comment]
Hi @hspak , sorry that you ran into this issue. [Upon further research](https://cloud.google.com/composer/docs/how-to/managing/upgrading), it appears that updating the `image_version` is still in beta, in which case, this will work with the `google-beta` provider. It looks like we need to restrict this in the `google` provider, so I will make that change to avoid future issues, but if you use the `google-beta` provider now, this should work. I'll leave this open until my code change is accepted. Thanks!
