### ISSUE TITLE
Update required to docs for generated resources with sensitive fields 

### ISSUE THREAD

**Issue by aslattery** [hashicorp/terraform-provider-google#11306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Expected Behavior

Link should take users to [Sensitive Data in State](https://www.terraform.io/language/state/sensitive-data) on the main Terraform documentation site.

### Actual Behavior

Users are instead taken to a [Vercel 500 page](https://www.terraform.io/docs/state/sensitive-data.html), presumably as the upstream documentation is no longer hosted at `/docs/*`.

![image](https://user-images.githubusercontent.com/5545673/159074736-f4d53dad-fe8b-44bc-b7bf-9a85fd0e8427.png)

### References

* #5678 was the original issue to add these references to `magic-modules`
* GoogleCloudPlatform/magic-modules#3393 contained the original fix
* [Direct link](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/resource.html.markdown.erb#L96) to `mmv1/templates/terraform/resource.html.markdown.erb#96`, where I believe the fix should be applied.

**Comment by slevenick** [comment]
Thanks for the links, I made a PR to update these links
