### ISSUE TITLE
Node pool version state information not updated after node pool upgrade

### ISSUE THREAD

**Issue by parberge** [hashicorp/terraform-provider-google#11313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
> terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.14.0
```

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "gcc_nodes" {
  version  = "1.21.9-gke.300"

  management {
    auto_upgrade = false
  }
}
```

### Expected Behavior

1. Terraform upgrade node pool to version `1.21.9-gke.300`
2. Running `terraform plan` will show `No changes. Your infrastructure matches the configuration.`

### Actual Behavior

1. Terraform upgrade node pool to version `1.21.9-gke.300`
2. Running `terraform plan` will show:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # google_container_cluster.gke has changed
  ~ resource "google_container_cluster" "gke" {
        id                          = "projects/plaza-parberge-testing-2587/locations/europe-north1-a/clusters/parberge-testing-gke-2818"
        name                        = "parberge-testing-gke-2818"
      ~ node_version                = "1.19.14-gke.1900" -> "1.21.9-gke.300"
        # (27 unchanged attributes hidden)

      ~ node_pool {
            name                        = "parberge-testing-gke-2818-node-pool"
          ~ version                     = "1.19.14-gke.1900" -> "1.21.9-gke.300"
```

### Steps to Reproduce

1. Make sure `version` of node pool isn't `1.21.9-gke.300`.
2. Update `version` to `1.21.9-gke.300`.
3. Run `terraform apply`
4. Run `terraform plan`

### References

* b/298506620

**Comment by Edwinhr716** [comment]
Unable to reproduce the bug

terraform version: v1.6.5

Terraform file
```
resource "google_container_node_pool" "gcc_nodes_2" {
    cluster = "cluster-upgrade-nodepool"
    provider = "google-beta"
    version = "1.21.9-gke.300"
    project = "edwinhernandez-gke-dev"
    name = "nodepool-upgrade-test-2"
    location = "us-central1"
    initial_node_count = 1
    management {
        auto_upgrade = false
    }
}
```

steps followed:

Upgraded to version 1.21.9-gke.300

ran `terraform apply` 

ran `terraform plan`

logs

```

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Comment by parberge** [comment]
> Unable to reproduce the bug
> 
> terraform version: v1.6.5
> 
> Terraform file
> ```
> resource "google_container_node_pool" "gcc_nodes_2" {
>     cluster = "cluster-upgrade-nodepool"
>     provider = "google-beta"
>     version = "1.21.9-gke.300"
>     project = "edwinhernandez-gke-dev"
>     name = "nodepool-upgrade-test-2"
>     location = "us-central1"
>     initial_node_count = 1
>     management {
>         auto_upgrade = false
>     }
> }
> ```
> 
> steps followed:
> 
> Upgraded to version 1.21.9-gke.300
> 
> ran `terraform apply` 
> 
> ran `terraform plan`
> 
> logs
> 
> ```
> 
> No changes. Your infrastructure matches the configuration.
> 
> Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
> ```
> 
> 

Thanks for testing. I will consider this bug solved then 👍
