### ISSUE TITLE
Failing test(s): TestAccBinaryAuthorizationPolicy

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11317]
```
Step 3/3 error: Check failed: ...
```

Failure rate: 100% since Mar 3 2022

Impacted tests:
- TestAccBinaryAuthorizationPolicy_full
- TestAccBinaryAuthorizationPolicy_basic
- TestAccBinaryAuthorizationPolicy_separateProjeect
- TestAccBinaryAuthorizationPolicy_update

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/270029?buildTab=tests&status=failed&expandedTest=-3654105603345523263)

Message:

```
provider_test.go:301: Step 3/3 error: Check failed: Policy for project tf-test-... was map[...]
```

**Comment by rileykarson** [comment]
Fixed w/ https://github.com/GoogleCloudPlatform/magic-modules/pull/5918
