### ISSUE TITLE
Data sources show success even if not found

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* data. google_compute_instance_group (among others)

### Terraform Configuration Files

I encountered this while testing this issue: https://github.com/hashicorp/terraform-provider-google/issues/11281
I had my `GOOGLE_ZONE=us-central1-a` so I saw success, even though the instance_groups I was trying to access were in `europe-west6-a`

### Expected Behavior

Terraform should report an error that the data source doesn't exist

### Actual Behavior

Terraform shows success

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The problem is that we're re-using the resource's Read function, and in that Read function we call `handleNotFound`, where, if the resources i not found, we remove it from state and call it a success. This shouldn't be the case for data sources.

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/12873 (well, it duplicated this- but it's got more activity)
