### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withNotificationConfig

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11324]
### Affected Resource(s)

* google_container_cluster

Failure rate: 100% since Feb 15 2022

Impacted tests:
- TestAccContainerCluster_withNotificationConfig

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/270065?buildTab=tests&status=failed&expandedTest=-8613758987108971401)

Message:

```
Error creating Topic: googleapi: Error 409: Resource already exists in the project (resource=test-topic-2).
```

**Comment by AlfatahB** [comment]
TestAccContainerCluster_withNotificationConfig
    [Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-8613758987108971401&tab=testDetails) - 1.1% failure
    [Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=-8613758987108971401&tab=testDetails) - 1.1% failure

**Comment by AlfatahB** [comment]
b/261830687

**Comment by roaks3** [comment]
This test appears to have no failures in the history that I can see. Since it was previously a 100% failure, my guess is that this was resolved somehow.
