### ISSUE TITLE
Failing test(s): TestAccComputeInstance_soleTenantNodeAffinities

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11321]
### Affected Resource(s)

* google_compute_instance

Failure rate:
- 100% since Feb 14
- Still 100% June 16 2022
- 0% in Mar 2023 (last failure was Feb 25, 2023)

Impacted tests:
- TestAccComputeInstance_soleTenantNodeAffinities

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/270065?buildTab=tests&status=failed&expandedTest=8338733404894056578)
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/301942?buildTab=tests&expandedTest=8338733404894056578

Message:

```
Step 3/8 error: Error running apply: exit status 1
Error: Error waiting for starting instance: couldn't find resource (21 retries)
```

**Comment by melinath** [comment]
It looks like this also sometimes fails with:

```
Error: Error waiting to create NodeGroup: Error waiting for Creating NodeGroup: The zone 'projects/ci-test-project-188019/zones/us-central1-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

**Comment by melinath** [comment]
It looks like this sometimes also fails with:

```
Error: Error waiting to create NodeGroup: Error waiting for Creating NodeGroup: The zone 'projects/<project-id>/zones/us-central1-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

**Comment by melinath** [comment]
Still 100%

**Comment by AarshDhokai** [comment]
Still failing in both [Google Cloud](https://ci-oss.hashicorp.engineering/test/8338733404894056578?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) and [Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/8338733404894056578?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)

**Comment by melinath** [comment]
New error:

```
Error: Error waiting for starting instance: Instance could not be scheduled due to no matching node with property compatibility.
Explanation:
The matching node(s) <tf-test-nodegroup-pqanc7mpsz-rpqj> are not in READY status.
Potential fix:
- Please consider waiting for the matching node(s) to become READY.
- Please consider deleting and recreating the node or contacting Google Cloud Support, in case it is taking several minutes for the node to become READY.
```

**Comment by AarshDhokai** [comment]
b/263129411

**Comment by roaks3** [comment]
This issue appears to have become flaky within the last month (no longer 100% failure), with a variety of error messages. That could point to something in the environment that was cleaned up to allow it to succeed on occasion. It will be interesting to see how the new test projects behave.

**Comment by roaks3** [comment]
Error is still the same as Stephen's comment above when it occurs, but it is much less common now. 0% fail rate in Mar 2023, last failure was Feb 25, 2023. It fails slightly more frequently in Beta.

Keeping this open for now and lowering the failure rate label.

**Comment by melinath** [comment]
Closing this for now - we can reopen if it pops up again.
