### ISSUE TITLE
`google_cloudbuild_trigger` fails with HTTP Error 400 when `git_file_source` is used

### ISSUE THREAD

**Issue by kawo123** [hashicorp/terraform-provider-google#11335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.15.0
+ provider registry.terraform.io/hashicorp/google-beta v4.15.0
```

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "helloworld_ci_trigger" {
  name            = "helloworld-ci-trigger"
  description     = "Continuous integration for helloworld component"
  service_account = var.deploy_sa_email

  github {
    owner = "XXXXXX"
    name  = "XXXXXX"
    push {
      branch = "^main$"
    }
  }

  git_file_source {
    path      = "helloworld/cloudbuild_ci.yaml"
    repo_type = "GITHUB"
    uri       = "https://github.com/XXXXXX/XXXXXX"
  }

  included_files = ["helloworld/**"]

  substitutions = {
    _ARTIFACT_REGISTRY_REPO = "my-repository"
  }
}
```

### Debug Output

https://gist.github.com/kawo123/ff3f3d60bdf8fb954616a5df6e564b57

### Expected Behavior

The `google_cloudbuild_trigger` should be created with reference to cloudbuild configuration from GitHub repo.

### Actual Behavior

I receive an error `Error: Error creating Trigger: googleapi: Error 400: Request contains an invalid argument.`

### Steps to Reproduce

1. `terraform apply`

**Comment by slevenick** [comment]
It looks like you don't have a repository specified in the configuration for the git_file_source? I'm guessing that there is default behavior but it is not finding the correct repository. 

Can you try specifying the `uri` field in the `git_file_source` block and see if that resolves the issue? I'm guessing that the error message is very unspecific and should actually say that it cannot find the correct yaml file

**Comment by kawo123** [comment]
@slevenick: Thanks for the suggestion. I updated the `git_file_source` block to include `uri` but still getting the same error `Error 400: Request contains an invalid argument.`

```tf
  git_file_source {
    path      = "helloworld/cloudbuild_ci.yaml"
    repo_type = "GITHUB"
    uri       = "https://github.com/XXXXXX/XXXXXX"
  }
```

**Comment by kawo123** [comment]
Closing. Found the issue to be irrelevant to the `git_file_source` block thanks to @slevenick's help.
