### ISSUE TITLE
Unable to create cloud build triggers with GitHub Enterprise repository

### ISSUE THREAD

**Issue by duxbuse** [hashicorp/terraform-provider-google#11340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently it is not possible to create cloudbuild triggers that link to github enterprise repositories. 

Even when using the [github](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#github) selector you will run into the following error, 
```text
Error creating Trigger: googleapi: Error 400: Repository mapping does not exist.
Please visit https://console.cloud.google.com/cloud-build/triggers/connect?project=XXX
to connect a repository to your project
```
It can be seen that since the addition of the [Github enterprise connector](https://cloud.google.com/build/docs/automating-builds/build-repos-from-github-enterprise) there is a new field that needs to be understood [enterpriseConfigResourceName](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.githubEnterpriseConfigs). As such I believe  that the terraform provider needs to accept this new field as a parameter for the resource and attach it to the google api call to ensure that the trigger once created can see and is aware of the linked repository.
### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "tf-cicd-trigger" {

  name    = "tf-cicd-trigger"

  project = module.cloudbuild_bootstrap.cloudbuild_project_id

  github {

    name  = "XXX"
    owner = "XXX"
    enterpriseConfigResourceName = "GITHUB_ENTERPRISE_APP_NAME" # <------ New Field

    push {
      branch       = "master"
      invert_regex = false
    }
  }
  filename        = "cloudbuild.yaml"
  service_account = "XXX"
  }
```

### References

* #0000

**Comment by rileykarson** [comment]
Dupes https://github.com/hashicorp/terraform-provider-google/issues/9956 I believe!
