### ISSUE TITLE
project requirement fails on apply with beta provider

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform-provider-google#11353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

When using `google-beta` provider (v 4.15.0), some resources which should not require a `project` explicitly when one is provided implicitly at the provider level will plan successfully, but fail on apply.

For example:
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_project_metadata_item
lists `project` as optional.

Even if these resources now require project in beta, they should throw an error on plan, rather than only on apply.

### Terraform Version
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.15.0
+ provider registry.terraform.io/hashicorp/google-beta v4.15.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
```

### Affected Resource(s)
* `google_sql_database`
* `google_compute_project_metadata_item`
* potentially others

### Terraform Configuration Files

Simple / self-contained repro case:
```
variable "project" {
  type    = string
  default = "foo"
}

provider "google-beta" {
  project = var.project
}

resource "google_compute_project_metadata_item" "foo" {
  key   = "FOO"
  value = "BAR"
}
```

More complicated repro case:
```
.
├── modules
│   └── testmodule
│       └── main.tf
└── test
    ├── main.tf
```

```tf
// main.tf
variable "project" {
  type    = string
  default = "foo"
}

provider "google-beta" {
  project               = var.project
  user_project_override = true
}

module "test" {
  source    = "../modules/testmodule"
  project   = var.project
  databases = ["foo", "bar"]
}


// modules/testmodule/main.tf 
variable "databases" {
  type    = set(string)
  default = []
}

variable "project" {
  type = string
}

resource "random_id" "name_suffix" {
  byte_length = 2
}

resource "google_sql_database_instance" "this" {
  name     = "test-${random_id.name_suffix.hex}"
  provider = google-beta

  region              = "us-west2"
  database_version    = "POSTGRES_14"
  deletion_protection = false


  settings {
    availability_type = "REGIONAL"
    tier              = "db-f1-micro"
  }
}

resource "google_sql_database" "database" {
  for_each = var.databases
  name     = each.value
  instance = google_sql_database_instance.this.name
}

resource "google_compute_project_metadata_item" "foo" {
  key   = "FOO"
  value = google_sql_database_instance.this.name
}
```

### Debug Output
[should be reproducible; let me know if you need some debug output]

### Panic Output
n/a

### Expected Behavior
The apply should succeed (ideally), or `terraform plan` should fail if project is really required.

### Actual Behavior
Plan succeeds, apply fails with the error
```
│ Error: project: required field is not set
│ 
│   with module.test.google_sql_database.database["foo"],
│   on ../modules/testmodule/main.tf line 29, in resource "google_sql_database" "database":
│   29: resource "google_sql_database" "database" {
│ 
╵
╷
│ Error: project: required field is not set
│ 
│   with module.test.google_sql_database.database["bar"],
│   on ../modules/testmodule/main.tf line 29, in resource "google_sql_database" "database":
│   29: resource "google_sql_database" "database" {
│ 
╵
╷
│ Error: project: required field is not set
│ 
│   with module.test.google_compute_project_metadata_item.foo,
│   on ../modules/testmodule/main.tf line 35, in resource "google_compute_project_metadata_item" "foo":
│   35: resource "google_compute_project_metadata_item" "foo" {
```

### Steps to Reproduce
1. `terraform apply`
1. There is no step 2

### Important Factoids
I originally discovered this by accident when I accidentally redefined the `google` provider with the source from `google-beta`, however, this seems reproducible as-is.

### References
#5761 - similar discussion, though that implies that this behavior may be less abnormal than I had been led to believe?

**Comment by ScottSuarez** [comment]
This is consistent w/ other resources in the provider- almost all resources are parented under a project unless indicated otherwise. The field is technically optional due to the provider default value, but is ultimately required.

**Comment by wyardley** [comment]
@ScottSuarez is the difference between GA and beta provider also expected?

my memory was that it was still only specific resources that can’t infer it when it’s set at the provider level (as it is in my example). So I don’t think this is working as expected.

**Comment by wyardley** [comment]
@rileykarson pointed out the main flaw here, which is that if the beta provider isn't explicitly used for each resource, it will then use the non-beta provider, which I think explains this behavior.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_versions#using-the-google-beta-provider
