### ISSUE TITLE
google_kms_crypto_key ID changed after importing

### ISSUE THREAD

**Issue by blakey22** [hashicorp/terraform-provider-google#11366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.15.0
```

### Affected Resource(s)

* google_kms_crypto_key

### Terraform Configuration Files

```tf
resource "google_kms_key_ring" "my-key-ring" {
  project  = "<gcp_project_id>"
  name     = "my-key-ring"
  location = "europe"
}

resource "google_kms_crypto_key" "my-key" {
  name     = "my-key"
  key_ring = google_kms_key_ring.my-key-ring.id
}

```

### Expected Behavior

The imported `google_kms_crypto_key` ID should be the same as the created one.

### Actual Behavior

The imported `google_kms_crypto_key` ID has changed from `projects/<gcp_project_id>/locations/europe/keyRings/my-key-ring/cryptoKeys/my-key"` to `<gcp_project_id>/europe/my-key-ring/my-key`.

### Steps to Reproduce

1. `terraform apply`
2. `terraform state show google_kms_crypto_key.my-key`
3. `terraform state rm google_kms_crypto_key.my-key`
4. `terraform import 'google_kms_crypto_key.my-key' <gcp_project_id>/europe/my-key-ring/my-key`
5. `terraform state show google_kms_crypto_key.my-key`

### Important Factoids
This will trigger an invalid amdement of `google_storage_bucket` or `google_bigquery_dataset` if `default_encryption_configuration` sets to the imported crypto key.

**Comment by ScottSuarez** [comment]
This behavior is by design so all id's have the same format

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_kms_key_ring.go#L200-L205
