### ISSUE TITLE
Timeout on google_bigquery_table

### ISSUE THREAD

**Issue by jamiet-msm** [hashicorp/terraform-provider-google#11369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

google_bigquery_table doesn't support timeouts. When I specify a timeout validation failed with:

```
│ Error: Unsupported block type
│ 
│   on modules/path/to/bigquery.tf line 85, in resource "google_bigquery_table" "resource_name":
│   85:   timeouts ***
│ 
│ Blocks of type "timeouts" are not expected here.
```

The reason I'd like to be able to specify timeout on here is because the creation/modification of an view that SELECTs FROM an external table (which is also defined using google_bigquery_table) is failing after 120seconds with error:

```
│ Error: Put "https://bigquery.googleapis.com/bigquery/v2/projects/project-id/datasets/dataset-id/tables/table-id?alt=json&prettyPrint=false": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
│
│   with module.RealTimeIngestion[0].module.RealTimeEventProcessing["msm"].google_bigquery_table.braze_egress_messages_row_per_external_id,
│   on modules/path/to/bigquery.tf line 87, in resource "google_bigquery_table" "resource_name":
│   87: resource "google_bigquery_table" "resource_name" {
│
```

So to be clear, its the creation of a view that is failing however I'm confident that the problem lies in the fact that that view is on top of an external table. That external table sits on top of a GCS bucket and the failure occurs when there is a sufficiently large volume of data in that bucket (I can't give an accurate figure as to what volume of data triggers the error I'm afraid but we're certainly talking many GBs). If I delete the contents of that bucket then the problem doesn't occur.

I'm not particularly au fait with terraform timeouts but I would hope that being able to specify a suitably long timeout would alleviate this problem and cause my applys to not fail.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "external_table" {
  dataset_id          = google_bigquery_dataset.ds.dataset_id
  project             = var.project_id
  table_id            = "t"
  /*
  Do NOT specify a value for the schema attribute. Instead rely on 
  external_data-configuration.schema
  Read https://github.com/hashicorp/terraform-provider-google/issues/10919#issuecomment-1058967078
  for an explanation as to why.
  */
  external_data_configuration {
    autodetect    = false
    source_uris   = ["gs://${google_storage_bucket.bucket.name}/publish/*"]
    source_format = "NEWLINE_DELIMITED_JSON"
    schema        = local.schema
    hive_partitioning_options {
      mode                     = "CUSTOM"
      source_uri_prefix        = "gs://${google_storage_bucket.bucket.name}/publish/{dt:STRING}/{hr:STRING}/{min:STRING}/{sec:STRING}/{micro:STRING}"
      require_partition_filter = false
    }
  }
  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }
}

resource "google_bigquery_table" "braze_egress_messages_row_per_external_id" {
  dataset_id          = google_bigquery_dataset.ds.dataset_id
  project             = var.project_id
  table_id            = "${google_bigquery_table.external_table.table_id}_vw"
  view {
  # vw.sql is a view only has the external table in its FROM clause
    query = templatefile("${path.module}/bigquery-views/view.sql", {
      project_id = google_bigquery_table.external_table.project
      dataset_id = google_bigquery_table.external_table.dataset_id
      table_id   = google_bigquery_table.external_table.table_id
    })
    use_legacy_sql = false
  }
  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }
}
```

I admit that I'm making an assumption here that a longer timeout on terraform would solve this. perhaps its the underlying API that's timing out - I don't know. I dont think so though, I can't find any pertinent errors in Cloud Logging.

**Comment by rileykarson** [comment]
The timeouts block wouldn't help here, I don't think- that timeout's set to 30m by default, and we make it configurable when we change that. What you're running in to here is the synchronous request timeout, the time the provider waits for a single request to come back.

Does changing the [`request_timeout`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_timeout) value on the provider help? It seems to me like this API is doing operations that _should be_ asynchronous using a long-running operation in a synchronous request.

**Comment by jamiet-msm** [comment]
@rileykarson ooo I wasn't aware of request_timeout, that sounds like it could be just the ticket. I will definitely give it a go. What is the default request_timeout (if its 120 seconds then that gives me confidence that this is indeed the culprit)?

**Comment by rileykarson** [comment]
Oh, yeah, I should have mentioned that it's [`120s`](https://github.com/hashicorp/terraform-provider-google-beta/blob/26bece70c2c09effd7a87bde7eb501710687cdde/google-beta/config.go#L578) in the first place!

**Comment by rileykarson** [comment]
With a mitigation there's not much to do here in the provider- the best fix would be if the API sent back an Operation object properly, but that's unlikely to be backwards compatible on their end.

One note: `request_timeout`'s a global setting which could lead to an obtuse failure condition if a response is lost- Terraform will keep waiting until the resource timeout (generally tens of minutes) or the request timeout, whichever is lower.

For my own reference, b/228020521 was related (and I linked this there)
