### ISSUE TITLE
google_compute_resource_policy description Field Not Working

### ISSUE THREAD

**Issue by Rob-S** [hashicorp/terraform-provider-google#11364]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.7
on windows_amd64

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```resource "google_compute_resource_policy" "db_compute_resource_policy_backup_disks" {
  for_each    = local.db_backups_regions_map
  project     = each.value.project_id
  region      = each.value.region
  name        = "db-compute-resource-policy-backup-disks"
  description = "Periodic snapshots of backup disks"
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = 1
        start_time     = "00:00"
      }
    }
    retention_policy {
      max_retention_days    = 30
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
    snapshot_properties {
      guest_flush = true # on Windows, create a read-only VSS snapshot
    }
  }
}
```

### Expected Behavior

description is a valid field

### Actual Behavior

Error: Unsupported argument
  on [dbbackups.tf](https://bitbucket.org/ucaas_mitel/gco_cloud_infrastructure/src/9097777991ce3d1dd7ee9c7f599513dcbc05193c/dbbackups.tf) line 70, in resource "google_compute_resource_policy" "db_compute_resource_policy_backup_disks":
  70:   description = "Periodic snapshots of backup disks"
An argument named "description" is not expected here.

### Steps to Reproduce

Create a google_compute_resource_policy with a description field.

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy

* #0000

![Screenshot_2022-03-28_194315](https://user-images.githubusercontent.com/323132/160510651-4f44aea5-1756-4f3c-96c6-486705b580f2.jpg)

**Comment by ScottSuarez** [comment]
Could you confirm which version of the provider you are using ?

This field was added in provider version `3.69.0`

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/CHANGELOG.md#3690-may-24-2021
