### ISSUE TITLE
Apigee Environment Support for Archive and Configurable Proxy

### ISSUE THREAD

**Issue by danistrebel** [hashicorp/terraform-provider-google#11379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Apigee Environments now include additional flavors that should ideally be reflected in the TF provider as well.

* [deploymentType](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#deploymenttype)
* [apiProxyType](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/ApiProxyType)

### New or Affected Resource(s)

* google_apigee_environment

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* [Apigee API Docs](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments/create)

* #0000

**Comment by xuchenma** [comment]
This issue should be solved in PR https://github.com/hashicorp/terraform-provider-google/pull/11405
