### ISSUE TITLE
Support GCE suspend and resume

### ISSUE THREAD

**Issue by coadler** [hashicorp/terraform-provider-google#11374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP recently added suspending to GCE instances. It would be nice to be able to suspend and resume instances directly from Terraform.

### New or Affected Resource(s)

* `google_compute_instance`

### Potential Terraform Configuration

I imagine that it would be easiest to add this to the `desired_status` field, which is currently used to stop and start VMs.

```tf
resource "google_compute_instance" "example" {
  ...
  desired_status = "SUSPENDED"
}
```

### References

* https://cloud.google.com/compute/docs/instances/suspend-resume-instance

b/359989572

**Comment by rileykarson** [comment]
Note: There's a parameter for suspension seen in `https://www.googleapis.com/compute/v1/projects/PROJECT_ID/zones/ZONE/instances/VM_NAME/suspend?discardLocalSsd=true` that could require special handling- probably `X_on_suspend` or something, if supporting it is important (it'd also be reasonable to omit)

**Comment by ggtisc** [comment]
Currently the unique options are `RUNNING` and `TERMINATED` for the [desired_status](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#desired_status) argument, even if the [API](https://cloud.google.com/compute/docs/reference/rest/v1/instances) has more options for the `status` field.

If another value is assigned it returns an error like this:

```
 Error: expected desired_status to be one of ["RUNNING" "TERMINATED"], got SUSPENDED
│ 
│   with google_compute_instance.ci_11374,
│   on main.tf line 63, in resource "google_compute_instance" "ci_11374":
│   63:   desired_status = "SUSPENDED"
```
