### ISSUE TITLE
Cannot configure runtime service account with `google_cloudfunctions2_function` 

### ISSUE THREAD

**Issue by mihirsamdarshi** [hashicorp/terraform-provider-google#11388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/google v4.11.0
+ provider registry.terraform.io/hashicorp/google-beta v4.15.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
```

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

```tf
locals {
  timestamp = formatdate("YYMMDDhhmmss", timestamp())
  env       = terraform.workspace == "default" ? "dev" : terraform.workspace
}

data "google_project" "project" {}

# Compress source code
data "archive_file" "source" {
  type        = "zip"
  source_dir  = var.source_dir
  output_path = "/tmp/function-${var.function_name}-${local.timestamp}-${local.env}.zip"
}

# Add source code zip to bucket
resource "google_storage_bucket_object" "zip" {
  name   = "${var.function_name}/source.zip#${data.archive_file.source.output_md5}"
  bucket = var.source_bucket
  source = data.archive_file.source.output_path

  depends_on = [data.archive_file.source]

  lifecycle {
    ignore_changes = [metadata]
  }
}

resource "google_cloudfunctions2_function" "function" {
  provider = google-beta
  name     = "${var.function_name}-${local.env}"

  service_config {
    available_memory = "256M"

    min_instance_count = 1

    service_account_email = var.service_account_email

  }

  build_config {
    runtime               = var.runtime
    entry_point           = var.entrypoint

    source {
      storage_source {
        bucket = var.source_bucket
        object = google_storage_bucket_object.zip.name
      }
    }
  }
}
```

### Expected Behavior

The resource should allow attaching a service account to the runtime service, like the cloud console provides, as shown below

<img width="847" alt="Screen Shot 2022-03-31 at 5 03 03 PM" src="https://user-images.githubusercontent.com/5462077/161169416-5f71b539-9d2b-478a-b044-dcbfaf9e561d.png">

### Actual Behavior

Received an error that the `service_account_email` attribute is not configurable, even though [it is listed as an argument in the documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions2_function#service_account_email)

```bash
╷
│ Error: Value for unconfigurable attribute
│ 
│   with module.cloud_functions["data-url-service-testing"].google_cloudfunctions2_function.function,
│   on function/cf.tf line 46, in resource "google_cloudfunctions2_function" "function":
│   46:     service_account_email = var.service_account_email
│ 
│ Can't configure a value for "service_config.0.service_account_email": its value will be decided automatically based on the result of applying this configuration.
```

### Steps to Reproduce

1. Use the configuration above with the appropriate values for the variables
1. `terraform plan`

**Comment by k-ezis** [comment]
We have a fix for this being reviewed shortly.

**Comment by chrisndo** [comment]
Has this fix been implemented? I'm running into a similar issue where no matter what `service_account_email` i provide, it uses the default service account.

**Comment by alxgda** [comment]
I'm facing the same issue as of today. No matter what, it's the default compute service that will be used.

**Comment by k-ezis** [comment]
Yeah it's been implemented, so that's very strange. Can you guys give me some more details on what you're seeing? I have some cycles this month to work on this so any info would be great and I'll take a look.

**Comment by pwmb** [comment]
I am using this version and still the service account is not getting set

```hcl
google = {
  version = "~> 4.43.0"
  source  = "hashicorp/google"
}
```



```hcl
resource "google_service_account" "function-service-account" {
  account_id   = local.fn_service_acc_name
  description  = "..."
  display_name = local.fn_service_acc_name
  project      = var.project_id
}

resource "google_cloudfunctions2_function" "fn" {
  name        = local.name
  location    = var.project_region
  project     = var.project_id

  service_config {
    service_account_email = google_service_account.function-service-account.email
  }
}
```

Instead the function uses the usual `Compute Engine Default Service Account`

**Comment by k-ezis** [comment]
@rileykarson I think we can close this issue, looks like the original fix worked.
