### ISSUE TITLE
firewall name length is in accurate in description

### ISSUE THREAD

**Issue by codeangler** [hashicorp/terraform-provider-google#11416]
https://github.com/hashicorp/terraform-provider-google/blob/5b48efa7620f78ca9f8b313205e509af27f76a89/google/resource_compute_firewall.go#L167

> Description: `Name of the resource. Provided by the client when the resource is
created. The name must be 1-63 characters long, and comply with
RFC1035. Specifically, the name must be 1-63 characters long and match
the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?' which means the
first character must be a lowercase letter, and all following
characters must be a dash, lowercase letter, or digit, except the last
character, which cannot be a dash.`,

yet the error message says the regex is with 61 characters.

```
│ Error: "name" ("allow-vault-cluster-chore-evalutation-splunk-for-aggregation-sink") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
```

**Comment by rileykarson** [comment]
Wouldn't that match 63 characters? I read the regex as a single alphabetical character followed by 0-61 alphanumeric or dash characters, then a single alphanumeric character for a maximum of 63 (1 + 61 + 1).
