### ISSUE TITLE
Allow deleting the Logging Buckets

### ISSUE THREAD

**Issue by LudovicEmoAirbus** [hashicorp/terraform-provider-google#11412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When a google_logging_project_bucket_config resource is destroyed, the actual logging bucket deletion is not triggered.
This is _as designed_ and documented in [1], however this prevent us to run configurations to create / destroy structures automatically without manual actions.

###  Affected Resource(s)

* google_logging_project_bucket_config

### References

* [1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config

**Comment by rileykarson** [comment]
@slevenick to investigate

**Comment by slevenick** [comment]
Buckets do have a delete method on them: https://cloud.google.com/logging/docs/reference/v2/rest/v2/billingAccounts.locations.buckets/delete

Only certain buckets cannot be deleted (_Required & _Default) but it seems like the rest can be? We may be able to implement a delete method that skips if the bucket is undeletable, but otherwise attempts to delete.
