### ISSUE TITLE
Firestore single field index exemption

### ISSUE THREAD

**Issue by mbyrne00** [hashicorp/terraform-provider-google#11419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I can not find a way to add a [single field index exemption](https://cloud.google.com/firestore/docs/query-data/indexing#add_a_single-field_index_exemption) via terraform. This is useful when we have large nested objects that we do not want indexed. This reduces overhead when payloads can be large and/or inconsistent. Our example is storing webhook payloads for reference - we only want to index the metadata and leave the payload as is (without converting to/from `string` as a workaround).

Note that this is about _exemptions_ and different to the following issue that I found: https://github.com/hashicorp/terraform-provider-google/issues/7593.

### New or Affected Resource(s)

* `google_firestore_index` or a new one specifically for `_exemption`

### Potential Terraform Configuration

```tf
resource "google_firestore_index_exemption" "my-field-exemption" {
   collection = "my-collection"
   field_path = "myNestedObjectToIgnore"
 }
```

### References

* https://cloud.google.com/firestore/docs/query-data/indexing#add_a_single-field_index_exemption
* b/275099334

**Comment by rileykarson** [comment]
Note: Not sure if this is a new resource or not, as the docs only have Console links. It doesn't appear as a resource in the API, at least.

**Comment by brabster** [comment]
Supporting the [index definition JSON](https://firebase.google.com/docs/reference/firestore/indexes) might be the way to do this?

**Comment by mbyrne00** [comment]
Thanks @brabster - good to have this as a backup. In our case we use firestore through gcp and _not_ firestore. We use `gcloud app deploy` to deploy our app with various `yaml` definitions for app, tasks, etc. We use `terraform` to set up anything that does not fall within standard `gcloud app deploy`. Ideally we'd like to avoid using `firebase` client as a third means but it's a good option to keep in mind, thanks.

**Comment by brabster** [comment]
Same position here @mbyrne00, Firestore in GCP - I'm hoping Terraform can support the index definition JSON directly if it's not able to support index exemptions one-by-one

**Comment by mbyrne00** [comment]
oh right, gotchya. Thanks for insights.

**Comment by melinath** [comment]
Possibly related to https://github.com/hashicorp/terraform-provider-google/issues/12151 as well

**Comment by pcostell** [comment]
I'll take ownership of implementation of this.

**Comment by pcostell** [comment]
Note: unless I don't understand the requests, I believe this and #7593 are in fact duplicates (single field indexes / exemptions are the same thing).

**Comment by mbyrne00** [comment]
Right - I wasn't aware index and exemption were the same under the hoods. If this is the case and we want to mark this issue as a duplicate it would be good to ensure exemption is explicitly verified in #7593 as a testing criterion before closing.
