### ISSUE TITLE
Memorystore Redis should not recreate instance with new provider version 4.16.0

### ISSUE THREAD

**Issue by ricardoarias-tempus** [hashicorp/terraform-provider-google#11425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.3

### Affected Resource(s)

* google_redis_instance

### Description

We have an existing google_redis_instance. Upon upgrading to v4.16.0, the provider tried to add 

      + read_replicas_mode       = "READ_REPLICAS_DISABLED" # forces replacement

Which was forcing replacement of our Redis. Please adjust the default values so that it will not force the replacement of existing Redis instances or back this change out until a major version release of the provider.

Our current fix is to pin version 4.15.0 and as a result no changes are made to the infrastructure.

**Comment by joe-a-t** [comment]
Looks related to https://github.com/hashicorp/terraform-provider-google/pull/11330

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/11410
