### ISSUE TITLE
Recreating secret in Secret Manager happens before it's deleted

### ISSUE THREAD

**Issue by yedpodtrzitko** [hashicorp/terraform-provider-google#11436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.16.0

### Affected Resource(s)

* `google_secret_manager_secret`

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">=4.16.0"
    }
  }

  backend "gcs" {
    bucket  = "xxx-terraform-state"
  }

}

provider "google" {
  project = var.project_id
  region  = var.region
}


locals {
  gcp_secrets = {
    GOOGLE_MAPS_API_KEY = var.GOOGLE_MAPS_API_KEY
  }
}

resource "google_secret_manager_secret" "app_secrets" {
  for_each = local.gcp_secrets

  secret_id = each.key

  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "app_secrets" {
  for_each = local.gcp_secrets

  secret = google_secret_manager_secret.app_secrets[each.key].id

  secret_data = each.value
}
```

### Debug Output

Dont have debug output, sorry. The normal one is here:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # google_secret_manager_secret.app_secrets will be destroyed
  # (because resource uses count or for_each)
  - resource "google_secret_manager_secret" "app_secrets" {
      - create_time = "2021-10-19T11:53:15.697050Z" -> null
      - id          = "projects/xxx-production/secrets/GOOGLE_MAPS_API_KEY" -> null
      - labels      = {} -> null
      - name        = "projects/xxx/secrets/GOOGLE_MAPS_API_KEY" -> null
      - project     = "xxx-production" -> null
      - secret_id   = "GOOGLE_MAPS_API_KEY" -> null

      - replication {
          - automatic = true -> null
        }

      - timeouts {}
    }

  # google_secret_manager_secret.app_secrets["GOOGLE_MAPS_API_KEY"] will be created
  + resource "google_secret_manager_secret" "app_secrets" {
      + create_time = (known after apply)
      + expire_time = (known after apply)
      + id          = (known after apply)
      + name        = (known after apply)
      + project     = (known after apply)
      + secret_id   = "GOOGLE_MAPS_API_KEY"

      + replication {
          + automatic = true
        }
    }

  # google_secret_manager_secret_version.app_secrets["GOOGLE_MAPS_API_KEY"] will be created
  + resource "google_secret_manager_secret_version" "app_secrets" {
      + create_time  = (known after apply)
      + destroy_time = (known after apply)
      + enabled      = true
      + id           = (known after apply)
      + name         = (known after apply)
      + secret       = (known after apply)
      + secret_data  = (sensitive value)
    }

Plan: 2 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_secret_manager_secret.app_secrets: Destroying... [id=projects/xxx-production/secrets/GOOGLE_MAPS_API_KEY]
google_secret_manager_secret.app_secrets["GOOGLE_MAPS_API_KEY"]: Creating...
google_secret_manager_secret.app_secrets: Destruction complete after 3s
╷
│ Error: Error creating Secret: googleapi: Error 409: Secret [projects/xxx/secrets/GOOGLE_MAPS_API_KEY] already exists.
│
│   with google_secret_manager_secret.app_secrets["GOOGLE_MAPS_API_KEY"],
│   on main.tf line 31, in resource "google_secret_manager_secret" "app_secrets":
│   31: resource "google_secret_manager_secret" "app_secrets" {
│
```

### Expected Behavior

- recreating the secret should happen after the original one is deleted

### Actual Behavior

- the secret is attempted to be created before deleting the existing one finishes

### Steps to Reproduce

there could be a way with fewer steps, but my current flow is as follows:

1.  create a secret in GCP Secret Manager manually
2. import the secret `terraform import google_secret_manager_secret.app_secrets GOOGLE_MAPS_API_KEY`
3. use `for_each` for the definition secrets of secrets, so the imported resource does not match, and needs to be recreated
4. run `terraform apply` to recreate the secret

**Comment by rileykarson** [comment]
Creation order is managed by Terraform Core, and can't be affected by the provider. We only execute in the context of a single action on a single resource, so there's nothing to do here.

**Comment by yedpodtrzitko** [comment]
so should I open it as a bug in Terraform Core then?
