### ISSUE TITLE
CMEK is getting ignored when it's used in Cloud SQL Instances (google-beta provider)

### ISSUE THREAD

**Issue by bestefreund** [hashicorp/terraform-provider-google#11438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.1.7

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "postgres3-j638" {
  project             = var.project_id
  name                = "postgres-instance3-j638"
  database_version    = "POSTGRES_11"
  region              = var.default_region
  deletion_protection = false

  encryption_key_name = "projects/${var.key_project}/locations/${var.region}/keyRings/default_key_ring/cryptoKeys/sql-key-1"

  settings {
    tier = "db-custom-4-8960"
  }
}
```

### Expected Behavior

SQL instance gets deployed with CMEK

### Actual Behavior

CMEK is replaced with GMEK in existing SQL instances
encryption_key_name-attribute is not used in new SQL-Instances

### Steps to Reproduce

Define resource with encryption_key_name

1. Use google-beta-provider version 4.16.0
1. `export TF_LOG=TRACE`
2. `terraform plan`
3. encryption_key_name-attribute is missing in the API call that terraform does

### Workaround

Use google-beta provider  version 4.15

**Comment by bestefreund** [comment]
Maybe it is related to the change in this commit https://github.com/hashicorp/terraform-provider-google-beta/commit/c3ee405b349737333a43dab46fa93065124b2aa2 but I'm not sure

**Comment by bestefreund** [comment]
Sorry, but the issue still persists:

If we deploy new Instances with provider-version >= 4.16.0 then the attribute `encryption_key_name` is getting ignored.

1. New SQL-instances: Don't get a CMEK like before
2. Existing SQL-instances with CMEK: Are not getting touched, if you've deployed an instance with provider-version < 4.16.0 & running Terraform again with version 4.19.0

It seems that `encryption_key_name` shouldn't be used anymore.
Could this attribute disappear in the future?

**Comment by Harmelodic** [comment]
I think the implication of this being closed is that the code has been put into the provider, and then in the next version of the terraform provider (`4.20.0`) - the fix will be out.

Probably just a pre-emptive closure of the ticket.
