### ISSUE TITLE
Latest Composer-1 Deployments Failing due to latest REGEX change

### ISSUE THREAD

**Issue by sandy-0007** [hashicorp/terraform-provider-google#11432]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pullrequest-to-an-issue) the pull request to this issue.

### Terraform Version

```
Terraform v1.1.4
on linux_amd64

```

### Affected Resource(s)

- google_composer_environment

### Issue Description

When trying to deploy Composer latest version using Terraform, encountering the below error.

Error: "config.0.software_config.0.image_version" ("composer‑1.18.4‑airflow‑2.2.3") doesn't match regexp "composer-(([0-9]+)(\\.[0-9]+\\.[0-9]+(-preview\\.[0-9]+)?)?|latest)-airflow-(([0-9]+\\.[0-9]+)(\\.[0-9]+)?)"

Please fix this ASAP

**Comment by sandy-0007** [comment]
I also tried using the version aliases, still getting the same error.

` Error: "config.0.software_config.0.image_version" ("composer‑1‑airflow‑2") doesn't match regexp "composer-(([0-9]+)(\\.[0-9]+\\.[0-9]+(-preview\\.[0-9]+)?)?|latest)-airflow-(([0-9]+\\.[0-9]+)(\\.[0-9]+)?)"`

**Comment by rileykarson** [comment]
I believe this will get addressed in `4.18.0` by https://github.com/GoogleCloudPlatform/magic-modules/pull/5885

**Comment by rileykarson** [comment]
Filed https://github.com/hashicorp/terraform-provider-google/issues/11441 to address the composer environment validation treadmill in `5.0.0`, also.
