### ISSUE TITLE
ACM  - Prevent config drift option

### ISSUE THREAD

**Issue by bnovickovs** [hashicorp/terraform-provider-google#11449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Prior to Anthos Config Management version 1.10.0, the Config Sync admission webhook is enabled by default. Starting from Anthos Config Management version 1.10.0, the Config Sync admission webhook is disabled by default.

https://cloud.google.com/anthos-config-management/docs/how-to/prevent-config-drift - Currently, this can be applied only manually using gcloud command, via:

https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#configuring-config-sync (using existing manifest).

Manifest example:

[3]: configSync YAML file
applySpecVersion: 1
spec:
  configSync:
    # Set to true to install and enable Config Sync
    enabled: true
    # If you don't have a Git repository, omit the following fields. You
    # can configure them later.
    sourceFormat: unstructured
    syncRepo: 
    syncBranch: staging
    secretType: ssh
    gcpServiceAccountEmail: null
    policyDir: gke-stg-app
    # the `preventDrift` field is supported in Anthos Config Management version 1.10.0 and later.
    preventDrift: true

### New or Affected Resource(s)

* google_gke_hub_feature_membership

### Potential Terraform Configuration

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature_membership#configmanagement

preventdrift = true/false

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6090
