### ISSUE TITLE
Support BigQuery Omni external connection for AWS s3

### ISSUE THREAD

**Issue by ismailsimsek** [hashicorp/terraform-provider-google#11459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As we can create BigQuery external connections with Cloud SQL for federated query, we should support that with AWS as well.
similar request https://github.com/hashicorp/terraform-provider-google/issues/11053

### New or Affected Resource(s)

* google_bigquery_connection

### Potential Terraform Configuration

```tf
resource "google_bigquery_connection" "connection" {
  provider      = google-beta
  connection_id = "connection_to_aws_s3"
  location      = "US"
  description   = "A BigQuery external connection for AWS "
  aws {
    AWS_ACCOUNT_ID = "the ID number of the connection's AWS IAM user."
    ROLE_NAME            = "the role policy name you chose."
    AWS_LOCATION      = "an AWS location in Google Cloud. Must be set to aws-us-east-1."
    CONNECTION_NAME= "the name you give this connection resource."
  }
}
```

### References

* https://cloud.google.com/bigquery-omni/docs/aws/create-connection#bq

b/374162343

**Comment by voycey** [comment]
Are there any updates on this? With the release of BQ Omni and BigLake this is more important than ever in order to setup cross cloud external tables.

**Comment by DrFaust92** [comment]
[rileykarson](https://github.com/rileykarson) i think this can be closed.

[voycey](https://github.com/voycey) i think you will need to extract the name and "manually" construct the iam role arn when passing to the connection resource.

**Comment by chrisst** [comment]
I can confirm, there's really no way around the cycle. Because Omni is using web identity under the hood to make the auth connection between the two clouds it requires a bi-directional configuration. This is by definition always going to be a cycle. Unfortunately the best you can do is use string building for 1 direction and resource reference in the other direction. Here's how I've modeled and e2e AWS Omni connection: https://gist.github.com/chrisst/314d131aa42db685938dee24dea0f912, setting up the references this way, and throwing a sleep in there for IAM propagation, allows terraform to succeed in a single apply.

**Comment by voycey** [comment]
Thanks @chrisst - if I ever get back to Omni then I will definitely give this a go :) I did get this applying if you look in https://github.com/hashicorp/terraform-provider-google/issues/12018 however I dont remember how far I got with it after!

**Comment by chrisst** [comment]
@voycey If you pick Omni back up let me know and I'm happy to help get it working. I think it's even picked up a few new features in the 2 years since you last tackle it 😅
