### ISSUE TITLE
 Consumer Quota Override resource is a trap and doesn't work 

### ISSUE THREAD

**Issue by laithrafid** [hashicorp/terraform-provider-google#11450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

erraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/google v4.15.0
+ provider registry.terraform.io/hashicorp/google-beta v4.15.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.6.0
+ provider registry.terraform.io/hashicorp/helm v2.5.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.9.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)
google_service_usage_consumer_quota_override

### Terraform Configuration Files

```tf
 resource "google_service_usage_consumer_quota_override" "override" {
  provider       = google-beta
  for_each       = local.consumer_quotas
  project        = var.project_id
  service        = each.value.service
  metric         = urlencode("${each.value.metric}")
  limit          = urlencode("${each.value.limit}")
  override_value = each.value.value
  force          = true
}
```

### Debug Output

https://raw.githubusercontent.com/laithrafid/infra-api/main/terraform/googlecloud/modules/gke_create/apply.log

### Actual Behavior

```
 Error: Error creating ConsumerQuotaOverride: googleapi: Error 400: The consumer override value can only be set between 0 to 8.
│ Help Token: Ae-hA1P0ObF4wlmXBlR-sniEo9AUbu0ceZb5JrAfPsFe61LiIxaRWBJ2Y9RXW3A4KlNvYior43COSHjNQeDUhDL9_9rl_bRFS2Bf9CmwqCzyH6AF
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "?error_code=101038\u0026max=8",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "metadata": {
│       "max": "8"
│     },
│     "reason": "COMMON_QUOTA_CONSUMER_OVERRIDE_TOO_HIGH"
│   }
│ ]
│ 
│   with module.project_config.google_service_usage_consumer_quota_override.override["compute.googleapis.com-compute.googleapis.com/regional_in_use_addresses"],
│   on project_config/main.tf line 88, in resource "google_service_usage_consumer_quota_override" "override":
│   88: resource "google_service_usage_consumer_quota_override" "override" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`  of this sub-module https://github.com/laithrafid/infra-api/tree/main/terraform/googlecloud/modules/gke_create/project_config

### References
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override

Issue been reported with no fix 
1. https://github.com/hashicorp/terraform-provider-google/pull/5966
2. https://github.com/hashicorp/terraform-provider-google/issues/10017
3. https://github.com/hashicorp/terraform-provider-google/pull/10179
4. https://github.com/hashicorp/terraform-provider-google/pull/9876
5. https://github.com/hashicorp/terraform-provider-google/issues/9787
6. https://github.com/hashicorp/terraform-provider-google/issues/8369
7. https://github.com/hashicorp/terraform-provider-google/issues/7893
8. https://github.com/hashicorp/terraform-provider-google/issues/7570
9. https://github.com/hashicorp/terraform-provider-google/issues/7533
10. https://github.com/hashicorp/terraform-provider-google/pull/5979
11. https://github.com/hashicorp/terraform-provider-google/pull/5979

**Comment by melinath** [comment]
According to the error message you shared, `The consumer override value can only be set between 0 to 8.` Could you please provide a minimal reproducible case - that is, the smallest possible configuration (without variables or other external references) that demonstrates that this doesn't work even if you set a proper consumer override value? It looks like our automated tests are working fine for this resource.

**Comment by laithrafid** [comment]
consumer quotas can't be increased from terraform module , try whatever variables , and if you check all issues i included , all around same issue . 

Try to increase/overwrite any consume (i have tried to increase  COMPUTE ENGINE > IN_USE_ADRESSESS)

**Comment by rileykarson** [comment]
This is working as intended, see the documentation at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override.

> Consumer overrides cannot be used to grant more quota than would be allowed by admin overrides, producer overrides, or the default limit of the service.


The API is meant to self-limit quota rather than request new quota. What I think you're looking for is a _producer_ quota,  discussed at https://cloud.google.com/service-usage/docs/service-quota-model#overrides, which allows producers to allocate more quota to a consumer. That's what ultimately happens when you submit a QIR through the quotas page (and I wish there was an API to attempt a QIR!).

**Comment by laithrafid** [comment]
@rileykarson Yes exactly , i thought it's not limited to limit quotas , naming is very confusing , "Consumer overrides cannot be used to grant more quota than would be allowed by admin overrides, producer overrides, or the default limit of the service."
who's the producer of a quota (google cloud) admin quota (google cloud admin account/owner) consumer of a quota ( developers/cloud engineers) 
API to attempt a QIR! , i was trying to increase/override  "producer or maybe admin" quotas , i think it would be less confusing if you can fix your terraform module's documentation to be more aligned with google cloud's documentation.

**Comment by rileykarson** [comment]
I'm not sure aligning with the API on naming would help, their name for the resource is `services.consumerQuotaMetrics.limits.consumerOverrides` which would translate to `google_service_usage_services_consumr_quota_metrics_limits_consumer_overrides` in the provider.

> actually, to be more specific , i researched your google cloud documentation for any reference of "admin" and/or "producer" quotas

The https://cloud.google.com/service-usage/docs/service-quota-model page I linked appears to be public and covers consumer, admin, and producer overrides. There's also https://cloud.google.com/docs/quota linked from that page, which covers the broader topic. And https://cloud.google.com/service-usage/docs/manage-quota, linked from the service usage docs.

**Comment by laithrafid** [comment]
what quota is this below: 
1. Service quota  < my best guess
2. Consumer quota 
3. Admin quota


https://console.cloud.google.com/iam-admin/quotas
             service/quota
compute.googleapis.com/regional_in_use_addresses : 
                 quota limit
IN-USE-ADDRESSES-per-project-region

if my guess right , then only way to increase is throw console no terraform or gcloud cmd /API for it to increase this ,  QIR ?

**Comment by rileykarson** [comment]
Without an admin or consumer quota defined, you're hitting the service quota. Lower-level quotas are used to apply limits more restrictive than the service's producer quota.
