### ISSUE TITLE
Anthos Fleet API for ASM

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#11462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It looks like all we can do is enable/disable the feature, so this is likely just a matter of confirming we can enter the feature and create/delete it successfully.

### New or Affected Resource(s)

* google_gke_hub_feature

### Potential Terraform Configuration

```tf
resource "google_gke_hub_feature" "feature" {
  provider = google-beta

  name = "servicemesh"
  location = "global"
}
```

### References

* https://cloud.google.com/service-mesh/docs/managed/auto-control-plane-with-fleet
* Internal issue [[b/226186088](http://b/226186088)](http://b/226186088)

**Comment by ScottSuarez** [comment]
Missing documentation was added by ASM team.. this can now be supported fully
b/242868571

**Comment by melinath** [comment]
This seems to be resolved.
