### ISSUE TITLE
authenticator_groups_config block conflicts with enable_autopilot

### ISSUE THREAD

**Issue by soerenmartius** [hashicorp/terraform-provider-google#11475]
When deploying a GKE cluster with autopilot enabled using the `google_container_cluster` resource, the `authenticator_groups_config` causes a conflict. According to the [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/google-groups-rbac), autopilot supports group-based RBAC. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version: `v1.1.8`
Provider version: `v4.10.0`

### Affected Resource(s)

* google_container_cluster

### Debug Output

<img width="1143" alt="Screenshot 2022-04-12 at 18 00 06" src="https://user-images.githubusercontent.com/930643/163004843-caaba475-9fdb-4783-a43f-65b5335d4e0c.png">

### Expected Behavior

The provider should not ocnfl

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/mineiros-io/terraform-google-gke-autopilot-cluster/runs/5973604865?check_suite_focus=true

**Comment by melinath** [comment]
It looks like autopilot added support for RBAC. I'm marking this as an enhancement request to add support for allowing autopilot to work with authenticator_groups_config. It might be as simple as making the fields not conflict, but there's no API example in [the docs](https://cloud.google.com/kubernetes-engine/docs/how-to/google-groups-rbac#new-cluster) so I'm hesitant to say that would definitely work.

**Comment by soerenmartius** [comment]
> It looks like autopilot added support for RBAC. I'm marking this as an enhancement request to add support for allowing autopilot to work with authenticator_groups_config. It might be as simple as making the fields not conflict, but there's no API example in [the docs](https://cloud.google.com/kubernetes-engine/docs/how-to/google-groups-rbac#new-cluster) so I'm hesitant to say that would definitely work.

Thanks @melinath  - please keep us posted

**Comment by soerenmartius** [comment]
Seems like this has been fixed in version [4.16.0](https://github.com/hashicorp/terraform-provider-google/pull/11310)
