### ISSUE TITLE
Google Cloud Build trigger for external Bitbucket server

### ISSUE THREAD

**Issue by daniel-lerch** [hashicorp/terraform-provider-google#11499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We have our code hosted on a on-premises Bitbucket server and manually configured Google Cloud Build triggers to build and deploy changes to Google Cloud. Now we would like to manage our Cloud resources with Terraform but Bitbucket sources do not seem to be supported by the official Google Cloud Terraform provider.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_cloudbuild_trigger" "some-external-bitbucket-trigger" {
    name = "some-external-bitbucket-trigger"
    filename = "cloudbuild.yaml"

  bitbucket {
    hostUrl = "https://bitbucket.example.com"
    project = "OPTIGEM"
    repository = "webserver"
    branch = "^master$"
    invertRegex = false
  }
}
```

### References

* [BitbucketServerConfigs](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.bitbucketServerConfigs) REST API documentation by Google

**Comment by daniel-lerch** [comment]
For my team, this feature is not important enough to dive into the project, implement it on our own and opening a pull request.

**Comment by headincl0ud** [comment]
+1

**Comment by prateek2408** [comment]
Working on it
