### ISSUE TITLE
403: Forbidden when trying to SetIamPolicy in one project using a service account in another project.

### ISSUE THREAD

**Issue by ctwilleager-nt** [hashicorp/terraform-provider-google#11497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform Version: 0.13.3

### Affected Resource(s)

google_project_iam_member

### Terraform Configuration Files
Provider.tf:
```tf
# Set up provider to impersonate the above service account.
provider "google" {
  alias = "impersonation"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email"
  ]
}

# Retrieve a temporary access token to authenticate as the service account.
data "google_service_account_access_token" "default" {
  provider               = google.impersonation
  target_service_account = var.terraform_service_account
  scopes                 = ["userinfo-email", "cloud-platform"]
  lifetime               = local.access_token_lifetime
}

# Configure default provider.
provider "google" {
  project      = local.project_id
  access_token = data.google_service_account_access_token.default.access_token
}
```
main.tf:
```tf
locals {
  role_member_pairs = flatten([
    for iam_pair in var.iam_role_members : [
      for members in iam_pair.members : {
        role    = iam_pair.role
        members = members
      }
    ]
  ])
}

resource "google_project_iam_member" "iam_members" {
  for_each = { for pair in local.role_member_pairs : "${pair.role}-${pair.members}" => pair }
  project  = var.project_id
  role     = each.value.role
  member   = each.value.members
}
```
initialize.tf:
```tf
variable "project_id" {
  description = "The GCP Project ID."
  type        = string
}

variable "iam_role_members" {
  description = "The map of roles and their members."
}
```
iam.tf:
```tf
locals {
  iam_role_members = [
    {
      role = "roles/viewer"
      members = [
        "group:**REDACTED**",
        "group:**REDACTED**"
      ]
    }
  ]
}

```

### Expected Behavior

Terraform should update the IAM policy of the target project.

### Actual Behavior

Terraform is failing with the following error:
```
Error: Request `Create IAM Members roles/bigquery.metadataViewer group:bigquery-users-prod@**REDACTED**.com for project "**REDACTED**"` returned error: Batch request and retried single request "Create IAM Members roles/bigquery.metadataViewer group:bigquery-users-prod@**REDACTED**.com for project \"**REDACTED**\"" both failed. Final error: Error applying IAM policy for project "**REDACTED**": Error setting IAM policy for project "**REDACTED**": googleapi: Error 403: Policy update access denied., forbidden

  on .terraform/modules/gcp_iam_policy/gcp/iam/main.tf line 12, in resource "google_project_iam_member" "iam_members":
  12: resource "google_project_iam_member" "iam_members" {
```

### Steps to Reproduce

Our environment uses an "Operations" project that is the centerpiece for automation involving our other projects. To reproduce this issue, you'll need at least two projects. One project as your "Ops" project, and the other as your simulated "production" project.

1. In your "OPS" project, create a service account for Terraform to initially start with.
2. Create another service account that will actually perform the required changes in Terraform.
3. Generate and save the JSON keyfile for the service account. Additionally, you will want to remove all newlines from the JSON file.
4. Grant the service account you created in Step 1 the roles "Service Account User" and "Service Account Token Creator" on the account you created in Step 2.
5. In your "PROD" project, grant the service account you created in Step 2 the roles of "Project/Owner" and "Cloud Resource Manager/Project IAM Admin"
6. Set the environment variable **TF_VAR_terraform_service_account** to be the email address of the account you created in Step 1.
7. Set the environment variable **GOOGLE_CREDENTIALS** to be the JSON data of the key you created in Step 3.
8. In the **iam.tf** file, replace REDACTED with a group you want to assign a role to.

### Important Factoids
1. This process works for literally everything else. I can create service accounts in my projects, enable project APIs and services, and interact with other services (e.g. GKE, Composer, BigQuery, etc). It is only when I attempt to set IAM policy in the project, then Terraform fails.

**Comment by ctwilleager-nt** [comment]
That's the funny part @melinath. I assigned the appropriate role of **Project IAM Admin** to the service account based on what I found here: https://stackoverflow.com/questions/67907211/how-to-resolve-googleapi-error-403-the-caller-does-not-have-permission-forbi

I can even see the role **Project IAM Admin** that I assign does have the appropriate permissions: https://cloud.google.com/iam/docs/understanding-roles#resource-manager-roles

Yet even when I grant this role, the error returned is always the same. This occurs even when I set the role globally at the organization level.

**Comment by melinath** [comment]
@ctwilleager-nt if you set [TF_LOG=trace](https://www.terraform.io/internals/debugging) you can get some additional debugging information, which should include details about what service accounts are being used for particular requests.

Basically, I am pretty sure the only way this could be a provider bug is if somehow the service account you're asking TF to use is not the one that ends up getting used. Otherwise, it's probably an IAM configuration issue.

Based on your description so far I'm guessing there's probably something wrong with your IAM configuration, which would mean this is not a provider issue.

**Comment by ctwilleager-nt** [comment]
So the problem ultimately is Terraform not respecting the variable difference here:

```tf
# Retrieve a temporary access token to authenticate as the service account.
data "google_service_account_access_token" "default" {
  provider               = google.impersonation
  target_service_account = var.terraform_service_account
  scopes                 = ["userinfo-email", "cloud-platform"]
  lifetime               = local.access_token_lifetime
}
```
We use separate accounts for Terraform accounts for plan operations and apply operations. What's happening here is that Terraform does not respect the **target_service_account** being different during the apply phase. When we run the "plan" phase, Terraform is persisting the data resource to the remote state. When we then run the "apply" phase, supplying an entirely different variable for **target_service_account**, Terraform ignores the variable and instead reads the incorrect account from remote state which does not have the permissions to actually apply and runs the apply phase with the wrong account.

Is there any way to stop Terraform from doing this and actually respect the completely different variable we're providing during the apply phase?

**Comment by melinath** [comment]
Gotcha - so what's actually happening here is probably that the `access_token` output field is Computed, and Computed fields on data sources are cached during the "refresh" phase, which happens prior to the plan phase. See here for more details: https://www.terraform.io/language/data-sources#data-source-lifecycle

This is a core part of Terraform behavior, so we can't change it from the provider side. If you believe it's a bug (or want to request changing it) I would recommend checking out https://github.com/hashicorp/terraform
