### ISSUE TITLE
Failing test(s): Cannot create a classic VPN tunnel with dynamic routing

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11503]
This seems to be due to a change (deprecation) on the API side.

Failure rate:
- 100% since April 8 2022
- Still 100% June 16 2022

Impacted tests:
- TestAccComputeVpnTunnel_router
- TestAccComputeRouterInterface_withTunnel
- TestAccComputeRouterPeer_bfd
- TestAccComputeRouterPeer_enable
- TestAccComputeRouterPeer_basic
- TestAccComputeRouterPeer_advertiseMode

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/279518?buildTab=tests&expandedTest=-275576511208386806

Message:

```
Error: Error creating VpnTunnel: googleapi: Error 400: Invalid value for field 'resource.peerIp': '8.8.8.8'. Cannot create a classic VPN tunnel with dynamic routing. Peer IP is outside of Google. Peer IP has to be used by a Compute Engine VM. Other Classic VPN usages are deprecated., invalid
```

**Comment by melinath** [comment]
Possibly related to https://github.com/hashicorp/terraform-provider-google/issues/7528

**Comment by upodroid** [comment]
This was messy. Google really wants people to stop using this. You need to create a VM and have a external IP associated with it. This is validated by Google when the POST request is made for `google_compute_vpn_tunnel` resource.

Can we remove these tests entirely?

**Comment by ghabian** [comment]
I've created a PR with a proposed solution. I refactored instances of VPN gateway + attached router to an HA VPN gateway. With other minor changes the failing tests are now successful.

The other approach would have been to create micro instances, attach external IPs, and use the IPs as `peer_ip` to pass the validation check as part of the test. I felt HA VPN is the less resource-intensive way.

I didn't touch any test that was previously successful to keep the coverage there.

**Comment by AarshDhokai** [comment]
It seems like all the tests have not failures in both [Google Cloud](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/357662?buildTab=tests&pager.currentPage=1&status=all&name=TestAccComputeRouter) and [Google Cloud Beta](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/357263?buildTab=tests&pager.currentPage=1&status=all&name=TestAccComputeRouter)
