### ISSUE TITLE
Failing test(s): TestAccDatastoreIndex_datastoreIndexExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11506]
Failure rate:
- 16% in Mar 2022

Impacted tests:
- TestAccDatastoreIndex_datastoreIndexExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/279518?buildTab=tests&expandedTest=-4052695643890826960

Message:

```
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: Error waiting for Deleting Index: couldn't find resource (21 retries)
```

```
Error: Error waiting to create Index: Error waiting for Creating Index: couldn't find resource (21 retries)
```

**Comment by AarshDhokai** [comment]
It seems like the test has no failures in [Google Cloud](https://ci-oss.hashicorp.engineering/test/-4052695643890826960?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) and [Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/-4052695643890826960?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)
