### ISSUE TITLE
cloudbuild: updated trigger cant be launched

### ISSUE THREAD

**Issue by lindmin** [hashicorp/terraform-provider-google#11514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform : 1.1.8
google-provider=4.17.0

### Affected Resource(s)

* google_cloudbuild_trigger

### Terraform Configuration Files

```tf

terraform{
required_providers {
    google = {
      version = "4.17.0"
    }
  }
}

data "google_project" "gcp-project" {
  project_id = "earn-app-341516"
}

resource "google_sourcerepo_repository" "src-repo" {
  name    = "sourceRepoName"
  project = data.google_project.gcp-project.project_id
  lifecycle {
    ignore_changes = [
      size
    ]
  }
}

resource "google_cloudbuild_trigger" "deploy-trigger2" {
  project = data.google_project.gcp-project.project_id
  name   = "deploy-trigger2"
  trigger_template {
    branch_name = "master"
    project_id  = google_sourcerepo_repository.src-repo.project
    repo_name   = google_sourcerepo_repository.src-repo.name
}
#  substitutions = {
#       "_ENV"="TOTO"
#   }
  depends_on = [
    google_sourcerepo_repository.src-repo,
  ]
  filename = "cloudbuild.yaml"
}

```

### Debug Output

https://gist.github.com/lindmin/6b78067676ccbb86e79c40f20ec1bad4

### Panic Output

N/A

### Expected Behavior

The trigger is created, and can be triggered manually via the console without problem

### Actual Behavior

The trigger is modified, but cant be launched. An approval is requested (not desired), and when i try to approve it in cloud console, i get this error message :  
_might not have been approved: Unrecoverable data loss or corruption._
![image](https://user-images.githubusercontent.com/7021711/163565987-42f0567b-32b7-40be-8e1b-88febdb8b858.png)

When i downgrade to google provider version 4.16.0, the problem disappear.

### Steps to Reproduce

1. `terraform apply` to create the source repo and the trigger
2.  uncomment the substitutions section
3. `terraform apply` to add the substitutions vars to trigger
4. trigger manually the trigger

### References

* #0000

**Comment by shuyama1** [comment]
Hi @lindmin! Would you mind sharing the full debug logs. Thanks a lot!

**Comment by lindmin** [comment]
Hello @shuyama1 ,  thanks for your reply.

I added the debug output and  modify the steps to reproduce/ terraform code.

I tried this code in my personal project, and it appears that the problem exist only when the updating process of terraform.

Do you need some extras infos ?

thanks.

**Comment by lindmin** [comment]
any news ?

**Comment by shuyama1** [comment]
@lindmin Sorry for the delay on this issue. Looks like the server returns an empty approvalConfig block during update process which triggered a bug from API side. Reported by the service team, the bug should be fixed by now. I just tried to follow your steps + configs and was not able to reproduce the error this morning, but I could have missed something. Can you confirm that you are still seeing the error with version 4.17.0+?

**Comment by lindmin** [comment]
Hello @shuyama1 ,

I tested again in 4.17, the trigger can now be updated and run without error.

Thanks a lot !
