### ISSUE TITLE
Error 409: Requested entity already exists when creating a second project in a folder. 

### ISSUE THREAD

**Issue by bladerunnerp** [hashicorp/terraform-provider-google#11522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.17.0

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
resource "google_project" "Engineering-main" {
  name       = "Engineering-Root"
  project_id = "engineering-root"
  folder_id  = google_folder.Engineering.name
}

resource "google_project" "Engineering-sandbox" {
  name       = "Engineering-Sandbox"
  project_id = "engineering-sandbox"
  folder_id  = google_folder.Engineering.name
}
```

### Debug Output

https://gist.github.com/bladerunnerp/1179c314c9e610aaef87c67e71fb5769

### Expected Behavior

I create a folder called Engineering, then I create a project of Engineering-main. 
I then create as second project in the same folder called Engineering-sandbox. 
This second project should be created.

### Actual Behavior

The first project is created without error. The second project fails with 409. 
This also seems to happen when trying to rename a project, which triggers a recreation, which fails after destroying the resource. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by shuyama1** [comment]
Hi @bladerunnerp, thanks for filing the issue. I was able to reproduce the error using the config provided. I believe the cause of this error is we are trying to use a project id which is already taken, as ids are supposed to be globally unique identifiers for projects (https://cloud.google.com/resource-manager/docs/creating-managing-projects).
I changed the project ids to `engineering-root-1` and `engineering-sandbox-1`, and was able to create the projects without any errors. Could you try changing the ids to something else and see if that works for you?

**Comment by bladerunnerp** [comment]
Hello, thank you for looking into this! I tried your suggestion and the plan requires engineering-root to be destroyed and recreated as engineering-root-1. This fails with the "already exists" condition I reported in this issue.

**Comment by shuyama1** [comment]
Looks like `engineering-root-1` is also not available, which could due to the fact that I used it to create a project. Looks like `engineering-root-3` and `engineering-sandbox-3` are non-taken. Maybe try with those?

**Comment by bladerunnerp** [comment]
So they need to be unique globally, across all of google? Seems I can work around this by appending a random number to the end of the name.

**Comment by bladerunnerp** [comment]
I can accomplish my goal this way. Though, I do feel this should be in-built behavior, as it's not very intuitive. 

`resource "random_id" "project" {
  byte_length = 4
}

resource "google_project" "Engineering-main" {
  name       = "Engineering-Root"
  project_id = "engineering-root-${random_id.project.hex}"
  folder_id  = google_folder.Engineering.id
}

resource "google_project" "Engineering-sandbox" {
  name       = "Engineering-Sandbox"
  project_id = "engineering-sandbox-${random_id.project.hex}"
  folder_id  = google_folder.Engineering.id
}`

**Comment by bladerunnerp** [comment]
After more careful reading of the google cloud provider docs, I see that I was incorrectly expecting google_project resource to behave like the google_folder resource and create a numerical id under the hood, but I understand now that this is not the case. Whether or not this is to be considered a usability bug or not can rest with hashicorp, but I think we're ok to close this issue. 

For anyone who may stumble upon it with the same troubles, please note that the code above is not my current preferred approach. I've included an example below of how I am now managing this until I get around to abstracting it out into a module. 

`resource "random_integer" "engineering-main" {
  min = 1
  max = 100000000000
}

resource "google_project" "Engineering-main" {
  name       = "Engineering-Root"
  project_id = random_integer.engineering-main.result
  folder_id  = google_folder.Engineering.id
}

resource "random_integer" "engineering-sandbox" {
  min = 1
  max = 100000000000
}

resource "google_project" "Engineering-sandbox" {
  name       = "Engineering-Sandbox"
  project_id = random_integer.engineering-sandbox.result
  folder_id  = google_folder.Engineering.id
}`
