### ISSUE TITLE
google_workflows_workflow should not revert external changes to workflow source code

### ISSUE THREAD

**Issue by craigafinch** [hashicorp/terraform-provider-google#11524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I suggest modifying  `google_workflows_workflow` so that it does not attempt to revert external changes to workflow source code, thus making it consistent with the behavior of `google_cloudfunctions_function`.  This behavior should be documented for both resources.

Why should the Terraform resource ignore external code changes? I want to _create_ workflows with Terraform, ensuring that critical options such as the service account are set correctly, and they should be subject to automated checks in our build/deploy pipeline for Terraform code. However, I want to _update_ my workflows via Cloud Build.  YAML source for workflows should be kept in a separate repo from Terraform source, for the following reasons:
*  The maintainers and owners of the workflow source code are not necessarily the same people who maintain the Terraform source, so repo access should be segmented
* An update to workflow YAML shouldn't require a PR on the Terraform repo
*  Automated linting and validation requirements are very different for YAML workflows vs. Terraform

I am already using `google_cloudfunctions_function` this way, and it's working well. 

### New or Affected Resource(s)

* google_workflows_workflow 
* google_cloudfunctions_function

### Potential Terraform Configuration

No code change is necessary, but you could create an option to let users choose whether or not the Terraform resource should control the source code:
```tf
resource "google_workflows_workflow" "example" {
  name            = "example"
  region          = var.region
  description     = "This is an example"
  service_account = module.my_service_account.email
  source_contents = templatefile(
      "${path.module}/workflow.tftpl", {target_host="${google_compute_address.internal.address}:443"}
  )
  ignore_source_changes = true
}
```

### References

1. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workflows_workflow
2. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function

**Comment by rileykarson** [comment]
You can use `lifecycle.ignore_changes` to control update behaviour on the field. The difference between the resources is that this references source _contents_ while function references a file by name.
