### ISSUE TITLE
panic from v4.17.0_x5 : runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by idy** [hashicorp/terraform-provider-google#11530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.8
on darwin_arm64
+ provider registry.terraform.io/aliyun/alicloud v1.164.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.19.0
+ provider registry.terraform.io/hashicorp/google v4.17.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.35.1
+ provider registry.terraform.io/itglobalcom/serverspace v0.2.2
+ provider registry.terraform.io/linode/linode v1.27.0
+ provider registry.terraform.io/vultr/vultr v2.10.1

### Panic Output

```
Stack trace from the terraform-provider-google_v4.17.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x130 pc=0x1045dbdc0]

goroutine 89 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceComputeInstanceUpdate(0x14000e05480, 0x105776460, 0x14000bce300, 0xffffffffffffffff, 0x14000d616b8)
        github.com/hashicorp/terraform-provider-google/google/resource_compute_instance.go:1389 +0x5d10
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000895420, 0x105822350, 0x14000637dc0, 0x14000e05480, 0x105776460, 0x14000bce300, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:363 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000895420, 0x105822350, 0x14000637dc0, 0x140005dadd0, 0x14000e05200, 0x105776460, 0x14000bce300, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:475 +0x2c0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000dea8, 0x105822350, 0x14000637dc0, 0x14000c21130, 0x104c35b5b, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0x870
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001b2880, 0x1058223f8, 0x14000637dc0, 0x14000cf8000, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x338
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x105703280, 0x140001b2880, 0x1058223f8, 0x14000dbae40, 0x14000da73e0, 0x0, 0x1058223f8, 0x14000dbae40, 0x14000cf2000, 0x576d)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000437a40, 0x10585a998, 0x140007224e0, 0x14000ce66c0, 0x14000142a50, 0x1066b8fc0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1282 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x14000437a40, 0x10585a998, 0x140007224e0, 0x14000ce66c0, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1616 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000362230, 0x14000437a40, 0x10585a998, 0x140007224e0, 0x14000ce66c0)
        google.golang.org/grpc@v1.44.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.44.0/server.go:919 +0x1f8

Error: The terraform-provider-google_v4.17.0_x5 plugin crashed!
```

**Comment by idy** [comment]
https://github.com/hashicorp/terraform-provider-google/blob/ec31c965a363f0c446c62359d04701f5a5f7303e/google/resource_compute_instance.go#L1389

If error is not nil, the instance should be nil and instance.name panics. is it?

**Comment by shuyama1** [comment]
Hi @idy, thanks for filing the issue! Would you mind sharing your config? Many thanks!

**Comment by idy** [comment]
If you want to reproduce the issue, you need:

1. first apply the config to create a compute instance.
2. update the compute instance, e.g. change the user name of the ssh-keys
3. terraform plan
4. use `gcloud-cli` or `console` delete it
5. terraform prev plan

```tf

data "google_compute_image" "ubuntu" {
  family  = "ubuntu-2004-lts"
  project = "ubuntu-os-cloud"
}


resource "google_compute_instance" "b11530" {
  name         = "b11530"
  machine_type = "e2-micro"

  boot_disk {
    initialize_params {
      image = data.google_compute_image.ubuntu.self_link
    }
  }

  network_interface {
    network = "default"
  }

  metadata = {
    ssh-keys = "y:${chomp(file("~/.ssh/id_rsa.pub"))}"
  }
}

```
