### ISSUE TITLE
Unable to provision google_healthcare_* resources

### ISSUE THREAD

**Issue by itsbalamurali** [hashicorp/terraform-provider-google#11532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```bash
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.18.0
```
### Affected Resource(s)

* google_healthcare_dataset
* google_healthcare_fhir_store

### Terraform Configuration Files

```tf
resource "google_healthcare_dataset" "dev_dataset" {
  project   = "some-test-project-id"
  name      = "dev-dataset"
  location  = "asia-south1"
  time_zone = "UTC"
}

# resource "google_pubsub_topic" "topic" {
#   name = "fhir-notifications"
# }

resource "google_healthcare_fhir_store" "dev_fhir_store" {
  name    = "dev-fhir-store"
  dataset = google_healthcare_dataset.dev_dataset.id
  version = "R4"

  enable_update_create          = false
  disable_referential_integrity = false
  disable_resource_versioning   = false
  enable_history_import         = true

  labels = {
    "enviroment" = "development"
  }
}

```

### Expected Behavior

Provision `google_healthcare_dataset` & `google_healthcare_fhir_store`.

### Actual Behavior

```bash
╷
│ Error: Error creating Dataset: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1/projects/projects/some-test-project-id/locations/asia-south1/datasets?alt=json&amp;datasetId=dev-dataset</code> was not found on this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_healthcare_dataset.dev_dataset,
│   on gcp_healthcare_datasets.tf line 1, in resource "google_healthcare_dataset" "dev_dataset":
│    1: resource "google_healthcare_dataset" "dev_dataset" {
```

### Steps to Reproduce

[Terraform Docs Example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_fhir_store#example-usage---healthcare-fhir-store-basic)

1. `terraform apply`

**Comment by slevenick** [comment]
From `│   <p>The requested URL <code>/v1/projects/projects/some-test-project-id/locations/asia-south1/datasets?alt=json&amp;datasetId=dev-dataset</code> was not found on this server.  <ins>That’s all we know.</ins>
`

It looks like you have a duplicate "projects/". Is your default project set to something like "projects/your-project-id"?

**Comment by itsbalamurali** [comment]
@slevenick that helped 🙏🏼 fix: `trimprefix(google_project.your_project.id,"projects/")` referencing `google_project` resource.
