### ISSUE TITLE
google_compute_security_policy with rules with action="throttle" fails to update after initial creation

### ISSUE THREAD

**Issue by liamstevens** [hashicorp/terraform-provider-google#11556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.6

#### Providers
provider registry.terraform.io/hashicorp/google v4.0.0
provider registry.terraform.io/hashicorp/google-beta v4.18.0

### Affected Resource(s)

google_compute_security_policy

### Terraform Configuration Files

```tf
resource "google_compute_security_policy" "backend_policy" {
  name = "kagi-policy"
  project = var.project
  provider = google-beta
  rule {
    action = "throttle"
    priority = "10003"
    match {
      expr {
        expression = "request.path.lower().matches('maps/')"
      }
    }
    rate_limit_options {
      rate_limit_threshold {
        count = 350
        interval_sec = 60
      }
      exceed_action = "deny(429)"
      enforce_on_key = "HTTP_COOKIE"
      enforce_on_key_name = "kagi_session"
      conform_action = "allow"
    }
    preview = true
  }
}
```

### Debug Output

See: https://gist.github.com/liamstevens/8974d3417f16cef1f50a0d62691ff3ed

### Expected Behavior

Terraform performs updates against resource and subresources (in this case, rules within the security policy resource)

### Actual Behavior

Terraform fails to apply this, giving an error regarding rate based bans which are not employed by the modified resource visible in the trace.

### Steps to Reproduce

1. Create `google_compute_security_policy` resource in Terraform configuration with at least 1 `rule` block that is using `action="throttle"`.
2. Run `terraform apply`
3. Modify the rule before running `terraform apply` again.

### Important Factoids

This particular run was done using user authentication, though this doesn't seem to have an impact.

**Comment by shuyama1** [comment]
Hi @liamstevens! Sorry for the delay on investigating this issue. Unfortunately I was not able to reproduce the error. Can you confirm if you are still seeing this issue recently with the latest version of provider? If so, would you mind sharing the config you use for both creating and updating the resource? Then I will try to reproduce the error and help debugging the issue.

**Comment by liamstevens** [comment]
Hi @shuyama1 , I haven't got any logs to hand for this one but it appears to only occur when the policy has a target. Removing the target allows for. I will update this the next time that I run anything against policy resources that have this condition. Perhaps that could help with repro?

**Comment by shuyama1** [comment]
@liamstevens Thanks for the quick response! It would be nice if you cloud provide the logs here when you run into the issue next time. Would you mind if we just close this since you are not having any issues for now. Feel free to reopen it if the similar errors happen again in the future.

**Comment by liamstevens** [comment]
Sure, I will re-open when I run into this next.
