### ISSUE TITLE
Enable the management of router interfaces and bgp peers of partner interconnects

### ISSUE THREAD

**Issue by a200462790** [hashicorp/terraform-provider-google#11560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today it is not possible to manage bgp peers for partner interconnect attachments using native terraform.

When an interconnect attachment is created for a partner interconnect, an interface and bgp peer is created behind the scenes. This prevents creating the interface and configuring the bgp peer via native terraform due to errors. 
`Error 400: The interfaces 'tf-explicit-interface' and 'auto-ia-if-on-prem-attachm-45634' are linked to the same interconnectAttachment., badRequest`
and 
`googleapi: Error 400: Invalid value for field 'resource.interfaces[0]': ''. Interface "auto-ia-if-on-prem-attachm-45634" has multiple associations: BGP peer auto-ia-bgp-on-prem-attachm-45634; BGP peer tf-explicit-peer, invalid`

### New or Affected Resource(s)

* google_compute_router_peer
* google_compute_router_interface datasource

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
data "google_compute_router_interface" "dynamic_interface" {
  router     = google_compute_router.router.name
  region     = "us-central1"
  interconnect_attachment   = google_compute_interconnect_attachment.attachment.id
}
# This resource will acquire and update the resource that was dynamically created
resource "google_compute_router_peer" "peer" {
  // name                      = "peer" <-- make name optional
  router                    = google_compute_router.router.name
  region                    = "us-central1"
  peer_ip_address           = "169.254.1.2"
  peer_asn                  = 65513
  advertised_route_priority = 100
  interface                 = data.google_compute_router_interface.dynamic_interface.name
}
```

### References

* This can behave similar to [logging bucket](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config):
"Creating a resource of this type will acquire and update the resource that already exists at the desired location."

**Comment by rileykarson** [comment]
I think in this case we'd expect the user to use `terraform import` to pick up the resource. There are resources that don't work that way, but they're typically project singletons or have no other viable interaction model (i.e. IAM)

**Comment by cstamm** [comment]
By using terraform import, it doesn't allow for a single pass build, unless I am mistaken.
