### ISSUE TITLE
Datasource for google_compute_instance_group_manager

### ISSUE THREAD

**Issue by kutysam** [hashicorp/terraform-provider-google#11564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is no way of retrieving the instance group template from a google_compute_instance_group_manager at all. By doing a get, we are able to retrieve it https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/get. 

google_compute_instance_group doesn't have it, google_compute_instance_template doesn't state what it is attached to.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by AarshDhokai** [comment]
b/263548232

**Comment by AarshDhokai** [comment]
Duplicate with [this issue](https://github.com/hashicorp/terraform-provider-google-beta/pull/5002) and PR is Merged for the issue, hence closing this issue.

**Comment by kutysam** [comment]
@AarshDhokai any idea if 
google_compute_region_instance_group_manager will be supported as well?

its very similar to `google_compute_instance_group_manager`

**Comment by AarshDhokai** [comment]
Hey @kutysam I think it's already supported by GCP Terraform Provider,  [`google_compute_region_instance_group_manager`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager).

**Comment by AarshDhokai** [comment]
Hey @kutysam,  please open a new issue if a feature request is required, specifying all the details and feasible configuration. Thanks!

**Comment by kutysam** [comment]
Hey @AarshDhokai , I've created a new issue at https://github.com/hashicorp/terraform-provider-google/issues/13363
Thank you!
