### ISSUE TITLE
`google_container_node_pool` `upgrade_settings` cannot be dynamic

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-google#11578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.8
google v4.18.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Code is simplified for a minimal example here, in reality would have the fields set by variables/conditionals and have a bunch of other node pool options set (like specifying a cluster).

```tf
resource "google_container_node_pool" "main" {
  dynamic "upgrade_settings" {
    for_each = [1]

    max_surge       = 1
    max_unavailable = 0
  }
}
```

### Expected Behavior

The `upgrade_settings` arguments should have passed `terraform validate` in the same way that they pass if the configuration is:

```tf
resource "google_container_node_pool" "main" {
  upgrade_settings {
    max_surge       = 1
    max_unavailable = 0
  }
}
```

### Actual Behavior

```
│ Error: Unsupported argument
│ 
│   on main.tf line 5, in resource "google_container_node_pool" "main":
│    7:     max_surge       = 1
│ 
│ An argument named "max_surge" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 6, in resource "google_container_node_pool" "main":
│    8:     max_unavailable = 0
│ 
│ An argument named "max_unavailable" is not expected here.
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

In this super minimal example, you will still get the following validate failure because I'm not including a cluster in the snippet, but that is irrelevant to this specific issue.
```
│ Error: Missing required argument
│ 
│   on main.tf line 1, in resource "google_container_node_pool" "main":
│    1: resource "google_container_node_pool" "main" {
│ 
│ The argument "cluster" is required, but no definition was found.
```

### References

* #0000

**Comment by megan07** [comment]
Hi @joe-a-t, sorry you're running into this - I think you may be missing the content block that goes along with `for_each`, it worked for me like this:
```
resource "google_container_node_pool" "with_upgrade_settings" {
  ...
  dynamic "upgrade_settings" {
    for_each = [1]

    content {
      max_surge       = 1
      max_unavailable = 0
    }
  }
}
```
Let me know if you're still seeing issues with that change. Thanks!

**Comment by joe-a-t** [comment]
Yep, my bad, thanks. Slowly backing away in embarrassment now
