### ISSUE TITLE
Move IAM Workload Identity Pools to GA from Beta

### ISSUE THREAD

**Issue by itsbalamurali** [hashicorp/terraform-provider-google#11571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Move IAM Workload Identity Pool to GA from Beta Provider https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iam_workload_identity_pool

### New or Affected Resource(s)

* google_iam_workload_identity_pool
* google_iam_workload_identity_pool_provider

**Comment by DrFaust92** [comment]
[rileykarson](https://github.com/rileykarson) forgot to link this to PR, can be closed

**Comment by melinath** [comment]
This might be resolved by https://github.com/hashicorp/terraform-provider-google/pull/12065 but according to feedback on https://github.com/hashicorp/terraform-provider-google/issues/12140 it sounds like the GA version is not currently working - there may have been some changes to the API between beta and GA.

**Comment by melinath** [comment]
> This might be resolved by #12065 but according to feedback on #12140 it sounds like the GA version is not currently working - there may have been some changes to the API between beta and GA.

The bug was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6309 - so this is now resolved.

**Comment by melinath** [comment]
@jva-dot-sh It looks like workload identity pools are in GA: https://cloud.google.com/iam/docs/reference/rest/v1/projects.locations.workloadIdentityPools If you're seeing an issue with it, could you open a new bug ticket? https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=bug&template=bug.md
