### ISSUE TITLE
Add support for Cloud Logging Log Buckets

### ISSUE THREAD

**Issue by U03A9** [hashicorp/terraform-provider-google#11572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the Google Terraform Provider does not support the creation or management of Cloud Logging Log Buckets. A primary use case for generating these resources with Terraform is to provision a Cloud Logging bucket to be declared as the logging bucket for a Cloud Storage bucket using Terraform. Currently, you would need to instantiate these Cloud Logging Log Buckets in the console. At that point, you could enforce the declaration of a `logging{}` attribute through Sentinel. You are able to configure this with a PubSub target, a Cloud Storage bucket, BigQuery Dataset, or a Cloud Logging log bucket. 

Our goal is to require the use of a Cloud Logging log bucket as the resource with the ability to provision control of these resources through Terraform.

### New or Affected Resource(s)

google_logging_log_bucket 

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_logging_log_bucket" "example_bucket"{
  description   =  "Example logging bucket"
  retentionDays =  30
  locked        =  false
  cmekSettings {
    kmsKeyName        =  "my-kms-key"
    kmsKeyVersionName =  "1"
  }
  indexConfigs = [
    {
      fieldPath =  "someField.intValue"
      type      =  "INDEX_TYPE_INTEGER"
    },
    {
      fieldPath =  "someOtherField.stringValue"
      type      =  "INDEX_TYPE_STRING"
    }
  ]
  restrictedFields = [
    "someField",
    "someOtherField"
  ]
}
```

### References
Buckets can be declared in a variety of ways and are documented here
https://cloud.google.com/logging/docs/reference/v2/rest
https://cloud.google.com/logging/docs/reference/v2/rest/v2/folders.locations.buckets
https://cloud.google.com/logging/docs/reference/v2/rest/v2/locations.buckets
https://cloud.google.com/logging/docs/reference/v2/rest/v2/organizations.locations.buckets
https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets

Buckets can be updated using the patch method
https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets/patch

### Related or fixes
None that I could find associated specifically with Cloud Logging Log Buckets.

**Comment by rileykarson** [comment]
@c2thorn to distinguish from google_logging_project_bucket_config (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config)

**Comment by c2thorn** [comment]
Given the endpoint linked and schema, this is the same resource as https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config

**Comment by benjamin-heimann-db** [comment]
> Given the endpoint linked and schema, this is the same resource as https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config

The [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config) does not reflect that this resource can also create new logging buckets. 
The name **xxx_bucket_config** and the current documentation suggest that it can only modify existing logging bucket configurations.

I was only able to find out how it works by searching in the source code of this repository:
https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_logging_bucket_config.go#L121.

Only if the parent type is "project" it will attempt to create the resource. 
On attempt to create a custom logging bucket in a folder, no specific error message is printed and the state is leaved in a corrupted state after Terraform Apply.

Also if someone tries to specify the bucket via name (and not id), Terraform plan goes green and apply fails with leaving the state corrupted. The faulty resource can then only be deleted manually from the state.

I don't know if i should create a new issue for this and how. 
But it took me some hours to understand it and maybe it is helpful for someone else.

**Comment by simonvanderveldt** [comment]
@c2thorn I'm not sure how the design of the `google_logging_project_bucket_config` resource came to be, but it doesn't really make sense to me. The API we're talking about (https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets) is just for creating/managing logging buckets, it says nothing about the configuration of the logging for the project. AFAIK one can create multiple custom logging buckets, but the `google_logging_project_bucket_config` only allows to define a single one. Also as far as I know Terraform always tries to stay as close as possible to the upstream API.

It seems to make more sense to just have a `google_logging_project_bucket` resource to allow users to create logging buckets. That maps 1:1 to GCP/the API and is also much clearer in its intent/usage which would prevent confusion for users as for example @benjamin-heimann-db explained happened to him.
