### ISSUE TITLE
Please add a google_sql_database datasource

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#11587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There should be a corresponding datasource for the google_sql_database resource and there is not:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/6265399/164732681-e728686e-b27d-46ab-a7bf-139d5947a1c9.png">

### New or Affected Resource(s)

* google_sql_database

### Potential Terraform Configuration

```tf
data "google_sql_database" "google_sql_database" {
   name     = "DBNAME"
  instance = "INSTANCE NAME
}
```

It would also be useful to get all databases on an instance and filter like aws_ami https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

```tf
data "google_sql_databases" "google_sql_database" {
   // would be nice to exclude DBs names matching a regex too
   name_exclude_regex     = "postgres"

   filter {
    name   = "name"
    values = ["mydb-*"]
   }

  instance = "INSTANCE NAME
}
```

### References

* #0000

**Comment by roaks3** [comment]
Looks like this was fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7055
