### ISSUE TITLE
Add Cloud function CMEK support

### ISSUE THREAD

**Issue by amandakarina** [hashicorp/terraform-provider-google#11581]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support to CMEK configuration on Cloud Functions

### New or Affected Resource(s)

* google_cloudfunctions_function
* google_cloudfunctions2_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  name        = "function-test"
  description = "My function"
  runtime     = "nodejs14"

  available_memory_mb   = 128
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  trigger_http          = true
  entry_point           = "helloGET"
  kms_key_name   = "projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKey/{crypto_key}"
}
```

### References

* [Google API](https://github.com/googleapis/google-api-go-client/blob/702783924de298b278434494e613adb302b45fe1/cloudfunctions/v1/cloudfunctions-gen.go#L543)

b/274818179

**Comment by DrFaust92** [comment]
kms_key_name is supported in cloudfunctions v1 but v2 doesnt support on api level

**Comment by k-ezis** [comment]
@rileykarson Feel free to assign this to me, I'll track internally

**Comment by rfparedes** [comment]
Is there an update or a workaround known to create a v2 function using a CMEK.  Without this, there can be no automation to create function.

**Comment by k-ezis** [comment]
Unfortunately CMEK isn't launched yet. It is being actively worked on and Terraform support is part of it's GA launch. Can you expand on the issue you're running into? We might be able to assist in a workaround in the meantime.

**Comment by rfparedes** [comment]
> Unfortunately CMEK isn't launched yet. It is being actively worked on and Terraform support is part of it's GA launch. Can you expand on the issue you're running into? We might be able to assist in a workaround in the meantime.

My terraform code tries to create a Cloud Function v2.  When creating a v2 function, two staging buckets are attempted to be created in Cloud Storage named "gcf-v2-sources-..." and "gcf-v2-uploads-...".  They fail to be created with the following error:

"module.functions.google_cloudfunctions2_function.function: Creating... | Error: Error creating function: googleapi: Error 400: Could not create bucket gcf-v2-sources-...  A default customer-managed encryption key (CMEK) on the bucket is request by an org policy in effect"

I have no control over the staging buckets. If I did, I could create staging buckets in advance with CMEK and use these instead.  Either way, I'm not sure of a workaround.

**Comment by rfparedes** [comment]
> Do you have a CMEK organization or project policy? Something like constraints/gcp.restrictNonCmekServices. If you have this applied it would result in the error you're seeing.

Yes.  And with organizational security requirements, this cannot change.

**Comment by k-ezis** [comment]
You can try creating the buckets before you create the function. You'd want to create two buckets with the following name format:
-gcf-v2-uploads-[project_number]-[region]
-gcf-v2-sources-[project_number]-[region]

and configure them with CMEK enabled. Then you'll need to update their CORS configuration to read: 

gcf-v2-uploads-[project_number]-[region]:
```
[
 {
   "method": [
     "PUT"
   ],
   "origin": [
     "https://*.cloud.google.com",
     "https://*.corp.google.com",
     "https://*.corp.google.com:*",
     "https://*.cloud.google",
     "https://*.byoid.goog"
   ],
   "responseHeader": [
     "content-type"
   ]
 }
]
```

gcf-v2-sources-[project_number]-[region]
```
[
  {
    "method": [
      "GET"
    ],
    "origin": [
      "https://*.cloud.google.com",
      "https://*.corp.google.com",
      "https://*.corp.google.com:*",
      "https://*.cloud.google",
      "https://*.byoid.goog"
    ]
  }
]
```

Then you can continue with the function creation as usual and the uploaded function code should be encrypted by CMEK.

**Comment by rfparedes** [comment]
Yes, thank you.  That worked.

**Comment by Ectelion** [comment]
Note that GCF 1st Gen already supports CMEK for Terraform as of Q2'2022: check out `docker_repository` and `kms_key_name` fields in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function#argument-reference

CMEK for GCF 2nd Gen is currently in public preview, and the Terraform support for it is on the shortlist.
