### ISSUE TITLE
[GKE] Support Reservation Affinity 

### ISSUE THREAD

**Issue by wuisawesome** [hashicorp/terraform-provider-google#11597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is a feature request to support setting reservation affinity on GKE clusters (via the `node_config` block of `google_container_cluster` and `google_container_node_pool`). This would be consistent with the GCP [REST](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#reservationaffinity) and [gRPC](https://github.com/googleapis/googleapis/blob/a0d4c5c2a714a7317714ba6f0066a74ec8a9c10b/google/container/v1/cluster_service.proto#L682) APIs.

Reservation affinity for GKE is described in more detail [here](https://cloud.google.com/kubernetes-engine/docs/how-to/consuming-reservations). 

### New or Affected Resource(s)

* `google_container_cluster`
* `google_container_node_pool`

### Potential Terraform Configuration

```tf
# Consume a specific reseration.
resource "google_container_node_pool" "a_node_pool" {
  name       = "my-node-pool"
  location   = "us-central1"
  cluster    = google_container_cluster.primary.name
  node_count = 1

  node_config {
    machine_type = "e2-medium"
    reservation_affinity {
      consume_reservation_type = "SPECIFIC_RESERVATION"
      key = "googleapis.com/reservation-name"
      values = ["my-reservation-1", "reservation-2"]
    }
  }
}

# Other reservation types with less fields.
resource "google_container_node_pool" "another_node_pool" {
  name       = "my-node-pool"
  location   = "us-central1"
  cluster    = google_container_cluster.primary.name
  node_count = 1

  node_config {
    machine_type = "e2-medium"
    reservation_affinity {
      consume_reservation_type = "ANY_RESERVATION"
    }
  }
}
```

### References

* [GKE Documentation on reservation affinity.](https://cloud.google.com/kubernetes-engine/docs/how-to/consuming-reservations#whats_next)
* [gRPC service definition for setting reservation affinity when creating a cluster](https://github.com/googleapis/googleapis/blob/a0d4c5c2a714a7317714ba6f0066a74ec8a9c10b/google/container/v1/cluster_service.proto#L682).

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6412
