### ISSUE TITLE
permission error when using google_monitoring_alert_policy for cloud sql

### ISSUE THREAD

**Issue by irimiaionut1988** [hashicorp/terraform-provider-google#11603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform version: 1.0.3
Installed hashicorp/google v4.16.0 (signed by HashiCorp)

### Affected Resource(s)
* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "cloudsql-alerts-password" {
  display_name = "Failed password authentication"
  combiner     = "OR"
  conditions {
    display_name = "Log match condition"
    condition_matched_log {
      filter = "resource.type=\"cloudsql_database\"\nresource.labels.project_id=\"${local.project}\"\nseverity=ALERT\ntextPayload =~ \".*FATAL:  password authentication failed.*\""
    }
  }
  documentation {
    content   = "Password authentication failed"
    mime_type = "text/markdown"
  }
  alert_strategy {
    notification_rate_limit {
      period = "3600s"
    }
  }
  notification_channels = [google_monitoring_notification_channel.email-to-platform-group.name]
}
```

### Debug Output

https://gist.github.com/irimiaionut1988/ecf016c67de3cad429ff702aa8dcac43
https://gist.github.com/irimiaionut1988/701d664a05454e428825fd46b09add99

### Panic Output

n / a

### Expected Behavior

We tried this 2 ways:
* existing resource, terraform should modify the alert
* new resource, terraform should create the resource

In GCP, in our project, the IAM principal executing this has the following roles assigned to it:
* Cloud SQL Admin
* Monitoring AlertPolicy Editor
* Monitoring NotificationChannel Editor
* Project IAM Admin

### Actual Behavior

For the 2 cases:
* terraform is hanging in the modify resource state, until timeout (around 40 mins. In the first gist, you can see I canceled it after 2 mins)
* terraform gives error 403 `googleapi: Error 403: projects/xxxxxx-cloud-sql-development -> User unauthorized to access xxxxxxx for resource projects/xxxxxx-cloud-sql-development/locations/global`

If we add one more permission to the IAM principal, then the resource gets updated successfully.
* Editor

### Steps to Reproduce

1. have a separate project in gcp
2. run terraform with a principal that has "limited" rights
3. If project editor role is missing, the resource will not be created

### Important Factoids

We are using a CI CD pipeline with gilab to run terraform. The IAM principal is actually a gitlab runner

### References

* #0000

**Comment by megan07** [comment]
Hi @irimiaionut1988, I'm sorry you're running into this issue. Would you verify that you can create the same alert policy in the console with the same permissions? This seems to be a permissions issue for which I would direct you to talk to a representative at Google, however, if you're able to create it in the console and not in Terraform, please let me know and I can take a look noting that difference. Thanks!

**Comment by irimiaionut1988** [comment]
I could not do the test in the console. However, I have found the IAM Policy Troubleshooter and it seems to me that GCP requires this project Editor permission for creating alert policies. I still consider this to be strange :)
