### ISSUE TITLE
Support networkTier in google_compute_global_address

### ISSUE THREAD

**Issue by 3150** [hashicorp/terraform-provider-google#11611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I got an error when ran `terraform plan` with this terraform file below. According to [REST Resource: globalAddresses](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses), networkTier argument can be used when reserving global ip.
```
resource "google_compute_global_address" "default" {
  name = "foo"
  projec  = "bar"
  networkTier = "STANDARD"
}
```

```
╷
│ Error: Unsupported argument
│ 
│   on ip.tf line 4, in resource "google_compute_global_address" "default":
│    4:   networkTier = "STANDARD"
│ 
│ An argument named "networkTier" is not expected here.

```

### New or Affected Resource(s)
`google_compute_global_address`

### Potential Terraform Configuration

```tf
resource "google_compute_global_address" "default" {
  name = "foo"
  project = "foo"
  networkTier = "STANDARD"
}
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address
- https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses

b/308248410

**Comment by 3150** [comment]
I would like to create PR to support networkTier argument if community and maintainers agree with it.

**Comment by rileykarson** [comment]
Yeah, feel free! Note this is a generated resource, so this would need to be against https://github.com/GoogleCloudPlatform/magic-modules

**Comment by 3150** [comment]
OK! I'll implement it from next week.

**Comment by NickElliot** [comment]
According to current documentation networkTier is locked to "PREMIUM" in global addresses and could not support any other value, so the original issue's config would not be possible. If there is further requests for this as an output-only or optional+computed field, please open a follow-up or respond to this issue, but as is there does not seem to be a purpose to including it within the Terraform schema.
