### ISSUE TITLE
Add support for enabling mutating webhook when installing PolicyController using google_gkehub_feature_membership

### ISSUE THREAD

**Issue by antonioribezzi-acc** [hashicorp/terraform-provider-google#11618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Policy Controller feature in Anthos Config Management on Google Cloud offers the possibility to enable Mutating Webhook feature, which allows administrators to mutate resources/set default values on the Kubernetes resources.
However, installing Anthos Config Management using the resource `gke_hub_feature_membership` does not have any option to activate this feature.

### New or Affected Resource(s)

* google_gkehub_feature_membership

### Potential Terraform Configuration

```tf
resource "google_gke_hub_feature_membership" "main" {
  configmanagement {
    policy_controller {
        mutation_enabled = true
    }
  }
}
```

### References

None

**Comment by rileykarson** [comment]
@slevenick: Can you raise with the DCL?

**Comment by slevenick** [comment]
b/231162352

**Comment by melinath** [comment]
This should be resolved - please re-raise otherwise.
