### ISSUE TITLE
Error when creating a budget

### ISSUE THREAD

**Issue by hulkk** [hashicorp/terraform-provider-google#11615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.1.9
Google provider v4.19.0

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
data "google_billing_account" "account" {
  billing_account = "<redacted>"
}

resource "google_billing_budget" "budget" {
  billing_account = data.google_billing_account.account.id
  display_name    = "Example Billing Budget"
  amount {
    specified_amount {
      currency_code = "USD"
      units         = "100"
    }
  }
  threshold_rules {
    threshold_percent = 0.5
  }
}
```

### Panic Output
N/A

### Expected Behavior

Example code for creating budget should work.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#example-usage---billing-budget-basic

### Actual Behavior

```
2022-05-01T10:11:55.8550260Z Plan: 1 to add, 0 to change, 0 to destroy.
2022-05-01T10:11:56.4909123Z google_billing_budget.budget: Creating...
2022-05-01T10:11:57.5572738Z Error: Error creating Budget: googleapi: Error 400: Request contains an invalid argument.

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hulkk** [comment]
This was due to wrong currency. My billing account is in EUR.

So maybe small clarification for documentation that currency has to be correct?

**Comment by c2thorn** [comment]
Hi @hulkk, sorry you ran into trouble with the example. In my opinion, you would have had a better experience if the error that was returned notified you which argument is invalid, and how.
That is an API returned error, and outside of the scope of the provider. Closing as I don't think there is much to do here.
