### ISSUE TITLE
Consolidate google_bigquery_reservation and  google_bigquery_reservation_assignment in docs

### ISSUE THREAD

**Issue by jclee2** [hashicorp/terraform-provider-google#11619]
### Description

Consolidate Documentation for [google_bigquery_reservation_assignment](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_reservation_assignment) and [google_bigquery_reservation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_reservation) 

They are showing a separate but should just be under the standardized BigQuery Reservation section as 2 sub-resource links

### New or Affected Resource(s)

Affected Resource

* google_bigquery_reservation
* google_bigquery_reservation_assignment

### Potential Terraform Configuration

N/A

### References

Issue #11215

**Comment by jclee2** [comment]
PR: https://github.com/hashicorp/terraform-provider-google/pull/11620

**Comment by DrFaust92** [comment]
[c2thorn](https://github.com/c2thorn) i see you are assigned so FYI i opened a quick PR for this
