### ISSUE TITLE
Key rotation with google_service_account_key with overlap retention

### ISSUE THREAD

**Issue by goobysnack** [hashicorp/terraform-provider-google#11626]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When using the keeper notation for key rotation, it replaces the existing key.  It seems there should be a way to keep the existing key with an overlap or retention period so as to avoid a race condition since service accounts are often used by applications and third parties or services.

### New or Affected Resource(s)

*google_service_account_key

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_service_account" "myaccount" {
  account_id = "myaccount"
  display_name = "My Service Account"
}

resource "time_rotating" "mykey_rotation" {
  rotation_days = 365
}

resource "google_service_account_key" "mykey" {
  service_account_id = google_service_account.myaccount.name

  keepers = {
    rotation_time = time_rotating.mykey_rotation.rotation_rfc3339
    retention_period = 90
  }
}
```

### References

* #11622 << Mistakenly labeled as a question - my bad.

**Comment by rileykarson** [comment]
Note: keepers are likely to be replaced by the upcoming `replace_triggered_by`, so we're unlikely to want to add more stuff to `keepers` as-is.

**Comment by goobysnack** [comment]
> Note: keepers are likely to be replaced by the upcoming `replace_triggered_by`, so we're unlikely to want to add more stuff to `keepers` as-is.

Understood.  Is there an option for retention period in `replace_triggered_by` block, or should it be part of the main block?

**Comment by goobysnack** [comment]
@rileykarson just checking in.  Is this possible?  To have a key rotation with a retention period for the current key, so that there's an overlapping period where both keys work?

**Comment by rileykarson** [comment]
Likely no- without the API implementing support for scheduling turning the key off, we're not likely to add support clientside.

**Comment by goobysnack** [comment]
It should be in the API.  You can add a key without deleting the old one right?  This shouldn't be an API constraint, unless I'm mistaken @rileykarson

**Comment by rileykarson** [comment]
Marking as needing upstream support & closing.
