### ISSUE TITLE
Key rotation with google_service_account_key with overlap retention

### ISSUE THREAD

**Issue by goobysnack** [hashicorp/terraform-provider-google#11622]
Has anyone figured out a way to use the key rotation with google_service_account_key without deleting the existing keys?

Using this example replaces the existing keys instead of adding keys.  A rotation should involve and overlap period where both keys are active IMO.  Otherwise breaking race conditions will occur.

resource "google_service_account" "myaccount" {
  account_id   = "myaccount"
  display_name = "My Service Account"
}

resource "time_rotating" "mykey_rotation" {
  rotation_days = 30
}

resource "google_service_account_key" "mykey" {
  service_account_id = google_service_account.myaccount.name

  keepers = {
    rotation_time = time_rotating.mykey_rotation.rotation_rfc3339
  }
}

**Comment by goobysnack** [comment]
So, there should be a way to configure:

resource "google_service_account" "myaccount" {
  account_id = "myaccount"
  display_name = "My Service Account"
}

resource "time_rotating" "mykey_rotation" {
  rotation_days = 30
}

resource "google_service_account_key" "mykey" {
  service_account_id = google_service_account.myaccount.name

  keepers = {
    rotation_time = time_rotating.mykey_rotation.rotation_rfc3339
    retention_period = 90
  }
}

**Comment by c2thorn** [comment]
Closing in favor of https://github.com/hashicorp/terraform-provider-google/issues/11626
