### ISSUE TITLE
GKE Cluster creation: Google Compute Engine does not have enough resources available to fulfill request

### ISSUE THREAD

**Issue by macksclark** [hashicorp/terraform-provider-google#11633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
terraform v0.14.8

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files (if applicable)
```tf
# networks_location by default is set to "us-central1"

data "google_container_cluster" "mllp-{{$env}}" {
  name     = "mllp-{{$env}}"
  location = "{{$networks_location}}"
  project  = "$${module.project.project_id}"
}
```

### Issue Description
Flake in deploying the GKE cluster:
`Error waiting for creating GKE cluster: Try a different location, or try again later: Google Compute Engine does not have enough resources available to fulfill request: us-central1-f.`

But I believe the terraform provider should re-try automatically on a different zone if it doesn't already. Is there any way we can add retries/zone variations to this creation in the cluster module? 

### Important Factoids
N/a

### References
See the same issue in a previous tf issue, but that one wasn't related to adding retries, it was related to fixing the cleanup when this error occurs: https://github.com/hashicorp/terraform-provider-google/issues/3033

**Comment by c2thorn** [comment]
labeling as `persistent-bug` to discuss in next triage

**Comment by rileykarson** [comment]
@c2thorn to add context before triage

**Comment by c2thorn** [comment]
I believe I misread this the first time. We should not retry on different locations since that would  be changing the user-specified config and would cause diffs.

**Comment by macksclark** [comment]
I don't think this is changing the user-specified config, for location I specify `us-central1` but it's failing on a specific zone of that region `us-central1-f`. So I meant that we should be retrying on a specific zone if the first one is unavailable to allocate the GCE resources for our request.

**Comment by c2thorn** [comment]
> I don't think this is changing the user-specified config, for location I specify `us-central1` but it's failing on a specific zone of that region `us-central1-f`. So I meant that we should be retrying on a specific zone if the first one is unavailable to allocate the GCE resources for our request.

The underlying zone that is chosen when a region is specified is not managed by the provider, but by the API/GKE itself. I don't think there is a mechanism to change the chosen zone when a region is specified in `location`. Even if there were, we believe this shouldn't be arbitrarily chosen by the provider and the logic should come from the API/GKE.

**Comment by rileykarson** [comment]
There *is* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_locations to control the locations of nodes, but when not provided that's provided by the API. Given that wasn't specified, the issue here is that the API is picking a bad set of zones, then complaining about the set that it picked.
