### ISSUE TITLE
Clarify private_ip_google_access values

### ISSUE THREAD

**Issue by RafaelAybar** [hashicorp/terraform-provider-google#11637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to know which values accept the `private_ip_google_access`. It's not specified in the official documentation: 
[private_ip_google_access](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#private_ip_google_access)

### New or Affected Resource(s)

GCP provider documentation: [private_ip_google_access](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#private_ip_google_access)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by upodroid** [comment]
Hello

This is mentioned in the API Documentation at the top of the resource reference page. Note, the API fields are in camelCase and the terraform fields are in snake_case.

https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks
