### ISSUE TITLE
CMEK is getting ignored when it's used in Cloud SQL Instances replica in different region (google-beta provider)

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#11644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.1.7

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "replica_instance_manual" {
  provider = google-beta

  name                 = "myreplica1"
  project              = var.project_id
  region               = var.replica_region
  master_instance_name = module.postgres-sql-db.instance_name
  database_version     = "POSTGRES_13"
  encryption_key_name = google_kms_crypto_key.cloudsql_replica_key.id
  replica_configuration {
    failover_target = false
  }


  settings {
    tier              = local.database_tier
    activation_policy = "ALWAYS"
    ip_configuration {
      ipv4_enabled    = false
      private_network = data.google_compute_network.my_network.self_link
    }
    location_preference {
      zone = data.google_compute_zones.replica_zones.names[0]
    }
  }
}

```

### Expected Behavior
SQL instance gets deployed with CMEK

### Actual Behavior
Getting error
```
Error: Error, failed to create instance sin-my-pg-db-1-a03b53fe-replicarep-10: googleapi: Error 400: Invalid request: Disk encryption config is not specified for the cross region replica.., invalid
```

It is ignoring KMS keys passed for replica instance. Provider should ignore CMEK for replica in same region as primary instance only. For cross region replica keys are needed but provider is not passing it. 
### Steps to Reproduce
Create primary instance using CMEK and replica instance in a different region using CMEK. 

1. `terraform apply`

### References

* #0000

**Comment by mark-it-allen-db** [comment]
I think this is caused by v4.16.0 of the google-beta provider where I noticed the following fix...

sql: fixed bug where permadiff of `encryption_key_name` would show on `google_sql_database_instance` for replica instances. ([#4130](https://github.com/hashicorp/terraform-provider-google-beta/pull/4130))

Workaround (which at least makes it work again but re-introduces the bug for same-region replicas fixed above) is to set the google-beta provider version less than 4.16.0
google-beta = "< 4.16.0"

versions.tf
terraform {
  required_providers {
    google-beta = ">= 4.4.0, < 4.16.0"
  }
}
