### ISSUE TITLE
Bad Doc:  Example Usage - Pubsub Subscription Different Project

### ISSUE THREAD

**Issue by whyvez** [hashicorp/terraform-provider-google#11642]
### Affected Resource(s)

* google_pubsub_subscription

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#example-usage---pubsub-subscription-different-project

```diff
resource "google_pubsub_topic" "example" {
  project = "topic-project"
  name    = "example-topic"
}

resource "google_pubsub_subscription" "example" {
  project = "subscription-project"
  name    = "example-subscription"
-  topic   = google_pubsub_topic.example.name
+  topic   = google_pubsub_topic.example.id
}
```

b/302797491

**Comment by rileykarson** [comment]
BOD: verify this works as intended as-is, and if it does feel free to remove `bug`

**Comment by shigwata** [comment]
other examples are also wrong.

**Comment by melinath** [comment]
It looks like the tests for this example are currently skipped - we should enable them and fix the example as described above.

**Comment by glasser** [comment]
This error still exists in the docs. It was introduced in 2019 in @rileykarson 's PR https://github.com/GoogleCloudPlatform/magic-modules/pull/2342 which changed from `name` to `id`. Unfortunately the whole point of this example is that it is cross-project and requires `id`.

**Comment by glasser** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9637 should fix it.
