### ISSUE TITLE
google_cloudfunctions_function_iam_member not recreated when referenced cloud_function is destroyed and recreated

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/terraform-provider-google#11650]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.20.0
```

### Affected Resource(s)
* `google_cloudfunctions_function_iam_member`

### Terraform Configuration Files
```tf
resource "google_cloudfunctions_function" "foo" {
  available_memory_mb   = 128
  entry_point           = "Handler"
  max_instances         = 1
  name                  = "my-function"
  project               = "my-project"
  region                = "us-west1"
  runtime               = "go116"
  source_archive_bucket = "some-bucket"
  source_archive_object = "function.zip"
  service_account_email = "some-email"
  timeout               = 10
  trigger_http          = true
}

resource "google_cloudfunctions_function_iam_member" "bar" {
  cloud_function = google_cloudfunctions_function.foo.name
  member         = "allUsers"
  project        = google_cloudfunctions_function.foo.project
  region         = google_cloudfunctions_function.foo.region
  role           = "roles/cloudfunctions.invoker"
}
```

### Expected Behavior
When a `google_cloudfunctions_function` referenced by `google_cloudfunctions_function_iam_member` is destroyed & recreated (likely due to a manual `terraform taint` or a configuration change requiring destroy & recreate of `google_cloudfunctions_function`), `google_cloudfunctions_function_iam_member` should also be recreated to reference the newly-deployed Cloud Function created by `google_cloudfunctions_function`.

### Actual Behavior
Terraform destroys & recreates the `google_cloudfunctions_function`, but the plan did not include doing same on the `google_cloudfunctions_function_iam_member` which references the function. At the end of `terraform apply`, it shows a warning that the `google_cloudfunctions_function_iam_member` has been deleted outside of Terraform. A subsequent `terraform apply` is necessary to recreate it.

### Steps to Reproduce

1. `terraform apply` the sample configuration above.
2. `terraform taint` the `google_cloudfunctions_function`.
3. `terraform plan` and see that only `google_cloudfunctions_function` needs to be destroyed & recreated.
4. `terraform apply` to do so. Note that the end of `apply` includes a warning that `google_cloudfunctions_function_iam_member` has been destroyed outside of Terraform.
5. `terraform apply` again to create a `google_cloudfunctions_function_iam_member` which properly references the currently-deployed `google_cloudfunctions_function`.

**Comment by slevenick** [comment]
Due to https://github.com/hashicorp/terraform-plugin-sdk/issues/122

Looks like there is a workaround with the newest CLI described on that issue

**Comment by StephenWithPH** [comment]
> Looks like there is a workaround with the newest CLI described on that issue

Indeed! Thanks for the pointer. I'll close this issue with faith that the CLI function will work as expected once it's released as non-beta.
