### ISSUE TITLE
secondary IP ranges in Google_compute_subnetwork are not removed from GCP

### ISSUE THREAD

**Issue by cova-fe** [hashicorp/terraform-provider-google#11654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
> tf --version
Terraform v1.1.9
on linux_amd64
```

### Affected Resource(s)

*google_compute_subnetwork

### Expected Behavior

tf code requires to remove a secondary range from a subnetwork. No changes to the range, only removal

### Actual Behavior

Code fails silently, no resource is removed.

### Steps to Reproduce

1. Create a subnet with secondary range (tf apply)
2. Remove that secondary range from tf code, run apply again

### References

* #2570
please have a look at this comment: 
https://github.com/hashicorp/terraform-provider-google/issues/2570#issuecomment-528787804_

**Comment by slevenick** [comment]
@cova-fe are you trying to remove the secondary_ip_ranges set on a subnetwork?

Did you see this note on the field:

  **Note**: This field uses [attr-as-block mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html) to avoid
  breaking users during the 0.12 upgrade. To explicitly send a list
  of zero objects you must use the following syntax:
  `example=[]`

**Comment by cova-fe** [comment]
@slevenick Hi, yes, we are trying to do that. The problem is that the secondary_ip_ranges in the network are managed using a dynamic block so I'm not sure how to trigger the removal when the "each" construct is basically empty.

**Comment by cova-fe** [comment]
> Hmmm so the question is really how can we get a dynamic block to generate the empty array rather than a null value.
> 
> I'm not too familiar with dynamic blocks but I can try to poke around

Shall we open an issue in terraform repo to deal with this issue?

**Comment by slevenick** [comment]
This seems to be a similar issue? https://stackoverflow.com/questions/65424562/how-to-handle-empty-list-for-dynamic-block

It seems unsupported by the language, but can be used with an explicit ternary expression to add the empty list.
