### ISSUE TITLE
Google Container Cluster Node Pool: allow to specify Spot nodes

### ISSUE THREAD

**Issue by morsik** [hashicorp/terraform-provider-google#11651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google has new feature (in Beta) called Spot instances. Similarly to AWS Spot Instances, they can run longer than 24 hours (Preemptible can up to 24h and after that they are killed).

Some support for Spot instances is already there, for example in GKE Cluster spec: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#spot but it's impossible to set `spot = true` on manually created Node Pool as another resource.

This feature request asks for adding support for Spot VMs in `google-beta` similarly as it already exists in `google_container_cluster`.

### New or Affected Resource(s)

* `google_container_node_pool`

### Potential Terraform Configuration

Similarly like it's done in `google_container_cluster`.

```tf
spot = true
```

**Comment by rileykarson** [comment]
This should work if it does in GKE cluster- the implementation of `node_config` is shared between the resources. Can you post an error message + version from a config where it doesn't?

**Comment by morsik** [comment]
@rileykarson at the beginning I thought so, but it didn't worked for me.

After your reply I checked out it again, and it looks like I messed up providers configuration for `google-beta` and it actually loaded `google` instead ;)

In that case - confirmed working! Sorry for confusion.

But still worth updating docs tough.

**Comment by kelly-brown** [comment]
I don't believe that this in beta anymore.  What's the process/timeline to get it ported into the google provider?

**Comment by rileykarson** [comment]
@kelly-brown: Filing an FR will get it added by our engineering team or the service engineering at some point (but w/o a hard timeline), or it's possible to contribute- it's likely a routine change, just removing the version guards from it in Magic Modules (the code generator that manages the GA and beta providers, keeping them in sync). Original change @ https://github.com/GoogleCloudPlatform/magic-modules/pull/5443.

**Comment by rileykarson** [comment]
re: Updating the docs, `google_container_node_pool`'s `node_config` doc references the `google_container_cluster` documentation for the field, so this is as well-documented as any other field in `node_config`! Closing.

**Comment by kelly-brown** [comment]
> @kelly-brown: Filing an FR will get it added by our engineering team or the service engineering at some point (but w/o a hard timeline), or it's possible to contribute- it's likely a routine change, just removing the version guards from it in Magic Modules (the code generator that manages the GA and beta providers, keeping them in sync). Original change @ [GoogleCloudPlatform/magic-modules#5443](https://github.com/GoogleCloudPlatform/magic-modules/pull/5443).

Hey @rileykarson when you get to doing issue 11681, will that PR make it obvious to me on how to do this?  If so I'll try and run with that for spot when that one is done.
