### ISSUE TITLE
Pass environment variables to `google_cloudfunctions_function` inside a `dynamic` block

### ISSUE THREAD

**Issue by robgero** [hashicorp/terraform-provider-google#11668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be useful if you could pass a `map` to `google_cloudfunctions_function` `environment_variables` attribute inside a `dynamic` block. Where each key would become an environment variable name and each value would become the corresponding value.

A `map` of `object` might be more appropriate here, where the keys of each object could be something like `env_name` and `env_value`. As I'm not sure if the`dymanic` block would work using a simple `map`. However, I'll use  `map` in the example below to keep it simple.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

`variables.tf`
```tf
variable "env_vars" {
  type = map

  default = {
    FOO = "bar"
    BAZ = "qux"
  }
}
```

`main.tf`
```tf
resource "google_cloudfunctions_function" "function" {
  ...

  dynamic "environment_variables" {
    for_each = var.env_vars

    content {
        each.name = each.value
      }
  }
```
Then you could access the environment variables in your cloud function runtime:

```python
# python code in the example
import os

print(os.environ.get("FOO")) # would output: bar
```

**Comment by robgero** [comment]
```bash
git:(main) ✗ terraform --version           
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.20.0

git:(main) ✗ terraform plan
╷
│ Error: Unsupported block type
│ 
│   on modules/scheduled_function/main.tf line 54, in resource "google_cloudfunctions_function" "function":
│   54:   dynamic "environment_variables" {
│ 
│ Blocks of type "environment_variables" are not expected here.
╵
```

**Comment by rileykarson** [comment]
@ScottSuarez: Can you dedupe against an upstream or request one gets filed?

**Comment by ScottSuarez** [comment]
A dynamic block wouldn't be necessary for your usecase

You can just directly assign the map to the field in question.
```hcl
resource "google_cloudfunctions_function" "function" {
  name        = "function-test"
  description = "My function"
  runtime     = "nodejs14"

  available_memory_mb   = 128
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  trigger_http          = true
  entry_point           = "helloGET"

  environment_variables = var.env_vars
}

variable "env_vars" {
  default = {
    MY_ENV_VAR = "my-env-var-value"
    MYENV2= "my-second-env"
  }
  type = map(string)
}
```

**Comment by ScottSuarez** [comment]
closing this issue, please reopen if this solution doesn't work for you.
