### ISSUE TITLE
gcp_filestore_csi_driver_config default value for GKE cluster causes reconfiguration

### ISSUE THREAD

**Issue by des-esseintes** [hashicorp/terraform-provider-google#11666]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hello team!
The default value for gcp_filestore_csi_driver_config is false - this can be clearly seen for any GKE cluster in gcp web console. But this does not seem to be detected by terraform properly. When running a build I do see this:

```
~ addons_config {

    + gcp_filestore_csi_driver_config {
        + enabled = false
      }

      # (8 unchanged blocks hidden)
  }
  ```

and this causes a reconfiguration that takes up to 20+ minutes!
Am I wrong, or should this be changed, somehow?
(Not marking it as a bug, though)

### New or Affected Resource(s)

GKE

* google_container_cluster

### Potential Terraform Configuration

N/A

### References

N/A

Thanks!

**Comment by slevenick** [comment]
Can you provide a terraform config that causes the issue? I would like to be able to reproduce this before attempting to fix it

**Comment by des-esseintes** [comment]
I'll prepare a minimal config and report asap (got to get rid of 3 layers of modules first haha)
Thank you!

**Comment by slevenick** [comment]
I believe this is intended behavior of Terraform.

Basically your original config states that addons_config should be empty, then changing that to specify it should exist with the value of false *is* an explicit change even if the API defaults it to be the case.

**Comment by des-esseintes** [comment]
well, it's a pity if this can't be "fixed". though, it certainly looks weird to me when a property of a cluster is set to false in gcp, and explicitly defining it as "false" in terraform causes a reconfiguration that basically does nothing.

it's up to you guys.

**Comment by slevenick** [comment]
Yeah, the issue is that we can't tell what the API's default is if it isn't contained in the response. The API doesn't seem to return this field if it isn't sent, and we don't want to assume that an empty field has a certain meaning (we have done this before and it has caused big problems)

I don't believe we will fix this at this time
