### ISSUE TITLE
google_compute_firewall_policy_rule "action" docs are incorrect

### ISSUE THREAD

**Issue by pib** [hashicorp/terraform-provider-google#11677]
The [description of the google_compute_firewall_policy_rule `action` argument](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall_policy_rule#action) does not line up with the [VPC documentation on hierarchical firewall policies](https://cloud.google.com/vpc/docs/using-firewall-policies):

> (Required) The Action to perform when the client connection triggers the rule. Can currently be either "allow" or "deny()" where valid values for status are 403, 404, and 502.

It doesn't mention `goto_next` at all, and talks about HTTP status codes, which clearly don't apply to network-level firewall rules.

This seems to originate from [the declarative-resource-client-library schema for the firewall policy API](https://github.com/GoogleCloudPlatform/declarative-resource-client-library/blob/main/services/google/compute/firewall_policy_rule.yaml#L71), but issues are disabled on that repo, so I'm filing one here.

The [firewallPolicies addRule documentation](https://cloud.google.com/compute/docs/reference/rest/v1/firewallPolicies/addRule) also includes the same description.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_firewall_policy_rule

**Comment by slevenick** [comment]
Filed b/232122272 internally

**Comment by SirGitsalot** [comment]
b/232122272 is resolved, the fix should show up the next time the DCL is upgraded in the MM build.
