### ISSUE TITLE
Spurious diffs in clouddeploy sample/test generation

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#11692]
Spurious diff in generation on clouddeploy target annotations field. Seems to reorder keys in a map:

https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6025-old..auto-pr-6025#diff-f289764c05046084f1117d4415776ad0174a734cb1bd39f7cdcef652c71e67e7

**Comment by rileykarson** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/6058
