### ISSUE TITLE
Composer 2 - Failed to install PyPi Packages, cannot deleted instance

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#11711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

tf: v1.1.8
provider: 4.21.0

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
// Take the sample code from composer docs
resource "google_composer_environment" "test" {
  name   = "example-composer-env-tf-c2"
  region = var.region
  config {

    software_config {
      image_version = "composer-2-airflow-2"

      pypi_packages = {
        "google-cloud-bigquery" = "==1"
      }
    }

    private_environment_config {
      enable_private_endpoint = true
      master_ipv4_cidr_block  = "10.10.0.0/28"
    }

    workloads_config {
      scheduler {
        cpu        = 0.5
        memory_gb  = 1.875
        storage_gb = 1
        count      = 1
      }
      web_server {
        cpu        = 0.5
        memory_gb  = 1.875
        storage_gb = 1
      }
      worker {
        cpu = 0.5
        memory_gb  = 1.875
        storage_gb = 1
        min_count  = 1
        max_count  = 3
      }


    }
    environment_size = "ENVIRONMENT_SIZE_SMALL"

    node_config {
      network    = google_compute_network.test.id
      subnetwork = google_compute_subnetwork.test.id
      service_account = google_service_account.test.name
    }
  }
}

resource "google_compute_network" "test" {
  name                    = "composer-test-network3"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "test" {
  name          = "composer-test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = var.region
  network       = google_compute_network.test.id
}

resource "google_service_account" "test" {
  account_id   = "composer-env-account"
  display_name = "Test Service Account for Composer Environment"
}

resource "google_project_iam_member" "composer-worker" {
  project = var.project
  role    = "roles/composer.worker"
  member  = "serviceAccount:${google_service_account.test.email}"
}
```

### Debug Output

First apply that fails;

```
Error waiting to update Environment: Error waiting for Updating newly created Environment: Error code 9, message: Failed to install pypi packages.
│ Your service account is missing the required permissions to check the build log for errors. You can access them through Cloud Logging, or by running gcloud builds log [LOG_ID] --project [MY_PROJECT_ID].
```

The composer instance in GCP:
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/393945/168825817-5bfa2e88-bca5-48a6-9cf6-9400840df7bf.png">

State File:
```json
"resources": [
    {
      "mode": "managed",
      "type": "google_composer_environment",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "status": "tainted",
          "schema_version": 0,
          "attributes": {
            "config": null,
            "id": "projects/[MY_PROJECT_ID]/locations/europe-west2/environments/example-composer-env-tf-c2",
            "labels": null,
            "name": null,
            "project": null,
            "region": null,
            "timeouts": null
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo3MjAwMDAwMDAwMDAwLCJkZWxldGUiOjE4MDAwMDAwMDAwMDAsInVwZGF0ZSI6NzIwMDAwMDAwMDAwMH19",
          "dependencies": [
            "google_compute_network.test",
            "google_compute_subnetwork.test",
            "google_service_account.test"
          ]
        }
      ]
    },
```

Plan after removing PyPi Package:
![image](https://user-images.githubusercontent.com/393945/168827764-ce867c02-a2c3-4041-8325-7d54581d1d19.png)

Running apply:
![image](https://user-images.githubusercontent.com/393945/168828525-1cb51ea2-d811-4ec7-8ae5-782c767f3c90.png)

### Expected Behavior

The resources creates but then fails in cloudbuild to add the PyPi packages. If i re-run the pipeline after fixing the PyPi package to be a correct version it should delete the composer instance and create a new one. 

### Actual Behavior

Upon trying to re-create i get the not-found 404 error. 

### Steps to Reproduce

1. Run the above terraform 
2. It should fail on the PyPi package install
3. Remove the PyPi packages or change to supported version
4. Try and re-run the pipeline, it should fail 

### References

* #0000

**Comment by gmenuel** [comment]
We're having the same problem, it seems that terraform didn't store the name of the environment in the state during the creation of composer (name=""), and during the deletion it uses this information to retrieve the info on the composer, so it failed.

The resourceComposerEnvironmentRead function is only called if the creation was successful, maybe the name should at least be set even if the creation is uncomplete ? Or destroy the composer and the resource if the creation failed, I believe that is what is done on for the resource_container_cluster resource

**Comment by drandell** [comment]
Still seeing this issue occurring in our business and having to explain to users to-do state imports or requiring manual intervention by admins is frustrating. Can we get an update on this?

**Comment by nphilbrook** [comment]
I was encountering a similar 404 error upon trying to destroy a composer environment and ran the apply with `TF_LOG=DEBUG`, and noted that the provider is sending a DELETE request to a URL that doesn't specify an actual environment:
```
---[ REQUEST ]---------------------------------------                                                                                                                                                                                                                          
DELETE /v1/projects/wf-gcp-us-ae-legaltech-dev/locations/us-central1/environments/?alt=json&prettyPrint=false HTTP/1.1                                                                                                                                                         
Host: composer.googleapis.com                                                                                                                                                                                                                                                  
User-Agent: google-api-go-client/0.5 Terraform/0.12.21 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/dev                                                                                                                                   
X-Goog-Api-Client: gl-go/1.16.14 gdcl/0.70.0                                                                                                                                                                                                                                   
Accept-Encoding: gzip                                                                                                                                                                                                                                                          
```
Definitely looks like the provider is not capable of deleting composer environments at all with this bug.

**Comment by drandell** [comment]
Any confirmation of this being a bug @rileykarson ?

**Comment by IgnacioNMiranda** [comment]
Hello everybody, similar problem here. When I try to deploy a GCP Composer instance I get the following error after the instance is deployed:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/38511917/211567638-f9b5f8e1-4307-48b6-adff-e14089e7faf4.png">
Then if I try to delete the instance I get the same error as @nphilbrook.

**Comment by JanHenGro** [comment]
We're facing the same issue. 
Unfortunately, the behavior occurs irregularly even with the same PyPI packages & versions. Sometimes the deployment runs successfully and sometimes not.
It is only reproducible by deliberately corrupting versions.

Does anyone have a suggestion if you can output the actual error that occurs when installing the PyPI packages in the log? 

The mentioned in-cluster build logs are empty:
Error waiting to update Environment: Error waiting for Updating newly created Environment: Error code 3, message: Failed to install PyPI packages.  Check the in-cluster build logs for details. They can be found in the Environment logs [URL]

**Comment by trodge** [comment]
I am currently working on this.
