### ISSUE TITLE
Rewrite `Making changes to resources` section of MM readme

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#11712]
Rewrite **Making changes to resources** section in MM readme page to only include brief summary+ links and move detailed instruction on different type of resources to dedicated locations -- handwritten, mmv1 resources to mmv1 readme and tpgtools resources to tpgtools readme.
Create a new readme page under mmv1 folder and move detailed guidance on modifying handwritten and mmv1 generated resource to mmv1 readme.

**Comment by rileykarson** [comment]
We can probably take the content from the internal go/terraform-contribution-guide here
