### ISSUE TITLE
Add CMEK support for google_vertex_ai_featurestore

### ISSUE THREAD

**Issue by enrique-zetina** [hashicorp/terraform-provider-google#11721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_vertex_ai_featurestore

### Potential Terraform Configuration

```tf
resource "google_vertex_ai_featurestore" "featurestore" {
  provider = google-beta
  name     = "terraform"
  labels = {
    foo = "bar"
  }
  region   = "us-central1"
  online_serving_config {
    fixed_node_count = 2
  }
 encryption_spec{
  kms_key_name = "mykey"
}
```

### References

At this point is not possible to set the encryption_spec when creating a [Featurestore](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore); nevetheless, the Featurestore oficial [documentation](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featurestores#Featurestore) allows to set `encryptionSpec` to use  customer managed encryption keys.

**Comment by sanghaniJ** [comment]
I've gone through this issue and found that the CMEK support is already provided in the [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6460) and is merged. Hence, closing this issue.

**Comment by sanghaniJ** [comment]
b/263838870
