### ISSUE TITLE
Unable to attach serverless NEG to internal backend for L7ILB

### ISSUE THREAD

**Issue by KonradSchieban** [hashicorp/terraform-provider-google#11737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.9 on linux_amd64

### Affected Resource(s)

* google_compute_region_backend_service

### Terraform Configuration Files

```tf
resource "google_compute_region_backend_service" "backend-service" {
  project = var.project_id
  region = var.region
  name = "region-service"
  //health_checks = [google_compute_health_check.health_check.id]
  protocol = "HTTP"
  load_balancing_scheme = "INTERNAL_MANAGED"

  backend {
    group = google_compute_region_network_endpoint_group.cloudrun_neg.id
  }
}

resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
  name                  = "cloudrun-neg"
  network_endpoint_type = "SERVERLESS"
  region                = var.region
  cloud_run {
    service = google_cloud_run_service.default.name
  }
}
```

### Debug Output

https://gist.github.com/KonradSchieban/601ad80ee0481cc563afda430aba69ad

### Expected Behavior

Following [this documentation](https://cloud.google.com/load-balancing/docs/l7-internal/setting-up-l7-internal-serverless) it should be possible to attach a serverless NEG to a backend. With gcloud, it is possible like this:

```
gcloud compute network-endpoint-groups create SERVERLESS_NEG_NAME \
    --region=REGION \
    --network-endpoint-type=serverless  \
    --cloud-run-service=CLOUD_RUN_SERVICE_NAME

gcloud compute backend-services create BACKEND_SERVICE_NAME \
    --load-balancing-scheme=INTERNAL_MANAGED \
    --protocol=HTTP \
    --region=REGION

gcloud compute backend-services add-backend BACKEND_SERVICE_NAME \
    --region=REGION \
    --network-endpoint-group=SERVERLESS_NEG_NAME \
    --network-endpoint-group-region=REGION
```

### Actual Behavior

 Error: Error creating RegionBackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].balancingMode': 'CONNECTION'. Balancing mode is not supported for Serverless network endpoint groups., invalid

### Steps to Reproduce

see Terraform above

1. `terraform apply`

### Important Factoids

N/A

### References

https://cloud.google.com/load-balancing/docs/l7-internal/setting-up-l7-internal-serverless

**Comment by sorenhansendk** [comment]
Hi @KonradSchieban 

I think the `balancing_mode` property have a wrong default value (CONNECTION) - so you need to do this:

<pre>
backend {
  group           = google_compute_region_network_endpoint_group.nuget-server.self_link
  balancing_mode  = "UTILIZATION"
  capacity_scaler = 1.0
}
</pre>

**Comment by KonradSchieban** [comment]
Thank you @sorenhansendk this indeed unblocked this issue. I wonder if this comes down to being no issue at all or missing documentation. May I ask where you have found the solution?

**Comment by sorenhansendk** [comment]
@KonradSchieban In the example for backends used in internal load balancers, is the `balancing_mode` property set to `UTILIZATION` - please check the example out here:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_backend_service#example-usage---region-backend-service-balancing-mode
