### ISSUE TITLE
documentation issue -- data.google_secret_manager_secret

### ISSUE THREAD

**Issue by zpbonjour** [hashicorp/terraform-provider-google#11736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.1.7

### Affected Resource(s)
google_secret_manager_secret

### Terraform Configuration Files

```tf
data "google_secret_manager_secret" "MAIN_DB_PASSWORD_SECRET" {
  secret_id = "MAIN_DB_PASSWORD_SECRET"
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Data source is created

### Actual Behavior

│ Error: Error constructing id: project: required field is not set
│
│   with data.google_secret_manager_secret.MAIN_DB_PASSWORD_SECRET,
│   on data-sources.tf line 1, in data "google_secret_manager_secret" "MAIN_DB_PASSWORD_SECRET":
│    1: data "google_secret_manager_secret" "MAIN_DB_PASSWORD_SECRET" {

### Steps to Reproduce

Attempt to source a secret without the project set

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/secret_manager_secret

The docs state that the project is optional when it is actually required.

b/301412408

**Comment by abheda-crest** [comment]
I've found out that this issue occurs when every [provider configuration block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference) has an alias and there is no default provider configuration. A provider configuration without an alias will be treated as the default configuration. But, If every explicit configuration of a provider has an alias, Terraform uses the implied empty configuration as that provider's default configuration. More details can be found [here](https://developer.hashicorp.com/terraform/language/providers/configuration#default-provider-configurations).
It seems like there are two potential solutions for this: 
1. To define a default provider configuration (A provider configuration block without an alias)
2. To explicitly [pass the reference](https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations) of the provider in the resource/data source itself.

**Comment by slevenick** [comment]
This is normal project-field functionality
