### ISSUE TITLE
Add connection_id field to bigquery table external_data_configuration

### ISSUE THREAD

**Issue by gutschenritter** [hashicorp/terraform-provider-google#11741]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The bigquery connection resource type cloud_resource was recently added in #[6020](https://github.com/GoogleCloudPlatform/magic-modules/pull/6020). In order to support Big Lake, connection resources should be able to be used on table creation and update, as a member of the [external data config](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#externaldataconfiguration).

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "my-table-resource" {
  dataset_id = google_bigquery_dataset.dataset.dataset_id
  table_id   = "my-table"
  project = "my-project"

  schema = <<EOF
[
  {
    "name": "foo",
    "type": "STRING"
  }
]
EOF

  external_data_configuration {
    source_format = "PARQUET"
    connection_id = google_bigquery_connection.connection.name
    source_uris = [
      "gs://my-uri/*.parquet",
    ]
  }

}
```

### References

* #0000

**Comment by gutschenritter** [comment]
I'm working on this right now.

**Comment by gutschenritter** [comment]
Fixed by #GoogleCloudPlatform/magic-modules/pull/6061

**Comment by DrFaust92** [comment]
[rileykarson](https://github.com/rileykarson) this can be closed

**Comment by sanghaniJ** [comment]
b/263756506

**Comment by sanghaniJ** [comment]
I've gone through this issue and it seems like the support for `connection_id` is already added. Here is the link of the [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6061) that was merged. Hence, closing this issue ticket.
