### ISSUE TITLE
Specify visible core count

### ISSUE THREAD

**Issue by sroemen-privia** [hashicorp/terraform-provider-google#11758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be great if terraform was able to specify the number of visible cores at machine build time, per https://cloud.google.com/compute/docs/instances/customize-visible-cores

### References

[customize visible core count](https://cloud.google.com/compute/docs/instances/customize-visible-cores)

**Comment by sanghaniJ** [comment]
b/263940733

**Comment by sanghaniJ** [comment]
I've gone through this issue and the request is regarding support for `visibleCoreCount` in `computeInstance`. The requested feature is now supported as per [terraform documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#visible_core_count). A [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6414) was done implementing this feature and was merged. Hence, closing this issue ticket.
