### ISSUE TITLE
Role roles/iap.httpsResourceAccessor has been retired., invalidIamPolicy

### ISSUE THREAD

**Issue by tedder** [hashicorp/terraform-provider-google#11751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.2.0
on darwin_amd64
```

Google provider: `terraform-provider-google-beta_v4.21.0_x5`

### Affected Resource(s)

* google_compute_backend_service_iam_binding

### Terraform Configuration Files

```tf
resource "google_compute_backend_service_iam_binding" "k8_internal_web_binding_domain" {
  provider = google-beta
  project  = var.project
  name     = data.google_compute_backend_service.k8_internal_web.name
  role     = "roles/iap.httpsResourceAccessor"
  members  = ["domain:example.com"]
}
```

### Debug Output

Only giving a subset of the debug output.

```
google_compute_backend_service_iam_binding.k8_internal_web_binding_domain: Creating...
POST /compute/beta/projects/example-project/global/backendServices/k8s1-xxx/setIamPolicy?alt=json HTTP/1.1
Host: compute.googleapis.com
User-Agent: Terraform/1.2.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/dev
Content-Length: 138
Content-Type: application/json
Accept-Encoding: gzip

{
 "policy": {
  "bindings": [
   {
    "members": [
     "domain:example.com"
    ],
    "role": "roles/iap.httpsResourceAccessor"
   }
  ],
  "etag": "xxx",
  "version": 3
 }
}
2022-05-23T13:45:48.873-0700 [INFO]  provider.terraform-provider-google-beta_v4.21.0_x5: 2022/05/23 13:45:48 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 23 May 2022 20:45:48 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "error": {
    "code": 400,
    "message": "Role roles/iap.httpsResourceAccessor has been retired.",
    "errors": [
      {
        "message": "Role roles/iap.httpsResourceAccessor has been retired.",
        "domain": "global",
        "reason": "invalidIamPolicy"
      }
    ]
  }
}
2022-05-23T13:45:48.884-0700 [ERROR] vertex "google_compute_backend_service_iam_binding.k8_internal_web_binding_domain" error: Error applying IAM policy for compute backendservice "projects/example-project/global/backendServices/k8s1-xxx": Error setting IAM policy for compute backendservice "projects/example-project/global/backendServices/k8s1-xxx": googleapi: Error 400: Role roles/iap.httpsResourceAccessor has been retired., invalidIamPolicy
```

### Expected Behavior

terraform should create the permissions for the principal with the IAP role. It's possible to create it in the web UI, no warnings, but it fails with the terraform provider.

Here's the role list in the web UI:
<img width="381" alt="Screen Shot 2022-05-23 at 1 54 40 PM" src="https://user-images.githubusercontent.com/97914/169905079-97c10450-7536-4f43-8b39-20cb8ad4fbf4.png">

### Actual Behavior

terraform (or the API) returns `Role roles/iap.httpsResourceAccessor has been retired., invalidIamPolicy`.

No indication this role has been retired, nor are there many hits for this phrase.

### Steps to Reproduce

1. `terraform apply`
2. see the failure.
3. change the IAM role to "roles/viewer"
4. `terraform apply`
5. it works.

### Important Factoids

The only thing that might be special about this is that I'm using a Kubernetes backend service with IAP. It's listed in my backend services and everything appears normal.

### References

* Google Cloud documentation for IAP access lists this role: https://cloud.google.com/iap/docs/managing-access#roles

**Comment by rileykarson** [comment]
We're sending a correct HTTP request, unusual. I can't find any documentation suggesting this has been retired, nor can I find an issue clientside. I'd suggest reaching out to the service team if possible (i.e. through Google Cloud Support, or through https://cloud.google.com/support/docs/issue-trackers), as the error doesn't seem to lie with Terraform but w/ the service team instead.

**Comment by wyardley** [comment]
Thanks Riley. What’s odd is that a) the role is still documented and b) we can assign it to the backend via the web console

**Comment by rileykarson** [comment]
I definitely agree that it's odd! I looked internally and didn't find any indicator why you were getting this error back, either. The role looks right- I double-checked the casing (as I found past roles retired for that, years ago) and the double letters in Accessor for good measure.

I can't see anything wrong w/ Terraform's behaviour here is all, and it seems to come from the API for whatever reason.

**Comment by rileykarson** [comment]
Other things to try (that I didn't):

* Compare the request gcloud sends to the Terraform one, using `-log-http`, and see whether `gcloud` succeeds
* Confirm the role the Console assigns is the same one Terraform is assigning (maybe they're similar but distinct? That's not unprecedented, but seems unlikely given the docs agree w/ the role you're using)
* Use the API explorer to play around with IAM versions- maybe using a `v1` vs `v3` policy does something?

**Comment by wyardley** [comment]
Yeah, we were trying to get / list the binding to compare but couldn’t get it to work.

If it matters, it’s not only a kube created backend that we’re getting from a data resource, but also using NEGs. Had thought about trying with the beta provider for that reason.

**Comment by wyardley** [comment]
Created issuetracker issue at https://issuetracker.google.com/issues/233644822

**Comment by avidelatm** [comment]
Maybe not what you are after, but I normally set that role by using slightly different terraform, and it works for me: 
`
resource "google_iap_web_iam_member" "iap_web_user" {
  role     = "roles/iap.httpsResourceAccessor"
  member   = "domain:example.com"
}
`

I wonder if the problem is either your google-beta provider version,  or if the problem might have to do with using an authoritative resource rather than a non-authorative.
