### ISSUE TITLE
dns: plan/apply with routing policy type change always fails

### ISSUE THREAD

**Issue by kanata2** [hashicorp/terraform-provider-google#11763]
Hi, I found a bug for `google_dns_record_set` with Routing Policy introduced in v4.21.0.
I'll send a Pull Request to fix this issue later.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.22.0
```

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

## main.tf version 1
terraform {
  required_version = "1.2.1"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.22.0"
    }
  }
}

variable "project" {
  type = string
}

provider "google" {
  project = var.project
  region  = "asia-northeast1"
}

resource "google_dns_record_set" "test" {
  managed_zone = "kanata2-example-com"
  name         = "test.kanata2.example.com."
  type         = "A"
  ttl          = 60
  rrdatas      = ["127.0.0.1"]
}

## main.tf version 2
terraform {
  required_version = "1.2.1"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.22.0"
    }
  }
}

variable "project" {
  type = string
}

provider "google" {
  project = var.project
  region  = "asia-northeast1"
}

resource "google_dns_record_set" "test" {
  managed_zone = "kanata2-example-com"
  name         = "test.kanata2.example.com."
  type         = "A"
  ttl          = 60
  routing_policy {
    wrr {
      weight  = 0.8
      rrdatas = ["127.0.0.1"]
    }
    wrr {
      weight  = 0.2
      rrdatas = ["10.0.0.0"]
    }
  }
}

```

### Debug Output

Paste on my gist: https://gist.github.com/kanata2/4529f5c5cc56927a53b7ba69b610424e

### Expected Behavior

Success to apply.

### Actual Behavior

Failed to apply changes, but tfstate is modified.

### Steps to Reproduce

1. `terraform apply` with main.tf version1
2. `terraform apply` with main.tf version2

### Important Factoids

Nothing.

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/5909

**Comment by shuyama1** [comment]
This should be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6103. Closing this issue now. Feel free to reopen this issue if the bug still occurs after the fix is released to the providers.
