### ISSUE TITLE
Dataproc Serverless: `google_dataproc_batch`

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#11775]
### Affected Resource(s)

* google_dataproc_batch

Hi, 

Just wondering if dataproc serverless support is in the pipeline ?

doc: https://cloud.google.com/dataproc-serverless/docs
rest api: https://cloud.google.com/dataproc-serverless/docs/reference/rest

Dan

### References

* b/323955683

**Comment by mitj04** [comment]
b/253647560

**Comment by rileykarson** [comment]
Note: this was waiting on https://github.com/GoogleCloudPlatform/magic-modules/pull/6837 in the internal bug, but I'm not sure why

**Comment by panas2567** [comment]
Hello, any update on when the serverless jobs could be supported?

**Comment by gargmukku07** [comment]
Hi Team,

We have also started using the DataProc Serverless both batch and interactive templates. Will be waiting for this feature.
