### ISSUE TITLE
Configuring a single GCP resource in DryRun section of a service perimeter

### ISSUE THREAD

**Issue by DmitriSmirnovCTL** [hashicorp/terraform-provider-google#11780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Similar to google_access_context_manager_service_perimeter_resource - is it possible to have a new resource or option to this one to add project id to 'spec' portion of VPC Service Control perimeter? This will allow to move specified resources into DryRun portion of related perimeters.

### New or Affected Resource(s)

google_access_context_manager_service_perimeter_resource

### Potential Terraform Configuration

```tf
resource "google_access_context_manager_service_perimeter_resource" "service-perimeter-resource" {
  perimeter_name = google_access_context_manager_service_perimeter.service-perimeter-resource.name
  resource = "projects/987654321"
spec {
  resource = "projects/987654321"
  }
}

OR
resource "google_access_context_manager_service_perimeter_spec_resource" "service-perimeter-spec-resource" {
  perimeter_name = google_access_context_manager_service_perimeter.service-perimeter-resource.name
  resource = "projects/987654321"
}

```

### References

* b/298506609

**Comment by rileykarson** [comment]
@c2thorn: This looks like a new resource, but can you make sure? Thanks!

**Comment by Charlesleonius** [comment]
@rileykarson or @roaks3 Can we close this out as it should be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/10145
