### ISSUE TITLE
Add Regional SSL policies support to google_compute_region_target_https_proxy

### ISSUE THREAD

**Issue by DaveyDevOps** [hashicorp/terraform-provider-google#11781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Regional SSL policies are used for Regional external HTTP(S) load balancer, Internal HTTP(S) load balancer
Currently in Pre-GA, a new resource will be needed. 

### New or Affected Resource(s)

* google_compute_region_target_https_proxy
* (new) google_compute_region_ssl_policy

### References

* https://cloud.google.com/load-balancing/docs/ssl-policies-concepts

**Comment by DaveyDevOps** [comment]
I started work on this... planning to continue.

**Comment by pio-janik** [comment]
Any progress on the task ? This is a valuable feature.

**Comment by DaveyDevOps** [comment]
PR merged to main

**Comment by DaveyDevOps** [comment]
Released in [terraform-provider-google-beta](https://github.com/hashicorp/terraform-provider-google-beta) v4.26.0

@rileykarson can you advise, should this remain open until GA?
