### ISSUE TITLE
Docs missing for role roles/iam.workloadIdentityPoolAdmin causes WorkloadIdentityPool: googleapi: Error 403: Permission 'iam.workloadIdentityPools.create' denied on resource

### ISSUE THREAD

**Issue by stewartshea** [hashicorp/terraform-provider-google#11789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.22.0
+ provider registry.terraform.io/hashicorp/google-beta v4.22.0
```
### Affected Resource(s)

google_iam_workload_identity_pool

### Terraform Configuration Files

```tf
resource "google_iam_workload_identity_pool" "github_actions_pool" {
  for_each                  = var.projects
  project                   = [redacted]
  provider                  = google-beta
  workload_identity_pool_id = "github-actions-pool"
}
```

### Debug Output

https://gist.github.com/stewartshea/a09ccf20569f3b8b5d677120fb186a60

Generates this error: 
```
{
  "error": {
    "code": 403,
    "message": "Permission 'iam.workloadIdentityPools.create' denied on resource '//iam.googleapis.com/projects/REDACTED-PROJECT/locations/global' (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "iam.googleapis.com",
        "metadata": {
          "resource": "projects/REDACTED-PROJECT/locations/global",
          "permission": "iam.workloadIdentityPools.create"
        }
      }
    ]
  }
}
```

### Panic Output

NA

### Expected Behavior

Identity pool should have been created 

### Actual Behavior

Received permission denied (with GCP owner  and org admin privileges) 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Authenticated as an Owner account that is also used to manage the remainder of the organization. 

I WAS able to solve this though by chasing down the role roles/iam.workloadIdentityPoolAdmin which is in beta. If this role is assigned to the calling user/account, the pool is created. 

### References

* #0000

**Comment by edwardmedia** [comment]
Close as the change has merged
