### ISSUE TITLE
google_compute_instance resolveImage function applies to the wrong project to resolveImageFamilyExists?

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-provider-google#11793]
hi,

I have a case with a simple stack deploying a project where I bumped into the 'resolveImage' function failing.  It reported that "Compute Engine API" was not enabled in the project the provider was using.  This is correct in the error, but I'm wondering if this resovleImage function should be operating against the project specified on the resource and not against the provider?

Looking at the code I found this line:

https://github.com/hashicorp/terraform-provider-google/blob/5332c033bfccab730de44ee69c165a45345aa562/google/image.go#L185

Rather than `c.Project` being passed to `resolveImageFamilyExists` should that instead be simply `project` i.e. the variable passed into the function which is the project for the new compute instance resource.

Thoughts?

Thanks,
Alex

**Comment by alexjmoore** [comment]
I do think this is still an issue. In fact I have seen this type of issue a few times across different resources - i.e. where the provider is making calls against the provider project rather than the target project of a resource. Of which this is an example. It means you need to enable APIs against the providers project that are not actually needed.

**Comment by rileykarson** [comment]
I suspect you're running into client and resource projects. They're one of the thorny bits in GCP- see https://cloud.google.com/docs/authentication/provide-credentials-adc#user-creds-client-based for a description of how it affects gcloud users, and https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#quota-management-configuration for resolution in Terraform.
