### ISSUE TITLE
Allow linking of Compute Resource Policy to Notebooks Instance

### ISSUE THREAD

**Issue by danielvdende** [hashicorp/terraform-provider-google#11795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, there is no way to assign a Compute Resource Policy ([docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy)) to a VM created with the `google_notebooks_instance` resource. The `google_compute_instance` resource does expose this option ([docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#resource_policies))
Unfortunately, we now have to resort to using the `gcloud` CLI or the Console to make this link, even though the `google_notebooks_instance` also creates a compute instance.

### New or Affected Resource(s)

* google_notebooks_instance

### Potential Terraform Configuration

```tf
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  vm_image {
    project      = "deeplearning-platform-release"
    image_family = "tf-latest-cpu"
  }
  resource_policy = "my-cool-resource-policy"
}
```
Note: it's currently not possible to assign more than 1 resource policy to a compute instance, hence my suggestion is a simple string attribute. This could, of course, be extended to a list if that were to be supported.

b/302797465

**Comment by rileykarson** [comment]
@slevenick: Determine if this is possible in the API

**Comment by danielvdende** [comment]
@slevenick Thanks for looking into this. Just to check before I open an issue in the wrong place, you mean this repo, right? https://github.com/googleapis/googleapis

**Comment by slevenick** [comment]
I think you'll need to file a request against the product's issue tracker. You can find a list here: https://cloud.google.com/support/docs/issue-trackers

The product will need to support it in the REST API, and then downstream clients like Terraform and the googleapis SDK can support it

**Comment by bcreddy-gcp** [comment]
`google_notebooks_instance` is now deprecated and will not be taking new feature requests. `google_workbench_instance` is the replacement if such features are of interest. That said, with workbench instances, the underlying GCE VM is supposed to be immutable and so, I don't see it getting support for anything similar. Is there a reason why such feature is of interest?

**Comment by bcreddy-gcp** [comment]
`google_notebooks_instance` is deprecated and will not be taking new feature requests. If this is of interest, a FR can be raised for `google_workbench_instance`.
