### ISSUE TITLE
Add support for MAC purpose in google_kms_crypto_key

### ISSUE THREAD

**Issue by ori-shalom** [hashicorp/terraform-provider-google#11806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP KMS CryptoKey support setting `MAC` purpose to be used with `HMAC_SHA256` for example.
 https://cloud.google.com/kms/docs/algorithms#key_purposes
Using  terraform, trying to set the  `purpose` attribute of `google_kms_crypto_key` to `"MAC"` returns the following error:
 ```
 Error: expected purpose to be one of [ENCRYPT_DECRYPT ASYMMETRIC_SIGN ASYMMETRIC_DECRYPT ], got MAC
```
Looks like the issue is here:
https://github.com/hashicorp/terraform-provider-google/blob/6072c3934ac7a9ab489edfb1776e8723f458619a/google/resource_kms_crypto_key.go#L91-L100

### Affected Resource

* google_kms_crypto_key

### Potential Terraform Configuration

```tf
resource "google_kms_crypto_key" "vault_asymmetric_sign_key" {
  name     = "crypto-key-name"
  key_ring = google_kms_key_ring.keyring.id
  purpose  = "MAC"

  version_template {
    algorithm = "HMAC_SHA256"
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### References

* https://cloud.google.com/kms/docs/algorithms#key_purposes

**Comment by melinath** [comment]
b/237107209

**Comment by prateek2408** [comment]
Issue has been fixed - https://github.com/GoogleCloudPlatform/magic-modules/pull/6218
