### ISSUE TITLE
Add support for DLP Automated BigQuery Data Profiler

### ISSUE THREAD

**Issue by vlad-ds** [hashicorp/terraform-provider-google#11803]
This new feature involves setting a scan configuration at the project level (or folder or org) that automatically scans all BigQuery data. 

Apologies if the feature is already present, but I could not find it. 

https://cloud.google.com/blog/products/identity-security/google-launches-automatic-dlp-for-bigquery
https://cloud.google.com/dlp/docs/data-profiles

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_bigquery_data_profiler

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

b/360000205

**Comment by Wallace99** [comment]
This would be great, but currently there is no way of achieving this through the DLP REST api (as far as I can see) so it is probably still a while off before it can be added to Terraform 
https://cloud.google.com/dlp/docs/reference/rest

**Comment by Wallace99** [comment]
Looks like as of recently DLP profiling (BigQuery and Cloud Storage) is supported through the API so I think this should be doable now https://cloud.google.com/dlp/docs/reference/rest/v2/organizations.locations.discoveryConfigs

**Comment by ggtisc** [comment]
Currently there isn't any resource called `google_bigquery_data_profiler` for this purpose

**Comment by Wallace99** [comment]
I think can be closed now as BigQuery DLP profiling can be configured with the discovery config resource

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_discovery_config

**Comment by ScottSuarez** [comment]
ack, thanks !
