### ISSUE TITLE
ignore_changes does not work for google_bigquery_table 

### ISSUE THREAD

**Issue by usmift** [hashicorp/terraform-provider-google#11802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.20.0
+ provider registry.terraform.io/hashicorp/google-beta v4.17.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.3

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "bigquery_table" {
  dataset_id          = google_bigquery_dataset.dataset.dataset_id
  table_id            = "bigquery_table"
  project             = data.google_project.project.project_id
  deletion_protection = false

  schema = ....

  lifecycle {
    ignore_changes = [
      etag,
      last_modified_time,
      num_bytes,
      num_rows
    ]
} 
 ```

### Debug Output

```
# module.workplace-productivity.google_bigquery_table.issues has changed
  ~ resource "google_bigquery_table" "bigquery_table" {
        id                  = "projects/bigquery_project/datasets/dataset/tables/bigquery_table"
      ~ last_modified_time  = 1654091882982 -> 1654156683005
        # (16 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
### Expected Behavior

No changes detected

### Actual Behavior

Changes in ignored fields are detected

### Steps to Reproduce

Update the table by any means.

1. `terraform apply`

b/300616884

**Comment by dogmatic69** [comment]
Notice the same behaviour for `num_bytes` / `num_rows`. Plans always indicate a change to be made. 

Resource includes the following as per the output given by terraform.

```
  lifecycle {
    ignore_changes = [
      num_bytes,
      num_rows,
    ]
  }
```

```
Terraform detected the following changes made outside of Terraform since the last "terraform
apply" which may have affected this plan:

  # google_bigquery_table.table has changed
  ~ resource "google_bigquery_table" "table" {
        id                  = "projects/xxx/datasets/xxx/tables/xxx"
      ~ num_bytes           = 0 -> 8
      ~ num_rows            = 0 -> 1
        # (17 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant
attributes using ignore_changes, the following plan may include actions to undo or respond to
these changes.
```

**Comment by zaccari** [comment]
Just finished upgrading from `0.13.0` to `1.4.6`, and from versions `0.15.0` to `1.2.9` I noticed this issue for `etag`, `num_bytes`, `num_rows` and `last_modified_time`, even with the following lifecycle:

`
  lifecycle {
    ignore_changes = [
      etag,
      last_modified_time,
      num_bytes,
      num_rows,
    ]
  }
`

It was when I jumped to the `1.3.x`+ (currently on `1.4.6`) that I noticed a warning about using these variables:

```
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Redundant ignore_changes element
│
│   on ../../modules/bigquery/device_metrics/metrics_availability.tf line 1, in resource "google_bigquery_table" "availability":
│    1: resource "google_bigquery_table" "availability" {
│
│ Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has been created, retaining the value
│ originally configured.
│
│ The attribute last_modified_time is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute in ignore_changes
│ has no effect. Remove the attribute from ignore_changes to quiet this warning.
│
│ (and 23 more similar warnings elsewhere)
```

And after removing the lifecycle hook, I no longer see the warning about `Objects have changed outside of Terraform`, so it appears that upgrading terraform might resolve this issue for anyone else who comes across it.

**Comment by aaleksandrov** [comment]
In my team we experience the same and it's quite annoying
I noticed that these changes are detected only for a small subset of tables while for others there are never changes detected. I couldn't find any difference between tables which pop up in plans and which don't

**Comment by rileykarson** [comment]
Some of the results here are not necessarily part of the plan, the ones messaged as "Terraform detected the following changes made outside of Terraform since the last "terraform
apply" which may have affected this plan:" in particular. Newer Terraform versions highlights output values that have changed since the last plan even though they won't impact the plan proper. It can be noisy- GKE sees this happen a lot as well. Unfortunately, providers have no configuration of this feature.

Our provider has a lot of "Optional + Computed" fields that behave like a configurable field sometimes and output fields other times, as they're the best solution to complex API defaults, a pattern prevalent in GCP. That exacerbates the issue. These are particularly common in large resources like we see in BQ and GKE.

**Comment by rileykarson** [comment]
@lsh-0 does `terraform plan` show a diff on those values?

**Comment by obada-ab** [comment]
Tried to reproduce this issue using the latest terraform version (1.5.7), but was unable to

**Comment by rileykarson** [comment]
Thanks for verifying @obada-ab!

Reading over this briefly, these reports are "{{value}} has changed" which is a newer Terraform feature but one that is distinct from a diff at plan time. Volatile values will get re-reported by Terraform in some cases, unfortunately, even through they're anticipated to change.

`lifecycle.ignore_changes` will specifically suppress the diff at plan time- it tells Terraform to ignore changes to _configuration_ that diverge from state- but won't change the newer Terraform Core feature's reporting as far as I know.
