### ISSUE TITLE
Failing test(s): TestAccVertexAIMetadataStore_vertexAiMetadataStoreExample

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11819]
Failure rate: Consistently since April 30, 2022

Impacted tests:
- TestAccVertexAIMetadataStore_vertexAiMetadataStoreExample

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=8815830251702987557)

Message:

```
Error: Error creating MetadataStore: googleapi: Error 400: Provided CryptoKey projects/ci-test-project-188019/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1 cannot be used in Vertex AI service. Please make sure the CryptoKey is enabled and Vertex AI service account `service-1067888929963@gcp-sa-aiplatform.iam.gserviceaccount.com` has Encryption and Decryption access to the CryptoKey.
```

**Comment by melinath** [comment]
Updated permissions. Test run: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/316333

b/239844638

**Comment by melinath** [comment]
Permissions seem to work; now failing with a new error. Retrying in case it's transient: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/316347

**Comment by melinath** [comment]
looks like that error was transient; marking this resolved.
