### ISSUE TITLE
Let us set days_since_custom_time to 0

### ISSUE THREAD

**Issue by WilhelmLundstrom** [hashicorp/terraform-provider-google#11816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When adding the lifecycle rule for days_since_custom_time, terraform only allows positive integers, whereas it probably should allow for 0 as well. It is possible to set the condition days_since_custom_time = 0 in the gcp console, so it would mae sense if it were possible in terraform as well.

### New or Affected Resource(s)

* google_storage_bucket
* google_storage_bucket_object

### Potential Terraform Configuration

Our use-case would be that we use custom time to mark when to delete an object in the storage, and hence want to delete it ASAP after that date has passed.

b/275618106

**Comment by rileykarson** [comment]
Note: It's possible the API is able to distinguish between zero and unset, while Terraform is not. We should make sure that it doesn't (and probably need an additional boolean field to support this otherwise)

**Comment by WilhelmLundstrom** [comment]
Is this something we can expect to be changed any time soon?

**Comment by kautikdk** [comment]
This is fixed with this PR:https://github.com/GoogleCloudPlatform/magic-modules/pull/10717

**Comment by kautikdk** [comment]
@melinath Can you please close this issue!
