### ISSUE TITLE
Failing test(s): TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11825]
Failure rate: Consistently since May 5, 2022

Impacted tests:
- ~TestAccCGCSnippet_sqlSqlserverVmInstanceExample~
- TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample
- ~TestAccCGCSnippet_sqlInstanceCmekExample~
- ~TestAccCGCSnippet_storageMakeDataPublicExample~

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=533436868669627091)

Message:

```
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
...
```

**Comment by melinath** [comment]
TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample can't init the `random` provider; the others can't init the google-beta provider.

**Comment by megan07** [comment]
Per [this comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/6165), this will be considered a breaking change. tl;dr - fixing this test uncovers a bug, and fixing that bug is a breaking-change.
