### ISSUE TITLE
Failing test(s): TestAccDataFusionInstance_dataFusionInstanceFullExample

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11822]
### Affected Resource(s)

* google_data_fusion_instance

Failure rate:
- Consistently since May 11, 2022
- Still 100% as of June 16, 2022

Impacted tests:
- TestAccDataFusionInstance_dataFusionInstanceFullExample

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=7345538750413882111)

Message:

```
Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 13, message: an internal error has occurred
```

**Comment by melinath** [comment]
Message has possibly been updated? Now reads:

```
Error: Error creating Instance: googleapi: Error 400: invalid creation request due to cloud-control2-saas::INVALID_ARGUMENT: Invalid instance version: 6.3.0...
```

https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/335482?buildTab=tests&expandedTest=7345538750413882111

**Comment by megan07** [comment]
TestAccDataFusionInstance_update also fails with the new message

**Comment by melinath** [comment]
Still 100% as of today.

**Comment by AarshDhokai** [comment]
- TestAccDataFusionInstance_dataFusionInstanceFullExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/7345538750413882111?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 96% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?testNameId=7345538750413882111&projectId=GoogleCloudBeta&tab=testDetails&branch_GoogleCloudBeta=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) - 95% failure

**Comment by AarshDhokai** [comment]
b/262235808
