### ISSUE TITLE
Failing test(s): TestAccContainer[AWS|Azure]

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11824]
Failure rate: Consistently since May 4, 2022

Impacted tests:
- TestAccContainerAwsCluster_BetaBasicHandWritten
- TestAccContainerAwsNodePool_BetaBasicHandWritten
- TestAccContainerAzureCluster_BetaBasicHandWritten
- TestAccContainerAzureNodePool_BetaBasicHandWritten

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=8642159548166866016)

Message:

```
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
...
```

**Comment by melinath** [comment]
These tests are managed by the DCL and don't seem to be fixable by just adding the google-beta provider to each resource. https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/302969

**Comment by AarshDhokai** [comment]
Looks like tests have no failure :
in Google Cloud Beta
[TestAccContainerAws*](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/357684?buildTab=tests&pager.currentPage=1&status=all&name=TestAccContainerAws)
[TestAccContainerAzure*](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/357684?buildTab=tests&pager.currentPage=1&status=all&name=TestAccContainerAzure)

in Google Cloud
[TestAccContainerAws*](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/357662?buildTab=tests&pager.currentPage=1&status=all&name=TestAccContainerAws)
[TestAccContainerAzure*](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/357662?buildTab=tests&pager.currentPage=1&status=all&name=TestAccContainerAzure)
