### ISSUE TITLE
Failing test(s): TestAccHealthcare

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11820]
Failure rate:
- Consistently since April 23, 2022
- Still 100% as of June 16, 2022

Impacted tests:
- TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample
- TestAccHealthcareFhirStore_healthcareFhirStoreStreamingConfigExample

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=5143309679600767093)

Message:

```
Error: Error creating DicomStore: googleapi: Error 403: ... please add the required bigquery.dataEditor role to your project's service account
```

```
Error: Error creating FhirStore: googleapi: Error 403: ... please add the required bigquery.dataEditor and bigquery.jobUser roles to your project's service account
```

**Comment by melinath** [comment]
Added missing roles; running tests: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/316359

**Comment by melinath** [comment]
Had a typo in the tests to run. Dicom succeeded, rerunning FHIR https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/316361

**Comment by melinath** [comment]
Passed.
