### ISSUE TITLE
Failing test(s): TestAccApiGatewayGateway

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#11826]
Failure rate: Consistently since April 23

Impacted tests:
- TestAccApiGatewayGatewayIamBindingGenerated
- TestAccApiGatewayGatewayIamMemberGenerated
- TestAccApiGatewayGatewayIamPolicyGenerated
- TestAccApiGatewayGateway_apigatewayGatewayBasicExample
- TestAccApiGatewayGateway_apigatewayGatewayFullExample
- TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/296876?buildTab=tests&status=failed&expandedTest=-6725046900877211087)

Message:

```
Error 400: API Gateway service agent is missing the required permissions on service account...
```

**Comment by melinath** [comment]
I think this probably has the same root cause as https://github.com/hashicorp/terraform-provider-google/issues/11912, which is now resolved. Rerunning tests: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/316357

**Comment by melinath** [comment]
yep, these are now passing.
