### ISSUE TITLE
Support to export Cloud Inventory Asset to BigQuery

### ISSUE THREAD

**Issue by yu-iskw** [hashicorp/terraform-provider-google#11832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
We can export the asset metadata for your organization, folder, or project to a [BigQuery](https://cloud.google.com/bigquery/what-is-bigquery) table, and then run data analysis on your inventory. BigQuery provides a SQL-like experience for users to analyze data and produce meaningful insights without the use of custom scripts.

- https://cloud.google.com/asset-inventory/docs/exporting-to-bigquery

### New or Affected Resource(s)
We may be able to extend the existing resources, although I don't know the detail about the implementation. If not, we have to create new resources to export Cloud Inventory Asset at project level, folder level and organization level each.

* `google_cloud_asset_organization_feed`
* `google_cloud_asset_folder_feed`
* `google_cloud_asset_project_feed `

### Potential Terraform Configuration

```tf
# Create a feed that sends notifications about network resource updates.
resource "google_cloud_asset_project_feed" "project_feed" {
  project          = "my-project-name"
  feed_id          = "network-updates"
  content_type     = "RESOURCE"

  asset_types = [
    "compute.googleapis.com/Subnetwork",
    "compute.googleapis.com/Network",
  ]

  feed_output_config {
    bigquery_destination {
      project = "test-project"
      dataset = "inventory_asset"
      table = "network_inventory_assets"
      force = true
    }
  }

  condition {
    expression = <<-EOT
    !temporal_asset.deleted &&
    temporal_asset.prior_asset_state == google.cloud.asset.v1.TemporalAsset.PriorAssetState.DOES_NOT_EXIST
    EOT
    title = "created"
    description = "Send notifications on creation events"
  }
}
```

### References
* https://cloud.google.com/asset-inventory/docs/exporting-to-bigquery
* https://cloud.google.com/asset-inventory/docs/reference/rest/v1/TopLevel/exportAssets

**Comment by shotarok** [comment]
`google_cloud_asset_{project,folder,organization}_feed.feed_output_config` is corresponding to the [FeedOutputConfig](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/feeds#FeedOutputConfig) resource. It only supports `PubSubDestinaion` as of now like below. Therefore, I'm afraid expanding the existing resources would be difficult until API supports BigQuery.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/1156179/197375839-63fe3b7d-656d-47fc-affb-19d0a05025c5.png">

---

Apart from that, the API endpoint: [feeds](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/feeds), which `google_cloud_asset_{project,folder,organization}_feed` use, has a REST resource and CRUD methods (create/update/delete/patch). On the other hand, the endpoint: [exportAssets](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/TopLevel/exportAssets) doesn't have a REST object and CRUD methods either. I wonder if dealing with `exportAssets` in terraform is difficult.  

@rileykarson I saw you put this in the Goals milestone. What do you think?

**Comment by rileykarson** [comment]
Thanks for investigating @shotarok! We go through these a couple dozen at a time, spending a couple minutes or less on each, and in cases where it seems reasonable the API implemented something, we tend to assume it already has. A one-time action like `exportAssets` would be difficult to model, yeah. What we'd do on creation is clear, but it's less clear what we should do if a user updates or deletes the resource, or even what a `terraform plan` would do.

For cases like this we'd recommend using the gcloud module (https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest). It allows the user to define a create and delete action (including doing nothing), and the lack of drift detection is clear.
