### ISSUE TITLE
Documentation: Alias form of secret name in google_cloud_run_service is not correct

### ISSUE THREAD

**Issue by nxhuy-github** [hashicorp/terraform-provider-google#11848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the documentation of the resource `google_cloud_run_service`, the `secret_key_ref` block said that, with `name` argument, we could define an alias by using the form:`:projects//secrets/` but this form didn't work at all. And because of that, we could not use the secrets in Cloud Run if our secrets come from a different project !!! Same thing happens with the `secret_name` argument (which is required) in `secret` block.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
# The right format should be:
uuid:projects/project_id/secrets/secret_name
# where:
#     - uuid: an (random) unique ID associated with the secret
#     - project_id: the project number for the project the secret was created in
#     - secret_name: the secret name 
```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#nested_secret_key_ref
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#nested_secret

**Comment by melinath** [comment]
The problem here seems to be that the doc strings use `<` and `>` to enclose variables, which apparently gets interpreted by the docs as html elements.
