### ISSUE TITLE
Add samples for how to leverage PubSub with Cloud Run

### ISSUE THREAD

**Issue by pattishin** [hashicorp/terraform-provider-google#11856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding in new samples using Cloud Run with Pubsub. This is part of an effort to add more snippets for documentation for Cloud Run. 

### New or Affected Resource(s)

* google_cloud_run_service
* google_pubsub_topic
* google_pubsub_subscription

### Potential Terraform Configuration
 
```tf
resource "google_pubsub_topic" "topic" {
  name = "pubsub_topic"
}

resource "google_pubsub_subscription" "subscription" {
  name  = "pubsub_subscription"
  topic = google_pubsub_topic.topic.name

  push_config {
    push_endpoint = "${local.cloud_run_url}"
    oidc_token {
      service_account_email = "${local.pubsub_sa}"
    }
  }
}
```

### References
* https://cloud.google.com/run/docs/events/pubsub
* https://cloud.google.com/run/docs/tutorials/pubsub
* https://cloud.google.com/run/docs/triggering/pubsub-push

Cloud Run Tf Resource: https://registry.terraform.io/modules/GoogleCloudPlatform/cloud-run/google/latest

* #0000

**Comment by pattishin** [comment]
Taking this on. Created issue for reference to new PR in magic modules.

**Comment by melinath** [comment]
Closing as resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6126
