### ISSUE TITLE
Move google container cluster spot vm configuration to GA

### ISSUE THREAD

**Issue by kelly-brown** [hashicorp/terraform-provider-google#11855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

spot VMs in node pools is GA but not available in the Google provider yet.

### New or Affected Resource(s)

* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "default_nodepool" {
...
spot = true
...
```
### References
https://github.com/hashicorp/terraform-provider-google/issues/11651

* #0000

**Comment by toumorokoshi** [comment]
took a quick look, and I think this is just a matter of removing the GA guards that were part of the original PR:

https://github.com/GoogleCloudPlatform/magic-modules/pull/5443/files#diff-542bf08ccbb9e20a2abbf127fde6d38f61c83124b05370a5e53d3e4caa3512f4R207.

**Comment by melinath** [comment]
b/235463281
