### ISSUE TITLE
How do I create a Dataflow Pipeline?

### ISSUE THREAD

**Issue by BenCoughlan15** [hashicorp/terraform-provider-google#11864]
I've come across Dataflow pipelines, and have manually set one up to work from the UI. 

You can see how it's setup here: 
https://www.youtube.com/watch?v=fwyLNP3RtCs&ab_channel=GoogleCloudTech

However, I can't seem to find an example of this anywhere using terraform. 

Is this possible? 

Should I be looking at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job? 

Kind regards,
Ben

**Comment by melinath** [comment]
The terraform provider has two Dataflow resources: [google_dataflow_job](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job) and [google_dataflow_flex_template_job](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job). The documentation for each one provides examples on how to use it and links to more general documentation about the products. I hope that helps!
