### ISSUE TITLE
Setting redis maintenance_policy causes creation of unexpected config block of maintenance_schedule

### ISSUE THREAD

**Issue by yonicurv** [hashicorp/terraform-provider-google#11871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.7

### Affected Resource(s)

resource "google_redis_instance"

### Terraform Configuration Files

```tf
resource "google_redis_instance" "cache_instance" {
  name           = "cache-instance"
  tier           = "STANDARD_HA"
  memory_size_gb = 2

  location_id             = local.gcp_zones[0]
  alternative_location_id = local.gcp_zones[1]
  authorized_network      = local.network
  connect_mode            = "PRIVATE_SERVICE_ACCESS"
  labels                  = local.labels

  maintenance_policy {
    weekly_maintenance_window {
      day = "SUNDAY"
      start_time {
        hours = 9
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/yonicurv/1a9006c0ec9bee33f4ce13c01f19835d

### Expected Behavior

Do not try to remove scheduled maintenance.

### Actual Behavior

Tries to remove and fails with :
Error 400: Invalid option 'maintenance_schedule': 'maintenance_schedule' cannot be updated on existing instances.

### Steps to Reproduce

1. `terraform apply`
2. Let GCP to schedule next maintenance.
3. `terraform apply`

### Workaround

Add the following block to ignore any changes related to maintenance_schedule, and preserve the configuration of maintenance_policy for future schedules.

```tf
  lifecycle {
    ignore_changes = [
      maintenance_schedule,
    ]
  }
```

### References

https://github.com/hashicorp/terraform-provider-google/pull/10978
https://github.com/hashicorp/terraform-provider-google/issues/9622

**Comment by melinath** [comment]
The information on https://github.com/hashicorp/terraform-provider-google/issues/11868 is useful to note - apparently TF is trying to set these output-only fields to null, which is triggering the error.

**Comment by anatoliykim** [comment]
Is there any solution to this other than ignoring the changes?

**Comment by rubensayshi** [comment]
for some reason this started happening to us today as well... no terraform or plugin update recently ...

**Comment by nicolae-gorgias** [comment]
same issue today

**Comment by rubensayshi** [comment]
tried a few versions of the provider, `4.33` works fine, `4.34` introduces this issue

**Comment by rubensayshi** [comment]
correction; downgrading the provider to an older version did not solve the issue ...

**Comment by SimonPNorra** [comment]
Same here. Somebody found a solution for this already?

**Comment by andrealmar** [comment]
same is happening to us here....

**Comment by stayanti** [comment]
same here, also the lifecycle trick does not work here

**Comment by Glenn-Terjesen** [comment]
Lifecycle workaround works for us, but it would be great if it would be fixed, thanks

**Comment by rubensayshi** [comment]
I've never paid much attention to this, but it might have to do with a scheduled upcoming maintenance.

for instances that are due for an upgrade the gcloud API will return the `maintenance_schedule` for the scheduled upcoming maintenance, and then terraform incorrectly NULLs that.

note how it NULLs the properties, not the whole object;

```
      - maintenance_schedule {
          - end_time               = "2023-07-08T05:00:00Z" -> null
          - schedule_deadline_time = "2023-07-15T04:00:00Z" -> null
          - start_time             = "2023-07-08T04:00:00Z" -> null
        }
```

**Comment by KhedoussiAr** [comment]
Lifecycle worked for me, as a temporary solution.

  lifecycle {  
  ignore_changes = [
    maintenance_schedule,
    ]
  }

**Comment by rubensayshi** [comment]
> Lifecycle worked for me, as a temporary solution.
> 
> lifecycle { ignore_changes = [ maintenance_schedule, ] }

this worked for me as well

**Comment by yaba-nofar** [comment]
thanks this solution worked for me!
tried it without the "," before :(
