### ISSUE TITLE
Fix downstream build linter errors

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#11888]
Failure rate: 100%

linter check: https://github.com/hashicorp/terraform-provider-google/runs/6886570050?check_suite_focus=true

Message:
```
google/config.go:36:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/container/v1"
	^
```

Possibly related to https://github.com/hashicorp/terraform-provider-google/issues/9349 ?

**Comment by rileykarson** [comment]
This is green now (and has been for a while)
