### ISSUE TITLE
Unable to create google_compute_forwarding_rule (IPV6)

### ISSUE THREAD

**Issue by pramos12** [hashicorp/terraform-provider-google#11890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add ip_version argument for google_compute_forwarding_rule to allow load balancer TCP/UDP external with IPV6.
https://cloud.google.com/load-balancing/docs/network/setting-up-network-backend-service#configure_the_load_balance

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

```tf
resource "google_compute_forwarding_rule" "google_compute_forwarding_rule_ipv6" {
  name                  = "ipv6-lb-forwarding-rule"
  backend_service       = google_compute_region_backend_service.default.id
  region                = "europe-west1"
  ip_protocol           = "UDP"
  ports                 = ["53"]
  ip_version            = "IPV6"
  load_balancing_scheme = "EXTERNAL"
  all_ports             = false
  allow_global_access   = false
  subnetwork            = google_compute_subnetwork.lb_subnet.id
}
```

**Comment by melinath** [comment]
This was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8453
