### ISSUE TITLE
Failing test(s): TestAccTPUNode_tpuNodeBasicExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11895]
### Affected Resource(s)

* google_tpu_node

Failure rate: 100% since 5/30/22

Impacted tests:
- TestAccTPUNode_tpuNodeBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/301942?buildTab=tests&expandedTest=-6496095039754300046

Message:

```
Error: Error waiting to create Node: Error waiting for Creating Node: Error code 3, message: Cloud TPU received an invalid argument. The 'CIDR Range' value "10.2.0.0/29" on network "<network id>" conflicts with another subnet or object in the (peered) customer network.
```

Note: this is a separate issue on top of https://github.com/hashicorp/terraform-provider-google/issues/10222.

**Comment by AarshDhokai** [comment]
- TestAccTPUNode_tpuNodeBasicExample 
[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6496095039754300046&projectId=GoogleCloud&tab=testDetails&branch_GoogleCloud=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) -- 89% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6496095039754300046&projectId=GoogleCloudBeta&tab=testDetails&branch_GoogleCloudBeta=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) -- 70% failure

**Comment by AarshDhokai** [comment]
b/262233657

**Comment by roaks3** [comment]
Per the duplicate, this was still 100% as of Sept 2022.

We don't see this error anymore, but it's possible it is being hidden by capacity/version errors.

**Comment by melinath** [comment]
We're not seeing this error these days.
