### ISSUE TITLE
Cloud NAT Dynamic Port Allocation / Endpoint Independent Mapping Failure

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#11909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

This looks to be an issue with how the API handles a change like this, I'm of the impression that `force_new` or similar should be setup when this "flip" between modes is detected.

### Terraform Version

1.2.1

### Affected Resource(s)

`google_compute_router_nat`

### Terraform Configuration Files

See below

### Debug Output

```
# module.splunk_logging_network_v2.module.nat_router.google_compute_router_nat.main will be updated in-place
  ~ resource "google_compute_router_nat" "main" {
      ~ enable_dynamic_port_allocation      = true -> false
      ~ enable_endpoint_independent_mapping = false -> true
        id                                  = "tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-8lp-us-central1-router/log-export-net-8lp-us-central1-router"
        name                                = "log-export-net-8lp-us-central1-router"
        # (12 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

│ Error: Error updating RouterNat "tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-8lp-us-central1-router/log-export-net-8lp-us-central1-router": googleapi: Error 400: Invalid value for field 'resource.nats[0].enableDynamicPortAllocation': 'true'. Dynamic Port Allocation cannot be enabled when using endpoint independent mapping., invalid
│ 
│   with module.splunk_logging_network_v2.module.nat_router.google_compute_router_nat.main,
│   on .terraform/modules/splunk_logging_network_v2.nat_router/modules/gcp/compute/cloud-nat/main.tf line 6, in resource "google_compute_router_nat" "main":
│    6: resource "google_compute_router_nat" "main" {
│ 
```

### Expected Behavior

Change should smoothly cutover between the two modes.

### Actual Behavior

Modification fails due to the conflict between the two modes on Cloud NAT.

### Steps to Reproduce

1. Create Cloud NAT with `enable_dynamic_port_allocation ` enabled via terraform
2. Set `enable_dynamic_port_allocation` to false and `enable_endpoint_independent_mapping` in the same modification

### Important Factoids

N/A

### References

* #0000

b/300616894

**Comment by c2thorn** [comment]
For reference, were you able to switch over in two separate apply commands?

**Comment by tgoodsell-tempus** [comment]
Yes I was able to do so:

Apply 1:
```
# module.test_network.module.nat_router.google_compute_router_nat.main will be updated in-place
  ~ resource "google_compute_router_nat" "main" {
      ~ enable_endpoint_independent_mapping = true -> false
        id                                  = "tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-l5w-router/log-export-net-l5w-router"
        name                                = "log-export-net-l5w-router"
        # (14 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
    
module.test_network.module.nat_router.google_compute_router_nat.main: Modifications complete after 11s [id=tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-l5w-router/log-export-net-l5w-router]
```

Apply 2:
```
# module.test_network.module.nat_router.google_compute_router_nat.main will be updated in-place
  ~ resource "google_compute_router_nat" "main" {
      ~ enable_dynamic_port_allocation      = false -> true
        id                                  = "tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-l5w-router/log-export-net-l5w-router"
        name                                = "log-export-net-l5w-router"
        # (14 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
module.test_network.module.nat_router.google_compute_router_nat.main: Modifications complete after 11s [id=tl-wsbamnfgxju9c0bgd6c9/us-central1/log-export-net-l5w-router/log-export-net-l5w-router]
```

**Comment by shijeesh-ns** [comment]
Looks like this issue is obsolete. Tested this behavior and not able to reproduce this issue.
