### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_withServiceAcc

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11907]
### Affected Resource(s)

* google_dataproc_cluster

Failure rate:
- 57% in June 2022
- 67.7% in Mar 2023

Impacted tests:
- TestAccDataprocCluster_withServiceAcc

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/301942?buildTab=tests&expandedTest=-6618324063868354150

Message:

```
Failed to initialize node dproc-cluster-test-j8z34och3q-m: Failed to create event log dir with 403 HTTP response code and 22 exit code See output in: <link>
```

b/326657440

**Comment by AarshDhokai** [comment]
- TestAccDataprocCluster_withServiceAcc
[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6618324063868354150&projectId=GoogleCloud&tab=testDetails&branch_GoogleCloud=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) - 68% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6618324063868354150&projectId=GoogleCloudBeta&tab=testDetails&branch_GoogleCloudBeta=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) - 71% failure

**Comment by AarshDhokai** [comment]
b262234577
