### ISSUE TITLE
Incorrect optional flag for `routine_type` parameter in `google_bigquery_routines` 

### ISSUE THREAD

**Issue by MrwanBaghdad** [hashicorp/terraform-provider-google#11919]
### Affected Resource(s)

* google_bigquery_routine

The docs and the [code generated](https://github.com/hashicorp/terraform-provider-google/blob/0baa871ae8f0cadef4feeeff730ee021ae114154/google/resource_bigquery_routine.go#L161) by the magic modules state that the `routine_type` is optional. This is incorrect per the [docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/routines)

https://github.com/hashicorp/terraform-provider-google/blob/0baa871ae8f0cadef4feeeff730ee021ae114154/google/resource_bigquery_routine.go#L159-L165

b/293328357

**Comment by rileykarson** [comment]
Note: going optional -> required is likely a breaking change

**Comment by MrwanBaghdad** [comment]
@rileykarson, I'm not sure it'd be a breaking change, as the API is already refusing null values for the `routine_type`, the current schema definition in terraform allows an invalid case per the docs IMO updating the field to required would remove an invalid case to be accessible from the terraform module and enforce the exact definition that the upstream API is enforcing

**Comment by roaks3** [comment]
Confirmed that this field is required by the API, and if it is not set in Terraform, the user receives an error:

```
Error: Error creating Routine: googleapi: Error 400: Routine type must be specified, invalid
```

I believe this is safe to change to being required by Terraform without breaking users, but I will confirm with the team that this would not violate any other assumptions.
