### ISSUE TITLE
Issue regarding GCP organization policy module for domain restricted sharing

### ISSUE THREAD

**Issue by G-Tejaswini** [hashicorp/terraform-provider-google#11911]
### Terraform Version
Latest version of terraform v1.1.9

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

Referred github link: https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/1-org/envs/shared/org_policy.tf

Also checked https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/modules/domain_restricted_sharing/main.tf

# Copy-paste your Terraform configurations here.

module "org_domain_restricted_sharing" {
source = "terraform-google-modules/org-policy/google//modules/domain_restricted_sharing"
version = "~> 5.0" (used 3.1.2 as well)
organization_id = var.organization_id
policy_for = var.policy_for
domains_to_allow = var.domains_to_allow
}

domains_to_allow = ["C0XXXXXl"]

variable "domains_to_allow" {
type = list(string)
description = "Domains which need to allow"
}

### Expected Behavior

Domain should be taken.

### Actual Behavior

Getting error as 

Error: Error reading organization: googleapi: Error 400: Request contains an invalid argument., badRequest
289│
290│   with module.org_domain_restricted_sharing.data.google_organization.orgs["C0XXXXX"],
291│   on .terraform/modules/org_domain_restricted_sharing/modules/domain_restricted_sharing/main.tf line 17, in data "google_organization" "orgs":
292│   17: data "google_organization" "orgs" {

### Steps to Reproduce

run this apply on Organization

1. `terraform apply`

**Comment by edwardmedia** [comment]
@G-Tejaswini this appears to be a question to the module. Do you mind filing an issue at the module owners?

**Comment by edwardmedia** [comment]
closing this assuming it is no longer an issue

**Comment by G-Tejaswini** [comment]
Hey can you please let me know the link or path where I can raise issue to
module owners?

**Comment by edwardmedia** [comment]
@G-Tejaswini how about https://github.com/terraform-google-modules/terraform-google-org-policy/issues?
