### ISSUE TITLE
Failing test(s): TestAccCloudFunctionsFunction_cmek

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#11913]
Failure rate: 
TestAccCloudFunctionsFunction_cmek:
- 96% in the 30d after being added on May 3 2022 (1 success)
- 96% June 2022

TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample:
- 96% in May 2022 (failures started Apr 30 2022)

Impacted tests:
- TestAccCloudFunctionsFunction_cmek
- TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/301968?buildTab=tests&expandedTest=-5609233894264835642

Message:

```
Error: Error waiting to create Repository: Error waiting for Creating Repository: Error code 7, message: Permission denied on Cloud KMS key. Please ensure your Artifact Registry service account has been authorized to use the configured key.
```

**Comment by AarshDhokai** [comment]
b/261390516
