### ISSUE TITLE
Compute instance missing external IPv6 address output attribute

### ISSUE THREAD

**Issue by espes** [hashicorp/terraform-provider-google#11918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.25.0
```

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
provider "google" {
  region  = "europe-west2"
}

resource "google_compute_network" "network" {
  name = "demo-net"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnet" {
  name = "demo-subnet"
  network = google_compute_network.network.id
  ip_cidr_range = "10.1.0.0/20"
  stack_type = "IPV4_IPV6"
  ipv6_access_type = "EXTERNAL"
}

resource "google_compute_instance" "instance" {
  name         = "server"
  machine_type = "f1-micro"
  zone         = "europe-west2-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = google_compute_network.network.id
    subnetwork = google_compute_subnetwork.subnet.id
    access_config {
      network_tier = "PREMIUM"
    }
    stack_type = "IPV4_IPV6"
    ipv6_access_config {
      network_tier = "PREMIUM"
    }
  }
}
```

### Debug Output

https://gist.github.com/espes/71be84b987f04421398c968c1459434a

### Expected Behavior

The [network_interface.0.ipv6_access_config.0.external_ipv6](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#network_interface.0.ipv6_access_config.0.external_ipv6) property is populated with the IPv6 address of the instance

### Actual Behavior

external_ipv6 is not populated. Notably, the ipv6 address is visible in `networkInterfaces.ipv6AccessConfigs` when running `gcloud compute instances describe server`, and in the API output in the debug log

### Steps to Reproduce

1. `terraform apply`
2. `terraform state show google_compute_instance.instance`
3. Observe the `ipv6_access_config` block does not contain the `external_ipv6` field

I'm not an expert on provider internals, but comparing the `flattenIpv6AccessConfigs` method to the equivalent `flattenAccessConfigs` method seems suspect: https://github.com/hashicorp/terraform-provider-google/blob/main/google/compute_instance_helpers.go#L171

**Comment by jbg** [comment]
This was missed from the release notes / changelog, and is a breaking change; previously the `external_ipv6_address` attribute was always set to an empty string, whereas now it seems that it's either a valid IPv6 address or `null`. We had hacks in place before to deal with the empty string, and those hacks now cause the TF plan to error out when an instance doesn't have an IPv6 address (because passing `null` to the TF `length()` function causes an error).
