### ISSUE TITLE
Cannot create google_project_access_approval_settings resrouce

### ISSUE THREAD

**Issue by tSte** [hashicorp/terraform-provider-google#11920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.25.0
+ provider registry.terraform.io/hashicorp/google-beta v4.25.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

### Affected Resource(s)

* google_project_access_approval_settings

### Terraform Configuration Files

```tf
resource "google_project_service" "access_approval_api" {
  provider = google.us
  service  = "accessapproval.googleapis.com"

  disable_on_destroy = true
}

resource "google_project_access_approval_settings" "project_access_approval" {
  provider   = google.us
  project_id = local.project_id

  notification_emails = ["some@email.com"]

  enrolled_services {
    cloud_product    = "all"
    enrollment_level = "BLOCK_ALL"
  }

  depends_on=[google_project_service.access_approval_api]
}
```

### Expected Behavior

Terraform should create resource

### Actual Behavior

Terraform ends up with:
```
Error: Error when reading or editing AccessApprovalProjectSettings "projects/some-project-id/accessApprovalSettings": googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the accessapproval.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/. If you are getting this error with curl or similar tools, you may need to specify 'X-Goog-User-Project' HTTP header for quota and billing purposes. For more information regarding 'X-Goog-User-Project' header, please check https://cloud.google.com/apis/docs/system-parameters.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/some-project-number",
│       "service": "accessapproval.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
```

### Steps to Reproduce

`terraform apply` with previous configuration

1. `terraform apply`

### Important Factoids

1. I've got enabled access transparency.
2. I can set up access approval for my project via UI, using the same account that is used by Terraform.
3. I've set up quota project using `gcloud` CLI and verified that the field exists in the `application_default_credentials.json` file.

**Comment by tSte** [comment]
Hey,

I enabled [access transparency](https://cloud.google.com/cloud-provider-access-management/access-transparency/docs/enable) for the entire GCP organisation.

I also enabled access approval API, like this:
```tf
resource "google_project_service" "access_approval_api" {
  provider = google.us
  service  = "accessapproval.googleapis.com"

  disable_on_destroy = true
}
```

But I also tried to enable the API [manually, via GCP console UI](https://cloud.google.com/cloud-provider-access-management/access-approval/docs/review-approve-access-requests-google-keys).

I ran this code in an empty project, twice. Always the same result.
```tf
terraform {
  required_version = "1.2.3"
  backend "gcs" { bucket = "hm-playground-terraform-state" }

  required_providers {
    google = {
      version               = "4.28.0"
      source                = "hashicorp/google"
      configuration_aliases = [google.eu]
    }
  }
}

locals { project_id = "myplayground" }

provider "google" {
  alias = "eu"

  project = local.project_id
  region  = "europe-west3"
  zone    = "europe-west3-a"
}

resource "google_project_service" "access_approval_api" {
  provider = google.eu
  service  = "accessapproval.googleapis.com"

  disable_on_destroy = true
}

resource "google_project_access_approval_settings" "project_access_approval" {
  provider   = google.eu
  project_id = local.project_id

  notification_emails = ["my_user@email.com"]

  enrolled_services {
    cloud_product    = "all"
    enrollment_level = "BLOCK_ALL"
  }

  depends_on = [google_project_service.access_approval_api]
}

```

Here's [TF debug log](https://gist.github.com/tSte/0b21c1d4abba741fe463c28e3cb3fe08).

**Comment by edwardmedia** [comment]
@tSte my understanding is that you are using a service account that has the key file `application_default_credentials.json`, like [here](https://cloud.google.com/docs/authentication/production#passing_variable). What role did you give to that service account? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#credentials

**Comment by tSte** [comment]
I'm not using service account, I'm using my own account.

**Comment by edwardmedia** [comment]
@tSte can you try using a service account instead of your User Credential? Giving that account with owner role for your project.

**Comment by tSte** [comment]
It seems to be working with service account. Why doesn't it work with regular one?

**Comment by edwardmedia** [comment]
@tSte I think the API's error message has explained a little bit. Glad it works with a service account. Closing the issue then
