### ISSUE TITLE
Error 400 when update app engine domain mapping

### ISSUE THREAD

**Issue by tiaguinho** [hashicorp/terraform-provider-google#11922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.2.2

### Affected Resource(s)

* google_app_engine_domain_mapping

### Terraform Configuration Files

```tf
resource "google_app_engine_domain_mapping" "domain_mapping" {
  for_each = local.services

  project     = local.project_id
  domain_name = "${each.value.domain}.example.com"

  ssl_settings {
    ssl_management_type = "AUTOMATIC"
  }
}
```

### Expected Behavior

Nothing to be updated

### Actual Behavior

On `terraform plan`:

```bash
 # google_app_engine_domain_mapping.domain_mapping["ID"] will be updated in-place
  ~ resource "google_app_engine_domain_mapping" "domain_mapping" {
        id                = "apps/PROJECT_ID/domainMappings/DOMAIN"
        name              = "apps/PROJECT_ID/domainMappings/DOMAIN"
      + override_strategy = "STRICT"
        # (3 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }
```

On `terraform apply`:
```bash
╷
│ Error: Error updating DomainMapping "apps/PROJECT_ID/domainMappings/DOMAIN": googleapi: Error 400: At least one field must be specified for this operation.
│ 
│   with google_app_engine_domain_mapping.domain_mapping["ID"],
│   on appengine.tf line 2, in resource "google_app_engine_domain_mapping" "domain_mapping":
│    2: resource "google_app_engine_domain_mapping" "domain_mapping" {
│ 
╵
```

### Steps to Reproduce

1. Import existing resource
2. `terraform plan`
3. `terraform apply`

### My findings

On line 65 of [resource_app_engine_domain_mapping.go](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_app_engine_domain_mapping.go#L65) there is a `override_strategy` attribute for this resource.
When I do the import, this attribute has a null value on the tfstate file.

I check on [GCP Domain Mapping API](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.domainMappings#resource:-domainmapping) and this attribute doesn't exist.

Digging a little deeper, on line 328 of [resource_app_engine_domain_mapping.go](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_app_engine_domain_mapping.go#L328) there is a check for changes on `ssl_settings`, and since there is no change on this attribute, the `updateMask` variable will be empty on line 334 making the field `updateMask` of the url empty too.

This is causing the error mentioned before.

I don't know if the `override_strategy` is supposed to be an internal attribute for terraform, but it is causing an error trying to apply changes on there is nothing to be changed.

**Comment by edwardmedia** [comment]
Closed this assuming this is no longer an issue
