### ISSUE TITLE
Add Cloud Run SLO support

### ISSUE THREAD

**Issue by tiagojsag** [hashicorp/terraform-provider-google#11935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to [these release notes](https://cloud.google.com/run/docs/release-notes#May_05_2022), Cloud Run recently added support for SLOs. If these are supported already by the current TF resources, it's not really clear how, and I suspect that at least a new google_monitoring_cluster_cloud_run_service data source would be necessary (or at least very convenient). There might be additional needs on new/existing data sources/resources - this is my first time configuring SLOs, so newb alert/disclaimer. 

### New or Affected Resource(s)

* google_monitoring_cluster_cloud_run_service -  a data source to reference a Cloud Run service on an SLO, similar to what is already done in google_monitoring_app_engine_service, for example.

### Potential Terraform Configuration

```tf
# Context data
data "google_cloud_run_service" "run-service" {
  name = "my-service"
  location = "us-central1"
}

# the actual new data source
data "google_monitoring_cluster_cloud_run_service" "srv" {
  service_id = data.google_cloud_run_service.run-service.id
}
```

### References

* #0000

**Comment by rileykarson** [comment]
Note: I haven't looked at the API yet, but this sounds like it may be a resource rather than a datasource

**Comment by jakubsacha** [comment]
Hey,

I've been looking at this today a bit, and you're right. *Monitoring service* needs to be created so it's resource not a data source.

Regarding the name, shouldn't it be `google_monitoring_cloud_run_service` instead of `google_monitoring_cluster_cloud_run_service`? Maybe even `google_monitoring_service` that supports all possible cases. That would reflect google API a bit better. [Google docs](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services#resource:-service) states it supports various types of *monitoring services*: 
- "custom": 
- "appEngine": 
- "clusterIstio": 
- "meshIstio": 
- "istioCanonicalService": 
- "cloudRun": 
- "gkeNamespace": 
- "gkeWorkload": 
- "gkeService":

**Comment by etruong42** [comment]
There's an internal Google ticket (b/234447582) about this that I am actively working on.

Preview: jakubsacha's choice of `google_monitoring_service` matches our design choice as well!

We currently have `google_monitoring_custom_service`, but we have found that it would be more useful for users to create all sorts of "service" resources to support SLOs in Cloud Run and all the other aforementioned services.

**Comment by jakubsacha** [comment]
Thanks for a feedback. Please let me know in case I can support you.

**Comment by rileykarson** [comment]
Closing, thanks! In the future if you use "Fixes {{issue}}" in a PR body, merging the PR will autoclose the issue.

**Comment by rileykarson** [comment]
Ah- @slevenick beat me to it.
