### ISSUE TITLE
Cannot delete google_cloudfunctions2_function (Cloud Functions 2nd gen)

### ISSUE THREAD

**Issue by Kopunk** [hashicorp/terraform-provider-google#11937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.26.0
+ provider registry.terraform.io/hashicorp/google-beta v4.26.0

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

* the version of the config before the change
```tf
resource "google_storage_bucket" "this" {
  name          = "myawesomecustomstroagebucket"
  location      = "EU"
  storage_class = "STANDARD"
  uniform_bucket_level_access = true
}

data "archive_file" "this" {
  type        = "zip"
  source_dir  = var.source_dir
  output_path = "./tmp/zipped-functions/${var.function_name}.zip"
}

resource "google_storage_bucket_object" "this" {
  name         = "${var.function_name}-source.zip"
  bucket       = google_storage_bucket.this.name
  source       = data.archive_file.this.output_path
  content_type = "application/zip"
}

resource "google_cloudfunctions2_function" "this" {
  depends_on = [google_storage_bucket_object.this]

  provider = google-beta
  location = var.location

  name        = var.function_name

  build_config {
    runtime               = "nodejs16"
    entry_point           = var.function_entry_point
    environment_variables = var.function_build_env_vars

    source {
      storage_source {
        bucket = google_storage_bucket.this.name
        object = google_storage_bucket_object.this.name
      }
    }
  }

  service_config {
    max_instance_count    = 1
    available_memory      = var.function_memory
    timeout_seconds       = var.function_timeout_seconds
    environment_variables = var.function_env_vars
    ingress_settings      = "ALLOW_INTERNAL_ONLY"
  }
}
```
* the version of the config after the change.

```tf
resource "google_storage_bucket" "this" {
  name          = "myawesomecustomstroagebucket"
  location      = "EU"
  storage_class = "STANDARD"
  uniform_bucket_level_access = true
}

data "archive_file" "this" {
  type        = "zip"
  source_dir  = var.source_dir
  output_path = "./tmp/zipped-functions/${var.function_name}.zip"
}

resource "google_storage_bucket_object" "this" {
  name         = "${var.function_name}-source.zip"
  bucket       = google_storage_bucket.this.name
  source       = data.archive_file.this.output_path
  content_type = "application/zip"
}

# resource "google_cloudfunctions2_function" "this" {
#   depends_on = [google_storage_bucket_object.this]
# 
#   provider = google-beta
#   location = var.location
# 
#   name        = var.function_name
# 
#   build_config {
#     runtime               = "nodejs16"
#     entry_point           = var.function_entry_point
#     environment_variables = var.function_build_env_vars
# 
#     source {
#       storage_source {
#         bucket = google_storage_bucket.this.name
#         object = google_storage_bucket_object.this.name
#       }
#     }
#   }
# 
#   service_config {
#     max_instance_count    = 1
#     available_memory      = var.function_memory
#     timeout_seconds       = var.function_timeout_seconds
#     environment_variables = var.function_env_vars
#     ingress_settings      = "ALLOW_INTERNAL_ONLY"
#   }
# }
```

### Expected Behavior

- Cloud Function 2nd gen is deleted
- underlying Cloud Run service is deleted
- function artifacts in Artifact Registry are deleted

### Actual Behavior

`terraform apply` returns error while deleting `google_cloudfunctions2_function`:
```
Error: Error waiting for Deleting function: Error code 5, message: Delete package operation for projects/myawesomeproj-staging/locations/europe-west1/repositories/gcf-artifacts/packages/test--functions--v2--hello--world%2Fcustom-run has failed. Additional information: Requested entity was not found..
```

- function is **not** deleted (in console shown with unknown status) :x: 
- underlying Cloud Run service is deleted :heavy_check_mark: 
- function artifacts in Artifact Registry are deleted :heavy_check_mark: 

The artifacts do exist in Artifact Registry (in `myawesomeproj-staging/gcf-artifacts` directory) before the deletion of the resource and get deleted despite the error message.

### Steps to Reproduce

1. `terraform apply` (after commenting out the google_cloudfunctions2_function resource)

**Comment by c2thorn** [comment]
Tagging @k-ezis	to take a look

**Comment by oilegor1029** [comment]
I have the same problem and I am not able to delete the cloud function manually in GCP Console.
Do you know how to delete it while the team fixes it?

**Comment by rileykarson** [comment]
Does the Console fail with the same error? I'd be curious what it fails with, to help identify a Terraform issue vs an API issue.

**Comment by oilegor1029** [comment]
This is a GCP Issue:
https://status.cloud.google.com/incidents/6ocKuGf4LTJTjaB84Ms4 
I think that we can close this issue (or leave it open till GPC fixes it) @rileykarson

**Comment by k-ezis** [comment]
Yes, this was an API issue that should now be resolved: https://status.cloud.google.com/incidents/6ocKuGf4LTJTjaB84Ms4
This was separate from our Terraform configuration and everyone should be able to delete functions as expected. Please let me know if you continue to see issues and I'll raise the issue with my team.
