### ISSUE TITLE
Enabling container cluster addon cloudrun_config results in error

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#11943]
### Affected Resource(s)

* google_container_cluster

Pinpointed the issue causing https://github.com/hashicorp/terraform-provider-google/issues/11897: Enabling `cloudrun_config` results in an error. Potentially due to new cluster version `1.23.6-gke.1500`.

Could be an upstream issue, filing here to track.

**Comment by shuyama1** [comment]
@c2thorn Please confirm if this issues has been fixed and feel free to close it, if so. If this bug still needs to be forwarded to the service team, please remove `service/terraform` label.
