### ISSUE TITLE
Cloud Composer: scheduler_count update does not change number of scheduler in environment

### ISSUE THREAD

**Issue by kubasieron** [hashicorp/terraform-provider-google#11940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

all versions

### Terraform Configuration Files

```tf
provider "google" {
  region = "us-central1"
  project = "my-project"
}

resource "google_composer_environment" "testman" {
  name   = "sample-name"
  region = "us-central1"
  project = "my-project"

  config {
    software_config {
      image_version = "composer-1.19.0-airflow-2.2.5"
      scheduler_count = 2
    }

    private_environment_config {
      enable_private_endpoint = true
    }

    node_config {
      ip_allocation_policy {
        use_ip_aliases = true
      }
    }
  }
}
```

### Expected Behavior

number of schedulers in environment is updated

### Actual Behavior

number of schedulers in environment was not updated

### Steps to Reproduce

starting config:
```tf
provider "google" {
  region = "us-central1"
  project = "my-project"
}

resource "google_composer_environment" "testman" {
  name   = "sample-name"
  region = "us-central1"
  project = "my-project"

  config {
    software_config {
      image_version = "composer-1.19.0-airflow-2.2.5"
    }

    private_environment_config {
      enable_private_endpoint = true
    }

    node_config {
      ip_allocation_policy {
        use_ip_aliases = true
      }
    }
  }
}
```

1. `terraform apply`
2. environment is created properly
3. changing configuration (scheduler_count -> 2)

```tf
provider "google" {
  region = "us-central1"
  project = "my-project"
}

resource "google_composer_environment" "testman" {
  name   = "sample-name"
  region = "us-central1"
  project = "my-project"

  config {
    software_config {
      image_version = "composer-1.19.0-airflow-2.2.5"
      scheduler_count = 2
    }

    private_environment_config {
      enable_private_endpoint = true
    }

    node_config {
      ip_allocation_policy {
        use_ip_aliases = true
      }
    }
  }
}
```
4. `terraform apply`
5. environment still has one scheduler

### References

* #0000

**Comment by kubasieron** [comment]
I wish to work on this item

**Comment by megan07** [comment]
Fixed by https://github.com/GoogleCloudPlatform/terraform-validator/pull/785
