### ISSUE TITLE
Role roles/iap.httpsResourceAccessor has been retired

### ISSUE THREAD

**Issue by independentid** [hashicorp/terraform-provider-google#11979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`Terraform v1.2.3`

### Affected Resource(s)

* google_compute_backend_service_iam_policy`

### Terraform Configuration Files

```tf
data "google_iam_policy" "canary_access_policy" {
  binding {
    role = "roles/iap.httpsResourceAccessor"
    members = [
      "user:phil.hunt@independentid.com",
      "domain:strata.io"
    ]
  }
}

resource "google_compute_backend_service_iam_policy" "iam_policy" {
  provider = google-beta
  project = var.GCP_PROJECT_ID
  name = google_compute_backend_service.canary_backend_service.name
  policy_data = data.google_iam_policy.canary_access_policy.policy_data
}
```

### Debug Output

```
Terraform will perform the following actions:

  # google_compute_backend_service_iam_policy.iam_policy will be created
  + resource "google_compute_backend_service_iam_policy" "iam_policy" {
      + etag        = (known after apply)
      + id          = (known after apply)
      + name        = "canary-bank-backend"
      + policy_data = jsonencode(
            {
              + bindings = [
                  + {
                      + members = [
                          + "domain:strata.io",
                          + "user:phil.hunt@independentid.com",
                        ]
                      + role    = "roles/iap.httpsResourceAccessor"
                    },
                ]
            }
        )
      + project     = "phil-workspace"
    }

...
╷
│ Error: Error setting IAM policy for compute backendservice "projects/phil-workspace/global/backendServices/canary-bank-backend": googleapi: Error 400: Role roles/iap.httpsResourceAccessor has been retired., invalidIamPolicy
│ 
│   with google_compute_backend_service_iam_policy.iam_policy,
│   on main.tf line 161, in resource "google_compute_backend_service_iam_policy" "iam_policy":
│  161: resource "google_compute_backend_service_iam_policy" "iam_policy" {
│ 
╵
```
### Expected Behavior

Should set the role as specified.

### Actual Behavior

See role retired error above. 

### Steps to Reproduce

1. `terraform apply`

### References

This is the same issue as identified in closed issue #11751 and is filed her per the note on that issue.

**Comment by edwardmedia** [comment]
I can repro the issue. As stated in #11751, the error is from api, and looks like it is the role specific. The tf resource is fine. After changing the role to `roles/compute.admin`, the resource gets created without an issue.

**Comment by edwardmedia** [comment]
@independentid Here is the response from APIs. So error is legit. Can you try with other roles?

```
iap.httpsResourceAccessor is a valid role.

However, the only permission it contains in iap.webServiceVersions.accessViaIAP, and so it cannot be granted on a compute backendServices resource. Instead, it can only be used on IAP resources, such as those in https://cloud.google.com/iap/docs/managing-access#managing_access_with_the_api.

The slightly confusing error message is because the MVP of IAP had a different permission model, and the role previously could have been granted on compute resources, but that was disabled in 2018.
```

**Comment by timeyr** [comment]
I think  `google_compute_backend_service` does not yield the correct object to attach the permission to. It yields something like 

`https://www.googleapis.com/compute/v1/projects/{project}/global/backendServices/{name}`.

However, according to https://cloud.google.com/iap/docs/managing-access#managing_access_with_the_api, we are supposed to add the permission to a resource that looks like

`https://iap.googleapis.com/v1/projects/{project}/iap_web/compute/services/{name or id}`

I suspect there are two "version" of the backend service resource, one for "compute" and one for "iap", and terraform currently only exposes the former, while we need the latter.

**Comment by timeyr** [comment]
`google_compute_backend_service_iam_policy` is the wrong resource, you need to use `google_iap_web_backend_service_iam_policy` instead.

**Comment by edwardmedia** [comment]
Close assuming this is no longer an issue
