### ISSUE TITLE
`google_cloud_scheduler_job` state is flaky

### ISSUE THREAD

**Issue by ace-n** [hashicorp/terraform-provider-google#11977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.1.8

### Affected Resource(s)

* google_cloud_scheduler_job

### Terraform Configuration Files

```tf
esource "google_cloud_run_service" "default" {
    name     = "hello"
    location = "us-central1"
    template {
      spec {
            containers {
                image = "us-docker.pkg.dev/cloudrun/container/hello"
            }
      }
    }
    traffic {
      percent         = 100
      latest_revision = true
    }
}

resource "google_cloud_scheduler_job" "job" {
  name             = "test-job"
  description      = "test http job"
  schedule         = "*/8 * * * *"
  time_zone        = "America/New_York"
  attempt_deadline = "320s"

  retry_config {
    retry_count = 1
  }

  http_target {
    http_method = "POST"
    uri         = google_cloud_run_service.default.status[0].url
    body        = base64encode("{\"foo\":\"bar\"}")
  }
}

```

### Debug Output

https://gist.github.com/ace-n/4261f3616a23708846fd16fefdf62161

### Behavior

The `google_cloud_scheduler_job` resource has two flaky state components.

#### Flaky URIs
For _reads_, the `google_cloud_scheduler_job` object will append a `/` to the `http_target.uri` property - but for _writes_, it won't.

#### Flaky `headers` property
The `http_target.headers` property seems to be required (i.e. a default value is included) on _update_, but not on _create_.

### Steps to Reproduce

1. Run an initial `terraform init`, followed by a `terraform apply`.
2. Run a second `terraform apply`.

### Workaround

To work around this, ensure the `http_target.uri` property **always** ends with a slash (`/`):
```tf
http_target {
    http_method = "POST"
    uri         = "${google_cloud_run_service.default.status[0].url}/"
    body        = base64encode("{\"foo\":\"bar\"}")
  }
```

**Comment by edwardmedia** [comment]
```
      ~ http_target {
          ~ uri         = "https://hello-rehvs75zla-uc.a.run.app/" -> "https://hello-rehvs75zla-uc.a.run.app"
            # (3 unchanged attributes hidden)
        }
```
