### ISSUE TITLE
google_storage_bucket: support for `MatchesPrefix` and `MatchesSuffix` in condition of  the lifecycle rule

### ISSUE THREAD

**Issue by shamil** [hashicorp/terraform-provider-google#11990]
Provider version: `4.27.0`
Terraform version: `1.2.3`

Please add support for [`MatchesPrefix` and `MatchesSuffix`](https://cloud.google.com/storage/docs/lifecycle#matchesprefix-suffix) to the condition of the lifecycle rule.

**Comment by gcaracuel** [comment]
https://github.com/hashicorp/terraform-provider-google-beta/pull/4527 is merged so can we close this?

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6237
