### ISSUE TITLE
google_container_aws_cluster / google_container_aws_node_pool should provide either data module or output of security_group_id it manages

### ISSUE THREAD

**Issue by peter-mueller-viacom** [hashicorp/terraform-provider-google#11992]
Hello!

When creating Anthos on AWS cluster using terraform it creates a security group for the control plane & node pool that it manages.  I cannot seem to access this security group programmatically from the resource() modules output, or find a data source to ingest it from.

As a workaround to finding the IDs I am currently using a double filter:
data "aws_security_group" "nodepool_sg" {
  filter {
    name   = "description"
    values = ["Base security group for the node pool"]
  }
  filter {
    name   = "tag:Name"
    values = ["${var.k8s_cluster_short_name}-${var.env}-np"]
  }
}

But I don't like this solution long-term, and I think the output and|or data source should be provided instead by the module.  Can you please add this feature?  Many thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_container_aws_cluster
* google_container_aws_node_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by shuyama1** [comment]
Hi @peter-mueller-viacom! Thanks for filing the request. Looks like we do support field `security_group_ids` in both `google_container_aws_cluster` and `google_container_aws_node_pool`. Is this what you are looking for or are you looking for a datasource specifically? 
Would you mind sharing what your use case is? Are you trying to refer the value of `security_group_id` in the same configuration as the resource is created, or are you trying to look up the security groups of an existing resource  in a separate configuration ?

**Comment by edwardmedia** [comment]
Closed as implemented
