### ISSUE TITLE
CMEK for Redis (resource google_redis_instance)

### ISSUE THREAD

**Issue by debrutal** [hashicorp/terraform-provider-google#11991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Enable terraform redis to support CMEK

- Google API supports defining cmek for Redis. [link](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#resource:-instance)

Though it is not listed as [supported yet](https://cloud.google.com/kms/docs/using-other-products#cmek_integrations), redis via CMEK is in PRE-GA status listed [here](https://cloud.google.com/memorystore/docs/redis/cmek)

Caching data in redis considering GDPR this would be a great addition to see this supported.

### New or Affected Resource(s)

* [google_redis_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance)

### Potential Terraform Configuration

```tf
      google_redis_instance { 
     ...
       customer_managed_encryption {
          kms_key_name = var.secret_manager_key_name
        }
     ...
    }
```

### References
I was orienting myself for this example using [google_secret_manager_secret](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#customer_managed_encryption)

**Comment by shuyama1** [comment]
Looks like the feature is implemented in https://github.com/GoogleCloudPlatform/magic-modules/pull/6197 which should be released in version 4.28.0
