### ISSUE TITLE
example of usage of alert_strategy for google_monitoring_alert_policy

### ISSUE THREAD

**Issue by dxk185** [hashicorp/terraform-provider-google#12016]
Hi Team,

I could not get a good example of using alert_strategy option for google_monitoring_alert_policy, resource.
The documentation https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#nested_alert_strategy, is not clear on this either.
I keep on getting this error message :

**Error: Unsupported block type
Blocks of type "alert_strategy" are not expected here.**

The pseudo code is:

resource "google_monitoring_alert_policy" "<pseudo>" {
  project = <pseudo>
  display_name = <pseudo>
  combiner = "OR"
  conditions {
    display_name = <pseudo>
    condition_threshold {
      filter = <pseudofilter>
      duration   = "60s"
      comparison = "COMPARISON_GT"
      aggregations {
        alignment_period   = "60s"
        per_series_aligner = DELTA_ALIGN
        cross_series_reducer = "REDUCE_COUNT"
      }
      trigger {
        count = "1"
      }
    }
  }
  alert_strategy {
    auto_close = "1800s"
  }
  notification_channels = <pseudocode>
  depends_on  = [
    google_logging_metric.<pseudoresource>
  ]
}

**Comment by edwardmedia** [comment]
@dxk185 how about this?
```
resource "google_monitoring_alert_policy" "alert_policy" {
    display_name = "My Alert Policy"
    combiner     = "OR"
    conditions {
        display_name = "test condition"
        condition_threshold {
            filter     = "metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\" AND resource.type=\"gce_instance\""
            duration   = "60s"
            comparison = "COMPARISON_GT"
            aggregations {
            alignment_period   = "60s"
            per_series_aligner = "ALIGN_RATE"
            }
        }

    }

    alert_strategy {
        auto_close = true
    }

    user_labels = {
        foo = "bar"
    }
}
```

**Comment by dxk185** [comment]
From the response explanation, it is just the same position where I have provided the "alert_strategy" block as well. That is just outside the "conditions" block. The same level as in "display_name".

**Comment by edwardmedia** [comment]
@dxk185 what do you try to do?

**Comment by edwardmedia** [comment]
@dxk185 it should work as configured like [this](https://github.com/hashicorp/terraform-provider-google/issues/12016#issuecomment-1177728530). Closing this question then.
