### ISSUE TITLE
Changing display name on google_bigquery_data_transfer_config resource shouldn't force replacement

### ISSUE THREAD

**Issue by amardeep** [hashicorp/terraform-provider-google#12012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.27.0
```

### Affected Resource(s)

* google_bigquery_data_transfer_config

with `data_source_id = "google_cloud_storage"`

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs
    google = {
      source  = "hashicorp/google"
      version = "~> 4.27.0"
    }
  }
}

provider "google" {
  project = "..."
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_bigquery_data_transfer_config" "test" {
  display_name   = "Test name"
  data_source_id = "google_cloud_storage"
  location       = "US"

  schedule               = "every day 08:09"
  destination_dataset_id = "..."

  params = {
    allow_jagged_rows               = "true"
    allow_quoted_newlines           = "true"
    data_path_template              = "..."
    destination_table_name_template = "test"
    field_delimiter                 = ","
    file_format                     = "CSV"
    max_bad_records                 = "0"
    skip_leading_rows               = "1"
    write_disposition               = "MIRROR"
  }

  email_preferences {
    enable_failure_email = true
  }
}
```

### Expected Behavior

terraform plan shouldn't show force replacement needed

### Actual Behavior

terraform plan  shows force replacement needed

```
# google_bigquery_data_transfer_config.test must be replaced
-/+ resource "google_bigquery_data_transfer_config" "test" {
...
~ display_name  = "Old test name" -> "Test name" # forces replacement
...
}

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by edwardmedia** [comment]
@amardeep same answer to your question https://github.com/hashicorp/terraform-provider-google/issues/12013
