### ISSUE TITLE
Changing  data_path_template in google_bigquery_data_transfer_config should result in force replacement

### ISSUE THREAD

**Issue by amardeep** [hashicorp/terraform-provider-google#12013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.27.0
### Affected Resource(s)

* google_bigquery_data_transfer_config

with `data_source_id = "google_cloud_storage"`

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    # https://registry.terraform.io/providers/hashicorp/google/latest/docs
    google = {
      source  = "hashicorp/google"
      version = "~> 4.27.0"
    }
  }
}

provider "google" {
  project = "..."
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_bigquery_data_transfer_config" "test" {
  display_name   = "Test name"
  data_source_id = "google_cloud_storage"
  location       = "US"

  schedule               = "every day 08:09"
  destination_dataset_id = "..."

  params = {
    allow_jagged_rows               = "true"
    allow_quoted_newlines           = "true"
    data_path_template              = "..."
    destination_table_name_template = "test"
    field_delimiter                 = ","
    file_format                     = "CSV"
    max_bad_records                 = "0"
    skip_leading_rows               = "1"
    write_disposition               = "MIRROR"
  }

  email_preferences {
    enable_failure_email = true
  }
}
```

### Expected Behavior

params.data_path_template is immutable, so running terraform plan should result in force replacement

### Actual Behavior

On changing params.data_path_template, plan/apply do not show force replacement and apply results in an error:

```
# google_bigquery_data_transfer_config.test will be updated in-place
~ resource "google_bigquery_data_transfer_config" "test"
...
      ~ params                   = {
          ~ "data_path_template"              = "gs://<old...>" -> "gs://<new...>"
            # (8 unchanged elements hidden)
        }
...
Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

google_bigquery_data_transfer_config.test: Modifying... [id=...]
╷
│ Error: Error updating Config "projects/...": googleapi: Error 400: Immutable parameter data_path_template with value string_value:         "gs://<old...>"
│  cannot be changed to string_value:    "gs://<new...>"
│ 
│   with google_bigquery_data_transfer_config.test,
│   on test.tf line 1, in resource "google_bigquery_data_transfer_config" "test":
│    1: resource "google_bigquery_data_transfer_config" "test" {
│ 
╵


```

**Comment by edwardmedia** [comment]
@amardeep as you see [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#params), parameters specific to each data source. Thus all individual fields in the params are not defined in the provider. It is up to api how to behave if you plan to update each field. I guess this would be fixed. Does this make sense?

**Comment by amardeep** [comment]
If I understand you correctly:
- Individual fields in params aren't/can't be defined in the provider.
- Some but not all of the fields are immutable - so if they are changed, api will throw error.

I guess it is fine to leave it like this if there is no better option. But it would be nice to atleast document
this behaviour in the docs and suggest a workaround of applying with `-replace=...` flag.

**Comment by edwardmedia** [comment]
@amardeep that is correct. What do you mean about the workaround of applying with `-replace=...`?

**Comment by edwardmedia** [comment]
@amardeep oh I see what you mean. @ScottSuarez do we usually specify this out in the doc?

**Comment by ScottSuarez** [comment]
We can, I don't see why not
