### ISSUE TITLE
location is set to null on terraform import for bigquery transfer config

### ISSUE THREAD

**Issue by amardeep** [hashicorp/terraform-provider-google#12011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.27.0
```

### Affected Resource(s)

* google_bigquery_data_transfer_config

where `data_source_id = "google_cloud_storage"`

### Command
```
terraform import google_bigquery_data_transfer_config.<resource_name> <config_id>
```

### Expected Behavior

In resulting state file, location should be set appropriately - for eg. `"location": "US"`

### Actual Behavior

After import, location in state is set to null: `"location": null`

This causes an issue, as now terraform plan shows it would need to recreate the resource:

```
$ terraform plan
...
+ location                 = "US" # forces replacement
...
```

Same message is shown if location is set to null or "US" in tf file.

**Comment by edwardmedia** [comment]
The location is part of the {{name}}

**Comment by lodotek** [comment]
What's the latest status here?

Thank you.

**Comment by lodotek** [comment]
any progress?

**Comment by kieronellis** [comment]
Importing for us has `location = ""`, rather than null.

**Comment by giulianobr** [comment]
OMG it still open! @zli82016 can you help here?

**Comment by shohei-ihaya** [comment]
Any updates?
I'm also facing this problem 😢

**Comment by giulianobr** [comment]
Hey team @zli82016 @edwardmedia @trodge @obada-ab any update here?
Thanks!

**Comment by obada-ab** [comment]
Seems like an issue with the custom import code, working on a fix
