### ISSUE TITLE
Error waiting for Creating CloudFunctions Function: timeout while waiting for state to become 'done: true'

### ISSUE THREAD

**Issue by ShaohuiQian** [hashicorp/terraform-provider-google#12017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.14.9

providers
    google  = "= 4.18.0"
    google-beta = "= 4.18.0"

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

resource "google_cloudfunctions_function" "main" {
      + available_memory_mb           = 256
      + description                   = "Cloud Function to create flattened BQ tables"
      + entry_point                   = "create_flattened_view"
      + environment_variables         = {
          + "DATA_PROJECT"           = "ygt-v2-synth-data"
          + "FHIR_DATASET"           = "final_fhir"
          + "FLATTENED_FHIR_DATASET" = "final_fhir_flattened"
        }
      + https_trigger_url             = (known after apply)
      + id                            = (known after apply)
      + ingress_settings              = "ALLOW_INTERNAL_ONLY"
      + max_instances                 = 0
      + name                          = "flattening-function"
      + project                       = "ygt-v2-synth-intake"
      + region                        = "us-central1"
      + runtime                       = "python37"
      + service_account_email         = "function-runner@ygt-v2-synth-intake.iam.gserviceaccount.com"
      + timeout                       = 540
      + vpc_connector                 = "projects/ygt-v2-networks/locations/us-central1/connectors/vpc-connector"
      + vpc_connector_egress_settings = "ALL_TRAFFIC"
      + event_trigger {
          + event_type = "google.pubsub.topic.publish"
          + resource   = "projects/ygt-v2-synth-intake/topics/fhirflattening"
          + failure_policy {
              + retry = (known after apply)
            }
        }
      + source_repository {
          + deployed_url = (known after apply)
          + url          = "https://source.developers.google.com/projects/hcls-hdc-artifacts-test/repos/hdc-cloud-functions/fixed-aliases/latest"
        }
    }

### Debug Output

Error: Error waiting for Creating CloudFunctions Function: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 5m0s)

  on .terraform/modules/flattening_cf/modules/repository-function/main.tf line 17, in resource "google_cloudfunctions_function" "main":
  17: resource "google_cloudfunctions_function" "main" {

### Expected Behavior

No error

### Actual Behavior

tf-apply failed due to the error above quite often in our projects

But the Cloud Function is actually deployed. It looks it timed out because CF was not deployed when terraform was checking.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ShaohuiQian** [comment]
Hey Edward, it is deployed with terraform in a large project, and we are using `terraform init && terraform apply -auto-approve`. Is this what you are asking for?

terraform found cf was not done at a certain time point, but cf was actually done later on after the time point tf was checking it.

**Comment by edwardmedia** [comment]
@ShaohuiQian can you repro it manually? Just including the related resources. Please share the debug log of the execution?

**Comment by ShaohuiQian** [comment]
It's flaky, I am not sure I can make it happen by intention.

But here's a log from history run. https://gist.github.com/ShaohuiQian/acb8a5cfffe7e3e9b531f973da403463

**Comment by edwardmedia** [comment]
@ShaohuiQian it looks like you have everything from project to other resources in one repo. This makes hard to isolate the problem. Since you can't repro the issue, I would think this could be something at the terraform core level. Do you want to file an issue at terraform core instead? Closing this now. You may reopen if you can repro it on individual resources.
