### ISSUE TITLE
Cycle when creating BigQuery Omni Connection 

### ISSUE THREAD

**Issue by voycey** [hashicorp/terraform-provider-google#12018]
It seems like there is a bug / error in how `google_bigquery_connection` needs to be setup. Currently the documentation on the Google Cloud website states that `gcloud` must be used to set this up (as there is a cyclical dependency), however there needs to be the ability to have this setup in Terraform 100% (as our deployments are touch free).

Specifically I can't see a way to define the connection role and the `google_bigquery_connection` without creating a cycle as it requires an IAM role and that IAM role requires the identity from `google_bigquery_connection`:

### Terraform Version

Terraform v1.1.9
on linux_amd64

### Affected Resource(s)

google_bigquery_connection
aws_iam_role

### Terraform Configuration Files

```tf
resource "google_bigquery_connection" "connection" {
    provider      = google-beta
    connection_id = "bq-connection"
    location      = "aws-ap-southeast-1"
    friendly_name = "👋"
    description   = "BQ Omni Connection"
    aws {
      access_role {
         iam_role_id =  aws_iam_role.bigquery-omni-connection-role.arn
      }
    }
}

resource "aws_iam_role" "bigquery-omni-connection-role" {
    name                 = "bigquery-omni-connection"
    max_session_duration = 43200

    assume_role_policy = <<-EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "accounts.google.com"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              "accounts.google.com:sub": ${google_bigquery_connection.connection.id}
            }
          }
        }
      ]
    }
    EOF
}
```

### Expected Behavior

Some ability to set up the STS role without creating a cycle or to create the IAM role without requiring the output of the STS role.

### Actual Behavior

Cycle

### References
https://github.com/hashicorp/terraform-provider-google/issues/11459#issuecomment-1170731315

**Comment by edwardmedia** [comment]
@voycey It seems there is no perfect solution. [aws](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection#aws) is optional. Is it possible you can deploy twice?

**Comment by voycey** [comment]
I think I can do it by creating proxy roles and applying them in multiple steps but its not a clean solution.

I will test it and then post it. The AWS is required here to be able to set the policy to allow BigQuery to access S3

**Comment by voycey** [comment]
I understand - but unfortunately we need to have it in a single apply as we deploy multiple environments off the same code, I will have a crack with the multiple policy attachments tomorrow and report back!

**Comment by edwardmedia** [comment]
@voycey from the provider's perspective, I can't think of any perfect solution.

**Comment by edwardmedia** [comment]
@voycey any update?

**Comment by voycey** [comment]
The only update is workarounds that need to be done to solve this temporarily - I stand by this being a bug that needs to be addressed.

I have got it applying with the following but haven't tested the connectivity yet

```hcl
resource "aws_iam_policy" "bigquery-omni-s3-policy" {
    name = "bigquery-omni-connection-policy"

    policy = <<-EOF
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "BucketLevelAccess",
              "Effect": "Allow",
              "Action": ["s3:ListBucket"],
              "Resource": ["arn:aws:s3:::${var.meter_bucket_name}"]
          },
          {
              "Sid": "ObjectLevelAccess",
              "Effect": "Allow",
              "Action": ["s3:GetObject"],
              "Resource": ["arn:aws:s3:::${var.meter_bucket_name}"]
          }
      ]
    }
    EOF
}

resource "aws_iam_policy" "bigquery-omni-connection-policy" {
  name        = "bq-omni-policy"
  path        = "/"
  description = "BQ Omni Policy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow",
        Action = "sts:AssumeRoleWithWebIdentity",
        Resource = "*",
        Condition = {
          StringEquals = {
            "accounts.google.com:sub" = "${google_bigquery_connection.connection.id}"
          }
        }
      }
    ]
  })
}


resource "aws_iam_role" "bigquery-omni-connection-role" {
  name = "bigquery-omni-connection"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Federated = "accounts.google.com"
        }
      },
    ]
  })
}


resource "aws_iam_role_policy_attachment" "bigquery-omni-s3-role-attach" {
  role       = aws_iam_role.bigquery-omni-connection-role.name
  policy_arn = aws_iam_policy.bigquery-omni-s3-policy.arn
}

resource "aws_iam_role_policy_attachment" "bigquery-omni-connection-role-attach" {
  role       = aws_iam_role.bigquery-omni-connection-role.name
  policy_arn = aws_iam_policy.bigquery-omni-connection-policy.arn
}

output "bigquery_omni_role" {
  value = aws_iam_role.bigquery-omni-connection-role.arn
}
```
