### ISSUE TITLE
google_document_ai_processor resource fails when setting the "eu" location.

### ISSUE THREAD

**Issue by moiseslodeiroedosoft** [hashicorp/terraform-provider-google#12015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.27.0
+ provider registry.terraform.io/hashicorp/random v3.3.2

### Affected Resource(s)

* google_document_ai_processor

### Terraform Configuration Files

Failing configuration

```tf
locals {
  name_suffix = "${random_pet.suffix.id}"
}

resource "random_pet" "suffix" {
  length = 2
}

provider "google" {
  region = "europe-west2"
  zone   = "europe-west2-a"
}

resource "google_document_ai_processor" "processor" {
  location = "eu"
  display_name = "test-processor-${local.name_suffix}"
  type = "OCR_PROCESSOR"
}
```

Working configuration (just chancing region and location)

```tf
locals {
  name_suffix = "${random_pet.suffix.id}"
}

resource "random_pet" "suffix" {
  length = 2
}

provider "google" {
  region = "us-central1"
  zone   = "us-central1-c"
}

resource "google_document_ai_processor" "processor" {
  location = "us"
  display_name = "test-processor-${local.name_suffix}"
  type = "OCR_PROCESSOR"
}
```

### Debug Output

[Gist error google_document_ai_processor](https://gist.github.com/moiseslodeiroedosoft/e4a5ded00366171efec7b72fbf8ed4fa)

### Expected Behavior

It should have created a resource of type google_document_ai_processor in the europe region (cannot change endpoint for european one https://cloud.google.com/document-ai/docs/reference/rest#service-endpoint)

### Actual Behavior

Throws the following error

`Error: Error creating Processor: googleapi: Error 400: Request contains an invalid argument.`

### Steps to Reproduce

1. Log into gcloud with gcloud auth application-default login (or modify the script to accept credentials)
2. `terraform plan`
3. `terraform apply`

### Important Factoids

1. The error is displayed when authenticated with a service account and also with terminal login.
2. There is no possibility to change the hostname according to Google DocumentAI for Europe (https://cloud.google.com/document-ai/docs/reference/rest#service-endpoint) 
`

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/10684
