### ISSUE TITLE
google_cloudfunctions2_function - support event_filters

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#12021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The rest api has the ability to supply `event_filters` for things like gcs_bucket triggers on cloudfunctions_2 - [rest-api-link](https://cloud.google.com/functions/docs/reference/rest/v2beta/projects.locations.functions#EventFilter), without this I cannot specify the bucket name to trigger my cloud function. 

### New or Affected Resource(s)

* google_cloudfunctions2_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions2_function" "terraform-test" {
  provider = google-beta
  name = "test-function"
  location = "us-central1"
  description = "a new function"

  build_config {
    runtime = "nodejs16"
    entry_point = "helloHttp"
    environment_variables = {
        BUILD_CONFIG_TEST = "build_test"
    }
    source {
      storage_source {
        bucket = google_storage_bucket.bucket.name
        object = google_storage_bucket_object.object.name
      }
    }
  }

  service_config {
    max_instance_count  = 3
    min_instance_count = 1
    available_memory    = "256M"
    timeout_seconds     = 60
    environment_variables = {
        SERVICE_CONFIG_TEST = "config_test"
    }
    ingress_settings = "ALLOW_INTERNAL_ONLY"
    all_traffic_on_latest_revision = true
    service_account_email = google_service_account.account.email
  }

  event_trigger {
    trigger_region = "us-central1"
    event_type = "google.cloud.storage.object.v1.finalized"
    retry_policy = "RETRY_POLICY_RETRY"
    service_account_email = google_service_account.account.email
    event_filter {
         attribute = "bucket"
         value = "my-bucket-name"
    }
  }
}
```

### References

* #0000

**Comment by SarahFrench** [comment]
I've been working on implementing this - going to open a PR soon
