### ISSUE TITLE
Terraform waits for the end of the OS Policy rollout to finish

### ISSUE THREAD

**Issue by cedriccheron** [hashicorp/terraform-provider-google#12025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.11

### Affected Resource(s)

* google_os_config_os_policy_assignment

### Terraform Configuration Files

```tf
resource "google_os_config_os_policy_assignment" "os_policies_dynatrace" {
  count = length(var.os_policies_zones)
  timeouts {
    create = "2h"
    update = "2h"
    delete = "2h"
  }


  project = google_project.main.project_id

  description = "Policy that enforces all needed tools for infra management"

  depends_on = [google_project_service.main]

  instance_filter {
    all = false

    inventories {
      os_short_name = "centos"
      os_version    = "7*"
    }

    inventories {
      os_short_name = "rocky"
      os_version    = "8.*"
    }

    exclusion_labels {
      labels = {
        disable_os_config_dynatrace = "true"
      }
    }

  }

  location = var.os_policies_zones[count.index]
  name     = "linux-gcp-infra-assignment-dynatrace"

  os_policies {
    id                            = "dynatrace-always-up-policy"
    mode                          = "ENFORCEMENT"
    allow_no_resource_group_match = false
    description                   = "A test os policy"

    resource_groups {
      inventory_filters {
        os_short_name = "rocky"
        os_version    = "8.*"
      }
      inventory_filters {
        os_short_name = "centos"
        os_version    = "7*"
      }

      resources {
        id = "install-curl-pkg"

        pkg {
          desired_state = "INSTALLED"

          yum {
            name = "curl"
          }
        }
      }

      resources {
        id = "ensure-dynatrace-is-up"

        exec {
          validate {
            interpreter = "SHELL"
            script      = "if systemctl is-active --quiet oneagent; then exit 100; else exit 101; fi"
          }

          enforce {
            interpreter = "SHELL"
            script      = "#gets and installs the dynatrace agent && exit 100"
          }
        }
      }
    }

  }

  rollout {
    disruption_budget {
      percent = 50
    }

    min_wait_duration = "3s"
  }
}
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

The terraform code should have updated the os policy configuration and stopped.

### Actual Behavior

The policy is updated, however, the pipeline continues as it it waiting for the end of the rollout.
With 10 VM tergeted by the OS Config, the rollout takes more than 1 hour, which is unusable in a CI/CD pipeline

### Steps to Reproduce

Prerequisite: Have a dozen of VMs in the targeted project

1. `terraform apply`
2. Update the policy (update the name for example) to force a new rollout
3. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@cedriccheron do you have log that can be shared? How to trigger your next step in your pipeline? I noticed that you set the timeout to 2h. Why?

**Comment by cedriccheron** [comment]
I forgot to add.
A side effect of this issue is that the OS Policy config is not saved in the tfstate, which means the following pipelines fail unless we remove manually the policies

**Comment by mldmld68** [comment]
Cedric is off today and tomorrow.
So I may explain : Terraform wait the policy on many GCE beeing removed and the new one being applied. And it take a while if the GCP project contains many GCE.
For us, Terraform should only change the policy, and then leave without waiting the apply of the new OS Policy.

Without changing the timeout of the resource, one get : 

google_os_config_os_policy_assignment.os_policies_remove_old_config[0]: Still destroying... [id=projects/xxxxxxxx/locati...s/gcp-infra-assignment-remove-old-conf, 19m40s elapsed]
google_os_config_os_policy_assignment.os_policies_repositories[0]: Still destroying... [id=projects/xxxx/locati...ents/gcp-infra-assignment-repositories, 19m40s elapsed]
google_os_config_os_policy_assignment.os_policies_xxx[0]: Still destroying... [id=projects/xxxx/locati...ssignments/gcp-infra-assignment-qualys, 19m41s elapsed]
google_os_config_os_policy_assignment.os_policies_remove_old_config[0]: Still destroying... [id=projects/xxxx/locati...s/gcp-infra-assignment-remove-old-conf, 19m50s elapsed]
google_os_config_os_policy_assignment.os_policies_certificates[0]: Still destroying... [id=projects/xxxx/locati...ents/gcp-infra-assignment-certificates, 19m50s elapsed]
google_os_config_os_policy_assignment.os_policies_repositories[0]: Still destroying... [id=projects/xxxx/locati...ents/gcp-infra-assignment-repositories, 19m50s elapsed]
google_os_config_os_policy_assignment.os_policies_xxx[0]: Still destroying... [id=projects/xxxx/locati...ssignments/gcp-infra-assignment-qualys, 19m51s elapsed]
╷
│ Error: Error deleting OSPolicyAssignment: operation not done.
│ 
│ 
╵
╷
│ Error: Error deleting OSPolicyAssignment: operation not done.
│ 
│ 
╵
╷
│ Error: Error deleting OSPolicyAssignment: operation not done.
│ 
│ 
╵
╷
│ Error: Error deleting OSPolicyAssignment: operation not done.
│ 
│ 
╵
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1

**Comment by edwardmedia** [comment]
Closing as this issue goes to OS Policy team
b/238658842
