### ISSUE TITLE
Dialogflow CX - Cycle Issue

### ISSUE THREAD

**Issue by DIONNiklas** [hashicorp/terraform-provider-google#12022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.27.0

### Affected Resource(s)

* google_dialogflow_cx_agent
* google_dialogflow_cx_flow
* google_dialogflow_cx_page

### Terraform Configuration Files

```tf
resource "random_pet" "test" {}

resource "google_dialogflow_cx_agent" "test" {
  default_language_code = "de"
  display_name          = "Bot-${random_pet.test.id}"
  location              = "global"
  time_zone             = "Europe/Berlin"
  supported_language_codes = ["en"]
}

resource "google_dialogflow_cx_flow" "startFlow" {
  parent = google_dialogflow_cx_agent.test.id
  display_name = "Start"

  transition_routes {
    intent = "${google_dialogflow_cx_agent.crewBot.id}/intents/00000000-0000-0000-0000-000000000000"
    target_page = google_dialogflow_cx_page.test.id
  }
}

resource "google_dialogflow_cx_page" "test" {
  parent = google_dialogflow_cx_flow.startFlow.id
  display_name = "Test"
}
```

### Debug Output

Cycle issue because google_dialogflow_cx_page is using as parent the flow resource and the flow resource should add a transition_routes to the page.

### Expected Behavior

How did you solve this problem? Unfortunately, there is no possibility to add a transition route to the flow resource afterwards. So you have to add a route to the flow resource as soon as you define it.

For me it seems as if the service cannot be completely mapped using Terraform.

**Comment by edwardmedia** [comment]
@DIONNiklas I see what you mean. This is not something the provider can solve. Both [parent](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_page#parent) and [target_page](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_flow#target_page) are optional. Have you tried omitting one, ie, not provide target_page? Does it break the process?

**Comment by DIONNiklas** [comment]
Both attributes are optional you are right. But otherwise the link between flow and page resource cannot be set up. Further more its not possible to create the link by string interpolation because I don't have any chance to create the id manually (or by a function which is controlled by myself)

**Comment by edwardmedia** [comment]
@ScottSuarez what do you think about this?

**Comment by ScottSuarez** [comment]
I'm not sure there is anything we can do here. Best bet would be to file a bug with the api team. This seems like an issue they can look into.

For a work around could you create the config with a transition route empty then fill in the transition route with the provisioned page manually within an update? Thats the only way I could see this working.

**Comment by edwardmedia** [comment]
@DIONNiklas closing this as there is not something that can be done at the provider level. You may file an issue as @ScottSuarez  provided above

**Comment by PerEkskogSEB** [comment]
I stumbled on the exact same issue just a few days ago and have discussed it with Google support and reached to the same workaround (which kind of defeats the purpose of using Terraform for us).

When I first looked into using Terraform with Dialogflow it seemed odd that the transition_routes go into the flow resource. When I design an agent in the Dialogflow GUI the transition_routes are actually in a "default start page". Now if this "default start page" could be exposed as a page resource in the flow, then the transition_routes would go into this page and this issue would not occur.

But perhaps the GUI does not show how an agent is really implemented so the idea is not possible to implement?

**Comment by DIONNiklas** [comment]
Thank you for the responses. Unfortunately, there is a hen egg problem here. Thus, Terraform is unfortunately unusable in this area. Which is a great pity. The solution for this problem would be an additional resource that can subsequently adjust the transition routes within the flow. As you can do it for example with the settings of the S3 Service on the AWS terraform provider.

**Comment by ScottSuarez** [comment]
Could you file a request for a new resource. Perhaps we can breakout this field to be used as a new fine-grained resource which will exclusively manage this field.

**Comment by ScottSuarez** [comment]
Thats another alternative. If you push for this perhaps through support or a pr it could be prioritized. unfortunately our team is quite overloaded as is

**Comment by PerEkskogSEB** [comment]
Google support came to the conclusion that from an API perspective you actually can create the flow, then the page, and then update the "default page part" of the flow.

Now my thinking is, perhaps it could be as simple (!) as introducing a "magic name" for the default page (that is automatically created) and when Terraform sees this it will instead update the flow as if it was a new page.
