### ISSUE TITLE
google_sql_user not able to create for myssql

### ISSUE THREAD

**Issue by hanumantharao19** [hashicorp/terraform-provider-google#12049]
module.mssql.google_sql_user.additional_users["qa"]: Still creating... [10s elapsed]
╷
│ Error: Error setting disabled: Invalid address to set: []string{"disabled"}
│ 
│   with module.mssql.google_sql_user.additional_users["prod"],
│   on ../modules/mssql/main.tf line 167, in resource "google_sql_user" "additional_users":
│  167: resource "google_sql_user" "additional_users" {
│ 
╵
╷
│ Error: Error setting disabled: Invalid address to set: []string{"disabled"}
│ 
│   with module.mssql.google_sql_user.additional_users["dev"],
│   on ../modules/mssql/main.tf line 167, in resource "google_sql_user" "additional_users":
│  167: resource "google_sql_user" "additional_users" {
│ 
╵
╷
│ Error: Error setting disabled: Invalid address to set: []string{"disabled"}
│ 
│   with module.mssql.google_sql_user.additional_users["qa"],
│   on ../modules/mssql/main.tf line 167, in resource "google_sql_user" "additional_users":
│  167: resource "google_sql_user" "additional_users" {
│ 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@hanumantharao19 can you share your config and the full debug log?

**Comment by srs2210** [comment]
I was able to replicate this issue as well and this error occurs when deploying the `google_sql_user` resource.

I believe the issue originates from the [PR# 11834](https://github.com/hashicorp/terraform-provider-google/pull/11834) where modifications were made to `google_sql_user` resource in provider version [v4.25.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.25.0). Because using google provider >= 4.25.0 throws this error (I have tested this).

Using google provider version 4.24.0 resolves the issue so this is a temporary workaround.

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/11891

**Comment by edwardmedia** [comment]
closing this as a dup #11891
