### ISSUE TITLE
Support "conflicts:" for nested fields in mmv1 generated resources

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

Currently, supplying `conflicts` on a field nested inside another field causes an error like:

```
RuntimeError: automated_backup_policy.quantity_based_retention does not exist
```

It looks like this because the logic in `check_conflicts` only checks whether the values for `conflicts` are in the top-level fields of the resource, and does not include nested fields. https://github.com/GoogleCloudPlatform/magic-modules/blob/64026ff546d9d3b2bd05f280df42dac6ee390792/mmv1/api/type.rb#L212

I ran into this while reviewing https://github.com/GoogleCloudPlatform/magic-modules/pull/6208

**Comment by rileykarson** [comment]
@megan07 to take a look at the difficulty here

**Comment by rileykarson** [comment]
(this may be an MMv1 issue, but may also be an SDK issue)
