### ISSUE TITLE
google_cloudfunctions2_function event_trigger service_account_email not set

### ISSUE THREAD

**Issue by pawelczuczwara** [hashicorp/terraform-provider-google#12055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When setting the service_account_email for the event_trigger 
Cloud Function gen2 is created with defalut comptute Eventarc trigger service account.

### New or Affected Resource(s)

    google_cloudfunctions2_function 
        event_trigger 
             service_account_email 

### Potential Terraform Configuration

Default documented resource configuration, that is not working:

      resource "google_cloudfunctions2_function" "terraform-test" {
        provider = google-beta
        name = "test-function"
        location = "us-central1"
        description = "a new function"
      
        build_config {
          runtime = "nodejs16"
          entry_point = "helloHttp"
          environment_variables = {
              BUILD_CONFIG_TEST = "build_test"
          }
          source {
            storage_source {
              bucket = google_storage_bucket.bucket.name
              object = google_storage_bucket_object.object.name
            }
          }
        }
      
        service_config {
               ...
               ...
        }
      
        event_trigger {
          trigger_region = "us-central1"
          event_type = "google.cloud.pubsub.topic.v1.messagePublished"
          pubsub_topic = google_pubsub_topic.sub.id
          retry_policy = "RETRY_POLICY_RETRY"
          service_account_email = google_service_account.account.email
        }
      }

### References

[previous issue with the service_config service_account_email](https://github.com/hashicorp/terraform-provider-google/issues/11388)

**Comment by drandell** [comment]
are you using the beta provider version 4.25 or greater? https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.25.0

**Comment by pawelczuczwara** [comment]
I´m using the:
  provider "registry.terraform.io/hashicorp/google-beta" {
    version     = "4.27.0"
