### ISSUE TITLE
Magic Modules: Eliminate custom_import requirement for resources with parent fields

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

For subresources, the preferred way of setting them up in magic modules is to use a parent ID field. This means setting a few specific fields, including a custom import. One of the main reasons a custom import is required is that the default import code does not allow parts of the import path to contain a `/` character - but a parent field contains a full id, which will always contain at least one `/`.

Examples:

- healthcare.FhirStore
  - [api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/healthcare/api.yaml#L179)
  - [terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/healthcare/terraform.yaml#L42)
- dialogflowcx.Intent
  - [api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/dialogflowcx/api.yaml#L115)
  - [terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/dialogflowcx/terraform.yaml#L36)
- kms.CryptoKey
  - [api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/kms/api.yaml#L66)
  - [terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/553b379be5dc738b9da86a859134dfcab3a5fba5/mmv1/products/kms/terraform.yaml#L45)

This is unintuitive and makes it harder to set up parent fields properly, especially for new contributors.

**Comment by rileykarson** [comment]
Personal opinion, not necessarily team one: generally, fields called `"parent"` containing multiple templated values should be avoided and the component parts used to shape the URL instead.

**Comment by NickElliot** [comment]
The current functionality (that is not documented outside of the .rb code generator) of using a `%` in a {{token}} field in `import_format` covers tested parent field resources, and can be assumed to work for most standard cases. A wider reaching change that explores wider-reaching regex generation changes could be explored for a future major release, but this issue's primary usage case requires no further update.
