### ISSUE TITLE
Cloudscheduler job fails to create successfully

### ISSUE THREAD

**Issue by Vermyndax** [hashicorp/terraform-provider-google#12069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Tested on 1.1.9 and 1.2.4

### Affected Resource(s)

* google_cloud_scheduler_job

### Terraform Configuration Files

```
terraform {
  required_version = ">= 1.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.27"
    }
  }
}
```

### Debug Output

```
│ Error: Error creating Job: googleapi: Error 403: The principal (user or service account) lacks IAM permission "cloudscheduler.jobs.create" for the resource "projects/72154013424/locations/us-central1" (or the resource may not exist).
│
│   with google_cloud_scheduler_job.salesforce_case_monitor_job,
│   on schedulers.tf line 1, in resource "google_cloud_scheduler_job" "salesforce_case_monitor_job":
│    1: resource "google_cloud_scheduler_job" "salesforce_case_monitor_job" {
```

### Expected Behavior

Cloud scheduler job should be created successfully. Verified that the terraform service account and the oauth account we're trying to use have the proper cloudscheduler.jobs.create permission.

### Actual Behavior

The above error occurred.

### Steps to Reproduce

1. Created the resource code as such:
```
resource "google_cloud_scheduler_job" "salesforce_case_monitor_job" {
  name             = "salesforce-case_monitor-job"
  description      = "Job to monitor Salesforces Cases, once daily"
  schedule         = "0 4 * * *"
  time_zone        = "America/New_York"
  attempt_deadline = "320s"

  http_target {
    http_method = "POST"
    uri         = "<url of workflow we're trying to execute>"

    oauth_token {
      service_account_email = "<email address of service account>"
    }
  }
}
```
2. Ran terraform apply thru GitHub Actions and also manually.

### Important Factoids

It seems like there is some kind of problem with resolving the project ID. The project ID is using the friendly name in the console, but the provider seems to use the numbered ID. Just a guess, but it seems like something is broken there.

### References

# * #0000

**Comment by edwardmedia** [comment]
@Vermyndax can you run the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job)? Which project is `72154013424`? Can you also try adding the `project` in the config instead of leaving it using default?

**Comment by Vermyndax** [comment]
Hi @edwardmedia - I tried running the oauth example from the page and it does not work either. It produces the same error.

The project 72... is the numbered project ID of the google project (should have left that out of the paste, honestly). I've found that some GCP modules use the friendly name of the GCP project and some others use the numbered project name. It seems that this module auto-resolves to the numbered project ID for whatever reason.

**Comment by edwardmedia** [comment]
@Vermyndax do you use module or directly call execute the resource mentioned in the [here](https://github.com/hashicorp/terraform-provider-google/issues/12069#issue-1299807263)?

**Comment by Vermyndax** [comment]
It was a direct resource execution, no module.

**Comment by edwardmedia** [comment]
@Vermyndax I don't see the code in the resource that uses the pattern. The issue seems to be clear. 
1) how do you verify the Terraform runner account has the right permissions. To test, can you use an account of the project owner to run?
2) I guess you have enabled these two services `Cloud Run Admin API` and `Cloud Scheduler API`. But double check
3) Is `72154013424` is right project you are working on?
4) You can share the full debug log so I can take a close look

```
The principal (user or service account) lacks IAM permission "cloudscheduler.jobs.create" for the resource "projects/72154013424/locations/us-central1" (or the resource may not exist).
```

**Comment by Vermyndax** [comment]
Hey @edwardmedia ...

1. The Terraform runner and service account does have owner permissions. I am using the same repo/account to deploy other resources from the same repository. Currently, this is the only resource that is failing.
2. Verified that Cloud Run and Cloud Scheduler APIs are enabled. I had also hand-created a version of this resource in Cloud Scheduler and it worked fine as well. We are deploying to Cloud Run as well, and it works fine.
3. Yes, that is the correct project. That is the numbered project ID. As I said before, one thing that is strange to me is that the URL in the console refers to the friendly name of the project and not the numbered version, but the error refers to the numbered version.
4. ok

**Comment by Vermyndax** [comment]
@edwardmedia I figured out the issue. The issue is that this resource cannot talk to the API with the project number, it requires the friendly project_id instead. Other resources in the provider resolve to the proper project fine, but this one does not. Changing to the friendly named project_id resolved the issue.

I still think this is a bug since other resources handle this fine, but it may be a bug in the GCP API and not the provider... and is certainly a low priority.

**Comment by edwardmedia** [comment]
@Vermyndax I can't repro the issue. Mind post your debug log so I can take a closer look? What version of the provider are you using? (you have given the Terraform version)
