### ISSUE TITLE
google_container_cluster is recreated on each apply when default nodepool has node_config block

### ISSUE THREAD

**Issue by volodymyr-stoiko** [hashicorp/terraform-provider-google#12070]
Following the issue https://github.com/hashicorp/terraform-provider-google/issues/2115

In the original issue it was said, that to prevent terraform from recreating cluster we have to skip using `node_config` block in the cluster and use it only in node pool.

In our setup, we have default service accounts prohibited in projects. That means we must use `node_config` at least because we have to specify the service account for nodes, e.g.

```
  node_config {
    service_account = google_service_account.gke_account.email
}
```

So even if we delete default node pool after it is created, we must have `node_config` block both in `google_container_cluster` and in `google_container_node_pool` resources otherwise cluster will not get into a healthy state. But then with `node_config` in `google_container_cluster`, we  run into this issue where terraform constantly recreates cluster.

**Comment by edwardmedia** [comment]
@volodymyr-stoiko can you share your config?

**Comment by edwardmedia** [comment]
@volodymyr-stoiko as https://github.com/hashicorp/terraform-provider-google/issues/2115. stated, it is not recommended to set `node_config` in both cluster and node_pool. The limitation is not at the terraform provider.

**Comment by volodymyr-stoiko** [comment]
It makes sense, but in the current case, it doesn't help as there is no way for us to not specify node_config in the default node pool because we must set the service account. And without it, the cluster won't start because we don't have default service accounts enabled in projects.

**Comment by volodymyr-stoiko** [comment]
@edwardmedia I'll try to explain this in more detail.

At organization level our company has a policy **Domain restricted sharing** with a constraint **constraints/iam.allowedPolicyMemberDomains** configured to accept only specific list of customer IDs. Google is not among those customer IDs. This requirement results in service accounts being disabled in any project we have in organization (e.g. default SAs like `235562352356-compute@developer.gserviceaccount.com ` can't be used).

Now we move to cluster creation. 

The resource `google_container_cluster` includes not only cluster but also default node pool (I understand it is on GKE side, not terraform decision). And in this [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended) you've mentioned, this default node pool is created with default(!) project service account. As I wrote, in our projects this account is disabled. 

So when we apply terraform with `google_container_cluster` resource, cluster in GKE would be provisioned with 83% progress and then fail on health check. And the reason for that is that node from default node pool will never be able to connect to GKE control-plane as it uses **disabled** default service account. So to make it working, we must add `node_config` block into `google_container_cluster` resource o configure using the different service account. 

With `node_config` block in `google_container_cluster` resource we are able then to run the cluster with the default node pool. Only after cluster is ready, `remove_default_node_pool = true` configuration triggers default node pool removal and now we want to create separate managed node pool with `google_container_node_pool`. This also requires `node_config` with service account configured as default service account is disabled.

And that's how we get to the point where we need `node_config` both in `google_container_cluster` and in `google_container_node_pool` resources

**Comment by edwardmedia** [comment]
@volodymyr-stoiko I am not sure if you can 100% avoid the accounts like ` gserviceaccount.com`. Below is the doc that you may want to review.
https://cloud.google.com/iam/docs/service-accounts#google-managed

The issue you are facing in creating gke clusters seems to be the reason. If you are using other services, could see more. Here is the list of Google managed service agents. 

https://cloud.google.com/iam/docs/service-agents

```
At organization level our company has a policy Domain restricted sharing with a constraint constraints/iam.allowedPolicyMemberDomains configured to accept only specific list of customer IDs. Google is not among those customer IDs. This requirement results in service accounts being disabled in any project we have in organization (e.g. default SAs like 235562352356-compute@developer.gserviceaccount.com can't be used).
```

**Comment by volodymyr-stoiko** [comment]
> @volodymyr-stoiko I am not sure if you can 100% avoid the accounts like gserviceaccount.com

**Comment by edwardmedia** [comment]
Closed per suggestion
