### ISSUE TITLE
Make 'region' Argument Optional in Dataflow Configuration

### ISSUE THREAD

**Issue by fribeiro1** [hashicorp/terraform-provider-google#12081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.4
on linux_amd64

+ provider registry.terraform.io/hashicorp/google v4.24.0

### Affected Resource(s)

* google_dataflow_job

### Terraform Configuration Files

```tf
resource "google_dataflow_job" "samplejob" {
  name = "samplejob"
  template_gcs_path = "gs://dataflow-templates-us-central1/latest/Word_Count"
  temp_gcs_location = "gs://samplebucket-123/temp"
  parameters = {
    inputFile = "gs://samplebucket-123/sampleobject"
    output = "gs://samplebucket-123/counts"
  }
}
```

### Debug Output

https://gist.github.com/fribeiro1/195629409cb26f51c133d34f67e66584

### Panic Output

N/A.

### Expected Behavior

The job is created.

### Actual Behavior

The provider requires the optional 'region' argument to create the job.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A.

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job#region

**Comment by fribeiro1** [comment]
@edwardmedia Thanks for your quick reply. "region" is optional in the API and should also be optional in the provider.

**Comment by edwardmedia** [comment]
@fribeiro1 could you share the api doc that shows the region is optional?

**Comment by fribeiro1** [comment]
@edwardmedia The default behavior when you don't provide a location is described at https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/create.

For example, the CLI, Java, and Python client libraries already implement it. I published samples at https://simplesassim.wordpress.com/2022/07/12/how-to-create-a-job-in-google-dataflow/.

**Comment by edwardmedia** [comment]
@fribeiro1 don't you need to provide {location} in the below endpoint?

POST https://dataflow.googleapis.com/v1b3/projects/{projectId}/locations/{location}/jobs

https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/create

Is this what you referred to when {location} is not provided? It is pretty clear not recommended. 

```
Using projects.jobs.create is not recommended, as your job will always start in us-central1.
```

**Comment by fribeiro1** [comment]
@edwardmedia No, you don't. I know it is odd. Still, I think the provider should align with the other tools.

**Comment by fribeiro1** [comment]
@edwardmedia I'm afraid I have to disagree with your evaluation, but I appreciate your attention to the issue. Regards.
