### ISSUE TITLE
Add Support for Importing Dataflow Jobs

### ISSUE THREAD

**Issue by fribeiro1** [hashicorp/terraform-provider-google#12088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to import jobs into the local state.

### New or Affected Resource(s)

* google_dataflow_job

### Potential Terraform Configuration

N/A.

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job#import

**Comment by sanghaniJ** [comment]
b/263840132

**Comment by sanghaniJ** [comment]
I've gone through this issue, and it seems like support for importing Dataflow Jobs has been provided in this [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6386) and is now merged. Hence, closing this issue ticket.
