### ISSUE TITLE
Support Spot Termination Action

### ISSUE THREAD

**Issue by andrewyz** [hashicorp/terraform-provider-google#12089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCE has a SPOT VM  that helps customer gain low price compute resources. There is a new field called instance-termination-action which decides the action GCE should take when VM is preempted. This field is enabled in GA and we need Terraform support on this.

### New or Affected Resource(s)

google_compute_instance
### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_instance" "foobar" {
  scheduling {
   provisioning_model = "SPOT"
   ...
   instance_termination_action = "STOP"
  }
}
```

### References

* https://cloud.google.com/compute/docs/instances/spot

**Comment by rileykarson** [comment]
This seems to be closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6272
