### ISSUE TITLE
Implement data source for Cloud Logging Sinks

### ISSUE THREAD

**Issue by mksh** [hashicorp/terraform-provider-google#12083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The provider includes resources for [Logging Sinks](https://cloud.google.com/logging/docs/export/configure_export_v2), but data sources that allow to reference sinks or their identities are missing.

### New or Affected Resource(s)

* data google_logging_project_sink
* data google_logging_folder_sink

### Potential Terraform Configuration

```tf
data "google_logging_project_sink" "example" {
   name = "spam"
   project = "eggs"
}

resource "google_storage_bucket_iam_binding" "example" {
  role    = "storage.objectCreator"
  members = [
     data.google_logging_project_sink.example.writer_identity
  ]
  bucket  = "sausage"
}
```

### References

- https://cloud.google.com/logging/docs/export/configure_export_v2
- https://cloud.google.com/logging/docs/export/using_exported_logs

**Comment by roaks3** [comment]
It looks like this was fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7250
