### ISSUE TITLE
google_certificate_manager_certificate: self_managed GCP API fields

### ISSUE THREAD

**Issue by alekssaul** [hashicorp/terraform-provider-google#12091]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.5 on darwin_arm64

### Affected Resource(s)
google_certificate_manager_certificate

### Terraform Configuration Files

```tf
resource "google_certificate_manager_certificate" "media_cdn" {
  name        = replace(var.domain_name, ".", "_")
  description = "The default cert"
  scope       = "EDGE_CACHE"
  self_managed {
    certificate_pem = file("${path.module}/assets/mediacdn_public.pem")
    private_key_pem = file("${path.module}/assets/mediacdn_privkey.pem")
  }
}
```

### Debug Output
```
2022-07-14T09:26:16.894-0400 [INFO]  provider.terraform-provider-google_v4.28.0_x5: 2022/07/14 09:26:16 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /v1/projects/ce-alekssaul-340117/locations/global/certificates?alt=json&certificateId=testcme_alekssaul_com HTTP/1.1
Host: certificatemanager.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/dev
Content-Length: 7541
Content-Type: application/json
Accept-Encoding: gzip

{
 "description": "The default cert",
 "scope": "EDGE_CACHE",
 "selfManaged": {
  "certificatePem": "<REDACTED>",
  "privateKeyPem": "<REDACTED>"
 }
}

-----------------------------------------------------: timestamp=2022-07-14T09:26:16.893-0400
2022-07-14T09:26:17.139-0400 [INFO]  provider.terraform-provider-google_v4.28.0_x5: 2022/07/14 09:26:17 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Thu, 14 Jul 2022 13:26:17 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"certificatePem\" at 'certificate.self_managed': Cannot find field.\nInvalid JSON payload received. Unknown name \"privateKeyPem\" at 'certificate.self_managed': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "certificate.self_managed",
            "description": "Invalid JSON payload received. Unknown name \"certificatePem\" at 'certificate.self_managed': Cannot find field."
          },
          {
            "field": "certificate.self_managed",
            "description": "Invalid JSON payload received. Unknown name \"privateKeyPem\" at 'certificate.self_managed': Cannot find field."
          }
        ]
      }
    ]
  }
}

```

### Expected Behavior

Terraform plugin to create a self managed cert

### Actual Behavior

Cert is not created and `terraform apply` errors out. Note that for an existing self-managed cerr in cert-manager `terraform import` also imports the cert with empty `certificate_pem` and `private_key_pem` fields

### Steps to Reproduce

1. `terraform apply`

### References

Presumably the issue is https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_certificate_manager_certificate.go#L463-L466 section transforms these fields into `certificatePem` and `privateKeyPem` for request body json. However GCP API expects `pemCertificate` and `private_key_pem` per documentation in; https://cloud.google.com/certificate-manager/docs/reference/rest/v1/projects.locations.certificates#SelfManagedCertificate

I can try to make the change, test, and PR if I can find time.

**Comment by roaks3** [comment]
It looks like this was fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6447
