### ISSUE TITLE
Documentation: google_storage_bucket_object t &  data.google_storage_bucket_object have missing arguments/attributes

### ISSUE THREAD

**Issue by martinOrigin8Cares** [hashicorp/terraform-provider-google#12090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version

Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.28.0

### Affected Resource(s)

- google_storage_bucket_object 
- data.google_storage_bucket_object

### Issue Description

The documenation (v4.28, latest at the moment of writing) doesn't include these arguements/attributes:

- event_based_hold
- detect_md5hash
- id
- temporary_hold

### Important Factoids

I compare the list from the documenation and the list from

- google_storage_bucket_object 
```
bucket
cache_control
content
content_disposition
content_encoding
content_language
content_type
crc32c
customer_encryption
detect_md5hash
event_based_hold
id
kms_key_name
md5hash
media_link
metadata
name
output_name
self_link
source
storage_class
temporary_hold
timeouts

generated with
terraform providers schema -json | jq -r '.provider_schemas."registry.terraform.io/hashicorp/google".resource_schemas.google_storage_bucket_object.block as $obj |  ($obj.attributes|keys) + ($obj.block_types|keys) | sort |.[]'
```

- data.google_storage_bucket_object  
```
bucket
cache_control
content
content_disposition
content_encoding
content_language
content_type
crc32c
customer_encryption
detect_md5hash
event_based_hold
id
kms_key_name
md5hash
media_link
metadata
name
output_name
self_link
source
storage_class
temporary_hold

generated with 

terraform providers schema -json | jq -r '.provider_schemas."registry.terraform.io/hashicorp/google".data_source_schemas.google_storage_bucket_object.block.attributes|keys |sort| .[]'
```

### References
Documeantion link:
https://registry.terraform.io/providers/hashicorp/google/4.28.0/docs/resources/storage_bucket_object
https://registry.terraform.io/providers/hashicorp/google/4.28.0/docs/data-sources/storage_bucket_object

This pull request seems to have no update on the documenation
https://github.com/hashicorp/terraform-provider-google/pull/9487

**Comment by melinath** [comment]
b/241975760
