### ISSUE TITLE
Add support for setting the Dataproc Metastore endpoint protocol

### ISSUE THREAD

**Issue by tsamaras** [hashicorp/terraform-provider-google#12106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The new gRPC endpoint for the Metastore service provides more security and more flexible connectivity for use cases like ours, where we have multiple Dataproc Clusters running in a number of different VPCs. Being able to configure it via Terraform would enable our migration away from a self hosted CloudSQL metastore database.  In order to leverage the gRPC endpoint the database and table level iam bindings would also need to be added.
https://cloud.google.com/dataproc-metastore/docs/endpoint-protocol 

### New or Affected Resource(s)

* google_dataproc_metastore_service
* google_dataproc_metastore_databases_iam
* google_dataproc_metastore_databases_tables_iam

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_dataproc_metastore_service" "default" {
  provider   = google-beta
  service_id = "metastore-srv"
  location   = "us-central1"
  port       = 9080
  tier       = "DEVELOPER"

  maintenance_window {
    hour_of_day = 2
    day_of_week = "SUNDAY"
  }

  hive_metastore_config {
    version = "2.3.6"
    endpoint_protocol = "GRPC"
  }
}

resource "google_dataproc_metastore_service_iam_member" "member" {
  provider = google-beta
  project = google_dataproc_metastore_service.default.project
  location = google_dataproc_metastore_service.default.location
  service_id = google_dataproc_metastore_service.default.service_id
  database_id = "default"
  role    = "roles/metastore.metadataViewer"
  member = "user:jane@example.com"
}
  

```

### References

* https://cloud.google.com/dataproc-metastore/docs/endpoint-protocol

**Comment by DrFaust92** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/6214 added support for endpoint_protocol to allow for GRPC endpoints

**Comment by c2thorn** [comment]
From what I can tell https://github.com/GoogleCloudPlatform/magic-modules/pull/6214 has done this and is scheduled to release soon. If there is more, please let us know specifically.
