### ISSUE TITLE
Add support for Auxiliary versions to google_dataproc_metastore_service

### ISSUE THREAD

**Issue by tsamaras** [hashicorp/terraform-provider-google#12108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Auxiliary versions allow a Dataproc Metastore service to support endpoints that use a different version of the hive protocol than the primary service endpoint. This enables, for example, a configuration where there are multiple Dataproc Clusters connected to the same metastore service but some are running Dataproc 2.0 while others are still using 1.5.

### New or Affected Resource(s)

* google_dataproc_metastore_service

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_dataproc_metastore_service" "default" {
  provider   = google-beta
  service_id = "metastore-srv"
  location   = "us-central1"
  port       = 9080
  tier       = "DEVELOPER"

  maintenance_window {
    hour_of_day = 2
    day_of_week = "SUNDAY"
  }

  hive_metastore_config {
    version = "3.1.6"
    auxiliary_versions = {
     "aux-service" = {
        version = "2.3.6"
      }
    }
  }
}
```

### References

* https://cloud.google.com/dataproc-metastore/docs/auxiliary-versions

**Comment by DrFaust92** [comment]
ill take a look at this
