### ISSUE TITLE
Cannot deploy google api gateway config with wildcards in endpoint path

### ISSUE THREAD

**Issue by marc-at-boum** [hashicorp/terraform-provider-google#12122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.19.0
+ provider registry.terraform.io/hashicorp/google-beta v4.20.0

### Affected Resource(s)

google_api_gateway_api_config

#### main.tf
```tf
locals {
  project = "boum-dev-marc-6"
  region = "europe-west1"
}

provider "google-beta" {
  alias           = "bug_report"
  project         = local.project
  region          = local.region
  request_timeout = "60s"
}

provider "google" {
  alias           = "bug_report"
  project         = local.project
  region          = local.region
  request_timeout = "60s"
}

resource "google_service_account" "bug_report" {
  project      = local.project
  account_id   = "bug-report-api"
  display_name = "bug report service account"
}


resource "google_api_gateway_api" "bug_report" {
  provider = google-beta
  project  = local.project
  api_id   = "bug-report"
}

resource "google_api_gateway_api_config" "bug_report" {
  provider             = google-beta
  project              = local.project
  api                  = google_api_gateway_api.bug_report.api_id
  api_config_id_prefix = "${google_api_gateway_api.bug_report.api_id}-"

  gateway_config {
    backend_config {
      google_service_account = google_service_account.bug_report.id
    }
  }terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.19.0"
    }
  }
}

locals {
  project = "boum-dev-marc-6"
}

provider "google" {
  alias           = "bug_report"
  project         = local.project
  region          = "europe-west1"
  request_timeout = "60s"
}

  openapi_documents {
    document {
      path     = "${google_api_gateway_api.bug_report.api_id}_openapi_spec.yaml"
      contents = filebase64("openapi.yaml")
    }
  }

  lifecycle {
    create_before_destroy = true
  }

}
``` 
#### openapi.yaml
```
{ "info":
    {
      "description": "Bug report api",
      "title": "Bug Report API",
      "version": "0.0.1"
    },
  "paths": {
    "/devices/{deviceId}": {
      "post": {
        "operationId": "test",
        "responses": {
          "201": {
            "description": "test",
            "schema": {
              "type": "string"
            }
          }
        },
        "summary": "test",
        "x-google-backend": {
          "address": "https://europe-west6-boum-dev-marc-6.cloudfunctions.net/device_management_register_device"
        }
      }
    }
  },
  "swagger": "2.0",
  "x-google-allow": "configured"
}
``` 

### Debug Output

https://gist.github.com/marc-at-boum/3f4a5fee2e542edb8f15fc72873efef6

### Panic Output

None

### Expected Behavior

Normal deployment of API config as it happens when the path in the openapi doesn't contain wildcards:
"/devices/{deviceId}" ->  "/devices"

### Actual Behavior

The following error is produced

 Error: Error creating ApiConfig: googleapi: Error 400: Cannot convert to service config.
│ 'location: "unknown location"
│ kind: ERROR
│ message: "http: undefined field \'deviceId\' on message \'google.protobuf.Empty\'."
│ 
│  location: "bug-report_openapi_spec.yaml: Operation \'post\' in path \'/devices/{deviceId}\'"
│ message: "Operation does not require an API key; callers may invoke the method without specifying an associated API-consuming project. To enable API key all the SecurityRequirement Objects (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-requirement-object) inside security definition must reference at least one SecurityDefinition of type : \'apiKey\'."
│ '
│ com.google.apps.framework.request.BadRequestException: Cannot convert to service config.
│ 'location: "unknown location"
│ kind: ERROR
│ message: "http: undefined field \'deviceId\' on message \'google.protobuf.Empty\'."
│ 
│  location: "bug-report_openapi_spec.yaml: Operation \'post\' in path \'/devices/{deviceId}\'"
│ message: "Operation does not require an API key; callers may invoke the method without specifying an associated API-consuming project. To enable API key all the SecurityRequirement Objects (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-requirement-object) inside security definition must reference at least one SecurityDefinition of type : \'apiKey\'."
│ '
│ 
│   with google_api_gateway_api_config.bug_report,
│   on main.tf line 34, in resource "google_api_gateway_api_config" "bug_report":
│   34: resource "google_api_gateway_api_config" "bug_report" {

### Steps to Reproduce

1. connect with gcloud cli to a project where you have owner rights
2. `terraform init`
3. `terraform apply`

### Important Factoids

None

### References

None

**Comment by edwardmedia** [comment]
@marc-at-boum  it seems to be fine in your `post` call. API complains about `{device}`.  I did not see it until it shows up in the error. Is that part of the yaml file? I am not sure how you can use the wildcard in the yaml if that is true. There is little the provider can help. Here is the API doc that might help you resolve the issue https://cloud.google.com/api-gateway/docs/reference/rest/v1beta/projects.locations.apis.configs#file. Does that make sense?

**Comment by edwardmedia** [comment]
Closing assuming this is no longer an issue

**Comment by marc-at-boum** [comment]
Sorry I was on holidays. Somebody on Stackoverflow found the solution. I didn't give the parameter block in the specification. The log was rather confusing though.
