### ISSUE TITLE
terraform plan is hanging at refreshing state

### ISSUE THREAD

**Issue by mfhuang** [hashicorp/terraform-provider-google#12121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.5

### Affected Resource(s)
This impact all the google_compute resources that we are trying to update.
* google_compute_*

Some examples are:
google_compute_region_target_http_proxy
google_compute_region_url_map
google_compute_region_target_http_proxy
google_compute_forwarding_rule

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

https://gist.github.com/mfhuang/3d9efb1a974adf48ae2f0c510b762717

### Panic Output
N/A

### Expected Behavior

When we run terraform plan and apply it should just work.

### Actual Behavior
When we run `terraform plan`, the job is hanging at refreshing state... This happens both in TFE UI Console and local run. The UI job timed out and failed eventually after 4 hours (4 hour is the timeout policy at our org). 
It doesn't hang every time though. We are seeing about 20-30% passing rate. If we retry enough times, repeatedly start new plan from UI or run `terraform plan` locally, we may get lucky and the plan will pass.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

We started to seeing this issue 3-4 weeks ago and it was getting worse. We was originally on the older terraform version 0.13.7 and google provider 3.90.1, and had upgraded to Terraform 1.2.5 with Google provider 4.28.0 but still seeing the issue.

A GCP support [ticket](https://console.cloud.google.com/support/cases/detail/v2/30028189) is opened, however the GCP support couldn't provide much information and suggested us reach out to the Terraform Google Provider support.

### References

* #0000

**Comment by edwardmedia** [comment]
@mfhuang I can't open the log file you provided under Debug Output. It gives me 404 error. I can't open the GCP support ticket either as I don't have access to your project. 

Are these only happening for resources `google_compute_*`? Do you have other non `google_compute_*` resources in the plan? How many resources does it have in the plan? Are you using a lot of dynamic blocks?

**Comment by mfhuang** [comment]
@edwardmedia I had to remove the debug output because it contains some internal data, but now it's updated: https://gist.github.com/mfhuang/3d9efb1a974adf48ae2f0c510b762717

We have only a few other resources but GCE is the majority. We have total 251 resources in our plan.
I will take a look at the other hanging issues as well. Thanks!

**Comment by edwardmedia** [comment]
@mfhuang your log reveals little regarding the work at the provider level. How did you know this happened on the resources `google_compute_*`? Where is the remote state? How good is the connection between your Terraform runner and the bucket where the state is? 
Yes, let me know what you find after you reviewed the earlier reported issues

**Comment by mfhuang** [comment]
@edwardmedia the debug and trace logs didn't tell us much so we don't actually know what is happening. `terraform plan` just hangs at refreshing state and google_compute_forwarding_rule.bastion_http happens to be the last resource in the log. 
This is the log from TFE console after we cancel the run.
```
module.dev-central1-bastion-host-0-72-0.google_compute_forwarding_rule.bastion_http: Refreshing state... [id=****]

------------ Terraform Enterprise System Message ------------

Force cancel signal received. Terraform will now abort.

-------------------------------------------------------------
failed to check for existence of custom script /usr/local/bin/finalize_custom_worker.sh: invalid state to create container
```

We host our private terraform enterprise in cloud. I'm reaching out to our SRE team to get more information about the setup.

I read the issue (#9631). It seems that the hanging issue was caused by the MIG state with `wait_for_instances` and `wait_for_instances_status`. We don't particularly set those in our configuration and in the remote state I can see those values are set to 
```
    wait_for_instances               = false
    wait_for_instances_status        = "STABLE"
```
Here is the example of our MIG configuration. Do you see any problem here? This configuration has not been changed for over a year though.
https://gist.github.com/mfhuang/b42098a40649dfc3eb6ca5759e71fd46

**Comment by mfhuang** [comment]
Any other suggestion how to debug/troubleshooting the issue @edwardmedia 
Our Terraform Enterprise cluster is hosted in AWS but the connection between AWS and Google should be via a pretty fast direct connect.
I also checked our TFE server logs and didn't see any interesting things other than the heartbeat requests from the UI while the plan is hanging at refreshing state.

**Comment by mfhuang** [comment]
We found out that the hanging issue was caused by another provider. After we upgraded that provider, we were able to run the plan. Thanks for looking into this issue.
