### ISSUE TITLE
Resize boot disk cause destroy and recreate VM 

### ISSUE THREAD

**Issue by shumak80** [hashicorp/terraform-provider-google#12124]
### Terraform Version
Terraform v1.2.2

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

resource "google_compute_instance" "default" {
  name              = "vm1"
  machine_type = "e2-standard-2"
  zone               = "europe-west3-a"
 
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-10"
      size = "20"
      type = "pd-standard"
    }
  }
  network_interface {
    subnetwork = "default"
  }
}

### Expected Behavior
GCP provider support resize of disk without destroy/recreate the instance.

### Actual Behavior
The VM is deleted and recreated.
GCP is able to resize the disk on the fly even boot disk so I expect to have the size increased but without deleting re-creating the VM.

### Steps to Reproduce

1. `terraform apply`
2. change size of the disk to 25
3. `terraform apply`

### References
This issue was already solved in https://github.com/hashicorp/terraform-provider-google/issues/861 , but it was for resource google_compute_disk.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

**Comment by edwardmedia** [comment]
@shumak80 did you notice the discussion in https://github.com/hashicorp/terraform-provider-google/issues/8597 Is that relevant?

**Comment by shumak80** [comment]
@edwardmedia It's not related to #8597 ... #8597 is about downsize disk. My case is about increase size of disk. It can be done without any changes to VM instance.

**Comment by edwardmedia** [comment]
@shumak80 That is the boot_disk, right? Where did you see you can resize the boot_disk without recreation?

**Comment by shumak80** [comment]
@edwardmedia It's a common thing ... you can read about this [here](https://cloud.google.com/compute/docs/disks/resize-persistent-disk). Even you can try it via console. If you create a boot disk as separate resource and use it as source for boot disk, then you are able to resize boot disk without re-creation.

**Comment by shuyama1** [comment]
It seems that in-place update for this field is not yet supported when the feature was implemented. Making it updatable is a feature request and making this issue as enhancement then.

**Comment by shumak80** [comment]
Ok. Then it should be mentioned in terraform documentation. To warn everybody that this feature is not ready yet.

**Comment by rileykarson** [comment]
See https://github.com/hashicorp/terraform-provider-google/issues/6087 for prior discussion on the matter, mostly https://github.com/hashicorp/terraform-provider-google/issues/6087#issuecomment-619270971. `initialize_params` indicates "I want the instance to have been created with these properties" meaning that recreating it when changed *is* the expected behaviour of the provider.
