### ISSUE TITLE
Failing test(s): TestAccIAMBetaWorkloadIdentityPool_*

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12140]
Failure rate:

- 100% since added 7/9/2022

Impacted tests:
- TestAccIAMBetaWorkloadIdentityPool_iamWorkloadIdentityPoolBasicExample
- TestAccIAMBetaWorkloadIdentityPool_iamWorkloadIdentityPoolFullExample
- TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderAwsBasicExample
- TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderAwsFullExample
- TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderOidcBasicExample
- TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderOidcFullExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/315760?buildTab=tests&expandedTest=-29076889344457039

Message:

```
Error creating WorkloadIdentityPool: googleapi: got HTTP response code 404 with body:

# ... 

<p>The requested URL <code>/v/projects/project-id/locations/global/workloadIdentityPools?alt=json&amp;workloadIdentityPoolId=tf-test-example-poolx2hn0c4x4x</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by jon-at-rithmik** [comment]
These WIP resources were promoted to GA. I can't speak to the naming, but the resources are no longer available via beta REST api, they are on v1 api. But, the latest provider release tries to reach them with invalid URL, so these resources are not usable at all with any version of the provider.

**Comment by melinath** [comment]
It looks like the beta API still exists for now (which is why our beta tests are still passing) but is marked as deprecated. It's possible something significant changed between beta & GA, which could be why the GA tests are failing. Based on the feedback above it sounds like this represents a real bug for users.

b/239836939

**Comment by jon-at-rithmik** [comment]
The error message reveals cause:

```
The requested URL <code>/v/projects/project-id
```

"v" is the invalid part, there should be a 1/2/3 after it. It lines up with [this line](https://github.com/modular-magician/terraform-provider-google/blob/0c1eb75297565aec63f6d35b7439e214dd27d204/google/config.go#L385) from the promotion PR.

I'm not familiar with building providers or else I'd try a local fix.

**Comment by melinath** [comment]
Resolved by https://github.com/hashicorp/terraform-provider-google/pull/12145
