### ISSUE TITLE
Cloud composer ip_allocation_policy bug

### ISSUE THREAD

**Issue by DanishKhakwani** [hashicorp/terraform-provider-google#12167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.2
+ provider registry.terraform.io/hashicorp/google v4.29.0
+ provider registry.terraform.io/hashicorp/google-beta v4.29.0

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "google_composer_environment" "airflow-staging" {
  provider = google-beta
  name     = "airflow-staging"
  region   = var.region

  config {
    node_count = 3
    node_config {
      zone            = "projects/${var.project}/zones/${var.region}-c"
      machine_type    = "projects/${var.project}/zones/${var.region}-c/machineTypes/n2-standard-8"
      disk_size_gb    = 100
      network         = module.vpc.network_name
      subnetwork      = "..."
      service_account = "..."
      oauth_scopes = [
        "https://www.googleapis.com/auth/cloud-platform"
      ]
      enable_ip_masq_agent = false
      ip_allocation_policy = [
        {
          cluster_ipv4_cidr_block       = "172.19.96.0/19"
          services_ipv4_cidr_block      = "172.19.128.0/19"
          use_ip_aliases                = true
        }
      ]
    }

    database_config {
      machine_type = "db-n1-standard-2"
    }

    web_server_config {
      machine_type = "composer-n1-webserver-2"
    }

    software_config {
      image_version  = "composer-1.18.12-airflow-2.2.5"
      python_version = "3"
      airflow_config_overrides = {
        "core-dags_are_paused_at_creation" = "True"
        "scheduler-parsing_processes"      = "6"
      }
    }

    private_environment_config {
      enable_private_endpoint = false
    }

    web_server_network_access_control {
      allowed_ip_range {
        value       = ...
        description = "Allows access from all IPv4 addresses"
      }
      allowed_ip_range {
        value       = ...
        description = "Allows access from all IPv6 addresses"
      }
    }

    maintenance_window {
      end_time   = "2022-06-16T13:00:00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=SA,SU"
      start_time = "2022-06-16T07:00:00Z"
    }
  }
}
```

### Expected Behavior
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#:~:text=this%20ip%20range.-,The%20ip_allocation_policy%20block%20supports%3A,-use_ip_aliases%20%2D%20(Optional%2C%20Cloud
According to the docs either / or is required when defining `cluster_ipv4_cidr_block` `services_ipv4_cidr_block` (shouldn't need to define `cluster_secondary_range_name`, `services_secondary_range_name`). Even though when those two values are defined it errors out. `Error: Conflicting configuration arguments`

### Actual Behavior
```
│ Error: Incorrect attribute value type
│
│   on composer-airflow-staging.tf line 21, in resource "google_composer_environment" "airflow-staging":
│   21:       ip_allocation_policy = [
│   22:         {
│   23:           cluster_ipv4_cidr_block       = "172.19.96.0/19"
│   24:           services_ipv4_cidr_block      = "172.19.128.0/19"
│   25:           use_ip_aliases                = true
│   26:         }
│   27:       ]
│
│ Inappropriate value for attribute "ip_allocation_policy": element 0: attributes "cluster_secondary_range_name" and "services_secondary_range_name" are required.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@DanishKhakwani could you try something like below config
```
  config {
    node_config {
      network        = google_compute_network.test.self_link
      subnetwork     = google_compute_subnetwork.test.self_link
      zone           = "us-central1-a"
      machine_type  = "n1-standard-1"
      ip_allocation_policy {
        use_ip_aliases          = true
        cluster_ipv4_cidr_block = "10.0.0.0/16"
      }
    }
  }
```

**Comment by DanishKhakwani** [comment]
Same error:
```
│ Error: Incorrect attribute value type
│
│   on composer-airflow-staging.tf line 21, in resource "google_composer_environment" "airflow-staging":
│   21:       ip_allocation_policy = [
│   22:         {
│   23:           use_ip_aliases                = true
│   24:           cluster_ipv4_cidr_block       = "172.19.96.0/19"
│   25:           services_ipv4_cidr_block      = "172.19.128.0/19"
│   26:           use_ip_aliases                = true
│   27:         }
│   28:       ]
│
│ Inappropriate value for attribute "ip_allocation_policy": element 0: attributes "cluster_secondary_range_name" and "services_secondary_range_name" are required.
```

According to the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#use_ip_aliases) `use_ip_aliases` is not required to be set 
```
use_ip_aliases
(Optional, Cloud Composer 1 only) Whether or not to enable Alias IPs in the GKE cluster.
If true, a VPC-native cluster is created. 
Defaults to true if the ip_allocation_policy block is present in config.
```

Also this is Composer v1 Cluster.

**Comment by edwardmedia** [comment]
@DanishKhakwani can you share your full debug log so I can take a close look?

**Comment by edwardmedia** [comment]
@DanishKhakwani is this still an issue?

**Comment by razilevin** [comment]
I am experiencing it as well except I am trying to use it in reverse by specifying the range names

`...
      ip_allocation_policy = [{
        cluster_secondary_range_name  = var.airflow_cluster_secondary_range
        services_secondary_range_name = var.airflow_services_secondary_range
        use_ip_aliases                = true
}]`

 I see this when validating with the above ip_allocation_policy
 
 `╷
│ Error: Incorrect attribute value type
│ 
│   on modules/airflow/main.tf line 41, in resource "google_composer_environment" "instance":
│   41:       ip_allocation_policy = [{
│   42:         cluster_secondary_range_name  = var.airflow_cluster_secondary_range
│   43:         services_secondary_range_name = var.airflow_services_secondary_range
│   44:         use_ip_aliases                = true
│   45:       }]
│     ├────────────────
│     │ var.airflow_cluster_secondary_range is a string, known only after apply
│     │ var.airflow_services_secondary_range is a string, known only after apply
│ 
│ Inappropriate value for attribute "ip_allocation_policy": element 0: attributes
│ "cluster_ipv4_cidr_block" and "services_ipv4_cidr_block" are required.`

And when I add back blanks for "cluster_ipv4_cidr_block" and "services_ipv4_cidr_block"  to pass validation I get

`╷
│ Error: Conflicting configuration arguments
│ 
│   with module.airflow.google_composer_environment.instance,
│   on modules/airflow/main.tf line 36, in resource "google_composer_environment" "instance":
│   36:     node_config {
│ 
│ "config.0.node_config.0.ip_allocation_policy.0.cluster_secondary_range_name":
│ conflicts with
│ config.0.node_config.0.ip_allocation_policy.0.cluster_ipv4_cidr_block
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.airflow.google_composer_environment.instance,
│   on modules/airflow/main.tf line 36, in resource "google_composer_environment" "instance":
│   36:     node_config {
│ 
│ "config.0.node_config.0.ip_allocation_policy.0.services_secondary_range_name":
│ conflicts with
│ config.0.node_config.0.ip_allocation_policy.0.services_ipv4_cidr_block
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.airflow.google_composer_environment.instance,
│   on modules/airflow/main.tf line 36, in resource "google_composer_environment" "instance":
│   36:     node_config {
│ 
│ "config.0.node_config.0.ip_allocation_policy.0.cluster_ipv4_cidr_block":
│ conflicts with
│ config.0.node_config.0.ip_allocation_policy.0.cluster_secondary_range_name
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with module.airflow.google_composer_environment.instance,
│   on modules/airflow/main.tf line 36, in resource "google_composer_environment" "instance":
│   36:     node_config {
│ 
│ "config.0.node_config.0.ip_allocation_policy.0.services_ipv4_cidr_block":
│ conflicts with
│ config.0.node_config.0.ip_allocation_policy.0.services_secondary_range_name
╵`
Trying to understand what I am doing wrong and I found this. Maybe this helps the debugging process

**Comment by razilevin** [comment]
This sounds interesting.
https://github.com/hashicorp/terraform-plugin-sdk/issues/705

**Comment by razilevin** [comment]
OK the ip-allocation policy cannot be an array but an object

`ip_allocation_policy {
...
}`

Sorry about the noise maybe help @DanishKhakwani

**Comment by edwardmedia** [comment]
@DanishKhakwani have you tried updating your config and see if your issue can be resolved? 

instead of 
```tf
      enable_ip_masq_agent = false
      ip_allocation_policy = [
        {
          cluster_ipv4_cidr_block       = "172.19.96.0/19"
          services_ipv4_cidr_block      = "172.19.128.0/19"
          use_ip_aliases                = true
        }
      ]
```
use this
```tf
      enable_ip_masq_agent = false
      ip_allocation_policy {
          cluster_ipv4_cidr_block       = "172.19.96.0/19"
          services_ipv4_cidr_block      = "172.19.128.0/19"
          use_ip_aliases                = true
        }
```

**Comment by DanishKhakwani** [comment]
Thanks. I'll try that out and update. Sorry haven't got a chance to post the debug log.

**Comment by DanishKhakwani** [comment]
@edwardmedia That was indeed a syntax issue. Seems to be working as expected now :). Thanks for your help!

**Comment by edwardmedia** [comment]
@DanishKhakwani glad your problem is solved. Closing the issue then
