### ISSUE TITLE
Can't import google_firebase_web_app resource

### ISSUE THREAD

**Issue by flisak-robert** [hashicorp/terraform-provider-google#12160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.2.4

### Affected Resource(s)

* google_firebase_web_app

### Terraform Configuration Files

```tf
resource "google_project" "project" {
  name       = "firebase-test"
  project_id = "firebase-test"
}

resource "google_firebase_project" "this" {
  provider = google-beta
  project  = google_project.project.number
}

resource "google_firebase_web_app" "this" {
  provider = google-beta
  project = google_project.project.project_id
  display_name = "Firebase Test Web App"
  depends_on = [google_firebase_project.this]
}
```

### Debug Output
https://gist.github.com/flisak-robert/d2030fbf738a5803b7c2c529073f2a1e

### Expected Behavior
Firebase Web App resource is imported correctly.

### Actual Behavior
An error comes up: `Error: project: required field is not set`

### Steps to Reproduce

1. `terraform import google_firebase_web_app.this "projects/<REDACTED>/webApps/<REDACTED>"`

### Important Factoids
I've tried all possible values for the `project` field. I've used `number`, `project_id`, `id`, but nothing seems to work.

### References

* #0000

**Comment by edwardmedia** [comment]
@flisak-robert it seems fine with me with below command

```
terraform import google_firebase_web_app.basic projects/myporject/webApps/1:510482966318:web:e7d54898de5cc43f2fbcbf
```


https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/firebase_web_app#attributes-reference

**Comment by flisak-robert** [comment]
@edwardmedia 
Thanks for looking into this. Could you please tell me what kind of authentication method you're using? I've stumbled upon some cases where the exact same code worked with service account authentication and didn't work with other authentication methods. I'm using Application Default Credentials (logged in using gcloud cli - `gcloud auth application-default login`), maybe that's the issue?

**Comment by edwardmedia** [comment]
@flisak-robert `gcloud auth application-default login` should work as long as the account has right permissions. Based on what you said below, it appears these accounts have different roles (permissions) assigned. 

```
've stumbled upon some cases where the exact same code worked with service account authentication but didn't with other authentication methods
```

Here is the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication) you might want to review regarding the supported authentication

**Comment by flisak-robert** [comment]
@edwardmedia Unfortunately, it is not a permissions issue since I'm the owner of this GCP/Firebase project. The import works if I explicitly set the project attribute in `provider` configuration. Previously, my provider configuration looked like this:
```
provider "google-beta" {
  billing_project = "mybillingproject"
  user_project_override = true
}
```
And now when I've changed it to this:
```
provider "google-beta" {
  billing_project = "mybillingproject"
  user_project_override = true
  project = firebase-test
}
```
the import works. Why isn't the `project` field from the `google_firebase_web_app` resource propagated properly?

**Comment by edwardmedia** [comment]
@flisak-robert yes, you do need to provide the project in somewhere. Great you have figured it out. Close the issue then
