### ISSUE TITLE
google_netblock_ip_ranges requires credentials

### ISSUE THREAD

**Issue by cagataygurturk** [hashicorp/terraform-provider-google#12168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.29.0

### Affected Resource(s)

* google_netblock_ip_ranges

### Expected Behavior

We have a Terraform code where we only consume google_netblock_ip_ranges data source and no other provider resource/data source. Therefore the environment where this code is running has no Google Cloud credentials set up. As google_netblock_ip_ranges  is not depending on authentication, we would expect that not configuring credentials would be OK.

### Actual Behavior

The provider complaining about not finding credentials.

The following workaround makes provider thing that credentials are set up and apparently it works without problem as the google_netblock_ip_ranges is not making any authenticated calls to Google APIs.

```tf
provider "google" {
  access_token = "NOTVALID_ONLY_HERE_TO_WORKAROUND"
}
```

**Comment by edwardmedia** [comment]
@cagataygurturk all terraform provider google resources follow the same pattern, share multiple layers of library. It is not a good idea to break that just for this. You may consider a terraform local provider without TPG.

https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file#example-usage
