### ISSUE TITLE
VPN between GCP projects

### ISSUE THREAD

**Issue by kashtan404** [hashicorp/terraform-provider-google#12177]
Hi, I see no option in [google_compute_vpn_tunnel](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_vpn_tunnel) resource to specify target "project" for vpn tunnel. Will it be added in the nearest future?
<img width="578" alt="Screenshot 2022-07-26 at 12 10 54" src="https://user-images.githubusercontent.com/26811914/180970091-b96de8f6-d55a-46db-9e18-09eb81890de3.png">

**Comment by edwardmedia** [comment]
@kashtan404 here is the [api](https://cloud.google.com/compute/docs/reference/rest/v1/vpnTunnels) which is behind resource. There is no project. VPC tunnel is universal to the gateway on the other side while `project` is GCP specific. Does this make sense?

**Comment by edwardmedia** [comment]
@kashtan404 closing the issue now assume it is no longer a question
