### ISSUE TITLE
Add support for new 'version' property in DLP - InfoType

### ISSUE THREAD

**Issue by tomli-optus** [hashicorp/terraform-provider-google#12171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
There is a new property that has been introduced for InfoType named `version` (https://cloud.google.com/dlp/docs/reference/rest/v2/InfoType). Currently this is not supported, and I would like this to be added from the top level Inspection Template configuration e.g.

[POST] https://dlp.googleapis.com/v2/projects/:parent/inspectTemplates
```tf
{
 "inspectTemplate": {
  "description": "Example1 Description",
  "displayName": "Example1",
  "inspectConfig": {
   "infoTypes": [
    {
     "name": "EMAIL_ADDRESS"
    },
    {
     "name": "PERSON_NAME",
     "version": "latest"
    }
   ]
  }
}
```

I have made the necessary changes, and have tested this from the updated Unit Tests. Have also manually verified the generated API payloads by invoking the DLP APIs directly through Postman. I have attached the code, as I do not have permissions to push the new branch to the Repo.

### New or Affected Resource(s)

* google/resource_data_loss_prevention_inspect_template.go
* google/resource_data_loss_prevention_inspect_template_test.go
[resource_data_loss_prevention_inspect_template.zip](https://github.com/hashicorp/terraform-provider-google/files/9179077/resource_data_loss_prevention_inspect_template.zip)

**Comment by melinath** [comment]
@tomli-optus it sounds like you've already made the changes - if you want to make a pull request, check out https://github.com/GoogleCloudPlatform/magic-modules#magic-modules for instructions on how to make contributions to this repository.

You might also find these docs useful: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by sanghaniJ** [comment]
b/263692678
