### ISSUE TITLE
Use `quota_project_id` as a default project for resources

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-provider-google#12170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As per docs

> Google Cloud reads the quota project for requests will be read automatically from the `core/project` value.

This is useful for any new users getting started with both GCP or Terraform. However, even if the user runs the following

```
gcloud config set project foo-bar-radek
gcloud auth application-default login
```
and the default credentials file clearly contains the project ID

```
$ jq .quota_project_id ~/.config/gcloud/application_default_credentials.json
"foo-bar-radek"
```

it appears that the provider still expects the desired project to be set when creating resources, e.g.

```hcl
resource "google_compute_instance" "example" {
  name         = "example"
  machine_type = "e2-small"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-10"
    }
  }

  network_interface {
    network = "default"
  }
}
```
```sh
$ terraform apply
```
```
google_compute_instance.this: Creating...
╷
│ Error: project: required field is not set
│
│   with google_compute_instance.this,
│   on main.tf line 11, in resource "google_compute_instance" "this":
│   11: resource "google_compute_instance" "this" {
│
╵
```

Could we just read the default project name from there and avoid having to set the project name twice, for the simplest setup?

### New or Affected Resource(s)

* `google_compute_instance`

**Comment by rileykarson** [comment]
We're not sure if we can access this project, and would prefer that users are explicit in their Terraform configuration rather than implicitly using this one.

I believe that we align on at least one project environment variable with gcloud for users that want to set it exactly once.
