### ISSUE TITLE
Unable to create google_iam_workload_identity_pool - the google api call is using incorrect api version

### ISSUE THREAD

**Issue by dimitdb** [hashicorp/terraform-provider-google#12186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform  v0.12.31
provider registry.terraform.io/hashicorp/google v4.30.0

### Affected Resource(s)

* google_iam_workload_identity_pool

### Terraform Configuration Files

```tf
provider "google" {
  credentials = file("path-to-credentials")
  project     = "myproject"
  region      = "europe-west1"
}

resource "random_id" "rid" {
  keepers     = {
    project_id = "myproject"
  }
  byte_length = 6
}

resource "google_iam_workload_identity_pool" "widf_pool" {
  workload_identity_pool_id = "legacy-${random_id.rid.hex}"
}
```

### Debug Output
https://gist.github.com/dimitdb/040d4e8ed4f3422b61f2129ff812fcd3

### Expected Behavior
terraform apply to complete successfully and a new workload identity pool to be created

### Actual Behavior
404 not found, note the api url terraform is calling, specifically the api version
POST /v/projects/myproject/locations/global/workloadIdentityPools?alt=json&workloadIdentityPoolId=widf-pool-ca3e884ed74f HTTP/1.1

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
Dup. A fix is https://github.com/hashicorp/terraform-provider-google/issues/12134. Should be in provider next week
