### ISSUE TITLE
google_billing_budget services bug

### ISSUE THREAD

**Issue by alanvuong** [hashicorp/terraform-provider-google#12185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.30.0
+ provider registry.terraform.io/hashicorp/google-beta v4.30.0

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

Initial deploy of google_billing_budget is fine.  Any subsequent change to `services` in budget_filter will not be applied, even when terraform confirms `Apply complete`

```tf
resource "google_billing_budget" "devbudget" {
  billing_account = var.billing_account_id
  display_name    = "dev budget"

  budget_filter {
    projects        = ["projects/XXXX"]
    calendar_period = "YEAR"
    services        = ["services/24E6-581D-38E5"]
  }

  amount {
    specified_amount {
      units = "100"
    }
  }
```

### Debug Output

https://gist.github.com/alanvuong/26208f42a43f7f68e105923642c7bddd

### Expected Behavior

Changes to the `services` in `budget_filter` should be updated in GCP Budgets

### Actual Behavior

When changes to `services` in `budget_filter` block are made, changes are detected and a confirmation of `Apply complete!` however there are no actual changes to the google budget.  Any other change in the `google_billing_budget` resource is actioned.

### Steps to Reproduce

1.  Create `google_billing_budget` resource with `budget_filter` with or without `services` declared - terraform plan/apply
2. Modify the same `google_billing_budget` to add or change `services` in 'budget_filter'
3. 'terraform plan` will detect the change
4. `terraform apply` will detect and confirm the change was applied
5. terraform state actually doesn't change and GCP console confirms no changes made to Budget

### References

* #0000

**Comment by edwardmedia** [comment]
@alanvuong could you share the debug log?

**Comment by alanvuong** [comment]
updated link to debug in initial post
