### ISSUE TITLE
google_billing_budget projects bug

### ISSUE THREAD

**Issue by andrewdelave** [hashicorp/terraform-provider-google#12196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- Terraform v1.2.6
on darwin_arm64
- provider registry.terraform.io/hashicorp/google v4.5.0

### Affected Resource(s)

- google_billing_budget

### Terraform Configuration Files

Initial apply of the 'google_billing_budget' is not working when the 'budget_filter' argument is set with 'projects' specified When the 'budget_filter' argument is removed, Terraform apply will work as expected. However when it is added, the Google API returns a 400 error.

```tf
resource "google_billing_budget" "budget" {
  billing_account = var.billing_acct_id
  display_name = "Example Billing Budget"
  budget_filter {
    projects = ["projects/12345123456"]
  }
  amount {
    last_period_amount = true
  }
  threshold_rules {
      threshold_percent =  10.0
  }
}
```

### Debug Output

https://gist.github.com/andrewdelave/c0fc6d22db9f3a5fa6d922c6f8e09530

### Expected Behavior

The expected behavior is that the budget is created with a 'budget_filter on the specific project listed in 'projects/PROJECT_NUMBER'

### Actual Behavior

Terraform returns a 400 error from the Google API stating there is an invalid argument.

```
Error: Error creating Budget: googleapi: Error 400: Request contains an invalid argument.
│ 
│   with google_billing_budget.budget,
│   on billing.tf line 47, in resource "google_billing_budget" "budget":
│   47: resource "google_billing_budget" "budget" {
```

### Steps to Reproduce

1. Create 'google_billing_budget' resource with 'budget_filter' with the 'projects' argument supplied.
2. 'terraform plan` will run successfully with the proposed changes.
3. 'terraform apply' will fail with and return the error stated above.

### Important Factoids

 
I am authenticating as a service account. The service account was able to create other budgets on the Billing Account when the 'projects' argument wasn't specified under 'budget_filter'.

### References

* #0000

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/12185

**Comment by shuyama1** [comment]
@andrewdelave Thanks for filing the issue. Unfortunately, I was not able to reproduce the error. The request seems valid. I've already created a ticket internally to ask the service team to look into the problem as I don't think the error message returned by the API is accurate. b/240743529

**Comment by andrewdelave** [comment]
@shuyama1 appreciate the help. Believe we were able to find the root cause of the issue. Essentially the projects that were being specified in the `["projects/12345123456"]` block were newly created and not attached to the billing account. Believe that is why it was returning the 400 error. A more useful error message still might be helpful if people come across the same issue in the future.

**Comment by shuyama1** [comment]
@andrewdelave Glad your problem got figured out. Agree that it would be more clear to users if the API returns a more useful error message. I'll update it on the internal ticket. Thanks!
