### ISSUE TITLE
Missing support for region in google_compute_target_tcp_proxy resource

### ISSUE THREAD

**Issue by CrackerJackMack** [hashicorp/terraform-provider-google#12197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the reference material I was following, it appears that the `google_compute_target_tcp_proxy` has `global` hard-coded throughout (eg. `projects/{{project}}/global/targetTcpProxies/`) making it impossible to add a regional TCP proxy target (currently in beta).

The feature this is required for is on-premise hosts and a hybrid cloud load balancer in order to provide cloud services such as private service connect endpoints, transition-based migrations, or even inter-cloud services.

### New or Affected Resource(s)

* google_compute_target_tcp_proxy

### Potential Terraform Configuration

```tf
#### NEG
resource "google_compute_network_endpoint_group" "neg" {
  provider              = google-beta
  name                  = "${var.name}-neg"
  network               = var.network
  default_port          = var.port
  zone                  = var.zone
  network_endpoint_type = "NON_GCP_PRIVATE_IP_PORT"
}

resource "google_compute_network_endpoint" "nodes" {
  provider               = google-beta
  for_each               = var.targets  # just set(string) of IP's of on-prem hosts
  zone                   = var.zone
  network_endpoint_group = google_compute_network_endpoint_group.neg.name
  port                   = google_compute_network_endpoint_group.neg.default_port
  ip_address             = each.value
}

#### The load balancer
resource "google_compute_region_health_check" "tcp-health-check" {

  name               = "${var.name}-health-check"
  region             = var.region
  timeout_sec        = 1
  check_interval_sec = 1

  tcp_health_check {
    port = var.port
  }
}

resource "google_compute_region_backend_service" "default" {
  provider              = google-beta
  name                  = "${var.name}-backend"
  load_balancing_scheme = "INTERNAL_MANAGED"
  locality_lb_policy    = "RANDOM"
  protocol              = "TCP"

  #   network               = var.network
  region        = var.region
  health_checks = [google_compute_region_health_check.tcp-health-check.id]

  backend {
    balancing_mode               = "CONNECTION"
    max_connections_per_endpoint = "100"
    capacity_scaler              = 1.0
    group                        = google_compute_network_endpoint_group.neg.id
  }
}

resource "google_compute_target_tcp_proxy" "default" {
  provider        = google-beta
  name            = "${var.name}-tcp"
  region          = var.region
  backend_service = google_compute_region_backend_service.default.id
}

resource "google_compute_forwarding_rule" "default" {
  name                  = "fwrule-${var.name}"
  region                = var.region
  ip_protocol           = "TCP"
  load_balancing_scheme = "INTERNAL_MANAGED"
  target                = google_compute_target_tcp_proxy.default.id
  network    = var.network
  subnetwork = var.subnetwork
  ip_address = google_compute_address.loadbalancer-ip.id
}


resource "google_compute_address" "loadbalancer-ip" {
  name         = "${var.name}-static"
  subnetwork   = var.subnetwork
  region       = var.region
  address_type = "INTERNAL"
  purpose      = "GCE_ENDPOINT"

}
```

### References

* [Provider code](https://github.com/hashicorp/terraform-provider-google/blob/v4.30.0/google/resource_compute_target_tcp_proxy.go)
* [Google internal TCP proxy hybrid howto](https://cloud.google.com/load-balancing/docs/tcp/set-up-int-tcp-proxy-hybrid#gcloud_3)
* [Google internal regional load balancer](https://cloud.google.com/load-balancing/docs/forwarding-rule-concepts#internal-tcp-proxy)
* [Google backend services reference](https://cloud.google.com/load-balancing/docs/backend-service)

**Comment by rileykarson** [comment]
Note: We'd likely implement this as a new resource entirely, in line with similar GCE resources

**Comment by rosmo** [comment]
I'm working on this.
