### ISSUE TITLE
Schedule Backup functionality for Bigtable using terraform

### ISSUE THREAD

**Issue by Suresh-Sathish-Kumar** [hashicorp/terraform-provider-google#12191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_bigtable_table_backup

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by Suresh-Sathish-Kumar** [comment]
Hi,

We are looking for a resource to be available for scheduling the bigtable backup via terraform.

Thanks,
Suresh

**Comment by ScottSuarez** [comment]
Scheduling backups isn't supported at the API level thus we cannot support it within terraform.
https://cloud.google.com/bigtable/docs/backups

If you are looking for a way to schedule backups i would recommend filing an issue or feature request against the API. A terraform resource/field could then be created as an interface for it.

**Comment by kevinsi4508** [comment]
We (Cloud Bigtable) are aware of the scheduled backup feature. Nothing concrete to share at the moment.

**Comment by melinath** [comment]
b/259279152

**Comment by eraac** [comment]
As workaround, to have a backup automation setup 100% via Terraform, here a [workflow script + terraform file](https://gist.github.com/eraac/67247322172b122093e8f0372712eecd) (trigger via cloud scheduler)

Input (all tables)
```json
{"cluster_id": "xxx", "instance_id": "yyy", "project_id": "zzz"}
```

Input (specific tables)
```json
{"cluster_id": "xxx", "instance_id": "yyy", "project_id": "zzz", "tables": ["table1", "table2"]}
```

**Comment by SarahFrench** [comment]
The release notes for BigTable show that an automated backups feature was released in Preview about 2 months ago: https://cloud.google.com/bigtable/docs/release-notes#March_19_2024

Documentation : https://cloud.google.com/bigtable/docs/managing-backups#use-automated-backup
The new field in the API: https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.tables#Table.FIELDS.automated_backup_policy

However this feature [doesn't appear to be supported in the client library yet](https://pkg.go.dev/cloud.google.com/go/bigtable@v1.23.0#TableConf), which is used by the Google provider when managing BigTable resources

**Comment by SarahFrench** [comment]
A new version of the client library that supports automated backups,[ 1.24, was released on May 28th](https://pkg.go.dev/cloud.google.com/go/bigtable?tab=versions) and that update was used in https://github.com/GoogleCloudPlatform/magic-modules/pull/10674 to add the `automated_backup_configuration` field to  the `google_bigtable_table` resource. That change will be included in an upcoming release. Based on timings I believe it'll be in v5.34.

Closing this issue as completed.
