### ISSUE TITLE
Firewall rule, pipeline error

### ISSUE THREAD

**Issue by damiancancela** [hashicorp/terraform-provider-google#12212]
Hello,

im trying to create a FW rule in GCP using Terraform 4.13 with this code over an orchestration pipeline.

Code

resource "google_compute_firewall" "ingress" {
  name    = "test-firewall"
  network = data.google_compute_network.shared_vpc.id

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }
  priority = "1020"

  source_ranges = ["35.191.0.0/16","130.211.0.0/22"]
  
}*/

Error

         "google_compute_firewall ingress: Firewall rule must target a service account for dictionary value @ data['google_compute_firewall']['target_service_accounts']"

Do you have some idea on what is going on?

Thanks

**Comment by edwardmedia** [comment]
@damiancancela can you share your debug log?

**Comment by damiancancela** [comment]
Hello, ive fixed the issue creating a service account with proper roles permissions. That fixed the issue.

Thank you and sorry for bothering
