### ISSUE TITLE
Documentation: provider configuration is missing GOOGLE_PROJECT

### ISSUE THREAD

**Issue by jtallar** [hashicorp/terraform-provider-google#12213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.6
- provider registry.terraform.io/hashicorp/google v4.30.0

### Affected Resource(s)

* [Documentation: Provider reference](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference)

### Issue description
The documenation (v4.30.0, latest at the time of writing) doesn't mention the possibility of using the environment variable `GOOGLE_PROJECT` to configure the default project to manage resources in. I was looking for ways to do so to avoid having an extra variable specifying the project ID. I tested it with a sample configuration and it works as expected.

### Important Factoids

I'm using `GOOGLE_APPLICATION_CREDENTIALS` environment variable for authentication.

**Comment by edwardmedia** [comment]
@jtallar I am seeing GOOGLE_PROJECT in the link you provide. Not sure exactly what you referred to `missing` It is under [full reference](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#full-reference) section. Can you check again or am I missing your point?

**Comment by jtallar** [comment]
My bad @edwardmedia , I was looking at the incorrect section. This issue can be closed.

**Comment by edwardmedia** [comment]
Thanks @jtallar Closing now
