### ISSUE TITLE
Control plane monitoring

### ISSUE THREAD

**Issue by alen-z** [hashicorp/terraform-provider-google#12220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

From GKE version 1.23.6 there is a possibility to turn on Control plane monitoring.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/7421289/182364239-c37f924e-19ea-480b-874d-72201ef50c3a.png">

This is available to be used with `gcloud`: https://cloud.google.com/stackdriver/docs/solutions/gke/managing-metrics#configuring_collection_of_control_plane_metrics

But I can not seem to find API documentation to make sure there is a prerequisite for Terraform to include this feature.

We'd like to apply some from pool of options with Terraform: `SYSTEM,API_SERVER,SCHEDULER,CONTROLLER_MANAGER`.

Am I missing something? Thank you.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
<depending on the GCP API definition>
```

### References

* https://cloud.google.com/stackdriver/docs/solutions/gke/managing-metrics#configuring_collection_of_control_plane_metrics
* https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster
* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters

**Comment by yungdarek122** [comment]
AFAIK, there is no prerequisite to add Terraform support to this feature. I am working on https://github.com/GoogleCloudPlatform/magic-modules/pull/6352 for that. 

The API documentation should be updated accordingly soon.

**Comment by alen-z** [comment]
Hey, just got here to mention that I've seen those new values being available, but you are fast! Looking for a next release.
