### ISSUE TITLE
Root of domain not returning correct record type or resource record data

### ISSUE THREAD

**Issue by jogoldberg** [hashicorp/terraform-provider-google#12223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.30.0
+ provider registry.terraform.io/hashicorp/google-beta v4.30.0

### Affected Resource(s)

* google_app_engine_domain_mapping

### Terraform Configuration Files

```tf
resource "google_app_engine_domain_mapping" "domain_mapping_2" {
  depends_on  = [google_app_engine_application.main]
  domain_name = "dev.example.com" #This domain is the root of a delegated DNS zone.

  ssl_settings {
    ssl_management_type = "AUTOMATIC"
  }
}

output "dump_dns" {
  value = google_app_engine_domain_mapping.domain_mapping_2.resource_records 
}

```

### Debug Output
OK I distilled the log down to just the relevant section and have removed secret information.
https://gist.github.com/jogoldberg/990ac609add9e0c2ecec190901ce60c4

### Expected Behavior

The custom URL domain mapping should be setup, and the records that are actually created (and visible in the GCP console) should be reflected in the resource_records attribute on the tfstate object

### Actual Behavior

the resource_records attribute on the tfstate object incorrectly says that the custom domain mapping goes to a CNAME which should point to ghs.googlehosted.com 

output in code provided produces this:

```
dump_dns = tolist([
  {
    "name" = "dev"
    "rrdata" = "ghs.googlehosted.com."
    "type" = "CNAME"
  },
])
```

because this is the root of the DNS zone, GCP actually needs (and has created) a mapping to a group of A Records and AAAA records.
![image](https://user-images.githubusercontent.com/82210743/182406526-9c1e2bb4-2c2f-42e8-ab5a-42ecb145c5b6.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

even though this looks like a subdomain, dev.example.com (not my real domain) is a naked domain as it's a delegated subzone of the root domain.

### References

* #0000

**Comment by edwardmedia** [comment]
@jogoldberg could you share your full debug log?

**Comment by jogoldberg** [comment]
> @jogoldberg could you share your full debug log?

I'll need some time to redact it. It contains a lot of secrets.

**Comment by jogoldberg** [comment]
> @jogoldberg could you share your full debug log?

OK I distilled the log down to just the relevant section and have removed secret information.
https://gist.github.com/jogoldberg/990ac609add9e0c2ecec190901ce60c4

**Comment by jogoldberg** [comment]
> > @jogoldberg could you share your full debug log?
> 
> OK I distilled the log down to just the relevant section and have removed secret information. https://gist.github.com/jogoldberg/990ac609add9e0c2ecec190901ce60c4

Having checked the debug, it looks like terraform is getting a bad response from the API. I've opened an issue with Google.
https://issuetracker.google.com/issues/241076235

If you concur that this is the cause, please feel free to close this issue

**Comment by edwardmedia** [comment]
@jogoldberg this is what the api sent back (see in your log), the same as you reported originally. Closing the issue as you requested

```
  "resourceRecords": [
    {
      "name": "dev",
      "rrdata": "ghs.googlehosted.com.",
      "type": "CNAME"
    }
  ]
```
