### ISSUE TITLE
Unable to use existing Pub/Sub topic ID in eventarc 

### ISSUE THREAD

**Issue by akhil-senroy** [hashicorp/terraform-provider-google#12232]
### Issue Description

I am trying to deploy an eventarc trigger for type = google.cloud.pubsub.topic.v1.messagePublished trough Terraform.
Terraform seems to deploy a new Pub/Sub topic when I refer to the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger). Is there a way we can specify an existing Pub/Sub topic ID?

**Comment by SarahFrench** [comment]
Hi there @akhil-senroy !

If I understand you correctly, you want eventarc to send messages to an existing Pub/Sub topic but currently it is making its own, right?

There is the ability to instruct eventarc to use an existing topic (e.g here's a [gcloud command where that's done](https://cloud.google.com/eventarc/docs/creating-triggers#pubsub-messages-existing-topic), and [the default behaviour seems to be creating a new topic](https://cloud.google.com/eventarc/docs/creating-triggers#pubsub-messages-new-topic)) and I believe this is also possible with the provider.

From looking at the provider's documentation, defining [a `transport` block in the resource block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger#transport), which contains a [nested `pubsub` block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger#pubsub) , would help you achieve this. The configuration would look something like this:

```hcl

resource "google_pubsub_topic" "existing-topic" {
    name = "topic"
}

resource "google_eventarc_trigger" "primary" {
    name = "name"
    location = "europe-west1"
    matching_criteria {
        attribute = "type"
        value = "google.cloud.pubsub.topic.v1.messagePublished"
    }
    destination {
        cloud_run_service {
            service = google_cloud_run_service.default.name # not shown in this snippet
            region = "europe-west1"
        }
    }
    transport {
        pubsub {
            topic = google_pubsub_topic.existing-topic.id
        }
    }
    labels = {
        foo = "bar"
    }
}
```

This would use an existing topic, but eventarc would still create and manage a new subscription attached to the preexisting topic.

Does this help with your issue? If not, or their are any more issues please follow up in here and I'll see if I can help

**Comment by akhil-senroy** [comment]
Thanks Sarah, this is exactly what I wanted!
