### ISSUE TITLE
Error creating ConsumerQuotaOverride - COMMON_QUOTA_LIMIT_NOT_FOUND

### ISSUE THREAD

**Issue by pfilourenco** [hashicorp/terraform-provider-google#12253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.1

### Affected Resource(s)

google_service_usage_consumer_quota_override

### Terraform Configuration Files

```tf
resource "google_service_usage_consumer_quota_override" "override" {
  provider = google-beta
  for_each = local.consumer_quotas

  project        = var.project_id
  service        = each.value.service
  metric         = urlencode(each.value.metric)
  limit          = urlencode(each.value.limit)
  dimensions     = each.value.dimensions
  override_value = each.value.value
  force          = true
}
```

### Terraform Plan

```tf
  + resource "google_service_usage_consumer_quota_override" "override" {
      + force          = true
      + id             = (known after apply)
      + limit          = "1%2Fd%2F%7Bproject%7D%2F%7Buser%7D"
      + metric         = "bigquery.googleapis.com%2Fquota%2Fquery%2Fusage"
      + name           = (known after apply)
      + override_value = "262144"
      + project        = "xxx-xxx-xxxx-xxxxx"
      + service        = "bigquery.googleapis.com"
    }
```

### Expected Behavior

It's working with gcloud:
`gcloud alpha services quota update --consumer=projects/xxx-xxx-xxx-xxx--service bigquery.googleapis.com --metric bigquery.googleapis.com/quota/query/usage --value 262144 --unit 1/d/{project}/{user} --force`
`Operation "operations/quat.p33-197845121441-9aa0bc9b-5d9b-4334-9515-358cbed9e55e" finished successfully.`

### Actual Behavior

```╷
│ Error: Error creating ConsumerQuotaOverride: googleapi: Error 404: No quota limit with limitId '1/d/{project}/{user}' for metric 'bigquery.googleapis.com/quota/query/usage' found in service 'bigquery.googleapis.com'.
│ Help Token: AfeSHlLogAP_I5COYIHeItLTZHmJosQcjsyC8m86_KcQBpKf8ZgUBkZpu99UeTHByWLyfFjKvqnVfOZXLM2XDpkvZ1Qw7L3v4bisvaRecozmOAw2
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "?error_code=101005\u0026limit_id=1/d/%7Bproject%7D/%7Buser%7D\u0026metric=bigquery.googleapis.com/quota/query/usage\u0026service_name=bigquery.googleapis.com",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "metadata": {
│       "limit_id": "1/d/{project}/{user}",
│       "metric": "bigquery.googleapis.com/quota/query/usage",
│       "service_name": "bigquery.googleapis.com"
│     },
│     "reason": "COMMON_QUOTA_LIMIT_NOT_FOUND"
│   }
│ ]
```

**Comment by SarahFrench** [comment]
Hi @pfilourenco , thanks for reporting this issue!

I've been able to reproduce this and it looks like the API has changed structure at some point in the past. The provider is using an older version of the API but the old structure of the API is still being supported (but I guess excludes newer types of quota?) , so our tests didn't fail

I'll work on a fix and will add a new test, thanks again 😁

**Comment by pfilourenco** [comment]
Hi @SarahFrench, any update on this?

**Comment by SarahFrench** [comment]
Hi, I'm still digging into this - I think there are 2 factors affecting this bug so it's taking a little while!

**Comment by karan-kaushik** [comment]
Hi, I was facing the same issue with the terraform code, using the following limit value `/d/project/user` helped solve it.

### Terraform Configuration
```
module "project_quota_manager" {
  source         = "terraform-google-modules/project-factory/google//modules/quota_manager"
  project        = "my-project-id"
  consumer_quotas = {
    user_daily_quota = {
        service        = "bigquery.googleapis.com"
        metric         = urlencode("bigquery.googleapis.com/quota/query/usage")
        limit          = urlencode("/d/project/user")
        override_value = 10
        force          = true

    }
  }
}
```

### Terraform Plan
```
  + resource "google_service_usage_consumer_quota_override" "override" {
      + force          = true
      + id             = (known after apply)
      + limit          = "%2Fd%2Fproject%2Fuser"
      + metric         = "bigquery.googleapis.com%2Fquota%2Fquery%2Fusage"
      + name           = (known after apply)
      + override_value = "10"
      + project        = "my-project-id"
      + service        = "bigquery.googleapis.com"
    }
```

### Terraform Output
```
  + user_daily_quota    = {
      + dimensions     = null
      + force          = true
      + id             = (known after apply)
      + limit          = "%2Fd%2Fproject%2Fuser"
      + metric         = "bigquery.googleapis.com%2Fquota%2Fquery%2Fusage"
      + name           = (known after apply)
      + override_value = "10"
      + project        = "my-project-id"
      + service        = "bigquery.googleapis.com"
      + timeouts       = null
    }
```

Hope this helps solve the issue

**Comment by SarahFrench** [comment]
@pfilourenco Does the above advice from @/karan-kaushik solve your problem?

**Comment by karan-kaushik** [comment]
Thank you for this clarification @SarahFrench 🙏
I will keep my eye out for the new changes to the provider.

**Comment by karan-kaushik** [comment]
> Thank you @karan-kaushik ! 🙏
> 
> From what I've found, I think this is where the confusion comes from:
> 
> **Terraform provider**
> 
> * Uses older but still-functioning version of the beta API
> * Older API requires the `unit` value to be like `/d/project/user/`
> 
> **gcloud**
> 
> * Uses a different (I assume newer) undocumented API structure - it actually uses a mix of new and old for different operations, currently
> * Newer API requires the `unit` value to be like `1/d/{project}/{user}/`
> * If you provide an old-API style unit it returns this error:
> 
> ```
> INVALID_ARGUMENT: quota unit must start with '1/'.
> ```
> 
> It may be premature to update the provider to the undocumented API structure, but I can update the provider's documentation to make the different unit formats clearer to understand.

Thank you for this clarification @SarahFrench 🙏
I will keep my eye out for the new changes to the provider.

**Comment by pfilourenco** [comment]
> @pfilourenco Does the above advice from @/karan-kaushik solve your problem?

Yes, it works.

Thanks for the support @SarahFrench  and @karan-kaushik .
