### ISSUE TITLE
Failed to install provider

### ISSUE THREAD

**Issue by mrondael1** [hashicorp/terraform-provider-google#12250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
 1.0.11

### Affected Resource(s)

errors during a terraform init

* google_XXXXX

### Terraform Configuration Files

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.52.0"
    }
  }

  required_version = "= 1.0.11"
}

terraform {
    backend "gcs" {
        bucket = "tf-statefiles-psgcplab" 
        prefix = "gke-cluster-cluster02-uswest1-state" #creates a new folder
    }
}

### Expected Behavior

Succesful loading of plugins and a completed init

### Actual Behavior
Initializing modules...

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/google-beta...
- Finding hashicorp/google versions matching "4.31.0"...
- Installing hashicorp/google-beta v4.31.0...
- Installing hashicorp/google v4.31.0...
- Installed hashicorp/google v4.31.0 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/google-beta v4.31.0: open
│ .terraform\providers\registry.terraform.io\hashicorp\google-beta\4.31.0\windows_amd64\terraform-provider-google-beta_v4.31.0_x5.exe: The system cannot find the path specified.

### Steps to Reproduce

run terraform init

### Important Factoids

I need to be able to run using terraform 1.0.11

I do see the following directory created but it is empty....
C:\Users\mrondael\Desktop\mygithub projects\multicloud-platform-master\multicloud-platform-master\gcp-gke\terraform\uswest1\2-gke-cluster\.terraform\providers\registry.terraform.io\hashicorp\google-beta\4.31.0\windows_amd64

I'm using windows os , I tried enabling long path in regeditor but still get same error.

### References

* #0000

**Comment by SarahFrench** [comment]
Hi @mrondael1  - I noticed your [comment elsewhere](https://github.com/genesys/multicloud-platform/issues/8#issuecomment-1205099128) about how the directory structure was too long - is the issue resolved now?

**Comment by mrondael1** [comment]
Yes

**Comment by SarahFrench** [comment]
That's great, I'm glad you found the solution!

When you were experiencing the issue, did you enable any debug output by setting  the`TF_LOG` environment variable? I'm wondering if the core Terraform code currently provides logs that helped you debug this problem, or if it's something that could be added to help users in future.
