### ISSUE TITLE
Add Support for BigQuery Data Masking 

### ISSUE THREAD

**Issue by zs-codex** [hashicorp/terraform-provider-google#12269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Are there plans to provide support for [GCP BigQuery Data Masking (pre-GA)](https://cloud.google.com/bigquery/docs/column-data-masking-intro) feature?

### New or Affected Resource(s)

* \>=google_[v4.31.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.31.0)

### Potential Terraform Configuration

The BigQuery Data Policy options are available through a [REST API](https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest).

### References

* https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest
* https://cloud.google.com/bigquery/docs/column-data-masking-intro

**Comment by DrFaust92** [comment]
ill take a look into this
