### ISSUE TITLE
google_storage_bucket: Bug in string validation of name

### ISSUE THREAD

**Issue by martinzuern** [hashicorp/terraform-provider-google#12279]
As already pointed out in https://github.com/hashicorp/terraform-provider-google/pull/12183#discussion_r936482945

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Since `v4.31.0`

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "demo" {
  name          = "my-bucket_with_underscores-in-the-middle"
  location      = "EU"
  force_destroy = true

  uniform_bucket_level_access = true
}
```

### Expected Behavior

It works, the name matches the requirements:
https://cloud.google.com/storage/docs/naming-buckets

### Actual Behavior

Throws error
`Error: error: string validation failed my-bucket_with_underscores-in-the-middle`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* #12183

**Comment by edwardmedia** [comment]
@martinzuern Below fix will be available in next release

https://github.com/GoogleCloudPlatform/magic-modules/pull/6353

**Comment by hdotking** [comment]
Hey all it's been 4 days and I can't create bucket's with underscores in the name. 

Can I please have an ETA on how long this will to put this in the next release? Otherwise is there a workaround I can utilise in the meanwhile?
