### ISSUE TITLE
Kubernetes Permissions Missing when attaching a Service-Project to Shared-VPC Host-Project

### ISSUE THREAD

**Issue by uramirez-sada** [hashicorp/terraform-provider-google#12273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_shared_vpc_service_project

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

After attaching a Service Project to the Host Project (using this Resource), a GKE Cluster (within the Service-Account) should have been allowed to exist on the preconfigured Shared VPC Subnet.

### Actual Behavior

The Service Project was successfully attached to the Host Project, however the Default GKE Service Accounts were NOT automatically granted the right permissions at the Shared VPC Subnet Level & the Host Project Level. 
i.e.

---SHARED-VPC SUBNET-LEVEL IAM BINDINGS---
USER1: [SERVICE-PROJECT-NUMBER]@cloudservices.gserviceaccount.com
USER2: service-[SERVICE-PROJECT-NUMBER]@container-engine-robot.iam.gserviceaccount.com
IAM ROLE: roles/compute.networkUser

---HOST PROJECT LEVEL IAM BINDING---
USER: service-[SERVICE-PROJECT-NUMBER]@container-engine-robot.iam.gserviceaccount.com
IAM ROLE: roles/container.hostServiceAgentUser

### Steps to Reproduce

Deploy a typical shared vpc environment (with host and service projects) then try to deploy a GKE cluster (from the service project) using this Module --> https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/22.1.0/submodules/private-cluster

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@uramirez-sada when you create a service project using `google_compute_shared_vpc_service_project`, what behind the scene is the Terraform provider calls below API endpoint, nothing else. What you asked actually is done via separate calls which create IAM resources. The provider have separate resources that can help achieve them, and they are not done in one single `google_compute_shared_vpc_service_project`. Does this make sense?

https://cloud.google.com/compute/docs/reference/rest/v1/projects/enableXpnResource

**Comment by uramirez-sada** [comment]
I see.
So what's the best way to deploy GKE Clusters on a Service Project (SP), once that SP is attached to a Host Project?

If I were to perform this attachment via the GCP Console, there's a checkbox marked: "Kubernetes Engine access" that allows those deployments to be possible.

In other words, there are a few Host-Project IAM Bindings that need to be granted for the Cluster Deployment to work.
i.e. 
**{SERVICE_PROJECT_ID}@cloudservices.gserviceaccount.com**  --GRANT--> 'roles/compute.networkUser'
**service-{SERVICE_PROJECT_ID}@container-engine-robot.iam.gserviceaccount.com**  --GRANT-->  'roles/compute.networkUser'
**service-{SERVICE_PROJECT_ID}@container-engine-robot.iam.gserviceaccount.com**  --GRANT--> 'roles/container.hostServiceAgentUser'

Is there any way to bake it into the same provider that performs the service-project attachment?

**Comment by edwardmedia** [comment]
@uramirez-sada You can use [google_project_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_member) to create the IAMs at the project level. Make sense?

**Comment by edwardmedia** [comment]
@uramirez-sada closing this issue now. Please reopen if you still see an issue

**Comment by uramirez-sada** [comment]
We are currently using: 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_shared_vpc_service_project
to attach a service project to a host project.

If we were to execute this same attachment process, via the GCP console, there's a checkbox that automates this IAM Binding we're speaking of.

So is there a way to achieve the same, here, using this resource? (i.e. `google_compute_shared_vpc_service_project`)
Maybe by adding an Argument like: `kubernetes_engine_access` = `true`?
