### ISSUE TITLE
validate doesn't accept uniform_bucket_level_access 

### ISSUE THREAD

**Issue by vancleimatheus** [hashicorp/terraform-provider-google#12281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v3.5.0

### Affected Resource(s)

google cloud storage

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.5.0"
    }
  }
}

provider "google" {
  credentials = file(var.credentials_file)

  project = var.project
  region  = var.region
  zone    = var.zone
}

resource "google_storage_bucket" "static-site" {
  name          = "${var.project}-terraform-bucket"
  location      = "US"
  force_destroy = true

  uniform_bucket_level_access = true

  website {
    main_page_suffix = "index.html"
    not_found_page   = "404.html"
  }
  cors {
    origin          = ["http://image-store.com"]
    method          = ["GET", "HEAD", "PUT", "POST", "DELETE"]
    response_header = ["*"]
    max_age_seconds = 3600
  }
}
```

### Debug Output

https://gist.github.com/vancleimatheus/bb13c064183fb7bc764b4344f07a995c

### Expected Behavior

A new bucket should be created

### Actual Behavior

Error was thrown

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

I'm able to create compute intances, vpcs, but a policy requires the bucket to have uniform_bucket_level_access, when I try to run basically the same code from the doc it doesn't work.

I had found that someone else already had this problem before:
https://github.com/hashicorp/terraform-provider-google/issues/7238

But the issue is locked

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#example-usage---creating-a-private-bucket-in-standard-storage-in-the-eu-region-bucket-configured-as-static-website-and-cors-configurations

* #0000

**Comment by edwardmedia** [comment]
@vancleimatheus can you try the latest version of the provider to see if that wrks for you?

**Comment by edwardmedia** [comment]
@vancleimatheus here is the version for the provider https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.31.0

Looks like you pinned the version in your [code](https://github.com/hashicorp/terraform-provider-google/issues/12281#issue-1332448201)

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.5.0"
    }
  }
}
```

**Comment by vancleimatheus** [comment]
@edwardmedia  my bad, you're correct. Upgrading to v4.31.0 worked fine, thanks
