### ISSUE TITLE
Set Firestore database mode

### ISSUE THREAD

**Issue by AdamMAtWork** [hashicorp/terraform-provider-google#12294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Firestore is a component of Firebase. Firestore supports two modes of operation: Native and Datastore.  The current `google_firebase_project` resource does not support specifying the Firestore mode.  Since the mode cannot be changed after data is added, it's important to get this setting correct as soon as Firestore is enabled for the project.

There are 2 problems with the current implementation of `google_firebase_project`:
1.  It does not support specifying the Firestore mode
2. It creates Firestore in Datastore mode.  A separate call using gcloud or the REST api is required to set Native mode.

The `google_firebase_project` resource should support specifying the Firestore mode (or some other method of specifying the firestore mode should be added)

The default Firestore mode should be "Native", since Datastore mode is going away.

### New or Affected Resource(s)

* google_app_engine_application

### Potential Terraform Configuration

```tf
resource "google_firebase_project" "immutable" {
  project  = "my_firebase_project"
  firestore_mode = "native"

  lifecycle {
    ignore_changes = [ firestore_mode ]
  }
}
```

OR, as a boolean option:

```tf
resource "google_firebase_project" "immutable" {
  project  = "my_firebase_project"
  firestore_native_mode = true

  lifecycle {
    ignore_changes = [ firestore_native_mode ]
  }
}
```

### References

https://cloud.google.com/datastore/docs/firestore-or-datastore
b/277382009

**Comment by tylerg-dev** [comment]
Firestore mode is not managed as part of the FirebaseProject.  The current way to manage this is through [app_engine_application#database_type
](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_application#database_type)
