### ISSUE TITLE
GCS - Custom Dual Region is not functioning thru Terraform as expected

### ISSUE THREAD

**Issue by vnachimu** [hashicorp/terraform-provider-google#12291]
### TL;DR

Terraform provider is NOT supporting to create a custom dual-region GCS bucket using location field.  It works just fine with Google's predefined dual-regions - NAM4, ASIA1, EUR4.  When you create a custom-dual region with a location field as US-CENTRAL1+US-EAST1, the terraform state stores the location as US. When we make an update to the bucket next time, there is a mismatch between code and state file, which forces the deployment to be recreated like force replacement.

However, both console and gcloud work fine without any issues. Google handles dual-regions something like this in gcloud-gsutil.

gsutil mb -l MULTI-REGION --placement REGION_1,REGION_2 gs://BUCKET_NAME/

There is an option / switch called "placement" where you can specify the dual-region info. Once the bucket has created, the backend data has been stored as below.

gs://my-bucket/ :
  Storage class:              STANDARD
  Location type:              dual-region
  Location constraint:        US
  Placement locations:        [`US-CENTRAL1`, `US-WEST1`]

GCS Terraform is not offering this switch "placement" to specify 2 regions to create a bucket. Therefore, we pass dual-region info like this,

location = US-CENTRAL1+US-EAST1

### Expected behavior

When we create a bucket, there should be an option to say the placement locations info in terraform resource. Something like below.

resource "google_storage_bucket" "auto-expire" {
  name          = "auto-expiring-bucket"
  location      = "US"
  placement = [`US-CENTRAL1`, `US-WEST1`]
}

### Observed behavior

In the current GCS resource of Terraform, we pass dual-region info like below.

resource "google_storage_bucket" "auto-expire" {
  name          = "auto-expiring-bucket"
  location      = "US-CENTRAL1+US-EAST1"
}

### Terraform Configuration

```hcl
resource "google_storage_bucket" "auto-expire" {
  name          = "auto-expiring-bucket"
  location      = "US-CENTRAL1+US-EAST1"
  force_destroy = true
}
```

### Terraform Version

```sh
hashicorp/google v4.31.0
```

### Additional information

None

**Comment by vnachimu** [comment]
Refer to this issue for additional information. [182](https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/182)

**Comment by edwardmedia** [comment]
@vnachimu I do see [Dual-region storage](https://cloud.google.com/storage/docs/dual-regions#availability) is available in the API but this is the feature the provider has not implemented. Can you create an enhancement using below link so it can be added in the backlog? Closing this issue then

https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md
