### ISSUE TITLE
Why there is no resource type of `google_vertex_ai_featurestore_entity_feature` 

### ISSUE THREAD

**Issue by bubu1225** [hashicorp/terraform-provider-google#12306]
I can see there are resources of [google_vertex_ai_featurestore](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore) and [google_vertex_ai_featurestore_entitytype](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype). But I can't find the resource of `featurestore_entity_feature`, which is used to create the feature of the entity type based on [GCP doc](https://cloud.google.com/vertex-ai/docs/featurestore/managing-features).   Without this, I can't create the features then even the entity type is created, I believe I still can't use this entity type

Any idea why ? Or when will it be available ?  

Thanks in advance.

**Comment by edwardmedia** [comment]
@bubu1225 it is not implemented yet. Go ahead to create an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) so it will be added into the backlog.

https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featurestores.entityTypes.features

**Comment by bubu1225** [comment]
Thank you @edwardmedia. Will do.
