### ISSUE TITLE
Add support `google_vertex_ai_featurestore_entity_feature`

### ISSUE THREAD

**Issue by bubu1225** [hashicorp/terraform-provider-google#12307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resources of [google_vertex_ai_featurestore](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore) and [google_vertex_ai_featurestore_entitytype](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype) for [Vertex AI Feature Store](https://cloud.google.com/vertex-ai/docs/featurestore) are available. But the resource of `featurestore_entity_feature`, which is used to create the feature of the entity type based on [GCP doc](https://cloud.google.com/vertex-ai/docs/featurestore/managing-features) is not implemented. Without this, the user can't create the features then even the entity type is created.

### New or Affected Resource(s)

* google_vertex_ai_featurestore_entity_feature

### References

[Feature Store Managing Features](https://cloud.google.com/vertex-ai/docs/featurestore/managing-features)

**Comment by shotarok** [comment]
We merged https://github.com/GoogleCloudPlatform/magic-modules/pull/6568 to support `google_vertex_ai_featurestore_entity_feature`, and we promoted it to GA in  https://github.com/GoogleCloudPlatform/magic-modules/pull/6565. I think we can close this issue.

**Comment by shotarok** [comment]
@c2thorn I saw you added this issue to the milestone: Goal. if the previous comment looks good, could you please close this issue? thanks!
