### ISSUE TITLE
Discontiguous multi-Pod CIDR for GKE node pools

### ISSUE THREAD

**Issue by sahmadov** [hashicorp/terraform-provider-google#12315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the event that there are insufficient IP addresses, GCP offers support for discontiguous multi-Pod CIDR, which enables users to avoid having to recreate their cluster. Currently, Google Cloud CLI version 353 or later supports the changes however it is not possible to request it through terraform. More details about multi-Pod CIDR can be found in [official documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr). 

### New or Affected Resource(s)

* google_container_cluster and google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "np" {
  name       = "my-node-pool"
  cluster    = google_container_cluster.primary.id
  pod_ipv4_range{
  	name = "my-range"
  	range = "10.100.0.0/16"
  }
}
```
AND
```tf
resource "google_container_node_pool" "np" {
  name       = "my-node-pool"
  cluster    = google_container_cluster.primary.id
  create_pod_ipv4_range{
  	name = "other-range"
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr
* https://cloud.google.com/sdk/gcloud/reference/container/node-pools/create

**Comment by cagataygurturk** [comment]
Hi @sahmadov, what you are trying to achieve is possible via `container_node_pool.network_config` attribute: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#network_config

**Comment by sahmadov** [comment]
Thanks @cagataygurturk after following the link you provided I found it here. 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#network_config
