### ISSUE TITLE
Document the Forwarding Rule Usage for PSC

### ISSUE THREAD

**Issue by danistrebel** [hashicorp/terraform-provider-google#12326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The forwarding rule implementation currently requires an empty string for `load_balancing_scheme` when used with a target of type service attachment. 

It would be good to document this use case explicitly.

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_compute_forwarding_rule" "default" {
  project               = module.project.project_id
  name                  = "endpoint-attachment"
  region                = var.region
  load_balancing_scheme = ""
  target                = module.foo.service_attachment.self_link
  network               = module.my-vpc.network.id
  ip_address            = module.my-addresses.endpoint_address.self_link
}

```

### References

* #0000

b/314617050

**Comment by c2thorn** [comment]
@danistrebel Can you explain a bit more about what you are looking for?

**Comment by danistrebel** [comment]
Thanks @c2thorn. 

The list of examples here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule currently doesn't include an example where the forwarding rule is pointing to a target that is a PSC service attachment.

For that the load balancing scheme needs to be set to `load_balancing_scheme = ""` as shown in the tf snippet above.

Does that help?

**Comment by c2thorn** [comment]
Yes it does, thank you. If you are interested in taking a stab at it yourself, we have documentation available for it: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1#testing

Otherwise, it'll be a bit before it is picked up by someone directly.

**Comment by danistrebel** [comment]
@rileykarson do you think it should be? 

In my view the dependency is Forwarding Rule => Service Attachment and a service attachment could also be used by another PSC consumer like a [PSC NEG].(https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#example-usage---region-network-endpoint-group-psc).

**Comment by rileykarson** [comment]
Either one is fine- it's probably just documented the way it is because Forwarding Rule predates Service Attachment

**Comment by pawelJas** [comment]
@danistrebel I can that docs were updated and tests added. Could we close this thread now?

**Comment by pawelJas** [comment]
Here are the examples: https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fmagic-modules%20load_balancing_scheme%20%3D%20%5C%22%5C%22&type=code
