### ISSUE TITLE
Provisioning firebase.googleapis.com succeeds only on second try

### ISSUE THREAD

**Issue by rainshen49** [hashicorp/terraform-provider-google#12334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.32.0
+ provider registry.terraform.io/hashicorp/google-beta v4.32.0
```

### Affected Resource(s)

* google_project
* google_project_service
* google_firebase_project

### Terraform Configuration Files

```tf
locals {
  project              = "lingkai-firebase-tf-2"
  project_display_name = "Lingkai Terraform Project 2"


  folder_id            = "1095975223327"
  location_id          = "us-central"
  region               = "nam5"
  zone                 = "us-central1-c"
}

locals {
  apis = toset([
    "serviceusage.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "firebase.googleapis.com",
    "identitytoolkit.googleapis.com",
    "firebaserules.googleapis.com",
    "firebasehosting.googleapis.com",
    "firestore.googleapis.com"
  ])
}

resource "google_project" "default" {
  provider   = google
  name       = local.project_display_name
  project_id = local.project
  folder_id  = local.folder_id
}

resource "google_project_service" "services" {
  provider = google
  project  = google_project.default.project_id
  for_each = local.apis
  service  = each.key
}

resource "google_firebase_project" "firebase" {
  provider     = google-beta
  project      = google_project.default.project_id
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">=4.0.0"
    }
  }
}

provider "google" {
  project = "lingkai-tf-creator" // Need a project with billing
  region  = local.region
  zone    = local.zone
}

provider "google-beta" {
  project               = "lingkai-tf-creator"
  region                = local.region
  zone                  = local.zone
  user_project_override = true
}
```

`lingkai-tf-creator` is a billing enabled project with required services enabled to provision new projects.

### Debug Output

https://gist.github.com/rainshen49/7515d65c9b9010b0f3f0999e565be7d5

### Expected Behavior

The provisioning of the new project and its services should be successful on first attempt.

### Actual Behavior

Failed on first attempt, but tried `terraform apply` again and succeeded. The failure on first attempt is

```
 Error: Error creating Project: googleapi: Error 403: Firebase Management API has not been used in project 212494890142 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebase.googleapis.com/overview?project=212494890142 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/firebase.googleapis.com/overview?project=212494890142"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/212494890142",
      "service": "firebase.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
```

When I visit this link, the API is already enabled.

### Steps to Reproduce

1.`terraform apply` -- fails
2. `terraform apply` -- succeeds

### Important Factoids

I was authenticated as a user (not service account)

**Comment by edwardmedia** [comment]
@rainshen49 below is from api in the error message. Some apis might need to do extra work even after it reports to client the enabling is complete. This looks like the case. To workaround, you may add [sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) logic between the resources. Do this make sense?

```
If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by tylerg-dev** [comment]
This is basically the same issue as: 
https://github.com/hashicorp/terraform-provider-google/issues/11020
https://github.com/hashicorp/terraform-provider-google/issues/11023
https://github.com/hashicorp/terraform-provider-google/issues/11465

**Comment by rainshen49** [comment]
Yup, added a 10 sec delay fixes the issue.

```
# Give some time for newly provisioned services to settle before calling
resource "time_sleep" "wait_10_seconds_for_services" {
  depends_on = [google_project_service.services]

  create_duration = "10s"
}

resource "google_firebase_project" "firebase" {
  depends_on = [time_sleep.wait_10_seconds_for_services]
  provider     = google-beta
  project      = google_project.default.project_id
}
```

I'm pretty sure there is no extra work during the provisioning of `firebase.googleapis.com`. This can work, but is not great. Thanks Edward!
