### ISSUE TITLE
GCP AutoPilot cluster has no nodes?

### ISSUE THREAD

**Issue by jcquiles** [hashicorp/terraform-provider-google#12331]
Hello, 

I recently built a GCP Autopilot cluster with Terraform. The cluster seems fine but when running `kubectl get nodes` nothing appears. The UI says there are nodes but kubectl is saying other wise. Is there something I can do to get the nodes going? Here is the output. Thank you! 

```
`➜  autopilot git:(main) ✗ kubectl cluster-info
W0817 15:11:45.881309   73848 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Kubernetes control plane is running at https://35.190.224.123
GLBCDefaultBackend is running at https://35.190.224.123/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
KubeDNS is running at https://35.190.224.123/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
KubeDNSUpstream is running at https://35.190.224.123/api/v1/namespaces/kube-system/services/kube-dns-upstream:dns/proxy
Metrics-server is running at https://35.190.224.123/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
➜  autopilot git:(main) ✗ kubectl get nodes -o wide
W0817 15:12:10.451256   73878 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
No resources found`
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@jcquiles can you share your config that created the autopilot, along with the debug log?

**Comment by jcquiles** [comment]
This is the configuration file I used to create the cluster along with the variables needed here. 

```
# GKE cluster
resource "google_container_cluster" "primary" {
  name     = "${var.project_id}-gke"
  location = var.region
 
  network    = google_compute_network.vpc.name
  subnetwork = google_compute_subnetwork.subnet.name
 
# Enabling Autopilot for this cluster
  enable_autopilot = true
}
```

**Comment by jcquiles** [comment]
Here is the `node_pool` looks empty 

```
    node_pool {
        initial_node_count  = 1
        instance_group_urls = []
        max_pods_per_node   = 32
        name                = "default-pool"
        node_count          = 0
        node_locations      = [
            "asia-northeast1-b",
            "asia-northeast1-c",
        ]
        version             = "1.22.10-gke.600"

        autoscaling {
            max_node_count = 1000
            min_node_count = 0
        }
```

**Comment by edwardmedia** [comment]
@jcquiles I guess this is expected as the nodes for autopilot are fully managed by GCP. Below is the doc that explains. Can you share docs that support what you expect? Anyway, this is the GKE/autopilot behavior. I think there is little the provider can do based on the terraform execution was successful. Let me know if you think otherwise  

https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#comparison

**Comment by edwardmedia** [comment]
@jcquiles isn't the warning you mentioned above from kubectl? Can you try to follow whatever the link provides to see if the warning can be resolved?

I think all these are beyond the provider. Do you have other questions / issues?

**Comment by edwardmedia** [comment]
@jcquiles closing this now. Feel free to reopen if you have more questions about this
