### ISSUE TITLE
│ There is no variable named "var". when implementing dynamic blocks for google_compute_region_instance_group_manager

### ISSUE THREAD

**Issue by ac185391** [hashicorp/terraform-provider-google#12342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2
- provider google-beta v4.30.0

### Affected Resource(s)

google_compute_region_instance_group_manager

* google_XXXXX

### Terraform Configuration Files

```tf

resource "google_compute_region_instance_group_manager" "mig" {
  provider           = google-beta
  name               = var.name
  base_instance_name = var.base_instance_name
  region             = var.region

  dynamic "version" {
    for_each = { for k, v in var.versions : k => v }
    content {
      name              = versions.value.name
      instance_template = versions.value.instance_template
      dynamic "target_size" {
        for_each = versions.value.set_target_size == true ? ["true"] : []
        content {
          fixed   = versions.value.percent == null ? versions.value.fixed : null
          percent = versions.value.fixed == null ? versions.value.percent : null
        }
      }
    }
  }

  description = var.description
  dynamic "named_port" {
    for_each = { for k, v in var.named_port : k => v }
    content {
      name = named_port.value.name
      port = named_port.value.port
    }
  }
  project                   = var.project
  target_size               = var.target_size
  target_pools              = var.target_pools
  wait_for_instances        = var.wait_for_instances
  wait_for_instances_status = var.wait_for_instances_status

  dynamic "auto_healing_policies" {
    for_each = var.set_auto_healing_policies == true ? ["true"] : []
    content {
      health_check      = var.health_check
      initial_delay_sec = var.initial_delay_sec
    }
  }

  dynamic "all_instances_config" {
    for_each = var.set_all_instances_config == true ? ["true"] : []
    content {
      metadata = var.metadata
      labels   = var.labels
    }
  }
  dynamic "update_policy" {
    for_each = var.set_update_policy == true ? ["true"] : []
    content {
      minimal_action                 = var.minimal_action
      most_disruptive_allowed_action = var.most_disruptive_allowed_action
      type                           = var.type
      instance_redistribution_type   = var.instance_redistribution_type
      max_surge_fixed                = var.max_surge_percent == null ? var.max_surge_fixed : null
      max_surge_percent              = var.max_surge_fixed == null ? var.max_surge_percent : null
      max_unavailable_fixed          = var.max_unavailable_fixed
      replacement_method             = var.replacement_method
    }
  }

  distribution_policy_zones        = var.distribution_policy_zones
  distribution_policy_target_shape = var.distribution_policy_target_shape

  dynamic "stateful_disk" {
    for_each = var.set_stateful_disk == true ? ["true"] : []
    content {
      device_name = var.device_name
      delete_rule = var.delete_rule
    }
  }

}

-----------------------vars in error------------------------
variable "versions" {
  type = list(object({
    name              = string,
    instance_template = string,
    set_target_size   = bool,
    fixed             = number,
    percent           = number
  }))
  description = "Application versions managed by this instance group."
}

variable "named_port" {
  type = list(object({
    name = string,
    port = string
  }))
  description = "The named port configuration."
  default = [{
    name = null
    port = null
  }]
}

variable "set_auto_healing_policies" {
  type        = bool
  description = "set auto healing policies."
  default     = false
}

variable "set_all_instances_config" {
  type        = bool
  description = "set all instance config."
  default     = false
}

variable "set_update_policy" {
  type        = bool
  description = "set update policy."
  default     = false
}

variable "set_stateful_disk" {
  type        = bool
  description = "set stateful disk."
  default     = false
}

```

### Debug Output

 Error: Insufficient version blocks
│ 
│   on main.tf line 1, in resource "google_compute_region_instance_group_manager" "mig":
│    1: resource "google_compute_region_instance_group_manager" "mig" {
│ 
│ At least 1 "version" blocks are required.
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 8, in resource "google_compute_region_instance_group_manager" "mig":
│    8:     for_each = { for k, v in var.versions : k => v }
│ 
│ There is no variable named "var".
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 13, in resource "google_compute_region_instance_group_manager" "mig":
│   13:         for_each = versions.value.set_target_size == true ? ["true"] : []
│ 
│ A managed resource "versions" "value" has not been declared in the root module.
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 24, in resource "google_compute_region_instance_group_manager" "mig":
│   24:     for_each = { for k, v in var.named_port : k => v }
│ 
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 37, in resource "google_compute_region_instance_group_manager" "mig":
│   37:     for_each = var.set_auto_healing_policies == true ? ["true"] : []
│ 
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 45, in resource "google_compute_region_instance_group_manager" "mig":
│   45:     for_each = var.set_all_instances_config == true ? ["true"] : []
│ 
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 52, in resource "google_compute_region_instance_group_manager" "mig":
│   52:     for_each = var.set_update_policy == true ? ["true"] : []
│ 
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│ 
│   on main.tf line 69, in resource "google_compute_region_instance_group_manager" "mig":
│   69:     for_each = var.set_stateful_disk == true ? ["true"] : []
│ 
│ There is no variable named "var".

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
@ac185391 I am not sure how I can help here. Do you receive them in the plan? I guess this is a question more about how to code the terraform config than an issue with the provider. To repro an issue with provider, I need all the data (vs. vars). Could you provide?

**Comment by ac185391** [comment]
sure. So what do you need, I have provided the code above as well as the variables throwing the error, do you need the rest of the variables and tfvars file for this?

**Comment by edwardmedia** [comment]
@ac185391 to repro, replace all variables with the data so I can run directly.

**Comment by ac185391** [comment]
I am only providing the below values, the rest are all default.
project            = "xyz"
region             = "us-central1"
name               = "test"
base_instance_name = "tf_test"
versions = [
  {
    name              = null,
    instance_template = "projects/xyz/global/instanceTemplates/test-instance-template",
    set_target_size   = false,
    fixed             = null,
    percent           = null
}]

/Users/ac185391/NCR/Terraform/sreg-gcp-modules/modules/managed_instance_group/variables.tf

Again, I know the dynamic blocks should work as I have been using them like this for most of my terraform. The problem is again the error message. It doesn't actually tell me anything

**Comment by edwardmedia** [comment]
@ac185391 Those error messages are not from the provider. I guess you better file a question or bug at the Terraform SDK to see if they can help.

**Comment by edwardmedia** [comment]
@ac185391 closing this now. Feel free to reopen if you want to continue the conversation
