### ISSUE TITLE
google_clouddeploy_target is created in google but not present in the terraform state 

### ISSUE THREAD

**Issue by Lindblomsebastian** [hashicorp/terraform-provider-google#12346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```bash
terraform -v
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.32.0
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
```

### Affected Resource(s)

* `google_clouddeploy_target`

### Terraform Configuration Files

```tf
resource "google_clouddeploy_target" "test" {
  for_each = local.environments.test.envs
  project = data.google_project
  location = local.location
  require_approval = false
  name = "${each.key}-${local.service_id}"
  description = "Target for ${local.service_name} in ${each.key}"
  labels = merge({
    env: each.key
  }, local.labels)

  execution_configs {
    usages = ["RENDER", "DEPLOY"]
    service_account = google_service_account.test_cd[each.key].email
  }

  gke {
    cluster = local.environments.test.cluster
    internal_ip = true
  }
  depends_on = [google_service_account.test_cd]
}

resource "google_clouddeploy_target" "prod" {
  for_each = local.environments.prod.envs
  project = local.project
  location = local.location
  require_approval = true
  name = "${each.key}-${local.service_id}"
  description = "Target for ${local.service_name} in ${each.key}"
  labels = merge({
    env: each.key
  }, local.labels)

  execution_configs {
    usages = ["RENDER", "DEPLOY"]
    service_account = google_service_account.prod_cd[each.key].email
  }

  gke {
    cluster = local.environments.prod.cluster
    internal_ip = true
  }
  depends_on = [google_service_account.prod_cd]
}

resource "google_service_account" "test_cd" {
  for_each = local.environments.test.envs
  account_id   = "${each.value}-${local.service_id}-cd"
  display_name = "${title(each.value)} ${local.service_name} Cloud Deploy"
  project = local.project
}

resource "google_service_account" "prod_cd" {
  for_each = local.environments.prod.envs
  account_id   = "${each.value}-${local.service_id}-cd"
  display_name = "${title(each.value)} ${local.service_name} Cloud Deploy"
  project = local.project
}

data "google_container_cluster" "prod-cluster" {
  name = "prod"
  location = var.GCP_ZONE
}

data "google_container_cluster" "test-cluster" {
  name = "test"
  location = var.GCP_ZONE
}

data "google_project" "project" {
}

locals {
  project = data.google_project
  location = "europe-west1"
  service_name = "Service Name"
  service_id = "service_id"
  labels = {
    service: "service_id"
  }
  environments = {
    test: {
      cluster = data.google_container_cluster.prod-cluster.id
      envs: ["test"]
    }
    prod: {
      cluster = data.google_container_cluster.test-cluster.id
      envs: ["prod"]
    }
  }
  all_environments = setunion(local.environments.prod.envs, local.environments.test.envs)
}
```

### Debug Output

I can't debug, as the apply is running in Terraform Cloud. The plan works great though

### Expected Behavior

There should be multiple `google_clouddeploy_target` resources, i.e `google_clouddeploy_target.test[each.key]` and `google_clouddeploy_target.prod[each.key]`

### Actual Behavior

Only the `google_clouddeploy_target.test[each.key]` is created in the terraform state. For `google_clouddeploy_target.prod` I'm getting 
```log
Error: Error creating Target: Resource already exists - apply blocked by lifecycle params: &clouddeploy.Target{Name:(*string)(0xc000b66c60), TargetId:(*string)(nil), Uid:(*string)(0xc000aa6790), Description:(*string)(0xc000b66d60), Annotations:map[string]string{}, Labels:map[string]string{"app":"signal-service", "env":"prod", "team":"workflow"}, RequireApproval:(*bool)(0xc00148c847), CreateTime:(*string)(0xc000aa67b0), UpdateTime:(*string)(0xc000aa67c0), Gke:(*clouddeploy.TargetGke)(0xc0005f8fd8), AnthosCluster:(*clouddeploy.TargetAnthosCluster)(nil), Etag:(*string)(0xc000aa6800), ExecutionConfigs:[]clouddeploy.TargetExecutionConfigs{clouddeploy.TargetExecutionConfigs{empty:false, Usages:[]clouddeploy.TargetExecutionConfigsUsagesEnum{"RENDER", "DEPLOY"}, WorkerPool:(*string)(nil), ServiceAccount:(*string)(0xc000b66f80), ArtifactStorage:(*string)(0xc000aa6870)}}, Project:(*string)(0xc000b67370), Location:(*string)(0xc000b66c20)}.
```

BUT the resource is created in Google. I can see the resource using `gcloud deploy targets list --region <region> --project <project>`

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@Lindblomsebastian the error is clear but I can't tell which resource. With all the variables, I can't repro. Are you able to replace all vars with data so I can repro?

```
Resource already exists
```

**Comment by Lindblomsebastian** [comment]
> @Lindblomsebastian the error is clear but I can't tell which resource. With all the variables, I can't repro. Are you able to replace all vars with data so I can repro?
> 
> ```
> Resource already exists
> ```

Hi, thanks for looking into it. I've updated the initial post with an updated version

**Comment by edwardmedia** [comment]
@Lindblomsebastian I can't repro the issue. All resources were created successfully, and did not hit `Resource already exists` error. 

Here is a similar issue https://github.com/hashicorp/terraform-provider-google/issues/10934

**Comment by edwardmedia** [comment]
@Lindblomsebastian is this still an issue?

**Comment by Lindblomsebastian** [comment]
> @Lindblomsebastian is this still an issue?

I deleted the resource using `gcloud` and was able to create it with a second terraform apply run. I haven't have the time to try it again. I'll close this and re-open if this issue pops up again.
