### ISSUE TITLE
Unable to deploy `google_compute_instance` when a NAT IP address is associated

### ISSUE THREAD

**Issue by saidi-adam** [hashicorp/terraform-provider-google#12353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version 1.1.3

### Affected Resource(s)

`google_compute_instance` + `google_compute_address`

### Terraform Configuration Files

```
resource "google_compute_address" "cloud_sql_proxy_host_vpc_ip" {
  provider     = google-beta.network-host-project
  name         = "cloud-sql-proxy-host-corp-vpc-ip"
  address_type = "EXTERNAL"
  network_tier = "PREMIUM"
  project      = var.network_project_id
  region       = var.gcp_region
}

resource "google_compute_instance" "cloud_sql_proxy_host_vpc" {
  provider                  = google-beta.network-host-project
  name                      = "cloud-sql-proxy-host-corp-vpc"
  machine_type        = "e2-medium"
  zone                      = "${var.gcp_region}-d"
  project                   = module.gcp-project.project_id
  allow_stopping_for_update = true

  tags = ["cloud-sql-proxy", var.stage]

  metadata = {
    ssh-keys               = "xxxxxxxxx"
    block-project-ssh-keys = true
  }

  boot_disk {
    initialize_params {
      image = "centos-cloud/centos-7-v20220719"
    }
  }

  network_interface {
    subnetwork         = google_compute_subnetwork.corp_access_vpc_subnetwork_01.name
    subnetwork_project = var.network_project_id
    access_config {
      nat_ip = google_compute_address.cloud_sql_proxy_host_vpc_ip.address
    }
  }

  metadata_startup_script = templatefile("./assets/cloud_sql_proxy.sh", {
    db_connection_name = "${module.mysql.connection_name}"
  })

  service_account {
    email  = google_service_account.cloud_sql_proxy.email
    scopes = ["cloud-platform"]
  }
}

resource "google_compute_firewall" "cloud_sql_proxy" {
  name    = "cloud-sql-proxy-ssh-firewall"
  network = "xxxxxxx"
  project = var.network_project_id
  target_tags = [
    "cloud-sql-proxy",
  ]

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = var.ip_ranges
}
```

### Debug Output

│ Error: Error creating instance: googleapi: Error 503: Internal error. Please try again or contact Google Support. (Code: '5E6D24F3DF838.1304663.8D039A1F'), backendError

### Expected Behavior

The deployment of the GCE instance into the chosen GCP project. 

### Actual Behavior

Had a HTTP503 error returned. I was able to go round this by commenting out the NAT IP configuration for the `google_compute_instance` which led to a successful Terraform apply, and then i uncommented out the config and applied successfully, but was unable to deploy the `google_compute_instance` whilst associated to the `google_compute_address`

**Comment by edwardmedia** [comment]
@saidi-adam this is likely a temporary API issue. We have below test code that runs fine. Can you re-try? If the issue remains, could you share the debug log? 

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_instance_test.go#L3372

**Comment by saidi-adam** [comment]
Hi @edwardmedia im unable to share the debug logs because they're very long (we have a large project) and also, they contain sensitive values too... is there another way? I've been deploying the VM instances by commenting out the nat ip reference so far...

**Comment by edwardmedia** [comment]
@saidi-adam have you had chance to re-run first?

**Comment by saidi-adam** [comment]
@edwardmedia I've been having this issue for about a week now and retried this morning again, getting a HTTP503 response. Are you able to replicate if you deploy a `google_compute_instance ` resource with a `google_compute_address ` instance associated via 

```
    access_config {
      nat_ip = google_compute_address.compute_address.address
    }
```

**Comment by edwardmedia** [comment]
@saidi-adam I can't replicate the problem with your code. I am not super clear what those values would be. Have you verified if the nap_ip is valid? 

It is fine with the code https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_instance_test.go#L3357

```
  project      = var.network_project_id

  provider                  = google-beta.network-host-project

  project                   = module.gcp-project.project_id

    subnetwork         = google_compute_subnetwork.corp_access_vpc_subnetwork_01.name
    subnetwork_project = var.network_project_id

```

**Comment by saidi-adam** [comment]
Hi @edwardmedia the `nat_ip` resource is valid and i've tested it elsewhere, the `project ` value is just the GCP project, whilst the other `project` being populated by the `network_project_id` is our host project - not really related afaik in this situation. 

I've tried to deploy a test instance with a `nat_ip` and it failed again with blank config...

**Comment by edwardmedia** [comment]
@saidi-adam did you deploy a test instance using above example I gave above?

**Comment by edwardmedia** [comment]
@saidi-adam is this still an issue?

**Comment by edwardmedia** [comment]
@saidi-adam closing this as I can't repro it. Please reopen this once you have the debug log to share.
