### ISSUE TITLE
Clarification that PubSub topic message retention duration can be up to 31 days

### ISSUE THREAD

**Issue by christianTNG** [hashicorp/terraform-provider-google#12355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The argument `message_retention_duration` for `google_pubsub_topic` is limited to `Cannot be more than 7 days` according to its [terraform documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic#message_retention_duration).

However the [Google Cloud documentation](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics/create#:~:text=Cannot%20be%20more%20than%2031%20days) allows for up to **31 days** since a change in December 2021. See [Google's blog post](https://cloud.google.com/blog/products/data-analytics/pubsub-launches-extended-message-storage-for-event-sourcing) for more details.

It would be very helpful to clarify the terraform documentation of `google_pubsub_topic` by including the latest change concerning the maximal duration.

### Affected Resource

* google_pubsub_topic

### References

*  #10175 added the `message retention duration` argument in the associated PR GoogleCloudPlatform/magic-modules#5347
* [Terraform Google documentation - pubsub_topic#message_retention_duration](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic#message_retention_duration)
*  [Google's blog post](https://cloud.google.com/blog/products/data-analytics/pubsub-launches-extended-message-storage-for-event-sourcing) announcing the extended message storage of up to 31 days

**Comment by c2thorn** [comment]
This should be addressed in https://github.com/GoogleCloudPlatform/magic-modules/pull/6430
