### ISSUE TITLE
apigee_endpoint_attachment - Error 400: the resource is locked by another operation

### ISSUE THREAD

**Issue by pysiok1983** [hashicorp/terraform-provider-google#12369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.2.7
Google provider - 4.32.0

### Affected Resource(s)

* google_apigee_endpoint_attachment

### Terraform Configuration Files
```
locals = {
    psc_groups = {
      psc_01 = {
        service_attachment_name = "psc1"
        service_attachment  = "projects/<proj1>/regions/us-central1/serviceAttachments/sa1"

      }
      psc_02 = {
        service_attachment_name = "psc2"
        service_attachment  = "projects/<proj2>/regions/us-central1/serviceAttachments/sa2"

      }
    }
}

resource "google_apigee_endpoint_attachment" "apigee_endpoint_attachment" {
  for_each               = local.psc_groups
  org_id                 = google_apigee_organization.org.id
  endpoint_attachment_id = each.value.service_attachemnt_name
  location               = "us-central1"
  service_attachment     = each.value.service_attachemnt
}
```

### Debug Output

│ Error: Error creating EndpointAttachment: googleapi: Error 400: the resource is locked by another operation where endpoint attachment psc1 is currently being created for organization proj1 by operation: d03e570e-56c4-4af9-85aa-c[117](https://github.com/pysiok1983/gcp-api-01/runs/7983352859?check_suite_focus=true#step:8:118)a77be7ac
│ Details:
│ [
│   ***
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "210181044925815171"
│   ***
│ ]

### Expected Behavior
Both PSCs should be created without any issues. 

### Actual Behavior

Seems that using a loop for google_apigee_endpoint_attachment causes an issue. The resource doesn't wait enough long and when the second psc is launching APIgee reports an issue. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Using -parallelism=1 solved this issue but delays the whole deployment.

### References

* #0000

**Comment by edwardmedia** [comment]
@pysiok1983 this limitation is at the API. There is little the provider can do. Does this make sense?

**Comment by pysiok1983** [comment]
Can we add a delay for each iteration within this resource?

**Comment by edwardmedia** [comment]
@pysiok1983 I don't think so. There is no need when one resource is created. When you prepare a module, that might be a good place to do. Does this make sense?

**Comment by pysiok1983** [comment]
> @pysiok1983 I don't think so. There is no need when one resource is created. When you prepare a module, that might be a good place to do. Does this make sense?

I have tested a module - same issue. 

```
 resource "time_sleep" "psc_propagation" {
   create_duration = "15s"
 }

module "psc_sb" {
    source                  = "../psc"
    for_each                = var.psc_groups
    service_attachment_name = each.value.service_attachment_name
    service_attachment      = each.value.service_attachment
    depends_on             = [ time_sleep.psc_propagation ]
}
```

**Comment by edwardmedia** [comment]
@pysiok1983 sorry, what I meant was that delay logic could be built inside a module which might handle the concurrency in multiple instances.

**Comment by pysiok1983** [comment]
> @pysiok1983 sorry, what I meant was that delay logic could be built inside a module which might handle the concurrency in multiple instances.

Are you able to provide an example?

**Comment by edwardmedia** [comment]
@pysiok1983 sorry no. This repo is for the individual resource. If there is no existing module available, you probably need to build it by yourself.

**Comment by edwardmedia** [comment]
Closing this now. @pysiok1983 feel free to reopen if you want to continue
