### ISSUE TITLE
Make downstream builders short-circuit with success if downstream commit was already built

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12360]
Currently, if a downstream builder detects that the corresponding downstream commit was already built, it will fail with an error. [Example failure](https://pantheon.corp.google.com/cloud-build/builds;region=global/bd0ec1e4-9d37-4bb1-ba8a-42c48135f410?project=graphite-docker-images)

This means that if one downstream fails due to a transient error, it has to be resolved manually instead of by clicking "retry" on the failed cloudbuild. We should instead consider the downstream builds to be idempotent - if a particular commit has already made it to a downstream, we should consider that a success, since the desired end state has been achieved.

**Comment by ScottSuarez** [comment]
related https://github.com/hashicorp/terraform-provider-google/issues/12359

**Comment by melinath** [comment]
I think this change should be fairly easy to make - a lot of the work here will be thinking through whether or not it's actually safe to do. We should also update the documentation around resolving this type of issue to reflect this change.

**Comment by melinath** [comment]
If we're also doing #11109 then this should be more clearly safe.

**Comment by rileykarson** [comment]
@trodge you'll be touching similar code in https://github.com/hashicorp/terraform-provider-google/issues/11109. If you have the time, this may be worth picking up as well.
