### ISSUE TITLE
[Bug]: google_compute_security_policy "Blocks of type "rate_limit_options" are not expected here."

### ISSUE THREAD

**Issue by jbrardport** [hashicorp/terraform-provider-google#12364]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```sh
$ terraform --version
Terraform v1.0.8
on darwin_arm64
+ provider registry.terraform.io/carlpett/sops v0.7.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/google v4.3.0
+ provider registry.terraform.io/hashicorp/google-beta v4.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

### Affected Resource(s)

* google_compute_security_policy

### Terraform Configuration Files

```tf
resource "google_compute_security_policy" "backend_policy" {
  provider    = google-beta
  name        = "${var.project_id}-security-policy"
  description = "security polcies (cloud armor) for ${var.project_id}"

  rule {
    action   = "throttle"
    preview  = true
    priority = "1000"
    description = "rate limit"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    rate_limit_options {
      conform_action = "allow"
      exceed_action = "deny(429)"
      enforce_on_key = "ALL"
      rate_limit_threshold {
        count = "200"
        interval_sec = "300"
      }
    }
  }
}
```

### Expected Behavior

Terraform plan should show resourecs affected

### Actual Behavior

```sh
╷
│ Error: Unsupported block type
│ 
│   on security-policies.tf line 17, in resource "google_compute_security_policy" "backend_policy":
│   17:     rate_limit_options {
│ 
│ Blocks of type "rate_limit_options" are not expected here.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3.  see error in stdout

### Important Factoids

Visual Studio Code terraform plugin seems to recognize the block and the block is listed in the documentation.

### References

* [rate_limit_options](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy#nested_rate_limit_options)

**Comment by jbrardport** [comment]
I'm closing this.

I see it was release in 4.10.0 and I am on 4.3.0.

In my head I was thinking I was on 4.30.0

**Comment by guidodl** [comment]
Hi, 
I am facing the same problem but in my case i am using google provider with version 4.34.0 (beta too).


Error: Unsupported block type



 on main.tf line 123, in resource "google_compute_security_policy" "policy":
123:         rate_limit_options {



Blocks of type "rate_limit_options" are not expected here.
 


Thank you for your help,
Guido
