### ISSUE TITLE
serviceExternalIpsConfig missing from google_container_cluster

### ISSUE THREAD

**Issue by BaskiGIT** [hashicorp/terraform-provider-google#12371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

google_container_cluster resource is missing the serviceExternalIpsConfig block under networkConfig.

### New or Affected Resource(s)

`google_container_cluster`

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  service_external_ips_config {
    enabled = true
  }
}
```

### References

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#networkconfig

**Comment by rileykarson** [comment]
@c2thorn to dedupe if possible

**Comment by c2thorn** [comment]
This was just added in https://github.com/GoogleCloudPlatform/magic-modules/pull/6392
