### ISSUE TITLE
[google_secret_manager_secret_iam_binding] Other roles within the IAM policy for the secret are NOT preserved.

### ISSUE THREAD

**Issue by Raffaello** [hashicorp/terraform-provider-google#12373]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.9

on linux_amd64

+ provider registry.terraform.io/hashicorp/google v4.33.0



Your version of Terraform is out of date! The latest version


is 1.2.7. You can update by downloading from https://www.terraform.io/downloads.html

```

### Affected Resource(s)

* google_secret_manager_secret_iam_binding

### Terraform Configuration Files

Having 2 terraform states within the same GCP project, to apply independently one to another, 
having each of those 1 dedicated service account, let's call them `gcp-sa-A` and `gcp-sa-B` (resource name `gcp-sa`)
applying this resource (
```tf
resource "google_secret_manager_secret_iam_binding" "fgw_secrets" {
  project  = var.project
  members = [
    "serviceAccount:${google_service_account.gcp_sa.email}",
  ]
  role      = "roles/secretmanager.secretAccessor"
  secret_id = var.secret_id
}
```

it will result in the secret manager to have the accessor to the latest applied of the 2 terraforms, for e.g.

if running terraform related to the `gcp-sa-A` first, the permissions on  GSM are ok.
Then running terraform related to the `gcp-sa-B`, the permission on GSM are only with the secret Accessor of the service account `gcp-sa-B`, **_basically it didn't preserve the other permission but merely replaced them._** 

As a per documentation: instead it shouldn't

> [google_secret_manager_secret_iam_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#google_secret_manager_secret_iam_binding): Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the secret are preserved.
ref: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam

### Expected Behavior

The expected behavior is that it won't replace the permissions members, but update/add/remove accordingly to the list specified in the terraform resource, without make any modification on the members that are not listed in the terraform resource.

### Actual Behavior

It replaces the members

### Steps to Reproduce

1. if running terraform related to the `gcp-sa-A` first, the permissions on  GSM are ok.
2. Then running terraform related to the `gcp-sa-B`, the permission on GSM are only with the secret Accessor of the service account `gcp-sa-B`, **_basically it didn't preserve the other permission but merely replaced them._** 

### References

* #0000

**Comment by edwardmedia** [comment]
@Raffaello in your test, are both config share the same role: "roles/secretmanager.secretAccessor"? How about giving one to "roles/secretmanager.admin"? Please let me know what you find.

**Comment by Raffaello** [comment]
> @Raffaello in your test, are both config share the same role: "roles/secretmanager.secretAccessor"? How about giving one to "roles/secretmanager.admin"? Please let me know what you find.

yes in my test both share the same role. 

It is working as exepcted if using `google_secret_manager_secret_iam_member` 

i have reported because either is a bug on the provider or the documentation is misleading:

> [google_secret_manager_secret_iam_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#google_secret_manager_secret_iam_binding): Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. **Other roles within the IAM policy for the secret are preserved.**
[google_secret_manager_secret_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#google_secret_manager_secret_iam_member): Non-authoritative. Updates the IAM policy to grant a role to a new member. **Other members for the role for the secret are preserved.**

as both by documentation are preserving roles, but effectively only the `google_secret_manager_secret_iam_member`  is doing that, at least in the set up to have 2 different terraform config applying to the same gcp project but with 2 dinstinct service accounts

**Comment by Raffaello** [comment]
> > @Raffaello in your test, are both config share the same role: "roles/secretmanager.secretAccessor"? How about giving one to "roles/secretmanager.admin"? Please let me know what you find.
> 
> yes in my test both share the same role.
> 
> It is working as exepcted if using `google_secret_manager_secret_iam_member`
> 
> i have reported because either is a bug on the provider or the documentation is misleading:
> 
> > [google_secret_manager_secret_iam_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#google_secret_manager_secret_iam_binding): Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. **Other roles within the IAM policy for the secret are preserved.**
> > [google_secret_manager_secret_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#google_secret_manager_secret_iam_member): Non-authoritative. Updates the IAM policy to grant a role to a new member. **Other members for the role for the secret are preserved.**
> 
> as both by documentation are preserving roles, but effectively only the `google_secret_manager_secret_iam_member` is doing that, at least in the set up to have 2 different terraform config applying to the same gcp project but with 2 dinstinct service accounts

oh i see:  

> Other roles within the IAM policy for the secret are preserved.

the role itself that is applied won't be preserved.... 
Than is no bug, I have just  been misreading the documentation all along! sorry 😄

**Comment by edwardmedia** [comment]
@Raffaello I am glad you have figured this out. Closing this issue then
