### ISSUE TITLE
Developer productivity - create two links for specific error and full test log

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#12377]
### motivation
improve time to diagnose error for external contributor

### action

It's difficult to parse a test log to figure out and diagnose an error for a contributor. The suggestion proposed is to surface that error separately and in addition to from the full log itself. Perhaps in a file or in a dropdown.

**Comment by rileykarson** [comment]
Should we make the build log more prominent?

**Comment by shuyama1** [comment]
Creating two links for VCR logs should be relatively easy based on the current setup of VCR recording tests. I could find some time to implement it this week if folks think it's more clear.

**Comment by ScottSuarez** [comment]
Thanks Shuya !! ^-^
