### ISSUE TITLE
Configure GCP's own "deletion protection" on Cloud SQL databases #12344 

### ISSUE THREAD

**Issue by multani** [hashicorp/terraform-provider-google#12372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

On [August 15th](https://cloud.google.com/sql/docs/postgres/release-notes#August_15_2022), GCP introduced their own "deletion protection" on Cloud SQL instances:

![image](https://user-images.githubusercontent.com/65311/186391755-bf58b9d6-8ea0-4de3-9b94-039e23e5b672.png)

This introduces [a new flag in the settings of an instance](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances#settings):

![image](https://user-images.githubusercontent.com/65311/186392018-467c3a46-3d52-479a-9dce-c3655e1bcb0c.png)

This flag is currently not supported by the Terraform Google provider and it's not possible to configure this behavior on Cloud SQL instances.

### New or Affected Resource(s)

* `google_sql_database_instance`

### Potential Terraform Configuration

See https://github.com/hashicorp/terraform-provider-google/issues/12344 for potential discussion about this feature, and how it to the current `deletion_protection` implemented in the provider itself.

**Comment by multani** [comment]
This is being implemented in https://github.com/GoogleCloudPlatform/magic-modules/pull/6441

**Comment by sundar-mudupalli-work** [comment]
This is mischaracterized and is a bug fix. The documentation talks about deletion protection and the provider does not work as mentioned in the documentation (i.e. does not create an instance with deletion protection turned on). Provider is unusable for a production deployment. Please reclassify and prioritize. Thanks.

**Comment by multani** [comment]
Hi @sundar-mudupalli-work ,

This has been discussed already in https://github.com/hashicorp/terraform-provider-google/issues/12344

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6441

**Comment by philip-harvey** [comment]
Awesome to see this get merged.  How can we tell when this is released into the provider?
