### ISSUE TITLE
fix TestAccComputeInstance_networkPerformanceConfig

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#12383]
### Affected Resource(s)

* google_compute_instance

```golang
	// This test /should/ be passing but the reason it's failing
	// is very non-obvious and requires further investigation
	//
	// It's been failing in teamcity for > 90d so there is no
	// starting point or obvious reason to potentially pivot off
	//
	// For whoever decides to investigate this. It looks like
	// at the time the failure is due to a failure to start
	// the compute instance after a config update. This results
	// in it /unable to find the resource/ as the start operation
	// never completes successful. I suspect a bad configuration
	// but am unsure.
```

It's possible this could be a bug and not a bad configuration. 

related: https://github.com/GoogleCloudPlatform/magic-modules/pull/6458

**Comment by mitj04** [comment]
It has a 100% passing rate for all the builds present in the TeamCity.

[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?tab=testDetails&projectId=GoogleCloudBeta&testNameId=1384792021507224348&page=2)

**Comment by roaks3** [comment]
Note for clarification: this test is passing fine in the nightly tests, but presumably fails in VCR, which is why VCR is skipped while we investigate
