### ISSUE TITLE
Events for Cloud Run for Anthos support

### ISSUE THREAD

**Issue by hrchu** [hashicorp/terraform-provider-google#12384]
I am working on provisioning a Knative eventing cluster on GKE.
Is there any way to enable GKE knative events by terraform?
https://cloud.google.com/anthos/run/archive/docs/events/quickstart#initialize-events 
I can only find `addons_config.cloudrun_config` on the reference.

**Comment by edwardmedia** [comment]
@hrchu I don't believe it is available yet. Not sure if Terraform is a right tool to build that. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) to request. Closing the question now
