### ISSUE TITLE
Detect when tests added in a PR did not run in VCR

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12380]
It would be great if the Magician could include a list of tests added in a PR that did not get run in VCR; non-VCR tests are easy to miss during review, which can cause failures in the nightly builds.

Potentially this could even include a pre-filled link for creating a non-VCR test run for the skipped tests.

**Comment by rileykarson** [comment]
How big of a problem is this? Are tests getting added w/o VCR often in your experience?

**Comment by rileykarson** [comment]
Proposal: if Go can emit the list of tests, calculate a delta between main and PR, crosscheck against the list of tests that ran
