### ISSUE TITLE
Is it possible to configure cloud run jobs through the google provider and/or is it on the roadmap?

### ISSUE THREAD

**Issue by ramonvermeulen** [hashicorp/terraform-provider-google#12399]
Hello! I was looking through he cloud run resources in the Google Provider, and couldn't find anything about the new cloud run jobs.
I was wondering if this is something which is on the roadmap to be added to the Google Provider in the near future?

**Comment by trav** [comment]
See:  #11743

**Comment by ramonvermeulen** [comment]
Cool, thanks. I'll follow that issue and close this one.
