### ISSUE TITLE
Document how to use `conflicts` in api.yaml

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12396]
Alongside the documentation for [exactly one of](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/README.md#exactly-one-of) it would be great to have docs for `conflicts:`

**Comment by SarahFrench** [comment]
Copying info from a duplicate issue (https://github.com/hashicorp/terraform-provider-google/issues/13814)

> I'm was checking the way I handle union fields is correct and started wondering about exactly_one_of versus conflicts as yaml fields for resource properties. I found some documentation about ExactlyOneOf but not conflicts.
>
>I think the difference is that conflicts is for specifying top-level properties that conflict, whereas exactly_one_of is specific to child objects inside a nested object.
>
>Existing documentation for exactly_one_of is here : https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/how-to/add-mmv1-resource.md#exactly-one-of
