### ISSUE TITLE
cloudsql instance deletion failure obsereved 

### ISSUE THREAD

**Issue by pnjha** [hashicorp/terraform-provider-google#12400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.15.5

### Provider Version
4.20.0

### Affected Resource(s)
* google_sql_database_instance
* google_sql_user
* google_sql_database

### Terraform Configuration Files

```tf
{
  "terraform": {
    "required_providers": {
      "google": {
        "source": "hashicorp/google"
      }
    }
  },
  "provider": {
    "google": {
      "project": "<redacted>",
      "credentials": "<redacted>",
      "region": "<redacted>"
    }
  },
  "resource": {
    "google_sql_database": {
      "rds_database": {
        "name": "<redacted>",
        "instance": "postgres-test1",
        "depends_on": [
          "google_sql_database_instance.rds_postgresql_instance",
          "google_sql_user.rds_user"
        ]
      }
    },
    "google_sql_database_instance": {
      "rds_postgresql_instance": {
        "name": "postgres-test1",
        "region": "<redacted>",
        "database_version": "POSTGRES_12",
        "clone": [],
        "deletion_protection": false,
        "settings": {
          "tier": "db-custom-4-16384",
          "disk_autoresize": false,
          "disk_size": 10,
          "disk_type": "PD_SSD",
          "availability_type": "REGIONAL"
        }
      }
    },
    "google_sql_user": {
      "rds_user": {
        "name": "<redacted>",
        "instance": "postgres-test1",
        "password": "<redacted>",
        "depends_on": ["google_sql_database_instance.rds_postgresql_instance"]
      }
    }
  },
  "output": {
    "self_link": {
      "value": "${google_sql_database_instance.rds_postgresql_instance.self_link}",
      "description": "Postgresql db self link."
    },
    "private_ip_address": {
      "value": "${google_sql_database_instance.rds_postgresql_instance.private_ip_address}",
      "description": "Database private ip address."
    }
  }
}

```

### Panic Output

Error: Error when reading or editing Database: googleapi: Error 400: Invalid request: failed to delete database "ImxCJPbXBIQa". Detail: pq: database "ImxCJPbXBIQa" is being accessed by other users. (Please use psql client to delete database that is not owned by "cloudsqlsuperuser")., invalid

### Expected Behavior

All the resources should have been deleted in the order dictated by the depends_on condition

### Actual Behavior

Deletion of database fails leading to failure to delete user and instance 

### Steps to Reproduce

Try creating an instance with the above terraform template and then try to delete the cloud_sql_instance via terraform.

**Comment by edwardmedia** [comment]
@pnjha looking at the repro steps, can you detail what command did you use? Just delete `google_sql_database_instance` only?

```
Try creating an instance with the above terraform template and then try to delete the cloud_sql_instance via terraform.
```

**Comment by pnjha** [comment]
@edwardmedia yes I performed `terraform destroy` on the template provided above. The issue is intermittent in my observation. So reproducing this error won't be straightforward. Since we maintain a large number of instances hence we see this error more often, but not always.
As a workaround for this issue we perform `terraform state rm` of all the resources except the`google_sql_database_instance` resource, and then trigger `terraform delete` to avoid letting terraform delete the database resource separately, and that works fine.

**Comment by edwardmedia** [comment]
@pnjha yeah maintaining a large of instances could be tricky. That is the area beyond the individual resource. Do you want to checkout [this](https://www.terraform.io/cli/commands/apply#parallelism-n) to see if that helps?

**Comment by pnjha** [comment]
@edwardmedia thanks for the suggestion, that might help but for now we already have a workaround mentioned above that should be enough to deal with this issue. From looking at the error message is it possible to figure out what might cause it?

**Comment by edwardmedia** [comment]
@pnjha not sure what exactly the error message means. When you have a large number of databases, the created sql user account is shared among the instances? Somehow I feel this is a concurrency issue. Glad you have a workaround and close the issue then. Feel free to reopen if you want to continue the conversation
