### ISSUE TITLE
Add Snapshot Chain Name Support

### ISSUE THREAD

**Issue by jesse-l** [hashicorp/terraform-provider-google#12429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding support for the chain name variable for a snapshot.  There is already support in the API for adding a chain name to both the google_compute_snapshot and adding it as a snapshot_properties of google_compute_resource_policy.  Just need to add the parameters to the objects in [magic-modules](https://github.com/GoogleCloudPlatform/magic-modules).

### New or Affected Resource(s)

* google_compute_snapshot
* google_compute_resource_policy

#### Snapshot

```terraform
resource "google_compute_snapshot" "snapshot" {
  name        = "tf-test-snapshot"
  source_disk = google_compute_disk.persistent.id
  zone        = "us-central1-a"
  chain_name  = "tf-test-snapshot-chain"
  labels = {
    my_label = "value"
  }
  storage_locations = ["us-central1"]
}
```

#### Resource Policy

```terraform
resource "google_compute_resource_policy" "hourly" {
  name   = "chain-name-scheduled-snapshot"
  region = "us-central1"
  description = "chain name snapshot"
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = 1
        start_time     = "18:00"
      }
    }
    retention_policy {
      max_retention_days    = 11
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
    snapshot_properties {
      labels = {
        my_label = "value"
      }
      storage_locations = ["us"]
      guest_flush       = true
      chain_name = "test-schedule-chain-name"
    }
  }
}
```

### References

- [Snapshot GA API Support](https://cloud.google.com/compute/docs/reference/rest/v1/snapshots)
- [Resource Policies GA API Support](https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies)

**Comment by jesse-l** [comment]
About to submit a PR for this

**Comment by AarshDhokai** [comment]
b/263774831

**Comment by AarshDhokai** [comment]
It seems like PR is merged for this issue, Hence Closing this issue.
