### ISSUE TITLE
Minor GCP getting-started guide update needed

### ISSUE THREAD

**Issue by chaseoli** [hashicorp/terraform-provider-google#12421]
# Background

Documentation needs to be updated to debian-10  given EOL error

>Error: Error resolving image name 'debian-cloud/debian-9': Could not find image or family debian-cloud/debian-9

Update docs here: https://learn.hashicorp.com/tutorials/terraform/google-cloud-platform-change?in=terraform/gcp-get-started#create-a-new-resource

# What kind of contribution is this issue about?

* Documentation update needed to GCP getting-started guide

# Related PR(s), if any:

* (same issue documented here a few years back) https://github.com/hashicorp/terraform-provider-google/issues/1862

# Details

**Comment by SarahFrench** [comment]
I've got a PR open to update the tutorial to use debain-11, just like how [a lot of acceptance tests were updated to 11](https://github.com/GoogleCloudPlatform/magic-modules/pull/6372/files) recently.

**Comment by SarahFrench** [comment]
The fix is merged and live on the tutorial page, closing
