### ISSUE TITLE
Documentation for updating `go.mod.erb`

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#12425]
# Background

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/go.mod.erb

# What kind of contribution is this issue about?

updating the go.mod is not intuitive and needs documentation

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/6432

**Comment by rileykarson** [comment]
Steps are to:

- Open up the GA provider repo and add the new entries / modify the versions of already pinned entries
- Run `go get`, `go mod tidy`
- Copy the go.mod and go.sum on top of https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/go.mod.erb and https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/go.sum

**Comment by SarahFrench** [comment]
Relevant: https://github.com/hashicorp/terraform-provider-google/wiki/FAQ#-how-do-i-update-the-go-version-used-by-the-terraform-providers-google-and-google-beta
