### ISSUE TITLE
Document what are considered breaking changes

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12420]
One of the things I most frequently have to reference is: is X a breaking change. It would be great to have a document that lays out known breakable changes in an easily-searchable way, with a brief description of why it's a breaking change and what alternatives might be available.

For example: changing default value is a breaking change. The only backwards compatible change w/ changing default values (whether adding or removing) is adding a default to a previously-Required field, or changing a field w/ a default to O+C

**Comment by ScottSuarez** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6664
