### ISSUE TITLE
Document requirement to have update tests on new resources

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12424]
New resources being added via mmv1 autogeneration need to have update tests to make sure that updating the resource works as expected. This is already documented at https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform#update-tests but it's not linked from the mmv1 docs.

**Comment by melinath** [comment]
closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12428

**Comment by melinath** [comment]
reopening - slightly different purpose

**Comment by rileykarson** [comment]
Note: This is stated at https://github.com/hashicorp/terraform-provider-google/wiki/Developer-Best-Practices#acceptance-tests, I think
