### ISSUE TITLE
Honor `async.error` settings from api.yaml in Terraform providers

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12431]
It looks like the operation error options that you can set in api.yaml don't actually get used anywhere - for example: https://github.com/GoogleCloudPlatform/magic-modules/blob/065f680d36c0a653e9d8542257d60663f96c15c5/mmv1/products/datastream/api.yaml#L40

it looks like the actually operation error just gets wrapped in CommonOpError which just always uses `e.Message`: https://github.com/hashicorp/terraform-provider-google/blob/5800a6dff199cf09fd3ddab7eef0c75bb2c92744/google/common_operation.go#L18

This breaks down if the error message is in a different place - for example:

```
...
"error": {
    "code": 9,
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "POSTGRES_CONNECTION_ERROR",
        "domain": "datastream.googleapis.com",
        "metadata": {
          "message": "An unexpected database connection error occurred while trying to connect to the data source. Make sure that the connection profile configuration is correct, or contact Google Support.",
          "uuid": "de7cb468-4c56-49ec-a32b-09a396f2ecf0",
          "time": "2022-08-30T17:37:43.192113Z",
          "originalMessage": "timeout expired\n"
        }
      }
    ]
  }
...
```

This ends up getting displayed as:

```
Error: Error waiting to create ConnectionProfile: Error waiting for Creating ConnectionProfile: Error code 9, message: 
```

# Expected Behavior

We should be honoring the async.error settings so that autogenerated resources can compensate for different operation error structures.

**Comment by melinath** [comment]
The workaround is to turn off `autogen_async`.

**Comment by rileykarson** [comment]
Based on the number of wrong / untrusted async blogs in MM and the infrequency of operations deviating significantly, we'd rather handwrite exceptional cases for now.

Terraform's templates only use a limited number of fields from the operations.

**Comment by melinath** [comment]
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/17098 - we should just remove the configuration for now and then do an actual intentional implementation later if needed.
