### ISSUE TITLE
google_compute_router_interface cannot refer to google_compute_interconnect_attachment as interconnect_attachment creates its own router_interface

### ISSUE THREAD

**Issue by AlfatahB** [hashicorp/terraform-provider-google#12445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.8
* provider registry.terraform.io/hashicorp/google v4.34.0

### Affected Resource(s)

* google_compute_router_interface
* google_compute_interconnect_attachment

### Terraform Configuration Files

```tf
resource "google_compute_network" "tf_network" {
  name                    = "tf-network"
  auto_create_subnetworks = false
}

resource "google_compute_router" "tf_router_1" {
  name                          = "tf-router-1"
  network                       = google_compute_network.tf_network.name
  bgp {
    asn = 16550
  }
}

resource "google_compute_interconnect_attachment" "tf_ica" {
  name                     = "tf-ica"
  router                   = google_compute_router.tf_router_1.name
  type = "PARTNER"
}

resource "google_compute_router_interface" "tf_router_interface" {
  name       = "tf-router-interface"
  router     = google_compute_router.tf_router_1.name
  ip_range = "169.254.1.1/30"
  interconnect_attachment = google_compute_interconnect_attachment.tf_ica.name
}

```

### Panic Output

```
 Error: Error patching router us-central1/tf-router-1: googleapi: Error 400: The interfaces 'tf-router-interface' and 'auto-ia-if-tf-ica-333d2bd0ed8b25c' are linked to the same interconnectAttachment., badRequest
│ 
│   with google_compute_router_interface.tf_router_interface,
│   on main.tf line 37, in resource "google_compute_router_interface" "tf_router_interface":
│   37: resource "google_compute_router_interface" "tf_router_interface" {
│ 
```

### Expected Behavior

We should be able to refer the interconnect_attachment that we created in the router_interface.

### Actual Behavior

Here, interconnect_attachment creates its own router_interface. I have also checked for the same by making REST API calls.

### Steps to Reproduce

1. `terraform apply`

### References

* #9688 
* https://cloud.google.com/compute/docs/reference/rest/v1/routers
* https://cloud.google.com/compute/docs/reference/rest/v1/interconnectAttachments

**Comment by edwardmedia** [comment]
@AlfatahB do you know what they are `tf-router-interface` and `auto-ia-if-tf-ica-333d2bd0ed8b25c`? Can you share your debug log?

**Comment by AlfatahB** [comment]
@edwardmedia Here I am sharing my debug logs.
[debug_logs.log](https://github.com/hashicorp/terraform-provider-google/files/9486908/debug_logs.log)

**Comment by edwardmedia** [comment]
@AlfatahB what do you mean with below statement under [Actual Behavior](https://github.com/hashicorp/terraform-provider-google/issues/12445#issue-1358554394)?  if api call succeeds, can you share the full log?  

```
I have also checked for the same by making REST API calls.
```

**Comment by AlfatahB** [comment]
I have used the following Terraform configuration:
```hcl
resource "google_compute_network" "tf_network" {
  name                    = "tf-network"
  auto_create_subnetworks = false
}

resource "google_compute_router" "tf_router_1" {
  name                          = "tf-router-1"
  network                       = google_compute_network.tf_network.name
  bgp {
    asn = 16550
  }
}

resource "google_compute_interconnect_attachment" "tf_ica" {
  name                     = "tf-ica"
  router                   = google_compute_router.tf_router_1.name
  type = "PARTNER"
}

resource "google_compute_router_interface" "tf_router_interface" {
  name       = "tf-router-interface"
  router     = google_compute_router.tf_router_1.name
  ip_range = "169.254.1.1/30"
}
```
I have made API GET call for this Router (tf-router-1) through [API Explorer](https://cloud.google.com/compute/docs/reference/rest/v1/routers/get). I am getting the following response:
```json
{
  "kind": "compute#router",
  "id": "2073442997727931682",
  "creationTimestamp": "2022-09-29T05:47:09.626-07:00",
  "name": "tf-router-1",
  "region": "https://www.googleapis.com/compute/v1/projects/project-name/regions/us-central1",
  "network": "https://www.googleapis.com/compute/v1/projects/project-name/global/networks/tf-network",
  "interfaces": [
    {
      "name": "auto-ia-if-tf-ica-temp-5cad0f3983f27d3",
      "linkedInterconnectAttachment": "https://www.googleapis.com/compute/v1/projects/project-name/regions/us-central1/interconnectAttachments/tf-ica-temp",
      "managementType": "MANAGED_BY_ATTACHMENT"
    },
    {
      "name": "tf-router-interface",
      "ipRange": "169.254.1.1/30"
    }
  ],
  "bgpPeers": [
    {
      "name": "auto-ia-bgp-tf-ica-temp-5cad0f3983f27d3",
      "interfaceName": "auto-ia-if-tf-ica-temp-5cad0f3983f27d3",
      "managementType": "MANAGED_BY_ATTACHMENT",
      "enable": "TRUE",
      "bfd": {
        "sessionInitializationMode": "DISABLED",
        "minTransmitInterval": 1000,
        "minReceiveInterval": 1000,
        "multiplier": 5
      },
      "enableIpv6": false
    }
  ],
  "bgp": {
    "asn": 16550,
    "advertiseMode": "DEFAULT",
    "keepaliveInterval": 20
  },
  "selfLink": "https://www.googleapis.com/compute/v1/projects/project-name/regions/us-central1/routers/tf-router-1"
}

```
We can see in the above response that there are 2 interfaces. One is the interface that I've created using terraform i.e. **tf-router-interface**, while other interface is not created by me i.e. **auto-ia-if-tf-ica-temp-5cad0f3983f27d3**.

So, In the terraform configuration, If I want to refer to this interconnect_attachment in the router_interface block as in [Terraform Configuration Files](https://github.com/hashicorp/terraform-provider-google/issues/12445#issue-1358554394), I get this error as in [Panic Output](https://github.com/hashicorp/terraform-provider-google/issues/12445#issue-1358554394).

**Comment by edwardmedia** [comment]
@AlfatahB it appears you want to create a [Partner Interconnect](https://cloud.google.com/network-connectivity/docs/interconnect/how-to/partner/provisioning-overview). Please explain to me why you need to create `google_compute_router_interface`?

**Comment by AlfatahB** [comment]
@edwardmedia I was working on this [issue](https://github.com/hashicorp/terraform-provider-google/issues/9688). Hence, I was trying to create `google_compute_router_interface` to confirm the behavior of router interface according to the [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/routers). I have also raised [another issue](https://github.com/hashicorp/terraform-provider-google/issues/12485).

**Comment by AlfatahB** [comment]
@edwardmedia I was working on this [issue](https://github.com/hashicorp/terraform-provider-google/issues/9688). Hence, I was trying to create `google_compute_router_interface` to confirm the behavior of router interface according to the [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/routers). I have also raised [another issue](https://github.com/hashicorp/terraform-provider-google/issues/12485).

**Comment by edwardmedia** [comment]
@AlfatahB I don't think `google_compute_router_interface` should be used in [Partner Interconnect](https://cloud.google.com/network-connectivity/docs/interconnect/how-to/partner/provisioning-overview) . This use case is invalid. That is why you got the error.

**Comment by edwardmedia** [comment]
@AlfatahB Thanks for reaching out. Close this issue then
