### ISSUE TITLE
Speech-to-Text workspaces

### ISSUE THREAD

**Issue by jonathan-falomir** [hashicorp/terraform-provider-google#12444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Having the ability to create a workspace for [Speech-to-Text](https://cloud.google.com/speech-to-text) service and the bucket that should be associated with it.

### New or Affected Resource(s)

* google_speech_to_text_workspace

### Potential Terraform Configuration

```tf
resource "google_speech_to_text_workspace" "workspace1" {
  workspace_name = "sandbox_workspace"
  bucket = "my_speech_workspace_bucket"
}
```

### References

* [Speech-to-Text](https://cloud.google.com/speech-to-text)

**Comment by melinath** [comment]
@jonathan-falomir could you link to the REST API docs for this resource?

**Comment by jonathan-falomir** [comment]
Sorry yeah that would have been helpful.
[Cloud Speech-to-Text API](https://cloud.google.com/speech-to-text/docs/reference/rest)

**Comment by melinath** [comment]
@jonathan-falomir thanks! Looking at the API I see CustomClasses and PhraseSets seem to be real resources that could potentially be provisioned with Terraform; I don't see `workspaces` - could you clarify what a `workspace` is and which API specifically would be used to create it? Or alternately - would custom classes and phrase sets meet your needs?

**Comment by jonathan-falomir** [comment]
Hi, so after digging some more into the API and the SDK it doesn't look like gcp gives us the ability to create workspaces (which are just a reference to a cloud storage bucket that will keep a record of transcriptions). It's very weird since the UI won't let you create a transcription without setting a workspace but the gcloud cli won't complain and will work just fine.
So, while the custom classes and phrases would be good to have in terraform it deviates from the original ticket request, so I'll just go ahead and close it since it's impossible form an API perspective to create the workspace.
