### ISSUE TITLE
Should flag dependents  of `google_compute_instance_template` "Forces replacement" transitively

### ISSUE THREAD

**Issue by alankan-finocomp** [hashicorp/terraform-provider-google#12455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v.1.2.8

### Affected Resource(s)

- google_compute_instance_template
- google_compute_region_instance_group_manager

### Terraform Configuration Files

```tf
resource "google_compute_instance_template" "rancher_server" {
  name         = "rancher-server"
  tags         = ["rancher", "http-server", "https-server"]
  machine_type = var.machine_type

  disk {
    source_image = data.google_compute_image.sles.self_link
    auto_delete  = true
    boot         = true
  }

  metadata = {
    ssh-keys       = "${var.user}:${tls_private_key.global_key.public_key_openssh}"
    enable-oslogin = "FALSE"
  }

  metadata_startup_script = local.install_k3s_script
}

resource "google_compute_region_instance_group_manager" "rancher_server" {
  name               = "rancher-server-igm"
  base_instance_name = "rancher-server"
  region             = var.region
  version {
    name              = "k3s-server-vm"
    instance_template = google_compute_instance_template.rancher_server.id
  }
  target_size        = var.replicas
  wait_for_instances = true
}
```

### Expected Behavior

When a "Forces replacement" is required for `google_compute_instance_template`, it should transitively flag its dependents as well.

### Actual Behavior

![image](https://user-images.githubusercontent.com/79436574/188058183-b7f4aef3-2596-49d5-bf17-acadd50a18f8.png)

![image](https://user-images.githubusercontent.com/79436574/188057643-88d8ab02-93dd-453b-b735-27399962fdb4.png)

When `google_compute_instance_template` has been updated and requires a `Forces replacement`, the dependents like `google_compute_region_instance_group_manager` is not flagged "Forces replacement` automatically and it ends up failing because it didn't free the instance_template up to be destroyed and recreated.

> Error: Error waiting for Deleting Instance Template: The instance_template resource 'projects/redacted/global/instanceTemplates/rancher-server' is already being used by 'projects/redacted/regions/australia-southeast1/instanceGroupManagers/rancher-server-igm'

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@alankan-finocomp can you try adding `depends_on` to see if that helps?

**Comment by rileykarson** [comment]
Variant of https://github.com/hashicorp/terraform-plugin-sdk/issues/122, see HashiCorp's solution: https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by
