### ISSUE TITLE
docker_repository and kms_key_name for Cloud Functions doesn't update

### ISSUE THREAD

**Issue by davidedironza** [hashicorp/terraform-provider-google#12457]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
1.1.7

### Affected Resource(s)

* google_cloudfunctions_function

### Issue Description

Updating an existing Cloud Function with CMEK and Artifact Repository doesn't update the correct values.
It seems that for the update it updates the runtime instead of the related attributes
* https://github.com/hashicorp/terraform-provider-google/pull/11627/files#diff-cd6c72f494d4214500c9224b6bc88941d02fca2d8a483fc18356f7dbfee21212R784
* https://github.com/hashicorp/terraform-provider-google/pull/11627/files#diff-cd6c72f494d4214500c9224b6bc88941d02fca2d8a483fc18356f7dbfee21212R789

### References

* https://github.com/hashicorp/terraform-provider-google/pull/11627

**Comment by edwardmedia** [comment]
@davidedironza can you share your config and steps so I can repro the issue?

**Comment by davidedironza** [comment]
@edwardmedia find here some terraform code. I couldn't provide our original code because we have a special setup in our org. maybe you have to change or add some missing stuff (iam-bindings?!) so it fits for you.
`
locals {
  cf_name = "cf-test-cmek"
  location = "europe-west6"
}

//KMS
resource "google_kms_key_ring" "my_key_ring" {
  project  = var.project_id
  name     = "keyring-${var.project_id}"
  location = local.location
}

resource "google_kms_crypto_key" "my_crypto_key" {
  name            = "key-${var.project_id}"
  key_ring        = google_kms_key_ring.my_key_ring.id
  rotation_period = "7776000s"
  lifecycle {
    prevent_destroy = true
  }
}
//END KMS

resource "google_storage_bucket" "buckets-cmek" {
  project       = var.project_id

  name     		= "cf-test-cmek"
  location 		= local.location
  storage_class = "STANDARD"
  uniform_bucket_level_access = true

  encryption {
    default_kms_key_name =  google_kms_crypto_key.my_crypto_key.id
  }
}

# zip up our source code
data "archive_file" "cf-cmek" {
  type        = "zip"
  output_file_mode = "0666"
  source_dir = "${var.workspace}/cloud_functions/${local.cf_name}/"
  output_path = "${var.workspace}/cloud_functions/${local.cf_name}.zip"
}

# place the zip-ed code in the bucket
resource "google_storage_bucket_object" "cf_zip-cmek" {

  name     = "${local.cf_name}-${lower(replace(base64encode(data.archive_file.cf-cmek.output_md5), "=", ""))}.zip"
  bucket   = google_storage_bucket.buckets-cmek.name
  source   = data.archive_file.cf-cmek.output_path

}

resource "google_artifact_registry_repository" "gcf-artifacts" {
  provider = google-beta
  project = var.project_id
  location = local.location
  repository_id = "gcf-artifacts"
  description = "Repo to save images from Cloud Functions build with CMEK"
  format = "DOCKER"
  kms_key_name = google_kms_crypto_key.my_crypto_key.id
}

resource "google_cloudfunctions_function" "cf_deploy-cmek" {
  project = var.project_id
  name = local.cf_name
  available_memory_mb = "256"
  source_archive_bucket = google_storage_bucket.buckets-cmek.name
  source_archive_object = google_storage_bucket_object.cf_zip-cmek.name
  timeout = 540
  entry_point = "main"
  trigger_http = true
  max_instances = "10"

  runtime = "python39"
  region = local.location

  service_account_email = "service-account-no-admin@${var.project_id}.iam.gserviceaccount.com"


#   first tf run without following attributes / second run including this attributes, so the update will fail
#   docker_registry = "ARTIFACT_REGISTRY"
#   docker_repository = google_artifact_registry_repository.gcf-artifacts.id
#   kms_key_name = google_kms_crypto_key.my_crypto_key.id

}
`

**Comment by davidedironza** [comment]
@edwardmedia any news here when this could be solved?
