### ISSUE TITLE
unwanted recreation of filestore instance when using PRIVATE_SERVICE_ACCESS and reserved_ip_range

### ISSUE THREAD

**Issue by kubitz** [hashicorp/terraform-provider-google#12458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.30.0
+ provider registry.terraform.io/hashicorp/google-beta v4.30.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/tls v4.0.2
```

### Affected Resource(s)

* google_filestore_instance

### Terraform Configuration Files

1. *CONFIG 1:* USING CIDR RANGE IN `reserved_ip_range`. 

```tf
resource "google_filestore_instance" "test_instance" {
  name     = "testinstance"
  location = "us-central1-b"
  tier     = "BASIC_SSD"

  file_shares {
    capacity_gb = 2560
    name        = "myshare"
  }

#### LOOK HERE ####
  networks {
    network           = google_compute_network.vpc.id
    modes             = ["MODE_IPV4"]
    connect_mode      = "PRIVATE_SERVICE_ACCESS"
    reserved_ip_range = "${google_compute_global_address.private_ip_alloc.address}/${google_compute_global_address.private_ip_alloc.prefix_length}"
  }
  depends_on = [google_service_networking_connection.private_vpc_connection]
}


##### Supporting Resources ####
resource "google_compute_network" "vpc" {
  name                    = "filestore-bug"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "network" {
  name          = "filestore-bug-network"
  ip_cidr_range = "172.160.0.0/29"
  region        = "us-central1"
  network       = google_compute_network.vpc.id
}

resource "google_compute_global_address" "private_ip_alloc" {

  name          = "filestore-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 29
  address       = "172.16.255.0"
  network       = google_compute_network.vpc.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network = google_compute_network.vpc.id
  service = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [
    google_compute_global_address.private_ip_alloc.name,
    google_compute_global_address.dummy_private_ip_alloc.name
  ]
}

resource "google_compute_global_address" "dummy_private_ip_alloc" {
  # At least one private IP address range must be of size /24.
  # This is a dummy address range that is not used in this MVP

  name          = "dummy-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  address       = "172.16.250.0"
  network       = google_compute_network.vpc.id
}
```

2. CONFIG 2: Using CIDR name instead of direct range

```tf
resource "google_filestore_instance" "test_instance" {
  name     = "testinstance"
  location = "us-central1-b"
  tier     = "BASIC_SSD"

  file_shares {
    capacity_gb = 2560
    name        = "myshare"
  }

#### LOOK HERE ####
  networks {
    network           = google_compute_network.vpc.id
    modes             = ["MODE_IPV4"]
    connect_mode      = "PRIVATE_SERVICE_ACCESS"
    reserved_ip_range = google_compute_global_address.private_ip_alloc.name # Change direct CIDR to name
  }
  depends_on = [google_service_networking_connection.private_vpc_connection]
}


##### Supporting Resources ####
resource "google_compute_network" "vpc" {
  name                    = "filestore-bug"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "network" {
  name          = "filestore-bug-network"
  ip_cidr_range = "172.160.0.0/29"
  region        = "us-central1"
  network       = google_compute_network.vpc.id
}

resource "google_compute_global_address" "private_ip_alloc" {

  name          = "filestore-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 29
  address       = "172.16.255.0"
  network       = google_compute_network.vpc.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network = google_compute_network.vpc.id
  service = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [
    google_compute_global_address.private_ip_alloc.name,
    google_compute_global_address.dummy_private_ip_alloc.name
  ]
}

resource "google_compute_global_address" "dummy_private_ip_alloc" {
  # At least one private IP address range must be of size /24.
  # This is a dummy address range that is not used in this MVP

  name          = "dummy-private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  address       = "172.16.250.0"
  network       = google_compute_network.vpc.id
}
```

### Expected Behavior

1. Inserting `reserved_ip_range` with direct CIDR block (CONFIG 1 works)
2. Inserting `reserved_ip_range` name doesn't lead to filestore recreation.

### Actual Behavior

1. if using `CONFIG 1` : 
`Error waiting to create Instance: Error waiting for Creating Instance: Error code 3, message: cloud-control2-saas::INVALID_ARGUMENT: when using connect mode PRIVATE_SERVICE_ACCESS, if reserved IP range is specified, it must be a named address range instead of direct CIDR value..`

3. If using `CONFIG 2`:
Resource is properly created, but filestore is recreated on every subsequent apply :
 `  ~ reserved_ip_range = "172.16.255.0/29" -> "filestore-private-ip-address" # forces replacement`

### Steps to Reproduce

1. `terraform apply`

### Work-around

For anyone facing this issue, you can workaround it by applying first CONFIG 2, then applying CONFIG 1. This is quite suboptimal but it works

**Comment by edwardmedia** [comment]
@kubitz can you share the debug log of both exectuions?

**Comment by edwardmedia** [comment]
@kubitz is this still an issue?

**Comment by edwardmedia** [comment]
@kubitz closing this assuming this is no longer an issue

**Comment by aarturm** [comment]
I'm facing the same issue.  I used above code and executed terraform apply 3 times. First time it creates Filestore instance and each next run will replace it:
[1stapply.log](https://github.com/hashicorp/terraform-provider-google/files/9858222/1stapply.log)
[2ndapply.log](https://github.com/hashicorp/terraform-provider-google/files/9858223/2ndapply.log)
[3rdapply.log](https://github.com/hashicorp/terraform-provider-google/files/9858224/3rdapply.log)

**Comment by aarturm** [comment]
@edwardmedia can this issue be re-opened? Or do I have to open one?
