### ISSUE TITLE
Nodepool not getting created

### ISSUE THREAD

**Issue by blessedwithsins** [hashicorp/terraform-provider-google#12472]
I am trying to create a GKE Cluster using Terraform. However, it's unable to create managed Nodepool and fails with the error below. 

google_container_node_pool.primary_nodes: Creating...
╷
│ Error: error creating NodePool: googleapi: Error 404: Not found: projects/piyushgaur-exams/locations/us-central1/clusters/piyushgaur-exams-gke., notFound
│ 
│   with google_container_node_pool.primary_nodes,
│   on gke.tf line 32, in resource "google_container_node_pool" "primary_nodes":
│   32: resource "google_container_node_pool" "primary_nodes" {
│ 
╵
piyushgaur-macbookpro2:hashicorp-terraform-associate piyushgaur$

Attached are the snippets and trace logs. 

Repository > https://github.com/blessedwithsins/hashicorp-terraform-associate/blob/main/gke.tf 

![image](https://user-images.githubusercontent.com/26162427/188539213-bed3705e-686a-429f-b9fc-b929aa54f073.png)

![image](https://user-images.githubusercontent.com/26162427/188539250-fbacf5e1-779a-495e-850c-0f4eb5bdcbea.png)
[gkelog.txt](https://github.com/hashicorp/terraform-provider-google/files/9492996/gkelog.txt)

piyushgaur-macbookpro2:hashicorp-terraform-associate piyushgaur$ terraform -v
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.34.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.2

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
piyushgaur-macbookpro2:hashicorp-terraform-associate piyushgaur$

**Comment by blessedwithsins** [comment]
I have tried using timeouts and depends_on as well, but resulting in same error.

**Comment by blessedwithsins** [comment]
It does create the Nodepool and then deletes it, but doesn't create the managed Nodepool. 

![image](https://user-images.githubusercontent.com/26162427/188553485-7785bab4-bc65-4df4-8982-631db23ca09b.png)


![image](https://user-images.githubusercontent.com/26162427/188553509-034206ca-554e-4253-ab72-58971cffdb05.png)

**Comment by edwardmedia** [comment]
@blessedwithsins it works fine with me using your code. You can run below code to see if that works for you

```tf
variable "gke_username" {
  default     = "gke_username"
  description = "gke username"
}

variable "gke_password" {
  default     = "gke_password"
  description = "gke password"
}

variable "gke_num_nodes" {
  default     = 1
  description = "number of gke nodes"
}

variable "project_id" {
    default     = "isssue12472"
}

variable "region" {
    default     = "us-central1"
}

data "google_compute_network" "vpc" {
  name = "default"
}

data "google_compute_subnetwork" "subnet" {
  name   = "default"
  region = "us-east1"
}

# GKE cluster
resource "google_container_cluster" "primary" {
  name     = "isssue12472-gke"
  location = "us-central1"
  
  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1

  network    = data.google_compute_network.vpc.name
  subnetwork = data.google_compute_subnetwork.subnet.name
}

# Separately Managed Node Pool
resource "google_container_node_pool" "primary_nodes" {
  name       = "${google_container_cluster.primary.name}-node-pool"
  location   = var.region
  node_locations   = [ "us-central1-a" ]
  cluster    = google_container_cluster.primary.name
  node_count = var.gke_num_nodes

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    labels = {
      env = var.project_id
    }

    # preemptible  = true
    machine_type = "n1-standard-1"
    tags         = ["gke-node", "${var.project_id}-gke"]
    metadata = {
      disable-legacy-endpoints = "true"
    }
  }
}
```

**Comment by blessedwithsins** [comment]
@edwardmedia Thanks Edward. Let me check internally and get back to you on this. Please allow me some time to provide an update.

**Comment by blessedwithsins** [comment]
@edwardmedia I was able to create the cluster. However, I have to provide the value of location as "us-central1-a". It didn't work without it.

**Comment by edwardmedia** [comment]
@blessedwithsins glad you have found the solution. Closing the issue then
