### ISSUE TITLE
Changing bigquery table schema forces table replacement

### ISSUE THREAD

**Issue by sophhu** [hashicorp/terraform-provider-google#12494]
Hello, what I'm using:
  google = {
      source  = "hashicorp/google"
      version = "4.12.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.12.0"
    }
    
    and terraform version 1.2.3 

The problem is that I am adding new fields to the schema of an existing bigquery table in terraform and terraform is asking that I replace the entire table but I cannot do that because I want to keep the data in the table. I don't see this issue mentioned in any of the releases (https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.35.0) though I did find this old post (https://stackoverflow.com/questions/66884998/terraform-bigquery-create-tables-replace-table-instead-of-edit) of a similar problem before on version 3.55.0 and I found something similar before too https://github.com/hashicorp/terraform-provider-google/issues/10919. 

here is the output from terraform I get: 
# google_bigquery_table.si_recipes_historical must be replaced
-/+ resource "google_bigquery_table" "si_recipes_historical" {
      ~ creation_time       = 1660852372575 -> (known after apply)
      + description         = "Historical back up of si_recipes table on a day to day basis"
      ~ etag                = "aPSfK3GJDrlo+0ve/6NRKA==" -> (known after apply)
      ~ expiration_time     = 0 -> (known after apply)
      ~ id                  = "projects/honey-production/datasets/site_interactions_platform/tables/si_recipes_historical" -> (known after apply)
      - labels              = {} -> null
      ~ last_modified_time  = 1662005514928 -> (known after apply)
      ~ location            = "US" -> (known after apply)
      ~ num_bytes           = 13458261254 -> (known after apply)
      ~ num_long_term_bytes = 0 -> (known after apply)
      ~ num_rows            = 23575447 -> (known after apply)
      ~ project             = "honey-production" -> (known after apply)
      ~ schema              = jsonencode(
          ~ [ # forces replacement
              - {
                  - name = "insertion_date"
                  - type = "DATE"
                },
                {
                    name = "id"
                    type = "STRING"
                },
                # (70 unchanged elements hidden)
                {
                    name = "add_to_cart_changes_div"
                    type = "STRING"
                },
              + {
                  + name = "add_to_cart_recording"
                  + type = "STRING"
                },
                {
                    name = "shipping_options_div"
                    type = "STRING"
                },
                # (30 unchanged elements hidden)
                {
                    name = "temp_disable_find_savings_mobile"
                    type = "STRING"
                },
              - {
                  - name = "add_to_cart_recording"
                  - type = "STRING"
                },
                {
                    name = "cart_qtys_div_mobile"
                    type = "STRING"
                },
                # (75 unchanged elements hidden)
                {
                    name = "h_store_attributes"
                    type = "STRING"
                },
              + {
                  + name = "has_fs_submit_button_mixin"
                  + type = "BOOLEAN"
                },
              + {
                  + name = "has_fs_pre_apply_code_action_mixin"
                  + type = "BOOLEAN"
                },
              + {
                  + name = "has_fs_remove_code_action_mixin"
                  + type = "BOOLEAN"
                },
              + {
                  + name = "has_fs_submit_button_mobile_mixin"
                  + type = "BOOLEAN"
                },
            ]
        )
      ~ self_link           = "https://bigquery.googleapis.com/bigquery/v2/projects/honey-production/datasets/site_interactions_platform/tables/si_recipes_historical" -> (known after apply)
      ~ type                = "TABLE" -> (known after apply)
        # (3 unchanged attributes hidden)

      ~ time_partitioning {
          ~ expiration_ms            = 0 -> (known after apply)
          - field                    = "insertion_date" -> null # forces replacement
          - require_partition_filter = false -> null
            # (1 unchanged attribute hidden)
        }
    }

is there a way to apply the schema changes in terraform but without replacing the whole table?

**Comment by edwardmedia** [comment]
@sophhu this is by design. [Here](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_bigquery_table.go#L452) is the code where this logic is implemented, which is based on its [API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch)

```tf
Updates information in an existing table. The update method replaces the entire table resource, whereas the patch method only replaces fields that are provided in the submitted table resource
```
