### ISSUE TITLE
Unable to set empty sandbox_config block on google_container_node_pool

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-google#12503]
### Terraform Version

```
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google-beta v4.35.0
```

### Affected Resource(s)

- google_container_node_pool

### Terraform Configuration Files

```tf
variable enable_kernel_sandbox {
  type = bool
}

resource "google_container_node_pool" "system_preemptible_nodes" {
  node_config {
    sandbox_config {
      sandbox_type = var.enable_kernel_sandbox ? "gvisor" : ""
    }
  }
}
```

### Expected Behavior

If `sandbox_type` is left empty, the block is ignored. This enables use cases to only enable sandboxing based on a boolean flag.

### Actual Behavior

```
│ Error: expected node_config.0.sandbox_config.0.sandbox_type to be one of [gvisor], got 
│ 
│   with module.google.module.dev_cluster.google_container_node_pool.system_preemptible_nodes,
│   on google/gke/gke_nodepool.tf line 20, in resource "google_container_node_pool" "system_preemptible_nodes":
│   20:       sandbox_type = var.enable_kernel_sandbox ? "gvisor" : ""
```

**Comment by hazcod** [comment]
@edwardmedia Ideally some logic around it if the input is `""` the block should be ommitted.

**Comment by edwardmedia** [comment]
@hazcod unfortunately there is not much we can do at the provider level as the field is clearly defined. What you wanted are some feature at the Terraform Core/SDK. Closing the issue now. Please reopen if you want to continue the discussion
