### ISSUE TITLE
GCP secret when destroy manually terraform goes on 400 request as secret already destroyed.

### ISSUE THREAD

**Issue by Raffaello** [hashicorp/terraform-provider-google#12504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.35.0

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html

````

### Affected Resource(s)

* `google_secret_manager_secret_version`

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

```
{
  "error": {
    "code": 400,
    "message": "SecretVersion.state is already DESTROYED.",
    "status": "FAILED_PRECONDITION"
  }

}: timestamp=2022-09-08T12:07:34.416+0100

2022-09-08T12:07:34.417+0100 [INFO]  provider.terraform-provider-google_v4.35.0_x5: 2022/09/08 12:07:34 [DEBUG] Retry Transport: Returning after 1 attempts: timestamp=2022-09-08T12:07:34.416+0100

2022-09-08T12:07:34.417+0100 [ERROR] provider.terraform-provider-google_v4.35.0_x5: Response contains error diagnostic: tf_provider_addr=provider tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/diag/diagnostics.go:56 diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="Error when reading or editing SecretVersion: googleapi: Error 400: SecretVersion.state is already DESTROYED." tf_resource_type=google_secret_manager_secret_version @module=sdk.proto tf_proto_version=5.2 tf_req_id=2176ca90-b5f0-ca6b-09df-3a3be972d20a timestamp=2022-09-08T12:07:34.417+0100

2022-09-08T12:07:34.419+0100 [ERROR] vertex "module.my_module.google_secret_manager_secret_version.my_secret_version (destroy)" error: Error when reading or editing SecretVersion: googleapi: Error 400: SecretVersion.state is already DESTROYED.
╷
│ Error: Error when reading or editing SecretVersion: googleapi: Error 400: SecretVersion.state is already DESTROYED.
│ 
│ 
╵

```

### Expected Behavior

When a secret is already in a destroyed state and terraform was to destroying the secret, 
it should not fail as the error is easy to recover:
it should update the state that the error has been destroyed and keep going instead of failing.
eventually it could emit a warning/info to notify the user of that unexpected secret state.

### Actual Behavior

When terraform tries to destroy the secret that has been already destroyed, manually for e.g., it is failing like is an unrecoverable error. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Raffaello** [comment]
> @Raffaello is this only happening to a specific resource or common behavior for general resources? What resource were you using? Can you share the config and the detailed steps to repro the issue?

It is happening generally on a specific resource: `google_secret_manager_secret_version`

basically:
1. create a secret with terraform,
2. then destroy the secret manually
3. update the secret with terraform. 

at point 3 terraform is trying to destroy an already destroyed secret and throws.

The 400 status code error i guess is the google API response: the call could be enclosed in a sort of try catch block and handling the case when is 400 and "already destroyed", implying that that step has been done outside terraform.
Terraform could just internally update its state like if it was a succesul operation and keep going on, eventually emitting a warning to the user as a something has changed outside its state.

On this also:
There is no state refresh on that specific resource secret neither, that terraform could pre-detect that the secret has been already destroyed, so it could skip a step destroying it when is computing is plan.

**Comment by Raffaello** [comment]
the code is simple as the 2 resources required to create a secret like:
```td
resource "google_secret_manager_secret" "my_secret" {
  project   = var.project
  secret_id = var.secret_id
  replication {
    automatic = true
  }
  labels = var.labels
}

resource "google_secret_manager_secret_version" "my_secret_version" {
  secret      = google_secret_manager_secret.secret.name
  secret_data = var.secret_data
  enabled     = var.enabled
}
```
I let you substitute those variables ...
the throw is on the "my_secret_version"

basically apply this micro module once (or just put it equivalently in a main.tf should reproduce the issue i guess).
with a value let say `"secretdata_1"`

it is all ok. 
2. then going on GCP UI destry this novel secret manually.
3. then apply the terraform again with instead `"secretdata_2"` as a new secret. It will throw 400 as secretdata_1 has been already destroyed.

NOTE: there is an analogue behaviour if at point 3 try to apply without a new value, but let say keeping apply `"secretdata_1"` and manually has been destroyed, it won't update it as for tfstate is already latest and active `"secretdata_1"` 

so it could be narrow down to just trigger a state refresh maybe as a pre-plan step eventually... (?)

**Comment by edwardmedia** [comment]
@Raffaello why did you want to run `terraform apply` after the secret is manually deleted? If you want to recover the secret, can you check if [terraform taint](https://www.terraform.io/cli/commands/taint) help in your case?

**Comment by Raffaello** [comment]
> @Raffaello why did you want to run `terraform apply` after the secret is manually deleted? If you want to recover the secret, can you check if [terraform taint](https://www.terraform.io/cli/commands/taint) help in your case?

it is not about recovering the secret. It is about really a simple situation like:
1. create a secret with terraform
2.  that secret is deleted outside terraform
3. create a new secret with terrafrom ( <- here terraform can't recover and i think it should, hence a bug ticket)

oh well, because it can be deleted manually, and create a new one with terraform. 
at the same time i will, say why not?, as it might be better question in this case as there might be complication on fix this.

Also because even if it might not be a best practice, but on secrets, or even other resources, can't be terraform always the exclusive and unique owner on resources. as for e.g. can be a enterprise policy to wipe out/invalidate some secrets/resources due to whatever internal policy is and all terraforms that are dealing with this kind of resources aren't working anymore as a silly e.g.

----

the point that i am try to make is: Terraform could be slightly smarter dealing in this scenario as it is not a conflict situation that requires "human intervention" and can't be resolved automatically. (even if ironically human intervention could have created it 😄, but also a gcloud cli or whatever.. ), 
Terraform could just simply recover from this scenario.  It will improve resiliency of the product itself i think, 

unless there is something that it would be better keeping how is behaving now.

**Comment by edwardmedia** [comment]
@shuyama1 shouldn't api send 404 (instead of 400) for this case? 

https://github.com/hashicorp/terraform-provider-google/blob/main/google/utils.go#L96

**Comment by Raffaello** [comment]
> @shuyama1 shouldn't api send 404 (instead of 400) for this case?
> 
> https://github.com/hashicorp/terraform-provider-google/blob/main/google/utils.go#L96

i don't know. I have reported the behaviour in that specific use case. I didn't go check the code or what the API should return.

I had a 400 after trying to create a new secret with terraform when the "last" secret was deleted manually.

**Comment by Raffaello** [comment]
One more thing: This is also a bug, because to fix this 400 error is enough to just modify the tfstate file manually (and not recommended honestly), in this specific case increase by 1 the secret version number... 

for e.g:

 if it was `mysecret/versions/1` 
and it terraform failing to destroy that version because manually destroyed already, 
changing to `mysecret/versions/2` it will work, eventually need to also create manually the 2 version and keep it enabled.

And this for me should be better managed by that terraform resource when do the apply command

**Comment by rileykarson** [comment]
It seems likely we should remove the object from state at read time. I'm not sure why we don't, and don't see anything in the original PR (but didn't do more than scan through it). Maybe an interaction with `enabled`.

IMO failing if the Delete call 404s is reasonable, removing the object on Read is what makes us never make a Delete call.

**Comment by shuyama1** [comment]
Hi @Raffaello! I was trying to reproduce the error and everything worked fine for me.
The config I used to repro the issue:
```tf
resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret-version"
  labels = {
    label = "my-label"
  }
  replication {
    automatic = true
  }
}


resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.name
  secret_data = "secret-data"
  enabled = true
}
```
The steps I followed to repro the issue:
1. run `terraform apply` to create the resources
2. delete the secret from UI
3. run `terraform apply` again (I've also tried changing `secret_data` to "secret-data-new" and then run `terraform apply`)

The resources created correctly for me. Please let me know if there's any step I've missed to repro the error. Also, it would nice if you could provide the full debug log so I can take a look. Thanks!

**Comment by Raffaello** [comment]
> Hi @Raffaello! I was trying to reproduce the error and everything worked fine for me. The config I used to repro the issue:
> 
> ```terraform
> resource "google_secret_manager_secret" "secret-basic" {
>   secret_id = "secret-version"
>   labels = {
>     label = "my-label"
>   }
>   replication {
>     automatic = true
>   }
> }
> 
> 
> resource "google_secret_manager_secret_version" "secret-version-basic" {
>   secret = google_secret_manager_secret.secret-basic.name
>   secret_data = "secret-data"
>   enabled = true
> }
> ```
> 
> The steps I followed to repro the issue:
> 
> 1. run `terraform apply` to create the resources
> 2. delete the secret from UI
> 3. run `terraform apply` again (I've also tried changing `secret_data` to "secret-data-new" and then run `terraform apply`)
> 
> The resources created correctly for me. Please let me know if there's any step I've missed to repro the error. Also, it would nice if you could provide the full debug log so I can take a look. Thanks!

Hi,

to recap your steps, with the `secret-data-new`:
 
1. run `terraform apply` to create the resources (`secret-data`)
2. delete the secret from UI (destroy)
3. run `terraform apply` again, but using the new secret

well that should have reproduced the error i have experienced.

as a per DEBUG output reported in this isse too.
```
[...[
2022-09-08T12:07:34.419+0100 [ERROR] vertex "module.my_module.google_secret_manager_secret_version.my_secret_version (destroy)" error: Error when reading or editing SecretVersion: googleapi: Error 400: SecretVersion.state is already DESTROYED.
╷
│ Error: Error when reading or editing SecretVersion: googleapi: Error 400: SecretVersion.state is already DESTROYED.
```

I think the whole point of the error i have experienced is about tf not able to refreshing the tfstate when it has been modified outside terraform itself, or sort of. 

In your case, was it refreshed during the second apply? 
if it is so, are you running the same tf and provider version i have used? (i have considered it could have been a version fixed in the latest, but i was using last provider and i though it was mostly related to the provider not tf itself, but i might have assumed wrong)
if not, might be something already fixed in the latest tf or provider version?

p.s.

I might have a better deeper look tomorrow if i have some time to dig into it.
I would appreciate if you could tell me which version have you used.

**Comment by Raffaello** [comment]
p.p.s / addendum
@shuyama1 I have used a micro module to deal with secret that is basically applying those 2 resources, but not sure, it shoud be the same as applying those directly. unless the bug is somehow hidden with some module refresh state or whatever, not knowing the internal, just guessing.

**Comment by shuyama1** [comment]
Hi @Raffaello. I used Terraform v1.1.9 and provider v4.35.0 (the versions you listed in the issue description) to test the resource. I also tried creating a module with these 2 resources and it seems still work fine for me. Let me know if you still see this error.

**Comment by Raffaello** [comment]
> Hi @Raffaello. I used Terraform v1.1.9 and provider v4.35.0 (the versions you listed in the issue description) to test the resource. I also tried creating a module with these 2 resources and it seems still work fine for me. Let me know if you still see this error.
> 
> Update: Okay. I think I sort of find what the issue is. I tried destroying the secret version resource instead of deleting the secret via UI in step 2, and I was able to see the error `Error 400: SecretVersion.state is already DESTROYED`. Looking into it now.

hi thanks.
for the reply.
oh nice to that you have been able to reproduce the error.
