### ISSUE TITLE
Remove api.yaml entries that are excluded in Terraform in MM

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#12509]
There are several api.yaml schema definitions that are obsolete due to the removal of Ansible and Inspec in MM. For example, [this Compute resource](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/terraform.yaml#L2650). We should find what is excluded in Terraform and remove them from MM to avoid confusion.

**Comment by rileykarson** [comment]
Part of https://github.com/hashicorp/terraform-provider-google/issues/9588

**Comment by rileykarson** [comment]
@c2thorn mind opening a new bug to clean up the remaining resourceref resources? A new one seems valid, since we've cleaned up the ones totally not in use.

**Comment by c2thorn** [comment]
> @c2thorn mind opening a new bug to clean up the remaining resourceref resources? A new one seems valid, since we've cleaned up the ones totally not in use.

created https://github.com/hashicorp/terraform-provider-google/issues/14675
