### ISSUE TITLE
Feature: support for GKE gke security posture

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-google#12502]
### Description

We might want to support GKE Security Posture so we can, via terraform, include clusters into the monitoring.

### New or Affected Resource(s)

- google_container_cluster

### References

https://console.cloud.google.com/kubernetes/security/dashboard

**Comment by davidalger** [comment]
duplicate of #12778

**Comment by rileykarson** [comment]
Closing as dupe
