### ISSUE TITLE
Add `no_remove_boot_disk` to `google_notebooks_instance`

### ISSUE THREAD

**Issue by alexanderblnf** [hashicorp/terraform-provider-google#12515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the `google_notebooks_instance` resource has an attribute that lets you control whether to keep the `data disk` upon recreation of the notebook instance ([no_remove_data_disk](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#no_remove_data_disk)).

This issue proposes that a similar attribute is added for the `boot disk`, given that it is possible to control either via the UI or `gcloud` . The name of the attribute can be `no_remove_boot_disk`.

```
gcloud compute instances set-disk-auto-delete "${notebook_name}" --disk "${notebook_name}-boot" --no-auto-delete
```

### New or Affected Resource(s)

* google_notebooks_instance

### Potential Terraform Configuration

```tf
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  no_remove_data_disk = true # Already exists
  no_remove_boot_disk = true # To be implemented
}
```

### References

* [Notebooks Instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance)

b/302672919

**Comment by melinath** [comment]
It doesn't look like this is possible to set through the API: https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v1/projects.locations.instances

**Comment by melinath** [comment]
Closing this feature request - will follow up re: deprecation separately.
