### ISSUE TITLE
Cloud Build Trigger in specific region 

### ISSUE THREAD

**Issue by dvanrhenen** [hashicorp/terraform-provider-google#12516]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As Cloud Build now supports running builds in specific regions, it would be nice to be able to deploy these through Terraform. Via the Console, SDK, or API it is already possible to both run builds and create triggers in specific regions. Adding this option towards Terraform would be of great value, as we can control the location of where our data is shared (in regards to the GDPR-law).

### New or Affected Resource(s)

- `google_cloudbuild_trigger`

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "filename-trigger" {
  region = "europe-west4"

  trigger_template {
    branch_name = "main"
    repo_name   = "my-repo"
  }

  substitutions = {
    _FOO = "bar"
    _BAZ = "qux"
  }

  filename = "cloudbuild.yaml"
}
```

### References

- [Cloud Build | Selecting the region](https://cloud.google.com/build/docs/locations#selecting_the_region)

**Comment by bschaatsbergen** [comment]
I believe this is addressed in: [#6440](https://github.com/GoogleCloudPlatform/magic-modules/pull/6440)
