### ISSUE TITLE
Labelling Dataflow Jobs

### ISSUE THREAD

**Issue by mpsanj** [hashicorp/terraform-provider-google#12514]
We want to label Dataflow Jobs in GCP, we are use the latest provider and the label field seems to be deprecated as in the doc.

Is there a way around this ? why is the label field not being supported ?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job#labels

**Comment by edwardmedia** [comment]
@mpsanj  It appears api does not support it. The provider is based on API, and can't do much until API supports it. Does this make sense?

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_dataflow_flex_template_job.go#L56

**Comment by edwardmedia** [comment]
closing this now assuming it is no longer a question
