### ISSUE TITLE
Failing test(s): TestAccDataprocMetastoreService_*

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12524]
### Affected Resource(s)

* google_dataproc_metastore_service
* google_dataproc_cluster

Failure rate: 100% since Aug 6 2022

Impacted tests:
- TestAccDataprocMetastoreService_dataprocMetastoreServiceCmekTestExample
- TestAccDataprocMetastoreService_updateAndImport
- TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample
- TestAccDataprocCluster_withMetastoreConfig

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/335482?buildTab=tests&expandedTest=-1290592027607407147

Message:

```
Error: Error waiting to create Service: Error waiting for Creating Service: Error code 13, message: an internal error has occurred
with google_dataproc_metastore_service.default
```

**Comment by melinath** [comment]
Still 100% as of today.

**Comment by roaks3** [comment]
Note: It looks like we stopped seeing the original error happening at 100% on Nov 30, 2022, but have since then seen an occasional error that looks different:

```
------- Stdout: -------
=== RUN   TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample
=== PAUSE TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample
=== CONT  TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample
    provider_test.go:307: Step 1/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to google_dataproc_metastore_service.default, provider
        "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample (934.97s)
FAIL
```

**Comment by trodge** [comment]
This has been passing since 08 Feb 23.
