### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withMonitoringConfig

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12526]
Failure rate: 100% since Aug 24 2022

Impacted tests:
- TestAccContainerCluster_withMonitoringConfig

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/335482?buildTab=tests&expandedTest=-1619661655963524941

Message:

```
Error: googleapi: Error 400: Control plane metrics are not supported for version 1.22.10-gke.600, version 1.23.6 or newer is required., badRequest
```

**Comment by ScottSuarez** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6554
