### ISSUE TITLE
Failing test(s): Service account my-service-account already exists within project

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12530]
### Affected Resource(s)

* google_cloudbuild_trigger
* google_cloud_run_service

Failure rate: 100% since Sept 5 2022

Impacted tests:
- TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample
- TestAccCloudRunService_cloudrunServiceIdentityExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/335482?buildTab=tests&expandedTest=-7521920861646730327

Message:

```
Error: Error creating service account: googleapi: Error 409: Service account my-service-account already exists within project projects/{test-project-id}.
```

It looks like the first day there was a "root resource was present, now absent" error which possibly left this dangling resource that isn't getting properly cleaned up by sweepers / doesn't have a random suffix.

b/270751824
b/272361638

**Comment by RustedBl4de** [comment]
@melinath & @rileykarson  Sorry to make an out of band request, but we are impacted by this particular issue and I am wondering what some of the terms/states in your bug tracking mean.  This issue does not seem to be assigned, in a branch, or in a project.  It does, however, appear to be in "Near-Term Goals".  What should I see the status of this being?

Thank you both for your patience and hard work!

**Comment by melinath** [comment]
@RustedBl4de this ticket is basically tracking that we need to do a little cleanup in our CI/CD environment, so it's not likely to result in changes to the provider. If you're experiencing a bug that shares this symptom I'd recommend opening a new ticket. Thanks!

**Comment by melinath** [comment]
I should say: if this _is_ caused by a bug you're running into, it would still be great to have a separate ticket & link to this issue from that bug report.

**Comment by RustedBl4de** [comment]
@melinath Thanks for the response.  I had suspected that might be the case.  I did find a relevant "bug" as opposed to a "test failure" here:
https://github.com/hashicorp/terraform-provider-google/issues/10191

Thank you again!

**Comment by AarshDhokai** [comment]
- TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/-7521920861646730327?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/-7521920861646730327?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure

**Comment by roaks3** [comment]
Note that this came back, because we don't sweep service agents, and there was an error on the Beta provider run (not clear what went wrong) https://ci-oss.hashicorp.engineering/viewLog.html?buildId=377595&tab=buildResultsDiv&buildTypeId=GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject#testNameId-7521920861646730327:

```
=== RUN   TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample
=== PAUSE TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample
=== CONT  TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample
    provider_test.go:315: Step 1/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to google_service_account.cloudbuild_service_account,
        provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
        unexpected new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample (5.00s)
FAIL
```

I'm deleting the service agent again to keep the tests happy, but I think the sweeper is the most urgent action item here. The error above could have been due to concurrent runs.

**Comment by roaks3** [comment]
This was resolved with https://github.com/GoogleCloudPlatform/magic-modules/pull/7543, to make sure the service account name does not conflict with subsequent runs. Closing because the only remaining action is the sweeper, captured by https://github.com/hashicorp/terraform-provider-google/issues/14439.
