### ISSUE TITLE
Validation of Nodepool spec in Plan

### ISSUE THREAD

**Issue by harpratap** [hashicorp/terraform-provider-google#12548]
### Description

When you create a nodepool with incorrect spec `plan` works fine but it fails during `apply`.
One such example is the name of the nodepool which has a character limit of 39 and it doesn't warn about it when you run a plan command on it.
There are other parts of spec that are not validated too, eg there is no validation on custom  machine type, the increments you can specify the memory in and the max limits of CPU and memory per node family

### New or Affected Resource(s)

* google_container_node_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#limitations

**Comment by rileykarson** [comment]
Carrying over the business logic on node pool to Terraform is likely not feasible. The rules change constantly on the API, so it'd be difficult to keep in sync.
