### ISSUE TITLE
Broken link in:https://learn.hashicorp.com/tutorials/terraform/google-cloud-platform-change?in=terraform/gcp-get-started

### ISSUE THREAD

**Issue by HemilTheRebel** [hashicorp/terraform-provider-google#12550]
# Background

The first paragraph after the code segment in creating a new resource heading is: 

> This new resource includes a few arguments. The name and machine type are simple strings, but boot_disk and network_interface are more complex blocks. You can see all of the supported arguments for the resource [in the GCP provider documentation](https://www.terraform.io/docs/providers/google/r/compute_instance.html).

When I click on the link, it shows me 404. A little research tells me, the link should probably be: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance

**Comment by megan07** [comment]
Merged internally. Thanks!
