### ISSUE TITLE
Unable to manage Cloud Armor adaptive_protection_config

### ISSUE THREAD

**Issue by billyfoss** [hashicorp/terraform-provider-google#12554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
% terraform -v
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.36.0
```

### Affected Resource(s)

* google_compute_security_policy

### Terraform Configuration Files

```tf

resource "google_compute_security_policy" "policy" {
  name = "my-policy"

  rule {
    action   = "deny(403)"
    priority = "1000"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["9.9.9.0/24"]
      }
    }
    description = "Deny access to IPs in 9.9.9.0/24"
  }

  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "default rule"
  }

  /* Optionally add in adaptive_protection_config 
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable = false
    }
  } */
}
```

### Expected Behavior

I expect the policy to be able to be enabled via terraform and disabled via terraform. 
It would be helpful if the provider could see the absence of setting the parameter as equivalent to enabled = false or an empty parameter so that it does not try to remove a parameter that will not go away. 

### Actual Behavior

Several errors were seen

1. When setting adaptive_protection_config with enabled = false initially
````
│ Error: Error updating SecurityPolicy "my-policy": googleapi: Error 400: Invalid value for field 'resource.adaptiveProtectionConfig.layer7DdosDefenseConfig.enable': 'false'. Cannot set layer 7 DDoS options if it's not enabled., invalid
│ 
│   with google_compute_security_policy.policy,
│   on cloud-armor.tf line 6, in resource "google_compute_security_policy" "policy":
│    6: resource "google_compute_security_policy" "policy" {
│ 
````

2. When setting enabled = true and then setting enabled = false, terraform will report success, but the policy will not change.
3. When removing the adaptive_protection_config section after being enabled, it appear to update the config, but it will not change the policy to disabled.  Terraform will continually try to update it. 
4. When manually disabling the policy via gcloud, it will change.  However, it will not match an empty config, so terraform will continually try to update it.
5. When manually disabled, we can add the config with enabled = false and terraform will see it matches and no longer try to update it. 
6. When terraform has never included the adaptive_protection_config section and someone manually enables it on a cloud armor policy, Terraform will see the field and never be able to clear it. 

### Steps to Reproduce

1. `gcloud auth application-default login`
2. `terraform init`
3. `terraform apply` 
4. Modify adaptive_protection_config section as described above
5. `terraform apply`  - see errors or unable permanently change the resource

### References

* https://issuetracker.google.com/issues/246651441 - Issue opened with the Google Cloud API to enable clearing the adaptiveProtectionConfig setting so Terraform configurations that are not setting this can see the expected state.

**Comment by edwardmedia** [comment]
@billyfoss can you share the gcloud command that `manually disables the policy`?

**Comment by billyfoss** [comment]
Instead of 

gcloud compute security-policies update mobile-clients-policy \
   --enable-layer7-ddos-defense

Use 

gcloud compute security-policies update mobile-clients-policy \
   --no-enable-layer7-ddos-defense

**Comment by edwardmedia** [comment]
Here is the payload. 
```
PATCH /compute/v1/projects/myproject/global/securityPolicies/issue12554
{"adaptiveProtectionConfig": {"layer7DdosDefenseConfig": {"enable": false, "ruleVisibility": "STANDARD"}}, "fingerprint": "s0RUUlPlcdQ="}
```
