### ISSUE TITLE
google_bigquery_dataset.default_partition_expiration_ms "must be a whole number" error

### ISSUE THREAD

**Issue by fredzqm** [hashicorp/terraform-provider-google#12561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
> ./terraform_0.12.31 -version
Terraform v0.12.31
+ provider.google v4.35.0
+ provider.google-beta v4.35.0
+ provider.null v3.1.1
```

I am working on upgrading terraform versions incrementally. It would be harder to go beyond 0.13 in one go.

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "logs" {                                                                              
    dataset_id                      = "logs"
    friendly_name                   = "logs"
    location                        = "us-central1"
    default_table_expiration_ms     = "2592000000" # 30 * 24 * 3600000
    default_partition_expiration_ms = "2592000000" # 30 * 24 * 3600000
}
```

### Debug Output

https://gist.github.com/fredzqm/3909b0e1e422bd93ae586af92fb58db8

```
Error: Attribute must be a whole number, got 2.592e+09

  on bigquery-logs.tf line 5, in resource "google_bigquery_dataset" "logs":
   5:   default_table_expiration_ms     = "2592000000" # 30 * 24 * 3600000

Error: Attribute must be a whole number, got 2.592e+09

  on bigquery-logs.tf line 6, in resource "google_bigquery_dataset" "logs":
   6:   default_partition_expiration_ms = "2592000000" # 30 * 24 * 3600000

```

### Expected Behavior

The config should work. 30 day default expiration is a perfectly valid use case. It worked with earlier terraform binary.

### Actual Behavior

It fails due to `Attribute must be a whole number` because the input number is too big. (exceeding MAX_INT?) 

### Steps to Reproduce

1. `terraform apply`

### References

I found a thread about the exact issue, but hasn't been responded to.
https://discuss.hashicorp.com/t/bigquery-table-expiration/36163

**Comment by edwardmedia** [comment]
@fredzqm using your code, it works fine with me. Can you share your debug log?

**Comment by fredzqm** [comment]
https://gist.github.com/fredzqm/3909b0e1e422bd93ae586af92fb58db8

Not sure if I should share the whole content externally. The actual configs are much bigger, so the debug log contains other information, but we should be locate where that error is thrown.

Note that I am trying to upgrade from an `Terraform v0.12.29` to an earlier version. It's possible this is just a backward compatibility issue.

Thanks!

**Comment by edwardmedia** [comment]
@fredzqm probably you need to run the code with the latest versions of terraform and provider. Please let me know the results with the latest versions.

**Comment by fredzqm** [comment]
Okay, so I am trying to upgrade, but there are lots of breaking changes (e.g. 0.13), so I want to churn through them gradually.

Let me reach out to you internally tomorrow. Trying to clean up tech debt with a crazy old version terraform binary `v0.12.29`. It's getting really difficult now.

**Comment by colakong** [comment]
I've encountered this same problem, but only when accidentally using a [32-bit build](https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_386.zip) of terraform instead of [64-bit](https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip).
