### ISSUE TITLE
Documentation: Document the selection of PRODUCT in detail for the command compiling providers

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#12560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the documentation https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers, a command to compile the provider is listed.
Command: make terraform VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" PRODUCT=dataproc 

We can add more details about how PRODUCT is determined to the documentation. 
1. It corresponds to folder names in mmv1/products.
2. handwritten files in mmv1/third_party folder are always compiled, so we can put any value for the PRODUCT (invalid or otherwise).

**Comment by SarahFrench** [comment]
It might be useful to include details about RESOURCE too. Here's something I wrote for some internal HashiCorp onboarding docs if it helps!

>To generate only a specific resources for a product, the command can be updated to also use the RESOURCE variable:
>
```
make terraform VERSION=<version> OUTPUT_PATH=<path to downstream> \
PRODUCT=pubsub RESOURCE=Topic
```
>
>The RESOURCE variable value needs to match the name of the resource inside the api.yaml file for that product. For this example, “Topic” comes from the name of one of the !ruby/object:Api::Resource entries in the objects array inside mmv1/products/pubsub/api.yaml
>
>NOTE: If you’re updating a handwritten resource, you can specify any random resource, or a non-existent generate resource (e.g. PRODUCT=pubsub RESOURCE=Foobar, doesn’t exist and so won’t generate anything, it will only copy and paste the files under third_party/terraform).

**Comment by shuyama1** [comment]
Thanks @SarahFrench! That's super useful! I'll also add it to the documentation.
