### ISSUE TITLE
google_bigquery_table external_data_configuration.csv_options is not setting the right properties in BQ

### ISSUE THREAD

**Issue by bmoyet** [hashicorp/terraform-provider-google#12577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.36.0

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "nodePropertiesExport" {
  dataset_id = google_bigquery_dataset.analytics.dataset_id
  table_id   = "nodeProperties"

  project = var.google_project

  external_data_configuration {
    autodetect            = "false"
    max_bad_records       = 10000
    source_format         = "CSV"
    ignore_unknown_values = "false"

    csv_options {
      quote                 = ""
      field_delimiter       = ","
      allow_quoted_newlines = "false"
      allow_jagged_rows     = "false"
    }

    schema = file("../schemas/analytics/nodePropertiesExport.json")

    source_uris = [
      "gs://av-eu-nodes-export-${lower(var.av_environment)}/*.csv",
    ]
  }
}
```
The schema is 

```json
[
      {
        "mode": "NULLABLE",
        "name": "nodeId",
        "type": "INTEGER"
      },
      {
        "mode": "NULLABLE",
        "name": "ownerId",
        "type": "INTEGER"
      },
      {
        "mode": "NULLABLE",
        "name": "clientId",
        "type": "STRING"
      },
      {
        "mode": "NULLABLE",
        "name": "url",
        "type": "STRING"
      }
    ]
```

### Expected Behavior

My BG table is created with the right options 
      allow_quoted_newlines = "false"
      allow_jagged_rows     = "false"

### Actual Behavior

It is not. On the left you can see a table I created manually which allow me to query my data correctly. On the right the table is generated by terraform and my query is not working properly due to the missing option (The change of the source does not matter there is only one csv file in the bucket).

![Screenshot from 2022-09-16 11-33-07](https://user-images.githubusercontent.com/7815879/190606703-0f282fd3-cdf0-4293-9853-74cbde4f9f03.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@bmoyet can you share your debug log?

**Comment by bmoyet** [comment]
Here you go :

https://gist.github.com/bmoyet/fbf1c528dda684023710ba5cfdf15010
