### ISSUE TITLE
google_compute_resource_policy not handling minor changes

### ISSUE THREAD

**Issue by perios101** [hashicorp/terraform-provider-google#12579]
### **Terraform Version**
1.1.5

### **Affected Resource(s)**

- google_compute_resource_policy

### **Terraform Configuration Files**

Changing from:
```
resource "google_compute_instance" "whatever-instance" {
  project      = local.gcp_project
  name         = "whatever-instance"
  machine_type = "e2-medium"
  zone         = local.gcp_zone

  boot_disk {
    initialize_params {
      image = "whatever-vm"
    }
  }

  resource_policies = [google_compute_resource_policy.vm-resource-policy.self_link]
}

resource "google_compute_resource_policy" "vm-resource-policy" {
  project     = local.gcp_project
  name        = "policy"
  region      = local.gcp_region
  description = "Start and stop VMinstance"
  instance_schedule_policy {
    vm_start_schedule {
      schedule = "30 3 * * 1-5"
    }
    vm_stop_schedule {
      schedule = "0 12 * * 1-5"
    }
    time_zone = "UTC"
  }
}
```
...to:
```
resource "google_compute_instance" "whatever-instance" {
  project      = local.gcp_project
  name         = "whatever-instance"
  machine_type = "e2-medium"
  zone         = local.gcp_zone

  boot_disk {
    initialize_params {
      image = "whatever-vm"
    }
  }

  resource_policies = [google_compute_resource_policy.vm-resource-policy.self_link]
}

resource "google_compute_resource_policy" "vm-resource-policy" {
  project     = local.gcp_project
  name        = "policy"
  region      = local.gcp_region
  description = "Start and stop VMinstance"
  instance_schedule_policy {
    vm_start_schedule {
      schedule = "30 3 * * 1-5"
    }
    vm_stop_schedule {
      schedule = "0 18 * * 1-5"
    }
    time_zone = "UTC"
  }
}
```

### **Expected Behavior**
Terraform should replace the resource policy (along with VM instance attachment), since any minor change to a schedule will force replacement of the resource.

This is especially important for clean CI only environments, where IaaC can only be run from CI, not from local developer machines. And since we're talking IaaC, using UI to manually detach the policy for Terraform to succeed would be directly contradicting IaaC concepts.

**### Actual Behavior**
Terraform fails to replace the resouce policy, fails as it's unable to handle resource attachment.

```
Error: Error when reading or editing ResourcePolicy: googleapi: Error 400: The resource_policy resource 'projects/myproject/regions/europe-west2/resourcePolicies/policy' is already being used by 'projects/myproject/zones/europe-west2-a/instances/whatever-instance', resourceInUseByAnotherResource
```

### **Steps to Reproduce**
terraform apply
change any parameter in the instance_schedule_policy of the google_compute_resource_policy resource
terraform apply

**Comment by edwardmedia** [comment]
@perios101 can you share the full debug log?

**Comment by edwardmedia** [comment]
@perios101 is this still an issue?

**Comment by slevenick** [comment]
Unfortunately we don't really have control over this within the provider. You could handle this as a two-step apply, removing the policy first or deleting the instance and then recreating, but we don't have control over this level of resource ordering within the provider without making the resource policy field entirely ForceNew which would be harmful in a lot of other cases
