### ISSUE TITLE
Database replacement on patch bumps

### ISSUE THREAD

**Issue by jsbroks** [hashicorp/terraform-provider-google#12576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.2.x

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "postgres" {
  name                    = "doesn't matter"
  database_version = "MYSQL_8_0"
}
```

```tf
resource "google_sql_database_instance" "postgres" {
  name                    = "doesn't matter"
  database_version = "MYSQL_8_0_29"
}
```

### Expected Behavior

Terraform should not replace the database since this is an inline operation.

### Actual Behavior

Terraform tries to replace database instance.

### Steps to Reproduce

1. `terraform apply`
1. change database_version to a patch
1. `terraform apply`

**Comment by edwardmedia** [comment]
@jsbroks where did you see replacement is not necessary? Do you have steps to achieve using other tools?

**Comment by edwardmedia** [comment]
@jsbroks is this still an issue?

**Comment by edwardmedia** [comment]
@jsbroks closing this assuming it is no longer an issue
