### ISSUE TITLE
Support multiple API's with same terraform resource product namespace

### ISSUE THREAD

**Issue by sandmman** [hashicorp/terraform-provider-google#12572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We're creating a new set of terraform resources using mmv1 for the GKE On-Prem API. It's a separate API (gkeonprem.googleapis.com) from GKE (container.googleapis.com); however, we'd like the resource name to have the container prefix rather than our service name. Something like: `google_container_bare_metal_cluster`.

Following the MMV1 docs, results in google_gkeonprem_bare_metal_cluster. As far as I can tell, the resource name is taken from the 'name' field in products/gkeonprem/api.yaml file and the snakecased resource.

The Container product and product folder is already taken by GKE. We'd like to be able to override our product name without it conflicting with generated files from GKE.

When we attempt to change the Product.name field in the mmv1 api.yaml file. We end up with the error:
```
generate': google-beta/container_operation.go was already modified during this run.. check to see if there is both a .go and .go.erb version of this file (RuntimeError)
```

### New or Affected Resource(s)

* google_gkeonprem_bare_metal_cluster
* google_gkeonprem_bare_metal_node_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://yaqs.corp.google.com/eng/q/3279858578818596864#a1
* My mmv1 fork: https://github.com/sandmman/magic-modules/blob/main/mmv1/products/gkeonprem/api.yaml](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fsandmman%2Fmagic-modules%2Fblob%2Fmain%2Fmmv1%2Fproducts%2Fgkeonprem%2Fapi.yaml

**Comment by rileykarson** [comment]
It's intentional that services are split by service endpoint in their provider representations, and merging multiple endpoints into a single product prefix is undesirable.

Note that this is possible technically with [`legacy_name`](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/overrides/terraform/resource_override.rb#L34-L38), but that's a feature used to support handwritten resources alongside generated one with a consistent naming convention when the handwritten resources differ from the generator default.
