### ISSUE TITLE
Add case-insensitive feature while creating datasets in BigQuery

### ISSUE THREAD

**Issue by ruchi-goyal-04** [hashicorp/terraform-provider-google#12586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi Team,

Google Cloud Platform has just launched a feature of creating case-insensitive datasets in BigQuery. Please refer the link below:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#schema_option_list

We are able to achieve this via GCP console using the below command:
CREATE SCHEMA DS1 OPTIONS(is_case_insensitive=true);

We are maintaining our whole infrastructure from the terraform itself, hence we need to have this feature to be enabled via terraform while creating datasets as we do not want our datasets names to be case-sensitive due to our business requirements.

Please help us to achieve this via terraform as soon as possible, as this is on a high priority for us.

Thanks,
Ruchi Goyal

### New or Affected Resource(s)

google_bigquery_dataset

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
Example configuration:

resource "google_bigquery_dataset" "dataset" {
  dataset_id                  = "example_dataset"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "EU"
  default_table_expiration_ms = 3600000
  **is_case_insensitive      = true**
}

### References

* #0000

**Comment by melinath** [comment]
It looks like this would require running SQL because it's part of the internal database state. We generally try to avoid managing database state via terraform & just stick to infrastructure.

**Comment by bquinart** [comment]
Hi
This feature became GA on 15/02/2023. And now allows to set or update through the REST API.
Can this issue be reconsidered based on that?
Thanks
Bruno

**Comment by bquinart** [comment]
Ability to set case insensitive option was added with #14031
