### ISSUE TITLE
data.google_project doesn't accept value in format 'projects/my-project-id' after resent update

### ISSUE THREAD

**Issue by ar-qun** [hashicorp/terraform-provider-google#12603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/fluxcd/flux v0.18.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/google v4.37.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/integrations/github v5.1.0
```

### Affected Resource(s)

* data.google_project

### Terraform Configuration Files

```tf

resource "google_project" "this" {
   name = "my-project-name"
   project_id = "my-project-id"
}
data "google_project" "this" {
  project_id = google_project.id
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

My expectation is that it should just work without extra steps, but I get a sense that there might be an overall naming convention.

### Actual Behavior

│ Error: "projects/my-project-id" project_id must be 6 to 30 with lowercase letters, digits, hyphens and start with a letter. Trailing hyphens are prohibited.
│ 
│   with data.google_project.this,
│   on main.tf line 38, in data "google_project" "this":
│   38:   project_id = module.project.project.id

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The current format would imply that I need to use `google_project.project_id` but that will create a dependency issue where data source would try to access the project before it is created. This is why I use `google_project.id` here in the first place.

`projects/my-project-id` is also a valid form to specify project for GCP. That is why it was working here before.

### References

* Was broken in #12553 because of the project_id validation.

**Comment by dip10du** [comment]
our team is encountering the exact same issue as well!

**Comment by rileykarson** [comment]
fyi @melinath @sanghaniJ this seems like it needs to be expanded to include this format or reverted.
