### ISSUE TITLE
provider "registry.terraform.io/-/google" produced an unexpected new value for was present, but now absent.

### ISSUE THREAD

**Issue by ranuka123** [hashicorp/terraform-provider-google#12604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.3

### Affected Resource(s)

google_compute_firewall

### Panic Output

```
Error: Provider produced inconsistent result after apply

When applying changes to google_compute_firewall.healthcheck_firewall,
provider "[registry.terraform.io/-/google](https://www.google.com/url?sa=D&q=http%3A%2F%2Fregistry.terraform.io%2F-%2Fgoogle)" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

This is an intermittent issue we experience.

**Comment by edwardmedia** [comment]
@ranuka123 can you provide a config and steps that can repro the issue?

**Comment by ranuka123** [comment]
The error is vaguely correct. The resource was being deleted by a different actor and terraform wasn't seeing it when it does its state check after creation (I'm assuming that's what it does based on the error). So closing this.
