### ISSUE TITLE
Ability to create service directory namespace for  Private Service Connect

### ISSUE THREAD

**Issue by bakuljajan** [hashicorp/terraform-provider-google#12602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current way to configure Private Service connect via terraform is to configure `google_compute_global_forwarding_rule` and all the service directory configurations will be auto-generated. But when we try to configure the service directory via console manually, and we can choose the type of the service directory whether it is `Standard` or `Private Service Connect`.

Having the same capability in terraform would be very helpful, especially in configuring the region where the service directory is hosted.

![image](https://user-images.githubusercontent.com/88089627/191255571-d5524593-126f-46d5-9ebc-82c31e5f0d6e.png)

Also, I found this issue which might be related #9758.

### New or Affected Resource(s)

* google_service_directory_service
* google_service_directory_namespace
* google_service_directory_endpoint

### Potential Terraform Configuration

```tf
resource "google_service_directory_namespace" "example" {
  provider     = google-beta
  namespace_id = "example-namespace"
  location     = "asia-southeast2"
  type         = "psc"   # Service directory namespace for Private Service Connect
}

resource "google_service_directory_service" "example" {
  provider   = google-beta
  service_id = "example-service"
  namespace  = google_service_directory_namespace.example.id
}

resource "google_service_directory_endpoint" "example" {
  provider    = google-beta
  endpoint_id = "example-endpoint"
  service     = google_service_directory_service.example.id

  metadata = {
    stage  = "prod"
    region = "us-central1"
  }

  address = "1.2.3.4"
  port    = 443
  network = "projects/1234/global/networks/abc-def-ghi"
}
```

### References

* https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#create-endpoint
* https://console.cloud.google.com/net-services/service-directory/services/create

**Comment by c2thorn** [comment]
The referenced guide uses a Compute Forwarding Rule to create the namespace. This should be available via https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#namespace

Please let us know otherwise, with specific API reference documentation.

**Comment by bakuljajan** [comment]
Hello @c2thorn, I've tried using the `google_compute_forwarding_rule` code below.

```tf
resource "google_compute_forwarding_rule" "psc" {
  provider = google-beta
  for_each = var.enable_create_vpc ? local.private_service_connect : {}

  project               = var.project
  name                  = "psc1234"
  region                = var.region
  target                = "all-apis"
  network               = module.vpc[0].network_name
  ip_address            = module.psc_ip[each.key].id
  load_balancing_scheme = ""

  service_directory_registrations {
    namespace = var.private_service_connect.namespace
    service   = var.private_service_connect.service
  }
}
```

But I'm getting errors like this.

```tf
│ Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.target': 'all-apis'. Invalid target. Must be either a valid In-Project Forwarding Rule Target URL, a valid Service Attachment URL, or a supported Google API bundle (global-only)., invalid
```

Do you have any examples for creating via `google_compute_forwarding_rule` ?
