### ISSUE TITLE
Billing Budget creation failing when adding pubsub_topic rule without monitoring_notification_channels

### ISSUE THREAD

**Issue by guptamukul-google** [hashicorp/terraform-provider-google#12613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* Terraform v1.2.8

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.


provider "google" {
  alias  = "impersonated"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email"
  ]
}

data "google_service_account_access_token" "default" {
  count                  = length(var.resource_creator_identity) != 0 ? 1 : 0
  provider               = google.impersonated
  scopes                 = ["userinfo-email", "cloud-platform"]
  target_service_account = var.resource_creator_identity
  lifetime               = "1800s"
}

provider "google" {
  access_token = length(var.resource_creator_identity) != 0 ? data.google_service_account_access_token.default[0].access_token : null
}

provider "google-beta" {
  access_token = length(var.resource_creator_identity) != 0 ? data.google_service_account_access_token.default[0].access_token : null
}

resource "google_billing_budget" "budget2" {

  billing_account = var.billing_account_id
  display_name    = "Billing Budget"
  budget_filter {
    projects               = toset(["projects/${var.project_id}"])
  }
  amount {
    specified_amount {
      units         = "100"
      currency_code = "USD"
    }
  }
  threshold_rules {
    threshold_percent = 0.5
  }

  all_updates_rule {
    disable_default_iam_recipients   = true
    pubsub_topic                     = "projects/${var.project_id}/topics/${var.pub_sub_topic}"
    monitoring_notification_channels = var.notification_channels
  }
}

variable "resource_creator_identity" {
  description = "Terraform Service Account which will be creating the GCP resources.
  type        = string
  default     = ""
}

variable "billing_account_id" {
  description = "Billing Account associated to the GCP Resources."
  type        = string
}

variable "project_id" {
  description = "Project ID of the GCP Project."
  type        = string
}

variable "pub_sub_topic" {
  description = "PubSub Topic Name."
  type        = string
}

variable "notification_channels" {
  description = "The full resource name of a monitoring notification channel in the for `projects/{project_id}/notificationChannels/{channel_id}`."
  type        = set(string)
  default     = []
}
```

### Debug Output

https://gist.github.com/guptamukul-google/bd13b85cb71ca24bb27e36c682647754

### Panic Output

NA

### Expected Behavior

Billing Budget should have been created with the referred pubsub topic attached when when there is no **monitoring_notification_channels** set i.e. `notification_channels` variable is kept as default (`[]`)

### Actual Behavior

Billing Budget creation is failing when adding pubsub_topic rule while keeping monitoring_notification_channels as `[]` but as soon as we set some monitoring_notification_channels i.e. `notification_channels = ["projects/{project_id}/notificationChannels/{channel_id}"]` the Billing budget gets created and the pubsub topic is also attached succesfully.

### Steps to Reproduce

1. `terraform apply`
2. Provide inputs to the required variables.

### Important Factoids

I am using Service account to create Billing Budget because we cannot us a user account to create the same.

### References

*

**Comment by edwardmedia** [comment]
@guptamukul-google I have tested below config which does not have `monitoring_notification_channels`. It works fine. Can you try it?  

```tf
resource "google_billing_budget" "devbudget" {
  billing_account = "123456-123456-123456"
  display_name    = "issue12613"

  budget_filter {
    projects        = ["projects/myproject"]
    calendar_period = "YEAR"
  }

  amount {
    specified_amount {
      units = "100"
    }
  }

  all_updates_rule {
    disable_default_iam_recipients   = true
    pubsub_topic                     = google_pubsub_topic.example.id
  }
}

resource "google_pubsub_topic" "example" {
  name = "issue12613"

  labels = {
    foo = "bar"
  }
  message_retention_duration = "86600s"
}
```

**Comment by edwardmedia** [comment]
@guptamukul-google is this still an issue?

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer an issue
