### ISSUE TITLE
GKE Nodepool adding tags & labels should not recreate

### ISSUE THREAD

**Issue by Evesy** [hashicorp/terraform-provider-google#12620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_container_node_pool

Previous issue: https://github.com/hashicorp/terraform-provider-google/issues/2532

The GKE API supports updating tags on an existing node pool; an operation is kicked off which adds network tags to all the existing node pools, similar to a version upgrade operation.

Currently, modifying tags on the `google_container_node_pool` resource causes it to be deleted & recreated. It feels like this behaviour should be changed to support the inline updating of existing node pools

## Maintainer notes

- [x] Update support for labels (https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels#update-node-pool-labels)
    * Added in [4.48.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4480-january-9-2023)
- [ ] Update support for tags (https://cloud.google.com/kubernetes-engine/docs/how-to/autopilot-network-tags#standard_1)

**Comment by g-awmalik** [comment]
This also applies to labels also reported [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1412). Seems like there is a [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/6599) but needs to account for labels as well.

**Comment by g-awmalik** [comment]
@edwardmedia - would you like us to create another issue for label or can we track it here?

**Comment by edwardmedia** [comment]
@g-awmalik we can track labels over here. Let me update the subject

**Comment by LucaPrete** [comment]
Hello, [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/6941) is the initial PR (under review) that allows to update nodepool labels without causing the nodepools to be re-created.

**Comment by korenlev** [comment]
If the node_pool is configured with auto scaling enabled then Update any metadata in node pool will FAIL with the following google error:

"Updates for 'labels' are not supported in node pools with autoscaling enabled (as a workaround, consider temporarily disabling autoscaling or recreating the node pool with the updated values.)

You can publish this error back to the user, so he can decide to use this temp workaround by google or not.

**Comment by michaelbannister** [comment]
According to [this doc](https://cloud.google.com/kubernetes-engine/docs/how-to/update-existing-nodepools#limitations) since GKE 1.23.4-gke.300 nodepool labels may be modified in-place even if cluster auotscaler is enabled.

**Comment by michaelbannister** [comment]
Ah, just found this was released in provider version 4.48.0 ([changelog](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4480-january-9-2023))– should this issue be closed?

**Comment by rileykarson** [comment]
Labels are possible, but network tags are not. I'll update the issue. It does seem possible to update them: https://cloud.google.com/kubernetes-engine/docs/how-to/autopilot-network-tags#standard_1

**Comment by melinath** [comment]
I believe this was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6599 - even though the title of the PR (and the release note) talk about labels, the actual implementation seems to add support for updating network tags.
