### ISSUE TITLE
Add feature GKE cluster-scoped DNS zone in google_dns_managed_zone & google_dns_response_policy

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#12629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_dns_managed_zone
* google_dns_response_policy

### Potential Terraform Configuration

```tf
resource "google_dns_managed_zone" "example-zone" {
  name        = "example-zone"
  dns_name    = "example-${random_id.rnd.hex}.com."
  description = "Example DNS zone"
  visibility = "private"
  gkeclusters = "projects/my-project/locations/us-east1-a/clusters/my-cluster"
  location = "us-east1-a"
}

```

```tf
resource "google_dns_response_policy" "example-response-policy" {
  provider = google-beta

  response_policy_name = "example-response-policy"
  description = "Example DNS response policy"
  gkeclusters = "projects/my-project/locations/us-east1-a/clusters/my-cluster"
  location = "us-east1-a"
}

```

### References

* [Configure a GKE cluster scope](https://cloud.google.com/dns/docs/zones/configure-scopes#api)
* [Configure a zonal GKE cluster-scoped zone](https://cloud.google.com/dns/docs/zones/configure-zonal-cluster-scopes#api)

**Comment by rileykarson** [comment]
Seems to have been resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/6814
