### ISSUE TITLE
google_compute_interconnect_attachment  Error 400: The resource is not ready

### ISSUE THREAD

**Issue by rjouhann** [hashicorp/terraform-provider-google#12631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
# terraform -v
Terraform v1.3.0
on linux_amd64
```

### Affected Resource(s)

* google_compute_interconnect_attachment

### Debug Output

[Download logs](https://www.dropbox.com/scl/fo/v9m2drkh6pnnr4f9oc3ow/h?dl=0&rlkey=qrtwopoq4hpfffx191ot4zfvq)

### Terraform Configuration Files

Find an example [here](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/use-cases/cloud_router_google_ipsec)

### Expected Behavior

The Google Interconnect should get deleted correctly the first time user run terraform destroy command.

### Actual Behavior

The Google Interconnect destroy isn't working and error out with the following error. After running a second time the terraform destroy command, the deletion works.

```
│ Error: Error when reading or editing InterconnectAttachment: googleapi: Error 400: The resource 'projects/prefab-setting-357415/regions/us-west1/interconnectAttachments/demo-pf-gcp-vpn-next-crab' is not ready, resourceNotReady
│ 
│ 
╵
```

### Steps to Reproduce

1. Create a Google Interconnect with a Partner and setup the BGP connection.
2. Run the terraform destroy command

Note: the problem does not happen when the Google Interconnect isn't activated. It must be activated and BGP session established.

### References

* https://docs.packetfabric.com/cr/add/google/

b/302672797

**Comment by edwardmedia** [comment]
@rjouhann the link to your config isn't working. Mind share the config here?

If there are other resources involved, could it be a timing issue?

**Comment by rjouhann** [comment]
@edwardmedia my bad, the example was in a different [branch](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/update_use_case_cloud_router_v0.3/examples/use-cases/cloud_router_google_ipsec).

I confirm all resources are correctly created before I call the destroy. I will get the debug output as well in a bit.

**Comment by mruppaner** [comment]
@rileykarson looks like this is can be closed as per the last comment by @rjouhann
