### ISSUE TITLE
google_artifact_registry_repository Fails with `artifactregistry.repositories.create`

### ISSUE THREAD

**Issue by heph2** [hashicorp/terraform-provider-google#12640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.9

### Affected Resource(s)

* google_artifact_registry_repository

### Terraform Configuration Files

```
resource "google_project_service" "artifactregistry_googleapis_com" {
  project = var.project_id
  service = "artifactregistry.googleapis.com"
}

# Docker Artifact Hub
resource "google_artifact_registry_repository" "docker-repo" {
  location      = "europe-west8"
  project       = var.project_id
  repository_id = "docker-repo"
  format        = "DOCKER"
  depends_on = [google_project_service.artifactregistry_googleapis_com]
}
```

### Expected Behavior

Should create a docker repository.
Also tried manually enabling the api using `gcloud` instead of terraform. Same result

### Actual Behavior

```
Error: Error creating Repository: googleapi: Error 403: Permission 'artifactregistry.repositories.create' denied on resource '//artifactregistry.googleapis.com/projects/abc-project/locations/europe-west8' (or it may not exist).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "artifactregistry.googleapis.com",
│     "metadata": {
│       "permission": "artifactregistry.repositories.create",
│       "resource": "projects/abc-project/locations/europe-west8"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│
│   with google_artifact_registry_repository.docker-repo,
│   on main.tf line 87, in resource "google_artifact_registry_repository" "docker-repo":
│   87: resource "google_artifact_registry_repository" "docker-repo" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@heph2 what account are you using to run the terraform (and gcloud)? Does the account have permission of `artifactregistry.repositories.create`? I see you have enabled the API (service), but you also need to provide iam for the account through other resources. Does this make sense?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_member

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#google_service_account_iam_member

**Comment by rvillane** [comment]
I'm running into a very similar issue.  The following is my terraform code:
```
resource "google_artifact_registry_repository" "harness-pov-artifact-registry-docker" {
  provider = google-beta

  project = var.gcp_project_id
  location      = "us"
  repository_id = "artifact-registry-docker"
  format        = "DOCKER"  
}
```

the error message after running `terraform apply` is:

```
google_artifact_registry_repository.artifact-registry-docker: Creating...
╷
│ Error: Error creating Repository: googleapi: Error 403: Permission 'artifactregistry.repositories.create' denied on resource '//artifactregistry.googleapis.com/projects/my-project/locations/us' (or it may not exist).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "artifactregistry.googleapis.com",
│     "metadata": {
│       "permission": "artifactregistry.repositories.create",
│       "resource": "projects/my-project/locations/us"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ 
│   with google_artifact_registry_repository.artifact-registry-docker,
│   on artifact-registry.tf line 1, in resource "google_artifact_registry_repository" "artifact-registry-docker":
│    1: resource "google_artifact_registry_repository" "artifact-registry-docker" {
```

In my case, even with this error, the repository was actually created and can pull/push container into it.  Now I'm getting the error message above every time the apply command is executed.  In GCP, the service account used to run terraform is showing as Owner, which is confusing as it should have more than enough IAM permissions.

Any ideas ?

**Comment by edwardmedia** [comment]
@rvillane besides `owner`, it looks like you do need to add at least below two permissions to the terraform runner to complete the entire `apply` execution. 

```
artifactregistry.repositories.create
artifactregistry.repositories.get
```

Closing this issue now. Feel free to reopen if you want to continue the conversation. Thanks
