### ISSUE TITLE
Plan fails when a resource depends on `google_compute_address`

### ISSUE THREAD

**Issue by juicemia** [hashicorp/terraform-provider-google#12645]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.2.1
+ provider registry.terraform.io/hashicorp/http v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* google_compute_address
* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_address" "this" {
  count = 2
  name  = "nat-${count.index}"
}

resource "google_compute_firewall" "this" {
  name        = "allow-nat"
  network     = data.google_compute_network.thing.self_link
  description = "Allow the NAT IP's."

  target_service_accounts = [data.google_service_account.thing.email]
  source_ranges           = google_compute_address.this[*].address
  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }
}
```

### Expected Behavior

Terraform should have been able to create a plan with a firewall that depends on a`google_compute_address`.

The plan should show the following for the firewall (this was taken using module version `3.90.1`):

```
      + source_ranges           = (known after apply)
```

### Actual Behavior

Terraform fails to create a plan with the following error:

```
╷
│ Error: 1 error occurred:
│ 	* one of source_tags, source_ranges, or source_service_accounts must be defined
│
│
│
│   with google_compute_firewall.this,
│   on networking.tf line 116, in resource "google_compute_firewall" "this":
│  116: resource "google_compute_firewall" "this" {
│
╵
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by juicemia** [comment]
For anybody who might also be having this issue, downgrading to `3.90.1` will get a successful plan. Downgrading to `4.0.0` gets the same error.

**Comment by juicemia** [comment]
Running plan with the provider on `4.0.0` will work if the address is specified on the `google_compute_address` resource like this:

```
resource "google_compute_address" "this" {
  count   = 1
  name    = "nat-${count.index}"
  address = "192.169.1.0"
}
```

However, this doesn't solve my use case because I'm using this address for a cloud NAT, so it needs to be a public external address, which means I have to leave the `address` field blank.

**Comment by juicemia** [comment]
It doesn't make sense to me because using version `3.90.1` correctly fills in values for that required field.

When `terraform plan` is run using that provider version I can see that the `source_ranges` requirement is fulfilled, and it's value is `(known after apply)` because the `google_compute_address` hasn't actually been created yet. When upgrading to provider version `4.x` somehow the provider is now failing to satisfy the requirement. This isn't what I would expect to experience according to the docs of what the expected behavior should be. I would expect the provider to still be able to correctly wire things up.

**Comment by edwardmedia** [comment]
@juicemia that is why it is called a **breaking-change**. An issue is expected. You may choose to keep **v3.90.1** or delete the state and import the resource with new version. I agree it is not the optimal and we have done out best to minimize the impacts

**Comment by juicemia** [comment]
I'm sorry maybe I've been unclear about what exactly the issue is. The `google_compute_firewall` has a breaking change and it's documented: `source_ranges` is now required whereas it wasn't before.

The change you linked is breaking because it changes the API of `google_compute_firewall` in a way that will break people who were not setting any of the `source_` parameters. What I'm reporting is a regression in the `google_compute_address` resource.

**Comment by edwardmedia** [comment]
@slevenick what do you think about this?

**Comment by slevenick** [comment]
If you apply the address first does it work? What are the actual values coming out of the .address value from that resource?

This is strange, because it seems like the address value coming out of the `google_compute_address` is empty, but I would imagine they do have values. Maybe because it's Optional+Computed there is plan-time unknownness that is being passed to the firewall resource?

**Comment by slevenick** [comment]
Oh, I believe this was fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5526

Upgrading to a newer version of the provider should fix it

**Comment by juicemia** [comment]
Running the latest module version has the same issue. I was doing this in a brand new project.

As soon as I get some time I'll try your suggestion of running `google_compute_address` first just to see what it's outputting.

**Comment by slevenick** [comment]
> Running the latest module version has the same issue. I was doing this in a brand new project.
> 
> As soon as I get some time I'll try your suggestion of running `google_compute_address` first just to see what it's outputting.

You're seeing this with version 4.30+ of the provider?

**Comment by juicemia** [comment]
I see this on version 4.X of the provider.

**Comment by slevenick** [comment]
What version specifically?
