### ISSUE TITLE
Support maxTimeTravelHours in google_bigquery_dataset

### ISSUE THREAD

**Issue by pmjacinto** [hashicorp/terraform-provider-google#12654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please support setting `maxTimeTravelHours` in the `google_bigquery_dataset` resource. It's a new field in the dataset API: https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets.

### New or Affected Resource(s)

* google_bigquery_dataset

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset" "test" {
  project    = "proj-id"
  dataset_id = "dataset-id"
  location   = "EU"
  # new field
  max_time_travel_hours = 168
}
```

**Comment by melinath** [comment]
b/253299674
