### ISSUE TITLE
Folder log sink - Missing uniqueWriterIdentity

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#12660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As per https://cloud.google.com/logging/docs/reference/v2/rest/v2/folders.sinks/create we are able to provide unique writer identity but this is currently not supported in the folder log sink (supported in project sink). 

### New or Affected Resource(s)

* google_logging_folder_sink

### Potential Terraform Configuration

```tf
resource "google_logging_folder_sink" "my-sink" {
  name   = "my-sink"
  description = "some explanation on what this is"
  folder = google_folder.my-folder.name
  
  # Use a unique writer (creates a unique service account used for writing)
  unique_writer_identity = true

  # Can export to pubsub, cloud storage, or bigquery
  destination = "storage.googleapis.com/${google_storage_bucket.log-bucket.name}"

  # Log all WARN or higher severity messages relating to instances
  filter = "resource.type = gce_instance AND severity >= WARNING"
}
```

### References

* #0000

**Comment by melinath** [comment]
b/253298732

**Comment by rileykarson** [comment]
From the API documentation:

```
Optional. Determines the kind of IAM identity returned as writerIdentity in the new sink. If this value is omitted or set to false, and if the sink's parent is a project, then the value returned as writerIdentity is the same group or service account used by Cloud Logging before the addition of writer identities to this API. The sink's destination must be in the same project as the sink itself.

If this field is set to true, or if the sink is owned by a non-project resource such as an organization, then the value of writerIdentity will be a unique service account used only for exports from the new sink. For more information, see writerIdentity in [LogSink](https://cloud.google.com/logging/docs/reference/v2/rest/v2/billingAccounts.sinks#LogSink).
```

Based on that, I'm not sure that setting this will do anything. The sink's parent isn't a project, and the documentation suggests that the unique identity only needs to be controlled on project-level sinks. However, even if that isn't the case, it appears that we set it to `true` all the time on this resource anyways (https://github.com/GoogleCloudPlatform/magic-modules/blob/4cf369106686100913600edb5e88d9f778730a99/mmv1/third_party/terraform/resources/resource_logging_folder_sink.go#L54). A comment there suggests the API enforced that all clients need to send it as `true` all the time.

GCP resources sometimes reuse schemas even when the resources aren't wholly identical. Unfortunately, reference documentation is automatically generated and that can lead to cases like this where they're confusing!
