### ISSUE TITLE
Dataplane V2 is immutable but resource updated in place

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/terraform-provider-google#12676]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```none
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.38.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.kubernetes_engine.google_container_cluster.this will be updated in-place
  ~ resource "google_container_cluster" "this" ***
      + datapath_provider           = "ADVANCED_DATAPATH"
        id                          = "projects/my-project-tf1ed0cd-sb/locations/us-east1/clusters/development-tools-us-east1"
        name                        = "development-tools-us-east1"
        # (27 unchanged attributes hidden)

        # (22 unchanged blocks hidden)
    ***
```

### Expected Behavior

Cluster should be destroyed and recreated

### Actual Behavior

Apply ran fine but obviously cluster was not updated.
### Steps to Reproduce

Build cluster with default datapath_provider then change to "ADVANCED_DATAPATH"

### References

Other folks see the same behavior: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/656#issuecomment-1254091835

**Comment by edwardmedia** [comment]
Can repro on `datapath_provider  = "LEGACY_DATAPATH"`

It looks like `ADVANCED_DATAPATH` can't be used as `IPAllocationPolicy.UseIPAliases` has not be implemented yet

│ Error: googleapi: Error 400: Clusters with DatapathProvider=ADVANCED_DATAPATH must set IPAllocationPolicy.UseIPAliases to true., badRequest
│ 
│   with google_container_cluster.primary,
│   on main.tf line 6, in resource "google_container_cluster" "primary":
│    6: resource "google_container_cluster" "primary" {

**Comment by edwardmedia** [comment]
b/254123801

**Comment by edwardmedia** [comment]
API teams has confirmed this field currently is immutable but will make it mutable sometime in 2023.
