### ISSUE TITLE
Cloud Run - problem with "run.googleapis.com/ingress" annotation

### ISSUE THREAD

**Issue by jw-websensa** [hashicorp/terraform-provider-google#12688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.2.9

### Affected Resource(s)

* google_cloud_run_service

### Problem

I have added a Cloud Run service to my terraform which looks like this:
```tf
resource "google_cloud_run_service" "default" {
  name = "${var.base_name}-cloud-run"

  location = var.region

  template {
    spec {
      service_account_name = google_service_account.default.email

      containers {
        image = var.image_tag

        dynamic env {
          for_each = local.cloud_run_envs
          content {
            name  = env.key
            value = env.value
          }
        }

        ports {
          container_port = local.port
          protocol       = "TCP"
        }

        resources {
          limits = {
            cpu    = var.cpu_limit
            memory = var.memory_limit
          }
        }
      }
    }

    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale"        = var.max_replicas
        "run.googleapis.com/vpc-access-connector" = google_vpc_access_connector.mongodb.name
        "run.googleapis.com/ingress"              = "internal"
      }
    }
  }

  depends_on = [google_artifact_registry_repository_iam_member.reader]
}
```
For some reason, when I try to deploy it, I get this message:
```
│ Error: Error creating Service: googleapi: Error 400: spec.template.metadata.annotations: Annotation 'run.googleapis.com/ingress' is not supported on resources of kind 'Revision'. Supported kinds are: Service
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Annotation 'run.googleapis.com/ingress' is not supported on resources of kind 'Revision'. Supported kinds are: Service",
│         "field": "spec.template.metadata.annotations"
│       }
│     ]
│   }
│ ]
│ 
│   with module.search.google_cloud_run_service.default,
│   on modules/search/cloud_run.tf line 7, in resource "google_cloud_run_service" "default":
│    7: resource "google_cloud_run_service" "default" {
│ 
╵
```
I checked documentation and it seems like nothing changed. Moveover, I have more cloud run services deployed with this annotations before and they work properly. Any clue why is it happening?

**Comment by Metroxe** [comment]
Also receiving the same issue, starting today. But mine is with `maxScale`. Currently looking for a solution. My example is below...

```hcl
resource "google_cloud_run_service" "web" {
  name                       = "${var.stage}-web"
  location                   = var.region
  autogenerate_revision_name = true

  template {
	spec {
	  service_account_name = local.service_account_name
	  timeout_seconds      = 30
	  container_concurrency = 80

	  containers {
		image = data.external.web_images.result.hasGCRTag == "true" && !var.force_placeholders ? "gcr.io/${data.google_project.project.project_id}/images/web:${var.stage}" : local.default_image
		resources {
		  limits = {
			memory = "512Mi"
			cpu    = 1
		  }
		}
	  }
	}
  }

  metadata {
	annotations = {
	  "autoscaling.knative.dev/minScale" = "0"
	  "autoscaling.knative.dev/maxScale" = "20"
	  "run.googleapis.com/ingress"       = "all"
	}

	labels = {
	  ecosystem: var.stage
	}

  }

  traffic {
	percent         = 100
	latest_revision = true
  }

  lifecycle {
	ignore_changes = [
	  template[0].metadata[0].annotations["run.googleapis.com/client-name"],
	  template[0].metadata[0].annotations["run.googleapis.com/client-version"],
	  template[0].metadata[0].annotations["client.knative.dev/user-image"],
	  template[0].spec[0].service_account_name
	]
  }

  timeouts {
	create = "2m"
	update = "2m"
  }
}
```

```
│ Error: Error creating Service: googleapi: Error 400: metadata.annotations: Annotation 'autoscaling.knative.dev/maxScale' is not supported on resources of kind 'Service'. Supported kinds are: Revision
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Annotation 'autoscaling.knative.dev/maxScale' is not supported on resources of kind 'Service'. Supported kinds are: Revision",
│         "field": "metadata.annotations"
│       }
│     ]
│   }
│ ]
```

**Comment by Metroxe** [comment]
I temporarily was able to solve this issue by commenting out the annotations for the initial creation. Then after deployment I put them in again and re-applied. Not ideal, but solved the issue for the time being for me.

However interestingly enough in my deployment, I have 6 cloud run instances, 3 of them had the following annotation, and all of these deployed properly, despite the exact same min and max scale. But any without a VPC connection threw errors. Not sure what the correlation could be.

```hcl
metadata {
	  annotations = {
		"autoscaling.knative.dev/minScale"        = "0"
		"autoscaling.knative.dev/maxScale"        = "5"
		"run.googleapis.com/vpc-access-connector" = var.vpc_connector_name
		"run.googleapis.com/vpc-access-egress"    = "all"
	  }

	  labels = {
		ecosystem: var.stage
	  }
	}
```

**Comment by edwardmedia** [comment]
@Metroxe @jw-websensa the provider does not have much control over the contents of annotations. Over time, the API makes some adjustments. Does `lifecycle` help mitigate the issue?

**Comment by jw-websensa** [comment]
@edwardmedia I am not sure how am I supposed to do that, could you explain?

**Comment by cdemire1** [comment]
I ran into the same error and moved the metadata block out of the template as explained in https://github.com/hashicorp/terraform-provider-google/issues/10958#issuecomment-1019698109

@edwardmedia Is it possible to update the related documentation with a new example?

**Comment by jw-websensa** [comment]
@cdemire1 thank you very much, problem solved! 
It is still strange to me that my first approach worked in the past, but hey, why google should inform about changes? :)
I would also like some more detailed examples so that similar mistakes don't happen in future

**Comment by edwardmedia** [comment]
@cdemire1 here is the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#annotations) that explains what to do. There have been some discussions like https://github.com/hashicorp/terraform-provider-google/issues/8380 Closing this issue now.

**Comment by jw-websensa** [comment]
@edwardmedia in my opinion these docs are not very informative about annotations, they only redirect to kubernetes docs, still it is hard to tell what particular annotations are possible
