### ISSUE TITLE
Failing test(s): TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#12695]
100% failure since 2022-09-28

Message:

```
Error: Reference to undeclared resource
on terraform_plugin_test.tf line 10, in resource "google_project_service" "apigee":
10:   project = google_project.project.project_id
A managed resource "google_project" "project" has not been declared in the
root module.
```

line in question: https://github.com/GoogleCloudPlatform/magic-modules/pull/6587/files#diff-2d4382e9db63078ff2a8ac1357597a38a440c6cb51129232fa71f44e2e052df8R9

needs to be updated to `google_project.default.project_id`, but it may need further verification as it has never passed

**Comment by AarshDhokai** [comment]
- TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/-8339103161169566908?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure
[Google Cloud](https://ci-oss.hashicorp.engineering/test/-8339103161169566908?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure

**Comment by AarshDhokai** [comment]
b/261705010
