### ISSUE TITLE
Cloud Build Trigger with `script` field

### ISSUE THREAD

**Issue by dvanrhenen** [hashicorp/terraform-provider-google#12702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

To previously run bash scripts inside a Cloud Build pipeline, using a `bash` image in combination with the `args` attribute was enough. But, this is now the legacy way to run bash scripts inside Cloud Build ([see Google Documentation](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#running_inline_bash_scripts_legacy)). It is not possible to use the `script` field to specify the bash commands.

This is supported when using a `cloudbuild.yaml` file but is not yet supported through the Terraform module. It would be nice if it was possible to also specify the `script` field inside the `build.step` attribute.

### New or Affected Resource(s)

* `google_cloudbuild_trigger`

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "build-trigger" {
  location = "global"

  trigger_template {
    branch_name = "main"
    repo_name   = "my-repo"
  }

  build {
    step {
      name   = "ubuntu"
      script = "echo hello" # using `script` field
    }

    step {
      name   = "python"
      script = "#!/usr/bin/env python\nprint('hello from python')\n" # using `script` field
    }

    source {
      storage_source {
        bucket = "mybucket"
        object = "source_code.tar.gz"
      }
    }

    tags          = ["build", "newFeature"]
    substitutions = {
      _FOO = "bar"
      _BAZ = "qux"
    }
  }
}
```

### References

* [Running inline bash scripts (legacy) | Running bash scripts](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#running_inline_bash_scripts_legacy)
* [Using the script field | Running bash scripts](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#using_the_script_field)

b/270751318

**Comment by melinath** [comment]
It looks like this is supported by the API: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build.BuildStep

**Comment by melinath** [comment]
b/253296389

**Comment by melinath** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/6701
