### ISSUE TITLE
Plan crashing for resource google_storage_transfer_job

### ISSUE THREAD

**Issue by marcusricardoaguiar** [hashicorp/terraform-provider-google#12703]
Whenever I plan a code with the resource `google_storage_transfer_job`, it's crashing as shown on **Debug output**, no matter which terraform version and/or gcp provider I've been using.

### Terraform Version

Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.35.0
+ provider registry.terraform.io/hashicorp/google-beta v4.35.0

### Affected Resource(s)

The affected resource is `google_storage_transfer_job`.

### Debug Output

Stack trace from the terraform-provider-google_v4.35.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x246a4bc]

goroutine 71 [running]:
github.com/hashicorp/terraform-provider-google/google.flattenTransferSchedule(0x0)
        github.com/hashicorp/terraform-provider-google/google/resource_storage_transfer_job.go:794 +0x5c
github.com/hashicorp/terraform-provider-google/google.resourceStorageTransferJobRead(0x7fd5381fb6d8?, {0x2bfe740?, 0xc000a11000})
        github.com/hashicorp/terraform-provider-google/google/resource_storage_transfer_job.go:568 +0x5f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x313e270?, {0x313e270?, 0xc000da41e0?}, 0xd?, {0x2bfe740?, 0xc000a11000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009a8e00, {0x313e270, 0xc000da41e0}, 0xc000a136c0, {0x2bfe740, 0xc000a11000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d9e0, {0x313e270?, 0xc000da4120?}, 0xc000a64d80)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003fa280, {0x313e270?, 0xc000d939e0?}, 0xc0010fe600)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x41e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x2b931a0?, 0xc0003fa280}, {0x313e270, 0xc000d939e0}, 0xc00045a380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x31434b8, 0xc0009fe000}, 0xc000d9bd40, 0xc0009b26f0, 0x424a1f0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x31434b8, 0xc0009fe000}, 0xc000d9bd40, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-google_v4.35.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

We should be apply to plan the code when running `terraform plan`.

### Actual Behavior

With this resource defined, it's crashing as shown on the **Debug output** session.

### Steps to Reproduce

1. We just need to define a resource `google_storage_transfer_job`.
2. `terraform plan`

### Important Factoids

I've also tested it with different terraform versions as well as gcp provider versions.

**Comment by giovanni-girelli-sdg** [comment]
same error on this resource.
