### ISSUE TITLE
Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 

### ISSUE THREAD

**Issue by RxGoodness** [hashicorp/terraform-provider-google#12701]
Hi there,

Please I'm having this error and I've not been able to find a breakthrough after trying all solutions i got.
I am having this error : 
  details: "Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/nftiket500/locations/us-east1/keyRings/nftiket500/cryptoKeys/nftiket5000/cryptoKeyVersions/1' (or it may not exist)

**Comment by edwardmedia** [comment]
@RxGoodness how did you get to this point? Are you manage resources via Terraform? Can you share the full debug log?

Also you may want to take a look at 

[google_kms_key_ring_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_key_ring_iam#google_kms_key_ring_iam_member)

[google_kms_crypto_key_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_crypto_key_iam)

**Comment by edwardmedia** [comment]
@RxGoodness closing this assuming this is no longer a question.
