### ISSUE TITLE
Fix TestAccClouddeployTarget_Target

### ISSUE THREAD

**Issue by alphanota** [hashicorp/terraform-provider-google#12714]
### Affected Resource(s)

* google_clouddeploy_target

The error is because of a misconfigured field in the Target resource. The field `execution_timeout` has a non-empty default value that is set by server, if not specified by the user.
However, terraform thinks this string field is empty by default, leading to the test failure.

**Comment by edwardmedia** [comment]
@alphanota where did you run this? Mind share your full debug log?

**Comment by alphanota** [comment]
The dcl version was rolled back to v.1.19 from v1.21 because of the test failure (https://github.com/hashicorp/terraform-provider-google/commit/38a14f1ed8668391665b923bacfec828bcc33981) which is why its working now.

The DCL version with the fix is v.1.23. I created this issue to follow PR guidelines and track the bug.
The PR to upgrade the DCL version is here (https://github.com/GoogleCloudPlatform/magic-modules/pull/6639)

**Comment by edwardmedia** [comment]
@alphanota I have added the label **tpgtools** then

**Comment by roaks3** [comment]
It looks like the DCL upgrade was merged, and I'm see this test succeed in the full history of our nightly tests (90 days).

@alphanota can this issue be closed out?
