### ISSUE TITLE
google_compute_global_address - An argument named "labels" is not expected here.

### ISSUE THREAD

**Issue by DavidCorino** [hashicorp/terraform-provider-google#12716]
### Terraform Version

1.2.1

### Affected Resource(s)

google_compute_global_address

### Adding labels to resource

resource "google_compute_global_address" "teste" {
  name    = "teste"
  labels  = teste
}

### Error Output

│ Error: Unsupported argument
│
│   on main.tf line 3, in resource "google_compute_global_address" "teste":
│    3:   labels  = teste
│
│ An argument named "labels" is not expected here.

**Comment by edwardmedia** [comment]
@DavidCorino looks like `labels` is still [beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address#labels). Can you try  with **google-beta**?

**Comment by DavidCorino** [comment]
Yes, i was using BETA, but seems something in cache, after retry works.
