### ISSUE TITLE
Add support for linux_node_config cgroupMode

### ISSUE THREAD

**Issue by hanikesn** [hashicorp/terraform-provider-google#12712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Newer GKE release allow setting the cgroupMode for nodes,:
https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#cgroup-mode-options

### New or Affected Resource(s)

* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "secondary-pools" {
  node_config {
    linux_node_config {
      cgroup_mode = "CGROUP_MODE_UNSPECIFIED"
    }
  }
}
```

### References

b/288868203

**Comment by peter-mueller-viacom** [comment]
Please also add same to resource google_container_aws_node_pool TY.

**Comment by davicedraz** [comment]
Complementing @DanTulovsky's suggestion, you can perform this update via terraform using a `null_resource` by running a script that performs the `gcloud container node-pools update` on the desired node pools.

For example:
```tf
resource "null_resource" "update_cgroup" {
  triggers = {
    // whatever makes the most sense in your context
  }

  provisioner "local-exec" {
    command = "sh ../scripts/update-cgroup-mode.sh ${module.node_pool} ${module.cluster.name} ${var.metadata.region}"
  }

  depends_on = [module.node_pool] // your module of node pools, so it will only run after creating it
}
```

**Comment by melinath** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/8997
