### ISSUE TITLE
Add a terraform resource to set up a managed Tensorboard instance

### ISSUE THREAD

**Issue by tarrade** [hashicorp/terraform-provider-google#12711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today for the MLOps pipeline on GCP using Vertex AI managed pipeline, the creation of Managed Tensorboard instance need to be done manually. Could we have a terraform ressource for Managed TensorBoard instance [1](https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-overview) as it was done for google_vertex_ai_metadata_store [2](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_metadata_store)

GCP support told me it was the right place to made a feature request.

### Potential Terraform Configuration

```tf
configuration option should be the same as the gcloud command 
- name 
- region
- cmek
- labels
- description
```

### References
Managed TensorBoard instance [1](https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-overview)
[gcloud command](https://cloud.google.com/sdk/gcloud/reference/ai/tensorboards/create)

**Comment by melinath** [comment]
API reference: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.tensorboards

**Comment by melinath** [comment]
b/253294891

**Comment by tarrade** [comment]
Works perfectly, thanks for the quick implementation
