### ISSUE TITLE
google_secret_manager_secret_version import documentation incorrect

### ISSUE THREAD

**Issue by soudaburger** [hashicorp/terraform-provider-google#12713]
Terraform import instructions for the `google_secret_manager_secret_version` resource are incorrect.  At the bottom of https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version it shows `$terraform import google_secret_manager_secret_version.default {{name}}/{{name}}`.

Error message received:
```
panic: Version name doesn not fit the format `projects/{{project}}/secrets/{{secret}}/versions/{{version}}`
```

The correct import configuration should be `projects/{{project}}/secrets/{{secret}}/versions/{{version}}`

**Comment by edwardmedia** [comment]
@soudaburger can you share the full debug log?

**Comment by soudaburger** [comment]
This is just a documentation error, you shouldn't need a debug log?
