### ISSUE TITLE
GCP Logging Bucket IAM permissions

### ISSUE THREAD

**Issue by anarwal** [hashicorp/terraform-provider-google#12729]
Hi, 

I am trying to add IAM permissions for Cloud Logging Bucker created via `google_logging_project_bucket_config`. I don't see any specific `IAM policy for Cloud Logging Bucket` (only thing I found was for [storage bucket](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam#google_storage_bucket_iam_member).

I want to know should I be using :

1. `google_project_iam_member` -> which adds permission to bucket but at the project level and not resource level.

2. or somehow I can use `google_storage_bucket_iam_member` -> this gives a failure for now as it complains it doesn't recognize "storage bucket" which is true as I have logging bucket and not storage bucket.

**Comment by edwardmedia** [comment]
@anarwal Can you checkout below doc?

https://cloud.google.com/logging/docs/access-control

**Comment by edwardmedia** [comment]
@anarwal closing this assuming it is no longer an issue
