### ISSUE TITLE
Add support for disk type and size configuration on the GKE Node Auto provisioning

### ISSUE THREAD

**Issue by mrvarmazyar** [hashicorp/terraform-provider-google#12722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
We need to provide two options as node auto provisioning defaults on the GKE to specify the Disk type and size as these are available on the [Google API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#autoprovisioningnodepooldefaults), in this way we will have more flexibility to change the default values in case they're required. 

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
cluster_autoscaling {
    enabled             = true
    autoscaling_profile = "OPTIMIZE_UTILIZATION"

    auto_provisioning_defaults {
        disk_type = "pd-ssd"
        disk_size  = 200
    }
}
```

### References

* #0000

**Comment by sanghaniJ** [comment]
b/263757556

**Comment by sanghaniJ** [comment]
I've gone through this issue and it seems like the support for `diskType` and `diskSize` has been added in this [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/6649). Hence, closing this issue ticket.
