### ISSUE TITLE
google_sql_database_instance should verify backup location value

### ISSUE THREAD

**Issue by cen1** [hashicorp/terraform-provider-google#12720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Any

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "mysql" { 
  settings {
    backup_configuration {
      location      = "europe-west4-b"
    }
  }
}
```

### Debug Output

```
Error: Error waiting for Create Instance: 


  on ../../../../modules/sql/mysql/database.tf line 1, in resource "google_sql_database_instance" "mysql":
   1: resource "google_sql_database_instance" "mysql" { 
```

### Expected Behavior

The backup location expects a **region**. If you do not specify a correct region (e.g. you type in a zone by accident) terraform does not complain about it. The apply starts, creates the instance but instance goes into a bad state ("Unknown error" event in SQL instance). Due to the error event, terraform fails while polling for the instance status. The failure error is pasted above in the debug output. This is very bad because instance eventually becomes healthy but is not saved in the state.

I am not sure if terraform provider should check for validity of the field or that is the google api's job so we also raised an issue with google support.

### Actual Behavior

Either the plan should fail or google API should return 400 and fail fast (before instance is created).

### Steps to Reproduce

Provision an instance with invalid region for backup location.

**Comment by edwardmedia** [comment]
@cen1 here is the API [doc](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#backupconfiguration). The provider is based on it. I don't think the provider could add a validation on a field if the API does not explicitly specify the business logic. Does this make sense?

**Comment by cen1** [comment]
Makes sense. Should be check in the API then. Will raise the issue to support.
