### ISSUE TITLE
`google_sql_user` got error `Root resource was present, but now absent` on apply

### ISSUE THREAD

**Issue by maoueh** [hashicorp/terraform-provider-google#12731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.3.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.38.0
+ provider registry.terraform.io/hashicorp/google-beta v4.38.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
```

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
# Heavily trimmed down to what is important

resource "google_sql_database_instance" "graph-dev" {
  project          = terraform.workspace
  name             = "graph-dev"
  database_version = "POSTGRES_14"
  region           = "us-central1"

  settings {
    activation_policy = "ALWAYS"
    availability_type = "ZONAL"
    disk_autoresize   = true
    disk_type         = "PD_SSD"
    pricing_plan      = "PER_USE"
    tier              = "db-custom-8-32000"

    database_flags {
      name  = "maintenance_work_mem"
      value = "102400000"
    }

    database_flags {
      name  = "max_wal_size"
      value = "10240"
    }

    maintenance_window {
      hour = 0
    }

    backup_configuration {
      binary_log_enabled = false
      enabled            = false
    }

    ip_configuration {
      ipv4_enabled    = false
      private_network = "projects/<project>/global/networks/vpc-global"
      require_ssl     = false
    }

    location_preference {
      zone = "us-central1-a"
    }
  }
}

resource "google_sql_database" "database" {
  name     = "graph"
  instance = google_sql_database_instance.graph-dev.name
}

resource "google_sql_user" "graph_dev_dev" {
  name     = "dev"
  instance = google_sql_database_instance.graph-dev.name
  host     = "%"
  password = "<pwd>"
}

resource "google_sql_user" "graph_dev_graph" {
  name     = "graph"
  instance = google_sql_database_instance.graph-dev.name
  host     = "%"
  password = "<pwd>"
}
```

### Debug Output

https://gist.github.com/maoueh/0c5e8bde379d88093dc63f3888e0bf67
### Expected Behavior

No error should have been displayed

### Actual Behavior

The users are actually created and works properly but `terraform apply` does error out with:

```
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.graph_dev_graph, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.graph_dev_dev, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using impersonation using service acount.

**Comment by edwardmedia** [comment]
@maoueh I used your code to test and couldn't repro the issue. Did you put an ip for the `host`?

**Comment by maoueh** [comment]
@edwardmedia The config show is the one I use, let me test some of those.

**Comment by maoueh** [comment]
@maoueh You are right, removing the `host` fixed the problem. Should this be turned into a feature request to better handle this case or there is not much that can be done on that matter?

**Comment by edwardmedia** [comment]
@maoueh this behavior is controlled by the API. I don't believe there is much we can do at the provider level at this moment. Glad you have figured this out. Closing the issue then. Feel free to reopen if you have more questions on this matter
