### ISSUE TITLE
Can we add tags within root_volume of google_container_aws_node_pool

### ISSUE THREAD

**Issue by Aracki** [hashicorp/terraform-provider-google#12746]
Would be nice to have option to add tags for `root_volume` within [google_container_aws_node_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_aws_node_pool#root_volume).

**Comment by c2thorn** [comment]
Hi @Aracki,
This does not seem possible via the API at this time: https://cloud.google.com/anthos/clusters/docs/multi-cloud/reference/rest/v1/AwsVolumeTemplate
If there is alternative way to do this, please let me know.
