### ISSUE TITLE
`google_bigquery_dataset`: add support for `storage_billing_model`

### ISSUE THREAD

**Issue by jonathan-ostrander** [hashicorp/terraform-provider-google#12758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google recently released a pre-GA feature that lets users choose between billing a dataset by logical bytes or physical bytes (previously all BigQuery datasets were billed by logical bytes). The `google_bigquery_dataset` resource should be updated to include a field for setting the billing model.

[One caveat with this property is that it cannot be changed to `logical` once it has already be set to `physical` so in-place updates can only go one direction.](https://cloud.google.com/bigquery/docs/updating-datasets#update_storage_billing_models)

### New or Affected Resource(s)

* `google_bigquery_dataset`

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset" "dataset" {
  # default to "LOGICAL"
  # storage_billing_model = "LOGICAL"
  storage_billing_model = "PHYSICAL"
}
```

b/277411427

**Comment by rileykarson** [comment]
Note: This is limited by an allowlist. https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team contains details on contacting our team through Google-internal channels, for folks where that may be relevant.

**Comment by LucaPrete** [comment]
I'm going to send a draft PR for this but we need the feature to be GA before merging it.

**Comment by brodin** [comment]
> I'm going to send a draft PR for this but we need the feature to be GA before merging it.

Does 'google-beta' provider mainly cover beta in the provider, or does it include beta (as in preview vs GA) for GCP Products?

**Comment by rileykarson** [comment]
GCP beta launch stage and public preview features. We consider it as stable as the GA provider in terms of the provider implementation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_versions

**Comment by brodin** [comment]
> I'm going to send a draft PR for this but we need the feature to be GA before merging it.

Looks to like it might arrive the 5th of July with the other major changes to BQ 🙏

**Comment by philip-harvey** [comment]
It looks like this is in public preview now so no allow list is needed, so does this mean it can be added to the beta provider now?

**Comment by LucaPrete** [comment]
@philip-harvey I gave it a try and I still get during tests: `Error: Error creating Dataset: googleapi: Error 400: Storage billing model configuration is not available for the project.`. This makes me doubt it went in public preview...

**Comment by philip-harvey** [comment]
> @philip-harvey I gave it a try and I still get during tests: `Error: Error creating Dataset: googleapi: Error 400: Storage billing model configuration is not available for the project.`. This makes me doubt it went in public preview...

Ah, it looks like it still requires support to activate a project for this billing model, so still in private preview, hence I assume not time to add support to the provider yet

**Comment by LucaPrete** [comment]
Good news folks! This is now GA and I was able to successfully use the provider in my local tests. I rebased the patch and submitted it again. Hopefully, tests should pass also online and the patch should be reviewed soon. Stay tuned for more updates ;)
