### ISSUE TITLE
Add support for Cloud Workstations

### ISSUE THREAD

**Issue by rmb938** [hashicorp/terraform-provider-google#12763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for Cloud Workstations https://cloud.google.com/workstations

I didn't see anything in the docs about support for Cloud Workstations nor any issues mentioning it.

### New or Affected Resource(s)

- [x] `google_cloud_workstation_cluster`
- [x] `google_cloud_workstation_configuration`
- [ ] `google_cloud_workstation_workstation`

Also accompanying IAM resources 

### Potential Terraform Configuration

```tf
resource "google_cloud_workstation_cluster" "my-cluster" {}

resource "google_cloud_workstation_configuration" "my-configuration" {
  cluster_id = google_cloud_workstation_cluster.my-cluster.id

  instance_type = "e2-standard-2"

  boot_disk_size_gb = 200
  boot_disk_type = "balanced"

  vpc_subnet = my-network.my-subnet.id

  # other advanced config here, like persistent directories, ect..
}

resource "google_cloud_workstation_workstation" "my-workstation" {
  configuration_id = google_cloud_workstation_configuration.my-configuration.id
}
```

**Comment by bschaatsbergen** [comment]
I'll take a look at implementing this 👍

**Comment by bschaatsbergen** [comment]
@ScottSuarez note to fully implement Cloud Workstations we still need

- https://github.com/GoogleCloudPlatform/magic-modules/pull/7017
- https://github.com/GoogleCloudPlatform/magic-modules/pull/7018

Jumping on these right now.

**Comment by rileykarson** [comment]
Sorry for the noise! Got to this a little too fast for the robot- it should be done now 🤞

**Comment by bschaatsbergen** [comment]
Thanks @rileykarson 👍🏼

**Comment by rileykarson** [comment]
Sorry for the noise! GitHub is a little overeager about closing issues. If anyone with edit permissions on a repo introduces a commit with the "Closes: {{issue}}" text in the commit message in *any* repo, including a fork- and including through a merge- it goes ahead and closes the issue. I'm not aware of a way to stop it.

**Comment by rmb938** [comment]
Haha no problem, keeps getting my hopes up that it's implemented :p

**Comment by bschaatsbergen** [comment]
> Haha no problem, keeps getting my hopes up that it's implemented :p 

Soon!

**Comment by rileykarson** [comment]
We likely missed the `4.56.0` cutoff, so this is likely to go out piecemeal. The final resource go out on `4.57.0`, set for the 13th.
