### ISSUE TITLE
Add a terraform resource support for Network Firewall Policies

### ISSUE THREAD

**Issue by gskconfo** [hashicorp/terraform-provider-google#12765]
### Affected Resource(s)

* google_compute_firewall_policy

Include support for creating [Google Network Firewall Policies resources](https://cloud.google.com/vpc/docs/network-firewall-policies) via the provider. 

cloud shell command :
gcloud compute network-firewall-policies

**Comment by rileykarson** [comment]
Picked up by @ghabian in https://github.com/GoogleCloudPlatform/magic-modules/pull/6693

**Comment by ghabian** [comment]
note on mentioned PR, it will only add support for policies. I'll create PRs later for rules and associations to break it up for reviewers.

**Comment by LucaPrete** [comment]
Hello @ghabian 

Are you already working on this? I'm planning to commit the resource as well but I don't want to step on your feet :)
Please, let me know if I can help, or if I can take over the task.

**Comment by ghabian** [comment]
Hi Luca, it's already committed just waiting on the team to release the changes. (looking at the changelog it might make it into v4.40 tomorrow)

**Comment by melinath** [comment]
google_compute_network_firewall* resources were added in [4.44](https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.44.0)
