### ISSUE TITLE
Unable to create google_dataproc_workflow_template without job

### ISSUE THREAD

**Issue by deepjy** [hashicorp/terraform-provider-google#12783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.1.6

### Affected Resource(s)
* google_dataproc_workflow_template

### Terraform Configuration Files

```tf
resource "google_dataproc_workflow_template" "template" {
  name = "test-tfe-example1"
  location = "us-central1"
  project  = "test-project"
  placement {
    managed_cluster {
      cluster_name = "test-bucket"
      config {
          staging_bucket = "test-bucket-staging"
          temp_bucket    = "test-bucket-temp"
        gce_cluster_config {
          internal_ip_only       = true
          zone = "us-central1-a"
          tags = ["foo", "bar"]
        }
        endpoint_config {
      enable_http_port_access = "false"
    }
      }
    }
  } 
}
```

### Debug Output

```
Error: Insufficient jobs blocks
on dataproc-workflow.tf line 2, in resource "google_dataproc_workflow_template" "template":
resource "google_dataproc_workflow_template" "template" {
At least 1 "jobs" blocks are required.
```

### Expected Behavior

In GCP, the dataproc workflow templates can be created without attaching the jobs. Later the jobs can be attached and template can be instantiated.
Gcloud cli command to create a workflow template without job:

```
gcloud dataproc workflow-templates create test-workflow-template --region us-central1
```

But in terraform [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template), the dataproc-workflow-template requires a mandatory job block. Whereas the workflow templates can be created without jobs using cli and jobs can be attached later to the templates

```
 jobs {
    step_id = "someJob"
    spark_job {
      main_class = "SomeClass"
    }
  }
```
The following arguments are supported:
[jobs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template#jobs) - (Required) Required. The Directed Acyclic Graph of Jobs to submit.

### Actual Behavior

Attaching a job is mandatory in Terraform while creating dataproc_workflow_template resource.

```
Error: Insufficient jobs blocks
on dataproc-workflow.tf line 2, in resource "google_dataproc_workflow_template" "template":
resource "google_dataproc_workflow_template" "template" {
At least 1 "jobs" blocks are required.
```

### Steps to Reproduce

Create the terraform file to create dataproc workflow template resource as described above
Run following commands
```
terraform plan 
terraform validate
```
 

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template#jobs

* #0000

**Comment by edwardmedia** [comment]
@deepjy it appears the API has updated its behavior. This was by design and not a bug. Could you file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) instead?

**Comment by deepjy** [comment]
Submitted enhancement request - https://github.com/hashicorp/terraform-provider-google/issues/12843
