### ISSUE TITLE
Dataset : updating a label throws an error after timeout

### ISSUE THREAD

**Issue by davidroman** [hashicorp/terraform-provider-google#12799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
# terraform -v
# Terraform v1.3.2
# on darwin_amd64
# + provider registry.terraform.io/hashicorp/google v4.36.0

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change is below


resource "google_vertex_ai_dataset" "dataset" {
  display_name          = "test_terraform_3"
  metadata_schema_uri   = "gs://google-cloud-aiplatform/schema/dataset/metadata/tabular_1.0.0.yaml"
  region                = "us-central1"
  project = "project-sd-1"
  labels = {
    foo = "baz",
    test = "labela"
  }
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.20"
    }
  }
}


# * the version of the config after the change is below, the only update is to the label, test 


resource "google_vertex_ai_dataset" "dataset" {
  display_name          = "test_terraform_3"
  metadata_schema_uri   = "gs://google-cloud-aiplatform/schema/dataset/metadata/tabular_1.0.0.yaml"
  region                = "us-central1"
  project = "project-sd-1"
  labels = {
    foo = "baz",
    test = "labelc"
  }
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.20"
    }
  }
}


```

### Steps to Reproduce

1. Edit a label on an existing google_vertex_ai_dataset
2. run `terraform apply`

### References

* #0000

**Comment by slevenick** [comment]
Fixed via https://github.com/GoogleCloudPlatform/magic-modules/pull/6661
