### ISSUE TITLE
Create a dataset using pubsub subscription

### ISSUE THREAD

**Issue by raihan1khan** [hashicorp/terraform-provider-google#12800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

we can write message to the Big query table, but what If I want to take the message and create a dataset

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by edwardmedia** [comment]
@raihan1khan what exactly you want to achieve? Can you share your config that you have already had?

**Comment by edwardmedia** [comment]
@raihan1khan closing this now assuming it is no longer an issue
