### ISSUE TITLE
[New major version] Make `DELETE` the default destroy behavior for google_firebase_web_app

### ISSUE THREAD

**Issue by rainshen49** [hashicorp/terraform-provider-google#12810]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

After https://github.com/GoogleCloudPlatform/magic-modules/pull/6652, backward compatibility requires `terraform destroy` to skip deleting the Firebase Web App by default, unless `deletion_policy="DELETE"` is specified. The new and more intuitive default behavior would be `deletion_policy="DELETE"`, which actually deletes the resource. 

### New or Affected Resource(s)

* google_firebase_web_app

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/6652

b/277381663

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8458

This will release with v5.0.0. Check https://github.com/hashicorp/terraform-provider-google/issues/15582 for more details on the major release.

Closing this issue for tracking purposes.
