### ISSUE TITLE
Apigee Org PayG support "google_apigee_organization"

### ISSUE THREAD

**Issue by nagspace** [hashicorp/terraform-provider-google#12816]
### Affected Resource(s)

* google_apigee_organization

google_apigee_organization only supports CLOUD & HYBRID.

Will there be support for PAYG the new offering that is called pay-as-you-go for Apigee?

**Comment by brysk** [comment]
Hi, I was able to provision PAYG Apigee organisation without any problems. Just configure [billing_type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_organization#billing_type) as PAYG and it will work fine

**Comment by nagspace** [comment]
Yes, initially when I posted this question there wasn't any support for the PayG from apigee module.

Thanks for sharing the update.

**Comment by melinath** [comment]
b/270216653

**Comment by melinath** [comment]
Closing as it sounds like this is resolved.
