### ISSUE TITLE
Revise terraform reviewer list to be a github group for singular source of truth

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#12813]
# Background

A contributor who is within the reviewer list cannot assign to a random reviewer. Only unassigned prs will go through this process. While one can assign issues to the [terraform-team](https://github.com/orgs/GoogleCloudPlatform/teams/terraform-team/members) group. This group is not complete with all reviewers and includes individuals who are not reviewers.

https://github.com/GoogleCloudPlatform/magic-modules/blob/ca50dc4fedb2efb3a80f3cae6dac926aebd1a0d0/.ci/containers/contributor-checker/check-contributor.sh#L19-L22

# Recommendation 
Create a github group for reviewers and have this be the source of truth or quantify that information somewhere. Allow assignment through either assignees or labels.

# What kind of contribution is this issue about?
* CI Processes

**Comment by rileykarson** [comment]
Groups are properties of organizations, rather than a repository or a floating list. They're also typically private to the organization. Given the mix of Googler and HashiCorp engineers in the reviewers' pool, this is infeasible.
