### ISSUE TITLE
Remove instances of schema.ConfigModeAttr

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#12824]
`ConfigMode: schema.ConfigModeAttr` is a setting that enables Attributes as blocks mode (https://www.terraform.io/language/attr-as-blocks) in Terraform, which corrected a breakage in Terraform Core between 0.11 and 0.12. It allows empty blocks to be specified, which is important to allow unsetting certain fields. However, it can result in negative behaviour for modules and advanced configurations, so we should try and remove occurrences of the setting.

This likely means attempting to correct O+C fields or similar. We've never scoped what removing this looks like.

**Comment by c2thorn** [comment]
Noting that schema.ConfigModeAttr affected https://github.com/hashicorp/terraform-provider-google/issues/18115

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11506
