### ISSUE TITLE
spanner iam example does not work

### ISSUE THREAD

**Issue by dogmatic69** [hashicorp/terraform-provider-google#12820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

n/a

### Affected Resource(s)

* google_spanner_instance_iam_member
* google_spanner_database_iam_member

### Terraform Configuration Files

```tf
resource "google_spanner_instance_iam_member" "instance" {
  instance = google_spanner_instance.xxx.name
  role     = "roles/compute.networkUser"
  member   = "serviceAccount:xxx@yyy.iam.gserviceaccount.com"
}
resource "google_spanner_database_iam_member" "database" {
  instance = google_spanner_instance.xxx.name
  database = google_spanner_database.yyy.name
  role     = "roles/compute.networkUser"
  member   = "serviceAccount:xxx@yyy.iam.gserviceaccount.com"
}
```

### Debug Output

```
Error setting IAM policy for Spanner Database: xxx/tfgen-spanid-xxx/xxx: googleapi: Error 400: Role roles/compute.networkUser is not supported for this resource., badRequest
```
### Expected Behavior

able to copy/paste an example and it works

### Actual Behavior

Error due to not valid role for spanner

### Steps to Reproduce

1. `terraform apply --auto-approve`

### References

* #0000

**Comment by edwardmedia** [comment]
@dogmatic69 below error is from API, there is not much we can do at the provider level. Just out of curiosity, why do you think this role should be supported?

```
googleapi: Error 400: Role roles/compute.networkUser is not supported for this resource.
```

**Comment by dogmatic69** [comment]
Let me clarify, the docs are wrong. It should not have a broken examole.

**Comment by edwardmedia** [comment]
@dogmatic69 oh sorry I misunderstood. Yes, let me update the doc then. Thanks
