### ISSUE TITLE
How to set http/2 end-to-end for cloud run service

### ISSUE THREAD

**Issue by AkselAllas** [hashicorp/terraform-provider-google#12832]
I can't seem to find the following option for [cloud_run_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service)

<img width="714" alt="image" src="https://user-images.githubusercontent.com/26136082/196676840-352627f6-33e5-4247-82a8-8642f489a7cf.png">

Same docs [as here](https://cloud.google.com/run/docs/configuring/http2#terraform) should be added to Terraform Registry

**Comment by sorenhansendk** [comment]
@AkselAllas 

You can enable HTTP/2 end-to-end on your port configuration.

<pre>
# Enable HTTP/2
# https://cloud.google.com/run/docs/configuring/http2
ports {
  name           = "h2c"
  container_port = 8080
}
</pre>

Reference: https://cloud.google.com/run/docs/configuring/http2#terraform
