### ISSUE TITLE
Failing test(s): iam_binding/iam_member

### ISSUE THREAD

**Issue by yugandhar-btc** [hashicorp/terraform-provider-google#12831]
### Affected Resource(s)

* google_storage_bucket_iam_member

As i have declared right way in terraform files and after terraforming validate passed terraform plan is failed with following error. 

Terraform v0.12.29

Error: Invalid for_each argument

  on .terraform/modules/rc_oct_mystudies_consent_documents/modules/simple_bucket/main.tf line 64, in resource "google_storage_bucket_iam_member" "members":
  64:   for_each = {
  65:     for m in var.iam_members : "${m.role} ${m.member}" => m
  66:   }

**Comment by melinath** [comment]
Closing as this does not have enough information to reproduce. Please open a new bug ticket and fill out the standard bug template if you are seeing this issue.
