### ISSUE TITLE
Terraform apply fails with panic that says to notify the developers because it's always indicative of a bug

### ISSUE THREAD

**Issue by chase-replicated** [hashicorp/terraform-provider-google#12839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Github Actions runs-on: ubuntu-22.04 which uses Terraform 1.3.1 https://github.com/actions/runner-images/blob/ubuntu22/20221002.2/images/linux/Ubuntu2204-Readme.md

### Affected Resource(s)

google_pubsub_topic google_storage_bucket

### Terraform Configuration Files

N/A

### Debug Output

Can't provide debug output because I'm using a reusable github actions workflow, and if I modified that, all our jobs that use these workflows across the org would spit out debug logs.
"""Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow. """ (https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows)

https://gist.github.com/chase-replicated/0b51970c6c7f20852c54d607de2510b0

### Panic Output

https://gist.github.com/chase-replicated/99d4c1aef9e7a7c2dbe107486c20ef7b

### Expected Behavior

terraform apply succeeds or tells me resources already exist

### Actual Behavior

Crashes

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running via Github Actions using reusable workflows https://github.com/replicatedcom/reusable-workflows

**Comment by edwardmedia** [comment]
@chase-replicated can you share the configs for both `google_pubsub_topic` and  `google_storage_bucket`?

**Comment by chase-replicated** [comment]
@edwardmedia You mean this?

```
https://github.com/replicatedhq/gcp-event-handler-terraform-module/blob/main/main.tf
```

**Comment by chase-replicated** [comment]
@edwardmedia like this?
```
# Resource to force archiving of file during apply step
resource "null_resource" "trigger" {
  triggers = {
    timestamp = timestamp()
  }
}

data "archive_file" "handler_function_zip" {
  type        = "zip"
  source_dir  = "../../../scripts/"
  output_path = "${path.root}/handler_function.zip"

  depends_on = [resource.null_resource.trigger]
}

resource "google_pubsub_schema" "event_schema" {
  name       = "event_schema_cloud-custodian"
  type       = "AVRO"
  definition = jsonencode({
    "type" : "record",
    "name" : "Avro",
    "fields" : [ 
      {   
        "name" : "kind",
        "type" : "string"
      },  
      {   
        "name" : "id",
        "type" : "string"
      },  
      {   
        "name" : "name",
        "type" : "string"
      },  
    ]   
  }) 
}

resource "google_pubsub_topic" "event_topic" {
  name         = "event_topic_cloud-custodian"

  schema_settings {
    schema   = google_pubsub_schema.event_schema.id
    encoding = "JSON"
  }

  labels = {
    owner      = "sre"
    managed-by = "terraform"
  }

  depends_on = [google_pubsub_schema.event_schema]
}

resource "google_pubsub_subscription" "event_subscription" {
  name  = "event_subscription_cloud-custodian"
  topic = google_pubsub_topic.event_topic.name

  depends_on = [google_pubsub_topic.event_topic]

  push_config {
    push_endpoint = google_cloudfunctions_function.handler_function.https_trigger_url
  }
}

resource "google_storage_bucket" "handler_storage_bucket" {
  name                        = "handler_storage_bucket-cloud-custodian"
  location                    = "US"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  labels = {
    owner      = "sre"
    managed-by = "terraform"
  }
}

resource "google_storage_bucket_object" "handler_object" {
  name         = "handler_storage_bucket_object-cloud-custodian"
  bucket       = google_storage_bucket.handler_storage_bucket.name
  source       = data.archive_file.handler_function_zip.output_path
  content_type = "application/zip"
  depends_on   = [google_storage_bucket.handler_storage_bucket]
}

resource "google_cloudfunctions_function" "handler_function" {
  name                  = "handler_function-cloud-custodian"
  runtime               = "python37"
  entry_point           = "print_decoded"
  trigger_http          = true
  source_archive_bucket = google_storage_bucket.handler_storage_bucket.name
  source_archive_object = google_storage_bucket_object.handler_object.name

  labels = {
    owner      = "sre"
    managed-by = "terraform"
  }
}
```

**Comment by edwardmedia** [comment]
@chase-replicated what does below file look like?

```
handler_function.zip
```

**Comment by chase-replicated** [comment]
import base64
import zlib
import requests
import json

webhooks = {
        "XXXXXX": "----REDACTED_SLACK_HOOK----",
        "XXXXXX": "----REDACTED_SLACK_HOOK----"
        }

def print_decoded(event, context):
    decoded_compressed = base64.b64decode(event["data"])
    decompressed = zlib.decompress(decoded_compressed)
    loaded = json.loads(decompressed)
    project_id = loaded["account_id"]
    print(loaded)

    for n in loaded["resources"]:
        try:
            print(n["labels"])
            print(n)
            slack_channel = n["labels"]["owner-slack"]
            url = webhooks[slack_channel]
        except KeyError:
            pass
        try:
            print(n["resourceLabels"])
            print(n)
            slack_channel = n["resourceLabels"]["owner-slack"]
            url = webhooks[slack_channel]
        except KeyError:
            url = "----REDACTED_DEFAULT_SLACK_HOOK----"
            pass
        if loaded["policy"]["name"] == "auditing-immortal-instances" or loaded["policy"]["name"] == "auditing-immortal-clusters":
            msg = "The resource `%s: %s` has an `expires-on` label set to `never`. Please ensure this is necessary! If it is, no action is necessary." % (n["name"], n["id"])
        else:
            labels = []
            try:
                labels.extend(n["labels"])
            except KeyError:
                pass
            try:
                labels.extend(n["resourceLabels"])
            except:
                pass
            msg = "*Action* `%s` *Triggered* in Projects `%s` on resource `%s` (ID `%s`)\nLabels: `%s`" % (loaded["policy"]["name"], project_id, n["name"], n["id"], labels)
        headers = { "Content-Type": "application/json" }
        print(n)
        response = requests.post(url, json={"text": msg}, headers=headers)

**Comment by edwardmedia** [comment]
@chase-replicated using your code, I can run the code without an issue. I also verified the function was successfully created.

**Comment by chase-replicated** [comment]
@edwardmedia Thanks, I assume then it might be an issue with GitHub Actions and how it's being run there? Is the error message wrong then when it says "This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers so that it can be fixed. The output above should help diagnose the issue."?

**Comment by edwardmedia** [comment]
@chase-replicated from the log you provided, it appears a bug in the provider. There are multiple changes in `google_storage_bucket` since v4.37.0. Are you able to repro the issue in the latest version?

**Comment by edwardmedia** [comment]
@chase-replicated are you able to repro this issue with the latest version of the provider?

**Comment by edwardmedia** [comment]
@chase-replicated  Closing this assuming it is no longer an issue. Feel free to reopen if this is not the case
