### ISSUE TITLE
google_compute_subnetwork migration to ipv6 forces replacement

### ISSUE THREAD

**Issue by ErikEngerd** [hashicorp/terraform-provider-google#12833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.2

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

Terraform file applied initially, which creates an IPV4 subnetwork: 

```tf
resource "google_compute_subnetwork" "subnet-lan" {
  provider          = google
  name              = "testsubnet"
  region            = "europe-west4"
  ip_cidr_range     = "10.50.0.0/16"
  network           = "network"
}
```

Terraform update to dual stack network, which forces
replacement. 
```tf
resource "google_compute_subnetwork" "subnet-lan" {
  provider          = google
  name              = "testsubnet"
  region            = "europe-west4"
  ip_cidr_range     = "10.50.0.0/16"
  network           = "network"
  stack_type        = "IPV4_IPV6"
  ipv6_access_type  = "EXTERNAL"
}
```
### Debug Output

See https://gist.github.com/ErikEngerd/c6a120509fd875b2fa5ee988ba5731d4

Note: redacted the project name and account name to avoid exposing details of our environment. 

### Panic Output

- 

### Expected Behavior

google_compute_subnetwork should have update the network. The google cloud console supports the upgrade of a subnet from IPV4 to dual stack without problems. 

### Actual Behavior

Terraform destroys the subnet and creates a new one. 
This does not work at all when there are resources on the subnet in which case the destroy fails. 

### Steps to Reproduce

1. terraform apply of the first file, which creates the IPV4 subnet
2. terraform apply of the second file, which modifies the network to dual stack (IPV4_IPV6). This then leads to deletion of the subnet followed by creating it again. 

### Important Factoids

- authenticating as service account used for other devops actions in the same environment. Does not seem to be a security issue AFAICT.

### References

-

**Comment by edwardmedia** [comment]
@ErikEngerd it looks like it is the addition of `ipv6_access_type` that causes replacement. 

```tf
  # google_compute_subnetwork.subnet-lan must be replaced
-/+ resource "google_compute_subnetwork" "subnet-lan" {

      + ipv6_access_type           = "EXTERNAL" # forces replacement
  
    }
```
Look at the [api](https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks), this field is immutable. That is why changing its value causes recreation. Does this make sense?

```
ipv6AccessType | enumThe access type of IPv6 address this subnet holds. It's immutable and can only be specified during creation or the first time the subnet is updated into IPV4_IPV6 dual stack.
```

**Comment by ErikEngerd** [comment]
If I read the documentation on the link you provided I see the following: 

_The access type of IPv6 address this subnet holds. It's immutable and can only be specified during creation **or the first time the subnet is updated** into IPV4_IPV6 dual stack._

There is indeed some confusion in the docs but it does say in fact that it is mutable only becomes immutable after the value is set to IPV4_IPV6. This would be a more correct description: "The field can be specified at construction or after construction when the field is updated to IPV4_IPV6. If the field is set to IPV4_IPV6, then the field can no longer be updated."

This is also consistent with the google docs which say:

_A single VPC network can contain any combination of these subnet types._

_When you create a subnet, you specify which stack type to use. You can also [update an existing IPv4 only subnet](https://cloud.google.com/vpc/docs/create-modify-vpc-networks#add-subnet-ipv6) to configure it as a dual stack subnet._

I agree that the API docs are really confusing but it does also work in the google cloud console to update a subnet to IPV4_IPV6 without recreating it.

**Comment by edwardmedia** [comment]
@ErikEngerd it is possible API has updated its behavior. By now, the provider is based on the API and it is by design and not a bug. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) to ask for a change. In the meantimes, you can try gcloud to see if update is supported on this field. You may include the debug log in the enhancement.  I am closing this issue now
