### ISSUE TITLE
Dataproc - Not all arguments available Eg : Reservation Affinity

### ISSUE THREAD

**Issue by krishna4ldw** [hashicorp/terraform-provider-google#12848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Why google don't keep up to date with terraform this is must for CICD

Refer to gcloud commands make sure all arguments are available through terraform
https://cloud.google.com/sdk/gcloud/reference/dataproc/clusters/create
Eg: release-channel
Add following arguments to dataproc resource  in terraform
-reservation
--reservation-affinity
--metric-sources
--metric-overrides
--metric-overrides-file
--node-group
Refer to this link
https://cloud.google.com/sdk/gcloud/reference/dataproc/clusters/create

### New or Affected Resource(s)

Dataproc

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster
https://cloud.google.com/sdk/gcloud/reference/dataproc/clusters/create
--->

* b/254925137

**Comment by krishna4ldw** [comment]
@rileykarson @melinath  any update on ETA ?

**Comment by krishna4ldw** [comment]
@rileykarson  , @melinath  Can you provide ETA when we can expect this feature . We definitely need metric arguments soon as dataproc product team informed one of the monitoring property is deprecated we need to port over to metric arguments please prioritize.

**Comment by melinath** [comment]
Fix was reverted.

**Comment by krishna4ldw** [comment]
Thanks for completing this @duqDarren , @c2thorn I dont see these features  added in release notes & documentation 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster
https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md
