### ISSUE TITLE
google_redis_instance rdb_snapshot_period shoud be optional

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#12854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_redis_instance

### Expected Behavior

It seems `google_redis_instance`'s `persistence_config.rdb_snapshot_period` field should be optional as per [API docs](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#persistenceconfig) instead of required.

Original discussion: https://github.com/GoogleCloudPlatform/magic-modules/pull/6528#issuecomment-1286180774

### Actual Behavior

Field is marked required.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6739
