### ISSUE TITLE
google_gke_hub_membership does not respect the depends_on argument

### ISSUE THREAD

**Issue by todd-dsm** [hashicorp/terraform-provider-google#12850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```shell
% tf version
Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.41.0
+ provider registry.terraform.io/hashicorp/google-beta v4.41.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

Should be the latest of everything.

### Affected Resource(s)

* `google_gke_hub_membership`

### Terraform Configuration Files

I'm coming back to GKE after a while away so I'm learning about the new stuff; as a result, I may be wrong about how to put this config together. That said, Regarding fleet inclusion via Terraform. I've lifted some code from [this project](https://gitlab.com/asm7/asm-terraform); works great but it must be done in stages; this is the second stage: `hub-mesh`.

This is the problematic bit: 

_NOTE: it fails with or without the `provider = google-beta` enabled._

```hcl
/*
  --------------------------------------------------------|-------------------------------------------------------------
                                                  FLEET MEMBERSHIP
  TFR: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership
  ----------------------------------------------------------------------------------------------------------------------
*/
resource "google_gke_hub_membership" "gke_membership" {
  membership_id = var.cluster_name
  endpoint {
    gke_cluster {
      resource_link = "//container.googleapis.com/${data.google_container_cluster.apps_cluster.id}"
    }
  }
  #provider = google-beta
  depends_on = [
    data.google_container_cluster.apps_cluster
  ]
}

...

/*
  --------------------------------------------------------|-------------------------------------------------------------
                                                      DISCOVERY
  ----------------------------------------------------------------------------------------------------------------------
*/
data "google_container_cluster" "apps_cluster" {
  name     = var.cluster_name
  location = var.location
}
```

### NOTE

> If I were to comment this file out, build everything else, then uncomment this file and run a subsequent apply, everything works as intended.

### Debug Output

https://gist.github.com/todd-dsm/8a6007757a40fb34eabf14bb8e7257b4

### Expected Behavior

I would expect this to behave as all other resources do, wait for the `depends_on` condition to become true before proc'ing this block. 

### Actual Behavior

```shell
% make plan
terraform fmt -recursive=true
terraform plan -no-color 2>&1 | \
	tee /tmp/tf-kubes-gke-gitops-plan.out
data.google_project.project: Reading...
...
module.asm.data.google_container_cluster.apps_cluster: Reading...
module.asm.data.google_container_cluster.apps_cluster: Read complete after 1s

Error: Invalid template interpolation value

  on mods/asm/hub_membership.tf line 11, in resource "google_gke_hub_membership" "gke_membership":
  11:       resource_link = "//container.googleapis.com/${data.google_container_cluster.apps_cluster.id}"
    ├────────────────
    │ data.google_container_cluster.apps_cluster.id is null

The expression result is null. Cannot include a null value in a string
template.
```

As it shows, the data block is trying to discover IF the cluster exists; at this stage (starting point) it does not. Then the `google_gke_hub_membership` fails to wait on the resource to exist; it just procs immediatly. 

I'm sure there's some subtle thing about this `depends_on` mechanism that I'm missing.

### Steps to Reproduce

1. snag the [code](https://github.com/todd-dsm/kubes-gke-gitops); I already know - I hate it too
2. Modify and source-in the environment variables: `source build.env stage`
3. uncomment the `mods/asm/hub_membership.tf` file
4. make init, make plan
5. Fail: the resource procs when it seems like it shouldn't

### Important Factoids

This is my attempt to catch up on what I have missed not being in GCP for a few years. I'm making every effort to follow the Google/HashiCorp docs as closely as possible. Everything should be by the book; please start from that perspective.

### References

* This is my [starting point](https://cloud.google.com/community/tutorials/terraform-asm-mcp).
* With the supporting [code](https://gitlab.com/asm7/asm-terraform).

Not sure if this helps but...

* This [issue](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1181) seems similar

I know this is all fairly late-breaking stuff so if it's just not there yet then that's answer 🤷 

TIA

**Comment by edwardmedia** [comment]
@todd-dsm instead of `depends_on`, can you try adding [sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) between two resources to see if it works?

**Comment by rileykarson** [comment]
There is a bug here, but it's a little different than the one you'd expect. Datasources represent a single GET call to the API, and aren't used for sequencing the real bug is that the datasource _should be_ returning an error, and is instead silently failing. Unfortunately, there's not really any way to wait for an out-of-band resource to exist w/ Terraform and it either exists (and the apply succeeds) or doesn't (and the apply failed).

For a bit more context, which I'll use to spin out an issue for the general case:

We reuse Read functions between resources and their corresponding datasources. That means on a `404` error we set the resource id to `""`. In a resource, that means that the resource doesn't exist. However in a datasource, it's meaningless. This manifests as Terraform believing it was successful in retrieving results for a datasource even though it's entirely null, as the underlying GET call failed. These differences are explained in the `Read` function [documentation](https://github.com/hashicorp/terraform-plugin-sdk/blob/b5b7dd0ab159303da4a64c94d64aeaea884c2a23/helper/schema/resource.go#L137-L167):

> 	// Managed resources can signal to Terraform that the managed resource
	// instance no longer exists and potentially should be recreated by calling
	// the SetId method with an empty string ("") parameter and without
	// returning an error.

> 	// Data resources that are designed to return state for a singular
	// infrastructure component should conventionally return an error if that
	// infrastructure does not exist and omit any calls to the
	// SetId method.

**Comment by rileykarson** [comment]
@edwardmedia: We're likely able to check the `id` after https://github.com/hashicorp/terraform-provider-google-beta/blob/f61f75a4b59e1d9fc1d43f243a54b188842e692f/google-beta/data_source_google_container_cluster.go#L40 with `GetId`, and throw an error if it's `""`.
