### ISSUE TITLE
`google_dns_managed_zone`: description cannot be empty string

### ISSUE THREAD

**Issue by smaftoul** [hashicorp/terraform-provider-google#12868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.41.0
```

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
resource "google_dns_managed_zone" "mynet" {
  project     = var.project
  name        = "mynet-lan"
  dns_name    = "mynet.lan."
  description = ""
}
```
### Expected Behavior

The `google_dns_managed_zone` gets created or, we have an error on the plan.

### Actual Behavior

```
google_dns_managed_zone.mynet: Creating...
╷
│ Error: Error creating ManagedZone: googleapi: Error 400: The 'entity.managedZone.description' parameter is required but was missing., required
│ 
│   with google_dns_managed_zone.mynet,
│   on main.tf line 1, in resource "google_dns_managed_zone" "mynet":
│    1: resource "google_dns_managed_zone" "mynet" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* Doesn't work with `""` as description, works with a description or without the description argument.
* Works without a description or, with a not empty string description.
* The description argument is documented as optional in the terraform provider.
* I haven't been able to find in google API documentation whether this field is optional, but the API behaves like if it's required.

### References

* https://cloud.google.com/dns/docs/reference/v1/managedZones

**Comment by edwardmedia** [comment]
@smaftoul clearly this field is required by the api. if you omit it in the config, the provider set the default `Managed by Terraform` for you. But if you sent it an empty string "", the api rejects. I think this is by design. Does this make sense?

```
Error 400: The 'entity.managedZone.description' parameter is required but was missing., required
```

**Comment by smaftoul** [comment]
I would have think that the provider must take care of that validating inputs. I want to see things failing during the plan rather than the apply.
