### ISSUE TITLE
Support google_compute_subnetwork update to IPV6

### ISSUE THREAD

**Issue by ErikEngerd** [hashicorp/terraform-provider-google#12860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It should be possible to update a subnetwork from IPV4 to dual stack IPV4_IPV6 without recreating the subnetwork. 

In concrete, first create an IPV4 subnet: 

```tf
resource "google_compute_subnetwork" "subnet-lan" {
  provider          = google
  name              = "testsubnet"
  region            = "europe-west4"
  ip_cidr_range     = "10.50.0.0/16"
  network           = "network"
}
```

Then update it to dual stack: 
```tf
resource "google_compute_subnetwork" "subnet-lan" {
  provider          = google
  name              = "testsubnet"
  region            = "europe-west4"
  ip_cidr_range     = "10.50.0.0/16"
  network           = "network"
  stack_type        = "IPV4_IPV6"
  ipv6_access_type  = "EXTERNAL"
}
```

### New or Affected Resource(s)

* google_compute_subnetwork

### Potential Terraform Configuration

The existing terraform configuration does not need to be changed. 

### References

[Google documentation](https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks) is confusing and seems to contradict itself by saying:

_The access type of IPv6 address this subnet holds. It's immutable and can only be specified during creation or the first time the subnet is updated into IPV4_IPV6 dual stack._

But it says that the update is possible. Updates are also possible through google cloud console. 

Also, updates using gcloud commandline work 

`gcloud compute networks subnets update testsubnet 
    --stack-type=IPV4_IPV6
    --ipv6-access-type=EXTERNAL`

[Debug output](https://gist.github.com/ErikEngerd/c6a120509fd875b2fa5ee988ba5731d4) from terraform 1.3.2 shows the output of the current version of terraform. 

* #12833

**Comment by ErikEngerd** [comment]
When defining a VM that has a network interface in the subnet and updating the VM to go from IPV4 to dual stack then nothing happens and the network interface is still in IPV4. Updating the network interface in the google cloud console works though. 

Network interface definition in terraform for a VM: 
```tf
network_interface { 
  ...
  stack_type = "IPV4_IPV6" 
}
```

**Comment by hao-nan-li** [comment]
b/261047629
b/261047894
b/261048516

**Comment by melinath** [comment]
b/261863885

**Comment by melinath** [comment]
@trodge I think you might have to assign yourself on the GH issue - I can't seem to do it.
