### ISSUE TITLE
google_logging_project_sink: how to disable _Default sink?

### ISSUE THREAD

**Issue by cdancy** [hashicorp/terraform-provider-google#12864]
I can't figure out for the life of me, through use of terraform, how to disable the `_Default` sink. Am I missing something? Any recommendations? Anyway I can, through use of terraform, stop that from being created?

I see it documented at least [HERE](https://cloud.google.com/logging/docs/export/configure_export_v2) which says:
```
You can't delete the _Default and the _Required sinks, but you can disable _Default sinks to stop routing logs to _Default Logging buckets. 
```

EDIT: or ... if there is some way to _configure_ the `_Default` Sink to point at one of our buckets through terraform that would be great!

**Comment by edwardmedia** [comment]
@cdancy first you can [import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink#import) the _Default  

Then you can update the [disabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink#disabled) to true with apply

Let me know if you still have questions

**Comment by cdancy** [comment]
@edwardmedia yeah this worked as expected. I was hoping to have it work in a single pass, as our automation is designed to just "do the happy path" and be done, but this got us moving forward. Thanks!
