### ISSUE TITLE
filestore instance force replacement when defining own reserved_ip_range

### ISSUE THREAD

**Issue by naimadswdn** [hashicorp/terraform-provider-google#12877]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.41.0
+ provider registry.terraform.io/hashicorp/random **v3.4.3**

### Affected Resource(s)

* google_filestore_instance

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.3.3"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.41.0"
    }
  }

  backend "local" {}
}

provider "google" {
  project = "pg-us-n-app-309204"
}

resource "google_compute_network" "vpc_network" {
  name                            = "issue-repro-vpc"
  auto_create_subnetworks         = false
  routing_mode                    = "GLOBAL"
  delete_default_routes_on_create = false
}

resource "google_compute_subnetwork" "subnetworks" {
  name                     = "issue-repro-subnetwork"
  ip_cidr_range            = "10.0.0.0/20"
  region                   = "us-east1"
  private_ip_google_access = true
  network                  = google_compute_network.vpc_network.id
}

resource "google_compute_global_address" "private_ip_address" {
  name          = "issue-repro-filestore-private-ip"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 29
  network       = google_compute_network.vpc_network.id
}

resource "google_compute_global_address" "private_ip_address_24" {
  name          = "issue-repro-filestore-private-ip-24"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  network       = google_compute_network.vpc_network.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.vpc_network.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.name, google_compute_global_address.private_ip_address_24.name]
}

resource "google_filestore_instance" "filestore" {
  name     = "issue-repro-filestore"
  location = "us-east1-b"
  tier     = "BASIC_HDD"

  file_shares {
    capacity_gb = 1024
    name        = "test_service"

    nfs_export_options {
      ip_ranges   = ["10.0.0.0/20"]
      access_mode = "READ_WRITE" 
      squash_mode = "NO_ROOT_SQUASH"
    }

  }

  networks {
    network           = google_compute_network.vpc_network.id
    modes             = ["MODE_IPV4"]
    connect_mode      = "PRIVATE_SERVICE_ACCESS"
    reserved_ip_range = google_compute_global_address.private_ip_address.name
  }

  depends_on = [
    google_service_networking_connection.private_vpc_connection
  ]

}
```

### Expected Behavior

When providing own reserved_ip_range for google_filestore_instance as a reference to google_compute_global_address, the filestore instance should not be force replaced. 

### Actual Behavior

When providing own reserved_ip_range as a reference to google_compute_global_address, the fielstore instance is created correctly (google_compute_global_address.private_ip_address.name is resolved to CIDR mask), but when running terraform plan once again, it will scream that the filestore instance need to be force replaced. Please take a look into below output from terraform plan command:

```tf
Terraform will perform the following actions:

  # module.filestore.google_filestore_instance.filestore must be replaced
-/+ resource "google_filestore_instance" "filestore" {
      ~ create_time = "2022-10-26T05:34:02.627496283Z" -> (known after apply)
      + etag        = (known after apply)
      ~ id          = "projects/XXX/locations/us-east1-b/instances/XXX" -> (known after apply)
        name        = "XXX"
      ~ project     = "XXX" -> (known after apply)
      + zone        = (known after apply)
        # (3 unchanged attributes hidden)

      ~ file_shares {
            name        = "XXX"
            # (1 unchanged attribute hidden)

          ~ nfs_export_options {
              - anon_gid    = 0 -> null
              - anon_uid    = 0 -> null
                # (3 unchanged attributes hidden)
            }
        }

      ~ networks {
          ~ ip_addresses      = [
              - "10.216.153.18",
            ] -> (known after apply)
          ~ **reserved_ip_range = "10.216.153.16/29" -> "XXX-filestore-private-ip" # forces replacement**
            # (3 unchanged attributes hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply` -> filestore instance will be created correctly.
2. `terraform plan` -> it will scream that the filestore instance need to be force replaced, because reserved_ip_range need to be changed.

### Important Factoids

Authentication as a service account with Editor and Network Admin roles.

### Workaround
Just add lifecycle to ignore reserved_ip_range changes. 

```tf
  lifecycle {
    ignore_changes = [
      networks[0].reserved_ip_range
    ]
  }
```

But that is not desirable as a final solution.

### References

* #0000

**Comment by edwardmedia** [comment]
@naimadswdn you have bunch of variables and I don't know what they are. Can you repro the issue with hard-coded config? If yes, please share the hard-coded config.

**Comment by naimadswdn** [comment]
@edwardmedia hello, thanks for looking into that. 
I have updated my original post, so it contains hard-coded values now.

**Comment by edwardmedia** [comment]
@naimadswdn can you assign the `name` to  `reserved_ip_range` as the field expects a `/29` CIDR block? Yes, it is expected that the resource will be forced recreation. This is by [design](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_filestore_instance.go#L176). Why do you think it is mutable? 

```tf
reserved_ip_range = google_compute_global_address.private_ip_address.name
```

```
[reserved_ip_range] Optional) A /29 CIDR block that identifies the range of IP addresses reserved for this instance.
```

**Comment by naimadswdn** [comment]
@edwardmedia thanks for your response. I do not think this is mutable. Let me explain it in more details. 

As you stated, `reserved_ip_range` is expected to be /29 CIDR block, BUT I have provided NAME of the `google_compute_global_address` resource and that works perfectly fine (resource created, no errors, warnings).

So if that works perfectly fine with NAME on the creation, why it screams about replacement when running terraform plan once again? 

As you can see in the Actual Behavior section, terraform is not understanding that "10.216.153.16/29" is actually pointing to NAME: "issue-repro-filestore-private-ip", so it want to replace the resource. BUT after replacement, it will be exactly the same IP address range in use. So it will destroy resource and create new, with exactly the same parameters. That is not intended.

So there are two resolutions as for me. 

1. Make sure that `google_filestore_instance` accept `reserved_ip_range` as both string with /29 CIDR block OR name of the reserved IP range and do NOT want to recreate resource when using name.
2. Add attribute reference to the `google_compute_global_address` resource, so I can reference to reserved CIDR block. Currently there is no such attribute reference, that is why I am forced to use name. (docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address#attributes-reference).

Please let me know if anything is still unclear.

**Comment by edwardmedia** [comment]
@naimadswdn could you please share the debug log? I'd like to review the api requests and responses. 

```
BUT I have provided NAME of the google_compute_global_address resource and that works perfectly fine (resource created, no errors, warnings).
```

**Comment by naimadswdn** [comment]
Hello @edwardmedia 

Debug logs uploaded here: https://gist.github.com/naimadswdn/f5fc83b0c94c93826d7bbc01024c3a0c
I have replaced project name with XXX. 

There are two files. One is from `terraform apply` command, that creates all resources, second file is output from `terraform plan` command, showing that terraform want to replace filestore instance, just after it correct creation. 

I have also edited my first post, with fixed reproduction scripts (there was small error, sorry for that).

**Comment by edwardmedia** [comment]
@naimadswdn thank you for the details. I can repro the issue. Unfortunately, there is not a fixable solution at the provider level. Basically the provider sends the name of IP and the api returns CIDR which causing the permdiff. I am reaching out to the upstream API team to see if they can fix it on their side.

**Comment by edwardmedia** [comment]
b/257089398
