### ISSUE TITLE
Error: Provider produced inconsistent result after apply at GCP project + User DB creation

### ISSUE THREAD

**Issue by mikeperello-scopely** [hashicorp/terraform-provider-google#12871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform version: 1.2.9
provider registry.terraform.io/hashicorp/google v4.41.0

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
resource "google_compute_global_address" "private_ip_address" {
  name          = "composer-ip-range"
  project = google_project.dwh_composer.project_id
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 20
  network       = google_compute_network.composer_network.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.composer_network.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.name]
}

resource "google_sql_database_instance" "main" {
  name             = "meltanodb"
  region           = google_composer_environment.main[0].region
  database_version = "POSTGRES_12"
  project = google_project.dwh_composer.project_id

  depends_on = [google_service_networking_connection.private_vpc_connection]
  
  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.composer_network.id
    }
    maintenance_window {
      day = 7
      hour = 9
    }
  }
}

resource "google_sql_user" "users" {
  name     = "meltano-user"
  instance = google_sql_database_instance.main.name
  host     = "meltano"
  password = "password"
  project  = "project"
}
```

### Expected Behavior

Terraform apply finished without error.

### Actual Behavior

The user is created in the database, but it terraform does not finish without errors:
```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.users, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@mikeperello-scopely did the error occur in the initial apply? Are all these resources in the same project? Any special settings for the network? Can you share the debug log?

**Comment by mikeperello-scopely** [comment]
Hi @edwardmedia 
The problem was with the `host` argument trying to modify a Postgres DB. Removing this argument I've been able to create the user without problems.

**Comment by edwardmedia** [comment]
@mikeperello-scopely glad you have figured this out. Happily close this issue then
