### ISSUE TITLE
Terraform detects no changes in google_bigtable_instance when all clusters are removed on update

### ISSUE THREAD

**Issue by kevinsi4508** [hashicorp/terraform-provider-google#12884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v4.41.0

### Affected Resource(s)

* google_bigtable_instance

### Terraform Configuration Files

```tf
provider "google" {
  project = "kevinsi-project"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_bigtable_instance" "instance" {
  name = "tf-instance"
  display_name = "tf instance2"
  deletion_protection=false

  labels = {
    my-label = "prod-label"
  }
}

```

### Debug Output

kevinsi@kevinsi:~/test-terraform/instance$ tf plan
google_bigtable_instance.instance: Refreshing state... [id=projects/kevinsi-project/instances/tf-instance]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

### Expected Behavior

Invalid config, at least one cluster is needed.

### Actual Behavior

No changes detected.

### Steps to Reproduce

1. `terraform apply`: Add two clusters in an instance.
2. Remove all clusters in the instance
3. `terraform apply`: Update instance with no clusters.

### References

* #0000

**Comment by kevinsi4508** [comment]
It is likely related to the logic that compares clusters using indexes: https://github.com/GoogleCloudPlatform/magic-modules/blob/adefb621cb47b0e99fce5967116a84fc3d088f88/mmv1/third_party/terraform/resources/resource_bigtable_instance.go#L541

**Comment by edwardmedia** [comment]
@kevinsi4508  how did you do in the step 2?

```
Remove all clusters in the instance
```

**Comment by kevinsi4508** [comment]
> 

First step; apply the following:

```
provider "google" {
  project = "kevinsi-project"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_bigtable_instance" "instance" {
  name = "tf-instance"
  display_name = "tf instance2"
  deletion_protection=false

  cluster {
    cluster_id   = "tf-instance-cluster2"
    num_nodes    = 1
    storage_type = "SSD"
    zone    = "us-central1-b"
  }

  cluster {
    cluster_id   = "tf-instance-cluster1"
    num_nodes    = 1
    storage_type = "SSD"
    zone    = "us-central1-c"
  }
 

  labels = {
    my-label = "prod-label"
  }
}

```

The second step: change the config to the following:

```
provider "google" {
  project = "kevinsi-project"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_bigtable_instance" "instance" {
  name = "tf-instance"
  display_name = "tf instance2"
  deletion_protection=false

  labels = {
    my-label = "prod-label"
  }
}

```

**Comment by edwardmedia** [comment]
@kevinsi4508 Below is what the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance#cluster) says. You should be able to reduce the number of cluster to 1, but not to 0. Please let me know what you think. 

```
cluster - (Required) A block of cluster configuration options. This can be specified at least once, and up to 4 times
```

**Comment by kevinsi4508** [comment]
> @kevinsi4508 Below is what the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance#cluster) says. You should be able to reduce the number of cluster to 1, but not to 0. Please let me know what you think.
> 
> ```
> cluster - (Required) A block of cluster configuration options. This can be specified at least once, and up to 4 times
> ```

Thanks Edward! I understand what it means when the cluster list is empty. That is why I mentioned:
> Expected Behavior: Invalid config, at least one cluster is needed.

I am opened b/255760356 to keep track of this issue. We can leave this issue open for now. Thanks!

**Comment by edwardmedia** [comment]
b/255760356

**Comment by kevinsi4508** [comment]
I think when there is no clusters, we are treating it as managing the clusters externally. This is an expected behavior with Optional & Computed field I believe.

It is pretty confusing. I am going to add a note to explain this behavior.
