### ISSUE TITLE
google_compute_subnetwork update INTERNAL_HTTPS_LOAD_BALANCER to REGIONAL_MANAGED_PROXY

### ISSUE THREAD

**Issue by hennna** [hashicorp/terraform-provider-google#12889]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If this is a bug report (for when something is there, but doesn't work how it should), please use the [bug issue template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md) instead.

If this is an enhancement / feature request (for when something (a resource, field, etc.) is missing, and should be added), please use the [enhancement template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md) instead.

If you have a support request or question, please check out the other resources listed [here](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md).

If your issue does not fit into one of the above templates, please fill out the following:

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Affected Resource(s)
*google_compute_subnetwork

### Terraform Configuration Files (if applicable)
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork

### Issue Description
Google subnetwork purpose INTERNAL_HTTPS_LOAD_BALANCER has been udpated to REGIONAL_MANAGED_PROXY. See https://cloud.google.com/load-balancing/docs/proxy-only-subnets#proxy_only_subnet_create. Issue request to update any references and documentation with INTERNAL_HTTPS_LOAD_BALANCER to REGIONAL_MANAGED_PROXY

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8571
