### ISSUE TITLE
google_Secret_manager_Secret_version support project field

### ISSUE THREAD

**Issue by steven-edgar** [hashicorp/terraform-provider-google#12882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resource google_secret_manager_secret_version does not support supplying the "project" field, making it impossible to store a secret in a project other than the set project. The data source for secret versions does support the project field, so we can retrieve the secret, just not set it. 

### New or Affected Resource(s)

* google_secret_manager_secret_version

### Potential Terraform Configuration

```tf
resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.id
  project = google_project.my-project.id
  secret_data = "secret-data"
}
```

### References

* #0000

**Comment by melinath** [comment]
It looks like the project should always be the same as what is in the secret's id, so providing a project separately likely doesn't make sense.
