### ISSUE TITLE
google_monitoring_alert_policy: Error when reading or editing MonitoringAlertPolicy

### ISSUE THREAD

**Issue by ryan-jan** [hashicorp/terraform-provider-google#12898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.15.1
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.24.0
+ provider registry.terraform.io/hashicorp/google-beta v4.24.0
+ provider registry.terraform.io/hashicorp/http v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `google_monitoring_alert_policy`

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "uptime_alert" {
  enabled      = local.uptime_check.alert_enabled
  display_name = "Uptime check for ${var.host} (${terraform.workspace})"
  notification_channels = [
    for channel in google_monitoring_notification_channel.email : channel.id
  ]

  combiner = "OR"

  conditions {
    display_name = "Uptime check has run for ${var.host} (${terraform.workspace})"

    condition_absent {
      filter = trimspace(replace(
        <<-EOT
        metric.type="monitoring.googleapis.com/uptime_check/check_passed" AND
        metric.label.check_id="${google_monitoring_uptime_check_config.https.uptime_check_id}" AND
        resource.type="uptime_url"
        EOT
        , "\n", " "
      ))
      # absent conditions have to have a min duration of 2 minutes
      duration = "${max(local.uptime_check.period, 120)}s"

      aggregations {
        # absent conditions have to have a min duration of 2 minutes
        alignment_period     = "${max(local.uptime_check.period, 120)}s"
        cross_series_reducer = "REDUCE_COUNT"
        group_by_fields      = []
        per_series_aligner   = "ALIGN_COUNT"
      }

      trigger { count = 1 }
    }
  }

  conditions {
    display_name = "Uptime check passed for ${var.host} (${terraform.workspace})"

    condition_threshold {
      filter = trimspace(replace(
        <<-EOT
        metric.type="monitoring.googleapis.com/uptime_check/check_passed" AND
        metric.label.check_id="${google_monitoring_uptime_check_config.https.uptime_check_id}" AND
        resource.type="uptime_url"
        EOT
        , "\n", " "
      ))
      duration   = "${local.uptime_check.period}s"
      comparison = "COMPARISON_LT"

      threshold_value = local.uptime_check.success_threshold_percent / 100

      aggregations {
        alignment_period     = "${local.uptime_check.period}s"
        cross_series_reducer = "REDUCE_FRACTION_TRUE"
        per_series_aligner   = "ALIGN_NEXT_OLDER"
      }

      trigger { count = 1 }
    }
  }
}

```

### Behavior

We have the above resource defined in an in-house module which we are referencing in one of our terraform configurations. Yesterday we had a strange situation where we were receiving the following error message when running `terraform plan` or `terraform apply`:

```tf
╷
│ Error: Error when reading or editing MonitoringAlertPolicy "projects/<id>/alertPolicies/<id>": googleapi: Error 403: Rejected by RpcSecurityPolicy for /ConfigService.GetModule: Rejected by AUTOMATIC_IAM system_authorization_policy check: Permission 'service.prevent_human_read_access' not granted to cloud-monitoring-alert-policy-api@prod.google.com, because a DENY rule was triggered: {permissions: "service.prevent_human_read_access" action: DENY conditions { iam: ATTRIBUTION op: NOT_IN values: "mdb:all-person-users" }}.; RpcSecurityPolicy http://rpcsp/p/EitAQ3pxGwaX3w1xc7gzo1FNUqsOwKED-AdY; If you already provided justification (go/admin_session) and still face a permission denied error, follow go/cloud-monarch-data-access#namespace-cloud-prod-2 for write access and go/cloud-monarch-data-access#namespace-cloud-prod for read access.
│ 
│   with module.webapp_monitoring["default"].google_monitoring_alert_policy.uptime_alert,
│   on /terraform_data/modules/webapp_monitoring/main.tf line 45, in resource "google_monitoring_alert_policy" "uptime_alert":
│   45: resource "google_monitoring_alert_policy" "uptime_alert" {
│ 
╵
```

This lasted a number of hours and then just stopped happening and we've been able to apply the configuration successfully every since, with no changes on our part to make this start working.

Is this a known issue? Did it happen to anyone else?

We are assuming that this was an issue at the API end but want to raise an issue to discuss and find out if there was anything we could have done to workaround the issue at the time to allow us to continue our deployments.

b/275110042

**Comment by melinath** [comment]
It looks like this was a time-bounded issue with the API which was resolved. Please open a new issue if that's incorrect. Thanks!
