### ISSUE TITLE
google_firestore_document resource - updating collection/document_id doesn't apply change

### ISSUE THREAD

**Issue by oliwilkinsonio** [hashicorp/terraform-provider-google#12897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.41.0
```

### Affected Resource(s)

Resources:
* google_firestore_document

### Terraform Configuration Files

Before:
```tf
resource "google_firestore_document" "role" {
  collection  = "role"
  document_id = "my-doc"

  fields = jsonencode({
    name = { stringValue = "Test" },
  })
}
```

After:
```tf
resource "google_firestore_document" "role" {
  collection  = "updated-role"
  document_id = "my-doc"

  fields = jsonencode({
    name = { stringValue = "Test" },
  })
}
```

Additional example:
```tf
resource "google_firestore_document" "role" {
  collection  = "role"
  document_id = "my-doc-is-changed"

  fields = jsonencode({
    name = { stringValue = "Test" },
  })
}
```

### Expected Behavior

The google firestore document should be detected as changed, and a replacement created (likely a DELETE/CREATE as the document would be recreated in firestore).

### Actual Behavior

Terraform does not detect a change.
```
No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

1. Create a new `google_firestore_document`
2. `terraform apply`
3. Update either the `collection` or `document_id` on the resource 
4. `terraform apply`
5. Observe no changes detected

b/275100803

**Comment by edwardmedia** [comment]
@oliwilkinsonio can you share the debug logs for both apply?

**Comment by edwardmedia** [comment]
Instead of recreating collection or document, the update (PATCH) appears to resend the same payload
 
```
---[ REQUEST ]---------------------------------------
PATCH /v1/projects/myproject/databases/(default)/documents/role/my-doc?alt=json HTTP/1.1
Host: firestore.googleapis.com

{
 "fields": {
  "name": {
   "stringValue": "Test"
  }
 }
}
```
