### ISSUE TITLE
resource "google_service_account_key" public_key_data conflicts with Key_algorithm

### ISSUE THREAD

**Issue by densnoigaskogen** [hashicorp/terraform-provider-google#12895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version: 1.2.7

### Affected Resource(s)

resource "google_service_account_key"

### Terraform Configuration Files

resource "google_service_account_key" "our_own_key" {
  service_account_id = google_service_account.ourserviceaccount.name
  public_key_data    = "xxxxxxxxxxxxxxxxx"   
}

### Expected Behavior

We have successfully upload customer-managed public key data into the service account. However, after re-running the terraform script, it proposes replacement and automatically added two default arguments: "**key_algorith**" and **"private_key**". This should not be added, would this be a bug? 

### Actual Behavior

![image](https://user-images.githubusercontent.com/33136996/198282855-30ea8524-a33a-4bd3-a1ad-f14b2b15934b.png)

### References

[](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_key)

* #0000

**Comment by edwardmedia** [comment]
@densnoigaskogen I can't repro the issue. After initial deployment, re-applying the same resource shows `No changes`
What version of the provider do you use? Did you manually do anything before two applies?

**Comment by edwardmedia** [comment]
@densnoigaskogen is this still an issue?

**Comment by densnoigaskogen** [comment]
hi @edwardmedia , my apology for the delayed response. We tested other  public_keys generated by ourselves, they all works fine in intended, it seems like the issue is with this specific public_key (which is provided by external company) we used in this case. Do you have any thoughts on what could be missing in a public key that could cause the force replacement each time running terraform script?

**Comment by edwardmedia** [comment]
@densnoigaskogen do you know what algorithm the key is used? [KEY_ALG_RSA_2048](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_key#key_algorithm) is the default. If yours is different, you need to provide yours. Let me know if that helps

```
key_algorithm : "KEY_ALG_RSA_2048"
```

**Comment by edwardmedia** [comment]
@densnoigaskogen is this still an issue?

**Comment by edwardmedia** [comment]
@densnoigaskogen closing this assuming it is no longer an issue
