### ISSUE TITLE
Failing test(s): ForceNew permadiff: TestAccDocumentAIProcessorDefaultVersion_documentaiDefaultVersionExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12905]
### Affected Resource(s)

* google_document_ai_processor_default_version

Failure rate: 100% since 2022-09-13

Impacted tests:
- TestAccDocumentAIProcessorDefaultVersion_documentaiDefaultVersionExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/348525?buildTab=tests&expandedTest=1789998193111564552

Message:

```
# google_document_ai_processor_default_version.processor must be replaced
-/+ resource "google_document_ai_processor_default_version" "processor" {
~ id        = "projects/project-id/locations/us/processors/e79fa191ecd3e06d" -> (known after apply)
~ version   = "projects/123456789/locations/us/processors/e79fa191ecd3e06d/processorVersions/pretrained-ocr-v1.0-2020-09-23" -> "projects/project-id/locations/us/processors/e79fa191ecd3e06d/processorVersions/pretrained-next" # forces replacement
# (1 unchanged attribute hidden)
}
Plan: 1 to add, 0 to change, 1 to destroy.
```

It looks like the API team started converting the project-id to project-number the morning of Sept. 13th.

**Comment by AarshDhokai** [comment]
- TestAccDocumentAIProcessorDefaultVersion_documentaiDefaultVersionExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/1789998193111564552?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure 
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/1789998193111564552?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure

**Comment by melinath** [comment]
Could likely resolve this with `projectNumberDiffSuppress`

**Comment by melinath** [comment]
`projectNumberDiffSuppress` is already in use. The issue is actually that `pretrained-next` is being replaced with `pretrained-ocr-v1.0-2020-09-23`. This is due to a change in how [model versions are managed](https://cloud.google.com/document-ai/docs/manage-processor-versions) - that naming scheme is no longer in use. There are now release channels instead, like `projects/my-proj/locations/us/processors/my-processor/processorVersions/stable`. Using the release channels directly would have the same permadiff behavior observed with `pretrained-next`.

We should probably suppress the diff, though I think there's a risk that folks will end up in a state where they don't see there's a _new_ version of the release branch available.

We could also consider something like https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_engine_versions to allow querying available processor versions. The DocumentAI only allows listing available versions within a particular processor, so it's convenient that the default version resource is separate - we could have a datasource that reads available versions for the processor and feeds them as input to the default version resource.

**Comment by melinath** [comment]
There doesn't seem to be a way to determine whether a particular version is rc or stable, so I think it's currently not possible to make a datasource that would spit out the latest stable version.
