### ISSUE TITLE
Failing test(s): TestAccDNSManagedZone_dnsManagedZoneQuickstartExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12906]
### Affected Resource(s)

* google_dns_managed_zone

Failure rate: 100% since 2022-09-24

Impacted tests:
- TestAccDNSManagedZone_dnsManagedZoneQuickstartExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/348525?buildTab=tests&expandedTest=-3604989738191621873

Message:

```
Error: Error creating ManagedZone: googleapi: Error 400: Please verify ownership of the 'googlecloudexample.com.' domain (or a parent) at http://www.google.com/webmasters/verification/ and try again
```

Similar issue: https://github.com/hashicorp/terraform-provider-google/issues/12528

Previously this was failing with this error sporadically - possibly this was a new verification that rolled out?

**Comment by hao-nan-li** [comment]
b/260590932

**Comment by AarshDhokai** [comment]
- TestAccDNSManagedZone_dnsManagedZoneQuickstartExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/-3604989738191621873?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/-3604989738191621873?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure

**Comment by AarshDhokai** [comment]
b/261395835

**Comment by roaks3** [comment]
It looks like this was resolved with https://github.com/GoogleCloudPlatform/magic-modules/pull/6918
