### ISSUE TITLE
Failing test(s): TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12904]
### Affected Resource(s)

* google_healthcare_fhir_store

Failure rate: 100% since added on 2022-09-27

Impacted tests:
- TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/348525?buildTab=tests&expandedTest=5334929892186247633

Message:

```
Error: Unsupported block type
on terraform_plugin_test.tf line 16, in resource "google_healthcare_fhir_store" "default":
16:   notification_configs {
Blocks of type "notification_configs" are not expected here. Did you mean
"notification_config"?
```

This is likely a typo in the test.

**Comment by AarshDhokai** [comment]
- TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/5334929892186247633?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/5334929892186247633?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 1% failure

**Comment by AarshDhokai** [comment]
b/261702502
