### ISSUE TITLE
Dataproc: No options to enable metrics

### ISSUE THREAD

**Issue by asaushkin** [hashicorp/terraform-provider-google#12916]
### Affected Resource(s)

* google_dataproc_cluster

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the official documentation, there is a way to enable additional OSS metrics on cluster https://cloud.google.com/dataproc/docs/guides/monitoring#enable_oss_metric_collection

Unfortunately, there is no such ability with the terraform code

I believe, it could be great if we add blocks to enable the OSS metrics

```
resource "google_dataproc_cluster" "dp_cluster" {
  cluster_config {
    metric_sources = [] // array of strings
    metric_overrides = [] // array of strings
  }
}
```

**Comment by cjac** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/6788

**Comment by roaks3** [comment]
This appears to have been fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6889

**Comment by cjac** [comment]
Thank you Ryan!
