### ISSUE TITLE
Failing test(s): TestAccDataSourceDnsManagedZone_basic

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12911]
### Affected Resource(s)

* google_dns_managed_zone

Failure rate: 100% since 2022-09-29

Impacted tests:
- TestAccDataSourceDnsManagedZone_basic

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/348525?buildTab=tests&expandedTest=1849171833069796537

Message:

```
provider_test.go:307: Step 1/1 error: Check failed: cloud_logging_config.0.% is ; want 1
cloud_logging_config.# is ; want 1
cloud_logging_config.0.enable_logging is ; want false
```

**Comment by AarshDhokai** [comment]
- TestAccDataSourceDnsManagedZone_basic
[Google Cloud](https://ci-oss.hashicorp.engineering/test/1849171833069796537?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) 100% failure

**Comment by AarshDhokai** [comment]
b/261394223

**Comment by rileykarson** [comment]
Resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/7312
