### ISSUE TITLE
GKE cluster pubsub notification - Composer2

### ISSUE THREAD

**Issue by edge7** [hashicorp/terraform-provider-google#12919]
Hello,

we are currently using Composer2 which under the hood creates a GKE Cluster.
In the GKE cluster there is the following option
![image](https://user-images.githubusercontent.com/5433786/199246705-a6441a2c-cdb4-4610-a422-ab00e1729c9c.png)
i.e.: 
Notifications for upgrades.

Is possible to modify such an option through the Composer2 Terraform module?

**Comment by edwardmedia** [comment]
@edge7 take a look at below available environment config of the api, it seems not possible right now. Once the api open the features, you may file enhancements for Terraform support request

https://cloud.google.com/composer/docs/reference/rest/v1/projects.locations.environments#Environment
