### ISSUE TITLE
Cloudbuild Trigger's Pubsub Config State Should Reflect Values Returned by API

### ISSUE THREAD

**Issue by DXCanas** [hashicorp/terraform-provider-google#12925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_cloudbuild_trigger

### Expected Behavior

I thought that I would be able to read `google_cloudbuild_trigger.example_trigger.pubsub_config.state` and understand what the implicitly created pubsub subscription's [state](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#state) is.

This would be useful for checking if the subscription exists and prompting the person running the plan.

### Actual Behavior

`pubsub_config.state`, which is [listed in the docs as an argument](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#state), is not an argument (but a Computed Attribute), and the value never updates according to what the [API presumably returns](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#state).  

### Steps to Reproduce

1. `terraform plan`
2. access `google_cloudbuild_trigger.example_trigger.pubsub_config.state` to have an up to date value

**Comment by edwardmedia** [comment]
@DXCanas can you share your debug log so we can take a look if `state` is available. Below is the block I see that is returned from the API. 

```
  "pubsubConfig": {
    "subscription": "projects/389245123456/subscriptions/gcb-issue12925-pubsub-trigger",
    "topic": "projects/myprojectt/topics/issue12925"
  },
```

**Comment by DXCanas** [comment]
Hm, seems you're right — I'm also not seeing it in the debug logs, despite the fact that I've deleted the corresponding subscription (so it should be `"state":"SUBSCRIPTION_DELETED"` in theory):

```
Request Details:
---[ REQUEST ]---------------------------------------
GET /v1/projects/OBFUSCATED/triggers/OBFUSCATED?alt=json HTTP/1.1
Host: cloudbuild.googleapis.com
User-Agent: Terraform/1.3.3 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/dev
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-11-02T11:26:43.100-0700
2022-11-02T11:26:43.700-0700 [INFO]  provider.terraform-provider-google_v4.42.0_x5: 2022/11/02 11:26:43 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Wed, 02 Nov 2022 18:26:43 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "id": "OBFUSCATED",
  "build": {
    "source": {
      "storageSource": {
        "bucket": "OBFUSCATED",
        "object": "OBFUSCATED"
      }
    },
      {
        "name": "OBFUSCATED",
        "args": [
            "OBFUSCATED"
        ],
        "id": "OBFUSCATED"
      }
    ],
    "timeout": "600s",
    "images": [
      "OBFUSCATED",
    ],
    "options": {
      "env": [
        "OBFUSCATED",
      ],
      "dynamicSubstitutions": true
    }
  },
  "createTime": "2022-09-30T18:12:25.419090734Z",
  "description": "OBFUSCATED",
  "substitutions": {
    "OBFUSCATED": "OBFUSCATED"
  },
  "name": "OBFUSCATED",
  "pubsubConfig": {
    "subscription": "projects/OBFUSCATED/subscriptions/OBFUSCATEDr",
    "topic": "projects/OBFUSCATED/topics/OBFUSCATED"
  }
}
```

Curious, though, [as the API documents that `state` _should_ be populated on `GET`](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#state):
> Potential issues with the underlying Pub/Sub subscription configuration. Only populated on get requests.

But I'm not even seeing this in `GET` requests from their API explorer. 

Deferring to greater experience: is this a bug in the API, or is there some other endpoint that we're supposed to be `GET`ting for this information?

**Comment by edwardmedia** [comment]
@DXCanas I can't explain what the API doc mean you referred to. You may reach out to the related teams to see if you can get the details. Based on what in the response from the api, it appears we are unable to make `state` available at this moment. Does this make sense? Closing the issue now. Feel free to reopen if you have further info to make it possible. Thanks

```
  "pubsubConfig": {
    "subscription": "projects/OBFUSCATED/subscriptions/OBFUSCATEDr",
    "topic": "projects/OBFUSCATED/topics/OBFUSCATED"
  }
```
