### ISSUE TITLE
Feature request: google_access_context_manager_service_perimeter_ingress_policy and google_access_context_manager_service_perimeter_egress_policy resources

### ISSUE THREAD

**Issue by wmuizelaar** [hashicorp/terraform-provider-google#12927]
### Affected Resource(s)

* google_access_context_manager_service_perimeter_ingress_policy
* google_access_context_manager_service_perimeter_egress_policy

Hi,

I filed https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/727 to add more granular support for dealing with VPC SC resources. This includes separate resources for ingress policies and egress policies, following the same pattern as the current `google_access_context_manager_service_perimeter_resource` resource in the Terraform provider.

Could these seperate resources be implemented?

For `google_access_context_manager_serivce_perimeter_ingress_policy`, the schema would be the same as the existing `ingress_policies` block in the perimeter-resource, and for the `google_access_context_manager_service_perimeter_egress_policy` the schema would be the same as the `egress_policies` block.

## References

* b/258778964

**Comment by AlfatahB** [comment]
[google_access_context_manager_service_perimeter](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter) has `ingress_policies` and `egress_policies` fields. I was able to find gcloud commands for [setting/updating ingress and egress policies for a service perimeter](https://cloud.google.com/vpc-service-controls/docs/configuring-ingress-egress-policies#gcloud) during creation/updation of that particular service parameter. But, I was unable to find gCloud command or an API doc for configuring ingress and egress policies separately.

**Comment by rileykarson** [comment]
Note: While initial revisions were submitted in https://github.com/GoogleCloudPlatform/magic-modules/pull/7762 and https://github.com/GoogleCloudPlatform/magic-modules/pull/7765, they didn't work as intended (as reported by https://github.com/hashicorp/terraform-provider-google/issues/14425) and are planned to be reworked substantially.

**Comment by roaks3** [comment]
@melinath per your comment on b/258778964, should we forward a new issue to the service team?

**Comment by melinath** [comment]
@roaks3 I think we are still holding this issue - attn @c2thorn @hao-nan-li to confirm.

**Comment by hao-nan-li** [comment]
This feature should've been completed. https://github.com/GoogleCloudPlatform/magic-modules/pull/8038

**Comment by melinath** [comment]
cool, closing as completed in that case.
