### ISSUE TITLE
Datasource for datastream static IPs

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As part of setting up a datastream connection with postgres, you have to allowlist the authorized networks. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/datastream_connection_profile#example-usage---datastream-connection-profile-postgres

The IP addresses in the example are datastream APIs. Instead of requiring users to find these addresses (or use them from the example) it would be great to have a datasource that returns them by calling https://cloud.google.com/datastream/docs/reference/rest/v1/projects.locations/fetchStaticIps.

### New or Affected Resource(s)

* datasource google_datastream_static_ips

### Potential Terraform Configuration

Compare to [Example Usage - Datastream Connection Profile Postgres](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/datastream_connection_profile#example-usage---datastream-connection-profile-postgres)

```tf
# This is pseudocode
datasource "google_datastream_static_ips" "static_ips" {
    location = "us-central1"
}
resource "google_sql_database_instance" "instance" {
    name             = "my-instance"
    database_version = "POSTGRES_14"
    region           = "us-central1"
    settings {
        tier = "db-f1-micro"

        ip_configuration {
            // Datastream IPs will vary by region.
            authorized_networks {
                for_each = datasource.google_datastream_static_ips.static_ips.static_ips
                value = each.value
            }
    }

    deletion_protection  = "true"
}
```

### References

* b/233804820

**Comment by rjackson** [comment]
I've been working on this. About to raise a PR :)
