### ISSUE TITLE
Why is `google_cloud_run_service` tainted?

### ISSUE THREAD

**Issue by birdx0810** [hashicorp/terraform-provider-google#12939]
as the title suggests, the `google_cloud_run_service` is tainted, and would destroy and re-create a new one every time `terraform apply` is made. What are the reasons and if they are valid, are there better workarounds other than untaint?

**Comment by edwardmedia** [comment]
@birdx0810 it shouldn't. Can you share your config so I can repro?

**Comment by birdx0810** [comment]
Sorry for the hassle, but I realized I couldn't reproduce this after untainting my initial `google_cloud_run_service` although I'm quite sure I've never tainted it in the first place. I'll close this issue.
