### ISSUE TITLE
Set Apigee Addons

### ISSUE THREAD

**Issue by danistrebel** [hashicorp/terraform-provider-google#12936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Apigee Customers that want to enable addons such as monetization or advanced API security have to call the following method https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations#IntegrationConfig

### New or Affected Resource(s)

Either as a property of

google_apigee_organization
or a standalone resource

google_apigee_organization_addons

**Comment by rileykarson** [comment]
Note: This likely makes the most sense as a property of google_apigee_organization given the shape of the API! If it isn't returned in GET, we could consider a separate resource like google_apigeee_organization_addons

**Comment by melinath** [comment]
b/270217301

**Comment by rileykarson** [comment]
Supported in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_addons_config, added by https://github.com/GoogleCloudPlatform/magic-modules/pull/7176 in `4.53.0`
