### ISSUE TITLE
google_vertex_ai_endpoint: Cannot determine region

### ISSUE THREAD

**Issue by gericdong** [hashicorp/terraform-provider-google#12944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.7

### Affected Resource(s)

google v4.42.0

* google_vertex_ai_endpoint

### Terraform Configuration Files

```tf
resource "random_id" "endpoint_id" {
  byte_length = 4
}

resource "google_vertex_ai_endpoint" "main" {
  name         = substr(random_id.endpoint_id.dec, 0, 10)
  display_name = "sample-endpoint"
  description  = "A sample Vertex AI endpoint"
  location     = "us-central1"
  labels = {
    label-one = "value-one"
  }
}
```

### Debug Output

When I didn't set field "region" on the resource level, got error:
╷
│ Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
│ 
│   with google_vertex_ai_endpoint.main,
│   on main.tf line 21, in resource "google_vertex_ai_endpoint" "main":
│   21: resource "google_vertex_ai_endpoint" "main" {
│ 
╵
When I set field "region" on the resource level, got error:
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 26, in resource "google_vertex_ai_endpoint" "main":
│   26:   region = "us-central1"
│ 
│ An argument named "region" is not expected here.

### Expected Behavior

An endpoint should be created successfully if field "location" is provided on the resource level.

### Actual Behavior

Error "Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'." occurred when location field is set. And when setting "region" on the resource level, error "Unsupported argument" occurred.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
This is a bug. This happens when `region` and `location` does not match. 

[VertexAIBasePath](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_vertex_ai_endpoint.go#L330) contains {{region}}

**Comment by xkobal** [comment]
HI @edwardmedia , I have the same problem, I'm unable to create an endpoint in a different region from the ressource one. 
Bug I need to create and endpoint in `europe-west4` and I have the error `"The provided location ID doesn't match the endpoint. The valid location ID is europe-west1"` which is my default region for my project. 

How can I fix this ?

**Comment by rileykarson** [comment]
We can introduce a `region` field and fix this bug without a breaking change, we've supported multiple locations on GKE Instance in the past. Removing `location` for consistency with the rest of the product would take a breaking change in the future, though.

**Comment by mahvar** [comment]
Any ETA for this fix?

**Comment by mahvar** [comment]
I understand the workaround is to set the region at provider level, but since we are creating vertex endpoints in a loop, we are facing [lack of support for instantiating provider in a loop](https://github.com/hashicorp/terraform/issues/19932). Any advice?
