### ISSUE TITLE
Documentation Page not loading - affecting multiple providers/resources.

### ISSUE THREAD

**Issue by papqin** [hashicorp/terraform-provider-google#12942]
Documentation Link
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager

Description
Sites are not loading the docs.

References
No response

Would you like to implement a fix?
No response

**Comment by RiccardoGrigoletto** [comment]
Same here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository

**Comment by msampathkumar** [comment]
same here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/os_config_patch_deployment

Thanks for the note @SarahFrench
