### ISSUE TITLE
GCP provider upgrade for terraform destroys the resource

### ISSUE THREAD

**Issue by aagakhar** [hashicorp/terraform-provider-google#12940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.14
google provider version 4.40.0

### Affected Resource(s)

* google_bigquery_table
### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.40.0"
    }
  }

  required_version = ">= 0.14"
}

### Debug Output
1) 
![image](https://user-images.githubusercontent.com/86243791/199729308-583d3ab5-d527-45a9-958b-df95b2b832e4.png)
![image](https://user-images.githubusercontent.com/86243791/199729740-5aeb7c7e-5607-443c-8e52-b93d8f768ac3.png)
In existing schema _m field comes after _a but now with new provider it is changing the sequence and hence replacing the fields with each other.

2) In another scenario when the JSON schema contains a STRUCT field, terraform plan again says 1 to be destroyed and shows that STRUCT will be replaced by RECORD.

### Expected Behavior

terraform plan should say 0 resource created and 0 resource destroyed. There should be no change to the existing resoources.

### Actual Behavior

There was no change to the BQ table schema or any terraform variable for BQ resource. But when terraform plan was done for existing BQ resource, it shows the table will be destroyed and new table will be created either because of the sequence of the fields changed in the schema returned by the terraform update API or due to the STRUCT data type in json schema should be changed to RECORD.
This behavior is not seen with earlier google provider version used, which is 3.55.0.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
@aagakhar can you share your config?

**Comment by aagakhar** [comment]
Hi Edward,
PFA. Please let me know if you are expecting the same and any further information.
[config files.zip](https://github.com/hashicorp/terraform-provider-google/files/9938379/config.files.zip)

**Comment by AJ5731** [comment]
@shuyama1 @edwardmedia Do we have any update on this issue ? Terraform is showing completely strange behaviour while plan. Sometime it says nothing to destroy and sometime it says destroy and create again. Below is the output I have seen when I tried to apply changes.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/98585422/207296323-a299a1ed-9533-40e7-9f62-200f3f4530d6.png">

**Comment by edwardmedia** [comment]
@AJ5731 @aagakhar anyway I can repro this issue? Can you post the [config](https://github.com/hashicorp/terraform-provider-google/issues/12940#issuecomment-1303490654) over here? (I can't download files)

**Comment by AJ5731** [comment]
> @AJ5731 @aagakhar anyway I can repro this issue? Can you post the [config](https://github.com/hashicorp/terraform-provider-google/issues/12940#issuecomment-1303490654) over here and list the steps to repro? (I can't download files)

@edwardmedia Please find the example configs over here to reproduce the issue.

> main.tf

```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.40.0"
    }
  }
  required_version = ">= 0.14"
}

provider "google" {
  region  = "us-central1"
  project = "<< GCP_PROJECT >>"
}

resource "google_bigquery_dataset" "test_dataset" {
  dataset_id         = "test_dataset"
  friendly_name      = "test-db"
  project            = "<< GCP_PROJECT >>"
  description        = "This is a test description"
  location           = "US"
  labels = {
    env = "sandbox"
  }
}

resource "google_bigquery_table" "test_table" {
  project = "<< GCP_PROJECT >>"
  dataset_id = google_bigquery_dataset.test_dataset.dataset_id
  table_id   = "t_aos_updates"
  schema     = file("test.json")
  time_partitioning {
    type  = "DAY"
    field = "_et"
  }
  clustering = ["_o"]
  labels = {
    env = "sandbox"
  }
  deletion_protection=false
}
```

> test.json
```
[ {
  "description" : "marker",
  "mode" : "NULLABLE",
  "name" : "_c",
  "type" : "STRING"
}, {
  "description" : "Entity",
  "mode" : "REQUIRED",
  "name" : "_e",
  "type" : "STRING"
}, {
  "description" : "Effective Timestamp",
  "mode" : "REQUIRED",
  "name" : "_et",
  "type" : "TIMESTAMP"
}, {
  "description" : "Identifier",
  "mode" : "REQUIRED",
  "name" : "_id",
  "type" : "STRING"
}, {
  "description" : "Message Type",
  "mode" : "REQUIRED",
  "name" : "_mt",
  "type" : "STRING"
}, {
  "description" : "Owner",
  "mode" : "REQUIRED",
  "name" : "_o",
  "type" : "STRING"
}, {
  "description" : "Process Timestamp",
  "mode" : "REQUIRED",
  "name" : "_pt",
  "type" : "TIMESTAMP"
}, {
  "description" : "Source",
  "mode" : "NULLABLE",
  "name" : "_src",
  "type" : "STRING"
}, {
  "fields" : [ {
    "mode" : "NULLABLE",
    "name" : "assetClass",
    "type" : "STRING"
  }, {
    "mode" : "NULLABLE",
    "name" : "id",
    "type" : "STRING"
  }, {
    "fields" : [ {
      "mode" : "NULLABLE",
      "name" : "accountName",
      "type" : "STRING"
    }, {
      "mode" : "NULLABLE",
      "name" : "accountNumber",
      "type" : "STRING"
    }, {
      "mode" : "NULLABLE",
      "name" : "confidence",
      "type" : "INT64"
    }, {
      "mode" : "NULLABLE",
      "name" : "createdBy",
      "type" : "STRING"
    }, {
      "mode" : "NULLABLE",
      "name" : "justification",
      "type" : "STRING"
    }, {
      "mode" : "NULLABLE",
      "name" : "lastModified",
      "type" : "TIMESTAMP"
    }, {
      "mode" : "NULLABLE",
      "name" : "lastModifiedBy",
      "type" : "STRING"
    } ],
    "mode" : "REPEATED",
    "name" : "justifications",
    "type" : "STRUCT"
  }, {
    "mode" : "NULLABLE",
    "name" : "lastModified",
    "type" : "TIMESTAMP"
  }, {
    "mode" : "NULLABLE",
    "name" : "lastModifiedBy",
    "type" : "STRING"
  } ],
  "mode" : "NULLABLE",
  "name" : "_a",
  "type" : "STRUCT"
}, {
  "mode" : "NULLABLE",
  "name" : "_m",
  "type" : "STRING"
}, {
  "mode" : "NULLABLE",
  "name" : "removeAllAccount",
  "type" : "STRING"
}, {
  "mode" : "NULLABLE",
  "name" : "type",
  "type" : "STRING"
} ]
```

- **Steps to reproduce:**

1. Use given main.tf and test.json file to create BQ dataset and table.
2. First terraform apply will create one BQ dataset and one table (Provided schema should be used in table).
3. You will the strange terraform behaviour in next terraform  **plan** or **apply**. Sometimes output of terraform plan/apply is "Plan: 0 to add, 1 to change, 0 to destroy." and sometimes "Plan: 1 to add, 0 to change, 1 to destroy"

![](https://jira.zebra.com/secure/attachment/2860560/2860560_image-2022-12-13-19-42-47-407.png)

![](https://jira.zebra.com/secure/attachment/2860559/2860559_image-2022-12-13-19-42-29-906.png)

5. Even if you apply changes to destroy table and create it again, next terraform apply will again show this strange behaviour.

**Comment by edwardmedia** [comment]
@aagakhar I tested your sample provided [here](https://github.com/hashicorp/terraform-provider-google/issues/12940#issuecomment-1350850016). It seems you need to update the schema in test.json for two types below. After the update was made. It all works fine. Is this the issue you talked about? 

"STRUCT" => "RECORD" 
"INT64" => "INTEGER"

**Comment by edwardmedia** [comment]
@aagakhar I have tested. I do see the same behavior for all the versions from v3.70.0 to the latest. Unfortunately the provider binary is not available for versions before v3.60.0 for my machine, so I can't verify whether it is a provider issue or an API's. I do not see breaking changes from 3.55.0 so I can't comment further on what was really going on. 

My guess this is likely is on APIs. If so, there is not much we can do at the provider level. Is that possible you make schema changes like below?

"INT64" => "INTEGER"
"STRUCT" =>"RECORD"

Does this make sense?

**Comment by aagakhar** [comment]
Hi @edwardmedia : Thanks for your suggestion. It seems to be working. So basically it is now expecting Legacy BQ data types instead of Standard SQL data types in Schema. 
Although its not clear why Legacy data types are expected when Standard data types are recommended. If you do have any insight on the same, please suggest.
We just need to be sure that going forward with any further upgraded version, it shall not create issues again.

**Comment by edwardmedia** [comment]
@aagakhar These are the types the API provides. I do not have insights. You may check out the API documents for its suggestions. 
Glad you have found the fix. I am gonna close the issue then. Thank you
