### ISSUE TITLE
Artifact Registry: warn about `gcr.io` redirection if creating a `gcr.io` repo

### ISSUE THREAD

**Issue by ace-n** [hashicorp/terraform-provider-google#12970]
### Terraform Version
```
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.43.0
```

### Affected Resource(s)

* google_artifact_registry_repository

### Issue Description

To map an Artifact Registry repository to a `gcr.io` domain, one must do _both_ of the following:
1) [Enable redirection of gcr.io traffic](https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo#redirect-enable).
2) Set the `google_artifact_registry_repository.repository_id` value accordingly (for example, to `gcr.io`).

When doing Step 2, there is no notification (from either Terraform itself or the Artifact Registry API) that Step 1 is required.

We should fix that to reduce end-user confusion. :)

[Debug output of `terraform apply --auto-approve`](https://gist.github.com/ace-n/d74ac499167f6b6deab9e92466947954)

### Terraform Configuration Files
Here's an example of an Artifact Registry repo with [`gcr.io` redirection](https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo) enabled.

```tf
resource "google_artifact_registry_repository" "ace-test-repo" {
  location          = "us"
  project           = "<PROJECT_ID>"
  description       = "Docker repository"
  format            = "DOCKER"

  // This is a special value, and should emit a WARNING message pointing to:
  //   https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo#redirect-enable
  // See `gcloud` instructions here:
  //   https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo#create-manual
  repository_id     = "gcr.io"
}
```

**Comment by edwardmedia** [comment]
@ace-n I am not sure what the issue here. I have tried creating the resources for  `gcr.io` and `eu.gcr.io`, all seem fine. What WARNING message do you suggest, and where / when should the message be provided? I noticed you choose `--auto-approve'. shouldn't the plan play that role that shows what will be creating?

**Comment by ace-n** [comment]
I'm arguing that anything ending in `gcr.io` is a "special value". These values should remind users that:
> **Note:** if you're using gcr.io repositories with Artifact Registry, be sure to enable gcr.io redirection
>
> See the official documentation for more information:
>   https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo#redirect-enable

(Maybe this could be part of the `plan` stage?)

**Comment by edwardmedia** [comment]
@ace-n Thanks for the suggestion. But I don't think there is a pattern that WARNING messages can be injected in the `plan`. The other option I can think of is the documentation. But this is very detail at the downstream.  There are much more requirements at the same level that could be asked to add. One example is `google_cloudbuild_trigger` when `github.com` is chosen. On the other side, the provider has no control over these materials. To be more effective and accurate, there are links at the top of each resource. does this make sense?

**Comment by ace-n** [comment]
If the Terraform team has a philosophy of including (or not including) information like this, then I'm happy to follow that approach.

If there **isn't** an existing philosophy, that may be a ~P2 worth discussing (e.g. with UX folks) in the future.

**Comment by edwardmedia** [comment]
@ace-n good idea to pursue further discussions in the future.

You are also welcome to file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) for any suggestion for improvement so it will be triaged 

For this issue, I don't think it is a BUG. Closing this accordingly.
