### ISSUE TITLE
Enable L4 ILB Subsetting Functionality in non-Beta Provider

### ISSUE THREAD

**Issue by Jberlinsky** [hashicorp/terraform-provider-google#12986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_container_cluster` exposes the `enable_l4_ilb_subsetting` field in `terraform-provider-google-beta`, but not in `terraform-provider-google`. This functionality has been GA [since June 2021](https://cloud.google.com/kubernetes-engine/docs/release-notes#June_24_2021). IHAC that is only using `terraform-provider-google-beta` because of this field, and would like to reduce their dependency on beta capabilities.

### New or Affected Resource(s)

* `google_container_cluster`

### References

* https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1454

b/302673111

**Comment by roaks3** [comment]
It's hard to track down the change, but it looks like this field was promoted to GA at some point. However, the docs still indicate that the field is beta-only, so we should fix that to resolve completely.
