### ISSUE TITLE
google_artifact_registry_repository_iam_binding: Error 400 Invalid argument

### ISSUE THREAD

**Issue by bourdeau** [hashicorp/terraform-provider-google#12989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
Terraform v1.3.3
on linux_amd64
```

### Affected Resource(s)

* google_artifact_registry_repository_iam_binding

### Terraform Configuration Files

```tf
resource "google_artifact_registry_repository" "default" {
    count         = var.project == "prod" ? 1 : 0
    location      = "europe-west1"
    repository_id = "docker"
    description   = "Docker Registry"
    format        = "DOCKER"
}

resource "google_artifact_registry_repository_iam_binding" "cross_accounts" {
  count        = var.project == "prod" ? 1 : 0
  project      = var.project
  repository   = google_artifact_registry_repository.default[0].name
  role         = "roles/artifactregistry.reader"
  members = [
    "serviceAccount:fooi@preprod.iam.gserviceaccount.com",
    "serviceAccount:bar@preprod.iam.gserviceaccount.com"
  ]
}
```

### Debug Output

https://gist.github.com/bourdeau/e77698f7d9162309f604cb6b65cf3ae0

### Expected Behavior

The role should be applied to the service account.

### Actual Behavior

Http error 400 because of an invalid argument is returned from the Google server.

### Steps to Reproduce

1. `terraform apply`

### References

* #10184

## IDEAS

It seems the `region` is missing from url (see: #10184)

**Comment by edwardmedia** [comment]
@bourdeau can you share the debug log that contains the API requests and responses?

**Comment by bourdeau** [comment]
@edwardmedia : here it is https://gist.github.com/bourdeau/49ce1e926cc81cc8c4e4b55b7b917261

**Comment by edwardmedia** [comment]
@bourdeau it looks like you also need to provide `location` for `google_artifact_registry_repository_iam_binding` as it is required. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository_iam#location

Note for future update:
In the [code](https://github.com/hashicorp/terraform-provider-google/blob/main/google/iam_artifact_registry_repository.go#L35), it is optional. Changing it to `required` is a breaking-change. 

Same situation is applied in [google_bigquery_connection_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection_iam#location)

**Comment by bourdeau** [comment]
@edwardmedia : adding `location` fixed the problem. My bad. As `location` is a required field, shouldn't it raise an error when the value is missing? Thanks a lot for your help.

**Comment by edwardmedia** [comment]
@bourdeau I think the better way to do is to provide the `id`, not `name`. Can you try?

 repository   = google_artifact_registry_repository.default[0].id

**Comment by edwardmedia** [comment]
@bourdeau does `id` work for you?

**Comment by bourdeau** [comment]
@edwardmedia Sorry for the late reply. Yes it works with `id` instead of `name` and without `location`. I'm very new to Terraform and I probably copy/pasted it from somewhere.

**Comment by edwardmedia** [comment]
@bourdeau glad you have solved the problem. Thanks for the confirmation. Closing this now
