### ISSUE TITLE
Terraform google_cloud_scheduler_job not updating User-Agent header

### ISSUE THREAD

**Issue by sukreshmanda** [hashicorp/terraform-provider-google#12998]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.4

### Affected Resource(s)

* google_cloud_scheduler_job

### Terraform Configuration Files

```tf
resource "google_cloud_scheduler_job" "assignment_processor" {
  name             = var.assignment_processor
  description      = ""
  schedule         = "0 3 * * *"
  time_zone        = "America/New_York"
  attempt_deadline = "1800s"

  retry_config {
    retry_count = 0
    max_retry_duration = "300s"
    min_backoff_duration = "1800s"
    max_backoff_duration = "3600s"
    max_doublings = 5
  }
  http_target {
    http_method = "POST"
    uri         = var.assignment_processor_url
    headers = {
      User-Agent = "Google-Cloud-Scheduler"
    }
  }
}
```

### Debug Output

https://gist.github.com/sukreshmanda/7e6d120b1fc663d4c4e0a184b5fa9745

### Expected Behavior

After applying terraform, the User-Agent header should get updated but it is not happening, because of that next time I plan terraform it shows headers are not updated.

### Actual Behavior

In the terminal output it says the resource is updated but still the testate file is not constant with code change after applying terraform.

### Steps to Reproduce

1. `terraform apply -target="google_cloud_scheduler_job.assignment_processor"`

### References

* #0000

**Comment by mikejoseph-ah** [comment]
same issue, have you found a solution?

**Comment by megan07** [comment]
Hi @sukreshmanda , sorry for my delay in responding. I've looked into this some and I see that we're [removing the "User-Agent" header if it's set to "Google-Cloud-Scheduler"](https://github.com/GoogleCloudPlatform/magic-modules/pull/1102/files#diff-246eaa8aed883122fc09d7e78fa9e91c26ccfe1a104bfd3a29fd967153ec3b28R20).

In trying to figure out why we're doing so, it looks like [this will always automatically be set to "Google-Cloud-Scheduler"](https://cloud.google.com/scheduler/docs/reference/rest/v1beta1/projects.locations.jobs#httptarget) and that is why we remove it.

I'm not very familiar with the resource, but I think it should work if you remove that header. Please let me know if this resolves your issue or if you believe this is incorrect. Thanks!

**Comment by sukreshmanda** [comment]
Hi @megan07 , thanks for letting me know that. After removing that header everything is working fine

**Comment by megan07** [comment]
great! thanks! i'll close this then.
