### ISSUE TITLE
[Bug of Compatibility] `arg::deletion_protection` on `resource_sql_database_instance` when set to True did not update on the GCP portal

### ISSUE THREAD

**Issue by IchiruTake** [hashicorp/terraform-provider-google#12999]
I have actively enabled the field `deletion_protection` by explicitly declared this field under the resource `resource_sql_database_instance`. But when I checked on the portal, this field does not get update when creation and/or modification. 
Whilst the equivalent field when creating VM instance worked fine, this argument does not work as expected.

The following note on the Terraform document on many versions from 4.40 till 4.43 here is confusing and thus cause misunderstanding.

: On newer versions of the provider, you must explicitly set `deletion_protection=false` (and run terraform apply to write the field to state) in order to destroy an instance. It is recommended to not set this field (or set it to `true`) until you're ready to destroy the instance and its databases.

[deletion_protection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection) - (Optional) Whether or not to allow Terraform to destroy the instance. Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail. Defaults to true.

**Expectation**:
Either the `arg::deletion_protection` is explicitly declared or not (using the default), the update request must be triggered on the portal, and this change could be noticed when browsing the related SQL resource.

**Comment by edwardmedia** [comment]
dup of https://github.com/hashicorp/terraform-provider-google/issues/12642
Closing
