### ISSUE TITLE
Support max_run_duration for VM

### ISSUE THREAD

**Issue by andrewyz** [hashicorp/terraform-provider-google#13005]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_instance
* google_compute_instance_template

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_instance" "foo" {
  # ...
  scheduling {
    max_run_duration {
      nanos = 123
      seconds = 60
    }
  }
}
```

### References

* Internal issue: http://b/238940694

**Comment by logicbomb421** [comment]
I'm also looking for this to be added. Do we know when the related PR will be merged and released by chance?

**Comment by philip-harvey** [comment]
I'm curious as to why max_run_duration doesn't support the STOP action currently, is this an API issue?

**Comment by andrewyz** [comment]
STOP action is not compatible with Terraform, as GCP will wipe out the timer once it get stopped, and Terraform will lost visibility on this.

**Comment by philip-harvey** [comment]
> STOP action is not compatible with Terraform, as GCP will wipe out the timer once it get stopped, and Terraform will lost visibility on this.

I'm not following, I don't see how Terraform needs to track the run timer, only set the max run duration via the API call.  Does the API fail to return the max run duration setting when the instance is stopped?  
It seems a lot worse to have the max run duration action locked to terminate since every time you run terraform it will recreate the instance, and then GCP will delete the instance, and GCP will delete it, etc

**Comment by andrewyz** [comment]
>Does the API fail to return the max run duration setting when the instance is stopped

Yes, that is why we cannot do it in Terraform, if an instance gets stopped, and max run duration is gone, Terraform cannot understand why there is such a mismatch,  and, given the limitation that max run duration can only be updated when the instance is stopped. There isn't a feasible way to work out smoothly.

Unfortunately, given the current STOP behavior is not welcomed by Terraform, we made a hard decision to only support the termination at this point. We might consider adding STOP once we improve the API, and this being approved by Terraform in future.

**Comment by philip-harvey** [comment]
The GUI displays the max run duration even when the VM is stopped, so it seems this is an API bug.  Has an upstream issue been created?  I am happy to create one on issue tracker if needed.

**Comment by andrewyz** [comment]
This is intended behavior, but I will sync with the team shortly to see if any recent change has improved the API recently.

**Comment by rileykarson** [comment]
Closing as this was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/6812. If there's additional stuff to track after the initial change, could we spin out a new issue?

**Comment by philip-harvey** [comment]
The limitation of having the only supported action being DELETE makes this not usable for most scenarios,  max_run_duration supports STOP as an action via GUI and CLI.  Not sure this issue should be closed since the implementation doesn't yet support STOP action.  However if it needs to be closed then I'm OK with opening a new issue to add the missing support for the STOP action.

**Comment by rileykarson** [comment]
Yeah, a new issue for STOP would be useful! That'll mean that we consolidate information about STOP there, rather than have this issue serve dual purposes.

**Comment by philip-harvey** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/13671
