### ISSUE TITLE
Failing test(s): TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#13008]
Failure rate: 100% since august 12

Impacted tests:
- TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/351830?buildTab=tests&status=failed&expandedTest=44275615969714275)

Message:

```
Permission denied on Cloud KMS key. Please ensure your Artifact Registry service account has been authorized to use the configured key.
```

**Comment by AarshDhokai** [comment]
- TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample
[Google Cloud](https://ci-oss.hashicorp.engineering/test/44275615969714275?currentProjectId=GoogleCloud&branch=%3Cdefault%3E) - 100% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/44275615969714275?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure

**Comment by AarshDhokai** [comment]
b/261391751
