### ISSUE TITLE
CORS block on google_storage_bucket only allows a single policy

### ISSUE THREAD

**Issue by thclark** [hashicorp/terraform-provider-google#13000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.33.0
```

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

This works but I can only set one CORS policy:

```tf
resource "google_storage_bucket" "media_assets" {
  name                        = "${var.environment}-media-assets"
  location                    = "EU"
  force_destroy          = true
  uniform_bucket_level_access = false
  cors {
    origin = [
      "https://your-website-domain.com",
      "https://your-admin-only-tool.com",
    ]
    method = ["GET", "HEAD", "PUT"]
    response_header = ["*"]
    max_age_seconds = 3600
  }
}
```

This doesn't work because the `cors` block can't be an array (it doesn't work if you make `cors` an argument either):

```tf
resource "google_storage_bucket" "media_assets" {
  name                        = "${var.environment}-media-assets"
  location                    = "EU"
  force_destroy          = true
  uniform_bucket_level_access = false
  cors [
      {
      origin          = [
        "https://your-website-domain.com",
      ]
      method          = ["GET"]
      response_header = ["*"]
      max_age_seconds = 3600
    },
    {
      origin          = [
        "https://your-admin-only-tool.com",
      ]
      method          = ["GET", "HEAD", "PUT"]
      response_header = ["*"]
      max_age_seconds = 3600
    }
  ]
}
```
### Expected Behavior

As I understand it, it's possible to set multiple independent CORS policies on a bucket ([as indicated here, all the `cors` entries are actually arrays](https://cloud.google.com/storage/docs/configuring-cors#storage_cors_configuration-python))

### Actual Behavior

I can't set multiple CORS policies, only one at a time.

**Comment by edwardmedia** [comment]
@thclark have you tried something like below?

```tf
resource "google_storage_bucket" "media_assets" {
  name                        = "${var.environment}-media-assets"
  location                    = "EU"
  force_destroy          = true
  uniform_bucket_level_access = false
  cors {
      origin          = [
        "https://your-website-domain.com",
      ]
      method          = ["GET"]
      response_header = ["*"]
      max_age_seconds = 3600
    }
 cors {
      origin          = [
        "https://your-admin-only-tool.com",
      ]
      method          = ["GET", "HEAD", "PUT"]
      response_header = ["*"]
      max_age_seconds = 3600
    }
}
```

**Comment by edwardmedia** [comment]
@thclark closing this assuming it is no longer an issue

**Comment by thclark** [comment]
Apologies, I hadn't seen the notifications here. No, I hadn't tried that so assume that I'd not figured out how to define an array like that. Thank you!
