### ISSUE TITLE
Missing ping config for uptime checks

### ISSUE THREAD

**Issue by chrisrickenbacher** [hashicorp/terraform-provider-google#13001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_monitoring_uptime_check_config` resource doesn't support the field pingConfig for `http_check`.

### New or Affected Resource(s)

* google_monitoring_uptime_check_config

### Potential Terraform Configuration

```tf
resource "google_monitoring_uptime_check_config" "ping-check" {
  display_name = "ping-check"
  timeout      = "60s"

  http_check {
    pingConfig = {
        pingsCount = 3
    }
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      project_id = var.project
      host = var.host
    }
  }

}
```

### References

See Google documentation: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#HttpCheck

b/305278292

**Comment by jdurelli** [comment]
I will create a PR for this and some similar issues
