### ISSUE TITLE
BITBUCKET cloud build trigger source type is invalid

### ISSUE THREAD

**Issue by jordanebelanger** [hashicorp/terraform-provider-google#13003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.3

### Affected Resource(s)

google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "build-and-deploy-trigger" {
  name     = "build-and-deploy"
  project  = google_cloud_run_service.cloud_run_service.project
  location = "global"

  git_file_source {
    path      = "cloudbuild.yaml"
    uri       = "https://bitbucket.org/myorg/myrepo"
    revision  = "refs/heads/develop"
    repo_type = "BITBUCKET"
  }

  trigger_template {
    branch_name = "develop"
    repo_name   = "myorg/myrepo"
  }
}
```

### Debug Output

https://gist.github.com/jordanebelanger/5fe52f1b13c8ae7c31cf726616d34ead

### Expected Behavior

Despite this [PR](https://github.com/hashicorp/terraform-provider-google/pull/12542) which presumably add support for bitbucket source types in cloud build triggers, trying to create a cloud build trigger resource with a `BITBUCKET` source type leads to `"invalid Error 400: Invalid value at 'trigger.git_file_source.repo_type' (type.googleapis.com/google.devtools.cloudbuild.v1.GitFileSource.RepoType), "BITBUCKET"`

The [documentation also mentions `BITBUCKET` as being an acceptable git source repo type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#argument-reference)

It should be possible to create cloud build triggers connected to bitbucket repositories.

**Comment by edwardmedia** [comment]
@jordanebelanger can you share the entire debug log so I can take a close look?

**Comment by jordanebelanger** [comment]
> @jordanebelanger can you share the entire debug log so I can take a close look?

https://gist.github.com/jordanebelanger/a20fe826153d5700413a2eb217d03be1

**Comment by edwardmedia** [comment]
It appears the API has updated the accepted repoType from `BITBUCKET` to `BITBUCKET_SERVER`

https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger.RepoType
