### ISSUE TITLE
Failing test(s): TestAccGkeHubFeatureMembership_gkehubFeatureAcm

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#13022]
Failure rate: 100% since 11/7

Impacted tests:
- TestAccGkeHubFeatureMembership_gkehubFeatureAcmUpdate
- TestAccGkeHubFeatureMembership_gkehubFeatureAcmAllFields

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/351878?buildTab=tests&status=failed&pager.currentPage=1&expandedTest=838033674041769552)

Message:

```
InvalidValueError for field configSync.git.secretType: illegal secretType  for Membership projects/733915491679/locations/global/memberships/tf-test10gyssa6mbi. Valid types are: [ssh cookiefile gcenode gcpserviceaccount token none]
```

**Comment by AarshDhokai** [comment]
- TestAccGkeHubFeatureMembership_gkehubFeatureAcmAllFields
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/-1250544568553697677?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure 

- TestAccGkeHubFeatureMembership_gkehubFeatureAcmUpdate
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/test/838033674041769552?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E) - 100% failure

**Comment by AarshDhokai** [comment]
b/261390522
