### ISSUE TITLE
missing Partial State; API timeout leave partially build environment, subsequent pipelines require destory before new apply

### ISSUE THREAD

**Issue by codeangler** [hashicorp/terraform-provider-google#13035]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.x

### Affected Resource(s)

Terraform provider.  Various resources fail.

* 4.x

### 

Our pain with the google provider is [partial state](https://www.hashicorp.com/blog/writing-custom-terraform-providers) in pipelines when we have a timeout waiting on API response. The result is rerunning the pipeline, which must destroy the previously deployed resources compounding the delay in new environment creation.

### Expected Behavior

I wonder if the google provider is implementing

 >   Partial mode is a mode that can be enabled by a callback that tells Terraform that it is possible for partial state to occur. When this mode is enabled, the provider must explicitly tell Terraform what is safe to persist and what is not. [docs](https://www.hashicorp.com/blog/writing-custom-terraform-providers)

### Actual Behavior

subsequent Terraform Apply needs to first destroy prior to completing a new apply

### Steps to Reproduce

random; based on timeouts with google API

### References

- https://github.com/hashicorp/terraform-provider-google/issues/10065#issuecomment-1312178123

**Comment by codeangler** [comment]
> I wonder if the google provider is implementing partial mode

We used to use partial mode and probably do in some places, but have since stopped using it. It was discovered by the SDK Lead at HashiCorp that it effectively didn't work, unfortunately! There was a period of time and set of assumptions where/when it did, but that's no longer generally true. That's reflected by partial not appearing in the successor to that guide, https://developer.hashicorp.com/terraform/tutorials/providers/provider-update, and the SDK function being [informally deprecated](https://github.com/hashicorp/terraform-plugin-sdk/blob/ac0b9654b5217af313c746f205b98f3278e3f20b/helper/schema/resource_data.go#L187-L200).

> Our pain with google provider is [partial state](https://www.hashicorp.com/blog/writing-custom-terraform-providers) in pipelines when we have a timeout waiting on API response.

That's a different issue than this covers, please do!

_Originally posted by @rileykarson in https://github.com/hashicorp/terraform-provider-google/issues/10065#issuecomment-1312178123_

**Comment by edwardmedia** [comment]
@codeangler do you have terraform config that can repro the issue?

**Comment by edwardmedia** [comment]
@codeangler is this still an issue?

**Comment by edwardmedia** [comment]
@codeangler closing this assuming it is no longer an issue
