### ISSUE TITLE
setting Backend Service security policy: googleapi: Error 400: The resource 'projects/data-mdm-sandbox/global/backendServices/san2-testing-dbt-docs-backend-service' is not ready,

### ISSUE THREAD

**Issue by sreenivas-ps** [hashicorp/terraform-provider-google#13033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/google v4.43.0
+ provider registry.terraform.io/hashicorp/google-beta v4.43.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

* google_compute_backend_service

### Terraform Configuration Files

```tf
resource "google_compute_backend_service" "backend_service_dbt_docs" {
  for_each = var.environments

  name        = "${var.deployment}-${each.value.name}-dbt-docs-backend-service"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 30

  load_balancing_scheme = "EXTERNAL"

  health_checks = [
    google_compute_health_check.dbt_docs.id
  ]

  iap {
    oauth2_client_id     = google_iap_client.project_client.client_id
    oauth2_client_secret = google_iap_client.project_client.secret
  }

  log_config {
    enable = true
  }

  lifecycle {
    ignore_changes = [
      backend
    ]
  }

  security_policy = var.security_policy
}
```

### Expected Behavior
the backend service should have been created attaching the passed security policy

### Actual Behavior
I think the security policy was being attached while the backend service was still in creation

```
╷
│ Error: Error setting Backend Service security policy: googleapi: Error 400: The resource 'projects/data-mdm-sandbox/global/backendServices/san2-testing-dbt-docs-backend-service' is not ready, resourceNotReady
│
│   with module.dataplatform_transformation.google_compute_backend_service.backend_service_dbt_docs["testing"],
│   on ../../modules/data-platform-transformation/lb.tf line 191, in resource "google_compute_backend_service" "backend_service_dbt_docs":
│  191: resource "google_compute_backend_service" "backend_service_dbt_docs" {
```

### Steps to Reproduce
- create a security policy which is already created.
- now create a new backend service, and then pass the security policy created in the previous step
- should be able to reproduce the error.

1. `terraform apply`

### References

* #0000

**Comment by sreenivas-ps** [comment]
[debug.log](https://github.com/hashicorp/terraform-provider-google/files/10012865/debug.log)

**Comment by sreenivas-ps** [comment]
@edwardmedia please find the attached log ^

**Comment by sreenivas-ps** [comment]
@edwardmedia : for testing, i tried not using the security policy but then it blown up at the url_map

```
╷
│ Error: Error creating UrlMap: googleapi: Error 400: The resource 'projects/data-mdm-sandbox/global/backendServices/san2-billing-backend-service' is not ready, resourceNotReady
│
│   with module.dataplatform_transformation.google_compute_url_map.url_map,
│   on ../../modules/data-platform-transformation/lb.tf line 76, in resource "google_compute_url_map" "url_map":
│   76: resource "google_compute_url_map" "url_map" {
```

**Comment by sreenivas-ps** [comment]
here is the cloud armor `google_compute_security_policy` resource which is created in root module; as i mentioned this resource is already created, so I am passing its selflink to the module where the `google_compute_backend_service` is being created. I've removed the actual IPs from below...

```
resource "google_compute_security_policy" "policy" {
  name = "${var.environment}-mdm-policy"

  rule {
    action   = "allow"
    priority = "900"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["xx.xx.xx.xx/32"]
      }
    }
  }

  rule {
    action   = "allow"
    priority = "910"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["yy.yy.yy.yy/32"]
      }
    }
  }

  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "default rule"
  }

  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable = true
    }
  }
}
```
are you suggesting I should use `time_sleep` to wait for the resource creation? should I add this in the `google_compute_backend_service` as the `google_compute_security_policy` resource is already at that point?

**Comment by edwardmedia** [comment]
@sreenivas-ps yes

**Comment by sreenivas-ps** [comment]
@edwardmedia I'm not sure how I can wait or delay once it has started the creating the resource, since within the same api call it is trying to attach the policy. I tried with null_resource with local-exec but didn't work.  I tried something like this but it never came to null_resource execution and still the errored; I believe it is not right what i am doing here. can you suggest how can i use the sleep here?

`
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 15"
  }
  triggers = {
    "before" = concat(
      [for i in google_compute_backend_service.backend_service: i.id],
      [for i in google_compute_backend_service.backend_service_dbt_docs: i.id]
    )
  }
}

resource "null_resource" "after" {
  depends_on = [
    null_resource.delay
  ]
}
`

**Comment by edwardmedia** [comment]
@sreenivas-ps let's halt adding sleep logic. I reviewed your debug log again, and did not find below `backendServices` being created. Is it supposed to be created by the code [here](https://github.com/hashicorp/terraform-provider-google/issues/13033#issue-1448613815)? You said it is already created? Can you share the result by running `terraform show`?

projects/data-mdm-sandbox/global/backendServices/san2-testing-dbt-docs-backend-service

**Comment by sreenivas-ps** [comment]
@edwardmedia : I said the resource `google_compute_security_policy` (cloud armor policy) was already created and the `google_compute_backend_service` uses it. Yes, the backend service should be created as I mentioned the resource here [here](https://github.com/hashicorp/terraform-provider-google/issues/13033#issue-1448613815)

**Comment by edwardmedia** [comment]
@sreenivas-ps can you confirm `google_compute_backend_service` was created and the `security_policy` was successfully attached even you see this error at the end?

**Comment by sreenivas-ps** [comment]
@edwardmedia I didn't check the backend service if the `security_policy` was applied when this error occurred. I will have to create this issue and then check it.

**Comment by edwardmedia** [comment]
@sreenivas-ps can you confirm google_compute_backend_service was created and the security_policy was successfully attached even you see this error at the end?

**Comment by edwardmedia** [comment]
@sreenivas-ps is this still an issue?

**Comment by sreenivas-ps** [comment]
I've tried to reproduce this with one backend service and was working; i've a list of backend services that get created and attaching the existing security policy to those is when I saw the issue. Also when i append a new backend service to list for the creation, I noticed this behaviour.

**Comment by edwardmedia** [comment]
@sreenivas-ps I am not sure what went wrong. Things I could think of are using **existing** resources. I encourage you to check if those references to the existing resources are correct.

Based on the result of [example](https://github.com/hashicorp/terraform-provider-google/issues/13033#issuecomment-1332767454) and testing you tried to repro, I think the provider works as expected. I am going to close this. Feel free to reopen if you see it differently.
