### ISSUE TITLE
Autoclass for Storage Bucket

### ISSUE THREAD

**Issue by thegrew** [hashicorp/terraform-provider-google#13044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a new autoclass feature for GCS buckets as per: https://cloud.google.com/storage/docs/autoclass and https://cloud.google.com/storage/docs/json_api/v1/buckets that I believe should be added to the bucket resource and data sources.

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "example" {
  name          = "example"
  location      = "US"
  autoclass     = true
}
```

### References

https://cloud.google.com/storage/docs/autoclass and https://cloud.google.com/storage/docs/json_api/v1/buckets

* #0000

**Comment by shuyama1** [comment]
@googlerjk Sorry if you've already started working on this. https://github.com/GoogleCloudPlatform/magic-modules/pull/6870 has the work that will close this issue. I'm assigning you from the issue.
