### ISSUE TITLE
Magician doesn't display link to individual test results on timeout.

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13057]
### Affected Resource(s)

* google_*

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Expected Behavior

On a timeout the individual test runs should still be linked from the PR.

### Actual Behavior

Only a link to the build log was linked from the PR.
See https://github.com/GoogleCloudPlatform/magic-modules/pull/6728#issuecomment-1317687771 for details.

**Comment by rileykarson** [comment]
We aren't sure if this is still an issue, and the code has been rewritten since this was filed.
