### ISSUE TITLE
Terraform import error: no schema available for google_logging_log_sink

### ISSUE THREAD

**Issue by nkukka** [hashicorp/terraform-provider-google#13061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.43.1
+ provider registry.terraform.io/hashicorp/google-beta v4.43.1

### Affected Resource(s)

* google_logging_log_sink

### Terraform Configuration Files

none

### Debug Output

```
$ terraform import google_compute_instance.<TF_NAME> projects/<PROJECT>/zones/<ZONE>/instances/<NAME>      
google_compute_instance.xxxxxxxxx: Importing from ID "projects/xxxxxxxxx/zones/xxxxxxxxx/instances/xxxxxxxxx"...
google_compute_instance.xxxxxxxxx: Import prepared!
  Prepared google_compute_instance for import
google_compute_instance.xxxxxxxxx: Refreshing state... [id=projects/xxxxxxxxx/zones/xxxxxxxxx/instances/xxxxxxxxx]
╷
│ Error: no schema available for google_logging_log_sink.xxxxxxxxx_sink to validate for self-references; this is a bug in Terraform and should be reported
│ 
│ 
╵
```

### Panic Output

n/a

### Expected Behavior

The resource should have been imported along with the google_logging_log_sink reference

### Actual Behavior

No schema available.

### Steps to Reproduce

Import any gcp resource with a log sink.

`terraform import google_compute_instance.<TF_NAME> projects/<PROJECT>/zones/<ZONE>/instances/<NAME>`

### Important Factoids

Authenticating as a user

### References

n/a

**Comment by edwardmedia** [comment]
@nkukka which resource do you want to import? `google_compute_instance`, `google_logging_log_sink`? Can you share your config used for your import?

**Comment by courtsimas** [comment]
Same issue.

**Comment by courtsimas** [comment]
the .tf file in question:
```
resource "google_logging_log_sink" "a_required" {
  destination            = "logging.googleapis.com/projects/<our project id>/locations/global/buckets/_Required"
  filter                 = "LOG_ID(\"cloudaudit.googleapis.com/activity\") OR LOG_ID(\"externalaudit.googleapis.com/activity\") OR LOG_ID(\"cloudaudit.googleapis.com/system_event\") OR LOG_ID(\"externalaudit.googleapis.com/system_event\") OR LOG_ID(\"cloudaudit.googleapis.com/access_transparency\") OR LOG_ID(\"externalaudit.googleapis.com/access_transparency\")"
  name                   = "_Required"
  project                = "<project number>"
  unique_writer_identity = true
}
# terraform import google_logging_log_sink.a_required <our project number>###_Required
```

running `terraform import module.terraform-<project number-Project-LoggingLogSink.google_logging_log_sink.a_required <project number>###_Required` spits out:

`│ Error: unknown resource type: google_logging_log_sink`

If we run the main project import command which is one line up in the script file, it's `terraform import module.terraform-<id>-Project.google_project.<project id> projects/<project id>` and it spits out:

```
module.terraform-<id>-Project.google_project.<project id>: Importing from ID "projects/<project id>"...
module.terraform-<id>-Project.google_project.<project id>: Import prepared!
  Prepared google_project for import
module.terraform-<id>-Project.google_project.<project id>: Refreshing state... [id=projects/<project id>]
╷
│ Error: no schema available for google_logging_log_sink.a_required to validate for self-references; this is a bug in Terraform and should be reported
│ 
│ 
╵
```

**Comment by edwardmedia** [comment]
@courtsimas @nkukka can you provide the link to the document of `google_logging_log_sink`?

**Comment by nkukka** [comment]
> @courtsimas @nkukka can you provide the link to the document of `google_logging_log_sink`?
This is generated by gcp bulk-export
```
resource "google_logging_log_sink" "xxxxxxxx_sink" {
  destination            = "logging.googleapis.com/projects/xxxxxxxx/locations/global/buckets/xxxxxxxx"
  filter                 = "resource.labels.instance_id=\"xxxxxxxx\""
  name                   = "xxxxxxxx-sink"
  project                = "xxxxxxxx"
  unique_writer_identity = true
}
# terraform import google_logging_log_sink.bard_beta_sink 286148226702###xxxxxxxx-sink
```
There however are no docs for these types of resources online, and the error applies to all of my GCP resources I try to import from the same project, for example the following compute instance:

```
resource "google_compute_instance" "xxxxxxxx" {
  boot_disk {
    auto_delete = false
    device_name = "xxxxxxxx"

    initialize_params {
      image = "https://www.googleapis.com/compute/beta/projects/xxxxxxxx/global/images/xxxxxxxx"

      labels = {
        state       = "active"
        team        = "xxxxxxxx"
        environment = "xxxxxxxx"
        component   = "xxxxxxxx"
      }

      size = 50
      type = "pd-balanced"
    }

    mode   = "READ_WRITE"
    source = "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/europe-north1-b/disks/xxxxxxxx"
  }

  deletion_protection = true

  labels = {
    team        = "xxxxxxxx"
    state       = "active"
    environment = "xxxxxxxx"
    component   = "xxxxxxxx"
  }

  machine_type = "e2-standard-2"

  metadata = {
    enable-oslogin = "TRUE"
  }

  name = "xxxxxxxx"

  network_interface {
    network            = "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/services"
    network_ip         = "10.240.15.202"
    stack_type         = "IPV4_ONLY"
    subnetwork         = "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/europe-north1/subnetworks/xxxxxxxx"
    subnetwork_project = "xxxxxxxx"
  }

  project = "xxxxxxxx"

  reservation_affinity {
    type = "ANY_RESERVATION"
  }

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
    provisioning_model  = "STANDARD"
  }

  service_account {
    email  = "xxxxxxxx@xxxxxxxx.iam.gserviceaccount.com"
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = true
    enable_vtpm                 = true
  }

  tags = ["https-server", "ssh-server"]
  zone = "europe-north1-b"
}
# terraform import google_compute_instance.xxxxxxxx projects/xxxxxxxx/zones/europe-north1-b/instances/xxxxxxxx
```

All in all, doesn't `terraform import` just write things to state that it reads from the cloud provider API? The configs or the lack thereof shouldn't matter in this case. But of course, correct me if I'm wrong.

The only online discussion I've found about these "resources" is the following: https://stackoverflow.com/questions/72445305/gcloud-terraform-export-unknown-resource-type-google-logging-log-sink

The comments suggest a workaround, but don't describe it. I however feel the suggestion doesn't work in case objects in the google cloud backend refer to these not-in-schema -type objects.

**Comment by edwardmedia** [comment]
@nkukka sorry I am still not clear which provider supports `google_logging_log_sink`. Without the document, I am not sure how I can help.

**Comment by nkukka** [comment]
@edwardmedia shouldn't google or at least google-beta support it?

It seems to be an integral part of GCP, to the extent where `terraform import` tries to import such resources as direct child/sibling resources for the bread and butter google_compute_instance.

**Comment by nkukka** [comment]
To reiterate, the problem is that the GCP API seems to be telling terraform that "okay you need this type of a resource which you should know how to handle" and the provider then tells terraform that it doesn't understand what that resource is.

**Comment by edwardmedia** [comment]
@nkukka by this moment, I don't think google and google-beta support it. What endpoint of GCP API? How did you get `okay you need this type of a resource which you should know how to handle`? Can you share any related document.  

google_logging_organization_sink
google_logging_folder_sink
google_logging_project_sink
google_logging_billing_account_sink
google_logging_log_view

Above are the resources that are built in the provider.  Still I have no clue what you are talking about

**Comment by nkukka** [comment]
@edwardmedia whichever api endpoint is used by terraform to do operations to perform CRUD on GCP resources, I don't know.

The part you quoted on me was not explicit terraform output, but only me putting the case into laymens terms.

I do not have a document for the said resource, the only way I have come across it, is the error message regarding not having a schema for it, printed out by the terraform import command.

**Comment by nkukka** [comment]
I am now unable to reproduce this problem. The provider and terraform versions are the same as before.

Maybe GCP fixed something on their end?

**Comment by edwardmedia** [comment]
@nkukka not sure what went wrong. Closing this issue now. Feel free to reopen if this comes back. Thanks
