### ISSUE TITLE
Apigee X Target Server & KVM Resources

### ISSUE THREAD

**Issue by lewis-strong** [hashicorp/terraform-provider-google#13074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Apigee X has features such as Target Servers & Key Value Maps which are not currently supported within Terraform

Adding the ability to configure these resources via IAC would be appreciated and allow outputs from other resources such as Endpoint Attachments to be referenced and used to configure Target Servers or Key Value Maps for Proxy consumption

### New or Affected Resource(s)

* google_apigee_target_server
* google_apigee_kvm

### Potential Terraform Configuration

```tf
resource "google_apigee_target_server" "target_server" {
  org_id                 = google_apigee_organization.apigee_org.id
  environment            = google_apigee_environment.environment.id
  name                   = "name"
  host                   = google_apigee_endpoint_attachment.endpoint.host
  port                   = 80
  enabled                = true
}
```

### References

@danistrebel

Unsupported community module regarding this functionality: https://registry.terraform.io/providers/scastria/apigee/latest/docs/resources/target_server

**Comment by riccardosalamanna** [comment]
I would really like to see this implemented 👍

**Comment by melinath** [comment]
b/270217608

**Comment by rs1986x** [comment]
@lewis-strong https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_target_server 😄
