### ISSUE TITLE
Service Directory Endpoint's Network Defaulting to Global

### ISSUE THREAD

**Issue by BolajiAkerele2013** [hashicorp/terraform-provider-google#13076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.6

### Affected Resource(s)

* google_service_directory_endpoint

### Terraform Configuration Files

```tf
resource "google_service_directory_namespace" "example" {
  provider     = google-beta
  namespace_id = "example-namespace"
  location     = "us-central1"
  project = "test-project"
}

resource "google_service_directory_service" "example" {
  provider   = google-beta
  service_id = "example-service"
  namespace  = google_service_directory_namespace.example.id
}

resource "google_service_directory_endpoint" "example" {
  provider    = google-beta
  endpoint_id = "example-endpoint"
  service     = google_service_directory_service.example.id

  metadata = {
    stage  = "prod"
    region = "us-central1"
  }

  address = "1.2.3.4"
  port    = 5353
  network = "projects/*************/locations/europe-west2/networks/test"
}
```

### Expected Behavior

Create the Service Directory Endpoint with Network as stated in the configuration (pointing to the region location)

### Actual Behavior
Terraform creates the Endpoint and defaults the location to global so everytime I run terraform plan / apply, I prompts to replace the network.
This happens everytime I run Terraform plan/apply even after I have applied it multiple times.

```tf
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_service_directory_endpoint.example must be replaced
-/+ resource "google_service_directory_endpoint" "example" {
      ~ id          = "projects/test-project/locations/us-central1/namespaces/example-namespace/services/example-service/endpoints/example-endpoint" -> (known after apply)
      ~ name        = "projects/test-project/locations/us-central1/namespaces/example-namespace/services/example-service/endpoints/example-endpoint" -> (known after apply)
      ~ network     = "projects/*************/locations/global/networks/test" -> "projects/*************/locations/europe-west2/networks/test" # forces replacement
        # (5 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@BolajiAkerele2013 I think below setting is invalid based on the api [doc](https://cloud.google.com/service-directory/docs/reference/rest/v1beta1/projects.locations.namespaces.services.endpoints)

```
network = "projects/*************/locations/europe-west2/networks/test"
```

`network | stringImmutable. The Google Compute Engine network (VPC) of the endpoint in the format projects/<project number>/locations/global/networks/*.`

**Comment by BolajiAkerele2013** [comment]
Thanks for the noted @edwardmedia. This addresses the problem. 
Since the VPC network is  global resource, the location should be global.
