### ISSUE TITLE
Vertex AI Endpoint deploy failure

### ISSUE THREAD

**Issue by MarcoCQin** [hashicorp/terraform-provider-google#13072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v4.43.1

### Affected Resource(s)

* google_vertex_ai_endpoint

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_vertex_ai_endpoint" "main" {
  name         = "1"
  display_name = "sample-endpoint"
  description  = "A sample Vertex AI endpoint"
  location     = "europe-west4"
}

```

### Expected Behavior

 A Vertex AI Endpoint should have been created in the europe-west4 location.

### Actual Behavior

 This html output file was generated 
![image](https://user-images.githubusercontent.com/54717305/202685149-c88107c1-3ef7-4b35-8108-57cc52585b49.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

 I am trying to deploy this resource using Cloud Build, but the service account which manages this process has Vertex AI Admin permissions and it managed to deploy other resources in the same GCP project.

### References

* #0000

**Comment by edwardmedia** [comment]
closing as dup of https://github.com/hashicorp/terraform-provider-google/issues/12944
