### ISSUE TITLE
Google Router Nat Subnet Attachment Resource

### ISSUE THREAD

**Issue by markeverettbeck** [hashicorp/terraform-provider-google#13085]
Issue: I am creating a new subnet for the vpc access connector, but there is no resource to simply add the subnet to the nat router when "LIST_OF_SUBNETWORKS" is used.

The Ask: Create a new resource to attach subnets to router nat.

**Comment by edwardmedia** [comment]
@markeverettbeck have you had chance to review the example [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector#example-usage---vpc-access-connector-shared-vpc) to see if that can address your question?

**Comment by edwardmedia** [comment]
@markeverettbeck is this still an question?

**Comment by edwardmedia** [comment]
@markeverettbeck closing this assume it is no longer a question
