### ISSUE TITLE
google_certificate_manager_certificate - introduce locality argument

### ISSUE THREAD

**Issue by cherusk** [hashicorp/terraform-provider-google#13090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resource google_certificate_manager_certificate currently does not allow to specify locality, leading to those certificates to always be global.

### New or Affected Resource(s)

* google_certificate_manager_certificate

That affects Secure Web Gateway(alpha, Pre-GA) resource, relying regional certificate manager certificates. No TF resource in place for that resource yet though.

**Comment by rileykarson** [comment]
Marking as `size/m` as adding new localities to existing resources has proven difficult

**Comment by roaks3** [comment]
I want to make sure I understand the request, but I believe this was fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7825. @felipegc could you confirm?

**Comment by rileykarson** [comment]
I think https://github.com/GoogleCloudPlatform/magic-modules/pull/7825 was just missing the magic word (`Fixes:`), this does seem closeable.

**Comment by felipegc** [comment]
> I want to make sure I understand the request, but I believe this was fixed by [GoogleCloudPlatform/magic-modules#7825](https://github.com/GoogleCloudPlatform/magic-modules/pull/7825). @felipegc could you confirm?

Yeap. It is closed. I didn’t know about the “trick” of adding “fixed:” word in front of the link.

**Comment by rileykarson** [comment]
There's a handful of keywords! `Fixes` is the most common one, generally: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
