### ISSUE TITLE
Terraform script failing when removing ability to act as root inside of image being provisioned

### ISSUE THREAD

**Issue by paper-michael** [hashicorp/terraform-provider-google#13091]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
latest

### Affected Resource(s)

* google_app_engine_flexible_app_version

### Debug Output
On Terragrunt apply
```
╷

│ Error: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 9, message: An internal error occurred while processing task /app-engine-flex/flex_await_healthy/flex_await_healthy>2022-11-07T19:19:23.101Z6483.fn.2: + /bin/bash /build-scripts/move-config-files.sh

│ Moving user supplied config files...

│ chgrp: changing group of '/etc/nginx/conf.d/nginx-app.conf': Operation not permitted

│ 

│ 

│   with google_app_engine_flexible_app_version.web,

│   on main.tf line 81, in resource "google_app_engine_flexible_app_version" "web":

│   81: resource "google_app_engine_flexible_app_version" "web" {

│ 

╵

time=2022-11-07T19:20:52Z level=error msg=Module [PATH/TO/TERRAGRUNT/MODULE] has finished with an error: 1 error occurred:

	* exit status 1
``` 

### Expected Behavior

Terraform should have completed the apply normally

### Actual Behavior

The bug above occured

### Steps to Reproduce

Difficult to say as I am sure this is contingent on some private/internal setup that I cannot share.

### Important Factoids

- I know this bug ticket is missing important info. I'm creating this ticket because I'm looking for information/context/background about the specific error message I'm getting, and any possible workarounds.
- This issue started during efforts to get rid of access to the root user inside of the containers for our services. The only accessible user inside the built image attempting to be deployed from the terraform script in question has limited access/permissions/privileges.
- The script is being run with Terragrunt
### References

-  Here is a link to a slack message I sent on the google cloud platform community slack channel, with no response: https://googlecloud-community.slack.com/archives/C1VNJ4EG7/p1668533609398569 which is part of why I'm (somewhat inappropriately) asking here
- The slack channel linked in the template for "question" issues is deprecated

**Comment by edwardmedia** [comment]
@edwardmedia it is hard to guess without the details. I am not sure what you mean below? Can you share the debug log what contains the related api requests and responses? Also please share your config

```
get rid of access to the root user inside of the containers for our services
```

**Comment by paper-michael** [comment]
This is the change in our dockerfile that was added. It's a laravel app
```
# Add custom group and user
RUN addgroup --system customgroup  \
    && adduser --system --ingroup customgroup customuser

RUN chown -R customuser:customgroup /run
RUN chown -R customuser:customgroup /app
RUN chown -R customuser:customgroup /usr/bin
RUN chown -R customuser:customgroup /var
RUN chown -R customuser:customgroup /etc/nginx
RUN chown customuser:customgroup nginx-app.conf
RUN chmod -R 777 /etc/nginx


# Disable root login
RUN passwd -l root
RUN usermod -s /usr/sbin/nologin root

# Login using custom user
USER customuser
```

**Comment by edwardmedia** [comment]
@paper-michael I am not sure how I can help here.  Were you able to deploy before the change? It looks like the issue happens after you modified the permissions. From the provider's perspective, as long as the terraform runner has right permissions, it should work. Your log reveals little about the error that is directly related to the provider.

**Comment by edwardmedia** [comment]
@paper-michael is this still an issue?

**Comment by edwardmedia** [comment]
@paper-michael  closing this assuming it is no longer an issue

**Comment by paper-michael** [comment]
yes, the issue ended up being unrelated to Terraform.
