### ISSUE TITLE
Error when applying retention policy in Apigee X Organization

### ISSUE THREAD

**Issue by entertvl** [hashicorp/terraform-provider-google#13099]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.43.1
```

### Affected Resource(s)

* google_apigee_organization

### Terraform Configuration Files

```tf
resource "google_apigee_organization" "main" {
  project_id         = "example-project"
  display_name       = "display-org-name"
  analytics_region   = "asia-northeast1"
  authorized_network = data.google_compute_network.network.id
  retention          = "DELETION_RETENTION_UNSPECIFIED"

  runtime_database_encryption_key_name = data.google_kms_crypto_key.runtime.id
}
```

### Debug Output

https://gist.github.com/entertvl/2de15b7371022b46b578ce70977b052c

### Expected Behavior

No error occured.

### Actual Behavior

Failed to update Organization (retry error).
After that, I tried terraform apply again, and it printed "No Changes".

### Steps to Reproduce

1. Deployed in the past Apigee X Organization without defined retention policy (e.g. using v4.33.0 or earlier providers)
2. Define a policy and apply

### Important Factoids

This error can occur in Apigee X Organization built by terraform before https://github.com/hashicorp/terraform-provider-google/pull/12336.

Retention policy is specified at the time of deletion of the Apigee X Organization,
I think the retry when terraform apply is because it is calling the API.
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations/delete?hl=ja

### References

* https://github.com/hashicorp/terraform-provider-google/pull/12336
* https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.34.0

**Comment by edwardmedia** [comment]
@entertvl are you able to enable TF_LOG=DEBUG and then share the debug log?

I am having trouble repro the issue 

b/260337744

**Comment by melinath** [comment]
b/270217748

**Comment by entertvl** [comment]
@edwardmedia 
Sorry for the late response.
I wasn't able to reproduce the issue on my end and cannot share the debugging logs.
I'll let you know if it happens again.
