### ISSUE TITLE
google_dataproc_job - How to define "id" or "name"?

### ISSUE THREAD

**Issue by davorceman** [hashicorp/terraform-provider-google#13095]
If I create job via GCP console, I can define job id I want.
But I don't see how to set it via terraform.
Am I missing something?

**Comment by edwardmedia** [comment]
@davorceman is this field you are looking for? 

[name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job#name) - (Required) A unique name for the resource, required by Dataflow.

**Comment by edwardmedia** [comment]
@davorceman closing this assuming it is no longer a question

**Comment by davorceman** [comment]
> @davorceman is this field you are looking for?
> 
> [name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job#name) - (Required) A unique name for the resource, required by Dataflow.

I'm asking for Dataproc, not Dataflow service
