### ISSUE TITLE
Add TCP TIME_WAIT to google_compute_router_nat

### ISSUE THREAD

**Issue by sh4sh** [hashicorp/terraform-provider-google#13094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Is it possible to add configurable TCP TIME_WAIT to Cloud NAT? This request has previously been tracked in https://github.com/hashicorp/terraform-provider-google/issues/10666 and its associated PRs, but it was reverted due to a conflict. As far as I can tell it did not get implemented.

https://github.com/hashicorp/terraform-provider-google/issues/10666#issuecomment-1173598610 by @black-snow explains well:
>I just stumbled over this. Why do we have all the options (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#tcp_established_idle_timeout_sec) except for the TCP wait time? :D
>
>Should be this: https://cloud.google.com/sdk/gcloud/reference/compute/routers/nats/create?hl=de#--tcp-time-wait-timeout
>
>The PR should look a lot like https://github.com/GoogleCloudPlatform/magic-modules/commit/09bc35cba420037a0578884a2e3abf32ca3ac7e8, I guess. But I have zip go knowledge :/

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
resource "google_compute_router_nat" "foobar" {
  name                               = "%s"
  router                             = google_compute_router.foobar.name
  region                             = google_compute_router.foobar.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
  tcp_time_wait_timeout_sec          = "%d"
}
```

### References

* Original issue: https://github.com/hashicorp/terraform-provider-google/issues/10666
* PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/6221
* Revert: https://github.com/GoogleCloudPlatform/magic-modules/pull/6343

**Comment by yudoufu** [comment]
I'll take this issue.
