### ISSUE TITLE
google_cloud_storage dual region buckets are not properly located in TF statefile.

### ISSUE THREAD

**Issue by CMDennis** [hashicorp/terraform-provider-google#13116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.1 on darwin_amd64
### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```
resource "google_storage_bucket" "dual_region_test" {
  force_destroy               = true
  location                    = "US-EAST4+US-CENTRAL1"
  name                        = "randomly-named-dual-region-bucket"
  project                     = "any_project"
  public_access_prevention    = "inherited"
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
}
```

### Debug Output
Terraform Plan (no resources)
https://gist.github.com/CMDennis/b5fc19c2a92d8223f3eff349288512da
Terraform Apply
https://gist.github.com/CMDennis/806ecc093c8f373cf77b435553ba625b
Terraform Plan (after apply should be a no op)
https://gist.github.com/CMDennis/54c9845f4669c5cac7d006d2fc1c1cd2
Terraform Statefile 
https://gist.github.com/CMDennis/6c63c125c1c840d86264618cb58d2beb
### Panic Output

No panics occur

### Expected Behavior

A bucket should be created in the desired dual regions, and the Terraform statefile should reflect this.

### Actual Behavior

The bucket is created in the correct dual region location. But the state file records the location as `location:US` instead of `location:REGION1+REGION2`

### Steps to Reproduce
1. Create configs for dual region bucket using format "REGION1+REGION2" (in my case US-EAST4+US-CENTRAL1) see config file snippet
2. terraform plan
3. terraform apply
4. terraform plan again 

### Important Factoids
1. The statefile indicates the location is the "multi-regional" US location but the bucket is created in the correct dual region configuration:
<img width="1628" alt="Screenshot 2022-11-23 at 11 47 33 AM" src="https://user-images.githubusercontent.com/27302065/203602622-ab24bba6-2ec1-4985-b9a6-5ee8e74138b1.png">
2. The NAM4 dual region prefix works as expected (but doesn't cover the regions I want to use)
### References

* #NA

**Comment by edwardmedia** [comment]
@CMDennis when you send the api with `location = "US-EAST4+US-CENTRAL1"`, the api treats it as `US`, and populates data in the field `custom_placement_config`. This is all done at the API and there is little we can do at the provider level. For the specific multiple regions, can you use below config instead?

```
resource "google_storage_bucket" "dual_region_test" {
  force_destroy               = true
  location                    = "US"
  name                        = "randomly-named-dual-region-bucket"
  project                     = "any_project"
  public_access_prevention    = "inherited"
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  custom_placement_config {
    data_locations = ["US-CENTRAL1","US-EAST4"]
  }
}
```

**Comment by CMDennis** [comment]
Ahh that resolves it....very strange that the API just quietly treats that location as "US" without throwing an error.

**Comment by edwardmedia** [comment]
@CMDennis that is all done at the api. Glad the suggestion works for you. Closing this now
