### ISSUE TITLE
google_container_cluster says 172 based cluster_ipv4_cidr is invalid.

### ISSUE THREAD

**Issue by mihok** [hashicorp/terraform-provider-google#13110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.2
on darwin_arm64
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

Note this comes from a autogenerated json file (`cdk.tf.json`) so if this is an issue with cdktf let me know and I'll open an issue there.

```json
"google_container_cluster": {
      "app-internal-logging-cluster-k8s": {
        "//": {
          "metadata": {
            "path": "app/app-internal-logging-cluster-k8s",
            "uniqueId": "app-internal-logging-cluster-k8s"
          }
        },
        "cluster_ipv4_cidr": "172.104.0.0/14",
        "location": "us-central1",
        "name": "app-internal-logging-cluster",
        "network": "${google_compute_network.app-internal-logging-vpc-network.id}",
        "networking_mode": "ROUTES",
        "node_pool": [
          {
            "name": "app-internal-logging-cluster-pool",
            "node_count": 1
          }
        ],
        "project": "app-commerce",
        "subnetwork": "${google_compute_subnetwork.app-internal-logging-vpc-subnet-us-central1.id}"
      }
    }
```

### Debug Output

https://gist.github.com/mihok/f207687afe502227b908544511c2acfc

### Expected Behavior

Running the same code but with `10.104.0.0/14` works, so the expected behavior is having the validation not fail on a `172/8` CIDR.

### Actual Behavior

Suggests that its not a valid CIDR.

```
         │ Error: expected "cluster_ipv4_cidr" to be an RFC1918-compliant CIDR, got: 172.104.0.0/14
          │ 
          │   with google_container_cluster.app-internal-logging-cluster-k8s (app-internal-logging-cluster-k8s),
          │   on cdk.tf.json line 53, in resource.google_container_cluster.app-internal-logging-cluster-k8s (app-internal-logging-cluster-k8s):
          │   53:         "cluster_ipv4_cidr": "172.104.0.0/14",
          │ 
          ╵

```

### Steps to Reproduce

1. Use `google_container_cluster` that has a property `custer_ipv4_cidr` with an `172...` CIDR range.
2. `terraform apply`

### Important Factoids

I ran into this issue while using CDKTF and the generated google provider modules

**Comment by edwardmedia** [comment]
@mihok can you share the debug log that contains api requests & responses?

**Comment by mihok** [comment]
@edwardmedia sorry for being naive, I ran the command with `TF_LOG=DEBUG` how do I get the api request & responses?

**Comment by edwardmedia** [comment]
@mihok you are on the track. Just share the output of `tf apply` when you have `TF_LOG=DEBUG`. 

```
---[ REQUEST ]---------------------------------------
GET
....

---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
```

**Comment by mihok** [comment]
@edwardmedia https://gist.github.com/mihok/367f41af6cabdd9c85509b81d67a5d16

**Comment by edwardmedia** [comment]
@mihok You might want to check [RFC1918-compliant CIDR](https://netbeez.net/blog/rfc1918/) to see if yours are compliant? Are you using cdk?  From the log you provided, I don't see any api calls invoked. 

```
10.0.0.0 – 10.255.255.255  (10/8 prefix)
172.16.0.0 – 172.31.255.255  (172.16/12 prefix)
192.168.0.0 – 192.168.255.255 (192.168/16 prefix)
```

**Comment by edwardmedia** [comment]
@mihok the [validation](https://github.com/hashicorp/terraform-provider-google/blob/main/google/validation.go#L121) is implemented in the provider. I think the error is appropriate in your case, as the CIDR is invalid. Did you say the [validation](https://github.com/hashicorp/terraform-provider-google/blob/main/google/validation.go#L121) is wrong?

**Comment by mihok** [comment]
A I see where I went wrong, you are correct @edwardmedia appreciate the clarity. The 172 CIDR is /12.
