### ISSUE TITLE
Bug with imported google_firebase_apple_app. deletion_policy is null

### ISSUE THREAD

**Issue by galkin** [hashicorp/terraform-provider-google#13119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1

### Affected Resource(s)

* google_firebase_apple_app

### Terraform Configuration Files

```tf
resource "google_firebase_apple_app" "default" {
  provider = google-beta
  project = "my-project-name"
  display_name = "Display Name Basic"
  bundle_id = "apple.app.12345"
}
```

### Expected Behavior

After import existing resource google_firebase_apple_app we don't need recreate the resource.

### Actual Behavior

We can not import resource without recreation. 

### Steps to Reproduce

1. Create ios app in Firebase Console (or use existing).
2. `terraform import google_firebase_apple_app.default projects/<projectName>/iosApps/<App ID in 1:___________:ios:___________ format>`
3. `terraform apply`

### References
* Looks repeated [#12810](https://github.com/hashicorp/terraform-provider-google/issues/12810)

**Comment by galkin** [comment]
@edwardmedia, thank you! Do you need any help with reproducing the bug?

**Comment by galkin** [comment]
@edwardmedia i think we should reopen this. The problem exists

**Comment by rainshen49** [comment]
Have we considered the approach in https://github.com/GoogleCloudPlatform/magic-modules/pull/6738? I have a similar fix in PR https://github.com/GoogleCloudPlatform/magic-modules/pull/6911 that happened in parallel with https://github.com/GoogleCloudPlatform/magic-modules/pull/6914
