### ISSUE TITLE
google_alloydb_instance updates display_name, id and name on every execution

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#13113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.9
on darwin_amd64
provider registry.terraform.io/hashicorp/google v4.44.0
provider registry.terraform.io/hashicorp/google-beta v4.44.0

### Affected Resource(s)

* google_alloydb_instance

### Terraform Configuration Files

```tf
resource "google_alloydb_instance" "default" {
  provider      = google-beta
  cluster       = google_alloydb_cluster.default.name
  instance_id   = "${var.prefix}-alloydb-instance"
  display_name  = "my-alloydb-instance"
  instance_type = "PRIMARY"
  labels = {
    key   = "value"
  }
  machine_config {
    cpu_count = 2
  }

}
```

### Expected Behavior
It should not update anything if there is no change in the code

### Actual Behavior
It is updating display_name, id and name on every execution

```
  # google_alloydb_instance.default will be updated in-place
  ~ resource "google_alloydb_instance" "default" {
      + display_name   = "my-alloydb-instance"
        id             = "projects/my-prj/locations/us-central1/clusters/sin-alloydb-cluster/instances/sin-alloydb-instance"
        name           = "projects/my-prj/locations/us-central1/clusters/sin-alloydb-cluster/instances/sin-alloydb-instance"
```
### Steps to Reproduce
Execute terraform apply again after instance is created

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
api doesn't include [display_name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#display_name) in its response
