### ISSUE TITLE
Please support adding "principals" to "resource_bigquery_datapolicy_data_policy"

### ISSUE THREAD

**Issue by RezaRahmati** [hashicorp/terraform-provider-google#13118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please see below screen shot, Policy Tags masking rules supports adding principals, but there is no option in `google_bigquery_datapolicy_data_policy` terraform module

![image](https://user-images.githubusercontent.com/10086092/204116217-21529fa0-6f90-4c21-aced-e8ca01a5dd94.png)

### New or Affected Resource(s)

* google_bigquery_datapolicy_data_policy

### Potential Terraform Configuration
```
resource "google_bigquery_datapolicy_data_policy" "data_policy" {
  provider         = google-beta
  project          = var.project_id
  location         = var.region
  data_policy_id   = "data_policy"
  policy_tag       = google_data_catalog_policy_tag.pii_policy_tag.name
  data_policy_type = "DATA_MASKING_POLICY"
  data_masking_policy {
    predefined_expression = "SHA256"
    principals = [
        "user@email.com",
        "server@example.gserviceaccount.com"
    ]
  }
  depends_on = [
    google_data_catalog_policy_tag.pii_policy_tag
  ]
}
```

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

[https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_datapolicy_data_policy#data_masking_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_datapolicy_data_policy#data_masking_policy)

**Comment by DrFaust92** [comment]
not supported via api https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest/v1beta1/projects.locations.dataPolicies#DataMaskingPolicy

unless! its a nice way to show the iam which in that case its already supported via the iam_* resources for this. which im prone to belive that case and ui is just simplifying it

**Comment by markdoutrempb** [comment]
The way to do this is
a) create the policy
b) use google_bigquery_datapolicy_data_policy_iam_member to add the role to the policy
What is wrong is the terraform docs. They show the role as "roles/viewer. The role needs to be
role = "roles/bigquerydatapolicy.maskedReader"

**Comment by rileykarson** [comment]
If another role makes more sense, feel free to add a value for [`allowed_iam_role`](https://github.com/GoogleCloudPlatform/magic-modules/blob/2e871d7e3d0b3ef75e923801b907f2d38e29832d/mmv1/api/resource/iam_policy.rb#L60) to https://github.com/GoogleCloudPlatform/magic-modules/blob/2e871d7e3d0b3ef75e923801b907f2d38e29832d/mmv1/products/bigquerydatapolicy/api.yaml#L42! That defaults to `roles/viewer`, since most IAM methods accept it.

Otherwise, closing as wontfix.
