### ISSUE TITLE
cloudfunctions.allowedVpcConnectorEgressSettings Error: googleapi: Error 400

### ISSUE THREAD

**Issue by headincl0ud** [hashicorp/terraform-provider-google#13122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.5
on darwin_amd64

### Affected Resource(s)

* google_folder_organization_policy

### Terraform Configuration Files

```tf
resource "google_folder_organization_policy" "allowed_egress_settings" {
  folder     = data.terraform_remote_state.<STATE>.outputs.folders.<PROJECT>
  constraint = "constraints/cloudfunctions.allowedVpcConnectorEgressSettings"
  list_policy {
    inherit_from_parent = false
    allow {
      values = ["VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED"]
    }
  }
}
```

### Debug Output

No response 

### Panic Output

No response 

### Expected Behavior

No response 

### Actual Behavior

```
│ Error: googleapi: Error 400: The policy contains invalid list value(s): [VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED]. Please fix the values in the policy and try again:
│ StoragePolicy{resource=null, constraint=constraints/cloudfunctions.allowedVpcConnectorEgressSettings, etag=<ByteString@54ef6f4d size=0 contents="">, updateTime=Optional.empty, policy=ListPolicy{inheritFromParent=false, unconditionalFragment=Optional[UnconditionalFragment{allValues=ALL_VALUES_UNSPECIFIED, allowedValues=[ListValue{type=EXACT, canonicalValue=VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED, userSuppliedValue=Optional[VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED]}], deniedValues=[], suggestedValue=Optional[]}], conditionalFragments=[]}}
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value: [VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED].",
│         "field": "policy.list_policy.allowed_values[0]"
│       }
│     ]
│   }
│ ]
│ , badRequest
```

### Steps to Reproduce

1. terraform init
2. terraform apply

### Temporary workaround:

```tf
resource "google_folder_organization_policy" "allowed_egress_settings" {
  folder     = data.terraform_remote_state.<STATE>.outputs.folders.<PROJECT>
  constraint = "constraints/cloudfunctions.allowedVpcConnectorEgressSettings"
  list_policy {
    inherit_from_parent = false
    allow {
      values = ["VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED"]
      all = true
    }
  }
}
```

**Comment by edwardmedia** [comment]
@edwardmedia the api complains `VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED`. Where did you find this value?

```
VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED
```

**Comment by edwardmedia** [comment]
@headincl0ud is this still an issue?
