### ISSUE TITLE
Still Missing confidential VM configuration for google_container_node_pool

### ISSUE THREAD

**Issue by pbecotte** [hashicorp/terraform-provider-google#13127]
### Affected Resource(s)

* google_container_node_pool

https://github.com/hashicorp/terraform-provider-google/issues/10236

This field is required for google_container_node_pool as well as the cluster

**Comment by rileykarson** [comment]
This appears in `NodeConfig`: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig

**Comment by mustaFAB53** [comment]
Hi Team,
Do we have any update on this issue. We are looking forward for the same.

Currently updating this at cluster level requires a recreation of the same which we do not want

As per gcloud [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/confidential-gke-nodes#update_an_existing_node_pool), this configuration can be update in-place at nodepool level which will help us alot

**Comment by HmFlashy** [comment]
Hello same for us! We we would like to be able to configure it at cluster level
Thanks

**Comment by rnicoll** [comment]
claiming this issue

**Comment by shuyama1** [comment]
fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/8758
