### ISSUE TITLE
Googlemail is resolved to gmail, failing terraform expectation (IAM)

### ISSUE THREAD

**Issue by stefluhh** [hashicorp/terraform-provider-google#13131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Google resolves `@googlemail.com` mails to `@gmail.com` and responds the successful IAM policy creation with the normalized mail TLD. Terraform validates the response with its expectation and yields to an error.

### Terraform Version

```
Terraform v1.3.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1
```

### Affected Resource(s)
* google_project_iam_member

### Terraform Configuration Files

```tf
resource "google_project_iam_member" "viewer" {
  for_each = [
    "user:some-user@gmail.com",
    "user:some-other-user@googlemail.com",
  ]

  project = var.project_id
  role    = "roles/viewer"
  member  = each.value
}
```

### Debug Output

```
... 
Members:([]string)[user:some-user@gmail.com user:some-other-user@gmail.com] Role:(string)roles/viewer
...
```

### Expected Behavior

Google should probably hide the fact that they normalize @googlemail to @gmail in their response.

### Actual Behavior

```
error: Provider produced inconsistent result after apply
--> Root resource was present, but now absent.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@stefano-lucka interesting. I would agree with your below expectation, but that is all done at the API. There is little we can do at the provider level. Can you share your debug log? 

```
Google should probably hide the fact that they normalize @googlemail to @gmail in their response.
```

**Comment by edwardmedia** [comment]
@stefluhh is this still an issue?

**Comment by edwardmedia** [comment]
@stefluhh closing this assume this is no longer an issue
