### ISSUE TITLE
Add support for logging bucket to google_logging_metric

### ISSUE THREAD

**Issue by LucaPrete** [hashicorp/terraform-provider-google#13139]
### Description

Add support for [bucket_name argument](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics#LogMetric) in google_logging_metric

### New or Affected Resource(s)

* google_logging_metric

### Potential Terraform Configuration

* modify product/logging/api to support the new field
* update the test
* create an ad-hoc example

### References

* https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics#LogMetric

**Comment by hao-nan-li** [comment]
b/261087278
