### ISSUE TITLE
```google_bigquery_table```: Cannot create materialized views for existing tables with schema field

### ISSUE THREAD

**Issue by illmaticz** [hashicorp/terraform-provider-google#13141]
### Community Note
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave +1 or me too comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.
If an issue is assigned to the modular-magician user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to hashibot, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.8

### Affected Resource(s)

google_bigquery_table

### Terraform Configuration Files

**./tables/tables.tf:**

```tf

resource "google_bigquery_table" "tables" {
  for_each            = {
    for m in var.tables : "${m.id}" => m
  }
  dataset_id          = var.db_id
  deletion_protection = false
  table_id            = each.value.id
  
  dynamic "time_partitioning" {
    for_each = each.value.partitioned == "true" ? [1] : []
    content {
      type  = each.value.type
      field = each.value.field
    }
  }
  
  dynamic "materialized_view" {
    for_each = each.value.has_materialized_view == "true" ? [1] : []
    content {
      query = file("${path.module}/${var.db_id}/materialized_views/${each.value.id}-mat-view.sql")
      enable_refresh = true
      refresh_interval_ms = 1800000
    }
  }
    
  labels = {
    environment = var.environment
    application = var.application
  }
  schema = fileexists("${path.module}/${var.db_id}/${each.value.id}.json") ? file("${path.module}/${var.db_id}/${each.value.id}.json") : null
}

```
**main.tf:** 
```tf

resource "google_bigquery_dataset" "database" {
  count                      = length(var.dbs)
  dataset_id                 = var.dbs[count.index].db_id
  friendly_name              = var.dbs[count.index].db_name
  description                = "Dataset created by Terraform"
  location                   = "US"
  delete_contents_on_destroy = var.delete_contents_on_destroy
  labels = {
    environment = var.environment
    application = var.dbs[count.index].app_name
  }
}

module "tables" {
  source      = "./tables"
  count       = length(var.dbs)
  db_id       = google_bigquery_dataset.database[count.index].dataset_id
  environment = var.environment
  application = var.dbs[count.index].app_name
  tables      = var.dbs[count.index].tables
}

```
example - **dev.tfvars:**

```tf
region     = "us-central1"
project_id = "hello-there"
dbs = [
  {
  db_id="hey_github"
  db_name="something"
  app_name="something"
  tables = [
    {
      id          = "example_table1"
      partitioned = "true"
      field       = "Date"
      type        = "MONTH"
      has_materialized_view = "true"
    },
    {
      id          = "example_table2"
      partitioned = "false"
      field       = ""
      type        = ""
      has_materialized_view = "true"
    }
  ]
  }

```

### Debug Output

```
Plan goes green, apply fails with:
Plan: 2 to add, 0 to change, 0 to destroy.

module.tables[5].google_bigquery_table.tables["example_table1"]: Creating...

module.tables[5].google_bigquery_table.tables["example_table2"]: Creating...
......

**`Error: googleapi: Error 400: Schema field shouldn't be used as input with a materialized view, invalid`**


```
### Expected Behavior

I am expecting to create a materialized view using a loop on already existing BQ tables that were created from a JSON schema file

### Actual Behavior

**`Error: googleapi: Error 400: Schema field shouldn't be used as input with a materialized view, invalid`**

### Steps to Reproduce

1. Take above TF configuration and try to create the tables with JSON Schema + materialized views

This error is pretty vague, also I understand this might not be an ACTUAL terraform provider issue but an issue on Google's side but still I couldn't find ANY info about it.

### Important Factoids

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
  }
  required_version = ">= 0.13"
}

Thank you in advance.

**Comment by edwardmedia** [comment]
@illmaticz can you share the debug log?

**Comment by illmaticz** [comment]
Hey @edwardmedia, I am attaching the part after the TF tries to apply since it is huge and I don't want to expose any info.
Can you let me know if that's enough for debugging?
[tf_debug.txt](https://github.com/hashicorp/terraform-provider-google/files/10126456/tf_debug.txt)

Thanks!

**Comment by edwardmedia** [comment]
@illmaticz Thanks for the log but I am more interested in seeing the api requests & responses before the error occurred?

**Comment by illmaticz** [comment]
[tf_log_Debug_extended.txt](https://github.com/hashicorp/terraform-provider-google/files/10140372/tf_log_Debug_extended.txt)

Hey @edwardmedia Here you go

**Comment by edwardmedia** [comment]
@illmaticz I reviewed the log and spotted below error. Based on the config you provided, it is hard for me to guess what went to wrong. Are you able to create a simple config by removing `module` and `dynamic` that can be used to repro the issue?  

```
Error: googleapi: Error 400: Schema field shouldn't be used as input with a materialized view, invalid
```

**Comment by edwardmedia** [comment]
@illmaticz is this still an issue?

**Comment by edwardmedia** [comment]
@illmaticz closing this assuming it is no longer an issue
