### ISSUE TITLE
google_cloudbuild_trigger repository mapping validation is not case sensitive

### ISSUE THREAD

**Issue by tomekporozynski** [hashicorp/terraform-provider-google#13142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.44.1
```

### Affected Resource(s)

google_cloudbuild_trigger

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "non_master_trigger" {
  project     = "<my_project>"
  description = "<my_description>"

  github {
    name  = "RePoSiTorY_NamE_that_is_CASEsensitive"
    owner = "mygithuborg"
    push {
      branch       = "^(development|non\\-production|production)$"
      invert_regex = true
    }
  }

  substitutions = {
    _TF_ACTION            = "plan"
  }

  filename = "cloudbuild-tf-plan.yaml"
}
```

### Debug Output

N/A

### Panic Output

N/A

#### Case example:
GitHub repository is called:  
***Repostiory_name_that_is_casesensitive***
This repository has been connected via https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github

In terraform code, we specify:

```tf
resource "google_cloudbuild_trigger" "non_master_trigger" {
 [...]
  github {
    name  = "RePoSiTorY_NamE_that_is_CASEsensitive"  #note the change in letter case of this repository
    owner = "mygithuborg"
 [...]
}
```

The expected result is:
```
Error: Error updating Trigger "projects/<...>": googleapi: Error 400: Repository mapping does not exist. Please visit https://console.cloud.google.com/cloud-build/triggers/connect?<...>
```

### Actual Behavior

The trigger is configured and build is successful resulting in trigger configuration that is not valid and not functional.

### Steps to Reproduce

A. Connect Github repository to CloudBuild via https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github
B. Within Terraform code, create trigger with "case-typo" in repository name (for example change random letter to capital letter in repo name). 
C. Apply the terraform code, inspect the trigger created.

### References

* #0000

**Comment by tomekporozynski** [comment]
Based on further investigation I reproduced the same "issue" by sending API requests via Method projects.locations.triggers.create.  So this issue is not strictly related to provider, rather API itself. Not sure if, in such case, this is a correct place to raise this bug. Please advice.

**Comment by edwardmedia** [comment]
@tomekporozynski can you share the debug log so I can take another look?

**Comment by tomekporozynski** [comment]
hi @edwardmedia I had confirmed this is related to API response (for method: projects.locations.triggers.create), so it seems there is nothing that could be done on terraform google provider level. The validation is done via API, not the terraform provider, it seems my issue should not be here. Thanks for your help.
