### ISSUE TITLE
Container Cluster doesn't respect project when checking if service enabled

### ISSUE THREAD

**Issue by clive-h-townsend** [hashicorp/terraform-provider-google#13148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf

provider "google" {
  credentials = file("terraform-XXXXX-cred.json")
}

resource "google_project" "project" {
  name            = var.project_id
  project_id      = var.project_id
  folder_id       = data.google_folder.production_folder.name
  billing_account = "XXXXX-XXXXXX-XXXXXX"
}

resource "google_project_service" "container" {
  project = google_project.project.project_id
  service = "container.googleapis.com"
}


resource "google_container_cluster" "primary" {
  project  = google_project.project.project_id
  name     = "XXXX-XXX-cluster"
  location = "us-central1"


  #   Must have node pool to create cluster, delete immediately
  remove_default_node_pool = true
  initial_node_count       = 1
  network                  = google_compute_network.vpc_network.name
  ip_allocation_policy {

  }
  networking_mode = "VPC_NATIVE"
}
```

### Debug Output

`Error: googleapi: Error 403: Kubernetes Engine API has not been used in project XXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=XXXXXX`

However, this is the WRONG project ID. This project ID maps to the google credentials file, not the project created in the terraform execution. 

### Expected Behavior

Not request enable API

### Actual Behavior

Requests to enable API in controlling project from the credentials file, not the referenced project identifier. However, if I manually enable the service `container.googleapis.com` in the controlling project, the cluster is correctly created in the child project.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@clive-h-townsend I think you were talking about two issues here:
1) the error you received. A cluster can't be created until the service `container.googleapis.com` is enabled in the project. You may want to add `depends_on` in `google_container_cluster` to make sure that order. Sometimes you may want to add [sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) to give extra time to have the service ready to use.
2) the issue you mentioned below. I don't have an answer. Can you share your debug log so I can take a close look?

```
However, this is the WRONG project ID. This project ID maps to the google credentials file, not the project created in the terraform execution.
```

**Comment by clive-h-townsend** [comment]
@edwardmedia - Thanks for the fast response! So it is the same issue because as you point out, on 1) that it is checking if `container.googleapis.com` is enabled. That is, of course, correct. But it is checking for that enabled status on the wrong project. The service is enabled on the child/controlled project (correctly) and not enabled on the parent (controlling) project (also correct). However, the `google_container_cluster` is not respecting the project tag specifically on the service enabled checking step. If I enable the service on both projects, `google_container_cluster` correctly creates on the child/controlled project.

I will run the debug and provide a gist now.

**Comment by clive-h-townsend** [comment]
Sorry for the noob question... I see the debug info in the console, not quite sure how to get that to you. It also appears to include sensitive data?

**Comment by edwardmedia** [comment]
Can you try something like `terraform apply >>debug.log`

**Comment by clive-h-townsend** [comment]
The `terraform apply >> debug.log` only prints the state refresh logs to the file. i.e 

`[0m[1mgoogle_cloud_tasks_queue.rq-news: Refreshing state... [id=projects/XXX/locations/us-central1/queues/XXX][0m`

 Everything else ends up in the terminal. 
 
 If the answer is that the service is required on both projects, I understand. Seems weird but I can do that. Might suggest a documentation update otherwise, all good.

**Comment by edwardmedia** [comment]
@clive-h-townsend this is a gcp behavior, not at the provider specific. Closing the issue then.
