### ISSUE TITLE
BigQuery and BigTable Data Sources?

### ISSUE THREAD

**Issue by aaroncline** [hashicorp/terraform-provider-google#13168]
I would really find a lot of value if there were data sources in the BigQuery and BigTable resources so that I could reference existing BigQuery Datasets and Tables and/or BigTable Clusters.  

Being able to add permissions (iam_member) to DataSets or Tables already in Bigquery that were not created by Terraform and that I don't want to create via Terraform would be extremely powerful.  For BigTable, being able to reference the schema, cluster, and permissions would be just as powerful.  Are there any plans on the roadmap to add Data Sources to BigQuery and BigTable part of the provider?

**Comment by edwardmedia** [comment]
@aaroncline please file [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) if the data sources are not available so the tasks will be triaged.
