### ISSUE TITLE
Unable to create Node Pool with google-beta when creating pod range using network_config

### ISSUE THREAD

**Issue by manikanthkumar** [hashicorp/terraform-provider-google#13178]
We are trying to create a gke cluster with multiple node pools. We want unique ip ranges for each node pool created.

**We are using below properties to create a node pool:**
```tf
resource "google_container_node_pool" "node-pool" {
  provider = google-beta
  name       = "sample-node"
  cluster    = google_container_cluster.primary.name
  project = "projectid"
  location   = "us-central1-a"
  node_count = 1
  version = "1.23.8-gke.1900"
  max_pods_per_node = 10
  autoscaling {
    max_node_count = 5
    min_node_count = 1
  }

  network_config {
    create_pod_range = true
    pod_ipv4_cidr_block = "10.0.0.0/24" #Sample ip range
    pod_range = ""
  }

  management {
    auto_repair  = true
    auto_upgrade = false
  }
  node_config {
    labels = {
      application = "somelabel"
    }
    taint {
      key = "type"
      value = "nodepool"
      effect = "NO_SCHEDULE"
    }
    tags = ["k8s-cluster", "k8s-dev-cluster"]
    machine_type = "n2d-standard-4"
    disk_size_gb = 10
  }
}
```
If we try to create node pool with above code it runs for about 30mins and stops with below error: 
**NodePool "sample-node" has state "PROVISIONING" with message ""**

Can you please let us know if we are missing something.

**Comment by edwardmedia** [comment]
@manikanthkumar can you share your debug log?

**Comment by manikanthkumar** [comment]
Hi Edward,
Below is the output i get for terraform apply for a node pool. Please let me know if this is what you are looking for.

module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Creating...
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [1m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [2m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [3m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [4m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [5m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [6m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m30s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m40s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [7m50s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [8m0s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [8m10s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [8m20s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [8m30s elapsed]
.
.
.

module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [29m51s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [30m1s elapsed]
module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"]: Still creating... [30m11s elapsed]
╷
│ Error: NodePool "projects/dev-slapp/locations/us-central1-a/clusters/test-cluster/nodePools/test-app-pool" has state "PROVISIONING" with message ""
│
│   with module.lm_gke_cluster.google_container_node_pool.node-pool["test-app-pool"],
│   on .terraform/modules/lm_gke_cluster/main.tf line 67, in resource "google_container_node_pool" "node-pool":
│   67: resource "google_container_node_pool" "node-pool" {
│
╵
Releasing state lock. This may take a few moments...

**Comment by edwardmedia** [comment]
@manikanthkumar I can't repro this error. Would you be possible to rerun with debug on (TF_LOG=DEBUG)?

**Comment by manikanthkumar** [comment]
Itw working now. We can close this

**Comment by edwardmedia** [comment]
@manikanthkumar cool. Thanks. Close the ticket now
