### ISSUE TITLE
google_monitoring_metric_descriptor replacement prevented by a dependent alert policy

### ISSUE THREAD

**Issue by llh-veolia** [hashicorp/terraform-provider-google#13179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.1.7 in attempted production
0.15.0 in the stripped-down code taken and ran from [your doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_metric_descriptor#example-usage---monitoring-metric-descriptor-basic)

### Affected Resource(s)

* google_monitoring_metric_descriptor
* google_monitoring_alert_policy

### Terraform Configuration Files

This minimal example is actually taken from your documentation ([link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_metric_descriptor#example-usage---monitoring-metric-descriptor-basic)).
The configurations differ before and after the change only by one commented line :
```tf
resource "google_monitoring_metric_descriptor" "with_alert" {
  description = "Daily sales records from all branch stores."
  display_name = "metric-descriptor-${local.name_suffix}"
  type = "custom.googleapis.com/stores/daily_sales-${local.name_suffix}"
  metric_kind = "GAUGE"
  value_type = "DOUBLE"

  # The line to uncomment
  # unit = "{USD}"
}

resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "metric-descriptor-${local.name_suffix}"
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"${google_monitoring_metric_descriptor.with_alert.type}\" AND resource.type=\"gce_instance\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
    }
  }
}
```

### Debug Output

https://gist.github.com/llh-veolia/6e4eb1c794f612ee81c44301112adc9e

### Expected Behavior

The alert policy that depend on the metric to be replaced should be deleted before the metric is deleted and then recreated after the metric has been recreated.

### Actual Behavior

The `terraform apply` stage fails.

### Steps to Reproduce

1. `terraform apply`
2. uncomment the line adding the unit
3. `terraform apply`

**Comment by edwardmedia** [comment]
@llh-veolia those behavior of inter-resources is managed by the Terraform core. Your expectation makes sense but I am not sure if that is supported. Do you see that behavior in other providers (or other resources)?

**Comment by llh-veolia** [comment]
This is the first time I encounter this problem.

I did find a workaround that you might want to include in the documentation example linked above : 
```tf
resource "google_monitoring_alert_policy" "alert_policy" {
  # same lines as before ...

  lifecycle {
    replace_triggered_by = [google_monitoring_metric_descriptor.with_alert]
  }
}
```
But it's not clean since it will trigger with _any_ changes made to the metric, not just those that trigger it's replacement.

**Comment by edwardmedia** [comment]
@llh-veolia yes, `lifecycle` is one workaround.  Unfortunately there is no good solution at the provider level. Closing this now. Feel free to reopen if you need to continue the conversation. Thanks

**Comment by llh-veolia** [comment]
thanks for your time.
