### ISSUE TITLE
terraform import google_access_context_manager_access_level - Not working as expected

### ISSUE THREAD

**Issue by amar2k05** [hashicorp/terraform-provider-google#13181]
Hi,
I am trying to import existing GCP infra (access level) into terraform state, below is the code.

**Import Command:**
terraform import google_access_context_manager_access_level.access_level.default accessPolicies/590731782016/accessLevels/test_access_001

**Resource used in main.tf**

resource "google_access_context_manager_access_level" "access-level" {
  parent = "accessPolicies/590731782016"
  name   = "accessPolicies/590731782016/accessLevels/test_access_001"
  title  = "test_access_001"
  basic {
    conditions {
      members= [
                "user:allan.mark@gmail.com"
               ] 
    }
  }
}

**Error:**
Error: Invalid address
│ 
│   on <import-address> line 1:
│    1: google_access_context_manager_access_level.access_level.default
│ 
│ Resource instance key must be given in square brackets.
╵
For information on valid syntax, see:
https://www.terraform.io/docs/cli/state/resource-addressing.html

I am using as per the documentation but still getting error. Kindly help.

Thanks,
Amarnath.

**Comment by amar2k05** [comment]
Hi,

I am now able to import successfully using below.

import --var-file=$VARS --var-file=$BACKEND --var-file=vars/$ENV/terraform.tfvars google_access_context_manager_access_level.access-level accessPolicies/590731782016/accessLevels/test_access_001

I am now going to import a module and I have a question, do we need to have individual configuration for each resource in the module or Can I use directly the module as the configuration?
I mean if my module uses 10 resources, do I need to have 10 resource blocks as part of configuration, or one module will suffice?

Regards,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 is this still an issue?

**Comment by amar2k05** [comment]
Hi,
No this is solved now.
I was using incorrect syntax.

Thanks,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 cool. Thank you letting me know. Closing the issue then
