### ISSUE TITLE
Google Compute Instance Still Initialize with incorrect os image

### ISSUE THREAD

**Issue by yasinahlattci** [hashicorp/terraform-provider-google#13187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform version 1.3.4
provider version 4.44.1

### Affected Resource(s)

google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "default" {
  name         = "test-vm"
  machine_type = "e2-medium"
  zone         = "${var.region}-b"

  boot_disk {
    initialize_params {
      image = "ubuntu-minimal-2004-lts-arm64"
    }
  }
  
  network_interface {
    network = "default"
    access_config {
    }
  }
  tags = ["svc1"]
}
```

Hello, machine types should be compatible with boot disks architecture. In this example I'm trying to initialize an instance, using e2-medium machine_type and ubuntu-minimal-2004-lts-arm64. Somehow I messed up the bootdisk image and choose the wrong one. If I want to create the same instance from cloud console, I could not be able to do that. I believe terraform should do the same thing here and throw and error. I am not sure if this error is related to terraform provider. It might be related to gcloud because api request also creates the machine.

### Expected Behavior
If bootdisk architecture and machine_type is not compatible, terraform should throw error

### Actual Behavior

Machine gets initialized

**Comment by edwardmedia** [comment]
@yasinahlattci can you share the doc (console screenshot) that says this can't be done? Also please share your debug log.

**Comment by yasinahlattci** [comment]
![console](https://user-images.githubusercontent.com/78930233/206031454-7a7b672d-9196-4e2d-902f-363d160468ee.png)
I couldn't be able to fit the machine_type into same screenshot but, it is e2-medium. boot image is 'ubuntu-minimal-2004-lts-arm64'

DEBUG LOG
[logs.txt](https://github.com/hashicorp/terraform-provider-google/files/10170630/logs.txt)

Thanks

**Comment by edwardmedia** [comment]
@yasinahlattci I see below error in the log. What did you see at the terraform side? 

{
  "error": {
    "code": 404,
    "message": "The resource 'projects/directed-bongo-370109/global/images/ubuntu-minimal-2004-lts-arm64' was not found",
    "errors": [
      {
        "message": "The resource 'projects/directed-bongo-370109/global/images/ubuntu-minimal-2004-lts-arm64' was not found",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}

**Comment by yasinahlattci** [comment]
Yes, I also see that but terraform succeeded anyways and creates the instance, after successfully applied I verified from console that the instance has been created. But I need to add that it's not working, I did not even ssh to the instance

**Comment by edwardmedia** [comment]
@yasinahlattci mind share the terraform result? You may run `terraform show`

**Comment by yasinahlattci** [comment]
Hi, sorry for late response. Of course
[terraform-show.txt](https://github.com/hashicorp/terraform-provider-google/files/10197621/terraform-show.txt)

**Comment by edwardmedia** [comment]
@yasinahlattci there is a [certain logic ](https://github.com/hashicorp/terraform-provider-google/blob/main/google/image.go#L93)in the provider for obtaining an image.  The provider will try multiple ways to land an image when an error is received like yours. Please review the [code](https://github.com/hashicorp/terraform-provider-google/blob/main/google/image.go#L93) and let me know if that makes sense.

**Comment by edwardmedia** [comment]
@yasinahlattci does this make sense to you?
