### ISSUE TITLE
Data Transfer - Short Term Token Minter doesn't exist

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#13191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

The documentation link for Data Transfer config references a shortTermTokenMinter role that doesn't exist anymore? 
Should this be updated to be tokenCreator? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config 

### Affected Resource(s)

* google_bigquery_data_transfer_config

### References

* #0000

**Comment by drandell** [comment]
No config as such, just that according to the understanding roles docs this role doesn't exist. Nor can i find it in one of the examples where we have actually deployed this with the role mentioned. 

https://cloud.google.com/iam/docs/understanding-roles - no short term minter in this document. 
And this doc links mentions assigning token creator which i have and thats working as intended - https://cloud.google.com/bigquery/docs/enable-transfer-service#cross-project_service_account_authorization

**Comment by edwardmedia** [comment]
@drandell can you [call the api](https://github.com/hashicorp/terraform-provider-google/issues/13286#issuecomment-1359691863) to see if the role exists? I found the role returned
