### ISSUE TITLE
User-Agent does not reflect the provider version in use

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform version

Terraform v1.4.0-dev
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.45.0
```

But this issue should not be affected by Terraform version

### Affected Resource(s)

N/A

### Terraform Configuration Files

Any config would trigger this issue, and I don't want to include config here as it'd confuse the issue description.

### Expected Behavior

User Agent should reflect the version of the provider in use (as well as the version of Terraform and the SDK)
As I'm using Terraform v1.4.0-dev and v4.45.0 of the provider, the user agent should look like:

```
Terraform/1.4.0-dev (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.45.0
```

### Actual Behavior

User Agent included the `dev` value:

```
Terraform/1.4.0-dev (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/dev
```

<img src="https://user-images.githubusercontent.com/15078782/206285339-a1a4258e-34a1-4660-8333-25da9b0fc74b.png" width="80%"/>

### Steps to Reproduce

Provision something and look at the headers on the outgoing requests to the Google API(s)

### Important Factoids

This bug is due to the variable in `./version/version.go` not being overridden by goreleaser with this step

https://github.com/hashicorp/terraform-provider-google/blob/01cd99483b1b8b31eb4bf388a41e29094cac07ff/.goreleaser.yml#L31-L32

The value is used in the provider code here on L1490 of provider.go:

https://github.com/hashicorp/terraform-provider-google/blob/d075c8203af8c5e22ad4f6307a8d396f059649a2/google/provider.go#L1483-L1491

### References

* Equivalent issue in the AWS provider: [Release: Restore provider version in HTTP User-Agent strings #28240](https://github.com/hashicorp/terraform-provider-aws/pull/28240)

**Comment by SarahFrench** [comment]
The recommended steps for testing the fix are to:

- `goreleaser build --single-target --debug --rm-dist --skip-validate`
- Set up a developer override with the output
- Run `TF_LOG=DEBUG terraform plan` - but I think this provider doesn't display the user agent in debug output

**Comment by SarahFrench** [comment]
I've opened PRs for TPG and TPGB but I need to manually test the change

**Comment by rileykarson** [comment]
🎉  I noticed this was an issue a couple weeks back (& checked to see that it was an issue for Azure/AWS as well) but forgot to actually file an issue for it. Good catch!

I noticed that the `ldflags` value was a different one than I expected, but I can't recall which the working one actually was at the moment.

**Comment by SarahFrench** [comment]
I can't claim any credit 😅 This was raised internally by someone on the AWS team and I just checked to see if it also affected us here
