### ISSUE TITLE
Promote Backup for GKE BackupPlan and Container Cluster Add-on to GA 

### ISSUE THREAD

**Issue by neha-vellanki12** [hashicorp/terraform-provider-google#13195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Backup for GKE is a GA feature, and both the add on in google_container_cluster (addonsConfig.gkeBackupAgentConfig) and Backup Plan resource should be promoted to GA for consistency 

### New or Affected Resource(s)

* google_container_cluster.addons_config.gke_backup_agent_config
* google_gke_backup_backup_plan

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/6883 appears to perform the changes to `google_container_cluster.addons_config.gke_backup_agent_config`. @neha-vellanki12 can you confirm that this feature has already gone GA on the API?

**Comment by neha-vellanki12** [comment]
@rileykarson yes, this feature is GA in the API

**Comment by neha-vellanki12** [comment]
So it looks like from this merged PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/6898, the add on has already been promoted to GA. I'll work on a change then to promote the BackupPlan resource to GA as well.
