### ISSUE TITLE
Resource component for Google cloud deploy

### ISSUE THREAD

**Issue by DarioBernardo** [hashicorp/terraform-provider-google#13200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Would be great to have a resource component for [google cloud deploy](https://cloud.google.com/deploy). So that it would be possible to automatically create CD deploy pipeline on cloud deploy using terraform

**Comment by melinath** [comment]
We believe this is already supported:

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/clouddeploy_delivery_pipeline
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/clouddeploy_target

Please provide additional details if something is missing. Thanks!

**Comment by DarioBernardo** [comment]
Amazing thank you so much! Exactly what i was looking for. it worked perfectly.
