### ISSUE TITLE
Support backup plan for GKE to google_container_cluster resources or google_container_cluster_backup_config

### ISSUE THREAD

**Issue by tidusete** [hashicorp/terraform-provider-google#13207]
### Community Note

- Please vote on this issue by adding a +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

- If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Support [backup plan for GKE](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/backup) to google_container_cluster or create a new resource google_container_cluster_backup_config

### New or Affected Resource(s)
google_container_cluster or create a new resource google_container_cluster_backup_config

### Potential Terraform Configuration
```
# Create a backup plan for the GKE cluster
resource "google_container_cluster_backup_config" "my-backup-plan" {
  # Replace these values with the settings for your backup plan
  # Replace <NAME> with the name of your backup plan,
  # <DESCRIPTION> with the optional description,
  # <RETENTION-DAYS> with the number of days to retain your backups
  # <NAMESPACE> with the name of the namespace that you want to include in the backup plan
  # <CRON-EXPRESSION> with the CRON expression for the schedule.
  # You can also set the "include_secrets" and "include_persistent_volume_data" variables to true or false
  # depending on whether you want to include Kubernetes Secret resources and persistent volume data in your backups.
 ...
```

### References

- [Plan a set of backups](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/backup-plan#console)
- [Back up your workloads](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/backup)

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google/issues/10970

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/12634
