### ISSUE TITLE
Make metric_descriptor argument optional and computer for resource_logging_metric

### ISSUE THREAD

**Issue by LucaPrete** [hashicorp/terraform-provider-google#13215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Make metric_descriptor argument optional and computer for resource_logging_metric.
If not specified the field is automatically populated from Google APIs.

### Affected Resource(s)

* google_logging_metric

### Potential Terraform Configuration

Need to:

* remove required: false in logging api.yaml
* add default_from_apis: true in terraform.yaml
* remove metric_descriptor where not needed in tests

### References

* [API reference which mentions the field as optional](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics#LogMetric)

**Comment by roaks3** [comment]
This appears to have been fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6937
