### ISSUE TITLE
Incorrect "optional" flag for `email` field in `google_project_service_identity `

### ISSUE THREAD

**Issue by jingyih** [hashicorp/terraform-provider-google#13227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_project_service_identity

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_project_service_identity.go#L37

The `email` field in the schema of `google_project_service_identity ` is marked as "Optional: true". However specifying `email` in the resource results in the following error:
```
Error: Computed attributes cannot be set

  on main.tf line 6, in resource "google_project_service_identity" "example2":
   6:   email = "123456@pubsub.com"

Computed attributes cannot be set, but a value was set for "email".
```

### Terraform Configuration Files
```
resource "google_project_service_identity" "example2" {
  provider = google-beta

  project = "xxx"
  service = "pubsub.googleapis.com"
  email = "123456@pubsub.com"
}
````

**Comment by SarahFrench** [comment]
Hi @jingyih , thanks for raising this issue. It's actually a problem I introduced 😅 

The [email field is merely an attribute](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity#email) and cannot be set from the configuration, so I'll remove that schema behaviour from the field.

**Comment by jingyih** [comment]
Thanks for the quick triage! Looking forward to the fix!
