### ISSUE TITLE
Truely declarative Firebase security rules management

### ISSUE THREAD

**Issue by alexeyinkin** [hashicorp/terraform-provider-google#13235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Terrafrom currently can manage Firebase security rules with two resources:
1. `google_firebaserules_ruleset`, https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_ruleset
2. `google_firebaserules_release`, https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release

The workflow is:

1. Import the release resource.
2. Create a ruleset.
3. Set it as current with the release resource.

However there is a problem with updating the rules. Unlike other resources, these cannot just be edited and `terraform apply`-ed. `google_firebaserules_ruleset` is immutable, and any change forces Terraform to replace the resource. But the ruleset cannot be deleted while it is current. I can see the following output when trying to `terraform apply` changed rules:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.firestore.module.security_rules.google_firebaserules_release.default will be updated in-place
  ~ resource "google_firebaserules_release" "default" {
        id           = "projects/PROJECT/releases/cloud.firestore"
        name         = "cloud.firestore"
      ~ ruleset_name = "projects/PROJECT/rulesets/6c3e9b37-3537-427d-89e9-3ab0ac5f1786" -> (known after apply)
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.firestore.module.security_rules.google_firebaserules_ruleset.default must be replaced
-/+ resource "google_firebaserules_ruleset" "default" {
      ~ create_time = "2022-12-14T01:36:43.546895Z" -> (known after apply)
      ~ id          = "projects/PROJECT/rulesets/6c3e9b37-3537-427d-89e9-3ab0ac5f1786" -> (known after apply)
      ~ metadata    = [
          - {
              - services = [
                  - "cloud.firestore",
                ]
            },
        ] -> (known after apply)
      ~ name        = "6c3e9b37-3537-427d-89e9-3ab0ac5f1786" -> (known after apply)
        # (1 unchanged attribute hidden)

      ~ source {
          ~ files {
              ~ content = <<-EOT # forces replacement
                    rules_version = '2';
                  - service cloud.firestore {
                  + service  cloud.firestore {
                      match /databases/{database}/documents {
                        match /{document=**} {
                          allow read;
                        }
                      }
                    }
                EOT
                name    = "firestore.rules"
            }
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.firestore.module.security_rules.google_firebaserules_ruleset.default: Destroying... [id=projects/PROJECT/rulesets/6c3e9b37-3537-427d-89e9-3ab0ac5f1786]
╷
│ Error: Error deleting Ruleset: failed to delete Ruleset: googleapi: Error 400: Request contains an invalid argument.
│ 
│ 
╵
```

The correct way to update the rules seems to be to:
1. Create another ruleset.
2. Set it as current.
3. Delete the old ruleset.

The upside of this workflow is that we totally follow and understand the actual resource creation in Firebase. However, the point of Terraform is to be declarative.

### New or Affected Resource(s)

I suggest a higher level resource that could create a ruleset, set it as current and delete the older one in a single run.

* google_firebaserules

### Potential Terraform Configuration

```tf
resource "google_firebaserules" "default" {
  name = "cloud.firestore"
  project = "PROJECT"
  source {
    files {
      content = <<EOT
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**}
      allow read, write: if false;
    }
  }
}
EOT
      name = "firestore.rules"
    }
  }
  old_rules = DELETE # Options are DELETE | KEEP
}

```

b/277381287

**Comment by thdk** [comment]
@alexeyinkin thanks for this information, with the steps you mentioned I was able to implement the workaround in terraform

Im posting my setup here in case anyone else is struggling:

```
## Firestore rules

data "local_file" "firestore-rules" {
  filename = "${path.module}/firestore.rules"
}

resource "google_firebaserules_ruleset" "default" {
  source {
    files {
      content     = data.local_file.firestore-rules.content
      name        = "firestore.rules"
      fingerprint = sha1(data.local_file.firestore-rules.content)
    }
  }

  lifecycle {
    ignore_changes  = all
  }

  project = var.project
}

resource "google_firebaserules_ruleset" "rules-2022-12-24" {
  source {
    files {
      content     = data.local_file.firestore-rules.content
      name        = "firestore.rules"
      fingerprint = sha1(data.local_file.firestore-rules.content)
    }
  }

  lifecycle {
    ignore_changes  = all
  }

  project = var.project
}

resource "google_firebaserules_release" "default" {
  name         = "production"
  ruleset_name = "projects/${var.project}/rulesets/${google_firebaserules_ruleset.rules-2022-12-24.name}"
  project      = var.project
  depends_on = [
    google_firebaserules_ruleset.rules-2022-12-24,
  ]
}

```

**Comment by diegofrata** [comment]
For anyone struggling with this, just add create_before_destroy to your resource:

```hcl
resource "google_firebaserules_ruleset" "firestore" {
  source {
    files {
      content = file("${path.module}/firebase/firestore.rules")
      name    = "firestore.rules"
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by thdk** [comment]
So far the `create_before_destroy`mentioned by @diegofrata  lifecycle rule did work well for me. 
It should probably be included in the docs or even make this the default for this resource?

**Comment by rileykarson** [comment]
Marking this to add that to our docs.

**Comment by JackClark123** [comment]
This doesn't work the rules are never updated using create_before_destroy

**Comment by rileykarson** [comment]
Thanks! Kicking back into triage

**Comment by rainshen49** [comment]
Hi all! Firebaser here, thanks for raising this issue! Could you try adding this lifecycle block to the `google_firebaserules_release` (not the `google_firebaserules_ruleset`)?

```hcl
resource "google_firebaserules_release" "default" {
    ...

    lifecycle {
        replace_triggered_by = [
            google_firebaserules_ruleset.default
        ]
    }
}
```

What's happening:
1. When the rules change, terraform tries to replace the ruleset
2. The ruleset can't be deleted because it's being used by a release, thus you get `Error deleting Ruleset: failed to delete Ruleset.`
3. The normal behavior for `google_firebaserules_release` is to update-in-place, but it can't because the old ruleset hasn't been deleted and the new ruleset hasn't been created.
4. `replace_triggered_by` alters the behavior by replacing the `google_firebaserules_release` together with `google_firebaserules_ruleset`, so you get the right sequence of events: delete release, delete ruleset, create ruleset, create release

This is definitely an awkward workflow. Would this be something that we can make the default behavior in the next release, or do we need a major release for that? @rileykarson

**Comment by rileykarson** [comment]
Execution ordering isn't generally something we can control in the provider, unfortunately, so I'm not certain there's actually a way we can significantly change how this works! 

It's hard to say in advance whether a potential change (if one is possible) would be breaking or not here- we'd ultimately need to make a subjective call based on the finer details on what gets changed.

**Comment by rainshen49** [comment]
I'm imagining making `ruleset_name` an immutable/input parameter, which would achieve the desired behavior. I'll discuss with team how breaking that might entail.

**Comment by rileykarson** [comment]
Ah, right, that is a change we could make. That would be breaking- we may also want to consider a separate field so that update in place is still possible for users that want that behaviour. We do that for startup metadata in GCE instance.

**Comment by rainshen49** [comment]
Do you mean https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_instance#metadata_startup_script? That sounds like a plausible approach. I found some additional infor about the rules API. It is a lot less complicated but in a non-standard way:
1. Only the `ruleset_name` field is mutable
2. The full name is the same whether replaced or updated, e.g. Firestore rules release will always be named `projects/<project-identifier>/releases/cloud.firestore`
3. The only other fields are `update_time` and `create_time`

So, unless folks are doing something special with the timestamps, users should be indifferent to whether rules releases are replaced or updated.

**Comment by rileykarson** [comment]
Yeah, even in these cases we want to be careful about what we do- Terraform messaging users that it will delete the resource will be alarming, and require someone to manually review the changed behaviour. Users updating the provider may not be experts on every resource in the configuration and don't expect to read every changelog entry in detail. Basically, if anything requires human intervention (such as introducing a new diff, or forcing something to be rewritten) it'll require a human to figure out what's up- and that counts as something that needs to go in a major version.

Adding a new field that recreates the resource when used w/o needing to specify `replace_triggered_by` (which can be hard to plumb through into modules, for example) would be fine as long as current configurations are unaffected.

**Comment by robinryf** [comment]
I hope this adds to the conversation. But the described approach in https://github.com/hashicorp/terraform-provider-google/issues/13235#issuecomment-1505579243 does not work for me.

My providers:

```
provider "registry.terraform.io/hashicorp/google-beta" {
  version     = "4.61.0"
```

My config:

```
resource "google_firebaserules_release" "primary" {
  provider = google-beta
  name         = "cloud.firestore"
  ruleset_name = "projects/${google_project.default.project_id}/rulesets/${google_firebaserules_ruleset.version13.name}"
  project = google_project.default.project_id

  lifecycle {
        replace_triggered_by = [
            google_firebaserules_ruleset.version13
        ]
    }
}

resource "google_firebaserules_ruleset" "version13" {
  provider = google-beta
  source {
    files {
      content = <<EOT
rules_version = '2';
service cloud.firestore {
    match /databases/{database}/documents {
        match /users/{userId} {
            // User section where clients can write directly if authenticated
            match /personal/{document=**} {
                allow read, write: if request.auth != null && request.auth.uid == userId;
            }
            // Backend only section per user..........
            match /server/{document=**} {
      	        allow read, write: if false;
            }
        }
        // Backend only section for all users
        match /server/{document=**} {
            allow read, write: if false;
        }
    }
}
EOT
      name = "firestore.rules"
    }
  }
  project = google_project.default.project_id
}
```

I get the error: 
```
│ Error: Error creating Release: Resource already exists - apply blocked by lifecycle params: &beta.Release{Name:(*string)(0x140011afa30), RulesetName:(*string)(0x1400041b330), CreateTime:(*string)(0x1400041b3b0), UpdateTime:(*string)(0x1400041b4b0), Disabled:(*bool)(nil), Project:(*string)(0x140011afad0)}.
│
│   with module.unity-game.google_firebaserules_release.primary,
│   on ../unity-game-firebase-backend/main.tf line 103, in resource "google_firebaserules_release" "primary":
│  103: resource "google_firebaserules_release" "primary" {
```

If I change "cloud.firestore" to something else the `terraform apply` is successful. And I do see a new release for my Firestore Rules. But the release in the Firebase Console does not show the correct file content. The Firestore Rules release that terraform created just defaults to the first/default rules.

**Comment by rainshen49** [comment]
Hi there @robinryf! Try `terraform import google_firebaserules_release. primary projects/<project-id-or-numer>/releases/cloud.firestore`, and see if `terraform apply` works.

Since there is only one Firestore database instance (for now), the rules release for Firestore is always named "projects/<project-id-or-numer>/releases/cloud.firestore", using any other name won't go to the right place. I'll add it into the comment.

**Comment by robinryf** [comment]
@rainshen49 Thank you very much! It works now that TF knows about the online config.

I was looking at https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/firebaserules_release when implementing and just used the example 'prod/release' as name. That sent me on the wrong path. Sorry to intrude on this issue!

**Comment by rainshen49** [comment]
Hey @robinryf thanks for your feedback, I've updated the documentation to be not misleading. 

To maintainers: this issue can be marked as fixed now
