### ISSUE TITLE
Document updating resource documentation in the Registry

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#13237]
# Background

Internal Google contributors have asked about updating documentation a few times.

# What kind of contribution is this issue about?

Mostly handwritten resources, I'd imagine, but also general contributions

# Related PR(s), if any:

* N/A

# Details

Internal Google contributors have asked about updating documentation a few times. Having a specific section on https://googlecloudplatform.github.io/magic-modules/ should make the process more clear.

**Comment by SarahFrench** [comment]
I'd be happy to help with this if it's not earmarked for anyone already
