### ISSUE TITLE
Firebase Rules Release workflow needs an update option.

### ISSUE THREAD

**Issue by valls-lab** [hashicorp/terraform-provider-google#13236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* Terraform v1.3.6 (but the behavior is present in all versions)

### Affected Resource(s)

* `google_firebaserules_release` , https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release

### Description

- When creating a new ruleset release for Cloud Firestore in Firebase using Terraform, it will only show up in Firebase Console if the release name is `cloud.firestore`.
- If a different release name is used, the new rules won't appear in the Console as Firebase only shows the rules under the release name `cloud.firestore`.
- The issue comes when trying to specify the release name to `cloud.firestore`, as it will throw the error attached in the Debug Output section below, stating that the resource already exists.
- This happens because Terraform will first destroy the old release used, and then create the new one, instead of updating this new one if it already exists.
- With this current behavior, it is not currently possible to update the Firestore rules using Terraform, as they are always overwritten, and as you cannot specify the correct release, they never show up in the Console.

### Terraform Configuration Files

```tf
resource "google_firebaserules_release" "primary" {
  name         = "cloud.firestore"
  ruleset_name = "projects/my-project-name/rulesets/${google_firebaserules_ruleset.minimal.name}"
  project      = "my-project-name"
}

resource "google_firebaserules_ruleset" "minimal" {
  source {
    files {
      content = "service cloud.firestore {match /databases/{database}/documents { match /{document=**} { allow read, write: if false; } } }"
      name    = "firestore.rules"
    }
  }

  project = "my-project-name"
}
```

### Debug Output

```
google_firebaserules_release.primary: Destroying... [id=projects/PROJECT/releases/release]
google_firebaserules_release.primary: Destruction complete after 1s
google_firebaserules_release.primary: Creating...
╷
│ Error: Error creating Release: Resource already exists - apply blocked by lifecycle params
```

### Actual Behavior

1. Destroy the old release.
2. Create a new release. An error is returned if the new release already exists.

### Expected Behavior

1. Destroy the old release.
2. Create a new release OR `UPDATE` the release if it already exists.

### Steps to Reproduce

1. Create a release named i.e. `release`.
2. Create a new release but this time called `cloud.firestore`.
3. The `Resource already exists` will pop up.

**Comment by edwardmedia** [comment]
@valls-lab can you share you debug log?

Are you able to achieve the `Expected Behavior` with other approaches, like gcloud or console?

**Comment by juliensnz** [comment]
@edwardmedia when we do the same with the firebase cli, it works like a charm:

`yarn firebase deploy --only firestore:rules --project=my-project`

**Comment by edwardmedia** [comment]
@juliensnz I am not super clear about yarn command. Can you catch the debug log and share? I want to see how it communicates with the api.

**Comment by tafm** [comment]
@edwardmedia 

https://github.com/firebase/firebase-tools/blob/d4a2ce803f60fee4b8b10df34510e82fca4ce5dd/src/gcp/rules.ts#L240

First they try to update the release with a patch request, if the release doenst exist (at catch block) a post request is made to create

```
Enter a value: yes

google_firebaserules_ruleset.basic: Destroying... [id=projects/pitang-balcaonegociacao-dev/rulesets/88b125ca-5711-40b3-b2fa-50fa0a63c09c]
google_firebaserules_ruleset.basic: Destruction complete after 2s
google_firebaserules_ruleset.basic: Creating...
google_firebaserules_ruleset.basic: Creation complete after 3s [id=projects/pitang-balcaonegociacao-dev/rulesets/49058557-1804-4d28-a781-07f83b3e8aab]
google_firebaserules_release.primary2: Creating...
╷
│ Error: Error creating Release: Resource already exists - apply blocked by lifecycle params: &firebaserules.Release{Name:(*string)(0xc000d95650), RulesetName:(*string)(0xc000cf7f70), CreateTime:(*string)(0xc000cf7f80), UpdateTime:(*string)(0xc000cf7f90), Disabled:(*bool)(nil), Project:(*string)(0xc000d956d0)}. 
```

**Comment by edwardmedia** [comment]
@valls-lab I have tried below configs. Note the `name` is different. Both apply work fine. If this is the not steps to repro, can you share yours? 

1st apply
```tf
resource "google_firebaserules_release" "primary" {
  name         = "cloud.firestore"
  ruleset_name = "projects/my-project-name/rulesets/${google_firebaserules_ruleset.minimal.name}"
  project      = "my-project-name"
}

resource "google_firebaserules_ruleset" "minimal" {
  source {
    files {
      content = "service cloud.firestore {match /databases/{database}/documents { match /{document=**} { allow read, write: if false; } } }"
      name    = "firestore.rules"
    }
  }

  project = "my-project-name"
}
```

2nd apply
```tf
resource "google_firebaserules_release" "primary" {
  name         = "cloud.firestore.new"
  ruleset_name = "projects/my-project-name/rulesets/${google_firebaserules_ruleset.minimal.name}"
  project      = "my-project-name"
}

resource "google_firebaserules_ruleset" "minimal" {
  source {
    files {
      content = "service cloud.firestore {match /databases/{database}/documents { match /{document=**} { allow read, write: if false; } } }"
      name    = "firestore.rules"
    }
  }

  project = "my-project-name"
}
```

**Comment by edwardmedia** [comment]
@valls-lab is this still an issue?

**Comment by edwardmedia** [comment]
@valls-lab closing this assuming it is no longer an issue. Feel free to reopen otherwise
