### ISSUE TITLE
google_kms_key_ring_iam_binding with conditions example is wrong 

### ISSUE THREAD

**Issue by jayeye** [hashicorp/terraform-provider-google#13230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_kms_key_ring_iam_binding

### Terraform Configuration Files

```tf
resource "google_kms_key_ring_iam_binding" "this" {
  key_ring_id = google_kms_key_ring.this.id
  role        = "roles/editor"
  members = [
    "group:dev@example.com",
    "serviceAccount:sa@example.iam.gserviceaccount.com",
  ]
  condition {
    title = "test access to test keyring"
    expression = "resource.service == \"cloudkms.googleapis.com\" && resource.name.startsWith(\"${google_kms_key_ring.this.id}\")"
  }
}
```

### Expected Behavior

conditions should have been applied

### Actual Behavior
```
╷
│ Error: Error applying IAM policy for KMS KeyRing "projects/symbiont-io-scratch-cf0038ae/locations/global/keyRings/scratch-apollo-lib-test-cf0038ae": Error setting IAM policy for KMS KeyRing "projects/symbiont-io-scratch-cf0038ae/locations/global/keyRings/scratch-apollo-lib-test-cf0038ae": googleapi: Error 400: LintValidationUnits/BindingRoleAllowConditionCheck Error: Conditions can't be set on primitive roles., badRequest
│ 
│   with google_kms_key_ring_iam_binding.this,
│   on kms.tf line 7, in resource "google_kms_key_ring_iam_binding" "this":
│    7: resource "google_kms_key_ring_iam_binding" "this" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
n/a
### References
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_key_ring_iam
 erroneously claims that conditions may be applied. There is a closed issue that claims to have fixed this problem, but it did not.

* #0000

**Comment by edwardmedia** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/4252

`roles/editor` is not supported. 

`roles/cloudkms.admin` works

@jayeye can you check? 

I am going to update the document
