### ISSUE TITLE
google_api_gateway_api_config does not create the service files using grpc_services

### ISSUE THREAD

**Issue by keithhardaway** [hashicorp/terraform-provider-google#13245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.0.8
google beta provider version 4.45.0

### Affected Resource(s)

* google_api_gateway_api_config

### Terraform Configuration Files
```
resource "google_api_gateway_api" "skadi-api" {
  provider = google-beta
  project = google_project.data.project_id
  api_id = "dev-skadi-api"
}

resource "google_api_gateway_api_config" "skadi-api-config" {
  provider = google-beta
  project = google_project.data.project_id
  api = google_api_gateway_api.skadi-api.api_id
  api_config_id = "dev-skadi-api-config"

  grpc_services {
    file_descriptor_set {
      path = "skadi_api_descriptor.pb"
      contents = filebase64("api-gateway-files/skadi_api_descriptor.pb")
    }
  }
  managed_service_configs {
    path = "api_config.yaml"
     contents = base64encode(<<-EOF
      type: google.api.Service
      config_version: 3
      name: "*.apigateway.${google_project.data.project_id}.cloud.goog"
      title: API Gateway for Skadi
      apis:
        - name: tyr.skadi.service.v1beta1.SkadiService
      usage:
        rules:
        - selector: "*"
          # Allow non API-key based authentication
          allow_unregistered_calls: true
      authentication:
        providers:
          - id: vanir-service-account-auth
            jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/${google_service_account.vanir-training-bot.email}
            issuer: google_service_account.vanir-training-bot.email
          - id: user-account-auth
            jwks_uri: https://www.googleapis.com/oauth2/v3/certs
            issuer: https://accounts.google.com
            audiences: "<id>.apps.googleusercontent.com"
        rules:
          - selector: "*"
            requirements:
              - provider_id: vanir-service-account-auth
              - provider_id: user-account-auth
      backend:
        rules:
          - selector: "*"
            address: ${google_cloud_run_service.dev-skadi-server.status.0.url}

     EOF
     )
  }
  lifecycle {
    create_before_destroy = true
  }
}

resource "google_api_gateway_gateway" "skadi-api-gateway" {
  provider = google-beta
  project = google_project.data.project_id
  region  = "us-west2"
  api_config = google_api_gateway_api_config.skadi-api-config.id
  gateway_id = "dev-skadi-api-gateway"
}
```

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

This should create a working API Gateway Config. Terraform succeeds but the config it creates is missing all of the service definition files. 

When I create the config manually, there is 4 protobuf config files that define the service this API gateway config manages. 

### Actual Behavior

Terraform applies successfully but doesn't create the config correctly. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@keithhardaway can you share your debug log?

**Comment by keithhardaway** [comment]
@edwardmedia I think the problem isn't with Terraform but with the protobuf descriptor set file I'm using. I'm generating it with 
```
python -m grpc.tools.protoc -I ./googleapis -I ./ \
    --include_imports \
    --include_source_info \
    --proto_path=. \
    --descriptor_set_out=api_descriptor.pb \
    --python_out=generated_pb2 \
    --grpc_python_out=generated_pb2 \
    ./tyr/skadi/service/v1beta1/skadi.proto
```

The api config is created correctly when I create it from the protobuf project directory. If I copy the descriptor file, it doesn't work. I think it's not finding the protobuf files it needs.
