### ISSUE TITLE
Add Cross region replication option for AlloyDB

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#13251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_alloydb_cluster
* google_alloydb_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* [AlloyDB cross-region replication](https://cloud.google.com/alloydb/docs/cross-region-replication/about-cross-region-replication)
* b/266706386

**Comment by bschaatsbergen** [comment]
If possible, I would like to pick this up asap! :)

**Comment by bschaatsbergen** [comment]
I'm curious, I haven't seen such API behaviour before - to create a secondary AlloyDB cluster there seems to be a 'secondarycreate' API call.. https://cloud.google.com/alloydb/docs/reference/rest/v1/projects.locations.clusters/createsecondary

How would we go about implementing something like this, would this mean we need to create another AlloyDB resource, e.g. `google_alloydb_cluster_secondary` and `google_alloydb_instance_secondary` ? @trodge / @rileykarson

**Comment by bschaatsbergen** [comment]
Update: it seems like we need to create a `google_alloydb_cluster_secondary` and `google_alloydb_instance_secondary` -> 
![image](https://github.com/hashicorp/terraform-provider-google/assets/58337159/519702f6-e1bf-4912-8b5c-cd3b45d0fe54)

**Comment by bschaatsbergen** [comment]
I've prepped a PR which is ready for review, it introduces the 2 new resources:

- google_alloydb_cluster_secondary
- google_alloydb_instance_secondary

**Comment by rileykarson** [comment]
Hmm- we may want to change the create call in the current resource based on a flag than introduce entirely new resources. That limits the opportunity for drift between the resource schemas substantially, I'm not entirely sure which would be better. FYI @ScottSuarez as reviewer, we may want to work out with the service team how we want to support this.

**Comment by bschaatsbergen** [comment]
For maintainability it would be preferred if the service team could simply add a flag to the `create` call to instruct whether under the hood `createsecondary` should be called or not @rileykarson / @ScottSuarez. 

For the sake of supporting this the Terraform Google provider, I'm unsure how long such a request with the service team might take.

**Comment by bschaatsbergen** [comment]
Heya @rileykarson / @ScottSuarez, is there any update on how we could approach this?

**Comment by ScottSuarez** [comment]
Given how there is no way to manage the secondary cluster independently and that it is always tied to the first I'd propose the following:

1. Add a field `create_secondary<bool> - default false` with `url_param_only` or a `virtual_field` set. 
2. This field should be `default: false` and `input:true`
3. Add a `post_create` method that will call the api to create the secondary instance based on this parameter.


This is assuming the following from the API team.
1. Managing secondary clusters won't scale to be more nuanced.
2. This management style makes sense from the teams point of view and lines up with your design philosophy. (secondary is heavily tied to main).

**Comment by bschaatsbergen** [comment]
Right on, I'll get to this today @ScottSuarez

**Comment by KristoferNorwood** [comment]
I was able to create a secondary cluster using the [AlloyDB Cluster Terraform resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_cluster#example-usage---alloydb-secondary-cluster-basic), which is super nice. Thank you for all of your effort on that!

However, I noticed that the secondary instance was not created and I don't see a `SECONDARY` instance type attribute listed in the [AlloyDB Instance Terraform resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#instance_type). I was able to create the resource using the `alloydb create-secondary` [gcloud command](https://cloud.google.com/sdk/gcloud/reference/alloydb/instances/create-secondary), thankfully. 

I was wondering, there a plan to implement the Secondary instance type in the terraform resource?

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9203 was merged 4 days ago, that should release next Monday assuming no surprises (along with promotion in https://github.com/GoogleCloudPlatform/magic-modules/pull/9271, probably, and the week after if not). This just got released as piecemeal because we broke up the change into distinct parts.

**Comment by imrannayer** [comment]
Part of provider 5.5 release
