### ISSUE TITLE
Terraform Plan fails on compute engine default service account with leading numbers.

### ISSUE THREAD

**Issue by riveraja** [hashicorp/terraform-provider-google#13256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.6

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
module "gce_default_sa" {
  source       = "../../../service-accounts"
  account_id   = "39XXXXX34-compute"
  display_name = "Compute Engine default service account"
  description  = ""
}
```
Note: replaced numbers with X to hide real project_id number.

### Expected Behavior

No error if the existing resource is imported prior to running a `terraform plan`.
### Actual Behavior

```
│ Error: "account_id" ("39XXXXX34-compute") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
│ 
│   with module.gce_default_sa.google_service_account.service_accounts,
│   on ../../../service-accounts/resources.tf line 2, in resource "google_service_account" "service_accounts":
│    2:   account_id   = var.account_id
```
### Steps to Reproduce

1. `terraform import ...`
2. `terraform plan`

### Important Factoids

This is the default Compute engine service account created in GCP. Compute Engine default service accounts have the format `PROJECT_NUMBER-compute@developer.gserviceaccount.com`. Refer to this [link](https://cloud.google.com/compute/docs/access/service-accounts#default_service_account).

### References

* #3212

**Comment by riveraja** [comment]
@edwardmedia here you go

```tf
resource "google_service_account" "gce_user" {
  account_id = "393744148573-compute"
  project    = data.google_project.project.project_id
}
```


```
➜  service-accounts git:(master) ✗ terraform import google_service_account.gce_user projects/xxxxx-sandbox/serviceAccounts/39xxxxxxxx73-compute@developer.gserviceaccount.com
data.google_project.project: Reading...
data.google_project.project: Still reading... [10s elapsed]
data.google_project.project: Read complete after 19s [id=projects/xxxxx-sandbox]
google_service_account.gce_user: Importing from ID "projects/xxxxx-sandbox/serviceAccounts/39xxxxxxxx73-compute@developer.gserviceaccount.com"...
google_service_account.gce_user: Import prepared!
  Prepared google_service_account for import
google_service_account.gce_user: Refreshing state... [id=projects/xxxxx-sandbox/serviceAccounts/39xxxxxxxx73-compute@developer.gserviceaccount.com]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

➜  service-accounts git:(master) ✗ terraform plan
╷
│ Error: "account_id" ("39xxxxxxxx73-compute") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
│ 
│   with google_service_account.gce_user,
│   on main.tf line 48, in resource "google_service_account" "gce_user":
│   48:   account_id = "39xxxxxxxx73-compute"
│ 
╵
```

**Comment by edwardmedia** [comment]
@riveraja I see what you are trying to do. 

1) are you able to create an brand new service account via console  with leading numbers? Below is what I see from the console.
2) the account you were testing on is the default service account which is managed by gcp. Why do you want to import it to terraform? For other uses, would a data source be a choice for you?  

```
Service account ID must be between 6 and 30 characters.
Service account ID must start with a lower case letter, followed by one or more lower case alphanumerical characters that can be separated by hyphens.
```

**Comment by riveraja** [comment]
@edwardmedia The main purpose was to be able to control service accounts in terraform. It should be fine to leave it from TF management at this point it seems. Thanks!
