### ISSUE TITLE
Convert contributor-checker to use golang

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13254]
contributor-checker is one of the most frequently-changed parts of our CI pipeline, due to onboarding, vacations, etc. Changes to it frequently result in pipeline breakages due to the fiddly nature of the bash script.

We should make the following changes to improve the stability of our pipeline:

1. Convert this script to golang
2. Run the script directly on a standard golang image (instead of custom-building an image)
3. Add unit tests that run automatically in CI, preferably via github actions.

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/8708
