### ISSUE TITLE
Failing test(s): TestAccFirebaseAppleApp_*

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13267]
### Affected Resource(s)

* google_firebase_apple_app

Failure rate: 100% since 2022-11-22

Impacted tests:
- TestAccFirebaseAppleApp_firebaseAppleAppBasicExample
- TestAccFirebaseAppleApp_update
- TestAccFirebaseAppleApp_firebaseAppleAppFullExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/360401?buildTab=tests&expandedTest=-7026834308340857772

Message:

```
Skip deleting App "projects/ci-test-project-188019/iosApps/1:1067888929963:ios:68211e93cd713a4644dbee" due to deletion_policy: ""
testing_new.go:84: Error running post-test destroy, there may be dangling resources: FirebaseAppleApp still exists
```

```
Error: Error creating AppleApp: googleapi: Error 409: Requested entity already exists
```

**Comment by roaks3** [comment]
Note that these sweepers are not working properly either, so these resources are not being deleted on each test run and accumulating. For that reason, these resources may need to be cleaned up before solving the underlying issue.

**Comment by roaks3** [comment]
The deletion error might have been fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6911. Once the instance is cleaned up we can see if these failures come up again on the next run.

**Comment by roaks3** [comment]
I removed all of the old apps and did not see any errors last night. Will wait another day or two before closing, I'm particularly curious about the `Error: Error creating AppleApp: googleapi: Error 409: Requested entity already exists` for the `TestAccFirebaseAppleApp_update` test.

Related to this, created a PR to fix the sweepers: https://github.com/GoogleCloudPlatform/magic-modules/pull/7279

**Comment by roaks3** [comment]
Closing as these tests have all passed for the last 2 days (after 100% failure rate prior).
