### ISSUE TITLE
Failing test(s): TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceDualTokenExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13277]
### Affected Resource(s)

* google_network_services_edge_cache_service

Failure rate: 10% (3/30) since added 2022-11-16

Impacted tests:
- TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceDualTokenExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/360401?buildTab=tests&expandedTest=-1880046837500981326

Message:

```
Error: Error waiting to create EdgeCacheKeyset: Error waiting for Creating EdgeCacheKeyset: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 30m0s)
```

**Comment by roaks3** [comment]
Note: this has been passing for over a month, so we could consider just closing it. However, looking at the run times for the tests, we seem to be relatively close to this 30m timeout, so it's probably worth bumping it to maybe 40m (the timeout really should only be triggered as a fail-safe that indicates something has gone very wrong).

**Comment by roaks3** [comment]
Confirmed that this did occur once in Mar 2023, so bumping the timeout is probably what we want
