### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_withLabels

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13270]
### Affected Resource(s)

* google_dataproc_cluster

Failure rate: 100% since 2022-12-09

Impacted tests:
- TestAccDataprocCluster_withLabels

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/360401?buildTab=tests&expandedTest=-6423698170585265788

Message:

```
provider_test.go:315: Step 1/1 error: Check failed: Check 2/3 error: google_dataproc_cluster.with_labels: Attribute 'labels.%' expected "4", got "5"
```

**Comment by roaks3** [comment]
This was fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/7002
