### ISSUE TITLE
Terraform support for cross-project Sole Tenancy.

### ISSUE THREAD

**Issue by idyczko** [hashicorp/terraform-provider-google#13281]
# Background
Add terraform support for sharing sole tenant node groups across multiple projects.

# What kind of contribution is this issue about?
* MMv1-based resource NodeGroup

# Related PR(s), if any:

# Details

**Comment by idyczko** [comment]
I will work on this request.

**Comment by melinath** [comment]
Is this for google_compute_node_group? What fields are being added?

**Comment by idyczko** [comment]
Yes, this is for the node groups. We want to add the shareSettings field to enable sharing node groups across projects.
