### ISSUE TITLE
The resource `bigquery_data_transfer_config` documentation point to the non-existing role

### ISSUE THREAD

**Issue by robertfirek** [hashicorp/terraform-provider-google#13286]
The documentation for [`bigquery_data_transfer_config` ](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#example-usage---bigquerydatatransfer-config-scheduled-query) 

1. Suggests usage of the GCP role `roles/iam.serviceAccountShortTermTokenMinter` which no longer exists.

    Probably the role `roles/iam.serviceAccountTokenCreator` should be used instead of the old one. 

2. Does NOT explain why this role is required to create "scheduled query". 

### Terraform Version

Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.46.0

### Affected Resource(s)

* bigquery_data_transfer_config

### Terraform Configuration Files

```tf
data "google_project" "project" {
}

resource "google_project_iam_member" "permissions" {
  project = data.google_project.project.project_id
  role   = "roles/iam.serviceAccountShortTermTokenMinter"
  member = "serviceAccount:service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com"
}

resource "google_bigquery_data_transfer_config" "query_config" {
  depends_on = [google_project_iam_member.permissions]

  display_name           = "my-query"
  location               = "asia-northeast1"
  data_source_id         = "scheduled_query"
  schedule               = "first sunday of quarter 00:00"
  destination_dataset_id = google_bigquery_dataset.my_dataset.dataset_id
  params = {
    destination_table_name_template = "my_table"
    write_disposition               = "WRITE_APPEND"
    query                           = "SELECT name FROM tabl WHERE x = 'y'"
  }
}

resource "google_bigquery_dataset" "my_dataset" {
  depends_on = [google_project_iam_member.permissions]

  dataset_id    = "my_dataset"
  friendly_name = "foo"
  description   = "bar"
  location      = "asia-northeast1"
}
```

### Debug Output

Output when `google_bigquery_data_transfer_config` is created without adding the role to the service agent.
```
│ Error: Error creating Config: googleapi: Error 400: Precondition check failed.
│
│   with google_bigquery_data_transfer_config.transferx,
│   on bigquery.tf line 20, in resource "google_bigquery_data_transfer_config" "transferx":
│   20: resource "google_bigquery_data_transfer_config" "transferx" {
```

### Panic Output

N/A

### Expected Behavior

Examples from the documentation using the real values and explaining the reason of some constructs.

### Actual Behavior

Unusable examples, no explanation. 

### Steps to Reproduce

1. `terraform apply` :)

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#example-usage---bigquerydatatransfer-config-scheduled-query

**Comment by edwardmedia** [comment]
@robertfirek trying to see if the role exists or not. Can you share your debug log by apply your [code](https://github.com/hashicorp/terraform-provider-google/issues/13286#issue-1503167252)? Or you can run below api call. 

```
POST /v1/projects/yourprojecthere:getIamPolicy
Host: cloudresourcemanager.googleapis.com
{
 "options": {
  "requestedPolicyVersion": 3
 }
}
```

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/13191

**Comment by edwardmedia** [comment]
https://cloud.google.com/bigquery/docs/enable-transfer-service#cross-project_service_account_authorization

gcloud iam service-accounts add-iam-policy-binding service_account \
--member serviceAccount:service-project_number@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com \
--role roles/iam.serviceAccountTokenCreator

**Comment by robertfirek** [comment]
> https://cloud.google.com/bigquery/docs/enable-transfer-service#cross-project_service_account_authorization
> 
> gcloud iam service-accounts add-iam-policy-binding service_account --member serviceAccount:[service-project_number@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com](mailto:service-project_number@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com) --role roles/iam.serviceAccountTokenCreator

Can we somehow put the comment in the documentation leading to this explanation? It is not required to create the transfer within the same project but it is not easy to find why it is needed when you are not so experienced with BigQuery as I am.
