### ISSUE TITLE
Support `annotations` in `google_cloud_run_v2_service`

### ISSUE THREAD

**Issue by sorenhansendk** [hashicorp/terraform-provider-google#13302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add an option to add annotations on services like we have on the V1 ressource: `google_cloud_run_service`

It's pretty good when you need to add custom annotations OR annotations there not is supported by the provider.

In this example is the CPU boost feature not supported by the current implementation. The new annotations should of course be merged, with the annotations there is added by the implementation here.

### New or Affected Resource(s)

* google_cloud_run_v2_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "default" {
  name     = "cloudrun-service"
  location = "us-central1"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
    annotations = {
      "run.googleapis.com/startup-cpu-boost" = "true"
    }
  }
}
```

### References

* https://github.com/hashicorp/terraform-provider-google/pull/13166

**Comment by JhoLee** [comment]
I'm also looking forward it to be impleneted soon!🙃
I had to use `VPC Access` and `Filestore` in cloud run v2, but `google_cloud_run_service` doesn't support `VPC Access` (which is supporting annotations) so it could not mount filestore in another vpc).

**Comment by hao-nan-li** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/7023
