### ISSUE TITLE
cannot import google_data_catalog_taxonomy

### ISSUE THREAD

**Issue by bakuljajan** [hashicorp/terraform-provider-google#13307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google-beta v4.46.0

### Affected Resource(s)

* google_data_catalog_taxonomy

### Terraform Configuration Files

```tf
resource "google_data_catalog_taxonomy" "this" {
  provider               = google-beta
  region                 = "asia-southeast2"
  project                = GCP_PROJECT_ID
  display_name           = "Confidentiality"
  activated_policy_types = ["FINE_GRAINED_ACCESS_CONTROL"]
}
```

```sh
terraform import 'google_data_catalog_taxonomy.this' 'projects/GCP_PROJECT_ID/locations/asia-southeast2/taxonomies/7317744211956907xxx'
```

### Debug Output

https://gist.github.com/bakuljajan/24319f7df8ac557cd97e885df11c95a6

### Expected Behavior

terraform state successfully imported

### Actual Behavior

error stating fetching project for Taxonomy: project: required field is not set

```sh
╷
│ Error: Error fetching project for Taxonomy: project: required field is not set
│ 
│ 
╵
```

### Steps to Reproduce

1. `terraform import 'google_data_catalog_taxonomy.this' 'projects/GCP_PROJECT_ID/locations/asia-southeast2/taxonomies/7317744211956907xxx'`

### References

* #0000

**Comment by edwardmedia** [comment]
@bakuljajan is `GCP_PROJECT_ID` a placeholder? I see it everywhere. If yes, what did you put? By using below config, it seems working fine with me. Can you try?

```tf
resource "google_data_catalog_taxonomy" "basic_taxonomy" {
  provider = google-beta
}
```

tf import google_data_catalog_taxonomy.basic_taxonomy projects/myprojectt/locations/us/taxonomies/920673625810712345

**Comment by edwardmedia** [comment]
Add [google_access_context_manager_access_level](https://github.com/hashicorp/terraform-provider-google/issues/13181)  not exactly same but similar

**Comment by bakuljajan** [comment]
yes, it is a placeholder @edwardmedia. I've tried using both project id and project number but got the same error `Error fetching project for Taxonomy: project: required field is not set`

**Comment by bakuljajan** [comment]
I've tried your example but got the same response
![image](https://user-images.githubusercontent.com/88089627/209486574-6b5e6a93-115a-409d-a956-01d72d59f988.png)

**Comment by edwardmedia** [comment]
@bakuljajan yeah, you need to replace myproject in my example with the value found below if not do so. 

```tf
data "google_project" "project" {
}

output "project_id" {
  value = data.google_project.project.project_id
}
```

If that does not work, can you add the environment value below before you run import again and share the log here?

```
export TF_LOG=DEBUG
```

**Comment by bakuljajan** [comment]
Okay. Let me create an experiment project first. I need to use a placeholder because of the error from our production google project.

**Comment by bakuljajan** [comment]
Still has the same error. Please find below screenshots and log
![image](https://user-images.githubusercontent.com/88089627/209515066-40acfd79-4a2f-476d-bc0a-92783ca36fd4.png)
![image](https://user-images.githubusercontent.com/88089627/209515114-618d0f70-21fa-4f2e-81ff-9ae18b38a9f8.png)

https://gist.github.com/bakuljajan/84648bd4dda864a2bcc8bb956f9614c2

**Comment by edwardmedia** [comment]
@bakuljajan is the resource valid? `projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917`

Can you share the result for below command?

```
gcloud data-catalog taxonomies describe projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917  --log-http
```

**Comment by bakuljajan** [comment]
Yes it is valid @edwardmedia. I've attached the screenshot from the bq dashboard in previous comment.

Will sent you the command output after holiday 🍻

**Comment by bakuljajan** [comment]
Here is the command output @edwardmedia 

```sh
gcloud data-catalog taxonomies describe projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917  --log-http
=======================
==== request start ====
uri: https://datacatalog.googleapis.com/v1/projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917?alt=json
method: GET
== headers start ==
b'X-Goog-User-Project': b'xpr-krdv-infra-sbx-2240'
b'accept': b'application/json'
b'accept-encoding': b'gzip, deflate'
b'authorization': --- Token Redacted ---
b'content-length': b'0'
b'user-agent': b'google-cloud-sdk gcloud/392.0.0 command/gcloud.data-catalog.taxonomies.describe invocation-id/78819342e11e47cf9c0f369761caee2a environment/None environment-version/None interactive/True from-script/False python/3.10.4 term/xterm-256color (Macintosh; Intel Mac OS X 22.2.0)'
== headers end ==
== body start ==

== body end ==
==== request end ====
---- response start ----
status: 200
-- headers start --
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Sat, 31 Dec 2022 04:17:57 GMT
Server: ESF
Transfer-Encoding: chunked
Vary: Origin, X-Origin, Referer
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
-- headers end --
-- body start --
{
  "name": "projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917",
  "displayName": "test-policy",
  "policyTagCount": 1,
  "taxonomyTimestamps": {
    "createTime": "2022-12-26T06:56:08.772Z",
    "updateTime": "2022-12-26T06:56:08.772Z"
  }
}

-- body end --
total round trip time (request+response): 1.709 secs
---- response end ----
----------------------
displayName: test-policy
name: projects/xpr-krdv-infra-sbx-2240/locations/us/taxonomies/4975932235129467917
policyTagCount: 1
taxonomyTimestamps:
  createTime: '2022-12-26T06:56:08.772Z'
  updateTime: '2022-12-26T06:56:08.772Z'
```

**Comment by bakuljajan** [comment]
Do you have any info about the release of this fix @edwardmedia @SarahFrench?
