### ISSUE TITLE
google_compute_instance error

### ISSUE THREAD

**Issue by fabiokfouri** [hashicorp/terraform-provider-google#13316]
### Affected Resource(s)

* google_compute_instance

I have received this message.

"Provider produced inconsistent final plan. This is a bug in the provider, which should be reported in the provider's own issue tracker."

This error is an intermittent error. Sometime raise an exception and sometimes not.

See my code.

```
locals {
    SHA = sha1(
              join("", 
                concat(
                    [for f in fileset(path.module, "../src/**") : filesha1(f)],
                )
              )
          )
}

resource "google_compute_instance" "my_vm" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  tags = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image ="ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network = "default"

    access_config {
    }
  }

  service_account {
    email  = google_service_account.default.email
    scopes = ["cloud-platform"]
  }

  metadata_startup_script = "echo ${local.SHA} >> /home/sha.log"

}
```
I have inserted the SHA value to trigger the rebuild the VM when  ome code have changed. The documentation **[link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata_startup_script) **have mentioned that the metadata_startup_script when is changed forces the instance to be recreated.

When have a new SHA, sometimes it raises an exception .

**Comment by edwardmedia** [comment]
@fabiokfouri can you share the debug log?

**Comment by edwardmedia** [comment]
@fabiokfouri is this still an issue?

**Comment by edwardmedia** [comment]
@fabiokfouri closing this assuming it is no longer an issue. Feel free to reopen otherwise
