### ISSUE TITLE
Add enable_binary_authorization option to google_cloud_run_service

### ISSUE THREAD

**Issue by jramos** [hashicorp/terraform-provider-google#13312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently the Binary Authorization of the Cloud Run service that is created is set to **disabled** by default. For better security in large teams it is advisable to turn on the Binary Authorization.

Possible workarounds include:

1. Manually enabling the Binary Authorization by running:
   `gcloud run services update ${name_of_cloud_run_service} --binary-authorization=default`
   _Problem_: Manual work defeats the purpose of terraform. Moreover, it might not be allowed by compliance regulations to set things manually.
3. Using the terraform-google-gcloud module to run the above command.
   _Problem_: The module would require service account credentials which can not simply be given due to compliance regulations.
4. Using a VM instantiated via terraform that has the cloud console enabled to run the command.
   _Problem_: Running a VM or similar for the purpose of a single line of code is inefficient in terms of building and pricing.
5. Using `google_org_policy_policy` to set an organization policy to allow `run.allowedBinaryAuthorizationPolicies`.
   _Problem_: The module would require orgPolicy admin permissions which can not simply be given due to compliance regulations.

### New or Affected Resource(s)

* google_cloud_run_service
* enable_binary_authorization

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"

  enable_binary_authorization = true

  template {
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### References

b/272368545

**Comment by yanweiguo** [comment]
Binary authorization setting is controlled by the `annotations` on service level. We updated the document to include what annotation keys can be used. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service

@melinath I think we can close this.
