### ISSUE TITLE
Add activity logging to identity platform (tenant) configuration

### ISSUE THREAD

**Issue by laurensknoll** [hashicorp/terraform-provider-google#13326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

You can enable activity logging for Identity platform (tenants) to log user sign-ins, etc. How to do so is specified here: https://cloud.google.com/identity-platform/docs/activity-logging

To enable activity logging, you supply the monitoring config object to the identity platform (tenant) config API: https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects.tenants/patch
```json
{
  "monitoring": {
    "requestLogging": {
      "enabled":true
    }
  }
}
```

As this attribute is not yet available in the Terraform resources, you can't configure activity logging using Terraform.

### New or Affected Resource(s)

* google_identity_platform_config
* google_identity_platform_tenant

### Potential Terraform Configuration

```tf
resource "google_identity_platform_config" "default" {
  project = google_project.default.project_id
  ...

  # Optional block, when not specified, defaults to false.
  monitoring {
    request_logging {
      enabled = true
    }
  }
}
```

### References

* Enabling activity logging: https://cloud.google.com/identity-platform/docs/activity-logging
* Project-level API spec: https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects/updateConfig
* Tenant-level API spec: https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects.tenants/patch

b/299601114

**Comment by gleichda** [comment]
@hao-nan-li This one can be closed. I had a formatting issue in the comment so the issues did not get closed.
