### ISSUE TITLE
Error: Error creating AlertPolicy: The filter contains unknown resource type: gce_route

### ISSUE THREAD

**Issue by Asmokin11** [hashicorp/terraform-provider-google#13349]
I am trying to create alert policies, but some of the resource types are not supported. I am getting below errors:

`│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="logging.googleapis.com/user/custom-role-iam" AND resource.type="iam_role"": The filter contains unknown resource type: iam_role
│
│   with module.m_oscare[0].google_monitoring_alert_policy.oscare_r_custom_alert["2"],
│   on modules/m_oscare/main.tf line 15, in resource "google_monitoring_alert_policy" "oscare_r_custom_alert":
│   15: resource "google_monitoring_alert_policy" "oscare_r_custom_alert" {
│
╵`

`│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="logging.googleapis.com/user/vpc-route" AND resource.type="gce_route"": The filter contains unknown resource type: gce_route
│
│   with module.m_oscare[0].google_monitoring_alert_policy.oscare_r_custom_alert["6"],
│   on modules/m_oscare/main.tf line 15, in resource "google_monitoring_alert_policy" "oscare_r_custom_alert":
│   15: resource "google_monitoring_alert_policy" "oscare_r_custom_alert" {
│
╵`

There seems to be a compulsion to include `resource.type` field when creating alert policies with terraform. However, the `resource.type` field is not included when I create the policy in console and import it in terraform.

How do I get around this issue? Is there a way I can generalize the filter to use all resource types instead of targeting a specific type?

**Comment by edwardmedia** [comment]
@Asmokin11 is this the resource you are using? Does the example work for you? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy

**Comment by Asmokin11** [comment]
Hello Edward, yes I am using the same resource. I am trying to create 6 alert policies, but only 3 of them get created and I get the same error for other 3 policies --> seems like terraform is not familiar with the `resource.type` which I am using in `filter` field.

The 3 policies which get successfully created have `resource.type=global` and `resource.type=gce_network`.
However, I get error when I set the type to "gce_route", "iam_role" or "gce_firewall_rule".

**Comment by edwardmedia** [comment]
@Asmokin11 can you share your debug log so I can take close look?

**Comment by Asmokin11** [comment]
@edwardmedia I have uploaded the debug.log in my [repo](https://github.com/Asmokin11/terraform/blob/main/terraform-debug.log)

**Comment by edwardmedia** [comment]
@Asmokin11 thanks for the log. I do see the errors as you mentioned [above](https://github.com/hashicorp/terraform-provider-google/issues/13349#issue-1511952520) 

`unknown resource type: iam_role` seems to be clear. To answer your question, terraform does not own those rules. You may want to checkout the [api](https://cloud.google.com/monitoring/alerts/using-alerting-api) doc.

Below are some examples for your review
https://cloud.google.com/monitoring/alerts/types-of-conditions#examples

**Comment by Asmokin11** [comment]
@edwardmedia Thanks for the suggestion, however since terraform does not own these rules is there a way I can omit the `resource.type` section from my alert policy?  or substitute it with something else? I tried with `resource.type=global` but it does not give me the required results.

When I try to remove the `resource.type` filter from the alert policy it tells me that it is required:
`╷
│ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="logging.googleapis.com/user/custom-role-iam"": must specify a restriction on "resource.type" in the filter; see "https://cloud.google.com/monitoring/api/resources" for a list of available resource types.
│
│   with module.m_oscare[0].google_monitoring_alert_policy.oscare_r_custom_alert["2"],
│   on modules/m_oscare/main.tf line 15, in resource "google_monitoring_alert_policy" "oscare_r_custom_alert":
│   15: resource "google_monitoring_alert_policy" "oscare_r_custom_alert" {
│`

**Comment by edwardmedia** [comment]
@Asmokin11 what are your required results? Are you able to create them via gcloud? If yes, you may share its debug log (attach --http-log to your gcloud) and let me take a look.

**Comment by Asmokin11** [comment]
@edwardmedia you are correct, I am not able to create the alert-policy with gcloud command when `resource.type="gce_route"` is set, I get this [error](https://github.com/Asmokin11/terraform/blob/main/gcloud-with-gce_route.log)
Also, when I remove the `resource.type` field in gcloud, I get this [error ](https://github.com/Asmokin11/terraform/blob/main/gcloud-without-gce_route.log) which is similar to what I am getting with terraform.

It seems, I am only able to create the alert policy when I am in the GCP console and do not provide the "gce_route" filter : [example](https://github.com/Asmokin11/terraform/blob/main/alert-without-resource-type.PNG).

This looks like the API from google is not allowing terraform to create the policies.
