### ISSUE TITLE
`google_container_cluster` uses invalid defaults if the cluster is enrolled in a release channel when using NAP defaults 

### ISSUE THREAD

**Issue by renescheepers** [hashicorp/terraform-provider-google#13341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google-beta v4.46.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  provider   = google-beta

  name     = "testing-rene-nap-default"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1

  cluster_autoscaling {
    enabled             = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 1
      maximum       = 100
    }

    resource_limits {
      resource_type = "memory"
      minimum       = 1
      maximum       = 100
    }

    # When this block is omitted, auto upgrade & auto repair is configured correctly.
    auto_provisioning_defaults {
    }
  }
}
```

### Expected Behavior

<img width="911" alt="image" src="https://user-images.githubusercontent.com/38879286/209318716-58c088e9-c415-4837-910e-68cbbae1d6f2.png">

Auto upgrade & repair enabled when enrolled in release channel.

### Actual Behavior

<img width="897" alt="image" src="https://user-images.githubusercontent.com/38879286/209318321-27a52d4c-3078-4e84-a9df-dcd3394d41ad.png">

Auto upgrade & Auto repair should default to true when enrolled in a release channel. Its also not possible to fix this issue using only the GCP console. 

When trying to change it in GCP console, not possible. Not that even though the checkbox is checked, its not enabled!
<img width="523" alt="image" src="https://user-images.githubusercontent.com/38879286/209318413-119cb621-f2ea-4191-b398-05dac4b3f685.png">

This will cause NAP to be broken in GKE:
```
(combined from similar events): NodeAutoprovisioning: attempt to create node group https://www.googleapis.com/compute/v1/projects/XXXXX/zones/us-central1-c/instanceGroups/nap-n1-standard-8-gpu2-4ys5l06s-XXX failed: googleapi: Error 400: Auto_upgrade must be true when release_channel REGULAR is set., badRequest
```

### Steps to Reproduce

1. `terraform apply`

### References

* b/298501809

**Comment by rileykarson** [comment]
This appears to be an issue with GKE's validation, not with Terraform. Stealing some snippets from a past execution of our `TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey` test:


When we send

```
  "autoscaling": {
   "autoprovisioningNodePoolDefaults": {
    "bootDiskKmsKey": "projects/my-project/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1",
    "diskSizeGb": 100,
    "diskType": "pd-standard",
    "imageType": "COS_CONTAINERD",
    "management": {},
    "minCpuPlatform": "automatic",
    "serviceAccount": "default",
    "upgradeSettings": {}
   },
```


We get back:

```
"autoscaling": {
  "enableNodeAutoprovisioning": true,
  "resourceLimits": [
   {
    "resourceType": "cpu",
    "maximum": "2"
   },
   {
    "resourceType": "memory",
    "maximum": "2048"
   }
  ],
  "autoscalingProfile": "BALANCED",
  "autoprovisioningNodePoolDefaults": {
   "oauthScopes": [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/cloud-platform"
   ],
   "serviceAccount": "default",
   "upgradeSettings": {
    "strategy": "SURGE"
   },
   "management": {},
   "diskSizeGb": 100,
   "diskType": "pd-standard",
   "bootDiskKmsKey": "projects/my-project/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1",
   "imageType": "COS_CONTAINERD"
  }
 },
```


This would normally mean that the `management` subvalues are set to `false`, since that's what omitting a field in JSON means, but when inspecting a node pool I see:

```
   "management": {
    "autoUpgrade": true,
    "autoRepair": true
   },
```

**Comment by renescheepers** [comment]
@rileykarson the provider wouldn't send `"management": {},` to GKE when using the empty `auto_provisioning_defaults`, it would send:
```
management { 
"autoUpgrade": false,
"autoRepair": false
}
```

**Comment by shuyama1** [comment]
@renescheepers Sorry for the late follow up on this issue. If I understand correctly, the bug report here is whether explicitly specifying empty block `auto_provisioning_defaults {}` results in different values for Auto upgrade & repair. Are you still running into this issue now?

I tested it just now with the same configs (except `auto_provisioning_defaults`):
with the empty `auto_provisioning_defaults` block:
```
resource "google_container_cluster" "primary" {
  provider   = google-beta

  name     = "tf-test-nap-default"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1

  cluster_autoscaling {
    enabled             = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 1
      maximum       = 100
    }

    resource_limits {
      resource_type = "memory"
      minimum       = 1
      maximum       = 100
    }

    # When this block is omitted, auto upgrade & auto repair is configured correctly.
    auto_provisioning_defaults {
    }
  }
}
```
and without the empty `auto_provisioning_defaults` block:
```
resource "google_container_cluster" "primary" {
  provider   = google-beta

  name     = "tf-test-nap-non"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1

  cluster_autoscaling {
    enabled             = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 1
      maximum       = 100
    }

    resource_limits {
      resource_type = "memory"
      minimum       = 1
      maximum       = 100
    }
  }
}
```

I end up having Auto upgrade & Auto repair enabled for both clusters. I wonder if the issue has already been resolved now.

with the empty `auto_provisioning_defaults` block:
<img width="813" alt="Screenshot 2023-11-30 at 6 43 00 PM" src="https://github.com/hashicorp/terraform-provider-google/assets/87669292/66c5a977-b7e3-4b48-b7c5-f2af2f9d3de6">

without the empty `auto_provisioning_defaults` block:
<img width="803" alt="Screenshot 2023-11-30 at 6 42 48 PM" src="https://github.com/hashicorp/terraform-provider-google/assets/87669292/e390d5a0-d983-4126-8d49-0505a9fe057c">

**Comment by shuyama1** [comment]
I'm assuming the API behavior has changed and this is no longer an issue. Closing this issue now but feel free to comment or reopen it if this error still occurs. Thanks!
