### ISSUE TITLE
Data Fusion does not save the full network ID to the state, causing destruction on next apply

### ISSUE THREAD

**Issue by ivgenys** [hashicorp/terraform-provider-google#13348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.1.9

### Affected Resource(s)

* google_data_fusion_instance

### Terraform Configuration Files

It's part of a larger inline module + being called through terragrunt, but "plain"/"direct" terraform would reproduce the same issue since it's a bug in the provider version 4.47.0
```tf
resource "google_data_fusion_instance" "instance" {
  provider                      = google-beta
  name                          = var.name
  project                       = var.project_id
  description                   = var.description
  region                        = var.region
  type                          = var.type
  enable_stackdriver_logging    = true
  enable_stackdriver_monitoring = true
  labels                        = var.labels
  version                       = var.datafusion_version
  options                       = var.options
  private_instance              = true
  dataproc_service_account      = var.dataproc_service_account

  network_config {
    network = var.network
    ip_allocation = "${google_compute_global_address.data_fusion_private_ip_alloc.address}/${google_compute_global_address.data_fusion_private_ip_alloc.prefix_length}"
  }
}
```

### Debug Output

```tf
-/+ resource "google_data_fusion_instance" "instance" {
      ~ api_endpoint                  = "https://datafusion-soar-deshino-dot-euw2.datafusion.googleusercontent.com/api" -> (known after apply)
      ~ create_time                   = "2022-12-27T12:24:56.288097967Z" -> (known after apply)
      - enable_rbac                   = false -> null
      ~ gcs_bucket                    = "gs://df-12234631967847591772-peoalu4f4ii63ezxaizbbqaaaa" -> (known after apply)
      ~ id                            = "projects/soar-deshino/locations/europe-west2/instances/datafusion" -> (known after apply)
      - labels                        = {} -> null
        name                          = "datafusion"
      - options                       = {} -> null
      ~ p4_service_account            = "service-642778116825@gcp-sa-datafusion.iam.gserviceaccount.com" -> (known after apply)
      ~ service_account               = "cloud-datafusion-management-sa@g9068f98580b7e2ae-tp.iam.gserviceaccount.com" -> (known after apply)
      ~ service_endpoint              = "https://datafusion-soar-deshino-dot-euw2.datafusion.googleusercontent.com" -> (known after apply)
      ~ state                         = "RUNNING" -> (known after apply)
      + state_message                 = (known after apply)
      ~ tenant_project_id             = "g9068f98580b7e2ae-tp" -> (known after apply)
      ~ update_time                   = "2022-12-27T12:37:49.428975329Z" -> (known after apply)
      ~ version                       = "6.7.2" -> (known after apply)
      + zone                          = (known after apply)
        # (7 unchanged attributes hidden)

      ~ network_config {
          ~ network       = "vpc" -> "projects/soar-deshino/global/networks/vpc" # forces replacement
            # (1 unchanged attribute hidden)
        }
    }
```

### Expected Behavior

1. Applying datafusion for the first time, `network_config.network` variable populated: `projects/soar-deshino/global/networks/vpc`. It should save to the state the value `projects/soar-deshino/global/networks/vpc`.
2. Running terraform plan, without changes to the terraform code, no changes should be performed on the data fusion instance.

### Actual Behavior

1. Running `terraform apply` for the first time, `network_config.network` variable populated: `projects/soar-deshino/global/networks/vpc`. It saves to the state the value `vpc` instead of `projects/soar-deshino/global/networks/vpc`.
3. Running `terraform plan`, it detects that the network changed (although it didn't) and destroys + recreates the datafusion instance

### Steps to Reproduce

1. Use google provider version 4.47.0
2. Create a Data Fusion instance: set the `network_config.network` param to a specific network and apply terraform
3. Run `terraform plan` immediately to see the upcoming destruction.

**Comment by ivgenys** [comment]
correction: not specific to the latest provider version (happens in 4.46.0 as well), and also happens on both google and google-beta providers

**Comment by edwardmedia** [comment]
@ivgenys  I can't repro this. Can you share your debug log with all the api requests and responses?

**Comment by edwardmedia** [comment]
@ivgenys is this still an issue?
