### ISSUE TITLE
BigQuery Routine Unsupported language type Javascript

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [hashicorp/terraform-provider-google#13346]
### Terraform Version
1.3.6

### Affected Resource(s)

* google_google_bigquery_routine

### Terraform Configuration Files

```
resource "google_bigquery_routine" "extract_kv_pair" {
  dataset_id = "test"
  routine_id     = "test_extract_kv_pairs"
  routine_type = "PROCEDURE"
  language = "JAVASCRIPT"
  arguments {
    name = "input_json_str"
    data_type = "{\"typeKind\" :  \"STRING\"}"
  }
  definition_body = "<code>"
}
```

### Debug Output

```
│ Error: Error creating Routine: googleapi: Error 501: Not Implemented: Unsupported language type JAVASCRIPT, notImplemented
│
│   with google_bigquery_routine.extract_kv_pair["bamboo_partitioned"],
│   on main.tf line 41, in resource "google_bigquery_routine" "extract_kv_pair":
│   41: resource "google_bigquery_routine" "extract_kv_pair" {
```
### Expected Behavior

I expect the resource to be created in BigQuery

### Actual Behavior

An error happened and nothing is created

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine#language

https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions

BQ expected JS and not JAVASCRIPT as the language definition (and JS is not accepted by the resource as an input value)

**Comment by lucienfregosibodyguard** [comment]
@edwardmedia I boostraped a PR in magic module if you want
https://github.com/GoogleCloudPlatform/magic-modules/pull/7048

**Comment by edwardmedia** [comment]
Cool. Thank you. Let me assign this issue to you then

**Comment by lucienfregosibodyguard** [comment]
@edwardmedia my test are failing and I don't have permission to get the debug trace ..
I tried in local and every tests are green, could you have a look please ? :)

**Comment by edwardmedia** [comment]
@lucienfregosibodyguard I tested the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine#example-usage---big-query-routine-json) and it works fine. It's language is `JAVASCRIPT`. I am not sure what happened to yours. 

```tf
resource "google_bigquery_dataset" "test" {
    dataset_id = "dataset_id"
}

resource "google_bigquery_routine" "sproc" {
  dataset_id = google_bigquery_dataset.test.dataset_id
  routine_id     = "tf_test_routine_id%{random_suffix}"
  routine_type = "SCALAR_FUNCTION"
  language = "JAVASCRIPT"
  definition_body = "CREATE FUNCTION multiplyInputs return x*y;"
  arguments {
    name = "x"
    data_type = "{\"typeKind\" :  \"FLOAT64\"}"
  } 
  arguments {
    name = "y"
    data_type = "{\"typeKind\" :  \"FLOAT64\"}"
  }

  return_type = "{\"typeKind\" :  \"FLOAT64\"}"
}
```

**Comment by lucienfregosibodyguard** [comment]
Oh ok it's on me I used `procedure` as a routine type and not `SCALAR_FUNCTION`

Will close the Issue then
