### ISSUE TITLE
Add validation to google_recaptcha_enterprise_key testing key options

### ISSUE THREAD

**Issue by lancehudson** [hashicorp/terraform-provider-google#13343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Testing keys with a fixed score should be set between 0 and 1 (1 being least risk).  https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1/projects.keys

Right now, both the provider and Google's API allow it to be set outside of that range. Ideally, Google adds validation to their API, but adding it to the provider would allow for a suitable error message to be issued during plan instead of waiting until an attempted apply.

### New or Affected Resource(s)

* google_recaptcha_enterprise_key

### Potential Terraform Configuration

```tf
resource "google_recaptcha_enterprise_key" "AlwaysPass" {
  display_name = "QA Key Always 0.7"

  testing_options {
    testing_score = 0.7
  }

  web_settings {
    integration_type = "SCORE"
    allowed_domains  = "test.com"
  }
}
```

### References

* https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1/projects.keys#testingoptions
* https://cloud.google.com/recaptcha-enterprise/docs/faq#id_like_to_run_automated_tests_with_what_should_i_do

**Comment by rileykarson** [comment]
Hey! Given this is not validated on the API, we're hesitant about validating it in Terraform. While I think the validation makes sense- and is likely an omission on the API's part- we've been burned by adding inaccurate validations in the past. Marking `upstream`.

**Comment by Cory-Kramer** [comment]
Developer from the reCAPTCHA Enterprise team here. We are fixing this upstream server side, should be rolled out within the next couple weeks (rollout schedule affected by the holidays).

**Comment by Cory-Kramer** [comment]
This fix has been fully rolled out upstream, this issue may now be closed.
