### ISSUE TITLE
Importing a subnet resource with `region` field set doesn't register the region field  

### ISSUE THREAD

**Issue by samveen** [hashicorp/terraform-provider-google#13356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.3.6
on linux_arm64
+ provider registry.terraform.io/hashicorp/google v4.47.0
```
### Affected Resource(s)

* `module.subnetworks.google_compute_subnetwork.default-asia-east2`

### Terraform Configuration Files
` tail -n 11  google/subnetworks/compute_subnetwork.tf `
```tf
resource "google_compute_subnetwork" "default-asia-east2" {
  name                       = "default"
  ip_cidr_range              = "10.170.0.0/20"
  region                     = "asia-east2"
  network                    = data.terraform_remote_state.common.outputs.network_default_link
  private_ip_google_access   = "false"
  private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS"
  purpose                    = "PRIVATE"
  stack_type                 = "IPV4_ONLY"
}
```

### `tf plan`

```
  # module.subnetworks.google_compute_subnetwork.default-asia-east2 will be created
  + resource "google_compute_subnetwork" "default-asia-east2" {
      + creation_timestamp         = (known after apply)
      + external_ipv6_prefix       = (known after apply)
      + fingerprint                = (known after apply)
      + gateway_address            = (known after apply)
      + id                         = (known after apply)
      + ip_cidr_range              = "10.170.0.0/20"
      + ipv6_cidr_range            = (known after apply)
      + name                       = "default"
      + network                    = "https://www.googleapis.com/compute/v1/projects/domestic-feline-696969/global/networks/default"
      + private_ip_google_access   = false
      + private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS"
      + project                    = (known after apply)
      + purpose                    = "PRIVATE"
      + region                     = "asia-east2"
      + secondary_ip_range         = (known after apply)
      + self_link                  = (known after apply)
      + stack_type                 = "IPV4_ONLY"
    }

```

### `terraform import module.subnetworks.google_compute_subnetwork.default-asia-east2 default`
```
module.firewall.data.terraform_remote_state.common: Reading...
module.subnetworks.data.terraform_remote_state.common: Reading...
module.firewall.data.terraform_remote_state.common: Read complete after 0s
module.subnetworks.data.terraform_remote_state.common: Read complete after 0s
module.subnetworks.google_compute_subnetwork.default-asia-east2: Importing from ID "default"...
╷
│ Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
│ 
│ 
╵
```

### Expected Behavior

the resource should be imported into the state file. 

### Actual Behavior

I get an Error about the region parameter being missing. 

### Steps to Reproduce

1. `terraform import module.subnetworks.google_compute_subnetwork.default-asia-east2 default`

**Comment by edwardmedia** [comment]
@samveen have you tried commands like below ones?

$ terraform import google_compute_subnetwork.default projects/{{project}}/regions/{{region}}/subnetworks/{{name}}
$ terraform import google_compute_subnetwork.default {{project}}/{{region}}/{{name}}
$ terraform import google_compute_subnetwork.default {{region}}/{{name}}

**Comment by samveen** [comment]
@edwardmedia  If I set the default region, the region used is the default region instead of the value for the region field, which leads to incorrect state when I check with `tf plan`. 

Thus I removed the default region from this module, and expecting that the region field for every resource would be honored, as shown in the docs at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork

The above fixed my `tf plan`,  but then `tf import` fails.

**Comment by edwardmedia** [comment]
@samveen yes, I think terraform does not pick up all the information from the resource definition while running import.

Glad `{{region}}/{{name}}` works for you. Closing the issue now

**Comment by samveen** [comment]
> @samveen yes, I think terraform does not pick up all the information from the resource definition while running import.

@edwardmedia Is this by design or an oversight? From how I expect things to work, this looks like an oversight rather than design. If so, this issue needs a fix rather than quick closure.
