### ISSUE TITLE
Request for datasource for `google_compute_region_instance_group_manager`

### ISSUE THREAD

**Issue by kutysam** [hashicorp/terraform-provider-google#13363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

With regards to https://github.com/hashicorp/terraform-provider-google-beta/pull/5002
Datasource was created for `google_compute_instance_group_manager`

However, we are missing a datasource for `google_compute_region_instance_group_manager`
The resource source is at here: 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager

I believe both codes are very similar. Probably the only difference is that region instance group manager requires a region.

### New or Affected Resource(s)

* Need datasource `google_compute_region_instance_group_manager`

### References

Related PR: https://github.com/hashicorp/terraform-provider-google-beta/pull/5002
Resource for datasource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager

b/338675264

**Comment by AarshDhokai** [comment]
b/264013514

**Comment by jimmybigcommerce** [comment]
This is a glaring omission.

**Comment by julienfig** [comment]
hello,
any news about this datasource ?
BR

**Comment by askubis** [comment]
I will try to work on it next monday.
