### ISSUE TITLE
block `node_pool_auto_config` not accepted in resource `google_container_cluster`

### ISSUE THREAD

**Issue by hkarimi-bc** [hashicorp/terraform-provider-google#13362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```shell
$ terraform -version
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.47.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
```
All are in the latest release as of this post.

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "default" {
  project = var.project_id
  name = var.cluster_name
  location = var.google_zone

  node_pool_auto_config {
    network_tags {
      tags = ["test-network-tag"]
    }
  }

  min_master_version = data.google_container_engine_versions.supported.latest_master_version
  initial_node_count = 1
  node_locations = [
    var.node_zone,
  ]
  remove_default_node_pool = true

```

### Debug Output

```shell
│ Error: Unsupported block type
│
│   on gke-cluster/main.tf line 25, in resource "google_container_cluster" "default":
│   25:   node_pool_auto_config {
│
│ Blocks of type "node_pool_auto_config" are not expected here.
╵
```

### Panic Output

None

### Expected Behavior

The terraform plan should have compiled, along with adding network tags to the cluster/nodes. `node_pool_auto_config` should be an allowed block in the resource `google_container_cluster` according to:
- [the terraform docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster.html#node_pool_auto_config)
- [the source code](https://github.com/hashicorp/terraform-provider-google/blob/7c54260832e353dbd6e0d5340edc81e2c625727f/google/resource_container_cluster_test.go#L4554)

### Actual Behavior

The plan failed to compile with the message that blocks of type `node_pool_auto_config` are not expected in resource `google_container_cluster`. 

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

If I remove the `node_pool_auto_config` block, the plan completes and I can apply it successfully. Ultimately, I would like to apply `network_tags` to the node pool that I later attach to this cluster.

### References

* #0000

**Comment by edwardmedia** [comment]
@hkarimi-bc this feature seems still in [beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_pool_auto_config). Can you try that?

**Comment by hkarimi-bc** [comment]
Thanks for looking into this @edwardmedia. I tried using the google-beta provider and terraform was able to run the `plan` and `apply` functions, but the subsequent node pool did not have the network tags attached. Fortunately, I was able to solve the issue with trial and error runs.

It turns out that the `tag` list under the `node_config` block for the `google_container_node_pool` resource will add the tags to `Network Tags` under `Metadata`, just as I wanted:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/91922313/210383702-ed38c3ac-bf97-427d-9ebe-802cbd8a3a12.png">

Here's the corresponding terraform script:

## main.tf
```terraform
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.47"
    }
  }
}

resource "google_container_cluster" "default" {
  provider = google
  project = var.project_id
  name = "simple-network-tags"
  location = "${var.region}-b"
  network = var.network
  subnetwork = var.sub_network

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  initial_node_count = 1
  node_locations = ["${var.region}-c"]
  remove_default_node_pool = true
}


resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "tagged-pool"
  cluster    = google_container_cluster.default.id
  initial_node_count = 1
  node_locations = ["${var.region}-c"]

  node_config {
    machine_type = "e2-standard-2"
    disk_size_gb = 100
    disk_type = "pd-standard"
    tags = ["simple-tag"]  # gets added as a network tag under metadata
  }
}
```

The support for the `node_config` block is not clear from the documentation in [`google_container_node_pool`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#node_config), which points to the [`google_container_cluster`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config) resource. Neither of those pages clarify how `tags` can be part of the `node_config` block and ultimately will be interpreted as a network tag. I'm glad this works on terraform, but I'd like to request an update to the docs to clarify it's use. In the mean tine, the script above should be a helpful reference.

**Comment by edwardmedia** [comment]
@hkarimi-bc I see tags in one [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-the-default-node-pool). Agreed it is not super clear, and we should improve it in the future versions

Glad you found the right way to use `node_pool_auto_config`. Closing this issue accordingly.
