### ISSUE TITLE
google_firebase_apple_app documentation incorrectly specifies bundle_id field as optional

### ISSUE THREAD

**Issue by Vidxyz** [hashicorp/terraform-provider-google#13386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Documentation for the google_firebase_apple_app](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_apple_app) terraform resource indicates that `bundle_id` is optional, however, when the following terraform block is applied, it results in an error

```
resource "google_firebase_apple_app" "my-ios-app" {
  provider = google-beta
  project = var.project_id
  display_name = "My iOS App"
}
```

```
Error: Error creating AppleApp: googleapi: Error 400: Request contains an invalid argument.
```

When the parameter `bundle_id` is added in, the `terraform apply` is successful

```
resource "google_firebase_apple_app" "my-ios-app" {
  provider = google-beta
  project = var.project_id
  display_name = "My iOS App"
  bundle_id = "my.ios.app"
}
```

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Affected Resource(s)

* google_firebase_apple_app

### Suggested Solution
[Update documentation for the `bundle_id` parameter](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_apple_app#bundle_id) to make it clear that it is **not** an optional value

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_apple_app#bundle_id
* b/277380978

**Comment by mraouffouad** [comment]
I'm wondering how the "Optional" desc made it to the docs? The PR that added this resource did not introduce it: https://github.com/GoogleCloudPlatform/magic-modules/pull/6630/files

**Comment by rainshen49** [comment]
I'll work on a fix.
