### ISSUE TITLE
Composer - New Feature Trigger , Snapshot 

### ISSUE THREAD

**Issue by krishna4ldw** [hashicorp/terraform-provider-google#13397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add new features to TF module 
1) triggerer 
https://cloud.google.com/composer/docs/composer-2/scale-environments#triggerer-count
2) Snapshot schedule
https://cloud.google.com/composer/docs/composer-2/save-load-snapshots#save-snapshot

### New or Affected Resource(s)

* google_composer_environment

### References
https://cloud.google.com/composer/docs/composer-2/scale-environments#triggerer-count
https://cloud.google.com/composer/docs/composer-2/save-load-snapshots#save-snapshot

* #0000

**Comment by rileykarson** [comment]
Note: The Terraform documentation suggests that snapshots may intentionally be excluded. Trigger seems to be valid to add, however.

**Comment by melinath** [comment]
It looks like triggerer is now supported (and the linked docs page includes a Terraform example.) https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#triggerer
