### ISSUE TITLE
Add `waf_settings` block to `google_recaptcha_enterprise_key`

### ISSUE THREAD

**Issue by gtsorbo** [hashicorp/terraform-provider-google#13401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add `waf_settings` block, including `waf_service` and `waf_feature` atrributes, as described in the [API reference](https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1/projects.keys#wafsettings). This is required for proper integration with Cloud Armor.

### New or Affected Resource(s)

* google_recaptcha_enterprise_key

### Potential Terraform Configuration

```tf
resource "google_recaptcha_enterprise_key" "primary" {
  display_name = "session-token-key"

  project = var.project_id

  waf_settings {
    waf_service = "CA"
    waf_feature = "SESSION_TOKEN"
  }

  web_settings {
    integration_type  = "SCORE"
    allow_all_domains = true
  }
}
```

### References

* https://github.com/GoogleCloudPlatform/terraform-google-waap/issues/5

**Comment by Cory-Kramer** [comment]
I am currently working on adding a `waf_settings` field to the `google_recaptcha_enterprise_key` resource. It should be available in the near future.

**Comment by Cory-Kramer** [comment]
This new field has been fully rolled, this issue may now be closed.

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9565
