### ISSUE TITLE
google_cloud_identity_group_memberships : error 403

### ISSUE THREAD

**Issue by bukzor-sentryio** [hashicorp/terraform-provider-google#13409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.47.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Affected Resource(s)

* `google_cloud_identity_group_memberships`

### Terraform Configuration Files

```tf
terraform {
  required_version = "~> 1.3.6"
  required_providers {
    google = { version = "~> 4.47.0" }
    null   = { version = "~> 3.2.1" }
  }
}

provider "google" {
  project = "scratch-buckevan"
}

resource "google_project_service" "cloudidentity" {
  service = "cloudidentity.googleapis.com"
}

# to get these weird ids, use:
#   gcloud identity groups describe --format 'value(name)' "$GROUP_EMAIL"
data "ggoogle_cloud_identity_group_membershipsoogle_cloud_identity_group_memberships" "_" {
  group      = "groups/123eab45c6defghi"
  depends_on = [google_project_service.cloudidentity]
}


resource "null_resource" "_" {
  triggers = {
    members = jsonencode(data.google_cloud_identity_group_memberships._.memberships)
  }
}
```

### Debug Output

https://gist.github.com/bukzor-sentryio/957147ac24bdb6834e4a438218221eb8

### Panic Output

N/A

### Expected Behavior

I expected to get a similar list of members as what I can get with `gcloud --log-http identity groups memberships list --group-email="$GROUP_EMAIL" --format=json --view=full`. Log available here: https://gist.github.com/bukzor-sentryio/957147ac24bdb6834e4a438218221eb8

### Actual Behavior

GCP API rejects the request with a 403 error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

See the two logs I posted: https://gist.github.com/bukzor-sentryio/957147ac24bdb6834e4a438218221eb8

Note that the two GCP API access in both logs is nearly identitical, but only one fails. The only difference I can see is the lack of `X-Goog-User-Project` in the (failing) terraform-generated request.

My theory is that the fix is to add `X-Goog-User-Project` to the request. Especially because:

   1. The error message suggests this as a solution.
   2. I've found more than a few solved 403 issues in the google tf provider that were fixed by adding X-Goog-User-Project to the request.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/11865
* https://github.com/hashicorp/terraform-provider-google/issues/4059

**Comment by edwardmedia** [comment]
@bukzor-sentryio below data source seems weird. 

```tf
# to get these weird ids, use:
#   gcloud identity groups describe --format 'value(name)' "$GROUP_EMAIL"
data "ggoogle_cloud_identity_group_membershipsoogle_cloud_identity_group_memberships" "_" {
  group      = "groups/123eab45c6defghi"
  depends_on = [google_project_service.cloudidentity]
}
```

```tf
# to get these weird ids, use:
#   gcloud identity groups describe --format 'value(name)' "$GROUP_EMAIL"
data "google_cloud_identity_group_memberships" "something" {
  group      = "groups/123eab45c6defghi"
  depends_on = [google_project_service.cloudidentity]
}
```

**Comment by edwardmedia** [comment]
@bukzor-sentryio is this still an issue?

**Comment by edwardmedia** [comment]
@bukzor-sentryio assume this is no longer an issue
