### ISSUE TITLE
google_cloud_run_v2_service basic example uses the `binary_authorization` advanced feature.

### ISSUE THREAD

**Issue by steren** [hashicorp/terraform-provider-google#13416]
On [Example Usage - Cloudrunv2 Service Basic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#example-usage---cloudrunv2-service-basic)

The sample uses `binary_authorization`:

```
resource "google_cloud_run_v2_service" "default" {
  name     = "cloudrun-service"
  location = "us-central1"
  ingress = "INGRESS_TRAFFIC_ALL"

  binary_authorization {
    use_default = true
    breakglass_justification = "Some justification"
  }
  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
  }
}
```

This is not expected. `binary_authorization` is an advanced feature that should not be used in a basic example.

The basic example should be:

```
resource "google_cloud_run_v2_service" "default" {
  name     = "cloudrun-service"
  location = "us-central1"
  ingress = "INGRESS_TRAFFIC_ALL"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
  }
}
```

**Comment by edwardmedia** [comment]
@steren what change would you suggest?

**Comment by steren** [comment]
I gave what the example should be in my above comment.

I can send a PR if you want.

**Comment by steren** [comment]
I've sent https://github.com/GoogleCloudPlatform/magic-modules/pull/7093 and https://github.com/hashicorp/terraform-provider-google/pull/13418
