### ISSUE TITLE
Cloud Run service image version management

### ISSUE THREAD

**Issue by jeremad** [hashicorp/terraform-provider-google#13435]
I have the following cloud run service:

```tf
resource "google_cloud_run_v2_service" "my_service" {
  name     = "my-service"
  location = "some-region"
  template {
    containers {
      image = "gcr.io/my-repo/my-service:v1"
    }
  }

  lifecycle {
    ignore_changes = [
      client,
      client_version,
      template[0].containers[0].image,
    ]
  }
}
```

I use the `lifecyle.ignore_changes` because I want to handle the deployment in the CI/CD of the code repository of `my-service`, this terraform configuration lives in another repo, with all my infrastructure. I currently use `gcloud` to deploy a new version.

An issue arise when I want to deploy a change in my infrastructure repo, say a new environment variable, simultaneously with a new version of my service. If It goes:
1. `gcr.io/my-repo/my-service:v1` is deployed
1. `terraform plan -out plan` -> plans the new env var with image `gcr.io/my-repo/my-service:v1`
1. `gcr.io/my-repo/my-service:v2` is deployed
1. `terraform apply plan` -> the service is deployed with image `gcr.io/my-repo/my-service:v1` and the new env var

Because of me using `ignore_changes` it goes fine, while with the usual terraform workflow it would fail. And I want it to fail, I do not want to silently downgrade.

This is obviously ma bad for using `ignore_changes` for something it's not meant to.

But my question is, is it possible to manage a Cloud Run service image outside of terraform, without risking this kind of unattented behavior. Best regards.

**Comment by edwardmedia** [comment]
@jeremad gcloud is the tool you can use to manage outside of terraform, which you have already used. I am not aware of other tools available. Keep in mind, applying terraform will bring your infra state back to what your config defined. Does this make sense?

**Comment by jeremad** [comment]
Hello, thank you for your response, I fully understand your respond. I was just wandering if there was any way to tell terraform, *in a safe way* to ignore the image version. The lifecycle thing I described, does do that, but not a safe way.

**Comment by edwardmedia** [comment]
@jeremad unfortunately I don't think there is a way in a terraform feature that can handle this at least with my knowledge. Close the question then.
