### ISSUE TITLE
google_compute_shared_vpc_service_project takes both project id and project number as acceptable input

### ISSUE THREAD

**Issue by sindhurav28** [hashicorp/terraform-provider-google#13436]
**Community Note**
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

**Description**
google_compute_shared_vpc_service_project takes both project id and project number as acceptable input. However, the project number is automatically replaced with project id in the Google Cloud API, this made Terraform to re-plan on the next run as it tried to change it from Google cloud set project id to project number. 

**Issue**
Even though the resource is successfully created, terraform state file is not maintained and terraform re-plans the resource creation at every new run even though the resource is already existing.

Request: Would it be possible for Terraform to either mark this occurrence as an error (Or) fail the deployment as this is not expected. (Or) Plan for a change from project id to project number (tracked as a modification and not addition)?

**New or Affected Resource(s)**
google_compute_shared_vpc_service_project

**Comment by slevenick** [comment]
Unfortunately this is a known and painful behavior of some APIs. We can't do the translation between number -> project ID or project ID -> number without making additional API calls which we don't want to do.

Terraform's failure mode here is to show the permanent diff on the field, which is probably the best we can do. Erroring out earlier in the process would be more painful, especially if the resource is successfully created, we may end up abandoning a working resource.

I don't think we have a good answer here. The best solution would be for the API to return the identifier of the project in the way specified by the client, but that doesn't seem to be happening.

I would recommend always using project_id as the project identifier in the provider except for resources that only work with project_number (there are a couple)
