### ISSUE TITLE
google_certificate_manager_certificate - self_managed block is not sensitive

### ISSUE THREAD

**Issue by ruanda** [hashicorp/terraform-provider-google#13450]
According to the documentation (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/certificate_manager_certificate#self_managed) self_managed block should be sensitive and not visible in plan. google-provider v4.48.0 does not mark this property as sensitive and I can see pem_private_key in clear text in plan.

**Comment by edwardmedia** [comment]
@ruanda I see below attributes are set sensitive. Don't you want the key to be visible? We want to hide its value, for sure

https://github.com/hashicorp/terraform-provider-google/blob/576870f22e71111b58c4195be5a2cec7c4327d89/google/resource_certificate_manager_certificate.go#L194

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_certificate_manager_certificate.go#L216

**Comment by ruanda** [comment]
Looks like only `private_key_pem` and `certificate_pem` are set to sensitive. Both are also marked as deprecated in favor of `pem_certificate` and `pem_private_key` which are not sensitive. I followed the docs and used new attributes and got surprised with private key visible in plan. Anyway, I don't think `certificate_pem` and `pem_certificate` should be sensitive, it does contain public cert after all.

**Comment by rileykarson** [comment]
@ruanda: If I've got this right, you'd prefer we unmark `self_managed` as sensitive in that case, is that right? For the deprecated subfields we should preserve it imo (and just remove those fields when we get the chance in a major version- they aren't supposed to be there).

That will mean the bottom-level fields that are currently sensitive will remain sensitive, while the top-level field's documentation will no longer suggest all its subfields are sensitive.

**Comment by ruanda** [comment]
Let me clarify
1. `private_key_pem` and `pem_private_key` should both be sensitive. They contain private key, so definitely sensitive data.  For now only depracated `private_key_pem` is sensitive. 
2. `certificate_pem` and `pem_certificate` contains public cert, I don't think they should be sensitive. For now `certificate_pem` is sensitive.
3. `self_managed` block is sensitive but I am not sure what it means exactly as my plan showed me diff in plain text for `pem_private_key` in `self_managed` block. Probably should not be sensitive as it doesn't work the way it is described in the documentation and marking it as sensitive is misleading.

**Comment by rileykarson** [comment]
Ah, I'd missed that one field should likely be sensitive while the other shouldn't. Thanks!

I'd prefer we keep `certificate_pem` sensitive as it's not clear whether removing it requires a major version or not, and the value of removing it is fairly low. It _probably_ doesn't require one. 

That means our delta would be:

* remove sensitive from `self_managed` since adding it to a parent field doesn't appear to do anything
* add sensitive to `pem_private_key`
