### ISSUE TITLE
google_sql_database_instance: cannot import `deletion_protection` flag

### ISSUE THREAD

**Issue by wata727** [hashicorp/terraform-provider-google#13452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.48.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "main" {
  name             = "main-instance"
  database_version = "POSTGRES_14"
  region           = "us-central1"

  deletion_protection = false

  settings {
    tier = "db-f1-micro"
  }
}
```

### Expected Behavior

`terraform import google_sql_database_instance.main main-instance` imports `deletion_protection` as `false` to a state.

### Actual Behavior

The `deletion_protection` is always imported as `true`.

### Steps to Reproduce

1. Run `terraform apply`

2. Run `terraform show` and check the value of the `deletion_protection`

```
$ terraform show
# google_sql_database_instance.main:
resource "google_sql_database_instance" "main" {
    available_maintenance_versions = []
    connection_name                = <REDACTED>
    database_version               = "POSTGRES_14"
    deletion_protection            = false
    first_ip_address               = <REDACTED>
    id                             = "main-instance"

... <snip> ...
```

3. Run `terraform state rm google_sql_database_instance.main`

4. Run `terraform import google_sql_database_instance.main main-instance`

5. Run `terraform show` and check the value of the `deletion_protection` again

```
$ terraform show
# google_sql_database_instance.main:
resource "google_sql_database_instance" "main" {
    available_maintenance_versions = []
    connection_name                = <REDACTED>
    database_version               = "POSTGRES_14"
    deletion_protection            = true
    first_ip_address               = <REDACTED>
    id                             = "main-instance"
```

### References

- https://github.com/GoogleCloudPlatform/magic-modules/pull/3954

**Comment by wata727** [comment]
Perhaps the issue is that the importer always set `deletion_protection` to `true` here:
https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_sql_database_instance.go#L1644-L1646

I was investigating if it could be fixed with `d.Get("deletion_protection")`, but it may be that only the ID can be referenced with `schema.ResourceData`... Is this correct?
https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.24.1/website/docs/plugin/sdkv2/resources/import.mdx#importer-state-function

**Comment by edwardmedia** [comment]
@wata727 do you see [deletion_protection_enabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection_enabled)

for `deletion_protection` below is from its Note:

```
This flag only protects instances from deletion within Terraform. To protect your instances from accidental deletion across all surfaces (API, gcloud, Cloud Console and Terraform), use the API flag settings.deletion_protection_enabled
```

**Comment by wata727** [comment]
Yes. I understand that there is a workaround using `deletion_protection_enabled`.
However, `deletion_protection_enabled`, which is a Cloud SQL feature, is irrelevant to this issue. It's counter-intuitive behavior, and I would like to fix it if possible.

**Comment by edwardmedia** [comment]
@wata727 `deletion_protection` is at the Terraform layer. The API has no knowledge about it. When we do import, terraform pulls down every attributes at the server, where `deletion_protection` is not part of the attributes at the server. That is why. Does this make sense?

**Comment by wata727** [comment]
Ah, that makes sense. I understand that `deletion_protection` will show up in the diff if you run `terraform plan` after the import:

```
Terraform will perform the following actions:

  # google_sql_database_instance.main will be updated in-place
  ~ resource "google_sql_database_instance" "main" {
      ~ deletion_protection            = true -> false
        id                             = "main-instance"
        name                           = "main-instance"
        # (12 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

My use case can be achieved if I run `terraform apply` after import. Thank you for taking the time to address this issue.

**Comment by rileykarson** [comment]
To supplement what @edwardmedia mentions in https://github.com/hashicorp/terraform-provider-google/issues/13452#issuecomment-1381418424 & to clarify the root cause here a little more: the field isn't present in the API & we have no knowledge of it *and* the provider has no access to the user's configuration during an import. During an import we create a resource state based on the import id and API state, forcing us to pick a value arbitrarily for unreadable fields. In this case (as we do for most cases) we set the default value by default, opting to lean on the side of addtl protection for end users' resources, at the cost of a little extra friction for cases like yours!
