### ISSUE TITLE
State refresh hangs on deleted storage bucket

### ISSUE THREAD

**Issue by angstwad** [hashicorp/terraform-provider-google#13464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected Resource(s)

* `google_storage_bucket`

### Terraform Configuration Files

N/A

### Debug Output

Running a plan or an apply hangs during state refresh phase when buckets are deleted outside of Terraform.  With verbose logs from the provider, looks like n this case it considers 404 to be a retryable error.  Is this intended behavior?  It would seem that a bucket returning a 404 on state refresh means it does not exist and should be re-created.

Example lines from logs:

```
2023-01-11T14:38:50.921-0700 [INFO]  provider.terraform-provider-google_v3.90.1_x5: 2023/01/11 14:38:50 [DEBUG] Retry Transport: Stopping retries, last request failed with non-retryable error: googleapi: got HTTP response code 404 with body: HTTP/2.0 404 Not Found
...
2023-01-11T14:38:50.925-0700 [INFO]  provider.terraform-provider-google_v3.90.1_x5: 2023/01/11 14:38:50 [DEBUG] Retry Transport: Returning after 1 attempts: timestamp=2023-01-11T14:38:50.921-0700
2023-01-11T14:38:50.925-0700 [INFO]  provider.terraform-provider-google_v3.90.1_x5: 2023/01/11 14:38:50 [DEBUG] Dismissed an error as retryable. Retry 404s for bucket creation - googleapi: Error 404: The specified bucket does not exist., notFound: timestamp=2023-01-11T14:38:50.921-0700
```

### Expected Behavior

Bucket is marked for recreation

### Actual Behavior

HTTP GET loop w/ backoff on a 404'ing object.

### Steps to Reproduce

1. Create bucket with TF
2. Delete bucket outside of TF
3. Rerun plan or apply

b/275607155

**Comment by sonic1981** [comment]
I can confirm this functionality also

```
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.48.0
+ provider registry.terraform.io/hashicorp/google-beta v4.48.0
```

**Comment by edwardmedia** [comment]
GCS buckets and service accounts retry all 404s, likely due to consistency issues in the API. Given that's intentional behaviour we probably need to do a fairly thorough investigation before changing that.

**Comment by angstwad** [comment]
> Tf doesn't even say this is happening though. It just hangs and you need turn tracing on to see what and why its hung on. Can we at least display some better information? Or even time out?

Yeah, agreed - this is less than ideal . Not to increase scope here but it would see that any resource for which the provider considers 404 to be retrayable (even for legitimate reasons like eventual consistency of resources) would result in this behavior - where state refresh hangs _without indicating what an underlying cause may be unless debug/trace logs are enabled_.  So, to reiterate the issue:

1. Terraform-created buckets are _not recreated_ if deleted outside of Terraform 
2. Subsequent Terraform plans applies hang - _break_ - unless the bucket is manually re-created
3. No logs/output are given to a user to indicate an underlying problem; Terraform silently engages in a `GET`-loop; users have to set `TF_LOG=debug` and interpret the logs

All of this - IMHO - defies user expectations and sets up a  bad experience.  

Just winging it here with some options/ideas:

1. Document this (expected?) behavior in the provider docs
2. Additional API endpoint that can respond authoritatively about the state (existence) of a given bucket (shorter window of eventual consistency)
3. Set a timeout for HTTP get loop (5 minutes?) after which the resource is considered gone and marked for recreation
4. using the current API (for which it's presumed to have a longer replication period/eventual consistency)

**Comment by sharkannon** [comment]
Is there a potential workaround for this? Cause our TF config is in a bad state because of this issue (Someone deleted a bunch of unused buckets manually, then updated TF afterwards)

**Comment by sharkannon** [comment]
Did find a workaround, had to recreate the resources manually then let TF delete them.

**Comment by cen1** [comment]
This needs some more visibility tbh.. it essentially block tf plan for 15? minutes (or more if you deleted more than 1) and needs a state rm to solve after checking the trace logs. It is an abysmal experience..
