### ISSUE TITLE
tpgtools only supports string -> string maps

### ISSUE THREAD

**Issue by molerus** [hashicorp/terraform-provider-google#13469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Magic modules generators only support maps where both the key and the value are strings. There is an existing TODO to change it.

### New or Affected Resource(s)

* google_vmwareengine_private_cloud
* google_vmwareengine_cluster

### References

https://github.com/GoogleCloudPlatform/magic-modules/blob/c2608fa90cc696a0ed426626334e7ee5467d87dc/tpgtools/templates/serialization.go.tmpl#L164

**Comment by melinath** [comment]
I'm not entirely sure whether this would be possible to do; Terraform maps are string -> string only. But we could possibly approximate something? We'd need at least one example of a field that needs this behavior.

**Comment by rileykarson** [comment]
@slevenick you fixed this, right?

**Comment by slevenick** [comment]
Yes, this was fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/10039.

Use of this feature requires a per-map override that sets the key name. See https://github.com/GoogleCloudPlatform/magic-modules/pull/10039/files#diff-dbbb52ee94ecce1ab59369bd8fcf3b283625728bd72738df2e13ef400c8185dfR28 for reference
