### ISSUE TITLE
Terraform import of a google_certificate_manager_certificate doesn't import its dns_authorizations

### ISSUE THREAD

**Issue by anthonydurot** [hashicorp/terraform-provider-google#13487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

$terraform -v

Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.48.0

### Affected Resource(s)

* google_certificate_manager_certificate

### Terraform Configuration Files

```tf
resource "google_certificate_manager_certificate" "wildcard_certificate" {
  name        = "test-certificate"
  scope       = "DEFAULT"
  managed {
    domains = [
      "my.domain",
      "*.my.domain"
      ]
    dns_authorizations = [
      google_certificate_manager_dns_authorization.dns_authorization.id,
    ]
  }
}

resource "google_certificate_manager_dns_authorization" "dns_authorization" {
  name        = "my_dns_authorization"
  domain      = "my.domain"
}

```

### Debug Output

https://gist.github.com/anthonydurot/62f692f131504c463134b08dbc2643e6

### Panic Output

n/a

### Expected Behavior

As you can see here, I have a dns_authorization in my certificate :

```console

$gcloud certificate-manager certificates describe test-certificate --format="value(managed.dnsAuthorizations)"

projects/<MY_PROJECT>/locations/global/dnsAuthorizations/my_dns_authorization
```

So, I should find this dnsAuthorization in my Terraform resource : 

```console

terraform state show 'google_certificate_manager_certificate.wildcard_certificate'
# google_certificate_manager_certificate.wildcard_certificate:
resource "google_certificate_manager_certificate" "wildcard_certificate" {
    id      = "projects/<MY_PROJECT>/locations/global/certificates/test-certificate"
    labels  = {}
    name    = "test-certificate"
    project = "<MY_PROJECT>"

    managed {
        authorization_attempt_info = [
            {
                details        = ""
                domain         = "my.domain"
                failure_reason = ""
                state          = "AUTHORIZED"
            },
            {
                details        = ""
                domain         = "*.my.domain"
                failure_reason = ""
                state          = "AUTHORIZED"
            },
        ]
        dns_authorizations         = [
          projects/<MY_PROJECT>/locations/global/dnsAuthorizations/my_dns_authorization // <- Here
        ]
        domains                    = [
            "my.domain",
            "*.my.domain",
        ]
        provisioning_issue         = []
        state                      = "ACTIVE"
    }

    timeouts {}
}
```

### Actual Behavior

dns_authorizations is empty : 

```console
terraform state show 'google_certificate_manager_certificate.wildcard_certificate'
# google_certificate_manager_certificate.wildcard_certificate:
resource "google_certificate_manager_certificate" "wildcard_certificate" {
    id      = "projects/<MY_PROJECT>/locations/global/certificates/test-certificate"
    labels  = {}
    name    = "test-certificate"
    project = "<MY_PROJECT>"

    managed {
        authorization_attempt_info = [
            {
                details        = ""
                domain         = "my.domain"
                failure_reason = ""
                state          = "AUTHORIZED"
            },
            {
                details        = ""
                domain         = "*.my.domain"
                failure_reason = ""
                state          = "AUTHORIZED"
            },
        ]
        dns_authorizations         = []
        domains                    = [
            "my.domain",
            "*.my.domain",
        ]
        provisioning_issue         = []
        state                      = "ACTIVE"
    }

    timeouts {}
}
```

### Steps to Reproduce

1. Create a dns_authorization, and a certificate : 
  * gcloud certificate-manager dns-authorizations create "my_dns_authorization" --domain="my.domain"
  * gcloud certificate-manager certificates create test-certificate --domains="my.domain,*.my.domain" --dns-authorizations="my_dns_authorization"

2. Terraform init the previous code

3. Import the certificate
  * $TF_LOG=DEBUG terraform import 'google_certificate_manager_certificate.wildcard_certificate' test-certificate

### Important Factoids

I'm authenticating as a user.

**Comment by edwardmedia** [comment]
There were changes around this pair of resources. 
https://github.com/GoogleCloudPlatform/magic-modules/pull/6004
