### ISSUE TITLE
While changing the root_password for MSSQL server it is destroying the instance and then creating the new instance.

### ISSUE THREAD

**Issue by sk251319** [hashicorp/terraform-provider-google#13499]
### Community Note
Expected behavior
Terraform should do not destroy the instance if we are changing the root-password.

###  Observed behavior
When I am changing the root_password for the existing MSSQL instance rather that doing the in-place edit it is destroying the instance and then recreating the instance.

we can change root_password using GCP console and gcloud utility and it is not recreating the instance but using terraform it is recreating the instance.

### Terraform Version

Provider version 
google      = "~> 3.61.0"
google-beta = "~> 3.61.0"

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
# provider version
#  google      = "~> 3.61.0"
# google-beta = "~> 3.61.0".



### Steps to Reproduce


1. `Create MSSQL instance with root_password through terraform`
2. `Update root_password  of mssql sql instance and do apply using terraform on the same instance `
3. `Rather than creating a new root_password for it will destroy the existing MSSQL instance will create a new MSSQL instance and root_password`


### References
https://github.com/terraform-google-modules/terraform-google-sql-db/issues/405

**Comment by sk251319** [comment]
thanks for the link. really apricate it. 
I hope we will be getting the solution soon. any tentative date when we will get the solution available.

**Comment by robert-nemet** [comment]
We are having the same issue. Thanks for starting work on this.

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/7136
