### ISSUE TITLE
negative_caching_policy throwing Unsupported argument error

### ISSUE THREAD

**Issue by jimmybyrum** [hashicorp/terraform-provider-google#13497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.48.0
+ provider registry.terraform.io/hashicorp/google-beta v4.48.0
```

### Affected Resource(s)

* google_compute_backend_bucket

### Terraform Configuration Files

```tf
resource "google_compute_backend_bucket" "..." {
  name             = "..."
  bucket_name      = "..."
  enable_cdn       = true
  compression_mode = "AUTOMATIC"

  cdn_policy {
    cache_mode       = "CACHE_ALL_STATIC"
    negative_caching = true

    negative_caching_policy = {
      code = 404
      ttl  = 0
    }
  }
}
```

### Debug Output

```log
2023-01-16T11:11:27.448+0100 [ERROR] vertex "google_compute_backend_bucket.<...>" error: Unsupported argument
2023-01-16T11:11:27.495+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-01-16T11:11:27.496+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google-beta/4.48.0/darwin_arm64/terraform-provider-google-beta_v4.48.0_x5 pid=32615
2023-01-16T11:11:27.496+0100 [DEBUG] provider: plugin exited
╷
│ Error: Unsupported argument
│
│   on infrastructure.tf line 346, in resource "google_compute_backend_bucket" "...":
│  346:     negative_caching_policy = {
│
│ An argument named "negative_caching_policy" is not expected here. Did you mean to define a block of type "negative_caching_policy"?
╵
2023-01-16T11:11:27.591+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-01-16T11:11:27.592+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.48.0/darwin_arm64/terraform-provider-google_v4.48.0_x5 pid=32617
2023-01-16T11:11:27.592+0100 [DEBUG] provider: plugin exited
```
[Gist with complete debug output](https://gist.github.com/jimmybyrum/adc98ebcac0750fb38c474b00729a283)

### Expected Behavior

The negative_caching_policy should have been updated in the backend bucket

### Actual Behavior

```
│ Error: Unsupported argument
│
│   on infrastructure.tf line 346, in resource "google_compute_backend_bucket" "...":
│  346:     negative_caching_policy = {
│
│ An argument named "negative_caching_policy" is not expected here. Did you mean to define a block of type "negative_caching_policy"?
```

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket#negative_caching_policy

### Possibly useful information

I ended up adding this config via the gcloud cli:
```
gcloud compute backend-buckets update <...> --negative-caching-policy='404=0'
```

If I then comment out the negative_caching_policy block in my terraform config, there are no errors and it shows that it will remove that config (so it's recognizing the existing config for negative_caching_policy, but not allowing me to set it via terraform).
```tf
  Terraform will perform the following actions:

  # google_compute_backend_bucket.<...> will be updated in-place
  ~ resource "google_compute_backend_bucket" "..." {
        id                      = "..."
        name                    = "..."
        # (7 unchanged attributes hidden)

      ~ cdn_policy {
            # (8 unchanged attributes hidden)

          - negative_caching_policy {
              - code = 404 -> null
              - ttl  = 0 -> null
            }
        }
    }
```

**Comment by edwardmedia** [comment]
@jimmybyrum not sure what happened to your initial config. But below is the daily test and it should work. 

https://github.com/hashicorp/terraform-provider-google/blob/eefc1a573567f421c21f0ea575bd71bf3ebf564c/google/resource_compute_backend_bucket_test.go#L260

**Comment by edwardmedia** [comment]
@jimmybyrum is this still an issue?

**Comment by jimmybyrum** [comment]
Hi @edwardmedia,

Yes, still seeing the same, even after updating to the latest version of the provider
```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.53.1
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1
```

Same error:
```terraform
╷
│ Error: Unsupported argument
│
│   on network.tf line 45, in resource "google_compute_backend_bucket" "...":
│   45:     negative_caching_policy = {
│
│ An argument named "negative_caching_policy" is not expected here. Did you mean to define a block of type "negative_caching_policy"?
╵
```

**Comment by edwardmedia** [comment]
@jimmybyrum I see where the problem is. Can you try removing `=` in below block?

```tf

    negative_caching_policy = {
      code = 404
      ttl  = 0
    }
```

```tf

    negative_caching_policy  {
      code = 404
      ttl  = 0
    }
```

**Comment by jimmybyrum** [comment]
Omg that's it. Thanks and nice job spotting that evil `=` there.
