### ISSUE TITLE
google_cloudfunctions_function does not see event_trigger topic name changes as a difference

### ISSUE THREAD

**Issue by jkosternl** [hashicorp/terraform-provider-google#13513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.3.6

Used: hashicorp/google v4.49.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

When changing an existing Cloud Function trigger topic name, a name change are not picked up as a change and thus ignored. 

For example:
Current state in TF:
```
event_trigger {
 event_type = "google.pubsub.topic.publish"
 resource   = "whatever-events-inbound"
}
```
New to be state:
```
event_trigger {
 event_type = "google.pubsub.topic.publish"
 resource   = "events-inbound"
}
```
If you `tf plan` this change, TF concludes that there is no change. 

### Debug Output
Didn't make, since it is not needed. 

### Panic Output
NA

### Expected Behavior
Every name change of a topic trigger should be taken as a change. 

### Actual Behavior
Name changes on a trigger from "price-events-inbound" to "new-price-events-inbound" are not considered as a change.
Only if you also change the last parts of the name, it does work. Like: "price-events-inbound" -> "price-events-inboundXX"

### Steps to Reproduce
1. Deploy a Cloud Function with a PubSub trigger to an existing PubSub topic called "price-events-inbound".
2. Update your TF configuration to only update the topic name in PubSub and the Cloud Function trigger topic name to "events-inbound"
3. Run `tf plan` and see that TF concludes: there is no change. 

### Important Factoids

NA

### References

NA

**Comment by edwardmedia** [comment]
@jkosternl I can't repro the issue. Below code seems working as expected. Can you detail the config and steps so I can repro?

https://github.com/hashicorp/terraform-provider-google/blob/b37e44258d093e1cc1151e58415b756f57890d9d/google/resource_cloudfunctions_function.go#L84

**Comment by jkosternl** [comment]
Thanks for checking out on our bug report @edwardmedia. We will create some better repro path with an easy example to show it.

**Comment by jkosternl** [comment]
But wait, is the next line L85 not already showing the problem @edwardmedia ? 
`return strings.HasSuffix(old, new)`
If the old name ends with the new name, no change is detected... That's not good. Changing 123asdf to asdf will result in true! 

To my opinion, this should be just a `strings.Compare(old, new)` right?  Or do the creators like to support namespace change to be seen as no change? At least, the side-effect is huge.

**Comment by jkosternl** [comment]
Thanks @edwardmedia for addressing and fixing this issue! Looks like the new code contains a lot more logic to compare the old and new values.
