### ISSUE TITLE
Add support for BYOIP by adding new resources

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a feature that allows Bring Your Own IP (BYOIP) with VPCs 👉 https://cloud.google.com/vpc/docs/bring-your-own-ip
That guide describes how [public advertised prefixes](https://cloud.google.com/compute/docs/reference/rest/v1/publicAdvertisedPrefixes) and [public delegated prefixes](https://cloud.google.com/compute/docs/reference/rest/v1/publicDelegatedPrefixes) are required to allow the IP(s) to be used, and those resources aren't implemented in the provider yet.

### New or Affected Resource(s)

* google_compute_public_advertised_prefix
* google_compute_public_delegated_prefix

### Potential Terraform Configuration

I'm unsure what the configuration would look like as the API documentation says this for both API endpoints:

> There is no persistent data associated with this resource.

But using the JSON from [the insert method docs for publicAdvertisedPrefixes](https://cloud.google.com/compute/docs/reference/rest/v1/publicAdvertisedPrefixes/insert) it might look something like:

```tf
resource "google_compute_public_advertised_prefix" "example" {
    name = "example.com" # must match https://www.ietf.org/rfc/rfc1035.txt
    description = "Description goes here"
    ip_cidr_range = "1.2.3.4/5"
    parent_prefix = google_compute_public_delegated_prefix.self_link
    # other fields, possibly...
}
```

I think there would also need to be data sources implemented to access this data, given that there are no resources in a typical CRUD sense for this API endpoint. E.g. the [docs for the fingerprint field](https://cloud.google.com/compute/docs/reference/rest/v1/publicDelegatedPrefixes/insert#body.request_body.FIELDS.fingerprint) of a PAP say "To see the latest fingerprint, make a get() request to retrieve a PublicDelegatedPrefix.".

### References

* There was a request for supporting Bring Your Own IP in the past (2021) but it was blocked by dependencies then : https://github.com/hashicorp/terraform-provider-google/issues/9984
* API docs:
    * https://cloud.google.com/compute/docs/reference/rest/v1/publicAdvertisedPrefixes
    * https://cloud.google.com/compute/docs/reference/rest/v1/publicDelegatedPrefixes

**Comment by Harmelodic** [comment]
Is there an ETA or target date for releasing this?
(couple of weeks? particular month? Q2/3/4 2023? 2024?)

**Comment by slevenick** [comment]
End of April is the ETA
