### ISSUE TITLE
Apigee org support for addons

### ISSUE THREAD

**Issue by ssvaidyanathan** [hashicorp/terraform-provider-google#13528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Apigee org allows to enable add-ons. Will be nice if that can be also enabled using the Apigee org module

### New or Affected Resource(s)

* google_apigee_organization

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_apigee_organization" "org" {
  analytics_region   = "us-central1"
  project_id         = data.google_client_config.current.project
  authorized_network = google_compute_network.apigee_network.id
  depends_on         = [google_service_networking_connection.apigee_vpc_connection]
  addons             = ["advancedApiOpsConfig", "apiSecurityConfig"]
}

```

**Comment by csantos** [comment]
Would be a great addition. I think the addon may need to be an object not just a string array though. Looking at the Apigee Organizations API, it looks like the add-ons are a structure ([AddonConfig](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations#AddonsConfig)) which can contain output values besides just enabled. For example, the [API Security addon structure](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations#apisecurityconfig) has an expiresAt field. So maybe the resource would look something like:

``` terraform
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_apigee_organization" "org" {
  analytics_region   = "us-central1"
  project_id         = data.google_client_config.current.project
  authorized_network = google_compute_network.apigee_network.id
  depends_on         = [google_service_networking_connection.apigee_vpc_connection]
  addons             = {
    advancedApiOps = {
      enabled = true
    }
    apiSecurity = {
      enabled = true
    }
}
```

That way you can follow the same object traversal to get to the output value such as:


``` terraform
google_apigee_organization.org.addons.apiSecurity.expiresAt
```

**Comment by rileykarson** [comment]
Marking `size/m` over `size/s` based on the fact that this list will grow over time, and `enabled` subfields have proven complex in GKE.
