### ISSUE TITLE
Terraform Deploy Error of UDP failover disableConnectionDrainOnFailover configuration

### ISSUE THREAD

**Issue by 597040593** [hashicorp/terraform-provider-google#13529]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.47.0
+ provider registry.terraform.io/hashicorp/google-beta v4.47.0

### Affected Resource(s)

* google_compute_region_backend_service

### Terraform Configuration Files

EOT
  protocol = "UDP"
  region = "us-east1"
  load_balancing_scheme = "INTERNAL"
  network = "projects/xxx"
  health_checks = [
  google_compute_health_check.xxx_healthcheck.id
  ]
  backend {
    failover = false
    group = google_compute_instance_group.xxx_instancegroup1.id
  }
  backend {
    failover = true
    group = google_compute_instance_group.xxx_instancegroup2.id
  }
  failover_policy {
    drop_traffic_if_unhealthy = true
  }

### Debug Output

Error: Error creating RegionBackendService: googleapi: Error 400: Invalid value for field 'resource.failoverPolicy': '{  "disableConnectionDrainOnFailover": false,  "dropTrafficIfUnhealthy": true}'. Disable connection drain on failover cannot be set when the protocol is UDP., invalid

### Expected Behavior

there is no disableConnectionDrainOnFailover configuration in the terraform configuration, so dont know where did this error come from

### Actual Behavior

error reporting I set the disableConnectionDrainOnFailover in UDP resource 

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@597040593 this error is from the API. Here is the original API doc where you can verify what it means. https://cloud.google.com/compute/docs/reference/rest/v1/regionBackendServices

here is the [disable_connection_drain_on_failover](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_backend_service#disable_connection_drain_on_failover) in the provider.

**Comment by edwardmedia** [comment]
b/268207403
