### ISSUE TITLE
google_container_cluster data source: read fail with Invalid address to set (...config_connector_config)

### ISSUE THREAD

**Issue by nemethloci** [hashicorp/terraform-provider-google#13525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.3.7
hashicorp/google provider version: 4.49.0

### Affected Resource(s)

* google_container_cluster (data provider)

### Terraform Configuration Files

```tf
data "google_container_cluster" "cluster" {
  count    = local.cloud_env == "cpl" ? 0 : 1
  project  = local.project
  location = local.region
  name     = local.cluster_name
}
# Note: variables have been checked and they are defined and their values are correct.
```
### Expected Behavior

terraform should fetch the cluster's data

### Actual Behavior
```
╷
│ Error: Invalid address to set: []string{"addons_config", "0", "config_connector_config"}
│ 
│   with module.global-config.data.google_container_cluster.cluster[0],
│   on .terraform/modules/global-config/main.tf line 28, in data "google_container_cluster" "cluster":
│   28: data "google_container_cluster" "cluster" {
│ 
╵
```
### Steps to Reproduce

```
terraform {
  required_version = "~> 1.3.7"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.49.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.16.1"
    }
  }
}

data "google_container_cluster" "cluster" {
  project  = local.project
  location = local.region
  name     = local.cluster_name
}
```
Run: terraform plan

### Important Factoids
- based on the error message triggering the issue, might require to have  addonsConfig.configConnectorConfig.enabled: true set for the GKE cluster.
- the very same terraform config works fine just by changing the provider version to 4.48.0 (same config, same cluster....)

**Comment by robertlindner** [comment]
We are seeing the same issue. 
Note: In the api response for our clusters, the `config_connector_config` is an empty object instead of `"enabled": <bool>`:
```
    "addonsConfig": {
        "configConnectorConfig": {},
        "gcePersistentDiskCsiDriverConfig": {
            "enabled": true
        },
        "horizontalPodAutoscaling": {},
        "httpLoadBalancing": {},
        "kubernetesDashboard": {
            "disabled": true
        },
        "networkPolicyConfig": {
            "disabled": true
        }
    },
```

**Comment by rshah28** [comment]
I'm running into same issue.
`addons_config {
    config_connector_config {
      enabled = var.enable_config_connector
    }
  }`

`google = {
      version = "~> 4"
      source  = "hashicorp/google"
    }
    google-beta = {
      version = "~> 4"
      source  = "hashicorp/google-beta"
    }`

**Comment by edwardmedia** [comment]
@nemethloci this appears the the [change](https://github.com/hashicorp/terraform-provider-google/pull/13380) has been applied in the resource but not in the data source.

**Comment by edwardmedia** [comment]
yes dups of 
https://github.com/hashicorp/terraform-provider-google/issues/13507 
https://github.com/hashicorp/terraform-provider-google/issues/11943
