### ISSUE TITLE
google_folder cannot import folder when in a module with an index from a for_each

### ISSUE THREAD

**Issue by davdmrgn** [hashicorp/terraform-provider-google#13539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.7

### Affected Resource(s)

* google_folder

### Terraform Configuration Files

./organizations/dev/main.tf

```tf
provider "google" {
}

module "default" {
  source = "../"
  env_id = "dev"
}
```

./organizations/folders.tf

```tf
locals {
  folders = [
    "Folder 1",
    "Folder 2",
    "Folder 3",
  ]
}

resource "google_folder" "org" {
  parent       = "organizations/ORG_ID"
  for_each     = toset(local.folders)
  display_name = each.key
}
```

### Expected Behavior

Folder data imported to state file.

### Actual Behavior

State file not updated.

### Steps to Reproduce

1. `cd ./organizations/dev`
2. `terraform init`
3. `terraform validate`
4. `terraform import "module.default.google_folder.org[\"Folder 1\"]" folders/FOLDER_ID`

### Important Factoids

Workaround:
1. Add a `google_folder` resource block to `./organizations/main.tf`
  ```tf
  resource "google_folder" "temp" {
    display_name  = "Folder 1"
    parent_org_id = "ORG_ID"
  }
  ```
2. Import the resource block: `terraform import google_folder.temp folders/FOLDER_ID` ✅ 
3. Move the resource in the state file: `terraform state mv google_folder.temp "module.default.google_folder.org[\"Folder 1\"]"

**Comment by edwardmedia** [comment]
@davdmrgn I think this is an issue more about how to use the terraform feature. Maybe ask a question over there?

**Comment by edwardmedia** [comment]
@davdmrgn sorry there is not much we can do at the provider level. Closing this now
