### ISSUE TITLE
Support for artifact registry remote repositories

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/terraform-provider-google#13536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

While currently in private preview, Google Cloud has added support to proxy artifacts from remote repositories. This enhancement is to request creation of support for that in the provider.

### New or Affected Resource(s)

* google_artifact_registry_repository

### References

* https://cloud.google.com/artifact-registry/docs/repositories/remote-repo

**Comment by rileykarson** [comment]
Note: Adding this to `google` or `google-beta` will require it releasing to public preview or GA.

**Comment by kevholmes** [comment]
Looks like we are now in `Public Preview` @rileykarson 🥳 

>We are excited to announce the Public Preview launch of Remote and Virtual Repositories in Artifact Registry! Remote and Virtual repositories are now publicly available for Docker, Maven, Python and Npm formats, with full UI and gcloud support. Linux and Go package support is under development, and will be launched incrementally as separate features.

**Comment by melinath** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7333
