### ISSUE TITLE
google_cloudfunctions2_function  created in GCP but not stored in tfstate if in failed state

### ISSUE THREAD

**Issue by majduk** [hashicorp/terraform-provider-google#13535]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.48.0
+ provider registry.terraform.io/hashicorp/google-beta v4.48.0
+ provider registry.terraform.io/hashicorp/google v4.48.0
+ provider registry.terraform.io/hashicorp/google-beta v4.48.0

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions2_function" "opl_cf" {
    location    = "europe-central2"
    name        = "opl-rakietykosmiczne-cf2-failing-code"
    project     = "majduk-sandbox-315813"

    build_config {
        entry_point           = "failing-code"
        runtime               = "python39"
        source {

            storage_source {
                bucket = "majduk_sendbox_bucket_for_code"
                object = "failing-code-5e0a6fa4e73343c3bbf825c58454e982.zip"
             }
         }
     }

    event_trigger {
        event_type            = "google.cloud.pubsub.topic.v1.messagePublished"
        pubsub_topic          = "projects/majduk-sandbox-315813/topics/sandbox-topic2"
        retry_policy          = "RETRY_POLICY_DO_NOT_RETRY"
        service_account_email = "cf2sa-710@majduk-sandbox-315813.iam.gserviceaccount.com"
        trigger_region        = "europe-central2"
     }

    service_config {
        all_traffic_on_latest_revision   = true
        available_memory                 = "512M"
        ingress_settings                 = "ALLOW_ALL"
        max_instance_count               = 3
        min_instance_count               = 1
        service_account_email            = "cf2sa-710@majduk-sandbox-315813.iam.gserviceaccount.com"
        timeout_seconds                  = 150
     }
}
```

### Debug Output

[gist](https://gist.github.com/majduk/88dad30c5452e01938eb35354b06f165)

### Expected Behavior

1. Terraform apply - Create the `google_cloudfunctions2_function` resource, the creation fails, the resource is saved in the terraform state and the resource's `state` variable is set to failed
2. Terraform apply - Terraform proposes to replace the resource as it's state is FAILED

### Actual Behavior

1. Terraform apply
2. Provider starts the resource creation, creates the resource in GCP, monitors the state
3. GCP Resource creation is completed but the internal state is FAILED 
4.  Resource is not stored in terraform but the resource stays in failed state in GCP preventing clean retry and forcing a manual action

### Steps to Reproduce

1. `terraform apply`
2. Provider creates the resource, creation fails
```
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Creating...
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [10s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [20s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [30s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [40s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [50s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [1m0s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [1m10s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [1m20s elapsed]
module.cf2_test2.google_cloudfunctions2_function.opl_cf: Still creating... [1m30s elapsed]
╷
│ Error: Error waiting to create function: Error waiting for Creating function: Error code 3, message: Could not create or update Cloud Run service opl-rakietykosmiczne-cf2-
failing-code, Container Healthcheck failed. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs f
or this revision might contain more information.                      
│                                                                                     
│ Logs URL: https://console.cloud.google.com/logs/viewer?project=majduk-sandbox-315813&resource=cloud_run_revision/service_name/opl-rakietykosmiczne-cf2-failing-code/revisio
n_name/opl-rakietykosmiczne-cf2-failing-code-00001-han&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22opl-rakietykosmiczne-cf2-f
ailing-code%22%0Aresource.labels.revision_name%3D%22opl-rakietykosmiczne-cf2-failing-code-00001-han%22 
│ For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
│ 
│   with module.cf2_test2.google_cloudfunctions2_function.opl_cf,
│   on module/cfgen2/main.tf line 51, in resource "google_cloudfunctions2_function" "opl_cf":
│   51: resource "google_cloudfunctions2_function" "opl_cf" {
│                                                                                     
```
5. `terraform state list`
```
terraform state list | grep module.cf2_test2.google_cloudfunctions2_function
<empty - the resource state not stored in terraform>
```
6. GCP resource created
```
ubuntu@ubuntu-container:~/opl-cf2$ gcloud alpha functions list --gen2
NAME                                   STATE   TRIGGER                REGION           ENVIRONMENT
opl-rakietykosmiczne-cf2-failing-code  FAILED  HTTP Trigger           europe-central2  2nd gen
```

This leads to a need of manual resource deletion.

### References

* b/274824568

**Comment by edwardmedia** [comment]
API returns `done` but with error. 

```
  "done": true,
  "error": {
    "code": 3,
    "message": "Could not create 
```

**Comment by rileykarson** [comment]
@edwardmedia: Were you able to successfully recreate the issue? The solution here is probably fairly routine- `taint_resource_on_failed_create` or https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/post_create_failure/delete_on_failure.go.erb cover this kind of case, but we'd want to ensure that behaviour is reasonable during provisioning failure (like this) and admission failure (when we supply an invalid request and receive an error immediately).

**Comment by ryanisroot** [comment]
I've been running into this issue as well, requiring me to the delete the function manually between iterations

**Comment by willwillems** [comment]
This is a known issue on our end as well

**Comment by drandell** [comment]
Any update on this?

**Comment by andreacfm** [comment]
Same issue here https://github.com/hashicorp/terraform-provider-google/issues/15143
