### ISSUE TITLE
Big query dataset creation: This is a bug in the provider, which should be reported in the provider's own issue tracker.

### ISSUE THREAD

**Issue by MaynardLBG** [hashicorp/terraform-provider-google#13548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
google provider version = "~> 4.30.0"

### Affected Resource(s)

google_bigquery_dataset_access

### Terraform Configuration Files

access_config = {
  "bqML" = {
    role           = "READER"
    group_by_email = 
  }
  "dsbq" = {
    role           = "organizations/233526418605/roles/custom.grp.dsbq"
    group_by_email = 
  }
  "dmltb" = {
    role           = "organizations/233526418605/roles/custom.grp.dmltb"
    group_by_email = 
  }
}

### Debug Output

![New Note](https://user-images.githubusercontent.com/73490120/214048373-11cf7250-6c1c-4b8c-a1a1-a72d357179a7.jpeg)
module.bq_ds.google_bigquery_dataset_access.dataset_access["dmltb"]: Creating...
module.bq_ds.google_bigquery_dataset_access.dataset_access["dsbq"]: Creating...
module.bq_ds.google_bigquery_dataset_access.dataset_access["bqML"]: Creating...

Warning: Version constraints inside provider configuration blocks are deprecated

  on provider.tf line 2, in provider "google":
   2:   version = "~> 4.30.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

Error: Provider produced inconsistent result after apply

When applying changes to
module.bq_ds.google_bigquery_dataset_access.dataset_access["dsbq"], provider
"provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected
new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to
module.bq_ds.google_bigquery_dataset_access.dataset_access["dmltb"], provider
"provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected
new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to
module.bq_ds.google_bigquery_dataset_access.dataset_access["bqML"], provider
"provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected
new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior

no error during terraform apply

### Actual Behavior

produces above error

### Steps to Reproduce
Create a bigquery instance with above configuration and do a terraform apply

### References
* #0000

**Comment by edwardmedia** [comment]
@MaynardLBG can you share your config you were using and the debug log that contains the API requests & responses?

**Comment by MaynardLBG** [comment]
@edwardmedia 
this is the config: 
  authorized_datasets = { for k, m in var.access_config : tostring(k) =>
    {
      authorized_dataset_id           = lookup(m, "authorized_dataset_id", null)
      project_id                      = lookup(m, "project_id", var.project_id)
      location                        = lookup(m, "location", null)
      default_table_expiration_ms     = lookup(m, "default_table_expiration_ms", null)
      default_partition_expiration_ms = lookup(m, "default_partition_expiration_ms", null)
      friendly_name                   = lookup(m, "friendly_name", null)
      description                     = lookup(m, "description", null)
    }
  if lookup(m, "authorized_dataset_id", null) != null }

  authorized_dataset_auth = { for val in
    flatten([for a in values(local.authorized_datasets) :
      [for k, v in var.access_config :
        { authorized_dataset = a,
          access_policy      = k,
          config             = { for c, d in v : c => d }
        }
      ]
    ]) :
    "${val.authorized_dataset.project_id}.${val.authorized_dataset.authorized_dataset_id}.${val.access_policy}" => val.config
  }

**Comment by NotBalveen** [comment]
[api_Logs.txt](https://github.com/hashicorp/terraform-provider-google/files/10491624/api_Logs.txt)

**Comment by MaynardLBG** [comment]
@edwardmedia logs are attached above

**Comment by edwardmedia** [comment]
@MaynardLBG @NotBalveen I am not super clear how to repro the issue. No idea how to construct the config based on what you provided. 

Can you enable TF_LOG=DEBUG to catch all the requests and response? 

Do the examples [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access) work for you? Maybe you can create a minimum config like the [examples](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access) that can repro the issue?

**Comment by MaynardLBG** [comment]
@edwardmedia , closing this issue as we have potentially have found root cause

**Comment by andrelaszlo** [comment]
Got the same error. The issue, in summary: I used a secondary domain when specifying `group_by_email` but it was normalized to the primary domain.

Terraform config:
```terraform
resource "google_bigquery_dataset_access" "my_team_to_my_dataset" {
  dataset_id     = google_bigquery_dataset.my_dataset.dataset_id
  role           = "roles/bigquery.dataViewer"
  group_by_email = "my-team@example.io"
}
```

Response
```http
PATCH /bigquery/v2/projects/my-project/datasets/my_dataset?alt=json HTTP/1.1
Host: bigquery.googleapis.com
User-Agent: Terraform/1.3.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.52.0
Content-Length: 352
Content-Type: application/json
Accept-Encoding: gzip

{
  "access": [
    {
      "role": "READER",
      "groupByEmail": "my-team@example.com"
    }
  ],
  ...
}
```

Note the difference - `my-team@example.io` vs `my-team@example.com`.

Further down the debug output:

```
2023-02-10T20:11:45.720+0100 [INFO]  provider.terraform-provider-google_v4.52.0_x5: 2023/02/10 20:11:45 [DEBUG] Skipping item with groupByEmail= "my-team@example.com", looking for "my-team@example.io"): timestamp=2023-02-10T20:11:45.720+0100
2023-02-10T20:11:45.720+0100 [INFO]  provider.terraform-provider-google_v4.52.0_x5: 2023/02/10 20:11:45 [DEBUG] Removing BigQueryDatasetAccess because it couldn't be matched.: timestamp=2023-02-10T20:11:45.720+0100
```

Not sure this can be fixed in the provider since it doesn't know about our primary and secondary domains (?), but it should probably be added to the docs.
