### ISSUE TITLE
Unexpected terraform deployment due to max_instances mismatch

### ISSUE THREAD

**Issue by KAKAinGoog** [hashicorp/terraform-provider-google#13543]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/google v4.47.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "google_project" "codelab_project" {
  project_id      = "codelab-terraform"
  name            = "codelab-terraform"
  billing_account = "XXXXX"

  # This is the ID for /experimental, see go/experimental-folder.
  # In particular, please accept go/experimental-folder#tos.
  # If you are not eligible for creating a project, ask a fellow engineer
  # and see go/terraform-codelab#import-existing-project for importing it.
  folder_id = "261046259366"


  lifecycle {
    # Stop any terraform plan which would destroy this GCP project.
    prevent_destroy = true
  }
}

# Grants your team permission to view this GCP project.
resource "google_project_iam_member" "codelab_iam_member" {
  project = google_project.codelab_project.project_id
  role    = "roles/viewer"

  member = "group:gcf-control-plane-dev@google.com"
}

# Enable the Compute Engine API.
resource "google_project_service" "codelab_compute_service" {
  project = google_project.codelab_project.project_id
  service = "compute.googleapis.com"
}


# create pub/sub topic
resource "google_pubsub_topic" "topic" {
  project = google_project.codelab_project.project_id
  name    = "terraform-topic"
}

# create bucket
resource "google_storage_bucket" "my-bucket" {
  project                     = google_project.codelab_project.project_id
  name                        = "my_terraform_bucket_chujunc"
  location                    = "US"
  uniform_bucket_level_access = true
}


# put code inside the bucket
resource "google_storage_bucket_object" "archive" {
  name   = "main.zip"
  bucket = "${google_storage_bucket.my-bucket.name}" # interpolation referencing
  source = "main.zip"
}

# create function
resource "google_cloudfunctions_function" "function" {
  name        = "terraform-function"
  description = "My function"
  runtime     = "python37"
  region      = "us-central1"

  available_memory_mb   = 128
  source_archive_bucket = "${google_storage_bucket.my-bucket.name}"      # interpolation referencing
  source_archive_object = "${google_storage_bucket_object.archive.name}" # interpolation referencing
  entry_point           = "helloGET"
  project               = google_project.codelab_project.project_id

  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = "${google_pubsub_topic.topic.name}" # interpolation referencing
  }
}

# create a schedular (cron job) for every minute
resource "google_cloud_scheduler_job" "job" {
  name        = "terraform-job"
  description = "test job"
  schedule    = "30 * * * *"
  region      = "us-central1"
  project     = google_project.codelab_project.project_id

  pubsub_target {
    # topic.id is the topic's full resource name.
    topic_name = "${google_pubsub_topic.topic.id}" # interpolation referencing
    data       = base64encode("hello-from-terraform")
  }
}
```

### Debug Output

First, create a Cloud Function without providing max_instances. Cloud Function then is created and show max instances as 3000. 
![Screenshot 2023-01-19 at 3 47 54 PM](https://user-images.githubusercontent.com/121135073/213587305-788a27c8-39bb-4db8-9b59-e744b27d3806.png)

Without changing any anything, run `terraform plan` again. It shows max_instances need to be updated from 3000 to 0. 
![Screenshot 2023-01-19 at 3 57 26 PM](https://user-images.githubusercontent.com/121135073/213588320-1d89f08e-7167-43bc-8cc7-707e709499a4.png)

### Expected Behavior

Terraform should not detect change when user doesn't modify config. 

### Actual Behavior
Terraform detecs change and apply deployment unless I set max_instances to 3000 explicitly. This is happening only for background function

### Steps to Reproduce

1. create cloud function without providing max_instances or have max_instances = 0
2. terraform plan

### References

* #0000

**Comment by rober15** [comment]
@KAKAinGoog  we faced the same problem in the last days. Is there any timeline when we will see the fix in the general available versions ?

**Comment by KAKAinGoog** [comment]
Hi! I actually don't have any insight regarding this. Maybe @melinath would know?

**Comment by melinath** [comment]
It looks like this went out in the release of 4.52.0 yesterday: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.52.0
