### ISSUE TITLE
No data source for compute_network_peering

### ISSUE THREAD

**Issue by kliu47** [hashicorp/terraform-provider-google#13541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently no datasource for `compute_network_peering`. Requesting a new data source that can return the list of current configurations as well as a list of all imported routes

### New or Affected Resource(s)

* google_compute_network_peering

### Potential Terraform Configuration

```tf

data "google_compute_network_peering" "gke-peer" {
  project = "host-project-id"
  name    = "peer name
}


```

### References

* Potential GCP API to leverage: https://cloud.google.com/compute/docs/reference/rest/v1/networks/listPeeringRoutes

**Comment by rileykarson** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/7051, I believe!
