### ISSUE TITLE
How to hookup a Cloud Function for Google Identity Platform's beforeSignIn event?

### ISSUE THREAD

**Issue by miniruwan** [hashicorp/terraform-provider-google#13553]
I want to setup a cloud function for `beforeSignIn` event. Following is [the way to do it manually](https://cloud.google.com/identity-platform/docs/blocking-functions#:~:text=Go%20to%20the,in%20(beforeSignIn).):

<img width="844" alt="image" src="https://user-images.githubusercontent.com/2083321/214149900-17ae0b2a-898b-464a-b8b3-60b78862208a.png">

My question is, **How to do this via Terraform?**

#### Things I have tried:
I couldn't find anything in Google Identity configuration side ([google_identity_platform_project_default_config)](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/identity_platform_project_default_config). So I thought this should be configured from the cloud functions side, and I tried to use `event_trigger `when creating the function as follows via terraform

```
resource "google_cloudfunctions_function" "function" {
  
  // ...

  event_trigger {
    event_type = "providers/cloud.auth/eventTypes/user.beforeSignIn:password"
    resource = projects/<my-project-name>
  }
}
```

But I'm getting _400 Bad Request_ from Google when trying to `terraform apply` with the following message:

> Unknown event_type providers/cloud.auth/eventTypes/user.beforeSignIn:password

This error makes sense because this event is not in the supported event types in cloud functions. You can get all the supported event types list from `gcloud functions event-types list` command.
![functions event types](https://user-images.githubusercontent.com/2083321/214155136-c0284dd3-c4f0-497c-ace8-0119332d81ce.png)

**Comment by edwardmedia** [comment]
@miniruwan I am not super familiar with this but I took a look at the related documents. The current provider does not support this. Also I did not find an API that supports this. Closing this now. Feel free to reopen if you see docs that might be more helpful. Thanks

**Comment by miniruwan** [comment]
Because the provider doesn't support it, I had to do it by _manually_ calling google apis with `local-exec` provisioner as follows:

```
resource "google_cloudfunctions_function" "function" {
  name        = "MyFunc"
  description = "Some Description"
  runtime     = "nodejs16"
  region      = var.function_region

  available_memory_mb   = 256
  source_archive_bucket = xxxxxx
  source_archive_object = xxxxxx
  entry_point           = "beforeSignIn"

  trigger_http     = true
  ingress_settings = "ALLOW_INTERNAL_ONLY"

  # Update Identity Platform setting for blocking function trigger to call newly created function for beforeSignIn
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      curl -X PATCH "https://identitytoolkit.googleapis.com/admin/v2/projects/${self.project}/config?updateMask=blockingFunctions.triggers" \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $GCLOUD_AUTH_TOKEN" \
          -d '{"blockingFunctions": {"triggers": {"beforeSignIn":{"functionUri":"${self.https_trigger_url}"}}}}'
    EOT
  }
}
```

**Comment by oboukili** [comment]
@edwardmedia, as @miniruwan workaround references, there is an [API for that](https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects/updateConfig). What would be the best course of action to be able to contribute here, directly through a PR within this repository, or within the [magic-modules repository](https://github.com/trodge/magic-modules/tree/main/mmv1/products/identityplatform)?
