### ISSUE TITLE
Stateful Managed Instance group is auto updated even when its set to oppurtunistic updates

### ISSUE THREAD

**Issue by sweetkrishiscool** [hashicorp/terraform-provider-google#13571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/google v4.45.0
+ provider registry.terraform.io/hashicorp/google-beta v4.45.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* google_instance_group_manager

### Terraform Configuration Files

  "update_policy": [
    {
      "instance_redistribution_type": "NONE",
      "max_surge_fixed": 0,
      "max_surge_percent": null,
      "max_unavailable_fixed": 3,
      "max_unavailable_percent": null,
      "minimal_action": "RESTART",
      "replacement_method": "RECREATE",
      "type": "PROACTIVE"
    }

changing to 
  "update_policy": [
    {
      "instance_redistribution_type": "NONE",
      "max_surge_fixed": 0,
      "max_surge_percent": null,
      "max_unavailable_fixed": 3,
      "max_unavailable_percent": null,
      "minimal_action": "REPLACE",
      "replacement_method": "RECREATE",
      "type": "OPPORTUNISTIC"
    }

### Debug Output

https://gist.github.com/sweetkrishiscool/36ec56f7564b551e2144589b1c13131f

### Expected Behavior
Create a new template and stop at the opportunistic update

### Actual Behavior

create a new template and applies immediately to the instances
### Steps to Reproduce
i am trying to update the stateful managed instance group to oppurtunistic updates,

i am running the 

gcloud compute instance-groups managed rolling-action stop-proactive-update <instance group> --region=northamerica-northeast1

then update the state file and do a terraform apply

### References

* #0000

**Comment by edwardmedia** [comment]
@sweetkrishiscool in your [config](https://github.com/hashicorp/terraform-provider-google/issues/13571#issue-1556767479), what do you mean `changing to`? Can you be more specific about what was wrong? And show me what is wrong in the log?

**Comment by sweetkrishiscool** [comment]
I have an existing state file where the MIG is created with PROACTIVE updates. 
i updated the MIG with gcloud command manually to OPPORTUNISTIC and tried to update the Terraform config, its still rolling out the update

`2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set
2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[1]: applying the planned Update change
2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set
2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[2]: applying the planned Update change
2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange
2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange
2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Received request: tf_proto_version=5.2 tf_req_id=c3e81199-8084-7e35-2228-40ee9bada2d9 @module=sdk.proto tf_provider_addr=provider tf_resource_type=google_compute_region_per_instance_config tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:801 timestamp=2023-01-24T11:27:08.131-0500
2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Received request: tf_rpc=ApplyResourceChange @module=sdk.proto tf_proto_version=5.2 tf_provider_addr=provider tf_req_id=03b07115-39e4-92ef-4045-f3ea404f1c93 tf_resource_type=google_compute_region_per_instance_config @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:801 timestamp=2023-01-24T11:27:08.131-0500
2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Sending request downstream: tf_provider_addr=provider tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_proto_version=5.2 tf_req_id=03b07115-39e4-92ef-4045-f3ea404f1c93 tf_resource_type=google_compute_region_per_instance_config @module=sdk.proto timestamp=2023-01-24T11:27:08.131-0500
2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Sending request downstream: tf_rpc=ApplyResourceChange @module=sdk.proto tf_req_id=c3e81199-8084-7e35-2228-40ee9bada2d9 tf_resource_type=google_compute_region_per_instance_config @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_proto_version=5.2 tf_provider_addr=provider timestamp=2023-01-24T11:27:08.131-0500
2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set
2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[0]: applying the planned Update change
2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange`

**Comment by edwardmedia** [comment]
@sweetkrishiscool I guess I am not super clear what you meant below. Here is what I guess:
1) ran gcloud command (then what result did you see?)
2) tried to update the Terraform config---> assume you update the config (changed the type from "PROACTIVE"  to "OPPORTUNISTIC" and then apply the config? (if this is true, what result did you see?)
3) what do you mean `its still rolling out the update`?

```
i updated the MIG with gcloud command manually to OPPORTUNISTIC and tried to update the Terraform config, its still rolling out the update
```

**Comment by sweetkrishiscool** [comment]
1. this is the result of the gcloud 
https://gist.github.com/sweetkrishiscool/eb44ecc8d91f9be4e13e7dc072b67cbc

2. you are right, i updated the type, also imported the state and applied the config 
this is the result of terraform apply
https://gist.github.com/sweetkrishiscool/ba7e02237f62e646fe4398b0dc91bb84

Since i have changed the type of update to OPPORTUNISTIC, terraform shouldn't apply the change to the instances, however i see its still applying the changes.

**Comment by edwardmedia** [comment]
@sweetkrishiscool how come I can find neither "PROACTIVE" nor "OPPORTUNISTIC" in the log. Instead, below is the block that shows the difference. Is this what you referred to?

```
      ~ update_policy {
          ~ minimal_action               = "RESTART" -> "REPLACE"
            # (7 unchanged attributes hidden)
        }
```

**Comment by sweetkrishiscool** [comment]
Hi @edwardmedia i dont think you will see a change in log from PROACTIVE to OPPURTUNISTIC, as i have updated the state file and changed the MIG config using the gcloud command, so terraform will act as if the MIG was configured with OPPURTUNISTIC updates. However the whole point is it doesnt respect that and does an apply

`2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set 2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[1]: applying the planned Update change 2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set 2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[2]: applying the planned Update change 2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange 2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange 2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Received request: tf_proto_version=5.2 tf_req_id=c3e81199-8084-7e35-2228-40ee9bada2d9 @module=sdk.proto tf_provider_addr=provider tf_resource_type=google_compute_region_per_instance_config tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:801 timestamp=2023-01-24T11:27:08.131-0500 2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Received request: tf_rpc=ApplyResourceChange @module=sdk.proto tf_proto_version=5.2 tf_provider_addr=provider tf_req_id=03b07115-39e4-92ef-4045-f3ea404f1c93 tf_resource_type=google_compute_region_per_instance_config @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:801 timestamp=2023-01-24T11:27:08.131-0500 2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Sending request downstream: tf_provider_addr=provider tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_proto_version=5.2 tf_req_id=03b07115-39e4-92ef-4045-f3ea404f1c93 tf_resource_type=google_compute_region_per_instance_config @module=sdk.proto timestamp=2023-01-24T11:27:08.131-0500 2023-01-24T11:27:08.131-0500 [TRACE] plugin.terraform-provider-google_v4.45.0_x5: Sending request downstream: tf_rpc=ApplyResourceChange @module=sdk.proto tf_req_id=c3e81199-8084-7e35-2228-40ee9bada2d9 tf_resource_type=google_compute_region_per_instance_config @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_proto_version=5.2 tf_provider_addr=provider timestamp=2023-01-24T11:27:08.131-0500 2023/01/24 11:27:08 [DEBUG] EvalApply: ProviderMeta config value set 2023/01/24 11:27:08 [DEBUG] module.waf.google_compute_region_per_instance_config.hyc_instance_smig[0]: applying the planned Update change 2023/01/24 11:27:08 [TRACE] GRPCProvider: ApplyResourceChange`

**Comment by edwardmedia** [comment]
@sweetkrishiscool help me understand how you change the state file?

```as i have updated the state file```

**Comment by sweetkrishiscool** [comment]
I edited the state file manually from PROACTIVE to OPPORTUNISTIC, as the resource was already updated using gcloud command

**Comment by edwardmedia** [comment]
@sweetkrishiscool by using below config, I am able to update the type from `PROACTIVE` to `OPPORTUNISTIC`. From the terraform's perspective, I do not see anything wrong yet.

```
update_policy {
        max_surge_fixed         = 0
        max_unavailable_fixed   = 1
        minimal_action          = "REPLACE"
        replacement_method      = "RECREATE"
        type                    = "PROACTIVE"  ----> "OPPORTUNISTIC"
}
```
Below is what you expected. But I don't understand why `terraform shouldn't apply the change to the instances`?  Terraform should bring the resources up to match what you have in the **config**.  You said you have updated the type in the state. (I don't understand why you need to manually update the state file.)  Did you change the type in the config? 

```
Since i have changed the type of update to OPPORTUNISTIC, terraform shouldn't apply the change to the instances, however i see its still applying the changes.
```

**Comment by sweetkrishiscool** [comment]
Hi @edwardmedia i didnt mean the config change, its applying the new instance template automatically to the instances even with the OPPORTUNISTIC policy

**Comment by edwardmedia** [comment]
sorry I am still not quite clear what the issue is. @ScottSuarez can you help?
