### ISSUE TITLE
google_dns_managed_zone with force_destroy = true sometimes doesn't work

### ISSUE THREAD

**Issue by ngocannguyen02** [hashicorp/terraform-provider-google#13573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
* google_4.48.0

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
resource "google_dns_managed_zone" "my_zone" {
  name        = "example-zone"
  dns_name    = "example-${random_id.rnd.hex}.com."
  force_destroy = true 
}
```

### Debug Output

External-dns is used to populate some records in that zone

`Error: Error when reading or editing ManagedZone: googleapi: Error 400: The resource named 'example-zone' cannot be deleted because it contains one or more 'resource records'., containerNotEmpty`

### Expected Behavior

Expecting to remove the dns zone even with records in it. 

### Actual Behavior

Error blaming cannot remove the dns zone because of resource records. A second attempt to destroy usually succeeds but should work at the first attempt

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by edwardmedia** [comment]
@ngocannguyen02 you received an API error. I guess this is the behavior of this API. Where did you see below `Expected Behavior`?

```
Expecting to remove the dns zone even with records in it
```

**Comment by ngocannguyen02** [comment]
I was expecting the zone to be removed even when having records in it according to the doc (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone#force_destroy). 

Trying a second time usually succeed. I'm using terraform and don't want the state to drift by using gcloud.

**Comment by edwardmedia** [comment]
@ngocannguyen02 zone and records are separate resources, those are on different API calls. If you manage them all via terraform, and then just remove the zone not the records, what do you want to expect?

**Comment by edwardmedia** [comment]
@ngocannguyen02 can you share your debug log?

**Comment by ngocannguyen02** [comment]
Hmm by enabling TF_LOG = DEBUG, it's always working. Doing more tests

**Comment by ngocannguyen02** [comment]
Issue was on our side because of using two external-dns at the same time causing deletion error
