### ISSUE TITLE
Data Fusion: changing instance's version triggers forces replacement

### ISSUE THREAD

**Issue by ptran32** [hashicorp/terraform-provider-google#13576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/googlecloudplatform/cdap v0.10.0
+ provider registry.terraform.io/hashicorp/google v4.50.0
```

### Affected Resource(s)

`google_data_fusion_instance`

### Terraform Configuration Files

before the change
```tf
resource "google_data_fusion_instance" "instance" {

  name                          = "test"
  description                   = "test"
  region                        = "europe-west1"
  type                          = "BASIC"
  enable_stackdriver_logging    = false
  enable_stackdriver_monitoring = false
  version                       = "6.7.2"
  private_instance              = true

  network_config {
      network       = "just-data-infra-dev-vpc"
      ip_allocation = "10.37.70.0/22"
    }
}
```

after the change (version has changed)
```tf
resource "google_data_fusion_instance" "instance" {

  name                          = "test"
  description                   = "test"
  region                        = "europe-west1"
  type                          = "BASIC"
  enable_stackdriver_logging    = false
  enable_stackdriver_monitoring = false
  version                       = "6.8.0"
  private_instance              = true

  network_config {
      network       = "just-data-infra-dev-vpc"
      ip_allocation = "10.37.70.0/22"
    }
}
```

### Debug Output

Terraform plan (debug mode)

[https://gist.github.com/ptran32/eab553a4ef3b93a3e3d95acacd01f5c1](https://gist.github.com/ptran32/eab553a4ef3b93a3e3d95acacd01f5c1)

### Expected Behavior

Terraform plan should update in-place the instance without destroying it.

### Actual Behavior

Terraform plan shows it will destroy the old instance (with the old version) and create a new instance (with the new version set)
Terraform apply actually execute the plan and destroy it

### Steps to Reproduce

1. `replace the values region, network, ip_allocation with your settings
2. `terraform apply`

### Important Factoids

I'm authenticated as a user using gcloud auth login command

### References

* #0000

**Comment by edwardmedia** [comment]
@ptran32 where do you see this can be done without recreation?

**Comment by ptran32** [comment]
> @ptran32 where do you see this can be done without recreation?

On Google's UI when I upgrade the version, it does an upgrade of the current instance. 

The creation date remains the same, so I can confirm that it is the same instance.
