### ISSUE TITLE
updating node_pool labels force replacement of the node_pool - add accurate description

### ISSUE THREAD

**Issue by korenlev** [hashicorp/terraform-provider-google#13577]
### Affected Resource(s)
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.33.0
+ provider registry.terraform.io/hashicorp/google-beta v4.50.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1

### Terraform Configuration Files

resource "google_container_node_pool" "nodes" {
  for_each           = { for i, v in var.node_pools : i => v }
  name               = each.value.name
  location           = each.value.region
  cluster            = google_container_cluster.k8s.name
  initial_node_count = each.value.initial_node_count
  node_locations     = each.value.node_locations
  autoscaling {
    min_node_count = each.value.min_node_count
    max_node_count = each.value.max_node_count
    # only from 1.24 location_policy = "ANY"
  }
  timeouts {
    create = "20m"
    update = "20m"
  }
  node_config {
    taint        = each.value.taint
    preemptible  = false
    machine_type = each.value.machine_type
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/cloud-platform",
    ]
    service_account = each.value.node_service_account
    labels          = var.labels
  }
  lifecycle {
    ignore_changes = [initial_node_count, node_config[0].labels]
  }
  management {
    auto_upgrade = true
    auto_repair  = true
  }
  max_pods_per_node = each.value.max_pods
}

```

### Actual Behavior (PLAN)

# google_container_node_pool.nodes["0"] must be replaced
-/+ resource "google_container_node_pool" "nodes" {
      ~ id                          = "projects/cb4-production/locations/us-central1/clusters/ar-k8s-production/nodePools/ar-k8s-production-pool" -> (known after apply)
      ~ instance_group_urls         = [
.................................
        ] -> (known after apply)
      ~ managed_instance_group_urls = [
..................................
        ] -> (known after apply)
        name                        = "ar-k8s-production-pool"
      + name_prefix                 = (known after apply)
      ~ node_count                  = 1 -> (known after apply)
      + operation                   = (known after apply)
      ~ project                     = "cb4-production" -> (known after apply)
      ~ version                     = "1.22.15-gke.2500" -> (known after apply)
        # (5 unchanged attributes hidden)

      ~ node_config {
          ~ disk_size_gb      = 100 -> (known after apply)
          ~ disk_type         = "pd-standard" -> (known after apply)
          ~ guest_accelerator = [] -> (known after apply)
          ~ image_type        = "COS_CONTAINERD" -> (known after apply)
          ~ labels            = { # forces replacement
              + "gke"         = "true"
                # (3 unchanged elements hidden)
            }
          ~ local_ssd_count   = 0 -> (known after apply)

**Comment by korenlev** [comment]
currently we work around this in production by:
lifecycle {
    ignore_changes = [initial_node_count, node_config[0].labels]
  }

**Comment by korenlev** [comment]
seems a google bug/feature:
Update metadata in node pool FAILED
Updates for 'labels' are not supported in node pools with autoscaling enabled (as a workaround, consider temporarily disabling autoscaling or recreating the node pool with the updated values.).

my suggestion change: notify terraform on the actual reason for replacement

**Comment by edwardmedia** [comment]
@korenlev is this like a dup of https://github.com/hashicorp/terraform-provider-google/issues/12620? Let's close this if yes

**Comment by korenlev** [comment]
Actually it is pointing out that this is google limitation when node pool
is configured for auto scaling , and suggesting to send more accurate error
message

בתאריך יום ה׳, 26 בינו׳ 2023, 19:16, מאת Edward Sun ‏<
***@***.***>:

**Comment by edwardmedia** [comment]
@korenlev I don't know what you meant. I believe it is a dup. close now.
