### ISSUE TITLE
Stateful IP for MIG

### ISSUE THREAD

**Issue by geekette86** [hashicorp/terraform-provider-google#13570]
hi, when i try to create stateful  MIG, i had this problem even though i used google-beta (>=4.5.0)and google as providers 
```
resource "google_compute_instance_group_manager" "kafka" {
  name = var.hostname

  base_instance_name = var.machine_name
  zone               = var.zone

  version {
    instance_template  = module.kafka_instance_template.self_link
  }

  all_instances_config  {
    metadata = {
      metadata_key = var.tags
    }
    labels = {
      label_key = var.labels
    }
  }

  #target_pools = [google_compute_target_pool.kafka.id]
  target_size  = var.target_size

  stateful_disk {
    device_name = var.disk_name
    delete_rule = "NEVER"
  }
  
  stateful_internal_ip {
    network_interface_name = "nic0"
    delete_rule = "NEVER"

  }
}
```
Result after terrform apply : 
```
Error: Unsupported block type
│ 
│   on compute-beta.tf line 48, in resource "google_compute_instance_group_manager" "kafka":
│   48:   all_instances_config  {
│ 
│ Blocks of type "all_instances_config" are not expected here.
╵
╷
│ Error: Unsupported block type
│ 
│   on compute-beta.tf line 64, in resource "google_compute_instance_group_manager" "kafka":
│   64:   stateful_internal_ip {
│ 
│ Blocks of type "stateful_internal_ip" are not expected here.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@geekette86 can you try adding below line in your config?

```
provider = google-beta
```

**Comment by geekette86** [comment]
@edwardmedia i already mentioned that i put both provider :)
