### ISSUE TITLE
Terraform module/resource for moving folder under another folder

### ISSUE THREAD

**Issue by amar2k05** [hashicorp/terraform-provider-google#13572]
Hi,
I have a requirement in managing folders in GCP, I want to move one folder under another folder.
Example: I have below folder structure and want to move sub folder named "sub_folder" under "folder2"
![image](https://user-images.githubusercontent.com/49494024/214591469-cc257fe9-4d06-4d08-a535-258367660394.png)

Is there any terraform resource/module to achieve this without dropping and re-creating the sub folder?
We have below gcloud command to do this, but was not able to find any equivalent terraform resource/module.

**gcloud resource-manager folders move [FOLDER_ID] --folder=[PARENT_ID]**

Kindly let me know if there is a way to achieve this in terraform.

### ### 

Thanks,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 here is the example of `google_folder`. Can you provide parent with `folder2` and then reapply the config?

```tf
resource "google_folder" "team-abc" {
  display_name = "Team ABC"
  parent       = google_folder.department1.name
}
```

**Comment by amar2k05** [comment]
Hi Edward,
I have tried below.

//Create Folder1
resource "google_folder" "folder1" {
  display_name = "folder1"
  parent       = "organizations/12345678934"
}

//Create Folder2
resource "google_folder" "folder2" {
  display_name = "folder2"
  parent       = "organizations/12345678934"
}

//Create sub_folder under folder1
resource "google_folder" "sub_folder" {
  display_name = "sub_folder"
  parent       = google_folder.folder1.name
}

Now, used below to move the folder

resource "google_folder" "sub_folder" {
  display_name = "sub_folder"
  parent       = google_folder.folder2.name
}

But as expected this is again creating the folder under "folder2" but not moving.

Thanks,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 I tested and it seems fine with me. What do you mean `but not moving`?

**Comment by amar2k05** [comment]
Hi Edward,
Thanks for your response.
Yes you are right, the folder got moved without changing the folder id. This is achievable when we use the terraform **"resource"**, but we have used terraform module **"terraform-google-modules/folders/google"** to create the folders and sub-folders in our organization. This module is creating the folder and not moving. PFB.

**Step1:** Creating folders names "folder1" & "folder2" under organization.
**Step2:** Creating sub-folders named "sub_folder1", "sub_folder2" & "sub_folder3" under "folder1"
**Step3:** Trying to move "sub_folder1" which is currently under "folder1" to "folder", but here it's creating a sub folder named "sub_folder1" under "folder2".
I think this is a default behaviour, but is there any way to move folders in GCP using terraform when we use modules i.e. Historically we have created folders & sub-folders using TF module and not resource.

**Step1:**
module "test_folders" {
  source  = "terraform-google-modules/folders/google"
  version = "3.1.0"
  parent  = "organizations/${var.org_id}"
  names = ["folder1","folder2"]
}

**Step2:**
module "test_sub_folder" {
  source  = "terraform-google-modules/folders/google"
  version = "3.1.0"
  parent  = module.test_folders.ids.folder1
  names = ["sub_folder1","sub_folder2","sub_folder3"]
}

**Step3:**
module "test_sub_folder_move" {
  source  = "terraform-google-modules/folders/google"
  version = "3.1.0"
  parent  = module.test_folders.ids.folder2
  names = ["sub_folder1"]
}

Regards,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 this is more about how to use the module. In this case, the provider works as expected, there is not much the provider can help. Closing the question now. Feel free to reopen if you need to continue the research. Thanks
