### ISSUE TITLE
Documentation around timeout_sec argument for LB Backend needs update / clarification

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#13587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.4

### Affected Resource(s)

* google_compute_backend_service
* google_compute_region_backend_service

### Terraform Configuration Files

```
resource "google_compute_backend_service" "default" {
  timeout_sec           = 86401
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Value should be rejected since it falls outside documented range of 1-86400 (1 day)

### Actual Behavior

Value is accepted as it's well within Google accepted max of 2^31 - 1 seconds.  

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Just looks like a documentation update that's needed.  

In addition to the max value, it would be extremely useful to mention that this value sets the _max request / response time_ for HTTP(S) load balancers, but acts as an _idle timeout_ value for TCP and SSL Proxies.  The setting is completely ignored for internal TCP/UDP load balancers.    Google mentions this in the gCloud documentation, but doesn't make the distinction when using the Web UI which I suspect is causing some confusion.  

### References

- https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting 
- https://cloud.google.com/sdk/gcloud/reference/compute/backend-services/update 
- https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/update
- https://cloud.google.com/compute/docs/reference/rest/v1/regionBackendServices/update 

* #0000

b/317497334

**Comment by melinath** [comment]
This looks like a simple docs update for timeoutSec - the [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) for the resource have the correct value.

**Comment by pawelJas** [comment]
@melinath Docs have been updated. Could you close this issue, please?

**Comment by melinath** [comment]
Closed by https://github.com/hashicorp/terraform-provider-google/pull/18400
