### ISSUE TITLE
google_storage_transfer_job is there a way to specify agent pool?

### ISSUE THREAD

**Issue by s2tu** [hashicorp/terraform-provider-google#13596]
The documentation for google_storage_transfer_job in terraform does not include a way to switch the "source agent pool name".

[https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#:~:text=%7D%2C%0A%20%20%22-,sourceAgentPoolName,-%22%3A%20string](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#:%7E:text=%7D%2C%0A%20%20%22-,sourceAgentPoolName,-%22%3A%20string)

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job

Is this a bug / missing feature in the provider ? or is there a way I can change this via terraform that isn't mentioned in the doc.

[google-cloud-platform](https://stackoverflow.com/questions/tagged/google-cloud-platform)[terraform](https://stackoverflow.com/questions/tagged/terraform)

**Comment by aclaypool** [comment]
I think this is a needed enhancement, so filed [issue 13626](https://github.com/hashicorp/terraform-provider-google/issues/13626)

**Comment by edwardmedia** [comment]
Agreed with @aclaypool Filing an enhancement is a good way to go. Closing this question then
