### ISSUE TITLE
google_service_account_iam_binding does not work with Workload Identity syntax

### ISSUE THREAD

**Issue by brad-taylor-yvr** [hashicorp/terraform-provider-google#13595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
terraform version:
Terraform v1.3.7
on linux_amd64

### Affected Resource(s)

* google_service_account_iam_binding

### Terraform Configuration Files

```
resource "google_service_account_iam_binding" "gsa_ksa_wli_binding" {
    service_account_id = "projects/enterprise-google-project-abc/serviceAccounts/gsa-for-ksa@enterprise-google-project-abc.iam.gserviceaccount.com"   
    role = "roles/iam.workloadIdentityUser"
    members = [
        "serviceAcccount:enterprise-google-project-abc.svc.id.goog[k8s-namespace/k8s-sa]"
   ]
}
```

### Debug Output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_service_account_iam_binding.gsa_ksa_wli_binding will be created
  + resource "google_service_account_iam_binding" "gsa_ksa_wli_binding" {
      + etag               = (known after apply)
      + id                 = (known after apply)
      + members            = [
          + "serviceAcccount:enterprise-google-project-abc.svc.id.goog[k8s-namespace/k8s-sa]",
        ]
      + role               = "roles/iam.workloadIdentityUser"
      + service_account_id = "projects/enterprise-google-project-abc/serviceAccounts/gsa-for-ksa@enterprise-google-project-abc.iam.gserviceaccount.com"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
google_service_account_iam_binding.gsa_ksa_wli_binding: Creating...
╷
│ Error: Error applying IAM policy for service account 'projects/enterprise-google-project-abc/serviceAccounts/gsa-for-ksa@enterprise-google-project-abc.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/enterprise-google-project-abc/serviceAccounts/gsa-for-ksa@enterprise-google-project-abc.iam.gserviceaccount.com': googleapi: Error 400: The member serviceAcccount:enterprise-google-project-abc.svc.id.goog[k8s-namespace/k8s-sa] is of an unknown type. Please set a valid type prefix for the member., badRequest
│ 
│   with google_service_account_iam_binding.gsa_ksa_wli_binding,
│   on shared-cloud-sql.tf line 61, in resource "google_service_account_iam_binding" "gsa_ksa_wli_binding":
│   61: resource "google_service_account_iam_binding" "gsa_ksa_wli_binding" {
│ 
```

### Expected Behavior

binding should have been created

### Actual Behavior

TF apply emitted error message

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- Running in Cloud Build
- trying to replicate the instructions from Google's Workload Identity how-to page, step No 6 cf [1]

```
gcloud iam service-accounts add-iam-policy-binding gsa-for-ksa@enterprise-google-project-abc.iam.gserviceaccount.com \
    --role roles/iam.workloadIdentityUser \
    --member "serviceAccount:enterprise-google-project-abc.svc.id.goog[k8s-namespace/k8s-sa]"
```

### References

* [1] https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
* #4765

**Comment by SarahFrench** [comment]
👋 Hi @brad-taylor-yvr , could you please check if the issue is fixed by changing the value of `members` to remove the extra `c` in `"serviceAcccount`? I think that's the type prefix that the error refers to.

**Comment by brad-taylor-yvr** [comment]
Thank you @SarahFrench ... your keen eyes spotted the problem. 👏 
Fixing that typo solved the problem.
