### ISSUE TITLE
Enhancement: GCP datastream google_datastream_stream add source config for Oracle and Postgres

### ISSUE THREAD

**Issue by toandm** [hashicorp/terraform-provider-google#13599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As of version 4.50.0 for provider "google", the `google_datastream_stream` resource only has source config for MySQL source only. I want to use Terraform to create a stream for a Postgres and Oracle source.

This error is output when trying to run `terraform apply` anyway.
```
Error creating Stream: googleapi: Error 400: Invalid stream configuration: [Incompatible Source Connection Profile and Source Configuration. The Connection Profile is of type "POSTGRESQL_PROFILE" and the Configuration is of type "MYSQL_SOURCE_CONFIG"].
```

### New or Affected Resource(s)

* google_datastream_stream

### Potential Terraform Configuration

```tf
resource "google_datastream_stream" "test_stream" {
  stream_id     = "test-postgres"
  location      = "asia-southeast1"
  display_name  = "test-postgres"
  source_config {
    source_connection_profile = google_datastream_connection_profile.test_postgres.id
    postgresql_source_config {
        include_objects {}
        exclude_objects {}
    }
  }

}
```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/datastream_stream#source_config

**Comment by juleslenotte** [comment]
PG support would be very useful. My current need is to replicate data from PG to BigQuery. It works great but I need to industrialize it.

**Comment by melinath** [comment]
This is now supported by the google_datastream_stream resource.
