### ISSUE TITLE
Action: compute.instanceGroups.addInstances is not supported 

### ISSUE THREAD

**Issue by 597040593** [hashicorp/terraform-provider-google#13602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on linux_amd64

provider registry.terraform.io/hashicorp/google v4.47.0
provider registry.terraform.io/hashicorp/google-beta v4.47.0

### Affected Resource(s)

* google_compute_instance_group

### Expected Behavior

Hi, I am currently exploring the Terraform to implement compute.instanceGroups.addInstances which seems not provided in the documentation. Is there any Terraform configuration I could use?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by 597040593** [comment]
https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroups/addInstances
I just want to realize this API in Terraform, btw I may publish this report to Enhancement

**Comment by edwardmedia** [comment]
@597040593 terraform is more `declarative`. To achieve `add` action, it seems needing an `imperative` tool. I think this might not be a good use case. But feel free to change the issue to `enhancement` so it can be triaged.

**Comment by edwardmedia** [comment]
@597040593 does this make sense?

**Comment by rileykarson** [comment]
Terraform doesn't allow you to make imperative API calls directly, but may represent them declaratively. In this case, [`addInstances` is used internally by the provider](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_compute_instance_group.go#L372-L373) to update the [`instances` field](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group#instances).

**Comment by sangram-pawar** [comment]
> @597040593 look at the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group#example-usage---with-instances-and-named-ports), the [instances](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group#instances) is a list. Can you add instance in it? If this is not what you plan to do, can you explain the details and how you can achieve that using other tools?

Hi, we cannot create instance groups with instances in it. This is because instance also needs forwarding rules which requires backend services which requires instance groups. So the only option is add instances to instance groups later. Hence we need a some way in TF to perform an equivalent of DM "action".
