### ISSUE TITLE
Option to delete previous cluster and sync with new cluster state when restoring an AlloyDB database

### ISSUE THREAD

**Issue by jdub55** [hashicorp/terraform-provider-google#13601]
Currently, the Terraform module for AlloyDB supports backup and restore, but it does not manage the state of the AlloyDB cluster. When restoring an AlloyDB database, by design, a new cluster is created when the database is restored. 
As a DevOps Engineer, I would like Terraform to manage the state of AlloyDB associated with the backup / restore process so that when I restore a database from a backup, there is an option to remove the old cluster once the restore process has completed. (e.g. a boolean flag that controls keeping or destroying the old cluster that is being restored from backup)

**Comment by edwardmedia** [comment]
@jdub55 what state do you mean? Could you give more details what you are trying to achieve? 

```
but it does not manage the state of the AlloyDB cluster.
```

**Comment by jdub55** [comment]
"The state we’re referring to is the Terraform state that keeps track of the controlled resources.

If we use Terraform to provision an AlloyDB cluster/instance with backups enabled, in order to give users the ability to ‘Restore’ those backups they also require the permission to create AlloyDB clusters/instances, this is because the Restore operation creates an entirely new cluster – which is where the problem with state comes into play.

If a user does a Restore operation (or otherwise manually creates a new AlloyDB cluster), the newly created AlloyDB cluster/instance won’t be tracked by Terraform, so we lose alignment between what Terraform knows about and the actual state of things.

If there were a way for Terraform to provision an AlloyDB cluster/instance from a given Restore point, then Terraform state and actual state would align, and we could build an interface to allow Users to run restore operations, while also not directly granting them the permission to create new clusters.

As it is, the AlloyDB backup/restore paradigm does not align with Terraform management principles."

**Comment by edwardmedia** [comment]
@jdub55 for the recommended workflow, you may restore the instance from the backup using other tools and then sync the terraform state with the restored instance by running `tf import`. How does this sound?

**Comment by fishpen0** [comment]
I opened an issue to request the ability to restore from the backup natively in the cluster resource here: https://github.com/hashicorp/terraform-provider-google/issues/13757. Since backups launch new clusters when they are restored, this seemed to be the ideal way to make it work and aligns with similar patters in other providers for similar databases

**Comment by edwardmedia** [comment]
@fishpen0 cool. I am closing this issue then
