### ISSUE TITLE
Failing test(s): TestAccCompute* ("Error 400: Cloud KMS error" permissions denied)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13609]
Failure rate: 38% failure since April 18th 2023

### Affected Resource(s)
* google_compute_instance_template

Impacted tests:
- ~~TestAccComputeInstanceTemplate_sourceSnapshotEncryptionKey~~ - this is now passing 100%
- TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey
- ~~TestAccComputeRegionInstanceTemplate_sourceSnapshotEncryptionKey~~ - this is now passing 100%
- TestAccComputeImage_imageEncryptionKey
- ~~TestAccComputeInstanceTemplate_sourceImageEncryptionKey~~ - this is now passing 100%

Nightly builds:
- ~~[TestAccComputeInstanceTemplate_sourceSnapshotEncryptionKey](https://hashicorp.teamcity.com/test/-4109935072844408801?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)~~ - this is now passing 100%
- [TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey](https://hashicorp.teamcity.com/test/1253905709001703553?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- ~~[TestAccComputeRegionInstanceTemplate_sourceSnapshotEncryptionKey](https://hashicorp.teamcity.com/test/-3646394956934120649?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)~~ - this is now passing 100%
- [TestAccComputeImage_imageEncryptionKey](https://hashicorp.teamcity.com/test/2589003762149855871?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- ~~[TestAccComputeInstanceTemplate_sourceImageEncryptionKey](https://hashicorp.teamcity.com/test/1158755514786700516?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)~~ - this is now passing 100%

Message:

```
Error: Error creating Snapshot: googleapi: Error 400: Cloud KMS error when using key projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1: Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource 'projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1' (or it may not exist)., kmsPermissionDenied
```

**Comment by rileykarson** [comment]
Note: This shared key may be a predecessor to a bootstrapped key, and we may want to convert it to one.

**Comment by megan07** [comment]
The error has changed here: `Error 409: The resource 'projects/ci-test-project-188019/zones/us-central1-a/disks/debian-disk' already exists, alreadyExists`, we likely need to randomize the name on that disk.

**Comment by roaks3** [comment]
This was 100% until Mar 10, 2023 with the "already exists" error. Since then, we have seen the original error again at 32%.

This test appears to use its own service account for encryption, and it is configured to have the `roles/cloudkms.cryptoKeyEncrypterDecrypter` role (which includes `cloudkms.cryptoKeyVersions.useToEncrypt`), but I don't see a `depends_on` field to make sure we wait for the permission to be created. It's possible that all we need is that dependency to ensure the permission is available.

**Comment by SarahFrench** [comment]
`TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey` has still been failing due to this issue - 70% failure since migrating to the new TeamCity projects (i.e. as far back as our data goes it's been flaky due to this issue).

I've just been addressing a similar issue (https://github.com/hashicorp/terraform-provider-google/issues/16687) where I can see lots of failures in the nightly tests for TPGB and I fixed a Beta-specific test that was authoritatively controlling an IAM binding on a cryptokey. 

I think _this_ GH issue is due to an acceptance test doing a similar thing, but there must be a test that's present in the GA provider (probably both GA/Beta).

**Comment by SarahFrench** [comment]
TestAccComputeInstanceTemplate_sourceImageEncryptionKey now passing 100%

TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey should also become the same way now that https://github.com/GoogleCloudPlatform/magic-modules/pull/9644 is merged

**Comment by SarahFrench** [comment]
This PR (https://github.com/GoogleCloudPlatform/magic-modules/pull/9673) will fix TestAccComputeImage_imageEncryptionKey

**Comment by melinath** [comment]
Marking as forward/exempt since Sarah's working on this.

**Comment by SarahFrench** [comment]
Closing as stale
