### ISSUE TITLE
`google_compute_intstance`: please add `metadata_userdata`, `metadata_userdata_encoding` that behave like `metadata_startup_script`

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform-provider-google#13616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_compute_instance` provides a way to force recreation when the startup script changes: `metadata_startup_script`.  This is great, unless you're using cloud-init - which relies on different metadata keys.

I'd like `metadata_userdata` and `metadata_userdata_encoding` which behave exactly the same, but load data into the `user-data` and `user-data-encoding` metadata keys.  This way, if I change the user data fed into cloud init, terraform will know to force recreation.

Alternatively, you could add a `replace_instance_on_metadata_change` field that takes a list of keys that trigger this behavior.

Unfortunately, I don't think `lifecycle`'s `replace_triggered_by` can help - it requires a resource reference.

For others that confront this, I have this workaround:
```tf
locals {
    user_data = file("${path.module}/cloud-config.yaml")
}

resource "google_compute_instance" "vm" {
    ...
    metadata = {
        user-data = local.user_data
    }
    metadata_startup_script = "echo ${md5(local.user_data)}"
}
```

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

```tf
resource "google_compute_instance" "vm" {
    ...
    metadata_userdata = file("${path.module}/cloud-config.yaml")
}
```

### References
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata_startup_script

**Comment by rileykarson** [comment]
There's an awkward-ish construct to use `replace_triggered_by`, see https://developer.hashicorp.com/terraform/language/resources/terraform-data#example-usage-data-for-replace_triggered_by

I don't want to generalise for all well-known metadata keys even those that need to be set during create, and we likely would have not implemented `metadata_startup_script` as it is today. Because this is awkward to write/discover we could consider adding an example to the docs, although we'd want to cover that with a separate issue.
