### ISSUE TITLE
Create a sweeper for `google_access_context_manager_access_policy` resources to help overnight build tests

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13628]
# Background

The TestAccAccessContextManager test failed consistently recently because a policy resource already existed before the  test ran. See GH issue about it here : https://github.com/hashicorp/terraform-provider-google/issues/13627

# What kind of contribution is this issue about?

Acceptance tests + sweepers

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google/issues/13627

# Details

The `google_access_context_manager_access_policy` resource is a singleton (only one can be made per org) so it needs to be removed for the test to re-run, but also it'll be easy to address with a sweeper.

Riley mentioned that it might be a good idea to make a handwritten sweeper for the policy, and as it's a singleton it can be identified using list methods from the API. The alternative is manual cleanup by someone with permissions on the nightly build project(s)

**Comment by hao-nan-li** [comment]
Note: I quickly scanned in several nightly test runs in May and noticed that occasionally the following error occurs:

`Error: Error setting IAM policy for accesscontextmanager accesspolicy "accessPolicies/300755759150": googleapi: Error 409: The operation was aborted.`

Usually on the next day the test will pass. Looks like there's some edge case that caused this error. (This might or might not be related to the sweeper).

**Comment by hao-nan-li** [comment]
Closing this as recently the test `TestAccAccessContextManager` consistently passed in the nightly builds. The sweeper log shows that `gcp_access_context_manager_policy` completes the run without errors.
