### ISSUE TITLE
Failing test(s): TestAccDataprocVirtualCluster_basic

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13635]
- Failure rate: 65% (20/31) Jan 23
- Was worse in Nov/Dec '22
- Failure rate: 22.6% in Mar 23

Impacted tests:
- TestAccDataprocVirtualCluster_basic

Nightly builds:
- [Test History: TestAccDataprocVirtualCluster_basic
](https://ci-oss.hashicorp.engineering/test/-2609347352367538293?currentProjectId=GoogleCloud&branch=%3Cdefault%3E)

Message:

```
------- Stdout: -------
=== RUN   TestAccDataprocVirtualCluster_basic
=== PAUSE TestAccDataprocVirtualCluster_basic
=== CONT  TestAccDataprocVirtualCluster_basic
provider_test.go:307: Step 1/1 error: Error running apply: exit status 1
Error: Error waiting for creating Dataproc cluster: Error code 2, message: GKE Operation operation-1675342929457-e1b6b341 is in RUNNING state, expecting DONE
with google_dataproc_cluster.virtual_cluster,
on terraform_plugin_test.tf line 29, in resource "google_dataproc_cluster" "virtual_cluster":
29: resource "google_dataproc_cluster" "virtual_cluster" {
--- FAIL: TestAccDataprocVirtualCluster_basic (1022.65s)
FAIL

```

### Affected Resource(s)

- google_dataproc_cluster

b/299683658

**Comment by shuyama1** [comment]
This may be due to a known upstream issue b/260182223

**Comment by melinath** [comment]
This is still happening occasionally.

**Comment by melinath** [comment]
No longer seeing this error message.
