### ISSUE TITLE
Failing test(s): SqlDatabaseInstance - Error waiting for Create Instance

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13637]
Failure rate:

Impacted tests:
- TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica
- TestAccSqlDatabaseInstance_basicMSSQL
- TestAccSQLDatabase_sqlDatabaseDeletionPolicyExample

Nightly builds:
- In the same TPG build [#f323a73](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/372000) these tests failed due to the same reason
    - TestAccSqlDatabaseInstance_basicMSSQL
    - TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica
    - TestAccSQLDatabase_sqlDatabaseDeletionPolicyExample

Message:

```
------- Stdout: -------
=== RUN   TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica
=== PAUSE TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica
=== CONT  TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica
provider_test.go:307: Step 1/3 error: Error running apply: exit status 1
Error: Error waiting for Create Instance:
with google_sql_database_instance.instance,
on terraform_plugin_test.tf line 3, in resource "google_sql_database_instance" "instance":
3: resource "google_sql_database_instance" "instance" {
--- FAIL: TestAccSqlDatabaseInstance_dontDeleteDefaultUserOnReplica (211.42s)
FAIL
```

Older example ([build link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/359018)) mentions this timeout:

```
------- Stdout: -------
=== RUN   TestAccSqlDatabaseInstance_basicMSSQL
=== PAUSE TestAccSqlDatabaseInstance_basicMSSQL
=== CONT  TestAccSqlDatabaseInstance_basicMSSQL
provider_test.go:307: Step 1/4 error: Error running apply: exit status 1
Error: Error waiting for Create Instance: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 30m0s)
with google_sql_database_instance.instance,
on terraform_plugin_test.tf line 3, in resource "google_sql_database_instance" "instance":
3: resource "google_sql_database_instance" "instance" {
--- FAIL: TestAccSqlDatabaseInstance_basicMSSQL (1806.77s)
FAIL
```

References

- Seems similar to this: https://github.com/hashicorp/terraform-provider-google/issues/10217

### Affected Resource(s)

- google_sql_database_instance

**Comment by mmizutani** [comment]
The root cause might be the same as https://github.com/hashicorp/terraform-provider-google/issues/13603.
The small, for-development-only tiers of MySQL and MSSQL instances often take unusually long time (sometimes longer than 30 minutes) to create at least in the us-central1 region.

**Comment by roaks3** [comment]
It looks like all 3 of these failed on the Feb 1 run, but otherwise have been passing 100% since then and prior to that (based on current history we have). All of the SQL tests were experiencing issues with the timeout for a while, but I think the increase to 40 mins should have resolved that until we [take steps to speed them up](https://github.com/hashicorp/terraform-provider-google/issues/13603).

I'm tempted to say we close this one, since we would have trouble reproducing it at the moment.

**Comment by SarahFrench** [comment]
I agree about closing this - Feb 1st was a bit of an anomaly and if the same happens again this issue can be searched for and re-opened/referenced in new issue
