### ISSUE TITLE
Failing test(s): TestAccMonitoringNotificationChannel_update

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13638]
Failure rate:  New

Looks like an API validation changed?

Impacted tests:
- TestAccMonitoringNotificationChannel_update

Nightly builds:
- [Failed in this build - first time](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/372030)

Message:

```
------- Stdout: -------
=== RUN   TestAccMonitoringNotificationChannel_update
=== PAUSE TestAccMonitoringNotificationChannel_update
=== CONT  TestAccMonitoringNotificationChannel_update
provider_test.go:315: Step 3/4 error: Error running apply: exit status 1
Error: Error updating NotificationChannel "projects/ci-test-project-188019/notificationChannels/9794609016602238869": googleapi: Error 400: Field labels[number] had an invalid value of "+15555379009": Phone number is not valid
with google_monitoring_notification_channel.update,
on terraform_plugin_test.tf line 3, in resource "google_monitoring_notification_channel" "update":
3: resource "google_monitoring_notification_channel" "update" {
--- FAIL: TestAccMonitoringNotificationChannel_update (26.77s)
FAIL
```

### Affected Resource(s)

- google_monitoring_notification_channel

**Comment by SarahFrench** [comment]
Looks like this code needs to be updated?

https://github.com/hashicorp/terraform-provider-google-beta/blob/d9da1106eb42f79c20dfec95358535d2a548249b/google-beta/resource_monitoring_notification_channel_test.go#L27

**Comment by roaks3** [comment]
@SarahFrench yea, I think you're right about updating the test there. If you haven't already started on a solution here, would you mind if we pick this one up as part of our Fixit next week? We will be focusing on working through our test failures.
