### ISSUE TITLE
"grpc: error while marshaling: string field contains invalid UTF-8.." in 4.51.0 windows_amd64

### ISSUE THREAD

**Issue by Ziemowit-LH** [hashicorp/terraform-provider-google#13630]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.51.0

Same with Terraform v1.2.9

### Affected Resource(s)
Provider itself.

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      version = "= 4.51"
    }
  }
}

provider "google" {}
```

### Debug Output
https://gist.github.com/Ziemowit-LH/afb8cee9c8984397121f9c2a51c57242

### Expected Behavior
Plan successful.

### Actual Behavior
```
╷
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/google: failed to retrieve schema from provider "registry.terraform.io/hashicorp/google": Plugin error: The plugin        
│ returned an unexpected error from plugin.(*GRPCProvider).GetProviderSchema: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8..
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

google provider 4.50 does not have this behaviour.
Does not happen for Terraform v1.3.6 on linux_amd64

### References

azurerm provider experience(d) same error:
* [#17563](https://github.com/hashicorp/terraform-provider-azurerm/issues/17563)
* [#12960](https://github.com/hashicorp/terraform-provider-azurerm/issues/12960)
* [#13182](https://github.com/hashicorp/terraform-provider-azurerm/issues/13182)

**Comment by edwardmedia** [comment]
looks like a terraform code issue.

**Comment by guoshaodong** [comment]
try to transfer it by []byte

**Comment by Ziemowit-LH** [comment]
> looks like a terraform code issue.
> 
> @Ziemowit-LH do you have a specific config that I can use to repro the issue?

Hello,
This is very weird.
I tried to replicate this today and it's not happening, while 4 days ago I it was happening consistently both in VS Code terminal and in Windows Terminal (Powershell).
The debug trace is the same up to the error too...

I have to close this issue then. Must have been something weird on my machine.
