### ISSUE TITLE
After removing a role from non-authoritative project_iam_member resource, should terraform delete the role in the infrastructure?

### ISSUE THREAD

**Issue by intotecho** [hashicorp/terraform-provider-google#13648]
project_iam_member is  "Non-authoritative. Updates the IAM policy to grant a role to a new member. Other members for the role for the project are preserved." 

But this doesn't explain what happens to the infrastructure when you remove a role from the config.
So should it remove the role or preserve it? What if there are other non-authoritative admins who also added that role? 

I have split a terraform config for a project into two separate modules. Each has its own state.
This is because I wish to migrate IAM from one to the other. 

I have a project_iam_member resource in the first config that adds roles to a service account member.
But when I run the second config, it removes the roles that are not specified. 

So now I have the same roles added to both configs - which I need to keep in sync. Is there a better solution?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam

**Comment by edwardmedia** [comment]
@intotecho it should. After you remove the roles in your config, terraform detects the changes and calls the api with `delete`. If you see the behavior different, let me know.

When you have the same roles in two different configs, and remove a role from one of them, terraform will delete the role. To sync, have you looked at terraform features like [lifecycle](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to see if that help your need?

**Comment by intotecho** [comment]
Hi Edward, thanks for the suggestion. I am also investigating [terraform state rm](https://developer.hashicorp.com/terraform/cli/commands/state/rm) to remove the state from the old config to see if that will solve the issue.

**Comment by edwardmedia** [comment]
@intotecho state rm is another approach. Hope you can get your issue resolved. Closing this question now.
