### ISSUE TITLE
Remove obsolete and unused MMv1 definition files for hand-written resources and data sources

### ISSUE THREAD

**Issue by mmizutani** [hashicorp/terraform-provider-google#13647]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Some of the resources and data sources were originally defined for auto-generation using the standard MMv1 template files such as [`magic-modules/mmv1/products/sql/api.yaml`](https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/products/sql/api.yaml) and [`magic-modules/mmv1/templates/terraform/examples/sql_mysql_instance_private_ip.tf.erb`](https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/templates/terraform/examples/sql_mysql_instance_private_ip.tf.erb`), and then later converted to hand-written Go template files such as [`magic-modules/mmv1/third_party/terraform/resources/resource_sql_database_instance.go.erb`](https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/third_party/terraform/resources/resource_sql_database_instance.go.erb) and [`magic-modules/mmv1/third_party/terraform/tests/resource_sql_database_instance_test.go.erb`](https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/third_party/terraform/tests/resource_sql_database_instance_test.go.erb).

For such resources and data sources that are currently hand-written and no longer auto-generated based on MMv1 templates, we no longer need to keep and maintain the MMv1 template and examples files.

> Add an MMv1 resource
> Generated resources are created using the mmv1 code generator, and are configured by editing definition files under the mmv1/products path. Go to the service for your resource like compute and open the api.yaml and terraform.yaml files. In each of those, find the resource’s properties field.
> For example, for google_spanner_database:
>   api.yaml
>   terraform.yaml

https://googlecloudplatform.github.io/magic-modules/docs/how-to/add-mmv1-resource/

> Add an MMv1 test
> For generated resources, you can add an example to the mmv1/templates/terraform/examples directory, which contains a set of templated Terraform configurations.

https://googlecloudplatform.github.io/magic-modules/docs/how-to/add-mmv1-test/

However, some of the MMV1 template and example files that are no longer used remain in the [magic-module repository](https://github.com/GoogleCloudPlatform/magic-modules).
This situation would be confusing for new contributors and would unnecessarily increase maintenance burden.

For example, the `google_sql_database_instance` code is hand-written and no longer relies upon MMv1 resource definition and ERB examples files, but the PR https://github.com/GoogleCloudPlatform/magic-modules/pull/5912 edited the examples files, which are no longer used for generating the [published document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance).

To enhance development productivity, the MMv1 template and examples files that were previously used for auto-generation of resource data source code but are no longer used due to the conversion of those definitions to hand-written files should be deleted from the repository.

### New or Affected Resource(s)

I have not thoroughly investigated all the resource and data source files, but at least the following are relevant:

* `google_sql_database_instance` resource

The following portion and files seem to be no longer used and should be removed:

- https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/products/sql/api.yaml#L51-L469
- [magic-modules/mmv1/products/sql/terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/products/sql/terraform.yaml)
- `magic-modules/mmv1/templates/terraform/examples/sql_*instance*.tf.erb`

### References

- https://github.com/GoogleCloudPlatform/magic-modules/pull/6986/files#r1091234371
- https://github.com/GoogleCloudPlatform/magic-modules/pull/6986#discussion_r1091234445

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/12509
