### ISSUE TITLE
Unlink billing account post GCP Project destroy

### ISSUE THREAD

**Issue by vugardzhamalov** [hashicorp/terraform-provider-google#13659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.50.0
+ provider registry.terraform.io/hashicorp/google-beta v4.50.0 

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
resource "google_project" "this" {

  name = local.google_project_display_name
  project_id = "${local.google_project_display_name}-${random_string.gcp_project_id_suffix.result}"
  billing_account = local.google_project_billing_account
  skip_delete = local.google_project_skip_delete
  auto_create_network = local.google_project_auto_create_network
  folder_id = local.google_project_folder_id 

}


```

### Expected Behavior

Once we issue 'terraform destroy' GCP Project should be unlinked from the billing account.

### Actual Behavior

At the moment once GCP Project is destroyed - it does NOT get unlinked from the billing account.

### Steps to Reproduce

1. `terraform destroy`

### References

* #0000

**Comment by vugardzhamalov** [comment]
Following does the job, but I wonder if project won't get unlinked form the billing account by design? Is this how it is intended to work?

```tf
provisioner "local-exec" {
    when = destroy
    command = "gcloud config set project ${self.project_id}; gcloud beta billing projects unlink ${self.project_id} --quiet"
}
```

**Comment by edwardmedia** [comment]
@vugardzhamalov what did you provide `skip_delete = local.google_project_skip_delete`? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project#skip_delete

**Comment by vugardzhamalov** [comment]
Thank you for coming back to me so quickly @edwardmedia !
For the sake of it just tried with both set to 'true' and 'false', in both of the cases my result is the same: project won't get unlinked from the billing account. Please let me know if there is any further info needed on the matter.

**Comment by edwardmedia** [comment]
@vugardzhamalov somehow when I use below config, `tf apply`: I see see the project list in the Manage Resources on the org level. Then  `tf destroy`, the project is gone in the list. It is fine with me. 

```
resource "google_project" "my_project" {
  name       = "issue13659"
  project_id = "issue13659"
  org_id     = "my_org"
  billing_account = "my_billing"
  skip_delete = false
  auto_create_network = false
}
```

Can you share your debug log? And the screenshot where you see the project unlinked after destroy?

**Comment by vugardzhamalov** [comment]
Yes @edwardmedia,  I am seeing the same thing. This is not what this issue is about. Let me try to clarify:

1. To create a new GCP Project simply issue 'terraform apply' and you will end up with a new GCP Project which is **_linked_** to your billing account.
2. To delete earlier created GCP Project simply issue 'terraform destroy' and you will end up with deleted GCP Project. But in my case GCP Project ID will **_NOT_** be unlinked from my billing account. Are you observing the same?

Now I am simply trying to understand if this is actually expected behavior - meaning I would like to know if deletion of the GCP Project via Terraform should end up with this GCP Project ID unlinked from your Billing Account or not.  Do you know the answer by any chance?

Please let me know if there is any further info needed on this. Thank you!

**Comment by vugardzhamalov** [comment]
I suspect that this is actually by design and not a bug at all.  I could be wrong but  it seems as if you try to "shut down" GCP Project via Web Console it does the same thing - meaning GCP Project won't be unliked from the billing account. But I can't find any documentation specifically on this issue. Following is taken from [here](https://support.google.com/googleapi/answer/6251787?hl=en#zippy=%2Cshut-down-a-project). I'd say it is somewhat useful but IMO still doesn't provide any specific info:

> Note that after the 30-day waiting period ends, the time it takes to completely delete a project may vary. For example, if a project has billing set up, it might not be completely deleted until the current billing cycle ends,  you receive the next bill, and your account is successfully charged.

**Comment by edwardmedia** [comment]
@vugardzhamalov how did you tell `unlinked` in your observation? I was checking the Console as I mentioned [here](https://github.com/hashicorp/terraform-provider-google/issues/13659#issuecomment-1421269176). How did you do? 

```
GCP Project ID will NOT be unlinked from my billing account
```

**Comment by vugardzhamalov** [comment]
@edwardmedia to my knowledge 'gcloud' doesn't provide any options to list GCP Projects linked to the billing account. Web Console is the only way I know of, as per instructions [here](https://cloud.google.com/billing/docs/how-to/view-linked):
1. Navigate to billing section, [here](https://console.cloud.google.com/billing)
2. Depending on your configuration, you should see at least one billing account there. Now go into billing account that you've linked your GCP project to (see 'billing_account' attribute)
3. On the left hand side panel you'll see option called 'Account management'. Now you should be able to see the list of GCP Projects linked to specific billing account.

I hope this helps, please let me know if there is any further info needed. Thank you!

**Comment by edwardmedia** [comment]
@vugardzhamalov in my [test](https://github.com/hashicorp/terraform-provider-google/issues/13659#issuecomment-1421269176), I see my test project was removed from `Projects linked to this billing account`. I don't know what makes the difference. In my case, the project was freshly created. Maybe in your case, you have other resources provisioned in the project which leads to a waiting time? Do you want to checkout it out after certain days as you [suspected](https://github.com/hashicorp/terraform-provider-google/issues/13659#issuecomment-1422600305)? Clearly this is the API's behavior.

**Comment by vugardzhamalov** [comment]
@edwardmedia I've created a few brand new projects for this issue only (bare projects only, nothing else was enabled). On my end the result is the same, every time I destroy gcp project it does NOT get unlinked from billing account.

It gets "better" though... I've also notices that if I create/destroy via 'terraform apply/destroy' several projects in a row, sometimes after 'terraform destroy' GCP project is still there, despite the fact that 'terraform destroy' reports nothing else left for destruction. 
I don't think I'll have more time to spend on this issue - as I've mentioned I have a work around.
Another factor in play here - I use GCP IAM Service Account that I am impersonating with Terraform (see "google_service_account_access_token" data block for more info [here](https://cloud.google.com/blog/topics/developers-practitioners/using-google-cloud-service-account-impersonation-your-terraform-code)). Who knows maybe it is somehow affecting it. This one probably could be closed for now - I don't think we'll get very far with this any time soon. Thank you for taking a look!

**Comment by edwardmedia** [comment]
@vugardzhamalov  Closing this now as you suggested.
