### ISSUE TITLE
`.` Not Allowed In `google_cloud_run_v2_service` volume path

### ISSUE THREAD

**Issue by enchorb** [hashicorp/terraform-provider-google#13662]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_cloud_run_v2_service

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

```
Error: Error updating Service "projects/project_name/locations/us-central1/services/server": googleapi: Error 400: Violation in UpdateServiceRequest.service.template.volumes[0].secret.items[0].path: may only have up to 255 alphanumeric characters, hyphens, and underscores.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "may only have up to 255 alphanumeric characters, hyphens, and underscores.",
│         "field": "Violation in UpdateServiceRequest.service.template.volumes[0].secret.items[0].path"
│       }
│     ]
│   }
│ ]
│ 
│   with module.server.google_cloud_run_v2_service.server,
│   on ../modules/gcp/server/main.tf line 41, in resource "google_cloud_run_v2_service" "server":
│   41: resource "google_cloud_run_v2_service" "server" {
```

### Expected Behavior

Secret path with `.` ie. `env.json` should be allowed, same as in `google_cloud_run_service`

### Actual Behavior

Fails with error shown in debug output

### Steps to Reproduce

Add a secret volume with a `.` in the path

```
volumes {
      name = "env"
      secret {
        secret       = "env"
        default_mode = 0444
        items {
          path    = "env.json"
          version = "latest"
          mode    = 0400
        }
      }
    }
```

1. `terraform apply`

### References

* b/272363146

**Comment by edwardmedia** [comment]
@enchorb can you share your config by removing the variables?

**Comment by enchorb** [comment]
Updated

**Comment by edwardmedia** [comment]
@enchorb note the error comes from the api. Below is where the field is explained in the api. There is not much the provider can do. Can you try yours by other tools, like gcloud?  

```
googleapi: Error 400: Violation
```

https://cloud.google.com/run/docs/reference/rest/v2/Volume#VersionToPath

**Comment by trshafer** [comment]
This has been fixed in the api

**Comment by yanweiguo** [comment]
@melinath could this be closed?

**Comment by melinath** [comment]
Closing, thanks!
