### ISSUE TITLE
ip_range parameter under "google_apigee_instance" resource is not working. 

### ISSUE THREAD

**Issue by imohitsuri** [hashicorp/terraform-provider-google#13660]
ip_range parameter under "google_apigee_instance" resource is not working. 

Error: Unsupported argument
│
│   on Test.tf line 115, in resource "google_apigee_instance" "apigee_instance":
│  115:   ip_range = "a.b.c.d/22"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.7
on windows_386
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v4.51.0

### Affected Resource(s)
google_apigee_instance

### Terraform Configuration Files
resource "google_apigee_instance" "apigee_instance" {
  name     = "tf-test%{random_suffix}"
  location = "us-central1"
  org_id   = google_apigee_organization.apigee_org.id
  ip_range = "a.b.c.d/22"
}

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

Error: Unsupported argument
│
│   on Test.tf line 115, in resource "google_apigee_instance" "apigee_instance":
│  115:   ip_range = "10.87.8.0/22"
│
│ An argument named "ip_range" is not expected here.

### Expected Behavior
google_apigee_instance should recognize ip_range and use the same while building apigee x instance.

### Actual Behavior
google_apigee_instance doesn't reconize the ip_range parameter, hence terraform validate fails.

### Steps to Reproduce

1. `terraform apply`
terraform validate

### Important Factoids

No.
### References

* #0000

**Comment by edwardmedia** [comment]
@imohitsuri interesting. It was implemented by https://github.com/hashicorp/terraform-provider-google/pull/10928 over a year. What version of the provider are you using?

**Comment by imohitsuri** [comment]
> @imohitsuri interesting. It was implemented by #10928 over a year. What version of the provider are you using?

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "~>2.0"
    }
  }
}
I even tried with "~>3.0" , still not working from Visual Studio.

I tried from GCP cloud shell, only then its working.

**Comment by edwardmedia** [comment]
@imohitsuri you listed the provider versions below.  Are you using the GA one (google v3.90.1) for your config? Can you try the latest one?

```
provider registry.terraform.io/hashicorp/google v3.90.1
provider registry.terraform.io/hashicorp/google-beta v4.51.0
```

**Comment by imohitsuri** [comment]
> @imohitsuri you listed the provider versions below. Are you using the GA one (google v3.90.1) for your config? Can you try the latest one?
> 
> ```
> provider registry.terraform.io/hashicorp/google v3.90.1
> provider registry.terraform.io/hashicorp/google-beta v4.51.0
> ```

Hi @edwardmedia ,

I tried with following provider in Visual Studio code and now its working fine:
terraform {
  required_providers {
    google = {
      source = "hashicorp/google-beta"
      version = "4.51.0"
    }
  }
}

Thanks,
Mohit

**Comment by edwardmedia** [comment]
@imohitsuri cool now we can close this issue then. Thank you
