### ISSUE TITLE
Drift with GCE instance (and probably anything that uses GCE instance types)

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#13672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.3.7
provider 4.51.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "default" {
  project                   = "my-project-id"
  name                      = "test"
  machine_type              = "n2d-custom-8-8192"
  zone                      = "us-central1-a"
  allow_stopping_for_update = true
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
    }
  }
  network_interface {
    subnetwork = "projects/my-project-id/regions/us-central1/subnetworks/my-subnet-name"
  }
}
```

### Debug Output
config drift, and the instance will be stopped and updated on every apply
resource "google_compute_instance" "default" {
      ~ machine_type              = "n2d-highcpu-8" -> "n2d-custom-8-8192"
}

To obtain the debug output, run `terraform apply` with the environment variable `TF_LOG=DEBUG`. See the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html) for more information.
--->

### Expected Behavior

Should not drift 

### Actual Behavior

config drift results in the instance being stopped, updated, and powered on again for every apply
This is most likely an upstream API issue but I can find no open issue tracker for this bug

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

The work around is to use the "standard" machine type name, but this gets VERY complicated when you are computing RAM and CPU on the fly inside of Terraform.

b/308756043

**Comment by rileykarson** [comment]
Ah, yeah, the API's normalizing based on internal business logic that we're not able to replicate inside the provider. A viable clientside solution would be to ignore differences on *any* standard machine type returned by the API going to a custom machine type, but that would ignore them even when they don't match.

If you file an issue against the API through the [Public Issue Tracker](https://cloud.google.com/support/docs/issue-trackers) or through Support and are able to share details about the issue w/ our team (https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) we can provide addtl context to the product team for the service about how this kind of behaviour is harmful to Terraform users.

**Comment by edwardmedia** [comment]
b/268221070

**Comment by philip-harvey** [comment]
> b/268221070

Hi @edwardmedia  I assume that from the internal bug tracker link that there is already an internal bug for this and hence not much point in me creating a bug tracker for this?  Thanks for posting the update.

**Comment by edwardmedia** [comment]
@philip-harvey yes. the issue is at the upstream (api) and I have filed the bug against them

**Comment by karolgorc** [comment]
Hi, copying the business logic 1:1 doesn't seem like a good solution, because honestly speaking this logic will be outdated once any changes are made on the API's side of things and cause more issues than solve them. 

But to somehow resolve this issue maybe we should add logic that throws a warning if a `machine_type` is recognized as custom? And then propose the `lifecycle.ignore_changes` to the user.

This still leaves automated solutions at risk, like a CI/CD pipeline using terraform. So i think some doc changes reflecting the current state of support on custom machine types would be ideal.

@rileykarson toughts?

**Comment by rileykarson** [comment]
> But to somehow resolve this issue maybe we should add logic that throws a warning if a machine_type is recognized as custom? And then propose the lifecycle.ignore_changes to the user.

Terraform doesn't let us return warnings (or really any prompt) based on properties of a resource! The only options are to succeed or return an error with a message.

> This still leaves automated solutions at risk, like a CI/CD pipeline using terraform. So i think some doc changes reflecting the current state of support on custom machine types would be ideal.

+1, just calling out in docs is low weight and addresses this enough.

**Comment by karolgorc** [comment]
Found a workaround for this issue on accident.

The `n2d` in front of the custom machine type causes the API translation to happen
```
# This will cause diff
machine_type = "n2d-custom-8-8192"

#This won't
machine_type = "custom-8-8192"
```

If you need to have a specific CPU platform dictated by the `n2d` part of your statement you can use `min_cpu_platform` instead

This is already in our docs
>[Custom machine types](https://cloud.google.com/dataproc/docs/concepts/compute/custom-machine-types) can be formatted as custom-NUMBER_OF_CPUS-AMOUNT_OF_MEMORY_MB
