### ISSUE TITLE
Consider editing LICENSE file in mmv1/third_party/terraform/ to match the LICENSE files in the downstream repos

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13681]
# Background

Recently the LICENSE file in the downstream TPG and TPGB repos was updated to include a copyright date ([see here](https://github.com/hashicorp/terraform-provider-google/pull/12777))

A lot of files in the root of the downstream repos are copied from the mmv1/third_party/terraform folder, for instance the [.goreleaser.yml.erb](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/.goreleaser.yml.erb) file is controlled from there.

Despite the above, it seems like [this LICENSE file in the magic-modules repo](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/LICENSE) doesn't affect the LICENSE in the downstream repos. I think it should be removed, but it's unclear what the history/intended use of that file is.

Proposed action : ~~delete mmv1/third_party/terraform/LICENSE file~~ update mmv1/third_party/terraform/LICENSE to match https://github.com/hashicorp/terraform-provider-google/blob/main/LICENSE

# What kind of contribution is this issue about?

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google/pull/12777
* https://github.com/hashicorp/terraform-provider-google-beta/pull/4782

# Details

See background

**Comment by SarahFrench** [comment]
I made this as an issue instead of as a PR because I figured some discussion might be required

**Comment by rileykarson** [comment]
This was added intentionally in https://github.com/GoogleCloudPlatform/magic-modules/pull/892 to demarcate that this directory is licensed differently than the rest of the repo. We likely want to keep it- we may want to update it to the current license text.

**Comment by SarahFrench** [comment]
👆 changed title for clarity, after discussion in the team sync
