### ISSUE TITLE
Add  FQDN based, Geo-location based, and Threat Intelligence rules to firewall_policy_rule

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#13688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

FQDN based rule, Thread Intelligence rule, and Geo-location rule are available as new Firewall Policy features announced at Google Cloud Next'22. I would like to be able to use these in Terraform as well.

### New or Affected Resource(s)

* google_compute_firewall_policy_rule
* google_compute_network_firewall_policy_rule
* google_compute_region_network_firewall_policy_rule

### Potential Terraform Configuration

```tf
resource "google_compute_network_firewall_policy" "basic_network_firewall_policy" {
  name        = "policy"
  description = "Sample global network firewall policy"
  project     = "my-project-name"
}

resource "google_compute_network_firewall_policy_rule" "egress" {
  action                  = "allow"
  description             = "This is a simple rule description"
  direction               = "EGRESS"
  disabled                = false
  enable_logging          = true
  firewall_policy         = google_compute_network_firewall_policy.basic_network_firewall_policy.name
  priority                = 1000
  rule_name               = "test-rule-egress"
  target_service_accounts = ["emailAddress:my@service-account.com"]

  match {
    dest_fqdns = ["www.google.com"]
  }
}

resource "google_compute_network_firewall_policy_rule" "primary" {
  action                  = "allow"
  description             = "This is a simple rule description"
  direction               = "INGRESS"
  disabled                = false
  enable_logging          = true
  firewall_policy         = google_compute_network_firewall_policy.basic_network_firewall_policy.name
  priority                = 1000
  rule_name               = "test-rule"
  target_service_accounts = ["emailAddress:my@service-account.com"]

  match {
    src_region_codes = ["US"]
  }
}

resource "google_compute_network_firewall_policy_rule" "deny" {
  action                  = "deny"
  description             = "This is a simple rule description"
  direction               = "INGRESS"
  disabled                = false
  enable_logging          = true
  firewall_policy         = google_compute_network_firewall_policy.basic_network_firewall_policy.name
  priority                = 999
  rule_name               = "test-rule2"
  target_service_accounts = ["emailAddress:my@service-account.com"]

  match {
    src_threat_intelligences = ["iplist-tor-exit-nodes", "iplist-known-malicious-ips"]
  }
}
```

### References

* https://cloud.google.com/blog/products/identity-security/announcing-new-google-cloud-firewall-capabilities/
* https://cloud.google.com/vpc/docs/using-firewall-policies#create-rules
* https://cloud.google.com/vpc/docs/use-network-firewall-policies#create-rules
* https://cloud.google.com/compute/docs/reference/rest/beta/networkFirewallPolicies

**Comment by melinath** [comment]
+1 seems to be supported now.
