### ISSUE TITLE
Ability to add default labels across all supporting resources

### ISSUE THREAD

**Issue by DesmondH0** [hashicorp/terraform-provider-google#13690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
It would be wonderful if GCP provider could have `default_labels` like the [default_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags) functionality from AWS provider

And applying labels to all supported resources
Currently we need to define labeling for all resources, and this enhancement would help to DRY the Terraform code.

### New or Affected Resource(s)

From provider settings

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

provider "google" {
  project     = "my-project-id"
  region      = "us-central1"
  default_labels = {
    label_key = "value"
  }
}
```

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/7325
