### ISSUE TITLE
Lack of context in `google_bigquery_table` error message related to `deletion_protection`

### ISSUE THREAD

**Issue by pndurette** [hashicorp/terraform-provider-google#13694]
### Background

When `deletion_protection` is `true` in `google_bigquery_table` and an apply deletes it, the error message should mention which table is affected:
```
Error: cannot destroy instance without setting deletion_protection=false and running `terraform apply`
```
Which makes it very difficult to pinpoint which table is impacted

i.e. here:
https://github.com/hashicorp/terraform-provider-google/blob/a688e85e4b76b23747046b5c70a7342a02a3c6a3/google/resource_bigquery_table.go#L1313

However our plans can get very big, which sometimes forces us to download the logs and try to grep what went wrong, when the provider could simply provide us the name.

### Suggestion

Add at least the `table` name to the error.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* `google_bigquery_table`

### Potential Terraform Configuration

N/A

### References

N/A

b/299600706

**Comment by wj-chen** [comment]
Fixed as part of https://github.com/GoogleCloudPlatform/magic-modules/pull/10455. @melinath Can you close this issue?

**Comment by melinath** [comment]
yep, thanks!
