### ISSUE TITLE
TF state isn't maintained for GKE clusters with enable_autopilot = true

### ISSUE THREAD

**Issue by mahvar** [hashicorp/terraform-provider-google#13698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

+ provider registry.terraform.io/hashicorp/google v3.63.0
+ provider registry.terraform.io/hashicorp/google-beta v4.52.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke_clusters" {
  provider = google-beta
  for_each = { for key, value in local.regions_list : key => value if value != null }
  project  = var.project_id
  name     = "${var.name}-${each.value.name}"
  location = each.value.name
  network    = google_compute_network.the_network.name
  subnetwork = google_compute_subnetwork.sub_networks[each.key].name
  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }
  private_cluster_config {
    enable_private_endpoint = true
    enable_private_nodes    = false
    master_ipv4_cidr_block  = each.value.gke_cidr_ranges.master
  }
  enable_autopilot = true
  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.gke_node.email
      oauth_scopes = [
        "https://www.googleapis.com/auth/service.management.readonly",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/trace.append",
      ]
    }
  }
  vertical_pod_autoscaling { enabled = true }
  release_channel { channel = "STABLE" }
}
```

### Debug Output

Will provide as a follow on comment

### Panic Output

N/A

### Expected Behavior

Repeated applications of the config to NOT tear down and recreate the clusters!

### Actual Behavior

Every time the unchanged cluster configs are applied, clusters are deleted and recreated! 

### Steps to Reproduce

1. Use my tf snippet above with "google_container_cluster"

2. `terraform apply`

3. Go ahead and recreate the cluster(s)
4. Without any change to the tf files `terraform apply`

### Important Factoids

N/A

### References

I was hoping to find some answers via this closed issue https://github.com/hashicorp/terraform-provider-google/issues/12064. But it seems to have been closed without a proper resolution?

* #0000

**Comment by edwardmedia** [comment]
@mahvar I do not understand what the problem you are facing. In your steps above, what do you mean `Go ahead and recreate the cluster(s)` and `Without any change to the tf files terraform apply`? 

I do see issues reported about Auto Pilot. Please keep in mind, there are features are pre-configured in the Auto Pilot. Below are its comparison with the standard GKE.   

https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison

**Comment by mahvar** [comment]
I meant despite the fact that I don't make any changes in the TF configs, every time I run `terraform apply`, it destroys the GKE clusters and recreates them, which means "TF state isn't maintained for GKE clusters with enable_autopilot = true"

**Comment by edwardmedia** [comment]
@mahvar can you share the plan (terraform plan) that indicates recreation is needed?

**Comment by mahvar** [comment]
https://gist.github.com/mahvar/e93b41b899d373c7df47bdd7b373aff1

**Comment by edwardmedia** [comment]
@mahvar thanks for sharing the plan. It looks like  `google_container_cluster` is going to be created (not recreated) while `google_sql_database_instance` is being recreated. Am I right? I am looking for the plan that shows the GKE is going to be recreated. 

```
it destroys the GKE clusters and recreates them
```

**Comment by mahvar** [comment]
Sorry about the delay! You're right! In all the haste, I had given you a wrong plan [facepalm] Here it is: https://gist.github.com/mahvar/65c8fbe03b75b5d4485b9fd63ff18c0c

**Comment by edwardmedia** [comment]
@mahvar i noticed below changes in the plan which triggers recreation. What are they originally? I see both `enable_` are different from what show [here](https://github.com/hashicorp/terraform-provider-google/issues/assigned/edwardmedia#issue-1578854608) Not sure what happens?

```
          - enable_private_endpoint = false -> null
          - enable_private_nodes    = false -> null
          + master_ipv4_cidr_block  = "172.16.200.16/28" # forces replacement
```
Using below config, I tested and it seems to be fine. I do not see permadiff and recreation. Can you try?

```tf
resource "google_container_cluster" "gke_clusters" {
  provider = google-beta
  //for_each = { for key, value in local.regions_list : key => value if value != null }
  //project  = var.project_id
  name     = "issue13698"
  location = "us-east1"
  network    = data.google_compute_network.network.name
  subnetwork = data.google_compute_subnetwork.subnetwork.name
  /*
  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }
  */
  ip_allocation_policy {
    cluster_ipv4_cidr_block  = "/16"
    services_ipv4_cidr_block = "/22"
  }
  private_cluster_config {
    enable_private_endpoint = true
    enable_private_nodes    = true
    master_ipv4_cidr_block  = "10.42.0.0/28"
  }
   master_authorized_networks_config {}
  enable_autopilot = true
  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = "issue13871@sunedward-tf-host.iam.gserviceaccount.com"
      oauth_scopes = [
        "https://www.googleapis.com/auth/service.management.readonly",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/trace.append",
      ]
    }
  }
  vertical_pod_autoscaling { enabled = true }
  release_channel { channel = "STABLE" }
}

data "google_compute_network" "network" {
  name = "issue12879"
}

data "google_compute_subnetwork" "subnetwork" {
  name   = "issue12879"
  region = "us-east1"
}
```

**Comment by edwardmedia** [comment]
@mahvar is this still an issue?

**Comment by edwardmedia** [comment]
@mahvar closing this assuming it is no longer an issue
