### ISSUE TITLE
Drift in google_bigquery_dataset max_time_travel_hours 

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#13693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.7

### Affected Resource(s)

google_bigquery_dataset 

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "logs" {
  dataset_id = "logs"
  location   = var.region
}
```

### Debug Output

resource "google_bigquery_dataset" "logs" {
        id                              = "projects/projectname/datasets/logs"
      - max_time_travel_hours           = "168" -> null
}

### Expected Behavior

Should not be any drift

### Actual Behavior

Config drift on every apply

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
Closing as a dup of https://github.com/hashicorp/terraform-provider-google/issues/13689
