### ISSUE TITLE
Failing test(s): TestAccSqlDatabaseInstance_settings_secondary

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13708]
### Failure rates

- 100% since 2023-01-17

### Impacted tests:

- TestAccSqlDatabaseInstance_settings_secondary

### Affected Resource(s)

* google_sql_database_instance

### Nightly builds

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/374114?buildTab=tests&expandedTest=-6659158429213003779

### Message(s)

```
provider_test.go:312: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# google_sql_database_instance.instance will be updated in-place
~ resource "google_sql_database_instance" "instance" {
id                             = "tf-test-hib2t68dqe"
name                           = "tf-test-hib2t68dqe"
# (14 unchanged attributes hidden)
~ settings {
# (12 unchanged attributes hidden)
~ location_preference {
+ secondary_zone = "us-central1-a"
# (1 unchanged attribute hidden)
}
# (2 unchanged blocks hidden)
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by roaks3** [comment]
I ran this locally and saw that the `secondary_zone` was not being returned by the API. This appears intentional, and I think we can simply change the test to use `availability_type = "REGIONAL"`, but I've followed up with the API team to make sure this isn't some sort of regression that we haven't noticed: b/269341322.
