### ISSUE TITLE
Failing test(s): Firebase Provision requests per minute and apps per project quota

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13719]
### Failure rates

- 100% since 2023-02-03

### Impacted tests:

- TestAccDataSourceGoogleFirebaseAndroidApp
- TestAccDataSourceGoogleFirebaseAppleApp
- TestAccDataSourceGoogleFirebaseAppleAppConfig
- TestAccFirebaseAndroidApp_firebaseAndroidAppBasicExample
- TestAccFirebaseAndroidApp_update
- TestAccFirebaseAppleApp_firebaseAppleAppBasicExample
- TestAccFirebaseAppleApp_firebaseAppleAppFullExample
- TestAccFirebaseHostingSite_firebasehostingSiteFullExample
- TestAccFirebaseHostingSite_firebasehostingSiteUpdate
- TestAccFirebaseWebApp_firebaseWebAppSkipDelete

### Affected Resource(s)

* google_firebase_android_app
* google_firebase_apple_app

### Nightly builds

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/374144?buildTab=tests&pager.currentPage=1&name=TestAccDataSourceGoogleFirebaseAndroidApp&expandedTest=95368672504330208

### Message(s)
```
Error: Error creating AndroidApp: googleapi: Error 429: Quota exceeded for quota metric 'Provision requests' and limit 'Provision requests per minute' of service 'firebase.googleapis.com' for consumer 'project_number:XXXX'
```

possibly also another separate quota issue:

```
Error: Error creating AppleApp: googleapi: Error 429: Too many Apps on project:XXXX
```

**Comment by roaks3** [comment]
Looks like these were all fixed. Instance was cleaned up, sweepers were fixed, and resource were prefixed appropriately to prevent more of these.
