### ISSUE TITLE
Failing test(s): TestAccFirebaseAppleApp_update

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13720]
### Failure rates

- 96% in 2023-01

### Impacted tests:

- TestAccFirebaseAppleApp_update

### Affected Resource(s)

* google_firebase_apple_app

### Nightly builds

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/374144?buildTab=tests&pager.currentPage=1&name=TestAccFirebaseAppleApp_update&expandedTest=-7026834308340857772

### Message(s)

```
Error: Error creating AppleApp: googleapi: Error 409: Requested entity already exists
```

**Comment by trodge** [comment]
This seems like an API bug, because the unique `app_id` is meant to be server-generated. Filed b/269488963.

**Comment by roaks3** [comment]
Looks like this was fixed on Feb 14, 2023, possibly due to https://github.com/GoogleCloudPlatform/magic-modules/pull/7277.
