### ISSUE TITLE
Failing test(s): TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13721]
### Failure rates

- 100% since 2023-01-31

### Impacted tests:

- TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample

### Affected Resource(s)

* google_healthcare_dicom_store

### Nightly builds

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/374144?buildTab=tests&pager.currentPage=1&name=TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample&expandedTest=-2576387264761293991

### Message(s)

```
Error: Error creating DicomStore: googleapi: Error 403: failed to verify dataset (projectID:ci-test-project-188019, datasetID:tf_test_dicom_bq_dstn9ov9ocb3), please add the required bigquery.dataEditor role to your project's service account
```

**Comment by trodge** [comment]
Added `roles/bigquery.dataEditor` to `hashicorp-test-runner@ci-test-project-188019.iam.gserviceaccount.com`.

**Comment by trodge** [comment]
Test appears to still be failing. Ran the following:
```
gcloud projects add-iam-policy-binding ci-test-project-188019 \
    --member=serviceAccount:service-1067888929963@gcp-sa-healthcare.iam.gserviceaccount.com \
    --role=roles/bigquery.dataEditor
```
Also filed b/269773393 .

**Comment by trodge** [comment]
It looks like we have some iam members that are removing that permission when they complete. I think we should convert them to a bootstrap function.
