### ISSUE TITLE
Missing parquet options from BigQuery Terraform provider

### ISSUE THREAD

**Issue by kkulczak** [hashicorp/terraform-provider-google#13727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Customer is loading into BQ a Parquet data containing nested lists.
Customer uses `--parquet_enable_list_inference` flag when creating external parquet tables with bq command line tool to properly parse input data.
[docs link](https://cloud.google.com/bigquery/docs/reference/bq-cli-reference#parquet_enable_list_inference_flag
)
They want to describe their infrastructure with Terraform BigQuery provider.
Unfortunately the provider do not support any parquet_options

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#parquetoptions

### New or Affected Resource(s)

* google_bigquery_table

### References

* b/268201164

**Comment by rileykarson** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7873
