### ISSUE TITLE
Permadiff in google_access_context_manager_service_perimeter when in dry run 

### ISSUE THREAD

**Issue by eitah** [hashicorp/terraform-provider-google#13723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

+ provider registry.terraform.io/hashicorp/google v4.52.0
+ provider registry.terraform.io/hashicorp/google-beta v4.52.0

### Affected Resource(s)

google_access_context_manager_service_perimeter

### Terraform Configuration Files

I omitted the locals used. The only difference from the example dry run provided in the terraform docs is that we do not want an enforced VPC perimeter here.

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
    google-beta = {
      source = "hashicorp/google-beta"
    }
  }
}

resource "google_access_context_manager_service_perimeter" "service-perimeter" {
  parent = "accessPolicies/${local.policy}"
  name   = "accessPolicies/${local.policy}/servicePerimeters/restrict_bigquery_dryrun_storage"
  title  = "restrict_bigquery_dryrun_storage"

  # We provide an empty RESTRICTED_SERVICES list since we do not want a perimeter at all.
  status {
    restricted_services = []
  }

  # Service 'storage.googleapis.com' will be in dry-run mode.
  spec {
    restricted_services = ["storage.googleapis.com"]
    resources = ["projects/${local.project_number}"]
  }

  use_explicit_dry_run_spec = true

}
```

### Debug Output

https://gist.github.com/eitah/8ee909fbcb4053781e9a2fc86ec0944d

### Expected Behavior

I would expect the plan to show no difference as nothing has changed. 

### Actual Behavior

The plan shows a perpetual diff where the RESTRICTED_SERVICES block (that was empty) has been removed. Omitting the RESTRICTED_SERVICES input array altogether returns an error.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
@eitah thanks for your log but that is not long enough. Are you able to share the portions that contain the api requests and responses that created  `google_access_context_manager_service_perimeter`?

**Comment by eitah** [comment]
Sure! @edwardmedia I've updated the gist ^ with the full trace, not just INFO, although I don't obiously see requests and responses. 

Is the above enough for you? This is a VPC Service perimiter that has already been created.

**Comment by edwardmedia** [comment]
@eitah yeah, I don't see the requests and responses. I can't repro it locally but I am happy to take a look if you can provide the debug log. My guess the API behaves a little bit different from what we expect on this field, but need the evidences.

**Comment by eitah** [comment]
Hi Edward, thanks for getting back to me! I updated the logs again to include the DEBUG state not just the info state as (I think) I had before. I also included perimiter creation in case that is helpful to you.

Perimiter creation: https://gist.github.com/eitah/8ee909fbcb4053781e9a2fc86ec0944d#file-initial-apply-service-perimiter-txt
Perimiter permadiff: https://gist.github.com/eitah/8ee909fbcb4053781e9a2fc86ec0944d#file-second-plan-serivce-perimiter-txt

**Comment by edwardmedia** [comment]
@eitah the problem is on the status field. Since you do not want a perimeter at all, have you try to remove the status block entirely? 

```
  # We provide an empty RESTRICTED_SERVICES list since we do not want a perimeter at all.
  status {
    restricted_services = []
  }
```

**Comment by eitah** [comment]
Ah but that's exactly the issue @edwardmedia 

```
╷
│ Error: Missing required argument
│
│   with google_access_context_manager_service_perimeter.service-perimeter,
│   on all.tf line 25, in resource "google_access_context_manager_service_perimeter" "service-perimeter":
│   25:   spec {
│
│ "spec.0.access_levels": one of
│ `spec.0.access_levels,status.0.access_levels,status.0.resources,status.0.restricted_services`
│ must be specified
╵
```

**Comment by eitah** [comment]
Ah! Rereading the error message here is obvious, when I add 

```
    access_levels = []
```
the error goes away

**Comment by eitah** [comment]
I think where I get lost in the documentation is this block in the docs from google_access_context_manager_service_perimeter. 

```
 (Optional) A list of AccessLevel resource names that allow resources within the ServicePerimeter to be accessed from the internet.... If no AccessLevel names are listed, resources within the perimeter can only be accessed via GCP calls with request origins within the perimeter...
```

So if i pass access_levels = [] will that break my service perimiters? in dry run nothing should be enforced, so I don't think so.

**Comment by edwardmedia** [comment]
@eitah I am not able to run the script thusI am not sure. I can take a look if I have the debug log. You should be able to review the api response from you dry run to seek the answer. Or run `terraform show`/

```
will that break my service perimeters? 
```

Based on [this](https://github.com/hashicorp/terraform-provider-google/issues/13723#issuecomment-1465211610), looks like you have found the solution to avoid the error.  Mind closing the issue if this is the case?

**Comment by eitah** [comment]
Thanks! issue resolved!
