### ISSUE TITLE
creating cloud_identity_group fails due to "already exists", when it doesn't, succeeds on subsequent runs.

### ISSUE THREAD

**Issue by lexual-anz** [hashicorp/terraform-provider-google#13733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform 1.3
provider: 4.50.0

### Affected Resource(s)

* google_cloud_identity_group

### Terraform Configuration Files

```tf
resource "google_cloud_identity_group" "cloud_identity_group_basic" {
  display_name         = "my-identity-group"
  initial_group_config = "WITH_INITIAL_OWNER"

  parent = "customers/ABC123"

  group_key {
      id = "my-identity-group@example.com"
  }

  labels = {
    "cloudidentity.googleapis.com/groups.discussion_forum" = ""
  }
}
```

### Debug Output

```
....group: Creating...
 
  Error: Error creating Group: googleapi: Error 409: Error(2018): Cannot create group 'my-identity-group@example.com' because it already exists.
  Details:
  [
    {
      "@type": "type.googleapis.com/google.rpc.ResourceInfo",
      "description": "Error(2018): Cannot create group 'my-identity-group@example.com' because it already exists.",
      "owner": "domain:cloudidentity.googleapis.com",
      "resourceType": "cloudidentity.googleapis.com/Group"
    }
  ]
  

```

### Expected Behavior

create groups successfully without error

### Actual Behavior

Not 100%, but routinely seeing it error when creating groups.
Either a 2nd or 3rd, terraform plan/apply cycle, seems to have it work.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@lexual-anz interesting. It says "already exists" during the first run? Can you share your debug log?

**Comment by lexual-anz** [comment]
Hi, I'll see if I can ramp up the logging level, and reproduce, and share here ;)

**Comment by edwardmedia** [comment]
@lexual-anz Yes, waiting for log and repro steps.

I am curious why it says "already exists" for the first run.

**Comment by lexual-anz** [comment]
we've seen it happen a couple of times in a row, and maybe not until the 4th run, it works.
Will get some logs in next few hours if I can, apologies, I missed your initial response ;(

**Comment by lexual-anz** [comment]
plan, and TF_LOG=debug apply outputs can be seen here:

https://gist.github.com/lexual-anz/dff90d0b78f73e0002e45e598369da66

Note, running plan/apply for the exact same codebase a few minutes later, succeeded (can provide logs of this if useful too).

**Comment by lexual-anz** [comment]
potentially relevant (?)
https://github.com/googleapis/google-api-go-client/issues/556

**Comment by edwardmedia** [comment]
@lexual-anz I do see the error on the below api call. It seems the `groupKey` is already created and not available. You might want to try if you can [import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_identity_group#import) it and see if that works.  I am not sure how the key was created. Can you manually delete it and try apply again? Or test by a different group key? 

```
POST /v1/groups?alt=json&initialGroupConfig=WITH_INITIAL_OWNER HTTP/1.1
Host: cloudidentity.googleapis.com
User-Agent: Terraform/1.3.9 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.50.0
Content-Length: 248
Content-Type: application/json
Accept-Encoding: gzip

{
 "description": "testing purposes only",
 "displayName": "test-group-05_np",
 "groupKey": {
  "id": "test-group-05_np@example.com"
 },
 "labels": {
  "cloudidentity.googleapis.com/groups.discussion_forum": ""
 },
 "parent": "customers/ABCD1234"
}
```

**Comment by lexual-anz** [comment]
Hi @edwardmedia the key definitely didn't exist before the terraform plan/apply. And as I said, subsequent terraform plan/apply results in a successful run of the terraform plan, and creation of the group.

**Comment by lexual-anz** [comment]
New gist: https://gist.github.com/lexual-anz/e2833f1dfef81dd5e864cde6e1b8d0d5

This is the request/response from TF_LOG
The initial failure, and a subsequent run that succeeded.
There was no manual intervention by me in between these two runs.
You can see the requests are identical, but the responses are very different.

**Comment by edwardmedia** [comment]
@slevenick what do you think of this issue?

**Comment by slevenick** [comment]
This looks like an API error, there's not much we can do from a client side if the API is responding to the same request in different ways for seemingly no reason.

I'd try filing an issue against the API's issue tracker directly: https://cloud.google.com/support/docs/issue-trackers
