### ISSUE TITLE
Spanner instance not updated properly when changing only the force destroy

### ISSUE THREAD

**Issue by dbrasseur-aneo** [hashicorp/terraform-provider-google#13749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.8

### Affected Resource(s)

Not sure which one, or both of :
* google_spanner_instance 
* google_spanner_database

### Terraform Configuration Files

```tf
provider "google" {
  project = var.project
  region = var.region
}

terraform {
  required_version = "1.3.8"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.53"
    }
  }
}

resource "google_spanner_instance" "supply_chain" {
  name             = "test-db"
  display_name     = "Test DB"
  config           = "regional-${var.region}"
  processing_units = 100
  force_destroy    = var.enable_force_destroy
}

resource "google_spanner_database" "supply_chain" {
  instance                 = google_spanner_instance.supply_chain.name
  name                     = "test"
  deletion_protection      = !var.enable_force_destroy
}

variable "project" {
  type = string
}

variable "region" {
  type = string
}

variable "enable_force_destroy"{
  type = bool
  default = true
}
```

### Debug Output

https://gist.github.com/dbrasseur-aneo/fb557fa1c19e7a604e6a9d23154586f8

### Expected Behavior

Both database and spanner instances shoud have been updated by changing their force_destroy and deletion_protection

### Actual Behavior

Only the database is updated correctly, the instance doesn't update with the error : 
```
| Error: Error updating Instance "prj-resim/test-db": googleapi: Error 400: Invalid UpdateInstance request.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Must specify a non-empty field mask.",
│         "field": "field_mask"
│       }
│     ]
│   }
│ ]
│
│   with google_spanner_instance.supply_chain,
│   on main.tf line 16, in resource "google_spanner_instance" "supply_chain":
│   16: resource "google_spanner_instance" "supply_chain"
```
However, **a second apply with the same values succeeds**

### Steps to Reproduce

With no deployment :
1. `terraform init`
2. `terraform apply -var=project=PROJECT -var=region=REGION -var=enable_force_destroy=true -auto-approve`
3. `terraform apply -var=project=PROJECT -var=region=REGION -var=enable_force_destroy=false -auto-approve`
The deployment should have failed
4. `terraform apply -var=project=PROJECT -var=region=REGION -var=enable_force_destroy=false -auto-approve`
The deployment should have succeeded
5. `terraform apply -var=project=PROJECT -var=region=REGION -var=enable_force_destroy=true -auto-approve`
The deployment should have failed
6. `terraform apply -var=project=PROJECT -var=region=REGION -var=enable_force_destroy=true -auto-approve`
The deployment should have succeeded

### References

Same error but different reason :
* #10046

**Comment by edwardmedia** [comment]
@dbrasseur-aneo do you see the behavior different from what it says below? . Do you notice `Unless this field is set to false in Terraform state`? Have you verified its state? 

```
[deletion_protection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#deletion_protection) - (Optional) Whether or not to allow Terraform to destroy the instance. Unless this field is set to false in Terraform state, a terraform destroy or terraform apply that would delete the instance will fail.
```

**Comment by rileykarson** [comment]
@edwardmedia: The action that's failing is setting the value in state, not the deletion itself. Looking at the plan contents, this should have successfully updated the field in-state w/o sending a request to the API (or a no-op request could have succeeded, although not sending one when we don't need to would be preferred).

```
  # google_spanner_database.supply_chain will be updated in-place
  ~ resource "google_spanner_database" "supply_chain" {
      ~ deletion_protection      = false -> true
        id                       = "test-db/test"
        name                     = "test"
        # (5 unchanged attributes hidden)
```

**Comment by edwardmedia** [comment]
@melinath below issue has been created per your suggestion

https://github.com/hashicorp/terraform-provider-google/issues/13820
