### ISSUE TITLE
Terraform Cloud everytime outputs as planned changes to set Cloud Run Job max_retries from 3 to 0 

### ISSUE THREAD

**Issue by stebranchi** [hashicorp/terraform-provider-google#13747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.7

### Affected Resource(s)

* google_cloud_run_job

### Terraform Configuration Files

```tf
resource "google_cloud_run_v2_job" "cloud_run_job" {

  name         = local.cloud_run_job_name
  location     = "europe-west3"
  launch_stage = "BETA"

  template {
    parallelism = 1
    task_count = 1
    template {
      containers {
        image = var.container_image
        dynamic "env" {
            for_each = var.container_env_vars
            content {
              name = env.key
              value = env.value
            }
        }
        dynamic "env" {
         ...
      }
      max_retries     = 0
      service_account = google_service_account.default.email
      timeout         = "3600s"
    }
  }
```

### Expected Behavior

Terraform Cloud should not detect any changes in the value for max_retries field in job configuration

### Actual Behavior

When run apply on Terraform Cloud everytime it gives as a resource to change the max_retries of each cloud run job from 3 to 0, also if in the job configuration there is 0 as max retries value, both in terraform and google cloud config

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

b/271916488

**Comment by yanweiguo** [comment]
There was an issue where the cloud run API treated 0 `max_retries` as unset. It has been fixed.

@stebranchi could you verify whether this is still an issue?

**Comment by shuyama1** [comment]
@yanweiguo Thanks for fixing the API issue. We'd likely still need to add `send_empty_value` to the field to make it work in Terraform.

**Comment by yanweiguo** [comment]
> @yanweiguo Thanks for fixing the API issue. We'll still likely need to add `send_empty_value` to the field to be able to send `0` value in Terraform after the API fix.

You're right. After `terraform apply`,  `max_retries` was set to 3 even though 0 was specified.

**Comment by fibbers** [comment]
Hi, thanks for working on this.
Some of our Cloud Run Jobs changed configuration: from `max_retries=0` to `max_retries=3` because of this bug.

After changing `max_retries` back to `0` using gcloud, the next run of Terraform will set it again to `3`.

I workarounded the issue by ignoring some changes so Terraform won't set it back to `3` unnecessarily:
```terraform
resource "google_cloud_run_v2_job" "jobs" {
  for_each     = local.cloud_run_jobs
  name         = each.key
  location     = local.region

  lifecycle {
    ignore_changes = [
      # Negeer dit allemaal zodat max_retries=0 geconfigureerd blijft.
      # Met gcloud teruggezet naar 0 van 3, maar Terraform wil het terugzetten naar 3, dus ignore_changes
      # totdat deze bug is gefixed: https://github.com/hashicorp/terraform-provider-google/issues/13747
      client,
      client_version,
      template[0].template[0].max_retries,
    ]
  }
  ...
```

I see work is done 2 weeks ago, including in the related PR, but it seems some if it has paused.
So, I don't want to pressure anyone:) but just a friendly question if there is still progress here. Or if there's anything I can do.

Thanks again for working on this.

**Comment by yanweiguo** [comment]
The fix https://github.com/GoogleCloudPlatform/magic-modules/pull/7425 is blocked since it will also send 0 if users don't specify maxTries. A client side default is needed to fix the side effect but it's a breaking change.
