### ISSUE TITLE
Data catalog Taxonomy resource is not available

### ISSUE THREAD

**Issue by pradeep-krisnarao** [hashicorp/terraform-provider-google#13750]
Hi 
I was wondering whether we can do ALL the data catalog operations from Terraform.  I could not find the google provider for some of the operations.  For example to create a Taxonomy.  It is available through the google-beta provider.  Why is it not supported by the google provider itself?
I am referring to this link:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_policy_tag

**Comment by edwardmedia** [comment]
@pradeep-krisnarao you are right. The resource is currently in beta. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) to ask for GA version
