### ISSUE TITLE
Resource google_compute_ha_vpn_gateway is missing option to create an ipv6/dual stack vpn gateway

### ISSUE THREAD

**Issue by zooper** [hashicorp/terraform-provider-google#13752]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Currently, there is no way of configuring a ha vpn gateway with dual stack support (IPv4 + IPv6) according to the argument reference section at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ha_vpn_gateway, this in turn makes it impossible to create a cloud router for IPv6. (Creation will default to IPv4)
Per https://cloud.google.com/network-connectivity/docs/router/how-to/configuring-ipv6-bgp: 

> To exchange IPv6 traffic between Google Cloud and your on-premises networks, you must enable the IPv4 and IPv6 (dual-stack) stack type in your network connectivity product, such as HA VPN. You then enable IPv6 prefix exchange in the BGP IPv4 session used by the connection.

### New or Affected Resource(s)

* google_compute_ha_vpn_gateway

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent. 
resource "google_compute_ha_vpn_gateway" "vpn-gateway" {
  name           = "test-ha-vpngw"
  network        = google_compute_network.network.id
  ip_family      = dual_stack
  vpn_interfaces {
      id                      = 0
      interconnect_attachment = google_compute_interconnect_attachment.attachment1.self_link
  }
  vpn_interfaces {
      id                      = 1
      interconnect_attachment = google_compute_interconnect_attachment.attachment2.self_link
  }
}

```

### References

* #0000

**Comment by rileykarson** [comment]
Note: the field in the API is `stackType`, so we'd implement this as `stack_type` rather than `ip_family` as suggested

**Comment by 600lyy** [comment]
having a look

**Comment by 600lyy** [comment]
PR merged to main! 

https://github.com/GoogleCloudPlatform/magic-modules/pull/7525

Dual stack support will be included in the upcoming TF Google provider releases.

stack_type = IPV4_ONLY | IPV4_IPV6

**Comment by rileykarson** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/7525
