### ISSUE TITLE
Add support for 'publish to Cloud Monitoring' in google_data_loss_prevention_job_trigger

### ISSUE THREAD

**Issue by nealharris** [hashicorp/terraform-provider-google#13768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_job_trigger does not support configuring a job to publish results to Cloud Monitoring.

### New or Affected Resource(s)

* google_data_loss_prevention_job_trigger

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_job_trigger

**Comment by rileykarson** [comment]
Is there documentation on how to set this up? I found https://cloud.google.com/dlp/docs/monitoring but that doesn't obviously contain anything wrt. configuring it in the first place, just reading it.

**Comment by melinath** [comment]
looks like this is JobTrigger.inspectJob.actions.publishToStackdriver, which is an empty object that acts as a boolean: https://cloud.google.com/dlp/docs/reference/rest/v2/Action#PublishToStackdriver
