### ISSUE TITLE
google_dataplex_lake_tasks support

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#13764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support for Dataplex tasks - https://cloud.google.com/dataplex/docs/reference/rest/v1/projects.locations.lakes.tasks 

### New or Affected Resource(s)

* google_dataplex_lake_tasks

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_dataplex_lake_tasks" "my_dq" {
  
  display_name = "My Awesome Task"
  description = "My description"
  labels = {
    bar = "foo"
  }
  trigger_spec {
    type = "ON_DEMAND"
  }
  execution_spec {
    service_account = "my_sa@project.iam.gserviceaccount.com"
    project = "my-awesome-project"
  }
  ## only one of these
  spark {}
  notebook {}
}
```

### References

* #0000

**Comment by rileykarson** [comment]
Note: This resource seems to represent either a one-time job *or* a recurring trigger.

**Comment by vijaikalyan** [comment]
@drandell - We recently added support for Dataplex Tasks. See [google_dataplex_task](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataplex_task). Could you please try this out and let us know if this meets your needs.

**Comment by melinath** [comment]
It looks like support for this resource was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/8124. If there are any issues with it please open a new ticket - thanks!
