### ISSUE TITLE
Option to snapshot disk before destroy

### ISSUE THREAD

**Issue by tammersaleh** [hashicorp/terraform-provider-google#1376]
### Affected Resource(s)

* google_compute_instance

Much like terraform-providers/terraform-provider-aws#2715, I'd love to see a `termination_snapshot_name` option that takes a final snapshot before destroying a disk.  I imagine this makes most sense as an option under the `boot_disk` and `attached_disk` structures on `google_compute_instance`, but I could also see it being an option on `google_compute_disk`, directly.

This should kick off snapshots any time GCP intends to deprovision the disk, including when the attached instance is decommissioned, and the user hasn't yet learned to set `auto_delete` to `false`.

**Comment by johananl** [comment]
I can take this one, too.

**Comment by mitj04** [comment]
b/263474622

**Comment by rileykarson** [comment]
This is a significant amount of client code for an entirely custom behaviour. I don't think we'd want to make a change of this type- this would make sense in the API layer.
