### ISSUE TITLE
google_secret_manager_secret: change of rotation_period forces replacement

### ISSUE THREAD

**Issue by jktcp** [hashicorp/terraform-provider-google#13770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.53.1
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1
```

### Affected Resource(s)

* google_secret_manager_secret

### Terraform Configuration Files

```tf
provider "google" {
  project = "sayfr-dev"
  region  = "eu-west-3"
}
provider "google-beta" {
  project = "sayfr-dev"
  region  = "eu-west-3"
}
resource "google_pubsub_topic" "topic" {
  name = "test-topic"
}
resource "google_project_service_identity" "secretmanager" {
  provider = google-beta
  service = "secretmanager.googleapis.com"
}
resource "google_pubsub_topic_iam_member" "secrets_manager_access" {
  topic  = google_pubsub_topic.topic.name
  member = "serviceAccount:${google_project_service_identity.secretmanager.email}"
  role   = "roles/pubsub.publisher"
}
resource "google_secret_manager_secret" "secret" {
  secret_id = "test-secret"
  replication {
    automatic = true
  }
  topics {
    name = google_pubsub_topic.topic.id
  }
  rotation {
    rotation_period    = "3600s"
    next_rotation_time = timeadd(timestamp(), "6m")
  }
  depends_on = [
    google_pubsub_topic_iam_member.secrets_manager_access,
  ]
}
```

### Debug Output

https://gist.github.com/jktcp/ff142091b659509f9b276419f3c05c49

Relevant excerpt - notice "forces replacement":
```
-/+ resource "google_secret_manager_secret" "secret" {
      ~ create_time = "2023-02-16T19:52:17.407147Z" -> (known after apply)
      + expire_time = (known after apply)
      ~ id          = "projects/test-project/secrets/test-secret" -> (known after apply)
      - labels      = {} -> null
      ~ name        = "projects/000000000000/secrets/test-secret" -> (known after apply)
      ~ project     = "test-project" -> (known after apply)
        # (1 unchanged attribute hidden)

      ~ rotation {
          ~ next_rotation_time = "2023-02-16T19:58:16Z" -> (known after apply)
          ~ rotation_period    = "3600s" -> "3700s" # forces replacement
        }

        # (2 unchanged blocks hidden)
    }
```

### Expected Behavior

Resource should be updated in-place.

### Actual Behavior

Resource is replaced.

### Steps to Reproduce

1. Run `terraform apply`
2. Change "3600s" to "3700s"
3. Run `terraform apply`

b/299600929

**Comment by shuyama1** [comment]
@jktcp Thanks for filing the issue! Change the label to `enhancement` as supporting in-place update is considered update behavior request

**Comment by jktcp** [comment]
"Bug vs enhancement" saga... The recreation would not be an issue if a secret is unreferenced. It if is used in some other resource, then Terraform tries to create new secret instance before deleting old one and everything fails:
```
│ Error: Error creating Secret: googleapi: Error 409: Secret [projects/000000000000/secrets/test-secret] already exists.
│ 
│   with google_secret_manager_secret.token,
│   on ./main.tf line 21, in resource "google_secret_manager_secret" "secret":
│   52: resource "google_secret_manager_secret" "secret" {
```

**Comment by rileykarson** [comment]
Does `lifecycle.create_before_destroy` solve that issue?

**Comment by jktcp** [comment]
> Does lifecycle.create_before_destroy solve that issue?

No. You cannot create two secrets with the same identifier!

**Comment by alexku7** [comment]
So critical issue without solution yet :(

**Comment by alexku7** [comment]
/reopen pls 

The provider 4.84.0 still hass the same issue.

The secreit is being replaced if rotation_period is changed

**Comment by alexku7** [comment]
Thanks for clarifying:)
