### ISSUE TITLE
Terraform templates enforce limits that Google API does not

### ISSUE THREAD

**Issue by nazir-kabani** [hashicorp/terraform-provider-google#13777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_resource_network_services_edge_cache_service.go 

### Terraform Configuration Files

```tf
"allow_origins": {
	Type:     schema.TypeList,
	Optional: true,
	Description: `Specifies the list of origins that will be allowed to do CORS requests.

l-Allow-Origin response header.`,
	MaxItems: 5,
	Elem: &schema.Schema{
		Type: schema.TypeString,
	},
},
```

### Debug Output

[](https://gist.github.com/nazir-kabani/52cd0673acd640f3de8d98c97caba02a)

### Panic Output

NA

### Expected Behavior

Google Media CDN supports 25 CORS origins - https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#corspolicy

User should be able to create media CDN service with upto 25 CORS origins using Terraform code

### Actual Behavior

TF limit is restricting users to create edge cache service with more than 5 CORS origins
below restriction with https://github.com/hashicorp/terraform-provider-google/blob/a245b0a1f111054c4566e868bb57708de7080752/google/resource_network_services_edge_cache_service.go#L746 module is restricting users.

```
"allow_origins": {
	Type:     schema.TypeList,
	Optional: true,
	Description: `Specifies the list of origins that will be allowed to do CORS requests.

l-Allow-Origin response header.`,
	MaxItems: 5,
	Elem: &schema.Schema{
		Type: schema.TypeString,
	},
},
```

### Steps to Reproduce

Try creating edge cache service with more than 5 CORS origins with Terraform

1. `terraform apply`

### Important Factoids

N/A

### References

NA

**Comment by msampathkumar** [comment]
Raised PR at https://github.com/GoogleCloudPlatform/magic-modules/pull/7331 for the same.
