### ISSUE TITLE
I got an issue running my terraform google-beta

### ISSUE THREAD

**Issue by MikeyHal** [hashicorp/terraform-provider-google#13775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.9
on linux_386
+ provider registry.terraform.io/hashicorp/google v4.0.0
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

* google_XXXXX

│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.peer-security-prod.google_compute_network_peering.local_network_peering,
│   on ../../../../modules/network modules/network-peering/main.tf line 34, in resource "google_compute_network_peering" "local_network_peering":
│   34: resource "google_compute_network_peering" "local_network_peering" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-google-beta_v4.53.1_x5 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "8676932801028733754": value out of range

goroutine 83 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xe275680, {0xdc0df48, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0xe275680)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xde2cd90, {{{0xb11b2a4, 0xdc0d708}}, {0xa72eac0, 0xde4b3e0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xdc0aeb0, {0xb11ae24, 0xe3a8b70}, 0xde4a820)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xdcb8410, {0xb11ae24, 0xe3a88a0}, 0xe3b3ce0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xab0f200, 0xdcb8410}, {0xb11ae24, 0xe3a88a0}, 0xe503fc0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0xdcd9560, {0xb11e254, 0xde885a0}, 0xe316780, 0xe05a048, 0xc4404a8, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0xdcd9560, {0xb11e254, 0xde885a0}, 0xe316780, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-google-beta_v4.53.1_x5 plugin crashed!
### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by shuyama1** [comment]
This may be similar to https://github.com/hashicorp/terraform-plugin-sdk/issues/469.

**Comment by clemenscodes** [comment]
Wild guess that this bug is caused by an integer in the state file that cant be parsed and overflows since you run on 32 bit. Does it work on 64 bit? In my case, simply upgrading to terraform version 1.3.9 solved this issue.

**Comment by MikeyHal** [comment]
Hi Clemens,

Thanks, I will try it.

Regards,
Michael

**Comment by clemenscodes** [comment]
Hey Mikey, 

I just realized that I had used a downloaded binary before and installed terraform from an official package 
manager instead, that made it work. 

Regargs, 
Clemens

**Comment by edwardmedia** [comment]
same issue with https://github.com/hashicorp/terraform-provider-google/issues/6518

**Comment by edwardmedia** [comment]
Close as a dup of https://github.com/hashicorp/terraform-provider-google/issues/6518
