### ISSUE TITLE
The terraform-provider-google_v4.53.1_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by papqin** [hashicorp/terraform-provider-google#13785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.9
on windows_386
+ provider registry.terraform.io/hashicorp/google v4.53.1
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1

### Affected Resource(s)

* google_monitoring_uptime_check_config
* google_pubsub_topic
* google_monitoring_notification_channel
* google_compute_instance_template
* google_compute_region_ssl_certificate
* google_compute_health_check
* google_compute_region_health_check
* google_compute_region_disk
* each terraform plan has different resources giving error

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Panic Output
Stack trace from the terraform-provider-google_v4.53.1_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "2298454105269501722": value out of range

goroutine 118 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x166e9ae0, {0x15e04fd8, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x166e9ae0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x1623eee0, {{{0x3a7e600, 0x15e044f8}}, {0x31073e0, 0x1669a700}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x15c05320, {0x3a7e1a0, 0x161400d8}, 0x1669a3e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x15e9a5a0, {0x3a7e1a0, 0x16059d10}, 0x164908a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x34c2680, 0x15e9a5a0}, {0x3a7e1a0, 0x16059d10}, 0x1672a500, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x15cb2360, {0x3a812e4, 0x15f0ad80}, 0x161a8aa0, 0x15fc5ae8, 0x4c62a08, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x15cb2360, {0x3a812e4, 0x15f0ad80}, 0x161a8aa0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-google_v4.53.1_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior
Should Refresh State.

### Actual Behavior
Giving Below Errors:
╷
│ Error: Plugin did not respond
│
│   with module.controllers.google_compute_region_disk.REDACTED_home_folder_disk,
│   on Modules\REDACTED_controllers\active_controller.tf line 49, in resource "google_compute_region_disk" "REDACTED_home_folder_disk":
│   49: resource "google_compute_region_disk" "REDACTED_home_folder_disk" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.controllers.google_compute_region_health_check.REDACTED_controllers_health_check_lb,
│   on Modules\REDACTED_controllers\active_controller.tf line 355, in resource "google_compute_region_health_check" "REDACTED_controllers_health_check_lb":
│  355: resource "google_compute_region_health_check" "REDACTED_controllers_health_check_lb" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.controllers.google_compute_health_check.REDACTED_controllers_health_check_img,
│   on Modules\REDACTED_controllers\active_controller.tf line 367, in resource "google_compute_health_check" "REDACTED_controllers_health_check_img":
│  367: resource "google_compute_health_check" "REDACTED_controllers_health_check_img" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.controllers.google_compute_region_ssl_certificate.default,
│   on Modules\REDACTED_controllers\active_controller.tf line 460, in resource "google_compute_region_ssl_certificate" "default":
│  460: resource "google_compute_region_ssl_certificate" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with module.REDACTED_workers.google_compute_instance_template.REDACTED-worker-template-1,
│   on Modules\REDACTED_workers\igm_workers.tf line 11, in resource "google_compute_instance_template" "REDACTED-worker-template-1":
│   11: resource "google_compute_instance_template" "REDACTED-worker-template-1" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.REDACTED_workers.google_compute_instance_template.REDACTED-worker-template-2,
│   on Modules\REDACTED_workers\igm_workers.tf line 46, in resource "google_compute_instance_template" "REDACTED-worker-template-2":
│   46: resource "google_compute_instance_template" "REDACTED-worker-template-2" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.REDACTED_workers.google_compute_instance_template.REDACTED-worker-template-auto,
│   on Modules\REDACTED_workers\igm_workers.tf line 158, in resource "google_compute_instance_template" "REDACTED-worker-template-auto":
│  158: resource "google_compute_instance_template" "REDACTED-worker-template-auto" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with module.monitoring.google_monitoring_notification_channel.email,
│   on Modules\monitoring\monitoring.tf line 1, in resource "google_monitoring_notification_channel" "email":
│    1: resource "google_monitoring_notification_channel" "email" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.monitoring.google_pubsub_topic.pub_sub_topic,
│   on Modules\monitoring\monitoring.tf line 11, in resource "google_pubsub_topic" "pub_sub_topic":
│   11: resource "google_pubsub_topic" "pub_sub_topic" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with module.monitoring.google_monitoring_uptime_check_config.controller,
│   on Modules\monitoring\monitoring.tf line 83, in resource "google_monitoring_uptime_check_config" "controller":
│   83: resource "google_monitoring_uptime_check_config" "controller" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.monitoring.google_monitoring_uptime_check_config.lb,
│   on Modules\monitoring\monitoring.tf line 105, in resource "google_monitoring_uptime_check_config" "lb":
│  105: resource "google_monitoring_uptime_check_config" "lb" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References
The error occurs with the latest provider v4.53.1 but also with older: 4.42.1
The error occurs with the latest Terraform v1.3.9 but also with older v1.2.6
Issue start occurring after 15 Feb 2023

* #0000

**Comment by edwardmedia** [comment]
This is the issue at the Terraform SDK

Dup of https://github.com/hashicorp/terraform-provider-google/issues/13775

Closing as a dup

**Comment by papqin** [comment]
Dont see any solutions in linked issues? Can you advise?

**Comment by papqin** [comment]
Sorry :) looks like my VDI moved to AMD. Changed Terraform to the AMD version and is working now. 

Terraform v1.3.9 on windows_amd64
