### ISSUE TITLE
Add Remote Function UDFs

### ISSUE THREAD

**Issue by CallumFriend** [hashicorp/terraform-provider-google#13817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for **remote function UDF** in the routines module.
 

### New or Affected Resource(s)

google_bigquery_routine

### Potential Terraform Configuration

```tf
resource "google_bigquery_routine" "sproc" {
  dataset_id      = google_bigquery_dataset.test.dataset_id
  routine_id      = "tf_test_routine_id%{random_suffix}"
  routine_type    = "REMOTE_FUNCTION"
  
  remoteFunctionOptions {
    endpoint= "string",
    connection= "string",
    userDefinedContext = jsonencode({"columns" : [
    { "name" : "value"}
    ]}),
    "maxBatchingRows": string
  }
}
```

Potentially linking to a connection resource but not sure on the best way as I'm mostly a user.

### References

[Routine API remote function bit](https://cloud.google.com/bigquery/docs/reference/rest/v2/routines#RemoteFunctionOptions)

b/299600726

**Comment by obada-ab** [comment]
Picked this up, PR(currently draft): https://github.com/GoogleCloudPlatform/magic-modules/pull/9893
