### ISSUE TITLE
Intermittent Error 409 `alreadyExists` when creating a `google_dns_response_policy`

### ISSUE THREAD

**Issue by danopia** [hashicorp/terraform-provider-google#13811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

    Terraform/1.3.4 (+https://www.terraform.io)
    Terraform-Plugin-SDK/2.10.1
    terraform-provider-google-beta/4.53.1

### Affected Resource(s)

* google_dns_response_policy

### Terraform Configuration Files

```tf
resource "google_compute_network" "network" {
  name                            = "network"
  auto_create_subnetworks         = false
  delete_default_routes_on_create = true
}

resource "google_dns_response_policy" "network" {
  provider             = google-beta
  response_policy_name = "network"

  networks {
    network_url = google_compute_network.network.id
  }
}
```

### Debug Output

This debug output contains other resource creations as it was captured from a real execution from a larger config.

https://gist.github.com/danopia/65c94c0e3795c7dc0a82242206c813b2

### Expected Behavior

* The resource should be created and recorded into the Terraform state.

```
google_dns_response_policy.network: Creating...
google_dns_response_policy.network: Creation complete after 2s [id=projects/forto-prj-example/responsePolicies/network]
```

### Actual Behavior

* Terraform tries creating the resource
* After 60 seconds, the resource creation fails with "Error 409"
* Terraform won't be able to successfully apply again until the response_policy is deleted from Google or imported into Terraform

```
google_dns_response_policy.network: Creating...
google_dns_response_policy.network: Still creating... [10s elapsed]
google_dns_response_policy.network: Still creating... [20s elapsed]
google_dns_response_policy.network: Still creating... [30s elapsed]
google_dns_response_policy.network: Still creating... [40s elapsed]
google_dns_response_policy.network: Still creating... [50s elapsed]
google_dns_response_policy.network: Still creating... [1m0s elapsed]
╷
│ Error: Error creating ResponsePolicy: googleapi: Error 409: The resource 'entity.responsePolicy' named 'network' already exists, alreadyExists
│ 
│   with google_dns_response_policy.network,
│   on network.tf line 63, in resource "google_dns_response_policy" "network":
│   63: resource "google_dns_response_policy" "network" {
│ 
╵
```

### Steps to Reproduce

I was unable to reproduce this in a GCP project that already created a `google_dns_response_policy`. It seems that the first creation is the possibly problematic one.

So, the best shot is:

1. create a GCP project
1. enable google dns API service
1. `terraform apply`

### Important Factoids

* I'm running this within a minute of creating a project.
* Occurs maybe 1 in 4 times.
* The debug log shows a retry: `Dismissed an error as retryable based on error code: googleapi: got HTTP response code 502 with body: HTTP/2.0 502 Bad Gateway`

**Comment by megan07** [comment]
Hi @danopia, I'm sorry you're hitting this - these `502`'s can be frustrating. What appears to be happening to me is that there ends up being a server error between Google creating the response policy and the API returning the response, thus the policy is created, and on retry of the `502` we see it already exists. We can't change anything with regard to that, I think best case we can maybe investigate if waiting longer after creating the project would help with the server error or if something in the configuration is causing it (my only thought would be potentially deleting default routes on create?). These would just be things I see that spark my curiosity, because I don't have insight what is happening on the backend, but might be worth exploring if the issue is persistently 25% of the time, in which case I'd consider this more an upstream issue.

**Comment by danopia** [comment]
Hey, thanks for responding. The debug log definitely shows this was a Google error and it also hasn't recurred in the past couple weeks, so I'll just sell close.
