### ISSUE TITLE
Add Supported Database Flags data source for AlloyDB

### ISSUE THREAD

**Issue by GauravJain21** [hashicorp/terraform-provider-google#13813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)
- google_alloydb_supported_database_flags

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References
[Supported Database Flags API](https://cloud.google.com/alloydb/docs/reference/rest/v1beta/projects.locations.supportedDatabaseFlags)

**Comment by rileykarson** [comment]
Note: This API is list-only: https://cloud.google.com/alloydb/docs/reference/rest/v1beta/projects.locations.supportedDatabaseFlags/list#SupportedDatabaseFlag

**Comment by GauravJain21** [comment]
Hey,
Is there a problem with a list only API?
The use case I have in mind is that a user wants to list down all the supported database flags and enable them accordingly.
Kindly help to refine my understanding here.
Best,
Gaurav

**Comment by rileykarson** [comment]
They're difficult to actually use in a Terraform configuration in any kind of meaningful way. Terraform doesn't work well with outputs of unknown length at plan time. So while we can support a datasource for the information mechanically, there's a pretty big gap between supporting it and it actually being useful to users.

Take a look at release channel support in https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_engine_versions for an example of a transformation we've had to make for a list API to be useful in a configuration.

**Comment by melinath** [comment]
this was resolved by the related PR.

**Comment by melinath** [comment]
forgot to actually close this
