### ISSUE TITLE
google_artifact_registry_repository cleanup policy

### ISSUE THREAD

**Issue by adriantr** [hashicorp/terraform-provider-google#13824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is currently no possibility to [set cleanup policy](https://cloud.google.com/artifact-registry/docs/repositories/cleanup-policy) for artifact registry through Terraform

### New or Affected Resource(s)

* google_artifact_registry_repository

### Potential Terraform Configuration

```tf
resource "google_artifact_registry_repository_cleanup_policy" "main" {
  name = "policy"
  action = "DELETE"
  condition {
    version_age = "30d"
  }
}
```

```tf
resource "google_artifact_registry_repository_cleanup_policy_binding" "main" {
  repository = google_artifact_registry_repository.main.name
  project = google_artifact_registry_repository.main.project
  location = google_artifact_registry_repository.main.location
  policy = google_artifact_registry_repository_cleanup_policy.main.id
}
```

### References

* b/272798258

**Comment by rileykarson** [comment]
Note: There's no settings to enable this in the API: https://cloud.google.com/artifact-registry/docs/reference/rest

Not sure how it's available in gcloud, in that case.

**Comment by philip-harvey** [comment]
It must be in the API but it's private preview currently so not in the API docs yet

**Comment by neurolabs** [comment]
https://cloud.google.com/artifact-registry/docs/repositories/cleanup-policy shows how you can use gcloud to set the cleanup policy.

**Comment by danquack** [comment]
Using the verbosity option, I'm not seeing the list-functionality return any results:

LIST: `gcloud artifacts repositories list-cleanup-policies [repository]`
```
GET /v1/projects/[project-name]/locations/[location]/repositories/[repository]?alt=json

{
  "name": "projects/[project-name]/locations/[location]/repositories/[repository]",
  "format": "DOCKER",
  "createTime": "2023-06-08T01:29:45.938615Z",
  "updateTime": "2023-06-22T14:27:33.401054Z",
  "mode": "STANDARD_REPOSITORY",
  "dockerConfig": {}
}

```

CREATE: `gcloud artifacts repositories set-cleanup-policies [repository] --policy policy.json`

```
PATCH /v1/projects/[project-name]/locations/[location]/repositories/[repository]?updateMask=cleanupPolicies?alt=json

{
    "cleanupPolicies": {
        "test": {
            "action": "Keep",
            "id": "test",
            "mostRecentVersions": {
                "keepCount": 100000
            }
        }
    },
    "createTime": "2023-06-08T01:29:45.938615Z",
    "dockerConfig": {},
    "format": "DOCKER",
    "mode": "STANDARD_REPOSITORY",
    "name": "projects/[project-name]/locations/[location]/repositories/[repository]",
    "updateTime": "2023-06-22T14:14:01.780517Z"
}
```

DELETE `gcloud artifacts repositories delete-cleanup-policies [repository] --policy policy.json`
```
PATCH /v1/projects/[project-name]/locations/[location]/repositories/[repository]?updateMask=cleanupPolicies?alt=json

{
    "createTime": "2023-06-08T01:29:45.938615Z",
    "dockerConfig": {},
    "format": "DOCKER",
    "mode": "STANDARD_REPOSITORY",
    "name": "pprojects/[project-name]/locations/[location]/repositories/[repository]",
    "updateTime": "2023-06-22T14:27:33.401054Z"
}
```
