### ISSUE TITLE
container_node_pool add support for raw block local NVMe SSDs 

### ISSUE THREAD

**Issue by Enzyme3** [hashicorp/terraform-provider-google#13829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
GKE v1.25.3-gke.1800+ adds [support for ephemeral and block devices backed by local NVMe SSD](https://cloud.google.com/kubernetes-engine/docs/concepts/local-ssd#api)
It appears that support for "Ephemeral Storage Local SSD API" (--ephemeral-storage-local-ssd) is [already implemented](https://github.com/hashicorp/terraform-provider-google/issues/8461)
But support for "Local NVMe SSD Block API" is missing (--local-nvme-ssd-block)

### New or Affected Resource(s)
* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration
```tf
resource "google_container_node_pool" "pool" {
  node_config {
    local_nvme_ssd_block {
      local_ssd_count = 2
    }    
  }
}
```

### References

* #8461
* [Ephemeral and block devices backed by local NVMe SSD](https://cloud.google.com/kubernetes-engine/docs/concepts/local-ssd#api)
* b/272369317

**Comment by geojaz** [comment]
I'll pick this one up
