### ISSUE TITLE
Issues with secret name's alias in google_cloud_run_service

### ISSUE THREAD

**Issue by Miky14880** [hashicorp/terraform-provider-google#13830]
Hello
In the documentation for `google_cloud_run_service` , the `secret_key_ref` block says that, for `name` argument, we could define an alias by using the form:  :projects/{project-id|project-number}/secrets/. 
This is used in case the secret is stored in another project.
Which is the correct procedure in this case for creating this alias?
If we just add the above mentioned prefix in the string name it is not working as we get error as name should only contain alphanumeric char, hypens or underscores.....

**Comment by Miky14880** [comment]
Hello,
unfortunately our Terraform modules are segregated by project, hence we cannot define a Google secret in another project different from the one where we are working.
As a consequence we cannot use the google_secret_manager_secret definition

_resource "google_secret_manager_secret" "secret" {
  secret_id = "secret"
  project = "<name_of_the_external_project>"
  replication {
    automatic = true
  }
}_

in the same place where we define the google_cloud_run_service, because they are on different projects.
When we run the code we got the following:
_Error: Error creating Secret: googleapi: Error 403: Permission 'secretmanager.secrets.create' denied for resource 'projects/<name_of_the_external_project>' (or it may not exist)._

Any suggestion?
Best Regards
Michela

**Comment by edwardmedia** [comment]
@Miky14880 does your terraform runner have the Permission 'secretmanager.secrets.create' on the project where the secret resides?

Error: Error creating Secret: googleapi: Error 403: Permission 'secretmanager.secrets.create' denied for resource 'projects/<name_of_the_external_project>' (or it may not exist).

**Comment by edwardmedia** [comment]
@Miky14880 is this still an issue?

**Comment by edwardmedia** [comment]
@Miky14880 closing this assuming it is no longer a question
