### ISSUE TITLE
Failing test(s): TestAccWorkstationsWorkstationConfig_

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13847]
### Failure rates

- Quota hit on 2nd night this test was in the nightly builds

### Impacted tests

- TestAccWorkstationsWorkstationConfig_displayName

### Affected Resource(s)

* google_workstations_workstation_cluster
* google_workstations_workstation_config 

### Nightly build test history

- [Test History: TestAccWorkstationsWorkstationConfig_displayName](https://ci-oss.hashicorp.engineering/test/-4233920961808192411?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)

### PR test failures

* TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample failing in this PR due to a resource-already-exists error on the service account: https://github.com/GoogleCloudPlatform/magic-modules/pull/6989#issuecomment-1446804618

### Message(s)

**TestAccWorkstationsWorkstationConfig_displayName**
```
Error: Error creating WorkstationCluster: googleapi: Error 429: Quota limit 'WorkstationClustersPerProjectPerRegion' has been exceeded. Limit: 5 in region us-central1.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.QuotaFailure",
"violations": [
{
"description": "Quota 'WorkstationClustersPerProjectPerRegion' exhausted. Limit 5 in region us-central1",
"subject": "project:[PROJECT_NUMBER]"
```

**TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample**
```
=== CONT  TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample
    provider_test.go:319: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating service account: googleapi: Error 409: Service account cloud-workstations-kms already exists within project projects/[PROJECT_NAME].
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.ResourceInfo",
            "resourceName": "projects/[PROJECT_NAME]/serviceAccounts/cloud-workstations-kms@[PROJECT_NAME].iam.gserviceaccount.com"
          }
        ]
        , alreadyExists
        
          with google_service_account.default,
          on terraform_plugin_test.tf line 46, in resource "google_service_account" "default":
          46: resource "google_service_account" "default" {

```

**Comment by roaks3** [comment]
Note: should be fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/7362

**Comment by rileykarson** [comment]
Quota issue seems to persist

**Comment by roaks3** [comment]
Looks like this quota can't be increased from the console, so I think we'll need to make an internal request, or use multiple regions in our tests.

**Comment by roaks3** [comment]
b/273543204

**Comment by roaks3** [comment]
Quota was increased on Mar 14, and the issue appears to be resolved now
