### ISSUE TITLE
`google_container_cluster` does not support dual-stack on creation

### ISSUE THREAD

**Issue by maxcorbin** [hashicorp/terraform-provider-google#13842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_container_cluster` is missing an option to set the stack type, options should be between `IPv4` and `IPv6`.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "cluster" {
  name     = var.name
  location = var.location
  stack_type = var.use_dual_stack ? "IPV4_IPV6" : "STACK_TYPE_UNSPECIFIED"
}
```

### References

[Documentation for the endpoint has three options](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#stacktype), `IPV4` for IPv4 only, `IPV4_IPV6` for dual-stack, and `STACK_TYPE_UNSPECIFIED`, which defaults to `IPV4`.

There are [additional requirements](https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#dual_stack_limitations) that the user needs to fulfill for this to work, but at the moment the user must update the cluster manually after the (lengthy) cluster creation process has finished.

Also, #13752 seems related as it also has to do with support for dual-stack networking in GCP.

### References

* b/265821032

**Comment by 600lyy** [comment]
I am looking at this one. The cluster resource is a handwritten resource in the magic module and I'll see if I could add a new field in the existing resource file

**Comment by 600lyy** [comment]
StackType is part of the IPAllocationPolicy in the Go container library:
https://pkg.go.dev/google.golang.org/api/container/v1#IPAllocationPolicy

Proposed Terraform Configuration:
```
ip_allocation_policy {
    cluster_secondary_range_name  = "pod-ranges"
    services_secondary_range_name = google_compute_subnetwork.custom.secondary_ip_range.0.range_name
    stack_type = "IPV4" || "IPV4_IPV6" || "STACK_TYPE_UNSPECIFIED"
}
```

**Comment by 600lyy** [comment]
PR submitted: https://github.com/GoogleCloudPlatform/magic-modules/pull/7459

**Comment by 600lyy** [comment]
PR merged and closed. Dual stack support will be included in the upcoming TF Google provider releases.

* `stack_type` - (Optional) The IP Stack Type of the cluster. 
Default value is `IPV4`.
Possible values are `IPV4` and `PV4_IPV6`.

**Comment by de-metavision** [comment]
possible values should probably be `IPV4` and `IPV4_IPV6`.

**Comment by rileykarson** [comment]
Closing based on https://github.com/GoogleCloudPlatform/magic-modules/pull/7459, thanks! One useful trick in GitHub is "Fixes:"- if you specify an issue in the PR body like "Fixes: https://github.com/hashicorp/terraform-provider-google/issues/13842" the PR getting merged will close the issue as long as the person merging the PR has permission to do so!
