### ISSUE TITLE
Add support for CloudSql data resource to fetch the default service account

### ISSUE THREAD

**Issue by CalinFlorescu** [hashicorp/terraform-provider-google#13844]
Suppose you want to manage permissions of a default service account in GCP using Terraform. In that case, you first need to activate that service account by making a request to its API (according to the GCP documentation). 

There are similar resources that have this already, like: 
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/storage_project_service_account

It would be great if the provider would have support for this because, at this time, I am forced to use the gcloud module to activate that service account.

Thank you!

**Comment by DasLeo** [comment]
+1 on that

**Comment by rileykarson** [comment]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity can be used to fetch generic service accounts!
