### ISSUE TITLE
Add Documentation on Conflicting configuration arguments 

### ISSUE THREAD

**Issue by haprcr** [hashicorp/terraform-provider-google#13843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the AlloyDB Terraform [Document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_cluster#time_based_retention), for the cluster resource, it is not mentioned that `time_based_retention` and `quantity_based_retention` are conflicting arguments. Any one of the argument needs to be specified and not both in order for the AlloyDB cluster to be created. 

### New or Affected Resource(s)

[`google_alloydb_cluster`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_cluster)

* google_XXXXX

### References

* #0000

<img width="658" alt="issue1-adb" src="https://user-images.githubusercontent.com/124026578/221518558-152afb06-baa0-4035-bfba-25f72236a480.png">

**Comment by ibhaskar2** [comment]
@rileykarson, this issue is resolved by hashicorp/terraform-provider-google-beta/pull/5519. Please have a look and close this issue.

**Comment by rileykarson** [comment]
Thanks! For future PRs this can be automated, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
