### ISSUE TITLE
Unable to download version 2.20.3

### ISSUE THREAD

**Issue by GuyCarmy** [hashicorp/terraform-provider-google#13859]
this issue is back 
https://github.com/hashicorp/terraform-provider-google/issues/12255

its exactly the same issue..

**Comment by SarahFrench** [comment]
Hi 👋, sorry that this issue has returned. I've raised it with the relevant team and will update this issue when it'd been addressed.

**Comment by efxvbr1** [comment]
I am getting this same error now. 

Error while installing hashicorp/google v2.20.3: could not query provider
13:03:28  registry for registry.terraform.io/hashicorp/google: registry response
13:03:28  includes invalid version string "4,5": can't specify multiple versions; a
13:03:28  single exact version is required
Do you have any work around like upgrading the version in terraform ?

**Comment by SarahFrench** [comment]
Here's a possible workaround: https://github.com/hashicorp/terraform-provider-google/issues/12255#issuecomment-1205680271

**Comment by mid198** [comment]
Hey getting similar issues
17:21:06  [0mError while installing hashicorp/google-beta v2.20.3: could not query provider
17:21:06  registry for registry.terraform.io/hashicorp/google-beta: registry response
17:21:06  includes invalid version string "4,5": can't specify multiple versions; a
17:21:06  single exact version is required

**Comment by SarahFrench** [comment]
This should now be fixed:
- https://registry.terraform.io/v1/providers/hashicorp/google/2.20.3/download/linux/amd64 shows the new `"protocols":["4.0","5.0"]` value
- https://registry.terraform.io/v1/providers/hashicorp/google-beta/2.20.3/download/linux/amd64 shows the new `"protocols":["4.0","5.0"]` value
- that change is also present in https://registry.terraform.io/v1/providers/hashicorp/google/versions

**Comment by SarahFrench** [comment]
@GuyCarmy could you please check if you can download the provider ok now?

**Comment by GuyCarmy** [comment]
@SarahFrench its working, sorry for the late response, thanks!!
