### ISSUE TITLE
Cloud SQL User Resource Not Deleted if Cloud SQL Instance Is Deleted

### ISSUE THREAD

**Issue by martinmaly** [hashicorp/terraform-provider-google#13851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.55.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected Resource(s)

* `google_sql_database_instance`
* `google_sql_user`

### Terraform Configuration Files

This issue happens on an `apply` of a modified config. Original and modified configs are therefore provided.

**Original Config**:

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }

  backend "gcs" {
    bucket = PROVIDE_GCS_BUCKET
  }
}


variable "project" {
  type        = string
  description = "GCP project for provisioning cloud resources."
}

variable "region" {
  type        = string
  description = "GCP region for provisioning regional resources."
  default     = "us-west1"
}


resource "google_sql_database_instance" "sql" {
  name             = "test-sql"
  database_version = "MYSQL_8_0"
  region           = var.region
  project          = var.project

  settings {
    tier                        = "db-n1-standard-1"
    deletion_protection_enabled = false
  }

  deletion_protection = false
}

resource "google_sql_database" "database" {
  name = "test"
  instance = google_sql_database_instance.sql.name
}

resource "google_sql_user" "user" {
  name = "test" 
  instance = google_sql_database_instance.sql.name
  password = random_password.password.result
}

resource "random_password" "password" {
  length      = 20
  min_lower   = 4
  min_numeric = 4
  min_special = 4
  min_upper   = 4
}
```

**Updated Config**: The change was to rename the `google_sql_database_instance` resource

from `resource "google_sql_database_instance" "sql" { ... }`

to `resource "google_sql_database_instance" "renamed" { ... }`

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }

  backend "gcs" {
    bucket = PROVIDE_GCS_BUCKET
  }
}


variable "project" {
  type        = string
  description = "GCP project for provisioning cloud resources."
}

variable "region" {
  type        = string
  description = "GCP region for provisioning regional resources."
  default     = "us-west1"
}


resource "google_sql_database_instance" "renamed" {     # <<- renamed "sql" -> "renamed"
  name             = "test-sql"
  database_version = "MYSQL_8_0"
  region           = var.region
  project          = var.project

  settings {
    tier                        = "db-n1-standard-1"
    deletion_protection_enabled = false
  }

  deletion_protection = false
}

resource "google_sql_database" "database" {
  name = "test"
  instance = google_sql_database_instance.renamed.name     # <<- renamed "sql" -> "renamed"
}

resource "google_sql_user" "user" {
  name = "test" 
  instance = google_sql_database_instance.renamed.name     # <<- renamed "sql" -> "renamed"
  password = random_password.password.result
}

resource "random_password" "password" {
  length      = 20
  min_lower   = 4
  min_numeric = 4
  min_special = 4
  min_upper   = 4
}
```

### Debug Output

[terraform apply log](https://gist.github.com/martinmaly/4e51010786bdacf6e83331db31969576)

### Expected Behavior

Terraform or Google provider should realize that by deleting the Cloud SQL instance, the user resource was deleted too.

### Actual Behavior

Terraform doesn't realize that the user was deleted, tries to refresh the state but Cloud SQL returns 403, possibly incorrectly, on a user that was deleted (along with the database instance).

```
│ Error: Error when reading or editing SQL User "test" in instance "test-sql": googleapi: Error 403: The client is not authorized to make this request., notAuthorized
│
│   with google_sql_user.user,
│   on sql.tf line 20, in resource "google_sql_user" "user":
│   20: resource "google_sql_user" "user" {
│
╵
```

### Steps to Reproduce

1. `terraform apply` the original config
2. rename the SQL resource, for example `"sql"` --> `"renamed"` as indicated
3. `terraform apply` (this results in [an error](https://gist.github.com/martinmaly/77323c0c85335497010da6f0dc2532bc). This error seems one-off
4. `terraform apply` This and any subsequent apply results in the error as described above (` Error when reading or editing SQL User "test" in instance "test-sql": googleapi: Error 403: The client is not authorized to make this request., notAuthorized`)

### Important Factoids

n/a

### References

https://github.com/hashicorp/terraform-provider-google/issues/7362#issuecomment-784034937 seems related

**Comment by edwardmedia** [comment]
@martinmaly keep in mind the sql instance name can't be reused within a week. By renaming the terraform resources, are you able to apply for `google_sql_database_instance`?

**Comment by martinmaly** [comment]
@edwardmedia - The config doesn't actually rename the GCP resource but the Terraform identifier

from 

```tf
resource "google_sql_database_instance" "sql" {
  name = "test-sql"
}
```

to

```tf
resource "google_sql_database_instance" "renamed" {   # "sql" --> "renamed"
  name = "test-sql"  # UNCHANGED !!!
}
```

**Comment by edwardmedia** [comment]
@martinmaly interesting. What did you when you run `terraform plan` after you renamed [as you said](https://github.com/hashicorp/terraform-provider-google/issues/13851#issuecomment-1448570741) the Terraform identifier? Can you share your plan?

**Comment by martinmaly** [comment]
Sorry for the delay; I think I attached the plan but apparently not:

https://gist.github.com/martinmaly/3478b12f91e1ac98e7d082881e1d1fac

**Comment by rileykarson** [comment]
@edwardmedia: Have you attempted to reproduce this locally?
