### ISSUE TITLE
Add support for IPv6 prefix exchange in google_compute_router_peer

### ISSUE THREAD

**Issue by bcleenders** [hashicorp/terraform-provider-google#13852]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We'd like to enable IPv6, and one of the steps is configuring our BGP sessions to exchange ipv6 prefixes.

This is related to #13752 - both are required to set up a VPN and use it for IPv6 traffic.

### New or Affected Resource(s)

* `google_compute_router_peer`

### Potential Terraform Configuration

```tf
resource "google_compute_router_peer" "peer" {
  name                      = "my-router-peer"
  router                    = "my-router"
  region                    = "us-central1"
  peer_ip_address           = "169.254.1.2"
  peer_asn                  = 65513
  advertised_route_priority = 100
  interface                 = "interface-1"
  
  # New fields:
  enable_ipv6               = true
  ipv6_nexthop_address      = "2600:2d00:0000:0002:0000:0000:0000:0001"
  peer_ipv6_nexthop_address = "2600:2d00:0:3::1" # short notation
}
```

Restrictions:
- The nexthop fields can only be set if ipv6 is enabled
- Either both nexthop fields must be set, or neither (defaults to automatic config)
- Both nexthop fields must be in `2600:2d00:0:2::/64` or `2600:2d00:0:3::/64` range (see second documentation link below, not listed as part of API).

### References

- [Router API config](https://cloud.google.com/compute/docs/reference/rest/v1/routers) which shows the field names.
- [documentation on enabling IPv6 for VPNs](https://cloud.google.com/network-connectivity/docs/router/how-to/configuring-ipv6-bgp)

* #13752

**Comment by 600lyy** [comment]
I am on it.

**Comment by shuyama1** [comment]
Closing the issue as https://github.com/GoogleCloudPlatform/magic-modules/pull/7583 is merged. Thanks for the work @600lyy!
