### ISSUE TITLE
Missing Alert Policy Example is incorrect

### ISSUE THREAD

**Issue by caitlinrubin** [hashicorp/terraform-provider-google#13856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

The example at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#example-usage---monitoring-alert-policy-evaluation-missing-data should use condition_absent not condition_threshold

### Affected Resource(s)

- google_monitoring_alert_policy

**Comment by edwardmedia** [comment]
@caitlinrubin I think the example is designed to show how to use the field [evaluation_missing_data](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#evaluation_missing_data). Yes `condition_absent` is another field. You may file an enhancement if you ask for its example.
