### ISSUE TITLE
google_compute_security_policy shows changes in rate-based rules every time on "terraform plan"

### ISSUE THREAD

**Issue by Pluto1024** [hashicorp/terraform-provider-google#13863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.46.0

### Affected Resource(s)

* google_compute_security_policy

### Debug Output

 ```
- rule {
          - action      = "rate_based_ban" -> null
          - description = "Test rule" -> null
          - preview     = true -> null
          - priority    = 5000 -> null

          - match {
              - versioned_expr = "SRC_IPS_V1" -> null

              - config {
                  - src_ip_ranges = [
                      - "*",
                    ] -> null
                }
            }

          - rate_limit_options {
              - ban_duration_sec = 300 -> null
              - conform_action   = "allow" -> null
              - enforce_on_key   = "XFF_IP" -> null
              - exceed_action    = "deny(429)" -> null

              - ban_threshold {
                  - count        = 10000 -> null
                  - interval_sec = 180 -> null
                }

              - rate_limit_threshold {
                  - count        = 6000 -> null
                  - interval_sec = 60 -> null
                }
            }
        }
      + rule {
          + action      = "rate_based_ban"
          + description = "Test rule"
          + preview     = true
          + priority    = 5000

          + match {
              + versioned_expr = "SRC_IPS_V1"

              + config {
                  + src_ip_ranges = [
                      + "*",
                    ]
                }
            }

          + rate_limit_options {
              + ban_duration_sec = 300
              + conform_action   = "allow"
              + enforce_on_key   = "XFF_IP"
              + exceed_action    = "deny(429)"

              + ban_threshold {
                  + count        = 10000
                  + interval_sec = 180
                }

              + rate_limit_threshold {
                  + count        = 6000
                  + interval_sec = 60
                }
            }
        }
```

### Expected Behavior

No changes should be shown in plan, as there is no changes in code for this rule.

### Actual Behavior

Terraform produces delete/create output for the rule on every "terraform plan". There is no changes in code for this or any other rules in this policy.

### Steps to Reproduce

1. Add terraform block for rate_limit rule in google_compute_security_policy
2. Run `terraform apply` to create the rule
3. Run `terraform plan` again without changing any code

**Comment by edwardmedia** [comment]
@Pluto1024 can you share your config?

**Comment by Pluto1024** [comment]
@edwardmedia 
Non of variables are changed before plan.

```
  dynamic "rule" {
    for_each = var.rate_limit == true ? [1] : []
    content{
      action      = "rate_based_ban"
      preview     = var.rate_limit_preview
      description = "Test rule"
      priority    = 5000
      rate_limit_options {
        enforce_on_key    = "XFF_IP"
        exceed_action     = "deny(429)"
        conform_action    = "allow"
        ban_duration_sec  = 300
        rate_limit_threshold {
          count         = var.rate_limit_count
          interval_sec  = var.rate_limit_interval_sec
        }
        ban_threshold {
          count         = var.ban_count
          interval_sec  = var.ban_interval_sec
        }
      }
      match {
        versioned_expr  = "SRC_IPS_V1"
        config {
          src_ip_ranges = ["*"]
        }
      }
    }
  }
```

**Comment by edwardmedia** [comment]
@Pluto1024 can you remove the dynamic code and create a minimum config that can be used to repro the issue?

**Comment by Pluto1024** [comment]
@edwardmedia I did couple tests and it seems that this rule was affected by another rules in configuration.
I have another dynamic rules with Preconfigured WAF configuration in it. They are lower priority than rate-based rule and located before it in config file. They have the same problem with plan showing non existing updates. 
I tried to remove those rules and rate-based rule stopped showing non existing updates in plan (without any changes in rate-based rule itself).

**Comment by Pluto1024** [comment]
@edwardmedia I did some tests and it seems there is some connection between this rate-based rule and another rules in the policy. In particular I have 3 rules (created dynamically) that have "preconfigured_waf_config" block in them. They are lower priority than rate-based rule. When those rules were presented, initial issue occurred. When I deleted those 3 rules, rate-based rule behaved as expected without any additional changes in it.

I ended up recreating all rules and now when there is no changes in code, the plan is accurate and shows "no changes". That solves initial problem partially.
But when there is any change in any rule in this policy (not necessary in mentioned rules) plan shows "ghost changes" in those 3 rules and rate-based rule.

I understand that it is difficult to reproduce, but maybe it will give you some idea of what it maybe related to.

**Comment by edwardmedia** [comment]
@Pluto1024 using below config, I am not able to repro the issue. Probably I need your config for further investigation

```tf
resource "google_compute_security_policy" "policy" {
  name = "issue13863"
  rule {
    action   = "rate_based_ban"
    preview  = true
    priority = 10502

    match {
      expr {
        expression = "request.path.matches('/svc/api3/v3')"
      }
    }

    rate_limit_options {
      ban_duration_sec    = 60
      conform_action      = "allow"
      enforce_on_key      = "HTTP_HEADER"
      enforce_on_key_name = "authorization"
      exceed_action       = "deny(429)"

      rate_limit_threshold {
        count        = 200
        interval_sec = 60
      }
    }
  }
  rule {
    action   = "rate_based_ban"
    preview  = true
    priority = 10000

    match {
      expr {
        expression = "request.path.matches('/svc/api3/v3')"
      }
    }

    rate_limit_options {
      ban_duration_sec    = 300
      conform_action      = "allow"
      enforce_on_key      = "XFF_IP"
      # enforce_on_key_name = "authorization"
      exceed_action       = "deny(429)"

      rate_limit_threshold {
        count        = 200
        interval_sec = 60
      }
    }
  }
  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "default rule"
  }
}
```

**Comment by edwardmedia** [comment]
@Pluto1024 is this still an issue?

**Comment by Pluto1024** [comment]
Hi @edwardmedia I partially solved it by recreating all rules. You can close this issue, as I don't have example of the issue any more.
Thank you for looking into this.

**Comment by edwardmedia** [comment]
@Pluto1024 closing this as you requested. Thank you
