### ISSUE TITLE
Add Support For Bigquery Data Masking v1 API Options

### ISSUE THREAD

**Issue by jamesnicolas** [hashicorp/terraform-provider-google#13867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
This resource https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_policy_tag which uses the v1beta1 API is missing some of the options that are currently available in v1, namely the options for the `data_masking_policy.predefined_expression` field. It's currently missing `DATE_YEAR_MASK` which exists in the v1 API, but not in the v1beta1 API. Can we support the extra options that exist in v1? Link to v1 API. https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest/v1/projects.locations.dataPolicies

### New or Affected Resource(s)

* google_bigquery_datapolicy_data_policy

### Potential Terraform Configuration

```tf
resource "google_bigquery_datapolicy_data_policy" "data_policy" {
    provider = google-beta
    location         = "us-central1"
    data_policy_id   = "data_policy"
    policy_tag       = google_data_catalog_policy_tag.policy_tag.name
    data_policy_type = "COLUMN_LEVEL_SECURITY_POLICY"
    data_masking_policy {
        predefined_expression = "DATE_YEAR_MASK" # support add all possible values for this that exist in v1
    }
}
```

**Comment by rileykarson** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/7406
