### ISSUE TITLE
Not able to create GKE cluster with confidential nodes enabled

### ISSUE THREAD

**Issue by zagr0** [hashicorp/terraform-provider-google#13871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.55.0
```
### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "europe-west1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count = 1

  confidential_nodes {
    enabled = true
  }
}
```

### Expected Behavior

GKE cluster should be created with no errors.
__Note:__ that in our scenario is important to remove default node pool (`remove_default_node_pool = true`) as we are going to use our custom pools.

### Actual Behavior

Cluster creation fails with error:
```
google_container_cluster.primary: Creating...
╷
│ Error: googleapi: Error 400: Confidential nodes feature only supports N2D and C2D machine families., badRequest
│ 
│   with google_container_cluster.primary,
│   on gke_test.tf line 11, in resource "google_container_cluster" "primary":
│   11: resource "google_container_cluster" "primary" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by zagr0** [comment]
In case of trying to provide compatible instance type for `default-pool` we are experience issue that node pool is always trying to be recreated each time `terraform apply` executed, probably it tries to create it again each time (but it should be handled with `remove_default_node_pool` config):

example:
```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "europe-west1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true

  node_pool {
    name = "default-pool"
    node_config {
      machine_type = "n2d-standard-2"
    }
  }
}
```

Output:
```
google_container_cluster.primary: Refreshing state... [id=projects/***/locations/europe-west1/clusters/my-gke-cluster]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_container_cluster.primary must be replaced
-/+ resource "google_container_cluster" "primary" {
      ~ cluster_ipv4_cidr           = "10.204.0.0/14" -> (known after apply)
      + datapath_provider           = (known after apply)
...
      + node_pool { # forces replacement
          + initial_node_count          = (known after apply)
          + instance_group_urls         = (known after apply)
          + managed_instance_group_urls = (known after apply)
          + max_pods_per_node           = (known after apply)
          + name                        = "default-pool" # forces replacement
          + name_prefix                 = (known after apply)
          + node_count                  = (known after apply)
          + node_locations              = (known after apply)
          + version                     = (known after apply)
...
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by edwardmedia** [comment]
@zagr0 have you tried something like below config?

```tf
resource "google_container_cluster" "confidential_nodes" {
  name               = "%s"
  location           = "us-central1-a"
  release_channel {
    channel = "RAPID"
  }

  node_pool {
    name = "%s"
    initial_node_count = 1
    node_config {
      machine_type = "n2d-standard-2" // can't be e2 because Confidential Nodes require AMD CPUs
    }
  }

  confidential_nodes {
    enabled = true
  }
}
```

**Comment by zagr0** [comment]
@edwardmedia , yes I tried, please check my [comment](https://github.com/hashicorp/terraform-provider-google/issues/13871#issuecomment-1449869733). Or maybe I missing something?
The problem is that I require `remove_default_node_pool = true` for this cluster, but this cause the issue with forcing of cluster recreation each time when I do `terraform apply`

**Comment by edwardmedia** [comment]
@zagr0 do you say providing `remove_default_node_pool = true` in the config causes recreation each time? Your above plan seems not say that. Can you explain a little more detail?

Do you use [node_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended) resource to manage you nodes?

**Comment by zagr0** [comment]
@edwardmedia , yes, exactly, with confidential nodes enabled and `remove_default_node_pool = true` terraform always want to replace the cluster:
```
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "europe-west1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true

  confidential_nodes {
    enabled = true
  }

  node_pool {
    name = "default-pool"
    node_config {
      machine_type = "n2d-standard-2"
    }
  }
}
```

Just for simplicity example in the ticket is missing node_pool resource, but we are using it according our use case. The cluster replace each terraform apply happens either with additional node pools or without them.

**Comment by edwardmedia** [comment]
@slevenick can you take a look at this?

**Comment by slevenick** [comment]
I'm not sure there is a problem here. I get the same behavior with confidential nodes disabled, so it seems like the behavior is caused by the combination of a node-pool & remove_default_node_pool. To my eye this seems intentional, as you've configured a node_pool and then immediately removed it via remove_default_node_pool.

Why do you believe this is a bug with confidential nodes?

**Comment by slevenick** [comment]
I don't think this is actually a problem.

When you use `remove_default_node_pool` it is expected that Terraform will remove the default node pool even when it's defined in the config. The problem is that Terraform doesn't know that it did that, so it sees your initial node pool config is gone and wants to recreate it.

I think the solution here is to add an ignore_changes block that targets the node_pool field, so you can set the node_pool initially, then delete it via remove_default_node_pool, and Terraform won't track changes on it. Does that make sense?

**Comment by zagr0** [comment]
Hi @slevenick, I can confirm that workaround with `ignore_changes` for node pool section works.
But still it seems like issue for `remove_default_node_pool` in combination with provided `node_pool` and terraform should handle the case, keep the state and not to try to create it if its instructed to remove default pool.

**Comment by slevenick** [comment]
Unfortunately this is the expected workaround for this issue. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#node-pool-management

We don't plan to do any more complex behavior around ignoring the node_pool when `remove_default_node_pool` is set.
