### ISSUE TITLE
GKE node_pool taints should not force resource recreation

### ISSUE THREAD

**Issue by gorge511** [hashicorp/terraform-provider-google#13872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.7
on darwin_amd64
```

Google Terraform Provider 4.55.0

### Affected Resource(s)

* google_container_node_pool

### Expected Behavior

Node pool should be modified in place. This change works in the GCP Console WebUI. So there should be possibility to update taints without node pool recreation.

Also this works with `gcloud`. See the [docs for update command](https://cloud.google.com/sdk/gcloud/reference/container/node-pools/update#--node-taints). 

### Actual Behavior

When you change the `taint` in `node_config` block on the node pool the resource is forced to be recreated.

There is a [limitation written in the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#taint), but I think this is no longer relevant for non-default node pools.

See the [forcing code in google provider](https://github.com/hashicorp/terraform-provider-google/blob/main/google/node_config.go#L325).
And see the [`gcloud` command docs](https://cloud.google.com/sdk/gcloud/reference/container/node-pools/update#--node-taints) where you can see that `--node-taints` is available in update operation.

### Steps to Reproduce

1. Create GKE cluster with non-default node pool with `google_container_node_pool` without `taint` in the `node_config` block.
2. Add any `taint` in the `node_config` block.
3. Plan now shows node pool recreation.

### References

* b/298500120

**Comment by rileykarson** [comment]
Note: We've had a lot of issues with GKE taints over time- we really need to rethink our model for them. See https://github.com/hashicorp/terraform-provider-google/issues/7928 for a related issue.

**Comment by ondrejhlavacek** [comment]
Can be closed, it's fixed, see https://github.com/hashicorp/terraform-provider-google/issues/7928 for details.
