### ISSUE TITLE
Could not add linux_node_config under node_config (Error: Blocks of type "linux_node_config" are not expected here.)

### ISSUE THREAD

**Issue by songohannyc** [hashicorp/terraform-provider-google#13870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v1.3.9
on darwin_amd64

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/google-beta from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Using previously-installed hashicorp/google v4.24.0
- Using previously-installed hashicorp/google-beta v4.55.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "ci_cluster" {
  count              = var.all_in_one_cluster ? 1 : 0
  name               = "${var.name_prefix}-${var.gke_cluster_name}"
  location           = var.region
  node_locations     = var.zones
  network            = var.existing_vpc_network != "" ? var.existing_vpc_network : google_compute_network.vpc_network[0].id
  subnetwork         = var.existing_subnetwork != "" ? var.existing_subnetwork : google_compute_subnetwork.subnetwork[0].id
  enable_legacy_abac = false
  logging_service    = "logging.googleapis.com/kubernetes"
  monitoring_service = "monitoring.googleapis.com/kubernetes"
  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = true
    master_ipv4_cidr_block  = var.master_ipv4_cidr_block
  }
  ip_allocation_policy {
    cluster_secondary_range_name = var.existing_subnetwork != "" ? "${var.existing_subnetwork}-secondary1" : google_compute_subnetwork.subnetwork[0].secondary_ip_range[0].range_name
  }

  node_pool {
    name               = "general-cpu-pool"
    initial_node_count = var.general_cpu_initial_node_count
    autoscaling {
      min_node_count = var.general_cpu_initial_node_count
      # If autoscaling is not enabled, then set max_node_count to min_node_count
      max_node_count = var.general_cpu_autoscaling_enabled ? var.general_cpu_max_node_count : var.general_cpu_initial_node_count
    }

    node_config {
      linux_node_config {
        sysctls = {
          "vm.max_map_count" = "262144"
        }
      }
      machine_type = var.general_cpu_instance_type
      disk_size_gb = var.general_cpu_disk_size
      oauth_scopes = [
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_only",
      ]
      image_type      = var.node_image_type
      preemptible     = var.general_cpu_preemptible_nodes
      disk_type       = var.general_cpu_disk_type
      local_ssd_count = var.general_cpu_local_ssd_count > 0 ? var.general_cpu_local_ssd_count : null
    }
  }

  timeouts {
    create = "20m"
  }
}

```

### Debug Output

│ Error: Unsupported block type
│ 
│   on cluster.tf line 62, in resource "google_container_node_pool" "general_cpu_pool":
│   62:     linux_node_config {
│ 
│ Blocks of type "linux_node_config" are not expected here.

### Expected Behavior

Allow linux_node_config within node_config
### Actual Behavior

Error: Blocks of type "linux_node_config" are not expected here

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#linux_node_config

**Comment by edwardmedia** [comment]
@songohannyc can you try something like below config?

```tf
data "google_container_engine_versions" "central1a" {
  location = "us-central1-a"
}

resource "google_container_cluster" "cluster" {
  name               = "%s"
  location           = "us-central1-a"
  initial_node_count = 1
  min_master_version = data.google_container_engine_versions.central1a.latest_master_version
}

resource "google_container_node_pool" "with_linux_node_config" {
  name               = "%s"
  location           = "us-central1-a"
  cluster            = google_container_cluster.cluster.name
  initial_node_count = 1
  node_config {
    image_type = "COS_CONTAINERD"
    linux_node_config {
      sysctls = {
        "net.core.netdev_max_backlog" = "%d"
        "net.core.rmem_max"           = 10000
        "net.core.wmem_default"       = 10000
        "net.core.wmem_max"           = 20000
        "net.core.optmem_max"         = 10000
        "net.core.somaxconn"          = %d
        "net.ipv4.tcp_rmem"           = "%s"
        "net.ipv4.tcp_wmem"           = "%s"
        "net.ipv4.tcp_tw_reuse"       = %d
      }
    }
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
```

**Comment by songohannyc** [comment]
@edwardmedia Same issue. Here is the debug log. https://gist.github.com/songohannyc/9fc165ef8493ec7d70346d5a7c7024d0

**Comment by songohannyc** [comment]
@edwardmedia hm...which version of provider.terraform-provider-google are you using. 

I ran 
`terraform init -upgrade

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "4.24.0"...
- Finding latest version of hashicorp/google-beta...
- Installing hashicorp/google v4.24.0...
- Installed hashicorp/google v4.24.0 (signed by HashiCorp)
- Installing hashicorp/google-beta v4.55.0...
- Installed hashicorp/google-beta v4.55.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.`

Could you advise how to install specific components? What are yours? Thank you for your help.

**Comment by songohannyc** [comment]
@edwardmedia Opps...I just realized that we pin hashicorp/google to version = "4.24.0". Version 4.55 is working!
Thank you for your help. I'll close the case.
