### ISSUE TITLE
Tainted project when using auto_create_network = false

### ISSUE THREAD

**Issue by ls-scanchon** [hashicorp/terraform-provider-google#13888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.55.0
+ provider registry.terraform.io/hashicorp/google-beta v4.55.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```
### Affected Resource(s)

* `google_project`

### Terraform Configuration Files

```tf
resource "google_project" "project" {
  name                = "some_project_name"
  project_id          = "some_project_name"
  billing_account     = "XXXXXX-YYYYYY-ZZZZZZ"
  auto_create_network = false
}
```

### Expected Behavior

The project should be created without the default network

### Actual Behavior

Terraform creates the project, then attempts to delete the network and crash with:

```
 Error: Error enabling the Compute Engine API required to delete the default network: failed to send enable services request: googleapi: Error 403: Service Usage API has not been used in project 297832857168 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=297832857168 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.Help",
│     "links": [
│       {
│         "description": "Google developers console API activation",
│         "url": "https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=297832857168"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/297832857168",
│       "service": "serviceusage.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ , accessNotConfigured
│
│   with google_project.project,
│   on project.tf line 1, in resource "google_project" "project":
│    1: resource "google_project" "project" {
│
```

And we end with a tainted project it attempts to recreate (which is impossible because projects are unique).

### Steps to Reproduce

1. `terraform apply` and observe failure
2. `terraform plan` and observe tainted project

**Comment by edwardmedia** [comment]
@ls-scanchon attempting to delete the network is the [logic](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_google_project.go#L186) implemented in the resource. What roles/permissions does the terraform runner has? I guess it may not have enough permissions to do that step.

**Comment by rileykarson** [comment]
@ls-scanchon: Is the project number in the error the project of the service account, or the project of the `google_project` resource?

**Comment by edwardmedia** [comment]
@ls-scanchon I just tested and it seems to be fine with me. With your config, does the project has a parent (org or folder)? 
To further investigate, mind sharing your debug log?

Reviewed the doc for [serviceusage.googleapis.com](https://cloud.google.com/service-usage/docs/reference/rest). Did you say you need to enable it at the project level in your manual test? And the runner is the owner of the organization, and the project does not have a parent?

**Comment by edwardmedia** [comment]
@ls-scanchon can you re-try to see if this issue is repeatable? Also See what happens if you add a parent in the config. Please share the debug log

**Comment by edwardmedia** [comment]
@ls-scanchon thanks for reporting this issue. Based on below doc, it appears to be an API bug. Could you please share your debug log for the execution of project creation?


https://cloud.google.com/service-usage/docs/enabled-service#default

**Comment by rileykarson** [comment]
Ah! I think I found it: L471 in that gist indicates that `X-Goog-User-Project` was sent as a header: https://gist.github.com/ls-scanchon/3c673cfacd7e202fac1fe3b54d3bb75b#file-debug_log-txt-L471. That corresponds to https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#user_project_override being set, whether in your configuration or an environment variable (`USER_PROJECT_OVERRIDE`).

GCP services can choose to check API enablement + request quotas against either the client (i.e. user) credentials, or against the target resource's project (i.e. resource). That's why I asked about the project number in https://github.com/hashicorp/terraform-provider-google/issues/13888#issuecomment-1457009136, this would also happen if your user account's project didn't have serviceusage enabled while using the default quota project for this API, the user one.

Can you try unsetting that environment variable or provider block setting? If other parts of the config rely on it, you may need to use an aliased provider.

---

> After some findings, maybe the problem is related to [stackoverflow.com/questions/68308103/gcp-project-creation-via-api-doesnt-enable-service-usage-api](https://stackoverflow.com/questions/68308103/gcp-project-creation-via-api-doesnt-enable-service-usage-api) ? (btw we already successfully created project in the past using this piece of code)

Whoops, yeah, no services are enabled by default on the target project when we make the project through Terraform.  Confirmed that by checking our test logs.
