### ISSUE TITLE
google_access_context_manager_service_perimeter_resource  takes only a string for projects instead of a list of projects

### ISSUE THREAD

**Issue by bouzid-kenna** [hashicorp/terraform-provider-google#13899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

resource "google_access_context_manager_service_perimeter_resource" "service-perimeter-resource" {
  for_each       = google_access_context_manager_service_perimeter.service_perimeter
  perimeter_name = google_access_context_manager_service_perimeter.service_perimeter[each.key].name
  resource       = var.projects_protected <------- This takes a string  
}

ServicePerimeterConfig   in resources takes a list of strings.

[](https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#VpcAccessibleServices)

### New or Affected Resource(s)

latest provider

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
The resource should be a list of strings 
### References

NA

**Comment by rileykarson** [comment]
This resource intentionally manages one project

> Allows configuring a single GCP resource that should be inside of a service perimeter. This resource is intended to be used in cases where it is not possible to compile a full list of projects to include in a google_access_context_manager_service_perimeter resource, to enable them to be added separately.

See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter for multiple projects.
