### ISSUE TITLE
Conflict between google_app_engine_application and google_firestore_database: database already exists

### ISSUE THREAD

**Issue by rwhogg** [hashicorp/terraform-provider-google#13891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 % terraform -v
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google-beta v4.55.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Affected Resource(s)

* google_app_engine_application
* google_firestore_database

### Terraform Configuration Files

```tf
variable "project_id" {
    type = string
}

data "google_project" "project" {
    project_id = var.project_id
}

resource google_app_engine_application "app" {
    project     = data.google_project.project.name
    location_id = "us-central"
}

resource google_firestore_database "database" {
    project     = data.google_project.project.name
    name        = "(default)"
    location_id = "nam5"
    type        = "FIRESTORE_NATIVE"

    depends_on = [google_app_engine_application.app]
}
```

### Expected Behavior

I think there are a few reasonable outcomes here:

1. Creating the plan should fail, with an error stating that the two resources (App Engine app and Database) should not be used together.
2. The database resource should recognize that the Firestore database already exists and gracefully add it to state. Subsequent changes to the database resource should gracefully update that state.
3. There should be some change to the App Engine resource that allows you to either suppress database creation altogether (assuming that even makes sense from an App Engine perspective) or to reference the database resource and thus know not to create.

### Actual Behavior

Database creation (from the google_firestore_database resource) fails, saying that the database already exists

### Steps to Reproduce

1. `terraform apply`

### Relevant Factoids

* The `depends_on` is not strictly necessary for the bug to appear, but does make it more consistently reproducible. If you omit it, the two resource creations will race.

**By contrast, using `depends_on` in the opposite direction (the app depends on the database rather than vice-versa) the creation, at least, seems to work.**

* Subsequent applies after the first will continue to attempt to create the database and will fail repeatedly in the same way.

* We also need to think about what should happen if someone already has one of these two resource types in their Terraform state and then imports one of the other type.

* Similarly, we need to consider what should happen if someone enters contradictory information into their Terraform configs, such as by specifying in the App Engine resource that you want a Firestore-native DB and specifying in the database resource that you want it to be in Datastore mode, or if they specify different regions.

**Comment by edwardmedia** [comment]
@rwhogg what exact error message did you get? Can you share your debug log?

Keep in mind **only one database is allowed per cloud project**. Do you have a database in a different region that has been already created?

**Comment by edwardmedia** [comment]
@rwhogg when you use google_app_engine_application to create CLOUD_FIRESTORE. I wonder if the api has already created the default database for you. Can you verify?

**Comment by rwhogg** [comment]
Yes, it already creates the default database for you

**Comment by edwardmedia** [comment]
In this case, users can't use the resource part of google_firestore_database. Instead, maybe try import it after google_app_engine_application was applied?

**Comment by rwhogg** [comment]
We've decided to just document that these two resources should not be used in combination instead.
