### ISSUE TITLE
startup-cpu-boost and cpu-throttling options for google_cloud_run_v2_service

### ISSUE THREAD

**Issue by sreid99** [hashicorp/terraform-provider-google#13908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Can't find how to use the Cloud Run options :

  startup-cpu-boost
  cpu-throttling

### Affected Resource(s)

* google_cloud_run_v2_service

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

```
containers {
  ...
  startup-cpu-boost = true
  cpu-throttling = true
  ...
}
```

or possibly in limits {}

```
containers {
  ...
  limits {
    ...
    startup-cpu-boost = true
    cpu-throttling = true
    ...
  }
}
```

### References

* might work using this, with beta provider #13302
* b/272785021

**Comment by sreid99** [comment]
Related to #13748, which mentions another setting : sessionAffinity

Found cpu_idle is already available under resources, and seems to be another name for cpu-throttling.

**Comment by steren** [comment]
We are starting the work to add startup CPU Boost to V2 API, which should appear in the terraform v2 resource just after.

Session affinity should be rolling out very soon.
