### ISSUE TITLE
Add ability to configure an existing bucket. e.g. Cloudbuild bucket.

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#13911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In many cases a bucket already exists, such as the bucket that Cloudbuild creates when you enable the API, but Terraform will error if you try to configure settings on this bucket since it already exists.  I believe that if the google_storage_bucket  had a setting to tell it not to create the bucket then it would be possible to configure bucket settings, such as lifecycle policy, using the resource.

### New or Affected Resource(s)

google_storage_bucket

### Potential Terraform Configuration

create_bucket  = bool

Note Google Cloud customers who are working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform/issues/26364, the core feature that would allow this. We'd prefer not to implement this in the provider.
