### ISSUE TITLE
Improve support for autoscaling_policy in google_compute_node_group

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#13928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

From internal discussion:

> The ask here is basically to alter [google_compute_node_group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_node_group) to:
> 
> 1. Allow specifying either a size or an autoscaling policy at create time. This isn't exactly feasible, because at create time, [`size` is an alias for `initial_size`](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/pre_create/compute_node_group_url_replace.go.erb) which is a required field.
> 2. (Optional) Support increasing the `size` attribute via calling the [addNodes](https://cloud.google.com/compute/docs/reference/rest/v1/nodeGroups/addNodes) endpoint. This is likely possible but not easy, because it's non-standard.
> 3. (Optional) Support decreasing the `size` attribute by calling the [deleteNodes](https://cloud.google.com/compute/docs/reference/rest/v1/nodeGroups/deleteNodes) endpoints. This is likely not feasible, because it would require selecting which specific nodes should be deleted.
> 
> Probably long-term the best fix here would be to make the `size` attribute output-only and require users to set `initial_size`, so that `size` has the same meaning for terraform as for the API. However, that would be a breaking change.

### New or Affected Resource(s)

* google_compute_node_group

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/195305249
*

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/9044
