### ISSUE TITLE
google_cloud_run_v2_service: `terraform apply` fails with `Requested entity already exists` when trying to reduce `max_instance_count`.

### ISSUE THREAD

**Issue by czka** [hashicorp/terraform-provider-google#13921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
terraform -v
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.56.0
```

### Affected Resource(s)

* `google_cloud_run_v2_service`

### Terraform Configuration Files

```tf
resource "google_cloud_run_v2_service" "some_cloud_run" {
  name         = "some_cloud_run"
  location     = "<some region>"
  ingress      = "INGRESS_TRAFFIC_ALL"
  launch_stage = "BETA"

  template {
    revision = "one"

    containers {
      image = "<some image>"
    }

    execution_environment = "EXECUTION_ENVIRONMENT_GEN2"

    scaling {
      min_instance_count = 1
      max_instance_count = var.max_instance_count
    }
  }

  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }
}
```

### Expected Behavior

`max_instance_count` should have been reduced from 2 to 1.

### Actual Behavior

A `Requested entity already exists` error occured.

### Steps to Reproduce

1. Run `terraform apply -var max_instance_count=2` - applies fine.
2. Now try reducing the max instance count: `terraform apply -var max_instance_count=1` - bails out with an error like:
```
google_cloud_run_v2_service.some_cloud_run: Modifying... [id=projects/<some project>/locations/<some region>/services/some_cloud_run]
╷
│ Error: Error updating Service "projects/<some project>/locations/<some region>/services/some_cloud_run": googleapi: Error 409: Requested entity already exists
│ 
│   with google_cloud_run_v2_service.some_cloud_run,
│   on cloud_run.tf line 1, in resource "some_cloud_run" "some_cloud_run":
│    1: resource "google_cloud_run_v2_service" "some_cloud_run" {
│ 
```

**Comment by edwardmedia** [comment]
@czka With below config, it seems to be fine. I am not able to hit the error. Can you share your debug log?

```tf
resource "google_cloud_run_v2_service" "default" {
  name     = "issue13921"
  location = "us-central1"
  ingress = "INGRESS_TRAFFIC_ALL"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }

    scaling {
      min_instance_count = 1
      max_instance_count = 1  # (2->1)
    }
  }
}
```

**Comment by czka** [comment]
@edwardmedia I'll try again tomorrow CET.

**Comment by czka** [comment]
@edwardmedia Here's the [`TF_LOG=DEBUG terraform apply` output](https://gist.github.com/czka/1e2a7dd1d9ab0972b3a95f6b2514c99c) for my real-life use case which I tried to distill into the example TF code I provided in this bug report. Please let me know if this helps.

**Comment by czka** [comment]
I understand better now: Whenever any Cloud Run template attribute changes, a new revision needs to be deployed. But I've hardcoded the revision. In my real-life use case I've hardcoded it not as hard as in my example `revision = "one"` above, but still it only changes under certain circumstances outside the Cloud Run configuration itself. I need to re-think this. My bug report is probably bogus.

**Comment by edwardmedia** [comment]
@czka please verify your use case, and close the issue if you think the resource works be design. Thanks

**Comment by czka** [comment]
I'm closing it. Will submit a new one if needed.
