### ISSUE TITLE
google_storage_transfer_job.aws_s3_data_source block is missing "path" parameter

### ISSUE THREAD

**Issue by smic-datalabs-jdcastro** [hashicorp/terraform-provider-google#13936]
### Description

In GCP Data Transfer Console, there is an available option to specify the "path" of the S3 Bucket defined as data source.

### New or Affected Resource(s)
*google_storage_transfer_job

### Potential Terraform Configuration

```
resource "google_storage_transfer_job" "sample_data_transfer" {
  description = "sample description"

  transfer_spec {
    object_conditions {
      ...
      ...
    }
    aws_s3_data_source {
      bucket_name = "bucket_name"
      aws_access_key {
        access_key_id     = ****
        secret_access_key = ****
      }
      path = "<path_in_bucket>" <--- include this
    }
  }
```

**Comment by trodge** [comment]
b/280345991

**Comment by kiwamizamurai** [comment]
similar 
https://github.com/hashicorp/terraform-provider-google/issues/12997

**Comment by kiwamizamurai** [comment]
@dilipped yes. this one can be closed

**Comment by dilipped** [comment]
@trodge , can you please close this one? I don't have permissions to do it.

**Comment by roaks3** [comment]
Yep, duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12997, fixed by https://github.com/hashicorp/terraform-provider-google/pull/14610
