### ISSUE TITLE
google_container_cluster has conflicting options that shouldn't conflict

### ISSUE THREAD

**Issue by cgetzen** [hashicorp/terraform-provider-google#13947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
# snippet
  ip_allocation_policy {
    cluster_secondary_range_name = "some-name"
    services_ipv4_cidr_block     = "192.168.0.0/20"
  }
```

### Debug Output

https://gist.github.com/cgetzen/deaddea45f41b6161a7615758aee6691

### Expected Behavior

These resources should not conflict. It should be possible to use a named range for pods but not services, and vice versa.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@cgetzen where did you see the Expected Behavior? Could you share the documents?

```
These resources should not conflict. It should be possible to use a named range for pods but not services, and vice versa.
```

**Comment by cgetzen** [comment]
My mistake - I thought GCP allowed this.
