### ISSUE TITLE
public_access_prevention documentation is inaccurate

### ISSUE THREAD

**Issue by enahsor** [hashicorp/terraform-provider-google#13954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```sh
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.41.0
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1
```

### Affected Resource(s)
`google_storage_bucket`

### Terraform Configuration Files
```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.41.0"
    }
  }
}

resource "google_storage_bucket" "test" {
  name = "test"
  location = "US"
  force_destroy = true

  public_access_prevention = "enforced" 
}
```

### Expected Behavior
A storage bucket with details provided should be created

### Actual Behavior
Terraform throws an error:
```
│ Error: Unsupported argument
│ 
│   on storage.tf line 16, in resource "google_storage_bucket" "test":
│   16:   public_access_prevention = "enforced" 
│ 
│ An argument named "public_access_prevention" is not expected here.
```
This example is similar to what is shown in the docs. The documentation does not state that  in order to use this property, your provider must be the `beta` version of the google provider ie.

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google-beta"
      version = "4.41.0"
    }
  }
}
```
or 

```tf
resource "google_storage_bucket" "history" {
  provider = google-beta
  project = var.project
  name = "test
  location = "US"
  force_destroy = true

  public_access_prevention = "enforced"  
}
```
would work
 
### Steps to Reproduce

1. `terraform apply`

### References

* [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket)

**Comment by edwardmedia** [comment]
@enahsor this field was introduced in v4.42.0. (yours is v4.41.0) Can you try any versions after that? 

https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.42.0

**Comment by slevenick** [comment]
Closing as this does exist in GA as of 4.42.0
