### ISSUE TITLE
Add network-firewall-policy-enforcement-order to google_compute_network resource

### ISSUE THREAD

**Issue by jenshonkan84** [hashicorp/terraform-provider-google#13952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add support for network-firewall-policy-enforcement-order in the google_compute_network resource

### New or Affected Resource(s)

* google_compute_network

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_network" "vpc_network" {
  project                 = "my-project-name"
  name                    = "vpc-network"
  auto_create_subnetworks = true
  mtu                     = 1460
  network_firewall_policy_enforcement_order = "BEFORE_CLASSIC_FIREWALL"
}
```

### References

https://cloud.google.com/compute/docs/reference/rest/v1/networks/patch

**Comment by ADN2435** [comment]
https://www.tiktok.com/coin?kbk.502=ar
