### ISSUE TITLE
Stateful internal IP for instance group

### ISSUE THREAD

**Issue by radekwroblewski** [hashicorp/terraform-provider-google#13961]
Hello. I'm trying to create a stateful MIG by adding stateful_internal_ip to it. As described in the docs https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#nested_stateful_internal_ip
I'm using beta provider.

```
resource "google_compute_instance_group_manager" "group" {
  base_instance_name = local.instance_identifier
  description        = "managed instance group for ${var.app_name}"
  name               = "${local.instance_identifier}-${var.business_unit}-${random_string.group_id.result}-group"
  target_size        = var.number_of_instances
  zone               = "${var.regionality}-${var.gcp_zone}"
  provider           = google-beta

  version {
    instance_template = google_compute_instance_template.instance_template.self_link
  }

  stateful_internal_ip {
    network_interface_name = "test-ip"
    delete_rule = "NEVER"
  }

}
```
Unfortunatelly this gives me an error on terraform-plan:
``               Error: Unsupported block type, 
                on target_repo/app.tf line 104, in resource \\"google_compute_instance_group_manager\\" \\"group\\":, 
                104:   stateful_internal_ip {, 
                Blocks of type \\"stateful_internal_ip\\" are not expected here. 
``
I have found a previous bug regarding that manner which is already closed: 
https://github.com/hashicorp/terraform-provider-google/issues/13570

I also tried adding other "beta" options for compute_instance_group_manager - stateful_external_ip or all_instances_config, they both produce the similar result.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_instance_group_manager

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
@radekwroblewski what version of the provider are you using? Can you share your debug log?

**Comment by radekwroblewski** [comment]
@edwardmedia Hi, I'm using provider versions 4.0.0. Here is my debug log (company info obfuscated):

[terraform-plan.log](https://github.com/hashicorp/terraform-provider-google/files/10955403/terraform-plan.log)

**Comment by radekwroblewski** [comment]
I've played around with google-beta provider version. Since 4.48.0 the error is different:
`Error: Unsupported argument

  on ../app.tf line 105, in resource "google_compute_instance_group_manager" "gr
oup":
 105:     network_interface_name = "nic0"

An argument named "network_interface_name" is not expected here.
`
Debug log here:
[terraform-plan.log](https://github.com/hashicorp/terraform-provider-google/files/10957111/terraform-plan.log)

**Comment by edwardmedia** [comment]
@radekwroblewski I am able to make a plan like below. Tried the latest version of google-beta

```tf
  # google_compute_instance_group_manager.appserver will be created
  + resource "google_compute_instance_group_manager" "appserver" {
      + base_instance_name             = "app"
      + fingerprint                    = (known after apply)
      + id                             = (known after apply)
      + instance_group                 = (known after apply)
      + list_managed_instances_results = "PAGELESS"
      + name                           = "issue13961"
      + operation                      = (known after apply)
      + project                        = (known after apply)
      + self_link                      = (known after apply)
      + status                         = (known after apply)
      + target_size                    = 5
      + wait_for_instances             = false
      + wait_for_instances_status      = "STABLE"
      + zone                           = "us-central1-a"

      + instance_lifecycle_policy {
          + force_update_on_repair = (known after apply)
        }

      + stateful_internal_ip {.      <-------here
          + delete_rule = "NEVER"
        }

      + update_policy {
          + max_surge_fixed                = (known after apply)
          + max_surge_percent              = (known after apply)
          + max_unavailable_fixed          = (known after apply)
          + max_unavailable_percent        = (known after apply)
          + min_ready_sec                  = (known after apply)
          + minimal_action                 = (known after apply)
          + most_disruptive_allowed_action = (known after apply)
          + replacement_method             = (known after apply)
          + type                           = (known after apply)
        }

      + version {
          + instance_template = (known after apply)
          + name              = "appserver"
        }
    }
```

**Comment by edwardmedia** [comment]
@radekwroblewski it looks like there is a typo for the field (network_interface_name ---> interface_name). Can you try using interface_name instead? I am going to update the doc accordingly. 

https://github.com/hao-nan-li/magic-modules/blob/af0f7f570d1e915116e102a72514e06f4bbf7644/mmv1/third_party/terraform/resources/resource_compute_instance_group_manager.go.erb#L336

**Comment by hao-nan-li** [comment]
I found https://github.com/GoogleCloudPlatform/magic-modules/pull/7399 which fixes the doc. 
As mentioned above, change the field to `interface_name` should solve the problem.
