### ISSUE TITLE
Add support for advanced network DDoS protection in google_compute_security_policy

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#13978]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Allow value `CLOUD_ARMOR_NETWORK` for variable `type`. Add another variable `network_ddos_protection` which can be `STANDARD` or `ADVANCED`.
### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "policy" {
  name = "my-policy"
  type = "CLOUD_ARMOR_NETWORK"
  network_ddos_protection = "ADVANCED"

}
```

### References

* [Advanced network DDoS protection](https://cloud.google.com/armor/docs/advanced-network-ddos#activate_advanced_network_ddos_protection)

**Comment by imrannayer** [comment]
[Issue 24](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/issues/24) is blocked due to this.

**Comment by melinath** [comment]
looks like this was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7979
