### ISSUE TITLE
Add Google Cloud project as destination in google_logging_project_sink

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#13972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_logging_project_sink

### Potential Terraform Configuration

```tf
resource "google_logging_project_sink" "my-sink" {
  name = "my-project-log-sink"

  # route log entries to another Google Cloud project
  destination = "logging.googleapis.com/projects/my-project-id"
}
```

### References

* [Route logs to supported destinations](https://cloud.google.com/logging/docs/export/configure_export_v2#destination-paths)

**Comment by melinath** [comment]
It looks like we don't do any validation on the `destination` field, so this should already work fine as long as it's supported by the API - please reopen (or open a new issue) if there's something I'm missing!
