### ISSUE TITLE
GCP - External resource attribute not supported in TF module "terraform-google-modules/vpc-service-controls/google//modules/regular_service_perimeter"

### ISSUE THREAD

**Issue by amar2k05** [hashicorp/terraform-provider-google#13977]
Hi,
We have a requirement to transfer files between **GCS (GCP) & S3 (AWS)** and for the same we are using Storage Transfer Service in GCP.
As the project is protected by VPC SC Perimeter with storage as one of the restricted service within the perimeter, we are trying to create an egress rule on the perimeter and trying to specify **"external_resources"** but this is not supported in the terraform module **"terraform-google-modules/vpc-service-controls/google//modules/regular_service_perimeter"**, is there any plan to enhance this module to accept "external_resources" in ingress/egress rules?

Note that currently it's supported in Terraform resource **"google_access_context_manager_service_perimeter"**

Thanks,
Amarnath.

**Comment by melinath** [comment]
I believe this should be raised in https://github.com/terraform-google-modules/terraform-google-vpc-service-controls
