### ISSUE TITLE
fields[] attribute in schema would cause the table to be re-created even without any change

### ISSUE THREAD

**Issue by kickingfish** [hashicorp/terraform-provider-google#13988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.56.0

### Affected Resource(s)
google_bigquery_table

* google_XXXXX

### Terraform Configuration Files
this is not applicable.  I attached the terraform code I am running with the sample schema.

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior
Terraform should not re-create the table when there is no change on the schema

The terraform will destroy the table and re-create it even there's no changes on the schema. This should not be done because data will be lost.

### Actual Behavior
Terraform Apply would say no changes detected

Terraform Apply drop and re-create the table.  Thus, losing the data.

### Steps to Reproduce
run the terraform files I attached.

1. `terraform apply`

### Important Factoids

[terraform-files.zip](https://github.com/hashicorp/terraform-provider-google/files/10969908/terraform-files.zip)

### References

* #0000

**Comment by edwardmedia** [comment]
@kickingfish to avoid download files,  can you post the config over here directly? Or share the link to https://gist.github.com/?

**Comment by kickingfish** [comment]
> @kickingfish to avoid downloading files, can you post the config over here directly? Or share the link to https://gist.github.com/?

would you be able to delete the files I uploaded?

**Comment by kickingfish** [comment]
actually, you can just use the schema.json to create a table and you'll see the issue I am referrign to.
The table will be created and the succeeding Apply will re-create the table.

**Comment by edwardmedia** [comment]
@kickingfish regarding [this](https://github.com/hashicorp/terraform-provider-google/issues/13988#issuecomment-1468264693), no I don't delete. You may. But you should always remove secrets from the data that share to the public

**Comment by edwardmedia** [comment]
@kickingfish sorry I don't know how to delete content at gist. Yes, make sure no any secrets before you post

**Comment by kickingfish** [comment]
There's new development.  I guess I need to close this for now.  I will open a new issue if we think we need to pursue this.  thanks for taking on this request.

**Comment by kickingfish** [comment]
I'll open new one once we see it is needed.
