### ISSUE TITLE
google_service_account_iam_member - service_account_id not matching regex

### ISSUE THREAD

**Issue by iskarconsulting** [hashicorp/terraform-provider-google#13987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.9

### Affected Resource(s)

google_service_account_iam_member

### Terraform Configuration Files

```tf
data "google_compute_default_service_account" "iac_project" {
  project = module.bootstrap.seed_project_id
}

resource "google_service_account_iam_member" "iac-seed-compute-sa" {
  service_account_id = data.google_compute_default_service_account.iac_project.email
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:${module.bootstrap.terraform_sa_email}"
}
```

### Debug Output

https://gist.github.com/iskarconsulting/64617299ad03ca2a923a915adf746648

### Expected Behavior

Expected resource to complete without error.

Using BASH, the service account matches the given regex in the error message:

```BASH
SA_VALUE='548424155928-compute@developer.gserviceaccount.com'

SA_REGEX='projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)|-)/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@[a-z]+.gserviceaccount.com$|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)'

[[ $SA_VALUE=~$SA_REGEX ]]

echo $? # Returns 0 (expected)
```

### Actual Behavior

```BASH
│ Error: "service_account_id" ("548424155928-compute@developer.gserviceaccount.com") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)|-)/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@[a-z]+.gserviceaccount.com$|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)" 
│
│   with google_service_account_iam_member.iac-seed-compute-sa,
│   on main.tf line 62, in resource "google_service_account_iam_member" "iac-seed-compute-sa":
│   62:   service_account_id = data.google_compute_default_service_account.iac_project.email
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@iskarconsulting what do you see if you change email to name for `service_account_id`?

```tf
resource "google_service_account_iam_member" "iac-seed-compute-sa" {
  service_account_id = data.google_compute_default_service_account.iac_project.email<-----
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:${module.bootstrap.terraform_sa_email}"
}
```

**Comment by iskarconsulting** [comment]
@edwardmedia thank you!

There isn't a `service_account_id` attribute exported by the `google_compute_default_service_account` data source. However, there is a `name` attribute which worked. The attribute `id` also worked although this isn't documented.

The error message I received is a bit misleading.

Your help is much appreciated.

**Comment by edwardmedia** [comment]
@iskarconsulting welcome. Closing the issue now. Thanks
