### ISSUE TITLE
Provider bug with deploying API gateway

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/terraform-provider-google#13984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.47.0
+ provider registry.terraform.io/hashicorp/google-beta v4.47.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

google_api_gateway_api

### Terraform Configuration Files

```tf
resource "google_api_gateway_api" "my_api" {
  provider = google-beta
  api_id   = "${var.developer}-${var.environment}-my-api-${var.random_id}"
  project  = var.project
}
```

### Debug Output

```bash

module.api_gateway.google_api_gateway_api.my_api: Still creating... [1m30s elapsed]
module.api_gateway.google_api_gateway_api.my_api: Still creating... [1m40s elapsed]
module.api_gateway.google_api_gateway_api.my_api: Creation complete after 1m44s [id=projects/my_project/locations/global/apis/my-api]

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.api_gateway.google_api_gateway_api_config.seeder_api_gw_config to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google-beta" produced an invalid new value
│ for .openapi_documents[0].document[0].contents: was
│ cty.StringVal("CiMgb3Blb....WRldiIKICAgICAgCg=="),
│ but now
│ cty.StringVal("CiMgb3BlbmFwaTItcnV....CAgICAgCg==").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)
```

### Expected Behavior

API gateway should have deployed

### Actual Behavior

Terraform errors out with the error above. Applying configuration the second time deploys it without a problem

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

API config file is generated dynamically because I inject urls of services running in cloud run

### References

* #0000

**Comment by edwardmedia** [comment]
@periwinkleFTW how did you get the idea that this issue was from `google_api_gateway_api`?

What is this field? `.openapi_documents[0].document[0].contents`? 

Because you use the module, it is hard to tell what went wrong. Are you able to repro the issue at the resource level? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/api_gateway_api#example-usage---apigateway-api-basic

**Comment by periwinkleFTW** [comment]
@edwardmedia this api_gateway behaviour is very flaky. I forgot to check the contents =( though this error seems to have gone away after upgrading terraform to 1.4.1.
I now have issues with alreadyExists for some of my resources, but that's another issue altogether

**Comment by edwardmedia** [comment]
@periwinkleFTW so the mentioned issue is resolved `after upgrading terraform to 1.4.1`? Should this be closed accordingly?

For the new `alreadyExists` issue, mind creating a new issue with the details?

**Comment by periwinkleFTW** [comment]
@edwardmedia you can close this issue. 

I will create a new issue for the alreadyExists error

**Comment by edwardmedia** [comment]
@periwinkleFTW close this now as you suggested.
