### ISSUE TITLE
Add auto_sleep to google_workstations_workstation_config

### ISSUE THREAD

**Issue by mcinquin** [hashicorp/terraform-provider-google#13980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The  **google_workstations_workstation_config** resource is not complete. We can't define the **auto-sleep** value. This is a problem because it is one of the main features of Cloud Workstations.

The idea is to add an `auto_sleep` argument. The value defined for this argument will be in seconds with a default value of 7200.

### New or Affected Resource(s)

* google_workstations_workstation_config

### Potential Terraform Configuration

```tf
resource "google_workstations_workstation_config" "default" {
   ...

  host {
    gce_instance {
   ...
      auto_sleep  = 5400
    }
  }
}

```

### References

* https://cloud.google.com/workstations/docs/create-configuration#create_a_machine_configuration
* https://github.com/hashicorp/terraform-provider-google/issues/12763

b/299600705

**Comment by melinath** [comment]
Although there's a PR that says it fixes this issue it doesn't actually seem to as far as I can tell.

**Comment by esu** [comment]
Hi @melinath, the auto-sleep feature in the UI uses the field named `idle_timeout` in the API, so it's resolved by the PRs above.

**Comment by melinath** [comment]
Thanks @esu - in that case, marking resolved!
