### ISSUE TITLE
Table is drop and re-created 

### ISSUE THREAD

**Issue by kickingfish** [hashicorp/terraform-provider-google#13990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.9 on windows_amd64

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files
code provided below

```tf
resource "google_bigquery_dataset" "dset" {
  dataset_id                  = "foo2"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "US"
  default_table_expiration_ms = 3600000
  project = "your project here"  
  delete_contents_on_destroy=true

  labels = {
    env = "default"
  }
}

resource "google_bigquery_table" "tbl" {
  dataset_id = google_bigquery_dataset.dset.dataset_id
  table_id   = "field"
  project = "your project here"  
   deletion_protection=false
  schema =   <<EOF
[
  {
   "name": "col1",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": null,
   "fields": []
  },

  {
   "name": "col2",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": null,
   "fields": []
  }
 ]
EOF
  time_partitioning {
    type = "DAY"
  }
  labels = {
    env = "default"
  }
}
```

### Debug Output
not applicable.  Just running the code I provided will replicate the issue.

### Panic Output
not applicable

### Expected Behavior
the code should not re-create the table when apply is rerun and there's no change on the schema

the table will not be recreated when there's no change on the schema.
### Actual Behavior
it is dropping and re-creating the table

it is dropping and re-creating the table

### Steps to Reproduce
run the terraform apply once on this code that I provided.

Running these code will reproduce the issue...
1. `terraform apply`
resource "google_bigquery_dataset" "dset" {
  dataset_id                  = "foo2"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "US"
  default_table_expiration_ms = 3600000
  project = "your project here"  
  delete_contents_on_destroy=true

  labels = {
    env = "default"
  }
}

resource "google_bigquery_table" "tbl" {
  dataset_id = google_bigquery_dataset.dset.dataset_id
  table_id   = "field"
  project = "your project here"  
   deletion_protection=false
  schema =   <<EOF
[
  {
   "name": "col1",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": null,
   "fields": []
  },

  {
   "name": "col2",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": null,
   "fields": []
  }
 ]
EOF
  time_partitioning {
    type = "DAY"
  }
  labels = {
    env = "default"
  }
}

### References

* #0000

**Comment by edwardmedia** [comment]
@kickingfish I can repro what you see. But I think there is a limitation in using JSON schema which you can see in the [note](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#schema) Once I updated it with below schema, it seems fine. I guess your sample schema is not supported by api?

```ts
[
  {
   "name": "col1",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": "STRING"
  },

  {
   "name": "col2",
   "mode": "NULLABLE",
   "type": "STRING",
   "description": "STRING"

  }
 ]
```

**Comment by kickingfish** [comment]
> @kickingfish I can repro what you see. But I think there is a limitation in using JSON schema which you can see in the [note](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#schema) Once I updated it with below schema, it seems fine. I guess your sample schema is not supported by api?
> 
> ```ts
> [
>   {
>    "name": "col1",
>    "mode": "NULLABLE",
>    "type": "STRING",
>    "description": "STRING"
>   },
> 
>   {
>    "name": "col2",
>    "mode": "NULLABLE",
>    "type": "STRING",
>    "description": "STRING"
> 
>   }
>  ]
> ```

You are correct in this updated schema.  Our app team is using the schema as is after copying as json.  The same schema will load successfully when using in 'bq mk' commandline.  We are hoping that terraform will behave the same way.  It should say the table exist and it should not re-create it.

**Comment by edwardmedia** [comment]
@kickingfish glad you have found a fix. Closing this accordingly

**Comment by kickingfish** [comment]
hi edward, May I know this won't be fixed?  We run the same schema using bq mk command but it works as expected.  It is not saying that the table exist,  We expect to do the same or it won't drop and re-create the table.
