### ISSUE TITLE
Terraform recreates BQ Dataset access resource every time there are changes in the plan

### ISSUE THREAD

**Issue by ensonic** [hashicorp/terraform-provider-google#14001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/google v3.46.0
+ provider registry.terraform.io/hashicorp/google-beta v4.10.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Affected Resource(s)

* google_bigquery_dataset_access

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "xxx_dashboard_metrics_dataset" {
  project    = "xxx"
  dataset_id = "dashboard_metrics"
}```

### Debug Output

```
 # google_bigquery_dataset.intrinsic-analytics-dashboard-metrics-dataset will be updated in-place
  ~ resource "google_bigquery_dataset" "xxx_dashboard_metrics_dataset" {
        creation_time                   = 1678464255262
        dataset_id                      = "dashboard_metrics"
      - default_partition_expiration_ms = 5184000000 -> null
      - default_table_expiration_ms     = 5184000000 -> null
        delete_contents_on_destroy      = false
        etag                            = "FPtVbLj8kfNH0tE2fiWufw=="
        ...
    }
```
When enabling TF_DEBUG it run for ages. I'll try to target the resource and add the log if I am able to get one.

### Expected Behavior

Don't change the resource.

### Actual Behavior

Proposes a change to a resource, which hasn't changed.

### Steps to Reproduce

1. run `terraform apply` multiple times without making changes to the tf files nor changing the cloud resource

### References

](https://stackoverflow.com/questions/74277791/terraform-recreates-bq-dataset-access-resource-every-time-there-are-changes-in-t)

* #0000

<!---
Note Google Cloud customers who are working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team
--->

**Comment by edwardmedia** [comment]
@ensonic using below config, I am not able to repro the issue. Can you share the config that I can use to repro the issue?

```tf
resource "google_bigquery_dataset" "dataset" {
  dataset_id                  = "issue14001"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "US"
  default_table_expiration_ms = 3600000
  default_partition_expiration_ms=5184000000
}
```

**Comment by ensonic** [comment]
Very odd, now that I filed the bug, it is not happening anymore.
