### ISSUE TITLE
Error 400: Precondition check failed on google_cloud_run_v2_job when launch_stage is not BETA

### ISSUE THREAD

**Issue by nadavavv** [hashicorp/terraform-provider-google#14010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.2.4
Provider version: 4.48.0

### Affected Resource(s)

google_cloud_run_v2_job

### Debug Output

Error: Error creating Job: googleapi: Error 400: Precondition check failed.

### Expected Behavior

The resource should be created.
The resource is created only when launch_stage variable is set to "BETA".

### Actual Behavior

Resource failed to create, plan works as expected but apply failed.

### Steps to Reproduce

1. Leave launch_stage variable with default value or set it to "GA".

2. `terraform apply`

**Comment by edwardmedia** [comment]
@nadavavv do you have the config that I can use to repro the issue?

**Comment by nadavavv** [comment]
> @nadavavv do you have the config that I can use to repro the issue?

`resource "google_cloud_run_v2_job" "cloud_run_job" {
  name         = local.cron_job_name
  location     = var.gcp_region
  launch_stage = "GA"

  template {
    template {
      containers {
        image   = local.image_name
        command = var.app_command
        resources {
          limits = {
            cpu    = var.app_data.resources.resources_cpu_min_and_max
            memory = var.app_data.resources.resources_memory_min_and_max
          }
        }
        dynamic "env" {
          for_each = var.app_env_vars.simple
          content {
            name  = env.value.name
            value = env.value.value
          }
        }
        dynamic "env" {
          for_each = var.app_env_vars.secret_key_ref

          content {
            name = env.value.name
            value_from {
              secret_key_ref {
                name = env.value.value_from.secret_key_ref.name
                key  = env.value.value_from.secret_key_ref.key
              }
            }
          }
        }
      }
      service_account = local.service_account_email
      vpc_access {
        connector = var.vpc_connector_name
        egress    = "ALL_TRAFFIC"
      }
      encryption_key = module.cmek_managed_services.key_path
      max_retries    = var.cloud_run_max_retries
    }
  }
  labels = local.job_labels
}`

**Comment by rileykarson** [comment]
This is working as expected, see https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services:

```
Set the launch stage to a preview stage on input to allow use of preview features in that stage.
```

@edwardmedia: We may want to include that text in our documentation as well, it's not currently clear that specifying a lower launch stage than the features you're using will result in this error based on our docs alone.

**Comment by edwardmedia** [comment]
@rileykarson got it.

**Comment by edwardmedia** [comment]
b/279068442
