### ISSUE TITLE
Docs: Add hidden user agent extension env var information to terraform website

### ISSUE THREAD

**Issue by musha68k** [hashicorp/terraform-provider-google#14011]
# Background

# What kind of contribution is this issue about?

* MMv1 third party / terraform website docs update

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/7470

# Details

* See undocumented environment variable check for `GOOGLE_TERRAFORM_USER_AGENT_EXTENSION` in the
[`providerConfigure`](https://github.com/hashicorp/terraform-provider-google/blob/c0c2e42de049c5a0c37ba460626ac7ae113c1f0e/google/provider.go#L1608) function.

**Comment by SarahFrench** [comment]
Closing as the PR was merged
