### ISSUE TITLE
google_sql_user does not create IAM SA accounts as documented

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#14019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.2

### Affected Resource(s)

google_sql_user

### Terraform Configuration Files

If you try to use the example in the documentation to create a SA IAM user in a CloudSQL instance (tested with Postgres) you get error:
Error: Error, failed to insert user userid@projectname.iam.gserviceaccount.com into instance instancename: googleapi: Error 400: Invalid request: Database username for Cloud IAM service account should be created without ".gserviceaccount.com" suffix., invalid

The documentation doesn't call this out, and it would be trivial for the provider to handle it, and type should default to the correct type.    If there is no plan to fix the provider so it handles this then the documention needs to be updated to call out an example of how to configure an IAM SA in a CloudSQL DB.

Example of what doesn't work:

```
resource "google_sql_user" "iam_user" {
  for_each = local.iam_users_set
  name     = each.key
  project  = var.project_id
  instance = var.database_instance_name
  type = endswith(each.key, ".gserviceaccount.com") ? (
    "CLOUD_IAM_SERVICE_ACCOUNT"
    ) : (
    "CLOUD_IAM_USER"
  )
}
```

Example that does work:

```tf
resource "google_sql_user" "iam_user" {
  for_each = local.iam_users_set
  name     = endswith(each.key, ".gserviceaccount.com") ? trimsuffix(each.key,".gserviceaccount.com") : each.key
  project  = var.project_id
  instance = var.database_instance_name
  type = endswith(each.key, ".gserviceaccount.com") ? (
    "CLOUD_IAM_SERVICE_ACCOUNT"
    ) : (
    "CLOUD_IAM_USER"
  )
}
```

### Debug Output
Error: Error, failed to insert user userid@projectname.iam.gserviceaccount.com into instance instancename: googleapi: Error 400: Invalid request: Database username for Cloud IAM service account should be created without ".gserviceaccount.com" suffix., invalid

### Expected Behavior
Provider should trim .gserviceaccount.com from the end of the name or documentation should call out that this string must be trimmed per the example abive.

### Actual Behavior
Provider does not trim  .gserviceaccount.com from the end of the name and a 400 error is returned

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@philip-harvey thanks for the suggestion, but I think adding a rule here might not be good idea. Below is the source api that the resource is based on. I don't see anything is called out for the field `name`. Adding a rule could introduce unintended bugs. What do you think?

https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users

**Comment by philip-harvey** [comment]
I understand there may be hesitantly to add this truncation to the provider, but I do think it would be the best option from a usability perspective.  If the decision is to continue requiring a truncated userID then I think this should be added to the Terraform documentation as an example, similar to the above.

e.g.
```
resource "google_service_account" "service_account" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_sql_user" "iam_user" {
  name     = trimsuffix(google_service_account.service_account, ".gserviceaccount.com")
  instance = google_sql_database_instance.main.name
  type = "CLOUD_IAM_SERVICE_ACCOUNT"
}
```

**Comment by edwardmedia** [comment]
@roaks3 what do you think?

**Comment by roaks3** [comment]
So I'm seeing `testGoogleSqlUser_iamUser`, which doesn't seem to have an issue passing the service account email as the SQL user name, but that test uses MySQL. I'm wondering if this is a Postgres-specific issue, or perhaps we just need another example in the docs to demonstrate the expected config.

**Comment by philip-harvey** [comment]
It may be Postgres specific, there seems be zero documentation on this from the Google API side though.  I only tested with Postgres and it doesn't work if you pass the full email address

**Comment by philip-harvey** [comment]
Found why it works for MySQL, per the docs:
https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#creating-a-database-user
Note: When MySQL stores the username, it truncates the @ and the domain name from the user's email address. For example, test-user@gmail.com becomes test-user). For this reason, you may not add two IAM users with the same username but different domain names to the same Cloud SQL instance.

So the test it's failing for MySQL because the API does the truncation for you under the hood, but for Postgres the full email is the user ID for IAM users.  

The documentation for CloudSQL for IAM for Postgres is wrong:
https://cloud.google.com/sql/docs/postgres/add-manage-iam-users#creating-a-database-user

It states "Service accounts use the format service-account-name@project-id.iam.gserviceaccount.com"
But that isn't the case for CloudSQL Postgres, they use the format service-account-name@project-id.iam

**Comment by philip-harvey** [comment]
Finally found it!

https://cloud.google.com/sql/docs/postgres/add-manage-iam-users#rest-v1beta4
"Note: Due to the length limit on a database username, you need to omit the .gserviceaccount.com suffix in the email. For example, the service account email for the service account sa-name@project-id.iam.gserviceaccount.com should be provided as sa-name@project-id.iam."

**Comment by philip-harvey** [comment]
I don't think trimming the name would be a breaking change since it could be done for just Postgres, and even if it was trimmed for MySQL it wouldn't break things since MySQL discards everything after the @ sign anyway, but I do understand the hesitancy to put this logic into the provider when it really should be in the API. e.g. the API errors that you need to truncate the name, it could just do this for you instead of throwing the error.
I think a note about the API for IAM users for MySQL dropping everything after the @ sign, and the API for IAM users for Postgres requiring you to pass a trimmed userID, along with an example similar to the above would be sufficient to close this out.

**Comment by roaks3** [comment]
Unassigning myself on this one so that it is open for someone else to pick up

**Comment by fotinakis** [comment]
I got hit by this issue myself so took a stab at the documentation update here: https://github.com/hashicorp/terraform-provider-google/pull/15391

@philip-harvey @roaks3 @edwardmedia is one of you able to review that PR?

**Comment by roaks3** [comment]
@fotinakis thanks for giving this a look. Once you create your PR, a reviewer will automatically be assigned to you from our team. You will only need an approval from that reviewer to get your change merged.
