### ISSUE TITLE
Support ephemeral_storage_local_ssd_config

### ISSUE THREAD

**Issue by dannawang0221** [hashicorp/terraform-provider-google#14021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support ```ephemeral_storage_local_ssd_config```  for [GKE Local SSD](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd#creating_a_node_pool_using_ephemeral_storage_on_local_ssds) 

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
#  ephemeral_storage_local_ssd_config 
resource "google_container_node_pool" "node_pool_name" {
  name               = "example-name"
  location           = "us-central1-c"
  cluster            = google_container_cluster.cluster.name
  initial_node_count = 1

  node_config {
    machine_type = "n1-standard-1"
    ephemeral_storage_local_ssd_config {
      local_ssd_count = 1
    }
  }
}
```
### References

* https://cloud.google.com/kubernetes-engine/docs/concepts/local-ssd
* https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd

**Comment by dannawang0221** [comment]
I'm working on this issue.

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/13829, https://github.com/hashicorp/terraform-provider-google/issues/8461

**Comment by rileykarson** [comment]
Note per https://github.com/GoogleCloudPlatform/magic-modules/pull/7483#issuecomment-1472976840: ephemeral_storage_local_ssd_config is different from ephemeral_storage_config
