### ISSUE TITLE
Singleton resource google_firebase_project cannot easily be used in multiple configs

### ISSUE THREAD

**Issue by martinmaly** [hashicorp/terraform-provider-google#14036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.2
on darwin_amd64
```

### Affected Resource(s)

* `google_firebase_project`

### Terraform Configuration Files

```tf
variable "project" {
  type = string
}

resource "google_firebase_project" "default" {
  depends_on = [
    google_project_service.enabled
  ]
  provider = google-beta
  project  = var.project
}

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
    google-beta = {
      source = "hashicorp/google-beta"
    }
  }
}

provider "google-beta" {
  billing_project       = var.project
  user_project_override = true
}

resource "google_project_service" "enabled" {
  project            = var.project
  service            = "firebase.googleapis.com"
  disable_on_destroy = false
}
```

### Debug Output

https://gist.github.com/martinmaly/3551301c59b978988166118d38729688

### Expected Behavior

Ideally Terraform provider would understand that `google_firebase_project` is a singleton resource (much like enabling an API in a project) and not fail when firebase has already been enabled on the project.

### Actual Behavior

```
╷
│ Error: Error creating Project: googleapi: Error 409: Project 1234567891011 is already a Firebase project.
│
│   with google_firebase_project.default,
│   on main.tf line 5, in resource "google_firebase_project" "default":
│    5: resource "google_firebase_project" "default" {
│
╵
```

### Steps to Reproduce

1. create 2 directories and copy the Terraform config in each
2. `terraform apply` in the first directory, using `--var=project=YOUR_PROJECT_ID`
3. `terraform apply` in the second directory, also using `--var=project=YOUR_PROJECT_ID`
4. notice 409 on the 2nd apply

### Important Factoids

n/a

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_project

Note: `Once Firebase has been added to a Google Project it cannot be removed.`

**Comment by martinmaly** [comment]
An argument why I believe Terraform provider should handle this is because of the following repro steps:

# Alternative Repro Steps

1. `terraform apply --var=project=YOUR_PROJECT_ID` the config above
2. `terraform destroy --var=project=YOUR_PROJECT_ID`
3. `terraform apply --var=project=YOUR_PROJECT_ID` the config above

Same error occurs.

**Comment by edwardmedia** [comment]
@martinmaly api does return 409 in this case. What to do `not fail`? How could it let users know when this happens? 

```
not fail when firebase has already been enabled on the project.
```

**Comment by martinmaly** [comment]
@edwardmedia it is a bit strange that Terraform returns error in this case. Is it necessary to let the users know? Or would warning be sufficient in this situation and let the `apply` succeed?

The compelling argument in my mind is that `destroy` in this case does not go back to a state where another `apply` can possibly succeed.

**Comment by edwardmedia** [comment]
@martinmaly personally I think the error like below is a proper message to users. I don't think we should let `apply` succeed. If yes, users would assume the 2nd instance were created. 

```
error: Error creating Project: googleapi: Error 409: Project 1234567891011 is already a Firebase project.
```

**Comment by martinmaly** [comment]
There is only the singleton instance involved and documentation is actually clear about that. It is also clear that once enabled, Firebase cannot be disabled and so customer can predictably get into a bad state:

1. `terraform apply` ... this works (assuming Firebase used for the first time in a project)
2. `terraform destroy` ... this cannot revert the project to a state before step No. 1 because Firebase activation in a project cannot be undone
3. `terraform apply` ... fails.

I don't quite see how this is a result customer would expect.

**Comment by roaks3** [comment]
My understanding of this resource is that it does not create a project, instead it only enables Firebase for an existing project, and it cannot disable Firebase. With this in mind, I would still expect "apply -> destroy -> apply" to succeed as it does for other resources, and that would match how `project_service` behaves. Forcing the user to import to get past the current error seems unnecessary and mildly confusing for a toggle resource like this (although, at least a workaround does exist).

Note that if we make this resource behave [more like `project_service`](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/resources/resource_google_project_service.go#L146-L162), we may need to convert the resource from MMv1 to handwritten, or use custom hooks to do that.

**Comment by martinmaly** [comment]
I understand this resource the same way, @roaks3 and likewise would expect `apply`->`destroy`->`apply` to succeed and match the `project_service` experience/behavior.
