### ISSUE TITLE
Error creating the custom project role. Error 400: Permission is not valid

### ISSUE THREAD

**Issue by Rendyhz97** [hashicorp/terraform-provider-google#14033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.9 on Cloud Shell GCP
provider registry.terraform.io/hashicorp/google v4.57.0

### Affected Resource(s)
google_project_iam_custom_role

### Terraform Configuration Files

```provider.tf
provider "google" {
  project = "xxx-xxx-xxx-xx"
  region  = "asia-southeast2"
  zone    = "asia-southeast2-a"
}
```

```main.tf
  role_id         = "testsqlviewer"
  title              = "testsqliewer"
  description  = "test"
  permissions = [
    "cloudsql.backupRuns.get",
    "cloudsql.backupRuns.list",
    "cloudsql.databases.get",
    "cloudsql.databases.getIamPolicy",
    "cloudsql.databases.list",
    "cloudsql.instance.addServerCa",
    "cloudsql.instances.clone",
    "cloudsql.instances.connect",
    "cloudsql.instances.demoteMaster",
    "cloudsql.instances.export",
    "cloudsql.instances.failover",
    "cloudsql.instances.get",
    "cloudsql.instances.getIamPolicy",
    "cloudsql.instances.import",
    "cloudsql.instances.list",
    "cloudsql.instances.listServerCa",
    "cloudsql.instances.promoteReplica",
    "cloudsql.instances.resetSslConfig",
    "cloudsql.instances.restart",
    "cloudsql.instances.restoreBackup",
    "cloudsql.instance.rotateServerCa",
  ]
}
```

### Actual Behavior
 Error: Error creating the custom project role projects/{myproject}roles/testsqlviewer: googleapi: Error 400: Permission cloudsql.instance.rotateServerCa is not valid., badRequest

### Expected Behavior
Expected Custom Role created successfully. I have checked that cloudsql.instance.rotateServerCa is a valid permission. and I have done custom creation via Google Cloud Console for cloudsql.instance.rotateServerCa permission there is no problem. I also made sure that there were no typos in my source code.

### Steps to Reproduce

1. run `terraform init`
2. run `terraform apply`

**Comment by edwardmedia** [comment]
@Rendyhz97 you may reference below doc to see if the permissions are available. Here is what I found

```ts
  permissions = [
    "cloudsql.backupRuns.get",
    "cloudsql.backupRuns.list",
    "cloudsql.databases.get",
    "cloudsql.databases.getIamPolicy",    <----- not supported
    "cloudsql.databases.list",
    "cloudsql.instance.addServerCa",   <------ missing `s`
    "cloudsql.instances.clone",
    "cloudsql.instances.connect",
    "cloudsql.instances.demoteMaster",
    "cloudsql.instances.export",
    "cloudsql.instances.failover",
    "cloudsql.instances.get",
    "cloudsql.instances.getIamPolicy",    <----- not supported
    "cloudsql.instances.import",
    "cloudsql.instances.list",
    "cloudsql.instances.listServerCa",    <------ missing `s`
    "cloudsql.instances.promoteReplica",
    "cloudsql.instances.resetSslConfig",
    "cloudsql.instances.restart",
    "cloudsql.instances.restoreBackup",
    "cloudsql.instance.rotateServerCa",    <------ missing `s`
  ]
```

https://cloud.google.com/iam/docs/understanding-roles

**Comment by Rendyhz97** [comment]
Thanks a lot for information. I know the rootcause now. Previously I saw the iam cloud sql permission information at this link :   https://cloud.google.com/sql/docs/postgres/iam-roles 
but I think there is wrong information on that link.
