### ISSUE TITLE
Terraform doesn't apply changes when removing data masking policy tag from `google_bigquery_table`.

### ISSUE THREAD

**Issue by rariyama** [hashicorp/terraform-provider-google#14047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.57.0
+ provider registry.terraform.io/hashicorp/google-beta v4.57.0
```

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

We can deploy one bigquery table with the terraform code below.
```tf
resource "google_bigquery_table" "bq_table" {
  table_id = "test_policy_tag"
  dataset_id = "test_bq_table"
  deletion_protection = false


  schema = file("table_schema/test_bq_table.json")
}
```

The content of `test_bq_table.json` is like this.
Policy tag can be attached to `description` column.
```json
[
    {
        "name": "id",
        "type": "INTEGER",
        "mode": "NULLABLE",
        "description": ""
    },
    {
        "name": "description",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "",
        "policyTags": {
            "names": [
                "projects/my-project/locations/my-location/taxonomies/id/policyTags/policy-tag-id"
            ]
        }
    }
]
```
### Debug Output
If we want to detach the policy tag, we need to remove it from json.
```json
[
    {
        "name": "id",
        "type": "INTEGER",
        "mode": "NULLABLE",
        "description": ""
    },
    {
        "name": "description",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": ""
    }
]
```

Terraform detects the changes in the plan step
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_bigquery_table.bq_table will be updated in-place
  ~ resource "google_bigquery_table" "bq_table" {
        id                  = "projects/my-project/datasets/test_bq_table/tables/test_policy_tag"
      ~ schema              = jsonencode(
          ~ [
              ~ {
                  + description = ""
                    name        = "id"
                    # (2 unchanged elements hidden)
                },
              ~ {
                  + description = ""
                    name        = "description"
                  - policyTags  = {
                      - names = [
                          - "projects/my-project/locations/my-location/taxonomies/id/policyTags/policy-tag-id",
                        ]
                    } -> null
                    # (2 unchanged elements hidden)
                },
            ]
        )
        # (15 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

and reports succesful changes in apply
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_bigquery_table.bq_table: Modifying... [id=projects/my-project/datasets/test_bq_table/tables/test_policy_tag]
google_bigquery_table.bq_table: Modifications complete after 0s [id=projects/my-project/datasets/test_bq_table/tables/test_policy_tag]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behavior

The policy tag should be detached from the table

### Actual Behavior
The policy tag still remains on the column.

### Steps to Reproduce

1. `Deploy bigquery table with table schema file and policy tag.`
1. `Remove policy tag from schema file.`
1. `Deploy it again`

**Comment by edwardmedia** [comment]
I can repro this. I think it might be a bug at the API. 
b/274616360

**Comment by rariyama** [comment]
Thanks for your comments.
I tried the workaround @ben-marengo-msmg suggested with the json. And I confirmed terraform could detach the policy tag from table.
```
[
    {
        "name": "id",
        "type": "INTEGER",
        "mode": "NULLABLE",
        "description": ""
    },
    {
        "name": "description",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "",
        "policyTags": {
            "names": [
            ]
        }
    }
]
```

`terraform plan` result is as follows.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_bigquery_table.bq_table will be updated in-place
  ~ resource "google_bigquery_table" "bq_table" {
        id                  = "projects/my-project/datasets/dataset-id/tables/table-id"
      ~ schema              = jsonencode(
          ~ [
              ~ {
                  + description = ""
                    name        = "id"
                    # (2 unchanged attributes hidden)
                },
              ~ {
                  + description = ""
                    name        = "description"
                  ~ policyTags  = {
                      ~ names = [
                          - "projects/my-project/locations/my-location/taxonomies/taxonomy-id/policyTags/policy-tag-id",
                        ]
                    }
                    # (2 unchanged attributes hidden)
                },
            ]
        )
        # (15 unchanged attributes hidden)
    }
```

After that, I run `terraform plan` again, and the result is below.
```
  # google_bigquery_table.bq_table will be updated in-place
  ~ resource "google_bigquery_table" "bq_table" {
        id                  = "projects/my-project/datasets/dataset-id/tables/table-id"
      ~ schema              = jsonencode(
          ~ [
              ~ {
                  + description = ""
                    name        = "id"
                    # (2 unchanged attributes hidden)
                },
              ~ {
                  + description = ""
                    name        = "description"
                  + policyTags  = {
                      + names = []
                    }
                    # (2 unchanged attributes hidden)
                },
            ]
        )
        # (15 unchanged attributes hidden)
    }
```

Then, We can detach policy tag with terraform by passing empty array even though schema diff shows up.

**Comment by neilstuartcraig** [comment]
I also came across this exact issue in the last few days. I had policy tags on some columns in several tables and removed them. Now every time I deploy I get:

```
~ resource "google_bigquery_table" "log_source_tables" {
        id                  = "projects/bbc-otg-traf-mgr-bq-prod-4591/datasets/vtm_test/tables/id_access"
      ~ schema              = jsonencode(
          ~ [
                # (3 unchanged elements hidden)
                {
                    description = "HTTP request method"
                    mode        = "NULLABLE"
                    name        = "request_method"
                    type        = "STRING"
                },
              ~ {
                    name       = "uri"
                  - policyTags = {
                      - names = [
                          - "projects/...",
                        ]
                    }
                    # (2 unchanged attributes hidden)
                },
                {
                    description = "The query string element of the request URI"
                    mode        = "NULLABLE"
                    name        = "query_string"
                    policyTags  = {
                        names = [
                            "projects/...",
                        ]
                    }
                    type        = "STRING"
                },
                # (38 unchanged elements hidden)
            ]
        )
        # (16 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
So deploys succeed but it's confusing for anyone looking at the plan.

I'll try the workaround but a "proper" fix would be amazing!

**Comment by neilstuartcraig** [comment]
> 

I just tried the workaround and it does work. So you have to:
1. Add/set `policyTags  = {names = []}` & run `terraform apply`
2. Remove the policyTags property from the schema & run `terraform apply` again

Now subsequent plans/applys won't show the spurious changes.

**Comment by rariyama** [comment]
Hi @neilstuartcraig 
Thanks for your comment. I confirmed your solution works well:+1:
Probably, it is a bug about Bigquery API, not terraform provider. Then, we need to try your solution or manually remove tags on console until the bug is fixed.

**Comment by edwardmedia** [comment]
b/290262067
b/290048262

**Comment by neilstuartcraig** [comment]
> Hi @neilstuartcraig Thanks for your comment. I confirmed your solution works well👍 Probably, it is a bug about Bigquery API, not terraform provider. Then, we need to try your solution or manually remove tags on console until the bug is fixed.

I have been speaking to our Google Cloud team & support - apparently it's intended behaviour! The rationale is that they think it protects us from accidentally removing a policy. I have told them I disagree as it doesn't fit with Terraform norms or the principal of least surprise, especially as there's no feedback to let the user know what's (not) happening.

Google have asked for a call so I'll discuss it with them, let's hope they'll change their minds! I'll update here when I know more.

For now, you're best off using the workaround above - which is a pain as you have to deploy twice (which means 2 PRs, 2 PR reviews & 2 scheduled changes for me/us 👎🏻).
