### ISSUE TITLE
google_compute_forwarding_rule: adding serviceDirectoryRegistrations[].serviceDirectoryRegion

### ISSUE THREAD

**Issue by davelanglois-ssc** [hashicorp/terraform-provider-google#14049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

adding serviceDirectoryRegistrations[].serviceDirectoryRegion support to resource_compute_forwarding_rule.go as per rest [api](https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules/insert#request-body)

google_compute_forwarding_rule  is a DCL based resource

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

b/314617188

**Comment by fmichaelobrien** [comment]
Following

**Comment by pawelJas** [comment]
From the same [api](https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules/insert#request-body) link in the request:
![image](https://github.com/hashicorp/terraform-provider-google/assets/56267784/a5aca755-972c-44ac-90a2-62dff097eb7a)

This field has no use for non-global/regional forwarding rule (google_compute_forwarding_rule)

**Comment by pawelJas** [comment]
@ScottSuarez Could we close this Issue please? This field is not required in google_compute_forwarding_rule (regional forwarding rule)

**Comment by ScottSuarez** [comment]
While, from your discussion, it's not useful in certain instances of `google_compute_forwarding_rule` it's not clear to me that it would 'never' be useful. 

Could you expand on how this fields would not be useful for this resource under any scenarios? Why is it supported in the API at all?

@pawelJas

**Comment by pawelJas** [comment]
@ScottSuarez 
In GCP every global, regional and zonal resources share the same public API message scheme. Those are separate API but generated from the same proto. Whenever the new field is added to any of the entity type gobal/regional/zonal it always appears in all the documentations and API definitions. It is not the best design, I agree with that.

If the new feature is designed well then there is an early validation which rejects the calls using unsupported fields, In some cases the field is just ignored. Also good defence mechanism is to provide a clear field description. 

In the given example of `serviceDirectoryRegion` it says `region to register this global forwarding rule`. This field should only be used with `google_compute_global_forwarding_rule` to point in which region is the Service Directory. The `serviceDirectoryRegion` location is not needed for `google_compute_forwarding_rule` which is regional and will share the location of the Service Directory.

**Comment by melinath** [comment]
Makes sense, thanks! Closing.
