### ISSUE TITLE
Feature request to add multiple services in `google_project_service`

### ISSUE THREAD

**Issue by msampathkumar** [hashicorp/terraform-provider-google#14042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is a feature request for something new. This is not a blocker but I believe this can simplify users effort. For Google Cloud Function, as you can see @ https://screenshot.googleplex.com/AkdhDbjGJbaYf25 a user could require enabling multiple services at once.

If `google_project_service` can support enabling multiple services at once, it could simple users work. Kindly please review its possibilities.

You may close this request, if it is by design or not possible to do. Please reach out if you need more details from me, otherwise many thanks 😊 

### New or Affected Resource(s)

* google_project_service

### Potential Terraform Configuration

Code sample from https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service

```tf
resource "google_project_service" "project" {
  project = "your-project-id"
  service = "iam.googleapis.com" # Here can you make it as `services` where a list can be added.

  timeouts {
    create = "30m"
    update = "40m"
  }

  disable_dependent_services = true
}
```

### References

* #0000

**Comment by rileykarson** [comment]
`google_project_service` targeting the same project executed by Terraform at the same time will actually batch together into a single request. A single-resource interface was supported as a `google_project_services` resource in the past, but it was removed for the reasons described in https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_3_upgrade#google_project_services-has-been-removed-from-the-provider
