### ISSUE TITLE
Error: The terraform-provider-google_v4.57.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by vamsee-web** [hashicorp/terraform-provider-google#14045]
### Terraform Version

terraform {
  required_version = "~> 1.3.9"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.41.1, < 5.0"
    }

    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 4.41.1, < 5.0"
    }
  }
}

### Affected Resource(s)

on bigquery.tf line 87, in resource "google_bigquery_dataset_iam_binding" "reader":
87: resource "google_bigquery_dataset_iam_binding" "reader" {

with google_cloudfunctions_function.mbp_cf[0],
on cloudfunction.tf line 30, in resource "google_cloudfunctions_function" "mbp_cf":
30: resource "google_cloudfunctions_function" "mbp_cf" {

on .terraform/modules/service_accounts.service_accounts/main.tf line 46, in resource "google_project_iam_member" "project-roles":
46: resource "google_project_iam_member" "project-roles" {

with module.cloud-storage-notebook[0].google_storage_bucket.buckets["notebooks"],
on ../../../modules/terraform-google-cloud-storage/main.tf line 41, in resource "google_storage_bucket" "buckets":
41: resource "google_storage_bucket" "buckets" {

with module.cloud-storage-intrim.google_storage_bucket_object.folders["amount-third-party_iovation"],
on ../../../modules/terraform-google-cloud-storage/main.tf line 213, in resource "google_storage_bucket_object" "folders":
213: resource "google_storage_bucket_object" "folders" {

with module.cloud-storage-intrim.google_storage_bucket_object.folders["amount-third-party_iovation"],
on ../../../modules/terraform-google-cloud-storage/main.tf line 213, in resource "google_storage_bucket_object" "folders":
213: resource "google_storage_bucket_object" "folders" {

with module.gcs_sa_iam_rpt["binding2"].module.storage_bucket-iam-bindings.google_storage_bucket_iam_member.storage_bucket_iam_additive["bkt-jb-q-dmgt-cdz-fis-mbp-lending--roles/storage.legacyBucketWriter--serviceAccount:"],
on .terraform/modules/gcs_sa_iam_rpt.storage_bucket-iam-bindings/modules/storage_buckets_iam/main.tf line 49, in resource "google_storage_bucket_iam_member" "storage_bucket_iam_additive":
49: resource "google_storage_bucket_iam_member" "storage_bucket_iam_additive" {

with module.subnet_iam_dataproc_dataprox[0].module.subnet-iam-bindings.google_compute_subnetwork_iam_binding.subnet_iam_authoritative["default--roles/compute.networkUser"],
on .terraform/modules/subnet_iam_dataproc_dataprox.subnet-iam-bindings/modules/subnets_iam/main.tf line 31, in resource "google_compute_subnetwork_iam_binding" "subnet_iam_authoritative":
31: resource "google_compute_subnetwork_iam_binding" "subnet_iam_authoritative" {

### Panic Output

Stack trace from the terraform-provider-google_v4.57.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x24a3026]

goroutine 110 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceIamBindingCreateUpdate.func1.1(0x0)
	github.com/hashicorp/terraform-provider-google/google/resource_iam_binding.go:102 +0x26
github.com/hashicorp/terraform-provider-google/google.iamPolicyReadModifyWrite({0x34c3e90, 0xc000d7efc0}, 0xc000c36120)
	github.com/hashicorp/terraform-provider-google/google/iam.go:96 +0x2df
github.com/hashicorp/terraform-provider-google/google.resourceIamBindingCreateUpdate.func1(0xc00056f780, {0x2eec3c0?, 0xc001277000})
	github.com/hashicorp/terraform-provider-google/google/resource_iam_binding.go:112 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x34c2e18?, {0x34c2e18?, 0xc00113a480?}, 0xd?, {0x2eec3c0?, 0xc001277000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00098ee00, {0x34c2e18, 0xc00113a480}, 0xc0008e24e0, 0xc00056f600, {0x2eec3c0, 0xc001277000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000994840, {0x34c2e18?, 0xc00113a360?}, 0xc000095e50)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000bc280, {0x34c2e18?, 0xc0011311d0?}, 0xc000c0ecb0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x2e79e00?, 0xc0000bc280}, {0x34c2e18, 0xc0011311d0}, 0xc000c0ec40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x34c8860, 0xc00096bd40}, 0xc000b06120, 0xc00097b650, 0x46d93c0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x34c8860, 0xc00096bd40}, 0xc000b06120, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-google_v4.57.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Need to add the roles and its permissions.

**Comment by vamsee-web** [comment]
because of this block my pipeline is getting crashed.

# resource "google_bigquery_dataset_iam_binding" "reader" {
#   project    = var.project_id
#   dataset_id = var.dataset_id_dw
#   role       = "roles/bigquery.dataEditor"

#   members = [
#     "serviceAccount:",
#   ]
# }


earlier the same block was working

**Comment by roaks3** [comment]
Hi @vamsee-web , I've looked into this a bit and do not see any obvious issues in the code that would be causing the issue. There are a couple things that could help us diagnose (ultimately, having a reproduction of the issue would be ideal):
1. Can you share more of the config you are using? Particularly, the resources that interact with this `google_bigquery_dataset_iam_binding` would help.
2. Could you run terraform with `TFL=_LOG=DEBUG` and share the output (a gist would probably best best for sharing)?
3. Is there any more info you can share about how you came across this crash? Did you change any configuration? Did this happen after a provider upgrade?

**Comment by slevenick** [comment]
Looks like the config provided is invalid:
```
│ Error: invalid value for members.0 (IAM members must have one of the values outlined here: https://cloud.google.com/billing/docs/reference/rest/v1/Policy#Binding)
│
│   with google_bigquery_dataset_iam_binding.reader,
│   on t.tf line 4, in resource "google_bigquery_dataset_iam_binding" "reader":
│    4: members = [
│    5: "serviceAccount:",
│    6: ]
```

If you can provide a valid config that causes this bug please reopen or open a new issue
