### ISSUE TITLE
google_access_context_manager_service_perimeter - Error: Null value found in list - Null values are not allowed for this attribute value.

### ISSUE THREAD

**Issue by amar2k05** [hashicorp/terraform-provider-google#14059]
Hi,
I am using resource "google_access_context_manager_service_perimeter" to create perimeter and passing list of GCP projects to "resources" parameter but I am getting below error.
I am not sure why this behaviour is occurring even though I am giving the input properly i.e. resources = ["projects/96787594399"]
Appreciate any response.

**Error start:**
Error: Null value found in list
│ 
│   with google_access_context_manager_service_perimeter.test_prod_perim_002,
│   on vpc_sc_resource_yaml.tf line 18, in resource "google_access_context_manager_service_perimeter" "test_prod_perim_002":
│   18:     resources = ["projects/96787594399"]
│ 
│ Null values are not allowed for this attribute value.
**Error end:**

Thanks,
Amarnath.

### Affected Resource(s)

google_access_context_manager_service_perimeter

**Comment by edwardmedia** [comment]
@amar2k05 can you share the config you are using and the steps to repro the issue?

**Comment by amar2k05** [comment]
Hi Edward,
PFB the gist link where all the files related to code are available.

https://gist.github.com/amar2k05/92c874795a885a940410fe811624de1a

Thanks,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 read the config you shared in the gist, I don't know how to repro, as there are dynamic code. Instead,
are you able to try the [sample](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter#example-usage---access-context-manager-service-perimeter-secure-data-exchange) to see if that works for you?

**Comment by edwardmedia** [comment]
@amar2k05 is this still an issue?

**Comment by amar2k05** [comment]
Hi Edward,
I have tried with latest provider and it's fine now.

Thanks,
Amarnath.

**Comment by edwardmedia** [comment]
@amar2k05 glad to know it is fine now. Closing this issue accordingly
