### ISSUE TITLE
User service account email instead of ID in the Eventarc-Workflows terraform sample

### ISSUE THREAD

**Issue by minyu19** [hashicorp/terraform-provider-google#14069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.9

### Affected Resource(s)
google_workflows_workflow

### Terraform Configuration Files

```tf
data "google_project" "project" {
  provider = google-beta
}

# Enable Eventarc API
resource "google_project_service" "eventarc" {
  provider           = google-beta
  service            = "eventarc.googleapis.com"
  disable_on_destroy = false
}

# Enable Pub/Sub API
resource "google_project_service" "pubsub" {
  provider           = google-beta
  service            = "pubsub.googleapis.com"
  disable_on_destroy = false
}

# Enable Workflows API
resource "google_project_service" "workflows" {
  provider           = google-beta
  service            = "workflows.googleapis.com"
  disable_on_destroy = false
}

# [END eventarc_terraform_enableapis]

# [START eventarc_workflows_create_serviceaccount]

# Create a service account for Eventarc trigger and Workflows
resource "google_service_account" "eventarc_workflows_service_account" {
  provider     = google-beta
  account_id   = "eventarc-workflows-sa"
  display_name = "Eventarc Workflows Service Account"
}

# Grant the logWriter role to the service account
resource "google_project_iam_binding" "project_binding_eventarc" {
  provider = google-beta
  project  = data.google_project.project.id
  role     = "roles/logging.logWriter"

  members = ["serviceAccount:${google_service_account.eventarc_workflows_service_account.email}"]

  depends_on = [google_service_account.eventarc_workflows_service_account]
}

# Grant the workflows.invoker role to the service account
resource "google_project_iam_binding" "project_binding_workflows" {
  provider = google-beta
  project  = data.google_project.project.id
  role     = "roles/workflows.invoker"

  members = ["serviceAccount:${google_service_account.eventarc_workflows_service_account.email}"]

  depends_on = [google_service_account.eventarc_workflows_service_account]
}

# [END eventarc_workflows_create_serviceaccount]

# [START eventarc_workflows_deploy]
# Define and deploy a workflow
resource "google_workflows_workflow" "workflows_example" {
  name            = "pubsub-workflow-tf"
  provider        = google-beta
  region          = "us-central1"
  description     = "A sample workflow"
  service_account = google_service_account.eventarc_workflows_service_account.id
  # Imported main workflow template file
  source_contents = templatefile("workflow.tftpl", {})

  depends_on = [google_project_service.workflows,
  google_service_account.eventarc_workflows_service_account]
}

# [END eventarc_workflows_deploy]

# [START eventarc_create_pubsub_trigger]
# Create an Eventarc trigger routing Pub/Sub events to Workflows
resource "google_eventarc_trigger" "trigger_pubsub_tf" {
  name     = "trigger-pubsub-workflow-tf"
  provider = google-beta
  location = "us-central1"
  matching_criteria {
    attribute = "type"
    value     = "google.cloud.pubsub.topic.v1.messagePublished"
  }
  destination {
    workflow = google_workflows_workflow.workflows_example.id
  }
  service_account = google_service_account.eventarc_workflows_service_account.id

  depends_on = [google_project_service.pubsub, google_project_service.eventarc,
  google_service_account.eventarc_workflows_service_account]
}
```

### Expected Behavior
In the https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/eventarc_workflows/main.tf, could you please update the following in the Terraform config file:
- google_service_account.eventarc_workflows_service_account.id to google_service_account.eventarc_workflows_service_account.email

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Reason for this request: The Eventarc team informed us to use email because ID causes error while checking for IAM policy of the service account.

### References

* #0000

**Comment by edwardmedia** [comment]
@minyu19 take a look at the serviceAccount on [this api doc](https://cloud.google.com/workflows/docs/reference/rest/v1/projects.locations.workflows), looks like it expect the id. Does this help answer your question?

**Comment by minyu19** [comment]
@edwardmedia Thank you, as per the link, the {account} in serviceAccount could be "The {account} value can be the email address or the unique_id of the service account." 
Since the ID was causing an error while checking for an IAM policy in a terraform sample, the Eventarc team informed us to use the email instead. So in the [terraform-docs-samples/blob/main/eventarc_workflows/main.tf](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/eventarc_workflows/main.tf), sample, could we make the requested change?

**Comment by edwardmedia** [comment]
Do you say make a change [here](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/eventarc_workflows/main.tf)? We don't own it.  Are we on the same page?

**Comment by msampathkumar** [comment]
@edwardmedia Just sharing the info, I have. During an investigation at [b/272592243](b/272592243#comment3) we found out that this change requirement. I believe has to be fixed even in API docs too.

@minyu19 please add if you have more information on this.

**Comment by minyu19** [comment]
Thank you, @msampathkumar !
Hi @edwardmedia , as per https://cloud.google.com/workflows/docs/reference/rest/v1/projects.locations.workflows, in the section that explains serviceAccount, they have the following information - "the {account} value can be the email address or the unique_id of the service account." 
Could we have https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workflows_workflow mention that the email address can also be used?

**Comment by edwardmedia** [comment]
@minyu19 to confirm, you want us to update below doc indicating an email address should be used? Is the existing id format still supported?

```
projects/{project}/serviceAccounts/{account}.
```


https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workflows_workflow#service_account

**Comment by edwardmedia** [comment]
@minyu19 can you clarify?

**Comment by minyu19** [comment]
Yes @edwardmedia, the existing id format is also supported along with the email address as per "The {account} value can be the email address or the unique_id of the service account." (Reference: https://cloud.google.com/workflows/docs/reference/rest/v1/projects.locations.workflows). So could we mention that the email address or id could be used in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workflows_workflow#service_account?
