### ISSUE TITLE
Support updating google_workstations_workstation_config, rather than delete/recreate

### ISSUE THREAD

**Issue by wilford** [hashicorp/terraform-provider-google#14072]
### Description

When updating an existing google_workstations_workstation_config, it looks like the provider will first try to delete the existing config and then recreate it with the new values.  An example is updating host.gce_instance.pool_size.  

The underlying API resource supports update calls on most fields: https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs/patch

The delta should just be patched in. 

### New or Affected Resource(s)

google_workstations_workstation_config

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7629
