### ISSUE TITLE
Apigee google_apigee_shared_flow requires org_name instead of org_id

### ISSUE THREAD

**Issue by georgy-varghese** [hashicorp/terraform-provider-google#14086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`Terraform Version: 1.4.2`
`provider registry.terraform.io/hashicorp/google: v4.58.0`

### Affected Resource(s)

* google_apigee_sharedflow

### Terraform Configuration Files

* Using org_id
```tf

data "archive_file" "this" {
  type        = "zip"
  source_dir  = "${path.module}/sharedflows/sf-flow"
  output_path = "${path.module}/sharedflows/sf-flow.zip"
}

resource "google_apigee_sharedflow" "sharedflow" {
  name           = "sharedflow"
  org_id         = module.apigee.org_id
  config_bundle  = data.archive_file.this.output_path 
  detect_md5hash = data.archive_file.this.output_md5
}
```
_Note_: `module.apigee` is sourced from [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/apigee)

*Output*
```
│   <p><b>404.</b> <ins>That’s an error.</ins>                                                                                                                                                                      
│   <p>The requested URL <code>/v1/organizations/organizations/<org_name>/sharedflows?name=<shareflow_name>&amp;action=import</code> was not found on this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_apigee_sharedflow.pre_flowhook,
│   on apigee-shared-flows.tf line 7, in resource "google_apigee_sharedflow" "sharedflow":              
│    7: resource "google_apigee_sharedflow" "sharedflow" {                                              
│ 
```
Looking at the code [here](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_apigee_sharedflow.go#L172), it seems it only needs org_name as below.

```tf
resource "google_apigee_sharedflow" "sharedflow" {
  name           = "sharedflow"
  org_id         = module.apigee.org_name
  config_bundle  = data.archive_file.this.output_path 
  detect_md5hash = data.archive_file.this.output_md5
}
```
### Expected Behavior

* Resource should be created using `org_id`, or
* Documentation (and probably parameter name) should be updated to `org_name`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@georgy-varghese here is where [org_id](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_apigee_sharedflow.go#L62) defined. Below is a test running every day.

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_apigee_sharedflow_test.go#L111

**Comment by georgy-varghese** [comment]
@edwardmedia, thanks for the quick response.

Resource `google_project.project.project_id` in the test, provides the organization name, which is different to the format in docs and `org_id`.
* org_name = `<org_name>`
  vs
* org_id = `organizations/<org_name>`

**Comment by edwardmedia** [comment]
@georgy-varghese  I do see what you mean now. [Here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.sharedflows/create) is where the api that defines the format of parent, not the org_id. Agreed we need to update the doc to match the reality.

**Comment by zli82016** [comment]
Hello, @georgy-varghese , can you please list the value of `module.apigee.org_id` and `module.apigee.org_name`? Thanks.
