### ISSUE TITLE
Label for Firebase resources

### ISSUE THREAD

**Issue by IchordeDionysos** [hashicorp/terraform-provider-google#14099]
I was wondering if it could make sense to create a label specifically for "Firebase" which could be assigned to all issues relating to Firebase-related services.

e.g. in the Firebase documentation, they link to Firebase-related issues by [filing an issue in the GitHub repo](https://github.com/hashicorp/terraform-provider-google/issues?q=is:issue+is:open+firebase), not by filtering for a tag `firebase`:

[Firebase documentation](https://firebase.google.com/docs/projects/terraform/get-started#:~:text=filing%20an%20issue%20in%20the%20GitHub%20repo)

I think this would be helpful for anyone trying to see if there is already an issue filed for a specific Firebase service or feature!

**Comment by edwardmedia** [comment]
@melinath what do you think about this suggestion?
