### ISSUE TITLE
Support Dataproc optional component Trino for 2.1.0+ images

### ISSUE THREAD

**Issue by erikamundson** [hashicorp/terraform-provider-google#14090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

For Dataproc images version 2.1.0+, the optional component Presto is replaced with Trino. It would be helpful terraform could support using the Trino optional component with image versions 2.1.x.

```
│ Error: expected cluster_config.0.software_config.0.optional_components.0 to be one of [COMPONENT_UNSPECIFIED ANACONDA DOCKER DRUID HBASE FLINK HIVE_WEBHCAT JUPYTER KERBEROS PRESTO RANGER SOLR ZEPPELIN ZOOKEEPER], got TRINO
│ 
│   with module.dataproc.google_dataproc_cluster.trino_cluster,
│   on ../../modules/dataproc/main.tf line 184, in resource "google_dataproc_cluster" "trino_cluster":
│  184:       optional_components = ["TRINO"]
```

Also, some other components are removed in 2.1.x compared to 1.x.x and 2.0.x
- DRUID
- HBASE
- ANACONDA (not available since 2.0.x)

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
resource "google_dataproc_cluster" "trino_cluster" {
  name = "${var.project}-trino-cluster"
  cluster_config {
    ...
    software_config {
      image_version       = "2.1.4-debian11"
      optional_components = ["TRINO"]
    }
  }
}
```

### References

* [GCP Documentation](https://cloud.google.com/dataproc/docs/concepts/components/overview#available_optional_components)

**Comment by rileykarson** [comment]
Note: Let's just make this a string rather than a strongly validated enum
