### ISSUE TITLE
DLP job trigger with multiple action options like save_findings and pub_sub

### ISSUE THREAD

**Issue by ayferkrd** [hashicorp/terraform-provider-google#14097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.2
on darwin_amd64

provider registry.terraform.io/hashicorp/archive v2.3.0
provider registry.terraform.io/hashicorp/google v4.57.0

### Affected Resource(s)

* google_data_loss_prevention_job_trigger

### Terraform Configuration Files

```tf
resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp" {
  parent       = "projects/${var.project_id}"
  description  = "BigQuery DLP Job Trigger with timestamplimit"
  display_name = "bigquery-dlp-job-trigger-limit-timestamp"

  triggers {
    schedule {
      recurrence_period_duration = "86400s"
    }
  }

  inspect_job {
    inspect_template_name = "projects/testlocations/global/inspectTemplates/6425492983381738900"
 storage_config {
      big_query_options {
        rows_limit = 1000
        sample_method = "TOP"
        table_reference {
          project_id = var.project_id
          dataset_id = "dataset"
          table_id   = "table"
        }
      }
    }

    actions {
      save_findings {
        output_config {
          table {
            project_id = var.project_id
            dataset_id = "output"
          }
        }
      }
      pub_sub {
        topic = var.pubsub_topic
      }
    }
  }
}
```

### Debug Output

│ Error: Error creating JobTrigger: googleapi: Error 400: Invalid value at 'job_trigger.inspect_job.actions[0]' (oneof), oneof field 'action' is already set. Cannot set 'saveFindings'
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value at 'job_trigger.inspect_job.actions[0]' (oneof), oneof field 'action' is already set. Cannot set 'saveFindings'",
│         "field": "job_trigger.inspect_job.actions[0]"
│       }
│     ]
│   }
│ ]
### Expected Behavior

to create dlp job trigger with both outputs saved in bigquery table also sent to pubsub topic

### Actual Behavior

cannot create dlp trigger

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

it must be possible to give multiple actions

### References

[](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_job_trigger#attributes-reference)

* #0000

**Comment by edwardmedia** [comment]
@ayferkrd I can repro what you see. The error 400 comes from the api. Where did you see the expected behavior? Can you share the link?

```
it must be possible to give multiple actions
```

**Comment by ayferkrd** [comment]
I can add both pubsub and save to bigquery while creating dlp job trigger from gcp console:
![image](https://user-images.githubusercontent.com/57121399/227838475-67ff68b4-e83d-4ff3-bc8c-c5c2ad4baaf1.png)

**Comment by edwardmedia** [comment]
@ayferkrd are you able to do the same with gcloud?

**Comment by ayferkrd** [comment]
I haven't tried gcloud cli but I can give multiple actions with DLP API

**Comment by edwardmedia** [comment]
@ayferkrd can you share the request payload when you test multiple actions with DLP API?

**Comment by ayferkrd** [comment]
I can create multiple actions with my python code using dlp client library, but now I tried it with dlp API call it returns the same error.

**Comment by slevenick** [comment]
Looks like an API-side restriction, not much we can do here

**Comment by realjordanna** [comment]
please reopen, this is not a backend restriction

**Comment by JayS-crest** [comment]
As per the issue, the request seems to be for adding multiple actions together. As per Terraform, the `actions` block is an array. So, instead of adding multiple actions to the same block, we could rather create multiple action blocks. That will work similarly to what the user is trying to do.

So instead of the below config.
```
actions{
  save_findings{}
  pub_sub{}
}

```
The ideal config as per terraform must be as follows.
```
actions{
  save_findings{}
}
actions{
  pub_sub{}
}
```

For the config mentioned in the issue, it could be sent like this.
```
actions {
  save_findings {
    output_config {
      table {
        project_id = var.project_id
        dataset_id = "output"
      }
    }
  }
}
actions {
  pub_sub {
      topic = var.pubsub_topic
  }
}
```
