### ISSUE TITLE
Resource google_project billing - potential critical bug

### ISSUE THREAD

**Issue by TomKulakov** [hashicorp/terraform-provider-google#14092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.7, and provider was v4+ (but I don't remember and don't have access to the code currently)

### Affected Resource(s)

* google_project

### Terraform Configuration Files
```tf
resource "google_project" "some_project" {
  name       = "Some Project"
  project_id = "some-project"
  folder_id  = google_folder.some_folder.name #or use organization instead
  labels = {test: "test"} # labels were added to the existing project
}
```

### Expected Behavior
Import should fail because of an missing permissions error or plan should display that billing will be removed. 

### Actual Behavior
Now it's getting interesting, because that depends on who is importing and with what permissions are given.
I did import state with Service Account with no billing viewer permissions and when I did by make a plan with another credentials with billing viewer permissions plan presented that billing will be removed. Here is a bug/design flaw/implementation error: it should fail if I'm missing some permissions or just display the billing ID - I think it's not a secret value, right?
Definitely it should not allow me to get access to only the part of the resource. 
I bet those are two depended resources, because it seems like project is linked to a billing in GCP. So **maybe having separate resource, google_project and google_project_billing would be good idea**.

Here is more descriptive possible scenario:
Imagine two Service Accounts: one for reading infrastructure for plan, another for applying infrastructure changes. Let's call them Planner and Applier. 
Planner has Folder Viewer, Project Viewer role, but no billing viewer role, because it's not needed (or is it?). 
Applier has Folder Admin, Projects Creator/Mover/Editor and so on + billing user (to be able to apply billing to project).
Planner was used to import state from currently existing infrastructure. Projects were imported, but because Planner had no Billing Viewer related permissions he knows nothing about the billing, hence in place of billing_account there is NULL in the state - **the state is untruthful** , because project has billing assigned!
It's time to modify imported project by adding label. Untruthful state was provided as the artifact to next step of the pipeline and Applier will take it and apply. billing_account will be set to NULL on existing project which had billing assigned.

### Steps to reproduce

1. Have two SA with permissions/roles mentioned above (make sure 1st that will make a plan will not have anything that will allow it to see billing). Also create some-project and assign a billing to it.
2. terraform init
3. terraform import google_project.some_project some-project
4. terraform plan with credentials of 1st SA
5. terraform apply with credentials of 2nd SA (should cause billing to be removed from project)

**Comment by edwardmedia** [comment]
@TomKulakov in your step 4 and 5,  do you see the diff? If yes, what do you see?

**Comment by edwardmedia** [comment]
@TomKulakov I do see what you mean now. [Here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.sharedflows/create) is where the api that defines the format of `parent`, not the `org_id`. Agreed we need to update the doc to match the reality.

**Comment by edwardmedia** [comment]
@TomKulakov is this still an issue/

**Comment by edwardmedia** [comment]
@TomKulakov closing this assuming it is no longer an issue
