### ISSUE TITLE
DLP job trigger on bigquery cannot use timespan config

### ISSUE THREAD

**Issue by ayferkrd** [hashicorp/terraform-provider-google#14096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/google v4.57.0

### Affected Resource(s)

* google_data_loss_prevention_job_trigger

### Terraform Configuration Files

```tf
resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp" {
  parent       = "projects/${var.project_id}"
  description  = "BigQuery DLP Job Trigger with timestamplimit"
  display_name = "bigquery-dlp-job-trigger-limit-timestamp"

  triggers {
    schedule {
      recurrence_period_duration ="86400s"
    }
  }

  inspect_job {
    inspect_template_name = "projects/test/locations/global/inspectTemplates/6425492983381733900" 
 storage_config {
      big_query_options {
        table_reference {
          project_id = var.project_id
          dataset_id = "dataset"
          table_id   = "table"
        }
      }

      timespan_config {
        start_time = "2023-01-01T00:00:23Z"
        timestamp_field {
          name = "timestamp"
        }
        enable_auto_population_of_timespan_config = true
      }
    }

    actions {
      save_findings {
        output_config {
          table {
            project_id = var.project_id
            dataset_id = "output"
          }
        }
      }
    }
  }
}
```

### Debug Output

 Error: Error creating JobTrigger: googleapi: Error 400: `rows_limit` or `rows_limit_percent` must be greater than zero when sample method is specified.
│ 
│   with module.bq_dlp_trigger.google_data_loss_prevention_job_trigger.bigquery_row_limit_timestamp,
│   on modules/bq_dlp_trigger/dlp_job_trigger.tf line 1, in resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp":
│    1: resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp" {
│ 

### Expected Behavior

Should create a DLP job trigger with timestamp configuration to run through the BigQuery.

### Actual Behavior

Cannot create DLP job trigger

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

rows_limit or rows_limit_percent cannot be used in conjunction with TimespanConfig.

### References

[](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_job_trigger#attributes-reference)

* #0000

**Comment by edwardmedia** [comment]
@ayferkrd it seems to be fine with me if I use below config. Do you see any difference?

```tf
resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_percentage" {
    parent = "projects/myproject"
    description = "Description"
    display_name = "Displayname"

    triggers {
        schedule {
            recurrence_period_duration = "86400s"
        }
    }

    inspect_job {
        inspect_template_name = "fake"
        actions {
            save_findings {
                output_config {
                    table {
                        project_id = "project"
                        dataset_id = "dataset"
                    }
                }
            }
        }
        storage_config {
            big_query_options {
                table_reference {
                    project_id = "project"
                    dataset_id = "dataset"
                    table_id = "table_to_scan"
                }

                rows_limit_percent = 50
                sample_method = "RANDOM_START"
            }
            
            timespan_config {
                start_time = "2023-01-01T00:00:23Z"
                timestamp_field {
                    name = "timestamp"
                }
                enable_auto_population_of_timespan_config = true
            }
        }
    }

}
```

**Comment by ayferkrd** [comment]
rows_limit_percent or rows_limit cannot be used with timespan_config:
 Error: Error creating JobTrigger: googleapi: Error 400: Both TimespanConfig and RowsLimit may not be set at the same time.
│ 
│   with module.bq_dlp_trigger.google_data_loss_prevention_job_trigger.bigquery_row_limit_timestamp["test_table"],
│   on modules/bq_dlp_trigger/dlp_job_trigger.tf line 1, in resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp":
│    1: resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit_timestamp" {
│

**Comment by ayferkrd** [comment]
@edwardmedia above config has sample_method with rows_limit_percent with timespan_config which is not possible

![image](https://user-images.githubusercontent.com/57121399/228101316-b94c6ec4-1af7-4e83-97f4-07282259bf9c.png)

**Comment by edwardmedia** [comment]
@ayferkrd Interesting. I see what you mean. I am not able to hit the error with my config, which contradicts below api doc. 
Wonder under what condition you can hit the error. Could you share your debug log?

b/275540727

https://cloud.google.com/dlp/docs/reference/rest/v2/InspectJobConfig#BigQueryOptions

**Comment by ayferkrd** [comment]
@edwardmedia I think even it doesn't hit the error, I believe the behaviour is not correct with the above configuration because timestamp configuration cannot work with sampling, it should scan the whole table.

**Comment by edwardmedia** [comment]
Create inspect job with both rows_limit and timespan_config:

expected: fails
actual: fails
Create inspect job with both rows_limit_percent and timespan_config:

expected: fails
actual: succeeds

**Comment by ayferkrd** [comment]
@edwardmedia, the real problem here is there is a default value set for sample_method, which blocks me from using timespan_config. Other than that, yes, both terraform and API has some problems independent of each other related to job trigger implementation.

**Comment by trodge** [comment]
b/280337903

**Comment by soumya92** [comment]
> I'm going to mark this as upstream because the core of the issue is an API error

Not entirely correct. As pointed out in https://github.com/hashicorp/terraform-provider-google/issues/14096#issuecomment-1489413261, this is an issue caused by the default value for `sample_method` which conflicts with Timespan filtering. Either setting timespan filtering should clear the sampling value, or the default for sample method should be unset.

**Comment by tlines2016** [comment]
> > I'm going to mark this as upstream because the core of the issue is an API error
> 
> Not entirely correct. As pointed out in [#14096 (comment)](https://github.com/hashicorp/terraform-provider-google/issues/14096#issuecomment-1489413261), this is an issue caused by the default value for `sample_method` which conflicts with Timespan filtering. Either setting timespan filtering should clear the sampling value, or the default for sample method should be unset.

I've come across this same issue where the provider is defaultiing `sample_method` to `top` within bigquery_options. In the meantime I'm just setting the default value for "rows_limit_percent" to 99 if rows_limit isn't defined as a sort of workaround for the issue of the provider defaulting to `sample_method = "top"` if we don't pass a value.

Quick question though, is it the case where we should open a new Issue for this, where it provides all of the details specific to the default value for `sample_method`? Or should we stick with this Issue for now?

**Comment by patrickmoy** [comment]
I attempted to use a custom encoder to remove `sample_method` if `timespan_config` is set, which would be a workaround for this case, but my update tests won't pass as the test plan is not empty. I'm not sure when the `default_value: :TOP` gets applied, but ImportStateVerifyIgnore doesn't fix my test either — the plan still expects `TOP`.

I've done some additional testing though, and it looks like setting `sample_method = ""` will pass, without the drawback of the 99% row limit workaround. I'll update the documentation with an example using `timespan_config` with an empty string for `sample_method` and consider this fixed.
