### ISSUE TITLE
 Can't configure a value for "host": its value will be decided automatically based on the result of applying this configuration.

### ISSUE THREAD

**Issue by StefanoAgostinelliHW** [hashicorp/terraform-provider-google#14101]
I'm trying to create a redis memory store with a defined write endpoint using the "host" argument but I'm not having success.
I'll send you the executed code and the error encountered:

Here is the code:
/ resource "google_redis_instance" "cache" {
  name           = local.redis_name
  project        = local.project
  region         = "europe-west8"
  host           = "10.125.0.0"
  tier           = "BASIC"
  memory_size_gb = 1
  authorized_network = data.google_compute_network.redis-network.id
  connect_mode       = "PRIVATE_SERVICE_ACCESS"
  redis_version     = "REDIS_5_0"
  display_name      = local.redis_name

  depends_on = [google_service_networking_connection.private_service_connection]

}

Here is the error message:

│ Error: Value for unconfigurable attribute
│
│   with google_redis_instance.cache,
│   on main.tf line 65, in resource "google_redis_instance" "cache":
│   65:   host           = "10.125.0.3"
│
│ Can't configure a value for "host": its value will be decided automatically based on the result of applying this configuration.

I thank you in advance for your kind reply and wish you a good day,

Stèfano

**Comment by edwardmedia** [comment]
@StefanoAgostinelliHW can you achieve this with other ways (tools)? 

[Here](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances) is the api which says the `host` is output only. This is what the provider based on. I guess the provider may not be able to accept it from users. Is this helpful?

**Comment by edwardmedia** [comment]
@StefanoAgostinelliHW closing this assuming it is no longer a question
