### ISSUE TITLE
Update Go lang version in providers to reduce vulnerabilities.

### ISSUE THREAD

**Issue by rakeshmulugu** [hashicorp/terraform-provider-google#14102]
Hello, 

We are building Images with terraform and Google Providers upgraded to the latest versions. The vulnerability scan results have high vulnerabilities related to the Go lang package bundled with google-provider.

I've noticed that the Google provider (4.58.0) is still using an older version of Golang (version 1.18.1) that has known high vulnerabilities. The latest versions of Golang have addressed these vulnerabilities, and I believe that updating to the latest version would significantly reduce the risk of security breaches in production. 

Therefore,I request that the Go version used in the Google provider be updated to the latest version. This would give us all more confidence in using the provider and reduce the risk of security issues.

Thank you for your attention to this matter. Please find the screenshot attached.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/48657726/227983305-03f99e99-0918-44c4-99a9-06726c0ae52e.png)

**Comment by rileykarson** [comment]
@zli82016 could you take a look at making this change after the release is out? Thanks!

**Comment by zli82016** [comment]
> @zli82016 could you take a look at making this change after the release is out? Thanks!

Sure. I will look into it.

**Comment by rileykarson** [comment]
Thanks! We tend to stay 1 minor release behind, so `1.19.7` is a good target version: https://go.dev/doc/devel/release#go1.19

**Comment by rakeshmulugu** [comment]
Hello, 

The issue is closed, so I tried building the image with the latest terraform version 1.4.2 and google providers of version 4.59.0. 

The vulnerability scans are the same; the terraform is still coupled with go 1.18.1. I have seen the PR related to this issue in magic modules where the Go version is modified. But the result is still the same.

This is our PROD setup, and there are 17 high vulnerabilities related to the older go lang version.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/48657726/228484011-a2d6a289-a234-429d-b8cd-44733346bc74.png)

**Comment by rileykarson** [comment]
The initial PR got reverted (https://github.com/GoogleCloudPlatform/magic-modules/pull/7548) due to goimports rule differences between versions, reopening.

**Comment by rakeshmulugu** [comment]
Hey I am just following the PR and merges from magic modules and this Repo I see in actions it still set up go version 1.8 . 

![Screenshot_20230329-233506](https://user-images.githubusercontent.com/48657726/228673523-0c08d728-d32c-4629-ae66-3ec50f38398f.png)

**Comment by rileykarson** [comment]
We made another revert in https://github.com/hashicorp/terraform-provider-google/pull/14143. This will take a bit longer- the gofmt change in `1.19` caused a surprisingly large delta for us.

**Comment by zli82016** [comment]
Upgraded Go 1.19 in https://github.com/GoogleCloudPlatform/magic-modules/pull/7645

**Comment by rakeshmulugu** [comment]
- I recently opened an issue with the `terraform-google-provider` repository to upgrade the Go language version bundled with Terraform providers, as the older version was causing vulnerabilities. The issue has since been closed after the reported changes were made. 

- However, after rebuilding the images with the latest versions of Terraform (1.4.5) and Google providers (4.62.1), I have noticed that the vulnerabilities related to Go 1.18 still persist. It appears that the providers are still using the older Go version.

- Upon further investigation, I found that the `go-version` file in the repository still contains the Go version 1.18.1. This discrepancy might be the cause of the issue. I request the reopening of the issue to address this concern. 

- If you require any further details or clarification, please let me know, and I'll be happy to provide the necessary information. It is crucial that we resolve this issue to ensure the security and stability of our infrastructure.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/48657726/233307724-247c1aa3-2a41-49e3-b01a-fae20831d705.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/48657726/233307764-4a7cc02d-616c-4b98-8b02-0a465e770944.png)

**Comment by rileykarson** [comment]
Ah, @zli82016 we need to update https://github.com/hashicorp/terraform-provider-google/blob/main/.go-version and https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.go-version in the downstream repos as well

**Comment by zli82016** [comment]
Upgraded Go in tpg and tpgb.

https://github.com/hashicorp/terraform-provider-google/pull/14371

https://github.com/hashicorp/terraform-provider-google-beta/pull/5522

**Comment by rakeshmulugu** [comment]
So the latest version will be bundled with tpg and tpgb in the next release?

**Comment by zli82016** [comment]
Probably not. It could be in the release after the next release.

**Comment by rileykarson** [comment]
I believe https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.64.0 was the release they were referring to! Can you check to see if the version is still outdated?

**Comment by rakeshmulugu** [comment]
The go version is updated. But still there are few vulnerabilities which
are critical that are fixed in latest go version.


Is it possible for you guys to maintain the version with each release with
the latest go version, so that everyone using these providers will be
having the latest stable versions of the go lang as well?

Would be helpful for us as well for presenting the images to security
Audits.

**Comment by rakeshmulugu** [comment]
The go version is updated. But still there are few vulnerabilities which are critical that are fixed in latest go version.


Is it possible for you guys to maintain the version with each release with the latest go version, so that everyone using these providers will be having the latest stable versions of the go lang as well?

Would be helpful for us as well for presenting the images to security Audits.

**Comment by zli82016** [comment]
Created PRs to upgrade the .go-verision in TGP and TGPB to 1.19.9

https://github.com/hashicorp/terraform-provider-google/pull/14561
https://github.com/hashicorp/terraform-provider-google-beta/pull/5623

**Comment by rakeshmulugu** [comment]
Thanks for the quick response,  just to confirm is it possible to maintain this version upgrade frequently??

**Comment by melinath** [comment]
Closing this as the version is updated. @rakeshmulugu we are not currently planning to automatically update to the latest go versions, but please do let us know if there are future concerns about a specific provider version.
