### ISSUE TITLE
v4.59.0 not available on releases.hashicorp.com

### ISSUE THREAD

**Issue by blgm** [hashicorp/terraform-provider-google#14116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Hi folks,

I see that [v4.59.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.59.0) was released yesterday, but it doesn't seem to be available on https://releases.hashicorp.com/terraform-provider-google/ yet. This is unusual because the time between a release appearing on GitHub and in the Terraform registry is typically imperceptible.

### Expected Behavior

v4.59.0 should be downloadable via releases.hashicorp.com. Typically this happens within minutes of a new release being created.

### Actual Behavior

v4.59.0 is visible on GitHub, but v4.58.0 is the latest on releases.hashicorp.com.

### Steps to Reproduce

1. Navigate to: https://releases.hashicorp.com/terraform-provider-google/
1. Observe that v4.59.0 is not available yet

Thanks!

**Comment by edwardmedia** [comment]
@blgm there was an issue. Should be available today.
