### ISSUE TITLE
google_logging_metric: No options to disabled Log-based metrics

### ISSUE THREAD

**Issue by rubber-ant** [hashicorp/terraform-provider-google#14119]
Affected Resource(s)

- [google_logging_metric](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_metric)
-  ["hashicorp/google" ="4.58.0"](https://registry.terraform.io/providers/hashicorp/google/4.58.0/docs/resources/logging_metric)

Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

###  Description

According to the official documentation, there is a way to create additional log-based metrics https://cloud.google.com/sdk/gcloud/reference/logging/metrics/update

Unfortunately, there is no such ability with the terraform code

I believe, it could be great if we add blocks to disable the log-based metrics

```
resource "google_logging_metric" "logging_metric" {
     disabled: true
     ... 
     ...
}
```

Current configuration with some of the metrics disabled from the console:
```
gcloud beta logging metrics list --project  $PROJECT | grep disabled
disabled: true
disabled: true
disabled: true
disabled: true
disabled: true
```

**Comment by edwardmedia** [comment]
disabled is available at the[ api](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics)

**Comment by DrFaust92** [comment]
ill take a look
