### ISSUE TITLE
Code conflicts when trying to define serviceaccount for GKE autopilot cluster.

### ISSUE THREAD

**Issue by lisoHA** [hashicorp/terraform-provider-google#14135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.44.0.   (using 4.44 because the issue is supposedly fixed in this release, but have tried the latest 4.59.0 as well)
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files
```tf
resource "google_container_cluster" "home" {
  name     = "${var.gke_username}-gke"
  location = var.region

  # to avoid - Error 400: Max pods constraint on node pools for Autopilot clusters should be 32
  # open issue, https://github.com/hashicorp/terraform-provider-google/issues/10782
  ip_allocation_policy {
  }

  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = var.google_sa_email
      oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
    }
  }

  network    = google_compute_network.vpc_network.name
  subnetwork = google_compute_subnetwork.subnet.name

  # Enabling Autopilot for this cluster
  enable_autopilot = true
}
```

### Debug Output

Error: googleapi: Error 400: Overriding Autopilot autoscaling settings is not allowed., badRequest
│
│   with google_container_cluster.home,
│   on main.tf line 27, in resource "google_container_cluster" "home":
│   27: resource "google_container_cluster" "home" {

### Expected Behavior

This configuration, with autopilot enabled and providing a service account through cluster_autoscaling, should work.

### Actual Behavior

IDE (Goland) indicated a conflict between ```enable_autopilot = true``` and the ```cluster_autoscaling``` block
### Steps to Reproduce

1. `terraform apply`

### References

I have seen #13412 and the mentioned #9505, also the google issue mentioned in there indicates that this problem should be resolved

I am unsure on how to continue debugging this issue, as all resources point to the problem being fixed right now.

**Comment by edwardmedia** [comment]
@lisoHA your Terraform provider version seems old. Can you try the latest to see if that fixes the error?

**Comment by lisoHA** [comment]
It seems that on the latest version, 4.59, terraform no longer throws errors. GoLand however, still produces code conflicts, even on the latest version. Unfortunately the problem still persists.

When i try to terraform apply with autopilot disabled after the cluster is already created (with autopilot), i can have a glimpse under the hood (by looking at what it will delete), and it does specify my serviceaccount there. However, i am still not seeing the expected behaviour in GCP; The containers in the cluster are still not able to write logs to the logging component of GCP.

**Comment by slevenick** [comment]
Looks like a GKE problem rather than a Terraform issue. You can try filing an issue against the relevant trackers
