### ISSUE TITLE
`google_bigtable_gc_policy` does not accept `max_age` in days

### ISSUE THREAD

**Issue by redzioch** [hashicorp/terraform-provider-google#14149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.59.0
```

### Affected Resource(s)

* google_bigtable_gc_policy

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "4.59.0"
    }
  }
}

provider "google" {
  project     = "project-name"
}

resource "google_bigtable_table" "bigtable_table" {
  name          = "table-name"
  instance_name = "bigtable-instance"
  column_family {
    family = "test"
  }
}

resource "google_bigtable_gc_policy" "bigtable_gc_policy" {
  depends_on = [
    google_bigtable_table.bigtable_table
  ]
  instance_name = "bigtable-instance"
  table         = "table-name"
  column_family = "test"
  gc_rules = jsonencode({
    rules = [{
      max_age = "120d"
    }]
  })
}
```

### Debug Output

https://gist.github.com/redzioch/c9082ba60ea1fcae45d1a0200822b65a

### Expected Behavior

`google_bigtable_gc_policy.bigtable_gc_policy` should be created successfully.

### Actual Behavior

Apply fails.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When you set `max_age = "${120 * 24}h"` apply is performed without error:
```
Terraform will perform the following actions:

  # google_bigtable_gc_policy.bigtable_gc_policy will be created
  + resource "google_bigtable_gc_policy" "bigtable_gc_policy" {
      + column_family = "test"
      + gc_rules      = jsonencode(
            {
              + rules = [
                  + {
                      + max_age = "2880h"
                    },
                ]
            }
        )
      + id            = (known after apply)
      + instance_name = "bigtable-instance"
      + project       = (known after apply)
      + table         = "table-name"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Log: https://gist.github.com/redzioch/bfeaf20c04f4be1525b7cf0470d5e5f0

But when you try to apply again Terraform tries to update policy:

```
Terraform will perform the following actions:

  # google_bigtable_gc_policy.bigtable_gc_policy will be updated in-place
  ~ resource "google_bigtable_gc_policy" "bigtable_gc_policy" {
      ~ gc_rules      = jsonencode(
          ~ {
              ~ rules = [
                  ~ {
                      ~ max_age = "120d" -> "2880h"
                    },
                ]
            }
        )
        id            = "age() > 120d"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Log: https://gist.github.com/redzioch/6f6f8d5c89d7afce16d57160b413ea4a

b/277755316

**Comment by edwardmedia** [comment]
@redzioch This field is controlled by the client lib, and looks like it is defined as [duration](https://pkg.go.dev/time#Duration). Do you see if `days` is supported?  The provider just pass through and has no much control over what is accepted and what is not. Does this make sense?

During my test, it does not accept `120d`. Does it work for you?

**Comment by redzioch** [comment]
I have no problem to define max age in hours.

Problem is, that TF wants to change it to days.

Maybe it's a problem on GCP API side.

```
Terraform will perform the following actions:

  # google_bigtable_gc_policy.bigtable_gc_policy will be updated in-place
  ~ resource "google_bigtable_gc_policy" "bigtable_gc_policy" {
      ~ gc_rules      = jsonencode(
          ~ {
              ~ rules = [
                  ~ {
                      ~ max_age = "120d" -> "2880h"
                    },
                ]
            }
        )
        id            = "age() > 120d"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by glasser** [comment]
The bug appears to be that `getGCPolicyFromJSON` (converting from what you write in your TF file to the bigtable API representation) uses `time.ParseDuration`, which does not allow `d`ays (just hours and smaller increments). But `GcPolicyToGCRuleString` uses the [bigtable library's `GetDurationString`](https://github.com/googleapis/google-cloud-go/blob/cf3452eba7d02b28343c9e6c2425288f80e42d3c/bigtable/gc.go#L142-L164), which *is* capable of generating `120d`.

One workaround is to just set the policy to any amount that is not an exact multiple of days! ie, a policy of `2881h` should do the trick.
