### ISSUE TITLE
Add FHIR Pubsub Enhancement for Sending Full Resource on Delete

### ISSUE THREAD

**Issue by JosieLi-Google** [hashicorp/terraform-provider-google#14142]
There are two changes for FHIR Pub/sub:
1: Option for sending full pervious resources when deleting resource should be added for customers.
2: New attribute `versionId` is also added in Pub/sub messages for customers.

**Comment by melinath** [comment]
@JosieLi-Google could you clarify what Terraform resources would be impacted by this change / what a configuration after this change would look like? The documentation for google_healthcare_fhir_store has some examples that could be a good starting point: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_fhir_store
