### ISSUE TITLE
google_alloydb_instance database_flags format should be consistent with google_sql_database_instance

### ISSUE THREAD

**Issue by adamstrawson** [hashicorp/terraform-provider-google#14180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_alloydb_instance

### Terraform Configuration Files

The `google_alloydb_instance` resources expects the `database_flags` format to be in `key = value` however, this prevents the user from using Terraform Dynamic blocks, as these blocks don't allow the use of dynamic keys. 

```tf
resource "google_alloydb_instance" "primary-instance" {
  cluster       = google_alloydb_cluster.cluster.name
  instance_id   = "foobar"
  instance_type = "PRIMARY"

  database_flags = {
    "max_connections" = "1"
  }
}
```

The CloudSQL resource `google_sql_database_instance` that also uses `database_flags` has a `name` & `value` pair.

```tf
resource "google_sql_database_instance" "instance" {
  name                = var.database_name
  settings {
    database_flags {
      name  = "max_connections"
      value = "1"
    }
  }
}
```

This format allows the user to use Terraform Dynamic blocks to define the `database_flags`

```tf
resource "google_sql_database_instance" "instance" {
  name                = var.database_name
  settings {
  
    dynamic "database_flags" {
      for_each = var.database_flags

      content {
        name  = database_flags.key
        value = database_flags.value
      }
    }
  }
}
```

### Expected Behavior

`google_alloydb_instance` should be consistent with `google_sql_database_instance`resources, and how it formats `database_flags`

**Comment by edwardmedia** [comment]
@adamstrawson thanks for the observation, but I guess we don't much flexibility on that at the provider level. These are controlled by the apis.  Below are two links that show where these two fields come from. 

https://cloud.google.com/alloydb/docs/reference/rest/v1/projects.locations.clusters.instances
https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#DatabaseFlags

Does this make sense?

**Comment by rileykarson** [comment]
As @edwardmedia mentioned, this matches differences between the APIs.
