### ISSUE TITLE
Enhance google_identity_platform_config to allow more settings to be handled via Terraform

### ISSUE THREAD

**Issue by scretu** [hashicorp/terraform-provider-google#14194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As I'm building GCP projects via Terraform, using the `google_project` resource, I also want to enable some APIs and features. One of the APIs is `identitytoolkit` and I need to be able to enable and configure it as well.

For example:
- in the `Settings/USERS` section, https://console.cloud.google.com/customer-identity/settings?project=<project_name> I have to manually uncheck "Enable create (sign-up)" and manually check Enable for "User activity logging"
- in the `Settings/SECURITY` section, adding "Authorized Domains" is also a manual job

Could the above settings be automated via Terraform? Thanks!

### New or Affected Resource(s)

* google_identity_platform_config

b/299600943

**Comment by gleichda** [comment]
@hao-nan-li The requirements from the initial comment are fulfilled thus I guess this one can be closed
