### ISSUE TITLE
Adding support for enabling and configuring MFA in Google Identity Platform

### ISSUE THREAD

**Issue by scretu** [hashicorp/terraform-provider-google#14192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As I'm building GCP projects via Terraform, using the `google_project` resource, I also want to enable some APIs and features. One of the APIs is `identitytoolkit` and I need to be able to enable and configure `MFA` as well. 

As of now, I have to go manually to https://console.cloud.google.com/customer-identity/mfa?project=<project_name> in order to enable and configure it.

### New or Affected Resource(s)

* google_identity_platform_config

b/299600868

**Comment by loeffel-io** [comment]
+1
