### ISSUE TITLE
label change cause nodepool recreation in  google_container_node_pool resource

### ISSUE THREAD

**Issue by poligraph** [hashicorp/terraform-provider-google#14196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform v1.2.7
provider[registry.terraform.io/hashicorp/google] 4.58.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```
resource "google_container_node_pool" "nodepool" {
...
  node_config {
    labels = {
      service = "infra" # change to "prometheus" after creation
    }
  }
}
```

### Expected Behavior

update nodepool labels without recreation

### Actual Behavior
```
  # google_container_node_pool.nodepool["prometheus"] must be replaced

          ~ guest_accelerator = [] -> (known after apply)
          ~ labels            = { # forces replacement
              ~ "service" = "infra" -> "prometheus"
            }
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
dup of https://github.com/hashicorp/terraform-provider-google/issues/12620
