### ISSUE TITLE
Unexpected Recreate With GKE Clusters

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#14203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.9

### Affected Resource(s)

* `google_container_cluster`

### Terraform Configuration Files

```tf
# other config redeacted
ip_allocation_policy {
         cluster_ipv4_cidr_block       = "245.0.0.0/14"
         services_ipv4_cidr_block      = "245.4.0.0/20"
```

### Debug Output

```
# module.cluster.google_container_cluster.main must be replaced
      ~ ip_allocation_policy {
          ~ cluster_ipv4_cidr_block       = "245.0.0.0/14" -> (known after apply)
          ~ services_ipv4_cidr_block      = "245.4.0.0/20" -> (known after apply)
          + stack_type                    = "IPV4" # forces replacement
            # (2 unchanged attributes hidden)
        }

```

### Expected Behavior

New attribute `stack_type` (introduced by https://github.com/hashicorp/terraform-provider-google/pull/14079) should not cause a re-create in a resource/cluster where that value was not set previously. 

### Actual Behavior

This value not being set previously, along with the `forceNew` flag set on it, finally combined with how terraform thinks the lack of the value should be handled, is causing an unexpected recreate on clusters. As this wasn't a breaking change, this should not be occurring.

### Steps to Reproduce

1. Create `google_container_cluster` using previous version of provider
2. Run terraform plan/apply with new version of provider
3. Observe terraform attempting to re-create the entire cluster

### Important Factoids

Unknown

### References

https://github.com/hashicorp/terraform-provider-google/pull/14079
https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.60.0

**Comment by joe-a-t** [comment]
For people interested in this, please 👍 https://github.com/hashicorp/terraform-provider-google/issues/10168, which would help prevent this from happening again in the future

**Comment by joe-a-t** [comment]
@600lyy @shuyama1 re https://github.com/GoogleCloudPlatform/magic-modules/pull/7459

**Comment by shuyama1** [comment]
@joe-a-t Thanks for the ping! Apologize for the issue! Looking into it now. Please stick to the previous version before we have the fix out.

**Comment by edwardmedia** [comment]
It does look like introduced by https://github.com/hashicorp/terraform-provider-google/pull/14079

**Comment by joe-a-t** [comment]
Linking https://github.com/GoogleCloudPlatform/magic-modules/pull/7626 so people can track

**Comment by rileykarson** [comment]
Hmm- this shouldn't have been an issue. New fields with default values can cause exactly this issue sometimes, but I actually checked the logs on this and confirmed that clusters not specifying the feature received the default value: https://gist.github.com/rileykarson/c3156fdb5ff4ebc66594363ce66ff203

That means it's likely a second class of this issue that we're not able to reasonably detect- clusters created before a certain date (whatever date a feature flag got flipped internally) return null, and clusters created after that date properly return the default value.

**Comment by shuyama1** [comment]
Tried to reproduce this error locally: 
1. create the resource with 4.60.0 and terraform apply
2. create the resource with 4.59.0, upgrade to 4.60.0 and terraform apply

I couldn't repro the error in both cases, which means the error is likely from what @rileykarson stated above that "clusters created before a certain date (whatever date a feature flag got flipped internally) return null, and clusters created after that date properly return the default value."

**Comment by joe-a-t** [comment]
Our cluster was version `1.24.10-gke.2300` and original created probably 1.5-2 years ago and got destroyed by this (another plug for https://github.com/hashicorp/terraform-provider-google/issues/10168 to reduce the chance of such issues).

I opened 44319400 GCP support case to hopefully allow you to investigate the actual cluster and see the full Terraform plan that we had.

**Comment by rileykarson** [comment]
I've created a release branch and am running tests on it. Assuming there are no surprises a fix should go out as `4.60.1`  tomorrow before noon PST.

**Comment by rileykarson** [comment]
This will be a little later than I'd hoped, probably a little before 2:00pm PST. Reopening in the meantime to preempt duplicates.

**Comment by rileykarson** [comment]
`4.60.1` is out, which should resolve the issue. Sorry for the disruption, folks!
