### ISSUE TITLE
Cannot build/test locally due to missing/private dependency

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform-provider-google#14218]
# Background

# What kind of contribution is this issue about?

* local development (all)

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google/blob/b495ed16a91076e5288d9b0348e66a4423493348/scripts/diff.go#L12

# Details

Starting sometime in the last 2 weeks, it's no longer possible to `go mod tidy` or `go get` dependencies. The result is that fresh clones of the repository are unable to run tests locally.

This appears to be because the https://github.com/hashicorp/terraform-provider-clean-google repo was deleted or made private.

**Comment by sethvargo** [comment]
@rileykarson any ideas on this?

**Comment by rileykarson** [comment]
That repo's never actually existed, you can just delete the file and those commands work. I think we need to put it under a different Go module or something. FYI @slevenick if you could take a look?

**Comment by slevenick** [comment]
Yeah, that's not a real repo. In most use cases (go build, make) the contents of scripts/ aren't used, so I'm not sure why go mod tidy decides to try them. It would be great if we had the ability to prevent go mod tidy from trying to read them.

`go get` should still work though, are you seeing errors on that specifically? I'm able to run `go get` from HEAD

**Comment by sethvargo** [comment]
Hey @rileykarson @slevenick thanks for the reply. Here's what I'm seeing on a fresh clone:

```text
$ git rev-parse HEAD
9d00efe585888c3c72fa705f8cb72a05fa2c4894

$ go version
go version go1.20.3 darwin/arm64

$ go mod tidy
go: finding module for package github.com/hashicorp/terraform-provider-clean-google/google
github.com/hashicorp/terraform-provider-google/scripts imports
	github.com/hashicorp/terraform-provider-clean-google/google: cannot find module providing package github.com/hashicorp/terraform-provider-clean-google/google: module github.com/hashicorp/terraform-provider-clean-google/google: git ls-remote -q origin in /Users/sethvargo/Development/go/pkg/mod/cache/vcs/8a09e4807c89e0e733077bc133bab61829d1c43ee508c409ab431169c786365f: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/hashicorp/terraform-provider-clean-google/' not found

$ go get ./...
github.com/hashicorp/terraform-provider-google/scripts imports
	github.com/hashicorp/terraform-provider-clean-google/google: cannot find module providing package github.com/hashicorp/terraform-provider-clean-google/google
```

**Comment by rileykarson** [comment]
Unusual! I see the following with `go version go1.19 darwin/arm64`:

```
rileykarson@rileykarson-macbookpro ~/go-workspace/src/github.com/hashicorp/terraform-provider-google
$ go mod tidy
go: finding module for package github.com/hashicorp/terraform-provider-clean-google/google
github.com/hashicorp/terraform-provider-google/scripts imports
	github.com/hashicorp/terraform-provider-clean-google/google: cannot find module providing package github.com/hashicorp/terraform-provider-clean-google/google: module github.com/hashicorp/terraform-provider-clean-google/google: git ls-remote -q origin in /Users/rileykarson/go-workspace/pkg/mod/cache/vcs/8a09e4807c89e0e733077bc133bab61829d1c43ee508c409ab431169c786365f: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

rileykarson@rileykarson-macbookpro ~/go-workspace/src/github.com/hashicorp/terraform-provider-google
$ go get
```

**Comment by bjmcdaniel** [comment]
This Continues to be an issue, no where can any references be found.  Any suggestions for a work around?

**Comment by melinath** [comment]
This should have been resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9145 - if you're still seeing this issue, please open a new ticket with details.
