### ISSUE TITLE
Support creation of linked BigQuery dataset on log analytics bucket

### ISSUE THREAD

**Issue by michaelbannister** [hashicorp/terraform-provider-google#14214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Log Analytics bucket support was added in #13934 but I couldn't find a way to create a linked BigQuery dataset other than using a local-exec provisioner to call gcloud like this:

```tf
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "gcloud logging links create log_analytics --bucket=${google_logging_project_bucket_config.log_analytics.bucket_id} --location=${google_logging_project_bucket_config.log_analytics.location} --project ${google_logging_project_bucket_config.log_analytics.project}"
  }
```

It'd be nice to be able to do this through Terraform and have it handle destruction correctly, too; currently if Terraform attempts to destroy the logging bucket after the link's created we get the error:
> Error deleting Logging Bucket Config "projects/<project>/locations/<location>/buckets/log-analytics": googleapi: Error 400: This bucket is used for advanced analytics and has an active link. The link must be deleted first before deleting the bucket

### New or Affected Resource(s)

* google_logging_project_bucket_config (probably?)

### Potential Terraform Configuration

```tf
resource "google_logging_project_bucket_config" "log_analytics" {
  project          = var.my_project
  location         = "eu"
  retention_days   = 30
  enable_analytics = true
  enable_linked_bigquery_dataset = true
  bucket_id        = "log_analytics"
}
```

### References

* #13934

**Comment by DrFaust92** [comment]
with how the api is structured this would be a dedicated resource and not part of the bucket config https://cloud.google.com/logging/docs/reference/v2/rest/v2/locations.buckets.links/create

**Comment by DrFaust92** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/7630
