### ISSUE TITLE
GKE Kubernetes Node Tags Attribute missing

### ISSUE THREAD

**Issue by tpcgold** [hashicorp/terraform-provider-google#14211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Add Node Tags as attributes to GKE Cluster

Google automatically assigns Network Tags for GKE Nodes but are not available as attributes in google_container_cluster.
Thus, it cannot be used for Firewall configuration. 

This is needed as e.g. if one is using GKE in Private Mode with Nginx one has to configure the firewall so the GKE Master CIDR range can access PORT 8443 of the NODES. 

This configuration is impossible with Terraform as we don't have the attribute for the Node TAGS. 
(one has to manually hardcode the auto-assigned name from Google as a workaround)

### New or Affected Resource(s)

* google_container_cluster

**Comment by alexbacchin-asx** [comment]
@tpcgold node network tags can be added to the node pool
