### ISSUE TITLE
Crashing bug with provider version 4.60.0

### ISSUE THREAD

**Issue by Bluestreak2k5** [hashicorp/terraform-provider-google#14217]
We have run into an crashing bug using atlantis, and multiple versions of Terraform. We've had to set the provider as such in our repos:

  required_providers {
    google      = ">=4.50.0, != 4.60.0"
    google-beta = ">=4.50.0, != 4.60.0"

running "/home/atlantis/.atlantis/bin/terraform1.1.5 plan -input=false -refresh -no-color -out \"*****.tfplan\"" in "*****": exit status 1
module.sql-db.null_resource.module_depends_on: Refreshing state... [id=5519311843549470282]
module.retool-db.null_resource.module_depends_on: Refreshing state... [id=1144844595048061793]
module.retool-staging-db.null_resource.module_depends_on: Refreshing state... [id=5249062550482559435]
module.gke.random_string.cluster_service_account_suffix: Refreshing state... [id=6mu3]

Error: Plugin did not respond

  with provider["registry.terraform.io/hashicorp/google"],
  on providers.tf line 19, in provider "google":
  19: provider "google" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-google_v4.60.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 11 [running]:
github.com/hashicorp/terraform-provider-google/google.GetBatchingConfig({0x36c0b18, 0xc000ddb4a0}, {{0x0, 0x0, 0x0}, {0x36c4ba8, 0x0}, 0x1}, 0xc00157c390)
	github.com/hashicorp/terraform-provider-google/google/framework_config.go:1406 +0x2a5
github.com/hashicorp/terraform-provider-google/google.(*frameworkProvider).LoadAndValidateFramework(_, {_, _}, {{0x2, {0xc000baea80, 0x90f}}, {0x0, {0x0, 0x0}}, {0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-provider-google/google/framework_config.go:58 +0x2f3
github.com/hashicorp/terraform-provider-google/google.(*frameworkProvider).Configure(0xc0001daa00, {0x36c0b18, 0xc000ddb4a0}, {{0xc00138e9f8, 0x5}, {{{0x36c7620, 0xc000e150e0}, {0x2c3ebc0, 0xc000df7ef0}}, {0x36c8b38, ...}}}, ...)
	github.com/hashicorp/terraform-provider-google/google/framework_provider.go:838 +0x22f
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ConfigureProvider(0xc00003c160, {0x36c0b18, 0xc000ddb4a0}, 0xc00157c400, 0xc00157c380)
	github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/fwserver/server_configureprovider.go:15 +0x10f
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ConfigureProvider(0xc00003c160, {0x36c0b18?, 0xc000ddb350?}, 0x3?)
	github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/proto5server/server_configureprovider.go:36 +0x292
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ConfigureProvider({0xc0009ff0e0, 0xc0009ff140, {0xc0010547e0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ConfigureProvider.go:25 +0x1b3
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).Configure(0xc000ba9860, {0x36c0b18?, 0xc000dda180?}, 0xc00157c040)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:556 +0x2ce
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_Configure_Handler({0x302d3a0?, 0xc000ba9860}, {0x36c0b18, 0xc000dda180}, 0xc00157e000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:331 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f501e0, {0x36c7900, 0xc0010bb040}, 0xc000f60360, 0xc0010b4ff0, 0x498d0d8, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc000f501e0, {0x36c7900, 0xc0010bb040}, 0xc000f60360, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-google_v4.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by supersmo** [comment]
I was just about to report the same.
In my case I narrowed it down to configuring the provider with batch.
Do you happen to use the same?

This minimal terraform config causes the crash for me:
```
terraform {
  required_version = "== 1.4.4"
  required_providers {
    google = {
      version = "4.60.0"
    }
    google-beta = {
      version = "4.60.0"
    }
  }
}

provider "google" {
    batching {
      enable_batching = true
      send_after      = "10s"
    }
}

provider "google-beta" {
    batching {
      enable_batching = true
      send_after      = "10s"
    }
}

resource "google_project_iam_member" "object_viewer" {
  member  = "user:some_user@something.com"
  project = "some_project_id"
  role    = "roles/storage.objectViewer"
}
```
Running the plan with google provider 4.60.0 causes the crash.
4.59.0 works.

**Comment by edwardmedia** [comment]
I can repro this. The crash only happens on v4.60.0. It is fine with v4.59.0

**Comment by rileykarson** [comment]
Assuming there are no unanticipated issues, this should go out in `4.60.2` tomorrow at some point.
