### ISSUE TITLE
Provide explanation/link on the use of "%{random_suffix}" in a resource name.

### ISSUE THREAD

**Issue by kurtkanaskie** [hashicorp/terraform-provider-google#14236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.60.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_apigee_environment 
* google_apigee_envgroup
* google_apigee_instance
* google_apigee_instance_attachment
* many others in general

### Terraform Configuration Files

```tf
name                  = "instance-name-%{random_suffix}"
```

### Actual Behavior

Error
```
╷
│ Error: Invalid template control keyword
│ 
│   on main.tf line 98, in resource "google_compute_region_network_endpoint_group" "tf_psc_neg_us_east1":
│   98:   name                  = "psc-neg-us-east1-%{random_suffix}"
│ 
│ "random_suffix" is not a valid template control keyword.
```

### Steps to Reproduce

1. Create a resource using %{random_suffix}
```
resource "google_compute_region_network_endpoint_group" "tf_psc_neg_us_east1" {
  name                  = "psc-neg-us-east1-%{random_suffix}"
```
3. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Configurations are reused between tests and examples. These are artifacts from folks copying what should be test-only configuration into the source sample- it's invalid Terraform code, and tests substitute a randomized suffix in its place. Seems like there are 78 cases across 34 files.

@edwardmedia this wouldn't be a bad idea for you to clean up if you have the cycles!

**Comment by edwardmedia** [comment]
I do see this in 78 cases in 34 doc files. Let me clean them up @rileykarson

**Comment by kurtkanaskie** [comment]
What I've done to acheive the same is to use:
```
resource "random_id" "random_suffix" {
  byte_length = 4
}

resource "google_compute_region_network_endpoint_group" "tf_psc_neg_us_east1" {
  name                  = "tf-psc-neg-us-east1-${lower(random_id.random_suffix.hex)}"
...
}
output "apigee_neg_name" {
  value = google_compute_region_network_endpoint_group.tf_psc_neg_us_east1.name
}
```
Which results in an output:
apigee_neg_name = "tf-psc-neg-us-east1-d6f6243e"
