### ISSUE TITLE
VPN forced replacement

### ISSUE THREAD

**Issue by Maarc-D** [hashicorp/terraform-provider-google#14264]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If this is a bug report (for when something is there, but doesn't work how it should), please use the [bug issue template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md) instead.

If this is an enhancement / feature request (for when something (a resource, field, etc.) is missing, and should be added), please use the [enhancement template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md) instead.

If you have a support request or question, please check out the other resources listed [here](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md).

If your issue does not fit into one of the above templates, please fill out the following:

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
All terraform versions
Google provider version : 4.61.0

### Affected Resource(s)

google_compute_ha_vpn_gateway

### Terraform Configuration Files (if applicable)

```tf
resource "google_compute_ha_vpn_gateway" "onprem" {
  for_each = google_compute_network.this
  region   = var.region
  project  = local.account_ids[terraform.workspace]
  name     = "vpn-worldline-onprem-${lower(terraform.workspace)}"
  network  = each.value.id
  # stack_type = "IPV4_ONLY" # same issue with IPV4_IPV6
}
```

### Issue Description

No matter which `stack_type` we put it force gateway replacement so tunnels too.

```tf
-/+ resource "google_compute_ha_vpn_gateway" "onprem" {
      ~ id         = "projects/myproject/regions/europe-west1/vpnGateways/vpn" -> (known after apply)
        name       = "vpn"
      ~ network    = "https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc-myproject" -> "projects/myproject/global/networks/vpc-myproject"
      ~ self_link  = "https://www.googleapis.com/compute/v1/projects/myproject/regions/europe-west1/vpnGateways/vpn" -> (known after apply)
      + stack_type = "IPV4_ONLY" # forces replacement
```

```tf
-/+ resource "google_compute_ha_vpn_gateway" "onprem" {
      ~ id         = "projects/myproject/regions/europe-west1/vpnGateways/vpn" -> (known after apply)
        name       = "vpn"
      ~ network    = "https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc-myproject" -> "projects/myproject/global/networks/vpc-myproject"
      ~ self_link  = "https://www.googleapis.com/compute/v1/projects/myproject/regions/europe-west1/vpnGateways/vpn" -> (known after apply)
      + stack_type = "IPV4_IPV6" # forces replacement
```

### References

* #0000

**Comment by Maarc-D** [comment]
For me the refresh must get the current value of the attribut `stack_type`

**Comment by Maarc-D** [comment]
I tried to pull my state edit it add the stack_type attribute manually
![image](https://user-images.githubusercontent.com/62051944/231105785-a908537c-009e-4ca5-aa1b-d654a2a560e9.png)
, push it 
try a new plan but did not resolve it, the attribut it still in my state after the refresh but still want to recreate the gateway

**Comment by Maarc-D** [comment]
After looking to the code : https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_ha_vpn_gateway.go seems that there is no Update method, that could explain why we have trouble here no ?

**Comment by edwardmedia** [comment]
On different resource https://github.com/hashicorp/terraform-provider-google/issues/14203

**Comment by edwardmedia** [comment]
@Maarc-D I have tested on below config, and couldn't repro the issue. Could you provide the steps to repro? 

```tf
resource "google_compute_ha_vpn_gateway" "ha_gateway1" {
  region   = "us-central1"
  name     = "issue14264"
  network  = google_compute_network.network1.id
  stack_type = "IPV4_IPV6"
}

resource "google_compute_network" "network1" {
  name                    = "issue14264"
  auto_create_subnetworks = false
}

resource "google_compute_ha_vpn_gateway" "ha_gateway2" {
  region   = "us-central1"
  name     = "issue14264-2"
  network  = google_compute_network.network1.id
  stack_type = "IPV4_ONLY"
}
```

**Comment by komalkanth** [comment]
@edwardmedia I can't confirm it's the exact issue we're seeing but all the symptoms are there. In our case the VPNs are deployed with 0.12.24 and the plan shows all the VPNs and the gateways being replaced when trying with 0.13.7

**Comment by edwardmedia** [comment]
I do see `stack_type` was introduced by https://github.com/hashicorp/terraform-provider-google/pull/14141 in v4.61.0. Similar to https://github.com/hashicorp/terraform-provider-google/issues/14203

**Comment by komalkanth** [comment]
I can confirm that I don't see the gateways and VPNs being replaced if I hard code my provider version to before v4.61.0.

**Comment by trodge** [comment]
This resource does not have an update method in the API, so any changes require recreating the resource. Specifying a field that was previously unspecified is a change from Terraform's perspective.

**Comment by rileykarson** [comment]
@trodge: This may be the same issue as https://github.com/hashicorp/terraform-provider-google/issues/14203, sometimes APIs return nothing (i.e. null) for resources created before an arbitrary date. This happens when services don't backfill new fields they introduce. `default_if_empty` or the approach taken there are appropriate if that's the case.

**Comment by rileykarson** [comment]
@trodge we may want to cherrypick this one, it's a perma-destroy: https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process#when-to-cherry-pick

**Comment by cschroer** [comment]
@rileykarson / @trodge is there any reason this was not included in yesterdays 4.62 release?

We are using this resource a lot, and we currently need to nail our provider version to <=4.60 to prevent a lot of infrastructure recreation.

**Comment by rileykarson** [comment]
None I'm aware of. FYI @trodge, also FYI @SarahFrench as current BOD.

**Comment by SarahFrench** [comment]
This has been released in :

**Comment by cschroer** [comment]
Thanks a lot! :)
