### ISSUE TITLE
Add source_snapshot to google_workstations_workstation_config resource

### ISSUE THREAD

**Issue by mcinquin** [hashicorp/terraform-provider-google#14265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the Google Cloud Workstation API reference, there is a new field in the WorkstationConfig object to control the Persistent Directory.
`source_snapshot` defines a snapshot that can be used as a source for creating the persistent disk.

Currently, this field is missing from the related Terraform resource.

Documentation:
https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs#PersistentDirectory

### New or Affected Resource(s)

* google_workstations_workstation_config

### Potential Terraform Configuration

```tf
resource "google_workstations_workstation_config" "default" {
  provider               = google-beta
  workstation_config_id  = "workstation-config"
  workstation_cluster_id = google_workstations_workstation_cluster.default.workstation_cluster_id
  location               = "us-central1"

  host {
    gce_instance {
      machine_type                = "e2-standard-4"
      boot_disk_size_gb           = 35
      disable_public_ip_addresses = true
      shielded_instance_config {
        enable_secure_boot = true
        enable_vtpm        = true
      }
    }
  }

  persistent_directories {
    mount_path = "/home"
    gce_pd {
      size_gb         = 200
      source_snapshot = "projects/{{project}}/global/snapshots/{{name}}"
      reclaim_policy  = "DELETE"
    }
  }
}
```

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7893
