### ISSUE TITLE
Remove native project owner after project creation

### ISSUE THREAD

**Issue by cah-douglas-short** [hashicorp/terraform-provider-google#14278]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

I'm researching best practice in how to handle this sort of issue. The scenario goes like this. 

- GCP Project creation is limited to a specific GCP Service Account that uses Cloudbuild to deploy the project, using a customized Terraform module
- As a result, the service account deploying the project becomes the default project owner

The request is to modify the Terraform module to remove the service account from the project owner role after the project is successfully deployed. The reason for this request is that projects are failing compliance auditing in my org for having too permissive permissions with respect to project owners. 

I can use a gcloud command to remove the IAM binding, but I'm looking for a better method that would not require using a gcloud command, and could be incorporated into the Cloudbuild pipeline. 

** Edit, it's just occurred to me that I could write a step into Cloudbuild to do this, which might be the easiest solution. I'm looking for a Terraform method if it exists.

**Comment by edwardmedia** [comment]
@cah-douglas-short terraform is more Declarative. In your case, you might need Imperative tool. Adding a step in the pipeline could be a good choice. I do not think of a way in terraform that can natively handle this.

**Comment by cah-douglas-short** [comment]
Thanks for the response Edward, much appreciated.
