### ISSUE TITLE
Add support for Distributed Edge Cloud

### ISSUE THREAD

**Issue by benfogel** [hashicorp/terraform-provider-google#14275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for Distributed Edge Cloud Container Resources https://cloud.google.com/distributed-cloud/edge/ to provision and manage cluster, node-pool, and vpn connection resources.

### New or Affected Resource(s)

* google_edgecontainer_cluster
* google_edgecontainer_node_pool
* google_edgecontainer_vpn_connection

### References

* https://cloud.google.com/distributed-cloud/edge/latest/docs/reference/container/rest/v1/projects.locations.clusters
* https://cloud.google.com/distributed-cloud/edge/latest/docs/reference/container/rest/v1/projects.locations.clusters.nodePools
* https://cloud.google.com/distributed-cloud/edge/latest/docs/reference/container/rest/v1/projects.locations.vpnConnections

**Comment by roaks3** [comment]
Fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8777
