### ISSUE TITLE
Since 4.59.0, data "google_container_cluster" wants containers api to be enable in the project even if the GKE is not in the project.

### ISSUE THREAD

**Issue by lchastel** [hashicorp/terraform-provider-google#14286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Context
I have a GKE that is used for several applications, in a GCP project "my-gke-project".

Each application has its own GCP project "my-project" and its own terraform code.
In "my-project", 
* I need to get details on the GKE so I use data "google_container_cluster" ... (with project = "my-gke-project")
* The containers api is not enabled in "my-project", because the project is not containing a GKE.

Since version 4.59.0, terraform plan failed indicating the containers api need to be enabled in "my-project".
Why do I need to enable it ?

In 4.58.0, I don't need to enable the containers api in "my-project".

### Terraform Version

Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.59.0
+ provider registry.terraform.io/hashicorp/google-beta v4.59.0

### Affected Resource(s)
data google_container_cluster

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.4"
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "4.59.0"
    }
    google-beta = {
      source = "hashicorp/google-beta"
      version = "4.59.0"
    }
  }
}

provider "google" {
  project = "my-project"
  region  = "europe-west3"
}


data "google_container_cluster" "gke" {
  name     = "my-gke"
  location = "europe-west3-a"
  project  = "my-gke-project"
}
```

### Panic Output

```
terraform init --upgrade   => succesfull

 terraform plan
data.google_container_cluster.gke: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error when reading or editing Container Cluster "my-gke": googleapi: Error 403: Kubernetes Engine API has not been used in project XXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=XXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.Help",
│     "links": [
│       {
│         "description": "Google developers console API activation",
│         "url": "https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=XXXXXX"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/XXXXXX",
│       "service": "container.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ , accessNotConfigured
│
│   with data.google_container_cluster.gke,
│   on app.tf line 21, in data "google_container_cluster" "gke":
│   21: data "google_container_cluster" "gke" {
│
╵
```
XXXXXX is the project number of "my-project".

### Expected Behavior
I should not need to enable containers api in the project that is not creating the GKE.

### Actual Behavior
The provider want containers api to be enabled in the project that is not creating the GKE.

If I enable it, I don't have the issue.
But I don't understand why I need to enable it, I'm specify the project in the data object declaration.

### Steps to Reproduce

1. Create a project with a GKE. (so containers api needs to be enabled in this project)  => my-gke-project"
2. Create a 2nd project  "my-project"
3. Copy the code in app.tf.
4. `terraform init`
5. `terraform plan`

### Important Factoids
I'm using an account which is owner of the both projects (my-gke-project and my-project)

### References
N/A

### Workarounds
* Enable containers api in my-project
* Use google provider 4.58.0.

**Comment by edwardmedia** [comment]
@lchastel just curious, how do you expect the data source `google_container_cluster` working when there is no cluster available in the project?

**Comment by edwardmedia** [comment]
@lchastel help me to understand, in below config, did you say it is expected to work when the api is not enabled in the project of `my-gke-project`?

```tf
data "google_container_cluster" "gke" {
  name     = "my-gke"
  location = "europe-west3-a"
  project  = "my-gke-project"
}
```

**Comment by lchastel** [comment]
Container API is enabled on my-gke-project, but not on my-project.

I want to create/update items in my-project => so I set  project to "my-project" in provider "google"
And I need to get details on GKE from my-gke-project, to use them in the items I want to create in my-project.
So I use a datasource "google_container_cluster" specify project = "my-gke-project"

And until version 4.58.0 it was working fine.
Now terraform plan failed indicating, it need container api to be enable in my-project.

**Comment by edwardmedia** [comment]
@lchastel  using the [exact](https://github.com/hashicorp/terraform-provider-google/issues/14286#issue-1664228684) config, I can't repro the issue. I guess I need below piece so I can the issue. Mind sharing what to do to `use them in the items I want to create in my-projec`?

```
And I need to get details on GKE from my-gke-project, to use them in the items I want to create in my-project.
```

**Comment by lchastel** [comment]
I made a new test this morning with terraform 1.4.6 and google provider 4.63.1.
The issue is not present anymore.

I confirm the closure of the ticket.
