### ISSUE TITLE
Google Secret Manager 'automatic' replication should support customer_managed_encryption

### ISSUE THREAD

**Issue by kutysam** [hashicorp/terraform-provider-google#14282]
Based on google documentation, we are supposed to be able to create
1. An automated replication for a secret
2. Customer Managed Encryption for this automated replication.
https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets#automatic

```
{
  "customerManagedEncryption": {
    object ([CustomerManagedEncryption](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets#CustomerManagedEncryption))
  }
}
```

However, terraform only allows a boolean for automatic and does not allow any options.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#automatic

### Terraform Version

Using google 4.60.1 and tf 1.3.7

### Affected Resource(s)

* google_secret_manager_secret

### Expected Behavior

```
resource "google_secret_manager_secret" "helloworld" {
  secret_id = "helloworld_api_key"

  replication {
    automatic {
      customer_managed_encryption {
        kms_key_name = "helloworld_kms_key"
      }
    }
}
```

The above should be acceptable but  this error happens as it is expecting automatic = true
Error
```
│ Blocks of type "automatic" are not expected here. Did you mean to define argument "automatic"? If so, use the equals sign to assign it a value.```

b/299601054

**Comment by edwardmedia** [comment]
I see the diff here.  The type for automatic is [bool](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_secret_manager_secret.go#L54) in the provider while it is a [object](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets#Automatic) in the api. I believe the api has updated its schema. 

Changed the label to enhancement instead

**Comment by kutysam** [comment]
Alright, i guess its an 'enhancement' as the current flow isn't breaking anything. Thankfully it allows itself to be important without any further modifications to the state when applied.
