### ISSUE TITLE
Missing field customContentType for uptime checks

### ISSUE THREAD

**Issue by costis** [hashicorp/terraform-provider-google#14285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The google_monitoring_uptime_check_config resource doesn't support the field customContentType for http_check

### New or Affected Resource(s)

* google_monitoring_uptime_check_config

### Potential Terraform Configuration

```tf
resource "google_monitoring_uptime_check_config" "check" {
  display_name = "example uptime check"
  timeout      = "60s"
  project      = var.project_id

  http_check {
    request_method    = "POST"
    content_type      = "USER_PROVIDED"
    customContentType = "application/json"
    path              = "/messages"
    port              = "443"
    use_ssl           = "true"
    validate_ssl      = "true"
    body              = jsonencode({ "message" = "hello" })

    accepted_response_status_codes {
      status_class = "STATUS_CLASS_2XX"
    }
  }

  monitored_resource {
    type   = "uptime_url"
    labels = {
      "project_id" = var.project_id
      "host"       = var.host
    }
  }
}

```

### References

See Google documentation:
* https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#HttpCheck.FIELDS.custom_content_type

b/299683580

**Comment by DrFaust92** [comment]
looking into it

**Comment by birnazarova2** [comment]
Is there any update on this? I needed to create an uptime check with `application/json` content-type, but looks like it is still not supported.

**Comment by jgacek-baracoda** [comment]
Same for me - it's not possible to create proper uptime check by terraform.
I ended up creating many uptime checks and manually changing content-type to application/json as my app doesn't support urlencoded.

**Comment by jdurelli** [comment]
I will create a PR for this and some similar issues
