### ISSUE TITLE
Data source google_dns_keys broken in > version 4.59

### ISSUE THREAD

**Issue by YuriyKishchenko** [hashicorp/terraform-provider-google#14298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* data.google_dns_keys

### Terraform Configuration Files

The following code that is copied [from the documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/dns_keys) works with provider version <= 4.59, but fails with newer versions
```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.61.0"
    }
  }
}

provider "google" {
}

resource "google_dns_managed_zone" "foo" {
  name     = "foobar"
  dns_name = "foo.bar."

  dnssec_config {
    state         = "on"
    non_existence = "nsec3"
  }
}

data "google_dns_keys" "foo_dns_keys" {
  managed_zone = google_dns_managed_zone.foo.id
}

output "foo_dns_ds_record" {
  description = "DS record of the foo subdomain."
  value       = data.google_dns_keys.foo_dns_keys.key_signing_keys[0].ds_record
}

```

### Expected Behavior

Terraform plan on provider version 4.59.0 produces the output (expected):

```
  # data.google_dns_keys.foo_dns_keys will be read during apply
  # (config refers to values not yet known)
 <= data "google_dns_keys" "foo_dns_keys" {
      + id                = (known after apply)
      + key_signing_keys  = (known after apply)
      + managed_zone      = (known after apply)
      + project           = (known after apply)
      + zone_signing_keys = (known after apply)
    }

  # google_dns_managed_zone.foo will be created
  + resource "google_dns_managed_zone" "foo" {
      + creation_time   = (known after apply)
      + description     = "Managed by Terraform"
      + dns_name        = "foo.bar."
      + force_destroy   = false
      + id              = (known after apply)
      + managed_zone_id = (known after apply)
      + name            = "foobar"
      + name_servers    = (known after apply)
      + project         = (known after apply)
      + visibility      = "public"

      + cloud_logging_config {
          + enable_logging = (known after apply)
        }

      + dnssec_config {
          + kind          = "dns#managedZoneDnsSecConfig"
          + non_existence = "nsec3"
          + state         = "on"

          + default_key_specs {
              + algorithm  = (known after apply)
              + key_length = (known after apply)
              + key_type   = (known after apply)
              + kind       = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + foo_dns_ds_record = (known after apply)

```

### Actual Behavior

Terraform plan on provider version 4.61.0 produces the error:
```
╷
│ Error: Invalid index
│
│   on main.tf line 30, in output "foo_dns_ds_record":
│   30:   value       = data.google_dns_keys.foo_dns_keys.key_signing_keys[0].ds_record
│     ├────────────────
│     │ data.google_dns_keys.foo_dns_keys.key_signing_keys is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by ayush-jain1** [comment]
+1 facing same issue, we pinned the provider to 4.59.0 to over come this

**Comment by edwardmedia** [comment]
@YuriyKishchenko using your config [here](https://github.com/hashicorp/terraform-provider-google/issues/14298#issue-1666101973), I can't repro the issue. I have tried both v4.59.0 and v4.61.0 which are fine. 

Can you detail the steps to repro?

**Comment by edwardmedia** [comment]
Below are two plans for `google_dns_keys` from different versions. Two attributes are missing from v4.61.0.

from v4.59.0
```
 <= data "google_dns_keys" "foo_dns_keys" {
      + id                = (known after apply)
      + key_signing_keys  = (known after apply)
      + managed_zone      = (known after apply)
      + project           = (known after apply)
      + zone_signing_keys = (known after apply)
    }
```

v4.61.0
```
 <= data "google_dns_keys" "foo_dns_keys" {
      + id           = (known after apply)
      + managed_zone = (known after apply)
      + project      = (known after apply)
    }
```
