### ISSUE TITLE
google_spanner_instance and google_spanner_database is deleted even if google_spanner_database.deletion_protection = true

### ISSUE THREAD

**Issue by nktks** [hashicorp/terraform-provider-google#14296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.61.0
```

### Affected Resource(s)

* google_spanner_instance
* google_spanner_database

### Terraform Configuration Files

First, already `terraform apply` is applied to below resources:
```tf
resource "google_spanner_instance" "delete-test" {
  config           = "regional-asia-northeast1"
  display_name     = "delete-test"
  name             = "delete-test"
  processing_units = 100
  project          = var.project_id
}

resource "google_spanner_database" "delete-test" {
  project                  = var.project_id
  instance                 = "delete-test"
  name                     = "delete-test"
  version_retention_period = "3d"
  deletion_protection      = true
}
```

confirm created resources
```
gcloud spanner instances list --project $GCP_PROJECT
NAME                            DISPLAY_NAME                    CONFIG                    NODE_COUNT  PROCESSING_UNITS  STATE  INSTANCE_TYPE
delete-test                     delete-test                     regional-asia-northeast1              100               READY  PROVISIONED
gcloud spanner databases list --instance=delete-test --project $GCP_PROJECT
NAME         STATE  VERSION_RETENTION_PERIOD  EARLIEST_VERSION_TIME        KMS_KEY_NAME
delete-test  READY  3d                        2023-04-13T09:05:24.793309Z
```

and comment out above resources and execute `terraform apply`.

### Debug Output

`terraform apply` outputs (partially)
```
google_spanner_instance.delete-test: Destroying... [id=<project_id>/delete-test]
google_spanner_database.delete-test: Destroying... [id=delete-test/delete-test]
google_spanner_instance.delete-test: Still destroying... [id=<project_id>/delete-test, 10s elapsed]
google_spanner_instance.delete-test: Destruction complete after 16s
╷
│ Error: cannot destroy instance without setting deletion_protection=false and running `terraform apply`
```
This seems to have prevented deletion at first glance, but acutually `delete-test` instance is deleted.
```
gcloud spanner instances list --project $GCP_PROJECT
NAME                            DISPLAY_NAME                    CONFIG                    NODE_COUNT  PROCESSING_UNITS  STATE  INSTANCE_TYPE
```

### Expected Behavior

After `terraform apply`, `gcloud spanner instances list --project $GCP_PROJECT` returns `delete-test` instance.

### Actual Behavior

`delete-test` instance is deleted.
```
gcloud spanner instances list --project $GCP_PROJECT
NAME                            DISPLAY_NAME                    CONFIG                    NODE_COUNT  PROCESSING_UNITS  STATE  INSTANCE_TYPE
```

### Steps to Reproduce

- First,  create these resources.
```tf
resource "google_spanner_instance" "delete-test" {
  config           = "regional-asia-northeast1"
  display_name     = "delete-test"
  name             = "delete-test"
  processing_units = 100
  project          = var.project_id
}

resource "google_spanner_database" "delete-test" {
  project                  = var.project_id
  instance                 = "delete-test"
  name                     = "delete-test"
  version_retention_period = "3d"
  deletion_protection      = true
}
```
- execute `terraform apply`
- and got errors ( this is expected, I know we can avoid to use depends_on, I dare to do this so that there are no dependencies between resources)
```
│ Error: Error creating Database: googleapi: Error 404: Instance not found: projects/$project_id/instances/delete-test
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ResourceInfo",
│     "description": "Instance does not exist.",
│     "resourceName": "projects/$project_id/instances/delete-test",
│     "resourceType": "type.googleapis.com/google.spanner.admin.instance.v1.Instance"
│   }
│ ]
│
│   with google_spanner_database.delete-test,
│   on spanner_test.tf line 9, in resource "google_spanner_database" "delete-test":
│    9: resource "google_spanner_database" "delete-test" {
```
- re execute `terraform apply` and this was succeeded
- confirm created resources
```
gcloud spanner instances list --project $GCP_PROJECT
NAME                            DISPLAY_NAME                    CONFIG                    NODE_COUNT  PROCESSING_UNITS  STATE  INSTANCE_TYPE
delete-test                     delete-test                     regional-asia-northeast1              100               READY  PROVISIONED
gcloud spanner databases list --instance=delete-test --project $GCP_PROJECT
NAME         STATE  VERSION_RETENTION_PERIOD  EARLIEST_VERSION_TIME        KMS_KEY_NAME
delete-test  READY  3d                        2023-04-13T09:05:24.793309Z
```
- comment out these resources like this
```tf
# resource "google_spanner_instance" "delete-test" {
#   config           = "regional-asia-northeast1"
#   display_name     = "delete-test"
#   name             = "delete-test"
#   processing_units = 100
#   project          = var.project_id
# }
#
# resource "google_spanner_database" "delete-test" {
#   project                  = var.project_id
#   instance                 = "delete-test"
#   name                     = "delete-test"
#   version_retention_period = "3d"
#   deletion_protection      = true
# }
```
- execute `terraform apply` and we got error
```
google_spanner_instance.delete-test: Destroying... [id=<project_id>/delete-test]
google_spanner_database.delete-test: Destroying... [id=delete-test/delete-test]
google_spanner_instance.delete-test: Still destroying... [id=<project_id>/delete-test, 10s elapsed]
google_spanner_instance.delete-test: Destruction complete after 16s
╷
│ Error: cannot destroy instance without setting deletion_protection=false and running `terraform apply`
```
- but these resources was deleted actually.
```
gcloud spanner instances list --project $GCP_PROJECT
NAME                            DISPLAY_NAME                    CONFIG                    NODE_COUNT  PROCESSING_UNITS  STATE  INSTANCE_TYPE
```

### References
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#deletion_protection
> (Optional) Whether or not to allow Terraform to destroy the instance. Unless this field is set to false in Terraform state, a terraform destroy or terraform apply that would delete the instance will fail.

**Comment by nktks** [comment]
@edwardmedia Thank you for confirming this.

> Did you apply after you set deletion_protection to true before you start your mentioned steps? If yes, please details the steps to repro the issue.

Yes. 
And I updated `Steps to Reproduce`  about details the steps to repro the issue.
Please confirm this.

**Comment by edwardmedia** [comment]
@nktks I see you have protection on the database but not on the instance, and you don't have the dependency between two. When you triggered `destroy`, terraform destroyed them independently, which resulted in the instance was successfully deleted, while terraform client received the protection error on the database. 

I am not sure if there is a better to force the execution of two resources in certain order internally besides users explicitly to set it.  Have you tied adding depend_on?

**Comment by nktks** [comment]
@edwardmedia 

> Have you tried adding depend_on?

Yes.  When I tried below resources,  `deletion_protection` works as expected
```tf
resource "google_spanner_instance" "delete-test" {
  config           = "regional-asia-northeast1"
  display_name     = "delete-test"
  name             = "delete-test"
  processing_units = 100
  project          = var.project_id
  force_destroy    = false
}

resource "google_spanner_database" "delete-test" {
  project                  = var.project_id
  instance                 = google_spanner_instance.delete-test.name
  name                     = "delete-test"
  version_retention_period = "3d"
  deletion_protection      = true
}
```

In conclusion, does `deletion_protection` work only when `google_spanner_database` resource depends on `google_spanner_instance` resource, right?

I think that if the [document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#deletion_protection) contains about this, it will help the user not to accidentally define resources individually.

But my question is cleared. Thank you for your help.

**Comment by edwardmedia** [comment]
@nktks I would say `deletion_protection` only works on individual resource, which blocks the DELETE request on the specific api. It does not cover if the resource is destroyed by other means. 

Closing the issue now. Thanks
