### ISSUE TITLE
Duplicate fields in Magic Modules YAML definitions

### ISSUE THREAD

**Issue by oguzhanakan0** [hashicorp/terraform-provider-google#14308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.5
on darwin_arm64
```

### Affected Resource(s)

* compute_packet_mirroring
* compute_url_map

### Debug Output

compute/PacketMirroring.yaml
```
panic: yaml: unmarshal errors:
  line 126: mapping key "name" already defined at line 121
  line 127: mapping key "description" already defined at line 123
````
compute/UrlMap.yaml
```
panic: yaml: unmarshal errors:
  line 2028: mapping key "custom_expand" already defined at line 2022
  line 2152: mapping key "default_from_api" already defined at line 2138
  line 2269: mapping key "custom_expand" already defined at line 2264
```
### Expected Behavior

Not having duplicate fields.

### Actual Behavior

There are duplicate fields.

### Steps to Reproduce

No steps required.

### References

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/PacketMirroring.yaml#L121-L127

**Comment by rileykarson** [comment]
fyi @trodge

**Comment by c2thorn** [comment]
Looks like @trodge already resolved this when they formatted the YAML files. For example: https://github.com/GoogleCloudPlatform/magic-modules/pull/7786/files#diff-bae55e57d0b0c41446f016c3c142ffd1201e58ddd19ddac79c9561c249f40c65L126
