### ISSUE TITLE
Failing test(s): TestAccSqlDatabaseInstance clone

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#14305]
### Failure rates

- 6% in Mar 2023

### Impacted tests

- TestAccSqlDatabaseInstance_basicClone
- TestAccSqlDatabaseInstance_cloneWithSettings

### Affected Resource(s)

* google_sql_database_instance

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=388396&tab=buildResultsDiv&buildTypeId=GoogleCloud_ProviderGoogleCloudGoogleProject#testNameId1228032783000337365)

### Message(s)

```
=== RUN   TestAccSqlDatabaseInstance_basicClone
=== PAUSE TestAccSqlDatabaseInstance_basicClone
=== CONT  TestAccSqlDatabaseInstance_basicClone
    vcr_utils.go:144: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error, failed to create instance tf-test-wdhvfzhlqm: googleapi: Error 400: A successful backup that's required for carrying out the CLONE operation can't be found, or a backup that was created before the restored timestamp can't be found. Modify the ID or timestamp for the backup., errorBackupNotFound
        
          with google_sql_database_instance.instance,
          on terraform_plugin_test.tf line 2, in resource "google_sql_database_instance" "instance":
           2: resource "google_sql_database_instance" "instance" {
        
--- FAIL: TestAccSqlDatabaseInstance_basicClone (4.83s)
FAIL
```

**Comment by roaks3** [comment]
This issue might have been resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7602, but I've opened it for us to monitor

**Comment by melinath** [comment]
seems like this is now passing consistently: https://ci-oss.hashicorp.engineering/test/1228032783000337365?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true
