### ISSUE TITLE
Explicitly disabling autoclass seems to cause the resource to be replaced on all succeeding `terraform plan` / `apply`

### ISSUE THREAD

**Issue by SahandJ** [hashicorp/terraform-provider-google#14319]
We have a few buckets with autoclass enabled as such:

```hcl
resource google_storage_bucket "my_bucket" {
    ...
    autoclass {
        enabled = true
    }
}
```
However we realised that these buckets should have autoclass enabled conditionally. We solved this by using a variable that we provide when declaring the module:

```hcl

variable "autoclass_enabled" {
  type = bool
}

...

resource google_storage_bucket "my_bucket" {
    ...
    autoclass {
        enabled = var.autoclass_enabled
    }
}
```
This correctly replaced the bucket and disabled autoclass. 
However when running `terraform plan` again, with no other relevant changes (other resource that were created, not relevant to this bucket) the bucket needs to be replaced:

```text
 + autoclass { # forces replacement
      + enabled = false # forces replacement
    }
```

I checked the state-file using `terraform show` and found the resource and saw this:
```hcl
{
    "address": "module.gcs.google_storage_bucket.my_bucket",
    ...
    "values": {
        "autoclass": [],
        ...
    }
}
```
I then used `terraform plan -out planfile` and `terraform show -json planfile` and compared it with the state and saw this:
```hcl
{
    "address": "module.gcs.google_storage_bucket.my_bucket",
    ...
    "values": {
        "autoclass": [
            {
                "enabled": false
            }
        ],           
        ...
    }
}
```

It looks like to me that disabling autoclass caused terraform to completely remove the block from the state. This causes the explicit `enabled = false` auto-class block to clash with the current state. This is not at all what I expected, and we cannot just recreate the bucket whenever we want to run our terraform scripts (as this would either fail, or delete all objects within the bucket based on whether `force-destroy` is enabled or not).

Is this expected behaviour or a bug?

### Affected Resource(s)
- google_storage_bucket

### References

b/278252191

**Comment by edwardmedia** [comment]
The issue is when `autoclass` is set to false, the api basically does not sent it back On the other side, when it is set to true, the api has its setting in the response payload

**Comment by edwardmedia** [comment]
b/278252191

**Comment by rileykarson** [comment]
@edwardmedia the API is probably not gonna change anything here- this comes down to a difference between how proto represents empty blocks and how JSON does. We should consider a clientside mitigation like a DiffSuppressFunc.
