### ISSUE TITLE
adding stack_type to resource `ha_vpn_gateway` provider wants to recreate resource version 4.61.0

### ISSUE THREAD

**Issue by olopopoo** [hashicorp/terraform-provider-google#14328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_ha_vpn_gateway

### Terraform Configuration Files

 version 4.61.0 adds stack_type to resource `ha_vpn_gateway, but wants to destroy and recreate the vpn_gateway resource.
 
 resource "google_compute_ha_vpn_gateway" "vpn_gateway" {
  provider = google-beta
  name     = each.value.gateway
  network  = each.value.network
  region   = each.value.region
  project  = each.value.project
}

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior
~ resource "google_compute_ha_vpn_gateway" "vpn_gateway" {
19:05:13        ~ id         = "projects/xxx-xx-xxx/regions/europe-west2/vpnGateways/xxx-mgmt-bld-xxx-mg-prod-cxx" -> (known after apply)
19:05:13          name       = "xxx-mgmt-bld-xxx-mg-prod-cxx"
19:05:13        
		~ network    = "https://www.googleapis.com/compute/v1/projects/xxx-xx-xxx/global/networks/mgmt-bld-xxx-mg-prod" -> "mgmt-bld-xxx-mg-prod" 
19:05:13        ~ self_link  = "https://www.googleapis.com/compute/v1/projects/xxx-xx-xxx/regions/europe-west2/vpnGateways/xxx-mgmt-bld-xxx-mg-prod-cxx" -> (known after apply) 
19:05:13        + stack_type = "IPV4_ONLY" 
19:05:13          # (2 unchanged attributes hidden)
19:05:13 
19:05:13        ~ vpn_interfaces {
19:05:13            ~ id                      = 0 -> (known after apply)
19:05:13            + interconnect_attachment = (known after apply)
19:05:13            ~ ip_address              = "x5.xxx.xxx.xxx" -> (known after apply)
19:05:13          }
19:05:13        - vpn_interfaces {
19:05:13            - id         = 1 -> null
19:05:13            - ip_address = "x5.xxx.xxx.xxx" -> null
19:05:13          }
19:05:13      }
19:05:13 

### Actual Behavior
-/+ resource "google_compute_ha_vpn_gateway" "vpn_gateway" {
19:05:13        ~ id         = "projects/xxx-xx-xxx/regions/europe-west2/vpnGateways/xxx-mgmt-bld-xxx-mg-prod-cxx" -> (known after apply)
19:05:13          name       = "xxx-mgmt-bld-xxx-mg-prod-cxx"
19:05:13        
		~ network    = "https://www.googleapis.com/compute/v1/projects/xxx-xx-xxx/global/networks/mgmt-bld-xxx-mg-prod" -> "mgmt-bld-xxx-mg-prod" 
19:05:13        ~ self_link  = "https://www.googleapis.com/compute/v1/projects/xxx-xx-xxx/regions/europe-west2/vpnGateways/xxx-mgmt-bld-xxx-mg-prod-cxx" -> (known after apply) 
19:05:13        + stack_type = "IPV4_ONLY" # forces replacement
19:05:13          # (2 unchanged attributes hidden)
19:05:13 
19:05:13        ~ vpn_interfaces {
19:05:13            ~ id                      = 0 -> (known after apply)
19:05:13            + interconnect_attachment = (known after apply)
19:05:13            ~ ip_address              = "x5.xxx.xxx.xxx" -> (known after apply)
19:05:13          }
19:05:13        - vpn_interfaces {
19:05:13            - id         = 1 -> null
19:05:13            - ip_address = "x5.xxx.xxx.xxx" -> null
19:05:13          }
19:05:13      }
19:05:13 

### Steps to Reproduce
Terraform forces a replacement of the resource, which is not expected as the default if not specified according to the google API docs below is IPV4_ONLY, so this addition isn't really changing any thing other than updating the config in the remote state

https://cloud.google.com/compute/docs/reference/rest/v1/vpnGateways

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/14264
