### ISSUE TITLE
Internet NEG support for non-classic HTTP(S) global load balancer (EXTERNAL_MANAGED backend)

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#14337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.5

+ provider registry.terraform.io/hashicorp/google v4.61.0

### Affected Resource(s)

* google_compute_backend_service

### Terraform Configuration Files

Tf plan:

```
 # module.global-elb.google_compute_backend_service.default["test-ineg"] will be created
  + resource "google_compute_backend_service" "default" {
      + connection_draining_timeout_sec = 300
      + creation_timestamp                       = (known after apply)
      + description                                     = "INEG backend test"
      + fingerprint                                      = (known after apply)
      + generated_id                                  = (known after apply)
      + id                                                    = (known after apply)
      + load_balancing_scheme                 = "EXTERNAL_MANAGED"
      + locality_lb_policy                            = "ROUND_ROBIN"
      + name                                              = "elb-test-ineg-443"
      + port_name                                      = (known after apply)
      + project                                            = "my-project"
      + protocol                                          = "HTTPS"
      + self_link                                           = (known after apply)
      + session_affinity                               = (known after apply)
      + timeout_sec                                    = 30
     + backend {
          + balancing_mode                         = "UTILIZATION"
          + capacity_scaler                            = 1
          + group                                          = (known after apply)
          + max_connections                        = (known after apply)
          + max_connections_per_endpoint = (known after apply)
          + max_connections_per_instance  = (known after apply)
          + max_rate                                     = (known after apply)
          + max_rate_per_endpoint              = (known after apply)
          + max_rate_per_instance               = (known after apply)
          + max_utilization                           = (known after apply)
        }
  }

```

### Panic Output

N/A

### Expected Behavior

Global Backend Service should be created, referencing the INEG

### Actual Behavior

```
│ Error: Error creating BackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0]': '{  "resourceGroup": "projects/my-project/global/networkEndpointGroups/test-ineg-443",  "balancing...'. Internet NEGs can be attached to EXTERNAL and INTERNAL_SELF_MANAGED backend services only., invalid
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Internet Network Endpoint Groups (INEGs) were historically only supported for classic HTTP(S) global elbs.  Supported was added for the newer non-classic HTTP(S) ELBs in early 2023.  

### References

* [#0000](https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-external-backend)

**Comment by jeheyer** [comment]
Actually, looks like this is a bug on the google side.  While the web console works fine, the corresponding gcloud commands fail with the same error:

```
  gcloud compute network-endpoint-groups create derp \
    --network-endpoint-type="internet-fqdn-port" \
    --global

  gcloud compute network-endpoint-groups update derp \
    --add-endpoint="fqdn=www.derp.com,port=443" \
    --global

  gcloud compute backend-services create test-backend \
    --load-balancing-scheme=EXTERNAL_MANAGED \
    --global
  
  gcloud compute backend-services add-backend test-backend \
    --network-endpoint-group=derp \
    --global-network-endpoint-group \
    --global
```

I'll proceed with opening a support case.

**Comment by edwardmedia** [comment]
@jeheyer did you notice the note [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service)? Do you intend to create a `self-managed internal load balancing`?

```
A Backend Service defines a group of virtual machines that will serve traffic for load balancing. This resource is a global backend service, appropriate for external load balancing or self-managed internal load balancing. For managed internal load balancing, use a regional backend service instead.

Currently self-managed internal load balancing is only available in beta.
```

**Comment by edwardmedia** [comment]
@jeheyer can you share you debug log? Using below config, it works fine with me. Does this work for you?

```tf
resource "google_compute_backend_service" "default" {
  name          = "issue14337"
  health_checks = [google_compute_health_check.default.id]
  load_balancing_scheme = "EXTERNAL_MANAGED"
}

resource "google_compute_health_check" "default" {
  name = "health-check"
  http_health_check {
    port = 80
  }
}
```

**Comment by jeheyer** [comment]
Ohhhh it's only supported in the beta provider.  Likewise, `gcloud beta` with those same commands works too.

**Comment by edwardmedia** [comment]
@jeheyer should we close this issue now?

**Comment by jeheyer** [comment]
Yes, I have confirmation from Google support this feature is still in beta/preview mode.
