### ISSUE TITLE
Router interface import not working : requires project ID. Fails when provided too

### ISSUE THREAD

**Issue by balaji2711996** [hashicorp/terraform-provider-google#14331]
Command used :  terraform import 'module.hub_vpn_onprem[0].google_compute_router_interface.router_interface["remote-0"]' us-east4/tt-rtr-infraservices-hub-default/tt-gw-infra-hub-vpn-onprem-gw1-remote-0

Error : project: required field is not set

terraform doc used : https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_interface#import 

As I received the error , project field is required, tried importing again by re-running with project id as below

terraform import 'module.hub_vpn_onprem[0].google_compute_router_interface.router_interface["remote-0"]' projects/tt-pr-infraservices-hub/regions/us-east4/routers/tt-rtr-infraservices-hub-default/tt-gw-infra-hub-vpn-onprem-gw1-remote-0

This error'ed out saying below,
Error: Invalid router interface specifier. Expecting {region}/{router}/{interface}

Any suggestions/fix for this would be helpful

**Comment by SarahFrench** [comment]
Hi @balaji2711996 👋 

Thanks for reporting this issue - I've had a look at the code and am getting familiar with the problem.

Ideally the resource's import function would be updated to be able to receive the project name like you tried to do - I'll have a look into that now and will work on a PR to add that functionality.

To help you now, a possible workaround for this is to add a `project` argument in your configuration and then run the import command afterwards.

```hcl
resource "google_compute_router_interface" "foobar" {
  project = "tt-pr-infraservices-hub"
}

```

Alternatively, if you can set a default project in your provider configuration this will help you work around the problem: [`project` in the provider configuration](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project)

**Comment by balaji2711996** [comment]
Hi @SarahFrench Thanks for the reply

Even after assigning the project using "gcloud config set project" to relevant project. The issue persists.

**Comment by SarahFrench** [comment]
Hi @balaji2711996  - I found that after I reproduced your error I could fix it by running the `terraform import` command when I had a default project set in the provider, either written in my Terraform configuration or when supplied by the GOOGLE_PROJECT environment variable (please see https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project).

If your Terraform configuration doesn't easily allow that workaround then I have a fix that's in review.
