### ISSUE TITLE
stack_type on compute_ha_vpn_gateway breaks current implementations on provider 4.61.0

### ISSUE THREAD

**Issue by nbrys** [hashicorp/terraform-provider-google#14336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
v1.3.3 / Google provider 4.61.0
### Affected Resource(s)

compute_ha_vpn_gateway / stack_type
### Terraform Configuration Files (if applicable)

```tf
resource "google_compute_ha_vpn_gateway" "gcp-vpn-gw" {
  name    = format("gw-%s", var.vpn_name)
  network = var.network
  region  = var.region
  project = var.project
}
```

### Issue Description
The introduction of stack_types breaks current implementations. The following is a change from our current gateway reported by terraform when running a plan

```tf
+ stack_type = "IPV4_ONLY" # forces replacement
```

**Comment by rileykarson** [comment]
Instance of https://github.com/hashicorp/terraform-provider-google/issues/14264
