### ISSUE TITLE
Update `google_compute_security_policy` to support `user_ip_request_header` and `origin.user_ip`

### ISSUE THREAD

**Issue by mspoonauer** [hashicorp/terraform-provider-google#14340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Update `google_compute_security_policy` `advanced_options_config` to support the ability to specify `user_ip_request_header`.

### New or Affected Resource(s)

* google_compute_security_policy

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_compute_security_policy" "my_policy" {
  provider    = google-beta
  name        = "my_policy"
  description = "Example Adaptive Protection and Threat Intelligence Cloud Armor security policy"

  # Apply advanced network DDoS protection
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable          = true
      rule_visibility = "PREMIUM"
    }
  }

  advanced_options_config {
    user_ip_request_header = 'x-my-true-client-ip'
  }

  # Block known malicious IPs
  rule {
    action      = "deny(403)"
    description = "block-malicious-ips"
    preview     = false
    priority    = 3000

    match {
      expr {
        expression = "evaluateThreatIntelligence('iplist-known-malicious-ips', origin.user_ip)"
      }
    }
  }
}
```

### References

* #0000

**Comment by mspoonauer** [comment]
Hey, Development Team.

Any insights on when we might be able to obtain the ability to control these features within Terraform?

The reason I ask is that if you make changes using gcloud or the API, the next Terraform run will probably remove all changes.

**Comment by melinath** [comment]
I believe this duplicates https://github.com/hashicorp/terraform-provider-google/issues/15048 - the `origin.user_ip` example does not seem to represent a new field.
