### ISSUE TITLE
Existing google_service_account doesn't get tainted on provider update

### ISSUE THREAD

**Issue by laszlocsomor** [hashicorp/terraform-provider-google#14351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
  $ /opt/hashicorp/terraform_1.4.5_linux_amd64/terraform -v
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.62.0
```

### Affected Resource(s)

* `google_service_account`

#### Before first apply

```tf
provider "google" {
  alias   = "real"
  project = "(redacted)"  # an existing GCP account I can access
}

provider "google" {
  alias   = "fake"
  project = "literally-anything"
}

resource "google_service_account" "service_account" {
  account_id = "laszlo-test-providers"
  provider   = google.real
}
```

#### Before second apply

```tf
provider "google" {
  alias   = "real"
  project = "(redacted)"  # an existing GCP account I can access
}

provider "google" {
  alias   = "fake"
  project = "literally-anything"
}

resource "google_service_account" "service_account" {
  account_id = "laszlo-test-providers"
  provider   = google.fake
}
```

### Debug Output

https://gist.github.com/laszlocsomor/3a67a73cb8ad5c15d49a15af88f3521a -- See `tf_debug_1.txt` (first apply) and `tf_debug_2.txt` (second).

### Panic Output

{blank}

### Expected Behavior

The second `apply` should have planned to update or recreate the `google_service_account.service_account`, since the resource reads the `project` from the `provider` and the provider was updated.

### Actual Behavior

The second `apply` had a clean plan.

### Steps to Reproduce

1. Set an actual value to `google.real.project` in the first TF file
1. `terraform apply`
1. Replace the TF file with the second one
1. `terraform apply` # should print a changing plan but it doesn't

### Important Factoids

The bug doesn't repro if you explicitly specify the `project` attribute; only when it's implicit from the `provider`.

### References

{blank}

**Comment by edwardmedia** [comment]
dup of https://github.com/hashicorp/terraform-provider-google/issues/11339. Closing
