### ISSUE TITLE
google_container_cluster 'project' field is actually required

### ISSUE THREAD

**Issue by bjd2385** [hashicorp/terraform-provider-google#14354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.6, GCP provider v4.62.0

### Affected Resource(s)

* `google_container_cluster`

### Terraform Configuration Files

```tf
# terraform.tf
provider "google" {
  alias   = "operations"
  project = "operations"
  region  = "us-east1"
}
```

```tf
# gitlab-runner.tf
resource "google_container_cluster" "gitlab-runner" {
  name     = "gitlab-runner"
  location = "us-east1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true

  initial_node_count = 1

  addons_config {
    # We don't need any LBs on this cluster.
    http_load_balancing {
      disabled = true
    }

    # Enable HPA (enabled by default).
    horizontal_pod_autoscaling {
      disabled = false
    }

    # We need the CSI driver enabled for RWX volumes.
    gcp_filestore_csi_driver_config {
      enabled = true
    }

    # We need this driver for RWO volumes.
    gce_persistent_disk_csi_driver_config {
      enabled = true
    }
  }
}
```

### Debug Output

```text
google_container_cluster.gitlab-runner: Creating...
2023-04-19T14:41:04.958Z [ERROR] provider.terraform-provider-google_v4.62.0_x5: Response contains error diagnostic: tf_proto_version=5.3 tf_resource_type=google_container_cluster @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_severity=ERROR @module=sdk.proto diagnostic_summary="project: required field is not set" tf_provider_addr=registry.terraform.io/hashicorp/google tf_req_id=39e8c830-0dfc-8724-de09-48d7abad409a tf_rpc=ApplyResourceChange timestamp=2023-04-19T14:41:04.957Z
2023-04-19T14:41:04.959Z [ERROR] vertex "google_container_cluster.gitlab-runner" error: project: required field is not set
Error: project: required field is not set
  with google_container_cluster.gitlab-runner,
  on gke-gitlab-runner.tf line 2, in resource "google_container_cluster" "gitlab-runner":
   2: resource "google_container_cluster" "gitlab-runner" {
```

### Panic Output

N/A

### Expected Behavior

According to [the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#project), this field isn't required.

### Actual Behavior

`project`-field is actually required?

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A it's a pretty straightforward setup.

### References

* N/A

**Comment by edwardmedia** [comment]
@bjd2385 most resources are associated with a project. That is why it is required. But you can skip it at the level of individual resources if you provide it in the [provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#provider-default-values-configuration) config. This help reduce the code in the individual resources. You may see optional applied for region, zone, etc. in most of resources. Does this make sense?

**Comment by edwardmedia** [comment]
@bjd2385 can you share your debug log for the case where you specified the project in config?

**Comment by bjd2385** [comment]
> @bjd2385 is this still an issue after you added `project` in the provider? If yes, can you share your debug log?

It is no longer an issue when I specify that on the resource-block. I'll get debug logs later today.

**Comment by edwardmedia** [comment]
@bjd2385 no debug log is needed unless you still have the issue. Closing this now. Feel free to reopen if you have more questions on this. Thanks

**Comment by bjd2385** [comment]
I had this issue while specifying the project in the provider block. Like apparently that wasn't enough. I had to specify the project ID on the individual resources. Not sure how to make it clearer. So in other words, specifying the project on the provider block alone wasn't enough. I don't think it's being respected.

**Comment by bjd2385** [comment]
I had this issue while specifying the project in the provider block. Like apparently that wasn't enough. I had to specify the project ID on the individual resources. Not sure how to make it clearer (pls see updated code example above). 

So in other words, specifying the project on the provider block alone wasn't enough. I don't think it's being respected in the version(s) I'm using, despite the docs.
