### ISSUE TITLE
Failing test(s): TestAccIAMWorkforcePoolWorkforcePoolProvider_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14376]
### Failure rates

- _100%_ since 2023-04-15

### Impacted tests

- TestAccIAMWorkforcePoolWorkforcePoolProvider_oidc
- TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcBasicExample
- TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcFullExample

### Affected Resource(s)

* google_iam_workforce_pool_provider

### Nightly build test history

- [TestAccIAMWorkforcePoolWorkforcePoolProvider_oidc](https://ci-oss.hashicorp.engineering/test/-4911874906922450432?currentProjectId=GoogleCloud&branch=%3Cdefault%3E)
- [TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcBasicExample](https://ci-oss.hashicorp.engineering/test/4279931651477504711?currentProjectId=GoogleCloud&branch=%3Cdefault%3E)
- [TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcFullExample](https://ci-oss.hashicorp.engineering/test/3613910494655602165?currentProjectId=GoogleCloud&branch=%3Cdefault%3E)

#### TestAccIAMWorkforcePoolWorkforcePoolProvider_oidc

```
vcr_utils.go:144: Step 1/7 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# google_iam_workforce_pool_provider.my_provider will be updated in-place
~ resource "google_iam_workforce_pool_provider" "my_provider" {
id                  = "locations/global/workforcePools/my-pool-xahdvpknoi/providers/my-provider-xahdvpknoi"
name                = "locations/global/workforcePools/my-pool-xahdvpknoi/providers/my-provider-xahdvpknoi"
# (9 unchanged attributes hidden)
~ oidc {
# (2 unchanged attributes hidden)
+ web_sso_config {
+ assertion_claims_behavior = "ONLY_ID_TOKEN_CLAIMS"
+ response_type             = "ID_TOKEN"
}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccIAMWorkforcePoolWorkforcePoolProvider_oidc (107.91s)
```

#### TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcBasicExample

```
vcr_utils.go:144: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# google_iam_workforce_pool_provider.example will be updated in-place
~ resource "google_iam_workforce_pool_provider" "example" {
id                = "locations/global/workforcePools/tf-test-example-pool3lntllixv8/providers/tf-test-example-prvdr3lntllixv8"
name              = "locations/global/workforcePools/tf-test-example-pool3lntllixv8/providers/tf-test-example-prvdr3lntllixv8"
# (6 unchanged attributes hidden)
~ oidc {
# (2 unchanged attributes hidden)
+ web_sso_config {
+ assertion_claims_behavior = "ONLY_ID_TOKEN_CLAIMS"
+ response_type             = "ID_TOKEN"
}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcBasicExample (109.35s)

```

#### TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcFullExample

Same as both above

**Comment by trodge** [comment]
These tests are all passing in the latest nightly runs.
