### ISSUE TITLE
Failing test(s): TestAccNotebooksInstance_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14380]
### Failure rates

- _100%_ since 2023-04-18

### Impacted tests

- TestAccNotebooksInstance_update
- TestAccNotebooksInstance_notebookInstanceFullExample

### Affected Resource(s)

* google_notebooks_instance

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/test/1861864166893878271?currentProjectId=GoogleCloud&branch=%3Cdefault%3E)

### Message(s)

Labels being removed after refresh

```
------- Stdout: -------
=== RUN   TestAccNotebooksInstance_notebookInstanceFullExample
=== PAUSE TestAccNotebooksInstance_notebookInstanceFullExample
=== CONT  TestAccNotebooksInstance_notebookInstanceFullExample
vcr_utils.go:144: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# google_notebooks_instance.instance will be updated in-place
~ resource "google_notebooks_instance" "instance" {
id                 = "projects/PROJECT_ID/locations/us-central1-a/instances/tf-test-notebooks-instance3axu0l80x2"
~ labels             = {
- "consumer-project-id" = "ajbp-test" -> null
- "resource-name"       = "ajbp-test-there-can-only-be-one" -> null
# (2 unchanged elements hidden)
}
name               = "tf-test-notebooks-instance3axu0l80x2"
# (16 unchanged attributes hidden)
# (2 unchanged blocks hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccNotebooksInstance_notebookInstanceFullExample (78.69s)
FAIL
```

b/299600700

**Comment by SarahFrench** [comment]
I think we just need to add a field in the import test step to ignore the label field

**Comment by SarahFrench** [comment]
When I run this test against a different GCP project I don't get that error. It might be that external factors are causing labels to change? Especially as the example error I copied includes `"ajbp-test-there-can-only-be-one"`

**Comment by SarahFrench** [comment]
Here's another interesting example of the label content: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/392900

It suggests that e2e tests are using the same project?

**Comment by melinath** [comment]
This failure no longer seems to be happening - the full example test is flakey due to "subnetwork not ready" errors but that's a separate issue.
