### ISSUE TITLE
Failing test(s): TestAccContainerNodePool_version

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14389]
### Failure rates

- 100% since 2023-04-19 - 2 test failures for same reason, error 400.

### Impacted tests

- TestAccContainerNodePool_version

### Affected Resource(s)

* google_container_node_pool

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/test/7191041804808208175?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)

### Message(s)

```
=== RUN   TestAccContainerNodePool_version
=== PAUSE TestAccContainerNodePool_version
=== CONT  TestAccContainerNodePool_version
vcr_utils.go:144: Step 1/6 error: Error running apply: exit status 1
Error: error creating NodePool: googleapi: Error 400: Node version "1.26.1-gke.1500" must not have a greater minor version than master version "1.25.8-gke.500"., badRequest
with google_container_node_pool.np,
on terraform_plugin_test.tf line 13, in resource "google_container_node_pool" "np":
13: resource "google_container_node_pool" "np" {
--- FAIL: TestAccContainerNodePool_version (607.36s)
FAIL

```

**Comment by SarahFrench** [comment]
Looks like the test is using an old version and it's reached the point that it's so old the API validation is rejecting it?

**Comment by trodge** [comment]
This test seems to be passing now.
