### ISSUE TITLE
Failing test(s): TestAccContainerAwsCluster_BetaBasicHandWritten (beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14392]
### Failure rates

- 100% since 2023-04-07 - this lines up with the migration to the new Beta overnight test project

### Impacted tests

- TestAccContainerAwsCluster_BetaBasicHandWritten
- TestAccContainerAwsNodePool_BetaBasicHandWritten
- 

### Affected Resource(s)

* google_container_aws_cluster

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/test/-1103612266762002937?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E&expandedTest=id%3A220272%2Cbuild%3A%28id%3A392095%29)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccContainerAwsCluster_BetaBasicHandWritten
=== PAUSE TestAccContainerAwsCluster_BetaBasicHandWritten
=== CONT  TestAccContainerAwsCluster_BetaBasicHandWritten
vcr_utils.go:146: Step 1/4 error: Error running apply: exit status 1
Error: Error creating Cluster: googleapi: Error 400: dedicated instance is not supported for this cluster, field: aws_cluster.control_plane.instance_placement
Details:
[
{
"@type": "type.googleapis.com/google.rpc.BadRequest",
"fieldViolations": [
{
"description": "dedicated instance is not supported for this cluster",
"field": "aws_cluster.control_plane.instance_placement"
}
]
}
]
with google_container_aws_cluster.primary,
on terraform_plugin_test.tf line 8, in resource "google_container_aws_cluster" "primary":
8: resource "google_container_aws_cluster" "primary" {
--- FAIL: TestAccContainerAwsCluster_BetaBasicHandWritten (6.23s)
FAIL

```

b/293594181

**Comment by SarahFrench** [comment]
@roaks3 here's another test failure that looks like it's related to the swap to the new nightly test project for TPGB

**Comment by rileykarson** [comment]
Note: Our original project was on a control list of some sort, we'll need to get the new ones on there.

**Comment by roaks3** [comment]
@SarahFrench Yea, this definitely looks related to the switch. It looks like this is a DCL resource, and I can't tell if something else is going on that we need to update (for example, it looks like there might be a real `secret_arn` used in the proxy config).

We used b/268374957 to set up the control lists, and I believe we were broadly given everything we need. It's possible we need to amend that request, but my inclination is that this is a separate issue.

**Comment by ostrain** [comment]
This should be fixed now
