### ISSUE TITLE
Possibly misleading example for creating an authorized dataset using the google_bigquery_dataset_access resource

### ISSUE THREAD

**Issue by hanss0n** [hashicorp/terraform-provider-google#14406]
The [code snippet](https://github.com/hashicorp/terraform-provider-google/blob/c5747c1ced19c21b43f3c45b7164326f244ba8fd/website/docs/r/bigquery_dataset_access.html.markdown?plain=1#L92) for creating an authorized dataset seems very misleading to me: 

```hcl
resource "google_bigquery_dataset_access" "access" {
  dataset_id    = google_bigquery_dataset.private.dataset_id
  dataset {
    dataset{
      project_id = google_bigquery_dataset.public.project
      dataset_id = google_bigquery_dataset.public.dataset_id
    }
    target_types = ["VIEWS"]
  }
}

resource "google_bigquery_dataset" "private" {
  dataset_id = "private"
}

resource "google_bigquery_dataset" "public" {
  dataset_id = "public"
}
```
Currently, the "private" dataset is granting access to specific views of the "public" dataset. Shouldn't this be the other way around?
It makes much more sense to have the "private" dataset expose a subset of information to the "public" dataset. Or am I missing something?

**Comment by edwardmedia** [comment]
@hanss0n [this](https://github.com/hashicorp/terraform-provider-google/issues/14406#issue-1681346720) is similar to the [view](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access#view) which says below words. I think it is giving `public` dataset access to the `private` dataset. Does this make sense? 

```
Queries executed against that view will have read access to tables in this dataset. 
```

**Comment by hanss0n** [comment]
My bad, it's correct now as it is! Thanks for the quick response.
