### ISSUE TITLE
add NotificationChannelStrategy to google_monitoring_alert_policy

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#14405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In order to "Send repeated notifications", I can't use the Cloud console, I have to use the REST API at the moment.
It would be very useful to be able to configure this in Terraform.

### New or Affected Resource(s)

* google_monitoring_alert_policy

### Potential Terraform Configuration

```tf
resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "My Alert Policy"
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\" AND resource.type=\"gce_instance\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = ["projects/PROJECT_ID/notificationChannels/CHANNEL_ID"]
  
  alert_strategy {
    ## The new settings are as follows.
    notification_channel_strategy {
      notification_channel_names = ["projects/PROJECT_ID/notificationChannels/CHANNEL_ID"]
      renotify_interval          = "1800s"
    }
  }

  user_labels = {
    foo = "bar"
  }
}
```

### References

* https://cloud.google.com/monitoring/alerts/concepts-indepth#send-repeated-notifications
* https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#notificationchannelstrategy

**Comment by trodge** [comment]
b/280452056
