### ISSUE TITLE
"google_compute_subnetwork" Attributes not working

### ISSUE THREAD

**Issue by popchop3** [hashicorp/terraform-provider-google#14429]
When trying to pull the "name", "id" attributes from the subnetwork which I created, so that I can pass them through to my VM. I am doing so using an output but am getting the following error message despite it showing as correct in the documentation

│ Error: Unsupported attribute
│ 
│   on outputs.tf line 7, in output "subnet-name-output":
│    7:     value = join("", google_compute_subnetwork.non-module-subnet.*.name)
│ 
│ This object does not have an attribute named "name".

Note, my subnetwork resource is defined like below:
resource "google_compute_subnetwork" "non-module-subnet" {
  for_each                  = toset(keys(var.regions)) #Get the keys from the region list in "env.tfvars" file and makes it a set to loop through
  name                        = "non-module-subnet-${each.value}-${var.env}"
  ip_cidr_range           = var.primary_region_subnet_cidrs[var.regions[each.value]]
  region                       = var.regions[each.value] 
  network                    = "non-module-vpc"
}

Anyone else having this issue? I am able to grab the attributes from the "google_compute_network" resource but just not "google_compute_subnetwork"

### Affected Resource(s)

- google_compute_subnetwork

**Comment by edwardmedia** [comment]
@popchop3 not sure what you want to do but looks like you should be able to obtain the name like below. This is about features of the Terraform core, and I don't think it is something wrong at the provider. Does this make sense?

```
google_compute_subnetwork.non-module-subnet[index].name
```

**Comment by edwardmedia** [comment]
@popchop3 here is an example. You should be able to see all the subnets' attributes from the `subnetwork_set`.

```
locals {
    subs = [
        {
            name          = "issue14429-central1"
            ip_cidr_range = "10.2.0.0/16"
            region        = "us-central1"
        },
        {
            name          = "issue14429-west1"
            ip_cidr_range = "10.3.0.0/16"
            region        = "us-central1"
        }
    ]
}

resource "google_compute_subnetwork" "my_sub" {

  count = 2
  name          = local.subs[count.index].name
  ip_cidr_range = local.subs[count.index].ip_cidr_range
  region        = local.subs[count.index].region
  network       = google_compute_network.custom-test.id
}

output "subnetwork_set" {
  value = toset(google_compute_subnetwork.my_sub)
}
```

**Comment by edwardmedia** [comment]
@popchop3 is this still an issue?

**Comment by edwardmedia** [comment]
@popchop3 closing this assuming it is no longer an issue
