### ISSUE TITLE
Provider produced inconsistent result after apply │ 

### ISSUE THREAD

**Issue by pkatakam** [hashicorp/terraform-provider-google#14442]
Got this error during the terraform apply. Reran was successful though . Just wanted to report this bug as it stated in the error log . 
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to google_project_iam_member.project, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"].base_iam" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

**Comment by edwardmedia** [comment]
@pkatakam thank you for reporting this but there is not enough info that can help us to investigate. Can you share your config and steps that leads to this?

**Comment by pkatakam** [comment]
We got this error while running our terraform code in gitlab pipeline. 
Attached the entire logs from our terraform apply stage. Let me know if this helps. 

$ terraform apply tfplan
module.project.random_id.project_random_id_suffix: Creating...
module.project.random_id.project_random_id_suffix: Creation complete after 0s [id=LbA]
module.project.google_project.project: Creating...
module.project.google_project.project: Still creating... [10s elapsed]
module.project.google_project.project: Still creating... [20s elapsed]
module.project.google_project.project: Still creating... [30s elapsed]
module.project.google_project.project: Still creating... [40s elapsed]
module.project.google_project.project: Still creating... [50s elapsed]
module.project.google_project.project: Creation complete after 56s [id=projects/mckgc9-iz-pk1-test-app2-2db0]
module.project.google_project_service.project_services["ids.googleapis.com"]: Creating...
module.project.google_project_service.project_services["vpcaccess.googleapis.com"]: Creating...
module.project.google_project_service.project_services["iam.googleapis.com"]: Creating...
module.project.google_project_service.project_services["cloudfunctions.googleapis.com"]: Creating...
module.project.google_project_iam_audit_config.project_audit: Creating...
module.project.google_project_default_service_accounts.default_sa: Creating...
module.project.google_project_service.project_services["cloudscheduler.googleapis.com"]: Creating...
module.project.google_project_service.project_services["servicenetworking.googleapis.com"]: Creating...
module.project.google_project_service.project_services["dns.googleapis.com"]: Creating...
module.project.google_project_service.project_services["pubsub.googleapis.com"]: Creating...
module.project.google_project_default_service_accounts.default_sa: Creation complete after 0s [id=projects/mckgc9-iz-pk1-test-app2-2db0]
module.project.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Creating...
module.project.google_project_iam_audit_config.project_audit: Creation complete after 7s [id=mckgc9-iz-pk1-test-app2-2db0/audit_config/allServices]
module.project.google_project_service.project_services["compute.googleapis.com"]: Creating...
module.project.google_project_service.project_services["vpcaccess.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["ids.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["iam.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["cloudfunctions.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["cloudscheduler.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["pubsub.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["servicenetworking.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["dns.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["compute.googleapis.com"]: Creation complete after 3s [id=mckgc9-iz-pk1-test-app2-2db0/compute.googleapis.com]
module.project.google_project_service.project_services["cloudasset.googleapis.com"]: Creating...
module.project.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["ids.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["vpcaccess.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["iam.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["cloudfunctions.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["dns.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["cloudscheduler.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["pubsub.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["servicenetworking.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["cloudasset.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["vpcaccess.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["ids.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["iam.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["cloudfunctions.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["servicenetworking.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["dns.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["cloudscheduler.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["pubsub.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["cloudasset.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Still creating... [30s elapsed]
module.project.google_project_service.project_services["cloudscheduler.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/cloudscheduler.googleapis.com]
module.project.google_project_service.project_services["cloudasset.googleapis.com"]: Creation complete after 20s [id=mckgc9-iz-pk1-test-app2-2db0/cloudasset.googleapis.com]
module.project.google_project_service.project_services["ids.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/ids.googleapis.com]
module.project.google_project_service.project_services["servicenetworking.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/servicenetworking.googleapis.com]
module.project.google_project_service.project_services["cloudfunctions.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/cloudfunctions.googleapis.com]
module.project.google_project_service.project_services["vpcaccess.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/vpcaccess.googleapis.com]
module.project.google_project_service.project_services["iam.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/iam.googleapis.com]
module.project.google_project_service.project_services["pubsub.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/pubsub.googleapis.com]
module.project.google_project_service.project_services["cloudresourcemanager.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/cloudresourcemanager.googleapis.com]
module.project.google_project_service.project_services["dns.googleapis.com"]: Creation complete after 30s [id=mckgc9-iz-pk1-test-app2-2db0/dns.googleapis.com]
module.project.google_project_service.project_services["serviceusage.googleapis.com"]: Creating...
module.project.google_project_service.project_services["cloudbuild.googleapis.com"]: Creating...
module.project.google_project_service.project_services["secretmanager.googleapis.com"]: Creating...
module.project.google_project_service.project_services["serviceusage.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["cloudbuild.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["secretmanager.googleapis.com"]: Still creating... [10s elapsed]
module.project.google_project_service.project_services["cloudbuild.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["serviceusage.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["secretmanager.googleapis.com"]: Still creating... [20s elapsed]
module.project.google_project_service.project_services["cloudbuild.googleapis.com"]: Creation complete after 21s [id=mckgc9-iz-pk1-test-app2-2db0/cloudbuild.googleapis.com]
module.project.google_project_service.project_services["secretmanager.googleapis.com"]: Creation complete after 21s [id=mckgc9-iz-pk1-test-app2-2db0/secretmanager.googleapis.com]
module.project.google_project_service.project_services["serviceusage.googleapis.com"]: Creation complete after 21s [id=mckgc9-iz-pk1-test-app2-2db0/serviceusage.googleapis.com]
module.iz_host_project_config.data.google_secret_manager_secret_version.secret_read_data[0]: Reading...
time_sleep.wait_for_project: Creating...
module.iz_host_project_config.data.google_secret_manager_secret_version.secret_read_data[0]: Read complete after 0s [id=projects/159180873004/secrets/mckgc9-sales-iz-pk1-nonprod-host-project-config/versions/1]
google_project_iam_member.project: Creating...
time_sleep.wait_for_project: Still creating... [10s elapsed]
time_sleep.wait_for_project: Still creating... [20s elapsed]
time_sleep.wait_for_project: Still creating... [30s elapsed]
time_sleep.wait_for_project: Still creating... [40s elapsed]
time_sleep.wait_for_project: Still creating... [50s elapsed]
time_sleep.wait_for_project: Creation complete after 1m0s [id=2023-04-27T18:57:52Z]
google_compute_shared_vpc_service_project.vpc_sharing[0]: Creating...
google_dns_managed_zone.private-zone[0]: Creating...
module.project_id_secret.google_secret_manager_secret.secret: Creating...
module.project_id_secret.google_secret_manager_secret.secret: Creation complete after 0s [id=projects/mckgc9-iz-pk1-nonprod-ss-[36](https://gitlab.mckgc9.gcp.cbm.matter.cloud/mckgc9-isolation-zone/iz-basic-sales-pk1/-/jobs/543#L36)01/secrets/test_app2_project_id]
module.project_id_secret.google_secret_manager_secret_version.secret: Creating...
module.project_id_secret.google_secret_manager_secret_version.secret: Creation complete after 1s [id=projects/[37](https://gitlab.mckgc9.gcp.cbm.matter.cloud/mckgc9-isolation-zone/iz-basic-sales-pk1/-/jobs/543#L37)[56](https://gitlab.mckgc9.gcp.cbm.matter.cloud/mckgc9-isolation-zone/iz-basic-sales-pk1/-/jobs/543#L56)3[60](https://gitlab.mckgc9.gcp.cbm.matter.cloud/mckgc9-isolation-zone/iz-basic-sales-pk1/-/jobs/543#L60)[72](https://gitlab.mckgc9.gcp.cbm.matter.cloud/mckgc9-isolation-zone/iz-basic-sales-pk1/-/jobs/543#L72)220/secrets/test_app2_project_id/versions/1]
google_dns_managed_zone.private-zone[0]: Creation complete after 1s [id=projects/mckgc9-iz-pk1-test-app2-2db0/managedZones/managed-private-zone]
google_compute_shared_vpc_service_project.vpc_sharing[0]: Still creating... [10s elapsed]
google_compute_shared_vpc_service_project.vpc_sharing[0]: Creation complete after 12s [id=mckgc9-iz-pk1-nonprod-hos-af4b/mckgc9-iz-pk1-test-app2-2db0]
**╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to google_project_iam_member.project, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"].base_iam" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.**

**Comment by edwardmedia** [comment]
@pkatakam not real. I need the terraform code and the steps to repro it. It's hard to see what is going on. Are you able to turn on the debug mode by setting up below environment variable?


export [TF_LOG](https://developer.hashicorp.com/terraform/internals/debugging)=DEBUG

**Comment by pkatakam** [comment]
We are not getting that error any more . When I reran the code it was successful. Also I don't think I am allowed to share the code.
