### ISSUE TITLE
User-supplied, empty values in the provider configuration should not be ignored and unused

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

N/A
This is related to a defect identified after introduction of v4.60.2
We have fixed the provider to have parity with the old behaviour, but in 5.0.0 we should remove the behaviour seen in <=4.59.0

### Affected Resource(s)

N/A - is related to provider config

### Terraform Configuration Files

Provider is configured by:
- Running `gcloud auth application-default login`
- Not having any ENVs for configuring the provider present

```hcl
provider "google" {
  credentials = ""
}
```

### Debug Output

N/A

### Expected Behavior

When a user sets a value in their configuration it should override any environment variables. If a user sets `credentials = ""`, or `project=""` (for example) then the provider should attempt to use that value.

### Actual Behavior

In the old SDK version of the provider <=4.59.0 empty strings would be ignored and ENVs would be used instead.
After muxing was introduced to the provider the ignoring stopped, and we then changed to code to ensure parity with the un-muxed code.
Currently empty strings are ignored in provider configurations.

### Steps to Reproduce

1. Local environment setup
    a. Running `gcloud auth application-default login`
    b. Unset any ENVs for configuring the provider
2. Make a TF config where the provider config block includes an empty string as an argument, e.g. `credentials = ""`
2. `terraform apply` <- error occurs here

### Important Factoids

The reason empty strings were ignored in the past is because the SDK made it hard to distinguish between Go's zero values and user-supplied values. After values were taken out of the `ResourceData` struct for the provider you lose any information about whether the value was set or not. Structs made using values from the provider config, i.e. the `Config` struct, have no way to distinguish between zero values and user values that match.

### References

* Original issue where this was reported: https://github.com/hashicorp/terraform-provider-google/issues/14255

**Comment by SarahFrench** [comment]
This change could include addition of validation functions like : https://developer.hashicorp.com/terraform/plugin/framework/providers/validate-configuration#validateconfig-method

**Comment by SarahFrench** [comment]
Issue is still open due because https://github.com/GoogleCloudPlatform/magic-modules/pull/9050 is needed to add user-facing validation on provider config values

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/9050
