### ISSUE TITLE
Impersonation doesn't seem to take effect for attaching/detaching service projects to Shared VPC host

### ISSUE THREAD

**Issue by jeffling-google** [hashicorp/terraform-provider-google#14459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version 
1.4.6

### Affected Resource(s)

*compute.organizations.enableXpnResource

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jeffling-google** [comment]
submitted without details by mistake. here is the issue:
In the provider, I have the impersonation of service account. 
provider "google" {
 
  impersonate_service_account = "ccc@ssssssssss.iam.gserviceaccount.com"
  request_timeout             = "5m"
}

The impersonation works fine for most of the operations - I can tell by looking at the logs:
authenticationInfo: {
principalEmail: "sss@cccc.iam.gserviceaccount.com"
principalSubject: "ssss@ccccc.iam.gserviceaccount.com"
serviceAccountDelegationInfo: [
0: {
firstPartyPrincipal: {
principalEmail: "sdfsdf@somedomain"
}
...

However, the code failed when attaching the project to a Shared VPC host project:

module "team_project" {
  source  = "terraform-google-modules/project-factory/google//modules/svpc_service_project"
  version = "~> 14.2"

  org_id                      = var.org_id
  billing_account             = var.billing_account
  name                        = var.name
  random_project_id           = true
  disable_services_on_destroy = true
  create_project_sa           = false
  folder_id                   = var.folder_id
  shared_vpc                  = var.shared_vpc
....

In the authentication info, the principal is the user account, not the service account. The user account doesn't have the permissions related to Shared VPC. After adding the permissions to the user account, it works.

It looks like the impersonation block doesn't take effect when attaching service project to the host project.

**Comment by jeffling-google** [comment]
Here is the error message when the user (not the service account) doesn't have the proper permissions:

Error: googleapi: Error 403: Required 'compute.organizations.enableXpnResource' permission for 'projects/beer-213320'
│ More details:
│ Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/beer-213320'
│ Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/team1-16a7'
│ 
│ 
│   with module.team_project.module.project-factory.google_compute_shared_vpc_service_project.shared_vpc_attachment[0],
│   on .terraform/modules/team_project/modules/core_project_factory/main.tf line 117, in resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment":
│  117: resource "google_compute_shared_vpc_service_project" "shared_vpc_attachment" {

**Comment by edwardmedia** [comment]
@jeffling-google As long as `impersonate` account works for other cases, it should work for Shared VPC.  I noticed below error, which complains about the permissions. Does `ccc@ssssssssss.iam.gserviceaccount.com` have the role of [roles/compute.xpnAdmin](https://cloud.google.com/compute/docs/access/iam#compute.xpnAdmin)? 

```
Error 403: Required 'compute.organizations.enableXpnResource' permission
```

**Comment by jeffling-google** [comment]
Yes, the service account does have the permission. The user account (that runs the code) does not. As soon as I added the role to the user (not the service account), the issue is gone. Hence reporting this issue:-)

**Comment by edwardmedia** [comment]
@jeffling-google is this still an issue?

**Comment by edwardmedia** [comment]
@jeffling-google closing this assuming it is no longer an issue
