### ISSUE TITLE
 Error while updating cloudfunction configuration: Error waiting for Updating CloudFunctions Function: Error code 3, message: Build failed: ...5, es6/es2015, es2016, es2017, es2018, es2019, es2020, es2021, es2022, esnext │ default: es3

### ISSUE THREAD

**Issue by mrkhoiit** [hashicorp/terraform-provider-google#14456]
### Terraform Version
Terraform v1.4.6
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/fly-apps/fly v0.0.21
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/google v4.63.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)
```
resource "google_cloudfunctions_function" "firebaseAuth" {
  name                = "firebaseAuth"
  description         = "firebaseAuth"
  runtime             = var.runtime
  available_memory_mb = 256
  max_instances       = 3000

  source_archive_bucket = var.gcp_bucket_name
  source_archive_object = var.gcp_bucket_object.firebase_auth
  # timeout               = 60
  trigger_http = true
  entry_point  = "firebaseAuth"

  environment_variables = {
    GCLOUD_PROJECT             = var.project
    FIREBASE_CONFIG            = var.firebase_config
    GOOGLE_OAUTH_CLIENT_ID     = var.GOOGLE_OAUTH_CLIENT_ID
    GOOGLE_OAUTH_CLIENT_SECRET = var.GOOGLE_OAUTH_CLIENT_SECRET
    GOOGLE_OAUTH_REDIRECT_URL  = var.GOOGLE_OAUTH_REDIRECT_URL
  }

  timeouts {
    create = "10m"
    update = "10m"
    delete = "10m"
  }
}
```
Last deploy still success. But yesterday and today i deploy allway error. Seem code is run build again because not deploy success. Please help !

**Comment by edwardmedia** [comment]
@mrkhoiit I have just tested deploying `google_cloudfunctions_function` and no issue is found.  Possible reason is that the api experienced a difficulty during the time you encountered a failure. If you still see the problem, could you share all the values for the variables and the debug log?

**Comment by mrkhoiit** [comment]
@edwardmedia Thank you so much. This is problem from me. 
For other user if see this error , now google default run : npm run build in package.json. Because need delete `scripts.build`
