### ISSUE TITLE
Add support for Iceberg to BigQuery External Tables

### ISSUE THREAD

**Issue by emkornfield** [hashicorp/terraform-provider-google#14464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support Iceberg as an external table type.  I'll plan on making a PR.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

N/A

### References

N/A

* #0000

**Comment by emkornfield** [comment]
I'll have a PR shortly.

**Comment by rileykarson** [comment]
Assigning based on https://github.com/GoogleCloudPlatform/magic-modules/pull/7858

**Comment by roaks3** [comment]
This appears fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7858
