### ISSUE TITLE
GKE node auto-provisioning doesn't work in versions higher than v4.43.0-v4.63.1+

### ISSUE THREAD

**Issue by stevekoskie** [hashicorp/terraform-provider-google#14465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
on darwin_amd64
provider registry.terraform.io/hashicorp/google v4.63.1

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_service_account" "default" {
  account_id   = "service-account-id-test"
  display_name = "Service Account GKE Testing"
}

resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster-test"
  location = "us-central1"
  remove_default_node_pool = true
  initial_node_count       = 1
  cluster_autoscaling {
    enabled = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 6
      maximum       = 50
    }
    resource_limits {
      resource_type = "memory"
      minimum       = 12
      maximum       = 100
    }
    auto_provisioning_defaults {
      service_account = google_service_account.default.email
      oauth_scopes = [
        "https://www.googleapis.com/auth/cloud-platform"
      ]
    }

  }


}

resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "my-node-pool"
  location   = "us-central1"
  cluster    = google_container_cluster.primary.name
  node_count = 1

  node_config {
    preemptible  = true
    machine_type = "e2-medium"

    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```

### Expected Behavior

Terraform should create a working node auto-provisioning configuration that adds more nodes and node pools as demand increases.

### Actual Behavior

Using a GKE provider with the supplied code with a higher version than v4.43.0 fails to create a working node auto-provisioning configuration. It looks like it is configured correctly, however if you create a resource demand on the cluster, it will not add any nodes or node pools. 

### Steps to Reproduce

1. Run the supplied code using version v4.43.0 
2. Create a kubernetes pod manifest that requests 16 CPU and apply it to the default namespace
3. Verify that the node pool and nodes are created as expected
4. Terraform destroy what you have created
5. Change the provider version to v4.63.1 or any version higher than v4.43.0
6. Create the same cluster again
7. After the cluster is build, create a k8s pod manifest with 16 CPU request and apply it to the default namespace
8. Observe that a new nodes or node pools are not created

### Important Factoids

The issue seems to stem around the usage of the `auto_provisioning_defaults` section. If that block is omitted, then this bug does not appear.

**Comment by edwardmedia** [comment]
@stevekoskie by trying below deployment, I don't see the difference on clusters of between v4.43.0 and v4.63.1 which are on your above config. In both cases, the pod seems working fine.

```
kubectl create deployment hello-server --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
```

How did you do for step 2 and 7? Can you share the details?

**Comment by stevekoskie** [comment]
@edwardmedia 
Here is the pod I created to force the CPU request so that a new node pool and node is created automatically.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "16"
  restartPolicy: Always
```
Save that file, and then do a `kubectl apply -f <filename> -n default`
The request: CPU 16 should force the cluster to build a new node pool that can handle that request. It will work in the older version but not the newer version.

**Comment by edwardmedia** [comment]
@stevekoskie thanks for the yaml file. I am able to repro the issue now. 

`management` was introduced in [v4.44.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.44.0),  Below is the partial request payload when `management` is not set which causes the behavior change.

  "autoscaling": {
   "autoprovisioningNodePoolDefaults": {
    "diskSizeGb": 100,
    "diskType": "pd-standard",
    "imageType": "COS_CONTAINERD",
    "management": {},   <----
    ...
   },

FYI, without `management`, after default_pool is deleted, the cluster will create another pool `nap-e2-highcpu-xxxxxx` which has `Autoscaling` enabled
