### ISSUE TITLE
terraform apply fails due to cloud run revision name collision

### ISSUE THREAD

**Issue by digitalnomd** [hashicorp/terraform-provider-google#14477]
Hello,

I’m running into the following bug with GCP for deploying Cloud Run instances:
```
Error: resource is in failed state "Ready:False", message: Found a conflicting revision name <my-cloud-run-instance987>. Revision names must be unique within the namespace.
```

I think the issue is that on Google's end they released a regression where the revision string only uses three characters and so sometimes there are collisions. In light of this I’m wondering if there are any workarounds, specifically one that would allow us to provide the revision string on our end so that we could set the revision ID to prevent a collision (e.g. include a sha-256 hash with 10 characters instead of 3)? Thanks!

**Comment by edwardmedia** [comment]
@digitalnomd It's hard to say what went wrong to hit this error. Can you share your config and detailed steps to repro this?

**Comment by greenozon** [comment]
@digitalnomd 
have you tried the [autogenerate_revision_name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#autogenerate_revision_name) = true  property in CR resource?

**Comment by edwardmedia** [comment]
@digitalnomd is this still an issue?

**Comment by digitalnomd** [comment]
This is still an issue. Using autogenerate_revision_name looks promising but haven't gotten a chance to try it yet.

It's hard to provide the exact configuration I'm using because it's all in code since I'm using cdktf.

**Comment by edwardmedia** [comment]
@digitalnomd please share once you have a chance to try

**Comment by digitalnomd** [comment]
@edwardmedia I tried using `autogenerate_revision_name=True` and I'm still getting the same issue. I think it has to do with the [cloud run name constraints](https://cloud.google.com/compute/docs/naming-resources#resource-name-format) since I'm only experiencing this with longer names at that length.

It seems like whatever code is appending a randomized string to the revision name, it's only using the last three characters for longer names. Instead it should be using more like the last 10 to prevent collisions.

**Comment by digitalnomd** [comment]
@edwardmedia the naming scheme already meets that requirement. It would be helpful to understand who is responsible for generating that revision string and how to get this resolved. It's not even clear what a mitigation would be beyond shortening the cloud run instance names which isn't guaranteed to work.

**Comment by digitalnomd** [comment]
Could you try again with a name that is 63 characters in length? I don't think you'll see a collision initially but the returned revision string should suggest one is likely to occur eventually.

It's probabilistic since that revision name has to be globally unique. By having only three random characters appended to the suffix, it's likely to occur eventually within a large enough code base.

**Comment by edwardmedia** [comment]
@digitalnomd if I increase the length of the name, I am sure it will hit the max eventually. From what I understand, the rule is managed by the api. You may reach out to the api to see if there is a way to work around it. I don't believe there is much we can do at the provider level. Am I answering your question?

**Comment by edwardmedia** [comment]
@digitalnomd  63 characters is a pretty large number. I guess you might need to consider shorten the names. By this moment, I don't think there is much we can do at the provider level. Closing the question now. Feel free to reopen if you want to continue the conversation
