### ISSUE TITLE
google_compute_network.network_firewall_policy_enforcement_order is not imported properly

### ISSUE THREAD

**Issue by LevOlkha** [hashicorp/terraform-provider-google#14470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
hashicorp/google 4.63.1

### Affected Resource(s)

google_compute_network

### Terraform Configuration Files

```tf
resource "google_compute_network" "xxx" {

  name        = "xxx"
  auto_create_subnetworks = false
  enable_ula_internal_ipv6 = false
}
```

### Expected Behavior
terraform plan should find no changes

### Actual Behavior
terraform plan marks the network to be replaced 
`+ network_firewall_policy_enforcement_order = "AFTER_CLASSIC_FIREWALL" # forces replacement`

### Steps to Reproduce

1. `terraform import google_compute_network.xxx projects/xxx/global/networks/XXX`
2. `terraform plan` 

regardless of setting `network_firewall_policy_enforcement_order` to a value or omitting, terraform always says that this is a new filed and the resources will be destroyed and recreated. 
Probably, value is not set properly during import command in state file 

### References

* #0000

**Comment by edwardmedia** [comment]
`network_firewall_policy_enforcement_order` needs to be C + O

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_network.go#L108

**Comment by rileykarson** [comment]
@edwardmedia I think the field might need to be default_if_empty. I'm assuming GCE has not backfilled the value for older resources, since that's something they forget to do somewhat often + it causes the same behaviour here.

**Comment by edwardmedia** [comment]
@LevOlkha trying to repro this. Following 2 steps you provided, I am not able to see below error. Could you detail the steps? 

```
+ network_firewall_policy_enforcement_order = "AFTER_CLASSIC_FIREWALL" # forces replacement
```

**Comment by edwardmedia** [comment]
@LevOlkha is this still an issue?

**Comment by LevOlkha** [comment]
Yes, it is still an issue.
I suspect that @rileykarson guess is correct.
It doesn't happens to some older resources only.

**Comment by LevOlkha** [comment]
it was problem with `4.63.1` but it is nit problem now with `4.65.2`
You can close the ticket

**Comment by edwardmedia** [comment]
@LevOlkha thank you for the update. Happy to close this issue now.
