### ISSUE TITLE
Cloud Run / Cloud Function: How to manage only a portion of the environment-variables

### ISSUE THREAD

**Issue by NicolaSpreafico** [hashicorp/terraform-provider-google#14471]
Hello,

while deploying a new Cloud Function: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions2_function

or a Cloud Run service:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service

there is the possibility to define environment-variables, like:
```
resource "google_cloud_run_service" "be_configurator_service" {
  name     = "foo"

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/placeholder"
		
        env {
          name  = "VAR1"
          value = "foo"
        }

        env {
          name  = "VAR2"
          value = "bar"
        }
      }
    }
  }
}
```
or 
```
resource "google_cloudfunctions2_function" "enqueuer" {
  name        = "hello-world"
  
  build_config {
    runtime     = "python311"
    entry_point = "entry_point"

    source {
      storage_source {
        bucket = "bucket"
        object = "object"
      }
    }
  }

  service_config {
    environment_variables = {
		VAR_ONE = "foo",
		VAR_TWO = "bar"
	}
  }
}
```

I have the following scenario which I need to understand if it's possible at all.

The env-var of my application are not entirely managed by Terraform:
- Half of the env-vars are managed by Terraform with the definition of other architectual resources (like topic, queues, other services, identities, ...)
- Half of the env-vars are purely on application level, and are managed by the CD pipeline which deploys new versions of the service. And we like to leave them here because they have nothing related to terraform and the developers can manage them directly without asking every time the team of Terraform to add more variables.

Of course you can imagine that every time Terraform or the pipeline run, it erase the unknown env-vars and put only the one managed. 

My goal here is to find any solution that can allow the 2 world coexist and allowing each one to manage the half portion of the env-vars related to them.

I know about the `--update-env-vars` flag which can allow you to update only a portion of env-var
https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--update-env-vars
https://cloud.google.com/sdk/gcloud/reference/run/deploy#--update-env-vars

but while I can implement something suitable on CD side, so that the application deployment can update only the env-vars related to it, I can't do something similar on Terraform side. The only idea I came up with is to remove the env-var declaration on the terraform resouce and use a secondary local-exec with a gcloud command that can leverage on the same --update-env-vars, but you can imagine how this can be hard to maintain.

My question is: is there a way (or if can be implemented for the future) to create a lifecycle/ignore_changes for specific keys of the environment variables instead of the whole block?

Thanks

**Comment by edwardmedia** [comment]
@NicolaSpreafico did you consider using variable files that can be shared by these resources?

**Comment by NicolaSpreafico** [comment]
@edwardmedia hello, can you elaborate on that?

**Comment by edwardmedia** [comment]
@NicolaSpreafico what I referred to is the file: [.tfvars](https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files)

**Comment by NicolaSpreafico** [comment]
@edwardmedia ok I understand.

The thing is, the architectural reference are generated directly by Terraform resources, so that part should be native as I cannot make a static file in advance.

The .tfvars you are suggesting can contains the partial variables related to the application scenario, but in any case the apply of that is in charge of the team manaing the architecture, and this is not suitable for the entire scenario as the developers should rely every time for the apply action.

I was looking more of a way to manage the env vars from 2 worlds. Terraform creates and put in place the variables for architectural reference, while the developers CD (entirely external from Terraform) can deploy the updated application code and set the portion of variables related to the application part.

**Comment by edwardmedia** [comment]
@NicolaSpreafico I am not sure if Terraform is a good tool to manage variables at the applications level.  One thing I can think of is 1) add steps in the pipeline by running gcloud (as you mentioned) 2) Chef or Ansible?

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer a question
