### ISSUE TITLE
google_compute_image does not allow SEV_SNP_CAPABLE for guest_os_features type

### ISSUE THREAD

**Issue by manuelbernhardt** [hashicorp/terraform-provider-google#14485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/google v4.63.1
+ provider registry.terraform.io/hashicorp/google-beta v4.63.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Affected Resource(s)

* google_compute_image

### Terraform Configuration Files

```tf
resource "google_compute_image" "benchmark-template-image" {
  provider = google-beta
  name = "benchmark-template-image-${google_compute_instance.benchmark-template-instance.instance_id}"
  source_snapshot = google_compute_snapshot.benchmark-template-snapshot.self_link
  guest_os_features {
    type = "GVNIC"
  }
  guest_os_features {
    type = "SEV_CAPABLE"
  }
  guest_os_features {
    type = "SEV_SNP_CAPABLE"
  }
  guest_os_features {
    type = "UEFI_COMPATIBLE"
  }
  guest_os_features {
    type = "VIRTIO_SCSI_MULTIQUEUE"
  }
  depends_on = [ google_compute_snapshot.benchmark-template-snapshot ]
```

### Expected Behavior

The resource gets created with the `SEV_SNP_CAPABLE` attribute set (see the [reference](https://cloud.google.com/compute/docs/reference/rest/beta/instances))

### Actual Behavior

The following error is returned:

```
Error: expected guest_os_features.2.type to be one of [MULTI_IP_SUBNET SECURE_BOOT SEV_CAPABLE UEFI_COMPATIBLE VIRTIO_SCSI_MULTIQUEUE WINDOWS GVNIC SEV_LIVE_MIGRATABLE], got SEV_SNP_CAPABLE
│
│   with module.gcp.module.gcp-node-template.google_compute_image.benchmark-template-image,
│   on modules/ce-benchmark-template/main.tf line 154, in resource "google_compute_image" "benchmark-template-image":
│  154: resource "google_compute_image" "benchmark-template-image" {
```

If the flag is not provided, `terraform apply` will work, but will re-create the resource every time as the flag is present in the image but not in the terraform configuration:

```
  # module.gcp.module.gcp-node-template.google_compute_image.benchmark-template-image must be replaced
-/+ resource "google_compute_image" "benchmark-template-image" {
      ~ archive_size_bytes = 3574231872 -> (known after apply)
      ~ creation_timestamp = "2023-05-03T05:58:07.046-07:00" -> (known after apply)
      ~ disk_size_gb       = 10 -> (known after apply)
      ~ id                 = "projects/project_id/global/images/benchmark-template-image-9055258460156850981" -> (known after apply)
      ~ label_fingerprint  = "42WmSpB8rSM=" -> (known after apply)
      - labels             = {} -> null
      ~ licenses           = [
          - "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/licenses/ubuntu-2204-lts",
        ] -> (known after apply)
        name               = "benchmark-template-image-9055258460156850981"
      ~ project            = "project_id" -> (known after apply)
      ~ self_link          = "https://www.googleapis.com/compute/v1/projects/project_id/global/images/benchmark-template-image-9055258460156850981" -> (known after apply)
        # (1 unchanged attribute hidden)

      - guest_os_features { # forces replacement
          - type = "SEV_SNP_CAPABLE" -> null
        }

        # (4 unchanged blocks hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* [GCP documentation for attribute disks[].initializeParams.guestOsFeatures[].type](https://cloud.google.com/compute/docs/reference/rest/beta/instances)

**Comment by rileykarson** [comment]
Assigning based on https://github.com/GoogleCloudPlatform/magic-modules/pull/7879

**Comment by shuyama1** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/7879
