### ISSUE TITLE
Cloud Build Trigger build step with `allowExitCodes` and `allowFailure` fields

### ISSUE THREAD

**Issue by dvanrhenen** [hashicorp/terraform-provider-google#14484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Within the `cloudbuild.yaml` [1], the REST API [2], as well as the Cloud Build UI, it is possible to specify the fields `allowExitCodes` and `allowFailure` per build step. These can be used to specify that a build step failure can be ignored as long as all other build steps in that build succeed, or when that step returns a particular exit code.

As the support for both `cloudbuild.yaml` and REST API are already in place, it would be nice to extend the `google_cloudbuild_trigger` resource with the capability to add both `allow_exit_codes` and `allow_failure` to the `build.step` configurations as well.

### New or Affected Resource(s)

* `google_cloudbuild_trigger`

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "build-trigger" {
  location = "global"

  trigger_template {
    branch_name = "main"
    repo_name   = "my-repo"
  }

  build {
    step {
      name           = "ubuntu"
      script         = "echo hello"
      allow_exit_codes = [1, 2] # Allowing exit codes 1 and 2
    }

    step {
      name         = "python"
      script       = "#!/usr/bin/env python\nprint('hello from python')\n"
      allow_failure = true # Allowing build step to fail
    }

    source {
      storage_source {
        bucket = "mybucket"
        object = "source_code.tar.gz"
      }
    }

    tags          = ["build", "newFeature"]
    substitutions = {
      _FOO = "bar"
      _BAZ = "qux"
    }
  }
}
```

### References

* [1] [Build configuration file schema - `allowExitCodes`](https://cloud.google.com/build/docs/build-config-file-schema#allowexitcodes)
* [2] [REST Resource: projects.builds - `Build.BuildStep.FIELDS.allow_exit_codes`](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build.BuildStep.FIELDS.allow_exit_codes)

**Comment by rileykarson** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/7866, should go out this week or next
