### ISSUE TITLE
google_secret_manager_secret_version does not correctly ignore changes to secret_value

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#14490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.4.4
provider registry.terraform.io/hashicorp/google v4.63.1

### Affected Resource(s)
google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret_version" "version" {
  secret      = google_secret_manager_secret.secret.id
  secret_data = "some data here"
  lifecycle {
    ignore_changes = [secret_data, enabled]
  }
}
```

### Expected Behavior
If a new value for secret_data is added to a new version in the secret (outside of terraform) then the ignore_changes lifecycle policy should prevent terraform from creating a new version.

### Actual Behavior
If a new value for secret_data is added to a new version in the secret (outside of terraform) then the ignore_changes lifecycle policy does not prevent terraform from creating a new version.   If the version that Terraform revers to is destroyed then terraform will create a new version which will make the latest version of the secret have an incorrect secret_data in it.

### Steps to Reproduce

1. `terraform apply`
2. add a new version to the secret outside of terraform and destroy the old version that Terraform created.
3. 'terraform apply'

### Important Factoids
since version isn't an input you can't do ignore_changes on it.
also related to https://github.com/hashicorp/terraform-provider-google/issues/14488

**Comment by edwardmedia** [comment]
@philip-harvey I am not sure if we can achieve below expected behavior as `ignore_changes` is for update. 

```
the ignore_changes lifecycle policy should prevent terraform from creating a new version.
```

**Comment by philip-harvey** [comment]
To destroy an old version of a secret via the GUI, select the secret (click on it), click the elipse under Actions and select Destroy.

**Comment by edwardmedia** [comment]
@philip-harvey in https://github.com/hashicorp/terraform-provider-google/issues/14488, I have explain what `terraform apply` is supposed to do. Do you see other resources that behave like what you said?

```
Currently it always points to the version Terraform created and ignores any newer version created outside of terraform
```

**Comment by philip-harvey** [comment]
In all other cases I am aware of a terraform apply will enforce the desired state, and for secrets this would be to have the latest version, which is the one that gets used, have the contents of the secret_data.  In this case the desired state is not working as expected and Terraform will never correct the state drift.

**Comment by philip-harvey** [comment]
Hi @edwardmedia in all other cases I'm aware of, putting a lifecycle ingnore_changes block will stop Terraform from trying to revert a change from outside of Terraform.  In this case this is not working as you would expect.   I can see why it's not working, it's due to the state tracking the version number and not referring to latest.    Probably the resource needs an additional flag.
e.g. enforce_latest_version = bool
so that Terraform knows if it should make sure that the version it is creating/tracking is the latest version and not just the version that it created.  If the resource was to switch to always tracking the latest version then this would break things for people who are used to it being stuck on tracking the version it created and be a breaking change.  Adding a new flag would make it a non-breaking change.

**Comment by c2thorn** [comment]
@philip-harvey following up from https://github.com/hashicorp/terraform-provider-google/issues/14488#issuecomment-1536626154, I think you want the functionality from the data source.

**Comment by philip-harvey** [comment]
Datasource doesn't help here, the issue is that if you set a lifecycle policy to ignore changes to secret_data then it does not and will overwrite the contents of the secret with whatever you have in secret_data in the resource call.

e.g. in my case I have an external secret that needs to be manually stuffed (can't be stuffed by Terraform), but I have to have a version in this secret or other things fail, so I create a version with secret_data = "REPLACE WITH THE ACTUAL SECRET" and set a lifecycle policy to ignore changes to this data.  Currently this does not work and if the "dummy" version is deleted then Terraform will create a new version and destroy my actual secret that was manually added.  There is another relevant open issue, https://github.com/hashicorp/terraform-provider-google/issues/13661, that Terraform will always destroy all old versions,  which is also in play here.

**Comment by edwardmedia** [comment]
Changing this to enhancement along with https://github.com/hashicorp/terraform-provider-google/issues/14488

**Comment by rileykarson** [comment]
@c2thorn @edwardmedia do we know why we don't read the secret data in the resource? If we did that, `ignore_changes` would work as intended.

**Comment by philip-harvey** [comment]
Hi @rileykarson  The secret_data is immutable, and since it only tracks the version it created currently it can never change.  It needs a way to read/track the latest version before it could work.

**Comment by rileykarson** [comment]
Thanks! I'm inclined to say that this one is working as intended- I think https://github.com/hashicorp/terraform-provider-google/issues/14488 will have the intended effect.
