### ISSUE TITLE
support Cloud Storage FUSE CSI Driver for GKE

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#14515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since May 2, Cloud Storage FUSE CSI Driver for GKE clusters is now available.
I would like you to enhance the addon so that it can be enabled in Terraform.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_container_cluster" "primary" {
  name               = "marcellus-wallace"
  location           = "us-central1-a"
  initial_node_count = 3
  
  # The new settings are shown below.
  addons_config {
    gcs_fuse_csi_driver_config {
      enabled = true
    }
  }
  
  node_config {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    labels = {
      foo = "bar"
    }
    tags = ["foo", "bar"]
  }
  timeouts {
    create = "30m"
    update = "40m"
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
* https://cloud.google.com/kubernetes-engine/docs/release-notes#May_02_2023

**Comment by megan07** [comment]
this should be closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/7884
