### ISSUE TITLE
Eliminate excluded resources in the provider

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#14510]
# Background
Excluded resources are a maintenance burden. They will incur duplicate work for our self service teams and almost guaranteed to get out of date. As I understand it, this pattern is needed for TFGC code, but I would prefer to supply the minimum meta data needed for that integration and source as much as possible from the generated provider itself. 

# What kind of contribution is this issue about?
MMv1-based resource

# Related PR(s), if any:

https://github.com/GoogleCloudPlatform/magic-modules/pull/7858

**Comment by rileykarson** [comment]
Note: I don't think this is required for TGC. I'm also not sure why service teams would need to duplicate work.

They _are_ required for IAM, although that's `exclude_resource` and not `exclude`.

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/12509
