### ISSUE TITLE
Add support for google_compute_region_security_policy

### ISSUE THREAD

**Issue by felipegc** [hashicorp/terraform-provider-google#14520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In order to increase support for policy type "CLOUD_ARMOR_NETWORK", the RegionSecurityPolicy must be created.

These objects are also required:

- type: CLOUD_ARMOR_NETWORK(must be included to work with ddos_protection_config)
- ddos_protection object

This configuration must be regional so we should create a new resource to add this capability.

### New or Affected Resource(s)

* google_compute_region_security_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

api reference: https://cloud.google.com/compute/docs/reference/rest/beta/regionSecurityPolicies

increase support for advanced network DDoS protection in existent google_compute_security_policy: https://github.com/hashicorp/terraform-provider-google/issues/13978:

**Comment by felipegc** [comment]
@rileykarson Currently the "google_compute_security_policy" is written in "Handwritten". Could you please help me defining if this new resource should also follow this path or if I should create it using "mmv1"?

**Comment by rileykarson** [comment]
@felipegc Hmm- it mostly depends on whether or not it can be. MMv1-based would be preferred, but consistency between the resources would be more important.

**Comment by felipegc** [comment]
Hi @rileykarson,
As far as I could see and test, it can be developed using mmv1. 
I also found that we have OrganizationSecurityPolicy which has been developed in mmv1. Besides that there are several pairs of policy/rules which are in separate resources, including OrganizationSecurityPolicy. I want to follow this approach of creating 2 resources: one for policy and one for rule because:
1- The apis provide the methods of (add/remove/patch)Rule and the terraform would map this behavior. Obs: the api explicitly says to use these methods while updating the rules.
2- Segregating the rule from policy it means they can “live” independently. For example in different terraform state.
3- Follows most of the policy/rules approaches
4- Mmv1 seems to be easier to maintain

Does it sounds reasonable?
Thanks

**Comment by imrannayer** [comment]
@felipegc r u planning to add `rules`, `adaptive_protection_config`,  `advanced_options_config`, and `recaptcha_options_config` in `google_compute_region_security_policy`

**Comment by felipegc** [comment]
> @felipegc r u planning to add `rules`, `adaptive_protection_config`, `advanced_options_config`, and `recaptcha_options_config` in `google_compute_region_security_policy`

Once they are public available. I have already mapped these tasks as next step. As far as I know they are currently only in private preview.

**Comment by imrannayer** [comment]
@felipegc It is in public preview. Should be available through beta API

https://cloud.google.com/compute/docs/reference/rest/beta/regionSecurityPolicies/list

**Comment by felipegc** [comment]
Though it is being shown on the api, some of these are not public which means must be under whitelisted project or it will not be supported for now.

As example, by exploring the api and trying to create a policy with "adataptative_protection_config" I receive the following error:
"Cloud Armor Adaptive Protection is currently not supported for regional policies"

When these features become available I will be working on them.

**Comment by melinath** [comment]
It looks like this was resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/7979
