### ISSUE TITLE
Issue when trying to create a tag binding with zonal resource

### ISSUE THREAD

**Issue by marcusricardoaguiar** [hashicorp/terraform-provider-google#14528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/aiven/aiven v4.2.1
+ provider registry.terraform.io/elastic/ec v0.5.1
+ provider registry.terraform.io/hashicorp/google v4.64.0
+ provider registry.terraform.io/hashicorp/google-beta v4.64.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/tfe v0.37.0

### Affected Resource(s)

* google_tags_location_tag_binding

### Terraform Configuration Files

```
resource "google_tags_location_tag_binding" "binding" {
  parent = "//compute.googleapis.com/projects/${data.google_project.project.number}/zones/us-central1-a/instances/instance1"
  tag_value = google_tags_tag_value.internal_tools_tag_value.id
  location = "us-central1-a"
}
```

### Debug Output

![image](https://github.com/hashicorp/terraform-provider-google/assets/8216333/084e1351-3da7-4fdd-b779-30e700de7fb4)

### Expected Behavior

It should create the binding.

### Actual Behavior

It creashed when trying to create the resource.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@marcusricardoaguiar I am able to run below config. Can you try it?

```tf
data "google_project" "project" {
}
resource "google_tags_tag_key" "key" {
	parent = "organizations/47440000001"
	short_name = "keynameissue14528"
	description = "For a certain set of resources."
}
resource "google_tags_tag_value" "value" {
	parent = "tagKeys/${google_tags_tag_key.key.name}"
	short_name = "issue14528"
	description = "For issue14528 resources."
}
resource "google_compute_instance" "default" {
	name         = "issue14528"
	machine_type = "e2-medium"
	zone         = "us-central1-a"
	boot_disk {
		initialize_params {
			image = "debian-cloud/debian-11"
		}
	}
	network_interface {
		 network = "default"
	}
}
resource "google_tags_location_tag_binding" "binding" {
	parent = "//compute.googleapis.com/projects/${data.google_project.project.number}/zones/us-central1-a/instances/${google_compute_instance.default.instance_id}"
	tag_value = "tagValues/${google_tags_tag_value.value.name}"
	location = "us-central1-a"
}
```

**Comment by edwardmedia** [comment]
@marcusricardoaguiar looks like project is supported. What error did you receive? Can you share your config?

[parent](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/tags_tag_key#parent) - (Required) Input only. The resource name of the new TagKey's parent. Must be of the form organizations/{org_id} or projects/{project_id_or_number}.

**Comment by marcusricardoaguiar** [comment]
Hey @edwardmedia , NVM. Now, I was able to make it work. My mistake was that I've used the name of instance instead of the id of the instance:
```
resource "google_tags_location_tag_binding" "binding" {
  parent = "//compute.googleapis.com/projects/${data.google_project.project.number}/zones/us-central1-a/instances/${google_compute_instance.instance.instance_id}"
  tag_value = "tagValues/${google_tags_tag_value.internal_tools_tag_value.name}"
  location = "us-central1-a"
}
```

Now, it's fine. I would recommend adding this example on terraform docs. We have one example for cloud_run there, but it's using the service name. :smile:
