### ISSUE TITLE
Tags unavailable on TF resources of Flexible Engine

### ISSUE THREAD

**Issue by habiba-gaddacha** [hashicorp/terraform-provider-google#14524]
Hello, 

For billing reports, I notice that tag management is missing for the following services : DWS (Data Warehouse Service) and OBS ( Object Storage Service).
We can add tags manually using the console but those terraform resources do not support tagging.

**Terraform Version**
Version v1.3.2

**Affected Resource(s)**
- flexibleengine_dws_cluster_v1
- flexibleengine_obs_bucket

Thanks in advance.

**Comment by rileykarson** [comment]
Was this meant for the https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine repo? Closing, I can reopen if that's not the case.
