### ISSUE TITLE
google_apigee_sharedflow_deployment update failure when used by google_apigee_flowhook

### ISSUE THREAD

**Issue by victorwongth** [hashicorp/terraform-provider-google#14530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/google v4.63.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Affected Resource(s)

* google_apigee_sharedflow
* google_apigee_sharedflow_deployment
* google_apigee_flowhook

### Terraform Configuration Files

Note that `${path.module}/sharedflowbundle_files.zip` expects a local zip file with an example provided on [Google Apigee docs](https://docs.apigee.com/api-platform/reference/shared-flow-bundle-configuration-reference).

```tf
resource "google_apigee_organization" "this" {
  project_id       = "test_org"
  display_name     = "test_org"
  runtime_type     = "HYBRID"
}

resource "google_apigee_environment" "this" {
  name         = "test_env"
  display_name = "test_env"
  org_id       = google_apigee_organization.this.org_id
}

data "archive_file" "sharedflow_bundle" {
  type        = "zip"
  source_dir  = "${path.module}/sharedflowbundle_files"
  output_path = "${path.module}/sharedflowbundle_files.zip"
}  
                                                                         
resource "google_apigee_sharedflow" "this" {
  name          = "test_sf"
  org_id        = google_apigee_organization.this.name
  config_bundle = data.archive_file.sharedflow_bundle.output_path
}

locals {
  latest_revision_id = max([for x in google_apigee_sharedflow.this.revision
: tonumber(x)]...)
}

resource "google_apigee_sharedflow_deployment" "this" {
  org_id        = google_apigee_organization.this.name
  environment   = google_apigee_environment.this.name
  sharedflow_id = google_apigee_sharedflow.this.name
  revision      = local.latest_revision_id
  lifecycle {
    create_before_destroy = true
  }
}

resource "google_apigee_flowhook" "this" {
  org_id          = google_apigee_organization.this.name
  environment     = google_apigee_environment.this.name
  flow_hook_point = "PreProxyFlowHook"
  sharedflow      = google_apigee_sharedflow.this.name
  depends_on = [
    google_apigee_sharedflow_deployment.this
  ]
}
```

### Debug Output

Note that I had to redact some of the identifiable data in the gist.

https://gist.github.com/victorwongth/3dec5a502c16f7534c67950a19c806de

### Panic Output

None

### Expected Behavior

When the underlying `sharedflowbundle_files.zip` changed, running the above Terraform code should deploy a new revision of the sharedflow.

### Actual Behavior

The new revision is actually deployed fine, but there would be an error:

```
Error: Error when reading or editing SharedflowDeployment: googleapi: Error 400: test_sf is attached to the PreProxyFlowHook FlowHook
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "<REDACTED>"
│   }
│ ]
```

From the logs this is because the provider is trying to [undeploy the old revision](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.sharedflows.revisions.deployments/undeploy).

When re-running the code, no changes are detected.

### Steps to Reproduce

1. Update content of the `sharedflowbundle_files.zip` where an example can be found in [Google Apigee docs](https://docs.apigee.com/api-platform/reference/shared-flow-bundle-configuration-reference)
2. `terraform apply`

### Important Factoids

None

### References

* https://docs.apigee.com/api-platform/reference/shared-flow-bundle-configuration-reference
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_sharedflow_deployment
* https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.sharedflows.revisions.deployments/undeploy

**Comment by edwardmedia** [comment]
@victorwongth I am having hard time to repro. But I notice the error in your log. It seems failing in deleting the deployment. Are you aware of anythimng that is still tied to the deployment?

```
REDACTED-SHAREDFLOW is attached to the PreProxyFlowHook FlowHook
```

DELETE /v1/organizations/REDACTED-ORGANIZATION/environments/REDACTED-ENVIRONMENTS/sharedflows/REDACTED-SHAREDFLOW/revisions/12/deployments

**Comment by victorwongth** [comment]
Hey @edwardmedia thank you for looking into this so quickly. The `REDACTED-SHAREFLOW` is indeed still attached to the PreProxyFlowHook. 

If you consider the interaction between the flowhook, sharedflow and sharedflow deployment:
- `sharedflow` is deployed by `sharedflow deployment`
- `sharedflow` is attached to `flowhook`
- `sharedflow deployment` cannot be deleted when `sharedflow` is attached to `flowhook` 

When the `Sharedflow deployment` is **recreated** by Terraform, it first created a new deployment successfully then attempted to delete the old deployment which is an unnecessary step. The `Sharedflow` is still attached to the flowhook all this time and it would be wrong to detach the `sharedflow` temporarily because this would lead to unintended behavior with the proxies.

Another way to understand the problem is to think about the equivalent steps on the UI: 
1. Updating the `sharedflow`
2. Deploying the `sharedflow`
Throughout these steps the `sharedflow` remains attached to the flowhook and deleting an old deployment version was never needed.

**Comment by victorwongth** [comment]
In conclusion I think the logic that Terraform performs by **recreating** the resource is wrong: 
1. deleting the old resource by calling this [undeploy API](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.sharedflows.revisions.deployments/undeploy)
2. creating the new resource by calling this [deploy API](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.sharedflows.revisions.deployments/deploy)

Terraform should use in-place update calling [deploy API](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.sharedflows.revisions.deployments/deploy) with the `override` parameter set to true, as explained in the doc:
> If another revision of the same shared flow is currently deployed, set the override parameter to true to have this revision replace the currently deployed revision.

**Comment by edwardmedia** [comment]
@victorwongth I kind of agree with you but I am not able to prove it. @megan07  can you help check?
