### ISSUE TITLE
Failing test(s): TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#14535]
### Failure rates

- 100% since 2023-05-03

### Impacted tests

- Addressed:
     - ~TestAccComputeFirewallPolicyRule_multipleRules~
     - ~TestAccComputeFirewallPolicyRule_update~
- Test failures as-of July 2023:
     - TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten
     - TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten

### Affected Resource(s)

* google_network_security_address_group

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/398232?mode=builds&buildTab=tests&expandedTest=-1848297138890150638)

### Message(s)

```
Error: Invalid resource type
```

**Comment by megan07** [comment]
This resource should be beta-only and the tests shouldn't be showing up in TPG, these tests pass in beta

**Comment by SarahFrench** [comment]
Looks like there's a hangover from this issue, it's still failing 100% but looks like this original issue was for something else that was fixed. Previously the test didn't run at all, now there's this issue:

[Test history](https://ci-oss.hashicorp.engineering/test/8973049031858672392?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A414603%29%2Cid%3A2000001097) for TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten

```
------- Stdout: -------
=== RUN   TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten
=== PAUSE TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten
=== CONT  TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten
    vcr_utils.go:152: Step 3/4 error: Error running pre-apply refresh:
        Error: Inconsistent dependency lock file
        The following dependency selections recorded in the lock file are
        inconsistent with the current configuration:
          - provider registry.terraform.io/hashicorp/google-beta: required by this configuration but no version is selected
        To make the initial dependency selections that will initialize the dependency
        lock file, run:
          terraform init
    testing_new.go:84: Error running post-test destroy, there may be dangling resources:
        Error: Inconsistent dependency lock file
        The following dependency selections recorded in the lock file are
        inconsistent with the current configuration:
          - provider registry.terraform.io/hashicorp/google-beta: required by this configuration but no version is selected
        To make the initial dependency selections that will initialize the dependency
        lock file, run:
          terraform init
--- FAIL: TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten (112.54s)
FAIL
```

**Comment by roaks3** [comment]
This test appears to be passing now. Since Aug 10, I'm seeing 100% success for both tests.
