### ISSUE TITLE
gcloud compute images create

### ISSUE THREAD

**Issue by intotecho** [hashicorp/terraform-provider-google#14554]
[gcloud compute images](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_image#kms_key_self_link) [Version 4.64.] doesn't expose all the options in [gcloud compute images create](https://cloud.google.com/sdk/gcloud/reference/compute/images/create)  

For example:
`gcloud compute images create ...

[--csek-key-file=FILE]  --forbidden-database-file=[DBX_VALUE]

[--key-exchange-key-file=[KEK_VALUE,…]] 

[--platform-key-file=PLATFORM_KEY_FILE] 

[--no-require-csek-key-create] 

[--signature-database-file=[DB_VALUE,…]] 

[--kms-key=KMS_KEY : --kms-keyring=KMS_KEYRING --kms-location=KMS_LOCATION --kms-project=KMS_PROJECT]
`
I am wondering if I can use terraform to sign a UEFI image. Is there a way to supply some of these arguments to a terraform module?

**Comment by edwardmedia** [comment]
@intotecho that is true. Not all fields are supported yet. What specific arguments do you refer to? If not, you may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) to request.

**Comment by edwardmedia** [comment]
@intotecho closing this now. Please file enhancements for requesting new fields
