### ISSUE TITLE
support AdditionalPodRangesConfig in GKE Autopilot cluster

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#14552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since May 9th, GKE Autopilot cluster can be set additional IPv4 secondary Pod ranges.
Terraform will be able to set it as well.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_compute_network" "main" {
  name                    = "gke-autopilot"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "main" {
  ip_cidr_range = "10.10.0.0/16"
  name          = "gke-autopilot"
  network       = google_compute_network.main.self_link
  region        = "asia-northeast1"

  secondary_ip_range {
    range_name    = "gke-autopilot-services"
    ip_cidr_range = "10.11.0.0/20"
  }

  secondary_ip_range {
    range_name    = "gke-autopilot-pods"
    ip_cidr_range = "10.12.0.0/16"
  }

  secondary_ip_range {
    range_name    = "gke-autopilot-pods-add"
    ip_cidr_range = "10.100.0.0/16"
  }
}

# Create a GKE cluster with autopilot mode enabled with Terraform.
# https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster
resource "google_container_cluster" "main" {
  name     = "gke-autopilot"
  location = "asia-northeast1"

  enable_autopilot = true

  release_channel {
    channel = "REGULAR"
  }

  network    = google_compute_network.main.name
  subnetwork = google_compute_subnetwork.main.name

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = true
    master_ipv4_cidr_block  = "172.16.0.0/28"
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = "gke-autopilot-pods"
    services_secondary_range_name = "gke-autopilot-services"
  }

  # The new settings are as follows.
  additional_pod_ranges_config {
    pod_range_names = [
      "gke-autopilot-pods-add",
    ]
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/release-notes#May_09_2023
* https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr#add_more_pod_ranges_autopilot
* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#additionalpodrangesconfig

**Comment by madushan1000** [comment]
It should work with standard clusters too with kuberntes version 1.26.0+ (https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr#add_more_pod_ranges_autopilot)

**Comment by jeperetz** [comment]
I'm addressing this in https://github.com/GoogleCloudPlatform/magic-modules/pull/8622

**Comment by shuyama1** [comment]
Closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/8622
