### ISSUE TITLE
`google_cloud_run_v2_service` reuses revision for changes to resource; Error 409 revision named '<rev>' already exists

### ISSUE THREAD

**Issue by Daniel-I-Am** [hashicorp/terraform-provider-google#14569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.64.0
```

### Affected Resource(s)

* resource.google_cloud_run_v2_service

### Terraform Configuration Files

```tf
variable "region" {
  type = string
}

variable "project" {
  type = string
}

provider "google" {
  project               = var.project
  region                = var.region
  user_project_override = true
}

resource "google_cloud_run_v2_service" "cloud_run_service" {
  project     = var.project
  name        = "sample-cloud-run"
  description = "Testing for a bug report"
  location    = var.region
  ingress     = "INGRESS_TRAFFIC_INTERNAL_ONLY"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"

      ports {
        container_port  = 8080
        name            = "http1"
      }

#      env {
#        name  = "SOME_VARIABLE"
#        value = "SOME VALUE"
#      }

      resources {
        cpu_idle = true

        limits = {
          memory = "512Mi"
          cpu    = 1
        }
      }
    }

    scaling {
      min_instance_count = 0
      max_instance_count = 5
    }
  }

  depends_on = [
    google_project_service.run
  ]

  lifecycle {
    ignore_changes = [
      annotations["client.knative.dev/user-image"],
      template[0].annotations["client.knative.dev/user-image"],
      template[0].containers[0].image,

      client,
      client_version,
      template[0].revision,
    ]
  }
}

resource "google_project_service" "run" {
  project            = var.project
  service            = "run.googleapis.com"
  disable_on_destroy = false
}
```

### Debug Output

Notes:
* Replaced my email with `daniel.<username>@<my-company>.com`
* Replaced my project ID with `<my-project>`

https://gist.github.com/Daniel-I-Am/18fc959b1fc4b3a6b9ac615502af7af1

### Expected Behavior

When deploying a cloud run service using the new `v2` resource where the image is managed by an outside source, I expect to be able to still update other fields from Terraform.

My use-case is the following:
The resource is managed by terraform, but the image is updated from a CI-job using `gcloud run deploy`. When adding a new environment variable or secret, I want to continue being able to do that from Terraform.

### Actual Behavior

In the old resource `google_cloud_run_service` there is a field `autogenerate_revision_name` to accomplish this goal. The new `google_cloud_run_v2_service` does not have this field and attempts to update the resource without adjusting the revision. This causes a conflict error (409) to be returned from the API:

> Error: Error updating Service "projects/&lt;my-project&gt;/locations/europe-west1/services/sample-cloud-run": googleapi: Error 409: Revision named 'sample-cloud-run-00002-yeg' with different configuration already exists.

### Steps to Reproduce

1. Deploy cloud run service using terraform: `terraform apply`
2. Create new revision using gcloud: `gcloud run deploy sample-cloud-run --project=<project> --region europe-west1 --image "us-docker.pkg.dev/cloudrun/container/hello"`
3. Deploy cloud run service again: `terraform apply` (there should not be any pending changes)
4. Change the resource (see the commented out `env` block in the configuration above).
5. Apply the change: `terraform apply`

```
Terraform will perform the following actions:

  # google_cloud_run_v2_service.cloud_run_service will be updated in-place
  ~ resource "google_cloud_run_v2_service" "cloud_run_service" {
        id                      = "projects/<my-project>/locations/europe-west1/services/sample-cloud-run"
        name                    = "sample-cloud-run"
        # (20 unchanged attributes hidden)

      ~ template {
            # (7 unchanged attributes hidden)

          ~ containers {
                # (3 unchanged attributes hidden)

              + env {
                  + name  = "SOME_VARIABLE"
                  + value = "SOME VALUE"
                }

                # (3 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_cloud_run_v2_service.cloud_run_service: Modifying... [id=projects/<my-project>/locations/europe-west1/services/sample-cloud-run]
╷
│ Error: Error updating Service "projects/<my-project>/locations/europe-west1/services/sample-cloud-run": googleapi: Error 409: Revision named 'sample-cloud-run-00002-yeg' with different configuration already exists.
│ 
│   with google_cloud_run_v2_service.cloud_run_service,
│   on test-cr.tf line 1, in resource "google_cloud_run_v2_service" "cloud_run_service":
│    1: resource "google_cloud_run_v2_service" "cloud_run_service" {
```

**Comment by edwardmedia** [comment]
@Daniel-I-Am following your steps, I am not able to repro the issue. No matter how I update the service through outside terraform, I always see a new revision is created and which is marked as ACTIVE. 

After step2, what do you see if you run below command? Do you see a new ACTIVE revision for `sample-cloud-run`?

```
 gcloud run revisions list
```

For step2, instead of  `gcloud run deploy sample-cloud-run`, have you tried to use `gcloud run services update` to see if that makes any difference?

If that does not help, could you share your full debug log?

**Comment by Daniel-I-Am** [comment]
Hrm, after your message, I ran through everything again. I can still reproduce it.

<details><summary>Results of running through everything</summary>
<blockquote>
With my example configuration above:

* `terraform init`
* `terraform apply`

```
$ gcloud --project <my-project> run revisions list --region europe-west1 | grep 'sample-cloud-run'
✔  sample-cloud-run-00001-cjb     yes     sample-cloud-run     2023-05-12 07:59:43 UTC  daniel.<username>@<my-company>.com
$ gcloud run deploy sample-cloud-run --project=<my-project> --region europe-west1 --image "us-docker.pkg.dev/cloudrun/container/hello"
Deploying container to Cloud Run service [sample-cloud-run] in project [<my-project>] region [europe-west1]
✓ Deploying... Done.
  ✓ Creating Revision...
  ✓ Routing traffic...
Done.
Service [sample-cloud-run] revision [sample-cloud-run-00002-wes] has been deployed and is serving 100 percent of traffic.
Service URL: https://sample-cloud-run-gwlgi3gxva-ew.a.run.app
$ gcloud --project <my-project> run revisions list --region europe-west1 | grep 'sample-cloud-run'
✔  sample-cloud-run-00002-wes     yes     sample-cloud-run     2023-05-12 08:00:33 UTC  daniel.<username>@<my-company>.com
✔  sample-cloud-run-00001-cjb             sample-cloud-run     2023-05-12 07:59:43 UTC  daniel.<username>@<my-company>.com
```

* `terraform apply` (no changes are detected)

Then I change my HCL to add the environment variable:
```diff
31,34c31,34
< #      env {
< #        name  = "SOME_VARIABLE"
< #        value = "SOME VALUE"
< #      }
---
>       env {
>         name  = "SOME_VARIABLE"
>         value = "SOME VALUE"
>       }
```

* `terraform apply`

```
Terraform will perform the following actions:

  # google_cloud_run_v2_service.cloud_run_service will be updated in-place
  ~ resource "google_cloud_run_v2_service" "cloud_run_service" {
        id                      = "projects/<my-project>/locations/europe-west1/services/sample-cloud-run"
        name                    = "sample-cloud-run"
        # (20 unchanged attributes hidden)

      ~ template {
            # (7 unchanged attributes hidden)

          ~ containers {
                # (3 unchanged attributes hidden)

              + env {
                  + name  = "SOME_VARIABLE"
                  + value = "SOME VALUE"
                }

                # (3 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_cloud_run_v2_service.cloud_run_service: Modifying... [id=projects/<my-project>/locations/europe-west1/services/sample-cloud-run]
╷
│ Error: Error updating Service "projects/<my-project>/locations/europe-west1/services/sample-cloud-run": googleapi: Error 409: Revision named 'sample-cloud-run-00002-wes' with different configuration already exists.
│
│   with google_cloud_run_v2_service.cloud_run_service,
│   on main.tf line 15, in resource "google_cloud_run_v2_service" "cloud_run_service":
│   15: resource "google_cloud_run_v2_service" "cloud_run_service" {
```
</blockquote>
</details> 

Doing the same with `gcloud --project <my-project> run services update --region europe-west1 sample-cloud-run --image us-docker.pkg.dev/cloudrun/container/hello` creates a revision as well.

```
➜  test-14569 gcloud --project <my-project> run services update --region europe-west1 sample-cloud-run --image us-docker.pkg.dev/cloudrun/container/hello
✓ Deploying... Done.
  ✓ Creating Revision...
  ✓ Routing traffic...
Done.
Service [sample-cloud-run] revision [sample-cloud-run-00002-qef] has been deployed and is serving 100 percent of traffic.
Service URL: https://sample-cloud-run-gwlgi3gxva-ew.a.run.app
Took 12 seconds
➜  test-14569 gcloud --project <my-project> run revisions list --region europe-west1 | grep 'sample-cloud-run'
✔  sample-cloud-run-00002-qef     yes     sample-cloud-run     2023-05-12 08:13:42 UTC  daniel.<username>@<my-company>.com
✔  sample-cloud-run-00001-tkv             sample-cloud-run     2023-05-12 08:12:32 UTC  daniel.<username>@<my-company>.com
```

* `terraform apply`
* make the HCL change
* `terraform apply`

Same issue again.

Regarding a debug log, is the one I have attached in the original report sufficient, or are you looking for other information?
https://gist.github.com/Daniel-I-Am/18fc959b1fc4b3a6b9ac615502af7af1

From what I can tell in the debug log, the providers send the request to update the service with the same revision set. https://gist.github.com/Daniel-I-Am/18fc959b1fc4b3a6b9ac615502af7af1#file-debug-log-L1367

**Comment by edwardmedia** [comment]
@Daniel-I-Am why do you want to add `template[0].revision` in the lifecycle.ignore_changes? Can you try by removing it?

```tf
resource "google_cloud_run_v2_service" "cloud_run_service" {

  lifecycle {
    ignore_changes = [
...
      template[0].revision,
    ]
  }
}

**Comment by lsnider** [comment]
We are running into the same issue.  If we don't add an ignore_changes for template[0].revision, then terraform will do a release every time it runs after a github action release.  If we do ignore changes on the template[0].revision, we get the name conflicted listed above.  I could post our terraform file but it's not materially different from what is already posted.

**Comment by edwardmedia** [comment]
@lsnider I guess I am not sure what you referred below. Without template[0].revision in ignore_changes, do you see proposed changes in the plan even no changes in the config?

```
 terraform will do a release every time it runs after a github action release
```

**Comment by Daniel-I-Am** [comment]
Hey @edwardmedia  I added the ignore for `template[0].revision` in order to not revert any changes to the revision from Terraform. Think of the following situation:
* terraform deployed revision 1
* gcloud deployed revision 2
* terraform notices the change to the revision and attempts to unset it, causing a new deployment (when none is needed)

---

With the above configuration, but without the ignore for the `template[0].revision`, I went through my steps again.
1. Deploy cloud run service using terraform: terraform apply
2. Create new revision using gcloud: gcloud run deploy sample-cloud-run --project=<project> --region europe-west1 --image "us-docker.pkg.dev/cloudrun/container/hello"
3. Deploy cloud run service again: terraform apply (there should not be any pending changes)

But without the ignore, there are changes pending here:
```
$ terraform plan
google_project_service.run: Refreshing state... [id=<my-project>/run.googleapis.com]
google_cloud_run_v2_service.cloud_run_service: Refreshing state... [id=projects/<my-project>/locations/europe-west1/services/sample-cloud-run]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_v2_service.cloud_run_service will be updated in-place
  ~ resource "google_cloud_run_v2_service" "cloud_run_service" {
        id                      = "projects/<my-project>/locations/europe-west1/services/sample-cloud-run"
        name                    = "sample-cloud-run"
        # (20 unchanged attributes hidden)

      ~ template {
          - revision                         = "sample-cloud-run-00002-waj" -> null
            # (6 unchanged attributes hidden)

            # (2 unchanged blocks hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

You can apply this change, which will create a new (identical) revision. I did not apply the change here. I make my configuration change to alter the environment variables.

4. Change the resource (see the commented out env block in the configuration above).
5. Apply the change: terraform apply

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_v2_service.cloud_run_service will be updated in-place
  ~ resource "google_cloud_run_v2_service" "cloud_run_service" {
        id                      = "projects/speeltuin-daniel/locations/europe-west1/services/sample-cloud-run"
        name                    = "sample-cloud-run"
        # (20 unchanged attributes hidden)

      ~ template {
          - revision                         = "sample-cloud-run-00002-fix" -> null
            # (6 unchanged attributes hidden)

          ~ containers {
                # (3 unchanged attributes hidden)

              + env {
                  + name  = "SOME_VARIABLE"
                  + value = "SOME VALUE"
                }

                # (3 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I added the debug output of this apply to my gist as well: https://gist.github.com/Daniel-I-Am/18fc959b1fc4b3a6b9ac615502af7af1#file-debug-without-revision-ignore-log

---

While this does not cause an error to occur, this does mean Terraform will remove any change in revision after external deployment. So Terraform will always show a change in revision (from whatever it is set to to `null`) after a deployment using `gcloud`.

I don't think there's a way for me to tell Terraform to ignore change to `template[0].revision` if it is the **only** changed attribute, while still resetting it to `null` when other attributes have changed... That would be the desired behaviour.

**Comment by edwardmedia** [comment]
@Daniel-I-Am I understand your use case, but I am not sure there is a perfect solution for it. It is hard to consolidate the methods between imperative and declarative approaches. 

From the provider's perspective, I think it works as expected. Do you agree?

**Comment by Daniel-I-Am** [comment]
> It is hard to consolidate the methods between imperative and declarative approaches.

That has always been a struggle with Terraform :sweat_smile: 

I think looking at it from the provider's perspective, it makes a lot of sense what is happening. I just wish we would have the `autogenerate_revision_name` from the v1 `google_cloud_run_service` so we don't have this issue.

At least, removing the ignore_changes on the `template[0].revision` fixed the error occuring and does not seem to reset the revision at every deployment (which I had apparently assumed without validating).

This means the resource can be managed by Terraform, however, every deployment will cause a redeployment of the cloud run service when `terraform apply` is run. For our cloud run services deployed from a CI pipeline outside of our infra repo, I think I will stay with the v1 `google_cloud_run_service` for now to remove the added clutter.

Thanks for the quick responses in any case :slightly_smiling_face:

**Comment by lsnider** [comment]
> @lsnider I guess I am not sure what you referred to below. Without template[0].revision in ignore_changes, do you see proposed changes in the plan even no changes in the config?
> 
> ```
>  terraform will do a release every time it runs after a github action release
> ```
> 
> I assume there is no step 2 mentioned [here](https://github.com/hashicorp/terraform-provider-google/issues/14569#issue-1705338856) in your case.

There is step 2 in my use case too.  In my example, the external revision comes from GitHub actions when a developer releases code (instead of gcloud via CLI).  So outside of the CLI/Github Actions difference, my issue reads exactly like what @Daniel-I-Am is describing.  I too was hoping for a `autogenerate_revision_name` in `google_cloud_run_v2_service` as it sounds like it'll fix the issue.

**Comment by N214** [comment]
Same use case, same issue here.
