### ISSUE TITLE
`google_container_cluster` disabling "cluster.master_authorized_networks_config.gcp_public_cidrs_access_enabled" on public cluster is not supported

### ISSUE THREAD

**Issue by Evesy** [hashicorp/terraform-provider-google#14575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

TF: `1.3.6`
Provider: `4.46.0`

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "cluster" {
  provider = google-beta
  name     = local.prefix

  depends_on = [
    google_compute_subnetwork.vpc_subnet
  ]

  location           = var.zone
  node_locations     = var.additional_zones
  enable_legacy_abac = false

  logging_config {
    enable_components = [
      "SYSTEM_COMPONENTS"
    ]
  }

  lifecycle {
    ignore_changes = [
      initial_node_count,
      node_config,
      min_master_version,
      node_version,
      logging_service,
      maintenance_policy["maintenance_exclusion"]
    ]
  }

  workload_identity_config {
    workload_pool = "${var.project}.svc.id.goog"
  }

  # This bit largely doesn't matter as we delete the default node pool anyway
  initial_node_count = 1

  # Enable shielded nodes
  enable_shielded_nodes = true

  node_config {
    machine_type = "n1-standard-4"
    disk_size_gb = "50"
    oauth_scopes = var.gke_node_scopes
    preemptible  = "false"
  }

  remove_default_node_pool = true

  # Disable basic auth
  master_auth {
    client_certificate_config {
      issue_client_certificate = true
    }
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "1.1.1.1/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "2.2.2.2/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "3.3.3.3/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "4.4.4.4/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "5.5.5.5/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "6.6.6.6/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "7.7.7.7/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "8.8.8.8/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "9.9.9.9/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "10.10.10.10/32"
      display_name = "-"
  }
    cidr_blocks {
      cidr_block   = "11.11.11.11/32"
      display_name = "-"
    }
    cidr_blocks {
      cidr_block   = "12.12.12.12/32"
      display_name = "-"
  }
}

  # Explicitly disable PodSecurityPolicy
  pod_security_policy_config {
    enabled = false
  }

  # Enable network policy for custom rules
  network_policy {
    enabled  = true
    provider = "CALICO"
  }

  # Network configuration
  network    = "projects/${var.network_project}/global/networks/${var.network}"
  subnetwork = "projects/${var.network_project}/regions/${var.region}/subnetworks/${google_compute_subnetwork.vpc_subnet.name}"

  # Logging and monitoring configuration
  #monitoring_service = "monitoring.googleapis.com/kubernetes"
  #logging_service    = "logging.googleapis.com/kubernetes"
  monitoring_service = "none"
  logging_service    = "none"

  min_master_version = var.master_version

  node_version = var.node_version

  release_channel {
    channel = var.release_channel
  }

  # Add on configuration
  addons_config {
    http_load_balancing {
      disabled = false
    }

    horizontal_pod_autoscaling {
      disabled = false
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = "${local.prefix}-pods"
    services_secondary_range_name = "${local.prefix}-services"
  }

  maintenance_policy {
    recurring_window {
      start_time = "2019-08-01T07:00:00Z"
      end_time   = "2019-08-01T11:00:00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"
    }
  }

  dynamic notification_config {
    for_each = var.cluster_notifications_enabled ? [1] : []
    content {
      pubsub {
        enabled = true
        topic = google_pubsub_topic.cluster-notifications[0].id
      }
    }
  }

  timeouts {
    create = "20m"
    delete = "40m"
    update = "24h"
  }
}
```

### Debug Output

https://gist.github.com/Evesy/a625f12eaf952bfd325544c5d1c2deb8

### Expected Behavior

Removing `cidr_blocks` from `master_authorized_networks_config` on a public cluster should happen without issue

### Actual Behavior

Terraform tries to update the cluster with `gcpPublicCidrsAccessEnabled: false` which fails, as this cannot be disabled on a public cluster.

- The existing TF state has `gcpPublicCidrsAccessEnabled` set to false.
- The actual GKE cluster resource (`gcloud describe container cluster...`) does not return `gcpPublicCidrsAccessEnabled` at all
- The cluster is a public GKE cluster

I suspect given the cluster type, TF should be defaulting `gcp_public_cidrs_access_enabled` to true when not set

**Comment by edwardmedia** [comment]
@Evesy it works fine me with below request. Can you detail the steps to repro the error?

```
PUT /v1/projects/myproject/locations/us-central1-a/clusters/issue14575?alt=json&prettyPrint=false HTTP/1.1
Host: container.googleapis.com
{
 "update": {
  "desiredMasterAuthorizedNetworksConfig": {
   "cidrBlocks": [
    {
     "cidrBlock": "1.1.1.1/32",
     "displayName": "-"
    },
    {
     "cidrBlock": "1.1.1.2/32",
     "displayName": "-"
    }
   ],
   "enabled": true,
   "gcpPublicCidrsAccessEnabled": false
  }
 }
}
```

**Comment by Evesy** [comment]
@edwardmedia Is the cluster you're using a public cluster? Specifically looking at these [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks#access_to_control_plane_endpoints) I think our cluster would be a 'legacy public cluster with public endpoints' which cannot have public cidr access disabled.

Our cluster has existed prior to the addition of `gcp_public_cidrs_access_enabled` support in the provider, so I suspect the state has been incorrectly defaulted to `false` for our cluster, when it is in fact implicitly enabled.

Explicitly setting `gcp_public_cidrs_access_enabled` to `true` in our TF config has provided a workaround, and now the cluster resources itself in GCP has `gcpPublicCidrsAccessEnabled` set to `true` (Whereas previously it was omitted entirely. Again I suspect this configuration was added at some point but not explicitly set on existing clusters

**Comment by edwardmedia** [comment]
@Evesy yes, that feature was added in https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.45.0

**Comment by edwardmedia** [comment]
@Evesy assuming the workaround works. This is a edge case and I don't think code change is needed to cover it. Closing this now.
