### ISSUE TITLE
False positive diff in `google_cloud_tasks_queue` resources on field `app_engine_routing_override`

### ISSUE THREAD

**Issue by artusiep** [hashicorp/terraform-provider-google#14571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
❯ terraform -v
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.64.0
```

### Affected Resource(s)

* google_cloud_tasks_queue

### Terraform Configuration Files

This is a terraform module I use for creation cloud_task.

```tf
variable "name" {
  type        = string
  description = "name of the task"
}

variable "location" {
  type        = string
  description = "location of  the task"
}

variable "project_id" {
  description = "name of the project"
}

variable "retry_config" {
  default     = {}
  description = "If a job does not complete successfully, Ifan acknowledgement is not received from the handler, then it will be retried with mentioned configuration"
}

variable "rate_limits" {
  default     = {}
  description = "Rate limits for task dispatches."
}

variable "app_engine_routing_override" {
  type       = object({
    service = optional(string)
    version = optional(string)
    instance = optional(string)
  })
  default = {}
  description = "App Engine Routing for the task. If set, app_engine_routing_override is used for all tasks in the queue, no matter what the setting is for the task."
}

resource "google_cloud_tasks_queue" "this" {
  project  = var.project_id
  name     = var.name
  location = var.location
  dynamic "retry_config" {
    for_each = var.retry_config != {} ? [var.retry_config] : toset([])
    content {
      max_attempts       = try(retry_config.value.max_attempts, null)
      max_retry_duration = try(retry_config.value.max_retry_duration, null)
      max_backoff        = try(retry_config.value.max_backoff, null)
      min_backoff        = try(retry_config.value.min_backoff, null)
      max_doublings      = try(retry_config.value.max_doublings, null)
    }
  }
  dynamic "rate_limits" {
    for_each = var.rate_limits != {} ? [var.rate_limits] : toset([])
    content {
      max_concurrent_dispatches = try(rate_limits.value.max_concurrent_dispatches, null)
      max_dispatches_per_second = try(rate_limits.value.max_dispatches_per_second, null)
      max_burst_size            = try(rate_limits.value.max_burst_size, null)
    }
  }
  dynamic "app_engine_routing_override" {
    for_each = var.app_engine_routing_override != {} ? [var.app_engine_routing_override] : []
    content {
      service = try(var.app_engine_routing_override.service, null)
      version = try(var.app_engine_routing_override.version, null)
      host    = try(var.app_engine_routing_override.host, null)
    }
  }
}
```

### Panic Output

No panic output

### Expected Behavior

Terraform should not try to update in place in case  `dynamic "app_engine_routing_override"` is empty.

### Actual Behavior

Creation of `"google_cloud_tasks_queue"` resource without any `"app_engine_routing_override"`  was successful

Here is content invoking module:
```tf
module "abc" {
  source = "../modules/cloud_tasks"
  location = "europe-west1"
  name = "some-name"
  project_id = "artusiep-project"
}
```

```
❯ tf apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.abc.google_cloud_tasks_queue.this will be created
  + resource "google_cloud_tasks_queue" "this" {
      + id       = (known after apply)
      + location = "europe-west1"
      + name     = "some-name"
      + project  = "artusiep-project"

      + app_engine_routing_override {
          + host = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "default"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.abc.google_cloud_tasks_queue.this: Creating...
module.abc.google_cloud_tasks_queue.this: Creation complete after 1s [id=projects/artusiep-project/locations/europe-west1/queues/some-name]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

But terraform keep trying to update the resource seeing diff in `"app_engine_routing_override"` configuration

```
❯ tf plan
module.abc.google_cloud_tasks_queue.this: Refreshing state... [id=projects/artusiep-project/locations/europe-west1/queues/some-name]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.abc.google_cloud_tasks_queue.this will be updated in-place
  ~ resource "google_cloud_tasks_queue" "this" {
        id       = "projects/artusiep-project/locations/europe-west1/queues/some-name"
        name     = "some-name"
        # (2 unchanged attributes hidden)

      + app_engine_routing_override {}

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create module based on Terraform Configuration Files
2.  Add invocation of the module
```tf
module "abc" {
  source = "../modules/cloud_tasks"
  location = "europe-west1"
  name = "some-name"
  project_id = "artusiep-project"
}
```
3. `terraform apply`
4. `terraform plan`

### Important Factoids

None

### References

None

**Comment by artusiep** [comment]
Thanks for response @edwardmedia 

This issue is directly connected with dynamic code. Removing the dynamic code resolves the issue.

I would like to have a module that supports cloud tasks both with `app_engine_routing_override` and without, using dynamic code.then  

I have created a repository that would help reproduce that issue: https://github.com/artusiep/terraform-provider-google-issue-14571
You can take a look at https://github.com/artusiep/terraform-provider-google-issue-14571/blob/main/error.txt to see that applying terraform was successful but next apply returns a diff `+ app_engine_routing_override {}`

**Comment by artusiep** [comment]
@edwardmedia 
This is a section with a state file for a resource that creates this issue:
```
    {
      "module": "module.cloud_tasks[\"task-name\"]",
      "mode": "managed",
      "type": "<edited>",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/hashicorp/google-beta\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_engine_routing_override": [],
            "id": "projects/at-pricingtool/locations/europe-west3/queues/<edited>",
            "location": "europe-west3",
            "name": "task-name",
            "project": "at-pricingtool",
            "rate_limits": [
              {
                "max_burst_size": 100,
                "max_concurrent_dispatches": 1000,
                "max_dispatches_per_second": 500
              }
            ],
            "retry_config": [
              {
                "max_attempts": 5,
                "max_backoff": "3600s",
                "max_doublings": 16,
                "max_retry_duration": "",
                "min_backoff": "0.100s"
              }
            ],
            "stackdriver_logging_config": [],
            "timeouts": null
          },
          "sensitive_attributes": [],
          "private": "<edited>"
        }
      ]
    }
```

**Comment by artusiep** [comment]
Here is a gist with debug logs: https://gist.github.com/artusiep/0b3d290a3fa12a59457c09eb8bdac0e1

There is a warning that could indicate the issue:
```
**2023-05-14T11:19:10.988+0200 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value for module.test.google_cloud_tasks_queue.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .app_engine_routing_override: block count changed from 1 to 0
module.test.google_cloud_tasks_queue.this: Creation complete after 1s [id=projects/artusiep-issue-14571/locations/europe-west1/queues/issue-14571-2]**
```

**Comment by edwardmedia** [comment]
@artusiep do you have the debug log for below execution?

```
Terraform will perform the following actions:

  # module.abc.google_cloud_tasks_queue.this will be created
  + resource "google_cloud_tasks_queue" "this" {
      + id       = (known after apply)
      + location = "europe-west1"
      + name     = "some-name"
      + project  = "artusiep-project"

      + app_engine_routing_override {
          + host = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "default"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.abc.google_cloud_tasks_queue.this: Creating...
module.abc.google_cloud_tasks_queue.this: Creation complete after 1s [id=projects/artusiep-project/locations/europe-west1/queues/some-name]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by edwardmedia** [comment]
@artusiep you declare [app_engine_routing_override](https://github.com/artusiep/terraform-provider-google-issue-14571/blob/9b2a880bb341ce3b8ce51098cec51c28f3831d2b/module/main.tf#L25) but I don't see where you provide its value. Without it, what do you expect for this [block](https://github.com/artusiep/terraform-provider-google-issue-14571/blob/9b2a880bb341ce3b8ce51098cec51c28f3831d2b/module/main.tf#L58)?

Maybe you can 

```tf
module "test" {
  source = "./module"
  location   = "europe-west1"
  name       = "issue-14571-2"
  project_id = "artusiep-issue-14571"


  app_engine_routing_override = {
    service = "worker"
    version = "1.0"
    instance = "test"
  }

}
```

**Comment by artusiep** [comment]
I would expect that this [block](https://github.com/artusiep/terraform-provider-google-issue-14571/blob/9b2a880bb341ce3b8ce51098cec51c28f3831d2b/module/main.tf#L57-L64) without value for [app_engine_routing_override](https://github.com/artusiep/terraform-provider-google-issue-14571/blob/9b2a880bb341ce3b8ce51098cec51c28f3831d2b/module/main.tf#L25) provided, should not result with diff

I have added a new comment to gist to let you take a look at what I'm talking about: https://gist.github.com/artusiep/0b3d290a3fa12a59457c09eb8bdac0e1?permalink_comment_id=4570002#gistcomment-4570002

**Comment by edwardmedia** [comment]
@artusiep here is the deal. I understood you don't want to set `app_engine_routing_override`, but your dynamic code leads to below plan. Can you remove `app_engine_routing_override` block?

```
  # module.abc.google_cloud_tasks_queue.this will be created
  + resource "google_cloud_tasks_queue" "this" {
      + id       = (known after apply)
      + location = "europe-west1"
      + name     = "some-name"
      + project  = "artusiep-project"

      + app_engine_routing_override {
          + host = (known after apply)
        }
    }
```

**Comment by artusiep** [comment]
> I understood you don't want to set app_engine_routing_override, but your dynamic code leads to below plan.

I think you don't exactly understand what I'm trying to achieve. I would like to have an **optional** `app_engine_routing_override` dynamic block. 

Creating resources:
![image](https://github.com/hashicorp/terraform-provider-google/assets/19203193/d85bbf2c-e90c-4bd9-b5b7-04b5006566be)
In plan, there are changes in the `test-beta` resource
![image](https://github.com/hashicorp/terraform-provider-google/assets/19203193/2f1d9c6b-9961-4cf5-b073-d65fab95cfcf)


Here is the screenshot that shows what happens in case I remove `app_engine_routing_override` dynamic block. Plan does not show any diff in `test-delta` resource but `test-charlie` does not have needed configuration
![image](https://github.com/hashicorp/terraform-provider-google/assets/19203193/dcdb7cdd-e731-45a7-899c-4b584aee4310)

**Comment by edwardmedia** [comment]
@artusiep sorry I may have not made myself clear. I think this is still a question about how to use the dynamic code. From the provider perspective, when you need to have setting in `app_engine_routing_override`, you need to provide them in the config. On the other side, when you don't have any settings, remove `app_engine_routing_override` completely. How to achieve it with the dynamic code, I don't have the solution yet. But that appears beyond the provider. By this moment, I think the provider still behave as expected. Does this make sense to you?

**Comment by artusiep** [comment]
@edwardmedia I understand what you are saying ,**but** lets take a look at:
```
dynamic "rate_limits"
```
or 
```
dynamic "retry_config"
```
in that case I do not specify those dynamic blocks and resulting plan is does not show diff in this config.

I understand that this could be caused by GCP API returning payload like:
```
{
  "name": "projects/artusiep-issue-14571/locations/europe-west1/queues/issue-14571-2",
  "rateLimits": {
    "maxDispatchesPerSecond": 500,
    "maxBurstSize": 100,
    "maxConcurrentDispatches": 1000
  },
  "retryConfig": {
    "maxAttempts": 100,
    "minBackoff": "0.100s",
    "maxBackoff": "3600s",
    "maxDoublings": 16
  },
  "state": "RUNNING"
}
```
but in my opinion provider should also cover that case, rather then expecting API to return each nested objects

I have limited skills with terraform provider development but is it possible to change behaviour of provider changing schema:
https://developer.hashicorp.com/terraform/tutorials/providers/provider-setup#define-coffees-schema 
or modifying read operation
https://developer.hashicorp.com/terraform/tutorials/providers/provider-setup#implement-read

**Comment by edwardmedia** [comment]
@artusiep have you tried removing the type in the variable to see if that makes difference?

```tf
variable "app_engine_routing_override" {
  /*
  type       = object({
    service = optional(string)
    version = optional(string)
    instance = optional(string)
  })*/
  default = {}
  description = "App Engine Routing for the task. If set, app_engine_routing_override is used for all tasks in the queue, no matter what the setting is for the task."
}
```

Keep in mind, the provider does not have much control over how the api behaves. What we could do is to use all terraform core provides to make it work for us. When you say the issue can't be reproed with the resource (without dynamic code), that means it is unlikely a problem in the provider. If the api's behavior does not make sense, we can file an issue against it. Does this make sense?

**Comment by artusiep** [comment]
Hello @edwardmedia 
> have you tried removing the type in the variable to see if that makes difference?
that's crazy by removing the `type` or this configuration:
```
variable "app_engine_routing_override" {
  type = object({})
  default     = {}
  description = "App Engine Routing for the task. If set, app_engine_routing_override is used for all tasks in the queue, no matter what the setting is for the task."
}
```
makes terraform works as I have expected
