### ISSUE TITLE
Support Private PyPi repositories in composer by allowing a GCS bucket to be passed as parameter

### ISSUE THREAD

**Issue by CaliWee** [hashicorp/terraform-provider-google#14586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It is not possible to create a composer environment that has python packages installed from a private pypi repository. This is because the pip.conf is created in the Google Cloud Storage (GCS) bucket. The bucket is created when the composer environment is created. This makes the pip.conf impossible to update before the environment attempts to install the private repositories.

If the Google Cloud Storage bucket could be created before the composer environment, then the pip.conf could be configured before the environment is created.

Doing so would hopefully be another possible solution to #10850 
and may be an alternative solution of #12781 

### New or Affected Resource(s)

google_composer_environment

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "my_bucket" {
  name          = "my-composer-bucket"
  location      = "US"
  force_destroy = false

  public_access_prevention = "enforced"
}

resource "google_storage_bucket_object" "pip_conf" {
  name    = "config/pip/pip.conf"
  bucket  = google_storage_bucket.my_bucket.name
  content = "[global]\nindex_url = https://us-west1-python.pkg.dev/my-private-pypi/combined/simple/"
}

resource "google_composer_environment" "test" {
  name   = "example-composer-env"
  region = "us-central1"
  bucket = google_storage_bucket.my_bucket.name
  config {
    software_config {
      pypi_packages = {
        my-private-package = ""
      }
  }
}
```

### References

* #10850 
* #12781 
* https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies#install-private-repo
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object

b/299600720

**Comment by CaliWee** [comment]
I just found out: As of version 5.6 a new config block `storage_config` can be provided where you can provide a bucket! 
https://registry.terraform.io/providers/hashicorp/google/5.6.0/docs/resources/composer_environment.html#bucket

The following terraform configuration should work as long as the service account building the composer environment has access to your private PyPI:

```
resource "google_storage_bucket" "my_bucket" {
  name          = "my-composer-bucket"
  location      = "US"
  force_destroy = false

  public_access_prevention = "enforced"
}

resource "google_storage_bucket_object" "pip_conf" {
  name    = "config/pip/pip.conf"
  bucket  = google_storage_bucket.my_bucket.name
  content = "[global]\nindex_url = https://us-west1-python.pkg.dev/my-private-pypi/combined/simple/"
}

resource "google_composer_environment" "test" {
  name   = "example-composer-env"
  region = "us-central1"
  software_config {
    bucket = google_storage_bucket.my_bucket.name
  }
  config {
    software_config {
      pypi_packages = {
        my-private-package = ""
      }
  }
}
```

**Comment by guicane** [comment]
Is this a christmas miracle?!?! Testing this later today!

**Comment by CaliWee** [comment]
Thank you to the Google Cloud Provider team for providing this change! I have been able to update my environments with this and it works as expected. Also thank you @guicane for testing it on your stack too. Closing this issue. Happy new year

**Comment by guicane** [comment]
Yes, I can also confirm this works as described!
