### ISSUE TITLE
Eventarc Service Agent take time to create - causes Trigger Precondition to fail

### ISSUE THREAD

**Issue by KatTraxler** [hashicorp/terraform-provider-google#14584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.66.1
+ provider registry.terraform.io/hashicorp/google v4.64.0
+ provider registry.terraform.io/hashicorp/google-beta v4.64.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Affected Resource(s)

google_eventarc_trigger

### Terraform Configuration Files

```tf
resource "google_eventarc_trigger" "run-initial-cloud-build-trigger" {
    name = "run-initial-cloud-build-trigger"
    project = var.gcp_deployment_project_id
    location = "us-central1"
    matching_criteria {
        attribute = "methodName"
        value = "google.devtools.cloudbuild.v1.CloudBuild.CreateBuildTrigger"
    }
     matching_criteria {   
        attribute = "type"
        value = "google.cloud.audit.log.v1.written"
     }
    matching_criteria {
        attribute = "serviceName"
        value = "cloudbuild.googleapis.com"
    }
    destination {
        workflow = "projects/${var.gcp_deployment_project_id}/locations/us-central1/workflows/run-cloudbuild-trigger"
    }
    service_account = google_service_account.eventarc-service-account.name
    

    depends_on = [ 
        google_project_iam_member.project_iam_assignment1_eventarc_cmsa,
        google_project_iam_member.project_iam_assignment2_eventarc_cmsa
        ]
}

resource "google_project_iam_member" "project_iam_assignment1_eventarc_cmsa" {
  project = var.gcp_deployment_project_id
  role    = "roles/eventarc.eventReceiver"
  member  = google_service_account.eventarc-service-account.member
  depends_on = [ google_service_account.eventarc-service-account ]
}

resource "google_project_iam_member" "project_iam_assignment2_eventarc_cmsa" {
  project = var.gcp_deployment_project_id
  role    = "roles/workflows.invoker"
  member  = google_service_account.eventarc-service-account.member
  depends_on = [ google_service_account.eventarc-service-account ]
}


resource "google_project_iam_member" "project_iam_assignment_eventarc_agent" {
  project = var.gcp_deployment_project_id
  role    = "roles/eventarc.serviceAgent"
  member  = "serviceAccount:service-${data.google_project.project.number}@gcp-sa-eventarc.iam.gserviceaccount.com"
  depends_on = [ google_eventarc_trigger.run-initial-cloud-build-trigger ]
}

```

### Debug Output

```bash
Error: Error creating Trigger: googleapi: Error 400: Invalid resource state for "": Permission denied while using the Eventarc Service Agent. If you recently started to use Eventarc, it may take a few minutes before all necessary permissions are propagated to the Service Agent. Otherwise, verify that it has Eventarc Service Agent role.
```

### Expected Behavior

Should have applied on first run

### Actual Behavior

Takes several `terraform apply` before eventually going through

### Important Factoids

This issue of the Service Agent taking several minutes to be created is documented in Google documenation already.  No, the creation of the Service Agent does not seem to be tied to the enabling of the eventarc API rather when a trigger is first requested to be created.

<img width="836" alt="Screenshot 2023-05-11 at 3 41 41 PM" src="https://github.com/hashicorp/terraform-provider-google/assets/52041609/350d742c-d93f-4248-af3d-702f652653dc">

### References

See Eventarc Troubleshooting Page: https://cloud.google.com/eventarc/docs/troubleshooting

**Comment by edwardmedia** [comment]
@KatTraxler I think you are right. This is similar to `google_project_service`. Some apis returns DONE while their resources are still not ready to use. This is beyond terraform's hand.  

Are there any pending issues?

**Comment by KatTraxler** [comment]
I looked through this repo for similar issues requesting an expansion of the timeout block/retry block or anything related to `google_eventarc_trigger` resource and didn't find anything.

**Comment by edwardmedia** [comment]
@KatTraxler cool Thank you. Let's close this issue now.

**Comment by KatTraxler** [comment]
I'm sorry, why is the issue closed?
 Can it be converted into a enhancement request.
