### ISSUE TITLE
google_firebase_hosting_site 404: Requested entity was not found.

### ISSUE THREAD

**Issue by glasnt** [hashicorp/terraform-provider-google#14585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6

### Affected Resource(s)

* google_firebase_hosting_site

### Terraform Configuration Files

```tf

locals {
  services = [
     # ...
    "firebase.googleapis.com",
    "firebasehosting.googleapis.com",
  ]
}

resource "google_project_service" "enabled" {
  for_each                   = toset(local.services)
  project                    = var.project_id
  service                    = each.value
  disable_dependent_services = true
  disable_on_destroy         = false
}


resource "google_firebase_project" "default" {
  provider = google-beta
  project  = var.project_id

  depends_on = [google_project_service.enabled]
}

resource "google_firebase_hosting_site" "client" {
  provider = google-beta
  project  = var.project_id
  site_id  = var.random_suffix ? "${var.project_id}-${random_id.suffix.hex}" : var.project_id

  depends_on = [google_project_service.enabled]
}


```

### Debug Output

First `apply`: 
```
│ Error: Error creating Site: googleapi: Error 404: Requested entity was not found.
│ 
│   with module.dynamic-python-webapp.google_firebase_hosting_site.client,
│   on infra/firebase.tf line 24, in resource "google_firebase_hosting_site" "client":
│   24: resource "google_firebase_hosting_site" "client" {
│ 
╵
```

Second `apply`: 
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Expected Behavior

I should only have to `apply` once. 

### Actual Behavior

*Speculation*: The Firebase / Firebase Hosting APIs are created, but are asynchronously still spinning up in the background, so the API is returning 404 on first apply, but by the time you apply again, all is well. 

Additionally: trying to destroy and re-create on the same project does not re-create the issue. It's once per project. (This is still an issue)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/58

Full single-apply logs https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/58/checks?check_run_id=13390877929

**Comment by edwardmedia** [comment]
@glasnt is this a timing issue? Have you tried adding [sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) between resources to see if that helps?

**Comment by glasnt** [comment]
@edwardmedia I shouldn't have to have a sleep here (also I'm working in an environment where I shouldn't use such methods)

**Comment by edwardmedia** [comment]
@glasnt some of the resources are not available to use right away even when API return DONE.  You may see such statements on the console when you enable some of the services. 

Help me to understand why you think we shouldn't have to have a sleep here?

**Comment by edwardmedia** [comment]
@glasnt I see you have added `make firebase site depend on project` in your link. Assuming it is no longer an issue. Closing this now
