### ISSUE TITLE
Failing test(s): TestAccFirebaserulesRelease_StorageReleaseHandWritten

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#14583]
### Failure rates

- 100% since 2023-05-10

### Impacted tests

- TestAccFirebaserulesRelease_StorageReleaseHandWritten

### Affected Resource(s)

* google_firebase_storage_bucket

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/399509?mode=builds&buildTab=tests&expandedTest=-6486443847824643163)

### Message(s)

```
Error: Invalid resource type
```

`google_firebase_storage_bucket` is beta only and thus I think `TestAccFirebaserulesRelease_StorageReleaseHandWritten` should probably be beta-only

**Comment by rainshen49** [comment]
Thanks for catching! I'll patch a PR for this.

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7944
