### ISSUE TITLE
Allow enabling log analytics on _Required log bucket

### ISSUE THREAD

**Issue by wehm2000** [hashicorp/terraform-provider-google#14588]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be great to be able to enable log analytics via terraform for the `_Required` bucket which contains the Admin Activity Logs.

Currently this is not possible due to the the bucket being locked for any other configuration changes. If you fill out all the required arguments, the `terraform apply will fail` with the follwing error:
```
Error: Error updating Logging Bucket Config "projects/my-project/locations/global/buckets/_Required": googleapi: Error 400: This bucket is locked. Locked buckets are immutable
```

Still, it is possible to uprade the bucket to use log analytics via Cloud Console, gcloud-Command or API call: https://cloud.google.com/logging/docs/buckets#upgrade-bucket

### New or Affected Resource(s)

* google_logging_project_bucket_config

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_logging_project_bucket_config" "analytics-enabled-bucket" {
    project          = "project_id"
    enable_analytics = true
    bucket_id        = "_Required"
}
```

b/284522079

**Comment by rileykarson** [comment]
@ScottSuarez I think `service/logging` covers `google_logging_*`?

**Comment by melinath** [comment]
It looks like updating this field requires using `updateAsync` instead of `patch`. It seems like the difference is maybe just that `updateAsync` returns an LRO, so it _might_ be enough to just change the request URL and switch to using existing logging_operation handling.

**Comment by melinath** [comment]
at a minimum though - you'd need to add the new `enable_analytics` field.

**Comment by victorwelling** [comment]
Workaround until this is implemented:

```hcl
data "google_client_config" "current" {
}

resource "null_resource" "enable_log_analytics" {
  provisioner "local-exec" {
    command = <<CURL
      curl -X POST --location "https://logging.googleapis.com/v2/projects/${google_project.project.project_id}/locations/global/buckets/_Required:updateAsync?updateMask=analyticsEnabled" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${data.google_client_config.current.access_token}" \
        -d "{\"analyticsEnabled\": true}"
    CURL
  }
}
```

Please note: if your `_Required` bucket is in a different location than `global`, update the URL accordingly.

**Comment by pengq-google** [comment]
We can let Terraform to manage it by import the _Required bucket (this workflow also works for _Default bucket):
```
terraform import google_logging_project_bucket_config.default_bucket projects/[my-project]/locations/global/buckets/_Required
```

Then
```
  ~ update in-place

Terraform will perform the following actions:

  # google_logging_project_bucket_config.required_bucket will be updated in-place
  ~ resource "google_logging_project_bucket_config" "required_bucket" {
        bucket_id        = "_Required"
        description      = "Audit bucket"
      ~ enable_analytics = false -> true
        id               = "projects/[my-project]/locations/global/buckets/_Required"
        lifecycle_state  = "ACTIVE"
        location         = "global"
        locked           = true
        name             = "projects/[my-project]/locations/global/buckets/_Required"
        project          = "projects/[my-project]"
        retention_days   = 400
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_logging_project_bucket_config.required_bucket: Modifications complete after 1m17s [id=projects/[my-project]/locations/global/buckets/_Required]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by rileykarson** [comment]
Closing as internal bug was closed.

I suspect that this became possible after https://github.com/hashicorp/terraform-provider-google/issues/9772 was released, as the update request seems to have been failing due to the lock status of the bucket changing.
