### ISSUE TITLE
Support GCP Workflow Identity Federation

### ISSUE THREAD

**Issue by tommed** [hashicorp/terraform-provider-google#14587]
### Description

We are a high-security company with ISO/IEC 27001 accreditation and have some public sector customers who audit our solution's backend cloud infrastructure rather than just the front-end services through pen. testing.

One of the things raised by the CHECK ITHCs were the use of JSON keys for service accounts.

When Google manage access, they keys are auto-rotated regularly, meaning no key pairs exist for long enough to be vulnerable to a brute-force attack. If any JSON credentials files are generated for service account use, they must be rotated manually every 30-90 days to ensure the same security.

Google recently brought out [WIF](https://cloud.google.com/iam/docs/workload-identity-federation) for the same reason. As I understand it, it allows service accounts to make use of OAuth2 to get temporary tokens for IAM.

I've checked and I can't see how the GCP provider could make use of WIF so we don't need to provide security JSON credentials to Terraform and risk making our service vulnerable to attacks.

From the ITHC report:

"Service Account keys consist of a key ID (Private_key_Id) and Private Key, which are used to sign programmatic requests users make to Google cloud services accessible to that particular service account. It is recommended that all Service Account keys are regularly rotated.

**Rationale Statement**
Rotating Service Account keys will reduce the window of opportunity for an access key that is associated with a compromised or terminated account to be used. Service Account keys should be rotated to ensure that data cannot be accessed with an old key that might have been lost, cracked, or stolen.
Each service account is associated with a key pair managed by Google Cloud Platform (GCP). It is used for service-to-service authentication within GCP. Google rotates the keys daily.
GCP provides the option to create one or more user-managed (also called external key pairs) key pairs for use from outside GCP (for example, for use with Application Default Credentials). When a new key pair is created, the user is required to download the private key (which is not retained by Google). With external keys, users are responsible for keeping the private key secure and other management operations such as key rotation. External keys can be managed by the IAM API, gcloud command-line tool, or the Service Accounts page in the Google Cloud Platform Console. GCP facilitates up to 10 external service account keys per service account to facilitate key rotation."

### Potential Terraform Configuration

```terraform
N/A
```

### Would you like to implement a fix?

None

**Comment by ScottSuarez** [comment]
@rileykarson @melinath this seems pretty important

**Comment by melinath** [comment]
Details on how to authenticate with the provider are available at https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference. We already allow users to pass tokens to Terraform, which would include tokens generated using WIF / OIDC. However, those technologies generally involve having a persistent trusted relationship with a provider (like GitHub Actions or Terraform Cloud) which can then generate the token on demand for a particular run. I don't think something like that would easily be possible using Terraform on its own, since there's a bootstrapping problem, but you could set up your pipeline to generate a new token that expires after X hours at the start of every run, then pass that to terraform instead - or something along those lines?

TLDR it's not clear to me what action this is asking for that's not supported by our existing auth functionality.

**Comment by tommed** [comment]
> it's not clear to me what action this is asking for that's not supported by our existing auth functionality.

Succinctly, Google's "best practices" which are written in white papers available to partners and security companies are suggesting that JSON keys are _not_ the preferred way to handle authentication anymore.

The problem with JSON keys is that they don't rotate over time and remain static. Anything remaining static is theoretically vulnerable to long-term brute force attacks. Our own independent CHECK ITHC has highlighted our use of JSON keys and we have pressure from a customer (who is a large metropolitan public authority) to look into treating this risk.

One of the few keys have is for Terraform; hence me reaching out.

Thanks for the link you provided. This suggests the following approach by Terraform:
![image](https://github.com/hashicorp/terraform-provider-google/assets/13066/5bffa1e7-b80f-4c7a-96e1-8b1f7062faf6)

Which does conflict somewhat with the aforementioned CREST supplied security advice.

Google has also changed it's advice, as per [this document](https://cloud.google.com/iam/docs/workload-identity-federation):

> Traditionally, applications running outside Google Cloud can use service account keys to access Google Cloud resources. However, service account keys are powerful credentials, and can present a security risk if they are not managed correctly.

Hopefully you can now see why I'm asking Terraform to consider this approach. I believe this is the contemporary preferred method and as we have pressure to adopt it asap, I am reaching out to you and echoing the advice we've been given. Many Thanks!

**Comment by rileykarson** [comment]
> We already allow users to pass tokens to Terraform, which would include tokens generated using WIF / OIDC.

Passing tokens is more for _very_ specific cases than general usage. We wouldn't expect users to do that. Plus, that defeats the point a bit- credential configurations are not meant to be _required_ to be confidential per https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#create_a_credential_configuration, while a key or token is.

> Hopefully you can now see why I'm asking Terraform to consider this approach...

I _think_ that https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#credentials will actually work as well- unless we've made a silly decision in our implementation there's no reason it shouldn't- I just don't have an external identity provider I can test with offhand.

Note that even if that doesn't work, we should support WIF through ADCs: https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#use_the_credential_configuration_to_access

This has been true since Mar 2021 AIUI: https://github.com/hashicorp/terraform-provider-google/issues/8671#issuecomment-804091709 (later discussion in that issue was a separate bug)

**Comment by rileykarson** [comment]
Sorry, what I mean there is that you should be able to specify a WIF credential configuration file through that field, not just a service account key!

**Comment by tommed** [comment]
Thanks for the clarification - re-reading your response makes a lot more sense and is extremely helpful thanks!

WIF is very new to us, so this is probably an ignorant question, but my understanding is that WIF works by plugging into the remote service's own Identity Provider (OAuth/SAML/Azure and AWS' own service accounts etc.) rather than just providing an alternative file than the service JSON files.

What exactly would I be 'downloading' and setting in the `GOOGLE_CREDENTIALS` environment variable to follow your instructions? Do you have any documentation or experience getting WIF and Terraform working together? Thanks again

**Comment by tommed** [comment]
Anyone?

**Comment by rileykarson** [comment]
I haven't followed the flow myself, but the file described in https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#create_a_credential_configuration is what you would supply to `credentials` or one of its environment variables!

**Comment by tommed** [comment]
Wonderful thanks. That makes a lot of sense for the authentication configuration side. When it comes to creating the WIF pool, (for example, in the linked example this is referring back to a AWS pool pre-configured in their WIF instance), what are the settings used?

If my understanding of WIF is right, there needs to be an external SSO to validate tokens against (the federated identity part) - would that be Hashicorp's auth provider? If so, do you have the details of what you used when you followed this through?

**Comment by tommed** [comment]
Ok thanks. So.. is it actually possible as you say?

**Comment by tommed** [comment]
Just wondering guys, is there a premium support option or something so we can get answers to these issues more expediently please? We obv have customers of our own and deadlines and one of the big risks in using any third party services to provision our own systems is we are reliant on levels of progress so we can work towards a solution. If Terraform aren't able to provide this level of support, it makes it much harder to adopt it as a viable professional service.

I don't mean for this post to be negative or pointing the finger, just trying to look for a way forward with this. We've been told it's possible twice now, but no one has been able to provide any guidance.

How do we move this forward please?

**Comment by tommed** [comment]
> If you have a support plan with either Google or HashiCorp, I'd recommend following up through those. We're unable to guarantee closure for individual issues / high touch support for questions through GitHub, other than cases with broad impact or ones that are opportunistically easy for folks to address.
> 
> 
> 
> Retagging to question given we think this works, although that's not guaranteed. If we determine it's not I'll update it.

Thanks, that's helpful and a good Avenue to explore. It's been said "It works", but there is no documentation, nor does anyone who claims it works actually appear to know how to configure it. I suspect it's had five minutes spent on it and by scanning documentation it's been dismissed, but the actual truth is this is quite an important feature. Google are moving away from json keys because they never change and therefore are susceptible to long term attacks. They have advised security companies to advise against these, but the documentation for this provider recommends to use this method. There is no documentation to reconfigure this, no does anyone seem to have investigated this concept enough to explain how to get it working end-2-end. I do believe this needs attention, otherwise i wouldn't have raised it in the first place.

Tbh I'm a little shocked given the perceived importance of this change, that Hashicorp aren't taking this more seriously. I had assumed security was important to them given their service tends to get given much higher permissions that most - to provision the infrastructure. You would have thought that as soon as Google announced WIF, it would have been in their priority list - certainly the people who are responsible for this provider anyway.

This is disappointing, but if you are saying the best way to proceed is for this information to be given to me privately by paying for support, rather than making it available to all (in the spirit of open source), then i have to say, I'm not surprised.

**Comment by tommed** [comment]
For anyone else who cares, Google have documented the Terraform WIF set up process step-by-step themselves here:
https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines#terraform-cloud
