### ISSUE TITLE
EventArc Trigger Missing Required property event_data_content_type

### ISSUE THREAD

**Issue by gobubble-faisal** [hashicorp/terraform-provider-google#14597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
- Terraform v1.4.6
- hashicorp/google v4.64.0
- hashicorp/google-beta v4.64.0

### Affected Resource(s)

* google_eventarc_trigger

### Terraform Configuration Files

```tf
resource "google_eventarc_trigger" "test_trigger" {
  name = "test-events"
  location = "nam5"
  service_account = "xxxx"

  matching_criteria {
    attribute = "type"
    value     = "google.cloud.firestore.document.v1.written"
  }

  matching_criteria {
    attribute = "database"
    value     = "(default)"
  }

  destination {
    cloud_run_service {
      region       = "us-central1"
      service      = "xxx-service-name-xxx"
      path         = "/"
    }
  }
}
```

### Debug Output

https://gist.github.com/gobubble-faisal/0430d7be786a86cd7f211460c36412a4

### Panic Output

No

### Expected Behavior

google_eventarc_trigger resource should have been created successfully

### Actual Behavior

Terraform failed with a 400 error from the Google Cloud API because the property, event_data_content_type, must be provided to the API and is not supported as a property by the Google Terraform Provider

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

No

### References

None

**Comment by edwardmedia** [comment]
[event_data_content_type](https://cloud.google.com/eventarc/docs/reference/rest/v1/projects.locations.triggers) is available. Change label to enhancement

**Comment by ScottSuarez** [comment]
Changing back to bug. This is configuration that is currently breaking due to a feature not being available.. Filed against upstream team
