### ISSUE TITLE
Field names in the `import_format` should be in snake case

### ISSUE THREAD

**Issue by maqiuyujoyce** [hashicorp/terraform-provider-google#14606]
# Background

It looks like not all field names in `import_format` are in snake case, but some are in camel case. E.g. https://registry.terraform.io/providers/hashicorp/google/4.65.0/docs/resources/firebase_android_app IIUC, all fields in TF resources should be in snake case and there is no exception. Could field names in `import_format` be fixed? I think a simple unit test should help.

# What kind of contribution is this issue about?

* MMv1-based resource

# Related PR(s), if any:

N/A

# Details

See background.

**Comment by rileykarson** [comment]
The case we ran into looked like a bug in the end- these are probably all bugs that can be filed individually, when they happen.
