### ISSUE TITLE
User "system:anonymous" cannot get resource "xx" in API group "" in the namespace "xx"

### ISSUE THREAD

**Issue by Div2508** [hashicorp/terraform-provider-google#14611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* 4.65.0

### Affected Resource(s)

* google_client_config

### Important Factoids

* When the customer tries to run infra config updates via terraform they may receive this error
* User "system:anonymous" cannot get resource "xx" in API group "" in the namespace "xx"
* There seems to be an issue with the latest version

### Workaround

Try hard coding the earlier versions in the TF code.

Sample code

```
data "google_client_config" "default" {}

provider "kubernetes" {
  host                   = data.vault_generic_secret.cluster_secret.data.endpoint
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.vault_generic_secret.cluster_secret.data.ca_certificate)
}

provider "google" {
  version = "4.64.0"#version 4.65 cause the issue 
  credentials = file("/tmp/service-account.key")
  project     = var.gcp_project
  region      = var.region
}
```

**Comment by shuyama1** [comment]
duplicate https://github.com/hashicorp/terraform-provider-google/issues/14602
