### ISSUE TITLE
forbidden: User "system:anonymous" in v4.65.1

### ISSUE THREAD

**Issue by drehelis** [hashicorp/terraform-provider-google#14613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.65.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0

```

### Affected Resource(s)

* data.kubernetes_service_v1

### Terraform Configuration Files

```tf
terraform {
  required_providers {
#    google      = "< 4.65.0"
#    google-beta = "< 4.65.0"
  }
}

data "google_client_config" "provider" {
  provider = google
}

data "google_container_cluster" "cluster" {
  project  = "xxx"
  name     = "yyy"
  location = "zzz"

}

provider "kubernetes" {
  insecure               = false
  host                   = "https://${data.google_container_cluster.cluster.endpoint}"
  token                  = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
}

data "kubernetes_service_v1" "nginx" {
  metadata {
    name      = "nginx-ingress-nginx-controller"
    namespace = "nginx"
  }
}
```

### Actual Behavior

```
data.google_client_config.provider: Reading...
data.google_client_config.provider: Read complete after 0s
data.google_container_cluster.cluster: Reading...
data.google_container_cluster.cluster: Read complete after 1s [id=projects/xxx/locations/yyy/clusters/zzz]
data.kubernetes_service_v1.nginx_ip: Reading...
╷
│ Error: services "nginx-ingress-nginx-controller" is forbidden: User "system:anonymous" cannot get resource "services" in API group "" in the namespace "nginx"
│
│   with data.kubernetes_service_v1.nginx_ip,
│   on yalla.tf line 26, in data "kubernetes_service_v1" "nginx_ip":
│   26: data "kubernetes_service_v1" "nginx_ip" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
dup of https://github.com/hashicorp/terraform-provider-google/issues/14602
