### ISSUE TITLE
The "for_each" map includes keys derived from resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#14628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.5

### Affected Resource(s)

* google_service_account
* google_project_iam_member

### Terraform Configuration Files

```
# Parent module
resource "google_service_account" "test1" {
  project    = var.project_id
  account_id = "test1"
}
module "mig" {
  source = "git::https://github.com/aws2gcp/gcp-network-terraform//mig"
  project    = var.project_id
  service_account_email      = google_service_account.test1.email
}

# Child module
locals {
  ops_agent_iam_members = { for i, v in ["logging.logWriter", "monitoring.metricWriter"] : i => {
    member = "serviceAccount:${var.service_account_email}"
    role   = "roles/${v}"
  } if var.service_account_email != null }
}
resource "google_project_iam_member" "default" {
  for_each = local.ops_agent_iam_members
  project  = var.project_id
  member   = each.value.member
  role     = each.value.role
}
```

### Panic Output

n/a

### Expected Behavior

The map keys are the indexes of a static list (0 and 1).  Should be no issue.  The service account e-mail is passed as a resource's value and thus has an implicit depends_on.  

### Actual Behavior

Terraform complains the map keys are derived from resource attributes:
```
The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify
│ the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Even passing the service account e-mail as a literal string (account_id@project_id.iam.gserviceaccount.com) w/ explicit depends_on will result in the same error, which makes no sense since both the keys _and_ single value would be static

Using count instead of for_each also results in the same error.

I've only found one work-around: move the for_each to the parent module.  This implies the error has nothing to do with the for_each and may be something to do with modules.  

### References

* https://github.com/aws2gcp/gcp-network-terraform/issues/4

**Comment by edwardmedia** [comment]
@jeheyer have you seen such arrangement working on other resources? This seems to be a question about the for_each feature. Have you asked Terraform core to see if that make sense?

**Comment by edwardmedia** [comment]
@jeheyer closing assuming this is no longer an issue

**Comment by jeheyer** [comment]
It's still an issue in the sense that I could never understand the root cause.  I just worked around by moving the same code from the child to the parent module.  I realized that's desirable anyway because the child module could be called multiple times with the same service account and I didn't want the extra complexity of a sticking data query inside the child module to avoid duplicate permissions.
