### ISSUE TITLE
Misleading error when creating private services connect via google_compute_service_attachment

### ISSUE THREAD

**Issue by mmllc-jsilverman** [hashicorp/terraform-provider-google#14626]
I tried to create a google_compute_service_attachment.

I created all the prerequisites ok: DNS Zone, forwarding rule, etc.

I received the following error:

```
│ Error: Error creating ServiceAttachment: googleapi: Error 400: Invalid value for field 'resource.domainNames': ''. Please verify ownership of the PTR domain. See more information at https://cloud.google.com/compute/docs/instances/create-ptr-record#domain_ownership., invalid
```

Off of this block:

```
resource "google_compute_service_attachment" "my-psc" {
  provider    = google-beta
  name        = "my-psc"
  project     = var.project_id
  region      = local.region
  description = "my psc"
  enable_proxy_protocol = false
  connection_preference = "ACCEPT_MANUAL"
  nat_subnets           = [google_compute_subnetwork.network_for_my_psc.id]
  target_service        = data.google_compute_forwarding_rule.my-fr.id
  domain_names          = ["p.my-domain.io."]
  consumer_accept_lists {
    project_id_or_num = "my-project"
    connection_limit  = 4
  }
}
```

The problem was traced to an ownership issue. The problem was solved by the account owner adding the service account that was being used to generate the records to the Google Search Console. Once authed there, the Terraform block worked.

I recommend changing this error to something more specific to the issue, or more clear in general.

**Comment by edwardmedia** [comment]
@mmllc-jsilverman can you share the debug log that contains the api requests?

**Comment by mmllc-jsilverman** [comment]
@edwardmedia ah.. I didn't run with debug on for this event so I don't have those logs.

Unfortunately, I have already proceeded past this in prod and I can't recreate this event easily.

**Comment by edwardmedia** [comment]
@mmllc-jsilverman Thank you for reporting this. I was thinking of passing along to the api to see if they can fix the `misleading` error message. Since we don't have the details about it and there is little we can do at the provider level, I am closing this issue right now.  Feel free to reopen if you get more details.
