### ISSUE TITLE
Add support for GKE Node Auto-provisioning locations

### ISSUE THREAD

**Issue by moppediert** [hashicorp/terraform-provider-google#14632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the [Node Autoprovisioning (NAP) settings](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#auto-provisioning_locations) of GKE you can specify the zones you wish NAP will provision node. Currently this is not supported by the `google_container_cluster` terraform resource and the result is that new nodes cannot be scheduled due to no location for NAP being set.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "cluster" {
  cluster_autoscaling {
    enabled = true
    auto_provisioning_defaults {
      locations = ["europe-west3-a", "europe-west3-b"]
    }
  }
}
```

### References

* [This instruction](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#auto-provisioning_locations) from Google on how to specify the Node Autoprovisioning locations when using `gcloud`

* b/298497322

**Comment by rileykarson** [comment]
Note: If this is equivalent to `node_locations`, we may want to use that name for consistency.

**Comment by red8888** [comment]
Im confused does this mean NAP is broken with `google_container_cluster`? I'm using it and it seems to be working, but I'm not sure how its choosing zones. I have a regional cluster and it seems to just randomly pick?

Can someone explain how NAP currently works with `google_container_cluster` if this isn't supported currently?

**Comment by rileykarson** [comment]
NAP should work, just this setting in particular is not modifiable yet- see https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#auto-provisioning_locations for documentation. Not setting it just means you'll be taking on the default behaviour, i.e. drawing from the default set of locations, which GKE is not specific about the rules for. That's likely the cluster's `node_locations`, the zone of the cluster for regional clusters, or an arbitrary set of zones in the region of the cluster for regional clusters.

**Comment by iahmad-khan** [comment]
Looks like this is supported.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#auto_provisioning_locations

**Comment by rileykarson** [comment]
Done in https://github.com/GoogleCloudPlatform/magic-modules/pull/11305
