### ISSUE TITLE
terraform-provider-google_v4.65.2_x5 plugin crashed

### ISSUE THREAD

**Issue by paulwer** [hashicorp/terraform-provider-google#14631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_v4.65.2_x5

### Panic Output

Stack trace from the terraform-provider-google_v4.65.2_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "6485940428763397016": value out of range

goroutine 306 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x16b28370, {0x16d82c60, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x16b28370)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x169a12d0, {{{0x368a200, 0x16d826b8}}, {0x2c41640, 0x1631b440}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x167ff560, {0x3689d80, 0x16b243f0}, 0x1631af40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x16aad580, 0x16aad5c0, {0x16f2e2c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x16dae140, {0x3689d80, 0x16b24078}, 0x16c820c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x30536a0, 0x16dae140}, {0x3689d80, 0x16b24078}, 0x161de040, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x16eac000, {0x368df38, 0x1701c120}, 0x1686e0a0, 0x16f2c420, 0x49db0e8, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xed7
google.golang.org/grpc.(*Server).handleStream(0x16eac000, {0x368df38, 0x1701c120}, 0x1686e0a0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x25f

Error: The terraform-provider-google_v4.65.2_x5.exe plugin crashed!
### Expected Behavior

terraform project plan should be created

### Actual Behavior

failed during evaluation of exsiting services

### Steps to Reproduce

1. `terraform plan` OR `terraform apply`

### References

* #9022

**Comment by rileykarson** [comment]
Just curious: are you on a 64 or 32 bit system? We've seen 32 bit OSes trigger these kind of issues in the past.

**Comment by paulwer** [comment]
Terraform v1.4.6
on windows_386
+ provider registry.terraform.io/hashicorp/google v4.65.2
+ provider registry.terraform.io/hashicorp/google-beta v4.65.2
+ provider registry.terraform.io/hashicorp/random v3.5.1

from win11 64bit

https://drive.google.com/drive/folders/1YauN3lqPdMkv7qeuVMBAoQ-D9rINGUrT?usp=sharing

**Comment by rileykarson** [comment]
What's weird here is, the message is `Error reading level state` and I don't think we support a field named `level` _anywhere_ in the provider. There's `protection_level`, `access_levels`, etc. but no `level`. The `Error reading {{field}} state:` pattern isn't ours either, we use `Error reading {{resource}}:`. I don't see provider code getting executed in the stack trace either (although the provider _binary_ is getting executed, in practice).

I see similar bugs from other providers in https://github.com/hashicorp/terraform/issues/28992 (which turned in to https://github.com/hashicorp/terraform-provider-aws/issues/19910 and died...) so I suspect that the bug isn't provider-specific.

I did see https://github.com/hashicorp/terraform-provider-google/issues/12621 where a user reported a similar issue against us, and they were running the 32-bit Terraform binary in a 64-bit environment- the same is true for you. It would be weird if a provider upgrade was the trigger, though, and not a core version or environment change.

**Comment by rileykarson** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/29548 was also recent and indicates the same, so I suspect that a version upgrade is the fix. @paulwer: Did you upgrade multiple components at once, or was the provider the triggering factor here?
