### ISSUE TITLE
Inconsistent value for project property in google_logging_project_bucket_config resource

### ISSUE THREAD

**Issue by jcoll-busup** [hashicorp/terraform-provider-google#14645]
The [documentation for the google_logging_project_bucket_config resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config) currently shows these examples:

```tf
resource "google_project" "default" {
    project_id = "your-project-id"
    name       = "your-project-id"
    org_id     = "123456789"
}

resource "google_logging_project_bucket_config" "basic" {
    project    = google_project.default.id
    location  = "global"
    retention_days = 30
    bucket_id = "_Default"
}
```

```tf
resource "google_logging_project_bucket_config" "analytics-enabled-bucket" {
    project          = "project_id"
    location         = "global"
    retention_days   = 30
    enable_analytics = true
    bucket_id        = "custom-bucket"
}
```
Following the examples, using **google_project.default.id** as value for the **project** property of the **google_logging_project_bucket_config** resource results in a 404 error upon reaching the creation request.

The debug output reveals that the URL of the create request is being generated incorrectly, appending `projects/` to the **project** property of the resource:

```
2023/05/18 12:03:53 [DEGUG] Loggin Bucket not exist projects/your-project-id-10606712/locations/global/buckets/custom-bucket
2023/05/18 12:03:53 [DEBUG] Creating new Bucket: map[string]interface {}{"analyticsEnabled":true, "cmekSettings":interface {}(nil), "description":"", "locked":interface {}(nil), "name":"", "retentionDays":30}
2023/05/18 12:03:53 [DEBUG] Waiting for state to become: [success]
2023/05/18 12:03:53 [DEBUG] Retry Transport: starting RoundTrip retry loop
2023/05/18 12:03:53 [DEBUG] Retry Transport: request attempt 0
2023/05/18 12:03:53 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /v2/projects/projects/your-project-id-10606712/locations/global/buckets?alt=json&bucketId=custom-bucket HTTP/1.1
Host: logging.googleapis.com
User-Agent: Terraform/1.4.6 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.63.1
Content-Length: 106
Content-Type: application/json
Accept-Encoding: gzip

{
 "analyticsEnabled": true,
 "cmekSettings": null,
 "description": "",
 "locked": null,
 "name": "",
 "retentionDays": 30
}

-----------------------------------------------------
2023/05/18 12:03:53 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 404 Not Found
Content-Length: 1667
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=UTF-8
Date: Thu, 18 May 2023 10:03:53 GMT
Server: ESF
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
```

One can use **google_project.default.project_id** (which lacks the `projects/` prefix) instead of **google_project.default.id** as a workaround.

Nonetheless, the result being stored in the tfstate file is inconsistent with results returned by data resources or the usage of the `terraform import` feature, because the **project** property lacks the `projects/` prefix, and the data being returned includes it. This is more of a nitpick, as it does not result in terraform noticing changes, but feels kind of wrong.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.63.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)

google_logging_project_bucket_config
(did not test other google_logging_* resources)

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.63.1"
    }

    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
  }
}

variable "billing-account-name" {
  type = string
}

data "google_billing_account" "default" {
  display_name = var.billing-account-name
  open         = true
}

resource "random_id" "project-id" {
  byte_length = 3
  prefix      = "your-project-id-"
}

resource "google_project" "my-project" {
  name            = "My Project"
  project_id      = random_id.project-id.dec
  billing_account = data.google_billing_account.default.id
}

resource "google_logging_project_bucket_config" "analytics-enabled-bucket" {
  project = google_project.my-project.id
  # Workaround: Works because the project_id property does not include the `projects/` prefix 
  #project          = google_project.my-project.project_id
  location         = "global"
  retention_days   = 30
  enable_analytics = true
  bucket_id        = "custom-bucket"
}
```

### Debug Output

https://gist.github.com/jcoll-busup/795dcc709da3ff6eef89066256b8d545
(to avoid leaking personal info, I have only included the lines relevant to the resource)

### Panic Output

Terraform did not produce a panic.

### Expected Behavior

A logging bucket named `custom-bucket` should be created successfully on the specified project.

### Actual Behavior

The operation fails with a 404 error.

### Steps to Reproduce

Note: A billing account is required to test this.

1. `terraform init`
2. `terraform apply -var="billing-account-name=YOUR_BILLING_ACCOUNT_NAME"`

### Important Factoids

No specific configuration required.

### References

No other references found.

**Comment by edwardmedia** [comment]
@jcoll-busup your workaround is actually the right solution. It should be `project_id` rather than `id`. This is a document bug. Do you still see an issue after you use `project_id`?

**Comment by jcoll-busup** [comment]
@edwardmedia no, no issue whatsoever for the moment.
