### ISSUE TITLE
Optional fields in google_cloudfunctions2_function show up in plan diff

### ISSUE THREAD

**Issue by rainshen49** [hashicorp/terraform-provider-google#14646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
provider hashicorp/google v4.65.2

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

A minimal `google_cloudfunctions2_function`

```tf
resource "google_cloudfunctions2_function" "minimal" {
  location = "us-central1"
  name     = "minimal"
  project  = "<project-id>"

  build_config {
    entry_point = "<entry-point>"
    runtime     = "nodejs16"

    source {
      storage_source {
        bucket = "gcf-v2-sources-000000-us-central1"
        object = "<entry-point>/function-source.zip"
      }
    }
  }

  service_config {}
}
```

### Expected Behavior

It should succeed after one `terraform apply` with no more diffs.

### Actual Behavior

`terraform apply` succeeded, but when I run `terraform plan`, got the following diff:

```
 ~ service_config {
          - available_memory                 = "256M" -> null
          - max_instance_count               = 100 -> null
          - timeout_seconds                  = 60 -> null
            # (9 unchanged attributes hidden)
        }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

According to the documentation https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/cloudfunctions2_function#nested_service_config, the fields in the diff should be optional with default values from the API.

I notice all the other [`service_config` fields](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/cloudfunctions2/Function.yaml) have `default_from_api: true` except for the three fields in the diff (`available_memory`, `max_instance_count`, `timeout_seconds`). Should these fields have `default_from_api`, too?

UPDATE: some fields in event_trigger are also missing this flag: `retry_policy` and `trigger_region`

**Comment by edwardmedia** [comment]
b/283253163
