### ISSUE TITLE
`google_billing_update` won't update to add Pub/Sub alerts

### ISSUE THREAD

**Issue by JanCVanB** [hashicorp/terraform-provider-google#14648]
I believe there is a problem with [the `google_billing_budget` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget). My team has tested a few different configurations and updates to some test billing budgets, and that module seems to exhibit behavior that contradicts its documentation. So far, we believe we've narrowed it down to the following behavior:

- Using a service account that has the `roles/billing.costsManager` role...
  - ... creating a budget on our billing account succeeds...
  - ... but then updating that budget to send alerts to a Pub/Sub topic fails with a 403.
- Using the same service account...
  - ... creating a different budget on the same billing account with the alerts already-enabled succeeds...
  - ... and then updating that budget to turn off alerts succeeds...
  - ... but then updating to turn them back on fails with a 403.

This indicates that there might be an improper escalated action taken by [the budget update handler](https://github.com/hashicorp/terraform-provider-google/blob/f54dc69e746474d31e9e9fe976960ac714ccbbed/google/resource_billing_budget.go#L516) in certain situations. Alternatively, the documentation (which claims that `roles/billing.costsManager` has sufficient permission to update budgets generally) is missing a nuance with the permissions required to connect a budget to a Pub/Sub topic.

Nuances:
- We're consuming the module indirectly through Cloud Foundation Fabric, but their budget resource abstraction is fairly thin and we don't see any failure modes in there.
- We're spanning multiple Google Cloud projects, for an in-house actuation platform, but the service account performing all actuation has sufficient roles in each project involved.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.1.2 - v1.3.1

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
module "test_budget" {
  source = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/billing-budget?ref=v20.0.0"

  ...

  pubsub_topic = null
}
```
vs.
```tf
module "test_budget" {
  source = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/billing-budget?ref=v20.0.0"

  ...

  pubsub_topic = "projects/collection-project-123/topics/test-budget-alerts"
}
```

### Panic Output

```
│ Error: Error creating Budget: googleapi: Error 403: The caller does not have permission
```

### Expected Behavior

Successful update to the budget.

### Actual Behavior

Failed to update the budget.

### Steps to Reproduce

See top.

### Important Factoids

See top.

### References

None

**Comment by edwardmedia** [comment]
@JanCVanB  Is the service account which has the role of `roles/billing.costsManager` at the org level? Below is the use case of that role on its [document](https://cloud.google.com/billing/docs/how-to/billing-access). I don't see it has permissions to 'pubsub'. 

Create, edit, and delete budgets, view billing account cost information and transactions, and manage the export of billing cost data to BigQuery. Does not confer the right to export pricing data or view custom pricing in the Pricing page. Also, does not allow the linking or unlinking of projects or otherwise managing the properties of the billing account.

At the end, it looks like this is the question about the permissions of that role where the provider has little control over it. Do you agree? Please let me know if there are specific issues that are provider's.

**Comment by JanCVanB** [comment]
@edwardmedia Thank you for responding!

Yes, service account has both `roles/billing.costsManager` at the org level and `roles/editor` in all projects involved. Additionally, we granted it `roles/pubsub.editor` in the project where the Pub/Sub topic already exists. The most relevant documentation seems to be https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#permissions_required_for_this_task, which confirms that the service account having `billing.budgets.update` and `pubsub.topics.list` should be enough to complete this budget update.

**Comment by JanCVanB** [comment]
To clarify, this is the same service account that successfully created the Pub/Sub topic, created a budget without Pub/Sub notifications, created a budget with Pub/Sub notifications, and updated a budget to turn off those Pub/Sub notifications. We just can't get it to turn ***on*** the Pub/Sub notifications after it's already created.

**Comment by edwardmedia** [comment]
@JanCVanB I see what you meant. To repro the issue for me, do you have config of resources I can use?

**Comment by JanCVanB** [comment]
@edwardmedia The above example (under "Terraform Configuration Files") is how my team was using it when we encountered the bug, but I created the lower-level minimal reproduction below that successfully reproduced the bug - and it also narrowed the circumstances further! This repro initially accidentally succeeded because our actuation service account (which already had the Billing Account Costs Manager role for the billing account) accidentally had the Project Owner role on the project that contains the Pub/Sub topic (because this repro has the actuation service account create the project). Once I manually downgraded its roles in the Pub/Sub topic's project to Project Editor + Pub/Sub Editor, it failed as originally expected.

This tells me that at least one of the following permissions (the Pub/Sub-related difference between Project Owner and Project Editor) is necessary to update a budget to start sending notifications to a Pub/Sub topic:

```
pubsub.schemas.setIamPolicy
pubsub.snapshots.getIamPolicy
pubsub.snapshots.setIamPolicy
pubsub.subscriptions.getIamPolicy
pubsub.subscriptions.setIamPolicy
pubsub.topics.getIamPolicy
pubsub.topics.setIamPolicy
```

I'm going to start granting these permissions on-by-one to the actuation service account via a custom role, to see which one(s) are necessary.

Any thoughts?

## Setup

Apply this:

```terraform
terraform {
  backend "gcs" {
    bucket = "***" # redacted
    prefix = "terraform/state/budget-test"
  }
  required_version = "~> 1.4.6"
  required_providers {
    google = {
      version = "~> 4.65.2"
      source  = "hashicorp/google"
    }
  }
}

resource "google_project" "p" {
  name            = "janvb's budget test project"
  project_id      = "***" # redacted
  org_id          = "***" # redacted
  billing_account = data.google_billing_account.a.id
}

data "google_billing_account" "a" {
  billing_account = "***" # redacted
  open            = true
}

resource "google_billing_budget" "b" {
  billing_account = data.google_billing_account.a.id
  display_name    = "janvb@ budget test billing budget"
  amount {
    specified_amount {
      units         = "1"
      currency_code = "USD"
    }
  }
  # all_updates_rule {
  #   pubsub_topic = google_pubsub_topic.t.id
  # }
}

resource "google_pubsub_topic" "t" {
  name    = "janvb-budget-test-topic"
  project = "***" # redacted
  depends_on = [
    google_project.p
  ]
}
```

## Test

Uncomment the all_updates_rule block and reapply:

```terraform
terraform {
  backend "gcs" {
    bucket = "***" # redacted
    prefix = "terraform/state/budget-test"
  }
  required_version = "~> 1.4.6"
  required_providers {
    google = {
      version = "~> 4.65.2"
      source  = "hashicorp/google"
    }
  }
}

resource "google_project" "p" {
  name            = "janvb's budget test project"
  project_id      = "***" # redacted
  org_id          = "***" # redacted
  billing_account = data.google_billing_account.a.id
}

data "google_billing_account" "a" {
  billing_account = "***" # redacted
  open            = true
}

resource "google_billing_budget" "b" {
  billing_account = data.google_billing_account.a.id
  display_name    = "janvb@ budget test billing budget"
  amount {
    specified_amount {
      units         = "1"
      currency_code = "USD"
    }
  }
  all_updates_rule {
    pubsub_topic = google_pubsub_topic.t.id
  }
}

resource "google_pubsub_topic" "t" {
  name    = "janvb-budget-test-topic"
  project = "***" # redacted
  depends_on = [
    google_project.p
  ]
}
```

**Comment by edwardmedia** [comment]
@JanCVanB Thank a lot for doing the experiment. Overall isn't this a question about the permissions needed for some actions? Based on what you observed below, did you expect it work when the role is set as the Editor? The api dictates what it behaves.  I am not sure how the provider can help here. Does this make sense?

```
Just to reiterate, this test will succeed unless, after applying the setup, you downgrade the actuator's project role from Owner to Editor.
```

**Comment by edwardmedia** [comment]
@JanCVanB closing this as there is little the provider can do on this

**Comment by JanCVanB** [comment]
I agree! I'll pursue a documentation fix with Google Cloud.
