### ISSUE TITLE
google_container_node_pool: terraform-provider-google_v4.65.2_x5 Crash

### ISSUE THREAD

**Issue by wintergren** [hashicorp/terraform-provider-google#14669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.6

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Selected parts:

```tf
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster-update-variant"
  version = "~> 26.0"

  project_id        = local.project_id
  name              = var.name
  region            = local.region
  zones             = var.google_zones
  network           = var.vpc_network_name
  subnetwork        = var.vpc_subnet_name
  ip_range_pods     = var.vpc_subnet_pods_name
  ip_range_services = var.vpc_subnet_services_name

  http_load_balancing      = true
  remove_default_node_pool = true
  enable_private_endpoint  = false
  enable_private_nodes     = true
  network_policy           = true

  notification_config_topic = google_pubsub_topic.cluster_notifications.id

  monitoring_enabled_components = ["SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER"]
  logging_enabled_components    = ["SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER", "WORKLOADS"]

  kubernetes_version = var.kubernetes_version
  release_channel    = var.release_channel

  node_pools = local.node_pools

  node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  depends_on = [module.gke_api, module.gke_vpc]
}

variable "node_pools" {
  type = list(object({
    name : string
    machine_type : string
    autoscaling : bool
    min_count : number
    max_count : number
    auto_upgrade : bool
    auto_repair : bool
    strategy : string
  }))
  default = [{
    auto_upgrade = true
    auto_repair  = true
    autoscaling  = true
    machine_type = "n1-standard-8"
    max_count    = 2
    min_count    = 1
    name         = "default"
    strategy     = "BLUE_GREEN"
  }]
}

locals {
  node_pools = [
    for node_pool in var.node_pools :
    merge(node_pool, { service_account = module.gke_service_account.email, version = var.kubernetes_version })
  ]
}
```

### Panic Output

Stack trace from the terraform-provider-google_v4.65.2_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 27 [running]:
github.com/hashicorp/terraform-provider-google/google.nodePoolUpdate(0xc0027f6d00, {0x3188700?, 0xc000957200}, 0xc001900390, {0x0, 0x0}, 0x274a48a7800)
github.com/hashicorp/terraform-provider-google/google/resource_container_node_pool.go:1661 +0x3879
github.com/hashicorp/terraform-provider-google/google.resourceContainerNodePoolUpdate(0xc0027f6d00, {0x3188700?, 0xc000957200?})
github.com/hashicorp/terraform-provider-google/google/resource_container_node_pool.go:651 +0x354
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x37c3218?, {0x37c3218?, 0xc0018a4300?}, 0xd?, {0x3188700?, 0xc000957200?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00129cee0, {0x37c3218, 0xc0018a4300}, 0xc000edfba0, 0xc0027f6980, {0x3188700, 0xc000957200})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0013352d8, {0x37c3218?, 0xc0018a41e0?}, 0xc001675f90)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0012eede0, 0xc0012eee40, {0xc0019c82a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013950e0, {0x37c3218?, 0xc00189d770?}, 0xc002799d50)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x310eb20?, 0xc0013950e0}, {0x37c3218, 0xc00189d770}, 0xc002799ce0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0019181e0, {0x37cb1e0, 0xc001931ba0}, 0xc0027d8c60, 0xc001a96ae0, 0x4b35bc0, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0019181e0, {0x37cb1e0, 0xc001931ba0}, 0xc0027d8c60, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-google_v4.65.2_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

terraform apply succeed

### Actual Behavior

provider crash

### Steps to Reproduce

1. `terraform apply`

Changes made:
We were runnning v25.0 of terraform-google-modules/kubernetes-engine/google//modules/private-cluster-update-variant. This change upgraded the module to v26.0 and we changed cluster node pool upgrade strategy to BLUE_GREEN. No other changes.

### Important Factoids

Applying through a Terraform Cloud workspace. TFC workspace authenticating through GCP workload identity.

**Comment by wintergren** [comment]
@edwardmedia As mentioned we are using this [module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/private-cluster-update-variant) to provision our GKE cluster. So the actual blue_green block is in that module. The only change on our end was to update the module version

From
```module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster-update-variant"
  version = "~> 25.0"```

To 
```module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster-update-variant"
  version = "~> 26.0"```

and then update the node_pools variable so strategy is defined

```strategy     = "BLUE_GREEN"```

This is the code from the module we are using (public module) with the block you asked about (in v26):

```upgrade_settings {
    strategy        = lookup(each.value, "strategy", "SURGE")
    max_surge       = lookup(each.value, "strategy", "SURGE") == "SURGE" ? lookup(each.value, "max_surge", 1) : null
    max_unavailable = lookup(each.value, "strategy", "SURGE") == "SURGE" ? lookup(each.value, "max_unavailable", 0) : null

    dynamic "blue_green_settings" {
      for_each = lookup(each.value, "strategy", "SURGE") == "BLUE_GREEN" ? [1] : []
      content {
        node_pool_soak_duration = lookup(each.value, "node_pool_soak_duration", null)

        standard_rollout_policy {
          batch_soak_duration = lookup(each.value, "batch_soak_duration", null)
          batch_percentage    = lookup(each.value, "batch_percentage", null)
          batch_node_count    = lookup(each.value, "batch_node_count", null)
        }
      }
    }
  }```

and it looked like this in the previous version (v25):
```upgrade_settings {
    max_surge       = lookup(each.value, "max_surge", 1)
    max_unavailable = lookup(each.value, "max_unavailable", 0)
  }```

**Comment by rileykarson** [comment]
Repro (apply with red line first, then green ones second):

```diff
resource "google_container_node_pool" "with_upgrade_settings" {
  name               = "my-bg-np"
  location           = "us-central1"
  cluster            = google_container_cluster.cluster.name
  initial_node_count = 1


  upgrade_settings {
-    strategy = "SURGE"
+    strategy = "BLUE_GREEN"
+    blue_green_settings {
+      node_pool_soak_duration = "10s"
+
+      standard_rollout_policy {
+        batch_soak_duration = null
+        batch_percentage    = null
+        batch_node_count    = null
+      }
+    }
  }
}

data "google_container_engine_versions" "central1" {
  location = "us-central1"
}

resource "google_container_cluster" "cluster" {
  name               = "my-bg-cluster"
  location           = "us-central1"
  initial_node_count = 1
  min_master_version = data.google_container_engine_versions.central1.latest_master_version
}
```

Terraform can enter weird states when all the values of a block are nil. This code didn't handle that case correctly.
