### ISSUE TITLE
Error - Invalid value at 'job.hive_job' (oneof), oneof field 'queries' is already set. Cannot set 'queryList' : Dataproc Hive job submit with terraform

### ISSUE THREAD

**Issue by harsimran-lbg** [hashicorp/terraform-provider-google#14670]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6

### Affected Resource(s)

*google_dataproc_job

### Terraform Configuration Files

```tf
main.tf

data "google_service_account" "dataproc_sa" {
  account_id = var.dataproc_sa_name
  #  filter {
  #    name = "name"
  #    values = var.dataproc_sa_name
  #  }
}


resource "google_dataproc_cluster" "dcl-hive" {
  name                          = "dcl-hive"
  region                        = var.region
  graceful_decommission_timeout = "120s"
  labels = {
    foo = "bar"
  }
  cluster_config {
    staging_bucket = "hive-warehouse-simran"


    # Override or set some custom properties

    software_config {
      image_version = "2.0.35-debian10"
      override_properties = {
        "dataproc:dataproc.allow.zero.workers" = "true",
        "hive:hive.metastore.warehouse.dir" = "gs://hive-warehouse-simran/datasets"
      }
    }


    gce_cluster_config {
      tags = ["foo", "bar"]
      # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
      service_account = data.google_service_account.dataproc_sa.email
      service_account_scopes = [
        "cloud-platform",
        "sql-admin"
      ]
      #  big query connector
      metadata = {
        hive-metastore-instance = "playpen-f0ctgm:europe-west2:hive-metastore-db"
        enable-cloud-sql-proxy-on-workers = "false"
      }
    }
    initialization_action {
      script      = "gs://goog-dataproc-initialization-actions-${var.region}/cloud-sql-proxy/cloud-sql-proxy.sh"
      timeout_sec = 500
    }

  }
}

resource "google_dataproc_job" "hive-job" {
  region       = var.region
  force_delete = true
  placement {
    cluster_name = "dcl-hive"
  }
  hive_config {
    #    query_file_uri = "./account-status-ext-table-script.q"

    query_file_uri = "gs://hive-warehouse-simran/datasets/account-status-ext-table-script.q"
  }
}
```

### Panic Output

│ Error: googleapi: Error 400: Invalid value at 'job.hive_job' (oneof), oneof field 'queries' is already set. Cannot set 'queryList'
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value at 'job.hive_job' (oneof), oneof field 'queries' is already set. Cannot set 'queryList'",
│         "field": "job.hive_job"
│       }
│     ]
│   }
│ ]

### Expected Behavior

A succcesful hive job should have been submitted to the dataproc cluster with the output of the external table in the jobs console on google console.

### Actual Behavior

Even though Have set the query file uri link for google storage where the Query script is stored and to be referred by dataproc cluster to submit hive job, its just not taking this variable value and in turn throwing error on query list is not set. 
From documentation it is written we can either set query list(where we can literrally mention which query to run) or query file uri ( that stored the hive query file to be run which contains set of queries)

This works well with gcloud cli command with the same params given as with terraform google_dataproc_job resource block:
commands:
 cluster creation :
gcloud dataproc clusters create dcl-hive \
    --scopes sql-admin,cloud-platform \
    --region ${REGION} \
    --initialization-actions gs://goog-dataproc-initialization-actions-${REGION}/cloud-sql-proxy/cloud-sql-proxy.sh \
    --properties "hive:hive.metastore.warehouse.dir=gs://hive-warehouse-simran/datasets" \
    --metadata "hive-metastore-instance=${PROJECT}:${REGION}:hive-metastore" \
    --metadata "enable-cloud-sql-proxy-on-workers=false" \
    [--service-account](https://cloud.google.com/sdk/gcloud/reference/dataproc/clusters/create#--service-account)=<my_service_account>

hive job submit command:

gcloud dataproc jobs submit hive \
    --cluster dcl-hive \
    --region ${REGION} \
    --file="gs://hive-warehouse-simran/datasets/account-status-ext-table-script.q";

Successful output with gcloud cli- 

INFO  : Completed executing command(queryId=hive_20230522091737_7cca2c4a-1c59-4ccc-a554-a4dde6f677f7); Time taken: 21.709 seconds
INFO  : OK
INFO  : Concurrency mode is disabled, not creating a lock manager
33 rows selected (24.565 seconds)
0: jdbc:hive2://dcl-hive-m:10000> 
0: jdbc:hive2://dcl-hive-m:10000> 
0: jdbc:hive2://dcl-hive-m:10000> 
0: jdbc:hive2://dcl-hive-m:10000> Closing: 0: jdbc:hive2://dcl-hive-m:10000
Job [c653bce7cb0841bbb65a1737498562f4] finished successfully.
done: true
driverControlFilesUri: gs://hive-warehouse-simran/google-cloud-dataproc-metainfo/6ad064c9-9887-4cdc-8332-8b75b6401edb/jobs/c653bce7cb0841bbb65a1737498562f4/
driverOutputResourceUri: gs://hive-warehouse-simran/google-cloud-dataproc-metainfo/6ad064c9-9887-4cdc-8332-8b75b6401edb/jobs/c653bce7cb0841bbb65a1737498562f4/driveroutput
hiveJob:
  queryFileUri: gs://hive-warehouse-simran/datasets/account-status-ext-table-script.q
jobUuid: 593f4d98-97d6-3d92-ac13-ee7fe7693751
placement:
  clusterName: dcl-hive
  clusterUuid: 6ad064c9-9887-4cdc-8332-8b75b6401edb
reference:
  jobId: c653bce7cb0841bbb65a1737498562f4
  projectId: playpen-f0ctgm
status:
  state: DONE
  stateStartTime: '2023-05-22T09:18:06.210798Z'
===============

### Steps to Reproduce

Just paste the above main.tf code to submit job to dataproc cluster.( this needs sql instance to be created to store hive metastore which was already created in my case)

and just`terraform apply`

### References

(https://cloud.google.com/architecture/using-apache-hive-on-cloud-dataproc/deployment)
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_job#nested_hive_config -- search for keywords "resource "google_dataproc_job" "hive"

**Comment by edwardmedia** [comment]
@harsimranlloyds I can't run your script as there are two unknown dependencies. Can you share the debug logs for 1) terraform apply 2) both gcloud commands so I can table a look at the details?

**Comment by slevenick** [comment]
Closing as not reproducible. Feel free to reopen and include reproduction steps if this is still an issue
