### ISSUE TITLE
Terraform Google Provider 4.66 -> google_dataflow_flex_template_job reports max_workers & num_workers as null

### ISSUE THREAD

**Issue by shermanericts** [hashicorp/terraform-provider-google#14679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
 terraform -v
2023-05-22T16:10:13.140-0700 [INFO]  Terraform version: 1.3.9
2023-05-22T16:10:13.143-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2023-05-22T16:10:13.143-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.0
2023-05-22T16:10:13.143-0700 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-05-22T16:10:13.143-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-05-22T16:10:13.143-0700 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-05-22T16:10:13.143-0700 [INFO]  Go runtime version: go1.19.6
2023-05-22T16:10:13.143-0700 [INFO]  CLI args: []string{"terraform", "-v"}
2023-05-22T16:10:13.143-0700 [DEBUG] Attempting to open CLI config file: /Users/esherman/.terraformrc
2023-05-22T16:10:13.143-0700 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-05-22T16:10:13.146-0700 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-05-22T16:10:13.146-0700 [DEBUG] ignoring non-existing provider search directory /Users/esherman/.terraform.d/plugins
2023-05-22T16:10:13.146-0700 [DEBUG] ignoring non-existing provider search directory /Users/esherman/Library/Application Support/io.terraform/plugins
2023-05-22T16:10:13.146-0700 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-05-22T16:10:13.148-0700 [INFO]  CLI command args: []string{"version", "-v"}
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/elastic/ec v0.7.0
+ provider registry.terraform.io/elastic/elasticstack v0.5.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/google v4.66.0
+ provider registry.terraform.io/hashicorp/google-beta v4.66.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Affected Resource(s)

* google_dataflow_flex_template_job

### Terraform Configuration Files

```
  # module.customer_env.module.system_ledger.google_dataflow_flex_template_job.system-ledger-ingress must be replaced
-/+ resource "google_dataflow_flex_template_job" "system-ledger-ingress" {
      ~ additional_experiments       = [] -> (known after apply)
      ~ id                           = "2023-05-22_14_47_16-6732291074181799549" -> (known after apply)
      ~ job_id                       = "2023-05-22_14_47_16-6732291074181799549" -> (known after apply)
      - labels                       = {} -> null
      - machine_type                 = "n1-standard-1" -> null
      - max_workers                  = 0 -> null
        name                         = "system-ledger-ingress"
      - num_workers                  = 1 -> null # forces replacement
      ~ service_account_email        = "<REDACTED>" -> (known after apply)
      ~ staging_location             = <REDACTED> -> (known after apply)
      ~ state                        = "JOB_STATE_RUNNING" -> (known after apply)
      ~ temp_location                = <REDACTED> -> (known after apply)
      ~ type                         = "JOB_TYPE_STREAMING" -> (known after apply)
        # (6 unchanged attributes hidden)
    }
```

### Expected Behavior

No changes should have been found.
### Steps to Reproduce
 

 1. Run a `terraform plan`

* The flex template is in the changelog as the num_workers and max_workers are now null.  Repeated applies and subsequent plans continue to prompt for same change.

### Important Factoids

Nothing extraordinary.
### References

* None.

I can provide a gist as need be.  While I didn't see anything sensitive, I wasn't sure if there were best practices of ensuring Terraform Debug Output has been sanitized.

**Comment by n-oden** [comment]
Something else is definitely deeply awry with `google_dataflow_flex_template_job` in 4.66.  Suddenly all of our attempts to launch/relaunch flex job report failure with this error:

```
Error: googleapi: Error 400: The template parameters are invalid. Details: serviceAccount: Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended. Details: [ { "@type": "type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters", "parameterViolations": [ { "description": "Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended.", "parameter": "serviceAccount" } ] } ] , badRequest
```

...but in fact the job _has_ been launched, so a subsequent run will fail because, well:

```
Error: googleapi: Error 409: (1c7a95bfb9b0ab10): There is already an active job named <jobname>. If you want to submit a second job, try again by setting a different name., alreadyExists
```

**Comment by edwardmedia** [comment]
That is true. Below changes was added in the https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.66.0

dataflow: added multiple fields to google_dataflow_flex_template_job (https://github.com/hashicorp/terraform-provider-google-beta/pull/5635)

**Comment by shermanericts** [comment]
> That is true. Below change was added in the https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.66.0
> 
> dataflow: added multiple fields to google_dataflow_flex_template_job ([hashicorp/terraform-provider-google-beta#5635](https://github.com/hashicorp/terraform-provider-google-beta/pull/5635))
> 
> I am having hard time to run a config. Anyone has one?

Thanks @edwardmedia !
Is the terraform configuration file in the top enough?  What else what you need?

**Comment by shermanericts** [comment]
> @shermanericts the configuration file in the top is not enough. That is a plan. I need a config. Do you have the debug log that can be shared? I'd like to take a look at the api requests and responses.

I have a log @edwardmedia .  While I don't think there's anything that would be sensitive, it would be great to somehow send that securely.  Do you have any thoughts?  Would `TF_LOG_PROVIDER` be enough or are the Terraform logs on average safe to send out.

**Comment by edwardmedia** [comment]
export TF_LOG=DEBUG

Yeah, I don't have a secure channel for the debug file. gist is the place I would suggest. It is public, you do need to redact the sensitive data before uploading the file

Thank you @shermanericts

**Comment by shermanericts** [comment]
https://gist.github.com/shermanericts/1ac9dbe81b5f7e427afae1a3524be20d

**Comment by shermanericts** [comment]
sorry  @edwardmedia  https://gist.github.com/shermanericts/78bf89f97c5173d4d4528a6b7e715fc8 should be it!

**Comment by edwardmedia** [comment]
I noticed the added fields are not listed in the [doc](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataflow_flex_template_job)

**Comment by shermanericts** [comment]
> I noticed the added fields are not listed in the [doc](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataflow_flex_template_job)

Sorry it took a bit.  What fields are you referring to?
We've adhered to [Dataflow Pipeline Options](https://cloud.google.com/dataflow/docs/reference/pipeline-options)

Does it have to do somehow with casing?  `numWorkers` now instead of `num_workers` for numWorkers in the referenced document?   4.65.2 worked fine.

**Comment by edwardmedia** [comment]
@shermanericts what I referred to the doc, for example, shouldn't [num_workers](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_dataflow_flex_template_job.go#LL107C20-L108C1) listed [here](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataflow_flex_template_job)?

**Comment by shermanericts** [comment]
> @shermanericts what I referred to about the doc, shouldn't [num_workers](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_dataflow_flex_template_job.go#LL107C20-L108C1) show [here](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataflow_flex_template_job), for example?

So you can list additional parameters using `parameters` that links to additional Google Pipeline Options + ones that the application can set, itself.  There was some back and forth [here](https://github.com/terraform-google-modules/terraform-google-dataflow/issues/17) a while back.  

I'll try using camel casing with 4.60 to see if that makes a difference.

**Comment by shermanericts** [comment]
Ah. interesting, I specify camel case, it's the terraform plan that specifies snake case (see the initial comment).  Here's my full resource config.

```
resource "google_dataflow_flex_template_job" "system-ledger-ingress" {
  provider = google-beta

  name                    = "system-ledger-ingress"
  project                 = var.project
  container_spec_gcs_path = "gs:/<REDACTED>/templates/system-ledger-ingress-${var.system_ledger_version}.json"
  on_delete               = local.dataflow_job_delete_action
  region                  = var.region

  parameters = {
    agentReportsSubscription = google_pubsub_subscription.agent_reporting_updates.id
    agentUpdatesSubscription = google_pubsub_subscription.agent_lifecycle_updates.id
    appName                  = "SystemLedgerIngress"
    autoscalingAlgorithm     = "THROUGHPUT_BASED"
    diskSizeGb               = 30
    enableStreamingEngine    = true
    ephiModelType            = local.decision_model_type
    ledgerTopic              = google_pubsub_topic.system-ledger-updates-topic.id
    maxNumWorkers            = 10
    numWorkers               = 1
    project                  = var.project
    projectId                = var.project
    region                   = var.region
    runner                   = "DataflowRunner"
    serviceAccount           = google_service_account.system_ledger_ingress_service_account.email
    telemetrySubscription    = "projects/${var.project}/subscriptions/${google_pubsub_subscription.agent-telemetry-subscription.name}"
    usePublicIps             = false
    workerMachineType        = "n1-standard-1"
  }
}
```

**Comment by shermanericts** [comment]
Hi @edwardmedia .  I don't know what else I can try.  I think I have the right configuration.  Please advise when able thanks!

**Comment by markveg** [comment]
Hi all, any news on this one - seeing the same issues as above but we also see the same happening with the subnetwork parameter also :(

**Comment by shermanericts** [comment]
@markveg is right.  @edwardmedia and @rileykarson, curious what the `documentation` tag is on this for?  I know we had back and forth, but a regression has happened per initial comments with running dataflow jobs as of 4.66 that did not happen in previous versions.

**Comment by rileykarson** [comment]
The documentation tag was because the PR adding these fields did not add documentation for these fields. @edwardmedia can you file a separate bug instead? Thanks!

> Something else is definitely deeply awry with google_dataflow_flex_template_job in 4.66. Suddenly all of our attempts to launch/relaunch flex job report failure with this error:

Ultimately the _root_ cause here is the unstructured `parameters` field. Many fields on the the resource can be configured either through its actual API surface (https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.flexTemplates/launch#FlexTemplateRuntimeEnvironment) or through `parameters`, in which case the API writes the value from `parameters` into the configured values from the API.

Terraform's not great at handling fields whose values are based on other fields, or cases like this where something can be configured in multiple ways. We're seeing different behaviour between `num_workers` and `service_account_email` because they're configured slightly differently.

* `num_workers` is configured as optional, which means Terraform will see a diff between the live resource and configuration when the value is set in `parameters`
* `service_account_email` is set as "optional with complex default (optional + computed)" which mitigates this, but introduces a new problem- when reading the current state of the resource, the value appears in both parameters and the resource body. When we send an update request (as the field is marked as updatable), _both_ `parameters.serviceAccountEmail` and `service_account_email` are present 

The contributor and reviewers for the change discussed above missed that nuance, and made changes that were reasonable for the relatively simple configurations that our test configurations (which are relatively simple).

---

Are the possible parameters documented anywhere? https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.flexTemplates/launch#launchflextemplateparameter just says "The parameters for FlexTemplate. Ex. {"numWorkers":"5"}", https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#run-a-flex-template-pipeline uses but does explain them, and https://cloud.google.com/dataflow/docs/guides/templates/configuring-flex-templates#specify-options explains that they're pipeline options, while https://cloud.google.com/dataflow/docs/guides/setting-pipeline-options does not state that pipeline options can be configured through the API.

That makes me _think_ https://cloud.google.com/dataflow/docs/reference/pipeline-options is correct, but I'm really not certain.

**Comment by rileykarson** [comment]
Ah- definitely incomplete, `outputTable` appears in https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#run-a-flex-template-pipeline but not in https://cloud.google.com/dataflow/docs/reference/pipeline-options

**Comment by shermanericts** [comment]
Thanks @rileykarson ! I was about to suggest reverting https://github.com/hashicorp/terraform-provider-google-beta/pull/5635/files as https://github.com/hashicorp/terraform-provider-google/issues/13189 was an enhancement request.

I have no problem adding additional parameters in the parameters block as I coped in my config above.

Thanks for chasing down the Google documentation on this one!

**Comment by komasoftware** [comment]
Hi 

We are seeing the same issue as described by @n-oden  : 

> Something else is definitely deeply awry with `google_dataflow_flex_template_job` in 4.66. Suddenly all of our attempts to launch/relaunch flex job report failure with this error:
> 
> ```
> Error: googleapi: Error 400: The template parameters are invalid. Details: serviceAccount: Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended. Details: [ { "@type": "type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters", "parameterViolations": [ { "description": "Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended.", "parameter": "serviceAccount" } ] } ] , badRequest
> ```
> 
> ...but in fact the job _has_ been launched, so a subsequent run will fail because, well:
> 
> ```
> Error: googleapi: Error 409: (1c7a95bfb9b0ab10): There is already an active job named <jobname>. If you want to submit a second job, try again by setting a different name., alreadyExists
> ```

Looking at the actual API call, the `service account` parameter should be specified in an `environment` block within the parameters but this is not exposed, see also https://github.com/hashicorp/terraform-provider-google/issues/9291

I added a [comment on issue 9291](https://github.com/hashicorp/terraform-provider-google/issues/9291#issuecomment-1572801769) earlier but @rileykarson pointed me here.

Now we tried rolling back to `4.60` release of the Google provider but this error persists.

Seeking advice !

**Comment by msenmurugan** [comment]
@rileykarson I have a dataflow flex template job that existed before. 

The Terraform plan shows three changes that attempt to remove machine_type, network, and subnetwork even though we haven't changed the dataflow flex template job settings and have instead updated the Terraform provider to version 4.68.0. If we apply the changes, then facing the below issue
```
Error: googleapi: Error 400: The template parameters are invalid. Details: serviceAccount: Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended. Details: [ { "@type": "type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters", "parameterViolations": [ { "description": "Runtime parameter serviceAccount should not be specified in both parameters field and environment field. Specifying runtime parameters in environment field is recommended.", "parameter": "serviceAccount" } ] } ] , badRequest
with google_dataflow_flex_template_job.ingest_pipeline_dataflow_job
```

 We have reverted the terraform provider version to 4.64.0, the TF plan shows no changes now.

**Comment by komasoftware** [comment]
@msenmurugan 
We fixed it by rolling back to an earlier version of the `google` AND `google-beta` provider.

**Comment by bvolpato** [comment]
+1. This is causing problems for many Dataflow users. Can we revert the changes at https://github.com/hashicorp/terraform-provider-google-beta/pull/5635?

**Comment by shermanericts** [comment]
Hi @rileykarson . Thanks again for all of your details so far.  Just some clarifying questions to some of the back and forth above.  Sorry for the forthcoming naivete.


> RE: https://github.com/GoogleCloudPlatform/magic-modules/pull/8026. This reverts commit 17924ba.

  * I see some breaking change failures in the terraform providers test preventing this PR.  Curious what may have changed where the revert of a working previous provider is now failing?  I'd be new to Go, but is there anything the community can do here to help get this over the line?

>  RE:  ..Many fields on the the resource can be configured either through its actual API surface..or through parameters, in which case the API writes the value from parameters into the configured values from the API.
 * If this is ambiguous to Terraform, can the dataflow portion of the provider simply decide whether to interact directly with the API surface or through Parameters?  

> num_workers is configured as optional, which means Terraform will see a diff between the live resource and configuration when the value is set in parameters
* What if in the future the provider requires these.  Would that make it easier to implement?

> I'm really not a fan of reverting things we've released, but the fix-forward here is complicated and will lead to surprising behaviours pretty much no matter what.
* I understand.  I'd rather not revert code either.  However, It would be great in this case to do so as it is blocking upgrading the Google Provider in general.   Furthermore, up until the breaking change I was able to run my flex template jobs in Terraform without fail.  While it's ok for us to pin to a provider version in the short term, but at some point  we will have a  dependency on upgrading the provider due to other reasons.  At this point, we'll probably have to abandon running dataflow jobs in terraform and use gcloud directly. 

Thanks again, let us know what the community can do to support this.  Again, I'd be new to Go so I'd have a steep learning curve, but I want to see what I can do to help the cause on this one.

**Comment by prensoni0143** [comment]
> @msenmurugan We fixed it by rolling back to an earlier version of the `google` AND `google-beta` provider.

How did it fix? could you offer link to dataflow flex template terraform sample and as well let me know which google-beta version to use?

**Comment by bvolpato** [comment]
@prensoni0143 Using google-beta version `4.65` should avoid the errors here.

**Comment by rileykarson** [comment]
A revert is not possible due to the time since the release, anymore- there was a window of opportunity of a few days where it would have been viable, but other members of the provider team were (understandably!) skeptical, and I couldn't find the cycles to test the revert extensively enough to move forward with it within the window (I got hung up on determining the list of options possible in `parameters`, when following up on my comments discussing https://cloud.google.com/dataflow/docs/reference/pipeline-options) . I've now closed the pull request.

Fixing this will require stopping Terraform from double-sending these values by writing custom logic to deduplicate the request. Longer-term, we may want to evaluate eliminating the ability to double-specify the values by removing the ability to specify either the first-class fields or the `parameters` values.

**Comment by shermanericts** [comment]
Thanks @rileykarson for the explanation!
While it's a saddening that a revert is no longer viable here, I understand the confusion.  I like the idea of your longer term point - we should only need to specify the values in one place.

For now, I'll pin to the previous version as mentioned above.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/9031
