### ISSUE TITLE
Terraform creates a new SQL instance when SSD capacity is auto-incremented, breaking references to the old instance.

### ISSUE THREAD

**Issue by romanstingler** [hashicorp/terraform-provider-google#14671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
on linux_amd64

### Affected Resource(s)

* google_cloud_run_service
* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "master" {
  name             = "my-sql-instance"
  region           = "us-central1"
  database_version = "POSTGRES_15"

  settings {
    tier = "db-f1-micro"
  }

    disk_autoresize       = true
    disk_autoresize_limit = 0
    disk_size             = 10
}

resource "google_cloud_run_service" "foo" {
  metadata {
    annotations = {
      "run.googleapis.com/cloudsql-instances" = google_sql_database_instance.master.connection_name
    }
  }
}
```

### Actual Behavior

When the SSD capacity for a SQL instance is configured to autoincrement in Terraform, Terraform will destroy the existing instance and create a new one. This breaks any external references to the SQL instance, such as Cloud Run service annotations referencing the connection name.

When Terraform applies this configuration a second time, it will destroy the existing google_sql_database_instance and recreate it with an incremented storage size.

However, any resources referencing the SQL instance connection name via attributes will now be broken.

During the second Terraform apply, the google_cloud_run_service.foo annotation value will be marked for deletion, since it refers to the old SQL instance connection name.

This behavior can break infrastructure when SQL instances are auto-scaled via storage capacity.

Suggestion: 

    * When storage_auto_increase is set, increment the storage capacity of the existing SQL instance instead of destroying/recreating it.

**Comment by edwardmedia** [comment]
@romanstingler where did you see `storage_auto_increase` supported?

**Comment by edwardmedia** [comment]
@romanstingler where did you see `storage_auto_increase` and `storage_gb` in `google_sql_database_instance`? I see [disk_autoresize](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#disk_autoresize) and [storageAutoResize](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances) in the api. The default of both are true.

Could you detail the steps about the issue?

**Comment by romanstingler** [comment]
@edwardmedia sorry fixed the code example. 
There should be an explicit warning (at the beginning and/or at the end of the changelog that the DB Instance will be replaced and not throw these errors 


`│ Error: Error connecting to PostgreSQL server  (scheme: gcppostgres): gcppostgres: open gcppostgres://postgres:XXXX@:5432/postgres?fallback_application_name=Terraform+provider: :5432/postgres is not in the form project/region/instance/dbname`

```
  ~ resource "google_cloud_run_service" "app_backend" {
        id                         = "locations/europe-west3/namespaces/w/services/app-backend"
        name                       = "hydration-app-backend"
        # (4 unchanged attributes hidden)

      ~ metadata {
          ~ annotations      = {
              - "run.googleapis.com/cloudsql-instances" = "w:europe-west3:x-db" -> null
              - "run.googleapis.com/ingress"            = "all" -> null
                # (7 unchanged elements hidden)
            }
            # (6 unchanged attributes hidden)
        }

      ~ template {
          ~ metadata {
              ~ annotations = {
                  - "autoscaling.knative.dev/maxScale"         = "100"
                  - "autoscaling.knative.dev/minScale"         = "1"
                  - "client.knative.dev/user-image"            = "eu.gcr.io/w/app-backend:latest"
                  - "run.googleapis.com/client-name"           = "gcloud"
                  - "run.googleapis.com/client-version"        = "431.0.0"
                  - "run.googleapis.com/cloudsql-instances"    = "w:europe-west3:x-db"
                  - "run.googleapis.com/cpu-throttling"        = "true"
                  - "run.googleapis.com/execution-environment" = "gen2"
                  - "run.googleapis.com/sessionAffinity"       = "false"
                  - "run.googleapis.com/startup-cpu-boost"     = "true"
                } -> (known after apply)
                name        = "app-backend-00102-foq"
                # (2 unchanged attributes hidden)
            }

            # (1 unchanged block hidden)
        }

        # (2 unchanged blocks hidden)
    }
    
    ```
    
    I know that there is also 
    
`   ~ disk_size                   = 200 -> 20 # forces replacement`
but if you have a longer configuration than this affects maybe hundreds of objects and then finding this piece is not user friendly.

There should be at least a warning that a reference will be destroyed. 
Furthermore, I would suggest that in the docs it will be stated that this setting could cause the DB instance to be replaced and cause issues if not excluded (ignore_changes)(disk_size in combination with disk_autoresize) .

**Comment by edwardmedia** [comment]
@romanstingler Sorry for your experiencing inconvenience, but this is common behavior for Terraform resources. Besides `disk_size`, there are more fields in `google_cloud_run_service`. Any changes on those fields will force replacement. 

```
~ disk_size                   = 200 -> 20 # forces replacement`
```

Did you see below warning on top of the resource in the plan? This is built in the terraform. Please let me know if that warning was missing. 
```
# google_cloud_run_service. app_backend must be replaced
```

**Comment by edwardmedia** [comment]
@romanstingler closing the issue as this is expected. Feel free to reopen if you see it differently.
