### ISSUE TITLE
Remove support for Game Services

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#14688]
There doesn't appear to be an associated blog post or release note, but the recommendation for existing customers has been to migrate to an alternative solution such as [Agones](https://agones.dev/site/) on GKE.

No open issues regarding these resources (that I could find).

**Comment by roaks3** [comment]
One other note: we should make sure to remove any internal documentation that references these resources (ie. for testing)

**Comment by hao-nan-li** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/8669
