### ISSUE TITLE
Set EKU (extended key usages) to "critical" in GCP CA using google_privateca_certificate_authority

### ISSUE THREAD

**Issue by saisatishkarra** [hashicorp/terraform-provider-google#14684]
Hi All, I am trying to mark the extension key usages to "critical" when setting the timestamping bit using terraform. Is there a guide on how to set EKU in google_privateca_certificate_authority of type "subordinate" in x509 config?

The critical= true in `name_constraints` is only applied to basic key usages but not EKU.

Is this possible to be defined? I can raise a bug if someone can confirm this.

**Sample config:**
```
resource "google_privateca_certificate_authority" "tsa_intermediate_ca" {
  pool = google_privateca_ca_pool.tsa_intermediate_ca_pool.name
  certificate_authority_id = lower(join("-",[var.project_prefix, local.tsa_ca_app_prefix, "intermediate-ca", var.environment]))
  location = var.default_region
  deletion_protection = var.ca_deletion_protection
  subordinate_config {
    certificate_authority = google_privateca_certificate_authority.tsa_root_ca.name
  }
  config {
    subject_config {
      subject {
        organization = "xxxx"
        common_name = "xxx-intermediate"
        locality = "xxx"
        province = "xx"
      }
    }
    x509_config {
      ca_options {
        is_ca = true
        max_issuer_path_length = 0
      }
      key_usage {
        base_key_usage {
          cert_sign = true
          crl_sign = true
        }
        extended_key_usage { 
         time_stamping = true
        }
      }
      name_constraints {
        critical = true
      }
    }
  }
  key_spec {
    cloud_kms_key_version = trimprefix(data.google_kms_crypto_key_version.tsa_ca_key_version.id, "//cloudkms.googleapis.com/v1/")
  }
  lifetime = "315360000s" # 10yrs
  project = local.project_id
  type = "SUBORDINATE"
  lifecycle {
    prevent_destroy = false
  }
}
```

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@saisatishkarra are you able to achieve that in other ways, like gcloud? If yes, can you share the command?

**Comment by saisatishkarra** [comment]
@edwardmedia  I haven't tried this using gcloud cli. I wanted to know if this is even supported and how to achieve it on gcloud. This is possible using OpenSSL and specifying the critical bit using a configuration file.

**Comment by saisatishkarra** [comment]
The subordinate certificate provisioned by the rootCA on UI doesn't let me edit the critical bit for EKU. 
![Screen Shot 2023-05-23 at 10 28 28 AM](https://github.com/hashicorp/terraform-provider-google/assets/29549979/1e15a756-4393-4636-9f21-e23c38692bf4)

I am hoping that this should be consistent and possibly similar to the OpenSSL configuration that lets to make EKU critical.

**Comment by saisatishkarra** [comment]
> swer. If that feature is supported by gcp, and you can enable it with certain means, we

Yes, it is a sample screenshot from my GCP console. Is there a channel/support where I could reach out to GCP to check if this is supported?

**Comment by edwardmedia** [comment]
@saisatishkarra please check [this](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) out 

By now, I am closing this question. You may file an enhancement once the feature is supported on GCP.
