### ISSUE TITLE
google_project_service: 160009 issues when activating services

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#14691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Not provider version specific

### Affected Resource(s)

* google_project
* google_project_service

### Terraform Configuration Files

```tf
resource "google_project_service" "project" {
  project = "your-project-id"
  service = "pubsub.googleapis.com"

  timeouts {
    create = "30m"
    update = "40m"
  }

  disable_dependent_services = true
}
```

### Debug Output

```

2023/05/23 06:53:51 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /v1/operations/acf.p2-694719461930-74da0502-0521-410e-bcd4-e90254cf6a0c?alt=json HTTP/1.1
Host: serviceusage.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/dev
Content-Type: application/json
Accept-Encoding: gzip
 
 
-----------------------------------------------------
2023/05/23 06:53:51 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Tue, 23 May 2023 06:53:51 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
 
{
  "name": "operations/acf.p2-694719461930-74da0502-0521-410e-bcd4-e90254cf6a0c",
  "metadata": {
    "@type": "type.googleapis.com/google.protobuf.Empty"
  },
  "done": true,
  "error": {
    "code": 3,
    "message": "[service pubsub.googleapis.com encountered internal error: type: \"googleapis.com\" subject: \"160009\" ] with failed services [pubsub.googleapis.com]",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "googleapis.com",
            "subject": "160009"
          }
        ]
      }
    ]
  }
}
```

### Expected Behavior

Service activation succeeds.

### Actual Behavior

An intermittent, flaky error from the GCP API that has increased in frequency over the last few days.

### Steps to Reproduce

1. `terraform apply`

### References

* yaqs/595690111161597952

**Comment by nphilbrook** [comment]
Thank you for opening this, Riley. For your reference we also have a P1 support case opened with GCP support on this issue https://console.cloud.google.com/support/cases/detail/v2/45091689?organizationid=825417849120

**Comment by nphilbrook** [comment]
Also for reference the most frequent context we see this error in is not `google_project_service` but rather `google_project` with `auto_create_network` set to false - since it has to enable the Compute API to delete the default network:
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/resources/resource_google_project.go#L185
I mention it just in case there is a work around in the provider to add some retry or something, that this use case isn't missed. Thanks!

**Comment by rileykarson** [comment]
Yeah, I'm aware of both- the Google-internal link I shared was about `google_project`, our nightlies had reproduced it in `google_project_service` so those are the logs I had available! Both resources are listed under references & share the function I'll need to amend, so fixing on will fix the other anyways.

**Comment by ScottSuarez** [comment]
Related to [TestAccBinaryAuthorizationPolicy_update failure](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=4390737544047082530&tab=testDetails)

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/8017 should resolve, we'll cherrypick it into the Monday release once merged.

**Comment by nphilbrook** [comment]
Thank you so much Riley for working on this. We almost pulled down your changes and built locally but just waiting on the fix on the backend and the release on Tuesday at this point.
