### ISSUE TITLE
Support BigQuery GCS Object Metadata external table 

### ISSUE THREAD

**Issue by caleb-recursion** [hashicorp/terraform-provider-google#14694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi. BigQuery supports a special type of external table designed for querying GCS object metadata. Documented [here](https://cloud.google.com/bigquery/docs/object-tables). As far as I can tell there is no way to define it with a terraform provider. Would be a really helpful feature. Thanks!

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "table" {
  dataset_id = google_bigquery_dataset.dataset.dataset_id
  table_id   = "some_id"

  external_data_configuration {
    autodetect    = true
    source_format = "GCS_METADATA"
    object_metadata = "SIMPLE"
    connection_id = google_bigquery_connection.connection.connection_id

    source_uris = [
      "gs://bucket/*",
    ]
  }
}
```

### References

* https://cloud.google.com/bigquery/docs/object-tables

b/284511149

**Comment by sachinpro** [comment]
> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.
> 
> ### Description
> Hi. BigQuery supports a special type of external table designed for querying GCS object metadata. Documented [here](https://cloud.google.com/bigquery/docs/object-tables). As far as I can tell there is no way to define it with a terraform provider. Would be a really helpful feature. Thanks!
> 
> ### New or Affected Resource(s)
> * google_bigquery_table
> 
> ### Potential Terraform Configuration
> ```terraform
> resource "google_bigquery_table" "table" {
>   dataset_id = google_bigquery_dataset.dataset.dataset_id
>   table_id   = "some_id"
> 
>   external_data_configuration {
>     autodetect    = true
>     source_format = "GCS_METADATA"
>     object_metadata = "SIMPLE"
>     connection_id = google_bigquery_connection.connection.connection_id
> 
>     source_uris = [
>       "gs://bucket/*",
>     ]
>   }
> }
> ```
> 
> ### References
> * https://cloud.google.com/bigquery/docs/object-tables
> 
> b/284511149

Isn't this already [here](https://github.com/hashicorp/terraform-provider-google/blob/547c48edd324faad09274c6d1c0746514817c596/google/resource_bigquery_table_test.go#L1625)

**Comment by carusooo** [comment]
> @caleb-recursion Isn't this already [here](https://github.com/hashicorp/terraform-provider-google/blob/547c48edd324faad09274c6d1c0746514817c596/google/resource_bigquery_table_test.go#L1625) ?

The linked code doesn't cover this infra since there's a requirement in terraform to provide a `source_format` which conflicts with the underlying [API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#objectmetadata:~:text=external%20data%20source.-,objectMetadata,Currently%20SIMPLE%20is%20the%20only%20supported%20Object%20Metadata%20type.,-FileSetSpecType):

> ObjectMetadata is used to create Object Tables. Object Tables contain a listing of objects (with their metadata) found at the sourceUris. If ObjectMetadata is set, sourceFormat should be omitted. Currently SIMPLE is the only supported Object Metadata type.

**Comment by DrFaust92** [comment]
closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/7128

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7128
