### ISSUE TITLE
google_sql_user - password_policy block is not supporting, throwing errors when terraform plan

### ISSUE THREAD

**Issue by yeshwanth14** [hashicorp/terraform-provider-google#14722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on linux_amd64

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

resource "google_sql_user" "users" {
  count = length(local.users)

  name     = local.users[count.index].user
  instance = local.users[count.index].instance_name
  host     = local.users[count.index].host
  password_policy = {
    allowed_failed_attempts      = 3
    password_expiration_duration = "90d"
  }

  password = data.google_secret_manager_secret_version.passwords[count.index].secret_data
  project  = var.project_id

  depends_on = [data.google_secret_manager_secret_version.passwords, google_sql_database_instance.sql_database_instance]
}

### Debug Output

 Error: Unsupported argument
│ 
│   on ../../modules/sql_instance/main.tf line 127, in resource "google_sql_user" "users":
│  127:   password_policy = {
│ 
│ An argument named "password_policy" is not expected here.

this is not working ?

**Comment by edwardmedia** [comment]
@yeshwanth14 do you want to check [this](https://github.com/hashicorp/terraform-provider-google/issues/14702) out?

**Comment by edwardmedia** [comment]
@yeshwanth14 does [this](https://github.com/hashicorp/terraform-provider-google/issues/14723#issue-1726007455) work for you?

```tf
resource "google_sql_user" "users" {
    name = "issue14762"
    instance = google_sql_database_instance.main.name
    password = "changeme"
    password_policy {
        allowed_failed_attempts = 3
        password_expiration_duration = "86400s"
    }
}

resource "google_sql_database_instance" "main" {
  name             = "issue14762"
  database_version =  "MYSQL_8_0"

  settings {
    tier = "db-f1-micro"
  }
  deletion_protection = false
}
```

**Comment by yeshwanth14** [comment]
Hi,

no it didn't work same error
Error: Unsupported block type
│ 
│   on ../../modules/sql_instance/main.tf line 133, in resource "google_sql_user" "users1":
│  133:     password_policy {
│ 
│ Blocks of type "password_policy" are not expected here.

**Comment by yeshwanth14** [comment]
i'm sorry it's working fine, i haven't mentioned providers block in google_sql_user module.
Thank you!!!
