### ISSUE TITLE
Error 409 when trying to update the resource `google_compute_security_policy`

### ISSUE THREAD

**Issue by marcusricardoaguiar** [hashicorp/terraform-provider-google#14738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Version: 1.5.0

### Affected Resource(s)

* google_compute_security_policy

### Terraform Configuration Files

After making some changes on the resource `google_compute_security_policy` that triggers the resource recreation, it is trying to create the resource again first before deleting it. Then, since we already have the resource with the same name, it's crashing it.

```tf
resource "google_compute_security_policy" "backend_apis_cloud_armor" {
  name = "backend-api"
  provider = google-beta
  lifecycle {
    ignore_changes = [
      # This is being ignored because GCP is raising an issue when trying to set this value to PREMIUM tier
      # Layer 7 DDoS defense premium is currently not enabled.
      adaptive_protection_config[0].layer_7_ddos_defense_config[0].rule_visibility
    ]
  }

  rule {
	...
  }
  rule {
  	...
  }
  
  rule {
	...
  }

  rule {
	...
  }
}
```

### Panic Output

![p1](https://github.com/hashicorp/terraform-provider-google/assets/8216333/95eeb2f4-8dbe-4939-8f0c-a18c20114b14)

### Expected Behavior

I would like that GCP/Terraform was able to handle this situation and, in this case, remove the resource first before creating the new one.

### Actual Behavior

Since it tries to create before remove, it will crash when trying to create a resource with the same name as the existing one.

### Steps to Reproduce

Use an already existing `google_compute_security_policy` resource and make some changes on their terraform code. This might try to recreate the resource. However, you should have that already existing stuff.

**Comment by edwardmedia** [comment]
@marcusricardoaguiar changing on two fields, `name` and `project`, trigger replacement. It works fine with me after I renamed the resource. 

What did you do to trigger the recreation?

```
After making some changes on the resource google_compute_security_policy that triggers the resource recreation,
```

**Comment by marcusricardoaguiar** [comment]
> @marcusricardoaguiar changing on two fields, `name` and `project`, trigger replacement. It works fine with me after I renamed the resource.
> 
> What did you do to trigger the recreation?
> 
> ```
> After making some changes on the resource google_compute_security_policy that triggers the resource recreation,
> ```

Hey @edwardmedia , for instance, the last time it happened, it was a rule that I replaced. I changed the rule priority and the expressions. Then, it triggered the security policy recreation.

**Comment by marcusricardoaguiar** [comment]
> @marcusricardoaguiar changing on two fields, `name` and `project`, trigger replacement. It works fine with me after I renamed the resource.
> 
> What did you do to trigger the recreation?
> 
> ```
> After making some changes on the resource google_compute_security_policy that triggers the resource recreation,
> ```

However, I haven't changed the project nor the name.

**Comment by edwardmedia** [comment]
@marcusricardoaguiar can you detail the steps to repro, specific the way to trigger recreation?

**Comment by edwardmedia** [comment]
@marcusricardoaguiar Using below config, I tested by 1) initial apply and 2) uncomment the 3rd rule and apply, and did not hit the problem. Adding the 3rd rule did not trigger `recreate google_compute_security_policy`. Can you try my config? Also what version of the provider do you use?

```tf
resource "google_compute_security_policy" "policy" {
  name = "issue14738-1"
  //type = "CLOUD_ARMOR"
  type = "CLOUD_ARMOR_INTERNAL_SERVICE"

  rule {
    action   = "deny(403)"
    priority = "1000"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["9.9.9.0/24"]
      }
    }
    description = "Deny access to IPs in 9.9.9.0/24"
  }

  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "default rule"
  }
/*  uncomment for the 2nd apply
  rule {
    description = "Login rate limit"
    action      = "throttle"
    priority    = 28
    match {
      expr {
        expression = join(" ", [
          "request.method == 'POST'",
          "&& !has(request.headers['*****'])"
        ])
      }
    }

    rate_limit_options {
      conform_action = "allow"
      exceed_action = "deny(429)"

      enforce_on_key = ""

      rate_limit_threshold {
        count = 5
        interval_sec = 60
      }
    }
  }
  */
}


resource "google_compute_backend_service" "default" {
  name          = "backend-service"
  health_checks = [google_compute_http_health_check.default.id]

  security_policy = google_compute_security_policy.policy.self_link
}

resource "google_compute_http_health_check" "default" {
  name               = "health-check"
  request_path       = "/"
  check_interval_sec = 1
  timeout_sec        = 1
}
```

**Comment by marcusricardoaguiar** [comment]
> @marcusricardoaguiar Using below config, I tested by 1) initial apply and 2) uncomment the 3rd rule and apply, and did not hit the problem. Adding the 3rd rule did not trigger `recreate google_compute_security_policy`. Can you try my config? Also what version of the provider do you use?
> 
> ```terraform
> resource "google_compute_security_policy" "policy" {
>   name = "issue14738-1"
>   //type = "CLOUD_ARMOR"
>   type = "CLOUD_ARMOR_INTERNAL_SERVICE"
> 
>   rule {
>     action   = "deny(403)"
>     priority = "1000"
>     match {
>       versioned_expr = "SRC_IPS_V1"
>       config {
>         src_ip_ranges = ["9.9.9.0/24"]
>       }
>     }
>     description = "Deny access to IPs in 9.9.9.0/24"
>   }
> 
>   rule {
>     action   = "allow"
>     priority = "2147483647"
>     match {
>       versioned_expr = "SRC_IPS_V1"
>       config {
>         src_ip_ranges = ["*"]
>       }
>     }
>     description = "default rule"
>   }
> /*  uncomment for the 2nd apply
>   rule {
>     description = "Login rate limit"
>     action      = "throttle"
>     priority    = 28
>     match {
>       expr {
>         expression = join(" ", [
>           "request.method == 'POST'",
>           "&& !has(request.headers['*****'])"
>         ])
>       }
>     }
> 
>     rate_limit_options {
>       conform_action = "allow"
>       exceed_action = "deny(429)"
> 
>       enforce_on_key = ""
> 
>       rate_limit_threshold {
>         count = 5
>         interval_sec = 60
>       }
>     }
>   }
>   */
> }
> 
> 
> resource "google_compute_backend_service" "default" {
>   name          = "backend-service"
>   health_checks = [google_compute_http_health_check.default.id]
> 
>   security_policy = google_compute_security_policy.policy.self_link
> }
> 
> resource "google_compute_http_health_check" "default" {
>   name               = "health-check"
>   request_path       = "/"
>   check_interval_sec = 1
>   timeout_sec        = 1
> }
> ```

Hi @edwardmedia , I've been using google-beta provider version **4.66.0**. I've tried your suggestion and it worked as you mentioned. However, if we include the block `enforce_on_key_configs` it will trigger the policy recreation. Instead of applying your suggested new rule, I've just tried to add the rule below and it triggered the policy recreation:
```
  rule {
    description = "Login rate limit"
    action      = "throttle"
    priority    = 28
    match {
      expr {
        expression = join(" ", [
          "request.method == 'POST'",
          "&& !has(request.headers['******'])"
        ])
      }
    }

    rate_limit_options {
      conform_action = "allow"
      exceed_action = "deny(429)"

      enforce_on_key = ""

      **enforce_on_key_configs {
        enforce_on_key_type = "HTTP_HEADER"
        enforce_on_key_name = "****"
      }**

      rate_limit_threshold {
        count = 5
        interval_sec = 60
      }
    }
  }
```

**Comment by edwardmedia** [comment]
@marcusricardoaguiar oh, yes, that is right.  [enforce_on_key_configs](https://github.com/hashicorp/terraform-provider-google-beta/blob/2e550eaedd416797856191f40cdb11d4a8b512b2/google-beta/resource_compute_security_policy.go#L277) is only available in beta and it is a field that could trigger recreation.

**Comment by edwardmedia** [comment]
@marcusricardoaguiar any changes on that field will trigger recreation once it is GA. I do not have a solution off the top of my  head to your situation. 

@ryanyuan  what do you think?

**Comment by ryanyuan** [comment]
hey @edwardmedia, I reckon you wanted to tag @roaks3

**Comment by roaks3** [comment]
I've checked through the code, and nothing stood out as an obvious cause of the 409. The force_replacement behavior will call the resource's delete function and then its create function, which both appear to properly retrieve operations and wait for them to complete.

My suspicion at this point is that the resource is deleted and allowed to proceed to the create, but the resource's name is not yet available (`google_storage_bucket` has similar behavior where a name cannot be reused immediately after a bucket is deleted, and it caused problems with ForceNew: https://github.com/GoogleCloudPlatform/magic-modules/pull/7314).

**Comment by santoshpandit1** [comment]
I could see the main potential issue here is:
`google_compute_backend_service` has the security_policy attribute which is string instead of an object type of `google_compute_security_policy` ; 

We are creating two separate resources here and mapping it after the resources are created. This will have an issue because the proper dependency is missing.

**Comment by edwardmedia** [comment]
b/297932215

**Comment by jaksky** [comment]
@santoshpandit1 even adding dependency between LB BE to Security policy didn't help. Is there any resolution?

**Comment by maxi-cit** [comment]
Hello there, I just checked this has been available in beta for some time now so I am bumping it to GA.

Additionally they removed the force_new flag for the enforce_on_key_configs block so now it updates-in-place instead of recreate.

**Comment by roaks3** [comment]
Yea, looks like `enforce_on_key_configs` was fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/8165. That leaves only `name` and `project` that can trigger replacements, for which we were not able to observe this issue.

@maxi-cit we should be able to close with your change (or even close it now), and then let users raise a new issue if there are still problems with the replacement.
