### ISSUE TITLE
New resource "google_compute_network_endpoints" (and regiona/global variants)

### ISSUE THREAD

**Issue by hkundag** [hashicorp/terraform-provider-google#14730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

To add multiple endpoints to a compute NEG, you need to define a single `google_compute_network_endpoint` per endpoint. This is tractable with Terraform `for_each` if you have a lot of endpoints to add, but it will result in calling `compute.networkEndpointGroups.attachNetworkEndpoints` once per endpoint. This can be really slow as the number of endpoints increases - for reference, one Terraform invocation to add 199 endpoints to a single NEG took me around 35 minutes.

`compute.networkEndpointGroups.attachNetworkEndpoints` supports adding multiple endpoints, and it would be much more efficient/quick to make a single call with all the endpoints compared to one call per endpoint.

To do so, we can create a new resource (`google_compute_network_endpoints`) that accepts multiple endpoint blocks and makes a single call to create all of them at once. We could support updates by computing diffs between the old config and new, or by simply detaching all existing endpoints and then attaching the new ones.

As an out-of-scope aside, there is no data source that will make available the endpoints stored in a NEG. `google_compute_network_endpoints` could work as a data source to do so.

### New or Affected Resource(s)

* `google_compute_network_endpoints`
* `google_compute_global_network_endpoints`

`google_compute_region_network_endpoints` can possibly be omitted since there is no `google_compute_region_network_endpoint` resource.

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_compute_network_endpoints" "endpoints" {
  network_endpoint_group = google_compute_network_endpoint_group.neg.name
  endpoint {
    ip_address = "10.0.0.0"
    port = 80
  }
  
  endpoint {
    ip_address = "10.0.0.1"
    port = 80
  }
}

...
 
locals {
  ip_addresses = ["10.1.0.1", "10.1.0.2", ...]
}

resource "google_compute_network_endpoints" "endpoints" {
  network_endpoint_group = google_compute_network_endpoint_group.neg.name

  dynamic "endpoint" {
    for_each = local.ip_addresses

    ip_address = endpoint.value
    port = 80
  }
}
```

### References

* [resource_compute_network_endpoint.go](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_network_endpoint.go#L138)

**Comment by melinath** [comment]
> one Terraform invocation to add 199 endpoints to a single NEG took me around 35 minutes.

how long does it take after this change?

**Comment by hkundag** [comment]
199 endpoints took 11 seconds with the new resource (tried it out on Cloud Shell).

**Comment by melinath** [comment]
> 199 endpoints took 11 seconds with the new resource (tried it out on Cloud Shell).

🤯 nice!
