### ISSUE TITLE
replica_count - error setting to 1 (when read replicas is disabled)

### ISSUE THREAD

**Issue by Kikivsantos** [hashicorp/terraform-provider-google#14734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_redis_instance

### Expected Behavior

the resource shoud be created

### Actual Behavior

The documentation says that if I create a redis with Standard Tier and read replicas disabled, the only valid value is 1 (and the default is 1).

[replica_count](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance#replica_count) - (Optional) Optional. The number of replica nodes. The valid range for the Standard Tier with read replicas enabled is [1-5] and defaults to 2. If read replicas are not enabled for a Standard Tier instance, the only valid value is 1 and the default is 1. The valid value for basic tier is 0 and the default is also 0.

But, when trying to create the resource, the error below is shown.

Error: Error creating Instance: googleapi: Error 400: Setting replica count requires read-replicas-mode to be "READ_REPLICAS_ENABLED"
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Setting replica count requires read-replicas-mode to be "READ_REPLICAS_ENABLED"
Details:
[
  ***
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      ***
        "description": "Invalid value: 1",
        "field": "instance.replica_count"
      ***
    ]
  ***
]

What would be the correct? 0 (and the documentation is wrong) or 1 (and is problably an error in some updated version from the provider)?

### Steps to Reproduce

1. `terraform apply`

### References
[replica_count](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance#replica_count) - (Optional) Optional. The number of replica nodes. The valid range for the Standard Tier with read replicas enabled is [1-5] and defaults to 2. If read replicas are not enabled for a Standard Tier instance, the only valid value is 1 and the default is 1. The valid value for basic tier is 0 and the default is also 0.

* #0000

**Comment by edwardmedia** [comment]
@Kikivsantos can you share your config that has the problem?

**Comment by Kikivsantos** [comment]
Hi, Edwardmedia.

Here is the code:

**main.tf code:**

```


locals {
    project_name         = "${terraform.workspace}" == "master" ? "production" : "${terraform.workspace}"
    
}

# ------------------------------------------------------------------------
# REDIS CLUSTER
# ------------------------------------------------------------------------

resource "google_redis_instance" "default" {
    name                =  "rdi-${var.environment[terraform.workspace]}-${var.name}"
    display_name        =  "rdi-${var.environment[terraform.workspace]}-${var.name}"

    region              = var.region[terraform.workspace]
    authorized_network  = "projects/${var.network_id[terraform.workspace]}/global/networks/${var.network_vpc[terraform.workspace]}"
    connect_mode        = "PRIVATE_SERVICE_ACCESS"
    redis_version       = "${var.redis_version}"
    project             = var.project_id[terraform.workspace]
   
    tier                = var.cluster_config[terraform.workspace].tier
    replica_count       = var.cluster_config[terraform.workspace].replica_count
    memory_size_gb      = var.cluster_config[terraform.workspace].memory_size_gb
    read_replicas_mode  = var.cluster_config[terraform.workspace].read_replicas_mode

    lifecycle {
        precondition {
          condition     = (var.cluster_config[terraform.workspace].tier == "BASIC" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_DISABLED") || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA")
          error_message = "You cannot have a BASIC tier with READ_REPLICAS_ENABLED!!!!"
        }

        precondition {
          condition     = (var.cluster_config[terraform.workspace].tier == "BASIC" && var.cluster_config[terraform.workspace].replica_count == 0) || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA")
          error_message = "You cannot have BASIC tier with replica_count > 0 "
        }

        precondition {
          condition     = ((var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_ENABLED" && var.cluster_config[terraform.workspace].replica_count > 0 && var.cluster_config[terraform.workspace].memory_size_gb >= 5) || (var.cluster_config[terraform.workspace].tier == "BASIC" ) || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_DISABLED") || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_ENABLED" && var.cluster_config[terraform.workspace].replica_count == 0) )
          error_message = "memory_size_gb must be >=5 if read_replicas_mode = READ_REPLICAS_ENABLED and replica_count > 0!!!!"
        }

        precondition {
          condition     = ((var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_DISABLED" && var.cluster_config[terraform.workspace].replica_count == 1) || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_ENABLED" && var.cluster_config[terraform.workspace].replica_count >= 1 && var.cluster_config[terraform.workspace].replica_count <= 5) || (var.cluster_config[terraform.workspace].tier == "BASIC" && var.cluster_config[terraform.workspace].replica_count == 0 ) )
          error_message = "replica_count must be:\n * 1 if tier is STANDARD_HA and read_replicas_mode is READ_REPLICAS_DISABLED;\n * between 1-5 if tier is STANDARD_HA and read_replicas_mode is READ_REPLICAS_ENABLED;\n * 0 if tier is BASIC!!!!"
        }

    }
    maintenance_policy {
      weekly_maintenance_window {
        day             = "${var.weekly_maintenance_window.day}"
          start_time {
            hours       = "${var.weekly_maintenance_window.hours}"
            minutes     = "${var.weekly_maintenance_window.minutes}"
            seconds     =  try(var.weekly_maintenance_window.seconds, null)
            nanos       =  try(var.weekly_maintenance_window.nanos, null)
          }
        }
    }

    labels = {
      env               = "${terraform.workspace}"
      area-name         = try("${var.labels.area-name}", null)
      squad-name        = try("${var.labels.squad-name}", null)
      #repo-name         = try("${var.labels.repo-name}" , null)
      #terraform         = try("${var.labels.terraform}", null)
    }
    
}

# ------------------------------------------------------------------------
# DNS PRIMARY
# ------------------------------------------------------------------------

module "dns-record-primary" {
  source                = "git::internal_GIT_REPOSITORY.git"
  depends_on            = [google_redis_instance.default]
  
  dns_record            = "${google_redis_instance.default.name}"
  dns_zone_name         = "DNS_PREFIX-${terraform.workspace}"
  zone_project_id       = var.zone_project_id[terraform.workspace] 
  dns_record_type       = "${var.dns_record_type}"

  dns_record_ttl        = "${var.dns_record_ttl}"
  
  rrdatas               = ["${google_redis_instance.default.host}"]
} 

# ------------------------------------------------------------------------
# DNS SECONDARY
# ------------------------------------------------------------------------

module "dns-record-secondary" {
  count                 = google_redis_instance.default.read_replicas_mode == "READ_REPLICAS_ENABLED" ? 1 : 0
  source                = "git::internal_GIT_REPOSITORY.git"
  depends_on            = [google_redis_instance.default]
  dns_record            = "${google_redis_instance.default.name}-read"
  dns_zone_name         = "DNS_PREFIX-${terraform.workspace}"
  zone_project_id       = var.zone_project_id[terraform.workspace] 

  dns_record_type       = "${var.dns_record_type}"
  dns_record_ttl        = "${var.dns_record_ttl}"

  rrdatas               = ["${google_redis_instance.default.read_endpoint}"]
} 
```


**terragrunt.hcl (the code from the resource i´m trying to create)**

```


terraform {
  source                              = "${find_in_parent_folders("modules/redis")}///"
}

### não entendi o que esse path faz
include {
  path                                = find_in_parent_folders()
}

inputs    = {
  name                                = "kiki"
  redis_version                       = "REDIS_6_X"

  cluster_config = {
    master = {
      tier  = "STANDARD_HA"
      memory_size_gb = 1
      read_replicas_mode = "READ_REPLICAS_DISABLED"
      replica_count       = 1
    }
    staging = {
      tier  = "BASIC"
      memory_size_gb = 1
      read_replicas_mode = "READ_REPLICAS_DISABLED"
      replica_count       = 0
    }
    develop = {
      tier  = "STANDARD_HA"
      memory_size_gb = 5
      read_replicas_mode = "READ_REPLICAS_ENABLED"
      replica_count       = 1
    }
  }
    
  maintenance_policy = {
    weekly_maintenance_window = {
      prod   = {
        day = "SATURDAY"
        start_time = {
          hours   = 5
          minutes = 0
          seconds = 0
          nanos   = 0
        }
      }
      nonprod = {
        day = "SATURDAY"
        start_time = {
          hours   = 5
          minutes = 0
          seconds = 0
          nanos = 0
        }
      }
    }
  }

  labels = {
    area-name  = "AREA_NAME"
    squad-name = "SQUAD1"
  }

}
```

**Comment by edwardmedia** [comment]
@Kikivsantos below is the error you received which seems clear what went wrong. Using the following config, it works for me.

```
Error 400: Setting replica count requires read-replicas-mode to be "READ_REPLICAS_ENABLED"
```

```tf
resource "google_redis_instance" "cache" {
  name           = "issue14734"
  tier           = "STANDARD_HA"
  memory_size_gb = 5

  location_id             = "us-central1-a"
  alternative_location_id = "us-central1-f"

  authorized_network = data.google_compute_network.redis-network.id

  redis_version     = "REDIS_6_X"
  display_name      = "Terraform Test Instance"
  reserved_ip_range = "192.168.0.0/28"
  replica_count     = 5
  read_replicas_mode = "READ_REPLICAS_ENABLED"

  labels = {
    my_key    = "my_val"
    other_key = "other_val"
  }
}
```

Regarding the behavior of replica_count, we may see the official description [here](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances). 

Can you modify above config so I can repro your issue?

**Comment by Kikivsantos** [comment]
Hi, Edwardmedia.

Thank you for the answer.

I have done this too. And putting replica_count = 5 works, with read_replicas_mode = read_replicas_enabled.
But the error is when putting `tier  = "STANDARD_HA" + read_replicas_mode =  "READ_REPLICAS_DISABLED" + replica_count = 1.`

The error is:
```
"@type": "type.googleapis.com/google.rpc.BadRequest",
"fieldViolations": [
  ***
    "description": "Invalid value: 1",
    "field": "instance.replica_count"
  ***
]
```

But the doc says that the only valid value to replicaCount when tier = STANDARD_HA + and  READ_REPLICAS_DISABLED (read replicas are not enabled) is 1 (and this is the default value)

As showed in the doc you sand me: 
**replicaCount** | integerOptional. The number of replica nodes. The valid range for the Standard Tier with read replicas enabled is [1-5] and defaults to 2. **If read replicas are not enabled for a Standard Tier instance, the only valid value is 1 and the default is 1.** The valid value for basic tier is 0 and the default is also 0.

What is the value for replica_count when READ_REPLICAS_DISABLED ? The doc says its 1 (when tier is STANDARD_HA ). but it doesn´t work.

Thanks
Cristiana Santos

**Comment by edwardmedia** [comment]
@Kikivsantos I think once you choose READ_REPLICAS_DISABLED for read_replicas_mode, do not provide replica_count then. Below config works for me. 

```tf
resource "google_redis_instance" "cache" {
  name           = "issue14734"
  tier           = "STANDARD_HA"
  memory_size_gb = 5

  location_id             = "us-central1-a"
  alternative_location_id = "us-central1-f"

  authorized_network = data.google_compute_network.redis-network.id

  redis_version     = "REDIS_6_X"
  display_name      = "Terraform Test Instance"
  reserved_ip_range = "192.168.0.0/28"
  //replica_count     = 5
  //read_replicas_mode = "READ_REPLICAS_ENABLED"
  //replica_count     = 1
  read_replicas_mode = "READ_REPLICAS_DISABLED"

  labels = {
    my_key    = "my_val"
    other_key = "other_val"
  }
}
```

**Comment by Kikivsantos** [comment]
HI, Edwardmedia.

I juts created one cluster with the configuration below (and this worked just fine):
```
      tier  = "STANDARD_HA"
      memory_size_gb = 1
      read_replicas_mode = "READ_REPLICAS_DISABLED"
      replica_count       = 0
   
```

What I´m saying is that the documentation says that tha replica_count only valid value is 1 (when read_replicas_mode  is disabled & tier is STANDARD_HA). But putting replica_count = 1 gives an error (which shouldn´t happen).

The thing (and my question) is:
Is the documentation wrong or is the terraform provider code wrong? 

Not putting a value in the replica_count  will just receive the default value and will not undo the error in the documentation from the provider (what i thing it is - as the count zero works just fine) 

Thanks

**Comment by Kikivsantos** [comment]
Hi, Edwardmedia

With null it works (as fine as with replica_count = 0)

But my question is about the documentation which says that the only valid value is 1 to replica_count when STANDARD_HA +read_replicas_mode  disabled.

Should i ignore the doc and use the default value = null or 0?

Thanks

**Comment by Kikivsantos** [comment]
I need to know this because I´m using precondition to validate my plan  as shown below:

I just changed this code (so that the replica_count = 0 or = null works (but i need to know if this is right or if this will be changed to follow what the documentation says)

```

       precondition {
        condition     = ((var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_DISABLED" && var.cluster_config[terraform.workspace].replica_count == 0) || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_DISABLED" && var.cluster_config[terraform.workspace].replica_count == null) || (var.cluster_config[terraform.workspace].tier == "STANDARD_HA" && var.cluster_config[terraform.workspace].read_replicas_mode == "READ_REPLICAS_ENABLED" && var.cluster_config[terraform.workspace].replica_count >= 1 && var.cluster_config[terraform.workspace].replica_count <= 5) || (var.cluster_config[terraform.workspace].tier == "BASIC" && var.cluster_config[terraform.workspace].replica_count == 0 ) )
        error_message = "replica_count must be:\n * 0 or null if tier is STANDARD_HA and read_replicas_mode is READ_REPLICAS_DISABLED;\n * between 1-5 if tier is STANDARD_HA and read_replicas_mode is READ_REPLICAS_ENABLED;\n * 0 if tier is BASIC!!!!"
       }
```

**Comment by edwardmedia** [comment]
@Kikivsantos yes. Or you may file an issue against the api to ask for clarification in its doc. By now, the provider does not have much control over it. Does this make sense? 

```
Should i ignore the doc and use the default value = null or 0?
```

**Comment by edwardmedia** [comment]
@Kikivsantos Cool, you may reach out Google account manager or you may use [resources](https://github.com/hashicorp/terraform-provider-google/wiki) on this repo to see what you can do. 

For now, I think we are good within the provider and I am closing the issue accordingly
