### ISSUE TITLE
Reserve external IPv6 google_compute_address

### ISSUE THREAD

**Issue by jeremiahlee** [hashicorp/terraform-provider-google#14748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for reserving external regional IPv6 address by supporting IP version and endpoint type in [google_compute_address](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address). Currently, IP version is only supported on [google_compute_global_address](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address).

The idea is to match `--ipVersion=IPV6 --endpoint-type=VM --region=(region)` and `--ipVersion=IPV6 --endpoint-type=NETLB --region=(region)` of [gcloud](https://cloud.google.com/sdk/gcloud/reference/compute/addresses/create).

[GCP documentation on static external IP addresses](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#external-ip) says:

- a non-global IPv6 compute address should be used "for VMs and supported regional load balancers"
- a global IPv6 compute address should be used "for global load balancers" only

From the [REST Resource: addresses documentation](https://cloud.google.com/compute/docs/reference/rest/beta/addresses): 

- `"ipVersion": "IPV6"`
- `"purpose": "GCE_ENDPOINT"`
- `"ipv6EndpointType": "VM"` or `"ipv6EndpointType": "NETLB"` with `"region"`

For reference, here is a comparison of the different gcloud commands:

IPv6 for VMs:
`gcloud compute addresses create NAME --ip-version=IPV6 --region=europe-north1 --endpoint-type=VM --project=yada`

IPv6 for supported regional load balancers:
`gcloud compute addresses create NAME --ip-version=IPV6 --region=europe-north1 --endpoint-type=NETLB --project=yada`

IPv6 for global load balancers:
`gcloud compute addresses create NAME --ip-version=IPV6 --region=europe-north1 --endpoint-type=NETLB --project=yada`

IPv4 for VMs and regional load balancers:
`gcloud compute addresses create NAME --region=europe-north1 --project=yada`

IPv4 for global load balancers:
`gcloud compute addresses create NAME --global --project=yada`

### New or Affected Resource(s)

* google_compute_address

### Potential Terraform Configuration

I'm fairly new to Terraform and defer to you on this.

### References

* #5027 seems like it might have been closed correctly at the time, but incorrectly today

**Comment by melinath** [comment]
looks like this is about adding an ip_version field to match the google_compute_global_address field

**Comment by LucaPrete** [comment]
@melinath I think this is done already

**Comment by melinath** [comment]
It looks like this was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8482
