### ISSUE TITLE
Add Terraform support for Cloud Composer's High Resilience Feature

### ISSUE THREAD

**Issue by Khaledmohamedrefaat** [hashicorp/terraform-provider-google#14751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add Terraform support for Cloud Composer's High Resilience Feature

### New or Affected Resource(s)
google_composer_environment
### References
#0000

**Comment by Khaledmohamedrefaat** [comment]
I wish to work on this item.

**Comment by melinath** [comment]
@Khaledmohamedrefaat could you give an example of what the change would be to implement support for this feature? Is it just a new field on the resource?

**Comment by melinath** [comment]
looks like a new field, and this is a handwritten resource

**Comment by melinath** [comment]
It looks like this should already be supported in Terraform: https://cloud.google.com/composer/docs/composer-2/create-environments#terraform_4

**Comment by melinath** [comment]
It looks like despite being in the cloud.google.com docs, the resilience_mode field does not actually exist in the provider 😂

**Comment by Khaledmohamedrefaat** [comment]
Hi @melinath, resilience_mode field has just been added to composer Go API, and we are submitting this pull request to make terraform support the use of this new field.
