### ISSUE TITLE
org_policy_policy has fields "enforce", "allowall" and "denyall" incorrectly defined as strings

### ISSUE THREAD

**Issue by DaveButland** [hashicorp/terraform-provider-google#14766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.66.0
+ provider registry.terraform.io/hashicorp/google-beta v4.66.0
```

### Affected Resource(s)

* google_org_policy_policy

### Terraform Configuration Files

```tf

variable "domain" {
  type = string
}

locals {
  org_id = data.google_organization.organization.org_id
}

data "google_organization" "organization" {
  domain = var.domain
}

resource "google_org_policy_policy" "test" {
  name   = "organizations/${local.org_id}/policies/storage.publicAccessPrevention"
  parent = "organizations/${local.org_id}"

  spec {
    inherit_from_parent = false

    rules {
      enforce = true
    }
  }
}
```

### Expected Behavior

Organization policy gets created with enforce set to true

### Actual Behavior

Error: Error creating Policy: googleapi: Error 400: A PolicyRule must be non-empty and have one of the fields under kind set.

### Steps to Reproduce

1.  create tfvars file with domain variable
2. `terraform init`
3. `terrform apply`

### Important Factoids

The fields enforce, allowall and denyall are defined as strings in terraform but the [Google REST API](https://cloud.google.com/orgpolicy/docs/reference/rest/v2/folders.policies#policyrule) requires boolean values. 

### References

* [OrgPolicyPolicySpecRulesSchema](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_org_policy_policy.go#L120)
* [Google REST API](https://cloud.google.com/orgpolicy/docs/reference/rest/v2/folders.policies#Policy.PolicyRule)
* #11473 - similar issue confusing boolean with string because API requires boolean but terraform requires upper case string.

**Comment by edwardmedia** [comment]
@DaveButland using below config, it is fine with me. The error you received seems to be on different things. Can you try mine?

```tf
resource "google_org_policy_policy" "primary" {
  name   = "projects/${google_project.basic.name}/policies/gcp.resourceLocations"
  parent = "projects/${google_project.basic.name}"

  spec {
    rules {
      condition {
        description = "A sample condition for the policy"
        expression  = "resource.matchLabels('labelKeys/123', 'labelValues/345')"
        location    = "sample-location.log"
        title       = "sample-condition"
      }

      values {
        allowed_values = ["projects/allowed-project"]
        denied_values  = ["projects/denied-project"]
      }
    }

    rules {
      allow_all = true
    }
  }
}
```

**Comment by DaveButland** [comment]
I just tried that and got the same error but I just noticed that the terraform plan translated the boolean into a string.

```
+ resource "google_org_policy_policy" "primary" {
      + id     = (known after apply)
      + name   = "projects/xxx/policies/gcp.resourceLocations"
      + parent = "projects/xxx"

      + spec {
          + etag        = (known after apply)
          + update_time = (known after apply)

          + rules {
              + condition {
                  + description = "A sample condition for the policy"
                  + expression  = "resource.matchLabels('labelKeys/123', 'labelValues/345')"
                  + location    = "sample-location.log"
                  + title       = "sample-condition"
                }
              + values {
                  + allowed_values = [
                      + "projects/allowed-project",
                    ]
                  + denied_values  = [
                      + "projects/denied-project",
                    ]
                }
            }
          + rules {
              + allow_all = "true"
            }
        }
    }
```

The log file output is interesting; it is missing the second rule values (on both mine and yours). 

```
    "request": {
      "policy": {
        "spec": {
          "inheritFromParent": false,
          "reset": false,
          "rules": [
            {
              "condition": {
                "title": "sample-condition",
                "description": "A sample condition for the policy",
                "location": "sample-location.log",
                "expression": "resource.matchLabels('labelKeys/123', 'labelValues/345')"
              },
              "values": {
                "allowedValues": [
                  "projects/allowed-project"
                ],
                "deniedValues": [
                  "projects/denied-project"
                ]
              }
            },
            {}
          ]
        },
        "name": "projects/xxx/policies/gcp.resourceLocations"
      },
```

What versions of terraform / provider are you using? I've just noticed I posted the wrong values above, I took them from my local rather than the pipeline. 

Should have been:
```
Terraform v1.4.4
on linux_amd64
provider registry.terraform.io/hashicorp/google v4.61.0
provider registry.terraform.io/hashicorp/google-beta v4.61.0
```

This code works fine if you change the true to "TRUE". I'm assuming the bug is in the translation of the boolean to string or string to uppercase. Would be much easier if the interface was just defined as boolean as in the "inherit_from_parent" field.

**Comment by edwardmedia** [comment]
@DaveButland Can you share your debug log?

**Comment by DaveButland** [comment]
@edwardmedia I have run your config and got the same error. I did extract the debug statements but I also ran it with the very latest providers and it worked. I guess somewhere between 4.61 and 4.67 it was fixed. That solves my problem as I can remove my workaround once I've updated my pipelines. Apologies for not checking the latest driver first.

**Comment by edwardmedia** [comment]
Glad you have identify where the problem is @DaveButland
