### ISSUE TITLE
Add support of `connectedProjects` in `google_vpc_access_connector`

### ISSUE THREAD

**Issue by jingyih** [hashicorp/terraform-provider-google#14760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version

$ terraform -v
Terraform v1.4.0-dev
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.66.0
+ provider registry.terraform.io/hashicorp/google-beta v4.66.0

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files (if applicable)

```tf
provider "google-beta" {
  project = xxx
  region  = "us-west1"
  zone    = "us-west1-a"
}

resource "google_cloud_run_v2_service" "default" {
  name     = "cloudrun-service"
  project  = xxx
  location = "us-west1"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
    vpc_access{
      connector = google_vpc_access_connector.connector.id
      egress = "ALL_TRAFFIC"
    }
  }
}

resource "google_vpc_access_connector" "connector" {
  name          = "run-vpc"
  project       = xxx
  subnet {
    name = google_compute_subnetwork.custom_test.name
  }
  machine_type = "e2-standard-4"
  min_instances = 2
  max_instances = 3
  region        = "us-west1"
}
resource "google_compute_subnetwork" "custom_test" {
  name          = "run-subnetwork"
  project       = xxx
  ip_cidr_range = "10.2.0.0/28"
  region        = "us-west1"
  network       = google_compute_network.custom_test.id
}
resource "google_compute_network" "custom_test" {
  name                    = "run-network"
  project                 = xxx
```

### Issue Description

The GCP API has field `connectedProjects`, but it is missing from the Terraform resource.

```
$ gcurl https://vpcaccess.googleapis.com/v1/projects/xxx/locations/us-west1/connectors/run-vpc
{
  "name": "projects/xxx/locations/us-west1/connectors/run-vpc",
  "state": "READY",
  "minThroughput": 200,
  "maxThroughput": 300,
  "connectedProjects": [
    "xxx"
  ],
  "subnet": {
    "name": "run-subnetwork",
    "projectId": "xxx"
  },
  "machineType": "e2-standard-4",
  "minInstances": 2,
  "maxInstances": 3
}
```

```
$ terraform state show google_vpc_access_connector.connector
# google_vpc_access_connector.connector:
resource "google_vpc_access_connector" "connector" {
    id             = "projects/xxx/locations/us-west1/connectors/run-vpc"
    machine_type   = "e2-standard-4"
    max_instances  = 3
    max_throughput = 300
    min_instances  = 2
    min_throughput = 200
    name           = "run-vpc"
    project        = "xxx"
    region         = "us-west1"
    self_link      = "projects/xxx/locations/us-west1/connectors/run-vpc"
    state          = "READY"

    subnet {
        name       = "run-subnetwork"
        project_id = "xxx"
    }
}
```

**Comment by edwardmedia** [comment]
`connectedProjects`  available in the https://cloud.google.com/vpc/docs/reference/vpcaccess/rest/v1/projects.locations.connectors

Change to enhancement
