### ISSUE TITLE
compute_instance: support confidentialInstanceType (with variant "SEV_SNP")

### ISSUE THREAD

**Issue by malt3** [hashicorp/terraform-provider-google#14768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP supports different confidential instance types (including `SEV` and `SEV_SNP`). Those cannot yet be selected via terraform. The `compute_instance` resource [only has a boolean](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#confidential_instance_config) to enable confidential computing.
This setting is [part of the sdk](https://pkg.go.dev/google.golang.org/api/compute/v0.alpha#ConfidentialInstanceConfig).

### New or Affected Resource(s)

* google_compute_instance
* google_compute_instance_template

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n2d-standard-4"
  zone         = "us-central1-a"

  tags = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
      labels = {
        my_label = "value"
      }
    }
  }

  network_interface {
    network = "default"
  }

  confidential_instance_config {
    enable_confidential_compute = true
    confidential_instance_type = "SEV_SNP"
  }

}
```

### References

n/a

b/312697065

**Comment by rileykarson** [comment]
Note: probably impacts other resources (google_compute_instance_from_template, for example)
