### ISSUE TITLE
Add support of `Fleet` field in resource_container_cluster

### ISSUE THREAD

**Issue by shumiao** [hashicorp/terraform-provider-google#14761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The GCP API has field `Fleet`, but it is missing from the Terraform resource.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "cluster" {
  provider = google-beta
  name     = local.prefix

  fleet {
    project = "${var.project}"
  }
```

b/299600918

**Comment by melinath** [comment]
This was completed in https://github.com/GoogleCloudPlatform/magic-modules/pull/9385 - https://github.com/hashicorp/terraform-provider-google/issues/16795 tracks a bug in the implementation.

**Comment by goobysnack** [comment]
I think the problem here is the fleet block creates the registration in the region path of the api, not global.  Features are created as global because the fleet itself is a global construct.

```
    fleet {
        membership     = "//gkehub.googleapis.com/projects/myproject/locations/us-east1/memberships/use1-cluster-1"
        pre_registered = false
        project        = "myproject"
    }
 ```
 
 should be:
 
 ```
     fleet {
        membership     = "//gkehub.googleapis.com/projects/myproject/locations/global/memberships/use1-cluster-1"
        pre_registered = false
        project        = "myproject"
    }
 ```
