### ISSUE TITLE
Postgres SQL Database Instance deployment super slow?

### ISSUE THREAD

**Issue by LiamLogan1996** [hashicorp/terraform-provider-google#14770]
I am in the process of building out a terraform module which is used to deploy a postgres instance in GCP. I am using following resource block **_google_sql_database_instance_** to deploy postgres.

I have noticed that during the creation of the actual Postgres instance it takes around 15-20 minutes. 

Is there a particular reason for this? Is this a terraform issue or a Google Cloud API issue for Cloud SQL (https://cloud.google.com/sql/docs/mysql/admin-api/rest/) 

This causes long development times due to having to wait for the instance to be created to be able to run tests against it.

**Comment by edwardmedia** [comment]
@LiamLogan1996 taking 15-20 minutes is normal for this resource. You may see default Timeouts are given [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#timeouts) . Comparing other resources, they are long but are expected. That's all done at the api level. There is no much the provider can do.
