### ISSUE TITLE
API Gateway Config with OpenApi.yaml cannot be applied when used with environment variables

### ISSUE THREAD

**Issue by Baroshem** [hashicorp/terraform-provider-google#14781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Hey There!

I have been using terraform with GCS for some time already and it has proven to be working quite well! Thanks for the amazing work!

I recently tried to configure the Google API Gateway with OpenApi.yaml file. The [default scenario](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/api_gateway_api_config) with static file works correctly and as expected but when I tried to have one file that would be populated with environment variables I am experiencing an error.

I am not sure if I am using it in the wrong way or if there is a bug of some sort so I would appreciate your help :)

Error in the console after running `apply`:

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for google_api_gateway_api_config.api_cfg to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/google-beta" produced an invalid new value for
│ .openapi_documents[0].document[0].contents:

// config planned vs config applied

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

`api-gateway-config.yaml` file:

```yaml
# openapi2-functions.yaml
swagger: "2.0"
info:
  title: API Gateway
  description: API which provides set of methods
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /custom-path:
    get:
      operationId: CustomController_getData
      summary: Get data
      x-google-backend:
        address: "${ CLOUD_RUN_URL }"
      responses:
        "200":
          description: Data has been successfully fetched
        "400":
          description: Bad request.
        "401":
          description: User unauthorized
        "403":
          description: User does not have permission to perform this operation.
        "500":
          description: Internal server error.
```

`main.tf` file:

```tf
resource "local_file" "api_gateway_config" {
  content = templatefile("${path.module}/configs/api-gateway-config.yaml", {
    CLOUD_RUN_URL = var.CLOUD_RUN_URL
  })
  filename = "${path.module}/configs/api-gateway-config.yaml"
}

resource "google_api_gateway_api_config" "api_cfg" {
  provider             = google-beta
  api                  = google_api_gateway_api.api_gw.api_id
  api_config_id_prefix = local.api_config_id_prefix
  display_name         = "The Config - ${var.environment}"
  project              = var.project
  gateway_config {
    backend_config {
      google_service_account = data.terraform_remote_state.gcs.outputs.shared_service_account_email
    }
  }

  openapi_documents {
    document {
      path     = "${path.module}/configs/api-gateway-config.yaml"
      contents = filebase64(local_file.api_gateway_config.filename)
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### Terraform Version

```
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.31.0
+ provider registry.terraform.io/hashicorp/google-beta v4.50.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Affected Resource(s)

* google_api_gateway_api_config

### Debug Output

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for google_api_gateway_api_config.api_cfg to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/google-beta" produced an invalid new value for
│ .openapi_documents[0].document[0].contents:

// config planned vs config applied

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behavior

The gateway config should be applied and there should be no error displayed

### Actual Behavior

The apply fails and there is an error in the console

### Steps to Reproduce

1. `terraform plan` // works correctly without errors
2. `terraform apply` // preplan work but fails on apply
3. See error

**Comment by edwardmedia** [comment]
@Baroshem not sure why you want to use `local_file`. What value do you expect below? Have you tried the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/api_gateway_api_config#example-usage---apigateway-api-config-basic) to see if it works for you?

```
contents = filebase64(local_file.api_gateway_config.filename)
```

**Comment by Baroshem** [comment]
@edwardmedia I tried to standarize the config file to use environment variables. It is possible to use the environment variable in TF to select different config file per environment but these configs are more or less the same so having three of them is difficult to maintain. 

Because of that I wanted to use the local file to create file with environment variables to have only one config file that would be modified accordingly to the environment.

I tried the basic example from the docs but it supports reading the whole file without env variables.

**Comment by Baroshem** [comment]
@edwardmedia 

I have three vars files:

```
1. dev.tfvars
2. stage.tfvars
3. prod.tfvars
```

I am then using the command `terraform apply -var-file=${{ inputs.environment }}.tfvars -auto-approve` in GitHub actions to deploy changes on certain environment.

I also have one api-gateway-config.yaml file:

```yaml
# openapi2-functions.yaml
swagger: "2.0"
info:
  title: API Gateway
  description: API which provides set of methods
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /custom-path:
    get:
      operationId: CustomController_getData
      summary: Get data
      x-google-backend:
        address: "${ CLOUD_RUN_URL }"
      responses:
        "200":
          description: Data has been successfully fetched
        "400":
          description: Bad request.
        "401":
          description: User unauthorized
        "403":
          description: User does not have permission to perform this operation.
        "500":
          description: Internal server error.
```

This file contains variables that I am then passing to a template local file:

```tf
resource "local_file" "api_gateway_config" {
  content = templatefile("${path.module}/configs/api-gateway-config.yaml", {
    CLOUD_RUN_URL = var.CLOUD_RUN_URL
  })
  filename = "${path.module}/configs/api-gateway-config.yaml"
}

resource "google_api_gateway_api_config" "api_cfg" {
  ... // configuration that is not relevant for this bug

  openapi_documents {
    document {
      path     = "${path.module}/configs/api-gateway-config.yaml"
      contents = filebase64(local_file.api_gateway_config.filename)
    }
  }
}
```

And then when I run `terraform plan` it works correctly without errors but later on when I try to run `terraform apply` on preplan it works but then fails on the actual apply with the following error:

```
```

**Comment by Baroshem** [comment]
@edwardmedia I dont think that I understand.

The error says clearly that it is an issue in the provider. What is there from my side to fix? There is nothing I can actually do to fix it. As it should work this way without errors (as I mentioned terraform plan and preplan works so it is an issue with the provider for the actual apply)

**Comment by edwardmedia** [comment]
@Baroshem sorry I may have not made myself clear. What I meant was you need to make sure all settings are the same in plan and apply. `Error: Provider produced inconsistent final plan` likely was complaining about the diff between plan and apply.

I have tested the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/api_gateway_api_config#example-usage---apigateway-api-config-basic) and did not found an issue. 

Your [config](https://github.com/hashicorp/terraform-provider-google/issues/14781#issue-1735804732) contains variables. For me, I can only guess what they are. Could you provide a config by replacing them with real data so I can run directly?

**Comment by edwardmedia** [comment]
@Baroshem does [this](https://github.com/hashicorp/terraform-provider-google/issues/14781#issuecomment-1578828097) make sense? Is there anything more I can help?

**Comment by edwardmedia** [comment]
@Baroshem closing this assume it is no longer an issue
