### ISSUE TITLE
resource/google_compute_subnetwork: Terraform state leaks on interrupt

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-google#14790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
% ./terraform --version
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.53.1
+ provider registry.terraform.io/hashicorp/google-beta v4.53.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Affected Resource(s)

* google_compute_network

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      version = "4.53.1"
    }
    google-beta = {
      version = "4.53.1"
    }
    null = {
      version = "3.2.1"
    }
  }
}

provider "google" {
  credentials = "${file("serviceaccount.json")}"
  project     = "project-foo"
  region      = "europe-west1"
}

//=====================================================================
//= Networks
//=====================================================================

resource "google_compute_network" "network" {
  name                    = "shoot--local--foo"
  auto_create_subnetworks = "false"

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }
}

resource "google_compute_subnetwork" "subnetwork-nodes" {
  name          = "shoot--local--foo-nodes"
  ip_cidr_range = "10.250.0.0/24"
  network       = google_compute_network.network.name
  region        = "europe-west1"

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }
}

//=====================================================================
//= Output variables
//=====================================================================

output "vpc_name" {
  value = google_compute_network.network.name
}
```

### Expected Behavior

terraform/terraform-provider-gcp to be resilient to interrupts and to do not leak terraform state when interrupt is received. We run terraform in quite automated manner without human interaction. Everytime state leaks, a human operator has to analyse it and fix it manually.

### Actual Behavior

terraform/terraform-provider-gcp leaks state when first terraform apply (that creates the resources) is interrupted.

### Steps to Reproduce

1. `terraform init`

2. `terraform apply -auto-approve`
When it starts creating the subnet, then interrupt:
```
google_compute_network.network: Creating...
google_compute_network.network: Still creating... [10s elapsed]
google_compute_network.network: Creation complete after 12s [id=projects/project-foo/global/networks/shoot--local--foo]
google_compute_subnetwork.subnetwork-nodes: Creating...
^CStopping operation...

Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

╷
│ Error: execution halted
│
│
╵
╷
│ Error: execution halted
│
│
╵
╷
│ Error: Error waiting to create Subnetwork: Error waiting for Creating Subnetwork: error while retrieving operation: unable to finish polling, context has been cancelled
│
│   with google_compute_subnetwork.subnetwork-nodes,
│   on main.tf line 36, in resource "google_compute_subnetwork" "subnetwork-nodes":
│   36: resource "google_compute_subnetwork" "subnetwork-nodes" {
│
```

Note that the network creation fails with `Error: Error waiting to create Subnetwork: Error waiting for Creating Subnetwork: error while retrieving operation: unable to finish polling, context has been cancelled`. The subnet is created in GCP but not saved in the terraform state.
Any subsequent `terraform apply -auto-approve`, it fails with reason that the firewall rules already exists:
```
google_compute_subnetwork.subnetwork-nodes: Creating...
╷
│ Error: Error creating Subnetwork: googleapi: Error 409: The resource 'projects/project-foo/regions/europe-west1/subnetworks/shoot--local--foo-nodes' already exists, alreadyExists
│
│   with google_compute_subnetwork.subnetwork-nodes,
│   on main.tf line 36, in resource "google_compute_subnetwork" "subnetwork-nodes":
│   36: resource "google_compute_subnetwork" "subnetwork-nodes" {
│
```

### References

* https://github.com/hashicorp/terraform-provider-google/issues/14789
* https://github.com/hashicorp/terraform-provider-google/issues/14782

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/14782
