### ISSUE TITLE
Tag Key is recreated on every execution when parent is set to project/PROJECT-ID

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#14792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.9

### Affected Resource(s)

* google_tags_tag_key

### Terraform Configuration Files

```tf
resource "google_tags_tag_key" "key" {
  parent = "project/<PROJECT_ID>"
  short_name = "keyname"
  description = "For keyname resources."
}
```

### Debug Output
```
  # google_tags_tag_key.basic_key must be replaced
-/+ resource "google_tags_tag_key" "basic_key" {
      ~ create_time     = "2023-06-02T14:19:26.215853Z" -> (known after apply)
      ~ id              = "tagKeys/282456517940498" -> (known after apply)
      ~ name            = "282456517940498" -> (known after apply)
      ~ namespaced_name = "ci-network-47gu/tagkey" -> (known after apply)
      ~ parent          = "projects/60673181905" -> "projects/ci-network-47gu" # forces replacement
      ~ update_time     = "2023-06-02T14:19:26.215853Z" -> (known after apply)
        # (4 unchanged attributes hidden)
    }
```

### Expected Behavior
Tag key should not be recreated

### Actual Behavior
Tag key is recreated on every execution when project ID is provided instead of project number.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@imrannayer can you try `project/<project_number>` in your config instead? Looks like the api has changed its behavior. I will update the document accordingly

```tf
resource "google_tags_tag_key" "key" {
  parent = "project/60673181905"
  short_name = "keyname"
  description = "For keyname resources."
}
```

**Comment by imrannayer** [comment]
Project ID and Project number both work fine. But when I provide project ID resource is recreated on every execution.

**Comment by imrannayer** [comment]
@edwardmedia r we going to fix it or stop supporting project id?
