### ISSUE TITLE
Add support for gke_restore_backup_plan

### ISSUE THREAD

**Issue by ego93** [hashicorp/terraform-provider-google#14796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now it is possible to create a GKE backup plan in Terraform with [google_gke_backup_backup_plan](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_backup_backup_plan) however you cannot do the same with a restore plan.

I would like to have the same option as gke_restore_backup_plan.

### New or Affected Resource(s)

* google_gke_restore_backup_plan

### Potential Terraform Configuration

```tf
resource "google_gke_restore_backup_plan" "basic" {
  name = "basic-restore-plan"
  backup_plan = google_gke_backup_backup_plan.basic.id
  cluster = google_container_cluster.primary.id
  location = "us-central1"
  project = "my-project"

  restore_config {
    namespaced_resource_restore_mode = delete-and-restore
    cluster_resource_conflict_policy = use-existing-version
    all_namespaces = true
  }
}
```

### References

Ref gcloud cli https://cloud.google.com/sdk/gcloud/reference/beta/container/backup-restore/restore-plans/create

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/12634
