### ISSUE TITLE
google_iam_workload_identity_pool  and google_iam_workload_identity_pool_provder objects are not recreateable

### ISSUE THREAD

**Issue by matihost** [hashicorp/terraform-provider-google#14805]
google_iam_workload_identity_pool  and google_iam_workload_identity_pool_provder objects are not recreateable.

Attempt to delete - marks both as deleted - and removes them form TF state normally.

Attempt to undelete them from GCP Console and import both to the state:
```
terragrunt import google_iam_workload_identity_pool.pool projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool
terragrunt import google_iam_workload_identity_pool_provider.provider projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-oidc-provider
```
went ok, BUT
it sets project field for both resource to project number, not id.
```
      ~ project                   = "137506669283" -> "some_project" # forces replacement
```

So then trying to reconcile - TF sees that project field is incorrect so it forces replacement - which deletes the pool and provider successfully but creation ends with already exist error.. and loop repeats :
```
  # google_iam_workload_identity_pool.pool must be replaced
-/+ resource "google_iam_workload_identity_pool" "pool" {
      ~ id                        = "projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool" -> (known after apply)
      ~ name                      = "projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool" -> (known after apply)
      ~ project                   = "137506669283" -> "some_project" # forces replacement
      ~ state                     = "ACTIVE" -> (known after apply)
        # (4 unchanged attributes hidden)

      - timeouts {}
    }

  # google_iam_workload_identity_pool_provider.provider must be replaced
-/+ resource "google_iam_workload_identity_pool_provider" "provider" {
      ~ id                                 = "projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-oidc-provider" -> (known after apply)
      ~ name                               = "projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool/providers/gh-oidc-provider" -> (known after apply)
      ~ project                            = "137506669283" -> "some_project" # forces replacement
      ~ state                              = "ACTIVE" -> (known after apply)
        # (6 unchanged attributes hidden)

      ~ oidc {
          - allowed_audiences = [] -> null
            # (1 unchanged attribute hidden)
        }

      - timeouts {}
    }
```
and
output:
```
google_iam_workload_identity_pool.pool: Destroying... [id=projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool]
google_iam_workload_identity_pool.pool: Still destroying... [id=projects/137506669283/locations/global/workloadIdentityPools/gh-identity-pool, 10s elapsed]
google_iam_workload_identity_pool.pool: Destruction complete after 11s
google_iam_workload_identity_pool.pool: Creating...
╷
│ Error: Error creating WorkloadIdentityPool: googleapi: Error 409: Requested entity already exists
```

Workaound: Just change the pool and provider id ... or modify state file manually.

**Comment by edwardmedia** [comment]
@matihost what version of the provider do you have? Can you try the latest to see if you can repro?

**Comment by slevenick** [comment]
Unfortunately I believe this is a design pattern on the API side that doesn't mesh well with Terraform. The resource stays around in the API with a "disabled" flag instead of fully deleting. It's a form of soft_delete. This is similar to how the google_sql_instance resource works, where names can't be reused within a certain period of time

**Comment by matihost** [comment]
ok, what about valid importing import project number into state instead of project id ?

so that only manualy modification of the state can avoid recurrent cycle of delete/failed creation of existing entry?

**Comment by lox** [comment]
I've run into this too, surely it should be possible to restore the deleted resources in google cloud and import them? 

Are you able to clarify why the numeric project id is being used that is triggering replacement @slevenick?

```
     ~ project                   = "137506669283" -> "some_project" # forces replacement
```

**Comment by lox** [comment]
I verified that I could import the Identity Pool and then set project to the numeric ID and terraform would re-use the resource, unfortunately I wasn't able to figure out how to restore / undelete the Identity Pool Provider.

**Comment by slevenick** [comment]
> I've run into this too, surely it should be possible to restore the deleted resources in google cloud and import them?
> 
> Are you able to clarify why the numeric project id is being used that is triggering replacement @slevenick?
> 
> ```
>      ~ project                   = "137506669283" -> "some_project" # forces replacement
> ```

Yeah, restoring manually and importing should work. As far as why the project # is used, that's probably coming from the import statement? If you use a project ID instead does it fix the problem?
