### ISSUE TITLE
Add TTL policy for Datastore

### ISSUE THREAD

**Issue by remko** [hashicorp/terraform-provider-google#14806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Datastore supports [TTL policies on entities](https://cloud.google.com/datastore/docs/ttl). I want to be able to set these TTL policies in terraform.

A similar feature for Firestore [has recently been implemented](https://github.com/hashicorp/terraform-provider-google/issues/12151).

### New or Affected Resource(s)

A new resource such as `google_datastore_ttl_policy`

### Potential Terraform Configuration

    resource "google_datastore_ttl_policy" "default" {
      kind = "MyKind"
      timestamp_property = "expireAt"
    }

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

- Datastore documentation: https://cloud.google.com/datastore/docs/ttl
- Equivalent Terraform resource for Firestore: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field#ttl_config (PR: https://github.com/hashicorp/terraform-provider-google/issues/12151)

**Comment by rileykarson** [comment]
Hmm- there doesn't seem to be an admin-level REST API that makes sense for this. Is this configured under these methods? https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects

**Comment by lrnq** [comment]
I submitted a feature request to `pulumi-gcp` at https://github.com/pulumi/pulumi-gcp/issues/1215, where it was mentioned that they are waiting on this particular issue to be resolved.

In response to your query, @rileykarson, AFAICT, the feature isn't configured under any of the methods listed under that link. 

It would be a great feature to include though, so hopefully we can figure something out. A newer issue https://github.com/hashicorp/terraform-provider-google/issues/15781 seem to request the feature as well.

**Comment by rileykarson** [comment]
Judging by the instructions in https://cloud.google.com/datastore/docs/ttl#gcloud and some manual testing, the resource to configure this for datastore is actually just https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field! I manually created a project w/ the default database in datastore mode, and was able to use that resource to configure a TTL policy:

```
resource "google_firestore_field" "default" {
  project = "tf-test-4glueeyzzm" # datastore project
  database = "(default)"
  collection = "chatrooms"
  field = "my_ttl"

  ttl_config {}
```
