### ISSUE TITLE
How to create gke windows node-pools with terraform with metadata

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#14818]
We need to create a GKE cluster using terraform, we are using module "gke" to create cluster. (https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest)

We have a scenario were we need to create windows nodepool and need to execute few powershell script to add metadata for windows nodepool.

earlier we were using gcloud below command to create windows node-pools :

gcloud beta container node-pools create cpu4w --project {projectid} --region {region} --image-type=WINDOWS_LTSC_CONTAINERD --cluster {cluster-name} --machine-type {machine-type} --num-nodes 0 --min-nodes 0 --max-nodes 20 --enable-autoscaling --node-labels={labels} --node-taints=taints --no-enable-autoupgrade --service-account={service-account} --metadata-from-file=sysprep-specialize-script-ps1=./windows.ps1 --metadata=windows-startup-script-bat="type C:\etc\kubernetes\monitor.ps1 && powershell -Command Start-Process powershell C:\etc\kubernetes\monitor.ps1"

But in the hashicorp document we dont see the option to execute metadata for windows node-pools.

Can you help us know how to execute powershell script as part of windows node-pools creation via terraform.

gke link : https://cloud.google.com/compute/docs/instances/startup-scripts/windows

**Comment by edwardmedia** [comment]
@bptambake it looks like [metadata](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#metadata) is supported. You may also check its [api doc](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig) for the details

**Comment by edwardmedia** [comment]
@bptambake is this still a question?

**Comment by bptambake** [comment]
Hi Team

I am still verifying the solution and will update by next week if any
issues

Thanks for your help

Regards
Basavaraj

**Comment by bptambake** [comment]
Hi Team

I am using module "gke" to create kubernetes gke cluster, but I want to
disable auto_upgrade (auto_upgrade=false) for all the nodepools, I am not
able to disable for all the nodepools.

How can I handle this? below highlighted is not working. please let us know
how to handle this as soon as possible

Regards
Basavaraj

[image: image.png]

**Comment by edwardmedia** [comment]
@bptambake since you are using the module, you may reach out to its owner to see if you can get the answer. As far as for the feature at the provider level, it is [what](https://github.com/hashicorp/terraform-provider-google/issues/14818#issuecomment-1578754569) as I explained. 

How did you achieve disabling auto_upgrade using other methods?

**Comment by bptambake** [comment]
Hi Team

can you please help us know how to set windows-os-version to "ltsc2022" for windows nodepool in terraform for gke

**Comment by bptambake** [comment]
Hi Team

Can you please help us know how to set windows-is-version to ltsc2022 for
windows node pool in terraform for hike

**Comment by edwardmedia** [comment]
@bptambake 
1) have you got it working for setting auto_upgrade?
2) do you know how to set the windows-os-version in the gcloud?

**Comment by edwardmedia** [comment]
@bptambake did you see below error? Where did you see your gcloud is working? 

```
the specified node image type \"WINDOWS_LTSC2022_CONTAINERD\" is not available.
```

**Comment by bptambake** [comment]
Hi team

below is the complete comamnd

gcloud beta container node-pools create cpu4w --project=test --cluster=test --region=us-central1 --image-type=WINDOWS_LTSC_CONTAINERD  --windows-os-version=ltsc2022 --machine-type=c2-standard-4 --enable-autorepair --no-enable-autoupgrade --enable-autoscaling --disk-type=pd-standard --disk-size=100


**--image-type=WINDOWS_LTSC_CONTAINERD  --windows-os-version=ltsc2022**

**Comment by bptambake** [comment]
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/678c5779-3292-4a42-a35c-a7b1fc36033a)

**Comment by edwardmedia** [comment]
@bptambake you may see the fields like below schema. 

```
{
    "nodePool": {
        "autoscaling": {
            "enabled": true
        },
        "config": {
            "diskSizeGb": 100,
            "diskType": "pd-standard",
            "imageType": "WINDOWS_LTSC_CONTAINERD",
            "machineType": "c2-standard-4",
            "oauthScopes": [
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/logging.write",
                "https://www.googleapis.com/auth/monitoring",
                "https://www.googleapis.com/auth/service.management.readonly",
                "https://www.googleapis.com/auth/servicecontrol",
                "https://www.googleapis.com/auth/trace.append"
            ],
            "windowsNodeConfig": {
                "osVersion": "OS_VERSION_LTSC2022"
            }
        },
        "initialNodeCount": 3,
        "management": {
            "autoRepair": true,
            "autoUpgrade": false
        },
        "name": "cpu4w",
        "upgradeSettings": {
            "maxSurge": 1
        }
    }
}
```

**Comment by bptambake** [comment]
but how to set that in terraform (module gke)

**Comment by bptambake** [comment]
getting below error

![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/8352075d-65e8-4d9c-b610-fa438aec4c07)

**Comment by edwardmedia** [comment]
Yeah, it appears `windowsNodeConfig` has not been implemented. Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) and it will be triaged 

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#WindowsNodeConfig

**Comment by bptambake** [comment]
Hi Team

I have created new enhancement request
https://github.com/hashicorp/terraform-provider-google/issues/14906

**Comment by bptambake** [comment]
Hi Team

Any updates on the https://github.com/hashicorp/terraform-provider-google/issues/14906

**Comment by bptambake** [comment]
@edwardmedia 

As said, I have raised an enhancement request https://github.com/hashicorp/terraform-provider-google/issues/14906, can you please provide any updates on that? Also the request is changed as "question", I have raised it as enhancement.

**Comment by bptambake** [comment]
@edwardmedia 
can you reopen this as commented
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/8d8b79bf-3624-476f-b915-0434704c02ae)
