### ISSUE TITLE
Review issue and PR templates in TPG and magic-module repos

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14822]
# Background

There are broken links in the checklist in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.github/PULL_REQUEST_TEMPLATE.md

There are references to hashibot in these files, but hashibot has been removed from the repo:
- https://github.com/hashicorp/terraform-provider-google/blob/main/.github/ISSUE_TEMPLATE/00_bug.md
- https://github.com/hashicorp/terraform-provider-google/blob/main/.github/ISSUE_TEMPLATE/01_enhancement.md

**We could do a general refresh of these files as they're a bit outdated.**

# What kind of contribution is this issue about?

* general contributions

**Comment by rileykarson** [comment]
We could trim down / eliminate the checklist on MM PRs with this refresh. I don't think it's giving us much signal.

**Comment by SarahFrench** [comment]
Stephen mentioned issue forms could be useful here, too

**Comment by melinath** [comment]
This is completed by the refactor to use issue forms.
