### ISSUE TITLE
google_service_account_id_token not working since 4.65.0

### ISSUE THREAD

**Issue by aweberlopes** [hashicorp/terraform-provider-google#14834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* data google_service_account_id_token

### Terraform Configuration Files

```tf
  data "google_service_account_id_token" "oidc" {
    target_audience = "https://europe-west3-bdaa-deployment-fnd-cg19am0m.cloudfunctions.net"
    target_service_account = "notifier-sa@bdaa-deployment-fnd-cg19am0m.iam.gserviceaccount.com"
  }
```

### Error

```tf
│ Error: unable to retrieve TokenSource: idtoken: unsupported credentials type
│ 
│   with data.google_service_account_id_token.oidc,
│   on main.tf line 48, in data "google_service_account_id_token" "oidc":
│   48:   data "google_service_account_id_token" "oidc" {
│ 
```

### Expected Behavior

```
tf plan
data.google_service_account_id_token.oidc: Reading...
data.google_service_account_id_token.oidc: Read complete after 0s [id=notifier-sa@bdaa-deployment-fnd-cg19am0m.iam.gserviceaccount.com]
```

### Actual Behavior

See Error above

### Steps to Reproduce

Try to use data google_service_account_id_token with >= 4.65 version of the provider

**Comment by edwardmedia** [comment]
@aweberlopes 1) I have tested on the examples from [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account_id_token), all fine with me. 2) I have also checked out its source code, no change lately.

Using the **same** config, was it fine for earlier versions? If yes, could share the debug logs for both working and not working applies?

**Comment by edwardmedia** [comment]
@aweberlopes is this still an issue?

**Comment by edwardmedia** [comment]
@aweberlopes closing this assuming it is no longer an issue

**Comment by adegtyarev** [comment]
@aweberlopes if you managed to fix or workaround the issue, could you pls share?
