### ISSUE TITLE
Using a subdomain with 'google_project_iam_member'

### ISSUE THREAD

**Issue by cr-lucas-alvarenga** [hashicorp/terraform-provider-google#14838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/google v4.66.0
+ provider registry.terraform.io/hashicorp/google-beta v4.66.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* google_project_iam_member

### Terraform Configuration Files

```tf
resource "google_project_iam_member" "domainwide" {
  for_each = toset([
    "roles/bigquery.dataViewer",
    "roles/bigquery.jobUser"
  ])

  project = var.config.project.id
  role    = each.key
  member  = "domain:subdomain.domain.com"
}
```

### Debug Output

https://gist.githubusercontent.com/cr-lucas-alvarenga/f8749e6addd7bde98c3609eb778adb6b/raw/15a1917665c3867dd5dd33a128a4bb1680be57f4/output.log

### Expected Behavior

IAM page should show "subdomain.domain.com" as Principal.

### Actual Behavior

IAM page returns "domain.com", missing the subdomain entirely.

### Steps to Reproduce

Create a 'google_project_iam_member' with member of value `domain:subdomain.domain.com`

1. `terraform apply`

### Important Factoids

Running in a GitLab CI/CD Pipeline (docker image)

**Comment by edwardmedia** [comment]
@cr-lucas-alvarenga based on the [document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam), it asks for a G Suite domain.  Do you see somewhere that shows it can be used for a subdomain? 

```
domain:{domain}: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
```

**Comment by edwardmedia** [comment]
@cr-lucas-alvarenga I can't find a document that says the subdomain is supported. From the [log](https://github.com/hashicorp/terraform-provider-google/issues/14838#issue-1746383724) you provided, the issue seems to complain a different thing. To take a closer look, can you share your debug log that includes the api requests and responses?

**Comment by edwardmedia** [comment]
@cr-lucas-alvarenga is this still an issue?

**Comment by edwardmedia** [comment]
@cr-lucas-alvarenga closing this assuming it is no longer an issue

**Comment by cr-lucas-alvarenga** [comment]
I apologize for the delay @edwardmedia, last week we had a national holiday. Unfortunately, I could not provision an environment with debugging enabled. For now, our team decided to proceed by manually adding subdomain principals on the GCP Console (we still can't do it via Terraform). Thank you for your time.
