### ISSUE TITLE
Possible api call bug in logging_project_bucket_config when creating a config for _Default bucket

### ISSUE THREAD

**Issue by saeedek** [hashicorp/terraform-provider-google#14836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

"terraform_version": "1.4.6"
"google provider version": "4.67.0"

### Affected Resource(s)

* google_logging_project_bucket_config

When applying this tf code:
```
resource "google_logging_project_bucket_config" "default" {
    project           = "project-name"
    location          = "europe-west1"
    provider          = google.logging
    retention_days    = 15
    enable_analytics  = false
    bucket_id         = "_Default"
}
```

I get this error:
`Error: Error creating Bucket: googleapi: Error 400: Resource id can only start with an alphanumber character`

### Expected Behavior

It should have tried to update/manage the resource not trying to create one.

### Actual Behavior

It fails as the resource name does not start with alphanumber character.

**Comment by saeedek** [comment]
@edwardmedia I don't want to create a new one, but to manage the _Default bucket which from my understanding this resource will do.

**Comment by edwardmedia** [comment]
@saeedek do you see anywhere that shows you can manage the _Default bucket?

https://cloud.google.com/logging/docs/default-settings

**Comment by saeedek** [comment]
In the top yellow box it is said:

> Creating a resource of this type will acquire and update the resource that already exists at the desired location.

Plus the example where bucket_id is equal to _Default is used (Which you mentioned that could be a mistake).
So it is safe to assume it is not possible to manage/update the _Default bucket using this resource, correct?

**Comment by edwardmedia** [comment]
@saeedek you can update and manage the _Default bucket

1) import _Default 
2) update attributes like `retention_days`
3) apply

```tf
resource "google_logging_project_bucket_config" "default" {
    bucket_id        = "_Default"
    description      = "Default bucket"
    enable_analytics = false
    location         = "global"
    project          = "projects/yourproject"
    retention_days   = 15   ---> (update from 30, default, to 15)
}
```

**Comment by saeedek** [comment]
@edwardmedia Thank you for your explanations.
I figured out the issue and resolved it based on the suggestion.

I will close this.
