### ISSUE TITLE
FR to add IOPS option for pd-extreme/hyperdisk-extreme within a disk block for google_compute_instance_template resource.

### ISSUE THREAD

**Issue by iabimac** [hashicorp/terraform-provider-google#14858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We would like to be able to set the 'provisioned_iops' option for 'pd-extreme' or 'hyperdisk-extreme' disks directly within the 'disk' block in the 'google_compute_instance_template' resource, instead of linking the disk source to a google_compute_disk where we are able to set the provisioned_iops setting.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk#provisioned_iops

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

Being able to use the 'provisioned_iops' for the disk block within the 'google_compute_instance_template' resouce.

 In the below example we would like 'Disk1' to be able to set 'provisioned_iops' within its disk block instead of using the 'Disk2' approach where we have to link the disk to another resource 'google_compute_disk.hyperdiskextreme.name' where we are able to set the 'provisioned_iops' option.

I am using latest terraform version and google provider version.

```
resource "google_compute_instance_template" "testTemplate" {
  name = "testTemplate"
  machine_type = "c3-highcpu-88"
  #Disk1
  disk {
    source_image      = "debian-cloud/debian-11"
    auto_delete = true
    boot        = true
    type             = "pd-extreme"
    provisioned_iops = "3000"
  }
 # Disk2
  disk {
    source      = google_compute_disk.hyperdiskextreme.name
    auto_delete = false
    boot        = false
  }
  network_interface {
    network = "default"
  }
}

resource "google_compute_disk" "hyperdiskextreme" {
  name             = "hyperdiskextreme"
  type             = "hyperdisk-extreme"
  provisioned_iops = "60000"
  zone             = "us-central1-a"
  physical_block_size_bytes = 4096
}
```

### References

* N/A

b/290345723

**Comment by rileykarson** [comment]
@roaks3 this was missing docs, do you mind adding those? Handwritten resources don't get those automatically, unfortunately.
