### ISSUE TITLE
Terraform support for configurable client HTTP Keepalive Timeout of Global External HTTP(S) Load Balancer

### ISSUE THREAD

**Issue by rostislavbobo** [hashicorp/terraform-provider-google#14867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for the new client HTTP keepalive timeout of Global External HTTP(S) Load Balancers, now in public preview. Read more about client HTTP keepalive timeout at https://cloud.google.com/load-balancing/docs/https?db=lb-stage-docs#timeout-keepalive-clients.

### New or Affected Resource(s)

* google_compute_target_http_proxy: `http_keep_alive_timeout_sec = number`
* google_compute_target_https_proxy: `http_keep_alive_timeout_sec = number`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

Configuration of a client HTTP keepalive timeout is similar to the [Target Http Proxy Basic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_http_proxy#example-usage---target-http-proxy-basic) and [Target Https Proxy Basic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_https_proxy#example-usage---target-https-proxy-basic) configuration with `http_keep_alive_timeout_sec` set to a number in a range `[5, 1200]`.

Note, there's no `http_keep_alive_timeout_sec` support for `google_compute_region_target_http_proxy` and `google_compute_region_target_https_proxy` as of now.

### References

* https://cloud.google.com/load-balancing/docs/https?db=lb-stage-docs#timeout-keepalive-clients

**Comment by melinath** [comment]
@rostislavbobo is there any additional work remaining on this ticket?

**Comment by rostislavbobo** [comment]
@melinath , in a couple of weeks we'll be adding GA support for this field. I can open a separate feature request or keep using this issue. Other that that, the beta scope is done.

**Comment by melinath** [comment]
@rostislavbobo cool, let's use a separate ticket for the promotion of the field to GA.
