### ISSUE TITLE
Cloud function logging can be improved when Go "github.com/GoogleCloudPlatform/functions-framework-go/funcframework" import is missing

### ISSUE THREAD

**Issue by rquinlivan** [hashicorp/terraform-provider-google#14889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When using the `google_cloudfunctions_function` resource, an error is produced if the following import is not present in the cloud function entrypoint Go source file:

"github.com/GoogleCloudPlatform/functions-framework-go/funcframework"

If this import is missing, the provider then returns an error:

```
    ��� Error: Error while updating cloudfunction configuration: %!s(<nil>)
    ��� 
    ���   with google_cloudfunctions_function.NAME,
    ���   on [cloudfunction.tf](http://cloudfunction.tf/) line 79, in resource "google_cloudfunctions_function" "NAME":
    ���   79: resource "google_cloudfunctions_function" "NAME" {
```

This error provides no information for debugging the issue. The log that provides context for the problem is found in Logs Explorer, under the logs for the affected cloud function:

```
"github.com/GoogleCloudPlatform/functions-framework-go"; if your function does not depend on the module, please add a blank import: `_ "github.com/GoogleCloudPlatform/functions-framework-go/funcframework"`; Error ID: 7a966edd
```

It would be ideal if the Terraform resource validated that the Go code bundle will include this necessary import and fail validation, rather than producing an error at runtime. If the error must be produced at runtime, it would be better if the error from the Log Explorer would show up in the output from Terraform to provide context for why the failure occurred.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

Not applicable

### References

* #0000

**Comment by rileykarson** [comment]
Validating this in Terraform would require inspecting the validity of the source code being sent to Cloud Functions, which isn't logic we'd be comfortable replicating clientside. Note that https://github.com/hashicorp/terraform-provider-google/issues/8768 covers improving error messages for similar cases.
