### ISSUE TITLE
google_binary_authorization_policy diff is noisy

### ISSUE THREAD

**Issue by drcapulet** [hashicorp/terraform-provider-google#14899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When trying to define the list of exclusions for a binary authorization policy, if you made a modification other than to add at the end of the list (like if you're keeping the list sorted), the diff is pretty much unusable.

### New or Affected Resource(s)

* `google_binary_authorization_policy`

### Potential Terraform Configuration

If you start with (abbreviated):

```tf
resource "google_binary_authorization_policy" "main" {
  ...

  dynamic "admission_whitelist_patterns" {
    for_each = toset([
      "gcr.io/google-containers/cluster-autoscaler:*",
      "gcr.io/google-containers/dnsmasq:*",
      "gcr.io/google-containers/dnsutils:*",
    ])

    content {
      name_pattern = admission_whitelist_patterns.value
    }
  }
}
```

And change to: 

```tf
resource "google_binary_authorization_policy" "main" {
  ...

  dynamic "admission_whitelist_patterns" {
    for_each = toset([
      "gcr.io/google-containers/cluster-autoscaler:*",
      "gcr.io/google-containers/coredns:*",
      "gcr.io/google-containers/dnsmasq:*",
      "gcr.io/google-containers/dnsutils:*",
    ])

    content {
      name_pattern = admission_whitelist_patterns.value
    }
  }
}
```

Your diff output will appear something like:

```
~ resource "google_binary_authorization_policy" "main" {
        id                            = "..."

      ~ admission_whitelist_patterns {
          ~ name_pattern = "gcr.io/google-containers/dnsmasq:*" -> "gcr.io/google-containers/coredns:*"
        }

      ~ admission_whitelist_patterns {
          ~ name_pattern = "gcr.io/google-containers/dnsutils:*" -> "gcr.io/google-containers/dnsmasq:*"
        }

      + admission_whitelist_patterns {
          + name_pattern = "gcr.io/google-containers/dnsutils:*"
        }

        # (1 unchanged blocks hidden)
  }
```

**Comment by rileykarson** [comment]
This field is implemented as a list, which means that ordering matters. By inserting `"gcr.io/google-containers/coredns:*",` between other values, you're telling Terraform "put this at index 1", and the previous index 1 at index 2 / 2 to 3. That means that the diff it's creating is correct, albeit a bit unintuitive if you don't care about ordering yourself.
