### ISSUE TITLE
terrafrom gcs backend race condition

### ISSUE THREAD

**Issue by oprudkyi** [hashicorp/terraform-provider-google#14894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

 I was told that team of provider support gcs backend, so this is copy of original issue https://github.com/hashicorp/terraform/issues/30149 for reference 

### Terraform Version

1.4.6

### Affected Resource(s)

* terraform.backend "gcs"

### Terraform Configuration Files

```
terraform {
  backend "gcs" {
    bucket = "some-bucket"
    prefix = "some-prefix"
  }
}
```

### Expected Behavior

Lock obtained

### Actual Behavior

```
Acquiring state lock. This may take a few moments...

Error: Error acquiring the state lock

Error message: 2 errors occurred:
	* writing
"gs://some-bucket/some-prefix/default.tflock"
failed: googleapi: Error 412: At least one of the pre-conditions you
specified did not hold., conditionNotMet
	* storage: object doesn't exist
```

### Steps to Reproduce

30-40+ parallel processes which concurrently access the same state
terraform apply -auto-approve -lock-timeout=30m -no-color

### Important Factoids

The race condition happens when many concurrent terraform processes (30+) try to obtain the same state/lock 
- original issue is https://github.com/hashicorp/terraform/issues/30149 and it is 1.5 years old 
- probably fix is https://github.com/hashicorp/terraform/pull/33062 and ~2 month old 

### References

* https://github.com/hashicorp/terraform/issues/30149
* https://github.com/hashicorp/terraform/pull/33062
* b/287190847

**Comment by edwardmedia** [comment]
I am not sure how much we can do at the provider level.

**Comment by oprudkyi** [comment]
Hi @edwardmedia @slevenick  
I was told  there https://github.com/hashicorp/terraform/pull/33062#issuecomment-1557723838 that provider team maintains gcs backend in terraform 

I am trying to find someone who can review and probably merge fix https://github.com/hashicorp/terraform/pull/33062 (or make correct fix)

**Comment by oprudkyi** [comment]
Hi @megan07 

could you please help with fixing/merging this issue ? because it is really headache for me
