### ISSUE TITLE
add the customWriterIdentity parameter to logging_sink resources

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#14893]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since June 12, 2023, the Cloud logging sink has the ability to set a customWriterIdentity field.
I would like to be able to configure this in Terraform as well.

### New or Affected Resource(s)

* google_logging_project_sink
* google_logging_folder_sink
* google_logging_organization_sink

### Potential Terraform Configuration

```tf
resource "google_service_account" "other_project" {
  project      = "other-project-id"
  account_id   = "gce-log-bucket-sink"
  display_name = "gce-log-bucket-sink"
}

resource "google_logging_project_sink" "my-sink" {
  name = "other-project-log-bucket-sink"

  # Can export to pubsub, cloud storage, bigquery, log bucket, or another project
  destination = "logging.googleapis.com/projects/other-project-id/locations/global/buckets/gce-logs"

  # Log all WARN or higher severity messages relating to instances
  filter = "resource.type = gce_instance AND severity >= WARNING"

  # Use a unique writer (creates a unique service account used for writing)
  unique_writer_identity = true
  
  # The new settings are as follows.
  custom_writer_identity = google_service_account.other_project.email
}
```

### References

* https://cloud.google.com/logging/docs/routing/user-managed-service-accounts
* https://cloud.google.com/logging/docs/release-notes#June_12_2023
* https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.sinks/create#query-parameters
* https://cloud.google.com/logging/docs/reference/v2/rest/v2/folders.sinks/create#query-parameters
* https://cloud.google.com/logging/docs/reference/v2/rest/v2/organizations.sinks/create#query-parameters

* b/287684175

**Comment by bmenasha** [comment]
Since May of 2023 logging will no longer create a unique logging identifier https://cloud.google.com/logging/docs/release-notes#May_31_2023  making it more important to have the ability to control the writer identity of the logging sink. 
thanks
