### ISSUE TITLE
how to set windows-os-version to "ltsc2022" for windows nodepool in terraform for gke

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#14904]
Hi Team

can you please help us know how to set windows-os-version to "ltsc2022" for windows nodepool in terraform for gke

**Comment by edwardmedia** [comment]
This is the extension of https://github.com/hashicorp/terraform-provider-google/issues/14818. Let's close this and reopen the original https://github.com/hashicorp/terraform-provider-google/issues/14818
