### ISSUE TITLE
how to set windows-os-version to "ltsc2022" for windows nodepool in gke via terraform

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#14906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
We want to create windows nodepool with windows-0s-version "ltsc2022", as cofirmed (https://github.com/hashicorp/terraform-provider-google/issues/14818) this feature is not supported in terraform.

below is the gcloud command:

gcloud beta container node-pools create cpu4w --project=test --cluster=test --region=us-central1 --image-type=WINDOWS_LTSC_CONTAINERD --windows-os-version=ltsc2022 --machine-type=c2-standard-4 --enable-autorepair --no-enable-autoupgrade --enable-autoscaling --disk-type=pd-standard --disk-size=100

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by bptambake** [comment]
Hi Team

This ticket was raised as enhancement to provision windows nodepool with 2022 image, but not sure why it was changed to question. Any reasons?
can you please consider this as enhancement  request and help us with this feature

Thanks.

**Comment by bptambake** [comment]
@rileykarson

This ticket was raised as enhancement to provision windows nodepool with 2022 image, but not sure why it was changed to question. Any reasons?
can you please consider this as enhancement request and help us with this feature

Thanks.

**Comment by bptambake** [comment]
Hi Team, @rileykarson , @edwardmedia

This ticket was raised as enhancement as requested by @edwardmedia as part of this ticket https://github.com/hashicorp/terraform-provider-google/issues/14818, please consider this as enhancement request.

![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/6d922cd3-42a9-4c7a-a111-966f7a21340c)

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/14979

**Comment by bptambake** [comment]
@rileykarson 

since this was changed to "question" so raised new one, so please consider https://github.com/hashicorp/terraform-provider-google/issues/14979 as enhancement request
