### ISSUE TITLE
enforce_on_key = "" # forces replacement

### ISSUE THREAD

**Issue by fralvarop** [hashicorp/terraform-provider-google#14905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/google v4.69.1
+ provider registry.terraform.io/hashicorp/google-beta v4.69.1
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/ndrpnt/mattermost v0.1.0
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.24
```

### Affected Resource(s)

* google_compute_security_policy 

### Terraform Configuration Files

```tf
resource "google_compute_security_policy" "default-policy" {
  provider = google-beta
  name    = "default-policy"
  project = module.project.project_id
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable = true
    }
  }

  advanced_options_config {
    json_parsing = "STANDARD"
    log_level    = "VERBOSE"
  }

  rule {
    action   = "allow"
    priority = "2147483647"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "Default rule, higher priority overrides it"
  }

  rule {
    preview  = false
    action   = "throttle"
    priority = "4990"
    match {
      expr {
        expression = "evaluateAdaptiveProtectionAutoDeploy()"
      }
    }

    rate_limit_options {
      ban_duration_sec = 0
      conform_action   = "allow"
      exceed_action    = "deny(404)"

      enforce_on_key = ""

      enforce_on_key_configs {
        enforce_on_key_type = "XFF_IP"
      }

      rate_limit_threshold {
        count        = 500
        interval_sec = 120
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/fralvarop/1b13a4ffc3ac552475d25f2714042601
### Expected Behavior

The rules should have been updated

### Actual Behavior

It trys to recreate the whole policy instead of updating the rules.

### Steps to Reproduce

1. Set `provider = google-beta` (as documentation indicates): [resource doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy#example-usage---with-enforceonkey-value-as-empty-string)
2. `terraform apply`

### References

* #0000

**Comment by fralvarop** [comment]
Hi @edwardmedia these are all the change I have done using terraform. I can modify it using cloud-armor GUI in GCP. I have no try using any command.
![Captura de pantalla 2023-06-16 a las 8 18 54](https://github.com/hashicorp/terraform-provider-google/assets/40148790/4bbc5f00-c8f1-4f7e-a558-1cc2d90d0246)

**Comment by edwardmedia** [comment]
It appears `enforce_on_key_configs` is the field that triggers recreation. https://github.com/hashicorp/terraform-provider-google-beta/blob/941f882014ba6f90ba7bbe16203c899f4fefca3a/google-beta/services/compute/resource_compute_security_policy.go#L277

**Comment by edwardmedia** [comment]
b/288767528

We can't remove ForceNew at this moment. The api behaves differently on creating the resource and updating the resource. The api accepts the first call but rejects with `Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs, Only one of enforceOnKey and enforceOnKeyConfigs can be specified.`

```
POST /compute/beta/projects/myproject/global/securityPolicies
Hostcompute.googleapis.com
{
 "rules"[
  {
    "enforceOnKey""IP",
    "enforceOnKeyConfigs"[],
    "enforceOnKeyName""",
...
    },
...
    }
   }
  }
 ]
}
```

Update
```
POST /compute/beta/projects/myproject/global/securityPolicies/issue14905/patchRule
Host: compute.googleapis.com
{
...
  "enforceOnKey": "IP",
  "enforceOnKeyConfigs": [],
  "enforceOnKeyName": "",
  }
 }
}
```

**Comment by edwardmedia** [comment]
Looks like switching between enforceOnKeyConfigs to enforce_on_key, we need to add updateMask like below

&updateMask=rateLimitOptions.enforceOnKeyConfigs
