### ISSUE TITLE
Create new resources to support Secure Web Proxy

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-google#14918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_secure_web_proxy_gateway
* google_secure_web_proxy_security_policy
* google_secure_web_proxy_security_policy_rule
* google_secure_web_proxy_tls_inspection_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/secure-web-proxy/docs/apis

**Comment by bschaatsbergen** [comment]
I'll pick this up as well :)!

**Comment by jorgel272** [comment]
Awesome Bruno, would be great to have these new resources in the Terraform provider 👍🏼

**Comment by jorgel272** [comment]
@bschaatsbergen We would also need a google_secure_web_proxy_security_rule resource. 

The Security rules are part of a Security Policy. The Security rules do the actually heavy lifting of blocking the traffic 😎

**Comment by bschaatsbergen** [comment]
Awesome, thanks for spotting this @jorgel272 👌

**Comment by bschaatsbergen** [comment]
It looks like https://github.com/GoogleCloudPlatform/magic-modules/pull/7942 has addressed adding the Secure Web Proxy Gateway. I'll see what needs to be added.
