### ISSUE TITLE
Provider produced inconsistent result after apply for cloudsql(mssql)

### ISSUE THREAD

**Issue by msraju04** [hashicorp/terraform-provider-google#14926]
I am deploying cloudsql (mssql) resource from Github actions, but during terraform apply I'm getting this error. Instance has be created successfully but DB is not created. I am getting this error.

 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.sql.google_sql_database.default, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing hashicorp/null v3.2.1...
- Installed hashicorp/null v3.2.1 (signed by HashiCorp)
- Installing hashicorp/google-beta v4.69.1...
- Installed hashicorp/google-beta v4.69.1 (signed by HashiCorp)
- Installing hashicorp/google v4.67.0...
- Installed hashicorp/google v4.67.0 (signed by HashiCorp)

### Affected Resource(s)

google_sql_database.default

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.67.0"
    }
  }
}




resource "random_id" "instance_name_suffix" {
  byte_length = 3
}
module "sql" {
  source                          = "../../../gcp_module/dbas-gcp-db-modules/cloudsql"
  name                            = var.name
  random_instance_name            = false
  project_id                      = var.project_id
  database_version                = var.db_version
  region                          = var.region
  deletion_protection             = var.deletion_protection
  tier                            = var.tier
  availability_type               = var.availability_type
  zone                            = var.zone
  disk_size                       = var.disk_size
  disk_autoresize                 = var.disk_autoresize
  user_labels                     = var.user_labels
  maintenance_window_day          = 7
  maintenance_window_hour         = 8
  maintenance_window_update_track = "stable"
  database_flags = var.database_flags
  ip_configuration = {
    require_ssl         = true
    private_network     = data.google_compute_network.target_project_network.id
    authorized_networks = []
    ipv4_enabled        = false
    allocated_ip_range  = var.allocated_ip_range
  }
  backup_configuration = var.backup_configuration
  
  db_name              = var.db_name
  db_charset           = "UTF8"
  db_collation         = "en_US.UTF8"
  user_name            = var.user_name
  user_password        = "aaaaaaaaaaaa"
  root_password        = "bbbbbbbb"
  additional_databases = []
  additional_users     = []
}

# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

module.sql.google_sql_database_instance.default: Modifying... [id=zzzzzzzzzz]
module.sql.google_sql_database_instance.default: Still modifying... [id=zzzzzzzz, 10s elapsed]
module.sql.google_sql_database_instance.default: Still modifying... [id=zzzzzzzzzzzzzzzzz, 20s elapsed]
module.sql.google_sql_database_instance.default: Still modifying... [id=zzzzzzzzzzzzzzzzzzz, 30s elapsed]
module.sql.google_sql_database_instance.default: Modifications complete after 31s [id=zzzzzzzzzzzzzzzz]
module.sql.google_sql_database.default: Creating...
module.sql.random_password.user-password: Creating...
module.sql.random_password.user-password: Creation complete after 0s [id=none]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.sql.google_sql_database.default, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Error: Process completed with exit code 1.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@msraju04 your config is on module and with various variables. It is hard for me to guess what is going on. Can you provide a config of individual `resources` with hardcoded values so I can repro the issue you reported?

**Comment by edwardmedia** [comment]
@msraju04 is this still an issue?
