### ISSUE TITLE
Add support for shardSize in google_vertex_ai_index

### ISSUE THREAD

**Issue by i2sarroyo** [hashicorp/terraform-provider-google#14935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The API supports the definition of the index deployed instances with the shardSize field in metadata config but the actual terraform config does not. By default it creates the index with the option SHARD_SIZE_MEDIUM which tenfold the memory of the minimun possible VM created for it and it impact the costs.

### New or Affected Resource(s)

google_vertex_ai_index

### Potential Terraform Configuration

```tf
resource "google_vertex_ai_index" "index" {
  region   = "us-central1"
  display_name = "test-index"
  description = "index for test"
  metadata {
    contents_delta_uri = "gs://${google_storage_bucket.bucket.name}/contents"
    config {
      dimensions = 2
      approximate_neighbors_count = 150
      distance_measure_type = "DOT_PRODUCT_DISTANCE"
      shard_size = "SHARD_SIZE_MEDIUM"
      algorithm_config {
        tree_ah_config {
          leaf_node_embedding_count = 500
          leaf_nodes_to_search_percent = 7
        }
      }
    }
  }
}
```

### References

* https://cloud.google.com/vertex-ai/docs/matching-engine/create-manage-index#index-metadata-file
* https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.indexes#resource:-index

**Comment by shotarok** [comment]
@i2sarroyo I was not aware that shard_size is available when creating a PR for google_vertex_ai_index: https://github.com/GoogleCloudPlatform/magic-modules/pull/6728. 

Indeed, the shard_size appears in the example json below.

<details><summary>Details</summary>

<img width="924" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/1156179/cd72e3a5-2118-48fe-86fc-4c3162e048f7">
from https://cloud.google.com/vertex-ai/docs/matching-engine/create-manage-index#index-metadata-file

</details> 


However, it's not explained in the yaml specification and https://cloud.google.com/vertex-ai/docs/matching-engine/configuring-indexes either.

Based on the response and the following doc, I believe the available values are the following. And the default is "SHARD_SIZE_MEDIUM".  Have you tried the small and large shard sizes before?

* SHARD_SIZE_SMALL
* SHARD_SIZE_MEDIUM
* SHARD_SIZE_LARGE
 
<details><summary>Details</summary>
 
<img width="883" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/1156179/ac919394-360b-48f4-a4f7-5510f76ca534">
from https://cloud.google.com/vertex-ai/docs/matching-engine/create-manage-index#create-index

</details> 
 
 ---
 
 @rileykarson I'd appreciate it if you could tell us how to report the missing explanation to GCP.

**Comment by shotarok** [comment]
I could confirm `SHARD_SIZE_SMALL` and `SHARD_SIZE_LARGE` were available by running acceptance tests.

<details><summary>Details</summary>

```console
-----------------------------------------------------
2023/07/08 12:42:41 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="gfe-default_product_name"
Date: Sat, 08 Jul 2023 19:42:41 GMT
Report-To: {"group":"gfe-default_product_name","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/default_product_name"}]}
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/xxxxx/locations/us-central1/indexes/5220296490726981632",
  "displayName": "tf-test-test-indexq0ihszz7z4",
  "description": "index for test",
  "metadataSchemaUri": "gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml",
  "metadata": {
    "config": {
      "dimensions": 2,
      "distanceMeasureType": "COSINE_DISTANCE",
      "featureNormType": "UNIT_L2_NORM",
      "algorithmConfig": {
        "bruteForceConfig": {}
      },
      "shardSize": "SHARD_SIZE_LARGE"
    }
  },
  "etag": "AMEw9yORUpqz6mKEHUPrDJa3NspQbVBCfuT2TeN46W3UDCAB6VCohJ3q_xmnzl3nSIip",
  "labels": {
    "foo": "bar"
  },
  "createTime": "2023-07-08T19:04:32.204099Z",
  "updateTime": "2023-07-08T19:42:35.799633Z",
  "indexStats": {
    "vectorsCount": "2",
    "shardsCount": 1
  },
  "indexUpdateMethod": "STREAM_UPDATE"
}
```

```console
-----------------------------------------------------
2023/07/08 11:18:26 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="gfe-default_product_name"
Date: Sat, 08 Jul 2023 18:18:26 GMT
Report-To: {"group":"gfe-default_product_name","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/default_product_name"}]}
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/xxxxxx/locations/us-central1/indexes/3721160764766027776",
  "displayName": "tf-test-test-indexz199pyw7xj",
  "description": "index for test",
  "metadataSchemaUri": "gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml",
  "metadata": {
    "config": {
      "dimensions": 2,
      "approximateNeighborsCount": 150,
      "distanceMeasureType": "DOT_PRODUCT_DISTANCE",
      "featureNormType": "NONE",
      "algorithmConfig": {
        "treeAhConfig": {
          "leafNodeEmbeddingCount": "500",
          "leafNodesToSearchPercent": 7
        }
      },
      "shardSize": "SHARD_SIZE_SMALL"
    }
  },
  "etag": "AMEw9yO_A6lg7upig0EnvkMxb96_Bf8a0dH37JT1a3IOKAXmmoRBEVKUidJUD7mVM2k=",
  "labels": {
    "foo": "bar"
  },
  "createTime": "2023-07-08T17:38:55.912414Z",
  "updateTime": "2023-07-08T18:18:23.036365Z",
  "indexStats": {
    "vectorsCount": "2",
    "shardsCount": 1
  },
  "indexUpdateMethod": "BATCH_UPDATE"
}
```

</details>

**Comment by i2sarroyo** [comment]
Great news @shotarok. Thank you so much for the effort

**Comment by rileykarson** [comment]
A "report an issue" button on cloud.google.com or the product's [public issue tracker](https://cloud.google.com/support/docs/issue-trackers), such as [this template for vertex](https://issuetracker.google.com/issues/new?component=1130925) is probably the best way to surface that kind of feedback with their product team.

**Comment by shotarok** [comment]
Thank you! I created this issue: https://issuetracker.google.com/issues/290565133
