### ISSUE TITLE
error with google_tags_location_tag_binding

### ISSUE THREAD

**Issue by lpqI** [hashicorp/terraform-provider-google#14932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.3.4

### Affected Resource(s)

* google_tags_location_tag_binding

### Terraform Configuration Files

```tf
resource "google_tags_location_tag_binding" "dataset" {
  for_each = local.tag_bind_dataset

  parent    = "//bigquery.googleapis.com/projects/${data.google_project.default.id}/datasets/${each.value.dataset_id}"
  tag_value = google_tags_tag_value.default[each.value.tag_value].id
  location  = each.value.location
}

resource "google_tags_location_tag_binding" "bucket" {
  for_each = local.tag_bind_bucket

  parent    = "//storage.googleapis.com/projects/_/buckets/${each.bucket}"
  tag_value = google_tags_tag_value.default[each.value.tag_value].id
  location  = each.value.location
}
```

### Debug Output

```
│ Error: Error when reading or editing TagsLocationTagBinding "asia-northeast1/tagBindings/<dataset or bucket full resource name>/tagValues/12345567890": googleapi: Error 400: Request contains an invalid argument.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Must be a valid One Platform resource name of a tag compatible regional resource",
│         "field": "binding.resource"
│       },
│       {
│         "description": "Resource type not supported in location asia-northeast1",
│         "field": "binding.resource"
│       }
│     ]
│   }
│ ]
```

### Expected Behavior
`terraform plan` exits without error

### Actual Behavior
end with error in `terraform plan`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

i had imported google_tags_location_tag_binding with `terraform import` and tried `terraform plan` to check if the import was successful
the result was an error, so when I checked the log with TF_LOG=DEBUG, i had found that provider had accessed to the url https://asia-northeast1-cloudresourcemanager.googleapis.com//v3/tagBindings/?alt=json&pageSize=300&parent=

upon careful checking the url, I got that the `parent` was not set
(`parent` set in terraform resource does not seem to be set)

**Comment by edwardmedia** [comment]
@lpqI can you see below docs are helpful?

https://cloud.google.com/resource-manager/docs/tags/tags-supported-services

https://cloud.google.com/iam/docs/full-resource-names

**Comment by lpqI** [comment]
@edwardmedia 
thanks for your reply

unfortunately, the link you suggested didn't work

i could successfully import the resource
but I got the above error when I ran `terraform plan` to make sure it was imported correctly

**Comment by edwardmedia** [comment]
@lpqI how did you create the resource? Can you share the state of the imported one? Can you share the config for your  `terraform plan`?

**Comment by lpqI** [comment]
@edwardmedia 
thanks for your reply

> how did you create the resource?

i created these resources manually
import is executed after creating

> Can you share the state of the imported one?

- dataset
```json
    {
      "mode": "managed",
      "type": "google_tags_location_tag_binding",
      "name": "dataset",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "index_key": "test-dataset-binding",
          "schema_version": 0,
          "attributes": {
            "id": "asia-northeast1/tagBindings/%2F%2Fbigquery.googleapis.com%2Fprojects%2Ftest-project%2Fdatasets%2Ftest-dataset/tagValues/1234567890",
            "location": "asia-northeast1",
            "name": "tagBindings/%2F%2Fbigquery.googleapis.com%2Fprojects%2Fagj-groupdwh%2Fdatasets%2Ftest-dataset/tagValues/1234567890",
            "parent": "//bigquery.googleapis.com/projects/test-project/datasets/test-dataset",
            "tag_value": "tagValues/1234567890",
            "timeouts": {
              "create": null,
              "delete": null
            }
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjoxMjAwMDAwMDAwMDAwLCJkZWxldGUiOjEyMDAwMDAwMDAwMDB9LCJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        },
      ]
    },
```

- bucket
```json
{
  "mode": "managed",
  "type": "google_tags_location_tag_binding",
  "name": "bucket",
  "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
  "instances": [
    {
      "index_key": "test-bucket-binding",
      "schema_version": 0,
      "attributes": {
        "id": "asia-northeast1/tagBindings/%2F%2Fstorage.googleapis.com%2Fprojects%2F_%2Fbuckets%2Ftest-buket/tagValues/1234567890",
        "location": "asia-northeast1",
        "name": "tagBindings/%2F%2Fstorage.googleapis.com%2Fprojects%2F_%2Fbuckets%2Ftest-buket/tagValues/1234567890",
        "parent": "//storage.googleapis.com/projects/_/buckets/test-buket",
        "tag_value": "tagValues/1234567890",
        "timeouts": {
          "create": null,
          "delete": null
        }
      },
      "sensitive_attributes": [],
      "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjoxMjAwMDAwMDAwMDAwLCJkZWxldGUiOjEyMDAwMDAwMDAwMDB9LCJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
    },
  ]
},
```

>  Can you share the config for your `terraform plan` ?

i didn't use option for terraform plan

**Comment by edwardmedia** [comment]
@lpqI have you tried updating the config with all the attributes you got from the imported and then run plan? The [states](https://github.com/hashicorp/terraform-provider-google/issues/14932#issuecomment-1608629081) look fine with me.

**Comment by lpqI** [comment]
@edwardmedia 
thanks for your reply

i guess i am doing what you told me to do
i had configure all parameters shown URL below, run import and plan
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding
- parent
- tag_value
- location

**Comment by lpqI** [comment]
@edwardmedia 
i had tried remove tfstate and import again, but i got same errors
i used provider with version 4.69.1

```
provider "registry.terraform.io/hashicorp/google" {
  version = "4.69.1"
}
```

**Comment by edwardmedia** [comment]
@lpqI I assume you have updated the config before you run `terraform plan`, right? Can you share the debug log for both import and plan?

**Comment by lpqI** [comment]
@edwardmedia 
log files are here
[logs.zip](https://github.com/hashicorp/terraform-provider-google/files/11928802/logs.zip)

please check it

**Comment by edwardmedia** [comment]
@lpqI it looks like the provider was failing on finding the `parent`. As I [mentioned](https://github.com/hashicorp/terraform-provider-google/issues/14932#issuecomment-1614677100) earlier, did you update the config before you run `terraform plan`?

```tf
resource "google_tags_location_tag_binding" "dataset" {
  parent    = <---- did you provide a value here when you run plan
....
}
```

**Comment by lpqI** [comment]
@edwardmedia 

> did you update the config before you run `terraform plan` ?

yes, i am using csv to set the value
specific values are

```terraform
resource "google_tags_location_tag_binding" "dataset" {
  parent    = "//bigquery.googleapis.com/projects/test-project/datasets/all_c"
  tag_value = "tagValues/1234567890"
  location  = "asia-northeast1"
}
```

**Comment by edwardmedia** [comment]
@lpqI I don't understand what you meant below. Your [config](https://github.com/hashicorp/terraform-provider-google/issues/14932#issuecomment-1617095424) is is similar to [what](https://github.com/hashicorp/terraform-provider-google/issues/14932#issuecomment-1605735714) I provided which works for me. I have no clue why it doesn't work for you. Keep in mind, the error appears to complain about the value of parent. I would suggest you hardcode the config to see it works

```
yes, i am using csv to set the value
```

**Comment by lpqI** [comment]
@edwardmedia 
>  I would suggest you hardcode the config to see it works
i will try

**Comment by lpqI** [comment]
@edwardmedia 
thanks for your advice

however, the cause of the error was not the for_each using CSV, but the import performed by another worker
it seems that an error occurred because a tag that does not exist was imported with tag_bind
→it worked fine after removing wrongs from tfstate file

**Comment by lpqI** [comment]
@edwardmedia 
thanks for your asking me

i guess this is the root cause of this issue that it was able to import tag_bind that does not exist

for example,
if dataset as all_c with tag_value tv1 is correct pairs, 
but pair of all_c and tv2 that does not exist was able to import
(i got `type.googleapis.com/google.rpc.BadRequest` errors after importing)

i want error message with wrong pair, but i ended up importing successfully

**Comment by edwardmedia** [comment]
@lpqI  Cool, closing the issue now. Thanks
