### ISSUE TITLE
google_sql_source_representation_instance fails if host is a DNS name

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#14933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.4.4
Google provider 4.69.1

google_sql_source_representation_instance

### Terraform Configuration Files

```tf
resource "google_sql_source_representation_instance" "summitweatherdb" {
  name             = "mydb-representation"
  region           = var.region
  database_version = "POSTGRES_14"
  host             = "mysever.domain.com"
  port             = 5432
  username         = "replication"
  password         = random_password.replication-user.result
}
```

### Expected Behavior

Host can be an IPv4 address or a DNS entry, apply should work.

### Actual Behavior

Error: could not parse "host" to IP address

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

https://cloud.google.com/sql/docs/postgres/replication/configure-replication-from-external
SOURCE HOST | The IPv4 address and port for the external server, or the the DNS address for the external server.

**Comment by edwardmedia** [comment]
@philip-harvey can you create an instance with ip address on Console or via gcloud?

**Comment by philip-harvey** [comment]
> @philip-harvey can you create an instance with ip address on Console or via gcloud?

Hi @edwardmedia as far as I am aware you can only create a sql source representation instance via the API, not yet supported via Gcloud or the console.
https://cloud.google.com/sql/docs/postgres/replication/configure-replication-from-external#setup-source-instance

**Comment by edwardmedia** [comment]
I see `DNS address` should be supported based on the [doc](https://cloud.google.com/sql/docs/postgres/replication/configure-replication-from-external#setup-source-instance)

SOURCE HOST | The IPv4 address and port for the external server, or the the DNS address for the external server. If the external server is hosted on Cloud SQL, the port is 5432.
-- | --

However, looks like the [validationFunc](https://github.com/hashicorp/terraform-provider-google-beta/blob/7f3b2ecf7a5f3c44001f8412910d6140d12f6a5c/google-beta/services/sql/resource_sql_source_representation_instance.go#L71) is wrongly used

**Comment by edwardmedia** [comment]
b/288571243

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9225
