### ISSUE TITLE
new resource: google_pubsub_schema_iam

### ISSUE THREAD

**Issue by ksiedlarek** [hashicorp/terraform-provider-google#14934]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It is not possible to assign permissions on Pub/Sub schema level via Terraform.
It can only be done by web console and causes issues for people who would like to maintain whole of their infrastructure as code.

### New or Affected Resource(s)

Looking on existing resources we have google_pubsub_topic_iam & google_pubsub_subscription_iam, it would be great to have new one: **google_pubsub_schema_iam**

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

data "google_iam_policy" "viewer" {
  binding {
    role = "roles/viewer"
    members = [
      "user:jane@example.com",
    ]
  }
}

resource "google_pubsub_schema_iam_policy" "policy" {
  project = google_pubsub_schema.example.project
  schema = google_pubsub_schema.example.name
  policy_data = data.google_iam_policy.viewer.policy_data
}

resource "google_pubsub_schema_iam_binding" "binding" {
  project = google_pubsub_schema.example.project
  topic = google_pubsub_schema.example.name
  role = "roles/viewer"
  members = [
    "user:jane@example.com",
  ]
}

resource "google_pubsub_schema_iam_member" "member" {
  project = google_pubsub_topic.example.project
  topic = google_pubsub_schema.example.name
  role = "roles/viewer"
  member = "user:jane@example.com"
}
```

### References

* b/298493785

**Comment by bschaatsbergen** [comment]
I'm happy to start working on this 👍🏼

**Comment by bschaatsbergen** [comment]
I would be happy to work on this, but as of now I don't see an iamSetPolicy and iamGetPolicy API call available for schema's..  https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.schemas

**Comment by rileykarson** [comment]
Good catch! Labeled.

**Comment by Dasio** [comment]
PR was merged and it will be released in 5.4.0 ([changelog](https://github.com/hashicorp/terraform-provider-google/pull/16367))

Can be closed

**Comment by bschaatsbergen** [comment]
Awesome work!

**Comment by melinath** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/9228
