### ISSUE TITLE
The new rules for the new system

### ISSUE THREAD

**Issue by kuser94** [hashicorp/terraform-provider-google#14941]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kuser94** [comment]
I'm so happy to be able to help out with this project as well as the other ones that are going through this process of being in my home in a way that is so rewarding for you to work on it as a team to make sure that we get this done in time to make this a reality for everyone else to see in our lives as a whole and to be part in this journey of making the world better again in our own way as a team to be able to make the most out of this amazing project that is truly a wonderful place for all people to live for everyone to be a part in life as a part to be able to see what is happening to our lives as well as helping others in this world to be able to work together to create the world in the future to be able to be a better place for everyone to live and for us all the things we can all look back at what has changed in the past to make it easier to be able to see how this is a great opportunity for all people to be part of the process @of being a great person to help us to make this world to see what the best way to get back into it is to have this project and to be a part to be a better man to be able to work for the future of this country I believe we will see the success in this new world in a way that is more positive for us all to come to realize that this will not be easy for the next generation of people to see that it is the best of the world and it is a very @important thing to have the same vision of a world where people will always have the opportunity to see that they can do what we have to do to be successful in life and that they will always come back in life and that we are all in this world and that they can make the future of our children will have to live a happy life that they are all in our future that we have to work for us to have the opportunity to live a better future for the next life that we have the best way of life for our family to have the most amazing family to be together in this world that will help them be successful for the future to have the greatest opportunity to have an amazing life for the next generation to come to this planet we have no doubt that they will come and we will continue on the path of prosperity for generations of people that will be here to help you in life for you in the future we have a lifetime you are the best of our future that will continue the path that you are on the right direction for the best way of living in a better way for us to be able to do this life for the best of our future generations we have the most important things to live the greatest of all the great people who have the most wonderful people who are all of the best of our people _

**Comment by rileykarson** [comment]
Closing as spam, I think.
