### ISSUE TITLE
Remove comments like `# [START ...` and `# [END ...` from example files (and any handwritten files)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14947]
# Background

Comments structured like `# [START unique_identifier_ref]` and `# [END unique_identifier_ref]` were used at one point to reuse examples from TPG when creating samples for docs in [cloud.google.com](http://cloud.google.com/). This isn't used anymore but the codebase still has a bunch of comments like this.

The comments didn't usually make it into TPG/TPGB through templating, but there is some leakage possibly due to copy/pasting in handwritten files:

https://github.com/hashicorp/terraform-provider-google/blob/a76563b12020244ea59f09b2b643de086e3174a4/google/resource_cloudfunction2_function_test.go#L211

Removing these comments will help contributors to Magic Modules. The significance of the comments isn't easily understood and it complicates PR review if the comments are propagated via copy/pasting of example config.

# What kind of contribution is this issue about?

* general contributions

# Related PR(s), if any:

N/A

# Details

Removing this comments from MM will often not result in diffs in the downstreams. There are a few cases where comments have ended up in the downstream though.

**Comment by melinath** [comment]
It would be good to break up these changes into multiple pull requests.

**Comment by melinath** [comment]
Currently ~357 left

**Comment by melinath** [comment]
Completed by the PRs above
