### ISSUE TITLE
Bigtable retention settings are not applied in-place, which causes updates to fail on replicated instances

### ISSUE THREAD

**Issue by bonnici** [hashicorp/terraform-provider-google#14943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/hashicorp/google v4.59.0
+ provider registry.terraform.io/hashicorp/google-beta v4.37.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/mrolla/circleci v0.6.1
```

### Affected Resource(s)

* google_bigtable_gc_policy

### Terraform Configuration Files

before:
```tf
resource "google_bigtable_gc_policy" "xxxxx_data_gc" {
  column_family = "xxxxxData"
  instance_name = google_bigtable_instance.xxxxx.name
  table         = google_bigtable_table.xxxxx_table.name

  max_age {
    duration = "2280h"
  }
}
```

after:
```tf
resource "google_bigtable_gc_policy" "xxxxx_data_gc" {
  column_family = "xxxxxData"
  instance_name = google_bigtable_instance.xxxxx.name
  table         = google_bigtable_table.xxxxx_table.name

  mode = "UNION"
  max_age {
    duration = "2280h"
  }
  max_version {
    number = 1
  }
}
```

### Debug Output

https://gist.github.com/bonnici/a8208dbeb3f723aa1149f10fcb6c141d

### Expected Behavior

The bigtable retention settings should be applied in-place. This is especially important for replicated instances, where removing the "max days" retention setting is [not allowed](https://cloud.google.com/bigtable/docs/garbage-collection#restrictions_on_changing_age-based_garbage_collection_policies). 

### Actual Behavior

The bigtable retention settings are first removed (causing an error) before being re-created.

```
module.infrastructure.google_bigtable_gc_policy.traces_data_gc: Destroying... [id=age() > 95d]
╷
│ Error: rpc error: code = FailedPrecondition desc = Cannot relax pure age-based GC for a replicated family (traceData). If you must relax the age constraint, unreplicate the instance and try again. For more information see: https://cloud.google.com/bigtable/docs/garbage-collection#restrictions_on_changing_age-based_garbage_collection_policies
```

### Steps to Reproduce

1. Create a replicated bigtable instance with a "max days" retention setting
2. Attempt to add a "version" retention setting (which applies as a union alongside the max days setting)

### Important Factoids

The bigtable instance is replicated.

**Comment by edwardmedia** [comment]
b/288471062

**Comment by glasser** [comment]
It seems like this resource has an odd choice of `id`; wouldn't it make more sense for the `id` to be constructed from the instance, table, and column family names?

**Comment by bonnici** [comment]
The workaround we ended up going with here was removing the garbage collection policy from the terraform state, so the updated policy looked like an "add" rather than a "delete and re-add". The updated policy was then applied in-place in Bigtable.

```
terraform state rm 'module.infrastructure.google_bigtable_gc_policy.xxxxx_data_gc'
```

**Comment by alexeykukuku** [comment]
Hi, the official comment from Cloud Bigatable team:

`max_version` and `max_age` belong to the old way to express GC policy and we intend to eventually deprecate those.

We suggest using `gc_rules`. Currently using `gc_rules` would allow making policy stricter without breaking the replication, but we're also working on a mechanism to allow relaxing the policy if a force-flag is specified (given the fact that it can lead to data inconsistencies between replica clusters).

**Comment by rileykarson** [comment]
Closing based on that conclusion- this should work with `gc_rules`, and supporting the actual lifecycle of gc policies is why that field was introduced.

**Comment by bonnici** [comment]
I have changed our configuration to use `gc_rules` now, but the issue was happening while I was trying to switch from `max_version` to `gc_rules`. It would be good if there was a way to do that cleanly, but I guess there's complications and the workaround will have to do.

**Comment by glasser** [comment]
Are you sure that this doesn't occur with `gc_rules` too? It seemed like any change to the GC policy resulted in the Terraform `id` changing which was enough to cause Terraform to try to delete and re-create.

**Comment by bonnici** [comment]
I'm pretty sure at one point I tried changing gc_rules and it went through without issues. It's a bit hard to test now though because it's a bit of a one-way street due to the fact that it's not possible to relax the GC constraints on a replicated table.

**Comment by rileykarson** [comment]
Here's a plan w/ the same change as the parent, using `gc_rules`:

```
$ terraform apply
google_bigtable_instance.instance: Refreshing state... [id=projects/my-project/instances/tf-instance]
google_bigtable_table.table: Refreshing state... [id=projects/my-project/instances/tf-instance/tables/tf-table]
google_bigtable_gc_policy.policy: Refreshing state... [id=age() > 95d]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_bigtable_gc_policy.policy will be updated in-place
  ~ resource "google_bigtable_gc_policy" "policy" {
      ~ gc_rules        = jsonencode(
          ~ {
              + mode  = "union"
              ~ rules = [
                  ~ {
                      ~ max_age = "95d" -> "2280h"
                    },
                  + {
                      + max_version = 1
                    },
                ]
            }
        )
        id              = "age() > 95d"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_bigtable_gc_policy.policy: Modifying... [id=age() > 95d]
google_bigtable_gc_policy.policy: Modifications complete after 2s [id=(age() > 95d || versions() > 1)]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

(note that 2280h is normalised to 95d by the server and causes a diff on next apply, since we're doing a basic json comparison that isn't aware of the semantic type of `max_age`. should be fine if 95d is written in place of 2280h, though)
