### ISSUE TITLE
How to handle map of maps in terraform if key is not present

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#14958]
How to handle map of maps in terraform if key is not present

I am having a map of maps, and if the key is not present getting below error:

var.mapofmaps is map of map of string with 4 elements
The given key does not identify an element in this collection value

Can you help me how to handle map of maps if key is not present. I also tried with lookup() but it only works for map but not for map of maps.

**Comment by edwardmedia** [comment]
@bptambake do you have a intended config to share? For question like this, I think Terraform core is the better place to get help.

**Comment by bptambake** [comment]
//list of keys leys
keys=[key1,key2,key3,key4,key5,key6,key7]

//map of maps
"map-of-maps":
  {
    "key1":
    {
      "k1": "v1"
    },
    "key3":
    {
      "k3": "v3"
    },
    "key4":
    {
      "k4": "v4"
    },
    "key6":
    {
      "k6": "v6"
    }

  }

i want to Iterate for the keys on this map-of-maps, but few of the key present in keys dont have corresponding value in map-of-maps and it is throwing error.
I need to handle the exception, if the key is not present in map-of-maps, it should return empty.

**Comment by edwardmedia** [comment]
@bptambake can you share your use case?

**Comment by bptambake** [comment]
Hi @edwardmedia 

I was able to handle this case, thanks for the help.
