### ISSUE TITLE
Hi, I'm trying to create a compute instance from the terraform code but its throwing compute.get.zone error even I have the permissions 

### ISSUE THREAD

**Issue by vandana-alyana** [hashicorp/terraform-provider-google#14954]
Hi, I'm trying to create a compute instance from the terraform code but its throwing compute.get.zone error even I have the permissions :
error:│ Error: Error loading zone 'us-central1-a': googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/xxxx/zones/us-central1-a', forbidden

**Comment by edwardmedia** [comment]
@vandana-alyana does the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage) here work for you?

Also, you might want to review Google Provider Configuration Reference, especially [Authentication](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication). Let me know if you still face the issue. When do that, please share your [debug](https://developer.hashicorp.com/terraform/internals/debugging) log.

**Comment by vandana-alyana** [comment]
It's working.
Previously I provided provider block in provider.tf but when I changed it to main.tf file its working.
