### ISSUE TITLE
Unable to use Cloud Identity Group data sources with application default credentials

### ISSUE THREAD

**Issue by g-awmalik** [hashicorp/terraform-provider-google#14972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.69.1
+ provider registry.terraform.io/hashicorp/google-beta v4.69.1

### Affected Resource(s)

data source:
- `google_cloud_identity_groups`

### Terraform Configuration Files

```tf
provider "google" {
  user_project_override = true
  billing_project       = var.project_id
}

data "google_cloud_identity_groups" "groups" {
  parent = "customers/${local.customer_id}"
}
```

### Debug Output

https://gist.github.com/g-awmalik/0b8ebad2fdacc6e9e629147aa993ce8d

### Panic Output

data.google_organization.org[0]: Reading...
data.google_organization.org[0]: Read complete after 1s [id=organizations/684124036889]
data.google_cloud_identity_groups.groups: Reading...
google_cloud_identity_group.group: Refreshing state... [id=groups/0279ka650zvdopx]
data.google_cloud_identity_groups.groups: Read complete after 0s [id=2023-06-23 19:35:15.788660558 +0000 UTC]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error when reading or editing CloudIdentityGroup "groups/0279ka650zvdopx": googleapi: Error 403: Your application is authenticating by using local Application Default Credentials. The cloudidentity.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/764086051850",
│       "service": "cloudidentity.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ 
│   with google_cloud_identity_group.group,
│   on main.tf line 48, in resource "google_cloud_identity_group" "group":
│   48: resource "google_cloud_identity_group" "group" {
│ 

### Expected Behavior

The plan/apply should have been successful with the data source populated.

### Actual Behavior

The plan/apply failed.

What's odd is that the api does succeed [here](https://gist.github.com/g-awmalik/0b8ebad2fdacc6e9e629147aa993ce8d#file-gistfile1-txt-L402) and returns a valid response but the provider seems to panic.

### Steps to Reproduce

1. `terraform apply`

### References

Seems like this was reported previously: https://github.com/hashicorp/terraform-provider-google/issues/8720

**Comment by aebrahim** [comment]
I am having the identical problem with google_apikeys_key

**Comment by ScottSuarez** [comment]
From the logs it looks like you are using two different provider versions

```
2023-06-23T12:33:44.366-0700 [DEBUG] provider.terraform-provider-google_v4.69.1_x5: 
2023-06-23T12:33:44.367-0700 [DEBUG] provider.terraform-provider-google-beta_v4.69.1_x5: 
```

The provider blocks are distinct. Thus each needs their own provider block. Try the following:

```hcl
provider "google" {
  user_project_override = true
  billing_project       = var.project_id
}

provider "google-beta" {
  user_project_override = true
  billing_project       = var.project_id
}
```

**Comment by melinath** [comment]
It seems like this should have worked because user_project_override and billing_project are set.

**Comment by rileykarson** [comment]
Yeah, this looks resolved without further followup indicating that didn't work.
