### ISSUE TITLE
google_compute_router_peer requires peer_ip_address

### ISSUE THREAD

**Issue by per-lind** [hashicorp/terraform-provider-google#14981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/fortinetdev/fortios v1.17.0
+ provider registry.terraform.io/hashicorp/aws v5.5.0
+ provider registry.terraform.io/hashicorp/google v4.70.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/megaport/megaport v0.2.9

### Affected Resource(s)

* google_compute_router_peer 

### Terraform Configuration Files

```tf
resource "google_compute_router_peer" "gcp_1" {
  project                   = "xxx"
  name                      = "gcp-1"
  router                    = data.google_compute_router.vpc-router.name
  region                    = "europe-west1"
  peer_asn                  = 65000
  advertised_route_priority = 100
  interface                 = google_compute_router_interface.gcp_1.name
}
```

### Debug Output

│ Error: Missing required argument
│
│   on vpn.tf line 69, in resource "google_compute_router_peer" "gcp_1":
│   69: resource "google_compute_router_peer" "gcp_1" {
│
│ The argument "peer_ip_address" is required, but no definition was found.

### Expected Behavior

Per the documentation we should be able to create a BGP peer without setting the IP and having gcp pick an address.

[https://cloud.google.com/sdk/gcloud/reference/compute/routers/add-bgp-peer](https://cloud.google.com/sdk/gcloud/reference/compute/routers/add-bgp-peer)

Preferably the cloud router IP and peer IP should be returned after creation so that it easly can be used when creating the other side of the peering.

This command works fine from the CLI `gcloud compute routers add-bgp-peer nat-router --interface=gcp-1 --peer-asn=65000 --peer-name=gcp-1 --region=europe-west1 --project=xxx`

### Actual Behavior

The argument "peer_ip_address" is required, but no definition was found.

### References

It looks like this was added here

* #4692

**Comment by edwardmedia** [comment]
@per-lind is [peer_ip_address](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_peer#peer_ip_address) what  you are looking for?

**Comment by melinath** [comment]
Hm, this is definitely listed as optional in the [gcloud docs](https://cloud.google.com/sdk/gcloud/reference/compute/routers/add-bgp-peer) but it's not listed as optional on the [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/routers). I'll check whether it's actually secretly optional.

**Comment by melinath** [comment]
I can confirm that this is actually optional. Specifically, if the interface does not have `ip_range` set, and the router_peer does not have `ip_address` or `peer_ip_address` set, then default values will be assigned for both `ip_address` and `peer_ip_address` on the server side.
