### ISSUE TITLE
google_alloydb_instance import PRIMARY not work!

### ISSUE THREAD

**Issue by unfeeling91** [hashicorp/terraform-provider-google#14990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.0

### Affected Resource(s)

* google_4.70.0

### Terraform Configuration Files

Example module from GoogleCloudPlatform
```tf
module "alloy-db" {
  source               = "GoogleCloudPlatform/alloy-db/google"
  version              = "~> 0.1"
  project_id           = <PROJECT_ID>
  cluster_id           = "alloydb-cluster-with-primary-instance"
  cluster_location     = "us-central1"
  cluster_labels       = {}
  cluster_display_name = ""
  cluster_initial_user = {
    user     = "<USER_NAME>",
    password = "<PASSWORD>"
  }
  network_self_link = "projects/${project_id}/global/networks/${network_name}"

  automated_backup_policy = null

  primary_instance = {
    instance_id       = "primary-instance",
    instance_type     = "PRIMARY",
    machine_cpu_count = 2,
    database_flags    = {},
    display_name      = "alloydb-primary-instance"
  }
  read_pool_instance = null

  depends_on = [google_compute_network.default, google_compute_global_address.private_ip_alloc, google_service_networking_connection.vpc_connection]
}
```

### Debug Output

Cannot import not exist instance, but the cluster is imported with success status without issue, PRIMARY instance exist in Google Cloud Platform UI

### Expected Behavior

Import success =

### Steps to Reproduce

1. `terraform import`

### References

* #0000

**Comment by edwardmedia** [comment]
@unfeeling91 can you share the import command you used?

**Comment by unfeeling91** [comment]
> @unfeeling91 can you share the import command you used and the debug log?

Hi, sure

`terraform import module.alloy-db.google_alloydb_instance.primary defaultdb/instances/defaultdb`

**Comment by edwardmedia** [comment]
@unfeeling91 As you use the module, it is hard for me to repro .  Have you tried if you can import the resource directly? Import to a module is a little tricky and that is something at the terraform level. 

```
Cannot import not exist instance, but the cluster is imported with success status without issue, PRIMARY instance exist in Google Cloud Platform UI
```

Do you have the import debug log?

**Comment by unfeeling91** [comment]
> @unfeeling91 As you use the module, it is hard for me to repro . Have you tried if you can import the resource directly? Import to a module is a little tricky and that is something at the terraform level.
> 
> ```
> Cannot import not exist instance, but the cluster is imported with success status without issue, PRIMARY instance exist in Google Cloud Platform UI
> ```
> 
> Do you have the import debug log?

Error Cannot import non-existent remote object

While attempting to import an existing object to module.alloy-db.google_alloydb_instance.primary, the provider detects that no object exists with the given id, only pre-existing object can be imported, check that id is correct or use terraform apply to create resource.

Id is correct and the PRIMARY machine exists in the cluster.

**Comment by edwardmedia** [comment]
@unfeeling91 have you tried importing it directly to the resource? How did you create the resource? I have no clue what below id is. Without the solid info, it is hard for me to guess what went wrong

```
terraform import module.alloy-db.google_alloydb_instance.primary defaultdb/instances/defaultdb
```

**Comment by unfeeling91** [comment]
> @unfeeling91 have you tried importing it directly to the resource? How did you create the resource? I have no clue what below id is. Without the solid info, it is hard for me to guess what went wrong
> 
> ```
> terraform import module.alloy-db.google_alloydb_instance.primary defaultdb/instances/defaultdb
> ```

Hi!

defaultdb - id of the cluster, defaultdb - id of PRIMARY instance in UI, cluster resource success imported, but instance resource with an issue that I describe little bit upper.

**Comment by jkkitakita** [comment]
In my case, this worked.

```sh
terraform import google_alloydb_instance.default projects/{{project}}/locations/{{location}}/clusters/{{cluster}}/instances/{{instance_id}}
```

maybe, doc is wrong?
ref. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#import

**Comment by edwardmedia** [comment]
b/289258392

**Comment by unfeeling91** [comment]
> In my case, this worked.
> 
> ```shell
> terraform import google_alloydb_instance.default projects/{{project}}/locations/{{location}}/clusters/{{cluster}}/instances/{{instance_id}}
> ```
> 
> maybe, doc is wrong? ref. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#import

You are a rock! Your variant is working, so the doc is wrong! Thanks a lot!

**Comment by HagaSpa** [comment]
Does the same issue occur when using import block?
