### ISSUE TITLE
Cannot create more than one Firestore index exemption per collection

### ISSUE THREAD

**Issue by and3rson** [hashicorp/terraform-provider-google#14997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.8
on linux_amd64
+ provider registry.terraform.io/elastic/ec v0.4.0
+ provider registry.terraform.io/hashicorp/google v4.71.0
+ provider registry.terraform.io/hashicorp/google-beta v4.71.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.5.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_firestore_field

### Terraform Configuration Files

```tf
locals {
  firestore_index_exemptions = {
    cf_form_templates     = ["createdAt", "updatedAt", "fields"]
    cf_form_template_uses = ["createdAt", "updatedAt"]
    cf_form_instances     = ["createdAt", "updatedAt", "instanceFormData"]
    cf_snippet            = ["createdAt", "updatedAt", "fields"]
    cf_snippet_category   = ["createdAt", "updatedAt"]
  }
  firestore_index_exemptions_flat = flatten([
    for collection_name, field_names in local.firestore_index_exemptions : [
      for field_name in toset(field_names) : {
        collection_name = collection_name
        field_name      = field_name
      }
    ]
  ])
}

resource "google_firestore_field" "firestore_index_exemption" {
  for_each   = { for exemption in local.firestore_index_exemptions_flat : "${exemption.collection_name}__${exemption.field_name}" => exemption }
  provider   = google-beta
  project    = var.app_project_id
  database   = "(default)"
  collection = each.value.collection_name
  field      = each.value.field_name

  index_config {}

  ttl_config {}
}
```

### Expected Behavior

13 index exemptions should be created (5 collections, 2-3 exemptions per collection).

### Actual Behavior

5 index exemptions are created (1 per collection), all other exemptions are timing out in TFE:

![image](https://github.com/hashicorp/terraform-provider-google/assets/190107/c39271e8-66c2-405f-8b01-211e125750f7)

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@and3rson are you able to achieve the expected behavior with other means?

**Comment by and3rson** [comment]
@edwardmedia Yes, I can create the indexes manually in GCP console, it only fails with Terraform.

**Comment by and3rson** [comment]
Update: seems like there's some sort of throttling involved:

> Error: Error creating Field: googleapi: Error 429: Request throttled at the client by AdaptiveThrottler.
with module.customforms.google_firestore_field.firestore_index_exemption["cf_form_templates__updatedAt"]
on .terraform/modules/customforms/terraform/modules/customforms/persistence.tf line 51, in resource "google_firestore_field" "firestore_index_exemption":
> resource "google_firestore_field" "firestore_index_exemption" {

**Comment by and3rson** [comment]
Update 2: seems like TF created TTL policies for all my `google_firestore_field` resources, even though I left `ttl_config` empty:

![image](https://github.com/hashicorp/terraform-provider-google/assets/190107/be319b52-4eb4-4683-8ca4-5a721aab9116)
