### ISSUE TITLE
gcs_fuse_csi_driver_config conflicts with enable_autopilot

### ISSUE THREAD

**Issue by michelka** [hashicorp/terraform-provider-google#15012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.7
+ provider registry.terraform.io/hashicorp/google v4.70.0
+ provider registry.terraform.io/hashicorp/google-beta v4.71.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

Only including the relevant bits: 
```tf
resource "google_container_cluster" "k8s" {
  provider = google-beta 

  enable_autopilot = true

  addons_config {
    gcs_fuse_csi_driver_config {
      enabled = true
    }
  }
}
```

### Debug Output

https://gist.github.com/michelka/e6663b7f69e5ef7d1ecc3a1350602eb0

### Expected Behavior

terraform apply succeeds and creates an GKE with both Autopilot and the fuse csi driver enabled.

### Actual Behavior

terraform apply fails with "Conflicting configuration arguments"

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-google/issues/14515

* #0000

**Comment by edwardmedia** [comment]
@michelka the rule was built in the [code](https://github.com/hashicorp/terraform-provider-google-beta/blob/2e6a2c4eca33cc9b5e1d9ab983dfac028608f17c/google-beta/services/container/resource_container_cluster.go#L446). Are you able to create an autopilot with gcs_fuse_csi_driver_config enabled via other means? I couldn't find a doc that supports that.

**Comment by edwardmedia** [comment]
@michelka is this still an issue?

**Comment by edwardmedia** [comment]
@michelka closing this assuming it is no longer an issue
