### ISSUE TITLE
datasource google_compute_global_address doesn't output prefix length for addresses

### ISSUE THREAD

**Issue by FedeHAL** [hashicorp/terraform-provider-google#15026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.55.0
```

### Affected Resource(s)

data.google_compute_global_address

### Debug Output

```
 +  google_compute_global_address = {
      + address   = "x.x.x.x"
      + id        = "XXXXXX"
      + name      = "google-managed-services"
      + project   = "my-project"
      + self_link = "URL"
      + status    = "RESERVED"
    }
```

### Expected Behavior

Should show prefix length when available, as gcloud command does:

`google-managed-services  x.x.x.x/x   INTERNAL  VPC_PEERING   NETWORK_NAME  RESERVED`

### Actual Behavior

It only shows the address as in the output above

### Steps to Reproduce

```
data "google_compute_global_address" "gcga" {
  name = "my_cga_name"
}

output "test" {
  value = data.google_compute_global_address.gcga
}
```

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/13960

**Comment by edwardmedia** [comment]
@FedeHAL is this still an issue?

**Comment by FedeHAL** [comment]
With 4.60.0 it is fixed. Now it shows the prefix_length. Thanks.

```
data "google_compute_global_address" "project-vpc" {
    address       = "X.X.X.X"
    address_type  = "INTERNAL"
    id            = "projects/project-prod/global/addresses/google-managed-services-project"
    name          = "google-managed-services-project"
    network       = "https://www.googleapis.com/compute/v1/projects/project-prod/global/networks/project"
    network_tier  = "PREMIUM"
    prefix_length = X
    project       = "project-prod"
    purpose       = "VPC_PEERING"
    self_link     = "https://www.googleapis.com/compute/v1/projects/project/global/addresses/google-managed-services-project"
    status        = "RESERVED"
}
```

**Comment by FedeHAL** [comment]
Thanks
