### ISSUE TITLE
GCP sql_database_instance "update" not working as expected

### ISSUE THREAD

**Issue by 180481** [hashicorp/terraform-provider-google#15030]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance

We want to update existing sql instance from auto resize to a static disk-size e.g. 40TB
New SQL instance gets "created" as expected with static size for "new" instance but does not "update" an existing instance.

For example, I created an instance with 40TB below. But when I use terraform to "update" disk to 60TB, it does not update. There is no error message either.

Terraform plan does not show any change if Pipeline shows success but no disk size change.

tier = "db-n1-highmem-8"
disk_autoresize = false
disk_size = 40960

Here is the the partial snippet of main module

resource "google_sql_database_instance" "master" {
  provider             = google-beta
  project              = var.project_id
  name                 = var.random_suffix ? format("%s-%s", lower(var.db_instance_name), random_id.db_name_suffix.hex) : var.db_instance_name
  database_version     = var.database_version
  region               = var.region
  master_instance_name = var.cross_region_replica ? var.master_instance_name : ""
  encryption_key_name  = var.kms_crypto_key == "" ? "" : data.google_kms_crypto_key.my_crypto_key[0].id
  deletion_protection  = var.deletion_protection
  depends_on           = [null_resource.depends_on_module]

  settings {
    tier = var.tier
    // Availability type now supports MYSQL and  POSTGRES
    availability_type = var.availability_type
    backup_configuration {
      backup_retention_settings {
        retained_backups = var.backup_configuration_backup_count
      }
      point_in_time_recovery_enabled = var.backup_configuration_point_in_time_recovery_enabled
      transaction_log_retention_days = var.backup_configuration_transaction_log_retention_days
      location                       = var.backup_configuration_location
      // Binary log isn't supported by postgres
      // MYSQL REGIONAL availability_type requires backup enabled and binary logs to be enabled
      binary_log_enabled = local.is_postgres ? null : local.is_mysql && var.availability_type == "REGIONAL" ? true : var.binary_log_enabled
      enabled            = local.is_mysql && var.availability_type == "REGIONAL" ? true : var.backup_enabled
      start_time         = var.backup_start_time
    }
    ip_configuration {
      // Only one of ipv4_enabled or private_network can be specified
      ipv4_enabled                                  = var.ipv4_enabled
      private_network                               = var.ipv4_enabled == true ? null : data.google_compute_network.private_network.id
      require_ssl                                   = var.require_ssl
      enable_private_path_for_google_cloud_services = var.enable_private_path_for_google_cloud_services
    }
    disk_autoresize = var.disk_autoresize
    disk_size       = var.disk_autoresize == true ? null : var.disk_size
    disk_type       = var.disk_type

}

Below are the output for terraform plan command

Output of Plan during creation of new instance

__________________________________________________________________________________
1st run - disk_autoresize = true - Instance gets created with default disk size
__________________________________________________________________________________

 + settings {
+ activation_policy     = "ALWAYS"
+ availability_type     = "ZONAL"
+ connector_enforcement = (known after apply)
+ disk_autoresize       = true
+ disk_autoresize_limit = 0
+ disk_size             = (known after apply)
+ disk_type             = "PD_SSD"
+ pricing_plan          = "PER_USE"

__________________________________________________________________________________
2nd run - 
disk_autoresize = false
disk_size             = 3049
In this run, other than auto_resize nothing changes
__________________________________________________________________________________

Terraform will perform the following actions:

  # module.cloudsql.google_sql_database_instance.master will be updated in-place
  ~ resource "google_sql_database_instance" "master" {
        id                             = "tfci-disktest-01"
        name                           = "tfci-disktest-01"
        # (14 unchanged attributes hidden)

      ~ settings {
          ~ disk_autoresize             = true -> false
            # (11 unchanged attributes hidden)

            # (11 unchanged blocks hidden)
        }
    }

__________________________________________________________________________________
3rd run - 
disk_autoresize = false
disk_size hardcoded to 3TB
In this run, other than auto_resize nothing changes
__________________________________________________________________________________

~ resource "google_sql_database_instance" "master" {
      id                             = "tfci-disktest-01"
      name                           = "tfci-disktest-01"
      # (14 unchanged attributes hidden)
    ~ settings {
        ~ disk_autoresize             = true -> false
          # (10 unchanged attributes hidden)
          # (11 unchanged blocks hidden)
      }
  }

**Comment by edwardmedia** [comment]
@180481 I can't repro your issue. Below is what the plan I got, and its apply results good. What is the version of the provider you are using? Can you share your debug log so I can take a closer look? 

```
  # google_sql_database_instance.main will be updated in-place
  ~ resource "google_sql_database_instance" "main" {
        id                            = "issue15030"
        name                          = "issue15030"
        # (11 unchanged attributes hidden)

      ~ settings {
          ~ disk_autoresize       = true -> false
          ~ disk_size             = 10 -> 20
            # (8 unchanged attributes hidden)

            # (3 unchanged blocks hidden)
        }
    }
```

**Comment by 180481** [comment]
Provider version - 4.74

[DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.72.0/linux_amd64/terraform-provider-google_v4.72.0_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/google/4.72.0/linux_amd64/terraform-provider-google_v4.72.0_x5]

**Comment by edwardmedia** [comment]
@180481 can you share the debug log that contains all the api requests and responses for the execution of update?

**Comment by edwardmedia** [comment]
@180481 is this still an issue?

**Comment by 180481** [comment]
@edwardmedia Closing this ticket. Issue was due to a lifecycle flag preventing the update so that it does not clash with autoresize. Thank you for the support.
