### ISSUE TITLE
Why do you have 2 buckets created but not used both?

### ISSUE THREAD

**Issue by prensoni0143** [hashicorp/terraform-provider-google#15038]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job

I see that you are creating "Bucket1" and "Bucket2" but then not using them, could you please correct Terraform module that replaces the use of it?

resource "google_storage_bucket" "bucket1" {
    name          = "tf-test-bucket1"
    location      = "US"
    force_destroy = true
}
resource "google_storage_bucket" "bucket2" {
    name          = "tf-test-bucket2"
    location      = "US"
    force_destroy = true
}

**Comment by edwardmedia** [comment]
@prensoni0143 the scripts you see on the doc are also used for the tests. There are `update` tests that use more than one buckets.
