### ISSUE TITLE
Add support for advanced_options_config.user_ip_request_headers to google_compute_security_policy

### ISSUE THREAD

**Issue by felipegc** [hashicorp/terraform-provider-google#15048]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for User-IP in cloud security policy

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "policy" {
  ...
  advanced_options_config {
    ...
    user_ip_request_headers = [
      "True-Client-IP",
    ]
  }
}
```
### References

* [Link to beta API docs](https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies#:~:text=advancedOptionsConfig.userIpRequestHeaders,client%20IP%20address.)

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8267
