### ISSUE TITLE
google_cloud_run_v2_job nested template syntax

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#15046]
# Background

# What kind of contribution is this issue about?
Question/comment

# Details
The new google_cloud_run_v2_job is very difficult to use and maintain due to the nested blocks with the same name "template" that have completely different content.    
It seems like bad programming practice to have different blocks with different content allowed, and be nested, and to give them the same name.  The docs are very hard to read and the code is hard to read and maintain as well.

Interested to hear why these blocks were given the same name and if this can be undone.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#nested_template

**Comment by melinath** [comment]
It looks like this matches the API structure, which we do in order to simplify maintenance of the Terraform resource long-term.
