### ISSUE TITLE
Error reading service account after creation - 403 Halts Execution

### ISSUE THREAD

**Issue by elchead** [hashicorp/terraform-provider-google#15042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Running in Github Runner:

provider.google v4.69.1

### Affected Resource(s)

google_service_account

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
provider "google" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}

resource "google_service_account" "service_account" {
  account_id   = var.service_account_id
  display_name = "Constellation service account"
  description  = "Service account used inside Constellation"
}
....
```

Here is the complete configuration:
https://github.com/edgelesssys/constellation/blob/main/cli/internal/terraform/terraform/iam/gcp/main.tf

### Debug Output
Not yet able to reproduce with debug output, since only happens sporadically.
```
Error: Error reading service account after creation: googleapi: Error 403: Permission 'iam.serviceAccounts.get' denied on resource (or it may not exist).
Details:
[
  ***
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "iam.googleapis.com",
    "metadata": ***
      "permission": "iam.serviceAccounts.get"
    ***,
    "reason": "IAM_PERMISSION_DENIED"
  ***
]
, forbidden

  with google_service_account.service_account,
  on main.tf line 16, in resource "google_service_account" "service_account":
  16: resource "google_service_account" "service_account" ***


Attempting to roll back.
Rollback succeeded.
Error: exit status 1
```

### Expected Behavior

Should create account without error.

### Actual Behavior

Halts due to 403.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Only fails at times, in the CI pipeline. Authentication with GCP is done with Github Action and roles must be correct since it works most of the times. (https://github.com/edgelesssys/constellation/blob/main/.github/actions/login_gcp/action.yml)

Issue is very similar to #10227.

### References

* #10227
* #6758 

b/298050821

b/291928614

**Comment by edwardmedia** [comment]
@elchead I wonder if the api was experiencing difficulties? Do you see this just starting recently, or at the very beginning since the config is used?

**Comment by elchead** [comment]
@edwardmedia We have been having this over many weeks, always sporadically occurring

**Comment by edwardmedia** [comment]
@elchead assume your terraform runner is static and no changes of roles for it. No network issues, right? I can't think another thing on top of mind. @trodge what do you think?

**Comment by elchead** [comment]
Terraform is static (just terraform apply) Our file is actually public: https://github.com/edgelesssys/constellation/blob/main/cli/internal/terraform/terraform/iam/gcp/main.tf

If it was a network issue, I would expect an error message other than 403 no?  Since it only makes a get request and gets a response in this step i think it's not network related.

**Comment by trodge** [comment]
Seems like it could be an API issue.

**Comment by elchead** [comment]
You think it might be a consistency issue? Should I contact Google?

**Comment by zli82016** [comment]
I suppose that the `terraform apply` will be applied for all of the resources in the main.tf file, right?

Is it possible to get logs, which will help to debug the issue?

I wonder if the delay time is not enough and the service account is not ready yet. You can try to make the delay time longer.

**Comment by elchead** [comment]
@zli82016 thanks for looking into it. Yes, we apply it on all resources, without targets.
We are an OSS project, so you can actually see the full-run and config for e.g. :
https://github.com/edgelesssys/constellation/actions/runs/5492357174/jobs/10009776763
and the log, which however doesn't include any hints:
[terraform.log](https://github.com/hashicorp/terraform-provider-google/files/12011585/terraform.log)

However, the error is related to the service account creation itself (see https://github.com/hashicorp/terraform-provider-google/blob/HEAD/google/services/resourcemanager/resource_google_service_account.go#L130-L131)
so it shouldn't have to do with the IAM member resources (ACLs).

**Comment by elchead** [comment]
On this note, I saw that there is actually a polling to wait to solve the eventual consistency problem: 
https://github.com/hashicorp/terraform-provider-google/blob/HEAD/google/services/resourcemanager/resource_google_service_account.go#L135C17-L135C17

Doesn't that make the suggested wait-delay in the official docs superfluous? https://registry.terraform.io/providers/hashicorp/google/4.73.0/docs/resources/google_service_account.html

**Comment by rapar8** [comment]
I'm also facing the same issue 

`Run set export TF_LOG=TRACE
Copying gs://svclyr-terraform-dev/dev-planfile.out to file://./dev-planfile.out
  
....
/home/runner/work/_temp/f0bb6014-195e-4b1c-aa5a-3b742058c96b/terraform-bin apply --auto-approve -input=false dev-planfile.out
module.apis.google_project_service.enable_apis["serviceusage.googleapis.com"]: Creating...
module.apis.google_project_service.enable_apis["containerscanning.googleapis.com"]: Creating...
module.apis.google_project_service.enable_apis["cloudresourcemanager.googleapis.com"]: Creating...
module.apis.google_project_service.enable_apis["artifactregistry.googleapis.com"]: Creating...
module.apis.google_project_service.enable_apis["secretmanager.googleapis.com"]: Creating...
module.apis.google_project_service.enable_apis["serviceusage.googleapis.com"]: Creation complete after 3s [id=***-dev/serviceusage.googleapis.com]
module.apis.google_project_service.enable_apis["artifactregistry.googleapis.com"]: Creation complete after 3s [id=***-dev/artifactregistry.googleapis.com]
module.apis.google_project_service.enable_apis["secretmanager.googleapis.com"]: Creation complete after 3s [id=***-dev/secretmanager.googleapis.com]
module.apis.google_project_service.enable_apis["cloudresourcemanager.googleapis.com"]: Creation complete after 3s [id=***-dev/cloudresourcemanager.googleapis.com]
module.apis.google_project_service.enable_apis["containerscanning.googleapis.com"]: Creation complete after 3s [id=***-dev/containerscanning.googleapis.com]
module.svclyr_service_account.google_service_account.service-account["solace-connector"]: Creating...
module.svclyr_service_account.google_service_account.service-account["cloud-run-deploy"]: Creating...
╷
│ Error: Error reading service account after creation: googleapi: Error [40](https://github.com/ingka-group-digital/omsvclyr/actions/runs/5660341646/job/15336019725#step:12:41)3: Permission 'iam.serviceAccounts.get' denied on resource (or it may not exist).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.serviceAccounts.get"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden
│ 
│   with module.svclyr_service_account.google_service_account.service-account["solace-connector"],
│   on modules/service-account/main.tf line 8, in resource "google_service_account" "service-account":
│    8: resource "google_service_account" "service-account" {
│ 
╵
╷
│ Error: Error reading service account after creation: googleapi: Error 403: Permission 'iam.serviceAccounts.get' denied on resource (or it may not exist).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.serviceAccounts.get"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden
│ 
│   with module.svclyr_service_account.google_service_account.service-account["cloud-run-deploy"],
│   on modules/service-account/main.tf line 8, in resource "google_service_account" "service-account":
│    8: resource "google_service_account" "service-account" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.`

**Comment by rapar8** [comment]
```
svclyr_service_account = {
  "cloud-run-deploy" = {
    type         = "internal"
    name         = "cloud-run-revision"
    display_name = "Cloud Run Revision"
    roles = [
      "roles/iam.serviceAccounts.actAs",
      "roles/iam.serviceAccounts.get",
      "roles/iam.serviceAccounts.list",
      "roles/resourcemanager.projects.get",
      "roles/resourcemanager.projects.list"
    ]
    description = "Terraform - SA - Service account associated with the revision of the service. The service account represents the identity of the running revision, and determines what permissions the revision has"
  },
  "solace-connector" = {
    type         = "internal"
    name         = "solace-rest-cloud-run"
    display_name = "Cloud Run Invoker from Solace Pubsub plus"
    roles = [
      "roles/iam.serviceAccounts.actAs",
      "roles/iam.serviceAccounts.get",
      "roles/iam.serviceAccounts.list",
    "roles/run.invoker"]
    description = "Terraform - SA - used by Solace PubSub Broker to initiate the Cloud Run Rest Request"
  }
}
```

**Comment by elchead** [comment]
@rapar8 we already contacted Google and they are looking into it. Will let you know :)

**Comment by c2thorn** [comment]
Service account creation is eventually consistent. We don't have a great solution, but mitigation in our user guide for SA: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/google_project_service#newly-activated-service-errors

While this is not the most common error we've seen regarding it, due to its seemingly intermittent nature I think it has the same cause. Sleeps/delays and more retries are the only thing we can offer on the Terraform side.

> On this note, I saw that there is actually a polling to wait to solve the eventual consistency problem: [`HEAD`/google/services/resourcemanager/resource_google_service_account.go#L135C17-L135C17](https://github.com/hashicorp/terraform-provider-google/blob/HEAD/google/services/resourcemanager/resource_google_service_account.go?rgh-link-date=2023-07-11T07%3A02%3A48Z#L135C17-L135C17)
> 
> Doesn't that make the suggested wait-delay in the official docs superfluous? [registry.terraform.io/providers/hashicorp/google/4.73.0/docs/resources/google_service_account.html](https://registry.terraform.io/providers/hashicorp/google/4.73.0/docs/resources/google_service_account.html)

The polling waits on 404's, not 403's. We wouldn't want to add retrying on 403's unless we are sure that doing so would be helpful. I see in https://github.com/edgelesssys/constellation/blob/main/cli/internal/terraform/terraform/iam/gcp/main.tf#L25C22-L25C24 that you have a sleep already. I wonder if increasing the time would decrease the frequency of the error?

**Comment by elchead** [comment]
> Service account creation is eventually consistent. We don't have a great solution, but mitigation in our user guide for SA: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/google_project_service#newly-activated-service-errors
> 
> While this is not the most common error we've seen regarding it, due to its seemingly intermittent nature I think it has the same cause. Sleeps/delays and more retries are the only thing we can offer on the Terraform side.
> 
> > On this note, I saw that there is actually a polling to wait to solve the eventual consistency problem: [`HEAD`/google/services/resourcemanager/resource_google_service_account.go#L135C17-L135C17](https://github.com/hashicorp/terraform-provider-google/blob/HEAD/google/services/resourcemanager/resource_google_service_account.go?rgh-link-date=2023-07-11T07%3A02%3A48Z#L135C17-L135C17)
> > Doesn't that make the suggested wait-delay in the official docs superfluous? [registry.terraform.io/providers/hashicorp/google/4.73.0/docs/resources/google_service_account.html](https://registry.terraform.io/providers/hashicorp/google/4.73.0/docs/resources/google_service_account.html)
> 
> @elchead The polling waits on 404's, not 403's. We wouldn't want to add retrying on 403's unless we are sure that doing so would be helpful. I see in https://github.com/edgelesssys/constellation/blob/main/cli/internal/terraform/terraform/iam/gcp/main.tf#L25C22-L25C24 that you have a sleep already. I wonder if increasing the time would decrease the frequency of the error?

I understand that SA creation is eventually consistent, and the consequence it has for consuming that resource (e.g. for assigning IAM roles via `google_project_iam_member`). But Terraform fails during the creation of the SA resource itself and not due to trying to consume it.
So I think that the sleep timer is of no help here, but correct me if I'm wrong.
The GCP support is looking into why it returns `403` in the SA GET request.
Until they have fixed that, tolerating 403 in the poller seems like the only way to fix that as far as I see.

**Comment by elchead** [comment]
@rapar8 did you find a fix? We still don't have any resolution from GCP

**Comment by sbocinec** [comment]
@rapar8  I think in your case the issue might be different as you are incorrectly referring to IAM _permissions_ as _roles_:
```
  roles = [
      "roles/iam.serviceAccounts.actAs",
      "roles/iam.serviceAccounts.get",
      "roles/iam.serviceAccounts.list",
``` 
there are no such roles.

In your case, the following should be used instead:
```
    roles = [
      "roles/iam.serviceAccountUser",
    ]
```

**Comment by sbocinec** [comment]
Another idea is to add a delay the `ServiceAccounts.Get` after the `Create` request is successfully finished as also suggested in the [IAM API doc](https://cloud.google.com/iam/docs/overview#consistency):
> The [IAM API](https://cloud.google.com/iam/docs/reference/rest) is [eventually consistent](https://wikipedia.org/wiki/Eventual_consistency). In other words, if you write data with the IAM API, then immediately read that data, the read operation might return an older version of the data. Also, changes you make might take time to affect access checks.

> This consistency model affects how the IAM API works. **For example, if you create a service account, then immediately refer to that service account in another request, the IAM API might say that the service account could not be found. This behavior occurs because operations are eventually consistent; it can take time for the new service account to become visible to read requests.**

**Comment by rapar8** [comment]
> @rapar8 did you find a fix? We still don't have any resolution from GCP

Yes, I got fix for this issue after lot of searching, using sleep,


```
resource "google_project_iam_member" "iam-member" {
  project = var.project_id
  member  = var.type == "internal" ? "serviceAccount:${lower(var.name)}@${var.project_id}.iam.gserviceaccount.com" : "serviceAccount:${var.name}"
  count   = length(var.roles)
  role    = var.roles[count.index]

  provisioner "local-exec" {
    command = "sleep 20"
  }
```

```
resource "google_service_account" "service_account" {
  for_each = {
    for name, sa in var.service_accounts : name => sa
    if sa.type != "external"
  }
  account_id   = lower(each.value.name)
  display_name = each.value.display_name
  description  = each.value.description

  provisioner "local-exec" {
    command = "sleep 25"
  }
}
```

**Comment by elchead** [comment]
@rileykarson @benhxy 
Unfortunately, the issue is happening again: https://github.com/edgelesssys/constellation/actions/runs/6426995441/job/17452003629#step:3:331
Maybe the retry is not waiting long enough?
We are running v4.83.0 which should have fixed the issue (see file here https://github.com/edgelesssys/constellation/blob/HEAD/cli/internal/terraform/terraform/gcp/main.tf)

**Comment by benhxy** [comment]
@elchead 
1. Is it using the latest version of TF module?
2. How long did it retry before you receive 403 from TF?

**Comment by elchead** [comment]
@benhxy 
1. As stated we are using v4.83 , but I don't see any relevant changes since then (https://github.com/hashicorp/terraform-provider-google/commits/a53c05ab0eb3aef0f36559f3ceca45137684e509/google/services/resourcemanager/resource_google_service_account.go)
2. We have not overwritten the terraform default which should be 120s (https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference)
