### ISSUE TITLE
google_container_cluster monitoring_config enable_components required but documented as optional

### ISSUE THREAD

**Issue by cen1** [hashicorp/terraform-provider-google#15056]
`monitoring_config` `enable_components` field is supposed to be optional as per documentation but is required when running terraform. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

### Terraform Version

0.12.31

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke" {
  # ...
  monitoring_config {
    managed_prometheus {
      enabled = var.cluster_monitoring_enabled
  }
}
```

### Plan Output

```
Error: Missing required argument

  on ../../../../modules/kubernetes/gke/gke.tf line 23, in resource "google_container_cluster" "gke":
  23:   monitoring_config {

The argument "enable_components" is required, but no definition was found.
```

**Comment by edwardmedia** [comment]
From the [api](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#loggingcomponentconfig) doc, it says 

```
enableComponents[] | enum (Component)Select components to collect logs. An empty set would disable all logging.
```

**Comment by edwardmedia** [comment]
@cen1 can you provide `enable_components = []` explicitly if you want to disable all logging? 

```tf
resource "google_container_cluster" "primary" {
  name               = "mycluster"
  location           = "us-central1-a"
  initial_node_count = 1
  monitoring_config {
	     enable_components = []
         managed_prometheus {
                enabled = true
         }
  }
}
```

**Comment by cen1** [comment]
I can try that but the core of the issue is to either correct the documentation or make it optional. The difference must have appeared semi-recently because we did not specify this attribute when deploying our cluster roughly a year ago.

**Comment by edwardmedia** [comment]
@cen1 it looks like changing is coming. `enable_components` is optional in the [beta](https://github.com/hashicorp/terraform-provider-google-beta/blob/87ec6f96a13dc4ff7f8323fb9e51feed77dcf022/google-beta/services/container/resource_container_cluster.go#L1111). Can you try it?

**Comment by cen1** [comment]
Ah that might actually make sense, I think we used the beta provider in the initial deploy.

**Comment by edwardmedia** [comment]
@cen1 I have already opened above PR that will make optional for GA. Before it is available, you can use the beta for the feature, I think.
