### ISSUE TITLE
Terraformer error importing google_comput_instance with terraform-provider-google

### ISSUE THREAD

**Issue by Kavuti** [hashicorp/terraform-provider-google#15059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.13.6

### Affected Resource(s)
I'm actually using Terraformer to import a manually created instance.

* google_compute_instance

### Terraform Configuration Files
providers.tf
```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.72.0"
    }
  }
  required_version = ">= 0.13"
}

provider "google" {
  project = "geometric-orbit-387800"
  region  = "europe-west1"
}
```

### Panic Output
https://gist.github.com/Kavuti/7fb0b2dfbe375a7830aa27e93eb6e359

### Expected Behavior
I would expect that Terraformer would import correctly the compute instance.

### Actual Behavior
Terraformer returns an error in the logs and declares that it should be reported to the provider developer.

### Steps to Reproduce

1. `tfenv use 0.13.6`
2. `terraformer import google --resources=instances --regions=your-region --projects=your-project`

**Comment by edwardmedia** [comment]
@Kavuti where did you see below command? [Here](https://cloud.google.com/docs/terraform/resource-management/import) are some methods I would follow.

```
terraformer import google --resources=instances --regions=your-region --projects=your-project
```

**Comment by edwardmedia** [comment]
@Kavuti Oh, I guess you were talking about [this](https://github.com/GoogleCloudPlatform/terraformer)? That is a separate repo. Yeah, I have little experience with that.  What we are concerned about is [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#import). If you see its functionality failure, here is the place. For `terraformer`, you may go to its repo to report issues. Does this make sense?

**Comment by Kavuti** [comment]
I would normally agree with you, but look at the lines 23-33 of the attached logs:
```
2023-07-06T11:19:16.688+0200 [ERROR] plugin.terraform-provider-google_v4.72.0_x5: Response contains error diagnostic: diagnostic_severity=ERROR tf_proto_version=5.3 tf_req_id=1349bcf0-f9e2-b2ac-3b36-c25d836462a6 tf_rpc=Configure diagnostic_attribute="" tf_provider_addr=registry.terraform.io/hashicorp/google @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto
  diagnostic_detail=
  | An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
  | 
  | Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
  | 
  | Path: 
  | Target Type: fwmodels.ProviderModel
  | Suggested `types` Type: basetypes.ObjectValue
  | Suggested Pointer Type: *fwmodels.ProviderModel
   diagnostic_summary="Value Conversion Error" timestamp="2023-07-06T11:19:16.687+0200"
```
The tool informs that the error it encounters is relatable to the provider more than the tool itself.
I tested the behavior also with the 4.68.0 of the provider and the error is the same.

**Comment by edwardmedia** [comment]
@Kavuti can you share the config you used for your testing?

**Comment by edwardmedia** [comment]
@Kavuti is this still an issue?

**Comment by edwardmedia** [comment]
@Kavuti closing this assuming it is no longer an issue.

**Comment by koi8** [comment]
The issue still exists. I was trying to downgrade versions of terraformer and nothing changes. The only thing is changed for me - google cloud provider got upgraded.
