### ISSUE TITLE
Promote SWP and related resources to TPG(G.A)

### ISSUE THREAD

**Issue by felipegc** [hashicorp/terraform-provider-google#15067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Make the SWP and related resources available in TPG(G.A):
- google_network_services_gateway
- google_network_security_url_lists
- google_network_security_gateway_security_policy
- google_network_security_gateway_security_policy_rule

obs: google_network_security_tls_inspection_policy is not being promoted to G.A yet because of the dependency with google_project_service_identity cannot be promoted yet.

### New or Affected Resource(s)

* google_network_services_gateway
* google_network_security_url_lists
* google_network_security_gateway_security_policy
* google_network_security_gateway_security_policy_rule

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by roaks3** [comment]
This appears to be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/8279
