### ISSUE TITLE
Support use of Private Service Connect endpoint in GKE google_container_cluster resource

### ISSUE THREAD

**Issue by ncapps** [hashicorp/terraform-provider-google#15064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Creating a VPC network peering connection between the cluster VPC and the control plane VPC is not allowed in some enterprise uses cases. An alternative solution is connect the cluster VPC and control plane VPC using a Private Service Connect (PSC) endpoint.

The Terraform resource, `google_container_cluster`, should allow creating a private cluster without specifying the `master_ipv4_cidr_block`. This use case is supported with the `gcloud container clusters create` command.

```bash
gcloud container clusters create private-cluster \
    --enable-master-authorized-networks \
    --enable-ip-alias \
    --enable-private-nodes \
    --enable-private-endpoint \
    --network="shared-vpc" \
    --subnetwork="shared-vpc-subnet" \
    --private-endpoint-subnetwork="shared-vpc-subnet-nodes"
```

Using Terraraform, we currently cannot create a private cluster without providing a value for `master_ipv4_cidr_block`.

This configuration results in a Terraform build phase error.

```tf
private_cluster_config {
    enable_private_endpoint     = true
    enable_private_nodes        = true
    private_endpoint_subnetwork = "projects/project-id/regions/region/subnetworks/shared-vpc-subnet-nodes"
}
```

Error message: 
```bash
module.kubernetes-engine.google_container_cluster.cluster: Creating...
╷
│ Error: master_ipv4_cidr_block must be set if enable_private_nodes is true
```

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

- Add support for creating a private cluster (standard) that utilizes Private Service Connect endpoints to connect the cluster VPC with the control plane VPC.

```tf
resource "google_container_cluster" "cluster" {
...
    private_cluster_config {
        enable_private_endpoint     = true
        enable_private_nodes        = true
        private_endpoint_subnetwork = "projects/project-id/regions/region/subnetworks/shared-vpc-subnet-nodes"
    }
}
```

### References

* b/290344299

**Comment by ncapps** [comment]
I will work on a fix for this issue.

**Comment by sanmaym** [comment]
@ncapps @rileykarson Can I get some clarification on this PR ? Are you trying to create a GKE cluster with private nodes which operates with PSC instead of VPC Peering? Is that possible today? My understanding was that its only supported for public GKE clusters and GKE cluster with private nodes was not supported yet

**Comment by ncapps** [comment]
Hi @sanmaym, Yes - we are creating GKE clusters with private nodes that use PSC. We have been using this configuration for over a year now. We needed to provision and manage the clusters using `gcloud` until this change was applied to the Google Terraform provider.
