### ISSUE TITLE
Creating memcache instance fails: API does not receive quota-project from ADC while polling for existing instance.

### ISSUE THREAD

**Issue by nfgrep** [hashicorp/terraform-provider-google#15066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.72.1
+ provider registry.terraform.io/hashicorp/google-beta v4.72.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```
### Affected Resource(s)

* google_memcache_instance

### Terraform Configuration Files

```tf
resource "google_memcache_instance" "memcache" {
  name = var.memcache_name
  project = var.project_id
  region = var.region
  authorized_network = var.authorized_network_id

  node_config {
    cpu_count      = 1
    memory_size_mb = 1024
  }

  node_count = 1
  memcache_version = "MEMCACHE_1_5"

  maintenance_policy {
    weekly_maintenance_window {
      day      = "SATURDAY"
      duration = "14400s" # 4 hours
      start_time {
        hours = 0
        minutes = 30
        seconds = 0
        nanos = 0
      }
    }
  }

  depends_on = [google_project_service.memcache]
}
```

### Debug Output

https://gist.github.com/nfgrep/475cc62d134dda9f5674d3c5f53ce03c

### Expected Behavior

A memcache instance is created and stored in the tfstate 

### Actual Behavior

A memcache instance gets created, but the provider fails when polling for its existence, and never loads it into tfstate:
```
│ Error: Error waiting to create Instance: Error waiting for Creating Instance: error while retrieving operation: googleapi: Error 403: Your application is authenticating by using local Application Default Credentials. The memcache.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/764086051850",
│       "service": "memcache.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]

```
 This leaves re-runs of `terraform apply` to error with "409: already exists", and a manual `terraform import` is required.

### Steps to Reproduce

1. Define a memcache instance in terraform
2. Run `gcloud auth application-default login --project <your-project-id-here>`
4. Run `terraform apply` 

### Important Factoids

- Authenticated as a user, as per [the official instructions](https://registry.terraform.io/providers/wiardvanrij/ipv4google/latest/docs/guides/provider_reference#running-terraform-on-your-workstation)
- Hitting the "operations" endpoint via `gcloud` works (I assume its sending raw user creds, not ADC) [1]
- Hitting the "operations" endpoint via `curl` manually only works with ADC if the `x-goog-user-project` header is set [2]
- Many other APIs seem to work fine [3]
- I've set `billing_project = <my-project>` and `user_project_override = true` 

### References

[1] `gcloud memcache operations describe operation-1688666352108-5ffd5460fc33b-66afd647-045805a6  --project shopify-nathan-prodk-1b1c0385 --region us-central1`

[2] 
This fails
```
curl -X GET \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://memcache.googleapis.com/v1/projects/shopify-nathan-prodk-1b1c0385/locations/us-central1/operations/operation-1688666352108-5ffd5460fc33b-66afd647-045805a6?alt=json"
```

This succeeds:
```
curl -X GET \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    -H "x-goog-user-project: shopify-nathan-prodk-1b1c0385" \
    "https://memcache.googleapis.com/v1/projects/shopify-nathan-prodk-1b1c0385/locations/us-central1/operations/operation-1688666352108-5ffd5460fc33b-66afd647-045805a6?alt=json"
```

[3]
The redis API "operations" endpoint seems to work fine. This succeeds:
```
curl -X GET \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://redis.googleapis.com/v1/projects/shopify-nathan-prodk-1b1c0385/locations/us-central1/operations/operation-1688661871446-5ffd43afe49f6-42b86d7e-8bc83923?alt=json"
```

**Comment by rileykarson** [comment]
Failing on [2] indicates that this probably isn't a Terraform-specific problem, since that should have worked. Does running https://cloud.google.com/sdk/gcloud/reference/auth/application-default/set-quota-project change anything with either Terraform or curl?

For https://cloud.google.com/docs/authentication/troubleshoot-adc#user-creds-client-based, #2 the Terraform-level quota management configuration values are also an option: https://cloud.google.com/docs/authentication/troubleshoot-adc#user-creds-client-based

**Comment by nfgrep** [comment]
Thank you for the swift response!

>Failing on [2] indicates that this probably isn't a Terraform-specific problem, since that should have worked.

I assumed google might be moving towards requiring that `x-goog-user-project` header, and that the terraform provider might need to do so. Otherwise you're right, this could be an issue with the API itself. Or ofc it could be human error on my side that I can't see yet. 

> Does running https://cloud.google.com/sdk/gcloud/reference/auth/application-default/set-quota-project change anything with either Terraform or curl?

Running `gcloud auth application-default set-quota-project <my-project>` doesn't change the results of `curl` or `terraform`. They both still error with "403 SERVICE_DISABLED".

> For https://cloud.google.com/docs/authentication/troubleshoot-adc#user-creds-client-based, https://github.com/hashicorp/terraform-provider-google/pull/2 the Terraform-level quota management configuration values are also an option: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#quota-management-configuration

I've already set both `billing_project = <my-project>` and `user_project_override = true` in terraform. Though those definitions are in a module, and perhaps not being loaded in time? I'll try a `depends_on [module.providers]` and see if that ensures the config gets loaded and solves my problem.

**Comment by rileykarson** [comment]
> I assumed google might be moving towards requiring that x-goog-user-project header, and that the terraform provider might need to do so.

Some APIs require it, which is what `user_project_override` and `billing_project` enable in Terraform!

> I've already set both billing_project = <my-project> and user_project_override = true in terraform. Though those definitions are in a module, and perhaps not being loaded in time? I'll try a depends_on [module.providers] and see if that ensures the config gets loaded and solves my problem.

I don't think that works, provider configuration values can flow _down_ from the root configuration into modules instantiated in the root (and from child modules into their children in nested configurations) (https://developer.hashicorp.com/terraform/language/modules/develop/providers#implicit-provider-inheritance), but not _up_ from a module into the root (or parent, in a nested context) configuration.

Can you try using the Terraform values with provider blocks (keeping in mind that `google-beta` needs to be configured separately) at the root level?

**Comment by nfgrep** [comment]
> I don't think that works, provider configuration values can flow down from the root configuration into modules instantiated in the root (and from child modules into their children in nested configurations) (https://developer.hashicorp.com/terraform/language/modules/develop/providers#implicit-provider-inheritance), but not up from a module into the root (or parent, in a nested context) configuration.

Oh... yea this is smelling like human error on my side, let me verify here...

> Can you try using the Terraform values with provider blocks (keeping in mind that google-beta needs to be configured separately) at the root level?

Yup that did the trick 🤦, so sorry to waste your time, and thank you for holding my hand here! 😅

**Comment by rileykarson** [comment]
Np! Closing out since the ADC issue doesn't seem to be Terraform-related given it can be replicated in curl and quota projects are supported in provider configuration, which resolve the error.
