### ISSUE TITLE
container_cluster support external BQ dataset

### ISSUE THREAD

**Issue by NissesSenap** [hashicorp/terraform-provider-google#15072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

So my guess is that this is a limitation in the API and not in the TF provider, but If I'm wrong it's probably rather easy to solve.
Using `resource_usage_export_config` in `google_container_cluster` I would like to send my data, to a dataset located in another project.

Writing

```.tf
      + resource_usage_export_config {
          + enable_network_egress_metering       = false
          + enable_resource_consumption_metering = true

          + bigquery_destination {
              + dataset_id = "my_other_project.gke_usage_metering"
            }
        }
``` 

Will give me the following error:

```shell
╷
│ Error: googleapi: Error 400: Bigquery_destination.dataset_id must be alphanumeric (plus underscores).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0x2fce1cfe2d676e9"
│   }
│ ]
│ , badRequest
│ 
│   with module.gke_blue.module.gke.google_container_cluster.primary,
│   on .terraform/modules/gke_blue.gke/modules/beta-private-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
│   22: resource "google_container_cluster" "primary" {
│ 
```

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```.tf
resource_usage_export_config {
  enable_network_egress_metering = false
  enable_resource_consumption_metering = true

  bigquery_destination {
    project_id = "my_other_project"
    dataset_id = "cluster_resource_usage"
  }
}
```

**Comment by rileykarson** [comment]
This error (`googleapi: Error 400: Bigquery_destination.dataset_id must be alphanumeric (plus underscores).`) is coming from the API, so the restriction seems to come from there! Let us know if this works in gcloud and/or the Console though, and we'll reopen.
