### ISSUE TITLE
Failing test(s): TestAccTags, TestAccTagsLocationTagBinding_locationTagBindingzonal + other tests using tags

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15078]
### Failure rates

- 33% since 2023-06-22 (TestAccTagsLocationTagBinding_locationTagBindingzonal)
- 21% since 2023-06-16  (TestAccTags)
- 29% since 2023-06-17  (TestAccComputeInstance_resourceManagerTags (TPGB))

### Impacted tests

- TestAccTagsLocationTagBinding_locationTagBindingzonal
- TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten
- TestAccTags
- TestAccComputeInstance_resourceManagerTags (TPGB)
- TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydbExample
- TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten

### Affected Resource(s)

* google_tags_tag_value

### Nightly build test history

- [Link - TestAccTagsLocationTagBinding_locationTagBindingzonal](https://ci-oss.hashicorp.engineering/test/7888771310400281422?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A414370%29%2Cid%3A2000002331)
- [ Link - TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten](https://ci-oss.hashicorp.engineering/test/-1848297138890150638?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A414370%29%2Cid%3A2000001229)
- [Link - TestAccTags](https://ci-oss.hashicorp.engineering/test/-499758186072444002?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A410610%29%2Cid%3A272811)
- [Link - TestAccComputeInstance_resourceManagerTags (TPGB)
](https://ci-oss.hashicorp.engineering/test/1545566099228307524?currentProjectId=GoogleCloudBeta&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccTagsLocationTagBinding_locationTagBindingzonal
=== PAUSE TestAccTagsLocationTagBinding_locationTagBindingzonal
=== CONT  TestAccTagsLocationTagBinding_locationTagBindingzonal
    vcr_utils.go:152: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_tags_tag_value.value will be updated in-place
          ~ resource "google_tags_tag_value" "value" {
              + description     = "For foo8slsa3fmyq resources."
                id              = "tagValues/281478355093968"
                name            = "281478355093968"
                # (5 unchanged attributes hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccTagsLocationTagBinding_locationTagBindingzonal (92.19s)
FAIL

```

b/305278126

**Comment by SarahFrench** [comment]
Here's the [config code in the test that sets the description](https://github.com/hashicorp/terraform-provider-google/blob/19493c79c9fda5ba6e61ea4daf245622d6dce850/google/resource_tags_test.go#L955).

**Comment by melinath** [comment]
Looks like this error is no longer occurring.
