### ISSUE TITLE
Attempt to recreate imported org_policy_policy

### ISSUE THREAD

**Issue by zhalas** [hashicorp/terraform-provider-google#15070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.72.1
```

### Affected Resource(s)

* google_org_policy_policy

### Terraform Configuration Files

```tf
locals {
  project_id = "PROJECT_ID"
  sa         = "test@${local.project_id}.iam.gserviceaccount.com"
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.72.1"
    }
  }
}

provider "google" {
  project               = local.project_id
  billing_project       = local.project_id
  user_project_override = true
}

resource "google_project_service" "orgpolicy_api" {
  service = "orgpolicy.googleapis.com"
  project = local.project_id
}


resource "google_org_policy_policy" "service_account_credential_lifetime_extension" {
  name = "projects/${local.project_id}/policies/iam.allowServiceAccountCredentialLifetimeExtension"
  #name   = "iam.allowServiceAccountCredentialLifetimeExtension"
  parent = "projects/${local.project_id}"

  spec {
    inherit_from_parent = true
    reset               = false
    rules {
      values {
        denied_values  = []
        allowed_values = [local.sa]
      }
    }
  }

  depends_on = [google_project_service.orgpolicy_api]
}

```

### Expected Behavior

After importing an existing policy that is exactly the same as the declared policy subsequent plan should show not changes.

### Actual Behavior

After importing an existing policy that is exactly the same as the declared policy Terraform tries to replace the policy due to name change:
```tf
  # google_org_policy_policy.service_account_credential_lifetime_extension must be replaced
-/+ resource "google_org_policy_policy" "service_account_credential_lifetime_extension" {
      ~ id     = "projects/PROJECT_ID/policies/iam.allowServiceAccountCredentialLifetimeExtension" -> (known after apply)
      ~ name   = "iam.allowServiceAccountCredentialLifetimeExtension" -> "projects/PROJECT_ID/policies/iam.allowServiceAccountCredentialLifetimeExtension" # forces replacement
        # (1 unchanged attribute hidden)

      ~ spec {
          ~ etag                = "COGynaUGELj9wdkB" -> (known after apply)
          ~ update_time         = "2023-07-07T00:16:33.456163Z" -> (known after apply)
            # (2 unchanged attributes hidden)

          ~ rules {

                # (1 unchanged block hidden)
            }
        }

      - timeouts {}
    }

```

### Steps to Reproduce

1. `terraform apply`
2. `terraform state rm google_org_policy_policy.service_account_credential_lifetime_extension`
3. `terraform import google_org_policy_policy.service_account_credential_lifetime_extension projects/PROJECT_ID/policies/iam.allowServiceAccountCredentialLifetimeExtension`
4. `terraform plan`

Instead of creating the policy via Terraform and removing it from the state in steps 1 and 2 the equivalent policy could as well be created in the GCP Console.

### Important Factoids

Contrary to what documentation says about the name format:

> [name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/org_policy_policy#name) - (Required) Immutable. The resource name of the Policy. Must be one of the following forms, where constraint_name is the name of the constraint which this Policy configures: * projects/{project_number}/policies/{constraint_name} * folders/{folder_id}/policies/{constraint_name} * organizations/{organization_id}/policies/{constraint_name} For example, "projects/123/policies/compute.disableSerialPortAccess". Note: projects/{project_id}/policies/{constraint_name} is also an acceptable name for API requests, but responses will return the name using the equivalent project number.

Using the `iam.allowServiceAccountCredentialLifetimeExtension` as the name (commented out in the example) actually works and does not cause the problem.

**Comment by edwardmedia** [comment]
I do see the difference for `name` in the states from apply and import. Below the first one is from import and the other is from apply. We better bring the one from import to match the one from the other. 

``` 
          "attributes": {
            "id": "projects/issue15070/policies/compute.vmExternalIpAccess",
            "name": "compute.vmExternalIpAccess",
            "parent": "projects/issue15070",
            "spec": [
              {
              }
            ]
          }
```

```
          "attributes": {
            "id": "projects/issue15070/policies/compute.vmExternalIpAccess",
            "name": "projects/issue15070/policies/compute.vmExternalIpAccess",
            "parent": "projects/issue15070",
            "spec": [
              {
              }
            ]
          }
```
