### ISSUE TITLE
Failing test(s): TestAccContainerCluster_updateVersion

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15084]
### Failure rates

- 100% since 2023-06-14

### Impacted tests

- TestAccContainerCluster_updateVersion

### Affected Resource(s)

* google_container_cluster

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/test/7740653715440869487?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccContainerCluster_updateVersion
=== PAUSE TestAccContainerCluster_updateVersion
=== CONT  TestAccContainerCluster_updateVersion
    vcr_utils.go:152: Step 3/4 error: Error running apply: exit status 1
        Error: googleapi: Error 400: Master version must be one of "STABLE" channel supported versions [1.21.14-gke.18800, 1.22.17-gke.12700, 1.23.17-gke.5600, 1.24.12-gke.1000, 1.24.13-gke.2500, 1.24.14-gke.1200, 1.25.8-gke.1000, 1.25.9-gke.2300, 1.26.5-gke.1200].
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "0x91231d41efd4b1e7"
          }
        ]
        , badRequest
          with google_container_cluster.with_version,
          on terraform_plugin_test.tf line 6, in resource "google_container_cluster" "with_version":
           6: resource "google_container_cluster" "with_version" {
--- FAIL: TestAccContainerCluster_updateVersion (544.19s)
FAIL
```

b/291748544

**Comment by melinath** [comment]
New error message:

```
Error: googleapi: Error 400: A cluster enrolled in a release channel may only use patch versions from a newer channel if the minor version in the newer channel is the same as a minor version available in the cluster's own release channel. To upgrade a cluster to a patch version from a newer release channel, ensure that the current control plane patch version and the desired control plane patch version have matching minor versions (for example, 1.22.1-gke.400 -> 1.22.4-gke.1500). For more information, refer to the documentation: https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#newer-patch-versions
```

**Comment by melinath** [comment]
It looks like the API does include a breakdown of versions by channel: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/ServerConfig#ReleaseChannelConfig However, we don't expose that in the [`google_container_engine_versions`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_engine_versions) datasource.

I don't know that the list of versions for a particular channel would be particularly useful for most users. The contributor who added support for the latest version for each channel [ran into issues](https://github.com/GoogleCloudPlatform/magic-modules/pull/6746#pullrequestreview-1228069074) making the entire list available, but we could do it if we think it's worthwhile. That said, I think it would be reasonable for this test to just call the endpoint directly and pass the appropriate values in the test context.

**Comment by trodge** [comment]
If the test calls the endpoint directly, how would we make that work with VCR?

**Comment by melinath** [comment]
Good point. It wouldn't work with VCR - I guess that would result in the test re-recording any time the latest version changes? That might be acceptable, though, unless it would cause other problems? A data source change would probably be preferable (and _would_ work with VCR) but would be more effort.
