### ISSUE TITLE
Service Account change in google_bigquery_data_transfer_config does nothing

### ISSUE THREAD

**Issue by giulianobr** [hashicorp/terraform-provider-google#15080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

As described [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/8152) after the fix of #14123 even after apply the TF code, the Service Account is not changing.

b/291652491

**Comment by giulianobr** [comment]
Opened a new ticket @zli82016 Thanks!

**Comment by edwardmedia** [comment]
@trodge you were on https://github.com/hashicorp/terraform-provider-google/issues/14123

**Comment by zli82016** [comment]
Please see more details how to fix the issue in the comment https://github.com/GoogleCloudPlatform/magic-modules/pull/8247#issuecomment-1615264797

**Comment by obada-ab** [comment]
Currently trying to fix this, added a comment here: https://github.com/GoogleCloudPlatform/magic-modules/pull/8247#issuecomment-1643761929
