### ISSUE TITLE
Storage Transfer Agent Pool permission error when caller is project Owner

### ISSUE THREAD

**Issue by CaliWee** [hashicorp/terraform-provider-google#15087]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.72.1
+ provider registry.terraform.io/hashicorp/google-beta v4.72.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
```
### Affected Resource(s)

* google_storage_transfer_agent_pool

### Terraform Configuration Files

```tf
data "google_storage_transfer_project_service_account" "default" {
  project = module.gcp-project.project_id
}

resource "google_project_iam_member" "storage_transfer_pubsub_editor_role" {
  project = module.gcp-project.project_id
  role    = "roles/pubsub.editor"
  member  = data.google_storage_transfer_project_service_account.default.member
}

resource "google_project_iam_member" "storage_transfer_storage_admin" {
  project = module.gcp-project.project_id
  role    = "roles/storage.admin"
  member  = data.google_storage_transfer_project_service_account.default.member
}


# TODO: this fails with a permissions error despite the caller being a project Owner
#  For the sake of time, I am creating manually and will revisit later.
resource "google_storage_transfer_agent_pool" "ml_preclin_transfer_manifest" {
  name         = "mlpreclin_nfs_transfer_pool"
  display_name = "Clusterbuddy transfer to GCS"
  bandwidth_limit {
    limit_mbps = "250"
  }

  depends_on = [google_project_iam_member.storage_transfer_pubsub_editor_role]
}
```

### Debug Output

https://gist.github.com/CaliWee/95db311956be7315af2acd3a9c669479

### Panic Output

NA

### Expected Behavior

A storage transfer agent pool should have been created

### Actual Behavior

A 403 permission denied error

### Steps to Reproduce

1.  Give the caller the Owner role in a project
2. `terraform apply` the above configuration

### Important Factoids

Authenticating as the service account and using the `gcloud` cli to create the same resource succeeds - 
```
$ gcloud auth activate-service-account ********
 Activated service account credentials for: [*****@******.iam.gserviceaccount.com]

$ gcloud transfer agent-pools create mlpreclin_nfs_transfer_pool \
  --no-async \ 
  --bandwidth-limit=250 \ 
  --display-name="Clusterbuddy transfer to GCS" 

Waiting for backend to create agent pool...done.                                                                                                                                                                                       
bandwidthLimit:
  limitMbps: '250'
displayName: Clusterbuddy transfer to GCS
name: projects/calico-preclinical-imaging-03/agentPools/mlpreclin_nfs_transfer_pool
state: CREATED

```
### References

I was not able to find any related GitHub issues

**Comment by edwardmedia** [comment]
@CaliWee can you provide `project` in the config?

```tf
resource "google_storage_transfer_agent_pool" "ml_preclin_transfer_manifest" {
  project =     <---- value needed here 
  name         = "mlpreclin_nfs_transfer_pool"
  display_name = "Clusterbuddy transfer to GCS"
  bandwidth_limit {
    limit_mbps = "250"
  }

  depends_on = [google_project_iam_member.storage_transfer_pubsub_editor_role]
}
```

**Comment by CaliWee** [comment]
![facepalm_st](https://github.com/hashicorp/terraform-provider-google/assets/109993230/1c1425d2-720d-459e-9ee3-a8e3b9c9c511)
Oof, that was it. Thank you and sorry!
