### ISSUE TITLE
Failing test(s): TestAccCloudRunService_cloudRunServiceSqlExample

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15081]
### Failure rates

- 100% since 2023-06-07

### Impacted tests

- TestAccCloudRunService_cloudRunServiceSqlExample
- TestAccCloudRunService_cloudRunServiceMulticontainerExample (BETA)

### Affected Resource(s)

* google_cloud_run_service

### Nightly build test history

- [TestAccCloudRunService_cloudRunServiceSqlExample](https://ci-oss.hashicorp.engineering/test/6583712081356590594?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true)
- [TestAccCloudRunService_cloudRunServiceMulticontainerExample](https://ci-oss.hashicorp.engineering/test/5509781408798692485?currentProjectId=GoogleCloudBeta&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccCloudRunService_cloudRunServiceSqlExample
=== PAUSE TestAccCloudRunService_cloudRunServiceSqlExample
=== CONT  TestAccCloudRunService_cloudRunServiceSqlExample
    vcr_utils.go:148: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_cloud_run_service.default will be updated in-place
          ~ resource "google_cloud_run_service" "default" {
                id                         = "locations/us-central1/namespaces/PROJECT_ID/services/tf-test-cloudrun-srv4skghfnu3f"
                name                       = "tf-test-cloudrun-srv4skghfnu3f"
                # (4 unchanged attributes hidden)
              ~ template {
                  ~ metadata {
                      ~ labels      = {
                          - "run.googleapis.com/startupProbeType" = "Default" -> null
                        }
                        # (2 unchanged attributes hidden)
                    }
                  ~ spec {
                        # (3 unchanged attributes hidden)
                      ~ containers {
                          + args    = []
                          + command = []
                            # (1 unchanged attribute hidden)
                            # (3 unchanged blocks hidden)
                        }
                    }
                }
                # (2 unchanged blocks hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccCloudRunService_cloudRunServiceSqlExample (936.70s)
FAIL
```

b/291749113

**Comment by SarahFrench** [comment]
The [commit history for the google_cloud_run_service resource](https://github.com/hashicorp/terraform-provider-google/commits/main/google/services/cloudrun/resource_cloud_run_service.go) doesn't show any obvious cause for this change, maybe it was an API-side change.

**Comment by yanweiguo** [comment]
`spec.template.metadata` has `default_from_api: true` set: https://github.com/GoogleCloudPlatform/magic-modules/blob/4d202133977a4d658f1f2bb94b6a4bda84c60d6f/mmv1/products/cloudrun/Service.yaml#L240

Why are diffs in `spec.template.metadata.labels` not ignored?

**Comment by melinath** [comment]
@yanweiguo default_from_api is not "inherited" - even if `spec.template.metadata` is `default_from_api: true`, subfields would also need that to be set.

**Comment by yanweiguo** [comment]
> @yanweiguo default_from_api is not "inherited" - even if `spec.template.metadata` is `default_from_api: true`, subfields would also need that to be set.

Good to know that. Thanks.
