### ISSUE TITLE
Implement `gcloud privateca certificates create` within a resource.

### ISSUE THREAD

**Issue by logston** [hashicorp/terraform-provider-google#15102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The provider does not seem to support having the CA Service create a private and public key for you. Eg. 

```
gcloud privateca certificates create \
  --issuer-pool=POOL_ID \
  --ca=ROOT_CA_ID \
  --generate-key \
  --key-output-file=KEY_FILENAME \
  --cert-output-file=CERT_FILENAME \
  --dns-san=DNS_NAME
```

### New or Affected Resource(s)

* google_privateca_certificate - My expectation is that this resource, or something like it, would provide `.key` and `.cert` outputs. 

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_certificate
- https://cloud.google.com/certificate-authority-service/docs/creating-certificate-authorities#test

b/291991515

**Comment by SarahFrench** [comment]
Have you looked at using the [tls provider](https://registry.terraform.io/providers/hashicorp/tls/latest) to create the private/public key pair? The [`tls_private_key` resource](https://registry.terraform.io/providers/hashicorp/tls/4.0.4/docs/resources/private_key) can create a key pair, and this can be used alongside the `tls_cert_request` resource to supply inputs to privateca resources in the Google provider. 

[Here's an example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/google-continuous-validation#example---check-if-a-certificate-will-expire-within-a-certain-timeframe-google_privateca_certificate) showing how those resources can be used with privateca resources. However bear in mind that when I wrote that config it was intended only as a contrived example that demonstrated the new `check` block in Terraform 1.5. I haven't personally done much certificate management in production, so there might be considerations I'm missing here!

**Comment by rileykarson** [comment]
Given the difference in UX between Terraform and gcloud @SarahFrench's proposed method of using the TLS provider would be preferred to baking this into the Google provider. To better document this as an option, leaving open as a documentation change to add an example doing so.
