### ISSUE TITLE
Support AlloyDB continuous backup

### ISSUE THREAD

**Issue by gpassini** [hashicorp/terraform-provider-google#15110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

AlloyDB [supports 2 types of backup strategies](https://cloud.google.com/alloydb/docs/backup/overview):
1. Automated backups; and
2. Continuous backup.

The AlloyDB Terraform provider already supports automated backups, via the `automated_backup_policy` field of the `google_alloydb_cluster` [resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_cluster), but there's no support for configuring continuous backup yet.

Currently, the alternative is to manually configure continuous backup for each AlloyDB cluster created by Terraform, as described in the [AlloyDB docs](https://cloud.google.com/alloydb/docs/backup/configure#continuous). Example:
```sh
gcloud alloydb clusters update CLUSTER_ID \
  --continuous-backup-recovery-window-days=WINDOW_LENGTH \
  --region=REGION_ID \
  --project=PROJECT_ID
```

### New or Affected Resource(s)

* google_alloydb_cluster

### Potential Terraform Configuration

```tf
resource "google_alloydb_cluster" "example" {
  continuous_backup_policy {
    window_length = "WINDOW_LENGTH"
  }
}
```

### References

* https://cloud.google.com/alloydb/docs/backup/overview#continuous
* https://cloud.google.com/alloydb/docs/backup/configure#continuous

b/291745106

**Comment by GoogleMarcfont** [comment]
Currently working on this!
