### ISSUE TITLE
Google snapshot resource policy is incorrect

### ISSUE THREAD

**Issue by goodspark** [hashicorp/terraform-provider-google#15147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.73.0
```

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
resource "google_compute_resource_policy" "disk_backups" {
  name   = "disk-backups"
  region = "us-west2"
  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 3
        start_time    = "00:00" # UTC
      }
    }
    retention_policy {
      max_retention_days = 7
      on_source_disk_delete = "APPLY_RETENTION_POLICY"
    }
  }
}

```

### Expected Behavior

There should be no `days_in_schedule` field in the `daily_schedule` block. The daily schedule literally means every day. Internally, the TF provider code should hardcode the `days_in_schedule` value to 1 or just not send it at all, depending on what the actual GCP API looks like.

### Actual Behavior

When I try to apply the above TF:

```
│ Error: Error creating ResourcePolicy: googleapi: Error 400: Invalid value for field 'resource.snapshotSchedulePolicy.schedule.dailySchedule.daysInCycle': '3'. Days in cycle for snapshot schedule policy must be 1, invalid
│ 
│   with module.mything.google_compute_resource_policy.disk_backups,
│   on modules/mything/main.tf line 54, in resource "google_compute_resource_policy" "disk_backups":
│   54: resource "google_compute_resource_policy" "disk_backups" {
```

### References

TF docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy#nested_daily_schedule
TF provider code: https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/compute/resource_compute_resource_policy.go#L221-L226
GCP docs: https://cloud.google.com/compute/docs/disks/scheduled-snapshots#create_disk_add_policy

Output of `gcloud compute resource-policies create snapshot-schedule --help`:

```
         Exactly one of these must be specified:

           --daily-schedule
              Snapshot schedule starts daily at START_TIME.

           --hourly-schedule=HOURS
              Snapshot schedule occurs every n hours starting at START_TIME.

           --weekly-schedule=WEEKLY_CYCLE
              Snapshot schedule occurs weekly on WEEKLY_SCHEDULE at START_TIME.
              WEEKLY_CYCLE must be one of: monday, tuesday, wednesday,
              thursday, friday, saturday, sunday.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
I can repro. Looks like [days_in_cycle](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy#days_in_cycle) does only accept 1.

**Comment by zli82016** [comment]
This is the API doc for the field `daysInCycle`. It does not specify that `daysInCycle` only accepts 1 and other numbers also make sense based on the API doc. 
`Defines a schedule with units measured in days. The value determines how many days pass between the start of each cycle.`

But  the service side does have the validation in the code to only accept 1. 
I am going to modify the provider doc to make it clear that  the field  `days_in_cycle` only accepts 1.

Normally, we don't add specific validation on the provider and rely on the validation on the service side.
I am going to double check with the service team for the acceptable values in this field.
