### ISSUE TITLE
google_cloud_run_service will not deploy a new revision with zero traffic

### ISSUE THREAD

**Issue by rileygriffith** [hashicorp/terraform-provider-google#15153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.5.2

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "axonic" {
...
  traffic {
    percent       = 100
    revision_name = data.google_cloud_run_service.service.traffic[0].revision_name
    or
    revision_name = data.google_cloud_run_service.service.template[0].metadata[0].name
  }
  traffic {
    percent         = 0
    latest_revision = true
  }
}
```

### Expected Behavior

Expected result is old revision will continue to serve 100% traffic, and the new revision will serve 0%.

### Actual Behavior

Terraform creates a new cloud run revision and serves that revision with 100% traffic, and switches the previous revision to 0%.

Doesn't matter if I have `autogenerate_revision_name` set to true or false, it will create a new revision regardless and give it 100% traffic.

Am I misunderstanding something here? Is there any way to have terraform update the service configuration (mostly just env vars) without creating a new revision, or creating a new revision with 0 traffic?

### References

* #0000

**Comment by edwardmedia** [comment]
b/290963806

**Comment by rileygriffith** [comment]
I think i have identified an easy solution for this. You can almost achieve a zero deployment, however if you switch traffic to the latest by non-terraform means, the state will lose the information on the revision name in the traffic block once refreshed. Ex:

```
              {
                "latest_revision": false,
                "percent": 100,
                "revision_name": "revision-00007-rnk",
                "tag": "",
                "url": ""
              }
```

will become

```
              {
                "latest_revision": true,
                "percent": 100,
                "revision_name": "",
                "tag": "",
                "url": ""
              }
```

Would it be feasible to have terraform state keep the revision name even if `latest_revision` is set to true?

**Comment by bskaplan** [comment]
If you switch to the cloud_run_v2 service, there's a traffic_statuses block that will include the revisions currently serving traffic. It looks like that data isn't currently being surfaced in the v1 resource, I'll look into that.

**Comment by rileygriffith** [comment]
I did switch to the v2 service for the resource, but unfortunately it seems like there is only a v1 data source, and I can't reference the v2 resource attributes in itself
