### ISSUE TITLE
Unable to create record-set, due to regex validation

### ISSUE THREAD

**Issue by tommed** [hashicorp/terraform-provider-google#15178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.3
on linux_amd[64](https://github.com/VigilantApps/ukp-cloud-template/actions/runs/5554750512/jobs/10148477374#step:4:68)

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
# reference to vipro.online DNS zone
data "google_dns_managed_zone" "vipro-online-dns-zone" {
  name    = "vipro-online"
  project = "vapps-online"
}

# set the dns record for this environment
resource "google_dns_record_set" "service-ep-dns-a-record" {
  name = "demo.ukp.vipro.online."
  project = "vapps-online"
  managed_zone = data.google_dns_managed_zone.vipro-online-dns-zone.name
  type = "A"
  ttl  = 300
  rrdatas = [google_compute_global_address.service-ip.address]
}
```

### Debug Output

https://gist.github.com/tommed/4c4dc732d13d4e5e736b106f887b3817

### Expected Behavior

Should create record set (I can confirm I can create this manually using the gcp console).

### Actual Behavior

Validation error prevents it being created.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tommed** [comment]
Any update on this please?

**Comment by c2thorn** [comment]
@tommed The error is for a Compute Global Address resource, not the record set. I'm assuming you have some other configuration elsewhere including `google_compute_global_address.service-ip`?

It's an API error, so there isn't anything we could do on the provider side. You likely need to change the name of the global address to something else.
