### ISSUE TITLE
google_healthcare_fhir_store: add support for lastUpdatedPartitionConfig 

### ISSUE THREAD

**Issue by FaithfulZhening** [hashicorp/terraform-provider-google#15185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for the lastUpdatedPartitionConfig​ option(https://cloud.google.com/healthcare-api/docs/reference/rest/v1/projects.locations.datasets.fhirStores#schemaconfig) in terraform.

### New or Affected Resource(s)

* google_healthcare_fhir_store

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_healthcare_fhir_store" "default" {
  provider = google-beta
  name    = "example-fhir-store"
  dataset = google_healthcare_dataset.default.id
  version = "R4"

  enable_update_create          = true
  disable_referential_integrity = false
  disable_resource_versioning   = false
  enable_history_import         = false
   
  ...

  stream_configs {
    resource_types = ["Observation"]
    bigquery_destination {
      dataset_uri = "bq://${google_bigquery_dataset.bq_dataset.project}.${google_bigquery_dataset.bq_dataset.dataset_id}"
      schema_config {
        recursive_structure_depth = 3
      }
    }
    lastUpdatedPartitionConfig {
      type = "PARTITION_TYPE_UNSPECIFIED"
      expirationMs = 10000
    }
  }
}
```

### References

* #0000

b/292263198

**Comment by averbuks** [comment]
This field has already been [added](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_fhir_store#last_updated_partition_config). Issue can be closed.
