### ISSUE TITLE
Add support for VPC spokes in google_network_connectivity_spoke

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#15195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Add support for VPC spoke in `google_network_connectivity_spoke`

### New or Affected Resource(s)

* google_network_connectivity_spoke

### Potential Terraform Configuration

```tf
resource "google_network_connectivity_spoke" "primary" {
  provider = google-beta
  name           = "name"
  location       = "us-west1"
  description = "A sample spoke with a linked vpc"
  hub              =  google_network_connectivity_hub.basic_hub.id
  linked_vpc_network {
    vpc = "vpc_self_link_url"
    exclude_export_ranges = []
  }
}
```

### References

* [VPC Spokes](https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/vpc-spokes-overview)
* [APIs](https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1/projects.locations.spokes#linkedvpcnetwork)
* b/296603372

**Comment by felipegc** [comment]
Hi @rileykarson I opened a cl/561448846 for this one. If you have time, could you please take a look at it? Thanks

**Comment by rileykarson** [comment]
Closed between that + DCL upgrade in https://github.com/GoogleCloudPlatform/magic-modules/pull/8876
