### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nprasadnurani** [hashicorp/terraform-provider-google#15198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

Terraform v1.4.6
on windows_386
+ provider registry.terraform.io/hashicorp/vsphere v2.4.1
### Panic Output

Stack trace from the terraform-provider-vsphere_v2.4.1_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1585274]

goroutine 82 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineRead(0x12cdcfa0, {0x17330a0, 0x12dfa048})
        github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:450 +0x6b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x130849a0, {0x1b50500, 0x130ba480}, 0x12cdcfa0, {0x17330a0, 0x12dfa048})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:712 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x130849a0, {0x1b50500, 0x130ba480}, 0x130c8c40, {0x17330a0, 0x12dfa048})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x547
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x13047770, {0x1b50500, 0x130ba420}, 0x13115920)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x12cdcd20, {0x1b50500, 0x130ba0d8}, 0x12e0a2a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1920ac0, 0x12cdcd20}, {0x1b50500, 0x130ba0d8}, 0x130c0180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x12f02360, {0x1b52188, 0x12c78120}, 0x12e360a0, 0x1308e300, 0x23fd1e8, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x12f02360, {0x1b52188, 0x12c78120}, 0x12e360a0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-vsphere_v2.4.1_x5.exe plugin crashed!

### Expected Behavior
vsphere_virtual_machine.vm: Refreshing state... [id=4220dd3b-2f07-4d9a-3395-c0a806a81622]
Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Actual Behavior

Crashed

### Steps to Reproduce

terrafrom import vsphere_virtual_machine.vm  vm_path

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@nprasadnurani from the log, it seems about below provider. Maybe I have missed the point. Can you point me to whatever the google provider resource is? 

```
terraform-provider-vsphere
```

**Comment by edwardmedia** [comment]
@nprasadnurani closing this assuming it is not related to the Google provider. Feel free to reopen if you see it differently
