### ISSUE TITLE
If neither max_surge_fixed nor max_unavailable_fixed is set it will NOT default to 1, even though document says it will. 

### ISSUE THREAD

**Issue by iBrandyJackson** [hashicorp/terraform-provider-google#15202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.2.7

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#nested_update_policy

https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers

### Debug Output

"2023-07-13T16:14:22.070Z [ERROR] vertex "google_compute_region_instance_group_manager.rbi-mig-1-us-central1-dev-02" error: Error creating RegionInstanceGroupManager: googleapi: Error 400: Invalid value for field 'resource.updatePolicy.maxUnavailable': '{ "fixed": 0}'. maxSurge and maxUnavailable cannot both be 0, invalid"

resource "google_compute_region_instance_group_manager" "mig-1-us-central1" { name = "mig-1-us-central1" base_instance_name = "mig-1-us-central1" region = "us-central1" version { instance_template = google_compute_instance_template.test-template-us-central1.self_link name = "test-template-us-central1" } update_policy { type = "OPPORTUNISTIC" minimal_action = "REPLACE" }}

### Expected Behavior

If neither max_surge_fixed nor max_unavailable_fixed is set it will default to 1.

**Comment by edwardmedia** [comment]
@iBrandyJackson can you share your config that I can use to repro the issue?

**Comment by edwardmedia** [comment]
I do receive this. It appears conflicts what the doc says

```
oogleapi: Error 400: Invalid value for field 'resource.updatePolicy.maxUnavailable': '{  "fixed": 0}'. maxSurge and maxUnavailable cannot both be 0, invalid
```

[max_surge_fixed](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#max_surge_fixed) - (Optional), The maximum number of instances that can be created above the specified targetSize during the update process. Conflicts with max_surge_percent. If neither is set, defaults to 1

**Comment by edwardmedia** [comment]
There are certain api rules that have to be met. 

```
1)  when both max_surge_percent and max_surge_fixed are not given, max_surge_fixed will need to be sent 1.  
2)  max_surge_percent and max_surge_fixed can't be set 1 at the same time. 
3) max_surge_fixed = 0 and max_surge_percent = "" is valid
4) max_surge_fixed must to set to 0 when replacement_method is set RECREATE
5) maxSurge and maxUnavailable cannot both be 0
```

**Comment by edwardmedia** [comment]
@iBrandyJackson taking a closer look, below rule is in place. But can you show me a doc that indicates one of them should default to 1 (as you stated in the subject)? 

```
maxSurge and maxUnavailable cannot both be 0
```

Between **max_surge_fixed** and **max_surge_percent**, **max_surge_fixed** should be set to 1 if neither are given

**Comment by edwardmedia** [comment]
@iBrandyJackson is this still an issue?

**Comment by edwardmedia** [comment]
@iBrandyJackson closing this now assuming it is no longer an issue

**Comment by edwardmedia** [comment]
@iBrandyJackson my understanding is there are two config.

1. it is about **max_surge**
     between max_surge__fixed_ and max_surge__percent_. If neither is set, defaults to 1. Both are **max_surge**

2. it is about **max_unavailable**
     between max_unavailable_[fixed](url) and max_unavailable_[percent](url),  If neither is set, defaults to 1. Both are **max_unavailable**

Am I right?

**Comment by askubis** [comment]
Question to the origianl author: @iBrandyJackson - is the issue fixed now after the recent change (https://github.com/GoogleCloudPlatform/magic-modules/pull/10935) ?

**Comment by askubis** [comment]
ping here

**Comment by askubis** [comment]
I think since the PR was merged, we should close the Issue.
