### ISSUE TITLE
Change the way of how destroy on deletion_protection enabled instances work

### ISSUE THREAD

**Issue by zculek-fb** [hashicorp/terraform-provider-google#15204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When destroy is applied to a Google Cloud SQL instance that has `deletion_protection` and/or `deletion_protection.enabled` set to `true`, the way it works now is that Terraform first runs a destroy on (child) resources of the Cloud SQL instance, such as user, database, etc., and when the destroy process reaches the instance itself, it fails due to `deletion_protection` being enabled.

I think the database itself is much more worth to be protected from deletion than the instance itself - the instance can easily be recreated, in a matter of minutes, but if the database is deleted and it's hundreds of GBs big, restoring from a backup could take quite some time. Since at the moment there is no way to set deletion_protection on the database itself, I suggest adding some kind of flag or an if condition or a check that would first check if deletion_protection on the instance is enabled or not, and if it is, skip deleting any of the instance resources (database, user) instead and throwing an error immediately. That would actually be much better workflow, because if `deletion_protection` is enabled on purpose, it was most probably done in an effort to prevent losing the database.

### New or Affected Resource(s)

* google_sql_database

### Potential Terraform Configuration

How it works now (deleting resources which are part of deletion_protection enabled instance):
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
module.mysql_db.google_sql_user.default[0]: Destroying... [id=csql//csql]
module.mysql_db.google_sql_database.default[0]: Destroying... [id=projects/myproj-staging/instances/csql/databases/csql]
module.mysql_db.google_sql_user.default[0]: Destruction complete after 1s
module.mysql_db.random_password.user-password: Destroying... [id=none]
module.mysql_db.google_sql_database_instance.replicas["csql-replica"]: Destroying... [id=csql-read-replica]
module.mysql_db.random_password.user-password: Destruction complete after 0s
module.mysql_db.google_sql_database.default[0]: Destruction complete after 2s
╷
│ Error: Error, failed to delete instance because deletion_protection is set to true. Set it to false to proceed with instance deletion
│
│
```

Desired: (don't delete any of the resources, throw an error immediately)
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
╷
│ Error: Error, failed to delete instance because deletion_protection is set to true. Set it to false to proceed with instance deletion
│
│
```

**Comment by rileykarson** [comment]
Terraform execution is not controlled by providers, and information cannot be passed between resources unless explicitly shared by the end user (such as through interpolation strings). In `google_sql_database`, you can set https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database to "ABANDON" to prevent deletion of databases, although this won't result in identical behaviour.
