### ISSUE TITLE
Fail to delete/create node pools 

### ISSUE THREAD

**Issue by saaramitay** [hashicorp/terraform-provider-google#15205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform {
  required_version = ">= 0.15"
  required_providers {

    google = {
      source  = "hashicorp/google"
      version = "4.68.0"
    }
  }
}

### Affected Resource(s)

* google_container_node_pool

### Panic Output

 Error: error creating NodePool: googleapi: Error 429: Too many operations: cluster "ClusterName" hits the concurrent operations quota 5, please try again later.
 Details:
 [
   {
     "@type": "type.googleapis.com/google.rpc.RequestInfo",
     "requestId": "0x7c853220612b8700"
   }
 ]
 , rateLimitExceeded
 
   with module.dagster_gke_nodes.google_container_node_pool.dagster_node_pools[6],
   on ../modules/infrastructure/gcp/kubernetes-node-pools/dagster-node-pool/main.tf line 5, in resource "google_container_node_pool" "dagster_node_pools":
    5: resource "google_container_node_pool" "dagster_node_pools" {
 

 Error: NodePool "NodePoolName" was created in the error state "ERROR"
 
   with module.dagster_gke_nodes.google_container_node_pool.dagster_node_pools[3],
   on ../modules/infrastructure/gcp/kubernetes-node-pools/dagster-node-pool/main.tf line 5, in resource "google_container_node_pool" "dagster_node_pools":
    5: resource "google_container_node_pool" "dagster_node_pools" {

### Expected Behavior

Action should be completed successfully as it was deployed already with the same code 3 weeks ago.

### Actual Behavior

Action drops the error:

 Error: Error deleting NodePool: googleapi: Error 429: Too many operations: cluster "ClusterName" hits the concurrent operations quota 5, please try again later.
 Details:
 [
   {
     "@type": "type.googleapis.com/google.rpc.RequestInfo",
     "requestId": "0x1e79cd4ffe8d87eb"
   }
 ]
 , rateLimitExceeded

### Steps to Reproduce

1. `terraform apply / terraform destroy`

### References

* #/15085

**Comment by edwardmedia** [comment]
@saaramitay can you share the config and steps that I can use o repro the issue?

**Comment by saaramitay** [comment]
Hey, 
Its pretty simple node pool module, this is the main.tf of the module:
resource "google_container_node_pool" "dagster_node_pools" {
  count               = length(var.node_config)
  name                = "${var.node_config[count.index].environment}-${var.name_prefix}-${var.node_config[count.index].machine_type}" # up to 39 lowercase letters
  cluster             = var.cluster
  project             = var.project
  location            = local.shared_settings.location
  node_locations      = local.shared_settings.node_locations
  initial_node_count  = local.shared_settings.initial_node_count
  max_pods_per_node   = local.shared_settings.max_pods_per_node

  management {
    auto_repair   = local.shared_settings.auto_repair
    auto_upgrade  = local.shared_settings.auto_upgrade
  }

  network_config {
    create_pod_range      = local.shared_settings.create_pod_range
    enable_private_nodes  = local.shared_settings.enable_private_nodes
  }

  autoscaling {
    location_policy       = local.shared_settings.location_policy
    min_node_count        = local.shared_settings.min_node_count
    max_node_count        = local.shared_settings.max_node_count
    total_min_node_count  = local.shared_settings.total_min_node_count
    total_max_node_count  = local.shared_settings.total_max_node_count
  }

  node_config {
    disk_size_gb      = var.node_config[count.index].disk_size_gb
    disk_type         = local.shared_settings.disk_type
    guest_accelerator = local.shared_settings.guest_accelerator
    image_type        = local.shared_settings.image_type
    labels            = var.node_config[count.index].labels
    local_ssd_count   = local.shared_settings.local_ssd_count
    logging_variant   = local.shared_settings.logging_variant
    machine_type      = var.node_config[count.index].machine_type
    metadata          = local.shared_settings.metadata
    oauth_scopes      = local.shared_settings.oauth_scopes
    preemptible       = local.shared_settings.preemptible
    resource_labels   = local.shared_settings.resource_labels
    service_account   = local.shared_settings.service_account
    spot              = local.shared_settings.spot
    tags              = local.shared_settings.tags
    taint             = local.shared_settings.taint

    shielded_instance_config {
      enable_integrity_monitoring = local.shared_settings.enable_integrity_monitoring
      enable_secure_boot          = local.shared_settings.enable_secure_boot
    }
  }

  upgrade_settings {
    max_surge       = local.shared_settings.max_surge
    max_unavailable = local.shared_settings.max_unavailable
    strategy        = local.shared_settings.strategy
  }
}


The locals.tf just contains the values for the settings, so is the variable.tf in the module.
This is my code main.tf:
 
module "dagster_gke_nodes" {
  source        = "../modules/infrastructure/gcp/kubernetes-node-pools/dagster-node-pool"

  project        = var.project
  cluster        = google_container_cluster.gke_cluster.name

  node_config = [
    {
      environment   = var.environment_prefix
      machine_type  = "m1-ultramem-80"
      disk_size_gb  = 1500
      labels        = {
        "size" = "m1-ultramem-80"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n1-standard-4"
      disk_size_gb  = 100
      labels        = {
        "size" = "n1-standard-4"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n1-standard-8"
      disk_size_gb  = 1000
      labels        = {
        "size" = "n1-standard-8"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n1-highcpu-16"
      disk_size_gb  = 1000
      labels        = {
        "size" = "n1-highcpu-16"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n2-standard-16"
      disk_size_gb  = 1000
      labels        = {
        "size" = "n2-standard-16"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n2-highmem-48"
      disk_size_gb  = 1000
      labels        = {
        "size" = "n2-highmem-48"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n2-highmem-80"
      disk_size_gb  = 1000
      labels        = {
        "size" = "n2-highmem-80"
      }
    },
    {
      environment   = var.environment_prefix
      machine_type  = "n2d-highmem-80"
      disk_size_gb  = 2500
      labels        = {
        "size" = "n2d-highmem-80"
      }
    },
  ]
}

To reproduce you just need to apply the configuration. I think what happens is one of two options:
Either Terraform is making too much API requests to the GCP per minute or there is a time gap between the time it takes to create networking subnet alias and assigning it to the node pool.

**Comment by edwardmedia** [comment]
@saaramitay is this still an issue?

**Comment by edwardmedia** [comment]
@saaramitay closing this assuming it is no longer an issue
