### ISSUE TITLE
Re-creation of existing google_monitoring_monitored_project resource for project number name

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#15211]
Reported here: https://github.com/hashicorp/terraform-provider-google/issues/15117#issuecomment-1640037648

Creating a follow up bug to track.

**Comment by roaks3** [comment]
Adding `service/terraform` because I assume our team will handle this fix, but if someone feels it would be more appropriate to forward to the service team, please remove the label

**Comment by c2thorn** [comment]
> Adding `service/terraform` because I assume our team will handle this fix, but if someone feels it would be more appropriate to forward to the service team, please remove the label

I'm close to pushing the fix out, so our team label is good.
