### ISSUE TITLE
Set IAM Permission to Data Policy Masking Rule using resources 'google_bigquery_datapolicy_data_policy_*' not working

### ISSUE THREAD

**Issue by GloriaSam** [hashicorp/terraform-provider-google#15221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```bash
Terraform v1.5.1
+ provider registry.terraform.io/hashicorp/google v4.64.0
```
### Affected Resource(s)

google_bigquery_datapolicy_data_policy_iam_policy
google_bigquery_datapolicy_data_policy_iam_binding
google_bigquery_datapolicy_data_policy_iam_member

### Terraform Configuration Files

```tf
variable "masked_reader" {
  type    = list(string)
  default =  [ 
  "user:1234@test.com"
  ]
}

variable "policy_tags_hierarchy" {
  type    = map(any)
  default = {
 "vehicle-data"
  }
}

variable "data_location" { 
type = string 
default = "EU"
}


# BigQuery Data Policy Masked Rule
resource "google_bigquery_datapolicy_data_policy" "masking_policy" {
  for_each         = var.policy_tags_hierarchy
  location         = var.data_location
  data_policy_id   = "masked_${replace(each.key, "-", "_")}"
  policy_tag       = "parent_tag_id"
  data_policy_type = "DATA_MASKING_POLICY"

  data_masking_policy {
    predefined_expression = "ALWAYS_NULL"
  }
}

# Data Policy Masked Rule member binding
resource "google_bigquery_datapolicy_data_policy_iam_binding" "parent_tag_masked_readers" {
  for_each       = var.policy_tags_hierarchy
  location       = var.data_location
  data_policy_id = "masked_${replace(each.key, "-", "_")}"
  role           = "roles/bigquerydatapolicy.maskedReader"
  members        = var.masked_reader
}
```

### Expected Behavior

The Terraform output ends its execution correctly, it declares that the binding will be created and it is aspected to be done.

### Actual Behavior

There are no changes in the list of Principals that are shown in the masking rules UI section. And no permissions are assigned on the data policy.

### Additional Content

The Google API to set the IAM policy on the data policy is been tested and is working correctly. (https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest/v1beta1/projects.locations.dataPolicies/setIamPolicy).

None of the resources in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_datapolicy_data_policy_iam are working. Neither *_iam_policy nor *_iam_member resource do anything.

**Comment by edwardmedia** [comment]
b/291916056

**Comment by GloriaSam** [comment]
Resolved, was the data_location variable. It works only if it's lower case:
```tf
variable "data_location" { 
type = string 
default = "eu"
}
```
