### ISSUE TITLE
PubSub Schema evolution - when revision limit is reached, resource can't be updated

### ISSUE THREAD

**Issue by uthark** [hashicorp/terraform-provider-google#15228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_pubsub_schema

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. Create schema and change it 20 times so that you get 20 revisions. 21st revision would fail.
1. `terraform apply`

### References

* #0000

b/294553291

**Comment by edwardmedia** [comment]
@uthark sounds like this is the restriction of the feature (api). Not sure how much the provider can do. Are you able to create more than 20 revisions via other means?

**Comment by uthark** [comment]
old revisions could be removed via API.

O.

**Comment by shuyama1** [comment]
Hey @melinath, I assume that you may have some context on this issue so I assign it to you. Apologize if I'm wrong and feel free to unassign yourself. (not forward this ticket to service team at this moment)

**Comment by melinath** [comment]
This is a constraint of the API - when pubsub schema updates were [implemented](https://github.com/GoogleCloudPlatform/magic-modules/pull/8079), we had a lot of trouble deciding how Terraform should behave and ended up settling on this for now. We're definitely interested in hearing how folks would like to see this behave.

The best workaround in the meantime is to [delete old revisions manually](https://cloud.google.com/pubsub/docs/schemas#delete-schema-revision) using gcloud or cloud console.

attn @kamalaboulhosn

**Comment by uthark** [comment]
wondering if it could be an additional flag to remove old revisions
automatically.
In the meantime we decided to implement additional pre-flight checks to
verify if the limit is reached.
O.
