### ISSUE TITLE
plugin crashed: SIGSEGV invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by NexusNull** [hashicorp/terraform-provider-google#15224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.74.0

### Terraform Configuration Files

https://gist.github.com/NexusNull/60a617121de9baab29701014999e2b9c#file-main-tf
https://gist.github.com/NexusNull/60a617121de9baab29701014999e2b9c#file-providers-tf

### Debug Output
https://gist.github.com/NexusNull/60a617121de9baab29701014999e2b9c#file-debug-log

### Panic Output
https://gist.github.com/NexusNull/60a617121de9baab29701014999e2b9c#file-crash-log

### Steps to Reproduce
1. Create json key for serviceaccount in a different organization
2. `export GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/credentials.json`
3. `terraform plan`

**Comment by NexusNull** [comment]
I updated my terraform version and the problem persists.
`
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.74.0
`

**Comment by hao-nan-li** [comment]
Just want to double-check, 
(1) The original crash was caused by selecting the wrong credential file (Project in wrong org).
(2) By selecting the right credential file, things work as expected.

**Comment by NexusNull** [comment]
> Just want to double-check, (1) The original crash was caused by selecting the wrong credential file (Project in wrong org). (2) By selecting the right credential file, things work as expected.

yes

**Comment by hao-nan-li** [comment]
I will mark this as closed since the crash is resolved.
