### ISSUE TITLE
Changing variable in variable set in TF Cloud results in an Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/terraform-provider-google#15225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.69.1
+ provider registry.terraform.io/hashicorp/google-beta v4.69.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.5.3. You can update by downloading from https://www.terraform.io/downloads.html
### Affected Resource(s)

* google_XXXXX
[terraform-provider-google](https://github.com/hashicorp/terraform-provider-google)

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Panic Output

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.iam.google_project_iam_member.team_secret_accessor_role["someemail@example.com"],
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)

### Expected Behavior

Expected terraform to update resources using new variables from variables set. This particular variable is a list of emails

### Actual Behavior

It throws an error for each new email that was added to the list.:

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.iam.google_project_iam_member.team_firebasedeveloper_role["someemail@example.com"],
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce

Create TF Cloud workspace. Create a variable set containing a variable that holds a list of strings with emails: ["email1@a.com", "email2@a.com"]

Deploy infrastructure

Modify variable in the variable set and add new emails. 

Deploy again

1. `terraform apply`

### Important Factoids

Original list with emails is used without any problems

### References

* #0000

**Comment by edwardmedia** [comment]
@periwinkleFTW can you provide a config code and steps that I can used to repro the issue?

**Comment by edwardmedia** [comment]
@periwinkleFTW is this still an issue?

**Comment by periwinkleFTW** [comment]
> @periwinkleFTW is this still an issue?

Yes, i am testing it on a staging environment to try to pinpoint the resources that cause this. Since the error is in the production it is taking time to give you more details

**Comment by periwinkleFTW** [comment]
> @periwinkleFTW is this still an issue?

I think I figured it out. My org is in the process of migrating org emails (managed by google) to a different domain. At first I tried to update the list of emails to have emails with both domains in there: `["name1@olddomain.com", "name1@newdomain.com"]` . Since `olddomain.com` domain was retired it was causing an error, even though for email purposes it acts as an alias forwarding emails sent to old address to the new one.

The error was this:
```
Error: Provider produced inconsistent result after apply
When applying changes to module.iam.google_project_iam_member.team_editor_role["name1@olddomain.com"], provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
``` 

This issue was resolved by putting only emails with new domain in the variable list. Maybe a better error message would help, but this only happens when orgs are switching emails

**Comment by edwardmedia** [comment]
@periwinkleFTW that does make sense. I think we can close this issue now. Feel free to reopen if see it differently.
