### ISSUE TITLE
cloudfunctions_2 - function updated in place when nothing changes

### ISSUE THREAD

**Issue by skylerrr** [hashicorp/terraform-provider-google#15249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/google v4.71.0
```

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions2_function" "my_function" {
  name        = "my_function"
  description = "my cool function"
  location    = local.region

  build_config {
    runtime     = "python39"
    entry_point = "entry"
    source {
      storage_source {
        bucket = google_storage_bucket.function_source_bucket.name
        object = google_storage_bucket_object.function_source_object.name
      }
    }
    environment_variables = {}
  }

  service_config {
    max_instance_count               = 1
    min_instance_count               = 0
    available_memory                 = var.mem
    timeout_seconds                  = var.timeout
    max_instance_request_concurrency = 1
    available_cpu                    = var.cpu
    all_traffic_on_latest_revision   = true
    service_account_email            = var.email
    environment_variables = {}
  }

}
```

### Expected Behavior

No updates to function should be planned

### Actual Behavior

Plan includes an update in place for the function because of storage_source.generation

```tf
Terraform will perform the following actions:

  # google_cloudfunctions2_function.my_function will be updated in-place
  ~ resource "google_cloudfunctions2_function" "my_function" {
        id          = "projects/xxx/locations/xxx/functions/my_function"
        name        = "my_function"
        # (8 unchanged attributes hidden)

      ~ build_config {
            # (4 unchanged attributes hidden)

          ~ source {
              ~ storage_source {
                  - generation = 1689955259084871 -> null
                    # (2 unchanged attributes hidden)
                }
            }
        }

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. Create a function
2. Do not make any changes to function code or tf config
3. Run `terraform plan`

**Comment by edwardmedia** [comment]
b/292251771

**Comment by melinath** [comment]
This is also causing 100% test failures for TestAccCloudFunctions2Function_update. It doesn't seem to be caused by a change to the code.

**Comment by shuyama1** [comment]
This is causing 100% test failures for all `TestAccCloudFunctions2*` tests (12 in total)

**Comment by James9074** [comment]
A workaround for now, you can ignore `generation` via `lifecycle`. There's probably a cleaner way to do this, but it works!

```
resource "google_cloudfunctions2_function" "function" {
  name     = your_function_name

  lifecycle { ignore_changes = [build_config[0].source[0].storage_source[0].generation] }

  build_config {
    runtime     = "python311"
    entry_point = "main"
    [...]
  ```
