### ISSUE TITLE
google_client_config data source as local-only

### ISSUE THREAD

**Issue by christopherfrieler** [hashicorp/terraform-provider-google#15247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I was wondering, why the `google_client_config` data source is not implemented as [local-only](https://developer.hashicorp.com/terraform/language/data-sources#local-only-data-sources). The [data source's documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config) explitly warns about the access-token being written to the remote state and, as far as understand, a local-only datasource would solve this.

Or is there a reason, why this data source needs to be tracked in the remote state? Most of its fields should be filled from the provider configuration and the access-token should be a new one every time.

My intended use-case as motivation:

I want to destroy a DAG file from the Google Cloud Composer's GCS Bucket via terraform and also delete the DAG from the Composer's database, using a provisioner calling its REST API. For this HTTP call, I want to use the access-token used by the provider anyway and which I could obtain from the data source. However, I don't want to (and don't need to) store the token in terraform's remote state. I could probably use the `service_account_access_token` data source to obtain an additional access token for another service user, but this seems to be unnecessary extra effort.

Hence, I want to suggest implementing the `google_client_config` as local-only.

### New or Affected Resource(s)

* google_client_config

### References
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config
https://developer.hashicorp.com/terraform/language/data-sources#local-only-data-sources

**Comment by rileykarson** [comment]
This datasource is local-only, that's a description of behaviour rather than a class of datasource. These datasources still write information into Terraform state, and when stored remotely will record that data remotely even if sensitive.

**Comment by christopherfrieler** [comment]
Ah, Ok. Thank you for clarification. Then "local-only" and "their result data exists only temporarily during a Terraform operation" says only, that there is no remote resource, but the data can still be part of the (possibly remote) state.

Does the [service_account_access_token data source](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account_access_token) have the same behavior? Or is using an extra access-token a way to avoid this? There's no warning in the documentation. (Maybe I will just try, when I find the time, and post the answer myself. ;-))

**Comment by rileykarson** [comment]
It will similarly store the datasource's value in the remote state. Doing so is just how Terraform datasources work, unfortunately! It wouldn't count as local-only because it makes a call to a GCP API to generate a token rather than doing so locally.
