### ISSUE TITLE
Failing test(s): TestAccCloudBuildTrigger_cloudbuildTriggerPubsub*

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#15251]
### Failure rates

- 100% since 2023-07-10

### Impacted tests

- TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample
- TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample

### Affected Resource(s)

* google_cloudbuild_trigger (it's a typo in an example for this resource)

### Nightly build test history

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/418549?buildTab=tests&expandedTest=build%3A%28id%3A418549%29%2Cid%3A2000000003

### Message(s)

```
 Error: Error creating Topic: googleapi: Error 409: Resource already exists in the project (resource=mytopic).
```

This is likely an issue with needing to add a `-` to the resource id in each of these examples so that it generates with a `tf-test-` prefix and a random suffix. See https://googlecloudplatform.github.io/magic-modules/develop/add-mmv1-test/#topicyaml-metadata for more information.

* b/293782020

**Comment by shuyama1** [comment]
Note for service team: 
I deleted the resource in our test project so the tests pass these days, but we still need the `tf-test-` prefix and a random suffix for the resource name in these tests. See https://googlecloudplatform.github.io/magic-modules/develop/add-mmv1-test/#topicyaml-metadata for more information.

**Comment by mariomachado94** [comment]
Looks like you fixed this issue in merge https://github.com/GoogleCloudPlatform/magic-modules/pull/8506.

Closing this item.

**Comment by melinath** [comment]
yep! Closing.
