### ISSUE TITLE
Failing test(s): TestAccContainerNodePool_tpuTopology

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#15254]
### Failure rates

- 100% since [added](https://github.com/GoogleCloudPlatform/magic-modules/pull/8271) - 2023-07-12

### Impacted tests

- TestAccContainerNodePool_tpuTopology

### Affected Resource(s)

* google_container_node_pool (misconfiguration in a test for this resource)

### Nightly build test history

- https://ci-oss.hashicorp.engineering/test/-7987102126786816945?currentProjectId=GoogleCloudBeta&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A415670%29%2Cid%3A2000001739

### Message(s)

```
Error: googleapi: Error 403: Permission denied on 'locations/us-central2-b' (or it may not exist)., forbidden
```
* b/293781877

**Comment by melinath** [comment]
@vivianrwu heads up that this test has never passed in CI since added in https://github.com/GoogleCloudPlatform/magic-modules/pull/8271 - possibly a misconfiguration in the test code.

**Comment by melinath** [comment]
After discussion with @vivianrwu - we will probably want to skip this test in all cases - it would require an additional allowlist and would likely still be flakey due to TPU availability constraints.

**Comment by roaks3** [comment]
This was skipped in https://github.com/GoogleCloudPlatform/magic-modules/pull/8953. Per the previous comment, is this a suitable resolution, or do we want to keep this open in hopes of the test becoming reliable some day?

**Comment by melinath** [comment]
Closing as resolved 👍
