### ISSUE TITLE
resource "google_vpc_access_connector" keeps recreating after successful apply using same code with default max_throughput

### ISSUE THREAD

**Issue by iBrandyJackson** [hashicorp/terraform-provider-google#15278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version: 1.5.0
Provider version: 4.74.0

### Affected Resource(s)

google_vpc_access_connector

### Terraform Configuration Files

```
provider "google" {
  project     = "hc-7edbc66ea51545b1be54dfc5eea"
  region      = "us-central1"
}
resource "google_compute_subnetwork" "network-with-private-secondary-ip-ranges" {
  name          = "test-subnetwork-test2"
  ip_cidr_range = "10.2.0.0/28"
  region        = "us-central1"
  network       = google_compute_network.custom-test.id
  secondary_ip_range {
    range_name    = "tf-test-secondary-range-update1"
    ip_cidr_range = "192.168.10.0/28"
  }
}
resource "google_compute_network" "custom-test" {
  name                    = "test-network-test2"
  auto_create_subnetworks = false
}
# Serverless connector is required for Cloud Run to connect to Cloud Redis.
resource "google_vpc_access_connector" "connector" {
  provider = google-beta
  name     = "byanev-connector-test2"
  project  = "hc-7edbc66ea51545b1be54dfc5eea"
  region   = "us-central1"
  subnet {
    name = google_compute_subnetwork.network-with-private-secondary-ip-ranges.name
  }
  min_instances  = 2
  max_instances  = 3
  max_throughput = 1000
  machine_type   = "f1-micro"
  depends_on     = [google_compute_subnetwork.network-with-private-secondary-ip-ranges]
```

### Debug Output

https://gist.github.com/iBrandyJackson/0e232c7821cd3de112ba2b517576c84c

### Expected Behavior

resource to be created and next plan/apply should not detect any changes.

### Actual Behavior

resource "google_vpc_access_connector" keeps recreating after successful apply using same code.

### Steps to Reproduce

see TF config above 

### Important Factoids

A workaround is to use: 
```
lifecycle {
ignore_changes = [ max_throughput ]
} 
```
however this will not create a resource google_vpc_access_connector with 1000 max_throughput

### References

https://github.com/hashicorp/terraform-provider-google/issues/9331
https://github.com/hashicorp/terraform-provider-google/issues/9228
https://github.com/hashicorp/terraform-provider-google/issues/10244

b/308248319

**Comment by edwardmedia** [comment]
It appears this is an api bug as it receives 1000 but return 300 for maxThroughput. Below is what the[ api doc](https://cloud.google.com/vpc/docs/reference/vpcaccess/rest/v1/projects.locations.connectors) says:

```
maxThroughput | integerMaximum throughput of the connector in Mbps. Default is 300, max is 1000.
```

**Comment by hao-nan-li** [comment]
Does adding min_throughput help? If not how about only having one of the _instaneces field or only the _throughput fields?

**Comment by rileykarson** [comment]
b/293142521 resulted in a documentation clarification: `If both min-throughput and min-instances are provided, min-instances takes precedence over min-throughput.`

**Comment by jashansudan** [comment]
> b/293142521 resulted in a documentation clarification: `If both min-throughput and min-instances are provided, min-instances takes precedence over min-throughput.`
> 
> That should unblock resolution here.

@NickElliot can we close this out?

**Comment by NickElliot** [comment]
The documentation in MMV1 should be updated to reflect this clarification as well -- but it remains that a user can easily apply a seemingly valid configuration that results in a permadiff. There should be some kind of guard preventing users from applying a plan where both min-x or max-x values are provided (or at least where the x-throughput values are not set to default).

**Comment by bhogan-bdai** [comment]
**Documentation**

https://registry.terraform.io/modules/terraform-google-modules/network/google/latest/submodules/vpc-serverless-connector-beta suggests using both `max_instances` and `max_throughput`. If using only instances or only throughput is recommended, that should be clarified there as well.

**Permadiff**

https://cloud.google.com/functions/docs/networking/shared-vpc-host-project#terraform uses only instances, but it still results in a replacement permadiff on `max_throughput`, where the default value from the terraform module/provider is 700 but the API returns 300.

Terraform provider: hashicorp/google @ 5.33.0
Module: terraform-google-modules/network/google//modules/vpc-serverless-connector-beta @ latest (version unspecified)

**Comment by SarahFrench** [comment]
I should have posted on the issue - I have a PR open for this: https://github.com/GoogleCloudPlatform/magic-modules/pull/10313#issuecomment-2160505910
