### ISSUE TITLE
google_notebooks_instance state with kms_key do not detect drift

### ISSUE THREAD

**Issue by oscarpulido55** [hashicorp/terraform-provider-google#15274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.5.3

### Affected Resource(s)

* google_notebooks_instance

### Terraform Configuration Files

```tf
resource "google_notebooks_instance" "user_managed_instance" {
...
  disk_encryption = "CMEK"
  kms_key = "projects/test-perms-prj/locations/us-central1/keyRings/test1/cryptoKeys/test1/cryptoKeyVersions/1"
...
}
```

### Debug Output
https://gist.github.com/oscarpulido55/ac25195e0b92deec0a2354775b4a098b

### Expected Behavior

Terraform state file generated including kms_key field when adding kms_key and disk_encryption = "CMEK" fields in google_notebooks_instance resource

### Actual Behavior

1. Terraform state file generated with empty kms_key field
2. Error when trying to run second plan

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

* #0000

**Comment by edwardmedia** [comment]
Yes I can repro the issue.

**Comment by edwardmedia** [comment]
b/296901901

**Comment by melinath** [comment]
This should be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9915
