### ISSUE TITLE
Resource google_app_engine_flexible_app_version unable to deploy .NET 6 application

### ISSUE THREAD

**Issue by benfranklin79** [hashicorp/terraform-provider-google#15281]
### Problem Description

A brief description of the problem along with a link to a repository are provided [here](https://stackoverflow.com/questions/76755150/why-does-a-terraform-deployment-of-a-gae-net-service-fail-despite-specifying-th) 

The above link details the versions of terraform and the provider being used.

The repository contains [steps](https://github.com/benfranklin79/shared/blob/master/20230725/readme.md#terraform-deployment) on what is hopefully enough to reproduce the problem. They also contain information on the build errors.

There is no service present in the environment we are deploying to. Our expectation is that the deployment succeeds and a new service is created with the version specified in the terraform (v1).

It's worth mentioning that we also did a test where we deployed the test application using `gcloud app deploy` which succeeded. For more details see the [repository](https://github.com/benfranklin79/shared/tree/master/20230725).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.3

### Affected Resource(s)

* google_app_engine_flexible_app_version 

### Terraform Configuration Files

See description above

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by benfranklin79** [comment]
@edwardmedia [here](https://github.com/benfranklin79/shared/blob/master/20230725/main.tf) is the terraform configuration

**Comment by edwardmedia** [comment]
@benfranklin79 I have tested on deploying [.NET version](https://cloud.google.com/appengine/docs/flexible/dotnet/runtime).  and no issue is found. I think you need to make sure your app code is working. Until you can deploy it with other means like gcloud, I can help see issues with terraform.

**Comment by edwardmedia** [comment]
@benfranklin79 is there anything left that we can help?

**Comment by edwardmedia** [comment]
@benfranklin79 closing this now, assuming it is no longer an issue
