### ISSUE TITLE
Add "description" field for google_tags_location_tag_binding

### ISSUE THREAD

**Issue by pntran1** [hashicorp/terraform-provider-google#15296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Local tag bindings can be used for multiple purposes.  Adding a description will clarify what the binding is used for.

For example:

resource "google_tags_location_tag_binding" "resource_tag_bindings" {
   ...
   description = "This binding is used to grant firewall access from web to db"

### New or Affected Resource(s)

google_tags_location_tag_binding

**Comment by rileykarson** [comment]
Description is not present in this API: https://cloud.google.com/resource-manager/reference/rest/v3/tagBindings

A Terraform-only description could be achieved with a comment in HCL, I think!

**Comment by pntran1** [comment]
@rileykarson - Thank you so much for the info and your help!
