### ISSUE TITLE
resource_labels flag missing in google container node_pool

### ISSUE THREAD

**Issue by Techops-ather** [hashicorp/terraform-provider-google#15294]
Hi Team,

Google gke 1.24version release has the "resource_labels" spec which is not propagated to the Terraform. It throws the below error _An argument named "resource_labels" is not expected here._

Could you please release the spec ASAP.!

**Comment by rileykarson** [comment]
This should be present, see the config in this test: https://github.com/hashicorp/terraform-provider-google-beta/blob/c65dec0df9dc770254a0298055fb9b3a4080a308/google-beta/resource_container_node_pool_test.go#L2083-L2125

Note that it's nested under `node_config`.

**Comment by Techops-ather** [comment]
@rileykarson thanks for reverting back and we added the same under node_config only.

But still getting the same error.

One finding as per the link which you have provided, it's been added on google-beta provider and not google. We use google and not google-beta.
