### ISSUE TITLE
[google_container_cluster] fqdn network policy setting

### ISSUE THREAD

**Issue by TheKangaroo** [hashicorp/terraform-provider-google#15295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE clusters can enable L7 (FQDN) network policies for Dataplane v2 clusters. This is documented here:
https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies
I believe it is not currently possible to manage this setting from within terraform.
The feature can be enabled with
`gcloud beta container clusters update <name> --enable-fqdn-network-policy` which will result in a networkConfig entry:
```
gcloud beta container clusters describe <name> |yq -r '.networkConfig.enableFqdnNetworkPolicy'
true
```

It should be possible to manage the fqdn network policy setting from the google_container_cluster resource in terraform.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  [...]
  addons_config {
    fqdn_network_policy {
      enabled = true
    }
 ```

### References

* b/293781747

**Comment by shuyama1** [comment]
Note to service team: this issue already have a PR linked
