### ISSUE TITLE
Cannot generate google/google-beta provider codes with `PRODUCT=container` filter

### ISSUE THREAD

**Issue by toVersus** [hashicorp/terraform-provider-google#15307]
# Background

I want to generate google and google-beta provider codes from [GoogleCloudPlatform/magic-modules](https://github.com/GoogleCloudPlatform/magic-modules) as described in [Generate google and google-beta providers](https://googlecloudplatform.github.io/magic-modules/get-started/generate-providers/). It works fine until [GoogleCloudPlatform/magic-modules#8381](https://github.com/GoogleCloudPlatform/magic-modules/pull/8381) merged, but I am no longer generating codes with the `PRODUCT=container` filter.

/cc @ScottSuarez

# What kind of contribution is this issue about?

* MMv1-based resource

# Related PR(s), if any:

None

# Details

Check the setup requirements and make sure that the required tools are installed.

```console
❯ ./scripts/doctor
Check for ruby in path...
   found!
Check for go in path...
   found!
Check for goimports in path...
   found!
Check for git in path...
   found!
Check for terraform in path...
   found!
Check for make in path...
   found!
```

Failed to generate provider code with `PRODUCT=container` filter:

<details>
<summary><code>make provider VERSION=beta OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta" PRODUCT=container</code></summary>
<pre>
<code>
make mmv1
cd mmv1;\
		bundle; \
		bundle exec compiler.rb -e terraform -o /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta -v beta -p products/container;
Using rake 13.0.6
Using concurrent-ruby 1.2.0
Using i18n 1.12.0
Using minitest 5.17.0
Using tzinfo 2.0.6
Using activesupport 7.0.4.2
Using ast 2.4.2
Using debug_inspector 1.1.0
Using binding_of_caller 1.0.0
Using bundler 2.4.6
Using diff-lcs 1.5.0
Using json 2.6.3
Using metaclass 0.0.4
Using mocha 1.3.0
Using openapi_parser 1.0.0
Using parallel 1.22.1
Using parser 3.2.0.0
Using rainbow 3.1.1
Using regexp_parser 2.6.2
Using rexml 3.2.5
Using rspec-support 3.12.0
Using rspec-core 3.12.1
Using rspec-expectations 3.12.2
Using rspec-mocks 3.12.3
Using rspec 3.12.0
Using rubocop-ast 1.24.1
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.4.2
Using rubocop 1.44.1
Bundle complete! 8 Gemfile dependencies, 29 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
I, [2023-07-27T01:06:24.761211 #9559]  INFO -- : Generating MM output to '/Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta'
I, [2023-07-27T01:06:24.761365 #9559]  INFO -- : Using beta version
I, [2023-07-27T01:06:24.841266 #9574]  INFO -- : products/activedirectory: Compiling provider config
I, [2023-07-27T01:06:24.864877 #9574]  INFO -- : products/activedirectory: Not specified, skipping generation
I, [2023-07-27T01:06:24.878273 #9579]  INFO -- : products/artifactregistry: Compiling provider config
I, [2023-07-27T01:06:24.882633 #9576]  INFO -- : products/apigateway: Compiling provider config
I, [2023-07-27T01:06:24.910331 #9579]  INFO -- : products/artifactregistry: Not specified, skipping generation
I, [2023-07-27T01:06:24.913338 #9576]  INFO -- : products/apigateway: Not specified, skipping generation
I, [2023-07-27T01:06:24.933826 #9574]  INFO -- : products/beyondcorp: Compiling provider config
I, [2023-07-27T01:06:24.952886 #9575]  INFO -- : products/alloydb: Compiling provider config
I, [2023-07-27T01:06:24.958363 #9574]  INFO -- : products/beyondcorp: Not specified, skipping generation
I, [2023-07-27T01:06:24.973194 #9575]  INFO -- : products/alloydb: Not specified, skipping generation
I, [2023-07-27T01:06:24.980970 #9576]  INFO -- : products/bigqueryanalyticshub: Compiling provider config
I, [2023-07-27T01:06:24.989215 #9575]  INFO -- : products/bigquerydatapolicy: Compiling provider config
I, [2023-07-27T01:06:24.998337 #9576]  INFO -- : products/bigqueryanalyticshub: Not specified, skipping generation
I, [2023-07-27T01:06:25.008657 #9575]  INFO -- : products/bigquerydatapolicy: Not specified, skipping generation
I, [2023-07-27T01:06:25.021089 #9574]  INFO -- : products/bigqueryconnection: Compiling provider config
I, [2023-07-27T01:06:25.031129 #9575]  INFO -- : products/bigqueryreservation: Compiling provider config
I, [2023-07-27T01:06:25.037858 #9574]  INFO -- : products/bigqueryconnection: Not specified, skipping generation
I, [2023-07-27T01:06:25.038233 #9576]  INFO -- : products/bigquerydatatransfer: Compiling provider config
I, [2023-07-27T01:06:25.049248 #9575]  INFO -- : products/bigqueryreservation: Not specified, skipping generation
I, [2023-07-27T01:06:25.054500 #9576]  INFO -- : products/bigquerydatatransfer: Not specified, skipping generation
I, [2023-07-27T01:06:25.058999 #9574]  INFO -- : products/bigtable: Compiling provider config
I, [2023-07-27T01:06:25.075520 #9574]  INFO -- : products/bigtable: Not specified, skipping generation
I, [2023-07-27T01:06:25.094940 #9577]  INFO -- : products/apigee: Compiling provider config
I, [2023-07-27T01:06:25.117273 #9576]  INFO -- : products/binaryauthorization: Compiling provider config
I, [2023-07-27T01:06:25.128590 #9575]  INFO -- : products/billingbudget: Compiling provider config
I, [2023-07-27T01:06:25.175911 #9574]  INFO -- : products/certificatemanager: Compiling provider config
I, [2023-07-27T01:06:25.325344 #9578]  INFO -- : products/appengine: Compiling provider config
I, [2023-07-27T01:06:25.400641 #9576]  INFO -- : products/binaryauthorization: Not specified, skipping generation
I, [2023-07-27T01:06:25.401635 #9578]  INFO -- : products/appengine: Not specified, skipping generation
I, [2023-07-27T01:06:25.401853 #9575]  INFO -- : products/billingbudget: Not specified, skipping generation
I, [2023-07-27T01:06:25.402944 #9577]  INFO -- : products/apigee: Not specified, skipping generation
I, [2023-07-27T01:06:25.403972 #9574]  INFO -- : products/certificatemanager: Not specified, skipping generation
I, [2023-07-27T01:06:25.413789 #9575]  INFO -- : products/cloudbuildv2: Compiling provider config
I, [2023-07-27T01:06:25.461488 #9577]  INFO -- : products/cloudfunctions: Compiling provider config
I, [2023-07-27T01:06:25.473132 #9575]  INFO -- : products/cloudbuildv2: Not specified, skipping generation
I, [2023-07-27T01:06:25.493934 #9576]  INFO -- : products/cloudasset: Compiling provider config
I, [2023-07-27T01:06:25.502727 #9577]  INFO -- : products/cloudfunctions: Not specified, skipping generation
I, [2023-07-27T01:06:25.531543 #9577]  INFO -- : products/cloudids: Compiling provider config
I, [2023-07-27T01:06:25.533158 #9575]  INFO -- : products/cloudidentity: Compiling provider config
I, [2023-07-27T01:06:25.535868 #9576]  INFO -- : products/cloudasset: Not specified, skipping generation
I, [2023-07-27T01:06:25.552945 #9577]  INFO -- : products/cloudids: Not specified, skipping generation
I, [2023-07-27T01:06:25.561869 #9575]  INFO -- : products/cloudidentity: Not specified, skipping generation
I, [2023-07-27T01:06:25.615703 #9579]  INFO -- : products/bigquery: Compiling provider config
I, [2023-07-27T01:06:25.631701 #9579]  INFO -- : products/bigquery: Not specified, skipping generation
I, [2023-07-27T01:06:25.642432 #9576]  INFO -- : products/cloudiot: Compiling provider config
I, [2023-07-27T01:06:25.661617 #9576]  INFO -- : products/cloudiot: Not specified, skipping generation
I, [2023-07-27T01:06:25.669132 #9574]  INFO -- : products/cloudfunctions2: Compiling provider config
I, [2023-07-27T01:06:25.696360 #9574]  INFO -- : products/cloudfunctions2: Not specified, skipping generation
I, [2023-07-27T01:06:25.701941 #9576]  INFO -- : products/cloudtasks: Compiling provider config
I, [2023-07-27T01:06:25.727870 #9576]  INFO -- : products/cloudtasks: Not specified, skipping generation
I, [2023-07-27T01:06:25.732974 #9579]  INFO -- : products/cloudscheduler: Compiling provider config
I, [2023-07-27T01:06:25.746351 #9574]  INFO -- : products/containeranalysis: Compiling provider config
I, [2023-07-27T01:06:25.756404 #9579]  INFO -- : products/cloudscheduler: Not specified, skipping generation
I, [2023-07-27T01:06:25.778453 #9574]  INFO -- : products/containeranalysis: Not specified, skipping generation
I, [2023-07-27T01:06:25.812949 #9576]  INFO -- : products/containerattached: Compiling provider config
I, [2023-07-27T01:06:25.847440 #9576]  INFO -- : products/containerattached: Not specified, skipping generation
I, [2023-07-27T01:06:25.856287 #9573]  INFO -- : products/accesscontextmanager: Compiling provider config
I, [2023-07-27T01:06:25.871132 #9576]  INFO -- : products/dataform: Compiling provider config
I, [2023-07-27T01:06:25.899714 #9573]  INFO -- : products/accesscontextmanager: Not specified, skipping generation
I, [2023-07-27T01:06:25.900187 #9576]  INFO -- : products/dataform: Not specified, skipping generation
I, [2023-07-27T01:06:25.945404 #9574]  INFO -- : products/datacatalog: Compiling provider config
I, [2023-07-27T01:06:25.972557 #9574]  INFO -- : products/datacatalog: Not specified, skipping generation
I, [2023-07-27T01:06:25.981339 #9573]  INFO -- : products/datafusion: Compiling provider config
I, [2023-07-27T01:06:26.006234 #9579]  INFO -- : products/databasemigrationservice: Compiling provider config
I, [2023-07-27T01:06:26.014823 #9573]  INFO -- : products/datafusion: Not specified, skipping generation
I, [2023-07-27T01:06:26.023837 #9574]  INFO -- : products/dataproc: Compiling provider config
I, [2023-07-27T01:06:26.032748 #9579]  INFO -- : products/databasemigrationservice: Not specified, skipping generation
I, [2023-07-27T01:06:26.033908 #9573]  INFO -- : products/datastore: Compiling provider config
I, [2023-07-27T01:06:26.106322 #9578]  INFO -- : products/cloudbuild: Compiling provider config
I, [2023-07-27T01:06:26.233092 #9577]  INFO -- : products/cloudrun: Compiling provider config
I, [2023-07-27T01:06:26.413798 #9574]  INFO -- : products/dataproc: Not specified, skipping generation
I, [2023-07-27T01:06:26.425406 #9577]  INFO -- : products/cloudrun: Not specified, skipping generation
I, [2023-07-27T01:06:26.427049 #9573]  INFO -- : products/datastore: Not specified, skipping generation
I, [2023-07-27T01:06:26.433774 #9578]  INFO -- : products/cloudbuild: Not specified, skipping generation
I, [2023-07-27T01:06:26.461491 #9575]  INFO -- : products/cloudrunv2: Compiling provider config
I, [2023-07-27T01:06:26.474137 #9574]  INFO -- : products/deploymentmanager: Compiling provider config
I, [2023-07-27T01:06:26.481904 #9575]  INFO -- : products/cloudrunv2: Not specified, skipping generation
I, [2023-07-27T01:06:26.490660 #9574]  INFO -- : products/deploymentmanager: Not specified, skipping generation
I, [2023-07-27T01:06:26.505985 #9574]  INFO -- : products/documentai: Compiling provider config
I, [2023-07-27T01:06:26.521564 #9574]  INFO -- : products/documentai: Not specified, skipping generation
I, [2023-07-27T01:06:26.534070 #9574]  INFO -- : products/essentialcontacts: Compiling provider config
I, [2023-07-27T01:06:26.535583 #9576]  INFO -- : products/dataplex: Compiling provider config
I, [2023-07-27T01:06:26.543121 #9577]  INFO -- : products/dialogflow: Compiling provider config
I, [2023-07-27T01:06:26.551018 #9574]  INFO -- : products/essentialcontacts: Not specified, skipping generation
I, [2023-07-27T01:06:26.554683 #9576]  INFO -- : products/dataplex: Not specified, skipping generation
I, [2023-07-27T01:06:26.561463 #9577]  INFO -- : products/dialogflow: Not specified, skipping generation
I, [2023-07-27T01:06:26.572341 #9577]  INFO -- : products/firebasedatabase: Compiling provider config
I, [2023-07-27T01:06:26.590542 #9577]  INFO -- : products/firebasedatabase: Not specified, skipping generation
I, [2023-07-27T01:06:26.595105 #9576]  INFO -- : products/firebase: Compiling provider config
I, [2023-07-27T01:06:26.617852 #9576]  INFO -- : products/firebase: Not specified, skipping generation
I, [2023-07-27T01:06:26.627076 #9574]  INFO -- : products/filestore: Compiling provider config
I, [2023-07-27T01:06:26.644289 #9574]  INFO -- : products/filestore: Not specified, skipping generation
I, [2023-07-27T01:06:26.644580 #9577]  INFO -- : products/firebaseextensions: Compiling provider config
I, [2023-07-27T01:06:26.651908 #9574]  INFO -- : products/firebasestorage: Compiling provider config
I, [2023-07-27T01:06:26.667707 #9577]  INFO -- : products/firebaseextensions: Not specified, skipping generation
I, [2023-07-27T01:06:26.683142 #9574]  INFO -- : products/firebasestorage: Not specified, skipping generation
I, [2023-07-27T01:06:26.685239 #9576]  INFO -- : products/firebasehosting: Compiling provider config
I, [2023-07-27T01:06:26.693409 #9575]  INFO -- : products/dns: Compiling provider config
I, [2023-07-27T01:06:26.716998 #9576]  INFO -- : products/firebasehosting: Not specified, skipping generation
I, [2023-07-27T01:06:26.722379 #9575]  INFO -- : products/dns: Not specified, skipping generation
I, [2023-07-27T01:06:26.738706 #9577]  INFO -- : products/firestore: Compiling provider config
I, [2023-07-27T01:06:26.750084 #9575]  INFO -- : products/gkehub: Compiling provider config
I, [2023-07-27T01:06:26.767786 #9577]  INFO -- : products/firestore: Not specified, skipping generation
I, [2023-07-27T01:06:26.781766 #9575]  INFO -- : products/gkehub: Not specified, skipping generation
I, [2023-07-27T01:06:26.792695 #9576]  INFO -- : products/gkebackup: Compiling provider config
I, [2023-07-27T01:06:26.795837 #9574]  INFO -- : products/gameservices: Compiling provider config
I, [2023-07-27T01:06:26.809150 #9577]  INFO -- : products/gkehub2: Compiling provider config
I, [2023-07-27T01:06:26.811137 #9574]  INFO -- : products/gameservices: Not specified, skipping generation
I, [2023-07-27T01:06:26.813262 #9576]  INFO -- : products/gkebackup: Not specified, skipping generation
I, [2023-07-27T01:06:26.843129 #9577]  INFO -- : products/gkehub2: Not specified, skipping generation
I, [2023-07-27T01:06:26.864664 #9576]  INFO -- : products/iam2: Compiling provider config
I, [2023-07-27T01:06:26.880909 #9577]  INFO -- : products/iambeta: Compiling provider config
I, [2023-07-27T01:06:26.890050 #9576]  INFO -- : products/iam2: Not specified, skipping generation
I, [2023-07-27T01:06:26.903744 #9577]  INFO -- : products/iambeta: Not specified, skipping generation
I, [2023-07-27T01:06:26.908477 #9573]  INFO -- : products/dialogflowcx: Compiling provider config
I, [2023-07-27T01:06:26.927811 #9576]  INFO -- : products/iamworkforcepool: Compiling provider config
I, [2023-07-27T01:06:26.929756 #9574]  INFO -- : products/healthcare: Compiling provider config
I, [2023-07-27T01:06:26.937419 #9573]  INFO -- : products/dialogflowcx: Not specified, skipping generation
I, [2023-07-27T01:06:26.949289 #9577]  INFO -- : products/iap: Compiling provider config
I, [2023-07-27T01:06:26.953860 #9574]  INFO -- : products/healthcare: Not specified, skipping generation
I, [2023-07-27T01:06:26.955650 #9576]  INFO -- : products/iamworkforcepool: Not specified, skipping generation
I, [2023-07-27T01:06:26.978255 #9577]  INFO -- : products/iap: Not specified, skipping generation
I, [2023-07-27T01:06:27.020470 #9574]  INFO -- : products/kms: Compiling provider config
I, [2023-07-27T01:06:27.037916 #9576]  INFO -- : products/logging: Compiling provider config
I, [2023-07-27T01:06:27.047981 #9574]  INFO -- : products/kms: Not specified, skipping generation
I, [2023-07-27T01:06:27.067267 #9576]  INFO -- : products/logging: Not specified, skipping generation
I, [2023-07-27T01:06:27.069242 #9573]  INFO -- : products/identityplatform: Compiling provider config
I, [2023-07-27T01:06:27.088267 #9577]  INFO -- : products/looker: Compiling provider config
I, [2023-07-27T01:06:27.104260 #9573]  INFO -- : products/identityplatform: Not specified, skipping generation
I, [2023-07-27T01:06:27.116496 #9573]  INFO -- : products/mlengine: Compiling provider config
I, [2023-07-27T01:06:27.120060 #9577]  INFO -- : products/looker: Not specified, skipping generation
I, [2023-07-27T01:06:27.130664 #9574]  INFO -- : products/memcache: Compiling provider config
I, [2023-07-27T01:06:27.149362 #9573]  INFO -- : products/mlengine: Not specified, skipping generation
I, [2023-07-27T01:06:27.160725 #9576]  INFO -- : products/metastore: Compiling provider config
I, [2023-07-27T01:06:27.161893 #9574]  INFO -- : products/memcache: Not specified, skipping generation
I, [2023-07-27T01:06:27.183867 #9573]  INFO -- : products/networkmanagement: Compiling provider config
I, [2023-07-27T01:06:27.193369 #9576]  INFO -- : products/metastore: Not specified, skipping generation
I, [2023-07-27T01:06:27.204961 #9579]  INFO -- : products/datastream: Compiling provider config
I, [2023-07-27T01:06:27.211448 #9573]  INFO -- : products/networkmanagement: Not specified, skipping generation
I, [2023-07-27T01:06:27.239766 #9579]  INFO -- : products/datastream: Not specified, skipping generation
I, [2023-07-27T01:06:27.259139 #9579]  INFO -- : products/orgpolicy: Compiling provider config
I, [2023-07-27T01:06:27.312905 #9579]  INFO -- : products/orgpolicy: Not specified, skipping generation
I, [2023-07-27T01:06:27.333410 #9574]  INFO -- : products/networksecurity: Compiling provider config
I, [2023-07-27T01:06:27.365620 #9574]  INFO -- : products/networksecurity: Not specified, skipping generation
I, [2023-07-27T01:06:27.381761 #9574]  INFO -- : products/oslogin: Compiling provider config
I, [2023-07-27T01:06:27.414004 #9574]  INFO -- : products/oslogin: Not specified, skipping generation
I, [2023-07-27T01:06:27.538557 #9573]  INFO -- : products/notebooks: Compiling provider config
I, [2023-07-27T01:06:27.580039 #9573]  INFO -- : products/notebooks: Not specified, skipping generation
I, [2023-07-27T01:06:27.595151 #9573]  INFO -- : products/publicca: Compiling provider config
I, [2023-07-27T01:06:27.627026 #9573]  INFO -- : products/publicca: Not specified, skipping generation
I, [2023-07-27T01:06:27.697705 #9573]  INFO -- : products/pubsub: Compiling provider config
I, [2023-07-27T01:06:27.732899 #9573]  INFO -- : products/pubsub: Not specified, skipping generation
I, [2023-07-27T01:06:27.768198 #9577]  INFO -- : products/monitoring: Compiling provider config
I, [2023-07-27T01:06:27.781335 #9573]  INFO -- : products/pubsublite: Compiling provider config
I, [2023-07-27T01:06:27.813264 #9577]  INFO -- : products/monitoring: Not specified, skipping generation
I, [2023-07-27T01:06:27.816233 #9573]  INFO -- : products/pubsublite: Not specified, skipping generation
I, [2023-07-27T01:06:27.825902 #9573]  INFO -- : products/resourcemanager: Compiling provider config
I, [2023-07-27T01:06:27.851566 #9573]  INFO -- : products/resourcemanager: Not specified, skipping generation
I, [2023-07-27T01:06:27.858863 #9573]  INFO -- : products/runtimeconfig: Compiling provider config
I, [2023-07-27T01:06:27.886204 #9573]  INFO -- : products/runtimeconfig: Not specified, skipping generation
I, [2023-07-27T01:06:27.921173 #9573]  INFO -- : products/secretmanager: Compiling provider config
I, [2023-07-27T01:06:27.935953 #9577]  INFO -- : products/redis: Compiling provider config
I, [2023-07-27T01:06:27.954162 #9573]  INFO -- : products/secretmanager: Not specified, skipping generation
I, [2023-07-27T01:06:27.963492 #9577]  INFO -- : products/redis: Not specified, skipping generation
I, [2023-07-27T01:06:27.976024 #9573]  INFO -- : products/securitycenter: Compiling provider config
I, [2023-07-27T01:06:27.999113 #9577]  INFO -- : products/securityscanner: Compiling provider config
I, [2023-07-27T01:06:28.000967 #9573]  INFO -- : products/securitycenter: Not specified, skipping generation
I, [2023-07-27T01:06:28.081114 #9573]  INFO -- : products/servicedirectory: Compiling provider config
I, [2023-07-27T01:06:28.097578 #9577]  INFO -- : products/securityscanner: Not specified, skipping generation
I, [2023-07-27T01:06:28.143943 #9577]  INFO -- : products/servicemanagement: Compiling provider config
I, [2023-07-27T01:06:28.173771 #9573]  INFO -- : products/servicedirectory: Not specified, skipping generation
I, [2023-07-27T01:06:28.186027 #9577]  INFO -- : products/servicemanagement: Not specified, skipping generation
I, [2023-07-27T01:06:28.194138 #9573]  INFO -- : products/serviceusage: Compiling provider config
I, [2023-07-27T01:06:28.204210 #9577]  INFO -- : products/sourcerepo: Compiling provider config
I, [2023-07-27T01:06:28.220377 #9573]  INFO -- : products/serviceusage: Not specified, skipping generation
I, [2023-07-27T01:06:28.227107 #9577]  INFO -- : products/sourcerepo: Not specified, skipping generation
I, [2023-07-27T01:06:28.252724 #9577]  INFO -- : products/sql: Compiling provider config
I, [2023-07-27T01:06:28.263968 #9573]  INFO -- : products/spanner: Compiling provider config
I, [2023-07-27T01:06:28.284062 #9577]  INFO -- : products/sql: Not specified, skipping generation
I, [2023-07-27T01:06:28.292207 #9573]  INFO -- : products/spanner: Not specified, skipping generation
I, [2023-07-27T01:06:28.301330 #9573]  INFO -- : products/storagetransfer: Compiling provider config
I, [2023-07-27T01:06:28.314798 #9579]  INFO -- : products/osconfig: Compiling provider config
I, [2023-07-27T01:06:28.330198 #9575]  INFO -- : products/gkeonprem: Compiling provider config
I, [2023-07-27T01:06:28.334129 #9573]  INFO -- : products/storagetransfer: Not specified, skipping generation
I, [2023-07-27T01:06:28.353257 #9579]  INFO -- : products/osconfig: Not specified, skipping generation
I, [2023-07-27T01:06:28.370445 #9573]  INFO -- : products/tags: Compiling provider config
I, [2023-07-27T01:06:28.375048 #9575]  INFO -- : products/gkeonprem: Not specified, skipping generation
I, [2023-07-27T01:06:28.382270 #9579]  INFO -- : products/tpu: Compiling provider config
I, [2023-07-27T01:06:28.407783 #9573]  INFO -- : products/tags: Not specified, skipping generation
I, [2023-07-27T01:06:28.424304 #9576]  INFO -- : products/networkservices: Compiling provider config
I, [2023-07-27T01:06:28.553272 #9579]  INFO -- : products/tpu: Not specified, skipping generation
I, [2023-07-27T01:06:28.602736 #9576]  INFO -- : products/networkservices: Not specified, skipping generation
I, [2023-07-27T01:06:28.608110 #9579]  INFO -- : products/vpcaccess: Compiling provider config
I, [2023-07-27T01:06:28.633476 #9573]  INFO -- : products/vmwareengine: Compiling provider config
I, [2023-07-27T01:06:28.677264 #9576]  INFO -- : products/workflows: Compiling provider config
I, [2023-07-27T01:06:28.695969 #9579]  INFO -- : products/vpcaccess: Not specified, skipping generation
I, [2023-07-27T01:06:28.725000 #9577]  INFO -- : products/storage: Compiling provider config
I, [2023-07-27T01:06:28.733248 #9573]  INFO -- : products/vmwareengine: Not specified, skipping generation
I, [2023-07-27T01:06:28.734801 #9576]  INFO -- : products/workflows: Not specified, skipping generation
I, [2023-07-27T01:06:28.771175 #9577]  INFO -- : products/storage: Not specified, skipping generation
I, [2023-07-27T01:06:28.792771 #9579]  INFO -- : products/accessapproval: Compiling provider config
I, [2023-07-27T01:06:28.825386 #9579]  INFO -- : products/accessapproval: Not specified, skipping generation
I, [2023-07-27T01:06:28.893902 #9575]  INFO -- : products/vertexai: Compiling provider config
I, [2023-07-27T01:06:28.910785 #9573]  INFO -- : products/workstations: Compiling provider config
I, [2023-07-27T01:06:28.912865 #9575]  INFO -- : products/vertexai: Not specified, skipping generation
I, [2023-07-27T01:06:28.925585 #9573]  INFO -- : products/workstations: Not specified, skipping generation
I, [2023-07-27T01:06:29.168138 #9574]  INFO -- : products/privateca: Compiling provider config
I, [2023-07-27T01:06:29.184694 #9574]  INFO -- : products/privateca: Not specified, skipping generation
I, [2023-07-27T01:06:32.030978 #9572]  INFO -- : products/compute: Compiling provider config
I, [2023-07-27T01:06:32.046602 #9572]  INFO -- : products/compute: Not specified, skipping generation
I, [2023-07-27T01:06:33.053277 #9578]  INFO -- : products/dlp: Compiling provider config
I, [2023-07-27T01:06:33.067681 #9578]  INFO -- : products/dlp: Not specified, skipping generation
bundler: failed to load command: compiler.rb (compiler.rb)
compiler.rb:319:in `<top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)

provider = final_product[:provider]
                        ^^^^^^^^^^^
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
	from /Users/tsubasanagasawa/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
make[1]: *** [mmv1] Error 1
make: *** [provider] Error 2
</code>
</pre>
</details>

Provider code generation without `PRODUCT=container` filter succeeds.

<details>
<summary><code>make provider VERSION=beta OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta"</code></summary>
<pre>
<code>
make mmv1
cd mmv1;\
		bundle; \
		bundle exec compiler.rb -e terraform -o /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta -v beta -a;
Using rake 13.0.6
Using concurrent-ruby 1.2.0
Using i18n 1.12.0
Using minitest 5.17.0
Using tzinfo 2.0.6
Using activesupport 7.0.4.2
Using ast 2.4.2
Using debug_inspector 1.1.0
Using binding_of_caller 1.0.0
Using bundler 2.4.6
Using diff-lcs 1.5.0
Using json 2.6.3
Using metaclass 0.0.4
Using mocha 1.3.0
Using openapi_parser 1.0.0
Using parallel 1.22.1
Using parser 3.2.0.0
Using rainbow 3.1.1
Using regexp_parser 2.6.2
Using rexml 3.2.5
Using rspec-support 3.12.0
Using rspec-core 3.12.1
Using rspec-expectations 3.12.2
Using rspec-mocks 3.12.3
Using rspec 3.12.0
Using rubocop-ast 1.24.1
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.4.2
Using rubocop 1.44.1
Bundle complete! 8 Gemfile dependencies, 29 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
I, [2023-07-27T01:09:27.925279 #10427]  INFO -- : Generating MM output to '/Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta'
I, [2023-07-27T01:09:27.925433 #10427]  INFO -- : Using beta version
I, [2023-07-27T01:09:27.994275 #10444]  INFO -- : products/activedirectory: Compiling provider config
(...)
I, [2023-07-27T01:10:14.690590 #10427]  INFO -- : Copying common files for terraform
I, [2023-07-27T01:10:15.294648 #10427]  INFO -- : Compiling common files for terraform
make tpgtools
make serialize
cd tpgtools;\
		cp -f serialization.go.base serialization.go &&\
		go run . --path "api" --overrides "overrides" --mode "serialization" > temp.serial &&\
		mv -f temp.serial serialization.go
E0727 10:10:23.454564   16084 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:23.463721   16084 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:23.476108   16084 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:23.481576   16084 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:23.527638   16084 resource.go:800] skipping "storage_release.tf.tmpl" due to no version match
cd tpgtools;\
		go run . --output /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta --version beta  --path "api" --overrides "overrides"
E0727 10:10:26.312276   16137 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:26.316606   16137 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:26.325884   16137 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:26.329765   16137 resource.go:800] skipping "beta_basic.tf.tmpl" due to no version match
E0727 10:10:26.362263   16137 resource.go:800] skipping "storage_release.tf.tmpl" due to no version match
 google_cloudbuild_worker_pool            no samples, skipping doc generation
 google_compute_firewall_policy           no samples, skipping doc generation
 google_compute_firewall_policy_association no samples, skipping doc generation
 google_dataproc_workflow_template        no samples, skipping doc generation
 google_gke_hub_feature_membership        no samples, skipping doc generation
make teamcity-servicemap-generate
cd tools/teamcity-generator;\
		go run . --output /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta --version beta
2023/07/27 10:10:27 Generating TeamCity configuration service package map for `google-beta` provider
2023/07/27 10:10:27 Opening /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta/.teamcity/components/generated/services.kt
2023/07/27 10:10:27 Saving service map to /Users/tsubasanagasawa/go/src/github.com/hashicorp/terraform-provider-google-beta/.teamcity/components/generated/services.kt
2023/07/27 10:10:27 Finished
</code>
</pre>
</details>

**Comment by ScottSuarez** [comment]
Thanks for the issue!!!
fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8471
