### ISSUE TITLE
Add support for defaultSearchHandlingStrict in FHIR Stores

### ISSUE THREAD

**Issue by kklin5** [hashicorp/terraform-provider-google#15316]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the Cloud Healthcare API, there is a feature that allows users to configure default search handling strict, which configures whether to ignore unrecognized search params.

Currently, the only way to set this flag in the FHIR store config is by calling the API through a curl command:

```
curl -X PATCH     -H "Authorization: Bearer $(gcloud auth print-access-token)"  \
            -H "Content-Type: application/json; charset=utf-8" \
            -d '{"defaultSearchHandlingStrict":"ENABLED"}'
            "https://healthcare.googleapis.com/v1/projects/PROJECT_ID/locations/LOCATION/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID?update_mask=defaultSearchHandlingStrict"
```
It would be great if this can be configured through terraform.

### New or Affected Resource(s)

* google_healthcare_fhir_store

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_healthcare_fhir_store" "default" {
  provider = google-beta
  name    = "example-fhir-store"
  dataset = google_healthcare_dataset.default.id
  version = "R4"

  enable_update_create          = true
  disable_referential_integrity = false
  disable_resource_versioning   = false
  enable_history_import         = false
   
  ...
  default_search_handling_strict=true
```

### References

* [https://cloud.google.com/healthcare-api/docs/reference/rest/v1/projects.locations.datasets.fhirStores#FhirStore.FIELDS.default_search_handling_strict](https://cloud.google.com/healthcare-api/docs/reference/rest/v1/projects.locations.datasets.fhirStores#FhirStore.FIELDS.default_search_handling_strict)

* b/293782025

**Comment by kklin5** [comment]
Can be implemented similar to https://github.com/hashicorp/terraform-provider-google/issues/14829

**Comment by DanielRieske** [comment]
I'll gladly pick this issue up, I will add the PR shortly.
