### ISSUE TITLE
Add `accelerators` to `google_workstations_workstation_config`

### ISSUE THREAD

**Issue by ConnorD** [hashicorp/terraform-provider-google#15311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Creating a Cloud Workstations configuration via the Beta REST API supports passing an `accelerators` argument in order to add GPUs ([see this Gist for example](https://gist.github.com/ConnorD/239e2f9d8527d5de2c05af3301328350#file-configurations-tf-L18)). The Google Terraform Provider doesn't have support for this yet.

### New or Affected Resource(s)

google_workstations_workstation_config

### Potential Terraform Configuration

```tf
resource "google_workstations_workstation_config" "default" {
  ...

  host {
    gce_instance {
      ...

      accelerators = [
        {
          type  = "nvidia-tesla-t4"
          count = 1
        },
      ]
    }
  }
}
```

**Comment by DanielRieske** [comment]
I'll gladly pick this issue up, i'll add the PR shortly.
