### ISSUE TITLE
Replace pull_external with external_providers in example definitions

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#15312]
# Background

We used to include the `random` provider on every single test in the Terraform provider; however, this added some latency and introduced an additional failure mode for test cases if the external provider was temporarily unavailable. As a result, we [made it possible](https://github.com/GoogleCloudPlatform/magic-modules/pull/4663) to set [`pull_external: true`](https://github.com/GoogleCloudPlatform/magic-modules/blob/65513bcdd7b3e97a80513de00abaa844971cb410/mmv1/provider/terraform/examples.rb#L150) in the example YAML config for tests that specifically needed the `random` provider. This was later expanded to include the `time` provider.

However, this implementation has a couple of issues. First, `pull_external` implies that _all_ external providers will be pulled, when in fact it's a specific set. Second, there is no way to add additional external providers (such as the `tls` provider) which may be useful for specific test cases.

We should:

1. switch to having an attribute called `external_providers` that allows examples to specify exactly which providers they need
2. iterate over that list in the [test_file template](https://github.com/GoogleCloudPlatform/magic-modules/blob/65513bcdd7b3e97a80513de00abaa844971cb410/mmv1/templates/terraform/examples/base_configs/test_file.go.erb#L83) to add all specified providers
3. Update configurations using pull_external to instead explicitly state what providers are needed

# What kind of contribution is this issue about?

* MMv1-based resource

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/8451#pullrequestreview-1548365218

**Comment by melinath** [comment]
We should use an allowlist of "safe" external providers to prevent arbitrary (potentially unsafe) providers from being added. (Or for example only allow providers published by Hashicorp.)

**Comment by zli82016** [comment]
Yeah, this is the new ticket https://github.com/hashicorp/terraform-provider-google/issues/18051
