### ISSUE TITLE
Missing a way to configure allowed domains on IAP

### ISSUE THREAD

**Issue by tino** [hashicorp/terraform-provider-google#15354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Once setting up Identity-Aware Proxy through Terraform, you run into an error 52, which is described here: https://cloud.google.com/iap/docs/allowed-domains#gcloud. Adding those allowed domains cannot be done from terraform – at least I can't find a documented way how to.

### New or Affected Resource(s)

I'm not sure if this should be a new resource, or part of the `iap` block of `google_compute_backend_service`?

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

How to accomplish it with the API is defined here: https://cloud.google.com/iap/docs/allowed-domains#configure_allowed_domains.

b/298050328

**Comment by bryan0515** [comment]
Duplicate - github.com/hashicorp/terraform-provider-google/issues/6471

**Comment by melinath** [comment]
duplicate
