### ISSUE TITLE
Cloud Storage Subscription for PubSub

### ISSUE THREAD

**Issue by userbradley** [hashicorp/terraform-provider-google#15352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

 

### Description

Google have today released cloud storage subscriptions for PubSub

https://cloud.google.com/blog/products/data-analytics/pubsub-cloud-storage-subscriptions-for-streaming-data-ingestion

### New or Affected Resource(s)

* `google_pubsub_subscription`

### Potential Terraform Configuration

Not too sure yet

### References

* https://cloud.google.com/pubsub/docs/cloudstorage
* https://cloud.google.com/blog/products/data-analytics/pubsub-cloud-storage-subscriptions-for-streaming-data-ingestion
* https://cloud.google.com/pubsub/docs/create-cloudstorage-subscription

**Comment by DanielRieske** [comment]
Hiya, this would require the addition of `CloudStorageConfig` to the existing subscription resource.

In any case, I'd like to pick this issue up.

https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#CloudStorageConfig
