### ISSUE TITLE
Is it possible to publish my app in azure/aws marketplace using Terraform ?

### ISSUE THREAD

**Issue by Nimmalapudi-Pratyusha** [hashicorp/terraform-provider-google#15353]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by Nimmalapudi-Pratyusha** [comment]
@edwardmedia I know for a fact that we can use the templates provided by the respective cloud vendors ,ex : CloudFormation templates by AWS and ARM templates by Azure ,so wanted to know if we could use terraform here

**Comment by edwardmedia** [comment]
@Nimmalapudi-Pratyusha sorry no clue to what you are talking about. If a feature GCP supports, likely it is possible it can be supported via Terraform, but I need to know what features you are talking about.  Does that make sense?

**Comment by edwardmedia** [comment]
@Nimmalapudi-Pratyusha closing this. Feel free to reopen if you have the answer
