### ISSUE TITLE
Support deprecation message at the resource level

### ISSUE THREAD

**Issue by rainshen49** [hashicorp/terraform-provider-google#15378]
# Background

Currently, [deprecation_message](https://github.com/GoogleCloudPlatform/magic-modules/blob/2a0393a3c9762599e729a5234f48d41d44585234/mmv1/api/type.rb#L32) is supported on a per field basis. Is there an equivalent on the resource level?
# What kind of contribution is this issue about?
* MMv1-based resource

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/8301

# Details

 In order to perform the first step of [Provider Data Source or Resource Removal](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-data-source-or-resource-removal), I seem to have to convert an entire resource to handwritten just to add a DeprecationMessage.

**Comment by rileykarson** [comment]
This should be possible in a resource_definition today: https://github.com/GoogleCloudPlatform/magic-modules/blob/2a0393a3c9762599e729a5234f48d41d44585234/mmv1/provider/terraform/custom_code.rb#L38-L43

We should add a dedicated attribute for it though, similar to some other things we've migrated out of resource definition:

**Comment by rainshen49** [comment]
This is helpful. I'm going to keep this issue open in case the team decides to work on adding a dedicated attribute.

**Comment by melinath** [comment]
This was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8696
