### ISSUE TITLE
Issues import data_managed_zone

### ISSUE THREAD

**Issue by RastogiAbhijeet** [hashicorp/terraform-provider-google#15371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.3

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Panic Output

╷
│ Error: Plugin did not respond
│ 
│   with google_cloud_scheduler_job.charger-logs-accumulator,
│   on schedulers.tf line 35, in resource "google_cloud_scheduler_job" "charger-logs-accumulator":
│   35: resource "google_cloud_scheduler_job" "charger-logs-accumulator" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with google_project_iam_binding.deployer-iam-binding,
│   on service-accounts.tf line 6, in resource "google_project_iam_binding" "deployer-iam-binding":
│    6: resource "google_project_iam_binding" "deployer-iam-binding" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-google_v4.74.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 749 [running]:
github.com/hashicorp/terraform-provider-google/google/services/dns.(*GoogleDnsRecordSetDataSource).Read(0x140016fb500, {0x1037bc7f8, 0x14000c9e570}, {{{{0x1037c4550, 0x140011dc3c0}, {0x1033040a0, 0x14000c9f230}}, {0x1037c5b38, 0x14000c90ec0}}, {{{0x1037c4550, ...}, ...}, ...}}, ...)
        github.com/hashicorp/terraform-provider-google/google/services/dns/data_source_dns_record_set.go:147 +0xa48
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x14000117340, {0x1037bc7f8, 0x14000c9e570}, 0x14000c9e720, 0x14001e6d3d8)
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/fwserver/server_readdatasource.go:75 +0x3a4
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadDataSource(0x14000117340, {0x1037bc7f8?, 0x14000c9e420?}, 0x140006ec500)
        github.com/hashicorp/terraform-plugin-framework@v1.1.1/internal/proto5server/server_readdatasource.go:52 +0x1b0
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadDataSource({0x14000c6ac60, 0x14000c6acc0, {0x14000d16ba0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadDataSource.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0x14000d76960, {0x1037bc7f8?, 0x14000fe82d0?}, 0x14000ddd130)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1036f96a0?, 0x14000d76960}, {0x1037bc7f8, 0x14000fe82d0}, 0x140004e0700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000d3a780, {0x1037c49c0, 0x1400067a1a0}, 0x140013539e0, 0x14000fbbfb0, 0x104a5d9b0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x14000d3a780, {0x1037c49c0, 0x1400067a1a0}, 0x140013539e0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x16c

Error: The terraform-provider-google_v4.74.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@RastogiAbhijeet  do you have the data source of `google_dns_record_set` in your config? Are you able to repro the issue? Please detail the steps and other resources & data sources in your config.

**Comment by edwardmedia** [comment]
@RastogiAbhijeet is this still an issue?

**Comment by edwardmedia** [comment]
@RastogiAbhijeet closing this now. Please reopen once you have the details
