### ISSUE TITLE
Allow reducing the suffix length appended to instance templates name_prefix

### ISSUE THREAD

**Issue by ralbertazzi** [hashicorp/terraform-provider-google#15374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Instance template resources provide a great [name_prefix](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#name_prefix) variable that allows using instance templates effectively on top of instance group managers. From what I can observe on the Google Cloud Console (which is validated by the [equivalent code](https://github.com/hashicorp/terraform-provider-google/blob/979425d490050c8e6c6612b7af7db6ba0c5e2dd3/google/services/compute/resource_compute_instance_template.go#L82-L97)) a date-like suffix is appended to the `name_prefix` so that changes to instance templates in Terraform can result in the creation of different template resources with different names.

In our project we use a high number of instance groups (and corresponding templates) for which we'd like to set self-explanatory names, where ideally the instance group name is equal to the name prefix of its instance template. However, this is sometimes not possible because of the 37 characters length limitation required by the `name_prefix`. In this case, we have to come up with shorter names that feel like a hack and are not really self-explanatory.

While I see the reason for the suffix to be appended, I'm wondering if it would be possible to make it configurable such that we can append a shorter suffix, leaving more characters to the `name_prefix`. For instance I see that the suffix has some format `20230801144601276600000001` which contains the creation date up to seconds granularity (`20230801144601`) plus an extra suffix (`276600000001`). Since I don't expect in my case to create multiple instance templates with the same `name_prefix` within 1 second, I would be fine having just the first part of the suffix and dropping the second one. Another idea would be to use a short hash (4-6 characters) of the instance template parameters, which would leave me with almost 60 characters usable for the `name_prefix`.

### New or Affected Resource(s)

* google_compute_region_instance_template
* google_compute_instance_template

b/312433567

**Comment by rileykarson** [comment]
We'd evaluate changing the default here as part of a major version. We don't want to add a knob, or change the format in a minor version.

**Comment by c2thorn** [comment]
Noting that we are intending to reduce the appended suffix in `name_prefix` globally, essentially changing the default value for many resources. This is a breaking change and is intended for the 6.0.0 major release.

**Comment by c2thorn** [comment]
> Noting that we are intending to reduce the appended suffix in `name_prefix` globally, essentially changing the default value for many resources. This is a breaking change and is intended for the 6.0.0 major release.

We couldn't land on a new UUID suffix that we felt wasn't prone to collisions. So we are keeping the current behavior for `name_prefix`'s less than 38 characters, but allowing a new max of up to **54 characters** with a shortened UUID suffix.

Current configs should not see the new behavior when upgrading to 6.0 unless changing the `name_prefix` to a length of 37 - 54 characters.

Resulting name for a `name_prefix` <= 37 characters:
`name_prefix` + YYYYmmddHHSSssss + 8 digit incremental counter
Resulting name for a `name_prefix` 38 - 54 characters:
`name_prefix` + YYmmdd + 3 digit incremental counter

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11448
