### ISSUE TITLE
google_bigquery_table expects schema at the top-level rather than in external_data_configuration

### ISSUE THREAD

**Issue by zakwalters** [hashicorp/terraform-provider-google#15377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.73.2
+ provider registry.terraform.io/hashicorp/google-beta v4.75.0
```

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

Adapted to use generic names and a simplified schema:

```tf
resource "google_bigquery_table" "events" {
  project       = local.project_id
  dataset_id    = google_bigquery_dataset.my_dataset.dataset_id
  table_id      = "events"

  external_data_configuration {
    source_format         = "NEWLINE_DELIMITED_JSON"
    source_uris           = ["gs://${module.my_bucket.name}/*"]
    connection_id         = google_bigquery_connection.my_connection.id
    autodetect            = false
    ignore_unknown_values = true
    schema = <<EOF
[
  { "name": "event", "type": "STRING" },
  { "name": "createdAt", "type": "TIMESTAMP" }
]
EOF
  }
}
```

### Debug Output

> Error: googleapi: 
> Error 400: Schema can be specified only on the Table.Schema field for external tables with an associated connection_id but schema was provided on Table.Externaldataconfig.Schema., invalid
> with google_bigquery_table.events
> on bigquery.tf line 16, in resource "google_bigquery_table" "events":
> `resource "google_bigquery_table" "events" {`

### Expected Behavior

According to the docs [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table.html#schema), we should specify the `schema` in `external_data_configuration.schema`. So the configuration above should `apply` successfully.

### Actual Behavior

When running `terraform apply`, we get the error mentioned above:

> Schema can be specified only on the Table.Schema field for external tables with an associated connection_id but schema was provided on Table.Externaldataconfig.Schema., invalid

In order to fix it, we had to move the `schema` definition to `google_bigquery_table.schema` - exactly where the docs say it _shouldn't_ go in this case:

```tf
resource "google_bigquery_table" "events" {
  project       = local.project_id
  dataset_id    = google_bigquery_dataset.my_dataset.dataset_id
  table_id      = "events"
  # This is moved out of external_data_configuration
  schema = <<EOF
[
  { "name": "event", "type": "STRING" },
  { "name": "createdAt", "type": "TIMESTAMP" }
]
EOF

  external_data_configuration {
    source_format         = "NEWLINE_DELIMITED_JSON"
    source_uris           = ["gs://${module.my_bucket.name}/*"]
    connection_id         = google_bigquery_connection.my_connection.id
    autodetect            = false
    ignore_unknown_values = true
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

n/a

### References

Couldn't find any open issues for this by looking for `external_data_configuration`.

The docs for the resource are [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table.html), and state:

> When setting schema for external_data_configuration, please use external_data_configuration.schema [documented below](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table.html#nested_external_data_configuration).

**Comment by edwardmedia** [comment]
b/294364642

**Comment by nevzheng** [comment]
Hi BigLake SWE here,

Would you mind sharing doing a TF_TRACE and showing us what the HTTP Requests/Response look like?

**Comment by wj-chen** [comment]
This looks to be working-as-intended. Schema should be specified in ExternalDataConfig **except** when a Connection ID is present. The error message indicates so - "Schema can be specified only on the Table.Schema field for external tables **with an associated connection_id** but schema was provided on Table.Externaldataconfig.Schema." I see explicit validations in the backend in this case. Let us know if you need more clarifications.

**Comment by wj-chen** [comment]
> > **except** when a Connection ID is present
> 
> This part is not specified in [the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table.html). Until I got that error back, there was no indication that specifying a connection ID would require a different approach. Given the fact that the docs disagreed with the error, I didn't have much confidence that applying the fix suggested in the error message would work until I tried it.
> 
> I think the best fix would be to update this warning with that extra detail: ![Screenshot 2023-08-08 at 14 51 11](https://user-images.githubusercontent.com/15427477/259122049-87d61b40-4ee3-4de4-9c14-c078fdd4bc6d.png)
> 
> It would be good to include some reference to this case in the description for `external_data_configuration.connection_id` too.

That makes sense. We will look into calling out this special case in the docs.
