### ISSUE TITLE
Support for creating revisions in google_pubsub_schema

### ISSUE THREAD

**Issue by kiewel** [hashicorp/terraform-provider-google#15376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
For now we don't have any option to create revision of pub sub schema in Terraform. This implies that every time we modify a schema it is recreated and we need to run TF again to assign new schema to the topic.
Also we don't have versioning.

It would be great if you could add this feature.

### New or Affected Resource(s)

* google_pubsub_schema

### Potential Terraform Configuration

```tf

resource "google_pubsub_schema" "example" {
  name = "example"
  revision = "someID"
  type = "AVRO"
  definition = "{\n  \"type\" : \"record\",\n  \"name\" : \"Avro\",\n  \"fields\" : [\n    {\n      \"name\" : \"StringField\",\n      \"type\" : \"string\"\n    },\n    {\n      \"name\" : \"IntField\",\n      \"type\" : \"int\"\n    }\n  ]\n}\n"
}

```

### References

* #0000

b/294553724

**Comment by bschaatsbergen** [comment]
This will be a bit tough to implement, as `revisionId` is an output only parameter in the [API reference](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.schemas#Schema)... hmmm..

**Comment by rileykarson** [comment]
This works as of `4.70.0`: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.70.0

We should document it more clearly, though. Update the definition creates a revision right now. Alongside the service team, we decided to support creating revisions but not deleting them through Terraform. A user would need to manually intervene to delete them (even if they've hit the max 20 limit).

**Comment by bschaatsbergen** [comment]
Happy to create a PR to document this more clearly. Consider it done tomorrow 😉👍🏼

**Comment by rileykarson** [comment]
Related: https://github.com/hashicorp/terraform-provider-google/issues/15228

**Comment by kiewel** [comment]
Thanks for your support. Now I see that it is sorted in the newest release
