### ISSUE TITLE
cluster_autoscaling resource_limits keeps showing in plan.

### ISSUE THREAD

**Issue by craiggunson** [hashicorp/terraform-provider-google#15403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)
[google_container_cluster](https://registry.terraform.io/providers/hashicorp/google/4.75.1/docs/resources/container_cluster.html) 

### Terraform Configuration Files
```
  cluster_autoscaling {
    enabled = true

    auto_provisioning_defaults {
      image_type = "COS_CONTAINERD"
    }
  }
```  

```

### Debug Output
```
      ~ cluster_autoscaling {
            # (1 unchanged attribute hidden)

          - resource_limits {
              - maximum       = 12 -> null
              - minimum       = 6 -> null
              - resource_type = "cpu" -> null
            }
          - resource_limits {
              - maximum       = 96 -> null
              - minimum       = 48 -> null
              - resource_type = "memory" -> null
            }

```
### Expected Behavior
These resource_limits were deleted some time ago, but never seem to apply. 

### Actual Behavior
Keeps showing in plan, and apply does nothing to change it.

### Steps to Reproduce
Put in some resource limits, apply, delete them, apply.

**Comment by edwardmedia** [comment]
b/294901462
