### ISSUE TITLE
Shutdown & Start Google Compute VM using terraform

### ISSUE THREAD

**Issue by apoorvanand** [hashicorp/terraform-provider-google#15408]
Does google terraform provider modules support vm shutdown and start using terraform?

**Comment by edwardmedia** [comment]
@apoorvanand you might want to review tools of imperative vs declarative. I do not believe Terraform is a good tool to handle that.

**Comment by apoorvanand** [comment]
> @apoorvanand you might want to review tools of imperative vs declarative. I do not believe Terraform is a good tool to handle that.

I believe automation using google sdk , api or cli would be better option to achive this.
