### ISSUE TITLE
google_dns_response_policy can't delete networks in the update

### ISSUE THREAD

**Issue by theminghuang** [hashicorp/terraform-provider-google#15411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.6

provider version
google           4.68
google-beta  4.68

### Affected Resource(s)

* google_dns_response_policy

### Terraform Configuration Files

Initially I have something like
```tf
resource "google_dns_response_policy" "my_response_policy" {
  provider = google-beta

  project              = "my-project-id"
  response_policy_name = "my-response-policy"

  networks {
    network_url = ***
  }
}
```

then I make the changes to make it cluster scoped instead of network scope
```tf
resource "google_dns_response_policy" "my_response_policy" {
  provider = google-beta

  project              = "my-project-id"
  response_policy_name = "my-response-policy"

  gke_clusters {
    gke_cluster_name = "projects/my-project-id/locations/us-central1/clusters/my-cluster"
  }
}
```

### Debug Output

https://gist.github.com/theminghuang/3d9f15870f86d198a7c844397dbb137b

### Expected Behavior

Expect apply went through succesfully

### Actual Behavior

Failed with "Invalid value for 'entity.gkeClusters[0].project': 'projects/my-project-id/locations/us-central1/clusters/my-cluster'"

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@theminghuang I am not able to repro your issue. From the log you provided, the PATCH request looks good to me. Not sure why the api returns this error. One possible reason is the api was temporally experiencing an issue? Can you retry to see if you can still see the same error?

On the other side, the api fails in removing `networks`. I am engaging the api team to see if there is an explanation. 

b/294730989

**Comment by theminghuang** [comment]
still seeing the same issue after retrying. Did you test the `us-central1` region as well? Wondering if this happen to a specific region only.

**Comment by edwardmedia** [comment]
Yes, I have tried both `us-central1` and `us-central1-a` for the clusters. Can't repro the error you received. @theminghuang

**Comment by edwardmedia** [comment]
Looks like to remove `networks`, we have to send empty `networks` like below to the api

```
 {
  "description": "Managed by Terraform",
   networks:[],
  "gkeClusters": [
   {
    "gkeClusterName": "projects/myproject/locations/us-central1-a/clusters/issue15411"
   }
  ]
 }
```

**Comment by edwardmedia** [comment]
@theminghuang can you share the full debug log?

**Comment by theminghuang** [comment]
let me try to grab one. I'll need to redact some information first.

Actually, one different I noticed between the actual output and the output I attached was that, the google_dns_response_policy is created in a different project than the project containing the cluster

So it's more like
```
resource "google_dns_response_policy" "my_response_policy" {
  provider = google-beta

  project              = "my-project-id-b"
  response_policy_name = "my-response-policy"

  gke_clusters {
    gke_cluster_name = "projects/my-project-id/locations/us-central1/clusters/my-cluster"
  }
}
```
let me know if that makes a difference.

The reason we did this because we have a project as host project for all vpc and networking stuff

**Comment by theminghuang** [comment]
just tested on my side, confirm that if the resources is created within the same project as the cluster, it went through. Is this not a supported operation?

**Comment by edwardmedia** [comment]
@theminghuang have you verified if `my-cluster` is accessible from the project where this resource is created? Likely it is an issue in how you architect the environments, which is beyond the scope of an individual resource. Does that make sense?

**Comment by theminghuang** [comment]
yeah, understood. I believe a gke cluster is scoped to a single project and we cannot have it accessible by multiple projects. We'll create multiple `google_dns_response_policy` instead then. Do you want to update the title to repurpose this issue to focus on the `networks` issue?

**Comment by edwardmedia** [comment]
@theminghuang thank you for confirming. I have updated the subject.

**Comment by edwardmedia** [comment]
To work around, we have to send empty list for [networks](https://github.com/hashicorp/terraform-provider-google/issues/15411#issuecomment-1667846073) to remove it in the update
