### ISSUE TITLE
 Unsupported block type for google_healthcare_fhir_store.notification_configs

### ISSUE THREAD

**Issue by yogitaahire** [hashicorp/terraform-provider-google#15421]
### Terraform Version
4.76.0

### Affected Resource(s)

google_healthcare_fhir_store

### Terraform Configuration Files

```tf

resource "google_healthcare_fhir_store" "fhirstore" {
  name      = join("-",["mt","gcp",var.gcp_environment,"fhir-store"])
  dataset = google_healthcare_dataset.datastore.id
  version = "R4"

  enable_update_create          = true
  disable_referential_integrity = true
  disable_resource_versioning   = false
  enable_history_import         = false

  notification_configs {
    pubsub_topic = google_pubsub_topic.fhirtopic.id
    send_full_resource = true
  }

  depends_on = [
    google_healthcare_dataset.datastore, google_pubsub_topic.fhirtopic
  ]
}

```

### Debug Output
╷
│ Error: Unsupported block type
│ 
│   on healthcaredatastores.tf line 11, in resource "google_healthcare_fhir_store" "fhirstore":
│   11:   notification_configs {
│ 
│ Blocks of type "notification_configs" are not expected here. Did you mean "notification_config"?
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
notification_config is used in the [code](https://github.com/hashicorp/terraform-provider-google/blob/9e0f53678dee1fc4dabaef12380ba3f3bceb81b3/google/services/healthcare/resource_healthcare_fhir_store.go#L146)  for google_healthcare_fhir_store, while the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_fhir_store#example-usage---healthcare-fhir-store-notification-configs) uses notification_configs

Please note notification_configs and notification_config is used for [google_healthcare_hl7_v2_store](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_hl7_v2_store#notification_configs)

**Comment by fcampuzano-medtel** [comment]
@edwardmedia  I am not sure what your comments means, but just to be clear.  It seems like there are two issues here. One with the documentation and one with one of the Arguments:


**Issue with example in documentation: block name should be "notification_config" **

When use the provider version 4.76.0, if you name the block "notification_configs" like shown in the example above, you get the error :

`"Blocks of type "notification_configs" are not expected here. Did you mean "notification_config""`
  
This seems like an issue with the documentation which in one of the examples mentions  "notification_configs".


** Issue with argument "send_full_resource" **

Using the block "notification_config", you will get an error with "send_full_resource = true", 

`│ Error: Unsupported argument
│ 
│   on healthcaredatastores.tf line 13, in resource "google_healthcare_fhir_store" "fhirstore":
│   13:     send_full_resource = true
│ 
│ An argument named "send_full_resource" is not expected here.`
