### ISSUE TITLE
`google_dns_managed_zone.private_visibility_config` incorrectly requires `networks` instead of at least one of `networks` or `gke_clusters`

### ISSUE THREAD

**Issue by nathkn** [hashicorp/terraform-provider-google#15428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.5.4
on darwin_arm64
```

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
resource "google_dns_managed_zone" "foo" {
  project     = "my-project"
  name        = "test"
  dns_name    = "foo."
  description = "foo"

  visibility = "private"

  private_visibility_config {
    gke_clusters {
      gke_cluster_name = "projects/my-project/locations/us-east1/clusters/my-cluster"
    }
  }
}

```

### Debug Output
https://gist.github.com/nathkn/7c255c429e43d890e0ec7796c1da708e

### Expected Behavior

A private managed zone with just gke_clusters in the private_visibility_config should have been created.

### Actual Behavior

It errors and says that `networks` is required:
```tf
$ tf apply 
╷
│ Error: Insufficient networks blocks
│ 
│   on zone.tf line 9, in resource "google_dns_managed_zone" "foo":
│    9:   private_visibility_config {
│ 
│ At least 1 "networks" blocks are required.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
With cluster-scoped dns zones ([cloud.google.com/dns/docs/zones/configure-scopes](https://cloud.google.com/dns/docs/zones/configure-scopes)), you can now specify a zone that applies just to a gke cluster, without applying to the entire network.

This is confirmed by the gcloud output:
```
$ gcloud dns managed-zones create foo --dns-name=foo. --visibility=private --description=foo

ERROR: (gcloud.dns.managed-zones.create) Missing required argument [--networks, --gkeclusters]: If --visibility is set to private, a list of networks or list of GKE clusters must be provided.'  NOTE: You can provide an empty value ("") for private zones that have NO network or GKE clusters binding.
```

Docs: https://cloud.google.com/dns/docs/zones/configure-scopes

**Comment by edwardmedia** [comment]
Similar behavior https://github.com/hashicorp/terraform-provider-google/issues/15411

**Comment by shuyama1** [comment]
This should be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/8581
