### ISSUE TITLE
Getting error to create data fusion build pipeline through terraform script

### ISSUE THREAD

**Issue by shekhar250723** [hashicorp/terraform-provider-google#15437]
**Terraform\GCP> terraform plan**
╷
**│ Error: Invalid resource type
│
│   on main.tf line 21, in resource "google_data_fusion_pipeline" "df_pipeline":
│   21: resource "google_data_fusion_pipeline" "df_pipeline" {
│
│ The provider hashicorp/google does not support resource type "google_data_fusion_pipeline".**

Need support on this to build data fusion pipeline creation through terraform script.

**Comment by edwardmedia** [comment]
@shekhar250723 I don't see google_data_fusion_pipeline in the provider. You may file a [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) to request

**Comment by shekhar250723** [comment]
@edwardmedia Ok, thanks for the update.
