### ISSUE TITLE
Is it possible to register a new cloudsearch provider via Terraform? 

### ISSUE THREAD

**Issue by ThePlenkov** [hashicorp/terraform-provider-google#15438]
Hi!

I was not able to find relevant resource. It would be nice if we could have a module allowing to register new search providers or what is even better in our case - index files. We have plenty of docs projects build with a site builder like vitepress. Most of them have local files with indexed content. So it would be great to have some module allowing us to register such files as search providers.

Thanks!

**Comment by edwardmedia** [comment]
@ThePlenkov Is this feature that is not particular to a specific provider? Sound like a question the terraform core instead?

**Comment by ThePlenkov** [comment]
It's a feature for https://registry.terraform.io/providers/hashicorp/google/latest/docs. I don't know though whether is possible or not in theory.

**Comment by edwardmedia** [comment]
@ThePlenkov I guess you may need it in the terraform module that work with GCP, but the feature sounds like at the Terraform core. I don't think that could be achieved at the provider level. You may reach out the the Terraform core to see if that can assist. If you see a particular gcp api that supports what you need, please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) to request. Closing this question now
