### ISSUE TITLE
Default value is unclear for `request_timeout` in `providerConfigure`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-google#15431]
When looking into the provider configuration block, I noticed that if `request_timeout` is not set then the default value should be `30s` based on the [following docs from the provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_timeout)

However when looking deeper into the provider, it's very unclear exactly what the default value is. It's clear however that it is not `30s`. This is seen in the following links where the Default value can be seen as being `120s` [here](https://github.com/hashicorp/terraform-provider-google/blob/09cb850ee64bcd78e4457df70905530c1ed75f19/google/transport/config.go#L1228-L1233)

However it is also set [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/1a357ac38caa5b1914353b62779d3c3325749383/mmv1/third_party/terraform/transport/transport.go#L17) as a default value of 5 minutes.

My question here is what is the correct default value that is being used by the `request_timeout` field in the provider block when the attribute is not set. I'm having trouble seeing exactly what the value is.

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by zli82016** [comment]
The correct default value that is being used by the request_timeout field in the provider block when the attribute is not set is 120s. It was changed from 30s to 120s, and the documentation is not updated.
