### ISSUE TITLE
Remove dataQualityResult and dataProfileResult from google_dataplex_datascan resource

### ISSUE THREAD

**Issue by saurabh-net** [hashicorp/terraform-provider-google#15448]
`dataQualityResult` and `dataProfileResult` were output-only fields which listed results for the latest job created under a Datascan. This is unlikely to be relevant in a Terraform context.

They will be removed for maintainability of the API spec for Datascans.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8583

This will release with v5.0.0. Check https://github.com/hashicorp/terraform-provider-google/issues/15582 for more details on the major release.
