### ISSUE TITLE
Add support for google_data_fusion_pipeline

### ISSUE THREAD

**Issue by shekhar250723** [hashicorp/terraform-provider-google#15440]
Terraform\GCP> terraform plan
╷
│ Error: Invalid resource type
│
│ on main.tf line 21, in resource "google_data_fusion_pipeline" "df_pipeline":
│ 21: resource "google_data_fusion_pipeline" "df_pipeline" {
│
│ The provider hashicorp/google does not support resource type "google_data_fusion_pipeline".

Required terraform provider for it (google_data_fusion_pipeline) to run the data fusion pipeline through automation.

### New or Affected Resource(s)

* google_data_fusion_pipeline

**Comment by melinath** [comment]
It looks like the pipelines can't currently be managed via the API - https://cloud.google.com/data-fusion/docs/reference/rest/v1beta1/projects.locations.instances - which means that they can't be managed by Terraform. Support would need to be added in the API first. If pipelines are similar to a database, it's also possible that it might not make sense to implement this in Terraform - I'm not sure.

**Comment by shekhar250723** [comment]
@melinath Thanks for the update.
