### ISSUE TITLE
google_bigquery_data_transfer_config not validating custom project setting

### ISSUE THREAD

**Issue by ahoneiser** [hashicorp/terraform-provider-google#15455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.77.0
+ provider registry.terraform.io/hashicorp/google-beta v4.77.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.22.0
+ provider terraform.local/local/google v4.78.0
```

### Affected Resource(s)

* google_bigquery_data_transfer_config

### Terraform Configuration Files

```tf
resource "google_bigquery_data_transfer_config" "data_transfer" {
  for_each = { for _, data_transfer in local.data_transfers : data_transfer.name => data_transfer }

  project                = var.project_id
  display_name           = each.key
  location               = "us"
  data_source_id         = "scheduled_query"
  destination_dataset_id = each.value.dataset_id
  schedule               = "every day 01:00"

  params = {
    destination_table_name_template = each.value.name
    write_disposition               = "WRITE_TRUNCATE"
    query                           = each.value.query
  }
}
```

### Expected Behavior

I expect the resources created above to be read / created / updated / deleted in the project given through the `var.project_id`.

### Actual Behavior

The project running the snippet above is configured to use a gcs storage backend, this backend is located in a different gcp project (say `something-something-terraform-admin`)  than the actual bigquery resources (say `some-tenant-project`). Create & Import actions are currently failing because the resource seems to be ignoring the given `project` id, it is instead always falling back to the project that holds the state.

The snippet above is part of a module below the actual project structure, hence the `project_id` variable definition.

### Steps to Reproduce

1. add a `project` key with a `project_id` different to the provider configured project to a `google_bigquery_data_transfer_config` resource
2. `terraform apply`

### References

I've identified these code snippets to be the problem:

* [Create Function](https://github.com/hashicorp/terraform-provider-google/blob/aabd7b3a6e2f203b9767f27b8a5968c6890c7d11/google/services/bigquerydatatransfer/resource_bigquery_data_transfer_config.go#L354-L365)
* [Read Function](https://github.com/hashicorp/terraform-provider-google/blob/aabd7b3a6e2f203b9767f27b8a5968c6890c7d11/google/services/bigquerydatatransfer/resource_bigquery_data_transfer_config.go#L426-L437)
* [Update Function Begin](https://github.com/hashicorp/terraform-provider-google/blob/aabd7b3a6e2f203b9767f27b8a5968c6890c7d11/google/services/bigquerydatatransfer/resource_bigquery_data_transfer_config.go#L511-L517) & [Update Function End](https://github.com/hashicorp/terraform-provider-google/blob/aabd7b3a6e2f203b9767f27b8a5968c6890c7d11/google/services/bigquerydatatransfer/resource_bigquery_data_transfer_config.go#L588-L590)
* [Delete Function](https://github.com/hashicorp/terraform-provider-google/blob/aabd7b3a6e2f203b9767f27b8a5968c6890c7d11/google/services/bigquerydatatransfer/resource_bigquery_data_transfer_config.go#L619-L638)

It seems like all of these functions are always defaulting to setting `billingProject` to the result of the `GetBillingProject` method when `GetProject` doesn't return an error, which fits the problem.

I've created a local build of the provider with this [fix](https://github.com/hashicorp/terraform-provider-google/compare/main...ahoneiser:terraform-provider-google:fix-bigquery-project-key) included, which seems to make things work as expected.

**Comment by edwardmedia** [comment]
b/295306364

**Comment by ahoneiser** [comment]
prepared a fix proposal for this (here)[https://github.com/GoogleCloudPlatform/magic-modules/compare/main...ahoneiser:fix-bigquery_data_transfer_config], providers build from this branch produce binaries that do what I want regarding `google_bigquery_data_transfer_config` resources.

**Comment by ahoneiser** [comment]
Closing this since the problem was caused by project configuration .. I'm using the `impersonate_service_account` key in the provider configuration, without this, the code does what it's supposed to do (add the `google_bigquery_data_transfer_config` to the right tenant project) .. so, went back to checking the provider docs, apparently, I need to use the `use_project_override = true` flag to make the service account impersonation work with custom projects ..

Problem solved :slightly_smiling_face:
