### ISSUE TITLE
google_container_cluster with enable_autopilot cause recreate

### ISSUE THREAD

**Issue by truongnguyentym** [hashicorp/terraform-provider-google#15454]
### Problem

If I enabled autopilot in cluster and then it will always got deleted and recreate again in next apply

### Terraform Version
1.5.4 

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf

resource "google_container_cluster" "debug" {
  name             = "debug"
  location         = "australia-southeast1"
  enable_autopilot = true # -> this will cause the deleting and recreate cluster
  
}

```

### Debug Output

When I check the plan, below are some diff

<img width="502" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/135801987/eed35540-b37b-4e61-8832-a128748c62d2">

<img width="584" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/135801987/59f8b38a-68ef-47e8-ab18-dbbb598295fa">

I do the same setup but apply using local state and found more issue here

```
 - dns_config { # forces replacement
          - cluster_dns        = "CLOUD_DNS" -> null
          - cluster_dns_domain = "cluster.local" -> null
          - cluster_dns_scope  = "CLUSTER_SCOPE" -> null
        }

```
I think this is main reason why cluster being force replace.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
b/295307332

**Comment by truongnguyentym** [comment]
I added below in the resource it fix the issue 
```
dns_config {
    cluster_dns        = "CLOUD_DNS"
    cluster_dns_domain = "cluster.local"
    cluster_dns_scope  = "CLUSTER_SCOPE"
  }
```

**Comment by vizeit** [comment]
@truongnguyentym 
You can also resolve this by adding lifecycle ignore changes on dns_config
