### ISSUE TITLE
Update release shepherd and on call docs to reflect the new TeamCity projects

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15461]
# Background

As we move to new TeamCity projects the processes around cutting releases will change. I need to update them.

# What kind of contribution is this issue about?

* Release shepherding
* On call?

**Comment by SarahFrench** [comment]
Progress on "Release Process" page in the Wiki

| Revision | Link |
|-|-|
| Updated the details & links about getting the commit SHA from TC at the start of the 'On Wednesday' section | [8a8a709](https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process/8a8a70928ae607fe8a06537a957bcf88c18f4f52)|

**Comment by SarahFrench** [comment]
Progress on "Release Shepherd Rotation" page in the Wiki

**Comment by SarahFrench** [comment]
@melinath are there other docs, etc, that may need updating?

**Comment by melinath** [comment]
you could update the example link in https://raw.githubusercontent.com/hashicorp/terraform-provider-google/main/.github/ISSUE_TEMPLATE/10_test_failure.md

**Comment by SarahFrench** [comment]
Thanks! That's done now. I'll close this issue now
