### ISSUE TITLE
Update 5.0.0 release guide about the change of enableEndpointIndependentMapping's default value

### ISSUE THREAD

**Issue by shijeesh-ns** [hashicorp/terraform-provider-google#15477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is to track updating 5.0.0 release guide about the change of enableEndpointIndependentMapping's default value.  Instead of assigning default value of true to enableEndpointIndependentMapping, use the API's default value 

### New or Affected Resource(s)

* google_compute_router_nat

### References

https://github.com/hashicorp/terraform-provider-google/issues/10547
https://github.com/GoogleCloudPlatform/magic-modules/pull/8600

**Comment by roaks3** [comment]
This appears resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8634
