### ISSUE TITLE
SSL Policy on Region HTTPs Proxy currently in Beta

### ISSUE THREAD

**Issue by hugopicq-ws** [hashicorp/terraform-provider-google#15486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Google provider in version 4.76.0 released the google_compute_region_ssl_policy resource which is not in beta anymore. It is intended to be used on a google_compute_region_target_https_proxy resource by specifying the ssl_policy attribute. Although the google_compute_region_ssl_policy is not in beta anymore, the ssl_policy attribute on google_compute_region_target_https_proxy resource is still in beta. It would be great to check that this attribute has not been forgotten in beta in 4.76.0 when the google_compute_region_ssl_policy was released and make it available to production so that we can take advantage of this great feature!

### New or Affected Resource(s)

* google_compute_region_target_https_proxy
* google_compute_region_ssl_policy

### Potential Terraform Configuration

N/A

### References

N/A

**Comment by melinath** [comment]
promote to GA docs: https://googlecloudplatform.github.io/magic-modules/develop/promote-to-ga/

**Comment by hugopicq-ws** [comment]
Hi, can you explain your answer? I don't want to promote it myself if the main reason why it is still in beta is because it is not suited to production. Will it be integrated in the next official release of the provider?

**Comment by DanielRieske** [comment]
Looking at the [documentation](https://cloud.google.com/compute/docs/reference/rest/v1/regionTargetHttpsProxies) it seems that the sslPolicy field is GA available.

I'll pick this issue up and promote it.
