### ISSUE TITLE
data resource doesn't work if count argument is used

### ISSUE THREAD

**Issue by abdul-jabbar01** [hashicorp/terraform-provider-google#15487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.3.3

### Affected Resource(s)

* google_compute_network
* google_container_cluster

### Terraform Configuration Files

```tf
# It works. As it fetches the correct network
data "google_compute_network" "shared_network" {
  name    = "network-name"
  project = "project-name"
}

# It doesn't work. As it returns []
data "google_compute_network" "shared_network" {
  count   = 1
  name    = "network-name"
  project = "project-name"
}
```

Same issue happens with `google_container_cluster` when using data resource.
 

### Expected Behavior
It should fetch network that is already created

### Actual Behavior
It returns `[]` network

### Steps to Reproduce
- Have a network created already in different project
- Use above code and run `terraform console`
- Then run `data.google_compute_network.shared_network`

**Comment by edwardmedia** [comment]
@abdul-jabbar01 do you see similar other data sources work as you expected?

```tf
# It doesn't work. As it returns []
data "google_compute_network" "shared_network" {
  count   = 1
  name    = "network-name"
  project = "project-name"
}
```

**Comment by abdul-jabbar01** [comment]
Yes, others are working as expected. I see issue with `google_compute_network` and `google_container_cluster`

**Comment by edwardmedia** [comment]
@abdul-jabbar01 can you give an example of data source that works as you expected?

**Comment by edwardmedia** [comment]
@abdul-jabbar01 I thought that feature might be built in the terraform core but I could be wrong.  Do you have a specific data  source that supports that?
