### ISSUE TITLE
Updating the password in mysql_profile in google_datastream_connection_profile forces replacement.

### ISSUE THREAD

**Issue by damjad** [hashicorp/terraform-provider-google#15489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the MySQL connection profile, whenever we try to update the password, it recreates the connection profile. 
Because of this, the streams attached to the connection profile fail permanently and one has to recreate the stream manually. 

It does not happen with a PostgreSQL connection profile. 

The proposal is to remove `ForceNew: true` from [resource_datastream_connection_profile.go#L163](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/datastream/resource_datastream_connection_profile.go#L163).

I have verified with `gcloud` SDK that updating the password does not impact the streams using the connection profile. 

I have used the following command:
```bash
gcloud datastream connection-profiles update projects/XXXX-XXX-XXX/locations/europe-west1/connectionProfiles/yyyy --location=eu-west1 --type=mysql --mysql-password=xxxx--mysql-username=xx

```

### New or Affected Resource(s)

* google_datastream_connection_profile

### References

* #0000

**Comment by damjad** [comment]
The fix would be to remove this line [ConnectionProfile.yaml#L181](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/datastream/ConnectionProfile.yaml#L181). right?

If so, can I take it up?

**Comment by melinath** [comment]
@damjad you are welcome to take a swing at it. Note that you'll need to update the [update tests](https://googlecloudplatform.github.io/magic-modules/develop/test/#add-an-update-test) to make sure this works properly.

**Comment by damjad** [comment]
@melinath I have edited the file as mentioned above in https://github.com/GoogleCloudPlatform/magic-modules/pull/8675. 

I have also run the tests using the commands provided [here](https://googlecloudplatform.github.io/magic-modules/develop/run-tests/). All of them are passing. 

However, I am not sure how to write a new test to validate the mutability of the field.

**Comment by melinath** [comment]
I'll leave a comment on the PR.

**Comment by damjad** [comment]
The MRs are merged. Do you know when it will be available in the public release?

**Comment by melinath** [comment]
Closing since the PR is merged - looks like this will probably go out in next weeks release (assuming there are no issues)
