### ISSUE TITLE
Failing sweeper(s): ContainerAzure*, ContainerAws*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15494]
### Failure rates

- 100% since ?

### Impacted tests

- ContainerAzureCluster sweeper
- ContainerAzureClient sweeper
- ContainerAwsCluster sweeper

### Affected Resource(s)

Azure
* google_container_azure_cluster
* google_container_azure_client

Aws
* google_container_aws_cluster

### Nightly build test history

- [see the end of the build output for any sweeper build](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_NightlyTests_PRE_SWEEPER)

### Message(s)

```
2023/08/14 19:27:13 Sweeper Tests for region (us-central1) ran unsuccessfully:

ContainerAzureCluster: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
    <p>The requested URL <code>/v1/projects/ci-test-project-nightly-ga/locations/us-central1/azureClusters</code> was not found on this server.  <ins>That’s all we know.</ins>
  
ContainerAzureClient: googleapi: got HTTP response code 404 with body:
    <p>The requested URL <code>/v1/projects/ci-test-project-nightly-ga/locations/us-central1/azureClients</code> was not found on this server.  <ins>That’s all we know.</ins>

ContainerAwsCluster: googleapi: got HTTP response code 404 with body:
    <p>The requested URL <code>/v1/projects/ci-test-project-nightly-ga/locations/us-central1/awsClusters</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by SarahFrench** [comment]
I think that we should just remove the generated sweeper for the Azure client resource; there's nothing to sweep. In fact, I think that resource should instead be a data source?

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/8794 fixed this in theory
