### ISSUE TITLE
Incorrect example for google_project in documentations

### ISSUE THREAD

**Issue by OlafMeuwese** [hashicorp/terraform-provider-google#15515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_project

### Incorrect Documentation example
It uses the `name` attribute of the folder instead of the `folder_id`

```
resource "google_project" "my_project-in-a-folder" {
  name       = "My Project"
  project_id = "your-project-id"
  folder_id  = google_folder.department1.name
}
```

### Correct example:
```
resource "google_project" "my_project-in-a-folder" {
  name       = "My Project"
  project_id = "your-project-id"
  folder_id  = google_folder.department1.folder_id
}
```
### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project

**Comment by edwardmedia** [comment]
@OlafMeuwese looks like the folder's name shares the same format as the folder_id based on the [folder doc ](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder#name).  Here is the [link](https://github.com/hashicorp/terraform-provider-google/blob/268162cac62dadc3287ea1a7fbf1c3add6641ef1/google/services/resourcemanager/resource_google_folder.go#L55) to its code.

Doesn't it work for you?

```
The resource name of the Folder. Its format is folders/{folder_id}.
```

**Comment by edwardmedia** [comment]
@OlafMeuwese close this assuming it is no longer an issue. Feel free to reopen if you see it differently

**Comment by OlafMeuwese** [comment]
@edwardmedia 
Before I comment, allow me to apologize for not replying sooner. I should have reacted quicker. Please know I truly appreciate your work and time. 

Just to make sure we are correct about what is going on here. I re-analyzed what you provided and still come to the conclusion that the example is not correct (based on the rest of the documentation and code). 

Okay so we have the `google_folder` which has the 2 attributes `name` and `folder_id`

As described in the link to the code:
```
"folder_id": {
  Type:        schema.TypeString,
  Computed:    true,
  Description: `The folder id from the name "folders/{folder_id}"`,
},
// Format is 'folders/{folder_id}.
// The terraform id holds the same value.
"name": {
  Type:        schema.TypeString,
  Computed:    true,
  Description: `The resource name of the Folder. Its format is folders/{folder_id}.`,
}
```

So from this I take that is we would have the `name` as `folders/185412351`, the `folder_id` would be `185412351`.
The `folder_id` variable is derived (subset) from the `name` as you will

Now if we look at the `google_project`, it states for the `folder_id`:
[folder_id](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project#folder_id) - (Optional) The numeric ID of the folder this project should be created under.

So this would state that is _only_ expects the numeric ID (`185412351`) not the whole path (`folders/185412351`)


This is truly different from the `google_folder` structure. 
Here the `parent` is indeed the full path of either folder () or organization ()
As described in the section:
[parent](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder#parent) - (Required) The resource name of the parent Folder or Organization. Must be of the form folders/{folder_id} or organizations/{org_id}.

Here the example uses the name of the (parent) folder in the child `google_folder` for the `parent` field. 

So as far as I understand it now, `google_project` and `google_folder` differ in how they reference their respective parents.
