### ISSUE TITLE
Failing test(s): TestAccRedisInstance_redisInstancePrivateServiceExample

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15532]
### Failure rates

- 100% since 2023-07-29

### Impacted tests

- TestAccRedisInstance_redisInstancePrivateServiceExample [new test history](https://hashicorp.teamcity.com/test/-8849368026242669580?currentProjectId=TerraformProviders_Google_NightlyTests), [old test history](https://ci-oss.hashicorp.engineering/test/-8849368026242669580?currentProjectId=GoogleCloud&expandTestHistoryChartSection=true)

### Affected Resource(s)

* google_redis_instance

### Nightly build test history

- see above

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccRedisInstance_redisInstancePrivateServiceExample
=== PAUSE TestAccRedisInstance_redisInstancePrivateServiceExample
=== CONT  TestAccRedisInstance_redisInstancePrivateServiceExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 13, message: an internal error has occurred
          with google_redis_instance.cache,
          on terraform_plugin_test.tf line 28, in resource "google_redis_instance" "cache":
          28: resource "google_redis_instance" "cache" {
--- FAIL: TestAccRedisInstance_redisInstancePrivateServiceExample (172.51s)
FAIL
```

b/299312447

**Comment by SarahFrench** [comment]
Not sure if related, but the timing of this issue starting matches : https://github.com/hashicorp/terraform-provider-google/issues/15531

**Comment by himanikh** [comment]
@SarahFrench Could you confirm if you see recovery in these tests starting yesterday? 

There was a internal platform issue for past few weeks which caused such failures but I was able to find a workaround and release it last week.

**Comment by SarahFrench** [comment]
This test has now passed 100% of the time since August 19th, so closing this issue 🚀
