### ISSUE TITLE
Cloud Functions: delete the created function when failed to create new function

### ISSUE THREAD

**Issue by hkak03key** [hashicorp/terraform-provider-google#15540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

For `google_cloudfunctions2_function`, when Terraform fails to create a new function, it leaves the created function but does not record it in tfstate.

As a result, we must manually delete the created function or execute `terraform import` and terraform apply again after that.
This process is very cumbersome.

So, one of the following implementations should be added:

- Before creating a new function, check if the function already exists. And if it does not exist and the deploy fails, Terraform deletes the function.
  - (I think this is better)
- Before creating a new function, check if the function already exists. And if it does not exist and the deploy fails, Terraform records it in tfstate and reports an error.

### New or Affected Resource(s)

* google_cloudfunctions2_function

### Potential Terraform Configuration

```tf
# any terraform code 
```

**Comment by edwardmedia** [comment]
b/296375923

**Comment by rileykarson** [comment]
Note: We probably want to taint the resource rather than delete it (that will cause it to get deleted on next apply)

**Comment by StephenWithPH** [comment]
With https://github.com/hashicorp/terraform-provider-google/issues/15143 / https://github.com/GoogleCloudPlatform/magic-modules/pull/8545, the failed function is now added to state (and tainted). Thus, future TF runs can handle this gracefully.

I think that solution is preferable to automatically deleting a function which failed to create; having the failed function around makes debugging the failure a little easier.

**Comment by rileykarson** [comment]
Yeah, this seems to have been resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8545. That would have released only a little after this was filed! (and I am consistent with my suggestions in https://github.com/hashicorp/terraform-provider-google/issues/13535#issuecomment-1402325387 and https://github.com/hashicorp/terraform-provider-google/issues/15540#issuecomment-1707015119 although I evidently had no memory between them, ha)
