### ISSUE TITLE
support for regional internal application load balancers with external backends 

### ISSUE THREAD

**Issue by bmenasha** [hashicorp/terraform-provider-google#15556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Be able to provision this resource configuration: 

https://cloud.google.com/load-balancing/docs/l7-internal/setup-regional-int-https-external-backend#gcloud

### New or Affected Resource(s)

At least: google_compute_region_network_endpoint_group  to support network_endpoint_type = "INTERNET_FQDN_PORT"

resource "google_compute_region_network_endpoint_group" "neg-1" {
  name                  = "my-service"
  network               = "https://www.googleapis.com/compute/v1/projects/bmenasha-compute-service-1/global/networks/gke-lb-us-east1-network"
  network_endpoint_type = "INTERNET_FQDN_PORT"
  region = "us-east1"
}

it currently returns the error: 

Error: expected network_endpoint_type to be one of [SERVERLESS PRIVATE_SERVICE_CONNECT ], got INTERNET_FQDN_PORT
│ 
│   with google_compute_region_network_endpoint_group.neg-1,
│   on main.tf line 447, in resource "google_compute_region_network_endpoint_group" "neg-1":
│  447:   network_endpoint_type = "INTERNET_FQDN_PORT"
│ 

* google_compute_region_network_endpoint_group

### References

https://cloud.google.com/load-balancing/docs/l7-internal/setup-regional-int-https-external-backend#gcloud

Thanks!

b/312433298

**Comment by Cheriit** [comment]
We've added support for regional NEGs of a type `INTERNET_IP_PORT` and `INTERNET_FQDN_PORT`. @bmenasha can you confirm if that solves your issue?

**Comment by slevenick** [comment]
Closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/9863
