### ISSUE TITLE
google_firestore_document.document: GoogleApi Error 400: Missing routing header

### ISSUE THREAD

**Issue by ch3ck** [hashicorp/terraform-provider-google#15550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
Terraform v1.5.0
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.5.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `google_firestore_document`

### Terraform Configuration Files

```tf
resource "google_firestore_document" "documents" {
  for_each = { for doc in var.collections : doc.document => doc }

  provider    = google-beta
  project     = local.project_id
  database    = var.database_name
  collection  = each.value.collection
  document_id = each.value.document
  fields      = jsonencode(each.value.fields)

  depends_on = [
    google_firestore_database.firestore
  ]
}
```

### Panic Output

See error below

### Expected Behavior

No error

### Actual Behavior

```bash
google_firestore_document.documents["fake-test-user"]: Creating...
╷
│ Error: Error creating Document: googleapi: Error 400: Missing routing header. Please fill in the request header with format x-goog-request-params:project_id=XXXXXXX. Please refer to https://firebase.google.com/docs/firestore/manage-databases#access_a_named_database_with_a_client_library for more details.
...
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Terraform provider:
```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "4.78.0"
    }
  }
}

provider "google" {
  # Configuration options
}
```

### References

- https://firebase.google.com/docs/firestore/manage-databases#access_a_named_database_with_a_client_library
- b/296467504

**Comment by edwardmedia** [comment]
b/296467504

**Comment by narendraaduri1** [comment]
please look at this issue Error: Error creating Document: googleapi: Error 400: Missing routing header. Please fill in the request header with format x-goog-request-params:project_id=xxxxxxxx&database_id=firestoredatabase02. Please refer to https://firebase.google.com/docs/firestore/manage-databases#access_a_named_database_with_a_client_library for more details.

**Comment by nguyen-vo** [comment]
hi, will this issue be fixed soon and are there any workaround in the mean time

**Comment by melinath** [comment]
This should now be resolved.

**Comment by ch3ck** [comment]
@melinath which provider version has this fix?

**Comment by melinath** [comment]
The API no longer requires the routing header, so it should work in all provider versions that support this resource. Definitely let us know if that doesn't seem to be the case!
