### ISSUE TITLE
Backend GCS bucket "doesn't exist" if quota project is deleted

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#15570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.5 on windows

### Affected Resource(s)

N/A 

### Terraform Configuration Files

Sample backend.tf file:
```
terraform {
  backend "gcs" {
    bucket = "my-gcs-bucket-name"
    prefix = "my-module-name"
  }
}
```

### Debug Output

```
Error: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist
``` 

### Expected Behavior

Continue to operate normally as the GCS bucket itself is fine, or, give a warning or error message that the quota project is not valid

### Actual Behavior

Terraform reports the GCS bucket does not exist, which may cause a sudden case of brown pants.  

### Steps to Reproduce

1. Configure Terraform to use a GCS bucket for state file storage
2. Run `gcloud auth login` and `gcloud config set project XXXX`
3. Run `gcloud auth application-default` to set `GOOGLE_APPLICATION_CREDENTIALS` for Terraform to use
4. Delete project XXXXX
5. Run a terraform init/plan/apply

### Important Factoids

Typical work-arounds like `terraform init -reconfigure` do not help.  Nor does re-authenticating.  

gcloud does complain when setting the default project to a non-existent one, but does not throw any warnings for a project that's recently deleted.  

I didn't try, but `gcloud auth application-default set-quota-project <any valid project>` probably fixes it too.  

### References

* [[Terraform claims backend GCS bucket doesn't exist](https://stackoverflow.com/questions/76933080/terraform-claims-backend-gcs-bucket-doesnt-exist)](https://stackoverflow.com/questions/76933080/terraform-claims-backend-gcs-bucket-doesnt-exist/76933081#76933081)

**Comment by edwardmedia** [comment]
@jeheyer after step 4 (Delete project XXXXX), are you able to see the bucket using gsutil?

**Comment by jeheyer** [comment]
I don't understand what you mean by "see the bucket".  Obviously, the bucket still exists, and would show up if gcloud is set for the correct project.

**Comment by edwardmedia** [comment]
@jeheyer it is not clear to me what went wrong. My suspect is deleting a project might cause the problem. To debug, I would first verify if the account (the terraform runner) is still able to access the bucket. To do that, you can use the same account to run gsutil to see if the objects in that bucket are still visible. Does this make sense?

**Comment by jeheyer** [comment]
So you're just looking for this?

```
terraform workspace list
querying Cloud Storage failed: storage: bucket doesn't exist

gcloud auth login
gsutil ls
NotFoundException: 404 The requested project was not found.

gcloud config set project my-project
gsutil ls
gs://bucket1/
gs://bucket2/

terraform workspace list
querying Cloud Storage failed: storage: bucket doesn't exist

gcloud auth application-default set-quota-project my-project
terraform workspace list
  default
  workspace1
  workspace2

```

**Comment by jeheyer** [comment]
Key point here is gsutil operates the the project level.  As do most Terraform resources.

The backend GCS bucket configuration is different.  It's using a global namespace, and if ADCs is used for authentication with an invalid quota project, the `bucket doesn't exist` message will appear.  

The root cause makes sense.  It's just the error message is very misleading because it a problem with the project, not the bucket.

**Comment by edwardmedia** [comment]
@jeheyer not sure what you meant below. [Remote state is a feature of Terraform backends](https://cloud.google.com/docs/terraform/resource-management/store-state). I agree the error message seems not clear. You may file a ticket against Terraform core?  

```
The backend GCS bucket configuration is different. It's using a global namespace
```

Based on what we see, I think the provider works as expected. Closing this issue now. Feel free to reopen if you disagree.

**Comment by jeheyer** [comment]
> You may file a ticket against Terraform core?

Link?

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform/issues
