### ISSUE TITLE
`certificate_id` in `google_compute_managed_ssl_certificate` should not be optional

### ISSUE THREAD

**Issue by maqiuyujoyce** [hashicorp/terraform-provider-google#15585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[`certificate_id` in `google_managed_ssl_certificate` is optional](https://github.com/hashicorp/terraform-provider-google-beta/blob/a568038c25be2f92973f362fb092c6b4454b0fe0/google-beta/services/compute/resource_compute_managed_ssl_certificate.go#L106), which indicates it's writable. But in reality it is an output-only field ([maps to the flattened `id` field ](https://github.com/hashicorp/terraform-provider-google-beta/blob/a568038c25be2f92973f362fb092c6b4454b0fe0/google-beta/services/compute/resource_compute_managed_ssl_certificate.go#L275) in the [REST API](https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates)).

This incorrect schema causes an issue in the Config Connector CRD: this output-only field is [under `spec` field](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/b746248cd5a9b30669380513de8fdc6b4c43018d/crds/compute_v1alpha1_computemanagedsslcertificate.yaml#L74) and is considered writable.

### New or Affected Resource(s)

* google_compute_managed_ssl_certificate

### Potential Terraform Configuration

N/A

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates
* https://github.com/hashicorp/terraform-provider-google-beta/blob/a568038c25be2f92973f362fb092c6b4454b0fe0/google-beta/services/compute/resource_compute_managed_ssl_certificate.go

b/312432901

**Comment by melinath** [comment]
This is a bit of a weird one - certificate_id is Optional + Computed, which means that a user could set a value and then remove it, and the set value would persist - so there are cases where a valid configuration could leave this unset. I think that does make this a breaking change.

**Comment by Hamzawy63** [comment]
@melinath 
Hi, I see that the field definition is already marked as output only field which means it shouldn't be modifiable by the user. Do I misunderstand something? https://github.com/GoogleCloudPlatform/magic-modules/blob/2f5695736b13dd47c7b22949eac216f714a99b62/mmv1/products/compute/ManagedSslCertificate.yaml#L109

**Comment by melinath** [comment]
The field (incorrectly) has `output: true` and also `default_from_api: true` - [default_from_api takes precedence](https://github.com/GoogleCloudPlatform/magic-modules/blob/2b6e2fac92b47dca3c9f5b6e86cfac64923d9a36/mmv1/templates/terraform/schema_property.erb#L26). I've opened https://github.com/hashicorp/terraform-provider-google/issues/18832 to track preventing this kind of issue in the future.

**Comment by Hamzawy63** [comment]
Thanks for your response!

That's how I understand the problem: 

- The field should be output only. 
- `default_from_api` causes the field to be modifiable by the user and hence config connector defined the field in the `spec` section (which shouldn't be the case for output only field
- The intended solution in that case is to remove `default_from_api` property, right?  

Please let me know If I misunderstand the issue. 

According to [default_from_api takes precedence](https://github.com/GoogleCloudPlatform/magic-modules/blob/2b6e2fac92b47dca3c9f5b6e86cfac64923d9a36/mmv1/templates/terraform/schema_property.erb#L26), This also affects TF behavior, right? i.e customers will be able to modify this field despite being labelled as`output-only` ? or did it only affect KCC behavior? 

Also, is this the equivalent field in the API ? https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates
<img width="789" alt="image" src="https://github.com/user-attachments/assets/fb4dce25-e47c-4556-8672-d168ed055fdd">

**Comment by melinath** [comment]
This impacts Terraform behavior. If the KCC resource is based on the Terraform resource, it would likely impact KCC as well.

Removing `default_from_api` in a major release would fix the issue, yes.

Yes, this is equivalent to the `id` field in the API.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11409
