### ISSUE TITLE
No Docs on How to update dependency versions

### ISSUE THREAD

**Issue by nevzheng** [hashicorp/terraform-provider-google#15583]
# Background

I needed to bump the Version of the Google API but didn't find clear instructions on how to do so.

There should be clearer documentation on how to upgrade dependencies.

# What kind of contribution is this issue about?

General Contributions

# Related PR(s), if any:

# Details

**Comment by c2thorn** [comment]
This exists now in https://googlecloudplatform.github.io/magic-modules/best-practices/#update-gomod
