### ISSUE TITLE
[Announcement] Upcoming Changes in Version 5.0.0 of the Google Provider

### ISSUE THREAD

**Issue by vravind1** [hashicorp/terraform-provider-google#15582]
We are planning to release version 5.0.0 of the Google providers in late September 2023. Major releases allow the provider to make breaking changes in a scheduled and publicized manner, to help avoid unnecessary churn for our users.

Since the last major provider release in November 2021, we have been listening closely to the community's feedback. The upcoming major release primarily focuses on various enhancements and bug fixes that include breaking changes.

The upcoming major release will also remove attributes that have been marked as deprecated. Typically these have been marked as such due to changes in the upstream API, or in some cases, the use of the attribute causes confusion.  Support for earlier versions of Terraform will not change as a result of the major version release v5.0.0.

### Notable Changes

**Labels Rework** \
This change will be applied to all “labels” and “annotations” fields, and may be applied to conceptually similar fields subject to mixed-management like GKE taints.

The current model for labels in Terraform assumes that Terraform is the exclusive owner of a resource, and is authoritative over the whole set of labels. While a reasonable assumption for early GCE, this has not proven to be a viable model for modern services.

We plan to rework the labels model to be non-authoritative, splitting labels into a user-managed field and an output-only field listing the complete set of labels on a resource. Following the change, Terraform will manage individual label keys defined in the user-managed field rather than the labels of a resource as a whole.

**Plan-time provider default values** \
Several common fields can be managed through provider configuration, providing a default value when they’re not defined in configuration: project, region, and zone. As implemented today, these values are unknown values (“known after apply”) when used from the provider block during the terraform plan. Additionally, they’re sticky- default changes do not apply to existing resources, creating configurations and states that are inconsistent.

After google_project_iam: project field is now required in 4.0.0, several users reported that this sticky default had meant their configurations contained IAM policies applied to the wrong project(s). With additional IAM resources past project & additional policy resources past IAM (firewalls, network firewall policies, etc) in GCP, this is an issue we should correct across the entire provider.

Newer features of Terraform Provider SDK will allow us to move this information forward from apply time, where it’s unknown at plan time, to plan time. This will remove the misleading sticky behavior of the values, and provide users additional information at plan time.

### Follow our Progress

The full contents of the major release and progress towards it can be viewed in the [v5.0.0 milestone](https://github.com/hashicorp/terraform-provider-google/milestone/89).

### Upgrading

As a major version contains breaking changes, it is considered best practice to pin a provider version to avoid bringing in potentially breaking changes automatically. To remain on previous versions of the provider until such time that you are able to accommodate those changes, either pin to any previous version:

```
terraform {
    required_providers {
        google = {
            version = "~> 4.78.0"
        }
    }
}
```

Or a specific version:

```
terraform {
    required_providers {
        google = {
            version = "=4.78.0"
        }
    }
}
```

Full documentation on [how to manage versions of a provider can be found on the Terraform Website](https://developer.hashicorp.com/terraform/language/providers/requirements#version-constraints).

Your usage patterns will dictate how much effort upgrading to v5.0.0 will take. We document each breaking change in our [upgrade guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade) which will describe what changes are necessary to existing resources to preserve behavior.

**Comment by rileykarson** [comment]
Our target date has coalesced and we're set for Monday October 2nd, 2023, barring any unexpected complications!

**Comment by billinghamj** [comment]
@rileykarson https://github.com/hashicorp/terraform-provider-google/issues/15885 might be a blocker, especially given secrets often can't be replaced nondestructively

**Comment by rileykarson** [comment]
Thanks! Flagged to have someone take a look at.

**Comment by rileykarson** [comment]
`5.0.0` is out:

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade
* https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0
* https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v5.0.0

**Comment by rileykarson** [comment]
For any issues encountered with upgrades, new bugs introduced, etc. please file dedicated issues!
