### ISSUE TITLE
`google_compute_instance_from_template` does not set `instance-template` metadata

### ISSUE THREAD

**Issue by gtebbutt** [hashicorp/terraform-provider-google#15606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```console
Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.79.0
```

### Affected Resource(s)

* `google_compute_instance_from_template`

### Terraform Configuration Files

```tf
resource "google_compute_instance_from_template" "tpl" {
  name = "instance-from-template"
  zone = "us-central1-a"

  source_instance_template = "projects/example-project/global/instanceTemplates/example-template"
}
```

### Expected Behavior

The `instance-template` metadata field will be set, since this is a special value expected by GCP (e.g. for display in the web console) - this behaviour would match instances created by an instance group manager. 

It'd also be extremely useful to have `creation_timestamp` returned as an attribute, although that's not directly related. 

### Actual Behavior

Currently `instance-template` is not set at all. It also can't be manually set by adding `metadata` to the `google_compute_instance_from_template` resource without overwriting the entire existing metadata object attached to the template, and it can't be added to the metadata of the template itself if using `name_prefix` because the full template ID to use as the value is not known until creation time. 

### Steps to Reproduce

1. Create any `google_compute_instance_from_template` resource

### Important Factoids

In this specific case it probably makes sense to automatically add the field on instance creation, as the instance group manager would do, but more broadly it might be worth considering a `merge_metadata` flag or similar to allow additional metadata values to be set at creation time without wiping out the template metadata. 

b/312433102

**Comment by edwardmedia** [comment]
@gtebbutt using below config, I do see  **foo = "bar"** showing up in the instance. Is this what you referred to? Please share your config and the debug log so I can take a closer look

```tf
resource "google_compute_instance_template" "tpl" {
  name         = "issue15606-template"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
    auto_delete  = true
    disk_size_gb = 100
    boot         = true
  }

  network_interface {
    network = "default"
  }

  metadata = {
    foo = "bar"
  }

  can_ip_forward = true
}

resource "google_compute_instance_from_template" "tpl" {
  name = "issue15606-instance"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.tpl.self_link_unique

  // Override fields from instance template
  can_ip_forward = false
  labels = {
    my_key = "my_value"
  }
}
```

**Comment by gtebbutt** [comment]
Sorry, I probably wasn't clear enough in that first description: GCP specifically expects a metadata field of the form `"instance-template": "projects/<PROJECT>/global/instanceTemplates/<TEMPLATE_NAME>"` to be set when an instance is created from a template - if you use a managed instance group, for example, this will be automatically added to the existing metadata on instance creation. 

If you look at the instance info in the web console there's a dedicated field "Instance template" under the "Basic information" heading; this will be populated correctly if the instance was created by a managed instance group, but will show "None" if the instance was created from a template by Terraform. 

---

Hopefully this is clearer, I've added comments in the relevant places: 

```tf
resource "google_compute_instance_template" "tpl" {
  name_prefix  = "issue15606-template-"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
    auto_delete  = true
    disk_size_gb = 100
    boot         = true
  }

  network_interface {
    network = "default"
  }

  metadata = {
    foo = "bar"

    # Can't set "instance-template" key here because full template name is not yet known when using name_prefix
    # I'm also not certain if setting that key here would cause issues with managed instance groups that try to add it automatically on instance creation
  }

  # Startup script isn't a strict requirement here, just a good example of the kind of complex metadata that we don't want to overwrite at instance creation time
  metadata_startup_script = file("complex_startup_script.sh")

  can_ip_forward = true
}

resource "google_compute_instance_from_template" "tpl" {
  name = "issue15606-instance"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.tpl.self_link_unique

  // Override fields from instance template
  can_ip_forward = false
  labels = {
    my_key = "my_value"
  }

  # Can't set this without wiping out the existing template metadata, and arguably shouldn't need to set system fields manually in either case 
  #metadata = {
  #  instance-template = google_compute_instance_template.tpl.id # This is expected by the system
  #  color             = "green"                                 # This is just an example of another custom field that might be instance specific
  #}
}
```

---

### Suggestions

For this specific issue, I'd expect the same behaviour as if the instance were created by a managed instance group: 

- `google_compute_instance_from_template` should automatically add an `instance-template` field to any existing metadata at instance creation time, containing the appropriate template name
- `google_compute_instance` and `google_compute_instance_from_template` should export the `created_at` attribute for other resources to reference (this isn't direct cause/effect with the metadata question, but the fact it's not available has created some additional complexity for us when looking for workarounds)

And then separately to that, a broader discussion question that this has raised for us internally: 

- Beyond automated system fields like `instance-template`, it would be useful if we could manually set custom metadata fields at instance creation time without losing the metadata that was already set on the template. One option would be adding a `merge_metadata` boolean flag, allowing the instance metadata to optionally be merged with the template metadata rather than replacing it entirely.

**Comment by edwardmedia** [comment]
@gtebbutt how did you create the instance? Could you detail the steps to create it?

```
GCP specifically expects a metadata field of the form "instance-template": "projects/<PROJECT>/global/instanceTemplates/<TEMPLATE_NAME>" to be set when an instance is created from a template - if you use a managed instance group, for example, this will be automatically added to the existing metadata on instance creation.
```

**Comment by gtebbutt** [comment]
Sure thing - from what we've seen it applies to any instance created by GCP itself, e.g. via an instance group manager. We're specifically using `google_compute_region_instance_group_manager`. 

I've just tested by adding the following resource to your sample code from above: 

```tf
resource "google_compute_region_instance_group_manager" "manager" {
  name               = "issue15606-instance-manager"
  base_instance_name = "issue15606-managed"
  target_size        = 1

  version {
    instance_template  = google_compute_instance_template.tpl.id
  }
}
```

The instance `issue15606-managed-...` has the template metadata set, but the instance `issue15606-instance` doesn't.

**Comment by edwardmedia** [comment]
@gtebbutt I have looked at the apis and not sure if that is possible

**versions.instanceTemplate** is available in [instanceGroupManagers](tps://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers) but not available in [instanceTemplates](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates) and [instances](https://cloud.google.com/compute/docs/reference/rest/v1/instances)

Unless you build a solution by yourself, I don't see there is a way natively in the terraform resource. Does this make sense?

**Comment by gtebbutt** [comment]
Again, apologies if I'm being unclear, but it's not the `versions.instanceTemplate` field that's relevant here - you just asked for an example of how the instances were being created, that was the shortest working example to create an instance via a group manager. 

The missing field, which is set on the created instance (not on the group manager, or the template) by that instance group manager, is in `metadata.items` with the key `instance-template`. 

It can be set correctly with: 
```tf
resource "google_compute_instance_from_template" "tpl" {
  name = "issue15606-instance"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.tpl.self_link_unique

  metadata = {
    instance-template = google_compute_instance_template.tpl.id # This is expected by the system
  }
}
```

I marked it as a bug for two reasons: 
- The system expects that field to be set when a template is used. Among other things, the "Basic information" returned by the web console will be incorrect if it is not set. As such, I would expect the resource to set this field automatically in the same way that an instance group manager does
- It is not possible to cleanly work around the issue by setting it manually on the `google_compute_instance_from_template` resource, because that will *replace* the template metadata entirely, rather than *adding* the `instance-template` key to that existing metadata

Hopefully that makes sense? Please let me know if I can pass along any other info, since it seems like my explanation isn't quite coming across clearly.

**Comment by edwardmedia** [comment]
Oh I see what you meant. Even `source_instance_template` is set in below config, the `Instance template` field is actually not set which can be viewed vi the console. 

```tf
resource "google_compute_instance_from_template" "tpl" {
  name = "issue15606-instance"
  zone = "us-central1-a"

  source_instance_template = google_compute_instance_template.tpl.self_link_unique

  metadata = {
    instance-template = google_compute_instance_template.tpl.id # This is expected by the system
  }
}
```

**Comment by melinath** [comment]
Thanks for reporting this issue and being so patient explaining your use case! However, after looking into this, I don't think this is a bug. Users are able to use `google_compute_instance_from_template` to successfully call the API and create compute instances.

Although there may be additional functionality from cloud console or other systems that is unlocked by setting `metadata.instance-template` on the instance, that is not a requirement of the API. We are already sending `sourceInstanceTemplate` when [creating the instance](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert) with `google_compute_instance_from_template`; the API doesn't return an error due to the missing metadata, or set the metadata field on the server side. So, we don't consider this a bug.

It does seem like the experience here is not ideal but I'm not sure what the best path forward would be - merging nested fields could get messy. We could silently add in `metadata.instance-template` regardless of what else is set, but that could surprise users.

Leaving open as a potential future enhancement.

**Comment by melinath** [comment]
As a workaround would it be possible to set `metadata.instance-template` on the template itself?

**Comment by gtebbutt** [comment]
Thanks @melinath, I appreciate you taking the time to look into it! Understood on the bug vs enhancement question, I can see both sides there so that makes sense. Also fair to say that full field merging could be more complex, totally reasonable to pin that as a broader question.

In terms of silently adding `metadata.instance-template` I do agree that's potentially surprising behaviour - I was certainly surprised when I realised that's what the instance group managers were doing! That said, since it *is* the approach the GCP resources themselves take, I'd say there's at least precedent for that option. 

With our current config we're using `name_prefix` on the templates, so we're not able to set `metadata.instance-template` there because the full template name/ID isn't known until creation time. That said, we can probably figure out a way to generate a unique ID outside the `google_compute_instance_template` resource only when it's updated, and then pass it to the `name` and `metadata.instance-template` fields simultaneously instead of using `name_prefix`. 

There was also some concern that setting it on the template could interfere with the instance group managers attempting to set the same field when creating instances from the template (we use shared templates for both managed and unmanaged instances, to ensure consistency), so will need to investigate a little more there. 

Side note from when we looked into manual ID generation is that having `creation_timestamp` returned on `google_compute_instance`, `google_compute_instance_from_template`, and `google_compute_instance_template` would make it a lot easier to keep track of things. That definitely falls into the "enhancement" bucket, and is a little tangential from the rest, but also hopefully straightforward - worth opening as a separate issue?

**Comment by gtebbutt** [comment]
Notes for anyone reading this later, based on a few quick tests around setting `metadata.instance-template` manually on the template itself: 

- If the value is set correctly, setting the field on the template will work as expected with instances created from that template using `google_compute_instance_from_template`.
- If the field is present on the template, and an instance is created by a managed instance group, that field will be overwritten on the instance by the group manager (the other metadata fields are left unchanged). If it was set to the correct value on the template this shouldn't generally make a difference, but it does mean that the project or template name might be replaced with its numeric ID equivalent, for example. 
- It's possible to set an *incorrect* value for this field on the template, e.g. `instance-template = "foo"`. Managed instance groups can still be used as normal in that case (they'll just overwrite it with the correct value on instance creation). Using `google_compute_instance_from_template` will succeed, but the web console will then throw an error if you try to view that instance - haven't gone deeper on this one but it seems like it has quite a bit of potential to break things if you're not careful.

**Comment by melinath** [comment]
If `creation_timestamp` would be useful that would definitely be worth opening as a separate ticket, since it's straightforward and can proceed separately from whatever happens here :-)

**Comment by rileykarson** [comment]
Setting this value is a behaviour of the MIG acting on a managed resource, and we don't necessarily want Terraform to do the same. Creation through this flow is effectively a one-time event, while MIGS continuously manage the resource. This matches the baseline conclusion in https://github.com/hashicorp/terraform-provider-google/issues/15606#issuecomment-1694001296.
