### ISSUE TITLE
distribution_policy_target_shape forces recreation of instance group

### ISSUE THREAD

**Issue by ralbertazzi** [hashicorp/terraform-provider-google#15628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.2
on darwin_arm64
```

### Affected Resource(s)

* `google_compute_region_instance_group_manager`

### Expected Behavior

Changing the `distribution_policy_target_shape` of an existing regional instance group manager does not result in a destroy and re-create of the MIG but in just an in-place update

### Actual Behavior

Changing the `distribution_policy_target_shape` of an existing regional instance group manager results in a destroy and re-create of the MIG.

Current workaround is to change it in-place from the Google Cloud Console and later change the value on Terraform. The next `terraform apply` will result in no changes to be applied, as desired.

### Steps to Reproduce

- Create a regional instance group manager resource
- Change its `distribution_policy_target_shape`
- `terraform apply`

```
~ distribution_policy_target_shape = "EVEN" -> "BALANCED" # forces replacement
```

### Important Factoids

Related docs:
- https://cloud.google.com/compute/docs/instance-groups/regional-mig-distribution-shape
- https://cloud.google.com/compute/docs/instance-groups/regional-mig-set-target-distribution-shape#changing_the_target_distribution_shape_of_an_existing_group

I can see that distribution policy target shape can be changed from the Google Cloud Console and that's the workaround that I actually used to avoid re-creating the instance group manager.

I can see from the docs that changing this property is not always possible. For instance my MIGs had proactive instance distribution and I had to disable it in order to change from EVEN to BALANCED. Did the provider take this in consideration? Would it have updated the instance group manager in-place if I didn't have had proactive instance distribution enabled?

If so, I believe a better experience would be to either:
1. Disable proactive instance distribution as part of the change too, although that sounds sneaky
2. Just update the `distribution_policy_target_shape` and see what the API returns (if proactive instance distribution is enabled, it will return a human-understandable error hopefully)

Both options look better to me than destroying the MIG and creating another one. Such operations take much more time but moreover they can result in temporary outages if one just executes the apply without thinking too much. Personally I would much rather prefer hitting an API error (option 2) than destroying the MIG that is sustaining my application's traffic.

**Comment by edwardmedia** [comment]
The api  accpets below call

```
PATCH /compute/v1/projects/myproject/regions/us-central1/instanceGroupManagers/tf-test-rigm-r2vfxmuj22?alt=json&prettyPrint=false HTTP/1.1
Host: compute.googleapis.com
{
 "distributionPolicy": {
  "targetShape": "BALANCED",
  "zones": [
   {
    "zone": "zones/us-central1-b"
   },
   {
    "zone": "zones/us-central1-a"
   }
  ]
 },
 "fingerprint": "IcTWgkfoxA4="
}
```
