### ISSUE TITLE
Artifact Registry VPC SC config

### ISSUE THREAD

**Issue by watsonjm** [hashicorp/terraform-provider-google#15622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently we have a rather large environment set up with Terraform. We have a VPC Service Perimeter and Artifact Registry in use with a remote PyPI repository set up. I cannot use these resources without running `gcloud artifacts vpcsc-config allow --project=my-project --location=my-location` first. I tried doing it myself in the perimeter to no avail, and I don't see what is changing in audit logs when this command is run. This should be a terraform resource so anyone with a perimeter and a remote repository can enable this.

### Potential Terraform Configuration

```tf
resource "google_artifact_registry_vpc_sc_config" "this" {
  project       = "my-project"
  location      = "my-location"
  vpc_sc_policy = "ALLOW"
}
```

### References

none

b/298050823

**Comment by melinath** [comment]
Note re: this API: it looks like this isn't a "real" resource - it only has get and update endpoints that are nested under `location`, and no delete endpoint. https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations/getVpcscConfig

**Comment by melinath** [comment]
Similar resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_service_split_traffic
