### ISSUE TITLE
Instance Group Autoscaler on PubSub undelivered messages creates an invalid target

### ISSUE THREAD

**Issue by luisds95** [hashicorp/terraform-provider-google#15627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- Terraform v1.5.6
- hashicorp/google v4.79.0
- hashicorp/google-beta v4.79.0

### Affected Resource(s)

* google_compute_region_autoscaler

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "request" {
  project                    = var.project_id
  name                       = "request-topic"
  message_retention_duration = "600s"
}

resource "google_pubsub_subscription" "worker" {
  project = var.project_id
  name    = "request-worker-subscription"
  topic   = google_pubsub_topic.request.name
}

module "gce-container" {
  source  = "terraform-google-modules/container-vm/google"
  version = "3.1.0"

  container = {
    image = var.image
  }
}

module "mig_template" {
  source  = "terraform-google-modules/vm/google//modules/instance_template"
  version = "~> 7.3"

  project_id = var.project_id
  region     = var.region
  service_account = {
    email  = var.sa_email
    scopes = toset(["cloud-platform"])
  }

  disk_size_gb = 10
  metadata = {
    "gce-container-declaration"    = module.gce-container.metadata_value
    "google-logging-enabled"       = "true"
    "google-logging-use-fluentbit" = "true"
  }
  name_prefix          = "worker-template"
  network              = var.network_self_link
  source_image         = reverse(split("/", module.gce-container.source_image))[0]
  source_image_family  = "cos-stable"
  source_image_project = "cos-cloud"
  subnetwork           = var.subnetwork_self_link
  subnetwork_project   = var.network_project_id
}

resource "google_compute_region_instance_group_manager" "mig" {
  provider           = google-beta
  base_instance_name = "worker-instance"
  project            = var.project_id
  region             = var.region

  version {
    name              = "worker-mig-version-0"
    instance_template = module.mig_template.self_link
  }

  name               = "worker-mig"
  wait_for_instances = false
  target_size        = null

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_region_autoscaler" "autoscaler" {
  provider = google-beta
  name     = "worker-autoscaler"
  project  = var.project_id
  region   = var.region

  target = google_compute_region_instance_group_manager.mig.self_link

  autoscaling_policy {
    max_replicas    = 3
    min_replicas    = 0
    cooldown_period = 60
    mode            = "ON"

    scale_in_control {
      max_scaled_in_replicas {
        percent = 100
      }
      time_window_sec = 120
    }

    metric {
      name                       = "pubsub.googleapis.com/subscription/num_undelivered_messages"
      single_instance_assignment = 1
      filter                     = "resource.type = pubsub_subscription AND resource.labels.subscription_id = ${google_pubsub_subscription.worker.id}"
    }
  }

  depends_on = [google_pubsub_subscription.worker]
}
```

### Debug Output

The autoscaler deploys without errors, but when looking at the instance group it shows this message:
`On: Target Pub/Sub: Expired on invalid subscription: [projects/[PROJECT_ID]/subscriptions/request-worker-subscription`

Whilst in that state, the autoscaler doesn't work. Nevertheless, If I click on edit the instance group on the console, and save straight away (without touching anything else), the error disappears and the autoscaling works as expected.

Of course, the error then reappears when the template is redeployed.

### Panic Output

No panic

### Expected Behavior

The autoscaler should detect the subscription and initialize correctly, or at least terraform should throw an error explaining the required format for the autoscaler filter given the metric name.

### Actual Behavior

Terraform happily deploys the config but the autoscaler doesn't start, even when just "redeploying" with the console (without making any changes) makes it run as expected.

### Steps to Reproduce

1. Provide the required variables and run `terraform apply`
2. In the console, go to [instance groups](https://console.cloud.google.com/compute/instanceGroups) and observe the status of "autoscaling"
3. Fix it by opening the instance group, click on edit and then on save.
4. Deploy a new image revision and the error will appear again

**Comment by edwardmedia** [comment]
@luisds95 not sure what the details of your modules. Can you share your debug log?

**Comment by edwardmedia** [comment]
@luisds95 is this still an issue?

**Comment by edwardmedia** [comment]
@luisds95 you know the terraform is just a pass-through to the api for what you want for the config. It has limited control over what is right and what is wrong in term of the configurations. . As long as the API accepts, we assume ti is good. 

One thing I would suggest for you to debug is once you have a working config, you may import the resources and then see what settings are needed.

Does this make sense?

**Comment by luisds95** [comment]
Ah, that was quite helpful, thank you @edwardmedia!

The misconfiguration was in fact in the filter, this is what I had
`filter  = "resource.type = pubsub_subscription AND resource.labels.subscription_id = ${google_pubsub_subscription.worker.id}"`
And this is what it should have been
`filter = "resource.type = pubsub_subscription AND resource.labels.subscription_id = \"${google_pubsub_subscription.worker.name}\""`

As this can't be handled in Terraform directly, can I suggest to at least do one of:
1. Update the documentation with an example of MIG with pubsub autoscaling (at least I couldn't find any)
2. Raise the issue up to the API to improve validation on these cases. I'm not sure where would this be either.

**Comment by edwardmedia** [comment]
@luisds95 is this still an issue?

**Comment by edwardmedia** [comment]
@luisds95 closing assuming this is no longer an issue
