### ISSUE TITLE
Add support for edgenetwork API

### ISSUE THREAD

**Issue by f1urps** [hashicorp/terraform-provider-google#15636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Full support should be added for the [edgenetwork API](https://cloud.google.com/distributed-cloud/edge/latest/docs/reference/network/rest) for Distributed Cloud Edge. This should include all resources in the API:

* Network
* Subnet
* Router
* Interconnect
* InterconnectAttachment

### New or Affected Resource(s)

* google_edgenetwork_*

### References

* #14275 

b/298049932

**Comment by f1urps** [comment]
I will work on this.

**Comment by melinath** [comment]
Could you please split this into separate tickets for minimal sets of resources that can be added together?

**Comment by f1urps** [comment]
> Could you please split this into separate tickets for minimal sets of resources that can be added together?

Done; created #15664, #15665, and #15666

**Comment by melinath** [comment]
Closing since this is now covered by those three tickets
