### ISSUE TITLE
`logging_project_bucket_config` creation is flaky and prone to failure

### ISSUE THREAD

**Issue by michaellzc** [hashicorp/terraform-provider-google#15630]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
1.3.3
```

### Affected Resource(s)

* `logging_project_bucket_config`

### Terraform Configuration Files

```tf
data "google_project" "self" {
  project_id = "some-project"
}
resource "random_id" "bucket_1" {
  prefix      = "src-test-"
  byte_length = 3
}
resource "google_logging_project_bucket_config" "bucket_1" {
    bucket_id        = random_id.bucket_1.hex
    description      = "Test logs"
    enable_analytics = false
    location         = "global"
    project          = data.google_project.self.project_id
    retention_days   = 30
}
```

### Debug Output

https://gist.github.com/michaellzc/95b4f01e83cf40c656712f3db08d7862

takeaways from the debug logs:

- check if bucket is there -> 404
- create -> timeout
- create (retry due to timeout earilier) -> 409 (Bucket audit-logs-bucket already exists)

### Expected Behavior

It should create the logging bucket successfully

### Actual Behavior

Notes: this does not happen all the time, maybe 1 out of every 2 applies.

```
│ Error: Error creating Bucket: googleapi: Error 409: Bucket audit-logs-bucket already exists
│ 
│   with google_logging_project_bucket_config.app_auditlogs_auditlogslogbucket_ECEBB224,
│   on cdk.tf.json line 297, in resource.google_logging_project_bucket_config.app_auditlogs_auditlogslogbucket_ECEBB224:
│  297:       },
```

### Steps to Reproduce

1. target a fresh project
1. `terraform apply -auto-approve`
2. then you got the error

### Important Factoids

The apply is done on terraform cloud using remote execution where the networking environment could be a factor.

### References

* #0000

**Comment by edwardmedia** [comment]
b/297561392

**Comment by pengq-google** [comment]
May I have your Terraform version? I am not sure what causes it yet, but I confirmed about 1 week ago that with Terraform version 3.46.0, it can't create log bucket. However, with version 4.70.0 it can. 
I agree it should not be flaky.

**Comment by michaellzc** [comment]
> May I have your Terraform version? I am not sure what causes it yet, but I confirmed about 1 week ago that with Terraform version 3.46.0, it can't create log bucket. However, with version 4.70.0 it can. I agree it should not be flaky.

per debug logs:

```
User-Agent: Terraform/1.3.3 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.79.0
```

this is happening to `4.69.1` as well. we upgraded to the `4.79.0` hoping it fixed it, but it didn't)

**Comment by michaellzc** [comment]
we found out about the double `CreateBucket` calls by inspecting GCP audit logs, and led of to enable debug logging in terraform to understand what exactly is going one

**Comment by pengq-google** [comment]
First, in your debug output (thank you for providing it!) I saw 3 errors as non-retryable and then immediately seen as retryable and retried on. I believe it means something is wrong in the retry transport. But I am not sure it is the root cause to this flaky creation behavior.

Second, is it possible that I can have your project id?

**Comment by michaellzc** [comment]
> First, in your debug output (thank you for providing it!) I saw 3 errors as non-retryable and then immediately seen as retryable and retried on. I believe it means something is wrong in the retry transport. But I am not sure it is the root cause to this flaky creation behavior.
> 
> Second, is it possible that I can have your project id?

Would you email me at [michael.lin@sourcegraph.com](mailto:michael.lin@sourcegraph.com)? Happy to provide potentially sensitive information over there.

**Comment by pengq-google** [comment]
Are all log buckets experiencing issues when they are created with log analytics enabled, a.k.a, with configuration "analyticsEnabled": true?

This may explain the timeout error, because creating log analytics enabled bucket takes more time. Please try increasing timeout request: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_timeout

:)

I'll update if I find anything new.

**Comment by michaellzc** [comment]
> Are all log buckets experiencing issues when they are created with log analytics enabled, a.k.a, with configuration "analyticsEnabled": true?
> 
> This may explain the timeout error, because creating log analytics enabled bucket takes more time. Please try increasing timeout request: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_timeout
> 
> :)
> 
> I'll update if I find anything new.

We have 4 logging buckets and 3 of them have `enabled_analytics=true`. At a glance, those that have log analytics enabled tend to fail the most.

This might explain it. We will try to increase the timeout.

**Comment by michaellzc** [comment]
After increasing the `request_timeout` setting, it seems like we no longer run into errors when creating logging buckets.
