### ISSUE TITLE
google_compute_security_policy: advanced_options_config.user_ip_request_headers is set to null when empty list is passed

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#15646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_security_policy

### Expected Behavior
After 'terraform apply' it should not show as difference. 

### Actual Behavior
It shows as a change on second execution
When advanced_options_config.user_ip_request_headers is set to null or empty list code is setting it as null and showing diff on second execution.

```
 ~ resource "google_compute_security_policy" "policy" {
        id          = "projects/sinprj/global/securityPolicies/my-test-ca-policy-1"
        name        = "my-test-ca-policy-1"
        # (5 unchanged attributes hidden)

      ~ advanced_options_config {
          + user_ip_request_headers = []
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (5 unchanged blocks hidden)
    }
```

```
~ advanced_options_config    = [
  ~ {
    ~ user_ip_request_headers = null -> []
    # (3 unchanged attributes hidden)
    },
]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
b/297920817

**Comment by felipegc** [comment]
Hi @imrannayer I could not reproduce exactly this scenario. Would it be possible to provide the "block hidden" too?

**Comment by felipegc** [comment]
The "user_ip_request_headers" list is not being erased once you created with few elements. In order to make it work we must send an empty "advanced_options_config" alongside updateMask="advanced_options_config.user_ip_request_headers"

**Comment by imrannayer** [comment]
You can reproduce by passing any value in `advanced_options_config` and dont set `user_ip_request_headers` or set it to an empty list []. 

Here is the code to reproduce the issue:


```
resource "google_compute_security_policy" "policies" {
  provider    = google-beta
  name        = "smoke-test-policy"
  description = "Quick and Dirty TF test"
  project     = "my-project-id"
  type        = "CLOUD_ARMOR"

  advanced_options_config {
    json_parsing = "STANDARD"
  }

}
```


```
resource "google_compute_security_policy" "policies" {
  provider    = google-beta
  name        = "smoke-test-policy"
  description = "Quick and Dirty TF test"
  project     = "my-project-id"
  type        = "CLOUD_ARMOR"

  advanced_options_config {
    json_parsing = "STANDARD"
    user_ip_request_headers = []
  }

}
```
