### ISSUE TITLE
Add support for `cgroupMode` option under `linux_node_config` for GKE nodes

### ISSUE THREAD

**Issue by arpitairan** [hashicorp/terraform-provider-google#15656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE has made the use of [cgroup v2](https://kubernetes.io/docs/concepts/architecture/cgroups/) the default since GKE v1.26 and has added the [Linux cgroup mode configuration options](https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#cgroup-mode-options) to allow customers to change from the default `CGROUP_MODE_V2` to `CGROUP_MODE_V1` to avoid issues like [Node memory usage on cgroupv2 reported higher than cgroupv1](https://github.com/kubernetes/kubernetes/issues/118916).

The option to manage the cgroup mode configuration under [LinuxNodeConfig](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#linuxnodeconfig) seems to be missing from the Terraform Google Provider.

Please add the `cgroup_mode` option under `linux_node_config` similar to how [Upstream support for Kubelet and Linux Node configurations in GKE](https://github.com/hashicorp/terraform-provider-google-beta/pull/2403) was added.

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
  ...
  node_config {
     ...
    linux_node_config {
      sysctls {
        ...
      }
      cgroup_mode = string
    }
  }
}
```

### References

* [Linux cgroup mode configuration options](https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#cgroup-mode-options)
* [LinuxNodeConfig](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#linuxnodeconfig)
* [Upstream support for Kubelet and Linux Node configurations in GKE](https://github.com/hashicorp/terraform-provider-google-beta/pull/2403)

b/299312482

**Comment by toVersus** [comment]
I submitted the PR to add this feature. See https://github.com/GoogleCloudPlatform/magic-modules/pull/8997.
