### ISSUE TITLE
Should `reconcile_connections` be enabled by default on `google_compute_service_attachment`?

### ISSUE THREAD

**Issue by kyle-burnett** [hashicorp/terraform-provider-google#15652]
Should the new `reconcile_connections` attribute on the `google_compute_service_attachment` resource be set to True by default?

https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/compute/resource_compute_service_attachment.go#L139-L149

```go
	"reconcile_connections": {
		Type:     schema.TypeBool,
		Optional: true,
		ForceNew: true,
		Description: `This flag determines whether a consumer accept/reject list change can reconcile the statuses of existing ACCEPTED or REJECTED PSC endpoints.

If false, connection policy update will only affect existing PENDING PSC endpoints. Existing ACCEPTED/REJECTED endpoints will remain untouched regardless how the connection policy is modified .
If true, update will affect both PENDING and ACCEPTED/REJECTED PSC endpoints. For example, an ACCEPTED PSC endpoint will be moved to REJECTED if its project is added to the reject list.

For newly created service attachment, this boolean defaults to true.`,
		Default: true,
```

According to Google documentation this feature is disabled by default for new Service Attachments - https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#publish-service-explicit

>[Connection reconciliation](https://cloud.google.com/vpc/docs/about-vpc-hosted-services#connection-reconciliation) is disabled by default for new service attachments. To create a service attachment that has connection reconciliation enabled, use the Google Cloud CLI or the API.

The default provider behavior does not seem to match the default API behavior here.

This is also a breaking change for any existing Service Attachment since we force re-creation when this attribute changes. That doesn't seem to line up with the feature's documentation since it implies that this can be enabled and disabled at-will on an existing Service Attachment - https://cloud.google.com/sdk/gcloud/reference/compute/service-attachments/update

**Comment by edwardmedia** [comment]
From its [api doc](https://cloud.google.com/compute/docs/reference/rest/beta/serviceAttachments), it says

```
For newly created service attachment, this boolean defaults to true.
```

**Comment by kyle-burnett** [comment]
Ah interesting. Seems to be some discrepancies in the various docs then.

**Comment by edwardmedia** [comment]
@kyle-burnett I can't figure out why they are different. But from the terraform provider's perspective, we use the api  as its standard and it is correct. Sorry about the confusion. Closing this question now.  Feel free to reopen if you see a strong argument.  Thanks
