### ISSUE TITLE
Not able to create GKE cluster using terraform 

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#15675]

**Comment by edwardmedia** [comment]
@bptambake does the example [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended) work for you?

**Comment by bptambake** [comment]
Please dont close ticket.. i tried that its not working

**Comment by bptambake** [comment]
Please dont close ticket.. i tried that its not working

**Comment by bptambake** [comment]
You can close other.. but will continue in this ticket

**Comment by bptambake** [comment]
I tried this approach its not working
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/8780d6ce-d671-466d-8ff9-fab7790b0acf)

**Comment by bptambake** [comment]
This document is not correctly defined. we are getting errors upon following this.
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/869bdcf8-413e-4065-a4df-6079b12d099a)

**Comment by bptambake** [comment]
Hi Team
can you please give me one working example on this below code mentioned by terraform

![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/ec6c25c3-6766-4fba-80d5-a4acc7238f28)

**Comment by edwardmedia** [comment]
@bptambake we do not own the repo you mentioned. Below is the one I would suggest you try. If you encounter a problem, let us know.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

**Comment by bptambake** [comment]
Hi Team
the link I am following is also from official terraform
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/guides/using_gke_with_terraform
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/7b355951-a0a4-4a7b-afcc-b472b1e3bf07)

**Comment by bptambake** [comment]
> @bptambake do you have the gke cluster already when you run your [config](https://github.com/hashicorp/terraform-provider-google/issues/15675#issue-1873489289) below? Based on the subject of the issue, you want to create a gke instance, but below config is the one for the situation where you have already had one. If you want to create a fresh GKE instance, make sure you choose **resource** not **data** in your config. I have explained that [here](https://github.com/hashicorp/terraform-provider-google/issues/15675#issuecomment-1699144507)
> 
> For a working config, I have given you examples [here](https://github.com/hashicorp/terraform-provider-google/issues/15675#issuecomment-1701072494). Does it make sense?
> 
> ```terraform
> ### this config only works when you have already had a gke instance, eesy-basu
> 
> data "google_client_config" "default" {
> }
> 
> data "google_container_cluster" "eesy-basu" {
>   name = "eesy-basu"
>   location = "us-central1"
> }
> 
> provider "kubernetes" {
>   host  = "https://${data.google_container_cluster.eesy-basu.endpoint}"
>   token = data.google_client_config.default.access_token
>   cluster_ca_certificate = base64decode(
>     data.google_container_cluster.eesy-basu.master_auth[0].cluster_ca_certificate,
>   )
> }
> ```

I am sorry, but I am not able to understand how this works only for existing cluster,, in that document its not mentioned the same.
If cluster is already there then whats the use of this block? can you please help me understand.

![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/1a225e35-e68d-419e-9cf8-4762cb748fe6)

**Comment by edwardmedia** [comment]
@bptambake I guess you understand the difference between [resource](https://developer.hashicorp.com/terraform/language/resources) and [data source](https://developer.hashicorp.com/terraform/language/data-sources)? If not, mind spending some time on that? Below config is not going to help create a resource.

```
data "google_container_cluster" "eesy-basu" {
  name = "eesy-basu"
  location = "us-central1"
}
```

**Comment by edwardmedia** [comment]
@bptambake not sure why you removed all your comments and updated the title to **b**. I have restored the subject for reference.
My guess is you on longer has the issue/question? Closing this accordingly. Feel free to reopen if you have more questions.

**Comment by bptambake** [comment]
I didn't feel this useful anymore, so I removed it. the issue was not addressed correctly, so I removed it.. sorry..
