### ISSUE TITLE
Provider crashed: managed_zone_id value out of range

### ISSUE THREAD

**Issue by AlxCloudRl** [hashicorp/terraform-provider-google#15676]
_Issue_: Doing a Terraform plan, I get a **crash panic** by Google Terraform provider, related to an **ID that is too big to parse**. This ID is stored in the Terraform state for the google_dns_managed_zone ressource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

**Terraform v1.5.5**
on linux_386
+ provider registry.terraform.io/hashicorp/**google v4.80.0**
+ provider registry.terraform.io/hashicorp/google-beta v4.80.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Affected Resource(s)

- **google_dns_managed_zone**

### Terraform Configuration Files

It's not an issue about the config but about a crash due to a ressource ID stored in the state, considered too big by Google terraform provider.

### Panic Output

https://gist.github.com/AlxCloudRl/308303af9916a30628846cf93d81e1fe

### Steps to Reproduce

 `terraform plan`

### Important Factoids

The out of range value (6159704459778898177) is the ID (managed_zone_id) in the state of the created google_dns_managed_zone ressource.

```
"module": "module.gcp-gke",
      "mode": "managed",
      "type": "google_dns_managed_zone",
      "name": "gitlab",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cloud_logging_config": [
              {
                "enable_logging": false
              }
            ],
            "creation_time": "2023-08-21T08:32:20.169Z",
            "description": xxx",
            "dns_name": "xxx",
            "dnssec_config": [],
            "force_destroy": false,
            "forwarding_config": [],
            "id": "projects/xxx/managedZones/xxxl",
            "labels": {},
            "managed_zone_id": 6159704459778898177,
            "name": "xxx",
            "name_servers": [
              "ns-gcp-private.googledomains.com."
            ],
           ...
```

Thanks

**Comment by slevenick** [comment]
@AlxCloudRl Are you running this on a 32-bit system? We are aware of a problem with the Terraform SDK related to 32-bit systems and integers that can't fit into 32 bits.

Unfortunately we don't have a lot of options to work around this, as it's a restriction at the SDK level

See https://github.com/hashicorp/terraform-plugin-sdk/issues/1236

**Comment by slevenick** [comment]
Hm, from your original bug report it looks like the output of terraform -v is:
```
Terraform v1.5.5
on linux_386

provider registry.terraform.io/hashicorp/google v4.80.0
provider registry.terraform.io/hashicorp/google-beta v4.80.0
provider registry.terraform.io/hashicorp/null v3.2.1
provider registry.terraform.io/hashicorp/random v3.5.1
provider registry.terraform.io/hashicorp/time v0.9.1
```

I believe linux_386 is a 32-bit system which would explain this issue. Are you getting the same result on the 64-bit x86_64? Can you provide the output of terraform -v on that system?
