### ISSUE TITLE
Not able to create GKE cluster using terraform

### ISSUE THREAD

**Issue by bptambake** [hashicorp/terraform-provider-google#15674]
I was able to create GKE cluster earlier, but now its failing with the below error.

### Terraform Version

![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/1821271c-e665-46a6-930b-19e12224430a)

Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/google v4.58.0
+ provider registry.terraform.io/hashicorp/google-beta v4.58.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

below is the error:
data.google_client_config.default: Reading...
module.gke.data.google_container_engine_versions.region: Reading...
module.gke.data.google_compute_zones.available: Reading...
╷
│ Error: oauth2: cannot fetch token: 400 Bad Request
│ Response: {
│   "error": "invalid_grant",
│   "error_description": "reauth related error (rapt_required)",
│   "error_uri": "https://support.google.com/a/answer/9368756",
│   "error_subtype": "rapt_required"
│ }
│
│   with data.google_client_config.default,
│   on eesy-cluster.tf line 24, in data "google_client_config" "default":
│   24: data "google_client_config" "default" {}
│
╵
╷
│ Error: Get "https://compute.googleapis.com/compute/beta/projects/project-id/zones?alt=json&filter=&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
│ Response: {
│   "error": "invalid_grant",
│   "error_description": "reauth related error (rapt_required)",
│   "error_uri": "https://support.google.com/a/answer/9368756",
│   "error_subtype": "rapt_required"
│ }
│
│   with module.gke.data.google_compute_zones.available,
│   on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 22, in data "google_compute_zones" "available":
│   22: data "google_compute_zones" "available" {
│
╵
╷
│ Error: Error retrieving available container cluster versions: Get "https://container.googleapis.com/v1/projects/project-id/locations/us-central1/serverConfig?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
│ Response: {
│   "error": "invalid_grant",
│   "error_description": "reauth related error (rapt_required)",
│   "error_uri": "https://support.google.com/a/answer/9368756",
│   "error_subtype": "rapt_required"
│ }
│
│   with module.gke.data.google_container_engine_versions.region,
│   on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 198, in data "google_container_engine_versions" "region":
│  198: data "google_container_engine_versions" "region" {

### References

* #0000

**Comment by bptambake** [comment]
![image](https://github.com/hashicorp/terraform-provider-google/assets/45705075/39c41252-13a3-48ad-930e-eccabeeeec03)

**Comment by bptambake** [comment]
below is the code i am using

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.64.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.64.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.12"
    }
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.14.0"
    }
  }
}

# google_client_config and kubernetes provider must be explicitly specified like the following.
data "google_client_config" "default" {}

data "google_container_cluster" "eesy-basu" {
  name     = "eesy-basu"
  location = "us-central1"
}

provider "kubernetes" {
  host  = "https://${data.google_container_cluster.eesy-basu.endpoint}"
  token = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.eesy-basu.master_auth[0].cluster_ca_certificate,
  )
}

provider "kubectl" {
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
  load_config_file       = false
}

**Comment by bptambake** [comment]
below is the code which I am usning

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.64.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.64.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.12"
    }
    kubectl = {
      source = "gavinbunney/kubectl"
      version = "1.14.0"
    }
  }
}

data "google_client_config" "default" {}

data "google_container_cluster" "eesy-basu" {
  name     = "eesy-basu"
  location = "us-central1"
}

provider "kubernetes" {
  host  = "https://${data.google_container_cluster.eesy-basu.endpoint}"
  token = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.eesy-basu.master_auth[0].cluster_ca_certificate,
  )
}

provider "kubectl" {
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(module.gke.ca_certificate)
  load_config_file       = false
}

**Comment by bptambake** [comment]
upgraded terraform version to 1.5.6 and still getting below error
╷
│ Error: Error when reading or editing Container Cluster "eesy-basu": Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/clusters/eesy-basu?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│   with data.google_container_cluster.eesy-basu,
│   on eesy-cluster.tf line 27, in data "google_container_cluster" "eesy-basu":
│   27: data "google_container_cluster" "eesy-basu" {
│
╵
╷
│ Error: Get "https://compute.googleapis.com/compute/beta/projects/pid/zones?alt=json&filter=&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│   with module.gke.data.google_compute_zones.available,
│   on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 22, in data "google_compute_zones" "available":
│   22: data "google_compute_zones" "available" {
│
╵
╷
│ Error: Error retrieving available container cluster versions: Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/serverConfig?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│   with module.gke.data.google_container_engine_versions.region,
│   on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 198, in data "google_container_engine_versions" "region":
│  198: data "google_container_engine_versions" "region" {

**Comment by bptambake** [comment]
Hi Team
Getting below error while cretaing GKE cluster
 Error: Error when reading or editing Container Cluster "eesy-basu": Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/clusters/eesy-basu?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with data.google_container_cluster.eesy-basu,
│ on eesy-cluster.tf line 27, in data "google_container_cluster" "eesy-basu":
│ 27: data "google_container_cluster" "eesy-basu" {
│
╵
╷
│ Error: Get "https://compute.googleapis.com/compute/beta/projects/pid/zones?alt=json&filter=&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with module.gke.data.google_compute_zones.available,
│ on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 22, in data "google_compute_zones" "available":
│ 22: data "google_compute_zones" "available" {
│
╵
╷
│ Error: Error retrieving available container cluster versions: Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/serverConfig?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with module.gke.data.google_container_engine_versions.region,
│ on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 198, in data "google_container_engine_versions" "region":
│ 198: data "google_container_engine_versions" "region" {

**Comment by bptambake** [comment]
Hi Team
Getting below error while cretaing GKE cluster
 Error: Error when reading or editing Container Cluster "eesy-basu": Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/clusters/eesy-basu?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with data.google_container_cluster.eesy-basu,
│ on eesy-cluster.tf line 27, in data "google_container_cluster" "eesy-basu":
│ 27: data "google_container_cluster" "eesy-basu" {
│
╵
╷
│ Error: Get "https://compute.googleapis.com/compute/beta/projects/pid/zones?alt=json&filter=&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with module.gke.data.google_compute_zones.available,
│ on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 22, in data "google_compute_zones" "available":
│ 22: data "google_compute_zones" "available" {
│
╵
╷
│ Error: Error retrieving available container cluster versions: Get "https://container.googleapis.com/v1/projects/pid/locations/us-central1/serverConfig?alt=json&prettyPrint=false": oauth2: "invalid_grant" "reauth related error (rapt_required)" "https://support.google.com/a/answer/9368756"
│
│ with module.gke.data.google_container_engine_versions.region,
│ on .terraform/modules/gke/modules/beta-public-cluster/main.tf line 198, in data "google_container_engine_versions" "region":
│ 198: data "google_container_engine_versions" "region" {

**Comment by edwardmedia** [comment]
closing as dup of https://github.com/hashicorp/terraform-provider-google/issues/15675

**Comment by bptambake** [comment]
Please dont close ticket.. i tried that its not working
