### ISSUE TITLE
google_compute_region_security_policy_rule is not able to override default rule

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#15687]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_region_security_policy_rule

### Terraform Configuration Files

```tf

resource "google_compute_region_security_policy" "region_edge_security_policy" {
  provider = google-beta
  project  = var.project_id


  name        = "${var.prefix}-ca-network-edge-policy"
  description = "${var.prefix} CA Edge Network edge security policy for NLB"
  type        = "CLOUD_ARMOR_NETWORK"
  region      = "us-central1"

}

resource "google_compute_region_security_policy_rule" "default_policy_rule" {
  provider = google-beta
  project  = var.project_id

  region = "us-central1"

  security_policy = google_compute_region_security_policy.region_edge_security_policy.name
  description     = "Default rule for network match policy"
  priority        = 2147483647
  network_match {
    src_ip_ranges = ["*"]
  }
  action  = "deny"
  preview = false
}
```

### Expected Behavior
When a new policy is created it has a default allow rule at priority `2147483647`. In order to override it should allow a rule update for priority `2147483647`. 

### Actual Behavior
Getting error
```
 Error: Error creating RegionSecurityPolicyRule: googleapi: Error 400: Invalid value for field 'resource.priority': '2147483647'. Cannot have rules with the same priorities., invalid
```

### Steps to Reproduce

1. `terraform apply`

### References

b/309764406

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/15686

**Comment by slevenick** [comment]
I don't think I understand this. The 400 error says we can't create a new rule with the same priority as an existing one. To override the default rule you need to either import and then modify the default rule, or delete it with another tool and then create a new rule

Second, why is this linked to the other security policy rule bug?

**Comment by imrannayer** [comment]
In [google_compute_security_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy), which creates a global security policy you can provide a rule with priority `2147483647` (lowest priority) which actually overrides the default rule created when you create a security policy. We need to the same behavior in `google_compute_region_security_policy_rule` when a rule with priority `2147483647` is provided instead of creating a rule it should update the existing rule with this priority. 

Here is how the rule looks like in my code:

```
  rule {
    action      = var.default_rule_action
    priority    = "2147483647"
    description = "Default rule, higher priority overrides it"
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
  }
```

**Comment by imrannayer** [comment]
is there any update on this issue?

**Comment by imrannayer** [comment]
Any update on this?

**Comment by asauta-byr** [comment]
I'm not sure why this is not considered a higher prio. Currently the only way to create a regional policy with default Deny rule in Terraform is to add a rule _before_ the default one:

```hcl
  resource "google_compute_region_security_policy_rule" "regional_rule_default" {
    provider = google-beta

    project  = var.project
    region = var.region

    security_policy = google_compute_region_security_policy.regional_policy.name

    preview   = false

    action   = "deny(403)"
    priority = "2147483646"  # Last rule before policy-default rule
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
    description = "Default rule substiute - Deny All"
  }
```

Not only this is confusing because it's inconsistent with both global policy and Google's default behavior, but also can be dangerous because it's easy to forget unless you verified it with console/cli.
