### ISSUE TITLE
State is not managed correctly for google_compute_region_commitment resource

### ISSUE THREAD

**Issue by abdulvirta** [hashicorp/terraform-provider-google#15699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.73.1
+ provider registry.terraform.io/hashicorp/google-beta v4.73.1

### Affected Resource(s)

* google_compute_region_commitment

### Terraform Configuration Files
```tf
resource "google_compute_region_commitment" "general_purpose_n1_1_production" {
  count = var.env == "prod" ? 1 : 0

  name        = "general-purpose-n1-1-production"
  description = "Commitments for general purpose n1"
  project     = local.project
  region      = "us-central1"
  plan        = "TWELVE_MONTH"
  type        = "GENERAL_PURPOSE_N1"
  category    = "MACHINE"
  auto_renew  = false
  resources {
    type   = "VCPU"
    amount = "32"
  }
  resources {
    type   = "MEMORY"
    amount = "208"
  }
}
```

### Expected Behavior
After the resource is created, it shouldn't try to create the resource again on second apply (when there are no changes to the resource configuration)

### Actual Behavior
The resource got created successfully the first time we apply. However, next apply of the same workspace failed because it tried to create the resource again and then fail with alreadyExists error. Looks like it saved the state with type "GENERAL_PURPOSE" and was trying to replace type with "GENERAL_PURPOSE_N1" which is the original and correct type.

### Steps to Reproduce

1. `terraform apply`

The resource gets created

2. `terraform apply` again with no changes on the resource configuration

Fails with alreadyExists error.

**Comment by edwardmedia** [comment]
@abdulvirta this is wired. Where is the state file? Can you share you debug log?

**Comment by edwardmedia** [comment]
@abdulvirta is this still an issue?

**Comment by edwardmedia** [comment]
@abdulvirta closing assuming this is no longer an issue
