### ISSUE TITLE
google_artifact_registry_repository - Support remote repositories for OS packages

### ISSUE THREAD

**Issue by steffencircle** [hashicorp/terraform-provider-google#15703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Artifact Registry now Supports Remote Repositories for OS Packages ( apt & yum).
Since support for the existing Remote Repo Types is already in place, it would be great of support for this could be added to the TF provider.

### New or Affected Resource(s)

* google_artifact_registry_repository 

### Potential Terraform Configuration

```tf
resource "google_artifact_registry_repository" "my-repo" {
  location      = "us-central1"
  repository_id = "my-repository"
  description   = "example remote docker repository"
  format        = "DOCKER"
  mode          = "REMOTE_REPOSITORY"
  remote_repository_config {
    description = "Debian"
    apt_repository {
      remote_repo = "DEBIAN"
      remote_repo_path= "debian/dists/buster"
    }
  }
}
```

### References

* #0000

b/299600940

**Comment by juliocc** [comment]
Is this being worked on? If not @sruffilli and I can take it.
