### ISSUE TITLE
google_compute_snapshot does not allow source_disk to be in a different GCP project

### ISSUE THREAD

**Issue by Fructokinase** [hashicorp/terraform-provider-google#15702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.2

### Affected Resource(s)

* google_compute_snapshot

### Terraform Configuration Files

```tf
resource "google_compute_snapshot" "my_snapshot" {
  name        = "my-snapshot"
  project     = var.project_id
  source_disk = data.google_compute_disk.flutter_snapshot_disk.id
  storage_locations = tolist(var.regions)
}
```

### Debug Output

Dismissed an error as retryable. Retry 404s for GET operation - googleapi: Error 404: The resource 'projects/<var.project_id>/zones/us-central1-a/operations/operation-<operation_id>' was not found, notFound

### Expected Behavior

Operation should be from the source disk's GCP project id

### Actual Behavior

Error: Error waiting to create Snapshot: Error waiting for Creating Snapshot: couldn't find resource (21 retries)

### Steps to Reproduce

1. Create a snapshot resource where the disk source is from a different GCP project than the resource project id
2. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@Fructokinase can you create it via other means like gcloud? If yes, can you share the debug log?

**Comment by edwardmedia** [comment]
@Fructokinase is this still an issue?

**Comment by edwardmedia** [comment]
@Fructokinase closing assuming it is no longer an issue
