### ISSUE TITLE
Add support for FastSocket in GKE node pools

### ISSUE THREAD

**Issue by lgeiger** [hashicorp/terraform-provider-google#15715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be excellent if the [`FastSocket`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#fastsocket) option would be available in GKE node pools similar to how `gvnic` is currently handled.

### New or Affected Resource(s)

- google_container_cluster
- google_container_node_pool

### Potential Terraform Configuration

```tf
  node_config {
    fast_socket {
      enabled = true
    }
  }
```

### References

- https://cloud.google.com/kubernetes-engine/docs/how-to/nccl-fast-socket
- https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#fastsocket

b/299312113

**Comment by rlia** [comment]
I would like to pick this issue up . I will add the PR.
