### ISSUE TITLE
Inconsistent behaviour between SDK and plugin framework provider config code when handling region self-links

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

N/A

### Affected Resource(s)

* Provider configuration

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The SDK provider config code transforms the region value from a self link to a region name: [link to unit test showing this](https://github.com/GoogleCloudPlatform/magic-modules/blob/03c4029cb8bace9904749925a6c316d640c69e51/mmv1/third_party/terraform/provider/provider_internal_test.go#L861-L868)
We'd expect the plugin framework version of that logic to behave the same way

### Actual Behavior

The plugin framework version of that logic leaves the region value as a self link : [link to failing unit test](https://github.com/GoogleCloudPlatform/magic-modules/blob/03c4029cb8bace9904749925a6c316d640c69e51/mmv1/third_party/terraform/fwtransport/framework_config_test.go.erb#L419-L427)

I haven't checked, but I think this doesn't impact users because the `GetRegion` functions used in the provider can accept a self link value and change it into a region name.

### Steps to Reproduce

Uncomment and run the affected unit test using the code that's currently on main branch - the test will fail

### Important Factoids

The SDK and PF provider config code follow the same pattern of having one struct/variable that contains the provider configuration data in a SDK-y or Plugin Framework-y way, and that data is used to populate a struct that's specific to the Google provider. The SDK code performs this truncation of the value when copying the region data to that second struct, but the Plugin Framework code doesn't.

### References

* #0000

**Comment by c2thorn** [comment]
@SarahFrench does https://github.com/GoogleCloudPlatform/magic-modules/pull/8587 also fix this?

**Comment by SarahFrench** [comment]
No it doesn't - that PR only touches helper functions used for finding location/region/zone values for resources and data sources.

This issue is super similar but is specific to the provider config code. I can put in a quick PR to fix this today, but this issue is more of a code-inconsistency issue as I don't think this defect is user facing:

>  I think this doesn't impact users because the GetRegion functions used in the provider can accept a self link value and change it into a region name

**Comment by c2thorn** [comment]
> this issue is more of a code-inconsistency issue (i.e. doesn't need to be done for 5.0.0) as I don't think this defect is user facing

That's fair, then I will remove it from the 5.0.0 milestone just for tracking.

**Comment by SarahFrench** [comment]
👍 Thanks, I'd overlooked that I'd added it to that milestone! I'll make a PR into main and it can be released soon after 5.0.0
