### ISSUE TITLE
Clarify the documentation of google_compute_instance data source regarding attached_disk

### ISSUE THREAD

**Issue by lorenzofelletti** [hashicorp/terraform-provider-google#15718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As per the  `google_compute_instance` documentation, the `attached_disk`s have the `source` field that corresponds to the "name or self_link of the disk attached to this instance".

First, this is not very clear, as it is not specified in which scenarios you get the name rather than the self_link.

Second, why couldn't we get both? As in some case one may prefer one or the other.

### New or Affected Resource(s)

* google_compute_instance (data)

### References

b/312432938

**Comment by rileykarson** [comment]
I think this is always going to be a self link. We can accept a name as input, but the API will always return this so it's what you'll get in the datasource.

**Comment by melinath** [comment]
Would we potentially want to make this data source link to the resource for the argument reference? Similar to https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/artifact_registry_repository#attributes-reference. That would bring it more in line with our standard documentation practices but would unfortunately directly conflict with clarifying this question.
