### ISSUE TITLE
Feature Request: google_dns_managed_zone force_destroy option

### ISSUE THREAD

**Issue by Evesy** [hashicorp/terraform-provider-google#1572]
Hi,

**Feature**
Similar to the AWS provider for Route53 it'd be great if the `google_dns_managed_zone` provided a `force_destroy` option, to first delete all record sets from the zone, before proceeding with the zone deletion.

**Existing behaviour**
Currently if there are records present in the managed zone Terraform is unable to delete the zone:

```
google_dns_managed_zone.dns-zone: Error deleting DNS ManagedZone: googleapi: Error 400: The resource named 'delivery-platform' cannot be deleted because it is not empty, containerNotEmpty
```

**Use case**
In a situation where Terraform is used to provision managed zones within Google Cloud DNS, however the records within that zone are managed by another service, it cannot be guaranteed that all records have been cleaned up from the zone (it may not be a graceful teardown of the environment).

In these scenarios it would be useful to have an optional argument, `force_destroy`, that will clean out the zone before destroying it. 

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_dns_managed_zone

### References
As suggested by @kim0 here: https://github.com/terraform-providers/terraform-provider-google/issues/1215

**Comment by 0verc1ocker** [comment]
This would be a nice feature to have. :+1:

**Comment by atmatthewat** [comment]
In the case where all the records are managed by Terraform, it would be nice if the records were automatically deleted when the zone is deleted. This is an issue if you change the zone such that a new resource is required (e.g., change visibility from public to private).

**Comment by xer0x** [comment]
+1 for a `force_delete` that will modify/move/delete a zone even if it isn't empty.

I appreciate the safety of not clobbing dns zones automatically. However, I would love for Terraform to be able to delete my zone, or move it to another google cloud project.

**Comment by toschneck** [comment]
+1  - we want to manage playground environments with our terraform setup. The clean up would be so much easier with this feature

**Comment by romankor** [comment]
+1 much needed feature

**Comment by emmekappa** [comment]
I have a scenario in which all my zones are fully managed by [external-dns](https://github.com/kubernetes-sigs/external-dns) so it makes perfect sense to allow the destruction of the managed zone even if it contains something.

**Comment by DnR-iData** [comment]
Hi,

Some news for this feature really appreciated ?

Same error today ...

```bash
  Enter a value: yes

google_dns_managed_zone.default: Destroying... [id=projects/xxxxxxxxx/managedZones/xxxxxxxxx]

Error: Error reading ManagedZone: googleapi: Error 400: The resource named 'xxxxxxxx' cannot be deleted because it is not empty, containerNotEmpty
```

My zones are fully managed by external-dns too.


```bash
Terraform v0.12.8
```

Thank you

---
DR

**Comment by MeNsaaH** [comment]
A much needed feature, my records are managed by `external-dns` too
+1
