### ISSUE TITLE
Add support for KSM metrics packages to monitoring_config

### ISSUE THREAD

**Issue by chelseychen** [hashicorp/terraform-provider-google#15720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE is launching a managed-version of kube-state-metrics which provides 6 metrics packages for customers to enable: STORAGE, HPA, POD, DAEMONSET, DEPLOYMENT, and STATEFULSET. These 6 values are added to monitoring_config.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "gke_cluster" {
  provider = google
  name     = "terraform-ksm-enabled"
  location = "us-central1-c"

  monitoring_config{
    enable_components = [ "SYSTEM_COMPONENTS", "STORAGE", "HPA", "POD", "DAEMONSET", "DEPLOYMENT", "STATEFULSET" ]
    managed_prometheus {
      enabled = true
    }
  }
}
```

### References

* Example: https://github.com/GoogleCloudPlatform/magic-modules/pull/6772

**Comment by rileykarson** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-google/issues/15704
