### ISSUE TITLE
Create a plural data source for DNS Managed Zones

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#15737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This data source would allow users to get a list of all DNS zones within a project.

Use case: used to check there is no duplicate peering

### New or Affected Resource(s)

* google_dns_managed_zones

### Potential Terraform Configuration

```tf
data "google_dns_managed_zones" "zones_projecta" {
    project = "qa_project"
}

output "zones_projecta" {
    value = data.google_dns_managed_zones.zones_projecta.dns_names
}
```

### References

* #0000

b/317497290

**Comment by melinath** [comment]
possibly related: https://github.com/hashicorp/terraform-provider-google/issues/8255
