### ISSUE TITLE
Add support for InstanceSettings resource  in GCE

### ISSUE THREAD

**Issue by arungantasala** [hashicorp/terraform-provider-google#15748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Authoritatively manages metadata common to all instances in a specific zone in GCE. 

### New or Affected Resource(s)

* google_compute_instance_settings

### Potential Terraform Configuration

```tf
resource "google_compute_instance_settings" "<%= ctx[:primary_resource_id] %>" {
  zone = "us-central1-a"
  metadata {
    items = {
      foo = "baz"
    }
  }
}
```

### References

* [Instance Settings](https://cloud.google.com/compute/docs/reference/rest/beta/instanceSettings)
* [Metadata](https://cloud.google.com/compute/docs/metadata/overview)

**Comment by SarahFrench** [comment]
These settings are currently represented as separate resources/datasources in the provider:
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_project_metadata
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account

Does this help with your use case?

**Comment by arungantasala** [comment]
Added a PR. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_project_metadata stores metadata on a global project resource. Here, we are requesting zonal version of the settings which are used by GCE Instance APIs.
default_service_account setting is not required now at zonal instance settings.

**Comment by melinath** [comment]
@arungantasala could you elaborate on which API specifically you want to call that is not currently supported?

**Comment by melinath** [comment]
looks like this is for https://cloud.google.com/compute/docs/reference/rest/beta/instanceSettings which is a new resource 👍
