### ISSUE TITLE
google_database_migration_service_connection_profile unable to create without a public IP

### ISSUE THREAD

**Issue by watsonjm** [hashicorp/terraform-provider-google#15755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.6
+ provider registry.terraform.io/hashicorp/google v4.81.0

### Affected Resource(s)

google_database_migration_service_connection_profile

### Terraform Configuration Files

```tf
resource "google_database_migration_service_connection_profile" "destination" {
  location              = data.google_compute_zones.available.region
  connection_profile_id = "${local.prefix}-test"
  display_name          = "${local.prefix}-test"
  cloudsql {
    settings {
      auto_storage_increase = true
      data_disk_size_gb     = "100"
      data_disk_type        = "PD_SSD"
      database_flags        = {}
      database_version      = "POSTGRES_15"
      source_id             = google_database_migration_service_connection_profile.source.name
      tier                  = "db-custom-4-26624"
      user_labels           = {}
      zone                  = element(data.google_compute_zones.available.names, length(data.google_compute_zones.available.names) - 1)

      ip_config {
        enable_ipv4     = false
        require_ssl     = true
        private_network = google_compute_network.main.id
      }
    }
  }
  labels = local.common_labels
}
```

### Expected Behavior

When I have `settings.ip_config.enable_ipv4 = false` I would expect there to be no public IP on the Cloud SQL instance created by this. This is assuming that `enable_ipv4` functions the same way as `settings.ip_configuration.ipv4_enabled` does in the resource google_sql_database_instance.

### Actual Behavior

When the Cloud SQL instance is created, it always has a public IP on the instance
### Steps to Reproduce

1. `terraform apply -target google_database_migration_service_connection_profile.destination -auto-approve`

### Important Factoids

It was initially ran with `enable_ipv4 = true`, and then I destroyed the connection profiles and manually deleted the Cloud SQL resources created by this, and then re-applied with `enable_ipv4 = false`, and still had a public IP.

**Comment by edwardmedia** [comment]
@watsonjm can you share the debug log? I guess this is controlled by the api and there is not much we can do at the provider level

**Comment by edwardmedia** [comment]
@watsonjm is this still an issue?

**Comment by edwardmedia** [comment]
@watsonjm any updates?

**Comment by edwardmedia** [comment]
@watsonjm closing this assuming it is no longer an issue. Feel free to reopen if otherwise
