### ISSUE TITLE
Resource_ancestors budget_filter Question

### ISSUE THREAD

**Issue by mdkubiak** [hashicorp/terraform-provider-google#15752]
If you have a support request or question please submit them to one of these resources:
Hello,

Not sure what I may be doing wrong but when I try to use the budget_filter with resource_ancestors, it says resource_ancestors is not expected here

Here is the example code from https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget.html#nested_all_updates_rule

This is what it says about this filter
_[resource_ancestors](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget.html#resource_ancestors) - (Optional) A set of folder and organization names of the form folders/{folderId} or organizations/{organizationId}, specifying that usage from only this set of folders and organizations should be included in the budget. If omitted, the budget includes all usage that the billing account pays for. If the folder or organization contains projects that are paid for by a different Cloud Billing account, the budget doesn't apply to those projects._

Here is the example code I used as a test after I couldn't get it to work
_resource "google_billing_budget" "budget" {
  billing_account = data.google_billing_account.account.id
  display_name = "Example Billing Budget"

  budget_filter {
    projects               = ["projects/${data.google_project.project.number}"]
    credit_types_treatment = "INCLUDE_SPECIFIED_CREDITS"
    services               = ["services/24E6-581D-38E5"] # Bigquery
    credit_types           = ["PROMOTION", "FREE_TIER"]
    resource_ancestors     = ["organizations/123456789"]
  }_

Here is the error
_│ Error: Unsupported argument
│
│   on budget.tf line 12, in resource "google_billing_budget" "budget":
│   12:     resource_ancestors = ["organizations/123456789"]
│
│ An argument named "resource_ancestors" is not expected here._

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@mdkubiak I see resource_ancestors in the [code](https://github.com/hashicorp/terraform-provider-google/blob/0b063b1c892decf057ef5a35954a1c436aab2cec/google/services/billing/resource_billing_budget.go#L325)

Are you able to apply a config like the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#example-usage---billing-budget-filter)? If not, can you share the debug log?

**Comment by edwardmedia** [comment]
b/299482340

**Comment by mdkubiak** [comment]
> @mdkubiak I see resource_ancestors in the [code](https://github.com/hashicorp/terraform-provider-google/blob/0b063b1c892decf057ef5a35954a1c436aab2cec/google/services/billing/resource_billing_budget.go#L325)
> 
> Are you able to apply a config like the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#example-usage---billing-budget-filter)? If not, can you share the debug log?

I'm new to Terraform so I'll try to figure that out setting up debugging, but yes, I used the example code and it fails 

resource "google_billing_budget" "budget" {
  billing_account = data.google_billing_account.account.id
  display_name    = "Control Tower Billing Budget"

  budget_filter {
    projects = ["projects/EXAMPLE"] #NOTE: Edited to not show company information
    #projects               = ["projects/${data.google_project.project.number}"]
    credit_types_treatment = "INCLUDE_SPECIFIED_CREDITS"
    services               = ["services/24E6-581D-38E5"] # Bigquery
    credit_types           = ["PROMOTION", "FREE_TIER"]
    resource_ancestors     = ["organizations/123456789"]
  }
  

│ Error: Unsupported argument
│
│   on budget.tf line 16, in resource "google_billing_budget" "budget":
│   16:     resource_ancestors     = ["organizations/123456789"]
│
│ An argument named "resource_ancestors" is not expected here.

**Comment by mdkubiak** [comment]
Fixed the issue.  I was running on 4.77 and the version that this was introduced in was 4.78.  I had to run terraform -init upgrade

**Comment by edwardmedia** [comment]
Cool.
For [debug](https://developer.hashicorp.com/terraform/internals/debugging), set an environment variable on your machine 

```
export TF_LOG=DEBUG 
```

Closing the issue now
