### ISSUE TITLE
Skip delete operation for bare metal admin cluster resource

### ISSUE THREAD

**Issue by naitianliu-google** [hashicorp/terraform-provider-google#15766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently the delete operation maps to the unenroll API because we do not have the delete API method to clean up the admin cluster resource and all its dependencies. However, customers may feel confused after running terraform destroy but the admin cluster resource is not actually deleted. After the internal discussion, we decide to map the delete operation to no-op in TF and guide users to manually delete admin cluster resource in the doc.

Here is the bug for more context. b/298059927

https://github.com/GoogleCloudPlatform/magic-modules/pull/8823

Please note this is a breaking change and need to be tracked in 5.0.0 release. 

### New or Affected Resource(s)

* google_gkeonprem_bare_metal_admin_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8823
