### ISSUE TITLE
Remove Firebase Location

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#15763]
### Description

deprecated `google_firebase_project_location` in favor of `google_firebase_storage_bucket` and `google_firestore_database`

### New or Affected Resource(s)

* google_ google_firebase_project_location

### References

* #0000

b/299600718

**Comment by rainshen49** [comment]
b/294255999

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8783
