### ISSUE TITLE
Missing functionality: Assign address for use in Stateful Instance Group (beta)

### ISSUE THREAD

**Issue by djsmiley2k** [hashicorp/terraform-provider-google#15774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It appears the functionality to assign a IP statically to a VM when in a stateful instance group is missing. This functionality exists via the gcloud command process - documented [here](https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-ip-addresses-in-migs#gcloud_3) allowing adding a IP either as a string, or as the url of a address object. This appears to be missing from the terraform currently./

### New or Affected Resource(s)

google_compute_instance_group_manager

### Potential Terraform Configuration

```tf
  stateful_internal_ip {
     interface_name = "nic0" # Optional, default: nic0
     delete_rule = "NEVER" # Enum: ON_PERMANENT_INSTANCE_DELETION, NEVER (default)
     address = var.network_ip
  }
```

### References

* https://cloud.google.com/compute/docs/reference/rest/beta/regionInstanceGroupManagers#InstanceGroupManager.FIELDS.inlinedField_61

**Comment by khtelus** [comment]
@djsmiley2k I _believe_ what you are looking for can be done via https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_per_instance_config

**Comment by SarahFrench** [comment]
There are fields for setting internal and external IPs, but they're present in the Beta version of the API only

**Comment by askubis** [comment]
@djsmiley2k this is not actually defined. you can create a per-instance config for existing instance. But if you specify the name that is not within the IGM, it will create a new instance. 

@SarahFrench the GA fields will be present in the next release (ETA Oct 11 IIUC, see https://github.com/GoogleCloudPlatform/magic-modules/pull/9115).
It is on both regional and zonal. Could you show me the page where you don't see the internal/external ips?

**Comment by djsmiley2k** [comment]
@askubis ah ok that matches what I was seeing at least, a new instance is created, with the name given. Only problem I have now is if that instance is ever removed (instance group reduced to zero/recycled), the IP's are 'lost' again and not reapplied.

**Comment by askubis** [comment]
@djsmiley2k well, resizing instance group to 0 is deliberate user action. If you do that you should be aware of the consequences. 
Also, If you have a MIG with 0 instances and a per-instance config that's some misconfiguration. I am NOT sure how terraform handles that. My intuition is that terraform should signal this configuration is impossible. 

on the other hand: there is autoDelete field for the Stateful Ips. If you set it to NEVER the address will not be deleted. 
(IIUC if you are using terraform and have defined the google_compute_address resource (that you're using for per_instance_config) it would get recreated after another "terraform apply", even if it got deleted due to autoDelete=ON_PERMANENT_INSTANCE_DELETION).

**Comment by SarahFrench** [comment]
> @SarahFrench the GA fields will be present in the next release (ETA Oct 11 IIUC, see https://github.com/GoogleCloudPlatform/magic-modules/pull/9115).
It is on both regional and zonal. Could you show me the page where you don't see the internal/external ips?

I can't - those notes I posted were from during triage and I think I was writing what someone was dictating. I'll update the comment above.

**Comment by SarahFrench** [comment]
Should this issue be closed given that https://github.com/GoogleCloudPlatform/magic-modules/pull/9115 is merged? Is there any remaining work to be done?
