### ISSUE TITLE
Firestore: Add ability to configure Point-in-time-recovery (PITR)

### ISSUE THREAD

**Issue by IchordeDionysos** [hashicorp/terraform-provider-google#15788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now it's not possible to configure PITR using Terraform.
To effectively configure Firestore via Terraform this is an essential feature.

### New or Affected Resource(s)

* google_firestore_database

### Potential Terraform Configuration

```tf
resource "google_firestore_database" "database" {
  project     = google_project.project.project_id
  name        = "(default)"
  location_id = "nam5"
  type        = "FIRESTORE_NATIVE"

  // New field
  point_in_time_recovery_enablement = "POINT_IN_TIME_RECOVERY_ENABLED"
}
```

In addition, the following attributes need to be returned:

```
google_firestore_database.database.version_retention_period
google_firestore_database.database.earliest_version_time
```

I've also seen the following attributes to be missing (would be nice if those could be added for completeness):
```
google_firestore_database.database.uid
google_firestore_database.database.update_time
```

### References

https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases#Database

**Comment by SarahFrench** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/8863
