### ISSUE TITLE
Firestore: Configuring Time-To-Live (TTL) policies

### ISSUE THREAD

**Issue by IchordeDionysos** [hashicorp/terraform-provider-google#15787]
Looking at the documentation for the TTL config it does not immediately get clear to me how to configure the TTL...
Please consider this issue as a nudge to improve the documentation of the resource.

I do see [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field#ttl_config) that 
> If set, this field is configured for TTL deletion

Does that mean this would enable TTL for the `someTimestamp` field?

```tf
resource "google_firestore_field" "timestamp" {
  project = "my-project-name"
  collection = "chatrooms_%{random_suffix}"
  field = "someTimestamp"

  ttl_config {}
}
```

I find the documentation especially confusing due to the following points:
1. In [this example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field#example-usage---firestore-field-basic), where this is NO timestamp field but the `ttl_config {}` is still there.

2. And in [this example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field#example-usage---firestore-field-timestamp) there is a comment above that says:
    > Disable all single field indexes for the timestamp property.
    
    But this only applies to the empty `index_config {}` not the empty `ttl_config {}`.

3. And the fact that the [`ttl_config` block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_field#nested_ttl_config) has no input values, and it's also unclear what state is/what values state can have!

I would propose to add an example like the following to the documentation:

---

# Example Usage - Firestore Field Time-To-Live (TTL)
```tf
resource "google_firestore_field" "time_to_live_policy" {
  project = "my-project-name"
  collection = "chatrooms_%{random_suffix}"
  field = "expiresAt"

  // Enables TTL with the field `expiresAt`. All documents will be deleted after the time in the `expiresAt` field has been reached.
  ttl_config {}
}
```

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/15781

**Comment by edwardmedia** [comment]
b/299900279

**Comment by IchordeDionysos** [comment]
@edwardmedia just a quick note, the labels says `service/filestore` instead of `service/firestore` 😊
