### ISSUE TITLE
google_redis_instance: Using a sharedvpc from different project throws 400 error

### ISSUE THREAD

**Issue by oed-pawlickf** [hashicorp/terraform-provider-google#15792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.7
on linux_amd64
```

```
Terraform provider: google 4.81.0
```

### Affected Resource(s)

* google_redis_instance

### Terraform Configuration Files

```tf
  redis_name     = "test-redis"
  memory_size_gb = 2

  project = "123456"

  redis_display_name = "GCP Redis Test"

  # Get your Locations here: https://cloud.google.com/compute/docs/regions-zones?hl=de
  tier = "BASIC"
  zone = "europe-west3-a" #Frankfurt

  #`redis_version` not provided, so latest supported version will be used.

  vpc_project_id     = [network-project]
  vpc                = [network-name]
  connection_mode    = "PRIVATE_SERVICE_ACCESS"
  secondary_ip_range = "auto"

  auth_enabled            = true
  transit_encryption_mode = "SERVER_AUTHENTICATION"

  read_replicas_mode = "READ_REPLICAS_DISABLED"
  replica_count      = 0
```

### Expected Behavior

The setup via GUI works with access to the shared VPC. This should also be possible via Terraform

### Actual Behavior

```
│ Error: Error creating Instance: googleapi: Error 400: authorized_network must exist in the same project as redis instance
│ com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: authorized_network must exist in the same project as redis instance
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value: projects/[network-project]/global/networks/[network-name]",
│         "field": "instance.authorized_network"
│       }
│     ]
│   }
│ ]
│ 
```

### Steps to Reproduce

1. `terraform apply`

b/300237834

**Comment by edwardmedia** [comment]
@oed-pawlickf can you share the debug log when you apply the config?
