### ISSUE TITLE
Allow Cloud Identity group membership lookup by alias or email

### ISSUE THREAD

**Issue by andrewesweet** [hashicorp/terraform-provider-google#15812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I want to find the members of a Cloud Identity group. I'm synchronising them from another directory service, so I'd like to use the identifiers from that source system e.g. a name ("Group Alias" in Cloud Identity speak) or email ("Group Email"), so "foo" or "foo@mycompany.com".

Unfortunately, the existing [`google_cloud_identity_group_memberships`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloud_identity_group_membership#group) datasource allows lookup by Group ID only ("groups/abcd1234"), a unique key per GCP organisation generated by Cloud Identity. The only way to discover this ID with this provider is to list _all groups in the org_ using [`google_cloud_identity_groups`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloud_identity_groups) and filter the result. For a large number of groups this is slow to execute. If you expect to frequently want to look this up, this is also a potential quota limit problem.

Ideally, I'd like `google_cloud_identity_group_membership` to allow one to specify a group alias, group email or group ID and Just Do The Right Thing (TM), as is the interface offered by the equivalent [googleworkspace provider functionality](https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs/data-sources/group_members#group_id). Alternatively, a datasource that exposes the [search API](https://cloud.google.com/identity/docs/reference/rest/v1/groups/search) or [lookup API](https://cloud.google.com/identity/docs/reference/rest/v1/groups/lookup) could be used to find the required group IDs and pass them into the existing data sources.

### New or Affected Resource(s)

* google_cloud_identity_group_memberships

### Potential Terraform Configuration

If expanding the set of identifiers accepted by the existing data source:
```tf
data "google_cloud_identity_group_memberships" "members" {
  group = "foo@mycompany.com"
}
```

If exposing the search API:
```tf
data "google_cloud_identity_groups_search" "search" {
  query = "groupKey == 'foo@mycompany.com'" # Or "display_name == 'foo'" for alias lookup
  view = "FULL" # Or BASIC
}

data "google_cloud_identity_group_memberships" "members" {
  group = one(data.google_cloud_identity_groups_search.groups).name # Best to do some validation rather than take the first result in
}
```

If exposing the lookup API:
```tf
data "google_cloud_identity_group_lookup" "lookup" {
  id = "foo@mycompany.com"
  namespace = null # The default value
}

data "google_cloud_identity_group_memberships" "members" {
  group = data.google_cloud_identity_group_lookup.name
}
```

### References
* [groups.lookup API](https://cloud.google.com/identity/docs/reference/rest/v1/groups/lookup#google.apps.cloudidentity.groups.v1.GroupsService.LookupGroupName)
* [groups.search API](https://cloud.google.com/identity/docs/reference/rest/v1/groups/search)
* b/300098791

**Comment by melinath** [comment]
Potentially related: https://github.com/hashicorp/terraform-provider-google/issues/8255

**Comment by rileykarson** [comment]
Discussed in triage: We prefer the second option of implementing dedicated datasource(s) for the search/lookup APIs
