### ISSUE TITLE
google_logging_folder_settings / google_logging_organization_settings new resources

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#15827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Would be nice to be able to update folder / organisation logging settings within terraform.

API: 
https://cloud.google.com/logging/docs/reference/v2/rest/v2/organizations/updateSettings
https://cloud.google.com/logging/docs/reference/v2/rest/v2/folders/updateSettings

### New or Affected Resource(s)

* google_logging_folder_settings 
* google_logging_organization_settings

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_logging_folder_settings" "settings" {
  folder_id = "folders/1234567"
  settings {
    kms_key_name = "projects/my-project/locations/us-central1/keyRings/my-ring/cryptoKeys/my-key"
    storage_location = "europe-west2"
    disable_default_sink = false
  }
}
```

### References

* #0000

b/301065890

**Comment by melinath** [comment]
This would be a settings-style fine-grained resource; it doesn't look like create / delete are supported in the API.
