### ISSUE TITLE
BigQuery Reservations: current_slots is added to Terraform state, resulting in Error 400: current_slots from Autoscale must not be set.

### ISSUE THREAD

**Issue by jonnydford** [hashicorp/terraform-provider-google#15826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.7

### Affected Resource(s)

* google_bigquery_reservation

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

Module usage
```tf
module "warehouse-reservation" {
  source = "../../../terraform-bigquery-editions/modules/reservations/"

  reservation_name    = "my-reservation"
  reservation_edition = "ENTERPRISE"
  base_slots          = 10000
  max_slots           = 11000
}
```

Module - main.tf
```tf
resource "google_bigquery_reservation" "reservation" {
    name              = var.reservation_name
    project           = var.bigquery_admin_project
    location          = "EU"
    slot_capacity     = var.base_slots
    edition           = var.reservation_edition
    ignore_idle_slots = var.ignore_idle_slots
    concurrency       = var.concurrency
    autoscale {
      max_slots = var.max_slots
    }
}
```

Module - vars.tf
```tf
variable "bigquery_admin_project" {
  type = string
  default = "my-bq-admin-project"
  description = "Name of BigQuery Admin project to create the reservation in."
}

variable "reservation_edition" {
  type = string
  default = "ENTERPRISE"
  description = "Edition of BigQuery Reservation to create. Options are STANDARD, ENTERPRISE or ENTERPRISE_PLUS"
}

variable "reservation_name" {
  type = string
  description = "Name of the Reservation to create"
}

variable "base_slots" {
  type = number
  default = 0
  description = "Base slot capacity."
}

variable "ignore_idle_slots" {
  type    = bool
  default = false
  description = "Whether or not to ignore idle slots from other reservations."
}

variable "max_slots" {
  type = number
  default = 400
  description = "Maximum number of slots to autoscale."
}

variable "concurrency" {
  type = number
  default = 0
  description = "Number of concurrent queries. Default '0' implies unlimited concurrent queries."
}
```

Terraform state file:
``` json
    {
      "module": "my-reservation",
      "mode": "managed",
      "type": "google_bigquery_reservation",
      "name": "reservation",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "autoscale": [
              {
                "current_slots": 1000,
                "max_slots": 11000
              }
            ],
            "concurrency": 0,
            "edition": "ENTERPRISE",
            "id": "projects/my-bq-admin-project/locations/EU/reservations/my-reservation",
            "ignore_idle_slots": false,
            "location": "EU",
            "multi_region_auxiliary": false,
            "name": "my-reservation",
            "project": "my-bq-admin-project",
            "slot_capacity": 10000,
            "timeouts": null
          },
          "sensitive_attributes": [],
          "private": ""
        }
      ]
    }
```

### Debug Output

```
│ Error: Error updating Reservation "projects/my-bq-admin-project/locations/EU/reservations/my-reservation": googleapi: Error 400: current_slots from Autoscale must not be set.
```

### Expected Behavior

`current_slots` would not be added to the Terraform state file, or it would be removed from the request sent to the Google APIs

### Actual Behavior

Error 400 returned as `current_slots` is being sent in the message body to the API

### Steps to Reproduce

1. `terraform apply`

I haven't quite figured out the steps to reproduce yet, since I have tens of reservations and only one in giving this error, but I believe it to be either an import of the resource, or a change in the number of baseline or max slots causing the issue.

This resource is the only one with a base_slots allocated, so it could be that.

### References

* #0000

b/300616656

**Comment by garsir** [comment]
Is there any update on whether this issue will be looked into?

**Comment by ScottSuarez** [comment]
I'm working on a pull request now

**Comment by yu-iskw** [comment]
I have the same issue.

**Comment by hatchpdnc** [comment]
just ran into this bug myself

**Comment by wj-chen** [comment]
The underlying PR https://github.com/GoogleCloudPlatform/magic-modules/pull/9219 is work-in-progress.

**Comment by c2thorn** [comment]
This issue could be fixed for this resource specifically by adding an encoder or update_encoder that just removes the unwanted fields.

**Comment by wj-chen** [comment]
Also currently exploring the option to update the API behavior to ignore output-only fields in the request.

**Comment by wj-chen** [comment]
> Also currently exploring the option to update the API behavior to ignore output-only fields in the request.

A change was made to the API to no longer throw the validation exception and just ignore the `current_slots` field in the request. It should be in effect approximately one week from now if the underlying release goes well, and I'll update here once again once it's ready.

**Comment by wj-chen** [comment]
Backend fix has been rolled out (more details in the buganizer issue). @trodge can you help me close this issue?
