### ISSUE TITLE
Missing data source `google_compute_reservation`

### ISSUE THREAD

**Issue by mr0re1** [hashicorp/terraform-provider-google#15829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The data source to inspect compute reservations is missing, though corresponding resource does [exist](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_reservation).

It will be nice to have `google_compute_reservation` data source.

### New or Affected Resource(s)

* google_compute_reservation

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

b/305377802

**Comment by SarahFrench** [comment]
Note for whoever picks this up: the equivalent resource for this datasource is [generated with MMv1](https://github.com/hashicorp/terraform-provider-google/blob/ff751a8633de20d822b5e52bbd9f3d6f75c51a13/google/services/compute/resource_compute_reservation.go#L6)
