### ISSUE TITLE
The firebaserules_release should have a db name property

### ISSUE THREAD

**Issue by mo-elsherif** [hashicorp/terraform-provider-google#15838]
The firebaserules_release resource applies only rules to the `(default)` db. We would like to have it apply rules to the other dbs as well. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We have multiple firebase dbs instances in our project and we want to apply the rule set to one of them not the  `(default)` db.

Currently, we do not find any workarround, but to set the rules manually and would be a great help to us to have it in code.

### New or Affected Resource(s)

* google_firebaserules_release

### Potential Terraform Configuration

```tf
resource "google_firebaserules_release" "primary" {
  name         = "cloud.firestore"
  ruleset_name = "projects/my-project-name/rulesets/${google_firebaserules_ruleset.firestore.name}"
  project      = "my-project-name"

  db           = "second_db"
 
  lifecycle {
    replace_triggered_by = [
      google_firebaserules_ruleset.firestore
    ]
  }
}
```

b/301066222

**Comment by rainshen49** [comment]
@mo-elsherif According to https://firebase.google.com/docs/rules/manage-deploy#release_deploy_a_ruleset, setting the name to `"cloud.firestore/second_db"` should work for you for now. There is some additional work needed. I'll update the issue once I figure those out with the team.

```hcl
resource "google_firebaserules_release" "primary" {
  --> name         = "cloud.firestore/second_db"
  ruleset_name = "projects/my-project-name/rulesets/${google_firebaserules_ruleset.firestore.name}"
  project      = "my-project-name"
 
  lifecycle {
    replace_triggered_by = [
      google_firebaserules_ruleset.firestore
    ]
  }
}
```

**Comment by rainshen49** [comment]
See https://github.com/hashicorp/terraform-provider-google/issues/16324

**Comment by dinvlad** [comment]
This issue with setting the name to `"cloud.firestore/second_db"` is that Terraform then runs into a conflict with the existing resource of the same name, which is seemingly somehow created without Terraform. I'm not sure how to interpret that.

**Comment by serpro69** [comment]
A new firestore database (`FIRESTORE_NATIVE` type at least) will have a pre-created default ruleset that prohibits all connections:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} { 
      allow read, write: if false; 
    } 
  } 
}
```

Setting `cloud.firestore/${name}` causes an error as mentioned above by @dinvlad , because the rules are managed outside of terraform.

Are there any workarounds for this currently, @rainshen49 ?

**Comment by YehorPytomets** [comment]
@serpro69, not clear how to get security rules working for a non-default native Firestore database when I've already deployed rules via Firebase rules editor.

**Comment by serpro69** [comment]
@YehorPytomets 

In addition to adding the `google_firebaserules_release` resource, add an import block like this:

```tf
import {
  id = "projects/{{project}}/releases/{{name}}"
  to = google_firebaserules_release.default
}
```

Then apply your changes. It will import configuration from firebase into your resource definition. From there you can just remove the import block, update the resource config and mange it normally via terraform.

**Comment by YehorPytomets** [comment]
@serpro69

Unfortunately, it didn't work for me. The terraform aborts with the message:

```
An import block was detected in "module.firestore-database". Import blocks are only allowed in the root module.
```

So I manually created my own `terraform-data` resource which triggers the `firebase deploy` command.

But anyway, thank your for your help!

**Comment by serpro69** [comment]
@YehorPytomets , you need to put the `import` block itself in the root module, yes. But you can import into non-root resources/modules via `to` argument. So my `google_firebaserules_release` is actually part of an inner module, and that works just fine.
