### ISSUE TITLE
❌ google_cloudfunctions_function / source_repository not working

### ISSUE THREAD

**Issue by gmorales254** [hashicorp/terraform-provider-google#15846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.6

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_cloudfunctions_function" "function" {
  provider = google
  name        = "api"
  description = "My entry function"
  runtime     = "nodejs16"
  project = var.google_project_id
  available_memory_mb   = 128
  trigger_http          = true
  entry_point           = "api"
  source_repository = {
    url ="https://source.cloud.google.com/xxxxx/xxxxxxx/+/main:xxxx/"
    }
}
```

### Debug Output

│ Error: Unsupported argument
│
│   on main.tf line 137, in resource "google_cloudfunctions_function" "function":
│  137:   source_repository = {
│
│ An argument named "source_repository" is not expected here. Did you
│ mean to define a block of type "source_repository"?

### Expected Behavior

Should take my repository branch...
### Actual Behavior

Error!

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing 

### References

* #0000

b/303616201

**Comment by gmorales254** [comment]
@edwardmedia If you need some extra info, let me know and thanks!

**Comment by KAKAinGoog** [comment]
Hi!

If you remove the "=" after `source_repository`, it should work. i.e. go with `source_repository { url=xxx } `. 

More context can be found here: https://github.com/hashicorp/terraform-provider-aws/issues/9130#issuecomment-505659705

**Comment by gmorales254** [comment]
Thanks! works.
