### ISSUE TITLE
clash between TF and Google applying changes on Cloud SQL master and failover replica

### ISSUE THREAD

**Issue by czka** [hashicorp/terraform-provider-google#1586]
```
$ terraform --version
Terraform v0.11.7
+ provider.google v1.10.0
```
A value update on a Cloud SQL flag on master (`enviro-shard02-v2`) and failover replica (`enviro-shard02-v2-failover`) triggers a TF diff for both. Then the change is applied on master. Next Google replicates that new setting immediately on the replica.

Problem is that it seems like TF tries to apply the update on the replica afterwards anyway, which results in `403: Operation failed because another operation was already in progress`:
 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_sql_database_instance.enviro-shard02-v2
      settings.0.database_flags.#:       "2" => "1"
      settings.0.database_flags.1.name:  "max_allowed_packet" => ""
      settings.0.database_flags.1.value: "41943040" => ""
      settings.0.maintenance_window.#:   "1" => "0"

  ~ google_sql_database_instance.enviro-shard02-v2-failover
      settings.0.database_flags.#:       "2" => "1"
      settings.0.database_flags.1.name:  "max_allowed_packet" => ""
      settings.0.database_flags.1.value: "41943040" => ""


Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_sql_database_instance.enviro-shard02-v2-failover: Modifying... (ID: enviro-shard02-v2-failover)
  settings.0.database_flags.#:       "2" => "1"
  settings.0.database_flags.1.name:  "max_allowed_packet" => ""
  settings.0.database_flags.1.value: "41943040" => ""
google_sql_database_instance.enviro-shard02-v2: Modifying... (ID: enviro-shard02-v2)
  settings.0.database_flags.#:       "2" => "1"
  settings.0.database_flags.1.name:  "max_allowed_packet" => ""
  settings.0.database_flags.1.value: "41943040" => ""
  settings.0.maintenance_window.#:   "1" => "0"
google_sql_database_instance.enviro-shard02-v2: Still modifying... (ID: enviro-shard02-v2, 10s elapsed)
google_sql_database_instance.enviro-shard02-v2: Modifications complete after 17s (ID: enviro-shard02-v2)

Error: Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.enviro-shard02-v2-failover: 1 error(s) occurred:

* google_sql_database_instance.enviro-shard02-v2-failover: Error, failed to update instance enviro-shard02-v2-failover: googleapi: Error 403: Operation failed because another operation was already in progress., operationInProgress
```

**Comment by morgante** [comment]
Could you ignore_changes to the database_flags property on the replica? https://www.terraform.io/docs/configuration/resources.html#ignore_changes

**Comment by czka** [comment]
Haven't tried that. Still, that would be a workaround, right? And the original issue is that Google TF provider should handle the interference of Google-driven Cloud SQL master -> replica flag updates and TF-driven flag updates gracefully.

**Comment by morgante** [comment]
Yes, that would be a workaround. That being said, I'm not sure how Terraform could best handle this since ultimately Terraform isn't really responsible for out-of-band changes to infrastructure and doesn't have visibility into them.

**Comment by rosbo** [comment]
I concur with @morgante. Terraform doesn't have visibility into these out-of-band changes. This "workaround" is probably the best solution.

Let us know if it works and we can add an example to our documentation on best practices around configuring sql replicas.

**Comment by czka** [comment]
Does TF realize that a replica depends on master in a way that a flag change on master will trigger a respective change on replica? If it does, could it put its actions in order to avoid clashes like this one? Eg. modify replica settings 1st, wait till it completes, then deal with master? Just thinking loud. Or maybe it's just pointless to set flags with TF on replica at all nad better let Google handle it, assuming that whatever flags master has so has the replica.

I don't have a setup to re-test this scenario anymore. An example in the docs would help.

**Comment by gries** [comment]
Hi,
This issue is still happening so for anyone that needs it here's the workarround that currently works for me.
```
resource "google_sql_database_instance" "replica" {
  name             = "replica-server"
  project          = "${var.project}"
  region           = "${var.region}"
  database_version = "${var.database_version}"

  master_instance_name = "my-master-instance"

  settings {
    tier            = "${var.tier}"
    disk_autoresize = "${var.autoresize}"
    database_flags  = "${var.db_flags}"

    ip_configuration = {
      authorized_networks = ["${var.authorized_networks}"]
    }
  }

  replica_configuration = ["${var.replica_configuration}"]

  // ignore changes to settings as they will be synced when changing the master
  lifecycle {
    ignore_changes = [
      "settings"
    ]
  }
}
```
The important part is the `ignore_changes` section.
how/why is explained in the comments above.

**Comment by upodroid** [comment]
@danawillow Can we close this out?

- Using Failover Replicas is deprecated now in favour setting avalability_type to REGIONAL https://cloud.google.com/sql/docs/mysql/high-availability#legacy_mysql_high_availability_option
https://cloud.google.com/sql/docs/mysql/configure-ha#ha-create
- You can't create Failover replicas after Q1 2021
- It offers poorer performance compared to the new HA option that is based on Regional PDs

**Comment by danawillow** [comment]
Seems reasonable. If anyone subscribed to this issue disagrees, comment and let me know why.
