### ISSUE TITLE
Changing from the deprecated secret replication syntax to the new replication syntax forces replacement of the secret

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#15885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
terraform version 1.5.2
Google provider version 4.83

### Affected Resource(s)

google_secret_manager_secret

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret"
  replication {
    automatic = true
  }
}
```

### Expected Behavior

No changes, should be equivalent 

### Actual Behavior

Every secret will be destroyed and recreated.  

 replication {
          - automatic = true -> null # forces replacement

          + auto { # forces replacement
            }
        }

### Steps to Reproduce

1. `terraform apply`
2. change  replication {
    automatic = true
  }
  to 
  replication {
    auto {}
  }
3. `terraform apply`

### Important Factoids

caused by https://github.com/hashicorp/terraform-provider-google/pull/15793

b/301066246

**Comment by rileykarson** [comment]
@c2thorn assigning as a 5.0.0 upgrade related issue, in case you have a plan for how to track these already

**Comment by c2thorn** [comment]
Created https://github.com/GoogleCloudPlatform/magic-modules/pull/9030 to prevent force replacement when replacing `replication.automatic` with `replication.auto`.
Targeting the 4.84 release.
