### ISSUE TITLE
google_gke_hub_membership global location only?

### ISSUE THREAD

**Issue by FeltlP** [hashicorp/terraform-provider-google#15882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When using the TF provider (google_gke_hub_membership) it seems that the location is fixed with global and no regional setup is possible like through the gc.loud CLI

### New or Affected Resource(s)

google_gke_hub_membership

### Potential Terraform Configuration

```tf
resource "google_gke_hub_membership" "gke_cluster" {
  project = "fleet_project_id"
  membership_id = "gke_cluster"
  location = "europe-west4"

  endpoint {
    gke_cluster {
      resource_link = "//container.googleapis.com/${data.google_container_cluster. gke_cluster.id}"
    }
  }
}
```

b/301066298

**Comment by melinath** [comment]
We can add a location field with default: global.

**Comment by sahsagar-google** [comment]
I am working on this.

**Comment by FeltlP** [comment]
@melinath & @sahsagar-google, thank you for picking this up that quickly!
If there is any ETA, please let me know, happy to test & give feedback if needed.

**Comment by FeltlP** [comment]
Has been added with version 5.1.0 of the provider, thx a lot!
