### ISSUE TITLE
No way to create DataProc cluster with the local SSD with NVMe interface

### ISSUE THREAD

**Issue by mesh-99** [hashicorp/terraform-provider-google#15915]
Error: Error waiting for creating Dataproc cluster: Error code 3, message: NVMe interface is required for local SSD(s) attached to Graphics Optimized G2 instances.

**Comment by mesh-99** [comment]
I need to create dataproc cluster with GPUs
So I select the Machine Type g2-standard-4 which is Nvidia L4 (4 vCPU, 2 core, 16 GB memory)
I am required to have a local SSD with NVMe interface, I set the num_local_ssds    = 1 but there is no way to specify interface
cluster_config {
    master_config {
      num_instances = 1
      machine_type  = "g2-standard-4"
      disk_config {
        boot_disk_size_gb = 30
        num_local_ssds    = 1
        # local_ssd_interface = "NVME" <<< Need something like this which is missing.
      }
    }
So when applied get the following error
Error: Error waiting for creating Dataproc cluster: Error code 3, message: NVMe interface is required for local SSD(s) attached to Graphics Optimized G2 instances.

**Comment by edwardmedia** [comment]
@mesh-99 can you share your config and debug log? Not sure if this is allowed by the api. Are you able to create it via other means?

**Comment by mesh-99** [comment]
Please find below the official documentation link from google to create dataproc cluster with local ssd.
https://cloud.google.com/dataproc/docs/concepts/compute/dataproc-local-ssds

gcloud dataproc clusters create cluster-name \
    --region=region \
    --num-master-local-ssds=1 \
    --num-worker-local-ssds=1 \
    --num-secondary-worker-local-ssds=1 \
    --master-local-ssd-interface=NVME \
    --worker-local-ssd-interface=NVME \
    --secondary-worker-local-ssd-interface=NVME \
    ... other args ...

You see the gcloud command above there is a way to set the interface type for local SSD.
There is no way to do it via terraform.

**Comment by edwardmedia** [comment]
@mesh-99 it is not supported via terraform yet. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) to request
