### ISSUE TITLE
Removing schema_settings from google_pubsub_topic does not trigger update

### ISSUE THREAD

**Issue by GustenT** [hashicorp/terraform-provider-google#15925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```terraform gustor$ terraform -v
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.83.0
```

### Affected Resource(s)

* google_pubsub_topic

### Terraform Configuration Files

Before
```tf
resource "google_pubsub_topic" "topic" {
  project      = google_project.project.project_id
  name         = "topic"

  schema_settings {
    schema   = google_pubsub_schema.schema.id
    encoding = "JSON"
  }

  depends_on = [google_pubsub_schema.schema]
}

resource "google_pubsub_schema" "schema" {
  project    = google_project.project.project_id
  name       = "schema"
  type       = "PROTOCOL_BUFFER"
  definition = "syntax = \"proto3\";\nmessage Results {\nstring message_request = 1;\nstring message_response = 2;\nstring timestamp_request = 3;\nstring timestamp_response = 4;\n}"
}
```

After
```tf
resource "google_pubsub_topic" "topic" {
  project      = google_project.project.project_id
  name         = "topic"

  depends_on = [google_pubsub_schema.schema]
}

resource "google_pubsub_schema" "schema" {
  project    = google_project.project.project_id
  name       = "schema"
  type       = "PROTOCOL_BUFFER"
  definition = "syntax = \"proto3\";\nmessage Results {\nstring message_request = 1;\nstring message_response = 2;\nstring timestamp_request = 3;\nstring timestamp_response = 4;\n}"
}
```

### Expected Behavior

The expected behaviour is that terraform would pick up on the removal of schema_settings and update the topic and remove the schema association from the topic.

### Actual Behavior

No changes detected.

### Steps to Reproduce

1. Create a google_pubsub_schema and a google_pubsub_topic with a schema_setting (terraform apply)
2. Remove schema_setting from google_pubsub_topic resource (terraform apply)

b/301582871

**Comment by kamalaboulhosn** [comment]
The fix for this would be considered a breaking change. Therefore, it has to wait for next year's 6.0 release.

**Comment by kamalaboulhosn** [comment]
The fix has been submitted as part of the next major release, which is planned for August 2024.
