### ISSUE TITLE
not able to modify metadata for existing object in gcp storage bucket via terraform

### ISSUE THREAD

**Issue by sachinmane1983** [hashicorp/terraform-provider-google#15943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@sachinmane1983 [metadata](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object#metadata) seems supported. What error did you get? Can you share the debug log?

**Comment by sachinmane1983** [comment]
> @sachinmane1983 [metadata](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object#metadata) seems supported. What error did you get? Can you share the debug log?

i want to set Cache-Control" = "no-store" for all existing objects in GCP storage bucket

resource "google_storage_object" "update_cache_control" {
  for_each = { for key, _ in data.google_storage_bucket_object.all_objects : key => key }
  name     = each.key
  bucket   = var.bucket_name

  content = null # Set content to null to avoid modifying the object's content

  metadata = {
    cache-control = "no-store"
  }
}
Error: Invalid resource type
│
│   on terraform-modules/gcp-hosted-bucket/main.tf line 195, in resource "google_storage_object" "update_cache_control":
│  195: resource "google_storage_object" "update_cache_control" {
│
│ The provider hashicorp/google does not support resource type "google_storage_object".

**Comment by edwardmedia** [comment]
@sachinmane1983 the [feature](https://github.com/hashicorp/terraform-provider-google/commit/122a5a4ec279c5d7ec4344f9d502701e0a391e51) was added 2 years ago.  Can you share the debug log?

What resource were you using?

```
google_storage_object. vs google_storage_bucket_object 
```

**Comment by edwardmedia** [comment]
closing assuming it is no longer an issue
