### ISSUE TITLE
GKE resources recreated on every `terraform apply` without any configuration changes

### ISSUE THREAD

**Issue by dkargatzis** [hashicorp/terraform-provider-google#15950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.7

provider.google v4.83.0

### Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Terraform Configuration Files

```tf
// Create a Google Compute VPC Network

resource "google_compute_network" "vpc_network" {
  name    = var.vpc_name
  project = var.project_id

  auto_create_subnetworks                   = false
  network_firewall_policy_enforcement_order = "AFTER_CLASSIC_FIREWALL"
}

// Define subnetworks within the VPC Network
resource "google_compute_subnetwork" "subnetwork" {
  count         = length(var.regions)
  name          = "${var.vpc_name}-subnet-${var.regions[count.index]}"
  ip_cidr_range = var.ip_cidr_range[count.index]
  region        = var.regions[count.index]
  network       = google_compute_network.vpc_network.self_link

  secondary_ip_range {
    range_name    = "k8s-pod-range"
    ip_cidr_range = "10.2.0.0/16"
  }

  secondary_ip_range {
    range_name    = "k8s-svc-range"
    ip_cidr_range = "10.3.0.0/16"
  }

  log_config {
    aggregation_interval = "INTERVAL_10_MIN"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }

  private_ip_google_access = true
  #  private_ipv6_google_access = "ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE" // Changed from "DISABLE_GOOGLE_ACCESS
}

// Define a firewall rule for the VPC Network
resource "google_compute_firewall" "firewall" {
  name    = "${var.vpc_name}-firewall"
  network = google_compute_network.vpc_network.self_link

  allow {
    protocol = "tcp"
    ports    = ["80"]
  }

  source_ranges = [
    "130.211.0.0/22",
    "35.191.0.0/16"
  ]
}

# Define a Google Cloud router for each subnetwork
resource "google_compute_router" "cloud_nat_router" {
  # Create one router for each subnetwork
  count   = length(google_compute_subnetwork.subnetwork)
  name    = "cloud-nat-router-${google_compute_subnetwork.subnetwork[count.index].name}"
  region  = google_compute_subnetwork.subnetwork[count.index].region
  network = google_compute_network.vpc_network.self_link

  # Define BGP settings (note that ASN is hard-coded here)
  bgp {
    asn = 64514
  }
}

# Define a NAT configuration for each router
resource "google_compute_router_nat" "nat" {
  # Create one NAT config for each router
  count  = length(google_compute_subnetwork.subnetwork)
  name   = google_compute_router.cloud_nat_router[count.index].name
  router = google_compute_router.cloud_nat_router[count.index].name
  region = google_compute_router.cloud_nat_router[count.index].region

  # Automatically allocate NAT IPs
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"

  # Log configuration (logging is disabled, only errors are logged)
  log_config {
    enable = false
    filter = "ERRORS_ONLY"
  }
}

// Output variables for the VPC Network module

output "vpc_network" {
  value       = google_compute_network.vpc_network.self_link
  description = "The self-link of the created VPC network."
}

output "vpc_network_name" {
  value       = google_compute_network.vpc_network.name
  description = "The name of the created VPC network."
}

output "subnetworks_name" {
  value       = google_compute_subnetwork.subnetwork[*].name
  description = "The self-links of the created subnetworks within the VPC network."
}

// Create a Google Container Cluster (GKE) in the specified VPC

resource "google_container_cluster" "cluster" {
  name               = var.cluster_name
  project            = var.project_id
  location           = var.location
  min_master_version = var.master_version

  resource_labels = {
    "provider" = "gcp"
    "tier"     = "free"
  }

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1

  release_channel {
    channel = "STABLE"
  }

  network    = var.network
  subnetwork = var.subnetwork

#  enable_l4_ilb_subsetting = false

  binary_authorization {
    evaluation_mode = "PROJECT_SINGLETON_POLICY_ENFORCE"
  }

  master_auth {
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  default_max_pods_per_node = 16

  ip_allocation_policy {
    cluster_secondary_range_name  = "k8s-pod-range"
    services_secondary_range_name = "k8s-svc-range"
  }

  network_policy {
    enabled  = true
    provider = "PROVIDER_UNSPECIFIED" // Consider setting the value to "CALICO"
  }

  enable_intranode_visibility = true

  private_cluster_config {
    enable_private_nodes    = false
    enable_private_endpoint = false
    master_ipv4_cidr_block  = var.master_ipv4_cidr_block
  }

  workload_identity_config {
    workload_pool = "${var.project_id}.svc.id.goog"
  }

  node_config {
    shielded_instance_config {
      enable_integrity_monitoring = true
      enable_secure_boot          = true
    }

    workload_metadata_config {
      mode = "GCE_METADATA"
    }
  }

  depends_on = [google_project_service.compute, google_project_service.container]
}
```

### Debug Output

Note: No errors are shown in the output even with the debug flag activated.

### Panic Output

There was no crash or panic produced during the `terraform apply` process.

### Expected Behavior

Terraform should recognize that no changes have been made and should not attempt to recreate the GKE resources.

### Actual Behavior

Terraform attempts to recreate the GKE resources every time, even without any changes to the configuration.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* I've experimented with older versions of the "hashicorp/google" provider, but the issue persists across these versions.
* The behavior remains consistent even after I made significant modifications to the GKE resources' configuration. Specifically:
  * I removed the resource_labels block based on references suggesting this might be a potential culprit.
  * I also excluded the `node_config`, `network_policy` and `ip_allocation_policy` configuration blocks, as there were other GitHub issues indicating potential problems with these configurations.
  * Instead of using the VPC's `self_link`, I input the VPC name directly to the GKE module. This change was influenced by another issue that hinted at the `self_link` as a possible source of the problem.
* There might still be underlying dependencies or intricacies within the VPC or other associated configurations that could be causing this unexpected behavior.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/11022
* https://github.com/hashicorp/terraform-provider-google/issues/2115

b/301736448

**Comment by csjingzhang** [comment]
For the GKE resources recreated, do you mean all the GKE related resources including cluster and networks, or it is a subset?

**Comment by dkargatzis** [comment]
Control plane and node pools are being recreated on every apply - VPC and other resources are not affected. I have also upgraded the "hashicorp/google" provideer to the latest version (v4.84.0) and still the same.

**Comment by edwardmedia** [comment]
@dkargatzis can you share the debug log for your original apply and subsequent apply?

**Comment by dkargatzis** [comment]
I've applied the Terraform configuration twice as you requested and uploaded the related log files to a Google Storage bucket. Here are the links:

1. [Original apply debug log](https://storage.googleapis.com/to-be-used-for-stackoverflow/terraform_first_apply.log)
2. [Subsequent apply debug log](https://storage.googleapis.com/to-be-used-for-stackoverflow/terraform_second_apply.log)

After the subsequent apply, I noticed an unexpected behavior: none of the node pools were created. FYI, I've tested this config on several operating systems (Windows, Ubuntu and GCP Active Cloud shell), and the issue remains consistent.

**Comment by dkargatzis** [comment]
@edwardmedia any update on this one?

**Comment by shervinkh** [comment]
I just investigated the logs. Here's what's happening:

1. A cluster is defined with a `node_config` object in Terraform and gets created once you run `terraform apply`.
2. You create a "NodePool" with `nodepool.config.preemptible = true` (based on the logs). This has an unwanted side-effect of setting `cluster.node_config = nodepool.config` (and hence setting `cluster.node_config.preemptible = true`).
3. When you run `terraform apply` again, it sees `cluster.node_config.preemptible` is unset in your TF file and defaults to false. This field is defined so that any change in it forces destruction and recreation of the cluster (https://github.com/hashicorp/terraform-provider-google/blob/117cf22b86d4bf4544c9fd51afdff9cadfa49786/google/services/container/node_config.go#L292-L298). So, Terraform plans  a destruction for your cluster.

On line 3824 of the "Subsequent apply debug log" you see `           ~ preemptible       = true -> false # forces replacement` which confirms this.

The unwanted side effect in step 2 in GKE side seems to be a bug. But to be fair the `cluster.node_config` field has been marked as deprecated in the GKE API (http://cloud/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster). That might be why it's not working as expected. You should avoid setting a `node_config` on your cluster resource and instead, use `cluster.node_pools[].config` to specify the same config.

**Comment by shervinkh** [comment]
Can you confirm whether removing `node_config` solves your issue?

**Comment by shervinkh** [comment]
I also see `+ master_ipv4_cidr_block  = "10.2.0.0/28" # forces replacement` in the logs. Seems like `private_cluster_config.master_ipv4_cidr_block` is not successfully being set on the cluster and this also forces destruction of the cluster.

If removing `node_config` doesn't fix the issue, That one might be it.

**Comment by shervinkh** [comment]
According to the logic here (https://github.com/hashicorp/terraform-provider-google/blob/cb14f80f49ab25656f3edfc65f2c50f255be38d6/google/services/container/resource_container_cluster.go#L5602-L5604), your config (using `enable_private_nodes = false` with `master_ipv4_cidr_block  = "10.2.0.0/28"`) is an invalid configuration. I'm not sure why you don't get a validation error from Terraform.

**Comment by shervinkh** [comment]
Considering the suppress function here (https://github.com/hashicorp/terraform-provider-google/blob/cb14f80f49ab25656f3edfc65f2c50f255be38d6/google/services/container/resource_container_cluster.go#L5575-L5596), the `master_ipv4_cidr_block` is likely ignore and your issue is most likely the `node_config`.

**Comment by dkargatzis** [comment]
Thanks for investigating my issue! 

I have defined the `preemptible` attribute (its value was unspecified until now) with its value set to false in the cluster's `node_config` block, but the behavior remained the same. I also removed the `node_config` entirely from the `google_container_cluster` resource, but that did not change the behavior either.

Removing the `master_ipv4_cidr_block` from the `private_cluster_config` block resulted in the expected behavior. Keeping the `master_ipv4_cidr_block` as it is and setting `enable_private_nodes` to true resulted in the following error

```bash
Error waiting for creating GKE cluster: The given master_ipv4_cidr 10.2.0.0/28 overlaps with an existing network 10.2.0.0/16.
```

**Comment by shervinkh** [comment]
I see. So, just removing `master_ipv4_cidr_block` fixed the issue? or removing `master_ipv4_cidr_block` + removing `node_config`?

According to the docs for `master_ipv4_cidr_block`, 
```
The IP range in CIDR notation to use for the hosted master network. This range will be used for assigning internal IP addresses to the master or set of masters, as well as the ILB VIP. This range must not overlap with any other ranges in use within the cluster's network.
```
So that error means the `10.2.0.0/28` range you specify conflicts with another range. You can use GCP Web UI to investigate what ranges are in-use in your cluster's network.

**Comment by dkargatzis** [comment]
Just removing the `master_ipv4_cidr_block` fixed the issue. Your support is highly appreciated!
