### ISSUE TITLE
Error creating Index: googleapi: Error 400: contentsDeltaUri is required but missing from Index metadata.

### ISSUE THREAD

**Issue by shotarok** [hashicorp/terraform-provider-google#15962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* google-beta: 4.76.0

### Affected Resource(s)

* google_vertex_ai_index

### Terraform Configuration Files

```tf
resource "google_vertex_ai_index" "index" {
  provider     = google-beta
  project      = "xxx"
  region       = "us-west1"
  display_name = "xxx"
  description  = "Index with embeddings for xxx"

  index_update_method = "STREAM_UPDATE"

  metadata {
    config {
      dimensions                  = 384
      distance_measure_type       = "DOT_PRODUCT_DISTANCE"
      approximate_neighbors_count = 50
      feature_norm_type           = "NONE"
      shard_size                  = "SHARD_SIZE_SMALL"

      algorithm_config {
        tree_ah_config {
          leaf_node_embedding_count    = 10000
          leaf_nodes_to_search_percent = 10
        }
      }
    }
  }
}
```

### Expected Behavior

terraform plan detects the missing required field: `metadata.contents_delta_uri`

### Actual Behavior

terraform plan succeeded, and terraform apply failed with the following error

```
Error: Error creating Index: googleapi: Error 400: contentsDeltaUri is required but missing from Index metadata.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@shotarok can you share the debug log?

**Comment by shotarok** [comment]
@edwardmedia Here is the debug logs: [debug.log](https://github.com/hashicorp/terraform-provider-google/files/12707740/debug.log). Please note that I tweaked it to hide the project name manually.
