### ISSUE TITLE
google_compute_managed_ssl_certificate can't be updated without manual delete first, when in use by LB

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#15966]
### Community Note

When a Global Application LB (previously known as Global HTTP(S) LB)  is created along with a Google managed SSL/TLS cert and then later if you want to update the domains of the managed cert it will not be possible with terraform without manually deleting the managed cert (after either manually updating the HTTPS target proxy to no longer use that managed cert or else deleting the HTTPS target proxy as well).

### Terraform Version

Terraform v1.4.5
on darwin_arm64

- Using previously-installed hashicorp/google v4.83.0
- Using previously-installed hashicorp/google-beta v4.83.0

### Affected Resource(s)

google_compute_managed_ssl_certificate
google_compute_target_https_proxy

### Terraform Configuration Files

This is visible when using the https://github.com/terraform-google-modules/terraform-google-lb-http module (or creating/using the resources directly)

```tf
# Copy-paste your Terraform configurations here.

see  https://github.com/terraform-google-modules/terraform-google-lb-http

### Debug Output

│ Error: Error creating ManagedSslCertificate: googleapi: Error 409: The resource 'projects/cbdc-out-of-scope-p2lxzf0qacu/global/sslCertificates/xrplai-lb-sandbox-prod-cert' already exists, alreadyExists
│ 
│   with module.lb.google_compute_managed_ssl_certificate.default[0],
│   on .terraform/modules/lb/main.tf line 142, in resource "google_compute_managed_ssl_certificate" "default":
│  142: resource "google_compute_managed_ssl_certificate" "default" {
│ 
╵
ERRO[0023] 1 error occurred:
        * exit status 1

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behavior

It should have updated or deleted the necessary resources and replaced with the updated managed certs

### Actual Behavior

error (forcing manual deletion of resources and rerunning

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform apply`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: authenticating as a user instead of a service account? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

<!---
Note Google Cloud customers who are working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team
--->

**Comment by edwardmedia** [comment]
@ggprod I am trying to understand whether this is an issue at the provider or inside the module. Are you able to repro the issue with a resource? Please share the config if you can. I would direct you to the module owner for help if you can't repro with a resource

**Comment by edwardmedia** [comment]
@ggprod can you repro this issue with a config of resources?

**Comment by edwardmedia** [comment]
@ggprod closing this assuming it is no longer an issue
