### ISSUE TITLE
Support SSH authentication For Dataform Repository

### ISSUE THREAD

**Issue by mardessonsfeir** [hashicorp/terraform-provider-google#15975]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In addition of [authentication_token_secret_version](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataform_repository#authentication_token_secret_version), support [SshAuthenticationConfig](https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#SshAuthenticationConfig) in [GitRemoteSettings](https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#GitRemoteSettings) in [Dataform Repositories](https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories).

### New or Affected Resource(s)

* [google_dataform_repository](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataform_repository)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_dataform_repository" "dataform_respository" {
  provider = google-beta
  name = "dataform_repository"
  git_remote_settings {
      url = google_sourcerepo_repository.git_repository.url
      default_branch = "main"
      authentication_token_secret_version = null
      ssh_authentication_config = {
            user_private_key_secret_version = google_secret_manager_secret_version.secret_version.id
            host_public_key = {host-public-key}
       }
  }
}
```

b/305277706

**Comment by maverickjoy** [comment]
This support for SSH authentication has been added : https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/dataform_repository , Thanks
