### ISSUE TITLE
Cannot create PREMIUM google_compute_global_address when google_compute_project_default_network_tier set to STANDARD

### ISSUE THREAD

**Issue by glimberg** [hashicorp/terraform-provider-google#15982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.7
Terraform provider google: v4.83.0

### Affected Resource(s)

* google_compute_global_address
* google_compute_project_default_network_tier

### Terraform Configuration Files

```tf
// set default network tier to Standard
resource "google_compute_project_default_network_tier" "project-tier" {
  project      = var.project
  network_tier = "STANDARD"
}

// grafana IP address
resource "google_compute_global_address" "grafana_external_address" {
  name         = "ztc-test-grafana-ip"
  address_type = "EXTERNAL"
  ip_version   = "IPV4"
}

// central IP address
resource "google_compute_global_address" "central_external_address" {
  name         = "ztc-test-central-ip"
  address_type = "EXTERNAL"
  ip_version   = "IPV4"
}

// keycloak IP address
resource "google_compute_global_address" "keycloak_external_address" {
  name         = "ztc-test-keycloak-ip"
  address_type = "EXTERNAL"
  ip_version   = "IPV4"
}
```

### Debug Output

https://gist.github.com/glimberg/d24a3739326e59d73f9de5938f0ea831

### Panic Output

None

### Expected Behavior

Per [Google Endpoint Documentation](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses), Global addresses shoule always be PREMIUM tier.

> This signifies the networking tier used for configuring this address and can only take the following values: PREMIUM or STANDARD. Internal IP addresses are always Premium Tier; global external IP addresses are always Premium Tier; regional external IP addresses can be either Standard or Premium Tier.

> If this field is not specified, it is assumed to be PREMIUM.

I would expect that the terraform provider would either default the network tier to PREMIUM, or at least have a `network_tier` argument so that it can be set as PREMIUM manually. 

### Actual Behavior

Google provider has no `network_tier` argument for `google_compute_global_address`, even though the API endpoint accepts a `networkTier` parameter.  Either the API docs are incorrect and it is not defaulting to PREMIUM for global addresses, or the terraform provider is overriding the argument with STANDARD.   

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It is possible to have the default network tier set to STANDARD and create PREMIUM Global addresses from GCP's web UI. 

### References

* #11611

**Comment by edwardmedia** [comment]
@glimberg does below [doc](https://cloud.google.com/network-tiers/docs/set-network-tier#setting_the_tier_for_all_resources_in_a_project) explain why it chooses standard tier in your case?

When creating a static regional external IP address, you can specify either PREMIUM or STANDARD for its network tier. If you don't specify a network tier, the address is created using the [project default tier](https://cloud.google.com/network-tiers/docs/set-network-tier#setting_the_tier_for_all_resources_in_a_project).

**Comment by glimberg** [comment]
I'm trying to create a GLOBAL PREMIUM ip address, not a regional external IP address.   GKE ingresses require a global premium address.  You can't do that with the "google_compute_address" resource, only the "google_compute_global_address" resource.

**Comment by glimberg** [comment]
Also, you can't specify a network tier for "google_compute_address" as there is no "network_tier" argument for it.

**Comment by edwardmedia** [comment]
I do see below statement in the [doc](https://cloud.google.com/network-tiers/docs/set-network-tier#expandable-2) 

```
Note: Global external IP addresses and internal IP addresses are always Premium Tier.
```

I think PREMIUM can be hard-coded for Global external IP addresses

**Comment by glimberg** [comment]
Either hard coded to PREMIUM, or exposing a `network_tier` argument for  `google_compute_global_address` will work for me.  I'm just blocked by this currently, as I can't create global addresses at all via terraform.

It's a hard requirement in our project that the default network tier is STANDARD so that our k8s node pools live on the standard tier.  The google API for k8s has no way to set the network tier for node pools, and setting the default network tier to standard is the only way to do that.
