### ISSUE TITLE
Cloud scheduler, bug in the provider

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/terraform-provider-google#16018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.5.7 Terraform Cloud

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
resource "google_cloud_scheduler_job" "ingestion_job" {
  name        = "${var.client}-${var.environment}-ingestion-scheduled-job"
  schedule    = "0 4 * * *"
  time_zone   = "America/Toronto"
  project = var.project
  region = var.region

  http_target {
    uri         = "${var.data_ingestion_api_url}/api/ingestion"
    http_method = "POST"
    headers = tomap({
      Content-Type = "application/json"
    })
    body        = base64encode("{\"impersonation_email\":\"example@corpemail.com\"}")
    oidc_token {
      service_account_email = var.ingestion_srv_acc_email
    }
  }
}
```

### Panic Output

Error: Provider produced inconsistent final plan
When expanding the plan for module.cloud_scheduler.google_cloud_scheduler_job.ingestion_job to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/google" produced an invalid new value for .http_target[0].oidc_token[0].audience: was null, but now cty.StringVal("https://my-app.uc.a.run.app/api/ingestion").

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected Behavior

Expected to deploy cloud scheduler

### Actual Behavior

Plan errors out 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@periwinkleFTW can you share the debug log?

**Comment by periwinkleFTW** [comment]
@edwardmedia I am not sure how to pull the debug from terraform cloud. 
It was plan (which succeeded) and then apply. Running apply 2nd time resulted in a successful apply, but it is a little annoying

**Comment by edwardmedia** [comment]
@periwinkleFTW for [debug log,](TF_LOG) are you able to create the environment variable?

```
export TF_LOG=DEBUG
```

`inconsistent plan` is likely related to the variables you use in the config. Are you able to repo the issue if you hardcode the config?

**Comment by edwardmedia** [comment]
@periwinkleFTW is this still an issue?

**Comment by periwinkleFTW** [comment]
@edwardmedia yes, the error still persists

**Comment by edwardmedia** [comment]
@periwinkleFTW I need the debug log so I can take a closer look. Are you able to run apply with [this](https://github.com/hashicorp/terraform-provider-google/issues/16018#issuecomment-1737585362)?

**Comment by periwinkleFTW** [comment]
@edwardmedia when using Terraform Cloud I can't seem to get the file output of the apply operation. When setting the TF_LOG value the only difference I see in the console is several lines of extra output in the beginning (version, igonoring plugins dir, etc.), then goes the regular apply output and it ends with the error I posted above

**Comment by edwardmedia** [comment]
@periwinkleFTW can you share the debug log that contains api requests and responses?

**Comment by edwardmedia** [comment]
@periwinkleFTW is this still an issue?

**Comment by periwinkleFTW** [comment]
@edwardmedia I got a hold of the log, I just need to clean it up

**Comment by edwardmedia** [comment]
@periwinkleFTW closing this now. Feel free to reopen this or file a new issue once you have more info.
