### ISSUE TITLE
google_compute_subnetwork wants to recreate subnet ranges for no reason

### ISSUE THREAD

**Issue by sephethus** [hashicorp/terraform-provider-google#16026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.5.7

### Affected Resource(s)

google_compute_subnetwork 

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "subnet" {
  name                       = google_compute_network.global.name
  ip_cidr_range              = local.ws_vars["cidr-block"]
  network                    = google_compute_network.global.name
  private_ip_google_access   = true
  region                     = local.ws_vars["region"]
  private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS"

  secondary_ip_range {
    ip_cidr_range = local.ws_vars["secondary"]
    range_name    = "subnet-pods"
  }

  secondary_ip_range {
    ip_cidr_range = local.ws_vars["tertiary"]
    range_name    = "subnet-services"
  }
}
```

### Debug Output
https://gist.github.com/sephethus/231829efb1a6d44780166ea554b42aad

### Panic Output
N/A

### Expected Behavior
What should happen is that it doesn't want to do anything to the subnet IP ranges since they match the state exactly down to the exact same IP ranges. It should only add the two things I needed to add. 

### Actual Behavior
It always wants to replace these subnet for no reason even after adding them. 

### Steps to Reproduce
Add a VPC subnet with secondary ranges, then try to apply again and it wants to replace the ranges it created which it cannot do because it errors out and plus they're already in use!

1. `terraform apply`
```
# google_compute_global_address.cb_private_pool will be created
  + resource "google_compute_global_address" "cb_private_pool" {
      + address            = (known after apply)
      + address_type       = "INTERNAL"
      + creation_timestamp = (known after apply)
      + description        = "IP Range for cloudbuild."
      + id                 = (known after apply)
      + name               = "cloudbuild-range"
      + network            = "stage"
      + prefix_length      = 16
      + project            = (known after apply)
      + purpose            = "PRIVATE_SERVICE_CONNECT"
      + self_link          = (known after apply)
    }

  # google_compute_subnetwork.subnet will be updated in-place
  ~ resource "google_compute_subnetwork" "subnet" {
        id                         = "projects/bdt-eng-stage/regions/us-east4/subnetworks/stage"
        name                       = "stage"
      ~ secondary_ip_range         = [
          - {
              - ip_cidr_range = "10.204.0.0/16"
              - range_name    = "gke-standard-cluster-1-pods-e08e7bbc"
            },
          - {
              - ip_cidr_range = "10.113.16.0/20"
              - range_name    = "gke-standard-cluster-1-services-e08e7bbc"
            },
          - {
              - ip_cidr_range = "10.201.0.0/16"
              - range_name    = "subnet-services"
            },
            {
                ip_cidr_range = "10.202.0.0/18"
                range_name    = "subnet-pods"
            },
          + {
              + ip_cidr_range = "10.201.0.0/16"
              + range_name    = "subnet-services"
            },
        ]
        # (11 unchanged attributes hidden)

      - timeouts {}
    }

  # google_service_networking_connection.private-service will be created
  + resource "google_service_networking_connection" "private-service" {
      + id                      = (known after apply)
      + network                 = "stage"
      + peering                 = (known after apply)
      + reserved_peering_ranges = [
          + "cloudbuild-range",
        ]
      + service                 = "servicenetworking.googleapis.com"
    }
```

### Important Factoids

Google auto manages its own ranges automatically with the k8s cluster on that subnet. There's no control over those that I can put in a terraform so it always wants to delete them which is fine, Google can recreate them, it's the other two subnets I don't understand. There's an ipv6 null value that becomes a string but why didn't it just import that value as a string instead of null? Why doesn't it let me set it explicitly in the tf?

```
╷
│ Error: Value for unconfigurable attribute
│ 
│   with google_compute_subnetwork.subnet,
│   on network.tf line 16, in resource "google_compute_subnetwork" "subnet":
│   16:   internal_ipv6_prefix = ""
│ 
│ Can't configure a value for "internal_ipv6_prefix": its value will be decided automatically based on the result of applying this configuration.
```

### References

* #0000

**Comment by sephethus** [comment]
Tried adding a Lifecycle block for ignoring changes and got this:

```
│ Warning: Redundant ignore_changes element
│ 
│   on network.tf line 9, in resource "google_compute_subnetwork" "subnet":
│    9: resource "google_compute_subnetwork" "subnet" {
│ 
│ Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has been created,
│ retaining the value originally configured.
│ 
│ The attribute internal_ipv6_prefix is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute in
│ ignore_changes has no effect. Remove the attribute from ignore_changes to quiet this warning.
```

**Comment by edwardmedia** [comment]
@sephethus you have 2 nodes of `secondary_ip_range` in the config. How comes it has 4 in the plan? Did you plan to remove 2?

It is server-side reordering. To avoid recreation, you may try to shift the order of `secondary_ip_range`.

**Comment by sephethus** [comment]
@edwardmedia the other 2 are created and destroyed as needed by GCP as part of the k8s cluster, not by us, so it's hard to control those other 2.

**Comment by Jojoooo1** [comment]
also having same issue!

**Comment by melinath** [comment]
@edwardmedia could you try to reproduce this & remove forward/review if you can?

**Comment by edwardmedia** [comment]
@sephethus @Jojoooo1 can you provide a simple config that I can use to repro?

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer an issue. Feel free to reopen if anyone see the issue again
