### ISSUE TITLE
Failing test(s): TestAccComputeNetworkEndpoints_networkEndpointsBasic

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16027]
### Failure rates

- Failure on 28th Sept 2023 - after merging `main` into `FEATURE-BRANCH-major-release-5.0.0` branch

### Impacted tests

- TestAccComputeNetworkEndpoints_networkEndpointsBasic

### Affected Resource(s)

* google_compute_network_endpoints

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/1205723632542747486?currentProjectId=TerraformProviders_Google_MajorRelease500&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccComputeNetworkEndpoints_networkEndpointsBasic
=== PAUSE TestAccComputeNetworkEndpoints_networkEndpointsBasic
=== CONT  TestAccComputeNetworkEndpoints_networkEndpointsBasic
    vcr_utils.go:152: Step 2/11 error running import: exit status 1
        Error: Import id "ci-test-project-nightly-ga/us-central1-a/tf-test-neg-4izqrrwro2/endpoints" doesn't match any of the accepted formats: [^projects/(?P<project>[^/]+)/zones/(?P<zone>[^/]+)/networkEndpointGroups/(?P<network_endpoint_group>[^/]+)$ ^(?P<project>[^/]+)/(?P<zone>[^/]+)/(?P<network_endpoint_group>[^/]+)$ ^(?P<zone>[^/]+)/(?P<network_endpoint_group>[^/]+)$ ^(?P<network_endpoint_group>[^/]+)$]
--- FAIL: TestAccComputeNetworkEndpoints_networkEndpointsBasic (196.05s)
FAIL

```

**Comment by melinath** [comment]
This seems to be passing. https://hashicorp.teamcity.com/test/1205723632542747486?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true
