### ISSUE TITLE
Error creating instance: googleapi: Error 400: [e2-medium, local-ssd] features are not compatible for creating instance., badRequest

### ISSUE THREAD

**Issue by akshatmawasthi** [hashicorp/terraform-provider-google#16020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.6

### Affected Resource(s)

google_compute_instance

### Terraform Configuration Files

Mentioned [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage)

### Debug Output

google_compute_instance.default: Creating...
╷
│ Error: Error creating instance: googleapi: Error 400: [e2-medium, local-ssd] features are not compatible for creating instance., badRequest
│ 
│   with google_compute_instance.default,
│   on main.tf line 22, in resource "google_compute_instance" "default":
│   22: resource "google_compute_instance" "default" {

### Expected Behavior

Created an e2 instance as per the example. 

### Actual Behavior

Did not create an instance, threw an error.

### Steps to Reproduce

Follow [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage)

**Comment by akshatmawasthi** [comment]
Changing the same to `n2-standard-2` works fine.

**Comment by usman-github** [comment]
On checking I can see local SSD does not support e2 machine types.

[Local SSD doc](https://cloud.google.com/compute/docs/disks/local-ssd#choose_number_local_ssds)

**Comment by edwardmedia** [comment]
@akshatmawasthi glad you found the reason. Should we close the issue?

**Comment by usman-github** [comment]
I guess it's confusing because of example. In example it's shown e2-medium with local SSD. I guess we can consider this as documentation bug.

**Comment by edwardmedia** [comment]
Oh, I see. Thank you for pointing that out. I can fix that in the doc
