### ISSUE TITLE
Failing test(s): TestAccBigqueryDataTransferConfig

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16033]
### Failure rates

- 100% since 2023-09-27 - new type of failure

### Impacted tests

- TestAccBigqueryDataTransferConfig

### Affected Resource(s)

* google_bigquery_data_transfer_config

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/3804758540908690301?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A34044%29%2Cid%3A2000000001)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccBigqueryDataTransferConfig
=== RUN   TestAccBigqueryDataTransferConfig/booleanParam
=== RUN   TestAccBigqueryDataTransferConfig/update_params
=== RUN   TestAccBigqueryDataTransferConfig/update_service_account
=== RUN   TestAccBigqueryDataTransferConfig/basic
=== RUN   TestAccBigqueryDataTransferConfig/update
    vcr_utils.go:152: Step 2/5 error: Error running apply: exit status 1
        Error: Error updating Config "projects/594424405950/locations/asia-northeast1/transferConfigs/6514c398-0000-2c7f-9fe7-883d24fe0948": googleapi: Error 400: The requested service account name () doesn't exist.
          with google_bigquery_data_transfer_config.query_config,
          on terraform_plugin_test.tf line 25, in resource "google_bigquery_data_transfer_config" "query_config":
          25: resource "google_bigquery_data_transfer_config" "query_config" {
=== RUN   TestAccBigqueryDataTransferConfig/service_account
=== RUN   TestAccBigqueryDataTransferConfig/no_destintation
--- FAIL: TestAccBigqueryDataTransferConfig (257.90s)
    --- PASS: TestAccBigqueryDataTransferConfig/booleanParam (34.18s)
    --- PASS: TestAccBigqueryDataTransferConfig/update_params (31.37s)
    --- PASS: TestAccBigqueryDataTransferConfig/update_service_account (60.29s)
    --- PASS: TestAccBigqueryDataTransferConfig/basic (33.11s)
    --- FAIL: TestAccBigqueryDataTransferConfig/update (39.01s)
    --- PASS: TestAccBigqueryDataTransferConfig/service_account (30.49s)
    --- PASS: TestAccBigqueryDataTransferConfig/no_destintation (29.45s)
FAIL

```

b/303808513

**Comment by SarahFrench** [comment]
Previously these tests failed due to a missing permission, which appears to be related to how the GA nightly tests were configured with Beta credentials for a period. Now the credentials are fixed the error shown above has occurred

**Comment by cleentfaar** [comment]
@SarahFrench we are running into the same error when running terraform apply on `google_bigquery_data_transfer_config` resources, in particular when we do it a second time (updates):
```
Error updating Config "...": googleapi: Error 400: The requested service account name () doesn't exist.
```


I noticed that if we specify a value for the `service_account_name` argument, it works again. It seems google no longer falls back to the SA that is running the terraform apply, and needs it to be specified explicitly? But only for updates, so sounds more like a bug?

**Comment by kickingfish** [comment]
We are getting the same error message.  This is happening when the provider is upgraded to 4.84.0.  If the 4.84.0 is used initially (not from upgrade), there is no issue.

**Comment by kickingfish** [comment]
I just tested the 5.0.0, it is still giving me the error --  Error: Error updating Config "projects/304937331054/locations/us/transferConfigs/653202dd-0000-236e-8fc1-94eb2c1bd542": googleapi: Error 400: The requested service account name () doesn't exist.

**Comment by kitagry** [comment]
I think this error occurs from https://github.com/hashicorp/terraform-provider-google/pull/15359.

I tried the following step

1. create `google_bigquery_data_transfer_config` : ok
2. change `google_bigquery_data_transfer_config` and update this: NG
    * error message is `Error 400: The requested service account name () doesn't exist.`

I think it is because updateMasks includes `service_account_name` whether `service_account_name` is empty or not. And if we don't set service_account_name explicitly, it try to update `service_account_name` to `""`.

**Comment by kickingfish** [comment]
Do we have an ETA for the fix? @SarahFrench

**Comment by SarahFrench** [comment]
I'll add a bug report separate to this issue

**Comment by SarahFrench** [comment]
Please follow https://github.com/hashicorp/terraform-provider-google/issues/16126 for updates on this bug as it goes through our triage process
