### ISSUE TITLE
Failing test(s): TestAccSecurityCenterFolderCustomModule

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16031]
### Failure rates

- 50% since 2023-09-27

### Impacted tests

- TestAccSecurityCenterFolderCustomModule

### Affected Resource(s)

* google_scc_folder_custom_module

### Nightly build test history

- Test history [when testing the 5.0.0 feature branch](https://hashicorp.teamcity.com/test/-4135639669920591092?currentProjectId=TerraformProviders_Google_MajorRelease500)
- Test history [when testing the main branch](https://hashicorp.teamcity.com/test/-4135639669920591092?currentProjectId=TerraformProviders_Google_NightlyTests)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccSecurityCenterFolderCustomModule
=== PAUSE TestAccSecurityCenterFolderCustomModule
=== CONT  TestAccSecurityCenterFolderCustomModule
    vcr_utils.go:152: Step 1/6 error: Error running apply: exit status 1
        Error: Error creating FolderCustomModule: googleapi: Error 403: Permission 'securitycenter.securityhealthanalyticscustommodules.create' denied on resource '//securitycenter.googleapis.com/folders/930278552528/securityHealthAnalyticsSettings' (or it may not exist).
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.ErrorInfo",
            "domain": "securitycenter.googleapis.com",
            "metadata": {
              "permission": "securitycenter.securityhealthanalyticscustommodules.create",
              "resource": "folders/930278552528/securityHealthAnalyticsSettings"
            },
            "reason": "IAM_PERMISSION_DENIED"
          }
        ]
          with google_scc_folder_custom_module.example,
          on terraform_plugin_test.tf line 15, in resource "google_scc_folder_custom_module" "example":
          15: resource "google_scc_folder_custom_module" "example" {
--- FAIL: TestAccSecurityCenterFolderCustomModule (84.63s)
FAIL
```

**Comment by SarahFrench** [comment]
@melinath could you take a look at this please? Riley mentioned in triage that this feature was added recently

**Comment by melinath** [comment]
securitycenter.securityhealthanalyticscustommodules.create is already granted to the test runner, so this is probably a Folder initialization time issue.
