### ISSUE TITLE
[Major Release 5.0.0] Resource: google_container_node_pool

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#16036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf

resource "google_container_cluster" "with_logging_variant" {
  provider    = google-beta
  name               = "tf-test-container-cluster-5"
  location           = "us-central1-a"
  initial_node_count = 1
}

resource "google_container_node_pool" "with_logging_variant" {
  provider    = google-beta
  name               = "tf-test-container-node-pool-1"
  location           = "us-central1-a"
  cluster            = google_container_cluster.with_logging_variant.name
  initial_node_count = 1
  node_config {
    oauth_scopes = [
       "https://www.googleapis.com/auth/cloud-platform",
    ]
    taint {
      key    = "taint_key"
      value  = "taint_value"
      effect = "PREFER_NO_SCHEDULE"
    }

    taint {
      key    = "taint_key2"
      value  = "taint_value2"
      effect = "NO_EXECUTE"
    }
  }
}
```

### Expected Behavior

1. logging_variant is no longer defaulted to "DEFAULT" with 5.0 provider
2. management.auto_repair and management.auto_upgrade defaulted to false previously with 4.84 provider

### Actual Behavior

1. logging_variant is still defaulted to "DEFAULT" with 5.0 provider
2. management.auto_repair and management.auto_upgrade defaulted to true previously with 4.84 provider

### Steps to Reproduce

1. `terraform apply`

**Comment by zli82016** [comment]
Updated the configuration.

**Comment by c2thorn** [comment]
I think this is a lack of clarification in the upgrade guide.

in 4.84.0 - 
`logging_variant` had a provider default of "DEFAULT", so it would show in plan.
`management.auto_repair` and `management.auto_upgrade` had a provider default of "false" if `management` was set.
So the following config: 
```
resource "google_container_node_pool" "with_logging_variant" {
  provider           = google-beta
  name               = "tf-test-container-node-pool-1"
  location           = "us-central1-a"
  cluster            = google_container_cluster.with_logging_variant.name
  initial_node_count = 1
  management { }
  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
    taint {
      key    = "taint_key"
      value  = "taint_value"
      effect = "PREFER_NO_SCHEDULE"
    }

    taint {
      key    = "taint_key2"
      value  = "taint_value2"
      effect = "NO_EXECUTE"
    }
  }
}
```

produces 

```
# google_container_node_pool.with_logging_variant will be created
  + resource "google_container_node_pool" "with_logging_variant" {

...

      + management {
          + auto_repair  = false
          + auto_upgrade = false
        }
...
      + node_config {
...
          + logging_variant   = "DEFAULT"
...
    }
```

In 5.0.0, the same config shows
```
  + resource "google_container_node_pool" "with_logging_variant" {
....
      + management {
          + auto_repair  = true
          + auto_upgrade = true
        }
...

      + node_config {
...
          + logging_variant   = (known after apply)
...
```
  
Which was the intention of the change. I will update the upgrade guide wording to try to be more specific.
