### ISSUE TITLE
Failing test(s): TestAccContainerNodePool_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16064]
### Failure rates

- 100% since 2023-08-19

### Impacted tests

- [TestAccContainerNodePool_withUpgradeSettings](https://hashicorp.teamcity.com/test/7583668857587341009?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccContainerNodePool_withKubeletConfig](https://hashicorp.teamcity.com/test/7762531682459800328?currentProjectId=TerraformProviders&expandTestHistoryChartSection=true)

### Affected Resource(s)

* google_container_node_pool

### Nightly build test history

- Link

### Message(s)

```
    vcr_utils.go:152: Step 9/10 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # google_container_node_pool.with_upgrade_settings will be updated in-place
          ~ resource "google_container_node_pool" "with_upgrade_settings" {
                id                          = "projects/ci-test-project-188019/locations/us-central1/clusters/tf-test-cluster-v21c4mossn/nodePools/tf-test-np-wost8itqid"
                name                        = "tf-test-np-wost8itqid"
                # (10 unchanged attributes hidden)
        
              ~ upgrade_settings {
                    # (3 unchanged attributes hidden)
        
                  ~ blue_green_settings {
                        # (1 unchanged attribute hidden)
        
                      ~ standard_rollout_policy {
                          ~ batch_node_count    = 1 -> 0
                          ~ batch_percentage    = 0 -> 0.5
                            # (1 unchanged attribute hidden)
                        }
                    }
                }
        
                # (3 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.

```

```
    vcr_utils.go:152: Step 1/4 error: Error running apply: exit status 1
        
        Error: NodePool tf-test-np-hbt6hqjltx was created in the error state "ERROR"
        
          with google_container_node_pool.with_kubelet_config,
          on terraform_plugin_test.tf line 16, in resource "google_container_node_pool" "with_kubelet_config":
          16: resource "google_container_node_pool" "with_kubelet_config" {

```

b/302797392

b/310896802

**Comment by SarahFrench** [comment]
These are failing on PRs currently, e.g. : https://github.com/GoogleCloudPlatform/magic-modules/pull/9134#issuecomment-1741112656

**Comment by SarahFrench** [comment]
**Context for the blue/green settings test failure**

The test fails on `Step 9/10`, which is where the settings are being updated from 
- batch_node_count    = 1 -> 0
- batch_percentage    = 0 -> 0.5

Here is a code snippet showing steps 7, 8, and 9:

https://github.com/hashicorp/terraform-provider-google/blob/56ba3d1df486b617879cf166187c4b8516914c0d/google/services/container/resource_container_node_pool_test.go#L607-L617

So it looks like there might be an issue updating (or eventual consistency problem?) as the non-empty plan in the error message is showing a change that should be achieved by step 9

**Comment by melinath** [comment]
I've skipped these tests in https://github.com/GoogleCloudPlatform/magic-modules/pull/9165 - fixing the issue will require unskipping the tests as well.

**Comment by melinath** [comment]
Based on b/300999895 it seems like the API issue should be resolved, so all that needs to happen here is re-enabling the tests.
