### ISSUE TITLE
google_sql_database_instance deletion_protection flag does not not work when setting to true

### ISSUE THREAD

**Issue by EduardJoy** [hashicorp/terraform-provider-google#16074]
### Terraform Version

provider registry.terraform.io/hashicorp/google v4.84.0

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

    resource "google_sql_database_instance" "main_cloud_sql_instance" {
      name    = "my-db"
    
      region           = var.region
      database_version = "POSTGRES_15"
    
      settings {
        tier              = "db-f1-micro"
        edition           = "ENTERPRISE"
        activation_policy = "ALWAYS"
    
        ip_configuration {
          ipv4_enabled       = "false"
          private_network    = var.net_link
          allocated_ip_range = var.ip_range
          require_ssl        = true
        }
      }
    
      deletion_protection = true
    }

In the Instance page in GCP Cloud SQL , the instance deletion protection should be enabled.

Instance deletion protection remains disabled.

b/303033816

**Comment by EduardJoy** [comment]
However, when manually settings the deletion_protection to true in the google cloud platform website and then settings deletion_protection = false in terraform, it successfully disables the protection.

**Comment by edwardmedia** [comment]
@EduardJoy does the [note](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection)  make sense to you?

This flag only protects instances from deletion within Terraform. To protect your instances from accidental deletion across all surfaces (API, gcloud, Cloud Console and Terraform), use the API flag settings.deletion_protection_enabled.

**Comment by EduardJoy** [comment]
Thank you!
I think I may have misread between the options.
