### ISSUE TITLE
Migration path for google_secret_manager_secret automatic -> auto replication

### ISSUE THREAD

**Issue by peakematt** [hashicorp/terraform-provider-google#16081]
Apologies if this is somewhere obvious that I'm missing, but is there a correct way to migrate Terraform creating `google_secret_manager_secret` resources using the now-deprecated `automatic = True` replication config to the new `auto {}` config? 

TF plan indicates that this change will re-create the GSM secret to make this migration happen. This is quite disruptive if we have randomly generated tokens in these secrets that are not stored elsewhere. Is there a way to perform this migration without forcing recreation of the secrets?

**Comment by edwardmedia** [comment]
@peakematt is terraform's [lifecycle](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) helpful?

**Comment by rileykarson** [comment]
@peakematt: Are you attempting to upgrade from `4.84.0`? An issue w/ the upgrade path was reported in https://github.com/hashicorp/terraform-provider-google/issues/15885 and we made a change to support it that's only available in that release. Sorry about that, should have been caught at the time of the deprecation!

Assigning @c2thorn to follow up.

**Comment by peakematt** [comment]
Ah I see! Looks like I'm on 4.83. I'll bump my version first. 

I should have searched before posting!

Thank you!
