### ISSUE TITLE
Empty maps converted to null, breaking GCP console UI

### ISSUE THREAD

**Issue by bgalkows** [hashicorp/terraform-provider-google#16080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Provider version `v4.84.0`

### Affected Resource(s)

`Google_project` resources.  This affects their visibility in the GCP console.

### Terraform Configuration Files

```tf
terraform {
  backend "gcs" {
    bucket = "[redacted]"
  }

  required_version = "~> 1.5.0"
  required_providers {
    google = {
      version = "~> 4.65"
      source  = "hashicorp/google"
    }
    google-beta = {
      version = "~> 4.65"
      source  = "hashicorp/google-beta"
    }
  }
}
```

### Debug Output

No debug output to list here.  Project creation succeeds as normal, but the empty map for labels is unexpectedly converted to null.

### Panic Output

No panic output to list here.

### Expected Behavior

With a labels attribute set to its default value of {} as below:
```tf
variable "labels" {
  description = "Project Labels"
  type        = map(string)
  default     = {}
}
```

In all terraform google provider versions prior to `v4.84.0`, this default {} value would remain an empty map after creation in the Apply, as seen below:

```tf
"labels": {}
```

### Actual Behavior

In `v4.84.0`, this default value of {} is converted to null after Apply:

```tf
"labels": null
```

### Steps to Reproduce

1. Create a GCP project through Terraform HCL with Google provider version `v4.84.0`, including the following attribute with a default value of empty map {}:
```tf
variable "labels" {
  description = "Project Labels"
  type        = map(string)
  default     = {}
}
```
2. `terraform plan`
3. `terraform apply`

The field is now null instead of {}.  As a result, the GCP console UI fails in certain places preventing the project from being displayed in its proper path.  The project itself is fully functional, but the visibility in GCP is broken in certain spots.

### References

I am not aware of any relevant other issues, but I will link them here if made aware.

**Comment by edwardmedia** [comment]
@bgalkows v5.0.0 was just released. Would you please check if the issue still exists?

**Comment by rileykarson** [comment]
`google_project` had no changes in `4.84.0`: https://github.com/hashicorp/terraform-provider-google-beta/commits/v4.84.0/google-beta/services/resourcemanager/resource_google_project.go

There are some changed in `5.0.0` that could have induced a change like this, but this issue precedes the `5.0.0` binary going out by around 10 minutes.

**Comment by edwardmedia** [comment]
@bgalkows with v5.0.0 and below config, I gam getting the following data in the state. Is this not what you got?

```tf
resource "google_compute_instance" "default" {
  name         = "issue16080"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
      /*
      labels = {
        my_label = "value"
      }*/
      labels = var.labels
    }
  }
...

}

variable "labels" {
  description = "Project Labels"
  type        = map(string)
  default     = {}
}
```

```
    boot_disk {
        auto_delete = true
        device_name = "persistent-disk-0"
        mode        = "READ_WRITE"
        source      = "https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-a/disks/issue16080"

        initialize_params {
            image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-11-bullseye-v20230912"
            labels = {}
            size   = 10
            type   = "pd-standard"
        }
    }
```

**Comment by bgalkows** [comment]
@edwardmedia In my state, the labels attribute ended up set to null.  The application uses a highly templated project creation pipeline with base factories where this attribute has been unchanged, and through debugging that recent provider version `v4.84.0` was the only cause I could discern.  When adding an upper bound version constraint to avoid `v4.84.0`, the labels attribute was set to {} as expected (and seen above):

```  
    google = {
        version = "~> 4.4, < 4.84"
        source  = "hashicorp/google"
    }
```

My project cannot upgrade to `v5.0.0` yet due to breaking changes, but I can try to test this on my own time at some point.

**Comment by rileykarson** [comment]
Which specific resource(s) were affected? I checked `google_project` based on "GCP project resources" and it hadn't been modified directly in months prior to `5.0.0`. I didn't personally attempt a repro though (@edwardmedia can you test against `4.84.0` and an earlier `4.X` version?)

**Comment by edwardmedia** [comment]
@rileykarson @bgalkows I have tried v4.4.0, v4.80.0, v4.84.0 on the config mentioned [here](https://github.com/hashicorp/terraform-provider-google/issues/16080#issuecomment-1743714148), all got below result. 

Probably we need specific resource(s) that were affected

```
    boot_disk {
        auto_delete = true
        device_name = "persistent-disk-0"
        mode        = "READ_WRITE"
        source      = "https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-a/disks/issue16080"

        initialize_params {
            image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-11-bullseye-v20230912"
            labels = {}
            size   = 10
            type   = "pd-standard"
        }
    }
```

**Comment by bgalkows** [comment]
@rileykarson Yes this was specifically `google_project`.

**Comment by edwardmedia** [comment]
@bgalkows I can repro the issue on `google_project` with v4.83.0. Fortunately it looks like this issue has been fixed with v5.0.0.

If you use below provider and run below 2 commands, you should see two new attributes of labels that are created. 
```
terraform init -upgrade
terraform apply
```

```tf
terraform {
    required_providers {
        google = {
            #version = "~> 4.4, < 4.84"
            version = "~> 5.0.0"
        }
            google-beta = {
            #version = "~> 4.4, < 4.84"
            version = "~> 5.0.0"
        }
    }
}
```

```
          "attributes": {
            "effective_labels": {},
            "terraform_labels": {},
...
          },
```

**Comment by bgalkows** [comment]
Thanks for your help Edward.  Unfortunately my team isn't ready to migrate to `v5.0.0` yet due to some of the breaking changes, but I will raise this fix as one more reason to do so.

**Comment by edwardmedia** [comment]
@bgalkows closing this now. Please reopen or create new issue if you see an issue after you upgrade
