### ISSUE TITLE
Failing test(s): TestAccLoggingBucketConfigProject_locked

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#16099]
### Failure rates

- 100% since 2023-09-16

### Impacted tests

- TestAccLoggingBucketConfigProject_locked

### Affected Resource(s)

* google_logging_project_bucket_config

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/8616866650560997006?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccLoggingBucketConfigProject_locked
=== PAUSE TestAccLoggingBucketConfigProject_locked
=== CONT  TestAccLoggingBucketConfigProject_locked
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: Error deleting Logging Bucket Config "projects/tf-test-77hi3qtw68/locations/global/buckets/variable-locked": googleapi: Error 400: Locked buckets currently cannot be deleted
        Error: Error deleting Logging Bucket Config "projects/tf-test-77hi3qtw68/locations/global/buckets/fixed-locked": googleapi: Error 400: Locked buckets currently cannot be deleted
--- FAIL: TestAccLoggingBucketConfigProject_locked (55.07s)
FAIL
```

b/303986865

**Comment by pengq-google** [comment]
We changed the locked behavior on Sep 15. Will fix the test cases soon. Thanks for raising this issue.!

**Comment by SarahFrench** [comment]
This test has been deleted in https://github.com/GoogleCloudPlatform/magic-modules/pull/9373, so I'm closing this issue
