### ISSUE TITLE
google_secret_manager_secret_version_access refreshes indefinitely

### ISSUE THREAD

**Issue by ifieldhouse** [hashicorp/terraform-provider-google#16095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`registry.terraform.io/hashicorp/google v4.76.0`

### Affected Resource(s)

* `google_secret_manager_secret_version`
* `google_secret_manager_secret_version_access`

### Terraform Configuration Files

```tf
data "google_secret_manager_secret_version_access" "credentials" {
  project = <project name>
  secret  = <secret name>
  version = <version>
}
```

### Expected Behavior

As the Service Account has no permissions over this secret, the resource should raise an error, stopping the current run. Either the resource should raise an error and fail, or a `timeouts` metadata element should be added for `"read"`, in order to better manage these situations.

### Actual Behavior

The agent constantly tries to refresh the resource, constantly outputting `data.google_secret_manager_secret_version_access.credentials: Still refreshing... [3m50s elapsed]` every 10 seconds. This makes the agent finicky in these cases, forcing us to stop the agent, remove it from terraform cloud, and restart the agent.

b/303400099

**Comment by abheda-crest** [comment]
@ifieldhouse I've tried reproducing the issue by revoking the secret manager permissions from the service account but I am getting the following error:
```
Error: Error retrieving available secret manager secret version access: googleapi: Error 403: Permission 'secretmanager.versions.access' denied for resource 'projects/<project-name>/secrets/<secret-name>/versions/<version-name>' (or it may not exist).
   with data.google_secret_manager_secret_version_access.credentials,
   on main.tf line 17, in data "google_secret_manager_secret_version_access" "credentials":
   17: data "google_secret_manager_secret_version_access" "credentials" {
```
Could you please share the steps to reproduce this issue or share the debug logs for the same?
