### ISSUE TITLE
Data of google_service_account missing member attribute

### ISSUE THREAD

**Issue by unidoct** [hashicorp/terraform-provider-google#16092]
When doing for example this:
```
data "google_service_account" "this" {
  account_id = "default"
}
```
and later when I want to retrieve:
```
data.google_service_account.this.member
```
the `member` isn't available. I have to explicitly make the member like
```
"serviceAccount:${data.google_service_account.this.email}"
```

**Comment by edwardmedia** [comment]
@unidoct I do see [member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account#member) is in the doc. Can you share the debug log?

**Comment by rileykarson** [comment]
Could you share your provider version as well?

This works on my machine, with `5.0.0` (but should have worked well before that too):

```
$ terraform apply
data.google_service_account.this: Reading...
data.google_service_account.this: Read complete after 0s [id=projects/my-project/serviceAccounts/tf-153@my-project.iam.gserviceaccount.com]

Changes to Outputs:
  + member = "serviceAccount:tf-153@my-project.iam.gserviceaccount.com"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

member = "serviceAccount:tf-153@my-project.iam.gserviceaccount.com"
```

**Comment by edwardmedia** [comment]
@unidoct is this still an issue?

**Comment by unidoct** [comment]
Hi,

No sorry, it was an other problem. But my IDE marks the .member as red as
if it isn't available. The error was due to something else.

Thanks,

Op ma 9 okt 2023 om 18:25 schreef Edward Sun ***@***.***>:

**Comment by edwardmedia** [comment]
Cool, closing now
