### ISSUE TITLE
Remove network in google_alloydb_cluster

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#16119]
`network` was deprecated in favor of `network_config` in https://github.com/GoogleCloudPlatform/magic-modules/pull/8963

It should eventually be removed in a future major release.

b/312433510

**Comment by roaks3** [comment]
This wasn't being forwarded because the issue type could not be determined. I _think_ this would qualify as an enhancement.

**Comment by melinath** [comment]
Switching to technical debt since this is essentially cleaning up dead code.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11460
