### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withAddons

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#16114]
### Failure rates

- 100% since 2023-08-01

### Impacted tests

- TestAccContainerCluster_withAddons

### Affected Resource(s)

* google_container_cluster

### Nightly build test history

- New: https://hashicorp.teamcity.com/test/4436753147621778536?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A37637%29%2Cid%3A2000000004
- Old: https://ci-oss.hashicorp.engineering/test/4436753147621778536?currentProjectId=GoogleCloudBeta&expandTestHistoryChartSection=true

### Message(s)

```
    vcr_utils.go:152: Step 1/4 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_container_cluster.primary will be updated in-place
          ~ resource "google_container_cluster" "primary" {
                id                          = "projects/test-project/locations/us-central1-a/clusters/tf-test-cluster-h7fszn1seq"
                name                        = "tf-test-cluster-h7fszn1seq"
                # (26 unchanged attributes hidden)
              ~ addons_config {
                  ~ gce_persistent_disk_csi_driver_config {
                      ~ enabled = true -> false
                    }
                    # (11 unchanged blocks hidden)
                }
                # (21 unchanged blocks hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
```

This looks to be a permadiff.

b/303616086

**Comment by melinath** [comment]
I've skipped this test in https://github.com/GoogleCloudPlatform/magic-modules/pull/9165 - fixing the issue will require unskipping the test as well.

**Comment by mattcary** [comment]
The pd csi driver can't be disabled on create. I've been told the solution is "For fields that can only be set on update, the resource should set them in the Create method after the initial Create finishes - similar to [privateClusterConfig.EnablePrivateEndpoint](https://github.com/GoogleCloudPlatform/magic-modules/blob/0126c3d731f79d8e38905271a8430b3d1676544f/mmv1/third_party/terraform/services/container/resource_container_cluster.go.erb#L2387)".

I'll be making a PR on google's magic modules which will eventually circulate to here.
