### ISSUE TITLE
Not able to use data "aws_fsx_ontap_storage_virtual_machine" geting this error, Error: Plugin did not respond    with data.aws_fsx_ontap_storage_virtual_machine.example,

### ISSUE THREAD

**Issue by rajmartha26** [hashicorp/terraform-provider-google#16127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform version 1.1.9

### Affected Resource(s)

data "aws_fsx_ontap_storage_virtual_machine" "example" {
  id = "svm-12345678"
}

### Terraform Configuration Files

data "aws_fsx_ontap_storage_virtual_machine" "example" {
  id = var.source_svm_id

}

variable "source_svm_id"{
  description = "Identifier of the storage virtual machine (e.g. svm-12345678)."
  type        = string
}

### Debug Output

Error: Plugin did not respond

  with data.aws_fsx_ontap_storage_virtual_machine.example,
  on main.tf line 12, in data "aws_fsx_ontap_storage_virtual_machine" "example":
  12: data "aws_fsx_ontap_storage_virtual_machine" "example" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 385 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/fsx.flattenSelfManagedActiveDirectoryAtt

### Panic Output

Error: Plugin did not respond

  with data.aws_fsx_ontap_storage_virtual_machine.example,
  on main.tf line 12, in data "aws_fsx_ontap_storage_virtual_machine" "example":
  12: data "aws_fsx_ontap_storage_virtual_machine" "example" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 385 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/fsx.flattenSelfManagedActiveDirectoryAtt

### Expected Behavior

it should display the SVM details

### Actual Behavior

Error: Plugin did not respond

  with data.aws_fsx_ontap_storage_virtual_machine.example,
  on main.tf line 12, in data "aws_fsx_ontap_storage_virtual_machine" "example":
  12: data "aws_fsx_ontap_storage_virtual_machine" "example" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 385 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/fsx.flattenSelfManagedActiveDirectoryAtt

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@rajmartha26 are you talking about [fsx_ontap_storage_virtual_machine](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/fsx_ontap_storage_virtual_machine)? It appears a data source of **terraform-provider-aws**

This repo is about **terraform-provider-google.**  Do you have issue / questions about this [provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs)?

**Comment by rajmartha26** [comment]
sorry, closing the issue
