### ISSUE TITLE
Upgrade to 5.0.0 breaks pubsub

### ISSUE THREAD

**Issue by dogmatic69** [hashicorp/terraform-provider-google#16129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_pubsub_topic

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "topic" {
  name = join("-", compact([var.name, var.seed]))

  project                    = var.project
  message_retention_duration = var.retention_duration

  labels = {
    terraformed = "true"
    component   = var.component
    seed        = var.seed
  }

  dynamic "message_storage_policy" {
    for_each = var.allowed_regions != null ? ["yes"] : []

    content {
      allowed_persistence_regions = var.allowed_regions
    }
  }
}
```

### Debug Output

```
Error: Error updating Topic "projects/xxx/topics/yyy": googleapi: Error 400: The update_mask in the UpdateTopicRequest must be set, and must contain a non-empty paths list.

  with module.foo.google_pubsub_topic.topic,
  on .terraform/modules/foo/modules/async-messaging/topic/resources.tf line 1, in resource "google_pubsub_topic" "topic":
   1: resource "google_pubsub_topic" "topic" {
```

The plan is as follows with many similar errors / updates to the topic. For reference the value of "seed" is "" (empty string) and has not changed but is passed in as a variable.
```
  # module.foo.google_pubsub_topic.topic will be updated in-place
  ~ resource "google_pubsub_topic" "topic" {
        id               = "projects/xxx/topics/yyy"
        name             = "yyy"
      ~ terraform_labels = {
          + "seed"        = (known after apply)
            # (2 unchanged elements hidden)
        }
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 55 to change, 0 to destroy.

```

### Expected Behavior

it should update the resource as was the case in 4.x

### Actual Behavior

apply fails with the stated error

### Steps to Reproduce

Create simple topic in 4.x, provision, update to 5.x and try again

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@dogmatic69 when you upgrade to v5.x, have you had chance to review the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade)? Did you run below command? 

```
terraform init -upgrade
```

**Comment by c2thorn** [comment]
The error looks to be the same as https://github.com/hashicorp/terraform-provider-google/issues/16091, is this a duplicate?

**Comment by edwardmedia** [comment]
@c2thorn the error does look like the same as reported https://github.com/hashicorp/terraform-provider-google/issues/16091

**Comment by edwardmedia** [comment]
Local test run with the latest source code passed.

**Comment by edwardmedia** [comment]
close as dup of https://github.com/hashicorp/terraform-provider-google/issues/16091

**Comment by dogmatic69** [comment]
> Local test run with the latest source code passed.

The issue is moving from 4.x to 5.x? Does the local test run cover that situation? 

When will the apparent fixes be released?

**Comment by c2thorn** [comment]
@dogmatic69 Yes it is an issue with existing resources upgrading from 4.x to 5.0. I assume by local test @edwardmedia meant manually testing the upgrade with the latest source code on `main` (with the fix)

> When will the apparent fixes be released?
Target is Monday October 9th with v5.1.0

**Comment by dogmatic69** [comment]
I've tried the workaround and seem to be working again. 

> Make some other change- such as adding a new label or modifying the existing one to avoid making a spurious call

**Comment by dogmatic69** [comment]
Seems like once the new tags are applied, the next apply with no changes breaks again. So the workaround only works once.
