### ISSUE TITLE
Adding google_compute_networks to list all networks within a specific project

### ISSUE THREAD

**Issue by jesse-l** [hashicorp/terraform-provider-google#16130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding a data source that would be used to list networks in a specific Google Cloud Project.

### New or Affected Resource(s)

* google_compute_networks

### Potential Terraform Configuration

```tf
resource "google_compute_networks" "default" {
     project_id = "<google_cloud_project_id>"
}
```

### References

* [Listing Network API Support](https://cloud.google.com/compute/docs/reference/rest/v1/networks/list)
* b/303638903

**Comment by rileykarson** [comment]
Closing based on https://github.com/GoogleCloudPlatform/magic-modules/pull/9232

You can close issues automatically by adding a keyword, generally "Fixes" before the issue title in your pull request body! https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
