### ISSUE TITLE
View Schema - Error: Conflicting configuration arguments

### ISSUE THREAD

**Issue by kickingfish** [hashicorp/terraform-provider-google#16148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.6.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v5.0.0

### Affected Resource(s)
google_bigquery_table

google_bigquery_table

### Terraform Configuration Files

```tf
module "bq_module" {
  source = "tfregistry-bqyissfikq-uc.a.run.app/ford/bigquery/gcp"

  project_id          = "<project id>"
  deletion_protection = false

  views = [
    {
      view_id             = "conflict view"
      dataset_id          = "tfm_dataset_vw"
      # description         = var.description
      use_legacy_sql      = false
      deletion_protection = false
      query               = "SELECT * FROM `<project id>.tfm_dataset_tbl.table_basic`"
      #query = file("view_qry.sql")
      schema = "view_qry.json"
      labels = {
        env      = "sandbox"
        billable = "false"
        owner    = "home"
      }
    }
  ]
}
```

### Debug Output
https://gist.github.com/kickingfish/824fc5eb1b5e2367ad684ef55e734eed

### Expected Behavior
Without error.  View will be created.

No error
### Actual Behavior
getting error Error: Conflicting configuration arguments

getting error Error: Conflicting configuration arguments
### Steps to Reproduce
Create views with schema from lower version of the Google provider.  Then, upgrade to 5.0.0.
schema file is used to give description to the columns 

I am using this tf files to test.  tf_files.zip attached
1. `terraform apply`

### References

* #0000

**Comment by kickingfish** [comment]
This code works until version 4.84.0.

**Comment by edwardmedia** [comment]
@kickingfish do you have the resource (not module) that can be used to repro the issue?

```tf
module "bq_module" {
  source = "tfregistry-bqyissfikq-uc.a.run.app/ford/bigquery/gcp"

...
}

**Comment by kickingfish** [comment]
This is the resource.

resource "google_bigquery_table" "bq_view" {
  for_each      = local.views
  dataset_id    = each.value["dataset_id"]
  friendly_name = each.key
  table_id      = each.key
  labels        = each.value["labels"]
  project       = var.project_id
  deletion_protection = each.value["deletion_protection"]
  depends_on = [google_bigquery_table.bq_table]

  description = each.value.description == "" ? null : each.value.description
  schema          = each.value["schema"]  == null ? null : file(each.value["schema"])
  #schema          = file(each.value["schema"])  == "" ? "blank.json" : file(each.value["schema"]) 

  view {
    query          = each.value["query"]
    use_legacy_sql = each.value["use_legacy_sql"]
  }
}

**Comment by edwardmedia** [comment]
@kickingfish can you hardcode the config so it can be run directly?

**Comment by kickingfish** [comment]
Hardcoding also give the same error.  

example,
resource "google_bigquery_table" "bq_view" {
#for_each = local.views
dataset_id = "tfm_dataset_vw"
friendly_name = "kingling_fish_Name"
table_id = "kingking_fish_view"
labels = null
project = "project_id"
deletion_protection = false
# depends_on = [google_bigquery_table.bq_table]

description = "kickfish_description"
schema = file("view_qry.json")
#schema = file(each.value["schema"]) == "" ? "blank.json" : file(each.value["schema"])

view {
query = "SELECT * FROM `project_id.dataset_id.table_id`"
use_legacy_sql = false
}
}


ERROR:
│ Error: Conflicting configuration arguments
│
│   with google_bigquery_table.bq_view,
│   on mmotta.tf line 26, in resource "google_bigquery_table" "bq_view":
│   26: resource "google_bigquery_table" "bq_view" {
│
│ "view": conflicts with schema
╵
╷
│ Error: Conflicting configuration arguments
│
│   with google_bigquery_table.bq_view,
│   on mmotta.tf line 37, in resource "google_bigquery_table" "bq_view":
│   37: schema = file("view_qry.json")
│
│ "schema": conflicts with view

**Comment by kickingfish** [comment]
If schema is defined inline..  this is the error.
Error: Conflicting configuration arguments
│
│   with google_bigquery_table.bq_view,
│   on mmotta.tf line 26, in resource "google_bigquery_table" "bq_view":
│   26: resource "google_bigquery_table" "bq_view" {
│
│ "view": conflicts with schema
╵
╷
│ Error: Conflicting configuration arguments
│
│   with google_bigquery_table.bq_view,
│   on mmotta.tf line 37, in resource "google_bigquery_table" "bq_view":
│   37: schema = <<EOF
│   38: [
│   39:   {
│   40:     "description": "FIRST NAME",
│   41:     "name": "FName",
│   42:     "type": "string",
│   43:     "mode": "nullable"
│   44:   },
│   45:   {
│   46:     "description": "LAST NAME",
│   47:     "name": "LName",
│   48:     "type": "string",
│   49:     "mode": "nullable"
│   50:   },
│   51:   {
│   52:     "description": "HOME ADDRESS",
│   53:     "name": "Address",
│   54:     "type": "string",
│   55:     "mode": "nullable"
│   56:   },
│   57:   {
│   58:     "description": "PHONE NUMBER",
│   59:     "name": "PhNumber",
│   60:     "type": "string",
│   61:     "mode": "nullable"
│   62:   }
│   63: ]
│   64: EOF
│
│ "schema": conflicts with view

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/16134, consolidating there
