### ISSUE TITLE
Add support for apigee pay as you go environment type parameter

### ISSUE THREAD

**Issue by emarcotte** [hashicorp/terraform-provider-google#16142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/blog/products/api-management/updates-to-apigee-api-management-pricing-models introduced several new options for environment types. The can be found [here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#EnvironmentType)

### New or Affected Resource(s)

[google_apigee_environment](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment)

### Potential Terraform Configuration

```tf
resource "google_apigee_environment" "env" {
  name         = "my-environment"
  description  = "Apigee Environment"
  display_name = "environment-1"
  org_id       = google_apigee_organization.apigee_org.id

  environment_type = "BASE"
}
```

### References

b/305197694

**Comment by scheuk** [comment]
+1

**Comment by melinath** [comment]
It looks like this is a request to add support for the `type` field - we'd prefer to use the name `type` if possible. I don't think it's reserved by Terraform / HCL.

**Comment by jimjcollins** [comment]
Some clarifications to this request:
1. Lacking the ability to set environment Type via the Terraform provider, we observe that Apigee PAYG environments created via the provider default to type "BASE", which lack features which are only available in "INTERMEDIATE" and "COMPREHENSIVE". So, the Apigee environments created lack necessary functionality and there is no ability to change the Apigee environment Type after creation.
2. "INTERMEDIATE" is claimed to be the default environment Type as per https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#EnvironmentType, so one would expect the Terraform provider which is lacking the ability to set Type would default to producing Apigee PAYG environments of Type "INTERMEDIATE", but that is not what is observed in actual usage of the Terraform provider, rather environments of type "BASE" are created.

**Comment by xuchenma** [comment]
This is fixed in https://github.com/hashicorp/terraform-provider-google/pull/16349
