### ISSUE TITLE
Unable to add Source and Destination IP Ranges -- Error: Conflicting configuration arguments - "source_ranges": conflicts with destination_ranges

### ISSUE THREAD

**Issue by Brink2Three** [hashicorp/terraform-provider-google#16155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.6.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.47.0
+ provider registry.terraform.io/hashicorp/google-beta v4.47.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_firewall" "cs-tools-default-deny-egress" {
	target_tags = ["cstools"]
	name = "cs-tools-default-deny-egress"
	network = google_compute_network.citystate.id
	description = "low priority rule to deny all internal traffic on this network unless specified."
	deny {
		ports = []
		protocol = "all"
	}
	direction = "EGRESS"
	disabled = false
	priority = 999
	source_ranges = ["10.14.102.0/24"]
	destination_ranges = [
		"10.10.0.0/16",
		"172.30.0.0/16"]
}
```

### Debug Output

https://gist.github.com/Brink2Three/0aebb1729419dc5174b868ead0768121

### Expected Behavior

Terraform creates a rule with both Source and Destination Ranges or matches an existing Firewall rule.

### Actual Behavior

Terraform errors out with the following messages:

```
 Error: Conflicting configuration arguments
│
│   with module.global.google_compute_firewall.cs-tools-default-deny-egress,
│   on global\google_compute_firewall.tf line 565, in resource "google_compute_firewall" "cs-tools-default-deny-egress":
│  565:         source_ranges = ["10.14.102.0/24"]
│
│ "source_ranges": conflicts with destination_ranges
╵
╷
│ Error: Conflicting configuration arguments
│
│   with module.global.google_compute_firewall.cs-tools-default-deny-egress,
│   on global\google_compute_firewall.tf line 566, in resource "google_compute_firewall" "cs-tools-default-deny-egress":
│  566:         destination_ranges = [
│  567:                 "10.10.0.0/16",
│  568:                 "172.30.0.0/16"]
│
│ "destination_ranges": conflicts with source_ranges
```

### Steps to Reproduce

1. Create a GCP firewall rule with both a source_range and a destination_range specified.
2. `terraform apply` or `terraform plan`

### References

I was unable to find any related issues to this issue. 

b/304967999

**Comment by SeiilkanM** [comment]
Having the same issue and blocked from moving forward. Is there any update on this, wondering if a fix exist already.

**Comment by Ruben-ASML** [comment]
You need to upgrade your terraform provider. The latest version is already 5.6.0. Also higher versions in the 4.x.x already have solutions.

**Comment by Brink2Three** [comment]
> You need to upgrade your terraform provider. The latest version is already 5.6.0. Also higher versions in the 4.x.x already have solutions.

Hey Ruben, I'll give that a try Monday and see if that fixes it. I didn't realize I was that far out of date. Thanks for the heads up.

**Comment by Brink2Three** [comment]
Yep that was it. Didn't want to do a major version upgrade to test, but going from `4.47.0` to `4.82.0` resolved the issue.
