### ISSUE TITLE
Failing test(s): TestAccProjectService_basic

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#16150]
### Failure rates

- 100% since 2023-09-29

### Impacted tests

- TestAccProjectService_basic

### Affected Resource(s)

* google_project_service

### Nightly build test history

- https://hashicorp.teamcity.com/test/3650280922175359194?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A35752%29%2Cid%3A2000000109

### Message(s)

```
Terraform will perform the following actions:
          # google_project_service.test2 must be replaced
        -/+ resource "google_project_service" "test2" {
              ~ id                 = "tf-test-6527160432802174682/cloudresourcemanager.googleapis.com" -> (known after apply)
              ~ project            = "tf-test-6527160432802174682" -> "projects/tf-test-6527160432802174682" # forces replacement
                # (2 unchanged attributes hidden)
            }
```

Possibly related to the default project changes?

**Comment by rileykarson** [comment]
@NickElliot can you look into this? I wonder if `SetNew` is overriding the DSF on the field.

**Comment by NickElliot** [comment]
I want to say there was a separate diffsuppress issue I had fixed where that wasn't conflicting before, but I'll look into it
