### ISSUE TITLE
Failing test(s): Apigee "this org is not authorized to set node_config"

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#16163]
### Failure rates

- 100% since 2023-10-02

### Impacted tests

- TestAccApigeeEnvironment_apigeeEnvironmentNodeconfigTestExample

### Affected Resource(s)

* google_apigee_environment

### Nightly build test history

- https://hashicorp.teamcity.com/test/-2720468524483745292?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A37180%29%2Cid%3A2000000012

### Message(s)

```
 Error: Error creating Environment: googleapi: Error 400: failed to process node config: this org is not authorized to set node_config
```

Looks like an API-side change; no change in the request sent to the server. Probably need to change something in our test env config but it's not clear what to do from the error message.

b/303986791

**Comment by rileykarson** [comment]
Addressed in https://github.com/GoogleCloudPlatform/magic-modules/pull/9340 by @xuchenma
