### ISSUE TITLE
Update resource Ids with extraneous prefixes or affixes to match eligible import formats

### ISSUE THREAD

**Issue by NickElliot** [hashicorp/terraform-provider-google#16160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

No specific version, present in 5.x.x and preceding.

### Affected Resource(s)

Currently including but not limited to:

* google_billing_project_info
* google_compute_network_endpoints

### Expected Behavior

When an Id is referenced in Terraform, it should provide the URI that is usable for all circumstances it may be needed.

### Actual Behavior

Some resources will append a trailing string e.g. `/endpoint` or `/billinginfo` to their structured URI that becomes the Id, and this Id will produce errors when attempted to be used as reference in certain scenarios such as importing.

### References

* [Pull request implementing stricter import validation that necessitated an update to import tests](https://github.com/GoogleCloudPlatform/magic-modules/pull/8913)
* [Pull request fixing a later-manifested test failure resulting from this issue](https://github.com/GoogleCloudPlatform/magic-modules/pull/9124)

**Comment by rileykarson** [comment]
@roaks3 fyi- this was mislabeled. I think it grabbed the first resource it saw?
