### ISSUE TITLE
Failing test(s): TestAccDataSourceComputeRouterStatus

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#16169]
### Failure rates

- 100% since 2023-09-14

### Impacted tests

- TestAccDataSourceComputeRouterStatus

### Affected Resource(s)

* google_compute_router_status

### Nightly build test history

- https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_NightlyTests_GOOGLE_PACKAGE_COMPUTE/38435?buildTab=tests&expandedTest=build%3A%28id%3A38435%29%2Cid%3A2000000007

### Message(s)

```
 vcr_utils.go:152: Step 1/1 error: Check failed: Check 7/7 error: data.google_compute_router_status.router1: Attribute 'best_routes.0.next_hop_vpn_tunnel' expected to be set
```

- b/304855345

**Comment by shuyama1** [comment]
fixed in b/304855345. Confirm the test has been passed consistently in the past few nights
