### ISSUE TITLE
Default settings for outlier detection are not compatible with gRPC

### ISSUE THREAD

**Issue by yutkin** [hashicorp/terraform-provider-google#16174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
* Terraform v1.4.2
* hashicorp/google 4.73.0 and 5.0.0
* hashicorp/google-beta 4.73.0 and 5.0.0

### Affected Resource(s)
`google_compute_backend_service`

### Terraform Configuration Files

```tf
outlier_detection {
    base_ejection_time {
      seconds = 30
      nanos = 0
    }
    interval {
      seconds = 10
      nanos = 0
    }
    success_rate_stdev_factor = 1000
  }
```

### Actual Behavior
Terraform adds default fields that are [not compatible with gRPC](https://cloud.google.com/traffic-director/docs/proxyless-configure-advanced-traffic-management#limitations). This causes `INTERNAL_ERROR` from Google after applying the plan:
<img width="470" alt="Screenshot 2023-10-09 at 11 11 00" src="https://github.com/hashicorp/terraform-provider-google/assets/2982775/8d2bfe59-cbb0-4a29-9283-b17e3ca5ad07">

Marking these fields as `null` didn't help. [Applying](https://cloud.google.com/traffic-director/docs/proxyless-configure-advanced-traffic-management#set_up_outlier_detection) these settings via `gcloud` tool finishes without errors.

**Comment by edwardmedia** [comment]
@yutkin I do see defaults are given to these fields in the [code](https://github.com/hashicorp/terraform-provider-google/blob/f0f0ae18a5144fc5ee2eaf14b63b22e341ba50ee/google/services/compute/resource_compute_backend_service.go#L899).  Do you have to provide `outlier_detection` block in the config in this case?

**Comment by yutkin** [comment]
> What do you see if you provide 0 (instead of null) to these fields?
Setting zeroes for these fields helped with applying the plan. Thanks!
