### ISSUE TITLE
Error: Conflicting configuration arguments, "schema": conflicts with view

### ISSUE THREAD

**Issue by andretojr** [hashicorp/terraform-provider-google#16192]
Guys, good morning!

We started having an error after updating the provider from 4.84.0 to 5.0.0, the same error occurs in 5.1.0.

All views in bigquery now have this error: Error: Conflicting configuration arguments, "schema": conflicts with view.

We noticed that if we remove the schema, the error does not occur.

Is there any change to the use of schema or would it be an error in the provider?

Attached is the Terraform trace and bigquery.tf file used.

Thank you, we await a response.

[en005-acervo-ibms-error.pdf](https://github.com/hashicorp/terraform-provider-google/files/12858174/en005-acervo-ibms-error.pdf)
[bigquery.txt](https://github.com/hashicorp/terraform-provider-google/files/12858199/bigquery.txt)

**Comment by edwardmedia** [comment]
@andretojr here is another issue https://github.com/hashicorp/terraform-provider-google/issues/16134 reported earlier, which appears to be the same as what you are facing. The fix will be released v5.2.0

**Comment by edwardmedia** [comment]
@andretojr closing as a dup. Feel free to reopen if you still see it with v5.2.0+
