### ISSUE TITLE
Allow passing docker run arguments for google_notebooks_instance module

### ISSUE THREAD

**Issue by PennyQ** [hashicorp/terraform-provider-google#16207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Our team is using google_notebooks_instance to provision Vertex AI notebooks for users. And we need to use our team managed container images with some additional build args, e.g. include GPU requests. 

Our current tf file looks like a combination of both basic image and GPU image examples as below:

```
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  metadata = {
    proxy-mode = "service_account"
    terraform  = "true"
  }
  container_image {
    repository = "gcr.io/{team_image_with_nvidia_driver}"
    tag = "latest"
  }
}
install_gpu_driver = true
boot_disk_type = "PD_SSD"
boot_disk_size_gb = 110
```
However the above wouldn't work as the GPU devices are not passed when docker containers are created. And we tested our docker image locally with `docker run --gpus all {team_image_with_nvidia_driver} nvidia-smi` and it can work well.

So would be nice to add an option for docker run args for the `container_image` set.
  

### New or Affected Resource(s)

* google_notebooks_instance

### Potential Terraform Configuration

The above code can look like
```
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  metadata = {
    proxy-mode = "service_account"
    terraform  = "true"
  }
  container_image {
    repository = "gcr.io/{team_image_with_nvidia_driver}"
    tag = "latest"
    run_args = {"--gpus", "all"}
  }
}
install_gpu_driver = true
boot_disk_type = "PD_SSD"
boot_disk_size_gb = 110
```

### References

* #0000

b/305197429

**Comment by melinath** [comment]
It looks like run_args (or any similar argument) is not currently supported by the API: https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v1/ContainerImage API support would need to be added before we could add support in the provider.

**Comment by bcreddy-gcp** [comment]
`google_notebooks_instance` is deprecated and will not be taking new feature requests. `google_workbench_instance` is the replacement if such features are of interest. Custom containers for workbench instances are under development right now.

**Comment by bcreddy-gcp** [comment]
`google_notebooks_instance is deprecated` and will not be taking new feature requests. If this is of interest, a FR can be raised for `google_workbench_instance`.

**Comment by melinath** [comment]
closing based on the above comment.

**Comment by bcreddy-gcp** [comment]
Here's the announcement: https://cloud.google.com/vertex-ai/docs/workbench/release-notes#January_16_2024
