### ISSUE TITLE
terraform-provider-google_v5.1.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by craigox** [hashicorp/terraform-provider-google#16208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.4.0

### Affected Resource(s)

* google_compute_reservation

### Terraform Configuration Files

This applied successfully  with an initial set of projects in the var, but when trying to add a new project it now causes a panic

```tf
resource "google_compute_reservation" "a2-high-1g-ew4b" {
  name    = "a2-high-1g-reservation-ew4b"
  project = var.project_id
  zone    = "europe-west4-b"
  specific_reservation {
    count = 1
    instance_properties {
      machine_type = "a2-highgpu-1g"
      guest_accelerators {
        accelerator_count = 1
        accelerator_type  = "nvidia-tesla-a100"
      }
    }

  }
  share_settings {
    share_type = "SPECIFIC_PROJECTS"
    dynamic "project_map" {
      for_each = var.general_gpu_share
      content {
        id = project_map.value
      }
    }
  }
  timeouts {
    create = "4m"
  }
}
```
```vars
variable "project_id" {
  type = string
}
variable "general_gpu_share" {
  type = list(any)
}
```
```variables
project_id        = "project_id"
general_gpu_share = ["project1", "project2", "project3", "project4"]
```
### Panic Output
```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.


Stack trace from the terraform-provider-google_v5.1.0_x5 plugin:
panic: runtime error: index out of range [0] with length 0

goroutine 277 [running]:
github.com/hashicorp/terraform-provider-google/google/services/compute.resourceComputeReservationUpdateEncoder(0x1036dfa80?, {0x103c54a20?, 0x14001821200}, 0xd?)
   github.com/hashicorp/terraform-provider-google/google/services/compute/resource_compute_reservation.go:1119 +0x10b8
github.com/hashicorp/terraform-provider-google/google/services/compute.resourceComputeReservationUpdate(0x140013f7000, {0x103c54a20?, 0x14001821200?})
   github.com/hashicorp/terraform-provider-google/google/services/compute/resource_compute_reservation.go:454 +0x2f4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x103cb1378?, {0x103cb1378?, 0x14001131770?}, 0xd?, {0x103c54a20?, 0x14001821200?})
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000990e00, {0x103cb1378, 0x14001131770}, 0x14001c796c0, 0x140013f6d80, {0x103c54a20, 0x14001821200})
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000ee9c98, {0x103cb1378?, 0x14001131650?}, 0x1400130eeb0)
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x14000e95560, 0x14000e955c0, {0x14001670680, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
   github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000681d60, {0x103cb1378?, 0x140011308a0?}, 0x14001c31c00)
   github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103bcbd60?, 0x14000681d60}, {0x103cb1378, 0x140011308a0}, 0x14001c31b90, 0x0)
   github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400004fa40, {0x103cba2c0, 0x140005a61a0}, 0x14001cd1560, 0x140017515f0, 0x1053fd660, 0x0)
   google.golang.org/grpc@v1.57.0/server.go:1360 +0xc88
google.golang.org/grpc.(*Server).handleStream(0x1400004fa40, {0x103cba2c0, 0x140005a61a0}, 0x14001cd1560, 0x0)
   google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
   google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
   google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-google_v5.1.0_x5 plugin crashed!
```

### Expected Behavior

Add a project to the reservation share, with no other changes to the resource.

### Actual Behavior

Panic raised

### Steps to Reproduce

1. `terraform apply -var-file=variables.tfvars`

### Important Factoids

using fast fabric as base for our organisation. 

### References

* #0000

b/305377682

**Comment by craigox** [comment]
same result with providers 4.84, 5 aswell

**Comment by edwardmedia** [comment]
@craigox does this happen on the initial apply? 

@ScottSuarez need to add checking [here](https://github.com/hashicorp/terraform-provider-google/blob/168350080fe4ba4ac54be355ccbb1b517a8fae9a/google/services/compute/resource_compute_reservation.go#L1119)?

**Comment by craigox** [comment]
> @craigox does this happen on the initial apply?
Yes!, this worked until I tried to add  a new project to the share list.

**Comment by craigox** [comment]
This repo is a bit borked atm, https://github.com/hashicorp/terraform-provider-google/issues/16208#issuecomment-1758037803 we can't update the project list atm

**Comment by narendraaduri1** [comment]
Stack trace from the terraform-provider-google_v4.84.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 214 [running]:
github.com/hashicorp/terraform-provider-google/google/services/sql.expandSqlServerAdvancedMachineFeatures(...)
        github.com/hashicorp/terraform-provider-google/google/services/sql/resource_sql_database_instance.go:1496       
github.com/hashicorp/terraform-provider-google/google/services/sql.expandSqlDatabaseInstanceSettings({0x16d93c00, 0x1, 0x1}, {0x169b0978, 0x12})
        github.com/hashicorp/terraform-provider-google/google/services/sql/resource_sql_database_instance.go:1247 +0x22da
github.com/hashicorp/terraform-provider-google/google/services/sql.resourceSqlDatabaseInstanceCreate(0x16bceeb0, {0x3853060, 0x17536d80})
        github.com/hashicorp/terraform-provider-google/google/services/sql/resource_sql_database_instance.go:1058 +0x7b6github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x16b5b500, {0x3f442a0, 0x16e2d668}, 0x16bceeb0, {0x3853060, 0x17536d80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x16b5b500, {0x3f442a0, 0x16e2d668}, 0x16ff33b0, 0x16bcedc0, {0x3853060, 0x17536d80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa92
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x16c12870, {0x3f442a0, 0x16e2d608}, 0x17378f90)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xfa4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x168983e0, 0x16898420, {0x173ff130, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x151       
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x16e31e50, {0x3f442a0, 0x16e2c138}, 0x16d7e600)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x583
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x38220a0, 
0x16e31e50}, {0x3f442a0, 0x16e2c138}, 0x16d7e5c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x18a   
google.golang.org/grpc.(*Server).processUnaryRPC(0x1752ec60, {0x3f48d9c, 0x16ffe000}, 0x16dfee60, 0x17565428, 0x56ac860, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xf03
google.golang.org/grpc.(*Server).handleStream(0x1752ec60, {0x3f48d9c, 0x16ffe000}, 0x16dfee60, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-google_v4.84.0_x5.exe plugin crashed!
not only 5.1.0 facing issue with 4.84.0, 5.0.0 also.

**Comment by ScottSuarez** [comment]
@roaks3 I didn't have a chance to get to this one but it will require some local testing. 

In particular I don't believe this update encoder was ever run or tested. I think it's total broken but your investigation may prove me wrong.
https://github.com/GoogleCloudPlatform/magic-modules/blob/5db8bc59741e95e78a2cd78bc03bce4b01bdf691/mmv1/templates/terraform/update_encoder/reservation.go.erb#L42

**Comment by baderfahoum17** [comment]
for what its worth, a temporary fix 
would be limiting the google-beta provider to 
```
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.63.1"
    }
```

**Comment by craigox** [comment]
Nope, doesnt work

```Stack trace from the terraform-provider-google_v4.63.1_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 199 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceComputeReservationUpdateEncoder(0x1032a7d20?, {0x10372af60?, 0x140015f8000}, 0xd?)
        github.com/hashicorp/terraform-provider-google/google/resource_compute_reservation.go:1069 +0x1090
github.com/hashicorp/terraform-provider-google/google.resourceComputeReservationUpdate(0x140019cbb00, {0x10372af60?, 0x140015f8000?})
        github.com/hashicorp/terraform-provider-google/google/resource_compute_reservation.go:428 +0x2fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x103771358?, {0x103771358?, 0x14001b975c0?}, 0xd?, {0x10372af60?, 0x140015f8000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14001133c00, {0x103771358, 0x14001b975c0}, 0x140027c6c30, 0x140019cb880, {0x10372af60, 0x140015f8000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x680
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14001478798, {0x103771358?, 0x14001b974a0?}, 0x140027b6190)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x14001422d80, 0x14001422de0, {0x14001907da0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140004885a0, {0x103771358?, 0x14001b96c00?}, 0x140025e7500)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1036b16a0?, 0x140004885a0}, {0x103771358, 0x14001b96c00}, 0x140025e7490, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000187e00, {0x103778440, 0x140019e2340}, 0x140027c3440, 0x140019d62a0, 0x104a36080, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xc7c
google.golang.org/grpc.(*Server).handleStream(0x14000187e00, {0x103778440, 0x140019e2340}, 0x140027c3440, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x298

Error: The terraform-provider-google_v4.63.1_x5 plugin crashed!```

**Comment by ScottSuarez** [comment]
Sorry @roaks3 forgot to forward this one. Since its end of the week you might not get to either

**Comment by melinath** [comment]
Based on the reported panic, the problem is with https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/compute/resource_compute_reservation.go#L1119 and the error is:

```
panic: runtime error: index out of range [0] with length 0
```

The object being indexed on that line is the `old` value returned by `d.GetChange("share_settings")`.

I was able to test this locally & reproduce the panic by creating a reservation with _no_ share_settings block and then _adding_ a share_settings block with a single project_map block inside. Here's a config to reproduce:

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "5.1.0"
    }
  }
}

resource "random_string" "suffix" {
  length  = 4
  upper   = false
  special = false
}

resource "google_project" "project1" {
  name = "Project1"
  project_id = "project1-${random_string.suffix.result}"
  org_id = "1234567890"
}

resource "google_compute_reservation" "a2-high-1g-ew4b" {
  name    = "test-reservation-asdf"
  zone    = "southamerica-west1-a"
  specific_reservation {
    count = 1
    instance_properties {
      machine_type = "e2-micro"
    }

  }
  share_settings {
    share_type = "SPECIFIC_PROJECTS"
    project_map {
      id = google_project.project1.project_id
    }
  }
  timeouts {
    create = "4m"
  }
}
```

In addition to fixing this issue, we should make sure that the update tests for this resource cover this case.
