### ISSUE TITLE
Apply new labels model to resources

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#16219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the next major release, apply the new labels model to resources by using the type `KeyValueLabels`
* `labels` field in `google_edgenetwork_network`
* `labels` field in `google_edgenetwork_subnet`
* `labels` field in `google_container_cluster`

**Comment by rileykarson** [comment]
Current change is small, but if the # we need to fix grows it'll probably be medium. Sizing that way so we don't undersize later.

**Comment by zli82016** [comment]
Apply the new labels model to `settings.user_labels` of the resource `google_sql_database_instance`

https://github.com/hashicorp/terraform-provider-google/issues/16375

**Comment by c2thorn** [comment]
Need to scan through new resources to see if the scope increases

**Comment by DevoFalcon** [comment]
It would be nice to have this apply to `resource_labels` for the resource `google_container_cluster` . Perhaps also to `node_config.resource_labels`

**Comment by rileykarson** [comment]
> This is probably out of scope of this, but it would be great to have a way to access the default_labels set on a provider

We could expose that value through `google_client_config`: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config

**Comment by zli82016** [comment]
> Apply the new labels model to `settings.user_labels` of the resource `google_sql_database_instance`
> 
> #16375

The  `default_labels` are not going to be applied to `google_sql_database_instance` resource as `user_labels` is nested inside `settings` and there is a bug in terraform sdk that SetNew is not working in the nested fields.  It needs to wait until the resource is migrated to plugin framework.
