### ISSUE TITLE
Error: Provider produced inconsistent final plan - "registry.terraform.io/hashicorp/google" produced an invalid new value for .terraform_labels: new element "date_modified" has appeared.

### ISSUE THREAD

**Issue by danishkamili** [hashicorp/terraform-provider-google#16217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Issue: 
Terraform fails to apply the plan, due to invalid new value for .terraform_labels: new element "date_modified" has appeared. While updating the resource GCP project.

### Terraform Version

Terraform v1.0.10

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
its from public Google LZ repo and this is the url to bootstrap files
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/environments/bootstrap

It fails at bootstrapping folder, only need to update the .tfvars and follow the instructions to bootstrap.sh (which needs billing ID, organization ID and folder ID where you want to create the boostrap project, first plan and apply is good, however, the subsequent apply fails - due to inconsistency.
```

### Debug Output
https://gist.github.com/danishkamili/3378fc6e5001da2a3c1653208295d585

### Panic Output

Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.landing_zone_bootstrap.module.project.google_project.project to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google" produced an invalid new value for .terraform_labels: new element "date_modified" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.landing_zone_bootstrap.module.project.google_project.project to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google" produced an invalid new value for .effective_labels: new element "date_modified" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
### Expected Behavior

Apply should be successful without adding additional labels 

### Actual Behavior

Terraform apply failed while trying to add a new label : date modified to the resource

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-google/issues/12043
https://github.com/hashicorp/terraform-provider-google/issues/10131

b/304967677

**Comment by fmichaelobrien** [comment]
We will need to look at upgrading from 1.0 to 1.5.7 or the new 1.6.0 https://releases.hashicorp.com/terraform/1.6.0/ as a first step in the https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding codebase

**Comment by danishkamili** [comment]
Setting a provider as per below suppressed the error, as its a change done at version >=5.0.0, 
[https://www.hashicorp.com/blog/terraform-google-provider-adds-updates-to-default-labels](https://www.hashicorp.com/blog/terraform-google-provider-adds-updates-to-default-labels)

> Effective labels: A new output-only attribute added to all resources, where the value contains a combination of all labels set on the resource in the Terraform configuration and any other labels present on the resource in Google Cloud that aren’t managed via Terraform.


required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 3.50, < 5.0.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 3.50, < 5.0.0"
    }
  }

**Comment by davidedironza** [comment]
Is there a timeline when this will be fixed?
We have a lot of projects to apply and we always get these errors "... .terraform_labels: new element ..."

**Comment by zli82016** [comment]
Found a similar issue 

Can you try Re-apply the terraform to see if the second `terraform apply` works, @davidedironza ?
