### ISSUE TITLE
Handle issue where TeamCity is trying to compile test binaries in empty packages

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16226]
# Background

Since the service package split all test files have left the `google`/`google-beta` packages. Either we need to remove them from TeamCity, or update the build steps to tolerate empty packages and fail gracefully.

# What kind of contribution is this issue about?

TeamCity

# Related PR(s), if any:

- N/A

# Details

See https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_NightlyTests_GOOGLE_PACKAGE_GOOGLE

![Screenshot 2023-10-11 at 22 34 05](https://github.com/hashicorp/terraform-provider-google/assets/15078782/d11d06d3-2f91-4ae2-a3d4-50ec51d6d5c6)

**Comment by SarahFrench** [comment]
@zli82016 is it preferable to either remove the `google` (and `google-beta`) packages' build configurations from TeamCity, or to keep them but make them fail gracefully if they don't contain any Go files?

**Comment by zli82016** [comment]
I remember it needs to add the package to the list manually to remove the packages from the TeamCity build configuration. It could be better to keep them and make them fail gracefully if they don't contain any go files in that case to avoid the manual work.
