### ISSUE TITLE
Unable to add an organization to domain restricted sharing org policy

### ISSUE THREAD

**Issue by nlrussell** [hashicorp/terraform-provider-google#16223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.2.2
Provider version: hashicorp/google v4.84.0 

### Affected Resource(s)

https://github.com/terraform-google-modules/terraform-google-org-policy/tree/v5.2.2/modules/domain_restricted_sharing

### Terraform Configuration Files

```tf
module "domain-restricted-sharing" {
  source           = "../../modules/domain_restricted_sharing"
  policy_for       = "organization"
  organization_id  = var.organization_id
  domains_to_allow = var.domains_to_allow
}
```

For `domains_to_allow`, tried org ID (numeric string), domain name (example.com), and DIRECTORY_CUSTOMER_ID per [this documentation](https://cloud.google.com/resource-manager/docs/organization-policy/restricting-domains#retrieving_customer_id). 

### Expected Behavior

Locate the organization being allowlisted, then plan and apply successfully.

### Actual Behavior

`Error: Organization not found`

This functionality works in the console, but not in Terraform.

### Steps to Reproduce

Create an org policy for domain restricted sharing, and try to add another organization to the list of domains to allow. 

### References
Many similar issues:
* #11911 
* https://github.com/terraform-google-modules/terraform-google-org-policy/issues/56 
* https://www.googlecloudcommunity.com/gc/General-Misc-Q-A/Domain-restricted-sharing-is-not-working-as-expected/m-p/625059

**Comment by edwardmedia** [comment]
@nlrussell can you reach out to the module owner https://github.com/terraform-google-modules/terraform-google-org-policy/issues to see if you can get help?

**Comment by edwardmedia** [comment]
@nlrussell closing this as this repo is not best for module
