### ISSUE TITLE
Add provider-defined custom functions

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#16244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

These seem to have been announced at HashiConf, as covered in https://github.com/hashicorp/terraform/issues/27696#issuecomment-1758977989.

I don't know much more than that yet, but may as well file a tracking issue to gather feedback / record plans!

Current ideas:

* Utility functions to retrieve project, zone, region, location, short resource name from a `.id` field
* Region from zone

### New or Affected Resource(s)

* N/A

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by bharathkkb** [comment]
Region from zone might another useful one https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/47477d60324a4b0045699e518251b4d4a0c53c08/main.tf#L44C52-L44C57

**Comment by SarahFrench** [comment]
Here's an idea I had when I heard about this new feature:

> Functions may also help users with prefixes required by member list entries in IAM resources, for example see how [in this example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam#google_bigquery_dataset_iam_member) user:<email here> is needed when setting the member argument. If the email corresponded to a service account it would need to be serviceAccount:<email here> , and if the email was for a Google group, then it'd be group:<email here>.
>
>Below is an example of how a fictional createIamMember function could help users add those prefixes automatically when iterating through a list of emails.
This would reduce a lot of work for user to provide these prefixes themselves, and [avoid that manual work resulting in typos like the one in this GitHub issue](https://github.com/hashicorp/terraform-provider-google/issues/13595#issuecomment-1408517060)

```tf
locals{
   emails = toset([
      "person.mcperson@example.com",                      # a single-person user
      "all-company@example.com,                          # a multi-user Google group
      "123456789-compute@developer.gserviceaccount.com", # a GCP service account
   ])
}

resource "google_bigquery_dataset_iam_member" "editor" {
  for_each   = local.emails
  dataset_id = google_bigquery_dataset.dataset.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = createIamMember(each.key)
}
```

**Comment by schollii** [comment]
Are these user-defined functions that can get created by the provider. 

Or, are they new functions provided exposed by the provider using a new mechanism that would be available to all providers? So technically someone who wants a new user-defined function could write a provider and create a resource that defines the function, then the user could use that function as any other function as long as the provider has been installed locally. Eg if the GCP provider has a gcp_udf resource e (that creates a user defined function in the provider) like this
```hcl
resource "gcp_udf" "foo" {
  funcname = "foo" 
  arg1 = {
     type = int
     description = "..." 
   } 
   return = {
     type = int
     description = "..." 
   } 
}
```
Then the tf code could use `gcp_foo(123)` in an expression that expects an int.

**Comment by bharathkkb** [comment]
Another usecase - extract elements from OP style resource names `//api.googleapis.com/locations/l/projects/p/collection/c`

**Comment by SarahFrench** [comment]
[v5.23.0 of the google](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.23.0) (and google-beta) provider introduced our first provider-defined functions.

For more information on provider-defined functions please see the [Terraform 1.8 announcement blog](https://www.hashicorp.com/blog/terraform-1-8-improves-extensibility-with-provider-defined-functions), and [a blog about the provider-defined functions released so far in major providers](https://www.hashicorp.com/blog/terraform-1-8-adds-provider-functions-for-aws-google-cloud-and-kubernetes).

There is also [the official documentation for creating provider-defined functions](https://developer.hashicorp.com/terraform/plugin/framework/functions).

---

Closing as complete. Any future requests or bug reports related to provider-defined functions should be created as separate issues.
