### ISSUE TITLE
Can't create a Cloud SQL Instance with PSC Enabled

### ISSUE THREAD

**Issue by luigi-bitonti** [hashicorp/terraform-provider-google#16257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.6.1

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "primary" {
  database_version               = "POSTGRES_13"
  deletion_protection            = false
  name                           = "db2"
  project                        = "myproject"
  region                         = "europe-west1"
  settings {
    activation_policy           = "ALWAYS"
    availability_type           = "ZONAL"
    deletion_protection_enabled = true
    disk_autoresize             = true
    disk_autoresize_limit       = 0
    disk_type                   = "PD_SSD"
    pricing_plan                = "PER_USE"
    tier                        = "db-g1-small"
    ip_configuration {
      ipv4_enabled    = false
      private_network = "projects/myproject/global/networks/test-vpc"
      psc_config {
        allowed_consumer_projects = [
            "test23",
        ]
        psc_enabled               = true
      }
    }
  }
}
```

### Expected Behavior

The CloudSQL Instance should be created.

### Actual Behavior
The instance is not created because the authorized network is enabled, which is not true.
_Error, failed to create instance db2: googleapi: Error 400: Invalid request: Authorized Network cannot be set for an instance with PSC connectivity.., invalid_

### Steps to Reproduce

1. `terraform apply`

### References

b/305924760

**Comment by madhu-narisetty** [comment]
Any resolution in place for this issue? I am also facing the same issue.

**Comment by disruptednetwork** [comment]
> Any resolution in place for this issue? I am also facing the same issue but I am using gcloud command rather than terraform.

Removing the private network configuration could fix the issue. I don't think it can be added with PSC at the same time. The "Authorized Network cannot be set..." error message is a bit misleading, though.

**Comment by luigi-bitonti** [comment]
> > Any resolution in place for this issue? I am also facing the same issue but I am using gcloud command rather than terraform.
> 
> Removing the private network configuration could fix the issue. I don't think it can be added with PSC at the same time. The "Authorized Network cannot be set..." error message is a bit misleading, though.

Thanks, it works.

**Comment by madhu-narisetty** [comment]
> > Any resolution in place for this issue? I am also facing the same issue but I am using gcloud command rather than terraform.
> 
> Removing the private network configuration could fix the issue. I don't think it can be added with PSC at the same time. The "Authorized Network cannot be set..." error message is a bit misleading, though.

thanks it works. I ended up with another limitation with Cloud SQL with PSC is not supported when CMEK enabled. Any thoughts on this limitation?
