### ISSUE TITLE
Cannot set labels on google_compute_forwarding_rule in v4

### ISSUE THREAD

**Issue by justinsb** [hashicorp/terraform-provider-google#16255]
Hi - we're still using v4, and it looks like we can't create google_compute_forwarding_rule with labels.

We get an error like "Invalid value for field 'resource.labels': ''. Invalid field set in Private Service Connect Forwarding Rule. This field should not be set., invalid"

AFAICT the issue is that this fix hasn't made it back to the v4 release branch:

https://github.com/hashicorp/terraform-provider-google/blob/2380027859522a4df94cfbf697cba6e3d898539d/google/services/compute/resource_compute_forwarding_rule.go#L737-L741

What's the process for backporting this to v4?  I'm happy to send a PR, but I'm not sure what backporting process is used here.

**Comment by edwardmedia** [comment]
@justinsb what version are you using? Have you tried https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.84.0?

**Comment by justinsb** [comment]
Ah - thank you @edwardmedia - I believe I was using 4.83 - let me check 4.84!

**Comment by justinsb** [comment]
You're right - seems to work great with the latest versions (and even recent versions) - thank you - I must have been using a really old version!

**Comment by justinsb** [comment]
Ah - I figured out what was going on here.  It's reproducible with the stock Private Service Connect example (adding a label), and it happens in v4 (including 4.84.0) and v5 (v5.1.0)

If we copy [this example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#example-usage---forwarding-rule-vpc-psc) and add a label to the google_compute_forwarding_rule resource then we get the message:

```
google_compute_forwarding_rule.default: Creating...
╷
│ Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Invalid field set in Private Service Connect Forwarding Rule. This field should not be set., invalid
│ 
│   with google_compute_forwarding_rule.default,
│   on main.tf line 21, in resource "google_compute_forwarding_rule" "default":
│   21: resource "google_compute_forwarding_rule" "default" {
│ 
```


Here's my tf file (I removed the project id, otherwise as-is).  Note the "foo" label !

```
terraform {
  required_providers {
    google = {
      version = "~> 5"
    }
   
  }
}


provider "google" {
  project     = "justinsb-bugs-202307"
  region      = "us-central1"
}



// Forwarding rule for VPC private service connect
resource "google_compute_forwarding_rule" "default" {
  name                    = "psc-endpoint"
  region                  = "us-central1"
  load_balancing_scheme   = ""
  target                  = google_compute_service_attachment.producer_service_attachment.id
  network                 = google_compute_network.consumer_net.name
  ip_address              = google_compute_address.consumer_address.id
  allow_psc_global_access = true
  labels = {
    "foo": "bar",
  }
}

// Consumer service endpoint

resource "google_compute_network" "consumer_net" {
  name                    = "consumer-net"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "consumer_subnet" {
  name          = "consumer-net"
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.consumer_net.id
}

resource "google_compute_address" "consumer_address" {
  name         = "website-ip-1"
  region       = "us-central1"
  subnetwork   = google_compute_subnetwork.consumer_subnet.id
  address_type = "INTERNAL"
}


// Producer service attachment

resource "google_compute_network" "producer_net" {
  name                    = "producer-net"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "producer_subnet" {
  name          = "producer-net"
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.producer_net.id
}

resource "google_compute_subnetwork" "psc_producer_subnet" {
  name          = "producer-psc-net"
  ip_cidr_range = "10.1.0.0/16"
  region        = "us-central1"

  purpose       = "PRIVATE_SERVICE_CONNECT"
  network       = google_compute_network.producer_net.id
}

resource "google_compute_service_attachment" "producer_service_attachment" {
  name        = "producer-service"
  region      = "us-central1"
  description = "A service attachment configured with Terraform"

  enable_proxy_protocol = true
  connection_preference = "ACCEPT_AUTOMATIC"
  nat_subnets           = [google_compute_subnetwork.psc_producer_subnet.name]
  target_service        = google_compute_forwarding_rule.producer_target_service.id
}

resource "google_compute_forwarding_rule" "producer_target_service" {
  name     = "producer-forwarding-rule"
  region   = "us-central1"

  load_balancing_scheme = "INTERNAL"
  backend_service       = google_compute_region_backend_service.producer_service_backend.id
  all_ports             = true
  network               = google_compute_network.producer_net.name
  subnetwork            = google_compute_subnetwork.producer_subnet.name
}

resource "google_compute_region_backend_service" "producer_service_backend" {
  name     = "producer-service-backend"
  region   = "us-central1"

  health_checks = [google_compute_health_check.producer_service_health_check.id]
}

resource "google_compute_health_check" "producer_service_health_check" {
  name     = "producer-service-health-check"

  check_interval_sec = 1
  timeout_sec        = 1
  tcp_health_check {
    port = "80"
  }
}
```

**Comment by justinsb** [comment]
In other words, it is specific to forwarding rules targeting Private Service Connect - other targets are fine.  The error message "Invalid field set in Private Service Connect Forwarding Rule" makes sense in that light.

**Comment by edwardmedia** [comment]
@justinsb the error is from the api. Not sure how much we can do at the provider level? For `Private Service Connect Forwarding Rule`, are you able to set its labels via other means?

**Comment by justinsb** [comment]
My expectation is that terraform would not pass resource.labels on creation, if doing so causes the request to be rejected.  I agree it's an annoying quirk in the API, but I think that's why people are using the terraform provider.

**Comment by edwardmedia** [comment]
@justinsb  it would be nice the provider can bring all the api rules to the front, but that is almost impossible. No matter how hard we try to implement at the provider level, you may still see the api error like this. Also the apis are evolving, and they change their rules time by time. For this case, `not pass resource.labels on creation` is on certain condition, and very specific, and seems pretty easy to avoid if that label block is removed from the config. 

@roaks3 what do you think?

**Comment by justinsb** [comment]
With the current behaviour, I don't see a declarative way to use terraform to apply labels to a PSC forwardingRule.  I have to run tf apply twice, the first time with no labels, then I edit my tf file to add labels, then I have to apply again.

If I was using imperative tooling like gcloud I agree this is easily worked around, but for terraform users this seems challenging.

**Comment by edwardmedia** [comment]
@justinsb good to know. I am going to close the ticket now. Feel free to reopen if you see the provider behaves incorrectly.

**Comment by justinsb** [comment]
Are there criteria for what is considered a bug and what is not?  If terraform users can't use functionality exposed by GCP (albeit awkwardly exposed), I would consider that a bug.

**Comment by Ziemowit-LH** [comment]
How to reopen this?

This happens with provider 5.2.0 and when the default labels are defined at provider level and there is no label block in **google_compute_forwarding_rule** itself:
```hcl
provider "google" {
  default_labels  = { mylabel = "labelvalue"}
}
resource "google_compute_forwarding_rule" "prisma_fwd" {
  ip_address            = "127.0.0.3"
  name                  = "rule"
  network               = var.project_network
  project               = var.project_id
  region                = var.region
  target                = var.private_service_connect
}
```
