### ISSUE TITLE
Increase Looker resource coverage to include resources managed by the Looker Application API

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The provider already includes the [google_looker_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/looker_instance) resource, which is managed via the Looker Admin API (https://cloud.google.com/looker/docs/reference/rest).

We've had interest from customers to increase coverage to include resources within a Looker instance that are managed via the Looker Application API (https://cloud.google.com/looker/docs/reference/looker-api/latest#versions).

([Link to comment](https://github.com/hashicorp/terraform-provider-google/issues/16259#issuecomment-1780792501) about implementing this in the Google provider vs an official, standalone Looker provider. There are [several community providers for Looker](https://github.com/search?q=terraform-provider-looker&type=repositories) currently.)

### New or Affected Resource(s)

* google_looker_project
* google_looker_folder

etc

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

b/307707470

**Comment by roaks3** [comment]
This isn't explicitly covered by `service/looker-core`, but it could potentially be forwarded to them

**Comment by SarahFrench** [comment]
I opened this issue after discussing this customer request in triage, with the intention of it being forwarded to that team for their input. I'll add the forwarding label

**Comment by efeelaiho** [comment]
@SarahFrench 

Hi, this is something that we'd like to potentially explore. The team is very new to developing the terraform provider, so may I request some doc as to how to create resources that are not part of One Platform? as I believe that'll be our main blocker. Also these resources within a Looker instance are not  Cloud IAM managed

**Comment by SarahFrench** [comment]
👋 Hi @efeelaiho

When we discussed this request in triage we agreed that managing resources inside a Looker instance is something that would preferably not be added to the Google provider, and instead be managed by an official Looker Terraform provider. Like you said, managing resources within a Looker instance would require a different type of authentication and that's a good sign that separate providers is the answer.  

There are existing Looker provider projects out there ([example](https://registry.terraform.io/providers/devoteamgcloud/looker/latest), [example](https://registry.terraform.io/providers/DevotedHealth/looker/latest)) but none are official providers.

I'm a HashiCorp employee, not Google, so I'll tag @rileykarson here in case this work needs more discussion internally.

**Comment by rileykarson** [comment]
I responded w/ some additional context on the internal-to-Google bug.

**Comment by rileykarson** [comment]
The internal issue has been closed as wontfix by the service team, so closing this as well.
