### ISSUE TITLE
google_compute_forwarding_rule description (with PSC) forces recreation on every tf apply

### ISSUE THREAD

**Issue by justinsb** [hashicorp/terraform-provider-google#16258]
Setting a description on a google_compute_forwarding_rule (with PSC) appears to force resource re-creation:

Adding a description in the [example from the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#example-usage---forwarding-rule-vpc-psc):

```
resource "google_compute_forwarding_rule" "default" {
  name                    = "psc-endpoint"
  description             = "My description"
  region                  = "us-central1"
  load_balancing_scheme   = ""
  target                  = google_compute_service_attachment.producer_service_attachment.id
  network                 = google_compute_network.consumer_net.name
  ip_address              = google_compute_address.consumer_address.id
  allow_psc_global_access = true
}
```

That can be applied once, causing the resource to be created.  But a second tf apply (with no changes to the tf file) causes a plan that includes deletion/recreation, because of description:

```
  # google_compute_forwarding_rule.default must be replaced
-/+ resource "google_compute_forwarding_rule" "default" {
      - all_ports               = false -> null
      - allow_global_access     = false -> null
      + base_forwarding_rule    = (known after apply)
      ~ creation_timestamp      = "2023-10-16T09:32:38.274-07:00" -> (known after apply)
      + description             = "My description" # forces replacement
...

Plan: 1 to add, 0 to change, 1 to destroy.
```

`gcloud compute forwarding-rules describe psc-endpoint --region us-central1` does not include the description, so it looks like it got lost somewhere in the creation flow.

(Related to #16255, but I think a different underlying issue)

**Comment by edwardmedia** [comment]
@justinsb looks like this is a dup of https://github.com/hashicorp/terraform-provider-google/issues/16195
