### ISSUE TITLE
Allow API gateway to pull OpenAPI spec from URL along with file

### ISSUE THREAD

**Issue by mephmanx** [hashicorp/terraform-provider-google#16253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to get an enhancement to the API Gatway terraform resource to allow the use of url hosted openapi specs.  I have Cloud Run Resources that generate their OpenAPI specs and I would like to have the terraform API Gateway resource pull from the URL's instead of having to load files into the terraform git repo.

### New or Affected Resource(s)

google_api_gateway_api_config

* google_XXXXX

### Potential Terraform Configuration

resource "google_api_gateway_api_config" "api_cfg" {
  provider = google-beta
  api = google_api_gateway_api.api_cfg.api_id
  api_config_id = "my-config"

  openapi_documents {
    document {
      path = "spec.yaml"
      contents = url("https://spec.com/openapi.yaml")
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
We'd recommend using something like the [`http datasource`](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http) for a flow like this!

**Comment by mephmanx** [comment]
Or, I wasnt able to get it to work.  I could be using it wrong.....  I havent used terraform for that long...
