### ISSUE TITLE
In cmd.exe Terraform isn't ignore quotes in env. variable value

### ISSUE THREAD

**Issue by mogol07** [hashicorp/terraform-provider-google#16278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.6.1                                                                                                                       
on windows_amd64                                                                                                                       
+ provider registry.terraform.io/hashicorp/google v5.2.0

### Terraform Configuration Files

in cmd.exe I executed
`set GOOGLE_APPLICATION_CREDENTIALS="credentials.json"`

### Debug Output
during `terraform -init` I got an error

`Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open "credentials.json": The filename, directory name, or volume label syntax is incorrect.`

### Expected Behavior

Terraform read file with service user credentials and successfully completed initialization.

```
Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...

Initializing provider plugins...
- Finding latest version of hashicorp/google...
- Installing hashicorp/google v5.2.0...
- Installed hashicorp/google v5.2.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
```

### Actual Behavior

I got an error (see above)

### Steps to Reproduce

1. Define variable in cmd.exe with quotes mark in filename (for example if path included )
2. Run `terraform -init` 

### Important Factoids

I found workaround. If I remove a quote marks, then terraform is completed successfully.
But using quotes are required if your path are included space, for example.

I don't test in PowerShell or Bash subsystem, but I don't see any notes about such behavior in CMD.exe shell.

**Comment by edwardmedia** [comment]
@mogol07 do you have a specific use case when you have to have the quotes?

**Comment by edwardmedia** [comment]
@mogol07 glad you figure it out. In term of `it worth to mention in documentations`, I guess you refer to the section [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication-configuration), what exactly you suggest to make it clearer?

**Comment by mogol07** [comment]
Honestly, I guess maybe it's more suitable in https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/common_issues 
But as I understand, this issue isn't "frequent" question. I don't very familiar with Terraform documentation. If exists something like "system requirements (and in Windows section mentions about limited compatibility with cmd.exe)" or "know issues"? 

In worst case we could close this issue. Because before I couldn't find any information about such "strange" behavior, but now it could be found in this tracker with work-around.

**Comment by edwardmedia** [comment]
Cool. Let's close this now. Thank you for filing the issue
