### ISSUE TITLE
v5 upgrade `Error: no schema available for google_firebase_project_location while reading state; this is a bug in Terraform and should be reported`

### ISSUE THREAD

**Issue by gojanpaolo** [hashicorp/terraform-provider-google#16280]
We upgraded to v5 and followed the guide: https://registry.terraform.io/providers/hashicorp/google/4.84.0/docs/guides/version_5_upgrade

We've removed `google_firebase_project_location` in our .tf file and replaced them with the new resource types and ran `terraform import` for those new resource types.
But we still get the following error on `terraform plan`
```
Error: no schema available for module.dev.google_firebase_project_location.prism while reading state; this is a bug in Terraform and should be reported
```

We use gcp storage bucket to store our terraform state.

Do we need to run `terraform state rm module.dev.google_firebase_project_location.prism` as well? If yes, I think that should be included in the guide.

**Comment by edwardmedia** [comment]
@gojanpaolo I guess you shouldn't run `rm` for the upgrade. It is not clear what went wrong in your case. Are you able to provide a config and the steps that I can use to repro the issue?

**Comment by edwardmedia** [comment]
@gojanpaolo is this still an issue?

**Comment by rainshen49** [comment]
I think @gojanpaolo  is right, we need to add a `terraform state rm module.dev.google_firebase_project_location.<label>` step in the guide. I'll patch a PR for this.

For context, my original idea in https://github.com/GoogleCloudPlatform/magic-modules/pull/8783#pullrequestreview-1613700114 was to deprecate and then remove the resouce in 6.X.X instead, but forgot to update documentation after reviewer feedback.

**Comment by gojanpaolo** [comment]
Hello! Sorry for the late response. We ran `terraform state rm ...` to unblock us from upgrading so not necessarily an issue anymore on our end but I believe others may encounter the same. Thanks!
