### ISSUE TITLE
Security Command Center Custom Module for Event Thread Detection

### ISSUE THREAD

**Issue by steffencircle** [hashicorp/terraform-provider-google#16294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Version 5.0.0 of the provider introcuded these new resources:

- google_scc_organization_custom_module
- google_scc_folder_custom_module
- google_scc_folder_custom_module

While they sound quite generic, those resources are currently only working for SHA (Secure Health Analytics).

We would like to use the same mechanism to be able to create a Custom Module for Event Thread Detection (ETD).
The related API for the Org resource can be found here https://cloud.google.com/security-command-center/docs/reference/rest/v1/organizations.eventThreatDetectionSettings.customModules/create

### New or Affected Resource(s)

* google_scc_organization_custom_module
* google_scc_folder_custom_module
* google_scc_folder_custom_module

### References

* b/306108528

**Comment by rileykarson** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/9509
