### ISSUE TITLE
Failing test(s): TestAccDataproc*

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#16313]
### Failure rates

- flaky since 09/29

### Impacted tests

- TestAccDataproc*

### Affected Resource(s)

* google_dataproc_cluster

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleBeta_NightlyTests_GOOGLEBETA_PACKAGE_DATAPROC?mode=builds)

### Message(s)

```
Error: Error waiting for creating Dataproc cluster: Error code 3, message: The resource 'projects/xxxxxxx/regions/us-central1/subnetworks/default' is not ready

```

**Comment by shuyama1** [comment]
We retry such error with error code 400. https://github.com/hashicorp/terraform-provider-google/blob/3cfedbb9f6e8b020ed3ff94179ce631ee92aefc2/google/transport/error_retry_predicates.go#L120 We can ask service team to fix the error code.

Meanwhile, I'll switch to use bootstrapped network instead of the default one for dataproc tests

**Comment by melinath** [comment]
Looks like this is resolved.
