### ISSUE TITLE
Ability to set a cloud function as a blocking auth function.  ( beforeCreate or beforeSignIn)

### ISSUE THREAD

**Issue by EduardJoy** [hashicorp/terraform-provider-google#16339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I think we would benefit from being able to set a cloud function as a blocking cloud function for firebase authentication.
Tradintionally this is done through either Identity Platform or Firebase Console
![image](https://github.com/hashicorp/terraform-provider-google/assets/58823388/faaefb19-ac66-4d88-a9e9-5a4b67b75864)

### New or Affected Resource(s)

Google Cloud Functions / Google identity platform / Firebase

b/308569675

**Comment by rileykarson** [comment]
Looks like part of `google_identity_platform_config` based on https://cloud.google.com/identity-platform/docs/reference/rest/v2/Config#BlockingFunctionsConfig

**Comment by ymonte** [comment]
The team is working on getting this updated in the Firebase docs, but the beta feature you are looking for is available I believe. Check out: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/identity_platform_config

**Comment by EduardJoy** [comment]
Thank you @ymonte ! This is exactly what I have been searching for!

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8402
