### ISSUE TITLE
Vertex Workbench Instance

### ISSUE THREAD

**Issue by tSte** [hashicorp/terraform-provider-google#16336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

If I understand correctly, current TF provider allows to create Vertex user-managed notebook (the `google_notebooks_instance`) and Google-managed notebook (`google_notebooks_runtime`). But does not seem to provide option to spawn [Vertex AI Workbench Instances](https://cloud.google.com/vertex-ai/docs/workbench/instances/introduction).

### New or Affected Resource(s)

* google_workbench_instance

### Potential Terraform Configuration

```tf
resource "google_workbench_instance" "default" { ... }
```

### References

* https://cloud.google.com/sdk/gcloud/reference/workbench/instances/create

b/303442493

**Comment by bcreddy-gcp** [comment]
I am currently working on it. Here's the fork: https://github.com/GoogleCloudPlatform/magic-modules/compare/main...bcreddy-gcp:magic-modules:new_wbi
