### ISSUE TITLE
The terraform-provider-google_v5.3.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by Programproductions** [hashicorp/terraform-provider-google#16343]
Hi I ran a plan out today only to get the following message. I was using 4.8 and have tried upgrading and init on 5.3.0 but made no difference. None of my cloud functions will deploy they all have the Error Request cancelled.

steps to reproduce:
terraform plan -out plan.out -var-file=dev.tfvars 

 Error: Request cancelled
│
│   with google_cloudfunctions_function.user_sso,
│   on cf-user-sso.tf line 4, in resource "google_cloudfunctions_function" "user_sso":
│    4: resource "google_cloudfunctions_function" "user_sso" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-google_v5.3.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "1698107804964847": value out of range

goroutine 1284 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x17bee460, {0x18094ce8, 0x1, 0x1}, 0x8)    
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x17bee460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x172217a0, {{{0x4305fa0, 0x1747bcc0}}, {0x36cb180, 0x174f9060}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x17475a80, {0x43058c0, 0x1770dfe0}, 0x171e54c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x17445d00, 0x17445d40, {0x178aa200, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x16d963c0, {0x43058c0, 0x1770c4f8}, 0x176d8b40)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x3bb21e0, 0x16d963c0}, {0x43058c0, 0x1770c4f8}, 0x16fc2380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a      
google.golang.org/grpc.(*Server).processUnaryRPC(0x178ae360, {0x430a3cc, 0x178ae000}, 0x179900a0, 0x178a7ae8, 0x5acbd88, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xf03
google.golang.org/grpc.(*Server).handleStream(0x178ae360, {0x430a3cc, 0x178ae000}, 0x179900a0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-google_v5.3.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@Programproductions this could be a known issue. Take a look at [this](https://github.com/hashicorp/terraform-provider-google/issues/15676) to see if that make sense. 

Unfortunately we don't have a lot of options to work around this, as it's a restriction at the SDK level

See https://github.com/hashicorp/terraform-plugin-sdk/issues/1236

**Comment by edwardmedia** [comment]
Cool. Glad you found the solution. Close this now
