### ISSUE TITLE
Seemingly spurious changes reported with google_compute_instance_template if only a trivial change is made

### ISSUE THREAD

**Issue by KKamishima** [hashicorp/terraform-provider-google#16353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Our system uses Managed Instance Group to host a fleet of containerized service agents. When I try to upgrade the container image for the agent, the only change necessary is about `"image"` property in `"gce-container-declaration"` metadata.

However, when I run `terraform plan`, I get a lot of changes unrelated to the one I made.

Excepts from the output of `terraform plan` (partly redacted):
```
  # module.***.google_compute_instance_template.main must be replaced
+/- resource "google_compute_instance_template" "main" {
      ~ id                   = "projects/***/global/instanceTemplates/***-instance-template20231018##########00000003" -> (known after apply)
      ~ metadata             = { # forces replacement
          ~ "gce-container-declaration"    = <<-EOT
                "spec":
                  "containers":
...
              -     "image": "asia-northeast1-docker.pkg.dev/***/***/***:vTEST"
              +     "image": "asia-northeast1-docker.pkg.dev/***/***/***:v20231020"
                  "restartPolicy": "Always"
                  "volumes": []
            EOT
            # (4 unchanged elements hidden)
        }
      ~ metadata_fingerprint = "********" -> (known after apply)
      ~ name                 = "***-instance-template20231018##########00000003" -> (known after apply)
      ~ region               = "asia-northeast1" -> (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/v1/projects/***/global/instanceTemplates/***-instance-template20231018##########00000003" -> (known after apply)
      ~ self_link_unique     = "https://www.googleapis.com/compute/v1/projects/***/global/instanceTemplates/***-instance-template20231018##########00000003?uniqueId=#########" -> (known after apply)
      - tags                 = [] -> null
      + tags_fingerprint     = (known after apply)
        # (7 unchanged attributes hidden)

      ~ disk {
          ~ interface         = "SCSI" -> (known after apply)
          - labels            = {} -> null
          ~ provisioned_iops  = 0 -> (known after apply)
          - resource_policies = [] -> null
            # (8 unchanged attributes hidden)
        }

      ~ network_interface {
          ~ internal_ipv6_prefix_length = 0 -> (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          ~ name                        = "nic0" -> (known after apply)
          - queue_count                 = 0 -> null
          ~ subnetwork                  = "https://www.googleapis.com/compute/v1/projects/***/regions/asia-northeast1/subnetworks/***-subnet" -> "***-subnet"
          ~ subnetwork_project          = "***" -> (known after apply)
            # (2 unchanged attributes hidden)
        }

      ~ scheduling {
          - min_node_cpus       = 0 -> null
            # (4 unchanged attributes hidden)
        }

        # (4 unchanged blocks hidden)
    }
```

I understand that it is due to the fact that Instance Templates are immutable and always needs to be replaced, not updated in place, and this is the way how Terraform works in general when the resource is about to be replaced.

However, these unrelated changes give me a headache while reviewing the output to see if there are no unintended changes.

I believe it defies the purpose of `terraform plan` and would like a way to mitigate it.

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

(omitted)

### References

* none

**Comment by rileykarson** [comment]
The issue here has to do with how unknown fields work- on a recreate their new value becomes unknown or "(known after apply)" again, and they are re-proposed no matter what. This is not something we can resolve in the provider.
