### ISSUE TITLE
Support resource_manager_tags for Instance Groups

### ISSUE THREAD

**Issue by Davide95** [hashicorp/terraform-provider-google#16356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, resource_manager_tags are supported [for VMs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#resource_manager_tags) but not [for Instance Groups](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template).
In some scenarios, this prevents set custom rules with the granularity of an Instance Group. Specifically, some roles cannot be applied with IAM conditions, hence they require the use of tags

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

It can be implemented in the same way as we do [for VMs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#resource_manager_tags)

b/308756069

**Comment by rileykarson** [comment]
Note that https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/tags_tag_binding can be used on arbitrary resources. The `resource_manager_tags` field will authoritatively manage the set of tags applied to the resource when set, as a one-time action by the API. It does **not** manage the state of the tags indefinitely.

**Comment by LucaPrete** [comment]
Working on this. PR coming

**Comment by LucaPrete** [comment]
The [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/9612) is finally ready for review!
