### ISSUE TITLE
Regression with `google_monitoring_alert_policy` "An aggregation cannot have group-by fields without a reducer."

### ISSUE THREAD

**Issue by macksclark** [hashicorp/terraform-provider-google#16366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.9

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "<name>" {
  project      = module.project.project_id
  display_name = "<display>"
  combiner     = "OR"
  conditions {
    display_name = "<name>"
    condition_threshold {
      filter = "metric.type=\"dataflow.googleapis.com/job/user_counter\" metric.labels.metric_name=\"fhirio/execute_bundle_error_count\" resource.type=\"dataflow_job\" resource.labels.project_id=\"${module.project.project_id}\" resource.labels.job_name=has_substring(\"{{.recon_pipeline_name}}\")"
      aggregations {
        alignment_period     = "60s"
        per_series_aligner   = "ALIGN_MAX"
        cross_series_reducer = "REDUCE_SUM"
        group_by_fields = [
          "resource.label.\"job_name\"",
          "metric.label.\"job_id\""
        ]
      }
      denominator_filter = "metric.type=\"dataflow.googleapis.com/job/user_counter\" (metric.labels.metric_name=\"fhirio/execute_bundle_error_count\" OR metric.labels.metric_name=\"fhirio/execute_bundle_success_count\") resource.type=\"dataflow_job\" resource.labels.project_id=\"${module.project.project_id}\" resource.labels.job_name=has_substring(\"{{.recon_pipeline_name}}\")"
      denominator_aggregations {
        alignment_period     = "60s"
        per_series_aligner   = "ALIGN_MAX"
        cross_series_reducer = "REDUCE_SUM"
        group_by_fields = [
          "resource.label.\"job_name\"",
          "metric.label.\"job_id\""
        ]
      }
      comparison      = "COMPARISON_GT"
      threshold_value = 0.001
      duration        = "0s"
      trigger {
        count = 1
      }
    }
  }
```

### Debug Output
N/a

### Expected Behavior

Since there is a cross_sum_reducer in both my aggregations, this should have deployed properly.

### Actual Behavior

Failure to deploy the alerting resources:
```
Step #2 - "Apply": │ Error: Error creating AlertPolicy: googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.aggregations[0].cross_series_reducer had an invalid value of "An aggregation cannot have group-by fields without a reducer.".
Step #2 - "Apply": │ 
Step #2 - "Apply": │   with google_monitoring_alert_policy.<name>,
Step #2 - "Apply": │   on alerts.tf line 665, in resource "google_monitoring_alert_policy" "<name>":
Step #2 - "Apply": │  665: resource "google_monitoring_alert_policy" "<name>" {
Step #2 - "Apply": │ 
```

The error message seems to indicate I am missing a reducer, but as mentioned in the expected behaviour, I have a cross_sum_reducer in my aggregation alongside the group by fields.

### Steps to Reproduce

1. `terraform apply` with my config above

### Important Factoids
N/a

### References
Don't see any related issues. I believe issue started around 11pm EST Oct 24th 2023.

b/307911389

**Comment by melinath** [comment]
@macksclark I'm not able to reproduce this issue - I can successfully apply your configuration using Terraform 1.5.6 / google provider 5.3.0. Based on the fact that you didn't change your configuration and also that the error message is a `googleapi: Error 400`, this seems like it would have to be due to an API change - possibly in the early stages of rollout.

If you add [TF_LOG=DEBUG to your terraform command](https://developer.hashicorp.com/terraform/internals/debugging), you can check the exact HTTP requests/responses, which may contain additional information.
