### ISSUE TITLE
Initializing provider plugins... - Finding latest version of hashicorp/ggoogle...

### ISSUE THREAD

**Issue by qarik-cmcgill** [hashicorp/terraform-provider-google#16371]
Typo by Hashicorp on provider Initializing provider plugins...
- Finding latest version of hashicorp/ggoogle... causing it to fail to pull provider.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@qarik-cmcgill I am not clear what the issue is. Can you detail where to start to look at?

**Comment by qarik-cmcgill** [comment]
terraform init is failing.  From below its trying to download provider │ provider named registry.terraform.io/hashicorp/ggoogle using ggoogle instead of google, this looks like a typo but not in my config.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.3.0"...
- Finding latest version of hashicorp/ggoogle...
- Installing hashicorp/google v5.3.0...
- Installed hashicorp/google v5.3.0 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/ggoogle: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/ggoogle
│ 
│ All modules should specify their required_providers so that external
│ consumers will get the correct providers when using a module. To see which
│ modules are currently depending on hashicorp/ggoogle, run the following
│ command:
│     terraform providers
╵

**Comment by qarik-cmcgill** [comment]
terraform {
  required_version = "~> 1.6.2"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "5.3.0"
    }
  }
}

provider "google" {
  project = var.gcp_project
  region  = var.gcp_region
  zone    = var.gcp_zone
}

**Comment by qarik-cmcgill** [comment]
Resolved
