### ISSUE TITLE
terraform_labels can't be updated on google_compute_instance_template

### ISSUE THREAD

**Issue by khtelus** [hashicorp/terraform-provider-google#16374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.2
on linux_amd64
```

Provider version 5.3.0

### Affected Resource(s)

* `google_compute_instance_template`

### Terraform Configuration Files

```tf
 resource "google_compute_instance_template" "default" {
   project              = var.project_id
   name_prefix          = "my-host-template-"
   machine_type         = var.instance_template.machine_type
   region               = var.region
   can_ip_forward       = false
   tags                 = var.tags

   disk {
     boot         = true
     source_image = data.google_compute_image.default.self_link
     disk_type    = "pd-balanced"
     disk_size_gb = data.google_compute_image.default.disk_size_gb
   }

   network_interface {
     subnetwork         = var.subnet
     subnetwork_project = var.vpc_host_project == null ? var.project_id : var.vpc_host_project
   }

   service_account {
     email  = var.instance_template.service_account_email
     scopes = ["cloud-platform"]
   }

   metadata = {
     enable-oslogin  = "TRUE"
     enable-osconfig = "TRUE"
   }

   lifecycle {
     create_before_destroy = true
   }

   labels = var.labels
 }
```

### Expected Behavior

With `create_before_destroy` set to `true` as per the configuration a new template should be created on update (in this case to `terraform_labels`) and then the deposed object deleted.

### Actual Behavior

Errors out with `Error: doesn't support update`

```
Step #1 - "terraform-apply":   # module.my_hosts.google_compute_instance_template.default will be updated in-place
Step #1 - "terraform-apply":   ~ resource "google_compute_instance_template" "default" {
Step #1 - "terraform-apply":         id                   = "projects/my-project/global/instanceTemplates/my-host-template-20230320160805321300000001"
Step #1 - "terraform-apply":         name                 = "my-host-template-20230320160805321300000001"
Step #1 - "terraform-apply":         tags                 = [
Step #1 - "terraform-apply":             "tag-a",
Step #1 - "terraform-apply":             "tag-b",
Step #1 - "terraform-apply":         ]
Step #1 - "terraform-apply":       ~ terraform_labels     = {
Step #1 - "terraform-apply":           + "applicationgroup"   = "appgroup"
Step #1 - "terraform-apply":           + "contact"            = "admins_at_domain_dot_com"
Step #1 - "terraform-apply":           + "costcenter"         = "1122334455"
Step #1 - "terraform-apply":           + "dataclassification" = "tbd"
Step #1 - "terraform-apply":           + "env"                = "np"
Step #1 - "terraform-apply":         }
Step #1 - "terraform-apply":         # (12 unchanged attributes hidden)
Step #1 - "terraform-apply": 
Step #1 - "terraform-apply":         # (4 unchanged blocks hidden)
Step #1 - "terraform-apply":     }
Step #1 - "terraform-apply": 
Step #1 - "terraform-apply": Plan: 0 to add, 3 to change, 0 to destroy.
Step #1 - "terraform-apply": module.my_hosts.google_compute_instance_template.default: Modifying... [id=projects/my-project/global/instanceTemplates/my-host-template-20230320160805321300000001]
Step #1 - "terraform-apply": ╷
Step #1 - "terraform-apply": │ Error: doesn't support update
Step #1 - "terraform-apply": │ 
Step #1 - "terraform-apply": │   with module.my_hosts.google_compute_instance_template.default,
Step #1 - "terraform-apply": │   on .terraform/modules/my_hosts/main.tf line 70, in resource "google_compute_instance_template" "default":
Step #1 - "terraform-apply": │   70: resource "google_compute_instance_template" "default" {
Step #1 - "terraform-apply": │ 
Step #1 - "terraform-apply": ╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by zli82016** [comment]
Sorry for the issue. @khtelus, can you please confirm that are you trying to upgrade the provider from 4.x to 5.3.0? And also can you please provide the value of `var.labels`? Thanks.

**Comment by khtelus** [comment]
Thanks @zli82016 the provider (and my remote state) has already been upgraded unfortunately. Had I known, would have pinned to last v4....

Value of `var.labels` in this case is exactly the same as `terraform_labels` in example above. So `var.labels` would be:

```
labels = {
  "env"                = "np",
  "contact"            = "admins_at_domain_dot_com",
  "costcenter"         = "1122334455",
  "applicationgroup"   = "appgroup",
  "dataclassification" = "tbd"
}
```

Thanks!

**Comment by zli82016** [comment]
The workaround could be to make some other change- such as adding a new label or modifying the existing one to make the update success.

**Comment by khtelus** [comment]
> The workaround could be to make some other change- such as adding a new label or modifying the existing one to make the update success.

This does indeed appear to be a workaround @zli82016 - if I add a "test" tag running a `plan` step changes the expected operation on the instance group to a `replace` vs. an `updated in-place`.

**Comment by khtelus** [comment]
@zli82016 I think one of the keys points here is - I don't want to change my template. Changing the template will of course in turn force re-creation of the VM instances based on this template. So adding another change (such as another label or a tag for example) to workaround this change is undesirable in my case...

**Comment by zli82016** [comment]
The PR [9394](https://github.com/GoogleCloudPlatform/magic-modules/pull/9394) made the fix to the resource `google_compute_instance_template` by adding an empty update method without resource recreation to make the provider upgrade succeed.

**Comment by saurabh21316** [comment]
@zli82016 @khtelus 

I know this issue is closed but I would appreciate if someone can please help. 
terraform plan: 

# module.ComputeInstance.google_compute_instance.mon_prod_esnode_c will be updated in-place
  ~ resource "google_compute_instance" "mon_prod_esnode_c" {
        id                   = "projects/production-colony/zones/northamerica-northeast1-c/instances/mon-prod-esnode-c"
        name                 = "mon-prod-esnode-c"
        tags                 = [
            "allow-healthchecks",
            "mon-prod-esnode",
        ]
      ~ terraform_labels     = {
          + "allow-healthchecks" = (known after apply)
          + "mon-prod-esnode"    = (known after apply)
        }
        # (18 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }

when run terraform apply, it doesn't throw any error and running terraform plan again it shows the same output

**Comment by zli82016** [comment]
Hello, @saurabh21316 , can you please provide more details how to reproduce this issue? Which provider version does it happen? Does it happen when upgrading the provider from 4.x to 5.x? Thanks.
