### ISSUE TITLE
google_composer_environment tests have naming collisions for networks

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#16380]
# Background

The tests generated for `google_composer_environment` are designed to be run in parallel, but the code that generates them in magic modules currently uses network names generated with `RandInt` [like so](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/composer/resource_composer_environment_test.go.erb#L463).

Doing this can cause naming collisions if the tests are run in parallel, as happened in [this pre-submit run](https://github.com/GoogleCloudPlatform/magic-modules/pull/9341#issuecomment-1777218682)

I believe the simplest fix would be to add a short string differentiating each network name from the others, so on L463 we would have:
```
network := fmt.Sprintf("%s-a-%d", testComposerNetworkPrefix, acctest.RandInt(t))
```
This may require limiting the length of the RandInt by making it, like so:
```
network := fmt.Sprintf("%s-a-%x", testComposerNetworkPrefix, acctest.RandInt(t))
```
or by truncating it, like so:
```
network := fmt.Sprintf("%s-a-%7d", testComposerNetworkPrefix, acctest.RandInt(t))
```

# What kind of contribution is this issue about?

* MMv1-based resource

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/9341

# Details

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/composer/resource_composer_environment_test.go.erb#L463

**Comment by rileykarson** [comment]
Collisions seem unlikely, and we're not sure that mitigating is worth doing until we see a pattern. Closing for now.
