### ISSUE TITLE
The default value of unique_writer_identity in the google_logging_project_sink resource has changed from false to true in the 5.3 version was this change intended ?

### ISSUE THREAD

**Issue by fr12k** [hashicorp/terraform-provider-google#16428]
I would suspect this kind of change happening in a major version release for example v5 but not in a minor release v5.3.

But its just an observation.

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@fr12k I do see [that change](https://github.com/hashicorp/terraform-provider-google/pull/15743) in [v5.0.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0), and no since then. 

Where did you see the change in v5.3?

**Comment by edwardmedia** [comment]
@fr12k is this still an issue (or question)?

**Comment by edwardmedia** [comment]
@fr12k closing assuming this is no longer a question

**Comment by fr12k** [comment]
Hi @edwardmedia, how you're doing ?

Sorry for the late response. The Release Notes of 5.0.0 clearly mention this change. But in the `logging_project_sink` resource documentation the changes is happening between the version 5.2.0 and 5.3.0.

https://registry.terraform.io/providers/hashicorp/google/5.2.0/docs/resources/logging_project_sink

> [unique_writer_identity](https://registry.terraform.io/providers/hashicorp/google/5.2.0/docs/resources/logging_project_sink#unique_writer_identity) - (Optional) Whether or not to create a unique identity associated with this sink. If false (the default), then the writer_identity used is serviceAccount:cloud-logs@system.gserviceaccount.com. If true, then a unique service account is created and used for this sink. If you wish to publish logs across projects or utilize bigquery_options, you must set unique_writer_identity to true.

https://registry.terraform.io/providers/hashicorp/google/5.3.0/docs/resources/logging_project_sink  

>  [unique_writer_identity](https://registry.terraform.io/providers/hashicorp/google/5.3.0/docs/resources/logging_project_sink#unique_writer_identity) - (Optional) Whether or not to create a unique identity associated with this sink. If false, then the writer_identity used is serviceAccount:cloud-logs@system.gserviceaccount.com. If true (the default), then a unique service account is created and used for this sink. If you wish to publish logs across projects or utilize bigquery_options, you must set unique_writer_identity to true.

Have a nice day.
