### ISSUE TITLE
Data Source google_client_openid_userinfo does not return value after provider version 4.58.0

### ISSUE THREAD

**Issue by avlind** [hashicorp/terraform-provider-google#16431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform `v1.6.3`

### Affected Resource(s)

* google_client_openid_userinfo

### Terraform Configuration Files

```tf
data "google_client_openid_userinfo" "me" {}

output "userinfo" {
  value = data.google_client_openid_userinfo.me.email
}
```

### Expected Behavior

Expect to get a Terraform output of the executing identity's email property.

### Actual Behavior

When using the Google provider version `4.58.0` and earlier, the TF configuration outputs a string w/ the email of the executing user. When I update to Google provider version `4.59.0` I received an error suggesting I don't have the appropriate API scopes assigned, and from Google provider version `4.60` -> `Current (5.4.0)` the output is returned empty, with no errors.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Testing has been done executing as a user, directly from GCP Cloud Shell. 

### References

* N/A

**Comment by edwardmedia** [comment]
@avlind it works fine with me for v5.4.0. What specific version are you using? I also checked the source code, and I don't see any change that could contributed this issue.

**Comment by avlind** [comment]
@edwardmedia - Here is a [gist of the output](https://gist.github.com/avlind/e7dac6af53b93eb34e344d41cc1e41e1).

Additionally, the terraform configuration files I am using for my sandbox testing have been uploaded to dedicated repo for at [this location](https://github.com/avlind/googletf-issue-16431/).

### Steps to Reproduce:

1. Launch GCP CloudShell
2. In Cloud Shell Run:
```
git clone https://github.com/avlind/googletf-issue-16431.git
cd googletf-issue-16431/
Terraform init
Terraform apply
```
3. You should get a successful output, as this is using version `4.58.0`
>Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
>
>Outputs:
>
> userinfo = "username@fqdn.com"
4. Comment line 7 and uncomment line 8 of `version.tf` to swap the provider version being referenced to `5.4.0`
5. Back in Cloud Shell Run:
```
terraform init -upgrade
terraform state rm data.google_client_openid_userinfo.me
terraform  apply
```
6. Output
>Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
>
>Outputs:
>
> userinfo = ""

**Comment by edwardmedia** [comment]
@avlind from the log, you may see below error. when you use v5.4.0. Go back to review if the runner has a proper identity.

```
 {
   "error": {
     "code": 403,
     "message": "User must be authenticated when user project is provided",
     "status": "PERMISSION_DENIED",
     "details": [
       {
         "@type": "type.googleapis.com/google.rpc.ErrorInfo",
         "reason": "USER_PROJECT_DENIED",
         "domain": "googleapis.com",
         "metadata": {
           "service": "openidconnect.googleapis.com",
           "consumer": "projects/newtftest"
         }
       }
     ]
   }
 }
```

**Comment by edwardmedia** [comment]
@avlind does [this](https://github.com/hashicorp/terraform-provider-google/issues/16431#issuecomment-1792425258) make sense to you? I believe the change you made may remove/change the terraform runner account. It is not related to the data source.

**Comment by edwardmedia** [comment]
@avlind closing as the error is clearly not about the data source

**Comment by edwardmedia** [comment]
Reopen per @avlind request. 

Please share the debug log with v5.x 

```tf
data "google_client_openid_userinfo" "me" {}

output "userinfo" {
  value = data.google_client_openid_userinfo.me.email
}
```

**Comment by avlind** [comment]
Debug Log for 5.4: https://gist.github.com/avlind/903864ad528ced1d7b392d13d315affb
Debug Log for 4.58: https://gist.github.com/avlind/453103fe13806e1cd5f0d38e62231f3c

**Comment by edwardmedia** [comment]
@avlind can you run the scripts in a VM?

**Comment by edwardmedia** [comment]
Closing this as @avlind has verified no issues if the scripts are run on a VM.
