### ISSUE TITLE
 google_secret_manager_secret_version.name output returns same value as google_secret_manager_secret_version.id

### ISSUE THREAD

**Issue by wesleung** [hashicorp/terraform-provider-google#16438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v1.6.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v4.84.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Affected Resource(s)

google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret-version"
  replication {
    auto {}
  }
}


resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.id
  secret_data = "secret-data"
}

output "admin_password_id" {
  value = google_secret_manager_secret_version.secret-version-basic.id
}
output "admin_password_name" {
  value = google_secret_manager_secret_version.secret-version-basic.name
}
```

### Debug Output

```
admin_password_id = "projects/###########/secrets/secret-version/versions/2"
admin_password_name = "projects/##########/secrets/secret-version/versions/2"

```

### Expected Behavior

admin_password_name = "secret-version"

### Actual Behavior

admin_password_name = "projects/##########/secrets/secret-version/versions/2"

### Steps to Reproduce

Run the above terraform

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@wesleung [name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version#name) is a readonly field, which is given by the api. There is not much we can do at the provider level.

Where did you see it should be something like below format?

```
admin_password_name = "secret-version"
```

**Comment by wesleung** [comment]
Documentation: id and name values should actually be flipped https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version

```
Attributes Reference
In addition to the arguments listed above, the following computed attributes are exported:

id - an identifier for the resource with format {{name}}

name - The resource name of the SecretVersion. Format: projects/{{project}}/secrets/{{secret_id}}/versions/{{version}}
```

**Comment by edwardmedia** [comment]
@wesleung can you share the state ( terraform show ) after it is created?

**Comment by edwardmedia** [comment]
@wesleung the api only returns name, not id. The id value is manufactured in the provider to match most common practices for other resources.

Can you share the debug log and see what the api returned response looks like?

**Comment by wesleung** [comment]
Here's the log

[tf_debug.log](https://github.com/hashicorp/terraform-provider-google/files/13253371/tf_debug.log)

The docs says {{name}} which IMHO meant the name of the secret.  But since this is the secret version, I guess it doesn't have to be the name of the secret. Not the end of the world for me, can close this ticket as Not Planned

**Comment by edwardmedia** [comment]
@wesleung sorry this might be a little confusion. Below is part of your log. You may see the format of its name given by the api. Yes, this is the version of secret, not the secret itself. Having a name like `secret-version` might be difficult.

```
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5: {
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5:   "name": "projects/#############/secrets/secret-version/versions/1",
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5:   "payload": {
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5:     "data": "c2VjcmV0LWRhdGE=",
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5:     "dataCrc32c": "4166372523"
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5:   }
2023-11-03T11:01:37.397-0700 [DEBUG] provider.terraform-provider-google_v5.4.0_x5: }
```
