### ISSUE TITLE
Upstream API issue with google_storage_insights_report_config

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#16443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

google_storage_insights_report_config

### Expected Behavior

Enabling the storage insights API should create the storage insights SA

### Actual Behavior

Storage insights SA is not created until you click on "create report configuration" in the GUI, hence it's not possible to create a storage insights config via Terraform at this time without having to also use the GUI.

### Steps to Reproduce

Create a new project and enable storage insights. 
Try to create a storage insights config, e.g. per example, https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_insights_report_config

### Important Factoids

Upstream API issue

**Comment by edwardmedia** [comment]
@philip-harvey I try to understand why it is not possible. Do you know which account it is?

If it is not automatically created by the api and no existing resources can help provision the SA, maybe we need an enhancement ticket instead?

```
hence it's not possible to create a storage insights config via Terraform at this time without having to also use the GUI.
```

**Comment by edwardmedia** [comment]
@philip-harvey I do see this service account is a Google Managed service agent which is listed [here](https://cloud.google.com/iam/docs/service-agents)

Requiring a user's click might be on purpose for the workflow as it seems a pricing is related.  Whether or not the agent is created, it is beyond what we can do at the provider level. 

Sorry for the confusion you were getting, but I think adding `google_storage_bucket_iam_member` resource  in the example is a nice piece because it shows what SA should be used. It is hard to give an example from end to end, especially it involves the action like `click`. I am not sure if there is a better way to put all these together. Don't you agree?

**Comment by philip-harvey** [comment]
I think I found a work around for this issue, in the beta provider there is google_project_service_identity which can force trigger creation of a SA for an enabled API for APIs that fail to auto create their SAs.

The issue with the documentation isn't the google_storage_bucket_iam_member, it's that the example uses the same bucket as the source and destination of the inventory, which is something that obscures the permissions needed in each bucket because they are different.   I can do a PR to improve the docs though.  I'll close this now that I have this work around and hopefully it will help others who may find this PR when searching for their issue.
