### ISSUE TITLE
Update supported backends for outlier_detection in google_compute_backend_service document

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#16448]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_backend_service

### Expected Behavior

[outlier_detection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#outlier_detection): According to [API doc](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) outlier_detection supports load_balancing_scheme `NTERNAL_SELF_MANAGED` or `EXTERNAL_MANAGED`. Terraform docs is showing `INTERNAL_SELF_MANAGED` only.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@imrannayer I don't see the provider code that limits the use of `EXTERNAL_MANAGED`. What error did you receive when you set it to a non NTERNAL_SELF_MANAGED value? Please share the debug log.

**Comment by imrannayer** [comment]
@edwardmedia ticket is to fix the documentation. Provider is working fine.
