### ISSUE TITLE
Create OAuth 2.0 Client ID (non-IAP) resource

### ISSUE THREAD

**Issue by katieclaiborne** [hashicorp/terraform-provider-google#16452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to be able to configure a non-IAP OAuth 2.0 Client ID as a resource.

If it's helpful, our specific use case is described on [this documentation page](https://docs.getdbt.com/docs/cloud/manage-access/set-up-bigquery-oauth#creating-a-bigquery-oauth-20-client-id-and-secret).

We tried using the `google_iap_client` resource to import a manually-created client, but encountered the following error:

> Error when reading or editing IapClient "projects/<project_number>/brands/<brand_id>/identityAwareProxyClients/<client_id>": googleapi: Error 403: The caller does not have permission

```tf
import {
  to = google_iap_brand.data_platform
  id = "projects/<project_number>/brands/<brand_id>"
}
resource "google_iap_brand" "data_platform" {
  support_email     = "<first.last>@cityblock.com"
  application_title = "Data Platform"
}

import {
  to = google_iap_client.dbt_cloud
  id = "projects/<project_number>/brands/<brand_id>/identityAwareProxyClients/<client_id>"
}
resource "google_iap_client" "dbt_cloud" {
  display_name = "dbt Cloud"
  brand        = google_iap_brand.data_platform.name
}
```

### New or Affected Resource(s)

This issue requests a new resource, perhaps named something like:
* google_oauth_client

It relates to the existing `google_iap_client` resource.

### Potential Terraform Configuration

```tf
resource "google_oauth_client" "dbt_cloud" {
  application_type              = "Web application"
  name                          = "dbt Cloud"
  authorized_javascript_origins = ["https://cloud.getdbt.com"]
  authorized_redirect_uris      = ["https://cloud.getdbt.com/complete/bigquery"]
}
```

I would like to be able to access the client ID and secret values as attributes.

### References

* Relates to #6074, and #1287 before it.
* [This Google issue](https://issuetracker.google.com/issues/182710613) is somewhat related, in that it references non-IAP OAuth 2.0 Client IDs.

**Comment by slevenick** [comment]
I'm not sure if this is currently possible via the REST APIs. Are you aware of a REST API that would allow us to do this? The resource google_iap_brand is backed by the IAP APIs here: https://cloud.google.com/iap/docs/reference/rest/v1/projects.brands so it seems to be only usable for IAP clients.

Without a REST API that enables this use case there isn't much we can do from the Terraform side
