### ISSUE TITLE
Filestore backup restore 

### ISSUE THREAD

**Issue by Konrad-Was** [hashicorp/terraform-provider-google#16461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We did not find it possible to create a backup installation using terraform. Currently, there is output in the source_backup documentation and we need an argument to use in Terraform.

### New or Affected Resource(s)

* google filestore backup
* google filestore instance
* google filestore snapshot

### Potential Terraform Configuration

```tf
file_shares {
    capacity_gb = var.capacity
    name        = var.fileshare_name
    source_backup = var.source_backup #this should be an input


│ Error: Value for unconfigurable attribute
│
│   with module.instance.google_filestore_instance.instance,
│   on ..\..\modules-lokal\Filestore\Instance\main.tf line 9, in resource "google_filestore_instance" "instance":
│    9:     source_backup = var.source_backup
│
│ Can't configure a value for "file_shares.0.source_backup": its value will be decided automatically based on the result of applying this configuration.
```

### References

b/310896689

**Comment by melinath** [comment]
After discussing this in triage we think that this is a gap - we support seeing that the resource has been restored from backup but don't support actually restoring a resource from backup.

Similar functionality exists in Spanner.

**Comment by Konrad-Was** [comment]
@melinath Thank you for your answer. 
When can we expect the ability to restore copies from backup and snapshot to be added in TF ?

**Comment by melinath** [comment]
This ticket has been forwarded to engineering but we don't have a timeline on when this functionality might be added.
