### ISSUE TITLE
Although `google_vertex_ai_endpoint` have `location` and `region`, can we consolidate them into `region`?

### ISSUE THREAD

**Issue by shotarok** [hashicorp/terraform-provider-google#16478]
According to the example below, although `google_vertex_ai_endpoint` has `location` and `region`, can we consolidate them into `region`? It looks like the other vertex ai resources use `region`. To introduce that change, do we need to wait for the next major version update?

ref. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_endpoint#example-usage---vertex-ai-endpoint-network

**Comment by slevenick** [comment]
Yeah, consolidating these into region would make sense. It looks like it was initially introduced as location, but we added region to support the field used in the base path: https://github.com/GoogleCloudPlatform/magic-modules/pull/7770

It would need to wait for the next major version though

**Comment by shotarok** [comment]
@slevenick Thank you for your quick answer!

@edwardmedia Can we keep this issue as a feature request? Or is there another way to manage this type of feature request?
