### ISSUE TITLE
google_dns_managed_zone Plugin did not respond

### ISSUE THREAD

**Issue by cgageat** [hashicorp/terraform-provider-google#16489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v1.6.3
on linux_386

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
data "google_dns_managed_zone" "minutis_zone" {
  name    = local.dns_zone_name
  project = local.dns_zone_project
}
```

### Debug Output

https://gist.github.com/cgageat/58368f31dc630390e02efb85e27ba0f6

### Expected Behavior

Resource should be imported as data

### Actual Behavior

terraform apply crash

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by rileykarson** [comment]
Similar to https://github.com/hashicorp/terraform-provider-google/issues/6518

**Comment by cgageat** [comment]
We downloaded the wrong binary in our new computer: 32bit instead of 64 one.
