### ISSUE TITLE
google_logging_*_bucket_config resources may not correct drift on acquire for unspecified fields

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#16498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_logging_folder_bucket_config
* google_logging_organization_bucket_config
* google_logging_project_bucket_config
* google_logging_billing_account_bucket_config

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

```
resource "google_logging_folder_bucket_config" "basic" {
  folder         = google_folder.default.name
  location       = "global"
  retention_days = 30
  bucket_id      = "_Default"
  
# index configs omitted when a value was added out of band
}
```

### Actual Behavior

No change on first apply. On second apply, a diff is detected.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This happens because unspecified fields don't return true on `HasChange` on Create. This is normally not a problem because this doesn't matter for Create calls, but the default logging config buckets will acquire themselves and then call update. During creation of the update mask we don't see a change, and don't add the field.

This may be a little tricky to resolve- because we can't refresh the resource we will overwrite fields that have a different value in configuration than live and that have `lifecycle.ignore_changes` set on the field. This makes sense if you know how the internals work here- ignore_changes just copies the refreshed value into state but we would need to refresh ourselves without access to `ignore_changes` (as the provider doesn't know if it's been set or not, just the final value). So a naive solution like setting a wildcard update mask may be undesirable.

As a workaround this can be resolved by running the second `terraform apply`.

### References

* #0000

b/310337648

**Comment by trodge** [comment]
Does this issue happen to any resource that creates via an update method?

**Comment by rileykarson** [comment]
It could, assuming that an update mask is needed. The point about `lifecycle.ignore_changes` would also apply- we probably need to accept that happening as a limitation until https://github.com/hashicorp/terraform/issues/19017 is possible.

**Comment by pengq-google** [comment]
I can't reproduce this outcome T_T

**Comment by rileykarson** [comment]
Ah- this isn't actually an issue with these resources. I think I got a few of the logging resources mixed up, where some of their update implementations would cause an issue _combined_ but don't on their own. Sorry for the noise!
