### ISSUE TITLE
`google_scc_mute_config` does not mute existing findings

### ISSUE THREAD

**Issue by jaredparker** [hashicorp/terraform-provider-google#16495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Mute rules only mute newly generated findings after the rule's creation. When creating a new mute rule within the GCP Console, it automatically runs the [`muteBulk`](https://cloud.google.com/security-command-center/docs/reference/rest/v1/organizations.findings/bulkMute) operation as well as the rule's creation operation ([see here](https://cloud.google.com/security-command-center/docs/how-to-mute-findings?_ga=2.147385975.-1325929350.1698405905#bulk_mute_findings)). The current `google_scc_mute_config` resource does not run this extra operation - meaning that existing findings are not muted and the process has to be done manually.

This bug/enhancement issue proposes that the [`muteBulk`](https://cloud.google.com/security-command-center/docs/reference/rest/v1/organizations.findings/bulkMute) operation is ran along side the resources creation/modification. I personally do not see a reason why this shouldn't be part of the default configuration, but if needed, this could potentially be toggled by a `mute_existing` boolean parameter.

_Note: The current resource's description states that it will "...automatically silence **existing** and future findings...". So, I believe this could be considered a bug._

>   Mute Findings is a volume management feature in Security Command Center
  that lets you manually or programmatically hide irrelevant findings,
  and create filters to automatically **silence existing** and future
  findings based on criteria you specify.

_https://github.com/gleichda/magic-modules/blob/main/mmv1/products/securitycenter/MuteConfig.yaml_

### New or Affected Resource(s)

* `google_scc_mute_config`

### Potential Terraform Configuration

```tf
resource "google_scc_mute_config" "mute-rule" {
  // ...
  mute_existing = true // default
}
```

### References

* GoogleCloudPlatform/magic-modules#7332

b/310896359

**Comment by francisphn** [comment]
There's a v2 API for Security Command Centre, and [complementary Terraform resource blocks](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.41.0) but the behaviour concerning this remains the same. I would have to guess that is to make it match with the behaviour of the API and gcloud CLI too.

In this case, would it make sense to create a resource block representing `bulkMute`? That said, I appreciate bulk-muting is not a CRUD-oriented resource (more so an _action_), so am also unsure how the update and delete case can be handled.

**Comment by jaredparker** [comment]
@francisphn One thing I'll re-highlight is the description of this terraform resource:

>   Mute Findings is a volume management feature in Security Command Center
  that lets you manually or programmatically hide irrelevant findings,
  and create filters to automatically **silence existing** and future
  findings based on criteria you specify.

_https://github.com/gleichda/magic-modules/blob/main/mmv1/products/securitycenter/MuteConfig.yaml_

This resource is described to mute existing findings, but it does not. As you say, the v2 API has the same issue and its description is also the same. I'll edit the original post to match this.

I haven't really explored the Google Provider codebase, so I cannot say what is best functionally. But @melinath's potential solution sounds quite good.

**Comment by owenhuyn** [comment]
Hi, I'm part of the GCP Security Command Center team.

We just released a new feature called "dynamic mute rules' which will mute your existing findings at scale:
https://cloud.google.com/security-command-center/docs/how-to-mute-findings#mute-types

The type is released as part of the new V2 API: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/scc_v2_organization_mute_config

This capability mutes existing and new findings. Let know if this functionality doesn't work for this use-case.

**Comment by melinath** [comment]
Great to hear! Marking this issue as closed in that case.
