### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_spotWithInstanceFlexibilityPolicy

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#16492]
### Failure rates

- 100% since 2023-11-01

### Impacted tests

- TestAccDataprocCluster_spotWithInstanceFlexibilityPolicy

### Affected Resource(s)

* google_dataproc_cluster

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/7223075439994866889?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
        Error: Error creating Dataproc cluster: googleapi: Error 400: Node groups are not allowed to be used without staging bucket permissions (storage.objects.get, storage.objects.create and storage.objects.update) for the vm service account. See https://cloud.google.com/dataproc/docs/concepts/service-accounts#VM_service_account., badRequest

```

b/310896896

**Comment by sunchengxuanivy** [comment]
is setting permission good enough to resolve the case? Let me know if any follow up needed @ScottSuarez

**Comment by ScottSuarez** [comment]
Looks like its passing again. We can close this out
