### ISSUE TITLE
Dataflow Error 400 Invalid template file while using default google template

### ISSUE THREAD

**Issue by heph2** [hashicorp/terraform-provider-google#16496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.6.3

### Affected Resource(s)

* google__dataflow_job

### Terraform Configuration Files

```tf
resource "google_dataflow_job" "test" {
    project = var.project_id
    name = "tf-test-dataflow-job1"
    zone = "europe-west1-a"
    template_gcs_path = "gs://dataflow-templates-europe-west1/latest/flex/MongoDB_to_BigQuery"
    temp_gcs_location = "${google_storage_bucket.bucket1.url}/tmp"

    parameters = {
      mongoDbUri = var.mongodb_connection_string
      database = "foo"
      collection = "foo"
      outputTableSpec = "foo.example_dataset.test"
      userOption = "NONE"
    }
    on_delete = "cancel"
}
```

### Expected Behavior

Should be able to create a dataflow job

### Actual Behavior

 Error: googleapi: Error 400: Invalid template file gs://dataflow-templates-europe-west1/latest/flex/MongoDB_to_BigQuery. Please specify a correct Google-provided template path from https://cloud.google.com/dataflow/docs/guides/templates/provided-templates or create your own template following https://cloud.google.com/dataflow/docs/guides/templates/creating-templates, failedPrecondition

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

b/310337735

**Comment by melinath** [comment]
Based on https://cloud.google.com/dataflow/docs/guides/templates/provided/mongodb-to-bigquery#api, it looks like the containerSpecGcsPath should be something like:

```
gs://dataflow-templates-LOCATION/VERSION/flex/MongoDB_to_BigQuery
```

so this seems like it should work - I can't tell if this is an issue with the provider or with the API.

@edwardmedia were you able to reproduce this?

@heph2 could you provide [API request/response logs](https://developer.hashicorp.com/terraform/internals/debugging) for the request that failed?

**Comment by edwardmedia** [comment]
Yes, looks like the path to the template is legit. It can be verified via below gsutil command

```
gsutil ls gs://dataflow-templates-europe-west1/latest/flex
```

**Comment by melinath** [comment]
@edwardmedia were you able to reproduce the error?

**Comment by edwardmedia** [comment]
Yes, it can be reproduced. @melinath

**Comment by Abacn** [comment]
That is strange. I can invoke "gsutil ls gs://dataflow-templates-europe-west1/latest/flex" in my side. Are you able to download https://storage.googleapis.com/dataflow-templates-europe-west1/latest/flex/MongoDB_to_BigQuery ? @heph2 @edwardmedia

**Comment by heph2** [comment]
Yes @Abacn i can invoke `gsutil ls` as well, and also download the template without issues

**Comment by Abacn** [comment]
I might find the problem. In your pasted log (https://clbin.com/H9217), I see the POST request is made to 

```
POST /v1b3/projects/<project>/locations/europe-west1/templates?alt=json&prettyPrint=false HTTP/1.1
```

however, according to the doc https://cloud.google.com/dataflow/docs/guides/templates/provided/mongodb-to-bigquery#api,

the POST request send to
```
https://dataflow.googleapis.com/v1b3/projects/<project>/locations/europe-west1/flexTemplates:launch
```
There are two types of dataflow template:
- "classic" template, API entry point is "templates" (e.g. https://cloud.google.com/dataflow/docs/guides/templates/provided/cloud-storage-to-bigquery#api)
- "flex" template, API entry point is "flexTemplates" (e.g. MongoDB to BigQuery)

**Comment by Abacn** [comment]
Please use google_dataflow_flex_template_job instead: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job

**Comment by heph2** [comment]
Thanks @Abacn that was the problem. Sorry then :)

**Comment by perebaj** [comment]
I face the same problem, thanks guys
