### ISSUE TITLE
google_compute_instance update network_interface.network_ip with google_compute_address

### ISSUE THREAD

**Issue by florenp** [hashicorp/terraform-provider-google#16494]
I have an existing google_compute_instance and I want to switch to a fixed ip.
I assign a google_compute_address of type "INTERNAL"

The plan show that the IP is going to change, but nothing is changed(the apply works fine).
A 2nd plan still show the same change.

The IP should be changed or if not possible the google_compute_instance should be replaced

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform -version
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.29.0
+ provider registry.terraform.io/hashicorp/google v5.5.0
+ provider registry.terraform.io/hashicorp/google-beta v5.5.0
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Affected Resource(s)

google_compute_instance

### Debug Output

https://gist.github.com/florenp/2c02bd0d5328387d296d4485615dfecf

### Expected Behavior

Update the google_compute_instance IP or if not possible replace the google_compute_instance

### Actual Behavior

Nothing is changed. The apply is ok, but another plan just after want to make the same change

### Steps to Reproduce

Create a google_compute_instance without any google_compute_address affected to it.
Create a google_compute_address and try to affect it to your google_compute_instance

b/310337617

**Comment by florenp** [comment]
> @florenp do you plan to change a public ip and private one?
> 
> [network_ip](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#network_ip) - (Optional) The private IP address to assign to the instance. If empty, the address will be automatically assigned.
> 
> To update the public ip, is this [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#example-usage---instance-with-ip) helpful?

I wanted to change my instance private IP(wanted to switch to a fixed one even if I destroy/recreate it). So I reserved a private one with google_compute_address and try to set it to my google_compute_instance. I got the result I pasted in the gist.

**Comment by edwardmedia** [comment]
Yeah, I do see this is a bug. Basically the plan shows the diff but there is no update for it in the plan

**Comment by florenp** [comment]
Hello @edwardmedia,

Any news on that?

**Comment by LucaPrete** [comment]
@florenp @edwardmedia I doubt this is allowed from APIs.

If I try to do the call directly from REST I receive:

```
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource.networkIP': 'x.x.x.x'. Updating this field is not supported.",
    "errors": [
      {
        "message": "Invalid value for field 'resource.networkIP': 'x.x.x.x'. Updating this field is not supported.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

I'm maybe missing something. I'll double check internally with the product team before confirming.

**Comment by LucaPrete** [comment]
Hello all!

@florenp I'm afraid this is working as expected.
The Google compute API doesn't allow you today to change the IP of a VM.

The process to promote it to static is described [here](https://cloud.google.com/vpc/docs/reserve-static-internal-ip-address#promote-in-use-internal-address). You will need to allocate (read create) a static IP, whose value is the one that the VM is already using.

I also successfully tried this in Terraform.

First, I created a test-vm with an ephemeral IP.

```
resource "google_compute_instance" "test_ip_update" {
  project      = "xxx"
  name         = "test-ip-update"
  machine_type = "e2-micro"
  zone         = "europe-west1-b"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
    }
  }
  network_interface {
    subnetwork = "https://www.googleapis.com/compute/v1/projects/xxx/regions/europe-west1/subnetworks/test-subnet"
  }
}
```

Then, I used the `google_compute_address` resource to make the IP static:

```
resource "google_compute_address" "static_address" {
  name         = "my-internal-address"
  project      = "xxx"
  subnetwork   = "https://www.googleapis.com/compute/v1/projects/xxx/regions/europe-west1/subnetworks/test-subnet"
  address_type = "INTERNAL"
  address      = google_compute_instance.test_ip_update.network_interface[0].network_ip
  region       = "europe-west1"
}
```

From now on, the IP assigned to the VM is static.

On a side note, given the API doesn't even allow to change the `network_ip` value I'd remove the unnecessary code from the update method in the resource, I'd mark the field as "not updatable" and I'd possibly add a note in the documentation, thus avoiding further confusion. @edwardmedia I can take care of this if you want.

Finally, I'd close this bug and mark it as `won't fix`.

**Comment by karolgorc** [comment]
> On a side note, given the API doesn't even allow to change the network_ip value I'd remove the unnecessary code from the update method in the resource, I'd mark the field as "not updatable"

Shouldn't we just make a change to the `network_ip` field force a replace of the instance? Unless there are some use cases of this i'm not aware of.

Because the succesful `terraform apply` even when just changing the `network_ip` by hand with different addresses is confusing

**Comment by karolgorc** [comment]
Will also test if Instances.Update() supports the IP change instead of Instances.UpdateNetworkInterface()

Found this comment as well.
// network_interface.[d].network_ip can only change when subnet/network
// is also changing. Validate that if network_ip is changing this scenario
// holds up to par.
func forceNewIfNetworkIPNotUpdatable(ctx context.Context, d *schema.ResourceDiff, meta interface{}) error {
	// separate func to allow unit testing
	return forceNewIfNetworkIPNotUpdatableFunc(d)
}

Seems like the force replace method is already in place but not working

**Comment by ScottSuarez** [comment]
@LucaPrete would you mind taking a look at https://github.com/GoogleCloudPlatform/magic-modules/pull/11395
