### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by 7pandeys** [hashicorp/terraform-provider-google#16506]
### Documentation Issue

**Documentation Link:** [Link to Documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_crypto_key)

### Description

The documentation for the `lifecycle` argument in the `google_kms_crypto_key` resource is currently lacking or unclear. I would like to request more information or clarification on how the `lifecycle` argument should be used or any additional examples that could be provided.

### Additional Information

- Provider: Terraform/Google
- Provider Version: 5.5.0
- Operating System: Mac

**Comment by trodge** [comment]
`lifecycle` is a meta argument for Terraform resources. Documentation for it is found [here](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#prevent_destroy). I will also add this link to the note referring to `lifecycle` in the `google_kms_crypto_key` docs page.
