### ISSUE TITLE
Error: Error applying IAM policy for service account

### ISSUE THREAD

**Issue by dilip0515** [hashicorp/terraform-provider-google#16505]
Terraform apply was working until yesterday but today getting the below errors while applying it.

below are by terraform and google provider versions i tried changing the google provider version to latest(5.5.0) as well

 terraform version > 1.3.6"
    google
      version = "~>4.45.0"
    google-beta 
      version = "~>4.45.0"
    

│ Error: Error applying IAM policy for service account 'projects/{project_id}/serviceAccounts/cloud-sql-proxy@{project_id}.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/{project_id}/serviceAccounts/cloud-sql-proxy@{project_id}.iam.gserviceaccount.com': googleapi: Error 400: Email ‘abc_gcp@groups.ms.com' is not the primary email address for unique ID ‘xxx’ of deleted member 'abc_gcp@groups.ms.com?uid=xxxx’., badRequest
│ 
│   with google_service_account_iam_member.proxy_account["roles/iam.serviceAccountTokenCreator"],
│   on abc.tf line 136, in resource "google_service_account_iam_member" "proxy_account":
│  136: resource "google_service_account_iam_member" "proxy_account" {

│ Error: Error applying IAM policy for iap tunnelinstance "projects/{project_id}/iap_tunnel/zones/us-central1-b/instances/db-proxy": Error setting IAM policy for iap tunnelinstance "projects/{project_id}/iap_tunnel/zones/us-central1-b/instances/db-proxy": googleapi: Error 400: Email 'abc_gcp@groups.ms.com' is not the primary email address for unique ID 'xxx’ of deleted member 'abc_gcp@groups.ms.com?uid=xxx’.
│ 
│   with google_iap_tunnel_instance_iam_member.proxy_instance_iap_tunnel_access["group:GCP@groups.optum.com"],
│   on cloudsql.tf line 155, in resource "google_iap_tunnel_instance_iam_member" "proxy_instance_iap_tunnel_access":
│  155: resource "google_iap_tunnel_instance_iam_member" "proxy_instance_iap_tunnel_access" {

**Comment by edwardmedia** [comment]
@dilip0515 it is hard to say what happened. Did you remove any accounts "yesterday"? What do you get if you make an api call?

```
endpoint: https://cloudresourcemanager.googleapis.com/v1/projects/{your_project}:getIamPolicy
method: POST
Payload body:
{
 "options": {
  "requestedPolicyVersion": 3
 }
}
```

**Comment by dilip0515** [comment]
getting a 401 unauthorized  error is there a way to look into the logs from google console?

**Comment by edwardmedia** [comment]
@dilip0515 from Google console, have you checked out [Stackdriver](https://cloud.google.com/products/operations?hl=en)?

For terraform, you may enable [debug](https://developer.hashicorp.com/terraform/internals/debugging) to obtain the log. 

Without your config, it is hard to say what went wrong?

What did you do? 
```
Terraform apply was working until yesterday but today getting the below errors while applying it.
```

**Comment by edwardmedia** [comment]
@dilip0515 closing now assuming this is no longer an issue
