### ISSUE TITLE
Support google_vertex_ai_feature_online_store resources

### ISSUE THREAD

**Issue by shotarok** [hashicorp/terraform-provider-google#16507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

A new version of Vertex AI Feature Store was announced at Cloud Next 23, and the following new APIs are available as v1beta1 as of Nov 11, 2023. This issue is a feature request to support those new APIs as new resources. [UPDATED] The v1 also supports them on Nov 20, 2023.

* APIs (v1)
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureOnlineStores
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureOnlineStores.featureViews
* APIs (v1beta1)
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featureOnlineStores
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featureOnlineStores.featureViews

### New Resources

* google_vertex_ai_feature_online_store
* google_vertex_ai_feature_online_store_feature_view

### Potential Terraform Configuration

```tf

```

### References

* [About Vertex AI Feature Store | Vertex AI > Documentation > Guides](https://cloud.google.com/vertex-ai/docs/featurestore/latest/overview)
* [Predictive and generative AI projects with Vertex AI Feature Platform | Cloud Next 23](https://www.youtube.com/watch?v=vWs2Q4gzO5g)

b/311159813

**Comment by melinath** [comment]
This ticket will cover google_vertex_ai_feature_online_store and google_vertex_ai_feature_online_store_feature_view; I'll create a new ticket to cover google_vertex_ai_feature_group and google_vertex_ai_feature_group_feature

**Comment by shotarok** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9686 will fix this issue.
