### ISSUE TITLE
How to attach instance in compute_network_endpoint_group

### ISSUE THREAD

**Issue by marandalucas** [hashicorp/terraform-provider-google#16512]
Hello, 

We are trying to convert "gcloud CLI automation" to Terraform.

1. DONE
```bash
gcloud compute network-endpoint-groups create "$neg_name" \
        --network-endpoint-type=gce-vm-ip-port \
        --zone="$zone" \
        --network="$network" \
        --subnet="$subnet" \
        --default-port=443 \
        --project="$project"
```

2. Unfortunately, we couldn't attach the instance following the documentation.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint_group

```
gcloud compute network-endpoint-groups update "$neg_name" \
        --zone="$zone" \
        --add-endpoint="$endpoint_instance_name_vm" \
        --project="$project"
```

Could you help up?

Thanks in advance

**Comment by edwardmedia** [comment]
@marandalucas for `--add-endpoint`, have you checked below [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint#example-usage---network-endpoint)?

```tf
resource "google_compute_network_endpoint" "default-endpoint" {
  network_endpoint_group = google_compute_network_endpoint_group.neg.name

  instance   = google_compute_instance.endpoint-instance.name
  port       = google_compute_network_endpoint_group.neg.default_port
  ip_address = google_compute_instance.endpoint-instance.network_interface[0].network_ip
}
```

**Comment by marandalucas** [comment]
@edwardmedia Thank! Let me try it :)

**Comment by edwardmedia** [comment]
@marandalucas is this still a question?

**Comment by edwardmedia** [comment]
@marandalucas closing assuming it is no longer a question

**Comment by marandalucas** [comment]
@edwardmedia My apologies. Yes, you can close it :)
