### ISSUE TITLE
Support google_vertex_ai_feature_group resources

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#16516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Split off from https://github.com/hashicorp/terraform-provider-google/issues/16507:

> A new version of Vertex AI Feature Store was announced at Cloud Next 23, and the following new APIs are available as v1beta1 as of Nov 11, 2023. This issue is a feature request to support those new APIs as new resources.

* APIs
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featureGroups
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.featureGroups.features

### New or Affected Resource(s)

* google_vertex_ai_feature_group
* google_vertex_ai_feature_group_feature

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* [About Vertex AI Feature Store | Vertex AI > Documentation > Guides](https://cloud.google.com/vertex-ai/docs/featurestore/latest/overview)
* [Predictive and generative AI projects with Vertex AI Feature Platform | Cloud Next 23](https://www.youtube.com/watch?v=vWs2Q4gzO5g)

b/311160598

**Comment by shotarok** [comment]
The v1 also supports the endpoints on Nov 20, 2023.

* API (v1)
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureGroups
  * https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureGroups.features
