### ISSUE TITLE
Plan fails when using google_project_service data source with disabled APIs - API not found

### ISSUE THREAD

**Issue by d-costa** [hashicorp/terraform-provider-google#16515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```sh
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.5.0
```

### Affected Resource(s)

* google_project_service (Data Source)

### Terraform Configuration Files

```tf
terraform {
  required_version = "1.6.3"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "5.5.0"
    }
  }
}

provider "google" {
  project = var.project_id
}

variable "project_id" {
  type = string
}

data "google_project_service" "compute" {
  service = "compute.googleapis.com"
}

data "google_project_service" "dataproc" {
  service = "dataproc.googleapis.com"
}
```

### Expected Behavior

```
data.google_project_service.dataproc: Reading...
data.google_project_service.compute: Reading...
data.google_project_service.compute: Read complete after 5s [id=PROJECT_ID/compute.googleapis.com]
data.google_project_service.dataproc: Read complete after 5s

Changes to Outputs:
  + compute_enabled  = true
  + dataproc_enabled = false

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

compute_enabled = true
dataproc_enabled = false
```

### Actual Behavior

```
data.google_project_service.compute: Reading...
data.google_project_service.dataproc: Reading...
data.google_project_service.compute: Read complete after 5s [id=PROJECT_ID/compute.googleapis.com]

Changes to Outputs:
  + compute_enabled = true

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
╷
│ Error: PROJECT_ID/dataproc.googleapis.com not found
│ 
│   with data.google_project_service.dataproc,
│   on main.tf line 24, in data "google_project_service" "dataproc":
│   24: data "google_project_service" "dataproc" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- This configuration works with google provider version `4.84.0`
- For context, we need this data source to conditionally enable APIs based on the status of others

### References

- Data source created here https://github.com/hashicorp/terraform-provider-google/pull/13434
- Modified here: https://github.com/hashicorp/terraform-provider-google/commit/3e00cfb

I believe this change was not intended, because it prevents the requested use case.

**Comment by edwardmedia** [comment]
@d-costa you are right. The behavior has been updated on most data sources by [this PR ](https://github.com/hashicorp/terraform-provider-google/pull/15799) in [v5.0.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0)

The original issue was https://github.com/hashicorp/terraform-provider-google/issues/12873

Please go through the links above to see if that make sense.

**Comment by d-costa** [comment]
Thank you for your response @edwardmedia

I understand the objective of the PR you mentioned, and I am not contesting its benefits, but this prevents the use case that even the documentation describes, since we cannot check if the service is enabled if we can only use it with enabled services:

> Verify the API service for the Google Cloud Platform project to see if it is enabled or not.
> (https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/google_project_service)

**Comment by edwardmedia** [comment]
@trodge what do you think about this?

**Comment by trodge** [comment]
It looks like this was an intended change for all data sources in 5.0.0 based on https://github.com/hashicorp/terraform-provider-google/issues/12873.

That being said, it's possible the behavior is not appropriate for this data source in particular, since the main use case for `data_source_google_project_service` would be determining whether a service is enabled.

@NickElliot might have more context having made the change in https://github.com/GoogleCloudPlatform/magic-modules/pull/8858.
