### ISSUE TITLE
Artifact registry docker image data source

### ISSUE THREAD

**Issue by dibunker** [hashicorp/terraform-provider-google#16557]
# Background
This is somewhat related to the request #4317, but since GCR is being deprecated, I decided to work on creating a data source for Artifact Registry.  This is my first time developing in the Terraform Plugin SDK v2, and I'm not sure how to proceed with writing the acceptance test.

# What kind of contribution is this issue about?

Handwritten data source.

# Related PR(s), if any:

# Details

Like in #4317, this would be a data source for a docker image in an Artifact Registry to obtain the fully qualified name and self_link.  I've forked the magic modules and started working on a handwritten data source, but I'm stuck on writing the acceptance test.

Conceptually, I understand that I would need an Artifact Registry repository populated with docker images to test the data source against. The question is, how do I get that test fixture?  I know there's this [public GCR](https://console.cloud.google.com/gcr/images/google-containers), but I'm not sure if there's an equivalent public Artifact Registry that I could use to test against.  If not, is it even possible to push docker images to an Artifact Registry repo within the scope of the test steps once a repository is setup?

I haven't created a PR yet, since the guidelines stated to first test locally, but I would be happy to put up a draft PR if that helps.

b/312432701

**Comment by dibunker** [comment]
That is to get the docker image information, which I'm proposing using [on my fork](https://github.com/dibunker/magic-modules/blob/ad20020d5a693edd54db91b5314fb74a5ee0ef3b/mmv1/third_party/terraform/services/artifactregistry/data_source_artifact_registry_docker_image.go#L114), not for pushing an image.

For the test context, wouldn't we need to create an artifact registry repo, populate it with images, and validate that the API is retrieving the information correctly? That is, the `get` and `list` methods are working and the data source attributes are correct.

**Comment by ardagnir** [comment]
https://console.cloud.google.com/artifacts/docker/go-containerregistry/us/gcr.io is a public AR repo. It's also a "gcr.io repository", so it should already work as a GCR data source, but should also work for testing AR data sources

**Comment by dibunker** [comment]
@ardagnir excellent!  I confirmed that I can use the API methods on that AR repo.  Now to write some tests.

**Comment by nprime496** [comment]
Hi, your work seems related to my issue, can you please tell whether it it is normal that `google_artifact_registry_docker_image` seems not to be working ? 

https://github.com/hashicorp/terraform-provider-google/issues/18577
