### ISSUE TITLE
Cannot set labels on google_compute_forwarding_rule on creation

### ISSUE THREAD

**Issue by Ziemowit-LH** [hashicorp/terraform-provider-google#16564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Latest as of today:
```terraform -version
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.6.0
```

### Affected Resource(s)

* google_compute_forwarding_rule

### Terraform Configuration Files

```tf
variable "project_id" { default = "project" }
variable "project_network" { default = "island-vpc" }
variable "region" { default = "region" }
variable "subnet" { default = "prisma-cloud-subnet" }
variable "reserve_ip_address" { default = "192.168.254.243" } # in the subnet above
variable "target_service_attachment" { default = "projects/other-project/regions/region/serviceAttachments/prisma" }

provider "google" {
  default_labels = { mylabel = "labelvalue" }
}

resource "google_compute_forwarding_rule" "prisma_fwd" {
  ip_address            = google_compute_address.prisma_ip.id
  name                  = "prisma-rule"
  network               = var.project_network
  project               = var.project_id
  region                = var.region
  target                = var.target_service_attachment
  load_balancing_scheme = "" # what is empty?
}

resource "google_compute_address" "prisma_ip" {
  address      = var.reserve_ip_address
  address_type = "INTERNAL"
  name         = "prisma-forwarded-ip"
  purpose      = "GCE_ENDPOINT"
  subnetwork   = var.subnet
  project      = var.project_id
  region       = var.region
}
```

```terraform -version
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.6.0
```

### Debug Output

DEBUG: https://gist.github.com/Ziemowit-LH/cea8141755bfba8e4f8a6fe499abec4a
TRACE: https://gist.github.com/Ziemowit-LH/115d19c26f2e056746a4761593bd1ec5

### Expected Behavior

Create the rule.

### Actual Behavior

```
╷
│ Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Invalid field set in Private Service Connect Forwarding Rule. This field should not be set., invalid
│ 
│   with google_compute_forwarding_rule.prisma_fwd,
│   on main.tf line 12, in resource "google_compute_forwarding_rule" "prisma_fwd":
│   12: resource "google_compute_forwarding_rule" "prisma_fwd" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #16255 - same behaviour reported in provider v4

After the resource is created updating the labels works.

**Comment by edwardmedia** [comment]
@Ziemowit-LH the error complains the ip address. Can you review[ its doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#ip_address) to see if that help resolve the issue?

```
Error 400: Invalid value for field 'resource.IPAddress'
``` 

If the issue persists, can you share your full debug log?

**Comment by Ziemowit-LH** [comment]
@edwardmedia Apologies I didn't realise my demonstration was wrong. I updated opening post with the correct error, better TF code and correct gists.

There was a gist before too... in the comments :/

**Comment by Ziemowit-LH** [comment]
Interesting.

With gcloud
```
gcloud compute forwarding-rules create prisma-rule --region region --network island-vpc1 --address prisma-forwarded-ip  --target-service-attachment "projects/prismaproject/regions/region/serviceAttachments/prisma" --labels label=value
```
 during creation there is no argument "--labels" at all:
```
ERROR: (gcloud.compute.forwarding-rules.create) unrecognized arguments:
  --labels
```
It is only possible to create them later with 
```
gcloud compute forwarding-rules update prisma-rule2  --update-labels label=value --region region
```

Holy cow, this is crap!

Now the (IMO great) idea of default_labels defined at provider level can't work with this resource.

**Comment by edwardmedia** [comment]
@Ziemowit-LH  as I said, the rule is set by the api. There is not much we can do at the provider. Closing this issue now. Feel free to reopen if you see it otherwise.
