### ISSUE TITLE
`google_storage_bucket_object` gets destroyed when file content changes

### ISSUE THREAD

**Issue by yaz-saleh** [hashicorp/terraform-provider-google#16569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Affected Resource(s)

* google_storage_bucket_object

### Terraform Configuration Files

```tf
provider "google" {
  project = "<project-name>"
  region  = "us-central1"
}

resource "google_storage_bucket" "upload_test" {
  name     = "<bucket-name>"
  location = "us-central1"
}


resource "google_storage_bucket_object" "upload" {
  name       = "this.txt"
  bucket     = google_storage_bucket.upload_test.name
  source     = "./this.txt"
}

resource "google_compute_instance_template" "template_test" {
  name_prefix  = "test-server"
  machine_type = "f2-micro"

  depends_on = [google_storage_bucket_object.upload]

  disk {
    source_image = "debian-cloud/debian-11"
    auto_delete  = true
  }

  metadata = {
    myKey = google_storage_bucket_object.upload.name
  }

  lifecycle {
    create_before_destroy = true
  }

  network_interface {
    network = "default"
  }
}

```

### Debug Output

https://gist.github.com/yaz-saleh/99cbc794a3bf5e0758748029cc29ce57

### Expected Behavior

Running `apply` should create a new `this.txt` file on Cloud Storage with new content.

### Actual Behavior

Running `apply` for the first time succeeds and behaviour is as expected, but when `this.txt` content is changed, and `apply` is run again, terraform creates a new `google_storage_bucket_object` resources on GCS and then promptly deletes it.

### Steps to Reproduce

1. Replace vars to target your GCP project.
2. Change `google_storage_bucket` name to a globally unique one
3. Create an empty `this.txt` file
4. Run `terraform apply`
5. Verify that `this.txt` appears on `google_storage_bucket`
6. Change `this.txt` content and save
7. Run `terraform apply` again 
8. Verify that `this.txt` disappears from `google_storage_bucket`

### Important Factoids

N/A

### References

* #0000

b/312696826

**Comment by edwardmedia** [comment]
similar to https://github.com/hashicorp/terraform-provider-google/issues/16546?

@yaz-saleh did you enable the [versioning](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#enabled) on the bucket?

what do you see if you add new objects by gstuil command?

**Comment by yaz-saleh** [comment]
> similar to #16546?
> 
> @yaz-saleh did you enable the [versioning](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#enabled) on the bucket?
> 
> what do you see if you add new objects by gstuil command?

I did not enable versioning. The bucket was created using the terraform resource I included above so the default versioning setting would have been used. 
```tf
resource "google_storage_bucket" "upload_test" {
  name     = "<bucket-name>"
  location = "us-central1"
}
```

I also checked in the console, and object versioning is off.

**Comment by edwardmedia** [comment]
I see a possible reason. For update the StorageClient launch both DELETE and POST. In this case, it invokes POST ahead of DELETE

**Comment by yaz-saleh** [comment]
> I see a possible reason. For update, the StorageClient launch both DELETE and POST. In this case, it invokes POST ahead of DELETE. In my test, I got DELETE then POST

Thanks for confirming. If I remove the ref to the storage object in `google_compute_instance_template` everything seems to work as expected. There is probably something in how the dependency graph is being constructed and that is causing the reversal of the `DELETE` and `POST` operations.

**Comment by jakubno** [comment]
I have the same issue.
```
Terraform v1.5.7
+ provider registry.terraform.io/hashicorp/google v5.6.0
```

**Comment by c2thorn** [comment]
This behavior is due to the `create_before_destroy` lifecycle argument in the instance template propagating to the storage bucket object. This is a bug in upstream Terraform. 

https://github.com/hashicorp/terraform/issues/31316 was closed in favor of https://github.com/hashicorp/terraform/issues/22094 which is the current tracking issue for this behavior.

Closing this issue here since there's not much we can do about it. The workaround would be managing the dependency manually, or temporarily removing the lifecycle argument when making the update. Not ideal, but this seems to be a rare case.
