### ISSUE TITLE
google_container_cluster fails to initialize default node pool and uses incorrect service account

### ISSUE THREAD

**Issue by Schachte** [hashicorp/terraform-provider-google#16560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

❯ terraform -v
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.6.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "cluster" {
  name                     = "cluster"
  project                  = var.project
  location                 = var.region
  remove_default_node_pool = true

  node_config {
    service_account = data.google_service_account.gke_svc_acct.email
  }

  lifecycle {
    ignore_changes = [node_config]
  }

  initial_node_count  = 1
  network             = var.cluster_network
  subnetwork          = var.private_subnet_name
  deletion_protection = false
  networking_mode     = "VPC_NATIVE"

  addons_config {
    http_load_balancing {
      disabled = true
    }
    horizontal_pod_autoscaling {
      disabled = false
    }
  }

  release_channel {
    channel = "REGULAR"
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = "k8s-pod-range"
    services_secondary_range_name = "k8s-service-range"
  }

  private_cluster_config {
    enable_private_nodes = true
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "172.16.0.0/28"
  }
}
```

```tf
resource "google_container_node_pool" "general" {
  depends_on = [google_container_cluster.cluster]
  name       = "general"
  cluster    = google_container_cluster.cluster.id
  project    = var.project
  node_count = 1

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  node_config {
    preemptible  = false
    machine_type = var.master_node_machine_type
    disk_size_gb = var.control_plane_disk_gb

    labels = {
      role = "general"
    }

    service_account = data.google_service_account.gke_svc_acct.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}

resource "google_container_node_pool" "worker" {
  depends_on = [google_container_cluster.cluster]
  name       = "worker"
  cluster    = google_container_cluster.cluster.id
  project    = var.project

  node_count = var.worker_node_min_nodes

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  autoscaling {
    min_node_count = var.worker_node_min_nodes
    max_node_count = var.worker_node_max_nodes
  }

  node_config {
    preemptible  = false
    machine_type = var.worker_node_machine_type
    disk_size_gb = var.data_plane_disk_gb

    labels = {
      role = "worker"
    }

    taint {
      key    = "instance_type"
      value  = "standard"
      effect = "NO_SCHEDULE"
    }

    service_account = data.google_service_account.gke_svc_acct.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```

### Debug Output
Logs are filled with:

```
(1) Google Compute Engine: Not all instances running in IGM after 14.772498665s. Expected 1, running 0, transitioning 1. Current errors: [PERMISSIONS_ERROR]: Instance 'cluster--default-pool-f32f8f13-vmd5' creation failed: Required 'compute.instances.create' permission for 'projects/123/zones/us-west2-c/instances/cluster--default-pool-f32f8f13-vmd5' (when acting as '123@cloudservices.gserviceaccount.com'); [PERMISSIONS_ERROR]: Instance 'default-default-pool-f32f8f13-vmd5' creation failed: Required 'compute.disks.create' permission for 'projects/123/zones/us-west2-c/disks/gke-cluster--default-pool-f32f8f13-vmd5' (when acting as '123@cloudservices.gserviceaccount.com'); [PERMISSIONS_ERROR]: Instance 'cluster--default-pool-f32f8f13-vmd5' creation failed: Required 'compute.disks.setLabe
```

### Expected Behavior

The cluster should be using the account specified in the `node_config` when spinning up the default node pool before destroying it, but  it's still using the default service account. 

I can verify the correct service account is being passed in and used.  `terraform show` output confirms. No issues with other modules.

### Actual Behavior

The default node pool is failing it seems due to using wrong service account despite being overridden 

### Steps to Reproduce

1. `terraform apply`
2. Wait
3. Fails

### Important Factoids

Nothing unusual, but I even tried adding elevated permissions to the default service account to get rid of this error and it's still present. 

### References

* #0000

**Comment by edwardmedia** [comment]
@can you share your debug log?

You have opened https://github.com/hashicorp/terraform-provider-google/issues/16559 as a question. Do you want to keep both open?

**Comment by Schachte** [comment]
@edwardmedia leaning more toward a bug, but wanted to gauge what people are thinking. I can close the question. What's the best info to grab for sharing debug info without posting personal info?

**Comment by Schachte** [comment]
I have tested this in 2 completely different accounts and my setup:
- works in account 1
- fails in account 2

Both service accounts I'm using have the `Owner` role. In account 2, I see that it's still attempting to create the default node pool using the default compute service account despite setting the override (see above).

**Comment by Schachte** [comment]
What is weird is that despite overriding, I always see the provider trying to act as the default compute service account while spinning up the default node pool:

```
(default GCP service account below)
(when acting as '123@cloudservices.gserviceaccount.com'); [PERMISSIONS_ERROR]
```

_This_ is what seems like the bug to me. I've clearly overridden this in my node_config block in the `google_container_cluster`.

**Comment by edwardmedia** [comment]
@Schachte logs will be shared in the public. Before posting them anywhere, you need to make sure to redact all private info. 

I am not sure what service accounts you referred to. 

1) Below environment variable is used for the Terraform runner. Not sure how it is related to the issue.

```
export GOOGLE_APPLICATION_CREDENTIALS='.....
```

2) below account is used for [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#service_account) reason. You use the data source to obtain the service account in your config. It is not clear what it is based on the context you provided. 
```
  node_config {
    service_account = data.google_service_account.gke_svc_acct.email
  }
```

To illustrate the issue, I think it would be better you can provide a simple config without any vars so I can repro what you were seeing. 

Does this make sense?

**Comment by Schachte** [comment]
I'm closing this after a couple days debugging I've found the issue detailed here:
https://stackoverflow.com/a/36916775/19353907

Essentially, regardless of what service account is specified, it will use the default service account for internal initialization. As the account exists (unlisted in the web UI), the associated IAM role for that account did not. Given that it's required and can't be overridden during the initialization of the default node pool, the creation would fail.
