### ISSUE TITLE
Upgrade from 4.84.0 to 5.0.0 cause unexpected changes on google_compute_network

### ISSUE THREAD

**Issue by efazati** [hashicorp/terraform-provider-google#16575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v1.2.9 

### Affected Resource(s)

* google_5.0.0

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
-       version = "~> 4.84.0"
+       version = "~> 5.0.0"
    }
  }
  required_version = "~> 1.2.9"
}
```

### Expected Behavior
There should be no change, but when I change the Terraform version there some unexpected changes

### Actual Behavior
```
  # module.sample.data.google_compute_network.project_default will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "google_compute_network" "project_default" {
      + description            = (known after apply)
      + gateway_ipv4           = (known after apply)
      + id                     = (known after apply)
      + internal_ipv6_range    = (known after apply)
      + name                   = "default"
      + project                = "sample"
      + self_link              = (known after apply)
      + subnetworks_self_links = (known after apply)
    }

  # module.sample.google_compute_global_address.private_ip_address must be replaced
-/+ resource "google_compute_global_address" "private_ip_address" {
      ~ address            = "10.x.x.x" -> (known after apply)
      ~ creation_timestamp = "2022-09-07T14:04:07.442-07:00" -> (known after apply)
      ~ id                 = "projects/sample/global/addresses/private-ip-address" -> (known after apply)
        name               = "private-ip-address"
      ~ network            = "https://www.googleapis.com/compute/v1/projects/sample/global/networks/default" -> (known after apply) # forces replacement
      ~ self_link          = "https://www.googleapis.com/compute/v1/projects/sample/global/addresses/private-ip-address" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

  # module.sample.google_service_networking_connection.private_vpc_connection must be replaced
-/+ resource "google_service_networking_connection" "private_vpc_connection" {
      ~ id                      = "projects%2Fsample%2Fglobal%2Fnetworks%2Fdefault:servicenetworking.googleapis.com" -> (known after apply)
      ~ network                 = "projects/sample/global/networks/default" -> (known after apply) # forces replacement
      ~ peering                 = "servicenetworking-googleapis-com" -> (known after apply)
        # (2 unchanged attributes hidden)
    }

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@efazati [v5.0.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0) does contain certain number of breaking changes.

From the plan, it looks like a new **google_compute_network** was introduced which was gonna to replace the old ones in other two resources?

**Comment by efazati** [comment]
@edwardmedia the strange part is the same code with 4.X version doesn't have any changes in the terrafor plan
`google_compute_network` is in my current statefile, so that is not a new thing
that's why I thought this is a bug, also I couldn't find anything related this in the v5.0.0 changelog

**Comment by edwardmedia** [comment]
@efazati I can't explain below plan. Did you have had the `default` network already? You might want to dig into the module to see if something suspicious. 

```
 <= data "google_compute_network" "project_default" {
      + description            = (known after apply)
      + gateway_ipv4           = (known after apply)
      + id                     = (known after apply)
      + internal_ipv6_range    = (known after apply)
      + name                   = "default"
      + project                = "sample"
      + self_link              = (known after apply)
      + subnetworks_self_links = (known after apply)
    }
```

**Comment by zli82016** [comment]
Hello, @efazati , can you provide the configuration for these three resources/data source? Thanks.

**Comment by efazati** [comment]
Our setup is quite simple, this is how I get `google_compute_network`
```
data "google_compute_network" "project_default" {
  name    = "default"
  project = module.project_default.project_id

  depends_on = [module.project_default.project_id]
}
```

In reality, inside a module I created a project and then later I used the default network belong to that project

```
resource "google_project" "project" {
  billing_account = var.google_billing_account_id
  name            = var.project_name
  project_id      = var.project_id
  org_id          = var.google_organization_account_id

  labels = {
    "project" : var.project_id,
  }

  lifecycle {
    prevent_destroy = true
  }
}


data "google_compute_network" "default" {
  name    = "default"
  project = google_project.project.project_id
}
```

So technically I didn't even define that network myself, it got created after creating the gcp project

**Comment by zli82016** [comment]
Something changed for the resource `google_project` in the module. I suspect that the change could be the adding of the new field `terraform_labels`. I am not sure if there are other changes.

The change of the module triggered the reread of the data source `google_compute_network`, because the data source depends on the module. Please see the [Hashcorp doc](https://developer.hashicorp.com/terraform/language/data-sources#data-source-arguments).

The workaround is to use the `locals` to reference the resource `google_project`. Can you try that?

**Comment by efazati** [comment]
Yes, you were right. Due to the dependency, after adding new Terraform labels to the project, Terraform assumed the network had changed, which then caused everything to want to change. By removing that dependency, my issue got fixed. Thanks!
