### ISSUE TITLE
Is it intentional that all resources starts with `google-beta` in the sidebar of the google-beta provider's doc?

### ISSUE THREAD

**Issue by shotarok** [hashicorp/terraform-provider-google#16571]
Is it intentional that all resources start with `google-beta` in the sidebar of the google-beta provider's docs? The filter of the sidebar works as a subsequence matching. So we can get a search result with a proper resource name. That said, it'd be clearer if the sidebar also uses appropriate resource names.

<img width="864" alt="google-beta_api_gateway_api___Resources___hashicorp_google-beta___Terraform___Terraform_Registry" src="https://github.com/hashicorp/terraform-provider-google/assets/1156179/b2b0ad6d-ed30-4e7c-ae04-8c0300c64e27">

from https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs

**Comment by edwardmedia** [comment]
yes
