### ISSUE TITLE
`google_tags_tag_binding` fails for regional GKE cluster

### ISSUE THREAD

**Issue by norman-zon** [hashicorp/terraform-provider-google#16574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.6.3

### Provider Version

5.6.0

### Affected Resource(s)

* google_tags_tag_binding

### Terraform Configuration Files

```tf
resource "google_tags_tag_binding" "env" {
    parent    = "//container.googleapis.com/projects/ <project>/locations/europe-west3/clusters/<cluster>"
    tag_value = "tagValues/123456789"
}

```

### Debug Output

https://gist.github.com/norman-zon/c256752349679069f48dbe70fca93b81

### Expected Behavior

The resource should be created succesfully

### Actual Behavior

The API rejected the object.

### Steps to Reproduce

1. `terraform apply`

### References

* #11448

**Comment by edwardmedia** [comment]
@norman-zon the error is from the api. It appears the parent you provided is invalid. Are you able to create the same binding via other means? 

Here the the [api doc](https://cloud.google.com/resource-manager/reference/rest/v3/tagBindings) we can reference.

**Comment by norman-zon** [comment]
@edwardmedia Yes, I can create the binding via the Cloud Console and it is visible with:

```
 gcloud alpha resource-manager tags bindings list \
    --parent=//container.googleapis.com/projects/<project>/locations/europe-west3/clusters/<cluster> \
    --location=europe-west3
```

**Comment by edwardmedia** [comment]
@norman-zon can you share the debug log for your gcloud command execution? (attaching --log-http)

**Comment by imrannayer** [comment]
@norman-zon have you tried [google_tags_location_tag_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding) for this?

**Comment by norman-zon** [comment]
@imrannayer [google_tags_location_tag_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding) worked. 
I overlooked, that this resource exists. Maybe a crosslink in the docs between `google_tags_location_tag_binding` and `google_tags_tag_binding`, explaining the two use cases might help to avoid future confusion.
