### ISSUE TITLE
google_notebooks_instance resources recreated on every terraform apply without any configuration changes due to `service_account_scopes`

### ISSUE THREAD

**Issue by 7pandeys** [hashicorp/terraform-provider-google#16587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.6

provider.google v5.5.0

### Affected Resource(s)

* google_notebooks_instance

### Terraform Configuration Files

```tf
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  vm_image {
    project      = "deeplearning-platform-release"
    image_family = "tf-latest-cpu"
  service_account_scopes = [
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/devstorage.read_write",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email"
  ]
  }
}
```

### Debug Output

Note: No errors are shown in the output even with the debug flag activated.

### Panic Output

There was no crash or panic produced during the terraform apply process.

### Expected Behavior

Terraform should recognize that no changes have been made and should not attempt to recreate the notebook instance resources.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Recreating notebooks in Terraform's google_notebook_instance resource occurs only when the service_account_scopes parameter is utilized; otherwise, recreation does not take place.
[Source](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance)

### References

* (https://github.com/hashicorp/terraform-provider-google/issues/15950)

b/312911294

**Comment by edwardmedia** [comment]
The api does not have `service_account_scopes` in the response.  

```
      - .service_account_scopes: element 0 has vanished
      - .service_account_scopes: element 1 has vanished
      - .service_account_scopes: element 2 has vanished
      - .service_account_scopes: element 3 has vanished
  ```

**Comment by melinath** [comment]
This should be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9915
