### ISSUE TITLE
[Feature Request] Terraform support for pubsub latest feature `Write to bigquery` subscription

### ISSUE THREAD

**Issue by gomrinal** [hashicorp/terraform-provider-google#16597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_pubsub_subscription

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#BigQueryConfig

b/313620289

**Comment by gomrinal** [comment]
![IMG_4266](https://github.com/hashicorp/terraform-provider-google/assets/29385581/8fe4ac4f-621b-4c97-bda9-a310b9b4954f)

**Comment by gomrinal** [comment]
Reference:
https://cloud.google.com/pubsub/docs/create-bigquery-subscription

**Comment by SarahFrench** [comment]
Implementing this feature request appears to be adding support for [the`bigqueryConfig` PubSub API field](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#BigQueryConfig) to the `google_pubsub_subscription` resource.

From a quick look, there doesn't seem to be an equivalent to this in the Eventarc API (figured I'd check as you can achieve lots of similar things with `google_eventarc_trigger` and  `google_pubsub_*` resources). If this feature was also possible via Eventarc I'd expect to see BiqQuery as an option for [the `destination` field in the API](https://cloud.google.com/eventarc/docs/reference/rest/v1/projects.locations.triggers#Destination) but that isn't listed.

**Comment by kamalaboulhosn** [comment]
This already exists: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#example-usage---pubsub-subscription-push-bq

**Comment by SarahFrench** [comment]
Oops, thanks for pointing that out @kamalaboulhosn ! Closing this issue as completed.
