### ISSUE TITLE
google_cloud_run_v2_service Error creating Service: googleapi: Error 409: Resource already exists.

### ISSUE THREAD

**Issue by raulgzm** [hashicorp/terraform-provider-google#16591]
I have a question about using this service and updating it when there are new changes. 
Currently, when I try to execute "terraform apply", I receive an error message saying "Error creating Service: googleapi: Error 409: Resource already exists". 

I would like to create a new revision each time there are new changes. 

Is this a bug? And if not, how can I accomplish this? 

Thank you for your support.

**Comment by edwardmedia** [comment]
@raulgzm are the [examples](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#example-usage---cloudrunv2-service-basic) work for you?

**Comment by edwardmedia** [comment]
@raulgzm is this still a question?
