### ISSUE TITLE
[Feature Request] Terraform support for pubsub latest feature `Write to cloud storage` subscription 

### ISSUE THREAD

**Issue by gomrinal** [hashicorp/terraform-provider-google#16596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please add support for pubsub latest feature i.e write to cloud storage from pubsub. This new feature in pubsub helps user to directly write to GCS bucket so no dataflow pipeline is required in between the pubsub <-> cloud storage if no ETL is required in the middle

### New or Affected Resource(s)

* google_pubsub_subscription

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#CloudStorageConfig

b/313620098

**Comment by gomrinal** [comment]
![IMG_4266](https://github.com/hashicorp/terraform-provider-google/assets/29385581/52c753a0-42f9-4fb4-83c7-88328d56e0f0)

**Comment by gomrinal** [comment]
Reference:
https://cloud.google.com/pubsub/docs/create-cloudstorage-subscription

**Comment by kamalaboulhosn** [comment]
This already exists: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#example-usage---pubsub-subscription-push-cloudstorage

**Comment by SarahFrench** [comment]
Oops, thanks for pointing that out @kamalaboulhosn ! Closing this issue as completed.
