### ISSUE TITLE
GKE fails to create when adding mesh_certificates enabled flag

### ISSUE THREAD

**Issue by jenshonkan84** [hashicorp/terraform-provider-google#16601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  provider = google-beta
  name     = "test-gw"
  location = var.REGION

  network         = var.NETWORK
  subnetwork      = var.SUB_NETWORK
  networking_mode = "VPC_NATIVE"
  ip_allocation_policy {
    cluster_secondary_range_name  = "podnet"
    services_secondary_range_name = "servicenet"
  }
  deletion_protection = false
  # Enabling Autopilot for this cluster
  enable_autopilot = true

  mesh_certificates {
    enable_certificates = true
  }

  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.node-account.email
      oauth_scopes    = ["https://www.googleapis.com/auth/cloud-platform"]
    }
  }
  node_pool_auto_config {
    network_tags {
      tags = ["test-a-tag"]
    }
  }
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = false
  }
}
```

### Debug Output
https://gist.githubusercontent.com/jenshonkan84/fd435a9386c999e9a9d538b46120675c/raw/eb179905bb787e0980cd1cdb7c16154cceccb2b0/gistfile1.txt

### Expected Behavior

Create a GKE cluster with Mesh Certificates feature enabled

meshCertificates:
  enableCertificates: true

### Actual Behavior

Error: googleapi: Error 400: Autopilot clusters must be using GKE metadata server.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0x2c5adfbaf4766fa8"
│   }
│ ]
│ , badRequest
│ 
│   with google_container_cluster.primary,
│   on main.tf line 1, in resource "google_container_cluster" "primary":
│    1: resource "google_container_cluster" "primary" {
│ 
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@jenshonkan84 based on the error you received below, it looks like this is the rule set by the api. There is not much we can do at the provider level. Are you able to create an autopilot with it through other means?

```
googleapi: Error 400: Autopilot clusters must be using GKE metadata server.
```

**Comment by jenshonkan84** [comment]
It works with gcloud. Thats why I think it is strange.

**Comment by edwardmedia** [comment]
@jenshonkan84 can you share the gcloud debug log? attach --log-http in the command

**Comment by jenshonkan84** [comment]
Sorry. I tested some more. And it looks like I lied. :( 

You can only run --enable-mesh-certificates on update of the cluster.

So I tried this.

First I create the cluster like this:

```
resource "google_container_cluster" "sec" {
  provider = google-beta
  name     = "test-gw2"
  location = var.REGION

  network         = var.NETWORK
  subnetwork      = var.SUB_NETWORK
  networking_mode = "VPC_NATIVE"
  ip_allocation_policy {
    cluster_secondary_range_name  = "podnet"
    services_secondary_range_name = "servicenet"
  }
  deletion_protection = false
  # Enabling Autopilot for this cluster
  enable_autopilot = true

#  mesh_certificates {
 #   enable_certificates = true
 # }

  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.node-account.email
      oauth_scopes    = ["https://www.googleapis.com/auth/cloud-platform"]
    }
  }
  node_pool_auto_config {
    network_tags {
      tags = ["test-a-tag"]
    }
  }
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = false
  }
}

```
Then after the cluster is created I comment the section back in:
```
mesh_certificates {
  enable_certificates = true
 }
```

So it looks like this:
```
resource "google_container_cluster" "sec" {
  provider = google-beta
  name     = "test-gw2"
  location = var.REGION

  network         = var.NETWORK
  subnetwork      = var.SUB_NETWORK
  networking_mode = "VPC_NATIVE"
  ip_allocation_policy {
    cluster_secondary_range_name  = "podnet"
    services_secondary_range_name = "servicenet"
  }
  deletion_protection = false
  # Enabling Autopilot for this cluster
  enable_autopilot = true

  mesh_certificates {
    enable_certificates = true
  }

  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.node-account.email
      oauth_scopes    = ["https://www.googleapis.com/auth/cloud-platform"]
    }
  }
  node_pool_auto_config {
    network_tags {
      tags = ["test-a-tag"]
    }
  }
  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = false
  }
}
```  

Then it works. Very strange behavior.  Could this be fixed some how?

**Comment by edwardmedia** [comment]
@jenshonkan84 I doubt this can be "fixed" somehow as this rule is set by the api. There is nothing we can do at the provider. Close this right now
