### ISSUE TITLE
BigQuery Dataset IAM Policy does not work for Federated Identity 

### ISSUE THREAD

**Issue by jgao-m-data** [hashicorp/terraform-provider-google#16607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.6.4
GNU/Linux x86_64  - WSL2
+ provider registry.terraform.io/hashicorp/google v5.7.0

### Affected Resource(s)

* resource "google_bigquery_dataset_iam_binding"
* resource "google_bigquery_dataset_iam_member"

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset_iam_binding" "test_federated" {
  project    = "test-project-id"

  dataset_id = "test_federated_user"
  role       = "roles/bigquery.dataViewer"
  members    = ["principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/title@domain.com"]
}

resource "google_bigquery_dataset_iam_member" "test_federated_member" {
  project    = "test-project-id"
  dataset_id = "test_federated_user"
  role       = "roles/bigquery.dataViewer"
  member     = "principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/name@domain.com"
}

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = ">= 5.6.0"
    }
  }
}

```

### Expected Behavior

Since
+We can give roles/permissions to federated identity/users in the GCP console,
+IAM policy works with Terraform for project level roles for federated identity
BigQuery Dataset level roles should work (in the same way)

### Actual Behavior

│ Error: Error applying IAM policy for Bigquery Dataset test-project-id/test_federated_user: Failed to parse BigQuery Dataset IAM member type: principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/name@domain.com
│
│   with google_bigquery_dataset_iam_binding.test_federated,
│   on main.tf line 2, in resource "google_bigquery_dataset_iam_binding" "test_federated":
│    2: resource "google_bigquery_dataset_iam_binding" "test_federated" 

│ Error: Error applying IAM policy for Bigquery Dataset test-project-id/test_federated_user: Failed to parse BigQuery Dataset IAM member type: principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/title@domain.com
│
│   with google_bigquery_dataset_iam_member.test_federated_member,
│   on main.tf line 10, in resource "google_bigquery_dataset_iam_member" "test_federated_member":
│   10: resource "google_bigquery_dataset_iam_member" "test_federated_member" {
│

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It seems, in the source code (https://github.com/hashicorp/terraform-provider-google/blob/141f32dee6958afb8983c66d1ba2dba72df1c270/google/services/bigquery/iam_bigquery_dataset.go#L215C1-L215C23 ). The function “iamMemberToAccess” hardcoded the iam member types and federated identity with the format (“principal://iam.googleapis.com/…”) was not taken into consideration.

### References

* https://github.com/hashicorp/terraform-provider-google/blob/141f32dee6958afb8983c66d1ba2dba72df1c270/google/services/bigquery/iam_bigquery_dataset.go#L215C1-L215C23
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam#google_bigquery_dataset_iam_policy 
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam

b/313620583

**Comment by edwardmedia** [comment]
Looks like more members need to be added [here](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/bigquery/iam_bigquery_dataset.go#L220)

**Comment by wj-chen** [comment]
Sounds like project IAM handles it fine. @edwardmedia Do you have pointer to how it's done in project IAM or other IAM resources? Wasn't able to find after a quick search. We are missing the context of why exact member type matching had to happen for BQ dataset IAM.

**Comment by originaliang** [comment]
@edwardmedia @wj-chen is there any chance to have a quick fix for it, for example, just adding the federated identities(prefix) in the allowed list?

**Comment by wj-chen** [comment]
We are looking for engineering capacity from the team to look into the feasibility of a quick fix as well as long-term alignment of IAM handling for this resource with the other GCP resources. Thank you for your patience.
