### ISSUE TITLE
google_gke_hub_feature invalid using fleetDefaultMemberConfig block

### ISSUE THREAD

**Issue by bjhshadow** [hashicorp/terraform-provider-google#16603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.7.0
+ provider registry.terraform.io/hashicorp/google-beta v5.7.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)

* google_gke_hub_feature

### Terraform Configuration Files

```tf
resource "google_gke_hub_feature" "asm" {
  for_each = local.enable_asm
  name     = "servicemesh"
  location = "global"
  project  = each.key
  fleetDefaultMemberConfig {
    mesh {
      management = "MANAGEMENT_AUTOMATIC"
    }
  }
}
```

### Expected Behavior

GKE fleet default membership configuration for ASM should be set as per the example provided.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature#example-usage---enable-fleet-default-member-config-service-mesh

### Actual Behavior

Error on plan regarding block unexpected.

### Steps to Reproduce

terraform plan   

### Important Factoids

* Typically run using terraform cloud with service account.
* google_gke_hub_feature works as expected _without_ the default config being added.   Sole issue appears to be with the new block.

### References

 https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature#example-usage---enable-fleet-default-member-config-service-mesh)

https://cloud.google.com/anthos/fleet-management/docs/reference/rest/v1/projects.locations.features#membershipspec.management

**Comment by edwardmedia** [comment]
I think the attribute should be [fleet_default_member_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_feature#fleet_default_member_config)

```tf
resource "google_gke_hub_feature" "feature" {
  name = "issue16603"
  location = "global"
  fleet_default_member_config {
    mesh {
      management = "MANAGEMENT_AUTOMATIC"
    }
  }
}
```
