### ISSUE TITLE
Error when re-creating VPN tunnel: Error creating VpnTunnel: googleapi: Error 400: Invalid value for field 'resource.peerExternalGatewayInterface': '0'. A tunnel with same peer external VPN gateway interface is already associated with the same local VPN gateway interface., invalid

### ISSUE THREAD

**Issue by jeheyer** [hashicorp/terraform-provider-google#16619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 1.6.4

### Affected Resource(s)

* google_compute_vpn_tunnel

### Terraform Configuration Files

```tf
resource "google_compute_vpn_tunnel" "default" {
  project                             = var.project_id
  name                               = var.name
  depends_on                     = [google_compute_ha_vpn_gateway.default, google_compute_external_vpn_gateway.default]
}

```

### Panic Output

N/A

### Expected Behavior

VPN tunnel should be completely destroyed before attempting re-creation

### Actual Behavior

Looks like it's trying to create a the new tunnel before the old one is completely destroyed

module.hybrid-networking.google_compute_router_peer.default: Destroying... [id=projects/my-project-id/regions/us-central1/routers/my-router/if-vpn-0-0]
module.hybrid-networking.google_compute_router_peer.default: Still destroying... [id=projects/my-project-id/regions/us-cent..my-router/if-vpn-0-0, 10s elapsed]
module.hybrid-networking.google_compute_router_peer.default: Destruction complete after 11s
module.hybrid-networking.google_compute_vpn_tunnel.default: Destroying... [id=projects/my-project-id/regions/us-central1/vpnTunnels/vpn-0-0]
**module.hybrid-networking.google_compute_vpn_tunnel.default: Creating...
module.hybrid-networking.google_compute_vpn_tunnel.default: Still destroying... [id=projects/my-project-id/regions/us-central1/vpnTunnels/vpn-0-0, 10s elapsed]**
module.hybrid-networking.google_compute_vpn_tunnel.default: Destruction complete after 11s

Error: Error creating VpnTunnel: googleapi: Error 400: Invalid value for field 'resource.peerExternalGatewayInterface': '0'. A tunnel with same peer external VPN gateway interface is already associated with the same local VPN gateway interface., invalid

### Steps to Reproduce

1. Create a VPN tunnel
2. Change the name
3. Run tf apply

### References

* #0000

**Comment by edwardmedia** [comment]
@jeheyer I can't repro it with the config [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_vpn_tunnel#example-usage---vpn-tunnel-basic). Can you share the config you have and debug log?

**Comment by jeheyer** [comment]
Not sure if it matters, but your example is with google_compute_vpn_gateway,  while mine is with google_compute_**ha_**vpn_gateway.default

**Comment by jeheyer** [comment]
I found out it's only reproducible when using for_each where the key could change.  Example:

```
variable "project_id" {
  type = string
}
variable "region" {
  type    = string
  default = "us-central1"
}
variable "network_name" {
  type    = string
  default = "default"
}
variable "vpn_name" {
  type    = string
  default = "vpn"
}
variable "router_name" {
  type = string
}
variable "shared_secret" {
  type = string
  default = "8675309jenny"
}
variable "ip_range" {
  type = string
  default = "169.254.1.1/30"
}
variable "peer_ip_address" {
  type = string
  default = "169.254.1.2"
}
variable "peer_asn" {
  type = number
  default = 65000
}
variable "vpn_gateway" {
  type = string
}
variable "peer_external_gateway" {
  type = string
}


resource "google_compute_router_interface" "default" {
  for_each                  = { for i, v in [{}] : "${var.vpn_name}-${i}" => true }
  project                 = var.project_id
  region                  = var.region
  name                    = "router-interface-0"
  router                  = var.router_name
  ip_range                = var.ip_range
  vpn_tunnel              = var.vpn_name
  interconnect_attachment = null
  depends_on              = [google_compute_vpn_tunnel.default]
}

resource "google_compute_router_peer" "default" {
  for_each                  = { for i, v in [{}] : "${var.vpn_name}-${i}" => true }
  project                   = var.project_id
  region                    = var.region
  name                      = "router-peer-0"
  router                    = var.router_name
  interface                 = "router-interface-0"
  peer_ip_address           = var.peer_ip_address
  peer_asn                  = var.peer_asn
  advertised_route_priority = 100
  enable                    = true
  enable_ipv6               = false
  depends_on                = [google_compute_router_interface.default]
}

resource "google_compute_vpn_tunnel" "default" {
  for_each                  = { for i, v in [{}] : "${var.vpn_name}-${i}" => true }
  project                         = var.project_id
  region                          = var.region
  name                            = var.vpn_name
  router                          = var.router_name
  peer_ip                         = null
  vpn_gateway                     = var.vpn_gateway
  peer_external_gateway           = var.peer_external_gateway
  peer_gcp_gateway                = null
  ike_version                     = 2
  shared_secret                   = var.shared_secret
  vpn_gateway_interface           = 0
  peer_external_gateway_interface = 0
}

}

```

**Comment by edwardmedia** [comment]
@jeheyer in the case, you might want to look closer into the dynamic code. From the resource itself, it works by design. Does this make sense?

**Comment by jeheyer** [comment]
Well, the code works by design as well :-) When the VPN tunnel name changes, the resource gets re-created (which it would have to do anyway as changing names is not possible in GCP).  

The problem is really either one of these two things:

1) Terraform is too dumb to understand it's re-creating the same resource, and essentially hitting a race condition where it starts creating the 'new' thing before the old one is completely destroyed
2) Provider either does or doesn't understand the same pair of VPN gateway interfaces is the same VPN tunnel, perhaps influencing the above.

Same thing probably happens with the router interfaces and router peers, just doesn't show up because they're depending on the VPN tunnels.

Anyway, work-around would be depend on a time_sleep and/or null_resource and loop through those with the same for_each.  This basically gives the VPN tunnels an explicit dependency and causes them not to be destroyed/created in parallel.

**Comment by edwardmedia** [comment]
@jeheyer I feel your pain but there is limitation by using Terraform as a tool because in most cases, each provider resource handles a single api endpoint, and focuses a very specific cloud resource. Usually it does not have knowledge about other resources at the provider level. That is why you need to use the Terraform code to put them together if you are building a system. 

To address your two things:

1. It is a bug if the provider keeps asking re-creating the same resource when no change in the configuration. Please provide  the details if this is the case.
2. Not sure if I understand what you said. But in your config, it has `depends_on`, it should see a chain actions. If you recreate google_compute_ha_vpn_gateway, it should trigger update on google_compute_vpn_tunnel accordingly. 

Do you see an issue here?

**Comment by jeheyer** [comment]
I'm not sure you're following me.  

1. Configuration is changing, so re-creation of the resource is expected.
2. I'm not changing the HA VPN gateway.  Doing so would require re-creation of all VPN tunnels.  The depends on is there because the VPN gateway(s) must be created before VPN tunnels can be done.

So this is my stupid fix:

```
resource "null_resource" "vpn_tunnels" {
  for_each = { for i, v in local.vpn_tunnels : v.key => true }
}

resource "google_compute_vpn_tunnel" "default" {
  for_each                        = { for i, v in local.vpn_tunnels : v.key => v }
  depends_on = [    null_resource.vpn_tunnels,  ]
}
```
