### ISSUE TITLE
Add revision labels on google_cloud_run_v2_service 

### ISSUE THREAD

**Issue by DKbyo** [hashicorp/terraform-provider-google#16624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently revision labels are the only ones used on Billing reports and this  Terraform plugin doesn't support them, it only supports Service labels, based on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#labels the labels should be used for billing, so should be set at the Revision label as well, as being set on Cloud Console.

### New or Affected Resource(s)

* google_cloud_run_v2_service

### Potential Terraform Configuration

As you already have on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#labels

```tf
resource "google_cloud_run_v2_service" "default-2" {
  name     = "cloudrun-labels"
  location = "us-central1"
  ingress = "INGRESS_TRAFFIC_ALL"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
    labels = {
          key = "value"
    }
  }
```

Labels might be set at Service Level and at Revision Level.

### References

- Cloud Run Labels used for Billing
 https://cloud.google.com/run/docs/configuring/services/labels#yaml
- Revision Template Spec
 https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services#RevisionTemplate

b/314943705

**Comment by tcs2340445** [comment]
And also 
Labels configured via Terraform for google_cloud_run_v2_service, not visible in Google UI

**Comment by mkavl** [comment]
Hi @melinath 

the issue we're facing is that the Cloud Run services which are created and labeled via Terraform, are not getting reported to billing because the revisions don't inherit the label set on the service level.

**Comment by melinath** [comment]
@mkavl [google_cloud_run_v2_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service) supports `labels` (only apply to the service itself) and `template.labels` (used when creating revisions). Does `template.labels` meet your needs?

If not - the [API docs](https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services) don't seem to include any other labels fields - are you able to configure this with gcloud or using the API directly? What API fields are missing from the Terraform request?

**Comment by yanweiguo** [comment]
I can confirm that `template.labels` are the revision labels in `google_cloud_run_v2_service`.
