### ISSUE TITLE
Unable to scale instances in a stateful MIG

### ISSUE THREAD

**Issue by drcapulet** [hashicorp/terraform-provider-google#16621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.7.0
+ provider registry.terraform.io/hashicorp/google-beta v5.7.0
```

### Affected Resource(s)

* google_compute_instance_group_manager
* google_compute_per_instance_config

### Terraform Configuration Files

```tf
data "google_compute_image" "cos" {
  family  = "cos-stable"
  project = "cos-cloud"
}

data "google_project" "main" {}

resource "google_compute_address" "main" {
  count = 4

  address_type = "EXTERNAL"
  name         = format("alex-testing-%02d", count.index + 1)
  region       = "us-central1"
}

resource "google_compute_instance_template" "main" {
  description          = "Instance template"
  instance_description = "Instance description"
  machine_type         = "e2-highcpu-2"
  name_prefix          = "alex-testing-"
  region               = "us-central1"

  # Ephemeral OS boot disk
  disk {
    auto_delete  = true
    boot         = true
    disk_size_gb = 10
    disk_type    = "pd-ssd"
    source_image = data.google_compute_image.cos.self_link
  }

  network_interface {
    network    = "default"
    subnetwork = "default"
  }

  # Instance Templates cannot be updated after creation with the Google Cloud Platform API.
  # In order to update an Instance Template, Terraform will destroy the existing resource and create a replacement
  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_group_manager" "main" {
  provider = google-beta

  base_instance_name = "alex-testing"
  name               = "alex-testing-us-central1-f-igm"

  project                   = data.google_project.main.name
  target_size               = 0
  wait_for_instances        = true
  wait_for_instances_status = "STABLE"
  zone                      = "us-central1-f"

  update_policy {
    max_unavailable_fixed = 1
    minimal_action        = "REPLACE"
    min_ready_sec         = 300
    replacement_method    = "RECREATE"
    type                  = "PROACTIVE"
  }

  version {
    instance_template = google_compute_instance_template.main.self_link
  }

  lifecycle {
    ignore_changes = [
      # https://github.com/hashicorp/terraform-provider-google/issues/15911
      target_size,
    ]
  }

  timeouts {
    create = "60m"
  }
}

resource "google_compute_per_instance_config" "main" {
  count = 3

  name                   = format("alex-testing-%02d", count.index + 1)
  instance_group_manager = google_compute_instance_group_manager.main.name
  zone                   = google_compute_instance_group_manager.main.zone

  preserved_state {
    external_ip {
      auto_delete    = "NEVER"
      interface_name = "nic0"

      ip_address {
        address = google_compute_address.main[count.index].self_link
      }
    }
  }
}
```

### Debug Output

Don't think that's needed here.

### Panic Output

N/A

### Expected Behavior

When changing the count on `google_compute_per_instance_config` from 3 to 2, the instance is deleted.

### Actual Behavior

The instance is updated to remove the stateful metadata, but still alive. If instead you were to comment out all resources so they're all destroyed, the instances are first cycled to remove the stateful metadata and then the instance group is deleted - for instances that take a while to cycle (like when using connection draining), this can take a very long time.

If you instead set `target_size` to 3 and have a count of 3 on `google_compute_per_instance_config` you end up with 6 nodes. You also have an issue when changing `target_size` - you get two nodes being spun up instead of one if you increase `target_size` to 4 and count on `google_compute_per_instance_config` to `4` - and in my case the second apply (since it reads 5 nodes instead of 4) deleted the non-stateful instance. If you instead just update `target_size` to the correct value after first applying an increase to `google_compute_per_instance_config` you're still stuck with the inability to remove an instance in a single shot.

It seems to be impossible to safely manage stateful MIGs with Terraform - it's also just very surprising that if I create a per-instance config, reverting that change does not tear down those resources. I do notice the console seems to have similar issues as well, but it does avoid the double instance spin up (since you can't create an instance via the UI) and anecdotally it seems to always delete the non-stateful ones over stateful instances.

### Steps to Reproduce

1. `terraform apply`
1. Change count of `google_compute_per_instance_config` from 3 to 2.
1. `terraform apply`

### Important Factoids

- Per #15911, `target_size` is in `ignore_changes` in the original example.

b/314111359

**Comment by drcapulet** [comment]
@edwardmedia Yes with the following:

```bash
gcloud compute instance-groups managed create-instance alex-testing-us-central1-f-igm \
  --instance alex-testing-01 \
  --stateful-external-ip address=MYIP,interface-name=nic0,auto-delete=never \
  --zone us-central1-f
```

```bash
gcloud compute instance-groups managed delete-instances alex-testing-us-central1-f-igm \
  --instances=alex-testing-01 \
  --zone us-central1-f
```

**Comment by edwardmedia** [comment]
Looks like a dup of https://github.com/hashicorp/terraform-provider-google/issues/9042

**Comment by edwardmedia** [comment]
@drcapulet I do see the instance failed to be removed on the console although the terraform apply results succeeded.

Here is the command the current terraform call
```
POST https://compute.googleapis.com/compute/v1/projects/myproject/zones/us-central1-f/instanceGroupManagers/my-testing-us-central1-f-igm/deletePerInstanceConfigs
{"names": ["alex-testing-03"]}
```

Using below command leads to the right result. A code fix is needed in `google_compute_per_instance_config`. 
```
POST https://compute.googleapis.com/compute/v1/projects/myproject/zones/us-central1-f/instanceGroupManagers/my-testing-us-central1-f-igm/deleteInstances
{"instances": ["https://compute.googleapis.com/compute/v1/projects/myproject/zones/us-central1-f/instances/my-instances-03"]}
```

**Comment by drcapulet** [comment]
@edwardmedia If I were to submit a PR to make that happen, would you prefer it be put behind a boolean option since the behavior change would be breaking?

**Comment by shuyama1** [comment]
@drcapulet I saw you made a fix PR linked to this ticket. Thanks for making the contribution! Can you confirm if the issues have been resolved by the fix and the ticket can be safely closed? Or if there's something else needed and we should keep this open? Thanks.

**Comment by drcapulet** [comment]
@shuyama1 Ah yeah sorry - should have noted that PR "closed" this issue.
