### ISSUE TITLE
Add default_tags for all ressources support

### ISSUE THREAD

**Issue by YassineAllaoui** [hashicorp/terraform-provider-google#16635]
# Background

# What kind of contribution is this issue about?
Default Tags at the provider level

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google/issues/0000

# Details

**Comment by melinath** [comment]
Support for default labels was added in version 5.0.0: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade

If you have a specific resource that is missing support please open a new request that has more details. Thanks!
