### ISSUE TITLE
Adding support for Google Cloud NetApp Active Directory

### ISSUE THREAD

**Issue by paavan-gopala-reddy** [hashicorp/terraform-provider-google#16633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

ActiveDirectory is the public representation of the active directory config.

### New or Affected Resource(s)

google_netapp_active_directory

### Potential Terraform Configuration

resource "google_netapp_active_directory" "<%= ctx[:primary_resource_id] %>" {
    active_directory_id = "test_netapp_ad"
    location = "us-central1"
    domain = "ad.internal"
    dns = "your_dns_ip"
    net_bios_prefix = "smbserver"
    username = "your_ad_username"
    password = "your_ad_password"
  }

**Comment by shuyama1** [comment]
resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/9546
