### ISSUE TITLE
Make .go-version files in TPG and TPGB be controlled by Magic Modules

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16641]
# Background

# What kind of contribution is this issue about?

Go version upgrades

# Related PR(s), if any:

* https://github.com/hashicorp/terraform-provider-google-beta/pull/6687
* https://github.com/hashicorp/terraform-provider-google/pull/16640

# Details

By moving these files under the control of MM we can reduce the number of PRs required to perform a Go version upgrade and help make the process smooth for maintainers.

Currently the process to upgrade the Go version includes:
- PR to upgrade Dockerfiles
- PR to upgrade everything else in Magic Modules (tested in the PR using the image generated from merging the first PR)
- PR to update .go-version in TPG
- PR to update .go-version in TPGB
- PR to update go.mod in terraform-google-conversion

**Comment by SarahFrench** [comment]
I don't imagine that there are situations where we'd want TPG and TPGB to be using different Go versions, so having a static file stored in Magic Modules that is updated once and then causes synchronised changes in TPG/TPGB would be a good change. However there might be reasons why this hasn't been done yet, so worth discussing in triage.

As far as I know, this file is mainly used for TeamCity to know which version of Go should be used for acceptance tests.

**Comment by melinath** [comment]
notes from triage:

- also update TGC go.mod to be managed
- Document process in the Wiki (for now)

**Comment by SarahFrench** [comment]
I did not document the upgrade process in the wiki 😓  - I'm adding this task to the new issue to upgrade to Go 1.21

**Comment by SarahFrench** [comment]
Closing this issue as completed per the title of the issue.

I've opened this issue https://github.com/hashicorp/terraform-provider-google/issues/17480 to cover improving the upgrade process for TGC.

And included documenting the upgrade process as part of https://github.com/hashicorp/terraform-provider-google/issues/17481
