### ISSUE TITLE
Failing test(s): TestAccLoggingProjectSink_updatePreservesCustomWriter

### ISSUE THREAD

**Issue by edwardmedia** [hashicorp/terraform-provider-google#16659]
### Failure rates

- 91.1% since 2023-10-12

https://github.com/GoogleCloudPlatform/magic-modules/pull/9526#issuecomment-1836807816
https://github.com/GoogleCloudPlatform/magic-modules/pull/9561#issuecomment-1836771758

### Impacted tests

- TestAccLoggingProjectSink_updatePreservesCustomWriter

### Affected Resource(s)

* google_logging_project_sink

### Nightly build test history

- [TestAccLoggingProjectSink_updatePreservesCustomWriter](https://hashicorp.teamcity.com/test/1249286244389931919?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccLoggingProjectSink_updatePreservesCustomWriter
=== PAUSE TestAccLoggingProjectSink_updatePreservesCustomWriter
=== CONT  TestAccLoggingProjectSink_updatePreservesCustomWriter
    vcr_utils.go:152: Step 1/4 error: Error running apply: exit status 1
        Error: Error creating Bucket: googleapi: Error 400: service account `service-org-*******@gcp-sa-logging.iam.gserviceaccount.com` must have both encrypt and decrypt access to the CMEK key `projects/ci-test-project-188019/locations/us-central1/keyRings/tf-test-keyring-asruliw04f/cryptoKeys/tf-test-key-asruliw04f`
          with google_logging_project_bucket_config.destination-bucket,
          on terraform_plugin_test.tf line 9, in resource "google_logging_project_bucket_config" "destination-bucket":
           9: resource "google_logging_project_bucket_config" "destination-bucket" {
--- FAIL: TestAccLoggingProjectSink_updatePreservesCustomWriter (54.24s)
FAIL
```

**Comment by melinath** [comment]
Test was added in https://github.com/hashicorp/terraform-provider-google/issues/14893 - and I see the same failure there. I'm not sure why it eventually succeeded... maybe they were just starting rollout of the permissions check or something?

**Comment by melinath** [comment]
This is weirder than we initially thought - the _nightly_ projects are running into errors regarding access to the _CI pipeline_ project's keys. That's because the logging settings are configured at the organization level, and the organization is shared across all test environments.

**Comment by melinath** [comment]
This has also previously failed with the error:

```
service-XXXXXXXX@gcp-sa-logging.iam.gserviceaccount.com does not have iam.serviceAccounts.getAccessToken permissions on tf-test-sink-sa36wpcg3a0c@ci-test-project-188019.iam.gserviceaccount.com
```

It looks like that failure is probably related to IAM propagation delays.
