### ISSUE TITLE
data google_secret_manager_secret does not support full id

### ISSUE THREAD

**Issue by silvajp2** [hashicorp/terraform-provider-google#16666]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.6.5
on linux_amd64
```

### Affected Resource(s)

* google_secret_manager_secret

### Terraform Configuration Files

# Copy-paste your Terraform configurations here.

```terraform
data "google_secret_manager_secret" "secret" {
  secret_id = "projects/#####/secrets/stg-infra-apikey-general_example-apikey"
}
```

### Expected Behavior

Terraform should honor the id received and the plan should have applied correctly instead. 
 
### Actual Behavior

Terraform tries to prepend the `projects/#####/secrets` to the Id used on the data.

The plan fails to apply, because the resource can't be found:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: projects/#####/secrets/projects/#####/secrets/stg-infra-apikey-general_example-apikey not found
│ 
│   with module.apikey.data.google_secret_manager_secret.secret,
│   on ../../../../modules/gcp/api/apikey/dependencies.tf line 6, in data "google_secret_manager_secret" "secret":
│    6: data "google_secret_manager_secret" "secret" {
│ 
```

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@silvajp2 what do you meant here for the expected behavior?

```
Terraform should honor the id received and the plan should have applied correctly instead.
```

How did you create the `google_secret_manager_secret`? Assume if you created it like the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#example-usage---secret-config-basic), what the [secret_id](secret_id) was it?

**Comment by silvajp2** [comment]
@edwardmedia Thank you for the response!

Yes, it works fine when you do that because it always adds the `projects/#####/secrets` at the beginning!

But if you look into the [secret_manager_secret](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret#id) resource id attribute is `projects/{{project}}/secrets/{{secret_id}} `  so when you try to use the id attribute to retrieve a secret it fails as shown.

**Comment by edwardmedia** [comment]
@silvajp2 does below config work for you?

```tf
data "google_secret_manager_secret" "qa" {
  secret_id = "secret"
}
```

**Comment by edwardmedia** [comment]
@silvajp2 is this still an issue?

**Comment by edwardmedia** [comment]
@silvajp2 closing assuming it is no longer an issue
