### ISSUE TITLE
project did match required format 

### ISSUE THREAD

**Issue by dwschewe10** [hashicorp/terraform-provider-google#16671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

➜  terraform git:(develop) ✗ terraform -v
Terraform v1.6.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v5.8.0
+ provider registry.terraform.io/hashicorp/random v3.6.0

### Affected Resource(s)

google_api_gateway_gateway

### Terraform Configuration Files

#provider.tf 
provider "google-beta" {
}

provider "google" {
}

provider "google" {
  alias = "iam"
}

# versions.tf
terraform {
  required_version = ">= 1.3"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "< 5.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 5.8"
    }
  }
}

locals {
  api_config_id_prefix     = var.api_config_id_prefix
  api_id                   = var.api_id
  gateway_id               = var.gateway_id
  display_name             = var.api_display_name
}

# Create the API Gateway API
###
resource "google_api_gateway_api" "api_gw" {
  provider     = google-beta
  api_id       = local.api_id
  project      = var.project_id
  display_name = local.display_name
}

## Create the API Gateway config
resource "google_api_gateway_api_config" "api_config" {
  provider             = google-beta
  api                  = google_api_gateway_api.api_gw.api_id
  api_config_id_prefix = local.api_config_id_prefix
  project              = var.project_id
  display_name         = local.display_name

  openapi_documents {
    document {
      path = "${path.root}/spec.yaml"
      contents = filebase64("${path.root}/spec.yaml")
    }
  }
  lifecycle {
    create_before_destroy = true
  }

  gateway_config {
    backend_config {
      google_service_account = "scaler-runner@${var.prod_ss_project_id}.iam.gserviceaccount.com"
    }
  }
    depends_on = [google_service_account.compute,
                google_project_iam_binding.compute]
}

## Create the API Gateway gateway
resource "google_api_gateway_gateway" "gw" {
  provider = google-beta
  region   = var.region
  project  = var.project_id

  api_config   = google_api_gateway_api_config.api_config.id

  gateway_id   = local.gateway_id
  display_name = local.display_name

  depends_on   = [google_api_gateway_api_config.api_config]
}

### Expected Behavior

A google api gateway should have been created 

### Actual Behavior

│ Error: Error creating Gateway: googleapi: Error 400: Resource name "projects/123456789012/locations/us-east4/gateways/github_gateway2" did not match the required format ^projects/([a-z0-9-]+)/locations/([a-z0-9-]+)(/([a-z]+)/([a-z0-9-.]+))+$

### Steps to Reproduce

I ran a TF apply with the following terraform.tfvars file 

github_project_id  = "pcgke-base-prod-gke-123d"
region             = "us-east4"
subnetwork         = "default"
prod_ss_project_id = "pcgke-base-prod-ss-123b"
disk_size_gb       = "20"
runner_image       = "debian-11-bullseye-v20231115"
api_id               = "clickopsapi2"
api_display_name     = "github_runner_api2"
api_config_id        = "github_gateway_config2"
api_config_id_prefix = "prefix"
gateway_id           = "github_gateway2"

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@dwschewe10 can you try below one instead of "github_gateway2"?

```
gateway_id = "github-gateway2"
```

**Comment by edwardmedia** [comment]
@dwschewe10 is this still an issue?

**Comment by edwardmedia** [comment]
@dwschewe10 closing this assuming it is no longer an issue
