### ISSUE TITLE
Failing test(s): TestAccLoggingBucketConfig* , TestAccLoggingLinkedDataset* -  "KMS key location must match the bucket location"

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16699]
### Failure rates

- 100% since 2023-11-11

### Impacted tests

- TestAccLoggingBucketConfigProject_indexConfigs
- TestAccLoggingBucketConfig_CreateBuckets_withCustomId
- TestAccLoggingLinkedDataset_loggingLinkedDatasetAllParamsExample
- TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample

### Affected Resource(s)

* google_logging_project_bucket_config

### Nightly build test history

- [TestAccLoggingBucketConfigProject_indexConfigs](https://hashicorp.teamcity.com/test/1457422032996945523?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccLoggingBucketConfig_CreateBuckets_withCustomId](https://hashicorp.teamcity.com/test/6860516122074752105?currentProjectId=TerraformProviders_Google_NightlyTests)
- [TestAccLoggingLinkedDataset_loggingLinkedDatasetAllParamsExample](https://hashicorp.teamcity.com/test/-8108513199982959115?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample](https://hashicorp.teamcity.com/test/-6334321899536447071?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample
=== PAUSE TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample
=== CONT  TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating Bucket: googleapi: Error 400: KMS key projects/ci-test-project-188019/locations/us-central1/keyRings/tf-test-keyring-asruliw04f/cryptoKeys/tf-test-key-asruliw04f (from resource policy) location must match the bucket location global for regional buckets.
          with google_logging_project_bucket_config.logging_linked_dataset,
          on terraform_plugin_test.tf line 2, in resource "google_logging_project_bucket_config" "logging_linked_dataset":
           2: resource "google_logging_project_bucket_config" "logging_linked_dataset" {
--- FAIL: TestAccLoggingLinkedDataset_loggingLinkedDatasetBasicExample (4.94s)
FAIL
```

b/315294874

**Comment by rileykarson** [comment]
These have been stable since 2023-12-08
