### ISSUE TITLE
Failing test(s): TestAccSqlUser_postgresIAM

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16704]
### Failure rates

- 100% since 2023-10-11

### Impacted tests

- TestAccSqlUser_postgresIAM

### Affected Resource(s)

* google_sql_user

### Nightly build test history

- [TestAccSqlUser_postgresIAM](https://hashicorp.teamcity.com/test/-8931663425942659432?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
Error:
    Error, failed to insert user admin into instance tf-test-5565518330345401337:
        googleapi: Error 400: Invalid request: Provided CLOUD_IAM_USER: admin, does not exist., invalid
```

b/315953533

**Comment by SarahFrench** [comment]
This issue appears to already be identified here: https://github.com/hashicorp/terraform-provider-google/issues/14233

Maybe the 30s sleep in the acceptance test stopped being sufficient on October 11th

**Comment by shuyama1** [comment]
Increasing the sleep time doesn't seem to fix the issue. I suspect this may be related to a backend change b/250047255

**Comment by melinath** [comment]
Note: this is now failing on PR builds as well.

**Comment by shuyama1** [comment]
Skipped the test in https://github.com/GoogleCloudPlatform/magic-modules/pull/10420 to avoid generating noise for PR builds.
We'll need to re-enable the test before closing this ticket.
