### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_updatable

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16706]
### Failure rates

- 100% since 2023-11-10

### Impacted tests

- TestAccDataprocCluster_updatable

### Affected Resource(s)

* google_dataproc_cluster

### Nightly build test history

- [TestAccDataprocCluster_updatable](https://hashicorp.teamcity.com/test/2482557752504464141?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccDataprocCluster_updatable
=== PAUSE TestAccDataprocCluster_updatable
=== CONT  TestAccDataprocCluster_updatable
    vcr_utils.go:152: Step 2/3 error: Error running apply: exit status 1
        Error: Error waiting for updating Dataproc cluster : Error code 2, message: No agent on master node(s) reported valid Instance Domain value
          with google_dataproc_cluster.updatable,
          on terraform_plugin_test.tf line 2, in resource "google_dataproc_cluster" "updatable":
           2: resource "google_dataproc_cluster" "updatable" {
--- FAIL: TestAccDataprocCluster_updatable (348.58s)
FAIL
```

Note: there's also the subnetwork/default not ready error affecting this test, which is covered here: https://github.com/hashicorp/terraform-provider-google/issues/16313

b/315953678

**Comment by Padmaar** [comment]
Is this a flaky test or consistently failing with this error?

**Comment by SarahFrench** [comment]
The tests have been consistently failing due to the error in the issue description. In the chart below the read bars indicate tests failures, failures that happen after a duration of >3minutes are due to the error above. Tests that fail faster (<1m) are due to another issue that is to do with networking, and it looks like if those networking issues didn't occur then the usual error would have occurred later in the test run.

![Screenshot 2024-02-01 at 10 28 28](https://github.com/hashicorp/terraform-provider-google/assets/15078782/a125701c-12d3-4171-adb9-65cbd926ecd6)

**Comment by Harwayne** [comment]
Dataproc pushed a server side fix around March 14th that I believe should have fixed this test. I don't have access to TeamCity. Is the test still failing?

**Comment by SarahFrench** [comment]
![Screenshot 2024-03-27 at 23 23 20](https://github.com/hashicorp/terraform-provider-google/assets/15078782/b2abe43f-e475-47a0-bbc9-37cd3950c804)

The test has started passing 100% of the time since early-mid March!

Closing as complete.
