### ISSUE TITLE
Failing test(s): TestAccTPUNode_tpuNodeFullTestExample

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16703]
### Failure rates

- 33% since 2023-11-28

### Impacted tests

- TestAccTPUNode_tpuNodeFullTestExample

### Affected Resource(s)

* google_tpu_node

### Nightly build test history

- [TestAccTPUNode_tpuNodeFullTestExample](https://hashicorp.teamcity.com/test/-5152197187456236967?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A64437%29%2Cid%3A2000000005)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccTPUNode_tpuNodeFullTestExample
=== PAUSE TestAccTPUNode_tpuNodeFullTestExample
=== CONT  TestAccTPUNode_tpuNodeFullTestExample
    vcr_utils.go:152: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_tpu_node.tpu will be updated in-place
          ~ resource "google_tpu_node" "tpu" {
                id                     = "projects/ci-test-project-nightly-ga/locations/us-central1-b/nodes/tf-test-test-tpuzcpco2itte"
                name                   = "tf-test-test-tpuzcpco2itte"
              ~ tensorflow_version     = "2.10.0" -> "2.11.0"
                # (12 unchanged attributes hidden)
                # (1 unchanged block hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccTPUNode_tpuNodeFullTestExample (289.90s)
FAIL
```

b/315953720

**Comment by SarahFrench** [comment]
This appears to be an issue with the design of the acceptance test's Terraform configuration:

```hcl
data "google_tpu_tensorflow_versions" "available" {
}


resource "google_tpu_node" "tpu" {
  name = "tf-test-test-tpu%{random_suffix}"
  zone = "us-central1-b"

  accelerator_type = "v3-8"

  tensorflow_version = data.google_tpu_tensorflow_versions.available.versions[0]

  description = "Terraform Google Provider test TPU"
  use_service_networking = true
  network = data.google_compute_network.network.id

  labels = {
    foo = "bar"
  }

  scheduling_config {
    preemptible = true
  }
}

data "google_compute_network" "network" {
  name = "%{network_name}"
}
```

Particularly the `tensorflow_version = data.google_tpu_tensorflow_versions.available.versions[0]` line.

I think by the test provisioning the resource we affect the list of available versions returned by that data source, which results in a new version value being passed to `tensorflow_version` and causes a non-empty plan at the end of the test.
`

**Comment by rileykarson** [comment]
We may want to assure that the zones are the same, the datasource should specify the same zone as where we're provisioning the resource. Available versions are not the same across locations.
