### ISSUE TITLE
google_dataflow_flex_template_job - Error: The terraform-provider-google-beta_v5.8.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by jepma** [hashicorp/terraform-provider-google#16713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.6.5
on darwin_amd64
+ provider registry.terraform.io/grafana/grafana v2.7.0
+ provider registry.terraform.io/hashicorp/google v5.8.0
+ provider registry.terraform.io/hashicorp/google-beta v5.8.0

### Affected Resource(s)

* google_dataflow_flex_template_job

### Terraform Configuration Files

```tf
resource "google_dataflow_flex_template_job" "default" {
  provider = google-beta

  lifecycle {
    ignore_changes = [
      # Ignore changes to max_workers and min_workers. because this will be 
      #   managed by the autoscaler
      max_workers, num_workers
    ]
  }

  count = var.disableIngestion ? 0 : 1

  project                 = var.project_id
  name                    = "test"
  region                  = var.region
  container_spec_gcs_path = "${data.google_storage_bucket.artifacts.url}/${data.google_storage_bucket_object.flex_template_metadata.name}"

  service_account_email = google_service_account.sa.email
  staging_location      = "${data.google_storage_bucket.temporary.url}/validator/staging"
  temp_location         = "${data.google_storage_bucket.temporary.url}/validator/temp/"
  network               = "default"
  subnetwork            = "regions/europe-west4/subnetworks/subnet-01"
  max_workers           = 2
  num_workers           = 1

  parameters = {
    productVersion = "1.1.0"
    project        = var.project_id

    environment           = local.environments[terraform.workspace].shorthand
    enableStreamingEngine = true
    runner                = "DataflowRunner"
  }
}
```

### Panic Output

```tf
Error: Plugin did not respond
│ 
│   with google_dataflow_flex_template_job.default[0],
│   on dataflow.tf line 16, in resource "google_dataflow_flex_template_job" "default":
│   16: resource "google_dataflow_flex_template_job" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google-beta_v5.8.0_x5 plugin:

panic: interface conversion: interface {} is string, not bool

goroutine 233 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataflow.resourceDataflowFlexJobSetupEnv(_, _)
        github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataflow/resource_dataflow_flex_template_job.go:367 +0x8d6
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataflow.resourceDataflowFlexTemplateJobCreate(0x0?, {0x49dde40?, 0xc00139ea80})
        github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataflow/resource_dataflow_flex_template_job.go:276 +0x188
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x51ea838?, {0x51ea838?, 0xc00165ed50?}, 0xd?, {0x49dde40?, 0xc00139ea80?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011c60e0, {0x51ea838, 0xc00165ed50}, 0xc000e12b60, 0xc00182c480, {0x49dde40, 0xc00139ea80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00127e840, {0x51ea838?, 0xc00165ec30?}, 0xc001461400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000257f20, 0xc000257f80, {0xc001bd0280, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000394d20, {0x51ea838?, 0xc001633d70?}, 0xc0012d51f0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x494bd20?, 0xc000394d20}, {0x51ea838, 0xc001633d70}, 0xc0012d5180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011ce000, {0x51f4320, 0xc00025cd00}, 0xc0013c4fc0, 0xc00070bad0, 0x6bce060, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xdf1
google.golang.org/grpc.(*Server).handleStream(0xc0011ce000, {0x51f4320, 0xc00025cd00}, 0xc0013c4fc0, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.58.3/server.go:997 +0x15c

Error: The terraform-provider-google-beta_v5.8.0_x5 plugin crashed!
```

### Steps to Reproduce

1. `terraform apply`

b/315457108

**Comment by edwardmedia** [comment]
I can repro this. Adding enableStreamingEngine causes the crash

```tf
  parameters = {
    productVersion = "1.1.0"
    project        = var.project_id

    environment           = local.environments[terraform.workspace].shorthand
    enableStreamingEngine = true <----- this line
    runner                = "DataflowRunner"
  }
```

Questionable code [here](https://github.com/hashicorp/terraform-provider-google-beta/blob/dc95a1bdba2b7123ef54f39b4bb4f59a4d977038/google-beta/services/dataflow/resource_dataflow_flex_template_job.go#L367)

**Comment by AnkurSarode** [comment]
I am also facing this issue without passing the `enableStreamingEngine` but I am passing the max_num_workers as a part of the parameters map.

**Comment by damondouglas** [comment]
Thank you for reporting this helpful issue. I recommend using `enable_streaming_engine = true` outside the `parameters` block of `google_dataflow_flex_template_job`. For example, I was able to successfully submit a Dataflow Flex template Job via:

```
resource "google_dataflow_flex_template_job" "pubsub_to_gcs" {
  provider = google-beta
  container_spec_gcs_path = "gs://dataflow-templates/latest/flex/Cloud_PubSub_to_GCS_Text_Flex"
  name                    = "gcs-to-pubsub-${random_string.postfix.result}"
  region = var.region
  temp_location = "gs://${data.google_storage_bucket.default.name}/temp"

  enable_streaming_engine = true

  parameters = {
    outputDirectory = "gs://${data.google_storage_bucket.default.name}/output/"
    inputTopic = data.google_pubsub_topic.output.id
    outputFilenamePrefix = "out-"
  }
}
```

I was able to replicate the reported issue via both `enableStreamingEngine = true` and `"true"` when provided under the `parameters` block:

```
resource "google_dataflow_flex_template_job" "pubsub_to_gcs" {
  // abbreviated view of resource configuration
   parameters = {
      enableStreamingEngine = true // "true" is also invalid
   }
}
```

Researching this issue taught me the following, though I haven't fully tested these principles. Dataflow templates have two groups of parameters, those that configure the runtime environment and those that configure template specific parameters. I commented on both below.

### Runtime Environment parameters

As terraform is essentially a wrapper around APIs for resource provisioning, the configuration details that are shared among templates map to the [RuntimeEnvironment](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/RuntimeEnvironment). In the context of the `google_dataflow_flex_template_job`, these are named in lower snake case. For example, `enableStreamingEngine` should be defined in the resource block as `enable_streaming_engine`.

### Template specific parameters

Within the `parameters` block of `google_dataflow_flex_template_job`, we find configuration details specific to that template. For example, in the [Pub/Sub to GCS Text](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/googlecloud-to-googlecloud/README_Cloud_PubSub_to_GCS_Text_Flex.md) template we have `outputDirectory`. Most of the templates are written in Java and therefore accept camel case. Note that these parameters, [per the API specification](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/LaunchTemplateParameters) should be a string key and string value pair.

**Comment by piyushpatel2005** [comment]
@damondouglas I think we don't need `enable_streaming_engine=true` to be able to submit streaming jobs. I was also able to submit a job which reads from kafka and writes to kafka without this option and yes it was still streaming in my case.

**Comment by damondouglas** [comment]
Good point. The reason for my comment is that it serves as a teaching moment to understand the difference between the various parameters, not so much to resolve this particular issue
