### ISSUE TITLE
Failing test(s): TestAccFirestoreDatabase_firestoreDefaultDatabaseExample

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16723]
### Failure rates

- 100% since 2023-11-22

### Impacted tests

- TestAccFirestoreDatabase_firestoreDefaultDatabaseExample

### Affected Resource(s)

* google_firestore_database

### Nightly build test history

- [TestAccFirestoreDatabase_firestoreDefaultDatabaseExample](https://hashicorp.teamcity.com/test/-3069467187706724312?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A61674%29%2Cid%3A2000000001)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
=== PAUSE TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
=== CONT  TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating Database: googleapi: Error 409: Database already exists. Please use another database_id
          with google_firestore_database.database,
          on terraform_plugin_test.tf line 4, in resource "google_firestore_database" "database":
           4: resource "google_firestore_database" "database" {
--- FAIL: TestAccFirestoreDatabase_firestoreDefaultDatabaseExample (12.18s)
FAIL
```

b/315953829

**Comment by rileykarson** [comment]
`(default)`should be hardcoded so this may be a different issue

**Comment by SarahFrench** [comment]
This is very similar to this other failing test issue (https://github.com/hashicorp/terraform-provider-google/issues/16768) but it describes a different error so I won't close it as duplicate.

**Comment by BBBmau** [comment]
@rileykarson We should consider using something other than `(default)` for testing unless there's a good reason for it.

I looked into this and found that `(default)` was already set in GCP. Since this leads to the original error I removed it expecting it to pass. However I get this instead which looks very similar to a recent issue that just got merged where the default name was changed in order for tests to pass. Mentioned here https://github.com/GoogleCloudPlatform/magic-modules/pull/9674

changing the name like what @SarahFrench would fix this error:
```bash
● ? ↓123  envchain GCLOUD make testacc TEST=./google/services/firestore/ TESTARGS='-run=TestAccFirestoreDatabase_firestoreDefaultDatabaseExample'

TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google/services/firestore/ -v -run=TestAccFirestoreDatabase_firestoreDefaultDatabaseExample -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
=== PAUSE TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
=== CONT  TestAccFirestoreDatabase_firestoreDefaultDatabaseExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating Database: googleapi: Error 400: Database ID '(default)' is not available in project 'hc-terraform-testing'. Please retry in 28 seconds.
        
          with google_firestore_database.database,
          on terraform_plugin_test.tf line 4, in resource "google_firestore_database" "database":
           4: resource "google_firestore_database" "database" {
        
--- FAIL: TestAccFirestoreDatabase_firestoreDefaultDatabaseExample (14.09s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-google/google/services/firestore       15.101s
FAIL
make: *** [testacc] Error 1
```
