### ISSUE TITLE
Failing test(s): TestAccIntegrationConnectorsConnection_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16720]
### Failure rates
- 100 since 2023-11-12/09
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionSaExample`
    - `TestAccIntegrationConnectorsConnection_update`
- 95% since 2023-11-09
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthJwtExample`
- 83% since 2023-11-09
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample`
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample`
- 70% since 2023-11-09
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample`
- 30% since 2023-11-09
    - `TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample`

### Impacted tests

- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthJwtExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthSshExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionSaExample
- TestAccIntegrationConnectorsConnection_update

### Affected Resource(s)

* google_integration_connectors_connection

### Nightly build test history

- [TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample](https://hashicorp.teamcity.com/test/7318379268959669420?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample](https://hashicorp.teamcity.com/test/-6446351618020232601?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample](https://hashicorp.teamcity.com/test/-5482930350973706248?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true) - **flaky**
- [TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample](https://hashicorp.teamcity.com/test/2091558984184943425?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
-  [TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthJwtExample](https://hashicorp.teamcity.com/test/8467822845286826269?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthSshExample - **flaky**
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionSaExample
- TestAccIntegrationConnectorsConnection_update

#### Error type : `Error code 13, message: an internal error has occurred`

Experienced by:
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthJwtExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthSshExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionSaExample
- TestAccIntegrationConnectorsConnection_update

```
------- Stdout: -------
=== RUN   TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample
=== PAUSE TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample
=== CONT  TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error waiting to create Connection: Error waiting for Creating Connection: Error code 13, message: an internal error has occurred
          with google_integration_connectors_connection.zendeskconnection,
          on terraform_plugin_test.tf line 29, in resource "google_integration_connectors_connection" "zendeskconnection":
          29: resource "google_integration_connectors_connection" "zendeskconnection" {
--- FAIL: TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionAdvancedExample (36.48s)
FAIL




------- Stdout: -------
=== RUN   TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample
=== PAUSE TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample
=== CONT  TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: Error waiting for Deleting Connection: Error code 13, message: an internal error has occurred
--- FAIL: TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionBasicExample (44.89s)
FAIL
```

#### Error type : imported resource doesn't resemble the one provisioned

- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample
- TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample

```
------- Stdout: -------
=== RUN   TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample
=== PAUSE TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample
=== CONT  TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample
    vcr_utils.go:152: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        (map[string]string) (len=1) {
         (string) (len=20) "status.0.description": (string) (len=100) "You must provide the OAuth access token. Refer to the help documentation to obtain the access token."
        }
        (map[string]string) (len=1) {
         (string) (len=20) "status.0.description": (string) (len=29) "connection deployment timeout"
        }
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: Error waiting for Deleting Connection: Error code 13, message: an internal error has occurred
--- FAIL: TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthCcExample (159.44s)
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample
=== PAUSE TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample
=== CONT  TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample
    vcr_utils.go:152: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        (map[string]string) (len=2) {
         (string) (len=20) "status.0.description": (string) "",
         (string) (len=14) "status.0.state": (string) (len=22) "AUTHORIZATION_REQUIRED"
        }
        (map[string]string) (len=2) {
         (string) (len=20) "status.0.description": (string) (len=29) "connection deployment timeout",
         (string) (len=14) "status.0.state": (string) (len=5) "ERROR"
        }
--- FAIL: TestAccIntegrationConnectorsConnection_integrationConnectorsConnectionOauthExample (783.85s)
FAIL
```

b/315457057

**Comment by balanaguharsha** [comment]
Checking
