### ISSUE TITLE
Failing test(s): TestAccComputeInstance_* (Beta) ("Cloud Armor Net LB with custom rules is currently not publicly available")

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16744]
### Failure rates

- 100% since 2023-11-15

### Impacted tests

- TestAccComputeInstance_PTRRecord (Beta)
- TestAccComputeInstance_update (Beta)
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyUserDefinedFieldsUpdate (Beta)
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyWithUserDefinedFieldsExample (Beta)
- TestAccComputeTargetInstance_targetInstanceWithSecurityPolicyExample (Beta)
- TestAccComputeTargetPool_withSecurityPolicy (Beta)

### Affected Resource(s)

* google_compute_instance

### Nightly build test history

- [TestAccComputeInstance_PTRRecord (Beta)](https://hashicorp.teamcity.com/test/3774136348885986818?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccComputeInstance_update (Beta)](https://hashicorp.teamcity.com/test/5269160588866606582?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
Error:
    Error updating instance while setting the security policies:
        Error adding security policy: googleapi:
            Error 400: Cloud Armor Net LB with custom rules is currently not publicly available., badRequest
```

b/315582570

**Comment by SarahFrench** [comment]
This field was added in : https://github.com/GoogleCloudPlatform/magic-modules/pull/8878
Merged on September 22nd

BUT, the test has only been failing due to the error `"Cloud Armor Net LB with custom rules is currently not publicly available"` since 2023-11-15.

In the time between the PR being merged (2023-109-22) and the error starting (2023-11-15) the test passed fine:

![Screenshot 2023-12-08 at 15 00 38](https://github.com/hashicorp/terraform-provider-google/assets/15078782/fd33dacb-c89f-4abb-90f5-81df60fb08be)

**Comment by melinath** [comment]
This is resolved.
