### ISSUE TITLE
Error in self-service labeler GitHub Action

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16746]
In an issue I opened (https://github.com/hashicorp/terraform-provider-google/issues/16745) I was notified about an error in the  `.github/workflows/self-service-labeler.yml` GHA on that issue.

Note: When the GHA ran there were no labels on the issue - I added some after the error occurred.

This part of the GHA experienced the error:

https://github.com/hashicorp/terraform-provider-google/blob/f0ddf682c314a05b2ad3172754748d6144c50935/.github/workflows/self-service-labeler.yml#L30-L40

See details about the error in the GHA run here : https://github.com/hashicorp/terraform-provider-google/actions/runs/7143174109/job/19454058870

Copied from there:

```
Error: Unhandled error: HttpError: Validation Failed: {"value":"service/compute-security-policy","resource":"Label","field":"name","code":"invalid"}


status: 422,
  response: {
    url: 'https://api.github.com/repos/hashicorp/terraform-provider-google/issues/16745/labels',
    status: 422,
    headers: {
        ...
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/rest/issues/labels#add-labels-to-an-issue'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/hashicorp/terraform-provider-google/issues/16745/labels',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"labels":["forward/review","service/compute-regional-pass-through-load-balancer","service/compute-security-policy"]}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}

```

**Comment by rileykarson** [comment]
@roaks3 do you mind taking a look?

**Comment by rileykarson** [comment]
Note: https://github.com/hashicorp/terraform-provider-google/issues/16745's template doesn't have a robot add labels, maybe we make an assumption that there's already one?

**Comment by melinath** [comment]
This is due to label length - GitHub has an (undocumented) 50-character limit on label length, and this label is 51 characters long.
