### ISSUE TITLE
Failing test(s): TestAccFirestoreDatabase_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16768]
### Failure rates

- 100% since 2023-12-09
- 100% since 2023-11-22 (e.g. `TestAccFirestoreDatabase_firestoreDefaultDatabaseExample`)
- 100% since 2023-11-15 ( e.g. `TestAccFirestoreDocument_firestoreDocumentBasicExample`)

#### "maximum number of databases per project" error:

- [TestAccFirestoreDatabase_firestoreDatabaseExample](https://hashicorp.teamcity.com/test/-9186772961375478136?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccFirestoreDatabase_firestoreDatabaseInDatastoreModeExample](https://hashicorp.teamcity.com/test/-3844691753058027902?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccFirestoreDatabase_firestoreDefaultDatabaseExample](https://hashicorp.teamcity.com/test/-3069467187706724312?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccFirestoreDatabase_updateConcurrencyMode](https://hashicorp.teamcity.com/project.html?projectId=TerraformProviders_GoogleBeta_NightlyTests&testNameId=7365282096799033932&tab=testDetails)
- [TestAccFirestoreDatabase_updateDeleteProtectionState](https://hashicorp.teamcity.com/project.html?projectId=TerraformProviders_GoogleBeta_NightlyTests&testNameId=-3386783164303757000&tab=testDetails)
- [TestAccFirestoreDatabase_updatePitrEnablement](https://hashicorp.teamcity.com/project.html?projectId=TerraformProviders_GoogleBeta_NightlyTests&testNameId=-6827610944169578250&tab=testDetails)
 
#### "The database (default) does not exist" error:

- [TestAccFirestoreDocument_firestoreDocumentBasicExample](https://hashicorp.teamcity.com/test/6610220860953765566?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccFirestoreDocument_firestoreDocumentNestedDocumentExample](https://hashicorp.teamcity.com/project.html?projectId=TerraformProviders_GoogleBeta_NightlyTests&testNameId=-6555456036088157527&tab=testDetails)
- TestAccFirestoreDocument_update
- TestAccFirestoreField_firestoreFieldBasicExample
- TestAccFirestoreField_firestoreFieldMatchOverrideExample
- TestAccFirestoreField_firestoreFieldTimestampExample
- TestAccFirestoreField_firestoreFieldUpdateAddIndexExample
- TestAccFirestoreField_firestoreFieldUpdateAddTTLExample
- TestAccFirestoreIndex_firestoreIndexBasicExample
- TestAccFirestoreIndex_firestoreIndexDatastoreModeExample

 

### Affected Resource(s)

* google_firestore_database
* google_firestore_document
* google_firestore_field

### Nightly build test history

See links on test names above

#### "maximum number of databases per project" error:

```
Error:
    Error creating Database: googleapi:
        Error 429: You have reached the maximum number of databases per project. Please delete an unused database and try again.
```

#### "The database (default) does not exist" error:

```
Error:
    Error creating Document: googleapi:
        Error 404: The database (default) does not exist for project ci-test-proj-firestore-beta Please visit https://console.cloud.google.com/datastore/setup?project=ci-test-proj-firestore-beta to add a Cloud Datastore or Cloud Firestore database.
```

b/315952202

**Comment by rileykarson** [comment]
If we don't have a sweeper, we should add one

**Comment by hao-nan-li** [comment]
Firestore_database and firestore_fields have some custom delete methods, reason why there's no sweeper implemented. Especially for firestore_DB, the deletion could be protected https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/pre_delete/firestore_database.go.erb#L6. 

The service teams seems to be investigating this issue this sprint, will wait and see what's the outcome.

**Comment by roaks3** [comment]
Note that these have continued to fail for the last few days in our nightly tests, but it appears to be due to a quota. I've cleared out those instances, and the fix appears to properly delete these when the test is complete, so I'd expect that these will pass moving forward.
