### ISSUE TITLE
Add the address attribute to the docs for the google_compute_address resource

### ISSUE THREAD

**Issue by colereynolds** [hashicorp/terraform-provider-google#16763]
Add the address attribute to the docs for the google_compute_address resource

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is simply an error in the docs for the `google_compute_address` resource. If you look at the attributes section, linked below, you'll notice the `address` attribute is missing even though it exists and it has for years. This creates a bit of confusion for new users that want to reference the address created by this resource and it would do me the favor of not having to explain that it does actually exist.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#attributes-reference

FYI - This is the second issue to be created in an effort to have this fixed. I don't think the engineer that closed this issue understood the problem or maybe they got it mixed up with something else. The first attempt can be found here: #11136

### New or Affected Resource(s)

`google_compute_address`

### References

* #11136

**Comment by rileykarson** [comment]
Address is a mixed argument + attribute and appears in the property reference: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#address

This is fairly common in GCP APIs unfortunately, and we don't plan to record these mixed values as attributes universally across the provider. They will always appear in the argument reference, though.

**Comment by colereynolds** [comment]
That's disappointing but thank you for the insight. Do you know where the code that generates these docs can be found? I'd like to bring some attention to the larger issue or create a PR to address this. It creates a poor experience for new users and I know I can't be the only one that gets tired of explaining the why behind it.

**Comment by rileykarson** [comment]
Most of our docs are using this template: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/resource.html.markdown.erb

The filter for an attribute is "output", while "default_from_api" represents these mixed fields.

We've been trying to resolve the larger cause in new Google Cloud APIs- a member of the provider team proposed an amendment to Google API guidance in https://google.aip.dev/129 that would split the argument and attribute at the API level.
