### ISSUE TITLE
Documentation error for gke_hub_membership import

### ISSUE THREAD

**Issue by terlar** [hashicorp/terraform-provider-google#16779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* gke_hub_membership

### Expected Behavior

The [import documentation for gke_hub_membership](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership#import) should be correct.

The documentation should follow the specified format:
```
projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/features/(?P<feature>[^/]+)/membershipId/(?P<membership>[^/]+) (?P<project>[^/]+)/(?P<location>[^/]+)/(?P<feature>[^/]+)/(?P<membership>[^/]+) (?P<location>[^/]+)/(?P<feature>[^/]+)/(?P<membership>[^/]+)
```

E.g.
```
$ terraform import google_gke_hub_membership.default projects/{{project}}/locations/{{location}}/features/{{feature}}/membershipId/{{membership_id}}
$ terraform import google_gke_hub_membership.default {{project}}/{{location}}/{{feature}}/{{membership_id}}
$ terraform import google_gke_hub_membership.default {{location}}/{{feature}}/{{membership_id}}
```

### Actual Behavior

Documentation says:
```
$ terraform import google_gke_hub_membership.default projects/{{project}}/locations/{{location}}/memberships/{{membership_id}}
$ terraform import google_gke_hub_membership.default {{project}}/{{location}}/{{membership_id}}
$ terraform import google_gke_hub_membership.default {{location}}/{{membership_id}}
```

Running `{{location}}/{{membership_id}}` you will get.
```
Error: Import id "{{location}}/{{membership_id}}" doesn't match any of the accepted formats: [projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/features/(?P<feature>[^/]+)/membershipId/(?P<membership>[^/]+) (?P<project>[^/]+)/(?P<location>[^/]+)/(?P<feature>[^/]+)/(?P<membership>[^/]+) (?P<location>[^/]+)/(?P<feature>[^/]+)/(?P<membership>[^/]+)]
```

Running the other ones will have very confusing messages, where it calls API:s with the wrong information.

### Steps to Reproduce

1. `terraform import google_gke_hub_membership.default projects/{{project}}/locations/{{location}}/memberships/{{membership_id}}`
2. `terraform import google_gke_hub_membership.default {{project}}/{{location}}/{{membership_id}}`
3. `terraform import google_gke_hub_membership.default {{location}}/{{membership_id}}`

**Comment by edwardmedia** [comment]
@terlar look at the [source code](https://github.com/hashicorp/terraform-provider-google/blob/9d577db230bead275a4a1a6ae2c15a608a9dba1b/google/services/gkehub/resource_gke_hub_membership.go#L284), the [import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership#import) format seems correct. 

What exact import command did you use to get that error? Can you share the result by running below gcloud command?

```
gcloud container hub memberships describe
```
