### ISSUE TITLE
Vertex AI Search Terraform Support

### ISSUE THREAD

**Issue by kamakay** [hashicorp/terraform-provider-google#16787]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Gen AI builder from september has been rebranded as "Vertex AI Search" using discoveryengine google apis.

### New or Affected Resource(s)

Proposal

* google_vertexaisearch_datastore_***

### Potential Terraform Configuration

None at the moment

### References

* Discovery Engine api https://cloud.google.com/discovery-engine/docs/reference/rest

**Comment by rileykarson** [comment]
@melinath to identify service team

**Comment by SarahFrench** [comment]
@melinath looks like there is a PR open for this issue : https://github.com/GoogleCloudPlatform/magic-modules/pull/9774

**Comment by melinath** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/magic-modules/pull/9682

**Comment by bademiya5306** [comment]
Is this fixed. When will be the documentation updated?

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9682. The docs will be updated when a release with this resource goes out.

**Comment by bademiya5306** [comment]
@melinath I am trying to create a vertex search app with website urls as data store using terraform. Is there any ETA when the support for this would be released so that i can use it?
