### ISSUE TITLE
Why is 5 the max number of notification channels in a budget alert

### ISSUE THREAD

**Issue by krisztiansala** [hashicorp/terraform-provider-google#16790]
A maximum of 5 channels are allowed in `monitoring_notification_channels` when creating a `google_billing_budget`. Why is this the limit?
I don't see such quota in GCP. And I would need to set around 15 channels (emails).
Could this arbitrary limit be increased?

**Comment by edwardmedia** [comment]
@krisztiansala where did you see the max of 5 channels? In a execution log? Can you share the log? Console?

**Comment by krisztiansala** [comment]
Hi, I saw it both in the logs and the documentation.
Log:
```
Error: Too many list items
...
Attribute all_updates_rule.0.monitoring_notification_channels supports 5 item
maximum, but config has 12 declared.
```
Docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#monitoring_notification_channels

"A maximum of 5 channels are allowed."

**Comment by edwardmedia** [comment]
Here is the [api doc](https://cloud.google.com/billing/docs/reference/budget/rest/v1/billingAccounts.budgets) that shows Max of 5. 

monitoringNotificationChannels[] | stringOptional. Email targets to send notifications to when a threshold is exceeded. This is in addition to the DefaultIamRecipients who receive alert emails based on their billing account IAM role. The value is the full REST resource name of a Cloud Monitoring email notification channel with the form projects/{projectId}/notificationChannels/{channel_id}. A maximum of 5 email notifications are allowed.

I think the behavior of the provider matches the API's. Are I right?

**Comment by edwardmedia** [comment]
@krisztiansala is this still a question?

**Comment by krisztiansala** [comment]
Thank you for the response. Yes, the provider implementation matches the API, so I guess my issue is with the API itself.
I will close this.
