### ISSUE TITLE
Failing test(s): TestAccComputeSubnetwork_subnetworkInternalL7lbExample and more

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#16804]
### Failure rates

- 100% since 2023-12-12

### Impacted tests

- TestAccComputeSubnetwork_subnetworkInternalL7lbExample
- TestAccComputeForwardingRule_forwardingRuleHttpLbExample
- TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample
- TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample
- TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample
- TestAccNetworkServicesGateway_minimalSwp
- TestAccNetworkServicesGateway_networkServicesGatewayMultipleSwpSameNetworkExample
- TestAccNetworkServicesGateway_networkServicesGatewaySecureWebProxyExample
- TestAccNetworkServicesGateway_multipleSwpGatewaysDifferentNetwork
- TestAccNetworkServicesGateway_multipleSwpGatewaysDifferentSubnetwork
- TestAccDNSRecordSet_routingPolicy

### Affected Resource(s)

* google_compute_subnetwork

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/7827340788455413374?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
vcr_utils.go:152: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_compute_subnetwork.network-for-l7lb will be updated in-place
          ~ resource "google_compute_subnetwork" "network-for-l7lb" {
                id                               = "projects/xxxxxx/regions/us-central1/subnetworks/tf-test-l7lb-test-subnetworkvndk9pmf6z"
              - ipv6_access_type                 = "INTERNAL" -> null
                name                             = "tf-test-l7lb-test-subnetworkvndk9pmf6z"
                # (13 unchanged attributes hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
```

b/316686879

**Comment by shuyama1** [comment]
Looks like the API has started to return value `INTERNAL` for `ipv6_access_type` field when it's not explicitly set since 12/12 and this causes a permadiff in Terraform.

**Comment by SarahFrench** [comment]
Notes from triage: this could be addressed with a diff suppress func in the provider, or a change to the API. The service team can choose whichever option is most appropriate.
