### ISSUE TITLE
Feature request: Allow `vcenter_network` to be set by users on `google_gkeonprem_vmware_cluster`

### ISSUE THREAD

**Issue by bateau84** [hashicorp/terraform-provider-google#16821]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
When creating `google_gkeonprem_vmware_cluster` it is necessary to define the vmware network name the cluster and node-pools are created in. 
As of now it is inherited from the admin cluster, however it is needed to not place the user-clusters in the same network as the admin-cluster and be able to define it manually.

### New or Affected Resource(s)
* `google_gkeonprem_vmware_cluster`
* `google_gkeonprem_vmware_node_pool`

### Potential Terraform Configuration

```tf
resource "google_gkeonprem_vmware_cluster" "gkee_onprem_cluster" {
...
  network_config {
    ...
    vcenter_network = "some-network-name"
   ...
  }
...
}
```

### References

- API: https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/projects.locations.vmwareClusters
- Docs for the field : https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/projects.locations.vmwareClusters#vmwarenetworkconfig

b/317042838

**Comment by SarahFrench** [comment]
Notes from triage: The field is present on the [google_gkeonprem_vmware_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gkeonprem_vmware_cluster#vcenter_network) resource, but currently it's implemented as an output. The field will need to be changed to be Optional + Computed.

**Comment by mikkelnygard** [comment]
> Notes from triage: The field is present on the [google_gkeonprem_vmware_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gkeonprem_vmware_cluster#vcenter_network) resource, but currently it's implemented as an output. The field will need to be changed to be Optional + Computed.

I have tested my pull request by building the provider locally. 
While setting `network_config.vcenter_network` is accepted, it does not seem to have any effect on the created kubernetes cluster.
Are you sure the underlying api supports it? Where can I find the reference?

**Comment by SarahFrench** [comment]
Hi @mikkelnygard - That's the correct API reference, and you're correct that making that field user-controlled is unsupported. [network_config.vcenter_network is output only](https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/projects.locations.vmwareClusters#vmwarenetworkconfig), so [the note from triage](https://github.com/hashicorp/terraform-provider-google/issues/16821#issuecomment-1861105036) was incorrect. Sorry for misleading you!

Unfortunately we're constrained by the API, so if a feature is supported via config files and gkectl but not by the API then we can only make a feature request to the service team that manages the API.

**Comment by mikkelnygard** [comment]
> Hi @mikkelnygard - That's the correct API reference, and you're correct that making that field user-controlled is unsupported. [network_config.vcenter_network is output only](https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/projects.locations.vmwareClusters#vmwarenetworkconfig), so [the note from triage](https://github.com/hashicorp/terraform-provider-google/issues/16821#issuecomment-1861105036) was incorrect. Sorry for misleading you!
> 
> Unfortunately we're constrained by the API, so if a feature is supported via config files and gkectl but not by the API then we can only make a feature request to the service team that manages the API.

Ok, thank you for the clarification. 
This is unfortunately a blocker for us, and means we can not use the terraform provider.
Can you make that feature request?

**Comment by bateau84** [comment]
Any update on this issue @SarahFrench ?

**Comment by bateau84** [comment]
It seems like this option is in the latest release of the provider? can someone confirm? :)
