### ISSUE TITLE
Cannot create multiple conditions in google_monitoring_alert_policy

### ISSUE THREAD

**Issue by raweber42** [hashicorp/terraform-provider-google#16834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```
resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "XXX unavailable"
  documentation {
    content = "The status of the XXX has changed."
  }
  combiner     = "OR"
  conditions {
    display_name = "XXX Status"
    condition_threshold {
      name            = "XXX in maintenance"
      comparison      = "COMPARISON_EQ"
      duration        = "60s" // how much should be the interval to check?
      filter          = "resource.type = \"custom.googleapis.com/XXX/XXX\""
      threshold_value = "1"
      trigger {
        count = "1"
      }
    }
    condition_threshold {
      name = "XXX service disruption"
      comparison = "COMPARISON_EQ"
      duration = "60s" // how much should be the interval to check?
      filter = "resource.type = \"custom.googleapis.com/XXX/XXX\""
      threshold_value = "2"
      trigger {
        count = "1"
      }
    }
  }
```

### Debug Output

```
│ Error: Too many condition_threshold blocks
│ 
│   on monitoring.tf line 19, in resource "google_monitoring_alert_policy" "alert_policy":
│   19:     condition_threshold {
│ 
│ No more than 1 "condition_threshold" blocks are allowed
```

### Expected Behavior

I want to be able to add multiple conditions with their own display_names. I can use 2 `conditions` fields, but that's not how it's supposed to work I think.

### Actual Behavior

I get the above error

### Steps to Reproduce

1. Create google_monitoring_alert_policy like mine above

### References

* #0000

**Comment by roaks3** [comment]
According to the [API reference](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#Condition), this seems to be working as expected, and I think that using multiple `conditions` blocks is the intended solution.

@raweber42 is there a specific issue with using multiple `conditions` blocks? That would determine if there is some sort of behavior gap, or if this is a feature request.

**Comment by edwardmedia** [comment]
@raweber42 is this still an issue?

**Comment by edwardmedia** [comment]
@raweber42 closing assuming this is no longer an issue
