### ISSUE TITLE
Use `network_config` over `network` in `google_alloydb_cluster` examples

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#16848]
Current examples all use `network`, we should use the non-deprecated variant in all of them (or all but one if we want an example of the old mechanism to stick around). Related to https://github.com/hashicorp/terraform-provider-google/issues/16119, the removal in `6.0.0`.

We shouldn't eliminate usages entirely, and should keep some in handwritten tests.

b/319230983

**Comment by c2thorn** [comment]
Note that this is heavily related to https://github.com/hashicorp/terraform-provider-google/issues/16119 and should be done simultaneously

**Comment by c2thorn** [comment]
closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16119
