### ISSUE TITLE
Creating and attaching a Data Catalog Tag to BigQuery - Root Resource was present but now absent 

### ISSUE THREAD

**Issue by yunus** [hashicorp/terraform-provider-google#16855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.10.0
+ provider registry.terraform.io/hashicorp/google-beta v5.10.0
```

### Affected Resource(s)

* google_data_catalog_tag

### Terraform Configuration Files

```tf

terraform {
  required_providers {
    google = {
      source  = "google"
      version = "~> 5.10.0"
    }
    google-beta = {
      source  = "google-beta"
      version = "~> 5.10.0"
    }
  }
}
locals {
  dataset_project = "DATASET_PROJECT_NAME"
  dataset = "DATASET_NAME"
  table = "TABLE_NAME"
  dataset_location = "US"
  template_project = "TEMPLATE_PROJECT_NAME"
  template_region = "us-central1"
}


# below changes are needed to create entries and tags
provider "google" {
  user_project_override = true
  billing_project       = local.template_project
}

resource "google_data_catalog_tag_template" "demo_tag_template" {
  tag_template_id = "demo_template"
  region = local.template_region
  display_name = "Demo Tag Template"
  project = local.template_project

  fields {
    field_id = "source"
    display_name = "Source of data asset"
    type {
      primitive_type = "STRING"
    }
    is_required = true
  }

  fields {
    field_id = "num_rows"
    display_name = "Number of rows in the data asset"
    type {
      primitive_type = "DOUBLE"
    }
  }
  fields {
    field_id = "has_pii"
    display_name = "Has PII"
    type {
      primitive_type = "BOOL"
    }
  }

  fields {
    field_id = "pii_type"
    display_name = "PII type"
    type {
      enum_type {
        allowed_values {
          display_name = "EMAIL_ADDRESS"
        }
        allowed_values {
          display_name = "US_SOCIAL_SECURITY_NUMBER"
        }
        allowed_values {
          display_name = "NONE"
        }
      }
    }
  }

  force_delete = "true"
}

resource "google_data_catalog_tag" "product_tag_bq" {
  depends_on = [ google_data_catalog_tag_template.demo_tag_template ]
  parent     = "projects/${local.dataset_project}/locations/${local.dataset_location}/entryGroups/@bigquery/entries/${base64encode(join("/",["projects",local.dataset_project,"datasets", local.dataset, "tables", local.table]))}"
  template   = google_data_catalog_tag_template.demo_tag_template.id

  fields {
    field_name = "source"
    string_value = "BigQuery"
  }
  fields {
    field_name   = "num_rows"
    double_value = 1000
  }
  fields {
    field_name   = "has_pii"
    bool_value = true
  }
  fields {
    field_name   = "pii_type"
    enum_value = "EMAIL_ADDRESS"
  }
}

```

### Debug Output

[debug output](https://gist.github.com/yunus/69c2313ac1045e2c28770818ee0a8de1)

### Expected Behavior

Tag and Tag template are created without any errors

### Actual Behavior

Both tag template and tag are created, attached to BigQuery table. But I receive an error in Terraform and inside the state file I don't see the Tag. So when I rerun the code I receive a 409 already exists error.

### Steps to Reproduce

The code above is self sufficient. I used the same project for both the tag template and the tag.

1. `terraform apply`

### Important Factoids

authenticating as the user

**Comment by roaks3** [comment]
I think the issue actually might have to do with the base64 encoding being done in your `parent` field. It is producing a value that ends in an `=` sign, which seems like it might be throwing off the URL parsing (or perhaps the API does not handle them). You can see that in the POST request to create the tag, the returned name includes your same base64 value with the `=` trimmed.

IIRC, the `=` is only used in base64 to indicate padding. Could you try your config with the trailing `=` removed and see if that succeeds?

**Comment by yunus** [comment]
Bingo. It works with trimming.
Here is the solution for others who hit the same issue:
```tf
resource "google_data_catalog_tag" "product_tag_bq" {
  depends_on = [ google_data_catalog_tag_template.demo_tag_template ]
  parent     = "projects/${local.dataset_project}/locations/${local.dataset_location}/entryGroups/@bigquery/entries/${trim(base64encode(join("/",["projects",local.dataset_project,"datasets", local.dataset, "tables", local.table])),"=")}"
  template   = google_data_catalog_tag_template.demo_tag_template.id

  ...
```
