### ISSUE TITLE
Support certificate_map for "google_compute_region_https_proxy"

### ISSUE THREAD

**Issue by TV2rd** [hashicorp/terraform-provider-google#16864]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_region_target_https_proxy
* google_compute_target_https_proxy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
The global https proxy resource: "google_compute_target_https_proxy" have support for certificate_map instead of ssl_certificates. As of my understanding the API supports this option for the region https proxies as well. 

I could have a workaround for this issue where i would use a "google_compute_target_https_proxy" to reference a region url map( i need the region url map to be able to do cross project reference in GCP). But when i supply a self_link of the regional url map it throws a 404 not found on the resource and a reference containing /global/ and not the url_map.self_link set in the https proxy resource. 
### References

* #0000

**Comment by TV2rd** [comment]
Got it to work for my use case using global load balancer.

**Comment by whyname** [comment]
I'm having the same problem and need regional target https proxy support to configure cert map.
