### ISSUE TITLE
Error when creating alloydb user

### ISSUE THREAD

**Issue by marcus-bilt** [hashicorp/terraform-provider-google#16869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.10.0
+ provider registry.terraform.io/hashicorp/google-beta v5.10.0
```

### Affected Resource(s)

* google_alloydb_user

### Terraform Configuration Files

```tf
resource "google_alloydb_user" "redash_readonly_user" {
  cluster   = "test"
  user_id   = "user1"
  user_type = "ALLOYDB_BUILT_IN"
  password  = "123456"
}
```

### Panic Output

```
╷
│ Error: Error creating User: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1/payment2/users?alt=json&amp;userId=user1</code> was not found on this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_alloydb_user.redash_readonly_user,
│   on main.tf line 842, in resource "google_alloydb_user" "redash_readonly_user":
│  842: resource "google_alloydb_user" "redash_readonly_user" {
│ 
╵
```

### Expected Behavior

It should create the user on alloydb cluster.

### Actual Behavior

It is failing when trying to create the user and the user has not being created.

### Steps to Reproduce

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_user

**Comment by shuyama1** [comment]
@marcus-bilt This error is likely due to that the input for the `cluster` field needs to be the long form of the cluster id ([in the format 'projects/{project}/locations/{location}/clusters/{cluster_id}'](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_user#cluster)), but, it's using the short name here instead. Could you try the long-form name and see if that works.

**Comment by marcus-bilt** [comment]
> @marcus-bilt This error is likely due to that the input for the `cluster` field needs to be the long form of the cluster id ([in the format 'projects/{project}/locations/{location}/clusters/{cluster_id}'](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_user#cluster)), but, it's using the short name here instead. Could you try the long-form name and see if that works.

Hi @shuyama1 , thanks so much for that. This fixed the issue.
