### ISSUE TITLE
Under resource -  `google_monitoring_alert_policy` Add Severity option

### ISSUE THREAD

**Issue by vxr222** [hashicorp/terraform-provider-google#16878]
`google_monitoring_alert_policy` Under this resource i wanted to add option for severity
Ref. Link https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#severity
Terraform Link  = https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#severity

I am getting error 
```
on main.tf line 60, in resource "google_monitoring_alert_policy" "dataflow_job_failed":
│   60:     severity = "ERROR"
│
│ An argument named "severity" is not expected here.
```
Module is below
```
resource "google_monitoring_alert_policy" "dataflow_job_failed" {
  project               = var.project_id
  severity = "ERROR"
  display_name          = "[Dataflow] Job Failed"
  notification_channels = var.notification_channels 
  combiner              = "OR"
  # user_labels           = var.user_labels
  conditions {
    display_name = "[Dataflow] Job Failed"
    condition_threshold {
      filter          = "metric.type=\"dataflow.googleapis.com/job/is_failed\" resource.type=\"dataflow_job\""
      duration        = var.duration
      comparison      = var.comparison
      threshold_value = var.threshold_value

      aggregations {
        per_series_aligner = "ALIGN_MAX"
        alignment_period   = "300s"
      }
      trigger {
        count = 1
      }
    }
  }
  alert_strategy {
    auto_close = var.auto_close_duration
  }
}
```

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by P1K3N** [comment]
Currently the severity available in the provider documentation it attaches the severity to the accident. 
In the policy I can still see "No severity", so something is not working. 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#severity

**Comment by Lavieira** [comment]
should you label it as "bug"?

**Comment by cw-optima-ovo** [comment]
Just adding that I'm seeing this behaviour too, cannot add severity to a `google_monitoring_alert_policy` resource as per documentation:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#severity

It is possible to add severity via the google cloud console and if exporting the JSON from the alert policy you can see there is a severity key available.
This PR should have solved the problem but even with the latest terraform version (1.7.5) it is not possible:
https://github.com/hashicorp/terraform-provider-google/pull/16775

I would expect this to deploy but the severity flag is not recognised by terraform.
```
resource "google_monitoring_alert_policy" "test-severity" {
  display_name = "test-severity"
  severity = "WARNING"
  enabled      = true
  project      = "my-project"
  combiner     = "OR"
  conditions {
    display_name = "Error detected in logs"
    condition_matched_log {
      filter = "(resource.type = \"cloud_run_revision\"\nresource.labels.service_name = \"some-function\"\nresource.labels.location = \"europe-west1\")\n severity>=DEFAULT\""
    }
  }
  alert_strategy {
    notification_rate_limit {
      period = "600s"
    }
  }
}
```


This code produces the error
```
│ Error: Unsupported argument
│ 
│   on testfile.tf line 74, in resource "google_monitoring_alert_policy" "test-severity":
│   74:   severity = "WARNING"
│ 
│ An argument named "severity" is not expected here.
```

@vxr222  would agree with @Lavieira this should be labelled as a bug

**Comment by luismendezescobar** [comment]
I'm having the same issue:
`resource "google_monitoring_alert_policy" "app_engine_read_queries" {
  display_name          = "Quota usage app engine read queries per minute on: ${var.app_name}"
  enabled               = var.alert_enabled_app_engine  
  combiner              = "OR"
  notification_channels = var.notification_channel
 
 severity              = "CRITICAL"
  
  documentation {    
    content =  "To resolve this issue, click [here](https://console.cloud.google.com/iam-admin/quotas?"
  }
  user_labels = {
    configuration = "terraform"
  }
  conditions {
    display_name = "Quota usage app engine read queries per minute on: ${var.app_name}"
    condition_monitoring_query_language {
      query    = <<EOT
      fetch consumer_quota|filter resource.project_id==${var.project_id}
      EOT 
      duration = "60s"
      trigger {
        count = 1
        
      }
      
    }
  }
  alert_strategy {
    auto_close = "3600s"
    
  }
  
  
}`
getting the error:
`
Error: Unsupported argument
  on ../../modules/alerts-quotes/main.tf line 7, in resource "google_monitoring_alert_policy" "app_engine_read_queries":
   7:   severity              = "CRITICAL"
`

**Comment by raweber42** [comment]
same here

**Comment by AntonioEFX** [comment]
Me too...

**Comment by cw-optima-ovo** [comment]
@rileykarson 
output from terraform -v
```
Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.25.0
```

After now upgrading to the above versions, I can verify the severity flag is now working, example config here:

```
resource "google_monitoring_alert_policy" "test-severity" {
  display_name = "test-severity"
  severity = ""
  enabled      = true
  project      = "my-project"
  combiner     = "OR"
  conditions {
    display_name = "Error detected in logs"
    condition_matched_log {
      filter = "(resource.type = \"cloud_run_revision\"\nresource.labels.service_name = \"cloud_run_resource\"\nresource.labels.location = \"europe-west2\")\n severity>=ERROR"
    }
  }
  alert_strategy {
    notification_rate_limit {
      period = "600s"
    }
  }
}
```

**Comment by rileykarson** [comment]
Thanks! Just to confirm explicitly, it didn't work before upgrading but did work afterwards?

**Comment by cw-optima-ovo** [comment]
@rileykarson At the point of my comment from 15/03, this wasn't working but I didn't note the version of the provider (unhelpfully). I tested this in a fresh folder though so whatever the latest provider version would be I would likely have used though can't be certain.

In one of the configs I have running at the moment using provider v4.8.4, the severity flag doesn't work but it also doesn't exist in that provider version so that's to be expected.

**Comment by rileykarson** [comment]
Thanks! I am going to assume that was it, although the number of reports is unusually high for that to be the case. If someone can share a repro w/ `terraform -v` with `google`/`google-beta` at `5.10.0+` I'll reopen this!
