### ISSUE TITLE
add NFS and GCS volume support to Cloud Run v2 Services

### ISSUE THREAD

**Issue by mvanholsteijn** [hashicorp/terraform-provider-google#16880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_cloud_run_v2

### Potential Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "default" {
  name     = "service"

  location     = "us-central1"
  ingress      = "INGRESS_TRAFFIC_ALL"
  launch_stage = "BETA"

  template {
    execution_environment = "EXECUTION_ENVIRONMENT_GEN2"
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello:latest"
      volume_mounts {
        name       = "nfs"
        mount_path = "/mnt/nfs"
      }
      volume_mounts {
        name       = "gcs"
        mount_path = "/mnt/bucket"
      }

    }
    vpc_access {
      network_interfaces {
        network    = "default"
        subnetwork = "default"
      }
    }

    volumes {
      name = "nfs"
      nfs {
        server = google_filestore_instance.default.networks[0].ip_addresses[0]
        path   = "/share1"
      }
    }
    volumes {
      name = "bucket"
      gcs {
        bucket = google_storage_bucket.default.name
      }
    }
    
  }
}

```

### References

b/318495280

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9728
