### ISSUE TITLE
Enhancement: Make a Google Analytics Resource

### ISSUE THREAD

**Issue by BenJackGill** [hashicorp/terraform-provider-google#16898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I've noticed the absence of a resource to manage Google Analytics properties. There is no way to create a Google Analytics property under a known Google Analytics account ID.

Additionally I would like to easily link a newly created Google Analytics property with a Firebase project. But I am not sure if this should go in the requested `google_analytics_property` resource or handled separately somehow.

A `google_analytics_property` resource is crucial for automating the setup and management of Google Analytics within Google Cloud projects, particularly when integrated with Firebase.

This feature request is inspired by the behavior of the Firebase Management REST API and the process described in the [Firebase documentation](https://firebase.google.com/docs/projects/api/workflow_set-up-and-manage-project?platform=web#link-ga-account), which outlines the steps for creating a Google Analytics property under a Google Analytics account ID and linking it to a Firebase project.

### New or Affected Resource(s)

* google_analytics_property

### Potential Terraform Configuration

```tf
resource "google_analytics_property" "example" {
  account_id   = "your-google-analytics-account-id"
  property_name = "example-property"
  firebase_project_link {
    project_id = google_firebase_project.example.project_id
  }
  // Other necessary configurations
}
```

### References

* Firebase Management REST API documentation: https://firebase.google.com/docs/projects/api/workflow_set-up-and-manage-project?platform=web#link-ga-account

**Comment by rileykarson** [comment]
This isn't a resource we plan to support in this provider. We cover Google Cloud products, and analytics would be supported through a dedicated provider similar to `googleworkspace`.
