### ISSUE TITLE
Failing test(s): TestAccVmwareengine*, TestAccDataSourceVmwareEngine*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16911]
### Failure rates

- 100% since 2023-12-18 or 19th - data source tests
- 97% since 2023-12-09 - TestAccVmwareengineCluster_vmwareEngineClusterUpdate
- 75% since 2023-12-07 - TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate

### Impacted tests

- [TestAccDataSourceVmwareEngineNetwork_basic](https://hashicorp.teamcity.com/test/-5170648712771003854?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccDataSourceVmwareengineNetworkPeering_basic](https://hashicorp.teamcity.com/test/-4792442694527198035?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccDataSourceVmwareengineNetworkPolicy_basic](https://hashicorp.teamcity.com/test/6087071735946702855?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccVmwareengineCluster_vmwareEngineClusterUpdate](https://hashicorp.teamcity.com/test/-1736928788925031626?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- [TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate](https://hashicorp.teamcity.com/test/1920134295574754469?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)
- TestAccVmwareengineNetworkPeering_update
- TestAccVmwareengineNetworkPeering_vmwareEngineNetworkPeeringStandardExample
- TestAccVmwareengineNetworkPeering_vmwareEngineNetworkPeeringVenExampl
- TestAccVmwareengineNetworkPolicy_update
- TestAccVmwareengineNetworkPolicy_vmwareEngineNetworkPolicyBasicExample
- TestAccVmwareengineNetworkPolicy_vmwareEngineNetworkPolicyFullExample
- TestAccVmwareengineNetwork_vmwareEngineNetworkStandardExample
- TestAccVmwareenginePrivateCloud_vmwareEnginePrivateCloudUpdate
- TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate

### Affected Resource(s)

* google_XXXXX - leaving this unset initially

### Nightly build test history

- See links above

### Message(s)

These errors can occur, depending on what resources are/aren't present in a test

```
Error: Error waiting to create Network: Error waiting for Creating Network: Error code 13, message: an internal error has occurred
```

```
Error: Error waiting to create Cluster: Error waiting for Creating Cluster: Error code 13, message: an internal error has occurred
```

```
Error: Error waiting to create PrivateCloud: Error waiting for Creating PrivateCloud: Error code 13, message: an internal error has occurred
```

For example TestAccVmwareengineCluster_vmwareEngineClusterUpdate shows all 3 errors causing failures on different nights.

**Comment by SarahFrench** [comment]
When I was reviewing https://github.com/GoogleCloudPlatform/magic-modules/pull/9599 the new acceptance test was failing with similar 'error code 13' errors, but then later it failed and gave a [much more informative error message that showed that the test would time out when creating private cloud resources and trigger a test failure via a timeout](https://github.com/GoogleCloudPlatform/magic-modules/pull/9599#issuecomment-1877080000).

The solution in that PR was to reduce the number of nodes used by the `google_vmwareengine_private_cloud` resource in the test, thereby reducing the time taken to provision the PC.

This made me wonder if there were other acceptance tests that could benefit from similar scaling down of nodes, for example in [TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate](https://github.com/GoogleCloudPlatform/magic-modules/blob/fabeca9e96b1c3d4e9536d78d57e9e8eecdfb92d/mmv1/third_party/terraform/services/vmwareengine/resource_vmwareengine_subnet_test.go#L71).

However I don't know if this will help with the issue amongst all the VMware engine acc tests at the moment. I think a combination of reducing what is provisioned and reducing the parallelism of the tests could help.

**Comment by SarahFrench** [comment]
Another thought: I'm wondering if there is a limitation that explains why the tests currently create all the VMWare Engine resources directly in the nightly test projects instead of creating a new ephemeral project in the test. There's [one single VMware that has a 100% pass history](https://hashicorp.teamcity.com/test/-4547734895370963781?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A81565%29%2Cid%3A2000000016), `TestAccVmwareengineNetwork_vmwareEngineNetworkUpdate`,  and it's because it creates the resource under test in [a new project provisioned by the test](https://github.com/GoogleCloudPlatform/magic-modules/blob/49d4f888391fdf8d6fd4436778feec4842342b65/mmv1/third_party/terraform/services/vmwareengine/resource_vmwareengine_network_test.go#L63). Doing that for all the VMware tests might be an easy way to overcome the opaque errors that might be linked to quotas

**Comment by melinath** [comment]
I don't think there's a particular reason to keep those tests in the main project apart from trying to keep the number of extra projects down in general.

**Comment by SarahFrench** [comment]
See https://github.com/GoogleCloudPlatform/magic-modules/pull/9599 for PR reducing the resources provisioned by some VMware acceptance tests.

**Comment by melinath** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9769 has some more reduction
