### ISSUE TITLE
Labels on snapshot_properties of google_compute_resource_policy cannot be updated in-place (or at all)

### ISSUE THREAD

**Issue by MrTrustworthy** [hashicorp/terraform-provider-google#16936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Important info at the start

This is effectively a copy/re-opening of #11260 since the missing GCP PATCH endpoint is now available.

### Terraform Version

Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.32.0
+ provider registry.terraform.io/hashicorp/google v5.5.0
+ provider registry.terraform.io/hashicorp/google-beta v5.5.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/vault v3.22.0

### Affected Resource(s)

* `google_compute_resource_policy`

### Terraform Configuration Files

```tf
# [...snip...]
resource "google_compute_resource_policy" "policy_x" {
  name    = "policy-x"
  [....]
  snapshot_schedule_policy {
    [....]
    snapshot_properties {
      labels = var.labels # <--- issue appears when this changes
    }
  }
}
# [...snip...]
```

### Debug Output

The only relevant part of the output is this part from `terraform plan/apply`:

```tf
          ~ snapshot_properties {
              ~ labels            = { # forces replacement
                  ~ "my_label"             = "x" -> "y"
                    # (7 unchanged elements hidden)
                }
```

### Expected Behavior

No `# forces replacement` should need to happen for a label change

### Actual Behavior

It tries to force a replacement of the policy. This also fails, because it's still attached to the disk and needs to be manually un-attached first. 

### Steps to Reproduce

As above: Create any snapshot policy, then change the `snapshot_properties.labels`

### Important Factoids

This is really just a copy/re-open of #11260 , which contains more details in the thread than I can provide here :) There has not been a change in provider behaviour as far as I could see since that issue was opened. 

What HAS changed, however, is that the reason it got originally closed was because the limitation came from the GCP API: There was no associated PATCH endpoint that allowed for updating this data, so the TF provider wasn't able to solve this.

Now, there is an associated PATCH endpoint [as per the docs](https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies/patch), so I hope a solution is possible and not too complex.

### References

* [PATCH endpoint doc](https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies/patch)
* Previous issue  #11260

b/319619474

**Comment by karolgorc** [comment]
Couldn't recreate on the newest version of the provider. I think this got fixed without linking to this issue

Can you upgrade provider version and check if the issue still persists?

**Comment by karolgorc** [comment]
I also think this is tied to here if there are any issues. https://github.com/GoogleCloudPlatform/magic-modules/pull/12510
