### ISSUE TITLE
Adjust all the KMS rotation period in order to reduce administrative complexity for customers

### ISSUE THREAD

**Issue by romanini-ciandt** [hashicorp/terraform-provider-google#16955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
The proposal is to adjust all the KMS rotation period in order to reduce administrative complexity for customers.

Currently, most of the places are using 100000s (~1 days and 4hrs), but according to [How often to rotate keys](https://cloud.google.com/kms/docs/key-rotation#how_often_to_rotate_keys) section on [Key Rotation Google documentation](https://cloud.google.com/kms/docs/key-rotation) automatic key rotation at a defined period, such as every 90 days (7776000s), increases security with minimal administrative complexity.

### New or Affected Resource(s)

* google_kms_crypto_key

### References

* [#0000](https://cloud.google.com/kms/docs/key-rotation#how_often_to_rotate_keys)

**Comment by shuyama1** [comment]
Thanks for creating the issue, @romanini-ciandt!

I assume this is for documentation change only. Not sure how useful it will be for Terraform users. Pass it to next weekly triage meeting to take a look.

**Comment by SarahFrench** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/9792
