### ISSUE TITLE
Error when updating existing `google_spanner_instance` to add autoscaling

### ISSUE THREAD

**Issue by danxmoran** [hashicorp/terraform-provider-google#16983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: v1.5.7
Provider: ~> 5.10

### Affected Resource(s)

* google_spanner_instance

### Terraform Configuration Files

Trying to update config from this:
```tf
resource "google_spanner_instance" "spanner" {
  display_name     = "dan-test"
  config           = "regional-us-central1"
  processing_units = 1000
}
```

To this:
```tf
resource "google_spanner_instance" "spanner" {
  display_name     = "dan-test"
  config           = "regional-us-central1"
  autoscaling_config {
    autoscaling_limits {
      min_nodes = 1
      max_nodes = 10
    }
    autoscaling_targets {
      high_priority_cpu_utilization_percent = 75
      storage_utilization_percent           = 90
    }
  }
}
```

### Debug Output

We run via [atlantis](https://www.runatlantis.io/) and I don't have access to set `TF_LOG` in that env 😞 I can ask my SRE team for help if needed

### Expected Behavior

The existing Spanner instance should switch from "Manual allocation" scaling mode to "Autoscaling", with the configured autoscaling parameters.

### Actual Behavior

The `plan` succeeds:
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # google_spanner_instance.spanner will be updated in-place
~ resource "google_spanner_instance" "spanner" {
        id               = "dan-project/tfgen-spanid-20231016202225148"
        name             = "tfgen-spanid-20231016202225148"
        # (10 unchanged attributes hidden)

      + autoscaling_config {
          + autoscaling_limits {
              + max_nodes = 10
              + min_nodes = 1
            }
          + autoscaling_targets {
              + high_priority_cpu_utilization_percent = 75
              + storage_utilization_percent           = 90
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

But the `apply` fails:
```
Error: Error updating Instance "dan-project/tfgen-spanid-20231016202225148": googleapi: Error 400: Cannot update an instance or instance partition that does not have an existing autoscaling config.
```

### Steps to Reproduce

1. Define a `google_spanner_instance` using `processing_units`
2. `terraform apply`
3. Update the `google_spanner_instance` to replace `processing_units` with `autoscaling_config`
4. `terraform apply`

### Important Factoids

I ran the equivalent `gcloud` command to apply the output, with HTTP request logging:
```shell
gcloud --log-http beta spanner instances update \
  --autoscaling-min-nodes=1 \
  --autoscaling-max-nodes=10 \
  --autoscaling-storage-target=90 \
  --autoscaling-high-priority-cpu-target=75 \
  tfgen-spanid-20231016202225148
```

The CLI sent a `PATCH` request to `https://spanner.googleapis.com/v1/projects/dan-project/instances/tfgen-spanid-20231016202225148?alt=json`, with body:
```json
{
  "fieldMask": "autoscalingConfig",
  "instance": {
    "autoscalingConfig": {
      "autoscalingLimits": {
        "maxProcessingUnits": 10000,
        "minProcessingUnits": 1000
      },
      "autoscalingTargets": {
        "highPriorityCpuUtilizationPercent": 75,
        "storageUtilizationPercent": 90
      }
    }
  }
}
```

### References

* https://cloud.google.com/spanner/docs/create-manage-instances#modify-managed-autoscaler

b/320651167

**Comment by danxmoran** [comment]
I can work on a fix for this - I've managed to reproduce it in the `magic-modules` tests locally.

**Comment by melinath** [comment]
I can reproduce this using the examples on the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_instance)
