### ISSUE TITLE
Missing documented `google_iam_workload_identity_pool` data source

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-google#16999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```shell
Terraform v1.5.7
on windows_amd64
```

### Affected Resource(s)

* `google_iam_workload_identity_pool`

### Terraform Configuration Files

```tf
data "google_iam_workload_identity_pool" "github" {
  workload_identity_pool_id = "github"
}
```

### Debug Output

n/a

### Expected Behavior

Expected to be able to look up a workload identity pool.

### Actual Behavior

Got the following error.

```shell
╷
│ Error: Invalid data source
│ 
│   on data.tf line 32, in data "google_iam_workload_identity_pool" "github":
│   32: data "google_iam_workload_identity_pool" "github" {
│ 
│ The provider hashicorp/google does not support data source
│ "google_iam_workload_identity_pool".
│ 
│ Did you intend to use the managed resource type
│ "google_iam_workload_identity_pool"? If so, declare this using a "resource"
│ block instead of a "data" block.
╵
Error: Process completed with exit code 1.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by edwardmedia** [comment]
@stevehipwell have you tried google-beta? It listed as beta in the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/iam_workload_identity_pool)

**Comment by stevehipwell** [comment]
@edwardmedia no I haven't, I didn't spot this in the docs. Thanks for the reply.

**Comment by edwardmedia** [comment]
@stevehipwell closing this now. Feel free to reopen if you still see an issue
