### ISSUE TITLE
Add support for readiness checks and disabling TCP connections for Cloud Workstation configurations

### ISSUE THREAD

**Issue by daanheikens** [hashicorp/terraform-provider-google#16997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_workstations_workstation_config` resource is currently missing support for the following API fields:

- [readinessChecks](https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs#readinesscheck)
- [disableTcpConnections](https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs#resource:-workstationconfig)

### New or Affected Resource(s)

`google_workstations_workstation_config`

### Potential Terraform Configuration

```tf
resource "google_workstations_workstation_config" "default" {
  disable_tcp_connections = true 

  readiness_checks {
    path = "/"
    port = 80
  }
  
  readiness_checks {
    path = "/healthz"
    port = 8080
  }
}
```

### References
https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs#resource:-workstationconfig

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workstations_workstation_config

b/320650639

**Comment by bschaatsbergen** [comment]
Hey @daanheikens, thanks for taking the time to raise this issue. I'll happily pick it up 👍🏼.

**Comment by bschaatsbergen** [comment]
Note, these will be 2 separate PRs.
