### ISSUE TITLE
Support INTERNET_IP_PORT value for network_endpoint_type of google_compute_region_network_endpoint_group

### ISSUE THREAD

**Issue by gmogr** [hashicorp/terraform-provider-google#17000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Resource: **google_compute_region_network_endpoint_group** [link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group)
Currenlty (in version 5.11.0) supported values for the field **network_endpoint_type** are: SERVERLESS and PRIVATE_SERVICE_CONNECT. But the api supports INTERNET_IP_PORT for the regional negs [link](https://cloud.google.com/sdk/gcloud/reference/compute/network-endpoint-groups/create).

### New or Affected Resource(s)

* google_compute_region_network_endpoint_group

### Potential Terraform Configuration

```tf
resource "google_compute_region_network_endpoint_group" "network_endpoint_group" {
  name                  = "region-network-endpoint-group"
  network_endpoint_type = "INTERNET_IP_PORT"
  default_port          = "443"
  region = var.region
}
```

### References

b/320651131

**Comment by Cheriit** [comment]
@gmogr The support for INTERNET_IP_PORT should be added

**Comment by slevenick** [comment]
Closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/9863
