### ISSUE TITLE
Add  gce_setup.shield_instance_config field in the Vertex AI Workbench Instance resource

### ISSUE THREAD

**Issue by gsaiz** [hashicorp/terraform-provider-google#17002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to improve the Terraform support for the Vertex AI Workbench Instance type.

In the web console, Google is already asking users to migrate existing notebooks the new "Instance" type: 
![image](https://github.com/hashicorp/terraform-provider-google/assets/25729908/04b29237-07e6-403d-b976-5e0ca948a8da)

Specifically, I would like to:

1. Add shielded VM configurations for the new Vertex AI Workbench "Instance" type. This is particularly helpful for secure boot, since it is disabled by default.
2. Add the auto-shutdown after idle time option.

Issue 1. is already possible, using Terraform, for the older Vertex AI User-Managed Notebooks type. It is also possible to configure it via the UI.
Issue 2. is possible via the UI. It is also possible via the metadata tags according to https://github.com/hashicorp/terraform-provider-google/issues/15654

### New or Affected Resource(s)

- google_workbench_instance

### Potential Terraform Configuration

This is what is possible already in [google_notebooks_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#nested_shielded_instance_config)

```tf
resource "google_notebooks_instance" "instance" {
  name = "notebooks-instance"
  location = "us-central1-a"
  machine_type = "n1-standard-1"
  vm_image {
    project      = "deeplearning-platform-release"
    image_family = "tf-latest-cpu"
  }
  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot = true
    enable_vtpm = true
  }
}
```

The google_workbench_instance equivalent would be

```tf
resource "google_workbench_instance" "instance" {
  name = "workbench-instance"
  location = "us-central1-a"
  gce_setup {
    machine_type = "n1-standard-1"
    vm_image {
      project      = "deeplearning-platform-release"
      family       = "tf-latest-cpu"
    }
    shielded_instance_config {
      enable_integrity_monitoring = true
      enable_secure_boot = true
      enable_vtpm = true
    }
    metadata {
      idle-timeout-seconds = 3600
    }
  }
}
}
```

### References

* #[15654](https://github.com/hashicorp/terraform-provider-google/issues/15654)
* https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v2/projects.locations.instances#Instance

b/320651030

**Comment by SarahFrench** [comment]
Note from triage: This request would mean updating the [gce_setup](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workbench_instance#gce_setup) field to include the shieldInstanceConfig field [described in the docs here](https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v2/projects.locations.instances#GceSetup)

**Comment by bcreddy-gcp** [comment]
We have a Draft CL for shielded instance config here: https://github.com/GoogleCloudPlatform/magic-modules/pull/9622. Currently the values flip flop between true and false due to a bug with the API. The feature will be enabled once it is resolved. 
And for idle-shutdown, it is managed using metadata as commented.

**Comment by gsaiz** [comment]
@bcreddy-gcp Thank you for linking to the right PR.

Is there any chance I can test this, maybe in the google-beta provider? I am currently blocked by my organisational's policy, which enforces secure boot

> Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 7, message: Constraint constraints/compute.requireShieldedVm violated for project projects/{PROJECT_NAME}. Secure Boot is not enabled in the 'shielded_instance_config' field. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information.
