### ISSUE TITLE
Blue-Green Upgrade Configuration Not Applied Correctly

### ISSUE THREAD

**Issue by vgupt312** [hashicorp/terraform-provider-google#17008]
I am facing an issue with the blue-green upgrade strategy on Google Cloud Platform when applying the configuration using Terraform provider 5.11.0. Below is the relevant Terraform code and the corresponding configuration:

dynamic "blue_green_settings" {
  for_each = lookup(local.node_pool_upgrade_settings, "strategy", "BLUE_GREEN") == "BLUE_GREEN" ? [1] : []
  content {
    node_pool_soak_duration = lookup(local.blue_green_settings, "node_pool_soak_duration", 1)
    standard_rollout_policy {
      batch_soak_duration = lookup(local.blue_green_settings, "batch_soak_duration", 1)
      batch_percentage    = lookup(local.blue_green_settings, "batch_node_count", null) == null ? lookup(local.blue_green_settings, "batch_percentage", 0.25) : null
      batch_node_count    = lookup(local.blue_green_settings, "batch_node_count", null)
    }
  }
}

Configuration:
strategy: "BLUE_GREEN"
blue_green_settings:
  node_pool_soak_duration: 120s
  batch_soak_duration: 300s
  batch_percentage: 0.5

However, after applying this configuration, GCP is not considering the provided values and is displaying the following:
Upgrade strategy: Blue-green upgrade
Batch node count: 0
Batch soak duration: 0s
Nodepool soak duration: 3600s

It seems that the batch_node_count and batch_soak_duration are not being applied as expected. 
Please investigate this issue and let me know if there's any misconfiguration or if there's a bug on the GCP side that needs attention.
However it is working fine when i am applying these settings using google command line.

I am attaching tfstate and other relevant documents.
![backend-pool-03-config](https://github.com/hashicorp/terraform-provider-google/assets/24548518/3f6e8a99-e989-402c-ad27-9a2249dd7510)
![terraform code](https://github.com/hashicorp/terraform-provider-google/assets/24548518/1d1aa412-8ab0-4acd-8a0d-630d345c1c78)
![terraform config](https://github.com/hashicorp/terraform-provider-google/assets/24548518/ce9409f6-e11e-49fc-8425-4ed273cf143a)
![tfstate](https://github.com/hashicorp/terraform-provider-google/assets/24548518/0032001c-f973-42d7-bc52-bf05a6e1b66f)
 

Thanks,
Vivek

**Comment by edwardmedia** [comment]
@vgupt312 can you share the complete config and debug log? Please post the log at [gist](https://gist.github.com/) and share the link.

**Comment by vgupt312** [comment]
Terraform plan output:
https://gist.github.com/vgupt312/f7219b8120e1256134d1d1073e5c107e

**Comment by edwardmedia** [comment]
@vgupt312 the **plan** does not tell what went wrong. Do you have the log for **apply**?

**Comment by edwardmedia** [comment]
@vgupt312 closing this assuming it is no longer an issue.
