### ISSUE TITLE
Default location precedence can significantly impact existing GKE clusters

### ISSUE THREAD

**Issue by gygitlab** [hashicorp/terraform-provider-google#17025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* `google_container_cluster`

### Description

In 5.x, [the default value for `location` was changed in precedence from `zone` to `region`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade#changes-to-how-default-location-region-and-zone-values-are-obtained-for-resources).

This change is notably impactful for `google_container_cluster` resources [as this value determines whether a cluster is regional or zonal](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#location). As a result a user upgrading provider with a cluster that relied on the default `zone` setting in the provider will now see their whole cluster destroy and changed over to a regional cluster.

To me this is a very destructive change that wasn't considered with the default location behaviour as it's not been called out anywhere.

For `google_container_cluster` specifically this should be managed more gracefully with perhaps a new setting to select what default location it can use (e.g. location_type). Or of course a revert of the location precedence change.

**Comment by edwardmedia** [comment]
@gygitlab sorry for the inconvenience, but I am not sure how we can help. I don't believe rollback is an option. From what I can see, you may 1) provide the location explicitly 2) not upgrade to v5.x. What suggestions do you have?

**Comment by gygitlab** [comment]
How about a new setting for `google_container_cluster` that changes what default location it specifically should use?

Or the ability to retrieve the default configured zone from the provider without sensitive data that comes with `google_client_config`?

**Comment by edwardmedia** [comment]
@gygitlab adding `location_type` might be able to achieve that, but I do see there are issues: 1) against the design pattern. This field is not supported by the api so it will confuse other users. 2) cost-effectiveness. I can not be convinced it is wa worthwhile by introducing a field for a mitigation while providing the location explicitly is available.

@hao-nan-li what do you think about this request?

**Comment by hao-nan-li** [comment]
The default value location changed, reason why that was out as part of a major release. I don't think rollback is an option. If making changes to the existing config is not the best option, perhaps going back to 4.x makes it.

**Comment by gygitlab** [comment]
Understood yeah.

Apologies it does appear I've jumped the gun here in that the specific scenario of upgrading a 4.x GKE cluster to 5.x doesn't actually appear to be affected by this thankfully.

And as an additional failsafe we can use `ignore_changes` in Terraform just to be sure.

Apologies again, will close thanks.
