### ISSUE TITLE
vertex search app and data store creation support

### ISSUE THREAD

**Issue by bademiya5306** [hashicorp/terraform-provider-google#17038]
Hi

i want to create a vertex ai search app that uses website urls as data store.  I see there is a similar request  in https://github.com/hashicorp/terraform-provider-google/issues/16787.

I would like to know if there is any ETA when this resource will be released so that i can start creating projects.

**Comment by edwardmedia** [comment]
@bademiya5306  In normal situation, closed PRs are released Monday or Tuesday the week after. The PR for https://github.com/hashicorp/terraform-provider-google/issues/16787 has been merged yesterday. Likely you will have it by next Tuesday.

**Comment by bademiya5306** [comment]
Does that pr provides support to create datastores for website urls? I did not see that option in those PRs
