### ISSUE TITLE
google_bigquery_dataset: Suppress location diff for multi-regions

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#17031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

BigQuery resources that support a `location` field are able to accept multi-region values in lowercase (e.g. `us`, `eu`), but since multi-regions are capitalized by the BigQuery API, using lowercase values result in a permanent diff.

It would be nice if Terraform can suppress such diffs since it is easy for developers to forget that multi-regions should be capitalized. This pain point is particularly amplified when using Terraform in CI/CD since the permanent diff is usually not detected until much later.

### New or Affected Resource(s)

* google_bigquery_*

b/321386313

**Comment by melinath** [comment]
Do you know which specific resources are missing the diff suppress? I see that bigquery table has it.

**Comment by jcanseco** [comment]
Nvm, turns out we're at an older provider version :)
