### ISSUE TITLE
Creating VPC Private Connection fails due to GlobalAddress not found in network

### ISSUE THREAD

**Issue by moulip** [hashicorp/terraform-provider-google#17041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.7.0
+ provider registry.terraform.io/hashicorp/google v5.12.0
+ provider registry.terraform.io/hashicorp/google-beta v5.12.0

### Affected Resource(s)
google_service_networking_connection

### Terraform Configuration Files

```tf
resource "google_compute_global_address" "private_ip_alloc" {
  provider = google-beta
  name          = "private-ip-alloc"
  purpose       = "PRIVATE_SERVICE_CONNECT"
  address_type  = "INTERNAL"
  address       = "10.0.12.5"
  network       = google_compute_network.vpc_network.id
}

resource "google_service_networking_connection" "default" {
  network                 = google_compute_network.vpc_network.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_alloc.name]

```

### Expected Behavior

The Private connection should be created into the VPC.

### Actual Behavior

The deployment fails with this output:
```
 │ Error: Error waiting for Create Service Networking Connection: Error code 9, message: Allocated IP range 'private-ip-alloc' not found in network.
│ Help Token: ARD_zUY-jXckm6YSM3CqakPYFICqsOwVxFSY6kPeGmmNpYO7MttKQt5UHMn3JiQvozDi5Ii9yV8ODLDyO1xGf1sN15movx-1TgpxpReDb5FTLz8I
```
The GlobalAddress has been created:

```
 gcloud compute addresses list

 NAME              ADDRESS/RANGE  TYPE      PURPOSE                  NETWORK       REGION        SUBNET  STATUS
private-ip-alloc  10.0.12.5      INTERNAL  PRIVATE_SERVICE_CONNECT  testinfravpc                        RESERVED

```

### Steps to Reproduce

Try to deploy with terraform apply

### Description

As stated above I'm trying to create a Private Connection into a VPC to enable Cloud SQL private connection. It keeps failing stating that the GlobalAddress is not found.

**Comment by edwardmedia** [comment]
@moulip can you share the debug log?

**Comment by moulip** [comment]
Hi thank you for your interest.
Here you are:

https://gist.github.com/moulip/521c61da7eab912745600793adafe8b3

**Comment by edwardmedia** [comment]
@moulip [reserved_peering_ranges](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_connection#reserved_peering_ranges) is expected PEERING type. Can you update the purpose and try again?

```tf
resource "google_compute_global_address" "private_ip_alloc" {
  provider = google-beta
  name          = "private-ip-alloc"
  purpose       = "PRIVATE_SERVICE_CONNECT".    <----- "VPC_PEERING"?
  address_type  = "INTERNAL"
  address       = "10.0.12.5"
  network       = google_compute_network.vpc_network.id
}
```

**Comment by moulip** [comment]
Hi,

Thanks that worked. It's not very intuitive but I know that's on Google.
