### ISSUE TITLE
[BUG]: `resource_limits` and `enable_autopilot` can't be specified at the same time

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-google#17045]
`resource_limits` and `enable_autopilot` can't be specified at the same time as they are conflicting arguments. We could check this in the plan already.

```
│ Error: Conflicting configuration arguments
│ 
│   with google_container_cluster.example,
│   on gke.tf line 72, in resource "google_container_cluster" "example":
│   72:   cluster_autoscaling {
│ 
│ "cluster_autoscaling.0.resource_limits": conflicts with enable_autopilot
╵

```

**Comment by edwardmedia** [comment]
@bschaatsbergen below is what the [api](In Autopilot, GKE automatically scales your nodes based on the number of Pods in your cluster.) describe about [cluster_autoscaling](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#cluster_autoscaling)

```
In Autopilot, GKE automatically scales your nodes based on the number of Pods in your cluster.
```

Are you able to achieve it via other tools?

**Comment by edwardmedia** [comment]
@bschaatsbergen closing this now. Feel free to reopen if you see both need to be specified at the same
