### ISSUE TITLE
Support VM image version that is present in the API for google_notebooks_runtime

### ISSUE THREAD

**Issue by cybersnacker** [hashicorp/terraform-provider-google#17056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google maintains different families of VM images that can be used to create a notebook runtime. Users should have the ability to provide the software version depending on their needs and not just default to the latest image of a particular image family. This feature is supported in [Google API](https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v1/projects.locations.runtimes), but not in the terraform module
<img width="859" alt="Screenshot 2024-01-19 at 7 17 20 PM" src="https://github.com/hashicorp/terraform-provider-google/assets/7777138/0db1e44c-875e-4704-9ec8-39dd54f33c15">

### New or Affected Resource(s)

* google_notebooks_runtime

### Potential Terraform Configuration

Module - [Module](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_runtime#nested_kernels)

```
### References
software_config
{
version
}


b/338674574

**Comment by roaks3** [comment]
@melinath I'm trying to understand why the `upstream` label was added here. As best I can tell, this field is already configurable through the API. I see that we already have the `softwareConfig` field, but it just doesn't include `version` yet.

**Comment by melinath** [comment]
@roaks3 Thanks for flagging this - I was supposed to look into this in more detail but lost track of it. The problem with the request as written is that the `version` field in the API is output-only, so it's not settable. Making it settable would be a feature request for the API. That said, it looks like the API already allows users to set software versions using the `kernels.0.tag` field, which is supported in the provider: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_runtime#kernels

@cybersnacker does that field meet your needs? If not, could you elaborate on what you're not able to do, ideally with a link to a quickstart or similar that explains the workflow that is not supported?

**Comment by cybersnacker** [comment]
My bad - I didn't realize `version` was output only. 

My goal is to change the environment that the notebook runtime begins with/notebook base VM. The process to do this via the UI is below. 
<img width="1135" alt="Screenshot 2024-02-17 at 7 31 36 PM" src="https://github.com/hashicorp/terraform-provider-google/assets/7777138/656f05de-7730-43ef-adf1-f8b2db7de1b0">

Ex: If I choose the 3.10 environment, I get the latest or M116 (as of Feb 16th) version. If I choose the 3.7, I get a notebook instance with M112 version. 

I've not had success specifying this information in the software_config block. I think the release versions [here](https://cloud.google.com/vertexai/docs/workbench/releasenotes_ga=2.248870031.-967759303.1682613515
) correspond to the images repo [here](https://console.cloud.google.com/artifacts/docker/deeplearning-platform-release/us/gcr.io/base-cpu). The other option is the [Deep Learning VM image](https://cloud.google.com/deep-learning-vm/docs/images#listing-versions), but the documentation specifies a docker registry/repo path

Here's my example software_config_block. FWIW, I didn't succeed with [runtime create API ](https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v1/projects.locations.runtimes/create) either.  Please let me know if this is not the right usage

Here's the block via the runtimes create API
```"softwareConfig": {
    "idleShutdown": true,
    "idleShutdownTimeout": 60,
    "kernels": [
      {
        "repository": "gcr.io/deeplearning-platform-release/base-cpu",
        "tag": "M115"
      }
    ]
  }
```

Here's the block with Terraform 
```
software_config {
    idle_shutdown_timeout    = var.idle_shutdown_timeout
    enable_health_monitoring = false
    software_config {
    kernels {
      repository = "gcr.io/deeplearning-platform-release/base-cpu"
      tag        = "M115"
    }
  }
```

**Comment by melinath** [comment]
I don't have a particularly deep knowledge of this API. However, it looks like the screenshot is for "create instance" - so maybe this is something to accomplish with the google_notebooks_instance resource instead? I see there are some examples of referencing `deeplearning-platform-release` images: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#example-usage---notebook-instance-basic

**Comment by cybersnacker** [comment]
The screenshot is still accurate for manage notebooks (Google says instances even when we try to create a managed notebook via the UI). To simplify the question - what terraform block corresponds to setting/choosing the environment or choosing a particular notebook VM release? Sometimes Google's latest provided releases have defects compared to older versions. 
![image](https://github.com/hashicorp/terraform-provider-google/assets/7777138/7989c05b-dd24-4062-95d4-5e2099afc403)

**Comment by melinath** [comment]
Unfortunately the UI doesn't always clearly map to specific API fields, and Terraform support is all based on the API implementation - for us to say whether this is already supported, we'd need to know what the underlying API field is. If you can find out how to do this same workflow with gcloud, the `--log-http` feature could help figure out what API field it uses.

**Comment by melinath** [comment]
Forwarding to the service team in case they are able to better interpret this request.

**Comment by cybersnacker** [comment]
It looks like Managed Notebooks is being deprecated in 2025. Any enhancements/compatibility between GCP provided functionality and Terraform is likely not warranted. 

Thanks for looking into this! Closing it for now
