### ISSUE TITLE
Support data_governance_type in google_bigquery_routine

### ISSUE THREAD

**Issue by hrfmmr** [hashicorp/terraform-provider-google#17061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In [certain cases](https://cloud.google.com/bigquery/docs/user-defined-functions#custom-mask), BigQuery user-defined functions require the specification of `data_governance_type`. Currently, the `google_bigquery_routine` resource definition does not allow for this specification. It would be nice to enable the specification of `data_governance_type`.

### New or Affected Resource(s)

* google_bigquery_routine

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_bigquery_routine" "example" {
  dataset_id      = "dataset_id"
  routine_id      = "routine_id"
  routine_type    = "SCALAR_FUNCTION"
  language        = "SQL"
  definition_body = "'*'"

  // 👇Add this option
  data_governance_type = "DATA_MASKING" 

  arguments {
    name = "s"
    data_type = jsonencode(
      {
        typeKind = "STRING"
      }
    )
  }

  return_type = jsonencode(
    {
      typeKind = "STRING"
    }
  )
}
```

### References

* https://github.com/googleapis/python-bigquery/pull/1708

b/321923926

**Comment by Kulja** [comment]
Once this is merged would it be possible to use it in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_datapolicy_data_policy#data_masking_policy?
