### ISSUE TITLE
Enhance google_identity_platform_config by exporting api key

### ISSUE THREAD

**Issue by vsoloviov** [hashicorp/terraform-provider-google#17063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When `google_identity_platform_config` resource is created we might need to access Identity Platform using API key.
Currently, resource doesn't export [apiKey](https://cloud.google.com/identity-platform/docs/reference/rest/v2/Config#clientconfig) attribute.

### New or Affected Resource(s)

* google_identity_platform_config

### Potential Terraform Configuration

```tf
resource "google_identity_platform_config" "default" {
  project = google_project.default.project_id
...
}

output "api_key" {
  description = "API key that can be used when making requests for this project."
  value       = google_identity_platform_config.default.api_key
}
```

### References

* #0000

b/321923890

**Comment by gleichda** [comment]
@hao-nan-li This one can be closed. I had a formatting issue in the comment so the issues did not get closed.
