### ISSUE TITLE
Error: Failed to load plugin schemas

### ISSUE THREAD

**Issue by AdamBriers** [hashicorp/terraform-provider-google#17078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.0

### Affected Resource(s)

Production pipeline in cloudbuild

*Terragrunt version is 0.47.0

### Terraform Configuration Files

```terraform {
  required_version = ">= 0.14.2"

  # Uncomment this after the initial bootstrap to move the terraform state into the GCS Bucket
  backend "gcs" {
    bucket = "gc-a-prj-cloudbld-0001-7087-terraform-state"
    prefix = "terraform/bootstrap/state"
  }

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.51.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 2.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 2.2"
    }
  }
}
```

### Steps to Reproduce

Pushed a change (new project) to our cloudbuild that hits our production trigger, fails on step 2 with various repeated errors failed to load plugin schemas "registry.terraform.io/hashicorp/google-beta"

**Comment by AdamBriers** [comment]
Step #2: │ Error: Failed to load plugin schemas
Step #2: │
Step #2: │ Error while loading schemas for plugin components: Failed to obtain
Step #2: │ provider schema: Could not load the schema for provider
Step #2: │ registry.terraform.io/hashicorp/google-beta: failed to instantiate provider
Step #2: │ "registry.terraform.io/hashicorp/google-beta" to obtain schema: timeout
Step #2: │ while waiting for plugin to start..

**Comment by AdamBriers** [comment]
@edwardmedia i can, i am just wary of jumping too far ahead if that makes sense?

**Comment by AdamBriers** [comment]
The repo terraform version is 1.4.0, i assume i am safe to update the following to the same version?
 terraform {
  required_version = ">= 0.14.2"

And the same regarding the provider version from 3.51.0 to 5.13.0?

**Comment by edwardmedia** [comment]
@AdamBriers there are breaking changes in each major releases. Regarding if upgrading is safe, you need to review the documents. Below is the one that is for grading v5.0.0

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade

**Comment by AdamBriers** [comment]
Thanks, i will review.

**Comment by edwardmedia** [comment]
@AdamBriers closing this now. Feel free to reopen if you still see an issue after upgrading all versions to the latest.

**Comment by AdamBriers** [comment]
FYI @edwardmedia i updated my provider etc and still had the same issue. I fixed the issue by bumping up the spec of the machine build used for cloudbuild (previously on N1_HIGHCPU_8)
