### ISSUE TITLE
Add support for CLOUDSDK_AUTH_ACCESS_TOKEN

### ISSUE THREAD

**Issue by nshenry03** [hashicorp/terraform-provider-google#17089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

From the [Authorize the gcloud CLI](https://cloud.google.com/sdk/docs/authorizing) documentation, it says

> If you already have an access token, use one of the following methods to pass the access token to the gcloud CLI:
> * ...
> * Set the `CLOUDSDK_AUTH_ACCESS_TOKEN` environment variable to the access token value.

This allows you to use `gcloud` CLI tool (for example `gcloud projects list`). There is no mention of `GOOGLE_OAUTH_ACCESS_TOKEN` (the environment variable used to configure [`access_token`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#access_token) for the Google Terraform provider.

Admittedly, I'm brand new to using Google.

Is there a reason these are different? Would it make sense to allow the Google Terraform provider to use the `CLOUDSDK_AUTH_ACCESS_TOKEN` environment variable to configure `access_token` or is there a reason for not doing this?

It made if fairly confusing for me...

### New or Affected Resource(s)

N/A

### Potential Terraform Configuration

```bash
export CLOUDSDK_AUTH_ACCESS_TOKEN='...'
```

Is the same as

```bash
export GOOGLE_OAUTH_ACCESS_TOKEN='...'
```

### References

* [Authorize the gcloud CLI](https://cloud.google.com/sdk/docs/authorizing)
* [`access_token`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#access_token)

**Comment by BBBmau** [comment]
> I'm not sure we want to do this- we share some variables with gcloud, but mostly those related to application default credentials. It may be confusing to have CLOUDSDK_ prefixed vars affect Terraform.

Closing due to no further interest from the community and from the comment above
