### ISSUE TITLE
google_iap_brand not detected in terraform plan - terraform apply fails 

### ISSUE THREAD

**Issue by raweber42** [hashicorp/terraform-provider-google#17094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.7.0

### Affected Resource(s)

* google_iap_brand

### Terraform Configuration Files

```
provider "google" {
  region  = var.region
  project = var.project_id
}

variable "region" {}
variable "project_id" {}

variable "kubernetes-workspace" {}

data "terraform_remote_state" "kubernetes-workspace" {
  backend = "remote"

  config = {
    organization = "my-organisation"
    workspaces = {
      name = var.kubernetes-workspace
    }
  }
}

data "google_client_config" "provider" {}

provider "kubernetes" {
  host  = "https://${data.terraform_remote_state.kubernetes-workspace.outputs.endpoint}"
  token = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(
    data.terraform_remote_state.kubernetes-workspace.outputs.cluster_ca_certificate,
  )
}

resource "google_compute_global_address" "service" {
  name = "service"
}

resource "google_project_service" "project_service" {
  project = var.project_id
  service = "iap.googleapis.com"
}

resource "google_iap_brand" "project_brand" {
  support_email     = "support@example.com"
  application_title = "project-11111111111111" // Or for all DEV?
  project           = var.project_id
}

resource "google_iap_client" "project_client" {
  display_name = "Service Client"
  brand        =  google_iap_brand.project_brand.name
}
```

### Expected Behavior

Running `terraform plan` should have detected that the resource already exists.

### Actual Behavior

`terraform plan` did not detect that the resource already existed (it was created manually beforehand). Therefore it suggests that a new `google_iap_brand` will be created, but when running `apply`, it throws the error:
```
|   Error: Error creating Brand: googleapi: Error 409: Requested entity already exists
│ 
│   with google_iap_brand.project_brand,
│   on main.tf line 41, in resource "google_iap_brand" "project_brand":
│   41: resource "google_iap_brand" "project_brand" {

```

### Steps to Reproduce

1. Activate IAP for a resource manually in Google Cloud Console
2. Create OAuth Screen when asked to (this will create the brand automatically)
3. Create new google_iap_brand in terraform (use same values as the ones retrievable via `gcloud iap oauth-brands list`
4. Run `terraform plan` (will show that the brand will be newly created)
5. Run `terraform apply` (will fail, because the resource already exists.

### References

* #0000

**Comment by edwardmedia** [comment]
@raweber42  the resource already existed (it was created manually beforehand), shouldn't you [import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iap_brand#import) it first?

**Comment by edwardmedia** [comment]
@raweber42 is this still an issue?

**Comment by edwardmedia** [comment]
@raweber42 closing this assuming it is no longer an issue
