### ISSUE TITLE
Merge CompareCaseInsensitive with CaseDiffSuppress

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17115]
We have two identical functions in common_diff_suppress: CompareCaseInsensitive and CaseDiffSuppress. We should standardize on one. I would prefer CaseDiffSuppress since it matches our current convention of including DiffSuppress in the function name.

**Comment by BBBmau** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/9898
