### ISSUE TITLE
Documentation bug: Terraform Doc says that `message_retention_duration` is capped at 7 days; it's unclear why.

### ISSUE THREAD

**Issue by chases2** [hashicorp/terraform-provider-google#17119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Document

Emphasis has been added to both document quotes

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#message_retention_duration

> (Optional) How long to retain unacknowledged messages in the subscription's backlog, from the moment a message is published. If retain_acked_messages is true, then this also configures the retention of acknowledged messages, and thus configures how far back in time a subscriptions.seek can be done. Defaults to 7 days. **Cannot be more than 7 days ("604800s")** or less than 10 minutes ("600s"). A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "600.5s".

https://cloud.google.com/pubsub/docs/replay-overview#subscription_message_retention

> Pub/Sub begins retaining messages on behalf of a subscription when the subscription is created. By default, Pub/Sub discards a message from a subscription as soon as the message is acknowledged. Unacknowledged messages are retained for a default of 7 days (configurable by the subscription's [message_retention_duration](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscription.FIELDS.bool.google.pubsub.v1.Subscription.message_retention_duration) property).
> 
> Configuring a subscription to retain acknowledged messages (using the [retain_acked_messages](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscription.FIELDS.bool.google.pubsub.v1.Subscription.retain_acked_messages) property) lets you replay previously-acked messages retained by the subscription. You can configure messages to be retained for a maximum of 7 days in a subscription. This configuration applies to both acknowledged and unacknowledged messages. **However, messages can be retained in a subscription for more than 7 days if the message retention duration configured on its topic is greater than 7 days.**

### Expected Behavior

Is the limitation on this field listed in Terraform's document a limitation of Terraform, or of Google Cloud?

If it's a limitation on Google Cloud (ie: "It can't be set past 7 days, that's a thing about subscriptions"), that's not true and should be removed or updated.

If it's a limitation on Terraform (ie: "We can't set it past 7 days"), it should explicitly say that it's limited to 7 days regardless of the topic's settings. Maybe with a bug attached; that's an unusual limitation.

**Comment by edwardmedia** [comment]
@chases2 I think the behavior was set by the[ api](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions). Take a look at the field **messageRetentionDuration** to see if that make sense.

https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions

**Comment by edwardmedia** [comment]
It is set the by the api. Closing this now

**Comment by chases2** [comment]
Follow-up: This limitation is very real, caused by the Google API, and (according to their documentation) arbitrary. Not sure what the best thing to do is if you want more than 7 days. Change it manually?

```
│ Error: Error creating Subscription: googleapi: Error 400: The value for message retention duration is out of bounds. You passed 744h in the request, but the value must be between 10m and 168h.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.DebugInfo",
│     "detail": "Invalid MessageRetentionDuration (requested=744h min=10m max=168h)"
│   }
│ ]
│ 
│   with module.sturdy_pubsub_topic.google_pubsub_subscription.dlq_subscription,
│   on ../../../modules/sturdy_topic/main.tf line 17, in resource "google_pubsub_subscription" "dlq_subscription":
│   17: resource "google_pubsub_subscription" "dlq_subscription" {
```
