### ISSUE TITLE
Expose the GCS bucket name in `google_composer_environment` attributes

### ISSUE THREAD

**Issue by alucryd** [hashicorp/terraform-provider-google#17126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be nice to expose the name of the created GCS bucket in the composer resource attributes, the same way the name of the GKE cluster is already exposed. This could then be used in `google_storage_bucket_iam_binding` resources for example.

### New or Affected Resource(s)

* google_composer_environment

### Potential Terraform Configuration

```tf
resource "google_composer_environment" "airflow" {
  name    = var.name
  project = var.project
  region  = var.region
  config {
    software_config {
      image_version = var.composer_version
    }
  }
}

resource "google_storage_bucket_iam_binding" "airflow" {
  bucket = google_composer_environment.airflow.config.0.gcs_bucket
  role   = "roles/storage.user"
  members = [
    "serviceAccount:${google_service_account.airflow.email}"
  ]
}

```

### References

b/322961580

**Comment by spapi17** [comment]
@alucryd, the GCS bucket is exposed with config.0.dag_gcs_prefix and config.0.storage_config.bucket

**Comment by alucryd** [comment]
@spapi17 I tried your suggestion, but got an error:
```
Error: Unsupported attribute
│ 
│   on composer.tf line 59, in resource "google_storage_bucket_access_control" "dags":
│   59:   bucket = google_composer_environment.airflow.config.0.storage_config.bucket
│ 
│ This object has no argument, nested block, or exported attribute named
│ "storage_config".
```

**Comment by spapi17** [comment]
@alucryd Sorry for inaccuracy here, please try google_composer_environment.airflow.storage_config.0.bucket

**Comment by alucryd** [comment]
Doesn't seem to work either, however I ended up setting up an external bucket as it's easier to keep it across composer upgrades. Thanks for the help.
