### ISSUE TITLE
google_pubsub_subscription no_wrapper is not supported

### ISSUE THREAD

**Issue by gulpinDev** [hashicorp/terraform-provider-google#17125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.7.1-dev
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.0.0
+ provider registry.terraform.io/hashicorp/google-beta v5.13.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* google_pubsub_subscription

### Terraform Configuration Files

```tf
resource "google_pubsub_subscription" "subscriptions" {
  for_each   = var.topics_subs_jobs
  name       = each.value.subscription
  topic      = each.value.topic

  dead_letter_policy {
    dead_letter_topic     = var.deadletter_queue_topic
    max_delivery_attempts = var.max_delivery_attempts
  }

  retry_policy {
    minimum_backoff = var.min_backoff
    maximum_backoff = var.max_backoff
  }

  push_config {
    push_endpoint = var.push_endpoint
    oidc_token {
      service_account_email = var.service_account_email
    }
    no_wrapper = {
      write_metadata = true
    }
  }
}
```

### Expected Behavior

The no_wrapper argument should be valid. I've tried with and without an equal (=)

### Actual Behavior

│ Error: Unsupported argument
│
│   on ../../modules/pubsub/subscriptions/main.tf line 23, in resource "google_pubsub_subscription" "subscriptions":
│   23:     no_wrapper = {
│
│ An argument named "no_wrapper" is not expected here.

│ Error: Unsupported block type
│
│   on ../../modules/pubsub/subscriptions/main.tf line 23, in resource "google_pubsub_subscription" "subscriptions":
│   23:     no_wrapper {
│
│ Blocks of type "no_wrapper" are not expected here.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@gulpinDev what do you see if you try below config?

```tf
resource "google_pubsub_subscription" "foo" {
  name                 = "mysubscription"
  topic                = google_pubsub_topic.foo.name
  ack_deadline_seconds = 10
  push_config {
    push_endpoint = "https://${data.google_project.project.project_id}.appspot.com"
    oidc_token {
      service_account_email = google_service_account.pub_sub_service_account.email
    }
    no_wrapper {
      write_metadata = true
    }
  }
}
```

**Comment by gulpinDev** [comment]
Same error:
![no_wrapper](https://github.com/hashicorp/terraform-provider-google/assets/74437204/5a456f5e-89ca-412c-9a44-de6b48791e3f)

**Comment by edwardmedia** [comment]
@gulpinDev Is v4.0.0 is version you are using? Can you try the latest version instead?

```
provider registry.terraform.io/hashicorp/google v4.0.0
```

**Comment by gulpinDev** [comment]
it was the version! i've updated it to 5.3.0 and now the field is recognised and the change is applied. thank you for helping :)
