### ISSUE TITLE
resource "google_project_service" "project"

### ISSUE THREAD

**Issue by JeremyPDC** [hashicorp/terraform-provider-google#17131]
I have looked for issues regarding this with no luck. I am fairly confident there is a bug here, but am wondering if it is already documented.

When adding the following resource.

resource "google_project_service" "project"

Then adding a dependent resource like the following

resource "google_recaptcha_enterprise_key" "primary"

The code will never run in one shot. I have tried adding a dependent "resource "time_sleep"" in between the two resources and no matter how long I make the wait it does not work.

If I rerun the TF again right after it works perfectly.

During the wait if I check the state of GCP using gcloud CLI everything appears to be set as you would expect. Its like TF needs a state refresh and is not getting it or something.

Any help would be greatly appreciated.

TIA

**Comment by edwardmedia** [comment]
@JeremyPDC can you provide the config and steps that I can follow to repro the issue?

**Comment by edwardmedia** [comment]
@JeremyPDC is this still an issue?
