### ISSUE TITLE
Enhancement: Allow for `region` arg to be inferred from environment variables for `google_compute_region_ssl_policy` 

### ISSUE THREAD

**Issue by kalenarndt** [hashicorp/terraform-provider-google#17142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, we are trying to reduce the amount of references to a google region where possible within our modules that we developing. We have been able to do this in most areas however, the `google_compute_region_ssl_policy` requires the `region` argument to be specified regardless if it is set via environment variables. 

This is currently what is happening 

```bash
└─ χ export GOOGLE_REGION=us-central1                                                                                 
└─ ❯ tfp
╷
│ Error: Missing required argument
│ 
│   on ../modules/regional/main.tf line 76, in resource "google_compute_region_ssl_policy" "region":
│   76: resource "google_compute_region_ssl_policy" "region" {
│ 
│ The argument "region" is required, but no definition was found.
╵
└─ χ printenv | grep -i google_region
GOOGLE_REGION=us-central1
```

If `region` is specified via an input it works fine.

### New or Affected Resource(s)

* google_compute_region_ssl_policy (There isn't a data source)

### Potential Terraform Configuration

```tf
resource "google_compute_region_ssl_policy" "region" {
  name            = "${var.friendly_name_prefix}-${var.product}-${lower(local.lb_type)}-regional-ssl-pol"
  description     = "The SSL policy of the public load balancer for ${var.product}."
  min_tls_version = "TLS_1_2"
  profile         = "RESTRICTED"
}
```

### References

* None that I could find

b/324044484

**Comment by SarahFrench** [comment]
Notes from triage: The cause of this issue appears to be due to [a resource ref being used for `region` on this resource](https://github.com/GoogleCloudPlatform/magic-modules/blob/69eb36c616c5bc4f1cdf729abfde8886ed5b381d/mmv1/products/compute/RegionSslPolicy.yaml#L51-L60).

Also, potentially, the custom expander might be affecting the field. Needs to be investigated but this is a bug
