### ISSUE TITLE
Creating a Vertex search APP and Website datastore

### ISSUE THREAD

**Issue by bademiya5306** [hashicorp/terraform-provider-google#17147]
Hi

1. Is there any resource to create vertext AI search Apps and link datastore to them

2. I am using the newly released resource "google_discovery_engine_data_store" to create a website datastore. How can i provide options to crawl my website urls?

Thanks

**Comment by edwardmedia** [comment]
@bademiya5306 all available `vertax ai` resources are listed  as `google_vertex_ai_****`. I don't think app searches are supported by now. You may request by filing [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) if you know they are supported by the api.
