### ISSUE TITLE
encountering issue with replication automatic

### ISSUE THREAD

**Issue by LavanyaVijayakumar** [hashicorp/terraform-provider-google#17158]
If you have a support request or question please submit them to one of these resources:
<img width="761" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/105811367/a01fda30-0386-4e8d-a929-0ec3840baf93">
https://github.com/pretamanger/cloud-infrastructure/actions/runs/7742154254/job/21110622482#step:10:454
* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by LavanyaVijayakumar** [comment]
resource "google_secret_manager_secret" "digital_platform_service_account_password" {
  secret_id = "DIGITAL_PLATFORM_SERVICE_ACCOUNT_PASSWORD"
  replication {}
  project = var.project_id
}

**Comment by edwardmedia** [comment]
@LavanyaVijayakumar there are a few of examples [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret). Do they work for you?

**Comment by LavanyaVijayakumar** [comment]
thank you.
