### ISSUE TITLE
Add post_startup_script support for google_workbench_instance resource

### ISSUE THREAD

**Issue by markustoivonen** [hashicorp/terraform-provider-google#17151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

According to the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workbench_instance), the `google_workbench_instance` resource is currently missing the `post_startup_script` field, which is supported in the [`google_notebooks_instance`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#post_startup_script) resource. The feature is supported when trying to create a Workbench instance through Cloud Console, just isn't supported through Terraform yet. 

### New or Affected Resource(s)

`google_workbench_instance`

### Potential Terraform Configuration

```tf
resource "google_workbench_instance" "instance" {
  name = "workbench-instance"
  location = "us-west1-a"
  post_startup_script = "gs://#PATH#/#TO#/#MY#/#SCRIPT
}
```

### References

N/A

b/323501385

**Comment by mahvar** [comment]
how about `install_gpu_driver`? It used to exist in `google_notebooks_instance`. How's that done in `google_workbench_instance`?

**Comment by bcreddy-gcp** [comment]
It is handled by default. An image with GPUs have GPU drivers installed by default.
