### ISSUE TITLE
add BackupConfig block in google_netapp_volume

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#17152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_netapp_volume

### Potential Terraform Configuration

```tf
resource google_netapp_volume myvolume {
  backup_config {
    backup_policies = []
    backup_vault = ""
    scheduled_backup_enabled = true
  }
}

```

### References

* https://cloud.google.com/netapp/volumes/docs/reference/rest/v1/projects.locations.volumes#backupconfig

b/323501940

**Comment by larizzo** [comment]
Do we know if this will be scheduled/prioritized? It seems critical to me to be able to allocated volumes to backup policies.

**Comment by roop2** [comment]
Hi,
I am working on it.
My PR has been merged to magic modules repo https://github.com/GoogleCloudPlatform/magic-modules/pull/10822 
This is the step we follow for releasing support to provider repo.
Hopefully in the next release of it will be available in the provider.
I will update this issue once it is released.

**Comment by roop2** [comment]
This is available in the recent TF provider release 
https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.33.0
