### ISSUE TITLE
Does google_firestore_field support wildcard (*) for field?

### ISSUE THREAD

**Issue by galenwarren** [hashicorp/terraform-provider-google#17163]
According to the firestore [docs](https://firebase.google.com/docs/firestore/query-data/index-overview#single-field_indexes), the "*" field value can be used to add collection-level index exemptions for an entire collection group. For example, this could be used to disable indexing for all fields by default.

However, this doesn't seem to work with the google_firestore_field resource; any attempt to set anything with field="*" results in

```
 Error: Error creating Field: googleapi: Error 400: Updating ttl other than single field level is not supported: UpdateFieldConfigurationRequest{ref=SingleFieldRef{referenceType=ReferenceType{kind=AuthorizationTimeTokens}}, indexingMode=IndexingMode{enable=[]}, expirationMode=ENABLE, validateOnly=false} 
```

Is this intended to work, or is there another way to disable all field indexes for a collection group (besides doing them individually, which  won't work for all collection group because of the limited number of field exemptions allowed)? Thanks.

**Comment by edwardmedia** [comment]
@galenwarren The error is from the api, that leads me to think it is possible not supported at the api. Are you able to use it with other tools like gcloud?

**Comment by galenwarren** [comment]
I don't see support in gcloud for setting these exemptions, it looks to me (based on some other comments in GitHub around this feature) that the REST API is used, specifically [PATCH](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.collectionGroups.fields/patch) to this resource. These docs do indicate support for the * field:

> A field path may be a simple field name, e.g. address or a path to fields within mapValue , e.g. address.city, or a special field path. The only valid special field is *, which represents any field.

You can also add an exemption for the * field through the GCP console, which presumably also uses the REST API.

From the trace output when it fails, I see that the request body being sent to the REST API is this:

> 2024-02-02T11:15:45.837-0500 [DEBUG] provider.terraform-provider-google_v4.84.0_x5: 2024/02/02 11:15:45 [DEBUG] Creating new Field: map[string]interface {}{"indexConfig":map[string]interface {}{}, "ttlConfig":interface {}(nil)} 

My best guess is that, in this case, we want the ttlConfig to be absent from the map, as opposed to being present with a nil value.

I can try to debug a bit more locally; if it turns out this is what is going on, would you be open to a PR to fix this behavior?

**Comment by edwardmedia** [comment]
See the doc [here](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.collectionGroups.fields) too. Forward the service team to better explanation

**Comment by galenwarren** [comment]
@edwardmedia  I've been trying a few options against the REST interface but nothing seems to work to set the * field. The documentation text that suggests setting field * might work appears to be copied verbatim from other non-REST APIs and so I think you may be right, this just isn't supported through the REST API.

**Comment by galenwarren** [comment]
In case anyone stumbles upon this, the only way I've found to automatically apply a field=* index is via the firestore [CLI](https://firebase.google.com/docs/firestore/query-data/indexing#use_the_firebase_cli). That seems to work fine.
