### ISSUE TITLE
google_cloudfunctions2_function TF changes at every plan

### ISSUE THREAD

**Issue by padoffe** [hashicorp/terraform-provider-google#17161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.5.7

### Affected Resource(s)

google_cloudfunctions2_function

### Terraform Configuration

```terraform
resource "google_cloudfunctions2_function" "this" {
  name        = "my-awesome-function"
  location    = "europe-west1"
  description = "My awesome description"

  build_config {
    runtime     = python39
    entry_point = "main"
    source {
      storage_source {
        bucket = "my-awesome-bucket"
        object = "my-awesome-function.zip"
      }
    }
  }

  service_config {
    max_instance_count            = 30
    min_instance_count            = 0
    available_memory              = 256Mi
    ingress_settings              = "ALLOW_INTERNAL_ONLY"
  }

 "event_trigger" {
    content {
      event_type            = "google.cloud.pubsub.topic.v1.messagePublished"
      pubsub_topic          = "projects/**************/topics/my-awesome-topic"
      retry_policy          = ""RETRY_POLICY_DO_NOT_RETRY""
  }
}
```

### Expected Behavior

The `google_cloudfunctions2_function` should be fully idempotent. 
Using the resource after the first apply should return the: `No changes. Your infrastructure matches the configuration.` message

### Actual Behavior

When not specifying these **optional** properties: **build_config.docker_repository** and **event_trigger.trigger_region**, terraform wants to change their values in this way: 

```
      ~ build_config {
          - docker_repository     = "projects/**************/locations/europe-west1/repositories/gcf-artifacts" -> null
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

      ~ event_trigger {
          - trigger_region        = "europe-west1" -> null
            # (5 unchanged attributes hidden)
        }
```

It might be the case for other properties that I have not discovered yet. 

### Steps to reproduce

Create a `google_cloudfunctions2_function` without specifying  the given properties

1. `terraform apply` once
2. `terraform plan` as much as you want after that

b/323501206

**Comment by oscar-b** [comment]
https://github.com/hashicorp/terraform-provider-google/pull/17072

**Comment by padoffe** [comment]
> #17072

Hi, this indeed fixed the permadiff issue on the `docker_repository` property. Thank you for that. 

However, event_trigger.trigger_region still suffers from the same issue: 

``` 
  ~ resource "google_cloudfunctions2_function" "this" {
        id               = "projects/**************/locations/europe-west1/functions/my-awesome-function"
        name             = "my-awesome-function"
        # (10 unchanged attributes hidden)

      ~ event_trigger {
          - trigger_region        = "europe-west1" -> null
            # (5 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }
```
