### ISSUE TITLE
`google_kms_crypto_key` is destroyed when adding `destroy_scheduled_duration` field

### ISSUE THREAD

**Issue by Kaawin1** [hashicorp/terraform-provider-google#17175]
Hello !

I'm using the version 2.3.0 of the terraform [terraform-google-kms](https://github.com/terraform-google-modules/terraform-google-kms/releases/tag/v2.3.0) module.
This version adds the supports of the `destroy_scheduled_duration attributes`.
When adding the field  and plan, I get the following error 
```
│ Error: Instance cannot be destroyed
│ 
│   on main.tf line 27:
│   27: resource "google_kms_crypto_key" "key" {
│ 
```
which is normal since the `google_kms_crypto_key` resource cannot be destroyed ([terraform module](https://github.com/terraform-google-modules/terraform-google-kms/blob/master/main.tf#L35))
I checked the code of the resource `google_kms_crypto_key` and I see that the field `ForceNew` is True.
From what I understand this means if this fiels is added or changed as I did, the resource is destroyed then recreated.
So my questions are:
- Is my understanding correct ?
- If so, why the field ForceNew is True  ? I dont see any reasons for this.

Best regards

**Comment by edwardmedia** [comment]
@Kaawin1 Your understanding is correct, because the api does not support update on that specific field. Does that make sense?

**Comment by Kaawin1** [comment]
Yes It makes sense.
Thank a lot for answering !
