### ISSUE TITLE
google_bigquery_dataset_iam_member erroring out with 'Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by mbohri-cslt** [hashicorp/terraform-provider-google#17172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.0.6

### Affected Resource(s)

google_bigquery_dataset_iam_member

### Terraform Configuration

```tf
```

### Debug Output

Step #4 - "tf apply": │ Error: Provider produced inconsistent result after apply
Step #4 - "tf apply": │ 
Step #4 - "tf apply": │ When applying changes to
Step #4 - "tf apply": │ google_bigquery_dataset_iam_member.reference_tic_editor, provider
Step #4 - "tf apply": │ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
Step #4 - "tf apply": │ unexpected new value: Root resource was present, but now absent.
Step #4 - "tf apply": │ 
Step #4 - "tf apply": │ This is a bug in the provider, which should be reported in the provider's
Step #4 - "tf apply": │ own issue tracker.

### Expected Behavior

TF apply should pass and resources should be created 

### Actual Behavior

Randomly terraform destroys the **google_bigquery_dataset_iam_member** resource and recreates ( without the resource being updated). The following error is being logged

```
google_bigquery_dataset_iam_member.resoursename, provider
"provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
```
 
TF Apply fails with error during this process and TF state gets updated incorrectly and causes errors when the TF apply is executed next time.

Sample error seen during the subsequent TF apply 

```
Error: Error creating Dataset: googleapi: Error 409: Already Exists: Dataset datasetname, duplicate
 with google_bigquery_dataset.datasetname,
 on main.tf line 803, in resource "google_bigquery_dataset" "datasetname":
 803: resource "google_bigquery_dataset" "datasetname" {
```

please note: the **google_bigquery_dataset_iam_member** resource name that errors in teh first run is not associated with the dataset that has duplicate error.

### Steps to reproduce

The following resources are available under the same Terraform project.
- google_bigquery_dataset_iam_member .
- google_bigquery_dataset .

Run Terraform apply multiple times 

b/325436168

**Comment by edwardmedia** [comment]
@mbohri-cslt thanks for reporting this issue but the provided info is not enough for me to investigate. Below info is a little bit vague and likely it is related to a way to build the system. 

Can you repro the issue? Are you able to put all in a simple config that I can repro? What version of provider do you use?


```
Error: Provider produced inconsistent result after apply
```

**Comment by edwardmedia** [comment]
@mbohri-cslt is this still an issue?

**Comment by edwardmedia** [comment]
closing this as a dup of #16607

**Comment by c2thorn** [comment]
Reopenning, this seems like a separate issue that I'm also seeing in https://github.com/GoogleCloudPlatform/magic-modules/pull/9948

**Comment by wj-chen** [comment]
@c2thorn Looks like the test issue in https://github.com/GoogleCloudPlatform/magic-modules/pull/9948 was resolved. Since we don't have additional information from the reporter on whether this is still happening or examples to repro, is it good to be closed for now?

**Comment by c2thorn** [comment]
Yes @wj-chen, either this user's case is not still happening or it will be fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/9948
