### ISSUE TITLE
google_iap_brand - Error 400: Support email is not allowed

### ISSUE THREAD

**Issue by raweber42** [hashicorp/terraform-provider-google#17199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.7.0

### Affected Resource(s)

google_iap_brand

### Terraform Configuration

```
resource "google_project_service" "project_service" {
  project = var.project_id
  service = "iap.googleapis.com"
}

resource "google_iap_brand" "project_brand" {
  support_email     = "suppliers@XXX.XX"
  application_title = "XXXX-staging-internal"
  project           = var.project_id
}

resource "google_iap_client" "new_client" {
  display_name = "Client Client"
  brand        =  google_iap_brand.project_brand.name
}

data "google_iam_policy" "iap_policy" {
  binding {
    role = "roles/iap.httpsResourceAccessor"
    members = [
      "group:group.XXXX.all@XXX.XX",
    ]
  }
}

resource "google_iap_web_iam_policy" "policy" {
  project = var.project_id
  policy_data = data.google_iam_policy.iap_policy.policy_data
}


resource "google_secret_manager_secret" "iap-oauth-client-id" {
  secret_id = "iap-oauth-client-id"
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "XXXX-iap-oauth-client-id-version" {
  secret = google_secret_manager_secret.iap-oauth-client-id.id
  secret_data = google_iap_client.XXXX_client.client_id
}

resource "google_secret_manager_secret" "iap-oauth-client-secret" {
  secret_id = "iap-oauth-client-secret"
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "XXXX-iap-oauth-client-secret-version" {
  secret = google_secret_manager_secret.iap-oauth-client-secret.id
  secret_data = google_iap_client.XXXX_client.secret
}

```

### Expected Behavior

The new brand is successfully created.

### Actual Behavior

```
╷
│ Error: Error creating Brand: googleapi: Error 400: Support email is not allowed: suppliers@XXX.XX
│   with google_iap_brand.project_brand,
│   on iap.tf line 6, in resource "google_iap_brand" "project_brand":
│    6: resource "google_iap_brand" "project_brand" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

### Steps to reproduce

1. `terraform apply`

### Important Factoids

I did deploy this terraform configuration on our DEV environment, there it works fine. The only difference is that I manually toggled IAP on our DEV environment first for testing purposes, then disabled it again and enabled it via terraform afterwards. I have the suspicion that the manual toggling somehow made the support_email work without me realising it.

I have a couple of questions:
- Does the support_email have to be unique (globally/across different projects)? Or can I use the same email for all environments (seems to not be the case as my `apply` is failing with the above error when I do that.
- Does the terraform service account have to be the owner of the email address (see [here](https://github.com/hashicorp/terraform-provider-google/issues/6104))? On my DEV environment this is NOT the case and still IAP works
- What exactly are the rules for a support_email not being allowed?

Thanks a lot in advance!

### References

https://github.com/hashicorp/terraform-provider-google/issues/6104

**Comment by edwardmedia** [comment]
@raweber42 import helped solve your other [issue](https://github.com/hashicorp/terraform-provider-google/issues/17094).

For this issue, you have identified #6104. Beyond [that](https://github.com/hashicorp/terraform-provider-google/issues/6104#issuecomment-613620591), I don't know extra words to your questions. The rule is set by the api ( you may see it is googleapi error), and there is not much that we can do at the provider level. Does this make sense?

**Comment by raweber42** [comment]
Thanks for the fast response @edwardmedia. 

First: Import would probably help, but we are also planning for disaster recovery cases (or setting up a new environment). I think I missed to specify: I am setting up a new environment right now. So I assumed, that with no configurations present about IAP whatsoever on that environment, I could just use the same configuration as on our DEV environment. Of course I could manually activate IAP and than import the configuration. But this is not a feasible approach for a disaster recovery. Obviously the idea is to run `terraform apply` once and everything is set up (without me having to `import` some configuration).

Regarding the idea

> Generally terraform runs as a service account, so the easiest way to have the service account own the support_email address would be to have the service account be an owner of a Google Group.

I am wondering, why it's working on our DEV environment, _without_ the service account being the owner of the Google Group to which the `support_email` belongs?

**Comment by edwardmedia** [comment]
@raweber42 in general, the terraform config should be repeatable. The environments like DEV, QA, etc. are just virtual, there should be no difference between envs from the Terraform perspective. BUT there could be huge difference between them depending upon how each environment is setup. You might want to compare IAMs, networks, etc. between them.

In your case, I do not think of a reason why it works in one env but not others if EVERYTHING else is the same.

**Comment by edwardmedia** [comment]
@raweber42 is this still an issue?

**Comment by raweber42** [comment]
We couldn't make it work with the `support_email`, so we now manually create the brands for the environments. We _did_ set the terraform account as the owner of the support_email google group, but it simply didn't work 😅. I wouldn't say this is resolved, but we found a workaround.

**Comment by edwardmedia** [comment]
Sorry about that. As I said, the rule is set by the api. Closing this now

```
googleapi: Error 400: Support email is not allowed: suppliers@XXX.XX
```
