### ISSUE TITLE
Remove custom logic around service labels for PRs and issues

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17192]
Currently, the [diff-processor](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/tools/diff-processor) uses [`labeler.UpdateIssues`](https://github.com/GoogleCloudPlatform/magic-modules/blob/7088e2486d94f074cb54b23d6921c58cdaf668a8/tools/issue-labeler/labeler/backfill.go#L129) to interact with the GitHub API and apply labels. We should instead be using [go-github](https://github.com/google/go-github) to interact with the API.

In particular, the diff processor currently has an `add-labels` CLI command which should be altered to return a list of labels to add. The code that _calls_ that command should take the necessary actions to _apply_ the labels using go-github. This will have better separation of concerns.

Additional details at b/316174075.

**Comment by NA2047** [comment]
@melinath
