### ISSUE TITLE
google_identity_platform_config - endpoint not found

### ISSUE THREAD

**Issue by Boardtale** [hashicorp/terraform-provider-google#17230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.6.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v5.15.0
+ provider registry.terraform.io/hashicorp/http v3.4.1

### Affected Resource(s)

google_identity_platform_config

### Terraform Configuration

```tf
data "google_project" "project" {}

resource "google_project_service" "identitytoolkit" {
  project = data.google_project.project.id
  service = "identitytoolkit.googleapis.com"
}

resource "google_identity_platform_config" "default" {
  project = data.google_project.project.id
  sign_in {
    allow_duplicate_emails = false

    email {
      enabled = true
      password_required = false
    }
  }
  authorized_domains = [
    "mydomain.com"
  ]
  quota {
    sign_up_quota_config {
      quota = 100
      start_time = ""
      quota_duration = "7200s"
    }
  }
}

```

### Expected Behavior

It creates specific configuration for identity platform

### Actual Behavior

│   <p>The requested URL <code>/v2/projects/projects/XXX/identityPlatform:initializeAuth?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>

### Steps to reproduce

1. `terraform apply`

### Important Factoids

I have a billing enabled and I manually enabled identity platform as I think it can't - it's in marketplace, not API after all

**Comment by edwardmedia** [comment]
@Boardtale what do you see if you change from `id` to `name` in below line?

```tf
resource "google_identity_platform_config" "default" {
  project = data.google_project.project.id   <---- data.google_project.project.name
  sign_in {
    allow_duplicate_emails = false

    email {
      enabled = true
      password_required = false
    }
  }
  authorized_domains = [
    "mydomain.com"
  ]
  quota {
    sign_up_quota_config {
      quota = 100
      start_time = ""
      quota_duration = "7200s"
    }
  }
}
```

**Comment by Boardtale** [comment]
Oh, I think it actually worked this way. But I get 
│ Error: Error creating Config: googleapi: Error 400: INVALID_PROJECT_ID : Identity Platform has already been enabled for this project.

Thou I saw this problem somewhere around, will try to find a solution :) 

Thanks a bunch!

**Comment by edwardmedia** [comment]
@Boardtale the issue is about what you provide for the `project` field. In this case, it expects the portion of XXX of below part. 

```
projects/XXX
```

Please share your debug log if you want me to take a closer look.

**Comment by Boardtale** [comment]
We can close it :) Thanks @edwardmedia !
I was able to fix it via 'import'.
But I had to anyway stop using terraform for identity platform, I need also Google, FB and Twitter along with Github providers which are currently not supported via Terraform (dont know about API).

But yeah, managed to make it working, thanks for all the help!
