### ISSUE TITLE
google_compute_instance_template: adding resource_manager_tags to existing template does nothing on apply

### ISSUE THREAD

**Issue by enordberg** [hashicorp/terraform-provider-google#17239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.6.3
+ provider registry.terraform.io/hashicorp/google v5.15.0
+ provider registry.terraform.io/hashicorp/google-beta v5.15.0
+ provider registry.terraform.io/hashicorp/vault v3.24.0

### Affected Resource(s)

google_compute_instance_template

### Terraform Configuration

Old TF:
```tf
resource "google_project_iam_member" "instance_admin" {
  project = var.project_id
  role    = "roles/compute.instanceAdmin.v1"
  member  = "serviceAccount:852634163304@cloudservices.gserviceaccount.com"
}

resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_tags_tag_key" "test_key" {
  description = "Test tag"
  parent      = "projects/${var.project_id}"
  purpose     = "GCE_FIREWALL"
  short_name  = "test_eric"
  purpose_data = {
    network = "${var.project_id}/default"
  }
}

resource "google_tags_tag_value" "test_value" {
  description = "Truth"
  parent      = "tagKeys/${google_tags_tag_key.test_key.name}"
  short_name  = "true"
}

resource "google_compute_instance_template" "test_instance_v4" {
  name_prefix    = "test-instance-v4"
  region         = "us-central1"
  description    = "Test instance template v4 two"
  machine_type   = "e2-micro"
  can_ip_forward = false

  tags = ["test-vm"]

  network_interface {
    network = "default2"
  }

  disk {
    source_image = "debian-cloud/debian-11"
    auto_delete  = true
    boot         = true
  }

  metadata = {
    foo = "bar"
  }

  service_account {
    email  = google_service_account.default.email
    scopes = ["cloud-platform"]
  }

  lifecycle {
    create_before_destroy = true
  }
}


resource "google_compute_region_instance_group_manager" "test_ces_v4" {
  name = "test-ces-v4"

  base_instance_name        = "test-ces-v4-us-central1"
  region                    = "us-central1"
  distribution_policy_zones = ["us-central1-a", "us-central1-b"]
  target_size               = 2

  version {
    instance_template = google_compute_instance_template.test_instance_v4.id
  }

  named_port {
    name = "custom"
    port = 8888
  }

  update_policy {
    type                         = "OPPORTUNISTIC"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REFRESH"
    max_surge_fixed              = 2
    max_unavailable_fixed        = 2
    replacement_method           = "SUBSTITUTE"
  }
}
```

Updated TF - note the added resource_manager_tags parameter in google_compute_instance_template:
```tf
resource "google_project_iam_member" "instance_admin" {
  project = var.project_id
  role    = "roles/compute.instanceAdmin.v1"
  member  = "serviceAccount:852634163304@cloudservices.gserviceaccount.com"
}

resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_tags_tag_key" "test_key" {
  description = "Test tag"
  parent      = "projects/${var.project_id}"
  purpose     = "GCE_FIREWALL"
  short_name  = "test_eric"
  purpose_data = {
    network = "${var.project_id}/default"
  }
}

resource "google_tags_tag_value" "test_value" {
  description = "Truth"
  parent      = "tagKeys/${google_tags_tag_key.test_key.name}"
  short_name  = "true"
}

resource "google_compute_instance_template" "test_instance_v4" {
  name_prefix    = "test-instance-v4"
  region         = "us-central1"
  description    = "Test instance template v4 two"
  machine_type   = "e2-micro"
  can_ip_forward = false

  tags = ["test-vm"]

  resource_manager_tags = {
    "${google_tags_tag_key.test_key.id}" = "${google_tags_tag_value.test_value.id}"
  }

  network_interface {
    network = "default2"
  }

  disk {
    source_image = "debian-cloud/debian-11"
    auto_delete  = true
    boot         = true
  }

  metadata = {
    foo = "bar"
  }

  service_account {
    email  = google_service_account.default.email
    scopes = ["cloud-platform"]
  }

  lifecycle {
    create_before_destroy = true
  }
}


resource "google_compute_region_instance_group_manager" "test_ces_v4" {
  name = "test-ces-v4"

  base_instance_name        = "test-ces-v4-us-central1"
  region                    = "us-central1"
  distribution_policy_zones = ["us-central1-a", "us-central1-b"]
  target_size               = 2

  version {
    instance_template = google_compute_instance_template.test_instance_v4.id
  }

  named_port {
    name = "custom"
    port = 8888
  }

  update_policy {
    type                         = "OPPORTUNISTIC"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REFRESH"
    max_surge_fixed              = 2
    max_unavailable_fixed        = 2
    replacement_method           = "SUBSTITUTE"
  }
}
```

### Debug Output

NA

### Expected Behavior

The google_compute_instance_template should be immutable.  When the resource_manager_tags are added, the plan should reflect a Force Replacement of the google_compute_instance_template object.  Then, the apply should do the Force replacement, creating a new version of the instance template.

### Actual Behavior

When adding resource_manager_tags to an existing google_compute_instance_template that does not have them already, the Plan shows that it will update the instance template in place.  Then, the apply seems to do nothing.  It looks like it successfully applies, but the instance template is NOT updated with the added tags.

### Steps to reproduce

1. Start with an existing google_compute_instance_template that does NOT contain resource_manager_tags
2. Add resource_manager_tags to that google_compute_instance_template
3. `terraform apply`

### Important Factoids

NA

b/324765597

**Comment by edwardmedia** [comment]
There are two `resource_manager_tags` in the `google_compute_instance_template` and `google_compute_region_instance_template`  

While forceNew is correctly set on `{root}.disk.resource_manager_tags'. It is wrong on `{root}.resource_manager_tags`
