### ISSUE TITLE
metadata_startup_script on google_compute_instance not running at all

### ISSUE THREAD

**Issue by GTGabaaron** [hashicorp/terraform-provider-google#17251]
### Community Note

I have a Terraform code that is running perfectly fine on my local computer, the issue happens ONLY when I run it from an Azure Pipeline.

My TF code creates several GCP VM Instances using google_compute_instance, each instace use the metadata and metadata_startup_script to upload the public key and run an initial-script respectively, but for some reason the metadata_startup_script is NOT running when TF is executed from an Azure Pipine, everything else runs fine.

Weird thing is TF Plan stage recognizes the initial-script content (vars and values as well) and mention it will be apply, but at the end is being skip during the actual TF Apply phase. I have tried to using it on different ways (as in the code below) but none of the options is executed.

```
Creating the data template resource ----->
    data "template_file" "admin" {
      template = file("initial-setup.sh")
      vars = {
        password = "${random_password.admin_password.result}"
        prefix = "${var.prefix}"
      }
    }

Different calling options inside google_compute_instance I've tried --->
    metadata_startup_script = "${data.template_file.admin.rendered}"
    metadata_startup_script = file("initial-setup.sh")
    metadata_startup_script = "useradd -m -s /bin/bash 'admin';echo 'admin:password@54w21@123@@' | chpasswd"
```

None of the options above run when TF is launch from an Azure Pipeline, but on my local computer the three of them run smoothly. It is possible to force this? or could be an issue with the agent pool missing requirement is missing ?

### Terraform Version

Terraform v1.7.3 on windows_amd64 (azure agent pool)
Terraform v1.3.0 on windows_amd64 (local computer)

### Affected Resource(s)

metadata_startup_script on google_compute_instance

### Terraform Configuration

```tf
```

### Expected Behavior

metadata_startup_script should run a initial scripts on each instance that creates an additional user, change its password and setup ssh keys.

### Actual Behavior

metadata_startup_script is being skipped, not running at all.

### Steps to reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@GTGabaaron two different issues 

1.  are you able to set the **metadata_startup_script** via terraform configuration? If no, are you able to set it up via glcoud?
2.  If it is successfully set up, but the script do nothing (like you said in the subject). Have you checked the script if it should run? Can you verify it via glcoud?
  
It is not clear to me which problem you are facing. If you want us to take a look, can you share a minimum config that I can repro?

**Comment by GTGabaaron** [comment]
Hi @edwardmedia, I'm new to GCP and never used gcloud, can you please elaborate on point 1.
1.- The metadata_startup_script is setup inside each google_compute_instance on the main.tf module.
2.-  As I mentioned on the details the initial-script.sh runs fine when I executed on my local computer, but not from the pipeline. Also, the script runs fine If I manually run it inside any instance after de deploy is completed.

Here is the initial-script.sh content, really simple as you can read --->
#!/bin/bash

prefix=$1
password=$2

# Updating the root user password and config setup
echo "root:$password" | chpasswd
sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i -e 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i -e 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config

# Creating the admin user and assigning its password
useradd -m -s /bin/bash "admin"
echo "admin:$password" | chpasswd
cd /tmp/
touch admin.txt
echo "admin username and password successfully created" >> admin.txt

# Updating the /etc/hosts files to contai the aliases for each VM
cat - >/etc/hosts <<EOF
127.0.0.1   localhost
10.0.5.20   $prefix-admin ad
10.0.5.22   $prefix-apache ap
10.0.5.24   $prefix-wwww web
10.0.5.26  $prefix-mysql sql
EOF

**Comment by edwardmedia** [comment]
@edwardmedia Here is an [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage) which has `metadata_startup_script`. Do you see if it works?

**Comment by edwardmedia** [comment]
@GTGabaaron sorry I do not know `the azure agent pool`. I can help if you encounter a problem running a config like the example.

**Comment by GTGabaaron** [comment]
Hi @edwardmedia I've got new information, yesterday I forgot to check the custom metadata section of each VM Instance on the portal, I was assuming the script was not being read in the TF Apply but in fact it is, I can the see content of the script on the custom metadata section with the corresponding values for each parameter/variable, is it possible to check/find on the GCP logs anything related to this ?
