### ISSUE TITLE
Error on creating Cloud SQL Instance (MySQL) when there is a password policy

### ISSUE THREAD

**Issue by jlam-bills** [hashicorp/terraform-provider-google#17265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

We are on Terraform cloud:

Terraform version: 1.4.5
Provider version: 5.16.0.

I also tested with previous versions, down to 5.8.0.

![image](https://github.com/hashicorp/terraform-provider-google/assets/29388835/7bfec73c-5b59-416a-a8fe-1b1d32baf351)

### Affected Resource(s)

`google_sql_database_instance`

### Terraform Configuration

```


resource "google_sql_database_instance" "master" {
  project             = google_project_service.sqladmin["project"].project
  name                = var.name
  database_version    = var.database_version
  deletion_protection = var.deletion_protection

  settings {
    tier              = var.machine_type
    activation_policy = "ALWAYS"
    disk_autoresize   = true
    disk_type         = var.disk_type
    pricing_plan      = "PER_USE"
    availability_type = var.availability_type

    user_labels = merge({
      bu  = coalesce(var.context.bu.key, "none")
      app = coalesce(var.context.app.key, "none")
      svc = coalesce(var.context.svc.key, "none")
      env = coalesce(var.context.env.key, "none")
    }, var.user_labels)

    backup_configuration {
      enabled                        = true
      binary_log_enabled             = local.type_settings[local.type].binary_log_enabled
      start_time                     = var.backup_start_time
      point_in_time_recovery_enabled = contains(split("_", var.database_version), "MYSQL") ? null : var.point_in_time_recovery_enabled
    }

    ip_configuration {
      ipv4_enabled    = var.ipv4_enabled
      private_network = var.private_network
      require_ssl     = local.type_settings[local.type].require_ssl

      dynamic "authorized_networks" {
        for_each = flatten([
          for key, values in var.authorized_networks :
          [
            for value in values :
            {
              name  = key
              value = value
            }
          ]
          if values != null
        ])
        content {
          name            = authorized_networks.value.name
          value           = authorized_networks.value.value
          expiration_time = null # Never expire
        }
      }
    }

    dynamic "location_preference" {
      for_each = compact([var.preferred_zone])
      content {
        follow_gae_application = null # Never follow GAE applications
        zone                   = location_preference.value
      }
    }

    dynamic "maintenance_window" {
      for_each = [for value in [var.maintenance_window] : value if value != null]
      content {
        day          = maintenance_window.value.day
        hour         = maintenance_window.value.hour
        update_track = maintenance_window.value.update_track
      }
    }

    dynamic "insights_config" {
      for_each = [for value in [var.insights_enabled] : value if value != null]
      content {
        query_insights_enabled  = insights_config.value
        query_string_length     = var.insights_query_string_length
        record_application_tags = var.insights_record_application_tags
        record_client_address   = var.insights_record_client_address
      }
    }

    password_validation_policy {
      enable_password_policy      = var.password_policy_enabled
      min_length                  = local.password_policy.min_length
      complexity                  = local.password_policy.complexity
      reuse_interval              = local.password_policy.reuse_interval
      disallow_username_substring = local.password_policy.disallow_username_substring
    }
  }
}
```

### Expected Behavior

The instance should be created.

### Actual Behavior

Error: Error, failed to create instance jaredtest-dev-8fb08547: googleapi: Error 400: Invalid request: Root user's password is not policy compliant: Length of password cannot be less than 14. Password does not meet the complexity criteria. ., invalid
with module.jared-test.module.instance.google_sql_database_instance.master
on .terraform/modules/jared-test/modules/instance/main.tf line 48, in resource "google_sql_database_instance" "master":

### Steps to reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@jlam-bills did you notice below words in the error? 

```
Length of password cannot be less than 14. Password does not meet the complexity criteria.
```

It is hard to guess what you provide for the configuration as yours contain many unknown variables. Are you able to create a simple config with all hardcoded attributes so I can repro?

**Comment by jlam-bills** [comment]
@edwardmedia yes, I saw the error.  The returned error was unable to set the `root` user password because of the password policy. 

this is the other piece of the information:
```  password_policy = var.password_policy_enabled ? merge({
    min_length                  = 14
    reuse_interval              = 10
    complexity                  = "COMPLEXITY_DEFAULT"
    disallow_username_substring = true
    }, var.password_policy) : {
    min_length                  = 0
    reuse_interval              = 0
    disallow_username_substring = false
    complexity                  = "COMPLEXITY_UNSPECIFIED"
  }
}

I only copied the relevant code that was part of a module that we have.

**Comment by edwardmedia** [comment]
@jlam-bills I am not sure if there is anything we can do at the provider level. It is not a rule set at the provider level. This is the policy. I am curious why you can't follow the suggestion?

Are you able to do via gcloud without disabling the policy?

**Comment by jlam-bills** [comment]
@edwardmedia I'm closing the issue. We just set `root_password` attribute to meet the password policy requirements.
