### ISSUE TITLE
Vertex AI search with a website datastore with target sites

### ISSUE THREAD

**Issue by bademiya5306** [hashicorp/terraform-provider-google#17274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to create a website search datastore where data would be indexed using the list of my website urls. But the resource specified here https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/discovery_engine_data_store#data_store_id. does not provide an option for the same.

Should there be an additonal resource  to create target sites and link it to datastore as per this ?https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/projects.locations.dataStores.siteSearchEngine.targetSites/create

b/326185857

**Comment by jialei-chen** [comment]
Thanks for bringing up the feature request! I am adding the new resource target site. Please see: https://github.com/GoogleCloudPlatform/magic-modules/pull/11669

**Comment by melinath** [comment]
Should be resolved by the PR linked above.
