### ISSUE TITLE
No way of overriding project for `google_bigquery_connection`

### ISSUE THREAD

**Issue by BouguiWonderland** [hashicorp/terraform-provider-google#17276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When using `google_bigquery_connection` to [create BigQuery Omni Connection towards AWS S3](https://cloud.google.com/bigquery/docs/omni-aws-create-connection#creating-aws-connection) ([Terraform Doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection)), there is no way of overriding the project in which the connection will be created. Therefore, the connection will always be created on the project of the service account used to launch Terraform commands.

```tf
resource "google_bigquery_connection" "connection" {
   connection_id = "my-connection"
   location      = "aws-us-east-1"
   friendly_name = "👋"
   description   = "a riveting description"
   aws { 
      access_role {
         iam_role_id =  "arn:aws:iam::999999999999:role/omnirole"
      }
   }
}
```

### New or Affected Resource(s)

`google_bigquery_connection`

### Potential Terraform Configuration

The following addition would be great :

```tf
resource "google_bigquery_connection" "connection" {
   project_id = "my-project-id"
   connection_id = "my-connection"
   location      = "aws-us-east-1"
   friendly_name = "👋"
   description   = "a riveting description"
   aws { 
      access_role {
         iam_role_id =  "arn:aws:iam::999999999999:role/omnirole"
      }
   }
}

**Comment by shuyama1** [comment]
@BouguiWonderland It seems the resource does have a [`project`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection#project) field. Can you try if that works?

**Comment by BouguiWonderland** [comment]
Indeed it works, I have somehow managed to not find the parameter in the list as it was not in the first positions as often. Sorry for the bothering
