### ISSUE TITLE
Destroy folders with contents in bucket GCS

### ISSUE THREAD

**Issue by alfonsozamorac** [hashicorp/terraform-provider-google#17285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.2.9

### Affected Resource(s)

google_storage_bucket_object

### Terraform Configuration

```tf
terraform {
  required_version = ">= 0.15"
  required_providers {
    google = "5.10"
  }
}
```

### Expected Behavior

When creating a folder in a bucket with Terraform, if any files are later inserted into this folder, they can be deleted because that object is managed by Terraform.

### Actual Behavior

When creating a folder in a bucket with Terraform, if any file is inserted later inside this folder, it can no longer be deleted even though the apply says that it has been deleted correctly. On the other hand, we see that it can be eliminated through the command line as well as through the UI.

### Steps to reproduce

1. Create a new bucket and folders
```tf
resource "google_storage_bucket" "bucket" {
  project                     = "XXXXXXX"
  name                        = "my-bucket-name"
  location                    = "EU"
  uniform_bucket_level_access = true
  force_destroy               = true
}

resource "google_storage_bucket_object" "folder" {
  name    = "myapp/"
  content = " "
  bucket  = google_storage_bucket.bucket.name
}
```
2. `terraform apply`
3. Insert one file in the created folder.
4. Comment the resource code of bucket_object, and you can see that the google_storage_bucket_object will be removed:
```tf
resource "google_storage_bucket" "bucket" {
  project                     = "XXXXXXX"
  name                        = "my-bucket-name"
  location                    = "EU"
  uniform_bucket_level_access = true
  force_destroy               = true
}

#resource "google_storage_bucket_object" "folder" {
#  name    = "myapp/"
#  content = " "
#  bucket  = google_storage_bucket.bucket.name
#}
```
5. `terraform apply`
6. The changes are applied but the folder still exists.
7. If you use the command line, you can remove it: `gsutil rm -r gs://my-bucket-name/myapp`
8. `terraform destroy`

**Comment by edwardmedia** [comment]
@alfonsozamorac following your steps, I did see the object in the bucket deleted.  When you executed step 5, did you see a **DELETE** request in your debug log?

**Comment by alfonsozamorac** [comment]
You can delete the folder as long as it is empty, if you insert any file inside, it will no longer be deleted:

Logs:

######

Terraform will perform the following actions:
```tf
    # google_storage_bucket_object.folder will be destroyed
  # (because google_storage_bucket_object.folder is not in configuration)
  - resource "google_storage_bucket_object" "folder" {
      - bucket           = "test-delete-folder" -> null
      - content          = (sensitive value)
      - name                   = "myapp/" -> null
      - output_name      = "myapp/" -> null
        ...
    }
```
Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_storage_bucket_object.folder: Destroying... [id=test-delete-folder-myapp/]
google_storage_bucket_object.folder: Destruction complete after 0s

###################

After applying the changes, you look at the UI again and see that the folder and file are still there.

**Comment by edwardmedia** [comment]
@alfonsozamorac I think I understand your question now. I don't think there is a folder in gcs as you expected a folder container. `google_storage_bucket_object` is used for content, not a folder. To test, are you able to provide zero byte of content instead of one empty string?

```
content = ""
```
When you commented `google_storage_bucket_object`, it tells the terraform to delete the content ( " " object in your case), not other objects you added later on which share the partial `ids` with it.

Does this make sense?
