### ISSUE TITLE
metadata_startup_script not running all the script content

### ISSUE THREAD

**Issue by GTGabaaron** [hashicorp/terraform-provider-google#17280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

This is related to https://github.com/hashicorp/terraform-provider-google/issues/17251
I managed to make the metadata_startup_script run the target script (at least part of) but there are some instructions that are not being executed. After checking the /var/log/messages file I get the following errors.

```
google_metadata_script_runner: Found startup-script in metadata.
google_metadata_script_runner: startup-script: sleep: invalid time interval ‘30**\r**’
google_metadata_script_runner: startup-script: Try 'sleep --help' for more information.
google_metadata_script_runner: startup-script: /tmp/metadata-scripts2343503260/startup-script: line 3: $'chpasswd**\r**': command not found
google_metadata_script_runner: startup-script: sed: can't read /etc/ssh/sshd_config**#015**: No such file or directory
google_metadata_script_runner: startup-script: sed: can't read /etc/ssh/sshd_config**#015**: No such file or directory
google_metadata_script_runner: startup-script: sed: can't read /etc/ssh/sshd_config**#015**: No such file or directory
google_metadata_script_runner: startup-script: Failed to restart sshd\x0d.service: Unit not found.
google_metadata_script_runner: startup-script: useradd: invalid user name 'user_admin**#015**'
google_metadata_script_runner: startup-script: /tmp/metadata-scripts2343503260/startup-script: line 9: $'chpasswd**\r**': command not found
google_metadata_script_runner: startup-script: /bin/cd: line 2: cd: /tmp**#015**: No such file or directory
```

As you can see above, estrange characters like **\r** or **#15** are being added for some instructions, which shouldn't be case since the script file is formatted in UNIX, using only LF ending line (I have double checked it). I even re-created the whole script in a Linux machine using Vim, but still is failing.

Below is the script content, simple as that --->

```
sleep 30
sudo su
sudo echo "root:${password}" | chpasswd
sudo sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sudo sed -i -e 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
sudo sed -i -e 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
sudo systemctl restart sshd
sudo useradd -m -s /bin/bash "user_admin"
sudo echo "user_admin:${password}" | chpasswd
sudo cd /tmp
sudo touch user_admin.txt
sudo echo "user_admin username and password successfully created" >> user_admin.txt
sudo echo "the values of the password is -----> " ${password} >> user_admin.txt
sudo echo "the value of the prefix is -----> " ${prefix} >> user_admin.txt
sudo touch initial-setup-services.txt
sudo ps -aux >> initial-setup-services.txt
cat - >/etc/hosts <<EOF
127.0.0.1   localhost
10.0.5.10   ${prefix}-administrator ad
10.0.5.11   ${prefix}-firewall fire
10.0.5.20   ${prefix}-web www
10.0.5.100  ${prefix}-mysql db
EOF
```

PS. I've tried removing the references to sudo, but the outcome is the same error messages.

### Terraform Version

Terraform v1.7.3 on windows_amd64

### Affected Resource(s)

metadata_startup_script on google_compute_instance

### Terraform Configuration

```tf
```

### Expected Behavior

No issues should be returned. As mentioned on the previous issue, when the script is executed from my local computer everything runs fine.

### Actual Behavior

Only some instructions of the script are being executed.

### Steps to reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@GTGabaaron can you share the [debug log ](https://developer.hashicorp.com/terraform/internals/debugging)for your apply execution? You should be able to see what exact scripts that are sent to the api?

**Comment by GTGabaaron** [comment]
@edwardmedia I'm sharing the logs to the last deploy this morning. I selected the debug level for the TF logs, let me know if any additional info is needed.
[TF_LOG_DEBUG.txt](https://github.com/hashicorp/terraform-provider-google/files/14301313/TF_LOG_DEBUG.txt)

**Comment by GTGabaaron** [comment]
HI there, I found the root cause of the issue and how to solve it, it was basically and incompatibility between azure devops agent and the linux bash files.

**Comment by zli82016** [comment]
@GTGabaaron, are you fine if I closed this issue? Or do you have more concerns? Thanks.
