### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withGatewayApiConfig failing on PRs

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#17319]
### Failure rates

- ?% since YYYY-MM-DD?

### Impacted tests

- TestAccContainerCluster_withGatewayApiConfig

### Affected Resource(s)

* google_container_cluster

### ~Nightly build test history~ Failure on PR

- [Link to failure on PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10009#issuecomment-1952909382)

### Message(s)

```
2024/02/19 16:46:13 [DEBUG] [transport] [server-transport 0xc0011011e0] loopyWriter exiting with error: transport closed by client 
    vcr_utils.go:152: Step 1/5, expected an error with pattern, no match on: Error running pre-apply refresh: exit status 1
        
        Error: expected gateway_api_config.0.channel to be one of ["CHANNEL_DISABLED" "CHANNEL_EXPERIMENTAL" "CHANNEL_STANDARD"], got CANARY
        
          with google_container_cluster.primary,
          on terraform_plugin_test.tf line 12, in resource "google_container_cluster" "primary":
          12:     channel = "CANARY"
        
--- FAIL: TestAccContainerCluster_withGatewayApiConfig (1.77s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container	1.871s
FAIL
stderr:


```

b/326185953

**Comment by SarahFrench** [comment]
I think that the validation here needs to be updated: https://github.com/hashicorp/terraform-provider-google/blob/dc3839878e2e68b2e1aa73fca12f3c3277cf17e3/google/services/container/resource_container_cluster.go#L1852

**Comment by melinath** [comment]
This test expects an error but it looks like the formatting of the error changed such that the regex no longer matches: https://github.com/hashicorp/terraform-provider-google-beta/blob/7462d9cd2c6677b807c4c9544a8064400589daa3/google-beta/services/container/resource_container_cluster_test.go#L4211

Previously the error from the API looked like:

```
expected gateway_api_config.0.channel to be one of [CHANNEL_DISABLED CHANNEL_EXPERIMENTAL CHANNEL_STANDARD], got CANARY
```

Now it looks like:

```
expected gateway_api_config.0.channel to be one of ["CHANNEL_DISABLED" "CHANNEL_EXPERIMENTAL" "CHANNEL_STANDARD"], got CANARY
```

**Comment by melinath** [comment]
This is also now failing in nightlies but I think it's worth just fixing since it's also impact PRs and the fix is trivial.
