### ISSUE TITLE
Missing `field` in `google_firestore_field` import

### ISSUE THREAD

**Issue by remko** [hashicorp/terraform-provider-google#17313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.16.0
+ provider registry.terraform.io/hashicorp/google-beta v5.16.0

### Affected Resource(s)

google_firestore_field

### Terraform Configuration

```tf
resource "google_firestore_field" "BatchOperation_expiresAt" {
      project    = "my-project-id"
      database   = "(default)"
      collection = "BatchOperation"
      field      = "expiresAt"
      ttl_config {}
}
```

### Expected Behavior

After importing the existing TTL using `terraform import 'google_firestore_field.BatchOperation_expiresAt' 'projects/my-project-id/databases/(default)/collectionGroups/BatchOperation/fields/expiresAt`, I would have expected no changes when doing a `terraform plan`.

### Actual Behavior

Terraform said it was going to apply the following change:

    # google_firestore_field.BatchOperation_expiresAt will be updated in-place
    ~ resource "google_firestore_field" "BatchOperation_expiresAt" {
        + field      = "expiresAt"

### Steps to reproduce

1. Use cloud console to create a TTL policy on a Firestore in Datastore model
2. Import it using `terraform import 'google_firestore_field.BatchOperation_expiresAt' 'projects/my-project-id/databases/(default)/collectionGroups/BatchOperation/fields/expiresAt`
3. Run `terraform plan`

### Important Factoids

This is the output of `terraform state show`:

    > terraform state show google_firestore_field.BatchOperation_expiresAt
    # google_firestore_field.BatchOperation_expiresAt:
    resource "google_firestore_field" "BatchOperation_expiresAt" {
        collection = "BatchOperation"
        database   = "(default)"
        id         = "projects/my-project-id/databases/(default)/collectionGroups/BatchOperation/fields/expiresAt"
        name       = "projects/my-project-id/databases/(default)/collectionGroups/BatchOperation/fields/expiresAt"
        project    = "my-project-id"
    
        timeouts {}

        ttl_config {
            state = "ACTIVE"
        }
}

The `field` seems to be missing from the config.

b/327218865

**Comment by roaks3** [comment]
Confirmed issue during the plan. It appears that immediately after import, the Terraform state has a null `field`, which is incorrect. There is likely some issue with the custom import code (it actually looks like there is a custom import defined for this resource, but it is not being used).
