### ISSUE TITLE
google_compute_firewall_policy_rule import field mismatch

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#17317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.6.6

### Affected Resource(s)

- `google_compute_firewall_policy_rule`

### Terraform Configuration

```tf
resource "google_compute_firewall_policy_rule" "rule" {
  for_each = random_integer.priority

  action          = "goto_next"
  direction       = "INGRESS"
  description     = "Default allow list for ${each.key} network"
  firewall_policy = google_compute_firewall_policy.standard.id
  match {
    layer4_configs {
      ip_protocol = "tcp"
    }
    layer4_configs {
      ip_protocol = "udp"
    }
    layer4_configs {
      ip_protocol = "icmp"
    }
    src_ip_ranges  = local.all_rules[each.key].source
    dest_ip_ranges = local.all_rules[each.key].dest
  }
  priority = each.value.result
}

import {
  to = google_compute_firewall_policy_rule.rule["transit"]
  id = "locations/global/firewallPolicies/807178536710/rules/10923"
}
```

### Debug Output

```
  # google_compute_firewall_policy_rule.rule["transit"] must be replaced
  # (imported from "locations/global/firewallPolicies/807178536710/rules/10923")
  # Warning: this will destroy the imported resource
-/+ resource "google_compute_firewall_policy_rule" "rule" {
        action                  = "goto_next"
        description             = "Default allow list for transit network"
        direction               = "INGRESS"
      - disabled                = false -> null
      - enable_logging          = false -> null
      ~ firewall_policy         = "807178536710" -> "locations/global/firewallPolicies/807178536710" # forces replacement
      ~ id                      = "locations/global/firewallPolicies/807178536710/rules/10923" -> (known after apply)
      ~ kind                    = "compute#firewallPolicyRule" -> (known after apply)
        priority                = 10923
      ~ rule_tuple_count        = 55 -> (known after apply)
```

### Expected Behavior

This should not destroy and replace the resource.  

### Actual Behavior

Resource is set for a force replacement due to the mismatch in the `firewall_policy` field reported by the resource output and what the API is storing, this causing a destroy/create cycle.

### Steps to reproduce

1. Create firewall rule in an unmanaged state following the pattern outlined in: https://github.com/hashicorp/terraform-provider-google/issues/13419
2. Import the firewall rule to it's proper spot using the `import` block

**Comment by ScottSuarez** [comment]
You should be able to remedy this issue by changing the firewall policy to the force_replace value read on import
```
      ~ firewall_policy         = "807178536710" -> "locations/global/firewallPolicies/807178536710" # forces replacement
```

Becomes
```
      firewall_policy         = "locations/global/firewallPolicies/807178536710" 
```
