### ISSUE TITLE
Identity Platform has already been enabled for this project

### ISSUE THREAD

**Issue by lripoche** [hashicorp/terraform-provider-google#17322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.16.0
+ provider registry.terraform.io/hashicorp/google-beta v5.16.0

### Affected Resource(s)

google_identity_platform_config

### Terraform Configuration

```tf
provider "google" {
  user_project_override = true
  billing_project       = var.deployment_project_id
}

provider "google-beta" {
  user_project_override = true
  billing_project       = var.deployment_project_id
}
module "project_services" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "~> 14.4"

  project_id  = var.deployment_project_id
  enable_apis = true

  activate_apis = [
    "servicemanagement.googleapis.com",
    "servicecontrol.googleapis.com",
    "identitytoolkit.googleapis.com",
    "cloudidentity.googleapis.com",
    "cloudbuild.googleapis.com",
    "run.googleapis.com",
    "cloudresourcemanager.googleapis.com",
  ]
  disable_services_on_destroy = false
}


resource "google_identity_platform_config" "default" {
  depends_on                 = [module.project_services]
  project                    = var.deployment_project_id
  autodelete_anonymous_users = true
  sign_in {
    email {
      enabled           = true
      password_required = true
    }
  }
}
```

### Debug Output

https://gist.github.com/lripoche/af519a4090d491fa34ad43441bf13a53

### Expected Behavior

Resource should be deployed correctly.

### Actual Behavior

Resource cannot be deployed because Identity Platform was already enabled.

The API is correctly enabled and nothing is configured within Identity Platform.

I can add the configuration without issue through the Google Cloud console. 

### Steps to reproduce

1. Instantiate this module and provide the `deployment_project_id` variable
1. `terraform apply`

### Important Factoids

Terraform command is executed from my workstation using gcloud ADC. 

The quota project was set using: `gcloud auth application-default set-quota-project our-internal-quota-project`.

**Comment by c2thorn** [comment]
@lripoche does this happen on a newly created project? It seems like the resource already exists for the project you are using.

If it already exists, do you need to just use `terraform import` instead?

**Comment by lripoche** [comment]
I did a few tests and it appears that this error occurs only in projects where I already have enabled then disabled the identitytoolkit API. 

If I enable the API in the cloud console, I can import it by using `tf import module.name.google_identity_platform_config.default deployment_project_id`. It imports an empty config. I can then run `tf apply` to activate email sign_in option. 

To detail a bit how I encountered this issue, at first, I was not able to deploy Identity Platform config with Terraform because it wasn't using the quota project I had set up using the gcloud CLI. Now I just define it within the module's provider : 
```tf
provider "google" {
  user_project_override = true
  billing_project       = "my-quota-project"
}

provider "google-beta" {
  user_project_override = true
  billing_project       = "my-quota-project"
}
module "project_services" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "~> 14.4"

  project_id  = var.deployment_project_id
  enable_apis = true

  activate_apis = [
    "servicemanagement.googleapis.com",
    "servicecontrol.googleapis.com",
    "identitytoolkit.googleapis.com",
    "cloudidentity.googleapis.com",
    "cloudbuild.googleapis.com",
    "run.googleapis.com",
    "cloudresourcemanager.googleapis.com",
  ]
  disable_services_on_destroy = false
}


resource "google_identity_platform_config" "default" {
  depends_on                 = [module.project_services]
  project                    = var.deployment_project_id
  autodelete_anonymous_users = true
  sign_in {
    email {
      enabled           = true
      password_required = true
    }
  }
}
```

Make sure to activate `identitytoolkit.googleapis.com` in your quota project first. 

Using this module with a brand new project I can deploy `google_identity_platform_config` properly. 

However, when I destroy `google_identity_platform_config` then redeploy it using `tf apply`, I still get the error: `INVALID_PROJECT_ID : Identity Platform has already been enabled for this project.`

Please let me know if this is a known limitation or a configuration error.

**Comment by c2thorn** [comment]
@lripoche I see. Yes it is a known limitation in the provider as the resource cannot actually be deleted (API restriction). Destroying it simply removes it from state in Terraform, so you would need to reimport it during the next redeploy. Apologies for the limitation. 

Closing this issue for now.
