### ISSUE TITLE
dataform_repository documentation is misleading

### ISSUE THREAD

**Issue by mmigdiso** [hashicorp/terraform-provider-google#17335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Description

the examples given on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataform_repository is misleading. 
The example is given to connect the dataform to a gcp source repo but google source repo is not supported by dataform as a remote git. 

git_remote_settings {
      url = google_sourcerepo_repository.git_repository.url
      default_branch = "main"
      authentication_token_secret_version = google_secret_manager_secret_version.secret_version.id
  }

this example is contradicting with the git providers listed in https://cloud.google.com/dataform/docs/connect-repository?_ga=2.55108780.-606622810.1699276445

in fact, there is a feature request for this: https://issuetracker.google.com/issues/287850319

### New or Affected Resource(s)

* google_*

### Potential Terraform Configuration

```tf 
```

b/326474616

**Comment by mmigdiso** [comment]
Thank you @SarahFrench  for taking a look into this. The problem seems to be on the dataform side as dataform does not accept the repo naming of the google code repo. 
you can find more details here: https://issuetracker.google.com/issues/287850319

In fact, when I try to add the google repo using the gcp UI, it gives me the following error: 'Must be a valid SSH URL.' 

When I use terraform to link the dataform repo to the google code repo, it doesn't fail but the remote connection screen of the dataform shows an error saying that the connection was not successful. 

Thus the problem is not on the terraform side but a lack of integration on gcp between these two components. 
The reason for opening this bug was to correct the documentation on terraform because other folks like me, after reading the terraform docs, may thing that this is a configuration issue.

**Comment by SarahFrench** [comment]
Thank you for the extra context about the error - I've opened a PR to change the examples in the docs
