### ISSUE TITLE
Enable `google_bigquery_datapolicy_data_policy` resources to use a `google_bigquery_routine` resource to define the data masking policy

### ISSUE THREAD

**Issue by chasinandrew** [hashicorp/terraform-provider-google#17341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Description

The ```google_bigquery_datapolicy_data_policy``` resource does not currently support creating [custom masking routines](https://cloud.google.com/bigquery/docs/user-defined-functions#custom-mask). Users are not able to manage their own user-defined functions in Terraform which can be a risk for potential misconfigurations.

### New or Affected Resource(s)

* google_bigquery_datapolicy_data_policy

### Potential Terraform Configuration

```tf 
```

### References

N/A

b/327064415

**Comment by SarahFrench** [comment]
Note from triage: It looks like the custom masking routine would be made via the [google_bigquery_routine](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine) resource, and then that would be referenced in the configuration of a `google_bigquery_datapolicy_data_policy` resource to enable custom masking routines.

[This section of the API docs](https://cloud.google.com/bigquery/docs/reference/bigquerydatapolicy/rest/v1/projects.locations.dataPolicies#DataMaskingPolicy) shows that referencing a routine is possible, and means the `google_bigquery_datapolicy_data_policy` resource would need to add a `routine` field to [the `data_masking_policy` block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_datapolicy_data_policy#data_masking_policy) in the resource.

**Comment by wj-chen** [comment]
The prerequisite change https://github.com/hashicorp/terraform-provider-google/issues/17061 is now complete and I will pick up this work.

**Comment by wj-chen** [comment]
Support has been added in https://github.com/GoogleCloudPlatform/magic-modules/pull/10388. @trodge Could you help me close this issue?

**Comment by SarahFrench** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/10388
