### ISSUE TITLE
Failing test(s): TestAccComputeRouterNat_withPrivateNatAndEmptyAction

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17379]
### Failure rates

- 100% since 2023-12-22

### Impacted tests

- TestAccComputeRouterNat_withPrivateNatAndEmptyAction
- TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges

### Affected Resource(s)

* google_compute_router_nat

### Nightly build test history

- https://hashicorp.teamcity.com/test/870417126083399828?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS
- https://hashicorp.teamcity.com/test/5380280077021967031?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS

### Message(s)

```
 Error: Error deleting Spoke: googleapi: Error 400: Resource '"projects/ci-test-project-nightly-beta/locations/global/spokes/tf-test-router-private-nat-ml7p76f9iu-spoke"' is already being used by resource(s) '"//compute.googleapis.com/projects/653407317329/locations/us-central1/routers/tf-test-router-private-nat-ml7p76f9iu"'
```

b/326650377

**Comment by rileykarson** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/10174 in theory (I haven't checked myself)

**Comment by melinath** [comment]
confirmed that this is now passing.
