### ISSUE TITLE
Failing test(s): TestAccFirebaseAppCheckServiceConfig_firebaseAppCheckServiceConfigUnenforcedExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17389]
### Failure rates

- 100% since [added](https://github.com/GoogleCloudPlatform/magic-modules/pull/9875) on 2024-01-31

### Impacted tests

- TestAccFirebaseAppCheckServiceConfig_firebaseAppCheckServiceConfigUnenforcedExample (GA only)

### Affected Resource(s)

* google_firebase_app_check_service_config

### Nightly build test history

- https://hashicorp.teamcity.com/test/503010936250154609?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS

### Message(s)

```
 Error: Error creating ServiceConfig: googleapi: Error 400: Firebase Realtime Database is not yet set up for project 594424405950.
```

b/326664572

**Comment by SarahFrench** [comment]
From triage: It would be worth checking [if the test needs to switch the service on (and then off when the test ends)](https://github.com/hashicorp/terraform-provider-google/blob/74dadb6684dc4cf2bd049759fdaf67759edc7451/google/services/firebaseappcheck/resource_firebase_app_check_service_config_generated_test.go#L63-L67) in the test projects or if we can update the test projects to all have the service enabled. If that cannot be changed we could add a wait, [like this example](https://github.com/hashicorp/terraform-provider-google/blob/74dadb6684dc4cf2bd049759fdaf67759edc7451/google/services/firestore/resource_firestore_document_generated_test.go#L72-L84), to ensure permissions propagate.

**Comment by rainshen49** [comment]
The reason this is failing is because this particular example uses App Check to protect Firebase Realtime Database, but there is no Realtime Database instances in the test project. Do you see any problem if we make a default Realtime Database instance in the test project environment? This only has to be done once per project. If we describe it using Terraform configs, it will roughly look like this

```hcl
resource "google_project_service" "firebase_database" {
  provider = google-beta
  project  = google_firebase_project.default.project
  service  = "firebasedatabase.googleapis.com"
}

resource "google_firebase_database_instance" "default" {
  provider = google-beta
  project  = google_firebase_project.default.project
  region   = "us-central1"
  instance_id = "${google_firebase_project.default.project}-default-rtdb"
  type     = "DEFAULT_DATABASE"
  depends_on = [google_project_service.firebase_database]
}
```

This is because I want to the App Check examples clean, that is, it isn't concerned with the provisioning of the resources it is used to project. The alternative is that I make this example create its own project, which will be more lengthy and takes more time to run.

**Comment by melinath** [comment]
@rainshen49 generally speaking we prefer for tests to create and destroy their own infrastructure.

If that's truly not possible for some reason (like the database needs to be set up manually but there can only be one per project or region or similar), you could create a new bootstrapping function for firebase database instances: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/acctest/bootstrap_test_utils.go

Example usage in a Resource.yaml file: https://github.com/GoogleCloudPlatform/magic-modules/blob/3907a64071e2aece0d26ef2e637e401a85ad1411/mmv1/products/secretmanager/Secret.yaml#L47

(We don't currently allow one-time setup of long-lived infrastructure since it can be difficult to maintain over time.)

The alternative, as you mentioned, would be to create a new project in the test - we have a decent number of tests that do this; the additional overhead is not really a concern, but if you want to have simpler docs examples, you either need to exclude part of the template during docs generation or make a separate example for docs (using `skip_test: true` and `skip_docs: true` on the examples that shouldn't be generated in each case.)
