### ISSUE TITLE
Failing test(s): TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17384]
### Failure rates

- 100% since 2024-02-06 (GA-only)

### Impacted tests

- TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample

### Affected Resource(s)

* google_database_migration_service_private_connection

### Nightly build test history

- https://hashicorp.teamcity.com/test/-2824815710737617596?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A97885%29%2Cid%3A2000000004

### Message(s)

First error was:
```
Error: Error waiting to create PrivateConnection: Error waiting for Creating PrivateConnection: Error code 4, message: Operation timed out.
```

Subsequent errors were:
```
Error: Error waiting to create PrivateConnection: Error waiting for Creating PrivateConnection: Error code 3, message: Failed to create the underlying private-connectivity resource: The IP range specified (10.0.0.0/29) overlaps with a reserved IP range. Provide a different IP range.
        com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: The IP range specified (10.0.0.0/29) overlaps with a reserved IP range. Provide a different IP range.
```

The changing error message combined with the fact this is GA-only makes me expect this to be an issue with dangling resources that are causing the conflict - but I can confirm that the private connection was not created. Perhaps there are some hidden resources that did get provisioned?

b/326671335

**Comment by SarahFrench** [comment]
Note from triage: the test uses a default network, so the problem could be solved by making the test use a dedicated network
