### ISSUE TITLE
Failing test(s): TestAccFirestoreField_firestoreFieldUpdateAddIndexExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17392]
### Failure rates

- 100% since 2024-01-22 (Technically since 2023-11-15, but that was initially due to a separate error.)

### Impacted tests

- TestAccFirestoreField_firestoreFieldUpdateAddIndexExample

### Affected Resource(s)

* google_firestore_field

### Nightly build test history

- https://hashicorp.teamcity.com/test/7677675020463571225?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A90949%29%2Cid%3A2000000015

### Message(s)

```
testing_new.go:84: Error running post-test destroy, there may be dangling resources: googleapi: Error 403: Cloud Firestore API has not been used in project tf-testld8dsvlqop before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=tf-testld8dsvlqop then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

b/326671122

**Comment by SarahFrench** [comment]
Note from triage: the problem here is that the test deletes all provisioned resources (including the project everything is contained in) and then runs the post destroy when the API is disabled. We could make the post destroy accept this error as expected, and not causing the test to fail.
