### ISSUE TITLE
Failing test(s): TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceDefaultDatabaseExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17391]
### Failure rates

- 48% as of 2024-02-23 (46/96)

### Impacted tests

- TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceDefaultDatabaseExample

### Affected Resource(s)

* google_firebase_database_instance

### Nightly build test history

- https://hashicorp.teamcity.com/test/-5726673718076092333?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

### Message(s)

```
Error: Error creating Instance: googleapi: Error 403: Permission 'firebasedatabase.instances.create' denied on resource '//firebasedatabase.googleapis.com/projects/tf-test-rtdb-projectmq3fdp9lqm/locations/us-central1' (or it may not exist).
```

b/326671138

**Comment by SarahFrench** [comment]
Note from triage: This could be a problem due to permissions not propagating (in the new project provisioned by the test) before they're used
