### ISSUE TITLE
Missing "Shielded VM" parameters in google_workbench_instance resource

### ISSUE THREAD

**Issue by Ardark27** [hashicorp/terraform-provider-google#17408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Description

The google_workbench_instance resource in Terraform currently lacks support for configuring "Shielded VM" parameters, despite the availability of this feature through the Google Cloud Platform (GCP) console interface.
![image](https://github.com/hashicorp/terraform-provider-google/assets/67149521/0b27f862-2475-4503-9251-98d70658dd64)

**Expected Behavior**
Users should be able to define and configure "Shielded VM" parameters such as **enable_secure_boot** and **enable_vtpm** when using the google_workbench_instance resource in Terraform, similar to how it can be done through the GCP console.

### New or Affected Resource(s)

* google_workbench_instance

### Potential Terraform Configuration

```tf 
```

b/326978482

**Comment by SarahFrench** [comment]
From triage: This request corresponds to adding support for the [the `shieldedInstanceConfig` API field](https://cloud.google.com/vertex-ai/docs/workbench/reference/rest/v2/projects.locations.instances#ShieldedInstanceConfig). The new field would be nested inside [the existing gce_setup block in the resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workbench_instance#nested_gce_setup).

**Comment by bcreddy-gcp** [comment]
It's available with today's release: https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v5.18.0.
See usage here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workbench_instance#example-usage---workbench-instance-full

**Comment by SarahFrench** [comment]
Thanks! Closing as complete
