### ISSUE TITLE
url_map does not support more than one header in response_headers_to_add 

### ISSUE THREAD

**Issue by intotecho** [hashicorp/terraform-provider-google#17404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.7

### Affected Resource(s)

google_compute_url_map 5.17

### Terraform Configuration

This url_map works fine, it adds a single response header. 

```tf
  path_matcher {
    name            = "my-paths"
    default_service = my_backend
    route_rules {
      match_rules {
        path_template_match =  # anything
      }
      service  = local.my_backend
      priority = 10
      header_action {
        response_headers_to_add {
          header_name  = "Active-Rule"
          header_value = 10
          replace      = false
        }
      }
```
But I cannot add more than one response header with this syntax, or multiple header_action blocks. 

I can do it on the GCP console, in yaml, so the API supports it.

```yaml
  routeAction:
    urlRewrite:
      pathTemplateRewrite: /
  headerAction:
    responseHeadersToAdd:
    - headerValue: '10'
      headerName: Active-Rule
    - headerValue: my.domain/server/
    - replace: true
      headerName: Location
```
I appears to be a limitation in the interface syntax, since the name of the block is plural: headers_to_add. 
The same issue affects request_headers_to_add and response_headers_to_add, which appear in various blocks, not just header_action. 

Note that the [compute-backend_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#example-usage---backend-service-network-endpoint) allows multiple headers as it uses a different syntax.
```tf
custom_request_headers          = ["host: ${google_compute_global_network_endpoint.proxy.fqdn}"]
custom_response_headers         = ["X-Cache-Hit: {cdn_cache_status}"]
```

### Steps to reproduce

1. `terraform apply`

**Comment by zli82016** [comment]
I can add multiple headers in `response_headers_to_add` inside `path_mather.route_rues.header_action` and cannot reproduce this issue. 


@intotecho , can you please provide the configuration to add multiple headers in `response_headers_to_add` and the logs with the error message? Thanks.

**Comment by intotecho** [comment]
The terraform component does in fact support multiple blocks of response_headers_to_add  inside header_action. This issue can be closed. 

```tf
 header_action {
        response_headers_to_add {
          header_name  = "header-1"
          header_value = 1
          replace      = false
        }
        response_headers_to_add {
          header_name  = "header-2"
          header_value = 1
          replace      = false
        }
      }
```
