### ISSUE TITLE
Add use_table_schema to bigquery_config for pubsub_subscription

### ISSUE THREAD

**Issue by Thrasi** [hashicorp/terraform-provider-google#17406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Description

Google now provides the option to [use table schema](https://cloud.google.com/pubsub/docs/subscription-properties#use-table-schema) for PubSub Bigquery subscriptions.

This is not available the [terraform bigquery_config](https://registry.terraform.io/providers/hashicorp/google/4.62.1/docs/resources/pubsub_subscription#nested_bigquery_config) for the google_pubsub_subscription resource.

### New or Affected Resource(s)

* [google_pubsub_subscription](https://registry.terraform.io/providers/hashicorp/google/4.62.1/docs/resources/pubsub_subscription)

### Potential Terraform Configuration

```tf 
resource "google_pubsub_subscription" "example" {
  name  = "example-subscription"
  topic = google_pubsub_topic.example.name

  bigquery_config {
    table = "table_name"
    use_table_schema = true
  }
}
```

### References

https://cloud.google.com/pubsub/docs/subscription-properties#use-table-schema
https://registry.terraform.io/providers/hashicorp/google/4.62.1/docs/resources/pubsub_subscription#nested_bigquery_config

**Comment by SarahFrench** [comment]
It appears that [this field was added to the pubsub subscription resource in v5.14.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.14.0), please see [the documentation here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#use_table_schema).
