### ISSUE TITLE
google_compute_firewall - removal of source_tags, when both source_tags and source_ranges are used

### ISSUE THREAD

**Issue by jakunow** [hashicorp/terraform-provider-google#17428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.17.0
+ provider registry.terraform.io/hashicorp/google-beta v5.17.0

### Affected Resource(s)

google_compute_firewall

### Terraform Configuration

```tf
resource "google_compute_firewall" "testrule" {
  name          = "testrule"
  project       = "project-1234"
  network       = "network-1234"
  source_ranges = ["10.0.0.0/24"]
  source_tags   = ["testtag"]
  allow {
    protocol = "tcp"
    ports    = [443]
  }
}
```

```tf
resource "google_compute_firewall" "testrule" {
  name          = "testrule"
  project       = "project-1234"
  network       = "network-1234"
  source_tags   = ["testtag"]
  allow {
    protocol = "tcp"
    ports    = [443]
  }
}
```

### Expected Behavior

* After applying the first configuration, the firewall rule has a source IP range as source filter and source tags as second source filter
* After applying the second configuration, the firewall has source tags as source filter
* Subsequent plans detect no changes needed.

### Actual Behavior

* After applying the first configuration, the firewall rule has a source IP range as source filter and source tags as second source filter
* After applying the second configuration, the firewall has a source IP range as source filter and source tags as second source filter
* Subsequent plans are aware that the resource does not match the configuration, and propose the removal of the source range. Applies succeed but have no actual effect on the firewall rule - resulting in perma-diff

### Steps to reproduce

* `terraform apply` the first config
* `terraform apply` the second config
* Observe that the resource still has the source_range as source filter

### Important Factoids

* This can be applied manually via console and editing firewall rule
* Console visualizes source range as "Source filter" and source tags as "Second source filter". To make that change you have to remove "Second source filter" and change "Source filter" from "IPv4 ranges" to "Source tags"

### References

Seems to be related to #16221

**Comment by roaks3** [comment]
This looks like it is actually a duplicate of the https://github.com/hashicorp/terraform-provider-google/issues/16221 issue you mentioned. Is there something different from that issue that you are specifically reporting here? If not, I think we can close as a duplicate.

**Comment by jakunow** [comment]
@roaks3 just wanted to point out source_tags issue that wasn't mentioned in #16221 
We can close this as duplicate.
