### ISSUE TITLE
Cannot add VPC peering to Private Service Access subnet to connect or use GCP services

### ISSUE THREAD

**Issue by dv01d** [hashicorp/terraform-provider-google#17439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

OpenTofu v1.6.2

### Affected Resource(s)
google_service_networking_connection

### Terraform Configuration
registry.opentofu.org/hashicorp/google v5.17.0

```
locals {
shared_vpc_project = "test"
}
data "google_compute_network" "network" {
  name                    = var.network
  project                 = local.shared_vpc_project
}


resource "google_compute_global_address" "private_ip_address" {
  name          = local.private_ip_name
  address_type  = "INTERNAL"
  purpose       = "VPC_PEERING"
  prefix_length = 24
  project       = local.shared_vpc_project
  network       = data.google_compute_network.network.id
}

resource "google_service_networking_connection" "default" {
  network                 = google_compute_global_address.private_ip_address.id
  service                 = "servicenetworking.googleapis.com"
  #reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.address}/${google_compute_global_address.private_ip_address.prefix_length}"]
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.name]
}
```

### Debug Output

```
google_service_networking_connection.default: Creating...
google_service_networking_connection.default: Still creating... [10s elapsed]
╷
│ Error: Error waiting for Create Service Networking Connection: Error code 9, message: Allocated IP range 'private-service-access-production' not found in network.
│ Help Token: AX4KC-h1UizO0FdDnGc7abx34d7jy4f6YV69g_rOOWRbQTVMOx-wMu1KKs2fKpihiFa12sif-oUdmfWvKq-sC_Q5S9n3O1TCaIB_cObOJvIvnPmK
│ 
│   with google_service_networking_connection.default,
│   on main.tf line 72, in resource "google_service_networking_connection" "default":
│   72: resource "google_service_networking_connection" "default" {
│ 
╵
```

### Expected Behavior

Created VPC peering

### Actual Behavior

Produced an error

### Steps to reproduce

1. Use google_service_networking_connection resource to create VPC peering
2. Use any combination of values to reserved_peering_ranges (i.e name from google_compute_global_address, or network block)
3. run terraform (tofu) apply

### Important Factoids

NA

### References

Similar to previous issues where this happened: https://github.com/hashicorp/terraform-provider-google/issues/11100

b/327438987

**Comment by zli82016** [comment]
It looks an issue in API. Forwarding to the service team to check.

**Comment by zli82016** [comment]
@dv01d ，can you please provide the following information to help debug? 

Consumer project:
Consumer Network:

**Comment by ametad** [comment]
This seems not correct:

```hcl
  network                 = google_compute_global_address.private_ip_address.id
```

I think this should be:

```hcl
  network                 = google_compute_network.network.id
```

Perhaps now the range can be found?

**Comment by zli82016** [comment]
> google_service_networking_connection

Yeah, it should be 
```
network                 = data.google_compute_network.network.id
```

**Comment by ametad** [comment]
Hi @zli82016 

Well I have no problems here... I was searching for another problem and saw this post. Spotted the wrong configuration and hoped to be helpful.

This is a snippet of a config we use and that is working:

```hcl
resource "google_compute_network" "private_network" {
  name = "private-network"
}

resource "google_compute_global_address" "private_services-range" {
  name          = "private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  network       = google_compute_network.private_network.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network = google_compute_network.private_network.id
  service = "servicenetworking.googleapis.com"

  reserved_peering_ranges = [
    google_compute_global_address.private_services-range.name,
  ]
}
```

**Comment by ametad** [comment]
BTW We do not use OpenTofu but Terraform.

**Comment by zli82016** [comment]
@ametad , thank you so much for spotting the configuration issue, which is really helpful.

**Comment by dv01d** [comment]
Thanks for pointing this one out.
