### ISSUE TITLE
google_compute_region_security_policy lacking rateLimitOptions

### ISSUE THREAD

**Issue by dawidolespl** [hashicorp/terraform-provider-google#17442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Hi,

the docs here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_security_policy_rule#action
states about rateLimitOptions field to be set when, for example 'throttle' action is chosen, but there is not such structure present in this code: https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/services/compute/resource_compute_region_security_policy_rule.go
In this condition it makes it useless for my use case, similar issue has been once resolved for the global variant:
https://github.com/hashicorp/terraform-provider-google-beta/pull/3596/files

### New or Affected Resource(s)

* google_compute_region_security_policy

### Potential Terraform Configuration

```tf 
resource "google_compute_region_security_policy_rule" "ratelimit" {
  region          = var.region
  project         = var.project
  provider        = google-beta
  security_policy = google_compute_region_security_policy.mypolicy.name
  action          = "throttle"
  priority        = 1000
  rate_limit_options {
    conform_action = "allow"
    rate_limit_threshold {
      count        = 100
      interval_sec = 60
    }
    exceed_action  = "deny(429)"
    enforce_on_key = "IP"
  }
}

```

b/327469519

**Comment by melinath** [comment]
This is indeed present in the API and missing in Terraform. I don't see an equivalent `google_compute_security_policy_rule` resource (should there be one?) but it looks like the rate_limit_options field is missing on:

- google_compute_region_security_policy
- google_compute_region_security_policy_rule
- google_compute_organization_security_policy
- google_compute_organization_security_policy_rule

**Comment by melinath** [comment]
Looking at these resources some more, I believe this field actually _shouldn't_ be supported on `google_compute_region_security_policy` or `google_compute_organization_security_policy` since they don't support managing rules - those can only be managed with the dedicated resources. `google_compute_security_policy` _does_ manage rules (which is probably why there isn't a corresponding rule resource.)

So - it should only be added to `google_compute_region_security_policy_rule` and `google_compute_organization_security_policy_rule`
