### ISSUE TITLE
Error reading level state: strconv.ParseInt: parsing "1706027508932": value out of range

### ISSUE THREAD

**Issue by Quillotaku** [hashicorp/terraform-provider-google#17461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.2
on windows_386
+ provider registry.terraform.io/hashicorp/google v5.13.0
+ provider registry.terraform.io/hashicorp/google-beta v5.18.0

Your version of Terraform is out of date! The latest version
is 1.7.4. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

google_*

### Terraform Configuration

```tf
```

### Expected Behavior

Normal output of the plan

### Actual Behavior

 Error: Plugin did not respond
│
│   with google_bigquery_dataset.terraform_dataset,
│   on bigdata.tf line 1, in resource "google_bigquery_dataset" "terraform_dataset":
│    1: resource "google_bigquery_dataset" "terraform_dataset" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_data_fusion_instance.example,
│   on bigdata.tf line 12, in resource "google_data_fusion_instance" "example":
│   12: resource "google_data_fusion_instance" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_pubsub_topic.default,
│   on functions.tf line 81, in resource "google_pubsub_topic" "default":
│   81: resource "google_pubsub_topic" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_compute_network.vpc,
│   on networking.tf line 2, in resource "google_compute_network" "vpc":
│    2: resource "google_compute_network" "vpc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_secret_manager_secret.pass,
│   on secrets.tf line 24, in resource "google_secret_manager_secret" "pass":
│   24: resource "google_secret_manager_secret" "pass" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_secret_manager_secret.ssh,
│   on secrets.tf line 36, in resource "google_secret_manager_secret" "ssh":
│   36: resource "google_secret_manager_secret" "ssh" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_secret_manager_secret_version.user,
│   on secrets.tf line 48, in resource "google_secret_manager_secret_version" "user":
│   48: resource "google_secret_manager_secret_version" "user" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with google_secret_manager_secret_version.token,
│   on secrets.tf line 56, in resource "google_secret_manager_secret_version" "token":
│   56: resource "google_secret_manager_secret_version" "token" {
│
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with google_service_account_iam_policy.admin-account-iam,
│   on service_account.tf line 51, in resource "google_service_account_iam_policy" "admin-account-iam":
│   51: resource "google_service_account_iam_policy" "admin-account-iam" {
│
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with google_storage_bucket.bucket,
│   on storage.tf line 1, in resource "google_storage_bucket" "bucket":
│    1: resource "google_storage_bucket" "bucket" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_storage_bucket.downloads,
│   on storage.tf line 19, in resource "google_storage_bucket" "downloads":
│   19: resource "google_storage_bucket" "downloads" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v5.13.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "1706027508932": value out of range

goroutine 278 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x10a8e050, {0x10a8bb90, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x10a8e050)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xfaf2bd0, {{{0x49ad738, 0x10a8a830}}, {0x3d82e60, 0x10209180}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xfd31940, {0x49acf58, 0x105d4b40}, 0x102080e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xfd2a000, 0xfd2a040, {0x10602160, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xfbc0460, {0x49acf58, 0x105d47c8}, 0x1043cab0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x4291a00, 0xfbc0460}, {0x49acf58, 0x105d47c8}, 0x1092b440, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x106bc140, {0x49acf58, 0x105d4798}, {0x49b1bc0, 0x104d0000}, 0x105fc000, 0xffaee10, 0x62d51a8, 0x0)
        google.golang.org/grpc@v1.60.1/server.go:1372 +0xf68
google.golang.org/grpc.(*Server).handleStream(0x106bc140, {0x49b1bc0, 0x104d0000}, 0x105fc000)
        google.golang.org/grpc@v1.60.1/server.go:1783 +0x110e
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.1/server.go:1016 +0x71
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.60.1/server.go:1027 +0x13d

Error: The terraform-provider-google_v5.13.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to reproduce

1. `terraform plan`

**Comment by sann3** [comment]
Same error I am also getting on many versions

**Terraform Version**
1.5.7 windows 386
1.7.4 windows 386

Stack trace from the terraform-provider-google_v5.0.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "6311955555626292354": value out of range

goroutine 3625 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x182c1630, {0x18108d70, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x182c1630)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x1739b420, {{{0x41b4a80, 0x1804fa08}}, {0x35aae60, 0x1768d0e0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1732d1c0, {0x41b43a0, 0x17c1c1f8}, 0x17672900)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x171848a0, 0x171848e0, {0x17808490, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x178a4a00, {0x41b43a0, 0x17717038}, 0x177e70e0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x3a8e1e0, 0x178a4a00}, {0x41b43a0, 0x17717038}, 0x17d80b40, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x16d31440, {0x41b8e4c, 0x177a4000}, 0x17db9ea0, 0x1756d0c8, 0x5930868, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xf03
google.golang.org/grpc.(*Server).handleStream(0x16d31440, {0x41b8e4c, 0x177a4000}, 0x17db9ea0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-google_v5.0.0_x5.exe plugin crashed!

**Comment by rileykarson** [comment]
Some explanation in https://github.com/hashicorp/terraform-provider-google/issues/16809#issuecomment-1977547509. Given our provider doesn't work with i386 and won't without significant effort given we write int64 results into `int` datatypes I'll see if HashiCorp can help us mark it incompatible.
