### ISSUE TITLE
TLS_JA3_FINGERPRINT is not supported in google_compute_security_policy resource

### ISSUE THREAD

**Issue by mqmr** [hashicorp/terraform-provider-google#17469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

[NOT A CONTRIBUTION]

It seems both of version of the provider - "stable" and "beta", don't support setting TLS_JA3_FINGERPRINT in google_compute_security_policy resource, while the documentation [1] and examples [2] show it's possible.

```
│ Error: expected rule.60.rate_limit_options.0.enforce_on_key to be one of ["ALL" "IP" "HTTP_HEADER" "XFF_IP" "HTTP_COOKIE" "HTTP_PATH" "SNI" "REGION_CODE" ""], got TLS_JA3_FINGERPRINT
```

```
│ Error: expected rule.60.rate_limit_options.0.enforce_on_key_configs.0.enforce_on_key_type to be one of ["ALL" "IP" "HTTP_HEADER" "XFF_IP" "HTTP_COOKIE" "HTTP_PATH" "SNI" "REGION_CODE"], got TLS_JA3_FINGERPRINT
```

- https://github.com/hashicorp/terraform-provider-google-beta/blob/f3462a7e0dd9c004586d6fb3e231356ec4d1b2f3/google-beta/services/compute/resource_compute_security_policy.go#L288
- https://github.com/hashicorp/terraform-provider-google/blob/ef4977ad913d503012c2d17418790bad960933bc/google/services/compute/resource_compute_security_policy.go#L221

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf 
```

### References

Docs: 
[1] https://cloud.google.com/armor/docs/rate-limiting-overview#identifying_clients_for_rate_limiting
[2] https://cloud.google.com/armor/docs/configure-rate-limiting#ja3

b/328077803

**Comment by rojomisin** [comment]
a workaround is to add a custom header to the backend and rate limit off the that
