### ISSUE TITLE
Make magician subcommands use `RunE` and return errors instead of calling os.Exit directly

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17479]
Currently magician subcommands (like `request-service-reviewers`) use Run, which has no return value, and then call `os.Exit` directly if there are errors. This makes testing more difficult. We should instead use `RunE` and return errors, and then manage printing fatal errors only at the root level.

Here is a commit that partially did this conversion for one command (alongside some other work that was the motivating factor & later discarded): https://github.com/GoogleCloudPlatform/magic-modules/pull/10066/commits/372f65a1bfc03875adc9a2b31e9b02ac3d5a38f4

**Comment by melinath** [comment]
@trodge I'm unassigning you since I think this was deprioritized for now & hasn't been started yet. Please feel free to reassign if that's incorrect.

**Comment by iyabchen** [comment]
I can take this ticket.
