### ISSUE TITLE
Unsupported block type - auto_deploy_config

### ISSUE THREAD

**Issue by micaellap** [hashicorp/terraform-provider-google#17487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

1.7.3 (choco has not disponibilized the newest version yet)

### Affected Resource(s)

google_compute_security_policy

### Terraform Configuration

```tf

resource "google_compute_security_policy" "policy" {
  name = "ratelimit-policy"

  adaptive_protection_config {

    layer_7_ddos_defense_config {
      enable = true
    }

    auto_deploy_config {
      load_threshold = 0.8
      confidence_threshold = 0.5
      impacted_baseline_threshold = 0.01
      expiration_sec = 7200

    }
  }
}
```

### Debug Output

https://gist.github.com/micaellap/883f2d0df51daae31a72ef3d2c6e60ac

### Expected Behavior

I should have been able to execute terraform plan/apply after especifying the **'auto_deploy_config'** section of **'adaptive_protection_config'** on a Cloud Armor policy file, after following the specified configurations displayed [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy#auto_deploy_config).

### Actual Behavior

I got the following error:

 Error: Unsupported block type
│
│   on policy_ego.tf line 68, in resource "google_compute_security_policy" "policy_ego":
│   68:     auto_deploy_config {
│
│ Blocks of type "auto_deploy_config" are not expected here.

### Steps to reproduce

1. `terraform plan`

**Comment by rileykarson** [comment]
The field is in beta as marked in the docs ("`(Optional, Beta)`"). You should be able to use it by explicitly specifying the beta provider as described in https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_versions.
