### ISSUE TITLE
Add new resources to support Service Extensions callouts for Cloud Load Balancing

### ISSUE THREAD

**Issue by maxi-cit** [hashicorp/terraform-provider-google#17491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Support callout extensions for the Network Services API

### New or Affected Resource(s)

* google_network_services_lb_route_extension
* google_network_services_lb_traffic_extension

### Potential Terraform Configuration

```tf
resource "google_network_services_lb_route_extension" "default" {
  name     = "my-lb-route-extension"
  ... 
} 

resource "google_network_services_lb_traffic_extension" "default" {
  name     = "my-lb-traffic-extension"
  ... 
} 
```

### References

**Issues**
* https://github.com/hashicorp/terraform-provider-google/issues/17372
* https://github.com/hashicorp/terraform-provider-google/issues/17373

**Docs**
* https://cloud.google.com/service-extensions/docs/callouts-overview

**API**
* https://cloud.google.com/service-extensions/docs/reference/rest/v1beta1/projects.locations.lbRouteExtensions
* https://cloud.google.com/service-extensions/docs/reference/rest/v1beta1/projects.locations.lbTrafficExtensions

**Comment by melinath** [comment]
These resources were added in the above PRs
