### ISSUE TITLE
Add iap.enabled to google_compute_region_backend_service

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#17494]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Region Backend Service has a custom encoder to force send the `iap` block with `iap.enabled = false` if it doesn't exist in config: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/encoders/region_backend_service.go.erb#L15

This is causing a customer issue: b/310147789
With this encoder, the provider does not surface the `iap.enabled` field to users. This is additionally not correct because users should be allowed to send `iap.enabled = false` with other fields in the `iap` block configured.

https://github.com/GoogleCloudPlatform/magic-modules/pull/9581 fixes this by adding `iap.enabled` as a required field. This would be a breaking change, and we may consider a state upgrader to add the field for existing resources in the next major release.

### New or Affected Resource(s)

* google_compute_region_backend_service

### Potential Terraform Configuration

```tf 
```

### References

b/310147789
https://github.com/GoogleCloudPlatform/magic-modules/pull/9581

**Comment by melinath** [comment]
Whatever happens for this should likely be replicated in `google_compute_backend_service` (the non-regional variant) so that they behave consistently. https://github.com/hashicorp/terraform-provider-google/issues/16585 tracks that request as well.
