### ISSUE TITLE
WorkloadIdentityPool: googleapi: Error 403: Permission 'iam.workloadIdentityPools.create' denied on resource

### ISSUE THREAD

**Issue by jsecchiero** [hashicorp/terraform-provider-google#17508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

```
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.19.0
+ provider registry.terraform.io/hashicorp/google-beta v5.19.0
```

### Affected Resource(s)

google_iam_workload_identity_pool

### Terraform Configuration

```tf
resource "google_iam_workload_identity_pool" "this" {
  provider = google-beta
  workload_identity_pool_id = "asdfasdf"
}
```

### Debug Output

Generates this error:
```
google_iam_workload_identity_pool.this: Creating...
╷
│ Error: Error creating WorkloadIdentityPool: googleapi: Error 403: Permission 'iam.workloadIdentityPools.create' denied on resource '//iam.googleapis.com/projects/REDACTED-PROJECT/locations/global' (or it may not exist).
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.workloadIdentityPools.create",
│       "resource": "projects/REDACTED-PROJECT/locations/global"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│
│   with google_iam_workload_identity_pool.this,
│   on main.tf line 30, in resource "google_iam_workload_identity_pool" "this":
│   30: resource "google_iam_workload_identity_pool" "this" {
│
```

### Expected Behavior

creating a `asdfasdf` `workload-identity-pools`. With gui and cli evrything is working as expected:
```
@ gcloud iam workload-identity-pools create asdfasdf --location=global
Created workload identity pool [asdfasdf].
```

### Actual Behavior

Permission denied

### Steps to reproduce

1. `terraform apply`

### References

#11789 mentions that special `workloadIdentityPoolAdmin` permissions are needed  but seems not enough

**Comment by ggtisc** [comment]
Hi @jsecchiero according to the official IO `provider = google-beta` isn't a valid argument: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iam_workload_identity_pool

This scenario was replicated with the next code without any issues:
```
provider "google" {}

resource "google_iam_workload_identity_pool" "this" {
  workload_identity_pool_id = "asdfasdf"
}
```
I suggest you review your credentials, roles, policies and permissions to validate that you are allowed to execute actions between your account and the resources involved. I share the following links so you can guide yourself:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/iam_policy
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/iam_role

**Comment by jsecchiero** [comment]
Hey @ggtisc thanks for the help

>according to the official IO provider = google-beta isn't a valid argument
i have used the same example shared in the previous issue #11789 but i have tried also without it with the same result

> I suggest you review your credentials, roles, policies and permissions to validate that you are allowed to execute actions between your account and the resources involved

i have used the same credentials for doing the same action via gui and cli, but only Terraform fails. Not sure what i can do more to test my credentials. Anyway with terraform i'm able to do everything else except create this particular resource `google_iam_workload_identity_pool`

>creating a asdfasdf workload-identity-pools. With gui and cli evrything is working as expected:
@ gcloud iam workload-identity-pools create asdfasdf --location=global
Created workload identity pool [asdfasdf].

**Comment by ggtisc** [comment]
@jsecchiero set the environment variable `TF_LOG=DEBUG` and for your credentials you need to verify them as well as the IAM permissions. You can check the examples of how to use IAM roles and IAM policies in the provided links. It looks more like an IAM permissions issue.

**Comment by jsecchiero** [comment]
finally i was able to look again and I confirm that it was an oversight on my side, the module that I was using was passing specifically other credentials
