### ISSUE TITLE
Failing test(s): TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#17532]
### Impacted tests

- TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval
- TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval

### Affected Resource(s)

- google_bigquery_table

### Failure rates

- 100% since 2024-03-05

### Message(s)

```
 Error: googleapi: Error 400: Connection projects/<id>/locations/aws-us-east-1/connections/e2e_ccmv_tf_test isn't authorized to assume into your AWS IAM Role. Please check if the Role specified for the Connection is correct and is configured to include your connection's BigQuery Google identity ID. There may be a propagation delay for role assignment in AWS. If you receive an error of this type when using a new connection, waiting and trying again later may resolve the issue., invalid
```

Did we lose permissions somewhere?

### Nightly build test history

- https://hashicorp.teamcity.com/test/-5149669494455250640?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/329648573

**Comment by wj-chen** [comment]
Looking into it.

**Comment by wj-chen** [comment]
Notes have been added to b/329648573 and the missing permission was re-granted. I don't have permission to see test history so please share if the tests begin to pass again or remain failing in the next runs.

**Comment by c2thorn** [comment]
I'll check tomorrow after it runs tonight.

**Comment by c2thorn** [comment]
They both passed @wj-chen, thank you!
