### ISSUE TITLE
Failing test(s): TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#17535]
### Impacted tests

b/329686752

- TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update

### Affected Resource(s)

- google_kms_ekm_connection

### Failure rates

- 100% since 2024-03-07

### Message(s)

```
 Error: Request `Create IAM Members roles/servicedirectory.viewer serviceAccount:service-653407317329@gcp-sa-ekms.iam.gserviceaccount.com for project "650527956789"` returned error: Batch request and retried single request "Create IAM Members roles/servicedirectory.viewer serviceAccount:service-653407317329@gcp-sa-ekms.iam.gserviceaccount.com for project \"650527956789\"" both failed. Final error: Error applying IAM policy for project "650527956789": Error setting IAM policy for project "650527956789": googleapi: Error 400: Service account service-653407317329@gcp-sa-ekms.iam.gserviceaccount.com does not exist., badRequest
```

Similar error in GA tests. This test required external set up in the service team's environment (secrets, etc). Test passes in the VCR project, but looks like it was not set up correctly in the nightly projects.

### Nightly build test history

- https://hashicorp.teamcity.com/test/736084826770840719?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS

b/330375061

**Comment by c2thorn** [comment]
Checked again, they started failing again :(

**Comment by tdbhacks** [comment]
Hmm, my guess is that this is what's causing the permissions to be reset: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/kms/resource_kms_ekm_connection_test.go#L63-L72

I might be wrong though, will double-check with Risham.

**Comment by shuyama1** [comment]
Looks like this is resolved now. Closing the ticket
