### ISSUE TITLE
Error importing Cloud Armor policy into terraform

### ISSUE THREAD

**Issue by ebarrett-Ocient** [hashicorp/terraform-provider-google#17537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

```
% terraform version
Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.19.0
```

### Affected Resource(s)

google_compute_security_policy

### Terraform Configuration

```
import {
  id = REDACTED
  to = google_compute_security_policy.my_policy
}
```
Contents of `generated_resources.tf` after running `terraform apply`:

```
# __generated__ by Terraform
# Please review these resources and move them into your main configuration files.

# __generated__ by Terraform from REDACTED
resource "google_compute_security_policy" "my_policy" {
  description = null
  name        = "REDACTED"
  project     = "REDACTED"
  type        = "CLOUD_ARMOR"
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable          = true
      rule_visibility = null
    }
  }
  rule {
    action      = "allow"
    description = null
    preview     = false
    priority    = 2
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = [REDACTED]
      }
    }
  }
  rule {
    action      = "allow"
    description = null
    preview     = false
    priority    = 1
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = [REDACTED]
      }
    }
  }
  rule {
    action      = "deny(403)"
    description = "Default rule, higher priority overrides it"
    preview     = false
    priority    = 2147483647
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/ebarrett-Ocient/2cbe41e14333299c5a62b3b004629179

### Expected Behavior

I expected to be able to import an existing Cloud Armor policy into terraform without, first, terraform wanting to make updates to said policy and then failing to make those changes.

### Actual Behavior

When attempting to import this policy by running `terraform plan -generate-config-out=generated_resources.tf` and then `terraform apply`, terraform wants to update the policy in-place.

```
Terraform will perform the following actions:

  # google_compute_security_policy.my_policy will be updated in-place
  # (imported from "REDACTED")
  ~ resource "google_compute_security_policy" "my_policy" {
        fingerprint = "REDACTED"
        id          = "REDACTED"
        name        = "REDACTED"
        project     = "REDACTED"
        self_link   = "REDACTED"
        type        = "CLOUD_ARMOR"

      ~ adaptive_protection_config {
          ~ layer_7_ddos_defense_config {
                enable          = true
              + rule_visibility = "STANDARD"
            }
        }

        rule {
            action   = "allow"
            preview  = false
            priority = 2

            match {
                versioned_expr = "SRC_IPS_V1"

                config {
                    src_ip_ranges = [
                        "REDACTED",
                    ]
                }
            }
        }
        rule {
            action   = "allow"
            preview  = false
            priority = 1

            match {
                versioned_expr = "SRC_IPS_V1"

                config {
                    src_ip_ranges = [
                        "REDACTED",
                    ]
                }
            }
        }
        rule {
            action      = "deny(403)"
            description = "Default rule, higher priority overrides it"
            preview     = false
            priority    = 2147483647

            match {
                versioned_expr = "SRC_IPS_V1"

                config {
                    src_ip_ranges = [
                        "*",
                    ]
                }
            }
        }
    }
```

When I accept this update, it fails with the following error:

```
│ Error: Error updating SecurityPolicy "my_policy": googleapi: Error 400: Invalid value for field 'resource.adaptiveProtectionConfig': '{  "layer7DdosDefenseConfig": {    "enable": true,    "ruleVisibility": "STANDARD"  }}'. Cloud Armor Adaptive Protection is currently not supported for edge or network policies or backend policies attached to a TCP or SSL backend., invalid
│
│   with google_compute_security_policy.my_policy,
│   on generated_resources.tf line 5, in resource "google_compute_security_policy" "my_policy":
│    5: resource "google_compute_security_policy" "my_policy" {
```

Terraform does successfully import the policy into `generated_resources.tf` and its state file. Further attempts to run `terraform apply` result in the same error shown above.

### Steps to reproduce

1. `terraform plan -generate-config-out=generated_resources.tf`
2. `terraform apply`

**Comment by ggtisc** [comment]
The issue was replicated successfully and without errors with the provided code and the exact same command terraform `plan -generate-config-out=generated_resources.tf`. However, valid data was used for the fields marked with `REDACTED`:

```
resource "google_compute_security_policy" "my_policy" {
  description = "policy description"
  name        = "my-policy"
  type        = "CLOUD_ARMOR"
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      enable          = true
      rule_visibility = null
    }
  }
  rule {
    action      = "allow"
    description = "rule description 2"
    preview     = false
    priority    = 1
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["9.9.9.0/24"]
      }
    }
  }
  
  rule {
    action      = "deny(403)"
    description = "Default rule, higher priority overrides it"
    preview     = false
    priority    = 2147483647
    match {
      versioned_expr = "SRC_IPS_V1"
      config {
        src_ip_ranges = ["*"]
      }
    }
  }
}
```

Some points need to be clarified:

1. Import: If you enable the debug with terraform you can see that the 1st action that terraform execute is to import the policy
2. Update: Because the resource is being declared again in the terraform code it will be updated. If you want to avoid this action it's enough if you only import the resource without making any changes, and then you can use it in other resources (for example use the policy for another new resources). You can learn more about how the import works here: https://developer.hashicorp.com/terraform/language/import

Finally, about the error message you have is due to a different issue, and it is because as the message says the configuration that you are using is `not supported for edge or network policies or backend policies attached to a TCP or SSL backend.` I suggest you to look at this documentation links to be sure of how to use the resources:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy#import
https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies

**Comment by ebarrett-Ocient** [comment]
> Update: Because the resource is being declared again in the terraform code it will be updated. If you want to avoid this action it's enough if you only import the resource without making any changes, and then you can use it in other resources (for example use the policy for another new resources). You can learn more about how the import works here: https://developer.hashicorp.com/terraform/language/import

I'm not sure I follow. The only place where the resource is being declared is in `generated_resources.yml`, which is generated through `plan -generate-config-out=generated_resources.tf`. I'm not actively making any changes to the resource.

**Comment by ggtisc** [comment]
Could you please provide the `src_ip_ranges` to be sure that are valid according to the documentation specifications and according to the information in the error message?

**Comment by ebarrett-Ocient** [comment]
> Could you please provide the `src_ip_ranges` to be sure that are valid according to the documentation specifications and according to the information in the error message?

Sorry, that's probably not something I should be sharing in a public forum. What exactly are you referring to when you say "according to the information in the error message"? I don't see any mention of IP ranges causing an error.

FWIW, I was able to workaround this issue by adding the following to `google_compute_security_policy.my_policy`:

```
  lifecycle {
    ignore_changes = [adaptive_protection_config]
  }
```
After adding that, running `terraform apply` produces no changes.

**Comment by roaks3** [comment]
I think this effectively the same issue as https://github.com/hashicorp/terraform-provider-google/issues/12743, only it seems to be observed here due to the `rule_visibility = null` not being picked up.

**Comment by ebarrett-Ocient** [comment]
Following up since I see the `waiting-response` label got tagged back on this issue. Was there something else I could provide besides the `src_ip_ranges`?

**Comment by roaks3** [comment]
Sorry for the confusion. We're going to close as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12743 because they likely stem from the same root issue, and we would expect them both to be resolved by a fix.

Please leave a comment if that does not sound correct!

**Comment by ebarrett-Ocient** [comment]
Makes sense. Does appear to be the same issue.
