### ISSUE TITLE
Project sweeper can fail due to liens

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#17556]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

When the project sweeper runs it sometimes fails due to :

```
description": "A lien to prevent deletion was placed on the project by [xpn.googleapis.com]. Remove the lien to allow deletion."
```

There are tests for [the `google_resource_manager_lien` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/resource_manager_lien) (`TestAccResourceManagerLien_basic`), so those projects could be orphaned by those tests?

We could consider making the project sweeper remove liens, but it depends on our appetite for risk 🎲 

### References

Possibly related feature request: https://github.com/hashicorp/terraform-provider-google/issues/12277

**Comment by rileykarson** [comment]
This should be resolved by the sweepers eventually clearing the resources that adde the lien (host/service projects in this case) and later cleaned up w/ the project sweeper. We should ensure they're working properly, though.
