### ISSUE TITLE
Add breaking change detection for the case adding `max_size`

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#17576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Adding of `max_size` to an array is a breaking change according to the [doc](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes/), but not detected by the breaking change detector in a PR.

Example: PR https://github.com/GoogleCloudPlatform/magic-modules/pull/10193

### Potential Terraform Configuration

```tf 
```

**Comment by iyabchen** [comment]
I could take a look at the ticket.

**Comment by melinath** [comment]
I believe this would be implemented as a field-level rule: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tools/diff-processor/rules/rules_field.go

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/2132
