### ISSUE TITLE
resource_compute_(region)_instance_group_manager does have a documentation issue wrt. status.stateful message

### ISSUE THREAD

**Issue by askubis** [hashicorp/terraform-provider-google#17572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.1

### Affected Resource(s)

compute_instance_group_manager
compute_region_instance_group_manager

### Terraform Configuration

```tf
resource "google_compute_instance_group_manager" "default" {

  name               = "example-group"
  base_instance_name = "test"
  target_size        = 3
  zone               = "us-central1-f"

  version {
    instance_template = google_compute_instance_template.default.id
    name              = "primary"
  }
}
```

### Expected Behavior

tfstate should contain the status.stateful field

### Actual Behavior

tfstate should contain the status.version.stateful field

### Steps to reproduce

1. `terraform apply`

### Important Factoids

The documentation (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#version_target) is not consistent with the API (https://www.googleapis.com/discovery/v1/apis/compute/v1/rest) for no apparent reason (so in fact to fix it the documentation should be fixed)

**Comment by askubis** [comment]
I would like to fix it.

**Comment by ggtisc** [comment]
@askubis it This seems more like a documentation issue than a bug. Please confirm us if you are having an error message. 

About the `status.version.stateful` it isn't in the provided code. Could you please provide the complete code and what is the exact field that is presenting a bug?

**Comment by askubis** [comment]
@ggtisc yes, this was more of a documentation issue.
