### ISSUE TITLE
google_cloudbuild_trigger requires the property repo_type but there is no value for Bitbucket Cloud?

### ISSUE THREAD

**Issue by grzzboot** [hashicorp/terraform-provider-google#17574]
### Question

Hello,
I'm trying to create build triggers for a Bitbucket Cloud connection and repository but I'm running into some confusing behaviour. I've declared for instance the following inside my trigger as its source_to_build:

```
source_to_build {
    repository = "projects/${var.project}/locations/${var.region}/connections/bitbucket-cloud/repositories/my-repo"
    ref       = "refs/heads/master"
  }
```

But this input isn't accepted by the latest google provider (5.20.0).
The property repo_type is required for this definition to work.
But, there is no property for Bitbucket Cloud?

These are values according to the docs:
```
UNKNOWN, CLOUD_SOURCE_REPOSITORIES, GITHUB, BITBUCKET_SERVER
```

So I tried using the `UNKNOWN` variant here, and it works in the sense that the trigger is created for me.
But, the next time I run the Terraform script again it spits out that I'm trying to modify my trigger resource by adding the repo_typ `UNKNOWN`.

```
# google_cloudbuild_trigger.trigger will be updated in-place
  ~ resource "google_cloudbuild_trigger" "trigger" {
        id              = "projects/myproject/locations/region/triggers/3a334bc4-e612-4be9-9ec9-b01569638b5e"
        name            = "trigger"
        tags            = []
        # (9 unchanged attributes hidden)

      ~ git_file_source {
          + repo_type  = "UNKNOWN"
            # (3 unchanged attributes hidden)
        }

      ~ source_to_build {
          + repo_type  = "UNKNOWN"
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

So clearly the underlying platform/state did not pick up the `UNKNOWN` and I have no way of omitting it in my code since the property is required.
Can you explain how this is intended to work with 2nd gen Bitbucket Cloud connections/repos so that I can get rid of these annoying "modifications"?

**Comment by roaks3** [comment]
@grzzboot as best I can tell, this is not yet supported. For `gcloud`, for example, a new subcommand was added specifically for bitbucket cloud this January. I think that implies we would need make modifications to the provider to support this (perhaps similar to https://github.com/hashicorp/terraform-provider-google/issues/9956).

Would you mind opening a new [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.yml) to have this added?
