### ISSUE TITLE
Failing test(s): TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteCustomExample

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#17589]
### Impacted tests

- TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteCustomExample

### Affected Resource(s)

- google_artifact_registry_repository

### Failure rates

- 100% since 2024-03-07
- 100% (7 failed out of last 7 runs) as of 2024-03-14

### Message(s)

```
Error 400: Failed to validate remote upstream: failed to fetch bearer token; generic::unauthenticated: Unauthorized error returned by the external repository... this typically means your upstream credentials are invalid
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-7205822403000672123?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS

b/330175752

**Comment by rafibarash** [comment]
Hey y'all, I've been working on custom remotes. We recently added auth validation when creating Docker remote repos and the error message makes this seem related. Would you mind providing a link to this test code? Also does your test verify pulling from this remote repo works? If your test just creates the remote repo, it is possible the auth was misconfigured and this wasn't found until we added validation

**Comment by rafibarash** [comment]
Oh I forgot to mention! We added a `disable_upstream_validation` field to the create repository request that can be used to disable this validation (for instance if the test uses dummy cred values and validation is expected to fail)

Looks like the [Repository docs](https://cloud.google.com/php/docs/reference/cloud-artifact-registry/latest/V1.Repository) haven't updated with this new value, I'll look into regenerating that too

**Comment by rafibarash** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10242

**Comment by rafibarash** [comment]
Don't think I have permission to mark this as closed though
