### ISSUE TITLE
Run unit tests for tools in a PR check

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#17598]
### What kind of contribution is this issue about?

Pull request UX

### Details

Raised in https://github.com/GoogleCloudPlatform/magic-modules/pull/10199#issuecomment-1998078261

The tools in magic-modules like our issue-labeler include unit tests, but it appears that we don't run them in PR checks.

When adding these tests to a PR check, we _might_ want to make sure they only run when tools are modified (I'm not sure if they would cause noise otherwise, or if they could be impacted by other changes).

**Comment by melinath** [comment]
Note from grooming: Can we just test everything in the tools directory?
