### ISSUE TITLE
Failing test(s): TestAccDatastoreIndex_datastoreIndexExample

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#17591]
### Impacted tests

- TestAccDatastoreIndex_datastoreIndexExample

### Affected Resource(s)

- google_datastore_index

### Failure rates

- 100% since 2024-03-01
- 100% (14 failed out of last 14 runs) as of 2024-03-14

### Message(s)

```
Error 404: Project '{{REDACTED}}' does not exist.
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-4052695643890826960?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS

b/330175726

**Comment by roaks3** [comment]
This one is strange. The error is coming directly from the `google_datastore_index` resource, which does not explicitly specify a project id, and the project id in the error message appears to be for the correct project. Forwarding to the service team to weigh in.
