### ISSUE TITLE
Failing test(s): TestAccComposerEnvironment_*

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#17590]
### Impacted tests

- TestAccComposerEnvironmentAirflow2_withSoftwareConfig
- TestAccComposerEnvironmentComposer1_private
- TestAccComposerEnvironment_basic
- TestAccComposerEnvironment_*
14 tests in total

### Affected Resource(s)

- google_composer_environment

### Failure rates

- 100% since 2024-02-28
- 100% (15 failed out of last 15 runs) as of 2024-03-14

### Message(s)

```
          1) Cloud Composer 1 is not supported in the selected region 'us-central1'. Based on your input: 'composer-1-airflow-2' you want to create Composer 1 environment. Currently suggested new environment image versions are: [composer-3-airflow-2.6.3, composer-3-airflow-2.5.3, composer-2.6.2-airflow-2.6.3, composer-2.6.2-airflow-2.5.3]., badRequest

```

### Nightly build test history

https://hashicorp.teamcity.com/test/-6915189059560242933?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryInvestigationsSection=true

b/330175355

**Comment by rileykarson** [comment]
These tests are largely passing now.
