### ISSUE TITLE
Add support for vacation start / end dates to reviewer assignment

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17602]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

Currently we allow core contributors to say that they are / are not on vacation; however, this means the they have to do the PR to set up the vacation immediately before leaving and have to remember to undo it afterwards; we should instead support a date range.

**Comment by iyabchen** [comment]
I can take over this one.

**Comment by melinath** [comment]
Vacation logic is defined in [AvailableReviewers](https://github.com/GoogleCloudPlatform/magic-modules/blob/f9a432f23c7ecd3eb75806b3087e572e667dc65d/.ci/magician/github/membership.go#L118C6-L118C24) - folks will still need to check in code to say what the start / end dates should be.
