### ISSUE TITLE
google_cloud_run_v2_service container order changes

### ISSUE THREAD

**Issue by ggorge-etiqa** [hashicorp/terraform-provider-google#17615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.20.0

### Affected Resource(s)

google_cloud_run_v2_service

### Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "this" {
  name     = var.service_name

  template {
    service_account = google_service_account.service_account.email

    execution_environment = "EXECUTION_ENVIRONMENT_GEN1"


    dynamic "containers" {
      for_each = var.containers_definition

      content {
        name  = containers.key
        image = containers.value.container_image
        
        [...]
      }
    }
   
   }
   
}
```

```tf
  containers_definition = {

    nginx-1 = {
      container_image           = "us-west1-docker.pkg.dev/prj/repo/my-nginx:latest"
      container_port            = 8000
    }

    be-1 = {
      container_image = "us-west1-docker.pkg.dev/prj/repo/my-be:latest"

    }
}
```      

### Expected Behavior

no changes in plan

### Actual Behavior

Terraform plan shows that a change should be performed:
```
         ~ containers {
              ~ image      = "us-west1-docker.pkg.dev/prj/repo/my-nginx:latest" -> "us-west1-docker.pkg.dev/prj/repo/my-be:latest"
              ~ name       = "nginx-1" -> "be-1"
[...]

         ~ containers {
              ~ image      = "us-west1-docker.pkg.dev/prj/repo/my-be:latest" -> "us-west1-docker.pkg.dev/prj/repo/my-nginx:latest"
              ~ name       = "be-1" -> "nginx-1"
[...]
```

### Steps to reproduce

1. `terraform plan`

**Comment by ggtisc** [comment]
Hi @ggorge-etiqa your issue isn't clear at all could you provide more information?

1. Does the resource already exists?
2. Is it a new resource or an update?
3. Please provide more information of how this issue is presented (for example: when I'm trying to create a `google_cloud_run_v2_service` it updates my existing containers)

**Comment by ggorge-etiqa** [comment]
Hi @ggtisc , it's a `terraform plan` after the first `terraform apply`.

Said that, I think my problem is that my `var.containers_definition` variable is a `map` and maps are not ordered. So basically seems the `for_each = var.containers_definition` order can change on each run.

Changin `var.containers_definition` to a `list` seems fixing the issue.

**Comment by ggtisc** [comment]
Yeah, as you said. That information is also relevant to work on issues because are internal configurations that only you can see. Please confirm if everything works now for you.
