### ISSUE TITLE
google_compute_disk does not allow SEV_LIVE_MIGRATABLE_V2 for guest_os_features type

### ISSUE THREAD

**Issue by fijimunkii** [hashicorp/terraform-provider-google#17628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/google v5.21.0
+ provider registry.terraform.io/hashicorp/google-beta v5.21.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

google_compute_disk

### Terraform Configuration

```tf
resource "google_compute_disk" "boot" {
  image                    = var.image
  provider                 = google
  project                  = var.gcp_project
  count                    = local.instance_count
  name                     = "abcd-boot-disk"
  type                     = var.type
  zone                     = var.zone
  size                     = var.size
  labels                   = var.labels
  interface                = var.interface
  dynamic "guest_os_features" {
    for_each = ["UEFI_COMPATIBLE","SEV_CAPABLE","SEV_LIVE_MIGRATABLE","SEV_LIVE_MIGRATABLE_V2"]
    content {
      type = guest_os_features.value
    }
  }
}
```

### Expected Behavior

The resource gets created with the SEV_LIVE_MIGRATABLE_V2 attribute set (see the [reference](https://cloud.google.com/compute/docs/reference/rest/beta/disks))

### Actual Behavior

```
Error: expected guest_os_features.2.type to be one of [MULTI_IP_SUBNET SECURE_BOOT SEV_CAPABLE UEFI_COMPATIBLE VIRTIO_SCSI_MULTIQUEUE WINDOWS GVNIC SEV_LIVE_MIGRATABLE SEV_SNP_CAPABLE SUSPEND_RESUME_COMPATIBLE TDX_CAPABLE], got SEV_LIVE_MIGRATABLE_V2

  on modules/gce_confidential/main.tf line 123, in resource "google_compute_disk" "boot":
 123: resource "google_compute_disk" "boot" {
```

### Steps to reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

- [GCP documentation for attribute guestOsFeatures[].type](https://cloud.google.com/compute/docs/reference/rest/beta/disks)

b/330393518

**Comment by ggtisc** [comment]
@roaks3 Issue confirmed! As the provided link says https://cloud.google.com/compute/docs/reference/rest/beta/disks `SEV_LIVE_MIGRATABLE_V2` is valid, but it rise an error message after `terraform apply`
