### ISSUE TITLE
Support for custom instance config in spanner

### ISSUE THREAD

**Issue by ns-nirmal** [hashicorp/terraform-provider-google#17632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Currently we can create a spanner instance with the [google_spanner_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_instance.html) resource. But we do not have the option to select the optional read-only regions here. We need to create a custom instance configuration for this and then use it to create the instance. 
Creating a custom instance configuration - https://cloud.google.com/spanner/docs/create-manage-configurations#create-configuration

This enhancement request is to add support for creating this custom instance configuration through terraform.

Google cloud resource: https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instanceConfigs

### New or Affected Resource(s)

* google_spanner_instance_config

### Potential Terraform Configuration

```tf 
resource "google_spanner_instance_config" "example" {
    name          = "custom_ eur5_example_config"
    display_name  = "Test Spanner Instance Config"
    configType    = "USER_MANAGED"
    baseConfig    = "eur4"
    replicas      = [
      {
        "location" : "europe-west2",
        "type" : "READ_WRITE",
        "defaultLeaderLocation" : true
      },
      {
        "location" : "europe-west2",
        "type" : "READ_WRITE"
      },
      {
        "location" : "europe-west1",
        "type" : "READ_WRITE"
      },
      {
        "location" : "europe-west1",
        "type" : "READ_WRITE"
      },
      {
        "location" : "europe-west4",
        "type" : "WITNESS"
      },
      {
        "location" : "us-east1",
        "type" : "READ_ONLY"
      }
    ]
    labels        = {
      "foo" = "bar"
    }
}
```

b/330932684

**Comment by alethenorio** [comment]
Something else to think of here is that applying this config to an existing instance causes Terraform to want to recreate the instance. This is technically not needed as one can [move the instance](https://cloud.google.com/spanner/docs/move-instance#gcloud-cli) to the new config instead.

It would be great if either a new resource could support this use case or if changing the instance config would just call this API instead of forcing a recreate of the resource
