### ISSUE TITLE
Resource `google_compute_target_https_proxy` fails to update certificates with `certificate_manager_certificates` attribute

### ISSUE THREAD

**Issue by K3nks** [hashicorp/terraform-provider-google#17641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

1.5.1

### Affected Resource(s)

`google_compute_target_https_proxy`

### Terraform Configuration

```tf

  internal_loadbalancer_config = {
    ssl_certs            = ["certname1", "certname2", "certname3"] 
  }


locals {
  ssl_cert_list = [for cert in var.internal_loadbalancer_config.ssl_certs : "//certificatemanager.googleapis.com/projects/${var.project_id}/locations/global/certificates/${cert}"]
}


resource "google_compute_target_https_proxy" "ilb-target-proxy" {
  name                             = "${var.env}-ilb-target-https-proxy"
  project                          = var.project_id
  url_map                          = google_compute_url_map.ilb-url-map.id
  certificate_manager_certificates = local.ssl_cert_list


}

```

### Expected Behavior

The target proxy certificates are updated from certificate_manager_certificates

### Actual Behavior

The update of certificates on `google_compute_target_https_proxy` from certificate_manager_certificates fails

````
module.test.google_compute_target_https_proxy.ilb-target-proxy: Modifying... [id=projects/gcp-project-id/global/targetHttpsProxies/test-lb-target-https-proxy]
╷
│
 
Error: 
Error updating TargetHttpsProxy "projects/gcp-project-id/global/targetHttpsProxies/test-lb-target-https-proxy": googleapi: Error 41
2: Certificate Map or at least 1 SSL certificate must be specified for setting SSL certificates in TargetHttpsProxy., conditionNotMet
│ 
│   with module.test.google_compute_target_https_proxy.ilb-target-proxy,
│   on ../modules/test/load-balancer.tf line 80, in resource "google_compute_target_https_proxy" "ilb-target-proxy":
│   80: resource "google_compute_target_https_proxy" "ilb-target-proxy" {
````

### Steps to reproduce

1. `terraform apply`

### Important Factoids

Using `google` provider version `5.21.0`

### References

The above terraform configuration is based on the documented example in the provider documentation:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_https_proxy#example-usage---target-https-proxy-certificate-manager-certificate

b/331207883

**Comment by ggtisc** [comment]
Hi @K3nks as the error says: `**Certificate Map** or at least 1 SSL certificate must be specified for setting SSL certificates in TargetHttpsProxy., conditionNotMet` you need to specify a Map, but you are assigning a list... So you need to change it for a map. You can follow the next guide to achieve this and learn more about terraform data types: https://developer.hashicorp.com/terraform/language/expressions/types#map

**Comment by K3nks** [comment]
> Hi @K3nks as the error says: `**Certificate Map** or at least 1 SSL certificate must be specified for setting SSL certificates in TargetHttpsProxy., conditionNotMet` you need to specify a Map, but you are assigning a list... So you need to change it for a map. You can follow the next guide to achieve this and learn more about terraform data types: https://developer.hashicorp.com/terraform/language/expressions/types#map

The documentation specifies a List:
```
resource "google_compute_target_https_proxy" "default" {
  name                             = "target-http-proxy"
  url_map                          = google_compute_url_map.default.id
  certificate_manager_certificates =  ["//certificatemanager.googleapis.com/${google_certificate_manager_certificate.default.id}"] # [google_certificate_manager_certificate.default.id] is also acceptable
}
```

From the error it seems its expecting a `google_certificate_manager_certificate_map` or `ssl_certificates`

**Comment by ggtisc** [comment]
@K3nks could you please provide a link to verify this information?

**Comment by K3nks** [comment]
Its in the Provider Documentation here? 
[https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_https_proxy#example-usage---target-https-proxy-certificate-manager-certificate](url)

**Comment by ggtisc** [comment]
After checking the documentation [link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_https_proxy#certificate_manager_certificates) it specify a format for the `certificate_manager_certificates`, but never specify if it require a map or a list when the need is to add more than just 1 certificate according to the error: `Certificate Map or at least 1 SSL certificate must be specified for setting SSL certificates in TargetHttpsProxy., conditionNotMet` So this could be probably a documentation issue.

**Comment by melinath** [comment]
Note from triage: This is a bug, not a documentation issue. "Certificate Map" does not indicate that the _value_ should be a map; rather, certificateMap is another field on this resource (referencing a CertificateMap API field.) certificate_manager_certificates is actually sent to the API in the sslCertificates field, so this configuration _should_ result in the correct API resource being created (or updated.) Something is going wrong here and will need to be investigated further. attn @ggtisc

**Comment by Hamzawy63** [comment]
This is a bug and will be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10261

>certificate_manager_certificates is actually sent to the API in the sslCertificates field, so this configuration should result in the correct API resource being created (or updated.) 

Yes, and this conversion is done using a custom_encoder that should be triggered to modify both the creation request and the update request. However, for `TargetHttpsProxy` and `RegionTargetHttpsProxy` resources, the encoder is not executed during the update phase. This is probably because those resources are uncommon case where the entire resource is [marked as immutable](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fmagic-modules%2Fblob%2Fd874e11de524dddb932b70f4ef1bc7905fb41846%2Fmmv1%2Fproducts%2Fcompute%2FRegionTargetHttpsProxy.yaml%23L18), but it has a [field-specific update](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fmagic-modules%2Fblob%2Fd874e11de524dddb932b70f4ef1bc7905fb41846%2Fmmv1%2Fproducts%2Fcompute%2FRegionTargetHttpsProxy.yaml%23L130) that overrides that

yaqs/2098594962982567936
