### ISSUE TITLE
A few small, but critical typos on documentation for `google_pubsub_subscription`

### ISSUE THREAD

**Issue by lazarillo** [hashicorp/terraform-provider-google#17645]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Not relevant

### Affected Resource(s)

`google_pubsub_subscription`

### Terraform Configuration

Not relevant

### Debug Output

Not relevant

### Expected Behavior

I expect that the syntax for a BigQuery table on the [google_pubsub_subscription](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription) is accurate.  I have now learned that syntax in the document is incorrect, and it should match the syntax usually used by Google Cloud:

`<project>:<dataset>.<table>`

Note how the first separator is a colon and the second separator is a period.

The documentation _usually, but not always_ uses a period for both, such as:

```tf
  bigquery_config {
    table = "${google_bigquery_table.test.project}.${google_bigquery_table.test.dataset_id}.${google_bigquery_table.test.table_id}"
  }
```

### Actual Behavior

As described above, the actually behavior is that the documentation sometimes accidentally uses a period for both separators.

### Steps to reproduce

visit
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription
and read the documentation for bigquery subscriptions.

b/330757367

**Comment by ggtisc** [comment]
@rileykarson this is a issue to improve the documentation, as the user says there are differences in some parts of the documentation where the structure to declare a `bigquery_config` use this `<project>.<dataset>.<table>` instead of this `<project>:<dataset>.<table>`. 

Links:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#bigquery_config
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#nested_bigquery_config

**Comment by jhuang-g** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/7410#issuecomment-1458827612 here is where the decision to change : to . was made. I think this means our documentation is correct and there is no typo.

**Comment by jhuang-g** [comment]
@NickElliot Could this be closed out?
