### ISSUE TITLE
google_active_folder behavior changed requring extra permissions

### ISSUE THREAD

**Issue by jsachnet** [hashicorp/terraform-provider-google#17677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

v1.7.5

### Affected Resource(s)

google_active_folder

### Terraform Configuration

```tf
variable "org_domain" {
  description = "The GCP organization domain name. The team group emails will be part of the org"
  type        = string
  default     = "domain.com"
}

data "google_organization" "org" {
  domain = var.org_domain
}

data "google_active_folder" "team_folder" {
  display_name = local.team_folder_display_name
  parent       = data.google_organization.org.name
}

resource "google_folder" "product_folder" {
  display_name = local.product_name
  parent       = data.google_active_folder.team_folder.name
}
```

### Debug Output

Error: error reading folder list: googleapi: Error 403: Permission 'resourcemanager.folders.list' denied on resource '//cloudresourcemanager.googleapis.com/organizations/redacted' (or it may not exist).
Details:
```
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "cloudresourcemanager.googleapis.com",
    "metadata": {
      "permission": "resourcemanager.folders.list",
      "resource": "organizations/redacted"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
```
, forbidden

  on .terraform/modules/product/products/factory/folder_product.tf line 5, in data "google_active_folder" "team_folder":
   5: data "google_active_folder" "team_folder" {

### Expected Behavior

Get an active folder with the organization without requiring `resourcemanager.folders.list` on the parent object

### Actual Behavior

As of v4.22.0 you now need `resourcemanager.folders.list` on the parent object. This change was not documented

### Steps to reproduce

1. `terraform plan`

### Important Factoids

Upgrading from an old version of the google provider to the latest v5.21.0 and my existing TF is now requiring additional permissions that were not required in the past. In version v4.21.0 and lower of the provider the module is doing a folder search. This was changed in v4.22.0 and the module is now doing a folder list. This change in behavior is not mentioned in the changelog for v4.22.0. My organization doesn't grant `resourcemanager.folders.list` on the folder that I need to reference as the parent of the folder that I do have `resourcemanager.folders.list` on.
```
Folder                resourcemanager.folders.list

org.com                no
 |- gcp-org-team       yes
```

### References

https://github.com/hashicorp/terraform-provider-google/blob/release-4.21.0/google/data_source_google_active_folder.go
https://github.com/hashicorp/terraform-provider-google/blob/release-4.22.0/google/data_source_google_active_folder.go
https://github.com/hashicorp/terraform-provider-google/blob/release-4.22.0/CHANGELOG.md

**Comment by ScottSuarez** [comment]
We switched to LIST over SEARCH because SEARCH was eventually consistent while LIST maintains strong consistently. 
https://github.com/GoogleCloudPlatform/magic-modules/pull/5989

We often don't document such changes when they don't have user facing impact. This was our mistake in not realizing there was, as in this case. IAM is a tricky beast. If you would like to contribute to this resource you could add new field, mode or the like, to the resource with default behavior being the current behavior.

**Comment by ScottSuarez** [comment]
I had some time today so [I've added](https://github.com/GoogleCloudPlatform/magic-modules/pull/10439) the field `rest_method` to datasource `google_active_folder` so you can use either `SEARCH` or `LIST` to find your folder.

**Comment by jsachnet** [comment]
@ScottSuarez this is awesome. Thank you!
