### ISSUE TITLE
Using `default_labels` on Google Terraform provider forces replacement of `google_datastream_private_connection`

### ISSUE THREAD

**Issue by darraghcopley** [hashicorp/terraform-provider-google#17670]
Using default_labels on Google Terraform provider (5.21.0) forces replacement of `google_datastream_private_connection`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

1.7.4

### Affected Resource(s)

`google_datastream_private_connection`

### Terraform Configuration

```tf
resource "google_datastream_private_connection" "read_replicas_private_connection" {
  display_name          = "Datastream ${var.gcp_project_id} with SVPC"
  location              = var.region
  private_connection_id = "datastream-peering-${var.gcp_project_id}-svpc"

  vpc_peering_config {
    vpc    = var.datastream_vpc
    subnet = var.datastream_peering_subnet
  }
}
```

```tf
provider "google" {
  region         = var.region
  project        = var.gcp_project_id
  default_labels = {
    test_label = "test_val_to_force_replacement"
  }
}
```

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.21.0"
    }
  }
}
```

### Expected Behavior

The resource should be updated in place and not need to be recreated in order to add labels to it

### Actual Behavior

<img width="1424" alt="Screenshot 2024-03-25 at 16 00 36" src="https://github.com/hashicorp/terraform-provider-google/assets/41948807/14daa61e-b81d-452a-8d6a-88754a2c6fae">

As seen in the plan, the labels, as expected, are to be applied on every resource created via the provider. However, on the resource `google_datastream_private_connection` it forces a replacement due to the `effective_labels` attribute

### Steps to reproduce

1. `terraform plan`

b/331218290

**Comment by ggtisc** [comment]
Confirmed issue after replication! This may be an enhancement because there is no error message but as it seems when the `default_labels `were added it attempts to destroy the existing resources and replace with new ones instead of only update the existing resources.

**Comment by darraghcopley** [comment]
Thanks for the quick reply @ggtisc ! Understood rgd enhancement over bug. I do think this is not expected behaviour however. Destroying and recreating the resource would cause quite some issues for other Datastream resources depending on it

**Comment by zli82016** [comment]
As the resource `google_datastream_private_connection` doesn't support in-place update in API, the resource has to be recreated to add default labels on the field `effective_labels`.

**Comment by zli82016** [comment]
The behavior is expected. Feel free to reopen it if there are any questions.
