### ISSUE TITLE
Add support for checkIfServiceHasUsage to `google_project_service`

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#17686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

This would be opt-in in `5.X` (i.e. default to `SKIP`, the current behaviour), but we could consider flipping the default in `6.0.0` to prevent users from disabling in-use services. This came up as desirable in a conversation w/ Composer, where environments were left broken as a result of disabling the still-active service.

We should likely include the field set to `CHECK` in our example usage regardless of the default status- that'll provide additional safety for users who have not considered all possible values for the resource & minimally modify the example.

We should consider adding the standard `_on_destroy` suffix to the field that we tend to use for values specific to destroy, implying a full name of `check_if_service_has_usage_on_destroy`. That's not consistent with its sibling (`disable_dependent_services`) but the context on that one is more clear, and it predates the pattern.

### New or Affected Resource(s)

* google_project_service

### Potential Terraform Configuration

```tf 
resource "google_project_service" "project" {
  project = "your-project-id"
  service = "iam.googleapis.com"

  check_if_service_has_usage_on_destroy = "CHECK"
  disable_dependent_services = true
}
```

b/331417946

**Comment by SarahFrench** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10973
