### ISSUE TITLE
Alert provider maintainers about releases Monday

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#17680]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

After a likely miss on releasing `5.22.0` today, let's improve the automation on releases.

Keeping the process at https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process in mind, I propose a script that does the following:

- At 9:30am PST check the releases list for both providers. If no release has been made that day for either one (this is the expected case, although non-PST folks may have done earlier), ping the `terraform-team-external` chat and ask for acknowledgement from the release shepherd.
- At 11:00am PST, check the releases list for both providers. If either provider has not had a release cut, follow up on the earlier thread and request a release is made.

I don't think we need to account for holidays or major releases, as we can just have a human comment on the thread that a release is not expected at these times.

**Comment by roaks3** [comment]
This is mostly done, just watching to make sure it is working as expected, and will follow up with some light documentation for maintenance.

**Comment by roaks3** [comment]
Looks good after second week. Marking as resolved, and the documentation will be added in the next day or two.
