### ISSUE TITLE
Make GCB downstream builder job fail if a commit creation error occurs

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#17702]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

In a recent downstream build job, we've seen downstream generation step silently swallowed a commit creation error `Error creating commit:  path error running git: fork/exec /usr/bin/git: argument list too long` without causing the builder job to fail. [GCB link](https://console.cloud.google.com/cloud-build/builds/65a2ed1c-a1f6-4b7a-943e-ad8ab45591d8;step=5?e=-13802955&mods=logs_tg_staging&project=graphite-docker-images)

This behavior may have been intentional, given that certain PRs do not generate any downstream changes and [Magician](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/magician/cmd/generate_downstream.go#L138) returns errors in such scenarios. However, we need to find a way to distinguish between instances where no downstream commits should be generated and actual generation errors. For the latter, we should ensure the build job fails accordingly.

**Comment by melinath** [comment]
Note from grooming: We could potentially check the error code from making the commit, or check whether there are any diffs prior to attempting to make a commit (so that we don't have to ignore empty commit failures)

**Comment by iyabchen** [comment]
I can take this ticket.
