### ISSUE TITLE
 The terraform-provider-google_v5.21.0_x5 plugin crashed! panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by rachelgagnon** [hashicorp/terraform-provider-google#17708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.5
terraform-provider-google v5.21.0

### Affected Resource(s)

resource "google_bigquery_table" "table" {
  dataset_id               = var.table.dataset_id
  table_id                 = var.table.table_id
  description              = var.table.description
  deletion_protection      = try(var.table.deletion_protection, null) != null ? var.table.deletion_protection : false
  schema                   = templatefile("${var.table.schema_path}", local.policy_map)
  require_partition_filter = try(var.table.require_partition_filter, null) != null ? var.table.require_partition_filter : false
  labels                   = try(var.table.labels, {})

  time_partitioning {
    type  = var.table.time_partitioning.type
    field = var.table.time_partitioning.field
  }

  table_constraints {
    primary_key {
      columns = split(",", var.table.primary_key.columns)
    }
  }
}

resource "google_bigquery_table" "historical_view" {
  dataset_id               = try(var.table.historical_view.dataset_id, null) != null ? var.table.historical_view.dataset_id : var.table.dataset_id
  table_id                 = var.table.historical_view.view_id
  deletion_protection      = try(var.table.historical_view.deletion_protection, null) != null ? var.table.historical_view.deletion_protection : false
  require_partition_filter = false

  view {
    use_legacy_sql = try(var.table.historical_view.use_legacy_sql, null) != null ? var.table.historical_view.use_legacy_sql : false
    query          = try(var.table.historical_view.query, null) != null ? var.table.historical_view.query : "WITH data AS (SELECT row_number() OVER (partition BY ${var.table.primary_key.columns} ORDER BY ${var.table.time_partitioning["field"]} DESC) AS _row, * FROM `${google_bigquery_table.table.project}.${var.table.dataset_id}.${var.table.table_id}`) SELECT * EXCEPT (_row) FROM data WHERE _row = 1"
  }

  depends_on = [
    google_bigquery_table.table
  ]
}

resource "google_bigquery_table" "transactional_view" {
  dataset_id               = try(var.table.transactional_view.dataset_id, null) != null ? var.table.transactional_view.dataset_id : var.table.dataset_id
  table_id                 = var.table.transactional_view.view_id
  deletion_protection      = try(var.table.transactional_view.deletion_protection, null) != null ? var.table.transactional_view.deletion_protection : false
  require_partition_filter = false

  view {
    use_legacy_sql = try(var.table.transactional_view.use_legacy_sql, null) != null ? var.table.transactional_view.use_legacy_sql : false
    query          = try(var.table.transactional_view.query, null) != null ? var.table.transactional_view.query : "WITH data AS (SELECT row_number() OVER (partition BY ${var.table.primary_key.columns} ORDER BY ${var.table.time_partitioning["field"]} DESC) AS _row, * FROM `${google_bigquery_table.table.project}.${var.table.dataset_id}.${var.table.table_id}`) SELECT * EXCEPT (_row) FROM data WHERE _row = 1 AND _cdc_id != 'DELETE'"
  }

  depends_on = [
    google_bigquery_table.table
  ]
}

### Terraform Configuration

```tf
```

### Expected Behavior

apply should've been successful - plan looks exactly as intended

### Actual Behavior

panic: interface conversion: interface {} is nil, not string

goroutine 2993 [running]:
[github.com/hashicorp/terraform-provider-google/google/services/bigquery.expandPrimaryKey(..](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery.expandPrimaryKey%28..).)
[github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:2345](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:2345)
[github.com/hashicorp/terraform-provider-google/google/services/bigquery.expandTableConstraints({0x3535e40](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery.expandTableConstraints%28%7B0x3535e40)?, 0xc00212cea0?})
[github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:2463](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:2463) +0x43f
[github.com/hashicorp/terraform-provider-google/google/services/bigquery.resourceTable(0x3da6324](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery.resourceTable%280x3da6324)?, {0x3d74480?, 0xc000368a80?})
[github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:1398](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:1398) +0xc98
[github.com/hashicorp/terraform-provider-google/google/services/bigquery.resourceBigQueryTableCreate(0x0](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery.resourceBigQueryTableCreate%280x0)?, {0x3d74480?, 0xc000368a80})
[github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:1421](http://github.com/hashicorp/terraform-provider-google/google/services/bigquery/resource_bigquery_table.go:1421) +0xf8
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x44e5c58](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*Resource%29.create%280x44e5c58)?, {0x44e5c58?, 0xc0020493b0?}, 0xd?, {0x3d74480?, 0xc000368a80?})
[github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766) +0x178
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000fa4620](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*Resource%29.Apply%280xc000fa4620), {0x44e5c58, 0xc0020493b0}, 0xc001f93d40, 0xc00186b080, {0x3d74480, 0xc000368a80})
[github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909) +0xa7e
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00118c0d8](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*GRPCProviderServer%29.ApplyResourceChange%280xc00118c0d8), {0x44e5c58?, 0xc002049290?}, 0xc00083fbd0)
[github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074) +0xe8d
[github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x44e5bb0](http://github.com/hashicorp/terraform-plugin-mux/tf5muxserver.%28*muxServer%29.ApplyResourceChange%280x44e5bb0)?, {0x44e5c58?, 0xc002048f60?}, 0xc00083fbd0)
[github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ApplyResourceChange.go:36](http://github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ApplyResourceChange.go:36) +0x1b5
[github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0004f2500](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.%28*server%29.ApplyResourceChange%280xc0004f2500), {0x44e5c58?, 0xc002048750?}, 0xc001fe4a80)
[github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859](http://github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859) +0x574
[github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x3d120c0](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler%28%7B0x3d120c0)?, 0xc0004f2500}, {0x44e5c58, 0xc002048750}, 0xc00186ac80, 0x0)
[github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503](http://github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503) +0x170
[google.golang.org/grpc.(*Server).processUnaryRPC(0xc001270000](http://google.golang.org/grpc.%28*Server%29.processUnaryRPC%280xc001270000), {0x44e5c58, 0xc0020486c0}, {0x44efbf8, 0xc00118eea0}, 0xc002058240, 0xc0012743c0, 0x5eb7f98, 0x0)
[google.golang.org/grpc@v1.61.1/server.go:1385](http://google.golang.org/grpc@v1.61.1/server.go:1385) +0xe49
[google.golang.org/grpc.(*Server).handleStream(0xc001270000](http://google.golang.org/grpc.%28*Server%29.handleStream%280xc001270000), {0x44efbf8, 0xc00118eea0}, 0xc002058240)
Error: The terraform-provider-google_v5.21.0_x5 plugin crashed!

### Steps to reproduce

to reproduce, run terraform plan and terraform apply on the total volume of files. pipeline is running in Azure Dev Ops for deployment

**Comment by slevenick** [comment]
Looks like it's due to an empty string being passed to primary_key. Workaround is to not set an empty string there, but we should still solve this crash
