### ISSUE TITLE
google_bigquery_routine creates SQL procedures incorrectly if parameters are declared in the statement

### ISSUE THREAD

**Issue by peter-gergely-horvath** [hashicorp/terraform-provider-google#17716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.6.6
on windows_amd64                                                                    
+ provider registry.terraform.io/hashicorp/google v5.22.0                           
+ provider registry.terraform.io/hashicorp/google-beta v5.22.0                      
+ provider registry.terraform.io/hashicorp/random v3.6.0     

### Affected Resource(s)

google_bigquery_routine

### Terraform Configuration

```tf
resource "google_bigquery_routine" "procedures" {
  project    = var.project_name
  dataset_id = "sample"

  routine_id = "foobar"

  routine_type = "PROCEDURE"
  language     = "SQL"

  description     = "Sample procedure"
  definition_body = <<EOT
CREATE OR REPLACE PROCEDURE sample.foobar(msg1 string, msg2 string)
BEGIN

    BEGIN TRANSACTION;

    select CONCAT(msg1, " ", msg2);

    COMMIT;
END;

EOT
}

```

### Expected Behavior

The provider should create a procedure that matches the signature specified in the SQL definition, including parameters, just like the examples shows for SQL FUNCTIONs in [Example Usage - Bigquery Routine Basic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine#example-usage---bigquery-routine-basic), where [arguments](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine#arguments) are NOT SPECIFIED explicitly, but are taken from the SQL statement.

```
resource "google_bigquery_routine" "sproc" {
  dataset_id = google_bigquery_dataset.test.dataset_id
  routine_id     = "routine_id"
  routine_type = "PROCEDURE"
  language = "SQL"
  definition_body = "CREATE FUNCTION Add(x FLOAT64, y FLOAT64) RETURNS FLOAT64 AS (x + y);"
}
```

The behavior shown for creating a FUNCTION should also apply to SQL PROCEDURES as well.

### Actual Behavior

The provider creates a parameter-less stored procedure that contains the DDL statement inside.
The procedure is not executable with the expected signature. Executing the procedure drops the procedure and might re-create the same procedure.

### Steps to reproduce

1. Create a sample Dataset in BigQuery
2. Create a TF config, add the example from above
3. `terraform apply` to create the procedure.
4. Inspect the procedure: no arguments are known to the system
5. Try to run the procedure: it will either not run or it will drop-create itself

**Comment by slevenick** [comment]
Unfortunately I don't think that we can fix this from the provider-side. It seems the issue you describe is with the data plane rather than the control plane. In other words, the procedure may not be created successfully in the routine, but from Terraform's point of view everything is fine. We don't want to get into the business of debugging procedures from Terraform, and from what I can see we send the correct payload and that payload is being stored and returned correctly by the API.

I would suggest bringing this up to the BigQuery product team directly via their [issue tracker](https://cloud.google.com/support/docs/issue-trackers)
