### ISSUE TITLE
google_service_account_iam_member does not support a members list

### ISSUE THREAD

**Issue by TwiggyWan** [hashicorp/terraform-provider-google#17728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Hello

When I read [google_service_account_iam_member documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#google_service_account_iam_member)  it states : 

> [member/members](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#member/members) - (Required) Identities that will be granted the privilege in role. 

But up on planning the potential terraform configuration given below I get errors : 
```
`│ Error: Missing required argument
│ 
│   in resource "google_service_account_iam_member" "foo":
│ 
│ The argument "member" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on iam_dse_sa.tf line 24, in resource "google_service_account_iam_member" "foo":
│   24:   members = [
│ 
│ An argument named "members" is not expected here. Did you mean "member"?
```

Sure enough resource_iam_XXX  use different schemas : 
https://github.com/hashicorp/terraform-provider-google/blob/6cd9e805ae13dbdf162b63b16bf4254165ac1ea9/google/tpgiamresource/resource_iam_member.go#L48

https://github.com/hashicorp/terraform-provider-google/blob/6cd9e805ae13dbdf162b63b16bf4254165ac1ea9/google/tpgiamresource/resource_iam_binding.go#L19

Looks to me like either the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#member/members) is wrong, or the resource_iam_member.go ` schema should use the `members` part just like in  `resource_iam_binding.go` . 

I did not know if this was bug or enhancement as I could simply duplicate my resource to achieve the desired effect.

Thanks. 

### New or Affected Resource(s)

* google_service_account_iam_member

### Potential Terraform Configuration

```tf 
resource "google_service_account_iam_member" "foo" {

  service_account_id = bar
  role               = "roles/iam.serviceAccountUser"
  members = [
    "user:johndoe@gmail.com",
    "group:beatles@gmail.com"
  ]
}
```

**Comment by slevenick** [comment]
It looks like the google_service_account_iam_member supports the `member` field in the same way that other IAM resources do. See [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance_iam#google_notebooks_instance_iam_member) for an example of another IAM resource.

Are you looking for the _iam_binding resource that allows you to specify a list of members? _iam_member is for a specific one member to permission pair, while _iam_binding manages a single permission and all members that have that permission.

**Comment by slevenick** [comment]
It is documented a little confusingly, but _iam_member resources only support the `member` field, while _iam_binding resources only support the `members` array. It's a little tricky to document different schemas on the same page, which is why it's documented as `member/members`
