### ISSUE TITLE
Add Terraform Support for Google Sensitive Data Protection Discovery Configs

### ISSUE THREAD

**Issue by yu-iskw** [hashicorp/terraform-provider-google#17749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Request to add Terraform support for configuring Google Sensitive Data Protection's Discovery Configs (organizations.locations.discoveryConfigs) across different levels: organization, folder, and project. This feature would allow users to automate the setup and management of sensitive data discovery settings within their Google Cloud environments using Terraform, enhancing security and compliance.

### New or Affected Resource(s)

* `google_sdp_discovery_config`

## 1. Configuration for an Organization:

```tf 
resource "google_sdp_discovery_config" "org_example" {
  name         = "org-example-config"
  display_name = "Organization Level Discovery Config"

  org_config {
    location {
      organization_id = "123456789012"  // Replace with your organization ID
    }
    project_id = "project-to-run-scan"
  }

  inspect_templates = ["projects/my-project/inspectTemplates/template-id"]
  actions {
    // Configuration for actions like export data or Pub/Sub notifications
  }
  targets {
    // Configuration for discovery targets
  }
  errors {
    // Error handling configuration
  }
}
```

## 2. Folder-Level Configuration:

```tf
resource "google_sdp_discovery_config" "folder_example" {
  name         = "folder-example-config"
  display_name = "Folder Level Discovery Config"

  org_config {
    location {
      folder_id = "folders/123456789012"  // Replace with your folder ID
    }
    project_id = "project-to-run-scan"
  }

  inspect_templates = ["projects/my-project/inspectTemplates/template-id"]
  actions {
    // Configuration for actions
  }
  targets {
    // Configuration for discovery targets
  }
  errors {
    // Error handling configuration
  }
  status = "RUNNING"
}
```

## 3. Project-Level Configuration:

```tf
resource "google_sdp_discovery_config" "project_example" {
  name         = "project-example-config"
  display_name = "Project Level Discovery Config"

  org_config {
    project_id = "your-project-id"  // Replace with your project ID
  }

  inspect_templates = ["projects/my-project/inspectTemplates/template-id"]
  actions {
    // Configuration for actions
  }
  targets {
    // Configuration for discovery targets
  }
  errors {
    // Error handling configuration
  }
}
```

### References

- https://cloud.google.com/sensitive-data-protection/docs/reference/rest/v2/organizations.locations.discoveryConfigs

**Comment by patrickmoy** [comment]
This was completed some time ago — it's at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_discovery_config

**Comment by yu-iskw** [comment]
@patrickmoy Thank you for addressing this. I will give it a try!
