### ISSUE TITLE
Google Artifact Registry - Support for third party repositories

### ISSUE THREAD

**Issue by pupseba** [hashicorp/terraform-provider-google#17751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Since March 21st Artifact Regsitry Custom repositories are GA. Documentation for [google_artifact_registry_repository](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository) only speaks about support for "central" repositories like "DOCKER_HUB" or "MAVEN_CENTRAL" which is also consistent with the codebase that seems to hold support only for these central repositories.

Support for configuring 3rd party repositories ("Custom", as Google and the UI refers to them) is missing from the Terraform module. ⚠️Please note that in documentation, the term "custom" is referenced as a way to configure a central repository with custom credentials; which is a different thing of what's being noted in this request.

### New or Affected Resource(s)

* google_artifact_registry_repository

### Potential Terraform Configuration

```tf
resource "google_artifact_registry_repository" "my-repo" {
  location      = "us-central1"
  repository_id = "my-repository"
  description   = "example remote docker repository"
  format        = "DOCKER"
  mode          = "REMOTE_REPOSITORY"
  remote_repository_config {
    description = "ghcr repository"
    docker_repository {
      public_repository     = "CUSTOM"
      public_repository_url = "https://ghcr.io/"
    }
  }
}
```

Or directly accepting the url of the remote repository, like this:

```tf
resource "google_artifact_registry_repository" "my-repo" {
  location      = "us-central1"
  repository_id = "my-repository"
  description   = "example remote docker repository"
  format        = "DOCKER"
  mode          = "REMOTE_REPOSITORY"
  remote_repository_config {
    description = "ghcr repository"
    docker_repository {
      public_repository     = "https://ghcr.io/"
    }
  }
}
```

b/333389330

**Comment by melinath** [comment]
It looks like this is supported in the API as a `customRepository` field that's a sibling to the `publicRepository` field that's already supported by the provider. For example: https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories#MavenRepository

**Comment by bahag-klickst** [comment]
@melinath 
Thanks for https://github.com/GoogleCloudPlatform/magic-modules/pull/10242, which now allows the creation of custom remote repositories.
However, the plan output of terraform still looks weird, as it still shows "public_repository" to be set :-(

```
# google_artifact_registry_repository.main["gcrio"] will be created
  + resource "google_artifact_registry_repository" "main" {
      + create_time      = (known after apply)
      + description      = "Remote Repo for pulling images from gcr.io and caching them"
      + effective_labels = (known after apply)
      + format           = "DOCKER"
      + id               = (known after apply)
      + location         = "europe-west1"
      + mode             = "REMOTE_REPOSITORY"
      + name             = (known after apply)
      + project          = "sre-hybrisinfra-dev-4fc6"
      + repository_id    = "gcrio"
      + terraform_labels = (known after apply)
      + update_time      = (known after apply)

      + remote_repository_config {
          + description = "Remote Repo for pulling images from gcr.io and caching them"

          + docker_repository {
              + public_repository = "DOCKER_HUB"

              + custom_repository {
                  + uri = "https://gcr.io/"
                }
            }
        }
    }
```

Most probably because it is a pre apply script, that does the magic of wiping out public repository setting, or?
Any chance to fix this plan output as well?

Thanks and best regards,
Tim.

**Comment by melinath** [comment]
Marking this as resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/10242

@bahag-klickst thanks! That's a side effect of the way the fix was implemented. Could you report it as a [new bug](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=bug&projects=&template=00_bug.yml)? (Feel free to link to this comment as why you're filing the bug.) It would also be useful to include in the bug report whether you see a [permadiff](https://googlecloudplatform.github.io/magic-modules/develop/permadiff/) after creating the resource.
