### ISSUE TITLE
Remove GOOGLE_FIRESTORE_PROJECT from tests

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#17775]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

This was added when our primary project was in datastore mode & firestore couldn't be configured programatically. We should use Firestore on the primary project and Datastore [compat mode] in a temporary project now, until all old datastore projects are backfilled: https://cloud.google.com/datastore/docs/upgrade-to-firestore

**Comment by SarahFrench** [comment]
Any changes in ENVs for testing would impact the setup in TeamCity - I'll keep an eye out for changes.

**Comment by melinath** [comment]
I don't actually see any usage of GetTestFirestoreProjectFromEnv in terraform-google-beta?

**Comment by SarahFrench** [comment]
I think this issue was meant to be closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10505 being merged - closing now
