### ISSUE TITLE
adding cloud sql user with google_sql_user with type CLOUD_IAM_USER doesn't grant roles/cloudsql.instanceUser to the added user whereas it does when added via gcloud or ui

### ISSUE THREAD

**Issue by qbaze** [hashicorp/terraform-provider-google#17788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.5.7

### Affected Resource(s)

google_sql_user

### Terraform Configuration

```tf
```

### Expected Behavior

`roles/cloudsql.instanceUser `should be granted for each iam user added to the cloud sql instance 

### Actual Behavior

`roles/cloudsql.instanceUser` IS NOT granted for an iam user added

### Steps to reproduce

1. create db and user resources 
```
resource "google_sql_database_instance" "this" {
  ...
}

resource "google_sql_user" "developers" {
  name     = existing_google_user_email_address@
  instance = google_sql_database_instance.this.name
  type = "CLOUD_IAM_USER"
}
```
2. `terraform apply`
3. check the added user in the IAM console if `roles/cloudsql.instanceUser` role is granted

**Comment by ggtisc** [comment]
Hi @qbaze I'm replicating this scenario, just to confirm:

1. If you are getting any errors, please share the message
2. Did you have the same issue with any settings in the `google_sql_database_instance` resource?
3. Were the resources created from 0 or had some of the resources already been created?

**Comment by qbaze** [comment]
hey @ggtisc 

ad. 1 no execution errors, user is added successfully to the cloud sql instance
ad. 2 I don't understand your question, there are no errors on execution, resources are created but the roles/`cloudsql.instanceUser`  role on the added user is missing whereas if iam user is added to cloud sql via UI it's being automatically granted
ad. 3 created from scratch

Maybe the question is if this is an expected behavior or it should mimic behavior of UI?

**Comment by ggtisc** [comment]
That is right! If you use the UI it could make it automatically, but if you use terraform you need to configure everything manually including permissions, roles and so on.

**Comment by ggtisc** [comment]
Closing this issue as expected behavior
