### ISSUE TITLE
Add support for configuring forward proxy in google_apigee_environment resource

### ISSUE THREAD

**Issue by apichick** [hashicorp/terraform-provider-google#17832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Please add support for configuring forward proxy for an Apigee environment in the google_apigee_environment resources. The API call is the following one
```
METHOD: "PUT"
URL: "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/environments/$ENV"
BODY: { “forwardProxyUri”: “http://$FORWARD_PROXY_IP:$FORWARD_PROXY_PORT” }
```

### New or Affected Resource(s)

* google_apigee_environment

### Potential Terraform Configuration

```tf 
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment
- [forwardProxyUri in the API documentation](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#Environment.FIELDS.forward_proxy_uri)

b/334929937

**Comment by xuchenma** [comment]
@c2thorn For this one we need to support different update_verb for different fields. We had this discussion last year: https://github.com/GoogleCloudPlatform/magic-modules/pull/6349#issuecomment-1227538045

I tried to set "update_verb" as PUT under this field, but the generated `resource_apigee_environment.go` still thinks this field should be updated with PATCH.
```
  - !ruby/object:Api::Type::String
    name: 'forwardProxyUri'
    description: |
      Optional. URI of the forward proxy to be applied to the runtime instances in this environment.
    required: false
    update_verb: :PUT
```

Do we have support for using different update_verb within the same TF resource? Or do we really have to handwrite this resource now.

**Comment by SarahFrench** [comment]
Note from triage:

Resources support 'standard updates' and 'partial updates'. If a resource is defined to use a mix of both then the standard update behaviour will be present and partial update will not be present in the code.

Using pre/post update logic or addressing the problem above by using 2x partial updates can unblock the issue seen in https://github.com/hashicorp/terraform-provider-google/issues/17832#issuecomment-2052498017

**Comment by SarahFrench** [comment]
Forwarding this ticket with the expectation that https://github.com/hashicorp/terraform-provider-google/issues/17849 has been completed

**Comment by xuchenma** [comment]
Thanks Sarah! Reading more about the source code, I realize in this case it is also a PATCH, so we will still stick to the standard updates.

Making https://github.com/GoogleCloudPlatform/magic-modules/pull/10457 to address this

**Comment by xuchenma** [comment]
this is fixed now: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment#forward_proxy_uri

**Comment by SarahFrench** [comment]
Awesome, thanks! I'll close the issue as completed.
