### ISSUE TITLE
google_endpoints_service: diff of `protoc_output_base64` should be suppressed

### ISSUE THREAD

**Issue by kchygoe** [hashicorp/terraform-provider-google#17844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Change of `protoc_output_base64` tends to be so huge, that it would be better to be suppressed

### New or Affected Resource(s)

* google_endpoints_service

### Potential Terraform Configuration

```tf 
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/endpoints_service

**Comment by SarahFrench** [comment]
Terraform SDK doesn't provide options for us to modify how the diff is presented to users. The only option would be to flag it as Sensitive and use the censoring that happens in the terminal output, but that could be misleading to users by falsely flagging it that way.

Closing as cannot do
