### ISSUE TITLE
google_dataflow_job: current user cannot act as service account error

### ISSUE THREAD

**Issue by CloutKhan** [hashicorp/terraform-provider-google#17861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

[`google_dataflow_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job.html) should make it more obvious (perhaps by way of the `For example:` boxes), for those of us that embody the second S of KISS, that its field `service_account_email` must be _only_ the email, sans the typical prefix of `serviceAccount:`.

On many resources that provide for a service account to be an input, the pattern `"serviceAccount:${google_service_account.a_new_sa.email}"` is remarkably common, enough that when it's not made abundantly obvious, the lack of a big bright warning can mean the pattern is used in places it should not be used in.

I've found my way here by landing on the issue https://github.com/hashicorp/terraform-provider-google/issues/7126 in which they did the same thing -- that is, used the pattern `"serviceAccount:${~service_account_email}"`, which lead to the error "current user cannot act as service account error", and the problematic inclusion of the prefix was not immediately (or even eventually) recognised as the culprit.

An example / warning on that field could have saved me an hour or three and would help anyone else likely to otherwise land on that issue closed without a resolution.

### New or Affected Resource(s)

[`google_dataflow_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job.html)

### Potential Terraform Configuration

```tf 
```

### References

https://github.com/hashicorp/terraform-provider-google/issues/7126

b/338674422

**Comment by melinath** [comment]
Note from triage: This could either be fixed with changes to the documentation or with additional validation.
