### ISSUE TITLE
Add field reserved_internal_range and range to allow integration with the Internal Ranges API

### ISSUE THREAD

**Issue by daanheikens** [hashicorp/terraform-provider-google#17881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Recently the Internal Ranges API became Generally Available to be used. Integration with the subnetwork resource was not yet present aswell as the Internal Ranges API resource. (PR here: https://github.com/GoogleCloudPlatform/magic-modules/pull/10465)

To integrate the Internal Ranges API with the Subnetwork resource, the field `reserved_internal_range` needs to be added. The gcloud sdk also provides the `range` argument but this seems to be a gcloud specific argument.

### New or Affected Resource(s)

* google_compute_subnetwork

### Potential Terraform Configuration

```tf 
resource "google_compute_subnetwork" "full_range" {
  name                     = "full-range"
  region                   = "europe-west4"
  network                  = google_compute_network.default.name
  reserved_internal_range  = google_network_connectivity_internal_range.default.id
  private_ip_google_access = true
}

# OR

resource "google_compute_subnetwork" "partial_range" {
  name                     = "partial_range"
  region                   = "europe-west4"
  network                  = google_compute_network.default.name
  reserved_internal_range  = google_network_connectivity_internal_range.default.id
  ip_cidr_range            = "10.0.0.0/29"
  private_ip_google_access = true
}

```

### References

https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1/projects.locations.internalRanges
https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks 

b/336319050

**Comment by daanheikens** [comment]
Since this PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/10465 is now merged, this one can be picked up.  Will do that asap to integrate the subnetworks with the Internal Ranges API.

**Comment by c2thorn** [comment]
@daanheikens can you resend the pull request and ping @trodge on it? It will sit until the 6.0.0 feature branches are ready 

@trodge you should apply the "stop review reminders" label to it

**Comment by daanheikens** [comment]
> @daanheikens can you resend the pull request and ping @trodge on it? It will sit until the 6.0.0 feature branches are ready
> 
> @trodge you should apply the "stop review reminders" label to it

Sure! Will do that. I believe it does require some extra effort to fix the issue in which i do need some support with. I will make sure to raise my questions on the PR. Thanks @c2thorn

**Comment by c2thorn** [comment]
This has been added to the 6.0 branch. The breaking change part of it has moved to a part of https://github.com/hashicorp/terraform-provider-google/issues/12824

The new field will no longer be a breaking change, but the removal of `schema.ConfigModeAttr` to the parent field will be.
