### ISSUE TITLE
Cloud Deploy CustomTargetType remote Skaffold config support with Cloud Build repositories

### ISSUE THREAD

**Issue by katiexzhang** [hashicorp/terraform-provider-google#17935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

When defining custom targets for Cloud Deploy, Terraform should support using Cloud Build V2 Repositories as remote Skaffold configs.

### New or Affected Resource(s)

* google_clouddeploy_custom_target_type

### Potential Terraform Configuration

```tf 

resource "google_clouddeploy_custom_target_type" "custom-target-type" {
    location = "us-central1"
    name = "tf-test-my-custom-target-type%{random_suffix}"
    description = "My custom target type"
    custom_actions {
      render_action = "renderAction"
      deploy_action = "deployAction"
      include_skaffold_modules {
        configs = ["my-config"]
        google_cloud_build_repo {
          repository = "projects/777/locations/us-central1/connections/git/repositories/repo"
          path = "configs/skaffold.yaml"
          ref = "main"
        }
      }
    }
}
```

### References

https://cloud.google.com/deploy/docs/api/reference/rest/v1/projects.locations.customTargetTypes#skaffoldgcbreposource

b/337873627

**Comment by rileykarson** [comment]
Assigning based on linked PR
