### ISSUE TITLE
google_compute_network_endpoint_group datasource is returning error if the NEG doesn't exist

### ISSUE THREAD

**Issue by than-pet** [hashicorp/terraform-provider-google#17947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.0.0

### Affected Resource(s)

datasource `google_compute_network_endpoint_group`

### Terraform Configuration

```tf
data "google_compute_network_endpoint_group" "this" {
  name = "not-existing-neg"
  zone = "europe-west2-a"
}

output "network_endpoint_group" {
  value = data.google_compute_network_endpoint_group.this
}
```

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: projects/my-project/zones/europe-west2-a/networkEndpointGroups/not-existing-neg not found
│
│   with data.google_compute_network_endpoint_group.this,
│   on test.tf line 20, in data "google_compute_network_endpoint_group" "this":
│   20: data "google_compute_network_endpoint_group" "this" {
│

### Expected Behavior

Return an object with null values if the NEG doesn't exist
```
Changes to Outputs:
  + network_endpoint_group = {
      + default_port          = null
      + description           = null
      + id                    = null
      + name                  = null
      + network               = null
      + network_endpoint_type = null
      + project               = null
      + self_link             = null
      + size                  = null
      + subnetwork            = null
      + zone                  = null
    }
```

That was the behavior before v5.0.0 (tested with v4.84.0)

### Actual Behavior

Plan fails if the NEG is not found in the google project after v5.0.0+

### Steps to reproduce

1. use a NEG name that doesn't exist
2. `terraform apply`

b/337926216

**Comment by ggtisc** [comment]
Confirmed scenario.

It is possible to create the resource with the shared terraform configuration, but only with version 4.84.0, for now it is not available for the current version. This could be an enhancement for the future.

**Comment by BBBmau** [comment]
This change is intentional, see the upgrade guide [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade#provider).
