### ISSUE TITLE
google_bigquery_connection is missing Encryption / CMEK option

### ISSUE THREAD

**Issue by shashank-google** [hashicorp/terraform-provider-google#17955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

google_bigquery_connection  when connecting to Cloud SQL has CMEK option in the UI (screenshot below)
![image](https://github.com/hashicorp/terraform-provider-google/assets/3214330/27e00d2a-388a-472c-90f5-2bf9267e5b80)

### New or Affected Resource(s)

* google_bigquery_connection

### Potential Terraform Configuration

```tf 
resource "google_bigquery_connection" "connection" {
    connection_id = "my-connection"
    encryption_key_name  = google_kms_crypto_key.key.id
    location      = "US"
    friendly_name = "👋"
    description   = "a riveting description"
    cloud_sql {
        instance_id = google_sql_database_instance.instance.connection_name
        database    = google_sql_database.db.name
        type        = "POSTGRES"
        credential {
          username = google_sql_user.user.name
          password = google_sql_user.user.password
        }
    }
}
```

b/337873927

**Comment by daanheikens** [comment]
Looking at the API: https://cloud.google.com/bigquery/docs/reference/bigqueryconnection/rest/v1/projects.locations.connections#Connection

The field is available in the API, but i think we should name it: `kms_key_name`. 

If agreed, i can pick this one up!

**Comment by rileykarson** [comment]
That seems reasonable! I'll assign you to mark you're taking a look.

**Comment by shashank-google** [comment]
Many thanks for getting this fixed
