### ISSUE TITLE
hashicorp/google 5.13.0 or later is not available on darwin_arm64

### ISSUE THREAD

**Issue by leroygordo** [hashicorp/terraform-provider-google#17976]
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 3.33.0, >= 3.43.0, >= 3.45.0, >= 3.88.0, >= 4.25.0, >= 4.51.0, >= 4.67.0, < 5.0.0, >= 5.13.0, <
│ 6.0.0
╵

Terraform v1.8.2
on darwin_arm64

I appreciate your help!

**Comment by rileykarson** [comment]
I think your config (probably modules in it) are providing an impossible version constraint. See these two in particular, that conflict: `< 5.0.0, >= 5.13.0`
