### ISSUE TITLE
Failing test(s): TestAccContainerCluster_stackType*

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#17982]
### Impacted tests

- TestAccContainerCluster_stackType_withDualStack
- TestAccContainerCluster_stackType_withSingleStack
- TestAccContainerNodePool_fastSocket

### Affected Resource(s)

- google_container_cluster

### Failure rates

- 100% since 2024-04-24

### Message(s)

```
=== RUN   TestAccContainerCluster_stackType_withDualStack
=== PAUSE TestAccContainerCluster_stackType_withDualStack
=== CONT  TestAccContainerCluster_stackType_withDualStack
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: googleapi: Error 400: No valid versions with the prefix "1.25" found.
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "0xbb8671c64a8dc49e"
          }
        ]
        , badRequest
          with google_container_cluster.with_stack_type,
          on terraform_plugin_test.tf line 17, in resource "google_container_cluster" "with_stack_type":
          17: resource "google_container_cluster" "with_stack_type" {
--- FAIL: TestAccContainerCluster_stackType_withDualStack (109.44s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/6268896300196352710?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A138260%29%2Cid%3A2000000064

b/337886323

**Comment by roaks3** [comment]
My guess here is that the available versions changed in some way that caused this test to no longer work. We may want a more resilient strategy here (or just bump the version).

**Comment by rileykarson** [comment]
To be more resilient we should prefer using the RAPID release channel over pinned versions when possible. The issue we run into here is that we need specific GKE versions- sometimes minor, sometimes patch versions- to trigger certain features or behaviours.

Here's a snippet of the versions available in my project in `us-central1`:

```
  "defaultClusterVersion": "1.28.7-gke.1026000",
  "validMasterVersions": [
    "1.29.4-gke.1043000",
    "1.29.3-gke.1282000",
    "1.29.3-gke.1093006",
    "1.29.3-gke.1093000",
    "1.29.1-gke.1589018",
    "1.29.1-gke.1589017",
    "1.28.9-gke.1000000",
    "1.28.8-gke.1175000",
    "1.28.8-gke.1095000",
    "1.28.7-gke.1026000",
    "1.28.3-gke.1286000",
    "1.28.3-gke.1118000",
    "1.27.13-gke.1000000",
    "1.27.12-gke.1190000",
    "1.27.12-gke.1115000",
    "1.27.11-gke.1062001",
    "1.27.11-gke.1062000",
    "1.27.8-gke.1067004",
    "1.26.15-gke.1191000",
    "1.26.15-gke.1158000",
    "1.26.15-gke.1090000",
    "1.26.14-gke.1044000",
    "1.26.13-gke.1144000",
    "1.26.8-gke.200"
  ],
  "channels": [
    {
      "channel": "RAPID",
      "defaultVersion": "1.29.3-gke.1093000",
      "validVersions": [
        "1.29.4-gke.1043000",
        "1.29.3-gke.1282000",
        "1.29.3-gke.1093006",
        "1.29.3-gke.1093000",
        "1.28.9-gke.1000000",
        "1.28.8-gke.1175000",
        "1.27.13-gke.1000000",
        "1.27.12-gke.1190000",
        "1.26.15-gke.1191000",
        "1.26.15-gke.1158000"
      ]
    },
    {
      "channel": "REGULAR",
      "defaultVersion": "1.28.7-gke.1026000",
      "validVersions": [
        "1.29.1-gke.1589018",
        "1.29.1-gke.1589017",
        "1.28.8-gke.1095000",
        "1.28.7-gke.1026000",
        "1.27.12-gke.1115000",
        "1.27.11-gke.1062000",
        "1.26.15-gke.1090000",
        "1.26.14-gke.1044000",
        "1.26.8-gke.200"
      ]
    },
    {
      "channel": "STABLE",
      "defaultVersion": "1.27.11-gke.1062000",
      "validVersions": [
        "1.28.7-gke.1026000",
        "1.28.3-gke.1286000",
        "1.28.3-gke.1118000",
        "1.27.11-gke.1062000",
        "1.27.8-gke.1067004",
        "1.26.14-gke.1044000",
        "1.26.13-gke.1144000",
        "1.26.8-gke.200"
      ]
    }
  ],
```

If we don't specify a version we can only test features and behaviours in `1.28.7-gke.1026000`. If we specify the RAPID release channel we get `1.29.3-gke.10930001`. However, if there was a feature or issue introduced in `1.29.4-gke.1043000` we can't access that through any means other than a filter on the list of available versions.

I'm unsure if it's guaranteed that the latest minor version is the default version in RAPID- it's possible that when `1.30` is first introduced it will not be present in RAPID or at least will not be its default version. If it is guaranteed or the window is short, we can add new GKE features to Terraform after RAPID's default supports them, and avoid pinning. If it will take longer than O(days) for RAPID's default to catch up, we probably still need to pin.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_engine_versions#latest_master_version may also work too.
