### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-google#17994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

1.8.0

### Affected Resource(s)

google_bigquery_dataset_access

### Terraform Configuration

```tf
resource "google_bigquery_dataset_access" "test_first_bq_dataset_security_editor_access" {
  project       = "test-project-bq-access"
  dataset_id    = "test_first_bq_dataset_security"
  role          = "roles/bigquery.dataEditor"
  group_by_email = "<AD_email>"
}

```

### Expected Behavior

Apply successful without errors

### Actual Behavior

Apply errored with below message

Error: Provider produced inconsistent result after apply
When applying changes to google_bigquery_dataset_access.test_first_bq_dataset_security_access, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker

### Steps to reproduce

1. `terraform apply`

b/356626311

**Comment by ggtisc** [comment]
Hi @Sreerag74031!

Didi you changed any specific argument like changing `role  = "roles/bigquery.dataEditor"` for `role = "OWNER"` or are you changing the `Google provider version`, or the project?

Please be more specific on what you are changing to reproduce the issue

**Comment by Sreerag74031** [comment]
Hi @ggtisc 
we were planning to use this resource google_bigquery_dataset_access but while testing we got below error from terraform apply. we tried this in Terraform Cloud

while checking gcp we see the configuration applied but the terraform apply failed so we are not able to use it.

Error: Provider produced inconsistent result after apply
When applying changes to google_bigquery_dataset_access.test_first_bq_dataset_security_access, provider "provider["registry.terraform.io/hashicorp/google"]" produced an unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker

**Comment by ggtisc** [comment]
I'm trying to reproduce this issue, but after a `terraform apply` everything is good and without errors. What is the `Google provider version` that you are using?

According to the error message you got, this looks more like a bad configuration with the provider on your code

**Comment by Sreerag74031** [comment]
I was using hashicorp/google version 5.0.0, we got the same error using latest version 5.30.0 
we have other google resources in the same terraform configuration and those all got created without issues. Issue is only when we added the google_bigquery_dataset_access resource

**Comment by ggtisc** [comment]
Thank you!

I tried again to replicate this issue with your specifications, but again the result was successful without errors. So maybe you need to try to reproduce this with the minimum configuration in a separated environment as it is in this [link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access).

Remember to be aware of the notes and warnings specified to achieve a good result

**Comment by julianafaria** [comment]
Hello,
I have the same error here, with different branches and repositories. This problem started to me on Jun 24th.
We noticed that access is added on resource, but the apply code terraform fail.

![terraform_error](https://github.com/hashicorp/terraform-provider-google/assets/75648780/0cfe3da4-6716-4d4d-950e-4ba257cb953e)

**Comment by julianafaria** [comment]
For my case, we identified the problem. The Google or Plugin Terraform is case sensitive. I saw the group that was added on resource by console, and put the same thing on terraform. If group is GroupNew_app@domain.com we have to put the same name on code, with you put all in lowercase or change something that is uppercase to lowercase, it fail.

**Comment by ggtisc** [comment]
Yes, as I commented on a previous [response](https://github.com/hashicorp/terraform-provider-google/issues/17994#issuecomment-2120877943) you need to check 1st for your project configuration and also is a good practice to make unit testing of the alone resource to see what is happening.

**Comment by husseyd** [comment]
Exactly as @julianafaria says, it seems to be case sensitive. This drives me nuts! If you are syncing groups from AD then this is very hard to manage, especially if they vary across environments...

It seems to me that this resource actually applies the change correctly but then crashes when reporting the result.

**Comment by ggtisc** [comment]
Yes @husseyd you need to be aware of all these rules. You can learn more in the [API](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets) and [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access)

**Comment by wj-chen** [comment]
Verified that when emails with mixed-case letters are sent in the API request, the API response will come back with the letters normalized to be all lower-case. In the UI, users are allowed to input mixed-case emails so the Terraform behavior should match to be consistent. Created https://github.com/GoogleCloudPlatform/magic-modules/pull/11477 to handle that. Waiting for approvals at the moment.
