### ISSUE TITLE
Failing test(s): TestAccDataSourceSqlDatabaseInstanceLatestRecoveryTime_basic

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18005]
### Impacted tests

- TestAccDataSourceSqlDatabaseInstanceLatestRecoveryTime_basic

### Affected Resource(s)

- data.google_sql_database_instance_latest_recovery_time

### Failure rates

- 100% (2 failed out of last 2 runs) as of 2024-05-02

### Message(s)

```
    vcr_utils.go:152: Step 1/1 error: Error running apply: exit status 1
        Error: googleapi: Error 503: Service temporarily unavailable., serverException
          with data.google_sql_database_instance_latest_recovery_time.default,
          on terraform_plugin_test.tf line 20, in data "google_sql_database_instance_latest_recovery_time" "default":
          20: data "google_sql_database_instance_latest_recovery_time" "default" {

```

### Nightly build test history

- https://hashicorp.teamcity.com/test/1181858489726045331?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A141985%29%2Cid%3A2000000002 (GA)

b/339026573

**Comment by SarahFrench** [comment]
This has only failed the past 2 days but given the error message I figured I'd make an issue. The https://status.cloud.google.com/ page doesn't mention any issues

**Comment by melinath** [comment]
This is now resolved.
