### ISSUE TITLE
google_compute_security_policy_rule is missing rate_limit_options

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/terraform-provider-google#18002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

I'm trying to port rules from `google_compute_security_policy` to `google_compute_security_policy_rule` introduced in 5.27.0, but I can't because `rate_limit_options` is supported as a field for rules in `google_compute_security_policy` but not in `google_compute_security_policy_rule`. Please support it 🙏

### New or Affected Resource(s)

* google_compute_security_policy_rule

### Potential Terraform Configuration

```tf 
```

**Comment by hassannmoussaa** [comment]
Im interested in working in this issue please assign it to me

**Comment by ggtisc** [comment]
Currently there is a bug reported with a related situation #18033

Closed as duplicated
