### ISSUE TITLE
Failing test(s): TestAccFirestoreDatabase_firestoreCmekDatabaseExample (Beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18008]
### Impacted tests

- TestAccFirestoreDatabase_firestoreCmekDatabaseExample
- ~TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample~ FIXED

### Affected Resource(s)

- google_firestore_database

### Failure rates

- 100% since 2024-03-04

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccFirestoreDatabase_firestoreCmekDatabaseExample
=== PAUSE TestAccFirestoreDatabase_firestoreCmekDatabaseExample
=== CONT  TestAccFirestoreDatabase_firestoreCmekDatabaseExample
    testing_new.go:85: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: Error when reading or editing Database: googleapi: Error 409: There are concurrent database changes, please try again.
--- FAIL: TestAccFirestoreDatabase_firestoreCmekDatabaseExample (40.02s)
FAIL
```

### Nightly build test history

- [TestAccFirestoreDatabase_firestoreCmekDatabaseExample  - Beta ](https://hashicorp.teamcity.com/test/-4863440899568192954?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true)
- ~[TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample - Beta](https://hashicorp.teamcity.com/test/203702319512889475?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true)~ FIXED

b/339909748

**Comment by melinath** [comment]
Not sure what would make us "eligible" - maybe it's an allowlist?

**Comment by jinyangtang** [comment]
Hi, I have granted beta nightly project `ci-test-project-nightly-beta` the permission to create CMEK firestore database, the next run should succeed.

**Comment by SarahFrench** [comment]
It may be just a bad luck, or this newly-exposed error might be flakey. We'll see with time

**Comment by melinath** [comment]
@SarahFrench what would you think about closing this ticket and then we'll open a new one with the new failure if it fails consistently?
