### ISSUE TITLE
google_cloud_run_v2_service: template.timeout value not validated before apply

### ISSUE THREAD

**Issue by alexrjones** [hashicorp/terraform-provider-google#18028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.27.0
+ provider registry.terraform.io/hashicorp/google-beta v5.27.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.1

### Affected Resource(s)

google_cloud_run_v2_service
google_cloud_run_v2_job

### Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "default" {
  # ...
  template {
    # ...
    timeout = "3"
  }
}
```

### Expected Behavior

When executing `terraform plan` with a configuration like the above, the provider should detect that the value is invalid and fail.

### Actual Behavior

`terraform plan` succeeded, and `terraform apply` failed when making the API call to create the service:

> `Error: Error creating Service: googleapi: Error 400: Invalid value at 'service.template.timeout' (type.googleapis.com/google.protobuf.Duration), Field 'timeout', Illegal duration format; duration must end with 's'`

### Steps to reproduce

1. Create a configuration like the example, where a timeout string without the 's' suffix is used.
1. `terraform plan` will succeed.
1. `terraform apply` will fail.

b/340300777

**Comment by ggtisc** [comment]
Confirmed issue:

According to [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#timeout) the `timeout` field needs to end with `s`, but terraform plan and terraform apply don't recognize it
