### ISSUE TITLE
Add resource for `gcloud asset search-all-resources`

### ISSUE THREAD

**Issue by stavling** [hashicorp/terraform-provider-google#18034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Hello!

Sorry if this is a repeat, I tried searching for already existing issues.

Right now there is a [cloud asset search resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloud_asset_resources_search_all) in this provider. It's using https://cloud.google.com/asset-inventory/docs/reference/rest/v1p1beta1/resources/searchAll.

The API has no guarantees (which is expected, since it's beta), but there is a GA version of the same functionality here: https://cloud.google.com/asset-inventory/docs/reference/rest/v1/TopLevel/searchAllResources.

Having a new resource in the non-beta provider using that endpoint would be very helpful - a recent unannounced change in the beta version of the API have now caused us some issues.

Thank you!

### New or Affected Resource(s)

* google_cloud_asset_resources_search_all
* google_cloud_asset_resources_search_all_resources

### Potential Terraform Configuration

```tf
data google_cloud_asset_resources_search_all_resources projects {
  scope = "organizations/0123456789"
  asset_types = [
    "cloudresourcemanager.googleapis.com/Project"
  ]
} 
```
The API part actually seems pretty much the same, but I guess the configuration would need to be named something different ☝️ 

b/340252471

**Comment by averbuks** [comment]
That issue was addressed https://github.com/GoogleCloudPlatform/magic-modules/pull/6823
Resource does exist for beta provider  https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloud_asset_resources_search_all
Ticket may be closed
