### ISSUE TITLE
Monitoring uptime check config recreated each time

### ISSUE THREAD

**Issue by VenelinMartinov** [hashicorp/terraform-provider-google#18038]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google-beta v5.28.0

### Affected Resource(s)

google_monitoring_uptime_check_config

### Terraform Configuration

```tf
provider "google" {
  region = "us-central1"
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google-beta"
      version = "5.28.0"
    }
  }
}

resource "google_monitoring_uptime_check_config" "uptime_check" {
  display_name = "API Uptime Check"
  timeout      = "30s"
  period       = "300s"

  http_check {
    path    = "/healthcheck"
    port    = 443
    use_ssl = true
    validate_ssl = true
  }

  monitored_resource {
    type   = "uptime_url"
    labels = {
      host       = "our.domain.com"
    #   project_id = "pulumi-development"
    }
  }

  content_matchers {
    content = ".*STATUS_CLASS_2XX.*"
  }
}

```

### Debug Output

https://gist.github.com/VenelinMartinov/0cdd7fc30fd789242e2b505ae457af5c

### Expected Behavior

No changes.

Here the GCP resource seems to require the project_id to be specified - the provider auto-fills it but then that triggers a diff next time. The diff should really be suppressed instead or a sensible error message should be produced because the project id is not specified.

### Actual Behavior

Recreated every time.

### Steps to reproduce

1. `terraform apply`
2. `terraform plan -refresh=false`

b/341136606

**Comment by ggtisc** [comment]
Hi @VenelinMartinov as you can see in the example of [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_uptime_check_config#example-usage---uptime-check-config-https) the `labels` is a required field and it suggest to use the `project_id` but you have the option to doesn't declare it.

There are fields that are set backstage and it means that if you don't set them terraform will do it for you, but it represent a change and this is the reason for what you obtain a `destroy and then create replacement` so based on this explanation you could decide to declare or let terraform manage it by itself, but as you can see this is not an error or bug. You can learn more of this harassment in this [link](https://googlecloudplatform.github.io/magic-modules/develop/permadiff/)

**Comment by VenelinMartinov** [comment]
This is certainly a bug:
The above program does not define project_id. 
GCP sets the project_id label
On the next terraform apply, the provider tries to delete the label and recreate the resource.

@ggtisc, I've raised a PR to fix the issue https://github.com/GoogleCloudPlatform/magic-modules/pull/10694

**Comment by VenelinMartinov** [comment]
Are you a maintainer of the project @ggtisc?

**Comment by ggtisc** [comment]
> This is certainly a bug: The above program does not define project_id. GCP sets the project_id label On the next terraform apply, the provider tries to delete the label and recreate the resource.
> 
> @ggtisc, I've raised a PR to fix the issue [GoogleCloudPlatform/magic-modules#10694](https://github.com/GoogleCloudPlatform/magic-modules/pull/10694)

Yes I confirmed it with a partner, so I'm forwarding it right now thank you very much
