### ISSUE TITLE
Add resource for Managed Folders in GCS

### ISSUE THREAD

**Issue by eh-john** [hashicorp/terraform-provider-google#18053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

There is [a new managed folder feature for GCS](https://cloud.google.com/storage/docs/managed-folders) that can't be created in terraform yet. It appears to have API support already as it [describes the REST APIs needed to create one in the docs](https://cloud.google.com/storage/docs/creating-managing-managed-folders#rest-apis).

It looks like the version of the Go SDK that this is using supports it too. 

Having this resource available allows one to set permissions at a path level in GCS.

### New or Affected Resource(s)

* google_storage_managed_folder

### Potential Terraform Configuration

```tf 
resource "google_storage_managed_folder" "managed_folder" {
    bucket = "bucket here"
    name   = "folder_name"
}
data "google_storage_managed_folder" "managed_folder" {
    bucket = "bucket here"
    name   = "folder_name"
}
```

### References

https://cloud.google.com/storage/docs/creating-managing-managed-folders#rest-apis_1
https://cloud.google.com/storage/docs/managed-folders

b/340252275

**Comment by hassannmoussaa** [comment]
Please assign this issue to me , ill open a PR for it

**Comment by SarahFrench** [comment]
Note from triage: This is the API for the new resource  https://cloud.google.com/storage/docs/json_api/v1/managedFolder/insert

**Comment by juliocc** [comment]
Apologies for the overlap! I didn't realize this was already assigned and I started working on it due to an urgent customer request. My PR (GoogleCloudPlatform/magic-modules#10786) already incorporates IAM and addresses all the details with import. Hope we can work this out.

/cc @ludoo

**Comment by roaks3** [comment]
Fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/10786
