### ISSUE TITLE
google_compute_ssl_certificate Secret Manager Version Support

### ISSUE THREAD

**Issue by wilsonfv** [hashicorp/terraform-provider-google#18061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

These resources accept plain text of TLS certificate private key hence they will store private key in Terraform state file.

Terraform state file is NOT compliance to general Secret Management practice.

There have been a few issues raised discussing similar things. (see reference)

The preference place to store TLS certificate private key is on GCP Secret Manager so we could add support to these 2 resources to accept GCP Secret Manager secret version as input to create GCP Compute SSL Certificate.

It would be quite similar to existing [google_cloudbuildv2_connection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuildv2_connection)

[private_key_secret_version](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuildv2_connection#private_key_secret_version) - (Optional) SecretManager resource containing the private key of the GitHub App, formatted as projects/*/secrets/*/versions/*.

Both TLS certificate private key and certificate public key can be retrieved from GCP Secret manager.

These 2 new added fields will be conflict to existing fields 

- private_key
- certificate

So the resources will create SSL compute certificate when either one of the pairs presents

### New or Affected Resource(s)

- [google_compute_ssl_certificate](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_ssl_certificate)
- [google_compute_region_ssl_certificate](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_ssl_certificate)

### Potential Terraform Configuration

```tf 
 resource "google_compute_ssl_certificate" "default" {
  name_prefix = "my-certificate-"
  private_key_secret_version = "projects/[Project ID]/secrets/[Secret Name]/versions/latest"
  certificate_secret_version = "projects/[Project ID]/secrets/[Secret Name]/versions/latest
  lifecycle {
    create_before_destroy = true
  }
}
```

```tf 
 resource "google_compute_regional_ssl_certificate" "default" {
  name_prefix = "my-certificate-"
  region = "europe-west2"
  private_key_secret_version = "projects/[Project ID]/secrets/[Secret Name]/versions/latest"
  certificate_secret_version = "projects/[Project ID]/secrets/[Secret Name]/versions/latest
  lifecycle {
    create_before_destroy = true
  }
}
```

### References

- https://github.com/hashicorp/terraform-provider-google/issues/6119
- https://github.com/hashicorp/terraform-provider-google/issues/927
- https://github.com/hashicorp/terraform-provider-google/issues/927

**Comment by SarahFrench** [comment]
Note from triage: We prefer to keep resources matching what the API defines and features like this should be addressed at the Core level - https://github.com/hashicorp/terraform/issues/516
