### ISSUE TITLE
Failing test(s): TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfig*

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#18077]
### Impacted tests

- TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample
- TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample

### Affected Resource(s)

- google_data_loss_prevention_discovery_config

### Failure rates

- TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample: 95% - 21 of the 22 runs since  added

### Message(s)

```
 Error: Error creating DiscoveryConfig: googleapi: Error 400: For a project, you can have multiple single-table discovery configurations but only one project-level discovery configuration for BigQuery tables.
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-2822591097687584442?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/339716259

**Comment by patrickmoy** [comment]
These tests were disabled in https://github.com/GoogleCloudPlatform/magic-modules/pull/10798 since they are redundant (update tests cover these cases), and test parallelism caused flakiness. 

I think we can consider this closed since these tests are no longer run?

**Comment by melinath** [comment]
Marking resolved since these tests no longer run.
