### ISSUE TITLE
32-bit private ASN range unsuported

### ISSUE THREAD

**Issue by netturpin** [hashicorp/terraform-provider-google#1808]
Hello,
I'm trying to create a router using the [32-bit private ASN range](https://tools.ietf.org/html/rfc6996#section-5) . While it's supported from GCP , Terraform is not able to parse this number correctly (with our without double quotes) and it output the error: 
```Error: google_compute_router.foobar: bgp.0.asn: cannot parse '' as int: strconv.ParseInt: parsing "4200000001": value out of range```

### Terraform Version
``` terraform -v
Terraform v0.11.7
+ provider.google v1.16.2
```

### Affected Resource(s)
- google_compute_router

### Terraform Configuration Files
```hcl
provider "google" {
  region      = "europe-west4"
}

resource "google_compute_network" "foobar" {
  name                    = "my-network"
  auto_create_subnetworks = false
}

resource "google_compute_router" "foobar" {
    name = "foobar"
    network = "${google_compute_network.foobar.name}"
    bgp {
    asn = "4200000001"
    }
}

```

### Debug Output
You can find the trace output [here](https://gist.github.com/netturpin/1ac97ee4e48a5f44a70e586e084763b4)

### Expected Behavior
Terraform should have output a plan file with a router having a  BGP ASN of 4200000001

### Actual Behavior
Terraform output an error:
`Error: google_compute_router.foobar: bgp.0.asn: cannot parse '' as int: strconv.ParseInt: parsing "4200000001": value out of range`

**Comment by ndmckinley** [comment]
Yep, that's larger than Go's `int32`.  Let's see if I can make Terraform handle it anyway.  :)

**Comment by ndmckinley** [comment]
Ah.  No, unfortunately!

https://github.com/hashicorp/terraform/issues/17077

Some good news, though - it seems like this will automatically start working as soon as HCL2 is done, so please follow the upstream bug for updates.

**Comment by roaks3** [comment]
Confirmed this is now fixed
