### ISSUE TITLE
Downstream changelog generation stopped working

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#18095]
### What kind of contribution is this issue about?

Downstream builds

### Details

We stopped adding new changelog entries to https://github.com/hashicorp/terraform-provider-google/tree/main/.changelog about 3 weeks ago. Right now it looks like it was a bug from https://github.com/GoogleCloudPlatform/magic-modules/pull/10482 (possibly https://github.com/GoogleCloudPlatform/magic-modules/pull/10482/files#diff-26bd0bd488ccce73529b6d8d630ed7d7c6cae08e051e7471b1331e262984a21bL332 ?)

**Comment by SarahFrench** [comment]
@roaks3 assigned you during triage FYI

**Comment by melinath** [comment]
We reordered some lines, so this is no longer creating the changelog files in the correct directory.

**Comment by roaks3** [comment]
@trodge passing this along, I wasn't able to get to this last week
