### ISSUE TITLE
Failing test(s): TestAccCloudFunctionsFunction_cmek

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#18094]
### Impacted tests

- TestAccCloudFunctionsFunction_cmek

### Affected Resource(s)

- google_cloudfunctions_function

### Failure rates

- ~50% since 2024-04-01 as of 2024-05-10

### Message(s)

```
  Error: Error waiting for Creating CloudFunctions Function: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 5m0s)

```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-5609233894264835642?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/339897870

**Comment by rileykarson** [comment]
We probably want to bump the resource timeout to the Terraform default (I think it was 20m or 30m)

**Comment by hao-nan-li** [comment]
Just double-checked the nightly runs in the past month, looks like `TestAccCloudFunctionsFunction_cmek` only failed once and the current timeout is set at `20 minutes`. Given the very low failing rate in the past months, I don't intend to make any change, if the failing rates goes back up, it might be worthy to increase the timeout to 30m or 60m and see the outcomes.

**Comment by hao-nan-li** [comment]
Most likely timeout, could change the timeout to 30 minutes and see if it fixed the issue.
