### ISSUE TITLE
Failing test(s): TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#18102]
### Impacted tests

- TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample

### Affected Resource(s)

- google_data_loss_prevention_discovery_config

### Failure rates

- 61% (14 failed out of last 23 runs) as of 2024-05-10

### Message(s)

```
vcr_utils.go:152: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
          map[string]string{
        -   "last_run_time": "2024-04-23T05:38:44.802696Z",
        +   "last_run_time": "2024-04-23T05:38:48.828130Z",
        -   "update_time":   "2024-04-23T05:38:46.877207Z",
        +   "update_time":   "2024-04-23T05:38:51.231298Z",
          }
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/6628941444233606909?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/339909443

**Comment by patrickmoy** [comment]
This test is skipped now, so it should no longer be running (and therefore failing).
