### ISSUE TITLE
Replace use of testing tools in `hashicorp/terraform-plugin-sdk/v2` with `hashicorp/terraform-plugin-testing`

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18110]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

See: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing@v1.7.0

This package contains the testing tools for provider, separate from the SDK. By updating the provider to use this package we can avoid issues in acceptance tests

**Comment by rileykarson** [comment]
@trodge had https://github.com/GoogleCloudPlatform/magic-modules/pull/10339 outstanding

**Comment by rileykarson** [comment]
Blocked on https://github.com/hashicorp/terraform-plugin-testing/issues/327

**Comment by melinath** [comment]
This is a prerequisite for https://github.com/hashicorp/terraform-provider-google/issues/12428

**Comment by trodge** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/10339
