### ISSUE TITLE
Missing Ingress_from documentation for VPC Service Controls resources for using networks as incoming source

### ISSUE THREAD

**Issue by daanheikens** [hashicorp/terraform-provider-google#18142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

According to the API reference, the [IngressSource](https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#ingresssource) object reflecting the `ingress_from[].sources[]` fields in the `google_access_context_manager_service_perimeter` should support networks as an option for the `resource` field. The documentation currently does not reflect this.

Source:https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#IngressSource 

### New or Affected Resource(s)

* google_access_context_manager_service_perimeter
* google_access_context_manager_service_perimeter_ingress_policy

### Potential Terraform Configuration

```tf 
resource "google_access_context_manager_service_perimeter_ingress_policy" "ingress_policy" {
  perimeter = "${google_access_context_manager_service_perimeter.storage-perimeter.name}"
  ingress_from {
    identity_type = "any_identity"
    sources {
      resource = "//compute.googleapis.com/projects/example-project/global/networks/example-network"
    }
  }
  ingress_to {
    resources = ["*"]
    operations {
      service_name = "bigquery.googleapis.com"
      method_selectors {
        method = "*"
      }
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### References

https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#ingresssource
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_ingress_policy#resource

b/341749801

**Comment by daanheikens** [comment]
I can pick this one up, adding examples, docs and tests.

**Comment by SarahFrench** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/11273
