### ISSUE TITLE
Error waiting for Deleting Firewall on project creation

### ISSUE THREAD

**Issue by shaikatzz** [hashicorp/terraform-provider-google#18156]
Upon project creation, and setting `auto_create_network` to false, the resource is trying to delete the firewall rules.
It requires compute engine APi to be enabled, so we also enable it, but this is async operation.

Looks like a retry was already implemented, but 10 seconds might not be good enough, i'm still received that error.
Those issues are very very problematic since terraform will automatically remove the project, and it will got into pending deletion, preventing me from re-creating the project again with the same name.
 
https://github.com/hashicorp/terraform-provider-google/blob/fb9ce6a05ba6cd79082e2fd89c1ac026ca1eb80f/google/services/resourcemanager/resource_google_project.go#L235

maybe a bigger timeout should be implemented, or at least some loop with multiple retries?

**Comment by melinath** [comment]
@shaikatzz Could you provide the error message you're receiving? This may require enabling debugging: https://developer.hashicorp.com/terraform/internals/debugging
