### ISSUE TITLE
google_billing_budget support for notificationsRule

### ISSUE THREAD

**Issue by joonvena** [hashicorp/terraform-provider-google#18182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add support for [enableProjectLevelRecipients](https://cloud.google.com/billing/docs/reference/budget/rest/v1/billingAccounts.budgets#NotificationsRule) in the resource. It would be highly beneficial to be able to configure this using the provider as now if you want to enable this you need to modify the budget by hand or use the API directly.

### New or Affected Resource(s)

* google_billing_budget

### Potential Terraform Configuration

```tf 
```

b/341735409

**Comment by melinath** [comment]
Note from triage: we should add support for the entire notificationsRule block.
