### ISSUE TITLE
sole tenant minNodeCpus cannot be changed while the instance is running, even if allow_stopping_for_update = true

### ISSUE THREAD

**Issue by Yurilb** [hashicorp/terraform-provider-google#18217]
### Community Note

After editing minNodeCpus, i get this error:
Error updating scheduling policy: googleapi: Error 400: minNodeCpus cannot be changed while the instance is running.

### Terraform Version & Provider Version(s)

Terraform v1.3.9
on Linux
+ provider registry.terraform.io/hashicorp/google v5.3.0

### Affected Resource(s)

google_compute_instance

### Terraform Configuration

```tf
```

### Expected Behavior

if allow_stopping_for_update = true, vm must be shutted down and minNodeCpus must be changed

### Steps to reproduce

1. `terraform apply`

b/342657819

**Comment by ggtisc** [comment]
Hi @Yurilb!

Please share with us your terraform code, debug output and any error message you have related to this, to try to replicate this scenario and see what is happening

**Comment by Yurilb** [comment]
Hi ggtisc,
this is the full code with an input.json that you need to customize with your values (I marked the field you have to change with "#"). 
If you look at that code, you will see that we calculate min_node_cpus from the size of the vm (main.tf, line 61). 
So, if you change the size of the vm (i.e. in input.json vm_size from n2-standard-4 to n2-standard-8), min_node_cpus changes its value (from 2 to 4)
If i try a terraform apply, terraform give this error: minNodeCpus cannot be changed while the instance is running.

As you can see,  we set allow_stopping_for_update = true, so i would have expected the vm to shut down.

In order to replicate that error, I think that the code can be simplified, by creating only a resource "google_compute_instance" on a sole tenant node group and trying to change only minNodeCpus
[Code.zip](https://github.com/hashicorp/terraform-provider-google/files/15465360/Code.zip)
