### ISSUE TITLE
Invert behavior of lifecycle condition `age` to align with other numerical conditions in GCS buckets

### ISSUE THREAD

**Issue by NickElliot** [hashicorp/terraform-provider-google#18232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

With resolution of https://github.com/hashicorp/terraform-provider-google/issues/17990, it became possible to send zero values for all numerical lifecycle conditions with a corresponding "send_x_if_zero" field. Currently age operates in the opposite manner, where it will send zero by default, and need a "no_age" field to not send zero. This behavior should be inverted in the next major release, to prevent the existing scenario of an "age=0" condition being inadvertently applied to many buckets.

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf 
lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      age = 0
      send_age_if_zero = true
    }
  }
```

### References

b/339089840
https://github.com/hashicorp/terraform-provider-google/issues/17990
https://github.com/GoogleCloudPlatform/magic-modules/pull/10717

b/342657169

**Comment by kautikdk** [comment]
Hi @NickElliot, Can you please assign this issue to me.

**Comment by rileykarson** [comment]
@NickElliot @kautikdk this is on track for `6.0.0` right? Tagged as future for now, but we should adjust that.

Also cc @c2thorn

**Comment by NickElliot** [comment]
Was intended for that, my bad! I was looking for a major release label but didn't see it, didn't realize it was another button.

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11356
