### ISSUE TITLE
Add a new resource representing backups in BigTable clusters

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

I'm working on a feature request to add force_destroy behaviour to google_bigtable_instance, as deletion can be blocked by backups being present.

To implement this fully I need to have an acceptance test that provisions some backups in a BigTable instance and its cluster(s). However there isn't a way to create BigTable backups using the Google provider currently.

To address this, I'd like to explore the idea of a new resource corresponding to this projects.instances.clusters.backup entity in the API : https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters.backups
(client library is used in the provider currently though: https://pkg.go.dev/cloud.google.com/go/bigtable#AdminClient.CreateBackup)

This resource would allow users to make ad-hoc backups through their Terraform configuration.

**A problem is** that [this resource is an expiring resource](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters.backups#Backup.FIELDS.expire_time) so this is an example of "jobs" that we have debated adding to the provider in the past.

---

There is an [open issue for _scheduled_ backups](https://github.com/hashicorp/terraform-provider-google/issues/12191), which is blocked by the upstream service and would not be addressed by adding the new resource represented in this issue.

### New or Affected Resource(s)

* google_bigtable_table_backup ?
* google_bigtable_cluster_backup ?

Naming isn't clear because:
* the API scopes the backup to clusters : [projects.instances.clusters.backups](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters.backups)
* BUT we don't have a `google_bigtable_cluster` resource, we have a `google_bigtable_instance` resource and that resource allows users to define 1+ clusters in that resource
    * so `google_bigtable_cluster_backup` feels like an odd choice as a result, although its correct
* ALSO, the back up is of a given table, so we could use `google_bigtable_table_backup`, but that doesn't agree with the API

### Potential Terraform Configuration

```tf 
resource "google_bigtable_table_backup" "example" {
  name = "my-backup" 
  source_table = google_bigtable_table.my_table.id
  expire_time = "2024-10-02T15:01:23Z"
}
```

### References

Related issue: https://github.com/hashicorp/terraform-provider-google/issues/12191

API docs: https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters.backups

Client library : https://pkg.go.dev/cloud.google.com/go/bigtable#AdminClient.CreateBackup

b/342657564

**Comment by rileykarson** [comment]
During triage we decided to close this- there aren't customers asking for it yet, and there are some questions to resolve with respect to backups expiring that make it messy.
