### ISSUE TITLE
principal / principalSet prefix does not work with ingress policy

### ISSUE THREAD

**Issue by IceR00t** [hashicorp/terraform-provider-google#18259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v5.28.0
on <architecture>
+ provider registry.terraform.io/hashicorp/google v5.28.0
+ provider registry.terraform.io/hashicorp/google-beta v5.28.0

### Affected Resource(s)

google_access_context_manager_service_perimeter

### Terraform Configuration

```tf
```

### Expected Behavior

Adding the `principal` or `principalSet` in the identities field should allow the Workload identity group principals access to the GCP resource via the ingress policy

### Actual Behavior

When attempting to build, we gain an error 400 with the following message: 

```
14:21:48 module.XXXX-hierarchy.google_access_context_manager_service_perimeter.service_perimeter: Modifying... [id=accessPolicies/123456789012/servicePerimeters/XXXX_perimeter]
14:21:49 |
14:21:49 | Error: Error updating ServicePerimeter "accessPolicies/123456789012/servicePerimeters/XXXX_perimeter":googleapi: Error 400: Unknown member type "principal" provided - expected prefix to be 'user' or 'serviceAccount'
14:21:49 |
14:21:49 |   with module.XXXX-hierarchy.google_access_context_manager_service_perimeter.service_perimeter, 
14:21:49 |   on ../../modules/XXXX-hierarchy/XXXX-vpc-sc.tf line 79, in resource "google_access_context_manager_service_perimeter" "service_perimeter":
14:21:49 |   79:resource "google_access_context_manager_service_perimeter" " service_perimeter" {
```

### Steps to reproduce

1. Use version 4.28.0 of Terraform.
2. Add principal or principalSet to identities section under ingress_from block.
3. Terraform build

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter#identities

b/344576405

**Comment by ggtisc** [comment]
Not possible to replicate, several inconsistencies have been found on [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter#example-usage---access-context-manager-service-perimeter-granular-controls), from poorly declared resources to poorly structured code blocks

**Comment by Charlesleonius** [comment]
We apologize for the misleading documentation. principalSet and principal prefixes are not yet supported by Access Context Manager and will be removed until further notice.

**Comment by Charlesleonius** [comment]
This documentation has been removed and the issue can be closed. @ggtisc

**Comment by Charlesleonius** [comment]
@rileykarson Can we close this please
