### ISSUE TITLE
Direct VPC Egress not configurable in google_cloud_run_service

### ISSUE THREAD

**Issue by MKand** [hashicorp/terraform-provider-google#18252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Users of the **google_cloud_run_service** resource are unable to configure direct VPC egress via the resource configuration. Many users still use this version of the resource and have NOT upgraded to **google_cloud_run_v2_service**. Those who want to use the new Direct VPC egress feature that recently went GA are forced to upgrade to google_cloud_run_v2_service, and this is not always feasible.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf 
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"

  template {
  metadata {
    annotations = {
      "run.googleapis.com/vpc-access-egress = "all-traffic"
      "run.googleapis.com/network= "default"
      "run.googleapis.com/subnetwork= "default"
      "run.googleapis.com/network-tags= ["tag1", "tag2", "tag3"]
    }
  }
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }
}
```

**Comment by rileykarson** [comment]
What isn't working here? We should have support for `annotations`

**Comment by gouyelliot** [comment]
I was able to deploy a Cloud Run v1 with Direct VPC using this config

```terraform
resource "google_cloud_run_service" "my-cloud-run" {

  ...

  template {
    metadata {
      annotations = {
        "run.googleapis.com/vpc-access-egress"  = "private-ranges-only"
        "run.googleapis.com/network-interfaces" = "[{\"network\":\"my-project\",\"subnetwork\":\"my-subnet\",\"tags\":[\"my-tag\"]}]",
      }
    }
  }
}
```

Tested on Terraform v1.3.3 & Google provider v4.84.0

**Comment by SarahFrench** [comment]
Note from triage: closing as this is configurable, as described here https://github.com/hashicorp/terraform-provider-google/issues/18252#issuecomment-2179817758
