### ISSUE TITLE
Missing plan-time validation for the `name` attribute of the `google_compute_instance`

### ISSUE THREAD

**Issue by AlexPykavy** [hashicorp/terraform-provider-google#18265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.7.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v5.31.1

### Affected Resource(s)

`google_compute_instance`

### Terraform Configuration

```tf
resource "google_compute_instance" "main" {
  name         = "super-long-machine-name-that-does-not-meet-the-google-compute-instance-naming-restrictions"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
    }
  }
  network_interface {
    network = "default"

    access_config {
      // Ephemeral public IP
    }
  }
}
```

### Expected Behavior

`terraform plan` fails with a meaningful message

### Actual Behavior

`terraform plan` passes

### Steps to reproduce

1. `terraform plan`
2. `terraform apply`

### References

I've tried to fix it in the https://github.com/GoogleCloudPlatform/magic-modules/pull/10775.

b/343730710

**Comment by ggtisc** [comment]
Hi @AlexPykavy I tried to replicate this scenario with the shared terraform version and Google provider version, and with your code and the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage) code. But the result was correct, returning the next error:

`Error creating instance: googleapi: Error 400: Invalid value for field 'resource.name' "super-long-machine-name-that-does-not-meet-the-google-compute-instance-naming-restrictions". Must be a match of regex '(?:[a-z](?:[a-z0-9]{0,61}[a-z0-9])?)', invalid`

I suggest you refresh your environment and make basic troubleshooting to release memory and cache and try again. A `terraform init` or `terraform init -upgrade` could also work.

**Comment by AlexPykavy** [comment]
Hi @ggtisc ,

Thank you for the quick response. Did you receive this error during the `terraform plan` or the `terraform apply`?

**Comment by ggtisc** [comment]
After a double check `terraform apply` works with an expected behavior, but `terraform plan` doesn't recognize the error for the long name.

Based on this I'm forwarding this as an enhancement proposal.

**Comment by SarahFrench** [comment]
Note from triage: We'd want to check for any history of compute instance names being validated in the provider and discovering edge cases before adding this
