### ISSUE TITLE
Failing test(s): TestAccDatastoreIndex_datastoreIndexExample

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-google#18277]
### Impacted tests

- TestAccDatastoreIndex_datastoreIndexExample

### Affected Resource(s)

- google_firestore_database

### Failure rates

- 100% since 2024-05-14

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccDatastoreIndex_datastoreIndexExample
=== PAUSE TestAccDatastoreIndex_datastoreIndexExample
=== CONT  TestAccDatastoreIndex_datastoreIndexExample
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating Database: googleapi: Error 409: Database already exists. Please use another database_id
          with google_firestore_database.database,
          on terraform_plugin_test.tf line 2, in resource "google_firestore_database" "database":
           2: resource "google_firestore_database" "database" {
--- FAIL: TestAccDatastoreIndex_datastoreIndexExample (6.67s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-4052695643890826960?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/344605700

**Comment by melinath** [comment]
This fix ended up breaking https://github.com/hashicorp/terraform-provider-google/issues/18072#issuecomment-2278535180. According to discussion around that ticket, it's not possible to automatically provision default databases in projects created in a test, so this test will need to move into an isolated project to avoid running into problems from the default database existing.

**Comment by rwhogg** [comment]
The resource was deleted, so this should no longer be an issue.
