### ISSUE TITLE
Missing spoke.group argument in google_network_connectivity_spoke resource

### ISSUE THREAD

**Issue by sagitur101** [hashicorp/terraform-provider-google#18297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

When hub policy mode configure to 'PRESET' and the preset topology is 'STAR', the argument spoke.group that should define the spoke group (center|edge) is missing in the documentation.

I got this error: - field `spoke.group` must be defined when hub.policy_mode = `PRESET` and hub.preset_topology = `STAR`: invalid argument

### New or Affected Resource(s)

google_network_connectivity_spoke, google_network_connectivity_hub

### Potential Terraform Configuration

```tf 
```
resource "google_network_connectivity_spoke" "office-0-spokes" {
  for_each = var.vpc_names

  name     = "${each.key}-spoke"
  location = "global"
  hub      = var.hub_uri
  linked_vpc_network {
    uri = google_compute_network.office-0-vpcs[each.key].id
  }
  group = "CENTER" || "EDGE"

}

b/344606019

**Comment by SarahFrench** [comment]
Note from triage: [here's the field in the API](https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1beta/projects.locations.spokes#Spoke.FIELDS.group), and this resource is made via the DCL

**Comment by Filipo24** [comment]
Not sure if it should be treated as a separate issue, but as it is related to the same feature I suggest the resource **google_network_connectivity_hub** is also updated to support a new attribute for **preset_topology** as for the VPC spoke to be part of the group the NCC hub need to set the Preset topology first to support STAR instead of MESH topology -> [presetTopology](https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1/projects.locations.global.hubs#presettopology)

**Comment by jrosati-burwood** [comment]
This is still an issue.
