### ISSUE TITLE
[Announcement] Upcoming Changes in Version 6.0.0 of the Google Provider 

### ISSUE THREAD

**Issue by swati-chadha** [hashicorp/terraform-provider-google#18300]
We are planning to release version 6.0.0 of the Google providers in late August 2024. Major releases allow the provider to make breaking changes in a scheduled and publicized manner to help avoid unnecessary churn for our users.
Since the last major provider release in September 2023, we have been listening closely to the community's feedback. The upcoming major release primarily focuses on various enhancements and bug fixes that include breaking changes.
Support for earlier versions of Terraform will not change as a result of the major version release v6.0.0.

### **Notable Changes** 

**1. Opt-out default label “goog-terraform-provisioned”**

As a follow-up to the addition of provider-level [default labels](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#default_labels) in 5.0.0, the 6.0.0 major release will include an opt-out  default label “_goog-terraform-provisioned_”. This provider-level label “_goog-terraform-provisioned_” will be added to applicable resources to identify resources that were created by Terraform. This default label will only apply for newly created resources with a `labels` field. This will enable users to have a view of resources managed by Terraform when viewing/editing these resources in other tools like Cloud Console, Cloud Billing etc.

**The `label` “_goog-terraform-provisioned_” can be used for the following :** 

- **To filter on the Billing Reports page:**

     ![image](https://github.com/hashicorp/terraform-provider-google/assets/171057907/4c328272-3b03-4438-8235-4ff81f505251)

- **To view the Cost Breakdown:**

     ![image](https://github.com/hashicorp/terraform-provider-google/assets/171057907/18dec336-cd97-4f52-9b3b-dad488889e59)

- **The label can also be used with [BigQuery export.](https://cloud.google.com/blog/topics/cost-management/use-labels-to-gain-visibility-into-gcp-resource-usage-and-spending)**

An [opt-in version](https://github.com/GoogleCloudPlatform/magic-modules/pull/9808) of the label was already released in [5.16.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.16.0), and 6.0.0 will change the label to opt-out. To opt-out of this default label, users may toggle the [add_terraform_attribution_label](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#add_terraform_attribution_label) provider configuration field. This can be set explicitly using any release from 5.16.0 onwards and the value in configuration will apply after the 6.0.0 upgrade.

```
provider "google" {
  // opt out of “goog-terraform-provisioned” default label
  add_terraform_attribution_label = false
}
```

**2. Allow reducing the suffix length in “_name_prefix_”.**

Another notable issue to be resolved in the next major release is https://github.com/hashicorp/terraform-provider-google/issues/15374. The default value for “_name_prefix_” for all resources will change to have a shorter appended suffix, which would allow the user-input to be longer. 

For example, [google_instance_template.name_prefix](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#name_prefix)

**Comment by HAHGX** [comment]
Cool

**Comment by daanheikens** [comment]
@swati-chadha https://github.com/GoogleCloudPlatform/magic-modules/pull/10507 This PR was reverted due to an unexpected breaking change, Is it possible to also add this to this upcoming major release?

**Comment by c2thorn** [comment]
> @swati-chadha [GoogleCloudPlatform/magic-modules#10507](https://github.com/GoogleCloudPlatform/magic-modules/pull/10507) This PR was reverted due to an unexpected breaking change, Is it possible to also add this to this upcoming major release?

reopened https://github.com/hashicorp/terraform-provider-google/issues/17881 to track that.

**Comment by c2thorn** [comment]
TPG 6.0 is released! 
Release notes (GA): https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.0.0
Upgrade guide: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_6_upgrade

We also have a blog post summarizing the release and key changes:
https://cloud.google.com/blog/products/management-tools/announcing-terraform-google-provider-6-0-0

**Comment by c2thorn** [comment]
Closing this and the 6.0.0 milestone. Further updates and followups should be in https://github.com/hashicorp/terraform-provider-google/milestone/97
