### ISSUE TITLE
google_container_cluster doesn't support new "ENTERPRISE" Threat Detection

### ISSUE THREAD

**Issue by mikelaramie** [hashicorp/terraform-provider-google#18313]
GKE Enterprise Threat Detection requires setting the Security Posture Mode to "ENTERPRISE" which is not currently a [valid configuration option](https://github.com/hashicorp/terraform-provider-google/blob/82b9689a662df45187b80e2d8e953c8ad86ede0a/google/services/container/resource_container_cluster.go#L1024) for the provider.  

We'll need to update [gke_hub_fleet](https://github.com/hashicorp/terraform-provider-google/blob/82b9689a662df45187b80e2d8e953c8ad86ede0a/google/services/gkehub2/resource_gke_hub_fleet.go#L107) in the near future as well, however the API doesn't yet support this option so we shouldn't update the provider until then (b/344875848)

**Comment by mikelaramie** [comment]
I'll start work on a PR to add this check

**Comment by HAHGX** [comment]
+1
