### ISSUE TITLE
google_compute_autoscaler update error

### ISSUE THREAD

**Issue by natedogith1** [hashicorp/terraform-provider-google#18332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v4.84.0

### Affected Resource(s)

google_compute_autoscaler

### Terraform Configuration

```tf
resource "google_compute_autoscaler" "default" {
  provider    = google-beta
  project     = var.project_id
  name        = format("scal-%s",var.name)
  description = "Terraform-managed."
  zone        = var.zone
  target      = google_compute_instance_group_manager.default.id

  autoscaling_policy {
    max_replicas    = 10
    min_replicas    = 2
    cooldown_period = 900
    mode            = "ON"

    cpu_utilization {
      target = 0.99
    }
  }
  lifecycle {
    ignore_changes        = [ autoscaling_policy ]
  }
}


resource "google_compute_instance_group_manager" "default" {
  provider           = google-beta
  project            = var.project_id
  zone               = var.zone
  name               = format("mig-%s",var.name)
  description        = "Terraform-managed."
  base_instance_name = format("mig-%s",var.name)
  target_pools       = []
  wait_for_instances = false
  wait_for_instances_status = "STABLE"
  named_port {
    name = "https-443"
    port = 443
  }
  named_port {
    name = "https-8443"
    port = 8443
  }
  version {
    instance_template = var.default_version.instance_template
    name              = var.default_version.name
  }
  lifecycle {
    create_before_destroy = true
    ignore_changes        = [ version, update_policy, auto_healing_policies, ]
  }

  timeouts {
    create = "5m"
    update = "5m"
    delete = "15m"
  }
}

```

### Debug Output

```
Terraform will perform the following actions:
  # google_compute_autoscaler.default will be updated in-place
  ~ resource "google_compute_autoscaler" "default" {
      + description        = "Terraform-managed."
        id                 = <content removed>
        name               = <content removed>
        # (5 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

```
╷
│ Error: Error waiting for Updating Autoscaler: Required field 'resource.autoscalingPolicy.maxNumReplicas' not specified
│ 
│ 
│   with google_compute_autoscaler.default[0],
│   on main.tf line 37, in resource "google_compute_autoscaler" "default":
│   37: resource "google_compute_autoscaler" "default" {
│ 
╵
```

### Expected Behavior

Apply perform successfully

### Actual Behavior

Apply fails with message "Required field 'resource.autoscalingPolicy.maxNumReplicas' not specified"

### Steps to reproduce

1. `terraform apply`
2. Change min and max number of instances in GCP console to 0. (this also happens to clear the autoscaler description)
3. `terraform apply`

### Important Factoids

life_cycle is set to ignore autoscaling_policy changes.  I have not tested if setting the min and max replica numbers to 0 in the terraform directly also causes this problem.

b/345321691

**Comment by ggtisc** [comment]
Confirmed issue!

As user explains when `max_replicas` and `min_replicas` values are equal to 0 terraform returns the next error message:

╷
```
│ Error: Error waiting for Updating Autoscaler: Required field 'resource.autoscalingPolicy.maxNumReplicas' not specified
│ 
│   with google_compute_autoscaler.default[0],
│   on main.tf line 37, in resource "google_compute_autoscaler" "default":
│   37: resource "google_compute_autoscaler" "default" {
```

This could be an inconsistency, since both [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler#min_replicas) and [Google Cloud documentation](https://cloud.google.com/compute/docs/reference/rest/v1/autoscalers) is not specified that the value cannot be 0
