### ISSUE TITLE
How to use GKE `queued_provisioning` and set `reservation_affinity` to none?

### ISSUE THREAD

**Issue by davidxia** [hashicorp/terraform-provider-google#18341]
### Question

I'm trying to use the [GKE queued\_provisioning feature here](https://registry.terraform.io/providers/hashicorp/google/5.9.0/docs/resources/container_node_pool#queued_provisioning). But when I `terraform apply`, the GKE API errors with "Error: error creating NodePool: googleapi: Error 400: Queued\_provisioning requires reservation affinity to be set to none". Does anyone have a code snippet of how to do that?

**Comment by prasadmahendra** [comment]
@davidxia ran in the same issue. did you figure out a soln?

**Comment by prasadmahendra** [comment]
turns out it is node_config:

```reservation_affinity {
   consume_reservation_type = "NO_RESERVATION"
}```

**Comment by davidxia** [comment]
yes, that's correct. A fuller example.

```terraform
resource "google_container_node_pool" "my_node_pool" {
  # ... (other node pool configurations) ...
  queued_provisioning {
    enabled = true
  }
  node_config {
    # ... (other node configurations) ...
    reservation_affinity {
      consume_reservation_type = "NO_RESERVATION"
    }
  }
}
```
