### ISSUE TITLE
Failing test(s): TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteYumExample

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#18353]
### Impacted tests

- TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteYumExample

### Affected Resource(s)

- google_artifact_registry_repository

### Failure rates

- 100% since 2024-06-03

### Message(s)

```
        Error: Error creating Repository: googleapi: Error 400: Failed to validate remote upstream: generic::invalid_argument: no repodata/repomd.xml index file
          with google_artifact_registry_repository.my-repo,
          on terraform_plugin_test.tf line 2, in resource "google_artifact_registry_repository" "my-repo":
           2: resource "google_artifact_registry_repository" "my-repo" {
```

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/-4364509028806082671?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A160917%29%2Cid%3A2000000005)

b/345575953

**Comment by annakuo** [comment]
What is the upstream repository you are using?

**Comment by zli82016** [comment]
> What is the upstream repository you are using?

https://github.com/GoogleCloudPlatform/magic-modules

**Comment by annakuo** [comment]
@zli82016 Currently, we only support CentOS, Rocky, or EPEL as upstream repositories. Please see our public documentation: https://cloud.google.com/artifact-registry/docs/repositories/remote-overview#supported-os-upstreams

Support for custom upstream repositories is expected to be available in Q3.

**Comment by zli82016** [comment]
> @zli82016 Currently, we only support CentOS, Rocky, or EPEL as upstream repositories. Please see our public documentation: https://cloud.google.com/artifact-registry/docs/repositories/remote-overview#supported-os-upstreams
> 
> Support for custom upstream repositories is expected to be available in Q3.

@annakuo, this test is in the [Google provider repository](https://github.com/hashicorp/terraform-provider-google/blob/28396e737ca5cacc7d720dc41f6cf17cf7e74bc7/google/services/artifactregistry/resource_artifact_registry_repository_generated_test.go#L311). Based on the the [self-service program](https://g3doc.corp.google.com/cloud/graphite/terraform/self_service/g3doc/index.md?cl=head), it is owned by the artifactregistry service team. 

https://github.com/GoogleCloudPlatform/magic-modules is the  source code and upstream repository to generate the provider repositories.

**Comment by annakuo** [comment]
@zli82016 Oh got it. The example test used CentOS 8 as an upstream but it looks like it was archived on May 31, 2024 (https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/).

I've submitted a pull request to change the upstream from CentOS 8 to Rocky 9.

Thank you for raising this issue!
