### ISSUE TITLE
google_sql_database Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by TonyLegeay** [hashicorp/terraform-provider-google#18356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.32.0
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)

google_sql_database 

### Terraform Configuration

```
resource "google_sql_database" "sqlsv_db_mydb" {
  instance  = google_sql_database_instance.sql_server.name
  name      = "mydb"
  charset   = "UTF8"
  collation = "en_US.UTF8"
}
```

### Debug Output

module.projet.google_sql_database.sqlsv_db_mydb: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.projet.google_sql_database.sqlsv_db_mydb, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an        
│ unexpected new value: Root object was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected Behavior

Ressource created

### Steps to reproduce

1. resource "google_sql_database_instance" "sql_server" {
  name                = "sqlsv-myinstance-qrdo"
  region              = "europe-west9"
  database_version    = "SQLSERVER_2019_STANDARD"
  root_password       = "xxxxx"

  settings {
    tier              = "db-custom-4-3840"
    activation_policy = "ALWAYS"
    availability_type = "ZONAL"
    disk_autoresize   = true
  }
}
2. terraform apply
3. resource "google_sql_database" "sqlsv_db_mydb" {
  instance  = google_sql_database_instance.sql_server.name
  name      = "mydb"
  charset   = "UTF8"
  collation = "en_US.UTF8"
}
4. terraform apply

**Comment by ggtisc** [comment]
Hi @TonyLegeay  please provide the configuration of your `google_sql_database_instance` to replicate this issue and confirm the correct behavior of the resources.

**Comment by TonyLegeay** [comment]
Hi @ggtisc ,

Here is the configuration I've used :

`resource "random_string" "suffix" {
  length  = 4
  special = false
  upper   = false
}

resource "google_sql_database_instance" "sql_server" {
  name                = "sqlsv-${data.google_project.project.name}-${random_string.suffix.result}"
  region              = local.region
  database_version    = "SQLSERVER_2019_STANDARD"
  root_password       = var.sql_root_password
  deletion_protection = false

  settings {
    tier              = "db-custom-4-3840"
    activation_policy = "ALWAYS"
    availability_type = "ZONAL"
    disk_autoresize   = true
    disk_type         = "PD_SSD"
    user_labels = {
      "env_name"    = local.env_name
      "pos"         = local.pos
      "provisioner" = "terraform"
      "application" = local.app_name
      "type"        = "sqlserver_instance"
    }

    ip_configuration {
      ipv4_enabled    = false
      private_network = "projects/${local.ref_env.projects.host}/global/networks/${local.ref_env.vpc.name}"
    }

    backup_configuration {
      enabled                        = true
      start_time                     = "22:00"
      location                       = tolist(setsubtract(["europe-west1", "europe-west9"], [local.region]))[0]
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = 3
      backup_retention_settings {
        retained_backups = 7
        retention_unit   = "COUNT"
      }
    }

    maintenance_window {
      day          = 7 # jour de la semaine de 1 (lundi) à 7 (dimanche)
      hour         = 23
      update_track = "stable"
    }
  }
}`

**Comment by TonyLegeay** [comment]
Hi @ggtisc ,
I find the problem : 
It cames from the collation I was asking for the database : "en_US.UTF8" is a bad copy/paste from a postgresql configuration !
Sql Server collations : https://learn.microsoft.com/en-us/sql/t-sql/statements/windows-collation-name-transact-sql?view=sql-server-ver16#windows-collations
Even if error message could be more helpful, it's clearly not a bug.
I then close the case.
Thanks for having consider it.
