### ISSUE TITLE
Creation infinite loop when creating multiple google_monitoring_monitored_project

### ISSUE THREAD

**Issue by Mateusz-Nakonieczny** [hashicorp/terraform-provider-google#18363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform ~ v1.5.0
on <architecture>
+ provider registry.terraform.io/hashicorp/google v4.80

### Affected Resource(s)

google_monitoring_monitored_project

### Terraform Configuration

```tf
resource "google_monitoring_monitored_project" "monitored_projects" {
  for_each      = var.region == "europe-west2" ? toset(local.projects) : toset([])
  metrics_scope = local.management_project_id_euw2
  name          = each.value
}

locals {
  projects = [for prj in var.all_projects : prj if prj != local.management_project_id_euw2]
}
```

### Expected Behavior

Creation of 170 monitored projects (adding 170 to a scoped project hosting monitoring)

### Actual Behavior

Infinite loop of creation of the google_monitoring_monitored_project until the 60 min limit on agent deployed on a VM runs out and the process is stopped

google_monitoring_monitored_project.monitored_projects["prj-1"]: Still creating... [19m20s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-2"]: Still creating... [19m20s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-3"]: Still creating... [19m20s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-4"]: Still creating... [19m20s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-5"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-6"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-7"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-8"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-9"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-10"]: Still creating... [19m30s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-11"]: Still creating... [20m0s elapsed]
google_monitoring_monitored_project.monitored_projects["prj-12"]: Still creating... [20m0s elapsed]

### Steps to reproduce

1. `terraform init`
2. `terraform apply`

b/346403464

**Comment by Mateusz-Nakonieczny** [comment]
**Since posting the issue:**  
- Checked the same code with the google-beta provider in version 5.23.0 (latest), still the same outcome
- Added timeout for the resource creation set to 45min, still the same outcome
- The service account creating the resources (adding scoped projects) has the Monitoring Metrics Scopes Admin role on the folder level where all the projects are stored, still the same outcome
- The same SA has ingress and egress rules created for every perimeter that the scoped projects are in, still the same outcome

**Comment by ggtisc** [comment]
Hi @Mateusz-Nakonieczny Are you able to reproduce this issue with a lower number of projects? Also you could increase the timeout like in this [example](https://cloud.google.com/monitoring/api/ref_v3/rest/v1/locations.global.metricsScopes.projects#methods). Terraform registry reference [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_monitored_project#timeouts)

**Comment by Mateusz-Nakonieczny** [comment]
Hi, i managed to find and fix the issue, by using export TF_LOG=DEBUG; terraform <verb> |& tee output.log i saw that the Scoped project does not have Cloud Resource Manager API and Cloud Monitoring API enabled. The issue additionally was that the Read requests per minute - 600 in scoped project was not enough for the amount of linked projects, after requesting the limit to be raised to 6000 the issue resolved for good.

**Comment by Mateusz-Nakonieczny** [comment]
Hi, i managed to find and fix the issue, by using export TF_LOG=DEBUG; terraform |& tee output.log i saw that the Scoped project does not have Cloud Resource Manager API and Cloud Monitoring API enabled. The issue additionally was that the Read requests per minute - 600 in scoped project was not enough for the amount of linked projects, after requesting the limit to be raised to 6000 the issue resolved for good.
