### ISSUE TITLE
Error when applying changes to module google_bigquery_dataset_access.dset_access

### ISSUE THREAD

**Issue by anandnreddy** [hashicorp/terraform-provider-google#18438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

Terraform v1.1.6
on windows_amd64

### Affected Resource(s)

google_bigquery_dataset_access.dset_access

### Terraform Configuration

```# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/#formatters
formatter: markdown table

header-from: description.md
# footer-from: footer.md

# see: https://terraform-docs.io/user-guide/configuration/#sections
sections:
  show:
    - header
    - inputs
    - providers
    - modules
    - footer

# # see: https://terraform-docs.io/user-guide/configuration/#sort
sort:
  enabled: true
  by: required

settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
```

### Debug Output

this bug is happening when we run it on tekton pipeline.

### Expected Behavior

changes should have been made to access using the dset_access module.

### Actual Behavior

When applying changes to module.bq-dataset-access["user1"].google_bigquery_dataset_access.dset_access,
provider "provider["registry.terraform.io/hashicorp/google"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to reproduce

1. `Terraform Apply`

**Comment by ggtisc** [comment]
Hi @anandnreddy!

When you talk about the `dset_access` is it an argument or attribute like [these](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access#argument-reference) or a module created by yourself in your terraform project?

Please share your terraform code(resources, variables, locals, etc) to replicate this issue and see what is happening

**Comment by anandnreddy** [comment]
@ggtisc we have created a module based on provider module.

Please see our resource module 

module "bq-dataset-access" {
  source   = "tfregistry-bqyissfikq-uc.a.run.app/ABC/bigquery/gcp//modules/dset_access"
  for_each = var.bq_dataset_access

  project    = each.value.project
  dataset_id = each.value.dataset_id
  role       = each.value.role
  email      = each.value.email

}

variables.tf 
variable "bq_dataset_access" {
  description = "variabes for dataset user access"
  default     = {}

  type = map(
    object({
      project    = string
      dataset_id = string
      role       = string
      email      = string
    })
  )
}

**Comment by ggtisc** [comment]
@anandnreddy could you be more specific on your issue. You are just sharing general info that we don't have access to. If you are working with modules this is a pure terraform issue and not a Google provider issue. Or are you having issues with a specific Google resource? If that is the case please share the terraform based reproduction of the issue without using modules(resource(s) code and output)

**Comment by anandnreddy** [comment]
@ggtisc I am checking this internally to see if this is a terraform issue.
I will keep you posted in two days. Thanks

**Comment by anandnreddy** [comment]
> @ggtisc I am checking this internally to see if this is a terraform issue. I will keep you posted in two days. Thanks

This looks like a terraform issue, but still not able to get through this error, "Root resource was present but now absent"

**Comment by ggtisc** [comment]
No worries, I suggest you simplify the code and just create the `google_bigquery_dataset_access` resource like in this [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access) to see if there is something bad.
