### ISSUE TITLE
Provide support for subnet as a source filter in firewall

### ISSUE THREAD

**Issue by jderuere** [hashicorp/terraform-provider-google#1845]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.16.2.

### Affected Resource(s)
- google_compute_firewall

### Terraform Configuration Files

Google provide the possibility to specify a subnet as a source filter. It would be nice to have it in Terraform.

For example: 

```
resource "google_compute_subnetwork" "subnetwork" {
  name = "my-subnetwork"
  network = "my-network"
  ip_cidr_range = "10.0.4.0/22"
}

resource "google_compute_firewall" "subnetwork_firewall" {
  name = "${google_compute_subnetwork.subnetwork.name}-allow-tcp"
  network = "${google_compute_network.my_network.self_link}"
  source_subnets = [
    "${google_compute_subnetwork.subnetwork.name}"
  ]

  allow {
    protocol = "tcp"
    ports = [
      "1-65535"
    ]
  }
}
```

**Comment by danawillow** [comment]
Hey @jderuere, can you show me how you're currently specifying a subnet as a source filter? I don't see anything in the API or gcloud that allows you to specify the name, although you can already specify the range in your example like this:

```
resource "google_compute_subnetwork" "subnetwork" {
  name = "my-subnetwork"
  network = "my-network"
  ip_cidr_range = "10.0.4.0/22"
}

resource "google_compute_firewall" "subnetwork_firewall" {
  name = "${google_compute_subnetwork.subnetwork.name}-allow-tcp"
  network = "${google_compute_network.my_network.self_link}"
  source_ranges = [
    "${google_compute_subnetwork.subnetwork.ip_cidr_range}"
  ]

  allow {
    protocol = "tcp"
    ports = [
      "1-65535"
    ]
  }
}
```
Does that work for you?

**Comment by morgante** [comment]
@danawillow I believe this option does exist in the UI, but all it does is grab the range from the subnet and use that as the source filter for the API call. Maybe adding your example to the docs would be sufficient?

**Comment by danawillow** [comment]
Ah, ok! That's a good idea. I'm working on porting firewalls to magic modules right now so I'll add this as an example there.

**Comment by red8888** [comment]
So just so I understand the UI option just grabs the source range of the subnet?

So what happens if the subnet range changes? or if you destroy/create a subnet with the same name but diff range, does the UI option pick up that change?

Because in that case it doesn't just grab the subnet range it dynamically retrieves the range from the subnet, also in the UI it lists the "filter" as "Subnets:subnetName". Thats a lot more readable

**Comment by red8888** [comment]
> So just so I understand the UI option just grabs the source range of the subnet?
> 
> So what happens if the subnet range changes? or if you destroy/create a subnet with the same name but diff range, does the UI option pick up that change?
> 
> Because in that case it doesn't just grab the subnet range it dynamically retrieves the range from the subnet, also in the UI it lists the "filter" as "Subnets:subnetName". Thats a lot more readable

well nevermind, just tested this and if you add ranges of your subnets the UI actually refers to the "Source filters" as "Subnets". So looks like it is just purely a UI thing, it must check if you have a subnet with that range and show that in the UI

**Comment by upodroid** [comment]
@rileykarson We can close this issue.

**Comment by rileykarson** [comment]
Closing as we're unlikely to pick up this change at this point. Note that you can retrieve the value off the subnet, eg:

```
google_compute_subnetwork.public_subnetwork.ip_cidr_range

# or
google_compute_subnetwork.public_subnetwork.secondary_ip_range[0].ip_cidr_range
```
