### ISSUE TITLE
404 error on documents page

### ISSUE THREAD

**Issue by saeidskyboy** [hashicorp/terraform-provider-google#18484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

on Terraform Network Module doc section (for google), provided hyperlinks are not working and you will encounter an error "The page you requested could not be found." 

### New or Affected Resource(s)

![Capture](https://github.com/hashicorp/terraform-provider-google/assets/97639248/5eb02e04-a9c8-44b3-a93a-77024327ca9e)

### Potential Terraform Configuration

```tf 
```

### References

https://registry.terraform.io/modules/terraform-google-modules/network/google/modules/vpc
https://registry.terraform.io/modules/terraform-google-modules/network/google/modules/routes
https://registry.terraform.io/modules/terraform-google-modules/network/google/modules/network-firewall-policy

**Comment by SarahFrench** [comment]
Hi @saeidskyboy, could you please open an issue in [the module's repo here](https://github.com/terraform-google-modules/terraform-google-network)? This repo is for the Google provider and we don't control modules and their documentation.

**Comment by saeidskyboy** [comment]
thanks Sarah, will approach them
