### ISSUE TITLE
Fix minor typo `enforcment` in google_sql_database_instance resource

### ISSUE THREAD

**Issue by ml4** [hashicorp/terraform-provider-google#18490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

google/services/sql/resource_sql_database_instance.go:

line 496 as of today (5.34.0):
s/enforcement/enforcement/

### New or Affected Resource(s)

* google_sql_database_instance

b/349125214

**Comment by SarahFrench** [comment]
Note from triage: typo fix [on this line](https://github.com/hashicorp/terraform-provider-google/blob/3f71750462129bb6e885b5b9d3fb4cb7a4d8ba46/google/services/sql/resource_sql_database_instance.go#L496), and that change will cause documentation to be updated.

**Comment by jharshika** [comment]
Fixed the issue in https://github.com/GoogleCloudPlatform/magic-modules/pull/11275

**Comment by SarahFrench** [comment]
Thanks!
