### ISSUE TITLE
[Datastream] BigQueryDestinationConfig now includes `merge` and `Append-only` as configure write modes

### ISSUE THREAD

**Issue by Nakachi-S** [hashicorp/terraform-provider-google#18507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

https://cloud.google.com/datastream/docs/destination-bigquery#configure-write-mode
BigQueryDestinationConfig has added `merge` and `Append-only` as configure write mode.

https://cloud.google.com/datastream/docs/reference/rest/v1/projects.locations.streams#bigquerydestinationconfig

### New or Affected Resource(s)

google_datastream_stream

### Potential Terraform Configuration

```tf 
resource "google_datastream_stream" "test_stream" {
  stream_id    = "test-stream"
  location     = "us-central1"
  display_name = "test-stream"
  source_config {
    ...
  }
  destination_config {
    destination_connection_profile = google_datastream_connection_profile.bq_connection_profile.id
    bigquery_destination_config {
      merge {
      }
      # or
      append_only {
      }
    }
  }
}
```

b/349124712

**Comment by zekailiu-vis** [comment]
definitely need it!

**Comment by kubikb** [comment]
@Nakachi-S @zekailiu-vis  Pull request submitted: https://github.com/GoogleCloudPlatform/magic-modules/pull/11116

**Comment by kubikb** [comment]
@Nakachi-S @zekailiu-vis the PR has been merged into the Google Terraform provider's main branch. It should get released soon  https://github.com/hashicorp/terraform-provider-google/pull/18726

**Comment by zekailiu-vis** [comment]
@kubikb thanks

**Comment by Nakachi-S** [comment]
@kubikb 
Thank you!!!!
