### ISSUE TITLE
ServiceLevelObjective(SLO) goal limit should be increased to 0.9999

### ISSUE THREAD

**Issue by AmirBagaon** [hashicorp/terraform-provider-google#18556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v0.14.6
on linux amd64
+ provider registry.terraform.io/hashicorp/google v4.30.0

### Affected Resource(s)

google_monitoring_slo

### Terraform Configuration

```tf
```

### Expected Behavior

Recently Google updated their SLO goal to be in range of 0 < goal <= 0.9999.

[Link](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#resource:-servicelevelobjective:~:text=goal-,number,in%20order%20for%20this%20objective%20to%20be%20met.%200%20%3C%20goal%20%3C=%200.9999,-%2E).

### Actual Behavior

Error: goal 0.999900 must be > 0 and <= 0.999

### Steps to reproduce

1. `terraform apply`

b/354712173

**Comment by ggtisc** [comment]
Hi @AmirBagaon!

Everything is ok according to the [link](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#resource:-servicelevelobjective:~:text=goal-,number,in%20order%20for%20this%20objective%20to%20be%20met.%200%20%3C%20goal%20%3C=%200.9999,-%2E) you're sharing. 

So if this is a proposal for an enhancement please confirm this, but if that isn't the case share with us your `terraform code` and your output.

**Comment by AmirBagaon** [comment]
Thanks for the answer.
It seems that the current abillity of terraform is to support a goal up to 0.999 but not 0.9999. [Link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_slo#:~:text=The%20following%20arguments,0%20%3C%20goal%20%3C%3D%200.999).

Google recently updated it from 0.999 to 0.9999, as can be sink in the [link](The fraction of service that must be good in order for this objective to be met. 0 < goal <= 0.9999.) I provided.

If terraform does support 0.9999 goal, can you please share a link to the release notes?

**Comment by ggtisc** [comment]
@AmirBagaon according to the documentation on terraform registry it is what it is. On the other hand, if you have any official Google source that indicates otherwise, please share it to verify the topic.

**Comment by Khemi2024** [comment]
Hi @ggtisc, I can confirm that we can configure the SLO goal to: 0.999<goal<0.9999 (i.e 0.9995) via the console and rest but unable to do so through Terraform like @AmirBagaon mentioned.

Are you able to confirm whether the plan is to update Terraform to match the ability the console and rest offers in terms of SLO goal boundaries and if not explain the reasoning.

Thanks

**Comment by ggtisc** [comment]
Confirmed issue!

In Google Cloud documentation the value of the goal could be 0.9999 while in terraform can only be 0.999

**Comment by etruong42** [comment]
Possible fix: https://github.com/GoogleCloudPlatform/magic-modules/pull/11248
