### ISSUE TITLE
[documentation] Terraform google_gkeonprem_bare_metal_admin_cluster: Admin users assigned read-only permissions

### ISSUE THREAD

**Issue by raph687** [hashicorp/terraform-provider-google#18572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

terraform -v
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.25.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.31.0

### Affected Resource(s)

google_gkeonprem_bare_metal_admin_cluster

### Terraform Configuration

```tf
security_config {
    authorization {
      admin_users {
        username = "user@example.com"
      }
    }
  }
```

### Expected Behavior

The documentation mentions:
 "Users that will be granted the cluster-admin role on the cluster, providing full access to the cluster."

### Actual Behavior

After the cluster creation the users have read-only permissions. I believe this is the expected behaviour but that the documentation is outdated.

### References

[google_gkeonprem_bare_metal_admin_cluster#admin_users](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gkeonprem_bare_metal_admin_cluster#admin_users)

**Comment by hao-nan-li** [comment]
@naitianliu-google Could you help us to verify the expected behaviour of admin users in this case?

**Comment by naitianliu-google** [comment]
For VMware and bare metal user clusters, users will be granted the cluster-admin role on the cluster, which provides full administrative access to the cluster. For bare metal admin clusters, users will be granted the cluster-view role, which limits users to read-only access. 

It is described in the API doc https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/Authorization

We will update the terraform doc to make it consistent and avoid confusion.

**Comment by ggtisc** [comment]
Thanks @naitianliu-google!

@raph687 please confirm us if everything is clear now for you according to the [Google Cloud documentation](https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/Authorization)

**Comment by raph687** [comment]
Thansk to all of you for your quick responses.

> Thanks @naitianliu-google!
> 
> @raph687 please confirm us if everything is clear now for you according to the [Google Cloud documentation](https://cloud.google.com/anthos/clusters/docs/on-prem-api/reference/rest/v1/Authorization)

Yes the documentation is clear and reflects the actual behaviour of the adminUsers role in a bare metal admin cluster
