### ISSUE TITLE
Logging sink cannot recognise custom_writer_identity argument

### ISSUE THREAD

**Issue by sindhu-prakasam-oxb** [hashicorp/terraform-provider-google#18643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

google_logging_project_sink

### Terraform Configuration

```
resource "google_logging_project_sink" "log-bucket" {
  name        = var.sink_name
  description = var.sink_description
  # Destination Logging Bucket in Monitoring Project
  destination = "logging.googleapis.com/projects/${var.monitoring_project_id}/locations/${var.bucket_location}/buckets/${var.monitoring_logging_bucket_id}"
  # Filter condition for routing logs from sink to logging bucket
  filter                 = var.sink_filter
  unique_writer_identity = var.sink_unique_writer_identity
  # Service account with log writer permission
  custom_writer_identity = var.log_writer_sa
}
```

### Debug Output
╷
│ Error: Unsupported argument
│ 
│   on ../../../terraform-modules/log-router-sink/main.tf line 12, in resource "google_logging_project_sink" "log-bucket":
│   12:   custom_writer_identity = var.log_writer_sa
│ 
│ An argument named "custom_writer_identity" is not expected here.

### Actual Behavior

Not able to create sinks using terraform, getting the following error
` An argument named "custom_writer_identity" is not expected here.`

### Steps to reproduce

1. `terraform apply`

**Comment by ggtisc** [comment]
Hi @sindhu-prakasam-oxb!

I tried to replicate this issue, but everything was successful without errors. What terraform version and Google provider version are you using?

**Comment by sindhu-prakasam-oxb** [comment]
Hi @ggtisc ,
the issue was because of the terraform version. its solved now. 
Thanks.
