### ISSUE TITLE
Using terraform google provider can the same user account(or service account) be provided with the bigquery.DataViewer and bigquery.JobUser roles

### ISSUE THREAD

**Issue by shrikant-rajappan** [hashicorp/terraform-provider-google#18640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

 terraform --version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v4.49.0
+ provider registry.terraform.io/hashicorp/google-beta v4.49.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

google_bigquery_dataset_access
google_project_iam_member

### Terraform Configuration

```tf
```

### Expected Behavior

Requirement : Using terraform google provider can the same user account(or service account) be provided with the bigquery.DataViewer and bigquery.JobUser roles. This can easily be done from Google cloud console but we strictly use only IAC for production environments and console access for editing is denied for all.

We tried with two different approaches and in both cases the plan succeeds but apply fails : 

1) By using a Custom role with all the role permissions(listed out below) from both the roles

Error received is below :

```
> Request `Create IAM Members roles/gke_role_name serviceAccount:<*****>@<*****>.iam.gserviceaccount.com for project "*****"` returned error: Error applying IAM policy for project "*****"`: Error setting IAM policy for project "*****"`: googleapi: Error 400: Role roles/gke_role_name is not supported for this resource., badRequest

> │ 

> │   with google_project_iam_member.gke_role_name_member["roles/gke_role_name"],

> , in resource "google_project_iam_member" "gke_role_name_member":

> │  resource "google_project_iam_member" "gke_role_name_member" {
```

2) By directly defining two seperate resources each for google_bigquery_dataset_access and google_project_iam_member and assigning the same user account with both roles. 

Actually dataViewer was already provided :

This fails too with the error :

Error creating DatasetAccess: googleapi: Error 400: IAM setPolicy failed for Dataset <project-name>:<dataset>: Role roles/bigquery.JobUser is not supported for this resource., invalid

IMPORTANT NOTE : WE ARE NOT USING google_bigquery_dataset_access FOR DEFINING THE bigquery.JobUser ROLE INSTEAD WE DEFINE A google_project_iam_member RESOURCE AND GET THE SAME ERROR AS ABOVE 

something like below : 

```
resource "google_project_iam_member" "billing-dataset-access-jobuser" {

 for_each = local.queriers 
 project = local.cluster_project
 role = "roles/bigquery.jobUser"
 member = each.value
}

```

### Actual Behavior

We really need to understand why we are able to apply the same two roles to a user-account or service-account through the google console however cannot through the IAC which uses terraform google provider. Is this not an aberration ? Arent both the console and provider supposed to act in a similar manner ?

The use case is typical wherein an external service-account might need both these roles to run reporting jobs being run at an external service.

```
bq.dataViewer --> smallest/most granular resource it can be assigned to is dataset

bq.JobUser --> smallest/most granular resource it can be assigned to is project
```

We understand the dichotomy of this requirement that we cannot create the access using the same resource i.e., bigquery_dataset_access for the bq.JobUser and google_project_iam_member for the bq.dataViewer.

Because we believed that creating a custom roles with all these below permissions (this encompasses all permissions in bq.DataViewer and bq.Jobuser) : 

```
"bigquery.config.get",

"bigquery.datasets.get",

"bigquery.datasets.getIamPolicy",

"bigquery.jobs.create",

"bigquery.models.export",

"bigquery.models.getData",

"bigquery.models.getMetadata",

"bigquery.models.list",

"bigquery.routines.get",

"bigquery.routines.list",

"bigquery.tables.createSnapshot",

"bigquery.tables.export",

"bigquery.tables.get",

"bigquery.tables.getData",

"bigquery.tables.getIamPolicy",

"bigquery.tables.list",

"bigquery.tables.replicateData",

"dataform.locations.get",

"dataform.locations.list",

"dataform.repositories.create",

"dataform.repositories.list",

"resourcemanager.projects.get"

```

What is the approach to follow per the provider specification ? 

Especially when we wish to encompass all OR atleast subset of permissions from multiple roles.

### Steps to reproduce

1. `terraform apply`

**Comment by ggtisc** [comment]
Hi @shrikant-rajappan!

To replicate this issue and detect the bug please share us your terraform configuration code(everything that we need to replicate the issue). You could use examples like this for sensitive data:

project = "my-project"
org_id = 1234567890
user = "my-user@my-domain"

**Comment by shrikant-rajappan** [comment]
Here are the two approaches we tried where in the plan succeeds but the apply fails : 

1) Here are two resources defined to give different role access to all the queriers in billing_queriers local variable : 

resource "google_bigquery_dataset_access" "billing-access" {
  for_each      = local.billing_queriers
  project       = local.cluster_project
  dataset_id    = local.billing_dataset_id
  role          = "roles/bigquery.dataViewer"
  user_by_email = each.value
}

resource "google_project_iam_member" "billing-access-jobuser" {
  for_each      = local.billing_queriers
  project       = local.cluster_project
  role          = "roles/bigquery.jobUser"
  member        = each.value
}

2) The other approach we tried is to create a custom role which encompasses all permissions of both roles : 

resource "google_project_iam_custom_role" "costing" {
  role_id     = "costing"
  title       = "Dataset permissions for costing data"
  permissions = [
    "bigquery.config.get",
    "bigquery.datasets.get",
    "bigquery.datasets.getIamPolicy",
    "bigquery.jobs.create",
    "bigquery.models.export",
    "bigquery.models.getData",
    "bigquery.models.getMetadata",
    "bigquery.models.list",
    "bigquery.routines.get",
    "bigquery.routines.list",
    "bigquery.tables.createSnapshot",
    "bigquery.tables.export",
    "bigquery.tables.get",
    "bigquery.tables.getData",
    "bigquery.tables.getIamPolicy",
    "bigquery.tables.list",
    "bigquery.tables.replicateData",
    "dataform.locations.get",
    "dataform.locations.list",
    "dataform.repositories.create",
    "dataform.repositories.list",
    "resourcemanager.projects.get"
  ]
}

resource "google_service_account" "costing_sa" {
  account_id   = "costing-sa"
  display_name = ""
}

resource "google_project_iam_member" "sa_custom_role_binding" {
  for_each = toset([
    "roles/costing",
  ])

  project = local.cluster_project
  role    = each.value
  member  = "serviceAccount:${google_service_account.costing_sa.email}"
}

resource "google_bigquery_dataset_access" "billing_access" {
  for_each    = local.billing_queriers
  project     = local.cluster_project
  dataset_id  = local.billing_dataset_id
  role        = "roles/costing"
  user_by_email = each.value
}

Please do advise if our approaches are not per provider specification.


Thank you

**Comment by shrikant-rajappan** [comment]
hi @ggtisc 
Thank you for testing this out and sharing your code.

I have one callout though - are you using both Custom_role as well as bq.JobUser + Dataviewer resources to provide access to the SA ?

Would it be recommended to add the iam_binding resource as well in either of the two approaches ?

Br,
Shrikant R

**Comment by ggtisc** [comment]
I can't tell you which is better, because it depends on your requirements and this goes beyond attending bugs, but I can provide you the documentation of [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam_custom_role), [API](https://cloud.google.com/iam/docs/reference/rest/v1/projects.roles) and [Google Cloud](https://cloud.google.com/iam/docs/roles-overview#custom).

**Comment by shrikant-rajappan** [comment]
Thank you for your time in looking into the issue. We are now able to make it work with the custom_role option with a subset of permissions.

**Comment by ggtisc** [comment]
It was a pleasure have a good coding :)
