### ISSUE TITLE
Failing test(s): TestAccComputeProjectCloudArmorTier_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18659]
### Impacted tests

- TestAccComputeProjectCloudArmorTier_modify
- TestAccComputeProjectCloudArmorTier_basic

### Affected Resource(s)

- google_compute_project_cloud_armor_tier

### Failure rates

- 100% since 2024-06-04

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccComputeProjectCloudArmorTier_modify
=== PAUSE TestAccComputeProjectCloudArmorTier_modify
=== CONT  TestAccComputeProjectCloudArmorTier_modify
    vcr_utils.go:152: Step 1/6 error: Error running apply: exit status 1
        Error: Error waiting to create ProjectCloudArmorTier: Invalid value for field 'cloudArmorTier': 'CA_STANDARD'. Setting the managed protection tier for projects enrolled in Cloud Armor Enterprise Annual Subscription is currently not supported. Please use the cloud console instead.
          with google_compute_project_cloud_armor_tier.cloud_armor_tier_config,
          on terraform_plugin_test.tf line 2, in resource "google_compute_project_cloud_armor_tier" "cloud_armor_tier_config":
           2: resource "google_compute_project_cloud_armor_tier" "cloud_armor_tier_config" {
--- FAIL: TestAccComputeProjectCloudArmorTier_modify (3.77s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-6779018165755433774?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/351842804

**Comment by SarahFrench** [comment]
Our nightly test project might need to be enrolled for this feature, judging from [this comment on the PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10698#issuecomment-2125885540)

**Comment by zli82016** [comment]
The tests passed after unenrolling the annual protection mode.
