### ISSUE TITLE
Failing test(s): TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update, 

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18657]
### Impacted tests

- TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update
- TestAccKmsCryptoKeyVersion_externalProtectionLevelOptionsVpc

### Affected Resource(s)

- google_XXXXX

### Failure rates

- 100% since 2024-06-15

### Message(s)

```
=== RUN   TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update
=== PAUSE TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update
=== CONT  TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update
    vcr_utils.go:152: Step 1/4 error: Error running apply: exit status 1
        Error: Error creating EkmConnection: googleapi: Error 400: Certificate error: Certificate is expired.
          with google_kms_ekm_connection.example-ekmconnection,
          on terraform_plugin_test.tf line 19, in resource "google_kms_ekm_connection" "example-ekmconnection":
          19: resource "google_kms_ekm_connection" "example-ekmconnection" {
--- FAIL: TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update (4.14s)
FAIL
```

### Nightly build test history

- [TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update](https://hashicorp.teamcity.com/test/736084826770840719?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true)
- [TestAccKmsCryptoKeyVersion_externalProtectionLevelOptionsVpc](https://hashicorp.teamcity.com/test/4704038950514810944?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true)

b/351843139

**Comment by SarahFrench** [comment]
[These tests depend on a certificate that's stored in a secret](https://github.com/GoogleCloudPlatform/magic-modules/blob/01ead35aa4858e7a1a9fddede50853eeb3ec0e6b/mmv1/third_party/terraform/services/kms/resource_kms_ekm_connection_test.go#L46-L62) and isn't managed by the test itself, and that certificate has expired.

**Comment by tdbhacks** [comment]
I've asked the EKM team to update the test cert and possibly use something with a long validity, I'll let you know when complete.

**Comment by rishamchokshi** [comment]
Certs should be updated, tests should be picking up the new values

**Comment by tdbhacks** [comment]
@SarahFrench whenever you have a couple mins, let us know if the tests are still failing or if we can close this issue

**Comment by SarahFrench** [comment]
Both TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update and TestAccKmsCryptoKeyVersion_externalProtectionLevelOptionsVpc have passed in the past 2 nights, closing
