### ISSUE TITLE
google_firebase_project should mention the need for user_project_override provider flag

### ISSUE THREAD

**Issue by serpro69** [hashicorp/terraform-provider-google#18668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Tried using [`firebase_project`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_project) resource and was facing the below error:

```
module.project.google_firebase_project.main: Creating...
╷
│ Error: Error checking if Firebase is already enabled: googleapi: Error 403: Your application is authenticating by using local Application Default Credentials. The firebase.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/32555940559",
│       "service": "firebase.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]

```

Even though I've had quota project set for ADC, it still didn't work and threw the same error.

Then while browsing through issues in the repo, I've stumbled upon #17713 that had some code examples, and I saw they they were setting [`user_project_override`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#user_project_override) for the provider that was managing firebase resources.
After trying the same in my code - it finally worked.

While the docs do say:

> This resource supports [User Project Overrides](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#user_project_override).

I think it would be beneficial to include that this actually must be set to `true` for this resource.

### New or Affected Resource(s)

* google_firebase_project

b/351843115

**Comment by rainshen49** [comment]
Hey @serpro69, just to gather a bit more information, which environment are you running Terraform from? Is it from your local machine or a Cloud environment? If from local machine, are you using `terraform` directly, or via some wrapper cli? If it's a Cloud environment, is it from the [Cloud Shell](https://cloud.google.com/shell/docs/open-in-cloud-shell) or somewhere else?

**Comment by serpro69** [comment]
Hi @rainshen49 ,
I'm running terrafrom from local machine.
I have a makefile that runs terraform commands, but it doesn't do anything special really: https://github.com/serpro69/terraform-makefile/blob/d3ed3acbd8e1932464031babfba581e8ff0ea70d/Makefile#L179

I tried now to run with just `terraform` executable directly and it produces the same results - if I don't set `user_project_override` for the `google_firebase_project` resource - I get an error.

I'm authenticating via ADC from local machine, and I have a quota project set via `gcloud auth application-default set-quota-project`

**Comment by rainshen49** [comment]
@melinath the [documentation template](https://github.com/GoogleCloudPlatform/magic-modules/blob/19e0c3ede2b509b767d13ae4eac4635eabbbb056/mmv1/templates/terraform/resource.html.markdown.erb#L225) hard-codes "This resource supports User Project Overrides". Should we add a variant like "This resource requires User Project Overrides"?

**Comment by melinath** [comment]
Supporting a variant would require adding a way to configure a variant and modifying the template to support it - I'd be a little hesitant to do that _now_ because it wouldn't be a simple change (and we're in the middle of switching the core generation logic to use Go instead of ruby). Alternatives would be:

- Switch the docs to a handwritten file so that you can alter that text.
- Update examples to include setting `user_project_override = true`
- add a [resource-level warning](https://googlecloudplatform.github.io/magic-modules/develop/resource-reference/#docs) about the requirement

**Comment by serpro69** [comment]
Just a humble opinion from my side - updating examples is usually a good approach (and should be done anyways because otherwise the examples aren't actually working, right?). Many people also tend to look at example code more often than read full documentation.

On a side note, I think this applies to more than just the resource mentioned in this issue. I think I've encountered at least a few more resources where `user_project_override = true` was a must (and I'd guess there's likely more), but the example code didn't contain that, and the docs only mentioned "the resource supports user project override"; basically same as the original issue.
So maybe updating the provider documentation would also help? E.g., a note that describes in which cases should `user_project_override` be set to `true`. 
For example, in the [firebase terraform](https://firebase.google.com/docs/projects/terraform/get-started) documentation, it says that `user_project_override = true` can be used for pretty much everything (maybe related to that tutorial only though?) except for initial project creation and enabling services. Not sure if that's actually the case for things beyond firebase, for example, and how up to date that example code is (the provider version is `~> 4.0` , so maybe not very up-to-date?), but I think it kind of highlights the problem I'm trying to describe here - lack of documentation on when this provider parameter is needed or not.
It's probably not a big issue for a person who's worked with terraform google provider for awhile, but for a newcomer, this info is quite hard to put together and make sense of I'd say (from personal experience)

**Comment by rainshen49** [comment]
@serpro69 The example in the [Firebase terraform](https://firebase.google.com/docs/projects/terraform/get-started#general-workflow-set-up-provider) documentation has two flavors of the google-beta provider, one with `user_project_override = true` and the other without, and your instinct is right, Firebase recommends user_project_override for other resources in simple use cases. However, that's only a recommendation because there are advanced use cases that call for a different quota/billing project. You can read more about it in the collapsible [here](https://firebase.google.com/docs/projects/terraform/get-started#faq-understand-project-related-attributes)

The examples in [Terraform registry](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/firebase_project) are resource-scoped. So it doesn't contain the `provider "google-beta" {}` config. Once the provider is configured with `user_project_override`, no change in the resource itself is needed. I've added a resource-level note per @melinath 's recommendation.

**Comment by serpro69** [comment]
> Once the provider is configured with `user_project_override = true`, no change in the resource block itself is needed.

Yes, that's exactly what I'm doing now, after having figured out how this works.

> However, if someone just copy-pasted the example without additional provider config, it won't work. I've added a resource-level note per @melinath 's recommendation.

This is how my first attempt at using this resource was - just copy-pasting the example in hopes it would work :grin: which led to me opening this issue so that the docs can be improved, hopefully being more helpful for someone who comes to use this resource for the first time and will struggle like me :) Thanks a lot for taking the time to improve this!
