### ISSUE TITLE
Add google_spanner_instance data source

### ISSUE THREAD

**Issue by maguro** [hashicorp/terraform-provider-google#1866]
### Terraform Version
Terraform v0.11.7
+ provider.google v1.13.0

### Affected Resource(s)
google_spanner_instance

It would be nice of there was a `google_spanner_instance` data source.  Sometimes one needs to add a `google_spanner_database` inside a pre-existing `google_spanner_instance`.

**Comment by chrisst** [comment]
@maguro does https://www.terraform.io/docs/providers/google/r/spanner_instance.html not work for you?
