### ISSUE TITLE
Deleted SA no longer returns empty email to TF - still present in 5.35.0

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/terraform-provider-google#18709]
@mbrancato @jlosito 
I have such issue (provider.google v3.90.1, Terraform v0.12.31)

the problem is appear only if SA was deleted:
if SA never created `data` return resource with empty `email` (it's ok)
after creation and remove SA - API return forbidden

_Originally posted by @marfenij in https://github.com/hashicorp/terraform-provider-google/issues/11208#issuecomment-1161480217_

**Comment by GavBurke** [comment]
The above issue was closed over 12 months ago but a solution never provided, and this issue is still happening today.

Using `data "google_service_account"` on a Service Account that doesn't exist returns blank email and we can handle the null in Terraform; using that on a Service Account that firstly does exist but then later does not then fails Terraform with error of

`Error: projects/-/serviceAccounts/<sa_name>@<project>.iam.gserviceaccount.com not found with data.google_service_account.analyst_admn_dp_alt_service_account, on data-providers.tf line 63, in data "google_service_account" "analyst_admn_dp_alt_service_account": 63: data "google_service_account" "analyst_admn_dp_alt_service_account" {`

**Comment by rileykarson** [comment]
This was inconsistent before (and these bugs seem to indicate it was inconsistent within the resource itself) but we intentionally always return errors in these cases as of `5.0.0`: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade#datasources-now-error-universally-on-404

**Comment by GavBurke** [comment]
Thanks for the reply @rileykarson 

That section specifically says "non-IAM", which this SA is presumably an IAM, so not sure it's applied here?

Especially when, if we are deploying to an environment where the SA has never existed, the code still works using a data source with a none-existent SA.  We currently do the following, a small snippet of the code, if there's any "upgrade path" to have this working with SA's that existed in IAM but then were deleted??

```
locals {
  prefix = var.deploy_to_alternative ? "${var.base_prefix}-${var.alternative_prefix}" : var.base_prefix
  alt_prefix = var.deploy_to_alternative ? var.base_prefix : "${var.base_prefix}-${var.alternative_prefix}"

  role_members_analyst_read_only = concat(
    (data.google_service_account.analyst_admn_dp_service_account.email != null ? ["serviceAccount:${local.prefix}-an-admn-dp@${var.project}.iam.gserviceaccount.com"] : []),
    (data.google_service_account.analyst_admn_dp_alt_service_account.email !=null ? ["serviceAccount:${local.alt_prefix}-an-admn-dp@${var.project}.iam.gserviceaccount.com"] : [])
)
}

data "google_service_account" "analyst_admn_dp_service_account" {
  account_id = "${local.prefix}-an-admn-dp"
  project    = var.project
}

data "google_service_account" "analyst_admn_dp_alt_service_account" {
  account_id = "${local.alt_prefix}-an-admn-dp"
  project    = var.project
}
```

**Comment by rileykarson** [comment]
IAM in that context refers to datasources based on getIamPolicy like https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/dataproc_cluster_iam_policy!

I'm not sure what the upgrade path here is, unfortunately. HashiCorp's decision on the matter was recorded at https://github.com/hashicorp/terraform/issues/16380#issuecomment-517282340 and the recommendation for providers in the SDK is to return an error. We were inconsistently compliant in the past. (We didn't blindly apply that recommendation and found null returns were dangerous ourselves as well- we've had incidents where users had unintentionally applied a configuration with null values from datasources that was therefore incorrect, sometimes missing security settings)
