### ISSUE TITLE
support multiple ports in cloud_run_v2_service

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/terraform-provider-google#18723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Right now, we can only specify a single port for `cloud_run_v2_service`.

This is noted in the docs:

> ports - (Optional) List of ports to expose from the container. Only a single port can be specified. The specified ports must be listening on all interfaces (0.0.0.0) within the container to be accessible. If omitted, a port number will be chosen and passed to the container through the PORT environment variable for the container to listen on Structure is documented below.

Trying to use multiple `ports` blocks results in a **Terraform** validation error. So this happens purely in Terraform, before any interaction with GCP's api.

```
│ Error: Too many ports blocks
│
│   on foo.tf line 131, in resource "google_cloud_run_v2_service" "foo":
│  131:       ports {
│
│ No more than 1 "ports" blocks are allowed
```

### New or Affected Resource(s)

* `google_cloud_run_v2_service`

### Potential Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "default" {
  provider = google-beta
  name     = "cloudrun-service"
  location = "us-central1"
  launch_stage = "BETA"
  ingress = "INGRESS_TRAFFIC_ALL"
  template {
    containers {
      name = "hello-1"
      ports {
        container_port = 8080
      }
      ports {
        container_port = 8888
      }
      image = "us-docker.pkg.dev/cloudrun/container/hello"
      depends_on = ["hello-2"]
      volume_mounts {
        name = "empty-dir-volume"
        mount_path = "/mnt"
      }
    }
    volumes {
      name = "empty-dir-volume"
      empty_dir {
        medium = "MEMORY"
        size_limit = "256Mi"
      }
    }
  }
}
```

### References

Note that the underlying GCP API takes an array of ports:

https://cloud.google.com/run/docs/reference/rest/v2/Container

b/352830724

**Comment by rileykarson** [comment]
Can you confirm this is possible in the API? Their documentation at https://cloud.google.com/run/docs/reference/rest/v2/Container still states: `Only a single port can be specified.`

**Comment by StephenWithPH** [comment]
> Can you confirm this is possible in the API?

Arg. I suspect you're right. Although their API's _signature_ supports multiple ports, there are strong hints that GCP itself does not.

See the details/contents of both of these public GCP issues:
- https://issuetracker.google.com/issues/301461129
- https://issuetracker.google.com/issues/300604199

Some Google automation also added `b/352830724` to this issue. That bug doesn't seem publicly-viewable in GCP's issue tracker, but there might be additional, useful context there.

**Comment by bskaplan** [comment]
Cloud Run only accepts one port. The API signature supports multiple for compatibility with Knative/Kubernetes, but the API will give an error if more than one port is provided.
