### ISSUE TITLE
google_dialogflow_cx_security_settings isn't consistently create-able

### ISSUE THREAD

**Issue by mmurakowski-verily** [hashicorp/terraform-provider-google#18735]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

google_dialogflow_cx_security_settings

### Terraform Configuration

```tf
resource "google_dialogflow_cx_security_settings" "security_settings" {
  location            = "global"
  display_name        = "mmurakowski-local-testing-01"
  redaction_strategy  = "REDACT_WITH_SERVICE"
  redaction_scope     = "REDACT_DISK_STORAGE"
  inspect_template    = google_data_loss_prevention_inspect_template.possible_inspect_template.id
  deidentify_template = google_data_loss_prevention_deidentify_template.redact_template.id
  purge_data_types    = ["DIALOGFLOW_HISTORY"]
}
```

### Debug Output

https://paste.googleplex.com/6011683166486528#

### Actual Behavior

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.assistant-dialogflow-t1d-agent.google_dialogflow_cx_security_settings.security_settings,
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Steps to reproduce

1. `terraform apply`

### Important Factoids

Me and Riley discussed already. Looks like the securitySettings API isn't consistent; it returns a success response before the resource is GETable.

b/353774151

**Comment by ggtisc** [comment]
Confirmed issue!

@mmurakowski-verily team is actively trying to create a security settings object with terraform, and this was confirmed by @rileykarson. Among other things there are a couple of arguments that are not in the Argument reference section of [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_security_settings#argument-reference) in comparison with [API documentation](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/projects.locations.securitySettings):

- name
- deidentifyTemplate
- purgeDataTypes[]
- audioExportSettings
- insightsExportSettings
- retentionWindowDays
- retentionStrategy
