### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by parag-warudkar-ck** [hashicorp/terraform-provider-google#18770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.2.7
on amd64
+ provider registry.terraform.io/hashicorp/google Issue happens both on 4.84 and 5.x
+ provider registry.terraform.io/hashicorp/google-beta Not used

We have pipelines that automate creation of service accounts and once a day or so we will run into the following error -

```
When applying changes to
│ module.cktest_wlid.google_service_account.service_gsa["zone::pipeline::dp-default"],
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.cktest_wlid.google_service_account.service_gsa["zone::pipeline::some-name-default"],
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
When this happens the resource in question is (eventually) created but not imported in the Terraform state. So this results in the next automated pipeline apply failing with resource already exists error. It is painful to then either manually import or delete it from the backend and let it recreate the resource.  

### Affected Resource(s)

google_service_account right now but it has happened with other resources as well - google_firestore_database for example.

### Terraform Configuration

```tf
resource "google_service_account" "service_gsa" {
  for_each   = { for x in local.wl_services : "${x.clusterNameShort}::${x.namespace}::${x.componentName}" => x }
  account_id = each.value.acctId"

  display_name = "${each.value.clusterNameShort}:${each.value.namespace}:${each.value.componentName}"
  project      = each.value.project
}
```

### Expected Behavior

Resource should have been created and imported into the Terraform state.

### Actual Behavior

Resource is eventually created but Terraform fails and doesn't import state.

### Steps to reproduce

1. `terraform apply`

### References

https://support.hashicorp.com/hc/en-us/articles/1500006254562-Provider-Produced-Inconsistent-Results

**Comment by ggtisc** [comment]
Hi @parag-warudkar-ck!

If you are using 3rd party pipelines you need to check your logs and the configuration you have, otherwise if you are using Google Cloud pipelines ([google_clouddeploy_delivery_pipeline](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/clouddeploy_delivery_pipeline)) please share your terraform configuration to replicate this issue.

**Comment by parag-warudkar-ck** [comment]
Hi @ggtisc - to clarify, this has nothing to do with any 3rd party or Google pipelines - what I referred to by pipeline is nothing more than a script that runs terraform apply in the most standard fashion - just that it is automated invocation.

**Comment by parag-warudkar-ck** [comment]
I guess I will repeat my earlier comment that there is no pipeline involved, 3rd party or otherwise! This is plain and simple terraform apply that is done via a shell script. It's literally that piece of terraform code applied using terraform apply in a script that runs as cron job (oh boy hopefully not a cron bug I have to file against debian 😃 )

**Comment by ggtisc** [comment]
Thanks for clarifying things @parag-warudkar-ck 

I tried to replicate this issue but the result was successful without errors using the terraform registry [examples](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account)

In your provided code you have some values that we don't have access to(locals), or you could simplify your code by assigning directly the value of these locals. Please share the full code to replicate this issue. In case you have sensitive data you could use examples like:

- project = "my-project"
- org_id = "1234567890"
- user = "my-user@my-domain.com"

**Comment by parag-warudkar-ck** [comment]
Well it would have been a never works issue if the examples didn't work :)  What you need here is to scale up the number of service account and bindings resources in a Terraform workspace/state to reproduce the issue. One way to do that trivially is to -

- Write a terraform module that has a for_each loop that iterates over a bunch of inputs specified in yaml for mass creating service accounts
```tf
resource "google_service_account" "service_gsa" {
  for_each   = { for x in local.wlid_services : "${x.clusterNameShort}::${x.namespace}::${x.componentName}" => x }
```
- Add some dummy workload identity style bindings to create a dependency chain  / add resources to the state - not sure this matters but it does help 
```tf
resource "google_service_account_iam_member" "service_gsa_wi_binding1..12" {
  for_each           = { for x in local.wlid_services : "${x.clusterNameShort}::${x.namespace}::${x.componentName}" => x }
  service_account_id = google_service_account.service_gsa["${each.value.clusterNameShort}::${each.value.namespace}::${each.value.componentName}"].name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:${each.value.clusterProject}.svc.id.goog[${each.value.namespace}/${replace(each.value.repoName, "_", "-")}.${each.value.componentName}]"
}
```
- Write a python script to generate a YAML spec for the tf module input that goes in local.wlid_services 
```yaml
env: production
clusterNameShort: 4-letter-anything
componentName: my-service-consumer-sa
serviceProject: gcp-project-blah
clusterProject: some-other-gcp-project
namespace: random-any-namespace
repoName: whatever-string
shortWLID: false
```
- Write a calling module to parse all the YAMLs and create the services data structure like this -
```tf
locals{
    wlid_services = {
    for f in fileset(path.module, "yamls/wlid*.yml") :
        format("%s-%s",basename(dirname(f)),trimsuffix(basename(f), ".yml")) => yamldecode(file(f))
    }
}
```
- Then pass that along to the module in var.services 

If you can automate adding a new yaml and doing a tf apply - as you approach few 10s of yamls you should see the error pop up. We pin our google provider version to 4.84 but any lower / higher version should work worse or better.

Let me know if you need me to clean up our production module/caller code and give you a ready made working sample, that is a bit of work - but I think the above should make it really easy for you to implement something that can mass create service accounts and bindings. You can use any other test approach as long as you can create a bunch of SAs and bindings in the TF state.

**Comment by ggtisc** [comment]
Due to the number of configurations we need the complete code or if you can upload an example to a public repository it could also work

**Comment by parag-warudkar-ck** [comment]
The code is the same - there is enough in the sample code I posted above to create a bunch of yaml files that the TF code iterates over using for_each, should be trivial to use a for_each construct  - it's just to create a bunch of service account resources and 10 bindings for each - doesn't matter which - but if you can't do that, welp - I will close it and follow up internally with the TAM. (I don't know if I can share the full code without consulting internally.)
