### ISSUE TITLE
Add deletion_protection field to Project resource

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#18775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add tags and deletion_protection field to Project resource

### New or Affected Resource(s)

* google_project

### Potential Terraform Configuration

```tf 
```

b/360011414

**Comment by ggtisc** [comment]
The [skip_delete](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project#skip_delete) argument looks similar to the purpose of the proposed new argument `deletion_protection`. On the other hand currently there isn't any argument to manage `tags`

**Comment by c2thorn** [comment]
`deletion_policy` will be released with 6.0. splitting off `tags` into its own issue for better tracking: https://github.com/hashicorp/terraform-provider-google/issues/19166
