### ISSUE TITLE
Minor documentation issue in google_compute_reservation block. change (Output) to (Optional)

### ISSUE THREAD

**Issue by hashkanna** [hashicorp/terraform-provider-google#18861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Documentation issue:
`in_use_count should be (Optional) instead of (Output)` in google_compute_reservation in the link below
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_reservation#specific_reservation

### New or Affected Resource(s)

* google_compute_reservation

### Potential Terraform Configuration

```tf 
```

**Comment by SarahFrench** [comment]
From triage: this field is [currently marked as output](https://github.com/GoogleCloudPlatform/magic-modules/blob/c683f810a51f5d129527bbdde5a2eb132077e528/mmv1/products/compute/Reservation.yaml#L176), and that determines what's shown in the documentation. The API shows that this field is output only:

![Screenshot 2024-07-29 at 18 10 44](https://github.com/user-attachments/assets/76af39c8-4fbc-4819-88b1-f6f4b90a0962)

I'll close this issue, but will re-open if there's more to it!
