### ISSUE TITLE
google_datastream_stream.destination_config.bigquery_destination_config breaking change

### ISSUE THREAD

**Issue by bloom-alex** [hashicorp/terraform-provider-google#18890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.2
on ARM
+ provider registry.terraform.io/hashicorp/google v5.39.0

### Affected Resource(s)

google_datastream_stream

### Terraform Configuration

```tf
resource "google_datastream_stream" "stream_data_science" {
  project = var.data_science_project

  backfill_all {}
  desired_state = "RUNNING"
  destination_config {
    bigquery_destination_config {
      data_freshness = "900s"
      // merge {}
      source_hierarchy_datasets {
        dataset_template {
          location = var.region
        }
      }
    }
    destination_connection_profile = google_datastream_connection_profile.destination.id
  }
  display_name = "stream-data-science"
  location     = var.region
  source_config {
    postgresql_source_config {
      include_objects {
        postgresql_schemas {
          schema = local.schema_name
        }
      }
      max_concurrent_backfill_tasks = 0
      publication                   = "datastream_publication"
      replication_slot              = "datastream_replication_slot"
    }
    source_connection_profile = google_datastream_connection_profile.source.id
  }
  stream_id = "stream-data-science"
}
```

### Expected Behavior

This was a valid terraform resource configuration before 5.39.0 and will now fail with the following error message 

```
"destination_config.0.bigquery_destination_config.0.append_only": one of `destination_config.0.bigquery_destination_config.0.append_only,destination_config.0.bigquery_destination_config.0.merge` must be specified
```

### Actual Behavior

The documentation states that both merge and append_only blocks are optional and that merge is the default behavior. I wouldn't mind just having to add merge {} as part of the bigquery_destination_config but it also flags the resource as needing replacement.

Expected behavior: either no change or letting us add merge to reflect the default behavior without to recreate the resource

### Steps to reproduce

1. `terraform apply`

**Comment by c2thorn** [comment]
Confirmed the breaking change. Fix-forwarding with https://github.com/GoogleCloudPlatform/magic-modules/pull/11292 and will create a patch release v5.39.1 with the fix.

**Comment by c2thorn** [comment]
https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.39.1 has released with the fix. The two new fields are no longer required
