### ISSUE TITLE
Add deletion_protection field to Folder resource

### ISSUE THREAD

**Issue by abd-goog** [hashicorp/terraform-provider-google#18904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add tags and deletion_protection field to Folder resource

### New or Affected Resource(s)

* google_folder

### Potential Terraform Configuration

```tf 
```

b/356428084

**Comment by melinath** [comment]
I've tweaked the title to only cover the deletion_protection field since that's a breaking change in 6.0.0 (but adding the tags field could come after 6.0.0 and will not be breaking.)

**Comment by c2thorn** [comment]
closed with https://github.com/hashicorp/terraform-provider-google/pull/19021

**Comment by SarahFrench** [comment]
@c2thorn heads up that the scope of this issue changed

**Comment by c2thorn** [comment]
Moving out of 6.0 since the breaking change part is already completed (deletion_protection)

**Comment by c2thorn** [comment]
Actually I think I will split the issues

**Comment by c2thorn** [comment]
closing as deletion_protection has been added, and I've opened https://github.com/hashicorp/terraform-provider-google/issues/19165
