### ISSUE TITLE
Failing test(s): TestAccNetappVolume_netapp*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18909]
### Impacted tests

- TestAccNetappVolume_netappVolumeBasicExample_update
- TestAccNetappbackup_netappBackupExample
- TestAccNetappbackup_netappBackupFull_update

### Affected Resource(s)

- google_netapp_backup_vault

### Failure rates

- 100% since June/July 2024 across the 3 tests

### Message(s)

```
    vcr_utils.go:152: Step 11/16 error: Error running apply: exit status 1
        Error: Error waiting to create backupVault: Error waiting for Creating backupVault: Error code 3, message: bad request error: "Error creating backup vault - Creation of multiple backup vaults is not supported for a project within a region."
          with google_netapp_backup_vault.backup-vault,
          on terraform_plugin_test.tf line 37, in resource "google_netapp_backup_vault" "backup-vault":
          37: resource "google_netapp_backup_vault" "backup-vault" {

```

Same for all 3 named tests

### Nightly build test history

- https://hashicorp.teamcity.com/test/714502481071555483?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&branch=refs%2Fheads%2Fnightly-test&expandTestHistoryChartSection=true
- https://hashicorp.teamcity.com/test/8777096052812546395?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&branch=refs%2Fheads%2Fnightly-test&expandTestHistoryChartSection=true
- https://hashicorp.teamcity.com/test/6527364086859666331?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&branch=refs%2Fheads%2Fnightly-test&expandTestHistoryChartSection=true

b/357636823

**Comment by SarahFrench** [comment]
The example used to generate TestAccNetappbackup_netappBackupExample [uses us-central1](https://github.com/GoogleCloudPlatform/magic-modules/blob/dfc611111c6a50458acd1e71fa2a723e48b681ce/mmv1/templates/terraform/examples/netapp_backup.tf.erb#L5-L11), and this is the default region used in all tests.

We could make different tests use different regions.

**Comment by Mehul3217** [comment]
Can we please get the list of projects that are being used for above tests, looks like some projects requires cleaning up of resources.

**Comment by trodge** [comment]
Any cleanup for these resources *should* be handled by [automated sweepers](https://github.com/hashicorp/terraform-provider-google/blob/fefe09ae6fae8652c34bfbdb650732c908836772/google/services/netapp/resource_netapp_backup_sweeper.go#L37). I agree with @SarahFrench that the most likely solution is going to be putting each test in its own region, unless we know that the sweepers are not working.

**Comment by melinath** [comment]
@Mehul3217 responded internally on b/357940045

**Comment by Mehul3217** [comment]
We have raised a PR for manual sweepers: https://github.com/GoogleCloudPlatform/magic-modules/pull/11467

**Comment by ScottSuarez** [comment]
Doesn't appear to have been resolved with my change.. reopening.. The bug is also tracked internally by the service team.

**Comment by Mehul3217** [comment]
It should get resolved now, we have cleaned up the required resources.

**Comment by SarahFrench** [comment]
It looks like these two tests are racing to be the first to provision a backup vault in the region:

<img width="1069" alt="Screenshot 2024-10-07 at 10 13 48" src="https://github.com/user-attachments/assets/23f07311-db3c-4f36-a3e2-264c1df4c2b9">

<img width="1070" alt="Screenshot 2024-10-07 at 10 14 08" src="https://github.com/user-attachments/assets/b0e680f8-3657-456f-b08f-88cbbbcb6133">


And this test is consistently failing 

<img width="1058" alt="Screenshot 2024-10-07 at 10 15 09" src="https://github.com/user-attachments/assets/443c69ea-9164-463c-ace0-5a6c08173264">

All the failures are still `Error creating backup vault - Creation of multiple backup vaults is not supported for a project within a region`

**Comment by SarahFrench** [comment]
Even if some resources needed cleaning up, there will be a problem if tests running at the same time are trying to provision a backup vault in the same region and project. Either projects need to use different regions (have them hardcoded into the test) or we need to ensure the tests provisioning these resources cannot run in parallel.

**Comment by Mehul3217** [comment]
Ack, working on it

**Comment by ScottSuarez** [comment]
> Ack, working on it
> 
> created a PR: [GoogleCloudPlatform/magic-modules#11939](https://github.com/GoogleCloudPlatform/magic-modules/pull/11939)

If you are using new regions not being sweeped could you add them to the sweeper please?
https://github.com/modular-magician/terraform-provider-google/blob/c2cf67f225401493c6d11470be3d6df8747ae816/google/services/netapp/resource_netapp_backup_vault_sweeper.go#L41

**Comment by Mehul3217** [comment]
> > Ack, working on it
> > created a PR: [GoogleCloudPlatform/magic-modules#11939](https://github.com/GoogleCloudPlatform/magic-modules/pull/11939)
> 
> If you are using new regions not being sweeped could you add them to the sweeper please? https://github.com/modular-magician/terraform-provider-google/blob/c2cf67f225401493c6d11470be3d6df8747ae816/google/services/netapp/resource_netapp_backup_vault_sweeper.go#L41

Have not added any new locations
