### ISSUE TITLE
Failing test(s): TestAccProjectService_*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18933]
### Impacted tests

- TestAccProjectService_basic
- TestAccProjectService_disableDependentServices

### Affected Resource(s)

- google_project_service

### Failure rates

- 100% since 2024-07-17

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccProjectService_basic
=== PAUSE TestAccProjectService_basic
=== CONT  TestAccProjectService_basic
    vcr_utils.go:152: Step 2/6 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
          map[string]string{
        -   "check_if_service_has_usage_on_destroy": "false",
          }
--- FAIL: TestAccProjectService_basic (79.52s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/3650280922175359194?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true
- https://hashicorp.teamcity.com/test/1012647840504938459?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357622778

**Comment by SarahFrench** [comment]
Context: https://github.com/hashicorp/terraform-provider-google/issues/17686

**Comment by SarahFrench** [comment]
Also see: https://github.com/GoogleCloudPlatform/magic-modules/pull/11314#discussion_r1700194469

>The new error is because check_if_service_has_usage_on_destroy is a parameter in the API (i.e. is url_param_only which implies ignore_read) and wasn't added to ImportStateVerifyIgnore. Non-blocking to resolve in this PR, though.
>
>Unless I'm missing something- it was added to some tests but not others.

**Comment by rileykarson** [comment]
I looked a bit more afterwards and I think we just missed it because the new tests were excluded from VCR. Incorrectly I think- they were likely copied off tests that wouldn't have succeeded (multiple fine grained resources) but only had 1 themselves.

**Comment by melinath** [comment]
taking this on due to high failure count.
