### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withConfidentialBootDisk*

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18948]
### Impacted tests

- TestAccContainerCluster_withConfidentialBootDisk
- TestAccContainerCluster_withConfidentialBootDiskNodeConfig
- TestAccContainerNodePool_withConfidentialBootDisk

### Affected Resource(s)

- google_container_cluster
- google_container_node_pool

### Failure rates

- 100% since 2024-07-28

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccContainerCluster_withConfidentialBootDiskNodeConfig
=== PAUSE TestAccContainerCluster_withConfidentialBootDiskNodeConfig
=== CONT  TestAccContainerCluster_withConfidentialBootDiskNodeConfig
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error waiting for creating GKE cluster: Google Compute Engine: Cannot attach confidential disks to non-confidential VM.
          with google_container_cluster.with_confidential_boot_disk_node_config,
          on terraform_plugin_test.tf line 2, in resource "google_container_cluster" "with_confidential_boot_disk_node_config":
           2: resource "google_container_cluster" "with_confidential_boot_disk_node_config" {
--- FAIL: TestAccContainerCluster_withConfidentialBootDiskNodeConfig (514.83s)
FAIL
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-1524638382129131556?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357622169

**Comment by melinath** [comment]
Note from triage: This is likely new validation from the API, and the test configuration needs to be updated accordingly.

**Comment by melinath** [comment]
Taking this on due to high test failure count
