### ISSUE TITLE
Failing test(s): Security policy-related tests

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18950]
### Impacted tests

- TestAccComputeTargetPool_withSecurityPolicy
- TestAccComputeTargetInstance_withSecurityPolicy
- TestAccComputeTargetInstance_targetInstanceWithSecurityPolicyExample
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyWithUserDefinedFieldsExample
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyWithDdosProtectionConfigExample
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyUserDefinedFieldsUpdate
- TestAccComputeRegionSecurityPolicy_regionSecurityPolicyBasicUpdateExample
- TestAccComputeRegionSecurityPolicyRule_regionSecurityPolicyRuleNetworkMatchUpdate
- TestAccComputeNetworkEdgeSecurityService_update
- TestAccNetworkSecurityAddressGroup_networkSecurityAddressGroupsCloudArmorExample

TestAccComputeNetworkEdgeSecurityService_computeNetworkEdgeSecurityServiceBasicExample

### Affected Resource(s)

- google_compute_region_security_policy

### Failure rates

- 100% since 2024-07-24

### Message(s)

TestAccComputeNetworkEdgeSecurityService_computeNetworkEdgeSecurityServiceBasicExample

```
        Error: Error creating NetworkEdgeSecurityService: googleapi: Error 400: Network Security Policies require Cloud Armor Managed Protection Plus tier and above to use., badRequest

```

All other tests:

```
------- Stdout: -------
        Error: Error creating RegionSecurityPolicy: googleapi: Error 400: Invalid value for field 'resource.type': 'CLOUD_ARMOR_NETWORK'. Network Security Policies are not supported as part of the current Cloud Armor service tier., invalid
          with google_compute_region_security_policy.policyddosprotection,
          on terraform_plugin_test.tf line 2, in resource "google_compute_region_security_policy" "policyddosprotection":
           2: resource "google_compute_region_security_policy" "policyddosprotection" {
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-6962948601919718204?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357704133

**Comment by SarahFrench** [comment]
Our test projects need to be upgraded to "Cloud Armor Managed Protection Plus tier and above"

**Comment by SarahFrench** [comment]
@c2thorn as the person on call this week, are you able to make these changes to the test projects? This would help address a large part of the recent spike in test failures

**Comment by c2thorn** [comment]
I've changed the test projects to "Enterprise Paygo" which hopefully encapsulates the (now longer existing?) Cloud Armor Managed Protection Plus tier. I'll keep this open to verify

**Comment by SarahFrench** [comment]
Thanks! I'll assign the issue to you and you can pass to the next on call as needed

**Comment by melinath** [comment]
@c2thorn just wanted to double-check that you had changed the test projects to "Enterprise Paygo"? I just checked and the nightly test projects were still on "Standard" - I've reinitiated the upgrade but if it's getting automatically downgraded that may not be sufficient.

**Comment by c2thorn** [comment]
yes I distinctly remember clicking "Enterprise Paygo" for both nightly projects...

**Comment by melinath** [comment]
This is a result of unenrolling ourselves from the annual tier in order to resolve https://github.com/hashicorp/terraform-provider-google/issues/18659

**Comment by melinath** [comment]
I think we probably need to re-enroll in annual and create a separate project for the tests that modify the tier.

**Comment by melinath** [comment]
Or run all the tests serially and modify the tiers within the tests as needed.

**Comment by melinath** [comment]
These are passing at this point - we re-enrolled.
