### ISSUE TITLE
Failing test(s): TestAccWorkbenchInstance_removeGpu

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18952]
### Impacted tests

- TestAccWorkbenchInstance_removeGpu

### Affected Resource(s)

- google_workbench_instance

### Failure rates

- 100% since 2024-07-08

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccWorkbenchInstance_removeGpu
=== PAUSE TestAccWorkbenchInstance_removeGpu
=== CONT  TestAccWorkbenchInstance_removeGpu
    vcr_utils.go:152: Step 3/4 error: Error running apply: exit status 1
        Error: Error waiting to modify Workbench Instance state: Error waiting for Modifying Workbench Instance state: Error code 7, message: Quota 'NVIDIA_P4_GPUS' exceeded.  Limit: 1.0 in region us-central1.
          with google_workbench_instance.instance,
          on terraform_plugin_test.tf line 2, in resource "google_workbench_instance" "instance":
           2: resource "google_workbench_instance" "instance" {
--- FAIL: TestAccWorkbenchInstance_removeGpu (208.73s)
FAIL
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-5084281869607539732?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357679834

**Comment by melinath** [comment]
Note from triage: Need to check whether we can increase the quota & verify what the cause here might be.

**Comment by melinath** [comment]
Taking on due to high test failure count - looks like the test is just referencing an incorrect function.
