### ISSUE TITLE
Failing test(s): TestAccCloudFunctionsFunction_buildServiceAccount

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18956]
### Impacted tests

- TestAccCloudFunctionsFunction_buildServiceAccount

### Affected Resource(s)

- google_cloudfunctions_function

### Failure rates

- 60% since 2024-07-11

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccCloudFunctionsFunction_buildServiceAccount
=== PAUSE TestAccCloudFunctionsFunction_buildServiceAccount
=== CONT  TestAccCloudFunctionsFunction_buildServiceAccount
    vcr_utils.go:152: Step 1/4 error: Error running apply: exit status 1
        Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Build failed: failed to Fetch: failed to download archive gs://gcf-sources-653407317329-us-central1/tf-test-zi89ai0x2i-9123a416-18d1-4c1e-9908-b7cc44c2e07a/version-1/function-source.zip: Access to bucket gcf-sources-653407317329-us-central1 denied. You must grant Storage Object Viewer permission to tf-test-build1-feri8bfna7@ci-test-project-nightly-beta.iam.gserviceaccount.com. If you are using VPC Service Controls, you must also grant it access to your service perimeter.
          with google_cloudfunctions_function.function,
          on terraform_plugin_test.tf line 49, in resource "google_cloudfunctions_function" "function":
          49: resource "google_cloudfunctions_function" "function" {
--- FAIL: TestAccCloudFunctionsFunction_buildServiceAccount (126.12s)
FAIL
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-3603872467180741944?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357621492

**Comment by SarahFrench** [comment]
>You must grant Storage Object Viewer permission to tf-test-build1-feri8bfna7@ci-test-project-nightly-beta.iam.gserviceaccount.com. If you are using VPC Service Controls, you must also grant it access to your service perimeter.

These permissions are granted in the test : https://github.com/GoogleCloudPlatform/magic-modules/blob/b5b2fa22cba8d31184a35774e92c8e4dc55267c5/mmv1/third_party/terraform/services/cloudfunctions/resource_cloudfunctions_function_test.go.erb#L1365-L1369

It may be an eventual consistency issue?

**Comment by ScottSuarez** [comment]
fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/11909
