### ISSUE TITLE
google_cloud_run_v2_service should validate that scaling.min_instance_count is less than scaling.max_instance_count

### ISSUE THREAD

**Issue by minimice** [hashicorp/terraform-provider-google#18969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

With regards to this page

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service

For the scaling block, update the documentation to state that `max_instance_count` is required to be present when `min_instance_count` is specified and vice versa.  Failure to do so would result in the following error (here I did not specify max_instance_count only min_instance_count):

```
Error 400: Violation in UpdateServiceRequest.service.template.scaling.max_instance_count: must be greater or equal than min_instance_count.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "must be greater or equal than min_instance_count.",
│         "field": "Violation in UpdateServiceRequest.service.template.scaling.max_instance_count"
│       }
│     ]
│   }
│ ]

```

### New or Affected Resource(s)

* google_cloud_run_v2_service

### Potential Terraform Configuration

```tf 
```

b/357621141

**Comment by melinath** [comment]
From triage: Updated the title to reflect that not only should the docs be updated, we should also mark the fields as `required_with` each other. (Note: this is not currently documented but functions similarly to exactly_one_of - that is, all fields must be listed.) This shouldn't be a breaking change as long as the API always returns errors for invalid configurations.

**Comment by c2thorn** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/examples/cloudrunv2_service_sql.tf.erb#L8 is a passing example of `max_instance_count` without `min_instance_count`. So maybe this is only true for `min_instance_count` ?

**Comment by charan-kumar-137** [comment]
`max_instance_count` and `min_instance_count` are actually NOT required with each other. 
The default for `max_instance_count` is 100 as mentioned in https://cloud.google.com/run/docs/configuring/max-instances#limits.

The above error might be due to setting `min_instance_count` greater than 100 (default).

**Comment by melinath** [comment]
Indeed - the error just says that max_instance_count needs to be greater than min_instance_count. Thanks for the catch!

**Comment by charan-kumar-137** [comment]
@melinath, Not just Cloud Run, Other Services where there is Range Arguments (min & max) would need this kind of validation. 

Spanner - https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances#autoscalinglimits
Cloud Functions - https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions#serviceconfig

Since [ValidateFunc](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#validatefunc) is supported Only for Primitive Types. is there any way we can add Validation for Nested Objects.

**Comment by melinath** [comment]
you can do cross-field validation using a [CustomizeDiff](https://github.com/hashicorp/terraform-provider-google/issues/18392) function. For MMv1 resources, this can be set up using the `custom_diff` top-level resource property (which takes a list of function names) and the functions can be defined using [`custom_code.constants`](https://googlecloudplatform.github.io/magic-modules/develop/custom-code/#add-reusable-variables-and-functions).
