### ISSUE TITLE
Delay skip_delete warning until version 6

### ISSUE THREAD

**Issue by juliocc** [hashicorp/terraform-provider-google#19002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Version 5.40.0 introduced a warning when the `skip_delete` attribute is used within the `google_project` resource:

>skip_delete is deprecated and will be removed in a future major release. The new release adds support for deletion_policy instead.

While the warning correctly notes the deprecation of `skip_delete`, the reference to the `deletion_policy` field in a future release is problematic because it is not currently available in version 5.40.0. This creates a frustrating user experience, as the warning implies an alternative exists, but users are unable to act upon it until they upgrade to version 6.

IMO this warning should only show up if there's an alternative available in the same version. Can the warning be suppressed in version 5.40.0 and introduce it in the next major version  alongside the availability of the `deletion_policy` field? This ensures that users are informed of the deprecation only when they have a viable alternative.

### New or Affected Resource(s)

* google_project

### Potential Terraform Configuration

```tf 
```

### References

- https://github.com/GoogleCloudPlatform/magic-modules/pull/11263
- https://github.com/hashicorp/terraform-provider-google/issues/18775

**Comment by rileykarson** [comment]
`deletion_policy` is being added in `5.X` to allow users to preemptively upgrade. Being able to resolve deprecation messages at the time they're added is convention in the ecosystem and [policy for our provider for this kind of change](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/#add-deprecations-and-warnings-to-the-main-branch-of-magic-modules), apologies for the miss here. I've been out for a few days so I haven't followed the exact chain of events too closely yet, but https://github.com/GoogleCloudPlatform/magic-modules/pull/11263 and https://github.com/GoogleCloudPlatform/magic-modules/pull/11359 (which introduces the field with the current default behaviour- "DELETE" by default) ideally would have happened in a single PR. 

https://github.com/GoogleCloudPlatform/magic-modules/pull/11359 has been merged. I think that'll go out in `5.42.0` by default, but I'll see if we can move it up to `5.41.0` next week to lower the distance between the deprecation message and the action to resolve the message being possible.

**Comment by rileykarson** [comment]
I've added notes to `5.40.0`'s GitHub release about this and @melinath was doing a cherrypick to include the field in `5.41.0`. @melinath do you mind closing this issue once that's done?

**Comment by juliocc** [comment]
Thanks for the update and quick fix. Good to know that `deletion_policy` is coming soon. 

> apologies for the miss here

No need to apologize, these things happen :)

**Comment by melinath** [comment]
yes, the cherry pick is completed and (barring any unforeseen issues) the field should be included in the upcoming release. Beta release notes are here: https://github.com/hashicorp/terraform-provider-google-beta/pull/7921/files and beta release branch is here: https://github.com/hashicorp/terraform-provider-google-beta/commits/release-5.41.0/ if you want to keep an eye on it.
