### ISSUE TITLE
Failing test(s): TestAccBigqueryDataTransferConfig

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19067]
### Impacted tests

- TestAccBigqueryDataTransferConfig/salesforce

### Affected Resource(s)

- google_bigquery_data_transfer_config

### Failure rates

- 100% since 2024-08-01

### Message(s)

```
 Error: Error creating Config: googleapi: Error 400: Transfer parameter connector.authentication.username has been deprecated.
```

Looks like an API-side change.

### Nightly build test history

- https://hashicorp.teamcity.com/test/3804758540908690301?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/358639918

**Comment by wj-chen** [comment]
The deprecation was recent. Will update the test to use new params described in https://cloud.google.com/bigquery/docs/salesforce-transfer#bq.
