### ISSUE TITLE
Failing test(s): TestAccBigqueryConnectionConnection_bigqueryConnectionKmsExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19066]
### Impacted tests

- TestAccBigqueryConnectionConnection_bigqueryConnectionKmsExample

### Affected Resource(s)

- google_bigquery_connection

### Failure rates

- 86% (77 failed out of last 89 runs) as of 2024-08-09

### Message(s)

```
    bootstrap_iam_test_utils.go:74: Added the following bindings to the test project's IAM policy:
        Members: ["serviceAccount:bq-594424405950@bigquery-encryption.iam.gserviceaccount.com"], Role: "roles/cloudkms.cryptoKeyEncrypterDecrypter"
        Retry the test in a few minutes.
```

Because this error keeps happening, it indicates that bootstrapping is not sticking - probably some other test that uses the same test project is resetting the project's IAM policy to not include this role for the service account.

### Nightly build test history

- https://hashicorp.teamcity.com/test/149665625515429691?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A188783%29%2Cid%3A2000000014

b/358640076

**Comment by wj-chen** [comment]
Will take a look to see if we can isolate the test setup more.
