### ISSUE TITLE
Failing test(s): TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19086]
### Impacted tests

- TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule

### Affected Resource(s)

- google_scc_management_organization_event_threat_detection_custom_module

### Failure rates

- 27% (17 failed out of last 61 runs) as of 2024-08-09

### Message(s)

```
Error: Error creating OrganizationEventThreatDetectionCustomModule: googleapi: Error 409: failed to create module due to concurrent modification
```

Possibly this indicates a need for a [mutex](https://googlecloudplatform.github.io/magic-modules/develop/resource-reference/#mutex) and/or serializing these tests.

### Nightly build test history

- https://hashicorp.teamcity.com/test/-224300369035462042?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A202459%29%2Cid%3A2000000000

b/358692342

**Comment by ScottSuarez** [comment]
Still seeing failures here
https://hashicorp.teamcity.com/test/-224300369035462042?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

```
=== RUN   TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule
=== PAUSE TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule
=== CONT  TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule
    vcr_utils.go:152: Step 1/4 error: Error running apply: exit status 1
        Error: Error creating OrganizationEventThreatDetectionCustomModule: googleapi: Error 409: failed to create module due to concurrent modification
          with google_scc_management_organization_event_threat_detection_custom_module.example,
          on terraform_plugin_test.tf line 2, in resource "google_scc_management_organization_event_threat_detection_custom_module" "example":
           2: resource "google_scc_management_organization_event_threat_detection_custom_module" "example" {
--- FAIL: TestAccSecurityCenterManagementOrganizationEventThreatDetectionCustomModule (6.35s)
FAIL

```

I suspect that since this runs in GA and BETA but is an ORG level test this is where the concurrent modification fails out? We should likely only run this test in one environment (if that is the problem).

**Comment by ScottSuarez** [comment]
Actually.. I'm going to continue to keep a pulse on this. Since the change has only been checked in recently I'll let this play out a bit more.

**Comment by ScottSuarez** [comment]
Another failure today, un-assigning myself

**Comment by zli82016** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/11756
