### ISSUE TITLE
Failing test(s): TestAccDataLossPreventionDiscoveryConfig_Update

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19089]
### Impacted tests

- TestAccDataLossPreventionDiscoveryConfig_Update

### Affected Resource(s)

- google_data_loss_prevention_discovery_config

### Failure rates

- 100% since 2024-07-04

### Message(s)

```
 Error: Error creating DiscoveryConfig: googleapi: Error 400: For a project, you can have multiple single-table discovery configurations but only one project-level discovery configuration for BigQuery tables.
```

It looks like the deletion of the DiscoveryConfig failed and the leftover resource was not swept. Initial error was:

```
testing_new.go:85: Error running post-test destroy, there may be dangling resources: DataLossPreventionDiscoveryConfig still exists at https://dlp.googleapis.com/v2/projects/ci-test-project-nightly-beta/locations/us-central1/discoveryConfigs/8667524838116786959
```

The ideal fix would be to write a [sweeper](https://github.com/hashicorp/terraform-provider-google/issues/17891)

### Nightly build test history

- https://hashicorp.teamcity.com/test/-9129528880868396147?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A212777%29%2Cid%3A2000000062

b/358691074

**Comment by patrickmoy** [comment]
Sweeper looked fine locally; PR merged. Let me know if tests don't improve after this
