### ISSUE TITLE
If get calls to service account fails after terraform creation terraform retries to create it even though it already exists.

### ISSUE THREAD

**Issue by Dutta78** [hashicorp/terraform-provider-google#19112]
### Community Note

google_service_account.service_account: Creating...

Error: Error creating service account: googleapi: Error 409: Service account bf1f61c6-sa already exists within project projects/<project_id>.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ResourceInfo",
    "resourceName": "projects/<project_id>/serviceAccounts/bf1f61c6-sa@<project_id>.iam.gserviceaccount.com"
  }
]
, alreadyExists

  with module.tenant-infra.google_service_account.service_account,
  on ../modules/v1/service_account.tf line 1, in resource "google_service_account" "service_account":
   1: resource "google_service_account" "service_account" {

2024/08/13 08:16:43 TF error: terraform: exit status 1

### Terraform Version & Provider Version(s)

Terraform v1.9.0
on <architecture>
+ provider registry.terraform.io/hashicorp/google v4.52.0
+ provider registry.terraform.io/hashicorp/google-beta v4.52.0

### Affected Resource(s)

"google_service_account"

### Terraform Configuration

```tf
```

### Expected Behavior

Terraform should be able to create the service account

### Actual Behavior

Terraform made a create api call to gcp to create a service account.
On its subsequent get call it returned an error even though a service account was created.
And then it retried to create a service account again.

### Steps to reproduce

Sometimes GCP does return an error while get call. If the service account is not attached to any policy.

**Comment by ggtisc** [comment]
Hi @Dutta78!

To replicate this issue we need the terraform code of your `google_service_account` resource, because with the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account) examples everything looks correct without errors

**Comment by sbocinec** [comment]
@Dutta78 The solution for this error is to use `google` TF provider version `~>5.21.0` as it introduced solution for this problem - `create_ignore_already_exists` field in the `google_service_account` resource. If you use `create_ignore_already_exists = true` in the resource, it should help.

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#create_ignore_already_exists
* https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#5120-jan-16-2024
