### ISSUE TITLE
`default_uri_disabled` is documented for `google_cloud_run_v2_service` but doesn't exist

### ISSUE THREAD

**Issue by dhermes** [hashicorp/terraform-provider-google#19163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.0 on macOS M3 (ARM)
+ provider registry.terraform.io/hashicorp/google v5.35.0

### Affected Resource(s)

`google_cloud_run_v2_service`

### Terraform Configuration

N/A

### Expected Behavior

The documented field should exist: https://github.com/hashicorp/terraform-provider-google/blob/12ca3e09291a9f27bda28ea5d66cc4bc4743748d/website/docs/r/cloud_run_v2_service.html.markdown#L1071-L1073

Or should be removed from the docs.

### Actual Behavior

```
│ Error: Unsupported argument
│ 
│   on service.tf line 47, in resource "google_cloud_run_v2_service" "foo":
│   47:   default_uri_disabled = true
│ 
│ An argument named "default_uri_disabled" is not expected here.
╵
```

### Steps to reproduce

1. `terraform apply`

**Comment by charan-kumar-137** [comment]
Maybe we should add the argument to `google_cloud_run_v2_service` as it is part of REST API (https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services#Service)

**Comment by charan-kumar-137** [comment]
Its available in BETA.

**Comment by dhermes** [comment]
Thanks @charan-kumar-137!

Now I understand what "Beta" means on the argument

> The `google-beta` provider is distinct from the `google` provider in that it supports GCP products and features that are in Preview, while `google` does not. Fields and resources that are only present in `google-beta` are clearly marked in the provider documentation.
