### ISSUE TITLE
Failing test(s): compute disk + storage pool

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19199]
### Impacted tests

- TestAccComputeDisk_storagePoolSpecified
- TestAccComputeInstance_bootDisk_storagePoolSpecified

### Affected Resource(s)

- google_compute_disk

### Failure rates

These were failing 100% in PRs due to quota issues. I've deleted the resources causing the quota issue, so this is temporarily resolved, but it could happen again at any time (or start failing in nightly test environments.)
 

### Message(s)

```
resource_compute_disk_test.go:1655: Error creating StoragePool: googleapi: Error 400: Maximum storage pools in this zone has been reached. Please delete an existing storage pool before creating a new storage pool., badRequest
```

This comes from the [`setupTestingStoragePool`](https://github.com/hashicorp/terraform-provider-google-beta/blob/9cadd5f5f748529e159d19f04e3681b21a57b490/google-beta/services/compute/resource_compute_disk_test.go#L1628) function, and happens because deletion of the existing resources wasn't successful at one point. Specifically, `Hyperdisk Balanced Storage Pools Advanced Iops` was at 100%.

Ideally, the storage pools would be implemented as a separate Terraform resource, which would have a sweeper that would automatically clean up any trailing pools on a regular basis.

Alternatively, I think it would be possible to implement a sweeper on its own, without a resource - it just wouldn't be autogenerated. https://github.com/hashicorp/terraform-provider-google/issues/17891 has some information about how to write sweepers.

Another mitigation would be to make the storage pools use less IOPS quota each - this would be great to do, but would not replace the need to have a sweeper - it would just make us less likely to hit the quota before the sweeper runs each night.

### Nightly build test history

Example failure: https://github.com/GoogleCloudPlatform/magic-modules/pull/11504#issuecomment-2299949158

b/361323245

**Comment by sizzle0121** [comment]
We avoid adding storage pools as a Terraform resource, since Terraform will plan to delete all the disks in a storage pool when users only want to delete the storage pool, which is risky and not we want.
Therefore, I think adding handwritten sweeper would be a better solution.

**Comment by c2thorn** [comment]
Going to skip in VCR for now: https://github.com/GoogleCloudPlatform/magic-modules/pull/11522

**Comment by melinath** [comment]
@c2thorn these should be passing now, since the resources were deleted - not sure we need to skip them in VCR.
