### ISSUE TITLE
Failing test(s): TestAccComputeInstance_confidentialHyperDiskBootDisk

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#19217]
### Impacted tests

- TestAccComputeInstance_confidentialHyperDiskBootDisk

### Affected Resource(s)

- google_compute_instance

### Failure rates

- 100% since 2024-07-15

### Message(s)

```
 Error: Error creating instance: googleapi: Error 400: Cannot attach confidential disks to non-confidential VM., badRequest
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-5465441705731221331?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

**Comment by c2thorn** [comment]
Skipping VCR: https://github.com/GoogleCloudPlatform/magic-modules/pull/11522

**Comment by melinath** [comment]
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/19014
