### ISSUE TITLE
Add support for creating DataMapper Workspace

### ISSUE THREAD

**Issue by sana-google** [hashicorp/terraform-provider-google#19222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Healthcare Data Engine (HDE) is a solution closely coupled with the Healthcare API. It is built using components provided by the Healthcare API. HDE has a feature called DataMapper, that allows users to map their source data (in BigQuery tables) to the FHIR standard format via a UI. This is achieved from within a Data Mapper Workspace, or simply called workspace. 

Currently the workspace can be set up via an API call or the Cloud Console UI. However, based on customer requirements, it would be good to extend this functionality to be fulfilled via Terraform.

### New or Affected Resource(s)

* google_healthcare_datamapper_workspace

### Potential Terraform Configuration

```tf 
resource "google_healthcare_datamapper_workspace" "default" {
  provider = "google"
  name    = "example-dm-workspace"
  dataset = google_healthcare_dataset.default.id
  data_project_ids = ["source-data-project-1", "source-data-project-2", ... ] 
}
```

### References

* https://cloud.google.com/healthcare-api/healthcare-data-engine/docs/reference/rest/v1/projects.locations.datasets.dataMapperWorkspaces

b/364292751

**Comment by melinath** [comment]
Note from triage: This is currently in alpha

**Comment by sana-google** [comment]
I have updated the references list to - https://cloud.google.com/healthcare-api/healthcare-data-engine/docs/reference/rest/v1/projects.locations.datasets.dataMapperWorkspaces

**Comment by sana-google** [comment]
The PR I am raising will add a new resource, `google_healthcare_workspace`. The export feature will be added later.
