### ISSUE TITLE
Failing test(s): TestAccComputeNetworkFirewallPolicyRule_multipleRules

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#19235]
### Impacted tests

- TestAccComputeNetworkFirewallPolicyRule_multipleRules

### Affected Resource(s)

- `google_compute_network_firewall_policy_rule`

### Failure rates

- 100% since 2024-08-16

### Message(s)

Looks like there is some update method that is not properly refreshing fingerprint. 

```
------- Stdout: -------
=== RUN   TestAccComputeNetworkFirewallPolicyRule_multipleRules
=== PAUSE TestAccComputeNetworkFirewallPolicyRule_multipleRules
=== CONT  TestAccComputeNetworkFirewallPolicyRule_multipleRules
    vcr_utils.go:152: Step 4/6 error: Error running apply: exit status 1
        Error: Error updating NetworkFirewallPolicy "projects/xxxxx/global/firewallPolicies/tf-test-policy-yyyy": googleapi: Error 412: Invalid fingerprint., conditionNotMet
          with google_compute_network_firewall_policy.fw_policy,
          on terraform_plugin_test.tf line 2, in resource "google_compute_network_firewall_policy" "fw_policy":
           2: resource "google_compute_network_firewall_policy" "fw_policy" {
--- FAIL: TestAccComputeNetworkFirewallPolicyRule_multipleRules (118.06s)
FAIL

```

### Nightly build test history

- https://hashicorp.teamcity.com/test/3924032820256974661?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true

**Comment by melinath** [comment]
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/19218
