### ISSUE TITLE
Support `node_kublet_config` in `node_pool_auto_config` so users can disable the kubelet read-only port

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform-provider-google#19236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

[comes from a comment from @hoskeri in #15208]

It appears that `node_pool_auto_config` doesn't currently support `node_kublet_config`.
I'm not sure how necessary it is for autopilot clusters (hopefully Google provides sensible defaults there), but there was discussion about adding support for some or all of the parameters supported there for `node_pool_auto_config` as well, similar to some of the other blocks / resources it's supported for.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf 
resource "google_container_cluster" "autopilot" {
  name               = "autopilot"
  location           = "us-central1-f"
  enable_autopilot = true

  node_pool_auto_config {
    kubelet_config {
       # supported params set here
    }
  }

  deletion_protection = false
  network             = "default"
  subnetwork          = "default"
}
```

### References

#15208 
https://github.com/GoogleCloudPlatform/magic-modules/pull/11272

b/362277444

**Comment by wyardley** [comment]
The good news is that I made pretty good progress on this. I'll put up a draft or a PR shortly.

However, even though it uses `NodeKubeletConfig`, https://pkg.go.dev/google.golang.org/api/container/v1#NodePoolAutoConfig mentions:

> Currently only `insecure_kubelet_readonly_port_enabled` can be set here.

So I'm not sure if it makes sense to implement it using the same code / schema as other KubeletConfig stuff or not. Another problem with it being this way is that `cpu_manager_policy` must be set, but then will have permadrift unless set to something other than an empty string. I'm starting to think that maybe it should be required (tangentially related to #19225)

Also, naming-wise, I think it makes sense to do
```hcl
  node_pool_auto_config {
    node_kubelet_config {}
  }
```

though maybe an argument could be made for matching `kubelet_config` there?

**Comment by melinath** [comment]
the naming should match the API - and FWIW even if the API supported other child fields I'd be inclined to only add the read-only port for now so that we can backport more easily.

**Comment by melinath** [comment]
(This is probably the only remaining ticket in this cluster that we'd consider for backporting, barring further evidence of impact.)

**Comment by wyardley** [comment]
> barring further evidence of impact.

https://github.com/GoogleCloudPlatform/magic-modules/pull/11572 possibly might be worth considering too, if we can get it narrow enough - otherwise, I'm guessing users of the GKE cluster module might see some issues if they don't set it to `""`
