### ISSUE TITLE
Failing test(s): TestAccVertexAIIndexEndpoint_updated

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-google#19309]
### Impacted tests

- TestAccVertexAIIndexEndpoint_updated

### Affected Resource(s)

- google_vertex_ai_index_endpoint

### Failure rates

- 100% since YYYY-08-10

### Message(s)

```hcl
=== RUN   TestAccVertexAIIndexEndpoint_updated
=== PAUSE TestAccVertexAIIndexEndpoint_updated
=== CONT  TestAccVertexAIIndexEndpoint_updated
    resource_vertex_ai_index_endpoint_test.go:22: Step 1/4 error: Error running apply: exit status 1
        Error: Error creating IndexEndpoint: googleapi: Error 400: Currently only one VPC network per user project is supported. Your project is already linked to https://www.googleapis.com/compute/v1/projects/ci-test-project-nightly-ga/global/networks/tf-bootstrap-net-vpc-network-1
        To change the VPC network, please undeploy all Vertex AI deployment resources, delete all endpoint resources, and then retry creating resources in 30 mins.
          with google_vertex_ai_index_endpoint.index_endpoint,
          on terraform_plugin_test.tf line 2, in resource "google_vertex_ai_index_endpoint" "index_endpoint":
           2: resource "google_vertex_ai_index_endpoint" "index_endpoint" {
--- FAIL: TestAccVertexAIIndexEndpoint_updated (28.89s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/1110679295788310533?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&branch=%3Cdefault%3E&expandTestHistoryChartSection=true

b/364309625

**Comment by BBBmau** [comment]
Looks like it could be related to the addition of the `deployed_index` resource. Tests began to fail once `deployed_index` tests were included in the nightly tests.

`deployed_index` test history: https://hashicorp.teamcity.com/test/-7657025106797983469?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

**Comment by SarahFrench** [comment]
Note from triage: Looks like this test is trying to create a new bootstrapped VPC, but it should use tf-bootstrap-net-vpc-network-1. Updating the test may be a sufficient fix

**Comment by melinath** [comment]
Manual test run to check if it's fixed: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS_GOOGLEBETA_PACKAGE_VERTEXAI/259217?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true

**Comment by melinath** [comment]
Looks good!
