### ISSUE TITLE
Fix intermittent formatting issue with VCR test reports

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19301]
### What kind of contribution is this issue about?

Pull request UX

### Details

Something about the way we're doing color formatting has a glitch that causes it to not always display properly.

<img width="860" alt="Screenshot 2024-08-28 at 10 21 08 AM" src="https://github.com/user-attachments/assets/099dbaee-2802-4775-866a-d5ec1763cf8e">

We should try to find a way to make this more consistent (which may require moving this output to a check, or removing the color formatting.)

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/11272#issuecomment-2313655174

**Comment by roaks3** [comment]
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodeConfigUpdates`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11272/artifacts/6a7d80b8-e633-48d6-b90c-7f6dc1c7667d/build-log/recording_build/TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodeConfigUpdates_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11272/artifacts/6a7d80b8-e633-48d6-b90c-7f6dc1c7667d/recording/TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodeConfigUpdates.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11272/artifacts/6a7d80b8-e633-48d6-b90c-7f6dc1c7667d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11272/artifacts/6a7d80b8-e633-48d6-b90c-7f6dc1c7667d/recording) for each test

**Comment by roaks3** [comment]
The above comment is now rendering fine after pasting here, and on the original PR, but it initially rendered as:

<img width="924" alt="Screenshot 2024-09-10 at 11 07 08 AM" src="https://github.com/user-attachments/assets/64371928-dad6-4b05-ada0-91449166dcaf">

**Comment by roaks3** [comment]
Note: this seems to be due to some sort of MathML/Latex issue, where the same content in the comment can be rendered with different html sometimes. I can't find any recent issues being raised about this, but it's possible we want to move away from this solution for rendering color/font to get more consistent results.

**Comment by melinath** [comment]
We could potentially use alerts: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by wyardley** [comment]
> The above comment is now rendering fine after pasting here, and on the original PR, but it initially rendered as:

I noticed this as well, where it would render weird and then show up properly later on the same comment.

Thanks for working on some changes towards fixing this, @melinath!

**Comment by melinath** [comment]
See https://github.com/orgs/community/discussions/31570 for discussion about the different options for "color" in markdown. After consideration, I'm opting for emoji-based emphasis because I don't think the benefit is worth the effort of implementing an image rendering website. Alert coloring would work for actual alerts, but these aren't actually alerts.

**Comment by wyardley** [comment]
I'm glad they're color emojis and not like "Tests failed during recording mode 👎👎"
