### ISSUE TITLE
Labels force change each time a plan/apply is run, even when the label values are not changed.

### ISSUE THREAD

**Issue by dapolloxp** [hashicorp/terraform-provider-google#19352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v5.43.1
on <architecture>
+ provider registry.terraform.io/hashicorp/google v5.43.1

### Affected Resource(s)

google_compute_interconnect
effective labels forces a recreation

"effective_labels": {
				Type:        schema.TypeMap,
				Computed:    true,
				ForceNew:    true,
				Description: `All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.`,
				Elem:        &schema.Schema{Type: schema.TypeString},
			}

### Expected Behavior

modifying labels should not recreate the circuit

### Actual Behavior

changing effective labels causes the entire circuits to be recreated. Labels should not cause a recreation of the circuit as it is a disruptive change.

### Steps to reproduce

1. `terraform apply` or 2. `terraform plan`

b/364309433

**Comment by melinath** [comment]
@zli82016 is the diff something the service team might be able to resolve? And if so, how?

The destruction could be resolved by adding update-in-place support, which would at least mitigate the impact.

**Comment by zli82016** [comment]
@dapolloxp, did you make changes to the `labels` field? 

It is expected for the resource to be created with the changes in the `effective_labels` field, as the resource is immutable.

**Comment by zli82016** [comment]
> @zli82016 is the diff something the service team might be able to resolve? And if so, how?
> 
> The destruction could be resolved by adding update-in-place support, which would at least mitigate the impact.


The update-in-place support could avoid the resource being recreated.

**Comment by melinath** [comment]
According to the issue title, this is happening "even when the label values are not changed"

**Comment by zli82016** [comment]
@dapolloxp , can you please provide the `terraform plan` to check the specific changes in `effective_labels` field? Thanks.

**Comment by melinath** [comment]
@zli82016 why is effective_labels ForceNew? As a computed field, it doesn't seem like it should ever cause resource recreation?

**Comment by zli82016** [comment]
> @zli82016 why is effective_labels ForceNew? As a computed field, it doesn't seem like it should ever cause resource recreation?

The resource `google_compute_interconnect` is immutable and in-place update is not supported. Setting it as computed is to avoid the users modifying it. Instead, it is combined in the code to include all of labels on the resource. `effective_labels` is used as `labels` in the API request.

**Comment by zli82016** [comment]
> can you please provide the Terraform configuration and `terraform plan` to check the specific changes in `effective_labels` field? Thanks.

@dapolloxp , can you please provide the Terraform configuration and terraform plan to check the specific changes in effective_labels field as I requested before? I still don't know the exact issue happing to this resource. Thanks.

**Comment by dapolloxp** [comment]
Yes. I am working on that and will send it over shortly.

**Comment by dapolloxp** [comment]
@zli82016 See the bug case for the files

**Comment by melinath** [comment]
It looks like compute interconnect has a patch method; perhaps the initial implementation just skipped adding support for it. https://cloud.google.com/compute/docs/reference/rest/v1/interconnects/patch

**Comment by melinath** [comment]
I've opened https://github.com/hashicorp/terraform-provider-google/issues/19410 to track the enhancement of adding update-in-place support. That way this ticket clearly just covers investigating any potential issues with incorrect diffs on the effective_labels field.
