### ISSUE TITLE
Referenced computed attributes in `google_storage_bucket_object` are not updated on the same plan/apply cycle

### ISSUE THREAD

**Issue by athak** [hashicorp/terraform-provider-google#19379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.1.0 (also happening with 5.43.1)

### Affected Resource(s)

google_storage_bucket_object

### Terraform Configuration

```tf
resource "google_storage_bucket_object" "test_bug" {
  name    = "test.txt"
  content = "123"
  bucket  = "test-bucket"
}

resource "terraform_data" "test_bug" {
  triggers_replace = [
    google_storage_bucket_object.test_bug.generation,
    google_storage_bucket_object.test_bug.media_link,
  ]
}

```

### Expected Behavior

When modifying the contents of the `google_storage_bucket_object`, the referenced attributes in other resources should be updated on the same plan/apply.

### Actual Behavior

The referenced attributes are updated in the next plan/apply.

### Steps to reproduce

1. `terraform apply`
2. Modify the content of the bucket object
3. `terraform plan`
The referenced attributes in the `terraform_data` resource are not shown as being modified.
4. `terraform apply`
5. `terraform plan`
The referenced attributes in the `terraform_data` resource are now shown as modified and will be updated.

b/367722415

**Comment by ggtisc** [comment]
Hi @athak !

For this purpose already exists the versioning in [google_storage_bucket](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#nested_versioning). For example if you set it to `enabled` then each version of your `google_storage_bucket_object` is going to be forced to be updated. This is enabled at `google_storage_bucket` level where your object was placed

**Comment by lantoniogc** [comment]
Hi. I found a similar issue with the `google_cloudfunctions2_function.cloud_function.source.storage_source.generation`. 

As displayed here:
```terraform
resource "google_cloudfunctions2_function" "cloud_function" {
    source {
      storage_source {
        bucket = var.storage_bucket.name
        object = google_storage_bucket_object.function_storage_object.name
        generation = google_storage_bucket_object.function_storage_object.generation
      }
    }
  }
```

The important line is: `generation = google_storage_bucket_object.function_storage_object.generation`

It's similar because when the source code of the function is updated and I make a `terraform plan` the `generation` output of the `google_storage_bucket_object.function_storage_object` is the same as the last deployment so the function doesn't get updated on the process.

I need to run terraform cycle again (plan/apply) so the generation output is updated on the storage object but it's using the old generation that is not uploaded yet to GCS. It should compute the new `generation` value instead of using an existing one.

**Comment by ggtisc** [comment]
@athak after a second review it seems to me that what you are looking for is for  `terraform_data.test_bug.triggers_replace` to be updated when you make changes to the `google_storage_bucket_object`. Is this correct?

**Comment by athak** [comment]
> @athak after a second review it seems to me that what you are looking for is for `terraform_data.test_bug.triggers_replace` to be updated when you make changes to the `google_storage_bucket_object`. Is this correct?

@ggtisc yes, that is correct, within the same plan/apply cycle. As it stands now, the changes are reflected in the next cycle.

**Comment by ggtisc** [comment]
Confirmed issue!

After doing some changes on the `google_storage_bucket_object` the `terraform_data.test_bug.triggers_replace` was not updated

**Comment by rileykarson** [comment]
This is a Terraform Core issue, Terraform plans greedily assume that output values are not volatile and can be carried forward later into plan when the resource is updated. There are _technically_ ways to trigger values becoming unknown on a plan from within the provider, but they require substantial custom logic to achieve and are not done in practice by providers to my knowledge.

Here's the same issue across different resources/features:

```diff
resource "google_compute_address" "my-address" {
  name        = "my-test-address"
  description = "foo"
+  labels = {
+    foo = "bar"
+  }
}

resource "google_compute_global_address" "gladress" {
  name = "my-test-gladress"
  lifecycle {
    replace_triggered_by = [google_compute_address.my-address.address]
  }
}
```

```
$ terraform apply
google_compute_address.my-address: Refreshing state... [id=projects/graphite-test-rileykarson/regions/us-central1/addresses/my-test-address]
google_compute_global_address.gladress: Refreshing state... [id=projects/graphite-test-rileykarson/global/addresses/my-test-gladress]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_compute_address.my-address will be updated in-place
  ~ resource "google_compute_address" "my-address" {
      ~ effective_labels   = {
          + "foo" = "bar"
        }
        id                 = "projects/graphite-test-rileykarson/regions/us-central1/addresses/my-test-address"
      ~ labels             = {
          + "foo" = "bar"
        }
        name               = "my-test-address"
      ~ terraform_labels   = {
          + "foo" = "bar"
        }
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

I looked for an issue upstream but couldn't seem to get the right terms together to find a preexisting issue against Core.
