### ISSUE TITLE
`google_compute_resource_policy` is recreated when labels defined in `snapshot_schedule_policy` are updated 

### ISSUE THREAD

**Issue by kumadee** [hashicorp/terraform-provider-google#19394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.7.5
on <architecture>
+ provider registry.terraform.io/hashicorp/google v5.35.0
+ provider registry.terraform.io/hashicorp/google-beta v5.35.0

### Affected Resource(s)

google_compute_resource_policy

### Terraform Configuration

```tf
# Initial configuration
resource "google_compute_resource_policy" "default_snapshot" {
    description = "Snapshot schedule policy for example disk"
    name        = "example-snapshot-schedule"
    project     = "example-project-e044dd03"
    region      = "europe-west3"

    snapshot_schedule_policy {
        retention_policy {
            max_retention_days    = 3
            on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
        }
        schedule {
            daily_schedule {
                days_in_cycle = 1
                start_time    = "04:00"
            }
        }
        snapshot_properties {
            chain_name        = "example"
            labels            = {
                "environment"    = "development"
                "supportgroupid" = "000195041"
            }
            storage_locations = [
                "europe-west3",
            ]
        }
    }
}
```

### Expected Behavior

The snapshot labels must be updated without the need to recreate the existing resource.

### Actual Behavior

Below the output of terraform plan
```sh
-/+ resource "google_compute_resource_policy" "default_snapshot" {
      ~ id          = "projects/example-project-e044dd03/regions/europe-west3/resourcePolicies/example-snapshot-schedule" -> (known after apply)
        name        = "example-snapshot-schedule"
      ~ self_link   = "https://www.googleapis.com/compute/v1/projects/example-project-e044dd03/regions/europe-west3/resourcePolicies/example-snapshot-schedule" -> (known after apply)
        # (3 unchanged attributes hidden)

      ~ snapshot_schedule_policy {
          ~ snapshot_properties {
              - guest_flush       = false -> null
              ~ labels            = { # forces replacement
                  ~ "supportgroupid" = "000195041" -> "0001996810"
                    # (8 unchanged elements hidden)
                }
                # (2 unchanged attributes hidden)
            }

            # (2 unchanged blocks hidden)
        }
    }

```

### Steps to reproduce

1. `terraform apply`
2. Change the label value or add new labels
3. `terraform plan` or `terraform apply`

### Important Factoids

This resource is also re-created, if one updates only the time schedule. For e.g. change the start_time value to `03:00`

### References

gcloud CLI also supports updating labels rather than recreating `google_compute_resource_policy`
```sh
    gcloud compute resource-policies update snapshot-schedule NAME
        [--description=DESCRIPTION] [--max-retention-days=MAX_RETENTION_DAYS]
        [--on-source-disk-delete=ON_SOURCE_DISK_DELETE] [--region=REGION]
        [--snapshot-labels=[KEY=VALUE,...]]
        [--weekly-schedule-from-file=PATH_TO_FILE
          | --start-time=START_TIME (--daily-schedule | --hourly-schedule=HOURS
          | --weekly-schedule=WEEKLY_CYCLE)] [GCLOUD_WIDE_FLAG ...]
```

**Comment by shuyama1** [comment]
Hi @kumadee, sorry for the late response. Looks like in-place update is supported for `google_compute_resource_policy` after [v5.38.0](https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v5.38.0). Would you mind updating to v5.38.0+ and see if that resolves your issue?

**Comment by kumadee** [comment]
> Hi @kumadee, sorry for the late response. Looks like in-place update is supported for `google_compute_resource_policy` after [v5.38.0](https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v5.38.0). Would you mind updating to v5.38.0+ and see if that resolves your issue?
> 
> 

No problem. I will verify this either today or tomorrow. I anyways looked at the PR which fixed the problem and it looks promising to me.

**Comment by kumadee** [comment]
I can confirm that this issue is fixed after updating to the provider version `5.44.0`.
