### ISSUE TITLE
node_pool_defaults.node_config_defaults.node_kubelet_config with GKE Autopilot clusters.

### ISSUE THREAD

**Issue by apeabody** [hashicorp/terraform-provider-google#19428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.5 & v1.8.2
on x86_64
+ provider registry.terraform.io/hashicorp/google v5.44.0
+ provider registry.terraform.io/hashicorp/google v6.2.0

### Affected Resource(s)

```
Terraform will perform the following actions:

  # google_container_cluster.default will be created
  + resource "google_container_cluster" "default" {
      + cluster_ipv4_cidr                        = (known after apply)
      + datapath_provider                        = (known after apply)
      + default_max_pods_per_node                = (known after apply)
      + deletion_protection                      = false
      + enable_autopilot                         = true
      + enable_cilium_clusterwide_network_policy = false
      + enable_intranode_visibility              = true
      + enable_kubernetes_alpha                  = false
      + enable_l4_ilb_subsetting                 = false
      + enable_legacy_abac                       = false
      + enable_multi_networking                  = false
      + enable_shielded_nodes                    = true
      + endpoint                                 = (known after apply)
      + id                                       = (known after apply)
      + label_fingerprint                        = (known after apply)
      + location                                 = "us-central1"
      + logging_service                          = (known after apply)
      + master_version                           = (known after apply)
      + monitoring_service                       = (known after apply)
      + name                                     = "gke-autopilot-basic"
      + network                                  = "default"
      + networking_mode                          = "VPC_NATIVE"
      + node_locations                           = (known after apply)
      + node_version                             = (known after apply)
      + operation                                = (known after apply)
      + private_ipv6_google_access               = (known after apply)
      + project                                  = "ap-bps-experimental-gke"
      + self_link                                = (known after apply)
      + services_ipv4_cidr                       = (known after apply)
      + subnetwork                               = (known after apply)
      + tpu_ipv4_cidr_block                      = (known after apply)

      + node_pool_defaults {
          + node_config_defaults {
              + insecure_kubelet_readonly_port_enabled = (known after apply)
              + logging_variant                        = (known after apply)
            }
        }
    }
 ```

### Terraform Configuration

```tf
resource "google_container_cluster" "default" {
  project  = "PROJECT_ID"
  name     = "gke-autopilot-basic"
  location = "us-central1"

  enable_autopilot = true


  node_pool_defaults {
    node_config_defaults {
    }
  }

  # Set `deletion_protection` to `true` will ensure that one cannot
  # accidentally delete this instance by use of Terraform.
  deletion_protection = false
}
```

### Expected Behavior

apply

### Actual Behavior

`Error: googleapi: Error 400: Setting node_pool_defaults.node_config_defaults.node_kubelet_config is not allowed on GKE Autopilot clusters.`

### Steps to reproduce

1. `terraform apply`

### Important Factoids

The config is not setting `node_pool_defaults.node_config_defaults.node_kubelet_config`.

b/365835779

**Comment by wyardley** [comment]
Is the empty `node_pool_defaults.node_config_defaults` block coming because of a the GKE module? I think in most use cases, you wouldn't want to have the block defined at all (or the provider wouldn't try to do anything?) if it's empty?

**Comment by apeabody** [comment]
> Is the empty `node_pool_defaults.node_config_defaults` block coming because of a the GKE module? I think in most use cases, you wouldn't want to have the block defined at all (or the provider wouldn't try to do anything?) if it's empty?

Hi @wyardley - The example above was the minimum needed to reproduce and is valid Terraform, however here is an additional example that results in the same error:

```
resource "google_container_cluster" "default" {
  project  = "ap-bps-experimental-gke"
  name     = "gke-autopilot-basic"
  location = "us-central1"
  provider = google-beta

  enable_autopilot = true


  node_pool_defaults {
    node_config_defaults {
      logging_variant = "MAX_THROUGHPUT"
    }
  }

  # Set `deletion_protection` to `true` will ensure that one cannot
  # accidentally delete this instance by use of Terraform.
  deletion_protection = false
}
```

`Error: googleapi: Error 400: Setting node_pool_defaults.node_config_defaults.node_kubelet_config is not allowed on GKE Autopilot clusters.`
