### ISSUE TITLE
Change the default value of soft_delete_policy to zero

### ISSUE THREAD

**Issue by jofrmartins** [hashicorp/terraform-provider-google#19441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

The default value is 604800s (7 days), but from 1 September this option started to pay out.

In general, storage now costs twice as much. 

As the default is 604800s, this option will always be active, without you needing it, and the cost of the project will increase unnecessarily.

https://github.com/hashicorp/terraform-provider-google/blob/270d18f71bc6dd721d14235d4dd30693c483d033/google/services/storage/resource_storage_bucket.go#L539-L545

I suggest setting the **default to zero**, so that users who need active **soft delete** can explicitly put the value they want in the code.

### New or Affected Resource(s)

* [google_storage_bucket](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket)

### Potential Terraform Configuration

```tf 
```

### References

- https://cloud.google.com/storage/docs/json_api/v1/buckets#softDeletePolicy.retentionDurationSeconds

>The value must be greater than or equal to 604800 (7 days) and less than 7776000 (90 days). The value can also be set to 0, which disables the soft delete policy.

b/373407544

**Comment by rileykarson** [comment]
I think this matches the API default- which as a provider maintainer I'd personally lean towards preserving. This'll get raised with the service team for consideration though.

**Comment by kautikdk** [comment]
As @rileykarson mentioned, We won't keep client side default different than server side default.
