### ISSUE TITLE
google_container_registry_repository project argument not optional

### ISSUE THREAD

**Issue by defo89** [hashicorp/terraform-provider-google#1945]
### Terraform Version
Terraform v0.11.8
+ provider.google v1.17.1

### Affected Resource(s)
- google_container_registry_repository

### Terraform Configuration Files
```hcl
data "google_container_registry_repository" "registry" {}

output "gcr_location" {
    value = "${data.google_container_registry_repository.registry.repository_url}"
}
```

### Expected Behavior
Container registry URL for this project is displayed.

### Actual Behavior
```
data.google_container_registry_repository.registry: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.google_container_registry_repository.registry: 1 error(s) occurred:

* data.google_container_registry_repository.registry: data.google_container_registry_repository.registry: project: required field is not set
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional information
Adding 'project' argument solves the issue but it should be optional not mandatory.

**Comment by dmitrijsf** [comment]
+ same with **google_container_engine_versions**

**Comment by fpoppinga** [comment]
Another workaround for this, if you happen to create the project in the same run as the GCR: 

```tf
provider "google" {
  alias   = "google_container_registry_fix"
  project = google_project.project.project_id // <- your project resource
}

resource "google_container_registry" "registry" {
  provider = google.google_container_registry_fix
}
```

**Comment by melinath** [comment]
The field is `optional` because it can fall back to the provider project, but if no provider project is set, this error will be returned; this is the standard behavior across the entire provider for `project` fields; it might be possible to document it better but that would be a large change, and this issue is very old. Closing.
