### ISSUE TITLE
default_labels not applied to google_compute_instance

### ISSUE THREAD

**Issue by paulmarsicloud** [hashicorp/terraform-provider-google#19503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.3.0

### Affected Resource(s)

`google_compute_instance`

### Terraform Configuration

```
terraform {
  required_providers {
    google = {
      version = "~> 6.3.0"
    }
  }
}

provider "google" {
  default_labels = {
    label-a = "defaultlabelprovider"
  }
}

resource "google_compute_instance" "test-vm" {
  for_each = var.vpc_networks
  name         = "test-vm"
  machine_type = var.machine_type
  zone         = var.zone
  project                 = var.project_id

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2204-lts"
    }
  }

...

metadata_startup_script = <<-EOT
    #!/bin/bash
    # Update and install necessary packages
    sudo su
    sudo apt update && sudo apt upgrade -y
  EOT

}
```

### Expected Behavior

`default_labels` are applied to `google_compute_instance`. Could be because there are `labels`, `terraform_labels` and `effective_labels` to choose from.

### Actual Behavior

`google_compute_instance` resource does not get any labels; 

### Steps to reproduce

1. `terraform apply`

### References

Very similar to #16375

b/368612656

**Comment by zli82016** [comment]
The default labels should exist in the `terraform_labels` and `effective_labels` fields and will not show in `labels` field.


The `labels` field only manages the labels defined in the resource configuration.

The `terraform_labels` merges the providers default labels and the labels in the resource configuration.

The `effective_labels` has all of the labels on the resource.

More details are in [the guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade)


------------
Can you provider the output of `terraform state show google_compute_instance.test-vm` , @paulmarsicloud ?

**Comment by paulmarsicloud** [comment]
@zli82016 - certainly!

```
# google_compute_instance.test-vm:
resource "google_compute_instance" "test-vm" {
    can_ip_forward          = false
    cpu_platform            = "Intel Broadwell"
    current_status          = "RUNNING"
    deletion_protection     = false
    description             = null
    effective_labels        = {
        "goog-terraform-provisioned" = "true"
    }
    enable_display          = false
    hostname                = null
    id                      = "projects/<REDACTED>/zones/us-central1-c/instances/test-vm"
    instance_id             = "3173735686692170799"
    label_fingerprint       = "vezUS-42LLM="
    machine_type            = "e2-medium"
    metadata_fingerprint    = "G-4juN2Hj74="
    metadata_startup_script = <<-EOT
        #!/bin/bash
        # Update and install necessary packages
        sudo su
        sudo apt update && sudo apt upgrade -y
    EOT
    min_cpu_platform        = null
    name                    = "test-vm"
    project                 = "nautical-commerce"
    self_link               = "https://www.googleapis.com/compute/v1/projects/<REDACTED>/zones/us-central1-c/instances/test-vm"
    tags_fingerprint        = "42WmSpB8rSM="
    terraform_labels        = {
        "goog-terraform-provisioned" = "true"
    }
    zone                    = "us-central1-c"

    boot_disk {
        auto_delete                = true
        device_name                = "persistent-disk-0"
        disk_encryption_key_raw    = (sensitive value)
        disk_encryption_key_sha256 = null
        interface                  = null
        kms_key_self_link          = null
        mode                       = "READ_WRITE"
        source                     = "https://www.googleapis.com/compute/v1/projects/<REDACTED>/zones/us-central1-c/disks/test-vm"

        initialize_params {
            enable_confidential_compute = false
            image                       = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20240904"
            labels                      = {}
            provisioned_iops            = 0
            provisioned_throughput      = 0
            size                        = 10
            storage_pool                = null
            type                        = "pd-standard"
        }
    }

    network_interface {
        internal_ipv6_prefix_length = 0
        ipv6_access_type            = null
        ipv6_address                = null
        name                        = "nic0"
        network                     = "https://www.googleapis.com/compute/v1/projects/<REDACTED>/global/networks/default-2"
        network_ip                  = "10.128.0.4"
        nic_type                    = null
        queue_count                 = 0
        stack_type                  = "IPV4_ONLY"
        subnetwork                  = "https://www.googleapis.com/compute/v1/projects/<REDACTED>/regions/us-central1/subnetworks/default-2"
        subnetwork_project          = "<REDACTED>"

        access_config {
            nat_ip                 = "34.29.176.137"
            network_tier           = "PREMIUM"
            public_ptr_domain_name = null
        }
    }

    scheduling {
        automatic_restart           = true
        instance_termination_action = null
        min_node_cpus               = 0
        on_host_maintenance         = "MIGRATE"
        preemptible                 = false
        provisioning_model          = "STANDARD"
    }

    service_account {
        email  = "<REDACTED>"
        scopes = [
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring.write",
        ]
    }

    shielded_instance_config {
        enable_integrity_monitoring = true
        enable_secure_boot          = false
        enable_vtpm                 = true
    }
}
```

Interestingly - I _now_ see this in the Console: 
<img width="394" alt="image" src="https://github.com/user-attachments/assets/0c068633-fbbb-49f4-a2e4-d74013786078">

**Comment by zli82016** [comment]
Thanks for the output. 

`label-a = "defaultlabelprovider"` are not present in `terraform_labels` and `effective_labels` field.

Can you try to run `terraform plan` again to see if the plan is empty, @paulmarsicloud ?

Also, do you remember when the resource `google_compute_instance.test-vm` is created?

**Comment by paulmarsicloud** [comment]
@zli82016 - so as this is a test instance, I've been destroying and creating as I go along. I recreated with `label-a = "defaultlabelprovider"` set and the resource still says in `terraform state show google_compute_instance.test-vm`:

```
resource "google_compute_instance" "test-vm" {
    can_ip_forward          = false
    cpu_platform            = "Intel Broadwell"
    current_status          = "RUNNING"
...
    terraform_labels        = {
        "goog-terraform-provisioned" = "true"
    }
```

<img width="403" alt="image" src="https://github.com/user-attachments/assets/e2df3442-431d-464b-896b-fc25800ea4ca">

So it seems that if the label needs to change at the provider level, it doesn't get picked up at all for `google_compute_instance`

**Comment by paulmarsicloud** [comment]
And `terraform plan` shows no changes when I change the `default_labels` field

**Comment by zli82016** [comment]
I cannot reproduce this issue. Sorry. `label-a = "defaultlabelprovider"` is present in `terraform_labels` and `effective_labels` fields when I tested locally.


And `terraform plan` shows  changes when I change the `default_labels` field.

The configuration I used is the following:
```
provider "google" {
  default_labels = {
    label-a = "defaultlabelprovider"
  }
} 

resource "google_compute_instance" "test-vm" {
  name         = "test-vm"
  machine_type = "n2-standard-2"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2204-lts"
    }
  }

  network_interface {
    network = "default"
    access_config { }
  }

  service_account {
    email = data.google_compute_default_service_account.default.email
    scopes = [
             "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring.write",
    ]
  }

metadata_startup_script = <<-EOT
    #!/bin/bash
    # Update and install necessary packages
    sudo su
    sudo apt update && sudo apt upgrade -y
  EOT
                
} 
```

@paulmarsicloud , is there something I missed? Does this issue happen to other resources?

Do you mind providing the logs for the comand `TF_LOG=DEBUG terraform plan`? Thanks.

**Comment by paulmarsicloud** [comment]
@zli82016 this appears to be working on my end now. Not sure if there was an alias or if I wasn't authenticated properly to GCP before running my terraform commands, but we can close this now. Thank you for the help and speedy replies!
