### ISSUE TITLE
Dataproc Cluster unable to create with internal_ip_only = false

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#19522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

+ provider registry.terraform.io/hashicorp/google v6.3.0

### Affected Resource(s)

google_dataproc_cluster

### Terraform Configuration

```tf
resource "google_dataproc_cluster" "basic" {
  name       = "tf-test-dproc"
  region     = "us-central1"

  cluster_config {
    gce_cluster_config {
      subnetwork       = google_compute_subnetwork.dataproc_subnetwork.name
      internal_ip_only = false
    }
  }
}
```

### Debug Output

POST /v1/projects/project/regions/us-central1/clusters?alt=json&prettyPrint=false HTTP/1.1
Host: dataproc.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/1.3.9 (+https://www.terraform.io) Terraform-Plugin-SDK/2.33.0 terraform-provider-google-beta/acc
Content-Length: 213
Content-Type: application/json
X-Goog-Api-Client: gl-go/1.21.6 gdcl/0.193.0
Accept-Encoding: gzip

{
 "clusterName": "tf-test-dproc-d138eek63n",
 "config": {
  "gceClusterConfig": {
   "subnetworkUri": "projects/project/regions/us-central1/subnetworks/dataproc-cluster"
  }
 },
 "projectId": "project"
}

### Expected Behavior

internalIpOnly should be set to false and sent in the request

### Actual Behavior

internalIpOnly was not sent

### Steps to reproduce

1. `terraform apply`

### Important Factoids

This is a problem due to the switch in default value for this field on the API-side. Previously a not present value for internal_ip_only was interpreted as the field being set to false. Now it is impossible to set false for this field through Terraform as the unset value is interpreted as true.

This prevents the creation of any cluster with an external IP and the latest version of Dataproc via Terraform 

### References

https://github.com/hashicorp/terraform-provider-google/issues/19424

b/368118038

**Comment by melinath** [comment]
@slevenick is this the root cause behind https://github.com/hashicorp/terraform-provider-google/issues/19424

**Comment by slevenick** [comment]
Yep!

**Comment by rileykarson** [comment]
@slevenick can you confirm this worked? I'm still seeing this:

> resource_dataproc_cluster_test.go:65: Step 1/1 error: Check failed: Check 3/20 error: google_dataproc_cluster.basic: Attribute 'cluster_config.0.gce_cluster_config.0.internal_ip_only' expected "false", got "true"

**Comment by rileykarson** [comment]
Can you add or modify a test to confirm it, and update that check to the appropriate value?
