### ISSUE TITLE
API gateway support for google_compute_network_endpoint_group was never implemented but release notes say it was

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#19567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.3.0
+ provider registry.terraform.io/hashicorp/google-beta v6.3.0
+ provider registry.terraform.io/hashicorp/random v3.6.3

### Affected Resource(s)

`google_compute_network_endpoint_group`

### Terraform Configuration

```tf
resource "google_compute_network_endpoint_group" "serverless_neg" {
  provider = google-beta
  name = "SERVERLESS_NEG_NAME"
  network_endpoint_type = "SERVERLESS"
  serverless_deployment {
    platform = "apigateway.googleapis.com"
    resource = "GATEWAY_ID"
  }
}
```

I also tried this
```
resource "google_compute_region_network_endpoint_group" "serverless_neg" {
  provider = google-beta
  name     = "SERVERLESS_NEG_NAME"
  region  = "REGION_ID"
  network_endpoint_type = "SERVERLESS"
  serverless_config {
    platform = "apigateway.googleapis.com"
    gateway_id = "GATEWAY_ID"
  }
}
```

### Expected Behavior

See this release note: https://github.com/hashicorp/terraform-provider-google-beta/blob/main/CHANGELOG.md#4120-february-28-2022. "compute: added field serverless_deployment to google_compute_network_endpoint_group (beta only) for API Gateway resources (https://github.com/hashicorp/terraform-provider-google-beta/pull/4041)"

And these issues:
* https://github.com/hashicorp/terraform-provider-google/issues/10729
* https://github.com/hashicorp/terraform-provider-google/issues/10061
* https://github.com/hashicorp/terraform-provider-google/issues/9907

I'm using the beta provider and its not there. I can also find zero working examples or docs for this feature that was merged years ago.

### Actual Behavior

```
│ Error: Unsupported block type
│ 
│   on api_gateway.tf line 33, in resource "google_compute_network_endpoint_group" "serverless_neg":
│   33:   serverless_deployment {
│ 
│ Blocks of type "serverless_deployment" are not expected here.
```

### Steps to reproduce

1. `terraform apply`

b/369904931

**Comment by ggtisc** [comment]
Confirmed documentation issue!

Currently there isn't any argument called `serverless_deployment` in [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint_group). It is just a mistake in the release note.

**Comment by Cheriit** [comment]
I see that there was an issue with the release notes.

Instead of "compute: added field serverless_deployment to google_compute_network_endpoint_group (beta only)" it should be "compute: added field serverless_deployment to google_compute_region_network_endpoint_group (beta only)". 

Serverless only available for the google_compute_region_network_endpoint_group
