### ISSUE TITLE
docs(cloudsql): add POSTGRES_16 to version list

### ISSUE THREAD

**Issue by jenewland1999** [hashicorp/terraform-provider-google#19565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Similar to #14864.
It is possible to specify v16, but it is missing from the documentation.
[PostgreSQL version 16 went GA on June 07 2024](https://cloud.google.com/sql/docs/postgres/release-notes#June_07_2024).

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf 
resource "google_sql_database_instance" "main" {
  name             = "main-instance"
  database_version = "POSTGRES_16"
  region           = "us-central1"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
  }
}
```

b/369163441

**Comment by BBBmau** [comment]
Hi @jenewland1999, currently `POSTGRES_16` is not supported based on the [API Docs](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/SqlDatabaseVersion), is this a field that has already been added in and is just missing a documentation update?

**Comment by jenewland1999** [comment]
> Hi @jenewland1999, currently `POSTGRES_16` is not supported based on the [API Docs](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/SqlDatabaseVersion), is this a field that has already been added in and is just missing a documentation update?

It would seem their docs are outdated too 😅. However, I can confirm that creating a DB with v16 is indeed possible using the API. Funnily enough, in their API Explorer if you bring up the autocomplete dropdown it seems to suggest that both v16 and v17 are valid options.
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/41fe4d3a-5707-4114-a66a-e2405a49a537">

**Comment by BBBmau** [comment]
@jenewland1999 this is a valid request then! Wanna open a PR that adds it in?

**Comment by jenewland1999** [comment]
Upon looking at the docs, I see that v16 and v17 of Postgres are now in the list, as such I'm going to mark this as closed. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#database_version-1
