### ISSUE TITLE
google_compute_backend_service: enabled iap can't be disabled

### ISSUE THREAD

**Issue by utnehmer** [hashicorp/terraform-provider-google#19596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v6.4.0
+ provider registry.terraform.io/hashicorp/google-beta v6.4.0

### Affected Resource(s)

* google_compute_backend_service

### Terraform Configuration

```tf
resource "google_compute_backend_service" "example" {
  name        = "example"
  port_name   = "http"
  protocol    = "HTTPS"
  timeout_sec = 30

  iap {
    enabled = true
  }

  project = var.project
}
```

### Expected Behavior

When setting `iap.enabled` to `false` it should be disabled.

### Actual Behavior

Terraform seems to change the setting but the next apply shows the same change.

```
google_compute_backend_service.example: Refreshing state... [id=projects/example/global/backendServices/example]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_compute_backend_service.example will be updated in-place
  ~ resource "google_compute_backend_service" "example" {
        id                              = "projects/example/global/backendServices/example"
        name                            = "example"
        # (22 unchanged attributes hidden)

      ~ iap {
          ~ enabled                     = true -> false
            # (3 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to reproduce

1. create tf file with `enabled=true`
2. `terraform apply`
3. change `enabled=true` to `enabled=false`
4. `terraform apply`
5. `terraform apply`
6. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-google/issues/19273

b/370068153

**Comment by ggtisc** [comment]
Confirmed issue!

After changing the value of `iap.enabled` from `true` to `false` the change is not applied in the `tfsate` file.

**Comment by slevenick** [comment]
The way to find out what features/bug fixes are available in a certain version of the provider is to check the notes for that release: https://github.com/hashicorp/terraform-provider-google/releases

For this specific one I would expect it to release on Monday as part of 6.8.0
