### ISSUE TITLE
google_database_instance - set ENTERPRISE_PLUS as default Edition for POSTGRES_16 

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#19606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

+ provider registry.terraform.io/hashicorp/google v6.4.0

### Affected Resource(s)

google_database_instance

### Important Factoids
`settings.edition` should no longer have a default and should be computed so we default to the API's value.
We missed updating the default in 6.0.0. See https://github.com/GoogleCloudPlatform/magic-modules/pull/10915

b/338258663

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/10915
b/338258663

b/370537315

**Comment by ggtisc** [comment]
Confirmed issue!

According to the [documentation](https://cloud.google.com/sql/docs/postgres/release-notes#June_07_2024) starting in June 7, 2024 the default edition for `POSTGRES_16` `google_database_instance` should be `ENTERPRISE_PLUS` but after creating a resource without specifying the `edition` it was set to `ENTERPRISE`

**Comment by isaurabhuttam** [comment]
@c2thorn should we close this bug, as changes for this has been merged as part of https://github.com/GoogleCloudPlatform/magic-modules/pull/12077

**Comment by c2thorn** [comment]
> @c2thorn should we close this bug? as changes for this has been merged as part of [GoogleCloudPlatform/magic-modules#12077](https://github.com/GoogleCloudPlatform/magic-modules/pull/12077)

yes that seems to have resolved this
