### ISSUE TITLE
kubelet_config.cpu_manager_policy is still mandatory in release 5.44.1

### ISSUE THREAD

**Issue by rvillane** [hashicorp/terraform-provider-google#19630]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

In release https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.4.0 added `node_config.kubelet_config.cpu_manager_policy` field optional to fix its update in google_container_cluster resource (https://github.com/hashicorp/terraform-provider-google/pull/19464).

Can that same fix be backported to provider 5.x?

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf 
```

### References

https://github.com/hashicorp/terraform-provider-google/pull/19464

**Comment by wyardley** [comment]
side note: I don't know whether Google / Hashicorp will be willing to backport that fix, but setting the value to `""` might work as a workaround if you can't update to >= 6.4.0.

**Comment by melinath** [comment]
Given the workaround, the limitations of doing backports, and the fact that this is not a regression in the resource, we're not planning to backport the fix (https://github.com/hashicorp/terraform-provider-google/pull/19464) at this time. However, we may want to add documentation that clarifies the workaround for users. Please feel free to leave any additional feedback here - for example, any issues with the workaround.
