### ISSUE TITLE
googleapi: Error 400: Replica configuration does not contain the dump file path when replicating from an on-premises master., errorReplicaConfigurationMissingDumpFilePath

### ISSUE THREAD

**Issue by ns-rkankanala** [hashicorp/terraform-provider-google#19634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

resource "google_sql_database_instance" "replica2" {

  name             = "test2"
  database_version = "MYSQL_8_0"
  region           = "us-west1"
  settings {
    tier = "db-custom-1-3840"
    ip_configuration {
      ipv4_enabled    = false
      private_network = "projects/ns/global/networks/s"
    }
  }
  master_instance_name = google_sql_source_representation_instance.instance2.name
  replica_configuration {
    #dump_file_path = "gs://bucket/dump.sql"
    failover_target         = false
    username                = "XXXX"
    password                = "XXX"
    #connect_retry_interval  = 60
    #master_heartbeat_period = 60000
  }
}

Keep getting an error 
Error, failed to create instance test2: googleapi: Error 400: Replica configuration does not contain the dump file path when replicating from an on-premises master., errorReplicaConfigurationMissingDumpFilePath

But as per documentation dumpfilepath was optional https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#replica_configuration

### Terraform Configuration

```tf
```

### Steps to reproduce

1. `terraform apply`

b/371061464

**Comment by ns-rkankanala** [comment]
After configuring dump file we get Error importing data: generic::unknown: gs://bucket/dump.sql: googleapi: Error 403: p1086763574318-6tsgck@gcp-sa-cloud-sql.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist)., forbidden 
 
 The issue here is the service account it generated dynamically and we cannot force service account to cloudsql replica.

**Comment by ggtisc** [comment]
Confirmed issue!

According to terraform registry the [dump_file_path](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#dump_file_path) is optional, but the shared code results in the following error:

`Error: Error, failed to create instance replica2: googleapi: Error 400: Replica configuration does not contain the dump file path when replicating from an on-premises master.`

**Comment by aymat13** [comment]
We have verified that the Terraform behavior is consistent with the API behavior.

Under the scenario where the master instance is a source representation instance and the replicaConfiguration is provided, the dump_file_path is a required field.

The public docs will be updated the reflect the behavior in a follow up PR.

**Comment by ns-rkankanala** [comment]
@aymat13 It does work without dump_file_path 
{
  "name": "master",
  "region": "us-west1",
  "databaseVersion": "MYSQL_8_0",
  "onPremisesConfiguration": {
    "hostPort": "<IP>:3306",
    "username": "<user>",
    "password": "<password>"
  }
}
REST API call:
curl -v --header "Authorization: Bearer $(gcloud auth print-access-token)" \
     --header 'Content-Type: application/json' \
     --data @source-payload-file.json \
     -X POST \
     https://sqladmin.googleapis.com/sql/v1beta4/projects/XXXX/instances

Sample payload for the creation of source representation is as follows:

{
    "settings": {
        "tier": "db-n1-standard-8",
        "dataDiskSizeGb": "100",
        "dataDiskType": "PD_SSD",
        "ipConfiguration": {
            "privateNetwork": "projects/XXXX/global/networks/XXXX",
            "ipv4Enabled": false
        },
	 "availabilityType": "REGIONAL"
    },
    "masterInstanceName": "master",
    "rootPassword": "generatedPassword",
    "region": "us-west1",
    "databaseVersion": "MYSQL_8_0",
    "name": "master"
}
REST API call:
curl -v --header "Authorization: Bearer $(gcloud auth print-access-token)" \
  --header 'Content-Type: application/json' \
  --data @/path/to/replica-payload-file.json \
  -X POST \
  https://sqladmin.googleapis.com/sql/v1beta4/projects/XXXXX/instances

Start replication using REST API call:

curl -v --header "Authorization: Bearer ${ACCESS_TOKEN}" \
     --header 'Content-Type: application/json' \
     --data '{
         "syncMode": "ONLINE",
       }' \
     -X POST \
     https://sqladmin.googleapis.com/sql/v1beta4/projects/XXX/instances/<name-of-replica-instance>/startExternalSync

**Comment by aymat13** [comment]
The behavior only happens under the scenario where the master instance is a source representation instance and the replicaConfiguration is provided while creating the replica.

In your second API call if you add a replicaConfiguration block, it is possible to replicate the issue. Sample payload:

```
{
  "settings": {
    "tier": "db-n1-standard-8",
    "dataDiskSizeGb": "100",
    "dataDiskType": "PD_SSD",
    "ipConfiguration": {
      "privateNetwork": "projects/XXXX/global/networks/XXXX",
      "ipv4Enabled": false
    },
   "availabilityType": "REGIONAL"
  },
  "masterInstanceName": "master",
  "rootPassword": "generatedPassword",
  "region": "us-west1",
  "databaseVersion": "MYSQL_8_0",
  "name": "master",
  "replicaConfiguration": {
     "mysqlReplicaConfiguration": {
         "username": "xxx",
         "password": "yyy",
      }
  }
}
```
