### ISSUE TITLE
`google_discovery_engine_chat_engine` should allow to modify datastores

### ISSUE THREAD

**Issue by ffeldhaus** [hashicorp/terraform-provider-google#19678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.4.0
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

google_discovery_engine_chat_engine

### Terraform Configuration

The issue occurs when modifying an initial configuration and adding another datastore. See initial config version and modified version below.

Initial Config with one datastore

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "6.4.0"
    }
  }
}

# enable APIs

resource "google_project_service" "dialogflow" {
  service = "dialogflow.googleapis.com"
}

resource "google_project_service" "discoveryengine" {
  service = "discoveryengine.googleapis.com"
}

# create engine
resource "google_discovery_engine_chat_engine" "primary" {
  engine_id = "chat-engine-id"
  collection_id = "default_collection"
  location = "global"
  display_name = "Chat engine"
  industry_vertical = "GENERIC"
  data_store_ids = [
    google_discovery_engine_data_store.data_store_1.data_store_id,
  ]
  common_config {
    company_name = "Example"
  }
  chat_engine_config {
    agent_creation_config {
    business = "test business name"
    default_language_code = "en"
    time_zone = "America/Los_Angeles"
    }
  }
}

# create data store
resource "google_discovery_engine_data_store" "data_store_1" {
  location                    = "global"
  data_store_id               = "data_store_1"
  display_name                = "Structured datastore"
  industry_vertical           = "GENERIC"
  content_config              = "NO_CONTENT"
  solution_types              = ["SOLUTION_TYPE_CHAT"]
}

# create data store
resource "google_discovery_engine_data_store" "data_store_2" {
  location                    = "global"
  data_store_id               = "data_store_2"
  display_name                = "Structured datastore"
  industry_vertical           = "GENERIC"
  content_config              = "NO_CONTENT"
  solution_types              = ["SOLUTION_TYPE_CHAT"]
}
```

Modified config with additional datastore
```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "6.4.0"
    }
  }
}

# enable APIs

resource "google_project_service" "dialogflow" {
  service = "dialogflow.googleapis.com"
}

resource "google_project_service" "discoveryengine" {
  service = "discoveryengine.googleapis.com"
}

# create engine
resource "google_discovery_engine_chat_engine" "primary" {
  engine_id = "chat-engine-id"
  collection_id = "default_collection"
  location = "global"
  display_name = "Chat engine"
  industry_vertical = "GENERIC"
  data_store_ids = [
    google_discovery_engine_data_store.data_store_1.data_store_id,
    google_discovery_engine_data_store.data_store_2.data_store_id,
  ]
  common_config {
    company_name = "Example"
  }
  chat_engine_config {
    agent_creation_config {
    business = "test business name"
    default_language_code = "en"
    time_zone = "America/Los_Angeles"
    }
  }
}

# create data store
resource "google_discovery_engine_data_store" "data_store_1" {
  location                    = "global"
  data_store_id               = "data_store_1"
  display_name                = "Structured datastore"
  industry_vertical           = "GENERIC"
  content_config              = "NO_CONTENT"
  solution_types              = ["SOLUTION_TYPE_CHAT"]
}

# create data store
resource "google_discovery_engine_data_store" "data_store_2" {
  location                    = "global"
  data_store_id               = "data_store_2"
  display_name                = "Structured datastore"
  industry_vertical           = "GENERIC"
  content_config              = "NO_CONTENT"
  solution_types              = ["SOLUTION_TYPE_CHAT"]
}
```

### Debug Output

Initial config
https://gist.github.com/ffeldhaus/7e62a9a9ae741b8e476289bc8a0ddfde

Modification
https://gist.github.com/ffeldhaus/82410e40f1fabe6568a2c3da8478c529

### Expected Behavior

The `google_discovery_engine_chat_engine` resource should be updated.

### Actual Behavior

The `google_discovery_engine_chat_engine` resource is force deleted and recreated.

### Steps to reproduce

1. `terraform apply`

**Comment by ffeldhaus** [comment]
The issue is caused by [`dataStoreIds` being defined as `immutable: true`](https://github.com/GoogleCloudPlatform/magic-modules/blob/abefe83b63a813b308e7c09db02036664924a331/mmv1/products/discoveryengine/ChatEngine.yaml#L102).

The [projects.locations.collections.engines.patch API](https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/projects.locations.collections.engines/patch) does not impose such limitations. There are also no limitations mentioned in the [`https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/projects.locations.collections.engines#Engine API resource definition`](https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/projects.locations.collections.engines#Engine).

The actual behavior via the API is, that data stores can be added to an existing chat engine, but removing one or more data stores from a chat results in an error message. This is because there is not (yet) a way for the chat engine to check if the data store is still used within the Dialogflow Agent.

It is still important that data stores can be added to existing engines especially as removing a data store from an engine fails with a meaningful error message and removing a data store is on the roadmap to be supported by chat engines.

**Comment by GraceHoogendoorn** [comment]
👍
