### ISSUE TITLE
Unable to upgrade to v6.4.0

### ISSUE THREAD

**Issue by rajat2911** [hashicorp/terraform-provider-google#19676]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.6
on <architecture>
+ provider registry.terraform.io/hashicorp/google v5.44.1
+ provider registry.terraform.io/hashicorp/google-beta v5.44.1

### Affected Resource(s)

+ provider registry.terraform.io/hashicorp/google v5.44.1
+ provider registry.terraform.io/hashicorp/google-beta v5.44.1

Could not retrieve the list of available versions for provider hashicorp/google: locked provider registry.terraform.io/hashicorp/google 6.4.0 does not match
│ configured version constraint >= 3.43.0, >= 4.74.0, >= 5.40.0, < 6.0.0, 6.4.0, < 7.0.0; must use terraform init -upgrade to allow selection of new versions
╵

### Terraform Configuration

```
    google = {
      source  = "hashicorp/google"
      version = "5.44.1"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "5.44.1"
    }    
```
Upgrading to 6.4.0 but getting error 

Could not retrieve the list of available versions for provider hashicorp/google: locked provider registry.terraform.io/hashicorp/google 6.4.0 does not match
│ configured version constraint >= 3.43.0, >= 4.74.0, >= 5.40.0, < 6.0.0, 6.4.0, < 7.0.0; must use terraform init -upgrade to allow selection of new versions

### Steps to reproduce

1. `terraform apply`

**Comment by rajat2911** [comment]
Hi @fd @ndarilek @mitchellh @kavu  Any update on this issue

**Comment by ndarilek** [comment]
Why would *I* in particular have an update? What's with this uptick in randos tagging people on issues that have nothing to do with their problem in recent years? Go away.

**Comment by slevenick** [comment]
Is this specifically an issue you're seeing upgrading to 6.4.0, or is it just that you're running into issues with the version constraint? It looks like the version constraint may be impossible to fulfill?
