### ISSUE TITLE
Magician should support manually assigning a random reviewer

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#19691]
### What kind of contribution is this issue about?

Pull request UX

### Details

The current system of assigning reviewers by assigning terraform-team has the following limitations:

1. It sends notifications to everyone in terraform-team who uses go/g3n for GitHub review notifications, not just the assigned reviewer.
2. It doesn't respect the vacation list in `.ci/magician/github/membership_data.go`.
3. It doesn't include Hashicorp employees who are also in the reviewer pool.

We want to be able to assign a new reviewer manually when necessary, either because the current reviewer is on vacation or because a reviewer didn't get assigned when a [CoreContributor](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/magician/cmd/request_reviewer.go#L67) opened a pull request.

The preferred interface for this would probably be a command invoked via pull request comments.

**Comment by roaks3** [comment]
Passing this along as I didn't have time to look into it last week
