### ISSUE TITLE
Documentation for google_sql_database_instance is missing for ssl_mode parameter which was previously present

### ISSUE THREAD

**Issue by drewhodson** [hashicorp/terraform-provider-google#19711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
6.x.x

### Affected Resource(s)

* google_sql_database_instance

### Issue Description

In a previous version ([5.4.3](https://registry.terraform.io/providers/hashicorp/google/5.43.1/docs/resources/sql_database_instance)) of the documentation  for the `google_sql_database_instance` resource, there was a description of the valid values for `ssl_mode` and a link to [Google's documentation](https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1beta4/instances#ipconfiguration) for this parameter. In the current version of the documentation ([6.5.0](https://registry.terraform.io/providers/hashicorp/google/6.5.0/docs/resources/sql_database_instance)) of this same resource, this additional information is missing. 

b/373407376

**Comment by c2thorn** [comment]
fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/12006
