### ISSUE TITLE
Lack of the description about google_project_iam_binding resource

### ISSUE THREAD

**Issue by danhnguyen123** [hashicorp/terraform-provider-google#19719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Please update the document about google_project_iam_binding resource (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam). 
Today my project uses google_project_iam_binding and it removes roles that other principals like Service Account already have this role from before, which leads to an accident in the production environment. I see a discussion about this issue here https://discuss.hashicorp.com/t/difference-between-google-project-iam-binding-and-google-project-iam-member/49645/2. 
Lack of description about this resource may lead to miss understanding for new users about it

### New or Affected Resource(s)

google_project_iam_binding

### Potential Terraform Configuration

```tf 
```

**Comment by SarahFrench** [comment]
Sorry you experienced that problem! We have an open issue to update that documentation here: https://github.com/hashicorp/terraform-provider-google/issues/17329

Closing as duplicate
