### ISSUE TITLE
Failing test(s): Compute instance tests:  The Cloud Storage bucket 'bosh-gce-raw-stemcells' is not found.

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#19729]
### Impacted tests

- TestAccComputeInstanceTemplate_imageShorthand
- TestAccComputeInstanceTemplate_nictype_update
- TestAccComputeInstance_nictype_update
- TestAccComputeRegionInstanceTemplate_imageShorthand
- TestAccComputeRegionInstanceTemplate_nictype_update
- TestAccComputeImageIamBindingGenerated
- TestAccComputeImageIamBindingGenerated_withAndWithoutCondition
- TestAccComputeImageIamBindingGenerated_withCondition
- TestAccComputeImageIamMemberGenerated
- TestAccComputeImageIamMemberGenerated_withAndWithoutCondition
- TestAccComputeImageIamMemberGenerated_withCondition
- TestAccComputeImageIamPolicyGenerated
- TestAccComputeImageIamPolicyGenerated_withCondition
- TestAccComputeImage_imageBasicExample
- TestAccComputeImage_imageBasicStorageLocationExample
- TestAccComputeImage_imageGuestOsExample
- TestAccComputeImage_update

### Affected Resource(s)

- google_compute_instance
- google_compute_instance_template

### Failure rates

- 100% since 2024-09-27

### Message(s)

```
        Error: Error creating Image: googleapi: Error 400: The Cloud Storage bucket 'bosh-gce-raw-stemcells' is not found., gcsBucketNotFound
```

### Nightly build test history

https://hashicorp.teamcity.com/test/-987213401400888252?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/371070509

**Comment by SarahFrench** [comment]
Added some more impacted tests to this ticket
