### ISSUE TITLE
Add support for source_workstation to google_workstations_workstation

### ISSUE THREAD

**Issue by esu** [hashicorp/terraform-provider-google#19730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs.workstations#Workstation.FIELDS.source_workstation now supports `source_workstation` for workstations PD cloning.

### New or Affected Resource(s)

* google_workstations_workstation

### Potential Terraform Configuration

```tf 
resource "google_workstations_workstation" "default" {
  provider               = google-beta
  source_workstation     = "projects/some-project/locations/us-west1/workstationClusters/cluster-lnf9om5v/workstationConfigs/config-lo3bl0ur/workstations/my-workstation"
}
```

b/372033071

**Comment by SarahFrench** [comment]
Note from triage: confirmed that this field is currently only in the Beta API
