### ISSUE TITLE
Failed to create `google_service_usage_consumer_quota_override`

### ISSUE THREAD

**Issue by sato-s** [hashicorp/terraform-provider-google#19749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.0
on x86
+ provider registry.terraform.io/hashicorp/google v5.36.0
+ provider registry.terraform.io/hashicorp/google-beta v5.36.0

### Affected Resource(s)

google_service_usage_consumer_quota_override

### Terraform Configuration

```tf
resource "google_service_usage_consumer_quota_override" "override" {
  provider       = google-beta
  project        = data.google_project.project.id
  service        = "cloudbuild.googleapis.com"
  metric         = urlencode("cloudbuild.googleapis.com/get_requests")
  limit          = urlencode("/min/project")
  override_value = 2700
}
```

### Expected Behavior

terraform successfully apply quota override.

### Actual Behavior

terraform apply fails with the following error.
```
Terraform v1.9.0
on linux_amd64
Initializing plugins and modules...
google_service_usage_consumer_quota_override.override: Creating...
╷
│ Error: Error creating ConsumerQuotaOverride: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
# Omitted
│ 
│ 
│   with google_service_usage_consumer_quota_override.override,
│   on quotas.tf line 1, in resource "google_service_usage_consumer_quota_override" "override":
│    1: resource "google_service_usage_consumer_quota_override" "override" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

### Steps to reproduce

1. `terraform apply`

**Comment by ggtisc** [comment]
Hi @sato-s!

Could you help me understand your issue? There are a couple of lacking data that I need to replicate this issue, so please check the following code and tell me if there is something different you have to change it. If you could return the complete code as the one I'm sharing it would be helpful.

```
resource "google_project" "project_19749" {
  name       = "Project 19749"
  project_id = "project-19749"
  org_id     = "1234567890" # this is just an example not real information
}

data "google_project" "project_19749" {}

resource "google_service_usage_consumer_quota_override" "su_cq_override_19749" {
  provider       = google-beta
  project        = data.google_project.project_19749.id
  service        = "cloudbuild.googleapis.com"
  metric         = urlencode("cloudbuild.googleapis.com/get_requests")
  limit          = urlencode("/min/project")
  override_value = 2700
}
```

For the limit are you using `urlencode("/min/project")`? Or are you using project/region or project/user like in this [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override#limit)?

**Comment by sato-s** [comment]
@ggtisc 
Thank you for your replay! 👍 
Here is complete example of tf files that will cause the error.

main.tf
```terraform
terraform {
  required_version = ">= 1.9.0"

  required_providers {
    google = {
      version = "~> 5.36.0"
    }

    google-beta = {
      version = "~> 5.36.0"
    }
  }
}

provider "google" {
  project = "[Your Project Name]"
  region  = "asia-northeast1"
}

provider "google-beta" {
  project = "[Your Project Name]"
  region  = "asia-northeast1"
}
```

data.tf
```
data "google_project" "project" {}
```

quotas.tf
```
resource "google_service_usage_consumer_quota_override" "override" {
  provider       = google-beta
  project        = data.google_project.project.id
  service        = "cloudbuild.googleapis.com"
  metric         = urlencode("cloudbuild.googleapis.com/get_requests")
  limit          = urlencode("/min/project")
  override_value = 2700
}
```

> For the limit are you using urlencode("/min/project")? Or are you using project/region or project/user like in this [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override#limit)?

I'm using `urlencode("/min/project")` as written in the above example.

**Comment by ggtisc** [comment]
Thank you @sato-s!

Please try the next just by adapting the quotas.tf:

```
resource "google_service_usage_consumer_quota_override" "override" {
  provider       = google-beta
  project        = "my-project" # change this
  service        = "cloudbuild.googleapis.com"
  metric         = urlencode("cloudbuild.googleapis.com/get_requests")
  limit          = urlencode("/min/project")
  override_value = 2700
  force = true # new argument to force the change
}
```

**Comment by sato-s** [comment]
@ggtisc 
Thanks!
That solved my problem.

I found consumer quota isn't what I imagined though.
https://github.com/hashicorp/terraform-provider-google/issues/11450
