### ISSUE TITLE
Compute address resource fails with "project required" while docs say otherwise

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform-provider-google#1975]
As per issue title, when creating a compute address, Terraform fails with the following while the [docs](https://www.terraform.io/docs/providers/google/r/compute_address.html#project) state the `project` attribute is optional.

Terraform version is `0.11.8`. Google provider version is `1.17.1`

The following should be enough to reproduce:
```
provider "google" {
  project = "a-project"
  region = "a-region"
  version = "1.17.1"
}

resource "google_compute_address" "default" {
  name = "the-address"
}
```

**Comment by danawillow** [comment]
Hey @walterdolce, I'm not able to repro this; that config creates an address just fine for me. Can you show me the error message you got, as well as `terraform plan` output if you have it?
