### ISSUE TITLE
Media CDN EdgeCacheService HostRules resources limit smaller than the Google API (10 vs 50).

### ISSUE THREAD

**Issue by alexjj1** [hashicorp/terraform-provider-google#19780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v0.13.7

### Affected Resource(s)

google_resource_network_services_edge_cache_service.go

### Terraform Configuration

In google/services/networkservices/resource_network_services_edge_cache_service.go, the MaxItems limit is 10:

```
host_rule": {
	Type:        schema.TypeList,
	Required:    true,
	MaxItems:    10,
}
```

### Expected Behavior

According to https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#routing, one may specify up to 50 host rules. Terraform should not artificially restrict the number of items.

### Actual Behavior

Terraform limits host rules to 10.

### Steps to reproduce

Add more than 10 host rules and then terraform apply.

b/372531267

**Comment by ggtisc** [comment]
Confirmed issue!

I can't define if this is a documentation issue or a bug because there are inconsistencies while the [APi](https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#routing) says that you can specify up to 50 `host rules` [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/network_services_edge_cache_service#hosts) states that the limit is just 10.

**Comment by alexjj1** [comment]
`host rules ` and `hosts` are two different types with different limits. The `host rule` limit is 50 within a Routing block: https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#routing.

And the `host` limit is 10 within a HostRule block: https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#hostrule.

That limit you linked in the terraform registry refers to the number of hosts within a HostRule. My report is about the limit of HostRules within a Routing block.

**Comment by yshakoor** [comment]
The fix is available in the main branch but still not available in the latest release https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.12.0, do we have time-line when this fix will be available.
