### ISSUE TITLE
provider setting false values in google_container_node_pool kubelet_config, breaking tf apply

### ISSUE THREAD

**Issue by prune998** [hashicorp/terraform-provider-google#19792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.7
on darwin_arm64

+ provider registry.terraform.io/hashicorp/google v6.6.0

### Affected Resource(s)

`google_container_node_pool`

this is created using the [private-cluster](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/private-cluster) module

### Terraform Configuration

```tf
nonspot-apps-e2st16              = {
  auto_repair        = "true"
  auto_upgrade       = "true"
  autoscaling        = "true"
  disk_size_gb       = "50"
  disk_type          = "pd-balanced"
  enable_gcfs        = "true"
  enable_secure_boot = "false"
  image_type         = "COS_CONTAINERD"
  initial_node_count = "0"
  instance_class     = "e2-standard"
  location_policy    = "BALANCED"
  machine_type       = "e2-standard-16"
  max_count          = "200"
  max_pods_per_node  = "64"
  max_surge          = "5"
  min_count          = "0"
  name               = "nonspot-apps-e2st16"
  number             = "16"
  orig_name          = "gke-shared-on-demand"
  service_node_label = "gke-shared-on-demand"
  sizes              = "4,8,16"
  skip_spot          = "true"
}
```

### Expected Behavior

The nodepool should be created on the first apply, and any consecutive applies should do nothing.
values should not be stored in the plan and should not include made-up values

### Actual Behavior

First apply creates the nodepool.

The state contains a section for `kubelet_config` that was not set in the first place:

```
terraform state show 'google_container_node_pool.pools["nonspot-apps-e2st16"]'

# google_container_node_pool.pools["nonspot-apps-e2st16"]:
resource "google_container_node_pool" "pools" {
    cluster                     = "prod-cluster"
    id                          = "projects/production-ops/locations/us-east4/clusters/prod-cluster/nodePools/nonspot-apps-e2st16"

...

    node_config {
        ...
        
        gcfs_config {
            enabled = true
        }

        kubelet_config {
            cpu_cfs_quota                          = false
            insecure_kubelet_readonly_port_enabled = "TRUE"
            pod_pids_limit                         = 0
        }
        ...
    }
}
```

Following apply try to update the nodepool like:
```
11:13:36.828 STDOUT terraform:   ~ update in-place
11:13:36.828 STDOUT terraform: Terraform will perform the following actions:
11:13:36.828 STDOUT terraform:   # google_container_node_pool.pools["nonspot-apps-e2st16"] will be updated in-place
11:13:36.828 STDOUT terraform:   ~ resource "google_container_node_pool" "pools" {
11:13:36.828 STDOUT terraform:         id                          = "projects/production-ops/locations/us-east4/clusters/prod-cluster/nodePools/nonspot-apps-e2st16"
11:13:36.828 STDOUT terraform:         name                        = "nonspot-apps-e2st16"
11:13:36.828 STDOUT terraform:         # (11 unchanged attributes hidden)
11:13:36.828 STDOUT terraform:       ~ node_config {
11:13:36.828 STDOUT terraform:           - kubelet_config {
11:13:36.828 STDOUT terraform:               - cpu_cfs_quota                          = false -> null
11:13:36.828 STDOUT terraform:               - insecure_kubelet_readonly_port_enabled = "TRUE" -> null
11:13:36.828 STDOUT terraform:               - pod_pids_limit                         = 0 -> null
11:13:36.828 STDOUT terraform:                 # (2 unchanged attributes hidden)
11:13:36.828 STDOUT terraform:             }
11:13:36.828 STDOUT terraform:             # (3 unchanged blocks hidden)
11:13:36.828 STDOUT terraform:         }
11:13:36.828 STDOUT terraform:         # (5 unchanged blocks hidden)
11:13:36.829 STDOUT terraform:     }
11:13:36.829 STDOUT terraform: Plan: 0 to add, 1 to change, 0 to destroy.
```

Which fail the apply with:

```
google_container_node_pool.pools["nonspot-apps-e2st16"]: Modifying... [id=projects/production-ops/locations/us-east4/clusters/prod-cluster/nodePools/nonspot-apps-e2st16]
╷
│ Error: googleapi: Error 400: At least one of ['node_version', 'image_type', 'updated_node_pool', 'locations', 'workload_metadata_config', 'upgrade_settings', 'kubelet_config', 'linux_node_config', 'tags', 'taints', 'labels', 'node_network_config', 'gcfs_config', 'gvnic', 'confidential_nodes', 'logging_config', 'fast_socket', 'resource_labels', 'accelerators', 'windows_node_config', 'machine_type', 'disk_type', 'disk_size_gb', 'storage_pools', 'containerd_config', 'resource_manager_tags', 'performance_monitoring_unit', 'queued_provisioning', 'max_run_duration'] must be specified.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0xa4b452d1aff58003"
│   }
│ ]
│ , badRequest
│ 
│   with google_container_node_pool.pools["nonspot-apps-e2st16"],
│   on cluster.tf line 506, in resource "google_container_node_pool" "pools":
│  506: resource "google_container_node_pool" "pools" {
│ 
```

### Steps to reproduce

1. `terraform apply`

b/372700144

**Comment by prune998** [comment]
It seems the newly created google `nodepools` now have `kubeletConfig` created by default:

```
gcloud container node-pools describe  --project production-ops --cluster prod-cluster --location us-east4 --format json test-pool-1  | jq '.'
{
  "autoscaling": {},
  "config": {
    "advancedMachineFeatures": {
      "enableNestedVirtualization": false
    },
    "diskSizeGb": 100,
    "diskType": "pd-balanced",
    "effectiveCgroupMode": "EFFECTIVE_CGROUP_MODE_V2",
    "imageType": "COS_CONTAINERD",
    "kubeletConfig": {
      "insecureKubeletReadonlyPortEnabled": true
    },
...
```

I guess this is confusing the provider ?

**Comment by wyardley** [comment]
So, there may not be a perfect / ideal solution to this in the short term.
One reason it's stored as an enum in state (at the request of the maintainers) when added in https://github.com/GoogleCloudPlatform/magic-modules/pull/11573 (vs. a native boolean) was partially to solve the issue of the default not being stable here (though it will be interesting to see if the integration tests will have issues if any defaults have changed).

The API doesn't return a value when it's empty; it's possible that there is an upstream change to explicitly set it to true on new clusters, maybe in preparation for the default changing in new clusters and / or certain cluster versions? I'm guessing in the long run, once this defaults to unset, things will probably be more stable / less of a hassle.

If you don't actually need the insecure kubelet port to be enabled, I would suggest setting it to false (out of band) using the CLI.

I'll comment in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2082 as well.

**Comment by rileykarson** [comment]
A changed default serverside for `insecureKubeletReadonlyPortEnabled` means the `kubeletConfig` block should have been marked to accept server-side changes (i.e. be made Optional + Computed) as well. `schemaInsecureKubeletReadonlyPortEnabled` was insulated against them, and the enum change was necessary to allow sending explicit false values while also accepting server-side changes to the default.

This affects configurations `google_container_cluster` configurations with `node_pool.node_config` defined, or `google_container_node_pool` resources with `node_config` defined, but `kubelet_config` not defined. `lifecycle.ignore_changes` on `kubelet_config` can mitigate in the meantime.

Will send out a fix in a few, just trying to see if I can understand why some configurations had this issue and others didn't last night- the anticipated default changes are tied to a specific GKE version, and we're seeing inconsistent behaviour between clusters with the same default GKE version. Possibly just a partial rollout (although ours are mainly in the same region).

**Comment by chuyang-deng** [comment]
>  just trying to see if I can understand why some configurations had this issue and others didn't last night

The change of explicitly setting the config is gradually rolling out and should be fully rolled out by next week.

**Comment by rileykarson** [comment]
Thanks for confirming @chuyang-deng!

PR up as https://github.com/GoogleCloudPlatform/magic-modules/pull/11971. Assuming no surprises I'm currently planning to cherrypick this into the `6.7.0` release Monday, and then prepare a backport as `5.44.2` early next week (I want to check there aren't further changes we need to support the eventual default flip before cutting that backport).

**Comment by rileykarson** [comment]
`6.7.0` and `5.44.2` are both out for `google` and `google-beta` and include the fix for this issue.
