### ISSUE TITLE
Add "header_action" and "redirect_options" fields to compute_security_policy_rule resource

### ISSUE THREAD

**Issue by matheusaleixo-cit** [hashicorp/terraform-provider-google#19805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add support for the fields "header_action" and "redirect_options" to the resource "google_compute_security_policy_rule".
These fields are supported when managing the rules via the "google_compute_security_policy" resource, but are missing from the policy rules resource.

### New or Affected Resource(s)

* google_compute_security_policy_rule

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy_rule" "policy_rule" {
  security_policy = google_compute_security_policy.default.name
  action          = "redirect"
  priority        = "100"
  match {
    versioned_expr = "SRC_IPS_V1"
    config {
      src_ip_ranges = ["*"]
    }
  }

  redirect_options {
    type = "EXTERNAL_302"
    target = "https://example.com"
  }
  header_action {
    request_headers_to_adds {
      header_name  = "X-Hello"
      header_value = "World"
    }
  }
}
```

### References

[API](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/addRule#:~:text=below%20the%20threshold.-,headerAction,object,-Optional%2C%20additional%20actions)

b/372701380

**Comment by SarahFrench** [comment]
Note from triage:
* [header_action field](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/addRule#body.request_body.FIELDS.header_action)
* [redirect_options field](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/addRule#body.request_body.FIELDS.redirect_options)

These fields are both "only supported in Global Security Policies of type CLOUD_ARMOR" and we could add validation in the provider to enforce this at plan-time, or just make sure this is noted in the provider documentation's description of the new fields.
