### ISSUE TITLE
Cannot create a google_container_node_pool with n4 series

### ISSUE THREAD

**Issue by epot** [hashicorp/terraform-provider-google#19890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.5
on darwin-arm64
+ provider registry.terraform.io/hashicorp/google v6.7.0

### Affected Resource(s)

google_container_node_pool

### Terraform Configuration

```tf


resource "google_container_node_pool" "service_nodes" {
  name     = "node-pool"
  location = xxx
  cluster  = xxx

  node_config {
    machine_type = `n4-highmem-2`

    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.sa_kube.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    # required to enable workload identity on node pool
    workload_metadata_config {
      mode = "GKE_METADATA"
    }
  }
}
```

### Debug Output

``` 
Error: googleapi: Error 400: 'pd-balanced' is not a compatible disk type with the machine type n4-highmem-2, please review the GCP online documentation for available persistent disk options.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0xbf908e2d11d740db"
│   }
│ ]
│ , badRequest
│
│   with module.environment.module.cluster_2.module.saasy.google_container_node_pool.service_nodes,
│   on ../../../modules/gcp/environment/cluster/service/nodepool.tf line 3, in resource "google_container_node_pool" "service_nodes":
│    3: resource "google_container_node_pool" "service_nodes" {
│
╵
Operation failed: failed running terraform apply (exit 1)
```

### Expected Behavior

I expect to get a success (it works with n2 instances)

### Actual Behavior

I get the error above.

### Steps to reproduce

1. `terraform apply`

**Comment by sbocinec** [comment]
@epot  this works as expected and exactly as the error explains: `Error: googleapi: Error 400: 'pd-balanced' is not a compatible disk type with the machine type n4-highmem-2, please review the GCP online documentation for available persistent disk options.`

N4 instances do not support `pd-balanced`, only `hyperdisk-balanced` disk type https://cloud.google.com/compute/docs/general-purpose-machines#n4_series
![image](https://github.com/user-attachments/assets/e2b298d5-ca41-4d8c-b6cf-2b9822968d38)


As you didn't provide a `disk_type` in the `node_config`, it uses a Persistent disk by default https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_node_config

**Comment by ggtisc** [comment]
Hi @epot as @sbocinec says you need to check the compatibility between components and machines. After trying with the following `n4-highmem-2` configuration everything was good without errors:

resource "google_container_cluster" "ccluster_19890" {
  name                      = "ccluster-19890"
  location                  = "us-central1"
  remove_default_node_pool  = true
  initial_node_count        = 1
  deletion_protection       = false

  workload_identity_config {
    workload_pool = "my-project.svc.id.goog" #replace my-project with your own project or the whole workload_pool with your own
  }
}

resource "google_service_account" "service_account_19890" {
  account_id = "service-account-19890"
}

resource "google_container_node_pool" "container_node_pool_19890" {
  name     = "container-node-pool-19890"
  location = "us-central1"
  cluster  = google_container_cluster.ccluster_19890.name

  node_config {
    machine_type = "n4-highmem-2"

    service_account = google_service_account.service_account_19890.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    workload_metadata_config {
      mode = "GKE_METADATA"
    }
  }
}

I suggest you check the link shared by @sbocinec to confirm the compatibility searching for `Supported disk types` for each machine type

**Comment by epot** [comment]
Oops sorry I am an idiot, it is working fine now!
