### ISSUE TITLE
Failing test(s): TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample + more

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#19983]
### Impacted tests

- ~TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample~
- TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample
- ~TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterBasicExample~
- ~TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterFullExample~

### Affected Resource(s)

- google_oracle_database_cloud_exadata_infrastructure

https://github.com/GoogleCloudPlatform/magic-modules/pull/11879

### Failure rates

- 100% since 2024-10-10

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample
=== PAUSE TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample
=== CONT  TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample
    resource_oracle_database_cloud_exadata_infrastructure_generated_test.go:42: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating CloudExadataInfrastructure: googleapi: Error 409: Conflict: CloudExadataInfrastructure name with same projectNumber has been used
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "903e5e8aeeab5c88"
          }
        ]
          with google_oracle_database_cloud_exadata_infrastructure.my-cloud-exadata,
          on terraform_plugin_test.tf line 2, in resource "google_oracle_database_cloud_exadata_infrastructure" "my-cloud-exadata":
           2: resource "google_oracle_database_cloud_exadata_infrastructure" "my-cloud-exadata"{
--- FAIL: TestAccOracleDatabaseCloudExadataInfrastructure_oracledatabaseCloudExadataInfrastructureBasicExample (6.17s)
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample
=== PAUSE TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample
=== CONT  TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample
    resource_oracle_database_autonomous_database_generated_test.go:98: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating AutonomousDatabase: googleapi: Error 409: Resource 'projects/oci-terraform-testing/locations/us-east4/autonomousDatabases/my-adb-instance-id-2' already exists
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.ResourceInfo",
            "resourceName": "projects/oci-terraform-testing/locations/us-east4/autonomousDatabases/my-adb-instance-id-2"
          }
        ]
          with google_oracle_database_autonomous_database.myADB,
          on terraform_plugin_test.tf line 2, in resource "google_oracle_database_autonomous_database" "myADB":
           2: resource "google_oracle_database_autonomous_database" "myADB"{
--- FAIL: TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample (7.61s)
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterBasicExample
=== PAUSE TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterBasicExample
=== CONT  TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterBasicExample
    resource_oracle_database_cloud_vm_cluster_generated_test.go:44: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating CloudExadataInfrastructure: googleapi: Error 409: Conflict: CloudExadataInfrastructure name with same projectNumber has been used
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "b66d9dbfc809c7eb"
          }
        ]
          with google_oracle_database_cloud_exadata_infrastructure.cloudExadataInfrastructures,
          on terraform_plugin_test.tf line 22, in resource "google_oracle_database_cloud_exadata_infrastructure" "cloudExadataInfrastructures":
          22: resource "google_oracle_database_cloud_exadata_infrastructure" "cloudExadataInfrastructures"{
--- FAIL: TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterBasicExample (5.73s)
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterFullExample
=== PAUSE TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterFullExample
=== CONT  TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterFullExample
    resource_oracle_database_cloud_vm_cluster_generated_test.go:116: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating CloudExadataInfrastructure: googleapi: Error 409: Conflict: CloudExadataInfrastructure name with same projectNumber has been used
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "230b79d1d2861cd9"
          }
        ]
          with google_oracle_database_cloud_exadata_infrastructure.cloudExadataInfrastructures,
          on terraform_plugin_test.tf line 43, in resource "google_oracle_database_cloud_exadata_infrastructure" "cloudExadataInfrastructures":
          43: resource "google_oracle_database_cloud_exadata_infrastructure" "cloudExadataInfrastructures"{
--- FAIL: TestAccOracleDatabaseCloudVmCluster_oracledatabaseCloudVmclusterFullExample (5.79s)
FAIL
```

### Nightly build test history

- https://hashicorp.teamcity.com/test/-8738921109466101302?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&branch=refs%2Fheads%2Fnightly-test&expandTestHistoryChartSection=true

b/381934722

**Comment by tulika-aakriti** [comment]
Looks like there were some cleanup from partner side which resulted in dangling resources. I have manually cleaned up all the resources and have recreated the permanent ones for datasource tests.

**Comment by SarahFrench** [comment]
I've updated the issue description with more up-to date error messages from these tests. Currently the tests are failing 100% of the time so I've updated labels.

TestAccOracleDatabaseAutonomousDatabase_oracledatabaseAutonomousDatabaseFullExample is experiencing a name collision - the test should be updated to provision a google_oracle_database_autonomous_database resource that has a name starting `tf-test-` and ending in a random string to ensure uniqueness.

The other tests experiencing `Error 409: Conflict: CloudExadataInfrastructure name with same projectNumber has been used` suggest that they're trying to provision a resource where there can only be one per project? If that's the case then the tests can be made to stop running in parallel by removing `t.Parallel()`. This would require more discovery to diagnose properly and address.

**Comment by tulika-aakriti** [comment]
>>Currently the tests are failing 100% of the time so I've updated labels.
Can we try to run the tests again. I have have cleaned all the resources. (assumption there shouldn't be any name collisions)

>> Suggest that they're trying to provision a resource where there can only be one per project?  
Yes the resources id should be unique. If the tests ` terraform destroy ` before next run we shouldn't be facing any of these errors.  

``` If that's the case then the tests can be made to stop running in parallel by removing t.Parallel() ``` Let me know if this is this a permanent solutions.

**Comment by SarahFrench** [comment]
👆🏻 In those PRs I've addressed the naming issues, so the tests should no longer be affected by errors due to using names of resources that already exist.

There may be some other issues that the naming issues were masking, but we'll see.

>If the tests terraform destroy before next run we shouldn't be facing any of these errors.

Sadly tests can fail in a way that prevents the test from cleaning up after itself, and that's what can cause the original issue causing the test failure. [Sweepers](https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/sweepers) are the way we remove those resources automatically, without manual intervention/toil from engineers. However I can see there aren't any sweepers for Oracle Database resources currently.

**Comment by tulika-aakriti** [comment]
> 👆🏻 In those PRs I've addressed the naming issues, so the tests should no longer be affected by errors due to using names of resources that already exist.

Thanks for this, I see that the new names doesn't contains ofake- prefix which will lead to create a actual resource( This take time in creation and takes other resources from partner API)

**Comment by tulika-aakriti** [comment]
I see the tests have already start failing with limitexceed ``` LimitExceeded: Provisioning Exadata Infrastructure failed after maximum retries. Cause: The following service limits were exceeded: exadata-database-server-x9m-count, exadata-storage-server-x9m-count. Request a service limit increase from the service limits page in the console. ``` The creation take 3-5hrs for a resource and in every test run we have populated resource which has not be cleaned, deletion will also take somewhere around 3-5hrs. while for fake ones it's <1hr. We need to add ofake- in the test run for vmcluster and cloud exadata resources.
while for other assertions issue i have created this PR https://github.com/GoogleCloudPlatform/magic-modules/pull/12484

**Comment by SarahFrench** [comment]
Thanks, I've opened a PR to add that prefix and included a comment about its importance: https://github.com/GoogleCloudPlatform/magic-modules/pull/12497

>Is there a way we can use sweepers but have ofake prefix for vmcluster and cloud exadata resources ? We need to take serious actions here to revert the id name or add ofake prefix in id and displayname.

I've opened an issue for that here: https://github.com/hashicorp/terraform-provider-google/issues/20599

**Comment by tulika-aakriti** [comment]
Thank you for the PR, left few nits so that it will be easier for backend to debug later in future.  Once the PR is merged the asssertions  should be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/12484

**Comment by SarahFrench** [comment]
Issue was closed accidentally - currently all the tests are passing except what's described in https://github.com/GoogleCloudPlatform/magic-modules/pull/12523
