### ISSUE TITLE
Add data source for retrieving all service accounts from a project

### ISSUE THREAD

**Issue by bestefreund** [hashicorp/terraform-provider-google#20025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add data source for retrieving all service accounts from a project

### New or Affected Resource(s)

* google_service_accounts

### Potential Terraform Configuration

```tf
data "google_service_accounts" "example" {
  project = "example-project"
}
```

### References

https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/list

b/376066147

**Comment by melinath** [comment]
Note from triage: information for pagination support: https://github.com/hashicorp/terraform-provider-google/issues/19157 Information about plural datasources: https://github.com/hashicorp/terraform-provider-google/issues/8255
