### ISSUE TITLE
Failing test(s): TestAccSpannerDatabase_mrcmek (beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#20039]
### Impacted tests

- TestAccSpannerDatabase_mrcmek (beta)

### Affected Resource(s)

- google_XXXXX

### Failure rates

- 100% since 2024-10-15

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccSpannerDatabase_mrcmek
=== PAUSE TestAccSpannerDatabase_mrcmek
=== CONT  TestAccSpannerDatabase_mrcmek
    resource_spanner_database_test.go:626: Step 1/2 error: Error running apply: exit status 1
        Error: Error creating Database: googleapi: Error 400: KMS Key provided is not usable: ServiceAccount: service-653407317329@gcp-sa-spanner.iam.gserviceaccount.com KmsKeyName: projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tf-mr-cmek-test-key-us-central1 Error: generic::permission_denied: Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource 'projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tf-mr-cmek-test-key-us-central1' (or it may not exist). [google.rpc.error_details_ext] { message: "Permission \'cloudkms.cryptoKeyVersions.useToEncrypt\' denied on resource \'projects/PROJECT_ID/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tf-mr-cmek-test-key-us-central1\' (or it may not exist)." details { [type.googleapis.com/google.rpc.DebugInfo] { detail: "cloud/security/kms/util/iam_authz.cc:244 - " } } }.
          with google_spanner_database.database,
          on terraform_plugin_test.tf line 9, in resource "google_spanner_database" "database":
           9: resource "google_spanner_database" "database" {
--- FAIL: TestAccSpannerDatabase_mrcmek (15.43s)
FAIL
```

### Nightly build test history

[- https://hashicorp.teamcity.com/...
](https://hashicorp.teamcity.com/test/64549409986271997?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true)

b/376067278

**Comment by melinath** [comment]
Note from triage: This looks like it should bootstrap the iam permissions using the utils in https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/acctest/bootstrap_iam_test_utils.go

**Comment by wyardley** [comment]
> Note from triage: This looks like it should bootstrap the iam permissions using the utils in https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/acctest/bootstrap_iam_test_utils.go

@melinath Yeah, I think #12152 will do that, and also do it in the same way in the cmek test.
