### ISSUE TITLE
Remove out of date references to maintainer etiquette

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform-provider-google#20047]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md has a different contributing doc from magic-modules or terraform-provider-google-beta, and refers to a doc that's no longer present (https://github.com/hashicorp/terraform/blob/main/docs/maintainer-etiquette.md)

### References

https://github.com/hashicorp/terraform/pull/32741/files

**Comment by SarahFrench** [comment]
Thanks for opening this issue, that contribution doc is from before my time at HashiCorp and could use a bunch of attention, including:
- [Whether this section is even relevant to maintainers anymore](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#maintainer-specific-information), and could be deleted
- Determining is [RELEASE_DIFF](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#ensuring-no-plan-time-difference-to-latest-provider-release-optional) usage is common (there is code related to this I've often been thinking I should look into more!)

For now I'll remove that reference to a maintainer etiquette doc, but I'll leave this issue open until I address the above.

The only contribution docs that should be relevant to contributions now is the guide for Magic Modules at https://googlecloudplatform.github.io/magic-modules/
