### ISSUE TITLE
Sweep run example?

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform-provider-google#20048]
### Question

Can you provide an up to date example of "sweep" runs, and potentially update existing docs and / or add a make target?

The example here:
https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#sweepers
doesn't seem to run as-is, and it's not totally clear what are valid values for `-sweep-run`, or whether one should use the specific sub-service (`google/services/foo`), or just the top level `google` directory.

Running given examples (from the page above and the link below) results in an error:
```
% TF_LOG=TRACE make testacc TEST=./google  TESTARGS='-sweep=us-central1 -sweep-run='  ## fails if you put a service name in `-sweep-run` too
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -sweep=us-central1 -sweep-run= -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
no Go files in /xxxx/yyy/go/src/github.com/hashicorp/terraform-provider-google/google
make: *** [testacc] Error 1
% SKIP_PROJECT_SWEEPER=1 go test ./google -v -sweep=us-central1 -sweep-run=
no Go files in /xxxx/yyy/github.com/hashicorp/terraform-provider-google/google
```

Specifying a specific service path (which I'm assuming isn't intended) like `google/services/container` instead of `google/` seems to result in it trying to _run_ the tests in the given directory.

Also, end users might want to know about `SKIP_PROJECT_SWEEPER=1` as mentioned [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/551f48015dbed65b65a5610cbb41b02f7f801bc6/mmv1/third_party/terraform/services/resourcemanager/resource_google_project_sweeper.go#L18-L22), especially if a regular sweep run would kill their test project.

Might also be good to link to the docs on sweep at https://googlecloudplatform.github.io/magic-modules/develop/test/run-tests/ and / or elsewhere in the Magic Modules docs (so it's searchable).

**Comment by SarahFrench** [comment]
This might be some of the info you're looking for: https://github.com/hashicorp/terraform-provider-google/issues/17891#issuecomment-2504348644

I think this issue (even though it's a question) is essentially a duplicate of that linked issue - if there's info about sweepers that would be useful to know about as a contributor then that issue would be a good place to provide feedback

**Comment by wyardley** [comment]
Closing for linked ticket
