### ISSUE TITLE
Appears to have resolved itself on 2023-12-20 after ~a week.

### ISSUE THREAD

**Issue by harrymyburgh** [hashicorp/terraform-provider-google#20055]
Appears to have resolved itself on 2023-12-20 after ~a week.

_Originally posted by @rileykarson in https://github.com/hashicorp/terraform-provider-google/issues/16804#issuecomment-1977677154_
            

This issue has not resolved itself. It is still an issue occurring with the `hashicorp/google` provider as of version `~>6.6.0`.

**Comment by melinath** [comment]
The linked issue is a test failure ticket related to the `TestAccComputeSubnetwork_subnetworkInternalL7lbExample` test. That test is currently passing (and has been for at least 3 months). If you are experiencing the diff described in that ticket, please fill out the [bug template](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=bug&projects=&template=00_bug.yml) to make sure we have all the information we need to help with your issue. Thanks!
