### ISSUE TITLE
Error creating EdgeCacheOrigin: googleapi: Error 404: Method not found.

### ISSUE THREAD

**Issue by Colt45s** [hashicorp/terraform-provider-google#20098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.4.6
on linux/amd64
+ provider registry.terraform.io/hashicorp/google v6.9.0

### Affected Resource(s)

google_network_services_edge_cache_origin

### Terraform Configuration

```tf
```

### Actual Behavior

```
google_network_services_edge_cache_origin.default: Creating...
Error: Error creating EdgeCacheOrigin: googleapi: Error 404: Method not found.
  with google_network_services_edge_cache_origin.default,
  on main.tf line 1, in resource "google_network_services_edge_cache_origin" "default":
   1: resource "google_network_services_edge_cache_origin" "default" {
```

### Steps to reproduce

1. `terraform apply`

### References

Related: https://github.com/hashicorp/terraform-provider-google/issues/14903#issuecomment-2414853418

**Comment by wyardley** [comment]
Did you find any workaround / fix?
