### ISSUE TITLE
Media CDN EdgeCacheService PathMatchers resources limit smaller than the Google API (10 vs 50).

### ISSUE THREAD

**Issue by alexjj1** [hashicorp/terraform-provider-google#20197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v0.13.7

### Affected Resource(s)

google_resource_network_services_edge_cache_service.go

### Terraform Configuration

In google/services/networkservices/resource_network_services_edge_cache_service.go, the MaxItems limit is 10:

```
"path_matcher": {
    Type:        schema.TypeList,
    Required:    true,
    Description: `The list of pathMatchers referenced via name by hostRules. PathMatcher is used to match the path portion of the URL when a HostRule matches the URL's host portion.`,
    MinItems:    1,
    MaxItems:    10,
```

### Expected Behavior

According to https://cloud.google.com/media-cdn/docs/reference/rest/v1/projects.locations.edgeCacheServices#routing, one may specify up to 50 path matchers. Terraform should not artificially restrict the number of items.

We would like to use this together with the increased host rule limit. I filed a bug for that here: https://github.com/hashicorp/terraform-provider-google/issues/19780

### Actual Behavior

Terraform limits path matchers to 10.

### Steps to reproduce

Add more than 10 path matchers and then terraform apply.

**Comment by ggtisc** [comment]
Duplicated issue https://github.com/hashicorp/terraform-provider-google/issues/19780

**Comment by yshakoor** [comment]
The fix is available in the main branch but still not available in the latest release https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.12.0, do we have time-line when this fix will be available.
