### ISSUE TITLE
Add terraform resources for Principal Access Boundary policy Binding for GCP

### ISSUE THREAD

**Issue by priyankadeo-g** [hashicorp/terraform-provider-google#20198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

GCP's Identity and Access Management (IAM) offers a new security policy type called Principal Access Boundary policies. Principal access boundary (PAB) policies let you restrict the resources that principals can access. Users can use principal access boundary policies to prevent their principals from accessing resources in other organizations, which can help prevent phishing attacks or data exfiltration. For applying a Principal Access Boundary policy to a resource, after you create a principal access boundary policy, you create a policy binding to apply the policy to a set of principals.

Please find detailed documentation here https://cloud.google.com/iam/docs/principal-access-boundary-policies#binding

### New or Affected Resource(s)

* google_iam_organizations_policy_binding

### Potential Terraform Configuration

```
resource "google_iam_organizations_policy_binding" "principal_access_boundary_binding" {
  location = xxx
  policy_binding_id = xxx
  policy = xxx
  policyKind = xxx
  target = xxx
}
```

### References

https://github.com/hashicorp/terraform-provider-google/issues/19905 - Principal Access Boundary policy

**Comment by SarahFrench** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/12251
