### ISSUE TITLE
Build a GKE private cluster with our master_ipv4_cidr_block

### ISSUE THREAD

**Issue by SrinivasMajeti** [hashicorp/terraform-provider-google#20191]
### Question

I am trying to build GKE private cluster with GKE 1.29+ version with out using master_ipv4_cidr_block which I am able to build when done through google console UI,

I am getting below 

Expected behavior:

Cluster to be build

Actual Behavior:

google_container_cluster.gke_private: Creating...
╷
│ Error: master_ipv4_cidr_block must be set if enable_private_nodes is true
│
│   with google_container_cluster.gke_private,
│   on main.tf line 7, in resource "google_container_cluster" "gke_private":
│    7: resource "google_container_cluster" "gke_private" {

Versions used:
required_version=">=1.3.9"

required_providers
{
google="6.6.0"
google-beta="6.6.0"
}

**Comment by wyardley** [comment]
I'm thinking that #12195 fixes this, possibly @gontech @rileykarson? The fix I had in the linked PR was wrong, but I also can't reproduce the issue against trunk, though I can in 6.10.0.

**Comment by SrinivasMajeti** [comment]
But https://github.com/hashicorp/terraform-provider-google/pull/12195 is just adding go version to the make file.

**Comment by SrinivasMajeti** [comment]
Thank you will wait for 6.11.0

**Comment by wyardley** [comment]
Thanks! Sorry, always forget about needing to reference the correct repo on issue links. I updated the above, but did indeed mean https://github.com/GoogleCloudPlatform/magic-modules/pull/12195
