### ISSUE TITLE
When updating google_apigee_developer, an error occurs, preventing the Apigee developer from being updated  

### ISSUE THREAD

**Issue by paullexandre51** [hashicorp/terraform-provider-google#20226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google vv6.10.0
+ provider registry.terraform.io/hashicorp/google-beta vv6.10.0

### Affected Resource(s)

google_apigee_developer

### Terraform Configuration

```tf
resource "google_apigee_developer" "main" {
  for_each   = local.apim_devs
  org_id     = data.terraform_remote_state.apigee.outputs.org_id
  email      = each.value.email
  first_name = each.value.first_name
  last_name  = each.value.last_name
  user_name  = each.value.user_name
  
dynamic "attributes" {
     for_each = try(each.value["attributes"], [])
     content {
       name  = attributes.value.name
       value = attributes.value.value
     }
   }
```

### Expected Behavior

The Apigee Developer should be updated.

### Actual Behavior

 googleapi: Error 400: Invalid JSON payload received. Unknown name "updateMask": Cannot bind query parameter. Field 'updateMask' could not be found in request message.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid JSON payload received. Unknown name \"updateMask\": Cannot bind query parameter. Field 'updateMask' could not be found in request message."
│       }
│     ]
│   }
│ ]

### Steps to reproduce

1. `terraform init`
2. `terraform apply`

b/379172536

**Comment by ggtisc** [comment]
Confirmed issue when trying to update an existing `google_apigee_developer` resource arguments it returns the following error:

```
Error: Error updating Developer "organizations/my-project/developers/my-user@my-domain.com": googleapi: Error 400: Invalid JSON payload received. Unknown name "updateMask": Cannot bind query parameter. Field 'updateMask' could not be found in request message.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid JSON payload received. Unknown name \"updateMask\": Cannot bind query parameter. Field 'updateMask' could not be found in request message."
│       }
│     ]
│   }
│ ]
│ 
│   with google_apigee_developer.apigee_developer_20226,
│   on main.tf line 60, in resource "google_apigee_developer" "apigee_developer_20226":
│   60: resource "google_apigee_developer" "apigee_developer_20226" {
```

[Example used link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_developer#example-usage---apigee-developer-with-attributes)
