### ISSUE TITLE
numeric id required for tag binding is missing on many resources

### ISSUE THREAD

**Issue by Sir-AlexD** [hashicorp/terraform-provider-google#20223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Terraform resources **google_tags_tag_binding** and **google_tags_location_tag_binding** require numerid_id in parent field to bind tag to resources.

Example :

```tf
resource "google_tags_location_tag_binding" "binding" {
  parent    = "//compute.googleapis.com/projects/123/regions/us-central1/subnetworks/456"
  tag_value = "tagValues/567890123456"
  location  = "us-central1"
}
```

However, this field (numeric_id) is often missing from the output of Terraform resources that can be tagged, complicating the code (see affected resources below).

Une resource terraform null_resource with gcloud comand in local-exec provisioner can be a alternative but is not very convenient if we want to tag many resources.

### New or Affected Resource(s)

* google_compute_global_forwarding_rule
* google_compute_region_instance_group_manager
* google_compute_region_health_check
* google_compute_subnetwork
* google_compute_region_network_endpoint_group

**Comment by wyardley** [comment]
Just a question (not a Google or Hashicorp employee, and not super familiar with tags, though have worked at updating some of the tests and examples that use these recently):

Normally, I've seen the tag key / value defined directly in Terraform, like the example in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding

In that case, you can use the `.id` attribute for when referencing both the key and the value, e.g.,

```terraform
resource "google_tags_tag_key" "key" {
  parent      = "organizations/123456789"
  short_name  = "keyname"
  description = "For keyname resources."
}

resource "google_tags_tag_value" "value" {
  parent      = google_tags_tag_key.key.id
  short_name  = "valuename"
  description = "For valuename resources."
}

resource "google_tags_location_tag_binding" "binding" {
  parent    = "//compute.googleapis.com/projects/${google_project.project.number}/zones/us-central1-a/instances/${google_compute_instance.instance.instance_id}"
  tag_value = google_tags_tag_value.value.id
  location  = "us-central1-a"
}
```

In this case, are you wanting to get the ID for the tags present directly from the resource they're applied to instead?

**Comment by Sir-AlexD** [comment]
Thank you for your question which will allow me to clarify the problem.

The google_compute_instance resource in your example have the numeric ID in output when you create it with terraform (instance_id). This field does not necessarily have the same name depending on the resource which further complicates the situation. For the google_compute_url_map resource for example, it is map_id.

The resources I listed in Affected Resource do not have this field but only the classic ID "id" which does not work with the tag binding.

**Comment by wyardley** [comment]
Ah, I see, so it's the `parent` field you're wanting to be able to populate, not the `tag_value`?

I can confirm that
`"//compute.googleapis.com/projects/[project]/regions/{region}/subnetworks/{name}"` (or `self_link` or `id`, or mangled forms of the above) don't seem to work here, and .

And it is odd that the numeric ID is not available. Interestingly, it is available for `google_compute_network`. One thing may be that terraform uses `id` for a different identifiers, and the API returns this numeric ID as `id`, so there are some hacks in the code (custom encoders / decoders) to handle it. It's not crazy hard to do this, though would have to do it separately for each one of these resources, I think.

It would also be nice if the provider had outputs to directly include the "One Platform resource name" style name directly (usually things are either in the form of `projects/foo/xxx/name` or the `self_link` with `https://www.googleapis.com/servicename` prefixing it, but maybe that would be a bigger effort? @rileykarson @SarahFrench - I don't think there can be a provider level function to normalize / synthesize this kind of value, but magic modules could presumably have some standard way of generating them? any thoughts on if / whether there's any precedent for having some way to have some or part of this formatted that way as a convenience.

Also, do either of you know if there's a simpler way to just say "give us `id` from the API, but call it `numeric_id`", without the custom encoder / decoder? And should the numeric ID be a string or a number? Seems like it's a string for `google_compute_network`, though to me, a number might be better?

To start with, I made a PR for that example (`google_compute_subnetwork`).

**Comment by wyardley** [comment]
One other thing I observed while working on the above: the `google_compute_network` resource has the `numeric_id` attribute, but I don't think the equivalent data source does. I did not add it in my PR.

**Comment by wyardley** [comment]
I guess since there are now provider functions (albeit ones that only function with Terraform >= 1.8) (e.g., [location_from_id](https://registry.terraform.io/providers/hashicorp/google/latest/docs/functions/location_from_id)), maybe there could be one called `tag_resource_id_from_self_link` or something (I don't know what the proper name is for the above style).

However, if that were to function even in the case where the numeric ID didn't exist in the self-link or the resource, might be pretty hard to implement, since I imagine there's no trivial way to get that in a standard way?

**Comment by SarahFrench** [comment]
>Also, do either of you know if there's a simpler way to just say "give us id from the API, but call it numeric_id", without the custom encoder / decoder? And should the numeric ID be a string or a number? Seems like it's a string for google_compute_network, though to me, a number might be better?

I think what you need here is: https://googlecloudplatform.github.io/magic-modules/develop/field-reference/#api_name
