### ISSUE TITLE
google_gke_hub_feature_membership uses beta endpoints in GA provider

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#20246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

google_gke_hub_feature_membership

### Terraform Configuration

```tf
```

### Steps to reproduce

1. `terraform apply`

### Important Factoids

Promoted from beta provider to GA provider in https://github.com/GoogleCloudPlatform/magic-modules/pull/10400

It seems like there is a v1 API with the necessary functionality we can use. It would likely not change any actual functionality, but should be used for the sake of SLOs and customer expectations.

**Comment by hao-nan-li** [comment]
Here https://github.com/GoogleCloudPlatform/magic-modules/tree/main/tpgtools/api, looks like gke_hub is migrated out from DCL, not sure what happened, but I'll remove the basepath for this product in DCL endpoints.

**Comment by hao-nan-li** [comment]
Closing this as the PR actually fixed the issue. Nightly tests hitting the correct endpoint.
