### ISSUE TITLE
Failing test(s): TestAccComposerEnvironment* (User label prefix 'goog-')

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#20249]
### Impacted tests

- TestAccComposerEnvironment_update
- TestAccComposerEnvironment_withWebServerConfig

### Affected Resource(s)

- google_composer_environment

### Failure rates

- 100% since 2024-08-22

### Message(s)

```
Error: Error waiting to update Environment: Error waiting for Updating newly created Environment: Error code 3, message: Errors in: [Web server]; Error messages:
          Failed to deploy the Airflow web server. This might be a temporary issue. You can retry the operation later.
        If the issue persists, it might be caused by problems with permissions or network configuration. For more information, see https://cloud.google.com/composer/docs/troubleshooting-environment-creation
        App Engine Flexible validation error: User label prefix 'goog-' is reserved and cannot be used: goog-terraform-provisioned
          with google_composer_environment.test,
```

Version 6.0.0 introduced the `goog-terraform-provisioned` attribution label, which is added automatically to all Terraform-provisioned resources. This is causing problems with the google_composer_environment resource.

### Nightly build test history

https://hashicorp.teamcity.com/test/-3074006311885699769?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS

b/378146943

**Comment by melinath** [comment]
@SirGitsalot @rileykarson  FYI. I think we'd need the API team to allow setting this label - does that sound right?

**Comment by SirGitsalot** [comment]
Yes, if they're rejecting any label with the `goog-` prefix as that must be coming from within their API implementation. IIRC there was another service that was doing the same and we disabled for that service - @c2thorn was the person who'd remember better than me.

**Comment by c2thorn** [comment]
> Yes, if they're rejecting any label with the `goog-` prefix as that must be coming from within their API implementation. IIRC there was another service that was doing the same and we disabled for that service - @c2thorn was the person who'd remember better than me.

that was Dataplex: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/dataplex/Datascan.yaml#L19

**Comment by rlapin-pl** [comment]
The issue should already be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/12463

**Comment by melinath** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/12463/files
