### ISSUE TITLE
google_compute_region_backend_service resource is outdated - please update

### ISSUE THREAD

**Issue by Chupaka** [hashicorp/terraform-provider-google#2024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please update `google_compute_region_backend_service` resource so that it can be used for EXTERNAL balancing scheme. [API](https://cloud.google.com/compute/docs/reference/rest/v1/regionBackendServices) requires at least portName parameter, probably loadBalancingScheme.

Also, securityPolicy is useful :) It exists in google_compute_backend_service, but not in regional one...

### New or Affected Resource(s)

* google_compute_region_backend_service

**Comment by circa10a** [comment]
[v1 of the api](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) supports `EXTERNAL` load balancing scheme. @paddycarver Any way the priority on this could be bumped?

**Comment by roaks3** [comment]
Looks to be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4125
