### ISSUE TITLE
Failing test(s): TestAccDataprocCluster_withNetworkRefs

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#20254]
### Impacted tests

- TestAccDataprocCluster_withNetworkRefs

### Affected Resource(s)

- google_dataproc_cluster

### Failure rates

- 100% since 2024-10-08

### Message(s)

```
resource_dataproc_cluster_test.go:914: Step 1/1 error: Error running apply: exit status 1
        Error: Error creating Dataproc cluster: googleapi: Error 400: Subnetwork 'dproc-cluster-test-rwq4mmc6b0-net' does not support Private Google Access which is required for Dataproc clusters when 'internal_ip_only' is set to 'true'. Enable Private Google Access on subnetwork 'dproc-cluster-test-rwq4mmc6b0-net' or set 'internal_ip_only' to 'false'., badRequest
          with google_dataproc_cluster.with_net_ref_by_name,
```

This was previously obscured by https://github.com/hashicorp/terraform-provider-google/issues/19424, so I can't pin down when it actually started failing.

### Nightly build test history

https://hashicorp.teamcity.com/test/6295589433850290566?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/378154034

**Comment by SarahFrench** [comment]
The test could also benefit from updating resource names to be sweepable, i.e. `tf-test-dproc-`

**Comment by surnaik** [comment]
This is an expected failure. We need to either set `internal_ip_only` to `false` or enable Private Google Access on the subnetwork.
