### ISSUE TITLE
Failing test(s): TestAccPubsubSubscriptionBigQuery_serviceAccount

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#20274]
### Impacted tests

- TestAccPubsubSubscriptionBigQuery_serviceAccount

### Affected Resource(s)

- google_pubsub_subscription

### Failure rates

- \>50% since 2024-10-26

### Message(s)

```
resource_pubsub_subscription_test.go:250: Step 3/6 error: Error running apply: exit status 1
        Error: Provider produced inconsistent result after apply
        When applying changes to google_project_iam_member.editor, provider
        "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected
        new value: Root object was present, but now absent.
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

### Nightly build test history

https://hashicorp.teamcity.com/test/7624098642910320430?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A255996%29%2Cid%3A2000000043

b/378169766

**Comment by wyardley** [comment]
Maybe also related to https://github.com/GoogleCloudPlatform/magic-modules/pull/12095 (like #20262)
Sorry if I made it worse 😞

**Comment by wyardley** [comment]
I think this one should be good now 🤞 - maybe confirm after a few days of nightly runs?

**Comment by wyardley** [comment]
Is this one looking better now?

**Comment by melinath** [comment]
It's been passing but I'd want to let it go a few more days before saying it's resolved.
