### ISSUE TITLE
`google_container_cluster` fails with an API error on 6.11.0

### ISSUE THREAD

**Issue by SphericalKat** [hashicorp/terraform-provider-google#20301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.4.4
on x86_64
+ provider registry.terraform.io/hashicorp/google v6.11.0
+ provider registry.terraform.io/hashicorp/google-beta v6.11.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration

```tf
resource "google_compute_network" "vpc" {
  name                    = "tokyo"
  description             = "tokyo"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnet" {
  name                     = "tokyo"
  ip_cidr_range            = "10.0.0.0/16"
  region                   = "asia-northeast1"
  private_ip_google_access = true
  network                  = google_compute_network.vpc.id
}

resource "google_container_cluster" "cluster" {
  name             = "gke-cluster"
  location         = "asia-northeast1"
  enable_autopilot = true

  network    = google_compute_network.vpc.id
  subnetwork = google_compute_subnetwork.subnet.id

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = true

    master_ipv4_cidr_block = "10.5.0.0/28"
  }

  ip_allocation_policy {
    cluster_ipv4_cidr_block  = "10.6.0.0/16"
    services_ipv4_cidr_block = "10.7.0.0/16"
    stack_type               = "IPV4"
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "10.0.0.0/8"
      display_name = "private"
    }

    cidr_blocks {
      cidr_block   = "0.0.0.0/0"
      display_name = "all"
    }
  }

  binary_authorization {
    evaluation_mode = "DISABLED"
  }

  addons_config {
    horizontal_pod_autoscaling {
      disabled = false
    }
    http_load_balancing {
      disabled = false
    }
  }

  maintenance_policy {
    recurring_window {
      start_time = "2021-04-06T15:00:00Z"
      end_time   = "2021-04-06T21:00:00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU"
    }
  }

  release_channel {
    channel = "REGULAR"
  }
}
```

### Expected Behavior

The apply should have passed, because there is no change to the resource.

### Actual Behavior

The `terraform apply` fails with the following API error:
```
╷
│ Error: googleapi: Error 400: Must specify a field to update.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0x284c6237e333a9c"
│   }
│ ]
│ , badRequest
│ 
│   with google_container_cluster.cluster,
│   on kubernetes.tf line 1, in resource "google_container_cluster" "cluster":
│    1: resource "google_container_cluster" "cluster" {
│ 
╵
```
Note that the exact same configuration works when we pin the provider version to `6.10.0`

### Steps to reproduce

1. Use version `6.11.0` of the `google` provider
2. `terraform apply`

b/378725361

**Comment by rorynickolls-skyral** [comment]
It looks like this may have been introduced by https://github.com/hashicorp/terraform-provider-google/pull/20105 in the latest release.

**Comment by melinath** [comment]
@SphericalKat can you share a plan? It would be helpful to see what fields Terraform thinks need to be updated, since there were a few different changes to this resource in this release.

**Comment by melinath** [comment]
I'm not able to reproduce this issue with the supplied config - if I apply on 6.10.0 and then upgrade to 6.11.0, no changes are detected. There must be some specific condition that triggers this error.

**Comment by ferrastas** [comment]
I'm also facing the same issue, I do not have the raw text as we use TFE, but here's a screenshot of the changes
<img width="940" alt="Screenshot 2024-11-12 at 18 33 19" src="https://github.com/user-attachments/assets/0c96d5a1-89da-40e8-95e0-363e1935b56e">

**Comment by josephweinerfulfilld** [comment]
Facing exactly the same issue as @ferrastas and @melinath .  This is a blocking issue for us when using `6.11.0`.  We additionally were not pinning to using an exact version.  Looking to workaround by using a previous version.

**Comment by melinath** [comment]
@ferrastas @josephweinerfulfilld @SphericalKat is there any chance y'all had previously been managing the user managed encryption keys feature outside of Terraform? (It doesn't look like it, since the values are all empty, but possibly setting it up and removing it later would change what the API returns vs. never setting it in the first place.)

**Comment by melinath** [comment]
I'm able to reproduce the error when trying to update the fields in place, but I'm not able to reproduce the behavior of having a diff on the field despite making no changes.

There's a note in the related tests that these fields can only be set on create, but there is also update support present, so I'm not sure if that note might be outdated. @ahmedtd FYI as the PR author in case you can provide insight.

We could "fix" the update issue by marking the field as immutable (ForceNew) but that would trigger delete & recreate for anyone experiencing the diff behavior.

**Comment by ryanfulfilld** [comment]
@melinath (replying for @josephweinerfulfilld): We have not been using the user managed encryption keys outside of Terraform. We ran into this error in a newly set-up environment, so I'm pretty confident that there shouldn't have been any manual configuration relics.

**Comment by ferrastas** [comment]
@melinath not possible, we faced this issue on an almost fresh new project. If it helps, it was created using provider version 6.10, this same plan was working yesterday, just before the 6.11 release. In fact, pinning to 6.10 the plan is not showing changes on the cluster resource.

**Comment by ahmedtd** [comment]
The current behavior of these fields is:

* For each field, you have to set it or not during cluster create.
* If the field is set at cluster create, you can never update the field to be unset (though you can update the value).
* If the field is unset at cluster create, you can never set it.

In the future, we are going to support setting / unsetting these fields, but it will never be truly freely settable, since there needs to be a CA root rotation operation in order to transition from set to unset or vice-versa.

**Comment by melinath** [comment]
@ferrastas @josephweinerfulfilld @SphericalKat @ryanfulfilld thanks! Is there any chance that one of you could share the API response you're getting for the resource's state refresh? You can get these logged by running `TF_LOG=DEBUG terraform apply`. Please feel free to redact anything except the user managed keys portion (if present).

**Comment by melinath** [comment]
Looks like the update functionality doesn't currently work as expected so moving forward with removing update support & marking the field as immutable for now.

**Comment by melinath** [comment]
Hey all - we've released 6.11.1, which _should_ resolve this issue; however, we still haven't been able to _reproduce_ it. Please try out the new release and respond here to let me know whether it fixed the problem. If not, please share an API response as described above.

**Comment by joemiller** [comment]
@melinath I ran a `plan` on one of the clusters exhibiting this behavior and the plan for 6.11.1 was "no changes" whereas on 6.11.0 it wanted to update the `user_managed_keys_config` field. Seems good.

**Comment by SphericalKat** [comment]
@melinath thanks for the quick fix and sorry about my slow response, it was nighttime here :P

I'll check out 6.11.1 and see if the problem still occurs
