### ISSUE TITLE
Add psc_Auto_Connections in google_sql_database_instance.psc_config

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#20343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add psc_Auto_Connections in google_sql_database_instance.psc_config

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf 
psc_config {
  psc_enabled = true
  allowed_consumer_projects = ["allowed-consumer-project-name"]
  pscAutoConnections {
     consumer_Project = ""
     consumer_Network = ""
  }
}
```

### References

https://cloud.google.com/sql/docs/postgres/configure-private-service-connect#create-cloud-sql-instance-psc-enabled-2

b/379652027

**Comment by BBBmau** [comment]
After reviewing, I notice that the API Reference does not contain `pscAutoConnections` however I do see that it's present in the docs mentioning the use of `psc_auto_connections`

Relevant Docs where it's referenced: https://cloud.google.com/sql/docs/postgres/configure-private-service-connect#create-cloud-sql-instance-psc-enabled-2

API Reference where it's not mentioned: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances#PscConfig

Even though it's not in the API Reference it is still most likely supported.

**Comment by Rei-Suzuki1729** [comment]
Isn't this issue resolved in the PR here?

#20307
