### ISSUE TITLE
Add enterprise_config field to container cluster resource

### ISSUE THREAD

**Issue by bradhoekstra** [hashicorp/terraform-provider-google#20355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add enterprise_config field to container cluster resource so GKE users can choose GKE Enterprise tier for their clusters.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf 
```

b/379652237

**Comment by BBBmau** [comment]
API Reference can be found here: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#enterpriseconfig
