### ISSUE TITLE
[documentation] Incorrect example attributes for google_access_context_manager_service_perimeter_dry_run_[in|e]gress_policy

### ISSUE THREAD

**Issue by anilkumarmyla** [hashicorp/terraform-provider-google#20382]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.8
on <architecture>
+ provider registry.terraform.io/hashicorp/google v6.12.0
+ provider registry.terraform.io/hashicorp/google-beta v6.12.0

### Affected Resource(s)

google_access_context_manager_service_perimeter_dry_run_ingress_policy
google_access_context_manager_service_perimeter_dry_run_egress_policy
google_access_context_manager_service_perimeter_egress_policy
google_access_context_manager_service_perimeter_ingress_policy

### Terraform Configuration

```tf
```

### Expected Behavior

The example usages of these resources are inaccurate and they should be as follows

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_dry_run_egress_policy
In google_access_context_manager_service_perimeter_dry_run_egress_policy, in perimeter definition 
- lifecycle -> ignore_changes should have `[spec[0].egress_policies]`

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_dry_run_ingress_policy
In google_access_context_manager_service_perimeter_dry_run_ingress_policy, in perimeter defition
- status should be spec since we're dealing with a dry_run perimeter
- lifecycle -> ignore_changes should have `[spec[0].ingress_policies]`

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_egress_policy
In google_access_context_manager_service_perimeter_egress_policy, in perimeter defition
- lifecycle -> ignore_changes should have `[status[0].egress_policies]`

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_ingress_policy
In google_access_context_manager_service_perimeter_ingress_policy, in perimeter defition
- lifecycle -> ignore_changes should have `[status[0].ingress_policies]`

### Steps to reproduce

1. `terraform apply`

b/380052088

**Comment by Charlesleonius** [comment]
I already fixed this the new version just hasn't been released to update the docs: https://github.com/hashicorp/terraform-provider-google/pull/20439

**Comment by Charlesleonius** [comment]
@melinath Can we please close this

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/12372

**Comment by anilkumarmyla** [comment]
> `status` should be `spec` for google_access_context_manager_service_perimeter_dry_run_ingress_policy

This is missed in the PR
