### ISSUE TITLE
datastream_stream should allow for GTID based replication

### ISSUE THREAD

**Issue by PaulRudin** [hashicorp/terraform-provider-google#20383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Datastream streams can be created using GTID based replication: see https://cloud.google.com/datastream/docs/sources-mysql#gtid, but this is cannot be configured via the terraform provider

### New or Affected Resource(s)

* google_datastream_stream

### Potential Terraform Configuration

```tf 
resource "google_datastream_stream" "default" {
    display_name = "SQL Server to BigQuery"
    location     = "us-central1"
    stream_id    = "stream"

    source_config {
        source_connection_profile = google_datastream_connection_profile.source.id
        sql_server_source_config {
            include_objects {
                schemas {
                    schema = "schema"
                    tables {
                        table = "table"
                    }
                }
            }
           cdc_method = "gtid"
        }
    }

    destination_config { ...  }

    backfill_none {}
}
```

b/380890449

**Comment by melinath** [comment]
It looks like mysql source config has a field called `gtid` that might be this? https://cloud.google.com/datastream/docs/reference/rest/v1/projects.locations.streams#gtid

Don't see anything for SQL server though. Perhaps this is a recently-added feature and the docs are outdated. Likely there will be a similar field on all source configs.

**Comment by PaulRudin** [comment]
> Note from triage: It looks like mysql source config has a field called `gtid` that might be this? https://cloud.google.com/datastream/docs/reference/rest/v1/projects.locations.streams#gtid
> 
> Don't see anything for SQL server though. Perhaps this is a recently-added feature and the docs are outdated. Likely there will be a similar field on all source configs. We should support all of them.

Yeah, actually I meant to refer to MySQL not SQL server in my example config - I just copied the wrong thing. I'm not sure all the cloud sql variants support this.
