### ISSUE TITLE
google_bigquery_data_transfer_config owner field

### ISSUE THREAD

**Issue by lord-skinner** [hashicorp/terraform-provider-google#20413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

I can set the service_account_name, but I need to be able to set the owner to a group so the users who depend on the scheduled query can get notified if there are failures. I need to be able to set these discreetly and use a google group as the owner while running as a Service Account. 

### New or Affected Resource(s)

google_bigquery_data_transfer_config

### Potential Terraform Configuration

```tf 
resource "google_bigquery_data_transfer_config" "scheduled_query_name" {
  data_refresh_window_days  = 0
  data_source_id            = "scheduled_query"
  destination_dataset_id    = "dataset"
  disabled                  = false
  display_name              = "my fancy scheduled query"
  location                  = "us"
  notification_pubsub_topic = null
  params = {
    destination_table_name_template = "example"
    query                           = "select * from `schema.table`"
    write_disposition               = "WRITE_TRUNCATE"
  }
  project              = "project"
  schedule             = "every 1 hours"
  service_account_name = "bq-sch-query-sales@project.iam.gserviceaccount.com"
  owner                = "group@domain.com"
  email_preferences {
    enable_failure_email = true
  }
}

```

b/380890664

**Comment by melinath** [comment]
Note from triage: It looks like the API doesn't currently support doing this: https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs

There's an `ownerInfo` field but it's output-only.

Support would need to be added for this at the API level before we could add it into the providers.

**Comment by lord-skinner** [comment]
@melinath Thanks for the info. Do I need to take action to get support for this added to the API?

**Comment by melinath** [comment]
This has been forwarded to engineering for consideration. There's no particular action you need to take. If you're working with a Google Technical Account Manager or Customer Engineer you can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

**Comment by melinath** [comment]
Per @wj-chen's comment, closing this ticket as resolved. Thanks for reaching out!
