### ISSUE TITLE
storagetransfer: GCS path cannot be computed field as it is user provided

### ISSUE THREAD

**Issue by gurusai-voleti** [hashicorp/terraform-provider-google#20421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

google_storage_transfer

### Terraform Configuration

```tf
resource "google_storage_transfer_job" "transfer_job" {
    name        = "transferJobs/%s"
    description = "%s"
    project     = "%s"
  
    transfer_spec {
      gcs_data_source {
        bucket_name = google_storage_bucket.data_source.name
        path  = "foo/"
      }
      gcs_data_sink {
        bucket_name = google_storage_bucket.data_sink.name
        path  = "/"
      }
    }
}
```

### Expected Behavior

Path is a user provided field

### Actual Behavior

Path cannot be computed field and cannot be started with "/" ref https://cloud.google.com/storage-transfer/docs/reference/rest/v1/GcsData

### Steps to reproduce

1. `terraform apply`

**Comment by ggtisc** [comment]
Hi @gurusai-voleti!

After running a `terraform apply` with the shared code everything was successful without errors. Is this a bug report or an enhancement proposal?

Could you be more specific about what you are looking for with the `path` argument and if it is for both or just for `gcs_data_source` or `gcs_data_sink`?

What do you mean when you are saying `Path cannot be computed field`?

**Comment by gurusai-voleti** [comment]
> Hi @gurusai-voleti!
> 
> After running a `terraform apply` with the shared code everything was successful without errors. Is this a bug report or an enhancement proposal?
> 
> Could you be more specific about what you are looking for with the `path` argument and if it is for both or just for `gcs_data_source` or `gcs_data_sink`?
> 
> What do you mean when you are saying `Path cannot be computed field`?

this is a bug report, this is for both `gcs_data_source` and `gcs_data_sink`

path is a field which captures input from the user and copies/sink data from source to destination (sink), this cannot be a computed field, computed field means after the resource is created on the provider then it is received and stored in tf state file this is a field to capture input from user

**Comment by ggtisc** [comment]
I made a new try with the following code and again everything was successful without errors and all the information included `gcs_data_source` and `gcs_data_sink` were saved correctly in the `tfstate` file. I suggest you compare and review your code to check if everything is ok in your environment.

```
data "google_storage_transfer_project_service_account" "stp_sa_20421" {
  project = "my-project"
}

resource "google_storage_bucket" "s3_bucket_20421" {
  name          = "s3_bucket_20421"
  storage_class = "NEARLINE"
  project       = "my-project"
  location      = "US"
}

resource "google_storage_bucket_iam_member" "s3_bucket_iam_member_20421" {
  bucket     = google_storage_bucket.s3_bucket_20421.name
  role       = "roles/storage.admin"
  member     = "serviceAccount:${data.google_storage_transfer_project_service_account.stp_sa_20421.email}"
  depends_on = [google_storage_bucket.s3_bucket_20421]
}

resource "google_storage_transfer_job" "transfer_job_20421" {
    name        = "transferJobs/transfer-job-20421"
    description = "something"
    project     = "my-project"
  
    transfer_spec {
      gcs_data_source {
        bucket_name = google_storage_bucket.s3_bucket_20421.name
        path  = "foo/"
      }
      gcs_data_sink {
        bucket_name = google_storage_bucket.s3_bucket_20421.name
        path  = "/"
      }
    }
}
```

If after this you continue having issues share with us your full code as in the above example to make a new try and compare the differences you have.

**Comment by gurusai-voleti** [comment]
> I made a new try with the following code and again everything was successful without errors and all the information included `gcs_data_source` and `gcs_data_sink` were saved correctly in the `tfstate` file. I suggest you compare and review your code to check if everything is ok in your environment.
> 
> ```
> data "google_storage_transfer_project_service_account" "stp_sa_20421" {
>   project = "my-project"
> }
> 
> resource "google_storage_bucket" "s3_bucket_20421" {
>   name          = "s3_bucket_20421"
>   storage_class = "NEARLINE"
>   project       = "my-project"
>   location      = "US"
> }
> 
> resource "google_storage_bucket_iam_member" "s3_bucket_iam_member_20421" {
>   bucket     = google_storage_bucket.s3_bucket_20421.name
>   role       = "roles/storage.admin"
>   member     = "serviceAccount:${data.google_storage_transfer_project_service_account.stp_sa_20421.email}"
>   depends_on = [google_storage_bucket.s3_bucket_20421]
> }
> 
> resource "google_storage_transfer_job" "transfer_job_20421" {
>     name        = "transferJobs/transfer-job-20421"
>     description = "something"
>     project     = "my-project"
>   
>     transfer_spec {
>       gcs_data_source {
>         bucket_name = google_storage_bucket.s3_bucket_20421.name
>         path  = "foo/"
>       }
>       gcs_data_sink {
>         bucket_name = google_storage_bucket.s3_bucket_20421.name
>         path  = "/"
>       }
>     }
> }
> ```
> 
> If after this you continue having issues share with us your full code as in the above example to make a new try and compare the differences you have.

GCS path never starts with /, it's a prefix  path for storage bucket object(s),

**Comment by ggtisc** [comment]
Hi @gurusai-voleti

This is not generating an error, rather it is something that should not be allowed. Please confirm us if this is correct.

Although reviewing the link that you share with us it does not specify that it cannot be done, but rather it is a warning as it is written: `it should generally not begin with a '/'`. To take it into consideration only

**Comment by gurusai-voleti** [comment]
> Hi @gurusai-voleti
> 
> This is not generating an error, rather it is something that should not be allowed. Please confirm us if this is correct.
> 
> Although reviewing the link that you share with us it does not specify that it cannot be done, but rather it is a warning as it is written: `it should generally not begin with a '/'`. To take it into consideration only

in gcs path if we keep / the  transfer job will not run/work as expected, it should be either empty or some path which ends /, cannot start with /

there is already a bug reported by a user on this https://github.com/hashicorp/terraform-provider-google/issues/13673

and path cannot be an computed field its an user provided field

**Comment by ggtisc** [comment]
Okay Thank you, I'm going to close this issue as duplicated to continue with the other one
