### ISSUE TITLE
For Google Cloud Pub/Sub subscription, Retry policy defaulted to "retry with exponential backoff" with 6.8.0

### ISSUE THREAD

**Issue by MadhuSurya-Git** [hashicorp/terraform-provider-google#20445]
### Community Note

For Google Cloud Pub/Sub subscription, Retry policy defaulted to "retry with exponential backoff" with latest provider

Problem:

The latest version of the Terraform Google Cloud provider has introduced a change in the default retry policy for Pub/Sub subscriptions. Previously, the default was "retry immediately," but now it defaults to "retry with exponential backoff" with a default backoff configuration (retry_policy_time = {minimum_backoff = "10s" maximum_backoff = "600s"}). This unexpected behavior is causing issues for our application teams, who require the "retry immediately" policy.

When we hardcode version 6.0 of the Google Cloud provider in our latest terraform module, it automatically applied the "retry immediately" policy (no backoff was provided), it has worked as expected.
Currently we have provided this workaround for most of our application teams.
But we don't recommend to hardcode Google Cloud provider version in our modules as per our process standards.

Impact:

The default exponential backoff policy is causing delays in message delivery, impacting the performance and responsiveness of our applications.

Requirement:

We need to ensure that the default retry policy for Pub/Sub subscriptions reverts to "retry immediately" when using the latest version of the Terraform Google Cloud provider.
Our Application teams requirement is "retry immediately"

Please resolve this bug immediately

### Terraform Version & Provider Version(s)

Terraform v1.5.7

terraform {
  backend "azurerm" {}
}

provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google" {
  credentials = file(var.gcp_credential_path)
  alias       = "impersonated"
}

data "google_service_account_access_token" "sa" {
  provider               = google.impersonated
  target_service_account = "sa-${substr(var.project_id, 0, min(length(var.project_id), 27))}@${var.project_id}.iam.gserviceaccount.com"
  lifetime               = "3600s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
  ]
}

### Affected Resource(s)

Pub/Sub subscription

### Terraform Configuration

terraform {
  backend "azurerm" {}
}

provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google" {
  credentials = file(var.gcp_credential_path)
  alias       = "impersonated"
}

data "google_service_account_access_token" "sa" {
  provider               = google.impersonated
  target_service_account = "sa-${substr(var.project_id, 0, min(length(var.project_id), 27))}@${var.project_id}.iam.gserviceaccount.com"
  lifetime               = "3600s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
  ]
}

module "gcp_pubsub" {
  source                      = "acnciotfregistry.accenture.com/accenture-cio/pubsub/google"
  version                     = "2.1.0"
  project_id                  = var.project_id
  topic_name                  = "NewTopic-us-east1"
  subscription_name           = "NewSubscription-us-east1"
  intended_event_type         = "Application"
  resources_to_create         = "BOTH"
  delivery_type               = "Push"
  endpoint_url                = "https://www.testendpointurl.com"
  push_auth_service_account   = "sa-103879-big-data@${var.project_id}.iam.gserviceaccount.com"
  labels = {
    examplenum = "gcp_pubsub_test"
    creates    = "subscription"
  }
}

### Debug Output

NA

### Expected Behavior

retry policy for Pub/Sub subscriptions should set to "retry immediately"

### Actual Behavior

retry policy for Pub/Sub subscriptions  set to  "retry with exponential backoff" with a default backoff configuration (retry_policy_time = {minimum_backoff = "10s" maximum_backoff = "600s"}).

### Steps to reproduce

1. `terraform apply`

### Important Factoids

When we hardcode provider version 6.0 (highlighted in bold) in our latest module, it is setting retry policy for Pub/Sub subscriptions to "retry immediately". 
Our requirement is without hardcoding provider version we need retry policy  to set as "retry immediately"
Please fix this issue.
-----------------------------------
terraform {
  backend "azurerm" {}
}

provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google" {
  credentials = file(var.gcp_credential_path)
  alias       = "impersonated"
}

data "google_service_account_access_token" "sa" {
  provider               = "google.impersonated"
  target_service_account = "sa-${substr(var.project_id, 0, min(length(var.project_id), 27))}@${var.project_id}.iam.gserviceaccount.com"
  lifetime               = "3600s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
  ]
}

**terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.0.0"
    }
  }
}**

### References

NA

~b/380481675~

b/381307966

**Comment by ggtisc** [comment]
This looks like an enhancement proposal for `google_pubsub_topic` `retry_policy_time`

**Comment by MadhuSurya-Git** [comment]
> This looks like an enhancement proposal for `google_pubsub_topic` `retry_policy_time`

Hi @ggtisc, 
For earlier provider versions retry policy was defaulted to set as "retry immediately". 
Now it is defaulted to "retry with exponential backoff". When provisioning or upgrading the PUB/SUB module with latest versions.
We need changes in google provider for pub/sub subscription retry policy to set as "retry immediately" - Requesting to revert back the changes for retry policy.

**Comment by melinath** [comment]
@MadhuSurya-Git I don't see any changes to `google_pubsub_subscription` in the latest release. What is the first version that has this behavior? There was a change in 6.7.0 that fixed a [permadiff bug](https://github.com/hashicorp/terraform-provider-google/issues/18016) where retry_policy was not getting sent to the API if it was an empty block in the configuration. Possibly what you're seeing is somehow a side effect of that change, if 6.7.0 is the first version where you see the issue?

cc @anavada FYI

**Comment by MadhuSurya-Git** [comment]
> @MadhuSurya-Git I don't see any changes to `google_pubsub_subscription` in the latest release. What is the first version that has this behavior for you? There was a change in 6.7.0 that fixed a [permadiff bug](https://github.com/hashicorp/terraform-provider-google/issues/18016) where retry_policy was not getting sent to the API if it was an empty block in the configuration. Possibly what you're seeing is somehow a side effect of that change, if 6.7.0 is the first version where you see the issue?
> 
> cc @anavada FYI

Hey @melinath @ggtisc / team,
**This issue started from 6.8.0**.
I tested hardcoding provider version from 6.0.0 to latest
till 6.7.0 it worked fine (Retry policy has set to Retry Immediately)
from 6.8.0 issue started (Retry policy has set to Retry after exponential backoff delay)
Please help in fixing this issue, please take necessary steps further to fix this issue or please guide us the remediation steps if any. We are hoping for the fix. Thank you!

**Comment by trodge** [comment]
Through testing I found that the change in behavior happens between 6.6.0 and 6.7.0. In 6.6.0 an empty or unspecified retry policy does not get sent to the API, but in 6.7.0 it does. The API response contains a non-empty retry policy. Therefore I think this is an API issue.

**Comment by melinath** [comment]
I can see this behavior in our nightly tests as well.

It looks like this isn't noticeable on our end because the subfields are both optional + computed, so they accept and persist API-side values if the parent field is set and empty. 

From our nightly tests, it looks like the behavior of the resource is fine if the retryPolicy is unset; this is only an issue if the field is set to an empty block.

I'm not sure we actually have a clear best practice for what the behavior _should_ be in this case. We definitely accidentally changed the default behavior of the resource, and the new behavior is ambiguous in terms of whether it's "more correct".

Marking for forwarding.

**Comment by melinath** [comment]
Just to state it explicitly, I don't think this is an API issue.

**Comment by MadhuSurya-Git** [comment]
Hello All,
We have fixed the issue in our code level. Thank you!

**Comment by melinath** [comment]
After some additional looking into this and thinking about it, we're closing this issue. Although the change in behavior was not intended, it is more correct / in line with the rest of the provider as it stands today, and it sounds like there is a code workaround as well.

@MadhuSurya-Git is there any chance you might be willing to share the workaround here?

**Comment by melinath** [comment]
I've updated the release notes. It looks like the new behavior matches what is in the [documentation for the Terraform field](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#retry_policy-1) so there's nothing to change there.

**Comment by MadhuSurya-Git** [comment]
@melinath / @ggtisc / All

Thank you for your support, please find workaround.:

Replaced the retry policy in the code with a dynamic "retry_policy" block.
=====================================
  retry_policy {
    minimum_backoff = var.retry_policy_time.minimum_backoff
    maximum_backoff = var.retry_policy_time.maximum_backoff
}
=====================================
  dynamic "retry_policy" {
    for_each = (var.retry_policy_time.minimum_backoff != "" && var.retry_policy_time.maximum_backoff != "") ? [1] : []
    content {
      minimum_backoff = var.retry_policy_time.minimum_backoff
      maximum_backoff = var.retry_policy_time.maximum_backoff
    }
  }
=====================================
pub/sub subscription retry policy is setting as "retry immediately" now, no matter the provider version.
