### ISSUE TITLE
missing "healthcare_fhir" industry vertical in google_discovery_engine_search_engine

### ISSUE THREAD

**Issue by leoskyrocker** [hashicorp/terraform-provider-google#20467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

#### Issue Context

The 'healthcare_fhir' value is currently absent in the industry vertical property of `google_discovery_engine_search_engine`. While users can create a search engine for the 'healthcare_fhir' vertical through the UI, this functionality is not available when provisioning infrastructure as code with the Terraform Google provider.

Additionally, there is a check in place that ensures the industry vertical in `google_discovery_engine_search_engine` matches the value in `google_discovery_engine_data_store`. This is problematic because `google_discovery_engine_data_store` already supports the 'healthcare_fhir' value, but it is not reflected in the search engine configuration.

#### Proposed Fix
Add the `healthcare_fhir` value to the industry vertical property in `google_discovery_engine_search_engine`.

### New or Affected Resource(s)

* google_discovery_engine_search_engine

### Potential Terraform Configuration

```tf 
```

b/380879944

**Comment by melinath** [comment]
Note from triage: If this enum is likely to change regularly (once a year or more), it may make sense to convert it from an enum field to a string field and link to the API docs in the field description for the allowed values. This would allow better forwards-compatibility.
