### ISSUE TITLE
`google_storage_bucket_object` does not predict changes to generated attributes

### ISSUE THREAD

**Issue by bendiknesbo** [hashicorp/terraform-provider-google#20552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v6.12.0

### Affected Resource(s)

google_storage_bucket_object

### Terraform Configuration

Apply this configuration first:
```tf
resource "google_storage_bucket" "my_bucket" {
  name          = "my-bucket"
  location      = "EU"
  storage_class = "STANDARD"

  uniform_bucket_level_access = true
}

resource "google_storage_bucket_object" "js" {
  name         = "index.js"
  content      = "some content"
  content_type = "application/javascript"
  bucket       = google_storage_bucket.my_bucket.id
}


output "js_url" {
  value = "https://storage.googleapis.com/${google_storage_bucket.my_bucket.name}/${google_storage_bucket_object.js.name}?filehash=${google_storage_bucket_object.js.crc32c}"
}
```

And then make this change, and make a plan
```tf
resource "google_storage_bucket" "my_bucket" {
  name          = "my-bucket"
  location      = "EU"
  storage_class = "STANDARD"

  uniform_bucket_level_access = true
}

resource "google_storage_bucket_object" "js" {
  name         = "index.js"
  content      = "some OTHER content"
  content_type = "application/javascript"
  bucket       = google_storage_bucket.my_bucket.id
}


output "js_url" {
  value = "https://storage.googleapis.com/${google_storage_bucket.my_bucket.name}/${google_storage_bucket_object.js.name}?filehash=${google_storage_bucket_object.js.crc32c}"
}
```

### Expected Behavior

The plan should indicate that changing the content will trigger a change in the "crc32c", "md5hash" and "generation" properties.
```shell
  # google_storage_bucket_object.js will be updated in-place
  ~ resource "google_storage_bucket_object" "js" {
      ~ content          = (sensitive value)
      ~ crc32c           = (known after apply)
      ~ detect_md5hash   = "BDBAwxp8hhzqennR52HkHg==" -> "different hash"
      + generation       = (known after apply)
        id               = "my-bucket-index.js"
      + md5hash          = (known after apply)
        name             = "index.js"
        # (9 unchanged attributes hidden)
    }
```

### Actual Behavior

```shell
  # google_storage_bucket_object.js will be updated in-place
  ~ resource "google_storage_bucket_object" "js" {
      ~ content          = (sensitive value)
      ~ detect_md5hash   = "BDBAwxp8hhzqennR52HkHg==" -> "different hash"
        id               = "my-bucket-index.js"
        name             = "index.js"
        # (12 unchanged attributes hidden)
    }
    ```

### Steps to reproduce

1. `terraform apply` the first configuration
2. Update to the second configuration (update `google_storage_bucket_object.js.content`)
3. `terraform plan`

### Important Factoids

Adding the following datasource and changing the `output "js_url"` to read the filehash from the datasource instead of the resource, will work as a workaround, as by the time the datasource is fetched, the new hash is calculated:

```tf
data "google_storage_bucket_object" "js_post_apply" {
  name   = google_storage_bucket_object.js.name
  bucket = google_storage_bucket_object.js.bucket

  depends_on = [google_storage_bucket_object.js] # Ensures the data resource refreshes after the resource is applied
}
```

The bug is also present if `google_storage_bucket_object.source` is used instead of `google_storage_bucket_object.content`.

b/382134480

**Comment by NickElliot** [comment]
Issue has been present since `5.35.0` with the resolution of https://github.com/hashicorp/terraform-provider-google/issues/10488 via https://github.com/GoogleCloudPlatform/magic-modules/pull/10038. Reproducible in all versions following then.

In the way Storage Bucket is configured, it appears Terraform can't identify that the computed attributes will change alongside the update to the `(sensitive)` `content` field and the manually set `"different hash"`on `detect_md5hash`.

A customize diff on the resource that applies [`SetNewComputed`](https://github.com/hashicorp/terraform-plugin-sdk/blob/v1.17.2/helper/schema/resource_diff.go#L301) for fields if `content` is updated should solve the problem
