### ISSUE TITLE
maxUsableWorkstations parameter should update in place in google_workstations_workstation_config resource

### ISSUE THREAD

**Issue by Gwim** [hashicorp/terraform-provider-google#20555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

The parameter maxUsableWorkstations has been properly implemented, but every nested resource must be destroyed before applying the parameter to the configuration. 
It would be easier to update in place, instead of deleting every nested ressource to apply the parameter.

### New or Affected Resource(s)

google_workstations_workstation_config

### Potential Terraform Configuration

```tf resource "google_workstations_workstation_config" "default" {
  provider                        = google-beta
  workstation_config_id  = "workstation-config"
  workstation_cluster_id = google_workstations_workstation_cluster.default.workstation_cluster_id
  location                        = "us-central1"

  max_usable_workstations = 2

  host {
    gce_instance {
      machine_type                        = "e2-standard-4"
      boot_disk_size_gb                 = 35
      disable_public_ip_addresses = true
      enableNestedVirtualization  = true
      shielded_instance_config {
        enable_secure_boot = true
        enable_vtpm            = true
      }
    }
  }

  persistent_directories {
    mount_path = "/home"
    gce_pd {
      size_gb                = 200
      source_snapshot = "projects/{{project}}/global/snapshots/{{name}}"
      reclaim_policy     = "DELETE"
    }
  }
}

```

b/383132984

**Comment by mickaelmallet31** [comment]
+1 for this feature: on my compagny, we've got **685** running workstations.
Destroying all of them to deploy this new **maxUsableWorkstations** feature has an impact on developer productivity.

Please get this ticket proposal be applied ASAP
Thanks for your support

**Comment by esu** [comment]
Thanks for this report! I'm from the Cloud Workstations team, and we are planning to review and implement this. We will have more information in the next 2-3 weeks.

**Comment by esu** [comment]
@mickaelmallet31 or any others -- would you be able to share the output of your Terraform plan that is showing a diff and causing the child resources to be recreated? In our testing, this parameter already updates in-place some of the time, so we're curious if there is a separate diff that's being picked up.

**Comment by Gwim** [comment]
Hello, it seems we had issues not related to the parameter itself but some modifications on configs with nested resources. We manage to set the parameter fine with nested resources so the ticket can be close.
Thanks for your time,

**Comment by Gwim** [comment]
Hello, it seems we had issues not related to the parameter itself but some modifications on configs with nested resources. We manage to set the parameter fine with nested resources so the ticket can be close.
Thanks for your time,
