### ISSUE TITLE
eTag mismatch when updating google_access_context_manager_service_perimeter

### ISSUE THREAD

**Issue by anilkumarmyla** [hashicorp/terraform-provider-google#20695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.6.3
on <architecture>
+ provider registry.terraform.io/hashicorp/google v6.13.0
+ provider registry.terraform.io/hashicorp/google-beta v6.13.0

### Affected Resource(s)

google_access_context_manager_service_perimeter

### Terraform Configuration

```tf
```

### Expected Behavior

No errors

### Actual Behavior

Whenever there is a change in the service perimeter, the deployment first fails with
`Error: Error updating ServicePerimeter "xxxx": googleapi: Error 400: The eTag provided 'f1611619354d94bb' does not match the eTag of the current version of the Access Policy, which is '48141e5ffd219c96'. The operation will not be performed.`

However on the next retry, the deployment succeeds without any error

### Steps to reproduce

1. `terraform apply`

### References

Seems like eTag support was recently added to ACM in 6.13.0 which might be directly related
https://github.com/hashicorp/terraform-provider-google/pull/20455

**Comment by shuyama1** [comment]
Sorry, we're aware that this may cause issues, so the feature has been reverted in https://github.com/hashicorp/terraform-provider-google/pull/20691
