### ISSUE TITLE
Restore SQL instance from snapshot

### ISSUE THREAD

**Issue by aclowkey** [hashicorp/terraform-provider-google#2446]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud provisions automatic backups for SQL instances, and allows to restore from those backups. In order to do so, you must create backups, either manually or schedule an automatic backup, then delete the instance, and use the backup to restore the instance.

https://cloud.google.com/sql/docs/mysql/backup-recovery/restoring#restorebackups

I think introducing a field of `backup` to `google_sql_database_instance` would be very useful. Similar to the `snapshot` field at `google_compute_disk`

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "master" {
  name = "master-instance"
  database_version = "MYSQL_5_6"
  # First-generation instance regions are not the conventional
  # Google Compute Engine regions. See argument reference below.
  region = "us-central"

  backup = "123456789"
}
```

**Comment by rileykarson** [comment]
Note that https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#snapshot_identifier is the AWS equivalent for context.

**Comment by jhuntoo** [comment]
Also something else to consider, a companion data source to address a common use case, similar to [aws_db_snapshot](https://www.terraform.io/docs/providers/aws/d/db_snapshot.html).

e.g.
```hcl
data "google_sql_database_backup" "latest_prod_backup" {
  instance_id = "production"
  most_recent            = true
}
```

which returns something similar to the output of `gcloud sql backups list --instance=<instance id>`

**Comment by rileykarson** [comment]
Note that backups need to be restored on an already-existing instance.
