### ISSUE TITLE
A data source to grab existing members of a iam role

### ISSUE THREAD

**Issue by MovieStoreGuy** [hashicorp/terraform-provider-google#2581]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I have recently moved to use terraform for managing access within various projects which has meant manually noting down which account has what role and storing them inside my vcs. 

This somewhat okay for our smaller projects we manage but some of our projects have been looked after manually and have some rather strange requirements so being able to automate who is apart of what role as a data source would be awesome.

### New or Affected Resource(s)

* google_*

### Potential Terraform Configuration

```tf
data "google_iam_member_binding" "existing_users" {
   project = "${var.project}"
   role     = "${var.role}"
}

resource "google_iam_member_binding" "updated_list" {
   project = "${var.project}"
   role     = "${var.role}"
   members = "${concat(data.google_iam_member_binding.existing_users.members, var.members)}"
}
```

### References

* #0000

**Comment by MovieStoreGuy** [comment]
I have but it is a pain to try update each user, with each role in a nice way.

**Comment by mitj04** [comment]
b/262374544

**Comment by mitj04** [comment]
- Product Name - Cloud Platform (Resource Manager)
- Datasource Name - google_project_iam_policy_members
- API Docs - [getIAMPolicy](https://cloud.google.com/resource-manager/reference/rest/v1/projects/getIamPolicy)
- Notes - 
    - REST Endpoints - 
        - POST https://cloudresourcemanager.googleapis.com/v1/projects/{resource}:getIamPolicy
    - This API allows us to retrieve the IAM access control policy for the provided Project, which contains the whole set of bindings. We can retrieve all the `members` of the given `Role` by filtering.

**Comment by rileykarson** [comment]
We recommend `google_iam_member` for this case. Automation like this is less well-supported by modern Terraform versions compared to the ones available at the time this issue was filed.
