### ISSUE TITLE
Add support for Stackdriver monitored project

### ISSUE THREAD

**Issue by aeneasr** [hashicorp/terraform-provider-google#2605]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.11.10

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf

resource "google_project_services" "project" {
  depends_on = ["google_project.project"]

  project = "${google_project.project.project_id}"

  services = [
    // ...
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "stackdriver.googleapis.com",
  ]
}

resource "google_monitoring_alert_policy" "cluster" {
  project = "${var.google_project_id}"

  display_name = "ORY GKE Cluster Alert Policy"
  combiner = "OR"
  enabled = true
  conditions = [
    {
      display_name = "test condition"
      condition_threshold {
        filter = "resource.type=\"gke_cluster\" AND severety>=\"WARNING\""
        duration = "60s"
        comparison = "COMPARISON_GT"
        threshold_value = 0
      }
    }
  ]
}
```

### Debug Output

```
Error: Error applying plan:

1 error(s) occurred:

* module.backoffice.google_monitoring_alert_policy.cluster: 1 error(s) occurred:
* google_monitoring_alert_policy.cluster: Error creating AlertPolicy: googleapi: Error 400: 'projects/<REDACTED>' is not a Stackdriver account project.
```

### Expected Behavior

It should be possible to link the project to a StackDriver account or use `google_monitoring_alert_policy` right away.

### Actual Behavior

I was unable to find any resources on how to link the project with the stackdriver account. It should either be documented how to achieve that (happy to do so after I know how to do it :) ) or added as a resource(?) or setting.

### Steps to Reproduce

I have not tested it yet, but a minimal reproduction case is probably to create a new project and try to set up a monitoring alert right away.

### References

* b/142750997 (outdated)
* b/194806937

**Comment by aeneasr** [comment]
Hi @danawillow , thank you for the response! The dependence should be implicit because the `project` and `project_services` is being created in a different module (module `gcp`) than `google_monitoring_alert_policy` (module `some_kubernetes_workspace`). `gcp` declares the project ID as output and `some_kubernetes_workspace` uses the project ID as input to specify the alert policy. I'll set up a log gist now.

**Comment by danawillow** [comment]
Sure, that's fine. first name last name at google dot com. In the meantime, @chrisst is there anything that needs to be done to enable stackdriver besides enabling the API?

**Comment by chrisst** [comment]
I believe that in order to use stack driver for the first time you will need to [enable a stack driver "workspace"](https://cloud.google.com/monitoring/workspaces/guide) which is loosely associated with a GCP project. I was hoping to deliver that but it looks like the api to create the workspace is still in development right now :( 
So for now there is still a manual step of going to https://app.google.stackdriver.com/accounts and adding your workspace.

When they release the api that supports this I'll get it added in!

**Comment by aeneasr** [comment]
Oh I see, that's what I kinda feared. Thank you for the update. @danawillow I'll refrain from sharing the trace with you then.

**Comment by chrisst** [comment]
@jaceq Unfortunately the stack driver codebase and apis are closed source and so there isn't a good place for the community to see the feature development. I've been told by the team that they are working on it but I also don't have insight as to when it will be available.

**Comment by spmsaj** [comment]
> I believe that in order to use stack driver for the first time you will need to [enable a stack driver "workspace"](https://cloud.google.com/monitoring/workspaces/guide) which is loosely associated with a GCP project. I was hoping to deliver that but it looks like the api to create the workspace is still in development right now :(
> So for now there is still a manual step of going to https://app.google.stackdriver.com/accounts and adding your workspace.
> 
> When they release the api that supports this I'll get it added in!

Hi, does this mean the api to create workspace is still not there from a GCP standpoint? And Terraform integration is waiting on that?

**Comment by rsalmond** [comment]
@spmsaj that is what I understand to be the case yes.

**Comment by jfotopoulos** [comment]
Hi.. any updates on this issue?

**Comment by boredland** [comment]
We'd need that too :-/

**Comment by jaceq** [comment]
@ocervell given it's almost half a year later... is this in beta finally?

**Comment by JessicaGreben** [comment]
I'm digging around the GCP [monitoring API docs](https://cloud.google.com/monitoring/api/v3/) and I still don't see API support for creating stackdriver workspaces. Sad. I'm also asking in the GCP slack stackdriver channel about a timeline, but no word yet.

**Comment by jamesmoriarty** [comment]
@danawillow any updates from your side?

**Comment by danawillow** [comment]
No updates on a date. If you're part of the alpha, you can ask your GCP rep to contact our team on  your behalf for support.

**Comment by probert-gameloft** [comment]
For the record, I'm also having the same issue. Had to create the workspace manually in StackDriver to be able to create the alert.

**Comment by emmaLP** [comment]
Is there a workaround for this in the meantime while this is is being worked on?

This is a blocker for a fully automated project set up.

**Comment by JessicaGreben** [comment]
@emmaLP the only workaround that I could come up with is to get early access to the alpha for Stackdriver Workspace API. I was told to talk with our Google Cloud Support point of contact to ask to be added to that. However you would still need to write the code to use the API to create stackdriver stuff, since terraform still doesn't have support for it.

**Comment by chrisst** [comment]
I have added alpha support for stackdriver workspaces to our closed build of the google provider. Since this is a closed alpha you will need to contact your account manager to get access to the stackdriver API and also the alpha Google provider builds.
Both the API and the Google provider are in alpha so are probably not good candidates for integrating into production at this point. Unfortunately I don't know the timeline for the stackdriver API's so I can't provide an update for when it will be available publicly.

**Comment by tibers** [comment]
Similar verbiage for TF 12:
`Error: Error creating AlertPolicy: googleapi: Error 400: 'projects/<PROJECT ID>' is not a workspace.`

**Comment by lawliet89** [comment]
Hey @chrisst It's been more than half a year since your comment. Is that API still in alpha?

**Comment by tibers** [comment]
@lawliet89 yeah all the gcloud commands are still `gcloud alpha ...` for working with stackdriver. 

example: https://cloud.google.com/sdk/gcloud/reference/alpha/monitoring/policies/create

**Comment by DanielJonesEB** [comment]
I know we're not supposed to leave +1 style messages, but given that there appears to be no other way to provide feedback or get visibility on StackDriver stuff, I'd like to say that I find it somewhat astonishing that in 2020 I can't fully automate the provisioning of an IAAS environment.

**Comment by rileykarson** [comment]
Just a quick note since I was taking a look at this earlier- the API is still available in alpha/private preview and unavailable at beta/public preview, at which point we'll be able to make it available in the `google-beta` provider. Our team has automation tracking the launch, and we're hoping to bring out provider support soon after it's available.

**Comment by prowerse** [comment]
Yes. This is still pending. Was creating uptime check and failed with following error - 
```
google_monitoring_uptime_check_config.check01: Creating...
Error: Error creating UptimeCheckConfig: googleapi: Error 404: Error while retrieving Stackdriver settings for project: projects/mickey-mouse-123456
```

Create stack driver workspace manually on console and it worked fine on next run. Would be appreciated if API for workspace creation is released sooner.

**Comment by apstndb** [comment]
Cloud Monitoring workspace is renamed to metrics scope and the API is in Public Preview.
https://cloud.google.com/monitoring/settings/manage-api

**Comment by rileykarson** [comment]
Oh, yep, we're working with https://github.com/GoogleCloudPlatform/declarative-resource-client-library to make that available, and add that to the provider.

**Comment by pietrodn** [comment]
Ok, so how do we enable the Cloud Monitoring API using Terraform now?

**Comment by trodge** [comment]
> Ok, so how do we enable the Cloud Monitoring API using Terraform now?

I believe you can already do so using [google_project_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service)

I seem to have linked this issue in the wrong PR, causing it to close prematurely.
https://github.com/GoogleCloudPlatform/magic-modules/pull/5218 will implement monitoring metrics scope and monitored project resources when it merges. These resources allow users to monitor metrics from multiple projects from the scope of a single project.

**Comment by rileykarson** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5218 /  https://github.com/GoogleCloudPlatform/magic-modules/pull/5235
