### ISSUE TITLE
Support for google_container_cluster istio addon

### ISSUE THREAD

**Issue by bluemalkin** [hashicorp/terraform-provider-google#2649]
Now that istio is released in beta https://cloud.google.com/blog/products/containers-kubernetes/accelerate-your-app-delivery-with-kubernetes-and-istio-on-gke

And that it can be added as an addon:

<img width="469" alt="screen shot 2018-12-13 at 9 19 14 am" src="https://user-images.githubusercontent.com/2703290/49902590-72e75180-feb8-11e8-97ad-37f1d17bb637.png">

We should add it as an add-on to the google beta provider: for example:
```
resource "google_container_cluster" "foo" {
  name = "foo"
[  ....]
  addons_config {
    istio {
      disabled = false
    }
  }
}
```

**Comment by danawillow** [comment]
Hey @bluemalkin, in the future would you mind filling out the template and leaving the commented lines in? They help hashibot label our issues :) Thanks!

**Comment by pondohva** [comment]
HI. I'd like to add this feature. Can I do this?

**Comment by danawillow** [comment]
Sure, I'll mark this as assigned!

**Comment by pondohva** [comment]
@danawillow I've [found](https://www.terraform.io/docs/providers/google/provider_versions.html#google-beta) that beta features (like cluster_autoscaling) moved to terraform-provider-google-beta. Should I create PR to beta repo instead?

**Comment by brettcurtis** [comment]
So is this in the beta provider now?

**Comment by pondohva** [comment]
@brettcurtis yep

**Comment by pondohva** [comment]
I guess it can be closed now due to https://github.com/terraform-providers/terraform-provider-google-beta/pull/280

**Comment by pondohva** [comment]
@rsalmond it has been merged to master of beta provider, because istio is beta feature.
