### ISSUE TITLE
Add data source for google_organization_iam_custom_role

### ISSUE THREAD

**Issue by bluemalkin** [hashicorp/terraform-provider-google#2652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Since you can define custom roles at the organization level to make them available for projects and folders, it seems logical to have a data source for `google_organization_iam_custom_role` so that we can fetch the custom role ID.

### New or Affected Resource(s)
Data source:
* google_organization_iam_custom_role

**Comment by zhhuta** [comment]
I believe you may use https://www.terraform.io/docs/providers/google/d/datasource_google_iam_role.html
where ```name``` is  
```organizations/{ORGANIZATION_ID}/roles/{ROLE_NAME}``` or ```projects/{PROJECT_ID}/roles/{ROLE_NAME}```
here is example
```hlc
locals {
 org_id = "{org_id}" # your org id
 prj_id = "{project_id}" # you project id
 role_id = "CustomRole"
}



data "google_iam_role" "orgroleinfo" {
  name = format("organizations/%s/roles/%s", local.org_id, local.role_id)
}

data "google_iam_role" "prjroleinfo" {
  name = format("projects/%s/roles/%s",local.prj_id, local.role_id)
}

output "the_org_role_permissions" {
  value = data.google_iam_role.orgroleinfo.included_permissions
}

output "the_prj_role_permissions" {
  value = data.google_iam_role.prjroleinfo.included_permissions
}
```

**Comment by upodroid** [comment]
@rileykarson We can close this too. The name arg in the doc specifies formats for both project and org level custom roles

**Comment by rileykarson** [comment]
Tracks with me. Thanks!
