### ISSUE TITLE
Support CMEK Disks for DataProc

### ISSUE THREAD

**Issue by paul-opsguru** [hashicorp/terraform-provider-google#2689]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Will be great to add CMEK support for local DataProc disks:

https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/customer-managed-encryption

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

Could be part of the `disk_config` block for both master and workers:
```
disk_config {
  disk_encryption_key = "${var.disk_key}"
  ...
}
```
### References

* #0000

**Comment by upodroid** [comment]
@rileykarson We can close this. It has been implemented in https://github.com/GoogleCloudPlatform/magic-modules/pull/1205
