### ISSUE TITLE
Should be able to create a google_sql_database_instance by cloning

### ISSUE THREAD

**Issue by dfedde-pivotal** [hashicorp/terraform-provider-google#272]
Hello,

CloudSql allows you to create a new instance by cloning a exiting one [see docs
here](https://cloud.google.com/sql/docs/mysql/clone-instance).

We would like this to be as supported way of creating a `google_sql_database_instance`.

**Comment by danawillow** [comment]
Hey @dfedde-pivotal, can you explain your use case a bit further?

**Comment by dfedde-pivotal** [comment]
we would like to be able to create a database as a clone of another(perhaps even to a point in time). With the AWS provider we were able to use [snapshot_identifier](https://www.terraform.io/docs/providers/aws/r/db_instance.html#snapshot_identifier) to create a  instance based on another instance. It looks like the only way to do something similar in CloudSQL is to clone database.

In our case we would be using this to setup a instance that has production data In It for testing.

**Comment by jcanseco** [comment]
Hello, I saw that this is now supported in 3.56.0, though it seems that there is a discrepancy between the docs and the implementation: [the docs say that `clone.point_in_time` is optional](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance), but [the field seems to be marked Required in the code](https://github.com/hashicorp/terraform-provider-google-beta/blob/4792c8d7ca37d0633409817b654b40fbcbe3d73a/google-beta/resource_sql_database_instance.go#L625-L630).

No impact on us -- was just curious which way it's supposed to be.

**Comment by sanghaniJ** [comment]
b/261802319

**Comment by sanghaniJ** [comment]
- Resource Name

  In Cloud SQL, for resource google_sql_database_instance the support for the feature is requested.

- Requested Feature

  The requested feature is regarding support for cloning resources.

- REST Endpoints

  Attaching the Rest API for [sqlDatabaseInstance](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances) and for [clone](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/clone) as well.

- Highlighting Notes

  The Clone functionality was available as per [Gcloud docs](https://cloud.google.com/sql/docs/mysql/clone-instance) but wasn't supported in Terraform.

By checking, I saw that the requested feature is supported in 3.56.0. But in the [comment](https://github.com/hashicorp/terraform-provider-google/issues/272#issuecomment-775545946) by Jazel on issue, it was stated that in docs, clone.point_in_time was Optional while the same in Code was Required. Addressing that, a [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/4715) for the same was merged and the field is Optional now. Hence, we can close the issue ticket.
