### ISSUE TITLE
Add a datasource for google_cloudbuild_trigger

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#2793]
This issue is to gauge interest in a datasource for `google_cloudbuild_trigger`. Please 👍 this comment if you're interested.

### Affected Resource(s)

* google_cloudbuild_trigger

**Comment by AarshDhokai** [comment]
b/261816602

**Comment by edwardmedia** [comment]
This data source is available now. Closing this ticket now

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloudbuild_trigger
