### ISSUE TITLE
Some `google_storage_*` resources don't encode object names properly

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-google#2895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
```

### Summary

This is a bug report about a bunch of resource that makes use of the GCS API directly because the `google.golang.org/api/storage/v1` package does not support the API calls for some reason.

When using the JSON API that requires the object names in the URL, we have to take care in URL encoding object names that contains `/` for the URL. See https://cloud.google.com/storage/docs/json_api/#encoding

These resources do not seem to do any form of URL encoding in API call.

### Affected Resource(s)

I looked through the source code searching for the string `https://www.googleapis.com/storage/v1` so this might not be exhaustive:

- `data.google_storage_bucket_object`
- `google_storage_default_default_object_access_control`
- `google_storage_object_access_control`

### Terraform Configuration Files

Consider the following example:

```tf
provider "google" {
  region  = "${var.region}"
  project = "${var.project_id}"
}

terraform {
  backend "gcs" {}
}

resource "google_storage_bucket" "test" {
  name     = "${var.bucket_name}"
  location = "${var.region}"

  storage_class = "REGIONAL"
}

resource "google_storage_bucket_object" "object" {
  name    = "foo/bar/baz"
  bucket  = "${google_storage_bucket.test.name}"
  content = "Hello GCP"
}

resource "google_storage_object_access_control" "public_rule" {
  object = "${google_storage_bucket_object.object.name}"
  bucket = "${google_storage_bucket.test.name}"
  role   = "READER"
  entity = "allUsers"
}

variable "bucket_name" {
  description = "Bucket name"
}

variable "project_id" {
  description = "Project ID to deploy the cluster to"
}

variable "region" {
  description = "Default region for GCP"
  default     = "asia-southeast1"
}

```

### Debug Output

https://gist.github.com/lawliet89/0258872b901513386f10a5b1c8f755a0

### Expected Behavior

ACL for object is created.

### Actual Behavior

Failed.

```
* google_storage_object_access_control.public_rule: Error creating ObjectAccessControl: googleapi: got HTTP response code 404 with body: Not Found
```

If you look at the debug log, you can see that the object name in the URL was not escaped properly.

Also, using the `urlencode` interpolation function does not work. It causes a HTTP 400 error where the URL object name differs from the one in the POST body.

**Comment by odedniv** [comment]
@lawliet89 does #3347 address this issue properly?

**Comment by lawliet89** [comment]
It does. But might require an "upstream" fix in magic modules.

**Comment by odedniv** [comment]
Is this repo commited to automatically from there?

**Comment by odedniv** [comment]
Adding @tysen to the convo

Is the current implementation better than #3347? Right now only variables explicitly with `%` in them get escaped. Should the user even be aware that this is part of the Google API when writing their Terraform configuration?

Also note that it should only be done in the URL, and so if the variable is used in the body of the request it must not be escaped. This means that it may be confusing for the user that he specified a variable to be escaped but it won't.

**Comment by odedniv** [comment]
Created https://github.com/GoogleCloudPlatform/magic-modules/pull/1717

**Comment by danawillow** [comment]
@edwardmedia @venkykuberan can one of you check on this?

**Comment by tmarszal** [comment]
@danawillow hi, just encountered this one myself today. When I try to create Object ACL it is not encoding object name in the URL.

I tried to encode it myself in HCL, but then the API is complaining that object value from url and body doesn't match. So the other part of this is that object doesn't need to be sent in the body - it is not when running this method from the API explorer.

**Comment by tmarszal** [comment]
Looks to me like this is what it takes to fix it (https://github.com/GoogleCloudPlatform/magic-modules/compare/master...tmarszal:master)

**Comment by danawillow** [comment]
I'm not sure what the status of this is, but it sounds like at least parts of it have been fixed. I'm going to close this out- feel free to file a new bug if there are still related issues.
