### ISSUE TITLE
Enabling metadata concealment on an existing container_node_pool is difficult

### ISSUE THREAD

**Issue by yob** [hashicorp/terraform-provider-google#2900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Node pools can be configured with optional metadata concealment like this:

```tf
resource "google_container_node_pool" "my-pool" {
  node_config {
    workload_metadata_config  {
      node_metadata = "SECURE"
    }
  }
}
```

`node_metadata` can also be set to `EXPOSE` or `UNSPECIFIED`.

For node pools that were created without this `workload_metadata_config` block, there's no way to add one without terraform wanting to recreate the entire node pool.

Reading the GCP docs it seems like it may not be possible to enable metadata concealment on an existing node pool. In that case, I'd hoped that setting the block to `UNSPECIFIED` might make the `terraform plan` a no-op, but it doesn't seem to work that way.

### New or Affected Resource(s)

* google_container_node_pool

**Comment by Chupaka** [comment]
And the actual output of `terraform plan` is... Oh, by the way, where is it? :)

**Comment by upodroid** [comment]
@danawillow Can we close this issue? Metadata Concealment has been deprecated in favour of Workload Identity.

https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment
