### ISSUE TITLE
Add generated id attribute to data.google_compute_backend_service

### ISSUE THREAD

**Issue by OmarDarwish** [hashicorp/terraform-provider-google#2926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When a backend service is created, it is assigned an autogenerated id. This id is required when validating signed JWT tokens for applications running behind an Identity Aware Proxy (IAP), since it is in the token's `aud` claim. 

When creating a backend service with terraform via the `google_compute_backend_service`, this id is not an attribute on this `resource`, and it is also not an attribute on the `data.google_compute_backend_service` either.

Looking at `.tfstate`, the `id` attribute on these resources seems to be the backend name, and not the generated id.

### New or Affected Resource(s)

* google_compute_backend_service
* data.google_compute_backend_service

### Potential Terraform Configuration

Either would be acceptable:

```tf
resource "google_compute_backend_service" "my_service" {
   ...
}

output "my_service_id" {
  value = "${google_compute_backend_service.my_service.generated_id}"
}
```

or

```tf
resource "google_compute_backend_service" "my_service" {
   ...
}

data "google_compute_backend_service" "my_service" {
   name = "${google_compute_backend_service.my_service}"
}

output "my_service_id" {
  value = "${data.google_compute_backend_service.my_service.generated_id}"
}
```
### References

* https://cloud.google.com/iap/docs/signed-headers-howto#verify_the_jwt_payload

**Comment by rosmo** [comment]
+1 to this.

**Comment by rosmo** [comment]
Hey @OmarDarwish,

Here's a workaround I used:

```
data "external" "audience-id" {
  program = [
    "gcloud",
    "compute",
    "backend-services",
    "describe",
    google_compute_backend_service.application-backend.name,
    "--global",
    "--format=json(id)"
  ]
}
```
Then you can refer to the ID with `data.external.audience-id.result.id`. Hope this help!

**Comment by linus** [comment]
We have this same issue. The workaround seems to work (though we get a cycle if specifying the backend service directly, since they will refer to each other). It feels bad though. Looking at the magic-modules repository, it seems like the `id` we want is exported:

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/api.yaml#L1415-L1418

However, the docs state otherwise and the value we get is according to the docs: `projects/{{project}}/global/backendServices/{{name}}`.

How can we get the id in the Terraform output?

**Comment by AlfatahB** [comment]
b/262351359

**Comment by AlfatahB** [comment]
I've looked into the issue and the following are the details I've found out:
- The existing `id` field of the `google_compute_backend_service` is used as the ID of the terraform resource and it is in the form `projects/{{project}}/global/backendServices/{{name}}`.  This `id` field is **not** the `id` output-only field in [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices).
- This `id` field that is defined by the API server is currently not supported in the terraform.
- This `id` field defined by the server is the unique identifier for the `google_compute_backend_service`.
-  It seems like we need to add support for a new field `generated_id` to get this `id` field defined by the server in the terraform state.
- Also, it seems like the `id` output-only field was defined in the [api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/api.yaml#L1436-L1439) but it was excluded in the [terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/terraform.yaml#L413-L414).

The possible solution is to add support for a new field `generated_id` in both the `google_compute_backend_service` resource and datasource that will give us the value of the `id` field defined by the server.
