### ISSUE TITLE
`google_sql_database_instance` should recreate going private -> public

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#2964]
This "upgrade" path isn't supported, but going public -> private is. We return an API error today, we should have plan show that that's `ForceNew` by using `CustomizeDiff` if possible.

Specifically, `private_network` can't go from having a value to no value; this might be infeasible if setting a diff `ForceNew` requires the field to be `Computed`.

**Comment by rileykarson** [comment]
It should also recreate if the `private_network` is in another project (shared VPC) going public -> private

**Comment by danawillow** [comment]
@edwardmedia @venkykuberan can one of you check on this?

**Comment by edwardmedia** [comment]
@rileykarson yes, it works when `public` -> `private` But it does not work when `private` -> `public` Below plan shows it is not for `recreate`
```
  # google_sql_database_instance.instance will be updated in-place
  ~ resource "google_sql_database_instance" "instance" {
...
          ~ ip_configuration {
              ~ ipv4_enabled    = false -> true
              - private_network = "projects/myprojectglobal/networks/issue2964private-network" -> null
                require_ssl     = false
            }
        }
    }
```
```
Error: Error, failed to update instance settings for : googleapi: Error 400: This operation is not valid for this instance., invalidOperation
```
