### ISSUE TITLE
Support for google_app_engine_default_service_account

### ISSUE THREAD

**Issue by radkomateusz** [hashicorp/terraform-provider-google#2998]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

Hello, I would like to have data source like: google_app_engine_default_service_account (projectId@appspot.gserviceaccount.com).
It's very similar to google_compute_default_service_account.

**Comment by evralston** [comment]
An adjacent issue (the regex validation of service account IDs in IAM policy resources) was addressed in #1390 which probably will help with the implementation of fixing this.
