### ISSUE TITLE
Add support for Interoperable storage access keys

### ISSUE THREAD

**Issue by jernster-clgx** [hashicorp/terraform-provider-google#2999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Need a way to automate the creation of interoperable storage access/developer keys.  It would also be useful to be able to provide a label / description for the purpose for the key.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by danawillow** [comment]
Hi @jernster-clgx, I'm not totally clear on what you're asking for. Could you link to the GCP documentation that describes this feature?

**Comment by jernster-clgx** [comment]
Hi Dana, this is in reference to https://cloud.google.com/storage/docs/migrating#keys - step one is being able enable interoperability access, the other is creating the developer/interoperability key, lastly, it'd be ideal to be able to assign a label to each key created to identify its purpose.

**Comment by theomessin** [comment]
Are there any plans on implementing this? It is very much needed in certain cases! Happy to help if you point me in the right direction.

**Comment by danawillow** [comment]
As far as I know, this is up for grabs. We have some info on how to contribute at https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md. If possible, we'd strongly prefer that the code be written in [magic modules](https://github.com/GoogleCloudPlatform/magic-modules). Let me know if you have any questions!

**Comment by paddycarver** [comment]
I'm not seeing support for this anywhere in the API. I think we're blocked on adding an API to generate these credentials.

**Comment by upodroid** [comment]
@rileykarson We can close this issue.

HMAC Keys can be created in terraform.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_hmac_key

**Comment by rileykarson** [comment]
👍  thanks!
