### ISSUE TITLE
AutoML Feature Request

### ISSUE THREAD

**Issue by josephlewis42** [hashicorp/terraform-provider-google#3037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be great to be able to provision service accounts that can use AutoML models and augment their datasets so customers could start to build custom tools to take advantage of the technology.

Terraform resources would be used to support two user-journeys:

1. Users build datasets and train models manually, but grant access to them through TF. These tools need IAM access to AutoML models.
2. Users build tools that help classify (or load classified data) that can be used to train models. These tools need to be able to create models, datasets, and get/grant IAM access to them.

### New or Affected Resource(s)

Resources listed from most useful to least:

* google_automl_models_iam_*
* google_automl_models
* google_automl_datasets_iam_*
* google_automl_datasets

### References

* https://cloud.google.com/vision/automl/docs/reference/rest/v1beta1/projects.locations.models
* https://cloud.google.com/vision/automl/docs/reference/rest/v1beta1/projects.locations.datasets

**Comment by krackjack29** [comment]
Hi Guys, has there been any updates on the automl terraform resource.

**Comment by bhagyashreemohan** [comment]
Can anyone share terraform code for automl .i want to automate my ML deployment in my projects on priority.

**Comment by mitj04** [comment]
b/262499716

**Comment by mitj04** [comment]
- **Product Name** - AutoML
- **Resource Name** - 
    - google_automl_models
    - google_automl_models_iam_* (poilcy/binding/member)
    - google_automl_datasets
    - google_automl_datasets_iam_* (poilcy/binding/member)
- **API Docs** - 
    - [Models](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.models) 
    - [Datasets](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.datasets)
- **Notes** - 
    - Base URL - `https://automl.googleapis.com/v1`
    - Models
        - REST Endpoints
            - [Create](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.models/create)
            - [Read](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.models/get)
            - [Update](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.models/patch)
            - [Delete](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.models/delete)
    - Datasets
        - REST Endpoints
            - [Create](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.datasets/create)
            - [Read](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.datasets/get)
            - [Update](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.datasets/patch)
            - [Delete](https://cloud.google.com/automl/docs/reference/rest/v1/projects.locations.datasets/delete) 
    - The response body of CREATE and DELETE contains an instance of `Operation` hence it seems we need to handle this behavior using the `async` block of api.yaml.
    - For the google_automl_*_iam_* resources, we may refer to any resource that supports Endpoints like getIamPolicy and setIamPolicy and has Terraform support for it, such as `google_bigquery_dataset`.
        - Reference for iam_* - [google_bigquery_dataset_iam_*](https://github.com/hashicorp/terraform-provider-google/blob/main/google/provider.go#L1424) 
    - UPDATE request is of PATCH type with updateMask required, it seems like we need to keep the `update_verb` to PATCH and `update_mask` to true.

**Comment by rileykarson** [comment]
AutoML is superseded by Vertex AI, which we support.

```
This legacy version of AutoML Vision is [deprecated](https://cloud.google.com/vision/automl/docs/deprecations) and will no longer be available on Google Cloud after January 23, 2024. All the functionality of legacy AutoML Vision and new features are available on the Vertex AI platform. See [Migrate to Vertex AI](https://cloud.google.com/vertex-ai/docs/start/migrating-to-vertex-ai) to learn how to migrate your resources.
```
