### ISSUE TITLE
google_compute_shared_vpc_service_project not leveraging IAM folder perms

### ISSUE THREAD

**Issue by leg100** [hashicorp/terraform-provider-google#3370]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

$ terraform -v
Terraform v0.11.13
+ provider.google v2.3.0
+ provider.google-beta v2.3.0
+ provider.random v2.1.0

### Affected Resource(s)

* google_compute_shared_vpc_service_project

### Terraform Configuration Files

```tf
resource "google_compute_shared_vpc_service_project" "project" {
  provider    = "google-beta"

  host_project    = "${var.host_project_id}"
  service_project = "${module.project.id}"
```

### Debug Output

I'd rather not (contains many identifiers I'd rather not make public).

### Expected Behavior

Should have successfully linked the service project to the host project.

### Actual Behavior

```
* google_compute_shared_vpc_service_project.project: googleapi: Error 403: Required 'compute.organizations.enableXpnResource' permission for 'projects/host-project'
More details:
Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/host-project'
Reason: forbidden, Message: Required 'compute.organizations.enableXpnResource' permission for 'projects/service-project'
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have the above permissions set on folders containing the host and service projects. This functionality is only supported on the beta endpoint [1]. Hence the use of the `google-beta` endpoint in terraform.

(I suspect terraform is ignoring this and sending it to the GA endpoint).

[1] https://cloud.google.com/vpc/docs/shared-vpc

### References

* #0000

**Comment by rileykarson** [comment]
This was fixed (but the issue not closed) and later reverted, as we enforced the use of GA APIs in the GA provider. Given it's now a documented limitation in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_shared_vpc_service_project, closing.
