### ISSUE TITLE
Disk snapshot data source

### ISSUE THREAD

**Issue by minichate** [hashicorp/terraform-provider-google#3382]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Similar to https://www.terraform.io/docs/providers/aws/d/ebs_snapshot.html, it'd be nice if there was a data source to look up disk snapshots. This could be passed as the `snapshot` attribute to the `google_compute_disk` resource to provision disks from the latest snapshot, for example.

### New or Affected Resource(s)

* google_compute_snapshot

### Potential Terraform Configuration

```tf
data "google_compute_snapshot" "latest_snapshot" {
  most_recent = true
  filter {
    label   = "foobar"
    values = ["baz"]
  }
}

resource "google_compute_disk" "disk1" {
  name = "from-snapshot"
  snapshot = "${google_compute_snapshot.latest_snapshot.self_link}"
}
```

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/snapshots/list
* Internal issue: [http://b/223263215](http://b/223263215)

**Comment by rileykarson** [comment]
Possible candidate for https://github.com/GoogleCloudPlatform/magic-modules/issues/1570

**Comment by codydiehl** [comment]
Looking for this as well for the possibility of using it for our DR fail-over from our production project to our DR project. 

We would reference the snapshots from multiple VMs in Prod over to DR project and bring up the new servers in the DR project. 
We created the systems with Terraform so would like to achieve the same with Terraform. 

This is currently not very efficient in Terraform as we first need to get the specific list of Snapshots that we need for the boot and data disks and then enter that in manually as variables to achieve this. 
When there is multiple servers this is a lot of pre-work and not very quick. 

Having the ability to reference them in a data source especially with the filter option, where we could perhaps define a date to get a list of disks including boot and the data disks would make short work of this issue.

**Comment by tpoindessous** [comment]
Hi ! 

Anybody interested by this enhancement ? ;) 

It would be great to be able to filter by name and by creationTimestamp.

My use case : 

- automatic creation of a disk + VM from the backup (snapshot) of "2020-04-20"

Thanks !

**Comment by mehdicopter** [comment]
What about your PR [#168](<https://github.com/hashicorp/terraform-provider-google/pull/168>) @tpoindessous ?

**Comment by tpoindessous** [comment]
> What about your PR [#168](https://github.com/hashicorp/terraform-provider-google/pull/168) @tpoindessous ?

Hi @mehdicopter , it was 3 years ago :) I tried to finish it but I failed ...

Now, with MagicModules, I find that the step to contribute a new datasource to TF GCP is too high for me :(
