### ISSUE TITLE
Include ability to filter images based on labels or other data.

### ISSUE THREAD

**Issue by amy-hashi** [hashicorp/terraform-provider-google#3442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Both the aws and azure providers already offer something similar ([azure name regex](https://www.terraform.io/docs/providers/azurerm/d/image.html) and [aws filter](https://www.terraform.io/docs/providers/aws/d/ami.html)). 

Ideally you'd be able to filter based on name, label, image family, region, etc. 

### New or Affected Resource(s)

* [data source - google_compute_image](https://www.terraform.io/docs/providers/google/d/datasource_compute_image.html)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
data "google_compute_image" "my_image" {
  name    = "debian-9"
  project = "debian-cloud"

  filter {
    name = "label"
    values = ["label1-*"]
  }

  filter {
    name = "region"
    values = ["uswest"]
  }
}
```

### References

* #0000

**Comment by upodroid** [comment]
@danawillow Can we close this issue? this feature is not needed for GCE Images.

1. https://cloud.google.com/compute/docs/reference/rest/beta/images/getFromFamily and https://cloud.google.com/compute/docs/reference/rest/beta/images/get API Calls return exactly one image from Google so there is no point in filtering the response. Images are globally unique within a project.
2. The OP referred to filters in `aws_ami` but AWS has a clunky implementation for this (biased 😄 ). https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ami.go#L205 and https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html . That API call returns a list of images that need to be filtered.

**Comment by danawillow** [comment]
@upodroid, I think the request is to be able to get a list of images that specify certain conditions, so that the user _doesn't_ have to know the name of the image in order to use it. That seems totally reasonable to me. This would be using https://cloud.google.com/compute/docs/reference/rest/beta/images/list instead of get or getFromFamily. Given the 25 👍  on this issue, it seems like this is something that people are looking for outside of what the provider currently offers, even if it isn't useful to you, so I'd prefer not to close it.

**Comment by upodroid** [comment]
In that case, I can implement the list method when no `name` or `family` is provided and use the filter query params to supply user filters. Like the `aws_ami` datasource, the filters provided must return a single image or an error is returned.
