### ISSUE TITLE
Remove redundant GKE tests

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#3447]
We have too many GKE tests; we should remove some so we use less quota and we can run acc tests faster.

**Comment by danawillow** [comment]
Whoops, forgot to link the PRs to this issue:
* https://github.com/GoogleCloudPlatform/magic-modules/pull/1983
* https://github.com/GoogleCloudPlatform/magic-modules/pull/1988
* https://github.com/GoogleCloudPlatform/magic-modules/pull/1990

**Comment by paddycarver** [comment]
This issue is basically waiting for someone to compile a list of redundant tests for GKE, and then remove them.
