### ISSUE TITLE
Return list of all networks in project via data resource google_compute_network

### ISSUE THREAD

**Issue by eternaltyro** [hashicorp/terraform-provider-google#3511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There should be  away to fetch all `google_compute_network` from a given project. My case is that I need to add all the networks of a given project to a private managed DNS zone. Currently, the data resource for `data.google_compute_network` only fetches a network by name. 

Instead of making `name` required and `project` optional, we could make both optional; If name is provided, then the current behaviour would prevail. If name is not provided but a project is, then the data resource would return a list of all the networks in the given project. If neither of them are provided, then it would be an error.

### Affected Resource(s)

* `data google_compute_network` 

### Potential Terraform Configuration

```tf
resource "google_dns_managed_zone" "private-zone" {
  name = "${var.project_id}-private-zone"
  dns_name = "private.example.local."
  description = "test"

  visibility = "private"

  private_visibility_config {
    networks {
    //SOME INTERPOLATION HERE
    }
  }
}

// Something like this
data "google_compute_network" "project-1" {
  project = "${var.project_id}"
}

```

### References

* https://stackoverflow.com/questions/55865615/fetching-compute-networks-from-project-using-data-resources?noredirect=1#comment98406187_55865615

**Comment by rileykarson** [comment]
This is similar to `[data.google_projects](https://www.terraform.io/docs/providers/google/d/google_projects.html)` (see [the API](https://cloud.google.com/compute/docs/reference/rest/v1/networks/list), and a possible candidate for https://github.com/GoogleCloudPlatform/magic-modules/issues/1570

**Comment by AarshDhokai** [comment]
- As per my observation, users want to support a list of all the networks available in the project, in an existing data source [google_compute_network](https://github.com/hashicorp/terraform-provider-google/blob/main/google/data_source_google_compute_network.go). That seems possible to implement by adding project_id attribute and by making name and project_id attribute optional. We need to add both into Exactlyoneof to require at least one attribute to decide whether the user wants a list of networks or a single network.
- But as per my observation, this isn’t an ideal way to handle such types of endpoints, instead we can add a new data source google_compute_networks which can give a list of networks within the project.

**Comment by rileykarson** [comment]
Case of https://github.com/hashicorp/terraform-provider-google/issues/8255

**Comment by roaks3** [comment]
Note that https://github.com/hashicorp/terraform-provider-google/issues/8255 also includes some light guidelines on how to implement a plural datasource like this

**Comment by roaks3** [comment]
Whoops, should have checked first, this is already implemented by https://github.com/GoogleCloudPlatform/magic-modules/pull/9232
