### ISSUE TITLE
Improve validation on GCP TF provider

### ISSUE THREAD

**Issue by tonglil** [hashicorp/terraform-provider-google#3580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Having this provider run without doing meaningful validation means often what you "think" you will do seeing the output of `terraform plan` is not actually what will happen due to many reasons, such as:

- insufficient permissions by the service account
- invalid values in fields
- invalid arguments

It becomes really cumbersome to use this provider in any sort of infrastructure-as-code management with code reviews because "approved" changes don't actually work. And since there isn't a "test" environment for a GCP project, it becomes a trial-and-error process to try to get it to work, at which point reviews are rendered useless.

The `terraform plan` phase should really be dry-running against the resources - otherwise there's no difference between `plan` and `validate`.

After all:

> This command is a convenient way to check whether the execution plan for a set of changes **matches your expectations** without making any changes to real resources or to the state. For example, terraform plan might be run before committing a change to version control, **to create confidence** that it will behave as expected.
- https://www.terraform.io/docs/commands/plan.html

### New or Affected Resource(s)

For example: `google_project_iam_binding`. If you forget to add the `serviceAccount:` or `group:` string, it will still pass `terraform validate` and `terraform plan`, however crash on you during `terraform apply` with a vague message as:

```
* google_project_iam_binding.test: Error applying IAM policy for project "project": Error setting IAM policy for project "project": googleapi: Error 400: Request contains an invalid argument., badRequest
```

### Potential Terraform Configuration

```tf
google_project_iam_binding.test: Creating...
  etag:               "" => "<computed>"
  members.#:          "" => "2"
  members.119724285:  "" => "my-account@project.iam.gserviceaccount.com"
  members.1285300841: "" => "114684633812-compute@developer.gserviceaccount.com"
...
```

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/3411
* https://github.com/terraform-providers/terraform-provider-google/issues/3420

**Comment by chrisst** [comment]
I think this would be really great! Especially as the newer APIs continue to become more complex. Unfortunately I think it would either require the upstream API's to support this behavior or some way to share validation logic between the API controllers and Terraform. Neither of which I am optimistic will be available in the near future.

I'm going to keep this open as an open forum for figuring out other ways that we can improve the validation flow.

**Comment by dijitali** [comment]
Agreed, the lack of proper validation of GCP resources makes introducing changes a bit of a case of whack-a-mole game trying to fix validation errors that only surface at the `apply` stage.

Since we only run `apply` in our CD pipeline, never locally, I have to push changes through in a fresh PR to my team each time which makes the entire process unreliable, takes up more of my time and interrupts my teammates more frequently when I have to bug them for a bunch of "fixing validation issue" reviews for a single change.  It encourages bad practices in the team when people try to look for other ways to find validation issues before an apply failing.

**Comment by paddycarver** [comment]
I think this is a useful and valuable conversation to have, and I think that improving the validation is something we'd like to do. Unfortunately, hunting down all the areas where validation is sub-optimal is a time-consuming and very manual process. Given that, I think the best way forward is when you notice that validation would have been useful, you open an individual issue to add that specific validation. That would help us to find and improve the validation across the provider in a sustainable, ongoing way.

**Comment by gordcook** [comment]
Would it help to isolate the 3 concerns?  If so, the permission problem is the top issue, in my opinion.

Terraform has a well known problem that if you try to apply without appropriate permissions, it often gets stuck in a bad state.  We were working with a valid Terraform configuration, but it took hours of iterations of applying and initializing the Terraform jobs to get the permissions correct.  

By the end of the plan phase, it seems to me that the provider knows all of the operations that it will need to perform and _ought_ to be able to verify whether the user has sufficient permissions to successfully complete all of those operations.
