### ISSUE TITLE
New data source: google_compute_instance_template

### ISSUE THREAD

**Issue by mattes** [hashicorp/terraform-provider-google#365]
A data source for `google_compute_instance_template`s would be helpful in combination with `google_compute_instance_group_manager`.

**Comment by rosbo** [comment]
Are you looking for any filtering functionality like [here](https://www.terraform.io/docs/providers/aws/d/ami.html) or simply a data source for a given instance template you reference by its unique name?

**Comment by mattes** [comment]
I don't know if `filters` are supported by the Google API, but `name_regex` would be awesome.

**Comment by universalvishwa** [comment]
I noticed that gcloud API does provide the capability to query existing instance templates. I also acknowledge this new data source request by @mattes . I ran into a wall without this functionality today. :-P

**Comment by universalvishwa** [comment]
Is this going to be addressed in near future?

**Comment by KyuRish** [comment]
I still don't see this, it is a very much required to force no public IPs with the template in terraform
