### ISSUE TITLE
Add a Firestore Document resource

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#3950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add the ability to create a Firestore document using Terraform. This is also the best way to expose the creation of collections, which are created implicitly when a document is created.

### New or Affected Resource(s)

* google_firestore_document

### Potential Terraform Configuration

```tf
resource "google_firestore_document" "admin" {
  collection = "users"
  name = "admin"
  fields = {
    username = "admin"
    password = "hunter2"
  }
}
```

### References

* #3657

**Comment by jakebiesinger-onduo** [comment]
In our use case, we use firestore for lightweight read-only application configuration, which I'd like to have checked in as code.  Terraform 0.12's lets me specify that config natively, and I'd like to publish it to firestore.

As a workaround, you can do this via cmdline, with all the usual caveats for doing so:

```terraform
locals {
  customers = [
    { 
      name = "customer1"
      some = "value"
      a-number = 123
    }
  ]
}
resource "null_resource" "deploy-customer-config" {
  count = length(local.customers)

  triggers = {
    source = jsonencode(local.customers[count.index])
  }

  provisioner "local-exec" {
    command = <<EOF
firebase --project ${local.project} database:set --confirm /client-config/${local.customers[count.index].name} --data '${jsonencode(local.customers[count.index])}'
EOF
  }
}
```

**Comment by adarobin** [comment]
The use case I have for this is we currently use Cloud Datastore to store metadata about projects we have created for our internal customers.  We're trying to rebuild our existing provisioning process using Terraform, and this would make storing that metadata much less painful.

**Comment by thomas-stockx** [comment]
> In our use case, we use firestore for lightweight read-only application configuration, which I'd like to have checked in as code. Terraform 0.12's lets me specify that config natively, and I'd like to publish it to firestore.
> 
> As a workaround, you can do this via cmdline, with all the usual caveats for doing so:
> 
> ```terraform
> locals {
>   customers = [
>     { 
>       name = "customer1"
>       some = "value"
>       a-number = 123
>     }
>   ]
> }
> resource "null_resource" "deploy-customer-config" {
>   count = length(local.customers)
> 
>   triggers = {
>     source = jsonencode(local.customers[count.index])
>   }
> 
>   provisioner "local-exec" {
>     command = <<EOF
> firebase --project ${local.project} database:set --confirm /client-config/${local.customers[count.index].name} --data '${jsonencode(local.customers[count.index])}'
> EOF
>   }
> }
> ```

The command line example here uses Realtime Database instead of Firestore and is therefore not really a workaround for having no Firestore Document resource.

Our use-case is the same however, storing config data in Firestore for some of our more lightweight applications, as well as an admin list for some Firestore security rules.
