### ISSUE TITLE
Support cloudbilling APIs / Billing Sub Accounts

### ISSUE THREAD

**Issue by adarobin** [hashicorp/terraform-provider-google#4033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd love to be able to create and manage our billing subaccounts through Terraform.

At my current employer, we provide an Enterprise Agreement, Preconfigured Security/Networking/Reporting/Logging, VPN, and chargeback for GCP to other departments.  We'd like to potentially migrate from the current homegrown python based provisioning solution to Terraform.  The only functionality that seems to be missing is the ability to create billing subaccounts with Terraform.

### New or Affected Resource(s)

* google_billing_sub_account

### Potential Terraform Configuration

```tf
resource "google_billing_sub_account" "my_billing_account" {
  name = "My Billing Account"
  master_billing_account = "012345-567890-ABCDEF"
}
```

### References

https://cloud.google.com/billing/reference/rest/v1/billingAccounts/create

**Comment by adarobin** [comment]
I'm happy to take a try at this, working on getting a CLA signed.  Does this need to be a fully generated resource, or is a manual one ok?

**Comment by karolsochk** [comment]
@adarobin any plans to progress this ?

**Comment by adarobin** [comment]
@karolsochk I'm still pushing for the CLA
