### ISSUE TITLE
Add support for Realtime Database trigger in resource.google_cloudfunctions_function

### ISSUE THREAD

**Issue by comradesharf** [hashicorp/terraform-provider-google#4055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently if I try to add Realtime Database trigger using `google_cloudfunctions_function`, applying resources will produce
```
Error: googleapi: Error 500: Internal error encountered., backendError
```

When I use `TF_LOG=TRACE`,  the **resource** will be 
```
"resource": "%!(EXTRA string=project_id, string=resource)"
```
This might be due to
https://github.com/terraform-providers/terraform-provider-google/blob/ac70b40e20cb24baf6b5a8e9220a1ff03702265b/google/resource_cloudfunctions_function.go#L584

where we are not covering the case for realtime database trigger.

Can we add realtime database trigger too in the switch case? 

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  name                  = "function-test"
  runtime               = "nodejs8"
  source_archive_bucket = "${google_storage_bucket.bucket.name}"
  source_archive_object = "${google_storage_bucket_object.archive.name}"
  entry_point           = "onHelloChanged"

  event_trigger {
    event_type = "providers/google.firebase.database/eventTypes/ref.create"
    resource   = "projects/_/instances/PROJECT_ID/refs/hello/{id}"
  }
}

```

### References

* https://cloud.google.com/functions/docs/calling/realtime-database#event_types

**Comment by comradesharf** [comment]
I can do PR for this

**Comment by daveth** [comment]
The [referenced link](https://cloud.google.com/functions/docs/calling/realtime-database#event_types) implies Firebase RT DB triggers are not GA. Would this mean the change to resolve the issue would be more appropriate to be applied to the google-beta provider instead?

**Comment by megan07** [comment]
Hi @daveth! You are correct, it looks like this would be implemented on the google-beta provider. We'd love to have your contribution. Please take a look at our [contributing guide](https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md) and please reach out with any questions!
Thanks!

**Comment by melinath** [comment]
It looks like this switch has been fixed as of https://github.com/hashicorp/terraform-provider-google/commit/92e352dcafa7e1b467a9cfcdd77e43ee4b41e3c7 (August 2019). There may also have been a problem on the API side; however, I'm marking this as resolved for now.
