### ISSUE TITLE
more useful examples

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#4077]
many of our documented examples show a configuration that would technically create that resource, but not with any sort of meaningful values. it would be worth going through these examples to ensure that they provide value (perhaps as a fixit).

**Comment by conorgil** [comment]
@danawillow This is a GREAT idea. I found the documentation lacking and incredibly difficult to use when getting up to speed. Examples really help clarify the practical use of resources.

https://github.com/terraform-providers/terraform-provider-google/pull/3239 is my attempt to add more useful examples to some resources.

**Comment by rileykarson** [comment]
We are not going to take action based on this issue, so closing out.
