### ISSUE TITLE
Can't use for_each in google_compute_address

### ISSUE THREAD

**Issue by lantier** [hashicorp/terraform-provider-google#4110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

* Terraform - 0.12.5
* Provider - 2.11.0

### Affected Resource(s)

* google_compute_address

### Terraform Configuration Files

```tf
data "google_compute_subnetwork" "subnetwork" {
  project = var.network_hosting_project
  name    = var.subnetwork
  region  = var.region
}

resource "google_compute_address" "static_ip" {
  name         = var.name
  description  = var.description
  project      = var.project
  subnetwork   = data.google_compute_subnetwork.subnetwork.self_link
  address_type = var.address_type

  dynamic "cidr" {
    for_each = var.address_type == "INTERNAL" ? [1] : []
    content {
      address = cidrhost(data.google_compute_subnetwork.subnetwork.ip_cidr_range, var.address_suffix)
    }
  }
}
```

### Debug Output

https://gist.github.com/lantier/996f9fc436a1cf050b2ab90f0a1798d8

### Expected Behavior

Create a INTERNAL/EXTERNAL static IP based on variable "address_type", because the resource doesn't accept ADDRESS value in EXTERNAL TYPES

### Actual Behavior

Error: Unsupported block type

  on ip.tf line 17, in resource "google_compute_address" "static_ip":
  17:   dynamic "cidr" {

Blocks of type "cidr" are not expected here.

**Comment by paddycarver** [comment]
I think there's some confusion here. What are you trying to achieve? The [`dynamic` block expression](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) is used to repeat a block within a resource, but the `google_compute_address` has no `cidr` block. It actually doesn't have any blocks at all.

**Comment by edwardmedia** [comment]
No response. Assuming it is no longer an issue
