### ISSUE TITLE
Support for Folder Audit Config

### ISSUE THREAD

**Issue by jbrekelmans** [hashicorp/terraform-provider-google#4130]
I am trying to enable Audit Logging on various APIs in IAM via Terraform.
This is possible by using [google_iam_policy](https://www.terraform.io/docs/providers/google/d/google_iam_policy.html), but google_iam_policy requires that I define all existing bindings in source code. The latter is undesirable for a few reasons:
1. I can remove my own permissions accidentally.
2. Default bindings created by GCP when enabling APIs have to be manually moved into source control.
3. The Terraform for IAM cannot be separated into two separate Terraform projects with separate state (a restriction in my corporate environment). 

Is there a way in Terraform to only set Audit Logging configuration, without also setting bindings?

**Comment by ryu1kn** [comment]
FYI https://github.com/terraform-providers/terraform-provider-google/issues/3066

**Comment by paddycarver** [comment]
Hey @jbrekelmans, so we already have this supported for google_project. Was there another resource you were looking for support for this for?

**Comment by chrisst** [comment]
folder audit config is being added as part of https://github.com/terraform-providers/terraform-provider-google/pull/5282

organization audit config was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/2741

Once folder audit configs are added I will be closing this out

**Comment by upodroid** [comment]
This issue can be closed now. This feature was added recently. 

https://www.terraform.io/docs/providers/google/r/google_folder_iam_audit_config.html
