### ISSUE TITLE
google_composer_storage resource

### ISSUE THREAD

**Issue by kardiff18** [hashicorp/terraform-provider-google#4148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be nice to have a google_composer_storage resource, so that you can upload files to the DAG folder in GCS. 

This would be similar to the following gcloud command:

gcloud composer environments storage dags import \
  --environment my-environment  --location us-central1 \
  --source test-dags/quickstart.py

### New or Affected Resource(s)

* google_composer_storage
*google_composer_environment

### Potential Terraform Configuration

None

### References

* No

**Comment by rileykarson** [comment]
On a re-review of this issue I'm not sure what API method(s) this would implement. I'm going to close this based on that + its age- if it gets refiled we'll address the re-filing.
