### ISSUE TITLE
Could not find default credentials when deleting terraform module

### ISSUE THREAD

**Issue by OwenMatsuda** [hashicorp/terraform-provider-google#4272]
### Problem

Terraform version: `0.12.6`

I'm getting this:
```
Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. 

  on <empty> line 0:
  (source code not available)
```

It occurs after I run terraform apply, and it seems to sometimes leave something stuck in the backend tf.state file. It performs all of the terraform operations correctly, but it throws an error at the end anyway. I was able to find a workaround by exporting the environment variable `export GOOGLE_APPLICATION_CREDENTIALS="/keys/key_1.json"`, with `key_1.json` being the key for the backend as described below.

### To Replicate the Issue
Directory Structure:
```
project
|    backend.tf.json
|    providers.tf
|    credential-test.tf.json
|––– credential-test/
     |    template.tf
```

In `backend.tf.json`:
```
{
  "terraform": {
    "backend": {
      "gcs": {
        "bucket": "someBucket",
        "prefix": "somePrefix",
        "credentials": "/keys/key_1.json"
      }
    }
  }
}
```
In `providers.tf`:
```
provider "google" {
  alias       = "testing"
  credentials = "${file("/keys/key_2.json")}"
  project     = "someProject"
}
```
Not sure if it matters, but key_1 and key_2 are different keys for different projects.

In `credential-test.tf.json`:
```
{
  "module": {
    "test-credential-error": {
      "source": "./credential-test/",
      "providers": {
        "google.main": "google.testing"
      }
    }
  }
}
```

In `credential-test/template.tf`:
```
provider "google" {
  alias = "main"
}

# Add disk resource
resource "google_compute_disk" "disk" {
  provider = "google.main"

  name  = "credentials-test-disk"
  size  = "210"
  zone  = "us-east1-b"
  image = "projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20190212a"
}
```

Once you have the file structure set up, in the main directory, do:
1. `terraform init`
2. `terraform apply`
    - yes
3. Delete `credential-test.tf.json`
4. `terraform apply`
    - yes

**Comment by danawillow** [comment]
Hi @OwenMatsuda, next time would you mind filling out one of the predefined issue templates? Those help our automation label issues so we can more easily navigate the issue tracker.

When you delete the module file, are you expecting that TF should do nothing, or attempt to provision something?

**Comment by zagr0** [comment]
Hi

We experience the same issue on
Terraform v0.12.13
+ provider.google v2.18.1

`Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

  on <empty> line 0:
  (source code not available)`

We expect the same behaviour as we have on 0.11, after resources from the module are destroyed, terraform apply expected to finished with success. Nothing expected to be provisioned.

**Comment by ahamed-atypon** [comment]
Me too, 
Terraform v0.12.13
provider.google v2.18.1

**Comment by danawillow** [comment]
@zagr0 and @ahamed-atypon, are you both also using remote state with gcs? I tried to do a simple repro without remote state and didn't get the same error.

**Comment by zagr0** [comment]
@danawillow , yes Im using aws s3 backend for state

**Comment by ahamed-atypon** [comment]
Yes GCP backend

**Comment by OwenMatsuda** [comment]
@danawillow I apologize and will use the issue template in the future. 

I expected that when I delete the module, it should destroy the specific resources associated with that module and complete successfully. When I do this, it destroy the resources as expected, but it throws the unexpected error described above.

**Comment by zagr0** [comment]
hello, is there any progress with the issue?
still present on 0.12.17

**Comment by danawillow** [comment]
I haven't had any time to verify that it's a core issue and not a provider one, but if you think it might be, you can try filing at http://github.com/hashicorp/terraform/issues

**Comment by zagr0** [comment]
created issue for core
https://github.com/hashicorp/terraform/issues/23567

**Comment by Miyurz** [comment]
I've been experiencing the same issue with terraform 0.12.21.
```
tf apply -var-file=prod.tfvars -lock=false

Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

  on <empty> line 0:
  (source code not available)



 tf version 
Terraform v0.12.20
+ provider.google v2.9.1
+ provider.google-beta v2.9.1
```

**Comment by danawillow** [comment]
@Miyurz since https://github.com/hashicorp/terraform/issues/23567 was closed, I'd recommend filing a new issue against hashicorp/terraform with full reproduction steps. I haven't been convinced yet that this is something we can fix at a provider level, but at the very least with a reproduction they can funnel it back over here if it is indeed a provider thing.

**Comment by OwenMatsuda** [comment]
Just ran a test on `Terraform v0.13.4` and did not encounter the problem.
