### ISSUE TITLE
Audit handwritten resources for potential nil pointers

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#4313]
Make sure we don't end up with another https://github.com/terraform-providers/terraform-provider-google/pull/4002 (and the numerous issues filed about it from people on versions before the fix was deployed).

The only way I can think to do this right now would be to go by hand to check that every handwritten resource that reads nested fields has a nil check. It doesn't prevent them sneaking in in the future, but porting our resources to MM will take care of that in the long run.

**Comment by rileykarson** [comment]
We are not going to take action based on this issue, so closing out.
