### ISSUE TITLE
data.google_kms_secret trying to force version 1

### ISSUE THREAD

**Issue by TylerWanner** [hashicorp/terraform-provider-google#4341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.14
+ provider.google v2.13.0

### Affected Resource(s)

* data.google_kms_secret

### Terraform Configuration Files

```tf
data "http" "keys" {
  url = "${data.google_storage_object_signed_url.keys.signed_url}"
}

data "google_kms_secret" "keys" {
  crypto_key = "${data.terraform_remote_state.storage.kms_key}"
  ciphertext = "${data.http.keys.body}"
}
```

### Expected Behavior

returns the unencrytped plaintext

### Actual Behavior

data.google_kms_secret.keys: data.google_kms_secret.keys: Error decrypting ciphertext: googleapi: Error 400: projects/prefect-vault/locations/global/keyRings/vault/cryptoKeys/vault-init/cryptoKeyVersions/1 is not enabled, current state is: DESTROY_SCHEDULED., failedPrecondition

^^ the error message is accurate, that version IS scheduled for deletion but am not trying to use version 1--there seems to be no way to use a different cryptokeyversion

**Comment by rileykarson** [comment]
I'm going to close this as stale/outdated. Please feel free to open it again / file a new issue if it's still a problem!
