### ISSUE TITLE
Default value for google_container_cluster.workload_identity_config.identity_namespace

### ISSUE THREAD

**Issue by misha-ridge** [hashicorp/terraform-provider-google#4544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_container_cluster` has a block `workload_identity_config` with an attribute `identity_namespace`.

This attribute can only be set to the `"${data.google_project.<some-project>.project_id}.svc.id.goog"`.

There is no Terraform syntax to refer to a provider
-> there is no way to construct `data.google_project.<project-from-a-provider>.project_id`
-> there is no way to create a cluster with workload identity enabled in the default project, specified in the provider. One has to explicitly say the project name in the cluster resource.

Given this attribute has a single allowed value, it would be useful to have that value as a default.

### New or Affected Resource(s)

* `google_container_cluster`

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "cluster" {
  provider = "google-beta"
  name = "name"
  # No explicit project attribute, project is inherited from provider

  workload_identity_config {
    # No explicit identity_namespace
  }
}
```

**Comment by rileykarson** [comment]
As a workaround, https://www.terraform.io/docs/providers/google/d/datasource_client_config.html#project allows you to retrieve the project id of the user's provider.

**Comment by misha-tectonic** [comment]
Oh, thank you. I looked for something like this, but missed it.

**Comment by rileykarson** [comment]
Note: This field was removed in `4.0.0`. https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_4_upgrade#workload_identity_config0identity_namespace-is-now-removed
