### ISSUE TITLE
linuxConfig for google_container_cluster

### ISSUE THREAD

**Issue by bryanlarsen** [hashicorp/terraform-provider-google#4589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We need to adjust the fs.inotify.max_user_watches on the nodes in our cluster.  Google's CLI supports doing that through the linuxConfig section of the --node-config flag in it's CLI: https://cloud.google.com/sdk/gcloud/reference/alpha/container/clusters/create

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
node_config {
  linux_config = {
    sysctl = {
       "fs.inotify.max_user_watches" = 500000
    }
  }
}
```

### References

* #0000

**Comment by danawillow** [comment]
This isn't yet available in the beta GKE APIs (https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig), so marking as blocked on upstream

**Comment by bobbypage** [comment]
Hi @bryanlarsen, I'm from the GKE node team.

We currently set `fs.inotify.max_user_watches` to `12288` on GKE since the default OS setting (`8192`) is too low (xref: https://github.com/kubernetes/kubernetes/issues/10421).

Is there any reason you need to tune the `max_user_watches`? Have you run into issues where the GKE set default `12288` is too low?

**Comment by danawillow** [comment]
(since I'm still subscribed to issues I've commented on in the past, just a note that linux_node_config is supported now: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#linux_node_config. Removing the 'upstream' label.)

**Comment by rileykarson** [comment]
+1 to Dana, I think https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#linux_node_config is what was requested here.
