### ISSUE TITLE
Add reservationAffinity to google_compute_instance

### ISSUE THREAD

**Issue by julianvmodesto** [hashicorp/terraform-provider-google#4593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add `reservationAffinity` to `google_compute_instance` to consume a `google_compute_reservation`.

### New or Affected Resource(s)

* google_compute_instance
* google_compute_reservation

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/4254
* https://cloud.google.com/compute/docs/reference/rest/v1/instances
* https://cloud.google.com/compute/docs/reference/rest/v1/reservations

**Comment by mhuxtable** [comment]
I'm working on this one. Should have a functional integration with the `google_compute_instance` and `google_compute_instance_template` resources in the morning.

**Comment by mhuxtable** [comment]
Now implemented, comments welcome on #7669

**Comment by dvmorris** [comment]
When will this be released?
