### ISSUE TITLE
Select a zone arbitrarily if a region is provided but a zone is not.

### ISSUE THREAD

**Issue by zioproto** [hashicorp/terraform-provider-google#4603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resource `google_filestore_instance` requires a zone to be specified.

However, from the GCP dashboard, is possible to create this resource just with the region specification:
<img width="536" alt="Screen Shot 2019-10-02 at 1 51 12 PM" src="https://user-images.githubusercontent.com/789701/66042086-d0b65a00-e51b-11e9-8883-57e628460b48.png">

### New or Affected Resource(s)

* google_filestore_instance

### Potential Terraform Configuration

```tf
resource "google_filestore_instance" "instance" {
  name = "test-instance"
  region = "us-central1"
  tier = "PREMIUM"

  file_shares {
    capacity_gb = 2660
    name        = "share1"
  }

  networks {
    network = "default"
    modes   = ["MODE_IPV4"]
  }
}
```

### References

* https://www.terraform.io/docs/providers/google/r/filestore_instance.html

**Comment by ndmckinley** [comment]
Unfortunately, filestore instances are zonal resources - behind the scenes, I assume the region selector is just selecting a zone within that region, using some logic that we can't access or replicate here.

https://cloud.google.com/filestore/docs/reference/rest/v1beta1/projects.locations.instances/create
> In Cloud Filestore, locations map to GCP zones, for example us-west1-b.

It would be a fairly significant bit of work on this provider to allow zones to be selected automatically if a region is provided.  I'm going to leave this open for voting, but I would need to see a significant number of votes to start work on this.

**Comment by ndmckinley** [comment]
I've changed the title to reflect the request - as it happens it would be exactly as easy to do this for all resources as for one resource.  :)

**Comment by airstand** [comment]
Head plus sign :)
I also prefer to have a region instead of explicitly defining a single zone.

**Comment by sanghaniJ** [comment]
b/263344707

**Comment by sanghaniJ** [comment]
I've gone through this issue and the request seems to be a selection of random zone when not provided in resource `filestore_instance` 
- I tried checking the [API Docs](https://cloud.google.com/filestore/docs/reference/rest/v1beta1/projects.locations.instances#Instance) and couldn't find the field Zone.
- Going through the markdown and resource [schema](https://github.com/hashicorp/terraform-provider-google/blob/f1499bfeda9a47c35400e2291ea6ea3f826ab48e/google/resource_filestore_instance.go#L234) it was mentioned that zone is `deprecated` in favor of location.
- Now, in Filestore, `location` map to Google Cloud zones, for example us-west1-b.
- After checking the `location` , it could be seen in the [resource](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_filestore_instance.go#L325) that when the location is not provided, the function GetZone is called and zone is automatically selected. 
- This feature was merged in [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/5450).

Hence, this issue can be closed.

**Comment by rileykarson** [comment]
The reason for closure identified in https://github.com/hashicorp/terraform-provider-google/issues/4603#issuecomment-1361116273 is incorrect- a zone still needs to be supplied, it's just that it may come from the provider or `location` field. Prior to https://github.com/GoogleCloudPlatform/magic-modules/pull/5450 it was required to supply a `zone` directly. The request here is to specify a region and have the resource select a zone was not satisfied.

However, I'm leaving this closed anyways- this was turned into a general bug across the provider & that's not a feature we're interested in supporting. Users should specify a zone explicitly, unless the API does selection for them (such as GCE regional disks, GKE, etc.)
