### ISSUE TITLE
Disallow `bigquery-json.googleapis.com` in `google_project_service`

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#4624]
This service is being renamed to `bigquery.googleapis.com` and will go away eventually. `2.X` will handle it with https://github.com/GoogleCloudPlatform/magic-modules/pull/2424.

This should be done post roll-forward of the new name (~early Nov)

**Comment by rileykarson** [comment]
Adding upstream label because we're waiting on the roll-forward.

**Comment by melinath** [comment]
It looks like this actually still needs to happen.
