### ISSUE TITLE
Use GITHUB_ORGANIZATION environment variable for Cloudbuild GitHub owner

### ISSUE THREAD

**Issue by orinokai** [hashicorp/terraform-provider-google#4629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When using GitHub repositories with google_cloudbuild_trigger it would be useful to optionally source the `owner` property from the `GITHUB_ORGANIZATION` environment variable.

I currently use this env var with the GitHub provider and it's useful to avoid hardcoding the owner or passing it as a variable. It is specifically useful when writing generic modules that could be used by any GitHub organisation, e.g. for publishing in the Terraform Registry.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "dev" {
  project = "my-project"
  description = "Push to master branch"
  filename = "cloudbuild.yml"

  github {
#  owner = "my-organisation" <-- no longer necessary
    name  = var.name

    push {
      branch = "^master$"
    }
  }
}
```

### References

* #1950
* #2416
* b/270751998

**Comment by rileykarson** [comment]
This can be solved with environment variables by the user: https://developer.hashicorp.com/terraform/language/values/variables#environment-variables
