### ISSUE TITLE
google_compute_image snapshot

### ISSUE THREAD

**Issue by aclowkey** [hashicorp/terraform-provider-google#4696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform version
v0.11.14
### Provider version
v1.20.0

### Description

You can provide in the Console, a source snapshot for an image, but you can't do that in the terraform resource.

### New or Affected Resource(s)

* google_compute_image

### Potential Terraform Configuration
```tf
resource "google_compute_image" "image" {
   name             = "image"
   source_snapshot  = "snapshot_url"
}

**Comment by stenalpjolly** [comment]
@paddycarver @danawillow @aclowkey 
I believe https://github.com/GoogleCloudPlatform/magic-modules/pull/3799 has already added support for source_snapshot and source_image

If nothing is missing, Can we please close the ticket?

**Comment by danawillow** [comment]
@megan07 @slevenick can you help?

**Comment by slevenick** [comment]
Yep, looks like this was done via https://github.com/GoogleCloudPlatform/magic-modules/pull/3799
