### ISSUE TITLE
Add support for push-auth-service-account to pubsub_subscription

### ISSUE THREAD

**Issue by lc-chrisbarton** [hashicorp/terraform-provider-google#4704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `gcloud` commandline tool has this arg `--push-auth-service-account` but it doesn't seem to be available in terraform. We use this config at the moment to work around this:

```
resource "null_resource" "google_pubsub_subscription_xxx" {
  provisioner "local-exec" {
    command = "gcloud --project $GCP_PROJECT_ID beta pubsub subscriptions create $SUBSCRIPTION --topic=$TOPIC --expiration-period=$EXPIRATION_PERIOD --ack-deadline=$ACK_DEADLINE --push-endpoint=$PUSH_ENDPOINT --push-auth-service-account=$SERVICE_ACCOUNT --push-auth-token-audience=$OPTIONAL_AUDIENCE_OVERRIDE"
    environment = {
      ACK_DEADLINE               = 10
      EXPIRATION_PERIOD          = "never"
      GCP_PROJECT_ID             = var.project_id
      OPTIONAL_AUDIENCE_OVERRIDE = "xxx"
      PUSH_ENDPOINT              = "https://xxx.${var.env}.yyy.com/xxx/v1/queue-zzz"
      SERVICE_ACCOUNT            = "id-pubsub-push-svc@${var.project_id}.iam.gserviceaccount.com"
      SUBSCRIPTION               = "qqq"
      TOPIC                      = "ppp"
    }
  }
}
```

### New or Affected Resource(s)

* google_pubsub_subscription

### References

https://github.com/terraform-providers/terraform-provider-google-beta/pull/1024

**Comment by ericvolp12** [comment]
So I was digging through this and was going to start working on it when I realized it has already been solved... In order to authenticate requests made from a PubSub PUSH subscription to the PUSH endpoint, you need to set the `oidc_token` in the `push_config` on the resource. You set the `oidc_token.service_account_email` to the email of the service account you wish to use to generate the authorization header (making sure it is permissioned for `subscriptions.create`, `subscriptions.patch` and `subscriptions.modifyPushConfig` RPCs with the `iam.serviceAccounts.actAs` permission).

Using @lc-chrisbarton's example, we can update the configuration as follows:
```
resource "null_resource" "google_pubsub_subscription_xxx" {
  name = "some_subscription_name"
  push_config {
    push_endpoint = "https://my_endpoint_with_auth/push"
    oidc_token {
      service_account_email = "myserviceaccount@email.com"
    }
  }
}
```

You don't need to specify an audience for this field either.

This should help anyone who is experiencing difficulty setting up authentication for pubsub subscription PUSH endpoints.

I think this issue can be closed.

**Comment by cmohank** [comment]
> oidc_token {
>       service_account_email = "id-pubsub-push-svc@${var.project_id}.iam.gserviceaccount.com"
>       audience = "xxx"
>     }

I am using the above . But when applying it, I am getting error message saying that "google api : error 400 : Invalid argument to the service push config::oidc_token::service_account_email". Any help to resolve it?

**Comment by juangaitanv** [comment]
> > oidc_token {
> > service_account_email = "id-pubsub-push-svc@${var.project_id}.iam.gserviceaccount.com"
> > audience = "xxx"
> > }
> 
> I am using the above . But when applying it, I am getting error message saying that "google api : error 400 : Invalid argument to the service push config::oidc_token::service_account_email". Any help to resolve it?

https://registry.terraform.io/modules/terraform-google-modules/pubsub/google/latest#:~:text=oidc_service_account_email%20%3D%20%22sa%40example.com%22

Use `oidc_service_account_email` attribute instead

**Comment by melinath** [comment]
Closing based on https://github.com/hashicorp/terraform-provider-google/issues/4704#issuecomment-627092643 - if that's incorrect please let us know.
