### ISSUE TITLE
google_container_cluster private_cluster_config should allow bgp propagation

### ISSUE THREAD

**Issue by dustyketchum** [hashicorp/terraform-provider-google#4778]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Assume your development / on prem network is remotely connected to your gcp vpc via interconnect or vpn or similar private networking.  If you create a google_container_cluster resource with a private_cluster_config, you would like to be able to access the gke configuration directly from your on prem network.  However you need to first 1) update the vpc peering that was created between your gcp vpc and the newly created gke master to import and export custom routes, and 2) advertise this new route with your gcp cloud router.  Step 1 - updating the vpc peering, cannot currently be automated via terraform.  

Proposal - add two new optional values export_custom_routes and import_custom_routes to private_cluster_config.  If these values are set, routes should be automatically propagated to / from the gke master network to the peered vpc.
An alternative proposal is to return the gke master network peering connection to the caller, and require the caller to then change the network peering to allow route propagation. However this is less desirable because there does not appear to be a way to have terraform modify an existing gcp peering connection to allow route propagation.  This would also be a lot more work for the caller for no real reason; the google_container_cluster resource can make this change.

### New or Affected Resource(s)

google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
```
resource "google_container_cluster" "test" {
...
  private_cluster_config {
    enable_private_endpoint = true
    enable_private_nodes    = true
    master_ipv4_cidr_block  = "10.0.0.1/28"
    export_custom_routes = true
    import_custom_routes = true
  }
...
}
```

### References

related
https://github.com/terraform-providers/terraform-provider-google/issues/3394

**Comment by dylanPowers** [comment]
I found a workaround in the google-beta provider that addresses this issue https://www.terraform.io/docs/providers/google/r/compute_network_peering_routes_config.html#example-usage-network-peering-routes-config-gke

```
resource "google_compute_network_peering_routes_config" "peering_gke_routes" {
  provider = google-beta

  peering = google_container_cluster.private_cluster.private_cluster_config[0].peering_name
  network = google_compute_network.container_network.name

  import_custom_routes = true
  export_custom_routes = true
}
```

**Comment by videap** [comment]
@dylanPowers thanks, your workaround works

Of course now in 2023 we don't actually need to use google-beta 🙂

**Comment by rileykarson** [comment]
I think this was solved in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering_routes_config.html#example-usage-network-peering-routes-config-gke as raised above, closing.
