### ISSUE TITLE
GKE Application-Layer Secrets

### ISSUE THREAD

**Issue by fproulx-dfuse** [hashicorp/terraform-provider-google#4789]
Application-layer Secrets encryption is now generally available in GKE.
https://cloud.google.com/blog/products/containers-kubernetes/exploring-container-security-use-your-own-keys-to-protect-your-data-on-gke

This feature is missing from Terraform provider. Not to be confused with database_encryption (etcd), this one encrypts Secret resources.

**Comment by marko7460** [comment]
Are there any plans on adding this feature in near future?

**Comment by upodroid** [comment]
@danawillow We can close this issue out. It already exists in the provider.

According to the docs it is the `database_encryption` block.

https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets

**Comment by danawillow** [comment]
You sure? The original poster specifically wrote "Not to be confused with database_encryption"

**Comment by upodroid** [comment]
I saw that but the it is the same thing. You are encrypting the etcd store which holds k8s Secrets.

From blog post posted by the original poster:

![image](https://user-images.githubusercontent.com/25100905/91279666-ae55ac80-e77d-11ea-9097-f01d5688818c.png)

**Comment by danawillow** [comment]
Cool, I'm convinced. @fproulx-dfuse or anyone else subscribed, if you disagree, please comment. In the meantime, closing.
