### ISSUE TITLE
"google_compute_instance" resource recreates instance if "metadata_startup_script" changed

### ISSUE THREAD

**Issue by paulpalamarchuk** [hashicorp/terraform-provider-google#4824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.6
+ provider.google v2.19.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "main" {
  name                      = var.name
  project                   = var.project_id
  machine_type              = var.machine_type
  zone                      = var.zone
  allow_stopping_for_update = true

  tags = ["datalab"]

  labels = {
    role    = "datalab"
    use_gpu = false
  }

  boot_disk {
    initialize_params {
      image = "cos-cloud/cos-stable"
      size  = var.boot_disk_size_gb
    }
  }

  network_interface {
    subnetwork = var.subnet_name
  }

  metadata = {
    enable-oslogin = "TRUE"
    for-user       = var.datalab_user_email
  }

  metadata_startup_script = "#!/bin/bash blah-blah-blah"

  service_account {
    email  = var.service_account
    scopes = ["cloud-platform"]
  }

  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = false
    enable_vtpm                 = true
  }

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
    preemptible         = false
  }
}
```

### Expected Behavior

Expedited to update the startup script

### Actual Behavior

Instance destroyed and created new.

### Steps to Reproduce

1. Apply resource
2. Change argument `metadata_startup_script`
3. `terraform plan`

[Plan Output](https://gist.github.com/paulpalamarchuk/b9c55637ffb1b402ce356b6956c44e5a)

**Comment by danawillow** [comment]
Hi @paulpalamarchuk, can you expand a bit more on what you expect to happen? Would you expect that changing the startup script would restart the instance (so that it can run), or that it would just take note so that the next time the instance restarts, it gets run?

**Comment by paulpalamarchuk** [comment]
Hi @danawillow, I expected that instance's metadata `startup-script` value will be changed, without restart or instance recreation, just the same, as I'll change it manually.
The root case is that instance recreated, if metadata changes and that is unexpected behaviour, for me.  
If there will be a flag(parameter) to restart instance if metadata changes, that would be nice.

**Comment by Chupaka** [comment]
@paulpalamarchuk, did you read the docs? https://www.terraform.io/docs/providers/google/r/compute_instance.html
Looks like you want "startup-script" metadata instead of using metadata_startup_script parameter.

**Comment by paulpalamarchuk** [comment]
@Chupaka thank you. I missed that.
Seems like issue can be closed.

**Comment by danawillow** [comment]
@Chupaka, I still think it might be worth making that field editable given that the user can manually force-recreate the instance by tainting the resource, although I'd consider that more of a feature request than a bug. Do you see any reason to keep it ForceNew, besides the fact that there's an alternative option?
