### ISSUE TITLE
google_sql_database_instance / Provider produced inconsistent final plan / ....authorized_networks

### ISSUE THREAD

**Issue by lchastel** [hashicorp/terraform-provider-google#4876]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.13
+ provider.external v1.2.0
+ provider.google v2.19.0
+ provider.google-beta v2.19.0
+ provider.local v1.4.0
+ provider.mysql v1.9.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "cloudsql" {
  name             = var.cloudsql_name
  database_version = var.database_version

  region  = var.gcp_region
  project = var.project_id

  settings {
    tier      = var.cloudsql_tier
    disk_size = var.storage_size

    location_preference {
      zone = var.gcp_zone
    }

    backup_configuration {
      enabled            = var.enable_backup
      binary_log_enabled = var.enable_binary_log
      start_time         = var.backup_start_time
    }

    ip_configuration {
      require_ssl     = "false"
      ipv4_enabled    = var.has_public_ip
      private_network = var.vpc_selflink

      **dynamic "authorized_networks" {
        for_each = local.authorized_networks
        iterator = net

        content {
          name  = net.key
          value = net.value
        }
      }**

    }

    user_labels = merge(
      local.common_labels,
      {
        "component" = "cloudsql"
      },
    )

    dynamic "database_flags" {
      for_each = var.database_flags
      iterator = flags

      content {
        name  = flags.key
        value = flags.value
      }
    }

    maintenance_window {
      day  = var.maintenance_window_day
      hour = var.maintenance_window_hour
    }
  }
}
```

```tf
locals {
authorized_networks = {
  "datastudio01" = "64.18.0.0/20"
  "datastudio02" = "64.233.160.0/19"
  "datastudio03" = "66.102.0.0/20"
  "datastudio04" = "66.249.80.0/20"
  "datastudio05" = "72.14.192.0/18"
  "datastudio06" = "74.125.0.0/16"
  "datastudio07" = "108.177.8.0/21"
  "datastudio08" = "173.194.0.0/16"
  "datastudio09" = "207.126.144.0/20"
  "datastudio10" = "209.85.128.0/17"
  "datastudio11" = "216.58.192.0/19"
  "datastudio12" = "216.239.32.0/19"
}
}
```

### Expected Behavior

When executing terraform apply, several block authorized network should be generated.
And so authorized networks set.

terraform plan show same result than apply, but doesn't return any error.

### Actual Behavior

Terraform apply extract ...
```
...
module.app.module.google-cloud-sql-mysql.google_sql_database_instance.cloudsql: Refreshing state... [id=xxx]
...
  # module.app.module.google-cloud-sql-mysql.google_sql_database_instance.cloudsql will be updated in-place
  ~ resource "google_sql_database_instance" "cloudsql" {
        connection_name               = "redacted"
        database_version              = "MYSQL_5_7"
        first_ip_address              = "redacted"
        id                            = "redacted"
       ...
           ~ settings {
       ... 
          ~ ip_configuration {
                ipv4_enabled    = true
                private_network = "redacted"
                require_ssl     = false

              - authorized_networks {
                  - name  = "redacted" -> null
                  - value = "redacted" -> null
                }
              + authorized_networks {
                  + name  = (known after apply)
                  + value = (known after apply)
                }
            }              
      ...

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

Error: Provider produced inconsistent final plan

When expanding the plan for
module.app.module.google-cloud-sql-mysql.google_sql_database_instance.cloudsql
to include new values learned so far during apply, provider "google" produced
an invalid new value for .settings[0].ip_configuration[0].authorized_networks:
actual set element
cty.ObjectVal(map[string]cty.Value{"expiration_time":cty.NullVal(cty.String),
"name":cty.StringVal("redacted"), "value":cty.StringVal("redacted")})
does not correlate with any element in plan.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.app.module.google-cloud-sql-mysql.google_sql_database_instance.cloudsql
to include new values learned so far during apply, provider "google" produced
an invalid new value for .settings[0].ip_configuration[0].authorized_networks:
block set length changed from 1 to 13.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
``` 

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Are you able to make a smaller config that reproduces the problem? Particularly one that doesn't feed nearly every field in as a variable. As-is, reproducing this  will take me a while to feed in values and I'll probably end up in a significantly different state.

**Comment by lchastel** [comment]
Here is a extract of my code (I have a lot of modules and extract was not so easy).
It's a fully working code.
It's creates the GCP project, the VPC, the Cloud SQL.

Please follow instruction in README.md to test.

After trying to reproduce the issue in this sample, I think the issue is due to manual operation on autorized networks from console (which could always happen)

[bug-auth-net.tar.gz](https://github.com/terraform-providers/terraform-provider-google/files/3846930/bug-auth-net.tar.gz)

**Comment by rileykarson** [comment]
Using `0.12.15` with `3.0.0-beta.1`, I'm unable to reproduce this. I was also unable to using `0.12.9`. That doesn't discount that it's happening, but means that it's on a limited range of versions of TF Core or on a provider release series we can't update anymore (`2.X`).

However, I am seeing some odd results where a valid configuration has a diff:

```
          ~ ip_configuration {
                ipv4_enabled    = true
                private_network = "projects/myprojectabc434325435/global/networks/vpc-network"
                require_ssl     = false

              - authorized_networks {
                  - name  = "cloudshell" -> null
                  - value = "142.231.7.23" -> null
                }
              + authorized_networks {
                  + name  = "cloudshell"
                  + value = (known after apply)
                }
            }
```

I'll use this issue to track fixing that.

**Comment by rileykarson** [comment]
Closing as stale- I'm not going to get to the minor issue I discovered, and was unable to reproduce the primary issue. Please file again if you encounter the same thing with newer provider versions.
