### ISSUE TITLE
Please add policy reference field to google_service_account

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform-provider-google#4979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`google_service_account` has an `email` attribute so the resource/data source can be used in IAM policies.  But it provides the bare email: `<name>@<project>.iam.gserviceaccount.com`.  This can't be used as-is in IAM policy since it's missing the `serviceAccount:` designator.  As a result, one must write: `format("serviceAccount:%s", google_service_acccount.foo.email)`.

Please add another attribute that prepends `serviceAccount:` to the email.  This would make for much less typing, and more readable configurations.

### New or Affected Resource(s)

* `google_service_account`

### Potential Terraform Configuration

Possible sample:

```tf
resource "google_service_account" "foo" {
  account_id = "foo"
  display_name = "bar"
}

data "google_iam_policy" "whatever" {
  binding {
    role = "roles/viewer"
    members = [google_service_account.foo.policy_ref]
  }
}
```

**Comment by AlfatahB** [comment]
b/262655388

**Comment by AlfatahB** [comment]
I've looked into this issue and the following are the details I have found out:
- It seems like the request is to add support for the `policy_ref` field in the `google_service_account` resource.
- This new field will add a prefix `serviceAccount:` to the already existing `email` field. But, such a field has already been added as [`member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#member) field.
- The PR that added support for this field can be found [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/6638). 

Hence, Closing this issue.
