### ISSUE TITLE
Error: Error reading AppProfile: googleapi: Error 400: Deleting an app profile will cause all requests using it to fail.

### ISSUE THREAD

**Issue by ahuiberts** [hashicorp/terraform-provider-google#5069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

2.14 google provider
0.12.8 terraform

### Affected Resource(s)

* google_bigtable_instance
* google_bigtable_app_profile

### Terraform Configuration Files
```
resource "google_bigtable_instance" "bigtable-ah" {
  name          = "bigtable-ah"
  provider      = "google.bigtable"
  project       = "bolcom-sbx-ah-bigtable-351"
  instance_type = "PRODUCTION"
  cluster {
    cluster_id    = "bigtable-ah-cluster"
    num_nodes     = "3"
    storage_type  = "HDD"
    zone          = "europe-west4-b"
  }
  cluster {
    cluster_id    = "bigtable-ah-cluster-replica"
    num_nodes     = "3"
    storage_type  = "HDD"
    zone          = "europe-west4-c"
  }
  lifecycle {
    ignore_changes = ["num_nodes"]
  }
}

resource "google_bigtable_app_profile" "bigtable-ah" {
  app_profile_id                = "bigtable-ah-app-profile"
  description                   = "Profile to enable the BigTable app profile"
  provider                      = "google.bigtable"
  instance                      = "${google_bigtable_instance.bigtable-ah.name}"
  project                       = "bolcom-sbx-ah-bigtable-351"
  multi_cluster_routing_use_any = true
}
```
### Expected Behavior

When I remove the replication node bigtable-ah-cluster-replica with a dependency to the app profile it should also remove the app profile

### Actual Behavior

When dropping the second node from the cluster I got the following error:

Error: Error reading AppProfile: googleapi: Error 400: Deleting an app profile will cause all requests using it to fail.

But running the same program again after failing the second node is gone and also the app profile is gone.

How am I able to prevent the error message?

**Comment by venkykuberan** [comment]
Hi @ahuiberts,
  In order to prevent to the error message, you can use 'ignore_warnings' argument. Please find the example below.
``` resource google_bigtable_app_profile "bigtable-ah" {
  app_profile_id                = "bigtable-ah-app-profile"
  description                   = "Profile to enable the BigTable app profile"
#   provider                      = google.bigtable
  instance                      = google_bigtable_instance.bigtable-ah.name
  project                       = var.project_id
  multi_cluster_routing_use_any = true
  ignore_warnings = true
}```

**Comment by RayBB** [comment]
FYI ignore warning is now the default:
https://github.com/googleapis/google-cloud-cpp/pull/2692

**Comment by kevinsi4508** [comment]
I believe this issue should be closed now. "Deleting an app profile will cause all requests using it to fail" warning can be ignored by setting `ignore_warnings` to true (as mentioned above).

**Comment by melinath** [comment]
b/259276194

**Comment by melinath** [comment]
Actually reopening - we should double-check that it is actually resolved.

**Comment by kevinsi4508** [comment]
Sure, I can verify that. It should be a generic thing, but something we did specifically for Cloud Bigtable.

**Comment by kevinsi4508** [comment]
Confirmed:



Case#1 without ignore warning

  + resource "google_bigtable_app_profile" "ap1" {
      + app_profile_id  = "tf-profile-single"
      + id              = (known after apply)
      + ignore_warnings = false
      + instance        = "tf-instance"
      + name            = (known after apply)
      + project         = (known after apply)

      + single_cluster_routing {
          + allow_transactional_writes = true
          + cluster_id                 = "tf-instance-cluster"
        }
    }

tf destroy

│ Error: Error when reading or editing AppProfile: googleapi: Error 400: Deleting an app profile will cause all requests using it to fail.
│ Details:

Case #2 with ignore warning

ignore_warnings = true

tf destroy

# no error message.

**Comment by melinath** [comment]
Closing per investigation
