### ISSUE TITLE
Lost ability to automatically create GKE subnetworks

### ISSUE THREAD

**Issue by abstrctn** [hashicorp/terraform-provider-google#5119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Pre-3.0.0, this provider let you defer the definition a new GKE cluster's primary subnet range to Google, by setting `create_subnetwork` along with a mask size:

```tf
ip_allocation_policy {
  create_subnetwork = true
  node_ipv4_cidr_block = "/25"
}
```

This was particularly useful in projects where multiple GKE clusters shared a network, because each cluster requires finding three IP blocks for the node, service and pod ranges. With the automatic creation, you didn't have to keep track of available IP space yourself.

Since both of these options were removed in #4638, subnetworks have to be created using a `google_compute_subnetwork`, which requires assigning a specific range at create time. (The node and service ranges are still created automatically.)

I understand the motivation of having Terraform be the control plane for the subnetwork as well, but wasn't that already possible with the previous options, simply by setting `subnetwork` to a Terraform-managed `google_compute_subnetwork` resource and `create_subnetwork = false`?

### New or Affected Resource(s)

* google_container_cluster

### References

* #4638

**Comment by spheromak** [comment]
this alone prevents us from using this version of the provider. Where we have multiple state files that control single clusters, and networks are defined in other Terraform runs. Yes we can reference the other state but it changes some scoping with the automation that allows folks to spin up gke clusters via infra pr's. 

I agree that something was lost by removing this setting, and nothing was actually gained other than a bad experience for folks that were using it before this version. :|

**Comment by rileykarson** [comment]
I'm sorry that this change caused a disruption for you both! I'd like to break into a few of the points that have been raised.

> This was particularly useful in projects where multiple GKE clusters shared a network, because each cluster requires finding three IP blocks for the node, service and pod ranges. With the automatic creation, you didn't have to keep track of available IP space yourself.

> Where we have multiple state files that control single clusters, and networks are defined in other Terraform runs. Yes we can reference the other state but it changes some scoping with the automation that allows folks to spin up gke clusters via infra pr's.

In these cases, is it possible to reuse existing subnetworks on the network? GKE nodes are just GCE VM instances, so I don't think that a dedicated subnetwork is often necessary. That's the default behaviour of the Cloud Console, for both the `default` network and custom networks / subnetworks:

![image](https://user-images.githubusercontent.com/2080520/70668513-a7efc680-1c28-11ea-8c2a-b498ab1ee2c9.png)

By doing that along with using the [GKE-managed secondary ranges](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips?hl=en_US&_ga=2.63126184.-621345815.1574102862#range_management)  through `cluster_ipv4_cidr_block` and `services_ipv4_cidr_block`, you'll be back to managing a minimal number of ranges.

In cases where subnetwork-level isolation is important, creating a new subnetwork out of band with the GKE cluster feels appropriate.

> I agree that something was lost by removing this setting, and nothing was actually gained other than a bad experience for folks that were using it before this version. :|

Again, I'm sorry that this is your experience with the change. For what it's worth, I don't believe there were no benefits. In addition to eliminating confusing situations when using Shared VPC, this let us simplify the resource's schema, making configs more explicit/improving plan/improving validation slightly.

---

I'm curious now why automatic range selection is a GKE feature and not part of the subnetwork API directly. I'll look into that.

**Comment by rileykarson** [comment]
Dropping support was an explicit decision and this issue hasn't had much activity, closing as stale.
