### ISSUE TITLE
google_billing_budget does not support last_period_amount

### ISSUE THREAD

**Issue by umairidris** [hashicorp/terraform-provider-google#5245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Feedback from @techisland2k19 in https://github.com/terraform-providers/terraform-provider-google-beta/pull/1428:

> "LastperiodAmount" field doesn't support amount arguement block for terraform google_billing_account resource.Cloud Billing Api doc mention it only. When do you intend to add into resource for terraform?

The reason is in the original PR in magic modules: https://github.com/GoogleCloudPlatform/magic-modules/pull/2734

Specifically @danawillow's comment:

> I don't think we have the capability in Terraform, let alone MM, to have a nested object with nothing inside of it. I'd say let's hold off on allowing people to specify this field, and make specifiedAmount required until the API puts something inside the LastPeriodAmount object.

If there is a workaround I am happy to add it. @danawillow do you have any suggestions?

I can also inquire about when the block will have more values as well internally. If you see the doc in https://cloud.google.com/billing/docs/reference/budget/rest/v1beta1/billingAccounts.budgets#LastPeriodAmount it mentions:

> At this time, the amount is automatically 100% of last period's spend; that is, there are no other options yet. Future configuration will be described here (for example, configuring a percentage of last period's spend).

### New or Affected Resource(s)

* google_billing_budget

### Potential Terraform Configuration

```tf
resource "google_billing_budget" "budget" {
  ...
  amount {
    last_period_amount {}
  }
  ...
}
```

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/2734

**Comment by danawillow** [comment]
The only workaround I can think of would be to add a dummy field (probably a Computed one so that people don't accidentally set it) inside the object that we eventually deprecate. The other option would be to make a boolean instead of a nested block, but that would require a config change for users that eventually migrate from the boolean to the block, so I'm more cautious about something like that.

**Comment by danawillow** [comment]
For what it's worth, we do have precedent for the boolean solution: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_bigtable_app_profile.go#L69

**Comment by nahz** [comment]
I'm looking at adding this functionality at the moment.
Branch is over here: https://github.com/nahz/magic-modules/tree/update-product-billingbudget-amount

Just want to do some more testing before submitting a PR.
