### ISSUE TITLE
Request for datasource google_compute_network_peering

### ISSUE THREAD

**Issue by dylanPowers** [hashicorp/terraform-provider-google#5248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Request for datasource google_compute_network_peering

This is being requested because of a current use case where it is necessary to get details on the network peering that's automatically created with the google_service_networking_connection resource.

### New or Affected Resource(s)

* google_compute_network_peering datasource

### Potential Terraform Configuration

```tf
data "google_compute_network_peering" "example" {
    name = "example"
}
```

**Comment by thesuperzapper** [comment]
This should probably also be an output of `google_service_networking_connection`, for example, it could be `peering_name` which is the name of the peering generated. 

In terms of implementation, the `services.connections/create` API returns a `Connection` object which contains the peering name:
* https://cloud.google.com/service-infrastructure/docs/service-networking/reference/rest/v1/services.connections/create

**Comment by thesuperzapper** [comment]
@danawillow I think the `peering_name` output is a relatively easy addition, and quite important, as it allows people to enable custom route exporting with a `google_compute_network_peering_routes_config`.

**Comment by thesuperzapper** [comment]
@danawillow ok, don't worry, it seems like the `peering_name` is always `servicenetworking-googleapis-com`, perhaps we should just document this, so that users know they can do something like this:

```hcl-terraform
resource "google_service_networking_connection" "google-private-services" {
  network = "XXXXX"
  service = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.google-private-services.name]
}

resource "google_compute_network_peering_routes_config" "google-private-services" {
  project = "XXXXX"
  network = "XXXXX"
  peering = "servicenetworking-googleapis-com"
  import_custom_routes = false
  export_custom_routes = true
}
```

**Comment by fstr** [comment]
It can still be useful to return the `peering_name`s. It's true that it always is `servicenetworking-googleapis-com`. 

But it can also contain more than one peering name:
- Create a private IP range for private services access using `google_compute_global_address`
- Create `google_service_networking_connection`
- Create a Postgres SQL instance using private IP
- Create a MySQL instance using private IP
- You will now have 3 peering names `servicenetworking-googleapis-com`, `cloudsql-mysql-googleapis-com` and `cloudsql-postgres-googleapis-com`
- Destroy only these resources
- Create a private IP range for private services access using `google_compute_global_address`
- Create `google_service_networking_connection`

You will have 3 `peering_name`s right away `servicenetworking-googleapis-com`, `cloudsql-mysql-googleapis-com` and `cloudsql-postgres-googleapis-com`, even though you don't have any MySQL or Postgres instance.

Returning all peering names can help to keep the project consistent, e. g. iterating over them and exporting custom routes.

**Comment by mitj04** [comment]
b/261974304
