### ISSUE TITLE
Control over logging in the provider, ex: add a prefix to every log line

### ISSUE THREAD

**Issue by spew** [hashicorp/terraform-provider-google#5461]
### Affected Resource(s)

* google_*

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be extremely helpful if we could control the output of the logger. For example, we would potentially like to strip certain log lines that contain sensitive information. However, more importantly, it would be helpful if we could add a request ID or the like to each log statement so that we could trace our requests through the system and see what is happening inside the terraform provider. 

So a lot of value would be added with the minimum requirement of being able to add a prefix or suffix to the log.

**Comment by slevenick** [comment]
@paddycarver has thoughts on this

**Comment by paddycarver** [comment]
I think we need some more information about this use case. Who is "we"? What kind of control are you looking for? What's the user experience desired here? There are a lot of ways I can think to implement this, but at the moment, I think we need some more details about what you're looking for and what kind of solution you're envisioning.

**Comment by spew** [comment]
We, https://github.com/GoogleCloudPlatform/k8s-config-connector, are using the terraform library to communicate with GCP. The provider logs to the main log package and does not give us any control over the output. Here are a several things we would like to have the ability to do:

1. Add a request id to each print statement. Our application has many threads (go routines) so it would make debugging much easier if we could tie a terraform provider log statement back to its associated goroutine.
2. Filter the logs, some of the logs are not useful (printing unhelpful polling messages, etc), and sometimes we would like to be able to print the wire request / response logs, but not always.
3. Scrub the logs, some of the time sensitive fields (passwords, etc) are being emitted to the logs. While this is arguably a bug in the provider -- we would like the ability to fix this quicker.

**Comment by paddycarver** [comment]
Hey @spew, I'm a bit confused. What does "the terraform library" mean in this context? [According to the documentation](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html) we don't really support using Terraform or its providers as a library, so I'd love some more information.

**Comment by rileykarson** [comment]
Closing as stale.
