### ISSUE TITLE
Update support for google_container_cluster.addons_config.cloudrun_config

### ISSUE THREAD

**Issue by shaulishaked** [hashicorp/terraform-provider-google#5463]
Hi there,

### Terraform Version
Terraform v0.12.18

### Affected Resource(s)
- google_container_cluster

Can you please add support for enabling Anthos for Cloud Run on a GCP Kubernetes cluster (https://www.terraform.io/docs/providers/google/r/container_cluster.html)?
Currently from what I see this is possible only using a local exec with a kubectl command (https://cloud.google.com/run/docs/gke/enabling-on-existing-clusters).

### References
https://www.terraform.io/docs/providers/google/r/container_cluster.html
https://cloud.google.com/run/docs/gke/enabling-on-existing-clusters

**Comment by edwardmedia** [comment]
@shaulishaked  is this something you are looking for 
https://www.terraform.io/docs/providers/google/r/container_cluster.html#cloudrun_config

**Comment by chrissng** [comment]
@shaulishaked AFAIK, this can be updated in-place. Unfortunately, the docs is not updated to reflect this change.
