### ISSUE TITLE
In a Shared VPC, is it possible to attach a Service Project to a specific Subnet of a Host VPC?

### ISSUE THREAD

**Issue by imranzunzani** [hashicorp/terraform-provider-google#5505]
### Affected Resource(s)

* google_compute_shared_vpc_host_project
* google_compute_shared_vpc_service_project

Based on the documentation here:
https://cloud.google.com/vpc/docs/provisioning-shared-vpc#networkuseratsubnet

Is there a way to pass these configurations when creating a Service Project for a Shared VPC:
![Specific_subnets_shared_vpc](https://user-images.githubusercontent.com/21126414/73194290-462de200-412c-11ea-8e9e-81911259e7e7.jpg)

Could you please point me to the documentation or example for equivalent Terraform Configuration, as I could not find it?
If these parameters are not yet supported, are they planned for a future enhancement?

**Comment by venkykuberan** [comment]
@imranzunzani We can't attach a specific subnet to a service project, they get attached to all the subnets exposed by the Host project.  Currently provider isn't supporting to expose the subnets of a Host project. I will add this issue to feature list to get prioritized and to work on.

Thank you

**Comment by imranzunzani** [comment]
Thank you @venkykuberan

**Comment by danawillow** [comment]
The docs that were linked to in the initial post say that this is accomplished using IAM bindings on the subnetwork, which can already be done with the `google_compute_subnetwork_iam_*` family of resources: https://www.terraform.io/docs/providers/google/r/compute_subnetwork_iam.html.

@imranzunzani, do those accomplish what you're looking for? If not, could you clarify what you're trying to do? There are quite a few knobs in that screenshot so I'm not 100% confident which part of it you're looking for TF support for.

**Comment by imranzunzani** [comment]
@danawillow , 
Taking the reference from:
https://www.terraform.io/docs/providers/google/r/compute_shared_vpc_service_project.html

`resource "google_compute_shared_vpc_service_project" "service1" {
  host_project    = "host-project-id"
  service_project = "service-project-id-1"
}`

I am looking to specify the 'individual subnets' that the service project can access.
Other subnets should not be available/visible to that service project.

Example:

`resource "google_compute_shared_vpc_service_project" "service1" {
  host_project    = "host-project-id"
  service_project = "service-project-id-1"
  subnetworks = [List of allowed subnetworks]
}`

This is needed at the time of attaching the Service Project to the Host Project. So that only the intended subnets are exposed to the Service Project.

Are you saying that I would need to create as many policies as the subnetworks and relevant roles?
Wouldn't the Service Project Owner still be able to see all the subnetworks in the shared VPC, even with that?

**Comment by danawillow** [comment]
Yup, you would do something that looks like this (note- I haven't actually tried it so this is an approximation):
```
resource "google_compute_shared_vpc_service_project" "service1" {
  host_project = "host-project-id"
  service_project = "service-project-id-1"
}

resource "google_subnetwork_iam_binding" "subnet" {
  subnetwork = "path/to/host/subnetwork"
  role = "roles/compute.networkUser"
  members = [
    # list of members from the service project that should become service project admins
  ]

  depends_on = [google_compute_shared_vpc_service_project.service1]
}
```
This makes it so the only users with the compute.networkUser permission on the host subnetwork are the ones you specify. This corresponds to the docs at https://cloud.google.com/vpc/docs/provisioning-shared-vpc#networkuseratsubnet:
> A Shared VPC Admin can assign an IAM member from a service project to be a Service Project Admin with access to only some of the subnets in the host project. This option provides a more granular means to define Service Project Admins by granting them the compute.networkUser role for only some subnets in the host project.

If you take a look at the gcloud tab, this terraform config does the same thing as that except with fewer commands you have to run :)

If you want to be able to add members to the binding without removing ones that are already there, you can also use `google_subnetwork_iam_member`. 

If you want something that you don't have to configure at quite a low level, I'd recommend checking out the project factory module (https://registry.terraform.io/modules/terraform-google-modules/project-factory/google), which has shared vpc support and fewer knobs.

Give one of those a try and let me know how it goes!

**Comment by oleksiypavlenko** [comment]
@danawillow thank you for your suggestion, this did the trick to me.
Only one correction for 2022: 

Resource google_subnetwork_iam_binding is named google_compute_subnetwork_iam_binding in provider v4.12.0.
