### ISSUE TITLE
Add stackdriverLoggingConfig to google_cloud_tasks_queue

### ISSUE THREAD

**Issue by courteouselk** [hashicorp/terraform-provider-google#5544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The REST API of GCP allows to configure `stackdriverLoggingConfig` on a Cloud Task Queue.

See:

- https://cloud.google.com/tasks/docs/reference/rest/v2beta3/projects.locations.queues
- https://cloud.google.com/tasks/docs/reference/rest/v2beta3/projects.locations.queues/create

It would be great if it would be also possible to configure this feature via Terraform.

### New or Affected Resource(s)

* google_cloud_tasks_queue

### Potential Terraform Configuration

```tf
resource "google_cloud_tasks_queue" "default" {
  provider = google-beta

  stackdriver_logging_config {
    sampling_ratio = 0.5
  }
}
```

**Comment by jeet-parekh** [comment]
I'll try this one.

**Comment by jeet-parekh** [comment]
Would like a confirmation before I make any changes. The change has to be made in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/cloudtasks/api.yaml, right?

The `samplingRatio` has to be between 0.0 and 1.0. Is there a way to enforce that through magic modules?
https://cloud.google.com/tasks/docs/reference/rest/v2beta3/projects.locations.queues#stackdriverloggingconfig

**Comment by danawillow** [comment]
@jeet-parekh correct! You'll also probably need to make changes in the corresponding terraform.yaml file. Enforcing the samplingRatio would be done via a validate func; `FloatBetween` should do it. Search MM for "validation" to see how we typically add those.

**Comment by jeet-parekh** [comment]
I couldn't make this work. Please feel free to pick it up. I'll be watching this issue to understand the fix.

**Comment by xylene314** [comment]
I agree to the above point, it would be really if logging can be configured through Terraform
