### ISSUE TITLE
Document import for service networking

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#5575]
It's missing on https://www.terraform.io/docs/providers/google/r/service_networking_connection.html but has import: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_service_networking_connection.go#L22-L24

**Comment by rileykarson** [comment]
Adding bug because KCC folks were unable to import after trying the format in code, `{{network}}:{{service}}`, so we should verify that this is working. We have very few CI logs for this resource, all failures.

**Comment by venkykuberan** [comment]
@rileykarson  I am able to import the resource with the following format with no issues

sample
```terraform import google_service_networking_connection.peering_connection {{peering-network}}:{{servicenetworking.googleapis.com}}```

I will update the doc after synced up with you
