### ISSUE TITLE
Add support for management settings in `google_container_cluster` NAP

### ISSUE THREAD

**Issue by davidquarles** [hashicorp/terraform-provider-google#5579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be amazing if the provider supported the v1 upstream NAP [NodeManagement](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeManagement) fields.  For our use case, I'm not super comfy turning on node autoprovisioning in production without node-autorepair.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "foo" {
  name = "foo"
  # ...
  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.cluster_nodes_service_account.email

      # new field, mirroring google_container_node_pool.management structure
      management {
        auto_repair = true
        auto_upgrade = true
      }
    }
  }
}
```

### References

* #655
* #669

**Comment by davidquarles** [comment]
I contributed the linked PR for this functionality at the `google_container_node_pool` layer back when (and very much appreciated the community vibe over here!) and I'm happy to contribute here as well, assuming it's not a wild amount of additional complexity to do so.

**Comment by danawillow** [comment]
That would be great! I'll assign this issue to you. I imagine it'll be quite similar to the other one.

**Comment by mitj04** [comment]
This issue is to add support for `management` in the `google_container_cluster` NAP. But, this has already been added as part of this [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/6794) which was part of this [issue](https://github.com/hashicorp/terraform-provider-google/issues/9180). Closing this issue please reach out to us in case of any queries.

We can close this [PR](https://github.com/hashicorp/terraform-provider-google/pull/5672) as well which was resolving this issue.

**Comment by mitj04** [comment]
b/263545635
