### ISSUE TITLE
Add support for `upgrade_settings` in `google_container_cluster` NAP

### ISSUE THREAD

**Issue by davidquarles** [hashicorp/terraform-provider-google#5580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The upstream/v1 cluster api now exposes [`upgradeSettings`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/UpgradeSettings) within [`NAP defaults`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AutoprovisioningNodePoolDefaults).  These fields are already supported in the (beta) `google_container_node_pool` resource, and it would be great if exposed them here, too.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "foo" {
  name = "foo"
  # ...
  cluster_autoscaling {
    auto_provisioning_defaults {
      service_account = google_service_account.cluster_nodes_service_account.email

      # new field, mirroring google_container_node_pool.upgrade_settings structure
      upgrade_settings {
        max_surge = "25%"
        max_unavailable = "0"
      }
    }
  }
}
```

### References

* [terraform-providers/terraform-provider-google-beta#2669](https://github.com/terraform-providers/terraform-provider-google-beta/pull/2669)
* https://github.com/terraform-providers/terraform-provider-google-beta/pull/1400
* https://github.com/GoogleCloudPlatform/magic-modules/pull/2669

**Comment by davidquarles** [comment]
I haven't contributed here in ~2 years as I've been in non-GCP environments (I can't adequately express how good it is to be back), so please forgive my ignorance around the new repo structure.  Should I be submitting issues over in magic-modules instead/too?  I'm happy to contribute, if that's helpful.  Thanks!

Also: it seems like `google_container_node_pool.upgrade_settings` can be promoted from the beta provider at this point, if the two repos explicitly map to the upstream APIs (again, forgive my ignorance if not).

**Comment by rileykarson** [comment]
@davidquarles: Either repo is fine to contribute to, the [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules) repo is a little easier for us but a little harder for contributors. Specifically, [the first-time setup is a little annoying](https://github.com/GoogleCloudPlatform/magic-modules#preparing-magic-modules--one-time-setup).

Issues belong here and not against the MM repo.

Yep, `google` maps to GA apis and `google-beta` to beta APIs. If it's moved to GA, moving it to `google` is appropriate.

**Comment by davidquarles** [comment]
This is going to require vendoring / upgrading the google beta api from 0.13.0 to at least 0.14.0, which seemed fairly nontrivial when I attempted.  Is there already any sort of inertia around making that happen?

**Comment by rileykarson** [comment]
It shouldn't be too bad- I believe you can edit the version in the `go.mod` file and run the commands at https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#vendoring-libraries. Are you seeing issues inside the code after the update?

**Comment by rileykarson** [comment]
Oh, looks like we're bumping it in another PR: https://github.com/terraform-providers/terraform-provider-google/pull/5584/files

**Comment by danawillow** [comment]
@davidquarles I'm going to go ahead and put you as the assignee for now, but if you end up deciding not to work on this (or don't think you'll get around to it for a while) feel free to unassign :)

**Comment by jravetch** [comment]
@rileykarson We've found an issue where terraform throws a 404 when trying to enable surge upgrades on a node pool.  The only solution is to recreate the node pool, which properly enables surge upgrades.  Is this due an API incompatibility issue as mentioned here https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades#surge ?  Enabling surge upgrades does work on the console on an existing node pool.  But when changing the settings via terraform, we get a 404.
Here's the 404:
`The requested URL <code>/v1beta1/us-central1/cluster-ci-us-central1-2/gen-g?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>`

**Comment by rileykarson** [comment]
@jravetch mind filing a new issue and filling out the bug template? I just tried modifying the surge settings on a cluster and it worked for me.

**Comment by danawillow** [comment]
https://github.com/terraform-providers/terraform-provider-google/issues/5767 might also be relevant

**Comment by clebio** [comment]
Hello, I believe #9180 resolved this (via GoogleCloudPlatform/magic-modules/pull/6815).
