### ISSUE TITLE
List pagination in sweeper template

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#5633]
### Affected Resource(s)

* google_*

Part of https://github.com/terraform-providers/terraform-provider-google/issues/3288

**Comment by upodroid** [comment]
@c2thorn is this done?

**Comment by c2thorn** [comment]
No, but it isn't something very useful to do at this point. There are changes coming to Magic Modules where we will get this for free.

**Comment by rileykarson** [comment]
Closing this because the issue is fairly sparse, and we're not likely to use it to make decisions. If desirable, let's refile with more context.
