### ISSUE TITLE
data source google_project does not check for space at end of project_id

### ISSUE THREAD

**Issue by themanifold** [hashicorp/terraform-provider-google#5687]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_project` data source does not check for a space at the end of the `project_id` field.

```
data "google_project" "project" {
    project_id="abc "|
}
```
Note the space at the end of the project_id. The error we get back is from the Google API and not from terraform. An example of the debug logs from terraform would be:

```
Google API Request Details:
    ---[ REQUEST ]---------------------------------------
    GET /v1/projects/abc-64358%20?alt=json&prettyPrint=false HTTP/1.1
    Host: cloudresourcemanager.googleapis.com
    User-Agent: google-api-go-client/0.5 HashiCorp Terraform/0.12.20 (+https://www.terraform.io) Terraform Plugin SDK/1.0.0 terraform-provider-google/2.18.1
    X-Goog-Api-Client: gl-go/1.11.0 gdcl/20191007
    Accept-Encoding: gzip

    -----------------------------------------------------
    2020/02/17 10:59:22 [DEBUG] Google API Response Details:
    ---[ RESPONSE ]--------------------------------------
    HTTP/2.0 400 Bad Request
    Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
    Cache-Control: private
    Content-Type: application/json; charset=UTF-8
    Date: Mon, 17 Feb 2020 10:59:24 GMT
    Server: ESF
    Server-Timing: gfet4t7; dur=620
    Vary: Origin
    Vary: X-Origin
    Vary: Referer
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-Xss-Protection: 0
    {
      "error": {
    rraform-provider-google_v2.18.1_x4:     "code": 400,
        "message": "Request contains an invalid argument.",
        "errors": [
          {
            "message": "Request contains an invalid argument.",
            "domain": "global",
            "reason": "badRequest"
          }
        ],
        "status": "INVALID_ARGUMENT"
      }
    }
    -----------------------------------------------------
```
What I expect:

A terraform error to be thrown after validation against the regex. From what I understand, the `google_project` **resource** does validate, see: https://github.com/terraform-providers/terraform-provider-google/issues/1498

### New or Affected Resource(s)

* google_project (data source)

**Comment by gturetsky** [comment]
I was looking for a first issue and found this one.

Looks like the `resourceGoogleProject` `project_id` schema field's `ValidateFunc` ([link](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/resource_google_project.go#L49)) doesn't get copied in the `datasourceSchemaFromResourceSchema` [function](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/datasource_helpers.go#L16). (This has wider implications...)

`datasourceSchemaFromResourceSchema` explicitly only copies these `schema.Schema` keys:
- `Computed`
- `ForceNew`
- `Required`
- `Type`

I can work on this and put in a PR.

**Comment by gturetsky** [comment]
> I was looking for a first issue and found this one.
> 
> Looks like the `resourceGoogleProject` `project_id` schema field's `ValidateFunc` ([link](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/resource_google_project.go#L49)) doesn't get copied in the `datasourceSchemaFromResourceSchema` [function](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/datasource_helpers.go#L16). (This has wider implications...)
> 
> `datasourceSchemaFromResourceSchema` explicitly only copies these `schema.Schema` keys:
> 
> * `Computed`
> * `ForceNew`
> * `Required`
> * `Type`
> 
> I can work on this and put in a PR.

https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/datasource_helpers.go#L12 - Looks like this was intentional...

**Comment by gturetsky** [comment]
> > I was looking for a first issue and found this one.
> > Looks like the `resourceGoogleProject` `project_id` schema field's `ValidateFunc` ([link](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/resource_google_project.go#L49)) doesn't get copied in the `datasourceSchemaFromResourceSchema` [function](https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/datasource_helpers.go#L16). (This has wider implications...)
> > `datasourceSchemaFromResourceSchema` explicitly only copies these `schema.Schema` keys:
> > 
> > * `Computed`
> > * `ForceNew`
> > * `Required`
> > * `Type`
> > 
> > I can work on this and put in a PR.
> 
> https://github.com/hashicorp/terraform-provider-google/blob/fd9dab7d615f8331dfc65d6f898365777e6f1ae5/google/datasource_helpers.go#L12
> 
> - Looks like this was intentional...

@danawillow @sl1pm4t @ndmckinley - Is there a reason why validation func aren't included in the copy?

**Comment by ndmckinley** [comment]
A change in strategy about client-side validation, I think!

Too much client-side validation which falls out of date, and we wind up prohibiting requests that are legitimate - too little and we wind up allowing requests that we should know will fail.  As the size of the provider increased, we found that more and more we were prohibiting valid requests, so we decided to have fewer validators.

This one seems safe!  I'd accept a PR that added the validation function to just this one data source - although since this is generated code, that change should be made at github.com/GoogleCloudPlatform/magic-modules, I think in the third_party directory.

**Comment by danawillow** [comment]
That specific function doesn't copy over validatefuncs, because it sets every single field to "computed", which means it's an output-only field. We don't want to validate those because, similar to what @ndmckinley mentioned, we might accidentally prohibit a valid API response if there was a change in the API between provider versions.

Setting the fields that can be set to either optional or required happens at the bottom of that file, but as you can see it doesn't look at the old schema anymore at that point. My guess is this would be a kind of annoying refactor to do, but you could give it a shot if you wanted.

**Comment by melinath** [comment]
b/237108127
