### ISSUE TITLE
BigQuery dataset data source

### ISSUE THREAD

**Issue by bkms** [hashicorp/terraform-provider-google#5693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I would like to create new BigQuery tables in an existing dataset that is not managed by Terraform. With other resources, I believe I can do this using the Data Source block to 'import' but not directly manage that resource. It would be appreciated if you could create a data source block for BQ datasets.

### New or Affected Resource(s)
We deal with a great many tables and datasets in our enterprise. There are many cases of various different TF scripts/states managing intertwined assets. It would be super helpful if we could manage these BQ assets in Terraform in the above mentioned cases.

* google_bigquery_dataset

### Potential Terraform Configuration
Just like other existing data sources.

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by jamiet-msm** [comment]
Really rather surprised that this doesn't exist. A google_bigquery_table data source would be nice also.

**Comment by tguvdamm** [comment]
Any update on this? The issue is from February last year and would be really good to have.

**Comment by crogers-rhino** [comment]
Would be happy to take a crack at implementing this myself if someone wants to point me in the right direction to get it  approved and planned and whatnot  😄

**Comment by mitj04** [comment]
b/261977395

**Comment by fedemarche** [comment]
update on this ?
