### ISSUE TITLE
`google_iap_tunnel_instance_iam_binding` is not recreated when instance is recreated

### ISSUE THREAD

**Issue by rgolab** [hashicorp/terraform-provider-google#5727]
[issue-type:bug-report]

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.7.0
+ provider.google-beta v3.9.0

### Affected Resource(s)

* google_iap_tunnel_instance_iam_binding

### Terraform Configuration Files

```tf
resource "google_iap_tunnel_instance_iam_binding" "test" {
    instance  = google_compute_instance.test.name
    role      = "roles/iap.tunnelResourceAccessor"
    members   = [
        "group:mygroup@domain.com"
    ]
}
```

### Expected Behavior

When I recreate the `google_compute_instance` the `google_iap_tunnel_instance_iam_binding` should be also recreated. After running `terraform apply` for the changes in the instance I'd like also see information the resource `google_iap_tunnel_instance_iam_binding` will be recreated.

### Actual Behavior

When I recreate the `google_compute_instance` the `google_iap_tunnel_instance_iam_binding` is not changed. When instance is up the tunnel doesn't work so binding is not available. When rerun `terraform apply` I can see changes in the members parameter.

### Steps to Reproduce

1. Create `google_compute_instance` and `google_iap_tunnel_instance_iam_binding`
2. Run `terraform apply`
3. Change eg. instance startup script
4. Rerun `terraform apply`
5. After finish the IAP tunnel will not work and you'll not see binding in the GCP Console
6. Rerun `terraform plan` or `terraform apply`
7. You'll see the changes in the `google_iap_tunnel_instance_iam_binding`

### Workaround (very ugly)

```tf
resource "google_iap_tunnel_instance_iam_binding" "test" {
    provider  = google-beta # use beta provider because condition is not available in the google provider
    instance  = google_compute_instance.test.name
    role      = "roles/iap.tunnelResourceAccessor"
    members   = [
        "group:mygroup@domain.com"
    ]
    # this condition is needed to recreate the binding each time the instance is recreated
    condition {
      title = google_compute_instance.test.instance_id
      expression = "1 == 1"
    }
}

**Comment by rileykarson** [comment]
This is a variant of https://github.com/terraform-providers/terraform-provider-google/issues/2213, caused by https://github.com/hashicorp/terraform/issues/19052. The advice in https://github.com/terraform-providers/terraform-provider-google/issues/2301#issuecomment-434511564 is relevant.

I'm leaving this open since that's what we've done with the other issue.

**Comment by tnguyen14** [comment]
@rileykarson the advice in #2301 is to give the subscription a random-ish name. What is the analogous advice for this issue with iam binding?

**Comment by rileykarson** [comment]
Ah! The instance should be given a name that changes, if possible.

**Comment by DawPawel** [comment]
Any update on this? It has been there for more than 2 years, and we still encounter issues with that (additionally with resource `google_compute_instance_iam_binding` or `google_compute_instance_iam_member`).

**Comment by ScottSuarez** [comment]
Terraform now supports [lifecycle configuration block replace_triggered_by argument](https://github.com/hashicorp/terraform-plugin-sdk/issues/122#issuecomment-1114912583) which should resolve this.
