### ISSUE TITLE
Add resources for Managed Active Directory (Now GA)

### ISSUE THREAD

**Issue by rjerrems** [hashicorp/terraform-provider-google#5731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi Guys, Now that managed AD has gone GA, it would be great to add terraform resources for creating new domain and trusts. Here is the GA announcement and API:

https://cloud.google.com/blog/products/identity-security/managed-service-for-microsoft-active-directory-is-ga
https://cloud.google.com/managed-microsoft-ad/reference/rest/v1/projects.locations.global.domains

### New or Affected Resource(s)

* google_managed_identities_domain
* google_managed_identities_domain_trust

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_managed_identities_domain" "ad" {
  fqdn               = "sandbox.example.local"
  locations          = ["australia-southeast1"]
  authorizedNetworks = ["projects/<project_id>/global/networks/<network_name>"]
  reserved_ip_range  = "10.200.200.0/24"
  labels {
    environment = "sandbox"
  }
}

resource "google_managed_identities_domain_trust" "trust" {
  name                     = google_managed_identities_domain.ad.name
  target_domain_name       = "on-prem.domain.local"
  trust_direction          = "INBOUND"
  trust_handshake_secret   = "supersecret"
  trust_type               = "EXTERNAL"
  target_dns_ip_addresses  = ["10.0.0.1", "10.0.0.2"]
  selective_authentication = true
}

```

**Comment by sumeetoc** [comment]
Hi, wanted to know any initial timeline by when it will be available in Terraform?

Thanks!
