### ISSUE TITLE
Support persistenceIamIdentity for google_redis_instance

### ISSUE THREAD

**Issue by filip-sc** [hashicorp/terraform-provider-google#5784]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please provide an attributes field persistenceIamIdentity for google_redis_instance. Currently there is no way as far as I can see, to access the underlying service account of gcp memstore for redis via terraform. 

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
resource "google_redis_instance" "instance" {
  ...
}

resource "google_storage_bucket_iam_member" "memstore_object_bucket_writer" {
  bucket = "bucket"
  role = "roles/storage.legacyBucketWriter"
  member = "serviceAccount:${google_redis_instance.instance.persistence_iam_identity}"
}
```

### References

* https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#Instance.FIELDS.persistence_iam_identity

**Comment by webervin** [comment]
Not sure if it is worth stand-alone issue or not, but just because persistenceIamIdentity should be rechecked every time as it can change over time, it would be very good to also have a terraform data source for redis memorystore, so we could obtain relevant service account by instance name.

**Comment by upodroid** [comment]
Hi

This value has been added now and should ship with provider version 3.34 which should be released next week.

https://github.com/GoogleCloudPlatform/magic-modules/pull/3805
