### ISSUE TITLE
Address `resource_dataflow_job` drain on batch type jobs

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#5796]
### Affected Resource(s)

* google_dataflow_job

TestAccDataflowJob_withRegion attempts to drain a batch dataflow job. We either need to make this not possible, or explicitly state that setting `on_delete=drain` for batch type jobs will wait for the job to finish on destroy.

b/340204067

**Comment by rileykarson** [comment]
Given "We either need to make this not possible"  marking as a breaking change. Documentation would be possible outside of one of those windows, though.

**Comment by c2thorn** [comment]
closed by service team
