### ISSUE TITLE
data.google_compute_subnet fails silently on missing resource

### ISSUE THREAD

**Issue by damoxc** [hashicorp/terraform-provider-google#5797]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.21
+ provider.google v3.10.0
+ provider.google-beta v3.10.0
+ provider.template v2.1.2

### Affected Resource(s)

* data.google_compute_subnet

### Terraform Configuration Files

```tf
data "google_compute_subnetwork" "subnetwork" {
  name    = var.subnetwork_name <-- incorrect value
  project = local.network_project_id
}
```

### Expected Behavior

An error about not being able to find the subnet should have been raised during plan/apply.

### Actual Behavior

The resource just returned null values resulting in some misleading error messages further down the line.

### Steps to Reproduce

Try and use a data.google_compute_subnet with a subnet name which does not exist.

**Comment by edwardmedia** [comment]
@damoxc I got below error in the debug log when I call `plan` to your config data. It seems to me clear what went wrong. Are you able to see this error? If it is not set to null, what value would be appropriate? Thanks
```
: ---[ RESPONSE ]--------------------------------------
: HTTP/2.0 404 Not Found
: 
: {
:   "error": {
:     "code": 404,
:     "message": "The resource 'projects/myproject/regions/us-central1/subnetworks/incorrect' was not found",
:     "errors": [
:       {
:         "message": "The resource 'projects/myproject/regions/us-central1/subnetworks/incorrect' was not found",
:         "domain": "global",
:         "reason": "notFound"
:       }
:     ]
:   }
: }
```

**Comment by damoxc** [comment]
@edwardmedia for example, assuming that `missing-family` doesn't exist but `some-project` does, using this

```tf
data "google_compute_image" "test_image" {
  family  = "missing-family"
  project = "some-project"
}
```

I receive this during a `terraform refresh`, so it is flagged during a `terraform plan`.
```
Error: error retrieving image information: googleapi: Error 404: The resource 'projects/cb-development/global/images/family/random-family' was not found, notFound

  on test.tf line 1, in data "google_compute_image" "test_image":
   1: data "google_compute_image" "test_image" {
```

I know immediately that the issue is my image family is missing, or I've made a typo. The key part is that this is different behaviourally to the subnetwork data resource, at the very least I'd expect the same behaviour across the provider.

The other problem with `google_compute_subnetwork` aside from the difference in behaviour, is that returning `null`  means it passes as valid configuration during `terraform plan` and you aren't made aware (unless looking closely) that there is a problem until you `terraform apply`.

**Comment by edwardmedia** [comment]
Different behavior. I would call it `enhancement`

**Comment by megan07** [comment]
Hi @damoxc!  Thank you for bringing this to our attention.  After digging into the code, I see that our datasources are inconsistent in general on how we handle these.  After some internal discussion, I think we're going to address this in the next major release when we address other breaking changes.

The approach we discussed is that singular datasources that are not found will return an error, while plural datasources that are not found will return empty.
Thanks!

**Comment by ar-qun** [comment]
Hello everyone,

Are there any updates on this? Just stumbled upon it and couldn't understand what is happening. So this issue is still there with Terraform 1.3.4

**Comment by c2thorn** [comment]
This is within scope of https://github.com/hashicorp/terraform-provider-google/issues/12873
