### ISSUE TITLE
Make VPC-native clusters the default in `google_container_cluster`

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#5842]
This is a breaking change and possibly not worth doing if the user impact is too high.

Many new GKE features rely on clusters being "vpc-native", first-class citizens in GCP VPC networks. Many older clusters are "routes-based", where they communicate over routes instead of through networks. gcloud and the Cloud Console both default to VPC-native, while the REST API defaults to routes-based.

A config like the following is routes-based:

```hcl
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"
  initial_node_count = 1
}
```

vs a VPC-native one:

```hcl
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"
  initial_node_count = 1
  ip_allocation_policy {
    cluster_ipv4_cidr_block = "/16"
	services_ipv4_cidr_block = "/22"
  }
}
```

VPC-native clusters contain additional configuration on top of routes-based ones, and there's no current flag to indicate that a cluster should be routes based. It's difficult to represent VPC-native as the default, especially in a way that will make the upgrade path for our users safe. However, the benefit to our users by flipping the default will be large- clusters cannot move from VPC-native to routes-based or vice-versa, and many features rely on VPC-native clusters.

b/299442842

**Comment by rileykarson** [comment]
Alternatively, safely making Terraform pick up whatever the API default is may be a better alternative.

**Comment by sdmodi** [comment]
This really needs to be fixed. Lots of GKE customers end up with routes based clusters and this is a problem because almost all new features are not supported for routes based clusters.
