### ISSUE TITLE
Add firestore index sweeper (was: Fix TestAccFirestoreIndex_firestoreIndexBasicExample)

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#5862]
TC output:
> Error creating Index: googleapi: Error 409: index already exists

It looks like we need a handwritten sweeper for this resource.

**Comment by ljluestc** [comment]
It appears that you're encountering an error while creating an index using the Google Cloud Search API, specifically an error with a status code of 409 indicating that the index already exists. To address this, you might need to implement a sweeper to handle the resource and the index appropriately. 

However, without the specific context of your code and the technology you're using, I can provide you with some general guidance on how to approach this situation:

1. **Check Existing Index**: Before creating an index, check if it already exists using a suitable API call provided by the Google Cloud Search API.

2. **Conditional Index Creation**: If the index doesn't exist, proceed with creating it. If it does exist, you can either skip the creation process or update the existing index if necessary.

3. **Error Handling**: If you still encounter errors despite these checks, implement error handling and logging to properly diagnose the issue and gather relevant information for troubleshooting.

4. **Manual Sweeper**: If the API doesn't provide a built-in method to clean up existing resources, you might need to implement a sweeper yourself. This involves identifying and deleting any redundant or conflicting indexes.

**Comment by rileykarson** [comment]
@hao-nan-li: Could be a good sweeper candidate.
