### ISSUE TITLE
Placement Policy for Instance Template

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#5863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for `resource_policies` to compute instance template. Support was added for compute instance via https://github.com/terraform-providers/terraform-provider-google/issues/5565 but at the time the API did not support this field on instance templates.

[instanceTemplate](https://cloud.google.com/compute/docs/reference/rest/beta/instanceTemplates)

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/144708037

**Comment by AarshDhokai** [comment]
b/261962116

**Comment by AarshDhokai** [comment]
Seems that the feature is already supported in this [resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template), so closing this issue. Feel free to reach out if there are any concerns.
