### ISSUE TITLE
Add Notification Options to google_bigquery_data_transfer_config

### ISSUE THREAD

**Issue by samhumphreys-2sixty** [hashicorp/terraform-provider-google#5866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current implementation of google_bigquery_data_transfer_config does not have the option for notifications. In GCP both email and PubSub is supported - it would be great if this was added to the resource.

### New or Affected Resource(s)

google_bigquery_data_transfer_config

### References

Documentation can be found here - https://cloud.google.com/bigquery-transfer/docs/transfer-run-notifications?#top_of_page

**Comment by samhumphreys-2sixty** [comment]
@danawillow /other - Is there any update on this?

**Comment by danawillow** [comment]
No updates! If you have a google-side customer engineer, TAM, or similar contact, you can ask them to reach out to our team internally for prioritization.

**Comment by adamcunnington** [comment]
@danawillow is this now resolved?

**Comment by samhumphreys-2sixty** [comment]
Looks like this has been released in [3.37.0](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3370-august-31-2020). This issue can be closed now 👍
