### ISSUE TITLE
Implement GKE Hub Membership

### ISSUE THREAD

**Issue by vmarchaud** [hashicorp/terraform-provider-google#5880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP recently published a "How to" guide to deploy a multi region ingress using GKE Hub feature. I previsouly used `kubemci` (https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress) which works fine. I would like to switch the new way to do it but i already everything with Terraform so i would prefer to wait for the resource for the GKE Hub before continuing on this path

### New or Affected Resource(s)

* google_container_hub
* google_container_hub_membership

### Potential Terraform Configuration

```tf

resource "google_container_cluster" "europe" {
 // ...
}
resource "google_container_cluster" "america" {
 // ...
}
resource "google_container_hub" "my_hub" {
  name = "my_hub"
}
resource "google_container_hub_membership" "europe_membership" {
  cluster = google_container_cluster.europe.self_link
  hub     = google_container_hub.my_hub.name
}
resource "google_container_hub_membership" "america_membership" {
  cluster = google_container_cluster.america.self_link
  hub     = google_container_hub.my_hub.name
}
```

### References

* b/161724911

**Comment by danawillow** [comment]
Unfortunately this product doesn't have public APIs that we can call at the moment, so labeling this upstream until there's something we can call to provision these.

**Comment by bharathkkb** [comment]
+1 for this

**Comment by ndmckinley** [comment]
Note that this is blocked on some upstream-gcp work - The GKE Hub team wants to do a little more work on their end before releasing a terraform integration.  The date that I have for that is ~end of September, plus or minus, so I will hold off on merging this until then.  That said, this is "done", in GoogleCloudPlatform/magic-modules#3923.

**Comment by rileykarson** [comment]
Closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/4600
