### ISSUE TITLE
Move Workload Identity to GA

### ISSUE THREAD

**Issue by uhinze** [hashicorp/terraform-provider-google#5916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Workload Identities are GA (since apparently March 13 https://mobile.twitter.com/whyhiannabelle/status/1238530862494310400). In the TF provider docs, they are still in beta currently (https://www.terraform.io/docs/providers/google/r/container_cluster.html). The feature should be made usable with the default Google provider.

### New or Affected Resource(s)

* google_container_cluster, blocks workload_identity_config and workload_metadata_config
* google_container_node_pool, block workload_metadata_config

**Comment by gleichda** [comment]
Workload identity is now available GA by #6490 🎉 
But when creating I get the issue (both for google_container_cluster 
``` 
Error: "node_config.0.workload_metadata_config": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/guides/provider_versions.html for more details.
```

Can this be also handled in this issue or should I create a new one?

**Comment by gleichda** [comment]
@danawillow any update when this will be done?

**Comment by danawillow** [comment]
Looks like this was done in https://github.com/GoogleCloudPlatform/magic-modules/pull/3580. @ndmckinley, anything else that needs to be done here?

**Comment by danawillow** [comment]
Ah, that one was for identity config, and you're looking for metadata config. That's why that PR didn't cover it, because it's two different fields. Probably best to leave this issue open then, and assign it out soon.
