### ISSUE TITLE
Make change on google_compute_network_peering non destructive

### ISSUE THREAD

**Issue by sdif** [hashicorp/terraform-provider-google#5971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi,
We want to enable `export_custom_routes` on a previously created `google_compute_network_peering` resource but it's a destructive operation when done through Terraform where it is not the case when done through the GCP Web UI.

Here is the output of the Terraform plan:
```
  # google_compute_network_peering.peering-production-data-prod must be replaced
-/+ resource "google_compute_network_peering" "peering-production-data-prod" {
      ~ auto_create_routes   = true -> (known after apply)
      ~ export_custom_routes = false -> true # forces replacement
      ~ id                   = "production-network/peering-production-data-prod" -> (known after apply)
        import_custom_routes = false
        name                 = "peering-production-data-prod"
        network              = "https://www.googleapis.com/compute/v1/projects/***/global/networks/production-network"
        peer_network         = "https://www.googleapis.com/compute/v1/projects/***/global/networks/data-prod-network"
      ~ state                = "ACTIVE" -> (known after apply)
      ~ state_details        = "[2020-03-25T07:38:13.328-07:00]: Connected." -> (known after apply)
    }
```

Is it possible to make this change non destructive ?
Thanks!

### New or Affected Resource(s)

* google_compute_network_peering

### Potential Terraform Configuration

```tf
resource "google_compute_network_peering" "peering-production-data-prod" {
  name         = "peering-production-data-prod"
  network      = google_compute_network.production.self_link
  peer_network = data.google_compute_network.data-prod-network.self_link

  export_custom_routes = true
}
```

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/5007

**Comment by mzaheer** [comment]
Hi is there an update on this issue? Making any changes to export or import custom routes should be a non-destructive operation on the peering connection.

@anGie44 I see you have a pull request in for the change but do we know when we can expect the request to be merged/resolved?

**Comment by rileykarson** [comment]
Internal reference: b/171209909

**Comment by mzaheer** [comment]
Awesome. Thank you guys!
