### ISSUE TITLE
Resync google_container_cluster with tf-conversion

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#5988]
Magician v2 doesn't alert us when handwritten validator files are modified, so GKE has drifted. We need to resync it and make sure all GA fields are expanded.

**Comment by melinath** [comment]
Should we re-triage this now that we're getting validator back in sync more generally?

**Comment by melinath** [comment]
I think this was resolved as part of the update process at the beginning of the year; if not, we should open it as a bug in the terraform-validator repository.
