### ISSUE TITLE
google_monitoring_notification_channel: empty Service name for pagerduty

### ISSUE THREAD

**Issue by vtatarin** [hashicorp/terraform-provider-google#6017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.15.0
+ provider.random v2.2.1

### Affected Resource(s)

google_monitoring_notification_channel

### Terraform Configuration Files

```tf
resource "google_monitoring_notification_channel" "pagerduty_shared_services" {
  display_name = "shared-services-api"
  type         = "pagerduty"
  labels = {
    service_key = MYKEY
  }
}

```

### Debug Output

https://gist.github.com/vtatarin/6f9d2bb2fa8d372e94c41cc28430331f

### Expected Behavior

GCP web UI shows Service name as `shared-services-api`

### Actual Behavior

GCP web UI shows Service name as an empty string. [Screenshot](https://imgur.com/a/Ayv7b2V)

### Steps to Reproduce

1. `terraform apply`

### References

* b/275110864

**Comment by melinath** [comment]
We believe this was due to a temporary outage on the API side that should be resolved. Please let us know if you're still seeing this issue!
