### ISSUE TITLE
Storage bucket object holds

### ISSUE THREAD

**Issue by matthias-froomle** [hashicorp/terraform-provider-google#6022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'm trying to set a hold on a bucket object as documented in the Google docs but I am unable to find information about this in the provider 
docs. 
I'm expecting this either as a block inside the `google_storage_bucket_object` resource or as a separate resource.

### New or Affected Resource(s)

* google_storage_bucket_object / google_storage_bucket_object_hold

### Potential Terraform Configuration

```tf
resource "google_storage_bucket_object" "picture" {
  name   = "butterfly01"
  source = "/images/nature/garden-tiger-moth.jpg"
  bucket = "image-store"

  hold {
    type = "temp" or "event"

  }
}

resource "google_storage_bucket_object_hold" "picture_hold" {
  name   = "picture_hold"
  object = google_storage_bucket_object.picture.self_link 
  type   = "temp" or "event"
}

```

### References

* https://cloud.google.com/storage/docs/holding-objects

**Comment by jaceq** [comment]
Any update on this? It's been almost a year...
