### ISSUE TITLE
google_folders datasource

### ISSUE THREAD

**Issue by sleterrier** [hashicorp/terraform-provider-google#6051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Dynamic lookup of a folder is currently only possible via:
-  [d/google_folder](https://www.terraform.io/docs/providers/google/d/google_folder.html), which requires the name of the folder in the form `{folder_id}` or `folders/{folder_id}`.
- or [d/google_active_folder](https://www.terraform.io/docs/providers/google/d/google_active_folder.html) , which requires the `display_name` and the `parent` (Organization or Folder)

It would be very handy to be able to get a list of folder(s) matching a string filter under a given Organization or Folder as well, in the same manner as [d/google_projects](https://www.terraform.io/docs/providers/google/d/google_projects.html).

### New or Affected Resource(s)

* data source **google_folders**

### Potential Terraform Configuration

```tf
data "google_folders" "my-org-folders" {
  filter = "parent.id:012345678910 lifecycleState:ACTIVE"
}

data "google_folders" "my-subfolders" {
  filter = "parent.id:folders/0123456789 lifecycleState:ACTIVE"
}
```

**Attributes Reference**
The following attributes are exported:
- folders - A list of folders matching the provided filter. Structure is defined below.

The folders block supports:
- folder_id - The folder id of the folder.
- folder_name - The folder name of the folder.

**Comment by imrannayer** [comment]
Is there any update on this?

**Comment by roaks3** [comment]
Appears resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/5437
