### ISSUE TITLE
Add support for BigQuery taxonomies and policy tags

### ISSUE THREAD

**Issue by pietrodn** [hashicorp/terraform-provider-google#6075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be very useful to have the Terraform resources to define the **Taxonomies** and the **Policy Tags** in BigQuery.

Taxonomies and Policy Tags are the entities used to configure column-level security in BigQuery.

Also, it is necessary to define the resources to grant IAM roles to users, groups and Service Accounts on such resources.

### New or Affected Resource(s)

* google_bigquery_taxonomy
* google_bigquery_policy_tag
* google_taxonomy_iam_member
* google_policy_tag_iam_member

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_bigquery_taxonomy" "personal_data_taxonomy" {
  name = "user_personal_data"
  display_name = "User personal data"
  description = "Taxonomy containing access policies for personal data protected by GDPR"
  activatedPolicyTypes = ["FINE_GRAINED_ACCESS_CONTROL"]
}

resource "google_bigquery_policy_tag" "ssn_policy_tag" {
  name = "ssn"
  display_name = "SSN"
  description = "Social Security Number"
  taxonomy = google_bigquery_taxonomy.personal_data_taxonomy.id
  parent_policy_tag = null
}

resource "google_taxonomy_iam_member" "taxonomy_admin" {
  taxonomy = google_bigquery_taxonomy.personal_data_taxonomy.id
  member = "user:pietrodn@example.com"
  role = "roles/datacatalog.policyTagsAdmin"
}

resource "google_policy_tag_iam_member" "ssn_viewer" {
  policy_tag = google_bigquery_policy_tag.ssn_policy_tag
  member = "serviceAccount:worker@example.com"
  role = "roles/datacatalog.policyTagFineGrainedReader"
}
```

### References

* [Introduction to BigQuery Column-level security](https://cloud.google.com/bigquery/docs/column-level-security-intro)
* [Restricting access with BigQuery Column-level security](https://cloud.google.com/bigquery/docs/column-level-security)
* [REST Resource: projects.locations.taxonomies](https://cloud.google.com/data-catalog/docs/reference/rest/v1beta1/projects.locations.taxonomies)
* [REST Resource: projects.locations.taxonomies.policyTags](https://cloud.google.com/data-catalog/docs/reference/rest/v1beta1/projects.locations.taxonomies.policyTags)

**Comment by chrhansen** [comment]
How would it look like when applied to an actual table? [The docs](https://cloud.google.com/bigquery/docs/column-level-security-intro#example_use_case) says that you add tags to a column/field using the schema, but Bigquery table schemas are often inferred (e.g. from a scheduled query) or using a heredoc, so it would be quite dirty to apply a tag to a schema string-interpolating it. Would it be something like this?

``` terraform
resource "google_bigquery_table" "default" {
  dataset_id = google_bigquery_dataset.default.dataset_id
  table_id   = "bar"

  time_partitioning {
    type = "DAY"
  }

  labels = {
    env = "default"
  }

  policy_tags {
    # The below is sort if mimicking the UI-example: 
    # https://cloud.google.com/bigquery/docs/column-level-security-intro#example_use_case.
    # Each field (here `permalink`) must exist in the schema.
    permalink = [google_bigquery_policy_tag.tag1, google_bigquery_policy_tag.tag2]
  }

  schema = <<EOF
[
  {
    "name": "permalink",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The Permalink"
  },
  {
    "name": "state",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "State where the head office is located"
  }
]
EOF

}
```

**Comment by pietrodn** [comment]
I propose to strictly follow Google's API and abstraction model by providing policy tags in the table schema.
It's better to be explicit when setting security and access control policies, after all.

**Comment by pietrodn** [comment]
I like your proposal too! However, is it possible to define blocks with dynamic keys? Maybe it's better to use a map so that it can be generated dynamically.
