### ISSUE TITLE
google_storage_transfer_job add support for Azure storage container source

### ISSUE THREAD

**Issue by bluemalkin** [hashicorp/terraform-provider-google#6224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support for Microsoft Azure Storage container as source is in beta. 

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```
resource "google_storage_transfer_job" "az-storage-container-nightly-backup" {
  description = "Nightly backup of Azure storage container"
  project     = var.project

  transfer_spec {
    object_conditions {
      max_time_elapsed_since_last_modification = "600s"
      exclude_prefixes = [
        "requests.gz",
      ]
    }
    transfer_options {
      delete_objects_unique_in_sink = false
    }
    azure_storage_container_data_source {
      storage_account_name = var.azure_storage_account
      container_name = var.azure_container
      shared_access_signature = var.azure_sas
    }
  }

  schedule {
    schedule_start_date {
      year  = 2018
      month = 10
      day   = 1
    }
    schedule_end_date {
      year  = 2019
      month = 1
      day   = 15
    }
    start_time_of_day {
      hours   = 23
      minutes = 30
      seconds = 0
      nanos   = 0
    }
  }
}
```

**Comment by sanghaniJ** [comment]
b/262189800

**Comment by sanghaniJ** [comment]
- Resource Name

  In Storage Transfer Service, support for the field in resource `google_storage_transfer_job` is requested. 
- Requested Feature

  In the storageTransferJob, TransferSpec contains `AzureBlobStorageData` which needs to be added.
- REST Endpoints

  https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#AzureBlobStorageData
- Highlighting Notes

  The requested feature has already been implemented, has been approved and merged in the [Pull Request](https://github.com/GoogleCloudPlatform/magic-modules/pull/4751).

  Attaching the  [terraform documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#azure_blob_storage_data_source) for the same.
