### ISSUE TITLE
Make node auto-repair default to true

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#6236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

From MSA email:
> we will be enabling Google Kubernetes Engine (GKE) node auto-repair by default in the GKE API for newly created clusters and node pools beginning on May 28, 2020.

Right now the schema around there looks like this:
```
	"management": {
		Type:     schema.TypeList,
		Optional: true,
		Computed: true,
		MaxItems: 1,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"auto_repair": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
				},

				"auto_upgrade": {
					Type:     schema.TypeBool,
					Optional: true,
					Default:  false,
				},
			},
		},
	},
```
So this basically just affects users who set `auto_upgrade` only and let `auto_repair` be the default. We should default `auto_repair` to true in order to match the server-side default.

Users with no `management` block will just get a server-side default. 

### New or Affected Resource(s)

* google_container_node_pool

b/299442391

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8967
