### ISSUE TITLE
google_healthcare_fhir_store resource is missing ability to enable BQ streaming 

### ISSUE THREAD

**Issue by jordan83** [hashicorp/terraform-provider-google#6241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Big query streaming is enabled through a property on the fhir store and it is described here:
https://cloud.google.com/healthcare/docs/how-tos/fhir-bigquery-streaming

The current google_healthcare_fhir_store resource doesn't have the ability to enable this feature:
https://www.terraform.io/docs/providers/google/r/healthcare_fhir_store.html

### New or Affected Resource(s)

* google_healthcare_fhir_store

### Potential Terraform Configuration
```tf
stream_configs {
  bigquery_destination {
     dataset_uri = "bq://BIGQUERY_PROJECT_ID.BIGQUERY_DATASET_ID"
     schema_config = {
       schema_type = "ANALYTICS"
     }
  }
}
```

**Comment by AlfatahB** [comment]
b/263341801

**Comment by AlfatahB** [comment]
I've looked into this issue and it seems like we need to add support for the `stream_configs` field in the `google_healthcare_fhir_store` resource. This field has now been added in the `google_healthcare_fhir_store` resource in the [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/3611). The documentation of `stream_configs` field can be found [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/healthcare_fhir_store.html#stream_configs).

Hence, closing this ticket.
