### ISSUE TITLE
Don't try to modify resources during GCP outage

### ISSUE THREAD

**Issue by thusoy** [hashicorp/terraform-provider-google#6328]
When the Google APIs knowingly doesn't return complete data, terraform shouldn't try to create missing resources as it's likely to compound the effects of an outage.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.24
+ provider.google v3.14.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* google_cloudfunctions_function, probably others

### Expected Behavior

GCP had an issue where it returned an empty response when listing existing cloud functions. `gcloud` is aware of this and reports that something is amiss:
```
$ gcloud functions list
WARNING: The following regions were fully or partially unreachable for query: us-central1, us-east1, us-east4
Listed 0 items.
```

Terraform should use the same signals that `gcloud` uses to detect that the response is not complete and forward that warning to the caller, and not try to recreate the missing resources.

### Actual Behavior

Terraform produced a plan to recreates the missing functions, as if the API request was successful.

### Steps to Reproduce

1. Wait for a partial GCP outage
2. Try to apply a resource based on a partially successful API response

I've tried to repro this several times with debug logging to capture the actual responses, but haven't been successful so far. 

### References

b/274819351

**Comment by venkykuberan** [comment]
We can't take any specific action on this issue today. Its needs to traiged by the team to take a holistic approach. I will move this issue to a different bucket for triaging. 

Can you please attach a debug log of the issue you encountered ?

**Comment by thusoy** [comment]
No, the issue was very flaky so I wasn't able to capture a log.

**Comment by rileykarson** [comment]
I'm gonna close this as obsolete- there's not a great way to detect an outage on our end & engagement has been minimal.
