### ISSUE TITLE
Add ability to Firebase resource to switch to Native Mode

### ISSUE THREAD

**Issue by anthony-johnson** [hashicorp/terraform-provider-google#6352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a new Firebase project using the `google_firebase_project` resource, it would be nice to have the ability to either create the project in Native mode or have the ability to switch from Datastore to Native mode.

Currently, we have to manually do this from the console prior to executing the index creation resource `google_firestore_index`.

### New or Affected Resource(s)

* google_firebase_project

### Potential Terraform Configuration

```
resource "google_firebase_project" "default" {
  provider = google-beta
  project  = google_project.default.project_id
  mode     = "Native"
}
```

### References

No

**Comment by danawillow** [comment]
Hey @anthony-johnson, I don't see any sort of option like that in the [Firebase API](https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects). If you know how to do it using the API, that would help us be able to add that support!

Marking upstream in the meantime.

**Comment by rileykarson** [comment]
Supported as https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_application#database_type
