### ISSUE TITLE
Allow to add backend to cloud armour via annotation 

### ISSUE THREAD

**Issue by gowrisankar22** [hashicorp/terraform-provider-google#6409]
Currently, we create cloud armor rules via terraform and applications(targets) separately. I don't find any other option to add targets to cloud armor rules via automation

Currently, I am doing manually. it is a very pain point for anyone whoever is using helm charts based deployments. proposal is to add a new annotation in the ingress with by passing cloud armour name or via back end config so that it will add to backend automatically 
```
---
   kubernetes.io/ingress.cloudarmor: cloudarmor1
```
Or 

```
beta.cloud.google.com/backend-config: '{"ports": {"8080":"cloudarmor-backendconfig"}}'
```
Example my application:
https://github.com/concourse/concourse-chart/blob/master/values.yaml#L1715-L1733

#6389 for more details

**Comment by danawillow** [comment]
@gowrisankar22, do you know how you would do this using gcloud or the REST API? I'm not clear that this is something we have the capability of doing.

Also, if you wouldn't mind filling out the issue template next time, that would be a big help to our team. Thanks!

**Comment by dotnetpiper** [comment]
Hi Team,

Could you please share an update on this, as i'd also like  to "Apply policy to targets (optional)" using terraform. If it has been implemented than kindly share the way to implement that.
Highly Appreciated!

![image](https://user-images.githubusercontent.com/20516546/120367736-de466780-c32e-11eb-8b33-9a1cbb1344f5.png)

**Comment by rileykarson** [comment]
The original issue here appears to apply to a Kubernetes resource and not to a GCP REST API or Terraform. @dotnetpiper: If what you raised is API functionality Terraform is missing, please file a new issue.
