### ISSUE TITLE
Add more stackdriver service monitoring datasources

### ISSUE THREAD

**Issue by emilymye** [hashicorp/terraform-provider-google#6429]
Add ability to add datasources for:

- [x] cloud endpoints
- [ ] cluster istio (API docs say deprecated but)
- [ ] mesh istio

The actual work of creating datasources is small (see [example](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/data_sources/data_source_monitoring_service_app_engine.go)) but the initial test resources that create the related monitoring services have to be bootstrapped separately

Finishing work from #5058

**Comment by edwardmedia** [comment]
For **mesh istio**. is it **meshUid** for **meshid"?

From https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services
```
JSON representation
--
{   "meshUid": string,   "serviceNamespace": string,   "serviceName": string }
```

From https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
```
meshId | string | The unique identifier for the service mesh All control planes running in the same service mesh should specify the same mesh ID. Mesh ID is used to label telemetry reports for cases where telemetry from multiple meshes is mixed together.
```

**Comment by edwardmedia** [comment]
- [x] cloud endpoints 
has been removed from https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services. Adding that DataSource is out of scope
