### ISSUE TITLE
Memorystore Redis data source

### ISSUE THREAD

**Issue by mchrobak** [hashicorp/terraform-provider-google#6467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be nice to have a data source for Memorystore instances.
https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances/get

### New or Affected Resource(s)

`data.google_redis_instance`

### Potential Terraform Configuration

```tf
data "google_redis_instance" "example_instance" {
  name = "example"
}
```

### References

N/A

**Comment by upodroid** [comment]
@rileykarson 

This already exists. https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/redis_instance

**Comment by rileykarson** [comment]
Done in https://github.com/GoogleCloudPlatform/magic-modules/pull/3623
