### ISSUE TITLE
Enable use of google_iap_client  as a DATASOURCE

### ISSUE THREAD

**Issue by Backstreets** [hashicorp/terraform-provider-google#6482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to be able to use a google_iap_client as a datasource, without having to import it to Terraform.  
The goal is to avoid destroying the iap client if I do a terraform destroy of my infra.
The info obtained from the datasource (oauth2_client_id, oauth2_client_secret, oauth2_client_secret_sha256) is to be used in the iap block of  google_compute_backend_service. 

### Potential Terraform Configuration

```tf
```

### References
https://www.terraform.io/docs/providers/google/r/iap_client.html
https://www.terraform.io/docs/providers/google/r/compute_backend_service.html

Mentioned in:
https://github.com/terraform-providers/terraform-provider-google/issues/6074

We also discussed this briefly in https://github.com/terraform-providers/terraform-provider-google/issues/6074#issuecomment-635506113

**Comment by oswalya** [comment]
This would really be a helpful implementation. 
As long as google does not provide the API to fully automate the oauth2 client configuration, at least with this approach we could reuse the data within our infrastructure automation.

Any news on this so far?

**Comment by hadim** [comment]
I also could benefit from this in case it helps prioritizing.

**Comment by upodroid** [comment]
@rileykarson We can close this issue.

The API doesn't return the oauth client secret and ID for security reasons after it has been created. You'll need to retrieve it from the UI. Therefore, a datasource in terraform will not work.

```
 REDACTED  MCW0CDP3YY  ~  $  http GET https://iap.googleapis.com/v1/projects/550924169191/brands  "Authorization: Bearer $(gcloud auth print-access-token)"
HTTP/1.1 200 OK
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Wed, 20 Jan 2021 22:22:14 GMT
Server: ESF
Transfer-Encoding: chunked
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0

{
    "brands": [
        {
            "applicationTitle": "GitLab",
            "name": "projects/550924169191/brands/550924169191",
            "supportEmail": "REDACTED"
        }
    ]
}
```
