### ISSUE TITLE
[Data Source] bring google_compute_image's `id` field format to match resources'

### ISSUE THREAD

**Issue by edwardmedia** [hashicorp/terraform-provider-google#6513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The output `id` field is **string (fixed64 format)**.  It can't be used to replace **self_link** like the work https://github.com/terraform-providers/terraform-provider-google/issues/5542
 

### New or Affected Resource(s)

* google_compute_image (data source)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
Looks like this matches what we expect: https://github.com/hashicorp/terraform-provider-google-beta/blob/67e7b9523dafe08c4351f6747d2645d8afe77b32/google-beta/services/compute/data_source_google_compute_image.go#L225
