### ISSUE TITLE
Add support for managing Firebase iOS apps

### ISSUE THREAD

**Issue by Pritilender** [hashicorp/terraform-provider-google#6520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Firebase Management API provides methods for managing iOS apps for a Firebase project - [API Docs](https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.iosApps)
It would be very helpful if this could be done via Terraform.

This was firstly mentioned in [the comment](https://github.com/terraform-providers/terraform-provider-google/issues/2973#issuecomment-611773905) on the original Firebase project issue.
But since there hasn't been any new issues regarding it, I'd like to request it via this issue

### New or Affected Resource(s)

* google_firebase_ios_app
* google_firebase_ios_app_config

### Potential Terraform Configuration

```tf
resource "google_firebase_ios_app" "foo" {
    project_id   = "project-foo"
    display_name = "Foo iOS App"
    bundle_id    = "com.bar.foo"
}

data "google_firebase_ios_app_config" "foo" {
    app_id = google_firebase_ios_app.foo.app_id
}
```

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/2973#issuecomment-611773905
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.iosApps
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.iosApps#IosApp
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.iosApps/getConfig

**Comment by cosma** [comment]
any updates on this issue?

**Comment by autumnw** [comment]
This is needed by lots of people, where are we?

**Comment by brownoxford** [comment]
Taking a quick look through magic-modules, this resource *seems* pretty straight forward to auto-generate but I didn't see how to generate the data elements... I'm happy to contribute a PR if anyone can point me in the right direction.

**Comment by brownoxford** [comment]
I am currently working on a PR for this issue, will update when I post the first draft.

**Comment by AlfatahB** [comment]
b/263458101

**Comment by AlfatahB** [comment]
I've looked into this issue, and we need to add support for `google_firebase_apple_app`  resource and `google_firebase_apple_app_config` datasource. The support for `google_firebase_apple_app` has recently been added to the [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/6630). But, `google_firebase_apple_app_config` datasource needs to be supported. Following are the details I've found out:

- **Product Name**: Firebase
- **New Datasource Name**: `google_firebase_apple_app_config`
- **API Docs**: [Firebase iOS App Config](https://firebase.google.com/docs/reference/firebase-management/rest/v1beta1/projects.iosApps/getConfig)
- **Notes**:
    - **REST API Endpoint**:  *GET* - `https://firebase.googleapis.com/v1beta1/{name=projects/*/iosApps/*/config}`
    - Looking at the API endpoints, the new datasource will be `beta-only` datasource.
    - There is a similar datasource, [`google_firebase_web_app_config`](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/data-sources/firebase_web_app_config), to get the configurations of the firebase web application.
    - [This datasource file](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/data_source_google_firebase_web_app_config.go) might be helpful for developing this new datasource.
