### ISSUE TITLE
Add support for managing Firebase Android apps

### ISSUE THREAD

**Issue by Pritilender** [hashicorp/terraform-provider-google#6521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Firebase Management API provides methods for managing Android apps for a Firebase project - [API Docs](https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.androidApps)
It would be very helpful if this could be done via Terraform.

This was firstly mentioned in [the comment](https://github.com/terraform-providers/terraform-provider-google/issues/2973#issuecomment-611773905) on the original Firebase project issue.
But since there hasn't been any new issues regarding it, I'd like to request it via this issue.

### New or Affected Resource(s)

* google_firebase_android_app
* google_firebase_android_app_config

### Potential Terraform Configuration

```tf
resource "google_firebase_android_app" "foo" {
    project_id   = "project-foo"
    display_name = "Foo iOS App"
    package_name = "com.bar.foo"
}

data "google_firebase_android_app_config" "foo" {
    app_id = google_firebase_android_app.foo.app_id
}
```

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/2973#issuecomment-611773905
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.androidApps
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.androidApps#AndroidApp
* https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects.androidApps/getConfig

**Comment by nkt** [comment]
any update on this?

**Comment by cosma** [comment]
hey guys, do you have this in development?

**Comment by autumnw** [comment]
Lots of people needs this, where are we?

**Comment by brownoxford** [comment]
Taking a quick look through magic-modules, this resource *seems* pretty straight forward to auto-generate but I didn't see how to generate the data elements... I'm happy to contribute a PR if anyone can point me in the right direction.

**Comment by brownoxford** [comment]
I am currently working on a PR for this issue, will update when I post the first draft.

**Comment by thomas-vl** [comment]
Any update on this?

**Comment by Bharathkumarraju** [comment]
any update on this @brownoxford

**Comment by brownoxford** [comment]
My apologies - this was pushed aside by other priorities and I have not been able to work on it.

**Comment by c2thorn** [comment]
b/251203893
