### ISSUE TITLE
google_cloudbuild_trigger is missing several arguments

### ISSUE THREAD

**Issue by craigsdickson** [hashicorp/terraform-provider-google#6531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The definition for the build block is missing the following properties when compared to https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#Build :

- source
- queueTtl
- artifacts
- logsBucket
- options
- substitutions
- secrets

### New or Affected Resource(s)

* google_cloudbuild_trigger

### References

* #6040
* #5108
* https://github.com/GoogleCloudPlatform/magic-modules/issues/3576

**Comment by tanjinP** [comment]
@craigsdickson I would like to take this on - just got my local environment working earlier this week for this project.

**Comment by danawillow** [comment]
Thanks @tanjinP! Assigning you now. Make sure you check out the CONTRIBUTING guide since this is a MM-generated resource.

**Comment by viyh** [comment]
+1, the log bucket is critical if all users are not able to be given IAM project-level viewer permissions.
