### ISSUE TITLE
"publisher_service_account" expects value though its not specified in pubsub module being optional field 

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-google#6541]
_This issue was originally opened by @shefaliA as hashicorp/terraform#25155. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Hi,
I am trying to use TF pubsub mofule for creating topic in GCP . I am getting below error when deploying module

Error: Unassigned variable
2020-06-05T18:10:07.8073851Z 
2020-06-05T18:10:07.8074455Z The input variable "publisher_service_account" has not been assigned a value

**Comment by venkykuberan** [comment]
@shefaliA it doesn't seem anything provider related, you aren't passing value to your config. Please pass on your plan output, will see if we can help.

**Comment by melinath** [comment]
closing due to lack of information.
