### ISSUE TITLE
Support GKE's new logging features

### ISSUE THREAD

**Issue by davidxia** [hashicorp/terraform-provider-google#6583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

~GKE `--enable-master-metrics` and `--master-logs` are now beta https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/update#--enable-master-metrics. It would be great to have Terraform support for each as well.~

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
# OUTDATED
enable_master_metrics = true

master_logs = ["APISERVER", "SCHEDULER", "CONTROLLER_MANAGER", "ADDON_MANAGER"]
```

## References

* b/186847999

**Comment by upodroid** [comment]
@danawillow We can close this issue out.

If you are looking to gather logs from system components you can set the following:
```
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1
  cluster_telemetry {
    type = "SYSTEM_ONLY"
   }
}
```
I haven't specified `logging_service` or `monitoring_service` as it is enabled by default and you need GKE version 1.15 or higher.

https://cloud.google.com/stackdriver/docs/solutions/gke/installing#controlling_the_collection_of_application_logs

**Comment by danawillow** [comment]
@upodroid this is a different feature. The one in question isn't actually available yet from what I can tell, so marking upstream.

**Comment by upodroid** [comment]
This is not documented in the SDK docs or in the API Reference 😒 . Looks like it is setting signalsConfig in the master block.

https://cloud.google.com/sdk/docs/release-notes#kubernetes_engine_9
https://cloud.google.com/sdk/gcloud/reference/beta/container/clusters/create
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters

```
 root  DESKTOP-7JUP8RO  mnt  c  Users  REDACTED  USAGE  #  gcloud beta container clusters create test --master-logs APISERVER --enable-master-metrics --log-http
=======================
----------------------
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Newly created clusters and node-pools will have node auto-upgrade enabled by default. This can be disabled using the `--no-enable-autoupgrade` flag.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s).
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
=======================
==== request start ====
uri: https://container.googleapis.com/v1beta1/projects/REDACTED/locations/europe-west2-b/clusters?alt=json
method: POST
== headers start ==
b'Authorization': --- Token Redacted ---
b'accept': b'application/json'
b'accept-encoding': b'gzip, deflate'
b'content-length': b'683'
b'content-type': b'application/json'
b'user-agent': b'google-cloud-sdk gcloud/304.0.0 command/gcloud.beta.container.clusters.create invocation-id/7fca4ca5640d46afaba5458b5c87bb25 environment/None environment-version/None interactive/True from-script/False python/3.8.2 term/xterm-256color (Linux 4.19.104-microsoft-standard)'
== headers end ==
== body start ==
{"cluster": {"master": {"signalsConfig": {"enableMetrics": true, "logEnabledComponents": ["APISERVER"]}}, "name": "test", "nodePools": [{"config": {"oauthScopes": ["https://www.googleapis.com/auth/devstorage.read_only", "https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/monitoring", "https://www.googleapis.com/auth/service.management.readonly", "https://www.googleapis.com/auth/servicecontrol", "https://www.googleapis.com/auth/trace.append"]}, "initialNodeCount": 3, "management": {"autoRepair": true, "autoUpgrade": true}, "name": "default-pool", "upgradeSettings": {"maxSurge": 1}}]}, "parent": "projects/REDACTED/locations/europe-west2-b"}
== body end ==
==== request end ====
---- response start ----
status: 400
-- headers start --
-content-encoding: gzip
alt-svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
cache-control: private
content-length: 127
content-type: application/json; charset=UTF-8
date: Wed, 26 Aug 2020 08:28:44 GMT
server: ESF
transfer-encoding: chunked
vary: Origin, X-Origin, Referer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
-- headers end --
-- body start --
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}

-- body end --
total round trip time (request+response): 0.167 secs
---- response end ----
----------------------
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Request contains an invalid argument.
```

**Comment by danawillow** [comment]
That's why the upstream label is there- waiting for GCP to properly release the feature :)

**Comment by rileykarson** [comment]
The surface of this API has changed, renaming the issue.
