### ISSUE TITLE
Cloud Function: In-place update of source_repository_url fails with message to organizational policies

### ISSUE THREAD

**Issue by jambt** [hashicorp/terraform-provider-google#6603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Updating the URL of a cloud function fails with a remark to org policies. However, deploying both versions is successful.

Org Policies in Place regarding Cloud Functions:
* Allowed ingress settings (Cloud Functions) - constraints/cloudfunctions.allowedIngressSettings
* Allowed VPC Connector egress settings (Cloud Functions) - constraints/cloudfunctions.allowedVpcConnectorEgressSettings
* Require VPC Connector (Cloud Functions) - constraints/cloudfunctions.requireVPCConnector

It seems that none of these Policies should hinder an in-place update. They do not affect a "fresh" deployment.

### Terraform Version
Terraform v0.12.26
+ provider.google v3.26.0

### Affected Resource(s)
* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions_function" "function" {
  name        = var.name
  description = var.description

  runtime               = "python37"
  available_memory_mb   = var.available_memory_mb
  timeout               = var.timeout
  region                = "europe-west3"
  service_account_email = var.service_account_email

  ingress_settings              = "ALLOW_INTERNAL_ONLY"
  vpc_connector                 = var.vpc_connector_id
  vpc_connector_egress_settings = "ALL_TRAFFIC"

  event_trigger {
    event_type = var.event_trigger.event_type
    resource = var.event_trigger.resource
  }

  source_repository {
    url = var.source_repository_url
  }
  entry_point = var.entry_point

  environment_variables = var.environment_variables
}
```

### Debug Output

```
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5: {
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:   "error": {
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:     "code": 400,
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:     "message": "The request has violated one or more Org Policies. Please refer to the respective violations for more information.",
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:     "errors": [
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:       {
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:         "message": "The request has violated one or more Org Policies. Please refer to the respective violations for more information.",
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:         "domain": "global",
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:         "reason": "failedPrecondition"
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:       }
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:     ],
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:     "status": "FAILED_PRECONDITION"
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5:   }
2020-06-16T12:10:57.978+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5: }
```

### Expected Behavior

A new version of the cloud function should be deployed using the new URL.

### Actual Behavior

The request fails with the message `Error: Error while updating cloudfunction configuration: googleapi: Error 400: The request has violated one or more Org Policies. Please refer to the respective violations for more information., failedPrecondition`

### Steps to Reproduce

1. `terraform apply` (success)
2. change url parameter
3. `terraform apply` (fails)
4. `terraform taint xxx.xxx`
5. `terraform apply` (success)

**Comment by venkykuberan** [comment]
@jambt it doesn't seem like a terraform/provider issue. Would you be able to update the CF url in glcoud ?

**Comment by jambt** [comment]
Hi @venkykuberan,

thank you for having a look at this issue. Indeed I am *able* to change the desired URL parameter by issuing

```
gcloud functions deploy tac-ffd-ingress \
--region=europe-west3 \
--entry-point="run" \
--ingress-settings=internal-only \
--runtime=python37 \
--service-account="ingress@<project>.iam.gserviceaccount.com" --source="https://source.developers.google.com/projects/<project>/repos/<repo_name>/moveable-aliases/develop/paths/cloudfunction" \
--timeout=60 \
--vpc-connector="projects/<project>/locations/europe-west3/connectors/<name>" \
--trigger-topic="ingress" \
--set-env-vars=CONFIG_BUCKET_NAME="<bucket>",ERROR_TOPIC="<error_topic>"
```

Which I built copying and pasting the values from the desired terraform plan output (which still fails). The change can also be done using the Cloud Console, so only the provider confronts me with this issue.

Note that due to `retry=false` and `max_instances=0`, I left out the two parameters `--retry` and `max-instances`.

**Comment by emilymye** [comment]
I can't seem to recreate this issue with a function + connector, updating the URL seems to be working fine for me. It might be helpful to see debug logs or the log from the successful gcloud update (`gcloud --log-http ...`) request to see if/how the successful request differs, but it's likely something related to your Org policies that's causing this issue and I'm not sure we have the background with Cloud Functions/org policies to help.

**Comment by jambt** [comment]
I ran both commands in debug mode. There is a clear difference that `gcloud deploy` repeats all parameters while Terraform only gives the parameters that are to be changed (url in this case). 

Please see the output below:
Terraform (output manually formatted for anonymization and better readability):
```
Send Patch CloudFunction Configuration request:
cloudfunctions.CloudFunction{
    AvailableMemoryMb:0,
    Description:"",
    EntryPoint:"",
    EnvironmentVariables:map[string]string(nil),
    EventTrigger:(*cloudfunctions.EventTrigger)(nil),
    HttpsTrigger:(*cloudfunctions.HttpsTrigger)(nil),
    IngressSettings:"",
    Labels:map[string]string(nil),
    MaxInstances:0,
    Name:"projects/<project>/locations/europe-west3/functions/ingress",
    Network:"",
    Runtime:"",
    ServiceAccountEmail:"",
    SourceArchiveUrl:"",
    SourceRepository:(*cloudfunctions.SourceRepository)(0xc000838870),
    SourceUploadUrl:"",
    Status:"",
    Timeout:"",
    UpdateTime:"",
    VersionId:0,
    VpcConnector:"",
    VpcConnectorEgressSettings:"",
    ServerResponse:googleapi.ServerResponse{HTTPStatusCode:0,
    Header:http.Header(nil)
}, ForceSendFields:[]string(nil), NullFields:[]string(nil)}

---[ REQUEST ]---------------------------------------
PATCH /v1/projects/<project>/locations/europe-west3/functions/ingress?alt=json&prettyPrint=false&updateMask=sourceRepository HTTP/1.1
Host: cloudfunctions.googleapis.com
2020-06-22T09:06:45.748+0200 [DEBUG] plugin.terraform-provider-google_v3.26.0_x5: User-Agent: google-api-go-client/0.5 HashiCorp Terraform/0.12.26 (+https://www.terraform.io) Terraform Plugin SDK/1.11.0 terraform-provider-google/3.26.0
Content-Length: 275
Content-Type: application/json
X-Goog-Api-Client: gl-go/1.14.3 gdcl/20200514
Accept-Encoding: gzip

{
    "name": "projects/<project>/locations/europe-west3/functions/ingress",
    "sourceRepository": {
        "url": "https://source.developers.google.com/projects/<project>/repos/<name>/moveable-aliases/develop/paths/cloudfunction"
        }
}

-----------------------------------------------------

Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
.....
```

gcloud
```
==== request start ====
uri: https://cloudfunctions.googleapis.com/v1/projects/dlh-avax-wl-tf-research-9451/locations/europe-west3/functions/tac-ffd-ingress?alt=json&updateMask=entryPoint%2CeventTrigger%2ChttpsTrigger%2CingressSettings%2Cruntime%2CserviceAccountEmail%2CsourceRepository%2Ctimeout%2CvpcConnector
method: PATCH
== headers start ==
Authorization: --- Token Redacted ---
accept: application/json
accept-encoding: gzip, deflate
content-length: 1177
content-type: application/json
user-agent: google-cloud-sdk google-cloud-sdk gcloud/292.0.0 command/gcloud.functions.deploy invocation-id/<id> environment/None environment-version/None interactive/False from-script/False python/2.7.16 term/xterm-256color (Macintosh; Intel Mac OS X 19.5.0)
== headers end ==
== body start ==
{
    "availableMemoryMb": 128,
    "description": "<description>",
    "entryPoint": "run",
    "environmentVariables":
         {"CONFIG_BUCKET_NAME": "<name>",
          "ERROR_TOPIC": "<name>", 
    },
    "eventTrigger": {
        "eventType": "google.pubsub.topic.publish",
        "resource": "projects/<project>/topics/ingress"
     },
    "ingressSettings": "ALLOW_INTERNAL_ONLY",
    "labels": {"deployment-tool": "cli-gcloud"},
    "name": "projects/<project>/locations/europe-west3/functions/ingress",
    "runtime": "python37", 
    "serviceAccountEmail": "<name>.iam.gserviceaccount.com",
    "sourceRepository": {
        "url": "https://source.developers.google.com/projects/<project>/repos/<name>/moveable-aliases/develop/paths/cloudfunction"
    }, 
    "status": "ACTIVE", 
    "timeout": "60s",
    "updateTime": "2020-06-22T07:15:44.802Z",
    "versionId": "3",
    "vpcConnector": "projects/<project>/locations/europe-west3/connectors/<name>",
    "vpcConnectorEgressSettings": "ALL_TRAFFIC"
}
== body end ==
==== request end ====
```


Might the Org Policy 
 * Require VPC Connector (Cloud Functions) - constraints/cloudfunctions.requireVPCConnector

check for the presence of the `vpcConnector` field (which is empty in the `terraform` case)?

Whether this is a bug in the provider or GCP probably depends on the documentation of that `PATCH`-Request.

Do these Information help trying to figure out what is going on here?

**Comment by jambt** [comment]
I opened a [bug ticket with google](https://issuetracker.google.com/issues/159561771). They pointed out that the requests made by the provider is not according to the specification of the [patch call](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions/patch) since the request body should contain a complete [CloudFunction](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction), not just only the updated values.

I suggested to change this behaviour, however, it would be great if the provider would generate a valid request by including all fields alongside the update map. Then this bug would be gone.

**Comment by emilymye** [comment]
I labeled this as an persistent bug to hand off to someone. 

It looks like we'll need to change the update logic to operate more like a regular (non-partial?) update operation, but I don't think I have the time to also confirm that this allows for patching more than one field at a time or other potential weird update behavior, considering this PATCH doesn't work as expected.
