### ISSUE TITLE
Create google_cloudbuild resource

### ISSUE THREAD

**Issue by salrashid123** [hashicorp/terraform-provider-google#6604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Create a new [CloudBuild](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds) resource that allows users to define submit an actual cloud build job.

The existing `google_cloudbuild_trigger` allows a user to create a trigger but theres no way to define a build step and submit the job.

eg, in gcloud cli, you can define and submit a job

- cloudbuild.yaml 
```yaml
steps:
- name: gcr.io/cloud-builders/curl
  id: httpbin
  args: ['-v', 'https://httpbin.org/get']
```

```bash
gcloud builds submit  --config cloudbuild.yaml
```

### New or Affected Resource(s)

* google_cloudbuild

### Potential Terraform Configuration

```hcl
  provider "google" {}

  resource "google_cloudbuild" "test-build" {
    build  {
        step  {
            name = "gcr.io/cloud-builders/gcloud"
            entrypoint = "sh"
            args = ["-c", "echo hi"]
        }
    }  
  }
```

### References

Note, the existing `google_cloudbuild_trigger` includes parsing logic for the `Build` structure in  [resource_cloud_build_trigger](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_cloud_build_trigger.go#L63)

- https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#Build

```
https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers/create
   >>   
 "build": {
    object (Build)
  },
```

which is the `build` structure used while defining and submitting a job
- https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds/create

**Comment by salrashid123** [comment]
i've gotten a very basic sample working [here](https://gist.github.com/salrashid123/3e0855b46339eb4e8d4ffd8c2f03d4ab#gistcomment-3798525) after adding in a new "resource" type to the existing `google_cloudbuild_trigger`.  Basically, resource type will submit a job like this

```hcl
resource "google_cloudbuild_builds" "builder" {
  provider = google-beta-local
  project = var.project_id
  location = "global"

  steps {    
        name = "gcr.io/cloud-builders/gsutil"
        id = "get_source"
        args = ["cp", format("gs://%s/%s", google_storage_bucket.build-bucket.name, google_storage_bucket_object.archive.name), "."]
  }
  steps {    
        name = "gcr.io/cloud-builders/docker"
        id = "buildstep"
        args = ["build", "-t", "gcr.io/$PROJECT_ID/testimage", "."]
        wait_for = ["get_source"]
  }

  images = ["gcr.io/$PROJECT_ID/testimage"]
  
  
  source {
    storage_source {
      bucket = google_storage_bucket.build-bucket.name
      object = google_storage_bucket_object.archive.name
    }
  }
   
}
```

---

however, the usecase i had is really very unique:  i just wanted to create an automated tutorial which creates actual resources (project,vm, etc) and then build some code vial cloud builder andthen deploy it to a VM.  At the moment, i used [local_exec](https://github.com/salrashid123/gcp_tokendistributor/blob/master/alice/build/main.tf#L12) to submit gcloud commands.

in the end, though i submitted this FR, its for this usecase only and i can't think of really any other use for making terraform manage cloud builds (its not a 'resource' terraform should manage). 

If you do have other usecases for this, pls add it to this FR since i'm unsure if this should be kept open after all.

**Comment by melinath** [comment]
Closing this, as it seems to be a job resource.
