### ISSUE TITLE
google_compute_node_types - support new Node Types in node template creation

### ISSUE THREAD

**Issue by mikida12** [hashicorp/terraform-provider-google#6617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today, when creating a new node template through GCP UI dashboard, there are 3 types you can choose from, 2 of which were added just recently: _c2-node-60-240, m1-node-96-1433, n1-node-96-1433_.

In google_compute_node_types there is no option to specify which type will be created, so by default only **c2-node-60-240** type can be created. As I can see here
https://www.terraform.io/docs/providers/google/d/google_compute_node_types.html
, only available arguments are: zone, project.

```
data "google_compute_node_types" "central1b" {
  zone = "us-central1-b"
}

resource "google_compute_node_template" "tmpl" {
  name      = "terraform-test-tmpl"
  region    = "us-central1"
  node_type = data.google_compute_node_types.types.names[0]
}
```

according to google API https://cloud.google.com/compute/docs/reference/rest/v1/nodeTypes looks like we should send the key "cpuPlatform" 

### New or Affected Resource(s)

google_compute_node_types
google_compute_node_template

* google_3.25.0

**Comment by vladimirfaile** [comment]
a must have - for me too

**Comment by megan07** [comment]
Hi @mikida12 and @vladimirfaile!  Thanks for the feature request. I just want to clarify what you're looking for, are you looking for more filter options on the `google_compute_node_types` data source? Similar to the `filter` parameter [here](https://cloud.google.com/compute/docs/reference/rest/v1/nodeTypes/list)?

**Comment by mikida12** [comment]
@megan07 I think so but I don't see an example that could verify this 100%. When I create a node template from GCP console, there are 3 options (c2-node-60-240, m1-node-96-1433, n1-node-96-1433) but I don't see anywhere I can specify this in TF, so it can only create c2-node-60-240 template by default. I can't create a node template for the other 2 machine types - and this is the functionality I am looking for.

Thanks

**Comment by megan07** [comment]
@mikida12 I think there are two examples on how you can do this. One is already possible, the other is what I'm referring to above (we'd have to implement)

Current option (you can hard-code `node_type` to be whatever you'd like)
>resource "google_compute_node_template" "tmpl" {
  name      = "terraform-test-tmpl"
  region    = "us-central1"
  node_type = "n1-node-96-1433"
}

Second option (we'd need to implement)
>data "google_compute_node_types" "central1b" {
  zone = "us-central1-b"
  cpu_platform = "Intel Skylake"
}
resource "google_compute_node_template" "tmpl" {
  name      = "terraform-test-tmpl"
  region    = "us-central1"
  node_type = data.google_compute_node_types.types.names[1]
}

I also want to mention, with your current example, you can index any of `data.google_compute_node_types.types.names`, it doesn't have to just be `0`, in which case, you should be able to get to the other types if you'd like.  But I'd recommend the first option here if there is a specific node type that you're looking for, just in case the order ever changes.

Let me know if this helps at all or if you still have questions. 
Thanks!

**Comment by mikida12** [comment]
Thanks for the detailed answer @megan07 .
I tried 2 approaches, but both failed:
1.  specifying node_type = "n1-node-96-1433" is not working:
`Error: Error creating NodeGroup: googleapi: Error 404: The resource 'projects/solebit-dev/zones/us-central1-c/nodeTypes/n1-node-96-1433' was not found, notFound`
2. when I tried to specify node_type = data.google_compute_node_types.node-zone[0].names[2] -> it is not the order which they appear in the drop-down in GCP console. there are currently 7 options and they will probably add more in the future, so we can not relay on this approach

**Comment by megan07** [comment]
Hi @mikida12!  I took a look - it looks like node-type `n1-node-96-1433` is not available in `us-central1-c`. I'm sure this is documented somewhere, but I did a quick manual lookup in the "Try this API" [here](https://cloud.google.com/compute/docs/reference/rest/v1/nodeTypes/list) specifying the project and zone.
It looks like for `us-central1-c` you can use `n1-node-96-624`, `n1-node-96-624`, or `n2-node-80-640`.

I wouldn't recommend the second way, just wanted to mention it's an option. To be honest, I'm not sure if the order of the list returned by the API is consistent, but if you wanted to test it you could use the link above and see if the order is the same there rather than checking the order of what's listed in the console.

**Comment by megan07** [comment]
Hi @mikida12! Just wanted to follow up and see if you were able to resolve this issue and if we could close it. Thanks!

**Comment by mikida12** [comment]
@megan07 sorry for the (very) late reply. I changed `node_type` to `n1-node-96-624` in that worked. Thanks for the help!

**Comment by megan07** [comment]
@mikida12 - no problem!  i'm glad it's working! thanks for letting me know!
