### ISSUE TITLE
Supporting a wildcard capability so we don't have to explicitly add new services as they become available to google_access_context_manager_service_perimeter

### ISSUE THREAD

**Issue by anubbhavm** [hashicorp/terraform-provider-google#6680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Request to implement a wildcard capability so we don't have to explicitly add new services as they become available. GCP regularly updates the list of restricted services, so this gives the customer an option to avoid appending to the list of restricted services.

### New or Affected Resource(s)
* google_access_context_manager_service_perimeter

### Potential Terraform Configuration

```tf
resource "google_access_context_manager_service_perimeter" "service-perimeter" {
  parent = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}"
  name   = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}/servicePerimeters/perimeter1"
  title  = "new perimeter"

  # The asterisk suggests all the supported services will be restricted.
  status {
    restricted_services = ["*.googleapis.com"]
  }
}
```

b/374161497

**Comment by danawillow** [comment]
This seems more like a feature request for the API itself, rather than for Terraform. If the API supports it then Terraform can do it already, but if not, you should make a request there.

**Comment by ggtisc** [comment]
@anubbhavm are you suggesting a wildcard that represents all the services to be restricted instead of putting each service inside the brackets of the restricted_services? please confirm it or if that is not the case be more specific.

**Comment by Charlesleonius** [comment]
The API does not support this on purpose. There is a new API to list the full set of supported services: https://cloud.google.com/sdk/gcloud/reference/access-context-manager/supported-services/list. You could use this to make sure all services are restricted.

**Comment by Charlesleonius** [comment]
@rileykarson Can we please close this
