### ISSUE TITLE
bigquery slot commitments

### ISSUE THREAD

**Issue by marengaz** [hashicorp/terraform-provider-google#6694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

following the implementation of #5125. please can you also implement bigquery slot commitments and assignments?

### New or Affected Resource(s)

* google_bigquery_slot_commitment
* google_bigquery_reservation_assignment

### Potential Terraform Configuration

```tf
# configuration proposal

resource "google_bigquery_slot_commitment" "my_slot_commitment" {
    id           = (output)
    project       = "my_project"
    location       = "EU"
    slots  = 500
    plan = "MONTHLY"
    renewal_plan = "MONTHLY"
}

# this resource type already exists https://www.terraform.io/docs/providers/google/r/bigquery_reservation.html
resource "google_bigquery_reservation" "my_reservation" {
    name           = "my_reservation"
    project       = "my_project"
    location       = "EU"
    slot_capacity  = 500
    ignore_idle_slots = false
}

resource "google_bigquery_reservation_assignment" "my_reservation_assignment" {
    reservation           = google_bigquery_reservation.my_reservation.id
    assignee           = "projects/myproject"
    job_type             = "QUERY"
}
```

### References

* commitments: https://cloud.google.com/bigquery/docs/reference/reservations/rest/v1/projects.locations.capacityCommitments
* reservations: https://www.terraform.io/docs/providers/google/r/bigquery_reservation.html
* assignments: https://cloud.google.com/bigquery/docs/reference/reservations/rest/v1/projects.locations.reservations.assignments

* b/176106064 (assignments)

**Comment by BenLiyanage** [comment]
Not sure how much is involved in this but I would potentially be interested in helping out--maybe doing one or two of the resources after being shown how to do the first., or at least reviewing the PR.

**Comment by rileykarson** [comment]
@melinath: Unassigning so that this gets picked up next sprint, we'd talked about leaving context on the ticket- do you remember what that was?

**Comment by melinath** [comment]
Ah - I think it's the context I left on the PR. I'll copy it here & clean it up:

- Everything seems to be working on the DCL side.
- On our side, we're getting a permadiff due to location not being explicitly set on the resource (only via the  parent id.) We would ideally ignore this case somehow.
- Also, although it's possible to create resources, we can't delete them, because the id is getting stored wrong - it's using replaceVars. We need to instead use the DCL resource ID() method. Ideally we would start using this method for all DCL resources.

**Comment by melinath** [comment]
@duffenterprises if you have a TAM and you need bigquery slot commitments, to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team

**Comment by rileykarson** [comment]
Just shuffling this around because we finished one of the requested resources & not the other here! The internal issue we were working off of was scoped to assignment.

**Comment by duffenterprises** [comment]
@rileykarson @c2thorn I'm a little confused by all the git merge/re-open, but this is looking like its getting closer. Thanks so much.

**Comment by rileykarson** [comment]
🤦  Just an overeager robot, the final state today will be open. I'll check back in a few minutes when it should be finished.

**Comment by sesidharreddy** [comment]
is this issue really resolved @rileykarson

**Comment by rileykarson** [comment]
Lost track of the tab, sorry. There we go- issue's open, and there's an additional resource before it closes for real. Sorry for the noise/confusion!

**Comment by kyledef** [comment]
Checking in on this as well. I see that in v 4.32.0, there is both `google_bigquery_reservation` and `google_bigquery_reservation_assignment` but there are no configurations for the project slot configuration which is needed before making a reservation.

**Comment by DrFaust92** [comment]
im going to look into adding the capacity commitment resource

**Comment by DrFaust92** [comment]
Q for maintainers.

capacity commitment supports crud technically but if we delete it according to docs:
```
Deletes a capacity commitment. Attempting to delete capacity commitment before its commitmentEndTime will fail with the error code google.rpc.Code.FAILED_PRECONDITION.
```

**Comment by marengaz** [comment]
Docs:
https://cloud.google.com/bigquery/docs/reference/reservations/rest/v1/projects.locations.capacityCommitments/delete

Not a maintainer. As a user, I'd expect to see these errors be passed through to my console and the terraform apply fail. Similar to a permission denied error, I guess?

**Comment by chrisst** [comment]
I did confirm that deleting a capacity commitment before it's time is over will just throw a normal http error and thus will fail the terraform destroy:

```
│ Error: Error when reading or editing CapacityCommitment: googleapi: Error 400: Cannot delete capacity commitment before commitment end time: 2023-02-28T06:55:26.814144+00:00
```
