### ISSUE TITLE
BigQuery - add optional 'require_partition_filter' to range partitioning

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-google#6725]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The 'require_partition_filter' optional field is available only for `time_partitioning`. It's also available for `range_partitioning` but is unsupported by the provider.

Source: https://cloud.google.com/bigquery/docs/creating-integer-range-partitions#creating_an_empty_partitioned_table_with_a_schema_definition

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
resource "google_bigquery_table" "table" {
  dataset_id = google_bigquery_dataset.dataset.dataset_id

  ...

  range_partitioning {
    field = "somefield_id"

    require_partition_filter = true
    range {
      start    = 1577836800
      end      = 1923436800
      interval = 86400
    }
  }
}

```

### References

* [beta#324](https://github.com/terraform-providers/terraform-provider-google-beta/pull/324/files)
* #5723

b/284524821

**Comment by danawillow** [comment]
Looks like the field on time_partitioning is deprecated in the API, but there's a top-level field we can add that should give the same thing: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#timepartitioning

**Comment by obada-ab** [comment]
The top-level `requirePartitionFilter` in the [Table api](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource:-table) is already implemented by magic-modules ([source](https://github.com/GoogleCloudPlatform/magic-modules/blob/80873b61ca146cb71226dc518caee382f3f96e85/mmv1/products/bigquery/Table.yaml#L129C26-L129C26)).

[`rangePartitioning`] (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#rangepartitioning) is not present in magic-modules, but all the fields inside it are "experimental" .

@melinath do you mind taking a look, I'm not sure if there's any action items to do here.

**Comment by melinath** [comment]
@obada-ab it looks like Table.yaml has `exclude_resource: true` set, which means that the resource implementation is not generated from that file. The fact that it has so many fields set in the configuration is a historical artifact - they are not used to generate Terraform. (However, Table.yaml _is_ used to generate the IAM policies for bigquery table.)

The bigquery table resource code lives here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/bigquery/resource_bigquery_table.go

It does have a `range_partitioning` field, which supports all the subfields documented in the API - and `requirePartitionFilter ` is not a documented subfield.

The documentation linked in the initial comment has separate sections for time partitioning and range partitioning that say you can set up "require partition filter" in the console by checking a box; my guess is that the user interpreted that to mean that both blocks have a `requirePartitionFilter` subfield - but actually, checking that box probably sets the top-level `requirePartitionFilter` field that Dana mentioned above.

We should probably treat this as a request to add support for the top-level `requirePartitionFilter` field to the handwritten bigquery table resource.
