### ISSUE TITLE
Add support for GCP PubSub Subscription filter  

### ISSUE THREAD

**Issue by brachipa** [hashicorp/terraform-provider-google#6727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In GCP PubSub there is new feature [filters](https://cloud.google.com/pubsub/docs/filtering?authuser=1&_ga=2.215962064.-657434898.1585215681&_gac=1.241434934.1592902189.EAIaIQobChMIypT34MaX6gIVQeztCh3peQxxEAAYASAAEgIWtvD_BwE)

it will be very helpful if you support it, since it is useful feature in PubSub.
I cab't create the PubSub in TF and then add the filter since the filter can't be set after subscription is created.

### New or Affected Resource(s)

* google_PubSub

### Potential Terraform Configuration

```tf
resource "google_pubsub_topic" "example" {
  name = "example-topic"
}

resource "google_pubsub_subscription" "example" {
  name  = "example-subscription"
  topic = google_pubsub_topic.example.name

  labels = {
    foo = "bar"
  }

  # 20 minutes
  message_retention_duration = "1200s"
  retain_acked_messages      = true

  ack_deadline_seconds = 20

  expiration_policy {
    ttl = "300000.5s"
  }

 filter="attributes:domain"
--


"

}
```

**Comment by tim-codes** [comment]
Looking to contribute to this issue however getting a bit confused by the source code. I can see that the resource is generated by magic modules as it has the "AUTO GENERATED CODE" warning in the source file. However, following the contribution guide and the link to this [repository](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform) I'm unable to find the corresponding code for the pubsub subscription.

**Comment by danawillow** [comment]
@tim-codes the third_party folder only has the non-generated resources. Since pubsub is generated, its definition lives at https://github.com/GoogleCloudPlatform/magic-modules/tree/master/products/pubsub (api.yaml and terraform.yaml). I'd also recommend reading through the README/codelab to get a sense of how to do things in MM, but happy to have you help out with this! Thanks!
