### ISSUE TITLE
Support serverless NEG

### ISSUE THREAD

**Issue by Sytten** [hashicorp/terraform-provider-google#6749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Serverless NEGs are now in open beta: https://cloud.google.com/load-balancing/docs/negs/setting-up-serverless-negs
This means they can now be implemented in the beta provider 🎉 

### New or Affected Resource(s)

* google_compute_serverless_network_endpoint_group

### Potential Terraform Configuration

```tf
resource "google_compute_serverless_network_endpoint_group" "neg_cloud_run" {
  name         = "my-lb-neg"
  region         = "us-central1"
  cloud_run {
    service = "myservicename"
    tag = "revension-0010" # Optional
    url_mask = ".example.com/" # Optional
  }
}

resource "google_compute_serverless_network_endpoint_group" "neg_gae" {
  name         = "my-lb-neg"
  region         = "us-central1"
  app_engine {
    service = "myservicename"
    version = "202007071054" # Optional, default to latest
    url_mask = "-dot-appname.appspot.com/" # Optional
  }
}

resource "google_compute_serverless_network_endpoint_group" "neg_gcf" {
  name         = "my-lb-neg"
  region         = "us-central1"
  cloud_function {
    service = "myservicename"
    version = "202007071054" # Optional, default to latest
    url_mask = "/" # Optional
  }
}
```

### References

*Requires also the fix from #6155 since it also does not support a health check

[API Docs](https://cloud.google.com/compute/docs/reference/rest/beta/networkEndpointGroups/insert#request-body)
[Overview](https://cloud.google.com/load-balancing/docs/negs/serverless-neg-concepts)
[Walkthrough](https://cloud.google.com/load-balancing/docs/negs/setting-up-serverless-negs)

**Comment by Sytten** [comment]
@danawillow I suggest also bumping #6155 to the same level otherwise this improvement is basically useless since you can't use it in the load balancer.

**Comment by danawillow** [comment]
That specific issue is for global NEGs, whereas this one is for regional. Can you explain further what the connection is?

**Comment by Sytten** [comment]
The problem is not related to global vs regional NEG, the problem is that `google_compute_backend_service` requires the parameter `health_checks`. That means that the (future) serverless NEG and the global NEG will not be usable since both not support the health check.

**Comment by danawillow** [comment]
Got it, thanks for the explanation! Will update that one to match this milestone / priority label.

**Comment by brucearctor** [comment]
@Sytten  -- `serverless NEG` and `global NEG` -- not supporting `health_checks` .  Is there a design/choice for the way forward here?  Is it that these services need to support health check?  So the services need modified?  Or, that `google_compute_backend_service` needs to be modified for `health_checks` to be optional?  Or ??  Verifying I understand what has been identified at issue here.  I'm interested in this feature existing, so trying to figure out the extent I capable of helping.

**Comment by Sytten** [comment]
The `google_compute_backend_service` needs to be modified to make the health check optional for sure. Otherwise I don't really more insight into the issue, I just know it is necessary for the serverless NEG to be of any practical use.

**Comment by icco** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/7051
