### ISSUE TITLE
Many documentation pages have broken links/anchors

### ISSUE THREAD

**Issue by preston-hf** [hashicorp/terraform-provider-google#6767]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

https://www.terraform.io/docs/providers/google/r/google_project_iam.html just to start. It seems like most of the pages that offer a selection of related resources that link to an anchor lower on the page have this issue. Notice how https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_member doesn't take you to the right place when you click `google_project_iam_member`. Instead, it should link to https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_member-1 or the ghost anchor it seems to be linking to should be removed. I want to reiterate that this is a much larger issue, someone needs to click through the docs and fix this wherever they find problems. It seems minor but it's a big annoyance having to come in from a Google search and scroll all the way down manually because the anchors are broken, dozens of times per day.

### Expected Behavior

Links should take you to the expected resource type

### Actual Behavior

It takes you to the middle of the page, inexplicably.

### Steps to Reproduce

1. Visit example site above
2. Click one of the resources in the top listing
3. Observe that it doesn't take you where you clicked.

**Comment by megan07** [comment]
Hi @preston-hf ! Sorry for the delay in responding to this - we will be moving our documentation to the terraform registry shortly (https://github.com/hashicorp/terraform-provider-google/issues/7374).  Which will happen once [this](https://github.com/GoogleCloudPlatform/magic-modules/pull/4061) is released, this will not be an issue after that.
Thank you!
