### ISSUE TITLE
google_iam_role return all included_permissions

### ISSUE THREAD

**Issue by bdronneau** [hashicorp/terraform-provider-google#6770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi,

I'm using [data iam_role](https://www.terraform.io/docs/providers/google/d/iam_role.html) in order to get `included_permissions` field and generate a custom role
In fields return, there is some fields flag as `Not applicable for project-level custom roles` or `Not applicable for project-level custom roles`.
Add some filters on the data source will allow more flexibility.

### New or Affected Resource(s)

* data [google_iam_role](https://www.terraform.io/docs/providers/google/d/iam_role.html)

### Potential Terraform Configuration

```tf
data "google_iam_role" "iamRoleViewer" {
  name = "roles/viewer"
  type = "GA"
  level = "org"
}
```

**Comment by upodroid** [comment]
@rileykarson We can close this issue.

The API that this datasource implementes doesn't have a way of requesting the API to only return project/org level permissions.

https://cloud.google.com/iam/docs/reference/rest/v1/roles/get

I recommend you go [here](https://cloud.google.com/support/docs/issue-trackers#feature_requests) and open a feature request with Google to implement this in their APIs. Once that is done, we can implement it in terraform.

**Comment by rileykarson** [comment]
Hmm, that seems right. @bdronneau can you point out a role that contains those messages? I tried `roles/accesscontextmanager.policyEditor` which I believe is org-only and did not see that result.

**Comment by bdronneau** [comment]
Hey @rileykarson ,

I use `roles/viewer` before opening this issue. I try this morning with Compute VIewer from the GCP Web ui (Create role from selection) a permission denied for custom role:
![Screen Shot 2021-01-22 at 10 10 54](https://user-images.githubusercontent.com/4170158/105471219-c97c0800-5c9a-11eb-8a4f-f0662465eb6e.png)

After digging in the link of @rileykarson, in `roles.get` [entry](https://cloud.google.com/iam/docs/reference/rest/v1/organizations.roles#Role), there is a array `includedPermissions` with [permissions](https://cloud.google.com/iam/docs/reference/rest/v1/permissions/queryTestablePermissions#Permission). On this last object,  field `customRolesSupportLevel` can be use for filtering. It's maybe overengineering to get in `data_google_iam_role` a field of all permissions, and a field with custom_role_support permissions.

**Comment by rileykarson** [comment]
Hmm- yeah, I think this would be infeasible to implement. In an example like you've provided Terraform would need to query the API 185 times to determine whether each permission is viable. These requests would need to happen on every single refresh/plan/apply, and would likely quickly burn through quota and cause Terraform to return errors as you hit quota limits.

**Comment by bdronneau** [comment]
Too bad, but I could not agree more.
Thank for your time.
