### ISSUE TITLE
Domain Split Service Endpoints from www.googleapis.com/compute to compute.googleapis.com, storage.googleapis.com etc

### ISSUE THREAD

**Issue by mhanline** [hashicorp/terraform-provider-google#6783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
tf version
Terraform v0.12.28
+ provider.google v3.29.0
+ provider.google-beta v3.29.0
```
### Affected Resource(s)

All compute engine / Google Cloud Storage / bigquery / DNS

### Terraform Configuration Files

This is just an example to show what is called for GCS and networking, but happens to other resources being called as well.
```
provider "google" {
  project     = "your-project-here"
}
resource "google_storage_bucket" "static-files" {
  name          = "bucket-mhan"
  location      = "US"
  force_destroy = true
  bucket_policy_only = true
}
resource "google_compute_network" "vpc" {
  name                    = "net-mh"
  auto_create_subnetworks = false
}
```

### Debug Output

[Gist link](https://gist.github.com/mhanline/a4f30664f5276130db315f3b2b45a4ab)

Pertinent lines:
```
2020-07-13T09:19:18.941+1000 [DEBUG] plugin.terraform-provider-google_v3.29.0_x5: POST /compute/v1/projects/redactedProjectID/global/networks?alt=json HTTP/1.1
2020-07-13T09:19:18.941+1000 [DEBUG] plugin.terraform-provider-google_v3.29.0_x5: Host: www.googleapis.com
```

### Expected Behavior

API Service Endpoint should be:
[compute.googleapis.com](https://cloud.google.com/compute/docs/reference/rest/v1?hl=en)
[storage.googleapis.com](https://cloud.google.com/storage/docs/json_api/v1?hl=en)
dns.googleapis.com
bigquery.googleapis.com

### Actual Behavior

API Service Endpoint used is (for example):
www.googleapis.com/compute/v1
www.googleapis.com/storage/dns
www.googleapis.com/dns/v1
www.googleapis.com/bigquery/v2/
### Steps to Reproduce

1. `terraform apply`

### References

* [Compute Engine API Reference ](https://cloud.google.com/compute/docs/reference/rest/v1?hl=en)- Uses compute.googleapis.com for its service endpoint
* [Storage API Reference](https://cloud.google.com/storage/docs/json_api/v1?hl=en)
* go/domain-split

**Comment by edwardmedia** [comment]
@mhanline Are the resources created correctly? If not, could you please provide sample configs?

**Comment by edwardmedia** [comment]
I see the differences of the endpoints between used and the suggested by APIs

**Comment by danawillow** [comment]
Cool, this is easy enough to change. @mhanline, since the provider is versioned and people can upgrade as they please, you might still see requests come in for the legacy endpoints long after we make the change on our end. Is that going to be ok?

**Comment by danawillow** [comment]
another question @mhanline: I noticed deployment manager isn't on your list, and that seems to still recommend the www.googleapis.com endpoint in its docs. Should I leave that alone?

**Comment by mhanline** [comment]
> since the provider is versioned and people can upgrade as they please, you might still see requests come in for the legacy endpoints long after we make the change on our end. Is that going to be ok?

I'm not the authority on domain split, but I don't see this as being an issue.

> another question @mhanline: I noticed deployment manager isn't on your list, and that seems to still recommend the [www.googleapis.com](http://www.googleapis.com) endpoint in its docs. Should I leave that alone?

Yes, I would keep as-is until the docs say otherwise. There are some exceptions that are being worked on such as this one, but getting as many onto the new endpoints as possible should be the way to go.
