### ISSUE TITLE
Dynamically create google_compute_instance nat_ip

### ISSUE THREAD

**Issue by joe-boyce** [hashicorp/terraform-provider-google#6810]
We are currently using modules across the board to ease the use of terraform for many customers, one of the pain points at the moment is the use of external IPs being assigned to instances

We currently have the following configuration in place:

```
network_interface {
    network = var.network
    subnetwork_project = var.subnetwork_project
    subnetwork  = var.subnetwork
    network_ip     = length(var.address) > 0 ? element(concat(var.address, list("")), count.index) : ""

    access_config {
        nat_ip = length(var.external_ip) > 0 ? element(concat(var.external_ip, list("")), count.index) : ""
    }
  }
```

This works by either allowing the user to provide a static external IP for each instance or if left blank will assign a dynamic external IP

Following on from the following case: https://github.com/terraform-providers/terraform-provider-google/issues/2712

Are you able to provide a working example of how to conditionally or dynamically use the access_config {} block so that if no external IP is required this can be done using the same module

Thanks,

Joe

**Comment by edwardmedia** [comment]
@joe-boyce can you see if below code works for you?
```tf
resource "google_compute_instance" "default" {
  name         = "issue6810demo"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"
  tags = ["foo", "bar"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  // Local SSD disk
  scratch_disk {
    interface = "SCSI"
  }
  network_interface {
    network = "default"
    dynamic "access_config" {
       for_each = var.natip == ""? [] : [1]
       content {
         nat_ip = var.natip
       }
    }
  }
  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}
variable "natip" {
  default = "35.222.xxx.xxx"
}
```

**Comment by edwardmedia** [comment]
@joe-boyce does above code work for you?

**Comment by joe-boyce** [comment]
Thanks for the response @edwardmedia, how does this work in terms of within a module thats using count for x instances, as your example only seems to work with a single instance being created

As mentioned above the code is currently:

module main.tf:
```access_config {
        nat_ip = length(var.external_ip) > 0 ? element(concat(var.external_ip, list("")), count.index) : ""
    }
```

module variables.tf
```variable "external_ip" {
  type        = list(string)
  default     = []
}
```

Resources being created via module:
```module "example" {
    source             = "git@github.com:path/to/module.git?ref=v1.0"
    project            = var.project
    instance_count     = 2
    name               = ["instance-2", "instance-2"]
    zones              = ["us-central1a", "us-central1b"]
    address            = ["10.x.x.1", "10.x.x.2"]
    external_ip        = ["35.222.xxx.1", "35.222.xxx.2"]
}
```

As mentioned if external_ip is not provided above the resources would be created with an ephemeral set

Thanks,

Joe

**Comment by edwardmedia** [comment]
@joe-boyce I was thinking of something like below code which can create multiple instances. You can notice their `natip` for each instance. 

```tf
# main.tf
variable "vms" {
    type = map(string)
    default = {
        vm1 = "35.223.xxx.xxx"
        vm2 = ""
    }
}
module "servers" {
    source = "./modules/vm"
    for_each = var.vms
    natip = each.value 
    name = each.key
}
```
```tf 
# modules/vm/main.tf
resource "google_compute_instance" "default" {
  name         = var.name
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"
  tags = ["foo", "bar"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  // Local SSD disk
  scratch_disk {
    interface = "SCSI"
  }
  network_interface {
    network = "default"
     dynamic "access_config" {
       for_each = var.natip == ""? [] : [1]
       content {
         nat_ip = var.natip
       }
    }
  }
  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}
```
```tf
# modules/vm/variables.tf
variable "natip" {
 type = "string" 
}
variable "name" {
  type = "string" 
}
```

**Comment by joe-boyce** [comment]
@edwardmedia I haven't tried the new example but when you say "provide yours, or let GCP provides", does this cater for not having an external IP at all, as that is the main purpose of the ticket to provide all 3 variations

Thanks,

Joe

**Comment by edwardmedia** [comment]
@joe-boyce if the suggestions are not good enough to meet your use case, I would recommend you post the question  at discuss.hashicorp.com as the solutions would be more Terraform, not the Provider specific. I am closing this issue then. Feel free to reopen it if you think needing assistance for the provider. Thank you
