### ISSUE TITLE
Validate function does not fail during plan or apply

### ISSUE THREAD

**Issue by devendradk** [hashicorp/terraform-provider-google#6872]
`Non working:`
https://github.com/terraform-providers/terraform-provider-google/blob/38aa8fadac5b6ea813308e6364581dd52a62e21b/google/resource_compute_address.go#L48

`Working:`
https://github.com/terraform-providers/terraform-provider-google/blob/38aa8fadac5b6ea813308e6364581dd52a62e21b/google/resource_compute_firewall.go#L84

`Terraform Version`
v0.12.0

`Terraform Configuration Files`

resource_compute_address was added with name which does not match validation criteria . I.e. name shouldn’t start with numbers or name should not be longer than 63.

This will trigger the ValidateFunc:

name           = "123-allow-trusted"
This will not trigger the ValidateFunc:

`Expected Behavior`
The ValidateFunc from the schema should be run with regular expression and give errors. 
"name" ("123-allow-trusted") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"

`Actual Behavior`
ValidateFunc runs without error message.

`Steps to Reproduce`
Create resource_compute_address config with a value that should fail validation
terraform plan

**Comment by edwardmedia** [comment]
@devendradk I can't repro the issue. Can you post your test configs? Thank you

**Comment by edwardmedia** [comment]
@devendradk is this still an issue with you?

**Comment by edwardmedia** [comment]
@devendradk I am closing this issue as I have not heard back from you. Please feel free to reopen it if this is still an issue
