### ISSUE TITLE
`google_bigquery_job` does not execute

### ISSUE THREAD

**Issue by dboshardy** [hashicorp/terraform-provider-google#6875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_bigquery_job

### Terraform Configuration Files (if applicable)

```bash
$ terraform --version
Terraform v0.12.26
Your version of Terraform is out of date! The latest version
is 0.12.29. You can update by downloading from https://www.terraform.io/downloads.html
```

```tf
resource "google_bigquery_job" "job" {
 job_id = "job_query"
 query {
 use_legacy_sql = false
 query = <<EOT
 DELETE FROM `${local.project}.${google_bigquery_dataset.dataset.dataset_id}.${google_bigquery_table.metrics.table_id}`
 WHERE ...
EOT

 }
 
}
```

### Issue Description
When creating a query job with no destination, the terraform plan and apply creates the job according to tf log output, but the jobs never show up in the project or personal job history in the BQ UI.

**Comment by edwardmedia** [comment]
@dboshardy could you post your full debug log?

**Comment by dboshardy** [comment]
I can't post our full log ,but looking at the debug trace, the google api returns a 200 response but the response contains this:

```
   "status": {
     "errorResult": {
       "reason": "invalidQuery",
       "location": "query",
       "message": "1.19 - 6.41: Unrecognized token DELETE.\n[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling
-standard-sql)]"
```

So there's two issues. Looking at the debug trace, while the plan shows `use_legacy_sql = false` the create job request doesn't have any `useLegacySql` property in the `configuration` object.  

Despite the 200 response, IMO this should return an error that the job creation was not successful due to the presence of the `errorResult` object.  Additionally, it looks like the provider isn't adhering to the resource specified at least with regards to `use_legacy_sql`.  It looks like the generated tests don't test for legacy sql setting.

**Comment by dboshardy** [comment]
It looks like I'm not the first to encounter the `use_legacy_sql` bug, as this issue was closed without resolution in April:
https://github.com/terraform-providers/terraform-provider-google/issues/6231

**Comment by dboshardy** [comment]
It looks like this line is the culprit [0].  That will always return true for a false boolean value.  That means this statement[1] always evaluates to false:

[0]https://github.com/terraform-providers/terraform-provider-google/blob/master/google/transport.go#L29
[1]https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_big_query_job.go#L1867

**Comment by edwardmedia** [comment]
@dboshardy can you create a job without a destination using a different way? If you can, could you post the steps? Thank you

**Comment by dboshardy** [comment]
Yes, if you use `use_legacy_sql = true` or left unspecified (default is true), and use a valid legacy sql query, it works.  If you use a standard sql query, and `use_legacy_sql = false` the legacy sql setting is not honored. When applying, you get an error in the debug level, but not in info. The resource says it was created successfully, but it in fact errorred and was not created. As per my response earlier, debug logs show the job creation request returned a 200 but the response body had a a list of errors that meant the job was not created.  

So this is, in fact, 2 issues:

1. The `use_legacy_sql` parameter is not honored in the actual job creation just like #6231 points out. And what [0] specifies as the cause.
2. Job creation can fail but is treated as a success by terraform. 

I would expect that if there was an error creating the BQ Job, the terraform resource creation should fail.

[0] https://github.com/terraform-providers/terraform-provider-google/issues/6875#issuecomment-665911879

**Comment by dboshardy** [comment]
I have a fork that fixes these issues [0]. However, it opens up some more issues, primarily:

1. DML statements cannot have a `create_disposition` or `write_disposition` set which is always set by default to the default values, `CREATE_NEVER`, `WRITE_EMPTY`.  

[0] https://github.com/dboshardy/terraform-provider-google

**Comment by dboshardy** [comment]
After investigating, specifying `create_disposition = ""` and `write_disposition = ""` will properly create DML query jobs.  My fork contains a change to docs to note this.

Shall I create a PR with my fork? @ndmckinley
