### ISSUE TITLE
google_compute_instance > boot_disk > auto_delete update should not force replacement

### ISSUE THREAD

**Issue by mrzor** [hashicorp/terraform-provider-google#6892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

~~~
Terraform v0.12.29
+ provider.google v3.30.0
+ provider.google-beta v3.30.0
~~~

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "main" {
  project             = google_project.main.project_id
  name                = local.xxx_instance_name
  machine_type        = var.xxx_instance_machine_type
  zone                = var.xxx_instance_zone
  deletion_protection = true

  boot_disk {
    source      = google_compute_disk.main_instance_boot_drive.name
    auto_delete = false
  }

  network_interface {
    # snip
  }

  service_account {
    # snip
  }

  scheduling {
    # snip
  }

  guest_accelerator {
    # snip
  }

  # snip depends_on = [ ... ]
}
```

### Expected Behavior

~~~
      ~ boot_disk {
          ~ auto_delete                = true -> false
~~~

### Actual Behavior

~~~
      ~ boot_disk {
          ~ auto_delete                = true -> false # forces replacement
~~~

### Steps to Reproduce

1. Import an instance
2. Change the auto_delete value of its boot disk
3. `terraform apply` or `terraform plan` : notice overeager attempt to recreate instance

### References

* [SDK gcloud compute instances set-disk-auto-delete](https://cloud.google.com/sdk/gcloud/reference/compute/instances/set-disk-auto-delete)
* [rest/v1/instances/setDiskAutoDelete](https://cloud.google.com/compute/docs/reference/rest/v1/instances/setDiskAutoDelete)

b/374162426

**Comment by rileykarson** [comment]
This probably makes sense to fix as part of https://github.com/terraform-providers/terraform-provider-google/issues/6857

**Comment by rwblokzijl** [comment]
Is there an update on this? Not being able to change this is a killer if you want to redeploy the machine without wiping the boot-disk.

**Comment by fuog** [comment]
also had problems while moving from standard VM to Spot VM .. spot-VMs forces you to recreate the vm. This is how I first noticed the problem. all our VMs had this feature turned on by default.

**Comment by philip-harvey** [comment]
Any chance to get this assigned?

**Comment by ggtisc** [comment]
Currently if you add the `deletion_protection` argument or change its value results in an `update-in-place` instead of `force-replacement`

**Comment by karolgorc** [comment]
This seems like a copy of https://github.com/hashicorp/terraform-provider-google/issues/14707

Will add it to related in PR
