### ISSUE TITLE
Documentation: attribute values instead of value for node_affinities block

### ISSUE THREAD

**Issue by dlorch** [hashicorp/terraform-provider-google#6919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26

### Affected Resource(s)

* Documentation: terraform-provider-google/website/docs/r/compute_instance_template.html.markdown 

```
The node_affinities block supports:

    key (Required) - The key for the node affinity label.

    operator (Required) - The operator. Can be IN for node-affinities or NOT_IN for anti-affinities.

    value (Required) - The values for the node affinity label.
```

### Actual Behavior

In the `node_affinities` block, the attribute is `values` (plural) and not `value`.

**Comment by c2thorn** [comment]
Closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/3869
