### ISSUE TITLE
Schema update for bigquery table

### ISSUE THREAD

**Issue by alexandre-cruel** [hashicorp/terraform-provider-google#6931]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to create bigquery tables via terraform.
The tables I plan to create are partitionned tables (i.e. requires a schema by default).
This schema will potentially change in the future if I need to add some columns to my table.
The data stored in the table isnt easy to reload and shouldnt be erased in production.
Though it looks like updating the schema will completely recreate the table as mentionned [here](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema-1).

From what google says [here ](https://github.com/terraform-google-modules/terraform-google-bigquery/issues/87): it's not possible to do such  thing. 
I think this feature would really help creating the tables by IaC while being stil dynamic in there use.
Thank you for the help and clarification

### New or Affected Resource(s)

* google_bigquery_table

### References

* [Link to the tf documentation](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema-1)
* [Link to google's issue question](https://github.com/terraform-google-modules/terraform-google-bigquery/issues/87)

**Comment by c2thorn** [comment]
Hi @alexandre-cruel, just wanted to get some clarification. There are two `schema` fields in the resource. The `external_data_configuration.schema` field you linked to is within the `external_data_configuration` block, and looks like it is only used during table creation.

However there is the standard `schema` field [here](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema) that is updatable without destroying the table. Is this suitable for you?

**Comment by alexandre-cruel** [comment]
In the use case I'm working on this isnt for external_data_configuration, it was for tables with data directly living on bigquery but according to the documentation I thaught it was the same for the 2 schema parameters.

Totally suitable yes, if you're sure that updating the schema to add a column wont delete the table and erase the dat, that'd be perfect 👍 !

**Comment by c2thorn** [comment]
That makes sense! It can be slightly confusing, and we are working on a UI update that should hopefully make it easier to differentiate between the two schema parameters.

I cannot guarantee how the API will behave when the provider calls update, but I can say that Terraform will not try to destroy/recreate the table while updating the top-level schema field. To fully make sure, I recommend testing out your scenario first. If the provider is behaving differently than expected, feel free to comment here!

**Comment by alexandre-cruel** [comment]
Great, thank you for your investigation time and help !
