### ISSUE TITLE
Remote-exec provisioner doesn't work with gcp vm

### ISSUE THREAD

**Issue by Shriyut** [hashicorp/terraform-provider-google#6932]
I'm trying to use remote-exec provisioner for a use-case related to my project on GCP using Terraform version 12, based on the format specified in terraform docs I get a known hosts key mismatch error after the provisioner timesout.

`resource "google_compute_instance" "secondvm" {
    name = "secondvm"
    machine_type = "n1-standard-1"
    zone = "us-central1-a"
 boot_disk {
            initialize_params {
                    image = "centos-7-v20190905"
            }
    }

    network_interface {
            network = "default"

            access_config {
            nat_ip = google_compute_address.second.address
            network_tier = "PREMIUM"
    }

    }

    #metadata = {
#ssh-keys = "root:${file("~/.ssh/id_rsa.pub")}"
#}

    metadata_startup_script = "cd /; touch makefile.txt; sudo echo \"string xyz bgv\" >>./makefile.txt"

    provisioner "remote-exec" {

    inline = [
            "sudo sed -i 's/xyz/google_compute_address.first.address/gI' /makefile.txt"
    ]

    connection {
            type = "ssh"
            #port = 22
            host = self.network_interface[0].access_config[0].nat_ip
            user = "root"
            timeout = "120s"
            #agent = false
            private_key = file("~/.ssh/id_rsa")
            #host_key = file("~/.ssh/google_compute_engine.pub")
            host_key = file("~/.ssh/id_rsa.pub")
    }
}

    depends_on = [google_compute_address.second]
}`

I'm not sure what exactly I'm doing wrong with the keys here but the error I get is

`google_compute_instance.secondvm: Still creating... [2m10s elapsed]
google_compute_instance.secondvm (remote-exec): Connecting to remote host via SSH...
google_compute_instance.secondvm (remote-exec):   Host: 104.155.186.128
google_compute_instance.secondvm (remote-exec):   User: root
google_compute_instance.secondvm (remote-exec):   Password: false
google_compute_instance.secondvm (remote-exec):   Private key: true
google_compute_instance.secondvm (remote-exec):   Certificate: false
google_compute_instance.secondvm (remote-exec):   SSH Agent: false
google_compute_instance.secondvm (remote-exec):   Checking Host Key: true
google_compute_instance.secondvm: Still creating... [2m20s elapsed]

Error: timeout - last error: SSH authentication failed (root@104.155.186.128:22): ssh: handshake failed: knownhosts: key mismatch`

**Comment by edwardmedia** [comment]
@Shriyut can you explain a little more detail about what exactly you want to achieve?

**Comment by Shriyut** [comment]
@edwardmedia i was trying to learn about remote exec provisioner and wanted to check if i could make configuration changes on some files on the VM.
Eg: Say i need the value of sonarqube vm's ip to change it in the plugin xml file in jenkins directory that keeps the ip of sonarqube.
But the main issue I have here is I can't even connect the host with remote-exec provisioner

**Comment by edwardmedia** [comment]
@Shriyut `remote-exec` is a Terraform feature. Below is the link to its document. `terraform-provider-google` does not own that feature. You might want to ask a question at https://github.com/hashicorp/terraform/issues. I am closing this issue. Please feel free to reopen it if you have questions specific to the provider. Thanks

https://www.terraform.io/docs/provisioners/remote-exec.html
