### ISSUE TITLE
Invalid resource type "google_cloud_asset_organization_feed"

### ISSUE THREAD

**Issue by jgireeshj** [hashicorp/terraform-provider-google#6938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.29
+ provider.google v3.27.0
+ provider.google-beta v3.33.0

### Affected Resource(s)

* google_cloud_asset_organization_feed
* google_pubsub_topic
* google_pubsub_topic_iam_member

### Terraform Configuration Files

I was using the example code  --> **_Example Usage - Cloud Asset Organization Feed_**
**

**https://www.terraform.io/docs/providers/google/r/cloud_asset_organization_feed.html**

**

### Debug Output

Error: Invalid resource type

  on test_assets_monitoring.tf line 7, in resource "google_cloud_asset_organization_feed" "default":
   7: resource "google_cloud_asset_organization_feed" "default" {

**Comment by edwardmedia** [comment]
@jgireeshj I can't repro your issue. There is a daily test using the example and it works fine. It seems your code is not exact same as the example. Could you post your config and full debug log? Also what roles (permissions) does the Terraform runner has?

**Comment by jgireeshj** [comment]
@edwardmedia please find the below code I am using:

provider "google-beta" {  
  project  = "my-project-name" 
}

# Create a feed that sends notifications about network resource updates.
resource "google_cloud_asset_organization_feed" "default" {
  project          = "my-project-name"
  feed_id          = "network-updates"
  content_type     = "RESOURCE"

  asset_types = [
    "compute.googleapis.com/Subnetwork",
    "compute.googleapis.com/Network",
  ]

  feed_output_config {
    pubsub_destination {
      topic = google_pubsub_topic.feed_output.id
    }
  }

  # Wait for the permission to be ready on the destination topic.
  depends_on = [
    google_pubsub_topic_iam_member.cloud_asset_writer,
  ]
}

# The topic where the resource change notifications will be sent.
resource "google_pubsub_topic" "feed_output" {
  project  = "my-project-name"
  name     = "network-updates"
}

# Find the project number of the project whose identity will be used for sending
# the asset change notifications.
data "google_project" "project" {
  project_id = "my-project-name"
}

# Allow the publishing role to the Cloud Asset service account of the project that
# was used for sending the notifications.
resource "google_pubsub_topic_iam_member" "cloud_asset_writer" {
  project = "my-project-name"
  topic   = google_pubsub_topic.feed_output.id
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:service-${data.google_project.project.number}@gcp-sa-cloudasset.iam.gserviceaccount.com"
}

**Comment by jgireeshj** [comment]
First I used the provider as google
provider "google" {  
  project  = "my-project-name" 
}

as this was not working, I've tried using google-beta

provider "google-beta" {  
  project  = "my-project-name" 
}

The version of terraform is up-to date

**Comment by jgireeshj** [comment]
Steps:

1.  terraform init
2. terraform validate

while running a validate command I am getting the below error:

**_

Error: Invalid resource type

  on test_assets_monitoring.tf line 7, in resource "google_cloud_asset_organization_feed" "default":
   7: resource "google_cloud_asset_organization_feed" "default" {

The provider provider.google does not support resource type
"google_cloud_asset_organization_feed".

_**

**Comment by edwardmedia** [comment]
@jgireeshj  do you provide **billing_project** somewhere? It is required argument. 

```billing_project - (Required) The project whose identity will be used when sending messages to the destination pubsub topic. It also specifies the project for API enablement check, quota, and billing.```

**Comment by danawillow** [comment]
Drive-by (I happened to be browsing the issue tracker, don't mind me): That resource was added in v3.32.0. So according to the versions of the google and google-beta providers that you've specified, only the google-beta provider will have support for that resource. You can specify the beta provider by putting `provider = google-beta` in the resource block.

@edwardmedia, not setting a required field would give a different error message. This one pretty clearly seems to say that the provider itself doesn't have support for the resource.

**Comment by jgireeshj** [comment]
> Drive-by (I happened to be browsing the issue tracker, don't mind me): That resource was added in v3.32.0. So according to the versions of the google and google-beta providers that you've specified, only the google-beta provider will have support for that resource. You can specify the beta provider by putting `provider = google-beta` in the resource block.
> 
> @edwardmedia, not setting a required field would give a different error message. This one pretty clearly seems to say that the provider itself doesn't have support for the resource.

I have tried with provider as "google-beta" also. But the same error is persisting. 

Providers:
Terraform v0.12.29
+ provider.google v3.27.0
+ provider.google-beta v3.33.0


I sorted out with the issue, by clearing the terraform plugins and rerun the code so that the Providers is updated with the latest version

After clearing the cache:

Providers:
Terraform v0.12.29
+ provider.google v3.33.0
+ provider.google-beta v3.33.0

Here the google provider version was updated to 3.33.0
The code is working as expected.
