### ISSUE TITLE
Include google_service_account_key import

### ISSUE THREAD

**Issue by alessiofranceschini** [hashicorp/terraform-provider-google#6939]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_service_account_key

### Potential Terraform Configuration

```tf
Terraform v0.12.29
+ provider.google v3.33.0
```

### References

* #0000

**Comment by melinath** [comment]
It looks like this is not possible because the private key data is not available after create. Please let us know if there's a use case that we're missing that isn't covered by the [datasource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/service_account_key)
