### ISSUE TITLE
google_compute_instance > boot_disk > auto_delete should not have a default value

### ISSUE THREAD

**Issue by mrzor** [hashicorp/terraform-provider-google#6950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The documentation states:

> The boot_disk block supports:      auto_delete - (Optional) Whether the disk will be auto-deleted when the instance is deleted. 
> Defaults to true.

As far as I can tell, this is the only optional parameter that has a default value. This means that no matter what happens, this configurable will not be allowed to drift and must be handled through Terraform.

This interacts in a bad way with #6846. 

This should _not_ have a default value. The instances/insert REST API does not require this field to be set at any point. The Terraform provider should not force the default and then, incidentally, guard against drift of that value **unless asked to**.

### New or Affected Resource(s)

* google_compute_instance

### References

* #6892 
* #6857
* [rest/v1/instances/insert](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert)

**Comment by rileykarson** [comment]
Hey @mrzor!

I'm not sure what you mean regarding #6846. Did you mean #6857 there?

While that field has an explicit default (reflecting the setting in the API), other fields actually implicitly default to `false` as well. Terraform will attempt to manage drift on all fields.

However you can disable that behaviour for a given field in your config with [`lifecycle.ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes). By entering a field's path in that array, changes will not cause Terraform to detect drift on the field. Note that in the case of a recreate, Terraform will use the original value provided in config to create the resource again.
