### ISSUE TITLE
disk create: Enable multi-writer option

### ISSUE THREAD

**Issue by ccancellieri** [hashicorp/terraform-provider-google#6953]
Hi, 
 I'm trying to enable beta (or alpha) --multi-writer flag in my gcloud project doing:

`
$ gcloud beta compute disks create XXXXXXXXXX-disk --project=XXXXXXXX --type=pd-ssd --size=30GB --zone=us-central1-a --multi-writer --physical-block-size=4096 --verbosity="debug"
`

With no success... the documentation says that it's possible to use that option but it doesn't work currently.

And: .... Is it possible to use a multi-writer disk with terraform ?

LOG:

DEBUG: Running [gcloud.beta.compute.disks.create] with arguments: [--multi-writer: "True", --physical-block-size: "4096"
, --project: "XXXXXXX", --size: "32212254720", --type: "pd-ssd", --verbosity: "debug", --zone: "us-central1-a", 
DISK_NAME:1: "['XXXXXXX-disk']"]
DEBUG: (gcloud.beta.compute.disks.create) Could not fetch resource:
 - Invalid resource usage: 'Multi Writer Disk feature is not available for this project.'.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 808, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/compute/disks/create.py", line 589, in Run
    support_pd_interface=True)
  File "/usr/lib/google-cloud-sdk/lib/surface/compute/disks/create.py", line 547, in _Run
    return client.MakeRequests(requests)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 105, in MakeRequests
    errors, error_message='Could not fetch resource:')
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 124, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 136, in RaiseException
    errors))
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - Invalid resource usage: 'Multi Writer Disk feature is not available for this project.'.
ERROR: (gcloud.beta.compute.disks.create) Could not fetch resource:
 - Invalid resource usage: 'Multi Writer Disk feature is not available for this project.'.

> @ccancellieri for this feature, where did you see? Can you post the link of the doc over here that will be helpful? Thanks

Here it is:

https://cloud.google.com/sdk/gcloud/reference/beta/compute/disks/create#--multi-writer

NOTE: I'm unable to add comments, this is why I'm editing

**Comment by edwardmedia** [comment]
@ccancellieri  for this feature, where did you see? Can you post the doc over here that will be helpful? Thanks

**Comment by ccancellieri** [comment]
> @ccancellieri for this feature, where did you see? Can you post the link of the doc over here that will be helpful? Thanks

Here it is:

https://cloud.google.com/sdk/gcloud/reference/beta/compute/disks/create#--multi-writer

**Comment by edwardmedia** [comment]
@ccancellieri  Thank you for clarification. Unfortunately the feature has not been implemented in `google_compute_disk` yet. Changing the label to 'enhancement` for dev backlog.

**Comment by ccancellieri** [comment]
FYI:
Just created an [issue report](https://issuetracker.google.com/issues/164841448) on the GCP side:

**Comment by c2thorn** [comment]
Labeling this upstream since the feature is still in alpha.

**Comment by gdsotirov** [comment]
The feature is already in beta, so should we expect it in the google-beta provider at least?

**Comment by kladiv** [comment]
+1

**Comment by tarrencev** [comment]
looking forward to support for this
