### ISSUE TITLE
google_auto_dns_record feature

### ISSUE THREAD

**Issue by jgireeshj** [hashicorp/terraform-provider-google#6970]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to get a new feature added , where a DNS Record will have to be automatically added or updated if there are any changes to the compute instance. The changes to the instance can be label, tag, ip address ... 

### New or Affected Resource(s)

* google_auto_dns_record

### Potential Terraform Configuration

For adding new DNS Records
```tf
project_id = "my_project"
pubsub_topic = "topic_name"
changes {
       tag = [tags of the instnace]   #list of tags
       type = "TXT"
}
changes {
       name= "nameof the instnace" #string .. name of instance
       type = "TXT"
}
changes {
       ip = "cidr_ip" #string .. name of instance
       type = "A"
}
```

For existing DNS Record, it should update the existing values
```tf
project_id = "my_project"
pubsub_topic = "topic_name"
updates{
       tag = [tags of the instnace]   #list of tags
       type = "TXT"
}
updates{
       name= "nameof the instnace" #string .. name of instance
       type = "TXT"
}
updates{
       ip = "cidr_ip" #string .. name of instance
       type = "A"
}
```

**Comment by ndmckinley** [comment]
Hi there!

Thanks for your request.  We are not going to do this, but it is fortunately already possible in HCL!  For instance,

```
resource "google_compute_instance" "i" {
  ...
}

resource "google_dns_record_set" "r" {
  name = "example.com."
  type = "TXT"
  rrdatas = [google_compute_instance.i.name]
}
```

Does that make sense?

**Comment by jgireeshj** [comment]
> Hi there!
> 
> Thanks for your request. We are not going to do this, but it is fortunately already possible in HCL! For instance,
> 
> ```
> resource "google_compute_instance" "i" {
>   ...
> }
> 
> resource "google_dns_record_set" "r" {
>   name = "example.com."
>   type = "TXT"
>   rrdatas = [google_compute_instance.i.name]
> }
> ```
> 
> Does that make sense?

@ndmckinley , I was asking for updating existing DNS records. This solution doesn't match to the requirement.

**Comment by ndmckinley** [comment]
Hi,

I believe it does.  If the records already exist before you start writing terraform configuration, you can [import them](https://www.terraform.io/docs/import/index.html), and work from there.  :)
