### ISSUE TITLE
[Doc] region marked as required cloud_scheduler_job argument

### ISSUE THREAD

**Issue by hallvors** [hashicorp/terraform-provider-google#6975]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

https://www.terraform.io/docs/providers/google/r/cloud_scheduler_job.html says 

    region - (Required) Region where the scheduler job resides

But none of the examples set region and it appears not actually required. Please fix the docs :)

**Comment by edwardmedia** [comment]
@hallvors Thank you for pointing this out. `Region` is optional. If user does not provide, the default value (like one from environment variable) will be used. Will update the doc.
