### ISSUE TITLE
Add provider meta to user agent for module attribution

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#6977]
https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-provider-metadata

Blocked on https://github.com/hashicorp/terraform-provider-google/issues/6976.

**Comment by rileykarson** [comment]
Should we dedupe to https://github.com/hashicorp/terraform-provider-google/issues/6832 / dedupe that one here?

**Comment by danawillow** [comment]
Oh good find, I looked around for an existing one but didn't have the right keywords in my search.
