### ISSUE TITLE
google_bigquery_data_transfer_config has no documented way of loading data from Cloud Storage

### ISSUE THREAD

**Issue by jxub** [hashicorp/terraform-provider-google#6978]
Hi,

First off, apologies if this question shouldn't belong here.

The GCP UI does provide an option to load from Cloud Storage (https://console.cloud.google.com/bigquery/transfers/configs/create), but there are no documented the allowed values of `google_bigquery_data_transfer_config.data_source_id` nor `google_bigquery_data_transfer_config.params` at https://www.terraform.io/docs/providers/google/r/bigquery_data_transfer_config.html for a load from GCS aside from the scheduled SQL example.

Has someone figured a way of loading GCS to BQ with `google_bigquery_data_transfer_config` or should I use `google_bigquery_job` instead?

Thanks for all help 😄

**Comment by venkykuberan** [comment]
Hi,
  It looks to me the [API](https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs#TransferConfig) doesn't support that feature yet.  Let us know once API supports it , we will take as a work item.

**Comment by psvaiter** [comment]
Yes, it works, but it's not documented. I've also had a hard time trying to find something.
I use this resource to load data from GCS. Here's a sample of terraform code.
```
resource "google_bigquery_data_transfer_config" "template" {
  display_name           = "My GCS Transfer"
  location               = var.location
  data_source_id         = "google_cloud_storage"
  destination_dataset_id = "my_dataset"
  project                = var.project_id
  schedule               = var.schedule_interval

  params = {
    data_path_template              = "gs://${local.bucket_name}/*.json"
    destination_table_name_template = "my_table"
    file_format                     = "JSON"
    max_bad_records                 = 0
    ignore_unknown_values           = "true"
    allow_quoted_newlines           = "true"
    delete_source_files             = "true"
  }
}
```

It seems `params` accept the same parameters that official API, and they are documented in some places. The best match I found was the [Python client library for BigQuery Transfer Service](https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/types.html#google.cloud.bigquery_datatransfer_v1.types.TransferConfig).

**Comment by jxub** [comment]
Thanks @psvaiter !

I tried looking around a couple of APIs but didn't found any example. I might add a CSV or JSON load example to the `google_bigquery_data_transfer_config` terraform docs in the future for anyone who might be interested.
