### ISSUE TITLE
No change detected when google_sql_user managed user's password is changed via console

### ISSUE THREAD

**Issue by mvn-srizzari** [hashicorp/terraform-provider-google#6995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.29
provider.google: version = "~> 3.33"

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
resource "google_sql_user" "root" {
  provider = google

  host     = "%"
  instance = google_sql_database_instance.instance.name
  name     = "root"
  password = var.root_password
}

resource "google_sql_database_instance" "instance" {
  provider = google

  database_version = "MYSQL_5_6"
  name             = "db"
  region           = "us-central1"

  settings {
    tier            = "db-g1-small"
    disk_autoresize = false

    database_flags {
      name  = "group_concat_max_len"
      value = 429496729
    }

    maintenance_window {
      day          = 1
      hour         = 5
      update_track = "stable"
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I have a variable `var.root_password` set to some password.  A diff is created if I alter it or remove the `password` argument from the resource entirely.  However, if I change the password manually in the console, a new password is set but a diff is not created in the next plan.
### Actual Behavior

No changes are detected on the next plan, and terraform now has an old password configured that cannot be used.

### Steps to Reproduce

1. Create resources as mentioned above and create user.
2. Test the expected password.
3. Update the password for the user in the GCP console.
4. Run `terraform plan` and see no diff.

### Important Factoids

I imported this user initially, but I was able to recreate the problem with a brand new user as well.

### References

* #0000

**Comment by edwardmedia** [comment]
@mvn-srizzari if it secure if you can retrieve the updated **password** using Terraform? Yes, you can use Terraform to update the password. Please provide a link if you see API provide an option to let you retrieve that value. Thanks

**Comment by mvn-srizzari** [comment]
I don't see a way to retrieve it via the API.  I see that this wouldn't be possible for the terraform provider to do since API doesn't support it.

Can the documentation be updated to reflect that you can set the password with terraform but there is no way for a diff to be created if the password is changed via other methods?

**Comment by edwardmedia** [comment]
@mvn-srizzari the doc has already specified the `password` can be updated. I don't think we need to stress users can't retrieve password. Do you see other tools that provide that feature? Thank you very much for your attention. I am closing this issue now. Feel free to reopen it if you see a need to continue the conversion. Thanks
