### ISSUE TITLE
Error 403: The principal (user or service account) lacks IAM permission "cloudscheduler.jobs.create"

### ISSUE THREAD

**Issue by kevinsimper** [hashicorp/terraform-provider-google#7001]
You get this error if you try to create a Cloud Scheduler Job in a region where your App Engine were not created.

So if config is this:
```
provider "google" {
  project = "my-project"
  region = "europe-west4"
}
```

but you region where you created App Engine is "europe-west1", it will not work. You will get this error:

```
Error: Error creating Job: googleapi: Error 403: The principal (user or service account) lacks IAM permission "cloudscheduler.jobs.create" for the resource "projects/my-project/locations/europe-west4" (or the resource may not exist).
```

However, if you change it to 
```
resource "google_cloud_scheduler_job" "job" {
  region = "us-central1"
  ...
}
```

It will show you this error:
```
Error: Error creating Job: googleapi: Error 400: Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1
```

Which will help you set the correct error on the cloud scheduler job you create.

**Comment by venkykuberan** [comment]
@kevinsimper Cloud Scheduler is not available in the region europe-west4 as mentioned [here](https://cloud.google.com/about/locations#europe) so my hunch is the preliminary check itself is failing for euorpe-west4 before it tries to validate the App Engine region. Thus we see different error messages on your 2 scenarios.

Hope that helps.

**Comment by hoxu** [comment]
I think this should be reported upstream so that GCP can fix the error message. It's misleading at best.

**Comment by c2thorn** [comment]
Reported at https://issuetracker.google.com/issues/169348259
