### ISSUE TITLE
service_name is missing in datasource google_compute_forwarding_rule

### ISSUE THREAD

**Issue by axot** [hashicorp/terraform-provider-google#7002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
We want to get dns name in datasource google_compute_forwarding_rule for internal load balancer.

### New or Affected Resource(s)

current master branch

### Potential Terraform Configuration

```tf
data "google_compute_forwarding_rule" "example" {
  name = "foobar"
}

output "service_name" {
  value = data.google_compute_forwarding_rule.example.service_name
}
```

**Comment by rileykarson** [comment]
It's probably worth updating this datasource to be similar to newer datasources in the process, so that new fields are automatically picked up.
