### ISSUE TITLE
Add support for health check logging

### ISSUE THREAD

**Issue by cornmander** [hashicorp/terraform-provider-google#7003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_health_check

### Potential Terraform Configuration

```tf
resource "google_compute_health_check" "https-health-check" {
  log_config {
    enable = true
  }
}
```

### References

* New feature currently in beta: https://cloud.google.com/compute/docs/reference/rest/beta/healthChecks/insert
* https://cloud.google.com/load-balancing/docs/health-check-logging?hl=en

**Comment by upodroid** [comment]
This already exists in the beta provider but it is buggy #7016

**Comment by upodroid** [comment]
@c2thorn we can close this out. It is already available in beta.
