### ISSUE TITLE
google_cloud_identity_group import not working

### ISSUE THREAD

**Issue by jenshonkan84** [hashicorp/terraform-provider-google#7006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.28

### Affected Resource(s)

* google_cloud_identity_group

### Terraform Configuration Files

```tf


resource "google_cloud_identity_group" "sandbox-group" {
  provider = google-beta
  display_name = trimsuffix(var.teamgroup, "@blaj.se")

  parent = "customers/xxxxxx"

  group_key {
    id = var.teamgroup
  }

  labels = {
    "cloudidentity.googleapis.com/groups.discussion_forum" = ""
  }
}

terraform import -provider=google-beta module.teamsandbox.google_cloud_identity_group.sandbox-group groups/Xxxxxxxxx
```

### Debug Output

module.teamsandbox.google_cloud_identity_group.sandbox-group: Refreshing state... [id=groups]
62 Error: Error when reading or editing CloudIdentityGroup "groups": googleapi: Error 400: Parent must be specified
63 Details:
64 [
65   {
66     "@type": "type.googleapis.com/google.rpc.BadRequest"
67   }
68 ]

### Expected Behavior
Import my group in to the state file.

### Actual Behavior
Tells me to specify parent but this is already present in the resource.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@jenshonkan84 can you try using config like below instead?
```tf
resource "google_cloud_identity_group" "sandbox-group" {
}
```

**Comment by jenshonkan84** [comment]
Tried your suggestion but same error:
```
$ terraform import -provider=google-beta module.teamsandbox.google_cloud_identity_group.sandbox-group groups/032hXXXXXXXXX
59 Acquiring state lock. This may take a few moments...
60 module.teamsandbox.google_cloud_identity_group.sandbox-group: Importing from ID "groups/032hXXXXXXX"...
61 module.teamsandbox.google_cloud_identity_group.sandbox-group: Import prepared!
62   Prepared google_cloud_identity_group for import
63 module.teamsandbox.google_cloud_identity_group.sandbox-group: Refreshing state... [id=groups]
64 Error: Error when reading or editing CloudIdentityGroup "groups": googleapi: Error 400: Parent must be specified
65 Details:
66 [
67   {
68     "@type": "type.googleapis.com/google.rpc.BadRequest"
69   }
70 ]
```

Terraform code:
```
resource "google_cloud_identity_group" "sandbox-group" {
 
}

```

**Comment by edwardmedia** [comment]
@jenshonkan84 I am not sure how your module is built. To test if the `import` works, can you use the config provided with below command?  (remove modules in your code temporarily) 
```
terraform import -provider=google-beta google_cloud_identity_group.default {{name}}
```

**Comment by jenshonkan84** [comment]
@edwardmedia 

Same result:

```
resource "google_cloud_identity_group" "cloud_identity_group_basica" {
}
```
```
$ terraform import -provider=google-beta google_cloud_identity_group.cloud_identity_group_basica groups/032hioqXXXXXX
google_cloud_identity_group.cloud_identity_group_basica: Importing from ID "groups/032hioXXXXX"...
google_cloud_identity_group.cloud_identity_group_basica: Import prepared!
  Prepared google_cloud_identity_group for import
google_cloud_identity_group.cloud_identity_group_basica: Refreshing state... [id=groups]
Error: Error when reading or editing CloudIdentityGroup "groups": googleapi: Error 400: Parent must be specified
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest"
  }
]
```

**Comment by edwardmedia** [comment]
@jenshonkan84  What do you see if you run below below command?
```
gcloud beta identity groups describe {{email}}
```

**Comment by megan07** [comment]
Hi @jenshonkan84 @edwardmedia - I see the problem. I need to add a custom import in order to allow us to import names with slashes in them `groups/xxxxxxx`, I'll add that in now. Thanks for catching this!
