### ISSUE TITLE
Unable to replace google_compute_region_disk  if snapshot is changed

### ISSUE THREAD

**Issue by emmaLP** [hashicorp/terraform-provider-google#7014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.24
+ provider.acme v1.5.0
+ provider.external v1.2.0
+ provider.google v3.23.0
+ provider.google-beta v3.23.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
````

### Affected Resource(s)
google_compute_region_disk

### Terraform Configuration Files
Script assumes you already have a project and a custom vpc and subnet
```tf
locals {
  project_name ="testing"
  network = "${local.project_name}-vpc"
  subnet = "${local.project_name}-backend-subnet"
  disk_name = "test"
  distribution_zones = ["us-central1-a", "us-central1-b"]
  labels = {
    project = "test"
    app = "app"
  }
}
data "external" "disk_snapshot" {
  program = [ "/home/emma/source/gcp-tooling-infrastructure/src/resources/disk_snapshot_lookup.sh"]
  query = {
    project_name = local.project_name
    disk_name= local.disk_name
  }
}
resource "google_compute_region_disk" "this" {
  name = local.disk_name
  project = local.project_name
  region = "us-central1"
  size = 200
  type = "pd-standard"
  snapshot = data.external.disk_snapshot.result.snapshot_id
  labels = local.labels
  replica_zones = local.distribution_zones
}

resource "google_compute_instance_template" "default" {
  machine_type = "n1-standard-1"
  name_prefix = "test-instance"
  project = local.project_name
  region = "us-central1"
can_ip_forward = false
  network_interface {
    network = local.network
    subnetwork = local.subnet
    subnetwork_project = local.project_name
  }
  metadata_startup_script = "mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb && mkdir -p /tmp/disk_mount &&  mount -o discard,defaults /dev/sdb /tmp/disk_mount && sudo chmod a+w /tmp/disk_mount"
  disk {
    source_image = "debian-cloud/debian-10"
    auto_delete = true
    boot = true
    disk_type = "pd-standard"
    disk_size_gb = 20
  }
  disk {
    source = google_compute_region_disk.this.self_link
    boot = false
    auto_delete = false
  }
  lifecycle {
    create_before_destroy = true
  }
}
resource "google_compute_region_instance_group_manager" "this" {
  name = "test-instance-igm"
  project = local.project_name
  region = "us-central1"
  base_instance_name = "test-instance"
  target_size = 1
  distribution_policy_zones = local.distribution_zones

  version {
    name = "live"
    instance_template = google_compute_instance_template.default.self_link
  }

  update_policy {
    type = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action = "REPLACE"
    max_surge_fixed = length(local.distribution_zones)
    max_unavailable_fixed = 0
    min_ready_sec = 60
  }

}

```

Shell script referenced in the external data source
```bash
#!/bin/bash
function error_exit() {
  echo "$1" 1>&2
  exit 1
}

function check_deps() {
  test -f $(which gcloud) || error_exit "gcloud command not detected in path"
  test -f $(which jq) || error_exit "jq command not detected in path"
}

function parse_input() {
  eval "$(jq -r '@sh "export PROJECT_NAME=\(.project_name) DISK_NAME=\(.disk_name)"')"
  if [[ -z "${PROJECT_NAME}" ]]; then error_exit "PROJECT_NAME needs to be specified"; fi
  if [[ -z "${DISK_NAME}" ]]; then error_exit "DISK_NAME needs to be specified"; fi
}

function find_snapshot() {
  SNAPSHOT_LINK=$(gcloud compute snapshots list --project "${PROJECT_NAME}" --filter="name~${DISK_NAME}" --limit 1 --sort-by="~creationTimestamp"  --format="value(selfLink)" | awk {'print $1'})
  jq -n \
    --arg snapshot_id "$SNAPSHOT_LINK" \
    '{"snapshot_id":$snapshot_id}'
}

check_deps && \
parse_input && \
find_snapshot
```
### Debug Output

https://gist.github.com/emmaLP/15605b59c58b4014d2772b99f0fcff44

### Expected Behavior

New disk is created first and then the old disk is removed. Ideally name should be name_prefix and a random string is added to the end of the name

### Actual Behavior

Error:
```
Error: Error creating RegionDisk: googleapi: Error 409: The resource 'projects/flooid-tooling/regions/us-central1/disks/jenkins-data-zqjl' already exists, alreadyExists

  on ../../gcp-compute-vm/main.tf line 212, in resource "google_compute_region_disk" "this":
 212: resource "google_compute_region_disk" "this" {
```

### Steps to Reproduce

1. Create with tf `terraform apply`
1. Create a snapshot of the disk (I did this via the console ensuring that the snapshot name contained the disk_name) and it has finished created the snapshot
1. Run terraform again: `terraform apply`

**Comment by edwardmedia** [comment]
@emmaLP below is the plan when I tested the behavior by updating the snapshot, The replacement is done successfully. From your log, I noticed there was no `DELETE` before `POST`. Can you post its `plan`? Your code uses `external` data source, I assume you are aware of its limitations. 

```
  # google_compute_region_disk.regiondisk must be replaced
-/+ resource "google_compute_region_disk" "regiondisk" {
 ...
      ~ snapshot                  = "https://www.googleapis.com/compute/v1/projects/myproject/global/snapshots/media-snapshot-1" 
-> "projects/myproject/global/snapshots/media-snapshot-2" # forces replacement
      ~ source_snapshot_id        = "7554020849252598713" -> (known after apply)
...
    }
Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by edwardmedia** [comment]
@emmaLP is this still an issue?

**Comment by emmaLP** [comment]
@edwardmedia sorry for the delay in getting back to you. Yes this is still an issue.

I re-tested this morning but used a plan file and then attempted to apply afterwards. I get the same error
Logs can be found here: https://gist.github.com/emmaLP/df852803af7e615e227f47db989deb59

This is down to the name of the disk been the same for the replacement. Google doesn't seem to allow duplicate disk names

**Comment by edwardmedia** [comment]
@emmaLP using external data source seems to be fine as long as it returns the right snapshot. If you add `output` for your external data source, what do you see? Also you may want to try hard-coding the result of the external data source, and see what it happens?

**Comment by emmaLP** [comment]
Even if I hard code the snapshot, I get the same issue. The issue is because the name of the regional disk is not unique. The gist link I sent yesterday contains 2 files, the plan logs as well as the apply logs.  The plan logs are after the apply logs

Only use tf to manage GCP infrastructure and the project is a personal one, only I have access to. I haven't gone and created a regional disk manually with the same name.

**Comment by emmaLP** [comment]
@edwardmedia The external data source only returns a snapshot id if there is one to be found, which is correct. I have run several tests against the external datasource and returns as expected. 

My problem is that when terraform wants to replace the regional disk, it tries to create the new disk first is which then fails because the name of the disk already exists. The regional disk name needs to be unique when replacing.

**Comment by edwardmedia** [comment]
I do see the problem now.

**Comment by edwardmedia** [comment]
https://paste.googleplex.com/5908394709876736
https://paste.googleplex.com/4923115122458624
https://paste.googleplex.com/4797858035269632

**Comment by danawillow** [comment]
The order of operations here isn't intuitive, but I'm having trouble coming up with something that would work with the config in question. Here are our options:

1. Create new InstanceTemplate, then destroy old RegionDisk. This won't work because the disk won't be able to be deleted; it's currently in use.
2. Create new InstanceTemplate, then create new RegionDisk. This won't work because the old disk still exists.
3. Create new RegionDisk first. This won't work because the old disk still exists.
4. Destroy old RegionDisk first. This won't work because the disk won't be able to be deleted; it's currently in use.

I think those are our only options, and none of them work. My recommendation would be to use the [random provider](https://registry.terraform.io/providers/hashicorp/random/latest/docs) to create a unique name for the RegionDisk so that when it's recreated, it doesn't try to create something that already exists. Funny enough, I think this explains why it tried to create the disk before deleting it- if you were to use a random name for it, then the only order of operations that works is to create the new disk first, since it has to exist before the new instance template is created.

Give that a try @emmaLP and let me know how it goes!

**Comment by edwardmedia** [comment]
@emmaLP is this still en issue with you?

**Comment by emmaLP** [comment]
@danawillow When trying with a random provider to append to the end of the disk name, on the second run I hit the same issue because the random provider only generates the string once. 

 I've actually implemented a work around where if a snapshot of the disk exists then the name of the disk name gets appended with the snapshot id so each disk name is always unique. It's not really ideal because this then changes the resource policy and older snapshots aren't been cleaned up because the disk resource policy has been replaced because the disk has a new name.

**Comment by emmaLP** [comment]
Ideally this issue should be fixed in the provider, can you give me an ETA of when this likely to be worked on?

**Comment by danawillow** [comment]
Hey @emmaLP, the provider doesn't actually have any control over what order operations happen in; that all happens within Terraform core. That's why I'm looking for a workaround :)

Can you post the config you tried with the random provider? I'd like to play around with it and see if I can come up with something that works.

**Comment by emmaLP** [comment]
Hi @danawillow,

This is my workaround solution that always results in a unique disk anme:
```bash
#!/bin/bash
function error_exit() {
  echo "$1" 1>&2
  exit 1
}

function check_deps() {
  test -f $(which gcloud) || error_exit "gcloud command not detected in path"
  test -f $(which jq) || error_exit "jq command not detected in path"
}

function parse_input() {
  eval "$(jq -r '@sh "export PROJECT_NAME=\(.project_name) DISK_NAME=\(.disk_name)"')"
  if [[ -z "${PROJECT_NAME}" ]]; then error_exit "PROJECT_NAME needs to be specified"; fi
  if [[ -z "${DISK_NAME}" ]]; then error_exit "DISK_NAME needs to be specified"; fi
}

function find_snapshot() {
  SNAPSHOT_RESULT=$(gcloud compute snapshots list --project "${PROJECT_NAME}" --filter="name~${DISK_NAME}" --limit 1 --sort-by="~creationTimestamp"  --format="value(selfLink, id)")
  SNAPSHOT_LINK=$(echo "${SNAPSHOT_RESULT}" | awk {'print $1'})
  SNAPSHOT_ID=$(echo "${SNAPSHOT_RESULT}" | awk {'print $2'})
  jq -n \
    --arg snapshot_link "$SNAPSHOT_LINK" \
    --arg snapshot_id "$SNAPSHOT_ID" \
    '{"snapshot_link":$snapshot_link, "id": $snapshot_id}'
}

check_deps && \
parse_input && \
find_snapshot
```

```hcl
locals {
  project_name ="test"
  disk_name = "test-${data.external.disk_snapshot.result.id == "" ? random_string.test_disk.result : data.external.disk_snapshot.result.id}"
  distribution_zones = ["us-central1-a", "us-central1-b"]
  labels = {
    project = "test"
    app = "app"
  }
}
data "external" "disk_snapshot" {
  program = [ "./disk_snapshot_lookup.sh"]
  query = {
    project_name = local.project_name
    disk_name= "test"
  }
}
resource "random_string" "test_disk" {
  length = 10
  special = false
  upper = false
}
resource "google_compute_region_disk" "this" {
  name = local.disk_name
  project = local.project_name
  region = "us-central1"
  size = 200
  type = "pd-standard"
  snapshot = data.external.disk_snapshot.result.snapshot_link
  labels = local.labels
  replica_zones = local.distribution_zones
}

resource "google_compute_instance_template" "default" {

  machine_type = "n1-standard-1"
  name_prefix = "test-instance"
  project = local.project_name
  region = "us-central1"
can_ip_forward = false
  network_interface {
    network = "test-backend-vpc"
    subnetwork = "test-backend-subnetwork"
    subnetwork_project = local.project_name
  }
  metadata_startup_script = "mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb && mkdir -p /tmp/disk_mount &&  mount -o discard,defaults /dev/sdb /tmp/disk_mount && sudo chmod a+w /tmp/disk_mount"
  disk {
    source_image = "debian-cloud/debian-10"
    auto_delete = true
    boot = true
    disk_type = "pd-standard"
    disk_size_gb = 20
  }
  disk {
    source = google_compute_region_disk.this.self_link
    boot = false
    auto_delete = false
  }
  lifecycle {
    create_before_destroy = true
  }
}
resource "google_compute_region_instance_group_manager" "this" {
  name = "test-instance-igm"
  project = local.project_name
  region = "us-central1"
  base_instance_name = "test-instance"
  target_size = 1
  distribution_policy_zones = local.distribution_zones

  version {
    name = "live"
    instance_template = google_compute_instance_template.default.self_link
  }

  update_policy {
    type = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action = "REPLACE"
    max_surge_fixed = length(local.distribution_zones)
    max_unavailable_fixed = 0
    min_ready_sec = 60
  }

}
```

**Comment by emmaLP** [comment]
Here is the scenario using just a random provider:
```hcl
locals {
  project_name ="test"
  disk_name = "test-${random_string.test_disk.result}"
  distribution_zones = ["us-central1-a", "us-central1-b"]
  labels = {
    project = "test"
    app = "app"
  }
}
data "external" "disk_snapshot" {
  program = [ "./disk_snapshot_lookup.sh"]
  query = {
    project_name = local.project_name
    disk_name= "test"
  }
}
resource "random_string" "test_disk" {
  length = 10
  special = false
  upper = false
}
resource "google_compute_region_disk" "this" {
  name = local.disk_name
  project = local.project_name
  region = "us-central1"
  size = 200
  type = "pd-standard"
  snapshot = data.external.disk_snapshot.result.snapshot_link
  labels = local.labels
  replica_zones = local.distribution_zones
}

resource "google_compute_instance_template" "default" {

  machine_type = "n1-standard-1"
  name_prefix = "test-instance"
  project = local.project_name
  region = "us-central1"
can_ip_forward = false
  network_interface {
    network = "test-backend-vpc"
    subnetwork = "test-backend-subnetwork"
    subnetwork_project = local.project_name
  }
  metadata_startup_script = "mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb && mkdir -p /tmp/disk_mount &&  mount -o discard,defaults /dev/sdb /tmp/disk_mount && sudo chmod a+w /tmp/disk_mount"
  disk {
    source_image = "debian-cloud/debian-10"
    auto_delete = true
    boot = true
    disk_type = "pd-standard"
    disk_size_gb = 20
  }
  disk {
    source = google_compute_region_disk.this.self_link
    boot = false
    auto_delete = false
  }
  lifecycle {
    create_before_destroy = true
  }
}
resource "google_compute_region_instance_group_manager" "this" {
  name = "test-instance-igm"
  project = local.project_name
  region = "us-central1"
  base_instance_name = "test-instance"
  target_size = 1
  distribution_policy_zones = local.distribution_zones

  version {
    name = "live"
    instance_template = google_compute_instance_template.default.self_link
  }

  update_policy {
    type = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action = "REPLACE"
    max_surge_fixed = length(local.distribution_zones)
    max_unavailable_fixed = 0
    min_ready_sec = 60
  }

}
```

Please use the bash script from the previous post.

Steps to reproduce with the random provider:
1. Run `terraform apply`
1. Manually create snapshot of persisted disk, ensuring the snapshot of the disk starts with test
1. Run `terraform apply` again
1. Regional persistent disk will try create first but fails with already existing error 
```
Error message:
google_compute_region_disk.this: Creating...

Error: Error creating RegionDisk: googleapi: Error 409: The resource 'projects/test/regions/us-central1/disks/test-e9yzld247m' already exists, alreadyExists

  on main.tf line 23, in resource "google_compute_region_disk" "this":
  23: resource "google_compute_region_disk" "this" {

```

**Comment by danawillow** [comment]
For the random provider scenario, can you try this:
```
resource "random_string" "test_disk" {
  length = 10
  special = false
  upper = false
  keepers = {
    "snapshot" = data.external.disk_snapshot.result.snapshot_link
  }
}
```

Take a look at the documentation for keepers to understand what this does- basically, it means "if the snapshot_link changes, then generate a new random string": https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers

**Comment by edwardmedia** [comment]
@emmaLP is this still an issue?

**Comment by edwardmedia** [comment]
Closing this. Feel free to reopen it if this is still an issue.
