### ISSUE TITLE
Need support to add IAM role binding to grant access to machine images stored in a different GCP Project

### ISSUE THREAD

**Issue by dpanyam** [hashicorp/terraform-provider-google#7019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Usecase  is creating a GCE VM from a machine image that exists in a different GCP Project.

If you want to create an instance from a machine image that is located in a different project, you need to ensure that you have access to the machine image

To grant the permissions on the machine image using the gcloud command-line tool, run the following command:

gcloud beta compute machine-images add-iam-policy-binding MACHINE_IMAGE_NAME \
    --project=MACHINE_IMAGE_PROJECT \
    --member='email' \
    --role='roles/compute.admin'

Replace the following:

MACHINE_IMAGE_PROJECT: The project ID for the project that contains the source machine image.
MACHINE_IMAGE_NAME: The name of the machine image that you want to add the permission binding to.
EMAIL: The email address of the serviceAccount or user that is creating the VM. Ensure that the email is formatted to include the required prefix, the prefix must be one of the following:

user: Specify this if the email address is associated with a user account.
serviceAccount: Specify this if the email address is associated with a service account. For example, serviceAccount:123456789000-compute@developer.gserviceaccount.com

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by upodroid** [comment]
https://cloud.google.com/compute/docs/machine-images/create-instance-from-machine-image
https://cloud.google.com/compute/docs/reference/rest/beta/instances/insert

Terraform is missing:
-  google_compute_machine_image_iam_* resources 
-  google_compute_machine_image data source
-  google_compute_instance_from_machine_image resource.

Final Config would look like this.

```
// Data or Resource
data "google_compute_machine_image" "image" {
  provider        = google-beta
  name            = "image"
}

resource "google_compute_machine_image_iam_member" "image" {
 provider     = google-beta
  image = data.google_compute_machine_image.name
  role    = "roles/editor"
  project = "other-project"
  member  = "serviceAccount:123456789000-compute@developer.gserviceaccount.com"
}

resource "google_compute_instance_from_machine_image" "tpl" {
  name = "instance-from-machine-image"
  zone = "us-central1-a"
  source_machine_image = google_compute_machine_image_iam_member.image.image
}
```

@dpanyam In the meanwhile, you can grant the role on the project to do cross project machine images now,
