### ISSUE TITLE
Request for easier configuration of resource_usage_export_config

### ISSUE THREAD

**Issue by jtslear** [hashicorp/terraform-provider-google#7021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.20
+ provider.google v2.20.0
+ provider.google-beta v3.33.0
```

### Affected Resource(s)

* `google_container_cluster.resource_usage_export_config`

### Terraform Configuration Files

When creating a `resource_usage_export_config` like so:

```tf
  resource_usage_export_config {
    enable_network_egress_metering       = var.network_egress_metering_enabled
    enable_resource_consumption_metering = var.resource_consumption_metering_enabled

    bigquery_destination {
      dataset_id = var.resource_usage_dataset
    }
  }
```

Having the `enable_network_egress_metering` and `enable_resource_consumption_metering` values set to `false`, causes terraform to want to apply this as a change for every run:

```
<SNIP>
      + resource_usage_export_config {
          + enable_network_egress_metering       = false
          + enable_resource_consumption_metering = false

          + bigquery_destination {}
        }
<SNIP>
```

In the state file this is stored simply as:

```
<SNIP>
"resource_usage_export_config": [],
<SNIP>
```

For clusters where we choose not to enable this feature, this shows up as a change every single time we run terraform and this is not desired.

As a workaround, we can apply the conditional trick with a dynamic block like so:

```tf
  dynamic "resource_usage_export_config" {
    for_each = var.network_egress_metering_enabled || var.resource_consumption_metering_enabled == true ? [1] : []
    content {
      enable_network_egress_metering       = var.network_egress_metering_enabled
      enable_resource_consumption_metering = var.resource_consumption_metering_enabled

      bigquery_destination {
        dataset_id = var.resource_usage_dataset
      }
    }
  }
```

And this appears to work as desired, however, having a dynamic block in place is not necessarily desired.  I propose that this `resource_usage_export_config` be provided a way to operate without the need to be conditional as I've provided above.

**Comment by edwardmedia** [comment]
Closing as request should be in enhancement
