### ISSUE TITLE
boot_disk_kms_key not supported under google_container_node_pool->node_config

### ISSUE THREAD

**Issue by Siegfriedk** [hashicorp/terraform-provider-google#7034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.0
+ provider registry.terraform.io/-/google v3.34.0
+ provider registry.terraform.io/-/google-beta v3.34.0
+ provider registry.terraform.io/hashicorp/google v3.34.0
+ provider registry.terraform.io/hashicorp/google-beta v3.34.0

### Affected Resource(s)

* google-beta v3.34.0

### Terraform Configuration Files

```tf

# this works
resource "google_container_cluster" "build" {
  node_config {
    boot_disk_kms_key = var.defaultkey
  }
}

# this doesn't work
resource "google_container_node_pool" "build" {
  node_config {
    boot_disk_kms_key = var.defaultkey
  }
}

```

### Debug Output
2020/08/16 00:51:50 [ERROR] eval: *terraform.EvalValidateResource, err: Unsupported argument: An argument named "boot_disk_kms_key" is not expected here.
2020/08/16 00:51:50 [ERROR] eval: *terraform.EvalSequence, err: Unsupported argument: An argument named "boot_disk_kms_key" is not expected here.

...

 boot_disk_kms_key = var.defaultkey

### Expected Behavior
I would assume, also based on how the nodepool struct is used in the code, that it should work in both node_pool blocks.

### Actual Behavior
Error message that boot_disk_kms_key is not expected here.

### Steps to Reproduce

Create a GKE Cluster with encrypted boot disk, the default node pool and your own node pools and referencing your customer managed key with boot_disk_kms_key

### Important Factoids

Nothing special.

### References

* #0000

**Comment by edwardmedia** [comment]
@Siegfriedk did you use `beta` provider? Below is what from its document. Let me know if this help address your issue.
```
boot_disk_kms_key - (Optional, Beta) The Customer Managed Encryption Key used to encrypt the boot disk attached to each node in the node pool. 
```

**Comment by Siegfriedk** [comment]
I have both provider declared at the top @edwardmedia 

That should work in theory right?

I hope it fits here, contribution of beta writes i should open a tickethere.
`
provider "google" {
  version = "~> 3.34.0"
  region  = var.region
  project = var.project
}

provider "google-beta" {
  version = "~> 3.34.0"
  region  = var.region
  project = var.project
}
`

**Comment by edwardmedia** [comment]
@Siegfriedk have you tried by adding `provider` inside the resource?
```tf
resource "google_container_node_pool" "build" {
....
 provider = google-beta
  node_config {
    boot_disk_kms_key = var.defaultkey
  }
....
}
```

**Comment by Siegfriedk** [comment]
@edwardmedia nope i haven't seen this syntax before; I can try that tomorrow.

But the boot_disk_kms_key is also beta for the google_container_cluster https://www.terraform.io/docs/providers/google/r/container_cluster.html#boot_disk_kms_key where it works without issues and both resources are in the same file (one is below the other)

**Comment by Siegfriedk** [comment]
@edwardmedia i forgot i was able to try it out sry 👍 
And that actually works. Tx

Can you give me a hint why?

**Comment by edwardmedia** [comment]
@Siegfriedk I am glad it works for you. Here is the document that might be helpful. https://www.terraform.io/docs/providers/google/guides/provider_versions.html
