### ISSUE TITLE
Doc: IAM policy audit_config is a top level field, not a sub-field of binding

### ISSUE THREAD

**Issue by pdecat** [hashicorp/terraform-provider-google#7046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

N/A

### Affected Resource(s)

* `google_iam_policy`

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Documentation should state that is a top-level field `audit_config` of the `google_iam_policy` resource.

Corresponding code: https://github.com/hashicorp/terraform-provider-google/blob/v3.35.0/google/data_source_google_iam_policy.go#L79

### Actual Behavior

Documentation states that `audit_config` is a sub-field of `binding`: https://github.com/hashicorp/terraform-provider-google/blame/v3.35.0/website/docs/d/iam_policy.html.markdown#L84-L89

### Steps to Reproduce

1. Go to https://www.terraform.io/docs/providers/google/d/iam_policy.html#audit_config

### References

* #2687

**Comment by edwardmedia** [comment]
@pdecat the example in the document seems to be clear where `audit_config` should be put. I agreed it is a little bit confusion in the `Argument Reference` section as the `audit_config` is listed along with `role` and `member`. Am I right in term of understanding the issue you reported?  Any suggestion that will make it clear?

**Comment by pdecat** [comment]
Hi @edwardmedia, the example is right, but the above documentation for binding states:

> Each document configuration must have one or more binding blocks, which each accept the following arguments:

Moving the `audit_config` documentation above the `binding` would eliminate the ambiguity IMO.
