### ISSUE TITLE
produced an unexpected new value for %!s(MISSING).

### ISSUE THREAD

**Issue by jsoref** [hashicorp/terraform-provider-google#7050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.0
+ provider registry.terraform.io/-/google v3.35.0
+ provider registry.terraform.io/hashicorp/google v3.35.0
```

### Affected Resource(s)

* google_kms_key_ring
* google_kms_crypto_key

### Terraform Configuration Files

`file.tf`:
```tf
data "google_kms_key_ring" "hell" {
  name     = "my-first-keyring"
  location = "global"
  project  = "pristine-bay-286722"
}

data "google_kms_crypto_key" "my_crypto_key" {
  name     = "my-crypto-key"
  key_ring = data.google_kms_key_ring.hell.self_link
}
```
`terraform.tfstate`:
```
{
  "version": 4,
  "terraform_version": "0.13.0",
  "serial": 3,
  "lineage": "ee8eceb7-1f35-47b9-7f4d-c6dff6ff3c8d",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "google_kms_crypto_key",
      "name": "my_crypto_key",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": null,
            "key_ring": null,
            "labels": null,
            "name": null,
            "purpose": null,
            "rotation_period": null,
            "self_link": null,
            "version_template": null
          }
        }
      ]
    },
    {
      "mode": "data",
      "type": "google_kms_key_ring",
      "name": "hell",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "pristine-bay-286722/global/my-first-keyring",
            "location": "global",
            "name": "my-first-keyring",
            "project": "pristine-bay-286722",
            "self_link": "projects/pristine-bay-286722/locations/global/keyRings/my-first-keyring"
          }
        }
      ]
    }
  ]
}
```

### Debug Output

https://gist.github.com/jsoref/9effc92245bd0acccc62de0cbec52b74

### Expected Behavior

Do not generate `%!s(MISSING)` in output

### Actual Behavior

```
2020-08-17T18:45:10.879-0400 [DEBUG] plugin.terraform-provider-google_v3.35.0_x5: 2020/08/17 18:45:10 [WARN] Removing KMSCryptoKey "projects/pristine-bay-286722/locations/global/keyRings/my-first-keyring/cryptoKeys/my-crypto-key" because it's gone
2020/08/17 18:45:10 [WARN] Provider "data.google_kms_crypto_key.my_crypto_key" produced an unexpected new value for %!s(MISSING).registry.terraform.io/hashicorp/google
      - .key_ring: was cty.StringVal("projects/pristine-bay-286722/locations/global/keyRings/my-first-keyring"), but now null
      - .name: was cty.StringVal("my-crypto-key"), but now null
```
### Steps to Reproduce

I've run `terraform plan` and `terraform apply` a couple of times...
1. ```sh
    export GOOGLE_APPLICATION_CREDENTIALS=key.json
    export TF_LOG=DEBUG
    terraform apply
    ```

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: authenticating as a user instead of a service account? --->
```sh
$ gcloud kms keyrings list --location global
NAME
projects/pristine-bay-286722/locations/global/keyRings/my-first-keyring
$ gcloud kms keys list --location global --keyring=my-first-keyring
Listed 0 items.
```
This keyring may have been made w/ cloud console...

### References

* #7044

**Comment by edwardmedia** [comment]
@jsoref here is the error we may want to check. Can you verify if the key exists?
```
CryptoKey projects/pristine-bay-286722/locations/global/keyRings/my-first-keyring/cryptoKeys/my-crypto-key not found.
```

**Comment by jsoref** [comment]
For this bug, there are no keys in the keyring. And I don't care. I'm annoyed by the `MISSING` thing.

**Comment by jsoref** [comment]
ok. This bug is due to the trailing `+` which should be a `,` here:
https://github.com/hashicorp/terraform/blob/27affd06cedff04d5a74c819cd296fa8ecff9e2b/terraform/eval_read_data_plan.go#L135

**Comment by edwardmedia** [comment]
@jsoref Thank you again for participation. It appears your fix is targeting `terraform`. I would suggest you file an issue at below GH. I am closing this issue then. Feel free to reopen it if you see a need to continue within the provider

https://github.com/hashicorp/terraform/issues

**Comment by jsoref** [comment]
I didn't realize that this bug was caused by terraform until I debugged it.

I hope you don't expect end users to be able to divine the right place for a given bug in advance.
