### ISSUE TITLE
Using self_link on instance creation is causing constant "forces replacement" on the instance

### ISSUE THREAD

**Issue by craigh1015** [hashicorp/terraform-provider-google#7052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_network
* google_compute_instance

### Terraform Configuration Files

```tf
# main.tf
resource "google_compute_network" "testnet" {
  name                    = "testnet"
  auto_create_subnetworks = true
}

module "test-vm" {
  source              = "./instance"
  instance_name       = "test-vm"
  instance_zone       = "us-central1-a"
  instance_subnetwork = google_compute_network.testnet.self_link
}

# instance/main.tf
variable "instance_name" {}
variable "instance_zone" {}
variable "instance_type" {
  default = "n1-standard-1"
}
variable "instance_subnetwork" {}

resource "google_compute_instance" "vm_instance" {
  name         = var.instance_name
  zone         = var.instance_zone
  machine_type = var.instance_type
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  network_interface {
    subnetwork = var.instance_subnetwork
    access_config {
      # Allocate a one-to-one NAT IP to the instance
    }
  }
}
```

### Expected Behavior

After resources have been created continued execution of `terraform plan` should report no changes to apply.

### Actual Behavior

The VM instance is destroyed and added on every execution.

Reports 
```
subnetwork = "https://www.googleapis.com/compute/v1/projects/deem-demo-mvc/regions/us-central1/subnetworks/testnet" -> "https://www.googleapis.com/compute/v1/projects/deem-demo-mvc/global/networks/testnet" # forces replacement
```
It appears that replacing `google_compute_network.testnet.self_link` with a self_link to the specific region might fix this.
However, I have not been able to identify a way of doing this.

Alternatively, having the actual subnet used by the instance stored in the tfstate would solve the issue

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

**Comment by edwardmedia** [comment]
@craigh1015 it seems that you were trying to assign `network` to `subnetwork`.  Look at the plan after you have applied, you may see 
it keeps trying to replace the `subnetwork` with the `network`. Please let me know if this make sense? 

```tf
instance_subnetwork = google_compute_network.testnet.self_link
```

**Comment by craigh1015** [comment]
This is from the PluralSight training course. I had assumed that it is requesting any valid subnet from those defined on the network.
How are you suggesting I modify the script?

The subnets are automatically created when the network is created. I am not sure how to get a self_link to the default subnet that was created in the region

**Comment by edwardmedia** [comment]
@craigh1015 you may try something like below 

```tf
resource "google_compute_network" "testnet" {
  name                    = "testnet"
  auto_create_subnetworks = false
}
module "test-vm" {
  source              = "./instance"
  instance_name       = "test-vm"
  instance_zone       = "us-central1-a"
  instance_subnetwork = google_compute_subnetwork.testsubnet.id
}
resource "google_compute_subnetwork" "testsubnet" {
  name          = "testsubnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.testnet.id
  secondary_ip_range {
    range_name    = "tf-test-secondary-range-update1"
    ip_cidr_range = "192.168.10.0/24"
  }
}
```

**Comment by craigh1015** [comment]
This appears to be creating a new subnet rather than use the default subnets.

Is there a mechanism to specify a self_link to the `default` subnet created when the network is created?

**Comment by edwardmedia** [comment]
@craigh1015  you could also just provide `network` instead of `subnetwork`. In that way, you can keep auto-created `default` subnetwork

```tf
resource "google_compute_instance" "vm_instance" {
  name         = var.instance_name
  zone         = var.instance_zone
  machine_type = var.instance_type
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  network_interface {
    network = var.instance_network
    access_config {
      # Allocate a one-to-one NAT IP to the instance
    }
  }
}
```

**Comment by craigh1015** [comment]
OK - that was exactly what I was looking for - thanks!
