### ISSUE TITLE
Add machine_image to google_compute_instance resource

### ISSUE THREAD

**Issue by robertrockjr** [hashicorp/terraform-provider-google#7055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add machine_image to google_compute_instance resource

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n1-standard-1"
  machine_image = "projects/<project>/global/machineImages/<machine_image_name>
  zone         = "us-central1-a"

### References

https://cloud.google.com/compute/docs/machine-images

* #0000

**Comment by upodroid** [comment]
There is an open PR for this.

https://github.com/GoogleCloudPlatform/magic-modules/pull/3873#issuecomment-675712186

**Comment by c2thorn** [comment]
There is an issue in the API that prevents disk overrides from working correctly. Following up internally.

**Comment by c2thorn** [comment]
Removing the upstream tag, the API will likely not support disk overrides for a while. Continued the feature without this functionality.
