### ISSUE TITLE
Simplistic google_kms_key_ring does not create key ring

### ISSUE THREAD

**Issue by jsoref** [hashicorp/terraform-provider-google#7058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

o:Terraform v0.13.0
o:+ provider registry.terraform.io/hashicorp/google v3.35.0

### Affected Resource(s)

* google_kms_key_ring

### Terraform Configuration Files

```tf
data "google_kms_key_ring" "hell" {
  name     = "my-new-keyring"
  location = "global"
  project  = "pristine-bay-286722"
}
```

### Debug Output

https://gist.github.com/jsoref/6dc3648de1ae0c99d0fb4a79a51e11df

### Expected Behavior

Create a key ring

### Actual Behavior

Nothing useful

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`

### Important Factoids

Billing is enabled.

**Comment by venkykuberan** [comment]
If you are trying to create the resource, you need to use the following, [doc](https://www.terraform.io/docs/providers/google/r/kms_key_ring.html)

```
 resource "google_kms_key_ring" "example-keyring" {
  name     = "keyring-example"
  location = "global"
}
```

**Comment by jsoref** [comment]
Sigh. I copy+pasted from https://www.terraform.io/docs/providers/google/d/kms_key_ring.html#example-usage -- the disinction between `data` and `resource` regularly trips me up.
