### ISSUE TITLE
Add a setting to destroy+create google_compute_instance during update

### ISSUE THREAD

**Issue by mig42** [hashicorp/terraform-provider-google#7075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

My current GCP infrastructure uses virtual machines with Local SSD attached to them. This setup doesn't allow to stop VM instances, you can only destroy them.

This is really inconvenient when I want to change the machine type. Terraform detects this as a resource update, so it attempts to stop and start the instance. However, as I can't force destroy during said update, Terraform fails:

```
Error: Error waiting for stopping instance: You cannot stop an instance that uses a local SSD. Delete and recreate the instance.
```

I would really appreciate having a setting to force destroy during update. Some boolean attribute called `destroy_on_update` could be nice.

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

```tf
resource "google_compute_instance" "test-instance" {
  name         = "my_test_machine"
  machine_type = "n1-standard-1"
  zone         = "europe-west1-a"
  tags = ["test_tag"]

  destroy_on_update = true

  boot_disk {
    device_name = "boot_disk"

    initialize_params {
      image = "ubuntu-minimal-1804-bionic-v20200720"
      size  = 375
      type  = "pd-ssd"
    }
  }

  // Local NVME disk
  scratch_disk {
    interface = "NVME"
  }
}
```

**Comment by danawillow** [comment]
Will probably be fixed by https://github.com/hashicorp/terraform-provider-google/issues/6857.

**Comment by rileykarson** [comment]
We'd recommend tainting the resource to resolve these cases. We're hesitant to add knobs that configure this setting, and "smart" behaviour (implemented through a customizediff) could be surprising for other users.
