### ISSUE TITLE
Terraform google_cloudfunctions_function

### ISSUE THREAD

**Issue by jgireeshj** [hashicorp/terraform-provider-google#7081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.35.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "instance_label_value_change" {
  project = var.project_id
  name    = "instance_label_value_update"
  # labels  = {
  #   generali_dns = var.label_generali_dns
  # }
}

resource "google_pubsub_subscription" "example" {
  project = var.project_id
  name    = "instance-label-subscription"
  topic   = google_pubsub_topic.instance_label_value_change.name
}

resource "google_storage_bucket" "bucket" {
  project   = var.project_id
  name      = "instance-label-dns"
}

resource "google_storage_bucket_object" "archive" {
  name   = "index.zip"
  bucket = google_storage_bucket.bucket.name
  source = "./bundle.zip"
}

resource "google_cloudfunctions_function" "function" {
  project               = var.project_id
  region                = var.region
  name                  = "function-test"
  description           = "My function"
  runtime               = "python37"
  available_memory_mb   = 256
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name 
  entry_point           = "main"
  event_trigger {
        event_type = "google_pubsub_topic.instance_label_value_change.publish"
        resource   = google_pubsub_topic.instance_label_value_change.id
  }

}

```

### Debug Output

google_cloudfunctions_function.function: Creating...

Error: googleapi: Error 400: The request has errors, badRequest

  on main.tf line 31, in resource "google_cloudfunctions_function" "function":
  31: resource "google_cloudfunctions_function" "function" {

### Expected Behavior

When the value for label of the compute instance is changed, a respective DNS entry will be created in the Cloud DNS.

**Comment by edwardmedia** [comment]
@jgireeshj can you share the debug log?

**Comment by upodroid** [comment]
@jgireeshj Your event trigger is incorrect.

It should be like this:

```
  event_trigger {
        event_type = "google.pubsub.topic.publish"
        resource   = google_pubsub_topic.instance_label_value_change.id
  }
```

**Comment by jgireeshj** [comment]
> @jgireeshj Your event_trigger.event_type field is wrong.
> 
> It should be like this:
> 
> ```
>   event_trigger {
>      event_type = "google.pubsub.topic.publish"
>      resource   = google_pubsub_topic.instance_label_value_change.id
>   }
> ```
> 
> Please try out the correct event_type and close the issue if it works for you.

@upodroid , Thanks it worked

**Comment by upodroid** [comment]
That is nice to hear.
