### ISSUE TITLE
Cloud Build triggers build step args not executing 

### ISSUE THREAD

**Issue by Arconapalus** [hashicorp/terraform-provider-google#7083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.35.0
+ provider registry.terraform.io/hashicorp/google-beta v3.35.0

### Affected Resource(s)

**Google_Cloud_Build_Triggers** 

### Terraform Configuration Files

```tf
resource "google_cloudbuild_trigger" "build-trigger" {
provider = google-beta 
project = var.project
 github { 
      owner = "github repo"
      name = var.name
    push {
        branch = var.branch_name
    }
}

build {
    step {

      id = "branch name"
      name = "alpine"
      entrypoint = "sh"
      env = [
         {
          BRANCH_NAME = var.branch_name
         }
]
      args = ["c" , "echo" , "${BRANCH_NAME}"]
         }
  

    } 
    
   description = "Push to any branch"
   filename = "cloudbuild.yaml"
}
```

### Debug Output

Error: Missing item separator Expected a comma to mark the beginning of the next item.

### Panic Output

n/a 

### Expected Behavior

Deploy cloud build trigger to execute TerraForm commands when GitHub commits 
### Actual Behavior

"Error: Missing item separator Expected a comma to mark the beginning of the next item."

### Steps to Reproduce

Assuming you have Github repo, cloud build trigger app integrated and permissions allowed for GitHub repo. CloudBuild.yaml to execute TerraForm commands when commits are pushed to GitHub repo. 

### Important Factoids

Cloud build service account has least privilege permission. However, can replication it with editor or owner role 

### References

No other issue, please forgive my ignorance as I'm fairly new to TerraForm cloud build triggers. I have added in the args ["c", "echo ${BRANCH_NAME}"] and have troubleshoot using various ways and still not being passed in.

**Comment by edwardmedia** [comment]
@Arconapalus I don't the enclosed **]** for one **env = [**

**Comment by Arconapalus** [comment]
I added ] to the module cloud build triggers and here is my variables.tf
```tf

# ------------------------------------------------------------------------------
#  variables for Cloud build triggers                                                       
# ------------------------------------------------------------------------------

variable "project" {
    description = "project to be used"
    type = string 

}

# variable "owner" {
#     description = "owner of github org"
#     type = string
# }

variable "name" {
    description = "name or repo"
    type = string
}

variable "branch_name" {
    description = "Working branch of github"
    type = string
    default = "staging"

}
```

**Comment by Arconapalus** [comment]
I figured out the problem with this. One, in order to replicate cloudbuild.yaml steps to build > steps. Need to delete filename="cloudbuild.yaml" What this does, makes the build steps inline which isn't an option when creating cloud build triggers. From here, we can go ahead and add 
```tf
resource "google_cloudbuild_trigger" "build-trigger" {
provider = google-beta 
project = var.project
 github { 
      owner = "github repo"
      name = var.name
    push {
        branch = var.branch_name
    }
}

build {
    step {

      id = "branch name"
      name = "alpine"
      entrypoint = "sh"
   
      args = ["-c","echo ${var.branch_name}"]
         }
    } 
    
   description = "Push to any branch"
#    filename = "cloudbuild.yaml"
}
```
As you can see above TF code, I'm passing the ${var.branch_name} in the args and below I have filename commented out. 
I don't see this an issue on TerraForm but more on GCP side of things. In documentation has no option to use inline and neither in GCP Cloud console. 
Thank you for time and expertise
