### ISSUE TITLE
Data source for google_secret_manager_secret_version constantly has ID changing due to timestamp issue

### ISSUE THREAD

**Issue by lucasteligioridis** [hashicorp/terraform-provider-google#7092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: v0.13.0
Google Provider: 3.35.0

### Affected Resource(s)

* data_source_google_secret_manager_secret_version

### Terraform Configuration Files

```tf
data "google_secret_manager_secret_version" "secret" {
  project = "my-project"
  secret = "my-secret"
  version = "latest"
}
```

### Expected Behavior

Once a terraform apply has been run, the diff should be clean unless a secret has changed.

### Actual Behavior

On terraform apply's for subsequent runs, there should be no diff or need to re-fetch the secret unless something has changed. But due to the way that the ID is configured:

https://github.com/hashicorp/terraform-provider-google/blob/d5c2dbf2648129fffb8596d038f7bc6e15299587/google/data_source_secret_manager_secret_version.go#L124

The ID will change every terraform plan/apply since the secret is read causing constant diffs with the `id` always changing.

```
 <= data "google_secret_manager_secret_version" "secret"  {
        create_time = "2020-08-24T06:55:21.133675Z"
        enabled     = true
      ~ id          = "2020-08-25 01:04:46.045399 +0000 UTC" -> "2020-08-25 01:06:12.418661 +0000 UTC"
        name        = "projects/12345678/secrets/my-secret/versions/1"
        project     = "my-project"
        secret      = "my-secret"
        secret_data = (sensitive value)
        version     = "1"
    }
```

Should probably emulate the way the AWS secret manager version resource works.

### Steps to Reproduce

1. Create a secret in the GCP secrets manager.
2. Create a data source as pasted above.
3. `terraform apply`
4. Then `terraform apply` again and see the diff always presenting itself because of the `id` using a currently read timestamp.

**Comment by edwardmedia** [comment]
I think setting `id` to the same as `name` might make more sense in this case.
