### ISSUE TITLE
Plans to implement 'user_account' resource

### ISSUE THREAD

**Issue by sidineycrescencio** [hashicorp/terraform-provider-google#7093]
Hi there,

Is there any plans to implement 'user_account' resource using the google cloud provider?

I see it's only possible create service accounts now, so wonder why we don't have yet the 'user_account' ?

Thanks.

**Comment by upodroid** [comment]
Hi

The user_account resource is effectively a GSuite/Cloud Identity or a Google Account user and they are both beyond the scope of the Google Cloud Provider.

There is a provider for GSuite if you are looking for a programmatic way of a creating gsuite users. 
https://github.com/DeviaVir/terraform-provider-gsuite

Thank you

**Comment by edwardmedia** [comment]
@sidineycrescencio does the answer from @upodroid make sense to you?

**Comment by sidineycrescencio** [comment]
Yes, it does @edwardmedia . Thanks for the prompt response @upodroid.
