### ISSUE TITLE
Can't use resourcePolicies inside disk block in the google_compute_instance_template

### ISSUE THREAD

**Issue by dpogorzelski** [hashicorp/terraform-provider-google#7094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

google_compute_instance_template's disk block does not accept `resourcePolicies` key

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

```tf
disk {
    auto_delete = false
    source      = "something"
    device_name = "data"
    resource_policies = ["disk-snapshot-name"]
  }
```

**Comment by jonathanrboniface** [comment]
Can you provide any solutions to associate a snapshot with a google_compute_instance_template?

**Comment by melinath** [comment]
This was resolved by https://github.com/hashicorp/terraform-provider-google/pull/8237
