### ISSUE TITLE
Update Dataproc autoscaling_policy

### ISSUE THREAD

**Issue by sumeetoc** [hashicorp/terraform-provider-google#7096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.36.0

### Affected Resource(s)

* google_dataproc_cluster

### Terraform Configuration Files

```tf
resource "google_dataproc_cluster" "simplecluster" {
  name    = "simplecluster"
  region  = "us-west1"
  project = "xxxx-xxxx"
  cluster_config {
    autoscaling_config {
      policy_uri = "projects/xxxx-xxxx/regions/us-west1/autoscalingPolicies/dataproc-test-cluster-policy"
    }
  }
}
```

### Debug Output

Displays success during terraform apply without any errors

### Expected Behavior

Should update the autoscaling_policy configuration with either the added policy_uri or remove it if not specified

### Actual Behavior

Displays success during terraform apply, however, the changes are not actually applied, and plans the changes on each terraform plan

### Steps to Reproduce

1. `terraform apply`
2. Remove the autoscaling_policy Terraform block
3. `terraform apply`
4. `terraform plan`

**Comment by venkykuberan** [comment]
I am seeing the same outcome but slightly different behavior. Actually provider isn't detecting the change in the config at all.

**Initial config**
```
resource "google_dataproc_cluster" "basic" {
  name     = "dataproc-policy"
  region   = "us-central1"
  cluster_config {
    autoscaling_config {
      policy_uri = "projects/xxxx/regions/us-central1/autoscalingPolicies/dataproc-policy"
    }
  }
}

resource "google_dataproc_autoscaling_policy" "asp" {
  policy_id = "dataproc-policy"
  location  = "us-central1"

  worker_config {
    max_instances = 3
  }

  basic_algorithm {
    yarn_config {
      graceful_decommission_timeout = "30s"

      scale_up_factor   = 0.5
      scale_down_factor = 0.5
    }
  }
}
```
I commented the whole cluster_config block however i don't see provider detecting the diff
```
resource "google_dataproc_cluster" "basic" {
  name     = "dataproc-policy"
  region   = "us-central1"
 # cluster_config {
 #   autoscaling_config {
 #     policy_uri = "projects/xxxx/regions/us-central1/autoscalingPolicies/dataproc-policy"
 #   }
  }
```
