### ISSUE TITLE
Error when trying to set boolean field to `false` on google_data_catalog_tag

### ISSUE THREAD

**Issue by tylerwengerd-cr** [hashicorp/terraform-provider-google#7097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.36.0
+ provider registry.terraform.io/hashicorp/google-beta v3.36.0
```

### Affected Resource(s)

* google_data_catalog_tag

### Terraform Configuration Files

```tf
resource "google_data_catalog_tag_template" "issue" {
  tag_template_id = "issue"

  force_delete = true
  region       = var.region
  project      = var.project_id

  fields {
    field_id = "bool_example"
    type {
      primitive_type = "BOOL"
    }
  }
}

resource "google_data_catalog_tag" "issue_true" {
  template = google_data_catalog_tag_template.issue.id
  parent   = var.entry_id

  fields {
    field_name = "bool_example"
    bool_value = true
  }
}

resource "google_data_catalog_tag" "issue_false" {
  template = google_data_catalog_tag_template.issue.id
  parent   = var.entry_id

  fields {
    field_name = "bool_example"
    bool_value = false
  }
}
```

### Debug Output

https://gist.github.com/tylerwengerd-cr/c025fb212ae8931137c881e4cbb602d0

(See line 360 vs. line 378 for an example of the empty request vs. a correct request structure.)

```
# Bad request when bool_example value should be false
{
 "fields": {
  "bool_example": {}
 },

# Working request when bool_example value is set to true
"fields": {
  "bool_example": {
    "boolValue": true
  }
},
```

### Panic Output

n/a

### Expected Behavior

The following request should exist and the tag should have been created, with the `bool_example` field in the tag set to `FALSE`:
```
"fields": {
  "bool_example": {
    "boolValue": false
  }
},
```

### Actual Behavior

Running a `terraform plan` produces a plan with correct tag values as expected:
```
Terraform will perform the following actions:

  # google_data_catalog_tag.issue_false will be created
  + resource "google_data_catalog_tag" "issue_false" {
      + id                   = (known after apply)
      + name                 = (known after apply)
      + parent               = "projects/cr-lab-twengerd-0508202549/locations/us/entryGroups/@bigquery/entries/cHJvamVjdHMvY3ItbGFiLXR3ZW5nZXJkLTA1MDgyMDI1NDkvZGF0YXNldHMvamFja2Fsb3BlL3RhYmxlcy9qcGRiX3NpdGVtb2Q"
      + template             = "projects/cr-lab-twengerd-0508202549/locations/us-central1/tagTemplates/issue"
      + template_displayname = (known after apply)

      + fields {
          + bool_value   = false
          + display_name = (known after apply)
          + field_name   = "bool_example"
          + order        = (known after apply)
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
```

But when running `terraform apply`, the following request was submitted during the API call, which resulted in the error below.

#### Request
```
# Visible in line 360 of the debug output
"fields": {
  "bool_example": {}
},
```

#### Error

> Error: Error creating Tag: googleapi: Error 400: Unsupported tag field value: value {
>}
>
>  on main-dc.tf line 30, in resource "google_data_catalog_tag" "issue_false":
>  30: resource "google_data_catalog_tag" "issue_false" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* Using Terraform 0.13.0 but also confirmed that this occurs with 0.12.29.
* Same error whether using `google` provider or `google-beta`.
* Have tried workarounds with "false" as a string, `0`, type conversion, etc. in the config file, with the same failure result.

### References

None

**Comment by edwardmedia** [comment]
When transformedStringValue == false, it always skip below assignment. That is why the transformed["boolValue"] is empty
https://github.com/hashicorp/terraform-provider-google/blob/f0e20f6bbcb5886c77740b2b8c3bef6cd1d75344/google/resource_data_catalog_tag.go#L440
