### ISSUE TITLE
BigQuery Data Transfer Service service account activation

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#7115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

BigQuery Data Transfer Service no longer provisions its service account when the API is enabled, but instead when the first call to the API is made. Currently, there is no way apply IAM policies to the service account before actually using the API. We need to add a resource or data source to make an API call so that the service account gets enabled. This is going to become a pattern going forward, so it would be worth thinking about a pattern + best practice in the provider for this.

Similar products:
* google_container_registry (https://github.com/hashicorp/terraform-provider-google/issues/4184, https://github.com/GoogleCloudPlatform/magic-modules/pull/3073)
* GKE Hub (in progress, https://github.com/hashicorp/terraform-provider-google/issues/5880)

### References

* b/165815126

**Comment by danawillow** [comment]
It's possible that we could take care of this and all future requests like this in one fell swoop with https://github.com/hashicorp/terraform-provider-google/issues/7020. Needs more investigation, maybe we have one person working on both issues next sprint.

**Comment by rtoma** [comment]
Hi Dana,

FYI - We noticed same behaviour on Cloud SQL. Using "google_sql_database_instance", with a private network configuration. This requires the servicenetworking.googleapis.com API enabled. Previously enabling this API triggered creation of service account service-[PROJECTNUMBER]@service-networking.iam.gserviceaccount.com, but that is no longer the case

**Comment by danawillow** [comment]
My impression is that many more of these are likely to come, but that the new `google_project_service_identity` resource will work for all of them. I'm actually going to go ahead and close this issue in favor of that one, which is now closed. The new resource should appear in v3.38.0 of the provider on Monday 9/8 (probably actually the Tuesday though because the Monday is a US holiday)
