### ISSUE TITLE
google_dataflow_job: current user cannot act as service account error

### ISSUE THREAD

**Issue by medzin** [hashicorp/terraform-provider-google#7126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.29
+ provider.external v1.2.0
+ provider.google v3.36.0
+ provider.google-beta v3.36.0
+ provider.kubernetes v1.12.0
+ provider.local v1.4.0
```

### Affected Resource(s)

* `google_dataflow_job`
 

### Terraform Configuration Files

```tf
resource "google_dataflow_job" "XXX" {
  name                  = "XXX"
  template_gcs_path     = "XXX"
  temp_gcs_location     = "XXX"
  region                = "europe-west3"
  zone                  = "europe-west3-a"
  subnetwork            = "XXX"
  network               = "staging"
  max_workers           = "1"
  service_account_email = "serviceAccount:${var.dataflow_pubsub_to_bq_service_account.email}"

  parameters = {
    inputTopic      = "XXX"
    outputTableSpec = "XXX"
  }
}
```

### Expected Behavior

The definition should create a dataflow job.

### Actual Behavior

I get the following error:

```
Error: googleapi: Error 400: (c60e031d12c3026c): Current user cannot act as service account serviceAccount:XXX
```

### Important Factoids

* I'm authenticating as a user with organization `roles/owner` and `roles/iam.serviceAccountUser` roles
* I'm using credentials generated by `gcloud auth application-default login`

**Comment by edwardmedia** [comment]
@medzin can you review below doc to see if you have proper roles assigned? 
https://cloud.google.com/dataflow/docs/concepts/access-control#example_role_assignment

**Comment by medzin** [comment]
@edwardmedia I added `roles/dataflow.admin` explicitly to my account and I still get the same error. I'm able to create jobs with selected service account (I see Compute nodes using it) from the Console so I suspect that may be a problem with a way Terraform call the GCP API or the API itself.

**Comment by edwardmedia** [comment]
@medzin are you aware of the Dataflow's [controller](https://cloud.google.com/dataflow/docs/concepts/security-and-permissions#cloud_dataflow_service_account) ? If not, you may also want to review below doc as well. 
https://cloud.google.com/dataflow/docs/concepts/security-and-permissions

**Comment by medzin** [comment]
Following gcloud command works without any problems (it is using the same user account as the Terraform code):

```
gcloud dataflow jobs run XXX \
         --gcs-location gs://XXX \
         --region europe-west3 --subnetwork XXX \
         --network staging --service-account-email XXX@XXX.iam.gserviceaccount.com \
         --staging-location gs://XXX \
         --parameters inputTopic=XXX,outputTableSpec=XXX:XXX \
         --max-workers 1 --project XXX
```

**Comment by edwardmedia** [comment]
@medzin The error was from dataflow api. There are two accounts `Cloud Dataflow service account` and `Controller service account` involved. When you say  `(it is using the same user account as the Terraform code)`, which account were you refer to? Or both?

**Comment by edwardmedia** [comment]
@medzin  can you provider both debug logs from gcloud and Terraform executions? We may compare what the difference is.

**Comment by edwardmedia** [comment]
@medzin  is this still an issue with you?

**Comment by medzin** [comment]
@edwardmedia yeah, give me a moment to prepare logs.

**Comment by edwardmedia** [comment]
@medzin Closing this issue. Please feel free to reopen it once you have the logs. Thanks
