### ISSUE TITLE
GCP Slack invalid

### ISSUE THREAD

**Issue by galan** [hashicorp/terraform-provider-google#7127]
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

I receive a 404 for the Slack mentioned above, can you please update the pointer to the correct one (is there one?).

**Comment by galan** [comment]
Yes, found one. You might update the pointer to https://cloud.google.com/community or the slack channel mentioned there. Thanks.

**Comment by edwardmedia** [comment]
Closing this as this issue seems to be not Terraform Provider Google related. Reopen it if it is and detailed config is needed. Thanks

**Comment by galan** [comment]
@edwardmedia Sorry when my request was confusing, but it is related. The link mentioned above will be displayed when creating a Github Issue in this repository when using "Question" as template: https://github.com/hashicorp/terraform-provider-google/issues/new?template=question.md

So you might update the template please, thank you.
