### ISSUE TITLE
Add DNS Managed Zone ID

### ISSUE THREAD

**Issue by hmoravec** [hashicorp/terraform-provider-google#7128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Each Managed DNS zone in GCP has unique ID ([see the id field here](https://cloud.google.com/dns/docs/reference/v1/managedZones)). The `google_dns_managed_zone` resource does not have this field (it has [`id` field](https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html#attributes-reference) but it is something different).

I would need to get the `ID` so I can pass it to ExternalDNS controller configuration which can identify DNS zones either by domain or by ID. In cases where I have both private and public zone with the same domain, I need to use the ID. Because the ID is not available in Terraform resource, it is not possible to automate the ExternalDNS deployment.

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration

There should be attribute with managed zone ID, e.g.
```tf
zone_id=1930303173991938365
```

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6062
