### ISSUE TITLE
tf destroy google_sql_user fails for postgres if an application has connected to the database

### ISSUE THREAD

**Issue by erniebilling** [hashicorp/terraform-provider-google#7135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: 0.12.29
terraform-provider-google: 3.36.0

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
variable db_instance_name { type = string }

resource "random_string" "username" {
  length = 16
  special = false
  number = false
}

resource "random_password" "password" {
  length = 64
  override_special = "~_-."
  min_upper = 2
  min_lower = 2
  min_special = 2
}

resource "google_sql_user" "user" {
  name     = random_string.username.result
  instance = var.db_instance_name
  password = random_password.password.result
}
```

### Expected Behavior

`tf destroy` should succeed and remove the sql user 

### Actual Behavior

`tf destroy` fails with 

`failed to deleteuser wPznSqvlicrBRoQd in instance csb-postgres-2325f2fb-9eb2-40a8-848c-128f792adbee:  exit status 1`

### Steps to Reproduce

1. `terraform apply` to create a sql user on a postgres database
2. Attach an application to the database
3. Shutdown that application
4. `terraform destroy` to attempt to destroy the user

**Comment by edwardmedia** [comment]
@erniebilling I can't repro it as I see  `destroy` succeeded. Can you post your debug log.

**Comment by edwardmedia** [comment]
@erniebilling is this still an issue with you?

**Comment by edwardmedia** [comment]
@erniebilling closing the issue as assuming it is no longer an issue with you.
