### ISSUE TITLE
 google_cloudbuild_trigger unable to create cloud build trigger within github.

### ISSUE THREAD

**Issue by priyankak1212** [hashicorp/terraform-provider-google#7138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 terraform -v
Terraform v0.12.28
+ provider.google v3.36.0
+ provider.google-beta v3.36.0

Your version of Terraform is out of date! The latest version
is 0.13.1. You can update by downloading from https://www.terraform.io/downloads.htm

### Affected Resource(s)

google_cloudbuild_trigger

### Terraform Configuration Files

resource "google_cloudbuild_trigger" "testing" {
  provider =  google-beta
  project   =  "testing"
  github {
    owner = "organization_name"
    name  = "repo-name"
    push {
      branch = "test"
    }
  }

  description = "testing environment."
  filename = "cloudbuild.yaml"
  
}

### Panic Output

Error: Error creating Trigger: googleapi: Error 400: Repository mapping does not exist. Please visit https://console.cloud.google.com/cloud-build/triggers/connect?project=****** to connect a repository to your project

### Expected Behavior

Above terraform script should create cloud build trigger withing Github App.

### Actual Behavior

It's giving me error "Error: Error creating Trigger: googleapi: Error 400: Repository mapping does not exist."

### Steps to Reproduce

Write an appropriate .tf file as above
terraform plan
terraform apply

### References

* #0000

**Comment by edwardmedia** [comment]
@priyankak1212 it works for me. Can you share you debug log? I noticed the error massage. Can you follow the suggestion to proceed?

**Comment by priyankak1212** [comment]
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloudbuild_trigger.testing will be created
  + resource "google_cloudbuild_trigger" "testing" {
      + create_time = (known after apply)
      + description = "testing environment."
      + filename    = "cloudbuild.yaml"
      + id          = (known after apply)
      + name        = (known after apply)
      + project     = "testing"
      + trigger_id  = (known after apply)

      + github {
          + name  = "repo-name"
          + owner = "organization_name"

          + push {
              + branch = "test"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by priyankak1212** [comment]
Debug Output:-

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloudbuild_trigger.testing will be created
  + resource "google_cloudbuild_trigger" "testing" {
      + create_time = (known after apply)
      + description = "testing environment."
      + filename    = "cloudbuild.yaml"
      + id          = (known after apply)
      + name        = (known after apply)
      + project     = "testing"
      + trigger_id  = (known after apply)

      + github {
          + name  = "repo-name"
          + owner = "organization_name"

          + push {
              + branch = "test"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by priyankak1212** [comment]
Need to connect github repository manually and above script is worked for creating cloud build trigger. Does terraform support automation for connecting repository?

**Comment by edwardmedia** [comment]
@priyankak1212  I was looking for the debug output right after you type "yes" for "terraform apply". Are you aware of **TF_LOG**? You may create below environment variable if you haven't done so. 
```
TF_LOG=DEBUG
```

**Comment by edwardmedia** [comment]
@priyankak1212 is this still an issue with you?

**Comment by priyankak1212** [comment]
> @priyankak1212 is this still an issue with you?

Resolved.

**Comment by angelkok** [comment]
I can replicate the issue and the manual workaround @priyankak1212 described. In order to use the GitHub repo, I first had to manually connect the repository through Cloud Build | Triggers | CONNECT REPOSITORY. Once the repository is linked, my terraform issue described here went away. Connecting process opens a window to GitHub repo search to link individual repos. I'm not sure yet how to get around this.
