### ISSUE TITLE
CloudSQL MYSQL_8_0 Error 400: Invalid request: Point-in-time recovery can only be enabled for Postgres instances.

### ISSUE THREAD

**Issue by r0bj** [hashicorp/terraform-provider-google#7147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/-/google v3.36.0
+ provider registry.terraform.io/-/google-beta v3.36.0
+ provider registry.terraform.io/hashicorp/google v3.36.0
+ provider registry.terraform.io/hashicorp/google-beta v3.36.0
```
### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "sql" {
  name             = "test"
  database_version = "MYSQL_8_0"
  region           = var.region

  settings {
    tier              = "db-g1-small"

    backup_configuration {
      enabled                        = true
      binary_log_enabled             = true
      point_in_time_recovery_enabled = true
    }
  }
}
```

### Expected Behavior

`google_sql_database_instance` instance is created with `point_in_time_recovery_enabled` option set to true.

### Actual Behavior

```
Error: Error, failed to create instance test4: googleapi: Error 400: Invalid request: Point-in-time recovery can only be enabled for Postgres instances., invalid
```

### Important Factoids

Creating `google_sql_database_instance` instance without option terraform `point_in_time_recovery_enabled = true` creates instance successfully and option `Point-in-time recovery` is enabled anyway:

<img width="219" alt="Screenshot 2020-08-28 at 14 39 10" src="https://user-images.githubusercontent.com/1297747/91617163-41d4dc00-e93c-11ea-9dcf-5254fe8d53c1.png">

**Comment by edwardmedia** [comment]
I can repro this issue. According below doc, it appears `Point-in-time recovery` is supported with MySql. 

https://cloud.google.com/sql/docs/mysql/backup-recovery/pitr

**Comment by edwardmedia** [comment]
I have filed below issue against CloudSql API for tracking. Closing this issue
b/166921988

**Comment by c2thorn** [comment]
`binary_log_enabled` is the correct field for enabling Point-in-time recovery for MySql. We can check user's configs during `plan` and point them to `binary_log_enabled` in the error message.
