### ISSUE TITLE
Resource project id isnt optional

### ISSUE THREAD

**Issue by Arola1982** [hashicorp/terraform-provider-google#7150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.1

### Affected Resource(s)

google_compute_instance

### Terraform Configuration Files

```
resource "google_compute_instance" "default" {
  name         = "free1"
  machine_type = "f1-micro"
  zone         = "us-west2-a"

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network = "default"
  }
}
```

### Debug Output

No need

### Panic Output

```
google_compute_instance.default: Creating...

Error: project: required field is not set

  on main.tf line 13, in resource "google_compute_instance" "default":
  13: resource "google_compute_instance" "default" {
```

### Expected Behavior

The resource should have been created, based off the project id defined in the provider

### Actual Behavior

Panic

### Steps to Reproduce

1. Define the google provider, supplying the project id
2. Define the resource block, without putting the optional project id
3. terraform apply

* #0000

**Comment by edwardmedia** [comment]
@Arola1982 how did you `Define the google provider, supplying the project id`? Below is the doc that shows the recommended ways for Google Provider.
https://www.terraform.io/docs/providers/google/guides/provider_reference.html

**Comment by Arola1982** [comment]
Hi @edwardmedia thank you for getting beck to me so quickly

https://registry.terraform.io/providers/hashicorp/google/latest/docs shows

Under the use provider option for terraform 0.13 i also added the project region and zone:

```terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.36.0"
      project = "xxxx-xxxx-123456"
      region  = "us-west2"
      zone    = "us-west2-a"
    }
  }
}
```

Following the getting started section under provisioning your resources - https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started i know the provider in the example is for 0.12 and below,  but in the example the project is in the provider and not in the resource.

So that is what i did when i got the error. Only by supplying the project in the resource did provisioning work.

In the docs for the resource - https://www.terraform.io/docs/providers/google/r/compute_instance.html

It says:

```
project - (Optional) The ID of the project in which the resource belongs. If it is not provided, the provider project is used.
```

But from what i experienced it seemed mandatory as it didnt pick the project up from the provider as it says.

I may have done something wrong, but reading the docs i think i followed what was expected.

As my understanding was that setting the project in the provider would effectively become the used value, but then if supplying a different project in the resource that would then become the project used and ignore the provider supplied project.

**Comment by edwardmedia** [comment]
@Arola1982 can you try adding `provider` inside the resource?
```tf 
resource "google_compute_instance" "default" {
  provider = google
  ...
}
```

**Comment by Arola1982** [comment]
@edwardmedia 

```
resource "google_compute_instance" "default" {
  name         = "free1"
  machine_type = "f1-micro"
  zone         = "us-west2-a"
  provider = google

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network = "default"
  }
}
```

Results in:

```
google_compute_instance.default: Creating...

Error: project: required field is not set

  on main.tf line 13, in resource "google_compute_instance" "default":
  13: resource "google_compute_instance" "default" {
```

To be honest if that worked it would seem kind of a pointless option given that the resource is google_compute_instance you'd think it was implied that it was a google provider.

I dont mind having to provide the project within the resource, the only reason i raised this really was to raise awareness of the documentation implying that project within the resource was optional, but currently it seems to be a requirement. Maybe its not exactly a bug, more that the documentation needs updating

**Comment by edwardmedia** [comment]
@Arola1982 below is the excerpt from the link I mentioned earlier. `optional` is based on the condition when you have already setup the **default project**. Same applied for other attributes, like `region`, `zone`, etc. This saves users many typing for each resources if they share same `project`. I don't think you can create resources in a project with specifying the `project`. 

```
project - (Optional) The default project to manage resources in. If another project is specified on a resource, it will take precedence. This can also be specified using the GOOGLE_PROJECT environment variable, or any of the following ordered by precedence.

GOOGLE_PROJECT
GOOGLE_CLOUD_PROJECT
GCLOUD_PROJECT
CLOUDSDK_CORE_PROJECT
```
I am closing this issue as the default behavior remains working. Please reopen it if you want to continue the conversation. If you want to provide suggestions to make the document better and clearer, please file another issue so it can be triaged. Thank you
