### ISSUE TITLE
http://www.gstatic.com/ipranges/goog.json returning 403 breaks google_netblock_ip_ranges

### ISSUE THREAD

**Issue by cagataygurturk** [hashicorp/terraform-provider-google#7155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.35.0
+ provider registry.terraform.io/hashicorp/google-beta v3.35.0

### Affected Resource(s)

* google_netblock_ip_ranges

### Description

http://www.gstatic.com/ipranges/goog.json currently returns 403 which breaks "google_netblock_ip_ranges" resource. https://www.gstatic.com/ipranges/goog.json works without problem though.

**Comment by cagataygurturk** [comment]
Issue reported to Google also https://issuetracker.google.com/u/2/issues/167014919

**Comment by ct-dh** [comment]
Just an FYI that the upstream issue seems to be blocked waiting for CLA approval/signoff. I am guessing this won't make it into a release for roughly a week? It's blocking all our deploys currently.

**Comment by cagataygurturk** [comment]
Hello @slevenick . When will this change be shipped in a new release? Google updated the documentation with https, it means that http endpoint will unlikely to return. Currently deployments are broken.
Thanks.

**Comment by slevenick** [comment]
@cagataygurturk It should be included in the release expected to go out today.
