### ISSUE TITLE
Figure out a way to ensure tests get run on community PRs in MM before they're merged

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#7163]

**Comment by slevenick** [comment]
Can be done by commenting `/gcbrun` on a MM PR after the diffs have been generated. This may require contributors to rebase off master as the cloudbuild file must exist on their branch to be able to run.

This runs VCR tests in REPLAYING mode, then runs any failing tests in RECORDING mode on their branch.
