### ISSUE TITLE
GCS default service account during project creation

### ISSUE THREAD

**Issue by riteshnanda09** [hashicorp/terraform-provider-google#7165]
Hello Guys,

I use Terraform to create projects in GCP, during project creation I want to make sure gcs default service account is added to a gsuite group, right now I use interpolation to form the service account email address and add it as a member to the group rather using the below data source because using data source will show as a change in every consecutive run to the state.

```hcl
data "google_storage_project_service_account" "gcs_account" {
}
```

But doing the interpolation way means the service account is not activated and gsuite group membership of the service account shows as a `user` rather `ServiceAccount` due to which gcp IAM doesn't detect the service account and the access provided doesn't work.

Does someone has also faced this issue or there is something I am missing?

I also tried enabling the gcs API services, seeing if that will activate the service account.

**Comment by edwardmedia** [comment]
@riteshnanda09 you may want to look into some third party providers to see if that works for you
https://github.com/DeviaVir/terraform-provider-gsuite

**Comment by upodroid** [comment]
I believe this is related a new behaviour when you enable APIs recently as mentioned in https://github.com/hashicorp/terraform-provider-google/issues/7020. You will need to enable the API and then make this additional api call to create the email and use that output for other operations.

**Comment by edwardmedia** [comment]
@riteshnanda09  is this still an issue with you?

**Comment by riteshnanda09** [comment]
Thanks @upodroid i see how it can help me with other service identities which i will need to do in future.

But specifically for gcs which i was looking for  , when i try to enable `storage.googleapis.com` it says 

```
Error: Error creating Service Identity: googleapi: Error 400: Service storage.googleapis.com has not been configured for service identities.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
    "violations": [
      {
        "subject": "?error_code=185010\u0026service_name=storage.googleapis.com",
        "type": "googleapis.com"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "serviceusage.googleapis.com",
    "metadata": {
      "service_name": "storage.googleapis.com"
    },
    "reason": "IAM_SERVICE_NOT_CONFIGURED_FOR_IDENTITIES"
  }
]
```

**Comment by riteshnanda09** [comment]
Thanks Guys .
