### ISSUE TITLE
Provide google_container_registry_image resource

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-provider-google#7175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be very helpful to have `google_container_registry_image` not only as a datasource but also as a resource.
This resource could then mirror an image via a provided source.

### New or Affected Resource(s)

* google_container_registry_image

### Potential Terraform Configuration

```tf
resource "google_container_registry_image" "foo" {
  name = "bar"
  tag = "0.12.18-orig"
  source_image = "hashicorp/terraform"
  source_tag = "0.12.18"
  # source_digest as an alternative would be great
```

### References

For us, this is getting more interesting as Docker Hub is adding rate limiting and thus we will have the use case of mirroring images quite frequently.

* #0000

**Comment by danawillow** [comment]
Is this something you could use the docker provider for?

**Comment by AndreasBergmeier6176** [comment]
> Is this something you could use the docker provider for?

If I am reading the docs right, there is no pushing there either.
As a bonus I would really like to have something that works regardless of a docker daemon on a machine.

**Comment by danawillow** [comment]
Got it. I don't think GCP has the APIs that would be necessary to add this as a resource, but please let me know if you're aware of any that we could use. In the meantime, a module like https://registry.terraform.io/modules/neomantra/mirror/docker/0.3.0 might do what you're looking for. It does require the docker daemon, and I'm not sure there's much of a way around that at this time.

**Comment by AndreasBergmeier6176** [comment]
> In the meantime, a module like https://registry.terraform.io/modules/neomantra/mirror/docker/0.3.0 might do what you're looking for.

That looks promising. Thanks for the pointer.
Probably what would be great is having a Provider which internally would make use of Skopeo.

**Comment by danawillow** [comment]
Closing this out since it's not something we'll realistically do here. You could probably try filing a feature request on the docker provider.

**Comment by AndreasBergmeier6176** [comment]
> Probably what would be great is having a Provider which internally would make use of Skopeo

Just FYI, I took a look at that. Problem with Skopeo is that it uses CGO and is quite involved to build. Thus not a thing I want to tackle right now. Will have a look at the docker module next.
