### ISSUE TITLE
google_compute_forwarding_rule expects region when it's global

### ISSUE THREAD

**Issue by icco** [hashicorp/terraform-provider-google#7176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
]$ terraform -v
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/google v3.37.0
+ provider registry.terraform.io/hashicorp/google-beta v3.37.0
```

### Affected Resource(s)

* google_compute_forwarding_rule

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google      = "~> 3.37"
    google-beta = "~> 3.37"
  }
}

variable "project" {
  type    = string
  default = ""
}

resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
  provider              = google-beta
  name                  = "cloudrun-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"
  project               = var.project
  cloud_run {
    service = google_cloud_run_service.cloudrun_neg.name
  }
}

resource "google_cloud_run_service" "cloudrun_neg" {
  provider = google-beta
  name     = "cloudrun-neg"
  location = "us-central1"
  project  = var.project

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}

resource "google_compute_backend_service" "example" {
  provider = google-beta
  name     = "example"
  project  = var.project

  backend {
    group = google_compute_region_network_endpoint_group.cloudrun_neg.id
  }
}

resource "google_compute_global_address" "example" {
  name    = "example-address"
  project = var.project
}

resource "google_compute_url_map" "example" {
  name            = "example"
  provider        = google-beta
  project         = var.project
  default_service = google_compute_backend_service.example.id
}

resource "google_compute_target_http_proxy" "http" {
  provider = google-beta
  name     = "example"
  project  = var.project

  url_map = google_compute_url_map.example.id
}

resource "google_compute_forwarding_rule" "http" {
  name    = "example"
  project = var.project

  ip_protocol           = "TCP"
  ip_address            = google_compute_global_address.example.address
  load_balancing_scheme = "EXTERNAL"
  port_range            = "80"
  target                = google_compute_target_http_proxy.http.id
  network_tier          = "PREMIUM"
}
```

### Debug Output

https://gist.github.com/icco/1388bc17ff2000591b527669315a3b4a

### Panic Output

N/A

### Expected Behavior

The forwarding rule should be created.

### Actual Behavior

```
Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

If you set a region (which shouldn't be needed)

```
Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.target': 'https://compute.googleapis.com/compute/beta/projects/----/global/targetHttpProxies/example'. Invalid target type TARGET_HTTP_PROXY for forwarding rule in scope REGION, invalid
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform-provider-google/issues/7051

**Comment by icco** [comment]
@slevenick FYI

**Comment by slevenick** [comment]
Does https://www.terraform.io/docs/providers/google/r/compute_global_forwarding_rule.html not work for this use case? I believe the `google_compute_forwarding_rule` requires a region

**Comment by icco** [comment]
Yes it does #faceplam. Thank you.
