### ISSUE TITLE
google_monitoring_alert_policy doesn't allow filter without resource.type 

### ISSUE THREAD

**Issue by hamza3202** [hashicorp/terraform-provider-google#7179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.25
+ provider.google v3.36.0
+ provider.google-beta v3.37.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_logging_metric" "resource-created" {

  filter = "protoPayload.methodName=~\"[A-z0-9\\.]+(Create|insert)[A-z0-9]*\" AND protoPayload.@type=\"type.googleapis.com/google.cloud.audit.AuditLog\" AND protoPayload.status.code=0 "
  name   = "resource-created"
  description = "Some resource is created"

  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    display_name = "Resource Created"
    labels {
      key = "Creator"
      description = "The authentication principal used to create this resource"
      value_type = "STRING"
    }
    labels {
      key = "MethodName"
      description = "The name of the method used to create resource"
      value_type = "STRING"
    }
    labels {
      key = "ServiceName"
      description = "The name of the google service used"
      value_type = "STRING"
    }
    labels {
      key = "Project"
      description = "The project in which resource was created"
      value_type = "STRING"
    }
    labels {
      key = "InsertId"
      description = "The unique ID of this request"
      value_type = "STRING"
    }
  }
  label_extractors = {
    "Creator" = "EXTRACT(protoPayload.authenticationInfo.principalEmail)"
    "MethodName" = "REGEXP_EXTRACT(protoPayload.methodName, \"[A-z0-9\\.]+(Create[A-z0-9]+)\")"
    "ServiceName" = "EXTRACT(protoPayload.serviceName)"
    "Project" = "EXTRACT(resource.labels.project_id)"
    "InsertId" = "EXTRACT(insertId)"
  }

}

resource "google_monitoring_alert_policy" "resource-created" {
  display_name = "Resource Created"
  combiner     = "OR"
  conditions {
    display_name = "Resource Created"
    condition_threshold {
      filter     = "metric.type=\"logging.googleapis.com/user/resource-created\""
      duration   = "0s"
      comparison = "COMPARISON_GT"
      trigger {
        count = 1
      }
      aggregations {
        alignment_period   = "60s"
        cross_series_reducer = "REDUCE_COUNT"
        per_series_aligner = "ALIGN_COUNT"
      }
    }
  }
}
```

### Expected Behavior

The alert policy should be created as I have already tested via google cloud console and this configuration works

### Actual Behavior

I get the following error
```
Error: Error updating AlertPolicy "projects/st1-monitoring-dev/alertPolicies/12023675363527204754": googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="logging.googleapis.com/user/resource-created"": must specify a restriction on "resource.type" in the filter; see "https://cloud.google.com/monitoring/api/resources" for a list of available resource types.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The project in which you are trying to create this

**Comment by edwardmedia** [comment]
@hamza3202 can you post the debug log?

**Comment by hamza3202** [comment]
@edwardmedia [here is the debug log](https://gist.github.com/hamza3202/e19f694cd91232b3b62b9df8f746a3eb).

**Comment by edwardmedia** [comment]
@hamza3202 note the error message `"Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of \"metric.type=\"logging.googleapis.com/user/resource-created\"\": must specify a restriction on \"resource.type\" in the filter; see \"https://cloud.google.com/monitoring/api/resources\" for a list of available resource types.",` 

You might want to follow the suggestions to investigate. Do you see `logging.googleapis.com/user/resource-created` available in the list? 

I have tried below filter and it seems working. BTW, this error is from `monitoring` api, likely this type of issues will be resolved in api. 
```
filter          = "metric.type=\"logging.googleapis.com/exports/byte_count\" AND resource.type=\"logging_sink\""
```

**Comment by edwardmedia** [comment]
@hamza3202 as I explained above, you may want to seek further assistance from `Monitoring` api.  There is not much we can do in the provider. I am closing this issue. Free free to reopen it if you think it is an issue with the provider.

**Comment by hamza3202** [comment]
Out of curiosity, does the console UI not use the same API? because I am able to create a resource in the UI, import it into terraform but not able to use it because of this field. So the issue might be in the provider?
