### ISSUE TITLE
google_compute_region_backend_service 2.x->3.x upgrade showing possible erroneous diffs in plan

### ISSUE THREAD

**Issue by nyc3-mikekot** [hashicorp/terraform-provider-google#7183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

----

Running Terraform Version : 0.12.18

Attempting to upgrade from Terraform Google Provider 2.20.0 to 3.x (as of this moment, 3.37.0)

The resource definition:

```
resource "google_compute_region_backend_service" "default" {
  name    = var.name
  project = var.project
  dynamic "backend" {
    for_each = var.backends
    content {
      group = backend.value["group"]
    }
  }
  protocol      = "UDP"
  health_checks = [google_compute_health_check.default.0.self_link]
}
```

The plan shows the following diff when running on version 3.37.0 (there is no diff on 2.20.0, though)

```
        - backend {
          - balancing_mode               = "CONNECTION" -> null
          - capacity_scaler              = 0 -> null
          - failover                     = false -> null
          - group                        = "https://www.googleapis.com/compute/v1/projects/AAAA/regions/BBB/instanceGroups/CCC" -> null
          - max_connections              = 0 -> null
          - max_connections_per_endpoint = 0 -> null
          - max_connections_per_instance = 0 -> null
          - max_rate                     = 0 -> null
          - max_rate_per_endpoint        = 0 -> null
          - max_rate_per_instance        = 0 -> null
          - max_utilization              = 0 -> null
        }
      - backend {
          - balancing_mode               = "CONNECTION" -> null
          - capacity_scaler              = 0 -> null
          - failover                     = true -> null
          - group                        = "https://www.googleapis.com/compute/v1/projects/AAA/regions/BBB/instanceGroups/DDD" -> null
          - max_connections              = 0 -> null
          - max_connections_per_endpoint = 0 -> null
          - max_connections_per_instance = 0 -> null
          - max_rate                     = 0 -> null
          - max_rate_per_endpoint        = 0 -> null
          - max_rate_per_instance        = 0 -> null
          - max_utilization              = 0 -> null
        }
      + backend {
          + balancing_mode = "CONNECTION"
          + failover       = (known after apply)
          + group          = "https://www.googleapis.com/compute/v1/projects/AAA/regions/BBB/instanceGroups/DDD"
        }
      + backend {
          + balancing_mode = "CONNECTION"
          + failover       = false
          + group          = "https://www.googleapis.com/compute/v1/projects/AAA/regions/BBB/instanceGroups/CCC"
        }
      - failover_policy {
          - disable_connection_drain_on_failover = false -> null
          - drop_traffic_if_unhealthy            = false -> null
          - failover_ratio                       = 0 -> null
        }
```

Happy to provide more info if needed, sensitive information was find/replaced out

Happy to provide more information if needed; based on what I'm seeing there aren't actually any diffs, but it looks like terraform is suggesting the backends still need to be swapped out (and `failover_policy` needs to be removed, but it had never been explicitly defined before by the looks of it)

**Comment by megan07** [comment]
Hi @nyc3-mikekot! I'm sorry that you're seeing these diffs. I wasn't able to recreate it with a simple test I wrote up.
A few questions I have for you
- was your order of operations after changing the provider version `terraform init` then `terraform plan`?
- is there any way your infrastructure could have changed outside of terraform?
- can you provide me with your `var.backends`?

i'm curious how one backend has a `failover=true` and the other is `failover=false` when the resource configuration doesn't seem to be setting it for either.
it's also strange that i didn't even see `failover` show up until after I ran `terraform apply`

**Comment by nyc3-mikekot** [comment]
Hi @megan07 ; i think you're just about correct about all of these assertions.

It's very likely someone edited these resources outside of terraform given that the configs I shared did not have these values (I was originally of the impression that perhaps these were all new things simply being tracked as of a 3.x change).

I think what makes the most sense to do here is to align the configs with the use of a few conditional dynamic blocks to make sure there's no diffs on my end when running plans (and lo and behold, that also happens to be the case from my testing thus far)
