### ISSUE TITLE
JSONBytesEqual function go panic >= 3.32.0 for bigquery tables

### ISSUE THREAD

**Issue by nyc3-mikekot** [hashicorp/terraform-provider-google#7193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Terraform version is 0.12.18

Go stacktrace: https://gist.github.com/nyc3-mikekot/34efee4e3ed5beb9e4f15016f260ec91

The error is with `JSONBytesEqual` function and this stacktrace is being thrown for our `google_bigquery_table` schemas on version 3.32.0 and greater (I tested with 3.31.0 and got a clean plan). 

In terms of reproducability, it currently happens 100% of the time with any plan; I haven't gotten up to the point where I know the exact steps to reproduce outside of plugging in our state file + json configuration, but above is the information I currently do have.

**Comment by nyc3-mikekot** [comment]
Note: This might also have relevance: the current state file is based off an apply from provider version 2.20.0, and we are thus trying to upgrade to a newer 3.x version (3.32.0 being a breaking change as reported above)

**Comment by megan07** [comment]
Hi @nyc3-mikekot ! Sorry that you're running into difficulties in your upgrade. Would you be able to share what one of your schemas looks like by chance? Thanks!

**Comment by nyc3-mikekot** [comment]
Hi @megan07 upon closer inspection, I believe I've found the culprit on our end. 

There is one particular schema we have in which someone made the key name have a leading whitespace, so it looks like: `"name ":` rather than `"name":`. This was being accepted as valid JSON in previous versions of the provider, however 😆 . After fixing the name of the key, the panic is no longer persisting on subsequent plans

**Comment by megan07** [comment]
Hi @nyc3-mikekot! Thanks for the update! I have created a PR that will log an error if `name` is not defined. This will avoid the panic, but show a diff. The diff might be confusing because the whitespace error won't appear, but the debug logs will point out where the error is. Does that sound ok?

**Comment by nyc3-mikekot** [comment]
That sounds good to me!
