### ISSUE TITLE
global or zonal IAP SSH tunnel  

### ISSUE THREAD

**Issue by YannSfeir** [hashicorp/terraform-provider-google#7196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
 
Identity Aware Proxy (IAP) SSH access can be set up not only for an specific instance, but also for a zone or globally. And that's my problem with the google_iap_tunnel_instance_iam_policy, google_iap_tunnel_instance_iam_binding and google_iap_tunnel_instance_iam_member because I can't use it with a Managed Instances Group for instance, considering instances can be replaced at any time and are on several different zones.

I would like to be able to set up a IAP SSH tunnel for all my instances, even with the instances not already created. Basically, zone and instance should be optional fields.

### New or Affected Resource(s)

google_iap_tunnel_iam_policy
google_iap_tunnel_iam_binding
google_iap_tunnel_iam_member

### Potential Terraform Configuration

```
resource "google_iap_tunnel_iam_policy" "policy" {
  project = google_compute_instance.tunnelvm.project
  policy_data = data.google_iam_policy.admin.policy_data
}

resource "google_iap_tunnel_iam_binding" "binding" {
  project = google_compute_instance.tunnelvm.project
  role = "roles/iap.tunnelResourceAccessor"
  members = [
    "user:jane@example.com",
  ]
}

resource "google_iap_tunnel_iam_member" "member" {
  project = google_compute_instance.tunnelvm.project
  role = "roles/iap.tunnelResourceAccessor"
  member = "user:jane@example.com"
}

```
* #0000

**Comment by semangard** [comment]
+1
For sure it is a mandatory missing feature.

**Comment by YannSfeir** [comment]
Hello,

First of all, thanks for your quick answer. 

But, the main issue with assigning the role  roles/iap.tunnelResourceAccessor with IAM is we can't use conditions based on access levels. However, our IAP tunnels have a couple of restrictions based on access levels, which we won't be able to use with IAM...

So, we really need that kind of resources.

Thanks for your help!

**Comment by upodroid** [comment]
https://cloud.google.com/iam/docs/conditions-overview#example-access-level

**Comment by danawillow** [comment]
Just to link the prior request for this: https://github.com/hashicorp/terraform-provider-google/issues/5577.

@upodroid, I'm pretty sure that specific condition is only valid for IAP resources, and doesn't work at the project IAM level. If you've been able to get it to work properly, I bet the subscribers on this issue would be interested in an example.

**Comment by upodroid** [comment]
I assumed the OP wasn't using conditions but later on he talked about access levels which can be specified in IAM conditions and work if you use the iap.googleapis.com setIamPolicy calls.

On that note, there are other resources such as backend services have iam methods which we don't have resources for. I'll open separate issues for those.
