### ISSUE TITLE
can not move google_project from org_id to folder_id

### ISSUE THREAD

**Issue by dsiebel** [hashicorp/terraform-provider-google#7197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/deviavir/gsuite v0.1.54
+ provider registry.terraform.io/hashicorp/google v3.35.0
+ provider registry.terraform.io/hashicorp/google-beta v3.35.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

originally tested with `v0.13.0`, then upgraded for the purpose of this issue report.

### Affected Resource(s)

* `google_project`

### Terraform Configuration Files

```hcl
resource "google_project" "project" {
  name            = "dsiebel-pg-20200904-001"
  project_id      = "dsiebel-pg-20200904-001"
  org_id          = "1234567"
}

// changed to:

resource "google_project" "project" {
  name            = "dsiebel-pg-20200904-001"
  project_id      = "dsiebel-pg-20200904-001"
  folder_id       = "192837465"
}

```

### Expected Behavior

Project is "moved" from organization/root level to a folder.

I tested this with `group_id = null`, `group_id = ""` and removing `group_id` entirely.
The only way to "fix" is by running `gcloud alpha projects move ${project_id} --folder=${folder_id}` manually and then re-applying terraform state.

### Actual Behavior

Folder is "added" to the resource in addition to the `org_id` which does not get removed so that both are set:

```
Terraform will perform the following actions:

  # google_project.project will be updated in-place
  ~ resource "google_project" "project" {
        auto_create_network = true
      + folder_id           = "192837465"
        id                  = "projects/dsiebel-pg-20200904-001"
        labels              = {}
        name                = "dsiebel-pg-20200904-001"
        number              = "5647383921"
        org_id              = "1234567"
        project_id          = "dsiebel-pg-20200904-001"

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

[...]

Error: 'org_id' and 'folder_id' cannot be both set.

  on test.tf line 20, in resource "google_project" "project":
  20: resource "google_project" "project" {
```

### Steps to Reproduce

1. Create a `google_project` with `org_id` parameter
2. `terraform apply`
3. Remove `org_id` and add `folder_id`
4. `terraform apply`

**Comment by dsiebel** [comment]
After some more digging I also found this and was wondering if and how it might be related
https://github.com/hashicorp/terraform-provider-google/issues/5073

**Comment by edwardmedia** [comment]
I can repor this issue. It appears `org_id` is not removed from the `plan` even when it is not listed in the updated config

**Comment by rileykarson** [comment]
Interesting- both `org_id` and `folder_id` are marked as "Optional+Computed" fields. Normally fields consider being unset as being set to the empty string. These fields instead consider being unset to mean they're output-only fields.

You can explicitly specify the empty string to resolve this.

A fix isn't really feasible, unfortunately. It would probably break users if we changed their unset behaviour (they've acted this way for ~3 years) and this is a resource that we _really _really_ don't want to break. I'll roll fixing this into https://github.com/hashicorp/terraform-provider-google/issues/5073.

**Comment by dsiebel** [comment]
I tried seeting `org_id = ""` but it didn't change anything in the behavior.
