### ISSUE TITLE
Label not updated when using google_dns_managed_zone

### ISSUE THREAD

**Issue by tonnihult** [hashicorp/terraform-provider-google#7198]
Hi

When we update the labels in a google_dns_managed_zone nothing happens. The deploy seems to go fine because apply step is green but when running a new plan terraform says that the same change needs to be done.

When looking at cloud logging we also see no patch or update calls done to cloud dns, only get calls. 

//Tonni

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.28

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

Here is an output from `terraform plan` with some edits
```
  ~ resource "google_dns_managed_zone" "feature-team" {
        description  = "zone for sandbox"
        dns_name     = "dns.domain.name."
        id           = "projects/yyy/managedZones/yyy"
      ~ labels       = {
          - "costcenter"  = "something" -> null
            "environment" = "sandbox"
            "ownerteam"   = "a-team"
        }
}
```
And here is the output from `terraform apply`:
```
module.teamsandbox.google_dns_managed_zone.feature-team: Modifying... [id=projects/yyy/managedZones/yyy]
module.teamsandbox.google_dns_managed_zone.feature-team: Modifications complete after 2s [id=projects/yyy/managedZones/yyy]
```

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

Labels in the managed zone are updated according to wanted changes

### Actual Behavior

Labels are not updated, running a new terraform plan shows that the same change needs to be done

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@tonnihult can you post the config code?

**Comment by tonnihult** [comment]
I checked the provider version and we are using 3.35.0. The resource looks like this

```tf
resource "google_dns_managed_zone" "feature-team" {
  depends_on = [google_project_service.enabled-apis]
  name        = "${var.teamname}-domain-name"
  project    = google_project.team-sandbox-project.project_id
  dns_name    = "${var.teamname}.domain.name."
  description = "zone for sandbox"
  dnssec_config {
    state = "on"
  }
  labels = {
    "environment"   = "sandbox"
    "ownerteam"     = var.teamname
  }
}
```

**Comment by edwardmedia** [comment]
@tonnihult I can't repro the issue. In my test, I saw the labels created and updated. I also verified the labels correctly showing up in GCP console. Can you repro the issue using your above code? If yes, can you post the debug logs before and after the config updated?

**Comment by tonnihult** [comment]
Ok. I doubled checked the permissions if there was a problem there but the account that is running the deploy has the dns admin role. Even tested to grant it owner rights but it still did not work. But when I grant myself the dns admin role I have no problem to remove the label through the UI.  

I don't find that there are others with issue for this resource so I'm going to close the issue and do the needed fixes manually for now.
