### ISSUE TITLE
Add Dataplane V2 support for GKE (beta)

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform-provider-google#7207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add[ Dataplane V2](https://cloud.google.com/blog/products/containers-kubernetes/bringing-ebpf-and-cilium-to-google-kubernetes-engine) support for GKE, currently in beta.
Based on the API reference it looks like [surfacing `datapathprovider` ](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#datapathprovider)should allow us to use `ADVANCED_DATAPATH` which enables Dataplane V2. 

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
datapath_provider = "ADVANCED_DATAPATH"
```
datapath_provider supported values include `string{"DATAPATH_PROVIDER_UNSPECIFIED", "LEGACY_DATAPATH", "ADVANCED_DATAPATH"}`
### References

* https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/656

**Comment by brancz** [comment]
I'm gonna try and give this a shot.
