### ISSUE TITLE
google_compute_health_check permadiff if http_health_check.port is not set

### ISSUE THREAD

**Issue by Chupaka** [hashicorp/terraform-provider-google#7210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

$ terraform -v
Terraform v0.12.29
+ provider.google v3.37.0
+ provider.google-beta v3.37.0

(Upgrading from v2 of the provider).

### Affected Resource(s)

* google_compute_health_check

### Terraform Configuration Files

```tf

resource "google_compute_health_check" "backend" {
  name = "hc-backend"

  http_health_check {
    request_path = "/index.php"
  }
}

```

### Expected Behavior

According to the docs (https://www.terraform.io/docs/providers/google/r/compute_health_check.html), for `http_health_check.port`, the default value is 80, so should be no changes in a plan.

### Actual Behavior

Every time I run plan/apply it shows this:

```tf
Terraform will perform the following actions:

  # google_compute_health_check.backend will be updated in-place
  ~ resource "google_compute_health_check" "backend" {
<snip>
      ~ http_health_check {
          - port         = 80 -> null
            proxy_header = "NONE"
            request_path = "/index.php"
        }
<snip>
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
Its working as expected, your state has value 80 (updated from API default value) and config has empty value thus you would see diff. In Place update happens as expected.

**Comment by Chupaka** [comment]
@venkykuberan so how should I use that default value without setting "port = 80" explicitly in my config? Should I remove 80 from the state so that there's no the same diff every time?

**Comment by Chupaka** [comment]
@venkykuberan ping?..

**Comment by pdecat** [comment]
IMO, fields like `port` that have default values set by the API should be `Computed` (in addition to `Optional`) to eliminate permanent diff when not explicitly defined in configuration.

**Comment by pdecat** [comment]
Note: there's some diff suppress code in https://github.com/hashicorp/terraform-provider-google/blob/v3.41.0/google/resource_compute_health_check.go#L77-L111 that should remove the diff if `port_specification` is set to `USE_FIXED_PORT`.
