### ISSUE TITLE
Add API Gateway Resources

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#7212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google released the API Gateway.

https://cloud.google.com/blog/products/serverless/google-cloud-api-gateway-is-now-available-in-public-beta
https://cloud.google.com/api-gateway/docs/reference/rest/v1beta/projects.locations.gateways

### New or Affected Resource(s)

* google_api_gateway_api
* google_api_gateway_config
* google_api_gateway_gateway

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by trevoro** [comment]
Most of the commands to manipulate the cloud gateway seem fairly straightforward. The resources are easy to reference and are unique. The challenge / design decision seems to be mostly based around how to handle the openapi specification yaml file. Is that something that would be embedded into a terraform config / module or would it simply be referenced and edited along side `.tf` files?

**Comment by dinvlad** [comment]
I'd suggest keeping it simple in the beginning, using a regular string field, like so:
```tf
openapi_documents = [yamlencode({
  swagger = "2.0"
  …
})]
```
This is similar to how it can be done, for example, through the `body` argument of `aws_apigatewayv2_api`.
Then if there's need for a dedicated data source, we could add it later without changing this feature.

**Comment by upodroid** [comment]
I'm thinking of having a yaml template that terraform dynamically generates at plan/apply time. As you see in the tutorials you need to supply urls of functions and cloud run services. Maybe some service account emails too. 

https://www.terraform.io/docs/configuration/functions/templatefile.html

**Comment by dinvlad** [comment]
For sure, and the above syntax (`yamlencode`) supports that too.

**Comment by trevoro** [comment]
OK so I dug into what it takes to write these. There's a generator written in ruby that probably needs to be used. It would take me awhile to wrap my head around how that works. I'd appreciate some guidance from the team on the best example resource that's similar to this so I can get an example before digging in. FWIW it's fairly impressive.

**Comment by wvanderdeijl** [comment]
You could also have a look at https://github.com/GoogleCloudPlatform/magic-modules/tree/master/products/servicemanagement which is the confit for Google Cloud Endpoints which is a *very* similar product to the new API Gateway product

**Comment by upodroid** [comment]
I already wrote a PR for this. It is the linked issue that will close this issue.
