### ISSUE TITLE
More service networking resources

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#7213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/service-infrastructure/docs/service-networking/reference/rest/v1/services/addSubnetwork
There are a few others that appear in the discovery docs but not the website at the moment that I believe are also part of this request (roles, at least)

### New or Affected Resource(s)

* google_service_networking_X

### References

* b/167412924

**Comment by nma** [comment]
I've started taking a look at this. If anyone has already taken a look would love to get in touch and share any findings.

**Comment by rileykarson** [comment]
Hey @nma! Did you ever end up taking a look at this?

**Comment by nma** [comment]
Hey @rileykarson. I've started a branch on https://github.com/nma/terraform-provider-google-beta/tree/service-network-subnet

Currently testing a local build.  This resource requires some org folder level permissions, so just in the midst of figuring out how to set that up and also translate it to a 'resource_x_test.go` format.

**Comment by rileykarson** [comment]
Thanks! Marking you as assigned for our tracking purposes. Feel free to reach out if you run into any issues- `terraform-team` internally is the best way to reach the team.

**Comment by rileykarson** [comment]
I'm going to move this into sprints until it's resolved to reflect @nma and @ScottSuarez's ongoing work to get testing infrastructure set up.

**Comment by nma** [comment]
The original customer that requested this feature has went with another solution. There is also no additional demand for the resource, so we can close this ticket for now. 

I will keep my forked branches around for a few quarters in case there is more user demand to reopen this issue.
