### ISSUE TITLE
`google_compute_firewall` can not be updated in place if no `log_config` block is present or `enable_logging` is false or not present

### ISSUE THREAD

**Issue by DeanBrunt** [hashicorp/terraform-provider-google#7220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.29
+ provider.google v3.36.0

### Affected Resource(s)
* google_compute_firewall

### Expected Behaviour

Updating properties of a Google Compute Firewall (when no `log_config` block is present and `enable_logging` is not present or false) should work assuming no properties are invalid.

### Actual Behaviour

Updating any property of an existing Google Compute Firewall (except for `log_config` or `enable_logging`) will fail if the resource already exists if no `log_config` block is present and `enable_logging` is not present or false.
The error is:
`
Error: Error updating Firewall "projects/project_name/global/firewalls/firewall_name": googleapi: Error 400: Invalid value for field 'resource.logConfig': '{  "enable": false}'. Logging for this firewall rule must be enabled to toggle logging options., invalid
`

### Steps to Reproduce

1. Create a `google_compute_firewall` with no `log_config` block and `enable_logging` is not present or false.
2. `terraform apply`
3. Update any property of the firewall that allows an update in place (except for `log_config` or `enable_logging`, I've used target our source tags/service accounts).
4. `terraform apply`

### Important Factoids

This is a recent issue and this behaviour was previously functional (suggesting Google API implementation has changed), and the logic [here](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_firewall.go#L1045-L1046) doesn't seem outrageous.

**Comment by edwardmedia** [comment]
@DeanBrunt can you share your config and the debug log so I can take a close look? Thanks

**Comment by DeanBrunt** [comment]
As quickly as that issue arrived it now seems to be gone.
When we were seeing the issue if you started from scratch and created this resource:
```tf
resource "google_compute_firewall" "bug_example" {
  name = "bug-example-firewall"
  network = "default"
  project = "project-name"

  source_tags = ["source-tag"]
  target_tags = ["target-tag"]

  allow {
    protocol = "all"
  }
}
```

Then modified it to this and reapplied:
```tf
resource "google_compute_firewall" "bug_example" {
  name = "bug-example-firewall"
  network = "default"
  project = "project-name"

  source_tags = ["source-tag", "source-tag-2"]
  target_tags = ["target-tag"]

  allow {
    protocol = "all"
  }
}
```

You would of observed the issue I described in my initial post.

**Comment by edwardmedia** [comment]
@DeanBrunt I tested using you suggested code, and seems to be fine. I guess the issues you experienced may be intermittent on API side. I am closing the issue now. Please feel free to reopen it if the issue comes bask. Thank you

```
  # google_compute_firewall.bug_example will be updated in-place
  ~ resource "google_compute_firewall" "bug_example" {
        creation_timestamp      = "2020-09-10T10:33:27.358-07:00"
        destination_ranges      = []
        direction               = "INGRESS"
        disabled                = false
        id                      = "projects/myproject/global/firewalls/issue7220-firewall"
        name                    = "issue7220-firewall"
        network                 = "https://www.googleapis.com/compute/v1/projects/myproject/global/networks/default"
        priority                = 1000
        project                 = "myproject"
        self_link               = "https://www.googleapis.com/compute/v1/projects/myproject/global/firewalls/issue7220-firewall"
        source_ranges           = []
        source_service_accounts = []
      ~ source_tags             = [
            "source-tag",
          + "source-tag-2",
        ]
        target_service_accounts = []
        target_tags             = [
            "target-tag",
        ]
        allow {
            ports    = []
            protocol = "all"
        }
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by mark-00** [comment]
We have the same problem with the following resource that has to be recreated after the source ranges change

```tf
resource "google_compute_firewall" "access" {
  name    = "access"
  project = var.fw_project_id
  network = var.network

  allow {
    protocol = "tcp"
    ports    = [443]
  }

  source_ranges = ["1.1.1.1","2.2.2.2"]
  target_tags   = ["vm"]
}
```

Terraform v0.12.17
+ provider.google v3.36.0

in  the trace during refresh of the state the api retruns
````
2020-09-21T17:56:17.688+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:   "logConfig": {
2020-09-21T17:56:17.688+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:     "enable": false,
2020-09-21T17:56:17.688+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:     "metadata": "INCLUDE_ALL_METADATA"
2020-09-21T17:56:17.688+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:   },

````

During apply the following is sent to the api 
````
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:  "logConfig": {
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:   "enable": false
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:  },
````

Although this works on the initial switch from enable:true to enable:false this fails on subsequent api calls with the same payload. To make it work the metadata element has to be pressent with value the empty string

````
  "logConfig": {
    "enable": false,
    "metadata": ""
  },
````

**Comment by mark-00** [comment]
can this ticket be reopend ?
