### ISSUE TITLE
Add support for GKE Ingress for Internal HTTP(s) load balancing

### ISSUE THREAD

**Issue by ppennanen** [hashicorp/terraform-provider-google#7221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Ingress for Internal HTTP(s) load balancing](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-ilb) is useful to run GKE services behind and internal load balancer. It would be very convenient to provision it with Terraform.

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "primary" {
    addons_config {
        internal_http_load_balancing {
            enabled = true
        }
    }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-ilb

**Comment by upodroid** [comment]
Hello

This is not done through terraform but through Kubernetes Service and Ingress resources.

Have a look at https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress for details.

If this resolves your question, please go ahead and close this issue.

Thank you
