### ISSUE TITLE
Add data source for google_compute_instance_group_manager

### ISSUE THREAD

**Issue by remm** [hashicorp/terraform-provider-google#7222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a resource for google_compute_instance_group_manager but the data source is absent

### New or Affected Resource(s)

* google_compute_instance_group_manager

### Potential Terraform Configuration

```tf
data "google_compute_instance_group_manager" "gke-m-usc1-envoy-dispatcher-589f9f73-grp" {
  name = "gke-m-usc1-envoy-dispatcher-589f9f73-grp"
  zone = "us-central1-a"
}
```

### References

* #0000

**Comment by AarshDhokai** [comment]
b/263546231

**Comment by AarshDhokai** [comment]
Seems like PR is merged for the requirements, Hence Closing this issue.
