### ISSUE TITLE
google_notebooks_instance documentation bug

### ISSUE THREAD

**Issue by cm-wayfair** [hashicorp/terraform-provider-google#7228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

https://github.com/hashicorp/terraform-provider-google-beta/blob/master/website/docs/r/notebooks_instance.html.markdown

### Terraform Configuration Files

N/A

### Debug Output

> install_gpu_driver - (Optional) Indicates that this is a boot disk. The virtual machine will use the first partition of the disk for its root filesystem.

`metadata = {
    terraform = "true"
  }`

### Expected Behavior

install_gpu_driver seems to have an incorrect description, possibly copy/paste error.

Also the example includes a reference to metadata.terraform = true without any explanation.

### References

[https://github.com/hashicorp/terraform-provider-google-beta/blob/master/website/docs/r/notebooks_instance.html.markdown](url)

**Comment by edwardmedia** [comment]
@cm-wayfair  You are correct. It should be something like below. Thank you
```
Whether the end user authorizes Google Cloud to install GPU driver on this instance. If this field is empty or set to false, the GPU driver won't be installed. Only applicable to instances with GPUs.
--
```

**Comment by cm-wayfair** [comment]
@edwardmedia thanks for the quick response.

For metadata I was more pointing out the examples. Was wondering if the terraform = "true" meant something specific. Seemed undocumented. If it was just an example that doesn't have any impact on the system then that is fine and you can probably close this. For example, if you set proxy-mode = "service_account" it definitely would have an impact.

`metadata = {
    proxy-mode = "service_account"
    terraform  = "true"
  }`
