### ISSUE TITLE
google_notebooks_instance should allow the 'tags' attribute

### ISSUE THREAD

**Issue by cm-wayfair** [hashicorp/terraform-provider-google#7233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Setting network tags is a common way of implementing firewall rules. However, google_notebooks_instance doesn't allow setting tags.

### New or Affected Resource(s)

* google_notebooks_instance

### Potential Terraform Configuration

```tf
tags = ["foo", "bar"]
```
Similar to compute_instance
[https://www.terraform.io/docs/providers/google/r/compute_instance.html#tags](https://www.terraform.io/docs/providers/google/r/compute_instance.html#tags)

```
Unsupported argument

  on resources.tf line 186, in resource "google_notebooks_instance" "notebook-api-instance-b":

 186:   tags = ["foo", "bar"]
```

### References

* #0000

**Comment by danawillow** [comment]
@cm-wayfair, the API in this case doesn't have an attribute for tags: https://cloud.google.com/ai-platform/notebooks/docs/reference/rest/v1beta1/projects.locations.instances. I'd recommend filing an issue against GCP itself for this API to get the field. Once it's there, we can add it to the provider.

**Comment by gogasca** [comment]
I added support to Notebooks API, this will be available in ~2 weeks in production

**Comment by melinath** [comment]
Looks like this should now be resolved: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#tags
