### ISSUE TITLE
Add SLO "availability" SLI metric support

### ISSUE THREAD

**Issue by Tailzip** [hashicorp/terraform-provider-google#7239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Through the [console](https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring/ui/create-slo#sli-metric) or [API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#basicsli), we can configure a SLO based on **availability** metric, but support is missing in `basic_sli` config block on the `google_monitoring_slo` resource.

### New or Affected Resource(s)

* google_monitoring_slo

### Potential Terraform Configuration

```tf
data "google_monitoring_app_engine_service" "default" {
  module_id = "default"
}

resource "google_monitoring_slo" "appeng_slo" {
  service = data.google_monitoring_app_engine_service.default.service_id

  slo_id = "ae-slo"
  display_name = "Terraform Test SLO for App Engine"

  goal = 0.9
  calendar_period = "DAY"

  basic_sli {
    availability {}
  }
}

```

### References

* https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring/ui/create-slo#sli-metric
* https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#basicsli
* https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#availabilitycriteria
* b/173480266

**Comment by venkykuberan** [comment]
@Tailzip per [API doc](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#AvailabilityCriteria), availability SLI isn't supported yet. Looks to me its just a place holder. I am not sure we can achieve any by passing empty `availability{}` to API. Can you please brief us what you are trying to achieve with the `availability` metric there ?

**Comment by rileykarson** [comment]
@venkykuberan: Is it possible that specifying `availability` in a request enables the feature and that placeholder is for more configuration options?

**Comment by rileykarson** [comment]
Also, note that the `BasicSli` object appears at multiple points during the request object. We'll want to support them all to close this issue. See the sample in https://github.com/hashicorp/terraform-provider-google/issues/7884, for example.

**Comment by Tailzip** [comment]
Agreed with @rileykarson, it looks like it's a _placeholder_ according to the API doc. It is indeed already possible to enable that feature directly in the Console, or via API as mentioned in the issue description.

**Comment by rileykarson** [comment]
Looks like we missed this in at least one place (per https://github.com/hashicorp/terraform-provider-google/issues/7884), we'll want to add it in all applicable locations. @venkykuberan are you able to pick this up this sprint?
