### ISSUE TITLE
Resource google_compute_network, delete_default_routes_on_create flag not working with recent change of ComputeDefaultBasePath

### ISSUE THREAD

**Issue by riteshnanda09** [hashicorp/terraform-provider-google#7243]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash tf --version
Terraform v0.12.26
+ provider.google v3.38.0
```

### Affected Resource(s)

* google_compute_network

### Expected Behavior

default routes (0.0.0.0/0) will be deleted immediately after network creation.

### Actual Behavior

default routes (0.0.0.0/0) was not deleted. looks like the url we build for the [network filter](https://github.com/hashicorp/terraform-provider-google/blob/0a5065f365e0ea3efdd87bde0b8d9daf0cc66b93/google/resource_compute_network.go#L148) uses [ComputeDefaultBasePath](https://github.com/hashicorp/terraform-provider-google/blob/cdced3dd3837268eadf440074002e1b9e77d0ce4/google/config.go#L247) which points to `https://compute.googleapis.com/compute/v1/` instead it should be using `https://www.googleapis.com/compute/v1/` specifically for route url.

I know we might want to use [actual service url in this commit](https://github.com/hashicorp/terraform-provider-google/commit/a82394b4403cfc1c6f7fefa83b83fdb483f31f57) , but it breaks routes deletion during network creation.

**Comment by McVillano** [comment]
Same problem here, default routes are not being deletd

**Comment by edwardmedia** [comment]
@riteshnanda09 @McVillano looks like this is a dup issue. https://github.com/hashicorp/terraform-provider-google/issues/7164.
Please follow it for the resolution. Thanks
