### ISSUE TITLE
Race condition when creating VPC before GKE

### ISSUE THREAD

**Issue by crockpotveggies** [hashicorp/terraform-provider-google#7244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
❯ terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.5.0
```

### Affected Resource(s)

* resource "google_compute_network" "vpc_network" 
* resource "google_container_cluster" "primary"

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

provider "google" {
  version = "3.5.0"

  credentials = file("PROJECTID.key.json")

  project = "PROJECTID"
  region  = "northamerica-northeast1"
  zone    = "northamerica-northeast1-a"
}

resource "google_compute_network" "vpc_network" {
  name = "terraform"
  project = "PROJECTID"
  auto_create_subnetworks = true
}

resource "google_container_cluster" "primary" {
  name               = "gke-primary"
  location           = "northamerica-northeast1-a"
  initial_node_count = 3
  network = "projects/PROJECTID/global/networks/terraform"

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  node_config {
    disk_size_gb = 500
    disk_type = "pd-ssd"
    machine_type = "e2-medium"

    oauth_scopes = [
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

    labels = {}

    tags = ["kubernetes", "backend"]
  }

  timeouts {
    create = "30m"
    update = "40m"
  }
}
```

### Debug Output

https://gist.github.com/crockpotveggies/424c9764200cfb27f4001cc840e75864
Note you can ignore the `Insufficient regional quota to satisfy request` because it indicates the VPC was finally found and is not related to the current problem.

### Panic Output

n/a

### Expected Behavior

Terraform creates a VPC, waits for the VPC to be created, then creates a GKE cluster once the VPC is valid and found.

### Actual Behavior

The VPC is 404 not found or 400 does not exist, and the command must be run twice in order to use the resource as part of a new GKE clsuter.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

No, brand new GCP account/project with GCE already enabled.

### References

n/a

**Comment by upodroid** [comment]
Hello

You should reference the name of the google_compute_network.vpc_network instead of writing the name of the vpc in the google_container_cluster resource. That creates the resource dependency and terraform will create it in the correct order.

`network = google_compute_network.vpc_network.name`

If this solves your issue, please go ahead and close this issue.

Thank you

**Comment by crockpotveggies** [comment]
Thanks that worked as expected. Is there a reason why I can't use the actual name of the VPC network, in case I have multiple? For example: 

```
network = google_compute_network.vpc_network.terraform1
...
network = google_compute_network.vpc_network.terraform2
```

When I try to do so:

```
❯ terraform apply

Error: Unsupported attribute

  on main.tf line 29, in resource "google_container_cluster" "primary":
  29:   network = google_compute_network.vpc_network.terraform

This object has no argument, nested block, or exported attribute named
"terraform".
```

**Comment by upodroid** [comment]
You can only use the values available in the schema which is found in the provider docs. You specify the name inside the resource so if you need to change it you only change it one place.

Have a look at the documentation and the learning guides at https://terraform.io. They have great guides on best practices tutorials.
