### ISSUE TITLE
provider-google for Cloud Composer uses v1beta1 API instead of v1 API

### ISSUE THREAD

**Issue by anitakar** [hashicorp/terraform-provider-google#7250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Does not apply. Google internal version.

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
resource "google_composer_environment" "composer_test_env" {
  name = "afronczak-terraform-env"
  region = "us-central1"
  project = "cloud-airflow-dev"
}
```

### Expected Behavior

Call https://composer.googleapis.com/v1/

### Actual Behavior

Called https://composer.googleapis.com/v1beta1/

### Steps to Reproduce

1. `terraform apply`

**Comment by anitakar** [comment]
I would like to work on it.

**Comment by edwardmedia** [comment]
Closed as this is fixed
