### ISSUE TITLE
Enhancement : google_compute_disk should not allow shrinking if already exists

### ISSUE THREAD

**Issue by lchastel** [hashicorp/terraform-provider-google#7260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Shrinking size of google_compute_disk, should not be allowed.
The disk is replaced, so its data are lost when terraform destroys it.

For me the best way to do it, is that the provider forbid to shrink existing disk (already deployed one)
It means that the developer will have to destroy manually the disk, but I find this better than current situation where it's destroyed automatically if the developer don't pay attention to plan.

terraform v0.12.29 
provider google v3.38.0

PS : I tried to do it directly with terraform :
* check the variable value is greater than actual disk size, but I received cycle error. 
* create a local variable with the greater size between variable and disk size, but I also received cycle error.
* create null resource with local-exec to get the greater size, or external data, ... but then the disk is always replaced.

I didn't test with variable validation in terraform v0.13, but I didn't see anything in the documentation that will allow the usage to resources in the validation process.

### New or Affected Resource(s)

* google_compute_disk

**Comment by danawillow** [comment]
Hey @lchastel, I think what you're looking for is https://www.terraform.io/docs/configuration/resources.html#prevent_destroy. I'd recommend putting that on any resource you want to make sure that Terraform doesn't destroy.

**Comment by lchastel** [comment]
Hello @danawillow 

Sorry about that, I missed this setting.
I tested it, and it's working like I want.

Best regards
Laurent
