### ISSUE TITLE
google_project_iam_policy - terraform plan showing what existing bindings are going to removed

### ISSUE THREAD

**Issue by gaspar-chilingarov** [hashicorp/terraform-provider-google#7262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.2
+ provider registry.terraform.io/-/google v3.38.0
+ provider registry.terraform.io/hashicorp/google v3.38.0

### Affected Resource(s)

google_project_iam_policy

### Terraform Configuration Files

```tf
locals {
        project = "XXXXXXXX"
}

provider "google" {
  project     = local.project
  region      = "us-central1"
}

resource "google_project_iam_policy" "group-reader" {
  project     = local.project
  policy_data = data.google_iam_policy.group-policy.policy_data
}

data "google_iam_policy" "group-policy" {
  binding {
    role = "roles/bigtable.viewer"

    members = [
        "group:service-users-admin@XXXXXXXX"
    ]
  }
}
```

There are more  IAM bindings created in the project throught the Console.

### Debug Output
.
### Panic Output
.

### Expected Behavior

Even on the first run, TF should hint, that will destroy some other bindings in the project

```
  # google_project_iam_policy.group-reader will be updated in-place
  ~ resource "google_project_iam_policy" "group-reader" {
        etag        = "XXXXX"
        id          = "XXXXXXXXX"
      ~ policy_data = jsonencode(
          ~ {
              ~ bindings = [
                    + {
                        + members = [
                            +"group:service-users-admin@XXXXXXXXX",
                       ]
                       + role    = "roles/bigtable.viewer"
                    },
                  - {
                      - members = [
                          - "user:service-user-1@XXXXXXXXX",
                        ]
                      - role    = "roles/cloudbuild.builds.viewer"
                    },
                ]
            }
        )
        project     = "XXXXXXXXX"
    }
```

### Actual Behavior

Suggested action by TF, it actually deleted all existing IAM bindings in the project

```
  # google_project_iam_policy.group-reader will be created
  + resource "google_project_iam_policy" "group-reader" {
      + etag        = (known after apply)
      + id          = (known after apply)
      + policy_data = jsonencode(
            {
              + bindings = [
                  + {
                      + members = [
                          + "group:service-users-admin@XXXXXXXX",
                        ]
                      + role    = "roles/bigtable.viewer"
                    },
                ]
            }
        )
      + project     = "XXXXXXXX"
    }
```

### Steps to Reproduce

1. Create manually any binding in Cloud Console 

2. run `terraform init` and `terraform apply`

### References

This documentation also needs warning, that creating policy can lock users out of the project. It is mentioned above ("replaces any existing policy already attached"), but the implications (TF will delete all existing bindings in the project) are not obvious. https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_policy-1

* #0000

**Comment by edwardmedia** [comment]
@gaspar-chilingarov below is what is says in the document. You might want to use google_project_iam_binding or google_project_iam_member instead
```
google_project_iam_policy: Authoritative. Sets the IAM policy for the project and **replaces** any existing
```

**Comment by gaspar-chilingarov** [comment]
Yes, about **replacing** part - it does not show up in TF plan/apply output, this decreasing trust in the tool, that it will tell you **exactly** what it plans to do. 

Adding second warning on the `google_project_iam_policy` section would be helpful too. We warn in case of the `destroy` scenario, but we don't warn user that it can be also dangerous during the `create`.

**Comment by edwardmedia** [comment]
@gaspar-chilingarov changed the label from `bug` to `enhancement`. Will be triaged

**Comment by edwardmedia** [comment]
@gaspar-chilingarov   We probably can't do that. That's just a consequence of Terraform itself. If a resource isn't in state, then the first plan for it will always show it being created, even if it's actually just overwriting something that already exists. If you want that sort of functionality, you can import it first like what is recommended at https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_policy-1
This behavior is built for all **iam** resources
