### ISSUE TITLE
Unable to manage old CLOUD_DATASTORE pre CLOUD_DATASTORE_COMPATIBILITY

### ISSUE THREAD

**Issue by ademariag** [hashicorp/terraform-provider-google#7263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform --version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.37.0
+ provider registry.terraform.io/hashicorp/google-beta v3.37.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```
### Affected Resource(s)

* google_app_engine_application

### Terraform Configuration Files

```json
{
  "resource": {
    "google_app_engine_application": {
      "datastore": {
        "database_type": "CLOUD_DATASTORE_COMPATIBILITY",
        "location_id": "europe-west",
        "project": "${google_project.project.project_id}"
      }
    }
  }
```

### Debug Output

```
  # google_app_engine_application.datastore will be updated in-place
  ~ resource "google_app_engine_application" "datastore" {
        app_id            = "anthaos-dev"
        auth_domain       = "gmail.com"
        code_bucket       = "staging.anthaos-dev.appspot.com"
      ~ database_type     = "CLOUD_DATASTORE" -> "CLOUD_DATASTORE_COMPATIBILITY"
        default_bucket    = "anthaos-dev.appspot.com"
        default_hostname  = "anthaos-dev.ew.r.appspot.com"
        gcr_domain        = "eu.gcr.io"
        id                = "anthaos-dev"
        location_id       = "europe-west"
        name              = "apps/anthaos-dev"
        project           = "anthaos-dev"
        serving_status    = "SERVING"
        url_dispatch_rule = []

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

Datastore updated

### Actual Behavior

```
Error: Error waiting for App Engine app to update: Error code 9, message: The "database_type" field cannot be modified for this application. Note: If data has already been written for this application, then the "database_type" may not be modified.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If I change the type to "CLOUD_DATASTORE" I get the following

```
Error: expected database_type to be one of [CLOUD_FIRESTORE CLOUD_DATASTORE_COMPATIBILITY], got CLOUD_DATASTORE                                        
```

**Comment by venkykuberan** [comment]
@ademariag first one seems legit error from the API and second error is from plan time validation. Currently provider supports only these 2 database_types {"CLOUD_FIRESTORE", "CLOUD_DATASTORE_COMPATIBILITY"}.  We will work on adding the rest as API now supports other database_types.
