### ISSUE TITLE
Credentials property ignored - No credentials loaded

### ISSUE THREAD

**Issue by rndlaine** [hashicorp/terraform-provider-google#7264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.2

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
variable "project_name" {
  type    = string
  default = "test"
}

variable "region" {
  type    = string
  default = "us-east1"
}

variable "billing_account" {
  type = string
}

variable "org_id" {
  type = string
}

provider "google" {
  region      = var.region
  credentials = file("tfadmin-service-key.json")
}

resource "random_id" "id" {
  byte_length = 2
  prefix      = var.project_name
}

resource "google_project" "project" {
  provider        = google-beta
  project_id      = random_id.id.hex
  name            = var.project_name
  billing_account = var.billing_account
  org_id          = var.org_id
}
```

### Debug Output

https://gist.github.com/rndlaine/d47e802b1e576afaf6ebe8dfcc01dc70

### Expected Behavior

Should have loaded the service account credentials provided in the `credentials` property.

### Actual Behavior

The provider's `credentials` property is ignored

### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

**Comment by edwardmedia** [comment]
@rndlaine looks like you defined `provider "google"` but used as `google-beta`. Can you see what happens?
```tf
resource "google_project" "project" {
  provider        = google             #<----- change this ?
  project_id      = random_id.id.hex
  name            = var.project_name
  billing_account = var.billing_account
  org_id          = var.org_id
}
```

**Comment by rndlaine** [comment]
Ok so this works 💯  on a new project, however it doesn't work on an existing project using a terraform backend.

```tf
terraform {
  backend "gcs" {
    bucket      = "terraform-admin"
    prefix      = "terraform/states"
    credentials = "tfadmin-service-key.json" # <--- can't use file() here, but passing the path seems to work
  }
}
```

I get the same "No credentials loaded" error.

**Comment by edwardmedia** [comment]
@rndlaine Your 2nd question is about the use of Terraform `backend` which is a Terraform feature.You may find the reference over https://www.terraform.io/docs/backends/config.html

**Comment by rndlaine** [comment]
The issue was caused by another resource that used the `google-beta` provider while only the `google` provider was declared.
