### ISSUE TITLE
google_cloud_identity_group fails to create

### ISSUE THREAD

**Issue by bwmaas** [hashicorp/terraform-provider-google#7285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/google-beta v3.39.0
```

### Affected Resource(s)

* google_cloud_identity_group

### Terraform Configuration Files

```tf
resource "google_cloud_identity_group" "some-group" {
    provider     = google-beta
    display_name = "some-group"
    parent       = "customers/${var.google_customer_id}"

    group_key {
        id = "some-group@somedomain.com"
    }

    labels = {
        "cloudidentity.googleapis.com/groups.discussion_forum" = ""
    }
}
```

### Debug Output

https://gist.github.com/bwmaas/a77304370726011248efe2b506c9450c

### Expected Behavior

Creation of Google Group

### Actual Behavior

```
Error: Error creating Group: googleapi: Error 400: Must specify initial_group_config when creating a Google Group.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Must specify initial_group_config when creating a Google Group.",
        "field": "initial_group_config"
      }
    ]
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This output was created using a service account

### References

* #0000

**Comment by venkykuberan** [comment]
Looks like its a breaking change, I don't see that param in the beta-provider. We will work on it, thanks for filing the issue.
