### ISSUE TITLE
Additional local SSD disks not supported (max 8)

### ISSUE THREAD

**Issue by joscabmar** [hashicorp/terraform-provider-google#7293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.23
+ provider.google v3.39.0
+ provider.google-beta v3.39.0
+ provider.null v2.1.2
+ provider.random v2.3.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
// Dynamic NVME scratch disk
  dynamic "scratch_disk" {
    for_each = range(var.local_disk_count)
    content {
      interface = "NVME"
    }
  }
```

### Debug Output

```
module.new_datanode.google_compute_instance.datanode[0]: Creating...

Error: Error creating instance: googleapi: Error 400: Number of local SSDs for an instance of type n2-highmem-64 should be one of [0, 8], while [16] is requested., badRequest

  on ../../modules/datanode/main.tf line 13, in resource "google_compute_instance" "datanode":
  13: resource "google_compute_instance" "datanode" {
```
https://gist.github.com/joscabmar/732ca482b2e5f80751fa0b081382bf5c

### Expected Behavior

I would expect to be able to create an instance with 16 local SSD

### Actual Behavior

Instead it says that the maximum is 8. But in the GCP docs it says that it is supported up to 24 disks

### Steps to Reproduce

1. `terraform apply`

### References

* https://cloud.google.com/compute/docs/disks/local-ssd

**Comment by edwardmedia** [comment]
@joscabmar this is googleapi error. Terraform has nothing to do with it. The document says a max of 24, and I think not all types support that count. Can you try using different instance type to see if that make sense?  

```
Number of local SSDs for an instance of type n2-highmem-64 should be one of [0, 8]
```

**Comment by joscabmar** [comment]
You are totally right @edwardmedia. It was my mistake. N2 machines are not yet compatible with  >8 local SSD: https://cloud.google.com/compute/docs/disks#local_ssd_limits
I will give it a try with a custom N1. Thanks for your response!

**Comment by joscabmar** [comment]
Using a custom N1 worked perfectly with the 16 local SSD. Thanks again. Closing the issue.
