### ISSUE TITLE
Unable to create secret version after creating a secret. 

### ISSUE THREAD

**Issue by Colum** [hashicorp/terraform-provider-google#7298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

+ provider registry.terraform.io/hashicorp/time v0.5.0

### Affected Resource(s)

* google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret" "app-postgres-password" {
  secret_id = var.app_postgres_password_secret_name

  replication {
    automatic = true
  }

  provisioner "local-exec" {
    command = "sleep 10"
  }
}

resource "google_secret_manager_secret_version" "app-postgres-password-version" {
  depends_on  = [google_secret_manager_secret.app-postgres-password]
  secret      = google_secret_manager_secret.app-postgres-password.id
  secret_data = random_password.password.result
}
```

### Expected Behavior

The secret is created, then the version is added to the secret.

### Actual Behavior

The secret is created in GCP Secret Manager without issue. Assigning a version to that secret allows a secret value to be set. This last step does not work. It fails with HTTP 403, but checking Secret Manager from the console shows the secret version is there. I've added a delay of 10s after the secret is created in case the secret needs time to be ready.

```
google_secret_manager_secret.app-postgres-password: Provisioning with 'local-exec'...
google_secret_manager_secret.app-postgres-password (local-exec): Executing: ["/bin/sh" "-c" "sleep 10"]
google_secret_manager_secret.app-postgres-password: Still creating... [10s elapsed]
google_secret_manager_secret.app-postgres-password: Creation complete after 11s [id=projects/migration-staging-288222/secrets/app-postgres-password]
google_secret_manager_secret_version.books-postgres-password-version: Creating...

Error: Error reading SecretVersion: googleapi: Error 403: Permission 'secretmanager.versions.access' denied for resource 'projects/713026546796/secrets/app-postgres-password
/versions/1' (or it may not exist).
```

**Comment by edwardmedia** [comment]
@Colum there is an example from below link. Does it works for you? In term of how to use `sleep`, I would suggest you can take a look at [this](https://github.com/hashicorp/terraform-provider-google/issues/6377#issuecomment-628978514)


https://www.terraform.io/docs/providers/google/r/secret_manager_secret_version.html

**Comment by Colum** [comment]
The example in there is what I based my code off of, unfortunately does not work. About the sleep, it was to rule out another possible reason why the code is failing, not for routine use.

**Comment by Colum** [comment]
Seems related this https://github.com/google/exposure-notifications-server/issues/214. I've tried using the service account's json file and `gcloud auth application-default login` to authenticate, unfortunately both produce the same result.

**Comment by crockpotveggies** [comment]
@edwardmedia I can confirm I am experiencing the same problem

**Comment by edwardmedia** [comment]
@Colum I can't repo it. The example works fine with me. Can you post the full debug log?

**Comment by Colum** [comment]
I've adjusted the service account to have role `Secret Manager Admin` and it works now. What threw me off was that previously when creating the secret version, I was getting a 403 but the secret version was being created - sounds like this is an issue with GCP.

Thanks for the help.
