### ISSUE TITLE
Incorrect `Provider Configuration Not Present` Removing google_compute_global_address

### ISSUE THREAD

**Issue by samhumphreys-2sixty** [hashicorp/terraform-provider-google#7303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/google-beta v3.39.0

### Affected Resource(s)

google_compute_global_address

### Terraform Configuration Files

```tf
# BEFORE CHANGE
terraform {
  required_providers {
      google-beta = {
        source  = "hashicorp/google-beta"
        version = "3.39.0"
      }

      google = {
        source  = "hashicorp/google"
        version = "3.39.0"
      }
  }
}

resource "google_project" "project" {
  name            = "Testing"
  project_id      = OMITTED
  folder_id       = OMITTED
  billing_account = OMITTED
}

resource "google_project_service" "cloudbilling-googleapis-com" {
  project             = google_project.project.project_id
  service             = "cloudbilling.googleapis.com"
  disable_on_destroy  = false
}

resource "google_project_service" "compute-googleapis-com" {
  project             = google_project.project.project_id
  service             = "compute.googleapis.com"
  disable_on_destroy  = false
}

resource "google_compute_global_address" "testing-ip" {
  depends_on  = [
    google_project_service.cloudbilling-googleapis-com,
    google_project_service.compute-googleapis-com
  ]
  provider    = google-beta
  project     = google_project.project.project_id
  name        = "testing-ip"
  description = ""
  ip_version  = "IPV4"

  labels = {
    "foo" = "bar"
  }
}

# AFTER CHANGE
terraform {
  required_providers {
      google-beta = {
        source  = "hashicorp/google-beta"
        version = "3.39.0"
      }

      google = {
        source  = "hashicorp/google"
        version = "3.39.0"
      }
  }
}

resource "google_project" "project" {
  name            = "Testing"
  project_id      = OMITTED
  folder_id       = OMITTED
  billing_account = OMITTED
}

resource "google_project_service" "cloudbilling-googleapis-com" {
  project             = google_project.project.project_id
  service             = "cloudbilling.googleapis.com"
  disable_on_destroy  = false
}

resource "google_project_service" "compute-googleapis-com" {
  project             = google_project.project.project_id
  service             = "compute.googleapis.com"
  disable_on_destroy  = false
}
```

### Debug Output

https://gist.github.com/samhumphreys-2sixty/9ebe6895172bc72b740f7a052d8e4e92

### Expected Behavior

google_compute_global_address should have been destroyed.

### Actual Behavior

Error raised that provider configuration not present, despite still being in the Terraform file. Also this wasn't an upgrade to Terraform 13, which is where this issue usually arises (mapping legacy providers).

Error - `Error: Provider configuration not present`

### Steps to Reproduce

1. `terraform apply` - using the full initial config
2. Remove the google_compute_global_address resource
3. `terraform apply`

### Important Factoids

- Authenticating as a user.
- Seems to be limited to google-beta provider only for resource google_compute_global_address.
- Unable to replicate this for a resource google_compute_address using the google-beta provider

* #0000

**Comment by edwardmedia** [comment]
I can repro this issue. It appears me an Terraform issue. What do you think @c2thorn?

**Comment by c2thorn** [comment]
Hi @samhumphreys-2sixty, you are experiencing behavior specific to Terraform in general, and not the Google provider. Terraform notices a reference to the `google-beta` provider in state, but your configuration doesn't have a reference to it (It would be nice if the required_providers block was enough).

I believe you are seeing inconsistent behavior for removing resources based on whether or not it was the last reference to `google-beta` in your config. If you add a provider block to your config like:
```
provider "google-beta" {
}
```
and try removing any `google-beta` resources, you should not see this error any more. I will close this for now, but please try this out and let us know.

**Comment by samhumphreys-2sixty** [comment]
@c2thorn thanks, you're right. The provider configuration is still necessary to destroy the resources, though as you say it would be nice if the required_providers block was authoritative. Not an issue though, thanks!
