### ISSUE TITLE
CloudSQL - need REVOKE ALL FROM user for destroy

### ISSUE THREAD

**Issue by tobias-farrenkopf** [hashicorp/terraform-provider-google#7304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
provider "google" {
  credentials = var.gcp_credentials
  project = var.gcp_project
  region  = var.gcp_region
}

data "google_compute_network" "private_network" {
  provider = google
  name     = var.network
}

### Database ###

resource "google_sql_database_instance" "master" {
  name             = var.db_name
  project          = var.gcp_project
  region           = var.gcp_region
  database_version = var.postgres_version

  settings {
    availability_type = "REGIONAL"
    tier              = var.tier
    backup_configuration {
      enabled = var.backup_enabled
    }
    disk_size = var.disk_size
    ip_configuration {
      ipv4_enabled    = "false"
      private_network = data.google_compute_network.private_network.self_link
    }
    maintenance_window {
      day          = 6
      hour         = 2
      update_track = "stable"
    }
    user_labels = {
      name          = var.db_name
      landscapename = var.landscape_name
      serviceid     = "xyz"
    }
  }
}

resource "google_sql_user" "users" {
  name     = "vcap"
  instance = google_sql_database_instance.master.name
  password = var.admin_password
}

### Outputs ###

output "postgres-name" {
  value = google_sql_database_instance.master.name
}

output "postgres-address" {
  value = google_sql_database_instance.master.first_ip_address
}

output "postgres-admin-user" {
  value = google_sql_user.users.name
}

output "postgres-version" {
  value = google_sql_database_instance.master.database_version
}
```

### Debug Output

See https://github.com/hashicorp/terraform-provider-google/issues/7209

### Expected Behavior

Destroying of the selected cloudsql postgres databases.
### Actual Behavior

Unfortunately the following error occurs when destroying the databases.

Error: Error, failure waiting for deletion of vcap in abcd-luke-dev03-1597333529-11
### Steps to Reproduce

1. `terraform init -plugin-dir <plugin_dir> <tf_dir>`
2. set env variables
3. `terraform destroy -force -plugin-dir -var-file=<path>/terraform.tfvars.json -state=<state_file>`

### Important Factoids

This is a clone of https://github.com/hashicorp/terraform-provider-google/issues/7209

GCP support case indicated that the `REVOKE ALL FROM user` call was not issued before deletion

Therefore we think it is indeed a terraform issue.
See also: https://github.com/hashicorp/terraform-provider-google/issues/7209#issuecomment-691051038

### References
* https://github.com/hashicorp/terraform-provider-google/issues/7209

**Comment by edwardmedia** [comment]
@tobias-farrenkopf have you tried to run 'REVOKE ALL FROM user' as[ #7209](https://github.com/hashicorp/terraform-provider-google/issues/7209) suggested? 
I think users should do that before run Terraform destroy. 
I don't think the provider is a right place where this step should be implemented to handle this situation.  But Let me update the issue label to `enhancement` so it can be triaged.

**Comment by c2thorn** [comment]
@tobias-farrenkopf From what I can tell, neither the [user API](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users) nor [DB instance API](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances) expose a way to issue the revoke command to the database. Looking at the [documentation for deleting users](https://cloud.google.com/sql/docs/postgres/create-manage-users#rest_4), it mentions revoking before attempting to delete. This doesn't seem possible for the provider to do at the moment. I'll close this, but I suggest filing a feature request explaining your use case with the Cloud SQL team ([public tracker here](https://issuetracker.google.com/issues?q=componentid:%20187202%20status:open)).

**Comment by tobias-farrenkopf** [comment]
@c2thorn I cannot understand your reasoning. Terraform destroy is removing the database on all major cloud provider (AWS, Azure, Alicloud) but not on GCP. Now from a user perspective this is a shortcoming of terraform. No we can play ping-pong who's
fault that is (GCP or Terraform) but an issue is still an issue. Right?   Our workaround is to use the gcloud cli `gcloud  sql instances delete`.

**Comment by ZPascal** [comment]
@c2thorn @tobias-farrenkopf I create a GCP [feature request](https://issuetracker.google.com/issues/171235562). I ask everyone who has the same problem to vote up the feature request.
