### ISSUE TITLE
Launch VM from a GCP Marketplace Image

### ISSUE THREAD

**Issue by avarmaavarma** [hashicorp/terraform-provider-google#7319]
Is there  a way to create a compute engine resource where the image is pulled off the public marketplace? I've tried this to no avail...

**example marketplace image**  
https://console.cloud.google.com/marketplace/details/f5-7626-networks-public/f5-big-ip-adc-hourly-good-200mbps

**Example Compute Instance Spin up TF**

```
variable image_name  { default = "f5-7626-networks-public/f5-big-ip-adc-best-byol" }
resource "google_compute_instance" "bigip" {
    name = "${var.environment}-${var.instance_name}"
    machine_type = "${var.instance_type}"
    zone = "${var.zone}"

  boot_disk {
    initialize_params {
        image = "${var.image_name}" 
    }
  }
}
```

Basically, regardless of how I try it, TF is UNABLE To find the image. Note that there isn't an issue launching a VM off this image using the console.  Just via terraform. Using the latest google provider version = "~> 3.0.0 and the latest TF version. 

Thanks

**Comment by edwardmedia** [comment]
@avarmaavarma  Can you see if you can [create an image](https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images) first, and then use the **data source** like below code?

```tf
data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_instance" "default" {
  # ...

  boot_disk {
    initialize_params {
      image = data.google_compute_image.my_image.self_link
    }
  }
}

```

**Comment by avarmaavarma** [comment]
Thanks - yes - able to do the above (with debian), but not with the marketplace image. However, I believe there is a way to use the marketplace images using a public URI to access them. It's not ideal, but it avoids the issue of the image not being correctly found using the data source technique above.

**Comment by edwardmedia** [comment]
@avarmaavarma you may also want to review [images](https://cloud.google.com/compute/docs/images#os-compute-support). Once you can see it using below command, you can reference it in Terraform code. As how to create an image is beyond the provider area, I am closing this question. Feel free to reopen if you see a need to continue the conversation. Thanks
```
gcloud compute images list
```
