### ISSUE TITLE
modify firewall rule error Invalid value for field 'resource.logConfig'

### ISSUE THREAD

**Issue by mark-00** [hashicorp/terraform-provider-google#7322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.17
+ provider.google v3.36.0

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_firewall" "access" {
  name    = "access"
  project = var.fw_project_id
  network = var.network

  allow {
    protocol = "tcp"
    ports    = [443]
  }

  source_ranges = ["1.1.1.1","2.2.2.2"]
  target_tags   = ["vm"]
}
```

### Expected Behavior

Updating properties of a Google Compute Firewall (when no log_config block is present and enable_logging is not present or false) should work assuming no properties are invalid.

### Actual Behavior

Updating any property of an existing Google Compute Firewall (except for log_config or enable_logging) will fail if the resource already exists if no log_config block is present and enable_logging is not present or false.
The error is:
Error: Error updating Firewall "projects/project_name/global/firewalls/firewall_name": googleapi: Error 400: Invalid value for field 'resource.logConfig': '{ "enable": false}'. Logging for this firewall rule must be enabled to toggle logging options., invalid

### Steps to Reproduce

Create a google_compute_firewall with no log_config block and enable_logging is not present or false.
terraform apply
Update any property of the firewall that allows an update in place (except for log_config or enable_logging, I've used target our source tags/service accounts).
terraform apply

### Important Factoids

During apply the following is sent to the api 
````
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:  "logConfig": {
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:   "enable": false
2020-09-21T17:56:57.266+0200 [DEBUG] plugin.terraform-provider-google_v3.36.0_x5:  },
````

Although this works on the initial switch from enable:true to enable:false, this fails on subsequent api calls with the same payload. To make it work the metadata element has to be pressent with value the empty string when enabled is false

````
  "logConfig": {
    "enable": false,
    "metadata": ""
  },
````

* #0000

**Comment by edwardmedia** [comment]
dup https://github.com/hashicorp/terraform-provider-google/issues/7309. closing

**Comment by mark-00** [comment]
I don think this is a dup if #7309 

I have an other error message and I specify neither log_config or enable_logging

**Comment by Sinble** [comment]
We have found that if a firewall rule had logging enabled then disabled. You will run into this error. It's coming back from the google API. You can recreate the error by going to https://cloud.google.com/compute/docs/reference/rest/v1/firewalls/patch and select "try it". try changing your firewall through there and you should get the same error. 

To fix we had to recreate the firewall rule from scratch
