### ISSUE TITLE
Stateful MIG beta timeline

### ISSUE THREAD

**Issue by przsab** [hashicorp/terraform-provider-google#7323]
With Stateful MIG in GA, can we expect this will get out of google-beta provider anytime soon?

**Comment by danawillow** [comment]
Hi @przsab, we're tracking this question as a feature request now, so you'll be able to follow along as the work gets assigned into a sprint.

**Comment by melinath** [comment]
Re-opening; I'd missed some references in hand-written files.

**Comment by melinath** [comment]
After discussion - leaving beta API usage in the hand-written files is our best practice, since otherwise we would need to switch back to the beta API in the future if new beta features are added.
