### ISSUE TITLE
google_access_context_manager_service_perimeter_resource failed to remove projects from perimeter

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#7327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_access_context_manager_service_perimeter_resource
* google_access_context_manager_service_perimeter

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 3.38"
}

variable "policy" {
  description = "Name of the parent policy"
  type        = string
  default     = "123456789"
}


variable "perimeter_name" {
  description = "Name of the perimeter. Should be one unified string. Must only be letters, numbers and underscores"
  type        = string
  default     = "my_debug_perimeter"
}

variable "project_number" {
  description = "Project number"
  type        = string
  default     = <PROJECT_NUMBER>
}

resource "google_access_context_manager_service_perimeter" "service_perimeter" {
  parent = "accessPolicies/${var.policy}"
  name   = "accessPolicies/${var.policy}/servicePerimeters/${var.perimeter_name}"
  title  = var.perimeter_name

  status {
    restricted_services = [
      "storage.googleapis.com",
      "bigtable.googleapis.com",
      "bigquery.googleapis.com",
    ]
    resources           = []
    access_levels       = []
  }


  spec {
    restricted_services = [
      "storage.googleapis.com",
      "bigtable.googleapis.com",
      "bigquery.googleapis.com",
      "dataflow.googleapis.com",
    ]
    resources     = formatlist("projects/%s", var.project_number)
    access_levels = []
  }
  use_explicit_dry_run_spec = true

  lifecycle {
    ignore_changes = [status[0].resources]
  }
}



resource "google_access_context_manager_service_perimeter_resource" "service_perimeter_resource" {
  perimeter_name = google_access_context_manager_service_perimeter.service_perimeter.name
  resource       = format("projects/%s", var.project_number)
}
```

```tf
provider "google" {
  version = "~> 3.38"
}

variable "policy" {
  description = "Name of the parent policy"
  type        = string
  default     = "123456789"
}


variable "perimeter_name" {
  description = "Name of the perimeter. Should be one unified string. Must only be letters, numbers and underscores"
  type        = string
  default     = "my_debug_perimeter"
}

variable "project_number" {
  description = "Project number"
  type        = string
  default     = <PROJECT_NUMBER>
}

resource "google_access_context_manager_service_perimeter" "service_perimeter" {
  parent = "accessPolicies/${var.policy}"
  name   = "accessPolicies/${var.policy}/servicePerimeters/${var.perimeter_name}"
  title  = var.perimeter_name

  status {
    restricted_services = []
    resources           = []
    access_levels       = []
  }


  spec {
    restricted_services = [
      "storage.googleapis.com",
      "bigtable.googleapis.com",
      "bigquery.googleapis.com",
      "dataflow.googleapis.com",
    ]
    resources     = formatlist("projects/%s", var.project_number)
    access_levels = []
  }
  use_explicit_dry_run_spec = true

  lifecycle {
    ignore_changes = [status[0].resources]
  }
}

```

### Expected Behavior

I created perimeter using `google_access_context_manager_service_perimeter` & added resources to the perimeter using `google_access_context_manager_service_perimeter_resource` in first code. In second code i removed all resources by removing resource `google_access_context_manager_service_perimeter_resource` & at the same time I set `restricted_services` to null in status block. It should set all these values in status block to null.

### Actual Behavior

When I execute second code it does not remove projects from perimeter. But if I set `restricted_services` to null in status block and execute the code and then remove `google_access_context_manager_service_perimeter_resource` and execute the code it works as expected and set everything in status block to null. 

### Steps to Reproduce

1. Execute the first code to create perimeter `terraform apply`
2. Execute the second code you will see projects are still assigned to perimeter.

**Comment by imrannayer** [comment]
https://gist.github.com/imrannayer/2b980fd6d0198c60bebcab7672291b1c

**Comment by edwardmedia** [comment]
@imrannayer I can't repro the issue with the [example](https://www.terraform.io/docs/providers/google/r/access_context_manager_service_perimeter_resource.html). 

I noticed that you have below line in `google_access_context_manager_service_perimeter`. Is it *projects/31629304376*? What do you try to do here when you try to remove it from the *perimeter"*?
```
 resources     = formatlist("projects/%s", var.project_number)
```

**Comment by imrannayer** [comment]
@edwardmedia I posted the code above to reproduce the issue. Example is very simple scanrio and it works fine. Spec section has nothing to do with this issue. It is status section which is facing issue. 
First code to create perimeter and second code is how I am removing the projects from perimeter. Just provide policy and project value in variables. Execute two codes an you will see resources stay attached in status section (enforced mode) after removing google_access_context_manager_service_perimeter_resource from code.

**Comment by edwardmedia** [comment]
@imrannayer after removing the `google_access_context_manager_service_perimeter_resource` and setting the `status.restricted_services = []`, I see the changes happen that match the new config. Can you post the debug log for the 2nd run (the one you posted appears doing different things)?

**Comment by imrannayer** [comment]
Gist already have debug logs for both codes. Here is direct link to those debug logs. Code 2 is where I set `status.restricted_services = []` and removed `google_access_context_manager_service_perimeter_resource`

Code1: https://gist.github.com/imrannayer/2b980fd6d0198c60bebcab7672291b1c#file-tf_create_resource-log
Code2: https://gist.github.com/imrannayer/2b980fd6d0198c60bebcab7672291b1c#file-tf_delete_resource-log

Thanks

**Comment by edwardmedia** [comment]
@imrannayer Sorry I have missed the `delete` one. From that log, I see two calls that seem correct

```
 ---[ REQUEST ]---------------------------------------
 PATCH /v1/accessPolicies/110729902727/servicePerimeters/sin_debug_perimeter?alt=json&updateMask=status.resources HTTP/1.1
  {
  "status": {
   "resources": []
  }
 }
```

```
 PATCH /v1/accessPolicies/110729902727/servicePerimeters/sin_debug_perimeter?alt=json&updateMask=status HTTP/1.1
 
 {
  "spec": {
   "resources": [
    "projects/31629304376"
   ],
   "restrictedServices": [
    "storage.googleapis.com",
    "bigtable.googleapis.com",
    "bigquery.googleapis.com",
    "dataflow.googleapis.com"
   ]
  },
  "status": {
   "resources": [
    "projects/31629304376"
   ]
  },
  "title": "sin_debug_perimeter",
  "useExplicitDryRunSpec": true
 }
```
```

**Comment by edwardmedia** [comment]
@imrannayer sorry I have missed the `delete` log. But from it, I see both requests which seem correct. They are almost identical as mine. How do you check the resources are failed to remove? From TF state or/and GCP console?

```
 ---[ REQUEST ]---------------------------------------
 PATCH /v1/accessPolicies/110729902727/servicePerimeters/sin_debug_perimeter?alt=json&updateMask=status.resources HTTP/1.1
  {
  "status": {
   "resources": []
  }
 }
```
```
 PATCH /v1/accessPolicies/110729902727/servicePerimeters/sin_debug_perimeter?alt=json&updateMask=status HTTP/1.1
 {
  "spec": {
   "resources": [
    "projects/31629304376"
   ],
   "restrictedServices": [
    "storage.googleapis.com",
    "bigtable.googleapis.com",
    "bigquery.googleapis.com",
    "dataflow.googleapis.com"
   ]
  },
  "status": {
   "resources": [
    "projects/31629304376"
   ]
  },
  "title": "sin_debug_perimeter",
  "useExplicitDryRunSpec": true
 }
```

**Comment by imrannayer** [comment]
Both gcp console and and tfstate are showing that resource(projects) are still in perimeter in enforced mode.

**Comment by edwardmedia** [comment]
@imrannayer I am wondering if we may see different places. Can you post the gcp console screenshot and the tfstate before and after the run?

**Comment by imrannayer** [comment]
It is right there in debug logs. `status.resource` is still showing project number even after dropping the resource `google_access_context_manager_service_perimeter_resource`.
You can use the code I provided to reproduce it in any org. It is the code I created explicitly for reproducing this bug.

**Comment by edwardmedia** [comment]
Now I see what you meant. I guess this is what you referred to. 
```
  "status": {
   "resources": [
    "projects/31629304376"   <---- should be deleted
   ]
  },
```

**Comment by imrannayer** [comment]
yes it is showing in TF state.
I can see it in GUI console and through CLI using  `gcloud access-context-manager perimeters describe <perimeter_name> --policy policy_id`

**Comment by edwardmedia** [comment]
I guess this is what you referred to. Agreed I think we should send the update payload without this line
```
  "status": {
   "resources": [
    "projects/31629304376" <---- this is what you referred to
   ]
  },
```

**Comment by danawillow** [comment]
This is a really interesting bug! Here's what's happening:

Terraform only refreshes its state when it's computing the original diff. At that time, there's a project in the status.resources list and the field is marked with ignore_changes, so when the provider receives the diff, it'll see that the intended outcome is to keep the status.resources list the same as it was. This is what the plan output looks like in my repro:
```
      ~ status {
            access_levels       = []
            resources           = [
                "projects/<project-id>",
            ]
          ~ restricted_services = [
              - "bigquery.googleapis.com",
              - "bigtable.googleapis.com",
              - "storage.googleapis.com",
            ]
        }
```

If I remove the `ignore_changes` line, then I get a diff that looks more like what we're hoping for:
```
      ~ status {
            access_levels       = []
          ~ resources           = [
              - "projects/<project-id>",
            ]
          ~ restricted_services = [
              - "bigquery.googleapis.com",
              - "bigtable.googleapis.com",
              - "storage.googleapis.com",
            ]
        }
```

However, that still shows as a non-empty plan when I run plan after the apply:
```
      + status {
          + access_levels = []
          + resources     = []
        }
```

Terraform doesn't always understand that unset and set to empty mean the same thing- we have to tell it explicitly. However, there's a very easy workaround on your end- just omit the status block entirely. I can also make a quick PR to treat them both the same- it'll just take some time to get reviewed, merged, and released.

Just to recap- here's what I recommend you set your second config to today- this should fix the issue you're seeing.
```
provider "google" {
  version = "~> 3.38"
}

variable "policy" {
  description = "Name of the parent policy"
  type        = string
  default     = "123456789"
}


variable "perimeter_name" {
  description = "Name of the perimeter. Should be one unified string. Must only be letters, numbers and underscores"
  type        = string
  default     = "my_debug_perimeter"
}

variable "project_number" {
  description = "Project number"
  type        = string
  default     = <PROJECT_NUMBER>
}

resource "google_access_context_manager_service_perimeter" "service_perimeter" {
  parent = "accessPolicies/${var.policy}"
  name   = "accessPolicies/${var.policy}/servicePerimeters/${var.perimeter_name}"
  title  = var.perimeter_name

  spec {
    restricted_services = [
      "storage.googleapis.com",
      "bigtable.googleapis.com",
      "bigquery.googleapis.com",
      "dataflow.googleapis.com",
    ]
    resources     = formatlist("projects/%s", var.project_number)
    access_levels = []
  }
  use_explicit_dry_run_spec = true
}
```

**Comment by danawillow** [comment]
Actually, I'm not going to make the empty vs unset fix- it's a bit more complex than I originally thought because of the way sets work in Terraform, and since the above config should work, I'm not convinced it's something that urgently needs to be fixed. Closing this bug for now, but please feel free to reopen or comment if you have further questions or issues.

**Comment by imrannayer** [comment]
Thanks @danawillow . I will use TF dynamic block for status. This will solve the issue for my use case but it will still be a problem in the following case:
Suppose  `access_levels` and `restricted_services` both are populated in status block of `google_access_context_manager_service_perimeter` and we call `google_access_context_manager_service_perimeter_resource` to add resources in same code.
Now If I set `access_levels` to an empty list, keep `restricted_services` as populated list and remove `google_access_context_manager_service_perimeter_resource` at the same time. The resource will not be removed from status block as expected. I tested and reproduce the issue.

**Comment by danawillow** [comment]
Hi @imrannayer, the solution of removing the `ignore_changes` line works here too. I created a sample config based on your last comment, and was able to use that to have it make the correct changes. Here's a gist that shows the changes: https://gist.github.com/danawillow/fb14a810e2efce6c131a4e9c4bda4b52. In the second I just commented out the lines that I wanted to remove so that you can see where the changes are. Hope that helps!
