### ISSUE TITLE
gce_persistent_disk_csi_driver_config not recognised as a valid key

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [hashicorp/terraform-provider-google#7329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v0.11.14
```

Providers used
```
provider "google-beta" {
  #version = "~> 2.1.0"
  version = "2.20.2"
}

provider "google" {
  #version = "~> 2.1.0"
  version = "2.20.3"
}
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
  gce_persistent_disk_csi_driver_config  {
    enabled = "${var.enable_csi_driver}" 
  }

```

### Expected Behavior

Create gke cluster with CSI enabled

### Actual Behavior

```
Error: module.kube.google_container_cluster.k8s: : invalid or unknown key: gce_persistent_disk_csi_driver_config
```

**Comment by edwardmedia** [comment]
@pantelis-karamolegkos **gce_persistent_disk_csi_driver_config** is beta. Did you add `provider = google-beta` inside the resource?

**Comment by pantelis-karamolegkos** [comment]
So I should format it as in:

```
  gce_persistent_disk_csi_driver_config  {
    enabled = "${var.enable_csi_driver}" 
    provider = google-beta
  }
```

?

**Comment by edwardmedia** [comment]
@pantelis-karamolegkos add it at the root like below. [Here](https://www.terraform.io/docs/providers/google/guides/provider_reference.html) is the official document you may want to review

```tf
resource "google_container_cluster" "primary" {
  provider = google-beta
...
}
```

**Comment by pantelis-karamolegkos** [comment]
First of all I noticed I was using the wrong way the add on enablement. So now my code is:

```
  addons_config {
    http_load_balancing {
      disabled = false
    }

    gce_persistent_disk_csi_driver_config {
      enabled = "${var.enable_csi_driver}" 
    }

    horizontal_pod_autoscaling {
      disabled = false
    }

    kubernetes_dashboard {
      disabled = true
    }
  }
```

Yes, my provider is `beta`

```
resource "google_container_cluster" "k8s" {
  provider = "google-beta"
  count = "${var.cluster_count}"
.
.
.
```

Now I get:

```
Error: module.kube.google_container_cluster.k8s: addons_config.0: invalid or unknown key: gce_persistent_disk_csi_driver_config
```

**Comment by edwardmedia** [comment]
@pantelis-karamolegkos can you share the debug log?

**Comment by edwardmedia** [comment]
@pantelis-karamolegkos I noticed the version of your plugin is pretty old. This feature was release [v3.19.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.19.0). Can you try with the latest version?

**Comment by pantelis-karamolegkos** [comment]
Yes turns out its a matter of outdated plugin.
Thanks anyway for your time spent on this :+1
