### ISSUE TITLE
google_sql_source_representation_instance is missing quite a few fields

### ISSUE THREAD

**Issue by mcfedr** [hashicorp/terraform-provider-google#7330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Basically a number of fields are missing from the terraform resource that mean you cannot really create an external source using this resource.

### New or Affected Resource(s)

* google_sql_source_representation_instance

missing fields from the google api
- username
- password
- dumpFilePath
- caCertificate
- clientCertificate
- clientKey

Changed
- host  - terraform validates this as an IP address, but the api also allows a dns host name - it does note that the hostname should be up to 60 chars long - and I've noticed in my use of it, that replication breaks if its longer than 60 - although the [api](https://www.googleapis.com/sql/v1beta4/projects/[PROJECT-ID]/instances) doesn't actually validate this.

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_sql_source_representation_instance" "instance" {
  name             = "my-instance"
  region           = "us-central1"
  database_version = "MYSQL_5_7"
  host             = "some.host.example.com"
  port             = 3306
  username = "some-user"
  password = "password-for-the-user"
  dumpFilePath = "gs://replica-bucket/source-database.sql.gz"
}
```

### References

* https://cloud.google.com/sql/docs/mysql/replication/replication-from-external#dump-file-example

**Comment by seuf** [comment]
Is it possible to also add the possibility to create representation instance of postgresql database to facilitate the migration from on premise pg instance to google cloud sql ?

**Comment by hao-nan-li** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/7143
