### ISSUE TITLE
Support new Cloud Logging API v2 features

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Cloud Logging API v2](https://cloud.google.com/logging/docs/reference/v2/rest) has released to GA and offers more features for `google_logging_*_bucket_config` and `google_logging_*_sink` resources. 

### New or Affected Resource(s)

`google_logging_*_bucket_config`:
Users can actually [create logs buckets](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets/create) and specify custom bucket ID's. Currently the Terraform resource only acquires existing buckets.

`google_logging_*_sink`
Users can specify a [custom bucket as the sink destination](https://cloud.google.com/logging/docs/api/tasks/exporting-logs). I believe this should already be possible in the provider now, but we should verify and update the documentation at least.

### References

* b/168297756

**Comment by upodroid** [comment]
FYI, saw this PR that implements exclusions. 

https://github.com/hashicorp/terraform-provider-google/pull/7335

**Comment by c2thorn** [comment]
Hi folks,

I named this issue pretty ambiguously, so we wanted to clarify what we are committing to so far. We  split this up by specific feature request and created https://github.com/hashicorp/terraform-provider-google/issues/7371 and https://github.com/hashicorp/terraform-provider-google/issues/7372 .

I am closing this, but if you have a separate feature that is a part of Cloud Logging API v2 please create a new feature request issue.
