### ISSUE TITLE
Data sources with non-deterministic IDs show perpetual diff with Terraform 0.13

### ISSUE THREAD

**Issue by Justin-W** [hashicorp/terraform-provider-google#7348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Summary

Data sources whose ID is set to a non-deterministic value (e.g. the current timestamp or a unique ID) that changes every time a refresh (the data source's Read method) runs show a perpetual diff starting with Terraform 0.13.0.

Issue hashicorp/terraform-provider-google#7092, and [the related fix PR](https://github.com/hashicorp/terraform-provider-google/pull/7098), show one possible way to fix data sources affected by this bug.

This has also been reported for the aws provider (terraform-providers/terraform-provider-aws#14579) and other providers (see references below).

_Comment posted by @jbardin in https://github.com/hashicorp/terraform/issues/25805#issuecomment-672071546_

> In general, correctly working data sources should not show up in the plan when there are no changes to the data source configuration or `depends_on` references. These particular data sources should be reported to the associated provider so they can be fixed.

_Comment posted by @bflad in https://github.com/terraform-providers/terraform-provider-aws/issues/14579#issuecomment-672864788_
> ...
> New `tfproviderlint`/`awsproviderlint` checks are now available for this specific issue (not enabled in our CI yet, fresh off the press):
> 
> * [R015](https://github.com/bflad/tfproviderlint/tree/master/passes/R015)
> * [R016](https://github.com/bflad/tfproviderlint/tree/master/passes/R016)
> * [R017](https://github.com/bflad/tfproviderlint/tree/master/passes/R017)
> 
> ...

### Terraform Version

Terraform v0.13.3
Google Provider v2.20.3, and v3.39.0 

### Affected Resource(s)

* data google_compute_zones: [this line](https://github.com/hashicorp/terraform-provider-google/blob/27ed50511049d72ce26fc2b2f1c1ecb15046528a/google/data_source_google_compute_zones.go#L95) appears to be the root cause of the problem (for this data source)
* plus many other data sources

To find the data sources affected, see [this github repo search](https://github.com/hashicorp/terraform-provider-google/search?q=%22time.Now%22),
or run:

`$ grep 'd.SetId' google/data_source*.go | grep Now`

### Terraform Configuration Files

```tf
data "google_compute_zones" "acme-web-services-guide-rails-customer-vpc-sn-0-available" {
  provider = google
  status = "UP"
}

```

### Expected Behavior

TF v0.12 output from `terraform plan` (immediately after a `terraform apply`):

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior

TF v0.13.3 output excerpt from `terraform plan` (immediately after a `terraform apply`):

```
...

  # data.google_compute_zones.zones-up will be read during apply
  # (config refers to values not yet known)
 <= data "google_compute_zones" "zones-up"  {
      + id      = "2020-09-23 21:11:42.856222 +0000 UTC"
      + names   = [
          + "us-west2-a",
          + "us-west2-b",
          + "us-west2-c",
        ]
      + project = "my-project"
      + region  = "us-west2"
      + status  = "UP"
    }

...
```

Note that the value of the `id` attribute in the above output is different every time that `terraform plan` is executed.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan > plan1.txt` 
3. `terraform plan > plan2.txt`
4. `diff plan1.txt plan2.txt`

### Important Factoids

We use the output from `terraform plan` in our CI process. So if the `terraform plan` output is not completely idempotent, then that is a big problem for us.

### References

* terraform-providers/terraform-provider-aws#14579
* bflad/tfproviderlint#192
* hashicorp/terraform-provider-google#7092
* hashicorp/terraform-plugin-sdk#586
* terraform-providers/terraform-provider-oci#1148
* hashicorp/terraform#25812
* hashicorp/terraform/issues/25805

**Comment by edwardmedia** [comment]
I see the difference in id

**Comment by oscarwest** [comment]
We also see ID difference, e.g.

`
 <= data "aws_acm_certificate" "wildcard"  {
        arn         = "arn:aws:acm:us-east-1:...:certificate/...-...-..-...-..."
        domain      = "staging.some.domain"
      ~ id          = "2020-09-24 13:57:35.730091589 +0000 UTC" -> "2020-09-24 13:59:40.610712375 +0000 UTC"
        most_recent = false
        statuses    = [
            "ISSUED",
        ]
        tags        = {}
    }

`

**Comment by bflad** [comment]
Drive-by comment: This problem can have a few causes -- while the data source difference will show the more obvious `id` attribute change, there can actually be other data source schema issues which are at play as well including:

* Ensuring that data source attributes that are optionally configurable, but always call `d.Set()`, should set `Computed: true`. Terraform can determine this as a difference internally, since it is not expecting a value in the state when it is not configured. For example in the given example above, the `google_compute_zones` data source `region` attribute is missing this currently.
* Keeping an eye on `Default` usage in data sources, which can unexpectedly show a difference: https://github.com/hashicorp/terraform-plugin-sdk/issues/586

We have experimentally seen in the AWS Provider that sometimes these non-obvious fixes can actually hide the unexpected difference output of a data source even without stabilizing the `id` attribute (since in some contexts it may be considered a breaking change).
