### ISSUE TITLE
dataflow_flex_template_job labels not applied

### ISSUE THREAD

**Issue by BrianPi** [hashicorp/terraform-provider-google#7353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_dataflow_flex_template_job

### Expected Behavior

Labels should be applied to the Dataflow job created by the resource.

### Actual Behavior

Labels field is dropped.

**Comment by rileykarson** [comment]
Worth noting: it's possible for this resource that the labels field doesn't actually work yet, and that the API presented it (and we implemented it) a little too early.

**Comment by rileykarson** [comment]
Sorry, this fell through the cracks last week! Assigning to @slevenick, this week's bug onduty.

**Comment by slevenick** [comment]
Yeah, this definitely doesn't work yet. I'll mark the field as deprecated as a placeholder because the API does not support the label field currently.

**Comment by slevenick** [comment]
Closing this issue for now as the API doesn't support `labels` at this time. When the API supports this you can file an issue to request support and we should be able to add it fairly easily

I've marked `labels` as deprecated with a note on it not being available currently. Prefer this to removing the field to prevent breaking existing configs that specify labels
