### ISSUE TITLE
Cloud Run Data Sources

### ISSUE THREAD

**Issue by kamaz** [hashicorp/terraform-provider-google#7363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Checking current issues as well as code I couldn’t find any datasources for `cloud run`. I think it would be a good addition especially combined with a new features like `api gateway` when both needs to be deployed independently. 

For an use case we have we deploy the `cloud run` but then we have to deploy `api gateway` with a generated swagger where we have to attach the `address` to  google backend. Most of the transformation and building swagger can be achieved though existing terraform providers but then requires breaking when a service address is required.

I’m happy to contribute.

### New or Affected Resource(s)

* google_cloud_run

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

data "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"
}
```

**Comment by danawillow** [comment]
Seems reasonable! Assigning to you to contribute; let us know if you end up not getting around to it.
