### ISSUE TITLE
Allow refresh/restart in Stateful Managed Instance Group configuration

### ISSUE THREAD

**Issue by przsab** [hashicorp/terraform-provider-google#7382]
Currently restart and refresh operations defined on SMIG are not included in Terraform GCP provider even though some parts of configuration indicate the group may behave in such way.

Today no operations on SMIG are performed automatically, i.e. every update to instance template or group require update-instances or recreate-instances CLI, where minimal_action or most_disruptive_allowed_action has no effect. 

```
resource "google_compute_per_instance_config" "state" {
  provider   = google-beta
  depends_on = [google_compute_disk.disks, google_compute_disk.software-disk-01]

  name = local.db_instance_name
  instance_group_manager = google_compute_instance_group_manager.group.name
  zone                   = var.db_zone

  minimal_action = "REFRESH"
  most_disruptive_allowed_action = "RESTART"

  preserved_state {
    disk {
      device_name = "software-disk-01"
      source      = "projects/${var.db_project}/zones/${var.db_zone}/disks/${google_compute_disk.software-disk-01.name}"
      delete_rule = "ON_PERMANENT_INSTANCE_DELETION"
    }
    dynamic "disk" {
      for_each = local.disks
      content {
        device_name = disk.value.device
        source      = "projects/${var.db_project}/zones/${var.db_zone}/disks/${disk.value.name}"
        delete_rule = "ON_PERMANENT_INSTANCE_DELETION"
      }
    }
  }
}
```

CLI command to update SMIG:
```
gcloud compute instance-groups managed update-instances group1 --instances instance1 --most-disruptive-allowed-action refresh --minimal-action refresh --zone us-central1-a
```

Having a complete disparity between group behavior and Terraform introduces need for workaround in local-exec which in turn require local application auth for gcloud.

**Comment by slevenick** [comment]
Hey @przsab I believe that the per_instance_config resource actually *does* update instances. After updating a per_instance_config we call `applyUpdatesToInstances` ([this endpoint](https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/applyUpdatesToInstances)) for each per instance config that was updated. This happens here: https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_compute_per_instance_config.go#L396

Are you able to capture the debug logs for an update to see if this is happening? Or what is leading you to believe that the instances are not being updated?

**Comment by przsab** [comment]
Resolved by triggering per-instance-config update with instance template reference in metadata.

```
  preserved_state {
    metadata = {
      instance_template = google_compute_instance_template.template.self_link
    }
  }
```
