### ISSUE TITLE
GCS: DaysSinceNoncurrentTime lifecycle_rule condition

### ISSUE THREAD

**Issue by ball-hayden** [hashicorp/terraform-provider-google#7383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_storage_bucket` `condition` block currently supports a subset of available conditions.
https://www.terraform.io/docs/providers/google/r/storage_bucket.html#condition

Specifically, I am interested in being able to specify the `DaysSinceNoncurrentTime` condition: 
https://cloud.google.com/storage/docs/lifecycle#dayssincenoncurrenttime

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
resource "google_storage_bucket" "my_bucket" {
  # etc  

  lifecycle_rule {
    condition { days_since_noncurrent_time = "30" }
    action { type = "Delete" }
  }
}
```

### References

https://www.terraform.io/docs/providers/google/r/storage_bucket.html#condition
https://cloud.google.com/storage/docs/lifecycle#dayssincenoncurrenttime

**Comment by upodroid** [comment]
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7223

**Comment by ball-hayden** [comment]
Arg. I did search first, I promise.
Sorry!
