### ISSUE TITLE
google_compute_packet_mirroring support for collector destination in a peer network

### ISSUE THREAD

**Issue by howsTricks** [hashicorp/terraform-provider-google#7392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is an option to configure GCP packet mirroring to have a source and destination in different networks that are peered. Hoping to get this option exposed in the google_compute_packet_mirroring resource

### New or Affected Resource(s)

google_compute_packet_mirroring

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

#Current configuration
  network {
    url = google_compute_network.default.id
  }

#Proposed configuration
  mirrored_source_network {
    url = google_compute_network.mirrored_source.id
  }
  collector_destination_network {
    url = google_compute_network.collector_destination.id
  }
```

### References

See here for google documentation on the this functionality https://cloud.google.com/vpc/docs/packet-mirroring#collector_destination_in_a_peer_network

b/374162004

**Comment by ggtisc** [comment]
Hi @howsTricks!

Currently there is the [cidr_ranges](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_packet_mirroring#cidr_ranges) argument to achieve this goal

**Comment by nadav-steiner** [comment]
Hi @howsTricks. 

The google_compute_packet_mirroring resource already supports configuring mirroring to a collector in a peered network. This configuration is implicit, there's no special field involved. We deduce the fact that this is a peered network as we inspect the VPC associated with the collector ILB (forwarding rule) and compare it with the source VPC (the "network" argument).
