### ISSUE TITLE
GKE cluster changes not detected

### ISSUE THREAD

**Issue by debakkerb** [hashicorp/terraform-provider-google#7393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
tf version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/google v3.41.0
+ provider registry.terraform.io/hashicorp/google-beta v3.41.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke_cluster" {
  project     = google_project.gke_svc_project.project_id
  name        = "gke-cluster"
  description = "GKE cluster to use for troubleshooting issues."
  location    = "europe-west1"
  network     = google_compute_network.gke_host_network.self_link
  subnetwork  = google_compute_subnetwork.gke_host_subnet.self_link

  remove_default_node_pool = true
  initial_node_count       = 1
  logging_service          = "logging.googleapis.com/kubernetes"
  monitoring_service       = "monitoring.googleapis.com/kubernetes"
  enable_shielded_nodes    = true
  enable_legacy_abac       = false

  release_channel {
    channel = "RAPID"
  }

  master_auth {
    username = ""
    password = ""
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = "gke-pod-euw1-secondary"
    services_secondary_range_name = "gke-svc-euw1-secondary"
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block = google_compute_subnetwork.gke_host_subnet.ip_cidr_range
    }
  }

  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_ipv4_cidr_block  = "10.255.0.0/28"
  }

  node_config {
    service_account = google_service_account.gke_svc_service_account.email
    oauth_scopes = [
      "storage-ro",
      "logging-write",
      "monitoring"
    ]
  }

  timeouts {
    create = "10m"
    update = "20m"
  }

  depends_on = [
    google_project_iam_member.host_agent_svc,
    google_project_iam_member.gke_svc_sa_iam_permissions,
    google_project_iam_member.gke_svc_fwl_permissions,
    google_compute_subnetwork_iam_member.google_api_svc_host,
    google_compute_subnetwork_iam_member.service_robot_network_user,
    google_compute_shared_vpc_host_project.host_project_config,
    google_compute_shared_vpc_service_project.svc_attachment
  ]
}

resource "google_container_node_pool" "gke_node_pool" {
  provider   = google-beta
  project    = google_project.gke_svc_project.project_id
  name       = "gke-nodes"
  cluster    = google_container_cluster.gke_cluster.name
  location   = "europe-west1"
  node_count = 1

  node_config {
    image_type   = "COS_CONTAINERD"
    machine_type = "n2-standard-4"

    service_account = google_service_account.gke_svc_service_account.email
    oauth_scopes = [
      "storage-ro",
      "logging-write",
      "monitoring",
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

    disk_size_gb = 20
    disk_type    = "pd-ssd"
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  timeouts {
    create = "30m"
    update = "40m"
    delete = "2h"
  }

  depends_on = [
    google_container_cluster.gke_cluster,
    google_project_iam_member.host_agent_svc,
    google_project_iam_member.gke_svc_sa_iam_permissions,
    google_project_iam_member.gke_svc_fwl_permissions,
    google_compute_subnetwork_iam_member.google_api_svc_host,
    google_compute_subnetwork_iam_member.service_robot_network_user,
    google_compute_shared_vpc_host_project.host_project_config,
    google_compute_shared_vpc_service_project.svc_attachment
  ]
}
```

### Expected Behavior

Whenever I make a change to the configuration above, my GKE cluster is upgraded.

### Actual Behavior

Terraform doesn't detect any changes.

### Important Factoids

I have a host project and service project.  The cluster is deployed in the service project, but uses the network in the host project.  Initial runs are fine, the cluster is being created and everything works as usual.  However, when I make a change to the cluster, Terraform doesn't detect any changes and reports that it doesn't have to update the infrastructure:

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

For example, if I comment out the `private_cluster_config`-block, it should recreate the cluster.  But running a terraform apply doesn't report any changes.  Same for `release_channel`.

**Comment by debakkerb** [comment]
This is a provider issue.  I reverted back to 3.40.0 and now changes are detected.  Whenever I make an update to the cluster, Terraform now applies the changes.

**Comment by debakkerb** [comment]
I've done some more research and initially I thought it was linked to the provider version.  However, that's not true, because I've downgraded the provider to 3.38 and the problem still persists.  The strange thing is that it only shows up for certain configuration changes and not for others.

As mentioned in the initial description, I've removed the release channel and private config blocks and that didn't trigger an update of the infrastructure.  However, renaming the cluster did trigger an update and the cluster was recreated.

**Comment by slevenick** [comment]
This is a bit of not ideal interaction between Terraform and the API structure, but not really a bug. What is happening here is that the fields you are modifying are marked as `Computed` and `Optional` within our Terraform schema, which means if you don't declare them in your config they will not track changes and change the resource based on them. `Computed` means the resource will accept different values from the API if the field is not specified in your config.

This is done because the API may set default values, or for other reasons.

What this means is that removing `release_channel` from your config is equivalent to saying "I don't care what the release channel is set to" and *NOT* "Make sure release channel is unset". I believe it is actually impossible to set the release channel to nothing in the API, as a cluster always needs *some* release channel.

The way to fix this would be to figure out what release channel you want and set the value to that. Similarly for the private config, instead of removing the block you will want to fill it out in the state that you want it to be in.

If you want these fields to just default to whatever the server would normally do, you can force a recreate by tainting the resource or changing the name as you found.

**Comment by debakkerb** [comment]
Thanks for clarifying.  I had a look at the documentation again and it says indeed that Terraform will not unenroll it when the field is removed, so that makes sense now.

My colleague and I were looking at the provider code and apparently the same applies to the `private_access_config`-block: https://github.com/hashicorp/terraform-provider-google/blob/3bdd32795f221857b38a8fcda03282934b505003/google/resource_container_cluster.go#L3031.

**Comment by slevenick** [comment]
Ah, yeah looks like setting everything to false causes the server to not return the private cluster config, so we needed to ignore in that case.

Old bug here: https://github.com/hashicorp/terraform-provider-google/issues/3056
