### ISSUE TITLE
compute_instance_from_template does not need to replace instances when source_instance_template differs

### ISSUE THREAD

**Issue by Rob-S** [hashicorp/terraform-provider-google#7398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In GCP, the compute engine instances which have been created do not reference the instance template which was used to create them. This can also be seen in the template resource, where it shows that the templates have no entry "is use by". (Note that this is different from managed instance groups, where the template is "in use by" the group.)

Currently, Terraform replaces the compute engine instances if the template name has been changed. This is an unnecessary replacement of a perfectly good compute instance. It would be an improvement if a change to the source_instance_template no longer "forces replacement".

### New or Affected Resource(s)

* google_compute_instance_from_template

### Potential Terraform Configuration

```tf
resource "google_compute_instance_from_template" "gn1sqldba01" {
  project = "my-project"
  name    = "gn1sqldba01"
  source_instance_template = "dba-template-version-1" # to be updated to "dba-template-version-2"
  zone                     = us-central1-f
  allow_stopping_for_update = false
  deletion_protection       = true
}
```

### References
[pipelineLog-587.txt](https://github.com/hashicorp/terraform-provider-google/files/5309544/pipelineLog-587.txt)
[pipelineLog-589.txt](https://github.com/hashicorp/terraform-provider-google/files/5309546/pipelineLog-589.txt)

**Comment by Rob-S** [comment]
Without this enhancement, there is a somewhat tedious workaround:

1. Enable deletion protection on the compute instance(s).
2. Delete the template via the GCP Console UI.
3. Make the changes to the template, keeping the same "name".
4. Run `terraform plan` and `terraform apply` once to recreate the templates. It will attempt to recreate the CE instances, but fail due to the deletion protection.
5. Run `terraform plan` and `terraform apply` again. Now that the updated template exists with the same name, Terraform will no longer attempt to recreate the CE instances.

**Comment by danawillow** [comment]
Hi @Rob-S, we talked about this in our triage meeting this week and decided we would not like to pursue this FR. Unfortunately, there's no good way for us to tell the user's intent here- they may have changed the name of the instance template specifically _because_ they made a new instance template and want the instance to be recreated based on it, and I think that silently allowing the field to be updated without actually making any changes to the instance would be surprising behavior to someone who wasn't expecting it. If your use case doesn't need that field to be modified or checked for drift, you can set lifecycle.ignore_changes to point to it after it's been created so that Terraform doesn't produce a diff based on that field.

**Comment by Rob-S** [comment]
@danawillow OK. I was thinking that the field values in GCP would be more definitive than the ones in Terraform (as indicated by the first sentence in my original "Description" and based on the "refreshing state" messages you see during plan and apply). So, if the diffs are based on the Terraform fields rather than the GCP instance attributes...

In that case, would it be possible to add the "source_instance_template" attribute to the "google_compute_instance" data source? That way you could get the name of the current template from the Terraform state and prevent the instance from being replaced. Currently, you have to hard-code the name of the template in the source_instance_template attribute and, when using name_prefix, that requires going into the GCP console to find the name of the template that was generated, then copy and paste it into that attribute in the Terraform configuration.

**Comment by danawillow** [comment]
I don't think we could add `source_instance_template` to the data source since that would require us to be able to query GCP for the instance template used for a specific instance, which as you mentioned, isn't something available in the API. In the provider implementation there isn't any way to read the state of any resource/data source other than the one being acted on, so we wouldn't be able to get it from the state of a different resource.

**Comment by Rob-S** [comment]
@danawillow The stored value of the `source_instance_template` field would already be available, or at least accessible (from the Terraform state as we've both mentioned), since it needs to be there in order to compare and determine if that field has changed, and trigger the Compute Engine instance to be recreated, even though nothing in the CE itself has been changed.

In our environment, Terraform is running in git Pipelines under a service account and can be run by quite a number of individuals. This presents a number of issues related specifically to the issue with the source instance template name:
- After creating a compute engine instance, you have to go back and update the Terraform configuration with the name of the template that was used. Otherwise the next time a pipeline is run it tries to recreate the instance. An example of this happening is attached. [pipelineLog-723.txt](https://github.com/hashicorp/terraform-provider-google/files/5423782/pipelineLog-723.txt)
- Therefore, you have to update the configuration with the actual name of the template that was used and run an extra pipeline, to make sure someone else's pipeline run doesn't recreate the instance.
- Since the state is being managed by the pipelines, we can't access the Terraform state to get the correct template name. We can go into the Google Cloud Console and get the name of the template, to update the configuration for the extraneous pipeline run.
- In some cases, if there are more than one template for the same name_prefix, you might get the wrong name on the first extraneous pipeline run. When you run the pipeline, the Terraform plan will show the correct template name as the reason it's replacing the instance. So you can get the correct template name directly from Terraform at that point and get it right for the second extraneous pipeline run.

So when you really should only need one Terraform plan/apply run, it takes at least 2-3 runs, to ensure your compute engine is not going to be attempted to be replaced later. Given the extra work that Terraform is necessitating, if it was up to me I would prefer to manage the GCP resources directly in the GC console.

**Comment by danawillow** [comment]
It sounds like the issue is that the template name is getting changed between Terraform runs. Is that something you're specifically trying to do, is it an artifact of your process, or are you not sure why it's happening? If the name isn't actually supposed to change on every run, I'd love to look at your config so I can try to figure out why that's happening.
