### ISSUE TITLE
google_compute_url_map fails when configuring CORS

### ISSUE THREAD

**Issue by hedlund** [hashicorp/terraform-provider-google#7400]
I'm having problems applying CORS rules to `google_compute_url_map` resources. It does not matter if I apply them as `default_route_action`, or nested in a `path_matcher`- the result is always the same.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.3

### Affected Resource(s)

* provider registry.terraform.io/hashicorp/google v3.41.0

### Terraform Configuration Files

```tf
# Simplified setup, that should contain everything needed.
# The offending resource is the google_compute_url_map at
# the bottom.

resource "google_project" "project" {
  name            = "A project"
  project_id      = "a-project"
}

resource "google_project_service" "compute" {
  project = google_project.project.project_id
  service = "compute.googleapis.com"
}

resource "google_storage_bucket" "bucket" {
  project       = google_project.project.project_id
  name          = "a-bucket"
  location      = "EU"
  storage_class = "MULTI_REGIONAL"

  uniform_bucket_level_access = true
}

resource "google_compute_backend_bucket" "backend" {
  project     = google_project.project.project_id
  name        = "bucket-backend"
  bucket_name = google_storage_bucket.bucket.name
  enable_cdn  = true
  depends_on  = [google_project_service.compute]
}

# This is the problematic resource, the rest is just boilerplate
resource "google_compute_url_map" "urls" {
  project         = google_project.project.project_id
  name            = "urls"
  default_service = google_compute_backend_bucket.backend.self_link

  default_route_action {
    cors_policy {
      disabled = false

      # Any values I change here, will trigger an error
      allow_credentials = true
    }
  }
}
```

### Debug Output

[https://gist.github.com/hedlund/cb3fe8ac2c328d0be8e300e71d603457](https://gist.github.com/hedlund/cb3fe8ac2c328d0be8e300e71d603457)

### Expected Behavior

The CORS rules should be applied.

### Actual Behavior

Terraform fails with the error:

```
Error: Error waiting for Updating UrlMap: generic::invalid_argument: Message does not pass whitelist validation. The offending field is a submessage of SimplifiedHttpRouteAction (UrlMap.SimplifiedHttpRouteAction) at field number 7 (UnknownField::Type 3).
```

### Steps to Reproduce

Simply apply the rules above with *any* CORS parameter, besides the `disabled`, and the error occurs. I have tried various combinations, and everything yields the same result. The example above was the most minimal one that yielded the error.

1. `terraform apply`

### Important Factoids

Nothing atypical AFAIK.

### References

None that I know of.

**Comment by hedlund** [comment]
I also tried applying the rule with the beta provider, but that made no difference.

**Comment by hedlund** [comment]
Could the error be due to the fact that the backend is a bucket? I haven't tried it with another type of backend, and on the `google_storage_bucket` resource itself, it is also possible to configure CORS (albeit not as nice as on the URL map).

**Comment by edwardmedia** [comment]
@hedlund I am able to create below resource without problem. I noticed you have only enable one service using above code. I wondered if other api services that might be needed. Please do research and let me know 

```
# google_compute_url_map.urls:
resource "google_compute_url_map" "urls" {
    creation_timestamp = "2020-10-01T09:32:12.159-07:00"
    default_service    = "https://www.googleapis.com/compute/v1/projects/myproject/global/backendBuckets/issue7400-bucket-backend"
    fingerprint        = "K1RFrO-jV9c="
    id                 = "projects/myproject/global/urlMaps/urls"
    map_id             = 4155249095756986979
    name               = "urls"
    project            = "sunedward-1-autotest"
    self_link          = "https://www.googleapis.com/compute/v1/projects/myproject/global/urlMaps/urls"
    default_route_action {
        cors_policy {
            allow_credentials = true
            disabled          = false
            max_age           = 0
        }
    }
}
```

**Comment by hedlund** [comment]
@edwardmedia I'm prone to agree. I tried editing the resource using the plain Google API, and that yielded the same results, indicating this has nothing to do with Terraform.

I've tried enabling the most likely services for the project, but no dice. Any possibility to get a list of what service you have the project where you could get it to work?

Anyways, feel free to close this issue, as it most likely has nothing to do with Terraform itself.

**Comment by edwardmedia** [comment]
Closing this, as suggested. Thanks
