### ISSUE TITLE
Updating the bandwidth field of google_compute_interconnect_attachment forces a recreation instead of updating in place

### ISSUE THREAD

**Issue by nathkn** [hashicorp/terraform-provider-google#7403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.24

### Affected Resource(s)

* google_compute_interconnect_attachment

### Expected Behavior

In the UI you can update the egress bandwidth for an interconnect attachment in-place: 
![image](https://user-images.githubusercontent.com/41593086/94831778-bd5df900-03d2-11eb-967a-4af2e7fcc639.png)

And I'd expect to be able to update the bandwidth of the attachment without needing the attachment to be recreated, which causes service interruption.

### Actual Behavior

When running the terraform apply, it tries to recreate the attachment:
```
  # google_compute_interconnect_attachment.my-attachment must be replaced
-/+ resource "google_compute_interconnect_attachment" "my-attachment" {
      ...
      ~ bandwidth                  = "BPS_2G" -> "BPS_5G" # forces replacement
      ...
```

### Steps to Reproduce

1. Create an interconnect attachment with a set bandwidth in terraform
2. Update the bandwidth field and run terraform apply

**Comment by edwardmedia** [comment]
@nathkn can you provide your config and the debug log?

**Comment by edwardmedia** [comment]
@nathkn is this still an issue?

**Comment by nathkn** [comment]
@edwardmedia yes it is still an issue, it's not particularly easy to redact all the private info from the config/debug, but I'll try to get something for you. I was hoping it'd be something to find without that for that reason.

**Comment by nathkn** [comment]
still working on debug logs, but it seems pretty clear without them that the `input: true` [line here](https://github.com/GoogleCloudPlatform/magic-modules/blob/2eae605c9b536d9ed1e9d3b9706fcae07ec6cf26/products/compute/api.yaml#L6960) is set erroneously: 

```yaml
- !ruby/object:Api::Type::Enum
        name: 'bandwidth'
        input: true
        description: |
          ...
```

**Comment by nathkn** [comment]
and here is the config and debug logs
https://gist.github.com/nathkn/514468fdb65ebb9e21bfdbb4f5efbe16

**Comment by nathkn** [comment]
closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/4205
