### ISSUE TITLE
google_service_networking_connection refresh bug

### ISSUE THREAD

**Issue by n-chiappero** [hashicorp/terraform-provider-google#7404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/google v3.41.0

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
variable "gcp_project_name" {
  type = string
  default = "my-project-XXXX"
  description = "GCP project where resources will be created"
}

variable "gcp_project_folder_id" {
  type = string
  description = "GCP organisation folder id where project will be created"
}

variable "gcp_region" {
  type = string
  default = "europe-west1"
  description = "location for your resources to be created in"
}

variable "gcp_zone" {
  type = string
  default = "europe-west1-b"
  description = "Availability zone"
}

variable "storage_service_account_name" {
  type = string
  default = "storage"
  description = "Storage Service Account name"
}

variable "billing_account_display_name" {
  description = "Billing account display name"
}

resource "google_project" "project" {
  name = var.gcp_project_name
  project_id = var.gcp_project_name
  folder_id = var.gcp_project_folder_id
  billing_account = data.google_billing_account.account.id
}

data "google_billing_account" "account" {
  display_name = var.billing_account_display_name
  open = true
}

resource "google_project_service" "services" {
  project = var.gcp_project_name
  for_each = toset([
    "compute",
    "servicenetworking",
  ])
  service = "${each.value}.googleapis.com"
  disable_on_destroy = false
}

resource "google_compute_network" "network" {
  project = var.gcp_project_name
  name = "${var.gcp_project_name}-network"
  depends_on = [
    google_project_service.services["compute"]
  ]
}

resource "google_compute_global_address" "private_ip_address" {
  project = var.gcp_project_name
  name = "private-ip-address"
  purpose = "VPC_PEERING"
  address_type = "INTERNAL"
  prefix_length = 16
  network = google_compute_network.network.id
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network = google_compute_network.network.id
  service = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [
    google_compute_global_address.private_ip_address.name
  ]
  depends_on = [
    google_project_service.services["servicenetworking"]
  ]
}

resource "google_service_account" "storage-sa" {
  project = var.gcp_project_name
  account_id = var.storage_service_account_name
  display_name = "Storage service account"
  depends_on = [
    google_project_service.services["compute"]
  ]
}

data "google_iam_policy" "storage-sa-roles" {
  binding {
    role = "roles/storage.admin"
    members = [
      "serviceAccount:${google_service_account.storage-sa.email}",
    ]
  }
}

resource "google_project_iam_policy" "storage-policy" {
  project = var.gcp_project_name
  policy_data = data.google_iam_policy.storage-sa-roles.policy_data
  depends_on = [
    google_project_service.services["compute"]
  ]
}

```

### Debug Output

https://gist.github.com/n-chiappero/9c03dd12ee2188e338eed5f7143ce513

### Panic Output

None

### Expected Behavior

apply or refresh with no error.

### Actual Behavior

After several times executing 'terraform apply' :
```
Error: googleapi: Error 400: Precondition check failed., failedPrecondition
```

### Steps to Reproduce

https://gist.github.com/n-chiappero/4c7dc187dd9a58c58bc8f8d7134d90cc

1. `terraform apply`
2. `terraform apply`
3. `terraform apply`
4. `terraform apply`
5. `terraform apply`
6. `terraform apply`
7. `terraform apply`

### Important Factoids

Number of executions needed to reproduce this error seems to be variable.
I have many resources, which I managed to reduce to this example to be able to reproduce the bug:
If there are no google_service_account and a google_service_networking_connection, everything is running fine.
If there are a google_service_account and no google_service_networking_connection, everything is running fine.
But as soon as there are a google_service_networking_connection and a google_service_account, it is not working anymore.

### References

None

**Comment by slevenick** [comment]
Hey @n-chiappero does this only happen when you call `terraform apply` many times in quick succession? Does the API call that returns the 400 error succeed for the other times that you run `terraform apply`?

To me this sounds like a quota issue, as most of the GCP APIs have limits on the number of requests you can make per (minute | second | hour)

It would be helpful if you could include logs from a successful run as well as an unsuccessful run. It will let me see if the issue is with the Terraform resource itself or something with the API

**Comment by n-chiappero** [comment]
Hi Sam, thank you for taking some time to look at this.
I seriously doubt it is a question of rate/limit, because once I got the error, it never runs without error again. I have to delete the project.
Plus, I ran the tests with `-parallelism=1` option, which should avoid doing concurrent requests.
I did the test on a freshly new project this morning:
1. First run : https://gist.github.com/n-chiappero/64ccd78aae16ec0f779c2c11ec2b9b6a
1. I got an error, so I ran `terrafom apply` another time, 2 mins later : 
https://gist.github.com/n-chiappero/40628544155ee12975a60622fd6c3e55
1. I waited 9 mins and ran `terrafom apply`again, and I got the 400 error : 
https://gist.github.com/n-chiappero/aefffd4efc09d4cd366bd553a223b58d

**Comment by slevenick** [comment]
Ok that is very strange. The same request succeeds one time and fails another, and it's a GET request so its pretty simple. If I had to guess I would say something about your service networking is setting up incorrectly behind the scenes, so it succeeds at first but then stops working.

Honestly I don't know much about service networking or why this would be happening, and this doesn't seem to be a provider problem so I'll reach out to some other people and see what I can find

**Comment by slevenick** [comment]
Checked with the team, it looks like this was a temporary error and shouldn't happen anymore. If you are able to reproduce this please let me know and I'll reopen this
