### ISSUE TITLE
maintenance_window of google_sql_database_instance replica is stuck - not changing / updating / refreshing

### ISSUE THREAD

**Issue by syedrakib** [hashicorp/terraform-provider-google#7422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

+ Terraform v0.12.29
+ provider.google v3.41.0
+ provider.google-beta v3.41.0

### Affected Resource(s)

google_sql_database_instance

# The issue:

My current TF state file shows the following for my Google CloudSQL Replica instance.

```json
    maintenance_window: []
```

My new TF configuration for my Google CloudSQL Replica instance is

```terraform
maintenance_window {
  day          = 1
  hour         = 23
  update_track = "canary"
}
```

✅ My TF Plan reads fine:

```terraform
+ maintenance_window {
    + day          = 1
    + hour         = 23
    + update_track = "canary"
  }

Plan: 0 to add, 1 to change, 0 to destroy.
```

❌ I run `terraform apply`. I get the following error

```shell
Error: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Cannot update maintenance window for replica instances., invalid
```

❌ Meaning, the operation failed and nothing should've changed. But when i check my TF state file, i see that it has changed

```json
"maintenance_window": [
  {
    "day": 1,
    "hour": 23,
    "update_track": "canary"
  }
]
```

❌ **The state file shouldn't have changed since the `terraform apply` had failed.**

Now, when i run the `terraform plan`, it produces the same unaltered plan as before.

```terraform
+ maintenance_window {
    + day          = 1
    + hour         = 23
    + update_track = "canary"
  }

Plan: 0 to add, 1 to change, 0 to destroy.
```

---

❓ I am not able to move beyond this. My CloudSQL ReadReplica is constantly producing this same plan and I am constantly getting a 400 error when trying to `terraform apply`. Hence, i can't proceed.

I also tried to set the `maintenance_window` of the instance manually from the GCP console. However, GCP doesn't even provide any interface to modify `maintenance_window` for ReadReplica instances - which is why the 400 error in the first place.

----

Looking for help here. Using latest 0.12.x version of Terraform **0.12.29**, and latest version of google provider **3.41.0**

**Comment by edwardmedia** [comment]
@syedrakib can you post your config and the steps to reach the issue?

**Comment by syedrakib** [comment]
I used the [**v3.2.0** of the **terraform-google-sql-db / mysql** module](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/v3.2.0/modules/mysql) for my work. It is [these lines](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/v3.2.0/modules/mysql/read_replica.tf#L104,L108) that are causing the issue.

Please note that, even though its [providers.tf file](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/v3.2.0/modules/mysql/versions.tf#L20) says it uses `terraform = "~> 0.12.6"` and `google = "~> 3.5"`, i am actually using the latest terraform 0.12.x version **v0.12.29** and passing the latest google-provider version **v3.41.0** to this module.

----

The fact that running `terraform apply` caused the state file to change even though it failed with a 400 error from google is the concerning part. That should be handled by the provider correctly, right?

**Comment by edwardmedia** [comment]
@syedrakib instead of module, can try run a single instance by removing unrelated field? Please provide the full debug log, if the problem still occurs.

**Comment by edwardmedia** [comment]
@syedrakib is this still an issue?

**Comment by edwardmedia** [comment]
@syedrakib closing this as no response received. Please retested by separating the provider code from the module. Feel free to reopen it if the issue can be reproed.
