### ISSUE TITLE
Monitoring alert policies: Unexpected diff when filter contains line breaks

### ISSUE THREAD

**Issue by MajorBreakfast** [hashicorp/terraform-provider-google#7425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.26

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "postgres" {
  project               = var.project
  display_name          = "${var.name}: Postgres"
  notification_channels = [data.google_monitoring_notification_channel.main.name]

  combiner = "OR"
  conditions {
    display_name = "Assert that utilization of disk is under 80%"
    condition_threshold {
      filter          = <<-EOF
        metric.type = "cloudsql.googleapis.com/database/disk/utilization"
        resource.type = "cloudsql_database"
        resource.label.database_id = ${jsonencode("${var.project}:${var.postgres_instance_name}")}
        EOF
      duration        = "60s"
      comparison      = "COMPARISON_GT"
      threshold_value = 0.8
    }
  }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The provider shows an unexpected diff for all alert policies. This diff should ideally not be there.

### Actual Behavior

My filter contains line breaks. These line breaks seem to get removed at some point and consequently produce an artificial diff.
```
  ~ resource "google_monitoring_alert_policy" "postgres" {
        ...
      ~ conditions {
            ...
          ~ condition_threshold {
                comparison      = "COMPARISON_GT"
                duration        = "60s"
              ~ filter          = <<~EOT
                  - metric.type="cloudsql.googleapis.com/database/disk/utilization" resource.type="cloudsql_database" resource.label.database_id="my-project:my-db"
                  + metric.type = "cloudsql.googleapis.com/database/disk/utilization"
                  + resource.type = "cloudsql_database"
                  + resource.label.database_id = "my-project:my-db"
                EOT
                ...
            }
        }
    }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Using a heredoc to to define the filter. The filter string is a bit long. The heredoc 

### References

n/a

**Comment by michael-bernards-db** [comment]
👍

**Comment by edwardmedia** [comment]
@MajorBreakfast what do you see if you add **AND** between each?

**Comment by MajorBreakfast** [comment]
Weirdly enough I too don't see it anymore today and I don't know what changed compared to what I saw yesterday and during the past few weeks. I'm going to close this issue and reopen a more precise one if I encounter it again. Thank you for having a look!

Note: The people voting thumbs up are people on my team who saw the diffs in our ci
