### ISSUE TITLE
Creating a firebase project uses the default project instead of the specified one

### ISSUE THREAD

**Issue by v-morlock** [hashicorp/terraform-provider-google#7427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.4

### Affected Resource(s)

* google_firebase_project

### Terraform Configuration Files

```tf
resource "random_string" "firebase" {
  length  = 3
  special = false
  upper   = false
  number  = false
}

resource "google_project" "firebase" {
  name       = "firebase"
  project_id = "firebase-${random_string.firebase.result}"
  provider   = google-beta

  org_id = "xxx"
}

resource "google_project_service" "firebase_api" {
  service                    = "firebase.googleapis.com"
  project                    = google_project.firebase.project_id
  disable_dependent_services = true
  provisioner "local-exec" {
    command = "sleep 15"
  }
}


resource "google_firebase_project" "firebase" {
  depends_on = [google_project_service.firebase_api]

  provider = google-beta
  project  = google_project.firebase.project_id
}
```

### Debug Output

https://gist.github.com/v-morlock/e3d5dd8ad6f0db176f02d2ba8c9c6a10

### Expected Behavior

Firebase shall be enabled in the project specified in google_firebase_project.project

### Actual Behavior

According to the logs, the resource tried to enable firebase in the provider's default project.

### Steps to Reproduce

1. initialize the google provider with project A as default
2. try to enable firebase in project B

### Important Factoids

We are trying to enable firebase in a submodule.

**Comment by edwardmedia** [comment]
@v-morlock is this similar to https://github.com/hashicorp/terraform-provider-google/issues/6377? 
Can you add below code before `google_firebase_project`?
```tf
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }
  triggers = {
    "project" = "${google_project.project.id}"
  }
}
```

**Comment by edwardmedia** [comment]
@v-morlock  Is this still an issue?

**Comment by edwardmedia** [comment]
@v-morlock I am closing this issue now. Feel free to reopen it if this is still an issue
