### ISSUE TITLE
Missing datasource : google_runtimeconfig_variable

### ISSUE THREAD

**Issue by azuenko** [hashicorp/terraform-provider-google#7428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It seems that `google_runtimeconfig_variable` datasource is missing and there is no way to read existing variables into TF runtime. It would be good to have a straightforward way to convey configuration data into TF runtime from external sources, like shell scripts of manual `gcloud` invocations. The issue is not quite critical as there is a workaround - use instead `google_secret_manager_secret_version`  data source from Secret Manager. 

### New or Affected Resource(s)

new datasource:

* google_runtimeconfig_variable

### Potential Terraform Configuration

```tf
data "google_runtimeconfig_variable" "variable" {
  name = "my-runtime-config-variable"
}
```

**Comment by brandonjbjelland** [comment]
I'm running into the same need as the original requestor here: needing the data stored in the variable much like would be fetched from `google_secret_manager_secret_version` as mentioned. The data source merged here looks like it was for `google_runtimeconfig_config` and not `google_runtimeconfig_variable`. Starting a PR on MM.
