### ISSUE TITLE
Promote GitHub cloud build triggers to GA

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#7435]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[The documentation for the cloudbuild triggers API](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.triggers#CommentControl) doesn't specify that the GitHub triggers are in beta, but they haven't yet [been promoted to GA in terraform](https://github.com/GoogleCloudPlatform/magic-modules/blob/cad7e56/products/cloudbuild/api.yaml#L172).

### New or Affected Resource(s)

* google_cloudbuild_trigger.github

### Potential Terraform Configuration

N/A - terraform wouldn't change; just promoting to GA.

### References

* Discovered while investigating https://github.com/hashicorp/terraform-provider-google/issues/7366

**Comment by rileykarson** [comment]
We should follow up with the team to determine if the feature is experimental

**Comment by melinath** [comment]
The team confirms that the feature is not experimental; the docs are just out of date slightly. Github triggers are GA.

**Comment by melinath** [comment]
Sorry, clarification - the feature is not experimental, but the API is.

**Comment by rileykarson** [comment]
That's GA for our purposes, generally- we track the stability of the underlying feature and not the API.

**Comment by melinath** [comment]
That makes sense - thanks!

**Comment by Tenzer** [comment]
https://cloud.google.com/cloud-build/release-notes also lists GitHub triggers as being GA since Feb 6th, 2020.
