### ISSUE TITLE
Release channel stable defaults to old GKE version v1.15.12-gke.20

### ISSUE THREAD

**Issue by nicoleczhu** [hashicorp/terraform-provider-google#7438]
To reproduce: 
1. Install Terraform v0.13.4 with something like: 
```
sudo apt-get install unzip && \
  wget -q https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip -O ./terraform.zip && \
  unzip -o terraform.zip && \
  sudo install terraform /usr/local/bin
```
2. Provision "google_container_cluster" "gke"  with provider "google-beta", any zone, no other special configs
3. Deploy everything and note that the cluster version is `v1.15.12-gke.20`

Expected: 
It's not clear from documentation which official release channel Terraform defaults to: 
https://cloud.google.com/kubernetes-engine/docs/release-notes

I expected Version 1.16.13-gke.401, given the Oct 2 release notes that: **"Version 1.16.13-gke.401 is the new default version in the Stable channel."**

any help is appreciated here. thank you

**Comment by edwardmedia** [comment]
@nicoleczhu Here is what Terraform doc says. Terraform does not control the version. You can always set it to a particular version (minimum) if you want. Does this make sense?

```
min_master_version - (Optional) The minimum version of the master. GKE will auto-update the master to new versions, so this does not guarantee the current master version--use the read-only master_version field to obtain that. If unset, the cluster's version will be set by GKE to the version of the most recent official release (which is not necessarily the latest version). ```

**Comment by nicoleczhu** [comment]
> @nicoleczhu Here is what the Terraform plugin [doc](https://www.terraform.io/docs/providers/google/r/container_cluster.html) says. The Terraform provider does not control the version. You can always set it to a particular version (minimum) if you want. Does this make sense?
> 
> ```
> min_master_version - (Optional) The minimum version of the master. GKE will auto-update the master to new versions, so this does not guarantee the current master version--use the read-only master_version field to obtain that. If unset, the cluster's version will be set by GKE to the version of the most recent official release (which is not necessarily the latest version). ```
> ```

Thanks Edward for your help! 

So if you run `gcloud container clusters create...` right now, they default to v1.16 of gke. I'm also hoping to avoid pinning a specific GKE version in Terraform. 

So my question is: when Terraform says `If unset, the cluster's version will be set by GKE to the version of the most recent official release (which is not necessarily the latest version)`, which "official release" is Terraform talking about?

GKE has multiple official releases via no/stable/fast channels. And by the way, setting release_channel doesn't change the GKE version either. Really scratching my head on this one. Thanks again!

**Comment by edwardmedia** [comment]
@nicoleczhu here is the [doc](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters) that might help answer your questions. 

initialClusterVersion

[ReleaseChannel](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#releasechannel)

**Comment by nicoleczhu** [comment]
thanks for your help! 

you are right. so it turns out... Google does a staged release across 4 days to cover all the zones. I was using a Day 4 zone -.-

**Comment by edwardmedia** [comment]
@nicoleczhu I am glad you have got the answers. Closing the issue then.
