### ISSUE TITLE
Add a google_compute_router_nat datasource

### ISSUE THREAD

**Issue by mgarstecki** [hashicorp/terraform-provider-google#7458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I need the list of IP addresses assigned to my NAT instance, so that I can whitelist them in other parts of my infrastructure, and can't find a way to list them with existing datasources.

I can't load a list of addresses, and the address object itself does not seem to have enough metadata anyway to link it to the Cloud NAT instance that uses it. Being able to load the details of the NAT instance could give me the self-links of the IPs, which is enough to then get their IPs.

My current alternatives seem to be to use remote_state or an external datasource with a gcloud script, but both options are a bit brittle.

Having also a data for Cloud Routers and to list Cloud NAT instances of a router might also be useful in the general case, though I don't need them for my use case: I have a deterministic naming convention for my Cloud NAT instances, so I can find the right one by name.

### New or Affected Resource(s)

* google_compute_router_nat datasource

### Potential Terraform Configuration

```tf
data "google_compute_router_nat" "subnet_nat" {
  # Required parameters of the "gcloud compute routers nats describe" command
  name = var.nat_name
  router = var.router_name
}
```

**Comment by jtyr** [comment]
This is related to https://github.com/hashicorp/terraform-provider-google/issues/7469.

**Comment by AarshDhokai** [comment]
b/263862606
