### ISSUE TITLE
validVersions based on version_prefix in google_container_engine_versions

### ISSUE THREAD

**Issue by vfiset** [hashicorp/terraform-provider-google#7462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

After a discussion with @rileykarson we've come to agreement that I should log a PR to expose `validVersions` based on `version_prefix` in `google_container_engine_versions`.

With this the user can get the latest valid version for his channel while respecting the `version_prefix` that is configured in the `google_container_engine_versions` data source.

`validVersions` is already available in the api response:
```
  {
   "channel": "RAPID",
   "defaultVersion": "1.18.6-gke.4801",
   "validVersions": [
    "1.18.9-gke.801",
    "1.18.6-gke.4801",
    "1.17.9-gke.1504"
   ]
  },
  {
   "channel": "REGULAR",
   "defaultVersion": "1.17.9-gke.1504",
   "validVersions": [
    "1.17.9-gke.6300",
    "1.17.9-gke.1504"
   ]
  },
```

### New or Affected Resource(s)

* google_container_engine_versions

### Potential Terraform Configuration

```tf
data "google_container_engine_versions" "main" {
  provider = google-beta
  project = var.gcp_project
  location = "us-east1-d"
  version_prefix = "1.16."
}

resource "google_container_cluster" "gke-cluster" {
  ...
  min_master_version = data.google_container_engine_versions.main.release_channel_valid_versions["REGULAR"][0]
  # or: 
  min_master_version = data.google_container_engine_versions.main.release_channel_latest_valid_versions["REGULAR"]
```

### References

* [GCP slack post](https://googlecloud-community.slack.com/archives/C1VNJ4EG7/p1602092552043800)

**Comment by matthieu-audin** [comment]
Is there any update regarding this subject ?
I can not pick the latest version available depending on the release channel

**Comment by sathieu** [comment]
I've proposed: https://github.com/hashicorp/terraform-provider-google/pull/12892

**Comment by sathieu** [comment]
Not the right project. The new PR is at: https://github.com/GoogleCloudPlatform/magic-modules/pull/6746
