### ISSUE TITLE
[resource/monitoring_alert_policy] Add support and docs example for MQL Alerting Policy

### ISSUE THREAD

**Issue by naseemkullah** [hashicorp/terraform-provider-google#7464]
### Description

https://cloud.google.com/monitoring/mql/alerts have recently been made available, they can be created in the UI, but have not had luck with terraform

### New or Affected Resource(s)

* google_monitoring_alert_policy

### References

https://cloud.google.com/monitoring/mql/alerts

**Comment by femnad** [comment]
Added a PR proposing to address this issue.

**Comment by yegle** [comment]
It looks like https://github.com/hashicorp/terraform-provider-google-beta/pull/2651 just missed the v3.45.0 cutoff.

What's the release cadence for the beta provider? Thank you!

**Comment by ndmckinley** [comment]
It should be released next Monday.  :)
