### ISSUE TITLE
google_monitoring_dashboard terraform destroy fail

### ISSUE THREAD

**Issue by mxfactorial** [hashicorp/terraform-provider-google#7471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/google v3.42.0

### Affected Resource(s)

google_monitoring_dashboard

### Terraform Configuration Files

```tf
resource "google_monitoring_dashboard" "default" {
  project = "a-project"
  dashboard_json = <<EOF
{
  "displayName": "a dashboard",
  "gridLayout": {
    "columns": "2",
    "widgets": [
      {
        "title": "a widget",
        "xyChart": {
          "dataSets": [
            {
              "minAlignmentPeriod": "60s",
              "plotType": "LINE",
              "timeSeriesQuery": {
                "timeSeriesFilter": {
                  "aggregation": {
                    "perSeriesAligner": "ALIGN_RATE"
                  },
                  "filter": "metric.type=\"compute.googleapis.com/instance/cpu/usage_time\"",
                  "secondaryAggregation": {}
                }
              }
            }
          ],
          "chartOptions": {
            "mode": "COLOR"
          },
          "timeshiftDuration": "0s",
          "yAxis": {
            "label": "y1Axis",
            "scale": "LINEAR"
          }
        }
      }
    ]
  }
}
EOF
}
```

### Debug Output

https://gist.github.com/mxfactorial/64888e50d5012a7952e8fedde52ab9d6

### Expected Behavior

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
### Actual Behavior

```
Error: Error when reading or editing MonitoringDashboard "projects/REMOVED/dashboards/f4cea24e-3427-4460-86cd-66fd1abb22a5": Delete "Terraform/0.13.3%20%28+https://www.terraform.io%29%20Terraform-Plugin-SDK/2.0.3%20terraform-provider-google/3.42.0%20?alt=json": unsupported protocol scheme ""
```
### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

### Important Factoids

none

### References

* #0000

**Comment by danawillow** [comment]
The fix for this has been submitted and will appear in the next release: see https://github.com/GoogleCloudPlatform/magic-modules/pull/4064 for the fix.
