### ISSUE TITLE
GKE nodepool optional autoscaling enable/disable

### ISSUE THREAD

**Issue by akhilesh0** [hashicorp/terraform-provider-google#7473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.20
+ provider.google v3.15.0
+ provider.google-beta v3.42.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
dynamic "autoscaling" {
    for_each = element(var.autoscaling_min, count.index) == null && element(var.autoscaling_max, count.index) == null ? [1] : []
    content {
      min_node_count = element(var.autoscaling_min, count.index)
      max_node_count = element(var.autoscaling_max, count.index)
    }
  }

variable "autoscaling_min" {
     default = [null, 10]
}

variable "autoscaling_max" {
    default = [null, 20]
}
```

### Debug Output

Error: Required attribute is not set

  on .terraform/main.tf line 5, in resource "google_container_node_pool" "node_pools":
   5: resource "google_container_node_pool" "node_pools" {

Error: Required attribute is not set

  on .terraform/main.tf line 5, in resource "google_container_node_pool" "node_pools":
   5: resource "google_container_node_pool" "node_pools" {

### Expected Behavior

For 1st nodepool autoscaling should be disabled
For 2nd nodepool autoscaling should be enabled with min 10 and max 20

### Actual Behavior

Plan is throwing error as min and max value must be set.
### Steps to Reproduce

Create 2 nodepool with count as 2. Enable autoscaling for 1st nodepool and disable for the other.
1. `terraform apply`

### References

* #0000

b/301066187

**Comment by venkykuberan** [comment]
@akhilesh0 can you please share your plan output ?

**Comment by akhilesh0** [comment]
@venkykuberan : I have already mentioned plan output in Debug Output. Below is the log
```
Error: Required attribute is not set

on .terraform/main.tf line 5, in resource "google_container_node_pool" "node_pools":
5: resource "google_container_node_pool" "node_pools" {

Error: Required attribute is not set

on .terraform/main.tf line 5, in resource "google_container_node_pool" "node_pools":
5: resource "google_container_node_pool" "node_pools" {
```

**Comment by venkykuberan** [comment]
The error message you shared isn't adequate enough to understand the issue, I need to see your resource config to understand which required attribute is missing ?

**Comment by rileykarson** [comment]
Closing as this is an issue with the HCL, not the provider.
