### ISSUE TITLE
Deploying GCP Bucket With Multiple Storage Classes?

### ISSUE THREAD

**Issue by TitanRob16** [hashicorp/terraform-provider-google#7475]
According to the documentation (https://www.terraform.io/docs/providers/google/r/storage_bucket.html), the acceptable values for "storage_class" are: 
_STANDARD, MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE._

However, what if I want to deploy a GCP bucket that's REGIONAL and ARCHIVE?

I've tried:
_storage_class = "ARCHIVE, REGIONAL"_

And:
_storage_class = "ARCHIVE", "REGIONAL"_

Neither unfortunately work. For the first, I receive the message:

_"Argument definitions must be separated by newlines, not commas. An argument definition must end with a newline."_

For the second, I receive the message:

_"Invalid Value"_

Is it possible to define multiple storage classes for GCP buckets with Terraform?
To be clear: I can create a bucket via the GCP Console that has the Location Type set to "Region" and the Default Storage Class set to "Archive". I want to achieve this same behaviour with Terraform.

**Comment by venkykuberan** [comment]
You can use `location` (ex: location = "US") and `storage_class` as `ARCHIVE`.
