### ISSUE TITLE
Concurrent activation of dependent / independent APIs

### ISSUE THREAD

**Issue by antoinecastex** [hashicorp/terraform-provider-google#7493]
hashicorp/google-beta: version = "~> 3.42.0"

Step #1: Error: Request "Enable Project Service \"cloudfunctions.googleapis.com\" for project \"itg-iclosing-gbl-ww-np\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): cloudfunctions.googleapis.com and project itg-iclosing-gbl-ww-np., failedPrecondition
Step #1: Error: Request "Enable Project Service \"dataflow.googleapis.com\" for project \"itg-iclosing-gbl-ww-np\"" returned error: Batch request and retried single request "Enable Project Service \"dataflow.googleapis.com\" for project \"itg-iclosing-gbl-ww-np\"" both failed. Final error: Error waiting for Enable Project "itg-iclosing-gbl-ww-np" Services: [dataflow.googleapis.com]: Error code 3, message: [dataflow activation failed] with failed services [dataflow.googleapis.com]
Step #1: 
Step #1: 
Step #1: 
Step #1: Error: Request "Enable Project Service \"endpoints.googleapis.com\" for project \"itg-iclosing-gbl-ww-np\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): endpoints.googleapis.com and project itg-iclosing-gbl-ww-np., failedPrecondition

**Comment by antoinecastex** [comment]
related to that https://github.com/terraform-google-modules/terraform-google-project-factory/issues/461

**Comment by bharathkkb** [comment]
Also similar to: https://github.com/hashicorp/terraform-provider-google/issues/7103

**Comment by rileykarson** [comment]
Ah! Looks like this just barely didn't make it into the last release, sorry. This will be part of `3.45.0`. We cut the release branch a few days before the actual release gets made.
