### ISSUE TITLE
AccessContextManager Context Aware Access UserAccessBinding resource

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

> Restricts access to Cloud Console and Google Cloud APIs for a set of users using Context-Aware Access.

From https://cloud.google.com/access-context-manager/docs/reference/rest/v1alpha/organizations.gcpUserAccessBindings

This resource binds google_access_context_manager_access_level resources to groups of users under management.

### New or Affected Resource(s)

* google_access_context_manager_gcp_user_access_binding

(note: not IAM)

### Potential Terraform Configuration

```tf
# note: this resource has a server-generated id
resource "google_access_context_manager_gcp_user_access_binding" "context_aware" {
  group_key = "01d520gv4vjcrht"
  access_levels = [...]
}
```

### References

* b/170510683

**Comment by melinath** [comment]
It looks like the feature is only in the v1alpha API - is that accurate? If so, does the resource only go into the beta provider?

**Comment by rileykarson** [comment]
It's possible the cloud docs are behind the actual API available! Can you try hitting the GA endpoint with the path for this resource?

**Comment by melinath** [comment]
Turns out this is also going to be blocked by https://github.com/hashicorp/terraform-provider-google/issues/7752, since I need to test it with the other Access Policy tests (which are what that bug represents). 😂

**Comment by melinath** [comment]
This is no longer blocked! 🥳  https://github.com/GoogleCloudPlatform/magic-modules/pull/4226 will resolve it. However, there's a bug in that PR that I'm not sure how to resolve, and I won't be around to work on it next sprint. (See chat for discussion.)

**Comment by melinath** [comment]
Since chat is difficult to find things in again, I'll summarize here:

- `opRes` is not getting set correctly because the operation is coming back `done` right away
- Riley:
  > (as written now) the value that ultimately becomes opres needs to happen after the done check to handle operations that are not immediately done. I took a quick look at common_operation and can't see what's going wrong
  > Probably the most suspicious place to me is https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/common_operation.go#L139. Are we entering that if block? We should be, I think.
