### ISSUE TITLE
Add support for IAM authentication to google_sql_user

### ISSUE THREAD

**Issue by shanesavoie** [hashicorp/terraform-provider-google#7512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is a preview feature, but would love support for this in the future.

https://cloud.google.com/sql/docs/postgres/create-manage-iam-users?authuser=1#gcloud

It looks like there's a new flag --type=cloud_iam_user|cloud_iam_service_account used to specify between a normal user and IAM authenticated user.

### New or Affected Resource(s)

* google_sql_user

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_sql_user" "user" {
  ...
  type="cloud_iam_user"
}

```

### References

* #0000

**Comment by dabbertorres** [comment]
I'd be happy to take a crack at adding this feature (over in [magic-modules](https://github.com/GoogleCloudPlatform/magic-modules)?), unless of course someone is already working on it.

**Comment by rileykarson** [comment]
@dabbertorres: Nobody is that I'm aware! You could edit in Magic Modules (there's a handwritten file @ https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_sql_user.go) but sending a PR in this repo is fine. One of us will upstream it to MM.

**Comment by rileykarson** [comment]
Looks like the change downstream was missing a `Fixes:`. Closing.
