### ISSUE TITLE
compute_instance.html.markdown - Ignition Config

### ISSUE THREAD

**Issue by braderhart** [hashicorp/terraform-provider-google#7516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.4

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
  metadata = {
    user-data = file("config.ign")
  }
```

### Expected Behavior

The docs state, "Container-Optimized OS, `metadata.user-data` accepts an Ignition Config"

### Actual Behavior

Container-Optimized OS doesn't accept an Ignition Config, only cloud-init

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/google/r/compute_instance.html

**Comment by edwardmedia** [comment]
@braderhart the plugin does not have control over what you can provide. But it would be good to be accurate in the document. Where do you see **Container-Optimized OS doesn't accept an Ignition Config, only cloud-init**? Can you post the link over here?

**Comment by braderhart** [comment]
@edwardmedia I tested it myself and got an error in the cloud-init logs, and the basic Ignition Config to create a systemd unit didn't work. I guess I could spin up another compute instance to be more specific, but it may be better to test it yourself and confirm that it isn't working, or if you are able to get it to work then provide more specifics.

Additionally, none of Google's documentation provides any information indicating an Ignition Config will work and I've searched the source code used to build Container-Optimized OS from Google and didn't see anything relating to Ignition.

**Comment by edwardmedia** [comment]
@braderhart  can you post your debug log? I did research and did not find any doc that supports your statement. Again, the Terraform plugin does not control what to run in the metadata. To repro, can you provide the code for both scripts?

**Comment by braderhart** [comment]
@edwardmedia I understand that the Terraform plugin does not control what to run in the metadata. In this instance, I am referring to `metadata.user-data` which is based on the OS image being used and if it doesn't work, then it simply doesn't process the configuration and will provide the error in the instance logs but the instance will start fine so there is nothing to report to Terraform. The doc here states, "For Container-Optimized OS, `metadata.user-data` accepts an Ignition Config":

https://www.terraform.io/docs/providers/google/r/compute_instance.html

This is incorrect, because **Container-Optimized OS** is a distribution by Google based on Chromium OS:

https://cloud.google.com/container-optimized-os/docs

It is not the same as CoreOS or its replacements by Red Hat, which do support Ignition Configs. The problem is that the docs are incorrect in suggesting that **Container-Optimized OS** somehow accepts and can use an Ignition Config. If it said, "For **Fedora CoreOS** and **RHEL CoreOS**, `metadata.user-data accepts` an Ignition Config" then that would be accurate.

I think I've provided enough information at this point to help you understand the issue. If you somehow still disagree feel free to test it yourself. If I'm wrong, and you can provide some reference that **[Container-Optimized OS](https://cloud.google.com/container-optimized-os/docs
)** actually does accept Ignition Configs then I'll be happy to admit that I was wrong.
