### ISSUE TITLE
VM instance keeps on being update despite no change to configuration

### ISSUE THREAD

**Issue by ErikEngerd** [hashicorp/terraform-provider-google#7517]
When defining a VM instance using machine type "e2-custom-4-4096", the VM is updated every time terraform apply is run. The change that is indicated is

 `machine_type              = "e2-highcpu-4" -> "e2-custom-4-4096"`

So apparently, "e2-custom-4-4096" is mapped to "e2-highcpu-4" when the VM is created. 
`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/google v3.43.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf

resource "google_compute_instance" "bim-nlb19" { 
  name = "bim-nlb19"
  zone = "europe-west4-a"
  machine_type = "e2-custom-4-4096"
  deletion_protection = false
  allow_stopping_for_update = true

  tags = ["null"]

  boot_disk { 
    source = google_compute_disk.bim-nlb19-boot.name
  }

  network_interface {
    subnetwork = "production-nlb-lan" 
    network_ip = "10.0.0.119"
  } 
  
  metadata = { 
    startup-script-url = "gs://axx-production-vm-support/centos-7/bootstrap.sh"
  }
  
  service_account {
    email = data.google_service_account.vm.email
    scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ] 
  }
} 


resource "google_compute_disk" "bim-nlb19-boot" {
  name  = "bim-nlb19-boot"
  type  = "pd-standard"
  size  = 20
  image = "centos-7"
  zone = "europe-west4-a"
}

```

### Debug Output
[debug output](https://gist.github.com/ErikEngerd/eed76ac3acad631181070c8226082d0b)

### Expected Behavior

No change should be made to the VM.

### Actual Behavior

VM is modified

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Authentication as user.

### References

-

**Comment by venkykuberan** [comment]
Looks like an API bug, I tried with `e2-custom-8-4096` and didn't see that behavior.
However to mitigate this issue for the given machine_type `e2-custom-4-4096`, you can add the following in your config
``` 
lifecycle {
      ignore_changes = ["machine_type"]
  }
```
