### ISSUE TITLE
Document google_project_service_identity can be used for Cloud Build

### ISSUE THREAD

**Issue by iddan** [hashicorp/terraform-provider-google#7522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Similarly to `google_compute_default_service_account` I think there should be `google_cloudbuild_default_service_account` to retrieve the default service account of Cloud Build. It is documented here: https://cloud.google.com/cloud-build/docs/cloud-build-service-account#:~:text=By%20default%2C%20Cloud%20Build%20service,service%20account%20has%20by%20default. 

Currently, I implemented a module locally to not repeat the code:
```tf
variable "project" {
  type = string
}

data "google_project" "project" {
  project_id = var.project
}

output "email" {
  value = "${data.google_project.project.number}@cloudbuild.gserviceaccount.com"
}
```

### New or Affected Resource(s)

* google_cloudbuild_default_service_account

### Potential Terraform Configuration

```tf
data "google_cloudbuild_default_service_account" "default" {
}

resource "google_project_iam_member" "cloud_build" {
  role   = "roles/editor"
  member = "serviceAccount:${data.google_cloudbuild_default_service_account.email}"
}
```

**Comment by rileykarson** [comment]
This is possibly possible through https://www.terraform.io/docs/providers/google/r/project_service_identity.html, depending how the API exposes the account.

**Comment by iddan** [comment]
Thank you! How should users be aware this is the correct way to receive the Cloud Build default service account?

**Comment by rileykarson** [comment]
Good question! I think we could consider adding an infobox on the page of resources with default service accounts that points to `google_project_service_identity`.

---

As a sidebar I just confirmed this works, with the config below (I posted a guess one of my teammates had during a triage meeting before):

```
resource "google_project_service_identity" "build_account" {
  provider = google-beta
  service = "cloudbuild.googleapis.com"
}

output "email" {
  value = google_project_service_identity.build_account.email
}
```

**Comment by iddan** [comment]
Awesome. Thank you!

**Comment by rileykarson** [comment]
Reopening- I think we want this to appear on the original resource page too, not just the service identity resource. This is about improving the discoverability of `google_project_service_identity`.

**Comment by rileykarson** [comment]
Re-opening, I was too fast for the robot.

**Comment by upodroid** [comment]
Any specific page @rileykarson?

**Comment by rileykarson** [comment]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger for this issue
