### ISSUE TITLE
[Action Advised] Migrate from Classic VPN to High Availability VPN by October 2021

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7528]
I save the body of the email to the team google group. (some) Important bits:

> What do I need to know?
> After October 2021, you will no longer be able to create new tunnels using the following deprecated Classic VPN configurations, and existing tunnels with these configurations will not be supported. However, the tunnels that you have currently installed and are using will continue to work as expected.
> 
> All Classic VPN tunnels that use dynamic routing (Cloud Router), regardless of the gateway to which the tunnel connects
> Classic VPN tunnels that connect two GCP Classic VPN gateways to one another, regardless of routing method they use
> Classic VPN tunnels that use static routing to connect one GCP Classic VPN gateway to another cloud provider's network
> Note: After October 2021, if you delete a tunnel configuration listed above, you won’t be able to recreate it. However, you’ll still be able to route traffic through your existing Classic VPN tunnels, unless you make changes to them that require you to switch to HA VPN.
> 
> You can continue to create the following Classic VPN configurations and get support for them after October 2021:
> 
> Classic VPN tunnels using static routing from Classic VPN gateways to on-premises VPN gateways and from on-premises VPN gateways to Classic VPN gateways
> Classic VPN tunnels using static routing from a Classic VPN gateway to and from a Compute Engine virtual machine (VM) acting as a VPN gateway

We should determine if there's impact on Terraform and make changes if appropriate.

**Comment by upodroid** [comment]
Part 1: Mark HA VPN Gateway GA. https://github.com/hashicorp/terraform-provider-google/issues/7534 PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/4115
Part 2: Added a deprecation note in the `google_compute_vpn_gateway` docs. Part of 4115

**Comment by rileykarson** [comment]
Hmm- the last part suggests we don't want to deprecate the original `google_compute_vpn_gateway ` resource, just modify it:


> You can continue to create the following Classic VPN configurations and get support for them after October 2021:
> 
> Classic VPN tunnels using static routing from Classic VPN gateways to on-premises VPN gateways and from on-premises VPN gateways to Classic VPN gateways
> Classic VPN tunnels using static routing from a Classic VPN gateway to and from a Compute Engine virtual machine (VM) acting as a VPN gateway

**Comment by upodroid** [comment]
Yeah, it is tricky to deprecate fields in schema.

**Comment by upodroid** [comment]
@melinath https://github.com/hashicorp/terraform-provider-google/issues/11322 is being tracked on this issue.

**Comment by rileykarson** [comment]
We've migrated test environments and this hasn't caused issues for us- we should be fine.
