### ISSUE TITLE
Promote HA VPN Gateway to GA

### ISSUE THREAD

**Issue by jtymes** [hashicorp/terraform-provider-google#7534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google recently announced a [partial deprecation of Classic VPN](https://cloud.google.com/network-connectivity/docs/vpn/release-notes#October_14_2020). We went to look at switching to the HA VPN option, which has been GA since [September 2019](https://cloud.google.com/network-connectivity/docs/vpn/release-notes#September_27_2019) and the [resource](https://github.com/GoogleCloudPlatform/magic-modules/blob/bd023cbd32cf957a8b97cf809b859ffaefa8a327/products/compute/api.yaml#L14665) is still marked as Beta. The [API](https://cloud.google.com/compute/docs/reference/rest/v1/vpnGateways) makes no mention of it still being in Beta. 

### New or Affected Resource(s)

* google_compute_ha_vpn_gateway

### Potential Terraform Configuration

NA - As far as I can tell the resources are equivalent, this is just promoting to GA. 

### References

* #3625

**Comment by rileykarson** [comment]
Related: https://github.com/hashicorp/terraform-provider-google/issues/7528, for our team to enact everything required by the partial deprecation.

@upodroid has sent out https://github.com/GoogleCloudPlatform/magic-modules/pull/4115 which marks this as GA.

**Comment by jtymes** [comment]
I think `google_compute_external_vpn_gateway` probably could get added to this promotion as well.
