### ISSUE TITLE
Essential Contacts

### ISSUE THREAD

**Issue by jenshonkan84** [hashicorp/terraform-provider-google#7549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for Essential Contacts.

### New or Affected Resource(s)

* google_essential_contacts

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References
https://cloud.google.com/resource-manager/docs/reference/essentialcontacts/rest

* #0000

**Comment by jenshonkan84** [comment]
Any progress on this topic?

/BR Jens

**Comment by sffortytwo** [comment]
The link under References is broken. Perhaps it should be https://cloud.google.com/resource-manager/docs/reference/essentialcontacts/rest?

**Comment by jenshonkan84** [comment]
Googe must have changed it. Now it is updated.

**Comment by sffortytwo** [comment]
Hi. I'd like to be involved in the development of this feature if possible. Who can I contact?
