### ISSUE TITLE
google_iam_policy documentation

### ISSUE THREAD

**Issue by Rob-S** [hashicorp/terraform-provider-google#7564]
(I was unable to comment on Issue #481 or #820.)

The [google_iam_policy page](https://www.terraform.io/docs/providers/google/d/iam_policy.html) says:

_This data source is used to define IAM policies to apply to other resources. Currently, defining a policy through a datasource and referencing that policy from another resource is the **only** way to apply an IAM policy to a resource._

Aren't the google_project_iam_binding, google_project_iam_member, google_storage_bucket_iam_binding and google_storage_bucket_iam_member resources also a way to apply an IAM policy to those resources?

**Comment by edwardmedia** [comment]
@Rob-S There are two things you may want to notice
1. What gcp resources:  google_*project*_iam_binding and google_*project*_iam_member are policies on *project* and google_*storage*_bucket_iam_binding, google_*storage*_bucket_iam_member are for *storage*. 
2) What policies: *_binding*, *_member* and *_policy* are for different usages. Please note all existing policies will be *deleted*  if you use *_policy*. Let me know if this make sense to you

**Comment by edwardmedia** [comment]
@Rob-S is this still a question for you?

**Comment by Rob-S** [comment]
It makes sense to me, and tends to confirm what I was explaining. The resources I mentioned apply to the higher level resources mentioned in their names, and being resources, can affect the IAM policies in the GCP resources. So the statement indicating that the data source is the only way to do that appears to be incorrect.

**Comment by edwardmedia** [comment]
@Rob-S I am closing this question now. Feel free to reopen it if you still have questions about it. Thank you
