### ISSUE TITLE
Fix bug with empty `initialize_params` block #664

### ISSUE THREAD

**Issue by aamarques** [hashicorp/terraform-provider-google#7565]
Hey..
I'm using terraformer with Google Provider. I've imported all the resources I want, including compute instances.
For test purposes, I have deleted on instance from GCP console and did :

```
$ terraform init
$ terraform refresh
$ terraform apply

```
.. and got this error

```
google_compute_instance.tfer--instance-002D-2: Creating...

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0]': '{ "mode": "READ_WRITE", "source": "projects/ccmn-devadm/zones/europe-west2-b/disks/instance-2", "...'. Cannot specify both 'source' and 'initializeParams'., invalid

```
if I open the file and comment on the source line, terraform runs successfully..

```
Terraform v0.12.29 (is outdated but that's the supporter version for terraformer)

provider.google v3.43.0
$ terraformer -v
version v0.8.8
```

**compute_instance.tf:**

```
resource "google_compute_instance" "tfer--instance-002D-2" {
  boot_disk {
    auto_delete = "true"
    device_name = "instance-2"

    initialize_params {
      image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-10-buster-v20201014"
      size  = "10"
      type  = "pd-standard"
    }

    mode   = "READ_WRITE"
    source = "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west2-b/disks/instance-2"
  }
```
....
**terraform plan:**

      + boot_disk {
          + auto_delete                = true
          + device_name                = "instance-2"
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west2-b/disks/instance-2"

          + initialize_params {
              + image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-10-buster-v20201014"
              + labels = (known after apply)
              + size   = 10
              + type   = "pd-standard"
            }
        }

**terraform apply :**

`Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0]': '{  "mode": "READ_WRITE",  "source": "projects/myproject/zones/europe-west2-b/disks/instance-2",  "...'. Cannot specify both 'source' and 'initializeParams'., invalid`

I've read the issue "Fix bug with empty `initialize_params` block #664" and saw that some thing was done on 2017, but I think that's is different right now.

Regards,

**Comment by venkykuberan** [comment]
Its working as expected, basically `initialize_params` is used if a new disk needs to created along with compute instance. `source` is used if i want to use an existing disk.

Provider doc: 
 initialize_params - (Optional) Parameters for a new disk that will be created alongside the new instance. Either initialize_params or source must be set.  more info here - https://www.terraform.io/docs/providers/google/r/compute_instance.html#source
