### ISSUE TITLE
google_compute_instance docs missing details on creating e2 and n2 custom instance types

### ISSUE THREAD

**Issue by jvkessel** [hashicorp/terraform-provider-google#7571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There used to only be one custom instance machine type in GCP based on the n1 machine type.   All custom instance types were created by specifying the number of cores and amount of memory in the format "custom-<cores><memory in MB>[-ext]".   Now additional Machine Types like e2 and n2 are available and can be created as custom machine types, but the terraform documentation does not describe how to do it.    The format is the following: 
"[<machine type>-]custom-<cores><memory in MB>[-ext]"
where <machine-type>, if included can be one of e2, n2 or n2d.  If the machine type is excluded, then the machine type is an n1 custom machine type.    Note that the Google Provider already supports these machine types as it simply passes them through to the Google API which supports this format.   See the [Google Cloud documentation for creating a custom machine type using the API](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#create)

The recommended change is to provide examples of other machine types that can be created in the documentation of the google_compute_instance resource and any other place where the Custom Instance format is referenced (such as compute_instance_template)

### New or Affected Resource(s)

[compute_instance.html.markdown](https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/compute_instance.html.markdown)
[compute_instance_template.html.markdown](https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/compute_instance_template.html.markdown)
[container_cluster.html.markdown](https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/container_cluster.html.markdown)

and there may be others

### Potential Terraform Configuration

```tf
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "e2-custom-5-4096"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = "default"

    access_config {
      // Ephemeral IP
    }
  }
}
```

### References

https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#create

* #0000

**Comment by edwardmedia** [comment]
There is a [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/4113) that has already updated the `machine_type`. Will be showed up in v3.45.0
