### ISSUE TITLE
Please expand supported locations for google_logging_*_bucket_config

### ISSUE THREAD

**Issue by ioreilly** [hashicorp/terraform-provider-google#7574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the provider allows you to provision a project or organization logging bucket in any location, but configuration is limited to `global` or `us-central1` buckets (see [here](https://www.terraform.io/docs/providers/google/r/logging_project_bucket_config.html#location)). 

In my case, all the infrastructure for my organization is in `us-west1` and it'd be nice to not have to hack around that for consistency.

### New or Affected Resource(s)

* google_logging_project_bucket_config
* google_logging_organization_bucket_config

**Comment by upodroid** [comment]
Hello

You can specify any location in the field. Terraform is not doing any field validation on it. 

https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_logging_bucket_config.go

Can you leave the issue open? We'll update the docs to remove global and us-central1
