### ISSUE TITLE
Terraform out-of-memory with large config

### ISSUE THREAD

**Issue by cah-ken-flannery** [hashicorp/terraform-provider-google#7581]
We have started to experience issues w/our terraform pipelines using too much memory when refreshing the state for large datasets. Our security architecture mandates all access to core datasets go thru authorized views. We have a particularly large dataset with nearly 630 tables resulting in 630 authorized views that need to be created/maintained by terraform. Processing this large of a dataset exhausts available memory on the worker node (16gb); increasing available memory to at least 30gb is necessary to successfully handle the dataset. However, this is not a sustainable solution for couple of reasons. First, we have even larger datasets that we will need to process in the future, some can easily exceed 2000 tables. Second, it appears that we are hitting quota limits documented here whenever these larger datasets are created/updated. In order to workaround this we have had to decrease terraform parallelism down to about 2. This corrects the quota errors (or at least makes them less frequent). However, by limiting parallelism our pipeline takes forever to complete -- taking nearly an hour or more just to process this dataset.
https://cloud.google.com/bigquery/quotas?hl=FA#dataset_limits

n.b. - when testing/troubleshooting this, it appears that the size of the structure of individual tables may also play a part in the memory usage. We can have some tables with hundreds of columns (up to 1000 in a few cases). Perhaps this is a side-effect of the authorized view query which is a source identical query against the original base table. In any case, the # of tables is not necessarily fixed but it seems the resulting size of the terraform state file perhaps is too large to process.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.25

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Unfortunately I'm not sure that this is specific to the Google provider, or something we can do anything about. I'd suggest [filing an issue against `hashicorp/terraform`](https://github.com/hashicorp/terraform/issues/new/choose) and giving them feedback on your experience. 

We have a handful of resources that get particularly large, as you've identified, and it's possible we could attempt do _some_ reduction of memory usage but I'm not sure how much of that falls on us vs the Go garbage collector. I'd be interested in the response from Terraform Core as to whether they've seen similar issues before, and how they measured memory usage in the provider + corrected it (assuming they have).

Honestly, the best solution in this case is likely to split your config up into smaller pieces if that's possible for you.
