### ISSUE TITLE
Default Compute Health Check Port is null, should be `443`

### ISSUE THREAD

**Issue by dv-tyler** [hashicorp/terraform-provider-google#7586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Provider Version

* google      = "~> 3"

### Affected Resource(s)

* google_compute_health_check

### Terraform Configuration Files

```tf
resource "google_compute_health_check" "health" {
  check_interval_sec  = 5
  healthy_threshold   = 2
  timeout_sec         = 5
  unhealthy_threshold = 5

  https_health_check {
    request_path = "/-/health"
  }
}
```

### Debug Output

Debug output is massive and has private info, the issue happens to be obvious from the plan output, included here:
```tf
# google_compute_health_check.health will be updated in-place
~ resource "google_compute_health_check" "health" {
      check_interval_sec  = 5
      healthy_threshold   = 2
      timeout_sec         = 5
      type                = "HTTPS"
      unhealthy_threshold = 5
   ~ https_health_check {
        - port         = 443 -> null
          proxy_header = "NONE"
          request_path = "/-/health"
       }
  }
```

### Expected Behavior

There should be no resource change, as the code has not changed. The TF state value for the health_check port should be `443`, not `null` by default.

### Actual Behavior

While `port` in `https_health_check` is optional, the provider appears to set this state to null, while the API sets the value to `443`. If the port is not explicitly set, the resource shows a modification on every plan or apply.

### Steps to Reproduce

1. Create a health check with an `https_health_check` config block
1. Do not set the `port`
1. `terraform apply`
1. Observe that `terraform plan` indicates a resource modification is needed without any code change

**Comment by venkykuberan** [comment]
@dv-tyler actually Provider sends the default port value as 443 in API request (when config doesn't have port value) and updates the state with port value 443 as expected.  However TF plan finds the difference between your config & state and shows the in-place update.  To circumvent we have `diff supress func` for port but looks like its not working as expected. We will look into it.
