### ISSUE TITLE
google_logging_project_sink supports destination log bucket

### ISSUE THREAD

**Issue by omelnyk1** [hashicorp/terraform-provider-google#7590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
It seems there are only 3 possible destinations for terraform resource google_logging_project_sin:
* storage bucket
* pubsub topic
* bigquery dataset

https://www.terraform.io/docs/providers/google/r/logging_project_sink.html#destination
In fact, we can configure other 3 destinations. Please find GCP console screenshot below:
![image](https://user-images.githubusercontent.com/25325816/96707901-bf472680-1398-11eb-9997-942df62a7b6e.png)
It would be nice to support destination cloud loggin bucket.

### New or Affected Resource(s)

* google_logging_project_sink

### Potential Terraform Configuration

`example` sink will look up logs by `filter` and send it to logging bucket `dbalogs` (resource id `logging.googleapis.com/projects/my-project/locations/global/buckets/dbalogs`) in GCP project `my-project`:
```tf
resource "google_logging_project_sink" "this" {
  name                   = "example"
  destination            = "logging.googleapis.com/projects/my-project/locations/global/buckets/dbalogs"
  filter                 = "logName=projects/my-project/logs/cloudsql.googleapis.com%2Fpostgres.log"
}

```

### References

https://cloud.google.com/logging/docs/export#sink-terms
https://www.terraform.io/docs/providers/google/r/logging_project_sink.html#destination
* #0000

**Comment by c2thorn** [comment]
The `destination` field supports any destination that the user provides. We don't do any validation against the field, so you should be able to provide log buckets as destinations currently. 

We meant to update our documentation, but it looks like that fell through. @venkykuberan, can we update the docs stating that log bucket destinations are possible, and also add text stating that the user can set any destination they want?

**Comment by c2thorn** [comment]
To clarify, the API expects the destination bucket to be in this form: `logging.googleapis.com/projects{project}/locations/{location}/buckets/{bucket}`.

Looks like we should also support passing in a bucket `id` to the destination field by prepending "logging.googleapis.com/" to the id `projects{project}/locations/{location}/buckets/{bucket}`
