### ISSUE TITLE
Support Cloud Firestore single field indexes

### ISSUE THREAD

**Issue by pdecat** [hashicorp/terraform-provider-google#7593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_firestore_index` is currently only supporting composite indexes, not single field indexes. This limitation is properly documented https://www.terraform.io/docs/providers/google/r/firestore_index.html

Trying to define a single field index is rejected at plan time:

```
Error: List shorter than MinItems

  on firestore.tf line 13, in resource "google_firestore_index" "my-index":
  13: resource "google_firestore_index" "my-index" {

Attribute supports 2 item minimum, config has 1 declared
```

The same Google Cloud API that is already used for composite indexes also supports single fields indexes:

> `fields[]` : `object (IndexField)`
> The fields supported by this index.
> For composite indexes, this is always 2 or more fields. The last field entry is always for the field path `__name__`. If, on creation, `__name__`  was not specified as the last field, it will be added automatically  with the same direction as that of the last field defined. If the final  field in a composite index is not directional, the `__name__` will be ordered `ASCENDING` (unless explicitly specified).
> *For  single field indexes, this will always be exactly one entry with a  field path equal to the field path of the associated field.*

See https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.collectionGroups.indexes

### New or Affected Resource(s)

* `google_firestore_index`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_firestore_index" "my-index" {
  project = "my-project-name"

  collection = "chatrooms"

  fields {
    field_path = "name"
    order      = "ASCENDING"
  }
```

### References

* b/275099900

**Comment by ssp** [comment]
any news about this? it would be super useful!

**Comment by ScottSuarez** [comment]
The api doesn't support single field index.

If you hit the underlying api with such a request you should see an error.
```log
Error: Error creating Index: googleapi: Error 400: this index is not necessary, configure using single field index controls

  on main.tf line 1, in resource "google_firestore_index" "my-index":
   1: resource "google_firestore_index" "my-index" {
```
