### ISSUE TITLE
Generate memorystore redis instance auth string via TF 

### ISSUE THREAD

**Issue by nitishkrishna** [hashicorp/terraform-provider-google#7601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We can now create memorystore redis instances with auth enabled via the [TF provider](https://github.com/GoogleCloudPlatform/magic-modules/pull/4079).
However, we still have to manually run a gcloud command to get the auth string that is used to connect to this instance:
https://cloud.google.com/memorystore/docs/redis/managing-auth#getting_the_auth_string

If we get this auth_string as an output/data source of the instance resource, we can consume that without manual commands needed.

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
data "google_redis_instance" "default" {
  name = "my-redis-instance"
}

data.google_redis_instance.default.auth_string
```

### References

Auth enabled issue: https://github.com/hashicorp/terraform-provider-google/issues/7459
Fixed in: https://github.com/GoogleCloudPlatform/magic-modules/pull/4079

* b/175902105

**Comment by sethvargo** [comment]
We also need this in the Exposure Notifications project.
