### ISSUE TITLE
pub sub subscription: attributes in terraform.tfstate is empty

### ISSUE THREAD

**Issue by pratik141** [hashicorp/terraform-provider-google#7606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.24
Terraform v0.13.5

### Affected Resource(s)

* google v3.44.0

### Debug Output
![bug](https://user-images.githubusercontent.com/13189088/96834201-39da7980-145f-11eb-8264-034f21abf44b.JPG)
![bug2](https://user-images.githubusercontent.com/13189088/96835349-19abba00-1461-11eb-930a-55a5a8178f31.JPG)

In gcloud output its there:
```pushConfig:
  attributes:
    x-goog-version: v1
  pushEndpoint: https://asd.com
```

### Expected Behavior

Running again tf should not give change diff again.

### Actual Behavior

After creating a pub-sub subscription with push configuration using terraform and applying the terraform again it's showing an update in the attributes section adding `x-goog-version`.  when checked in tfstate file its showing empty

### Steps to Reproduce
1. create a   pub-sub subscription with tf 
2. run `terraform apply` again

**Comment by edwardmedia** [comment]
@pratik141 Can you share your Terraform config code and debug log?

**Comment by pratik141** [comment]
```
resource "google_pubsub_subscription" "subscription" {

  count                      = var.create_subscription ? 1 : 0
  project                    = var.project_id
  name                       = var.subscription_name
  topic                      = var.topic
  ack_deadline_seconds       = var.ack_deadline_seconds
  filter                     = var.filter
  retain_acked_messages      = var.retain_acked_messages
  enable_message_ordering    = var.enable_message_ordering
  message_retention_duration = var.message_retention_duration

  dynamic "expiration_policy" {
    for_each = var.expiration_policy
    content {
      ttl = lookup(expiration_policy.value, "ttl")
    }
  }

  dynamic "dead_letter_policy" {
    for_each = var.dead_letter_policy
    content {
      dead_letter_topic     = lookup(dead_letter_policy.value, "dead_letter_topic")
      max_delivery_attempts = lookup(dead_letter_policy.value, "max_delivery_attempts")
    }
  }

  dynamic "push_config" {
    for_each = var.push_config
    content {
      push_endpoint = lookup(push_config.value, "push_endpoint")

      attributes = {
        x-goog-version = lookup(push_config.value, "attributes_version", "v1")
      }

      oidc_token {
        service_account_email = lookup(push_config.value, "service_account_email", "")
        audience              = lookup(push_config.value, "audience", "")
      }
    }
  }

  dynamic "retry_policy" {
    for_each = var.retry_policy
    content {
      minimum_backoff = lookup(retry_policy.value, "minimum_backoff")
      maximum_backoff = lookup(retry_policy.value, "maximum_backoff")
    }
  }

  labels = var.subscription_labels
}```

**Comment by pratik141** [comment]
[pubsub.zip](https://github.com/hashicorp/terraform-provider-google/files/5428238/pubsub.zip)
even default config having same issue [example-usage-pubsub-subscription-push](https://www.terraform.io/docs/providers/google/r/pubsub_subscription.html#example-usage-pubsub-subscription-push)

**Comment by ndmckinley** [comment]
I believe this to be an issue with the `dynamic` feature of Terraform, rather than an issue with our provider - I can't reproduce it with the example you point to.  I think it's fairly likely your config is producing an empty string for "x-goog-version" when it's evaluated for state saving - that is the default and it is returned inconsistently from the API, so the behavior you're seeing reflects what I'd expect if you were not setting that value at all.

**Comment by ndmckinley** [comment]
Ah, our unit tests exclude this resource specifically to avoid detecting this permadiff constantly.  I believe I can fix this with a sufficiently complex diffsuppress.
