### ISSUE TITLE
Service is not created with google_project_service

### ISSUE THREAD

**Issue by Sardonic-1** [hashicorp/terraform-provider-google#7608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/google v3.44.0
+ provider registry.terraform.io/hashicorp/google-beta v3.44.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/random v3.0.0
```
### Affected Resource(s)

* google_project_service
* google_service_networking_connection (possible)

### Terraform Configuration Files

```tf
resource "google_project_service" "networking_service" {
  project = var.project_id
  service = "servicenetworking.googleapis.com"

  lifecycle {
    prevent_destroy = true
  }
}

resource "google_service_networking_connection" "caas_service_networking_connection" {
  provider = google-beta
  network                              = google_compute_network.caas_vpc.id 
  service                               = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_alloc.name]
}

```

### Debug Output
[Debug output ](https://gist.github.com/Sardonic-1/8bc6904c9aa4885db930f23cb158ecfe)
### Expected Behavior

servicenetworking.googleapis.com should be enabled

### Actual Behavior

The following is thrown
``` Error: service servicenetworking.googleapis.com not in enabled services for project claroty-as-a-service-lab ```
### Steps to Reproduce

1. Add the configuration for the service as stated above
2. Run terraform plan/refresh/apply

**Comment by edwardmedia** [comment]
@Sardonic-1 it needs a little extra time to have the service enabled before it becomes available for other resources that depend on it. To workaround it, you may need to add `delay` logic before the resource. Here is an [example](https://github.com/hashicorp/terraform-provider-google/issues/6377#issuecomment-628978514) that might want to take a look. If that works for you, please go ahead to close the issue.

**Comment by Sardonic-1** [comment]
@edwardmedia Sadly it doesn't help, the service doesn't get enabled even if I wait and try to re-apply

**Comment by edwardmedia** [comment]
@Sardonic-1 can you post the config that includes the suggested workaround and the debug log?

**Comment by edwardmedia** [comment]
@Sardonic-1 is this still an issue?

**Comment by Sardonic-1** [comment]
@edwardmedia sorry for the delayed response - for the time being I've enabled the service manually, I can't modify our environments too much to test right now.

**Comment by edwardmedia** [comment]
@Sardonic-1  Let's close this issue now. Feel free to reopen it once you can repro the issue. Thanks
