### ISSUE TITLE
google_access_context_manager_service_perimeter_resource inconsistent result after apply

### ISSUE THREAD

**Issue by fallard84** [hashicorp/terraform-provider-google#7610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26
+ provider.google v3.41.0
+ provider.google-beta v3.41.0

### Affected Resource(s)

* google_access_context_manager_service_perimeter_resource

### Terraform Configuration Files

service_perimeter.tf
```tf
provider "google" {
  version               = "3.41"
  user_project_override = true
  billing_project       = "<MASKED>"
}
resource "google_access_context_manager_service_perimeter" "service-perimeter" {
  parent = "accessPolicies/${var.org_access_policy}"
  name   = "accessPolicies/${var.org_access_policy}/servicePerimeters/test-policy"
  title  = "test-policy"

  status {
    restricted_services = var.restricted_services
  }

  lifecycle {
    # Allow projects to be added separately from this module
    ignore_changes = [status[0].resources]
  }
}
```

resources.tf
```tf
resource "google_access_context_manager_service_perimeter_resource" "service-perimeter-resource1" {
  perimeter_name = var.vpc_service_perimeter
  resource       = "projects/<PROJECT_NUMBER_1>"
}
resource "google_access_context_manager_service_perimeter_resource" "service-perimeter-resource2" {
  perimeter_name = var.vpc_service_perimeter
  resource       = "projects/<PROJECT_NUMBER_2>"
}
resource "google_access_context_manager_service_perimeter_resource" "service-perimeter-resource3" {
  perimeter_name = var.vpc_service_perimeter
  resource       = "projects/<PROJECT_NUMBER_3>"
}
```

The real configuration files have been simplified to show what we are trying to achieve. In reality, each `google_access_context_manager_service_perimeter_resource` is part of a module that is instantiated for many projects that must be add to the service perimeter.

### Expected Behavior

The 3 projects should be added to the service perimeter.

### Actual Behavior

An error is thrown by the provider:
```
Error: Provider produced inconsistent result after apply

When applying changes to
google_access_context_manager_service_perimeter_resource.service-perimeter-resource2,
provider "registry.terraform.io/-/google" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
All `google_access_context_manager_service_perimeter_resource` seems to be created in parallel, which seems to be causing some inconsistency since a PATCH request is sent for each of them and they each try to override the same fields. Inconsistent results happen. The only way to get the resources to be created would be to target apply each resources one after the other (not really convenient). Note that this is my interpretation of what is happening and I may be wrong.

**Comment by edwardmedia** [comment]
@fallard84 can you post the debug log?

**Comment by fallard84** [comment]
Yes, I will share them early next week since I got rid of the logs I had. So I need to get them again and will need to do some clean up to remove any sensitive data.

**Comment by fallard84** [comment]
See the debug logs. I have only kept the part of the logs that apply the changes. It tries to apply 3 resources in parallel.
https://gist.github.com/fallard84/32db2360f59c066958d36c4866421a97
I have masked the project IDs but I kept the first and last 3 digits so you can better analyze them.

**Comment by ndmckinley** [comment]
Hey - sorry for the long silence, I'm doing a cleanup, but I think this has been fixed by mutexes that have been added since this has been filed.  Closing.  Please comment / reopen / open a new bug if not!
