### ISSUE TITLE
Service account service-<project_number>@gs-project-accounts.iam.gserviceaccount.com does not exist

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/terraform-provider-google#7611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.13.5

### Affected Resource(s)

* google_kms_crypto_key_iam_member

### Terraform Configuration Files

```tf
resource "google_kms_crypto_key_iam_member" "cis_gcp_2_2" {
  crypto_key_id = google_kms_crypto_key.cis_gcp_2_2.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${google_project.this.number}@gs-project-accounts.iam.gserviceaccount.com"

  depends_on = [
    google_project_service.this,
  ]

}
```

### Expected Behavior
After enabling the storage API I'd expect the service account would be usable.

### Actual Behavior
For some reason, I need to hit the API before that service account becomes available for use: https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount/get

**Comment by edwardmedia** [comment]
@brettcurtis can you take a look at this [issue](https://github.com/hashicorp/terraform-provider-google/issues/7608) to see if the suggested workaround help solve your problem?

**Comment by brettcurtis** [comment]
@edwardmedia - no, in my use case it doesn't actually become available even after waiting.  I'm not creating any buckets in my code until after the above resource is successfully created. I suspect if I did all would be fine.

**Comment by edwardmedia** [comment]
@brettcurtis can you post you debug log?

**Comment by brettcurtis** [comment]
Here is the gist: https://gist.github.com/brettcurtis/b73307368c37a502ca62daacf24d3585

**Comment by edwardmedia** [comment]
@brettcurtis below service account should be created once you enable the Storage service. The error seems clear. Can you explain how you enabled the API? If it is managed by Terraform, you can check its state. If not, you can import it and verify the service is enabled properly. (how are you sure **After enabling the storage API**?)  At this moment, I don't think your above code has issues. 

```
Service account service-438958811041@gs-project-accounts.iam.gserviceaccount.com does not exist.
```

**Comment by edwardmedia** [comment]
@brettcurtis  do you see that service available on the GCP Console?

**Comment by brettcurtis** [comment]
So I enable the api in the explicit dependency the resource uses:

main.tf
```hcl
resource "google_project_service" "this" {
  count = length(var.services)

  project = google_project.this.project_id
  service = element(var.services, count.index)

  disable_on_destroy = false
}
```

variables.tf
```hcl
variable "services" {
  description = "The service to enable"
  type        = list(string)

  default = [
    "cloudkms.googleapis.com",
    "storage.googleapis.com",
  ]
}
```

I can see the service yes:
```none
gcloud services list
NAME                     TITLE
cloudkms.googleapis.com  Cloud Key Management Service (KMS) API
compute.googleapis.com   Compute Engine API
oslogin.googleapis.com   Cloud OS Login API
storage.googleapis.com   Cloud Storage API
```

Yes, I can see it in the UI as well. 

The crazy thing is once I hit the API once for example go here: https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount/get 
add my project and get the response I can re-run my terraform and everything is fine.

**Comment by brettcurtis** [comment]
Thanks for the help, I've definitely waited for a long time before re-running terraform so it's not that. Let me whip up a simple test case tomorrow and share that with you.

**Comment by brettcurtis** [comment]
Use this main.tf:

```hcl
# Project Resource
# https://www.terraform.io/docs/providers/google/r/google_project.html

resource "google_project" "this" {
  name       = "some-project-name-99345"
  project_id = "some-project-name-99345"
  billing_account     = "XXXX-XXXX-XXXXX-XXXXX"
  folder_id           = "111222333444"
  auto_create_network = false
}

# Project Service Resource
# https://www.terraform.io/docs/providers/google/r/google_project_service.html

resource "google_project_service" "this" {
  project = google_project.this.project_id
  service = "storage.googleapis.com"

  disable_on_destroy = false
}

# KeyRing Resource
# https://www.terraform.io/docs/providers/google/r/kms_key_ring.html

resource "google_kms_key_ring" "this" {
  name     = "default-keyring"
  project  = google_project.this.project_id
  location = "us-east4"

  depends_on = [
    google_project_service.this,
  ]
}

# KMS CryptoKey Resource
# https://www.terraform.io/docs/providers/google/r/kms_crypto_key.html

resource "google_kms_crypto_key" "cis_gcp_2_2" {
  name            = "cis-gcp-2-2-key-logging-sink"
  key_ring        = google_kms_key_ring.this.id
  rotation_period = "100000s"
}
# KMS Crypto Key IAM Policy Resource
# https://www.terraform.io/docs/providers/google/r/google_kms_crypto_key_iam.html

resource "google_kms_crypto_key_iam_member" "cis_gcp_2_2" {
  crypto_key_id = google_kms_crypto_key.cis_gcp_2_2.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${google_project.this.number}@gs-project-accounts.iam.gserviceaccount.com"

  depends_on = [
    google_project_service.this,
  ]
}
```
Validate service is enabled:
```
gcloud config set project some-project-name-9934
gcloud services list
NAME                    TITLE
compute.googleapis.com  Compute Engine API
oslogin.googleapis.com  Cloud OS Login API
storage.googleapis.com  Cloud Storage API
```
Re run terraform apply, you should still see the same issue. Wait as long as you want. Next you can hit the API like I mentioned above, then re-run apply.

**Comment by edwardmedia** [comment]
@brettcurtis can you try adding below **delay** logic in your code? You may reference the [example](https://github.com/hashicorp/terraform-provider-google/issues/6377#issuecomment-628978514) here.

```tf
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }
  triggers = {
    "project" = "${google_project.project.id}"
  }
}
```

**Comment by brettcurtis** [comment]
I can but again, I can wait for hours and hours and it still doesn't allow me to use the service account.

**Comment by brettcurtis** [comment]
I just made an edit to the main.tf above to included a missing service and added the sleep as requested. Anyway, if you run that you'll see the problem I'm trying to describe.

**Comment by edwardmedia** [comment]
@brettcurtis I noticed your above code has `null_resource`. Did you have *depends_on* in each resource? 
```tf
resource "google_service_account" "foo" {
  account_id   = "example"
  display_name = "example"
  project      = google_project.project.project_id
  depends_on = [null_resource.delay]   <----????
}
```

**Comment by brettcurtis** [comment]
Feel free to add it and try, I'm just not sure how a sleep of 60 seconds will help when it's not a timing issue.

**Comment by edwardmedia** [comment]
@brettcurtis I can't repro this issue with the suggested solution. Closing this issue then. Please feel free to reopen it if you still see an issue. And I can take a look with your config and the debug log. Thanks

**Comment by brettcurtis** [comment]
You're saying you run the exact code above changing the obvious things that need to be changed and it runs for you to completion? Let's pull the null_resource out of the mix as I think it's cluttering the problem. 

So, run the tf above if it succeeds show me the apply, if it doesn't, and fails with the error above wait as long as you want and re-run it.

**Comment by edwardmedia** [comment]
@brettcurtis I don't see anything wrong in your log in term of the API requests. Whether the expected service account becomes available or not after you apply the plan is beyond Terraform provider. We have identified the time issue when new project and services are created. The length of waiting time varies depending on the type of services. Does this make sense to you? I am more than happy to help if you can post the complete config code (with the suggested solution) and the debug log. 
 
You may also look at below code to see if that helps. 

```tf
resource "google_project_service_identity" "build_account" {
  provider = google-beta
  service = "cloudbuild.googleapis.com"
}

output "email" {
  value = google_project_service_identity.build_account.email
}
```

**Comment by brettcurtis** [comment]
No, it makes sense, I agree it's outside the provider. I'll create a support ticket with Google since I would expect the service account to become available after the API was enabled without actually invoking it.
