### ISSUE TITLE
Unable to successfully import existing resource using google_bigquery_connection

### ISSUE THREAD

**Issue by krohmag** [hashicorp/terraform-provider-google#7615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.29
+ provider.aws v3.12.0
+ provider.cloudflare v2.12.0
+ provider.google v3.43.0
+ provider.google-beta v3.43.0
+ provider.random v3.0.0
+ provider.sdm v1.0.15
```

### Affected Resource(s)

* google_bigquery_connection

### Terraform Configuration Files

```tf
resource "google_bigquery_connection" "app_connection" {
  provider = google-beta
  for_each = toset(var.app_databases)

  location      = "US"
  connection_id = "${each.key}_${var.environment}"

  cloud_sql {
    database    = each.key
    instance_id = google_sql_database_instance.replica[0].connection_name
    type        = "POSTGRES"
    credential {
      password = <redacted>
      username = <redacted>
    }
  }
}
```

I'm trying to import an existing BigQuery connection into this resource, running the following: 
```
terraform import module.primary_application_database.google_bigquery_connection.app_connection[<service_name>] projects/<project_id>/locations/us/connections/<connection_id>
```

### Debug Output

https://gist.github.com/krohmag/f49e94840789beffb93fe46094453167

### Expected Behavior

The resource should have been imported into the state.

### Actual Behavior

```
Error: Cannot import non-existent remote object
```
The object does exist in the project. I've verified it via the BQ UI, and the BQ CLI. The Terraform docs for importing are somewhat ambiguous as to what defines `{{name}}`. I've attempted the import based on the name provided by the BQ CLI, and the name format from the Terraform `google_bigquery_connection` attribute reference (this is the format that is shown in the BQ API docs, so I believe this should be the correct format). Both result in the same error. 

### Steps to Reproduce

1. Create a BQ connection in a Google project.
2. Attempt to import that resource into the Terraform state. 

### Important Factoids

Looking through the debug logs, the regex the import is using appears to be incorrect, resulting in the error:
```
2020-10-23T12:54:59.291-0400 [DEBUG] plugin.terraform-provider-google-beta_v3.43.0_x5: 2020/10/23 12:54:59 [DEBUG] matching ID projects/<redacted>/locations/us/connections/application_service_integration to regex (?P<name>[^/]+).
2020-10-23T12:54:59.291-0400 [DEBUG] plugin.terraform-provider-google-beta_v3.43.0_x5: 2020/10/23 12:54:59 [DEBUG] importing name = projects
```
Based on the regex slicing off everything after `projects`, I've also tried to import based solely on the name after `connections/`, but that also results in the same error. 

The BigQuery API docs indicate that project, location, and connectionId are all required to successfully make the request. 

### References

* [BigQuery connection get API docs](https://cloud.google.com/bigquery/docs/reference/bigqueryconnection/rest/v1beta1/projects.locations.connections/get)

**Comment by edwardmedia** [comment]
With import command
terraform import google_bigquery_connection.connection projects/*/locations/*/connections/*

Result in GET URL 
should be:  https://bigqueryconnection.googleapis.com/v1beta1/{name=projects/*/locations/*/connections/*}

but actual:  https://bigqueryconnection.googleapis.com/v1beta1/
