### ISSUE TITLE
Unable to use parenthesis in filter (gcloud_projects)

### ISSUE THREAD

**Issue by frasercarter** [hashicorp/terraform-provider-google#7636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
ohmyzsh! ❯ terraform -v 

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.38.0
+ provider registry.terraform.io/hashicorp/google-beta v3.38.0
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)
Experienced with below resource however may affect more if its a filter validation issue; when trying to use parenthesis in a filter to query 2 or more parent.ids (in this instance folders) the API reports an error in the syntax, however the same syntax string is used with the gcloud command and successfully returns the expected projects nested under those parent ids.
* google_projects

### Terraform Configuration Files

```tf
data "google_projects" "reports_prod" {
  filter = "parent.id:(${local.join}) labels.environment:prod lifecycleState:ACTIVE"
  }

locals {
  filter = "parent.id:(${local.join}) labels.environment:prod lifecycleState:ACTIVE" # To confirm syntax
  join = join(",",["${google_folder.data_reports.folder_id}","${google_folder.data.folder_id}"])
}
```

### Expected Behavior
No issue with syntax as local.filter value confirms this is in alignment with filter used with gcloud command.

```
ohmyzsh! ❯ terraform console
> local.filter
parent.id:(000000000000,000000000001) labels.environment:prod lifecycleState:ACTIVE

ohmyzsh! ❯ 
gcloud projects list --filter="parent.id:(000000000000,000000000001) labels.environment:prod lifecycleState:ACTIVE"
PROJECT_ID           NAME                        PROJECT_NUMBER
sensitive-000000   Sensitive - Prod      999999999991
sensitive-000001    Sensitive - Dev       999999999992
```

### Actual Behavior

```
Error: Error retrieving projects: googleapi: Error 400: field [filter] has issue [invalid syntax]
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "invalid syntax",
        "field": "filter"
      }
    ]
  }
]
```

**Comment by edwardmedia** [comment]
@frasercarter this is handled in the layer of Terraform core. I would suggest you file an issue at [Terraform](https://github.com/hashicorp/terraform/issues). Feel free to reopen this if you see this is the Google provider specific.
