### ISSUE TITLE
No examples of how to use peerExternalGateway with the new google_compute_ha_vpn_gateway

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#7639]
Im trying to use `google_compute_ha_vpn_gateway` to create a vpn to aws as classic VPNs have been deprecated

Usually I would use `peer_ip` in the `google_compute_vpn_tunnel` resource with the IP of the aws vpn tunnel 

That throws this error: 
`Error creating VpnTunnel: googleapi: Error 400: Invalid value for field 'resource.peerIp': '1.2.3.4'. Cannot specify peer IP for HA VPN tunnel creation, please specify peerExternalGateway or peerGcpGateway instead., invalid`

Here is what it says about `peer_external_gateway`: `"URL of the peer side external VPN gateway to which this VPN tunnel is connected."`

The grammatical errors in there makes me suspicious this is just broken, but how do I use this with AWS or any other external non GCP vpn? the URL of the AWS tunnel? that doesn't make sense

Does this only support GCP VPC VPNs?

**Comment by edwardmedia** [comment]
@red8888 there are some [examples](https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html) that shows how to use these resources. VPNs are industrial standard. I have not tried your case yet but I don't believe it is for GCP VPC [VPNs](https://cloud.google.com/network-connectivity/docs/vpn/concepts/overview) only.

**Comment by red8888** [comment]
There are no examples for using `peer_external_gateway` and that is the only supported configuration for `google_compute_ha_vpn_gateway`

There should be an example in the docs of using `google_compute_external_vpn_gateway` with `peer_external_gateway` in addition to the included example for just hooking up two GCP VPNs together

**Comment by edwardmedia** [comment]
@red8888 I noticed you have filed another [issue](https://github.com/hashicorp/terraform-provider-google/issues/7662) . Are they the same questions? I am closing this one and using the other issue for tracking. Feel free to reopen it if you see a reason to keep two issues open.
