### ISSUE TITLE
Missing "project" fields not caught during "terraform plan"

### ISSUE THREAD

**Issue by ahmetb** [hashicorp/terraform-provider-google#7646]
Trying to use the example at https://www.terraform.io/docs/providers/google/r/compute_region_network_endpoint_group.html  to generate a GCLB.

### Terraform Version

Terraform v0.12.29
+ provider.google v3.44.0
+ provider.google-beta v3.44.0
### Affected Resource(s)

Unclear. :( :( 

terraform apply shows 3 weird log lines with no info + weird spacing around those lines:

```

Error: project: required field is not set



Error: project: required field is not set



Error: project: required field is not set
```

### Terraform Configuration Files

<details>
<summary>main.tf</summary>
<pre>
# provider "google" {
#   project = "${var.project}"
# }

provider "google-beta" {
  project = var.project
}

resource "google_cloud_run_service" "default" {
  name     = "hello"
  location = var.region

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
  }
}

data "google_iam_policy" "public" {
  binding {
    role    = "roles/run.invoker"
    members = ["allUsers"]
  }
}

resource "google_cloud_run_service_iam_policy" "public" {
  location    = google_cloud_run_service.default.location
  project     = google_cloud_run_service.default.project
  service     = google_cloud_run_service.default.name
  policy_data = data.google_iam_policy.public.policy_data
}

resource "google_compute_global_address" "default" {
  name = "${var.name}-address"
}

resource "google_compute_global_forwarding_rule" "default" {
  name   = "${var.name}-fwdrule"
  target = google_compute_url_map.default.id
}

resource "google_compute_managed_ssl_certificate" "default" {
  provider = google-beta

  name = "${var.name}-cert"
  managed {
    domains = ["${var.domain}"]
  }
}

resource "google_compute_backend_service" "default" {
  name      = "${var.name}-backend"
  protocol  = "HTTP"
  port_name = "http"
}

resource "google_compute_url_map" "default" {
  name            = "${var.name}-urlmap"
  default_service = google_compute_backend_service.default.id
}

resource "google_compute_region_target_https_proxy" "default" {
  name   = "${var.name}-https-proxy"
  region = var.region

  url_map          = google_compute_url_map.default.id
  ssl_certificates = [google_compute_managed_ssl_certificate.default.id]
}

resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
  provider              = google-beta
  name                  = "${var.name}-neg"
  network_endpoint_type = "SERVERLESS"
  region                = var.region
  cloud_run {
    service = google_cloud_run_service.default.name
  }
}

output "cloud_run_url" {
  value = element(google_cloud_run_service.default.status, 0).url
}

output "ip_address" {
  value = google_compute_global_address.default.address
}
</pre>
</details>

<details>
<summary>variables.tf</summary>
<pre>
variable "project" {
  description = "The project to deploy to, if not set the default provider project is used."
  type        = string
}

variable "name" {
  description = "The name of load balancer."
  type        = string
}

variable "region" {
  description = "The region of the backend."
  type        = string
}

variable "domain" {
  description = "The domain name of the load balancer."
  type        = string
}

variable "network" {
  description = "Network name"
  type        = string
  default     = "default"
}
</pre>
</details>

### Debug Output

https://gist.github.com/ahmetb/b56b60ca8e09c0ba4354b5eeec08835c

### Expected Behavior

It should print which resource has missing project setting OR use specified project on `provider "google-beta" {  project = var.project }`

### Actual Behavior

Shows a very odd error message making it impossible to debug which resource is missing `project` field.

### Steps to Reproduce

1. `terraform apply -var project=ahmetb-demo -var region=us-central1 -var name=hello -var domain=test.ahmet.dev`

**Comment by ahmetb** [comment]
I realized these 3 errors happen like that because 3 resources are being created in parallel.

However that's not an excuse. I think errors should be prefixed with the resource attempted to being created.

Some resources do this properly:

> **Error: Invalid value for ssl_certificates:** project: required field is not set

Also unclear why `terraform plan` or `terraform validate` doesn't capture this.

**Comment by venkykuberan** [comment]
Uncomment the `google` provider block and try it. If don't have the provider attribute in the resource config, tf picks the default `google` provider for creds, project, zone, region etc.

**Comment by ahmetb** [comment]
@venkykuberan Thanks for the advice. Since commenting-out `google` and having only `google-beta` still worked, I assumed `project = [...]` config can be picked up from `google-beta` as well ––however that was not the case.

Is that a bug that `google-beta { project = ... }` setting is not used properly when `google` provider is commented out?

**Comment by ahmetb** [comment]
Also we should probably keep this bug open because clearly some resources are able to print better error messages (https://github.com/hashicorp/terraform-provider-google/issues/7646#issuecomment-717565355) however some still aren't.

Similarly, I am not sure why these are not being caught during `plan` phase.

**Comment by ndmckinley** [comment]
If the resource is not in state, unfortunately the plan phase does not call into our code with the information we'd need to check whether the project is set, so this problem is not resolvable in our provider.  I do encourage you to open a bug in hashicorp/terraform with this as a motivating example - specifically what we would need is the provider configuration alongside the proposed configuration of the resource.

Let me see what I can do re: giving you the best possible error message.  :)

**Comment by ahmetb** [comment]
@ndmckinley I'm not entirely familiar with terraform internals, basically my main problem was that some resources print "which resource" was trying to fetch project ID:

    Error: Invalid value for ssl_certificates: project: required field is not set

it seems your commit might address that?

**Comment by ndmckinley** [comment]
Yep!  Now all resources will print that for project.  I think I _just_ missed the release cut, so that should be released a week from Monday.
