### ISSUE TITLE
Allow VPC_PEERING and SHARED_LOADBALANCER_VIP in google_compute_address.purpose

### ISSUE THREAD

**Issue by garbetjie** [hashicorp/terraform-provider-google#7652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_compute_address.purpose` field only supports `GCE_ENDPOINT`. `VPC_PEERING` and `SHARED_LOADBALANCER_VIP` are out of beta, but are not yet available in the latest `google` provider. It would be great to have these added.

### New or Affected Resource(s)

* google_compute_address

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://github.com/hashicorp/terraform-provider-google/issues/6743
* https://github.com/hashicorp/terraform-provider-google/issues/6499
* https://github.com/modular-magician/inspec-gcp/pull/411
* https://github.com/hashicorp/terraform-provider-google-beta/pull/2204/files

**Comment by txomon** [comment]
Same thing applies to `google_compute_global_address`. The complete list of options enabled for both should be:

* GCE_ENDPOINT
* DNS_RESOLVER
* VPC_PEERING
* NAT_AUTO
* IPSEC_INTERCONNECT

For google_compute_address.purpose https://cloud.google.com/compute/docs/reference/rest/v1/addresses#Address.FIELDS.purpose
For google_compute_global_address.purpose https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses#Address.FIELDS.purpose

**Comment by jmthvt** [comment]
This is already in beta, it just needs to be promoted to GA.
