### ISSUE TITLE
Cloud Function Memory Limit 

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#7654]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If this is a bug report (for when something is there, but doesn't work how it should), please use the [bug issue template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md) instead.

If this is an enhancement / feature request (for when something (a resource, field, etc.) is missing, and should be added), please use the [enhancement template](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md) instead.

If you have a support request or question, please check out the other resources listed [here](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=question.md).

If your issue does not fit into one of the above templates, please fill out the following:

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform v0.13.1
google provider v3.44.0

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files (if applicable)

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```
N/A

### Issue Description

The current restrictions on the cloudfunction state that the maximum amount of memory assignable to a cloud function is 2GB. 
However, in the cloud function UI it shows you can assign 4GB:
![image](https://user-images.githubusercontent.com/393945/97423164-bd381700-1906-11eb-98e7-f9ef5bd3b14d.png)

The go code -> https://github.com/hashicorp/terraform-provider-google/blob/31001bd420a947a2c56882df51f88671b283ff7f/google/resource_cloudfunctions_function.go#L18-L24

The google cloud function api documentation -> https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1#google.cloud.functions.v1.CloudFunction 

Can it be confirmed that 4GB is allowed or not? And if so happy to raise a PR to add this little change in :).

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment]
The [doc](https://cloud.google.com/functions/quotas) states 2GB

**Comment by drandell** [comment]
So can you explain the UI option then @edwardmedia ?

**Comment by edwardmedia** [comment]
@drandell the UI option seems clear it supports 4GB. Somehow it does not match the API doc, which the Tearrform provider is based on. I have filed an issue against the related teams. Hopefully this discrepancy can get resolved soon.

**Comment by drandell** [comment]
@edwardmedia okay maybe I should have been a bit more specific. Are you staying that the doc linked by yourself is the source of truth or this is as yet unknown?
