### ISSUE TITLE
[Enhancement] Regional Filestore instances like in AWS

### ISSUE THREAD

**Issue by Shaybs** [hashicorp/terraform-provider-google#7656]
Enhancement/Feature Request is in the title.

**Comment by upodroid** [comment]
Hi

This doesn't exist yet on Google Cloud. Terraform can only support products that Google has release and have an API to control them.

In the meanwhile:
- Open a feature request with Google directly.
- Use NetApp Cloud Volumes. They are regional nfs stores and much better than Filestore.


If this answers your question, please go ahead and close this issue.

Thank

**Comment by rileykarson** [comment]
Thanks for filing! As @upodroid says, since this appears to be unsupported in GCP, there's not much we can do in the provider.
