### ISSUE TITLE
GCP Certificate Authority Service support

### ISSUE THREAD

**Issue by paulwilljones** [hashicorp/terraform-provider-google#7657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Added support for [GCP Certificate Authority Service](https://cloud.google.com/certificate-authority-service/docs/reference/rest). Currently in beta, with apiv1beta1 support merged into [google-cloud-go SDK](https://github.com/googleapis/google-cloud-go/commits/master/security/privateca/apiv1beta1).

### New or Affected Resource(s)

* google_privateca_certificateauthority
* google_privateca_certificate

**Comment by GregoireW** [comment]
This product is beta so not sure what it is plan / done / known  about those new resources. Anyway I write the result of my test here.

With provider 3.64,

- The PR on magic-modules state `SUBORDINATE` certificates are not working correctly, so it is not a big surprise they don't.
- If we apply a tf to create ca/certificate, then the next time we plan, tf will try to replace the resource (destroy / re-create)

**Comment by melinath** [comment]
b/259264347
