### ISSUE TITLE
weird google_compute_router_peer error - peer IP address 1.2.3.4 is specified, but IP address is not specified

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#7662]
tf and provider version: 
```
Terraform v0.12.12
+ provider.aws v3.12.0
+ provider.google v3.44.0
+ provider.google-beta v3.44.0
```

trying to use google_compute_router_peer resource:
```
resource "google_compute_router_peer" "gcw1-router-interface1" {
  provider        = google-beta
  name            = "gcw1-gcp-to-aws-bgp1"
  region          = google_compute_router.gcp-router.region
  router          = google_compute_router.gcp-router.name
  advertise_mode  = "DEFAULT"
  peer_ip_address = aws_vpn_connection.aws-gcp-vpn-connection-1.tunnel1_vgw_inside_address
  peer_asn        = aws_vpn_connection.aws-gcp-vpn-connection-1.tunnel1_bgp_asn
  interface       = google_compute_router_interface.gcw1-router-interface1.name
}

```
I get this cryptic error:
`Error: Error creating RouterBgpPeer: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[0]': '{  "name": "gcw1-gcp-to-aws-bgp1",  "interfaceName": "gcw1-gcp-to-aws-interface1...'. In BGP Peer "gcw1-gcp-to-aws-bgp1", peer IP address 1.2.3.4 is specified, but IP address is not specified., invalid`

What does this even mean? `peer IP address 1.2.3.4 is specified, but IP address is not specified` ? 

There are no other arguments for IP address, what else to I have to specify here? I cant even find anything in source for `but IP address is not specified` either

**Comment by red8888** [comment]
looks like this issue was how I created the route interface.

I did this:
```
resource "google_compute_router_interface" "gcw1-router-interface1" {
  ip_range   = aws_vpn_connection.aws-gcp-vpn-connection-1.tunnel1_inside_cidr
```

Instead of this:
```
resource "google_compute_router_interface" "gcw1-router-interface1" {
  ip_range   = "${aws_vpn_connection.aws-gcp-vpn-connection-1.tunnel1_cgw_inside_address}/30"
```

but im confused because shouldnt tunnel1_inside_cidr give me the right value here?

**Comment by edwardmedia** [comment]
@red8888 both resources have examples on web documents [google_compute_router_peer](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_bgp_peer), [google_compute_router_interface](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_interface) 
For your last question, can you use *output` and then manipulate the data?

**Comment by edwardmedia** [comment]
@red8888 closing this as the examples show how to code. Feel free to reopen if you want to continue the conversation
