### ISSUE TITLE
Data for pubsub service

### ISSUE THREAD

**Issue by camerondavison** [hashicorp/terraform-provider-google#7663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In the same way that there is a `google_storage_project_service_account` It would be nice to have one available for the pubsub service account. This would make it easier to add the necessary permissions for dead letter queues.

### Potential Terraform Configuration

```tf
data "google_pubsub_project_service_account" "pubsub_account" {
}
```

**Comment by rileykarson** [comment]
This is likely a similar case to https://github.com/hashicorp/terraform-provider-google/issues/7522

**Comment by rileykarson** [comment]
Reopening- I think we want this to appear on the original resource page too, not just the service identity resource. This is about improving the discoverability of `google_project_service_identity`.

**Comment by rileykarson** [comment]
Re-opening, I was too fast for the robot.
