### ISSUE TITLE
`google_dataproc_cluster_iam` shows headers for `google_pubsub_subscription_iam`.

### ISSUE THREAD

**Issue by bartcode** [hashicorp/terraform-provider-google#7670]
### Affected Resource(s)

* google_dataproc_cluster_iam
* google_pubsub_subscription_iam

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Description

On the documentation page of [`google_dataproc_cluster_iam`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster_iam), the headers are mentioning pubsub (e.g. `google_pubsub_subscription_iam_policy`). The examples are correct, it's just the headers that are wrong.

b/308569349
b/308569682

**Comment by cnauroth** [comment]
I believe this was resolved in #7672 . Can we please close this issue?
