### ISSUE TITLE
VPC Connector -> Project Required

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#7673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform v0.13.1
google provider v3.44.0

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

```tf
resource "google_compute_network" "vpc_network" {
  name                    = "${var.project_id}-vpc"
  project                 = var.project_id
  auto_create_subnetworks = false
  routing_mode            = "REGIONAL"
}

resource "google_vpc_access_connector" "connector" {
  name          = "my-connector"
  region        = "europe-west2"
  ip_cidr_range = "10.8.0.0/28"
  network       = "${var.project_id}-vpc"
}
```

### Debug Output

![image](https://user-images.githubusercontent.com/393945/97578572-e3ce7e80-19e8-11eb-9e99-ea9a17083a5b.png)

### Panic Output

N/A

### Expected Behavior

The VPC connector should create.

### Actual Behavior

The VPC connector failed to create stating that the project is required. 
However, the terraform docs https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector state that project is optional.

### Steps to Reproduce

1. Try to create the above resource without supplying a project id

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment]
@drandell `project` is optional if you have set the default project on your machine. One method is you can do it by providing environment variable `GOOGLE_PROJECT`. Here is the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project) you may want to review. You may close this issue if this makes sense to you

**Comment by drandell** [comment]
Ah i see, no that makes sense. I will close this.
