### ISSUE TITLE
Poor documentation around load balancers and health checks

### ISSUE THREAD

**Issue by kwri-avongluck** [hashicorp/terraform-provider-google#7674]
1) I setup a healthcheck for our load balancer:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_health_check

<img width="610" alt="Screen Shot 2020-10-29 at 1 34 33 PM" src="https://user-images.githubusercontent.com/40496582/97617766-2d6c9880-19ec-11eb-8e10-31d2794bd955.png">

2) It hasn't been working at google.  (No errors applying, it just isn't detecting an online backend)

3) Finally after 2 days of troubleshooting I find this little gem crammed in the legacy http health_check you're not supposed to use:

<img width="610" alt="Screen Shot 2020-10-29 at 1 34 16 PM" src="https://user-images.githubusercontent.com/40496582/97617899-5b51dd00-19ec-11eb-9b7c-82272f460391.png">

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_http_health_check

"The newer google_compute_health_check should be preferred for all uses *EXCEPT NETWORK LOAD BALANCERS WHICH STILL REQUIRE THE LEGACY VERSION*

It might save folks a lot of time / trouble to mention this on the google_compute_health_check page which doesn't mention this limitation at all..  google_compute_health_check even goes on to mention usage with load balancers.

**Comment by kwri-avongluck** [comment]
Actually... it looks like the Note about having to use the legacy google_compute_http_health_check with network load balancers might no longer be correct?

Potential Solutions:
1. Mention needing to use the legacy healthcheck for Network Load Balancers on the google_compute_health_check page
2. Drop the Note from google_compute_http_health_check if it is no longer true.

**Comment by edwardmedia** [comment]
Here is what [Health checks overview ](https://cloud.google.com/load-balancing/docs/health-check-concepts?_ga=2.186289837.-564592060.1584370165#selecting_hc )explains

```
Network Load Balancing requires legacy health checks that use the HTTP protocol. All other load balancer types use regular health checks.```
