### ISSUE TITLE
google_data_catalog_taxonomy, google_data_catalog_policy_tag: import not working

### ISSUE THREAD

**Issue by pietrodn** [hashicorp/terraform-provider-google#7679]
I want to import the existing taxonomy and policy tag that I have manually defined in my project, but the import using the `google-beta` 0.45 provider does not work.
I am owner and "Policy Tag Admin" on the GCP project.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.4

### Affected Resource(s)

* `google_data_catalog_taxonomy`
* `google_data_catalog_policy_tag`

### Terraform Configuration Files

```tf
resource "google_data_catalog_taxonomy" "personal_data" {
  provider               = google-beta
  region                 = "us"
  display_name           = "Personal data - My Project"
  description            = "Taxonomy to handle personal data of our users."
  activated_policy_types = ["FINE_GRAINED_ACCESS_CONTROL"]
}

resource "google_data_catalog_policy_tag" "identifier_cleartext" {
  provider     = google-beta
  taxonomy     = google_data_catalog_taxonomy.personal_data.id
  display_name = "identifier_cleartext"
  description  = "Can see the real user identifier in cleartext"
}
```

### Debug Output

https://gist.github.com/pietrodn/0b71f202f2e6a9bf8d1822c2e62ce60a

### Expected Behavior

Terraform should import the resource.

### Actual Behavior

Terraform complains that the resource does not exist.

### Steps to Reproduce

```
terraform import module.common.google_data_catalog_taxonomy.personal_data projects/my-project/locations/us/taxonomies/2286267978568221919

terraform import module.common.google_data_catalog_policy_tag.private_field "projects/my-project/locations/us/taxonomies/2286267978568221919/policyTags/3829827598341455677"
```

### References

* https://github.com/hashicorp/terraform-provider-google-beta/pull/2626

**Comment by edwardmedia** [comment]
The GET request URL is no correct

terraform import google_data_catalog_taxonomy.personal_data projects/my-project/locations/us/taxonomies/2286267978568221919

```
2020-10-30T12:35:04.820Z [DEBUG] plugin.terraform-provider-google-beta_v3.45.0_x5: GET /v1beta1/projects?alt=json HTTP/1.1
2020-10-30T12:35:04.820Z [DEBUG] plugin.terraform-provider-google-beta_v3.45.0_x5: Host: datacatalog.googleapis.com
2020-10-30T12:35:04.820Z [DEBUG] plugin.terraform-provider-google-beta_v3.45.0_x5: User-Agent: Terraform/0.13.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.3 terraform-provider-google-beta/3.45.0
2020-10-30T12:35:04.820Z [DEBUG] plugin.terraform-provider-google-beta_v3.45.0_x5: Content-Type: application/json
2020-10-30T12:35:04.820Z [DEBUG] plugin.terraform-provider-google-beta_v3.45.0_x5: Accept-Encoding: gzip
```

**Comment by pietrodn** [comment]
Thank you! I'll try it as soon as a new version is released. 👍

**Comment by pietrodn** [comment]
I confirm the import works. However I'm observing another problem: Terraform wants to replace the policy tag on the imported resource because it wants to "add" the taxonomy attribute:

```
 # module.common.google_data_catalog_policy_tag.advertising_id_cleartext must be replaced
-/+ resource "google_data_catalog_policy_tag" "advertising_id_cleartext" {
      ~ child_policy_tags = [] -> (known after apply)
      ~ id                = "projects/my-project-id/locations/us/taxonomies/268635763456745357/policyTags/3829827535341454737" -> (known after apply)
      ~ name              = "projects/my-project-id/locations/us/taxonomies/268635763456745357/policyTags/3829827535341454737" -> (known after apply)
      + taxonomy          = "projects/my-project-id/locations/us/taxonomies/268635763456745357" # forces replacement

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Adding the `lifecycle` block seems to be an effective workaround:
```tf
resource "google_data_catalog_policy_tag" "my_policy_tag" {
  provider     = google-beta
  taxonomy     = google_data_catalog_taxonomy.my_taxonomy.id
  display_name = "my_policy_tag"
  description  = "Whatever"

  lifecycle {
    // Workaround for bug: Terraform wants to replace the imported policy tag
    ignore_changes = [taxonomy]
  }
}
```

**Comment by c2thorn** [comment]
@pietrodn So the import is successful, but if you immediately run `terraform apply` it will show new diffs? This is a different problem but a problem nonetheless. Do you mind opening another issue with your repro steps?

**Comment by pietrodn** [comment]
@c2thorn exactly. I'll try to reproduce a set of minimal reproduction steps and open another issue. Thanks
