### ISSUE TITLE
App Engine API unnecessarily required for Datastore creation

### ISSUE THREAD

**Issue by yk-47** [hashicorp/terraform-provider-google#7680]
### Terraform Version

Terraform v0.12.29
+ provider.google v3.45.0

### Affected Resource(s)

* google_app_engine_application

### Summary
I'm trying run a terraform plan after I've imported `google_app_engine_application` for my datastore instance in my target project (PROJECT-B), I'm authtenticating to gcloud using a service account from my source project (PROJECT-A). 

When running terraform plan, it requires me to enable the App Engine API in my source project (PROJECT-A) even though I'm creating it in my target project (PROJECT-B).

We turn the App Engine API on as part of this creation for the target project.

### Terraform Configuration Files

```tf
resource "google_app_engine_application" "cloud-datastore" {
  project     = google_project.test-project.project_id
  location_id = "europe-westl"
  database_type = "CLOUD_DATASTORE_COMPATIBILITY"
}
```

### Expected Behavior

It should create and refresh the state of the datastore instance.

### Actual Behavior

I get the following error:
```
Error: Error when reading or editing App Engine Application "PROJECT-B": googleapi: Error 403: App Engine Admin API has not been used in project 239539014771 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/appengine.googleapis.com/overview?project=PROJECT-A-ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

### Steps to Reproduce

1. Terraform import app engine resource to create datastore `Terraform import google_app_engine_application-cloud-datastore PROJECT B`
2. Activate service account from source project `gcloud auth activate-service-account --key-file` 
3. Switch to source project `gcloud config set project PROJECT-A` 
4. terraform plan

### References

Looks very similar to  https://github.com/hashicorp/terraform-provider-google/issues/1529

**Comment by upodroid** [comment]
Hi

The API has to enabled in the project that the service account belongs to.

For example, `gcloud compute instances create foo-bar --account terraform@potato.iam.gserviceaccount.com --project tomato` will only work if:
- Compute Engine is enabled on project tomato because this is the project that will hold the instance.
- Compute Engine is enabled on project potato because this is the project that the service account belongs to.

**Comment by yk-47** [comment]
Hi @upodroid 

Why is this not the case with other google apis?

**Comment by upodroid** [comment]
Yeah

**Comment by edwardmedia** [comment]
@yk-47 does this make sense to you? You may close it if yes, or leave it open if you still have issues with it.

**Comment by yk-47** [comment]
This makes sense, thanks for the prompt response.
