### ISSUE TITLE
Fix the positions of some of the documentation entries.

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#7681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We have alot resources under the Cloud Platform section of the provider docs. These are mostly handwritten resources.

I would like to move them under the correct API section.

![image](https://user-images.githubusercontent.com/25100905/97701367-353c4380-1aa5-11eb-8f14-282227938409.png)

- Yellow Resources should be under Cloud Billing. Billing Budget Section exists but should renamed Cloud Billing and move the yellow resources and their associated data sources.
- Green resources should be under Resource Manager along with their corresponding datasources.
- Blue resources should be under Cloud IAM along with their data sources
- Black resources should be under Service Usage
- Red resource should be under Compute Engine 

After I complete the move, the only resources/datasource left is `google_client_*`

@rileykarson Should I do this as part of a minor release or come back to it when the v4 work starts?

**Comment by upodroid** [comment]
I'll leave CRM resources alone and move the other resources/datasources.

**Comment by rileykarson** [comment]
I think blue+black make sense to keep there too! yellow+red sgtm

**Comment by upodroid** [comment]
I think that decision needs to be revisited for a few reasons:
- Docs are hosted in a new place.
- Resources/Datasources are searchable.

The switchover happened recently so we could come out say "new site and we shuffled some of the docs to line them up with their correct APIs and Google Docs."

**Comment by rileykarson** [comment]
Fair enough! I'll bring it up with the team in our triage monday and see if anyone else has any inputs.

**Comment by upodroid** [comment]
Great, in the meanwhile I'll fix the red and the yellow ones.

**Comment by rileykarson** [comment]
After consulting with the team, I think we're happy with the split as-is after your change! The project/folder/org resources (including service accounts) make sense to group together under a single label.

Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4182
