### ISSUE TITLE
region_backend_service doesn't support EXTERNAL

### ISSUE THREAD

**Issue by ogreface** [hashicorp/terraform-provider-google#7683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

It's currently not possible to build an external, regional, HTTP(S) load balancer via Terraform. This is because the regional_backend_service resource forces your loadBalancingScheme to INTERAL, or INTERNAL_MANAGED. EXTERNAL is supported by the API (and appears to have been supported for some time).

It looks like there' s a fix in for this already: 
https://github.com/hashicorp/terraform-provider-google/commit/aff0ab261800da32bd9ad7864a1b60aead3a8f29

Any chance of a point release today for the provider? This is a significant blocker for us and we're trying to build and validate some of our infrastructure for a deployment later this weekend.

Thanks!

**Comment by c2thorn** [comment]
Hi @ogreface , I wasn't able to get to this until now. If you weren't aware, the feature was released in [v3.46](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.46.0). We aim to release on Mondays to allow for extra test time, so we likely wouldn't have released when you requested. 

If it helps at all in the future, it is always an option to checkout this repository at the commit that you want, and [build the provider](https://github.com/hashicorp/terraform-provider-google#building-the-provider) so you can use pre-released features.

**Comment by ogreface** [comment]
Thanks @c2thorn , appreciate it. 

Building the provider is fine, but overriding in TFE is a bit more problematic. :) Regardless, I appreciate you following up on this, thanks again!
