### ISSUE TITLE
Add full example for OSLogin SSHPublicKey

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#7686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We are currently missing a full test for OSLogin SSHPublicKey; we only have a basic test. There are a couple of things that make this a little complicated:

- expirationTimeUsec will need to be automatically set to a future time
- project should be set to a different project than the default
- the full test needs to use a different public key than the basic test. The resource ID is based on the SSH key's fingerprint, and if the tests use the same key, the resource will sometimes be deleted by one test before the other test is done with it.

### New or Affected Resource(s)

N/A - test only

### Potential Terraform Configuration

N/A - test only

### References

* Follow-up to https://github.com/hashicorp/terraform-provider-google/issues/7597

**Comment by c2thorn** [comment]
Thanks for filing this @melinath ! I think this could go under tech-debt, but I'll let you all decide during triage.
