### ISSUE TITLE
google_cloud_scheduler_job attribute retry_config does not maintain state

### ISSUE THREAD

**Issue by lc-chrisbarton** [hashicorp/terraform-provider-google#7689]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```shel
 terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.44.0
+ provider registry.terraform.io/hashicorp/null v2.1.2l
```

### Affected Resource(s)

google_cloud_scheduler_job attribute retry_config

### Terraform Configuration Files

```tf
resource "google_cloud_scheduler_job" "job_run_svc_calculate_analytics_behaviors" {

  name             = "RUN_SVC_CALCULATE_ANALYTICS_BEHAVIORS"
  schedule         = "0 5 * * *"
  attempt_deadline = "900s"
  retry_config {
    retry_count = 0
  }
  http_target {
    http_method = "POST"
    uri         = "https://run.${var.env}.acme.com/run/v1/schedule-workloads?type=CALCULATE_ANALYTICS_BEHAVIORS&kubernetes_cluster=models&kubernetes_cluster_zone=us-central1-a"
    oidc_token {
      service_account_email = var.sa_cloud_scheduler_push_svc_email
      audience              = "run-svc"
    }
  }
}
```

### Expected Behavior

After applying the change if we run `terraform apply` again we expect there are no changes to apply.

### Actual Behavior

After applying the change if we run `terraform apply` again we are prompted to apply changes.

### Debug Output

See https://github.com/hashicorp/terraform-provider-google/issues/6204 but now use 

```
retry_config {
    retry_count = 0
}
```

If you do not include 'retry_config' then everything works i.e. there is no retry after a 400 or 500 series HTTP status code is returned and after applying the terraform once you are not prompted to re-apply it if you re-run `terraform apply`. However I think the documentation is wrong on the default behaviour because it says:

"By default, if a job does not complete successfully, meaning that an acknowledgement is not received from the handler, then it will be retried with exponential backoff according to the settings Structure is documented below."

See 'https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job#retry_config'

**Comment by venkykuberan** [comment]
`retry_count` > 0 should work as expected. If don't want to have retry_config you can just ignore that block as its optional.

**Comment by edwardmedia** [comment]
No response. Assuming it is no longer an issue
