### ISSUE TITLE
`google_bigquery_table` doesn't support ORC format

### ISSUE THREAD

**Issue by laurenemms** [hashicorp/terraform-provider-google#7691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.45.0
```

### Affected Resource(s)

`google_bigquery_table`

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "some_table" {
  dataset_id = "some_dataset"
  table_id = "some_table"

  external_data_configuration {
    autodetect  = true
    source_format = "ORC"
    source_uris = [
      "gs://bucket-name/*"
    ]
    hive_partitioning_options {
      mode = "CUSTOM"
      source_uri_prefix = "gs://bucket-name/{date:DATE}"
    }
  }
}
```
### Expected Behavior
Should be able to create a table from a bucket with ORC data. This works from the API.

### Actual Behavior
`Error: expected external_data_configuration.0.source_format to be one of [CSV GOOGLE_SHEETS NEWLINE_DELIMITED_JSON AVRO DATSTORE_BACKUP PARQUET], got ORC`

### Steps to Reproduce

`terraform apply`

### References

Orc is listed as supported: https://cloud.google.com/bigquery/external-data-cloud-storage and works when hitting the API

**Comment by upodroid** [comment]
@venkykuberan there is another identical issue for the same field. 

https://github.com/hashicorp/terraform-provider-google/issues/7653

I'll open to fix the valid options

**Comment by venkykuberan** [comment]
Thank you @upodroid.

@laurenemms i am closing this issue as a duplicate. We have a work in progress here #7653 for the same field. I requested to include ORC in the source_format list.

**Comment by laurenemms** [comment]
> Thank you @upodroid.
> 
> @laurenemms i am closing this issue as a duplicate. We have a work in progress here #7653 for the same field. I requested to include ORC in the source_format list.

Hi! Is it possible to reopen this? I noticed that this change was [considered out of scope of that PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/4155/files#r520275350).

**Comment by upodroid** [comment]
I don't agree with the assesment in https://github.com/GoogleCloudPlatform/magic-modules/pull/4155/files#r520275350 

Tests are not required for relaxing ValidateFuncs. It is the job of the enduser to supply valid values.

@slevenick Do you agree?

**Comment by slevenick** [comment]
I'd say it could be added to that PR, but I wouldn't require them to add it. I'll reopen this as the format can be added in a separate PR
