### ISSUE TITLE
Docs for google_monitoring_alert_policy have incorrect import instructions

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform-provider-google#7693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.3
+ provider registry.terraform.io/-/google v3.45.0
+ provider registry.terraform.io/hashicorp/google v3.45.0

### Affected Resource(s)

* google_monitoring_alert_policy

### Expected Behavior

The documentations says import looks like:
`terraform import google_monitoring_alert_policy.default {{name}}`

### Actual Behavior

Documented syntax doesn't work.  Even after figuring out what `name` is, I get:
```
$ terraform import google_monitoring_alert_policy.default projects/{{project_id}}/alertPolicies/{{alert_policy_id}} 
google_monitoring_alert_policy.default: Importing from ID "projects/{{project_id}}/alertPolicies/{{alert_policy_id}}"...

Error: project: required field is not set
```

After futzing around a bit, the correct syntax appears to be:
```
terraform import google_monitoring_alert_policy.default "{{project_id}} projects/{{project_id}}/alertPolicies/{{alert_policy_id}}"
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#import

**Comment by edwardmedia** [comment]
@rvandegrift what the format of **{{name}}** did you put?
Below is what I see both **id** and **name**, and it is fine with me. Can you check?
```
            "id": "projects/myproject/alertPolicies/3983119688813294231",
            "name": "projects/myproject/alertPolicies/3983119688813294231",
```

**Comment by rvandegrift** [comment]
@edwardmedia - the bit you cited is the `name` field for the embedded `condition` block.  According to the docs `google_monitoring_alert_policy` has no `name` or `id` field - so I didn't include either.

But after import, `terraform state show google_monitoring_alert_policy.default` includes both `id` and `name`.  I wouldn't expect them to be required in the config, since they're computed from the API results.

**Comment by edwardmedia** [comment]
@rvandegrift  do you see both `id` and `name` under **Attributes Reference**? Does that make sense? Those are what I refer to. (I updated above context)

**Comment by rvandegrift** [comment]
I see those attributes, but that says:
> the following computed attributes are exported:
>
>  * `id` - ...
>   * `name` - ...

But I never have needed to configured computed attributes to import before.  Are you saying that's a requirement here?

**Comment by edwardmedia** [comment]
@rvandegrift when you plan to import a resource, I guess you have already known what it is. We don't expect you to get the id/name from Terraform. Does this make sense? Are you able to find its `name` via other tools like GCP Console or gcloud?
I don't understand what you mean. I have verified the `import` command and it works for me. If that doesn't work for you, do you want to post your complete config and the command?
```
Are you saying that's a requirement here?
```

**Comment by rvandegrift** [comment]
@edwardmedia Yea, I have no problem getting the `name` - it looks like `projects/{{project_id}}/alertPolicies/{{alert_policy_id}}`.  My first post shows the invocation and error.

I think I figured out the issue.  In my case, `{{project_id}}` in `name` is a stackdriver workspace project - so it's different than the project configured on my provider instance.


Terraform should be able to handle this situation better.

Ideally, the project id in the full resource name should be used.  But if that can't be done, or isn't desirable, it'd be nice to get an error message about the mismatch between the provider's configured project id and project id in the import's full resource name.

**Comment by edwardmedia** [comment]
@rvandegrift this follows the general pattern for other resources. You may file new [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?template=enhancement.md) for your suggestions. I am glad you found the solution to your issue. Do you still see issue with the doc? I am closing this now. Feel free to reopen if you need further discussion.
