### ISSUE TITLE
Import of google_compute_project_metadata_item uses the provider default project instead of the project specified in the resource

### ISSUE THREAD

**Issue by supersmo** [hashicorp/terraform-provider-google#7694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.5
hashicorp/google v3.46.0

### Affected Resource(s)

* google_compute_project_metadata_item

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {}
  }
}

provider "google" {
  project = var.default_project_id
}

variable "default_project_id" {
  description = "The default project id specified in the provider config"
  type = string
}

variable "project_id" {
  description = "The actual gcp-project-id"
  type = string
}

resource "google_compute_project_metadata_item" "enable_oslogin" {
  project = var.project_id
  key = "enable-oslogin"
  value = "TRUE"
}
```

### Expected Behavior
The project specified in the resource should have been used.

### Actual Behavior
The project specified in the provider config block was used.

### Steps to Reproduce

```sh
TF_VAR_default_project_id=default_project_id
TF_VAR_project_id=specific_project_id
terraform init
terraform import google_compute_project_metadata_item.enable_oslogin enable-oslogin
terraform state show google_compute_project_metadata_item.enable_oslogin
```
output:
```sh
# google_compute_project_metadata_item.enable_oslogin:
resource "google_compute_project_metadata_item" "enable_oslogin" {
    id      = "enable-oslogin"
    key     = "enable-oslogin"
    project = "****"
    value   = "TRUE"

    timeouts {}
}
```
Both the project and the value that was imported is from the project specified in the provider block and not the project specified in the resource.

### References

Looks to be the same kind of issue (but not same resource) as :
* #5550

**Comment by venkykuberan** [comment]
When importing an existing resource the config should have just the name of the resource like below

 `resource "google_compute_project_metadata_item" "enable_oslogin" {
 }`

Can you remove the attributes in your config and try importing ?

**Comment by supersmo** [comment]
Yes, the import succeeds using the default project set in the provider config.
That is not what I want to achieve though.

In my case I expected the imported resource to use the project specified in the resource block rather than the default project in the provider. I've seen this work for other resources... although I'm not sure if  in all of those cases the project was taken from the import id or from the project specified in the resource.

It's a bit confusing if it doesn't respect the project in the resource block and this comment suggests that it should work: https://github.com/hashicorp/terraform-provider-google/issues/5742#issuecomment-590526579

Following that example:
```
terraform {
  required_providers {
    google = {}
  }
}
provider "google" {}

resource "google_compute_project_metadata_item" "enable_oslogin" {
  project = <the-project-id>
}
```

```
terraform import google_compute_project_metadata_item.enable_oslogin enable-oslogin
```
Results in:
```Error: project: required field is not set```

**Comment by venkykuberan** [comment]
@supersmo import command (all resources) uses the information given in the command arguments and for `project` it rely on env. variable or provider config. It doesn't look into resource config as that's the resource its trying to import.

**Comment by supersmo** [comment]
Then my understanding of how importing other resources in terraform was incorrect as I thought it could respect the project field specified in the resource.
Thanks @venkykuberan for explaining the limitations of terraform import.

Would it be possible to support a full resource name for the import and use the project specified there? Not sure if a project metadata item has a standard full resource name but I assume it would be something like //compute.googleapis.com/projects/project-id/meta-data/key instead of just passing the key.

**Comment by venkykuberan** [comment]
You can try passing the id as `projects/project-id/meta-data/key`.

**Comment by supersmo** [comment]
Tried now and it doesn't work. It doesn't use the project-id from the full resource name.

**Comment by venkykuberan** [comment]
@supersmo currently this resource supports import only by the `key`. I will make this issue as an enhancement ticket to support for other formats as well.
