### ISSUE TITLE
Support Cloud Domains API

### ISSUE THREAD

**Issue by loozhengyuan** [hashicorp/terraform-provider-google#7696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud has [announced](https://cloud.google.com/blog/products/networking/cloud-domains-is-generally-available) the general availability of [Cloud Domains](https://cloud.google.com/domains/docs) on [October 19, 2021](https://cloud.google.com/release-notes#October_19_2021). You can find the API docs [here](https://cloud.google.com/domains/docs/reference/rest).

### New or Affected Resource(s)

* google_domains_registration

### Potential Terraform Configuration

```tf
resource "google_domains_registration" "domain_tld" {
  domain_name = "domain.com"

  management_config {
    transfer_lock = true
  }

  labels = {
    key = "value"
  }
}
```
Internal issue: [http://b/232423611](http://b/232423611)

**Comment by claudioscalzo** [comment]
Starting from [October 19th 2021](https://cloud.google.com/release-notes#October_19_2021) Cloud Domains is [available in GA](https://cloud.google.com/blog/products/networking/cloud-domains-is-generally-available) (@loozhengyuan you may want to update the issue description 🙏🏻).

**Comment by loozhengyuan** [comment]
Thanks @claudioscalzo, I have updated the issue to reflect the GA status.

**Comment by Mearman** [comment]
Has there been any progress on adding this resource?

**Comment by james-reed-toshi** [comment]
+1 on this, would be great to have the support

**Comment by ScottSuarez** [comment]
We may require to handwrite this resource..

Reasons
### Imperative methods for updating fields
While this resource supports patch for [updating labels](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/patch) all other updatable fields require specific imperative methods to update them.
##### configureContactSettings
##### configureDnsSettings
##### configureManagementSettings

### Registering a new domain requires two calls
One call is required to [retrieve information needed to register the domain, including price and availability](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/retrieveRegisterParameters). A [subsequent call is then needed](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/register), using data from the first, to register and purchase the domain.

### Managing domains which already exist 
While terraform import could be used to import and manage existing domains its not ideal. We could, prior to creating a domain, check if it already exists and then manage it directly. Applying any corresponding updates to the resource model.

### Deletion Protection needed
Deleting a domain will [push the domain to the calling users Google Domains](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/delete). It's not clear to me how to get a domain from google domain back into cloud domains, so, if this is a frustrating experience I would prefer to protect our users from making such a mistake.

**Comment by ScottSuarez** [comment]
Provisioning a domain is tricky with terraform due to surprising prices, different TLDs accepting different whois formats, and different TLDs allowing different settings... Need to consider if terraform is the correct place or if we would rather manage this resource in a fine-grained way.

**Comment by ScottSuarez** [comment]
Hello github community. 

Could you share more about the format of the resource you are expecting and/or your desires for this resource.

Are you looking for e2e provisioning of a domain. This can get rather dangerous with the price volatility of domains. A typo could result in a significant unexpected purchase, costing thousands of dollars, if it was to be automated with terraform.

Are you simply looking to manage existing/provisioned domains and the metadata therein? 

Its a tricky resource for us due to the price volatility and the non-traditional interface of the api.

**Comment by loozhengyuan** [comment]
@ScottSuarez I can't speak for everyone but maybe I can share my use case when I first created this issue. In our organisation, we use Terraform to manage resources on Google Cloud rather than to provision resources end-to-end, so being able to at least manage provisioned domains is already a good step forward for us.

With that said, some organisations do use Terraform to provision E2E so I think it is helpful to provide that. To guard against unexpected creation behaviours, I think the resource should have some meta-arguments with safe defaults:

```hcl
resource "google_domains_registration" "domain_tld" {
  domain_name = "domain.com"
  
  registration_enabled = false
  registration_budget = 20

  management_config {
    transfer_lock = true
  }

  labels = {
    key = "value"
  }
}
```

- `registration_enabled`: Whether to register the domain. Defaults to `false`.
- `registration_budget`: Maximum budget for domain registration. If the domain exceeds this threshold, domain registration will fail. Defaults to `0`.

So the expectation is that if the user wants to use this resource to create domains, they must set these two variables. In absence of either variables (or when left to default values), then domain creation will safely fail. This explicit opt-in behaviour also keeps the user aware of the potential dangerous behaviour when interacting with this resource.

Last but not least, I think good documentation will come a long way. Most people rely on the provider documentation when writing a new resource, so having an explicit warning message for this resource will be very helpful.

**Comment by james-reed-toshi** [comment]
The idea from @loozhengyuan sounds great to me. It might be worth considering adding the ability to use `timeouts` on this resource, too.

**Comment by ScottSuarez** [comment]
What would you want to happen with deletion?

If you delete a domain it gets forced out into [google domains](https://cloud.google.com/domains/docs/delete-domain) within the account of the deleter or owner of the SA who completed the operation. There is currently no way to import the domain back into Cloud Domains. Work in progress to allow importing it back but it likely wouldn't be able to be a terraform native operation.

**Comment by rileykarson** [comment]
We've talked with the product team internally about Terraform support for a domain registration resource, and have elected not to move forward with it at this time based on ambiguity about how we'd manage the pricing information in the registration, and concerns on their end about the dangerousness of Terraform. And, uh, a whole laundry list of issues below:

* There are additional difficulties wrt. deletion, as the account who deletes a domain becomes its owner when it falls into Google Domains. Given we expect most companies to run the provider as a service account, that means that a service account will be the sole owner of the domain- requiring a support ticket to recover.

* Testing up to the normal standards of the provider would mean burning multiple domains a night at pretty high cost, but that's our problem and not a user-facing one 🙂 

* Many actions are done through custom RPCs that can be hard to map into Terraform- retrieving registration parameters as discussed above, as well as some RPCs that have to do with authorization and transfer that I'm not sure make sense in Terraform or not

* The API normalises values, contacts in particular, that tend to be a big pain for Terraform when calculating diffs. In particular we're unable to systematically tell apart alternate forms of an email address, and they'll always return the canonical form. Think the gmail rules, where `foobar@gmail.com` and `Foo.BaR+baz@gmail.com` map to the same canonical value (generally-but-not-always `foobar@gmail.com`).

They mentioned that managing DNS settings and contacts are something that they thought made sense to be managed in Terraform for their service, and I'd bet the same is true of management settings. Given those are [separate RPCs](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations) it'd be possible to manage them as separate Terraform resources, `google_domains_registration_management_settings`, `google_domains_registration_contact_settings`, and `google_domains_registration_dns_settings`. We'd accept feature requests or contributions for breakouts of those if desired.

**Comment by melinath** [comment]
marking as upstream since this is an issue with the API implementation.

**Comment by bukzor-sentryio** [comment]
Looking at the API today, there's now an endpoint to transfer the "deleted" domain registration back from Google Domains back into Cloud Domains:

https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/import

**Comment by ScottSuarez** [comment]
There is still a lot of uncertainty around this. When we delete this with a SA where does the domain go? The SA's google domains? When recreating a resource we will be unable to understand that it was deleted and import it from the relevant location without a lot of high maintenance code.

If you have significant interest in this resource I would recommend engaging the google cloud support directly. There would have to be a significant priority and effort from the api team for declarative support. The api is not terraform friendly as is.

**Comment by wyardley** [comment]
Yes, one thing I've thought about is that managing DNS records in particular would be nice (the equivalent of `google_dns_record_set` etc. for the builtin DNS).
