### ISSUE TITLE
google_bigquery_dataset does not support roles/bigquery.dataEditor/Owner/Viewer despite them being aliases for WRITER/OWNER/READER, producing endless diffs

### ISSUE THREAD

**Issue by muscovitebob** [hashicorp/terraform-provider-google#7697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.20
+ provider.google v3.42.0
+ provider.google-beta v3.42.0
```

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "mydataset" {
  dataset_id    = "mydataset"
  friendly_name = "mydataset"
  description   = "My example dataset"
  location      = "EU"
  project       = "myproject"

  access {
    role          = "roles/bigquery.dataOwner"
    user_by_email = "myuser1@myproject.iam.gserviceaccount.com"
  }
  access {
    role          = "roles/bigquery.dataEditor"
    user_by_email =  "myuser2@myproject.iam.gserviceaccount.com"
  }
}
```

### Expected Behavior

No diff after repeated terraform apply.

### Actual Behavior

Diff is produced wherein terraform sees the BigQuery API return OWNER and WRITER roles for the above service accounts, respectively, despite the fact that these [are equivalent.](https://cloud.google.com/bigquery/docs/access-control-basic-roles#dataset-basic-roles)

### Steps to Reproduce

1. `terraform apply` the manifest given.
2. `terraform apply` again and see an unexpected diff.

### References

* Often intersects with https://github.com/hashicorp/terraform-provider-google/issues/3929

**Comment by upodroid** [comment]
Hi

Terraform is behaving as expected.

Have a look at the API documentation.

https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets

In `access[].role` it says the following:

This field will accept any of the above formats, but will return only the legacy format. For example, if you set this field to "roles/bigquery.dataOwner", it will be returned back as "OWNER"

Please ensure that you only use the legacy format.

Tables support the standard getIamPolicy/SetIamPolicy methods but datasets currently don't so you need to bear that in mind.
