### ISSUE TITLE
Add support for Google Virtual Network Interface (gVNIC)

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/compute/docs/instances/create-vm-with-gvnic

Will appear as the `networkInterfaces[].nicType` field, which doesn't currently appear in the docs

### New or Affected Resource(s)

* google_compute_instance

### Potential Terraform Configuration

```tf
  network_interfaces {
    ...

    nic_type = "GVNIC"
  }
```

### References

* b/171435195 (internal)

**Comment by upodroid** [comment]
This doesn't exist in the generated go client yet.

https://raw.githubusercontent.com/googleapis/google-api-go-client/master/compute/v0.beta/compute-gen.go and search for "type NetworkInterface"

Also:

- We need to add GVNIC to this enum too:
https://github.com/GoogleCloudPlatform/magic-modules/blob/6c09b5a5a9a9cff255cd074f433d4d446c24c705/products/compute/api.yaml#L5547 
- Amend the Instance Template as well.

https://pkg.go.dev/google.golang.org/api/compute/v0.beta#NetworkInterface

**Comment by rileykarson** [comment]
Moving into Sprint 26 for the assignee to re-investigate. We can move this back out if it's still not available.

**Comment by edwardmedia** [comment]
Using pre-configured images works (like below)

```tf
  boot_disk {
    initialize_params {
      image = "beta/projects/gvnic-vm-image-prod/global/images/family/debian-9-gvnic"
    }
  }
```

**Comment by rileykarson** [comment]
note: I filed this issue describing a part of the upcoming GA API. We need to ensure we can enable gvnic under `guestOsFeatures[].type`.

**Comment by rileykarson** [comment]
@edwardmedia: The instance part of this API should be available now. When you have the chance, mind giving it a try?
