### ISSUE TITLE
No option to select different service account for node pool

### ISSUE THREAD

**Issue by Muhamed-Hamid** [hashicorp/terraform-provider-google#7700]
When creating a new cluster under composer with custom service account, then associate a new node pool, it takes the default gke service account which brings access denied when trying to use this pool from composer. The option is available from google api but not available in tf.

**Comment by edwardmedia** [comment]
@Muhamed-Hamid can you post your config code and then explain what you are trying to do?

**Comment by Muhamed-Hamid** [comment]
@edwardmedia You can find the below, it creates a node pool under my composer gke cluster, but doesn't have the same service account, instead it takes the default and i can't specify the service account in "google_container_node_pool". This results the no jobs can run from composer over this node pool. 

```
resource "google_container_node_pool" "pricing" {
  name                   = "${var.name}-${var.env}"
  cluster                = basename(google_composer_environment.pricing.config.0.gke_cluster)
  location               = var.zone
  autoscaling  {
    min_node_count       = 1
    max_node_count       = 4
  }
  node_config  {
    preemptible          = true
    machine_type         = var.pipeline-machine
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
  management  {
    auto_upgrade        = true
    auto_repair         = true
  }
} 
```

**Comment by Muhamed-Hamid** [comment]
Sorry, you can close it. i found in the cluster details
