### ISSUE TITLE
Error 400 when updating a google_spanner_instance's config

### ISSUE THREAD

**Issue by quentinms** [hashicorp/terraform-provider-google#7732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.46.0
+ provider.google-beta v3.46.0
```

### Affected Resource(s)

* google_spanner_instance

### Terraform Configuration Files

Current config:
```tf
resource "google_spanner_instance" "test" {
  project      = "project"
  name         = "qms-test"
  config       = "regional-us-east1"
  display_name = "QMS Test"
  num_nodes    = 1
}
```

New config I want to apply (update `config`):
```tf
resource "google_spanner_instance" "test" {
  project      = "project"
  name         = "qms-test"
  config       = "nam11"
  display_name = "QMS Test"
  num_nodes    = 1
}
```

### Debug Output

https://gist.github.com/quentinms/fb986ab0dbc83faf5c8b5edc8d50dace

### Panic Output

N/A 

### Expected Behavior

Terraform should have updated spanner's config in-place.
(Or maybe it should recreate the instance, it's not clear to me if changing the `config` is allowed, it's not exposed in the UI)

### Actual Behavior

**Apply Error**

```
Error: Error updating Instance "xxx/qms-test": googleapi: Error 400: Invalid UpdateInstance request.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Must specify a non-empty field mask.",
        "field": "field_mask"
      }
    ]
  }
]
```

### Steps to Reproduce

1. Create a spanner instance

```tf
resource "google_spanner_instance" "test" {
  project      = "project"
  name         = "test"
  config       = "regional-us-east1"
  display_name = "test"
  num_nodes    = 1
}
```

2. Plan & Apply

3. Update the instance's config

```tf
resource "google_spanner_instance" "test" {
  project      = "project"
  name         = "test"
  config       = "nam11"
  display_name = "test"
  num_nodes    = 1
}
```

4. Plan

```
Terraform will perform the following actions:

  # google_spanner_instance.muybridge will be updated in-place
  ~ resource "google_spanner_instance" "test" {
      ~ config       = "projects/project/instanceConfigs/regional-us-east1" -> "nam11"
        display_name = "Muybridge"
        id           = "project/test"
        labels       = {}
        name         = "test"
        num_nodes    = 1
        project      = "project"
        state        = "READY"
    }
```

5. Apply

```
Error: Error updating Instance "project/test": googleapi: Error 400: Invalid UpdateInstance request.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Must specify a non-empty field mask.",
        "field": "field_mask"
      }
    ]
  }
]
```

### Important Factoids

N/A

**Comment by edwardmedia** [comment]
@quentinms can you share the debug log?

**Comment by quentinms** [comment]
@edwardmedia Added [a gist](https://gist.github.com/quentinms/fb986ab0dbc83faf5c8b5edc8d50dace) to the issue description.

**Comment by slevenick** [comment]
I can reproduce this, and the issue is that `config` is not added to the fieldMask under any circumstances. I think that is intentional though, as when I add it to the fieldMask I get the following error: `Error 501: Changing the configuration of an existing instance is not supported.`

Other than the interesting choice of error code #, I think updating `config` is not supported and what we actually want to happen is that the instance is recreated. Does that sound like what you want to do, or is there a reason you think you can update the config in-place?

**Comment by quentinms** [comment]
Recreating the instance sounds good. I was actually surprised when I first planned that it would update in-place.
