### ISSUE TITLE
Uptime config keeps re-creating whenever deploy is done

### ISSUE THREAD

**Issue by Dhanabalan-pop** [hashicorp/terraform-provider-google#7734]
resource "google_monitoring_uptime_check_config" "https" {
  project     = myproject
  display_name = "Uptime check"
  timeout = "10s"
  period = "60s"

  http_check {
    path = "/"
    port = "443"
    use_ssl = true
    validate_ssl = true
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      host = "myhost"
    }
  }
   lifecycle {
    create_before_destroy = true
    prevent_destroy = true
  }
}

Uptime keeps destoryed and created whenever code is deployed. Why is this issue?

**Comment by edwardmedia** [comment]
Yes, I can repro it.

**Comment by slevenick** [comment]
I think what is happening here is that there is a label being added to the `monitored_resource.labels` by the API. In our examples this is shown being set to the project id: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_uptime_check_config#example-usage---uptime-check-config-https

If you add this `project_id` label does it fix the issue for you?

Like this:
```
monitored_resource {
  type = "uptime_url"
  labels = {
    project_id = "your-project-id"
    host = "myhost"
  }
}
```

**Comment by Dhanabalan-pop** [comment]
thanks..it works after adding project_id under labels
