### ISSUE TITLE
google_compute_interconnect_attachment - updating bandwidth is replacing resources

### ISSUE THREAD

**Issue by cloudryder** [hashicorp/terraform-provider-google#7738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.46.0
+ provider registry.terraform.io/hashicorp/google-beta v3.46.0
+ provider registry.terraform.io/hashicorp/null v3.0.0

### Affected Resource(s)

* google_compute_interconnect_attachment

### Terraform Configuration Files (if applicable)

I have the following config in the module
```tf
resource "google_compute_interconnect_attachment" "att" {
  project           = var.project_id
  interconnect      = "https://www.googleapis.com/compute/v1/projects/${var.interconnect_project}/global/interconnects/${var.interconnect_name}"
  name              = "att-${data.google_compute_router.router.name}-${var.interconnect_shortname}"
  router            = data.google_compute_router.router.self_link
  candidate_subnets = var.candidate_subnets
  vlan_tag8021q     = var.bgp_vlan_id
  region            = var.interconnect_attachment_region
  admin_enabled     = true
  bandwidth         = var.interconnect_attachment_bandwidth

  lifecycle {
    ignore_changes = [
      candidate_subnets,
      region,
    ]
  }
}
```

Calling the module as below

```
module "interconnect1" {
  source = "../tf-module-gcp-network/modules/interconnect_attachment"
  project_id                        = var.project_id
  network_name                      = module.mgmtvpc.network_name
  router_name                       = rtr.name
  interconnect_name                 = "icx"
  interconnect_shortname            = "icx"
  interconnect_project              = "icx-project"
  interconnect_attachment_region    = "us-west2"
  interconnect_attachment_bandwidth = "BPS_50G"
  candidate_subnets                 = ["x.x.x.x/x"]
  bgp_vlan_id                       = "1234"
  bgp_peer_asn                      = 65400
}
```

### Issue Description

Resource is trying to replace the resource instead of just updating the Bandwidth.

```
-/+ resource "google_compute_interconnect_attachment" "att" {
        admin_enabled              = true
      ~ bandwidth                  = "BPS_10G" -> "BPS_50G" # forces replacement
        candidate_subnets          = [
            "x.x.x.x/x",
        ]
```

### References

* #0000

**Comment by edwardmedia** [comment]
@cloudryder this is be design. Why do you think it should not recreate the resource?

**Comment by cloudryder** [comment]
> @cloudryder this is be design. Why do you think it should not recreate the resource?
Thanks for the response @edwardmedia . From the GCP Console we can edit the attachment to update the speed by increasing or decreasing it, without having to recreate the attachment.

Also, API reference
https://cloud.google.com/compute/docs/reference/rest/v1/interconnectAttachments/patch

**Comment by edwardmedia** [comment]
I see 
https://github.com/hashicorp/terraform-provider-google/blob/a4fd4d854cf6e0808a79c38f157631419dcd95e7/google/resource_compute_interconnect_attachment.go#L99

**Comment by slevenick** [comment]
This is an enhancement request rather than a bug
