### ISSUE TITLE
Fix TestAccFilestoreInstance* tests

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7750]
Getting a ` After applying this test step, the plan was not empty.` error for these tests. Looks like a diff remains in `file_shares`

**Comment by melinath** [comment]
It looks like the API is returning nfsExportOptions, which was not set by terraform. It seems like probably a new default returned by the API.

**Comment by melinath** [comment]
b/173061584 TLDR a default that was already being set is now also being returned by the API.

**Comment by melinath** [comment]
Should be on track to be resolved today.

**Comment by melinath** [comment]
These tests are now succeeding. See bug for detailed rollout.
