### ISSUE TITLE
google_storage_transfer_job -- notification_config field

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#7775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We'd like to request support for a `notification_config` field in `google_storage_transfer_job` to more closely reflect the API's [TransferJob](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs) resource which supports a ` notificationConfig` field.

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_storage_transfer_job" "transfer-job" {
    description = "Sample storage transfer job"
    transfer_spec {
        gcs_data_sink {
            bucket_name = "my-sink-bucket"
        }
        gcs_data_source {
            bucket_name = "my-source-bucket"
        }
    }
    schedule {
        schedule_start_date {
            year    = 2020
            month   = 1
            day     = 1
        }
    }
    notification_config {
        pubsub_topic = "projects/my-project/topics/my-topic"
        event_types = ["TRANSFER_OPERATION_SUCCESS", "TRANSFER_OPERATION_FAILED"]
        payload_format = "JSON"
   }
}
```

### References

* https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/303

**Comment by ct-dh** [comment]
Any update on when this might be implemented? It seems a fairly small change in magic modules that would be quick to implement.

**Comment by hao-nan-li** [comment]
b/245746513
