### ISSUE TITLE
Google Cloud Run update image after creation

### ISSUE THREAD

**Issue by sulantha2006** [hashicorp/terraform-provider-google#7779]
I am trying to use Cloud Run with ESP V2. This requires me to

1. Reserve a cloud run address by deploying a dummy cloud run instance.
2. Use the address and API spec file to build an endpoints container image
3. Update the service created at step 1 with the image created at step 2.

Extra details are https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run#reserve_hostname

Can you suggest a way to implement this using Terraform? I don't mind during this in two steps (having two terraform configurations). But I am not sure how to update an existing instance without creating it in the same terraform config. (the second one tries to recreate it).

Any help is highly appreciated.

**Comment by edwardmedia** [comment]
@sulantha2006 I don't think you can do it. Terraform maintains one state.  What you are trying to do seems involving multiple states, which is against TF pattern. Does this make sense to you?

**Comment by sulantha2006** [comment]
Yes. I figured it, just wanted to know if there is a workaround. 

So the only way to achieve this is to do step 1 with TF and 2,3 with an external script. I also will have to add disregard_modifications to step 1. Thank you.
