### ISSUE TITLE
Ensure that GoogleCloudPlatform/terraform-google-conversion builds, automate building it

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7781]
We let tgc break, as seen with a PR like https://github.com/GoogleCloudPlatform/magic-modules/pull/4215 to fix it. We should ensure we've fixed it, and make sure that the Magician builds it so that we don't break it again in the future.

**Comment by melinath** [comment]
Terraform-google-conversion is being built by the Magician as of #4281. Looks like it's working.

Innocuous change: #4284
Bad change: #4285

Search logs for step #22
