### ISSUE TITLE
google_compute_organization_security_policy_rule creates permadiff on match description

### ISSUE THREAD

**Issue by cornmander** [hashicorp/terraform-provider-google#7790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.25
+ provider.google-beta v3.34.1

### Affected Resource(s)

* google_compute_organization_security_policy_rule

### Terraform Configuration Files

```tf
resource "google_compute_organization_security_policy_rule" "rule" {
  provider    = google-beta
  policy_id   = "locations/global/securityPolicies/123"
  description = "foo"
  priority    = 2147483645
  direction   = "INGRESS"
      match {
            description    = "match description"
            config {
                dest_ip_ranges = []
                src_ip_ranges  = [
                    "0.0.0.0/0",
                ]

                layer4_config {
                    ip_protocol = "tcp"
                    ports       = []
                }
            }
  }
  action                  = "deny"
  preview                 = false
  enable_logging          = true
  target_resources        = []
  target_service_accounts = []
}
```

### Expected Behavior

No diff should be generated.

### Actual Behavior

A diff is generated on the nested rule description:

      ~ match {
          + description    = "in_tcp_deny_all"
            versioned_expr = "FIREWALL"

            config {
                dest_ip_ranges = []
                src_ip_ranges  = [
                    "0.0.0.0/0",
                ]

                layer4_config {
                    ip_protocol = "tcp"
                    ports       = []
                }
            }
        }

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` or `terraform apply`

**Comment by edwardmedia** [comment]
@cornmander can you share the debug log for `terraform plan`?

**Comment by edwardmedia** [comment]
@cornmander is this still an issue?

**Comment by edwardmedia** [comment]
Closing this as assuming this is no longer an issue

**Comment by soulmanos** [comment]
I've been testing this resource today, and I'm seeing this exact issue.

`terraform plan` will always result in an output of `Plan: 0 to add, 1 to change, 0 to destroy.` even after apply.

```
google_compute_organization_security_policy_rule.deny_ssh_rdp_internet_ingress will be updated in-place
...
      ~ match {
          + description    = "deny ssh, rdp and icmp"
            versioned_expr = "FIREWALL"

            config {
                dest_ip_ranges = []
                src_ip_ranges  = [
                    "0.0.0.0/0",
                ]

                layer4_config {
                    ip_protocol = "tcp"
                    ports       = [
                        "22",
                    ]
                }
                layer4_config {
                    ip_protocol = "tcp"
                    ports       = [
                        "3389",
                    ]
                }
                layer4_config {
                    ip_protocol = "icmp"
                    ports       = []
                }
            }
        }
    }
```

```
provider "google" {
  version     = "~> 3.50.0"
  credentials = file("./.json")
}

provider "google-beta" {
  version     = "~> 3.50.0"
  credentials = file("./.json")
}
```
