### ISSUE TITLE
Add support for new cdnPolicy settings in google_compute_backend_service (beta)

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

These features are collectively "Flexible Cache Control". https://cloud.google.com/compute/docs/reference/rest/beta/backendServices

### New or Affected Resource(s)

* google_compute_backend_service

### Potential Terraform Configuration

```tf
  cdn_policy {
    cache_mode = "CACHE_ALL_STATIC"
    default_ttl = 7200
  }
```

### References

* https://github.com/hashicorp/terraform-provider-google/issues/7780
* b/168035584

**Comment by upodroid** [comment]
Also, the region_backend_service needs the same fields updated too.

https://cloud.google.com/compute/docs/reference/rest/beta/regionBackendServices

Copy & paste the diff from https://github.com/GoogleCloudPlatform/magic-modules/pull/4261

IDM doing it
