### ISSUE TITLE
Merge in actual IAM policy bindings in terraform-google-conversion

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7797]
See b/172575813 for details. It's valuable for Terraform Validator to be able to compare policies against full changes to IAM instead of individual memberships or bindings.

Mappers to update: 
- [x] Project https://github.com/GoogleCloudPlatform/terraform-validator/pull/180
- [x] Storage Bucket https://github.com/GoogleCloudPlatform/magic-modules/pull/4618 https://github.com/GoogleCloudPlatform/terraform-validator/pull/207
- [x] Folder https://github.com/GoogleCloudPlatform/magic-modules/pull/4616 https://github.com/GoogleCloudPlatform/terraform-validator/pull/208
- [x] Organization https://github.com/GoogleCloudPlatform/magic-modules/pull/4618 https://github.com/GoogleCloudPlatform/terraform-validator/pull/208

Not actually IAM:
- [x] ~Project Organization Policy~

**Comment by melinath** [comment]
Is the expectation for this ticket that I should essentially pull in the terraform provider and use its client configuration code? Or that I would assume (for now) that the user has a basic setup with common env vars set, and instantiate the api client(s) necessary using that information if available?

I think the full configuration code couldn't easily be copied over, but I could potentially copy over config.go.

If there is some other best practice, that would also be great to know!

**Comment by rileykarson** [comment]
Spoke offline, but where I believe we ended up is that Validator already has access to creds, and passes a Config object through to tgc. We should be able to pull a client out of the Config object and make requests. Does that sound right?

**Comment by melinath** [comment]
Yes, that's where we ended up. The Config available in tgc should support creating an appropriate client.

**Comment by melinath** [comment]
This is blocked by https://github.com/GoogleCloudPlatform/terraform-validator/issues/158

**Comment by melinath** [comment]
In case this is useful to future people: config.go (which provides Config) is copied over to tgc by `magic-modules/provider/terraform_object_library.rb`)

**Comment by melinath** [comment]
Doc laying out the plan: https://docs.google.com/document/d/1_FDdCuqs3hpaceZRXnKfJJ0VgdsJzuKYsmOEA0AZIi8/edit#

**Comment by melinath** [comment]
It turns out that terraform validator currently doesn't work with folders or organizations (or their associated policies) - basically, it always assumes that resources will be related to a specific project with a known id.

- https://github.com/GoogleCloudPlatform/terraform-validator/issues/150
- https://github.com/GoogleCloudPlatform/terraform-validator/issues/145
- https://github.com/GoogleCloudPlatform/terraform-validator/issues/42

We will need to fix those prior to being able to merge those iam bindings.

**Comment by melinath** [comment]
I've opened https://github.com/GoogleCloudPlatform/terraform-validator/issues/206 to track the folder/organization issue centrally as a persistent bug rather than each of the smaller issues.

**Comment by melinath** [comment]
Resolved as of 811d32c
