### ISSUE TITLE
Datastore index fails to create after 21 retries

### ISSUE THREAD

**Issue by justyns** [hashicorp/terraform-provider-google#7799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Discovered issue using:

```
➜ terraform -v
Terraform v0.12.19
+ provider.google v3.15.0
```

Also tested the issue with these versions and ran into the same error:

```
➜ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.47.0
```

### Affected Resource(s)

* google_datastore_index

### Terraform Configuration Files

```tf
provider "google" {
  version = "= 3.47.0"
  project = local.project
  region  = "us-west1"
  zone    = "us-west1-a"
}

resource "google_datastore_index" "foo4" {
  kind = "foo4"
  properties {
    name = "property_a"
    direction = "ASCENDING"
  }
  properties {
    name = "property_b"
    direction = "ASCENDING"
  }

  timeouts {
    create = "1h"
    delete = "1h"
  }
}
```

### Debug Output

I would need to scrub the full debug output to post it here (to make sure it doesn't have project ids/etc), but let me know if it is needed.  This shows the last get request before it gives up:  https://gist.github.com/justyns/57d8af0a59c6364d8546558b609e9cda (the operation id has been replaced with `xxx`, but the operation id it tries to retrieve is the same as the one it receives from the initial create request.  I can also do `gcloud datastore operations describe xxx` and see output for the operation.)

### Expected Behavior

Terraform should create the datastore index, wait for it to be created, and then return successfully.

### Actual Behavior

Terraform sends the request to create the datastore index, waits approximately 3m30s and then fails with this error:

```
google_datastore_index.foo: Still creating... [3m20s elapsed]

Error: Error waiting to create Index: Error waiting for Creating Index: couldn't find resource (21 retries)

  on datastore.tf line 9, in resource "google_datastore_index" "foo":
   9: resource "google_datastore_index" "foo" {
```

**Note**: If I try re-running the same terraform module after a minute or two, it fails saying the index already exists:

```
google_datastore_index.foo: Creating...

Error: Error creating Index: googleapi: Error 409: index already exists

  on datastore.tf line 9, in resource "google_datastore_index" "foo":
   9: resource "google_datastore_index" "foo" {
```

If I check in the gcp console or with `gcloud datastore indexes list`, I do see the index as succesfully created.  If I check immediately after terraform fails, it's usually still in "Indexing" status.  It switches to "Serving" after another minute or so.

### Steps to Reproduce

1. Copy example tf above
1. Replace provider config with a project you have access to
1. `terraform init`
1. `terraform apply`
1. TF will probably error out
1. Check the GCP console to see if the index was actually created
1. Run `terraform apply` again to see the `index already exists` error.

### Important Factoids

- Indexes **do get created**, but terraform does not wait long enough for their creation
- AFAICT TF does not wait long enough because it's getting a 404 when trying to look up the operation
- Setting the timeout values do not appear to affect this
- The same code and tf/provider versions used to work in the same environment recently

**Comment by edwardmedia** [comment]
I see the same bahavior

**Comment by rileykarson** [comment]
@justyns: Mind checking if this is still happening? I'm not seeing it- I wonder if the API was having trouble returning operations in time a few days ago.

**Comment by justyns** [comment]
Thanks @rileykarson  - I just tried the example code in my post again and it is working fine now with no changes:

```
google_datastore_index.foo5: Creation complete after 4m42s [id=projects/test-project/indexes/xxx]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

So I think you're right that it was probably a temporary API issue. 

Is it worth changing the logic in the provider to use a different api to check the status of the index (instead of relying on the operation status), or to fallback to checking the index status if the operation id can't be found?

Also FWIW, I could do `gcloud datastore operations describe <operation id>` the other day and got a result back.  I have not checked if that uses a different api call than `/v1/projects/project-id/operations/operation-id?alt=json` that TF uses.

**Comment by dskdas** [comment]
issue happened multiple times for me today. i had to eventually do a terraform import of the datastore indexes to allow me to continue.

**Comment by rileykarson** [comment]
If either of you are able to capture debug logs, I'd be interested in seeing what the create request prior to the operation GET that 404's looks like. That should be the request right before https://gist.github.com/justyns/57d8af0a59c6364d8546558b609e9cda#file-datastore-index-fail-to-create-log-L8 in the original gist.

I've tried to repro this a few more times, and it hasn't failed for me yet.

**Comment by edwardmedia** [comment]
I have tried several times today, none were failed. Likely this is a temporally api issue.  I am closing the issue then. @dskdas @justyns if you still see exception happens, please reopen this and share the debug logs. Thanks
