### ISSUE TITLE
Google API Service Account problem

### ISSUE THREAD

**Issue by antoinecastex** [hashicorp/terraform-provider-google#7800]
Hello

Just have discovered something wrong happening when i create my project with TF

In the same time i also enable APIs like Compute ou Cloud Build

That mean in the same time the Service Account of each API is created automatically and managed by Google

That's work 

But normally the last step is the IAM part, i mean Cloud Build SA needs to be Cloud Build Service Account

And that's not the case

I don"t know why but  all the service account doesn't have their permissions assigned, meaning after that if i'm going to cloud build and try to use it, i got an error ....

I go to IAM add the SA manually and now everything is working

Someone is aware about that ?

How to solve ?

Thanks

**Comment by edwardmedia** [comment]
@antoinecastex can you share your Terraform config?

**Comment by antoinecastex** [comment]
Yes


terraform {
backend "gcs" {
bucket = "xxx"
}
}
variable "PROJECT_ID" {
description = "Project ID"
type = string
}
variable "BUDGET_PROJECT_ID" {
description = "Project ID for the Budget"
type = string
}
variable "PROJECT_NAME" {
description = "Project name"
type = string
}
variable "FOLDER_ID" {
description = "Folder ID of the project"
type = string
}
variable "BILLING_ACCOUNT" {
description = "Billing Account ID"
type = string
}
variable "HOST_PROJECT" {
description = "Shared VPC host project"
type = string
}
variable "BUDGET_THRESHOLD" {
description = "Threshold of the monthly budget alert of the project"
type = string
}
variable "BUDGET" {
description = "Monthly budget of the project"
type = string
}
variable "QUOTA_SERVICE" {
description = "API Service to modify Quota"
type = string
}
variable "QUOTA_METRIC" {
description = "Quota Metric to modify"
type = string
}
variable "QUOTA_LIMIT" {
description = "Quota Limit to modify"
type = string
}
variable "BQ_QUOTA" {
description = "Quota to set for BQ Daily Query"
type = string
}
variable "ROLE" {
description = "List of role to give in IAM"
type = list(string)
}
variable "USER_PERMISSION" {
description = "List of people to authorize in IAM"
type = list(string)
}
variable "LABELS" {
description = "Set of key/value label pairs to assign to the project"
type = map(any)
}
variable "APIS" {
description = "List of apis to enable"
type = list(string)
}
variable "USECASE" {
description = "Request for Sandbox or not"
type = bool
}
variable "BUDGET_PUBSUB" {
description = "Project and Topic for Budget Notifications"
type = string
}
variable "BUDGET_CHANNEL" {
description = "Project and Channel for Budget Notifications by Email"
type = string
}
variable "DEVISE" {
description = "Devise du billing account"
type = string
}
resource "google_project" "project" {
provider = google-beta
name = var.PROJECT_NAME
project_id = var.PROJECT_ID
folder_id = var.FOLDER_ID
billing_account = var.BILLING_ACCOUNT
labels = var.LABELS
auto_create_network = false
}
resource "google_project_service" "service_default" {
provider = google-beta
service = "cloudapis.googleapis.com"
project = var.PROJECT_ID
depends_on = [
google_project.project
]
}
resource "google_project_service" "service" {
provider = google-beta
for_each = toset(var.APIS)
service = each.key
project = var.PROJECT_ID
disable_on_destroy = false
depends_on = [
google_project_service.service_default
]
}
resource "google_billing_budget" "budget" {
provider = google-beta
billing_account = var.BILLING_ACCOUNT
display_name = var.PROJECT_ID
budget_filter {
projects = [var.BUDGET_PROJECT_ID]
}
amount {
specified_amount {
currency_code = var.DEVISE
units = var.BUDGET
}
}
threshold_rules {
threshold_percent = var.BUDGET_THRESHOLD
spend_basis = "CURRENT_SPEND"
}
threshold_rules {
threshold_percent = 1.0
spend_basis = "CURRENT_SPEND"
}
all_updates_rule {
pubsub_topic = var.BUDGET_PUBSUB
monitoring_notification_channels = [var.BUDGET_CHANNEL]
}
depends_on = [
google_project_service.service
]
}
resource "google_project_iam_binding" "project" {
provider = google-beta
project = var.PROJECT_ID
count = length(var.ROLE)
role = "roles/${element(var.ROLE, count.index)}"
members = var.USER_PERMISSION
depends_on = [
google_billing_budget.budget
]
}
resource "google_compute_shared_vpc_service_project" "service" {
count = var.USECASE ? 1 : 0
provider = google-beta
host_project = var.HOST_PROJECT
service_project = var.PROJECT_ID
depends_on = [
google_project_iam_binding.project
]
}
resource "google_project_iam_binding" "project_host" {
count = var.USECASE ? 1 : 0
provider = google-beta
project = var.HOST_PROJECT
role = "roles/compute.networkUser"
members = var.USER_PERMISSION
depends_on = [
google_compute_shared_vpc_service_project.service
]
}
resource "google_service_usage_consumer_quota_override" "override" {
provider = google-beta
dimensions = {}
project = var.PROJECT_ID
service = var.QUOTA_SERVICE
metric = var.QUOTA_METRIC
limit = var.QUOTA_LIMIT
override_value = var.BQ_QUOTA
force = true
depends_on = [
google_project_iam_binding.project
]
}

**Comment by edwardmedia** [comment]
@antoinecastex what service account(s) are you talking about? I see you have `google_project_iam_binding` and do you have other **iam policy* for each resource? Following is the iam resource example for compute instance. 

```
I go to IAM add the SA manually and now everything is working
```

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_iam

**Comment by antoinecastex** [comment]
@edwardmedia  i'm talking about SA of Cloud Build for example

On my TF code as you can see i'm enabling some APIS , one of them is Cloud Build, and i'm also giving permission to the people who ask the project, that mean for Cloud Build they will be Cloud Build ADMIN OK ?

But the problem is that, when you enable the API of Cloud Build for example (you can try in the UI console) it create a SA for cloud build and ... it also give them permission in IAM

This last part is not done when the enabling of the API has been request throuf TF , and  i think there is a bug otherwise i have a problem in my code ?

thanks

**Comment by edwardmedia** [comment]
@antoinecastex I see what you mean now. What you needed is the IAM resources for Cloud Build, very much like the one I mentioned above for the compute instance. The IAM resources are separate. They are not created automatically when you create their corresponding resources. Unfortunately the Could Build IAM are not available yet. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?template=enhancement.md) so it be can triaged. I am closing it then. Feel free to reopen it if your question has not been addressed.
