### ISSUE TITLE
google_logging_project_sink does not work for automatically created sinks

### ISSUE THREAD

**Issue by matthewblain** [hashicorp/terraform-provider-google#7811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

> Terraform v0.13.5
> + provider registry.terraform.io/hashicorp/google v3.46.0
> + provider registry.terraform.io/hashicorp/google-beta v3.37.0

### Affected Resource(s)

* google_logging_project_sink

### Terraform Configuration Files

Elided config file:

```tf
resource "google_logging_project_sink" "log_sink" {
  name = "_Default"

  destination = vars.logging_bucket

  # While this is the default filter, it appears that it must be set explicitly.
  filter = <<-endfilter
    NOT LOG_ID("cloudaudit.googleapis.com/activity") AND 
    NOT LOG_ID("externalaudit.googleapis.com/activity") AND
    NOT LOG_ID("cloudaudit.googleapis.com/system_event") AND
    NOT LOG_ID("externalaudit.googleapis.com/system_event") AND
    NOT LOG_ID("cloudaudit.googleapis.com/access_transparency") AND
    NOT LOG_ID("externalaudit.googleapis.com/access_transparency")
  endfilter
}

```

### Debug Output

The error is this:

`googleapi: Error 409: Sink _Default already exists, alreadyExists`

Attached is a non-debug log: 
[elidedlog.txt](https://github.com/hashicorp/terraform-provider-google/files/5540241/elidedlog.txt)
 It should be enough info to understand this issue but I can provide the full version if necessary.

### Expected Behavior

The always-present logging sink should have been updated to point to the non-default bucket.

### Actual Behavior

Terraform attempted to create a new sink, which is not possible for _Default.

Note: I also experimented with importing the existing _Default sink, but that failed at the 'delete' stage.

`Error: googleapi: Error 403: Sink _Default cannot be deleted. Consider disabling instead, forbidden`

### Steps to Reproduce

1. `terraform apply`

### References

I am trying to use Terraform to accomplish the steps described here; bucket creation mostly worked but the sink part did not.
https://cloud.google.com/logging/docs/regionalized-logs

It looks like the google_logging_project_bucket_config (partly) address a similar issue by acquiring or creating a resource. See some discussion in issue #7587  

* #0000

**Comment by edwardmedia** [comment]
@matthewblain was this error from the first `terraform apply` or 2nd `apply`? If this is the first, did you run `terraform import`?

**Comment by matthewblain** [comment]
@edwardmedia  First apply fails with the 'create' error. After trying import... well it seems it can run in one of two paths, one seems to work! This may be less severe than I thought.

* Path one: The unique_writer_identity flag is different -> "~ unique_writer_identity = true -> false # forces replacement" -> failure on delete of _Default. See attached 
[elidedlog2.txt](https://github.com/hashicorp/terraform-provider-google/files/5541912/elidedlog2.txt)

 * Path two: If I set unique_writer_identity to true in the terraform module, it instead says "will be updated in-place" and works!

I guess I didn't notice the unique_writer_identity issue the first attempt after using import. I am not sure how I would have known the value of this property any way other than calling the API (or using Terraform) directly, as the UI and gcloud logging sink don't say anything one way or another.

At this point I'd say the bug is lower priority, and possibly just an error message issue
 * Somehow warn the user on _Default (or other singleton) sinks that they must run import, and cannot modify it in any way which 'forces replacement'.

**Comment by edwardmedia** [comment]
@matthewblain because the error was `alreadyExists`, that is why I asked if your run was 1st or 2nd apply. It does not make sense if that was 1st try. Your successful running `import` seems to prove that error message `alreadyExists` was correct. Does this make sense?  If you can repro the error message when you try to create a fresh resource, please post the debug log, and I can take a close look

**Comment by matthewblain** [comment]
@edwardmedia It happened on the first apply. 

The key here is that every Google Cloud project has several resources which always exist. That includes the `_Default` log sink. These resources can neither be created nor deleted. However, a number of properties on them can be changed, and thus it makes sense to be able to manage them with a tool like Terraform.

The other bug I referenced calls these `singleton` resources; 

What is the correct way to manage them with Terraform? Some ways I could imagine:
* Do it like `google_logging_project_bucket_config`. That is, simply adopt any existing resources if the user asks to 'create' them by adding it to the terraform configuration. 
* Keep current behavior of `google_logging_project_sink` . That is, fail on apply when apply attempts to create or delete one of these 'singleton' resources. Document that the user needs to run `import` after adding it to their terraform configuration, and `state rm` after removing it from their terraform configuration.  Note that I believe this means that running Terraform to create an entire cloud project from scratch presumably will fail on first apply, then require the user to run 'import' of the resource (which was created by but invisible to terraform), then re-run apply to ensure the setup is complete.
* Have Terraform know (via some mechanism) about 'singleton' resources and handle them differently. E.g. adopt instead of attempt to create; warn or error on delete; warn or error on a 'forced replacement' which would trigger a delete/create. Resources which are not 'known' as singleton resources continue to behave as today.

Ideally google_logging_project_bucket_config, google_logging_project_sink, and other Google Cloud resources would have similar behavior.

**Comment by edwardmedia** [comment]
I see. Change label to `enhancement` (reference the work https://github.com/hashicorp/terraform-provider-google/issues/7587)

**Comment by LipingSun** [comment]
When this enhancement can be implemented?

**Comment by estliberitas** [comment]
@LipingSun it's on the way, checkout a referenced PR above.

**Comment by pankajmt** [comment]
@estliberitas guess you will be updating this thread when you have a new simplified PR?

**Comment by estliberitas** [comment]
@pankajmt can do ;)

**Comment by pankajmt** [comment]
Many thanks :)

**Comment by YawningCobra8** [comment]
Hi @matthewblain or @estliberitas, are there any updates on this?

**Comment by sherbang** [comment]
For anyone else with this issue:
You can change your Organization default to [disable the _Default sink](https://cloud.google.com/logging/docs/default-settings#disable-default-sink) on new projects.  Then you can use Terraform to create/manage a different sink, and pretend the _Default one doesn't exist.  Note: this will not update your existing projects.

I'm sure there are many use-cases that this will not be appropriate for, but it's an acceptable workaround for me (far better than crashing-out, then importing, then retrying).

**Comment by xinyusun1997** [comment]
Hi, is there any update on this issue?

**Comment by ScottSuarez** [comment]
A datasource may be better to manage the default sink

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/logging_sink

**Comment by code-ape** [comment]
Hello all, I'm encountering this same conundrum. @ScottSuarez, I see you posted a bit over a month ago that using the `google_logging_sink` data source may be a better option, could you expand on that? I'm in need of making a change to the `_Default` Log Sink and trying to find how to do this given the current module's capabilities. Thanks!

**Comment by shulai** [comment]
While I would strongly prefer being able to handle natively in Terraform, I could do a workaround using a `null_resource` to run the required `gcloud` commands:
```
resource "null_resource" "default_sink_disable_logging" {

 triggers = {
    project     = google_project.gtm.project_id
  }

  provisioner "local-exec" {
    command     = <<-EOT
    gcloud auth login --cred-file=./credentials.json
    gcloud config set project ${google_project.gtm.project_id}
    gcloud logging sinks update _Default --project=${google_project.gtm.project_id} --log-filter='NOT LOG_ID("cloudaudit.googleapis.com/activity") AND NOT LOG_ID("externalaudit.googleapis.com/activity") AND NOT LOG_ID("cloudaudit.googleapis.com/system_event") AND NOT LOG_ID("externalaudit.googleapis.com/system_event") AND NOT LOG_ID("cloudaudit.googleapis.com/access_transparency") AND NOT LOG_ID("externalaudit.googleapis.com/access_transparency")
    NOT LOG_ID("appengine.googleapis.com/nginx.request") AND NOT LOG_ID("appengine.googleapis.com/request_log")'
    EOT
  }
}
```

**Comment by Evesy** [comment]
Starting in Terraform 1.5 you can now define imports as part of the Terraform configuration, so it should be possible to manage the default sinks with something akin to the below (not tested):

```hcl
import {
  to = google_logging_project_sink.default
  id = "projects/${var.project}/sinks/_Default"
}

resource "google_logging_project_sink" "default" {
  name = "_Default"
  project = var.project
  destination = "logging.googleapis.com/projects/${var.project}/locations/global/buckets/_Default"
  filter = "NOT LOG_ID(\"cloudaudit.googleapis.com/activity\") AND NOT LOG_ID(\"externalaudit.googleapis.com/activity\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"externalaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/access_transparency\") AND NOT LOG_ID(\"externalaudit.googleapis.com/access_transparency\")"

  unique_writer_identity = true
}
```

**Comment by pawelczuczwara** [comment]
> While I would strongly prefer being able to handle natively in Terraform, I was able to do a workaround using a `null_resource` to run the required `gcloud` commands:
> 
> ```
> resource "null_resource" "default_sink_disable_logging" {
> 
>  triggers = {
>     project     = google_project.gtm.project_id
>   }
> 
>   provisioner "local-exec" {
>     command     = <<-EOT
>     gcloud auth login --cred-file=./credentials.json
>     gcloud config set project ${google_project.gtm.project_id}
>     gcloud logging sinks update _Default --project=${google_project.gtm.project_id} --log-filter='NOT LOG_ID("cloudaudit.googleapis.com/activity") AND NOT LOG_ID("externalaudit.googleapis.com/activity") AND NOT LOG_ID("cloudaudit.googleapis.com/system_event") AND NOT LOG_ID("externalaudit.googleapis.com/system_event") AND NOT LOG_ID("cloudaudit.googleapis.com/access_transparency") AND NOT LOG_ID("externalaudit.googleapis.com/access_transparency")
>     NOT LOG_ID("appengine.googleapis.com/nginx.request") AND NOT LOG_ID("appengine.googleapis.com/request_log")'
>     EOT
>   }
> }
> ```

It is much safer to give gcloud credentials used by the provider, accessed by
data.google_client_config... than store credentials in the file.

```terraform
resource "null_resource" "example" {
  triggers = {
    project     = google_project.gtm.project_id
  }
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    environment = {
      CLOUDSDK_AUTH_ACCESS_TOKEN = data.google_client_config.current.access_token
    }
    command = "gcloud logging sinks update _Default --project=..."
  }

}
```

**Comment by olejorgenb** [comment]
Can someone explain how to run the import command. It's not really clear which IDs to use?

[id](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink.html#id) - an identifier for the resource with format `projects/{{project}}/sinks/{{name}}`

```
Usage: terraform [global options] import [options] ADDR ID

  The ADDR specified is the address to import the resource to. Please
  see the documentation online for resource addresses. The ID is a
  resource-specific ID to identify that resource being imported. Please
  reference the documentation for the resource type you're importing to
  determine the ID syntax to use. It typically matches directly to the ID
  that the provider uses.

$ terraform import google_logging_project_sink.my_sink projects/my-project/sinks/my-sink
```

The only identifier available in the GCP UI is the sink location and name. "logging.googleapis.com/projects/<project-id>/locations/global/buckets/_Default` / `_Default`

**Comment by ledmonster** [comment]
Can we close the issue?
I could configure with `import` block.
