### ISSUE TITLE
IAM ressource for Google APIs enabled

### ISSUE THREAD

**Issue by antoinecastex** [hashicorp/terraform-provider-google#7814]
Following my problem

https://github.com/hashicorp/terraform-provider-google/issues/7800#issuecomment-727515474

The action which is : give specific permission to the SA created by the API when you enable it, is not done when you do everything throug TF

Specially Cloud Build

Enabling API of CB with TF , create the SA, but the SA has not the appriopriate permissions automatically assigned ..

**Comment by edwardmedia** [comment]
@antoinecastex when you enable Cloud Build, gcp created the `<project_id>@cloudbuild.gserviceaccount.com` for you. I guess it is the SA you are referring to. Did you say this SA does not have enough permissions? Can you be more specific what permissions are missing? I assume these permissions were assigned when you enable the API through other methods. Please provide steps so I can repro the issue.

**Comment by antoinecastex** [comment]
That's exactly the SA that i have in mind @edwardmedia 

SA does not have enough permission ... no he has NOTHING, he is not having any permissions .. that's the problem

Normally (you can reproduce that by enabling API CB in the Console) he would have Cloud Build Service Account Role ...

**Comment by edwardmedia** [comment]
@antoinecastex  can you post the terraform config code that you used to enable the CB api?

**Comment by antoinecastex** [comment]
The same as here https://github.com/hashicorp/terraform-provider-google/issues/7800#issuecomment-727515474

@edwardmedia  i giv an array with multiple apis to enable in this code during the project creation , and  lets gooo

nothing more !

**Comment by edwardmedia** [comment]
@antoinecastex I see your below code but no clue what services were you enabling. If you did successfully enable 
the API, it is up to the GCP service that assigns the necessary permissions to the default SA. At this moment, I am not convinced as that process is beyond Terraform provider. It is still possible the plugin handles inappropriately, that is why I need the details. Can you post the code explicitly along with your debug log?  

```
for_each = toset(var.APIS)
```

**Comment by antoinecastex** [comment]
Example for one the var.APIS value passed for the last project created 👍 ["bigquery.googleapis.com", "storage-component.googleapis.com", "cloudfunctions.googleapis.com", "run.googleapis.com", "datastore.googleapis.com", "dataflow.googleapis.com", "apigateway.googleapis.com", "appengine.googleapis.com", "sql-component.googleapis.com", "redis.googleapis.com", "storagetransfer.googleapis.com", "iap.googleapis.com", "dlp.googleapis.com", "workflows.googleapis.com", "sqladmin.googleapis.com", "bigquerystorage.googleapis.com", "storage-api.googleapis.com", "sqladmin.googleapis.com", "datacatalog.googleapis.com", "container.googleapis.com", "compute.googleapis.com", "serviceusage.googleapis.com", "iamcredentials.googleapis.com", "pubsub.googleapis.com", "storage-component.googleapis.com", "cloudbuild.googleapis.com", "monitoring.googleapis.com", "cloudresourcemanager.googleapis.com", "clouddebugger.googleapis.com", "logging.googleapis.com", "monitoring.googleapis.com", "cloudtrace.googleapis.com", "cloudtasks.googleapis.com", "cloudscheduler.googleapis.com", "sourcerepo.googleapis.com", "cloudkms.googleapis.com", "networkmanagement.googleapis.com", "iam.googleapis.com", "oslogin.googleapis.com", "resourceviews.googleapis.com", "servicemanagement.googleapis.com", "stackdriver.googleapis.com", "vpcaccess.googleapis.com"]



And here is the log of the full process done with this project today


Step #2: {"import_set":"ISET2244136","staging_table":"u_ad_task","result":[{"transform_map":"AD Task","table":"sc_task","display_name":"number","display_value":"TASK1161018","record_link":"https://loreal.service-now.com/api/now/table/sc_task/02296601db60a8509e3770a7f49619ef","status":"ignored","sys_id":"02296601db60a8509e3770a7f49619ef","status_message":"No field values changed"}]}
DONE
PUSH
Finished Step #2
100   592    0   375  100   217    454    263 --:--:-- --:--:-- --:--:--   456
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Step #2: 
Step #2:                                  Dload  Upload   Total   Spent    Left  Speed
Step #2:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #2: launcher.gcr.io/google/ubuntu1604:latest
Step #2: Status: Downloaded newer image for launcher.gcr.io/google/ubuntu1604:latest
Step #2: Digest: sha256:23dc29d9afa78c82d5024c32f6cfc317031f23a1b3b661ee4f0e83ab82a61ed4
Step #2: 3c2cba919283: Pull complete
Step #2: 998498404f9a: Pull complete
Step #2: ff83c3f26fa3: Pull complete
Step #2: ff83c3f26fa3: Download complete
Step #2: ff83c3f26fa3: Verifying Checksum
Step #2: 998498404f9a: Download complete
Step #2: 998498404f9a: Verifying Checksum
Step #2: 3c2cba919283: Download complete
Step #2: 3c2cba919283: Verifying Checksum
Step #2: 3c2cba919283: Pulling fs layer
Step #2: 998498404f9a: Pulling fs layer
Step #2: ff83c3f26fa3: Pulling fs layer
Step #2: latest: Pulling from google/ubuntu1604
Step #2: Using default tag: latest
Step #2: Pulling image: launcher.gcr.io/google/ubuntu1604
Starting Step #2
Finished Step #1
Step #1: Apply complete! Resources: 83 added, 0 changed, 0 destroyed.
Step #1: 
Step #1: google_project_iam_binding.project_host[0]: Creation complete after 8s [id=itg-shared-services-fr-emea-dv/roles/compute.networkUser]
Step #1: google_project_iam_binding.project_host[0]: Creating...
Step #1: google_compute_shared_vpc_service_project.service[0]: Creation complete after 11s [id=itg-shared-services-fr-emea-dv/itfr-datalake-fr-emea-dv]
Step #1: google_service_usage_consumer_quota_override.override: Creation complete after 11s [id=projects/itfr-datalake-fr-emea-dv/services/bigquery.googleapis.com/consumerQuotaMetrics/bigquery.googleapis.com%2Fquota%2Fquery%2Fusage/limits/%2Fd%2Fproject/consumerOverrides/Cg1RdW90YU92ZXJyaWRl]
Step #1: google_service_usage_consumer_quota_override.override: Still creating... [10s elapsed]
Step #1: google_compute_shared_vpc_service_project.service[0]: Still creating... [10s elapsed]
Step #1: google_service_usage_consumer_quota_override.override: Creating...
Step #1: google_compute_shared_vpc_service_project.service[0]: Creating...
Step #1: google_project_iam_binding.project[25]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/viewer]
Step #1: google_project_iam_binding.project[4]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/datastore.owner]
Step #1: google_project_iam_binding.project[28]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/monitoring.admin]
Step #1: google_project_iam_binding.project[12]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/iap.admin]
Step #1: google_project_iam_binding.project[30]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/cloudtasks.admin]
Step #1: google_project_iam_binding.project[35]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/iam.roleViewer]
Step #1: google_project_iam_binding.project[2]: Creation complete after 6s [id=itfr-datalake-fr-emea-dv/roles/cloudfunctions.admin]
Step #1: google_project_iam_binding.project[23]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/cloudbuild.builds.builder]
Step #1: google_project_iam_binding.project[18]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/compute.admin]
Step #1: google_project_iam_binding.project[14]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/workflows.admin]
Step #1: google_project_iam_binding.project[2]: Creating...
Step #1: google_project_iam_binding.project[15]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/cloudsql.client]
Step #1: google_project_iam_binding.project[25]: Creating...
Step #1: google_project_iam_binding.project[10]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/memcache.admin]
Step #1: google_project_iam_binding.project[4]: Creating...
Step #1: google_project_iam_binding.project[32]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/source.admin]
Step #1: google_project_iam_binding.project[28]: Creating...
Step #1: google_project_iam_binding.project[34]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/networkmanagement.admin]
Step #1: google_project_iam_binding.project[12]: Creating...
Step #1: google_project_iam_binding.project[1]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/storage.admin]
Step #1: google_project_iam_binding.project[30]: Creating...
Step #1: google_project_iam_binding.project[17]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/container.admin]
Step #1: google_project_iam_binding.project[35]: Creating...
Step #1: google_project_iam_binding.project[5]: Creation complete after 6s [id=itfr-datalake-fr-emea-dv/roles/endpoints.portalAdmin]
Step #1: google_project_iam_binding.project[5]: Creating...
Step #1: google_project_iam_binding.project[3]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/run.admin]
Step #1: google_project_iam_binding.project[23]: Creating...
Step #1: google_project_iam_binding.project[8]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/appengine.appAdmin]
Step #1: google_project_iam_binding.project[18]: Creating...
Step #1: google_project_iam_binding.project[16]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/appengine.appCreator]
Step #1: google_project_iam_binding.project[14]: Creating...
Step #1: google_project_iam_binding.project[29]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/cloudtrace.admin]
Step #1: google_project_iam_binding.project[15]: Creating...
Step #1: google_project_iam_binding.project[24]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/stackdriver.accounts.editor]
Step #1: google_project_iam_binding.project[10]: Creating...
Step #1: google_project_iam_binding.project[9]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/cloudsql.admin]
Step #1: google_project_iam_binding.project[32]: Creating...
Step #1: google_project_iam_binding.project[20]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/iam.serviceAccountAdmin]
Step #1: google_project_iam_binding.project[34]: Creating...
Step #1: google_project_iam_binding.project[36]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/compute.osAdminLogin]
Step #1: google_project_iam_binding.project[1]: Creating...
Step #1: google_project_iam_binding.project[19]: Creation complete after 7s [id=itfr-datalake-fr-emea-dv/roles/serviceusage.serviceUsageAdmin]
Step #1: google_project_iam_binding.project[17]: Creating...
Step #1: google_project_iam_binding.project[31]: Creation complete after 5s [id=itfr-datalake-fr-emea-dv/roles/cloudscheduler.admin]
Step #1: google_project_iam_binding.project[31]: Creating...
Step #1: google_project_iam_binding.project[26]: Creation complete after 10s [id=itfr-datalake-fr-emea-dv/roles/clouddebugger.user]
Step #1: google_project_iam_binding.project[3]: Creating...
Step #1: google_project_iam_binding.project[13]: Creation complete after 9s [id=itfr-datalake-fr-emea-dv/roles/dlp.admin]
Step #1: google_project_iam_binding.project[8]: Creating...
Step #1: google_project_iam_binding.project[11]: Creation complete after 9s [id=itfr-datalake-fr-emea-dv/roles/storagetransfer.admin]
Step #1: google_project_iam_binding.project[16]: Creating...
Step #1: google_project_iam_binding.project[6]: Creation complete after 9s [id=itfr-datalake-fr-emea-dv/roles/dataflow.admin]
Step #1: google_project_iam_binding.project[29]: Creating...
Step #1: google_project_iam_binding.project[21]: Creation complete after 9s [id=itfr-datalake-fr-emea-dv/roles/pubsub.admin]
Step #1: google_project_iam_binding.project[24]: Creating...
Step #1: google_project_iam_binding.project[22]: Creation complete after 9s [id=itfr-datalake-fr-emea-dv/roles/storage.admin]
Step #1: google_project_iam_binding.project[9]: Creating...
Step #1: google_project_iam_binding.project[33]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/cloudkms.admin]
Step #1: google_project_iam_binding.project[20]: Creating...
Step #1: google_project_iam_binding.project[0]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/bigquery.admin]
Step #1: google_project_iam_binding.project[36]: Creating...
Step #1: google_project_iam_binding.project[27]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/logging.admin]
Step #1: google_project_iam_binding.project[19]: Creating...
Step #1: google_project_iam_binding.project[7]: Creation complete after 8s [id=itfr-datalake-fr-emea-dv/roles/apigateway.admin]
Step #1: google_project_iam_binding.project[22]: Creating...
Step #1: google_project_iam_binding.project[7]: Creating...
Step #1: google_project_iam_binding.project[26]: Creating...
Step #1: google_project_iam_binding.project[13]: Creating...
Step #1: google_project_iam_binding.project[11]: Creating...
Step #1: google_project_iam_binding.project[6]: Creating...
Step #1: google_project_iam_binding.project[21]: Creating...
Step #1: google_project_iam_binding.project[33]: Creating...
Step #1: google_project_iam_binding.project[0]: Creating...
Step #1: google_project_iam_binding.project[27]: Creating...
Step #1: google_billing_budget.budget: Creation complete after 1s [id=billingAccounts/018CE6-1BB566-490761/budgets/1408bae4-9227-4584-b8cf-f4c87e0a76eb]
Step #1: google_billing_budget.budget: Creating...
Step #1: google_project_service.service["workflows.googleapis.com"]: Creation complete after 42s [id=itfr-datalake-fr-emea-dv/workflows.googleapis.com]
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Creation complete after 42s [id=itfr-datalake-fr-emea-dv/networkmanagement.googleapis.com]
Step #1: google_project_service.service["workflows.googleapis.com"]: Still creating... [40s elapsed]
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Still creating... [40s elapsed]
Step #1: google_project_service.service["workflows.googleapis.com"]: Still creating... [30s elapsed]
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Still creating... [30s elapsed]
Step #1: google_project_service.service["resourceviews.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/resourceviews.googleapis.com]
Step #1: google_project_service.service["resourceviews.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["workflows.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["cloudscheduler.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/cloudscheduler.googleapis.com]
Step #1: google_project_service.service["cloudscheduler.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["resourceviews.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["run.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/run.googleapis.com]
Step #1: google_project_service.service["workflows.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["run.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["sql-component.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/sql-component.googleapis.com]
Step #1: google_project_service.service["servicemanagement.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/servicemanagement.googleapis.com]
Step #1: google_project_service.service["cloudresourcemanager.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/cloudresourcemanager.googleapis.com]
Step #1: google_project_service.service["cloudscheduler.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["servicemanagement.googleapis.com"]: Creating...
Step #1: google_project_service.service["cloudresourcemanager.googleapis.com"]: Creating...
Step #1: google_project_service.service["resourceviews.googleapis.com"]: Creating...
Step #1: google_project_service.service["sql-component.googleapis.com"]: Creating...
Step #1: google_project_service.service["storagetransfer.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/storagetransfer.googleapis.com]
Step #1: google_project_service.service["cloudtasks.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/cloudtasks.googleapis.com]
Step #1: google_project_service.service["vpcaccess.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/vpcaccess.googleapis.com]
Step #1: google_project_service.service["compute.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/compute.googleapis.com]
Step #1: google_project_service.service["dlp.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/dlp.googleapis.com]
Step #1: google_project_service.service["datastore.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/datastore.googleapis.com]
Step #1: google_project_service.service["compute.googleapis.com"]: Creating...
Step #1: google_project_service.service["workflows.googleapis.com"]: Creating...
Step #1: google_project_service.service["datastore.googleapis.com"]: Creating...
Step #1: google_project_service.service["networkmanagement.googleapis.com"]: Creating...
Step #1: google_project_service.service["sqladmin.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/sqladmin.googleapis.com]
Step #1: google_project_service.service["iap.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/iap.googleapis.com]
Step #1: google_project_service.service["cloudfunctions.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/cloudfunctions.googleapis.com]
Step #1: google_project_service.service["dataflow.googleapis.com"]: Creation complete after 20s [id=itfr-datalake-fr-emea-dv/dataflow.googleapis.com]
Step #1: google_project_service.service["run.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["cloudscheduler.googleapis.com"]: Creating...
Step #1: google_project_service.service["pubsub.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/pubsub.googleapis.com]
Step #1: google_project_service.service["cloudtasks.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["vpcaccess.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["dlp.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["storagetransfer.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["pubsub.googleapis.com"]: Creating...
Step #1: google_project_service.service["bigquery.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/bigquery.googleapis.com]
Step #1: google_project_service.service["cloudfunctions.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["iap.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["dataflow.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["sqladmin.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["bigquery.googleapis.com"]: Creating...
Step #1: google_project_service.service["run.googleapis.com"]: Creating...
Step #1: google_project_service.service["bigquerystorage.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/bigquerystorage.googleapis.com]
Step #1: google_project_service.service["storage-api.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/storage-api.googleapis.com]
Step #1: google_project_service.service["bigquerystorage.googleapis.com"]: Creating...
Step #1: google_project_service.service["storage-api.googleapis.com"]: Creating...
Step #1: google_project_service.service["sourcerepo.googleapis.com"]: Creation complete after 21s [id=itfr-datalake-fr-emea-dv/sourcerepo.googleapis.com]
Step #1: google_project_service.service["iam.googleapis.com"]: Creation complete after 21s [id=itfr-datalake-fr-emea-dv/iam.googleapis.com]
Step #1: google_project_service.service["iam.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["sourcerepo.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["cloudtasks.googleapis.com"]: Creating...
Step #1: google_project_service.service["vpcaccess.googleapis.com"]: Creating...
Step #1: google_project_service.service["dlp.googleapis.com"]: Creating...
Step #1: google_project_service.service["storagetransfer.googleapis.com"]: Creating...
Step #1: google_project_service.service["iamcredentials.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/iamcredentials.googleapis.com]
Step #1: google_project_service.service["cloudkms.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/cloudkms.googleapis.com]
Step #1: google_project_service.service["appengine.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/appengine.googleapis.com]
Step #1: google_project_service.service["cloudbuild.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/cloudbuild.googleapis.com]
Step #1: google_project_service.service["cloudkms.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["appengine.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["cloudbuild.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["iamcredentials.googleapis.com"]: Creating...
Step #1: google_project_service.service["cloudfunctions.googleapis.com"]: Creating...
Step #1: google_project_service.service["iap.googleapis.com"]: Creating...
Step #1: google_project_service.service["dataflow.googleapis.com"]: Creating...
Step #1: google_project_service.service["sqladmin.googleapis.com"]: Creating...
Step #1: google_project_service.service["apigateway.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/apigateway.googleapis.com]
Step #1: google_project_service.service["container.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/container.googleapis.com]
Step #1: google_project_service.service["stackdriver.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/stackdriver.googleapis.com]
Step #1: google_project_service.service["redis.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/redis.googleapis.com]
Step #1: google_project_service.service["datacatalog.googleapis.com"]: Creation complete after 22s [id=itfr-datalake-fr-emea-dv/datacatalog.googleapis.com]
Step #1: google_project_service.service["redis.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["container.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["apigateway.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["datacatalog.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["stackdriver.googleapis.com"]: Still creating... [20s elapsed]
Step #1: google_project_service.service["iam.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["sourcerepo.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["cloudkms.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["appengine.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["cloudbuild.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["container.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["redis.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["apigateway.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["datacatalog.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["stackdriver.googleapis.com"]: Still creating... [10s elapsed]
Step #1: google_project_service.service["iam.googleapis.com"]: Creating...
Step #1: google_project_service.service["sourcerepo.googleapis.com"]: Creating...
Step #1: google_project_service.service["serviceusage.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/serviceusage.googleapis.com]
Step #1: google_project_service.service["oslogin.googleapis.com"]: Creation complete after 4s [id=itfr-datalake-fr-emea-dv/oslogin.googleapis.com]
Step #1: google_project_service.service["cloudkms.googleapis.com"]: Creating...
Step #1: google_project_service.service["serviceusage.googleapis.com"]: Creating...
Step #1: google_project_service.service["appengine.googleapis.com"]: Creating...
Step #1: google_project_service.service["oslogin.googleapis.com"]: Creating...
Step #1: google_project_service.service["cloudbuild.googleapis.com"]: Creating...
Step #1: google_project_service.service["monitoring.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/monitoring.googleapis.com]
Step #1: google_project_service.service["logging.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/logging.googleapis.com]
Step #1: google_project_service.service["clouddebugger.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/clouddebugger.googleapis.com]
Step #1: google_project_service.service["cloudtrace.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/cloudtrace.googleapis.com]
Step #1: google_project_service.service["storage-component.googleapis.com"]: Creation complete after 3s [id=itfr-datalake-fr-emea-dv/storage-component.googleapis.com]
Step #1: google_project_service.service["container.googleapis.com"]: Creating...
Step #1: google_project_service.service["cloudtrace.googleapis.com"]: Creating...
Step #1: google_project_service.service["apigateway.googleapis.com"]: Creating...
Step #1: google_project_service.service["datacatalog.googleapis.com"]: Creating...
Step #1: google_project_service.service["redis.googleapis.com"]: Creating...
Step #1: google_project_service.service["clouddebugger.googleapis.com"]: Creating...
Step #1: google_project_service.service["stackdriver.googleapis.com"]: Creating...
Step #1: google_project_service.service["storage-component.googleapis.com"]: Creating...
Step #1: google_project_service.service["monitoring.googleapis.com"]: Creating...
Step #1: google_project_service.service["logging.googleapis.com"]: Creating...
Step #1: google_project_service.service_default: Creation complete after 23s [id=xxxxx/cloudapis.googleapis.com]
Step #1: google_project_service.service_default: Still creating... [20s elapsed]
Step #1: google_project_service.service_default: Still creating... [10s elapsed]
Step #1: google_project_service.service_default: Creating...
Step #1: google_project.project: Creation complete after 59s [id=projects/xxxxx]
Step #1: google_project.project: Still creating... [50s elapsed]
Step #1: google_project.project: Still creating... [40s elapsed]
Step #1: google_project.project: Still creating... [30s elapsed]
Step #1: google_project.project: Still creating... [20s elapsed]
Step #1: google_project.project: Still creating... [10s elapsed]
Step #1: google_project.project: Creating...
Step #1: Already have image: hashicorp/terraform
Starting Step #1
Finished Step #0
Step #0: commands will detect it and remind you to do so if necessary.
Step #0: rerun this command to reinitialize your working directory. If you forget, other
Step #0: If you ever set or change modules or backend configuration for Terraform,
Step #0: 
Step #0: should now work.
Step #0: any changes that are required for your infrastructure. All Terraform commands
Step #0: You may now begin working with Terraform. Try running "terraform plan" to see
Step #0: 
Step #0: Terraform has been successfully initialized!
Step #0: 
Step #0: * hashicorp/google-beta: version = "~> 3.47.0"
Step #0: 
Step #0: in your configuration, with the constraint strings suggested below.
Step #0: changes, we recommend adding version constraints in a required_providers block
Step #0: To prevent automatic upgrades to new major versions that may contain breaking
Step #0: 
Step #0: so the latest version was installed.
Step #0: The following providers do not have any version constraints in configuration,
Step #0: 
Step #0: - Installed hashicorp/google-beta v3.47.0 (signed by HashiCorp)
Step #0: - Installing hashicorp/google-beta v3.47.0...
Step #0: - Finding latest version of hashicorp/google-beta...
Step #0: Initializing provider plugins...
Step #0: 
Step #0: use this backend unless the backend configuration changes.
Step #0: Successfully configured the backend "gcs"! Terraform will automatically
Step #0: 
Step #0: 
Step #0: 
Step #0: has changed. Terraform will now check for existing state in the backends.
Step #0: Terraform has detected that the configuration specified for the backend
Step #0: 
Step #0: Backend configuration changed!
Step #0: Initializing the backend...
Step #0: 
Step #0: docker.io/hashicorp/terraform:latest
Step #0: Status: Downloaded newer image for hashicorp/terraform:latest
Step #0: Digest: sha256:943b1d56d978e713315e1058e1e1297eafdf166c95bb7bbe2712699b0a664f48
Step #0: 6bc566ab3295: Pull complete
Step #0: 7f821a175ebf: Pull complete
Step #0: 6bc566ab3295: Download complete
Step #0: 6bc566ab3295: Verifying Checksum
Step #0: df20fa9351a1: Pull complete
Step #0: 7f821a175ebf: Download complete
Step #0: 7f821a175ebf: Verifying Checksum
Step #0: df20fa9351a1: Download complete
Step #0: df20fa9351a1: Verifying Checksum
Step #0: 6bc566ab3295: Pulling fs layer
Step #0: 7f821a175ebf: Pulling fs layer
Step #0: df20fa9351a1: Pulling fs layer
Step #0: latest: Pulling from hashicorp/terraform
Step #0: Using default tag: latest
Step #0: Pulling image: hashicorp/terraform
Starting Step #0
BUILD
HEAD is now at 927dc7a multiple roles
 * branch            927dc7a542c98c740300082701682b1432bc06c0 -> FETCH_HEAD
From https://source.developers.google.com/p/xxxxx/r/xxxxx
Initialized empty Git repository in /workspace/.git/
FETCHSOURCE

starting build "f02720e9-a01c-4667-93ab-0ee71050b7cc"

**Comment by antoinecastex** [comment]
you can see @edwardmedia  APIs are enabled , but the IAM permission related to the API are not set by TF .... I was thinking this was the job of Google when you say : i want this API  even if it's throug UI or throug TF ... but finally not

**Comment by edwardmedia** [comment]
@antoinecastex can you repro the issue? Did you say no single permissions assigned to the CB SA?

**Comment by edwardmedia** [comment]
@antoinecastex look at your code, your project is a fresh. you enabled the APIs right after the project creation. There is a possible reason that something are not ready in a fresh project when some services are enabled. In that case, we may have to workaround it in the Terraform level which adds `delay` logic. Can you repro the issue on a old project?

**Comment by antoinecastex** [comment]
That's very interesting @edwardmedia  i have to just enable cloudbuild.googleapis.com on a project with the ressource google_project_service  and  ... the SA has been created + IAM permissions

So you are very close to the truth .... delay is mandatory ? but strange ?  how many time ?  do you recommend me maybe to make a pause between every APIs that i enable ?


Have you see this issue ? 

https://urldefense.com/v3/__https://github.com/terraform-google-modules/terraform-google-project-factory/issues/448__;!!IY5JXqZAIQ!ryVzb7u3N6CeY4vniEPz3tZLrh4ZIGLywwlWRxku7LSJW7is67tM3UWGtgAxl073Htw$

**Comment by edwardmedia** [comment]
@antoinecastex this is not mandatory. Based on how each API was built, some APIs may take longer time. Some may return `done` while the internals are still in the middle of process. In the Terraform layer, we don't have insights other than relying on the returns of status. How long does the delay (pause) needs? Case by case.  
Sorry about the inconvenience. I am closing this issue then. Feel free to reopen this issue or create another if you need more questions
