### ISSUE TITLE
TestAccIAMBetaWorkloadIdentityPoolProvider_*

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#7817]
Failing with plan not empty:
```
~ oidc {
~ allowed_audiences = [
- "https://example.com/gcp-oidc-federation",
- "example.com/gcp-oidc-federation",
]
~ issuer_uri        = "https://sts.windows.net/azure-tenant-id-full" -> "https://sts.windows.net/azure-tenant-id-basic
}
```

**Comment by c2thorn** [comment]
`TestAccIAMBetaWorkloadIdentityPoolProvider_aws` seems to be failing because the PATCH request
```
{
 "aws": {
  "accountId": "888888888888"
 }
}
``` 
fails to persist and `accountId` does not change

**Comment by slevenick** [comment]
Hmmmm, potentially a eventual consistency issue?

**Comment by slevenick** [comment]
Nope, looks like the API updated to not allow updates on that field. The real error is hidden by a weird update mask behavior

**Comment by c2thorn** [comment]
Should it be moved to ForceNew?
