### ISSUE TITLE
Fix API gateway VCR tests

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#7819]
These reliably fail due to generating unique ids within the TF resource. Should fix by avoiding this, or skipping these tests

**Comment by upodroid** [comment]
FYI there was some char limits on the resource which isn't documented by Google

**Comment by upodroid** [comment]
Talked about it in https://github.com/GoogleCloudPlatform/magic-modules/pull/4193

Case ref is 25747924
