### ISSUE TITLE
GKE cluster nodepools don't wait for cluster to exit RECONCILING state

### ISSUE THREAD

**Issue by tibers** [hashicorp/terraform-provider-google#7823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.x (yes I know it's not the latest version)

### Affected Resource(s)

gke nodepools, gke clusters:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

### Terraform Configuration Files

The generic example of having a separately managed `nodepool` will suffice.

### Debug Output

NA

### Panic Output

NA

### Expected Behavior

1. Terraform creates the GKE cluster
1. The GKE cluster is created with the default nodepool
1. TF destroys the old default nodepool and adds the managed nodepool per the docs
1. We should wait until the entire workflow is done and the cluster leaves the RECONCILING (or REPAIRING) state. 

A `gcloud container clusters list` will show the RECONCILING or REPAIRING state - a simple `kubectl get cs` does not indicate the cluster is unhealthy. The UI will show the cluster with a "spinning" circle. 

### Actual Behavior

TF does not wait for the cluster to become repaired. This check could be implemented by looking for the state of the nodepool and the health of the cluster via the google API. By not waiting for the new nodepool to join, TF will begin trying to continue the workflow (in my case, installing helm charts with the helm provider) but will timeout because the cluster isn't ready and takes too long to become ready.

### Steps to Reproduce

1. Install managed GKE
1. Direct TF to use managed nodepools per the docs
1. Immediately try to install something using the helm provider (or a local-exec to helm)
1. Observe that TF doesn't know about the cluster state so it will not wait.

Adding `depends_on` and then the nodepool resource does not wait for the cluster to reconcile as a result of the nodepool changes.

### Important Factoids

This looks like it will have the STATUS of the cluster and we should be polling for it:
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.Status

### References

nil

**Comment by rileykarson** [comment]
We can call https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_container_cluster.go#L2649 from https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_container_node_pool.go#L1083 (probably before the node pool level check) to do this, I think

**Comment by venkykuberan** [comment]
I am moving this issue to enhancement bucket, we will work on once it gets triaged.
