### ISSUE TITLE
cloud scheduler HTTP bodies should be base64-encoded

### ISSUE THREAD

**Issue by bleything** [hashicorp/terraform-provider-google#7828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/-/google v3.48.0
+ provider registry.terraform.io/hashicorp/google v3.48.0
```

### Affected Resource(s)

* google_cloud_scheduler_job

### Terraform Configuration Files

```tf
provider "google" {
  project = "[redacted]"
  region  = "us-central1"
}

resource "google_cloud_scheduler_job" "repro" {
  name = "http-body-base64-repro"

  http_target {
    uri  = "http://example.com"
    body = "{}"
  }
}
```

### Debug Output

https://gist.github.com/bleything/917fbc494e3bc9d498e19e078ef6f71c

### Expected Behavior

The job should be created with the given body content.

### Actual Behavior

The API returns an error message saying that it can't decode the body:

```
Error: Error creating Job: googleapi: Error 400: Invalid value at 'job.http_target.body' (TYPE_BYTES), Base64 decoding failed for "{}"
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value at 'job.http_target.body' (TYPE_BYTES), Base64 decoding failed for \"{}\"",
        "field": "job.http_target.body"
      }
    ]
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* wrapping the value for `body` in `base64encode()` is an effective workaround:

```tf
resource "google_cloud_scheduler_job" "repro" {
  name = "http-body-base64-repro"

  http_target {
    uri  = "http://example.com"
    body = base64encode("{}")
  }
}
```

### References

* [docs for the HttpTarget object](https://cloud.google.com/scheduler/docs/reference/rest/v1/projects.locations.jobs#HttpTarget) which indicates that the body should be a base64-encoded string

**Comment by edwardmedia** [comment]
`A base64-encoded string.` from the [doc](**https://cloud.google.com/scheduler/docs/reference/rest/v1beta1/projects.locations.jobs#HttpTarget**) . Update the document accordingly. Change label to document

**Comment by owennewo** [comment]
Whilst the above got me passed the error it did not present a proper json body to the destination cloud function.  This helped:
```
body = base64encode(jsonencode( {  } ))
```
without this a python cloud function calling `request.get_json()` was not receiving the json.

**Comment by bleything** [comment]
@edwardmedia: I think changing the behavior of the provider is a stronger fix than changing the docs. If we know the API always expects base64 then the provider can automatically handle the encoding so the user doesn't have to think about it.

**Comment by bleything** [comment]
@rileykarson @c2thorn: I don't think that GoogleCloudPlatform/magic-modules#4247 adequately addresses this issue. The docs that were added don't make it clear that the user has to encode the string, imo. And I still think pushing that responsibility to the user is the wrong choice, as I said above.

If you can give me a pointer or a hint about how to add the encoding magic I'd be happy to put in a PR. If you feel like this doc fix is sufficient, let me know and I'll drop it 🙂

**Comment by c2thorn** [comment]
@bleything I think it's reasonable to push the encoding to the provider and add a stronger note stating what the provider is doing. I'll reopen this.

Looks like we use base64 encoding here: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/data_sources/data_source_storage_object_signed_url.go#L313

**Comment by upodroid** [comment]
I don't agree because the API expects a b64 payload and terraform has a way of easily converting something to b64. In the unlikely event a newcomer doesn't know that terraform has b64 helper functions, there is a clear example that uses the b64 encode function.

Also, this is isn't the only resource that wants a b64 encoded field.

**Comment by bleything** [comment]
Yeah, I hear you. There's certainly a philosophical difference here that needs to be considered and decided upon.

My position is that the user shouldn't have to know that the API expects base64. The principle of least surprise is a core value of mine, and so my opinion is that we should make an effort to allow the user to specify the payload in any format and the provider should do the right thing. In this case that means handling the encoding for the user. It probably also means detecting when the input is base64 to begin with and passing it unchanged. I'd also argue this should be done universally, any time we know that the API expects a certain format.

I understand this creates additional maintenance burden and the maintainers need to decide whether they're willing to take that on. I hope they'll decide the cost is worth it, but ultimately it's up to them.

**Comment by rileykarson** [comment]
Summarising some team discussion:

* Terraform's builtin functions make base64 encoding an input extremely easy
* Changing the field behaviour in a way that isn't backwards-compatible (eg: to expect raw values) would be a breaking change, so that isn't an option we'd take.
* Auto-encoding a value would be undesirable in case our heuristic was wrong. Having to choose the correctly formatted field is also around as much work for the user as using the builtin TF function.
* We can surface errors early on (plan time) if we use a regex to check if the value is base64 encoded.

I think the takeaway was that we should add the regex + improve the docs. @c2thorn does that sound right?

**Comment by c2thorn** [comment]
@rileykarson that sounds right. By adding the regex validation we can fail fast and give a hint towards the builtin function.
I removed the sizing label since the scope has expanded a bit.
