### ISSUE TITLE
compute ssl-certificates: beta -> v1

### ISSUE THREAD

**Issue by nyetsche** [hashicorp/terraform-provider-google#7832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

The `compute_managed_ssl_certificate` resource appears to be out of beta and should be included in the regular provider.

Originally it was added to `google-beta` here: https://github.com/GoogleCloudPlatform/magic-modules/pull/1420

The schema listed there has changed. v1 now includes all the fields that were in beta:

https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates

And example JSON output from `gcloud compute ssl-certificates describe QUUX`. 

```
{
  "certificate": "",
  "creationTimestamp": "2020-05-07T04:14:40.747-07:00",
  "description": "",
  "expireTime": "2021-02-03T01:24:50.000-08:00",
  "id": "4090121010515170127",
  "kind": "compute#sslCertificate",
  "managed": {
    "domainStatus": {
      "QUUX.DOMAIN": "ACTIVE"
    },
    "domains": [
      "QUUX.DOMAIN"
    ],
    "status": "ACTIVE"
  },
  "name": "QUUX",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/PROJECT/global/sslCertificates/QUUX",
  "subjectAlternativeNames": [
    "QUUXALT.DOMAIN"
  ],
  "type": "MANAGED"
}
```

Output from `gcloud beta compute ssl-certificates describe QUUX` is identical, except for the `selfLink`.

Discovered during https://github.com/GoogleCloudPlatform/terraformer/issues/653 - the `terraformer` tool doesn't have a native way to use the `google-beta` provider.

### Terraform Version

```
terraform version
Terraform v0.12.29
+ provider.google-beta v3.48.0
```

The version is intentional, `terraformer` uses that: https://github.com/GoogleCloudPlatform/terraformer/blob/master/go.mod#L31

### Affected Resource(s)

* google_compute_managed_ssl_certificate

### Steps to Reproduce

Create Terraform with both providers:

```
provider "google" {}
provider "google-beta" {}

resource "google_compute_managed_ssl_certificate" "QUUX" {
  certificate_id = "1234"
  provider       = google-beta

  managed {
    domains = ["QUUX.DOMAIN"]
  }

  name    = "QUUX"
  project = "PROJECT"
  type    = "MANAGED"
}
```

`terraform plan` with `provider = google-meta` succeeds.
`terraform plan` with `provider = google` fails with:

```
Error: Invalid resource type

  on resource.tf line 4, in resource "google_compute_managed_ssl_certificate" "QUUX":
   4: resource "google_compute_managed_ssl_certificate" "QUUX" {

The provider provider.google does not support resource type
"google_compute_managed_ssl_certificate".
```

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/1420
* https://github.com/GoogleCloudPlatform/terraformer/issues/653 
* https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates

**Comment by edwardmedia** [comment]
Changing label to `enhancement` to enable **v1**
