### ISSUE TITLE
Docs: Example is invalid, since conditions can't be set on primitive roles

### ISSUE THREAD

**Issue by paxorus** [hashicorp/terraform-provider-google#7833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.45.0

### Affected Resource(s)

* google_project_iam_binding
* google_project_iam_member

### Issue Description
Terraform Enterprise behaved as expected, rejecting the invalid resource during the apply.
```
Error: Request "Create IAM Members roles/editor serviceAccount:455395250569-compute@developer.gserviceaccount.com for \"project \\\"<project>\\\"\"" returned error: Batch request and retried single request "Create IAM Members roles/editor serviceAccount:455395250569-compute@developer.gserviceaccount.com for \"project \\\"<project>\\\"\"" both failed. Final error: Error applying IAM policy for project "<project>": Error setting IAM policy for project "<project>": googleapi: Error 400: LintValidationUnits/BindingRoleAllowConditionCheck Error: Conditions can't be set on primitive roles., badRequest
```
Steps to reproduce: 
1. Create a google_project_iam_member with basic role `roles/editor` and a condition like an expiration.
1. `terraform apply`

### Important Factoids
None

### References

* Google Provider docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_member
* GCP IAM docs: https://cloud.google.com/iam/docs/conditions-overview#limitations
> Basic roles (roles/owner, roles/editor, roles/viewer) are unsupported; if you attempt to set a condition in a role binding that uses a basic role, the setIamPolicy operation will fail.

**Comment by edwardmedia** [comment]
@paxorus it works fine with me using below code. After `tf apply`, I saw the new user added with the `Editor` role. Can you share the code you used and the debug log? 

```tf
resource "google_project_iam_member" "project" {
  project = "your-project-id"
  role    = "roles/editor"
  member  = "user:jane@example.com"
}
```

**Comment by paxorus** [comment]
Hi, @edwardmedia! Thanks for getting back to me. Would you be able to retry that snippet with a condition? I had meant the "With IAM Conditions" example in the docs:
```tf
resource "google_project_iam_member" "project" {
  project = "your-project-id"
  role    = "roles/editor"
  member  = "user:jane@example.com"

  condition {
    title       = "expires_after_2019_12_31"
    description = "Expiring at midnight of 2019-12-31"
    expression  = "request.time < timestamp(\"2020-01-01T00:00:00Z\")"
  }
}
```

Here is our exact code:
```tf
resource "google_project_iam_member" "compute_engine_default_no_editor" {
  role   = "roles/editor"
  member = "serviceAccount:${data.google_compute_default_service_account.default.email}"

  # An expiration in the past should remove this default role.
  condition {
    title       = "already_expired"
    description = "Already expired"
    expression  = "request.time < timestamp(\"2020-01-01T00:00:00Z\")"
  }
}
```

For the debug log, getting this log will be a little challenging with our current setup, so I would prefer not to do it unless we believe it will definitely help. Our current setup requires us to get a review and approval to commit to the codebase, and another review and approval revert it. I don't believe it will help, because Terraform Enterprise is behaving totally correctly, in compliance with the GCP docs, by rejecting a google_project_iam_member that has both `role = roles/editor` and a `condition`. So it is just the Terraform docs "With IAM Conditions" example that does not seem compliant with the GCP docs.

**Comment by edwardmedia** [comment]
@paxorus  got it, you are right.  Thank you
