### ISSUE TITLE
Support attributes for google_bigtable_table column_family

### ISSUE THREAD

**Issue by autumnw** [hashicorp/terraform-provider-google#7839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When we use google_bigtable_table to create a table, it does not allow us to add attributes for clomun_family likes the following (maxversions):
```tf
resource "google_bigtable_table" "table" {
  for_each      = var.tables
  name          = each.key
  instance_name = google_bigtable_instance.instance.name

  dynamic "column_family" {
    for_each = each.value.families
    content {
      family = column_family.key
      maxversions = column_family.value.maxversions
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### New or Affected Resource(s)

* google_bigtable_table

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_bigtable_table" "table" {
  for_each      = var.tables
  name          = each.key
  instance_name = google_bigtable_instance.instance.name

  dynamic "column_family" {
    for_each = each.value.families
    content {
      family = column_family.key
      maxversions = column_family.value.maxversions
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### References

* #0000

**Comment by rileykarson** [comment]
If this is available under columnfamilies type, we likely want to avoid it (at least as part of this resource). Our support for families in google_bigtable_table is just the `initialColumnFamilies` you can supply on a create request.
