### ISSUE TITLE
When destroying & creating a Spanner instance, its database isn't recreated with it

### ISSUE THREAD

**Issue by quentinms** [hashicorp/terraform-provider-google#7840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.48.0
```

### Affected Resource(s)

* google_spanner_instance
* google_spanner_database

### Terraform Configuration Files

Before:
```tf
resource "google_spanner_instance" "test" {
  project      = var.project
  name         = "test"
  config       = "regional-us-east1"
  display_name = "Test"
  num_nodes    = 1
}

resource "google_spanner_database" "test" {
  project  = var.project
  instance = google_spanner_instance.test.name
  name     = "test"
}
```

After:
```tf
resource "google_spanner_instance" "test" {
  project      = var.project
  name         = "test"
  config       = "nam11"
  display_name = "Test"
  num_nodes    = 1
}

resource "google_spanner_database" "test" {
  project  = var.project
  instance = google_spanner_instance.test.name
  name     = "test"
}
```

### Debug Output

https://gist.github.com/quentinms/52ad7e765738b986888025b953a0f4cf

### Expected Behavior

In addition to recreating the `google_spanner_instance` it should also recreate the `google_spanner_database` linked to it.

### Actual Behavior

It only recreates the `google_spanner_instance` (making a spanner instance with no database). 
By planning again, it will notice the `google_spanner_database` is missing and will want to create it. It should all happen at the same time.

### Steps to Reproduce

1. `terraform plan` & `terraform apply` the following:
```tf
resource "google_spanner_instance" "test" {
  project      = var.project
  name         = "test"
  config       = "regional-us-east1"
  display_name = "Test"
  num_nodes    = 1
}

resource "google_spanner_database" "test" {
  project  = var.project
  instance = google_spanner_instance.test.name
  name     = "test"
}
```

2. Change the `google_spanner_instance` config to force a destroy & create.

```tf
resource "google_spanner_instance" "test" {
  project      = var.project
  name         = "test"
  config       = "nam11" // Will force recreation
  display_name = "Test"
  num_nodes    = 1
}

resource "google_spanner_database" "test" {
  project  = var.project
  instance = google_spanner_instance.test.name
  name     = "test"
}
```
3. `terraform plan`

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_spanner_instance.test must be replaced
-/+ resource "google_spanner_instance" "test" {
      ~ config       = "projects/test-project/instanceConfigs/regional-us-east1" -> "nam11" # forces replacement
        display_name = "Test"
      ~ id           = "test-project/test" -> (known after apply)
      - labels       = {} -> null
        name         = "test"
        num_nodes    = 1
        project      = "test-project"
      ~ state        = "READY" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

The plan is missing the `google_spanner_database` database which will also be destroyed (and should be recreated).

### References

* Possibly related: `google_spanner_instance`'s recreation behavior was recently changed to fix #7732.

**Comment by edwardmedia** [comment]
Yes, we have to apply twice to restore the database. Not sure if there is a proper way that the Terraform code can be configured to reflect the underlying relationship.

**Comment by rileykarson** [comment]
This is an occurrence of an upstream issue in Terraform's resource model (https://github.com/hashicorp/terraform-plugin-sdk/issues/122) for which we're not aware of any solution, unfortunately. Since there's nothing we can do here, I'm closing this out.
