### ISSUE TITLE
Firestore index timeout on creation

### ISSUE THREAD

**Issue by etiennelandais** [hashicorp/terraform-provider-google#7842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`➜ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.47.0`

### Affected Resource(s)

* google_firestore_index

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.47.0"
    }
}

provider "google" {
  project     = var.project_id
  region      = var.region
}

resource "google_firestore_index" "foo_index_4" {
  collection = "foo"

  fields {
    field_path = "foo1"
    order      = "ASCENDING"
  }

  fields {
    field_path = "foo2"
    order      = "ASCENDING"
  }
}


```

### Debug Output

https://gist.github.com/etiennelandais/3e449fa30e1188fe0f40f516b13903db

### Expected Behavior

Terraform should create the firestore index, wait for it to be created, and then return successfully.

### Actual Behavior

Terraform sends requests to create firestore index, index are created about 5 minutes later but Terraform is stuck to "Still creating..." until Timeout

Terraform is calling the [Operation API](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.operations) to check the readyness of the index.

Maybe it should be calling the [Collection Group indexes API](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.collectionGroups.indexes) to check the state of the index ? 

### Steps to Reproduce

1. Copy example tf above
2. Replace provider config with a project you have access to
3. terraform init
4. terraform apply
5. Terraform will  timeout
6. Check the GCP console to see if the index was actually created

### Important Factoids

*Indexes do get created.
*Setting the timeout values do not appear to affect this

### References

* #0000

**Comment by edwardmedia** [comment]
@etiennelandais we had an [issue](https://github.com/hashicorp/terraform-provider-google/issues/6692) in creating indexes but that appears different. Your config looks good. I wonder if API experienced difficulties in returning operation responses during that period. Mind try again to see if the issue go away?

**Comment by etiennelandais** [comment]
Hello @edwardmedia 

Indeed this issue doesn't seems to be related to mine.

I've just run terraform apply on my project and the issue is still here.

To add more information, I've run the following commands at different times of the deployment:

`gcloud firestore indexes composite list`
`gcloud firestore operations list`

At the begining of the deployment : 

`---
metadata:
  '@type': type.googleapis.com/google.firestore.admin.v1.IndexOperationMetadata
  index: projects/foo-project/databases/(default)/collectionGroups/reports/indexes/
  progressDocuments: {}
  startTime: '2020-11-19T08:35:20.856579Z'
  state: INITIALIZING
name: projects/foo-project/databases/(default)/operations/AyA1MDY5ZjNiZjljNWYtMGIxOS1kYzY0LTg0ZTUtODY1YTFmZmYkGnRsdWFmZWQHEmVwb3J1ZS1yZXhlZG5pLW5pbWRhFApHEg

┌──────────────┬──────────────────┬──────────────────┬──────────┬────────────────┬───────────┬──────────────┐
│     NAME     │ COLLECTION_GROUP │   QUERY_SCOPE    │  STATE   │  FIELD_PATHS   │   ORDER   │ ARRAY_CONFIG │
├──────────────┼──────────────────┼──────────────────┼──────────┼────────────────┼───────────┼──────────────┤
│ CICAgLjyi5UL │ foo              │ COLLECTION       │ CREATING │ foo1           │ ASCENDING │              │
│              │                  │                  │          │ foo2           │ ASCENDING │              │
└──────────────┴──────────────────┴──────────────────┴──────────┴────────────────┴───────────┴──────────────┘
`
about 5 minutes into deployment: 

`

metadata:
  '@type': type.googleapis.com/google.firestore.admin.v1.IndexOperationMetadata
  index: projects/foo-project/databases/(default)/collectionGroups/reports/indexes/
  progressDocuments: {}
  startTime: '2020-11-19T08:42:44.180853Z'
  state: INITIALIZING
name: projects/foo-project/databases/(default)/operations/AyA1MDY5ZjNiZjljNWYtMGIxOS1kYzY0LTg0ZTUtODY1YTFmZmYkGnRsdWFmZWQHEmVwb3J1ZS1yZXhlZG5pLW5pbWRhFApHEg

┌──────────────┬──────────────────┬──────────────────┬──────────┬────────────────┬───────────┬──────────────┐
│     NAME     │ COLLECTION_GROUP │   QUERY_SCOPE    │  STATE   │  FIELD_PATHS   │   ORDER   │ ARRAY_CONFIG │
├──────────────┼──────────────────┼──────────────────┼──────────┼────────────────┼───────────┼──────────────┤
│ CICAgLjyi5UL │ foo              │ COLLECTION       │ READY    │ foo1           │ ASCENDING │              │
│              │                  │                  │          │ foo2           │ ASCENDING │              │
`

At the end of the deployment:


`
---
metadata:
  '@type': type.googleapis.com/google.firestore.admin.v1.IndexOperationMetadata
  index: projects/foo-project/databases/(default)/collectionGroups/reports/indexes/
  progressDocuments: {}
  startTime: '2020-11-19T08:45:32.050258Z'
  state: INITIALIZING
name: projects/foo-project/databases/(default)/operations/AyA1MDY5ZjNiZjljNWYtMGIxOS1kYzY0LTg0ZTUtODY1YTFmZmYkGnRsdWFmZWQHEmVwb3J1ZS1yZXhlZG5pLW5pbWRhFApHEg

┌──────────────┬──────────────────┬──────────────────┬──────────┬────────────────┬───────────┬──────────────┐
│     NAME     │ COLLECTION_GROUP │   QUERY_SCOPE    │  STATE   │  FIELD_PATHS   │   ORDER   │ ARRAY_CONFIG │
├──────────────┼──────────────────┼──────────────────┼──────────┼────────────────┼───────────┼──────────────┤
│ CICAgLjyi5UL │ foo              │ COLLECTION       │ READY    │ foo1           │ ASCENDING │              │
│              │                  │                  │          │ foo2           │ ASCENDING │              │
└──────────────┴──────────────────┴──────────────────┴──────────┴────────────────┴───────────┴──────────────┘
`

**Comment by edwardmedia** [comment]
@etiennelandais Can you try to add [timeout](https://www.terraform.io/docs/configuration/resources.html?&_ga=2.74577754.91921133.1605645248-671278361.1584370291#operation-timeouts) to see it that helps?

The default timeout for this resource is 10 minutes. Did it take more than that?

**Comment by etiennelandais** [comment]
@edwardmedia 

OK now it's working without increasing the timeout.

It maybe was a transient operation API issue 

Sorry the inconvenience
