### ISSUE TITLE
Terraform does not enforce only-one-of google_compute_url_map.path_matcher.route_rules.match_rules on full_path_match, prefix_match, or regex_match

### ISSUE THREAD

**Issue by goodspark** [hashicorp/terraform-provider-google#7844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.21
+ provider.google v3.48.0
+ provider.google-beta v3.48.0
```

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

```tf
data "google_compute_backend_service" "main" {
  name = "main"
}

data "google_compute_backend_service" "other" {
  name = "other"
}

resource "google_compute_url_map" "default" {
  provider = google-beta
  name  "my-urlmap"
  default_service = data.google_compute_backend_service.main.id

  host_rule {
    hosts = ["*"]
    path_matcher = "all"
  }

  path_matcher {
    name = "all"
    default_service = data.google_compute_backend_service.main.id
    route_rules {
      priority = 1

      match_rules {
        header_matches {
          header_name = "blahblah"
          exact_match = "test"
        }
      }

      route_action {
        weighted_backend_services {
          backend_service = data.google_compute_backend_service.main.self_link
          weight = 990
        }
        weighted_backend_services {
          backend_service = data.google_compute_backend_service.other.self_link
          weight = 10
        }
      }
    }
  }
}
```

### Expected Behavior

Terraform should not have allowed this configuration to go through.

### Actual Behavior

The config was applied and Google silently failed and removed our configuration on the load balancer and cut off all traffic.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is a bug both on the Google provider and on Google Cloud itself.
1. The provider should be validating these inputs. The documentation states exactly one of full_path_match, prefix_match, or regex_match must be defined. So the provider should enforce that.
2. Google Cloud should not just silently accept this and then delete our load balancer configuration. This is not a Terraform provider problem and has already been reported to Google.

### References

Docs about match_rules:
- Terraform: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_url_map (search for "The match_rules block supports")
  > Only one of prefixMatch, fullPathMatch or regexMatch must be specified.
- Google: https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps (search for "pathMatchers[].routeRules[].matchRules[].prefixMatch")
  > Only one of prefixMatch, fullPathMatch or regexMatch must be specified.

**Comment by edwardmedia** [comment]
@goodspark help me understand what your case is. What you want is `Terraform should not have allowed this configuration to go through.` Did you make any config change before you run `apply`? On the other side, how to handle the situation when someone wants to update the configuration?

**Comment by edwardmedia** [comment]
@goodspark is this still an issue?

**Comment by goodspark** [comment]
Yes, but I don't understand the question. The config is in the description, right?

If you're asking what changed, before hand the URL map was using default_route_action.weighted_backend_services to route requests to different backends. This change was to enable that routing only when a header was present.

I updated the config in the description to show the weighted routes to be a fuller example.

To reiterate, the problem here is that the provider was not enforcing the only-one-of conditions for the fields in match_rules. Without it, GCP silently removed the backends from the load balancer (which will cause an outage). While GCP shouldn't have allowed this and should have errored, it seems there's an opportunity here for the provider to do validation and prevent that from happening in the first place.

**Comment by edwardmedia** [comment]
I see. Need to add `Only one of prefixMatch, fullPathMatch or regexMatch must be specified.` in the validation

**Comment by ndmckinley** [comment]
Hm, I think that that's a misreading of "must" in the documentation.  I agree it is unclear, but I believe that the configuration you applied is a valid one, which is why GCP didn't error.  The config you show here would forward all traffic with the specified header to the backend services you provided.

> predicates within a given matchRule have AND semantics. All predicates within a matchRule must match for the request to match the rule.

"Only one of X, Y, or Z must be specified", in Google's documentation language, tends to imply that you can also specify none of X, Y, or Z.  We call these cases "at most one of", rather than "exactly one of".  We are able to validate these on the provider side - and we do in many cases - but prefixMatch, fullPathMatch and regexMatch would be an "at most one of", which would not have prevented this issue.
