### ISSUE TITLE
How to stop cloudsql instance using this terraform provider

### ISSUE THREAD

**Issue by yashbhutwala** [hashicorp/terraform-provider-google#7848]
https://cloud.google.com/sql/docs/postgres/start-stop-restart-instance#stop

Be able to do what this gcloud command does with terraform:

```bash
gcloud sql instances patch [INSTANCE_NAME] --activation-policy NEVER
```

**Comment by edwardmedia** [comment]
@yashbhutwala `activation-policy` is supported in `sql_database_instance`. Below is its doc

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#activation_policy

**Comment by yashbhutwala** [comment]
I see!  OK thanks @edwardmedia!  💯
