### ISSUE TITLE
Allow us to configure default providers with google_identity_platform_oauth_idp_config

### ISSUE THREAD

**Issue by tibers** [hashicorp/terraform-provider-google#7856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.x

### Affected Resource(s)

google_identity_platform_default_supported_idp_config
google_identity_platform_oauth_idp_config

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/identity_platform_default_supported_idp_config

https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#managing_saml_and_oidc_providers_programmatically

It seems like we can't add providers (or default providers) to the Identity Platform and must add them manually. How do we add providers ("anonymous", "email / password") through TF or is this impossible?

**Comment by edwardmedia** [comment]
@tibers  what do you mean `providers (or default providers)`? I am not sure if that is a Terraform [provider](https://www.terraform.io/docs/providers/index.html). Can you explain a little more details about what you are trying to do?

**Comment by tibers** [comment]
OK so we're working with the Identity Platform API's Identity Provider component in gcloud, which has some functionality in the google-beta provider. 

My understanding of the IDP config is from the first refs link so the code should be something like:

```hcl
resource "google_identity_platform_default_supported_idp_config" "idp_config" {
  enabled       = true
  idp_id        = <USERNAME AND PASSWORD PROVIDER>
  client_id     = var.fromFirebase
  client_secret = var.fromFirebase
}
```

In the docs I see a list of `app_id`s which I believe setup the Identity Providers which can be something like `apple.com` or `facebook.com` but I need "Anonymous" and "Email / Password", which don't seem to be supported? Or am I looking at the wrong bit of TF code and this whole thing isn't supported yet at all?

**Comment by edwardmedia** [comment]
@tibers you are right. Below is the code that handles the resource creation. It only takes the one you listed above. Closing this question then. Feel free to reopen it if you have more question about it. Thaks

https://github.com/hashicorp/terraform-provider-google/blob/ee251c46904022e68f857408f2192295d3f18ecf/google/resource_identity_platform_default_supported_idp_config.go#L128
