### ISSUE TITLE
Support for network ingress settings on App Engine services

### ISSUE THREAD

**Issue by matthewblain** [hashicorp/terraform-provider-google#7866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

App Engine supports network ingress settings to restrict access to private or load balancer traffic. This can be done with gcloud or through the API with the networkSettings / IngressTrafficAllowed enum

Terraform does not support this setting, so it's not possible to configure that way. It would be good to enable this feature.

### New or Affected Resource(s)

This could be done by tweaking the related google_app_engine_service_split_traffic module, creating a new parallel module, or similar.

### Potential Terraform Configuration

Here is a config which enhances google_app_engine_service_split_traffic, using the example in the docs for that.

```tf

resource "google_app_engine_service_split_traffic" "liveapp" {
  service = google_app_engine_standard_app_version.liveapp_v2.service

  # New line:
  ingress_traffic_allowed = "INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB"
  migrate_traffic = false
  split {
    shard_by = "IP"
    allocations = {
      (google_app_engine_standard_app_version.liveapp_v1.version_id) = 0.75
      (google_app_engine_standard_app_version.liveapp_v2.version_id) = 0.25
    }
  }
}
```

Given that this feature (ingress) is service-specific, not version-specific, it could also be separate.
I'm also using a name similar to Cloud Functions instead of the App Engine API; I don't know which name is better.

```tf

resource "google_app_engine_service" "liveapp" {
  service = "internalservice"

  ingress_settings = "INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY"
}
```

### References

* https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services#IngressTrafficAllowed
* #5740 - similar issue for Cloud Functions, completed.

**Comment by matty-rose** [comment]
I'm interested in helping to contribute this feature - at a cursory glance it seems I should be looking at actually contributing to https://github.com/GoogleCloudPlatform/magic-modules since that seems to be where a majority of the resources are generated from? I'm also leaning towards making it a separate resource as opposed to coupling it to the traffic split.

**Comment by matty-rose** [comment]
As an update I have submitted a PR to the magic modules repo implementing a new network_settings resource that should resolve this - https://github.com/GoogleCloudPlatform/magic-modules/pull/4810
