### ISSUE TITLE
`google_container_node_pool.autoscaling.*_node_count` should not trigger a node pool deletion

### ISSUE THREAD

**Issue by hadim** [hashicorp/terraform-provider-google#7870]
It seems to me changing one of those values could be done without deleting and recreating a node pool. At least this is possible to do it using the GKE dashboard.

**Comment by edwardmedia** [comment]
@hadim I don't see it is possible to update the `*_node_count` without deleting the node pool based on the provided the API


https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters.nodePools/create

**Comment by edwardmedia** [comment]
@hadim I am not seeing the a node pool deletion plan after I update the count below. What plan did you see? Can you share your plan?

```
# google_container_node_pool.primary_preemptible_nodes will be updated in-place
.......
      ~ autoscaling {
          ~ max_node_count = 2 -> 3
            min_node_count = 1
        }
```

**Comment by hadim** [comment]
I don't remember can you try with `min_node_count`? I will try again (not working on this code currently) and let you know soon.

**Comment by edwardmedia** [comment]
@hadim I got below plan. Let me know if you see a different plan

```tf
  # google_container_node_pool.primary_preemptible_nodes will be updated in-place
  ~ resource "google_container_node_pool" "primary_preemptible_nodes" {
....
      ~ autoscaling {
          ~ max_node_count = 3 -> 5
          ~ min_node_count = 1 -> 2
        }
```

**Comment by hadim** [comment]
I actually can confirm what you see and cannot reproduce the issue. Not sure what happened before. I'll close here. Thanks for the assistance.
