### ISSUE TITLE
google_sql_database_instance : MySQL :  Invalid request: Invalid full instance name

### ISSUE THREAD

**Issue by talonx** [hashicorp/terraform-provider-google#7878]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.49.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
resource "google_sql_database_instance" "mysql" {
  name = "grafana-mysql"
  database_version = "MYSQL_5_7"
  deletion_protection = true
  project = var.project
  settings {
    tier = "db-n1-standard-1"
    backup_configuration {
      enabled = true
      binary_log_enabled = true
    }
    ip_configuration {
      private_network = var.vpc_network
    }
    maintenance_window {
      //Sunday 3 AM PST
      day = 7
      hour = 11
      update_track = "stable"
    }
  }
  replica_configuration {
    failover_target = "true"
    //    master_instance_name = google_sql_database_instance.instance.name
  }
}

# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

Should have created the CloudSQL instance

### Actual Behavior

```module.grafana-cloudsql.google_sql_database_instance.mysql: Creating...

Error: Error, failed to create instance grafana-mysql: googleapi: Error 400: Invalid request: Invalid full instance name: racoon-one:., invalid
```
Note that racoon-one is the project id and name.

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform-provider-google/issues/5506
The workaround in 5506 did not help.

**Comment by edwardmedia** [comment]
@talonx can you share your full debug log?

**Comment by edwardmedia** [comment]
@talonx is this still an issue?

**Comment by talonx** [comment]
@edwardmedia Thanks for the response. Here is the debug log - https://gist.github.com/talonx/ef7a50ac231150db64bb77c30b08e6fa

**Comment by edwardmedia** [comment]
@talonx have you tried to add `master_instance_name` like below? 

```tf
  master_instance_name = google_sql_database_instance.instance.name
  replica_configuration {
    failover_target = "true"
  }
```

We should add validations to make sure
1. `replica_configuration` and `master_instance_name` coexist. 
2. `backup` must not be enabled if replica is configured.

**Comment by talonx** [comment]
@edwardmedia According to the docs, `master_instance_name` refers to the instance that will act as the master in the replication setup. I have just one instance (and if I setup failover I want this one to be the master). I tried two things
 *

**Comment by talonx** [comment]
@edwardmedia I tried both of these
- Setting `master_instance_name = "grafana-mysql"` which fails with 

`Error: Error, failed to create instance grafana-mysql: googleapi: Error 400: The instance being created cannot have the same name as the source instance., errorMatchingSourceDestinationInstanceName`

which seems to indicate that this instance is a failover and it needs to refer to a master from which it will replicate. However, I want to have a single instance at least for now. 
- Tried setting `  master_instance_name = google_sql_database_instance.mysql.name` which fails with a `Configuration for google_sql_database_instance.mysql may not refer to itself.` 

Both of these errors seem valid. Is there a place where I can find complete working examples? This is a simple enough setup IMO.

Docs : https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance



(I hit Comment without writing the entire comment - deleted that half-typed one)

**Comment by talonx** [comment]
Can somebody help here? I tried what you suggested. What am I missing?

**Comment by c2thorn** [comment]
@talonx, sorry about the delay. From what I can understand you do _not_ want to create this instance as a replica? If that is the case, you can remove the `replica_configuration` block entirely.

If that is not the case and you want `grafana-mysql` to be a replica, you must supply a `master_instance_name` referring to another instance. It seems to be an oversight that the provider does not require `master_instance_name` when `replica_configuration` is defined.

**Comment by c2thorn** [comment]
I see, `master_instance_name` can exist without `replica_configuration` defined. @talonx, let me know if my previous comment has helped your issue, and I can reopen.
