### ISSUE TITLE
google_cloud_scheduler_job: support a "paused" attribute

### ISSUE THREAD

**Issue by pietrodn** [hashicorp/terraform-provider-google#7883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud Scheduler allows to [pause](https://cloud.google.com/scheduler/docs/reference/rest/v1/projects.locations.jobs/pause) jobs. A paused job is still present in the list of Cloud Scheduler tasks, but does not fire at its schedule, until it is un-paused.

It would be useful if the `google_cloud_scheduler_job` supported a `paused` boolean attribute, to define paused jobs in the infrastructure, or to make sure they are not paused.

Currently, the paused status of a Cloud Scheduler job is ignored by the provider in the Terraform plan.
The current behavior introduces the risk of drift between the desired infrastructure and the live one, as one may not realize that a Cloud Scheduler job is paused.

### New or Affected Resource(s)

* `google_cloud_scheduler_job`

### Potential Terraform Configuration

```tf
resource "google_cloud_scheduler_job" "job" {
  name        = "test-job"
  description = "test job"
  schedule    = "*/2 * * * *"
  paused      = true

  pubsub_target {
    topic_name = google_pubsub_topic.topic.id
    data       = base64encode("test")
  }
}
```

**Comment by felixogg-britned** [comment]
Using 3.65.0 actually a ```paused``` state, configuration drift originating from the GUI, **blocked Terraform apply** with an error
``` googleapi: Error 400: Job.state must be ENABLED or UPDATE_FAILED  for UpdateJob.```

It all cleared up when I manually enabled the jobs in the GUI, and re-ran ```plan``` and ```apply```.

**Comment by dcarvalhal** [comment]
Hey guys!!

We have an update about this?

" An argument named "paused" is not expected here."

**Comment by irwinbraganza** [comment]
+1

**Comment by fkfouri** [comment]
This feature would be great

**Comment by gorziza** [comment]
+1

**Comment by YohanGrember** [comment]
+1, it's a real pain not to be able to handle the cloud scheduler job state from Terraform :/

**Comment by lmartelli** [comment]
https://github.com/hashicorp/terraform-provider-google/pull/11141 :-)

Please, give it a try
