### ISSUE TITLE
"google_monitoring_slo" is missing Availability option

### ISSUE THREAD

**Issue by marcfong** [hashicorp/terraform-provider-google#7884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.google v3.49.0
+ provider.random v3.0.0

### Affected Resource(s)

* google_monitoring_slo

### Terraform Configuration Files

```tf
resource "google_monitoring_slo" "windows_based" {
  service = "ist:xxxxxxxxx"
  display_name = "Terraform Test SLO with window based SLI"

  goal = 0.7
  calendar_period = "FORTNIGHT"

  windows_based_sli {
    window_period = "60s"
    good_total_ratio_threshold {
      threshold = 0.7
      basic_sli_performance {
        availability {
        }
      }
    }
  }
}

```

### Debug Output

```
Error: Unsupported block type
  on main.tf line 14, in resource "google_monitoring_slo" "windows_based":
  14:           availability {
Blocks of type "availability" are not expected here.
```

### Expected Behavior

Terraform plan should succeed.
The CLoud Monitoring API supports both "Availability" and "latency" parameters to the "BlasicSliPerformance" type.
See API docs here :
[https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#BasicSli](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#BasicSli)

### Actual Behavior

Terraform apply failed.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
Change label to `enhancement`
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#availabilitycriteria

**Comment by rileykarson** [comment]
Closing in favour of https://github.com/hashicorp/terraform-provider-google/issues/7239
