### ISSUE TITLE
removing all items from dynamic block for google_compute_subnetwork secondary_ip_ranges does not change resource

### ISSUE THREAD

**Issue by BusiPlay** [hashicorp/terraform-provider-google#7892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 0.13.5

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "subnet" {
  provider = google
  for_each = { for subnet in local.network_subnets:
                subnet.subnet_key => subnet
  }
  name = each.key
  network = each.value.vpc
  ip_cidr_range = each.value.cidr_block
  region = each.value.region

  dynamic "secondary_ip_range" {
    for_each = each.value.sec_ranges
    
    content{
        range_name = secondary_ip_range.key
        ip_cidr_range = secondary_ip_range.value  
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform should remove all blocks related to dynamic content 

### Actual Behavior
No changes were found

### Steps to Reproduce

0. Create google_compute_subnetworks with dynamic secondary_ip_range blocks, and a variable or local containing a non-empty collection
1. `terraform apply`
2. Update variable/local to remove all values from collection
3. `terraform plan`

### Important Factoids

N/A

### References

https://github.com/hashicorp/terraform/issues/22605 references a similar issue for the OCI provider, which was reclassified as a provider issue

* #0000

**Comment by edwardmedia** [comment]
@BusiPlay can you share the `plan` in the step #1 and step #3?

**Comment by BusiPlay** [comment]
Step #1
[plan1.log](https://github.com/hashicorp/terraform-provider-google/files/5599799/plan1.log)

Step#3
[plan3.log](https://github.com/hashicorp/terraform-provider-google/files/5599803/plan3.log)

**Comment by edwardmedia** [comment]
@BusiPlay  I can't repro your issue. By removing the items in the list, I got below plan. I see the two subnets are gone after applying the plan. Can you share your data in `locals` and `variables` and detailed steps to repro your issue? 

```
Terraform will perform the following actions:
  # google_compute_subnetwork.subnet["us-central1-sn"] will be destroyed
  - resource "google_compute_subnetwork" "subnet" {
      - creation_timestamp         = "2020-11-27T08:38:21.407-08:00" -> null
      - gateway_address            = "192.168.1.1" -> null
      - id                         = "projects/autotest/regions/us-central1/subnetworks/us-central1-sn" -> null
      - ip_cidr_range              = "192.168.1.0/24" -> null
      - name                       = "us-central1-sn" -> null
      - network                    = "https://www.googleapis.com/compute/v1/projects/autotest/global/networks/network-2" -> null
      - private_ip_google_access   = false -> null
      - private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS" -> null
      - project                    = "autotest" -> null
      - region                     = "us-central1" -> null
      - secondary_ip_range         = [
          - {
              - ip_cidr_range = "10.11.0.0/20"
              - range_name    = "pod-range"
            },
          - {
              - ip_cidr_range = "172.30.21.0/24"
              - range_name    = "svc-range"
            },
        ] -> null
      - self_link                  = "https://www.googleapis.com/compute/v1/projects/autotest/regions/us-central1/subnetworks/us-central1-sn" -> null
    }
  # google_compute_subnetwork.subnet["us-west4-sn"] will be destroyed
  - resource "google_compute_subnetwork" "subnet" {
      - creation_timestamp         = "2020-11-27T08:38:21.531-08:00" -> null
      - gateway_address            = "192.168.2.1" -> null
      - id                         = "projects/autotest/regions/us-east4/subnetworks/us-west4-sn" -> null
      - ip_cidr_range              = "192.168.2.0/24" -> null
      - name                       = "us-west4-sn" -> null
      - network                    = "https://www.googleapis.com/compute/v1/projects/autotest/global/networks/network-2" -> null
      - private_ip_google_access   = false -> null
      - private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS" -> null
      - project                    = "autotest" -> null
      - region                     = "us-east4" -> null
      - secondary_ip_range         = [
          - {
              - ip_cidr_range = "10.12.0.0/20"
              - range_name    = "pod-range"
            },
          - {
              - ip_cidr_range = "172.30.22.0/24"
              - range_name    = "svc-range"
            },
        ] -> null
      - self_link                  = "https://www.googleapis.com/compute/v1/projects/autotest/regions/us-east4/subnetworks/us-west4-sn" -> null
    }
Plan: 0 to add, 0 to change, 2 to destroy.
```

**Comment by BusiPlay** [comment]
To clarify, removing the subnets correctly removes the resources, however removing all secondary IP ranges does not cause the existing subnets to be changed.

Files attached. If you apply as is, then change sec_ranges in the second subnet to an empty map, you will see no changes on a subsequent apply:

[repro.zip](https://github.com/hashicorp/terraform-provider-google/files/5609446/repro.zip)

**Comment by edwardmedia** [comment]
@BusiPlay I can repro your issue. It only happens when **all** elements are removed from `secondary_ip_range`. Unfortunately this is the Teeraform SDK issue. Below is the code in the provider plugin where `schema.ResourceDiff` does not detect any changes in that case. On the other side, when one `ip_cidr_range` is removed, thing is different. Does this make sense to you?

https://github.com/hashicorp/terraform-provider-google/blob/97678cefadcb1615714efc069de0deea00999f4c/google/resource_compute_subnetwork.go#L265

**Comment by BusiPlay** [comment]
Yes, I'm observing the same behavior - however, would you not want to evaluate the presence of any existing keys for secondary_ip_range if schema.ResourceDiff does not provide any changes (ie when all ip_cidr_range are removed?)

The related issue I linked, https://github.com/hashicorp/terraform/issues/22605, asks providers to handle this kind of occurrence.

**Comment by edwardmedia** [comment]
@BusiPlay  By removing the settings inside the it using the `dynamic` code, basically it removes the `secondary_ip_range` node from the request payload. Unfortunately because `secondary_ip_range` is defined as `optional` and `computed`, what Terraform treats it is no change for this field. 
To make it working, you need to include the node `secondary_ip_range = []` instead of omitting it completely. 
In this case, there is nothing the provider can do. I am closing this issue.

**Comment by BusiPlay** [comment]
@edwardmedia doesn't this effectively preclude the use of dynamic blocks in this case? Not sure how I can work around this - if I explicitly change the main.tf to provide an empty value I can’t do one thing if the variables contain data and another thing if they don’t?

**Comment by BusiPlay** [comment]
The Google Network module does work around this using the following:
  secondary_ip_range = [
    for i in range(
      length(
        contains(
        keys(var.secondary_ranges), each.value.subnet_name) == true
        ? var.secondary_ranges[each.value.subnet_name]
        : []
    )) :
    var.secondary_ranges[each.value.subnet_name][i]
  ]

**Comment by edwardmedia** [comment]
@BusiPlay I will take a look at the [example](https://github.com/hashicorp/terraform-provider-google/issues/7892#issuecomment-738764397) . It would be better if you can have a full config. Sorry about the inconvenience  . I understood and agreed with you.

**Comment by BusiPlay** [comment]
Full config of the workaround used by the Google Network module can be reviewed at https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/subnets. I've mainly placed it here for posterity, it just confirms that dynamic can not be used with this resource, and shows how to work around it.

As a purely academic exercise, I looked for other keyed attribute blocks that could potentially be used with dynamic blocks. The closest I could find was CloudSQL'a authorized_networks block, but this is wrapped inside an ip_configuration block which then throws an error if there are no authorized_networks (which I prefer to the silent failure observed here)
