### ISSUE TITLE
google_cloudbuild_trigger 403 caller doent have permission

### ISSUE THREAD

**Issue by beingminimal** [hashicorp/terraform-provider-google#7894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.49.0
+ provider registry.terraform.io/hashicorp/time v0.6.0

### Affected Resource(s)
* google_cloudbuild_trigger

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
provider "google" {
  project     = "project-name"
  credentials = file("service-acc-iac.json")
  region      = "asia-south1"
}

resource "google_cloudbuild_trigger" "build-trigger" {
  project = "project-name"
  trigger_template {
    branch_name = "master"
    repo_name   = "cloud-source-repo-name"
    dir         = "triggers"
  }

   build {
    step {
      name = "hashicorp/terraform"
      args = ["terraform", "init"]
    }
   }
}

```

### Debug Output
https://gist.github.com/beingminimal/bba2564145ad4c3c4fa0348eb3f7d16b

### Expected Behavior
Cloud build Trigger should be created

### Actual Behavior
At the time of running terraform apply I am getting "Error creating Trigger: googleapi: Error 403: The caller does not have permission".

I have given the below roles to my service account
Cloud Build Service Account
Cloud Build Editor
Service Usage Admin
Organization Administrator

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@beingminimal did you enable **cloudbuild** service? If not, you might want to take a look below resource

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service

**Comment by beingminimal** [comment]
Hi @edwardmedia yes, cloudbuild.googleapis.com is enabled.

**Comment by edwardmedia** [comment]
@beingminimal You have listed service accounts and roles. Do you intend to use your own service account (vs the default Cloud Build service account) to trigger builds? What benefits do you get if that is true? How did you manage these accounts and roles? 

https://cloud.google.com/cloud-build/docs/securing-builds/configure-access-for-cloud-build-service-account

**Comment by beingminimal** [comment]
Hi @edwardmedia , agree that creating our own service account for using terraform will not be so much useful. So tried to perform the same steps with Cloud build default service account. But unfortunately in that also I am getting the same error. 

Do I need to grant any other permission to cloud build default service account to use "google_cloudbuild_trigger" resource of terraform?

**Comment by edwardmedia** [comment]
@beingminimal I am not super sure what the error comes from (what permission needed on what resources). Hope me understand 
1) How did you create other resources? If they are managed by Terraform, can you share the configs? If not, can you import the states?
2) Have you verified if the account has proper permissions to the repository?

**Comment by beingminimal** [comment]
Hi @edwardmedia,

What we are trying to achieve is to create a base project "project-a" which can manage IAC for other new projects "project-b" in GC.
Below are the steps which I performed: 
1. Created base project from console e.g. "project-a"
2. Created cloud source repo from console e.g. "project-a-repo"
3. Enable Cloud build API , Cloud Resource manager API, Cloud Billing API in "project-a" from console
2. Created manual trigger to perform terraform init, plan and apply which will create resources (folder, project "project-b" , project-b-repo and project-b-trigger) with the required permission. Please check attached files for more detail.
[main.txt](https://github.com/hashicorp/terraform-provider-google/files/5609198/main.txt)
[variables.txt](https://github.com/hashicorp/terraform-provider-google/files/5609199/variables.txt)

3. Grant Storage Object Viewer, Billing Account User, Folder Creator & Project Creator roles to default service account.
4. Execute the build.
Note my all steps are passing but the build has been failed in the last step of creating the trigger. 

Step #2 - "tf apply": google_sourcerepo_repository.new-project-iac: Creating...
Step #2 - "tf apply": google_sourcerepo_repository.new-project-iac: Creation complete after 2s 
Step #2 - "tf apply": 
Step #2 - "tf apply": Error: Error creating Trigger: googleapi: Error 403: The caller does not have permission
Step #2 - "tf apply": 
Step #2 - "tf apply": 
Finished Step #2 - "tf apply"

PS: 
Here we are trying to create triggers for project-b using the base project's default service account (project-a). 
So for doing this do we need to give some org level role to project-a default service account?
I tried giving Cloud Build Service Account at org level but getting the same error.

**Comment by edwardmedia** [comment]
@beingminimal Is the serviceAccount of project-a a member of Project-b?

**Comment by beingminimal** [comment]
Hi @edwardmedia , 

I tried giving "Project Owner" permission at the Organisation level to "project-a" service account which means it can now access all the resources of "project-b". We have verified it by looking at the IAM of "project-b". "project-b" IAM is listing "project-a" service account with Project Owner permission.

Correct me if I am wrong and let us know which specific permission we should give to which service account.

Our team is stuck now at this point. So please provide a solution to this so we can conclude how to create triggers for "project-b" from the base project "project-a".

**Comment by edwardmedia** [comment]
@beingminimal what account were you using to conduct step #4 `Created manual trigger to perform terraform init, plan and apply...`? Is that the same as `service-acc-iac.json`? Does the account of `service-acc-iac.json` have the right permissions?

**Comment by beingminimal** [comment]
Hi @edwardmedia, please refer to the latest files which I have attached with the steps. service-acc-iac.json was used when we tried to perform steps locally. But after that, we tried it in cloud code and in that also receiving the same error. 

Regarding which service account we used in step 4, 
It is the default service account that cloud build provides. And the same service account has org level Project Owner role.

**Comment by edwardmedia** [comment]
@beingminimal sorry I am confused. In the[ Terraform code](https://github.com/hashicorp/terraform-provider-google/issues/7894#issue-751331505) at the very top, you have specified what account is used which is from the key file. But you also mentioned for step4, it uses `default service account` which I assume is `project_id@cloudbuild.gserviceaccount.com`
Can you run [Terraform code](https://github.com/hashicorp/terraform-provider-google/issues/7894#issue-751331505) manually by `tf apply`? If not, and hits that error, that means the account with `service-acc-iac.json` does not have right permissions. I am not sure how you use the `default service account (`project_id@cloudbuild.gserviceaccount.com`) to run `tf apply`. If this is the case, can you provide the details?

**Comment by beingminimal** [comment]
Hi @edwardmedia ,

Let me brief about how we use the default service account and execute tf apply.
We need to perform all our terraform operations through Cloud build pipeline, and that has default service account project_id@cloudbuild.gserviceaccount.com. We have created `cloudbuild.yaml` file and integrated it with cloud build to perform tf apply in Cloud build.

```
cloudbuild.yaml

steps:
- id: 'tf-init'
  name: 'hashicorp/terraform:0.13.5'
  args: ['init']
# [START tf-plan]
- id: 'tf-plan'
  name: 'hashicorp/terraform:0.13.5'
  args: ['plan']
# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.13.5'
  args: [ 'apply', '-auto-approve']
# [END tf-apply]   
```
Reference for default service account: https://cloud.google.com/cloud-build/docs/cloud-build-service-account
Please check the terraform code available in https://github.com/hashicorp/terraform-provider-google/issues/7894#issuecomment-734946743 (main and variable files)

**Comment by edwardmedia** [comment]
@beingminimal Oh it seems clear now. The Terraform provider uses its own way to authenticate itself to the APIs. How do you provide the credential to the Terraform? Do you expect it automatically uses `project_id@cloudbuild.gserviceaccount.com`  Please review this [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#impersonate_service_account_delegates) for `impersonate_service_account_delegates`

To verify if the caller has enough permissions, you can run [this code](https://github.com/hashicorp/terraform-provider-google/issues/7894#issue-751331505) manually.

**Comment by edwardmedia** [comment]
@beingminimal Is this still an question? Cloud Build odes not automatically use its default account to be as the Terraform runner account. You need to link these together. If I misunderstood your question, please clarify.

**Comment by beingminimal** [comment]
Hi @edwardmedia ,

Regarding cloud build service account, to run terraform runner with cloud build we have given additional IAM roles to default service account so that can be used as terraform runner. And with that service account, we can create all other required GCP resources but getting errors with the cloud build trigger.

And can you please elaborate on why we need to impersonate service account delegation? does it mean we need to add project-a service account delegation in project-b?

**Comment by edwardmedia** [comment]
@baroncharlus the Terraform provider uses its way to [provider credentials](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials). How do you let the provider to pick the CB's service account? Please go over the doc to understand how the provider authenticate itself. This is not the permissions. It is the issue of a wrong account

**Comment by edwardmedia** [comment]
@baroncharlus does that make sense to you?

**Comment by edwardmedia** [comment]
@beingminimal closing this assuming it is no longer a question. Feel free to reopen it if you need further conversation
