### ISSUE TITLE
TF wants to create already existing google_dns_policy

### ISSUE THREAD

**Issue by krathow** [hashicorp/terraform-provider-google#7898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.49.0
+ provider registry.terraform.io/hashicorp/google-beta v3.49.0

### Affected Resource(s)

google_dns_policy

### Terraform Configuration Files

```tf
resource "google_dns_policy" "my-cloud" {
  name                      = "my-cloud"
  enable_inbound_forwarding = true
  enable_logging = false

  alternative_name_server_config {
    target_name_servers {
      ipv4_address = "10.1.1.2"
    }
    target_name_servers {
      ipv4_address = "10.2.3.4"
    }
  }

  networks {
    network_url = google_compute_network.network.self_link
  }
}
```

### Debug Output

2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   <title>Error 404 (Not Found)!!1</title>
2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   <style>
ns{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   </style>
2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   <p><b>404.</b> <ins>That’s an error.</ins>
2020-11-27T15:11:45.120Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5:   <p>The requested URL <code>/dns/v1/projects/my-cloud-gcp/policies/my-cloud</code> was not found on this server.  <ins>That’s all we know.</ins>

### Expected Behavior

TF should recognize that the resource already exists

### Actual Behavior

`terraform show ` show the resource is in the state
but
`terraform plan` wants to create the resource either way.

Seems there is some error on calling the GCP-API, as can be seen in the debug output

* #0000

**Comment by edwardmedia** [comment]
@krathow Was it originally created by applying the same config? Can you share the state and the full debug log for the 2nd apply? (above log message does not tell us much)

**Comment by krathow** [comment]
@edwardmedia - thanks, meanwhile I could find the problem:
the corporate policy forbids to access the Cloud DNS API via certain paths and GCP's response is just a 404 instead of a permission denied because of organization controls.
In turn Terraform wants to create the resource again even though it has that resource in the state.

**Comment by edwardmedia** [comment]
@krathow  I guess you no longer have the issue. Closing the issue accordingly. Feel free to reopen it this is no the case.
