### ISSUE TITLE
AI Platform Notebooks are missing "no sudo access" option

### ISSUE THREAD

**Issue by kos-maverik** [hashicorp/terraform-provider-google#7900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating an AI Platform Notebook on Google Cloud Console, there is an option to `Disable sudo access to the instance`.

This feature seems to be missing from the notebooks terraform resource.

This is currently an impediment on enabling AI Platform Notebooks in my company.

### New or Affected Resource(s)

* [google_notebooks_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance)

### Potential Terraform Configuration

```tf
resource "google_notebooks_instance" "instance" {
  provider = google-beta
  name = "notebooks-instance"
  location = "us-west1-a"
  machine_type = "e2-medium"
  vm_image {
    project      = "deeplearning-platform-release"
    image_family = "tf-latest-cpu"
  }
  disable_sudo_access = true
}
```

**Comment by kos-maverik** [comment]
Hello, are there any updates on this? Thanks.

**Comment by melinath** [comment]
Sounds like this is already supported by the `metadata` field. Closing.
