### ISSUE TITLE
Unable to create external tables over Google Spreadsheets

### ISSUE THREAD

**Issue by nirby821** [hashicorp/terraform-provider-google#7909]
Using terraform v0.13.5 and provider hashicorp/google-beta v3.36.0, we are unable to create an external table over Google spreadsheets. The process fails with the following error:

```
Error: googleapi: Error 400: Error while reading table: static_countries_external, error message: Failed to read the spreadsheet. Error code: PERMISSION_DENIED, invalid
```

Running the command using `bq mk` with the same service account authentication and exactly the same spreadsheet and destination tables - succeeds. Also tried adding `scopes = ["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/bigquery"]` to providers definition.

This is the tf resource configuration that fails:
```
resource "google_bigquery_table" "countries_external_sheet" {
  project = PROJECT_NAME
  dataset_id = "internal"
  table_id = "static_countries_external"

  external_data_configuration {
    autodetect    = true
    source_format = "GOOGLE_SHEETS"

    source_uris = [
      "THE_SOURCE_URL",
    ]
  }
}
```

And this is the bq mk command that succeeded:
```
table_def:
{
  "autodetect": true,
  "sourceFormat": "GOOGLE_SHEETS",
  "sourceUris": [
"THE_SOURCE_URL"
  ]
}

bq mk --external_table_definition=driver_table_def PROJECT_NAME:internal.static_countries_external
```

How can we solve this? Thanks

**Comment by venkykuberan** [comment]
@nirby821 can you please attach the debug log here. If you can get http request/response from bq tool please include that as well.
