### ISSUE TITLE
GKE cluster creation throws an auth error, yet is created

### ISSUE THREAD

**Issue by NandoTheessen** [hashicorp/terraform-provider-google#7919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.29
+ provider.external v2.0.0
+ provider.google v3.49.0
+ provider.google-beta v3.49.0
+ provider.kubernetes v1.13.3
+ provider.null v2.1.2
+ provider.random v2.3.1
```

### Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "europe-west1"
  project = data.google_projects.projects.projects[0].project_id

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1
  network = "xxx"
  subnetwork = "xxx"

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }
}

resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "my-node-pool"
  location   = "europe-west1"
  cluster    = google_container_cluster.primary.name
  node_count = 1

  node_config {
    preemptible  = true
    machine_type = "e2-medium"

    metadata = {
      disable-legacy-endpoints = "true"
    }

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```

### Debug Output

https://gist.github.com/NandoTheessen/e1e6641ae77a625d4377cb89394ab102

### Expected Behavior

The GKE cluster and Node Pool should have been created and be healthy

### Actual Behavior

We see an error related to authentication after exactly 10 minutes, the cluster is created still but the nodes aren't healthy.

```
Error: Error waiting for creating GKE cluster: error while retrieving operation: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project
More details:
Reason: authError, Message: Invalid Credentials
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I've followed this repository https://github.com/terraform-google-modules/terraform-example-foundation to guide me through the setup of our google account

### References

* #0000

**Comment by edwardmedia** [comment]
@NandoTheessen  can you get the debug log so I can take a close look? You might want to set the environment variable `TF_LOG=TRACE` if you haven't done so.

**Comment by edwardmedia** [comment]
@NandoTheessen is this still an issue?

**Comment by edwardmedia** [comment]
@NandoTheessen Closing this issue, assuming it is no longer an issue.

**Comment by NandoTheessen** [comment]
@edwardmedia hey, sorry for the late response.
Yes, this still is an issue.

I've found that if I removed the OAuth scopes from the nodes completely and reran, nodes did come up for the new cluster but that behavior isn't consistent. However, I'm pretty sure now that the issue isn't with the Google Provider itself but with the used terraform module.
