### ISSUE TITLE
Using Multiple Service Accounts and Credentials

### ISSUE THREAD

**Issue by terradict** [hashicorp/terraform-provider-google#7920]
Hi everyone ! 

In my team, we have been using Terraform with the Google provider for a while now.

As of today, we have one service account that has several (often admin) roles on our GCP project (to be able to do the tasks we ask it to do). 
As we are trying to improve our security best practices compliance, we are splitting that service account into several smaller ones (as recommended here https://cloud.google.com/iam/docs/using-iam-securely: least privilege principal).

However, we are facing a limitation on the Terraform Google provider side: it seems that, when using the "google" provider, we can only provide one service account (json key) in the [provider "google" / "credentials"] field. This service account seems to be used for all subsequent requests made to the Google API.

Is there a way to provide separate service accounts for separate resources management ? If not, does anyone know a workaround to do this (in a clean-ish way) ?

Thanks for your help !

**Comment by edwardmedia** [comment]
@terradict the service account you were talking about is for Terraform runner. If you intend to use Terraform to manage GCP resources, you must give this account certain roles, at least to cover these resources. 

You can create Terraform runners as many as you want, and give each one limited roles. But you might want to consider setting up roles for users and deciding who can access the runner accounts.

**Comment by edwardmedia** [comment]
@terradict Is this still a question?

**Comment by terradict** [comment]
Thanks for the answer @edwardmedia !

Indeed, I am realizing that in our case, there no point in splitting the roles between several SAs, given that all the steps are executed at the same step. So I am closing this issue. 

Thanks again !
