### ISSUE TITLE
Make scheduling node_affinities updatable 

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Compute API allows `node_affinities` to be updated when the instance is stopped: https://cloud.google.com/compute/docs/reference/rest/v1/instances/setScheduling

This can allow users to move VMs to sole tenancy without destroying and recreating their instances. Right now we have the field set as `ForceNew`. We should remove `ForceNew` from the field/sub-fields, and modify [schedulingHasChange](https://github.com/hashicorp/terraform-provider-google/blob/master/google/compute_instance_helpers.go#L355) to detect changes on `node_affinities`. 

The API documentation states that `setScheduling` requires the instance to be stopped, but it seems that this is only true to update `node_affinities`. We should determine if it is right to move the entire `setScheduling` call to after we stop the instance, or if the instance should only be stopped for updating `node_affinities`.

### New or Affected Resource(s)

* google_compute_instance

### References

* b/174512356

**Comment by rileykarson** [comment]
Note: there's an outstanding PR but we need someone on our team (likely @c2thorn) to pick it up
