### ISSUE TITLE
KMS key ring trying to be created in wrong project

### ISSUE THREAD

**Issue by veggie124** [hashicorp/terraform-provider-google#7926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

➜ terraform -v
Terraform v0.13.5

### Affected Resource(s)

google_kms_key_ring

### Terraform Configuration Files

```
resource "google_kms_key_ring" "poshta-dev-keyring" {
  count = var.environment_state == "dev" ? 1 : 0
  name = "poshta-dev-ring"
  location = "global"
  project = module.project-factory.project_id
}
```

### Debug Output

https://gist.github.com/veggie124/fcc5c86589943a4e3879993db06a3ec2

### Expected Behavior

We expected the key ring to be created in project B (The terraform service account is in project A)

### Actual Behavior

Terraform tries to create the key ring in project A and fails because we have the kms api disabled in that project

### Steps to Reproduce

1. `terraform apply`

### References

This is very similar to this issue from last year: 
https://github.com/hashicorp/terraform-provider-google/issues/4828

* #0000

**Comment by edwardmedia** [comment]
@veggie124 Is `spins-poshta-dev` project-A or Project-B? It is not clear how you reference the project_id. Can you try hardcoding below attribute?

```
project = module.project-factory.project_id
```

**Comment by veggie124** [comment]
I should have mentioned it, the new project (being created in another part of this same config) is spins-poshta-dev (project B) and that is from the module project-factory. We have also tried hard coding the project ID.
Code for that below:
```
locals {
  project_name            = "spins-poshta-${var.environment_state}"
}

# Creates GCP Project and enables APIs
module "project-factory" {
  source                  = "terraform-google-modules/project-factory/google"
  version                 = "~> 9.0"

  name                    = local.project_name
  random_project_id       = "false"
  org_id                  = var.org_id
  folder_id               = var.folder_id
  billing_account         = var.billing_account_id
  activate_apis           = var.gcp_apis
  default_service_account = "keep"
  labels                  = {"cost-center": "productappinfra"}
}
``` 

Project A is what contains the terraform service account.

**Comment by edwardmedia** [comment]
@veggie124  what is the result of running below config? If it fails, can you share the debug log?

```tf
resource "google_kms_key_ring" "poshta-dev-keyring" {
  count = var.environment_state == "dev" ? 1 : 0
  name = "poshta-dev-ring"
  location = "global"
  project = <project-B-id>
}
```

**Comment by veggie124** [comment]
Same error when hard coding. Here is the debug from that round:
https://gist.github.com/veggie124/8dd22fc6325cbdc17dbe5cac95a5f3d2

note that the project number 308178187047 is from project A (where the service account lives)
```
resource "google_kms_key_ring" "poshta-dev-keyring" {
  count = var.environment_state == "dev" ? 1 : 0
  name = "poshta-dev-ring"
  project = "spins-poshta-dev"
  location = "global"
}
```
This is the project we expect it to be created in.
![image](https://user-images.githubusercontent.com/1765654/100937986-80d57900-34b9-11eb-8e86-2a138f13abe7.png)

This is where it is trying to create it.
![image](https://user-images.githubusercontent.com/1765654/100938057-9c408400-34b9-11eb-9c30-a483a75b6025.png)

**Comment by edwardmedia** [comment]
@veggie124 your log appears not the result running directly from the [code](https://github.com/hashicorp/terraform-provider-google/issues/7926#issuecomment-737528640) 

I have tested your code cross different projects, it works fine with me. 

If you still see an error in creating `google_kms_key_ring` by running above code, please post it debug log.

**Comment by veggie124** [comment]
Sorry I don't understand what you mean by 

> @veggie124 your log appears NOT the result running directly from the code

Are you saying the code I pasted is not what is running in the debug? The runs get kicked off when we merge branches with our source control and I'm looking at the master branch with the above code in it.

Here is the plan that the run created as well:
![image](https://user-images.githubusercontent.com/1765654/100945751-82a63900-34c7-11eb-89e9-89f484324366.png)

Even with the project specified it is still trying to create the key ring in the terraform project and not the poshta project.

We intentionally have kms disabled in the terraform project, but it is enabled in the poshta project.

This reads very very similar to this issue from a year ago. https://github.com/hashicorp/terraform-provider-google/issues/4828

**Comment by edwardmedia** [comment]
@veggie124 I thought you could have run `tf apply` manually. I see below call in your log which appears to be correct. I also noticed that there were a lot of other activities in the log. Because I don't have a full picture of config, I can't tell what's going on. When did you enable the kms service on `spins-poshta-dev` and does the Teeraform runner has permissions?

```
2020-12-02T22:10:31.158Z [DEBUG] plugin.terraform-provider-google_v3.49.0_x5: POST /v1/projects/spins-poshta-dev/locations/global/keyRings?alt=json&keyRingId=poshta-dev-ring HTTP/1.1
```

**Comment by veggie124** [comment]
Alright, so I created a brand new project with the only resource being the keyring and received the same error.

Here is the config for that project:
```
provider "google" {
 region = var.region
 version = "~> 3.34"
}

terraform {
  required_version = "~> 0.13.0"
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "spins"

    workspaces {
      # Overridden by TF Cloud environment, only useful when run locally for Dev.
      # Can be passed via command line parameter to terraform.
      name = "gcp-key-ring-test"
    }
  }
}

locals {
  project_name            = "spins-keyring-test"
}

# Creates GCP Project and enables APIs
module "project-factory" {
  source                  = "terraform-google-modules/project-factory/google"
  version                 = "~> 9.0"

  name                    = local.project_name
  random_project_id       = "false"
  org_id                  = var.org_id
  billing_account         = var.billing_account_id
  activate_apis           = var.gcp_apis
  default_service_account = "keep"
  labels                  = {"cost-center": "productappinfra"}
}

resource "google_kms_key_ring" "spins-test-keyring" {
  name = "spins-test-keyring"
  project = "spins-keyring-test"
  location = "global"
}
```
the cloudkms api is enabled on this project (spins-keyring-test).

Here is the plan showing the project being hardcoded:
![image](https://user-images.githubusercontent.com/1765654/101076838-94401d00-3569-11eb-803f-edfaeb8e8922.png)


Here is the debug log with the same error:
https://gist.github.com/veggie124/5d3ee7ee19a16becb852269f174759f8

**Comment by edwardmedia** [comment]
@veggie124 Besides other permissions, you have to enable the same service(s) on the host project as well. This is common GCP behavior.

**Comment by edwardmedia** [comment]
@veggie124 does this make sense to you? Is this still an issue?

**Comment by edwardmedia** [comment]
@veggie124 closing this assuming it is no longer an issue.
