### ISSUE TITLE
Allow changes to network_interface on compute_instance resource

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#7931]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource

* google_compute_instance

Google currently has a beta feature that allows you to change the network and the subnet of an instance when it is turned off.

Schema fields and update logic needs to be amended to support this feature.

### References

* https://cloud.google.com/compute/docs/instances/migrating-interfaces-between-networks

**Comment by ScottSuarez** [comment]
Hi @upodroid, previously a request was filed [7118](https://github.com/hashicorp/terraform-provider-google/issues/7118) which I fulfilled in a [two](https://github.com/GoogleCloudPlatform/magic-modules/pull/4011) [part](https://github.com/GoogleCloudPlatform/magic-modules/pull/4030) series to add support. So this should be there. Can ask for details on your scenario and why this change might not satisfy your requirements?

**Comment by upodroid** [comment]
Sorry it is a duplicate issue.

We can close it out.

**Comment by ScottSuarez** [comment]
no worries !
