### ISSUE TITLE
Document link update for security command center

### ISSUE THREAD

**Issue by beingminimal** [hashicorp/terraform-provider-google#7946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Hello,

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/scc_source link contains a document link of Binary authorization for GKE as "How to Guides"

Please update it and add the Security Command Center guide.
https://cloud.google.com/security-command-center/docs

Thanks

**Comment by rileykarson** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4339
