### ISSUE TITLE
Will beta 3.50.0 include custom_response_headers in backend_bucket and backend_service?

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#7950]
Also, it seems like it is overdue, when will the release of 3.50.0 (specifically of the beta provider) happen?

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@ggprod Likely it will come out today

**Comment by edwardmedia** [comment]
@ggprod  it has been released 40 minutes ago

**Comment by ggprod** [comment]
@edwardmedia Thanks!
