### ISSUE TITLE
Add backup retention field to Cloud SQL 

### ISSUE THREAD

**Issue by schirayu** [hashicorp/terraform-provider-google#7961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The gcloud command and the API seem to support a `retained-backups-count` field, which allows us to choose how many automated backups we would like to retain. See https://cloud.google.com/sdk/gcloud/reference/beta/sql/instances/create#--retained-backups-count. The current default is 7 days. 

The `google_sql_database_instance` resource in Terraform does not support this field yet. We need this field exposed since 7 days of retention is not enough for us. To achieve this, we are having to write cron jobs, which brings in issues related to managing an extra infrastructure piece in production. It would be great if this was supported directly via Terraform. 

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
settings.backup_configuration.retained_backups_count=<number between 1-365 as per current support>
```

### References

* b/175914398

**Comment by marcfong** [comment]
@rileykarson 

Can we also ensure the `retained-transaction-log-days` field which is used together with `retained-backups-count` as also added as part of this fix?
