### ISSUE TITLE
Lack of the documentation of the import command resources FQN formats

### ISSUE THREAD

**Issue by alex-pravdin-sn** [hashicorp/terraform-provider-google#7964]
It seems like there's no documentation of how to use the import command with GCP. Particularly, I can't find the second parameter format which identifies resources in GCP. It seems to be completely different from the format used in GCP API. 

For example, I somehow invented the format to import a Cloud Run service: `locations/<location>/namespaces/<project id>/services/<service name>`. But I'm stuck on importing Cloud Tasks queues. And I can't see any real help in the documentation.

It would be nice to add this kind of information.

**Comment by edwardmedia** [comment]
@alex-pravdin-sn I am not certain if I understand your question correctly. Not all resources support `Import`. If one does, you should be able to find the format like [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#import) for `cloud run service`.  here is the one for [google_cloud_tasks_queue](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_tasks_queue#import).  Can you be more specific about what you are looking for?

**Comment by alex-pravdin-sn** [comment]
You're right, I didn't read the documentation well, sorry.
