### ISSUE TITLE
Unable to remove google_access_context_manager_access_level in one run when still referenced

### ISSUE THREAD

**Issue by rolandkool** [hashicorp/terraform-provider-google#7969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.50.0

### Affected Resource(s)

* google_access_context_manager_access_level
* google_access_context_manager_service_perimeter

### Terraform Configuration Files

```tf
resource "google_access_context_manager_access_level" "access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/access_level_test"
  title       = "access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_access_level" "another_access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/another_access_level_test"
  title       = "another_access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_service_perimeter" "tftest" {
  provider       = google.vpcsc
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/tftest"
  title          = "tftest"
  perimeter_type = "PERIMETER_TYPE_REGULAR"
  status {
    restricted_services = [
      "storage.googleapis.com",
      "pubsub.googleapis.com",
    ]
    access_levels = [
      google_access_context_manager_access_level.access_level_test.name,
      google_access_context_manager_access_level.another_access_level_test.name,
    ]
  }
  lifecycle {
    ignore_changes = [ status[0].resources ]
  }
}
```

### Expected Behavior

When removing the `another_access_level_test` `google_access_context_manager_access_level` resource and the reference in the `access_levels` array in the `google_access_context_manager_service_perimeter` resource in a single run, terraform fails with the following error:

> google_access_context_manager_access_level.another_access_level_test: Destroying... [id=accessPolicies/1234/accessLevels/another_access_level_test]

Error: Error when reading or editing AccessLevel: googleapi: Error 400: Level name 'another_access_level_test' is not available in this Access Policy resource, but is referenced in 'status' field of Perimeter 'tftest'. If you are trying to delete a Level which is referenced in this Perimeter, you must first remove the reference.

### Actual Behavior

It would expect it to succeed. Terraform should update the perimeter resource first before destroying the access_level.

### Steps to Reproduce

Use example tf files provided, apply the changes to create the perimeter and access levels. Remove one access level and the reference in the perimeter resource. After removal, the config looks like:

```tf
resource "google_access_context_manager_access_level" "access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/access_level_test"
  title       = "access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_service_perimeter" "tftest" {
  provider       = google.vpcsc
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/tftest"
  title          = "tftest"
  perimeter_type = "PERIMETER_TYPE_REGULAR"
  status {
    restricted_services = [
      "storage.googleapis.com",
      "pubsub.googleapis.com",
    ]
    access_levels = [
      google_access_context_manager_access_level.access_level_test.name,
    ]
  }
  lifecycle {
    ignore_changes = [ status[0].resources ]
  }
}
```

Run terraform apply and observe the error.

I've also tried with a `depends_on` on the perimeter resource and on the access_level resource and changed the references in the `access_levels` array to actual names like (`accessPolicies/1234/accessLevels/another_access_level_test`).

In all cases, error remains.

**Comment by edwardmedia** [comment]
@rolandkool can you be more specific how to `remove`? Mind add the config that is after `remove` is done?

**Comment by rolandkool** [comment]
@edwardmedia I've updated the issue description.

**Comment by ScottSuarez** [comment]
I would suggest filing an issue against terraform directly. This issue seems identical to [20196](https://github.com/hashicorp/terraform/issues/20196) which the terraform team has resolved but this seems to be a reemergence. If I look at the state file the dependency chain is there, but terraform isn't calling the api's in the correct order because it seems to be forgetting the dependency chain (which they supposedly fixed). I'm not sure there is anything we can do on our side here.

**Comment by ScottSuarez** [comment]
In the meantime I suggest a two step apply (i know its not ideal and apologize)

**Comment by rolandkool** [comment]
Hi @ScottSuarez 
Thanks for taking the time to look into this. I will file a bug against terraform and reference this issue.
I noticed that tf 0.14 was released and tested with that as well, but same issue.
For now we already do a two step apply and that works, but it is just annoying.

**Comment by rolandkool** [comment]
Unfortunately, there is no solution to fix this. Dependencies only work properly when deleting both resources (perimeter and access level), not when deleting one and updating another as delete is always done before update.
