### ISSUE TITLE
google_compute_instance_template: Error: doesn't support update

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform-provider-google#7971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.1

### Affected Resource(s)

* google_compute_instance_template

### Terraform Configuration Files

```tf
resource "google_compute_instance_template" "test" {
  name_prefix = "${var.env}-${replace(var.role, "_", "-")}-"

  tags = [
    var.env,
  ]

  labels = {
    env      = var.env
  }

  machine_type = var.size

  scheduling {
    automatic_restart = true
  }

  disk {
    source_image = var.build != "" ? "aproject/test-${replace(var.role, "_", "-")}-${var.build}" : "aproject/test-${replace(var.role, "_", "-")}"
    auto_delete  = true
    boot         = true
    disk_type    = "pd-standard"
  }

  network_interface {
    network = var.vpc_name
    access_config {
      nat_ip = ""
    }
  }



  metadata = {
    role                         = var.role
    env                          = var.env
  }

  service_account {
    email = var.compute_service_account.email
    scopes = [
      "cloud-platform",
    ]
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

```
  # module.mymodule.google_compute_instance_template.test will be updated in-place
  ~ resource "google_compute_instance_template" "test" {
        id                   = "projects/arpoject/global/instanceTemplates/myenv-myservice-20201208204739443400000010"
        name                 = "myenv-myservice-20201208204739443400000010"
        tags                 = [
            "myenv",
        ]
        # (12 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

...........

Error: doesn't support update
```

### Expected Behavior

When running consecutive apply/plan steps there should be no diff

### Actual Behavior

An attempt to "update" the template is performed even though there are no changes to the template.
The second issue with this is that templates cannot be updated, new one should be created instead.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by edwardmedia** [comment]
@dawidpogorzelski this is by [design](https://github.com/hashicorp/terraform-provider-google/blob/13e49e48828cb5a2d6ac15f3f1b195209edb4c25/google/resource_compute_instance_template.go#L38). [API](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates) does not support update. Please close the issue if this makes sense to you

**Comment by dawidpogorzelski** [comment]
Well there's 2 issue with the above code,
first that there is a change detected even tho there was no change made and there is actually no change detected even if the diff output but somehow the resource is marked to be updated.
The second is that if any updates happen to the template the google provider should destroy and recreate the resource as it used to be so far. This issue only happens from terraform 0.14.0 on

**Comment by edwardmedia** [comment]
@dawidpogorzelski oh I see. Probably there is not much we can do with it within the provider plugin. Mind file an issue with Terraform against 0.14.0 instead?
