### ISSUE TITLE
Add support for transaction_log_retention_days in Cloud SQL backup configuration

### ISSUE THREAD

**Issue by lupupitkanen** [hashicorp/terraform-provider-google#7980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would help to manage Cloud SQL instance disk usage by setting the number of days to retain binary logs (from one to seven) using Terraform. Support for this in API is now in beta under settings -> backupConfiguration -> transactionLogRetentionDays.

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
backup_configuration {
  binary_log_enabled = true
  enabled = true
  transaction_log_retention_days = 3
}
```

### References

https://cloud.google.com/sql/docs/mysql/backup-recovery/pitr#set-retention

**Comment by isaacseymour** [comment]
It looks like https://github.com/hashicorp/terraform-provider-google/pull/8582 resolved this issue! 🎉

**Comment by roaks3** [comment]
Yea, this appears resolved like you mentioned, thanks!
