### ISSUE TITLE
google_monitoring_dashboard: thresholds are compared as float point numbers

### ISSUE THREAD

**Issue by yegle** [hashicorp/terraform-provider-google#7988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.1

### Affected Resource(s)

* google_monitoring_dashboard

### Terraform Configuration Files

https://github.com/google/exposure-notifications-verification-server/blob/d9e2329c9214f9fe16701e557e7a1f08e3547e73/terraform/alerting/monitoring.tf#L15-L21

### Expected Behavior

The `thresolds` in the dashboard should not cause any diff.

### Actual Behavior

Getting diff each time I run `terraform apply`:

```
  # module.en-alerting.google_monitoring_dashboard.verification-server will be updated in-place
  ~ resource "google_monitoring_dashboard" "verification-server" {
      ~ dashboard_json = jsonencode(
          ~ {                             
              - etag        = "271a84cae5c15075542aa27c2ab5c9a6" -> null
              ~ gridLayout  = {      
                  ~ widgets = [                      
                      ~ {                
                          ~ xyChart = {
                              ~ thresholds   = [
                                  ~ {
                                      ~ value = 0.9950000047683716 -> 0.995
                                        # (1 unchanged element hidden)
                                    },
                                ]
                                # (2 unchanged elements hidden)
                            }
                            # (1 unchanged element hidden)
                        },
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
This is more TF Core issue, did the config ran successfully in prior versions or terraform (< 0.14) ?

**Comment by yegle** [comment]
This was recently added after we upgrade to 0.14, I'm not sure if it worked before.

**Comment by venkykuberan** [comment]
This is not a provider issue, please raise it against Terraform Core. You can try with older version of tf and see if it works and add that to the issue. As we can't do much here, i am closing this one. Sorry for not being very helpful here.

**Comment by yegle** [comment]
Hmm it looks like the upstream think the issue is with the provider: https://github.com/hashicorp/terraform/issues/27305#event-4125566251

I did confirm the API is likely returning 0.995 as expected:

```
$ gcloud monitoring dashboards list --project=xxx|grep threshold -A2
      thresholds:
      - label: SLO Goal
        value: 0.995
```

**Comment by yegle** [comment]
Can we reopen this issue? Per https://github.com/hashicorp/terraform/issues/27305 this is an issue with the provider, thank you!
