### ISSUE TITLE
`google_sql_database_instance.settings.0.replication_type` diff on `"SYNCHRONOUS"` value

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

This affects all Core versions, and all provider versions going back at least a few years.

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "master" {
  name             = "master-instance"
  database_version = "POSTGRES_11"
  region           = "us-central1"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
  }
}
```

### Debug Output

N/A - I haven't experienced this myself yet, likely due to a staggered rollout.

### Panic Output

N/A

### Expected Behavior

No diffs.

### Actual Behavior

Terraform sees a diff on `replication_type`, eg:

```
+ replication_type            = "SYNCHRONOUS"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Users should be able to work around this using `lifecycle.ignore_changes`, eg:

```tf
lifecycle {
  ignore_changes = [settings.0.replication_type]
}
```

That solution will continue to work even if the API behaviour change is reverted. You can also set the value explicitly to `""` (eg `replication_type = ""`) although this will cause a diff if the API returns `"SYNCHRONOUS"` once again.

### References

* b/175317767

**Comment by deekthesqueak** [comment]
Here is the DEBUG output I got for this error
[WARN] Provider "registry.terraform.io/hashicorp/google" produced an invalid plan for module.platform_gcp.google_sql_database_instance.main, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .settings[0].replication_type: planned value cty.StringVal("SYNCHRONOUS") does not match config value cty.NullVal(cty.String) nor prior value cty.StringVal("")
      - .settings[0].location_preference: block count in plan (1) disagrees with count in config (0)
      - .settings[0].backup_configuration: block count in plan (1) disagrees with count in config (0)
