### ISSUE TITLE
How to add already created CMEK in Terraform Template for Dataflow.

### ISSUE THREAD

**Issue by NishantRanout** [hashicorp/terraform-provider-google#7994]
How to add already added CMEK in Terraform Template for Dataflow. I am using Terraform v.0.11.13

**Comment by edwardmedia** [comment]
@NishantRanout Here is the resource you may checkout for the work. If that does not work, can you explain details about what you are trying to do? The latest versions are recommended.. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job

**Comment by NishantRanout** [comment]
@edwardmedia I am trying the below code : - 

provider "google" {
  project= var.project_id 
  region = var.region

resource "google_dataflow_job" "dataflow_job" {
  project               = var.project_id
  region                = var.region
  zone                  = "${var.region}-a"
  name                  = var.project_name
  on_delete             = "cancel"
  max_workers           = var.max_workers
  template_gcs_path     = var.template_location
  temp_gcs_location     = "gs://${var.gcs_location}/tmp_dir"
  service_account_email = var.controller_service_account_email
dataflow_kms_key = <my already creaked CMEK >
  parameters = {
    inputPubSub       = var.input_PubSub_subscription
    outputPubSub      = var.output_PubSub_subscription
  }
 
}

**Comment by NishantRanout** [comment]
everything is working fine until I am defining my own CMEK.

when I am defining dataflow_kms_key in my template it is giving me below error : -

Error : google_dataflow_job.dataflow_job: : invalid or unknown key: dataflow_kms_key

**Comment by NishantRanout** [comment]
I am not able to find out the correct syntax for already created dataflow_kms_key for dataflow terraform template.

**Comment by edwardmedia** [comment]
@NishantRanout currently the resources do not support CMEK. You may file a [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?template=enhancement.md) for the feature request. Closing this issue then
