### ISSUE TITLE
Add support for security center notifications configuration

### ISSUE THREAD

**Issue by indypinball** [hashicorp/terraform-provider-google#7995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please add support for creating notification configurations for findings in security command center

### New or Affected Resource(s)

* google_scc_notification

### Potential Terraform Configuration

```tf
resource "google_scc_notification" "notification" {
  org_id = "123456789"
  name = "The configuration id"
  description = "A description"
  topic = google_pubsub_topic.topic.id
  filter = "state = ACTIVE"
}
```

### References

* https://cloud.google.com/security-command-center/docs/how-to-notifications#create-notification-config

**Comment by pp-patrickpeng** [comment]
+1
