### ISSUE TITLE
Create `3.52.0` release

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7998]
With `3.51.0` going out on 2020/12/14, it's likely to be the last provider release for `google` and `google-beta` in 2020. I'm filing this issue to track our next release, `3.52.0`, which we currently project we'll release on 2021/01/05 or 2021/01/11.

**Comment by c2thorn** [comment]
Release branches for `3.52.0` are cut from commit SHA's `2ebfe917e4d836f01ebc2d9212ab5b44c0a44fdd` and `3b69cf9b38716dce87554757a01506d36f71b65e` for TPG and TPGB respectively. 
Release dates scheduled for `2021/01/11`

**Comment by slevenick** [comment]
3.52.0 is now released
