### ISSUE TITLE
github checks failing during `make website`

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Debug Output

Github checks for terraform-provider-google and terraform-provider-google-beta are currently failing for the `make website` step. See https://travis-ci.org/github/hashicorp/terraform-provider-google/builds/748916234

**Comment by rileykarson** [comment]
Likely handled by doing https://github.com/hashicorp/terraform-provider-google/issues/8001

**Comment by melinath** [comment]
It looks like this is no longer happening - specifically, it looks like the github actions tests are not running `make website`.
