### ISSUE TITLE
Support guestOsFeatures in `google_compute_disk`

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#8012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There doesn't seem to be any other issue requesting this, so making one here. Compute disk supports the `guestOsFeatures` block:
https://cloud.google.com/compute/docs/reference/rest/v1/disks

In https://github.com/hashicorp/terraform-provider-google/issues/7908, it was found that `guestOsFeatures` supports an enum that may need some custom interaction logic with `interface`. We should investigate if the enum and `interface` field are mutually exclusive or if there is more complex logic.

### New or Affected Resource(s)

* google_compute_disk

**Comment by ScottSuarez** [comment]
**note if adding support for this field that this resource has no update method!!** Therefore using O+C or default_if_empty might be needed

**Comment by seboss666** [comment]
Hello, I've just got onto the problem for a client that wants to enforce shielded VMs and also enforcing the naming convention on the boot disk of VMs. I've created the boot disk independantly just to find myself granted with a 412 API error because the disk does not have the feature enabled. As this issue is a good year old already, does anyone that knows golang has already tried to poke at this ?

**Comment by roaks3** [comment]
Appears resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7970
