### ISSUE TITLE
Can't read Cloud Run status URL attribute 

### ISSUE THREAD

**Issue by alex-pravdin-sn** [hashicorp/terraform-provider-google#8014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/google v3.50.0
+ provider registry.terraform.io/hashicorp/google-beta v3.50.0
```

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
provider "google-beta" {
  project = var.project_id
  region = var.region
  zone = var.zone
}

output "status" {
  value = google_cloud_run_service.worker-cloud-run.status.url
}

resource "google_cloud_run_service" "worker-cloud-run" {
  ...
}
```

### Expected Behavior

An URL is outputted.

### Actual Behavior

```
Error: Unsupported attribute

  on main.tf line 44, in output "status":
  44:   value = google_cloud_run_service.worker-cloud-run.status.url
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When I'm printing the whole status property I see a list of parameters:

```tf
output "status" {
  value = google_cloud_run_service.worker-cloud-run.status
}
```
```
Outputs:

status = tolist([
  {
    "conditions" = tolist([
      {
        "message" = ""
        "reason" = ""
        "status" = "True"
        "type" = "Ready"
      },
      {
        "message" = ""
        "reason" = ""
        "status" = "True"
        "type" = "ConfigurationsReady"
      },
      {
        "message" = ""
        "reason" = ""
        "status" = "True"
        "type" = "RoutesReady"
      },
    ])
    "latest_created_revision_name" = "worker-dev2-2kt4m"
    "latest_ready_revision_name" = "worker-dev2-2kt4m"
    "observed_generation" = 2
    "url" = "https://some-url.a.run.app"
  },
])
```

How to read the URL parameter? The documentation lists these status parameters, but how to read them?

**Comment by venkykuberan** [comment]
status is an array type, It has to be referenced like below,
```
output "cloud_run_url"{
        value = google_cloud_run_service.worker-cloud-run.status.0.url
     } 
```

**Comment by alex-pravdin-sn** [comment]
@venkykuberan Thank you.

Also, could you update the documentation that the status is an array? https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#status - I can't see here that it's an array.
