### ISSUE TITLE
 Support Google Cloud Repository as a source of terraform module

### ISSUE THREAD

**Issue by beingminimal** [hashicorp/terraform-provider-google#8015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hello,

Please provide native support for adding the google cloud source repository as the Terraform module's source. As per the given document, it is not supported in a native way like Github and bitbucket.

https://www.terraform.io/docs/modules/sources.html
https://cloud.google.com/source-repositories
How this might work:

The terraform module installer should support installation from a Cloud source repository as source types.

### New or Affected Resource(s)

* Terrafrom modules

**Comment by rileykarson** [comment]
Hey @beingminimal! Mind filing an issue at https://github.com/hashicorp/terraform/issues/new/choose? This repo specifically covers the GCP provider and not Terraform "core" features like modules.
