### ISSUE TITLE
google_bigtable_gc_policy -- support minutes for `max_age` field

### ISSUE THREAD

**Issue by caieo** [hashicorp/terraform-provider-google#8019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It looks like Bigtable Garbage Collection Policy supports more granularity aside from just `days` ([cloud.google.com documentation here](https://cloud.google.com/bigtable/docs/configuring-garbage-collection#top_of_page)). We would like to request support for `minutes` as well as `seconds` for the `max_age` field.

### New or Affected Resource(s)

* google_bigtable_gc_policy

### Potential Terraform Configuration

```tf
resource "google_bigtable_gc_policy" "policy" {
  instance_name = google_bigtable_instance.instance.name
  table         = google_bigtable_table.table.name
  column_family = "name"

  max_age {
    minutes = 60
  }
}
```

### References

* [GoogleCloudPlatform/k8s-config-connector#345](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/345)

**Comment by slevenick** [comment]
Should be fixed by https://github.com/hashicorp/terraform-provider-google/pull/7879
