### ISSUE TITLE
support for other import formats for google_compute_project_metadata_item

### ISSUE THREAD

**Issue by venkykuberan** [hashicorp/terraform-provider-google#8024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_compute_project_metadata_item

### Potential Terraform Configuration
terraform import google_compute_project_metadata_item.enable_oslogin projects/xxxxx/meta-data/key

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #7694 

b/329648793

**Comment by tophed** [comment]
A workaround is to specify the project ID as an environment variable:

`GOOGLE_PROJECT=<project-id> terraform import google_compute_project_metadata_item.<name> <key>`

**Comment by billyfoss** [comment]
I don't see an option to specify the project on the new 'import' block supported in Terraform 1.5.  
So it seems the only way to import these is via the 'terraform import' command line.

**Comment by roaks3** [comment]
Looks straight-forward to fix, we just need to support the `projects/{{project}}/meta-data/{{key}}` import format
