### ISSUE TITLE
Run terraform-validator tests when terraform-google-conversion is changed by MM

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8037]
Now that terraform validator is caught up to terraform-google-conversion, we should make sure that changes to terraform-google-conversion don't break it.

Specifically, even if all the tests for terraform-google-conversion pass, there can still be breaking issues that would be caught by terraform-validator tests. There may also be issues in terraform-google-conversion that would only get caught by terraform-validator's integration tests.

We should run terraform-validator's tests and integration tests any time that terraform-google-conversion is updated (and ensure that they are run using the new terraform-google-conversion code.)

### References

* https://github.com/GoogleCloudPlatform/terraform-validator/issues/158

**Comment by rileykarson** [comment]
This could be achieved by merging conversion into the validator repo

**Comment by melinath** [comment]
We're not going to do this; we'll merge conversion with validator instead.
