### ISSUE TITLE
point_in_time_recovery_enabled is actually not only for PostgreSQL

### ISSUE THREAD

**Issue by czka** [hashicorp/terraform-provider-google#8050]
### Affected Resource(s)

* google_sql_database_instance

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#point_in_time_recovery_enabled reads:

> Valid only for PostgreSQL instances.

Which seems not be the case (anymore?), as documented by Google: https://cloud.google.com/sql/docs/mysql/backup-recovery/pitr.

**Comment by c2thorn** [comment]
Need to verify if this has changed since https://github.com/hashicorp/terraform-provider-google/issues/7147

**Comment by upodroid** [comment]
We can close this issue. PITR is available but as different API fields depending on whether DB version is MySQL or PostgreSQL. It is the job of the end user to pick the right one based on what they are running.

binary_log_enabled for MySQL
point_in_time_recovery_enabled for PostgreSQL
