### ISSUE TITLE
Document Proper Management of Slack Auth Token for google_monitoring_notification_channel

### ISSUE THREAD

**Issue by ssanderson** [hashicorp/terraform-provider-google#8051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is issue is largely a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/3150, which was closed as a result of the additions made in https://github.com/GoogleCloudPlatform/magic-modules/pull/1835. However, even after reading through that issue and the documentation changes made, it wasn't clear to me how to properly manage the `auth_token` field for a Slack notification channel.

The basic issue I've encountered is that I'd prefer not to include the `auth_token` directly in my terraform resource configuration, but if I omit it and instead `terraform import` the resource (as suggested in the above-linked PR), Terraform tries to update the notification the next time I run, which (I believe) will result in Terraform overriding the existing auth token with an invalid or empty one.

What I'm currently doing to work around this issue is using `lifecycle.ignore_changes` to tell terraform not to modify the `labels` or `sensitive_labels` fields of the notification channel. 

Concretely, my configuration looks like this:

```hcl
resource "google_monitoring_notification_channel" "slack" {
  type = "slack"
  display_name = "Slack (${var.env_name})"
  labels = {
    "channel_name" = "#alerts-${var.env_name}"
  }

  sensitive_labels {
    # See note above.
    auth_token = "DUMMY"
  }

  lifecycle {
    ignore_changes = [labels, sensitive_labels]
  }
}
```

Is it expected that the `terraform import` solution currently documented also requires the use of `ignore_changes`? If so, it would probably be helpful to include that in the documented suggestion. I'm happy to post a PR with this update, but I wanted to verify that what I'm doing is reasonable / expected first.

### New or Affected Resource(s)

* google_monitoring_notification_channel

### References

- https://github.com/hashicorp/terraform-provider-google/issues/3150
- https://github.com/GoogleCloudPlatform/magic-modules/pull/1835

**Comment by rileykarson** [comment]
Hey @ssanderson! We don't want to provide opinionated documentation for these kinds of fields inside the provider documentation, I think. However I'm glad you found a configuration that works well for your expectations.
