### ISSUE TITLE
Unable to specify multiple exclusion/hotword rules inside a ruleset

### ISSUE THREAD

**Issue by dwilliams782** [hashicorp/terraform-provider-google#8055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.2

### Affected Resource(s)

* google_data_loss_prevention_inspect_template

### Terraform Configuration Files

```tf
resource "google_data_loss_prevention_inspect_template" "main-scan-template" {
  parent       = "projects/${local.project}"
  description  = example-scan-global"
  display_name = "example-scan-global"

  inspect_config {
    dynamic "info_types" {
      for_each = [
        "AUTH_TOKEN",
        "AWS_CREDENTIALS"
      ]
      content {
        name = info_types.value
      }
    }

    rule_set {
      info_types {
        name = "PHONE_NUMBER"
        }
      }

      rules {
        exclusion_rule {
          dictionary {
            word_list {
              words = [
                "+4412345678",
                "+441234567891"
              ]
            }
          }
          matching_type = "MATCHING_TYPE_FULL_MATCH"
        }
        exclusion_rule {
          regex {
            pattern = "^[0-9]{2}\\.[0-9]\\.[0-9]{4}\\.[0-9]{2,3}$"
          }
          matching_type = "MATCHING_TYPE_FULL_MATCH"
        }
      }
    }
}
```

### Panic Output

```
Error: List longer than MaxItems
Attribute supports 1 item maximum, config has 2 declared

```
### Expected Behavior

We should be able to specify multiple exclusion / hotword rules inside a single ruleset
### Actual Behavior

Terraform errors if more than one hotword and exclusion rule are provided

**Comment by venkykuberan** [comment]
API doesn't allow to set more than one type of `exclusionrule` per ruleset as per the [API doc](https://cloud.google.com/dlp/docs/reference/rest/v2/InspectConfig#exclusionrule)

API throws error like below for your confiig
```
{
    "error": {
        "code": 400,
        "message": "Invalid value at 'inspect_template.inspect_config.rule_set[0].rules[0]' (oneof), oneof field 'type' is already set. Cannot set 'exclusion_rule'",
        "status": "INVALID_ARGUMENT",
        "details": [
            {
                "@type": "type.googleapis.com/google.rpc.BadRequest",
                "fieldViolations": [
                    {
                        "field": "inspect_template.inspect_config.rule_set[0].rules[0]",
                        "description": "Invalid value at 'inspect_template.inspect_config.rule_set[0].rules[0]' (oneof), oneof field 'type' is already set. Cannot set 'exclusion_rule'"
                    }
                ]
            }
        ]
    }
}
```
As provider schema is setup as expected I will close this issue. Please reopen it if feel otherwise

**Comment by dwilliams782** [comment]
Hi,

![image](https://user-images.githubusercontent.com/42545485/103080193-3ed9b780-45cd-11eb-85ee-830b68868891.png)

The GUI definitely supports having multiple rules per ruleset, this is from an existing inspect template we have created.

The api spec linked says that rules is just a list of InspectionRules:

```
"rules": [
    {
      object (InspectionRule)
    }
  ]
```

I can't see any reference to only one being allowed, and obviously this doesn't tie up with the GUI. Any ideas?

**Comment by dwilliams782** [comment]
I don't have any permissions to reopen this issue but I do think it is genuine, or that I am misunderstanding something?

**Comment by dwilliams782** [comment]
I've done more testing today and worked out you can specify multiple `rules` blocks within a rule_set, which is how you can implement multiple exclusion / hotword rules, so `rules` should probably be changed to `rule` given it's singular?

Hope this helps someone else as the documentation is unclear.
