### ISSUE TITLE
Adding Optional Components does not update components or force Dataproc cluster recreation

### ISSUE THREAD

**Issue by BusiPlay** [hashicorp/terraform-provider-google#8063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Terraform Version 0.13.5

### Affected Resource(s)

google_dataproc_cluster.optional_components

### Terraform Configuration Files

`
     software_config {
      image_version = var.dataproc_version
      optional_components = var.dataproc_optional_components
      override_properties = {
        "yarn:yarn.log-aggregation-enable" = true,
        "dataproc:dataproc.conscrypt.provider.enable" = false,
        "hive:hive.metastore.warehouse.dir" = "${google_storage_bucket.dataproc.url}/hive-bucket/hive-warehouse"
      }
    }
`

### Actual Behavior
The Terraform documentation states that 

Due to limitations of the API, all arguments except labels,cluster_config.worker_config.num_instances and cluster_config.preemptible_worker_config.num_instances are non-updatable. Changing others will cause recreation of the whole cluster!

If adding optional components to an already configured cluster, the components are not updated, and the cluster is not destroyed/recreated

### Steps to Reproduce
1. Create Dataproc Cluster with optional components (eg ZOOKEEPER, JUPYTER, ANACONDA, HIVE_WEBHCAT, KERBEROS)
2. Confirm cluster creation with listed components
3. Add Components (eg RANGER,SOLR)
4. Note that Terraform apply appears to apply changes
5. Note that the cluster is not updated with the optional components (eg gcloud dataproc clusters describe does not show added components)

* #0000

**Comment by edwardmedia** [comment]
@BusiPlay can you share the config code you use?

**Comment by edwardmedia** [comment]
@BusiPlay do you have the debug logs available to share?

**Comment by edwardmedia** [comment]
@BusiPlay closing this as no reply received. Feel free to reopen it if you have the details ready to share.
