### ISSUE TITLE
need Data Source for google_compute_disk

### ISSUE THREAD

**Issue by jvkessel** [hashicorp/terraform-provider-google#8068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be very helpful to have a data source for google persistent disks.  

The usecase would be in a situation where I want to create a disk that will not be destroyed when the instance it's attached to is destroyed.   To do this, I would maintain two separate terraform modules: one with persistent resources like my disk and one with ephemeral resources like the instance that can be destroyed whenever not in use.   I would need a data source for the instance to get the self-link of the disk  to attach to the instance.

I originally tried creating the disk as a resource with a lifecycle of "prevent_destroy" but then the whole destroy command fails because one resource has "prevent_destroy".   I found guidance that in Terraform, it's better to create a "persistent resources" module and use Data Sources to link to those resources, so I need one for a disk now.

### New or Affected Resource(s)

new Data Source for google_compute_disk

### Potential Terraform Configuration

```tf
########
# In the Persistent module

resource "google_compute_disk" "persistent-boot-disk" {
    name        = "persistent-boot-disk"
    description = "Persistent AD Server disk"
    type        = "pd-standard"
    size        = 60
    project     = var.google-project.project-id
    zone        = var.google-project.zone1
    image       = "windows-server-2016-dc-v20201208"
    lifecycle {
        prevent_destroy = true
    }
}


########
# In the "Ephemeral" module (separate terraform files and directories from the Persistent module)

data "google_compute_disk" "persistent-boot-disk" {
    name        = "persistent-boot-disk"
    project     = var.google-project.project-id
}

resource "google_compute_instance" "ad-master-win-01" {
    name                        = "ad-master-win-01"
    machine_type                = "e2-standard-4"
    project                     = var.google-project.project-id
    zone                        = var.google-project.zone1
    allow_stopping_for_update   = true
    tags                        = [
        "ad-master"
    ]
    boot_disk {
        source = data.google_compute_disk.persistent-boot-disk.self_link
        auto_delete = false
    }

    network_interface {
        network    = google_compute_network.vpc-dc1.self_link
        subnetwork = google_compute_subnetwork.sn-vpc-dc1-infra.self_link
        network_ip = "10.20.0.3"
    }
}

```

### References

regarding the use of "prevent_destroy" on some resources in a terraform script, it was indicated that the right way to do this with terraform is to put persistent resources in one module and use data sources to reference them from another module:
https://github.com/hashicorp/terraform/issues/3874#issuecomment-733565924

**Comment by walbertus** [comment]
@jvkessel did you find the workaround for your case?
