### ISSUE TITLE
Add support for Eventarc

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#8069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google released an event bus like tool that can trigger cloud run services.
### New or Affected Resource(s)

* google_eventarc_trigger

### References

* https://cloud.google.com/blog/products/serverless/build-event-driven-applications-in-cloud-run
* https://cloud.google.com/run/docs/events/reference/rest/v1beta1/projects.locations.triggers#Trigger

**Comment by rileykarson** [comment]
Note: This resource will be used as our first `tpgtools`/DCL-based resource.

**Comment by upodroid** [comment]
What is that?

**Comment by rileykarson** [comment]
It's a new code generator we're adding alongside Magic Modules (v1), there are some details @ https://github.com/hashicorp/terraform-provider-google/issues/8206 if you're interested.

**Comment by rileykarson** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4476

**Comment by meteatamel** [comment]
Has this been published? I couldn't find it in Terraform docs

**Comment by slevenick** [comment]
@meteatamel It should go out as part of the next release expected this week.

**Comment by slevenick** [comment]
Well it looks like releases are a little behind. Probably will be released next week

**Comment by rileykarson** [comment]
It should be this week!

**Comment by meteatamel** [comment]
Thanks! I'll check later in the week then.

**Comment by meteatamel** [comment]
Looks like it's published on google-beta and supports beta API of Eventarc, thanks! One related question. Any idea when the GA API of Eventarc will be supported on google?
