### ISSUE TITLE
google_compute_url_map: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by yegle** [hashicorp/terraform-provider-google#8070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ tf version
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/google v3.51.0
+ provider registry.terraform.io/hashicorp/google-beta v3.51.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

https://github.com/google/exposure-notifications-server/tree/main/terraform

### Debug Output

https://gist.github.com/000ecf600530d56e132d6aa6d60a41a6

### Expected Behavior

terraform apply finishes without error.

### Actual Behavior

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.en.google_compute_url_map.urlmap-https[0]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google-beta" produced an invalid new value
for .map_id: was cty.NumberIntVal(2.085541984016382821e+18), but now
cty.NumberIntVal(2.0855419840163827e+18).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

Modify `exposure_hosts` variable to the module and run `terraform apply`.

**Comment by yegle** [comment]
I was able to return back to normal by destroying `module.en.google_compute_url_map.urlmap-https[0]` and re-run `terraform apply`.

**Comment by edwardmedia** [comment]
@yegle can you isolate which resource or data source has issues?

**Comment by yegle** [comment]
I think it's `module.en.google_compute_url_map.urlmap-https[0]` that was causing issue.

**Comment by edwardmedia** [comment]
@yegle your config is too broad. Can you run the `google_compute_url_map` to see  if you can repro the issue? Remove the module code, and hardcode the variables, etc. Those things are out of this site focus.

**Comment by yegle** [comment]
I can no longer reproduce the issue on my end as I've destroyed the resource and recreate.

**Comment by edwardmedia** [comment]
@yegle closing the issue then. Feel free to reopen if you can repro it
