### ISSUE TITLE
Facing issue while creating Monitoring Dashboard "google_monitoring_dashboard"

### ISSUE THREAD

**Issue by Sandhya-boreddy** [hashicorp/terraform-provider-google#8073]
Hi,

When I tried to create monitoring dashboard in GCP using terraform script, I am getting error message as "The provider provider.google does not support resource type "google_monitoring_dashboard"

used version = "~> 3.5.0" in providers.tf

Terraform script:
resource "google_monitoring_dashboard" "verification-server" {
  project        = var.project
  dashboard_json = <<EOF
{
  "displayName": "Demo Dashboard",
  "gridLayout": {
    "widgets": [
      {
        "blank": {}
      }
    ]
  }
}

EOF
}

Thanks,
Sandhya

**Comment by edwardmedia** [comment]
@Sandhya-boreddy can you try the version `v.3.51.0`? If the issue remains, can you share your debug log?

**Comment by edwardmedia** [comment]
@Sandhya-boreddy is this still an issue?

**Comment by edwardmedia** [comment]
@Sandhya-boreddy closing this assuming this is no longer an issue. Feel free to reopen if need
