### ISSUE TITLE
google_service_account_key should have a way to rotate the key

### ISSUE THREAD

**Issue by baens** [hashicorp/terraform-provider-google#8075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

A [best practice](https://support.google.com/googleapi/answer/6310037?hl=en) for service account keys is to periodically rotate them to ensure that you have control of them and they have not leaked. Currently, you would have to rename the resource to force a generation, but then you would have to change the variables downstream if you were referencing them. 

It would be nice to implement the [`keepers` block like in the `random` resources.](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers)

### New or Affected Resource(s)

* google_service_account_key

### Potential Terraform Configuration

Before:
```tf
resource "google_service_account_key" "test_20000101" {
  service_account_id = google_service_account.test.name
}

resource "kubernetes_secret" "test" {
  metadata {
    name      = "test"
    namespace = "default"
  }

  data = {
    "account-file.json" = base64decode(google_service_account.test_20000101.private_key)
  }
}
```

After:
```tf
resource "google_service_account_key" "test" {
  keepers = {
    rotation-date = "2000-01-01"
  }
  service_account_id = google_service_account.test.name
}

resource "kubernetes_secret" "test" {
  metadata {
    name      = "test"
    namespace = "default"
  }

  data = {
    "account-file.json" = base64decode(google_service_account.test.private_key)
  }
}
```

**Comment by jwilner** [comment]
I've been looking for this same thing. Currently, I have achieved it with the following, but it'd be nice to do it with something less clever:

```hcl
resource "google_service_account_key" "foo" {
         service_account_id = time_rotating.foo_timer.unix > 0 ? google_service_account.foo.name : google_service_account.foo.name
}
```

**Comment by jwilner** [comment]
I'll submit a PR adding this.
