### ISSUE TITLE
Allow gcloud composer to work with private GKE cluster endpoint via IAP as it works with GCE.

### ISSUE THREAD

**Issue by skolenkin** [hashicorp/terraform-provider-google#8083]
To increase composer usability, please add a possibility to allow gcloud composer to work with private GKE cluster endpoint via IAP as implemented in cloud compute.

Current command creates a cluster with private IP (via what) but then it is unable to communicate to it from remote.

The current implementation of a terraform google provider doesn't allow add airflow connections:
https://github.com/hashicorp/terraform-provider-google/issues/4418

As workaround we can use 'gcloud composer' command:
```
CONNECTION_CREATE_COMMAND="gcloud composer environments run $COMPOSER_ENVIRONMENT \ --project $COMPOSER_PROJECT \ --location ${COMPOSER_LOCATION} \ connections -- --add \ --conn_id=${CONN_ID_BASE}_${app}_${c} \ --conn_type=google_cloud_platform \ --conn_extra '{\"extra__google_cloud_platform__project\": \"${BQ_PROJECT}\", \ \"extra__google_cloud_platform__key_path\": \"${KEY_JSON_FILE_PATH}\", \ \"extra__google_cloud_platform__scope\": \"https://www.googleapis.com/auth/cloud-platform\"}'"
eval $CONNECTION_CREATE_COMMAND
```

The workaround above works if you have public IP as an endpoint for GKE (Composer cluster).

**Comment by edwardmedia** [comment]
@skolenkin help me understand your request. Is this for Terraform provider? If yes, could you add the the config for the details?

**Comment by skolenkin** [comment]
@edwardmedia Because currently terraform doesn't support customization GCP composer we implemented a workaround via gcloud command. But gcloud compose need GKE public endpoint and doesn't support IAP.

**Comment by edwardmedia** [comment]
@skolenkin please be clear and more details about what you want and how we can help. Is this a request for new resource(s)? Or new feature(s) in existing resource(s)? If this is for existing resource(s), please list the name(s) . If you see the features that are supported by GCP api, please post the links to the documents.

Currently Terraform provider supports `google_composer_environment`. I have no clue about the variable `CONNECTION_CREATE_COMMAND` you listed above, and how the provider can help in your case.

**Comment by skolenkin** [comment]
@edwardmedia We want to create additional connections in Airflow (composer) via terraform resource.
Using terraform we can’t do it. Could you please take a look at the following comment in the issue: 
https://github.com/hashicorp/terraform-provider-google/issues/4418#issuecomment-548440892.
  We have found a workaround via cloud command but we have GCP composer which deployed in private GKE cluster and cloud composer command can’t connect to private GKE cluster. 
  Summary:
   1 - Terraform doesn’t support Cloud Composer connection resource
2 - gcloud composer command doesn’t support external connection to private GKE cluster via IAP. 

As a workaround, we created a proxy host in a private network and run gcloud composer command inside the proxy. 
But this solution is not very good.

**Comment by edwardmedia** [comment]
@skolenkin what you request is the same as [#4418](https://github.com/hashicorp/terraform-provider-google/issues/4418#issuecomment-548440892)? #4418 is already labelled as enhancement and has been triaged. If this is true, we should use #4418, do you agree?

**Comment by skolenkin** [comment]
@edwardmedia 
4418 is close to this, but the main issue, that gcloud composer doesn't support IAP, so in case of using IAP 4418 will not resolve it. To create an environment with auth via IAP for gcloud composer, with GKE (private endpoint) it is needed to create a proxy GCE and route traffic via it

**Comment by edwardmedia** [comment]
@skolenkin I am still not sure what we can help. I guess you choose to enable `enable_private_endpoint`. Isn't the connection issue you are facing from that setting? What's wrong about the workaround with IAP and proxy GCE if that works? From Terraform perspective, there are other resources/modules available you can use to manage these resources. To execute commands remotely, have you looked into [remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html) to see if that helps? Please keep in mind, the provider is basically built on top of GCP's public API. If the features you want are supported by API, please add the links. Otherwise, the goal could be hard to achieve. Does this make sense to you?

**Comment by skolenkin** [comment]
@edwardmedia I created a future request in gcloud using the following link https://issuetracker.google.com/issues/new?component=460446&template=1162764.
We can close this issue. 

Thanks
