### ISSUE TITLE
Istio Gateway external Ip

### ISSUE THREAD

**Issue by tarrencev** [hashicorp/terraform-provider-google#8086]
Hi,

I would like to retrieve the `istio-gateway` external ip for DNS record creation. Is there a way to do this right now?

**Comment by edwardmedia** [comment]
@tarrencev Currently supporting istio from the provider is limited. I would say no right now. But I can take a close look if you provide the details about what you want to achieve

**Comment by tarrencev** [comment]
@edwardmedia when enabling the istio addon in gke, an external port is assigned to the ingress gateway. im not sure how to query for this inside the terraform config. one work around it seems is to generate a new external ip and assign it to the gateway

**Comment by edwardmedia** [comment]
@tarrencev in that case, you should be able to use Terraform [output](https://www.terraform.io/docs/configuration/outputs.html) to obtain it

**Comment by tarrencev** [comment]
@edwardmedia is it possible to use an output value from the cluster for the gke provisioned ip? if so, do you know the attribute name? in the workaround case i use the output.

**Comment by edwardmedia** [comment]
@tarrencev  possible. I don't know the attribute name. You should be able to check it by running `tf show` after the cluster is created. It is possible I may have misunderstood your requirement. You may share the config code that shows where the generated ip and its use are.

**Comment by edwardmedia** [comment]
@tarrencev do you still need me to take a look?

**Comment by upodroid** [comment]
You will need to use the `kubernetes_service` data source from the Kubernetes Terraform provider to pull the IP of the service. Once Istio is installed the service lives in the istio-system namespace with the name istio-ingressgateway.

Have a look at this article for how to authenticate to the gke and use it with the kubernetes terraform provider.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#interacting-with-kubernetes

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/service

Bear in mind that Kubernetes is eventually consistent and you may run in to errors.

**Comment by tarrencev** [comment]
perfect thanks! i will check it out

**Comment by edwardmedia** [comment]
@tarrencev is this still an issue?

**Comment by edwardmedia** [comment]
@tarrencev closing this assuming it is no longer a question
