### ISSUE TITLE
Support shielded instance configs for creating google dataproc cluster

### ISSUE THREAD

**Issue by randell-blackline** [hashicorp/terraform-provider-google#8092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support shielded instance configs for creating google  dataproc cluster. Dataproc API supports it https://github.com/googleapis/google-api-go-client/blob/master/dataproc/v1/dataproc-api.json#L3978

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_dataproc_cluster" "dataproc_cluster1" {


    cluster_config {

          gce_cluster_config {
                     shielded_instance_config {
                           enable_integrity_monitoring = true # Optional. Defines whether instances have integrity monitoring enabled. 
                           enable_secure_boot = true # Optional. Defines whether instances have Secure Boot enabled. 
                           enable_vtpm = true # Optional. Defines whether instances have the vTPM enabled.
                    }
          }

  
    } 


}
```

### References

https://github.com/googleapis/google-api-go-client/blob/master/dataproc/v1/dataproc-api.json#L3978

* b/177924389

**Comment by kristamacg** [comment]
Hi all, do we have an ETA on this?
