### ISSUE TITLE
Precondition check failed for google_service_networking_connection

### ISSUE THREAD

**Issue by abergmeier** [hashicorp/terraform-provider-google#8095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/google v3.38.0
+ provider registry.terraform.io/hashicorp/google-beta v3.38.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.9.0

Your version of Terraform is out of date! The latest version
is 0.14.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.vpc.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.name]
  depends_on              = [
    google_compute_network.vpc,
```

### Debug Output

https://gist.github.com/abergmeier/485d42409eefe721271229e1a9383b39

### Expected Behavior

Using this configuration it should apply fine.

### Actual Behavior

```
2020/12/30 13:06:00 [ERROR] eval: *terraform.EvalRefresh, err: googleapi: Error 400: Precondition check failed., failedPrecondition
2020/12/30 13:06:00 [ERROR] eval: *terraform.EvalSequence, err: googleapi: Error 400: Precondition check failed., failedPrecondition

Error: googleapi: Error 400: Precondition check failed., failedPrecondition
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This is probably insufficient error checking in the API rather than the provider.
Am currently changing Permissions so it might be connected to that.

**Comment by edwardmedia** [comment]
@abergmeier there is an [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_connection) that be tested everyday. Yours has not much different. Likely the issue is with your settings. Mind sharing the whole log so I can take a close look?

**Comment by AndreasBergmeier6176** [comment]
@edwardmedia Do you have a way I can get you the non-redacted version privately?

**Comment by AndreasBergmeier6176** [comment]
> Am currently changing Permissions so it might be connected to that.

The thing that confuses me though is that both me (Project Owner) and the CloudBuild Service Account get the same failure.

**Comment by edwardmedia** [comment]
@AndreasBergmeier6176 I would suggest to post the info at [gist](https://gist.github.com/). Please redact appropriately before post. Mainly I need to see the requests and responses with API.

**Comment by AndreasBergmeier6176** [comment]
There you go: https://gist.github.com/AndreasBergmeier6176/f7769304ca97c934267dd235cb45f792

**Comment by edwardmedia** [comment]
@abergmeier the error message returned from api is not super clear. Is `vpn-peer` in the same project `foobar`?
What do you see if you run `gcloud beta services vpc-peerings list --network=vpn-peer`

**Comment by AndreasBergmeier6176** [comment]
> @abergmeier the error returned from api is not super clear.
> Is `vpn-peer` in the same project `foobar`?

Yes

> What do you see if you run `gcloud beta services vpc-peerings list --network=vpn-peer`
```
$ gcloud beta services vpc-peerings list --network=vpn-peer --project brain-ca-cota-dev
ERROR: (gcloud.beta.services.vpc-peerings.list) FAILED_PRECONDITION: Precondition check failed.
```

> I just ran the sample code [above](https://github.com/hashicorp/terraform-provider-google/issues/8095#issuecomment-752652368), it works fine with me. Can you try the same to see if it works in your environment?

Output in the same project is:
```
google_compute_network.peering_network: Creating...
google_compute_network.peering_network: Still creating... [10s elapsed]
google_compute_network.peering_network: Still creating... [20s elapsed]
google_compute_network.peering_network: Still creating... [30s elapsed]
google_compute_network.peering_network: Still creating... [40s elapsed]
google_compute_network.peering_network: Creation complete after 42s [id=projects/foobar/global/networks/peering-network]
google_compute_global_address.private_ip_alloc: Creating...
google_compute_global_address.private_ip_alloc: Still creating... [10s elapsed]
google_compute_global_address.private_ip_alloc: Creation complete after 12s [id=projects/foobar/global/addresses/private-ip-alloc]
google_service_networking_connection.foobar: Creating...
google_service_networking_connection.foobar: Still creating... [10s elapsed]

Error: Error waiting for Create Service Networking Connection: Error code 7, message: Set Service Networking service account as servicenetworking.serviceAgent role on consumer project.
```

**Comment by AndreasBergmeier6176** [comment]
BTW: I tried disabling and enabling Service Network API and it does not solve the problem.

**Comment by edwardmedia** [comment]
@AndreasBergmeier6176 can you check if the billing account is properly set on the project and it does not meet the quote limits?

**Comment by AndreasBergmeier6176** [comment]
What solved this is adding:

```terraform
 binding {
     role = "roles/servicenetworking.serviceAgent"
     members = [
       "serviceAccount:service-${data.google_project.default.number}@service-networking.iam.gserviceaccount.com",
     ]
   }
```

to our `google_project_iam_policy`.
While enabling _Service Network API_ might have implicitly added the serviceAgent role, the policy would have erased it afterwards.
The only thing I cannot yet explain why the erase happened even though we tried applying with `-target`.
Anyway it works now - thanks for all your effort.

**Comment by edwardmedia** [comment]
@AndreasBergmeier6176 I am glad you have resolved the issue. In term of the behavior you see, are you aware of the differences of three iam resources?

**_xxxx_iam_policy_**: Authoritative. Sets the IAM policy for the project and **_replaces any existing policy already attached_**.

**Comment by AndreasBergmeier6176** [comment]
> are you aware of the differences of three iam resources?

Yes. Although we currently are migrating from member/binding to policy.
Would be really good to have a way of disallowing mixing between these, though.
