### ISSUE TITLE
google_sql_user does not support lifecycle

### ISSUE THREAD

**Issue by Legogris** [hashicorp/terraform-provider-google#8096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/google v3.51.0
```

### Affected Resource(s)

* `google_sql_user`

### Terraform Configuration Files

```tf
resource "google_sql_user" "this" {
  instance = "foo"
  name     = "bar"
  password = random_password.this.result
  project  = "myproject"

  lifefycle {
    ignore_changes = [password]
  }
}
```

### Expected Behavior

Plan proposes creating user

### Actual Behavior

```
Error: Unsupported block type

  on main.tf line x, in resource "google_sql_user" "this":
  35:   lifefycle {

Blocks of type "lifefycle" are not expected here.
```

### Steps to Reproduce

1. `terraform apply`

Same result regardless of which attribute is attempted, and with `all`.

**Comment by edwardmedia** [comment]
@Legogris where does you see `lifecycle` should be supported?

**Comment by Legogris** [comment]
@edwardmedia

https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user

Should be expected to work with resources, no? The stanza works fine with any other resource in this porvider I tried with, without being in docs.

**Comment by edwardmedia** [comment]
@Legogris looks like there is a typo in your [code](https://github.com/hashicorp/terraform-provider-google/issues/8096#issue-776442708). Can you try by updating it?
```tf
resource "google_sql_user" "this" {
  instance = "foo"
  name     = "bar"
  password = random_password.this.result
  project  = "myproject"

  lifefycle {.    #<---- shouldn't it be lifecycle instead? 
    ignore_changes = [password]
  }
}
```

**Comment by edwardmedia** [comment]
@Legogris does my above finding solve your problem?

**Comment by Legogris** [comment]
@edwardmedia Can confirm I should have gone to bed way earlier that day - was sure triple-checked that.. PEBKAC, closing.
