### ISSUE TITLE
Support for Certificate Authority service in beta provider?

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#8105]
I'm just curious when the Certificate Authority service and its associated apis will be supported with corresponding resources/data-sources in the beta provider.

Thanks,
Mark

**Comment by edwardmedia** [comment]
@ggprod looks like you are talking about https://githubs .com/hashicorp/terraform-provider-google/issues/7657
It is currently labelled as **goal**, which means there is no firm timeline. If you want to have in the earlier and you have Google's account managers working with you, you may reach out to reset the priority.

**Comment by ggprod** [comment]
@edwardmedia ok, thanks Edward
