### ISSUE TITLE
documentation typo for google_cloud_run_service

### ISSUE THREAD

**Issue by tjwebb** [hashicorp/terraform-provider-google#8106]
The documentation here is incorrect: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-sql

The `metadata` section should be outside of the template section, like this:

```
template {
    ...
}

metadata {
    ...
}
```

**Comment by edwardmedia** [comment]
@tjwebb it looks like there are two different metadata. Both are correct. Below is the link to their APIs. Let me know if that makes sense to you.

https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services

**Comment by edwardmedia** [comment]
@tjwebb I am closing this. Feel free to reopen it if you have different views
