### ISSUE TITLE
HTTP 403 - Forbidden - Creating google_cloudfunctions_function resource

### ISSUE THREAD

**Issue by hkmushtaq** [hashicorp/terraform-provider-google#8107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.26

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "api_deployment_bucket" {
    project = data.google_project.project.number
    name = "${local.project_name}-deployments-bucket"
    location      = var.static_content_bucket_location
}

resource "google_storage_bucket_object" "api_archive" {
  name   = "api-${var.BUILD_ID}.tgz"
  bucket = google_storage_bucket.api_deployment_bucket.name
  source = "../bundle.tgz"
}

resource "google_cloudfunctions_function" "api-function" {
    project = data.google_project.project.number
    region = "us-east4"
    name        = "${local.project_name}-api-function"
    description = "Api"
    runtime     = "nodejs10"

    available_memory_mb   = 128
    source_archive_bucket = google_storage_bucket.api_deployment_bucket.name
    source_archive_object = google_storage_bucket_object.api_archive.name
    trigger_http          = true
    ingress_settings = "ALLOW_INTERNAL_AND_GCLB"
    entry_point = "default"
}
```

### Debug Output

https://gist.github.com/hkmushtaq/aaf123b84866b74d4474d0e6f3c1ca1b

### Expected Behavior

Create the cloud function

### Actual Behavior

Returned 403

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using a service account via the GOOGLE_CREDENTIALS env var - all other resources in terraform get created. Just the cloud function has problems

**UPDATE 1/04/21**:
Upon request, verified the roles were correct
![image](https://user-images.githubusercontent.com/4555208/103559843-c9030500-4e84-11eb-88bc-7f3b939415b4.png)

**Comment by edwardmedia** [comment]
@hkmushtaq Can you review the service account has proper [roles](https://cloud.google.com/functions/docs/concepts/iam#access_control_for_service_accounts) assigned?

**Comment by hkmushtaq** [comment]
Yes, I even added editor and owner roles to test

![image](https://user-images.githubusercontent.com/4555208/103559235-cd7aee00-4e83-11eb-9154-4d6f40b623f7.png)

**Comment by edwardmedia** [comment]
@hkmushtaq what **project** do you provide when you created other resources? I noticed below line in your code. Is it the same as one for other resources?

```
project = data.google_project.project.number
```

```
cloudfunctions.functions.create' denied on resource 'projects/<project-number>/locations/us-east4/functions/myproject-dev-api-function' (or resource may not exist)
```

**Comment by hkmushtaq** [comment]
I use the default one - I only manually specified the project for this to see if it would make a difference. But all resources should be using the same project

________________________________

**Comment by edwardmedia** [comment]
@hkmushtaq under project, there are **id**, **name** and **number**. Which one do you use? Because it is provided with data in your code, I can't tell which one you were using. Can you verify if it is the same as one you used for other resources?

**Comment by edwardmedia** [comment]
@hkmushtaq is this still an issue?

**Comment by edwardmedia** [comment]
@hkmushtaq closing this. Feel free to reopen if this is still an issue

**Comment by hkmushtaq** [comment]
Apologies, I got pulled into some other items. For the time being I worked around this by deploying to cloud run instead. I will try to recreate in a spike project and share the code as soon as I can.
