### ISSUE TITLE
Cloud DNS : Terraform can't remove managed zone labels

### ISSUE THREAD

**Issue by dlaburthe** [hashicorp/terraform-provider-google#8130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.51.0

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

* First apply
```tf
resource "google_dns_managed_zone" "zone1" {
  name     = var.name
  dns_name = var.dns_name

  labels = {
      "lab1" = "tag1",
      "lab2" = "tag2"
  }
}
```

* Modification apply
```tf
resource "google_dns_managed_zone" "zone1" {
  name     = var.name
  dns_name = var.dns_name

  labels = {
      "lab1" = "tag1"
  }
}
```

### Expected Behavior

The label "lab2" should be removed from the managed zone.

### Actual Behavior

The label "lab2" is still present on the managed zone.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I've reached google support with this issue, as I couldn't remove the labels with gcloud either.
The problem with gcloud has been solved but it didn't help terraform.

The google support team provided me the following information :

> It looks like the labels are not being cleared because terraform is using a PATCH request instead of an PUT request. Patch is used for partial updates to specific fields of a resource, but is problematic when it comes to clearing map fields. For example, if you want to add a label to a resource that already has labels: {a: b}, you can send a partial update using a patch method with the following body:
>```
> labels: {c: d}
>```
> And the result will be:
>```
> labels: {
>      a: b
>      c: d
>  }
>```
> So it does not replace the whole labels field with just {c: d}, but instead adds the new label to the existing labels. Therefore when you send a patch request with labels: {}, it doesn't clear the existing labels, but essentially adds an "empty" label to the already existing labels.
> 
> You can work around this by using a PUT request instead of a PATCH request to clear the labels (see our API reference[1]). As it's not our expertise, we cannot be sure how terraform should be configured, but if you can use the gcloud tool to clear labels, even better.

**Comment by venkykuberan** [comment]
@dlaburthe Thank you for filing the issue, i see the issue we will work on it.

**Comment by c2thorn** [comment]
Switching the managed zone resource from PATCH to PUT requires a more fields to be sent:
```
{
  "error": {
    "code": 400,
    "message": "The 'entity.managedZone.id' parameter is required but was missing.",
    "errors": [
      {
        "message": "The 'entity.managedZone.id' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      },
      {
        "message": "The 'entity.managedZone.nameServers[0]' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      },
      {
        "message": "The 'entity.managedZone.nameServers[1]' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      },
      {
        "message": "The 'entity.managedZone.nameServers[2]' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      },
      {
        "message": "The 'entity.managedZone.nameServers[3]' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      },
      {
        "message": "The 'entity.managedZone.creationTime' parameter is required but was missing.",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
```
`id` and `creationTime` would be new fields for the resource, and most likely a custom update encoder so that `nameServers` are sent as well. This is a bit more involved than a normal bug, so I'm adding a label to get it triaged next week.

**Comment by mxdlx** [comment]
I think I'm being hit by the same issue, I created the DNS zones and added labels, then I went and changed them but each terraform apply shows that it needs to update the labels, each and every time, it is really annoying.

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6062
