### ISSUE TITLE
Fix Redis/memcache tests

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#8154]
We've run out of Tenancy Units for network servicing:
```
Error: Error waiting for Create Service Networking Connection: Error code 13, message: You have reached the limit of number of tenant resources in the tenancy unit for service 'servicenetworking.googleapis.com'
```
Need to remove these, hopefully with the API:
https://cloud.google.com/service-infrastructure/docs/service-consumer-management/reference/rest/v1/services.tenancyUnits/delete

**Comment by melinath** [comment]
Causing failures for at least the following tests:

- TestAccRedisInstance_redisInstancePrivateServiceExample
- TestAccMemcacheInstance_update

There's also a separate (I think?) quota issue tracked at https://github.com/hashicorp/terraform-provider-google/issues/9232

**Comment by c2thorn** [comment]
Finally got around to this, reached out to the Service Networking team: b/191659698

**Comment by c2thorn** [comment]
Service networking team deleted the resources for us. Hopefully with the bootstraps set in place, we stop leaking more.
