### ISSUE TITLE
mapping from gcp resource to resource type in terraform

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-google#8161]
Where to find mapping from gcp resource to corresponding resource type in terraform.

I'm trying to do GCLB using terraform however not able to find the right terraform respurce type. is there a mapping table or so to find out the right resource type?

**Comment by edwardmedia** [comment]
@Sreerag74031 there is no such a mapping table as far as I understand. There is a search box in the web documentations, that might be able to help you quickly find the resources you need

[google](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account)
[googel-beta](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/google_service_account)
