### ISSUE TITLE
"role" and "members" arguments missing from generated "google_storage_bucket_iam_binding"

### ISSUE THREAD

**Issue by mayeco** [hashicorp/terraform-provider-google#8162]
GCS import failed

```
terraform validate

Error: Missing required argument

  on storage_bucket_iam_binding.tf line 1, in resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1":
   1: resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1" {

The argument "members" is required, but no definition was found.


Error: Missing required argument

  on storage_bucket_iam_binding.tf line 1, in resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1":
   1: resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1" {

The argument "role" is required, but no definition was found.

```

https://github.com/GoogleCloudPlatform/terraformer/issues/368

**Comment by edwardmedia** [comment]
@mayeco can you provide the command(s) you were using?

**Comment by mayeco** [comment]
hello @edwardmedia 
`terraformer import google --resources=gcs --regions=europe-west1 --projects=XXX`

I assume this run terraform import in background

**Comment by edwardmedia** [comment]
@mayeco can you reference below doc and try to see if any of them works for you?

[import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam#import)

**Comment by edwardmedia** [comment]
@mayeco does any of the formats mentioned above work for you?

**Comment by edwardmedia** [comment]
@mayeco is this still an issue?

**Comment by dvdantunes** [comment]
Hi, I'm having this issue too. 

I can reproduce the same error following the steps on https://github.com/GoogleCloudPlatform/terraformer/issues/368

But in my case I'm using this configuration:

- terraformer version: v0.8.10
- terrafom version: v0.13.6
- google provider version: v3.53.0

Thank you!

**Comment by edwardmedia** [comment]
@mayeco @dvdantunes can you try below config and command to see that works for you? Please refer to the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam#import) for more commands. 

```tf 
resource "google_storage_bucket_iam_binding" "editor" {
}
```
# terraform import google_storage_bucket_iam_binding.editor "b/issue8162 roles/storage.objectViewer"

**Comment by edwardmedia** [comment]
@mayeco @dvdantunes is above example helpful?

**Comment by dvdantunes** [comment]
Hi @edwardmedia, sorry for the late response

I tried what you suggested and it worked. I did the following:

```
# main.tf
resource "google_storage_bucket_iam_binding" "viewer" {
}
```

Then used the `import` on a bucket of my own, similar to the following:

`terraform import google_storage_bucket_iam_binding.viewer "b/bucket-testjp-dev-yl  roles/storage.objectViewer"`

``` bash
google_storage_bucket_iam_binding.viewer: Importing from ID "b/bucket-testjp-dev-yl  roles/storage.objectViewer"...
google_storage_bucket_iam_binding.viewer: Import prepared!
  Prepared google_storage_bucket_iam_binding for import
google_storage_bucket_iam_binding.viewer: Refreshing state... [id=b/bucket-testjp-dev-yl/roles/storage.objectViewer]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

And the following `terraform.tfstate` was generated:

``` hcl
{
  "version": 4,
  "terraform_version": "0.13.6",
  "serial": 1,
  "lineage": "173f5916-90c1-d4c4-ae7c-1054c628a9f5",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "google_storage_bucket_iam_binding",
      "name": "viewer",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "bucket": "b/bucket-testjp-dev-yll",
            "condition": [],
            "etag": null,
            "id": "b/bucket-testjp-dev-yl/roles/storage.objectViewer",
            "members": [],
            "role": "roles/storage.objectViewer"
          },
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
  ]
}

```


Do you want me to do any other test?

**Comment by edwardmedia** [comment]
@mayeco no for you to do other tests. From what I understand, the solution works. I am going to close this issue then. Feel free to reopen it if this is not the case. Thank you

**Comment by chriswood-ps** [comment]
@edwardmedia   hi edward, this works for a single binding but I have thousands to do as produced by terraformer.. will this be fixed beyond this?

**Comment by tobynelson-pdx** [comment]
I am in the same boat as @chriswood-ps  I have hundreds of bindings, will this be fixed in the future?
