### ISSUE TITLE
Remove strcase dependency

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8166]
We use a "strcase" library in exactly one place, and it's for a pretty routine conversion to jsonCamelCase. We can include a few LOC in the provider and cut a dependency.

Reference: b/177115695

**Comment by melinath** [comment]
Resolved by merge of https://github.com/hashicorp/terraform-provider-google/pull/8296 and https://github.com/hashicorp/terraform-provider-google-beta/pull/2900
