### ISSUE TITLE
google_billing_budget documentation and examples are contradicting regarding project field in budget filter

### ISSUE THREAD

**Issue by supersmo** [hashicorp/terraform-provider-google#8170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_billing_budget

### Expected Behavior

Examples in documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget
```
resource "google_billing_budget" "budget" {
  billing_account = data.google_billing_account.account.id
  display_name = "Example Billing Budget"

  budget_filter {
    projects = ["projects/${data.google_project.project.number}"]
  }
```

In the example aboe project.number is used.

In the documentation of the field:
"The budget_filter block supports:

* projects - (Optional) A set of projects of the form projects/{project_id}, specifying that usage from only this set of projects should be included in the budget. If omitted, the report will include all usage for the billing account, regardless of which project the usage occurred on. Only zero or one project can be specified currently."

In our terraform we have used projects/{project_id} but since the latest google provider our terraform plans catch a diff where it wants to replace the field with number -> project_id

So it looks like when the resource is refreshed when creating a plan it gets the number instead of the project_id as it did before.
Looks like the behavior has changed is it a bug or something that needs to be updated in the documentation and release notes?

Which is the correct value to use: project_id as before or number?
Please clarify and make the documentation coherent.

**Comment by venkykuberan** [comment]
@supersmo doc needs to be updated, examples use right attribute (`project,number`). We will fix the doc
