### ISSUE TITLE
google_cloud_run_service knative ready status race condition

### ISSUE THREAD

**Issue by tdamant** [hashicorp/terraform-provider-google#8172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* Terraform v0.14.4
* hashicorp/google v3.52.0

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
terraform {
  required_version = "0.14.4"

  required_providers {
    google = {
      source = "hashicorp/google"
      version = "~> 3"
    }
  }

  backend "gcs" {
    bucket = "[REDACTED]"
  }
}

provider google {
  project = "[REDACTED]"
}

variable application_name {
  type = string
}

variable image {
  type = string
}

resource "google_service_account" service_account {
  account_id = "${var.application_name}-service"
}

resource google_cloud_run_service api {
  name     = var.application_name
  location = "us-east1"

  autogenerate_revision_name = true

  template {
    spec {
      service_account_name = google_service_account.service_account.email

      containers {
        image = var.image

        env {
          name  = "NODE_ENV"
          value = "production"
        }
      }
    }
  }

  traffic {
    latest_revision = true
    percent         = 100
  }
}
```

### Debug Output

https://gist.github.com/tdamant/26cd5c983c47b1a0530393bfbec9f10f

> Note: we have truncated the debug output to the area which seems to be causing the problem. We have also redacted necessary details.

### Expected Behavior

Upon creation of a new cloud run revision Terraform should succeed if that revision achieves a 'ready' state. Similarly, if the revision fails to achieve a 'ready' state terraform should error.

### Actual Behavior

A new revision (`[REDACTED]-2gclx`) was successfully created however the ready check returned the status of the previous revision (ready = false). Terraform exits with a status of 1 however the newly created revision had actually rolled out.
```
"status": {
     "observedGeneration": 134,
     "conditions": [
       {
         "type": "Ready",
         "status": "False",
         "reason": "HealthCheckContainerError",
         "message": "Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.\n\nLogs URL:\nhttps://console.cloud.google.com/logs/viewer?project=[REDACTED]&resource=cloud_run_revision/service_name/[REDACTED]/revision_name/[REDACTED]-skqzj&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22[REDACTED]%22%0Aresource.labels.revision_name%3D%22[REDACTED]-skqzj%22",
         "lastTransitionTime": "2021-01-12T11:44:14.282951Z"
       },
       {
         "type": "ConfigurationsReady",
         "status": "False",
         "reason": "HealthCheckContainerError",
 run_revision%22%0Aresource.labels.service_name%3D%22[REDACTED]%22%0Aresource.labels.revision_name%3D%22[REDACTED]-skqzj%22",
         "lastTransitionTime": "2021-01-12T11:44:14.282951Z"
       },
       {
         "type": "RoutesReady",
         "status": "True",
         "lastTransitionTime": "2021-01-12T11:33:57.178809Z"
       }
     ],
     "latestReadyRevisionName": "[REDACTED]-jr2cm",
     "latestCreatedRevisionName": "[REDACTED]-skqzj",
     "traffic": [
       {
         "revisionName": "[REDACTED]-jr2cm",
         "percent": 100,
         "latestRevision": true
       }
     ],
     "url": "https://[REDACTED]-e6ljcj3fja-ue.a.run.app",
     "address": {
       "url": "https://[REDACTED]-e6ljcj3fja-ue.a.run.app"
     }
```

### Steps to Reproduce

1. Create a service with working container
2. Apply a new revision with a broken container (terraform succeeds)
3. Apply a new revision with a working container (terraform errors)

### Important Factoids

This appears to be a race condition in the knative api because the bug is not always reproducible. Sometimes the ready status returned refers does refer to the most recent configuration.

During testing, we found that if we used a container image that already existed on the knative cluster the issue didn't occur.

Looking at the [`PollCheckKnativeStatus` method](https://github.com/hashicorp/terraform-provider-google/blob/master/google/cloudrun_polling.go#L33) it doesn't take in to account that the `latestCreatedRevisionName` should also equal the revision name of the most recently deployed configuration.

**Comment by slevenick** [comment]
Hm, that's rather annoying. Looking at the responses maybe we should be checking that the observedGeneration is the same as the generation we received in the response to the original PUT request. I'll try adding that and see if it works

**Comment by kostacasa** [comment]
Hi @slevenick , have you had a chance to look into this? It's an issue we hit frequently with TF deployments to Cloud Run.

**Comment by slevenick** [comment]
Ah, I totally had half-written a solution and then got distracted and forgot! https://github.com/GoogleCloudPlatform/magic-modules/pull/4793 should fix this
