### ISSUE TITLE
google_memcache_instance authorized_network

### ISSUE THREAD

**Issue by ahmedfourti** [hashicorp/terraform-provider-google#8177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.14.3

### Affected Resource(s)

* google_memcache_instance

### Terraform Configuration Files

```tf
resource "google_memcache_instance" "this" {
  provider = google-beta.beta
  count        = var.memorystore_type == "memcache" ? 1 : 0
  name         = var.name
  display_name = var.display_name == null ? var.name : var.display_name
  node_count   = var.memcache_node_count
  region       = var.region
  node_config {
    cpu_count      = var.memcache_cpu_count
    memory_size_mb = var.memcache_memory_size_mb
  }
  zones               = var.memcached_zones
  authorized_network  = var.authorized_network
  memcache_version    = var.memcache_version
  dynamic "memcache_parameters" {
    for_each = var.memecache_parameters
    content {
      params = memcache_parameters.value
    }
  }
  labels              = var.labels
}
```

### Expected Behavior

The attibute authorized_network is supposed to be optional as per documentation

`authorized_network - (Optional) The full name of the Google Compute Engine network to which the instance is connected. If left unspecified, the default network will be used.`

Applying multiple time terraform shouldn't face any issue.

### Actual Behavior

Actually the first apply, memcache was provisionned on default network as expected.
At the second apply, terraform is not able to detect the default network and will destroy the instance and create it again

`~ authorized_network    = "projects/[project]/global/networks/default" -> null # forces replacement
`
### Steps to Reproduce

You can reproduce it using the terraform resource and apply twice

**Comment by venkykuberan** [comment]
`authorized_network` should be set as `computed` field in the schema. We will fix it, thank for filing the issue.
