### ISSUE TITLE
BigQuery time_partitioning only accepts DAY as a value

### ISSUE THREAD

**Issue by fiona-streetgroup** [hashicorp/terraform-provider-google#8180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version v0.14.4

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_bigquery_table" "table-ingestion-land_registry_house_price_index" {
  dataset_id = google_bigquery_dataset.dataset-ingestion.dataset_id
  table_id   = "land_registry_house_price_index"

  //  Need to change this to Month
  time_partitioning {
    type = "MONTH"
  }

  labels = {
    env = terraform.workspace
  }

  schema = <<EOF
[
  {
    "name": "date",
    "type": "STRING",
    "mode": "REQUIRED"
  },
  {
    "name": "region_name",
    "type": "STRING",
    "mode": "REQUIRED"
  }
]
EOF

}


```

### Debug Output

Error: expected time_partitioning.0.type to be one of [DAY], got MONTH

  on ingestion/data_lake/table-ingestion-land_registry_house_price_index.tf line 1, in resource "google_bigquery_table" "table-ingestion-land_registry_house_price_index":
   1: resource "google_bigquery_table" "table-ingestion-land_registry_house_price_index" {

### Expected Behavior

Should accept "MONTH" as a value for time_partitioning type

### Actual Behavior

Getting the above error, which mentions "DAY" is the only acceptable value for time_partitioning type

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@fiona-streetgroup can you share the debug log?

**Comment by fiona-streetgroup** [comment]
@edwardmedia please find logs attached
[terraform.log](https://github.com/hashicorp/terraform-provider-google/files/5807582/terraform.log)

**Comment by edwardmedia** [comment]
@fiona-streetgroup I don't see the mentioned error in the log. Below is one host in your log. Without the complete code, it's hard to see what is going on. I do see `terraform-provider-google_v3.5.0_x5` is called. Note the version is pretty old, can you try with the latest version?
Also, what do you see if you run above config alone? 

>Host: sts.amazonaws.com

**Comment by fiona-streetgroup** [comment]
Thanks @edwardmedia - upgrading the provider resolved the issue
