### ISSUE TITLE
Google-Beta Provider Configuration Not Recognized in Airgapped Environments Using TF 0.13+

### ISSUE THREAD

**Issue by jornjohnson** [hashicorp/terraform-provider-google#8182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
TF 0.13.5
TFE (Terraform Enterprise) 202012-2
google-beta 3.52.0

### Affected Resource(s)

All resources defined by google_beta provider.

### Terraform Configuration Files

```
terraform {
  backend "remote" {
    hostname = REDACTED
    organization = REDACTED

    workspaces {
      name = "aif-tf12-tf13-ws2-dev"
    }
  }
}

#locals {
#  tf13_ci                    = REDACTED
#  tf13_label_pau             = REDACTED
#  tf13_label_data_owner      = REDACTED
#  tf13_project_id            = REDACTED
#  tf13_monitoring_project_id = REDACTED
#  tf13_shared_bucket_name    = REDACTED
#  tf13_subnet_name           = REDACTED
#}
#
#module "tf13_mike_lim" {
#  source        = "TFE_REGISTRY/mcc/t-ai-user/google"
#  version       = "1.2.1-b20210111195426"
#  label_version = "1-2-1-b20210111195426"
#
#  env                      = var.env
#  label_billing_project    = var.label_billing_project
#  label_configuration_item = local.tf13_ci
#  label_organization       = var.label_organization
#  label_classification     = var.label_classification
#  label_pau                = local.tf13_label_pau
#  label_data_owner         = local.tf13_label_data_owner
#  label_workspace          = var.label_workspace
#  project_id               = local.tf13_project_id
#  shared_bucket_name       = local.tf13_shared_bucket_name
#  monitoring_project_id    = local.tf13_monitoring_project_id
#  region                   = var.region
#  subnet_name              = local.tf13_subnet_name
#  user_lan_id              = REDACTED
#  user_email               = REDACTED
#}

terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
    }
    google-beta = {
      source = "hashicorp/google-beta"
    }
    google = {
      source = "hashicorp/google"
    }
  }
}
```

### Debug Output
Debug Output - https://gist.github.com/jornjohnson/c8a533f99625ca9fa523cc2e92297ba3

### Expected Behavior

Expected the google-beta provider configuration referenced in the `terraform` block to initialize the provider configurations for destroy actions on the last remaining google-beta defined resources.

### Actual Behavior

Google-beta provider configuration doesn't appear to initialize, forcing terraform to resolve the provider against the public registry `registry.terraform.io`.  In an airgapped environment with no internet access, this attempt at resolution times out.

### Steps to Reproduce

1. Run `terraform init` against airgapped Terraform Enterprise backend using bundled TF 0.13.5 with google-beta, google, and null providers.
2. `terraform plan` which should error out.

### Important Factoids

The configured environment is airgapped with a compiled TF and providers bundle uploaded to a self hosted TFE service.  We've figured out a workaround by defining a dummy data resource in the config to initialize the provider.  Then to finally clean up the config I can perform a `terraform state rm` call against the dummy data resource.

**Comment by edwardmedia** [comment]
@jornjohnson it appears to me this is an area of Terraform as it is a TF's feature? Did it work with different versions of the Google providers?

**Comment by jornjohnson** [comment]
This is specific to only the google-beta provider, so I don't believe this is a terraform issue.  The observed behavior does not extend to any other provider that I tested.  The list includes;

- hashicorp/google-beta
- hashicorp/google
- hashicorp/random
- hashicorp/null
- hashicorp/template
- hashicorp/archive
- hashicorp/vault

Due to our airgapped nature and reliance on bundled versions I was only able to test versions 3.52, 3.51, 3.42, and 3.38.

**Comment by edwardmedia** [comment]
@jornjohnson there is nothing in the provider plugin that handles **Airgapped Environments**. I would suggest file an issue to Terraform to get help from them. Closing this accordingly.

**Comment by slevenick** [comment]
I would suggest asking for support from Hashicorp because support for airgapped environments appears to be a feature of Terraform Enterprise.
