### ISSUE TITLE
GCS data source to download an existing file from a bucket

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#8189]
It would be nice to have a GCS data source that allows download of an existing object in bucket.  It could be added as a new output attribute to the existing google_storage_bucket_object data source: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/storage_bucket_object

**Comment by edwardmedia** [comment]
@ggprod  does [google_storage_bucket_object_content](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/storage_bucket_object_content) work for you?

**Comment by ggprod** [comment]
@edwardmedia Yes, that's perfect, thanks!  I'm not sure how I missed that. Sorry to waste your time.
