### ISSUE TITLE
google_cloudfunctions_function is missing java11 runtime

### ISSUE THREAD

**Issue by eyalzek** [hashicorp/terraform-provider-google#8191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "function" {
  runtime     = "java11"
  ...
}
```

### References

* https://cloud.google.com/functions/docs/concepts/java-runtime
* 
 ```bash
$ gcloud functions deploy --help | grep Choices -A 14
        Choices:

        ◆ nodejs10: Node.js 10
        ◆ nodejs12: Node.js 12
        ◆ nodejs14: Node.js 14
        ◆ python37: Python 3.7
        ◆ python38: Python 3.8
        ◆ python39: Python 3.9
        ◆ go111: Go 1.11
        ◆ go113: Go 1.13
        ◆ java11: Java 11
        ◆ dotnet3: .NET Framework 3
        ◆ ruby26: Ruby 2.6
        ◆ nodejs6: Node.js 6 (deprecated)
        ◆ nodejs8: Node.js 8 (deprecated)
```

**Comment by upodroid** [comment]
Hi

The provider doesn't validate the value that you put in the runtime field. So try to create a function where `runtime = "java11"` and it should work.

If this works for you, please go ahead and close this issue.

Thank you

**Comment by eyalzek** [comment]
> Hi
> 
> The provider doesn't validate the value that you put in the runtime field. So try to create a function where `runtime = "java11"` and it should work.
> 
> If this works for you, please go ahead and close this issue.
> 
> Thank you

Indeed it does. Might make sense to update the resource docs to point to google's official documentation, in order to avoid it getting outdatd
