### ISSUE TITLE
Add support for samples in tpgtools

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8200]
The [DCL](https://github.com/GoogleCloudPlatform/declarative-resource-client-library) provides a bank of samples written in the JSON serialization format of the DCL. We can use those to generate documentation and examples as a successor to MMv1's [Terraform Examples](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/provider/terraform/examples.rb). We should additionally have the ability to attach Terraform-specific samples that exercise Terraform specific features like alternate providers and the random provider.

**Comment by ScottSuarez** [comment]
split off an issue for the sample testing 
https://github.com/hashicorp/terraform-provider-google/issues/9429

**Comment by ScottSuarez** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/4991

**Comment by rileykarson** [comment]
I don't think the parent issue has been complete? @c2thorn

**Comment by ScottSuarez** [comment]
I forked cameron's code so my pr was composite of his work
