### ISSUE TITLE
Convert 3-5 handwritten/MMv1-generated resources to using the DCL

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8205]
Note: This is a stub issue before we decide on a specific set of resources.

**Comment by upodroid** [comment]
The `google_runtimeconfig_config` handwritten resource is a great candidate to convert. I just implemented it's datasource and it is one of the simplest resource in the provider. 2 fields and no operations.

**Comment by rileykarson** [comment]
Note: 2 were completed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5138
