### ISSUE TITLE
Cannot create Bigtable tables on a multi-cluster bigtable instance.

### ISSUE THREAD

**Issue by alanroche** [hashicorp/terraform-provider-google#8213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
To add, here is the Terraform version:
vagrant@xxxxxx:~/workspace/src$ terraform -version
Terraform v0.14.4

Google Provider version is:
hashicorp/google v3.52.0

### Affected Resource(s)

google_bigtable_table

### Terraform Configuration Files

```tf
resource "google_bigtable_instance" "alantest-data-test" {
  provider              = google
  name                  = var.bigtable_instance_name
  deletion_protection   = false
  labels = var.labels_shared

  dynamic "cluster" {
  	for_each = var.bigtable_clusters
  	content {
		cluster_id = "${var.bigtable_cluster_base_name}-${cluster.key}"
		zone = cluster.value["location"]
		num_nodes = cluster.value["node_count"]
		storage_type = "SSD"
    }
  }
}

resource "google_bigtable_app_profile" "bt_app_profile_online" {
  instance = google_bigtable_instance.alantest-data-test.name
  app_profile_id = "${var.bigtable_instance_name}-app-profile-online"
  multi_cluster_routing_use_any = true
  ignore_warnings = true // Cannot destroy/drop without this
}

resource "google_bigtable_app_profile" "bt_app_profile_batch" {
  instance = google_bigtable_instance.alantest-data-test.name
  app_profile_id = "${var.bigtable_instance_name}-app-profile-batch"
  multi_cluster_routing_use_any = true
  ignore_warnings = true // Cannot destroy/drop without this
}

resource "google_bigtable_table" "alantest-data-table-test" {
  depends_on = [google_bigtable_instance.alantest-data-test]
  instance_name = google_bigtable_instance.alantest-data-test.name
  count 		= length(var.bigtable_tables)
  name          = var.bigtable_tables[count.index]
  column_family {
   family = "cf"
  }
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
}

```

NOTE:
The issue also occurs where  3 clusters are created statically (not via a "dynamic" black)
ie. with:
```tf
 # first
  cluster {
    cluster_id   = "${var.bigtable_cluster_base_name}-1"
    zone         = "${var.region}-a"
    num_nodes = 1
    storage_type = "SSD"
  }

    # first
  cluster {
    cluster_id   = "${var.bigtable_cluster_base_name}-2"
    zone         = "${var.region}-b"
    num_nodes = 1
    storage_type = "SSD"
  }

    # first
  cluster {
    cluster_id   = "${var.bigtable_cluster_base_name}-3"
    zone         = "${var.region}-c"
    num_nodes = 1
    storage_type = "SSD"
  }
```
### Debug Output

Unfortunately I cannot create a Gist as it is blocked by our corporate DLP. I will add it in a separate comment below. 
The relevant part is not excessively long.

### Expected Behavior

Tables should have been created successfully on the multi cluster Bigtable instance with no errors, and managed in Terraform State.

### Actual Behavior
- Creating bigtable tables against a Multi Cluster (ie. 3 clusters) Bigtable Instance fails. 
- Creating the same bigtable tables against a Single Cluster Bigtable instance succeeds as expected.
- The tables do actually seem to get created in Bigtable, but the terraform run bombs out and errors out so they are left unmanaged by Terraform state - ie. a subsequent terraform complains that "table already exists" 

The following error is outputted:
Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.

### Steps to Reproduce

Create a Bigtable Instance with more than one cluster in TF.
Create more than one table in the cluser. Observe the error above.

1. `terraform apply`

### Important Factoids

No

### References

* #0000

**Comment by alanroche** [comment]
Debug output (cannot create a Gist due to DLP blocker)

2021/01/12 18:47:17 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
google_bigtable_table.alantest-data-table-test[3]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[0]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[2]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[1]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[4]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[5]: Still creating... [1m10s elapsed]
google_bigtable_table.alantest-data-table-test[7]: Still creating... [1m10s elapsed]
2021/01/12 18:47:22 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_bigtable_table.alantest-data-table-test[0]"
2021/01/12 18:47:22 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2021/01/12 18:47:22 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "google_bigtable_table.alantest-data-table-test[5]"
2021/01/12 18:47:27 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_bigtable_table.alantest-data-table-test[0]"
2021/01/12 18:47:27 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "google_bigtable_table.alantest-data-table-test[5]"
2021/01/12 18:47:27 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
google_bigtable_table.alantest-data-table-test[0]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[3]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[7]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[2]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[1]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[4]: Still creating... [1m20s elapsed]
google_bigtable_table.alantest-data-table-test[5]: Still creating... [1m20s elapsed]
2021/01/12 18:47:32 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_bigtable_table.alantest-data-table-test[0]"
2021/01/12 18:47:32 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2021/01/12 18:47:32 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "google_bigtable_table.alantest-data-table-test[5]"
2021/01/12 18:47:37 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_bigtable_table.alantest-data-table-test[0]"
2021/01/12 18:47:37 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2021/01/12 18:47:37 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "google_bigtable_table.alantest-data-table-test[5]"
google_bigtable_table.alantest-data-table-test[3]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[5]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[7]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[2]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[1]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[4]: Still creating... [1m30s elapsed]
google_bigtable_table.alantest-data-table-test[0]: Still creating... [1m30s elapsed]
2021/01/12 18:47:41 [DEBUG] google_bigtable_table.alantest-data-table-test[4]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:41 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[4] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:41 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[4]
2021/01/12 18:47:41 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[4] has no state, so skipping provisioners
2021/01/12 18:47:41 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[4] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:41 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[4]
2021/01/12 18:47:41 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[4]": visit complete
2021/01/12 18:47:42 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_bigtable_table.alantest-data-table-test[0]"
2021/01/12 18:47:42 [DEBUG] google_bigtable_table.alantest-data-table-test[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:42 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[0] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:42 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[0]
2021/01/12 18:47:42 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[0] has no state, so skipping provisioners
2021/01/12 18:47:42 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[0] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:42 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[0]
2021/01/12 18:47:42 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[0]": visit complete
2021/01/12 18:47:42 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "google_bigtable_table.alantest-data-table-test[5]"
2021/01/12 18:47:42 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2021/01/12 18:47:42 [DEBUG] google_bigtable_table.alantest-data-table-test[5]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:42 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[5] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:42 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[5]
2021/01/12 18:47:42 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[5] has no state, so skipping provisioners
2021/01/12 18:47:42 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[5] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:42 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[5]
2021/01/12 18:47:42 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[5]": visit complete
2021/01/12 18:47:44 [DEBUG] google_bigtable_table.alantest-data-table-test[3]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:44 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[3] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:44 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[3]
2021/01/12 18:47:44 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[3] has no state, so skipping provisioners
2021/01/12 18:47:44 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[3] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:44 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[3]
2021/01/12 18:47:44 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[3]": visit complete
2021/01/12 18:47:44 [DEBUG] google_bigtable_table.alantest-data-table-test[2]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:44 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[2] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:44 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[2]
2021/01/12 18:47:44 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[2] has no state, so skipping provisioners
2021/01/12 18:47:44 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[2] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:44 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[2]
2021/01/12 18:47:44 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[2]": visit complete
2021/01/12 18:47:45 [DEBUG] google_bigtable_table.alantest-data-table-test[1]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:45 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[1] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:45 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[1]
2021/01/12 18:47:45 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[1] has no state, so skipping provisioners
2021/01/12 18:47:45 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[1] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:45 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[1]
2021/01/12 18:47:45 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[1]": visit complete
2021/01/12 18:47:46 [DEBUG] google_bigtable_table.alantest-data-table-test[7]: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.
2021/01/12 18:47:46 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[7] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:46 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[7]
2021/01/12 18:47:46 [TRACE] EvalApplyProvisioners: google_bigtable_table.alantest-data-table-test[7] has no state, so skipping provisioners
2021/01/12 18:47:46 [TRACE] EvalMaybeTainted: google_bigtable_table.alantest-data-table-test[7] encountered an error during creation, so it is now marked as tainted
2021/01/12 18:47:46 [TRACE] EvalWriteState: removing state object for google_bigtable_table.alantest-data-table-test[7]
2021/01/12 18:47:46 [TRACE] vertex "google_bigtable_table.alantest-data-table-test[7]": visit complete
2021/01/12 18:47:46 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/google\"] (close)" errored, so skipping
2021/01/12 18:47:46 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/12 18:47:46 [TRACE] dag/walk: upstream of "root" errored, so skipping


Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.



Error: Error creating column family cf. rpc error: code = Unavailable desc = The service is currently unavailable.


2021-01-12T18:47:46.988Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-12T18:47:46.991Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.52.0/linux_amd64/terraform-provider-google_v3.52.0_x5 pid=3839
2021-01-12T18:47:46.991Z [DEBUG] plugin: plugin exited
make: *** [/home/vagrant/workspace/src/Makefile.infra:7: infra/deploy] Error 1
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$
vagrant@alantest-gcp:~/workspace/src$

**Comment by edwardmedia** [comment]
@alanroche I just ran below code and it works fine for me. Can you review your code of `google_bigtable_table`? Let me know if the static code works for you.

```tf
resource "google_bigtable_instance" "instance" {
  name = "bt-instance-issue8213"
  cluster {
    cluster_id   = "bt-instance1"
    zone         = "us-central1-b"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance2"
    zone         = "us-central1-c"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance3"
    zone         = "us-central1-a"
    num_nodes    = 1
    storage_type = "HDD"
  }

  deletion_protection  = "false"
}

resource "google_bigtable_app_profile" "ap" {
  instance       = google_bigtable_instance.instance.name
  app_profile_id = "bt-profile-issue8213"

  multi_cluster_routing_use_any = true
  ignore_warnings               = true
}

resource "google_bigtable_table" "table" {
  name          = "tf-table-issue8213"
  instance_name = google_bigtable_instance.instance.name
  split_keys    = ["a", "b", "c"]

  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by alanroche** [comment]
So, did some more testing.

The problem is reproducable in your TF above if you add multiple tables, - for me it starts exhibiting on 6 or more tables. 

ie. add the following to the above:
... and you should see:
```
Error: Error creating presplit table. rpc error: code = Unavailable desc = The service is currently unavailable.
```

It looks like the rpc might be timing out? As I say, the tables are actually getting created, its that the TF provider errors and the tables become unmanaged.
 
```tf

resource "google_bigtable_table" "table1" {
  name          = "tf-table-issue8213-1"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}
resource "google_bigtable_table" "table2" {
  name          = "tf-table-issue8213-2"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_bigtable_table" "table3" {
  name          = "tf-table-issue8213-3"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}

resource "google_bigtable_table" "table4" {
  name          = "tf-table-issue8213-4"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}
resource "google_bigtable_table" "table5" {
  name          = "tf-table-issue8213-5"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}
resource "google_bigtable_table" "table6" {
  name          = "tf-table-issue8213-6"
  instance_name = google_bigtable_instance.instance.name
  project = "gti-dev"
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by edwardmedia** [comment]
@alanroche can you post the debug log?

**Comment by alanroche** [comment]
Hi, 
@edwardmedia  The second comment above has the an extract of debug at trace level around the issue, before and after the error.
I looked at the rest and there looked to be nothing remarkable. Do you need more than this? Unfortunately I can't post much more than this as gists are blocked by our security scanners so I am limited to what I can enter in a comment.
Thanks...

**Comment by edwardmedia** [comment]
@alanroche I just tested by appending 6 more tables and it completed successfully. Actually in my test, the entire execution finished pretty fast. I can't repro the issue. It is possible api experiencing some difficulties. Can you try in different time? As you have discovered, the rest is nothing remarkable. As long as the calls are good, this is all the provider focuses. Other issues might be out of reach by the provider.

**Comment by alanroche** [comment]
@edwardmedia I retested on a GCP vm instance to avoid any network issues,
When I tested with 6 tables I got the same result as you, - it applied very quickly and succeeded.  However when I added some more tables (total 12 here, but it also happened on the GCP VM with 10) to the test TF template I was able to reproduce it there too.

Another slight difference is I have specified a column family and some more slit keys, - though I doubt they matter much.

The following template reproduces it for me consistently from a GCP VM:

```tf
resource "google_bigtable_instance" "instance" {
  name = "bt-instance-issue8213"
  cluster {
    cluster_id   = "bt-instance1"
    zone         = "europe-west2-b"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance2"
    zone         = "europe-west2-c"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance3"
    zone         = "europe-west2-a"
    num_nodes    = 1
    storage_type = "HDD"
  }

  deletion_protection  = "false"
}

resource "google_bigtable_app_profile" "ap" {
  instance       = google_bigtable_instance.instance.name
  app_profile_id = "bt-profile-issue8213"
  

  multi_cluster_routing_use_any = true
  ignore_warnings               = true
}

resource "google_bigtable_table" "table1" {
  name          = "tf-table-issue8213-1"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}
resource "google_bigtable_table" "table2" {
  name          = "tf-table-issue8213-2"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}

resource "google_bigtable_table" "table3" {
  name          = "tf-table-issue8213-3"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}

resource "google_bigtable_table" "table4" {
  name          = "tf-table-issue8213-4"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}
resource "google_bigtable_table" "table5" {
  name          = "tf-table-issue8213-5"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}
resource "google_bigtable_table" "table6" {
  name          = "tf-table-issue8213-6"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }
  lifecycle {
    prevent_destroy = false
  }
}
resource "google_bigtable_table" "table7" {
  name          = "tf-table-issue8213-7"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}

resource "google_bigtable_table" "table8" {
  name          = "tf-table-issue8213-8"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}

resource "google_bigtable_table" "table9" {
  name          = "tf-table-issue8213-9"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}

resource "google_bigtable_table" "table10" {
  name          = "tf-table-issue8213-10"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}



resource "google_bigtable_table" "table11" {
  name          = "tf-table-issue8213-11"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}



resource "google_bigtable_table" "table12" {
  name          = "tf-table-issue8213-12"
  instance_name = google_bigtable_instance.instance.name
  
  split_keys = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ]
  column_family {
     family = "cf"
  }

  lifecycle {
    prevent_destroy = false
  }
}


```

**Comment by edwardmedia** [comment]
@alanroche I do the error now after adding the column_family blocks. Unfortunately the reason is likely the api is not able to handle wide concurrent calls. To workaround it, I added depend_on blocks and it seemed fine now. Below is my test code, and let me know if that works for you. 

```tf 
resource "google_bigtable_instance" "instance" {
  name = "bt-instance-issue8213"
  cluster {
    cluster_id   = "bt-instance1"
    zone         = "us-central1-b"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance2"
    zone         = "us-central1-c"
    num_nodes    = 1
    storage_type = "HDD"
  }

  cluster {
    cluster_id   = "bt-instance3"
    zone         = "us-central1-a"
    num_nodes    = 1
    storage_type = "HDD"
  }

  deletion_protection  = "false"
}

resource "google_bigtable_app_profile" "ap" {
  instance       = google_bigtable_instance.instance.name
  app_profile_id = "bt-profile-issue8213"

  multi_cluster_routing_use_any = true
  ignore_warnings               = true
}

resource "google_bigtable_table" "table" {
  name          = "tf-table-issue8213"
  instance_name = google_bigtable_instance.instance.name
  split_keys    = ["a", "b", "c"]

  lifecycle {
    prevent_destroy = false
  }

  column_family {
     family = "cf"
  }
  column_family {
     family = "a"
  }
  column_family {
     family = "b"
  }
  column_family {
     family = "c"
  }
  column_family {
     family = "d"
  }

  depends_on = [
    google_bigtable_app_profile.ap
  ]
}

resource "google_bigtable_table" "table1" {
  name          = "tf-table-issue8213-1"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }

  column_family {
     family = "cf"
  }

  depends_on = [
    google_bigtable_table.table
  ]
}
resource "google_bigtable_table" "table2" {
  name          = "tf-table-issue8213-2"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }
  column_family {
     family = "cf"
  }

  depends_on = [
    google_bigtable_table.table1
  ]
}

resource "google_bigtable_table" "table3" {
  name          = "tf-table-issue8213-3"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }
  column_family {
     family = "cf"
  }
  depends_on = [
    google_bigtable_table.table2
  ]
}

resource "google_bigtable_table" "table4" {
  name          = "tf-table-issue8213-4"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }
  depends_on = [
    google_bigtable_table.table3
  ]
}
resource "google_bigtable_table" "table5" {
  name          = "tf-table-issue8213-5"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }
  column_family {
     family = "cf"
  }
  depends_on = [
    google_bigtable_table.table4
  ]
}
resource "google_bigtable_table" "table6" {
  name          = "tf-table-issue8213-6"
  instance_name = google_bigtable_instance.instance.name
  split_keys = [
    "a",
    "b",
    "c"
  ]
  lifecycle {
    prevent_destroy = false
  }
  column_family {
     family = "cf"
  }
  depends_on = [
    google_bigtable_table.table5
  ]
}
```

**Comment by alanroche** [comment]
I will test the workaround tomorrow, - we would need to generate the the TF template off of something like a Jinja template. The tables are dynamic for our use case and can vary depending deployment environment, - hence driven by a list of maps. However, i don't expect it won't work with a TF looped table resource (ie. with a "count") driven from list of tables. 

IMO this should be fixed by throttling the parallel fan out, as the above is a workaround, not addressing root cause. Creating N tables on a multi cluster instance shouldn't be such an exotic configuration.

**Comment by alanroche** [comment]
I was able to work around the problem with `terraform apply -parallelism=2`.
Still, a workaround,

**Comment by edwardmedia** [comment]
Closing this as the workaround works
