### ISSUE TITLE
Add master_authorized_networks_config option to google_composer_environment resource

### ISSUE THREAD

**Issue by ilicmilan** [hashicorp/terraform-provider-google#8215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Since `google_composer_environment`resource creates GKE cluster in the background, I wish I could specify `master_authorized_networks_config` as we can for [google_container_cluster resoruce](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#master_authorized_networks_config) so we don't have to run this command manually every time we create a private composer environment (GKE cluster):
```
gcloud container clusters update CLUSTER_NAME --enable-master-authorized-networks --master-authorized-networks NETWORKS
```

### New or Affected Resource(s)
* google_composer_environment

### Potential Terraform Configuration

```tf
  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "192.168.0.0/16"
      display_name = "some-network"
    }
  }
```

* #0000

**Comment by upodroid** [comment]
Hello

The API doesn't support setting master authorized networks as part the composer resource. You will need to amend the cluster manually.

https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments

Terraform can only implement what is available in an API.

If you would like to see this in the API, you can here and submit a feature request. https://cloud.google.com/support/docs/issue-trackers#trackers-list

Thank you

**Comment by ilicmilan** [comment]
Hi @upodroid ,

Thanks for the answer.
I have contacted GCP Support regarding this and here is the answer:

> This feature has been requested before. You can track it at the link https://issuetracker.google.com/issues/144873412. The discussion about this feature has been going on internally and we have shared your issue to that discussion as well. Since this doesn't appear to be a common problem, it has been a relatively low priority so far.

**Comment by rileykarson** [comment]
Closing this since it isn't supported in the API.
