### ISSUE TITLE
google_sql_user can not be deleted with database

### ISSUE THREAD

**Issue by matti** [hashicorp/terraform-provider-google#8218]
```
resource "google_sql_database_instance" "default" {
  ...
}

resource "google_sql_user" "default" {
  ...
}
```

--> `failed to deleteuser myuser-1 in instance terraform-20210113104335222300000001: googleapi: Error 400: Invalid request: Invalid request since instance is not running., invalid`

https://stackoverflow.com/questions/63939213/terraform-trying-to-read-the-sql-user-after-database-is-deleted

**Comment by edwardmedia** [comment]
@matti can you share the debug log along with the config that you were using?

**Comment by edwardmedia** [comment]
@matti is this still an issue?

**Comment by matti** [comment]
yes:
- terraform starts to delete the database
- terraform tries to delete the user, but it fails because the instance is shutting down (1s ago)

--> user resource will never be deleted

**Comment by edwardmedia** [comment]
@matti I have just tested below code, and it was fine in running `tf destroy`. Can you provide details about your situations? Config code, debug logs?

```tf
resource "random_id" "db_name_suffix" {
  byte_length = 4
}

resource "google_sql_database_instance" "master" {
  name = "issue8218-instance-${random_id.db_name_suffix.hex}"

  settings {
    tier = "db-f1-micro"
  }
  deletion_protection = false
}

resource "google_sql_user" "users" {
  name     = "issue8218user"
  instance = google_sql_database_instance.master.name
  host     = "me.com"
  password = "changeme"
}
```

**Comment by edwardmedia** [comment]
@matti feel free to reopen this once you are able to provide the details. Thanks
