### ISSUE TITLE
google_container_cluster recurring_window difference is always shown

### ISSUE THREAD

**Issue by translucens** [hashicorp/terraform-provider-google#8226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.4

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "cluster" {
  maintenance_policy {
    recurring_window {
      start_time = "2021-01-15T00:30:00+09:00"
      end_time   = "2021-01-15T04:30:00+09:00"
      recurrence = "FREQ=DAILY"
    }
  }
}
```

### Panic Output

N/A

### Expected Behavior

no difference detected

### Actual Behavior

```
      ~ maintenance_policy {

          ~ recurring_window {
              ~ end_time   = "2021-01-14T19:30:00Z" -> "2021-01-15T04:30:00+09:00"
              ~ start_time = "2021-01-14T15:30:00Z" -> "2021-01-15T00:30:00+09:00"
                # (1 unchanged attribute hidden)
            }
        }
```

### Steps to Reproduce

1.  specify `recurring_window` > `start_time`, `end_time` other than UTC
1. `terraform apply`
1. `terraform plan`
    * difference is still shown

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment]
@translucens the time format for recurring_window has specific requirements. Below doc says 
>Note that GKE may accept other formats, but will return values in UTC, causing a permanent diff.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#recurring_window

Let me know if this make sense to you

**Comment by translucens** [comment]
@edwardmedia Thank you for replying, and I understand this behavior is expected. I overlooked your quoted sentence in the reference.
So this issue is able to be closed.
