### ISSUE TITLE
google_compute_interconnect_attachment: add support for MTU 

### ISSUE THREAD

**Issue by lancekett** [hashicorp/terraform-provider-google#8227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We would like to be able to manage the MTU field for interconnect attachments
These are available fields in the REST API resource, as well as the cloud sdk:
--mtu

The existing terraform resource does not include these fields in the code or the documentation.

### New or Affected Resource(s)

* google_compute_interconnect_attachment

### Potential Terraform Configuration

```tf
resource "google_compute_interconnect_attachment" "default" {
  name              = "on-prem-interconnect"
  interconnect      = "my-interconnect-id"
  router            = google_compute_router.foobar.id
  mtu               = "1500"
}
```

### References

The REST API documentation for the resource specifies the fields and their accepted values here: https://cloud.google.com/compute/docs/reference/rest/v1/interconnectAttachments

This request is similar to #4109, but for different fields.

* b/179510449

**Comment by vabagaria** [comment]
We are building our GCP landing zone entirely using TF and this would be very handy.

**Comment by vabagaria** [comment]
This is a good workaround while waiting for provider update:

```
resource "null_resource" "attachment_mtu_mod" {
  depends_on = [ google_compute_interconnect_attachment.attachment ]

  provisioner "local-exec" {
    command = "gcloud compute interconnects attachments {$var.type} update ${var.name} --mtu=1500 --region=${var.region} --project=${var.project}"
  }
}
```
