### ISSUE TITLE
please align with aws/azurerm provider adding skip_credentials_validation/

### ISSUE THREAD

**Issue by tbugfinder** [hashicorp/terraform-provider-google#8234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to be able to run plan cycles without having to authenticate to GCP.
AWS and AZURE provider have skip_credentials_validation as an initialisation option. Some other options might be needed in addition.
Please align with the other providers.

### New or Affected Resource(s)

* provider initialisation

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
provider tcp {
  skip_credentials_validation = true
  ###??skip_requesting_account_id = true
}
```

### References

* #0000

**Comment by upodroid** [comment]
Hello

Introducting that field in the Google Provider doesn't make sense for a few reasons:
- AWS has it so you can use LocalStack. That is a mock framework for AWS. Google doesn't have an equivalent tool today.
- AWS also has local DynamoDB emulator.
- Google APIs will not work without a valid access token that is generated from a valid google credentials.

As for Azure, I'm not sure why it is there but this PR introduced it https://github.com/terraform-providers/terraform-provider-azurerm/pull/322


https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#connecting-to-local-aws-compatible-solutions 

Thank you

**Comment by tbugfinder** [comment]
Hi @upodroid ,

at least new terraform plan phases could be executed without an authenticated API call and actually that's my use-case.
So it makes sense also for Google independently of local executors and mock frameworks.

Thx.

**Comment by rileykarson** [comment]
@tbugfinder: When you refer to running plan phases, do you mean specifically `terraform plan`? `terraform plan` is absolutely expected to make web requests.

**Comment by tbugfinder** [comment]
@rileykarson let's assume there's no deployment needed at all, no changes to a deployment applicable and the user just want's to learn or showcase terraform + a given provider - in this setup a `terraform plan` doesn't have to do any authenticated web requests to the cloud API.

**Comment by tbugfinder** [comment]
I didn't check how this is implemented within the AWS provider, however it worked for me.
Having that feature, users can support each other within the terraform world without having cloud provider credentials of different kind or have the "risk" of creating costs.

**Comment by rileykarson** [comment]
I'm confused- you're able to perform a `terraform plan` hitting the AWS APIs without authenticating as a given AWS account? That seems undesirable, and like we may be talking about different things.

**Comment by tbugfinder** [comment]
Oh, that's indeed I was looking for.
Excellent!! `terraform plan` can executed without having any google account.
