### ISSUE TITLE
google_billing_budget in v3.52 threshold percentages not being honoured

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#8238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.5

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
resource "google_billing_budget" "budget" {
  provider = google
  count    = var.create_budget ? 1 : 0

  billing_account = var.billing_account
  display_name    = local.display_name

  budget_filter {
    projects               = local.project_numbers
    credit_types_treatment = var.credit_types_treatment
    services               = local.services
  }

  amount {
    specified_amount {
      currency_code = "USD"
      units = tostring(var.amount)
    }
  }

  dynamic "threshold_rules" {
    for_each = var.alert_spent_percents
    content { 
      threshold_percent = threshold_rules.value
    }
  }

  dynamic all_updates_rule {
    for_each = length(local.alert_email_addresses) > 0 ? [1]: []
    content {
      monitoring_notification_channels = [
        for k, v in local.alert_email_addresses:
        google_monitoring_notification_channel.billing_notification_channel[k].id
      ]
      disable_default_iam_recipients = true
    }
  }
}
```

```tf
variable "alert_spent_percents" {
  description = "A list of percentages of the budget to alert on when threshold is exceeded"
  type        = list(number)
  default     = [0.5, 0.7, 1.0]
}
```

### Expected Behavior

It should show 50%, 70% and 100%.

### Actual Behavior

We had some existing budgets alerts set at 50%, 70% and 100%. 
These now show as below in GCP

![image](https://user-images.githubusercontent.com/393945/104943674-051e8580-59ae-11eb-92ee-32c6a14c8291.png)

Below is the output from a plan which doesn't honour the threshold rules and seems to be apply the default.

```tf
+ threshold_rules {
          + spend_basis       = "CURRENT_SPEND"
          + threshold_percent = 80
        }
      + threshold_rules {
          + spend_basis       = "CURRENT_SPEND"
          + threshold_percent = 90
        }
      + threshold_rules {
          + spend_basis       = "CURRENT_SPEND"
          + threshold_percent = 100
        }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@drandell  can you share the debug log?

**Comment by drandell** [comment]
Hi @edwardmedia sadly not. This was taken from my company's internal repository. 
Happy to go ahead and make an example repo to reproduce.

**Comment by drandell** [comment]
It was a config issue overriding the default values, was difficult to spot! 
Closing as working as intended now
