### ISSUE TITLE
Support defining partition expiration in google_bigquery_table

### ISSUE THREAD

**Issue by daniel-dylag-openx** [hashicorp/terraform-provider-google#8240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
In our use case, we have many tables in the same dataset with different requirements about partition expiration time. E.g. there are 3 tables for the same data, but for different aggregation periods: hourly, daily and monthly. The hourly data must be kept only for 2 months, daily for 4 months and monthly for a year. This is normally maintained by setting partition expiration time for each table to respective value and is possible to update in CLI or API by field: `timePartitioning.expirationMs` (https://cloud.google.com/bigquery/docs/managing-partitioned-tables#partition-expiration).
At the moment the only workaround is writing a custom module to run the command to update the setting (but it doesn't detect a change of the setting).
It is currently possible to specify the default partition expiration time in google_bigquery_dataset, but is not sufficient if some tables in the dataset must have different setting than others.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration
There could be a new field `time_partitioning_expiration` available:
```
resource "google_bigquery_table" "default" {
  dataset_id = google_bigquery_dataset.default.dataset_id
  table_id   = "bar"

  time_partitioning {
    type = "DAY"
  }
  time_partitioning_expiration = 518400 # 60 days

}
```

### References

N/A

**Comment by paxorus** [comment]
There is an `expiration_ms` field for the google_bigquery_table resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table.
Example:
```tf
time_partitioning {
    type          = "DAY"
    expiration_ms = 5184000000 # 60 days
}
```

> The time_partitioning block supports:
> expiration_ms - (Optional) Number of milliseconds for which to keep the storage for a partition.

Does it suit your needs, or were you looking for something different?

**Comment by daniel-dylag-openx** [comment]
@paxorus Yes, I don't know how come I overlooked it. Thanks!
