### ISSUE TITLE
google_firebase_project does not consider project parameter.

### ISSUE THREAD

**Issue by p4ranoidandro1d** [hashicorp/terraform-provider-google#8242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version 

$ terraform -v
Terraform v0.13.5

$ terragrunt -v
terragrunt version v0.25.2

Provider version used 3.49.0 and 3.52.0 (same behaviour)

### Affected Resource(s)

* google_firebase_project

### Terraform Configuration Files

*firebase.tf
```tf
resource "google_firebase_project" "default" {
  provider      = google-beta
  project       = google_project.gcp-project.project_id
}
```

*project.tf
```tf
resource "random_id" "project_id_rand" {
  byte_length = 4
}

resource "google_project" "gcp-project" {
  name                = "dumb"
  project_id          = substr(format("%s-%s", "dump", random_id.project_id_rand.hex), 0, 30)
  folder_id           = some_folder_id
  billing_account     = var.billing_account
  auto_create_network = false
}
```

### Debug Output

https://gist.github.com/p4ranoidandro1d/dd4cd441a21d2f8b0e06d3af5760f6d3

### Expected Behavior

Creates a firebase project on provided gcp project

### Actual Behavior

The plan shows the correct project target, but it is not taken into account.
Terraform tries to create the resource on the default project (where the service account used is from).

Issue has already been mentioned an abandoned ticket #7427 

The target google_project is created and the Firebase Management API is enabled.

### Steps to Reproduce

1. `terraform apply`

### References

* #7427

**Comment by edwardmedia** [comment]
@p4ranoidandro1d `google_firebase_project` is for creating *A Google Cloud Firebase instance*. The error you received below complains the API service is not enabled. You may want to take a look at [google_project_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service)

>Error: Error creating Project: googleapi: Error 403: Firebase Management API has not been used in project 700289339729 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebase.googleapis.com/overview?project=700289339729 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by p4ranoidandro1d** [comment]
Thank you Edward, actually, the API's are correctly enabled on the target project ... 
But not on the one hosting the service account used to deploy the resources across the GCP organization..

Wasnt aware of that pre requisite. After enabling it on both the target project and the service account one, the firebase project is  successfully created...

My bad.

Thanks again.
