### ISSUE TITLE
google_compute_security_policy all rules getting recreated

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-google#8251]
While trying to add a new rule to an existing security policy, terraform plan shows all rules will be recreated. Is this an expected behaviour?

**Comment by venkykuberan** [comment]
@Sreerag74031  can you please share your config & plan output to understand what's going on ?

**Comment by mrkaleslie** [comment]
@Sreerag74031 i am getting a similar issue when i add a new rule, existing rules show they want to recreate

```diff

-     - rule {
-         - action      = "allow" -> null
-         - description = "description" -> null
-         - preview     = false -> null
-         - priority    = 100 -> null

-         - match {
-             - versioned_expr = "SRC_IPS_V1" -> null

-             - config {
-                 - src_ip_ranges = [
-                     - "x.x.x.x",
                    ] -> null
                }
            }
        }
+     + rule {
+         + action      = "allow"
+         + description = "description"
+         + priority    = 100

+         + match {
+             + versioned_expr = "SRC_IPS_V1"

+             + config {
+                 + src_ip_ranges = [
+                     + "x.x.x.x.x",
                    ]
                }
            }
        }
```

I found i was able to get around the issue by explicitly specifying `preview  = false`

**Comment by Sreerag74031** [comment]
@mrkaleslie thanks, i think the preview option fixed the issue.

**Comment by mrkaleslie** [comment]
Hi @Sreerag74031 would you be able to reopen this issue, although there is a work around i don't think it constitutes as a fix

**Comment by Sreerag74031** [comment]
Rule recreate issue for match -> config was resolved with including preview option, however for match -> expr the recreate issue is still there. 
reopening the issue for rule match -> expr

**Comment by melinath** [comment]
🤦 accidentally triggered linking between that PR and this ticket. @mrkaleslie to make things easier & because there's a different underlying cause, could you open a new issue for the false positive case you mentioned? Please @ me on it so I can claim it. :-) Thanks!
