### ISSUE TITLE
google_dns_managed_zone reference network by id doesn't work as described

### ISSUE THREAD

**Issue by kuroda** [hashicorp/terraform-provider-google#8252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.5.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
resource "google_dns_managed_zone" "private-zone" {
  name        = "private-zone"
  dns_name    = "example.com."
  description = "Private DNS zone"

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = google_compute_network.network0.id
    }

    networks {
      network_url = google_compute_network.network1.id
    }
  }
}

resource "google_compute_network" "network0" {
  name                            = "network0"
  project                         = var.project
  auto_create_subnetworks         = false
  delete_default_routes_on_create = false
}

resource "google_compute_network" "network1" {
  name                            = "network1"
  project                         = var.project
  auto_create_subnetworks         = false
  delete_default_routes_on_create = false
}
```

### Expected Behavior

According to the official [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone), we can create a private DNS zone by writing like this:

```tf
resource "google_dns_managed_zone" "private-zone" {
  name        = "private-zone"
  dns_name    = "example.com"
  description = "Private DNS zone"

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = google_compute_network.network0.id
    }

    networks {
      network_url = google_compute_network.network1.id
    }
  }
}
```

### Actual Behavior

The above conf file results in the following error:

```
Error: Error creating ManagedZone: googleapi: Error 400: Invalid value for 'entity.managedZone.privateVisibilityConfig.networks[0].networkUrl': 'projects/my-project-id/global/networks/network0', invalid
```

However, I can fix this error by rewriting the conf file as follows:

```tf
resource "google_dns_managed_zone" "private-zone" {
  name        = "private-zone"
  dns_name    = "example.com"
  description = "Private DNS zone"

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = "https://www.googleapis.com/compute/v1/${google_compute_network.network0.id}"
    }

    networks {
      network_url = "https://www.googleapis.com/compute/v1/${google_compute_network.network1.id}"
    }
  }
}
```

The documentation should be fixed.

### Steps to Reproduce

1. `terraform apply`

### References

* #6972

**Comment by edwardmedia** [comment]
@kuroda can you try using the latest version of provider plugin? Below version is pretty old. Let me know if the latest version works for you?

> registry.terraform.io/hashicorp/google v3.5.0

**Comment by kuroda** [comment]
@edwardmedia Yes, you are right. With the latest version, it works as expected. I'm sorry to have taken your time.
