### ISSUE TITLE
Instance Group Template - Missing Lifecycle block docs

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#8254]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template 

Compute instance template documentation mentions the lifecycle block in a section of its own recommended use. 

EDIT:

The instance template should make reference to the terraform docs link; 
https://www.terraform.io/docs/language/meta-arguments/lifecycle.html 

That would be useful. 

Another thing to mention, in the example usage of the data object
```tf
 // boot disk
  disk {
    source_image = google_compute_image.my_image.self_link
  }
```

Is missing the data.

### New or Affected Resource(s)

* compute_instance_template 

### References

* #0000

**Comment by venkykuberan** [comment]
Other example configs in the doc shows how to use/reference `disk` data. I think its adequate enough
