### ISSUE TITLE
Explicitly document the list of resources that use batching

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8257]
We received an internal request (b/178017598) to explicitly document which resources have batching enabled/disabled through batching config.

**Comment by ScottSuarez** [comment]
nit * should we auto generate this?

**Comment by rileykarson** [comment]
It's a big pain to list generated + non-generated stuff together, so I would vote no right now. We end up having to stick a bunch of ruby code into templates.
