### ISSUE TITLE
Quota exceeded after upgrading to v3.53.0

### ISSUE THREAD

**Issue by LipingSun** [hashicorp/terraform-provider-google#8264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v3.53.0

### Affected Resource(s)

* any

### Debug Output
`terraform plan`
```
Error: Error when reading or editing Project Service xxxxx/bigquery.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
Error: Error when reading or editing Project Service xxxxx/logging.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
Error: Error when reading or editing Project Service xxxxx/logging.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
Error: Error when reading or editing Project Service xxxxx/cloudkms.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
Error: Error when reading or editing Project Service xxxxx/monitoring.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
Error: Error when reading or editing Project Service xxxxx/cloudkms.googleapis.com: googleapi: Error 429: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:123456'., rateLimitExceeded
```

The exact same terraform was able to run plan in `v3.52.0` but fails in `v3.53.0`

**Comment by edwardmedia** [comment]
@LipingSun  is this still an issue?

**Comment by LipingSun** [comment]
Tested rollback to v3.52.0 but still got the issue. Probably something changed on the server side. We can close this.
