### ISSUE TITLE
Create two nics in a same VM using terraform

### ISSUE THREAD

**Issue by danilomnds** [hashicorp/terraform-provider-google#8269]
Dear,

I've been trying to create a new network interface for my VM, but I'm facing the following error:

Error: Error waiting for instance to create: Networks must be distinct for NICs attached to a VM.

This is part of my code:

  network_interface {
    subnetwork      = var.host_subnetwork_uri
   # static address
    network_ip      = google_compute_address.static.address
  }

    network_interface {
    subnetwork      = var.host_subnetwork_uri    
    # dynamic address in my subnet that is the same
  }

Do you have any idea about how I should proceed?

Tks
Danilo

**Comment by venkykuberan** [comment]
2nd NIC needs to be attached to a different network. You can try creating a network then attach the ip from that network. Hope the following example helps 

doc - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address

```
resource "google_compute_network" "default" {
  name = "my-network"
}

resource "google_compute_subnetwork" "default" {
  name          = "my-subnet"
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.default.id
}

resource "google_compute_address" "internal_with_subnet_and_address" {
  name         = "my-internal-address"
  subnetwork   = google_compute_subnetwork.default.id
  address_type = "INTERNAL"
  address      = "10.0.42.42"
  region       = "us-central1"
}
```

**Comment by danilomnds** [comment]
I see what you mean and it really makes sense. Thanks for the replication!

Best Regads,
Danilo
