### ISSUE TITLE
min_node_count of 1 results in 0 nodes unless initial_node_count is explicitly set

### ISSUE THREAD

**Issue by katebrenner** [hashicorp/terraform-provider-google#8270]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* container_node_pool

### Terraform Configuration Files

```tf
# config before ( resulted in 0 nodes ) .
resource "google_container_node_pool" "nodes_pools" {
  count              = length(var.regions)
  name               = "${var.machine_type}-${var.regions[count.index]}"
  location           = var.regions[count.index]
  cluster            = google_container_cluster.clusters[count.index].name

  autoscaling {
    min_node_count = 1
    max_node_count = 3
  }

  node_config {
    preemptible     = false
    machine_type    = var.machine_type
    disk_type       = "pd-ssd"
    service_account = google_service_account.gke-cluster.email
  }
}

# after ( resulted in proper amount of nodes ) 

resource "google_container_node_pool" "nodes_pools" {
  count              = length(var.regions)
  name               = "${var.machine_type}-${var.regions[count.index]}"
  location           = var.regions[count.index]
  cluster            = google_container_cluster.clusters[count.index].name
  initial_node_count = 1

  autoscaling {
    min_node_count = 1
    max_node_count = 3
  }

  node_config {
    preemptible     = false
    machine_type    = var.machine_type
    disk_type       = "pd-ssd"
    service_account = google_service_account.gke-cluster.email
  }
}

```

### Expected Behavior

Would have expected 1 node per zone

### Actual Behavior

resulted in 0 nodes

**Comment by edwardmedia** [comment]
@katebrenner below is the comment in the doc for [google_container_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster). Does it make sense?

>initial_node_count - (Optional) The number of nodes to create in this cluster's default node pool. In regional or multi-zonal clusters, this is the number of nodes per zone. Must be set if node_pool is not set. If you're using google_container_node_pool objects with no default node pool, you'll need to set this to a value of at least 1, alongside setting remove_default_node_pool to true.

**Comment by katebrenner** [comment]
@edwardmedia Thank you! Yes that makes sense for `google_container_cluster` ! However, this information is missing from the [container_node_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool#initial_node_count) doc in which I was referencing.  Could it be added there as well for extra clarity?

**Comment by edwardmedia** [comment]
@katebrenner it could. Please file a separate issue labelled document for triage. Closing this issue then. Thank you
