### ISSUE TITLE
google_compute_instance_group not updated properly

### ISSUE THREAD

**Issue by soltex1** [hashicorp/terraform-provider-google#8278]
To simplify, I've updated the post:

Is there any news about this issue?

https://github.com/hashicorp/terraform-provider-google/issues/6127

**Comment by edwardmedia** [comment]
@soltex1 I am afraid no to your below question.  https://github.com/hashicorp/terraform-provider-google/issues/6127 has been labelled `upstream-terraform`. We can't do much without Terraform's support. You may file an issue against Terraform directly to see if that can expedite the process.  Closing the issue then 

>Is there any news about this issue?
