### ISSUE TITLE
Ignore order of BigQuery table columns

### ISSUE THREAD

**Issue by paxorus** [hashicorp/terraform-provider-google#8282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/google v3.32.0
```
### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
# First we apply this config:
resource "google_bigquery_table" "our_table" {
  dataset_id = google_bigquery_dataset.our_dataset.dataset_id
  table_id   = "our_table"
  schema     = <<EOF
  [
    { "mode": "REQUIRED", "name": "x", "type": "INTEGER" },
    { "mode": "REQUIRED", "name": "y", "type": "INTEGER" }
  ]
  EOF
}
```

```tf
# Then swap the columns, and plan:
resource "google_bigquery_table" "our_table" {
  dataset_id = google_bigquery_dataset.our_dataset.dataset_id
  table_id   = "our_table"
  schema     = <<EOF
  [
    { "mode": "REQUIRED", "name": "y", "type": "INTEGER" },
    { "mode": "REQUIRED", "name": "x", "type": "INTEGER" }
  ]
  EOF
}
```

### Debug Output

We use Terraform Enterprise to plan and apply, and I'm not sure how to generate debug output with it.

### Panic Output

None

### Expected Behavior

The diff should be clean in v3.53.0, as it was in v3.39.0. We have confirmation from the GCP Support team that BigQuery columns are not guaranteed to stay in a particular order.

### Actual Behavior

The plan shows that the google_bigquery_table resource needs to be changed, when using provider v3.53.0.

### Steps to Reproduce

1. `terraform init -upgrade` to `google = "~> 3.53.0"`.
2. `terraform apply` with the first TF config.
3. Switch to the second TF config.
2. `terraform plan` will show a diff (that we expect to be suppressed).
3. `terraform apply` will not do anything to the table. It will not re-order the columns, so it's a permadiff.
3. `terraform init -upgrade` to `google = "~> 3.39.0"`.
4. `terraform plan`. The diff will now be clean.

### Important Factoids
* We are using Terraform Enterprise.
* Sometimes our applications cause the BigQuery API to return the columns of a table in a scrambled order, even though the table schema was not modified in any way.

### References

* The fix was introduced in v3.32.0 to resolve #4143. You can see the JSON deep-equals implementation sorts the columns by "name".
* A follow-up change to the fix was made in v3.39.0 to resolve #7193, for the edge case where "name" is not present.
* The fix was removed recently in v3.53.0 to resolve #7979, which adds a diff suppress for a separate issue and removes the sorting that was added earlier.

**Comment by edwardmedia** [comment]
Need to review this [change](https://github.com/GoogleCloudPlatform/magic-modules/pull/4347)

**Comment by afafara** [comment]
Combined with [this](https://github.com/GoogleCloudPlatform/magic-modules/pull/4400) introduced in 3.54.0, reordering causes table to be recreated on apply.

**Comment by rileykarson** [comment]
@ScottSuarez are you able to take a look and determine whether we should revert https://github.com/GoogleCloudPlatform/magic-modules/pull/4400 or attempt to fix-forward? Also see https://github.com/hashicorp/terraform-provider-google/pull/8258#issuecomment-768469108.

**Comment by ScottSuarez** [comment]
I'll /should/ be able to fix forward on this. I wish we had a testcase for this scenario. I did not realize we could reorder the columns. Sorry about that folks ! We'll revert this for next release and work on proper fix for this scenario before checking in.

**Comment by rileykarson** [comment]
@paxorus: To be clear, you're seeing the same behaviour on both `3.32.0` and `3.54.0`? What current provider version are you using?

**Comment by paxorus** [comment]
`3.53.0` behaves incorrectly, `3.39.0` behaves as expected, so different behavior. We have rolled back to and are currently on `3.39.0`. We never tried `3.54.0`.
