### ISSUE TITLE
Add possibility to enable Email/Password authentication on the Identity Platform

### ISSUE THREAD

**Issue by amerello** [hashicorp/terraform-provider-google#8288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

The [identity_platform_oauth_idp_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/identity_platform_default_supported_idp_config)  resource allows to configure OIDC providers on the Identity Platform, which is working as expected.

The Identity Platform also supports `Email/Password` and `Phone` as configurable providers, but the terraform resource doesn't support this feature.

This is [how to enable it manually](https://cloud.google.com/identity-platform/docs/quickstart-email-password#add-provider), but this is of course not great and it would be nice to be able to do this via Terraform

**Comment by wvanderdeijl** [comment]
We are also in the process of moving to Identity Platform with Terraform and found that changing the Identity Platform config at project level is not supported through Terraform. Updating that Config is what is required to enable email/password authentication, but also things like MFA, ClientConfig.Permissions, email templates, custom domains, etcetera

The API itself is described at https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects/updateConfig

**Comment by c2thorn** [comment]
API supports get/update for the project level config and many fields.
https://cloud.google.com/identity-platform/docs/reference/rest/v2/Config

**Comment by ToeFungi** [comment]
Any updates on this?

**Comment by sheikhaafaq** [comment]
Any updates on this?

**Comment by sheikhaafaq** [comment]
Is there any option available in gcloud to create an identity provider by email and password?

**Comment by melinath** [comment]
This is scoped to adding a new resource to support [getting](https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects/getConfig)/[updating](https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects/updateConfig) the default [Config](https://cloud.google.com/identity-platform/docs/reference/rest/v2/Config) object, and specifically only supporting the sign-in config field. All other fields can be excluded for now.

**Comment by ernani** [comment]
Is this related to this issue?
https://github.com/hashicorp/terraform-provider-google/issues/8510

I think there we have a clearer explanation of what's required.

**Comment by StephenWithPH** [comment]
> Is this related to this issue?
> #8510

@ernani ... I did not open this issue, but I believe #8510 addresses supporting email and password signin as this issue requests.

#8510 would certainly satisfy the use case I'm after.
