### ISSUE TITLE
Add google_firebase_android_app resource

### ISSUE THREAD

**Issue by mleonhard** [hashicorp/terraform-provider-google#8293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I wish to automate configuring Firebase Cloud Messaging for Android apps.  This has several purposes:
- eliminate error-prone manual steps
- reduce manual handling of credentials
- bring FCM config under our software development process (code reviews, continuous integration, continuous deployment)

### New or Affected Resource(s)

- `google_firebase_android_app` resource
   - `google_firebase_project_id`
   - `package_name`
   - `google_services_json` attribute

### Potential Terraform Configuration

```tf
resource "google_project" "default" {
  provider = google-beta

  project_id = "app-staging"
  name       = "app-staging"
  org_id     = "123456789"
}

resource "google_firebase_project" "default" {
  provider = google-beta
  project  = google_project.default.project_id
}

resource "google_firebase_android_app" "default" {
  google_firebase_project_id = google_firebase_project.default.id
  package_name = "com.example.app.staging"
}
output "google_services_json" {
  value = google_firebase_android_app.default.google_services_json
}
```

### References

* #2973
* #8292
* #8294

**Comment by slevenick** [comment]
Same as others the other linked requests, we will need a REST API for this

**Comment by mleonhard** [comment]
This ticket is labeled "waiting-response".  Does that mean it is waiting for a response from me?

**Comment by slevenick** [comment]
Ah, nope that was a mistake. There is an API for this, so I've sized & milestoned it

**Comment by Bharathkumarraju** [comment]
@mleonhard when can this be available in tf code?

**Comment by mleonhard** [comment]
@Bharathkumarraju On 2019-01-31, someone filed https://github.com/hashicorp/terraform-provider-google/issues/2973 "Add Support for Firebase".  Google Firebase team ignored it for a year.  Then a Google engineer added support for creating a Firebase project.  A project without resources is useless.  They didn't add the resources.  They did the bare minimum to close the ticket.  They asked me to file tickets for the resources.  Then they ignored these tickets for 2.5 years.  Google Firebase team has let 3.5 years pass without solving the [customer need](https://github.com/hashicorp/terraform-provider-google/issues/2973#issuecomment-564985773).

I expect that this will never get done.

**Comment by Bharathkumarraju** [comment]
@mleonhard  thanks a lot for the clarifications for now it should be manual for us then :)

**Comment by canatella** [comment]
Here is the code for a module I created to do that using the firebase CLI. It's far from perfect, sometimes I need to apply multiple times, but it does the job: https://gist.github.com/canatella/121eab76622679b477bfdb0e19fd99b2 

This is how I use it:
```
provider "google" {
  alias = "user"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email",
  ]
}

data "google_client_config" "default" {
  provider = google.user
}

data "google_service_account_access_token" "default" {
  provider               = google.user
  target_service_account = "something@foobar.iam.gserviceaccount.com"
  scopes                 = ["userinfo-email", "cloud-platform"]
  lifetime               = "3600s"
}

provider "google" {
  access_token = data.google_service_account_access_token.default.access_token
}

module "android_app" {
  source               = "./../firebase-app"
  firebase_admin_token = data.google_service_account_access_token.default.access_token
  project              = google_app_engine_application.hopper.project
  platform             = "android"
  bundle               = "com.foobar"
  name                 = "My application"
}
```

**Comment by Bharathkumarraju** [comment]
@canatella thank you let me test it as well.

**Comment by tylerg-dev** [comment]
FYI: Android App is available in the google-beta provider now: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebase_android_app

**Comment by wyardley** [comment]
I think this can probably be closed now, right?
