### ISSUE TITLE
Provider version transition problem

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform-provider-google#8297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.14.5

### Affected Resource(s)

* google_compute_backend_service

### Terraform Configuration Files

https://github.com/dawidpogorzelski/repro

```tf
resource "google_compute_backend_service" "test" {
  name = "test"
}
```

### Expected Behavior

* `google_compute_backend_service` is created with provider version 3.49
* provider is upgraded to latest version (3.54)
* a destroy plan is generated via `terraform plan -destroy -out=terraform.tfplan`
* destroy plan can be showed in json format `terraform show -json terraform.tfplan`

### Actual Behavior

* `google_compute_backend_service` is created with provider version 3.49
* provider is upgraded to latest version (3.54)
* a destroy plan is generated via `terraform plan -destroy -out=terraform.tfplan`
* destroy plan can't be showed in json format `terraform show -json terraform.tfplan` fails with `Failed to marshal plan to json: error marshaling prior state: unsupported attribute "custom_response_headers"`

### Steps to Reproduce

1. `git clone https://github.com/dawidpogorzelski/repro.git && cd repro`
2. `terraform init`
3. `terraform apply`
4. `terraform init -upgrade`
5. `terraform plan -destroy -out=terraform.tfplan`
6. `terraform show -json terraform.tfplan`

### Important Factoids

First of all the reason this issue appears is that https://github.com/hashicorp/terraform-provider-google/pull/7824 (3.49) added `custom_response_headers` into `google_compute_backend_service` resource which was removed later on in https://github.com/hashicorp/terraform-provider-google/pull/7943 (3.51). 
After upgrading to anything more recent than 3.51, the provider fails to marshal to json `google_compute_backend_service` created by 3.49 because it doesn't know about `custom_response_headers` anymore. This issue is actually bigger than it appears, if we consider how terraform cloud/enterprise work they both generate a destroy plan first as in [5] and then show the generated destroy plan to the user as json via [6] and ask for confirmation. This means that for terraform cloud/enterprise users this provider version transition (3.49-->3.54) issue can stall the whole pipeline.
I would imagine this issue can reappear under many different forms, whenever the elements of a resource change between versions.
Side note: one could attempt to solve this issue by implementing a strict process to ensure that the upgrade of the provider version is only performed after all the resources in that workspace have been destroyed with the version they have been created with but this is quite unrealistic as not all workspaces/resources can be destroyed to begin with and there can be a whole lot of them which creates a lot of overhead.

**Comment by edwardmedia** [comment]
@dawidpogorzelski following your steps, I can't repro the error. I can obtain the json data. Can you share the debug log for each step?

**Comment by dawidpogorzelski** [comment]
Hey @edwardmedia , sure thing
[2-init.log](https://github.com/hashicorp/terraform-provider-google/files/5885587/2-init.log)
[3-apply.log](https://github.com/hashicorp/terraform-provider-google/files/5885588/3-apply.log)
[4-init-upgrade.log](https://github.com/hashicorp/terraform-provider-google/files/5885589/4-init-upgrade.log)
[5-plan.log](https://github.com/hashicorp/terraform-provider-google/files/5885590/5-plan.log)
[6-show.log](https://github.com/hashicorp/terraform-provider-google/files/5885591/6-show.log)

**Comment by edwardmedia** [comment]
@dawidpogorzelski I can repro the error only with Terraform v0.14.5. It is fine with Terraform v0.13.5. There is not much we can do at the provider level. Do you want to file an issue to Terraform instead?

**Comment by dawidpogorzelski** [comment]
Opened https://github.com/hashicorp/terraform/issues/27645 thanks :)

**Comment by edwardmedia** [comment]
@dawidpogorzelski thanks for filing the issue against Terraform code. I am closing this issue then.
