### ISSUE TITLE
[DOC] Add navigation links to "$foo block supports" documentation

### ISSUE THREAD

**Issue by minrk** [hashicorp/terraform-provider-google#8308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This isn't specific to the google provider, but rather all terraform docs. Sorry if this is the wrong place, I didn't find a better one.

Most resources have blocks documented in two places:

1. a short, descriptive summary with a link target, e.g. [google_container_cluster.maintenance_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#maintenance_policy), and
2. a "`foo` block supports:" section which describes in detail what the block supports (this is ~always what I want to be reading)

There are no anchor links for the detailed specifications of the blocks, so it is not possible to navigate to the actual definition of any block via links, only manually scrolling past everything or searching the page for text. It would be super helpful, especially for resources with many options and nested blocks, to have links to the actual block definitions, instead of just the short summaries which are not usually (in my experience) enough to write a block.

Two ideas that would have greatly helped me to navigate block definitions:

- add a `$block-details` anchor for every detailed block definition and make the ubiquitous "Structure is documented below" text link to this
- move the detailed explantations within the existing already-linked definitions, but collapse them by default, e.g. in `<details>`, if keeping the option list concise is a goal

### New or Affected Resource(s)

All documented resources with block definitions, but most especially those with many options, where the link-targed summary and block definition can be many scroll-pages apart. For example: google_container_cluster.maintenance_policy

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#maintenance_policy

**Comment by roaks3** [comment]
Appears fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5192
