### ISSUE TITLE
BigQuery Materialised view update error

### ISSUE THREAD

**Issue by alepuccetti** [hashicorp/terraform-provider-google#8310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform version `0.14.4`

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "my_view" {
  project    = "project_id"
  dataset_id = "dataset_id"
  table_id   = "view_id"

  materialized_view {
    query               = <<EOF
CHANGED_SQL_CODE
EOF
  }

}
```

### Expected Behavior

Correclty update the materialised view. Maybe it needs to be dropped and re-create it.

### Actual Behavior

Error message `Error: googleapi: Error 400: Schema update for materialized views is not supported., invalid`

Worth to note that my SQL code change did not involved actual schema changes

### Steps to Reproduce

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.audit_logs.google_bigquery_table.bq_query_stats_daily_clients will be updated in-place
  ~ resource "google_bigquery_table" "my_view" {
        id                  = "projects/project_id/datasets/dataset_id/tables/talbe_id"

      ~ materialized_view {
          ~ query               = <<-EOT
CHANGE_SQL_CODE
            EOT
        }
    }
```

### References

Support for materialized views were recently added with #7080 to address #6779.

**Comment by edwardmedia** [comment]
@alepuccetti can you provide the configs (before and after the change) and the full debug log?

**Comment by alepuccetti** [comment]
I can post a a redacted version of the SQL code change but I don't have the debug logs. I hoe this is enough to get an idea of the issue.
```sql
with cte as (
select
    date(timestamp) as datestamp,
    project_id,
    event
from `table`
where project_id in (
  'project_id_1', 'project_id_2, 'project_id_3',

  'project_id_4'
  )
)
select
    datestamp,
    project_id,
    count(event) as events
from cte
group by 1,2
```

The only thing that change was the list of `project_ids` in the where clause. So, no actual schema change.

**Comment by edwardmedia** [comment]
@alepuccetti it is more or less related to the `query` field as it is a simple field and the provider just passes it. Without the details, it is hard to evaluate. The debug log could help us understand more. Can you repro the issue with your redacted version of sql code? I'd like to have any version of code of both before and after changes so I can repro the issue.

**Comment by edwardmedia** [comment]
@alepuccetti is this still an issue?

**Comment by alepuccetti** [comment]
I did not have time to reproduce the issue to get the debug logs. Unfortunately, at the moment, I don't have any more information.

**Comment by edwardmedia** [comment]
@alepuccetti Closing the issue then. Feel free to reopen it once you have more info. Thanks

**Comment by gecko655** [comment]
Same issue happened to me. I'd like to write info for this.

Here is my `terraform plan` output that affected by the issue.
It has a typo in a column name `momth`
Table names are blurred.

```
  # google_bigquery_table.dest_table will be updated in-place
  ~ resource "google_bigquery_table" "dest_table" {
        id                  = "projects/dest_project/datasets/dest_dataset/tables/dest_table"
        # (16 unchanged attributes hidden)

      ~ materialized_view {
          ~ query               = <<-EOT
                SELECT
                  user_id,
              -   DATE_TRUNC(date, MONTH) momth,
              +   DATE_TRUNC(date, MONTH) month,
                  min(date) monthly_first_login_date,
                FROM source_project.source_dataset.source_table
                GROUP BY 1,2
            EOT
            # (2 unchanged attributes hidden)
        }
    }
```

Here is `TF_LOG=1 terraform apply` output after respond 'yes' to the prompt.

[terraform_log.txt](https://github.com/hashicorp/terraform-provider-google/files/6047254/terraform_log.txt)


Reproduced versions:
```bash
$ terraform version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.52.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

Hope this helps.

**Comment by gecko655** [comment]
@edwardmedia or someone

Can you reopen this issue? I was not able to reopen it.
