### ISSUE TITLE
google_compute_instance_group is missing subnetwork field

### ISSUE THREAD

**Issue by krathow** [hashicorp/terraform-provider-google#8322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The subnetwork-parameter is missing for this resource, as per the API-description: https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroups/insert

### New or Affected Resource(s)

* google_compute_instance_group

### Potential Terraform Configuration

```tf
resource "google_compute_instance_group" "http" {
  name        = "mygroup"
  network     = "mynet"
  subnetwork = "mysubnet"
  zone        = "us-central-1-a"
  named_port {
    name = "http"
    port = 80
  }
}
```

### References

* #0000

**Comment by c2thorn** [comment]
The documentation indicates that `subnetwork` is an output-only field. Very reasonable to add to the provider.
@krathow your example configuration suggests that you to set `subnetwork` in your configuration, going against the documentation stating that it is output-only. Is this what you were intending?

**Comment by krathow** [comment]
yes, you're right, my fault, I didn't properly read the docs
