### ISSUE TITLE
Addition of each new view taking around an hour

### ISSUE THREAD

**Issue by goyalmunish** [hashicorp/terraform-provider-google#8323]
In our configuration on BigQuery, we have hundreds of datasets and on average hundreds of views in each dataset, with a common terraform state file.

Currently, we are at a stage that a `terraform refresh` is taking more than 30 minutes. Also, I see that `terraform import` for a single view under a directory containing thousands of terraform files takes more than 3 minutes but running the same command after separating out the associated module to a different directory just takes few seconds.

I would appreciate I can get some pointers on best practices for layouts for such a repo of Terraform configuration files and state files (remote).

**Comment by rileykarson** [comment]
`terraform refresh` generally sends 1 GET request per resource and sends only [10 by default](https://www.terraform.io/docs/cli/commands/refresh.html#parallelism-n). Each request is pretty quick but over thousands of resources that'll add up. Hundreds of datasets with hundreds of views in each is within a range of 10,000 - 100,000 pretty quickly and I'm surprised you're not hitting quota issues (or it's possible you are and the provider is retrying them).

I'm not sure why `terraform import` is taking that long, I'd guess it takes a long time to parse a config that large.

I'd recommend considering breaking up your Terraform config into separate pieces. Some considerations I would have are:

- Is it important these all live in the same config and get applied simultaneously? If absolutely necessary to keep it like that, `-target` will limit the scope of affected resources when you're only touching a few or less.
- Are these datasets all within the same project? Splitting into separate configs per-project is fairly common.
- If not, are there other logical splits? Per-environment or per-location etc.
- Failing any of those criteria, a dataset + hundreds of views seems like a complete config all on it's own. Splitting it up to have a single config per dataset would work better.

I've seen [terragrunt](https://terragrunt.gruntwork.io/) used to manage split-up configs en masse. Note that if you're applying across all these configs it's likely you'll have the same `terraform refresh` time as you're seeing here and that the advantages will come entirely from running Terraform on a subset at a time.

---

The other things you could look into:

- increasing the parallelism number mentioned above will probably not impact `terraform import` but will help `refresh` `plan` `apply` and `destroy`.
- if your logs indicate you're running into quota limits and Terraform is retrying requests, increasing the associated quota will lead to a faster execution time.

**Comment by rileykarson** [comment]
Also, closing since I believe this answers your question. I'll reopen if it doesn't, though.
