### ISSUE TITLE
Add Query Insights fields to google_sql_database_instance

### ISSUE THREAD

**Issue by jbuck** [hashicorp/terraform-provider-google#8328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google announced general availability of [Query Insights for Cloud SQL PostgreSQL](https://cloud.google.com/sql/docs/release-notes#January_28_2021) today. This feature enables the [pg_stat_statements extension](https://www.postgresql.org/docs/current/pgstatstatements.html) on your database, and displays the data from it in the GCP console. It is incredibly useful for debugging poorly performing queries and I want to enable it everywhere I'm using Terraform to deploy Cloud SQL instances :)

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "primary" {
  settings {
    insights_config {
      query_insights_enabled  = true
      query_string_length     = 1024
      record_application_tags = true
      record_client_address   = true
    }
  }
}
```

### References

* https://cloud.google.com/blog/products/databases/get-ahead-of-database-performance-issues-with-cloud-sql-insights
* https://cloud.google.com/sql/docs/postgres/insights-overview
* https://cloud.google.com/sql/docs/postgres/using-insights

**Comment by eddy-curv** [comment]
In which version will this be delivered?

**Comment by c2thorn** [comment]
v3.58 which should be released tomorrow.
https://github.com/hashicorp/terraform-provider-google/tree/release-3.58.0
