### ISSUE TITLE
Redis TLS feature introduction

### ISSUE THREAD

**Issue by akumar-lbg** [hashicorp/terraform-provider-google#8331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a use case where a client program wants to connect with Redis instance and the compliance validation states that Redis is not TLS enabled. It also leads to the feature of getting the CA available with redis instance, and should be fetched via tf data resource.

With [GCP documentation](https://cloud.google.com/memorystore/docs/redis/tls-encryption-overview#:~:text=Memorystore%20for%20Redis%20supports%20encrypting,by%20using%20the%20TLS%20protocol) it looks like its a preview feature. 

We are looking for the flag via provided, so that native terraform code can consume it.

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
resource "google_redis_instance" "cache" {
  name           = "tf-test%{random_suffix}"
  tier           = "STANDARD_HA"
  memory_size_gb = 1

  location_id             = "us-central1-a"
  alternative_location_id = "us-central1-f"

  authorized_network = google_compute_network.network.id
  connect_mode       = "PRIVATE_SERVICE_ACCESS"

  redis_version     = "REDIS_4_0"
  display_name      = "Terraform Test Instance"

  tls                 = true

}
```

### References

* https://cloud.google.com/memorystore/docs/redis/tls-encryption-overview#:~:text=Memorystore%20for%20Redis%20supports%20encrypting,by%20using%20the%20TLS%20protocol.

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/8060
