### ISSUE TITLE
`google_compute_router_nat` with dynamic `subnetwork` block recreates all subnetworks on the addition to the `for_each` set

### ISSUE THREAD

**Issue by courteouselk** [hashicorp/terraform-provider-google#8332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```$ terraform -v

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.54.0
+ provider registry.terraform.io/hashicorp/google-beta v3.54.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Affected Resource(s)

* google_compute_router_nat

### Terraform Configuration Files

```tf
resource "google_compute_router_nat" "default" {
  project                            = xxx
  region                             = xxx
  name                               = xxx
  router                             = google_compute_router.default.name
  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
  nat_ip_allocate_option             = "AUTO_ONLY"

  dynamic "subnetwork" {
    for_each = local.subnetworks # <- this is a set that gets one more value in

    content {
      name                     = google_compute_subnetwork.default[subnetwork.value].id
      source_ip_ranges_to_nat  = ["ALL_IP_RANGES"]
    }
  }
}

resource "google_compute_subnetwork" "default" {
  for_each = local.subnetworks

  project                  = xxx
  region                   = xxx
  name                     = each.key
  network                  = google_compute_network.default.self_link
  ip_cidr_range            = local.ranges[each.key]
  private_ip_google_access = true
}
```

### Expected Behavior

When just one more value is added there should be one more `subnetwork` added to the `google_compute_router_nat`.

### Actual Behavior

Instead, `terraform plan` shows that _all_ existing `subnetwork` blocks will be deleted, and then created again (with one extra for the value added to the `for_each` set.

### Steps to Reproduce

1. `terraform plan`

### References

* https://discuss.hashicorp.com/t/dynamic-block-content-update/8965

**Comment by edwardmedia** [comment]
@courteouselk have you tried to add the new subnetwork by removing the dynamic code? I tested it and it seems to be fine without destroy the existing subnetworks. Can you try? If you see the same behavior you might want to double check the use of dynamic code?

**Comment by edwardmedia** [comment]
@courteouselk have you identified if this is an issue with the provider and using of terraform (dynamic) code?

**Comment by courteouselk** [comment]
Hi @edwardmedia, apologies for a delay.  The idea to try to use non-dynamic block did not cross my mind at the time, so I just went ahead with whole re-create approach.  However, in the next couple of weeks I will need to do the similar thing again (i.e. to add one more entry for NAT), and I will be able to test your suggestion.  Considering that the similar test went fine on your side, I do not exclude that the problem I faced could be a result of some backwards incompatibility between the terraform states (we did not touch that particular resource for quite some time, during which we migrated to terraform 0.14 as well as did quite some upgrades with respect to the GCP provider).  So it's possible that the next time there will be no issue.  I will keep you posted.

**Comment by edwardmedia** [comment]
@courteouselk Thanks for taking further steps. Yes, keep me updated

**Comment by edwardmedia** [comment]
@courteouselk Closing this issue then. Feel free to reopen it once you have more info. Thanks

**Comment by courteouselk** [comment]
hi @edwardmedia,

I just tried it with the following:

```terraform
resource "google_compute_router_nat" "default" {
  project                            = xxx
  region                             = xxx
  name                               = xxx
  router                             = google_compute_router.default.name
  source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"
  nat_ip_allocate_option             = "AUTO_ONLY"

  dynamic "subnetwork" {
    for_each = [for sn in local.subnetworks : sn if sn != "new-subnetwork"] # <- this is a set that gets one more value in

    content {
      name                     = google_compute_subnetwork.default[subnetwork.value].id
      source_ip_ranges_to_nat  = ["ALL_IP_RANGES"]
    }
  }

  subnetwork {
    name                     = "projects/xxx/regions/xxx/subnetworks/new-subnetwork"
    source_ip_ranges_to_nat  = ["ALL_IP_RANGES"]
  }
}
```

Still, the effect is the same.  All existing NATs are going to be dropped and recreated.
