### ISSUE TITLE
Unable to delete healthcheck

### ISSUE THREAD

**Issue by sorenhansendk** [hashicorp/terraform-provider-google#8351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_health_check.healthcheck

### Terraform Configuration Files

<pre>
resource "google_compute_health_check" "healthcheck" {

  # Logging is not in GA yet - so this is required
  provider = google-beta

  for_each = {
    for key, instance in var.instances : key => instance
    # Filter out instances there need a healthcheck
    if instance.healthcheck
  }

  name = "${var.group_prefix}-${each.key}"

  timeout_sec         = 10
  healthy_threshold   = 3
  check_interval_sec  = 10
  unhealthy_threshold = 3

  http_health_check {
    host         = "xxx"
    port         = 80
    request_path = "/"
  }

  log_config {
    enable = true
  }
}
</pre>

### Expected Behavior

1. Delete healthcheck

### Actual Behavior

<pre>
google_compute_health_check.healthcheck["all"]: Refreshing state... [id=xxx]

Error: failed to decode planned changes for google_compute_health_check.healthcheck["all"]: error decoding 'before' value: an object with 19 attributes is required (18 given)
</pre>

### Steps to Reproduce

1. `terraform destroy -force`

### Important Factoids

When I remove the `google-beta` reference and `log_config` I am able to destroy.

We use the `v3.54` of the GCP Terraform provider (both beta and official)

**Comment by venkykuberan** [comment]
@sorenhansendk I am able to delete the resource with the same config, just used the static name. Can you try the same on your end ?

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/google v3.54.0
+ provider registry.terraform.io/hashicorp/google-beta v3.54.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```
```
resource "google_compute_health_check" "tcp-health-check" {
  provider    = google-beta
  name        = "http-health-check"
  description = "Health check via tcp"

  
  timeout_sec         = 10
  healthy_threshold   = 3
  check_interval_sec  = 10
  unhealthy_threshold = 3

  http_health_check {
    host         = "xxx"
    port         = 80
    request_path = "/"
  }

  log_config {
    enable = true
  }
}
```

**Comment by mateuszkwiatkowski** [comment]
I had similar problem just with AWS provider and I fixed it with upgrade of provider.

**Comment by sorenhansendk** [comment]
@venkykuberan I close this issue. We have upgraded the provider and fixed it that way.
