### ISSUE TITLE
Terraform GCP timeout while waiting for state to become 'DONE'

### ISSUE THREAD

**Issue by shyamsabhaya** [hashicorp/terraform-provider-google#8358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.6

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
variable "project" {}
variable "name" {}
variable "zone" {}
variable "machine_type" {}
variable "ssh_keys" {}
variable "startup_script" {}
variable "image_project" {}
variable "sentinel_image_name" {}

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "~> 3.52.0"
    }
  }
}

provider "google" {
  # Set to match the longest possible request, delete.
  request_timeout = "5m"
}

resource "google_compute_instance" "vm" {
  name         = var.name
  project      = var.project
  boot_disk {
    initialize_params {
      image = join("/", [var.image_project, var.sentinel_image_name])
    }
  }

  machine_type = var.machine_type
  zone         = var.zone

  network_interface {
    network = "default"
  }

  service_account {
    scopes = ["logging-write", "compute-rw", "storage-rw", "monitoring-write",
              "pubsub", "service-management", "service-control", "https://www.googleapis.com/auth/trace.append"
             ]
  }

  metadata = {
    ssh-keys = var.ssh_keys
    startup-script = var.startup_script
  }

  timeouts {
    create = "100s"
    delete = "5m"
  }
}

output "vm_id" {
  value = google_compute_instance.vm.instance_id
}

output "vm_internal_ip" {
  value = google_compute_instance.vm.network_interface.0.network_ip
}

```

### Debug Output

Added Terraform log

### Panic Output

No crash

### Expected Behavior

We have a 100 second timeout for instance create on GCP in our config file above. We create the VM, and we get this error:
`"Error: Error waiting for instance to create: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 1m40s)"` However, we check our console, and see that the VM booted up in 7 seconds. See attached image for logs.

### Actual Behavior

Terraform returns an error stating that the VM was waiting to finish booting up and exceeded the allocated 100 seconds.

### Steps to Reproduce

1. `terraform apply`

### References

![instance_boot](https://user-images.githubusercontent.com/7365797/106525102-50e62a00-6498-11eb-8e66-f6f0c9de05bb.png)
[terraform_log.log](https://github.com/hashicorp/terraform-provider-google/files/5907107/terraform_log.log)

**Comment by edwardmedia** [comment]
@shyamsabhaya what `image` and `machine_type ` are you using?

**Comment by shyamsabhaya** [comment]
Our image is debian10
Machine Type is n1-standard2

**Comment by edwardmedia** [comment]
@shyamsabhaya it is likely the API experienced some issues during the time you executed the config. Can you try it again to see if you can repro the issue?

**Comment by shyamsabhaya** [comment]
Hi Edward,

If we set the timeout shorter on the HTTP timeout, would it retry or would it fail? How does Terraform retry there? Our timeout for HTTP is set at 5 min, but we give the GCE API 100 seconds to bring up a VM.

```
provider "google" {
  # Set to match the longest possible request, delete.
  request_timeout = "5m"
}
```

**Comment by edwardmedia** [comment]
@shyamsabhaya here is what the Terraform explains about the [request_timeout](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_timeout). My understanding is in your case it is up to the timeouts defined in the resources. I could be wrong. Since this is a Terraform feature, you might file a question to Terraform core. I am closing the issue. Feel free to reopen it if you have further questions
