### ISSUE TITLE
Support `--trigger-topic` for Cloud Functions deployment

### ISSUE THREAD

**Issue by northtree** [hashicorp/terraform-provider-google#8363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, Terraform only supports `--trigger-event` while deploying Cloud Functions. Since such [legacy notification might be removed at a future date](https://cloud.google.com/functions/docs/calling/pubsub#legacy_cloud_pubsub_triggers), we have to support `--trigger-topic` as recommended by official doc.

Meanwhile, there are incompatible error from gcloud CLI with `--trigger-topic` to update GCF which was deployed via Terraform before.

> ERROR: (gcloud.functions.deploy) The format of the Pub/Sub event source has changed.  You are trying to update a function that is using the legacy `providers/cloud.pubsub/eventTypes/topic.publish` event type. To get the legacy behavior, use the `--trigger-event` and `--trigger-resource` flags e.g. `gcloud functions deploy --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource [your_topic_name]`.

### Affected Resource

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "hello_world" {
  name        = "hello_world"
  runtime     = "python38"
  available_memory_mb   = 256
 
  event_trigger {
    event_type = "providers/cloud.pubsub/eventTypes/topic.publish"
    resource = "hello_world_pubsub"
    failure_policy {
      retry = true
    }
  }
  entry_point           = "main"
  ...
}
```

### References

* https://cloud.google.com/functions/docs/calling/pubsub#legacy_cloud_pubsub_triggers

**Comment by melinath** [comment]
Closing as this is for the v1 cloudfunctions API and it's not clear what fields need to change. If this is still needed, please clarify what support for the https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions API is missing in the current implementation. Thanks!
