### ISSUE TITLE
Error when reading or editing Subscription: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token

### ISSUE THREAD

**Issue by Ikeajoel** [hashicorp/terraform-provider-google#8364]
Hi! When we upgraded our terraform infrastructure from 0.12.25 to 0.13.0 this bug above was introduced.

"Error when reading or editing Subscription: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token"

Any idea what can be the problem?

The provider we are using is google.

**Comment by venkykuberan** [comment]
Looks like terraform don't have the credentials setup.  This [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials) helps to add creds.
