### ISSUE TITLE
Shielded VM constraint violated even though correct fields set

### ISSUE THREAD

**Issue by oholdswo** [hashicorp/terraform-provider-google#8373]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.14.5

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "shielded_instance_test" {
  name                      = "shielded-instance-test"
  project                   = var.gcp_project
  machine_type              = "e2-micro"
  zone                      = "europe-west2-c"
  allow_stopping_for_update = true

  boot_disk {
    initialize_params {
      image = var.image
      size  = 20
      type  = "pd-standard"
    }
  }

  network_interface {
    network    = "default"
    subnetwork = "default"
  }

  service_account {
    scopes = [
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring.write",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/trace.append"
    ]
  }

  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = true
    enable_vtpm                 = true
  }
}
```

### Debug Output

https://gist.github.com/oholdswo/0ae8146928c23cb35867d4b6955f6fab

### Expected Behavior

The VM should have been successfully created since all three shielded_instance_config fields are set to true.

### Actual Behavior

Terraform apply fails:

`Error: Error creating instance: googleapi: Error 412: Constraint constraints/compute.requireShieldedVm violated for project. Secure Boot is not enabled in the 'shielded_instance_config' field. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information., conditionNotMet`

### Steps to Reproduce

1. Activate the GCP compute.requireShieldedVm org constraint
2. Create a boot disk image with the shielded_instance_config fields set to true
3. Input var.project and var.image into the above terraform config file
4. `terraform init`
5. `terraform apply`

### Important Factoids

* I am able to create the VM using the GCP console UI directly, using exactly the same configuration.
* Boot disk image is stored in a different GCP project, so using `<PROJECT>/<IMAGE>` format.

**Comment by venkykuberan** [comment]
@oholdswo i am not able to repro the issue on my end. Can you please try with provider version ~3.x.x.

**Comment by oholdswo** [comment]
@venkykuberan thanks for the response. I tried a provider version of ~3.0.0 but unfortunately still see the same error. 
I've created a new gist with the full debug output: https://gist.github.com/oholdswo/db3ee722053ed855c039a3bb44aae765

**Comment by venkykuberan** [comment]
I see your request is still sending `shieldedVmConfig` to API. Can you try with the provider version `3.54.0` and see if its working. 

The feature was originally called shieldedVmConfig in the API and was added to the beta API with that name. The name of the feature got changed and it was added to the GA API as shieldedInstanceConfig per [API doc](https://cloud.google.com/compute/docs/reference/rest/v1/instances), however API beta version supports  both `shieldedVmConfig` and `shieldedInstanceConfig` [beta API doc](https://cloud.google.com/compute/docs/reference/rest/beta/instances)

**Comment by oholdswo** [comment]
Provider version 3.54.0 fixed it, thanks very much @venkykuberan! :tada:
