### ISSUE TITLE
Support for manually invoked builds to google_cloudbuild_trigger

### ISSUE THREAD

**Issue by pairaksi** [hashicorp/terraform-provider-google#8374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

You are able to create manual triggers in GCP console. 
https://cloud.google.com/cloud-build/docs/automating-builds/create-manual-triggers

Same would be nice to have supported with google_cloudbuild_trigger

### New or Affected Resource(s)
google_cloudbuild_trigger

**Comment by slevenick** [comment]
We initially thought this was for triggering manual builds which is something we likely don't want to support. This is actually a request for creating a trigger that can be manually run. This is described in the linked docs page.

I'm unable to figure out exactly how this would be done via the existing API though. This might be done by not setting any explicit triggers in the existing resource

**Comment by bruno-morel** [comment]
It's indeed undocumented (at least publically) => https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers#BuildTrigger

I've opened a support ticket to either release the API documentation linked to this, or make it explicit that it's not available from the APIs from Google....

**Comment by LondonAppDev** [comment]
I opened a bug on the Google issue tracker as per their feature request process: https://issuetracker.google.com/issues/192637573

Might be useful to vote for it with a ⭐:
<img width="439" alt="Screenshot 2021-07-14 at 20 15 22" src="https://user-images.githubusercontent.com/4703936/125679879-71047642-0e23-4151-86c5-9df084bfd7f3.png">

**Comment by ilango100** [comment]
While waiting for the solution, my workaround is to set `ignored_files = ["**/*"]`. This makes sure that the trigger is not run on any change, but can be triggered manually or through API.

Hope this helps

**Comment by lion7** [comment]
You can actually create a webhook trigger without any secret, which results into a manual trigger on GCP:
```terraform
resource "google_cloudbuild_trigger" "my-trigger" {
  name = "my-trigger"

  webhook_config {
    secret = ""
  }

  build {
    step {
      name = "gcr.io/cloud-builders/git"
      args = ["clone", "https://github.com/random/repo"]
    }
  }
}
```

**Comment by jaismith** [comment]
> 

This deploys successfully for me but the trigger in GCP appears not to have the 'webhook' option enabled, maybe because it is missing the `sourceToBuild` argument? Is this still working for you?

**Comment by lion7** [comment]
No, the source I specified in the `build` section doesn't appear at all. I have to manually correct it in the gcp console after applying terraform.

It is also broken when the trigger is a pub/sub topic. In that case the provided source is also not showing up.

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon

**Comment by hspak** [comment]
Hello,

I see that this issue was closed, but I don't see this feature list in the latest release notes: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.13.0

Will this be included in the next release?

Thank you!
