### ISSUE TITLE
cloud_run_service not recognizing sandbox=gvisor annotation set by google

### ISSUE THREAD

**Issue by jambt** [hashicorp/terraform-provider-google#8380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Description
When deploying a google cloud run service, the sandbox is set to `gvisor` by google. This change will be removed on each subsequent apply, but always reverted by google. Thus, there are changes displayed, when there are none.

### Terraform Version
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/google v3.55.0

(+ provider registry.terraform.io/hashicorp/random v3.0.1)
(+ provider registry.terraform.io/terraform-providers/docker v2.7.2)

### Affected Resource(s)

* google_cloudrun_service

### Terraform Configuration Files

```tf
resource google_cloud_run_service this {
  name     = var.name
  project  = var.project_id
  location = local.location

  template {
    metadata {
      labels = var.labels
      annotations = {
        "autoscaling.knative.dev/maxScale" = 20,
        "run.googleapis.com/sandbox"         = "gvisor"  # <-- This line is not a solution #### marked line #####
      }
    }
    spec {
      service_account_name = var.service_account_name
      containers {
        image = "TEST"
        dynamic "env" {
          for_each = merge({
            "GCLOUD_PROJECT" = var.project_id
          }, var.env)
          content {
            name  = env.key
            value = env.value
          }
        }
      }
      container_concurrency = 5
      timeout_seconds       = 120
    }
  }

  metadata {
    labels = merge(
      {
        "cloud.googleapis.com/location" : local.location
      },
      var.labels
    )
  }

  autogenerate_revision_name = true

  traffic {
    latest_revision = true
    percent         = 100
  }
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Terraform apply: cloudrun service should be deployed.
Terraform plan: no change displayed

#### With the marked line:

Terraform apply: 
```
  Error: Error updating Service <service-name>: googleapi: Error 400: The feature 'sandbox selector' is not supported in the declared launch stage on resource reprocessor. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.
```

#### Without the marked line

Terraform apply: cloudrun service is deployed.
Terraform plan: On every change, the following change is presented: 

```
    ~ template {
          ~ metadata {
              ~ annotations = {
                    "autoscaling.knative.dev/maxScale" = "1000"
                  - "run.googleapis.com/sandbox"       = "gvisor" -> null
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids
n/a

### References

**Comment by edwardmedia** [comment]
@jambt  what version of the provider are you using? Please share the full debug log if using the latest version does not help resolve the issue

**Comment by jambt** [comment]
Hi @edwardmedia,

thanks for helping me with this issue. I'm indeed using the latest provider and added the following information to the original post:

I created you a full debug log for the two scenarios above:
**Without the marked line** (change of `gvisor` is planned): https://gist.github.com/jambt/6ba3634b7ae81c51f20527dda53a1968

**With the marked line** (error applying): https://gist.github.com/jambt/b1b56720bf5b5faf9db89d1c99209a2f

If I can help you investigate this further, please let me know.

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/8401

**Comment by edwardmedia** [comment]
@jambt thanks for sharing the debug log. From the error, here is [what](https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation) suggested by the API. BTW, the provider has not much to control inside the `annotations` block. 
```
		metadata {
			annotations = {
				"run.googleapis.com/launch-stage"  = "BETA" 
				"run.googleapis.com/sandbox"       = "gvisor"
			}
		}
```

**Comment by jambt** [comment]
hi @edwardmedia,

thank you for investigating. My issue is not with these annotations being set, but rather that the provider (in its up-to-date version) tries to change the value on every plan. Thus, a plan with many Cloud Run deployments which all get changed for no reason is unusable.

Today, we updated the provider to 3.56 and got even more (unwanted) annotation/label changes without changing the definition of the resource. To reiterate: I expect the provider to indicate _no_ change if the source code stays the same after applying.

**Comment by edwardmedia** [comment]
@jambt to answer your below expecteation. here is what/how the provider handles [annotation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#annotations) blocks.  
Does this make sense?

>To reiterate: I expect the provider to indicate no change if the source code stays the same after applying.

```
annotations - (Optional) Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. More info: http://kubernetes.io/docs/user-guide/annotations Note: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field.
```

**Comment by jambt** [comment]
Hi @edwardmedia ,

thank you for taking the time to help me out here again. The documented behaviour is found in my example, so thisvus not a bug.

Allow me one last question: Is it indeed intended  that the annotations set in this way vary with each provider version? For example, by using 3.56 instead of 3.55 I have two additional annotations for `creator` and latest updater. It aeems unintuitive to have to adopt the annotations on each minor version updare.

Thank you for your help, once again!

**Comment by edwardmedia** [comment]
@jambt Out of curiosity, where did you get v3.56? I only see [v3.55](https://github.com/hashicorp/terraform-provider-google/releases) as the latest release by this moment. 
I don't think that is intentional. I see we have code in `cloud_run_service` that try to handle the diff in the annotation blocks. But as the doc explains, the server side keeps changing, we suggest client side to handle it accordingly. Yes,  this behavior fits `annotation` blocks in most other resources.
You are welcome to ask questions. If you agree that makes sense, please close the issue then.

**Comment by jambt** [comment]
Thank you very much for clearing this up. Then this is merely a hint that sometimes these differences in the annotation block handling can be irritating for users. However, it is clearly documented.

Thank you for your help!
