### ISSUE TITLE
Fix TestAccEndpointsService_basic

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8383]
It looks like this was previously covered in https://github.com/hashicorp/terraform-provider-google/issues/5039; unclear if that's related.

https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/170671?buildTab=tests&expandedTest=4647748206155634981

**Comment by edwardmedia** [comment]
Can't repro it locally

**Comment by edwardmedia** [comment]
Error on random_id which is not used in the test. 

```
When expanding the plan for random_id.foo to include new values learned so far
        during apply, provider "registry.terraform.io/-/random" produced an invalid
        new value for .keepers["config_id"]: was cty.StringVal("2021-02-24r0"), but
        now cty.StringVal("2021-02-25r1").
```
