### ISSUE TITLE
Fix TestAccContainerCluster_withAuthenticatorGroupsConfig

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8384]
https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/170671?buildTab=tests&expandedTest=1946850189227800554

**Comment by venkykuberan** [comment]
This requires `gke_security_groups` to be created as part of boostrap process as API is validating it now
