### ISSUE TITLE
Fix TestAccContainerNodePool_withManagement

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8388]
This may be a backwards-incompatible API change?

https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/170671?buildTab=tests&logFilter=debug&expandedTest=4113757717354893212

**Comment by rileykarson** [comment]
See https://github.com/hashicorp/terraform-provider-google/issues/8390
