### ISSUE TITLE
Notebook instance gets re-created with terraform using google_notebooks_instance

### ISSUE THREAD

**Issue by dubeyanir** [hashicorp/terraform-provider-google#8395]
### Affected Resource(s)

* google_notebooks_instance

code taken as it is from 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#example-usage---notebook-instance-basic-container
```tf

-- it can be reproduced by creating notebook using the google_notebooks_instance resource.


-- we are able to create the notebook from the resource.
-- however instance gets re- created when build is run again even without any changes to the code.

**Comment by venkykuberan** [comment]
```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/google v3.54.0
+ provider registry.terraform.io/hashicorp/google-beta v3.54.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

I don't see Terraform attempts to recreate the resource when there is no change detected in the state/config. If you run `tf apply` on top of it, you get output like below.
```
terraform apply -auto-approve
google_notebooks_instance.instance: Refreshing state... [id=projects/test-project1-xxxx/locations/us-west1-a/instances/notebooks-instance]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed
```

We don't know how your build process is setup. Make sure you aren't deleting the resource at the end of build process and your terraform state is stored in some backend.

**Comment by rileykarson** [comment]
Closing as stale.
