### ISSUE TITLE
Redis Instance auth_string field doesn't function as expected

### ISSUE THREAD

**Issue by xiaobaitusi** [hashicorp/terraform-provider-google#8400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_redis_instance

### Terraform Configuration Files

```tf
resource "google_redis_instance" "cache" {
  provider       = google-beta
  name           = "tf-test"
  memory_size_gb = 1
  region         = "us-central1"
  auth_enabled   = true
  auth_string    = "some_auth_string"
}
```

### Expected Behavior
It's expected to set the authString in the underlying resource with the specified value. 

### Actual Behavior
However, the subsequent `terraform show` shows  a different (random server-generated) auth string.
```
resource "google_redis_instance" "cache" {
    auth_enabled             = true
    auth_string              = "REDACTED"
   # more configuration...
}
```
If running `terraform apply` again, it returns the following error.
```
Error: Error updating Instance "projects/{{my-project}}/locations/us-central1/instances/{{name}}": googleapi: Error 400: Update mask is empty
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Update mask is empty
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value: ",
        "field": "update_mask"
      }
    ]
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
also suppress diff needed?
```
  # google_redis_instance.cache will be updated in-place
  ~ resource "google_redis_instance" "cache" {
        auth_enabled             = true
      ~ auth_string              = "939f0590-73b4-449d-ab2e-8338b31e9d7a" -> "some_auth_string"
```

**Comment by alexanderjlee** [comment]
The string looks to be correct when being ingested using `google_kms_secret`, however my main concern is that it shows the `auth_string` in plain text and decrypted, rather than as a `(sensitive value)` during `terraform plan`.

``` 
      + resource "google_redis_instance" "redis" {
      + alternative_location_id  = (known after apply)
      + auth_enabled             = true
      + auth_string              = "the_actual_auth_password_decrypted"
```

**Comment by alexanderjlee** [comment]
Disregard my last post, after reading [this](https://cloud.google.com/memorystore/docs/redis/auth-overview?_ga=2.212658452.-1802906750.1591738086&_gac=1.157927112.1610047917.CjwKCAiA_9r_BRBZEiwAHZ_v1xshqVz75hJaEmNKRtpT_8-7DCEcX1DPgyTzC4zrysfoFcrZVE7DkRoCh1QQAvD_BwE ) it seems like the `auth_string` is supposed to be randomly generated upon being enabled.  So now I'm not sure what `auth_string` is supposed to do in the context of terraform or if it needs to be defined in the resource module if Memorystore is going to generate the UUID automatically.

**Comment by rileykarson** [comment]
Whoops, yep, I believe this was mistakenly marked as a user-configurable field. I was a reviewer and definitely keyed in on `Computed` being set and didn't notice `Optional` also was. We should be able to remove `Optional: true` even without considering it a breaking change, since specifying it would never have worked.
