### ISSUE TITLE
Cloud Run minimum instances not supported even with BETA annotation

### ISSUE THREAD

**Issue by aminubakori** [hashicorp/terraform-provider-google#8401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.55.0

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "cloudrun_server" {  
	name     = "${var.service_name}-server"
	location = var.region

	template {
		spec {
			containers {
				image = "gcr.io/cloudrun/placeholder"

				env {
					name = "PROJECT_CONFIG"
					value = "sm://${var.project_id}/${google_secret_manager_secret.config_secret.secret_id}?destination=app/.env"
				}

				ports {
					container_port = 3005
				}

				resources {
					limits = {
					"memory" = "2G"
					"cpu" = "2"
					}
				}
			}

			service_account_name = google_service_account.service_account.email
		}

		metadata {
			annotations = {
				"run.googleapis.com/launch-stage"  = "BETA" 
				"run.googleapis.com/sandbox"       = "gvisor"
				"autoscaling.knative.dev/minScale" = "1"
				"autoscaling.knative.dev/maxScale" = "10"
			}
		}
  	}

	traffic {
		percent         = 100
		latest_revision = true
	}

	depends_on = [ 
		google_project_service.enable_cloudrun_api, 
		google_service_account.service_account
	]
}
```

### Panic Output
Error: Error creating Service: googleapi: Error 400: The feature 'minimum instances' is not supported in the declared launch stage on resource sandbox-server. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.

### Expected Behavior
Create a Cloud Run instance with a minimum number of running instances as stated above.

### Actual Behavior
Returns the error above.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@aminubakori can you share the debug log for the execution when you call `terraform apply`?

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/8401

**Comment by aminubakori** [comment]
Hi @edwardmedia 

Thanks for helping out.

Please find the logs here [https://gist.github.com/aminubakori/77d7907493b6706ed2d1b0d416d9a282](Logs Gist Link)

Thank you.

**Comment by aminubakori** [comment]
@edwardmedia Have you been able to look at the logs?

**Comment by aminubakori** [comment]
Found a way to fix this. The BETA metadata annotations needs to be a variable directly under the resource root.

# Example
```tf
resource "google_cloud_run_service" "cloudrun_server" {  
	name     = "example-server"
	location = "europe-west1"

	metadata {
		annotations = {
			"run.googleapis.com/launch-stage"  = "BETA"
		}
	}

	template {
		spec {
			containers {
				image = "gcr.io/cloudrun/placeholder"
			}
		}

		metadata {
			annotations = {
				"run.googleapis.com/launch-stage"  = "BETA" 
				"autoscaling.knative.dev/minScale" = "1"
				"autoscaling.knative.dev/maxScale" = "10"
			}
		}
  	}

	traffic {
		percent         = 100
		latest_revision = true
	}
}
```
