### ISSUE TITLE
Newly added 'reservation_affinity' in 'google_compute_instance' is not supported.

### ISSUE THREAD

**Issue by sthamma** [hashicorp/terraform-provider-google#8402]
Hi,

I see that support for 'reservation_affinity' is added few days ago (https://github.com/hashicorp/terraform-provider-google/pull/7669).  

I am using GCP shell and on version 0.14.6 which is latest. I still get an issue which is attached. Can someone please clarify ?

I am not sure if I have to place that in any block, couldn't find any doc that supports. Attached two screenshots.

Thanks
Sri.
![terraform_block](https://user-images.githubusercontent.com/64287573/107156361-7618e380-6943-11eb-9233-7d43ec0f6206.png)

![unsupported_in_terraform](https://user-images.githubusercontent.com/64287573/107156315-49fd6280-6943-11eb-9f93-2719469c64b3.png)

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by edwardmedia** [comment]
@sthamma looks like this enhancement has not made through yet. Here is its PR:

https://github.com/GoogleCloudPlatform/magic-modules/pull/4335

**Comment by sthamma** [comment]
ok, thank you for your time on this. When would this be available(possibility) ?

**Comment by edwardmedia** [comment]
@sthamma it's in the code review. Until that is done, it will be in a release. I don't have a number how long it will take. Closing this then
