### ISSUE TITLE
Blocks of type "gce_persistent_disk_csi_driver_config" are not expected here

### ISSUE THREAD

**Issue by sthamma** [hashicorp/terraform-provider-google#8403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.55.0
+ provider registry.terraform.io/hashicorp/google-beta v3.55.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name                      = var.cluster_name
  location                  = var.zone
  network                   = var.network
  subnetwork                = var.subnetwork
  default_max_pods_per_node = 110
    addons_config {
    http_load_balancing {
      disabled = false
    }
    horizontal_pod_autoscaling {
      disabled = true
    }
    gce_persistent_disk_csi_driver_config = {
        enabled = true
        provider = "google-beta"
    }
  }
```

### Expected Behavior

Should execute plan succesfully. Right now, plan failed.

### Actual Behavior

Error: Unsupported argument

  on terraform.tf line 20, in resource "google_container_cluster" "primary":
  20:     gce_persistent_disk_csi_driver_config = {

An argument named "gce_persistent_disk_csi_driver_config" is not expected
here.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@sthamma `[gce_persistent_disk_csi_driver_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#gce_persistent_disk_csi_driver_config)` is in *beta*. Can you try `provider-beta` to see if it works?

**Comment by sthamma** [comment]
@edwardmedia . I have tried that if you see gce_persistent_disk_csi_driver_config block, I have that provider-beta given. I declared provider block without any version(so I will get latest version).

**Comment by edwardmedia** [comment]
@sthamma can you try by adding the provider at the root?

```tf
resource "google_container_cluster" "primary" {
  name                      = var.cluster_name
  location                  = var.zone
  network                   = var.network
  subnetwork                = var.subnetwork
....
  provider = "google-beta"
```

**Comment by sthamma** [comment]
Thank you, I have placed 'provider' at resource level and it worked. Closing the issue....
