### ISSUE TITLE
why no data option for google_compute_health_check?

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-google#8404]
while creating google_compute_backend_service resource healthcheck is required, but there is no data option for google_compute_health_check to read existing healthcheck to use with backend_service.

**Comment by edwardmedia** [comment]
@Sreerag74031 there are several [examples](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service) that show how these resources are used. If that does not explain your question, can you be more specific what you mean about the `data option`? What you want to provide? Where do you see it available in other apps, like *gcloud*, gcp *api*, etc.?

**Comment by Sreerag74031** [comment]
I meant for backend service we have resource https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service
as well as the data source https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_backend_service

where as for google_compute_health_check i only see resource no data source

**Comment by edwardmedia** [comment]
@Sreerag74031 oh I see. It has not been built yet. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=&template=enhancement.md) for it so it can be prioritized.

**Comment by edwardmedia** [comment]
Closing this then
