### ISSUE TITLE
BigQuery materialized views are being shown as changed even though nothing has changed since the last apply

### ISSUE THREAD

**Issue by fiona-streetgroup** [hashicorp/terraform-provider-google#8411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.55.0

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

When running `terraform apply`, no changes should be detected if there have been no changed made to the view since the last apply.

### Actual Behavior

Each time `terraform apply` is run, the materialised views appears as being changed even though there have been no updates. This makes it very difficult to review actual changes made to other resources.

### Steps to Reproduce

1. Create google_bigquery_table with a materialized_view block, and include a query inside.
2. `terraform apply` - view will be created
3. Run `terraform apply` again, the same view will appear as a change (even though nothing has changed)

This does not happen with standard views.

### References

* #0000

**Comment by fiona-streetgroup** [comment]
Example tf for the materialised view
[materialized_view_example.txt](https://github.com/hashicorp/terraform-provider-google/files/5945890/materialized_view_example.txt)

**Comment by venkykuberan** [comment]
@fiona-streetgroup can you please share your plan output to understand the diffs?

**Comment by edwardmedia** [comment]
No response. Assuming it is no longer an issue
