### ISSUE TITLE
google_cloud_run_service: make `location` optional

### ISSUE THREAD

**Issue by yegle** [hashicorp/terraform-provider-google#8413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now `location` field is required in `google_cloud_run_service`, but it can also be specified via `metadata.labels["cloud.googleapis.com/location"]`.

In fact to avoid a permanent diff one have to add `metadata.labels["cloud.googleapis.com/location"]` to `lifecycle.ignored_changes`.

It would be great if `location` can be made an optional field, so we can put the location information in `metadata.labels["cloud.googleapis.com/location"]`.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
We don't want to support specifying the location through this label, but we can ignore the label in Terraform since it's never supposed to be user-settable.

**Comment by yegle** [comment]
I didn't realize the label is output only. In that case, remove that field from diffing is a better solution.
