### ISSUE TITLE
google_service_networking_connection should fail if a servicenetworking-googleapis-com already exists

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#8414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.52.0
+ provider registry.terraform.io/hashicorp/google-beta v3.52.0
```

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
# Create a google_service_networking_connection in mysubnetwork
resource "google_compute_global_address" "private-ip" {
  provider      = google-beta
  name          = "private-ip"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  address       = "10.1.1.0"
  project       = myproject_id
  network       = google_compute_subnetwork.mysubnetwork.network
}

resource "google_service_networking_connection" "private-ip-peer" {
  provider                = google-beta
  network       = google_compute_subnetwork.mysubnetwork.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private-ip.name]
}

# Create a SECOND google_service_networking_connection in the same subnetwork
resource "google_compute_global_address" "private-ip-2" {
  provider      = google-beta
  name          = "private-ip-2"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  address       = "10.1.2.0"
  project       = myproject_id
 network       = google_compute_subnetwork.mysubnetwork.network
}

resource "google_service_networking_connection" "private-ip-peer-2" {
  provider                = google-beta
  network                = google_compute_subnetwork.mysubnetwork.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private-ip-2.name]
}
```

### Expected Behavior
One of the google_service_networking_connection resources should immediately fail when it sees a servicenetworking-googleapis-com peer already exists for the subnetwork.

### Actual Behavior

google_service_networking_connection merely asserts its config. Both google_service_networking_connection resources will fight over the config and, more dangerously, if a servicenetworking-googleapis-com peer already exists it will be clobbered by the resource's configuration instead of terraform throwing an error and forcing me to import the existing resource.

**Comment by edwardmedia** [comment]
@red8888 can you share the debug log?

**Comment by edwardmedia** [comment]
@red8888 is this still an issue?

**Comment by edwardmedia** [comment]
@red8888 closing this now. Feel free to reopen it if this is still an issue
