### ISSUE TITLE
terraform-provider-google-beta should use secretmanager v1 endpoints

### ISSUE THREAD

**Issue by tam7t** [hashicorp/terraform-provider-google#8415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`secretmanager.googleapis.com` has `v1beta1` and `v1` APIs. After Secret Manager went GA in March 2020, new features are only being added to the `v1` version of the API (see [expiration](https://cloud.google.com/secret-manager/docs/creating-and-managing-expiring-secrets#limitations)).

To allow the `terraform-provider-google-beta` provider to include the latest Preview features, it should be updated to point to `/v1/` instead of `/v1beta1`.

### New or Affected Resource(s)

* google_secrets_secret
* google_secrets_version
* google_secrets_secret_iam_member
* google_secrets_secret_iam_binding
* google_secrets_version_access

**Comment by rileykarson** [comment]
Was this closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/4479, or is there more to do?

**Comment by tam7t** [comment]
Ah yes I believe that this is complete now that the change is in the `terraform-provider-google-beta` repo
