### ISSUE TITLE
cloud_function errors out during waiting if there is a connection timeout (during UPDATE)

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform-provider-google#8430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.5
google provider: 3.54.0

### Affected Resource(s)

google_cloud_function

### Description

According to source code, if CFN is getting create there are retry operations:
https://github.com/hashicorp/terraform-provider-google/blob/49df8cb3f3ddc896110ce252fbd58e96fd63d056/google/resource_cloudfunctions_function.go#L443

However when updating, there aren't any retries:
https://github.com/hashicorp/terraform-provider-google/blob/49df8cb3f3ddc896110ce252fbd58e96fd63d056/google/resource_cloudfunctions_function.go#L680

### Expected Behavior

I'd like update behave same way as create. I'd like my process (whether it's create OR update) not to fail if I have a DNS resolution problem for a second (or a single timeout)

### Actual Behavior

When there is some error / problem during update operation it will fail. I for example had a short network blip and ended up with:

```
Error: Error waiting for Updating CloudFunctions Function: error while retrieving operation: Get "https://cloudfunctions.googleapis.com/v1/operations/XXXXXXXXXByb2QtNTM2YmE5MGIvZXVyb3BlLXdlc3QxL2Nsb3VkX3ZtX2NvbnRyb2wvbnBlSUR5SU9EZVE?alt=json&prettyPrint=false": dial tcp 172.217.168.10:443: connect: connection refused
```

### Steps to Reproduce

update CFN and switch network OFF/ON while waiting for update to finish

**Comment by venkykuberan** [comment]
We will include the retry in the update as well. Thanks for filing the issue
