### ISSUE TITLE
google_compute_security_policy expr rules getting recreated

### ISSUE THREAD

**Issue by Sreerag74031** [hashicorp/terraform-provider-google#8437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.6

### Affected Resource(s)

* google_compute_security_policy

### Terraform Configuration Files

```tf
-     - rule {
-         - action      = "allow" -> null
-         - description = "description" -> null
-         - preview     = false -> null
-         - priority    = 100 -> null

-         - match {

-             - expr {
-                 - expression = "request.path.matches('/some/path/')" -> null
               }
            }
        }
+     + rule {
+         + action      = "allow"
+         + description = "description"
+         + preview     = false
+         + priority    = 100
+         + match {

+             + expr {
+                 + expression = "request.path.matches('/some/path/')"
                }
            }
        }
```

### Steps to Reproduce

If security policy resource has expr rule any change in the resource the expr rules are getting re-created.

### References

* #8251

**Comment by venkykuberan** [comment]
@Sreerag74031 this seems duplicate as we are working on a fix here #8251. It will soon be released.
I will close this one, as we are tracking the other one
