### ISSUE TITLE
Support for Cloud SQL Query Insights

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#8449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud SQL for PostgreSQL recently added a feature known as [Query Insights](https://cloud.google.com/sql/docs/postgres/insights-overview). The [API docs](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#Settings) for Cloud SQL instances don't yet document how to configure this feature via the API, but the API presumably exposes a `settings.insightsConfig` field based on the sample request body [on this page](https://cloud.google.com/sql/docs/postgres/using-insights#rest-v1).

### New or Affected Resource(s)

* `google_sql_database_instance`

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "my-instance" {
  name             = "my-instance"
  database_version = "POSTGRES_11"
  region           = "us-central1"

  settings {
    tier = "db-f1-micro"

    insights_config {
      query_insights_enabled = true
      query_string_length = 1024
      record_application_tags = true
      record_client_address = true
    }
  }
}
```

Note that the schema suggested by the above configuration is not a requirement but only a suggestion based on [disparate](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/386) [information](https://cloud.google.com/sql/docs/postgres/using-insights#gcloud) on how the API exposes the feature.

### References

* https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/399

**Comment by j-martin** [comment]
This is an issue for us as changing the instance(s) configuration via terraform disableds Query Insights and forces a restart.

**Comment by Chupaka** [comment]
When I added
```
  settings {
    insights_config {
      query_insights_enabled = true
    }
  }
```
to my TF config of `google_sql_database_instance`, it doesn't want to roll manually enabled Query Insights back anymore. So looks like it's already supported but not documented?..

**Comment by Chupaka** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4464

**Comment by rileykarson** [comment]
Thanks @Chupaka!
