### ISSUE TITLE
google_compute_resource_policy erroneously plans to destroy resources

### ISSUE THREAD

**Issue by assafrahav** [hashicorp/terraform-provider-google#8459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

internal build 2021.02.03-5 (mainline @355283235)

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
resource "google_compute_resource_policy" "pd_snapshots" {
  name    = "${var.component}-snapshots"
  project = var.project_id
  region  = var.region
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = var.snapshot_interval
        start_time     = format("%02d:00", local.snapshot_start)
      }
    }
    retention_policy {
      max_retention_days    = var.snapshot_retention
      on_source_disk_delete = "APPLY_RETENTION_POLICY"
    }
    snapshot_properties {
      guest_flush = var.guest_flush
    }
  }
}
```

### Expected Behavior

Successful application of the resource, and no diff in subsequent terraform runs

### Actual Behavior

On subsequent runs terraform plans to destroy and recreate the resource. The reason appears to be that if `var.guest_flush` is false, then the `snapshot_properties` isn't actually applied to the resource - presumably since this is the default behavior in GCP.

However on subsequent runs the provider doesn't explicitly see this property on the resource, and plans to add the `snapshot_properties` block which necessitates destroy&recreate.

### Steps to Reproduce

1. Create a `google_compute_resource_policy` resource containing 

```
    snapshot_properties {
      guest_flush = false
    }
```

1. Apply 1st time - success
1. Apply 2nd time - terraform plans to destroy and recreate the resource

Obviously directly creating such a resource is pointless since the block could simply be omitted from the configuration, however as part of a module where I want to allow the user to specify the value of this property via variable it is necessary even when the value is false.

### References

* #0000

**Comment by venkykuberan** [comment]
@assafrahav i don't see that happening on my end, i used the sample config from the doc. Can you please share your plan output here

```
resource "google_compute_resource_policy" "bar" {
  name   = "policy"
  region = "us-central1"
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = 20
        start_time     = "23:00"
      }
    }
    retention_policy {
      max_retention_days    = 10
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }
    snapshot_properties {
      labels = {
        my_label = "value"
      }
      storage_locations = ["us"]
      guest_flush       = false
    }
  }
}
```

**Comment by assafrahav** [comment]
Terrafom plan is stable with the snippet you provided, but if I remove the label and storage_location from the snapshot_properties block, the original behavior is manifested.

So it looks like it only happens if guest_flush is the only property and it is set to false.

**Comment by venkykuberan** [comment]
I see the problem, when only `guest_flush` field is used in the block provider is treating it as empty block since it's considering its value (`false`) as default value for golang bool. We will fix the code. Thanks for filing the issue
