### ISSUE TITLE
google_compute_resource_policy inconsistent handling of start_time

### ISSUE THREAD

**Issue by assafrahav** [hashicorp/terraform-provider-google#8460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

internal build 2021.02.03-5 (mainline @355283235)

### Affected Resource(s)

* google_compute_resource_policy 

### Terraform Configuration Files

```tf
resource "google_compute_resource_policy" "pd_snapshots" {
  name    = "${var.component}-snapshots"
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = var.snapshot_interval
        start_time     = "${local.snapshot_start}:00"
      }
    }
  }
}
```

### Expected Behavior

Terraform applies the resource and remains stable on subsequent applications.
Alternatively, it can reject start time which isn't properly padded.
The important point is that the behavior should be consistent.

### Actual Behavior

If `local.snapshot_start` is les than 10, then the resulting time string is `h:00`

The resource applies this without incident, however on subsequent diffing it interprets `h:00` as being different than `0h:00` and plans to destroy&recreate the resource

### Steps to Reproduce

1. create a `google_compute_resource_policy` resource with a start time < 10:00 and no leading 0
2. apply the config
3. apply terraform a second time - it will plan to destroy the resouce

### References

* #0000

b/308756082

**Comment by venkykuberan** [comment]
`HH:MM` is the expected format, please refer the doc https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy#start_time

start_time - (Required) Time within the window to start the operations. It must be in format "HH:MM", where HH : [00-23] and MM : [00-00] GMT.

**Comment by assafrahav** [comment]
The issue is the provider isn't enforcing that requirement, it allows specifying the input in `h:00` format.
Either the provider should CONSITENTLY treat `h:00` as being the same as `hh:00` or it should reject the input.

Accepting the input, but then getting into a destroy&create loop is not really acceptable behavior.

**Comment by assafrahav** [comment]
@venkykuberan I want to be sure you saw the last comment. I don't think it's correct to close this issue based on the current behavior of the resource.

I agree that h:00 is not in the prescribed format, but the resource needs to enforce this and thrown an error rather than enter this loop of creating & destroying.

**Comment by rileykarson** [comment]
I had this issue flagged to reopen- reopened/unlocked/unassigned so it goes back to triage. We can consider suppressing the diff or disallowing inputs that'll be changed here.
