### ISSUE TITLE
Add support for Firebase Auth Cloud Functions trigger event

### ISSUE THREAD

**Issue by marvinsxtr** [hashicorp/terraform-provider-google#8464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Firebase Auth Cloud Functions trigger event is missing, I tried both `providers/firebase.auth/eventTypes/user.create` as well as `google.firebase.auth.user.create`. They would be really helpful as I will have to deploy functions which use this trigger manually now.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "create_user" {
  project     = var.project_name
  region      = var.region
  name        = "createUser"
  runtime     = "nodejs10"

  source_archive_bucket = google_storage_bucket.cloud_functions_source_bucket.name
  source_archive_object = google_storage_bucket_object.functions_source.name

  available_memory_mb   = 256
  entry_point           = "createUser"

  event_trigger {
    event_type = "providers/firebase.auth/eventTypes/user.create"
    resource = var.project_name
  }
}
```

### References

* https://cloud.google.com/functions/docs/calling/firebase-auth

**Comment by taeold** [comment]
@marvinsxtr I gave setting up a Cloud Function with a Firebase Auth trigger a try today, and I was able to successfully deploy one:

```functions.tf
// functions.tf
resource "google_cloudfunctions_function" "function" {
  name    = local.function_name
  runtime = "nodejs14"
  region  = var.region

  entry_point = "helloWorld"
  available_memory_mb   = 128
  source_archive_bucket = google_storage_bucket.source.name
  source_archive_object = google_storage_bucket_object.archive.name

  event_trigger {
    event_type = "providers/firebase.auth/eventTypes/user.create"
    resource   = "projects/${var.project}"
  }
}
```

```bash
$ tf --version                                                                       
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.71.0

$ tf apply
google_cloudfunctions_function.function: Creating...
google_cloudfunctions_function.function: Still creating... [10s e
google_cloudfunctions_function.function: Still creating... [20s e
google_cloudfunctions_function.function: Still creating... [30s e
google_cloudfunctions_function.function: Still creating... [40s e
google_cloudfunctions_function.function: Still creating... [50s e
google_cloudfunctions_function.function: Still creating... [1m0s 
google_cloudfunctions_function.function: Still creating... [1m10s
google_cloudfunctions_function.function: Creation complete after 

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

I'm not sure what changed (I don't see any interesting changes on Cloud Functions provider), but Firebase Auth trigger support does seem to exist already.

**Comment by marvinsxtr** [comment]
@taeold I upgraded Terraform to the version you are using (3.71.0) and tried it again. Unfortunately I still get the following:

```
Error: googleapi: Error 400: The request has errors, badRequest

   with google_cloudfunctions_function.create_user,
   on functions.tf line 269, in resource "google_cloudfunctions_function" "create_user":
  269: resource "google_cloudfunctions_function" "create_user" {
```

**Comment by taeold** [comment]
@marvinsxtr That's confusing. When I looked into this issue, I found that `event_type` is just a string and there isn't really anything that needs to be done on `google-provider` codebase in order to bring Auth Trigger support.

Do you want to double check https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction? Maybe there is something else going wrong in your function definition that's causing 400 Bad Request. For example, `event_trigger.resource` should be prepended with `projects/{MY-PROJECT-ID}` in contrast to the example code you provided.

**Comment by marvinsxtr** [comment]
@taeold Adding the `projects/` prefix resolved the issue. I missed it because in the [Google documentation](https://cloud.google.com/functions/docs/calling/firebase-auth#deploying_your_function), the `--trigger-resource` is only the project id. Maybe a hint in the [terraform provider documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function#event_trigger) would be helpful to prevent this.
