### ISSUE TITLE
Add security_level field to google_cloudfunctions_function

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#8465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
security_level = "secure-always"
```

### References

* https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#SecurityLevel
* https://cloud.google.com/functions/docs/writing/http#security_levels

**Comment by millouzgc** [comment]
Hello @gomezjdaniel, were you able to find a compromise on the code? You seem to be very close to the solution to implement.

**Comment by melinath** [comment]
resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6007

**Comment by melinath** [comment]
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11086
