### ISSUE TITLE
google_bigquery_data_transfer_config - cannot schedule a SQL script (doing manually to workaround)

### ISSUE THREAD

**Issue by kurtmaile** [hashicorp/terraform-provider-google#8469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.1 - seems its with all though looking at the latest docs.

### Affected Resource(s)

* google_bigquery_data_transfer_config

### Terraform Configuration Files

Below is an example TF config we would like to schedule a SQL script every 2 hours - the script itself will sequentially create 2 tables. (NOTE: the importance of FOR SYSTEM_TIME AS OF GeneratedTimestamp for consistent snapshot timings).  There are numerous reasons for wanting have a set of pipeline steps executed as 1 unit of work.

The table creation responsibility (target dataset, tablename, partitioning etc) lay with the **script** being scheduled, not TF params.  TF is currently enforcing these as required which in this use case are not relevant.

Is there another way of doing this that I am missing?  Sorry if so!

```tf
resource "google_bigquery_data_transfer_config" "scheduled_script"  {

  display_name = "scheduled_script"
  location = "EU"
  data_source_id = "scheduled_query"
  schedule = "every 2 hours"
  params = {
    query = "script_query"
  }
}
```

WHERE script_query is below for readability have spaced it all out. 

```
BEGIN
DECLARE GeneratedTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

CREATE OR REPLACE TABLE `target_project.target_dataset.target_table_1`
CLUSTER BY TransactionNumber
AS
  SELECT
    *,
    GeneratedTimestamp
  FROM 
    `target_project.target_dataset.build_target_table_1` e
     FOR SYSTEM_TIME AS OF GeneratedTimestamp
  ;

CREATE OR REPLACE TABLE `target_project.target_dataset.target_table_2`
CLUSTER BY TransactionNumber
AS
  SELECT
    *,
   GeneratedTimestamp
  FROM 
    `target_project.target_dataset.build_target_table_2` e
     FOR SYSTEM_TIME AS OF GeneratedTimestamp
  ;

END
```

### Expected Behavior

A scheduled query is created for a multi step script, where the script steps control the target behaviour and destination_dataset_id and destination_table_name_template etc are NOT mandatory.

### Actual Behavior

ERRORs as required params

### Steps to Reproduce

Try to provision a query script without destination_dataset_id, destination_table_name_template etc - 

1. `terraform apply`

### Important Factoids

We do this manually via the console fine now as TF it appears enforced the target table and dataset constraints.

**Comment by edwardmedia** [comment]
@kurtmaile from your `script_query` it appears you are trying to create / alter `table`. Is that something you are trying to do? I am not sure if `google_bigquery_data_transfer_config` supports that. [Below](https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest) is the official explanation on what it can achieve. Can you post a link to the doc that says your task can be done?

> Schedule queries or transfer external data from SaaS applications to Google BigQuery on a regular basis.

**Comment by edwardmedia** [comment]
@kurtmaile is this still an issue?

**Comment by edwardmedia** [comment]
@kurtmaile Closing this issue now. Feel free to reopen it if you want to continue the conversation
