### ISSUE TITLE
google_monitoring_alert_policy: support "Notify on incident resolution"

### ISSUE THREAD

**Issue by yegle** [hashicorp/terraform-provider-google#8470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There's a new option on the web UI when editing/adding an alert policy "Notify on incident resolution" that you can uncheck, and the "RESOLVED" notification will not be triggered.

### New or Affected Resource(s)

* google_monitoring_alert_policy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/275109911

**Comment by yegle** [comment]
I tried to modify the policy and then use `gcloud alpha monitoring policies list` to show the policy, and did not see any changed fields from the output. Looks like the API does not support this option yet.

**Comment by afafara** [comment]
This is now the default behaviour for new alerts: https://cloud.google.com/monitoring/docs/release-notes#April_09_2021

**Comment by ahmed1smael** [comment]
For API the default is on, so it's nice to have the option to turn it off.

**Comment by Elephantei** [comment]
It would be helpful to have this option, seeing that some of the alerts do not need notification upon resolution - without this option, all of them have this by default and it makes it a very "dense" space to go through alerts.

**Comment by rrmestl-cx** [comment]
Hello... is there an update to this feature request ?!?!?!

**Comment by gparton** [comment]
PSA to those requesting this feature: Terraform can't support something that can't be achieved with the API and the API doesn't currently support this. [This upstream issue](https://issuetracker.google.com/issues/218288184) to expose it in the Monitoring API needs to be addressed before the Terraform team can work on it.

**Comment by k4leung4** [comment]
The REST API documentation shows support for `notificationPrompts` now.
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#alertstrategy

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#NotificationPrompt

**Comment by toVersus** [comment]
I opened a PR to add support for this feature. I've detailed the behavior in the PR, and it worked without any issues locally.
