### ISSUE TITLE
Not able to import source repo that mirrors GitHub

### ISSUE THREAD

**Issue by jschaf** [hashicorp/terraform-provider-google#8471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.51.0
+ provider registry.terraform.io/hashicorp/google-beta v3.56.0

### Affected Resource(s)

* google_sourcerepo_repository

### Terraform Configuration Files

```tf
resource google_sourcerepo_repository simc-p-src-github {
  name = "github_simple-circle_simc"
}
```

### Debug Output

https://gist.github.com/jschaf/3bb0783de028c17472b532c5134d6f0b

### Panic Output
N/A

### Expected Behavior

Terraform should succeed at importing state of the source repo.

### Actual Behavior

```
google_sourcerepo_repository.simc-p-src-github: Importing from ID "simc-prod"...
google_sourcerepo_repository.simc-p-src-github: Import prepared!
  Prepared google_sourcerepo_repository for import
google_sourcerepo_repository.simc-p-src-github: Refreshing state... [id=projects/simc-prod/repos/simc-prod]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
google_sourcerepo_repository.simc-p-src-github, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.
```

### Steps to Reproduce

1. ` terraform import google_sourcerepo_repository.simc-p-src-github simc-prod`

### Important Factoids

- Source repo was created in GCP console (since I don't think you can create a mirrored repo in terraform) following https://cloud.google.com/source-repositories/docs/mirroring-a-github-repository

- The source repo definitely exists:

  ```sh
  $ gcloud source repos list
  
  REPO_NAME                  PROJECT_ID  URL
  github_simple-circle_simc  simc-prod   https://github.com/simple-circle/simc
  ```

**Comment by edwardmedia** [comment]
@jschaf can you try below command?

```
terraform import google_sourcerepo_repository.simc-p-src-github github_simple-circle_simc
```

```tf
resource google_sourcerepo_repository simc-p-src-github {
}
```

**Comment by jschaf** [comment]
Oh, that works! After an import `plan` and `apply` work as expected.

**Comment by edwardmedia** [comment]
@jschaf I am glad it works for you. Closing the issue then
