### ISSUE TITLE
google_compute_target_ssl_proxy should support multiple ssl_certificates

### ISSUE THREAD

**Issue by quentinms** [hashicorp/terraform-provider-google#8473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: v0.12.18
Google: 3.56.0

### Affected Resource(s)

* google_compute_target_ssl_proxy

### Terraform Configuration Files

```tf
resource "google_compute_target_ssl_proxy" "default" {
  name             = "test-proxy"
  backend_service  = google_compute_backend_service.default.id
  ssl_certificates = [google_compute_managed_ssl_certificate.cert1.id, google_compute_managed_ssl_certificate.cert2.id]
}

resource "google_compute_managed_ssl_certificate" "cert1" {
  name    = "cert1"
  managed {
    domains = ["cert1.example.cm"]
  }
}

resource "google_compute_managed_ssl_certificate" "cert2" {
  name    = "cert2"
  managed {
    domains = ["cert2.example.cm"]
  }
}

resource "google_compute_backend_service" "default" {
  name          = "backend-service"
  protocol      = "SSL"
  health_checks = [google_compute_health_check.default.id]
}

resource "google_compute_health_check" "default" {
  name               = "health-check"
  check_interval_sec = 1
  timeout_sec        = 1
  tcp_health_check {
    port = "443"
  }
}
```

### Debug Output

> ssl_certificates = var.ssl_certificates
> Attribute supports 1 item maximum, config has 2 declare

### Expected Behavior

Terraform should create the SSL Proxy with both certificates (it's doable in the GCE UI).

It's important as it allows migration from a cert to another, as reflected in these docs: https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs#migrating-ssl

> Associate new Google-managed certificate with the correct target proxy **while maintaining the target proxy's association with the existing self-managed certificate**

### Actual Behavior

Terraform complains that `ssl_certificates` can have only one value.
(which is reflected in the docs https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_target_ssl_proxy#ssl_certificates)

### Steps to Reproduce

1. `terraform plan`

### References

* https://github.com/hashicorp/terraform-provider-google/pull/4316 (similar fix for https_proxy)

**Comment by edwardmedia** [comment]
Change label to `enhancement`

The code is set [MaxItems: 1](https://github.com/hashicorp/terraform-provider-google-beta/blob/1250ea52fe059c6fc9d65983f0a28002921da368/google-beta/resource_compute_target_ssl_proxy.go#L70)

From [api doc](https://cloud.google.com/compute/docs/reference/rest/v1/targetSslProxies)

>URLs to SslCertificate resources that are used to authenticate connections to Backends. At least one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates.

**Comment by quentinms** [comment]
Thanks for the quick turnaround!
