### ISSUE TITLE
google_cloud_identity_group intermittently fails to create group (due to propagation of changes)

### ISSUE THREAD

**Issue by LangdalP** [hashicorp/terraform-provider-google#8483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Version 0.13.5 - bug is independent of version as I will demonstrate below

### Affected Resource(s)

* google_cloud_identity_group

### Terraform Configuration Files

```tf
terraform {
  backend "local" {
    path = "state/terraform.tfstate"
  }
}

provider "google" {
  region  = "europe-west4"
  project = "my-gcp-project"
}

locals {
  gsuite_customer_id = "customers/REDACTED"
  letters = toset(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])
}

# Create one test group per letter in the alphabet
resource "google_cloud_identity_group" "test_groups" {
  for_each     = local.letters
  display_name = "test-${each.key}"
  parent       = local.gsuite_customer_id
  group_key {
    id = "test-${each.key}@myorg.com"
  }
  labels = {
    "cloudidentity.googleapis.com/groups.discussion_forum" = ""
  }
}
```

### Panic Output

```
Error: Error when reading or editing CloudIdentityGroup "groups/03bj1y3818fddp4": googleapi: Error 403: Error(2028): Permission denied for resource groups/03bj1y3818fddp4 (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ResourceInfo",
    "description": "Error(2028): Permission denied for resource groups/03bj1y3818fddp4 (or it may not exist).",
    "owner": "domain:cloudidentity.googleapis.com",
    "resourceName": "groups/03bj1y3818fddp4",
    "resourceType": "cloudidentity.googleapis.com/Group"
  }
]
```

### Expected Behavior

When creating groups with a sufficiently privileged service account, group creation should not intermittently fail.

### Actual Behavior

Once in a while, let's say every 5th or 10th run of the above terraform config, an error will happen during group creation.

### Steps to Reproduce

1. Replace project id, customer id and group ids in the above terraform
2. Run `terraform init`
3. Run `terraform apply` and `terraform destroy` until it fails. Typically every 5-10 run.

### Important Factoids

I have been in contact with GCP support about this issue. Together, we have figured out why it sometimes fails. Below is a snippet from my discussion with them:

[...] However, creating groups via terraform can still fail, as demonstrated above. I have inspected the source code for the terraform resource `google_cloud_identity_group` to form a hypothesis as to why:

1. The following source code shows where the API request to create the group is executed: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_cloud_identity_group.go#L188
2. The following source code (in the same function) shows that right after creating the group, the resource code tries to read the group from the API: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_cloud_identity_group.go#L223

As such, I think that there is a slight delay in the API after creating a group where the group is not visible in the API. This delay is enough for the terraform resource to trigger an error, since it can not find the group it just created.

**Response from GCP support:**

The terraform resource should implement exponential backoff to handle that creation of groups needs some time to propagate across servers. I checked the TerraForm documentation you provided, and determined that it does implement exponential backoff[1]. I'd expect the issue is that the system doesn't recognise the errors returned, so doesn't know that it should retry. I opened an internal ticket last month to document the errors returned by the Cloud Identity API, which should address part of the issue. I'd recommend opening an issue[2] on the TerraForm side so that they can update the system once the documentation is updated.

[1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job#retry_config

### Closing words

The situation might be a bit tricky, since the API seemingly returns a 403 response code when it does not think the group exists. However, the GCP representative does seem to think that it is retryable, so that might be one way to fix this issue.

**Comment by slevenick** [comment]
Thanks for the detailed explanation! I believe we have a precedent for similar resources that don't propagate immediately.
