### ISSUE TITLE
Cloud Composer version > 1.13.0 is not pulling the image of airflow-monitoring at the right path

### ISSUE THREAD

**Issue by ferdidb** [hashicorp/terraform-provider-google#8487]
If you try to create a `google_composer_environment` with the version `composer-1.14.0-airflow-*` or upper it tries to pick the image for the `airflow-monitoring` at the following path -> `europe-docker.pkg.dev/cloud-airflow-releaser/airflow-monitoring/airflow-monitoring:cloud_composer_service_2021-02-02-RC0`.
If we create a composer cluster from the UI with the same configuration, the image path used is : `eu.gcr.io/cloud-airflow-releaser/airflow-monitoring:cloud_composer_service_2021-02-02-RC0`.

If it is not coming from Terraform I am really sorry to disturb you but I don't really understand how it is doing that.
I tested with `provider = google` and `provider = google-beta` and in both cases it leads to what I described.

I know that there is no problem of this kind with the version `composer-1.13.0-airflow-*`.

My resource code looks like this : 
```
resource "google_composer_environment" "test-composer" {
  name     = "rbac-testing-compsoer"
  region   = var.region

  config {
    node_count = 3

    node_config {
      zone            = var.zone
      machine_type    = "n1-standard-4"
      network         = ...
      subnetwork      = ...
      service_account = ...
    }

    software_config {
      env_variables = {
....
      }

      pypi_packages = {
        networkx   = "==2.3"
        jsonschema = "[format]==3.0.2"
      }

      image_version  = "composer-1.14.2-airflow-1.10.14"
      python_version = 3

      airflow_config_overrides = {
        core-dags_are_paused_at_creation         = "True"
        core-dagbag_import_timeout               = 300
        core-dag_concurrency                     = 8
        core-store_serialized_dags               = "True"
        core-min_serialized_dag_update_interval  = 30
        core-store_dag_code                      = "True"
        core-dag_file_processor_timeout          = 300
        core-max_num_rendered_ti_fields_per_task = 0
        scheduler-catchup_by_default             = "False"
        scheduler-min_file_process_interval      = 20
        scheduler-dag_dir_list_interval          = 100
      }
    }
  }
```

Let me know if I can provide any more information.

Best regards,
Ferdinand

**Comment by ferdidb** [comment]
Sorry the mistake was coming from my side. Initially I had in the upper code `provider = google` and after removing it then it worked.

I passed from 
```
resource "google_composer_environment" "test-composer" {
  name     = "rbac-testing-compsoer"
  region   = var.region
  provider = google

.........
```
to the following : 
```
```
resource "google_composer_environment" "test-one-composer" {
  name     = "rbac-testing-one-compsoer"
  region   = var.region
  provider = google

.........
```

(and also changed the resource name and key name)

**Comment by ferdidb** [comment]
I am using terraform version 12.8.0 and google provider version 3.57.0

**Comment by ferdidb** [comment]
Pypi packages are also concerned. I have to change manually the image of `worker-scheduler` pod to have : 

```
    image: eu.gcr.io/cloud-airflow-releaser/airflow-builder:cloud_composer_service_2021-02-02-RC0
```
The previous value was of the same kind as upper, something like : `europe-docker.pkg.dev/cloud-airflow-releaser/airflow-builder/airflow-builder:cloud_composer_service_2021-02-02-RC0`

**Comment by edwardmedia** [comment]
@ferdidb it is not controlled by Terraform provider. Have you had chance to review [image version](https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments#softwareconfig)? Also can you try the latest version of the provider? If none works, please post the full debug log so I can take a look.

**Comment by ferdidb** [comment]
Hello @edwardmedia ,

I have tested several image of cloud composer but the problem is not coming from here because what I am seeing is that the image of PODs are not good, not the image of the composer cluster. I can't choose the image version of a pod (ex: airflow-monitoring) from the terraform configuration. Some pods have a good image path but some have not, and the consequence is that some pods have the state `Pod errors: ImagePullBackOff`. It is not normal since I am using the latest version of google provider `3.57.0`.

I tested several images (1.14.0, 1.14.1, 1.14.2) and I would say that all the `1.14.*` are concerned. I know that `1.13.0` is working but since I want to use a feature (RBAC) that appeared in `1.13.4` I am not interested in this one.

I think that those images are controlled by terraform in the sense that I created a cluster using terraform and created the same cluster manually. The manual cluster created successfully but not the terraform one (with the problem described upper).

You can reproduce this bug by trying to create a composer cluster using the configuration I gave.

**Comment by ferdidb** [comment]
If you are able to deploy a Cloud Composer with the spec I gave in the description it will definitely set that the problem is coming from my side.
I use terraform 0.12.8 and google 3.57.0

My resource conf is : 
```
resource "google_compute_network" "my-network" {
  name                    = "my-network"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "dll-subnetwork-network" {
  name                     = "dll-subnetwork"
  ip_cidr_range            = "10.2.0.0/16"
  region                   = "europe-west1"
  network                  = google_compute_network.dll-network.self_link
  private_ip_google_access = true
}

data "google_service_account" "composer-service-account" {
  account_id = ...
}


resource "google_composer_environment" "test-composer" {
  name     = "rbac-testing-compsoer"
  region   = var.region

  config {
    node_count = 3

    node_config {
      zone            = var.zone
      machine_type    = "n1-standard-4"
      network         = google_compute_network.my-network.self_link
      subnetwork      = google_compute_subnetwork.my-subnetwork-network.self_link
      service_account = data.google_service_account.composer-service-account.name
    }

    software_config {
      env_variables = {
....
      }

      pypi_packages = {
        networkx   = "==2.3"
        jsonschema = "[format]==3.0.2"
      }

      image_version  = "composer-1.14.2-airflow-1.10.14"
      python_version = 3

      airflow_config_overrides = {
        core-dags_are_paused_at_creation         = "True"
        core-dagbag_import_timeout               = 300
        core-dag_concurrency                     = 8
        core-store_serialized_dags               = "True"
        core-min_serialized_dag_update_interval  = 30
        core-store_dag_code                      = "True"
        core-dag_file_processor_timeout          = 300
        core-max_num_rendered_ti_fields_per_task = 0
        scheduler-catchup_by_default             = "False"
        scheduler-min_file_process_interval      = 20
        scheduler-dag_dir_list_interval          = 100
      }
    }
  }
```

What I experience is linked to the POD image of airflow-monitoring which is not able to be pulled from the cluster (because the address is wrong, see me previous comment). I think it could be linked to the API version called during the GKE cluster creation but to be honest I don't really know. The wrong image address seems to somehow be linked to a development environment while the correct one has a more operational name.

**Comment by edwardmedia** [comment]
It also failed on my test, timeout after 55 mins. I don't see anything wrong within the provider. I could be wrong. Bring @ScottSuarez to help 

```
Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 3, message: Http error status code: 400
Http error message: BAD REQUEST
Errors in: [Web server]; Error messages:
        Creation of airflow web server version failed. This may be an intermittent issue of the App Engine service. You may retry the operation later.
{"ResourceType":"appengine.v1.version","ResourceErrorCode":"504","ResourceErrorMessage":"Timed out waiting for the flex deployment to become network provisioned."}
```

Below is API test config that experienced the same result (note: using different image)
```
POST /v1beta1/projects/myproject/locations/us-central1/environments HTTP/1.1
Host: composer.googleapis.com
{
 "config": {
  "softwareConfig": {
   "imageVersion": "composer-1.13.4-airflow-1.10.12"
  }
 },
 "name": "projects/myproject/locations/us-central1/environments/issue8487-2"
}
```

**Comment by ferdidb** [comment]
Might it be related to that specific line? https://github.com/hashicorp/terraform-provider-google/blob/v3.57.0/google/resource_composer_environment.go#L13

The v1beta API version is used, but I think that it could use the `composer "google.golang.org/api/composer/v1"` instead, no?

**Comment by ScottSuarez** [comment]
Taking a look today

**Comment by ScottSuarez** [comment]
It looks like cloud composer is in the process migrating to Artifact Registry which is why the beta version of the api utilizes that endpoint. If you are using a private cluster I suggest following https://cloud.google.com/vpc-service-controls/docs/set-up-gke so you can ensure `pkg.dev` is on the dns record sets. You are right that switching to v1 will more then likely resolve this issue you are having but I expect that resolution to be transient once this officially launches. Let me know if any of that context help, if you are able to now resolve it, or you have any further questions here.

**Comment by ferdidb** [comment]
Hello @ScottSuarez, 

Thank you but I'm sorry that won't help since I'm not using a private cluster (I used the exact configuration I gave in my upper comment). I keep that link because that day will come but today it is not the fact.

This bug concerns everyone that wants to deploy a composer cluster with an image version > 1.13.0 no? 

I can wait for the resolution to be transient once it launches as you said because I don't want to bring complexity if it gonna be changed after.

Thank you for your time @ScottSuarez and @edwardmedia , hope this will be fixed soon :-).

Tell me if I can help, I would be glad and proud if I can participate in a fix (if one is needed).

**Comment by ScottSuarez** [comment]
@ferdidb could you inform me a little more about the error that occurs? Does the deployment succeed through terraform or is there an error in deployment? I found in deploying my own instance that deployment succeeded. I'm trying to diagnose what went wrong here with your deployment. I suspect maybe something related to the networking configuration. Maybe console output with environment variable `TF_LOG=DEBUG` set can yield some more information. In the meantime I'll try a a pass adapting more of your configuration.

```
data "google_composer_image_versions" "all" {
}

resource "google_composer_environment" "test" {
	name   = "good-stuff"
	region = "us-central1"
	config {
		node_config {
			network    = google_compute_network.test.self_link
			subnetwork = google_compute_subnetwork.test.self_link
			zone       = "us-central1-a"
		}
		software_config {
			image_version  = "composer-1.14.2-airflow-1.10.14"
			python_version = "3"
		}
	}
}

// use a separate network to avoid conflicts with other tests running in parallel
// that use the default network/subnet
resource "google_compute_network" "test" {
	name                    = "something-something"
	auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "test" {
	name          = "some-subnetwork"
	ip_cidr_range = "10.2.0.0/16"
	region        = "us-central1"
	network       = google_compute_network.test.self_link
}
```

d

**Comment by ferdidb** [comment]
Well I just tried again and it works now. I didn't change anything in my terraform configuration nor manually through the UI. I assume that there was a change either on the 3.58.0 google provider version or else where, may be you know where @ScottSuarez ?

My problem was that when deploying through Terraform some pods (ex: airflow-monitoring, worker-scheduler) had a "bad image path" in the sense that their status were "IMagePullBackOff" which means that there were not able to download the image.
The path in question was for example `europe-docker.pkg.dev/cloud-airflow-releaser/airflow-monitoring/airflow-monitoring:cloud_composer_service_2021-02-02-RC0`.
While the cluster was creating, if I changed the image path to have `eu.gcr.io/cloud-airflow-releaser/airflow-monitoring:cloud_composer_service_2021-02-02-RC0` then it was working.

Same was happening for pod worker-scheduler which add PyPi packages.

Now it seems that these pods are able to pull their images without problems.

**Comment by ScottSuarez** [comment]
huh, really strange! I have no clue why it wasn't working before and is working now? Maybe composer team fixed something behind the scenes? Thanks @ferdidb for your patience on this. I'm glad you're able to provision resources now ! :) Feel free to reopen if the issue reemerges !
