### ISSUE TITLE
Manage go.mod in Magic Modules

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8501]
We've run into a couple issues with syncing `go.mod` between `google`/`google-beta`/`google-private` and I wonder if we should just manage `go.mod` in one place. This gives us a little less flexibility, but it's flexibility we've never used.

MM managed the file for a while, but we were automatically generating it. That took a long time (2-3 mins per Magician run) so let's just handwrite it now.

**Comment by melinath** [comment]
You'll also need to modify the code I just added in https://github.com/GoogleCloudPlatform/magic-modules/pull/5026 and https://github.com/GoogleCloudPlatform/magic-modules/pull/5030 - we will need to recognize changes to the go.mod file as triggering test runs.

**Comment by melinath** [comment]
no, https://github.com/GoogleCloudPlatform/magic-modules/pull/5032 is specific to terraform-google-conversion, so it will not use the same go.mod file as the providers.

**Comment by shuyama1** [comment]
> no, [GoogleCloudPlatform/magic-modules#5032](https://github.com/GoogleCloudPlatform/magic-modules/pull/5032) is specific to terraform-google-conversion, so it will not use the same go.mod file as the providers.

Got it! Thanks.
