### ISSUE TITLE
google_compute_address doesn't support labels

### ISSUE THREAD

**Issue by skorobogatydmitry** [hashicorp/terraform-provider-google#8507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/google v3.57.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Platform

Mac OS 11.2

### Affected Resource(s)

google_compute_address

### Terraform Configuration Files

```tf
resource "google_compute_address" "lb-public-addresses" {
  name = "lb-public-address"
  region = "europe-west4"
  labels = {
    some = "other"
  }
}
```

### Expected Behavior

Resource added.

### Actual Behavior

```
Error: Unsupported argument

  on gcp-subscriber/main.tf line 92, in resource "google_compute_address" "lb-public-addresses":
  92:   labels = {

An argument named "labels" is not expected here.
```

### Steps to Reproduce

1. `mkdir test`
2. `cd test`
3. `nano test.tf`
4. Put this config:
``` tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.57.0"
    }
  }
}
provider "google" {
  credentials = var.gcp-config
  project = var.gcp-project
}
resource "google_compute_address" "test" {
  name = "test"
  region = "europe-west4"
  labels = {
    some = "other"
  }
}
variable gcp-project {
  type = string
}
variable gcp-config {
  type = string
}
```
5. `terraform init`
6. `terraform apply -var gcp-project=PROJECT -var gcp-config=CREDS_FILE`

### Important Factoids

- `labels` claimed to be supported for this resource.
- initially I faced this when used resource inside a module.
- same issue with `google_compute_forwarding_rule`
- `terraform apply` tolerates existing labels (doesn't attempt to cleanup manually added ones)

**Comment by edwardmedia** [comment]
@skorobogatydmitry `labels` is marked as [beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#labels). Can you try beta to see if that works?

**Comment by skorobogatydmitry** [comment]
> @skorobogatydmitry `labels` is marked as [beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#labels). Can you try beta to see if that works?

@edwardmedia , yes, it works. Thank you for clarifying!
