### ISSUE TITLE
google_datafusion_instance does not support developer instance type

### ISSUE THREAD

**Issue by fmiquel90** [hashicorp/terraform-provider-google#8508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.57.0
+ provider registry.terraform.io/hashicorp/google-beta v3.57.0

### Affected Resource(s)

* google_data_fusion_instance

### Terraform Configuration Files

```tf
variable "project_id" {
  default = "staging-test-24246"
}

variable "impersonate_service_account" {
  default = "my_service_account"
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.57.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "3.57.0"
    }
  }
}

provider "google" {
  project                     = var.project_id
  impersonate_service_account = var.impersonate_service_account
}

provider "google-beta" {
  project                     = var.project_id
  impersonate_service_account = var.impersonate_service_account
}

resource "google_data_fusion_instance" "instance" {
  provider                      = google-beta
  name                          = "datafusion"
  description                   = "datafusion instance"
  region                        = "europe-west-2"
  type                          = "developer"
  enable_stackdriver_logging    = false
  enable_stackdriver_monitoring = false
  private_instance              = false
  version                       = "6.3.0"
}
```

### Expected Behavior

Deploy a DataFusion Instance of Developer type

### Actual Behavior

```tf
Error: expected type to be one of [BASIC ENTERPRISE], got developer

  on main.tf line 37, in resource "google_data_fusion_instance" "instance":
  37:   type                          = "developer"
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

It's possible to deploy a Data Fusion instance of Developer type with the Google Cloud SDK

**Comment by venkykuberan** [comment]
Looks like `DEVELOPER` type added after we created the resource. We will fix it, thanks for filing the issue

**Comment by fmiquel90** [comment]
Yes and according to the Cloud SDK documentation, a zone argument is required only for the DEVELOPER instance type : Compute Engine zone in which the instance will be created. Only needed for DEVELOPER edition

https://cloud.google.com/sdk/gcloud/reference/beta/data-fusion/instances/create
