### ISSUE TITLE
Error: The resource 'projects/gce-uefi-images/global/images/family/ubuntu-1804-lts' was not found

### ISSUE THREAD

**Issue by andrewm4894** [hashicorp/terraform-provider-google#8512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.4
+ provider registry.terraform.io/-/google v3.43.0
+ provider registry.terraform.io/hashicorp/google-beta v3.43.0

### Affected Resource(s)

* google_compute_image

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

# define image to use
data "google_compute_image" "myimage" {
  family  = "ubuntu-1804-lts"
  project = "gce-uefi-images" # does not work anymore
  #project = "ubuntu-os-cloud" # this does work but means i have to destroy and recreate everything
}

```

### Expected Behavior

This used to work fine but recently it seems like terraform can not find the gce-uefi-images project or cannot access it. 

### Actual Behavior

I received error message

```
Error: error retrieving image information: googleapi: Error 404: The resource 'projects/gce-uefi-images/global/images/family/ubuntu-1804-lts' was not found, notFound
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
GCP doesn't have that image under that project any more, you can verify it by this command.  

```gcloud compute images list --project gce-uefi-images ```

I am closing this as its not a terraform/provider issue

**Comment by andrewm4894** [comment]
The source_image_project here might need to change maybe https://registry.terraform.io/modules/terraform-google-modules/vm/google/latest/submodules/instance_template

Not sure if this the correct place for that?

Maybe it's something I need to try raise with gcp somehow. Feels like a project just disappearing like this would break things for a lot of people, but agree not really a terraform issues (apart from that small update to the docs maybe so others don't try use the old project).

**Comment by morgante** [comment]
This project is referenced in the docs: https://github.com/search?p=1&q=org%3Ahashicorp+gce-uefi-images&type=Code

@rileykarson We should re-open and address.

**Comment by slevenick** [comment]
Looks like a docs fix would help. May require a little investigating into what can replace these images
