### ISSUE TITLE
Google Cloud VMware Engine Support 

### ISSUE THREAD

**Issue by bohleadam** [hashicorp/terraform-provider-google#8516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud VMware Engine deploys a VMware SDDC "Private Cloud" in a supported Google region. The ability to deploy this service and manage this resource through terraform would be useful

### New or Affected Resource(s)

* [ ] google_vmware_engine_private_cloud
* [ ] google_vmware_engine_cluster
* [ ] google_vmware_engine_network

## References

* https://cloud.google.com/vmware-engine/docs/reference/rest
* b/186891448

**Comment by rileykarson** [comment]
@bohleadam is there an API reference page available you can link us to?

**Comment by bohleadam** [comment]
@rileykarson, I have done some more investigation here and it doesn't look like there is a documented API for Google Cloud VMware Engine at the moment. I believe this is currently in development. So I may have been a little premature in raising this. I appreciate we are stuck until there is an API. Is it possible to keep this enhancement request open until the API surfaces, or is it best to close the request and reopen this request when an API is published?

**Comment by rileykarson** [comment]
Either way is fine- labeled this as upstream to represent that the API's not there yet.

**Comment by cb-randy** [comment]
any update on this?

**Comment by bohleadam** [comment]
@cb-randy one of my colleagues has access to a early release api for Google cloud vmware engine. But as far as I am aware at the moment. The GCVE api is not yet GA.

**Comment by cb-randy** [comment]
Thanks @bohleadam Happy to contribute to make this happen.  My company is looking to automate GCVE for our clients.

**Comment by blarose** [comment]
This is a really important feature and I am willing to help out in any way that I can.

**Comment by jaimeseoane** [comment]
I fully support this feature.. I recently started working with the VMware Engine for testing automation configurations but it would be great that the VPC setup could be done via terraform since at the moment the whole setup is manual

**Comment by ashishsingh1508** [comment]
They are working on this and will release soon

**Comment by codding-buddha** [comment]
I am working on it.

**Comment by melinath** [comment]
This is resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8050 and https://github.com/GoogleCloudPlatform/magic-modules/pull/8101.
