### ISSUE TITLE
terraform destroy fails if an _iam_policy resource was modified since last apply

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform-provider-google#8519]
If an IAM policy was modified since the last `terraform apply`, `terraform destroy` fails with:
```
Error: Error setting IAM policy for pubsub topic "projects/my-project/topics/test": googleapi: Error 409: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff.
```
This error from the API is misleading.  There is no concurrent update.  `terraform destroy` used the etag from the state file (which has changed due to the out-of-tf modifcation), even though it is out of date.  Specifying `-refresh=true` but it sure sounds like it should.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$  terraform version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.56.0
```

### Affected Resource(s)

I have tested this behavior with:
* `google_pubsub_topic_iam_policy`
* `google_pubsub_subscription_iam_policy`

But it likely affectes other `*_iam_policy` resources too.

`_iam_binding` and `_iam_member` are _not_ affected

### Terraform Configuration Files

```tf
variable "project_id" {}

provider "google" {
  project = var.project_id
}

data "google_iam_policy" "test" {
  binding {
    role = "roles/viewer"
    members = [
      "allUsers",
      "allAuthenticatedUsers",
    ]
  }
}

resource "google_pubsub_topic" "test" {
  name = "test"
}

resource "google_pubsub_topic_iam_policy" "test" {
  topic       = google_pubsub_topic.test.name
  policy_data = data.google_iam_policy.test.policy_data
}
```

### Debug Output

https://gist.github.com/rvandegrift/77f859e635a3be2ec189df717527fbca

Before modifying the iam policy, the etag was `BwW7uTzJ8DQ=`.  Afterwards, it was `BwW7uUxt4pM=`.  You can see terraform using the first value in the above trace.

### Expected Behavior

`terraform destroy` should succeed here:
1. if `-refresh=true`, the destroy operation should catch the 409, pull the etag, and retry.
2. alternatively, if a resource is being destroyed, updates to its iam policy can be skipped (very soon, it won't exist)

If I use `_iam_binding` or `_iam_member` instead, terraform seems to always get the latest etag first.  Hence why those resources work correctly in this case.

### Actual Behavior

`terraform destroy` will only use the old etag, and so it fails.

Destroying a few times in a row kind of works.  For some reason, terraform only tries to delete the topic on the second attempt.  The call pattern for each attempt looks like this:
1. first attempt
    1. pubsub.projects.topics.setIamPolicy (response 409)
2. second attempt
    1. pubsub.projects.topics.delete (response 200)
    2. pubsub.projects.topics.setIamPolicy (response 409)
3. third attempt
    1. pubsub.projects.topics.setIamPolicy (response 404)

### Steps to Reproduce

1. `TF_VAR_gcp_project=my-project`
1. `terraform apply`
2. Note the etag value from the state: `terraform state show google_pubsub_topic_iam_policy.test | grep etag | cut -f 2 -d \"`
2. Update the IAM policy, note the new etag: `gcloud pubsub topics remove-iam-policy-binding test --member allUsers --role roles/viewer --project=$TF_VAR_gcp_project`
3. `terraform destroy`

### References

* #0000

**Comment by edwardmedia** [comment]
@rvandegrift I tested your code and couldn't repro the result. In my test, I commented `allusers` in the members and re-_apply_ and then call  _tf destroy_. I wonder how you `Update the IAM policy`. Can you provide the detail steps?

**Comment by rvandegrift** [comment]
Hi @edwardmedia - you need to make the change outside of terraform, since an `apply` will pull the new etag.  See step 4 in my above report.

**Comment by edwardmedia** [comment]
@rvandegrift  if you make changes outside of terraform, you probably need to sync the state by `import` the resources before you can run destroy.

**Comment by rvandegrift** [comment]
@edwardmedia Do you mean that I have to do `terraform state rm ... && terraform import ...`?  A straight up import will fail because the resource is already present in the state.

The help for the `-refresh` option says that it updates the state before attempting a destroy.  But the steps above shows that the `_iam_policy` resources do not do that.

**Comment by edwardmedia** [comment]
@rvandegrift yes. You can also delete the state file manually. But be careful, as the state file keeps the state for all resources in your config.

**Comment by rvandegrift** [comment]
@edwardmedia Is there a reason that's necessary specifically for the _iam_policy resource types?  I've never had to re-import before destroy before, even if there are changes from the last known state.

**Comment by edwardmedia** [comment]
@rvandegrift the key is **make the change outside of terraform**. Does terraform know what changes were made? This is general behavior and should be applied on all resources. Give me examples that are different.

**Comment by rvandegrift** [comment]
@edwardmedia Based on the help, yes, terraform should know because `-refresh` defaults to `true`:
```
$ terraform destroy -h
...
   -refresh=true          Update state prior to checking for differences. This
                          has no effect if a plan file is given to apply.
```
I understand this to mean that terraform will first refresh resources to find the diffs, and then destroy.  If it refreshs the IAM policy, it should have the new etag.  Am I misunderstanding the help?


But the other IAM resources work as expected.  Here's a full example.
Terraform config:
```
variable "project_id" {}

provider "google" {
  project = var.project_id
}

resource "google_pubsub_topic" "test" {
  name = "test"
}

resource "google_pubsub_topic_iam_member" "test" {
  topic  = google_pubsub_topic.test.name
  member = "allUsers"
  role   = "roles/viewer"
}
```

Execution:
```
$ export TF_VAR_project_id=my-project
$ terraform apply -auto-approve
google_pubsub_topic.test: Creating...
google_pubsub_topic.test: Creation complete after 3s [id=projects/my-project/topics/test]
google_pubsub_topic_iam_member.test: Creating...
google_pubsub_topic_iam_member.test: Creation complete after 5s [id=projects/my-project/topics/test/roles/viewer/allusers]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
$ gcloud pubsub topics remove-iam-policy-binding test --member=allUsers --role roles/viewer --project=$TF_VAR_project_id
Updated IAM policy for topic [test].
etag: BwW8CR0NCag=
version: 1
$ terraform destroy -auto-approve
google_pubsub_topic_iam_member.test: Destroying... [id=projects/my-project/topics/test/roles/viewer/allusers]
google_pubsub_topic_iam_member.test: Destruction complete after 6s
google_pubsub_topic.test: Destroying... [id=projects/my-project/topics/test]
google_pubsub_topic.test: Destruction complete after 1s

Destroy complete! Resources: 2 destroyed.
```

**Comment by edwardmedia** [comment]
@rvandegrift  three types of **IAM** resources behave a little bit different. You may find the details in below issue. Does this make sense?

[IAM issues due to deleted IAM member](https://github.com/hashicorp/terraform-provider-google/issues/7278)

**Comment by edwardmedia** [comment]
@rvandegrift I have tried above execution steps on both `google_pubsub_topic_iam_member` and `google_pubsub_topic_iam_policy`. All work fine. 

For `google_pubsub_topic_iam_policy`, I strictly followed your [steps](https://github.com/hashicorp/terraform-provider-google/issues/8519#issue-812452410) (#2,#4 and #5). It works fine with me.

**Comment by edwardmedia** [comment]
@rvandegrift does the explanation make sense to you?

**Comment by edwardmedia** [comment]
@rvandegrift I am closing this issue. Feel free to reopen it if you need to continue the conversation.
