### ISSUE TITLE
"Expected OAuth 2 access token, login cookie or other valid authentication credential" -- broken since provider version 3.53.

### ISSUE THREAD

**Issue by gswallow** [hashicorp/terraform-provider-google#8521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.53.0
+ provider registry.terraform.io/hashicorp/google-beta v3.53.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.0.0

### Affected Resource(s)

google_project_iam_member

### Expected Behavior

When running `terraform destroy`, resources are deleted without complaint.  This is what (mostly) happened until I recently upgraded the providers.  

### Actual Behavior

If I trust upgrades (I upgraded to 3.57.0), all of a sudden I can't delete resources:

Error: Error when reading or editing Resource xxx for IAM Member (role "serviceAccount:service-508170527894@container-engine-robot.iam.gserviceaccount.com", "roles/cloudkms.cryptoKeyEncrypterDecrypter"): Request "Delete IAM Members roles/cloudkms.cryptoKeyEncrypterDecrypter serviceAccount:service-508170527894@container-engine-robot.iam.gserviceaccount.com for \"project \\\"xxx\\\"\"" returned error: Batch request and retried single request "Delete IAM Members roles/cloudkms.cryptoKeyEncrypterDecrypter serviceAccount:service-508170527894@container-engine-robot.iam.gserviceaccount.com for \"project \\\"xxx\\\"\"" both failed. Final error: Error retrieving IAM policy for project "xxx": googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
More details:
Reason: authError, Message: Invalid Credentials

### Steps to Reproduce

1. `terraform destroy`

### Important Factoids

I am impersonating a service account in a project where the resources reside:

```
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.52.0"
    }
    random = {
      source = "hashicorp/random"
      version = "3.0.0"
    }
    google-beta = {
      source = "hashicorp/google-beta"
      version = "3.52.0"
    }
  }
}

provider "google" {
  project = var.project_id
  alias   = "tokengen"
}

data "google_client_config" "default" {
  provider = google.tokengen
}

data "google_service_account_access_token" "sa" {
  provider               = google.tokengen
  target_service_account = var.terraform_service_account
  lifetime               = "3600s"

  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email"
  ]
}

provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
}
```

### References

* #0000

**Comment by gswallow** [comment]
What's interesting is that if I *retry,* deletes will eventually work.  I just have to retry enough times.

**Comment by ScottSuarez** [comment]
curious, I wonder what could be causing this it works at times and other times it doesn't. Do you have more details for the terraform run? If you run terraform with the environment variable TF_LOG=DEBUG you should get a more detailed output that you can share. Just make sure to scrub any sensitive bits

**Comment by rileykarson** [comment]
@gswallow: Is your config extremely large? Those tokens time out after an hour, which may be it. Otherwise have you happened to try the direct support for impersonation in the provider? https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#impersonate_service_account

**Comment by maitreya-source** [comment]
We were able to replicate this issue with smaller config as well and we increased the timeout to 3600s too just to be safe. 
Provider version - 3.61
Terraform version - 0.13.6

**Comment by hypsrizzari** [comment]
I ran into this today, also destroying, but I was using `terraform plan -destroy -target ...`.  I'm using an impersonation token as well.  I get the proper plan, but when I apply, same error.

The data resource gets added to the state file, so the previous token used is already there in state.  It's been several hours, so that token expired, but I used target so the data source is not being refreshed.  I've encountered that scenario before in targeted plans where I'm creating as well.

I worked around this by running `terraform refresh`.  You can also target with this command.  This updated the token in state and all was well.  Since running an apply will refresh, you can also do that to get the updated token, which might explain why it would seemingly just work after a while.  I was also able to run `terraform apply -target data.google_service_account_access_token.default` which refreshed the token as well, and then subsequently able to run my targeted destroy.

Terraform: 0.14.11
google provider: 3.78.0


Error I got:
```
Error: Error when reading or editing Router: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
More details:
Reason: authError, Message: Invalid Credentials
```

**Comment by shmish111** [comment]
I had a very similar issue with importing resources, a terraform refresh seemed to fix the issue, very weird.

**Comment by rileykarson** [comment]
When doing authentication this way- leveraging a token from a datasource- it's expected that the token will fall out of date if you're doing targeted actions. They last for a short period of time, and they need `terraform refresh` ran on them to get updated. By running `apply` with a `-target`, the token is keeping its old value and going stale.

**Comment by ScottSuarez** [comment]
Closing this issue since there is nothing we can do here. The tokens retrieved in the manner are good for one hour. Excessively long configuration deployments can run into this issue.
