### ISSUE TITLE
google_sql_database_instance default collation

### ISSUE THREAD

**Issue by Patryk7975** [hashicorp/terraform-provider-google#8524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I need to write terraform script that creates MS SQL Server instance in Google Cloud. 
As far as I can see there is no way to set default server collation other than Latin General so I can change collation of system databases (master, model, tempdb, msdb).
According to the gcp API documentation it should be possible to set "collation" attribute in "settings" section but when I put it in my terraform script it fails with an error: "an argument named "collation" is not expected here"

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "dev-sql" {
    region = "europe-north1"
    database_version = "SQLSERVER_2017_STANDARD"
    deletion_protection = false
    root_password = "Password"

    settings {
        collation = "Polish_CI_AS"      
        tier = "db-custom-2-7680" 
    }
}
```

### References

* #https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance
* #https://cloud.google.com/sql/docs/sqlserver/admin-api/rest/v1beta4/instances

**Comment by suckowbiz** [comment]
We are also in need to set the default collation of a SQL Server instance.

@Patryk7975 How did you workaround this issue?

**Comment by Patryk7975** [comment]
> We are also in need to set the (default) collation of a SQL Server instance (database).
> 
> @Patryk7975 How did you workaround this issue?

For now default collation of our server and collation o system databases is Latin General because there is no way to change it in terraform script.
I changed only collation of application database in google_sql_database resource configuration.
In case of collation conflicts (for example when using temporary tables) we will solve it programatically in sql.
