### ISSUE TITLE
Add tests for google_compute_interconnect_attachment

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Affected Resource(s)

* google_compute_interconnect_attachment

### Issue Description

Per https://github.com/GoogleCloudPlatform/magic-modules/pull/4496#issuecomment-780923823 we should now be able to add tests for this resource. We should do that! It is currently untested.

**Comment by upodroid** [comment]
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/7972

**Comment by melinath** [comment]
Indeed - thanks!
