### ISSUE TITLE
google_bigquery_dataset_iam_member doesn't handle deleted members

### ISSUE THREAD

**Issue by bschaeffer** [hashicorp/terraform-provider-google#8533]
Issue #7896 is clearly a bug which is still happening but was auto closed and locked.

Its happening to us in the exact same way as described in the ticket and the solution is still the same. Has it been fixed?

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/8132

**Comment by bschaeffer** [comment]
`3.48.0`. If fixed we should reference the fix in #7896 as well.

**Comment by edwardmedia** [comment]
This is fixed in [v3.54.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.54.0)
Closing the issue now.
