### ISSUE TITLE
deprecation warning for bigtable gc policies creates impossible situation

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform-provider-google#8539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Hello
We started getting deprecation warnings like this:
```
for bt gc policies, we got the following error:
Warning: Deprecated Attribute
  on bigtable.tf line 34, in resource "google_bigtable_gc_policy" "foo":
  34:     days = 3
Deprecated in favor of duration
(and 19 more similar warnings elsewhere)
```

That's fine, so Ok, we change 3d to, say, 72h. At that point, though, terraform apply returns the error
`Error: doesn't support update` if we try to a change like this
```diff
  ~ resource "google_bigtable_gc_policy" "foo" {
        id            = "(age() > 3d || versions() > 1)"
        # (5 unchanged attributes hidden)

      ~ max_age {
          - days     = 3 -> null
          + duration = "72h"
        }

        # (1 unchanged block hidden)
    }
```

We can remove the state and try to reimport it, however, then we find out that this is not an importable resource
```
Error: resource google_bigtable_gc_policy doesn't support import
```

It may be safe to simply remove the state, reapply everything, and not worry about dupe resources being left behind, but I don't know enough about bt garbage-collection policies to know if this is safe / sane. In either event, the current experience is frustrating.

### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.56.0
+ provider registry.terraform.io/hashicorp/google-beta v3.56.0
```
(tried with 3.57.0 as welll)

### Affected Resource(s)
* google_bigtable_gc_policy

### Terraform Configuration Files
```tf
resource "google_bigtable_gc_policy" "foo" {
  instance_name = module....
  table         = module....
  column_family = "data"

  max_age {
    duration = "72h"
  }
}
```
### Debug Output
can provide if needed

### Expected Behavior
When changing from, say, 30d to 720h for `duration`, we'd expect that the change will be a noop or state only change

### Actual Behavior
Terraform gives the error
```
Error: doesn't support update
```

### Steps to Reproduce

1. `terraform apply`

**Comment by rileykarson** [comment]
Deduping to https://github.com/hashicorp/terraform-provider-google/issues/8416
