### ISSUE TITLE
DialogflowCX as enhancement

### ISSUE THREAD

**Issue by ObjectiveTruth** [hashicorp/terraform-provider-google#8542]
### Affected Resource(s)

* google_dialogflow_cx_*

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

DialogflowCX is a new feature of GCP as it just gained General Availability in Dec, 2020. DialogflowCX is used in the contact center space and this means many enterprise customers. With the rise of DevOps, this will help out larger clients for GCP

**Comment by roaks3** [comment]
I believe the feature requested here has been added
