### ISSUE TITLE
UNSPECIFIED release_channel cannot be specified on google_container_cluster creation

### ISSUE THREAD

**Issue by withernet** [hashicorp/terraform-provider-google#8543]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.57.0
```

### Affected Resource(s)

```
+ provider registry.terraform.io/hashicorp/google v3.57.0
```

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  ...

  release_channel {
    channel = "UNSPECIFIED"
  }
}
```

### Debug Output

NA

### Panic Output

NA

### Expected Behavior

When creating an initial cluster, if `release_channel.channel = "UNSPECIFIED"` then the release channel is not set at all:

This is plan:

```
      + release_channel {}
```

Changing this to `STABLE` results in:

```
      + release_channel {
          + channel = "STABLE"
        }
```

This results in `auto_upgrade = false` resulting in an error on cluster creation; so having to re-apply to fix the issue.

### Actual Behavior

Expect `UNSPECIFIED` to be set on cluster creation

### Steps to Reproduce

1. Create a bare-minimum `google_container_cluster` resource with the release_channel set to `UNSPECIFIED`
2. `terraform plan` to see that it's not set
3. `terraform apply` again to see that it gets set after cluster creation

### Important Factoids

If `auto_upgrade` for nodes is set to `false`; then on initial cluster creation the cluster cannot be created, for ex:

```
Error: error creating NodePool: googleapi: Error 400: Auto_upgrade and auto_repair cannot be false when release_channel REGULAR is set., badRequest
```

**Comment by edwardmedia** [comment]
@withernet I am not super clear what the problem is here. Can you post the config and specify how to repro the issue? Thanks

**Comment by withernet** [comment]
On initial cluster create, the release channel is not set if it's `UNSPECIFIED`; after it's created a `terraform apply` will change it from `STABLE` to `UNSPECIFIED`.

**Comment by edwardmedia** [comment]
@withernet when it was set to **STABLE** and how to do that?

>after it's created a terraform apply will change it from STABLE to UNSPECIFIED.

**Comment by withernet** [comment]
What I am saying is it automatically sets to `STABLE` and ignores your setting on initial creation if it's set to `UNSPECIFIED`.

**Comment by Gaardsholt** [comment]
I am having the same issue.
I want to create a cluster which is NOT in a release channel, where I control the k8s version myself instead.
If I set this
```hcl
release_channel {
  channel = "UNSPECIFIED"
}
```
Then the cluster will be created with the "REGULAR" channel

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/8390
