### ISSUE TITLE
Terraform Google Provider Fails to enable API when using service account auth

### ISSUE THREAD

**Issue by Lauan** [hashicorp/terraform-provider-google#8544]
Hi,

I was going to post on **bug** session, but thought better to ask first.
I am using Terraform to automate the creation of Artifact Registry repositories in different GCP projects and stumbled on a strange behavior.

On my terraform file (I am actually using modules, but it isn't relevant here) I am declaring the creation/activation of some Google APIs using the resource **google_project_service**.

The authentication method I am using is "json key" from a _Project Owner_ service account (I am keeping the key in a safe place), and at my first attempt I received an error about having to first manually activate the **Service Usage API**. After a little reading I found out that in fact this API has to be activated and after that my problem was solved (quite annoying having to activate the API manually to only then start my automation, but ok, my question comes now).

After a few days, I had to debug one specific case and forgot I was already authenticated with my user account (using gcloud CLI) and the env GOOGLE_APPLICATION_CREDENTIALS was not set. When I ran the terraform init/plan/apply, the specs were applied successfully without first activating the **Service Usage API**.

**Is that an expected behavior? Is the Service Usage API only needed when authenticated through service account?**

Terraform v0.14.4
provider.google v3.57.0
provider.google-beta v3.57.0

**Comment by edwardmedia** [comment]
@Lauan first, you should be able to enable **Service Usage API** using below config. 

```tf
resource "google_project_service" "serviceusage" {
  project = google_project.project.id
  service = "serviceusage.googleapis.com"
  disable_dependent_services = true
}
```
The answer to your below question is "NO". Once the API is enabled, the endpoint **serviceusage.googleapis.com** starts to accept the http requests in the project. There is nothing to do with authentication. Once it is enabled, it remains enabled until you disable it through UI or calling `tf destroy` on above terraform resource, etc.
>Is the Service Usage API only needed when authenticated through service account?

Regarding the authentication method, we recommend using the [key file](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials) of a service account. To be able to create other resources, this service account must have permissions on these resources. Keep in mind, sometimes a _Project Owner_ may not have enough privilege. Some resources are on project level. In that case, the service must be on Org or Folder level. For example, you can't use a _Project Owner_  service account to create another project. 

Does this make sense?

**Comment by edwardmedia** [comment]
@Lauan is this still an issue?

**Comment by Lauan** [comment]
Hi @edwardmedia , sorry for the late reply.

The things you said make perfect sense to me, in fact it is what I was expecting when I started writing the code.
I may have been a little too vague in the first post and will try to detail better.
In my test environment, I have a project where i created a service account (assigned to the role 'Project Owner') and the following blocks (between other resources):

```yaml
[...]
resource "google_project_service" "serviceusage-api" {
  project = var.gcp_project
  service = "serviceusage.googleapis.com"
}

resource "google_project_service" "artifactregistry-api" {
  project = var.gcp_project
  service = "artifactregistry.googleapis.com"
}
[...]
```

_Obs: My user account also has the "Project Owner" role._

1. Logged out from my user account and created the GOOGLE_APPLICATION_CREDENTIALS env with the Service Account's json key;
2. Ran terraform apply and got the following error:
`* google_project_services.service: Error creating services: googleapi: Error 403: Service Usage API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured`
3. Tried several fixes (adding explicit dependencies to the resources and creating another service account with same privileges), but none did the trick;
4. Found [this thread](https://github.com/hashicorp/terraform-provider-google/issues/1538) and tried to manually activate the "Service Usage API" before running terraform. After that everything went fine!;

_in the meanwhile, I had logged on my GCP user account through gcloud CLI and removed the GOOGLE_APPLICATION_CREDENTIALS env_

5. After a few days I created a fresh new project and ran the same terraform spec. To my surprise, the plan was applied successfully without having to first activate the API.
6. For the sake of testing, I created a third project (same configs, owner service account and it all) and checked if the Service Usage API was activated (it wasn't);
7. Tried to run Terraform from Service account and receive the same error from **item 2**;
8. Tried to run Terraform from my user account (logged on to gcloud CLI) and all the resources were created successfully.

That's why I was thinking on posting as a Bug, but I may run another tests if necessary.
Thanks!

**Comment by Lauan** [comment]
Hi @edwardmedia .
Actually I'm still confused. My tests has only proven (at least in my environment) that something is off.

- When I run terraform apply (authenticating on google cloud using a service account's json key) it obligates me to first activate the Service Usage API manually;
- When I run terraform apply (authenticating on google cloud using gloud CLI with my user account) it simply applies without asking anything.

Both accounts has the same "Project Owner" role.

My question is about the different behaviors in exact the same test environment (only authenticating with different methods).

Sorry if I am complicating a simple question, but i have the impression that I couldn't be quite clear before.

**Comment by edwardmedia** [comment]
@Lauan as I mentioned earlier, `Service Usage API` has no direct impact on authentication or vice versa. I don't the details about the terraform config code and how you `authenticating on google cloud using gcloud CLI with my user account`. If your config contains resources that require `Service Usage API`, the first one seems reasonable.
For your 2nd one test, after `authenticating on google cloud using gcloud CLI with my user account` and before run terraform apply, have you checked if  `Service Usage API` is enabled or not? You might want to print out the gcloud log (--log-http) to see if `Service Usage API` is enabled in any steps.

**Comment by edwardmedia** [comment]
@Lauan do it make sense to you?

**Comment by edwardmedia** [comment]
@Lauan closing the issue now as no more questions are raised.
