### ISSUE TITLE
Remove trace-append and trace-ro scope aliases on compute instance scopes

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#8545]
### Description
Attempted to remove these two previously as they aren't listed on the [official documentation](https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/set-scopes#--scopes) with https://github.com/hashicorp/terraform-provider-google/pull/8496 however this is going to be a breaking change so silo'ing it for a major version release.

### References

* https://github.com/hashicorp/terraform-provider-google/pull/8496
* https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/set-scopes#--scopes
* https://github.com/hashicorp/terraform-provider-google/issues/8495

**Comment by rileykarson** [comment]
@ScottSuarez: Feel free to unassign if you won't get to this!

I'm marking as `4.0.0-ready` because there is no change needed in `3.X` (we can't send a deprecation message)
