### ISSUE TITLE
GCP Autopilot Support

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-google#8553]
### References

https://www.youtube.com/watch?v=_JKsv2BtAnY

https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview

### Description

Is there a way to support Autopilot on GCP?

**Comment by rileykarson** [comment]
@c2thorn: Would it make sense to represent this as a separate resource, or as configuration on the primary resource?

**Comment by c2thorn** [comment]
I think it is worth trying to add it to the primary resource, there are more overlapping features than first anticipated.

**Comment by paulwilljones** [comment]
Once google-api-go-client [v0.41.0](https://github.com/googleapis/google-api-go-client/tree/release-v0.41.0/container/v1beta1) is released with Autopilot support, this is ready:

https://github.com/hashicorp/terraform-provider-google/compare/master...paulwilljones:autopilot

**Comment by WilliamDenniss** [comment]
+1 to add it as a primary resource, this aligns with how we treated the GKE API & CLI. 

Goal is to have "one GKE" product, just with two different ways to operate it.

**Comment by vongohren** [comment]
Is the roadmap of getting the google release and this release out, far away?

**Comment by hcharley** [comment]
@vongohren If what I'm reading from @paulwilljones about v0.41.0 is correct, I think we're waiting on this PR:

https://github.com/googleapis/google-api-go-client/pull/875

**Comment by hcharley** [comment]
PR https://github.com/googleapis/google-api-go-client/releases/tag/v0.41.0 released

**Comment by vongohren** [comment]
Seems like the PR has gotten one approved review, what might the timeline for this be?

**Comment by c2thorn** [comment]
@vongohren ETA `v3.62`, scheduled for March 29th. See https://github.com/hashicorp/terraform-provider-google/pull/8632#issuecomment-801330687

**Comment by vongohren** [comment]
@c2thorn great, thanks for quick feedback! And nice update on the comment

**Comment by c2thorn** [comment]
Complications in the change have pushed the deadline out, but this is actively being worked on.

**Comment by hazcod** [comment]
@c2thorn : any idea what the release schedule for `google-beta` is so we can beta test?

**Comment by c2thorn** [comment]
@hazcod - Releases are scheduled for Mondays. If you are interested in testing the feature right now, the commit https://github.com/hashicorp/terraform-provider-google-beta/pull/3101/commits/dd964024d8a307d87a66052b3e94d60a79de71e9 can be built following the steps at https://github.com/hashicorp/terraform-provider-google#building-the-provider
