### ISSUE TITLE
"disk" block documentation fails to mention that you can leave the source_image parameter set to a blank value

### ISSUE THREAD

**Issue by gswallow** [hashicorp/terraform-provider-google#8577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Doesn't matter.

### Affected Resource(s)

Documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template

### Terraform Configuration Files

See the example below:
```
resource "google_compute_instance_template" "sftp" {
  name_prefix = "${local.name_prefix}-sftp-tpl-"
  description = "This template is used to set up SFTP server instances"

  instance_description = "SFTP server instance"
  machine_type         = var.machine_type

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
  }

  disk {
    source_image = data.google_compute_image.selected.self_link
    disk_type    = var.boot_disk_type
    disk_size_gb = var.boot_disk_size_gb
    auto_delete  = var.auto_delete_boot_disk
    boot         = true
  }

  disk {
    boot         = false
    source_image = ""
    disk_type    = var.data_disk_type
    disk_size_gb = var.data_disk_size
    auto_delete  = var.auto_delete_data_disk
  }
  ```

### Actual Behavior

The documentation does not state that you can leave the source_image field to blank (""), though the actual Google documentation states you can: https://cloud.google.com/compute/docs/instance-templates/create-instance-templates#based-on-existing-instance

As a result, I was trying to create a google_compute_disk (or google_compute_regional_disk) and map it to each machine, which works, but is too complicated.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
If you don't want a persistent disk, you can set the `disk_type = local-ssd` and not use the source_image attribute.

Provider doc - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#source_image 

API doc - https://cloud.google.com/compute/docs/instance-templates/create-instance-templates#based-on-existing-instance

**Comment by gswallow** [comment]
No, that's not what I said.  The API doc says:

```
gcloud compute instance-templates create [INSTANCE_TEMPLATE_NAME] \
    --source-instance=[SOURCE_INSTANCE] \
    --source-instance-zone=[SOURCE_INSTANCE_ZONE] \
    [--configure-disk= \
        device-name=[SOURCE_DISK], \
        instantiate-from=[INSTANTIATE_FROM], \
        auto-delete=[AUTO_DELETE]]
        
[INSTANTIATE_FROM] specifies whether to include the disk and which image to use. Valid values depend on the type of disk:
    ...
    blank (valid only for non-boot persistent disks and local SSDs). If specified, then, when the template is used to create a new instance, the disk is created unformatted. You must format and mount the disk in a startup script before you can use it in a scalable setup.
```

Because of that particular line in the API doc, I tried using `source-image = ""` when attaching a second, persistent disk (non-boot), and it worked.  The Terraform documentation is misleading.  Please re-open this case.
