### ISSUE TITLE
Cannot update BigQuery Materialized view

### ISSUE THREAD

**Issue by gecko655** [hashicorp/terraform-provider-google#8579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
$ terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.52.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Affected Resource(s)

* `google_bigquery_table`

### Terraform Configuration Files

- Initial configuration 
```tf
resource "google_bigquery_table" "dm_monthly_first_logins" {
  dataset_id = "dest_dataset"
  table_id = "dest_table"
  materialized_view {
    enable_refresh = true
    query = <<-EOT
SELECT
  user_id,
  DATE_TRUNC(date, MONTH) momth,
  min(date) monthly_first_login_date,
FROM src_project.src_dataset.src_table
GROUP BY 1,2
    EOT
  }
}
```

- Diff to reproduce
```diff
resource "google_bigquery_table" "dm_monthly_first_logins" {
  dataset_id = "dest_dataset"
  table_id = "dest_table"
  materialized_view {
    enable_refresh = true
    query = <<-EOT
SELECT
  user_id,
- DATE_TRUNC(date, MONTH) momth,
+ DATE_TRUNC(date, MONTH) month,
  min(date) monthly_first_login_date,
FROM src_project.src_dataset.src_table
GROUP BY 1,2
    EOT
  }
}
```
### Debug Output

https://gist.github.com/gecko655/1eaab4eca6c8351dabc1b65de7e47db4

### Expected Behavior

After `terraform apply`, the BigQuery materialized view `dm_monthly_first_logins` is updated so that the typo `momth` is fixed as `month`.
### Actual Behavior

The `terraform apply` command fails with the following error. (See the debug log file for details)
> Error: googleapi: Error 400: Schema update for materialized views is not supported., invalid

### Steps to Reproduce

1. `terraform apply` with the "initial configuration"
2. Apply the diff
3. `terraform apply` again

### References

* This issue is the reopen of #8310
  - #8310 is currently closed due to no-response.

* Support for materialized views were recently added with #7080 to address #6779.

**Comment by tmshn** [comment]
I wonder if Google allow us to update MVs query in-place; if not, we always need to recreate the resource to update query, and the fix should be as easy as just add `ForceNew: true` to the `query` field.

**Comment by tmshn** [comment]
I've tried using [API explorer](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch) and the result is NO.
Note that I rewrite the query so that the schema won't change (e.g.: `min()` → `max()`).

```json
{
  "error": {
    "code": 400,
    "message": "Updating materialized view query is not yet supported.",
    "errors": [
      {
        "message": "Updating materialized view query is not yet supported.",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by gecko655** [comment]
Thanks a lot! 👍
