### ISSUE TITLE
google_compute_region_url_map tries to be smart and rewrites default_service ids to regional ones

### ISSUE THREAD

**Issue by ahmadnassri** [hashicorp/terraform-provider-google#8586]
the `parseRegionalFieldValue` [method](https://github.com/hashicorp/terraform-provider-google/blob/45d889473c9b304c254abbaa49f0c64f633ae806/google/field_helpers.go#L312) is parsing any value passed to it and constructing the url to a regional one.

this means when attempting to use a global url for a backend service, it gets rewritten to a regional one ... 

the google api docs indicate that global services are fine to mix with regional url maps: https://cloud.google.com/compute/docs/reference/rest/beta/regionUrlMaps/insert

also, I cannot understand why the client here is going through all the extra work of parsing the passed values then making it's own assertions on what should be sent to the API????

should be relying on the API itself to determine correctness and proper formats ...

**Comment by edwardmedia** [comment]
@ahmadnassri does `google_compute_url_map` help?

**Comment by ahmadnassri** [comment]
after hours of debugging, and trying multiple different combinations of resource types, we ended up using a specific mix of global and regional resources that worked ... yet the actually created GCP entities are all regional!

I do not understand the provider client need to reconstruct and reconstruct resource ids and forcing behaviour instead of using the passed in IDs...

after digging more into the provider source, it seems it does this for everything!

this is very confusing and unwanted behavior!

if I pass in a global resource ID, then I want that specific resource ID sent to the GCP API! not an invisible rewrite to a regional one?!

**Comment by edwardmedia** [comment]
@ahmadnassri is this still an issue or anything left we can assist?

**Comment by ahmadnassri** [comment]
@edwardmedia yes, this is an issue, the provider logic is wrong.... as I have explained ... twice.

**Comment by edwardmedia** [comment]
@ahmadnassri can you share your config code and the debug log?

**Comment by ahmadnassri** [comment]
I cannot easily share the code samples, but the resources in question are: `url_map` and `network_endpoint_group`, currently the following combination works:

`google_compute_url_map` 
`google_compute_region_network_endpoint_group`

**Comment by edwardmedia** [comment]
@ahmadnassri are you able to create a test config so I can repro the issue? It could be a bug. It also could be a feature that has not been implemented, or  Without the specific details, it is hard for me to follow.

In term of `google_compute_region_network_endpoint_group `, are you aware of the existence of `google_compute_global_network_endpoint_group` which handles the GLOBAL business?

**Comment by ahmadnassri** [comment]
can you address why the provider parses and rewrites regional IDs into global and vice versa?

why isn't the provider passing the IDs as given by user input?

**Comment by ahmadnassri** [comment]
I can't provide you with any config at the moment and I don't have time to mock one up ...

you've evaded / ignored the question which is VERY clear ... I've even linked to the source code where it is 

the provider code is intentionally parsing location id url strings, extracts the region code and replaces global / region values with internal logic, rather than passing the values as is to the GCP API.

this make little to no sense, why would the provider which acts as a client to the GCP API have any role in overriding user input?

and again, I don't need to provide examples of the Terraform config, I'm linking directly to the code where this occurs here: https://github.com/hashicorp/terraform-provider-google/blob/45d889473c9b304c254abbaa49f0c64f633ae806/google/field_helpers.go#L312

if you don't wish to answer, that's fine ... but please stop asking me for "examples" because it's irrelevant to the question asked.

**Comment by edwardmedia** [comment]
@ahmadnassri I am here to help users to use the provider. If users face issues like an expected behavior is not met by design ( that a bug) or a feature is not supported (that is an enhancement), we will try to address them. Because you filed a bug, to better understand the issue, I'd like to know the use case: what is the expected behavior, and what is the actual result.  Fair?

I don't understand what you mean [global services are fine to mix with regional url maps](https://github.com/hashicorp/terraform-provider-google/issues/8586#issue-819537551). 

To match the URL you provided for **regional** one, are you aware of below API?
https://cloud.google.com/compute/docs/reference/rest/beta/urlMaps/insert

As I mentioned earlier, in general rule, **google_compute_region_XXXXX** take care of **regional** resources, while **google_compute_global_XXXXX** are for **global**. Does this make sense?
