### ISSUE TITLE
google_sql_database_instance postgres point_in_time_recovery_enabled should default to true

### ISSUE THREAD

**Issue by optimadba** [hashicorp/terraform-provider-google#8598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The GUI for CloudSQL Postgres has default PITR enabled when enabling backups. Terraform provider doesn't follow this default and enforces to add an extra line of code.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by slevenick** [comment]
Unfortunately I don't think we want to do this. If we add a feature with a true default in the provider it will retroactively enable this for all users of a new version of the provider, which is definitely not something we want to do.

I think keeping this feature as opt-in rather than opt-out is the best way to go
