### ISSUE TITLE
google_cloud_run_service should set client.knative.dev/user-image

### ISSUE THREAD

**Issue by fhut** [hashicorp/terraform-provider-google#8599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform version 0.14.7, terraform-provider-google version 3.58.0.

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf

resource "google_cloud_run_service" "this" {
  name     = "my-service"
  location = local.region

  autogenerate_revision_name = true

  metadata {
    annotations = {
      # setting the below three annotations manually should not be necessary
      "client.knative.dev/user-image" = local.container_image
      "run.googleapis.com/client-name" = "terraform"
      "run.googleapis.com/client-version" = "terraform 0.14.7 with terraform-provider-google 3.58.0"
    }
  }

  template {
    metadata {
      annotations = {
      # setting the below three annotations manually should not be necessary
        "client.knative.dev/user-image" = local.container_image
        "run.googleapis.com/client-name" = "terraform"
        "run.googleapis.com/client-version" = "terraform 0.14.7 with terraform-provider-google 3.58.0"

        "autoscaling.knative.dev/maxScale" = "1000"
      }
    }
    spec {

      service_account_name = "${local.project_id}@appspot.gserviceaccount.com"
      containers {
        image = local.container_image
        resources {
          limits = {
            memory = "512Mi"
            cpu    = "1000m"
          }
        }
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### Expected Behavior

The terraform provider should set the annotations "client.knative.dev/user-image", "run.googleapis.com/client-name", and "run.googleapis.com/client-version" analogously to gcloud cli.

### Actual Behavior

If the cloud run service was deployed the first time with gcloud cli and is then subsequently imported into terraform, the values for the above-mentioned annotations are never modified by terraform. This is dangerous, because the button 'edit and deploy new revision' in the google cloud console will then not work as expected: The newly created revision will use the container image taken from the "client.knative.dev/user-image" annotation, and not take the container image version that was actually previously set.

### Steps to Reproduce

Create a google cloud run service using gcloud cli. Import the service into terraform. Deploy a new version of the container image. Observe that the annotations are not set. Use the button 'edit and deploy new revision' in the google cloud console. Observe that it will lead to a re-deployment of the old version.

### References

https://github.com/knative/client/blob/v0.19.0/conventions/client.md contains an explanation of the purpose of the "client.knative.dev/user-image" annotation.

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/8380

**Comment by fhut** [comment]
Hi @edwardmedia . We are also obverving the issue with the permanent diff in the annotation block, but it is a separate issue that I did not intend to touch here.

The annotation "client.knative.dev/user-image" is a separate issue; terraform is a high-level tool and it should behave as the documentation on knative convention describes (https://github.com/knative/client/blob/v0.19.0/conventions/client.md), just like `gcloud`, and thus set the annotation "client.knative.dev/user-image" to the image that was last deployed.

**Comment by rileykarson** [comment]
As implemented today at least, Terraform doesn't manage annotations inside of Cloud Run for itself. I'd have considered Cloud Run (the managed service variant represented by the `google_cloud_run_service` resource) to be the knative client and not the tool that configures the Cloud Run API (gcloud, Console, Terraform, etc). It seems that take is wrong, though, and we'll want to consider amending Terraform's behaviour here.

I believe that doing so is closer to an enhancement than a bugfix, so relabelling as such.

---

Looking at your config, isn't what's happening expected? You've specified a value for the `user-image` annotation so Terraform is ensuring that value is what's set on the API. If you cleared it Terraforms should clear the annotation, and if you updated it, Terraform would do the same.

**Comment by fhut** [comment]
I agree that the proposed change can be appropriately classified as an enhancement.

Users should not have to think about setting the annotations in their config, because terraform knows the only correct value, and if the user does not set the annotation, they will be unpleasantly surprised (as we were) as soon as they use another api client (gcloud, cloud-console), because it will rely on the user-image annotation.

**Comment by rileykarson** [comment]
As far as we're aware, the user-image annotation is only managed by certain clients like `gcloud` and doesn't actually have any impact on the service itself. There's no action to take here on that field.

We can bring the client annotations under management, though. Filed https://github.com/hashicorp/terraform-provider-google/issues/8814 for that.
