### ISSUE TITLE
Unable to deploy gcp data-catalog with user credentials

### ISSUE THREAD

**Issue by dsbrambila** [hashicorp/terraform-provider-google#8600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform version 0.14.0, terraform-provider-google version 3.58.0. 

### Affected Resource(s)

* google_data_catalog_entry_group

### Terraform Configuration Files

```tf
resource "google_data_catalog_entry_group" "entry-group" {
  entry_group_id = "my_id"
}
```

### Expected Behavior

I should be able to deploy the service using my user credentials and not only service-accounts.

### Actual Behavior

```
Error: Error when reading or editing DataCatalogEntryGroup "projects/xx/locations/region/entryGroups/entry-group": googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the datacatalog.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/
```

### Steps to Reproduce

1. `terraform apply`

### References
https://stackoverflow.com/questions/56823383/your-application-has-authenticated-using-end-user-credentials-from-the-google-cl shows how to circumvent the issue by using a service account instead. This is not an acceptable solution since I would rather avoid storing my credentials.

**Comment by edwardmedia** [comment]
@dsbrambila [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials) is what the Terraform Provider Google recommends. If you can't find a way that works for you, you may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=&template=enhancement.md) then it can be added into backlog. Does this make sense?

**Comment by dsbrambila** [comment]
I would rather not store account credentials in my personal machine. That's why I think it is important to enable access via user credentials instead.

**Comment by upodroid** [comment]
Have a look at the warning on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_access_level

A small number of APIs don't support User Credentials and put a similar notice on those resources.

**Comment by edwardmedia** [comment]
@dsbrambila go ahead to file an enhancement if you see a need and it is feasible. Closing this issue then
