### ISSUE TITLE
Add support for streaming DICOM export

### ISSUE THREAD

**Issue by xingao267** [hashicorp/terraform-provider-google#8609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Healthcare API has released a new feature in beta to streaming DICOM metadata to BigQuery. https://cloud.google.com/healthcare/docs/how-tos/dicom-bigquery-streaming. Would like to add it to Terraform provider so this feature can be used with Terraform.

The change should be similar to https://github.com/GoogleCloudPlatform/magic-modules/pull/3611/files

### New or Affected Resource(s)

* google_healthcare_dicom_store

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by manjunathbellad** [comment]
Hello Team,

Is it possible to expedite this feature. We need it for a prod release by month end .

**Comment by xingao267** [comment]
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8958 which is fixed.
