### ISSUE TITLE
google_compute_network datasource missing ID output

### ISSUE THREAD

**Issue by dkpat12** [hashicorp/terraform-provider-google#8613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The data source for `google_compute_network` seems to be missing the ID attribute which is required by some resources. It could be that the documentation for the data is incorrect, but the resource version does contain the ID attribute. Can this please be added to bring parity between the two resources? 

### New or Affected Resource(s)

* data.google_compute_network
* resource.google_compute_network

### Potential Terraform Configuration

```tf
data "google_compute_network" "default" {
  name = "default"
}

output "default_net" {
  value = data.google_compute_network.default.id
}
```

### References

* #5623 May have intended to fix this but in the PR it was instead entirely removed.
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network#id

**Comment by venkykuberan** [comment]
The `id` exists and working as expected. Just executed your config to get the below output

```
data.google_compute_network.default: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

default_net = projects/test-project1-xxxx/global/networks/default
```

**Comment by dkpat12** [comment]
Oh, that's great! In that case this issue needs to address the documentation not reporting that
