### ISSUE TITLE
google_bigquery_data_transfer_config not working with serviceAccountShortTermTokenMinter

### ISSUE THREAD

**Issue by hragbalian** [hashicorp/terraform-provider-google#8624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/google v3.58.0
+ provider registry.terraform.io/hashicorp/google-beta v3.58.0
```

### Affected Resource(s)

```
google_bigquery_data_transfer_config
```

### Terraform Configuration Files

```tf
resource "google_project_iam_member" "permissions" {
  project = var.project
  role   = "roles/iam.serviceAccountShortTermTokenMinter"
  member = "serviceAccount:service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com"
}


resource "google_bigquery_data_transfer_config" "query_config" {
  depends_on = [google_project_iam_member.permissions]

  project               = var.project
  # service_account_name  = "service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com"

  display_name           = "results"
  location               = "US"
  data_source_id         = "amazon_s3"
  schedule               = "every 24 hours"
  destination_dataset_id = module.bigquery.bigquery_dataset.dataset_id

  params = {

    destination_table_name_template = "results"
    # write_disposition               = "WRITE_APPEND"
    data_path                       = "s3:/<BUCKET>/file.csv"
    access_key_id                   = data.google_secret_manager_secret_version.aws_livescoring_access_key_id.secret_data
    file_format                     = "CSV"
    skip_leading_rows               = 1
    # query                           = "SELECT name FROM tabl WHERE x = 'y'"
  }

  sensitive_params {
    secret_access_key = data.google_secret_manager_secret_version.aws_livescoring_secret_access_key.secret_data
  }

  timeouts {
    create = "10m"
  }
}
```

### Panic Output

```
Error: Error creating Config: googleapi: Error 400: P4 service account needs iam.serviceAccounts.getAccessToken permission. Running the following command may resolve this error: gcloud iam service-accounts add-iam-policy-binding <NAME>@<PROJECT>.iam.gserviceaccount.com --member='serviceAccount:service-<ACCOUNT>@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' --role='roles/iam.serviceAccountTokenCreator'
```

### Expected Behavior

Create the Data Transfer Service

### Actual Behavior

Won't produce the Data Transfer Service

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

My issue is identical to the one reported in the referenced issue.  The resolution in that ticket appears to be to use the ```service_account_name``` parameter, but when I try to do so, I get this error: 

```
Error: Error creating Config: googleapi: Error 400: Request contains an invalid argument.
```

Even though I'm using (what I think) is an provider version that should have this parameter enabled. 

### References

* #4449

**Comment by edwardmedia** [comment]
@hragbalian to make BQ Data Transfer Config work properly, you need to have below conditions:

- Your service account needs owner permissions on the target dataset. This is because it needs to be able to grant write permissions to an internal BQ-DTS service account.
- A service account service-PROJECT_NUMBER@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com needs permissions to create access tokens on behalf of your service account.

In your case, it looks like it lacks the 2nd condition. 

You may want to look at the resource [google_service_account_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#google_service_account_iam_member) to see if that helps. Let me know how it works.

**Comment by hragbalian** [comment]
Thanks @edwardmedia, for the reply.  I'm probably not understanding something, but isn't google_project_iam_member in my example supposed to address the second bullet? 

In any case, I can't seem to bind any permission to that service account that would get this to work.  To be honest, I'm actually not even sure where the service account **serviceAccount:service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com**
is getting generated.  I don't see it in anywhere in the console, and it's nowhere in my TF code.  I'm should be able to see this service account in the console, at the very least, right?

**Comment by edwardmedia** [comment]
@hragbalian the command suggested in the error message (below) you received has three inputs: _service-account_, _member_ and _role_. Does `google_project_iam_member` support that? 

> gcloud iam service-accounts add-iam-policy-binding <NAME>@<PROJECT>.iam.gserviceaccount.com --member='serviceAccount:service-<ACCOUNT>@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' --role='roles/iam.serviceAccountTokenCreator'

Regarding serviceAccount:service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com, it is an internal account and created when you enable one of the BigQuery APIs. Do you see if it is in the response if you make below call?

```
POST /v1/projects/your-project:getIamPolicy
Host: cloudresourcemanager.googleapis.com
{
 "options": {
  "requestedPolicyVersion": 3
 }
}
```

**Comment by hragbalian** [comment]
Ah! @edwardmedia, the point about how I needed a permissions resource with the three input parameters was really helpful.  The [TF documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config) on `google_bigquery_data_transfer_config` uses the `google_project_iam_member` permissions resource, which only has the parameters for role and member but not for service account.  The service account that I'm using is created in a master 'project factory' project, not in the project that I'm trying to provision the DTS.  I guess `google_project_iam_member` is looking for the service account in its own project, and I erroneously assumed it would work with my case.  In any case, if use `google_service_account_iam_binding` it works: 

```
resource "google_service_account_iam_binding" "permissions" {
  service_account_id = "projects/<project-factory-project>/serviceAccounts/${var.service_account_id}"
  role               = "roles/iam.serviceAccountShortTermTokenMinter"

  members = [
    "serviceAccount:service-${data.google_project.project.number}@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com"
  ]
}
```

and add that resource to the `depends` in the DTS resource

```
  depends_on = [google_service_account_iam_binding.permissions]
```

Note that I tried with `google_service_account_iam_member` and it was unsuccessful.  

Thanks!
