### ISSUE TITLE
Data source google_cloudiot_default_service_account is missing

### ISSUE THREAD

**Issue by leigh-johnson** [hashicorp/terraform-provider-google#8625]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The default service account for GCP Cloud IoT Core (cloudiot API v1) cannot be referenced as a data source.

```
Error: Invalid data source

  on data.tf line 1, in data "google_cloudiot_default_service_account" "default":
   1: data "google_cloudiot_default_service_account" "default" {

The provider provider.google does not support data source
"google_cloudiot_default_service_account".
```

This service account is automatically created when the Cloudiot API is enabled, with an email ending in `@gcp-sa-cloudiot.iam.gserviceaccount.com`. 

Is it possible to provide a data lookup for convenience here? Similar to:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/storage_project_service_account
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/bigquery_default_service_account
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/storage_transfer_project_service_account
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/app_engine_default_service_account
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account

### New or Affected Resource(s)

* google_cloudiot_default_service_account

### Potential Terraform Configuration

```tf
# data.tf

# lookup default compute service account (supported, thank you!)
data "google_compute_default_service_account" "default" {

}

# lookup default cloudiot service account (functionality missing)
data "google_cloudiot_default_service_account" "default" {
}
```

**Comment by rileykarson** [comment]
Maybe possible with https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity?

**Comment by edwardmedia** [comment]
@rileykarson yes, it works

@leigh-johnson Here is the way you can try by adding `google_project_service_identity` like below

```tf
resource "google_project_service_identity" "iot" {
  provider = google-beta
  project = "myproject"
  service = "cloudiot.googleapis.com"
}
```
Then you are able to retrieve the default email from above resource. Below is the result from `tf show`
```
# google_project_service_identity.iot:
resource "google_project_service_identity" "iot" {
    email   = "service-573164xxxxxx@gcp-sa-cloudiot.iam.gserviceaccount.com"
    id      = "projects/myproject/services/cloudiot.googleapis.com"
    service = "cloudiot.googleapis.com"
}
```

**Comment by leigh-johnson** [comment]
Thank you @edwardmedia for posting that example and @rileykarson for the docs link! I didn't know the `google-beta` provider existed.
