### ISSUE TITLE
Unable to get google providers for M1 Mac "darwin_arm64"

### ISSUE THREAD

**Issue by ramimmadi** [hashicorp/terraform-provider-google#8629]
Hi ,

I am trying  to setup terraform in my Mac M1 and Its been so difficult as I am getting multiple errors like 

> Provider registry.terraform.io/hashicorp/google v3.58.0 does not have a
> package available for your current platform, darwin_arm64.

My terraform version: 

> v0.14.6

I have tried to install the provider by following steps mentioned in Readme.md of 
> hashicorp/terraform-provider-google

Go Version:

> go version go1.16rc1 darwin/arm64

However nothing works at the moment. I guess it is because of Mac M1 using a different chip but It would be great If you can provide some kind of workaround for this issue.

**Comment by melinath** [comment]
Related issue upstream: https://github.com/hashicorp/terraform/issues/27257

There is some discussion in that thread about how to build providers locally for your architecture. However, it seems like we should also make sure there are builds available for darwin_arm64.

**Comment by megan07** [comment]
I believe this will just be a matter of us updating to Go `1.16.0`, I think the release pipeline is ready for this.

**Comment by hazcod** [comment]
Seems like the PR is ready for merging, yay!

**Comment by bobrik** [comment]
The latest release still doesn't have package for `darwin_arm64`, is something else missing?

**Comment by melinath** [comment]
@bobrik It looks like the PR was just merged, so it should be included when the 3.63.0 release is cut.

**Comment by bobrik** [comment]
Github confused me by showing the date of the release (which happened after merge), not the date of the commit.

![image](https://user-images.githubusercontent.com/89186/112553125-2a9a8780-8d81-11eb-9831-3086984cb5e7.png)
