### ISSUE TITLE
Add prevent_downsize disk attribute

### ISSUE THREAD

**Issue by przsab** [hashicorp/terraform-provider-google#8642]
### Description

Details and scope of this enhancement has been already explained in issue https://github.com/hashicorp/terraform-provider-google/issues/8597

### New or Affected Resource(s)

* google_compute_disk
* google_compute_region_disk

### Potential Terraform Configuration

```tf
resource "google_compute_disk" "disk1" {
  name   = "disk1"
  type   = "pd-ssd"
  size   = 512
  prevent_downsize = true
}
```

### References

*  https://github.com/hashicorp/terraform-provider-google/issues/8597
* b/182371718
*

**Comment by rileykarson** [comment]
After a discussion about the alternatives available to add `prevent_downsize`, we decided not to move forward with this feature request.
