### ISSUE TITLE
Flakey test: TestAccSqlDatabaseInstance_backupUpdate

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8658]
### Affected Resource(s)

* google_sql_database_instance

TestAccSqlDatabaseInstance_backupUpdate fails for a variety of different reasons:

- [unknown SQL errors](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/171617?buildTab=tests&expandedTest=2829843264706257858)
- [timeouts](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/174870?buildTab=tests&expandedTest=2829843264706257858)
- ["invalid backup run"](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/171722?buildTab=tests&expandedTest=2829843264706257858)

We should investigate making this test more reliable.

**Comment by mitj04** [comment]
TestAccSqlDatabaseInstance_backupUpdate

[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=2829843264706257858&tab=testDetails) - 67% of success rate (29 failures)

[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=2829843264706257858&tab=testDetails) - 68.5% of success rate (28 failures)

**Comment by mitj04** [comment]
b/261373713

**Comment by roaks3** [comment]
The timeouts appear to have been resolved, and I'm not seeing any of the other failures listed here. If there is instability remaining with the test, we can capture those failures with separate issues dedicated to the failure observed.
