### ISSUE TITLE
Why is google_artifact_registry_repository only available in beta?

### ISSUE THREAD

**Issue by pandanos** [hashicorp/terraform-provider-google#8679]
Artifact registry is GA in GCP since Nov 2020. 
https://cloud.google.com/artifact-registry/docs/release-notes

Why is it still in beta in terraform? When can expect it to be not in beta in Terraform? :)

**Comment by edwardmedia** [comment]
@pandanos yes it is GA from api now. Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=&template=enhancement.md) asking for a GA so it will be added the backlog

https://cloud.google.com/artifact-registry/docs/release-notes#November_16_2020
