### ISSUE TITLE
VPC Access Connector - support specifying network by id

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#8683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, you have to provide the name of the network for a vpc_access_connector. 
This is rather unintuitive when the `google_compute_network` resource id returns the fully qualified link. 
I think it would be better served to have the option to provide the name (as is) or fully qualified path. 

### New or Affected Resource(s)

* google_vpc_access_connector

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_network" "vpc_network" {
  name = "vpc-network"
  mtu  = 1500
}

resource "google_vpc_access_connector" "connector" {
  name               = "vpc-con"
  ip_cidr_range      = "10.8.0.0/28"
  network            = google_compute_network.vpc_network.id
}
```

### References

n/a

**Comment by drandell** [comment]
Hi @rileykarson do I close this now? :)

**Comment by rileykarson** [comment]
Oh, yep! https://github.com/hashicorp/terraform-provider-google/pull/10988 makes the change.
