### ISSUE TITLE
How to install the extensions on Google AI Notebook instace

### ISSUE THREAD

**Issue by RahulVadisetty91** [hashicorp/terraform-provider-google#8688]
I want to install the extension on ai notebook instance using terraform.
please have look on attached image.
![image](https://user-images.githubusercontent.com/24702792/111141790-f2898c80-85a9-11eb-901e-f47f4ace9b10.png)

**Comment by edwardmedia** [comment]
@RahulVadisetty91 is it not supported by the Terraform provider yet. I have checked `gcloud beta notebooks instances create`, I can't find that either. Let me know if you see differently.

**Comment by edwardmedia** [comment]
@RahulVadisetty91 If you see any other places (like gcloud, api) where `extensions` is supported, please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=&template=enhancement.md)  so it will be added into the backlog for deployment.
