### ISSUE TITLE
Support for pub/sub invoked builds to google_cloudbuild_trigger

### ISSUE THREAD

**Issue by bruno-morel** [hashicorp/terraform-provider-google#8692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is an adjacent feature to the manual trigger (https://github.com/hashicorp/terraform-provider-google/issues/8374)
You are able to create triggers in GCP console that are started on pub/sub events.
https://cloud.google.com/build/docs/automating-builds/create-pubsub-triggers#gcloud

Same would be nice to have supported with google_cloudbuild_trigger

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

google_cloudbuild_trigger

```tf
I believe it should be another Object inside the trigger properties that would be mutually exclusive to the other Trigger objects
```

### References

https://github.com/hashicorp/terraform-provider-google/issues/8374

**Comment by maqiuyujoyce** [comment]
I believe the Pub/Sub trigger is supported by the `pubsubConfig` field in the BuildTrigger defined [here](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers#PubsubConfig).

**Comment by tonybenchsci** [comment]
Any updates on when this might be supported?

**Comment by javimoya** [comment]
Any updates on when this might be supported?

**Comment by al-dann** [comment]
and we need to take into account that the repository can be GitHub as well as Google Cloud Repository

**Comment by iamsumit** [comment]
I have raise a pull request to add the support. Can anyone please review this?
