### ISSUE TITLE
type miss

### ISSUE THREAD

**Issue by kosukekurimoto** [hashicorp/terraform-provider-google#8707]
https://github.com/hashicorp/terraform-provider-google/blob/919e9aef4d253081219a3f032246e0506904323e/google/resource_compute_interconnect_attachment.go#L148

NG
"mtu": {
Type:     schema.TypeString,  ← Must be typeInt.

**Comment by kosukekurimoto** [comment]
This issue occurs from v3.6.0.

**Comment by ScottSuarez** [comment]
We reverted the type change due to breaking existing users terraform state but have fixed the bevaior for this field so mtu should work regardless of your input.

https://github.com/GoogleCloudPlatform/magic-modules/pull/4643
