### ISSUE TITLE
google_storage_bucket 'project' argument required

### ISSUE THREAD

**Issue by jamesmealing** [hashicorp/terraform-provider-google#8715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.5
provider registry.terraform.io/hashicorp/google v3.60.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/google"
      version = "3.60.0"
    }
  }
}

provider "google" {
  project = "my-test-project"
  region  = "europe-west1"
  zone    = "europe-west1-b"
}

resource "google_storage_bucket" "example" {
  name          = "my-test-bucket"
  location      = "europe-west1"
}
```

### Debug Output
https://gist.github.com/jamesmealing/51dd169685051cee266a315eb8f69988

### Expected Behavior

According to the resource [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#argument-reference) the 'project' argument is optional and will use the provider project if it is not provided. 

### Actual Behavior

When running a 'terraform apply' it errors with the following: 'Error: project: required field is not set' - Despite the project being set in the provider.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@jamesmealing  have you tried by adding the `provider` in the resource? 

```tf
resource "google_storage_bucket" "example" {
  provider     = "google"
  name          = "my-test-bucket"
  location      = "europe-west1"
}
```

**Comment by jamesmealing** [comment]
@edwardmedia I have, and this works, however, if this is by design, then the documentation needs updating to mark this argument as 'Required' - Currently it is 'Optional'.

**Comment by jamesmealing** [comment]
@edwardmedia I have, and this works, however, if this is by design, then the documentation needs updating to mark either the 'provider' argument or the 'project' argument as 'Required' as currently, 'project' is referenced as being 'Optional'.

**Comment by edwardmedia** [comment]
@jamesmealing  you have to provide `project` to the resources one way or another. It is optional if you have already set the [default](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project) value for it. Closing the issue as this is the behavior across the board for all resources.

**Comment by jamesmealing** [comment]
I agree, but ```project``` is already defined at the provider level, therefore, why is it necessary to either specify it again or refer to the provider specifically in this resource?

The documentation for the ```project``` argument states that - "_If it is not provided, the provider project is used_" - But this is not the case as the provider project is defined but is not being used.

Based on the current behaviour, this should read - "_If it is not provided, ```provider``` must be specified instead_".

**Comment by jamesmealing** [comment]
Further, having just read more about the ```provider``` [resource](https://www.terraform.io/docs/language/meta-arguments/resource-provider.html), I am even more sure that this is not the intended behaviour:

"_By default, Terraform interprets the initial word in the resource type name (separated by underscores) as the local name of a provider, and uses that provider's default configuration. For example, the resource type google_compute_instance is associated automatically with the default configuration for the provider named google._"

In this case, the ```google_storage_bucket``` resource isn't automatically using the default configuration with regards to ```project```, hence either ```provider``` or ```project``` must be explicitly defined.

**Comment by rileykarson** [comment]
Per [@edwardmedia's comment](https://github.com/hashicorp/terraform-provider-google/issues/8760#issuecomment-805952269): I would be surprised if that provider definition affected anything, I'd assume it would cause the AWS provider to not work but do nothing to the Google one. It's probably worth verifying, though.

Per https://github.com/hashicorp/terraform-provider-google/issues/8715#issuecomment-802919039: The default configuration for the `google` provider will be used! At least, it is for me. I'm using `0.13.4` and not `0.14.5`, admittedly.

---

If the following configuration doesn't work in isolation, there's certainly a provider bug:

```
provider "google" {
  project = "my-test-project"
  region  = "europe-west1"
  zone    = "europe-west1-b"
}

resource "google_storage_bucket" "example" {
  name          = "my-test-bucket"
  location      = "europe-west1"
}
```

I don't receive the same error, though (subbing in my project):

```
rileykarson@rileykarson-macbookpro ~/terraform-test/test-input/gcs-project
$ GOOGLE_PROJECT= terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_storage_bucket.example will be created
  + resource "google_storage_bucket" "example" {
      + bucket_policy_only          = (known after apply)
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "EUROPE-WEST1"
      + name                        = "my-test-bucket"
      + project                     = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_storage_bucket.example: Creating...

Error: googleapi: Error 409: Sorry, that name is not available. Please try a different one., conflict

  on main.tf line 7, in resource "google_storage_bucket" "example":
   7: resource "google_storage_bucket" "example" {
```

**Comment by edwardmedia** [comment]
@jamesmealing this issue in your case is below name of the provider (**aws**). Let me know what you see if you change it to **google**. (I left comments in #8760 as well)

```tf
terraform {
  required_providers {
    aws = {                <--------- aws? What do you see if you change it to google?
      source  = "hashicorp/google"
      version = "3.60.0"
    }
  }
}
```

**Comment by jamesmealing** [comment]
@edwardmedia is spot on! 👌  What a silly mistake, sorry chaps! 🙈 

This does make total sense as well, for precisely the reason I thought it wasn't working:

"_By default, Terraform interprets the initial word in the resource type name (separated by underscores) as the local name of a provider, and uses that provider's default configuration._"

Terraform was, quite rightly, looking for a provider named `google` as that is the initial word of the `google_storage_bucket ` resource, however, because my `provider` was inadvertently called `aws`, it obviously couldn't find it! 🤦‍♂️ 

Thanks, both, for your help. 🙂
