### ISSUE TITLE
Howto contribute to website

### ISSUE THREAD

**Issue by tpoindessous** [hashicorp/terraform-provider-google#8718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hi ! It would be nice to have a howto for contributing to the website. Now, with magicModules, it's getting quite difficult to contribute to the website. For example, I would like to propose a change for the description of google_compute_region_ssl_certificate but in MagicModules repo, I can't find where this is set :( 

### New or Affected Resource(s)

* google_compute_region_ssl_certificate

### References

thanks !

**Comment by venkykuberan** [comment]
@tpoindessous you can create a PR against the provider repo, we will upstream the change to magic modules. Hope that helps.
