### ISSUE TITLE
Cloud Identity Group Data Sources don't work with Application Default Credentials

### ISSUE THREAD

**Issue by johnae** [hashicorp/terraform-provider-google#8720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.8
+ provider registry.terraform.io/carlpett/sops v0.6.0
+ provider registry.terraform.io/davidsbond/tailscale v0.0.1
+ provider registry.terraform.io/hashicorp/google v3.60.0
+ provider registry.terraform.io/hashicorp/google-beta v3.60.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* data google_cloud_identity_group_*

### Terraform Configuration Files

```tf

provider "google" {
  project               = "example-project-1234"
  user_project_override = true
  billing_project       = local.project_id
}

data "google_cloud_identity_groups" "groups" {
  parent = "customers/A000abc11"
}
```

### Panic Output

```
$ terraform plan

Error: Error when reading or editing CloudIdentityGroups "": googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the cloudidentity.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/., accessNotConfigured

  on main.tf line 58, in data "google_cloud_identity_groups" "groups":
  58: data "google_cloud_identity_groups" "groups" {
```

### Expected Behavior

I am able to run plan as expected when provider is configured with `user_project_override` and `billing_project`.

### Actual Behavior

Despite configuring the provider with the suggested `user_project_override` and `billing_project` I am unable to use the google_cloud_identity_group_* data sources.

### References

There is an issue about this regarding resources here #7477

Speculation: did the fix in #7477 not include data sources.

**Comment by edwardmedia** [comment]
@johnae what version of the provider are you using?

**Comment by johnae** [comment]
@edwardmedia Ah sorry, I'm using these providers currently:

```
$ terraform -v

Terraform v0.14.8
+ provider registry.terraform.io/carlpett/sops v0.6.0
+ provider registry.terraform.io/davidsbond/tailscale v0.0.1
+ provider registry.terraform.io/hashicorp/google v3.60.0
+ provider registry.terraform.io/hashicorp/google-beta v3.60.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

**Comment by edwardmedia** [comment]
@johnae the error message is from api which indicates it is not supported. Can you use a service account following its recommendation? It does require org level permissions.

> Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the cloudidentity.googleapis.com

>We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting

**Comment by johnae** [comment]
@edwardmedia Ok. I find it odd though that the resources would work but not the data sources, are they using different api:s? I was under the impression that #7477 and `billing_project` and `user_project_override` in general were meant to solve this issue without resorting to using a service account.
