### ISSUE TITLE
google_compute_interconnect_attachment: error when passign mtu

### ISSUE THREAD

**Issue by imrannayer** [hashicorp/terraform-provider-google#8721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/google v3.60.0
+ provider registry.terraform.io/hashicorp/google-beta v3.60.0

### Affected Resource(s)

* google_compute_interconnect_attachment

### Terraform Configuration Files

```tf

variable "mtu" {
  type        = string
  description = "Maximum Transmission Unit (MTU), in bytes, of packets passing through this interconnect attachment. Currently, only 1440 and 1500 are allowed. If not specified, the value will default to 1440"
  default = "1440"
}

resource "google_compute_interconnect_attachment" "interconnect_attachment1_region2" {
  name    = "vl-${var.vpc_name}-${var.region1}-${local.suffix3}"
  project = local.interconnect_project_id
  region  = var.region2
  router  = var.region2_router1_name
  mtu = var.mtu

  type                     = "PARTNER"
  edge_availability_domain = "AVAILABILITY_DOMAIN_1"

  lifecycle {
    ignore_changes = ["vlan_tag8021q"]
  }
}
```

### Expected Behavior

Create attachment

Attachment created by also getting following error:

`Error: Error waiting for InterconnectAttachment "vl-vpc-us-east4-cr5" to be provisioned: "Error reading InterconnectAttachment: mtu: '' expected type 'string', got unconvertible type 'float64'"
`

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/8707

**Comment by edwardmedia** [comment]
@imrannayer can you share the debug log?

**Comment by edwardmedia** [comment]
@imrannayer is this still an issue?

**Comment by imrannayer** [comment]
Yes it is still happening. I cant generate logs from my production environment and I dont have any non-prod env available at the moment. 
It is happening even if I change the values from GCP GUI console after which terraform will start throwing that error.

**Comment by edwardmedia** [comment]
@imrannayer from the error you posted, it complains the data type of that field. Currently **mtu** is defined as a string. I have a fix (see #8707) . For that, you can either provide it with a string value or wait for the fix in the release.  Sorry about the inconvenience

**Comment by imrannayer** [comment]
I provided it as a string and it is still an issue.

**Comment by imrannayer** [comment]
It causes a problem even if I change it from gui console after which terraform refresh keep failing with the error.

**Comment by edwardmedia** [comment]
@imrannayer let's wait for the next release then
