### ISSUE TITLE
google_cloud_run_service `Status` attribute is an array and not an Object

### ISSUE THREAD

**Issue by alethenorio** [hashicorp/terraform-provider-google#8728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/google v3.54.0
+ provider registry.terraform.io/hashicorp/google-beta v3.56.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* google_cloud_run_service 
* google_cloud_run_service data source

### Terraform Configuration Files

```tf
data "google_cloud_run_service" "my_service" {
  name     = "myservice"
  location = "europe-west1"
}
```

### Debug Output

```
$ terraform state show data.google_cloud_run_service.my_service
# data.google_cloud_run_service.my_service:
data "google_cloud_run_service" "my_service" {
    autogenerate_revision_name = false
    id                         = "locations/europe-west1/namespaces/my-project/services/my-service"
    location                   = "europe-west1"
    name                       = "my-service"
    project                    = "my-service"
    status                     = [
        {
            conditions                   = [
                {
                    message = ""
                    reason  = ""
                    status  = "True"
                    type    = "Ready"
                },
                {
                    message = ""
                    reason  = ""
                    status  = "True"
                    type    = "ConfigurationsReady"
                },
                {
                    message = ""
                    reason  = ""
                    status  = "True"
                    type    = "RoutesReady"
                },
            ]
            latest_created_revision_name = "my-service-a1brr"
            latest_ready_revision_name   = "my-service-a1brr"
            observed_generation          = 224
            url                          = "https://my-service-url.a.run.app"
        },
    ]

    // Other fields below omitted as they are ireelevant to the issue
}
```
### Expected Behavior

The `Status` section is an Object instead of an Array as per documentation

### Actual Behavior

The `Status` section is an array and you need to index it in order to change it

### Steps to Reproduce

1. Attempt to reference either a cloud run resource or data source by `data.google_cloud_run_service.my_service.status.url`

**Comment by edwardmedia** [comment]
@alethenorio looked at `metadata`, `spec` and `status` in below schema, all three are `object` in api and `schema.TypeList` in terraform code. This is by design. 

```
{
  "apiVersion": string,
  "kind": string,
  "metadata": {
    object (ObjectMeta)
  },
  "spec": {
    object (ServiceSpec)
  },
  "status": {
    object (ServiceStatus)
  }
}
```

https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services#ServiceStatus

**Comment by alethenorio** [comment]
@edwardmedia I am clearly looking at the state and how Terraform stores it and it is an array

When I try to refer to it like this

google_cloud_run_service.my_service.status.url

I get an error that this is not possible.

If I then switch to

google_cloud_run_service.my_service.status[0].url

Then it works and this is what I am using right now.

Not sure I understand why this was closed.

**Comment by edwardmedia** [comment]
@alethenorio this is by design. I have listed examples of other fields that share the same types.

**Comment by alethenorio** [comment]
Ah I understood what you meant now. Thanks
