### ISSUE TITLE
Add support for `network_config` to `google_container_node_pool`

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We'll also want it supported in `google_container_cluster` where node pools are inlined (the default pool, inline node pool list)

### New or Affected Resource(s)

* google_container_node_pool
* google_container_cluster

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/178640055

**Comment by upodroid** [comment]
I think we can close this. I added ILB Subsetting a while back in https://github.com/GoogleCloudPlatform/magic-modules/pull/4626 and the other fields are already available.

https://pkg.go.dev/google.golang.org/api/container/v1beta1#NetworkConfig

```
enable_intranode_visibility - (Optional) Whether Intra-node visibility is enabled for this cluster. This makes same node pod to pod traffic visible for VPC network.

enable_l4_ilb_subsetting - (Optional, Beta) Whether L4ILB Subsetting is enabled for this cluster.

private_ipv6_google_access - (Optional) The desired state of IPv6 connectivity to Google Services. By default, no private IPv6 access to or from Google Services (all access will be via IPv4).

datapath_provider - (Optional) The desired datapath provider for this cluster. By default, uses the IPTables-based kube-proxy implementation.

default_snat_status - (Optional) GKE SNAT DefaultSnatStatus contains the desired state of whether default sNAT should be disabled on the cluster, API doc.
```

GKE has many breaking changes planned for v4. We might as well make NetworkConfig parameters nested as well to make it lineup with the API format.

**Comment by rileykarson** [comment]
This refers to the very similarly named https://pkg.go.dev/google.golang.org/api/container/v1beta1#NodeNetworkConfig block at the node pool level, not that cluster-level one!

**Comment by upodroid** [comment]
Got it https://cloud.google.com/kubernetes-engine/docs/how-to/multi-pod-cidr
