### ISSUE TITLE
azure resource for creating VM from restore point(recovery service vault )

### ISSUE THREAD

**Issue by prtkdave** [hashicorp/terraform-provider-google#8750]
### Community Note

We should have resource that can create VM from the recovery point. There is no resource as of now to create virtual machine instance from recovery service vault. It is very critical to have automated restoration of VMs same as backup.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment]
I think this is meant for the Azure provider? Closing, I'd suggest filing there.
