### ISSUE TITLE
HPA documentation section

### ISSUE THREAD

**Issue by pentago** [hashicorp/terraform-provider-google#8754]
Heapster

google_container_cluster documentation isn't correct in the fact that GKE uses **Heapster** for horizontal pod autoscaling, it's superseded with metrics-server long time ago.

**Comment by edwardmedia** [comment]
@pentago can you specify what is wrong and what is supposed to be?

**Comment by edwardmedia** [comment]
@pentago can you provide the details about this?

**Comment by pentago** [comment]
This provider page URL: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster
This paragraph: https://i.imgur.com/mDdqMuW.png
Heapster isn't used for long time now, metrics-server is new package for HPA.
