### ISSUE TITLE
Add support for npm in google_artifact_registry_repository

### ISSUE THREAD

**Issue by beingminimal** [hashicorp/terraform-provider-google#8757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Hello,

Please add support for npm packages in google_artifact_registry_repository terraform resource.

Refer link for more detail - https://cloud.google.com/artifact-registry/docs/nodejs/quickstart

### New or Affected Resource(s)

* google_artifact_registry_repository

**Comment by upodroid** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/4604

That fix should be released in v3.62 of the provider.

**Comment by rileykarson** [comment]
Closing as fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4604

**Comment by upodroid** [comment]
```
resource "google_artifact_registry_repository" "my-repo" {
  provider = google-beta

  location = "us-central1"
  repository_id = "my-repository"
  description = "example docker repository"
  format = "NPM"
// any value is accepted here now. Before 3.62 only DOCKER was accepted.
  // format = "potato"
}
```

**Comment by beingminimal** [comment]
@upodroid Thanks for the update. I will try with adding format as NPM.
