### ISSUE TITLE
google_storage_bucket 'project' argument required

### ISSUE THREAD

**Issue by jamesmealing** [hashicorp/terraform-provider-google#8760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Note: I raised this previously in issue [#8715](https://github.com/hashicorp/terraform-provider-google/issues/8715) which was incorrectly closed - I have tried commenting on the closed issue, however, I am yet to receive a reply so I don't know if this has been picked up or not.

### Terraform Version

Terraform v0.14.5
provider registry.terraform.io/hashicorp/google v3.60.0

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/google"
      version = "3.60.0"
    }
  }
}

provider "google" {
  project = "my-test-project"
  region  = "europe-west1"
  zone    = "europe-west1-b"
}

resource "google_storage_bucket" "example" {
  name          = "my-test-bucket"
  location      = "europe-west1"
}
```

### Debug Output
https://gist.github.com/jamesmealing/51dd169685051cee266a315eb8f69988

### Expected Behavior

According to the resource [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#argument-reference) the `project` argument is optional and will use the provider project if it is not provided. 

### Actual Behavior

When running a `terraform apply` it errors with the following: '_Error: project: required field is not set_' - Despite the project being set in the provider.

As per the previously closed issue, including the `provider` argument also resolves the issue, however, as per the `provider` [documentation](https://www.terraform.io/docs/language/meta-arguments/resource-provider.html), this argument should not be required by default:

"_By default, Terraform interprets the initial word in the resource type name (separated by underscores) as the local name of a provider, and uses that provider's default configuration. For example, the resource type google_compute_instance is associated automatically with the default configuration for the provider named google._"

In this case, the `google_storage_bucket` resource isn't automatically using the default configuration with regards to `project`, hence either `provider` or `project` must be explicitly defined.

The documentation for the project argument states that - "_If it is not provided, the provider project is used_" - But this is not the case as the provider project is defined but is not being used.

### Steps to Reproduce

1. Run a `terraform apply` using the sample code above

**Comment by edwardmedia** [comment]
@rileykarson I have left comments in #8716. What do you think about the behavior?

**Comment by edwardmedia** [comment]
@jamesmealing noticed your config below Let me know what you see

```tf
terraform {
  required_providers {
    aws = {                <--------- aws? What do you see if you change it to google?
      source  = "hashicorp/google"
      version = "3.60.0"
    }
  }
}
```

**Comment by rileykarson** [comment]
Deduping back to #8715 where there's more discussion.

**Comment by jamesmealing** [comment]
@edwardmedia was absolutely right above regarding the provider name - Full reply and explanation in #8715.
