### ISSUE TITLE
Error creating SecretVersion: googleapi: Error 400: Field [payload] is required.

### ISSUE THREAD

**Issue by yanc0** [hashicorp/terraform-provider-google#8766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.9

### Affected Resource(s)

* google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret_version" "fleets-password" {
  secret = google_secret_manager_secret.fleets-password.id
}
```

### Debug Output

```
google_secret_manager_secret_version.password: Creating...

Error: Error creating SecretVersion: googleapi: Error 400: Field [payload] is required.

  on cloudsql.tf line 48, in resource "google_secret_manager_secret_version" "password":
  48: resource "google_secret_manager_secret_version" "password" {
```

### Expected Behavior

The documentation says that only `secret` attribute is required. I expect the secret version to be created
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version#argument-reference

### Actual Behavior

Google api returns a 400 error, saying that a payload is missing. If we add the `secret_data` attribute, there is no more error.

```
resource "google_secret_manager_secret_version" "password" {
  secret = google_secret_manager_secret.password.id
  secret_data = "mysecretpassword"
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@yanc0  can you share the full debug log?

**Comment by yanc0** [comment]
```
resource "google_secret_manager_secret" "cloudsql-password" {
  secret_id = "cloudsql-password"

  labels = {
    label = "cloudsql"
  }

  replication {
    user_managed {
      replicas {
        location = "europe-west1"
      }
      replicas {
        location = "europe-west2"
      }
    }
  }
}

resource "google_secret_manager_secret_version" "cloudsql-password" {
  secret = google_secret_manager_secret.cloudsql-password.id
}
```
```
2021-03-25T16:48:05.977+0100 [INFO]  plugin.terraform-provider-google_v3.61.0_x5: 2021/03/25 16:48:05 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /v1/projects/my-project/secrets/cloudsql-password:addVersion?alt=json HTTP/1.1
Host: secretmanager.googleapis.com
User-Agent: Terraform/0.14.9 (+https://www.terraform.io) Terraform-Plugin-SDK/2.4.4 terraform-provider-google/dev
Content-Length: 3
Content-Type: application/json
Accept-Encoding: gzip

{}


-----------------------------------------------------: timestamp=2021-03-25T16:48:06.170+0100
2021-03-25T16:48:06.171+0100 [INFO]  plugin.terraform-provider-google_v3.61.0_x5: 2021/03/25 16:48:06 [DEBUG] Retry Transport: Stopping retries, last request failed with non-retryable error: googleapi: got HTTP response code 400 with body: HTTP/2.0 400 Bad Request
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Thu, 25 Mar 2021 15:48:06 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "error": {
    "code": 400,
    "message": "Field [payload] is required.",
    "status": "INVALID_ARGUMENT"
  }
}:

```

Thank you @edwardmedia !

**Comment by yanc0** [comment]
Same behaviour with the exact copy/paste of the example

**Comment by edwardmedia** [comment]
@yanc0 can you share the full debug log for running the example?

**Comment by domgolonka** [comment]
I am getting the same error with version 0.13.6

**Comment by yanc0** [comment]
@edwardmedia here is the full debug log (I only targeted google secret resources, avoiding the entier cloudsql execution plan)
https://gist.github.com/yanc0/90db052f8491d711f5519ad67f41ddd3

**Comment by edwardmedia** [comment]
@yanc0 I noticed you chose **userManaged** in the `google_secret_manager_secret`. Shouldn't you provide the data then? If you set **automatic** for replication, do you still receive this error?

```
  "replication": {
    "userManaged": {
      "replicas": [
        {
          "location": "europe-west1"
        },
        {
          "location": "europe-west2"
        }
      ]
    }
```

**Comment by yanc0** [comment]
Same error when changing replication type 
```
  replication {
    automatic = true
  }

Error: Error creating SecretVersion: googleapi: Error 400: Field [payload] is required.
```

**Comment by edwardmedia** [comment]
@yanc0  can you share the full config so I can repro?

**Comment by yanc0** [comment]
@edwardmedia https://gist.github.com/yanc0/4c4c530b67f1cd0f0920e51682b18adf
Thanks !

**Comment by edwardmedia** [comment]
@yanc0 see [required](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets/addVersion) in the api doc. Thank you

**Comment by yanc0** [comment]
Thanks @edwardmedia !
