### ISSUE TITLE
SecretManager for cloud build

### ISSUE THREAD

**Issue by vongohren** [hashicorp/terraform-provider-google#8808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There seeme to be an interconnected way of saying what secret you want to use in the google cloud build: https://cloud.google.com/build/docs/securing-builds/use-secrets#configuring_builds_to_access_the_secret_from

I cannot find anything similar in terraform?
I only found this: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#kms_key_name an attribute in the secret block, that demands a kms.

But the docs have no notion of KMS, just secret name and version.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

Links in description, not found anything similar on this repo

**Comment by megan07** [comment]
Hi @vongohren ! Thanks for reaching out! I think this will be the `secret_env` that is directly on the `step` block. I would link it to you, but it appears that our links don't work great when there are 2 attributes on the same page, with the same name. Sorry about that! I will bring that up with the appropriate team.

[Here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#args) is a look at `args`, from my understanding it looks like you need this, `entrypoint` ([link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#entrypoint)) and `secret_env` (which is just 2 below `entrypoint` in the docs).

Let me know if that helps! Sorry again for the docs trouble!

**Comment by eriksw** [comment]
@megan07 How are we supposed to use secrets that we've put into secrets manager (already, per the documentation) without putting the secret values into our terraform code/state?

`secret_env` appears to require the literal value of the secret (which is _not okay_ to put into terraform!)—where would be the place to specify the `versionName` per https://cloud.google.com/build/docs/securing-builds/use-secrets#configuring_builds_to_access_the_secret_from

**Comment by megan07** [comment]
@eriksw I'm sorry! I think I was focussing on the wrong part of the original question. I think we'll need to add [`availableSecrets`](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build.Secrets) to the [`build`](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build) block.

Sorry for the misunderstanding. Is this inline with what you're looking for?

**Comment by vongohren** [comment]
@eriksw thanks for following up this and @megan07 I think that is something that will assist.
As @eriksw mentions, with the link, there should be a way to address the secret by version as google buiild allows adding it

**Comment by cgroschupp** [comment]
I have created a pr. 
@megan07 can you please review this pr?
