### ISSUE TITLE
incorrect documentation of properties ipv4_enabled and private_network of google_sql_database_instance

### ISSUE THREAD

**Issue by mvanholsteijn** [hashicorp/terraform-provider-google#8818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
0.13.6

### Affected Resource(s)

* google_sql_database_instance

### Issue Description
The documentation states that `ipv4_enabled` and `private_network` are mutually exclusive but the CloudSQL documentation says:

> You can use both public IP and private IP to connect to the same Cloud SQL instance. Neither connection method affects the other.

### References

- https://cloud.google.com/sql/docs/postgres/private-ip
- https://cloud.google.com/sql/docs/mysql/private-ip

**Comment by c2thorn** [comment]
closed with https://github.com/hashicorp/terraform-provider-google/pull/8819
