### ISSUE TITLE
'Error: Provider produced inconsistent final plan' when using workflows and scheduler

### ISSUE THREAD

**Issue by swfz** [hashicorp/terraform-provider-google#8832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.62.0

### Affected Resource(s)

* google_workflows_workflow

### Terraform Configuration Files

```tf
terraform {
  required_version = "~>0.14.2"
  required_providers {
    google = "~>3.62.0"
  }
}

provider "google" {
  project = var.project
  region  = var.region
}

variable "region" {}
variable "project" {}

locals {
  region  = var.region
  project = var.project
}

resource "google_cloud_scheduler_job" "workflow_job" {
  name             = "workflow-scheduler"
  description      = "Kick Workflow Scheduler"
  schedule         = "0 1 * * *"
  time_zone        = "Asia/Tokyo"
  attempt_deadline = "320s"
  project          = local.project
  region           = local.region

  retry_config {
    retry_count          = 1
    max_backoff_duration = "3600s"
    max_doublings        = 5
    max_retry_duration   = "0s"
    min_backoff_duration = "5s"
  }

  http_target {
    http_method = "POST"
    uri         = "https://workflowexecutions.googleapis.com/v1/${google_workflows_workflow.sample.name}/executions"
  }
}

resource "google_workflows_workflow" "sample" {
  name            = "sample_workflow_from_terraform"
  description     = "sample"
  region          = local.region
  source_contents = file("sample.yml")
}
```

### Panic Output

```
Error: Provider produced inconsistent final plan

When expanding the plan for google_cloud_scheduler_job.workflow_job to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.http_target[0].uri: was
cty.StringVal("https://workflowexecutions.googleapis.com/v1/sample_workflow_from_terraform/executions"),
but now
cty.StringVal("https://workflowexecutions.googleapis.com/v1/projects/terraform-sample-294414/locations/us-central1/workflows/sample_workflow_from_terraform/executions").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Actual Behavior

It happens when a workflow is created or changed, but the workflow settings themselves are reflected.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@swfz can you share the full debug log?

**Comment by swfz** [comment]
@edwardmedia sorry. 
Share debug logs
https://gist.github.com/swfz/33b1b3c699471ad890caf614a00d9427

**Comment by edwardmedia** [comment]
@swfz  I see what the problem is. Thanks
