### ISSUE TITLE
google_container_cluster addons "config_connector_config" does not work

### ISSUE THREAD

**Issue by monotek** [hashicorp/terraform-provider-google#8836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/carlpett/sops v0.6.0
+ provider registry.terraform.io/fluxcd/flux v0.1.1
+ provider registry.terraform.io/gavinbunney/kubectl v1.10.0
+ provider registry.terraform.io/hashicorp/google v3.62.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "playground" {
  addons_config {
    config_connector_config {
      enabled  = true
    }    
    network_policy_config {
      disabled = false
    }
  }

  name               = var.name
  project            = var.project
  location           = var.location
  initial_node_count = 1
  min_master_version = "1.18.16-gke.2100"

  network_policy {
    enabled  = true
    provider = "CALICO"
  }

  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }

  remove_default_node_pool = true
}
```

### Expected Behavior

cluster with config connector addon enabled should be created

### Actual Behavior

```
Error: Unsupported block type

  on main.tf line 4, in resource "google_container_cluster" "test":
   4:     config_connector_config {

Blocks of type "config_connector_config" are not expected here.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by venkykuberan** [comment]
@monotek `config_connector_config` exist only in `beta` provider, using the same should work.  Please let us know if that didn't work.

**Comment by monotek** [comment]
Thanks. 
It works in the beta module.
Any eta when this is going to be in stable?

**Comment by venkykuberan** [comment]
Once the API GA version supports it we will add it to provider GA version.
