### ISSUE TITLE
in big_query_options there is no option for adding identifying and excluding fields for scanning the particular columns in bigquery

### ISSUE THREAD

**Issue by sriram23kmm** [hashicorp/terraform-provider-google#8838]
### Affected Resource(s)

* google_data_loss_prevention_job_trigger

https://github.com/hashicorp/terraform-provider-google/blob/01b9d53e3ba40edd547777591f39858c7a8b5b1d/google/resource_data_loss_prevention_job_trigger.go#L181

#refer below which we can do it from REST call

"storageConfig": {
      "bigQueryOptions": {
        "tableReference": {
          "projectId": "",
          "tableId": "",
          "datasetId": ""
        },
        "identifyingFields": [
          {
            "name": "name of bigquery column"
          }
        ],
        "excludedFields": [],
        "sampleMethod": "RANDOM_START",
        "rowsLimit": "82"
      }
    }

**Comment by edwardmedia** [comment]
@sriram23kmm They might be the features that have not been implemented. Where do you see them?

**Comment by sriram23kmm** [comment]
@edwardmedia please look into google documentation for `BigqueryOpptions` :  https://cloud.google.com/dlp/docs/inspecting-storage#inspect_a_table

 `identifyingFields` & `ExcludingFields` Attributes are not available with these terraform resource 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_job_trigger
