### ISSUE TITLE
Inconsistent release name "3.63.0" (no v)

### ISSUE THREAD

**Issue by ImJasonH** [hashicorp/terraform-provider-google#8845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

N/A

### Affected Resource(s)

https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.63.0

The release is named `3.63.0`, which is inconsistent with previous releases, e.g., [v3.62.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.62.0), and with its own release tag, which is [`v3.63.0`](https://github.com/hashicorp/terraform-provider-google/tree/v3.63.0)

### Expected Behavior

I expected release v3.63.0 to be named v3.63.0, consistent with its tag name and previous release names.

### Actual Behavior

v3.63.0 was named 3.63.0.

### References

See https://github.com/hashicorp/terraform-provider-google/releases

cc @slevenick who created this release

**Comment by slevenick** [comment]
Whoops, this is now fixed
