### ISSUE TITLE
Cannot create an instance with a service account but no scope

### ISSUE THREAD

**Issue by quentinms** [hashicorp/terraform-provider-google#8871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: v0.12.18
Google: 3.63.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "test-instance" {
  name    = "test-instance-1"
  project = "test-project"

  machine_type = "n1-standard-2"
  zone         = var.zone

  service_account {
    email  = "test-service-account@test-project.iam.gserviceaccount.com"
    scopes = []
  }
}
```

### Expected Behavior

Create an instance with a service account but no scope. Same result as 
```
gcloud compute instances create test-instance-1 --no-scopes --service-account=test-service-account@test-project.iam.gserviceaccount.com --project=test-project
```

### Actual Behavior

```
Error: List shorter than MinItems

  on main.tf line 57, in resource "google_compute_instance" "test-instance":
  57:     scopes = []

Attribute supports 1 item minimum, config has 0 declared
```

### Steps to Reproduce

1. Try creating an instance with a service account but no scope
2. `terraform plan`

### References

* #8801
* https://github.com/GoogleCloudPlatform/magic-modules/pull/4634

**Comment by rick-pri** [comment]
Wow, thanks for raising this as I just came across this in the last hour ...

**Comment by rick-pri** [comment]
If you want to get around this for now I had to roll back to the previous version with:

```
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "<= 3.62.0"
    }
}
```

and then run `terraform init -upgrade`.

**Comment by edwardmedia** [comment]
@quentinms I submitted that pr that disallows the empty scope. `scope` is optional. To match`--no-scope`, can you remove the `scope` from the config?

**Comment by quentinms** [comment]
@edwardmedia I'll try and report back. That being said `scopes` is currently marked as `required` in the docs (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#scopes).

**Comment by edwardmedia** [comment]
@quentinms it should be optional. Let me update the code accordingly
