### ISSUE TITLE
Apply is running for 20 minutes before throwing an error

### ISSUE THREAD

**Issue by xrustalik** [hashicorp/terraform-provider-google#8872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I met an issue with terraform apply command. It runs a significant amount of time when meeting an error. 
I.e. I'm running a simple terraform script that changes the service account role for the google cloud project.  
Usually, this procedure takes around 1 minute to finish. However, when an error is met, it is running for 20 or more minutes and then throwing an error. 

I also noticed this behavior when creating and updating databases with errors and even changing options for the Cloud Run services.

Is there any way to throw an error faster?

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.61.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

```

```
module.gcp-infra.google_cloud_run_service_iam_policy.pub-sub-auth: Still destroying... [id=v1/projects/test/lo...s/europe-west2/services/test **10m30s** elapsed]
module.gcp-infra.google_cloud_run_service_iam_member.member-pub-sub: Still creating... [**10m30s** elapsed]
module.gcp-infra.google_cloud_run_service_iam_member.member-bitbucket: Still creating... [**10m30s** elapsed]
```
Script that invokes these changes: 
```
resource "google_cloud_run_service_iam_member" "member-bitbucket" {
  location = google_cloud_run_service.test.location
  project = google_cloud_run_service.test.project
  service = google_cloud_run_service.test.name
  role = "roles/run.admin"
  member = "serviceAccount:***"
}
resource "google_cloud_run_service_iam_member" "member-pub-sub" {
  location = google_cloud_run_service.test.location
  project = google_cloud_run_service.test.project
  service = google_cloud_run_service.test.name
  role = "roles/run.invoker"
  member = "serviceAccount:***"
}
```

#### Steps to Reproduce
```
terraform plan
terraform apply
```

**Comment by melinath** [comment]
@xrustalik I can try to look into this. Do you have debug logs from a test run that failed? What is the error you're getting?

**Comment by melinath** [comment]
Closing due to lack of information. Please reopen if you have more details.
