### ISSUE TITLE
Add support for Bigtable CMEK

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support the https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters#EncryptionConfig block

### New or Affected Resource(s)

* google_bigtable_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* b/122704067

**Comment by upodroid** [comment]
cloud.google.com/go/bigtable doesn't support CMEK yet. Is it worth rewriting that resource to use google.golang.org/api/bigtableadmin/v2 instead?

**Comment by rileykarson** [comment]
Yeah, we should move the bigtable resources onto the REST client libs eventually. Mechanically we'd want to do it in two parts, shifting to REST but supporting the same stuff & then adding new functionality like `EncryptionConfig`.

**Comment by rameshdharan** [comment]
> cloud.google.com/go/bigtable doesn't support CMEK yet.

FYI cloud.google.com/go/bigtable CMEK support is in progress and almost ready:
https://github.com/googleapis/google-cloud-go/pull/3899

> Is it worth rewriting that resource to use google.golang.org/api/bigtableadmin/v2 instead?

I would say no per above. 

(h/t @kolea2 who supervises Cloud Bigtable's client integrations)

**Comment by upodroid** [comment]
@rameshdharan I see that PR has been merged now. Do you know when that team will cut a new release?

One of the reasons I want to rewrite it with the autogen library is that it is using gRPC to communicate which is troublesome (#8221) as we can't log requests in terraform.

https://github.com/googleapis/google-cloud-go/blob/master/bigtable/admin.go#L632

I did some reading when I looked at 8221 and some gRPC [interceptors](https://dev-state.com/posts/grpc_framework_3/) needs to be used which looks pretty complicated.

**Comment by rameshdharan** [comment]
> @rameshdharan I see that PR has been merged now. Do you know when that team will cut a new release?

Release has been cut (two recent ones actually):
https://pkg.go.dev/cloud.google.com/go/bigtable@v1.10.0

> One of the reasons I want to rewrite it with the autogen library is that it is using gRPC to communicate which is troublesome (#8221) as we can't log requests in terraform.

Understood, however note that while I can see how request logging can be useful FWIW I haven’t heard it raised from any of our existing Bigtable+Terraform users as a blocking concern. 

We do meanwhile have a customer blocked and eagerly awaiting the ability to use Terraform to create Bigtable CMEK-protected clusters, hence we are correspondingly eager to help move this along.
