### ISSUE TITLE
Can't bootstrap confidential_nodes without node_config for default pool

### ISSUE THREAD

**Issue by hughryan** [hashicorp/terraform-provider-google#8885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.14.9

### Google Provider Version
google-beta 0.62.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "confidential_cluster_01" {
  provider              = google-beta
  name                  = "confidential_cluster_01"
  project               = local.project_id
  network               = google_compute_network.public_01.name
  subnetwork            = google_compute_subnetwork.public_01.name
  enable_shielded_nodes = true
  location = local.region
  monitoring_service = "monitoring.googleapis.com/kubernetes"

  remove_default_node_pool = true
  initial_node_count       = 1

  master_auth {
    username = ""
    password = ""
  }

  release_channel {
    channel = "RAPID"
  }

  vertical_pod_autoscaling {
    enabled = true
  }

  cluster_autoscaling {
    enabled = false
  }

  confidential_nodes {
    enabled = true
  }

  database_encryption {
    state    = "ENCRYPTED"
    key_name = google_kms_crypto_key.key_01.id
  }

  workload_identity_config {
    identity_namespace = "${local.project_id}.svc.id.goog"
  }

  networking_mode = "VPC_NATIVE"
  ip_allocation_policy {
    cluster_ipv4_cidr_block  = ""
    services_ipv4_cidr_block = ""
  }

  network_policy {
    enabled = true
  }

  addons_config {
    network_policy_config {
      disabled = false
    }

    horizontal_pod_autoscaling {
      disabled = true
    }

    http_load_balancing {
      disabled = true
    }

    gce_persistent_disk_csi_driver_config {
      enabled = true
    }
  }
}

resource "google_container_node_pool" "n2d_standard_4" {
  provider = google-beta
  name     = "n2d-standard-4"
  project  = local.project_id
  location = local.region
  cluster  = google_container_cluster.confidential_cluster_01.name

  node_locations = [
    "us-east1-b",
    "us-east1-c"
  ]

  initial_node_count = 1

  autoscaling {
    min_node_count = 2
    max_node_count = 3
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  upgrade_settings {
    max_surge       = 1
    max_unavailable = 0
  }

  node_config {
    preemptible  = false
    machine_type = "n2d-standard-4"
    disk_size_gb = "100"
    disk_type    = "pd-standard"

    service_account = google_service_account.confidential_cluster_01.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    shielded_instance_config {
      enable_secure_boot          = true
      enable_integrity_monitoring = true
    }

    metadata = {
      disable-legacy-endpoints = "true"
    }

    labels = {
      node-pool = "n2d-standard-4"
    }
  }
}

```

### Debug Output

```
Error: googleapi: Error 400: Confidential nodes feature only supports N2D machine series., badRequest
```

### Expected Behavior

The cluster should have bootstrapped with an N2D machine series type for the default pool since `confidential_nodes` was set to true in the configuration, and then the default node pool should have been destroyed because `remove_default_node_pool` was set to true. Additionally, a database encryption key was specified, but was also not provided to the default pool.

I think that forcing us to define the config for the default pool is reasonable for both the confidential nodes and database encryption features, however, when the default pool config is defined along with `remove_default_node_pool` it results in terraform trying to recreate the default pool on subsequent runs of `terraform apply`.

### Actual Behavior

The cluster failed to bootstrap because it tried to create the default node pool with the wrong machine series type. It then also failed to bootstrap after specifying the default pool series type because it did not have access to the database encryption key.

### Steps to Reproduce

1. Define a GKE cluster with `confidential_nodes` enabled, `database_encryption.state` set to `ENCRYPTED` with a provided key, and `remove_default_node_pool` set to true. You should also define a custom node pool using N2D machine types.
2. Try and create the cluster, it will fail because it tries to create default nodes with the wrong machine type.
3. Add the machine type to the default pool node_config definition. It will now fail because the default pool doesn't have access to the encryption keys.
4. Add a service account to the default pool node_config for access to the keys. The cluster will now create properly.
5. Run terraform apply (or plan) again, and the cluster will try to recreate the default pool due to the default pool node_config definition, despite `remove_default_node_pool` being set to true.

### Important Factoids

Default pool node_config required to get the cluster to bootstrap:
```
  node_config {
    # bootstrap with n2d node type to enable confidential nodes
    machine_type = "n2d-standard-2"
    # boostrap with service account for access to keys
    service_account = google_service_account.key_service_account.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
  ```

### References

GKE Confidential Nodes Requirements: https://cloud.google.com/kubernetes-engine/docs/how-to/confidential-gke-nodes#availability

**Comment by hughryan** [comment]
> @hughryan can you post the debug log?

The issue is multifaceted. Under what conditions is the debug log are you interested in?

**Comment by edwardmedia** [comment]
@hughryan can you see if below config works for you?

```tf
resource "google_container_cluster" "confidential_nodes" {
  name               = "%s"
  location           = "us-central1-a"
  enable_shielded_nodes = true
  release_channel {
    channel = "RAPID"
  }

  node_pool {
    name = "%s"
    initial_node_count = 1
    node_config {
      machine_type = "n2d-standard-2"
    }
  }

  confidential_nodes {
    enabled = true
  }
}
```

**Comment by hughryan** [comment]
> @hughryan can you see if below config works for you? If not, I'd like to see the api requests & responses in creating the cluster.

I don't see how this would end up deleting the default node pool. Did you mean to have `remove_default_node_pool = true` set as well?

**Comment by upodroid** [comment]
> "node pools defined inside a cluster can't be changed (or added/removed) after cluster creation without deleting and recreating the entire cluster."

This is a typo. The only requirement is that a nodepool must be created during the first POST API call to create the cluster, hence the `remove_default_node_pool` value. That specifies a tiny nodepool in the 1st POST Call and deletes it right away. You can add/delete nodepools after the cluster has been created. You can even have clusters with 0 nodepools.

**Comment by edwardmedia** [comment]
@hughryan is this still an issue?

**Comment by edwardmedia** [comment]
@hughryan closing assuming it is no longer an issue
