### ISSUE TITLE
Cannot clear projects from google_billing_budget

### ISSUE THREAD

**Issue by juliocc** [hashicorp/terraform-provider-google#8888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/google v3.63.0

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
resource "google_billing_budget" "budget" {
  billing_account = var.billing_account
  display_name    = "my budget"
  amount {
    last_period_amount = true
  }
  threshold_rules {
    threshold_percent = 1.0
  }
  budget_filter {
    projects = [
      var.project_number_1,
      var.project_number_2
    ]
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Removing the `budget_filter` block from an existing budget should clear the projects from the underlying resource.

### Actual Behavior

Projects are not removed and budget remains the same.

### Steps to Reproduce

1. Provide values to `billing_account`, `project_number_1` and `project_number_2`
2. terraform apply the code shown above
3. Remove the `billing_filter` block
4. terraform apply again

### Important Factoids

Adding other projects or removing some projects works correctly. The problem is updating an existing budget by removing the `budget_filter` block or setting projects to null or []

### References

N/A

**Comment by venkykuberan** [comment]
@juliocc can you please attach the debug log of your update call , after removing the `budget_filter`.

**Comment by juliocc** [comment]
Here it is: https://gist.github.com/juliocc/2497d050fce0277ee7321eb8cdf01b92

**Comment by venkykuberan** [comment]
Looks like UpdateMask need to include this field in the update call., @melinath

**Comment by melinath** [comment]
@juliocc the fix to this bug will still require you to set `projects = []` and apply prior to deleting the block altogether. This is due to implementation details about terraform core (and the fact that the budget filter block is considered Optional + Computed).
