### ISSUE TITLE
How to set cloud run ingress mode

### ISSUE THREAD

**Issue by pjeannet** [hashicorp/terraform-provider-google#8890]
Hello, I'm trying to set the ingress parameter for a cloud run instance to force it through a LB (with cloud armor). This can be done through the GCP console as shown bellow, but I can't see any parameter in the provider (both GA and beta). I tried to set it by hand and then use terraform plan to compare the online and local conf and see if there were any metadatas that could be set but didn't find anything. Did I miss something? 
![image](https://user-images.githubusercontent.com/6052793/114425577-7fc7fd00-9bb9-11eb-9aa1-9fa37133591d.png)
Thanks

**Comment by melinath** [comment]
Hi, @pjeannet - it looks like you can configure ingress settings by using an annotation. Specifically, something like:

```hcl
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"

  metadata {
    annotations = {
      "run.googleapis.com/ingress" = "all"
    }
  }
}
```

Available values are documented here: https://cloud.google.com/sdk/gcloud/reference/run/deploy#--ingress

I'll make a PR to improve the documentation for the provider. Thanks!

**Comment by pjeannet** [comment]
Thanks for the answer, worked like a charm
