### ISSUE TITLE
google_dns_record_set - type "DS" is not expected type

### ISSUE THREAD

**Issue by jlam-bills** [hashicorp/terraform-provider-google#8897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version 

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.63.0
+ provider registry.terraform.io/hashicorp/google-beta v3.64.0

Your version of Terraform is out of date! The latest version
is 0.14.10. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
resource "google_dns_record_set" "ds_records" {
  for_each = {
    "dev" = ["<some_ds_record>"],
    "prd" = ["<some_ds_record>"],
    "stg" = ["<some ds record>"],
  }

  project      = <some_project_id>
  managed_zone = google_dns_managed_zone.<some_zone>.name
  ttl          = 300
  name         = "${each.key}.${google_dns_managed_zone.<some_zone>.dns_name}"
  rrdatas      = each.value
  type         = "DS"

```

### Expected Behavior

The expected behavior from "terraform validate" should pass. "DS" is a valid DNS record type [(reference doc)](https://cloud.google.com/dns/docs/overview#supported_dns_record_types)

### Actual Behavior

```
Error: expected type to be one of [A AAAA CAA CNAME MX NAPTR NS PTR SOA SPF SRV TLSA TXT], got DS
```
### Steps to Reproduce

1. `terraform validate`

### Important Factoids

We downgraded the provider to use version 3.63.0 rather than using the latest version (3.64.0).

```
    google = {
      source  = "hashicorp/google"
      version = "~> 3.63.0"
    }
```

**Comment by rjw57** [comment]
I opened https://github.com/GoogleCloudPlatform/magic-modules/pull/4689 which should fix this. Looks like it's just an incomplete whitelist in the magic modules service spec.
