### ISSUE TITLE
google_data_catalog_tag_template cannot be destroyed if force_delete argument is not set

### ISSUE THREAD

**Issue by jamiet-msm** [hashicorp/terraform-provider-google#8906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.9                                                                                                                 
provider registry.terraform.io/hashicorp/google v3.63.0

### Affected Resource(s)

* google_data_catalog_tag_template

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.63.0"
    }
  }
}

provider "google" {
  region = var.region
  project = var.project
}

variable "project" {}
variable "region"{}

resource "google_data_catalog_tag_template" "basic_tag_template" {
  tag_template_id = "my_tag_template"
  region          = var.region
  display_name    = "my tag template"

  fields {
    field_id     = "schemaversionmajor"
    display_name = "Major Version Number"
    type {
      primitive_type = "DOUBLE"
    }
    is_required = true
  }
}
```

### Expected Behavior

After applying this configuration I should be able to destroy it

### Actual Behavior

Destroying fails with error:

```bash
Error: Error when reading or editing TagTemplate: googleapi: Error 400: Invalid value at 'force' (TYPE_BOOL), ""
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value at 'force' (TYPE_BOOL), \"\"",
        "field": "force"
      }
    ]
  }
]
```

### Steps to Reproduce

Attempting to issue `terraform apply` using my own credentials on the above terraform configuration failed with error:

> Error when reading or editing DataCatalogTagTemplate "projects/msm-groupdata-datalake-dev/locations/europe-west2/tagTemplates/my_tag_template": googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the datacatalog.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting.

Hence I did this:
```bash
# deployer-dev@${SA_PROJECT}.iam.gserviceaccount.com is an SA that has permission to deploy this configuration
export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud --impersonate-service-account=deployer-dev@${SA_PROJECT}.iam.gserviceaccount.com  auth print-access-token)
terraform apply -var 'region=europe-west2' -var "project=${PROJECT}" --auto-approve
terraform destroy -var 'region=europe-west2' -var "project=${PROJECT}" --auto-approve
```

Upon issuing the destroy I got the error above.

If I look at the state file I see something quite peculiar:

```bash
cat terraform.tfstate | grep "force_delete"
            "force_delete": null,
```

`null` is not a valid value for `"force_delete"` and would explain why we're getting the strange error above. I'd consider this a bug. The provider shouldn't be writing `null` for a value that requires a boolean.

We were able to get around this easily by specifying `force_delete` in our terraform configuration...nonetheless, we figured we should inform you.

**Comment by edwardmedia** [comment]
dup https://github.com/hashicorp/terraform-provider-google/issues/8898
