### ISSUE TITLE
Creating HMAC key sometimes fails with "Unexpected Value"

### ISSUE THREAD

**Issue by huang-jy** [hashicorp/terraform-provider-google#8916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.29

### Affected Resource(s)

* google_storage_hmac_key

### Terraform Configuration Files

```tf
resource "google_service_account" "test-sa" {
  account_id   = "test-sa"
  display_name = "Service Account for testing"
}

resource "google_project_iam_member" "test-sa-storage-admin" {
  role = "roles/storage.admin"
  member = "serviceAccount:${google_service_account.test-sa.email}"
}

resource "google_project_iam_member" "test-sa-workload_identity" {
  role   = "roles/iam.workloadIdentityUser"
  member = "serviceAccount:my-project-name.svc.id.goog[test/test]"
}

resource "google_service_account_key" "test-sa-key" {
  service_account_id = google_service_account.test-sa.name
  # public_key_type    = "TYPE_X509_PEM_FILE"
  public_key_type = "TYPE_RAW_PUBLIC_KEY"

  depends_on = [
    google_service_account.test-sa
  ]
}

resource "google_storage_hmac_key" "test-sa-hmac-key" {
  service_account_email = google_service_account.test-sa.email
  depends_on = [
    google_service_account.test-sa,
    google_project_iam_member.test-sa-storage-admin,
    google_project_iam_member.test-sa-workload_identity,
    google_service_account_key.test-sa-key,
    google_container_cluster.test-cluster,
    google_container_node_pool.test-cluster-nodes
  ]
}

output "test-sa-private-key-data" {
  value = base64decode(google_service_account_key.test-sa-key.private_key)
}

output "test-sa-hmac-key-secret" {
  value = google_storage_hmac_key.test-sa-hmac-key.secret
}

output "test-sa-hmac-key-access-id" {
  value = google_storage_hmac_key.test-sa-hmac-key.access_id
}


```

### Debug Output

Not generated, but can generate if needed

### Panic Output

N/A

### Expected Behavior

Build produces without error

### Actual Behavior

Build proceeds, but will sometimes fail with "Unexpected Value" (will paste exact error if it occurs again)

### Steps to Reproduce

Difficult to reproduce as it seems like a race condition

1. `terraform plan -out tfplan `
2. `terraform apply tfplan`

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment]
@huang-jy can you post a debug log that shows the issue? What version of the provider are you using? Your Terraform version is pretty old.

**Comment by huang-jy** [comment]
> @huang-jy can you post a debug log that shows the issue? What version of the provider are you using? Your Terraform version is pretty old.

Yes, I'm trying to get the problem to reproduce -- I have the debug logging enable and will post the log if I enctouner it again.

Version details:

```
$ terraform version
Terraform v0.12.29
+ provider.google v3.57.0
+ provider.google-beta v3.60.0
+ provider.random v3.1.0
```

**Comment by huang-jy** [comment]
I got the problem reproduced this time with logging:

Stdout showed this
```
google_container_node_pool.nodes: Still creating... [5m20s elapsed]
google_container_node_pool.nodes: Still creating... [5m30s elapsed]
google_container_node_pool.nodes: Still creating... [5m40s elapsed]
google_container_node_pool.nodes: Still creating... [5m50s elapsed]
google_container_node_pool.nodes: Creation complete after 5m58s [id=projects/blender-fox/loc
ations/europe-west2-a/clusters/blender-fox/nodePools/blender-fox-node-pool]
google_storage_hmac_key.moon-sa-hmac-key: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to google_storage_hmac_key.moon-sa-hmac-key, provider
"registry.terraform.io/-/google" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

The relevant part of the debug log output is here: https://pastebin.com/HgFvLjXq (will expire in 2 days)

**Comment by edwardmedia** [comment]
@huang-jy can you try to see if you can repro this with the Terraform of the latest version? For the log, can you post it at https://gist.github.com/?

**Comment by huang-jy** [comment]
I've tried with the terraform 0.15.0 and I haven't yet got it fail, but I have found another problem.

Some of the fields are now marked as sensitive. For example:

```
│ Error: Output refers to sensitive values
│ 
│   on output.tf line 20:
│   20: output "test-sa-hmac-key-secret" {
│ 
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

If I use `sensitive=true` then the creation works, but the output will show redacted.

However, when creating a HMAC key, you can only see the output once (at time of creation). Meaning, if I cannot retrieve the value during the creation of the resource, I will not ever be able to use that secret value.

Is there a way around this? I appreciate that the whole point of the `sensitive` directive is to prevent it being viewed in plans and cli, but in cases like this, the value IS needed.

Yes, I could create the HMAC outside of Terraform, but then the infrastructure diverges from the code, and I'm trying to keep them in line.

**Comment by edwardmedia** [comment]
@huang-jy from what I read, with the latest version of Terraform, the originally reported error  has gone away. Is that true? If yes, let's close this issue.
In term of the `sensitive` attribute, it appears to be a different issue. I'd like you to open another issue so we can trace them separately. Do you mind?

**Comment by huang-jy** [comment]
So far it hasn't reappeared, I will continue testing and will raise a
separate issue regarding the `sensitive` attribute.

**Comment by edwardmedia** [comment]
Separate issue on `sensitive` https://github.com/hashicorp/terraform-provider-google/issues/8943

**Comment by huang-jy** [comment]
Thanks, I am continuing to test on 0.15 to see if I can get the original error. We can close this issue if I can't repliate.

**Comment by edwardmedia** [comment]
@huang-jy closing this now. Feel free to reopen if you can repro the original error

**Comment by huang-jy** [comment]
Yes, agreed. Have not been able to replicate issue since updating to 0.15 and letting terraform pick up the later provider versions
