### ISSUE TITLE
Flakey test: TestAccComputeInstance_soleTenantNodeAffinities

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8928]
TestAccComputeInstance_soleTenantNodeAffinities fails sometimes with the following error:

`Error waiting for instance to create: Instance could not be scheduled due to no matching node with property compatibility.`

It is a little hard to tell how frequently this comes up because previously there was a different issue.

Example failure: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182538?buildTab=tests&status=all&name=TestAccComputeInstance&pager.currentPage=1&orderBy=name&order=asc&expandedTest=8338733404894056578

**Comment by upodroid** [comment]
These were made updatable recently by @c2thorn in https://github.com/GoogleCloudPlatform/magic-modules/pull/4402

**Comment by c2thorn** [comment]
Thanks for the reminder @upodroid, it does seem to no longer flake.
