### ISSUE TITLE
dns_record_set clears rrdatas for AAAA records.

### ISSUE THREAD

**Issue by toumorokoshi** [hashicorp/terraform-provider-google#8935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.64.0
```

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
provider "google" {
 project     = "{project-id}"
 region      = "us-west1"
}

resource "google_dns_managed_zone" "parent-zone" {
  name        = "my-zone"
  dns_name    = "my-zone.hashicorptest.com."
  description = "Test Description"
}

resource "google_dns_record_set" "resource-recordset" {
  managed_zone = google_dns_managed_zone.parent-zone.name
  name         = "test-record.my-zone.hashicorptest.com."
  type         = "AAAA"
  rrdatas = [
      "7777:7777:7777:7777::",
      "8888:8888:8888:8888::",
  ]
  ttl          = 86400
}
```

### Debug Output

https://gist.github.com/toumorokoshi/c4b179b7585ab00093c70e72003ad339

### Panic Output

N/A

### Expected Behavior

terraform plan shows the rrdatas specified:  "7777:7777:7777:7777::",  "8888:8888:8888:8888::".

### Actual Behavior

terraform plans shows an empty list of rrdatas:

```
  # google_dns_record_set.resource-recordset will be created
  + resource "google_dns_record_set" "resource-recordset" {
      + id           = (known after apply)
      + managed_zone = "my-zone"
      + name         = "test-record.my-zone.hashicorptest.com."
      + project      = (known after apply)
      + rrdatas      = []
      + ttl          = 86400
      + type         = "AAAA"
    }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I think the source of this issue has to do with a change when deleting `resource_dns_record_set.go` and the new [resource_dns_resource_dns_record_set.go](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_dns_resource_dns_record_set.go#L91).

In the new version, the `DiffSuppressFunc` was moved from per-element to the [whole schema](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_dns_resource_dns_record_set.go#L91), which for `TypeList` results in [DiffSuppressFunc](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/schema.go#L971) running on every element due to the way that attributes are expanded into enumerated keys (`rrdatas.0`, `rrdatas.1`).

DiffSuppressFunc also ends up running on the housekeeping value `rrdatas.#` that is required for the [differ to detect a value at all](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/field_reader.go#L173), which ultimately runs the `ipv6AddressforDnsDiffSuppress` function, which converts "0" and "N" into nil pointers, ultimately considering them equal and omitting the `rrdatas.#` feel from the final diff map.

It is debatable that this is a bug with the terraform-plugin-sdk itself: you probably want to run diff suppression some other way where the array diff is computed, then calculating the final length if the field still exists.

### References

* N/A.

**Comment by edwardmedia** [comment]
`rrdates` is empty in the plan but it does send the data to api. The [tests](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=180377&buildTypeId=GoogleCloud_ProviderGoogleCloudMmUpstream&tab=testsInfo) cover the case and they were succeeded. Locally `tf apply` test is fine

**Comment by edwardmedia** [comment]
It looks like currently DiffSuppressFunction doesn't work on TypeList & TypeMap yet

https://github.com/hashicorp/terraform-plugin-sdk/issues/477

**Comment by toumorokoshi** [comment]
It does a tiny bit, see [this comment qualifying things](https://github.com/hashicorp/terraform-plugin-sdk/issues/477#issuecomment-824219102).

It does make some diff suppression use cases impossible though.
