### ISSUE TITLE
Flakey tests: project billing or API enablement

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#8938]
### Affected Resource(s)

* google_*

Some tests can be flakey due to the delay before billing or an API are done getting enabled for a project.  They fail with an error like:

> If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Although this can sometimes resolve with a re-run it would be better to not have this failure case, especially since it compounds for resources that require multiple APIs and/or billing enabled at once. It would be great if we could address the root cause, though I'm not exactly sure how we would do that.

An incomplete list of impacted tests:
- [TestAccProviderUserProjectOverride](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182733?buildTab=tests&status=failed&expandedTest=-2651359853968618908)
- [TestAccProviderIndirectUserProjectOverride](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182733?buildTab=tests&status=failed&expandedTest=-644959833650203088)
- [TestAccActiveDirectoryDomain_update](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/182558?buildTab=tests&pager.currentPage=1&expandedTest=7699655873097682585&name=TestAccActiveDirectoryDomain&status=failed)
- [TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/182558?buildTab=tests&pager.currentPage=1&expandedTest=4638123434893120962&name=TestAccActiveDirectoryDomain&status=failed)
- [TestAccComputeInstanceTemplate_subnet_xpn](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182538?buildTab=tests&name=xpn&pager.currentPage=1&expandedTest=3174955086040473595)
- [TestAccApigeeInstanceAttachment_apigeeInstanceAttachmentBasicTestExample](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182538?buildTab=tests&name=TestAccApigeeInstanceAttachment_apigeeInstanceAttachmentBasicTestExample&pager.currentPage=1&expandedTest=-1088947708178477728)
- [TestAccApigeeInstance_apigeeInstanceBasicTestExample](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182538?buildTab=tests&name=TestAccApigeeInstance_apigeeInstanceBasicTestExample&pager.currentPage=1&expandedTest=4392393421630202833)
- [TestAccComposerEnvironment_withEncryptionConfig](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/182558?buildTab=tests&name=TestAccComposerEnvironment_withEncryptionConfig&pager.currentPage=1&expandedTest=6159577270595453582)
- [TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/301942?buildTab=tests&expandedTest=-7604319118826038242)
- [TestAccServiceNetworkingPeeredDNSDomain_basic](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/301968?buildTab=tests&expandedTest=6546262587776747437)

**Comment by upodroid** [comment]
For `TestAccComputeInstanceTemplate_subnet_xpn` you can set `auto_create_network` field of `google_project` resource to false to eliminate Compute Engine API enablement failures thanks to the logic in that resource

https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_google_project.go#L180


```
func testAccComputeInstanceTemplate_subnet_xpn(org, billingId, projectName, suffix string) string {
	return fmt.Sprintf(`
resource "google_project" "host_project" {
  name            = "Test Project XPN Host"
  project_id      = "%s-host"
  org_id          = "%s"
  billing_account = "%s"
}

// This is redundant now
resource "google_project_service" "host_project" {
  project = google_project.host_project.project_id
  service = "compute.googleapis.com"
}

resource "google_compute_shared_vpc_host_project" "host_project" {
  project = google_project_service.host_project.project
}

resource "google_project" "service_project" {
  name            = "Test Project XPN Service"
  project_id      = "%s-service"
  org_id          = "%s"
  billing_account = "%s"
}

// This is redundant now
resource "google_project_service" "service_project" {
  project = google_project.service_project.project_id
  service = "compute.googleapis.com"
}

resource "google_compute_shared_vpc_service_project" "service_project" {
  host_project    = google_compute_shared_vpc_host_project.host_project.project
  service_project = google_project_service.service_project.project
}

resource "google_compute_network" "network" {
  name                    = "network-%s"
  auto_create_subnetworks = false
  project                 = google_compute_shared_vpc_host_project.host_project.project
}

resource "google_compute_subnetwork" "subnetwork" {
  name          = "subnetwork-%s"
  ip_cidr_range = "10.0.0.0/24"
  region        = "us-central1"
  network       = google_compute_network.network.self_link
  project       = google_compute_shared_vpc_host_project.host_project.project
}

data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_instance_template" "foobar" {
  name         = "instance-test-%s"
  machine_type = "e2-medium"
  region       = "us-central1"

  disk {
    source_image = data.google_compute_image.my_image.self_link
    auto_delete  = true
    disk_size_gb = 10
    boot         = true
  }

  network_interface {
    subnetwork         = google_compute_subnetwork.subnetwork.name
    subnetwork_project = google_compute_subnetwork.subnetwork.project
  }

  metadata = {
    foo = "bar"
  }
  project = google_compute_shared_vpc_service_project.service_project.service_project
}
`, projectName, org, billingId, projectName, org, billingId, suffix, suffix, suffix)
}

```

I would adjust TestAccProvider* tests to use Compute Engine API resources too instead of PubSub

**Comment by circa10a** [comment]
We've seen this on a number of resources which causes our terraform provisions to fail intermittently. It would be a tremendous help if the provider was conscious of enabling these api's and polled for their enablement properly.

**Comment by mitj04** [comment]
b/261374130

**Comment by roaks3** [comment]
I believe this is resolved, but please reopen if I have that wrong. I was not able to find any test failures for these tests due to APIs being disabled, and moving forward, I think we will want to solve this by ensuring that our environment has all necessary APIs enabled prior to tests being run, ie. https://github.com/GoogleCloudPlatform/magic-modules/pull/7196.
