### ISSUE TITLE
How to import google_bigquery_data_transfer_config ?

### ISSUE THREAD

**Issue by norbjd** [hashicorp/terraform-provider-google#8944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/google v3.64.0
```

### Affected Resource(s)

* google_bigquery_data_transfer_config

### Terraform Configuration Files

```tf
resource "google_bigquery_data_transfer_config" "my_scheduled_query" {}
```

### Expected Behavior

```
PROJECT_ID=my-gcp-project
CONFIG_ID=30f3d41c-334a-45be-9f7a-c88187c16ace 

terraform import google_bigquery_data_transfer_config.my_scheduled_query projects/$PROJECT_ID/locations/europe/transferConfigs/$CONFIG_ID
```

should import my existing scheduled query successfully.

### Actual Behavior

```
Error: project: required field is not set
```

### Steps to Reproduce

```
terraform import google_bigquery_data_transfer_config.my_scheduled_query projects/$PROJECT_ID/locations/europe/transferConfigs/$CONFIG_ID
```

[From the docs about bigquery_data_transfer_config import](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#import), it seems that `{{name}}` is the resource name. I've also tried to import with the 2nd argument equal to `name of my scheduled query` or `my-gcp-project/name of my scheduled query` but none of them works.

If that can help, the code relative to the import is here :

https://github.com/hashicorp/terraform-provider-google/blob/e0962381982b27970b152ca8d9fc8661144d9b5e/google/resource_bigquery_data_transfer_config.go#L618

How can I import successfully a resource of type `google_bigquery_data_transfer_config` ?

Thanks :)

**Comment by edwardmedia** [comment]
@norbjd can you try below command like below? Replacing both <project_number> with the project numeric number and the transferConfig id. 

> tf import google_bigquery_data_transfer_config.query_config projects/<project_number>/locations/asia-northeast1/transferConfigs/6078232e-0000-2d17-b67e-94eb2c181dxx

**Comment by norbjd** [comment]
@edwardmedia thanks for your answer.

I've tried your command and got the error:

```
Error: project: required field is not set
```

So I've tried to import like this (double quotes are important):

> terraform import google_bigquery_data_transfer_config.my_scheduled_query "<project_name> projects/<project_number>/locations/europe/transferConfigs/6078232e-0000-2d17-b67e-94eb2c181dxx"

And succeeded to import the resource ! I believe that the documentation is incorrect (name is not enough), or maybe I'm missing something.

**Comment by edwardmedia** [comment]
@norbjd if you run `terraform show`, you should be able to inspect the attributes. Both `id` and `name` should be the one you used in your command. Am I right?

**Comment by norbjd** [comment]
Yes I can see both `id` and `name` (they are equal: `projects/<project_number>/locations/europe/transferConfigs/6078232e-0000-2d17-b67e-94eb2c181dxx`).

But I cannot import using this `id` or `name`: `terraform import google_bigquery_data_transfer_config.my_scheduled_query {{id}}` or `terraform import google_bigquery_data_transfer_config.my_scheduled_query {{name}}` both return:

```
Error: project: required field is not set
```

**Comment by edwardmedia** [comment]
@norbjd `{{id}}` and `{{name}}` are placeholders. You need to provide the data for them. You may find similar ones across the entire provider document. We need to provide the resource identifier so Terraform import knows what resource you want to import. What suggestion do you have if we don't use this format?

**Comment by norbjd** [comment]
Yes I know that `{{id}}` and `{{name}}` are placeholders :smile: 

I don't understand your question, sorry. My problem is that the following command, from the docs:

> terraform import google_bigquery_data_transfer_config.my_scheduled_query projects/<project_number>/locations/europe/transferConfigs/6078232e-0000-2d17-b67e-94eb2c181dxx

does not work, but this one:

> terraform import google_bigquery_data_transfer_config.my_scheduled_query "<project_name> projects/<project_number>/locations/europe/transferConfigs/6078232e-0000-2d17-b67e-94eb2c181dxx"

works. I have personally no problem anymore, but I think documentation should be updated, because `<project_name>` is necessary.

**Comment by edwardmedia** [comment]
@norbjd have you set a default `Project` like [GOOGLE_PROJECT](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project) on your machine? If not, yes you do need to provide the project_name in the command. It is the behavior across the board, not specific to this import. You may try out to see the results. Closing this issue then. Feel free to reopen if that does not work for you.
