### ISSUE TITLE
Google Cloud Run - Metadata annotations not being applied...at all?

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/terraform-provider-google#8945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`0.15.0`

### Affected Resource(s)

 - `google_cloud_run_service`

### Terraform Configuration Files

```terraform
  // ...

resource "google_cloud_run_service" "myservice" {

  depends_on = [
    google_project_service.run_api
  ]

  name = "myservice"
  location = var.region

  template {
    spec {

      service_account_name = google_service_account.myservice.email

      containers {

        image = "gcr.io/myproject/myservice:1.19.8-gcloud"

        ports {
          container_port = 9011
        }

        resources {
          limits = {
            memory = "512Mi"
          }
          requests = {
            memory = "512Mi"
          }
        }
      }
    }
  }

  traffic {
    percent = 100
    latest_revision = true
  }

  metadata {
    annotations = {
      "autoscaling.knative.dev/minScale" = 1
      "run.googleapis.com/cloudsql-instances" = google_sql_database_instance.global.connection_name
    }
  }
}

  // ...
```

### Expected Behavior

When I do a fresh creation or new revision of a Cloud Run service, I expect the above annotations to be applied.

### Actual Behavior

The service is created without a configuration for Cloud SQL and without the minimum instances setting applied.

### Steps to Reproduce

Create any new service similar to above.

### Important Factoids

It seems like the settings just aren't making it through to where they need to go.

**Comment by edwardmedia** [comment]
@atrauzzi can you review the Q & A in https://github.com/hashicorp/terraform-provider-google/issues/8380 to see if that make sense?

**Comment by atrauzzi** [comment]
@edwardmedia - It seems unrelated?  I'm not talking about _changes_.  I'm saying that the annotations I'm trying to provide are simply not being applied?

For example, when I set `run.googleapis.com/cloudsql-instances`, I should be getting a minimum number of instances as 1.  It's staying as the default of 0 when I go to verify the service in the Google Cloud web console.  Even for a brand new service (no revisions).

This seems to have an up to date summary of the values that need to be supported: https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate

**Comment by atrauzzi** [comment]
Ah!  I figured it out!

This metadata section actually belongs under `template`, not under the resource itself!  Yikes!
