### ISSUE TITLE
clone.point_in_time should be optional in google_sql_database_instance?

### ISSUE THREAD

**Issue by sshota0809** [hashicorp/terraform-provider-google#8954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.64.0
+ provider registry.terraform.io/hashicorp/google-beta v3.64.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "test_pg" {
  provider            = google-beta
  name                = "test-pg-clone"
  clone {
    source_instance_name = "test-pg-original"
  }
}
```

### Debug Output

```
Error: Missing required argument

  on db.tf line 94, in resource "google_sql_database_instance" "test_pg":
  94:   clone {

The argument "point_in_time" is required, but no definition was found.
```

### Expected Behavior

point_in_time should be optional as [document](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#point_in_time) says

### Actual Behavior

The argument "point_in_time" is required.

In source code, it is certainly required.

https://github.com/hashicorp/terraform-provider-google/blob/8a5cd7ddbf537e55dcbe64e87c51a9a40bb58daf/google/resource_sql_database_instance.go#L695

I'm not sure which is correct.

### Steps to Reproduce

1. You don't include `clone.point_in_time` parameter in `.tf` file
1. `terraform apply`

**Comment by edwardmedia** [comment]
It should be optional. The api accepts below payload

```
{
 "cloneContext": {
  "destinationInstanceName": "issue8356-3clone",
 }
}
```
