### ISSUE TITLE
add ability to connect github repository to cloudbuild trigger

### ISSUE THREAD

**Issue by vitdolphin** [hashicorp/terraform-provider-google#8961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I am trying to setup a cloudbuild trigger that would use github enterprise repo and looks like functionality for that does not exist. besides going via UI there is no option to create that connection. we are recreating projects/repos a lot and this manual step is cumbersome and does not allow scalability.

### New or Affected Resource(s)
* google provider 3.64.0

### Potential Terraform Configuration

```tf
resource github_repository "zone_repo" {
  name = "cf-tf-${var.gcp_project_name_zone}-repo"
  description = "zone level repository"
  visibility = "private"
}
resource "google_cloudbuild_trigger" "filename-trigger" {
  project                                = module.project-factory.project_id
  name                                   = "${var.gcp_project_name_zone}-trigger"
  github {
    owner = "owner"
    name = github_repository.zone_repo.name
    push {
      branch = "master"
    }
  }
  substitutions = {
    _CONTAINER_REGISTRY = var.gcp_account_project

  }
  filename                               = "cloudbuild.yaml"
}
```
currently running this code creates the repository but mapping fails: 
Error: Error creating Trigger: googleapi: Error 400: Repository mapping does not exist. Please visit https://console.cloud.google.com/cloud-build/triggers/connect?project=xxxxxxxxxxxxxxxxx to connect a repository to your project

**Comment by megan07** [comment]
Hi @vitdolphin ! I'm sorry you're experiencing this issue. Is it possible to provide us debug logs from what you're seeing? Thanks!

**Comment by megan07** [comment]
Hi @vitdolphin, after looking into this a bit, it looks like this is a manual step you will have to take for now, as there is no way for us to automate it (see [here](https://github.com/hashicorp/terraform-provider-google/issues/1950#issuecomment-540117897)). I'll close this for now, but if you have an idea of how we can automate it, please feel free to open a new issue! Thanks!
