### ISSUE TITLE
boot_disk -> initialize_params block -> add resource_policies field

### ISSUE THREAD

**Issue by rkrv-capco** [hashicorp/terraform-provider-google#8963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When a boot disk (persistent type) is created along with the VM instance, it is not possible to apply resource_policy(for example attaching snapshot_policy) to the disk resource.Currently, I have to manually configure the snapshot policy for the persistent boot disks on GCP.

### Terraform Version

Terraform v0.14.8

### New or Affected Resource(s)

 google_compute_instance

### Potential Terraform Configuration

```tf
resource "google_compute_instance" "db_server" {
  name           = "db-server"
  machine_type   = var.db_machine_type
  can_ip_forward = false
  boot_disk {
    initialize_params {
      image = var.db_image_name
      type  = var.db_disk_type  # pd-balanced
      size  = var.db_disk_size_gb
      **resource_policies = [google_compute_resource_policy.snapshot_policy.self_link]**
    }
  }
  network_interface {
    network    = google_compute_network.vpc.name
    subnetwork = google_compute_subnetwork.subnetwork.name
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#initialize_params

b/359676042

**Comment by osuarez84** [comment]
I am experiencing the same issue with the resource `compute_instance_from_template` and `google_compute_instance_group_manager`. It seems to be related to an issue with the API given back the name of the `resourcePolicy` instead of the complete id. This is the other issue talking about the same:

https://github.com/hashicorp/terraform-provider-google/issues/9260


Is there any workaround here to be able of attach the resource policies to the disks?

**Comment by ggtisc** [comment]
This is a proposal to add a new argument supported for the [boot_disk](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#nested_boot_disk) to manage the resource policies

**Comment by karolgorc** [comment]
Working on a pr supporting disk resource policies on instance
