### ISSUE TITLE
 google_bigquery_dataset_iam_binding dataset_id inconsistency

### ISSUE THREAD

**Issue by derhally** [hashicorp/terraform-provider-google#8967]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.59.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* google_bigquery_dataset_iam_binding

### Terraform Configuration Files

```tf

provider "google" {
  project = "org-main"
  region  = "us-central1"
  zone    = "us-cental1-a"
}

module "log_export" {
  source  = "terraform-google-modules/log-export/google"
  version = "~> 6.0.0"

  log_sink_name           = "org-sink"
  destination_uri         = module.log_destination.destination_uri
  filter                  = "logName:\"logs/cloudaudit.googleapis.com\""
  parent_resource_type    = "organization"
  parent_resource_id      = local.org_id
  unique_writer_identity  = true
  include_children        = true
}

module "log_destination" {
  source  = "terraform-google-modules/log-export/google//modules/bigquery"
  version = "~> 6.0.0"

  project_id               = local.org_log_sink_proj.project_id
  dataset_name             = "org_bq_sink"
  log_sink_writer_identity = module.log_export.writer_identity
}

resource "google_bigquery_dataset_iam_binding" "security_log_viewer" {

  dataset_id = module.log_destination.resource_name
  role       = "roles/bigquery.dataViewer"

  members = [
    "group:security-groupr@foo.com",
  ]
}
```

### Debug Output

Sorry. but I cannot provide full debug output.

When running apply terraform returns with the error

```
Error retrieving IAM policy for Bigquery Dataset org-log-1234/projects/org-log-1234/datasets/org_bq_sink: googleapi: got HTTP response code 404 
```

### Expected Behavior

IAM binding is applied for the dataset successfully.

### Actual Behavior

When setting the `dataset_id` argument of `google_bigquery_dataset_iam_binding`  in the form of `projects/your-project-id/datasets/dataset-id` the project is prepended to the path and terraform apply returns the error 

provider returns the error

```
Error retrieving IAM policy for Bigquery Dataset org-main/projects/org-log-1234/datasets/org_bq_sink: googleapi: got HTTP response code 404 
```

in my case `org-main` is the default provider's project.

When setting the dataset_id to just the name of the dataset, it fails because it uses the "project" set on the default provider.  which doesn't contain the dataset.  The error reported is similar to 

```
Error: Error retrieving IAM policy for Bigquery Dataset org-main/org_bq_sink: googleapi: Error 404: Not found: Dataset org-org-main:org_bq_sink, notFound
```

When managing an organization this requires an aliased provider to be defined and explicitly setting the provider on the google_bigquery_dataset_iam_binding.  

It would be better if the resource worked similar to the other resources where it works with the id being in the form of "projects/your-project-id/datasets/dataset-id` or just `dataset-id`.   This would avoid having to create different instances of providers to workaround the issue.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by megan07** [comment]
Hi @derhally ! I'm so sorry that you're experiencing this issue. I don't see it documented (we'll have to fix that), but I see in the code that you can set `project` on the `google_bigquery_dataset_iam_binding` resource. I tried it locally and it seemed to solve this problem. If this works for you, I will update the documentation to show that option.

Thanks!

**Comment by derhally** [comment]
Ok, will try the project argument.  I didn't see project as a valid argument in the docs.  Thanks !

**Comment by derhally** [comment]
@megan07 thanks I used the project argument and it works as expected.

**Comment by megan07** [comment]
Great! Then I'll close this with the [doc update](https://github.com/GoogleCloudPlatform/magic-modules/pull/4724).
Thanks!
