### ISSUE TITLE
Rewrite PrivateCA to use GA API

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#8979]
In the move to GA, the API has made breaking changes that the Terraform implementation will have to adjust for. For example, the parent URL of Certificate Authority has changed to require a CA pool `/projects/my-project/locations/us-west1/caPools/my-pool/certificates/`

The Beta API will be deprecated and current resources created by it will be deleted. This means we can completely rewrite the implementations without fear of breaking changes.

Thanks to @drebes for providing the relevant information.

### New or Affected Resource(s)

* google_privateca_*
* b/188661552

**Comment by rileykarson** [comment]
One quick note- this API is fairly unique and the "completely rewrite the implementations without fear of breaking changes" isn't a precedent for other resources. Despite having an API with a stability level of beta, the product behaved closer to an alpha, and is something we'd support through the [google-private provider](https://github.com/hashicorp/terraform-provider-google/issues/5935) instead, where we don't have as strict of compatibility expectations.
