### ISSUE TITLE
Monitoring alerting policy is not honoring regex filter

### ISSUE THREAD

**Issue by pavantrue** [hashicorp/terraform-provider-google#8980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.14.8

### Affected Resource(s)

google_monitoring_alert_policy

### Terraform Configuration Files

```
resource "google_monitoring_alert_policy" "gke_nodes_cpu_utilization" {
  display_name = "GKE nodes CPU utilization"
  combiner = "OR"
  conditions {
    display_name = "Condition for GKE nodes CPU utilization"
    condition_threshold {
      filter = "metric.type=\"compute.googleapis.com/instance/cpu/utilization\" AND resource.type=\"gce_instance\" AND metadata.system_labels.instance_group=~\"gke-cluster-1.*\" AND metadata.user_labels.goog-gke-node=\"\"" 
      aggregations {
        alignment_period = "60s"
        per_series_aligner = "ALIGN_MEAN"
        cross_series_reducer = "REDUCE_NONE"
      }
      trigger {
          count = 3
      }
      duration = "60s"
      comparison = "COMPARISON_GT"
      threshold_value = 0.5

    }
  }
```

### Debug Output

I have regex in one of filter conditions i.e `=~` (metadata.system_labels.instance_group=~\"gke-cluster-1.*\") and it fails during apply time with below error message

google_monitoring_alert_policy.gke_nodes_cpu_utilization: Modifying... [id=projects/pp-devcos-origin/alertPolicies/2283190796571016922]

```
Error: Error updating AlertPolicy "projects/pp-devcos-origin/alertPolicies/2283190796571016922": googleapi: Error 400: Field alert_policy.conditions[0].condition_threshold.filter had an invalid value of "metric.type="compute.googleapis.com/instance/cpu/utilization" AND resource.type="gce_instance" AND metadata.system_labels.instance_group=~"gke-cluster-1.*" AND metadata.user_labels.goog-gke-node=""": Could not parse filter "metric.type=\"compute.googleapis.com/instance/cpu/utilization\" AND resource.type=\"gce_instance\" AND metadata.system_labels.instance_group=~\"gke-cluster-1.*\" AND metadata.user_labels.goog-gke-node=\"\""; syntax error at line 1, column 136, token '=~'

  on main.tf line 14, in resource "google_monitoring_alert_policy" "gke_nodes_cpu_utilization":
  14: resource "google_monitoring_alert_policy" "gke_nodes_cpu_utilization" {

```

If i tries to escape it i.e `=\~` it will fail with syntax with below error
```
Error: Invalid escape sequence

  on main.tf line 20, in resource "google_monitoring_alert_policy" "gke_nodes_cpu_utilization":
  20:       filter = "metric.type=\"compute.googleapis.com/instance/cpu/utilization\" AND resource.type=\"gce_instance\" AND metadata.system_labels.instance_group=\~\"gke-cluster-1.*\" AND metadata.user_labels.goog-gke-node=\"\"" 

The symbol "~" is not a valid escape sequence selector.
```

### Expected Behavior

It should have proceeded and apply mentioned filters 

### Actual Behavior

The provider reports error as mentioned above 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by megan07** [comment]
Hi @pavantrue ! I'm sorry you've come across this issue. I've taken a look and I'm wondering if this isn't the syntax the API is looking for. If you take a look here, this is what the filter field is expecting (https://cloud.google.com/monitoring/api/v3/filters#filter_selectors). I think you want to update the filter to be `metadata.system_labels.instance_group=monitoring.regex.full_match(\"gke-cluster-1.*\")`. This seemed to work for me. Please let me know if you're still experiencing issues.

Thanks!

**Comment by pavantrue** [comment]
Thanks much @megan07. Somehow missed above documentation. Mentioned syntax works as expected
