### ISSUE TITLE
Add Support for `adaptiveProtectionConfig`  to `google_compute_security_policy`

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-google#8984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add `adaptiveProtectionConfig` for `google_compute_security_policy`. This is the "adaptive protection" documented:

- https://cloud.google.com/armor/docs/configure-security-policies#using
- API: https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies

### New or Affected Resource(s)

* `google_compute_security_policy`

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "policy" {
  provider = google-beta
  name = var.security_policy

  adaptive_protection_config {
    layer7_ddos_defense_config {
       enable = true
       rule_visibility = "PREMIUM"
     }
  }
}

```

### References

* b/175427442

**Comment by bluemalkin** [comment]
Would love to see this implemented !

**Comment by matty-rose** [comment]
I'm interested in working on this issue - happy to have it assigned to me
