### ISSUE TITLE
Beta: Support for Cloud Build Worker Pools

### ISSUE THREAD

**Issue by carlpett** [hashicorp/terraform-provider-google#8985]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Cloud Build worker pools is available through `gcloud beta` for projects which are part of the preview. Would be great to be able to create them using Terraform!

### New or Affected Resource(s)

* google_cloudbuild_worker_pool

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_worker_pool" "my-pool" {
  name = "my-pool"
  region = "us-central1"

  # Optional
  peered_network = "projects/my-project/global/networks/my-network" # Default un-peered
  disable_public_ip = True # Default false
  worker_machine_type = "e2-medium"
  worker_machine_disk_size = "100G"
}
```

### References

* b/182597571

**Comment by rileykarson** [comment]
Note: this is / will be available in the DCL

**Comment by carlpett** [comment]
Great, but, eh, what is the DCL? :sweat_smile:

**Comment by rileykarson** [comment]
Notes that I add to issues are generally during a team triage meeting so I don't completely flesh out the details, sorry about that! The DCL ('declarative client library') is https://github.com/GoogleCloudPlatform/declarative-resource-client-library, a client library for declarative tooling like TF which substantially simplifies the implementation of new resources.

**Comment by carlpett** [comment]
Oh, okay, thanks for the explanation!
