### ISSUE TITLE
scaling_schedule in regional autoscaller not working when min_required_replicas = 0 is set

### ISSUE THREAD

**Issue by MikeMoore63** [hashicorp/terraform-provider-google#8993]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### google_compute_region_autoscaler - beta

* google_compute_region_autoscaler

### Terraform Configuration Files

```
resource "google_compute_region_autoscaler" "scheduled_scale" {
  provider = google-beta.beta_deploy_provider
  name = "repobridge-scaler"
  depends_on = [
  google_compute_region_instance_group_manager.buildbridge-instance-group-manager]
  target = google_compute_region_instance_group_manager.buildbridge-instance-group-manager.id
  region = var.region


  autoscaling_policy {
    max_replicas = 1
    min_replicas = 1
    cooldown_period = 60
    cpu_utilization {
      target = 1
    }

    scaling_schedules {
          name = "weekend"
          description = "scale build bridge down at weekends"
          min_required_replicas = 0
          schedule = "0 3 * * SAT"
          duration_sec = 36 * 60 * 60
          time_zone = "UTC"
    }
    scaling_schedules {
          name ="weekday"
          description = "scale build bridge down at weekdays"
          time_zone = "UTC"
          schedule = "0 3 * * MON,TUE,WED,THU,FRI"
          duration_sec = 18 * 60 * 60
          min_required_replicas = 1
    }
  }
}
```

### Expected Behavior

Expected to create auto scaller with schedule connected to mig
### Actual Behavior

Error: Error creating RegionAutoscaler: googleapi: Error 400: Required field 'resource.autoscalingPolicy.scalingSchedules.key' not specified, required

In the api call you can see terraform generted an api call like this

'''

    2021-04-25T13:47:50.603+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:50 [DEBUG] Creating new RegionAutoscaler: map[string]interface {}{"autoscalingPolicy":map[string]interface {}{"coolDownPeriodSec":60, "cpuUtilization":map[string]interface {}{"utilizationTarget":1}, "maxNumReplicas":1, "minNumReplicas":1, "mode":"ON", "scalingSchedules":map[string]interface {}{"weekday":map[string]interface {}{"description":"scale build bridge down at weekdays", "durationSec":64800, "minRequiredReplicas":1, "schedule":"0 3 * * MON,TUE,WED,THU,FRI", "timeZone":"UTC"}, "weekend":map[string]interface {}{"description":"scale build bridge down at weekends", "durationSec":129600, "schedule":"0 3 * * SAT", "timeZone":"UTC"}}}, "name":"repobridge-scaler", "region":"projects/xxxxxx/global/regions/europe-west1", "target":"projects/*******/regions/europe-west1/instanceGroupManagers/gce-europe-west1-b-d-repobridge"}: timestamp=2021-04-25T13:47:50.603+0100
2021-04-25T13:47:50.603+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:50 [DEBUG] Waiting for state to become: [success]: timestamp=2021-04-25T13:47:50.603+0100
2021-04-25T13:47:50.604+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:50 [DEBUG] Retry Transport: starting RoundTrip retry loop: timestamp=2021-04-25T13:47:50.604+0100
2021-04-25T13:47:50.604+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:50 [DEBUG] Retry Transport: request attempt 0: timestamp=2021-04-25T13:47:50.604+0100
2021-04-25T13:47:50.604+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:50 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /compute/beta/projects/xxxxxx/regions/europe-west1/autoscalers?alt=json HTTP/1.1
Host: compute.googleapis.com
User-Agent: Terraform/0.12.26 (+https://www.terraform.io) Terraform-Plugin-SDK/2.4.2 terraform-provider-google-beta/dev
Content-Length: 666
Content-Type: application/json
Accept-Encoding: gzip

{
 "autoscalingPolicy": {
  "coolDownPeriodSec": 60,
  "cpuUtilization": {
   "utilizationTarget": 1
  },
  "maxNumReplicas": 1,
  "minNumReplicas": 1,
  "mode": "ON",
  "scalingSchedules": {
   "weekday": {
    "description": "scale build bridge down at weekdays",
    "durationSec": 64800,
    "minRequiredReplicas": 1,
    "schedule": "0 3 * * MON,TUE,WED,THU,FRI",
    "timeZone": "UTC"
   },
   "weekend": {
    "description": "scale build bridge down at weekends",
    "durationSec": 129600,
    "schedule": "0 3 * * SAT",
    "timeZone": "UTC"
   }
  }
 },
 "name": "repobridge-scaler",
 "region": "projects/xxxxxx/global/regions/europe-west1",
 "target": "projects/xxxxxx/regions/europe-west1/instanceGroupManagers/gce-europe-west1-b-d-repobridge"
}

-----------------------------------------------------: timestamp=2021-04-25T13:47:50.604+0100
2021-04-25T13:47:53.359+0100 [INFO]  plugin.terraform-provider-google-beta_v3.55.0_x5: 2021/04/25 13:47:53 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 25 Apr 2021 12:47:53 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

14b
{
  "error": {
    "code": 400,
    "message": "Required field 'resource.autoscalingPolicy.scalingSchedules.key' not specified",
    "errors": [
      {
        "message": "Required field 'resource.autoscalingPolicy.scalingSchedules.key' not specified",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
'''

### Steps to Reproduce

Create any scaling auto mig with a scaling_schedule

1. `terraform apply`

### References

https://cloud.google.com/compute/docs/reference/rest/beta/regionAutoscalers/get

* #0000

**Comment by edwardmedia** [comment]
@MikeMoore63 there is a test (below) that works fine. Can you compare the differences?

https://github.com/hashicorp/terraform-provider-google-beta/blob/6d7bc1f340997d3b233cc59152845ffddcb840f6/google-beta/resource_compute_region_autoscaler_test.go#L256

**Comment by MikeMoore63** [comment]
JUst created using gcloud and all worked fine but log looked similar so puzzled as to 

> @MikeMoore63 there is a test (below) that works fine. Can you compare the differences?
> 
> https://github.com/hashicorp/terraform-provider-google-beta/blob/6d7bc1f340997d3b233cc59152845ffddcb840f6/google-beta/resource_compute_region_autoscaler_test.go#L256

Ok so played around with this it only errors when min_required_replicas = 0.

Using gcloud/console I can set to 0.

**Comment by MikeMoore63** [comment]
A work around for this is set min_replicas in outer resource to 0 and just scale up which works. This as docs state after duration is passed reverts to default behavior.
