### ISSUE TITLE
add support version_retention_period with google_spanner_database

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#8994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to set the PITR (version_retention_period) of Spanner Database using Terraform.

The version_retention_period of Spanner Database is output-only with the REST API, and I need to use updateDdl and `ALTER DATABASE` to set it.
If google_spanner_database implements the logic to be set by updateDdl, it is very useful because the setting is completed only by Terraform.

### New or Affected Resource(s)

* google_spanner_database

### Potential Terraform Configuration

```tf
resource "google_spanner_database" "sample" {
  instance                 = "sample"
  name                     = "sample-pitr"
  version_retention_period = "7d" 
}
```

### References

* https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases
* https://cloud.google.com/spanner/docs/use-pitr#go

**Comment by BenCoughlan15** [comment]
Would really appreciate this one. 

Is it something we can contribute towards?

**Comment by BenCoughlan15** [comment]
Still no movement on this, can I add a PR for this?

**Comment by marktru** [comment]
@BenCoughlan15 - Hi Ben, yes you can certainly create a PR if you are still interested!
