### ISSUE TITLE
google_logging_metric should be recreated when renaming label

### ISSUE THREAD

**Issue by Evesy** [hashicorp/terraform-provider-google#9000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.6

### Affected Resource(s)

* google_logging_metric

### Terraform Configuration Files

```tf
resource "google_logging_metric" "host_error" {
  name        = "compute/host_errors"
  description = "Counter for  VM instances that have hostError's"
  filter      = "resource.type=gce_instance AND protoPayload.methodName=compute.instances.hostError"
  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    labels {
      key         = "instance"
      value_type  = "STRING"
      description = "Hostname of instance"
    }
    labels {
      key         = "zone"
      value_type  = "STRING"
      description = "Availability zone of instance"
    }
    display_name = "VM Host Errors"
  }
  label_extractors = {
    "instance" = "REGEXP_EXTRACT(protoPayload.resourceName, \"projects/.+/zones/.+/instances/(.+)\")"
    "zone"     = "EXTRACT(resource.labels.zone)"
  }
}
```

### Expected Behavior

The resource should be wholly recreated if one of the label names is changed, due to the limitations outlined in https://cloud.google.com/logging/docs/logs-based-metrics/labels
`A label can't be deleted after it is created`

### Actual Behavior

When I changed one of the label names (`instance` -> `instance_name`) the Terraform diff was as below:

```tf
# google_logging_metric.host_error will be updated in-place
  ~ resource "google_logging_metric" "host_error" {
        id               = "compute/host_errors"
      ~ label_extractors = {
          - "instance"      = "REGEXP_EXTRACT(protoPayload.resourceName, \"projects/.+/zones/.+/instances/(.+)\")" -> null
          + "instance_name" = "REGEXP_EXTRACT(protoPayload.resourceName, \"projects/.+/zones/.+/instances/(.+)\")"
            # (1 unchanged element hidden)
        }
        name             = "compute/host_errors"
        # (3 unchanged attributes hidden)

      ~ metric_descriptor {
            # (4 unchanged attributes hidden)

          - labels {
              - description = "Hostname of instance" -> null
              - key         = "instance" -> null
              - value_type  = "STRING" -> null
            }
          + labels {
              + description = "Hostname of instance"
              + key         = "instance_name"
              + value_type  = "STRING"
            }
            # (1 unchanged block hidden)
        }
    }
```

This resulted in the below error when applying the plan:

```
google_logging_metric.host_error: Modifying... [id=compute/host_errors]
Error: Error updating Metric "compute/host_errors": googleapi: Error 400: Cannot delete existing label: instance
```

### Steps to Reproduce

1. Create resources as listed above
2. Rename one of the labels
3. Plan & apply

**Comment by edwardmedia** [comment]
@Evesy from the plan, it shows `update`, not `recreate`. Also the error is from api. Looks like it does not allow you to `delete existing label` as you tried to update the `key`. You may try to update `description` to see what happens.

**Comment by edwardmedia** [comment]
It looks like api does not allow updating the label.keys
