### ISSUE TITLE
google_access_context_manager_access_level errors with managing an existing access level

### ISSUE THREAD

**Issue by keeleysam** [hashicorp/terraform-provider-google#9003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.9

### Affected Resource(s)

* google_access_context_manager_access_level

### Terraform Configuration Files

```tf
resource "google_access_context_manager_access_level" "ios_os_policy" {
  parent = "accessPolicies/1234567890"
  name   = "accessPolicies/1234567890/accessLevels/ios_os_policy"
  title  = "ios_os_policy"
  custom {
    expr {
      expression = "device.os_type == OsType.IOS && device.versionAtLeast('14.5.0')"
    }
  }
}
```

### Expected Behavior

In this case, `accessPolicies/1234567890/accessLevels/ios_os_policy` already exists and was created through outside of Terraform but is now going to be managed with Terraform.  The expected behavior is that Terraform reads the existing true state from the ACM API and is able to update the existing level.

### Actual Behavior

Terraform doesn't know that the access level already exists, so it calls create instead of patch when applying and gets an error from the API:

```
Terraform v0.14.9
Initializing plugins and modules...
google_access_context_manager_access_level.ios_os_policy: Creating...

Error: Error creating AccessLevel: googleapi: Error 409: Level 'accessPolicies/1234567890/accessLevels/ios_os_policy' already exists and cannot be created.

  on main.tf line 3, in resource "google_access_context_manager_access_level" "ios_os_policy":
   3: resource "google_access_context_manager_access_level" "ios_os_policy" {

```

### Steps to Reproduce

1. Create an access level outside of Terraform
2. Attempt to manage it with Terraform

### Important Factoids

The provider already supports reading state from the ACM API and doesn't rely on the Terraform state file to monitor the contents of an access level.  For example, if one creates an access level with Terraform, then updates it outside of Terraform, a subsequent plan will detect that there are changes which need to be made.

Of course, managing preexisting resources with Terraform may not always be supported, but when migrating many access levels to be managed this way its really needed to be able to do so without hacking up a fake state file or causing major disruption by deleting access levels and recreating them.

This wouldn't be an issue with the `google_access_context_manager_access_levels` resource as it purges existing access levels, but we need to continue managing some access levels outside of Terraform.

### References

https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.accessLevels/create
https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.accessLevels/patch
* #0000

**Comment by venkykuberan** [comment]
@keeleysam its not required to use fake state file, You can import the resource (created outside of terraform) first and then have terraform manage the resource. Terraform will have the latest state of the resource once you import it and then it will call Update method instead for Create method (unless you change any ForceNew fields) on any changes in the config

doc
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_access_level#import

**Comment by edwardmedia** [comment]
No response. Assume it is no longer an issue
