### ISSUE TITLE
google_dns_record_set: AAAA record broken since v3.64.0

### ISSUE THREAD

**Issue by freddd** [hashicorp/terraform-provider-google#9014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
{
  resource: {
    google_dns_record_set: {
      'id': {
        project: 'project',
        name: 'name',
        managed_zone: ''zone',
        type: 'AAAA',
        ttl: 300,
        rrdatas: ['ip'],
      }
    }
  }
}
```

### Expected Behavior

To be able to create AAAA records:
```
  + resource "google_dns_record_set" "<id>" {
      + id           = (known after apply)
      + managed_zone = "<zone>"
      + name         = "<name>"
      + project      = "<project>"
      + rrdatas      = ["<ip>"]
      + ttl          = 300
      + type         = "AAAA"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

The rrdatas is empty and thus the record cannot be created:
```
  + resource "google_dns_record_set" "<id>" {
      + id           = (known after apply)
      + managed_zone = "<zone>"
      + name         = "<name>"
      + project      = "<project>"
      + rrdatas      = []
      + ttl          = 300
      + type         = "AAAA"
    }
```
For now we've solved it by downgrading to `v3.63.0`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@freddd  closing this as it is a dup https://github.com/hashicorp/terraform-provider-google/issues/8935
Below PR has been opened. Hopefully this can be resolved. 

https://github.com/GoogleCloudPlatform/magic-modules/pull/4725
