### ISSUE TITLE
terraform-provider-google_v3.66.0_x5 plugin crashed

### ISSUE THREAD

**Issue by dieseldesai** [hashicorp/terraform-provider-google#9022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.66.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
  required_version = ">= 0.14.11"
}

provider "google" {
  project = var.project
  region  = var.region
  zone    = var.zone
}

variable "project" {
  type        = string
  description = "The GCP project to build the instance into"
}

variable "region" {
  type        = string
  description = "The GCP region to build the instance into"
  default = "us-central1"
}

variable "zone" {
  type        = string
  description = "The GCP zone to build the instance into"
  default = "us-central1-a"
}

variable "uid" {
  description = "Unique identifier"
  type = string
}

resource "google_compute_instance" "node" {
  name             = var.uid
  machine_type     = "n1-standard-8"
  min_cpu_platform = "Intel Haswell"

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-minimal-2004-focal-v20201211"
      type = "pd-ssd"
      size = 250
    }
  }

  network_interface {
    subnetwork="default"
    access_config {
    }
  }


  metadata = {
    enable-guest-attributes = true
  }

  tags = [var.uid]

  service_account {
    scopes = ["cloud-platform"]
  }
}

```

### Debug Output

https://gist.github.com/dieseldesai/4f785a8da23b847165dc8eb04cab4c7c

### Expected Behavior

A google compute instance should have been provisioned

### Actual Behavior

the terraform google provider plugin crashed

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by jvlake** [comment]
The same issue as above but with terraform 0.12.31 (upgrading due to public key invalidation).

**Comment by rcaril** [comment]
Same issue on TFE .13.7 with this latest updatge:

```
2021-04-29T13:34:56.830Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-29T13:34:56.830Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/google/3.66.0/linux_amd64/terraform-provider-google_v3.66.0_x5 pid=253 error="exit status 2"
2021/04/29 13:34:56 [ERROR] eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
2021/04/29 13:34:56 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
```

**Comment by harroguk** [comment]
Same as @rcaril but in Terraform v0.13.5
Tested and it is working in terraform-provider-google_v3.65

**Comment by rcaril** [comment]
@megan07 - this code fix did not fix the problem. Same behavior.

**Comment by megan07** [comment]
Hi @rcaril, I'm sorry you're experiencing the issue still. Would you be willing to share your configuration and your full debug logs so I can see what is happening? Thanks!

**Comment by rcaril** [comment]
@megan07 My log is attached. 

[run-mwzH4qRFxRLhDV4v-plan-log.txt](https://github.com/hashicorp/terraform-provider-google/files/6400102/run-mwzH4qRFxRLhDV4v-plan-log.txt)

What kind of configuration are you looking for? 

This is my initial setup:

```
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.66.0"
    }
  }
  backend "remote" {
    hostname     = "########"
    organization = "#####"
    workspaces {
      name = "######"
    }
  }
}
```
Please let me know if you need more details.

**Comment by aareet** [comment]
Thank you for the quick response @rcaril, I think there might be a small misunderstanding. The fix for this bug was recently merged and is still in the process of being released. From the configuration, it seems that you may still be using a version (3.66.0) that does not have this fix. The issue gets closed automatically when a fix is merged, which probably caused this confusion. Sorry about that. We are working to get this fix out in a release as soon as possible.

**Comment by rcaril** [comment]
Hi @aareet - thanks for clarifying this! I indeed did not realize that the merge would not go into your release automatically. Please keep me updated on when this has been released. Would I expect this to be version 3.67?

**Comment by aareet** [comment]
Glad we figured it out 🙂. I will certainly update this ticket once we release. We're currently expecting this to be version 3.66.1, but I will confirm once we release.

**Comment by rcaril** [comment]
@aareet This has solved my problem, thanks!
