### ISSUE TITLE
Support for Cloud SQL Query Insights

### ISSUE THREAD

**Issue by dhinakar2707** [hashicorp/terraform-provider-google#9024]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

Hi Team,

Please can someone help me if Cloud SQL Query Insights has support/available in terraform 0.12 version?

Your help is much appriciated.

Thanks,
Dhinakar

**Comment by venkykuberan** [comment]
Yes we are supporting it from provider version `v.3.58.0`. Please refer this doc https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance
