### ISSUE TITLE
GPG validation of recent release fails inspection

### ISSUE THREAD

**Issue by essjayhch** [hashicorp/terraform-provider-google#9025]
Following the latest release of 3.66.0, Terraform 0.12.28 is failing to accept the google-beta module due to the following error
```
Error verifying GPG signature for provider "google-beta"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

**Comment by essjayhch** [comment]
I'm guessing this is somehow related to #9022 , but it's not the same issue specifically.

**Comment by curtbushko** [comment]
@essjayhch You might want to re-open this issue as I am seeing the same thing.
