### ISSUE TITLE
Terraform doesn't retry 504 Gateway Timeout from GCS

### ISSUE THREAD

**Issue by drigz** [hashicorp/terraform-provider-google#9026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.12.31, google provider v3.66

### Affected Resource(s)

* google_storage_bucket

### Expected Behavior

When the API returns a 504, terraform retries it.

### Actual Behavior

```
Error when reading or editing Storage Bucket "my-bucket": googleapi: Error 504: , gatewayTimeout
```

### Steps to Reproduce

1. Use terraform to create a GCS bucket.
1. `terraform apply`
1. (very rarely, only happened for me once) Observe the 504 error.

### References

* https://cloud.google.com/storage/docs/json_api/v1/status-codes#504_Gateway_Timeout

**Comment by venkykuberan** [comment]
@drigz This issue is on the API side, provider have no control of it. I am closing this now. Please reopen when you get the error next time with the debug log attached.
