### ISSUE TITLE
Cloud Composer Environment (max-pods-per-node)

### ISSUE THREAD

**Issue by reaVen-** [hashicorp/terraform-provider-google#9028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

cloud_composer_environment creates an underlying GKE kubernetes cluster, i would like to be able to override the max-pods-per-node configuration. This is already possible when creating the composer cluster via gcloud tools

### New or Affected Resource(s)

* google_composer_environment node_config.max_pods_per_node

**Comment by ggtisc** [comment]
Hi @reaVen-!

Currently the [max_pods_per_node](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment#max_pods_per_node) exists to achieve this objective
