### ISSUE TITLE
Change url for ressources dns_record_set

### ISSUE THREAD

**Issue by mBouamama** [hashicorp/terraform-provider-google#9040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Change url: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_resource_dns_record_set
to https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set

### New or Affected Resource(s)

* google_dns_record_set

## Resoltion
Rename this file: https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/dns_resource_dns_record_set.html.markdown

to dns_record_set.html.markdown

### References

* #0000

**Comment by rileykarson** [comment]
Note: I think that this is due to the `legacy_name` field in MMv1 not getting used in the filename.
