### ISSUE TITLE
google_compute_snapshot - Snapshot cannot be created for Regional disks (google_compute_region_disk)

### ISSUE THREAD

**Issue by maheshwara-bwd** [hashicorp/terraform-provider-google#9043]
Hi team,

I was not able to create a Snapshot for Regional disks created with **google_compute_region_disk**.

google_compute_snapshot is not able to find the source disk for Regional disks as it is specifically searching for a disk inside **project/<project_name>/zones/<zone_name>/disks/<disk_name>** while regional disks are created inside **project/<project_name>/regions/<region_name>/disks/<disk_name>**

Also, **zone** is a mandatory attribute now. Is that really intended?

Please check the screenshot attached below:
1. Cannot find regional disk which was created in the previous step
![image](https://user-images.githubusercontent.com/48576526/116733887-4b05d380-aa0a-11eb-9ab0-8728cc057791.png)
2. Zone is mandatory
![image](https://user-images.githubusercontent.com/48576526/116733560-df236b00-aa09-11eb-8865-8cad446912e2.png)

**Is there any other way of creating a snapshot for a Regional persistent disk or am I missing something? Please help.**

Thanks in advance

**Comment by slevenick** [comment]
This looks related to https://github.com/hashicorp/terraform-provider-google/issues/9053 closing in favor of that one.

I don't believe there is currently a way in Terraform to create snapshots of regional disks, the existing snapshot resource only works on zonal disks as far as I can tell
