### ISSUE TITLE
The referenced disk resource cannot be found

### ISSUE THREAD

**Issue by RobCannon** [hashicorp/terraform-provider-google#9045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/hashicorp/google-beta v3.66.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/invidian/tls v2.2.1

### Affected Resource(s)

* google_compute_instance
* google_compute_disk

### Terraform Configuration Files

```tf
resource "google_compute_disk" "boot_partition" {
  name                      = "${var.instance_name}-boot"
  type                      = "pd-ssd"
  zone                      = var.zone
  physical_block_size_bytes = 4096
  image                     = data.google_compute_image.image.self_link
  size                      = 100
  labels                    = local.labels
}

resource "google_compute_instance" "shell" {
  name         = var.instance_name
  project      = var.project_id
  machine_type = var.machine_type
  zone         = var.zone

  boot_disk {
    source = google_compute_disk.boot_partition.self_link
  }

  metadata = {
    startup-script         = data.template_file.startup_script.rendered
    enable-oslogin         = true
  }

  network_interface {
    subnetwork         = var.subnetwork
    subnetwork_project = var.subnetwork_project_id
    network_ip         = google_compute_address.shell.address
  }

  tags = var.tags

  shielded_instance_config {
    enable_secure_boot = true
  }

  service_account {
    email  = var.service_account
    scopes = ["cloud-platform"]
  }

  labels = local.labels

  lifecycle {
    ignore_changes = [
      attached_disk
    ]
  }

  depends_on = [
    google_compute_disk.boot_partition
  ]
}


```

### Debug Output

Our corporate policy prevents us from using a gist:

Here is the error output:
```
module.equifax_shell.google_compute_instance.shell: Creating...

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].source': 'projects/xxxx/zones/us-east1-b/disks/shell-boot'. The referenced disk resource cannot be found., invalid

  on .terraform/modules/equifax_shell/shell.tf line 35, in resource "google_compute_instance" "shell":
  35: resource "google_compute_instance" "shell" {

```

### Expected Behavior

The new compute instance should be created with the attached disk as the boot drive.

### Actual Behavior

The error occurs, but it is inconsistent.  It occurs about every third run and re-running usually fixes the problem

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This was working find before the latest upgrade to 0.14.1 (and google provider 3.66.1).  I am unable to get this to run on older versions now because of the PGP key change.

### References

I have already looked at this issue.  We are referencing the disk resource so that it should be noticed as a dependency.  I have tried explicitly listing the resource as a dependency and it doesn't change the behavior
https://github.com/hashicorp/terraform-provider-google/issues/3025

* #0000

**Comment by edwardmedia** [comment]
@RobCannon can you share the entire debug log?

**Comment by RobCannon** [comment]
Sorry, when I run with TF_LOG=TRACE, the error doesn't happen. Since I suspect this to be a timing issue, I guess the additional time for the error log to write out is enough time for the disk creation to finish and for the resource to show up from the Google API.  The error still occurred in some of our jobs over the weekend, but I didn't have trace logging setup for the production terraform runs.

**Comment by edwardmedia** [comment]
@RobCannon your code looks fine. Normally timing is not an issue for these resources. One thing I can think of is API may experience issues at that time.  Let's leave the issue open for a few days. Please try to repro the issue so we can take a close look.

**Comment by RobCannon** [comment]
I have set TF_LOG=TRACE on our production jobs and the issue has not come up since.  It was still happening before that change.  I suspect that changing it back will re-introduce the bug.

**Comment by edwardmedia** [comment]
@RobCannon setting `TF_LOG=TRACE` shouldn't change the behavior. If it does, we will need help from the Terraform core to take a look. In term of timing as you suspected, it could be the reason ( I did not see such cases for these resources ). In this case, you may add `sleep` logic between these two resources.

**Comment by RobCannon** [comment]
We are not seeing this issue any more.
