### ISSUE TITLE
google_project_iam_binding returns "Request contains an invalid argument"

### ISSUE THREAD

**Issue by yorix20** [hashicorp/terraform-provider-google#9050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/hashicorp/google-beta v3.66.1
```

### Affected Resource(s)

* [google_project_iam_binding](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_binding)

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
        source = "hashicorp/google"
        version = "3.66.1"
    }
  }
}

provider "google" {
  credentials = file("google-creds.json")
  project = "terraform-312509"
  region = "europe-west3"
  zone = "europe-west3-c"
}

resource "google_service_account" "sa" {
  account_id   = "test-123"
  display_name = "Service Account"
  project = "terraform-312509"
}


resource "google_project_iam_binding" "project" {
  project = "terraform-312509"
  role    = "roles/owner"

  members = [
    "serviceAccount:${google_service_account.sa.email}",
  ]
}
```

### Debug Output

https://gist.github.com/yorix20/80b6bfe205389231792366e0d1669f0a

### Expected Behavior

IAM binding from  project `terraform-312509` to Service Account`serviceAccount:test-123@terraform-312509.iam.gserviceaccount.com`with role `roles/owner`

### Actual Behavior

ERROR:
```
│ Error: Request "Set IAM Binding for role \"roles/owner\" on \"project \\\"terraform-312509\\\"\"" returned error: Error applying IAM policy for project "terraform-312509": Error setting IAM policy for project "terraform-312509": googleapi: Error 400: Request contains an invalid argument., badRequest
│
│   with google_project_iam_binding.project,
│   on main.tf line 24, in resource "google_project_iam_binding" "project":
│   24: resource "google_project_iam_binding" "project" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running the same operation with `gcloud`works:

```
gcloud projects add-iam-policy-binding terraform-312509 \
    --member="serviceAccount:test-123@terraform-312509.iam.gserviceaccount.com" \
    --role="roles/owner"
```

**Comment by edwardmedia** [comment]
@yorix20 how did you create the credential file? Since you are working on `project` level resources, does the account used in the credential file have `org` level privilege?

**Comment by yorix20** [comment]
Hi @edwardmedia,

Thanks for your response.

I added `roles/resourcemanager.organizationAdmin` to the service account but I still get the same error.

Here are the logs from `gcloud`

```
gcloud projects add-iam-policy-binding terraform-312509 \
    --member="serviceAccount:test-123@terraform-312509.iam.gserviceaccount.com" \
    --role="roles/owner" --verbosity=debug
```
https://gist.github.com/yorix20/a462900b157ff8cdc8c0e9168760591b

**Comment by edwardmedia** [comment]
@yorix20 is your `service account` one of below account?
You chose `_binding` resource in your config, which means it will try to replace the below two members with your new one for the `roles/owner`.  As a result, the account `terraform@terraform-312509.iam.gserviceaccount.com` will no longer be an owner on the project. Is that what you want to do?  Instead you may want to try `google_project_iam_member` to see if that works for you.

```
  {
   "role": "roles/owner",
   "members": [
    "serviceAccount:terraform@terraform-312509.iam.gserviceaccount.com",
    "user:IuryAlves20@gmail.com"
   ]
  },
```

>google_project_iam_binding: Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the project are preserved.

**Comment by yorix20** [comment]
Hi @edwardmedia 

I thought `google_project_iam_binding`would append the new binding. Anyways, using `google_project_iam_member`worked.

Thank you very much =)
