### ISSUE TITLE
terraform tries to drop table on partition_expiration_days update

### ISSUE THREAD

**Issue by nirby821** [hashicorp/terraform-provider-google#9056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v0.13.5

### Affected Resource(s)

Google Cloud BigQuery
Currently using provider hashicorp/google-beta

### Terraform Configuration Files

```tf
resource "google_bigquery_table" "support_forms_requests_table" {
  project = some_project
  dataset_id = "some_dataset"
  table_id = "support_forms_requests"
  time_partitioning {
    type = "DAY"
    field = "partition_date"
    require_partition_filter = true
    expiration_ms = 40 * 24 * 60 * 60 * 1000
  }
  # Expiration time of table, null by default as working with partition expiration time
  expiration_time = null
  clustering = []
  labels = {
    billable = "true"
    owner = "waze-data"
  }

  deletion_protection=false

  schema = <<EOF
      ${file("../path/to/schema.json")}
      EOF
}
```

### Debug Output

the log contains sensitive information

```
# google_bigquery_table.attribution_table must be replaced
```

### Expected Behavior

I would expect terraform to update partition_expiration_days in-place and not try to re-create the table

### Actual Behavior

Terraform tries to drop the table on edit of partition_expiration_days in the terraform config file

### Steps to Reproduce

1.  Update partition_expiration_days on an existing table
2.  run `terraform apply`

**Comment by edwardmedia** [comment]
@nirby821 can you share the debug log?

**Comment by edwardmedia** [comment]
@nirby821 is this still an issue?

**Comment by nirby821** [comment]
While invoking this operation on a different table, in order to create logs - I noticed that the change to expiration_ms is done in-place(!), this probably means that there was another reason for which terraform decided to drop the original table. Is there a way to know which operation require that a table to be dropped and which will modify the table in-place? Tnx

**Comment by ScottSuarez** [comment]
set deletion protection to `false` and run terraform plan you should be able to see which field will cause a modify/cause deletion.

**Comment by nirby821** [comment]
Ok, thanks
