### ISSUE TITLE
Throw a validation error when CNAME rrdatas strings don't end with a dot in google_dns_record_set

### ISSUE THREAD

**Issue by openlyDarwin** [hashicorp/terraform-provider-google#9074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Probably applies to more than CNAME record set types, but after a successful `plan` with an `rrdatas` list that includes strings that don't have a trailing dot, an `apply` will fail and throw the following error from the gcloud API:

```
Error: Error creating DNS RecordSet: googleapi: Error 400: Invalid value for 'entity.change.additions[0].rrdata[0]': 'example.rrdatas.list.entry', invalid
```

Seems like something the provider can and should catch during validation.

### New or Affected Resource(s)

* google_dns_record_set

### Potential Terraform Configuration

```tf
# No new config
```

### References

* From [the API docs](https://cloud.google.com/dns/docs/reference/json-record):
  > Note that the hostnames must end with periods or trailing dots (.) in the rrdatas fields to be fully-qualified DNS names.

**Comment by corradomatt** [comment]
I've run into this issue as well.

But I've also run into an issue where creating a CNAME record on a private zone with the trailing dot included results in a DNS record which is not propagated to the network. If I manually create a CNAME record with the same values the record is available in the network immediately. I wonder if this is a bug with the Google API which needs to be addressed with Google or with the Terraform API call.

**Comment by melinath** [comment]
b/237099616

**Comment by NA2047** [comment]
Suggest Closing this issue due to fix being merged in main
