### ISSUE TITLE
Create FrontendConfig resource

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-google#9088]
Would be nice to have a Terraform equivalent of:

```tf
resource "null_resource" "ingress_ssl_config" {
    provisioner "local-exec" {
    command = <<EOT
kubectl create -f - -- <<EOF
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
    name: ingress-frontend-config
    namespace: default
spec:
    redirectToHttps:
        enabled: true
        responseCodeName: MOVED_PERMANENTLY_DEFAULT
    sslPolicy: modern-ssl-policy
EOF
EOT
    }
}
```

**Comment by edwardmedia** [comment]
@hazcod  do you want to create k8s resources? k8s' api is different from what we discuss here which is GCP's apis. If I misunderstood, mind provide the api that supports what you are asking?

**Comment by hazcod** [comment]
@edwardmedia I guess it's a bit of an oddball scenario. In this case the FrontendConfig instruments the GCP external HTTPS load balancers, so are actually part of GCP. But for some reason, it must be instructed from within the Ingress on kubernetes using an annotation to the FrontendConfig.

**Comment by edwardmedia** [comment]
@hazcod have you seen a GCP api that supports it? Please provide the link if so.

**Comment by hazcod** [comment]
I guess this fits under the new kubernetes provider, closing.

**Comment by edwardmedia** [comment]
Yeah that is for k8s provider
