### ISSUE TITLE
Creating google_dns_record_set with rrdatas from google_dns_keys data source causes replacement due to case differences

### ISSUE THREAD

**Issue by MontyD** [hashicorp/terraform-provider-google#9093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/hashicorp/google-beta v3.66.1
```

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
data "google_dns_keys" "project" {
  managed_zone = "managed_zone_id"
}

resource "google_dns_record_set" "project_keys" {
  managed_zone = "target_managed_zone_id"
  project      = "target_project"

  name = "google_dns_managed_zone.project.dns_name"
  type = "DS"
  rrdatas = [
    for ksk in data.google_dns_keys.project.key_signing_keys : ksk.ds_record
  ]
  ttl = 300
}
```

### Expected Behaviour

After initial creation `google_dns_record_set.project_keys` should not be recreated on subsequent applies. 

### Actual Behaviour

On every apply `google_dns_record_set.project_keys` is replaced because the `rrdatas` change case, e.g.:

```
  # google_dns_record_set.project_keys must be replaced
-/+ resource "google_dns_record_set" "project_keys" {
      ~ id           = "projects/test/managedZones/product/rrsets/test.dev.null./DS" -> (known after apply)
        managed_zone = "product"
        name         = "test.dev.null."
        project      = "test"
      ~ rrdatas      = [ # forces replacement
          - "13244 1 1 55sd323sddf323356huku",
          + "13244 1 1 55SD323SDDF323356HUKU",
        ]
        ttl          = 300
        type         = "DS"
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` for a second time and see that the `google_dns_record_set` is recreated.

**Comment by rjw57** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/4769 opened which should fix this
