### ISSUE TITLE
Support for Dataproc on GKE

### ISSUE THREAD

**Issue by forestoden** [hashicorp/terraform-provider-google#9094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Dataproc on GKE is in Beta and it would be nice to add support for it in Terraform. Right now, we would be able to create the GKE cluster with Terraform but then have to manually create the Dataproc cluster on GKE.

https://cloud.google.com/dataproc/docs/concepts/jobs/dataproc-gke

### New or Affected Resource(s)

* google_dataproc_cluster

### Potential Terraform Configuration

```tf
resource "google_dataproc_cluster" "simplecluster" {
  name   = "simplecluster"
  region = "us-central1"

  gke_cluster_config {
    cluster_name = <cluster_name>
  }
}
```

**Comment by forestoden** [comment]
I may have time to work on this soon, but if someone else is interested in picking it up, please do!

**Comment by hoesler4dh** [comment]
Has anyone started with this? @forestoden?
