### ISSUE TITLE
Startup-script is not working on the boot of VM instance (debian 9)

### ISSUE THREAD

**Issue by shailesh-tendolkar** [hashicorp/terraform-provider-google#9109]
Using Terraform I added startup script metadata to install the apache server on the VM instance. After terraform apply it creates everything but that startup script fails to run and I can see that script on the console under custom metadata...On the other hand, if I write the same script on the console it works. I am doing exactly the same thing using console then why it's not working via Terraform?

**Comment by edwardmedia** [comment]
@shailesh-tendolkar can you share your config and debug log?

**Comment by edwardmedia** [comment]
@shailesh-tendolkar is this still an issue?

**Comment by edwardmedia** [comment]
@shailesh-tendolkar closing assuming this is no longer an issue
