### ISSUE TITLE
google_compute_project_metadata_item concurrency issues causing rate limit errors

### ISSUE THREAD

**Issue by ct-dh** [hashicorp/terraform-provider-google#9119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
 user@somehost  ~/code/tf-tests/metadata-concurrencvy  terraform-14 --version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/google v3.67.0

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
user@somehost  ~/code/tf-tests/metadata-concurrencvy 
```

### Affected Resource(s)

* google_compute_project_metadata_item

### Terraform Configuration Files

```tf
provider "google" {
  project     = "private-project"
}

resource "google_compute_project_metadata_item" "version_metadata" {
  count = 15
  key   = format("metadata-concurrency-repo-%d", count.index)
  value = "foo"
}

```

This is not the real code and is just a simple minimal repro (I just used 15 for the count as I was sure it would fail, our real use-case is probably only 8 or so items).

### Panic Output

n/a

### Expected Behavior

All metadata items set in common instance metadata.

### Actual Behavior

Quote/rate limit error:
```
Error: googleapi: Error 403: Quota exceeded for quota group 'ProjectSetCommonInstanceMetadataGroup' and limit 'Project set common instance metadata requests per user per 100 seconds' of service 'compute.googleapis.com' for consumer 'project_number:353363507040'., rateLimitExceeded

  on main.tf line 5, in resource "google_compute_project_metadata_item" "version_metadata":
   5: resource "google_compute_project_metadata_item" "version_metadata" {
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

I think there should be a new mutex added for project level metadata as concurrent updates are not actually possible to common instance metadata and this should reduce the collisions enough that this scenario should not hit the rate limit as readily. I will try a build of the provider from magic-modules with a mutex added to see if this helps.

### References

* #0000

**Comment by ct-dh** [comment]
I have raised a PR to MagicModules that adds a mutex to this resource, it seems to address the issue - https://github.com/GoogleCloudPlatform/magic-modules/pull/4778

I would also think this would be a great use case for batching, but haven't had a chance to fully figure out how to implement that.

**Comment by ct-dh** [comment]
@venkykuberan / @ScottSuarez any comments/thoughts?

I have an initial build locally using batching, which does seem to work quite well, but wondering if it's worth polishing up or not.

**Comment by ScottSuarez** [comment]
looks good to me ! 

should be live in versioned release `6.69.0`

**Comment by ct-dh** [comment]
@ScottSuarez I assume the version number you mentioned there was a placeholder to be filled in later when you had decided which one? Unless there has been a massive bump in major versions I am not aware of.

Also, I don't think I was very clear in my last reply. I have a separate build locally, that I haven't pushed yet as I have tidied up var names etc that adds a batcher for project metadata item resource. The benefit to me is that what has been merged with the mutex reduces the amount of raciness but you still end up making many API calls, and I guess that makes it more likely to clash with other things outside of the terraform configuration. The batcher, does seem to make it much quicker and less chatty. Do you think it is worth tidying up that change and raising a PR or is there a reason it wouldn't actually be wanted, such as not wanting many batchers or something like that.

**Comment by ScottSuarez** [comment]
@ct-dh ahh sorry yeah mistype there `3.69.0`

Ah I see, sorry about that. If you would like you can submit another pull request with the batching feature and ping me on for the review.

**Comment by ScottSuarez** [comment]
I can definitely see batching being useful but it does depend on the complexity of the feature. I can't promise anything but I don't see why we would want to outright avoid that at the moment.
