### ISSUE TITLE
Artifact Repository resource - format docs missing valid formats

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#9126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Bug

The documentation for artifact repository is missing a list of valid "formats" that can be supplied. 
The example shows 'DOCKER' but i'm guessing there's a 'MAVEN' and 'NPM' option also? 

### Terraform Version

N/A

### Affected Resource(s)

* google_artifact_registry_repository

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository

* #0000

**Comment by muhammadpanji** [comment]
I found list of valid format in `gcloud` docs : https://cloud.google.com/sdk/gcloud/reference/artifacts/repositories/create

I can't find the reference to valid format in the API documentation.

The documentation is autogenerated file. I'm interested working on this issue but I need time to understand how to edit the source of the autogenerated file.

**Comment by c2thorn** [comment]
Formats available for TF listed here: https://cloud.google.com/artifact-registry/docs/integrate-terraform
