### ISSUE TITLE
Error creating EnvgroupAttachment: googleapi: got HTTP response code 404

### ISSUE THREAD

**Issue by pdallecarbonare** [hashicorp/terraform-provider-google#9129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.67.0
+ provider registry.terraform.io/hashicorp/google-beta v3.67.0

### Affected Resource(s)

google_apigee_envgroup_attachment.envgroup

### Terraform Configuration Files

```tf
data "google_client_config" "current" {}

resource "google_apigee_organization" "org" {
  display_name     = "Apigee Test Org"
  description      = "Terraform managed Apigee Organization"
  runtime_type     = "HYBRID"
  analytics_region = "europe-west1"
  project_id       = data.google_client_config.current.project
}

resource "google_apigee_envgroup" "apigee_envgroup" {
  org_id    = google_apigee_organization.org.id
  name      = "tf-test"
  hostnames = ["abc.foo.com"]
}

resource "google_apigee_environment" "apigee_env" {
  org_id       = google_apigee_organization.org.id
  name         = "tf-test"
  description  = "Apigee Environment"
  display_name = "tf-test"
}

resource "google_apigee_envgroup_attachment" "envgroup" {
  envgroup_id  = google_apigee_envgroup.apigee_envgroup.name
  environment  = google_apigee_environment.apigee_env.name
}
```

### Expected Behavior

Attach an Apigee environment to an Apigee environment group

### Actual Behavior

Error: Error creating EnvgroupAttachment: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/tf-test/attachments?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>

### Steps to Reproduce

1. Use the example of https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_envgroup_attachment -> In my case it's a Apigee Hybrid Org, so can skip the creation of the service network peering.
2. `terraform apply`

**Comment by edwardmedia** [comment]
@pdallecarbonare can you share the debug log that have all the requests & responses?

**Comment by pdallecarbonare** [comment]
[](https://gist.github.com/pdallecarbonare/7080a2ef9cdd5324f169b85a8daf47e4)

**Comment by edwardmedia** [comment]
@pdallecarbonare can you try changing the name to id in below field to see if it works for you?

```tf
resource "google_apigee_envgroup_attachment" "envgroup" {
  envgroup_id  = google_apigee_envgroup.apigee_envgroup.name <----- name --> id
  environment  = google_apigee_environment.apigee_env.name
}
```

**Comment by sboyatsis** [comment]
I'm running into same issue.  I wasn't sure what the format of the resource ID of the environment should be.  The code I'm getting not found on the environment is :
resource "google_apigee_envgroup_attachment" "attach1" {
  count = var.org_name == "gds-sdp-apigee-snd" ? 1 : 0   
  envgroup_id  = format("%s/%s/%s/%s","organizations",var.org_name,"envgroups","useast")
  environment  = format("%s/%s/%s/%s","organizations",var.org_name,"environments","snd-useast-1")
}

Getting error: Error creating EnvgroupAttachment: googleapi: Error 404: environment "organizations/gds-sdp-apigee-snd/environments/snd-useast-1" does not exist

**Comment by edwardmedia** [comment]
@sboyatsis you can find the right format [here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.envgroups.attachments/create)

```
https://apigee.googleapis.com/v1/{parent=organizations/*/envgroups/*}/attachments
```

**Comment by sboyatsis** [comment]
I'm confused then on how I specify the environment that I want to attach to this environment group?  I want to attach environment snd-useast-1 to the useast environment group .  

This is code that successfully creates the useast environment group:

esource "google_apigee_envgroup" "env_grp" {
  count = var.org_name == "gds-sdp-apigee-snd" ? 1 : 0
  name      = "useast"
  hostnames = ["sandbox-steveb.useast.libertymutual.com"]
  org_id = format("%s/%s","organizations",var.org_name)
}

snd-useast-1 exists.  

Are you saying the attachment resource code should be this:

resource "google_apigee_envgroup_attachment" "attach1" {
  count = var.org_name == "gds-sdp-apigee-snd" ? 1 : 0   
  envgroup_id  = format("%s/%s/%s/%s","organizations",var.org_name,"envgroups","useast")
  environment  = format("%s/%s/%s/%s","organizations",var.org_name,"envgroups","useast")
}

Where do I supply the actual environment snd-useast-1 ?

**Comment by edwardmedia** [comment]
@sboyatsis  Sorry I should have made it clearer. I was referring to the one in the below error. It should be "organizations/gds-sdp-apigee-snd/envgroups/snd-useast-1" instead

> Getting error: Error creating EnvgroupAttachment: googleapi: Error 404: environment "organizations/gds-sdp-apigee-snd/environments/snd-useast-1" does not exist

Have you had chance to run below instead? If fail, can you post the debug log?
```tf
resource "google_apigee_envgroup_attachment" "envgroup" {
  envgroup_id  = google_apigee_envgroup.apigee_envgroup.name   <<<<<< name --> id
  environment  = google_apigee_environment.apigee_env.name
}
```

**Comment by sboyatsis** [comment]
I'm pretty sure the envgroup_id is being specified correctly.  It's the environment that It says not found but it is an actual environment so thinking it's this bug.  In the documentation it states:
envgroup_id - (Required) The Apigee environment group associated with the Apigee environment, in the format organizations/{{org_name}}/envgroups/{{envgroup_name}}

**Comment by sboyatsis** [comment]
The issue was that environment argument is just a string with the environment name.  

resource "google_apigee_envgroup_attachment" "attach1" {
count = var.org_name == "gds-sdp-apigee-snd" ? 1 : 0
envgroup_id = format("%s/%s/%s/%s","organizations",var.org_name,"envgroups","useast")
environment ="useast"
}

**Comment by pdallecarbonare** [comment]
> @pdallecarbonare can you try changing the name to id in below field to see if it works for you?
> 
> ```terraform
> resource "google_apigee_envgroup_attachment" "envgroup" {
>   envgroup_id  = google_apigee_envgroup.apigee_envgroup.name   <<<<<< name --> id
>   environment  = google_apigee_environment.apigee_env.name
> }
> ```

If I use the ID, it works. . Then it just seems to be wrong documented in the example. I could have figured that out myself!

**Comment by edwardmedia** [comment]
@pdallecarbonare I am glad the **ID** works for you. Closing the issue then

**Comment by pdallecarbonare** [comment]
> @pdallecarbonare I am glad the **ID** works for you. Closing the issue then

However, the example should still be updated -> [Example Usage - Apigee Environment Group Attachment Basic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_envgroup_attachment#example-usage---apigee-environment-group-attachment-basic).

`resource "google_apigee_envgroup_attachment" "envgroup" {
  envgroup_id  = google_apigee_envgroup.apigee_envgroup.name   <<<<<< name --> id
  environment  = google_apigee_environment.apigee_env.name
}`
