### ISSUE TITLE
Error applying IAM policy for storage bucket - Error 400: Role roles/storage.viewer is not supported for this resource.

### ISSUE THREAD

**Issue by black-snow** [hashicorp/terraform-provider-google#9130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.67.0

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

Not sure what's supposed to go here. A storage bucket and IAM policies.

### Terraform Configuration Files

https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/latest/examples/simple_bucket

### Debug Output

Lots of stuff there, will hand in later if required.

### Panic Output

-

### Expected Behavior

Bucket + some IAM created.

### Actual Behavior

Bucket gets created, IAM fails.  
`terraform destroy` won't scrap the bucket.

Output:

```
module.cloud-storage_example_simple_bucket.module.bucket.google_storage_bucket.bucket: Creating...
module.cloud-storage_example_simple_bucket.module.bucket.google_storage_bucket.bucket: Creation complete after 1s [id=xyz-my-demo-bucket-999]
module.cloud-storage_example_simple_bucket.module.bucket.google_storage_bucket_iam_member.members["roles/storage.viewer user:example-user@example.com"]: Creating...
╷
│ Error: Error applying IAM policy for storage bucket "b/xyz-my-demo-bucket-999": Error setting IAM policy for storage bucket "b/xyz-my-demo-bucket-999": googleapi: Error 400: Role roles/storage.viewer is not supported for this resource., invalid
│
│   with module.cloud-storage_example_simple_bucket.module.bucket.google_storage_bucket_iam_member.members["roles/storage.viewer user:example-user@example.com"],
│   on .terraform/modules/cloud-storage_example_simple_bucket/modules/simple_bucket/main.tf line 63, in resource "google_storage_bucket_iam_member" "members":
│   63: resource "google_storage_bucket_iam_member" "members" {
│
```

The issue seems to lie here: https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/v1.7.2/examples/simple_bucket/main.tf#L34

```
  iam_members = [{
    role   = "roles/storage.viewer"
    member = "user:example-user@example.com"
  }]
```

I don't see a default role `storage.viewer` in GCP, only `roles/storage.admin` ...

### Steps to Reproduce

Follow the steps in https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/latest/examples/simple_bucket

```
module "cloud-storage_example_simple_bucket" {
  source  = "terraform-google-modules/cloud-storage/google//examples/simple_bucket"
  version = "1.7.2"
  name = "someuniquebucketnamehere"
  project_id = "your-project-id-here"
}
```

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform destroy`

### Important Factoids

Nope. Running this from GCP cloud shell.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/1564

**Comment by edwardmedia** [comment]
@black-snow instead of `module`, can you repro the issue with plain terraform config? If yes, post the config here

**Comment by black-snow** [comment]
@edwardmedia thanks for the quick reply. Where do I post issues for this samples https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/latest/examples/simple_bucket?

Here's a stripped down version:

```
resource "google_storage_bucket" "bucket" {
  name                        = "youruniquebucketname"
  project                     = "yourproject"
  location                    = "europe-west3"
  storage_class               = null
  uniform_bucket_level_access = true
  labels                      = null
  force_destroy               = false

  versioning {
    enabled = true
  }
}

resource "google_storage_bucket_iam_member" "members" {
  bucket = google_storage_bucket.bucket.name
  role   = "roles/storage.viewer"
  member = "user:example-user@example.com"
}
```

The issue is that there's no such role by default. :|

**Comment by black-snow** [comment]
Moved the issue here: https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/114
