### ISSUE TITLE
BigQuery permadiff when using field of type "DECIMAL"

### ISSUE THREAD

**Issue by jtjanchor** [hashicorp/terraform-provider-google#9132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.7

### Affected Resource(s)

* google_bigquery_dataset

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "business" {
  dataset_id = "business"
  location   = "US"
}

resource "google_bigquery_table" "items" {
  dataset_id          = google_bigquery_dataset.business.dataset_id
  table_id            = "items"
  deletion_protection = false

  schema = <<EOF
[
  {
    "name": "quantity",
    "type": "DECIMAL",
    "mode": "NULLABLE"
  }
]
```

### Debug Output

https://gist.github.com/jtjanchor/b7022b189c7bccfa20d5dfd23427de7f

### Expected Behavior

I expected the Big Query tables to be created without trying to replace each time.

### Actual Behavior

Each time I run `terraform apply` the columns with type "DECIMAL" get converted to "NUMERIC" and there is an attempt to replace the tables.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@jtjanchor here is what the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#schema) says:

> we currently cannot suppress the recurring diff this causes. As a workaround, we recommend using the schema as returned by the API.

Does this make sense to you?

**Comment by jtjanchor** [comment]
Yep this makes sense, and we were able to fix it this way. Still a bit unexpected, but I missed that part of the docs. Thanks for the response.

**Comment by edwardmedia** [comment]
@jtjanchor closing the issue. Thanks
