### ISSUE TITLE
add support for Cloud DNS response policy rules

### ISSUE THREAD

**Issue by oprudkyi** [hashicorp/terraform-provider-google#9133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/blog/products/networking/introducing-cloud-dns-response-policies
https://cloud.google.com/dns/docs/zones/manage-response-policies#api

Basically response policy rules allow to implemented dns substitutions in more simple way then private dns zone
i.e. resolve api endpoints dns names into internal IPs while keeping public IPs for external ingress  
by example api.somedomain.com can resolve into internal ip inside VPC and still can be used as normal dns/ip outside of gcloud 

### New or Affected Resource(s)

* google_dns_response_policy
* google_dns_response_policy_rule

### Potential Terraform Configuration

```tf
resource "google_dns_response_policy" "demo" {
  name = "demo-dns-policy"
  
  networks = [
    google_compute_network.network-1.id,
    google_compute_network.network-2.id,
  ]
}

# use internal IPs for host name
resource "google_dns_response_policy_rule" "test_record" {
  response_policy = google_dns_response_policy.demo.name
  name = "test-1"
  behavior: "LOCAL_DATA"
  dns_name         = "test-record.my-zone.hashicorptest.com."
  local_data {
    type         = "A"
    rrdatas      = ["10.0.0.1", "10.1.0.1"]
    ttl          = 86400
  }
  local_data {
    ...
  }
}

# remap by wilcard
resource "google_dns_response_policy_rule" "mask_record" {
  response_policy = google_dns_response_policy.demo.name
  name = "test-1"
  behavior: "LOCAL_DATA"
  dns_name         = "*.my-zone.hashicorptest.com."
  local_data {
    type         = "A"
    rrdatas      = ["restricted.hashicorptest.com."]
    ttl          = 86400
  }
}

# bypass wildcard rule
resource "google_dns_response_policy_rule" "bypass" {
  response_policy = google_dns_response_policy.demo.name
  name = "test-2"
  behavior: "BYPASS_RESPONSE_POLICY"
  dns_name         = "www.my-zone.hashicorptest.com."
}

resource "google_compute_network" "network-1" {
  name                    = "network-1"
  auto_create_subnetworks = false
}

resource "google_compute_network" "network-2" {
  name                    = "network-2"
  auto_create_subnetworks = false
}
```

### References

https://cloud.google.com/blog/products/networking/introducing-cloud-dns-response-policies
https://cloud.google.com/dns/docs/zones/manage-response-policies#api

**Comment by rileykarson** [comment]
Is this requesting the same thing as https://github.com/hashicorp/terraform-provider-google/issues/9110?

**Comment by oprudkyi** [comment]
@rileykarson  hm, it seems I didn't found bc "Response policy zones" in #9110 aren't official name. 
but anyway closing now
