### ISSUE TITLE
google_pubsub_topic and google_pubsub_subscription -> provide deletion_protection argument

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform-provider-google#9134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`deletion_protection` - (Optional, Default: `false`) Whether or not to allow Terraform to destroy the resource. Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.

### New or Affected Resource(s)

* `google_pubsub_topic`
* `google_pubsub_subscription`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_pubsub_topic" "test_topic" {
  name = "test-topic"

  deletion_protection = true
}

resource "google_pubsub_subscription" "github_nodes_shards_subscription" {
  name  = "test-subscription"
  topic = google_pubsub_topic.test_topic.name

  deletion_protection = true
}

```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection

**Comment by rileykarson** [comment]
We've reserved the use of provider-side `deletion_protection` fields for cases where they default to `true1, as when they default to `false` they duplicate the functionality of [`prevent_destroy`](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#prevent_destroy). A `true` default makes deletion difficult and is appropriate for a limited number of cases, particularly database resources- which is not the case here. See https://github.com/hashicorp/terraform/issues/24658 for a proposal to increase the safety of resources generally.
