### ISSUE TITLE
Replace Hashibot Functionality with GitHub Actions

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#9136]
HashiBot will soon be deprecated in favor of GitHub Actions. We want to replace the functionality of what we currently have to use GitHub Action instead.

**Comment by upodroid** [comment]
While you are here, can you add logic to autoclose issues labelled waiting-response AND have no new comment in the last 30 days? Adding a comment removes the label.

btw, 27 of the 53 open issues labelled waiting-response are older than 2021.

**Comment by rileykarson** [comment]
Note: We aren't sure whether there are preexisting actions we can reuse, sizing larger than this may end up for now
