### ISSUE TITLE
googleapi: Error 403: on first attempt at creating repository, but works on 2nd attempt

### ISSUE THREAD

**Issue by syntapy** [hashicorp/terraform-provider-google#9137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.3 on linux_amd64
provider registry.terraform.io/hashicorp/google v3.67.0

### Affected Resource(s)

* google_project_service
* google_sourcerepo_repository

### Terraform Configuration Files

```tf
variable "project_id" {
  type = string
}

variable "region" {
  type = string
  default = "us-west1"
}

variable "zone_letter" {
  type = string
  default = "a"
}

locals {
  zone = join("-", [var.region, var.zone_letter])
}

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.67.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region = var.region
}

resource "google_project_service" "sourcerepo" {
  service = "sourcerepo.googleapis.com"
}

resource "google_sourcerepo_repository" "test_repo" {
  name = "test-repo"
}
```

### Debug Output

1st terraform apply [gist](https://gist.github.com/syntapy/54090025577bcd81e15088b3f8f5a407)
2nd terraform apply [gist](https://gist.github.com/syntapy/1c1a78a010e1c7e9254ba27f991b38c6)

### Panic Output

N/A

### Expected Behavior

Should have created all resources with no errors on 1st `terraform apply`

### Actual Behavior

Gave error on 1st `terraform apply` but finished creating all resources with no errors on 2nd `terraform apply` with no other modifications

### Steps to Reproduce

1. Copy that terraform snippet into a `main.tf`, add a `terraform.tfvars` file, run `terraform init`
2.`terraform apply` two times in a row

**Comment by edwardmedia** [comment]
@syntapy likely `google_project_service` took extra long time in the background before it becomes available to use.  To solve the problem you may modify the config by 1) adding the dependency in `google_sourcerepo_repository` 2) adding a wait (or sleep) logic between two resources. Let me know if that solves the problem

**Comment by syntapy** [comment]
@edwardmedia I did each independently and they both worked

**Comment by edwardmedia** [comment]
@syntapy you could put them together. But just make sure giving extra time for the service to be provisioned before the next resource starts to use it. It is pretty common behavior. Closing the issue then.
