### ISSUE TITLE
`make lint` gives extraneous feedback

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Currently, we encourage people opening PRs to run `make lint` to catch any formatting errors; however, `make lint` frequently catches "issues" on user's machines that are not considered a problem in ci/cd. For example, see https://github.com/GoogleCloudPlatform/magic-modules/pull/4689#issuecomment-818669974 (or run `make lint` on your own machine.)

We should correct this mismatch so that the output from `make lint` is actionable for contributors.

**Comment by rileykarson** [comment]
Note: It seems to ignore the config file locally, and I have not been able to figure it out

**Comment by melinath** [comment]
Reopening as the fix (though it makes an improvement) doesn't fully resolve the issue - see comments on the PRs.

**Comment by ScottSuarez** [comment]
> Reopening as the fix (though it makes an improvement) doesn't fully resolve the issue - see comments on the PRs.

Ah sorry about that, I removed the closes from one of the prs but not the other !

**Comment by melinath** [comment]
> > Reopening as the fix (though it makes an improvement) doesn't fully resolve the issue - see comments on the PRs.
> 
> Ah sorry about that, I removed the closes from one of the prs but not the other !

No worries! :-)

**Comment by melinath** [comment]
for future us: this is reopened because we still need to update the version of the linter in the provider to match what people are likely to have locally (which is what was causing the diff in lint errors that were fixed in the most recent PR)

**Comment by ScottSuarez** [comment]
resolved with
https://github.com/hashicorp/terraform-provider-google-beta/pull/3329
and 
https://github.com/hashicorp/terraform-provider-google/pull/9348

if more issues feel free to reopen.

created new bug to track new ignored rules https://github.com/hashicorp/terraform-provider-google/issues/9349
