### ISSUE TITLE
Skip provider linting / go tests / TeamCity tests if go code is unmodified.

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

A fair number of PRs are docs-only - for example: https://github.com/GoogleCloudPlatform/magic-modules/pull/4757 - or modify other non-go files, or don't modify the provider (i.e. PRs that modify terraform-google-conversion only).

If the PR doesn't modify the providers' go code, we can safely skip running provider linting, go tests and TeamCity tests. This will avoid tying up TeamCity agents, keep the Magician from spamming these PRs with irrelevant comments, and give a quicker turnaround time to contributors on those PRs.

**Comment by rileykarson** [comment]
Note: https://github.com/hashicorp/terraform-provider-google/issues/9146 probably makes this harder

**Comment by melinath** [comment]
Basically, this would require doing something similar to the [github-differ](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/containers/github-differ/generate_comment.sh) for the linter/tester containers and only running the respective check if the list of files in the diff contains at least one `.go` file.
