### ISSUE TITLE
Run VCR tests using GA provider for GA-only PRs

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

Some PRs (like making something GA) only modify the GA provider. However, we currently only run tests on the beta provider. This can end up introducing bugs into the GA provider that would have been caught by VCR tests (if they had been run). It would be great if we could detect this case (i.e. changes to GA provider go code but not to beta provider go code) and run VCR tests for the GA provider instead of beta.

This is somewhat related to: https://github.com/hashicorp/terraform-provider-google/issues/9147, in a way.

**Comment by rileykarson** [comment]
Notes: Figuring out a GA-only PR is difficult. We could consider a rule like "if go files are altered in ga and not beta, run at ga".

**Comment by melinath** [comment]
We may want to run GA VCR tests on all PRs, which would make a duplicate of #13170

**Comment by melinath** [comment]
We should just run GA VCR on all PRs.
