### ISSUE TITLE
Artifact Registry data source.

### ISSUE THREAD

**Issue by hsblhsn** [hashicorp/terraform-provider-google#9151]
I can not see any data source documentation for Artifact Registry. Although there's documentation for Container Registry data sources.

Is data source for Artifact registry not ready yet? Or, it's just a missing documentation?

**Comment by rileykarson** [comment]
Data sources do not become automatically available, and we don't aim for complete coverage w/ them. We'll use this issue to track interest.

**Comment by hsblhsn** [comment]
Hey there,
is there any update on it?

**Comment by jamesvnz** [comment]
This is quite an important item to have a data source for. It's very common to have artifact repositories shared across projects / folders / orgs.

Given that Artifact Repository is positioned as the replacement / migration path for Container Registry, we need to have parity with Container Registry, which has a data source.

**Comment by killthekitten** [comment]
Same here – sharing an artifact registry is impossible at the moment, which was not the case with container registry.

**Comment by bcspragu** [comment]
Would also like to see this. My main motivation is getting rid of a perpetual diff I see, which causes unnecessary re-deployments of an App Engine Flex-based service, e.g.:

```plain text
~ container {
  ~ image = "$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE_NAME@sha256:$SOME_SHA" -> "$REGION.pkg.dev/$PROJECT/$REPO/$IMAGE_NAME:$SOME_TAG"
}
```

Because I _do_ want to deploy based on the tag, but, App Engine (reasonably) references it by SHA, This causes an update even if the tag does indeed point to that SHA

**Comment by ManveerBhullar** [comment]
+1. Since GAR is being billed as a GCR replacement, having a `data source` for it would be great

**Comment by yehoshuadimarsky** [comment]
+1 to this, any updates?

**Comment by bogaertg** [comment]
👍

**Comment by melinath** [comment]
b/247009610
