### ISSUE TITLE
Missing example cloud_run_service_secret_volumes

### ISSUE THREAD

**Issue by ricardolpd** [hashicorp/terraform-provider-google#9158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.15.3 9 (from inside gcp cloud)

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service

the following example does not exist.
/home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes

### Debug Output
Clicking on the example above, the following output is shown:
```
2021/05/16 22:29:42 Cloning https://github.com/terraform-google-modules/docs-examples.git into /home/ricardo/cloudshell_open/docs-examples
Cloning into '/home/ricardo/cloudshell_open/docs-examples'...
remote: Enumerating objects: 1620, done.
remote: Counting objects: 100% (826/826), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 1620 (delta 807), reused 784 (delta 783), pack-reused 794
Receiving objects: 100% (1620/1620), 384.70 KiB | 10.40 MiB/s, done.
Resolving deltas: 100% (1245/1245), done.
Path /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes/main.tf does not exist
Tutorial file /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes/tutorial.md does not exist or is not a file
-bash: cd: /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes: No such file or directory
ricardo@cloudshell:~$ terraform -v
Terraform v0.15.0
on linux_amd64
```

### Expected Behavior

Example should exist to be able to run it

### Actual Behavior

folder does not exit

### Steps to Reproduce

click on the example button which points to the following link): 
https://console.cloud.google.com/cloudshell/open?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fterraform-google-modules%2Fdocs-examples.git&cloudshell_working_dir=cloud_run_service_secret_volumes&cloudshell_image=gcr.io%2Fgraphite-cloud-shell-images%2Fterraform%3Alatest&open_in_editor=main.tf&cloudshell_print=.%2Fmotd&cloudshell_tutorial=.%2Ftutorial.md

1. `terraform apply`
N.A

### References

N.A

* #0000

**Comment by edwardmedia** [comment]
@ricardolpd did you click `Open GOOGLE CLOUD SHELL` button? Your link leads to the cloud shell. What is the problem?

**Comment by ricardolpd** [comment]
When opening that examply through the google cloud shell, the folder the example points at is missing, thats what i am trying to explain in this issue:

this is the output from cloud shell when opening that example (if you open the link to cloud provided you will the errors below:
```
2021/05/16 22:29:42 Cloning https://github.com/terraform-google-modules/docs-examples.git into /home/ricardo/cloudshell_open/docs-examples
Cloning into '/home/ricardo/cloudshell_open/docs-examples'...
remote: Enumerating objects: 1620, done.
remote: Counting objects: 100% (826/826), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 1620 (delta 807), reused 784 (delta 783), pack-reused 794
Receiving objects: 100% (1620/1620), 384.70 KiB | 10.40 MiB/s, done.
Resolving deltas: 100% (1245/1245), done.
Path /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes/main.tf does not exist
Tutorial file /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes/tutorial.md does not exist or is not a file
-bash: cd: /home/ricardo/cloudshell_open/docs-examples/cloud_run_service_secret_volumes: No such file or directory
ricardo@cloudshell:~$ terraform -v
Terraform v0.15.0
on linux_amd64
```

**Comment by rileykarson** [comment]
Same issue as https://github.com/hashicorp/terraform-provider-google/issues/8317, for some reason a subset of examples aren't showing up. I renamed the old one to be general, and deduplicating there.
