### ISSUE TITLE
Cloud Run Service Secret Environment Variables, throws spec.template.spec.containers[0].env.value_from should be empty

### ISSUE THREAD

**Issue by ricardolpd** [hashicorp/terraform-provider-google#9159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.15.3.

### Affected Resource(s)

Cloud Run beta, spec env secret manager env.

google_cloud_run_service

### Terraform Configuration Files
(code from example)
```
data "google_project" "project" {
  provider = google-beta
}

resource "google_secret_manager_secret" "secret" {
  provider = google-beta

  secret_id = "secret"
  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "secret-version-data" {
  provider = google-beta

  secret = google_secret_manager_secret.secret.name
  secret_data = "secret-data"
}

resource "google_secret_manager_secret_iam_member" "secret-access" {
  provider = google-beta

  secret_id = google_secret_manager_secret.secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"
  depends_on = [google_secret_manager_secret.secret]
}

resource "google_cloud_run_service" "default" {
  provider = google-beta

  name     = "cloudrun-srv"
  location = "us-central1"

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
        env {
          name = "SECRET_ENV_VAR"
      value_from {
            secret_key_ref {
              name = google_secret_manager_secret.secret.secret_id
              key = "1"
            }
          }
        }
      }
    }
  }

  metadata {
    annotations = {
      generated-by = "magic-modules"
      "run.googleapis.com/launch-stage" = "ALPHA"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
  autogenerate_revision_name = true

  lifecycle {
    ignore_changes = [
        metadata.0.annotations,
    ]
  }

  depends_on = [google_secret_manager_secret_version.secret-version-data]
}
```tf

### Debug Output

│ Error: Error updating Service "locations/us-east1/namespaces/just-ricardo-duarte/services/cloud-run-example": googleapi: Error 400: spec.template.spec.containers[0].env.value_from: spec.template.spec.containers[0].env.value_from should be empty
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "spec.template.spec.containers[0].env.value_from should be empty",
│         "field": "spec.template.spec.containers[0].env.value_from"
│       }
│     ]
│   }
│ ]

### Expected Behavior

should have allowed to add a secret manager reference to cloud run

### Actual Behavior

Terraform apply failed

### Steps to Reproduce

terraform init
terraform apply

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables

* #0000

**Comment by edwardmedia** [comment]
@ricardolpd can you share the debug log?

**Comment by ricardolpd** [comment]
@edwardmedia 

I had another retracing my steps to get your logs, and after getting a few times the same error. I realised the only thing missing from the example i had was:

`"run.googleapis.com/launch-stage"  = "ALPHA"` in the metadata annotations.

Apologies for kinda jumping the gun on the issue. 

Looking at the docs i couldnt find any mention of this annotation being a requirement for beta features. 
Does this flag have always to be there when using beta features? 

I am happy for the issue to be closed, with perhaps a small nit, to those wanting to use beta features, as to know if that annotation is a requirement or not, otherwise feel free to close the issue.

**Comment by Flydiverny** [comment]
When deploying using gcloud CLI we noticed our cloud run deployment had the annotation `"run.googleapis.com/launch-stage" = "BETA"` which we tried to add thru terraform but we seem to be facing the same issues even after adding it. Seems odd if we need `ALPHA` stage for it to work with terraform? Maybe we are missing something else.

**Comment by edwardmedia** [comment]
@ricardolpd  please provide the debug log so I can take a close look at how to reach that error.

@Flydiverny for the field **annotation**, there is comment below in the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#annotations). Terraform does not have full control over it. 

>Note: The Cloud Run API may add additional annotations that were not provided in your config. If terraform plan shows a diff where a server-side annotation is added, you can add it to your config or apply the lifecycle.ignore_changes rule to the metadata.0.annotations field.

**Comment by edwardmedia** [comment]
@ricardolpd is this still an issue?

**Comment by ricardolpd** [comment]
@edwardmedia i had already replied, i found the issue, i have apologised and asked a simple question regarding the annotation requirement for beta funcionality.
see below. Other than that i am happy to close.

> @edwardmedia
> 
> I had another retracing my steps to get your logs, and after getting a few times the same error. I realised the only thing missing from the example i had was:
> 
> `"run.googleapis.com/launch-stage" = "ALPHA"` in the metadata annotations.
> 
> Apologies for kinda jumping the gun on the issue.
> 
> Looking at the docs i couldnt find any mention of this annotation being a requirement for beta features.
> Does this flag have always to be there when using beta features?
> 
> I am happy for the issue to be closed, with perhaps a small nit, to those wanting to use beta features, as to know if that annotation is a requirement or not, otherwise feel free to close the issue.

**Comment by edwardmedia** [comment]
Great. Closing the issue then

**Comment by ujwaldhakal** [comment]
@edwardmedia even though i copy exact code from the cloud run with secrets or value i ended up same error 
`Error 400: spec.template.spec.containers[0].volumeMounts: spec.template.spec.containers[0].volumeMounts should be empty`
and `Error 400: spec.template.spec.containers[0].env.value_from: spec.template.spec.containers[0].env.value_from should be empty`

**Comment by edwardmedia** [comment]
@ujwaldhakal can you be specific what exact code you copied from?

> i copy exact code from the cloud run with secrets or value i ended up same error

**Comment by Flydiverny** [comment]
The mistake on our part was setting the annotation on the `template` part

```tf
template {
  metadata {
    annotations = {
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }
}
```

instead of 
```tf
metadata {
  annotations = {
    "run.googleapis.com/launch-stage" = "BETA"
  }
}
 ```

**Comment by ricardolpd** [comment]
@edwardmedia can you please clarify if this annotation is required for all beta features?

`"run.googleapis.com/launch-stage" = "BETA"`

I noticed the docs mentioned "ALPHA" not beta. If this annotation is required to use beta features, can you please add it to the docs. as its very easy to miss from examples.

**Comment by edwardmedia** [comment]
@ricardolpd regarding the annotation, I added the comment [here](https://github.com/hashicorp/terraform-provider-google/issues/9159#issuecomment-843236468) . Does this make sense?

**Comment by ujwaldhakal** [comment]
> @ujwaldhakal can you be specific what exact code you copied from?
> 
> > i copy exact code from the cloud run with secrets or value i ended up same error
@edwardmedia 
Looks like i had to clear my .terraform and state then it was working fine . Looks like it was version issue i was using beta 3.4x it has been solved

**Comment by edwardmedia** [comment]
@ujwaldhakal  I am glad you have found the solution. Closing the issue then.

**Comment by ricardolpd** [comment]
> @ricardolpd regarding the annotation, I have already added the comment [here](https://github.com/hashicorp/terraform-provider-google/issues/9159#issuecomment-843236468) . Does this make sense?

@edwardmedia i had read this before i opened the issue, but i think you will agree that between that line and 

`"run.googleapis.com/launch-stage" = "BETA"`

I fully understand terraform doesnt have control over which annonations are allowed since, some of these are obscure and a consequence of using kuberneters in th background. However since this little line makes all the different when adopting beta/alpha features, i feel the docs should highlight the requirement properly, or the error message should be more descriptive, thats all. As you can see i am not the only one that tripped when adopting this.
