### ISSUE TITLE
google container cluster cannot enable addon 'config_connector_config'

### ISSUE THREAD

**Issue by rbabyuk** [hashicorp/terraform-provider-google#9169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.3
hashicorp/google v3.66.1
tested hashicorp/google v3.51.1

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
provider "google" {

  project     = var.project
  region      = var.region
  credentials = file(var.gcp_auth_file)
}

resource "google_container_cluster" "primary" {
  name                      = "${var.project}-gke"
  location                  = var.region
  default_max_pods_per_node = 30

  # Manage Addons
  addons_config {
    config_connector_config {
      enabled = true
    }
  }

  #  min_master_version = local.kubernetes_version
  release_channel {
    channel = var.release_channel
  }
  // release_channel    = var.release_channel

  remove_default_node_pool = true
  initial_node_count       = 1

  network    = var.network_name
  subnetwork = var.subnet_name

  master_auth {
    username = var.gke_username
    password = var.gke_password

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  #Enable Workload Identiry to manage security
  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }

  ip_allocation_policy {

    cluster_secondary_range_name  = "gke-cluster-secondary-range"
    services_secondary_range_name = "gke-services-secondary-range"
  }
}
```

### Debug Output

https://gist.github.com/rbabyuk/55d9b1f1608512e7df7ef012b9cf3a54

### Expected Behavior

config_connector_config addon is enabled

### Actual Behavior

terraform reports an error

### Steps to Reproduce

place snippet I provided and run TF plan

1. `terraform apply`

### References

* #0000

**Comment by venkykuberan** [comment]
@rbabyuk `config_connector_config` is supported only in `google-beta` at this time. Please try the same.

**Comment by edwardmedia** [comment]
@rbabyuk is this still an issue?

**Comment by rbabyuk** [comment]
hi @edwardmedia , I can confirm that with newer google provider it's ok
