### ISSUE TITLE
Support for adding project to monitoring workspace

### ISSUE THREAD

**Issue by mkotsbak** [hashicorp/terraform-provider-google#9170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I don't find any Terraform resources for adding a monitored project to a monitor workspace, i.e. the manual operation described here:
https://cloud.google.com/monitoring/settings#add-monitored-project

Is there missing API for doing this or just missing Terraform support?

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/2605
