### ISSUE TITLE
Allow to specify a retry policy for cloudfunctions_function when using event trigger

### ISSUE THREAD

**Issue by ploth** [hashicorp/terraform-provider-google#9172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As it is possible for `google_pubsub_subscription` to specify a retry policy it would be great to have the same feature for `google_cloudfunctions_function` when using `event_trigger`. In the current state it is only possible to configure whether the function should be retried on failure.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_cloudfunctions_function" "this" {

  ...

  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = ...

    failure_policy {
      retry = true
    }

    retry_policy {
      minimum_backoff = "10s"
      maximum_backoff = "600s"
    }
  }
}
```

### References

* [retry_policy for google_pubsub_subscription](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#retry_policy)
* [failure_policy for google_cloudfunctions_function](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function#failure_policy)

**Comment by melinath** [comment]
Closing since it doesn't appear that the underlying GCP resource supports this functionality: https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions
