### ISSUE TITLE
google_redis_instance cannot be upgraded - # forces replacement

### ISSUE THREAD

**Issue by eyalc10** [hashicorp/terraform-provider-google#9174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.31
+ provider.google v3.67.0
+ provider.google-beta v3.67.0

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* google_redis_instance

### Terraform Configuration Files

```tf
module "memorystore" {
  source  = "terraform-google-modules/memorystore/google"
  version = "2.0.0"

  name    = "my-tf-memorystore-upgrade-test"
  project = "my-project"
  region = "us-central1"
  authorized_network = "internal"
  redis_version = "REDIS_5_0"
}
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Panic Output

I have expected that memorystore version would be upgraded keeping data as a part of STANDARD_HA tier
### Actual Behavior

Data loss -  memorystore instance was replaced - deleted and created with the new version (5.0) 
### Steps to Reproduce

1. `terraform apply`

### References

* b/188917140

**Comment by venkykuberan** [comment]
@eyalc10 `redis_version` is ForceNew field [here](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_redis_instance.go#L129), so any value change makes the resource to be recreated.

Were you able to upgrade the redis version via `gcloud` or `REST API` without recreating the resource ?

**Comment by eyalc10** [comment]
@venkykuberan , yes , 
`gcloud redis instances upgrade my-tf-memorystore-upgrade-test --redis-version=redis_5_0 --region=us-central1`
- upgrade was successful , data kept safe , when working with "STANDARD_HA" tier instance 

IP was not changed as well .

**Comment by rileykarson** [comment]
Lack of update support is not a bug, changing to an enhancement request

**Comment by eyalc10** [comment]
When changing a value in Terraform - you would expect TF to change the remote resource with as minimal changes as possible - according to the supported method. 

For example - IP change for a specific resource 

I can definitely agree that it's not a bug perse, but it is a behaviour that you do not expect, 
STANDARD_HA tier was set to support data integrity upon an upgrade, 
TF should not be the platform to emit such support .
