### ISSUE TITLE
Add support for the rest of the AutoprovisioningNodePoolDefaults settings in `google_container_cluster`

### ISSUE THREAD

**Issue by pib** [hashicorp/terraform-provider-google#9180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[AutoprovisioningNodePoolDefaults](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AutoprovisioningNodePoolDefaults) in the v1 API has support for several more fields than those currently supported by the [auto_provisioning_defaults block](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#auto_provisioning_defaults). 

Currently only `min_cpu_platform`, `oauth_scopes`, and `service_account` are supported.

Options currently missing are
- `upgradeSettings`
- `management`
- `diskSizeGb`
- `diskType`
- `shieldedInstanceConfig`
- `bootDiskKmsKey`

It might makes sense for these to be implemented in separate PRs. There are already a couple of existing PRs that add `upgrade_settings` and `management` (linked in the references section below).

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "example" {
  name = "example"

  cluster_autoscaling {
    enabled = true

    auto_provisioning_defaults {
      service_account  = google_service_account.cluster_nodes_service_account.email
      min_cpu_platform = "Intel Haswell"
      oauth_scopes     = []

      # New options
      upgrade_settings {
        max_surge       = "25%"
        max_unavailable = "0"
      }

      management {
        auto_repair  = true
        auto_upgrade = true
      }

      disk_size_gb      = 12
      disk_type         = "pd-ssd"
      boot_disk_kms_key = google_kms_crypto_key.example.id

      shielded_instance_config {
        enable_secure_boot          = true
        enable_integrity_monitoring = false
      }
    }
  }
}
```

### References

* #5580 (request for upgrade_settings), #5676 (PR for that feature)
* #5579 (request for management block), #5672 (PR for that feature)
* b/189224778

**Comment by dippynark** [comment]
Should default node image type be included in this list? https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#default-image-type

**Comment by YpNo** [comment]
Hi,
I need the missing options as well with a focus on image_type.

Regards.

**Comment by rafaeljesus** [comment]
Any idea when these features will be available? I can't enable NAP due to this limitation as well
