### ISSUE TITLE
"list" function was deprecated in Terraform v0.12

### ISSUE THREAD

**Issue by PrateekKhatri** [hashicorp/terraform-provider-google#9181]
Terraform Version = v0.15.3

**Error:**

**Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.**

**Comment by edwardmedia** [comment]
@PrateekKhatri are you filing a bug against Google provider? If yes, could you provide the config and details as mentioned in the template? If you file an issue against Terraform features, do you mind file one directly to Terraform?

**Comment by PrateekKhatri** [comment]
List function was deprecated by terraform. I have updated my code and everything is working. We can make use to "tolist" function instead of the "list" function.

Closing the issue.
