### ISSUE TITLE
rrdatas field on dns_record_set incorrectly marked as ForceNew

### ISSUE THREAD

**Issue by spew** [hashicorp/terraform-provider-google#9184]
The 'rrdatas' field on resource_dns_resource_dns_record_set has been marked as 'ForceNew'. Previously this field did not have ForceNew.

https://cloud.google.com/dns/docs/reference/v1beta2/resourceRecordSets#resource

**Comment by roaks3** [comment]
This was fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/5191, which reverted the ForceNew behavior
