### ISSUE TITLE
tpgtools --version option should default to GA

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9190]
### Affected Resource(s)

* google_*

According to the tpgtools README I should be able to omit --version - but if I do, I get a nil pointer dereferencing error, because the version is never set to its default value (ga). We should make sure that this is set properly & tested.

**Comment by rileykarson** [comment]
This is largely irrelevant now that we pretty much exclusively interact with both generators through make where the version is required.
