### ISSUE TITLE
Support to deploy DialogFlow CX Agent

### ISSUE THREAD

**Issue by jcanizalez** [hashicorp/terraform-provider-google#9200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
I am hopping to get support for managing DialogFlow CX Agent using Terraform. Currently only Agents for DialogFlow ES are supported

### New or Affected Resource(s)

* google_dialogflow_cx_agent

### Potential Terraform Configuration

```tf
resource "google_dialogflow_cx_agent" "cx_agent" {
  display_name = "dialogflow-agent"
  default_language_code = "en"
  supported_language_codes = ["fr","de","es"]
  time_zone = "America/New_York"
  enables_spell_correction = "true"
}
```

### References

* https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/projects.locations.agents
* https://cloud.google.com/dialogflow/cx/docs/concept/agent

**Comment by jcanizalez** [comment]
Hi team I would like to work on this issue, but I have some questions:

1. Because the API for Dialog Flow CX is very different from the current supported resource google_dialog_flow (DialogFlow ES), is ok if I create a new product folder for dialogflowcx and inside I can create the new resource google_dialogflow_cx_agent, and probabbly the additional resources in the future: google_dialogflow_cx_page, google_dialogflow_cx_flow, or there is a better approach?
2. And in the case that a new product dialogflowcx its needed, should I create it using tpgtools? Or continue using MMV?


For reference documentation:
**DialogFlow ES** (currently supported in gcp provider) https://cloud.google.com/dialogflow/es/docs/reference/rest/v2-overview
**DialogFlow CX:** (new) https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3-overview

**Comment by c2thorn** [comment]
@jcanizalez 

1. With the differences in the API, I think a new product folder would be appropriate. We'd want to keep both versions simultaneously.
2. Please continue using MMv1, dialogflow is not currently available upstream in the DCL.

**Comment by jcanizalez** [comment]
Thanks @c2thorn for your quick response

I will work on this
