### ISSUE TITLE
google_storage_bucket lifecycle_rule throwing List shorter than MinItems error

### ISSUE THREAD

**Issue by joeyorlando** [hashicorp/terraform-provider-google#9215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.15.4

### Provider Version

3.68.0

### Affected Resource(s)

* google_storage_bucket (`lifecycle_rule` attribute specifically)

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "stitchdata" {
  name           = "<my_bucket_name_here>"
  storage_class  = "STANDARD"
  location       = "US"
  requester_pays = false

  lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      age                        = 7
      days_since_custom_time     = 0
      days_since_noncurrent_time = 0
      matches_storage_class      = []
      num_newer_versions         = 0
      with_state                 = "ANY"
    }
  }

  labels = local.labels
}
```

### Debug Output

```
Waiting for the plan to start...

Terraform v0.15.4
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Error: List shorter than MinItems
│
│   with google_storage_bucket.stitchdata,
│   on gcs_stitchdata.tf line 11, in resource "google_storage_bucket" "stitchdata":
│   11:     condition {
│
│ Attribute supports 1 item minimum, config has 0 declared
```

### Expected Behavior

The `plan` should successfully complete

### Actual Behavior

Received above debug output mentioning that my `lifecycle_rule` block is not properly configured when in fact it _should_ be

### Steps to Reproduce

1. `terraform plan` (with above configuration)

**Comment by edwardmedia** [comment]
API takes empty array of **matches_storage_class**

**Comment by joeyorlando** [comment]
that did the trick. I was importing this `google_storage_bucket` resource and the `terraform plan` prior to the `import` showed `matches_storage_class      = []`. Omitting `matches_storage_class` fixed things for me, thank you.
