### ISSUE TITLE
multiple `google_project_iam_binding` for the same `role` not working

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform-provider-google#9225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.68.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `google_project_iam_binding`

### Terraform Configuration Files

This is not working, and doesn't show any errors:

```tf
data google_service_account worker {
  depends_on = [ google_deployment_manager_deployment.cluster_security ]
  account_id = "${local.infrastructure_name}-w"
}

resource google_project_iam_binding worker_storage_admin {
  members = ["serviceAccount:${data.google_service_account.worker.email}"]
  role = "roles/storage.admin"
}

data google_service_account master {
  depends_on = [ google_deployment_manager_deployment.cluster_security ]
  account_id = "${local.infrastructure_name}-m"
}

resource google_project_iam_binding master_storage_admin {
  members = ["serviceAccount:${data.google_service_account.master.email}"]
  role = "roles/storage.admin"
}
```

Somehow only `google_project_iam_binding.worker_storage_admin` is applied, and `google_project_iam_binding master_storage_admin` is silently ignored.

What does work is this
```tf
resource google_project_iam_binding storage_admin {
  members = [
    "serviceAccount:${data.google_service_account.worker.email}",
    "serviceAccount:${data.google_service_account.master.email}",
  ]
  role = "roles/storage.admin"
}
```

I found this hugely surprising, I wished there was some kind of error. I don't mind declaring these resources as one, but I wasted hours figuring out what's gone wrong in other layers having trusted Terraform to get the basics right.

### Expected Behavior

I wished the original code either worked, or 

### Actual Behavior

No warning or error, invalid state.

### Steps to Reproduce

1. `terraform apply`

**Comment by ct-dh** [comment]
(Another user here, not a contributor)

If you take a look at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam you will see a few "note" boxes - the behavior you are seeing is expected and documented there.

What you want to use to do things the way you initially had them is to use `google_project_iam_member` as this is not authoritative for a given role, google_project_iam_binding is so only 1 will ever win.

**Comment by edwardmedia** [comment]
@errordeveloper as @ct-dh pointed out, you might want to compare the differences among three **iam** resources (_policy, _binding and _member). In your case, you might just put them in one _binding resource. Does this make sense?

**Comment by edwardmedia** [comment]
@errordeveloper is this still an issue?

**Comment by edwardmedia** [comment]
@errordeveloper closing this assuming this is no longer an issue

**Comment by errordeveloper** [comment]
Thanks for following up, @edwardmedia! The information folks provided here is more then sufficient :)
