### ISSUE TITLE
cloud dataflow jobs in "cancelling" or "draining" states should not be considered update candidates

### ISSUE THREAD

**Issue by n-oden** [hashicorp/terraform-provider-google#9227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/google v3.68.0
+ provider registry.terraform.io/hashicorp/google-beta v3.68.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/integrations/github v4.9.4
```

### Affected Resource(s)

* google_dataflow_flex_template_job

### Terraform Configuration Files

Sorta N/A: as far as I can tell this occurs with any possible syntactically correct `google_dataflow_flex_template_job` resource that launches a streaming job.  (And providing ours won't help because you won't be able to load our flex template json from GCS.)

### Debug Output

https://gist.github.com/n-oden/437f2f640f74558042b35ae0165a2bf7

### Expected Behavior

The provider should notice that the dataflow job we are attempting to update is in state CANCELLING or DRAINING, and since both of those are states in which an update is not possible, it should create a new job resource immediately if `lifecycle.create_before_destroy` is `true`, or wait until the existing job reaches the DRAINED or CANCELLED states and then create the new job if `lifecycle.create_before_destroy` is `false`.

### Actual Behavior

The provider spins while reporting "Still modifying..." until the existing job finally hits the DRAINED/CANCELLED state and aborts with an error:

```
Error: Error waiting for job with job ID "2021-05-25_08_34_18-15188511358509409746" to be running: 
the job with ID "2021-05-25_08_34_18-15188511358509409746" has terminated with state 
"JOB_STATE_DRAINED" instead of expected state "JOB_STATE_RUNNING"
```

### Steps to Reproduce

1. create a `google_dataflow_flex_template_job` resource with `terraform apply`
2. wait for the job to be created and hit state `RUNNING`
3. make a change to the terraform resource definition that would cause the job to be updated in-place, such as changing the path pointed to in `container_spec_gcs_path`
4. *before* running terraform apply, manually drain the existing job, either from the GCS console or with `gcloud dataflow jobs drain <jobid>`
5. *while* the existing job is in state DRAINING, `terraform apply`

### Important Factoids

This may also be an issue with `google_dataflow_job` resources; I have not yet checked.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/8408

**Comment by andremarianiello** [comment]
Something to keep in mind with this issue: if you try to create a job with the same name as a cancelling/draining job it will fail, whether or not it is an update.

**Comment by melinath** [comment]
It sounds like the issue here is that an "update" of a job (which actually replaces a job with a new job with the same name) can only happen when the current job with that name has one of the following states:

- JOB_STATE_RUNNING
- JOB_STATE_CANCELLED
- JOB_STATE_DRAINED

But the current update logic only goes through if the job is in RUNNING state; it should also go through in the other two states.

I don't think that we can create before destroy because the job would fail as @andremarianiello described. The current behavior is the same as destroying before create. Let me know if that seems incorrect!

**Comment by melinath** [comment]
@n-oden  I tried to make some tweaks to allow updating jobs that are in the CANCELLED state but ended up getting an error from the API. Are you sure updating jobs in the CANCELLED and DRAINED states should be possible? Alternatively we could potentially switch to creating new jobs (i.e. not updating the existing job) but I think that might be an unexpected behavior. We could just fast-fail if the current state is CANCELLING or DRAINING, and alert the user that they need to wait for the job to complete first.

**Comment by melinath** [comment]
It looks like CANCELLED/DRAINED can't be updated: https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs#jobstate
