### ISSUE TITLE
google_vpc_access_connector getting redeployed on every `terraform apply` without changes in configuration

### ISSUE THREAD

**Issue by fhaubner** [hashicorp/terraform-provider-google#9228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.69.0
+ provider registry.terraform.io/hashicorp/google-beta v3.69.0

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "custom_test" {
  provider      = google-beta
  name          = "vpc-con"
  ip_cidr_range = "10.2.0.0/28"
  region        = "europe-west3"
  network       = google_compute_network.custom_test.id
}

resource "google_compute_network" "custom_test" {
  provider                = google-beta
  name                    = "vpc-con"
  auto_create_subnetworks = false
}

resource "google_vpc_access_connector" "test-vpc-connector" {
  provider      = google-beta
  name          = "test-vpc-connector"
  subnet {
    name = google_compute_subnetwork.custom_test.name
  }
  machine_type = "e2-standard-4"
  min_instances = 2
  max_instances = 3
  project = "xyz"
  region  = "europe-west3"
}
```

### Expected Behavior

The google_vpc_access_connector resource should work fine with providing "min_instances", "max_instances" and not providing "min_throughput", "max_throughput". Alternatively to the parameter set "min_instances", "max_instances", it should be possible to use "min_throughput", "max_throughput".

According to the documentation
https://cloud.google.com/sdk/gcloud/reference/beta/compute/networks/vpc-access/connectors/create
**At most one of these may be specified**:
- Scaling settings of a VPC Access Connector can be specified in terms of **number** of Google Compute Engine VM **instances** underlying the connector autoscaling group.
- Scaling settings of a VPC Access Connector can be specified in terms of **throughput**.

### Actual Behavior

When only having the parameters "min_instances" / "max_instances" specified in the terraform configuration, terraform seems to assume a default value for "max_throughput" of 1000 and thus always sees a deviation in state, whenever the "max_instances" < 10. 
The default value for "max_throughput" of 1000 would refer to "max_instances" of 10. Whenever "max_instances" has a value different than 10, the serverless VPC access gets redeployed in every "terraform apply".

When only using the parameters "min_throughput" / "max_throughput" instead of "min_instances" / "max_instances" it is working as expected and no re-deployment is happening.

### Steps to Reproduce

Terraform apply needs to be executed twice with the above configuration.

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
sending 
```
{
 "machineType": "e2-standard-4",
 "maxInstances": 3,
 "minInstances": 2,
 "minThroughput": 200,
 "subnet": {
  "name": "issue9228"
 }
}
```
leads to 
```
{
  "error": {
    "status": "INVALID_ARGUMENT", 
    "message": "Connector maximum throughput must be a multiple of 100 between 200 and 1000 in Mbps.", 
    "code": 400
  }
}
```

**Comment by edwardmedia** [comment]
API returns 300 for `max_throughput` if it is not set. Change its default to 300.
