### ISSUE TITLE
Test Failure: TestAccMemcacheInstance_memcacheInstanceBasicExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9233]
```
provider_test.go:268: Step 1/2 error: Error running pre-apply refresh:
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
```

Failing consistently since Apr. 23

**Comment by edwardmedia** [comment]
This issue may be related to https://github.com/GoogleCloudPlatform/magic-modules/pull/4707

**Comment by melinath** [comment]
For additional context, here's a test failure prior to merging that PR: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/182719?buildTab=tests&status=all&pager.currentPage=1&name=TestAccMemcacheInstance_memcacheInstanceBasicExample&expandedTest=3041568605595415113

Here's the failure after merging that PR: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/182902?buildTab=tests&status=all&pager.currentPage=1&name=TestAccMemcacheInstance_memcacheInstanceBasicExample&expandedTest=3041568605595415113

[It doesn't look like this test was running on GA at all at the time.](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/182882?buildTab=tests&name=TestAccMemcacheInstance_memcacheInstanceBasicExample&pager.currentPage=1&status=all)

The first GA run I see for it is on Apr. 23rd: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/183764?buildTab=tests&status=all&pager.currentPage=1&name=TestAccMemcacheInstance_memcacheInstanceBasicExample&expandedTest=3041568605595415113 (and it is failing with the "could not load plugin" error again.)

It looks like when memcached was [promoted to GA on Apr. 22nd](https://github.com/GoogleCloudPlatform/magic-modules/pull/4709), the tests were not updated. Now that it's GA I think they're supposed to not specify a particular provider.

**Comment by melinath** [comment]
Correction: the PR promoting memcached to GA was concurrent to the PR fixing the test for beta - and they didn't conflict. So even though the promotion PR did remove the google-beta from all the other tests, the beta test fix PR slipped past (and broke the tests once it was GA.)
