### ISSUE TITLE
Test failure: Quota 'SUBNETWORKS' exceeded

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9236]
### Affected Resource(s)

* google_compute_router_nat
* google_compute_router_peer

The following tests are failing consistently:
- [TestAccComputeRouterNat_update](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/189260?buildTab=tests&status=failed&expandedTest=-1323705874708314492)
- [TestAccComputeRouterPeer_advertiseMode](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/189260?buildTab=tests&status=failed&pager.currentPage=1&expandedTest=-156064009061301858)
- [TestAccComputeRouterPeer_basic](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/189234?buildTab=tests&pager.currentPage=1&expandedTest=52391852189696790)

**Comment by rileykarson** [comment]
We may want to reduce the number of auto_create_subnetworks networks, I don't think this is due to leaked resources.

**Comment by mitj04** [comment]
As per the new runs of tests, adding priority/2 label.

[TestAccComputeRouterPeer_basic](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=52391852189696790&tab=testDetails)
[TestAccComputeRouterNat_update](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-1323705874708314492&tab=testDetails)
[TestAccComputeRouterPeer_advertiseMode](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-156064009061301858&tab=testDetails)

**Comment by mitj04** [comment]
b/261374368

**Comment by roaks3** [comment]
I'm not seeing these errors at all anymore. The issue could have been resolved by other measures, including cleanup / sweeper fixes.
