### ISSUE TITLE
Flakey test: Successful backup required for carrying out the operation was not found.

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9239]
### Affected Resource(s)

* google_sql_database_instance

Impacted tests:
- TestAccSqlDatabaseInstance_basicClone
- TestAccSqlDatabaseInstance_cloneWithSettings

Error message:

```
Error 400: Successful backup required for carrying out the operation was not found.
```

Error rate:
- [fail ~75% of the time](https://ci-oss.hashicorp.engineering/test/7309789566661006962?currentBuildTypeId=GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject&currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)
- 71% in October 2021
- 74.2% in Jan 2022

TestAccSqlDatabaseInstance_basicClone:
- 74% in May 2022

TestAccSqlDatabaseInstance_cloneWithSettings:
- 74% in May 2022

**Comment by rileykarson** [comment]
Note: this is likely an issue with the bootstrapping of the instance

**Comment by mitj04** [comment]
TestAccSqlDatabaseInstance_basicClone

[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=1228032783000337365&tab=testDetails) - 56.8% success rate (38 failures)

[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=1228032783000337365&tab=testDetails) - 53.9% success rate (41 failures)

TestAccSqlDatabaseInstance_cloneWithSettings

[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=7309789566661006962&tab=testDetails) - 56.8% success rate (38 failures)

[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=7309789566661006962&tab=testDetails) - 52.8% success rate (42 failures)

**Comment by roaks3** [comment]
I'm not exactly sure what state this was in previously, but on Feb 10, 2023, it looks like the bootstrapped SQL instance and backup that these tests rely on was recreated, and both tests have been passing since. Considering this one resolved.
