### ISSUE TITLE
Flakey test: TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9241]
### Affected Resource(s)

* google_bigquery_job

Failure rate:
- 16% in May 2022

Impacted tests:
- TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/301968?buildTab=tests&expandedTest=-3890092861340691398

Message:

```
provider_test.go:309: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
# google_project_iam_member.encrypt_role will be created
+ resource "google_project_iam_member" "encrypt_role" {
+ etag    = (known after apply)
+ id      = (known after apply)
+ member  = "serviceAccount:bq-<number>@bigquery-encryption.iam.gserviceaccount.com"
+ project = "<project-id>"
+ role    = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by mitj04** [comment]
Current Passing Rate: 93% ([TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-3890092861340691398&tab=testDetails))

**Comment by mitj04** [comment]
Just want to highlight here that it's only failed 4 times in the history of TeamCity builds and it's been passing since 25th Nov, 2022. Also, I'm not getting any particular reason for failing in the instances of failures by looking at the failure. I checked the subsequent build run(in which it was passing) after it failed, there I didn't get any file changes which are impacting this Test file in order to fix this.

**Comment by mitj04** [comment]
b/261682467

**Comment by roaks3** [comment]
This appears to be resolved. There are no failures of this test in our history at the moment (save for one known issue that came up with `max_time_travel_hours`).
