### ISSUE TITLE
google_secret_manager_secret_version produces changes in plan after v3.69.0 release

### ISSUE THREAD

**Issue by iva-bashmat** [hashicorp/terraform-provider-google#9248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.69.0

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_service_account" "test-service-account" {
  project      = var.project_id
  account_id   = var.test_account_id
  display_name = var.test_display_name
}

resource "google_service_account_key" "test-service-account-key" {
  service_account_id = google_service_account.test-service-account.id
}

resource "google_secret_manager_secret" "test-service-account-secret" {
  secret_id = var.secret_id
  project   = var.project_id

  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "test-service-account-key" {
  secret      = google_secret_manager_secret.test-service-account-secret.id
  secret_data = base64decode(google_service_account_key.test-service-account-key.private_key)
}
```

### Expected Behavior

Plan should not contain any changes

### Actual Behavior

All `google_secret_manager_secret_version` are marked as change required
```
  # module.test-sa.google_secret_manager_secret_version.tets-service-account-key will be updated in-place
  ~ resource "google_secret_manager_secret_version" "test-service-account-key" {
      - destroy_time = "" -> null
        id           = "projects/sensetive/secrets/test-secret-key/versions/2"
        name         = "projects/sensetive/secrets/test-secret-key/versions/2"
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change
      ~ secret_data  = (sensitive value)
        # (3 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. `terraform apply` using v3.68.0 (skip if you already have secret version available)
1. `terraform apply` using v3.69.0 - produces changes in secret version

### Important Factoids

This behavior appears since last release v3.69.0

**Comment by edwardmedia** [comment]
@iva-bashmat I can't repro this. I applied your above config first with v3.68.0 and then upgrade to v3.69.0. With plan and apply, I did not see the diff. Can you share the debug logs for the execution with both versions?

**Comment by edwardmedia** [comment]
@iva-bashmat is this still an issue?

**Comment by iva-bashmat** [comment]
@edwardmedia I cannot reproduce it now (tried switching version 3.66, 3.67, 3.68 and 3.69). Also, i have applied these changes on my env, so cannot get debug options. 
Please close ticket, sorry for bothering
