### ISSUE TITLE
Error creating instance: googleapi: Error 503: Internal error on google_compute_instance_from_template resource

### ISSUE THREAD

**Issue by davidg251** [hashicorp/terraform-provider-google#9260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```tfTerraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.69.0
```

### Affected Resource(s)

* google_compute_instance_from_template

### Terraform Configuration Files

I'm using the example to create a new instance template https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template . Terraform is creating the template successfully. But for the VM Google API is showing the error on Debug Output section.

With this file terraform apply doesn't work.
https://gist.github.com/nan140114/2791cce40e746073f99ee96f5e8d9994

After remove the 
```resource_policies = [google_compute_resource_policy.daily_backup.id]```
on ***disk*** block. It works.
With this file terraform apply does work.
https://gist.github.com/nan140114/0f80d962876be5a808f5db51ed55e6b4

I tried creating the a new VM from the template via GCP Console and it worked.

### Debug Output

https://gist.github.com/nan140114/31651576f90ee48e9e7d910bffddae9e
### Expected Behavior
A new virtual created from the specified instance template

A new VM created from the template
### Actual Behavior
Error on VM creation.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -var-file=./envs/development.tfvars`
3. `terraform apply -auto-approve  -parallelism=1 -var-file=./envs/development.tfvars`
### Important Factoids

The terraform plan is OK.

### References

b/308756318

**Comment by edwardmedia** [comment]
We should send the **_id_** instead of the **_name_** for **resourcePolicies**. Below is the current implementation which has the problem

```
POST /compute/beta/projects/projects/myproject/zones/us-central1-a/instances?alt=json&prettyPrint=false&sourceInstanceTemplate=projects%2Fmyprojectt%2Fglobal%2FinstanceTemplates%2Fissue9260 
Host: www.googleapis.com

{
 "disks": [
  {
   "autoDelete": true,
   "boot": true,
   "deviceName": "persistent-disk-0",
   "initializeParams": {
    "diskType": "zones/us-central1-a/diskTypes/pd-standard",
    "resourcePolicies": [
     "issue9260"
    ],
    "sourceImage": "projects/debian-cloud/global/images/family/debian-9"
   },
   "interface": "SCSI",
   "kind": "compute#attachedDisk",
   "mode": "READ_WRITE",
   "type": "PERSISTENT"
  }
 ],
 "metadata": {},
 "name": "instance-from-issue9260",
 "scheduling": {
  "automaticRestart": true,
  "onHostMaintenance": "MIGRATE"
 },
 "tags": {},
 "zone": ""
}
```

**Comment by edwardmedia** [comment]
Noticed the data format of `resourcePolicies`, it is a shortname returned from api but when creating an instance, it requires the format like `projects/%s/regions/%s/resourcePolicies/%s`. The provider rely on whatever returned from the template to create an instance.

**Comment by osuarez84** [comment]
I am facing the same issue here when using the example to develop my module code. Is there any work around to make this work?

**Comment by nan140114** [comment]
I just removed the block.

**Comment by ndlanier** [comment]
Was there ever a workaround or resolution to this. Currently running into this issue

**Comment by melinath** [comment]
It looks like we have workarounds for similar cases for disk.initialize_params.disk_type and disk.source_image: https://github.com/hashicorp/terraform-provider-google/blob/4a1460e095d64cbfade02da4207a66bbbf860894/google/resource_compute_instance_from_template.go#L223 According to the comment, it's necessary to allow overrides to work correctly on a per-disk basis.

However, we don't actually currently support disk resource policies on compute instances at all - we just modify the array of disks to add whatever was on the instance template. Since instance templates [support disk resource policies](https://github.com/hashicorp/terraform-provider-google/pull/8237), those can get passed through to compute instances implicitly without their formatting getting updated to specify a full path.

I think this is not actually an upstream bug.

**Comment by melinath** [comment]
In terms of workarounds - managing compute instances directly or using [google_compute_instance_group_manager](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager) may be a better option.

**Comment by melinath** [comment]
I wonder if we could consider making this resource not try to override any fields if no overrides are provided on the resource.

**Comment by karolgorc** [comment]
Working on a pr supporting disk resource policies on instance
