### ISSUE TITLE
etags keep trying to change

### ISSUE THREAD

**Issue by esn89** [hashicorp/terraform-provider-google#9261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

I am trying to understand why this is happening.  On TF 0.14 when I do `terragrunt apply` everything is clean and it returns with no infrastructure change.

On TF 0.15, with the GCP provider version of: `v3.69.0` it spits out a bunch of scary looking changes about etags.

### Terraform Version
0.15.4

### Affected Resource(s)
```
Terraform detected the following changes made outside of Terraform since the
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
relevant attributes using ignore_changes, the following plan may include

 # module.gke-gcr-iam.google_project_iam_member.project_iam_additive["myproject--roles/dataflow.admin--serviceAccount:tf-gke-mycluster-lmay@mycurrentproject.iam.gserviceaccount.com"] has been changed
  ~ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "BwXDG76answ=" -> "BwXDRLwaWr4="
        id      = "myproject/roles/dataflow.admin/serviceaccount:tf-gke-mycluster-lmay@mycurrentproject.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # module.gke-gcr-iam.google_project_iam_member.project_iam_additive["gcp-container-registry--roles/storage.admin--serviceAccount:tf-gke-mycluster-lmay@mycurrentproject.iam.gserviceaccount.com"] has been changed
  ~ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "BwXBv8IKxeM=" -> "BwXDS3QXBcM="
        id      = "gcp-container-registry/roles/storage.admin/serviceaccount:tf-gke-mycluster-lmay@mycurrentproject.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
 .....
 Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
 ```

### Terraform Configuration Files

```tf
module "gke-gcr-iam" {
  source   = "git::https://github.com/terraform-google-modules/terraform-google-iam.git//modules/projects_iam?ref=v5.1.0"
  mode     = "additive"
  projects = ["myproject"]

  bindings = {
    "roles/storage.admin" = [
      "serviceAccount:${data.terraform_remote_state.gke.outputs.service_account}",
    ]

    "roles/dataflow.admin" = [
      "serviceAccount:${data.terraform_remote_state.gke.outputs.service_account}",
    ]
  }
  ...
}


```

### Expected Behavior
I expect that, that long message about etags change shouldn't come up.

### Actual Behavior
A lot of changes are happening to the etags

### Steps to Reproduce

1. `terragrunt plan`

### References

https://github.com/terraform-google-modules/terraform-google-iam/issues/140

**Comment by edwardmedia** [comment]
@esn89 I tested by switching Terraform version back and forth between **_v0.14.5_** and **_v0.15.4_** and can't repro the issue. Under both conditions, the provider first checks if there is diff in the policy based on the same below call, which does not touch the field `etag`. API does issue a new `etag` after a diff is detected and new policy is set. By updating the Terraform version, I don't see the diff in the policy at the very beginning thus no new `etag` is issued. Because in your case, a module is used so it is hard to tell what causes the new `etag` being issued. Can you try by running a single `google_project_iam_member` between different versions to see if you can repro it? Or you can post the debug log so I can take a look. Basically we want to see what triggers a call with `setIamPolicy`. Does this make sense?

Also I notice below `No changes` at the bottom ....

> No changes. Your infrastructure matches the configuration.

```
POST /v1/projects/myproject:getIamPolicy
Host: cloudresourcemanager.googleapis.com

{
 "options": {
  "requestedPolicyVersion": 3
 }
}
```

**Comment by muffl0n** [comment]
I had the same with Terraform v0.15.4 and provider v3.70.0. Running `terraform apply -refresh-only` fixed it, for now.

**Comment by edwardmedia** [comment]
@esn89 running `terraform apply -refresh-only` solves your problem?

**Comment by esn89** [comment]
Hi there, this works!  Thanks!
