### ISSUE TITLE
Terraform GCP Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by PrateekKhatri** [hashicorp/terraform-provider-google#9263]
Getting below error while terraform apply:

When applying changes to module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0], provider "provider[\"registry.terraform.io/hashicorp/google\"]"  produced an unexpected new value: Root resource was present, but now absent.  This is a bug in the provider, which should be reported in the provider's own issue tracker.

Terraform version: 0.15.3
Google provider version: 3.67.0

**Comment by edwardmedia** [comment]
@PrateekKhatri can you share your config and the full debug log?

**Comment by PrateekKhatri** [comment]
Hi, 

**Please find the config file below:**

resource "google_storage_bucket" "bucket_complaint" {
  count                       = var.infra_type == "compliant" ? var.var_count : 0
  name                        = "${var.env_name}-${var.infra_type}-bucket-${count.index + 1}"
  location                    = data.google_compute_regions.available.names[index(data.google_compute_regions.available.names, element(var.region_name, count.index))]
  uniform_bucket_level_access = true
  retention_policy {
    retention_period = 2147483600
  }
  encryption {
    default_kms_key_name = "projects/${var.project_name}/locations/${var.deployment_location}/keyRings/${var.key_ring_name}/cryptoKeys/${var.key_name}"
  }
  lifecycle_rule {
    condition {
      age = 3
    }
    action {
      type = "Delete"
    }
  }
}

resource "null_resource" "bucket_logging" {
  count      = var.infra_type == "compliant" ? 1 : 0
  depends_on = [google_storage_bucket.bucket_complaint]

  provisioner "local-exec" {
    command     = "..//..//infra_samples//modules//storage_bucket//bucket_logging.ps1 -Service_Account_Email ${var.serviceaccount_email} -Bucket_Name ${google_storage_bucket.bucket_complaint[count.index].name}"
    interpreter = ["PowerShell", "-Command"]
  }
}

resource "google_storage_bucket_iam_binding" "binding" {
  count   = var.var_count
  bucket  = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role    = var.infra_type == "compliant" ? "roles/storage.admin" : "roles/storage.legacyBucketReader"
  members = var.infra_type == "compliant" ? ["user:test@gmail.com", ] : ["allUsers", "allAuthenticatedUsers"]
}

resource "google_storage_bucket_iam_member" "legacy_writer" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.legacyBucketWriter"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "legacy_reader" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.legacyBucketReader"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "legacy_owner" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.legacyBucketOwner"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "legacy_object_reader" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.legacyObjectReader"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "legacy_object_owner" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.legacyObjectOwner"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "object_creator" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.objectCreator"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "object_viewer" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.objectViewer"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "object_admin" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.objectAdmin"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

resource "google_storage_bucket_iam_member" "storage_admin" {
  count  = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role   = "roles/storage.admin"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}

--------------------------------------------------------------------------------------------------------------------------

**Error Logs:**

**After terraform apply:**

module.kms[0].random_id.id: Creating...
module.kms[0].random_id.id: Creation complete after 0s [id=B5svrw]
module.kms[0].google_kms_key_ring.key_ring: Creating...
module.kms[0].google_kms_key_ring.key_ring: Creation complete after 4s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf]
module.kms[0].google_kms_crypto_key.key_ephemeral[0]: Creating...
module.kms[0].google_kms_crypto_key.key_ephemeral[1]: Creating...
module.kms[0].google_kms_crypto_key.key_ephemeral[0]: Creation complete after 3s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-01]
module.kms[0].google_kms_crypto_key.key_ephemeral[1]: Creation complete after 3s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-02]
module.kms[0].google_kms_crypto_key_iam_binding.owners[1]: Creating...
module.kms[0].google_kms_crypto_key_iam_binding.owners[0]: Creating...
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[1]: Creating...
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[0]: Creating...
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[1]: Still creating... [10s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[0]: Still creating... [10s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.owners[0]: Still creating... [10s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.owners[1]: Still creating... [10s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.owners[1]: Still creating... [20s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.owners[0]: Still creating... [20s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[0]: Still creating... [20s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[1]: Still creating... [20s elapsed]
module.kms[0].google_kms_crypto_key_iam_binding.owners[0]: Creation complete after 26s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-01/roles/owner]
module.kms[0].google_kms_crypto_key_iam_binding.owners[1]: Creation complete after 26s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-02/roles/owner]
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[0]: Creation complete after 27s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-01/roles/cloudkms.cryptoKeyEncrypterDecrypter]
module.kms[0].google_kms_crypto_key_iam_binding.encrypter_decrypter_permission[1]: Creation complete after 27s [id=projects/project_name/locations/us-central1/keyRings/pkz-compliant-keyring-079b2faf/cryptoKeys/compliant-key-02/roles/cloudkms.cryptoKeyEncrypterDecrypter]
module.storage_bucket[0].google_storage_bucket.bucket_complaint[0]: Creating...
module.storage_bucket[0].google_storage_bucket.bucket_complaint[0]: Creation complete after 3s [id=pkz-compliant-bucket-1]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Creating...
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [20s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [30s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [40s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [50s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Still creating... [1m0s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_reader[0]: Creation complete after 1m5s [id=b/pkz-compliant-bucket-1/roles/storage.legacyObjectReader/user:user@gmail.com]
module.storage_bucket[0].null_resource.bucket_logging[0]: Creating...
module.storage_bucket[0].null_resource.bucket_logging[0]: Provisioning with 'local-exec'...
module.storage_bucket[0].null_resource.bucket_logging[0] (local-exec): Executing: ["PowerShell" "-Command" "..//..//infra_samples//modules//storage_bucket//bucket_logging.ps1 -Service_Account_Email vm-@project_name.iam.gserviceaccount.com -Bucket_Name pkz-compliant-bucket-1"]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_object_owner[0]: Creation complete after 1m6s [id=b/pkz-compliant-bucket-1/roles/storage.legacyObjectOwner/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_member.object_viewer[0]: Creation complete after 1m6s [id=b/pkz-compliant-bucket-1/roles/storage.objectViewer/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_member.object_creator[0]: Creation complete after 1m8s [id=b/pkz-compliant-bucket-1/roles/storage.objectCreator/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_reader[0]: Creation complete after 1m8s [id=b/pkz-compliant-bucket-1/roles/storage.legacyBucketReader/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_member.object_admin[0]: Creation complete after 1m9s [id=b/pkz-compliant-bucket-1/roles/storage.objectAdmin/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_binding.binding[0]: Creation complete after 1m9s [id=b/pkz-compliant-bucket-1/roles/storage.admin]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Still creating... [1m10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Still creating... [1m10s elapsed]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_owner[0]: Creation complete after 1m10s [id=b/pkz-compliant-bucket-1/roles/storage.legacyBucketOwner/user:user@gmail.com]
module.storage_bucket[0].google_storage_bucket_iam_member.legacy_writer[0]: Creation complete after 1m11s [id=b/pkz-compliant-bucket-1/roles/storage.legacyBucketWriter/user:user@gmail.com]
module.storage_bucket[0].null_resource.bucket_logging[0] (local-exec): Enabling logging on gs://pkz-compliant-bucket-1/...
module.storage_bucket[0].null_resource.bucket_logging[0]: Creation complete after 9s [id=3638291127670016226]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.storage_bucket[0].google_storage_bucket_iam_member.storage_admin[0], provider "provider[\"registry.terraform.io/hashicorp/google\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by edwardmedia** [comment]
@PrateekKhatri looks like below resources trying to manage a same role `roles/storage.admin`. Is that you intended to do?

``tf
resource "google_storage_bucket_iam_binding" "binding" {
  count = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role = var.infra_type == "compliant" ? "roles/storage.admin" : "roles/storage.legacyBucketReader"
  members = var.infra_type == "compliant" ? ["user:test@gmail.com", ] : ["allUsers", "allAuthenticatedUsers"]
}
```

```tf
resource "google_storage_bucket_iam_member" "storage_admin" {
  count = var.var_count
  bucket = var.infra_type == "compliant" ? google_storage_bucket.bucket_complaint[count.index].name : google_storage_bucket.bucket_non_complaint[count.index].name
  role = "roles/storage.admin"
  member = var.infra_type == "compliant" ? "user:user@gmail.com" : "allUsers"
}
```

**Comment by edwardmedia** [comment]
@PrateekKhatri is this still an issue?

**Comment by PrateekKhatri** [comment]
Hi,
Thanks.. it was my mistake I have added same roles at both the place. after updating the code it is working fine now. Thanks for your help.

**Comment by edwardmedia** [comment]
@PrateekKhatri I am glad your problem is resolved. Closing the issue then
