### ISSUE TITLE
google_notebooks_instance don't persist tags in state

### ISSUE THREAD

**Issue by debakkerb** [hashicorp/terraform-provider-google#9273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
terraform -v
Terraform v0.15.3
```
### Affected Resource(s)

* google_notebooks_instance

### Terraform Configuration Files

```tf
resource "google_service_account" "notebook_identity" {
  project    = var.project_id
  account_id = "notebook-id-${var.environment}"
}

resource "random_id" "randomizer" {
  byte_length = 2
}

resource "google_notebooks_instance" "default" {
  project         = var.project_id
  name            = "${var.notebook_name}-${var.environment}-${random_id.randomizer.hex}"
  location        = var.zone
  machine_type    = var.machine_type
  network         = var.network_selflink
  subnet          = var.subnetwork_selflink
  no_public_ip    = true
  no_proxy_access = true

  boot_disk_size_gb = var.boot_disk_size
  boot_disk_type    = var.boot_disk_type

  vm_image {
    project      = var.vm_image_project_id
    image_family = var.vm_image_family
  }

  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = true
    enable_vtpm                 = true
  }

  service_account = google_service_account.notebook_identity.email

  labels = var.instance_labels
  tags   = ["iap-access-ssh"]

}
```

### Expected Behavior

Terraform state shows the tags and it doesn't recreate the notebook instance when I'm not updating anything.

### Actual Behavior

The resource gets recreated every time I ran a `terraform apply`, because for some reason the tags are not persisted in the state.  They show up as an empty list each time I give it a spin.  The strange thing is that the underlying instance does have the tag I'm trying to apply.

Here's the output for when I run `terraform state show RESOURCE`

```tf
resource "google_notebooks_instance" "default" {
    boot_disk_size_gb  = 110
    boot_disk_type     = "PD_SSD"
    create_time        = "2021-06-01T19:59:27.982042194Z"
    id                 = "projects/[PROJECT_ID]/locations/europe-west3-a/instances/[NOTEBOOK_ID]"
    install_gpu_driver = false
    labels             = {
        "goog-caip-notebook" = ""
    }
    location           = "europe-west3-a"
    machine_type       = "n1-standard-4"
    name               = [NOTEBOOK_ID]
    network            = "https://www.googleapis.com/compute/v1/projects/[NETWORK_PROJECT_ID]/global/networks/[NETWORK]"
    no_proxy_access    = true
    no_public_ip       = true
    project            = [PROJECT_ID]
    service_account    = [SERVICE_ACCOUNT]
    state              = "PROVISIONING"
    subnet             = "https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/regions/europe-west3/subnetworks/[SUBNET_NAME]"
    tags               = []
    update_time        = "2021-06-01T19:59:44.996188295Z"

    shielded_instance_config {
        enable_integrity_monitoring = true
        enable_secure_boot          = true
        enable_vtpm                 = true
    }

    vm_image {
        image_family = "tf-latest-cpu"
        project      = "deeplearning-platform-release"
    }
}
```

**Comment by venkykuberan** [comment]
@debakkerb sorry for the delay in responding. Do you see `tags` coming back in the api response ?

**Comment by edwardmedia** [comment]
No response. Assuming this is on longer an issue
