### ISSUE TITLE
google provider google_storage_bucket Documentation BUG  for days_since_custom_time

### ISSUE THREAD

**Issue by mike-19** [hashicorp/terraform-provider-google#9276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Documentation BUG 

This is a documentation error as per the discussions here [1]
This seems to be a bug in the Google provider documentation. The source code shows that the type is an integer
https://github.com/hashicorp/terraform-provider-google/blob/3ebd09f04ed16e112f9c72070bd42f6e25c97f9f/google/resource_storage_bucket.go#L171-L175

Please correct the documentation references, google provider documentation has the wrong format described [3] instead a number of days its referencing Date in RFC 3339

[1]https://discuss.hashicorp.com/t/query-on-resource-google-storage-bucket/24953/2

[3]https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#days_since_custom_time

### Affected Resource(s)

* google-storage-bucket

**Comment by rileykarson** [comment]
Note: While the source code appears to have the right docs, the registry seems to be off.
