### ISSUE TITLE
How to emulate a gcloud app deploy cron.yaml call?

### ISSUE THREAD

**Issue by thedmeyer** [hashicorp/terraform-provider-google#9287]
Does the provider support the ability to submit a `cron.yaml` equivalent with either the `google_app_engine_standard_app_version` or the `google_app_engine_flexible_app_version` resource?

As far as I can tell the only way to do this is by moving crons into cloud scheduler but then these are not managed under app engine.

**Comment by thedmeyer** [comment]
Some supporting info:
https://cloud.google.com/appengine/docs/flexible/nodejs/scheduling-jobs-with-cron-yaml
<img width="1754" alt="Screen Shot 2021-06-04 at 2 53 08 PM" src="https://user-images.githubusercontent.com/2959172/120861492-9f89fa80-c544-11eb-907b-515194cf7b75.png">

**Comment by edwardmedia** [comment]
@thedmeyer below is what the [doc](https://cloud.google.com/appengine/docs/flexible/nodejs/scheduling-jobs-with-cron-yaml#about) says. Have you tried putting the **cron.yaml** alongside the **app.yaml**?

> A cron.yaml file in the root directory of your application (alongside app.yaml) configures scheduled tasks for your Node.js application.

**Comment by thedmeyer** [comment]
> @thedmeyer below is what the [doc](https://cloud.google.com/appengine/docs/flexible/nodejs/scheduling-jobs-with-cron-yaml#about) says. Have you tried putting the **cron.yaml** alongside the **app.yaml**?
> 
> > A cron.yaml file in the root directory of your application (alongside app.yaml) configures scheduled tasks for your Node.js application.

Correct. That is the app engine native way of doing it. However, I am wondering how to set up crons that are managed by app engine (the app engine tab in cloud scheduler) rather than the regular cloud scheduler using a terraform resource similar to:

```
resource "google_cloud_scheduler_job" "job" {
  name             = "test-job"
  schedule         = "*/4 * * * *"
  description      = "test app engine job"
  time_zone        = "Europe/London"
  attempt_deadline = "320s"

  app_engine_http_target {
    http_method = "POST"

    app_engine_routing {
      service  = "web"
      version  = "prod"
      instance = "my-instance-001"
    }

    relative_uri = "/ping"
  }
}
```

**Comment by thedmeyer** [comment]
Also -- if the cron.yaml is included in the source code zip passed into the `google_app_engine_standard_app_version` it does not get recognized by GCP after deploy. See: https://stackoverflow.com/questions/53255084/google-app-engine-cron-job-not-showing-up

**Comment by edwardmedia** [comment]
@thedmeyer from the screenshot I provided, I don't see a way you can create an instance under `APP ENGINE CRON JOBS` tab (vs  there is a `Create Job` under `SCHEDULER JOBS` tab). Can you be more specific how you achieved via other non-Terraform methods?

**Comment by thedmeyer** [comment]
@edwardmedia Cron jobs that are defined in the App Engine `cron.yaml` and are uploaded using `gcloud app deploy cron.yaml` appear in the `APP ENGINE CRON JOBS` tab under Cloud Scheduler.

This is the only way to create jobs in this section.

**Comment by edwardmedia** [comment]
@thedmeyer  oh I see. I guess this feature has not been implemented yet. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) for it then.
