### ISSUE TITLE
Support for Vertex AI resources 

### ISSUE THREAD

**Issue by charles-bluett** [hashicorp/terraform-provider-google#9298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently none of the recently released Vertex AI resources are supported by the terraform provider.

https://cloud.google.com/vertex-ai/docs/reference

### New or Affected Resource(s)

* google_vertex_ai_*

Batch Predictions
CustomJobs
dataLabeling
~datasets~
~endpoints~
~Feature stores (v1beta1)~
hyperparameter Tuning Jobs
~indexEndpoints (v1beta1)~
~indexs (v1beta1)~
~metadata stores (v1beta1)~
Model deployment monitoring Jobs (v1beta1)
Models
operations
pipeline Jobs
Specialist Pools
studies (v1beta1)
~tensorboards (v1beta1)~
Training Pipelines

### References

https://cloud.google.com/vertex-ai/docs/reference
There is an existing request for Feature Stores https://github.com/hashicorp/terraform-provider-google/issues/9264

* #0000

**Comment by jamiet-msm** [comment]
Would really really like to see Feature Store supported please folks!

**Comment by upodroid** [comment]
It is being worked on.

**Comment by marktru** [comment]
This needs to have the milestone unassigned and a P1 priority. Relates to issue http://b/199214105.

**Comment by shotarok** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/6759 added `google_vertex_ai_tensorboard`.

**Comment by melinath** [comment]
Since about half of the requested resources have been implemented, we're closing this issue; it's not possible to tell how many of the thumbs are due to resources that have already been implemented. For anyone following this issue: Please open new (individual) issues for any resources that you want to see in the providers that are not yet supported. Thank you!
