### ISSUE TITLE
Cloud Composer Resource doesn't allow to be created with naming including `preview` due to regex. 

### ISSUE THREAD

**Issue by juzov-mag** [hashicorp/terraform-provider-google#9314]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.14.0

### Affected Resource(s)

* google_3.70.0

### Terraform Configuration Files

```tf
resource "google_composer_environment" "composer_dm_development" {
  name    = "dm-development"
  project = google_project.project.project_id
  region  = "us-central1"
  config {
    node_count = 3

    node_config {
      zone         = "us-central1-a"
      machine_type = "n1-standard-1"

      service_account = google_service_account.sa.name
    }
    software_config {
      image_version  = "composer-1.17.0-preview.1-airflow-2.0.1"
      python_version = 3
    }
  }
}

```

### Expected Behavior

Terraform should accept versons including `preview`

### Actual Behavior

```
Error: "config.0.software_config.0.image_version" ("composer-1.17.0-preview.1-airflow-2.0.1") doesn't match regexp "composer-([0-9]+\\.[0-9]+\\.[0-9]+|latest)-airflow-([0-9]+\\.[0-9]+(\\.[0-9]+.*)?)"
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by c2thorn** [comment]
This was fixed in 3.71.0: https://github.com/hashicorp/terraform-provider-google-beta/pull/3287
Please update your provider and try again.
