### ISSUE TITLE
Failing test: TestAccSecurityCenterSource_basic

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-provider-google#9316]
Seems like maybe something changed upstream, but TestAccSecurityCenterSource_basic fails with `Request contains an invalid argument`

**Comment by upodroid** [comment]
Did you upgrade SCC to Standard/Premium?

Google said they would be permanently disabling SCC legacy today(07/06/2021).

https://cloud.google.com/security-command-center/docs/legacy-products-migration

**Comment by megan07** [comment]
Closing as this has been succeeding for 90+ days now
