### ISSUE TITLE
VPC service control supported on VPC peering connections?

### ISSUE THREAD

**Issue by Celestica-Edward** [hashicorp/terraform-provider-google#9317]
### Affected Resource(s)

* google_service_networking_*

Hi,

We would like to manage this in terraform:
https://cloud.google.com/sdk/gcloud/reference/services/vpc-peerings/enable-vpc-service-controls
https://cloud.google.com/sdk/gcloud/reference/services/vpc-peerings/disable-vpc-service-controls

Example:
gcloud services vpc-peerings enable-vpc-service-controls \
    --network=xxxxx  \
    --service=servicenetworking.googleapis.com

This is used at least in peering connections to GCP VMware engine:
https://cloud.google.com/vmware-engine/docs/networking/howto-setup-internet-access#enable_internet_access_by_using_an_on-premises_connection

## References

* b/312371408

**Comment by mmalet-sky** [comment]
We are also needing this feature, I expect it'll need to be added as an `vpc_service_controls_enabled = {true|false}` option on the `service_networking_connection`

**Comment by roaks3** [comment]
b/251560503

**Comment by roaks3** [comment]
This issue is blocked as we work with the service team to provide a way to read this value.

**Comment by rileykarson** [comment]
Not having that isn't great, but is only really a blocked for import. We can manage the enablement status in Terraform state- it just might drift.

**Comment by juliocc** [comment]
The API for this just became available (see b/263492666). 

I have a customer waiting for this to become available in terraform. If no one is working on this, I have some bandwidth to give it a try. 

Let me know if thats OK.

**Comment by rileykarson** [comment]
I'd suggest flagging you're looking at it on the service's Terraform-specific issue (b/312371408, linked from the GH issue parent) but other than any concerns raised there (I don't expect any) should be fine to do so.

**Comment by c2thorn** [comment]
closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10899
