### ISSUE TITLE
google_composer_environment does not allow image version "composer-1.17.0-preview.1-airflow-2.0.1"

### ISSUE THREAD

**Issue by al-dann** [hashicorp/terraform-provider-google#9318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

hashicorp/google v3.70.0

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
resource "google_composer_environment" "composer_env" {
  project = "aaaaa"
  name    = "bbbbb"
  region  = "cccc"

  config {
    node_count = 3

    node_config {
      ...
    }

    software_config {
      image_version  = "composer-1.17.0-preview.1-airflow-2.0.1"

      python_version = 3

      airflow_config_overrides = {
        api-auth_backend  = "airflow.api.auth.backend.default"
      }
    }

    private_environment_config {
      enable_private_endpoint = true
    }
  }
}

```

### Expected Behavior

Should not through an error, as that version name is correct (according to Google - https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images)

### Actual Behavior

Error: "config.0.software_config.0.image_version" ("composer-1.17.0-preview.1-airflow-2.0.1") doesn't match regexp "composer-([0-9]+\\.[0-9]+\\.[0-9]+|latest)-airflow-([0-9]+\\.[0-9]+(\\.[0-9]+.*)?)"

### Important Factoids

The regular expression check (embedded in the provider implementation) does not correlate to actual naming used by Google

### References

https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images

**Comment by edwardmedia** [comment]
@al-dann  that **image_version**'s regexp comes from that api [spec](https://cloud.google.com/composer/docs/reference/rest/v1/projects.locations.environments) . I guess we can not use `preview` version here?
@c2thorn what do you think?

**Comment by al-dann** [comment]
Yes, that is the issue. 
If I look today - https://cloud.google.com/composer/docs/concepts/versioning/composer-versions already has the most recent version "composer-1.17.0-preview.2-airflow-2.0.1" As you work for Google, you might be able to contact that team in order clarify the difference between the version and the API constraints (or documentation being out of date).
Thanks a lot!

**Comment by edwardmedia** [comment]
@al-dann As you can tell this is not something the provider can handle. Do you have to use the `preview` version? You may file an issue against `composer`. Closing the issue here now.
