### ISSUE TITLE
For module calls the provider is sending null value upstream instead of omitting the key.

### ISSUE THREAD

**Issue by dkerr-ignw** [hashicorp/terraform-provider-google#9319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.70.0
+ provider registry.terraform.io/hashicorp/google-beta v3.70.0

### Affected Resource(s)

registry.terraform.io/hashicorp/google v3.70.0

### Terraform Configuration Files

```tf
module "memorystore" {
  source = "git::git@gitlab.com:REDACTED//modules/memorystore"

  for_each = var.memory_store_instances

  service         = "service"
  environment     = var.environment
  location        = var.location
  cost_allocation = var.cost_allocation

  name        = each.key
  type        = each.value.type
  region      = each.value.region
  memory_size = each.value.memory_size
  cpu_count   = each.value.cpu_count

  redis_ha           = null
}
```

### Debug Output

https://gist.github.com/dkerr-ignw/a30d387c76f8d4deeeda4eb5ae7511f9

### Panic Output

n/a

### Expected Behavior

The module should use it's default value (false) because redis_ha would be "unset".

In the memorystore module redis_ha is set to `false`
```tf
variable "redis_ha" {
  description = "Enable HA configuration for Redis"
  type        = bool
  default     = false
}
```

### Actual Behavior

The redis_ha default value is overriden with `null`

```
│ Error: Null condition
│ 
│   on .terraform/modules/memorystore/modules/memorystore/main.tf line 79, in module "memorystore":
│   79:   tier                    = var.redis_ha ? "STANDARD_HA" : null
│     ├────────────────
│     │ var.redis_ha is null
```

If i remove `redis_ha` from the call everything plans correctly.

### Steps to Reproduce

Attempt to use `null` in a module call to get the default value from the module itself.

### References

* #0000

**Comment by edwardmedia** [comment]
@dkerr-ignw do you suspect which resource has the issue? The config you provided is a module. I have no knowledge about it. You might want to check the owner of the module to see if they can provide assistance. If you think it is a provider issue, please try to repro it with a minimum config.

**Comment by dkerr-ignw** [comment]
I'll give it a try with a more minimal config. 
To try and explain the problem better:

https://www.terraform.io/docs/language/expressions/types.html

> Finally, there is one special value that has no type:
> 
> null: a value that represents absence or omission. If you set an argument of a resource or **module** to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

1. Basically create any module that takes an input.
2. Set a default in the module for that input.
3. call the module with that input = null

```tf
module "name" {
   input = null
}
```

Inside the module `input` should be it's default value. not `null`. 

I'll create a test case.

**Comment by dkerr-ignw** [comment]
Hm, simple example works as intended. it must be something on my side. Sorry to bother you.
