### ISSUE TITLE
Running the "Example Usage - Cloud Run Anthos" on google_cloud_run_service throws an error

### ISSUE THREAD

**Issue by amerello-otto** [hashicorp/terraform-provider-google#9320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/google v3.65.0
+ provider registry.terraform.io/hashicorp/google-beta v3.70.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.1
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.4.1

### Affected Resource(s)

google_cloud_run_service

### Terraform Configuration Files

```tf
data "google_client_config" "provider" {}

data "google_container_cluster" "my_cluster" {
  name     = "cluster-1"
  location = "us-central1-c"
}

provider "kubernetes-alpha" {
  host  = "https://${data.google_container_cluster.my_cluster.endpoint}"
  token = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.my_cluster.master_auth.0.cluster_ca_certificate,
  )
}

resource "kubernetes_manifest" "test-configmap" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "serving.knative.dev/v1"
    "kind"       = "Service"
    "metadata" = {
      "name"      = "helloworld-go"
      "namespace" = "default"
    }
    "spec" = {
      "template" = {
        "spec" = {
          "containers" = [
            {
              "image" = "us-docker.pkg.dev/cloudrun/container/hello"
            }
          ]
        }
      }
    }
  }
}
```

### Expected Behavior

Resource should be created

### Actual Behavior

Step #2 - "apply": kubernetes_manifest.test-configmap: Refreshing state...
Step #2 - "apply": kubernetes_manifest.test-configmap: Destroying...
Step #2 - "apply": kubernetes_manifest.test-configmap: Destruction complete after 1s
Step #2 - "apply": kubernetes_manifest.test-configmap: Creating...
Step #2 - "apply": 
Step #2 - "apply": Error: Provider produced inconsistent result after apply
Step #2 - "apply": 
Step #2 - "apply": When applying changes to kubernetes_manifest.test-configmap, provider
Step #2 - "apply": "registry.terraform.io/hashicorp/kubernetes-alpha" produced an unexpected new
Step #2 - "apply": value: .object: wrong final value type: incorrect object attributes.
Step #2 - "apply": 
Step #2 - "apply": This is a bug in the provider, which should be reported in the provider's own
Step #2 - "apply": issue tracker.
Step #2 - "apply": 

### Steps to Reproduce

1. `terraform apply`

**Comment by venkykuberan** [comment]
@amerello-otto error shows the issue is on the `kubernetes` provider. Can you please raise it there ..
