### ISSUE TITLE
google_compute_region_network_endpoint_group references cloudrun service name (by data ref) returns error

### ISSUE THREAD

**Issue by yolocs** [hashicorp/terraform-provider-google#9323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_region_network_endpoint_group
* data.google_cloud_run_service

### Terraform Configuration Files

```tf
variable "project" {
   type    = string
   default = "my-project"
 }

 variable "region" {
   type    = string
   default = "us-central1"
 }

 provider "google" {
   project = var.project
   region  = var.region
 }


resource "google_compute_region_network_endpoint_group" "ff-test-neg" {
   name                  = "ff-test-neg"
   network_endpoint_type = "SERVERLESS"
   region                = var.region
   cloud_run {
     service = data.google_cloud_run_service.ff-test-svc1.name
   }
 }

 resource "google_compute_backend_service" "ff-test-svc1" {
   name       = "ff-test-svc1"
   enable_cdn = false
   backend {
     group = google_compute_region_network_endpoint_group.ff-test-neg.id
   }
 }

 data "google_cloud_run_service" "ff-test-svc1" {
   name = "ff-test-svc1"
   location = var.region
 }

```

### Debug Output

```
terraform plan
╷
│ Error: AtLeastOne
│
│   with google_compute_region_network_endpoint_group.ff-test-neg,
│   on main.tf line 69, in resource "google_compute_region_network_endpoint_group" "ff-test-neg":
│   69:   cloud_run {
│
│ "cloud_run.0.url_mask": one of `cloud_run.0.service,cloud_run.0.url_mask` must be specified
╵
╷
│ Error: AtLeastOne
│
│   with google_compute_region_network_endpoint_group.ff-test-neg,
│   on main.tf line 71, in resource "google_compute_region_network_endpoint_group" "ff-test-neg":
│   71:     service = data.google_cloud_run_service.ff-test-svc1.name
│
│ "cloud_run.0.service": one of `cloud_run.0.service,cloud_run.0.url_mask` must be specified

```

### Expected Behavior

Expect the cloudrun service name could be referenced by data ref.

### Actual Behavior

See debug output.

### Steps to Reproduce

1. `terraform plan` with the terraform config pasted

**Comment by edwardmedia** [comment]
@yolocs here is an [example](google_compute_region_network_endpoint_group) that is used for cloud run. Are you able to run it instead of the **data source**? If yes, we need to compare what the differences are. Your **data source** does not tell us the details.

**Comment by yolocs** [comment]
> @yolocs here is an [example](google_compute_region_network_endpoint_group) that is used for cloud run. Are you able to run it instead of the **data source**? If yes, we need to compare what the differences are. Your **data source** does not tell us the details.

Sorry, this link gets me nowhere. FWIW, referencing a `resource google_cloud_run_service` does work for me. It's only the data reference that doesn't work.

**Comment by yolocs** [comment]
btw, it's no doubt that the cloudrun service my data source references does exist in my project.

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/9332

**Comment by yolocs** [comment]
No worries. I can confirm the example does work. It's only the **data source** of cloudrun service that doesn't work.

**Comment by edwardmedia** [comment]
@yolocs what is the value of below code? Have you compared it with the one from the example? Or you can post the debug log so we can take a close look?


>  data.google_cloud_run_service.ff-test-svc1.name

**Comment by yolocs** [comment]
I realized that I didn't create the cloudrun service (which is defined in another module) in the first place. No wonder data source can't get the cloudrun service name. The error message is a bit confusing though as it doesn't tell that the data source doesn't exist.

Anyhow, sorry about the noise.
