### ISSUE TITLE
modifying a resource fails with `Error 409: Requested entity already exists`

### ISSUE THREAD

**Issue by elouanKeryell-Even** [hashicorp/terraform-provider-google#9325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- terraform

```
$ terraform -v
Terraform v0.13.5
```

- providers:

```
- Installing hashicorp/google v3.71.0...
- Installing hashicorp/google-beta v3.71.0...
```

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

Before:

```tf
resource "google_compute_subnetwork" "cloud_run_main" {
  name          = "cloudrun-main"
  region = var.region
  ip_cidr_range = "10.0.189.0/28"
  network       = local.network
}

resource "google_vpc_access_connector" "cloud_run_main" {
  provider      = google-beta
  name          = "backend-main"
  region = var.region
  subnet {
    name = google_compute_subnetwork.cloud_run_main.name
  }
  max_throughput = 1000
}
```

After:

(change value of `max_throughput`):

```tf
resource "google_compute_subnetwork" "cloud_run_main" {
  name          = "cloudrun-main"
  region = var.region
  ip_cidr_range = "10.0.189.0/28"
  network       = local.network
}

resource "google_vpc_access_connector" "cloud_run_main" {
  provider      = google-beta
  name          = "backend-main"
  region = var.region
  subnet {
    name = google_compute_subnetwork.cloud_run_main.name
  }
  max_throughput = 300
}
```

### Debug Output

terraform plan:

```
# google_vpc_access_connector.cloud_run_main must be replaced
+/- resource "google_vpc_access_connector" "cloud_run_main" {
      ~ id             = "projects/project/locations/europe-west1/connectors/euw1-backend-main-dv" -> (known after apply)
        machine_type   = "e2-micro"
      ~ max_instances  = 10 -> (known after apply)
      ~ max_throughput = 1000 -> 300 # forces replacement
      ~ min_instances  = 2 -> (known after apply)
        min_throughput = 200
        name           = "euw1-backend-main-dv"
      ~ project        = "project" -> (known after apply)
        region         = "europe-west1"
      ~ self_link      = "projects/project/locations/europe-west1/connectors/euw1-backend-main-dv" -> (known after apply)
      ~ state          = "READY" -> (known after apply)

      ~ subnet {
            name       = "euw1-resolver-backend-app-cloudrun-main-dv"
          ~ project_id = "project" -> (known after apply)
        }
    }

```

terraform apply:

```
google_vpc_access_connector.cloud_run_main: Creating...

Error: Error creating Connector: googleapi: Error 409: Requested entity already exists

  on nat-gateway.tf line 14, in resource "google_vpc_access_connector" "cloud_run_main":
  14: resource "google_vpc_access_connector" "cloud_run_main" {
```

### Expected Behavior

- terraform deletes the old `google_vpc_access_connector`
- terraform creates the new `google_vpc_access_connector`

### Actual Behavior

- terraform creates the new `google_vpc_access_connector` --> it crashes because of a name conflict (new resource has same name as old resource)

### Steps to Reproduce

1. `terraform apply`

**Comment by venkykuberan** [comment]
@elouanKeryell-Even `max_throughput` is a ForceNew field, any change on it makes the resource to be recreated. Do you see any error on the delete call before create call ?

Can you please attach the debug log here to understand what's going on ?

**Comment by edwardmedia** [comment]
FYI there are several reported issues that seem to be related  
https://github.com/hashicorp/terraform-provider-google/issues/9331
https://github.com/hashicorp/terraform-provider-google/issues/9228

**Comment by elouanKeryell-Even** [comment]
@edwardmedia I don't think we are talking exactly about the same thing

Those issues you mentionned seem to complain about the `google_vpc_access_connector` being updated

I don't mind the update, I am totally OK with it

However, I am quite worried that terraform (or this module) isn't able to perform a simple update of a resource's field, without crashing 😕

**Comment by elouanKeryell-Even** [comment]
> @elouanKeryell-Even `max_throughput` is a ForceNew field, any change on it makes the resource to be recreated. Do you see any error on the delete call before create call ?

@venkykuberan this is the thing: there is no "delete call" before "create call", which is the root of my error. I would be glad if I had a way to "delete before create"

> 
> Can you please attach the debug log here to understand what's going on ?

- plan: https://gist.github.com/elouanKeryell-Even/72c626f31870510b80b445ffd4fd3218
- apply: https://gist.github.com/elouanKeryell-Even/49045b3fd11d512e1ce70ef89af2b437

Note that my tf configuration is a little bit wider than simply a `google_vpc_access_connector`, so you will see references to a few other resources (namely: two Cloud Run services)

**Comment by edwardmedia** [comment]
@elouanKeryell-Even as you can see below line in the plan, it tells us the `apply` usually starts with `destroy`. That is controlled by the Terraform framework. For the [apply log ](https://github.com/hashicorp/terraform-provider-google/issues/9325#issuecomment-858447362), it seems not complete. If you can repro, can you double check the debug log for `apply`?

> ~ max_throughput = 1000 -> 300 # forces replacement

**Comment by elouanKeryell-Even** [comment]
@edwardmedia ok so my issue lies in the terraform core, if I understand you correctly

Let's close this issue then, since it is mis-located
