### ISSUE TITLE
google_compute_instance input for allow_stopping_for_update not functioning as expected

### ISSUE THREAD

**Issue by ranjitk-burwood** [hashicorp/terraform-provider-google#9342]
I am attempting to use the google_compute_instance resource with `allow_stopping_for_update` set to `true`.

When editing values such as the `boot_disk` `initialize_params` for `size` or `type` I notice that my VM is destroyed and re-created (new instance ID). Is this supposed to occur? I do see my `plan` output with the results of `~ type   = "pd-balanced" -> "pd-ssd" # forces replacement`. If I edit the service account I do not get a re-creation event.

I had initially provisioned a VM instance with the same settings and when updating the same `initialize_params` values it did not give me a `plan` output saying it would change anything on the VM. When looking at the VM through the GCP console those values for `size` and `type` were updated which I wasn't expecting to happen since I didn't see a plan output.

**Comment by edwardmedia** [comment]
@ranjitk-burwood I think that behavior is expected. `forces replacement` takes precedence over `allow_stopping_for_update` no matter what value it is. Does this make sense?

```
allow_stopping_for_update - (Optional) If true, allows Terraform to stop the instance to update its properties. If you try to update a property that requires stopping the instance without setting this field, the update will fail.
```

**Comment by ranjitk-burwood** [comment]
@edwardmedia Thanks for the explanation. Makes sense but I was thinking that changing the boot disk wouldn't need the instance to be re-created. There is also some documentation from GCP about [re-sizing disk size](https://cloud.google.com/compute/docs/disks/working-with-persistent-disks#console). 

I tried this out manually through the console and it did not re-create my instance but did update the boot disk. Is this just something that Terraform can't handle in the same way as going through the UI?

**Comment by ranjitk-burwood** [comment]
@edwardmedia Did a little more testing with fields such as `email`, `machine_type`, and `shielded_config` with `allow_stopping_for_update` set to `false` and I got an error message about needing that set to `true` in order to update those fields so it seems like those are working as intended and do not re-create the instance but just update in place.

Seems like the main one for me is just the `initialize_params` input. What happens if there is a workload running on that VM and it gets re-created? Does that workload shut down or are things migrated to a new VM instance without any disruption?

**Comment by edwardmedia** [comment]
@ranjitk-burwood it gets re-created. When you re-apply with the new config, Terraform will try to bring the new disk to match the one you want. You need to build a mechanism that can preserve the workload. 

https://github.com/hashicorp/terraform-provider-google/blob/2a8b07b89d7261e0861678de9bb742f6a2657c37/google/resource_compute_instance.go#L170

**Comment by ranjitk-burwood** [comment]
@edwardmedia Thanks for the link to the code. Makes more sense now seeing that. I'll try to look into some options for preserving workloads.
