### ISSUE TITLE
google_monitoring_slo allowed to set invalid SLI

### ISSUE THREAD

**Issue by estensen** [hashicorp/terraform-provider-google#9344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.3
on darwin_amd64

### Affected Resource(s)

* google_monitoring_slo

### Terraform Configuration Files

Refactoring from using `metric.label.response_code` to `metric.label.response_code_class` I forgot to change the value from `200` and `500` to `2xx` and `5xx`

```tf
resource "google_monitoring_slo" "availability_slo" {
  count               = var.project == "prod" ? 1 : 0
  project             = data.google_project.project.project_id
  service             = google_monitoring_custom_service.abc.service_id
  slo_id              = "availability-slo-abc"
  display_name        = "99% of requests are successful over rolling 28 days (service=${google_monitoring_custom_service.abc.display_name})"
  goal                = 0.99
  rolling_period_days = 28

  request_based_sli {
    good_total_ratio {
      good_service_filter = <<-EOT
        resource.type="cloud_run_revision"
        project="${data.google_project.project.project_id}"
        resource.label.service_name="abc"
        metric.type="run.googleapis.com/request_count"
        metric.label.response_code_class=200
      EOT
      bad_service_filter  = <<-EOT
        resource.type="cloud_run_revision"
        project="${data.google_project.project.project_id}"
        resource.label.service_name="abc"
        metric.type="run.googleapis.com/request_count"
        metric.label.response_code_class=500
      EOT
    }
  }
}
```

### Expected Behavior

I expect not being able to set an invalid SLI

### Actual Behavior

No failure and not noticing the failure before manually checking the console

Logging into GCloud Monitoring and selecting the service the Service Level Indicator says "No status" and an error pops up:

>There was an issue parsing the filter string used in the SLO. Only filters that join labels with "AND" are supported. Filtering by groupId is not supported. The UI does not yet support any request-based SLI based on a ratio between two time series that have different metric types.The data in the form was reset.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@estensen it would be nice if some pre-check can be done. Unfortunately most of fields are string type, and the provider relies on the [api schema](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services.serviceLevelObjectives#ServiceLevelIndicator). I guess there is not much that can be done.
