### ISSUE TITLE
Unable to Upgrade terraform due to provider configuration

### ISSUE THREAD

**Issue by m477r1x** [hashicorp/terraform-provider-google#9345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Background
Hi there,

I'm sorry for modifying the template but I feel this context is required for the rest of the issue to make sense. Also, if there is somewhere else I should be pasting this, please tell me and I will move to the correct location.

I am having an issue upgrading one of our modules from terraform12 to terraform13 (and afterwards up to 15, and now since yesterday eventually to 1.0! (YAY).

I am making sure there are no pending changes before upgrading terraform, so I am running plans and applies first with terraform12 before upgrading as the upgrade steps suggest. The problem I am facing is the output complains that the provider does not support the resource type `google_project_services` which I have done some reasearch and believe it was deprecated according to this article: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_3_upgrade#resource-google_project_services. And that I should change the configuration to use the newer `project_services` public module for better interaction with the GCP API. However when changing the configuration, I then get an error stating that it needs the original configuration to destroy the resources. So firstly, I cannot use the original configuration because from my understanding it is deprecated and no longer works (as seen in the error output below)? And secondly, i dont want it to destroy resources in GCP, i simply want to update the terraform configuration syntax. I'm not sure if this is a 'real' bug, but I am struggling to find any concrete answers as to how to proceed so I am looking for some guidance if possible. 

### Terraform Version
Terraform v0.12.29
+ provider.google v3.65.0

### Affected Resource(s)

google_project_services

### Terraform Configuration Files

<details>
  <summary>Original Resource Config</summary>
  
```resource "google_project_service" "services" {
  project = data.google_project.storage.project_id

  service = [
    "storage-api.googleapis.com",
    "storage-component.googleapis.com"
  ]
}
```
</details>

<details>
  <summary>New config using public module</summary>

```
module "project_services" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "3.3.0"

  project_id = data.google_project.storage.project_id
  activate_apis = [
    "storage-api.googleapis.com",
    "cloudresourcemanager.googleapis.com",
  ]

  disable_services_on_destroy = false
  disable_dependent_services  = false
}
```
</details>

### Debug Output

I'm sorry but I am not running this terraform locally as we lock down our environments so that terraform is only run on our CI/CD runners, and I am unable to set environment variables on those runners without affecting other projects outputs. Hopefully since it is a small error it is ok to paste here?

<details>
  <summary> First output with original provider config</summary>

```
Error: Invalid resource type

  on project_services.tf line 1, in resource "google_project_services" "services":
   1: resource "google_project_services" "services" {

The provider provider.google does not support resource type
"google_project_services".
```
</details>

<details>
  <summary>Second output with updated proivider config</summary>

```
Error: Provider configuration not present

To work with google_project_services.services its original provider
configuration at provider["registry.terraform.io/-/google"] is required, but
it has been removed. This occurs when a provider configuration is removed
while objects created by that provider still exist in the state. Re-add the
provider configuration to destroy google_project_services.services, after
which you can remove the provider configuration again.
```
</details>

### Expected Behavior

I was hoping that updading thew config to use the new public module would allow terraform to update the state file in place and not require any deletion of resources as this output appears to indicate would need to happen.

### Actual Behavior

The error above.

### Steps to Reproduce

1. `terraform apply`

**Comment by m477r1x** [comment]
Sorry to spam I wondered if anybody was able to offer any advice on this?

**Comment by c2thorn** [comment]
Hi @m477r1x I believe I understand your situation. I believe what's happening is that the old `google_project_services` resource remains in your state file. Are you able to use `terraform rm` https://www.terraform.io/docs/cli/commands/state/rm.html to make Terraform "forget" about the reference? If you do so, the new `google_project_service` has the ability to "pickup" any existing services on create, so the new module should run smoothly afterwards.

**Comment by m477r1x** [comment]
Hi @c2thorn thanks very much for your advice, I will try this tomorrow and let you know!

**Comment by c2thorn** [comment]
I'll close this for now, and reopen based on the results.

**Comment by m477r1x** [comment]
@c2thorn this has worked thank you for your advice!

**Comment by c2thorn** [comment]
@m477r1x Glad to hear it!
