### ISSUE TITLE
Add support for NAT addresses of the Apigee X instance

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#9358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Apigee X runtime can assign static IP NAT addresses.
https://cloud.google.com/apigee/docs/api-platform/security/nat-provisioning

### New or Affected Resource(s)

* google_apigee_instance_nat_address

### Potential Terraform Configuration

```tf
resource "google_apigee_instance" "apigee_instance" {
  name         = "tf-test%{random_suffix}"
  location     = "us-central1-b"
  description  = "Terraform-managed Apigee Runtime Instance"
  display_name = "tf-test%{random_suffix}"
  org_id       = google_apigee_organization.apigee_org.id
}

resource "google_apigee_instance_nat_address" "apigee_instance" {
  instance = google_apigee_instance.apigee_instance.id
  name     = "tf-test-address-1"
  activate = true
}
```

### References

* https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.instances.natAddresses

**Comment by danistrebel** [comment]
I can take stab at this.
