### ISSUE TITLE
Add support for basically everything load-balancing

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/terraform-provider-google#9364]
I've been able to configure the vast majority of my google cloud resources with really great results but have run into a wall with google cloud load balancing.

I can't find any resources to provision serverless network endpoint groups, backend services and load balancers...Is this right? Is there any reason why these aren't part of the terraform google provider?

Things have been so comprehensive and I was on a roll, but am dead in my tracks for load balancing, would love to see all of this added!

**Comment by edwardmedia** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/9372 is from you, @atrauzzi Assume this is related?

**Comment by atrauzzi** [comment]
Yeah, but I think in general it's been very difficult to figure out just what kinds of resources I should be using for load balancing.

What would I use to create a load balancer once my backend is ready?

**Comment by c2thorn** [comment]
Hi @atrauzzi 
Have you checked out [terraform-google-modules](https://github.com/terraform-google-modules?type=source)? It has a few load balancing examples like https://github.com/terraform-google-modules/terraform-google-lb
This tutorial has more information: https://cloud.google.com/community/tutorials/modular-load-balancing-with-terraform

Most of the resources you seem interested in are in Compute Engine: 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint_group
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service

I'm closing this as this isn't asking for anything specific and is no longer a feature request.

**Comment by atrauzzi** [comment]
How would I make use of the ["single anycast IP"](https://www.youtube.com/watch?v=D4XZkCJyqis&t=544s) of google's load balancers?

What resource does that correspond to in terraform?
