### ISSUE TITLE
google_compute_router: empty dynamic block for advertised_ip_ranges with advertise_mode = DEFAULT should be allowed

### ISSUE THREAD

**Issue by socratesx** [hashicorp/terraform-provider-google#9369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be great if advertise_mode set to DEFAULT and an empty dynamic block for advertised_ip_ranges was allowed.

Consider the following example snippet: 

```tf
variable "config" {
  default = {
    name = "router"
    region = "europe-west3"
    project_id = "example"
  }
}

resource "google_compute_router" "cloud_router" {
  name     =  var.config["name"]
  network  = google_compute_network.vpc_network.id
  region   = var.config["region"]
  project = var.config["project_id"]

  bgp {
    asn = 65000
    advertise_mode = lookup(var.config, "gcp_custom_cidrs", "") == "" ? "DEFAULT ": "CUSTOM"

    dynamic "advertised_ip_ranges" {
      for_each = split(",",lookup(each.value, "gcp_custom_cidrs", ""))
      content {
        range = advertised_ip_ranges.value     
      }
    }
  }
}

```
That one will  introduce an empty `advertised_ip_ranges{}` inside the bgp block resulting to failure. The error message is that advertised_ip_ranges{} cannot be used with DEFAULT advertise_mode. 

I encountered the limitation when creating a custom module that allows the user to define custom cidrs to advertise instead of all, using the gcp_custom_cidrs argument in the config variable. 

### New or Affected Resource(s)

* google_compute_router

### Potential Terraform Configuration

The following config variables could be used with the same google_compute_router declaration as above to create a cloud router with specific cidrs to advertise in the first case and with the default behavior in the second case. 

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

variable "custom_config" {
  default = {
    name = "router1"
    region = "europe-west3"
    project_id = "example"
    gcp_custom_cidrs = "10.1.0.0/16,10.2.0.0/16"
  }
}

variable "default_config" {
  default = {
    name = "router2"
    region = "europe-west3"
    project_id = "example"
  }
}
```

Summarizing, with this feature implemented we could have the following scenarios:

- DEFAULT + custom_cirds=""            =>  Like using DEFAULT with no custom_cirds
- CUSTOM + custom_cidrs="x.x.x.x"  =>  As it is now with CUSTOM and user defined cidrs
- CUSTOM + custom_cidrs=""            =>  As it is now with CUSTOM and empty defined cidrs
- DEFAULT + custom_cidrs="x.x.x.x"  =>  error

**Comment by clementtournier** [comment]
Same issue here.

When putting the "range" argument to an empty string, and _null_ values are not allowed, Terraform always try to update the configuration even without any modifications.

```hcl
  advertised_ip_ranges {
    range       = each.value.advertise_mode == "CUSTOM" ? each.value.advertised_ip_ranges.range : ""
    description = each.value.advertise_mode == "CUSTOM" ? each.value.advertised_ip_ranges.description : null
  }
```

Terraform plan :
```hcl
  ~ resource "google_compute_router_peer" "bgp_peer" {
        id                        = "projects/XXX/regions/YYY/routers/vpn/vpn-tunnel"
        name                      = "my_name"
        # (10 unchanged attributes hidden)

      + advertised_ip_ranges {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by ScottSuarez** [comment]
Hi @clementtournier, this is how terraform works under the hood. The field `advertised_ip_ranges` is a list, in adding a `advertised_ip_ranges` block you are adding an item to that list, even if the values to that item are empty.

https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_router_peer.go#L111-L114

**Comment by clementtournier** [comment]
@ScottSuarez Thank you for sharing this information, I understand better, had the same kind of issue with _advertised_groups_ parameter that requires a list, not a map, but I found a workaround by passing a double quoted empty value followed by the [compact](https://www.terraform.io/docs/language/functions/compact.html) function, so the list had no element.

```hcl
advertised_groups = compact([ each.value.advertise_mode == "CUSTOM" ? each.value.advertised_groups : "" ])
```

But regarding _advertised_ip_ranges_ , I have no idea.

**Comment by clementtournier** [comment]
@socratesx I Finally found a solution by using ```dynamic``` block for ```advertised_ip_ranges``` argument  :

```hcl
  dynamic "advertised_ip_ranges" {
    for_each    = each.value.advertise_mode == "CUSTOM" ? toset([1]) : toset([])
    content {
      range       = each.value.advertised_ip_ranges.range
      description = each.value.advertised_ip_ranges.description
    }
```

Hope it will help.

**Comment by ScottSuarez** [comment]
given that there is a workaround I'm going to close this issue for now. 

i'm sure terraform core would appreciate any suggestions if they aren't already there.

**Comment by socratesx** [comment]
Thank you guys for your support and comments, I was able to solve the problem using the compact function. The  only thing I had to do is to use it in the for_each argument like: 

```hcl
 dynamic "advertised_ip_ranges" {
      for_each = compact(split(",",lookup(each.value, "gcp_custom_cidrs", "")))
      content {
        range = advertised_ip_ranges.value     
      }
    }
```
