### ISSUE TITLE
Error when trying to configure backend service for serverless network endpoint group

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/terraform-provider-google#9372]
Using the following configuration:

```
resource "google_compute_region_network_endpoint_group" "api" {

  count = var.public ? 1 : 0

  name = var.name
  network_endpoint_type = "SERVERLESS"
  region = var.currentRegion.location
  cloud_run {
    service = google_cloud_run_service.api.name
  }
}

resource "google_compute_region_backend_service" "api" {

  count = var.public ? 1 : 0

  name = var.name
  region = var.currentRegion.location

  backend {
    group = google_compute_region_network_endpoint_group.api[0].id
  }
}
```

I end up receiving the following message:

```
Invalid load balancing scheme for regional backend service with Serverless network endpoint group., invalid
```

---

I can't seem to find any combination of values that will let me create the backend service pointed at my **Cloud Run** network endpoint group.  Is there something missing in the documentation?

**Comment by edwardmedia** [comment]
@atrauzzi can you try something like below config to see if that works?

```tf
resource "google_compute_region_network_endpoint_group" "function_neg" {
  name                  = "function-neg"
  region                = "us-central1"
  cloud_function {
    function = google_cloudfunctions_function.function_neg.name
  }
}

resource "google_compute_backend_service" "backend" {
  name                            = "issue9372"
  connection_draining_timeout_sec = 10
 
  backend {
    group = google_compute_region_network_endpoint_group.function_neg.id
  }
}
```

**Comment by atrauzzi** [comment]
Will give that a shot.

Out of curiosity, what would be the main reason to switch from a regional to a global backend service?

**Comment by edwardmedia** [comment]
@atrauzzi chance to give that a shot?

**Comment by atrauzzi** [comment]
@edwardmedia - That's HTTPS, but I'm asking about global vs. regional?  Or is HTTPS load balancing only global? The documentation you listed doesn't speak to regional vs. global.

Apologies, some of this is confusing as I don't feel like I have enough information to make a decision with load balancing sometimes.

**Comment by edwardmedia** [comment]
@atrauzzi in GCP, `HTTP(S) Load Balancing is a global, proxy-based Layer 7 load balancer`

https://cloud.google.com/load-balancing/docs/https

**Comment by atrauzzi** [comment]
Okay, so how would I make use of the ["single anycast IP"](https://www.youtube.com/watch?v=D4XZkCJyqis&t=544s) of google's load balancers?

What resource does that correspond to in terraform?
