### ISSUE TITLE
Improve performance of google_storage_bucket with force_destroy

### ISSUE THREAD

**Issue by priscilasolis** [hashicorp/terraform-provider-google#9397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When attempting to delete a bucket with a large number of objects using `terraform destroy` and `force_destroy` enabled, the deletion takes a significant amount of time.

Currently, it seems like the objects inside the bucket are deleted using a worker pool, and the amount of workers depends on the number of cores of the machine running it. In the case that it only has one worker the latency is significant, as opposed to what we would see with a `gsutil rm -r gs://<BUCKET_NAME>` which seems to finish faster in the same machine with the same constraints.

It would be a good improvement that the time it takes to delete the bucket with Terraform is similar to using `gsutil` or the console.

### New or Affected Resource(s)

* google_storage_bucket

### References

* https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_storage_bucket.go#L798

**Comment by ScottSuarez** [comment]
hi @priscilasolis, we are limited by the available storage sdk. There is no methods available to enable a faster deletion.

https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L9327


gsutils itself uses a customized python implementation that we can't utilize. I would suggest asking the maintainers of the sdk or the api to expose more convenient/faster methods.
https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/rm.py#L344-L362
