### ISSUE TITLE
example description value of "test resource." in gke_hub_membership.html.markdown causes problems for membership resource

### ISSUE THREAD

**Issue by linde** [hashicorp/terraform-provider-google#9401]
The value makes it hard to use the cluster in the Anthos or GKE UI to configure ACM or even delete the membership later.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_gke_hub_membership

### Terraform Configuration Files

```tf
## content from the example in the markdown file

resource "google_gke_hub_membership" "membership" {
  membership_id = "basic"
  endpoint {
    gke_cluster {
      resource_link = "//container.googleapis.com/${google_container_cluster.primary.id}"
    }
  }
  description = "test resource."   ### THIS IS PROBLEMATIC
  provider = google-beta
}

```

### Debug Output

It actually "works" ok, you just cant use the resulting cluster for ACM or similar.

### Expected Behavior

Just change to have a name that can be part of a resource and make docs to this effect and/or have validation, ideally.

### Steps to Reproduce

follow the [instructions](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership), then try to configure a feature like ACM in the UI.

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/gke_hub_membership

* #0000

**Comment by edwardmedia** [comment]
@linde I am not clear what is wrong. After running below plan, I can see the cluster has been registered by executing `gcloud beta container hub memberships describe basic` Can you provide the details specifying the problem?

```tf
resource "google_gke_hub_membership" "membership" {
  membership_id = "basic"
  endpoint {
    gke_cluster {
      resource_link = "//container.googleapis.com/${google_container_cluster.primary.id}"
    }
  }
  description = "test resource."
  provider = google-beta
}
```

**Comment by linde** [comment]
hey, thanks for the follow-up! the problem might be on the google cloud console side, that a cluster with spaces or `.` in the description field causes problems with other hub feature setup. i think it is ok to reolve this item and we can follow-up interally.
