### ISSUE TITLE
Terraform plan after apply has additional ACL changes required and never resolves (2nd edition)

### ISSUE THREAD

**Issue by jdstone** [hashicorp/terraform-provider-google#9418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Summary

After running terraform apply, a subsequent terraform plan indicates it needs to perform additional changes for ACLs even though the plan indicated it completed. (see output samples below). This is the exact same bug as mentioned in the References section at the bottom (see #8957).  It seems the "fix" that was applied did not actually fix the problem.  **NOTE** that resource targeting is in use because of another separate issue that's occurring.

```tf
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
google_storage_bucket.example-artifacts: Refreshing state... [id=example-artifacts]
google_storage_bucket_acl.example-artifacts: Refreshing state... [id=example-artifacts-acl]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_storage_bucket_acl.example-artifacts will be updated in-place
  ~ resource "google_storage_bucket_acl" "example-artifacts" {
        id          = "example-artifacts-acl"
      ~ role_entity = [
          - "OWNER:group-engineering@example.com",
          - "READER:user-348419557177-compute@developer.gserviceaccount.com",
            "OWNER:project-owners-348419557177",
            # (1 unchanged element hidden)
            "READER:project-viewers-348419557177",
          + "OWNER:group-engineering@example.com",
            "OWNER:user-dev-ccie-gcr-upload-key@example-production.iam.gserviceaccount.com",
            "OWNER:project-editors-398082806114",
          + "OWNER:user-348419557177-compute@developer.gserviceaccount.com",
          + "READER:user-348419557177-compute@developer.gserviceaccount.com",
        ]
        # (1 unchanged attribute hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Terraform Version

```tf
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.73.0
+ provider registry.terraform.io/hashicorp/google-beta v3.73.0
```

### Affected Resource(s)

* google_storage_bucket_acl

### Terraform Configuration Files

```tf
provider "google" {
  credentials = file(var.google_credentials_file)
  project     = var.google_project_id
  region      = var.google_region
}

resource "google_storage_bucket" "example-artifacts" {
  name          = "example-artifacts"
  location      = "US"
  storage_class = "MULTI_REGIONAL"

  lifecycle_rule {
    action {
      type = "Delete"
    }

    condition {
      age        = "365"
      with_state = "ANY"
    }
  }
}

resource "google_storage_bucket_acl" "example-artifacts" {
  bucket = google_storage_bucket.example-artifacts.name

  role_entity = [
    "OWNER:project-owners-${var.google_project_number}",
    "OWNER:project-editors-${var.google_project_number}",
    "READER:project-viewers-${var.google_project_number}",
    "OWNER:group-engineering@example.com",
    "OWNER:user-dev-ccie-gcr-upload-key@example-production.iam.gserviceaccount.com",
    "OWNER:project-editors-398082806114",
    "OWNER:user-${var.google_project_number}-compute@developer.gserviceaccount.com",
    "READER:user-348419557177-compute@developer.gserviceaccount.com",
  ]
}
```

### Debug Output

https://gist.github.com/jdstone/335d80d4ebcb76f9898bdf18b7aaa36c

### Panic Output

N/A

### Expected Behavior

It should not think it needs to make additional changes after an apply is run.

### Actual Behavior

After configuring the ACLs, which seems to work, it thinks it needs to update the ACLs again.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### Important Factoids

N/A

### References

* #8957

**Comment by edwardmedia** [comment]
This PR should take care of it. 

https://github.com/GoogleCloudPlatform/magic-modules/pull/4848

**Comment by edwardmedia** [comment]
Add the label of `waiting-response` for the PR (#4848) review & approval

**Comment by jdstone** [comment]
> Add the label of `waiting-response` for the PR (#4848) review & approval

@edwardmedia 
Looks like you referenced the incorrect PR.  (Feel free to delete my command after fixing)

**Comment by edwardmedia** [comment]
Closing this as it appears to be taken care by https://github.com/GoogleCloudPlatform/magic-modules/pull/4848

**Comment by jdstone** [comment]
@edwardmedia why hasn't that PR been reviewed yet?  It's over a month old.  Is a review process this long common/normal?
