### ISSUE TITLE
Budget amount not updating when calling google_billing_budget 

### ISSUE THREAD

**Issue by jdub55** [hashicorp/terraform-provider-google#9422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Initializing provider plugins...
- Finding hashicorp/google-beta versions matching ">= 3.55.0"...
- Finding hashicorp/google versions matching ">= 3.55.0, ~> 3.55"...
- Installing hashicorp/google-beta v3.73.0...
- Installed hashicorp/google-beta v3.73.0 (self-signed, key ID 34365D9472D7468F)
- Installing hashicorp/google v3.73.0...
- Installed hashicorp/google v3.73.0 (self-signed, key ID 34365D9472D7468F)
- 
### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

Budget amount should be updated

### Actual Behavior

Budget amount is not updated

### Steps to Reproduce

 update amount of existing google_billing_account resource
2. terraform apply - successfully reports the change
      ~ amount {
            last_period_amount = false
          ~ specified_amount {
                currency_code = "USD"
                nanos         = 0
              ~ units         = "2" -> "5"
            }
        }
3. terraform apply - successful reports change
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
When validated in console or gcloud can confirm that the amount is not changed.

### References

* #0000

**Comment by edwardmedia** [comment]
@jdub55 can you share your config and debug log?

**Comment by jdub55** [comment]
This looks look to be an internal API error that Google Support and Engineering are reviewing. Closing out the case as it's likely no change to Terraform are needed to address this issue.
