### ISSUE TITLE
Hey @zffocussss!

### ISSUE THREAD

**Issue by karthickshiv** [hashicorp/terraform-provider-google#9425]
Hey @zffocussss!

`google_project_iam_member` is used to define a single user:role pairing. You can define multiple `google_project_iam_member` blocks to attach multiple roles to a single user, or multiple users to a single role.

can you please share some sample code?

**Comment by edwardmedia** [comment]
@karthickshiv not super clear what you are trying to do here. If you have specific questions / issues about the provider plug-in, please follow the template and provide the details so we can help. Close this one now
