### ISSUE TITLE
Cannot import GKE without nodepool block definition

### ISSUE THREAD

**Issue by puzzloholic** [hashicorp/terraform-provider-google#9427]
Hi,

Currently I have live production GKE cluster, and I want to manage it with Terraform. Is there any way to separate nodepool resource management, so the `nodepool` block is not imported within `google_container_cluster` resource?

Right now I have multiple `google_container_node_pool` resource from importing each nodepool, but multiple `nodepool` blocks also exists in `google_container_cluster` resource. If I want to remove those `nodepool` blocks, `google_container_cluster` must be force replaced .

**Comment by venkykuberan** [comment]
@puzzloholic so you imported both the cluster and node_pool resources, right ?.  You should be able to remove it from the cluster without recreating the cluster. Can you share both the `cluster` & `node_pool` config.

**Comment by puzzloholic** [comment]
@venkykuberan, I manage to switch nodepool management to `google_container_node_pool` resource using this step on my own. This is my findings.

This is my resource config after importing the cluster and each of the nodepool.
```
resource "google_container_cluster" "k8s_cluster" {
  # other configs

  node_pool {
    # node_pool 1 config
  }

  node_pool {
    # node_pool 2 config
  }

  node_pool {
    # node_pool 3 config
  }

  # other configs
}

resource "google_container_node_pool" "pool_1" {
  # node_pool 1 config
}

resource "google_container_node_pool" "pool_2" {
  # node_pool 2 config
}

resource "google_container_node_pool" "pool_3" {
  # node_pool 3 config
}

```
What I want to remove is all `node_pool` block  inside resource `google_container_cluster.k8s_prod`.
First I try to remove 1 `node_pool` block, and terraform indicates that `google_container_cluster.k8s_prod` must be replaced because node_pool block

But, when I try removing all `node_pool` blocks, surpisingly, terraform did not detect any changes on the state.

So, that's it, I manage to move node pool management to resource `google_container_node_pool` by removing all `node_pool` blocks in resource `google_container_cluster`
