### ISSUE TITLE
google_cloud_run_service can't be initially created with secret manager env vars

### ISSUE THREAD

**Issue by txomon** [hashicorp/terraform-provider-google#9441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

Following the previously reported bug #9175 I have finally been able to isolate the problem. This will only fail if the cloud run service hasn't been created before. The way to fix it is to manually enter a secret env var through the console and then applying again.

### Terraform Version
```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.72.0
+ provider registry.terraform.io/hashicorp/google-beta v3.72.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/newrelic/newrelic v2.23.0
```

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
locals {
  env_secrets ={
    SECRET_KEY : "projects/994503404540/secrets/api_secret_key"
  }
  project = {
    id: "cybernetic-tide-317715",
    region: "europe-west1"

  }
}

resource "random_uuid" "secrets" {
  for_each = local.env_secrets
}

locals {
  # Secrets seem
  secret_uuid = {for env_name, secret_id in local.env_secrets : env_name => "secret-${random_uuid.secrets[env_name].result}"}
  secret_mappings = {for env_name, secret_id in local.env_secrets : env_name => "${local.secret_uuid[env_name]}:${secret_id}"}
  run_googleapis_com_secrets = join(",", values(local.secret_mappings))
}

resource "google_cloud_run_service" "instance" {
  provider = google-beta

  project = local.project.id
  name = "test"
  location = local.project.region
  autogenerate_revision_name = true

  template {
    metadata {
      annotations = {
        "run.googleapis.com/launch-stage" = "ALPHA"
        "autoscaling.knative.dev/maxScale" = 1000
        "run.googleapis.com/client-name" = "terraform"
        "autoscaling.knative.dev/minScale" = 1
        "run.googleapis.com/secrets" = local.run_googleapis_com_secrets
      }
    }
    spec {
      container_concurrency = 80
      timeout_seconds = 299

      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"

        dynamic "env" {
          for_each = local.secret_uuid
          content {
            name = env.key
            value_from {
              secret_key_ref {
                name = env.value
                key = "latest"
              }
            }
          }
        }

        ports {
          container_port = 8080
        }

        resources {
          limits = {
            "cpu" = "1"
            "memory" = "1Gi"
          }
          requests = {}
        }
      }
    }
  }

}

terraform {
  required_version = "= 1.0"

  required_providers {
    google = {
      source = "hashicorp/google"
      version = "= 3.72.0"
    }
    google-beta = {
      source = "hashicorp/google-beta"
      version = "= 3.72.0"
    }
  }
}


```

### Debug Output

https://gist.github.com/txomon/818300abee68a210b08723e0dad6a584

### Expected Behavior

Cloud run instance should have been created

### Actual Behavior

It didn't get created

### Steps to Reproduce

1. New cloud run instance. If it was previously created it will work
1. `terraform init`
2. `terraform apply`

### Important Factoids

This will ONLY fail if the cloud run instance doesn't exist

### References

* #9175

### Workaround

1. Create the google_cloud_run_service without any secrets referenced (in the example `secret_env` empty and `       "run.googleapis.com/secrets" = local.run_googleapis_com_secrets` commented out
2. Go to the console, open the service, click on `Edit and deploy new revision` button
3. Go to the `Variables and secrets` tab, click on secrets, and add the resource by id by clicking on the lower button `DON'T SEE YOUR SECRET? ENTER SECRET RESOURCE ID`. 
![image](https://user-images.githubusercontent.com/228250/123419281-56185280-d5ba-11eb-889b-c605f6bf7f7d.png)
4. `Reference Method -> Exposed as environment variable `
5. Add the name and the version
6. click `Done`
7. `Deploy`
8. Go back to your terraform files, and restore all the code commented in step 1, it should be able to apply now

**Comment by edwardmedia** [comment]
There is a daily test here https://github.com/hashicorp/terraform-provider-google-beta/blob/23b194d1e0fcd4c394528a2831a6fa355d8f41ef/google-beta/resource_cloud_run_service_test.go#L330

**Comment by txomon** [comment]
I have tried to change the code to use the exact annotations and the problem is still there:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_cloud_run_service.instance will be created
  + resource "google_cloud_run_service" "instance" {
      + autogenerate_revision_name = true
      + id                         = (known after apply)
      + location                   = "europe-west1"
      + name                       = "test1"
      + project                    = "cybernetic-tide-317715"
      + status                     = (known after apply)

      + metadata {
          + annotations      = (known after apply)
          + generation       = (known after apply)
          + labels           = (known after apply)
          + namespace        = (known after apply)
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }

      + template {
          + metadata {
              + annotations      = {
                  + "autoscaling.knative.dev/maxScale" = "1000"
                  + "autoscaling.knative.dev/minScale" = "1"
                  + "generated-by"                     = "magic-modules"
                  + "run.googleapis.com/client-name"   = "terraform"
                  + "run.googleapis.com/launch-stage"  = "BETA"
                  + "run.googleapis.com/secrets"       = "secret-a8ada0b7-f433-756a-d776-f22d68009edc:projects/994503404540/secrets/api_secret_key"
                }
              + generation       = (known after apply)
              + name             = (known after apply)
              + namespace        = (known after apply)
              + resource_version = (known after apply)
              + self_link        = (known after apply)
              + uid              = (known after apply)
            }

          + spec {
              + container_concurrency = 80
              + serving_state         = (known after apply)
              + timeout_seconds       = 299

              + containers {
                  + image = "us-docker.pkg.dev/cloudrun/container/hello"

                  + env {
                      + name = "SECRET_KEY"

                      + value_from {
                          + secret_key_ref {
                              + key  = "latest"
                              + name = "projects/994503404540/secrets/api_secret_key"
                            }
                        }
                    }

                  + ports {
                      + container_port = 80
                    }

                  + resources {
                      + limits = {
                          + "cpu"    = "1"
                          + "memory" = "1Gi"
                        }
                    }
                }
            }
        }

      + traffic {
          + latest_revision = (known after apply)
          + percent         = (known after apply)
          + revision_name   = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_cloud_run_service.instance: Creating...
╷
│ Error: Error creating Service: googleapi: Error 400: spec.template.spec.containers[0].env.value_from: spec.template.spec.containers[0].env.value_from should be empty
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "spec.template.spec.containers[0].env.value_from should be empty",
│         "field": "spec.template.spec.containers[0].env.value_from"
│       }
│     ]
│   }
│ ]
│
│   with google_cloud_run_service.instance,
│   on main.tf line 23, in resource "google_cloud_run_service" "instance":
│   23: resource "google_cloud_run_service" "instance" {
│
╵
```

**Comment by edwardmedia** [comment]
@txomon I am able to see both **TARGET** and **SOURCE** under `Environment variables` by running the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-multiple-environment-variables) . I have tried `initial apply` and following `apply` with additional `env` and all work fine with me. Instead of `dynamic code`, can you try the example first to see if that works for you?

**Comment by txomon** [comment]
@edwardmedia not sure if we are referring to the same scenario. The one you linked is about environment variables in general. The one I supplied is about secret manager provisioned environment variables. Also, I have provided an example to reproduce the error, is it not working?

**Comment by txomon** [comment]
I have further simplified the example to avoid noise on the communication.
Please find here the debug log with the same error. [google-provider-error.log](https://github.com/hashicorp/terraform-provider-google/files/6755775/google-provider-error.log)


```
locals {
  secret_id = "projects/994503404540/secrets/api_secret_key"
  project = {
    id : "cybernetic-tide-317715",
    region : "europe-west1"
  }
}

resource "random_uuid" "secrets" {
}

locals {
  # Secrets seem
  secret_uuid     = "secret-${random_uuid.secrets.result}"
  secret_mappings = "${local.secret_uuid}:${local.secret_id}"
}

resource "google_cloud_run_service" "instance" {
  provider = google-beta

  project                    = local.project.id
  name                       = "test2"
  location                   = local.project.region
  autogenerate_revision_name = true

  template {
    metadata {
      annotations = {
        "generated-by"                     = "magic-modules"
        "run.googleapis.com/launch-stage"  = "BETA"
        "autoscaling.knative.dev/maxScale" = 1000
        "run.googleapis.com/client-name"   = "terraform"
        "autoscaling.knative.dev/minScale" = 1
        //        "run.googleapis.com/secrets"       = local.secret_mappings
      }
    }
    spec {
      container_concurrency = 80
      timeout_seconds       = 299

      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"

        env {
          name = "SECRET_KEY"
          value_from {
            secret_key_ref {
              name = local.secret_id
              key  = "latest"
            }

          }
        }

        ports {
          container_port = 80
        }

        resources {
          limits = {
            "cpu"    = "1"
            "memory" = "1Gi"
          }
          requests = {}
        }
      }
    }
  }

}

```

**Comment by edwardmedia** [comment]
@txomon have you had a chance to run the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables)? It works for me. I see a `secret` showing in the UI. Let me know if the example works for you

**Comment by txomon** [comment]
@edwardmedia yes it does, the key difference here is that the example here only uses the secret name and not the secret id, which is fine when your secrets are residing in the same project as the secret.

@edwardmedia have you had a change to run the provided terraform configuration files I provided that show case the bug?

**Comment by edwardmedia** [comment]
@txomon here is what the [doc](https://cloud.google.com/run/docs/reference/rest/Shared.Types/SecretVolumeSource) says about the secretName field. The Terraform just passes through what you provide. In your case, you may need to add ":" in front of **"projects/994503404540/secrets/api_secret_key"**. Let me know if that helps

> The name of the secret in Cloud Secret Manager. By default, the secret is assumed to be in the same project. If the secret is in another project, you must define an alias. An alias definition has the form: :projects/<project-id|project-number>/secrets/. If multiple alias definitions are needed, they must be separated by commas. The alias definitions must be set on the run.googleapis.com/secrets annotation.

**Comment by txomon** [comment]
Awesome, so now that we are in the same line of thought, can you confirm whether you can reproduce the bug I have given with the example?

**Comment by edwardmedia** [comment]
@txomon I am able to deploy a service using below config. Did you notice below instruction from the [comment](https://github.com/hashicorp/terraform-provider-google/issues/9441#issuecomment-875761254) ? Let me know if that works?

> The alias definitions must be set on the run.googleapis.com/secrets annotation.

```tf
resource "google_cloud_run_service" "default" {
  provider = google-beta

  name     = "issue9441-cloudrun-srv"
  location = "us-central1"

  template {
    metadata {
      annotations = {
        "run.googleapis.com/secrets" = "secret:projects/6117649xxxxx/secrets/secret"
      }
    }

    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
        env {
          name = "SECRET_ENV_VAR"
      value_from {
            secret_key_ref {
              name = "secret"
              key = "1"
            }
          }
        }
      }
    }
  }

  metadata {
    annotations = {
      generated-by = "magic-modules"
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
  autogenerate_revision_name = true

  lifecycle {
    ignore_changes = [
        metadata.0.annotations,
    ]
  }

  depends_on = [google_secret_manager_secret_version.secret-version-data]
}
```

**Comment by edwardmedia** [comment]
@txomon can you try adding below `metadata` at the root of the resource? Let me know if that works for you. Your UUID is fine

```
  metadata {
    annotations = {
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }
```

**Comment by txomon** [comment]
@edwardmedia it seems to work when setting it in the outer field. Thank you!

Which annotations should go in the outer `metadata.annotations` field and which ones in the inner `template.metadata.annotations` field? The API documentation has both objects but it fails to mention any difference on the two fields and so far I had assumed they were interchangeable.

**Comment by edwardmedia** [comment]
@txomon I am glad your code is working. To be honest, I am not 100 certain what **annotations** go where. Likely we need to go over many documentations, as each play different roles and come from different parties. Should we close the issue then?

**Comment by txomon** [comment]
@edwardmedia yeah, no worries on that. I would only suggest to make a special note on the documentation regarding the top level metadata block having to contain the launch-stage annotation and marking explicitly how those two blocks are not always interchangeable.

**Comment by edwardmedia** [comment]
Please keep in mind, it is all up to the api that control the **annotations**. They may change over time. 
Closing the issue then . Glad your code is working
