### ISSUE TITLE
lifecycle_rule option for google_storage_bucket should be able to be defined conditionally 

### ISSUE THREAD

**Issue by alexandrefilgueira** [hashicorp/terraform-provider-google#9443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It seems impossible to have a resource that creates a bucket with a condition on the lifecycle, so you end up having multiple resources to be able to do this.

Tried several ways that in Terraform should define that I want this property or not, but none worked out, like:

`lifecycle_rule {
    condition {
      age = null
    }
    action {
      type = null
    }
  }`

`lifecycle_rule {}`

`lifecycle_rule = null`

### New or Affected Resource(s)

google_storage_bucket

**Comment by rileykarson** [comment]
What doesn't work exactly? You should be able to omit the field, specify it as `null`, or use a `dynamic` block?

**Comment by alexandrefilgueira** [comment]
if you try the first option, it will tell you that null is not valid.
if you try the second option, it will tell you that you're missing required properties
if you try the third option, it will tell you that you should specify a lifecycle_rule type block

**Comment by rileykarson** [comment]
Can you post sample configuration(s) for each and the exact error you receive, as well as a response from the REST API / gcloud describe / Console that you're unable to represent in Terraform? 1 and 3 should be valid configurations, 2 isn't (you would write 3 instead).

**Comment by alexandrefilgueira** [comment]
I didn't understand the glcoud describe part, but this is the rest

So, for this case:

`
resource "google_storage_bucket" "backup-bucket" {
  name = var.bucket_name

  location = var.location
  storage_class = var.storage_class

  lifecycle_rule = null
}
`


The output of Terraform plan shows:

> Error: Unsupported argument
> 
>   on ../../modules/backups/main.tf line 15, in resource "google_storage_bucket" "backup-bucket":
>   15:   lifecycle_rule = null
> 
> An argument named "lifecycle_rule" is not expected here. Did you mean to
> define a block of type "lifecycle_rule"?


While doing this:
`resource "google_storage_bucket" "backup-bucket" {
  name = var.bucket_name

  location = var.location
  storage_class = var.storage_class

  lifecycle_rule {
    condition {
      age = null
    }
    action {
      type = null
    }
  }
}`

Terraform plan throws:

> Error: Required attribute is not set
> 
>   on ../../modules/backups/main.tf line 19, in resource "google_storage_bucket" "backup-bucket":
>   19:     action {


Let me know if you still need the gcloud describe, not sure exactly what you meant.

**Comment by rileykarson** [comment]
Oh, I wasn't aware explicit nulls didn't work there. Omitting `lifecycle_rule` entirely is correct, in that case.

**Comment by rileykarson** [comment]
Closing this out- I'm not aware that there's an API state that can't be expressed, and Terraform, rejecting those configurations is expected.

**Comment by alexandrefilgueira** [comment]
Sorry for the late reply.

Actually, I know that this is not supported, I was proposing the implementation of this feature as an enhancement, because as of now, you would need to create a new resource with those settings if you want to create a module for example.

Sometimes, you might want to have lifecycles, sometimes maybe not, and if you have a module that creates buckets, then is when this limitation is a problem.

**Comment by rileykarson** [comment]
Isn't that a case for https://www.terraform.io/docs/language/expressions/dynamic-blocks.html?

**Comment by alexandrefilgueira** [comment]
oh, you're completely right, sorry
