### ISSUE TITLE
How do I hook up Cloud Load Balancer to Cloud Run?

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/terraform-provider-google#9444]
What resources would I use from this provider to make use of the ["single anycast IP"](https://www.youtube.com/watch?v=D4XZkCJyqis&t=544s) of google's load balancers?

What resource does that correspond to from this provider?  So far I have (connected in order):
 - `google_cloud_run_service`
   - `google_compute_region_network_endpoint_group`
     - `google_compute_backend_service`
       - `google_compute_url_map`
         - `google_compute_target_https_proxy` :point_left: _Do I need this??_
           - `...what's next?`

Is there any central reference as to what resources I need to make in order to get my Cloud Run service fronted by load balancing using a serverless network endpoint group?

**Comment by venkykuberan** [comment]
@atrauzzi I don't see a complete terraform example of resources for cloud run with lb. We need to NEG for cloud run to point to lb at high level. Combining #2 & #3 will lead you the place where you want. Hope it helps ..

1) [Google doc have the gcloud steps](https://cloud.google.com/load-balancing/docs/https/setting-up-https-serverless#deploy_serverless_app) 

2) [Terraform example for cloud run/neg ](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#example-usage---region-network-endpoint-group-cloudrun)

3) [Terraform module for HTTP LB with Serverless NEG](https://github.com/terraform-google-modules/terraform-google-lb-http/tree/master/modules/serverless_negs)

**Comment by atrauzzi** [comment]
Much appreciated, I'll close this and reopen/comment if anything comes to mind.  I feel like I'm getting close!
