### ISSUE TITLE
reservation_affinity = null should be the same as "ANY_RESERVATION"

### ISSUE THREAD

**Issue by dex4er** [hashicorp/terraform-provider-google#9449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.73.0
+ provider registry.terraform.io/hashicorp/google-beta v3.73.0

### Affected Resource(s)

* google_compute_instance

### Actual Behavior

After #9256 my VMs are going to be recreated because this PR introduced `reservation_affinity` value. The documentation https://cloud.google.com/kubernetes-engine/docs/how-to/consuming-reservations#consuming_reserved_instances_in says the default value is `"ANY_RESERVATION"` so it should be the same as `null`.

My plan after upgrade of the google provider:

```
Terraform will perform the following actions:

  # google_compute_instance.test must be replaced
-/+ resource "google_compute_instance" "test" {
      + allow_stopping_for_update = true
      - enable_display            = false -> null
      - metadata                  = {} -> null
        name                      = "test"
      - resource_policies         = [] -> null

      + confidential_instance_config {
        }

      ~ network_interface {
        }

      - reservation_affinity { # forces replacement
          - type = "ANY_RESERVATION" -> null # forces replacement
        }

      ~ scheduling {

          + node_affinities {
            }
        }

      - shielded_instance_config {
          - enable_integrity_monitoring = true -> null
          - enable_secure_boot          = false -> null
          - enable_vtpm                 = true -> null
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### References

* #9256

**Comment by venkykuberan** [comment]
Agree, we need to set default value for the field. We will include it, thanks for filing the issue.
