### ISSUE TITLE
Provide string fields for setting min/max values within google_monitoring_slo ranges to support infinity/-infinity values

### ISSUE THREAD

**Issue by saidi-adam** [hashicorp/terraform-provider-google#9453]
### Affected Resource(s)

* google_monitoring_slo

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_slo

I'm trying to create a `google_monitoring_slo` resource within GCP via Terraform and as per the documentation (link above), it states that the range block which consists of `min` and `max` will always default to Infinity if let blank as well as they're both optional.

I currently want to specify a `min` of 1440 and a max of infinity - so as per the docs, i could leave max blank. Doing this returns the following error message when running Terraform Deploy

│ Error: Error creating Slo: googleapi: Error 400: The minimum of the range in a MetricSumInRange must be less than its maximum. Got a minimum of 1440.0 and a maximum of 0.0

I've created the resource via GCP console and viewed the JSON version of it - and it specifies the following
`"range": { "min": 1440, "max": "Infinity" }`
I've tried passing through `max="Infinity"` but i shortly get a failure, stating that max must be an integer, not a string. I then tried passing a large number 999 million as the max value, which worked. I just want to have infinity and i feel like the docs are suggesting something that i've tried. Do you have any idea how i can get over this?

Moreover, I've noticed that within the codebase (link below) there doesn't seem to be a check for min, just max
https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_monitoring_slo_test.go

Just to add - the issue i'm having here seems to be similar to the one closed before here - hashicorp/terraform-provider-google#7614 (comment), but there were no comments made about a fix on the ticket

Thank you!

PS. This issue was raised before into Terraform directly and the response stated that it wasn't a TF issue, but a Google one instead - https://github.com/hashicorp/terraform/issues/28969

b/193533934

**Comment by melinath** [comment]
It turns out that this is (unfortunately) going to be a complicated fix.

Currently, it turns out that omitting the max/min fields results in not sending a value to the API; the API then defaults the missing value to 0. This is different than the documented behavior, which states that omitting min will set it to `-infinity` and omitting max will set it to `infinity`. It looks like we don't have any special handling around an "infinity" string, so my guess is this behavior dates to the introduction of the resource.

We can't change the behavior of the resource because that would break any existing configurations that are relying on the current behavior.

Really, these should be string fields so that users could choose to specify `infinity` or `-infinity` explicitly (even if we made that the default.) We could do a state upgrade to convert the type, but that carries risks of breaking configurations.

More likely, we will add a new version of each field that is a string and has the behavior we want.

**Comment by saidi-adam** [comment]
Thanks for the review @melinath - could you give me any indication as to when this issue could be resolved? Either directly or indirectly through a new release? I've work that's been postponed due to this bug, so would appreciate any clarity on this.

**Comment by melinath** [comment]
@saidi-adam we're working on establishing the timeline for this one :-) in the meantime, one of my teammates has suggested the following potential workaround:

> apparently this is a common json problem, but people work around it by just representing positive infinity as 1.0e1024, and negative infinity as -1.0e1024, since those are both too big to fit in a 64 bit float and get converted to inf/-inf on evaluation

It's not clear whether that would work in this case, but it could be worth a shot?

**Comment by saidi-adam** [comment]
hey @melinath just wanted to update you on your suggestion - i've tested passing through `1.0e1024` as both a string and integer but get the following error message; I've tried the `-1.0e1024` version too, but still without luck as I see the same error.

`Error: failed to encode google_monitoring_slo.adam_slo in state: cannot serialize infinity as JSON`

**Comment by etruong42** [comment]
Hello - 

`1.0e1024` is too large. [magic-modules](https://github.com/GoogleCloudPlatform/magic-modules) uses Ruby, and the biggest float Ruby has is `1.7976931348623157e+308` (use `-1.7976931348623157e+308`) for the smallest value.

This appears to work.

```
resource "google_monitoring_slo" "my_slo" {
    service = google_monitoring_service.my_service.service_id
    #slo_id = "0HqJ_9KeQY2zsy8n4fb4Cw"
    goal = 0.8
    calendar_period = "DAY"
      request_based_sli {
    distribution_cut {
          distribution_filter = "metric.type=\"custom.googleapis.com/opencensus/grpc.io/client/roundtrip_latency/cumulative\" resource.type=\"k8s_container\""
          range {
            max = 100000
            min = "-1.7976931348623157e+308"
          }
        }
  }
    display_name = "80% - Distribution Cut - Calendar day"
}
```

```
  # google_monitoring_slo.my_slo will be updated in-place
  ~ resource "google_monitoring_slo" "my_slo" {
        id                  = "projects/180739612668/services/0O9SUJdyQEOZiSun0SMgkQ/serviceLevelObjectives/8Nxk8oanQoK6-6Yk81-BaA"
        name                = "projects/180739612668/services/0O9SUJdyQEOZiSun0SMgkQ/serviceLevelObjectives/8Nxk8oanQoK6-6Yk81-BaA"
        # (8 unchanged attributes hidden)

      ~ request_based_sli {
          ~ distribution_cut {
                # (1 unchanged attribute hidden)

              ~ range {
                  ~ min = 0 -> -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                    # (1 unchanged attribute hidden)
                }
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/410834/228936928-cde43ba5-d845-4217-b598-ed51df25f05f.png)

As others have mentioned, the actual behavior does not match the documentation, so I have made a PR to correct the documentation here: 

I have filed a new issue to make these values settable to "infinity/-infinity" as originally promised in the documentation: https://github.com/hashicorp/terraform-provider-google/issues/14153

**Comment by rileykarson** [comment]
Sounds good! If you edit the PR description to have one of [these keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue it'll auto-close the issue when merged. That'll mostly automate things. For example:

`Fixes https://github.com/hashicorp/terraform-provider-google/issues/9453`
