### ISSUE TITLE
google_pubsub_topic : schema_settings is an unsupported block type.

### ISSUE THREAD

**Issue by ranjitk-burwood** [hashicorp/terraform-provider-google#9464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.13.5

### Affected Resource(s)

* [google_pubsub_topic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic)

### Terraform Configuration Files

Child module main.tf

```tf
resource "google_pubsub_topic" "topic" {

  // REQUIRED

  name    = var.topic_name
  project = var.project_id

  message_storage_policy {
    allowed_persistence_regions = var.allowed_persistence_regions
  }

  // OPTIONAL

  kms_key_name = var.kms_key_name
  labels       = var.topic_labels

  schema_settings {
    schema   = var.schema
    encoding = var.encoding
  }
}
```

terraform.tfvars

```tf
schema       = ""
encoding     = "ENCODING_UNSPECIFIED"
```

### Expected Behavior

Based on the [google_pubsub_topic](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic) resource documentation I am expecting to be able to use a block of code for `schema_settings` but it does not seem to be supported when running either a `terraform validate` or `terraform apply`.

### Actual Behavior

I receive an error message of 
```
Error: Unsupported block type

  on ..\..\..\..\modules\pub_sub\pub_sub_topic\main.tf line 22, in resource "google_pubsub_topic" "topic":
  22:   schema_settings {

Blocks of type "schema_settings" are not expected here.
```

### Steps to Reproduce

1. `terraform init -backend=FALSE`
2. `terraform validate`

OR 

1. `terraform apply`

### Important Factoids

I am passing a blank string from my tfvars for `schema`.

The `resource_pubsub_topic.go` file in the Google Terraform provider repository shows `schema_settings` as an input on [Line 94](https://github.com/hashicorp/terraform-provider-google/blob/55379b948d2df4402bc4f8c81294502037e816ad/google/resource_pubsub_topic.go#L94).

### References

* #0000

**Comment by edwardmedia** [comment]
@ranjitk-burwood the feature was added in the version of [v3.68.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.68.0). What the provider version are you using? Can you get the latest to see if that works?

**Comment by ranjitk-burwood** [comment]
@edwardmedia Thanks, I was using v3.65.0 and switched to v3.68.0 and can confirm it works now on a `terraform validate` at least. On a `terraform apply` I receive the error below which looks to be due to the topic being provisioned already.

```
googleapi: Error 400: Invalid update_mask provided in the UpdateTopicRequest: the 'schema_settings' field in the Topic is not mutable.
```
