### ISSUE TITLE
Backfill support for `user_project_override` and `billing_project` for `google_service_networking_connection`

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-google#9466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Hey! This happened sooner than I thought :)

Per #9454, filing an issue for adding `user_project_override` and `billing_project` support to the `google_service_networking_connection` resource.

See:

https://github.com/hashicorp/terraform-provider-google/blob/8a6ce5351a58081b972ec6dd0603f4bdbacb54cf/google/resource_service_networking_connection.go#L101.

### New or Affected Resource(s)

* google_service_networking_connection

### Potential Terraform Configuration
N/A

### References

* #9437 
* #9454
* b/193588328

**Comment by rileykarson** [comment]
@ericnorris: If you have a TAM/CE with GCP are you able to have them reach out to my team internally to simultaneously file linked requests there? https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team covers some details if they haven't before, as well as the internal shortlinks `go/request-terraform` and `go/terraform-faq` (which I'll update that page to include)

**Comment by ericnorris** [comment]
@rileykarson done! Thank you for following up.
