### ISSUE TITLE
GCE MIG autoscaling - CPU utilisation policy cannot be removed after being added

### ISSUE THREAD

**Issue by szisiu** [hashicorp/terraform-provider-google#9469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.73.0
+ provider registry.terraform.io/hashicorp/google-beta v3.73.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler

### Terraform Configuration Files

Initial config file:

```tf
module "vm_managed_instance_group" {
  source  = "terraform-google-modules/vm/google//modules/mig"
  version = "6.6.0"

 # other settings

  autoscaling_enabled = "true"
  autoscaling_lb = [{
    target = 0.8
  }]
  autoscaling_cpu = [{
    target = 0.8
  }]
}
```

Final config file:

```tf
module "vm_managed_instance_group" {
  source  = "terraform-google-modules/vm/google//modules/mig"
  version = "6.6.0"

 # other settings

  autoscaling_enabled = "true"
  autoscaling_lb = [{
    target = 0.8
  }]
  # autoscaling_cpu has been removed
}
```

### Debug Output

When switching to final config:

![image](https://user-images.githubusercontent.com/13850737/123976090-2a340d00-d9be-11eb-87ee-9cf71b008b98.png)

### Expected Behavior

The CPU utilisation policy should be removed when other policies are required.

### Actual Behavior

Set up two autoscaling policies (eg.: CPU utilisation and LB utilisation). There is a need now to keep only LB utilisation policy. CPU utilisation policy is still being present.

### Steps to Reproduce

1. create a managed instance group with autoscaling policies eg. CPU utilisation and LB utilisation (CPU utilisation must be added)
2. update the config file and remove  CPU utilisation policy
3. `terraform apply`

### Important Factoids

- MIG module used https://registry.terraform.io/modules/terraform-google-modules/vm/google/latest/submodules/mig (v. 6.6.0)
- https://cloud.google.com/compute/docs/autoscaler

**Comment by edwardmedia** [comment]
@szisiu you currently use the `module`.  Can you repro the issue using the `resource` config?

**Comment by szisiu** [comment]
Hi @edwardmedia,

Reproduced using resource directly. Created initial config file with:

```tf
resource "google_compute_region_autoscaler" "autoscaler" {
  provider = google
  count    = 1
  name     = "${var.instance_name}-autoscaler"
  project  = var.project_id
  region   = var.region

  target = google_compute_region_instance_group_manager.mig.self_link

  autoscaling_policy {
    max_replicas    = 3
    min_replicas    = 1
    cooldown_period = 30
    cpu_utilization {
      target = 0.8
    }
    load_balancing_utilization {
      target = 0.8
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13850737/124117084-fd403280-da6f-11eb-8f3c-950dcb077ed9.png)

then updated config file:

```tf
resource "google_compute_region_autoscaler" "autoscaler" {
  provider = google
  count    = 1
  name     = "${var.instance_name}-autoscaler"
  project  = var.project_id
  region   = var.region

  target = google_compute_region_instance_group_manager.mig.self_link

  autoscaling_policy {
    max_replicas    = 3
    min_replicas    = 1
    cooldown_period = 30
    # cpu_utilization has been removed
    load_balancing_utilization {
      target = 0.8
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13850737/124116951-d71a9280-da6f-11eb-9f4a-ad8298d4142d.png)

removing other policy works:

![image](https://user-images.githubusercontent.com/13850737/124117432-6fb11280-da70-11eb-8e15-34c2fd6b2c76.png)

**Comment by edwardmedia** [comment]
@szisiu looks at the [api doc](https://cloud.google.com/compute/docs/reference/rest/v1/autoscalers), it appears api provides a default value. 

Do you have the debug log that contains the api calls after `cpu_utilization` is removed?

**Comment by szisiu** [comment]
The first and second try requests looks the same (enabled tf logs with `TF_LOG=TRACE`):

```json
---[ REQUEST ]--------------------------------------
PUT /compute/v1/projects/my-project/regions/us-central1/autoscalers?alt=json&autoscaler=tf-test-autoscaler HTTP/1.1
Host: compute.googleapis.com
User-Agent: Terraform/1.0.1 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/3.73.0
Content-Length: 443
Content-Type: application/json
Accept-Encoding: gzip
{
 "autoscalingPolicy": {
  "coolDownPeriodSec": 30,
  "cpuUtilization": {
   "predictiveMethod": "NONE",
   "utilizationTarget": 0.8
  },
  "loadBalancingUtilization": {
   "utilizationTarget": 0.8
  },
  "maxNumReplicas": 3,
  "minNumReplicas": 1,
  "mode": "ON"
 },
 "name": "tf-test-autoscaler",
 "region": "projects/my-project/global/regions/us-central1",
 "target": "https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/instanceGroupManagers/tf-mig"
}
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
# other headers
{
  "id": "5583049028015465685",
  "creationTimestamp": "2021-07-01T12:40:42.394-07:00",
  "name": "tf-test-autoscaler",
  "target": "https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/instanceGroupManagers/tf-mig",
  "autoscalingPolicy": {
    "minNumReplicas": 1,
    "maxNumReplicas": 3,
    "coolDownPeriodSec": 30,
    "loadBalancingUtilization": {
      "utilizationTarget": 0.8
    },
    "mode": "ON"
  },
  "region": "https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/my-project/regions/us-central1/autoscalers/tf-test-autoscaler",
  "status": "PENDING", # or "ACTIVE"
  "kind": "compute#autoscaler"
}
```

api docs states that `If none of these [polices] are specified, the default will be to autoscale based on cpuUtilization to 0.6 or 60%.`. In my case there is always some autoscaling policy set. And in case of CPU util there is target at 0.8.

**Comment by edwardmedia** [comment]
Oh I see `cpuUtilization` is still in the request. @

**Comment by melinath** [comment]
Unfortunately, this is a consequence of that block being Computed & Optional. This is a core behavior of Terraform, rather than a bug in the provider.

If you want to unset the field, you can essentially do so by first setting the values to their defaults and then removing the block.

**Comment by szisiu** [comment]
> If you want to unset the field, you can essentially do so by first setting the values to their defaults and then removing the block.

thanks @melinath but I tried this and other combinations and `cpuUtilization` is always pushed, eg.:

```
autoscaling_policy {
    # ...
    cpu_utilization {
      target = 0.6 #default
    }
    load_balancing_utilization {
      target = 0.5
    }
  }
```

then

```
autoscaling_policy {
    # ...
    load_balancing_utilization {
      target = 0.5
    }
  }
```

the thing is - I dont know what policy will be the best for my case, that is why I am testing different ones with different values and as a result I noticed the issue with `cpuUtilization`

**Comment by szisiu** [comment]
also found some related issue regarding Computed and Optional: https://github.com/hashicorp/terraform-provider-google/issues/4326
