### ISSUE TITLE
Google BigQuery table are being force replaced , even when there is no change in the schema structures.

### ISSUE THREAD

**Issue by Sophyiya** [hashicorp/terraform-provider-google#9472]
Noticed similar kind of issues about force replacement were already discussed at https://github.com/hashicorp/terraform-provider-google/issues/8710 and https://github.com/hashicorp/terraform-provider-google/issues/8803, also fix was released.But when we were trying to provision the bigquery table resource with google provider V3.74.0, during the consecutive Terraform apply,the tables are being force replaced(detroyed and recreated)even though there is no change in the schema structure

Interestingly, when we tried Terraform apply using one of the older google provider V3.55.0 and could see there was no force replacements. 

Is this the expected behavior? And how to avoid the force replacements for bigquery tables in V3.74.0?

**Comment by venkykuberan** [comment]
@Sophyiya Can you please attach the plan output to get an idea about what's causing the resource to be recreated ?

**Comment by Sophyiya** [comment]
[terraform_plan_forces_replacement.txt](https://github.com/hashicorp/terraform-provider-google/files/6747131/terraform_plan_forces_replacement.txt)

@venkykuberan I have uploaded the terraform plan which forces the replacement of tables. The plan shows that the Objects have changed outside of Terraform, but that is not the case.

**Comment by venkykuberan** [comment]
It looks like case-sensitive diff causing the resource to be recreated. I will change this issue as bug and we will work on the fix.

**Comment by Sophyiya** [comment]
@venkykuberan Thanks for the update. So the reason for force replacement is "type" and "mode" for the columns were case sensitive. Did I get the root cause correctly?

**Comment by melinath** [comment]
@Sophyiya yes, that's what is causing the recreation.

**Comment by melinath** [comment]
I don't know if they're case sensitive for BigQuery table schemas; from the terraform side, we have considered those fields to be case-sensitive, which is what triggered recreation.

**Comment by Sophyiya** [comment]
@melinath Thanks for confirming.

**Comment by melinath** [comment]
Verified I can reproduce this locally. BigQuery table accepts lowercase mode & type and then uppercases them in the returned value, causing a permadiff.
