### ISSUE TITLE
google_container_node_pool outputs IGM's URL, not IG's

### ISSUE THREAD

**Issue by talonx** [hashicorp/terraform-provider-google#9481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.3

### Affected Resource(s)

+ provider registry.terraform.io/hashicorp/google v3.74.0

### Expected Behavior

Expecting the instance group URLs to be output from the google_container_node_pool resource when I output the `instance_group_urls` attribute.

### Actual Behavior

The `instance_group_urls` actually outputs the instance group manager's URL.  This is a problem because I want to hook up this container node pool to a GLB, and the `google_compute_backend_service` expects a list of IG URLs in the `backend` argument, not a list of IGM URLs. 

If I use the IGM URL, the error I get is 
```
Error: Error creating BackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].group': 'https://www.googleapis.com/compute/v1/projects/<snipped>/zones/us-central1-a/instanceGroupManagers/gke-<snipped>-dca6a2b3-grp'. Unexpected resource collection 'instanceGroupManagers'., invalid
```

**Comment by edwardmedia** [comment]
@talonx can you post your config to show how you do?

**Comment by talonx** [comment]
Node pool definition (used by specific node pools)
```
resource "google_container_node_pool" "mypool" {
  cluster = var.gke_cluster_name
  autoscaling {
    max_node_count = var.max_node
    min_node_count = var.min_node
  }
  initial_node_count = var.initial_node

  management {
    auto_repair = true
    auto_upgrade = false
  }

  name = var.pool_name
  project = var.gcp_project
  upgrade_settings {
    max_surge = 9
    max_unavailable = 0
  }

  node_config {
    disk_size_gb = var.node_disk_size
    disk_type = var.node_disk_type
    labels = var.node_labels
    local_ssd_count = var.local_ssd_count
    machine_type = var.machine_type
    service_account = var.service_account
    oauth_scopes = var.oauth_scopes
    preemptible     = "false"
  }

  //https://github.com/hashicorp/terraform-provider-google/issues/6901#issuecomment-667369691
  lifecycle {
    ignore_changes = [
      initial_node_count
    ]
  }

}
```
Example of a specific node pool
```
module "first_pool" {
  source = "../../modules/node-pool"

  gcp_project = var.gcp_project
  gke_cluster_name = data.terraform_remote_state.gke.outputs.gke_cluster_name
  max_node = 50
  pool_name = "first"
  pool_zone = var.gke_cluster_zone

  machine_type = "n2-highmem-2"
  node_labels = {
    pool-name = "first"
  }
  service_account = data.google_service_account.node_pool_service_account.email

  oauth_scopes = [
    "https://www.googleapis.com/auth/cloud-platform"
  ]

}

```

Part of outputs.tf for the first_pool (this is stored in a GCS remote state - from where the backend service module picks data from)
```
output "first_pool_instance_group_urls" {
  value = module.first_pool.instance_group_urls
}
```
This takes care of creating the node pool. For the backend service I do this - 
```
resource "google_compute_backend_service" "myservice" {
  name = var.backend_service_name
  port_name = var.port_name
  project = var.project_id

  health_checks = [
    google_compute_http_health_check.mycheck.id
  ]
  backend {
    group = var.instance_group_url
  }
}
```
The `var.instance_group_url` is taken from the node pool's remote state. This URL comes as the Instance Group Manager URL I posted earlier. The backend service however seems to expect an IG url instead.

**Comment by edwardmedia** [comment]
@talonx are you able to run the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended)  along with  below `output`?  Please note `instance_group_urls` is a list. I got a list of IGs. Let me know what you see from the example. 

```tf
output "instance_group_urls" {
  value       = google_container_node_pool.primary_preemptible_nodes.instance_group_urls
}
```

**Comment by talonx** [comment]
@edwardmedia this is my output
```

instance_group_urls = tolist([
  "https://www.googleapis.com/compute/v1/projects/<removed>/zones/us-central1-a/instanceGroupManagers/gke-<removed>-test-my-node-pool-20453fd0-grp",
])
```
This looks like a list with one IGM, not IG.

**Comment by talonx** [comment]
I found the PR that added the output for this - and this line in the code seems to indicate that the URLs are actually of the IGMs.

https://github.com/asiragusa/terraform-provider-google/blob/1f7f2ec31217090298e4e6ead73be911d989f30d/google/resource_container_node_pool.go#L422

**Comment by edwardmedia** [comment]
Oh I see both below resources are valid. Both actually share the same short name. We can get the IG from IGM

```
https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-c/instanceGroupManagers/gke-issue9481--gke-c-issue9481--node--d5783922-grp
https://www.googleapis.com/compute/beta/projects/myproject/zones/us-central1-c/instanceGroups/gke-issue9481--gke-c-issue9481--node--d5783922-grp
```

**Comment by rileykarson** [comment]
This is working as intended, from https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters.nodePools the field is described as `The resource URLs of the managed instance groups associated with this node pool.`.

Note that for cluster we do the lookup for the underlying groups. That's historical- I believe the field used to be documented differently on the API, and we believed at the time that it was a bug that it returned the managed groups. The cluster-level field is now deprecated in the API and points to the pool-level one.

**Comment by edwardmedia** [comment]
@talonx I am interested why you want to set up your own GLB to the node pool?

> because I want to hook up this container node pool to a GLB,

**Comment by talonx** [comment]
> Oh I see both below resources are valid. Both actually share the same short name. We can get the actual IG from IGM as it is one attribute of IGM. @rileykarson How do you want to handle this?
> 
> ```
> https://www.googleapis.com/compute/v1/projects/myproject/zones/us-central1-c/instanceGroupManagers/gke-issue9481--gke-c-issue9481--node--d5783922-grp
> https://www.googleapis.com/compute/beta/projects/myproject/zones/us-central1-c/instanceGroups/gke-issue9481--gke-c-issue9481--node--d5783922-grp
> ```

I am missing something here. The output of `instance_group_urls` is not accepted by the `group` argument of google_compute_backend_service. The doc for the latter says

`The fully-qualified URL of an Instance Group or Network Endpoint Group resource. `

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#group

If I pass the output to the backend service resource, I get the error in my original post. I understand that one can get the IG from the IGM, but in this case the IGM is created as a result of creating the container node pool, and there is no Terraform datasource for IGM using which I can fetch the IG.

What is the recommended way to connect the backend service to an IG that is created as part of a container node pool?

**Comment by talonx** [comment]
> @talonx I am interested why you want to set up your own GLB to the node pool?
> 
> > because I want to hook up this container node pool to a GLB,

The other option is Ingress, which does not work for us because of https://github.com/kubernetes/ingress-gce/issues/369

**Comment by talonx** [comment]
For the time being I'm using the Terraform replace function to convert "instanceGroupManagers" to "instanceGroup" in the URL string and use that in the backend service resource. Works fine.

**Comment by rileykarson** [comment]
Yep, a replacement function is a good workaround! We're aware there's a gap here- as the Cluster provides the less useful of the two group- but don't plan to mitigate it clientside. We'd take a change from the API including a new field, though, which you could try requesting at https://issuetracker.google.com/issues/new?component=187077&template=0
