### ISSUE TITLE
Cancel running ci job if there is a subsequent push to the same pr

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#9483]
Cancel running teamcity and cloudbuild jobs to save resources

**Comment by melinath** [comment]
There might be some complications with this since we'd need to make sure we don't leave dangling resources... the simplest version would be: I think we could probably check whether the SHA for the build is still the current SHA for the PR prior to launching a TeamCity test run.

**Comment by ScottSuarez** [comment]
ahh good point ! but if it's vcr test in `replaying` mode there shouldn't be dangling resources?

I think those would be safe to cancel
