### ISSUE TITLE
Failing test: TestAccStorageNotification_basic

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9484]
This test has been failing since June 28. I can reproduce it locally with an isolated run in a separate org, so it's probably not a race condition. Possibly an API bug.

**Comment by melinath** [comment]
example failure: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/194456?buildTab=tests&status=failed&expandedTest=-6865005456619694730

**Comment by megan07** [comment]
This seems to have fixed itself around July 19/20th:

GA: https://ci-oss.hashicorp.engineering/test/-6865005456619694730?currentProjectId=GoogleCloud&branch=%3Cdefault%3E

Beta: https://ci-oss.hashicorp.engineering/test/-6865005456619694730?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E
