### ISSUE TITLE
Failing test: TestAccContainerNodePool_withGPU - permadiff (update in place)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9485]
This is also failing on all PRs. This would be good to fix soon.

example failure: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/194456?buildTab=tests&status=failed&expandedTest=-811545022082220983

This has been happening since June 10th. It looks like a permadiff caused by `google_container_node_pool.node_config.kubelet_config.cpu_cfs_quota` getting set to `false` by the API.

output:

```
provider_test.go:276: Step 1/2 error: After applying this test step, the plan was not empty.
              stdout:
              
              
              An execution plan has been generated and is shown below.
              Resource actions are indicated with the following symbols:
                ~ update in-place
              
              Terraform will perform the following actions:
              
                # google_container_node_pool.np_with_gpu will be updated in-place
                ~ resource "google_container_node_pool" "np_with_gpu" {
                      id                  = "projects/ci-test-project-188019/locations/us-central1-c/clusters/tf-test-cluster-mf7e69lfn2/nodePools/tf-test-np-7w668kfgvh"
                      name                = "tf-test-np-7w668kfgvh"
                      # (8 unchanged attributes hidden)
              
              
                    ~ node_config {
                        + tags              = []
                          # (12 unchanged attributes hidden)
              
                        - kubelet_config {
                            - cpu_cfs_quota = false -> null
                          }
              
                          # (1 unchanged block hidden)
                      }
              
                      # (2 unchanged blocks hidden)
                  }
```

**Comment by mitj04** [comment]
Currently, it has a success rate of 100% in GA Cloud build and 94% in Beta build but passes in all the latest builds.

Google Cloud: https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=-811545022082220983&tab=testDetails

Google Cloud Beta: https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=-811545022082220983&tab=testDetails

**Comment by melinath** [comment]
+1 looks like we resolved this at some point. The beta failures are a different permadiff that seems like it was time-limited.
