### ISSUE TITLE
Add support for `dns_config` to `google_container_cluster` (beta)

### ISSUE THREAD

**Issue by kosukeoya** [hashicorp/terraform-provider-google#9494]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for `dns_config` to `google_container_cluster`

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
resource "google_container_cluster" "with_dns_config" {
	name               = "cluster_name"
	location           = "us-central1"
	initial_node_count = 1
	dns_config {
		cluster_dns 	   = "CLOUD_DNS"
		cluster_dns_domain = "cluster1"
		cluster_dns_scope  = "VPC_SCOPE"
	}
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#dnsconfig
* https://pkg.go.dev/google.golang.org/api@v0.48.0/container/v1beta1#DNSConfig
* https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns

**Comment by kosukeoya** [comment]
I wish to work on this item.

**Comment by sankit2020** [comment]
Please add support for "--cluster-dns" parameter within the API to create constianr cluster. Refer here for the example usage ---


$ gcloud alpha container clusters create "dnstest" \
  --zone "us-central1-c" \
  --release-channel rapid \
  --machine-type n2-standard-2 \
  --cluster-dns clouddns
