### ISSUE TITLE
Migrate resource_storage_bucket_object to cloud.google.com/go/storage

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform-provider-google#9507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As per title, please migrate resource_storage_bucket_object to cloud.google.com/go/storage. At the moment it uses deprecated package google.golang.org/api/storage/v1.
This is a prerequisite for adding CSEK to objects: https://github.com/hashicorp/terraform-provider-google/issues/8133 as in old package this isn't supported, in new however it is.

### New or Affected Resource(s)

* google_storage_bucket_object

### References

* #8133

**Comment by ScottSuarez** [comment]
customer supplied encryption should be supported on the generated client
https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L1712
