### ISSUE TITLE
Importing google_compute_router_interface fails, "project: required field is not set"

### ISSUE THREAD

**Issue by Byte27** [hashicorp/terraform-provider-google#9508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/google-beta v3.74.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* google_compute_router_interface

### Terraform Configuration Files

```tf
resource "google_compute_router" "router" {
  project = local.project
  name = "my-roueter"
  network = <some-network>
  region = local.region
}

resource "google_compute_router_interface" "vpn-if-1" {
  provider = google-beta

  project = local.project
  region = local.region
  router = google_compute_router.router.name
  name = "if-vpn-1"
  ip_range = "*.*.*.*"
}
```

### Expected Behavior

Terraform should be able to import the resource.

### Actual Behavior

```
│ Error: project: required field is not set
```

### Steps to Reproduce

1. Create a Cloud router with an interface in Google Cloud
2. Run `terraform import google_compute_router_interface.if-1 europe-west1/my-router/if-vpn-1`

**Comment by edwardmedia** [comment]
@Byte27  it works for me using below config and command. Can you try?

```tf
resource "google_compute_router_interface" "foobar" {
}
```

> terraform import google_compute_router_interface.foobar us-central1/my-router/if-vpn-1

**Comment by Byte27** [comment]
Nope for some reason I can't get this to work. I'm getting

```
google_compute_router_interface.if-vpn-1: Importing from ID "europe-west1/my-router/if-vpn-1"...
google_compute_router_interface.if-vpn-1: Import prepared!
  Prepared google_compute_router_interface for import
google_compute_router_interface.if-vpn-1: Refreshing state... [id=europe-west1/my-router/if-vpn-1]
╷
│ Error: project: required field is not set
```

Importing other resources does still work

**Comment by edwardmedia** [comment]
@Byte27 do you use the environment variables? Can you run the command like below before you import?

> export GOOGLE_CLOUD_PROJECT=<my_project_id>

**Comment by Byte27** [comment]
This seems to have worked, thanks! It's strange though that Terraform doesn't allow you to specify the project as part of the import command

**Comment by edwardmedia** [comment]
@Byte27 glad it works for you now. Closing the issue then
