### ISSUE TITLE
Missing trigger options in Cloud build

### ISSUE THREAD

**Issue by shivaharikumar** [hashicorp/terraform-provider-google#9512]
Looking at the documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger , I cannot see trigger options like Manual invocation or Webhook invocation which are possible from GCP console (UI).

In the REST documentation from GCP, webhook is referenced, https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers
```
 "webhookConfig": {
    object (WebhookConfig)
  },
```

**Comment by rileykarson** [comment]
Hello! Do you mind re-filing this issue, filling out the enhancement template? Thanks!

**Comment by c2thorn** [comment]
This was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/4931
