### ISSUE TITLE
Terraform apply fails to update the `google_cloud_identity_group` resource when bumping the `hashicorp/google` provider version

### ISSUE THREAD

**Issue by PatrickDale** [hashicorp/terraform-provider-google#9513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tfe v0.25.3
```

### Affected Resource(s)

* google_cloud_identity_group

### Terraform Configuration Files

```tf
locals {
  some_google_groups = [
    "some-google-group",
  ]
}

resource "google_cloud_identity_group" "some_google_group" {
  for_each = toset(local.some_google_groups)

  display_name = each.value
  parent       = "customers/${data.google_organization.my_organization.directory_customer_id}"

  group_key {
    id = "${each.value}@my_org.com"
  }

  labels = {
    "cloudidentity.googleapis.com/groups.discussion_forum" = ""
  }
}
```

### Debug Output

```
{"@level":"error","@message":"Error: Error updating Group \"groups/<group-id>>\": googleapi: Error 400: Request contains an invalid argument.","@module":"terraform.ui","@timestamp":"2021-07-06T14:10:51.618619Z","diagnostic":{"severity":"error","summary":"Error updating Group \"groups/<group-id>\": googleapi: Error 400: Request contains an invalid argument.","detail":"","address":"google_cloud_identity_group.some_google_group[\"some-google-group\"]","range":{"filename":"google-groups.tf","start":{"line":11,"column":59,"byte":197},"end":{"line":11,"column":60,"byte":198}},"snippet":{"context":"resource \"google_cloud_identity_group\" \"some_google_group\"","code":"resource \"google_cloud_identity_group\" \"some_google_group\" {","start_line":11,"highlight_start_offset":58,"highlight_end_offset":59,"values":[]}},"type":"diagnostic"}
```

### Terraform Plan Output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_identity_group.some_google_group["some-google-group"] will be updated in-place
  ~ resource "google_cloud_identity_group" "some_google_group" {
        id                   = "groups/<group-id>"
      + initial_group_config = "EMPTY"
        name                 = "groups/<group-id>"
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

I would have expected `terraform apply` to have passed.

### Actual Behavior

Running `terraform apply` failed with the error I posted above. I ran `terraform apply` again after receiving the error, and it passed with the message: `No changes. Your infrastructure matches the configuration.`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing atypical about this terraform run. It is being executed in Terraform Cloud, and the only change made was updating the `hashicorp/google` provider version from `~> 3.66.0` to `~> 3.74.0`.

**Comment by edwardmedia** [comment]
@PatrickDale did you say it failed on the first and worked on the 2nd apply? If yes, could be api issue? Can you repro it?

**Comment by edwardmedia** [comment]
@PatrickDale is this still an issue?

**Comment by edwardmedia** [comment]
@PatrickDale closing this assume it is no longer an issue

**Comment by geirsagberg** [comment]
I had the same error, upgrading from 3.66.0 to 3.77.0. Worked on second apply for me as well.
