### ISSUE TITLE
apigee: added SLASH_22 support for `peering_cidr_range` on `google_apigee_instance`

### ISSUE THREAD

**Issue by ochorne** [hashicorp/terraform-provider-google#9514]
Google updated perring range for eval org provisioning. The value must be 22 for an eval installation. Is it possible add SLASH_22 support for `peering_cidr_range` on `google_apigee_instance`. Now i have issue then i try create google_apigee_instance with default range SLASH_23 for Eval org

**Comment by edwardmedia** [comment]
It appears api has updated the enums. It used to be `SLASH_23`. Now it is `SLASH_22`
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.instances#cidrrange
