### ISSUE TITLE
google_vpc_access_connector fails subnetwork check if using dynamic sub-block

### ISSUE THREAD

**Issue by txomon** [hashicorp/terraform-provider-google#9515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/hashicorp/google v3.72.0
+ provider registry.terraform.io/hashicorp/google-beta v3.72.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/newrelic/newrelic v2.23.0
```

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

Use example: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector#example-usage---vpc-access-connector-shared-vpc with a dynamic clause for the subnet.

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

* The google_vpc_access_connector should be happy about having a dynamic subblock of at least one element

### Actual Behavior

* The pre-check fails:
```
╷
│ Error: ExactlyOne
│ 
│   with module.network.google_vpc_access_connector.connector,
│   on main.tf line 25, in resource "google_vpc_access_connector" "connector":
│   25: resource "google_vpc_access_connector" "connector" {
│ 
│ "network": one of `network,subnet.0.name` must be specified
╵
```

### Steps to Reproduce

1. Take the example
2. Make it a `dynamic "subnet"` block
1. `terraform apply`
2. it will fail

### Important Factoids

* The check fails even if there is a mix of dynamic and static subnet blocks

**Comment by edwardmedia** [comment]
@txomon Without seeing your `dynamic code`, it is hard to see this is a provider bug. Do you have a config that could help demo this is the case?

**Comment by txomon** [comment]
I believe you are right, it seems to be a problem with terraform itself, as when the resource is in a submodule it seems to fail if the data provided comes from outside the module. Let me try to create an example code

**Comment by txomon** [comment]
Here you are.

Inside `network/main.tf` if you replace the `var.subnetworks` with the `local.subnetworks` version in line 21 you will be able to surface the bug. You don't even need to replace with valid values the variables in the top file.

[sample.zip](https://github.com/hashicorp/terraform-provider-google/files/6785672/sample.zip)

**Comment by edwardmedia** [comment]
You may file an issue against Terraform code.  Closing this issue here then. Thank you
