### ISSUE TITLE
Add support for `PublicAccessPrevention` to storage buckets (beta)

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-google#9519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCS has a feature to set `PublicAccessPrevention` attribute on buckets: https://cloud.google.com/storage/docs/using-public-access-prevention#storage_set_public_access_prevention_unspecified-go

### New or Affected Resource(s)

* google_storage_bucket

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_storage_bucket" "static-site" {
  name   = "image-store.com"

  public_access_prevention = "enforced"
}
```

### References

- https://cloud.google.com/storage/docs/using-public-access-prevention#storage_set_public_access_prevention_unspecified-go

**Comment by jcanseco** [comment]
Also requested by a KCC user here: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/498

**Comment by muhammadpanji** [comment]
Hi @rileykarson, I'm interested adding this functionality? Anyone already working on this issue? Thank you

**Comment by rileykarson** [comment]
Nope- we'd mark an assignee if so. I'll add you, given you're taking a look.

**Comment by unrealcloud** [comment]
I'd gladly help if needed as well!

**Comment by jackwhelpton** [comment]
I can take a swing at this, as I've just been looking at the provider code for an unrelated issue. PR coming up shortly, I'll add a link here...

**Comment by rileykarson** [comment]
Looks like you're most of the way there! @ScottSuarez was assigned as a reviewer and can assist.

**Comment by fculpo** [comment]
This is very needed on my side too, hope it's coming soon :)
