### ISSUE TITLE
google_bigtable_gc_policy cannot be destroyed on a replicated table

### ISSUE THREAD

**Issue by pritho** [hashicorp/terraform-provider-google#9521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.15.5

### Affected Resource(s)

* google_bigtable_gc_policy

### Terraform Configuration Files

```tf
resource "google_bigtable_app_profile" "cluster" {
  app_profile_id                = "automatic_failover"
  description                   = "automatic_failover"
  ignore_warnings               = true
  instance                      = google_bigtable_instance.instance.name
  multi_cluster_routing_use_any = true
}
resource "google_bigtable_app_profile" "cluster1" {
  app_profile_id  = "direct_primary"
  description     = "primary"
  ignore_warnings = true
  instance        = google_bigtable_instance.instance.name
  single_cluster_routing {
    allow_transactional_writes = false
    cluster_id                 = "primary"
  }
}
resource "google_bigtable_app_profile" "cluster2" {
  app_profile_id  = "direct_secondary"
  description     = "secondary"
  ignore_warnings = true
  instance        = google_bigtable_instance.instance.name
  single_cluster_routing {
    allow_transactional_writes = false
    cluster_id                 = "secondary"
  }
}
resource "google_bigtable_gc_policy" "policy1" {
  column_family = "fam1"
  instance_name = google_bigtable_instance.instance.name
  mode          = "UNION"
  table         = google_bigtable_table.table1.name
  max_age {
    duration = "8h"
  }
}
resource "google_bigtable_gc_policy" "policy2" {
  column_family = "famX"
  instance_name = google_bigtable_instance.instance.name
  mode          = "UNION"
  table         = google_bigtable_table.table2.name
}
resource "google_bigtable_gc_policy" "policy3" {
  column_family = "famY"
  instance_name = google_bigtable_instance.instance.name
  mode          = "UNION"
  table         = google_bigtable_table.table2.name
  max_age {
    duration = "7h"
  }
  max_version {
    number = 3
  }
}
resource "google_bigtable_gc_policy" "policy4" {
  column_family = "famZ"
  instance_name = google_bigtable_instance.instance.name
  mode          = "INTERSECTION"
  table         = google_bigtable_table.table2.name
  max_age {
    duration = "19h"
  }
  max_version {
    number = 7
  }
}
resource "google_bigtable_instance" "instance" {
  deletion_protection = false
  display_name        = "qual btn7o42g-ins"
  name                = "qual-btn7o42g-ins"
  cluster {
    cluster_id   = "frankfurt"
    num_nodes    = 2
    storage_type = "SSD"
    zone         = "europe-west6-a"
  }
  cluster {
    cluster_id   = "primary"
    num_nodes    = 2
    storage_type = "SSD"
    zone         = "europe-west6-b"
  }
  cluster {
    cluster_id   = "secondary"
    num_nodes    = 2
    storage_type = "SSD"
    zone         = "europe-west6-c"
  }
}
resource "google_bigtable_table" "table1" {
  instance_name = google_bigtable_instance.instance.name
  name          = "tableA"
  column_family {
    family = "fam1"
  }
}
resource "google_bigtable_table" "table2" {
  instance_name = google_bigtable_instance.instance.name
  name          = "tableB"
  column_family {
    family = "famX"
  }
  column_family {
    family = "famY"
  }
  column_family {
    family = "famZ"
  }
}

```

### Debug Output

`
rpc error: code = FailedPrecondition desc = Cannot relax pure age-based GC for a replicated family (fam1). If you must relax the age constraint, unreplicate the instance and try again.
`

### Expected Behavior

`terraform destroy` should work fine

### Actual Behavior

The resource cannot be destroyed because gc-policies cannot be deleted from a replicated table

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by edwardmedia** [comment]
@krathow this behavior is controlled by API. There is not much the Terraform layer can do. Have you tried to follow below suggestion? 

> If you must relax the age constraint, unreplicate the instance and try again.

**Comment by vdobler** [comment]
@edwardmedia You write

> If you must relax the age constraint, unreplicate the instance

What does "unreplicate" mean here? How would you do that with terraform? Does this mean we have to change the `resource "google_bigtable_instance"` to just one cluster first?

**Comment by edwardmedia** [comment]
@krathow your [config](https://github.com/hashicorp/terraform-provider-google/issues/9521#issue-939515320) appears not valid. Can you post a testable one and its debug log so I can take a close look?

**Comment by edwardmedia** [comment]
@krathow is this still an issue?

**Comment by krathow** [comment]
@edwardmedia - sorry my dummy code wasn't working. I've updated it above.

The error is still persistent there.
