### ISSUE TITLE
wrong project for reusable_config in google_privateca_certificate_authority resource

### ISSUE THREAD

**Issue by YpNo** [hashicorp/terraform-provider-google#9523]
Hi,

I've used `google_privateca_certificate_authority` resource to create my CA Certificate. The `tf apply` works but no any certificate is shown in the console and with the gcloud command.

I think the issue is located on `reusable_config` parameter which it must be set with the project name `privateca-data`, No ? :
`projects/568668481468/locations/<my_location>/reusableConfigs/root-unconstrained`

When I create the CA within the console and I import it in terraform, the `reusable_config` is not set. It forces the replacement in the next apply.

```terraform
resource "google_privateca_certificate_authority" "this" {
  provider                 = google-beta
  certificate_authority_id = "My Root CA"
  location                 = var.region
  lifetime                 = "314496000s"
  project                  = var.project_id
  type                     = "SELF_SIGNED"
  key_spec {
    algorithm = "EC_P256_SHA256"
  }
  tier = "ENTERPRISE"
  config {
    subject_config {
      common_name = "My Root CA #2021"
      subject {
        country_code        = "US"
        organization        = "My Company"
        organizational_unit = "IT"
        locality            = "New York"
      }
    }

    reusable_config {
      reusable_config = format("projects/568668481468/locations/%s/reusableConfigs/root-unconstrained", var.region)
    }
  }
  disable_on_delete = true

  issuing_options {
    include_ca_cert_url    = true
    include_crl_access_url = true
  }

  labels = {
    owner      = "infrastructure"
    managed-by = "terraform"
  }
}
```

Output:
```shell
...
google_privateca_certificate_authority.this: Creating...
google_privateca_certificate_authority.this: Still creating... [10s elapsed]
google_privateca_certificate_authority.this: Creation complete after 11s [id=projects/<my_project>/locations/us-central1/certificateAuthorities/My-Root-CA]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

Check with gcloud command:
```shell

$ gcloud privateca roots list --location us-central1
NAME              LOCATION      POOL                    STATE    INCLUDED_IN_POOL_ISSUANCE  NOT_BEFORE         NOT_AFTER

```
### Terraform & Provider Version

* Terraform v0.13.5
* google-beta 3.74.0

### Affected Resource(s)

* google_privateca_certificate_authority

### SDK Version

* Google Cloud SDK 347.0.0

Regards.

**Comment by edwardmedia** [comment]
@YpNo can you post the debug log for the **apply** execution? This is an interesting issue. Some fields are defined as **required** but you were able to run without providing the data. Below is just an [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_certificate_authority#x509_config) of these fields.

> x509_config - (Required) Describes how some of the technical X.509 fields in a certificate should be populated. Structure is documented below.

**Comment by YpNo** [comment]
Hi @edwardmedia,

`x509_config` didn't seem to exist in v3.74. And the reusable_config is gone in v3.75 ?

You want the debug of the apply execution after I imported the manually created resource, or when I tried to apply and create the CA at first ?

The debug log for the first regular apply in attach.

Regards.
[tf_debug.log.gz](https://github.com/hashicorp/terraform-provider-google/files/6816795/tf_debug.log.gz)

**Comment by edwardmedia** [comment]
@YpNo looks like `reusable_config` is gone in newer versions. I do see significant changes lately. No one is going to work on the obsolete code. Please use the latest version to build your resources.  Closing this issue now. If you see issues with latest versions, please file new bugs. Thanks
