### ISSUE TITLE
google_active_directory_domain authorized_networks should accept network self_link?

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-provider-google#9546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2
on linux_amd64

### Affected Resource(s)

* google_active_directory_domain

### Terraform Configuration Files

```tf
resource "google_active_directory_domain" "ad-domain" {
  domain_name       = "ad1.example.com"
  locations         = ["europe-west2"]
  reserved_ip_range = "192.168.255.0/24"
  authorized_networks = [module.network["vpc-test"].network_self_link]
}
```

### Expected Behavior

`authorized_networks` should accept the `self_link` of the network

### Actual Behavior

`authorized_networks` appears to require the `id` of the network

### References

See original issue raised to the Google network module team requesting that as a result of this resource needing `id` that could they make `id` an output, they seemed to suggest it best to raise a case here as self_link is more the typical reference to be passed and is already a top level output of the module:

See: https://github.com/terraform-google-modules/terraform-google-network/issues/307

* #0000

**Comment by edwardmedia** [comment]
@alecraso this is by design. There was an [initiative](https://github.com/hashicorp/terraform-provider-google/issues/5542) inside the provider that changed the **self_link** to **id**
