### ISSUE TITLE
Secret Manager Secret publishing to Cloud Pub/Sub requires rotation

### ISSUE THREAD

**Issue by madlenSt** [hashicorp/terraform-provider-google#9548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/google-beta v3.74.0

### Affected Resource(s)

* google_secret_manager_secret

### Terraform Configuration Files

```tf
variable "project_id" {
  type        = string
  description = "id of existing GCP project"
}

locals {
  gcp_service_list = toset([
    "cloudresourcemanager.googleapis.com",
    "iam.googleapis.com",
    "secretmanager.googleapis.com",
  ])

}

data "google_project" "this" {
  project_id = var.project_id
}

resource "google_project_service" "this" {
  for_each           = local.gcp_service_list
  disable_on_destroy = false
  project            = data.google_project.this.project_id
  service            = each.key
}

resource "google_pubsub_topic" "this" {
  name    = "my-pubsub-topic"
  project = data.google_project.this.project_id
}

resource "google_secret_manager_secret" "this" {
  secret_id = "my-secret"

  topics {
    name = google_pubsub_topic.this.id
  }

  replication {
    automatic = true
  }
  project = data.google_project.this.project_id
}

resource "google_project_service_identity" "secret_manager" {
  provider = google-beta

  project = data.google_project.this.project_id
  service = "secretmanager.googleapis.com"
}

resource "google_pubsub_topic_iam_member" "pub" {
  project = data.google_project.this.project_id
  topic   = google_pubsub_topic.this.name
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${google_project_service_identity.secret_manager.email}"
}
```

### Debug Output

```
│ Error: RequiredWith
│ 
│   with google_secret_manager_secret.this,
│   on main.tf line 30, in resource "google_secret_manager_secret" "this":
│   30: resource "google_secret_manager_secret" "this" {
│ 
│ "topics": all of `rotation,topics` must be specified
```

### Expected Behavior
Successful apply

### Actual Behavior
Setting rotation is required when using Pub/Sub topics unlike in case of configuring a secret manually in GCP.
So not setting the rotation leads to an error.

### Steps to Reproduce
* `terraform apply`

### Additional Information
As a workaround I set the rotation block to be empty and ignored changes to it, but I don't see why I have to specify it in first place when I don't want to rotate secrets.

```tf
resource "google_secret_manager_secret" "this" {
  secret_id = "my-secret"

  topics {
    name = google_pubsub_topic.this.id
  }

  replication {
    automatic = true
  }
  rotation {
  }
  lifecycle {
    ignore_changes = [
      rotation,
    ]
  }
  project = data.google_project.this.project_id
}
```

I added the ignore_changes block because without ignoring the changes, the secret will be updated at each new apply:

```tf
resource "google_secret_manager_secret" "this" {
  secret_id = "my-secret"

  topics {
    name = google_pubsub_topic.this.id
  }

  replication {
    automatic = true
  }
  rotation {
  }
  project = data.google_project.this.project_id
}
```
which you can see if you 
* run `terraform apply`
* run `terraform apply` again

```
Terraform will perform the following actions:

  # google_secret_manager_secret.this will be updated in-place
  ~ resource "google_secret_manager_secret" "this" {
        id          = "projects/project-id/secrets/my-secret"
        name        = "projects/number/secrets/my-secret"
        # (4 unchanged attributes hidden)


      + rotation {}

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by edwardmedia** [comment]
@madlenSt it appears `"topics": all of `rotation,topics` must be specified` is built on purpose. [Below](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets#rotation) is what api doc specifies: 

> The rotation time and period for a Secret. At nextRotationTime, Secret Manager will send a Pub/Sub notification to the topics configured on the Secret. Secret.topics must be set to configure rotation.

**Comment by madlenSt** [comment]
Yes, I see why setting the rotation requires a Pub/Sub topic.
But not the other way around, so specifying a Pub/Sub topic should not require a rotation if only used for [event-notifications](https://cloud.google.com/secret-manager/docs/event-notifications) like SECRET_VERSION_ADD other than SECRET_ROTATE.
As you can see the API request is successful without setting rotation and only setting the topic:
![Capture](https://user-images.githubusercontent.com/70107248/125589223-91128dbd-2a40-4432-bdbc-9635916aaf76.PNG)

**Comment by alexku7** [comment]
Why it has been closed?
Actually I encountered with the same bug.
The provider should allow applying the topics settings for notifications only regardless the rotation settings.

In many cases we want to set a topic for notification only without enabling the rotation
