### ISSUE TITLE
Add `ReservationAffinity` to `NodeConfig`

### ISSUE THREAD

**Issue by minac** [hashicorp/terraform-provider-google#9556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud allows for Resource Reservations to be consumed by a specific node. This feature uses the parameters `ReservationAffinity` and/or `Reservation`.
This is possible with `gcloud`, but not with Terraform yet, because Terraform [node_config](https://github.com/hashicorp/terraform-provider-google/blob/master/google/node_config.go) module does not support all available NodeConfig parameters, namely [ReservationAffinity](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#ReservationAffinity).

```
gcloud container node-pools create NODEPOOL_NAME \
    --cluster CLUSTER_NAME --num-nodes=2 \
    --machine-type=MACHINE_TYPE \
    --reservation-affinity=specific --reservation=RESERVATION_NAME
```

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "myname" {
   /* (...) */
  node_config {
    reservation {
      reservation-affinity = specific
      reservation-name = myreservation
    }
   /* (...) */
```

### References

* https://github.com/hashicorp/terraform-provider-google/blob/master/google/node_config.go
* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#ReservationAffinity
* https://cloud.google.com/kubernetes-engine/docs/how-to/consuming-reservations
* https://cloud.google.com/compute/docs/instances/reserving-zonal-resources#how_reservations_work

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6412
