### ISSUE TITLE
google_monitoring_notification_channel auth_token for slack doesn't work

### ISSUE THREAD

**Issue by Mor-Kam** [hashicorp/terraform-provider-google#9564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26 

### Affected Resource(s)

* google_monitoring_notification_channel

### Terraform Configuration Files

```tf
variable "auth_token" {
  type        = string 
  description = "auth_token for slack notification channel"  
}

resource "google_monitoring_notification_channel" "slack_bot" { 
  provider = google
  #project = var.project
  display_name = "${var.environment}-notifcation-channel-slack" 
  type = "slack" 
  labels = { 
    "channel_name" = "#ops" 
  
  }

  sensitive_labels { 
    auth_token = var.auth_token
  }

} 
```
The auth_token is obtained from slack-bot and stored as a TF_VAR env variable 

### Expected Behavior

Terraform should have created a slack notification channel in GCP authenticated to work with our slack workspace. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/35569950/125775799-51188046-b45d-49ed-a183-50cb68b8402c.png)

The above error is seen and the resource is created without the proper authentication to the slack workspace. 

### Steps to Reproduce

Install the Google Monitoring to your slack workspace. 

Copy the automatically generated oAuth Token and set it as an TF_VAR env var 

Run terraform apply 

1. `terraform apply`

* #0000

**Comment by edwardmedia** [comment]
@Mor-Kam from what you provided, it is hard to say what went wrong. In order to debug the issue, can you follow the suggestion from the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_notification_channel) to see if we can figure it out?

> Due to these loose constraints it's often best to set up a channel through the UI and import to Terraform when setting up a brand new channel type to determine which labels are required.

**Comment by edwardmedia** [comment]
@Mor-Kam is this still an issue?
