### ISSUE TITLE
google_billing_budget budget_filter projects order is unpredictable and leads to constant changes

### ISSUE THREAD

**Issue by jalmeroth** [hashicorp/terraform-provider-google#9566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2
+ provider registry.terraform.io/hashicorp/google v3.75.0

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
provider "google" {
  project      = "<redacted>"
  region       = "europe-west3"
  zone         = "europe-west3-c"
}

data "google_project" "project_a" {
  project_id = "<redacted>"
}

data "google_project" "project_b" {
  project_id = "<redacted>"
}

data "google_billing_account" "account" {
  billing_account = "<redacted>"
}

resource "google_billing_budget" "budget" {
  billing_account = data.google_billing_account.account.id
  display_name    = "Example Billing Budget"
  amount {
    specified_amount {
      currency_code = "EUR"
      units         = "101"
    }
  }
  threshold_rules {
    threshold_percent = 0.5
  }

  budget_filter {
    projects = [
      data.google_project.project_a,
      data.google_project.project_b,
    ]
  }
}
```

### Debug Output

```
~ budget_filter {
  ~ projects               = [
      - "projects/442837xxxxxx",
        "projects/106809xxxxxx",
        # (1 unchanged element hidden)
        "projects/336745xxxxxx",
      + "projects/442837xxxxxx",
    ]
    # (5 unchanged attributes hidden)
}
```
### Expected Behavior

On second run (after the billing budget has been created successfully) the sort order of budget_filter -> projects-list remains the same.

### Actual Behavior

The sort order of budget_filter -> projects-list is unpredictable. It's neither sorted by project number nor by project name.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids

This behaviour wasn't present before release 3.52.0.

### References

n/a

**Comment by jalmeroth** [comment]
@edwardmedia has this fix been released with the release 3.76.0? I don't see it been mentioned in the changelog nor the issue has been resolved.

**Comment by edwardmedia** [comment]
@jalmeroth it is released in v3.76.0

I see the fix in the master. Here is the test for your case. https://github.com/hashicorp/terraform-provider-google/blob/8a1ae88456533a21c62e417ced15287d042029f5/google/resource_billing_budget_test.go#L287

**Comment by edwardmedia** [comment]
@jalmeroth can you share your debug log with the latest release?

**Comment by jalmeroth** [comment]
@edwardmedia I ran our tests with the today's release v3.77.0 and with that it works as expected. But when I run it with v3.76.0 it doesn't. 🤷‍♂️ Anyway, it works now – so thank you very much!
