### ISSUE TITLE
provider_meta not being inherited by submodules 

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform-provider-google#9573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.0

### Affected Resource(s)

N/A (all resources)

### Terraform Configuration Files

*main.tf*
```tf
module "test" {
    source = "./submod"
}

terraform {
  provider_meta "google" {
    module_name = "hello-gcp"
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.67"
    }
  }
}
```
*submod/main.tf*
```tf

resource "random_id" "server" {
  byte_length = 8
}

resource "google_service_account" "default" {
project = "test-project-tf-bug-attrib"
  account_id   = "test-${random_id.server.hex}"
}
```

### Debug Output

User Agent `hello-gcp` is missing

```
---[ REQUEST ]---------------------------------------
GET /v1/projects/PROJECT_ID/serviceAccounts/test-b46569bb50e0d443@PROJECT_ID.iam.gserviceaccount.com?alt=json&prettyPrint=false HTTP/1.1
Host: iam.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/1.0.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/3.75.0
X-Goog-Api-Client: gl-go/1.16.2 gdcl/20210606
Accept-Encoding: gzip
```

### Expected Behavior

User Agent `hello-gcp` is present

### Actual Behavior

User Agent `hello-gcp` is missing

If we add `provider_meta` to the submodule like below, we get the expected user agent

```
*submod/main.tf*
```tf

resource "random_id" "server" {
  byte_length = 8
}

resource "google_service_account" "default" {
project = "test-project-tf-bug-attrib"
  account_id   = "test-${random_id.server.hex}"
}

terraform {
  provider_meta "google" {
    module_name = "hello-gcp"
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.67"
    }
  }
}

```

```
---[ REQUEST ]---------------------------------------
GET /v1/projects/PROJECT_ID/serviceAccounts/test-b46569bb50e0d443@PROJECT_ID.iam.gserviceaccount.com?alt=json&prettyPrint=false HTTP/1.1
Host: iam.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/1.0.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/3.75.0 hello-gcp
X-Goog-Api-Client: gl-go/1.16.2 gdcl/20210606
Accept-Encoding: gzip

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-google/issues/8346

**Comment by bharathkkb** [comment]
@rileykarson I don't think this is a duplicate of #8346

Our understanding was that provider_meta block would pick up the nearest definition. In this case the nearest definition was in the root module and there was no provider_meta in the submodule so it should have picked up the root module provider_meta?

**Comment by rileykarson** [comment]
Ah, got it- I think it's the same underlying problem in any case and it's worth expanding that issue to cover both. I guess we could keep two issues, but honestly, they'd be in the same place- this is an issue with one or both of the SDK/Core's implementation of the feature.

**Comment by bharathkkb** [comment]
@rileykarson is there an upstream issue we can track?

**Comment by rileykarson** [comment]
Given https://github.com/hashicorp/terraform-provider-google/issues/8346 doesn't link any, I'd assume no
