### ISSUE TITLE
google_bigquery_job requires bigquery.tables.create permission?

### ISSUE THREAD

**Issue by MartinPetkov** [hashicorp/terraform-provider-google#9577]
We have a terraform config which is creating a google_bigquery_job to insert data into an existing unpartitioned BigQuery table in an existing dataset. It's pretty much this:

```


resource "google_bigquery_job" "insert_data" {
    job_id  = "insert_data"
    project = local.project_id

    query {
        query = <<EOF
SELECT
...
EOF

        destination_table {
            project_id = local.project_id
            dataset_id = local.dataset_id
            table_id = local.table_id
        }
 
        script_options {
            key_result_statement = "LAST"
        }
 
        write_disposition = "WRITE_APPEND"
        flatten_results   = true
        }
    }
}
```

However, for some reason trying to apply it via Terraform with a limited role results in this error:

```
Error: Error creating Job: googleapi: Error 403: Access Denied: Dataset my-project:my_dataset: Permission bigquery.tables.create denied on dataset my-project:my_dataset (or it may not exist)., accessDenied
 
  on main.tf line 115, in resource "google_bigquery_job" "insert_data":
 115: resource "google_bigquery_job" "insert_data" {
```

Why does this happen? I can't find any mention in the docs of this permission being required just to run a google_bigquery_job.

**Comment by edwardmedia** [comment]
@MartinPetkov the error comes from api, which is pretty clear. Terraform does not have much control over that. You may want to review the 1) [permissions] (https://cloud.google.com/bigquery/docs/jobs-overview#required_permissions) are in place and 2) if the dataset exists. Does this make sense?

**Comment by edwardmedia** [comment]
@MartinPetkov is this still an issue?

**Comment by MartinPetkov** [comment]
It is still an issue and I haven't explored by the extra permission is needed, but I'll close this issue since it's something to do with GCP and not the provider.
