### ISSUE TITLE
Google provider - notebooks environment 

### ISSUE THREAD

**Issue by terekete** [hashicorp/terraform-provider-google#9579]
Hi Community,

Looking for a bit of help with the Google Provider in regards to Notebook Environments. I am looking to build out some environments based on container images. When I try to do that I am not seeing them appear in the notebook UI console drop down in the Vertex notebooks section.

Question I have is: 
1. Is this how this resource is meant to function, show the environment in the UI? (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_environment)
2. If so, is there any reason it may not be showing up in the console/UI ?

**Comment by edwardmedia** [comment]
@terekete can you see if the below resource can help you? 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#example-usage---notebook-instance-basic

**Comment by edwardmedia** [comment]
@terekete have your question been addressed?

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer an question
