### ISSUE TITLE
google_project_organization_policy - Resource Location Restriction

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#9581]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2
hashicorp/google v3.74.0

### Affected Resource(s)

* google_project_organization_policy

### Terraform Configuration Files

```tf
resource "google_project_organization_policy" "location_org_policy" {
  for_each   = local.project_env_ids
  project    = each.value
  constraint = "constraints/gcp.resourceLocations"

  list_policy {
    allow {
      values = [for location in lookup(var.project_location_override, each.key, var.location_policy_config[each.key]) : "in:${location}-locations"]
    }
  }
}
```
Just an example from our code base, but can be easily modified to re-create the below issue.

### Debug Output

```
│ Error: googleapi: Error 409: The operation was aborted., aborted
│ 
│   with module.location-org-policy["id"].google_project_organization_policy.location_org_policy["dev-env"],
│   on .terraform/modules/location-org-policy/location-organization-policy/main.tf line 6, in resource "google_project_organization_policy" "location_org_policy":
│    6: resource "google_project_organization_policy" "location_org_policy" {
│ 
╵
╷
│ Error: googleapi: Error 409: The operation was aborted., aborted
│ 
│   with module.location-org-policy["id"].google_project_organization_policy.location_org_policy["env"],
│   on .terraform/modules/location-org-policy/location-organization-policy/main.tf line 6, in resource "google_project_organization_policy" "location_org_policy":
│    6: resource "google_project_organization_policy" "location_org_policy" {
```

### Expected Behavior

The organisational policy should be updated.

### Actual Behavior

The organisational policy was not updated but the terraform plan thinks it executed, re-running the pipeline then shows no changes however in the console it remains with the old conditions.

### Steps to Reproduce

1. Have a project with a resource location restriction, for example our org is europe-west2 only.
2. Manually change the organisational policy to add in europe locations
3. Revert back then to the europe-west2 only. 
4. Try and run terraform to change the org policy and it fails with the aborted message. 

### Important Factoids

For some extra background, we manage our projects via a factory written in TF. I had manually updated some old projects with org policy exceptions and wanted to go back and have terraform manage that config (since we added that capability to our process recently). Hence the manually add/remove steps.

**Comment by edwardmedia** [comment]
@drandell instead of the dynamic / variable code, can you repro the issue with a hard-coded config? If can, please post the config so we can take a look at the resource's implementation.

**Comment by drandell** [comment]
Had state re-fresh off by mistake. It did work with hard-coded values and after that i looked into this more. Closing this now
