### ISSUE TITLE
Add example in doc to create Subordinate CAs for google_privateca_certificate_authority

### ISSUE THREAD

**Issue by Matroxt** [hashicorp/terraform-provider-google#9584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Creating a Subordinate CA via the Google Cloud Web interface is really straight forward, but it's a lot less clear how to do it via Terraform. The documentation examples seem to cover Root CAs only. 

An example [in the doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_certificate_authority) would make the resource usage more user friendly.

### New or Affected Resource(s)

* google_privateca_certificate_authority

### Potential Terraform Configuration

I don't think this requires new configurations in the provider, just a new example in the documentation.

**Comment by slevenick** [comment]
Currently I don't think this is actually possible through the provider. In my understanding configuring a subordinate CA requires setting up 2 CAs, using [this method](https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificateAuthorities/fetch) to fetch the CSR, manually signing that CSR and then adding the result back into the CA with another [custom method](https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificateAuthorities/activate).

This is not a great fit for Terraform as it requires manual steps, so I don't think an example would be very helpful
