### ISSUE TITLE
Extract metrics related to MM Github PR status trust

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9585]
We want to be able to trust that our checks are reliable. One way to measure this is: how many PRs do we merge that have failed checks? (Ideally it would also be great to know how many we merged without waiting to see whether tests passed.) We should track this over time.

Essentially this comes down to getting the following information about each MM PR that was merged since the last script run:

- How many checks/statuses were run for the last commit total?
- How many checks/statuses failed?
- How long did each check/status take?
- Was the merge before or after the last status check completed?

For now, this could be implemented as a script that we run occasionally to get the relevant data from Github.

Depends on https://github.com/hashicorp/terraform-provider-google/issues/9589 for completion.

**Comment by rileykarson** [comment]
note: We should consider Apps Script [Google] internally, they can be shared in team drive

**Comment by rileykarson** [comment]
We are probably not gonna take any action based on this specific bug.
