### ISSUE TITLE
Remove ansible/inspec support from magic modules

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9588]
Practically speaking, mmv1 has not been supporting ansible/inspec for some time - i.e. we would not do work to add support for new resources, update resources due to API changes, or fix bugs in those codebases.

However, we still have a lot of code in magic modules related to supporting those codebases, which adds complexity / makes the code harder to search, and makes the prospect of making improvements to the core generation code daunting / infeasible.

We should remove all the code specific to inspec / ansible in order to simplify magic modules - including:

- [x] build steps
- [ ] ruby code (the compilation providers & any code supporting specifically these providers)
~- [ ] yaml files~ https://github.com/hashicorp/terraform-provider-google/issues/12509
- [x] products that don't have a terraform.yaml file

**Comment by wyardley** [comment]
This is a bummer; I don't know all the background / politics, but hope we can see either a GCP project that supports spec testing of these resources, or a return of using Magic Modules to generate inspec resources.

I realize this may not necessarily be on Google's end, and inspec-gcp itself doesn't seem super actively maintained these days, but it seems inconvenient to manually add support to resources directly there vs. benefiting from all the work happening upstream here.
