### ISSUE TITLE
Add support for requesting a Private Certificate Authority Certificate using an auto-generated key

### ISSUE THREAD

**Issue by emossman** [hashicorp/terraform-provider-google#9593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I would like to be able to request certificates from Private CA without needing to generate and manage private key material. 

Currently, a public key needs to be specified in the config.public_key block.

The GCP console and gcloud commands allow for auto generation of key material - see here: https://cloud.google.com/certificate-authority-service/docs/requesting-certificates#console_1 and here: https://cloud.google.com/certificate-authority-service/docs/requesting-certificates#gcloud_1

### New or Affected Resource(s)

* google_privateca_certificate

### Potential Terraform Configuration

```tf
resource "google_privateca_certificate" "certificate" {
  project               = var.project_name
  location              = var.region
  certificate_authority = var.root_ca_name
  lifetime              = var.certificate_lifetime
  name                  = var.cert_name
  pool                  = var.root_ca_pool
  labels                = var.labels
  config {
    subject_config {
      subject {
        common_name         = var.cert_common_name
        country_code        = var.country_code
        organization        = var.organization
        organizational_unit = var.ou
        locality            = var.locality
        province            = var.province
      }
      subject_alt_name {
        dns_names       = var.dns_names_list
        email_addresses = var.email_addresses_list
      }
    }

    public_key {
      **generate = true**
    }
    x509_config {
      ca_options {
        is_ca = false
      }
      key_usage {
        base_key_usage {
          crl_sign      = false
          decipher_only = false
        }
        extended_key_usage {
          server_auth = false
        }
      }
    }
  }
```

### References

None

**Comment by rileykarson** [comment]
@slevenick: Can you take a look at how this would work w/ TF?

**Comment by pmansour** [comment]
@emossman in this scenario, where would you foresee the associated private key being stored?

When gcloud and GCP cloud console perform key generation, they generate the key-pair locally and persist the generated private key to the local machine (via the [--key-output-file](https://cloud.google.com/sdk/gcloud/reference/privateca/certificates/create#--key-output-file) gcloud flag or through a download link in Cloud Console). A way to securely store the generated private key is essential to making the certificate useful.

I'd love to hear your thoughts on this.

**Comment by emossman** [comment]
@pmansour

I didn't realize that the private key was persisted locally in both of those examples. That complicates things.

Some of the options for storing the associated key pair could be:
- locally on the machine that is executing terraform
  - I don't like this because then you need to manually move the key pair elsewhere
- GCP Secret Manager
  - This is better, but it would need a corresponding terraform resource to be created
- Google Cloud Storage
  - I like this less than Secret Manager because it is not purpose built for secrets, and a bucket and bucket object would still need to be created

**Comment by slevenick** [comment]
@pmansour is there any action that should be taken within the Terraform provider at this point? It seems like there is not a great solution to storing the private key at this point, and Terraform is likely not the right answer here.

**Comment by melinath** [comment]
b/259264471

**Comment by gfxcc** [comment]
Auto-generated key can be achieved via using `tls_private_key`. [This code sample](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/privateca_quickstart/main.tf) shows how to generate the private key in terraform and sign it via CAS.

Code snippets 
```
provider "tls" {}

resource "tls_private_key" "example" {
  algorithm = "RSA"
}
...
resource "google_privateca_certificate" "default" {
  pool                  = google_privateca_ca_pool.default.name
  certificate_authority = google_privateca_certificate_authority.test_ca.certificate_authority_id
  location              = "us-central1"
  lifetime              = "860s"
  name                  = "my-certificate"
  pem_csr               = tls_cert_request.example.cert_request_pem
}
```

At the end, you can output the private key of `tls_private_key.example` as needed. 

This should fulfill the request.

**Comment by gfxcc** [comment]
@slevenick please take a look and close the issue as needed.
