### ISSUE TITLE
The terraform-provider-google-beta_v3.62.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by betsy-lichtenberg** [hashicorp/terraform-provider-google#9594]
Report attached.

[crash-report.txt](https://github.com/hashicorp/terraform-provider-google/files/6844112/crash-report.txt)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@betsy-lichtenberg can you post the steps to get the log?

**Comment by betsy-lichtenberg** [comment]
1. Run the example https://github.com/terraform-google-modules/terraform-google-lb-internal/tree/master/examples/simple

terraform init
terraform apply
terraform destroy

It didn't happen right away, but after several rounds of creating and destroying, it started happening.

I fixed it locally by removing the beta block from main.tf:

provider "google-beta" {
  version = "~> 3.62.0"
}

**Comment by edwardmedia** [comment]
@betsy-lichtenberg do you have a debug log available so I can take a look? The example you provided is a module. Do you want to file an issue against its owner instead?

**Comment by betsy-lichtenberg** [comment]
Sure, I'll do that. Thanks.

**Comment by dv-stephen** [comment]
I'm experiencing the same problem. Debug log is here: https://gist.github.com/dv-stephen/0216e431e6e1b7e9677b1769cf3022e2

**Comment by edward2a** [comment]
Hi all, I think I was tagged by mistake?

**Comment by dv-stephen** [comment]
@edward2a Whoops, yes. Sorry!

/cc @edwardmedia
