### ISSUE TITLE
Cloud Run Service Secret Environment Variables throws "spec.template.spec.containers[0].env.value_from should be empty" with further metadata annotations

### ISSUE THREAD

**Issue by BasileNq** [hashicorp/terraform-provider-google#9596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.2

### Affected Resource(s)

- google_cloud_run_service
- google_vpc_access_connector
- google_secret_manager_secret

### Terraform Configuration Files

```tf

resource "google_vpc_access_connector" "connector" {
  name          = "vpc-connector"
  ip_cidr_range = "range"
  network       = google_compute_network.private_network.name
}

resource "google_secret_manager_secret" "secret" {
  secret_id = "id"
    replication {
        automatic = true
    }
}

resource "google_secret_manager_secret_version" "secret_basic" {
  provider = google-beta
  secret = google_secret_manager_secret.secret.name

  secret_data = "data"
}

resource "google_secret_manager_secret_iam_member" "secret_access" {
  provider = google-beta

  secret_id = google_secret_manager_secret.secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"
  depends_on = [google_secret_manager_secret.secret]
}


resource "google_cloud_run_service" "service" {
  provider = google-beta
  name     = "name
  location = region
  project  = project

  
  template {
    spec {
      containers {
        image = image
        env {
          name = "name_secret"
        value_from {
            secret_key_ref {
              name = google_secret_manager_secret.secret_db_pass.secret_id
              key = "latest"
            }
          } 
        }
        env {
          name = "name1"
          value = "value1"
        }
        env {
          name = "name2"
          value = "value2"
        }
        env {
          name = "name3"
          value = "value3"
        }
      }
      timeout_seconds = 900
    }
    
    metadata {
      annotations = {
        generated-by = "magic-modules"
        "run.googleapis.com/launch-stage" = "BETA"
        "run.googleapis.com/vpc-access-connector"= google_vpc_access_connector.connector.name
      }
    }

  }
  traffic {
    percent         = 100
    latest_revision = true
  }
  autogenerate_revision_name = true

  lifecycle {
    ignore_changes = [
        metadata.0.annotations,
    ]
  }
  depends_on = [google_secret_manager_secret.secret]
}

```

### Debug Output

│ Error: Error creating Service: googleapi: Error 400: spec.template.spec.containers[0].env.value_from: spec.template.spec.containers[0].env.value_from should be empty
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "spec.template.spec.containers[0].env.value_from should be empty",
│         "field": "spec.template.spec.containers[0].env.value_from"
│       }
│     ]
│   }
│ ]
│ 
│   with google_cloud_run_service.service,
│   on main.tf line 344, in resource "google_cloud_run_service" "service":
│  344: resource "google_cloud_run_service" "service" {

### Expected Behavior

This should add a connector (connections section on gcp) and a secret (variables and secrets section on gcp) to the cloud run service. 

### Actual Behavior

According to the terraform documentation, the metadata section should be located after the template section. However, after some research this could be a mistake and it should be located in the right hand side after the template spec section. When it is located here, you can add a secret (without a connector), which is not the case when it is placed below template.

### Steps to Reproduce

Add a private network for the connector, an image and run plan then apply.

Ex private network: 
```tf
resource "google_compute_network" "private_network" {
  name = "private-network"
  auto_create_subnetworks = false
}
```

### References

This could be usefull: 
* https://github.com/hashicorp/terraform-provider-google/issues/9159

**Comment by edwardmedia** [comment]
@BasileNq there is a discussion (see below). Can you see if that helps? 

https://github.com/hashicorp/terraform-provider-google/issues/9441

**Comment by BasileNq** [comment]
Thank you for your answer edwardmedia. I take a look to the discussion but unfortunately it doesn't help. 
If i'm setting up either the secret or the connector, it works perfectly. However, when i'm setting up both in the same Cloud Run service, i get the output below: 
```tf
│ Error: Error creating Service: googleapi: Error 400: spec.template.spec.containers[0].env.value_from: spec.template.spec.containers[0].env.value_from should be empty
│ Details:
│ [
│ {
│ "@type": "type.googleapis.com/google.rpc.BadRequest",
│ "fieldViolations": [
│ {
│ "description": "spec.template.spec.containers[0].env.value_from should be empty",
│ "field": "spec.template.spec.containers[0].env.value_from"
````

**Comment by edwardmedia** [comment]
@BasileNq can you share the full debug log?

**Comment by BasileNq** [comment]
Sure: [here](https://gist.github.com/BasileNq/7e716bc345b606e757a55091af8a277e)

**Comment by edwardmedia** [comment]
@BasileNq it works fine with me for having both the secret and the connector. Do you have `run.googleapis.com/secrets` in your annotation like below?

```
  template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale": "1000",
        "autoscaling.knative.dev/minScale": "1",
        "run.googleapis.com/client-name": "terraform",
        "run.googleapis.com/launch-stage": "ALPHA",
        "run.googleapis.com/secrets" = "secret-1b43ced0-7ffd-7734-98ed-fe39c701579f:projects/611764914450/secrets/secret".    <-------- this line 
        "run.googleapis.com/vpc-access-connector" = google_vpc_access_connector.connector.name
      }
    }
...
```

**Comment by BasileNq** [comment]
No, i don't have the ```run.googleapis.com/secrets``` in my annotation. This annotation isn't specified  in the cloud run service terraform documentation. How did you get the first part of the annotation value: ```secret-1b43ced0-7ffd-7734-98ed-fe39c701579f``` ?

**Comment by edwardmedia** [comment]
@BasileNq it is the secretName. This is the format when the secret is in a different project. There is a little discussion over [here](https://github.com/hashicorp/terraform-provider-google/issues/9441#issuecomment-875761254)

**Comment by BasileNq** [comment]
Okay but my secret is in the same project. I try it out with the following configuration :
```tf
locals {
  env_secrets ={
    SECRET_KEY : google_secret_manager_secret.secret_db_pass.id
  }
  project = {
    id: var.gcp_project,
    region: "europe-west1"

  }
}

resource "random_uuid" "secrets" {
  for_each = local.env_secrets
}

locals {
  # Secrets seem
  secret_uuid = {for env_name, secret_id in local.env_secrets : env_name => "secret-${random_uuid.secrets[env_name].result}"}
  secret_mappings = {for env_name, secret_id in local.env_secrets : env_name => "${local.secret_uuid[env_name]}:${secret_id}"}
  run_googleapis_com_secrets = join(",", values(local.secret_mappings))
}



  template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale": "1000",
        "autoscaling.knative.dev/minScale": "1",
        "run.googleapis.com/client-name": "terraform",
        "run.googleapis.com/launch-stage": "ALPHA",
        "run.googleapis.com/secrets" = local.run_googleapis_com_secrets #    <-------- this  line 
        "run.googleapis.com/vpc-access-connector" = google_vpc_access_connector.connector_db.name
      }
```
But I have still the same issue.

**Comment by edwardmedia** [comment]
@BasileNq below is the config I was using to test.  Can you see if that works for you?

```tf
resource "google_cloud_run_service" "default" {
  provider = google-beta

  name     = "issue9596-cloudrun-srv"
  location = "us-central1"

  template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale": "1000",
        "autoscaling.knative.dev/minScale": "1",
        "run.googleapis.com/client-name": "terraform",
        "run.googleapis.com/launch-stage": "ALPHA",
        "run.googleapis.com/secrets" = "secret-1b43ced0-7ffd-7734-98ed-fe39c701579f:projects/61176400000/secrets/secret"
        "run.googleapis.com/vpc-access-connector" = google_vpc_access_connector.connector.name
      }
    }

    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
        env {
          name = "SECRET_ENV_VAR"
          value_from {
            secret_key_ref {
              name = "secret-1b43ced0-7ffd-7734-98ed-fe39c701579f"
              key = "1"
            }
          }
        }
        env {
          name = "name1"
          value = "value1"
        }
        env {
          name = "name2"
          value = "value2"
        }
        env {
          name = "name3"
          value = "value3"
        }
      }
    }
  }

  metadata {
    annotations = {
      generated-by = "magic-modules"
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
  autogenerate_revision_name = true

  lifecycle {
    ignore_changes = [
        metadata.0.annotations,
    ]
  }
}

resource "google_vpc_access_connector" "connector" {
  name          = "issue9596-vpc-con"
  ip_cidr_range = "10.8.0.0/28"
  network       = "default"
}
```

**Comment by BasileNq** [comment]
I have created a new project to test this configuration. It does not pose any problem. 
So I went back to my initial project, I delete my Cloud Run service and ran terraform apply and didn't get any error.
Here is my final configuration: 
```
resource "google_cloud_run_service" "service" {
  provider = google-beta
  name     = "name-service"
  location = var.gcp_region
  project  = var.gcp_project

  
  template {
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale": "100",
        "autoscaling.knative.dev/minScale": "0",
        "run.googleapis.com/client-name": "terraform",
        "run.googleapis.com/vpc-access-connector" = google_vpc_access_connector.connector.name
      }
    }
    spec {
      containers {
        image = ilage
        env {
          name = "secret-env"
        value_from {
            secret_key_ref {
              name = google_secret_manager_secret.secret.secret_id
              key = "latest"
            }
          } 
        }
        env {
          name = "name3"
          value = "value3"
        }
        env {
          name = "name2"
          value = "value2"
        }

        env {
          name = "name1"
          value = "value1"
        }
      }
      timeout_seconds = 900
    }
    
    

  }
  metadata {
    annotations = {
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
  autogenerate_revision_name = true

  lifecycle {
    ignore_changes = [
        metadata.0.annotations,
    ]
  }
  depends_on = [google_secret_manager_secret.secret]
}
```
I don't know if it's because I deleted the service but the two annotation sections are important in this configuration.
Thank you edwardmedia  for your time.

**Comment by edwardmedia** [comment]
@BasileNq You are welcome. I am glad you have resolved the problem. Closing the issue then
