### ISSUE TITLE
google_compute_url_map does not support weighted backend service with serverless NEG

### ISSUE THREAD

**Issue by asodja** [hashicorp/terraform-provider-google#9600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_url_map

### Context
Since we are migrating from AppEngine I try to do a traffic split between two Serverless services: AppEngine and CloudRun. I try to do this with `google_compute_url_map`. Unfortunately it seems that this does not work or is not supported.  

### Terraform Configuration Files

```tf
locals {
  project = "my-project"
}

resource "google_compute_url_map" "default2" {
  name = "url-map-target-proxy3"
  description = "a description"
  project = local.project
  default_service = google_compute_backend_service.cloudrun.id

  host_rule {
    hosts = ["some.host"]
    path_matcher = "allpaths"
  }

  path_matcher {
    name = "allpaths"
    default_service = google_compute_backend_service.cloudrun.id

    route_rules {
      priority = 1
//      service = google_compute_backend_service.cloudrun.id
      route_action {
        weighted_backend_services {
          backend_service = google_compute_backend_service.cloudrun.id
          weight = 1000
        }
      }
    }
  }
}

resource "google_compute_backend_service" "cloudrun" {
  name = "cloudrun-backend1"
  port_name = "http"
  protocol = "HTTP"
  project = local.project
  timeout_sec = 30
  backend {
    group = google_compute_region_network_endpoint_group.cloudrun_neg.id
  }
}

resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
  name = "cloudrun-neg1"
  network_endpoint_type = "SERVERLESS"
  project = local.project
  region = "us-central1"
  cloud_run {
    service = google_cloud_run_service.cloudrun_neg.name
  }
}

resource "google_cloud_run_service" "cloudrun_neg" {
  name     = "cloudrun-neg1"
  location = "us-central1"
  project = local.project
  template {
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### Debug Output

https://gist.github.com/asodja/8942ba2ef998e0a0cae890f625f8d2c1

### Expected Behavior

Url map with weighted backend service is created

### Actual Behavior

Error is given:
`Error: Error creating UrlMap: googleapi: Error 400: Invalid value for field 'resource': '{  "name": "url-map-target-proxy3",  "description": "a description",  "hostRule": [{    "host": ["so...'. One of backend_service or url_redirect must be set, invalid`

If I uncomment `service = google_compute_backend_service.cloudrun.id` I get: `Exactly one of backend service or route action weighted service must be specified for a route rule`

If I change `route_rules` to `path_rule` then I get error:`Advanced routing rules are not supported for scheme EXTERNAL`.
So I suspect this is not even possible with Serverless NEG.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@asodja this error is from api where these rules are set. Can you create this **url_map** via other methods?

**Comment by asodja** [comment]
Oh ok. I will check.

**Comment by asodja** [comment]
I got an update from Google support via our TAM and it looks like servlerless traffic splitting is not possible at the moment with url map. But it will be in future (GA for Advanced Traffic Management features is planned for Q1 '22).

**Comment by edwardmedia** [comment]
@asodja closing this then. Thanks for checking
