### ISSUE TITLE
Location validation for Cloud Function

### ISSUE THREAD

**Issue by bboughton** [hashicorp/terraform-provider-google#9602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Would it be possible to add validation to the region parameter of the cloudfunction resource? At the moment Cloud Functions are [not available in all GCP locations](https://cloud.google.com/functions/docs/locations). If you try to use this provider to create a cloudfunction in a location that is not supported the plan will succeed, because of the lack of validation, but it will fail to apply. Ideally the input can be validated before trying to apply the change.

I submitted PR #9555 to address this issue but it was rejected because it could cause a poor user experience and/or be difficult to maintain. I've since done some additionally looking and it appears that there is an [API endpoint](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations/list) that lists the locations that are available for cloud functions. Would source this list to assist in validation be a viable option?

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

N/A

### References

N/A

**Comment by rileykarson** [comment]
Terraform requires that `ValidateFunc` functions- the ones responsible for plan time validations- don't make external API calls, so calling a locations API is not possible. @melinath covered the reasons we can't use a static list in https://github.com/hashicorp/terraform-provider-google/pull/9555#issuecomment-883611366.
