### ISSUE TITLE
Support configuring Subordinate CA with PrivateCA resources

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform-provider-google#9604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Configuring subordinate CAs is a fairly common use-case. Currently this requires manual steps outside of Terraform to fetch a CSR, sign it and send the result back to the API. These actions happen through custom REST verbs and could be partially implemented in Terraform, but the actual signing of the request likely will always need to happen out of band.

See: https://cloud.google.com/certificate-authority-service/docs/creating-certificate-authorities#subordinate-external

### New or Affected Resource(s)

* google_privateca_certificate_authority

### Potential Terraform Configuration

Unsure at the moment, but would likely call custom methods for fetch & activate on Certificate Authority API: https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificateAuthorities

This may need to involve a manual process for signing the key, which makes it difficult to implement. Will likely require some thought on how to best proceed

### References

* https://github.com/hashicorp/terraform-provider-google/issues/9584

**Comment by wrobelma** [comment]
My issue #9663 was mostly a bug not an enhancement so it could be fixed faster then this issue just by allowing for a successful creation of a google_privateca_certificate_authority sub CA resource in an activation_pending state.

**Comment by drebes** [comment]
This is not only about activation. The current code is broken as it always tries to enable/disable the CA independent of its type/state:

```
$ make testacc TEST=./google-beta TESTARGS='-run=TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample
=== PAUSE TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample
=== CONT  TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample
2021/08/06 23:23:26 [INFO] Authenticating using DefaultClient...
2021/08/06 23:23:26 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/08/06 23:23:26 [INFO] Authenticating using DefaultClient...
2021/08/06 23:23:26 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/08/06 23:23:26 [DEBUG] Waiting for state to become: [success]
2021/08/06 23:23:26 [INFO] Terraform is using this identity: drebes@drebes.dev
2021/08/06 23:23:26 [DEBUG] Getting shared CA pool "static-ca-pool"
2021/08/06 23:23:26 [DEBUG] Waiting for state to become: [success]
2021/08/06 23:23:26 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/08/06 23:23:26 [DEBUG] Retry Transport: request attempt 0
2021/08/06 23:23:27 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/08/06 23:23:27 [DEBUG] Retry Transport: Returning after 1 attempts
    provider_test.go:276: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error waiting to enable CertificateAuthority: Error waiting for Enabling CertificateAuthority: Error code 9, message: Cannot perform Certificate Authority enablement, Certificate Authority is in state AWAITING_USER_ACTIVATION.
        
          on terraform_plugin_test.tf line 2, in resource "google_privateca_certificate_authority" "default":
           2: resource "google_privateca_certificate_authority" "default" {
        
        
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: Error waiting to disable CertificateAuthority: Error waiting for Disabling CertificateAuthority: Error code 9, message: Certificate authority is not enabled.
        
        
--- FAIL: TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample (18.29s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta	18.802s
FAIL
make: *** [testacc] Error 1
```
I've opened GoogleCloudPlatform/magic-modules#5055 to fix this, and get back to the previous pre-GA behavior of allowing the creation of the subordinate CA, but still requiring offline activation (as stated on the docs), which is acceptable by users since signing the CSR can be an offline process anyway.
