### ISSUE TITLE
Add support for Cloud Composer v2

### ISSUE THREAD

**Issue by gor-obr** [hashicorp/terraform-provider-google#9611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for creation of Cloud Composer v2 environments.

https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments

Composer v2 uses the same API version as Composer v1, and it is already possible to create v2 environments using Terraform. However, v2 introduces a number of new fields (and doesn't support some of the existing fields), so in order for Composer v2 to be fully supported in Terraform, these new fields should be added to Terraform.

### New or Affected Resource(s)

google_composer_environment

**Comment by gor-obr** [comment]
I wish to work on this item.

**Comment by rileykarson** [comment]
@c2thorn to investigate the changes required for this. We support the v1beta1 API in the `google-beta provider already, what's changed here?

**Comment by gor-obr** [comment]
A set of new fields will be introduced to the v1beta1 API. These fields will be Compser v2 only (there will be a check and if the image version is `composer-1.x.x-airflow-x-x-x`), and any of these fields have been set, the request will not be accepted. Some examples of the new fields are `workloads_config` and `environment_size`.

Additionally, some fields that are used in Composer v1 will be disallowed for Composer v2 image versions. Some examples are `node_count`, `machine_type` and `python_version`.

Unfortunately, Terraform doesn't support cross-field validation ("if image version is 1 and workload_config is present, report error"), so I'm trying to use `CustomizeDiff` function in order test these fields in plan stage.

**Comment by c2thorn** [comment]
So the main difference is a set of new fields from the API? Seems reasonable to add these.

> Unfortunately, Terraform doesn't support cross-field validation ("if image version is 1 and workload_config is present, report error"), so I'm trying to use `CustomizeDiff` function in order test these fields in plan stage.

I'm not sure we'd want this type of validation in Terraform because the provider will certainly lag behind the API, and the validation could cause issues if the API's conditions change.

**Comment by c2thorn** [comment]
@gor-obr do you know where we could find the list of new fields for v2? It isn't apparent to me looking through the `v1beta1` documentation
