### ISSUE TITLE
Creating a new google_iap_client off of the default OAuth brand

### ISSUE THREAD

**Issue by danesggen** [hashicorp/terraform-provider-google#9613]
Because the modification and deletion of OAuth brands (`google_iap_brand`) is not yet supported by the GCP API, I am unable to go the route of baking in the creation of a new brand in to my TF infra.

As a workaround, I'd like to leverage the default existing brand that is available in my project, which if I run

`gcloud alpha iap oauth-brands list`

gives me

`projects/123456789/brands/123456789`
(ids replaced)

Yet if I specify that as an input to the `brand` parameter for the `google_iap_client` resource, I get a "Precondition check failed", likely because according to the TF docs (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iap_client), the brand must be in the format:

`projects/{project_number}/brands/{brand_id}/identityAwareProxyClients/{client_id}`

This seems a bit crazy to me because the whole point of creating a new client within the brand is so I can obtain a new client_id in the first place.

So the question is, why is a client_id required here, and given the brand I currently have available to use does not have any existing clients associated with it, is there a way I can get this working?

Many thanks.

**Comment by slevenick** [comment]
Hm, have you tried setting `brand = projects/123456789/brands/123456789`? I would believe that the documentation is incorrect as what you are describing sounds totally correct

**Comment by slevenick** [comment]
Closing due to lack of response. Feel free to reopen or comment if this is still impacting you
