### ISSUE TITLE
Updating google_dns_record_set forces replacement of the resource instead of in-place update

### ISSUE THREAD

**Issue by hatzibod** [hashicorp/terraform-provider-google#9614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.7

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

```tf
resource "google_dns_record_set" "test" {
  name         = "test.example.com."
  type         = "A"
  ttl          = 300
  managed_zone = google_dns_managed_zone.global.name
  rrdatas = [
    "10.0.0.1",
    "10.0.0.2"
  ]
}
```

### Debug Output

Trace differences between version 3.63.0 and newer versions:

https://gist.github.com/hatzibod/0608b58b8fabd80bfbd7288f738ffc5d

### Expected Behavior

Updating rrdatas should be an in-place change.

### Actual Behavior

The resource is being deleted and a new one is being created.

### Steps to Reproduce

1. Create a resource. (`terraform apply`)
2. Then add/remove an IP
3. Run `terraform apply`

This change was introduced in 3.64.0.

**Comment by edwardmedia** [comment]
Related to https://github.com/hashicorp/terraform-provider-google/issues/9416. Add label of persist-bug

**Comment by Sytten** [comment]
Is it possible to get some priority on this bug, seems like there are a few issues related to that problem and it is known since may :/

**Comment by roaks3** [comment]
This was happening because `rrdatas` was set to ForceNew, but that behavior has since been reverted with https://github.com/GoogleCloudPlatform/magic-modules/pull/5191, and updates should now be happening in-place.
