### ISSUE TITLE
Option in google_project resource to NOT create a project Owner IAM policy for the project creator

### ISSUE THREAD

**Issue by bgmonroe** [hashicorp/terraform-provider-google#9621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The default behavior for both the GCP Cloud Console and the google_project resource is to create an initial IAM policy for the creator with Owner rights.  I'd like to request that there be an argument (boolean I suppose) that can override this behavior so that a project can be created without that IAM policy.  It's unneeded if cases where an automation-based service account is building the projects and its IAM policy is defined higher in the resource hierarchy (folder or org level).

I can't use the authoritative google_project_iam_policy or google_project_iam_binding resources for my use-cases and the google_project_iam_member resource can't remove IAM policies.

### New or Affected Resource(s)

google_project

### Potential Terraform Configuration

```tf
resource "google_project" "new_project" {
  name            = local.proj_name
  project_id      = local.proj_id
  folder_id       = local.folder_id

  default_owner_iam_policy = false
}
```

**Comment by bgmonroe** [comment]
TBH, I think this should be a boolean constraint Org Policy similar to compute.skipDefaultNetworkCreation but this seems like the path of least resistance.

**Comment by upodroid** [comment]
This a behavior of the Google API and can't be overriden.

**Comment by bgmonroe** [comment]
Yes, I assumed it was "baked in" to the API.  

As I said above, for my use-case, the service account has all the privileges it needs defined above the project.  Also, as  I mentioned above, I can't use `google_project_iam_binding` for my use-case.

It seems that a couple of the `google_project` resource arguments are secondary API calls (`billing_account` and `auto_create_network` anyway) so I would think that it would be easy-enough to subsequently call the IAM API to remove the policy after the project is created.

I don't see this as a big departure/deviation philosophically from the `auto_create_network` argument.

**Comment by rileykarson** [comment]
If support is added for something like this, we'd avoid baking it into the `google_project` resource. The problem with making followup API calls there is that any error returned by the provider during `Create` taints the resource, extremely-undesirably-so for projects. This _could be implemented_ similar to https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_default_service_accounts but we'd prefer not to do so clientside. An org policy or server-side field that controls the behaviour would be much more desirable.

In the meantime, you can probably use `lifecycle.ignore_changes` on the `members` field of `google_project_iam_binding` to effectively create a create-time-only binding setting, removing the assigned owner.

```
resource "google_project_iam_binding" "project" {
  project = "google_project.project_id.id"
  role    = "roles/owner"

  members = []

  lifecycle {
    ignore_changes = ["members"]
  }
}
```

**Comment by rileykarson** [comment]
Potentially resolved with https://github.com/hashicorp/terraform-provider-google/issues/11724 rather than a workaround as well

Other than a generic resource like that I think we want to avoid this kind of resource- we'd recommend an org policy (if one exists) instead.
