### ISSUE TITLE
google_service_account expects <project-id>, google_project output gives project/<project-id>

### ISSUE THREAD

**Issue by arivictor** [hashicorp/terraform-provider-google#9623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.0.3
+ provider registry.terraform.io/hashicorp/google v3.76.0
```

### Affected Resource(s)

* google_project
* google_service_account

> Potentially others that expect project ID to be a certain format that conflicts with what the project resource outputs.

### Terraform Configuration Files

```tf
resource "google_service_account" "service-account" {
  account_id = "example"
  project    = google_project. example.id # .id returns projects/xxxxx
}

resource "google_project" "example" {
  name       = "example"
  project_id = "example"
}
```

### Expected Behavior

I expect `google_service_account` to accept the output format of `.id` from `google_project`. Or I would expect `google_project`'s `.id` attribute to return just the project ID without any prepended text.

### Actual Behavior

`google_project`'s `.id` attribute returns the project ID with `projects/` prepended. This is not accepted by `google_service_account`. Terraform errors as the url is malformed:

```
<p>The requested URL <code>/v1/projects/projects/example/serviceAccounts?alt=json&amp;prettyPrint=false</code>
```
As you can see it prepends `projects/` to the input which already has `projects/<project-id>`.

**want**: /v1/projects/example/serviceAccounts
**got**: /v1/projects/projects/example/serviceAccounts

### Steps to Reproduce

1. Configure a project
```tf
resource "google_project" "example" {
  name       = "example"
  project_id = "example"
}
```
2. Configure a service account in that project
```tf
resource "google_service_account" "service-account" {
  account_id = "example"
  project    = google_project.example.id
}
```
3. Apply
```
terraform apply
```

### Important Factoids

1. Can use the projects `.number` attribute but this forces a replacement on `apply` and then eventually errors and causes a bug.
2.  Current workaround is using `replace(google_project.example.id, "projects/", "")`. Ideally `id` would be just `id`.

**Comment by edwardmedia** [comment]
@arivictor `id` is more a global identifier. Here is the [doc](https://cloud.google.com/apis/design/resource_names) that might be helpful to follow. There could be exceptions. 

Does below `name` or `project_id` work for you?

```tf
resource "google_service_account" "service-account" {
  account_id = "example"
  project    = google_project.example.name 
  # project    = google_project.example.project_id 
}
```

**Comment by edwardmedia** [comment]
@arivictor is this still an issue?

**Comment by edwardmedia** [comment]
@arivictor closing assuming this is no longer an issue
