### ISSUE TITLE
Database Migration Service (DMS)

### ISSUE THREAD

**Issue by Tensho** [hashicorp/terraform-provider-google#9624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

* https://cloud.google.com/database-migration
* https://cloud.google.com/database-migration/docs/apis

### New or Affected Resource(s)

* `google_dms_connection_profile`
* `google_dms_migration_job`

### Potential Terraform Configuration

```tf
resource google_dms_connection_profile source {
  type = "mysql"
  ...
}

resource google_dms_connection_profile destination {
  type = "cloudsql"
  ...
}

resource google_dms_migration_job test {
  source = google_dms_connection_profile.source.id
  destination = google_dms_connection_profile.destination.id
  ...
}
```

### References

* [DMS - APIs & references](https://cloud.google.com/database-migration/docs/apis)

**Comment by rileykarson** [comment]
@slevenick can you file a bug w/ the DCL for this?

**Comment by slevenick** [comment]
Filed b/194799691 b/194799516

**Comment by arpitgup** [comment]
Hi all,
Do we have any resources available for GCP Database migration service in Terraform?
Because the configuration you have used above:
resource google_dms_connection_profile source {
  type = "mysql"
  ...
}

Is not visible in hasicorp documentation

**Comment by jrab66** [comment]
Are theree any plans to have this on the roadmap?

**Comment by DrFaust92** [comment]
will take a look

**Comment by AlfatahB** [comment]
b/206740587

**Comment by rileykarson** [comment]
Partly done in https://github.com/GoogleCloudPlatform/magic-modules/pull/7447, adding `google_database_migration_service_connection_profile`. Leaving open for now, as https://cloud.google.com/database-migration/docs/reference/rest/v1/projects.locations.migrationJobs is unsupported. We're unsure if that's a great fit for Terraform as one-off jobs have never worked super great.

**Comment by rileykarson** [comment]
Note: some followup work on the existing resource is tracked in https://github.com/hashicorp/terraform-provider-google/issues/15647

**Comment by krmozejko** [comment]
I have problem with `google_database_migration_service_connection_profile` resource. When I define these resource with `alloydb` block to create target cluster for migration nothing is being added to terraform state - neither connection profile nor cluster itself. As a result each time I run `terraform apply` it attempts to create cluster and fails, because it already exists. Is there a way to workaround this?

**Comment by melinath** [comment]
After discussing this with the DMS team, it's not clear that migrationJobs would make sense in Terraform, since it is a more imperative API resource. If anyone reading this feels that they need support for migrationJobs, please open a new ticket detailing the use case and the desired behavior.

**Comment by Tensho** [comment]
Don't 62 likes under the issue description mean it's something people think is valuable? 🙂 

My use case is the next – we serve many clients with a dedicated infrastructure stack for each one, including distinguished database instances. I'd appreciate describing the database migration configuration once as Terraform module, peer-reviewing it with my colleagues and calling it for each client with respective parameters. I had multiple iterations (one of which resulted in a dump profile feature DMS team released recently) to make DMS finally work for our scale and it would be so much easier to do those iterations via the code rather than manually managing the job.

I understand the DMS job is imperative by its nature, but as far as API endpoint exists for it, DMS team has designed to work with job resource programmatically, right? Terraform provider is just another client for it.

**Comment by rileykarson** [comment]
@melinath can you share that discussion with me?

**Comment by melinath** [comment]
@Tensho thanks for expanding on the use case you have for the migration job! It's definitely clear that people are interested in DMS; however, it's possible that most use cases are covered by connection profile support. Getting more information about use cases for the migration job is definitely useful though, appreciate it!

**Comment by melinath** [comment]
Talked this over with @rileykarson; we're splitting the discussion of the job resource into a separate ticket to collect feedback specifically about that resource, and are considering this ticket resolved for now due to the implementation of connection profile support in https://github.com/GoogleCloudPlatform/magic-modules/pull/7447. Thank you again for raising this issue!
