### ISSUE TITLE
Error, attempting to list users associated with instance abstracta-repo-cec1f008: googleapi: Error 403: The client is not authorized to make this request., notAuthorized

### ISSUE THREAD

**Issue by VikramVasudevan** [hashicorp/terraform-provider-google#9628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.76.0
+ provider registry.terraform.io/hashicorp/google-beta v3.76.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
data "google_project" "project" {
  provider = google-beta
}

data "google_client_config" "myconfig" {
  provider = google-beta
}

resource "random_id" "suffix" {
  count = 1

  byte_length = 4
}

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "_%@"
}

resource "google_sql_database_instance" "master" {
  name             = "master-instance-${random_id.suffix[0].hex}"
  database_version = "SQLSERVER_2017_STANDARD"
  region           = data.google_client_config.myconfig.region
  project = data.google_project.project.number
  root_password    = random_password.password.result
  deletion_protection = false

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-custom-2-3840"
  }
}
```

### Debug Output

Refer to this issue  [https://github.com/hashicorp/terraform-provider-google/issues/685](url)

### Panic Output

```
Error: Error, attempting to list users associated with instance master-instance-1e474e58: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
│
│   with google_sql_database_instance.master,
│   on main.tf line 28, in resource "google_sql_database_instance" "master":
│   28: resource "google_sql_database_instance" "master" {
│
```

### Expected Behavior

Resources should be created without errors.

### Actual Behavior

Received error

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-google/issues/685
https://stackoverflow.com/questions/62332850/why-cant-terraform-list-sql-users-in-gcp-account/68510717#68510717
https://stackoverflow.com/questions/68524391/error-attempting-to-list-users-associated-with-instance-googleapi-error-403-t

**Comment by VikramVasudevan** [comment]
Ok this is going to be a bit of a surprise. I think there is some regional dependency here ..
I dont get this error when I use region asia-south1 and zone asia-south1-a
I do get this error when I use region asia-southeast1 and zone asia-southeast1-a

Am I missing something?

**Comment by VikramVasudevan** [comment]
Another user had reported similar issue ... 

[https://stackoverflow.com/questions/62332850/why-cant-terraform-list-sql-users-in-gcp-account](url)

Looks like the root cause is the following request that fails with 404 Not Found
```
GET /sql/v1beta4/projects/myprojectid/instances/myinstance-e6c95cca?alt=json&prettyPrint=false HTTP/1.1
```

Any clues on this one?

**Comment by VikramVasudevan** [comment]
OK this is a showstopper for us to continue using terraform ... if we cant get this resolved soon...  The striking thing about this issue is its inconsistency. It failed in my local windows machine, later it worked, then it failed in ubuntu consistently. I cant seem to draw a pattern here ... Clearly, terraform is unable to find the resource immediately after it gets created (possibly a delay is required ?) .

The resource also seems to be unaffected by subsequent "terraform destroy"s and is always there unless I go and remove it from the console manually.

**Comment by VikramVasudevan** [comment]
Just wanted to leave an update here for others who stumble across this issue. I decided to try out Pulumi for this use case and I have not seen this issue happening there ..  so far it has been good going with Pulumi and if all goes well, I might make the switch soon.

I have to say that I am very disappointed by the support I have received from terraform.

**Comment by edwardmedia** [comment]
@VikramVasudevan sorry for the delayed response. Using your config, it is fine with me for the regions that did not work for you. You were receiving the `error 403` from API. Have you checked the Terraform executor to see if it has permission to those regions?  

```tf
resource "random_id" "suffix" {
  count = 1
  byte_length = 4
}

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "_%@"
}

resource "google_sql_database_instance" "master" {
  name             = "master-instance-issue9628"
  database_version = "SQLSERVER_2017_STANDARD"
  region           = "asia-southeast1"
  //project = data.google_project.project.number
  root_password    = random_password.password.result
  deletion_protection = false

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-custom-2-3840"
  }
}
```

**Comment by edwardmedia** [comment]
@VikramVasudevan is [that](https://github.com/hashicorp/terraform-provider-google/issues/9628#issuecomment-892893483) helpful? Is this still an issue?

**Comment by edwardmedia** [comment]
Closing this assuming it is no longer an issue
