### ISSUE TITLE
Not able to set data source in a list parameter in biiling_budget

### ISSUE THREAD

**Issue by sowmiya-ragu** [hashicorp/terraform-provider-google#9633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.76.0
+ provider registry.terraform.io/hashicorp/google-beta v3.76.0

### Affected Resource(s)

* google_billing_budget

### Terraform Configuration Files

```tf
I'm trying to access the project_id from another resource and setting in budget_filter , projects variable. As it is of list type , it takes the data value as null:

data "google_projects" "my-org-projects" {
  filter = "parent.id:<id> labels.business-unit:unitname"
}
locals {
    project_count = length(data.google_projects.my-org-projects.projects)
}

data "google_project" "project" {
  count = local.project_count
  project_id = data.google_projects.my-org-projects.projects[count.index].project_id
}

resource "google_billing_budget" "budget" {
  count = local.project_count
  billing_account = "00837C-63BBD1-ECBE56"
  display_name    = "${data.google_project.project[count.index].project_id}"
  budget_filter {
   **projects = ["${data.google_project.project[count.index].id}"]**
    // This throws error "Null values are not allowed for this attribute value" 
  }
  amount {
    specified_amount {
      currency_code = "USD"
      units         = "90"
    }
  }
  threshold_rules {
    threshold_percent = 0.8
}

```
How do I access the project id and set it in
budget_filter
{
projects = [""]
}
### Debug Output
Error: Null value found in list

  on label.tf line 58, in resource "google_billing_budget" "budget":
  58:    projects = ["${data.google_project.project[count.index].id}"]

Null values are not allowed for this attribute value.

**Error: Null value found in list**

  on label.tf line 58, in resource "google_billing_budget" "budget":
  58:    projects = ["${data.google_project.project[count.index].id}"]

**Null values are not allowed for this attribute value.**

### Expected Behavior
Create budget alert and by setting project id in the budget_filter.

**Comment by edwardmedia** [comment]
@sowmiya-ragu this appears to be an issue about how to properly use the dynamic code vs an issue with the plugin. You may want to debug to see if the list is null. Below error seems clear. What do you see if you hard-coded the resources?

> Error: Null value found in list

**Comment by sowmiya-ragu** [comment]
If it is hardcoded , it works.
But the same data resource is accessed in google_billing_budget's 
_display_name =  "${data.google_project.project[count.index].project_id}"_
and it works.
But not in budget_filter. I suspect because the  "projects" type is list.

**Comment by edwardmedia** [comment]
@sowmiya-ragu `projects` below is defined as a `set` and it expects a list of projects. You have found the reason. Closing the issue then

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#projects

**Comment by sowmiya-ragu** [comment]
Edward , 

What is the solution for this ?

**Comment by sowmiya-ragu** [comment]
Used the below snippet and it worked.
projects = ["projects/${data.google_projects.my-org-projects.projects[count.index].project_id}"]
