### ISSUE TITLE
Error patching google_compute_router and google_compute_router_interface

### ISSUE THREAD

**Issue by dps3ven** [hashicorp/terraform-provider-google#9638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.7
google provider 3.76.0

### Affected Resource(s)

- google_compute_router
- google_compute_router_interface
- google_compute_router_peer

### Terraform Configuration Files

```tf
provider "google" {
  region  = "us-east1"
  zone    = "us-east1-b"
}

resource "google_compute_router" "router" {
  bgp {
    asn            = 65001
    advertise_mode = "DEFAULT"
  }
  name        = "test-router"
  network     = google_compute_network.vpc.id
}

resource "google_compute_network" "vpc" {
  auto_create_subnetworks         = false
  delete_default_routes_on_create = true
  name                            = "test-network"
  routing_mode                    = "REGIONAL"

}

resource "google_compute_router_interface" "interface_one" {
  ip_range   = "169.254.201.234/30"
  name       = "interface-1"
  router     = google_compute_router.router.name
}

resource "google_compute_router_peer" "peer_one" {
  advertised_route_priority = 100
  interface                 = google_compute_router_interface.interface_one.name
  name                      = "peer-1"
  router                    = google_compute_router.router.name
  peer_asn                  = 64512
  peer_ip_address           = "169.254.201.233"
}

# resource "google_compute_router_interface" "interface_one" {
#   ip_range   = "169.254.242.158/30"
#   name       = "interface-1"
#   router     = google_compute_router.router.name
# }

# resource "google_compute_router_peer" "peer_one" {
#   advertised_route_priority = 100
#   interface                 = google_compute_router_interface.interface_one.name
#   name                      = "peer-1"
#   router                    = google_compute_router.router.name
#   peer_asn                  = 64512
#   peer_ip_address           = "169.254.242.157"
# }
```

### Debug Output

https://gist.github.com/dps3ven/4e5f41db669889fdebea115afb0c859c

### Panic Output

none

### Expected Behavior

Apply complete! Resources: 4 added, 0 changed, 4 destroyed.

### Actual Behavior

Error: Error patching router us-east1/test-router: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[0].ipAddress': ''. BGP Peer "peer-1" has IP address 169.254.201.234 different from interface IP address 169.254.242.158, invalid

### Steps to Reproduce

1. terraform apply
2. comment out the first google_compute_router_interface and google_compute_router_peer resources
3. uncomment out the second google_compute_router_interface and google_compute_router_peer resources
4. terraform plan
5. terraform apply

## GCP REST API results after initial apply
```tf
{
  "bgp": {
    "keepaliveInterval": 20.0,
    "asn": 65001.0,
    "advertiseMode": "DEFAULT"
  },
  "bgpPeers": [
    {
      "name": "peer-1",
      "interfaceName": "interface-1",
      "peerIpAddress": "169.254.201.233",
      "advertisedRoutePriority": 100.0,
      "peerAsn": 64512.0,
      "advertiseMode": "DEFAULT",
      "enable": "TRUE",
      "ipAddress": "169.254.201.234"
    }
  ],
  "creationTimestamp": "2021-07-23T14:06:32.407-07:00",
  "id": "4550322857495138743",
  "interfaces": [
    {
      "name": "interface-1",
      "ipRange": "169.254.201.234/30"
    }
  ],
  "kind": "compute#router",
  "name": "test-router",
  "network": "projects/well-sandbox/global/networks/test-network",
  "region": "projects/well-sandbox/regions/us-east1",
  "selfLink": "projects/well-sandbox/regions/us-east1/routers/test-router"
}
```

## GCP REST API results are identical after second apply and destruction complete message:

"google_compute_router_interface.interface_one: Destruction complete after 12s"

But it seems that the cloud router interface is not actually deleted and is preventing a reapply with new IP addresses

```
### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

**Comment by slevenick** [comment]
Huh.... This feels like a dependency problem.

The example you've provided triggers a recreation on the interface, which *should* trigger a recreation on the peer. I believe it is not correctly recreating because of some HCL limitations, and because it sticks around it prevents the creation of the new interface. Here is the bug against the Terraform SDK that describes this: https://github.com/hashicorp/terraform-plugin-sdk/issues/122

I'm able to solve this by using `google_compute_router_interface.interface_one.id` instead of `google_compute_router_interface.interface_one.name` as the dependency in the peer. This requires some function calls, but correctly causes the peer to recreate when the interface recreates. This works because `id` is a computed field, which can only be used *after* the interface exists, and deleting the interface makes it unknowable, so the peer must be deleted when the interface is deleted.

```
resource "google_compute_router_peer" "peer_one" {
  advertised_route_priority = 100
  interface                 = element(split("/", google_compute_router_interface.interface_one.id), length(split("/", google_compute_router_interface.interface_one.id))-1)
...
```

Unfortunately we cannot fix this in the provider itself, so I'll close it out
