### ISSUE TITLE
Merge terraform.yaml files into api.yaml

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Issue Description

Magic Modules supports generating a variety of downstream libraries. For each product, there is a generic api.yaml file specifying the API as a whole, and then a downstream-specific override (inspec.yaml, ansible.yaml, terraform.yaml) to handle anything specific to that downstream. However, following https://github.com/hashicorp/terraform-provider-google/issues/9588, terraform providers and terraform validator will be the only downstreams, which means that we will be able to merge the api.yaml and terraform.yaml files.

This will lower cognitive load around remembering which things go in which place, and simplify learning how to use mmv1 and maintaining it.

Ideally we'd want to split this up into several stages to simplify review. For example:

1. Add support to api.yaml parsing for all fields supported by terraform.yaml parsing.
2. Allow terraform.yaml to be left out.
3. Write a script to merge api.yaml and terraform.yaml
4. Test the script on a single product a few times & have individual PRs for each of those
5. Run the script on all remaining products
6. Remove any ruby code related to terraform.yaml support

**Comment by rileykarson** [comment]
@c2thorn
