### ISSUE TITLE
Extract test run data from TeamCity builds for MM PR builds

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9640]
Currently we don't have a lot of insight into our test reliability for PRs over time, and it's not in a centralized location. At a minimum, we should extract VCR test run time & total test count. This could be done with Apps Script.

Depends on https://github.com/hashicorp/terraform-provider-google/issues/9589 for completion.

**Comment by rileykarson** [comment]
I think we do this.
