### ISSUE TITLE
Extract test run data from TeamCity builds for nightly builds

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9641]
Currently we don't have a lot of insight into our nightly build test reliability over time, and it's not in a centralized location.

At a minimum, we should extract:

- test run duration
- total test count
- \# of new test failures
- \# of total test failures
- \# of test failures TeamCity thinks are flakey
- \# of test successes TeamCity thinks are flakey

This could be done with Apps Script.

Depends on https://github.com/hashicorp/terraform-provider-google/issues/9589 for completion.

**Comment by c2thorn** [comment]
Created an appscript that triggers daily to read the latest TC nightly runs. Couldn't find a straightforward way to dump the data into a DB for the dashboard, so currently writing to Sheets.

**Comment by rileykarson** [comment]
We collect most of these.
