### ISSUE TITLE
Extract MM build data from Cloudrun 

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9642]
Currently we don't have a lot of insight into our build reliability over time, and it's not in a centralized location. At a minimum, we should extract:

- Build duration (broken down by build step)
- Build step success or failure

This could maybe be done with Apps Script? Or some other way.

Depends on https://github.com/hashicorp/terraform-provider-google/issues/9589 for completion.

**Comment by rileykarson** [comment]
We collect these #s.
