### ISSUE TITLE
config_connector dependency in google_container_cluster

### ISSUE THREAD

**Issue by baldey-nz** [hashicorp/terraform-provider-google#9648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/google v3.77.0
+ provider registry.terraform.io/hashicorp/google-beta v3.77.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf

provider "google-beta" {
  project = var.gcp_project_id
  region  = var.gcp_default_region
}

resource "google_container_cluster" "prv_cluster" {
  #Beta provider for the shielded nodes
  provider                    = google-beta
  count                       = var.enable_cluster ? 1 : 0
  name                        = var.prv_cluster_name
  location                    = var.region
  remove_default_node_pool    = true
  initial_node_count          = 1
  monitoring_service          = var.monitoring_service
  logging_service             = var.logging_service
  enable_binary_authorization = var.binary_authorization
  enable_shielded_nodes       = var.shielded_nodes

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = var.private_cluster ? var.private_cluster : null
    master_ipv4_cidr_block  = var.private_cluster ? var.mst_ip_cidr_range : null
  }


  node_locations = [
    "us-central1-a",
    "us-central1-c",
    "us-central1-f",
  ]


  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  maintenance_policy {
    recurring_window {
      start_time = "2019-11-18T17:59:00.00Z"
      end_time   = "2019-11-18T23:59:00.00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=MO,TU,SU"
    }
  }

  master_authorized_networks_config {
    dynamic "cidr_blocks" {
      for_each = [for b in var.master_access_cidrs : {
        cidr_block   = b.cidr_block
        display_name = b.display_name
      }]

      content {
        cidr_block   = cidr_blocks.value.cidr_block
        display_name = cidr_blocks.value.display_name

      }
    }
  }

  network            = var.network_name
  subnetwork         = var.node_subnetwork
  min_master_version = var.min_master_version

  ip_allocation_policy {
    cluster_secondary_range_name  = "cluster"
    services_secondary_range_name = "service"
  }

  network_policy {
    enabled = true
  }

  pod_security_policy_config {
    enabled = var.psp_enabled
  }

  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }  

  // Configure various addons
  addons_config {
    // Enable network policy (Calico)
    network_policy_config {
      disabled = false
    }
    // Enable config connector
    config_connector_config {
      enabled = true    
    }
}

  lifecycle {
    ignore_changes = [
      initial_node_count,
      network_policy,
      node_config,
      node_pool,
    ]
    create_before_destroy = true
  }

    depends_on = [var.project]
}
```

### Debug Output

https://gist.github.com/baldey-nz/eac76e38a5a5b69b8b9928104761a4af#file-out-log

### Expected Behavior
If both workload_identity_config and config_connector_config are enabled in the initial cluster definition then terraform should create the workload_identity_config first to satisfy the dependency that config_connector_config has on it.

### Actual Behavior

googleapi: Error 400: Workload identity must be enabled for ConfigConnector addon., badRequest

### Steps to Reproduce
1. configure a cluster with both:
```tf
  addons_config {
    // Enable config connector
    config_connector_config {
      enabled = true    
    }
}
```
and
```tf
  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }  

``` 
defined

2. `terraform apply`

### Important Factoids

None 

### References

* #0000

**Comment by edwardmedia** [comment]
@baldey-nz how did you enable `workload_identity_config`? From the log you provided, I don't see it. What value is it from your config (below)? I guess you notice the following limitation. It is fine with the below config. Can you try to see if it works for you?

>  "${var.project}.svc.id.goog"

> identity_namespace (Required) - Currently, the only supported identity namespace is the project's default.

```tf
resource "google_container_cluster" "primary" {
  provider          = google-beta
  name               = "issue9648"
  location           = "us-central1-a"
  initial_node_count = 3
  node_config {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    labels = {
      foo = "bar"
    }
    tags = ["foo", "bar"]
  }
  timeouts {
    create = "30m"
    update = "40m"
  }

  workload_identity_config {
    identity_namespace = "${data.google_project.project.project_id}.svc.id.goog"
  }  

  // Configure various addons
  addons_config {
    // Enable network policy (Calico)
    network_policy_config {
      disabled = false
    }
    // Enable config connector
    config_connector_config {
      enabled = true    
    }
  }

}
```

**Comment by baldey-nz** [comment]
@edwardmedia thanks for looking at this. Im not sure why the value was not shown in the logging that i posted but its the project id passed in as a variable

```tf
  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }  
```
in my config the above definitely works because if i remove the config_connector syntax from my config:

```tf
    config_connector_config {
      enabled = true    
    }
```

then the terraform runs successfully and my cluster has the workload identity feature enabled. It only fails when i run with both workload_identity_config and config_connector_config enabled at the same time. If i do identity workload first then config_connector in a subsequent terraform apply it works. Please note that im running this against an existing cluster that doesnt have either workload identity or config connector enabled (not sure if this would make a difference).

I have tried your suggestion by adding
```tf
data "google_project" "project" {}
```
and using
```tf
  workload_identity_config {
    identity_namespace = "${data.google_project.project.project_id}.svc.id.goog"
  }  
```
but i get the same error when running :
Error: googleapi: Error 400: Workload identity must be enabled for ConfigConnector addon., badRequest

**Comment by edwardmedia** [comment]
@baldey-nz you may share the full debug log so I can take a close look. Also can you try the [config](https://github.com/hashicorp/terraform-provider-google/issues/9648#issuecomment-888508441) I provided to see if that works for you?

**Comment by baldey-nz** [comment]
sorry maybe i wasnt clear in my response but i have run the config that you provided and i got the same error. i will run again shortly and provide the debug output

**Comment by baldey-nz** [comment]
i have narrowed this down a bit further.

1) your config used directly to create a new cluster works - we get a cluster with both workload identity and config connector enabled. no problems
2) this is only a problem for existing clusters .To reproduce - If i remove the workload identity from your config e.g:
```tf
resource "google_container_cluster" "primary" {
  provider          = google-beta
  name               = "issue9648"
  location           = "us-central1-a"
  project            = "my-project"
  initial_node_count = 1
  node_config {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    labels = {
      foo = "bar"
    }
    tags = ["foo", "bar"]
  }
  timeouts {
    create = "30m"
    update = "40m"
  }

  // Configure various addons
  addons_config {
    // Enable network policy (Calico)
    network_policy_config {
      disabled = false
    }
  }
}
```
and create a cluster i get a cluster without workload identity and config connector enabled. Then if i try and add these to that config and run again. e.g:
```tf
resource "google_container_cluster" "primary" {
  provider          = google-beta
  name               = "issue9648"
  location           = "us-central1-a"
  project            = "my-project"
  initial_node_count = 1
  node_config {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    labels = {
      foo = "bar"
    }
    tags = ["foo", "bar"]
  }
  timeouts {
    create = "30m"
    update = "40m"
  }

  workload_identity_config {
    identity_namespace = "my-project.svc.id.goog"
  }  

  // Configure various addons
  addons_config {
    // Enable network policy (Calico)
    network_policy_config {
      disabled = false
    }
    // Enable config connector
    config_connector_config {
      enabled = true    
    }
  }
}
```
i get the Error: googleapi: Error 400: Workload identity must be enabled for ConfigConnector addon., badRequest error.

gist for the debug output of the second run can be seen [here](https://gist.githubusercontent.com/baldey-nz/0f86669da3ec538d7c08fd4e8f085dfd/raw/a13b3c8dd03edb81963fa25fbbb7fb8da2615cac/gist.log)

**Comment by edwardmedia** [comment]
@baldey-nz I see what happened in your case. API does require the application of these two attributes (`workload_identity_config` and `config_connector_config`) in certain order when they are added in the same change. I am not sure if Terraform can force the sequence. For the workaround, you could first add `workload_identity_config` and then `config_connector_config` with two applies.

**Comment by baldey-nz** [comment]
thanks @edwardmedia . I guess it would be good if this could be documented somewhere so others dont fall into the same trap
