### ISSUE TITLE
Remove shortname in doc from resource_policies on google_compute_instance

### ISSUE THREAD

**Issue by menzbua** [hashicorp/terraform-provider-google#9651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/google-beta v3.74.0

### Affected Resource(s)

* google_compute_resource_policy
* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "vm01" {
  boot_disk {
    auto_delete  = false

    initialize_params {
      size  = 512
      type  = "pd-ssd"
      image = "ubuntu-2004-focal-v20210610"
    }
  }

  name                      = "dev01"
  description               = "terraform managed"
  machine_type              = "f1-micro"
  zone                      = "europe-west3-a"
  can_ip_forward            = false
  deletion_protection       = false
  allow_stopping_for_update = false
  project                   = "test-project01"
  resource_policies = ["resource-policy01"]

  network_interface {
    subnetwork = google_compute_subnetwork.test-net01.id

    access_config {
    }
  }

  scheduling {
    preemptible         = false
    automatic_restart   = false
  }

}
resource "google_compute_resource_policy" "respol01" {
  name        = "resource-policy01"
  region      = "europe-west3"
  project     = "test-project01"
  description = "terraform managed"
  instance_schedule_policy {
    vm_start_schedule {
      schedule = "0 7 * * *"
    }

    time_zone = "Europe/Berlin"
  }
}
```

### Debug Output

```
╷
│ Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.resourcePolicies[0]': 'respol01'. The URL is malformed., invalid
│
│   with google_compute_instance.vm01,
│   on main.tf line 20, in resource "google_compute_instance" "vm01":
│   20: resource "google_compute_instance" "abh1ad" {
│
╵

```

### Expected Behavior

It is documented that the `resource_policies` can be "A list of **short names** or **self_links**". I'm using a short name of a resource policy to bind that policy to a vm. I expect that the policy would bound to the vm.

### Actual Behavior

But when i use the short name of a resource policy i got an error from the googleapi.

### Steps to Reproduce

Use the short name of a resource policy not the self_link in a resource policy binding of a vm and the error occurs.

**Comment by edwardmedia** [comment]
@menzbua looks like it does not take the `shortname`. Can you confirm if the `self_link` works for you?

**Comment by menzbua** [comment]
@edwardmedia Yes, `self_link` is working. Only `shortname` does not.

**Comment by edwardmedia** [comment]
Updating the doc to remove the shortname is good?

**Comment by menzbua** [comment]
Hmm, for me it would be better when i can use the shortname, too.

**Comment by edwardmedia** [comment]
Using reference is generally better as it enforces the sequence (dependency) when the resources are built.

**Comment by menzbua** [comment]
For my script it would be easier to access the shortname. But when it is not possible to implement the access to the short name i have to modify my script.

**Comment by melinath** [comment]
b/241976514
