### ISSUE TITLE
terraform apply uses different source_machine_image when creating instance from cross project machine image

### ISSUE THREAD

**Issue by MuriukiPM** [hashicorp/terraform-provider-google#9653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.77.0
+ provider registry.terraform.io/hashicorp/google-beta v3.77.0

### Affected Resource(s)

* google_compute_instance_from_machine_image

### Terraform Configuration Files

`main.tf`
```tf
terraform {
  required_version = ">= 0.13"
  backend "gcs" {}
}

provider "google" {
  project = var.project_id
}

provider "google-beta" {
  project = var.project_id
}
```

`data.tf`
```tf
data "google_compute_default_service_account" "default" {
}
```

`variables.tf`
```tf
variable "project_id" {}
variable "machine_project_id" {}
variable "machine_src_image_name" {}

```

`gce-test.tf`
```tf
resource "google_compute_instance_from_machine_image" "test" {
  provider = google-beta
  name     = "test"
  zone     = "us-central1-a"

  source_machine_image = "projects/${var.machine_project_id}/global/machineImages/${var.machine_src_image_name}"

  // Override fields from machine image
  can_ip_forward = false
  
  service_account {
    email = data.google_compute_default_service_account.default.email
    scopes = ["service-management", "service-control", "storage-ro", "logging-write", "monitoring-write"]
  }
  
  network_interface {
    network = "default"
    subnetwork = "default"
    access_config {}
  }
}
```

### Debug Output

https://gist.github.com/MuriukiPM/e37814fdaa1bf0d0e9df3ea13612f4d9

### Expected Behavior

Output of `terraform plan` shown below should have been applied.
https://gist.github.com/MuriukiPM/2326093c26731b77fcd094cce582c739

### Actual Behavior

Terraform attempts to query source machine image using the wrong link : link has the wrong project id compared to the one generated in the plan. Seems to be overwritten at some point, replaced with the provider project id.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- authenticating to GCP via application default credentials for user.

### References

1. https://cloud.google.com/compute/docs/machine-images/create-instance-from-machine-image#create-instance-from-different-project

**Comment by edwardmedia** [comment]
@MuriukiPM the error seems clear. Can you verify if the image exists or your account has permission to access it?

> Error 404: The resource 'projects/my-new-instance-project-id/global/machineImages/test-image' was not found, notFound

**Comment by MuriukiPM** [comment]
@edwardmedia yes, the image exists. The account used by terraform to authenticate has access as well. I was able to run the corresponding gcloud sdk command to create the instance from the image.

**Comment by edwardmedia** [comment]
@MuriukiPM can you post the debug for the gcloud command execution?

**Comment by MuriukiPM** [comment]
HI @edwardmedia See below the command and the debug log in a gist
```sh
gcloud beta compute instances create test \
 --project=my-new-instance-project-id \
 --zone us-central1-a \
 --verbosity debug \
 --source-machine-image projects/my_machine_image_project_id/global/machineImages/test-image \
 --service-account 123456789000-compute@developer.gserviceaccount.com \
 --scopes=service-management,service-control,storage-ro,logging-write,monitoring-write
```

Debug log
https://gist.github.com/MuriukiPM/d5c4f7ba2e1b37bf562b1264f1ea65c9

**Comment by edwardmedia** [comment]
@MuriukiPM can you post the log for below command instead?  

```
gcloud beta compute instances create test \
 --project=my-new-instance-project-id \
 --zone us-central1-a \
 --verbosity debug \
 --source-machine-image projects/my_machine_image_project_id/global/machineImages/test-image \
 --service-account 123456789000-compute@developer.gserviceaccount.com \
 --scopes=service-management,service-control,storage-ro,logging-write,monitoring-write \
 --log-http
```

**Comment by vFawzi** [comment]
I can confirm that I see same issue, worked from gcloud but in terraform it did not work, Terraform replace the  PROJECT-ID  (the project that have the machine image) variable in : ( source_machine_image = "projects/PROJECT-ID/global/machineImages/NAME" )

this variable get replaced during execution with PROJECT-ID= the project where new instance should be created , then you get error since the machine image does not exist in this project

Error 404: The resource 'projects/**terraform-test-createinstance-project/**global/machineImages/test' was not found, notFound

**Comment by edwardmedia** [comment]
I see now what the problem is.

**Comment by vFawzi** [comment]
do we have any updates for this issue ?
