### ISSUE TITLE
GCE_VM_IP endpoint type support as a backend for TCP/IP Internal LB. as of now it supports only GCE_VM_IP_PORT

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-google#9654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCE_VM_IP endpoint type support as a backend for TCP/IP Internal LB. as of now it supports only GCE_VM_IP_PORT

### New or Affected Resource(s)

* google_compute_network_endpoint_group resource should support network_endpoint_type = "GCE_VM_IP" for TCP/IP ILB

### Potential Terraform Configuration

resource "google_compute_network_endpoint_group" "neg" {
  name                  = var.endpoint_group_name
  project               = var.project_id
  network               = var.network
  subnetwork            = var.subnet
  default_port          = var.compute_health_check_port
  network_endpoint_type = "GCE_VM_IP"
  zone                  = var.zone
}

resource "google_compute_network_endpoint" "test-neg" {
  project                = var.project_id
  network_endpoint_group = var.endpoint_group_name
  for_each               = { for endpoint in var.endpoints : endpoint.instance => endpoint }
  instance               = each.value.instance
  port                   = each.value.port
  ip_address             = each.value.ip_address
  zone                   = var.zone
}

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

https://cloud.google.com/load-balancing/docs/negs/zonal-neg-concepts

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6182/files
