### ISSUE TITLE
panic when importing secret gives wrong template

### ISSUE THREAD

**Issue by steveoh** [hashicorp/terraform-provider-google#9666]
### Affected Resource(s)

* google_secret_manager_secret_version

provides template `projects/{{project}}/secrets/{{secret}}/versions{{version}}`

should be `projects/{{project}}/secrets/{{secret}}/versions/{{version}}` with a slash

Also the docs on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version show the import as `terraform import google_secret_manager_secret_version.default {{name}}/{{name}}`

when it is `terraform import google_secret_manager_secret_version.default projects/{{project}}/secrets/{{secret}}/versions/{{version}}`

**Comment by edwardmedia** [comment]
@steveoh can you share your config and its debug log? Thanks

**Comment by steveoh** [comment]
I have a google-beta provider

I was trying to import a secret like this

```
resource "google_secret_manager_secret" "default" {
  secret_id = "secret"
  project   = module.gcp_project.project_id

  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
      replicas {
        location = "us-west3"
      }
    }
  }
}

resource "google_secret_manager_secret_version" "default" {
  secret = google_secret_manager_secret.default.id

  secret_data = file("${path.module}/secret.json")
}
```
I followed the docs on the page linked above and ran

```
terraform import google_secret_manager_secret_version.default {{name}}/{{name}}
```

and I was prompted with another incorrect template to import the secret.

Yes they are both doc issues but one is docs coming out of the CLI.

**Comment by rileykarson** [comment]
Regardless of documentation status, we should not have a panic no matter what- triaged back to bug
