### ISSUE TITLE
google_scc_notification_config - 400 invalid argument error

### ISSUE THREAD

**Issue by ericyz** [hashicorp/terraform-provider-google#9670]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.77.0
+ provider registry.terraform.io/hashicorp/google-beta v3.77.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_scc_notification_config" "scc_notification_config" {
  config_id    = var.scc_notification_name
  organization = var.org_id
  description  = "SCC Notification for all active findings"
  pubsub_topic = google_pubsub_topic.scc_notification_topic.id

  streaming_config {
    filter =  "state = \"ACTIVE\""
  }
}


```

### Debug Output

https://gist.github.com/ericyz/755a3687ecad99ba8b3625f78feaf3d3

### Expected Behavior

200 status
### Actual Behavior

400 status for  "state = \"ACTIVE\"", but 200 status for "category = \"OPEN_FIREWALL\" AND state = \"ACTIVE\""

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
Below gcloud command example from  the [tutorial](https://cloud.google.com/security-command-center/docs/how-to-enable-real-time-notifications) is failing too. I guess API is experiencing an issue. 

```
 gcloud scc notifications create scc-critical-and-high-severity-findings-notify \
   --pubsub-topic $TOPIC \
   --organization $ORG_ID \
   --filter "(severity=\"HIGH\" OR severity=\"CRITICAL\") AND state=\"ACTIVE\""
```

**Comment by bharathkkb** [comment]
@ericyz @edwardmedia maybe related to 191703221

**Comment by Erouan50** [comment]
@ericyz I have different behavior. The creation works properly, like for example the following resource worked for me:

```hcl
resource "google_scc_notification_config" "scc_notification_config" {
  config_id = "scc-critical-and-high-severity-findings-notify"
  organization = data.google_organization.current.org_id
  description = "Custom config to send notification when critical finding are found"
  pubsub_topic = google_pubsub_topic. scc_notification_topic.id

  streaming_config {
    filter = "severity=\"CRITICAL\" AND state=\"ACTIVE\""
  }
```

However, if update the filter with this value for example `filter = "state=\"ACTIVE\""`, I got the following error:

```hcl
Error: Error updating NotificationConfig "organizations/************/notificationConfigs/scc-critical-and-high-severity-findings-notify": googleapi: Error 400: Request contains an invalid argument.

  on modules/event-thread-detector-notification/pubsub.tf line 1, in resource "google_scc_notification_config" "scc_notification_config":
   1: resource "google_scc_notification_config" "scc_notification_config" {

```

I this there is an issue during the update but not during the creation.
