### ISSUE TITLE
Attribute documentation for google_privateca_ca_pool is out of date

### ISSUE THREAD

**Issue by switj** [hashicorp/terraform-provider-google#9673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

google_privateca_ca_pool

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_ca_pool#id

### Expected Behavior

The actual attributes are:
```
resource "google_privateca_ca_pool" "pool" {
    id       = "projects/prj-XXX/locations/us-west4/caPools/pool-XYZ"
    labels   = {}
    location = "us-west2"
    name     = "pool-XYZ"
    project  = "prj-XXX"
    tier     = "DEVOPS"
}
```

### Actual Behavior

The only attribute listed in the doc is `id`

### Impact

The `name` attribute is needed for the `pool` field when creating a `google_privateca_certificate_authority` resource. Having this reference helps terraform determine the dependancies between the ca pool the certificate authority.

**Comment by rileykarson** [comment]
An "attribute" refers to an output-only field in Terraform, like `id` here. `name` is listed as an argument on the resource, where an "argument" is a configurable field: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_ca_pool#name

I'm not sure why that's what defines attribute vs argument, but that's convention for providers.
