### ISSUE TITLE
Data "source google_compute_default_service_account" gets no data

### ISSUE THREAD

**Issue by menzbua** [hashicorp/terraform-provider-google#9677]
Hi,

i have a question regarding the data source `google_compute_default_service_account`. My datasource.tf file looks like this:
```tf
data "google_compute_default_service_account" "default" {
  project     = "storage-bucket-test-314809"
}
output "default_account" {
  value = data.google_compute_default_service_account.default
}
data "google_project" "project" {
  project_id     = "storage-bucket-test-314809"
}
output "default_project" {
  value = data.google_project.project
}
```

When i try to get the compute default service account i did not get any informations:
```bash
root@47e64b60cb7f:~# terraform refresh
google_compute_network.aib6ie: Refreshing state... [id=projects/storage-bucket-test-314809/global/networks/test-vpc01]
google_compute_subnetwork.fohz4i: Refreshing state... [id=projects/storage-bucket-test-314809/regions/europe-west3/subnetworks/test-sub01]

Outputs:

default_account = {
  "display_name" = tostring(null)
  "email" = tostring(null)
  "id" = tostring(null)
  "name" = tostring(null)
  "project" = tostring(null)
  "unique_id" = tostring(null)
}
root@47e64b60cb7f:~#
```

The `google_project` is working:

```bash
default_project = {
  no relevant data
  })
  "name" = "storage-bucket-test"
  "number" = ""
  "org_id" = ""
  "project_id" = "storage-bucket-test-314809"
  "skip_delete" = tobool(null)
}
```

Have i specify any other paramters for the compute default service account? Compute API is activated and the service account is there when i take a look in the Google Cloud Console.

Following versions are running:
```bash
root@47e64b60cb7f:~# terraform version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/google-beta v3.74.0
root@47e64b60cb7f:~#
```

Thanks a lot
Regards
Manuel

**Comment by edwardmedia** [comment]
@menzbua can you post your debug log by running below config?

```tf
data "google_compute_default_service_account" "default" {
  project     = "storage-bucket-test-314809"
}
output "default_account" {
  value = data.google_compute_default_service_account.default
}
```

**Comment by menzbua** [comment]
Hi @edwardmedia,

is it safe to post here? Or should i look for informations to remove?

Regards
Manuel

**Comment by edwardmedia** [comment]
@menzbua do you noticed below error in your log? The account `961917372153` does not appear in any other places which make me hard to guess. Does it tell you something?

```
{
  "error": {
    "code": 404,
    "message": "Account deleted: 961917372153",
    "errors": [
      {
        "message": "Account deleted: 961917372153",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}
```

**Comment by menzbua** [comment]
@edwardmedia no, i don't know this account and i don't know where it comes from. I think i will create a new project and check if default service account data is working there.

**Comment by edwardmedia** [comment]
@menzbua yes, please post the result in a fresh project

**Comment by menzbua** [comment]
Hi @edwardmedia,

with the new project the issue is solved. Something went wrong with the service accounts for the old project.

Thanks for your help.
Regards
Manuel

**Comment by edwardmedia** [comment]
@menzbua  Cheers! Closing the issue then
