### ISSUE TITLE
About node pool

### ISSUE THREAD

**Issue by chtourou-youssef** [hashicorp/terraform-provider-google#9682]
If you have a support request or question please submit them to one of these resources:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended , in documentation , why using a separately managed node pool is recommended ?

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)

**Comment by hawksight** [comment]
It allows you to control the k8s master or GKE master version separately to that of your nodes.
If you have all node pools, then those pools can be upgraded individually, independant (for the most part) of the cluster master / control plane.
