### ISSUE TITLE
GA: Support for Cloud Build Worker Pools

### ISSUE THREAD

**Issue by chris-jaques** [hashicorp/terraform-provider-google#9684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Build Worker Pools are now GA, but the resource still only exists in the beta provider, which throws the following error:
```
Error creating WorkerPool: googleapi: Error 403: project is not allowlisted for this feature, please contact Google Cloud Support at https://cloud.google.com/support-hub
```
The resource should be moved to the `google` provider, without this restriction

### New or Affected Resource(s)

* google_cloudbuild_worker_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #8985

**Comment by slevenick** [comment]
b/195009432

**Comment by mikeywaites** [comment]
Hey.  Wondering if there's any timeline of when worker pools will be released out of beta?  Or is there a workaround for using them as beta at the moment?

**Comment by Zowie** [comment]
+1

**Comment by bestefreund** [comment]
+1

**Comment by NotNoah** [comment]
+1

**Comment by octopop** [comment]
Any progress on this? (or any workarounds so that we don't have to keep that section commented out in our TF code)?

**Comment by tstadje** [comment]
+1

**Comment by bestefreund** [comment]
The issue still occurs.
When it comes to the deployment of the resource `google_cloudbuild_worker_pool` with Terraform it comes to the error `Error creating WorkerPool: googleapi: Error 403: project is not allowlisted for this feature, please contact Google Cloud Support at https://cloud.google.com/support-hub`

Is here any progress on this & when will this `priority/1`-issue be solved?

If we can contribute something to this issue then let me know were to place it, please.

**Comment by rezakamalifard** [comment]
+1

**Comment by jdub55** [comment]
Code change has been merged and this should be getting released soon. https://github.com/GoogleCloudPlatform/magic-modules/pull/5356

**Comment by rileykarson** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/5356

**Comment by gecko655** [comment]
The feature is included in [v4.3.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.3.0), but the documentation states that it is still in beta. This should also be updated.

https://github.com/hashicorp/terraform-provider-google/blob/master/website/docs/r/cloudbuild_worker_pool.html.markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_worker_pool

**Comment by rileykarson** [comment]
@ndmckinley: Is that something you'd be able to fix up?

**Comment by ndmckinley** [comment]
Yep, sure thing.

**Comment by ndmckinley** [comment]
Oh, the doc was handwritten, so that's really easy.
