### ISSUE TITLE
google_artifact_registry_repository 'format' diff should be case-insensitive

### ISSUE THREAD

**Issue by Chupaka** [hashicorp/terraform-provider-google#9692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently docs point to gcloud manual for format listing, where formats are in lowercase (e.g. "docker"). And it successfully creates the repo. But the next plan wants to recreate the resource because of

```
  # google_artifact_registry_repository.gar must be replaced
-/+ resource "google_artifact_registry_repository" "gar" {
      ~ create_time   = "2021-07-31T18:37:18.152832Z" -> (known after apply)
      ~ format        = "DOCKER" -> "docker" # forces replacement
```

### New or Affected Resource(s)

* google_artifact_registry_repository

**Comment by ScottSuarez** [comment]
ref: consider. promoting in fix of this bug https://github.com/hashicorp/terraform-provider-google/issues/9690
