### ISSUE TITLE
Docs/validation: Only one access_config supported per network_interface

### ISSUE THREAD

**Issue by morgante** [hashicorp/terraform-provider-google#9693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

- google_compute_instance_template
- google_compute_instance

### Important Factoids
Currently, the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#access_config) says you can have multiple access configs for each `network_interface`. In practice, the GCP API does not allow this and returns "At most one access config currently supported." We should at least correct the documentation so users aren't confused when trying to use multiple access configs.

b/314111528

**Comment by psawant29** [comment]
Hi @rileykarson I will work on this issue
