### ISSUE TITLE
google_firestore_index causes googleapi: Error 409: index already exists

### ISSUE THREAD

**Issue by david-wb** [hashicorp/terraform-provider-google#9694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.0.1

### Affected Resource(s)

* google_firestore_index

### Terraform Configuration Files

```tf
resource "google_firestore_index" "daily-conversation-reports-index" {
  collection = "dailyConversationReports"

  fields {
    field_path = "agentId"
    order      = "ASCENDING"
  }

  fields {
    field_path = "fromDate"
    order      = "ASCENDING"
  }

  fields {
    field_path = "toDate"
    order      = "ASCENDING"
  }
}
```

### Expected Behavior

I should be able to apply the same terraform configuration multiple times without errors. The provider should know that the resource already exists and is tracked by terraform.

### Actual Behavior

Re-running the same configuration twice, it passed the first time, but on the second run it errors out with
```
Error: Error creating Index: googleapi: Error 409: index already exists
│ 
│   with google_firestore_index.daily-conversation-reports-index,
│   on firestore.tf line 1, in resource "google_firestore_index" "daily-conversation-reports-index":
│    1: resource "google_firestore_index" "daily-conversation-reports-index" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ScottSuarez** [comment]
Can you help me understand your workflow to encounter this issue.

If you run terraform apply to create an index the index should exist in state. Running a subsequent apply won't create a new index. 

If you are creating a new index with the same parameters as a previously created one. It could be that the api does not allow duplicate indexes to be created. If this is the case you may need to import the already created index with `$ terraform import google_firestore_index.default {{name}}`.

**Comment by david-wb** [comment]
> Can you help me understand your workflow to encounter this issue.
> 
> 
> 
> If you run terraform apply to create an index the index should exist in state. Running a subsequent apply won't create a new index. 
> 
> 
> 
> If you are creating a new index with the same parameters as a previously created one. It could be that the api does not allow duplicate indexes to be created. If this is the case you may need to import the already created index with `$ terraform import google_firestore_index.default {{name}}`.

Yes that's exactly the problem. A subsequent apply is trying to create a new index and thats causing the error. @ScottSuarez

**Comment by ScottSuarez** [comment]
Cool ! I'll try to reproduce on my end

**Comment by ScottSuarez** [comment]
could you provide some logs as a github gist? With both actions, first apply and second apply provided
you can set
```
export TF_LOG=DEBUG
export TF_LOG_PATH=./t.log
```

to collect them

If you set a final fields block to 
```
  fields {
    field_path = "__name__"
    order      = "ASCENDING"
  }
```
it should unblock you while i work on a fix
