### ISSUE TITLE
Add unit tests for customize diff / diff suppress funcs

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9700]
Many of our diff suppress funcs and customize diff funcs may not be unit tested. We want to go through them, find any that are missing unit tests, and add unit tests for them. This is time boxed as a medium.

**Comment by ScottSuarez** [comment]
not this may require adding wrapper functions for existing diff suppresses

**Comment by megan07** [comment]
I was able to complete 8 unit tests for diff suppress functions. I didn't look into any of the customize diff ones.

Here is a list of the others that still need unit tests:

- storage_bucket_object.detect_md5hash (this one is inline, so we'd have to break it out if we wanted a unit test for it)

- authHeaderDiffSuppress
- cidrOrSizeDiffSuppress
- cloudrunAnnotationDiffSuppress
- cloudrunLabelDiffSuppress
- cloudrunTemplateAnnotationDiffSuppress
- compareCaseInsensitive
- compareCryptoKeyVersions
- compareProjectName
- comparePubsubSubscriptionExpirationPolicy
- compareResourceNames
- compareSelfLinkOrResourceNameWithMultipleParts
- compareSelfLinkRelativePaths
- compareServiceAccountEmailToLink
- compareTpuNodeSchedulingConfig
- composerImageVersionDiffSuppress
- containerClusterAddedScopesSuppress
- containerClusterPrivateClusterConfigSuppress
- containerNodePoolLabelsSuppress
- ontainerNodePoolTaintSuppress
- dataprocImageVersionDiffSuppress
- dataprocMetastoreServiceOverrideSuppress
- diffSuppressIamUserName
- diffSuppressEmptyStartTimeOfDay
- diffSuppressEnableLogging
- diskImageDiffSuppress
- emptyOrUnsetBlockDiffSuppress
- iamMemberCaseDiffSuppress
- internalIpDiffSuppress
- jsonPolicyDiffSuppress
- kmsCryptoKeyRingsEquivalent
- monitoringDashboardDiffSuppress
- NotebooksInstanceLabelDiffSuppress
- podSecurityPolicyCfgSuppress
- portDiffSuppress
- resourceBigQueryDatasetAccessIamMemberDiffSuppress
- resourceBigQueryDatasetAccessRoleDiffSuppress
- resourceDataflowJobLabelDiffSuppress
- rfc5545RecurrenceDiffSuppress
- rrdatasDnsDiffSuppress
- serviceAccountDiffSuppress
- sslSettingsDiffSuppress
- suppressFirstGen
- suppressOmittedMaxDuration
- suppressSuffixDiff

Closed by add unit tests for diff suppress funcs GoogleCloudPlatform/magic-modules#5050
