### ISSUE TITLE
Settings version must be provided

### ISSUE THREAD

**Issue by generalpiston** [hashicorp/terraform-provider-google#9719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.76.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.76.0"
    }
  }
  required_version = ">= 1.0.3"
}

provider "google" {
  credentials = "credentials.json"

  project = "..."
  region  = "us-central"
}

resource "google_sql_database_instance" "..." {
  name             = "..."
  database_version = "POSTGRES_13"
  region           = "us-central1"

  settings {
    tier = "db-f1-micro"

    ip_configuration {
      ipv4_enabled = true
    }

    backup_configuration {
      enabled = true
      binary_log_enabled = false
      location = "us"
      point_in_time_recovery_enabled = true
    }

    maintenance_window {
      day = 1
      hour = 0
    }
  }
}
```

### Expected Behavior

It should not error out.

### Actual Behavior

```
google_sql_database_instance....: Modifying... [id=...]
╷
│ Error: Error, failed to update instance settings for : googleapi: Error 400: Missing parameter: Settings version., required
│
│   with google_sql_database_instance....,
│   on main.tf line 63, in resource "google_sql_database_instance" "...":
│   63: resource "google_sql_database_instance" "..." {
│
╵
```

### Steps to Reproduce

1.  Create an instance in Google Cloud Platform.
2. Import that resource.
3. `terraform apply`

### Important Factoids

If you add a `version` to Google provider, it works:

```tf
provider "google" {
  credentials = "credentials.json"

  project = "..."
  region  = "us-central"
  version = "3.76.0"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#settings.version

**Comment by edwardmedia** [comment]
@generalpiston where did you see you can do without that `Settings version.`?

**Comment by generalpiston** [comment]
@edwardmedia Apparently setting a version is deprecated...

```
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│
│   on main.tf line 16, in provider "google":
│   16:   version = "3.76.0"
│
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated
│ and will be removed in a future version of Terraform. To silence this warning, move the provider version constraint into the
│ required_providers block.
```

**Comment by edwardmedia** [comment]
@generalpiston that [change](https://github.com/hashicorp/terraform-provider-google/issues/9719#issuecomment-892906633) is in Terraform core. The [error](https://github.com/hashicorp/terraform-provider-google/issues/9719#issue-959733113) you received is a separate thing, right? Can you detail what exact issue you are trying to resolve?

**Comment by generalpiston** [comment]
@edwardmedia There error is in the issue description. When I try to apply the above configuration, I get the following error:

```
google_sql_database_instance....: Modifying... [id=...]
╷
│ Error: Error, failed to update instance settings for : googleapi: Error 400: Missing parameter: Settings version., required
│
│   with google_sql_database_instance....,
│   on main.tf line 63, in resource "google_sql_database_instance" "...":
│   63: resource "google_sql_database_instance" "..." {
│
╵
```

 I solved the error by adding `version` to the google provider like so:

```
provider "google" {
  credentials = "..."

  project = "datacy-dev-319809"
  region  = "us-central"
  version = "3.76.0"
}
```

However, that's deprecated, apparently.

I get that the change is in Terraform core, but shouldn't the google provider respect it moving forward?

**Comment by edwardmedia** [comment]
@generalpiston is this still an issue?

**Comment by generalpiston** [comment]
@edwardmedia I can't seem to reproduce any more.

**Comment by edwardmedia** [comment]
@generalpiston closing this issue then. Feel free to reopen if it comes back. Thanks
