### ISSUE TITLE
Refreshing google_sql_user resource fails if database instance is deleted outside Terraform

### ISSUE THREAD

**Issue by wheukels** [hashicorp/terraform-provider-google#9721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.78.0
```
### Affected Resource(s)

google_sql_user

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "test" {
  name             = "test-instance-1"
    database_version = "POSTGRES_13"
    region           = "europe-west4"

    settings {
      tier = "db-f1-micro"
    }
}

resource "google_sql_user" "test" {
  name     = "testuser"
  instance = google_sql_database_instance.test.name
  password = "test123"
}
```

### Debug Output

https://gist.github.com/wheukels/d67cbdc9ed400a4f1620d4f5ab829f41

### Expected Behavior

When refreshing a database user fails because the database no longer exists, the user should be treated as a non-existent resource, if it is feasible to do so.

### Actual Behavior

`terraform plan` fails with the following error:

Error: Error when reading or editing SQL User "testuser" in instance "test-instance-1": googleapi: Error 400: Invalid request: Invalid request since instance is not running., invalid

### Steps to Reproduce

1. `terraform apply`
2. Manually delete the database instance
3. `terraform apply`

To fix the issue, the google_sql_user needs to be removed from the state with ```terraform state rm```.

### References

https://github.com/hashicorp/terraform/issues/10917 details a similar issue in the AWS provider.

**Comment by edwardmedia** [comment]
@wheukels I don't think this can be fixed. There is a discussion [here](https://github.com/hashicorp/terraform-provider-google/issues/7810) . Please go over it to see if that make sense?

**Comment by wheukels** [comment]
Thank you @edwardmedia, I did not find this issue earlier but is indeed basically indentical.
