### ISSUE TITLE
Handwritten GCE resources send requests to `projects/projects/{{project}}`

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#9722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- All

### Affected Resource(s)

* google_compute_* (handwritten)

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

Any of our CI logs work, for example https://ci-oss.hashicorp.engineering/repository/download/GoogleCloud_ProviderGoogleCloudGoogleProject/199592:id/debug-google-eec9d8c-TestAccInstanceGroupManager_basic.log. Note that generated resources are not affected, see https://ci-oss.hashicorp.engineering/repository/download/GoogleCloud_ProviderGoogleCloudGoogleProject/199592:id/debug-google-eec9d8c-TestAccComputeAddress_addressBasicExample.log

### Panic Output

N/A

### Expected Behavior

Requests are sent to `projects/{{project}}`

### Actual Behavior

Requests are sent to `projects/projects/{{project}}`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Discovered in https://github.com/hashicorp/terraform-provider-google/issues/9631. Note that this is distinct from https://github.com/hashicorp/terraform-provider-google/issues/9657 where the user provided `projects/my-project`, this bug affects users who specify only `my-project`.

The Google-internal bug b/194934028 (created for #9657) links to some context on why the API is accepting these values. I _suspect_ that Terraform is doing this due to a change in the GCE client, although it's difficult to find the history on that- our logs go back 90d and the issue is present throughout, and I can't use GitHub to check blame on the GCE client because it's all in one too-large file.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/9631
* https://github.com/hashicorp/terraform-provider-google/issues/9657
* b/194934028

**Comment by ScottSuarez** [comment]
weeeeird
