### ISSUE TITLE
How to use topics and rotation period in google_secret_manager_secret?

### ISSUE THREAD

**Issue by arimaverick** [hashicorp/terraform-provider-google#9726]
How can I use pub sub topics in google_secret_manager as it seems cannot recognize the topics block? I am trying to implement the following link: https://cloud.google.com/secret-manager/docs/event-notifications#add_topics 

resource "google_secret_manager_secret" "secret_1" {
  secret_id = "secret_1"
  project = var.project_id  
  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }
  topics {
    name = google_pubsub_topic.token_topic.id
  }
}

Error: Unsupported block type

  on functions.tf line 126, in resource "google_secret_manager_secret" "regtoken_secret_1":
 126:   topics {

Blocks of type "topics" are not expected here.

**Comment by ScottSuarez** [comment]
topics block is working for me fine.

Which version of the terraform google provider are you using?
I would recommend updating

```
resource "google_secret_manager_secret" "secret_1" {
  secret_id = "secret_1"
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
  rotation {
    next_rotation_time = "2014-10-02T15:01:23Z"
    rotation_period = "3153600000s"
  }
  topics {
    name = "beep"
  }
}
```

**Comment by ScottSuarez** [comment]
closing for now, feel free to make a new issue and comment if this is still a point of contention for you
