### ISSUE TITLE
google_storage_transfer_job lacks folders support

### ISSUE THREAD

**Issue by dmnfortytwo** [hashicorp/terraform-provider-google#9728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCS Data Transfer supports folders for both source and destination buckets but corresponding TF resource does not support it.

### New or Affected Resource(s)

* google_storage_transfer_job: gcs_data_source & gcs_data_sink

### Potential Terraform Configuration

```tf
resource "google_storage_transfer_job" "main_backup" {
  description = "Nightly backup of gs://foo_main"
  project     = var.project

  transfer_spec {
    object_conditions {
      min_time_elapsed_since_last_modification = "259200s" # 3 days
    }

    gcs_data_source {
      bucket_name = "foo_main"
      folder      = "dummy/"
    }
    gcs_data_sink {
      bucket_name = google_storage_bucket.main_backup.name
      folder      = "foobar"
    }
  }

  schedule {
    schedule_start_date {
      year  = 2018
      month = 10
      day   = 1
    }
    schedule_end_date {
      year  = 2019
      month = 1
      day   = 15
    }
    start_time_of_day {
      hours   = 23
      minutes = 30
      seconds = 0
      nanos   = 0
    }
  }
}
```
![Screenshot at 2021-08-05 15:28:38](https://user-images.githubusercontent.com/26309559/128350802-915b92cc-8306-4e07-a637-e1bb0557b6f4.png)
![Screenshot at 2021-08-05 15:28:19](https://user-images.githubusercontent.com/26309559/128350821-5745f5e3-1b44-4838-aabb-9dca2a7ec96c.png)

**Comment by psvaiter** [comment]
I guess this feature has been added in [v3.85.0](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3850-september-20-2021) using the name `path`.

**Comment by roaks3** [comment]
Yep, appears fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5117 with `path`
