### ISSUE TITLE
Can't replace (delete) google_privateca_certificate_authority due to ignore_active_certificates_on_deletion

### ISSUE THREAD

**Issue by skorobogatydmitry** [hashicorp/terraform-provider-google#9735]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.78.0

### Affected Resource(s)

* google_privateca_certificate_authority

### Terraform Configuration Files

```tf
resource "google_privateca_certificate_authority" "root" {
...
  ignore_active_certificates_on_deletion = "false" # it doesn't matter
...
```

### Expected Behavior

Resource deletion works.

### Actual Behavior

Resource replacement fails on deletions with the following message:
```
 |Error: Error when reading or editing CertificateAuthority: googleapi: Error 400: Invalid value at 'ignore_active_certificates' (TYPE_BOOL), ""
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value at 'ignore_active_certificates' (TYPE_BOOL), \"\"",
│         "field": "ignore_active_certificates"
│       }
│     ]
│   }
│ ]
```
### Steps to Reproduce

- add resource to TF config
- import resource to state
- plan shows that it need to replace `google_privateca_certificate_authority` - expected
- TF disables CA but can't delete it (see message above)

**Comment by skorobogatydmitry** [comment]
It seems that it happens only for imported resources, as they have `ignore_active_certificates_on_deletion` set to `null`.
If change it in state to some, deletions passes.

**Comment by edwardmedia** [comment]
@skorobogatydmitry that is by design. Any more question / issue about this?

**Comment by skorobogatydmitry** [comment]
> @skorobogatydmitry that is by design. Any more question / issue about this?

@edwardmedia , could you explain a bit ?
It looks odd from design perspective that import command sets incorrect parameter to state what prevents from managing this resource, no ?

**Comment by edwardmedia** [comment]
There are issues in this resource. By executing below import command, it launches the following request, which is wrong. Thank you @skorobogatydmitry for reporting this

> terraform import google_privateca_certificate_authority.default projects/myproject/locations/us-central1/caPools/my-ca-issue9735/certificates/certificate-issue9375

```
GET /v1/projects/projects/locations/myproject/caPools/locations/certificateAuthorities/us-central1?alt=json HTTP/1.1
Host: privateca.googleapis.com
```

**Comment by edwardmedia** [comment]
> terraform import google_privateca_certificate_authority.default us-central1/my-ca-issue9735/certificate-issue9375

```
GET /v1/projects/myproject/locations/us-central1/caPools/my-ca-issue9735/certificateAuthorities/certificate-issue9375=json HTTP/1.1
Host: privateca.googleapis.com
```

**Comment by skorobogatydmitry** [comment]
@edwardmedia , thank you very much for fixing this!
