### ISSUE TITLE
Creating a google_service_account 404s

### ISSUE THREAD

**Issue by jalseth** [hashicorp/terraform-provider-google#9736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v3.78.0
+ provider registry.terraform.io/hashicorp/google-beta v3.78.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

`google_service_account`

### Terraform Configuration Files

```tf
resource "google_service_account" "tf_deployer" {
  project    = google_project.tf_state.id
  account_id = "${var.name}-tf-deployer"
}
```

### Expected Behavior

Service account is created.

### Actual Behavior

GCP returns a 404: 

```
Error: Error creating service account: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1/projects/projects/[redacted]/serviceAccounts?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Looking at the 404 response, the `projects/` in the URL is duplicated, which I believe is causing the issue. The path should be `v1/projects/[redacted]/serviceAccounts`, not `v1/projects/projects/[redacted]/serviceAccounts`.

Edit: I have confirmed the project it's referencing exists, so that's not the issue for the 404.

**Comment by slevenick** [comment]
You can solve this problem by referencing `  project    = google_project.tf_state.project_id` rather than `.id` directly.

It would be great for us to accept both forms in the future, but I wouldn't consider this a bug

**Comment by jalseth** [comment]
Thanks for the clarification! It should be relatively easy to implement a fix that accepts both, I'll do that if I have time.
