### ISSUE TITLE
for_each with condition is inverted on expiration_policy dynamic block

### ISSUE THREAD

**Issue by via-justa** [hashicorp/terraform-provider-google#9744]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v                                   
Terraform v0.15.0
on darwin_amd64
```

### Affected Resource(s)

* google_pubsub_subscription

### Terraform Configuration Files

The following code is a simplified version of the module I'm writing. I'm trying to set the `expiration_policy` block dynamically if `expiration_policy_enabled` is set to `true`. 
```tf
provider "google" {
  project = "xxx-staging"
}

variable "expiration_policy_enabled {
  type            = bool
  description = "should expiration_policy be set"
  default.      = true
}

resource "google_pubsub_topic" "topic" {
  name = "topic"
}

resource "google_pubsub_subscription" "subscription" {
  name                 = "subscription"
  topic                = google_pubsub_topic.topic.name
  ack_deadline_seconds = 10

  dynamic "expiration_policy" {
    for_each = var.expiration_policy_enabled ? ["12d"] : []
    content {
      ttl = expiration_policy.key
    }
  }
}
```

### Debug Output

https://gist.github.com/via-justa/0d608921571085bf87d805de6b153c98

### Expected Behavior

Terraform create subscription with `expiration_policy` `ttl` set to 12d like so
```tf
Terraform will perform the following actions:

  # google_pubsub_subscription.subscription will be created
  + resource "google_pubsub_subscription" "subscription" {
      + ack_deadline_seconds       = 10
      + id                         = (known after apply)
      + message_retention_duration = "604800s"
      + name                       = "sub"
      + path                       = (known after apply)
      + project                    = (known after apply)
      + topic                      = "topic"

      + expiration_policy {
          + ttl = (known after apply)
        }
    }

...

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

terraform creates the resours with undefined `expiration_policy`. It looks like the result of the condition is inverted and instead of taking the `true` value it's taking the `false` value and vice versa. 
```tf
Terraform will perform the following actions:

  # google_pubsub_subscription.subscription will be created
  + resource "google_pubsub_subscription" "subscription" {
      + ack_deadline_seconds       = 10
      + id                         = (known after apply)
      + message_retention_duration = "604800s"
      + name                       = "sub"
      + path                       = (known after apply)
      + project                    = (known after apply)
      + topic                      = "topic"

      + expiration_policy {}
    }

...

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

1. configure google provider and copy the above code
2. run `terraform plan`

**Comment by rileykarson** [comment]
Given the stage this is happening at, I don't believe it's a provider issue- I'd suggest reporting the problem to Terraform Core: https://github.com/hashicorp/terraform/issues/new?assignees=&labels=bug%2C+new&template=bug_report.md
