### ISSUE TITLE
Support for the integration with Secret Manager in Cloud Run not actually added in PR #9073

### ISSUE THREAD

**Issue by andrewrpalmer-sky** [hashicorp/terraform-provider-google#9745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.12.31

### Affected Resource(s)

* google_cloud_run_service

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "foo" {

  name = "foo"
  location = "europe-west2"

  template {
    spec {
      containers {
        image = "eu.gcr.io/project/path/image-version"
        env {
          name = "foo_PASSWORD"
          value_from {
            secret_key_ref {
              name = google_secret_manager_secret.foo_password.secret_id
              key = "latest"
            }
          }
        }
      }
    }
  }

  metadata {
    annotations = {
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }
}
```

### Expected Behavior
Plan/apply succeeds

### Actual Behavior
Error: Unsupported block type\n\n  on main.tf line ### in resource \"google_cloud_run_service\" ###: \"foo\":\n value_from {\n\nBlocks of type \"value_from\" are not expected here.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Compare
https://github.com/hashicorp/terraform-provider-google/pull/9073/files and
https://github.com/hashicorp/terraform-provider-google-beta/pull/3225/files - the former only added the documentation for the feature, not the underlying resource support.

### References

* #9073

**Comment by edwardmedia** [comment]
@andrewrpalmer-sky Can you take a look at this issue? Is that related?

https://github.com/hashicorp/terraform-provider-google/issues/9441

**Comment by edwardmedia** [comment]
@andrewrpalmer-sky is this still an issue?

**Comment by andrewrpalmer-sky** [comment]
Hi, still a problem, and not related to #9441 - I notice in the example code in that issue you used the google-beta provider which works fine, but the supporting code is missing from the google provider which seems to be the problem here.

**Comment by thiras** [comment]
I confirm the issue

**Comment by edwardmedia** [comment]
@andrewrpalmer-sky from what I can see, the feature is [beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#value_from) only. Did you expect otherwise?

**Comment by andrewrpalmer-sky** [comment]
It's mentioned in the google-provider changelog as being available, so yes:

https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3670-may-10-2021

IMPROVEMENTS:
    cloudrun: added support to bind secrets from Secret Manager to environment variables or files to google_cloud_run_service

**Comment by edwardmedia** [comment]
@andrewrpalmer-sky sorry if the changelog does not make clearer. But both the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables) and the [note](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#value_from) specify the feature is beta. Please file an enhancement if you see it is ready for GA.
Closing the issue then
