### ISSUE TITLE
"google_compute_firewall" Resource Should be Renamed to "google_compute_firewall_rule"

### ISSUE THREAD

**Issue by ikegentz** [hashicorp/terraform-provider-google#9747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version
1.0.4

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files (if applicable)
```
resource "google_compute_firewall" "jenkins_firewall" {
    name = "jenkins-firewall"
    project = "<my_project>"
    network = "default"
    description = "Allow HTTP access to Jenkins server"

    allow {
        protocol = "tcp"
        ports = ["8080"]
    }
    direction = "INGRESS"
    target_tags = ["jenkins"]
}

```

### Issue Description
**Expected:** the `google_compute_firewall` resource to be named `google_compute_firewall_rule`, to keep with naming convention (see second reference)
**Actual:** the resource is actually names `google_compute_firewall`
**Steps:** used `google_comptue_firewall` to create an individual firewall rule

### Important Factoids
Nothing strange

### References
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall
- https://cloud.google.com/sdk/gcloud/reference/compute/firewall-rules

**Comment by edwardmedia** [comment]
@ikegentz the Terraform provider usually try to align with the API. Below is the name of the Resource in its Doc. 

https://cloud.google.com/compute/docs/reference/rest/v1/firewalls

Looking at the list of left navigation on this page. Making sense?

**Comment by ikegentz** [comment]
Makese sense - thanks!
