### ISSUE TITLE
Support REDIS_6_0 for memstore

### ISSUE THREAD

**Issue by RayBB** [hashicorp/terraform-provider-google#9749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now GCP supports up to Redis 6 (pre-GA) per https://cloud.google.com/memorystore/docs/redis/upgrading-instance-version

However, it looks like terraform only supports up to version 5
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance#redis_version

Can version 6 be added?

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by upodroid** [comment]
Hi Raymond

Terraform doesn't validate the redis_version field so you can put in REDIS_6_X now.

I have updated docs to mention that the updated values are noted in the API documentation.

Thank you
