### ISSUE TITLE
Incorrect documentation: google_compute_instance.advanced_machine_features

### ISSUE THREAD

**Issue by tsdalton** [hashicorp/terraform-provider-google#9753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* Terraform v1.0.2

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "vm_instance" {
  name = "vm_instance"
  machine_type = var.compute_machine_type
  zone         = var.gcp_zone

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }

  // incorrect argument name
  advanced_machine_config {
    enable_nested_virtualization = true
  }

  // correct argument name
  advanced_machine_features {
    enable_nested_virtualization = true
  }
}
```

Please find in the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance) that the optional argument `advanced_machine_config` should instead be  `advanced_machine_features`. Additionally, it would be helpful to have some examples/further documentation about what goes in the `advanced_machine_features` block.

**Comment by edwardmedia** [comment]
Besides the doc, below two places in code could be updated too.

https://github.com/hashicorp/terraform-provider-google/blob/58f376b1bb2d610e7d57aeb92815032f8334e425/google/resource_compute_instance.go#L1306

https://github.com/hashicorp/terraform-provider-google/blob/58f376b1bb2d610e7d57aeb92815032f8334e425/google/resource_compute_instance.go#L1747
