### ISSUE TITLE
google_cloud_build_trigger filter field

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#9755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Requesting support for the [filter](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers) field for `google_cloudbuild_trigger`.

The `filter` field is apparently almost always used for pubsub-based triggers according to [this comment](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers) and [this page](https://cloud.google.com/build/docs/automating-builds/create-pubsub-triggers#risks_associated_with_an_unfiltered_trigger). That is, users will almost always want to use `filter` when using `pubsub_config`.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### References

* https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/447

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon
