### ISSUE TITLE
Ability to provide service directory region when generating private service connect (PSC) IP's and forwarding rules for Google APIs

### ISSUE THREAD

**Issue by kliu47** [hashicorp/terraform-provider-google#9758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, when generating a PSC endpoint and forwarding rule using google_compute_global_address & google_compute_global_forwarding_rule, the PSC endpoint in is created in the default service directory region. Request is to be able to provide the region in order to create secondary endpoints for availability. 

### New or Affected Resource(s)
[beta]
google_compute_global_forwarding_rule
google_compute_global_address

### Potential Terraform Configuration

```tf

resource "google_compute_global_address" "default" {
  provider     = google-beta
  project      = google_compute_network.network.project
  name         = "global-psconnect-ip"
  address_type = "INTERNAL"
  purpose      = "PRIVATE_SERVICE_CONNECT"
  network      = google_compute_network.network.id
  address      = "10.3.0.5"
}
resource "google_compute_global_forwarding_rule" "default" {
  provider              = google-beta
  project               = google_compute_network.network.project
  name                  = "globalrule"
  target                = "all-apis"
  network               = google_compute_network.network.id
  ip_address            = google_compute_global_address.default.id
  load_balancing_scheme = ""
  region = "us-east4" #new value for region when ip_address is of purpose PRIVATE_SERVICE_CONNECT
}
```

### References

* https://cloud.google.com/vpc/docs/configure-private-service-connect-apis

b/196055443

**Comment by c2thorn** [comment]
The related field in the [REST API](https://cloud.google.com/compute/docs/reference/rest/v1/globalForwardingRules) is `serviceDirectoryRegistrations[].serviceDirectoryRegion`
