### ISSUE TITLE
Importing IAM service account to google_sql_user fails

### ISSUE THREAD

**Issue by villesau** [hashicorp/terraform-provider-google#9760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- Terraform v1.0.3
- registry.terraform.io/hashicorp/google v3.79.0

### Affected Resource(s)

* google_sql_user

### Terraform Configuration Files

```tf
resource "google_sql_user" "sql_backend_access" {
  name     = "some-backend@${var.project_id}.iam"
  instance = module.pg.instance_name
  project  = var.project_id
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}
```

### Expected Behavior

`tf import google_sql_user.sql_backend_access <project-id>/<instance>/some-backend@<project-id>.iam` imports the service account.

### Actual Behavior

It fails to following error:

```
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "google_sql_user.sql_backend_access", the provider detected that no object exists with the given id. Only pre-existing objects can be
│ imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵

```

### Steps to Reproduce

All of the following fails:

1. `tf import google_sql_user.sql_backend_access project/<project-id>/<instance>/some-backend@<project-id>.iam`
2. `tf import google_sql_user.sql_backend_access project/<project-id>/<instance>/<actual-unique-iam-id>`
3. `tf import google_sql_user.sql_backend_access project/<project-id>/<instance>/some-backend`

### Important Factoids

- importing regular users succeeds
- running apply (without importing) results following:

```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.sql_backend_access, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but
│ now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

```

E: The above error actually might also happen in some cases even when creating totally new IAM service account users. The accounts get created but terraflrm errors out and it's not possible to recover from it since importing is broken.

**Comment by itspngu** [comment]
This also happens for "actual" IAM users which aren't service accounts.

**Comment by villesau** [comment]
I believe that pinning the terraform version to `3.77.0` might help. It helped with #9723 at least.

**Comment by itspngu** [comment]
Can confirm that pinning to 3.77.0 did let me import IAM Cloud SQL users.

Also forgot to mention in my first comment that this bug in fact breaks existing configurations, because the provider can not find accounts on the instance, tries to create them, and eventually complains about not finding the accounts it just "created".

**Comment by villesau** [comment]
@megan07 @slevenick this PR https://github.com/GoogleCloudPlatform/magic-modules/pull/4984 likely caused this and #9723

**Comment by rileykarson** [comment]
Deduping to https://github.com/hashicorp/terraform-provider-google/issues/9723, since they appear to be the same issue
