### ISSUE TITLE
flink job deployment on GCP Dataproc

### ISSUE THREAD

**Issue by sehgalnamit** [hashicorp/terraform-provider-google#9766]
We would like to deploy flink job on dataproc based on GCP Documentation [Dataproc Flink Component  |  Dataproc Documentation  |  Google Cloud|https://cloud.google.com/dataproc/docs/concepts/components/flink]
Dataproc Flink Component  |  Dataproc Documentation  |  Google Cloud

As per docs , our current terraform module is not supporting FLINK Optional Component

software_config_optional_components = ["ZOOKEEPER", "JUPYTER", ] # https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster#optional_components

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster#optional_components
 
While in the GCP documentation, it is available by creating the cluster using flags via GCloud CLI and via Console

Require a feature to include flink as an optional component.

Thanks
Namit Sehgal

**Comment by ScottSuarez** [comment]
This would require adding a field for FLINK to the enumeration list. Recommend switching this field to be a string input.

https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/dataproc/api.yaml#L484-L498

https://cloud.google.com/dataproc/docs/reference/rest/v1/ClusterConfig#Component

**Comment by ScottSuarez** [comment]
@sehgalnamit feel free to submit a pr on the file linked above to update the fields to be in sync with the documentation if you want a solution expedited.

**Comment by sehgalnamit** [comment]
Many Thanks @ScottSuarez 
Raised PR 
https://github.com/sehgalnamit/magic-modules/pull/1

**Comment by sehgalnamit** [comment]
@ScottSuarez 
Can check please again?
https://github.com/GoogleCloudPlatform/magic-modules/pull/5106
