### ISSUE TITLE
google_compute_backend_bucket/google_compute_url_map -- Dependency missing

### ISSUE THREAD

**Issue by huang-jy** [hashicorp/terraform-provider-google#9769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.0-alpha20210728
on linux_amd64

### Affected Resource(s)

* google_compute_backend_bucket
* google_compute_url_map

### Terraform Configuration Files

Example codebase demonstrating this issue available at: https://gitlab.com/blenderfox-bugreports/google-terraform-backend-bucket-bugreport

### Debug Output

```
│ Error: Error creating UrlMap: googleapi: Error 400: The resource 'projects/myProject/global/backendBuckets/defaultsvc-backend-bucket' is not ready, resourceNotReady
│
│   with google_compute_url_map.routing,
│   on routing.tf line 54, in resource "google_compute_url_map" "routing":
│   54: resource "google_compute_url_map" "routing" {
│
╵

```

### Panic Output

N/A

### Expected Behavior

Terraform should wait for the backend bucket to be ready before trying to create the url-map

### Actual Behavior

Terraform did not wait for the backend bucket to be ready before trying to create the url-map which then failed since the bucket was not ready.

The issue occurs only sometimes, and seems to depend on what Terraform decides to action first. If parallelism is increased from its default (10) to (for example) 20, the problem can be triggered reliably.

In the case of the linked example, I have a url-map referencing a backend_bucket resource. There is a dependency here, in that the backend bucket must be ready before the url-map can be created.

When terraform tries to run actions in parallel, the url-map creation can be started before the backend_bucket is created and/or ready. This causes the url-map creation to fail with the error mentioned above. It does not appear that the url-map creation waits for backend_bucket to be ready before starting.

### Steps to Reproduce

Instructions are available on the linked GitLab repo, including sample terraform files

### Important Factoids

N/A

**Comment by edwardmedia** [comment]
@huang-jy from the symptom you described, similar behavior could happen to other resources. There are several ways in Terraform that might help. Besides [depend_on](https://www.terraform.io/docs/language/meta-arguments/depends_on.html), you may also add `sleep` logic between the resources. Does this make sense?

**Comment by huang-jy** [comment]
Yes, depend_on was one option I considered, but even the Terraform documentation says that it should be a last resort.

How would `sleep` logic help in this case?

My understanding is that Terraform _should_ be able to infer dependencies between resources itself without us having to explicitly say "A before B"

**Comment by edwardmedia** [comment]
@huang-jy Some resources may take extra long time to complete even its api reports `done`. In such case, there is not much the provider can do. here is an example about using `sleep`. Please take a look and let me know if that help

https://github.com/hashicorp/terraform-provider-google/issues/6377#issuecomment-628978514

**Comment by huang-jy** [comment]
Adding the delay does help in this matter, but it now introduces a problem with my use case.

Since `depends_on` must be a static list I don't think I can use the code in a module since I can't say in advance how many buckets there will be.

I was intending the module caller to specify what buckets they want to create -- which will then require the `url-map` to wait on all the buckets' creations before being created.

I'm not sure how I can do a dynamic `depends_on` in this case.

**Comment by edwardmedia** [comment]
@huang-jy don't you think you can work with the owner of the module to find a solution? To see if the provider can help, can you provide the config (resources only) that can repro the issue?

**Comment by huang-jy** [comment]
Example code and module located at:

https://gitlab.com/blenderfox/terraform-cdn-bucket-module

You can run it as follows:

1. cd into the `example` folder, and save a GCP serviceaccount json file as `credentials.json` in that folder
2. Update the `preprod/terraform.tfvars` file to reflect your local environment
3. `terraform init`
4. `terraform plan -out tfplan -var-file="preprod/terraform.tfvars" `

This will create two buckets -- a default and a "main" one and a routing table to map requests to one of the two buckets. The bucket definitions are explicit (I.e they are within the module) but should ideally be outside the module.

The null_resource workaround (https://github.com/hashicorp/terraform-provider-google/issues/9769#issuecomment-896940941) to introduce delays for the resource generation are included:

https://gitlab.com/blenderfox/terraform-cdn-bucket-module/-/blob/main/module/cdn.tf#L36
https://gitlab.com/blenderfox/terraform-cdn-bucket-module/-/blob/main/module/default-cdn.tf#L35
https://gitlab.com/blenderfox/terraform-cdn-bucket-module/-/blob/main/module/routing.tf#L76

The dilemma here is that if we make the buckets configurable via something like a `for_each`, then the `depends_on` will be dynamic so how do we fill that with the `null_resource` references if it must be a static list?

You can replicate the problem if you comment out the blocks in the 3 links above then `destroy` and `plan`/`apply`

```
│ Error: Error creating UrlMap: googleapi: Error 400: The resource '{resource_name}' is not ready, resourceNotReady
│
│   with module.cdn-router.google_compute_url_map.routing,
│   on ../module/routing.tf line 49, in resource "google_compute_url_map" "routing":
│   49: resource "google_compute_url_map" "routing" {
│
```

Hopefully this makes sense.

**Comment by edwardmedia** [comment]
@huang-jy I see [what you say ](https://gitlab.com/blenderfox-bugreports/google-terraform-backend-bucket-bugreport#bug-report-repo-for-the-google_compute_backend_bucket-issue). The error is clear. Based on the fact as I explained [here](https://github.com/hashicorp/terraform-provider-google/issues/9769#issuecomment-896940941), you can always find `issue` like this on other resources. By introducing `depend_on` and `sleep`, we are trying to put that under control. You may also consult Terraform Core to see how to effectively implement dynamic code. I don't think there are much the provider itself can do to this. Closing the issue accordingly. Feel free to reopen if you can repro with the config without the dynamic code. 
 
> If the issue does not occur, destroy and reapply with an increased parallelism value:

```
Error 400: The resource '{resource_name}' is not ready,
```
