### ISSUE TITLE
Ability to lock logging buckets via google_logging_project_bucket_config resource

### ISSUE THREAD

**Issue by jlosito** [hashicorp/terraform-provider-google#9772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_logging_project_bucket_config` resource doesn't seem to have the locking feature based on the most recent documentation.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config

I would like to lock a bucket via this resource. In other words, I would like to do something like the following command via the `google_logging_project_bucket_config` resource.
`gcloud logging buckets update _Default --location=global --locked`

Here's a link to the documentation on locking log buckets.
https://cloud.google.com/logging/docs/buckets#locking-logs-buckets

I believe the `locked` attribute is not exposed in the schema, yet I do see references to maybe what should be it.
https://github.com/hashicorp/terraform-provider-google/blob/45e0dfc621066b2a1719cf29fea8df9709583fbf/google/resource_logging_bucket_config.go#L154
https://github.com/hashicorp/terraform-provider-google/blob/45e0dfc621066b2a1719cf29fea8df9709583fbf/google/resource_logging_bucket_config.go#L12-L47

### New or Affected Resource(s)

* google_logging_project_bucket_config

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_logging_project_bucket_config" "lock_default_bucket" {
    project = "my_project_id"
    location = "global"
    retention_days = 30
    bucket_id = "_Default"
    is_locked = true
}
```

### References

* b/282978598

**Comment by diogospt** [comment]
Any updates regarding this feature request?
