### ISSUE TITLE
google_compute_router_interface deployment is failing

### ISSUE THREAD

**Issue by g-nikolay** [hashicorp/terraform-provider-google#9780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.3
Provider v3.79.0

### Affected Resource(s)

* google_compute_router_interface

### Terraform Configuration Files

```tf
resource "google_compute_network" "compute_network" {
  name = "compute-network"
  auto_create_subnetworks = false
  routing_mode = "REGIONAL"
}

resource "google_compute_router_interface" "foobar" {
  name       = "interface-1"
  router     = google_compute_network.compute_network.name
  region     = "us-west1"
  ip_range   = "169.254.1.1/30"
  vpn_tunnel = "tunnel-1"

  depends_on = [
    google_compute_router.compute_router
  ]
}

resource "google_compute_router" "compute_router" {
  name = "compute-router"
  description = "example router description"
  region = "us-west1"
  network = google_compute_network.compute_network.id
  bgp {
    asn = 64517
    advertise_mode = "CUSTOM"
    advertised_groups = ["ALL_SUBNETS"]
    advertised_ip_ranges {
      description = ""
      range = "1.2.3.4"
    }
  }

  depends_on = [
    google_compute_network.compute_network
  ]
}
```

### Debug Output

https://gist.github.com/g-nikolay/1c514436bd0b2f668f4cc4e9a070ac55

### Actual Behavior

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_compute_router_interface.foobar, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Hmm- seems like https://github.com/hashicorp/terraform-provider-google/issues/9722 may not be entirely innocuous like I suspected, that's the only difference between the URLs in use for `google_compute_router` and `google_compute_router_interface`.

@ScottSuarez: Are you still taking a look at #9722?

**Comment by ScottSuarez** [comment]
Just had some time to take a look today. Seems like a simple fix pending no test issues

https://github.com/hashicorp/terraform-provider-google/issues/9722

**Comment by rileykarson** [comment]
@g-nikolay: This _should_ be fixed in next week's release but if it's not can you post again here?

**Comment by g-nikolay** [comment]
@rileykarson thanks for reply, I'll keep you posted, thanks!
