### ISSUE TITLE
Fix import for `google_essential_contacts_contact`

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#9783]
`google_essential_contacts_contact`

will fix the following test(s)
`TestAccEssentialContactsContact_essentialContactExample `

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/5072

**Comment by upodroid** [comment]
I can fix this. Also we need to promote this to ga as the beta api is deprecated.

https://cloud.google.com/resource-manager/docs/reference/essentialcontacts/rest/v1beta1/projects.contacts

**Comment by ScottSuarez** [comment]
note @c2thorn upodroid has a pr out
