### ISSUE TITLE
Support Shared Reservations with Terraform (beta)

### ISSUE THREAD

**Issue by sankit2020** [hashicorp/terraform-provider-google#9790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

https://buganizer.corp.google.com/issues/178812267

**Comment by sankit2020** [comment]
This feature is in public preview on August 2nd.

Feature Name: Shared Reservation

API documentation (usually found in the user guide or in a "Rest API" section on the cloud website): go/shared-reservations-ug

**Comment by upodroid** [comment]
Hi

Can you link the docs from Google instead of reporting the bug number if public docs exist when you log the issue in Github?

https://cloud.google.com/compute/docs/instances/reservations-shared
https://cloud.google.com/compute/docs/reference/rest/beta/reservations/insert

**Comment by rileykarson** [comment]
This is adding support for the `shareSettings` block:

```
  "shareSettings": {
    "shareType": enum,
    "projects": [
      string
    ]
  },
```

Note that `projects` will return projects by number even when specified with their id, so we may need to ignore reading back the value from the API or something similar (this will make import difficult regardless)

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/5547 (as of Jan 12th or so)
