### ISSUE TITLE
Error: timeout while waiting for state to become 'success' (timeout: 1m0s)

### ISSUE THREAD

**Issue by Barbarians** [hashicorp/terraform-provider-google#9793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.4

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
provider "google-beta" {}

terraform {
  backend "gcs" {}
}

resource "google_container_cluster" "primary" {
  provider = google-beta
  for_each = var.clusters

  name                     = each.value["name"]
  location                 = each.value["location"]
  subnetwork               = each.value["subnetwork"]
  description              = var.description
  initial_node_count       = var.initial_node_count
  remove_default_node_pool = true
  enable_legacy_abac       = false
  network                  = var.network
  project                  = var.project

  default_max_pods_per_node   = var.default_max_pods_per_node
  enable_intranode_visibility = var.enable_intranode_visibility

  enable_shielded_nodes = var.enable_shielded_nodes

  network_policy {
    enabled = var.network_policy_enabled
  }

  cluster_autoscaling {
    enabled             = var.cluster_autoscaling_enabled
    autoscaling_profile = var.autoscaling_profile
  }

  addons_config {
    horizontal_pod_autoscaling {
      disabled = false
    }
    http_load_balancing {
      disabled = var.http_load_balancing
    }
    istio_config {
      disabled = true
    }
    cloudrun_config {
      disabled = true
    }
    dns_cache_config {
      enabled = var.dns_cache_config
    }
    gce_persistent_disk_csi_driver_config {
      enabled = true
    }
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = each.value["cluster_secondary_range_name"]
    services_secondary_range_name = each.value["services_secondary_range_name"]
  }

  release_channel {
    channel = var.maintenance_channel
  }

  maintenance_policy {
    recurring_window {
      start_time = var.maintenance_weekly_start_time
      end_time   = var.maintenance_weekly_end_time
      recurrence = format("FREQ=WEEKLY;BYDAY=%s", var.maintenance_weekly_days)
    }
  }

  private_cluster_config {
    enable_private_nodes    = var.enable_private_nodes
    enable_private_endpoint = var.enable_private_endpoint
    master_ipv4_cidr_block  = each.value["master_ipv4_cidr_block"]
    master_global_access_config {
      enabled = var.master_global_access_config
    }
  }

  master_auth {
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  authenticator_groups_config {
    security_group = "gke-security-groups@******"
  }

  pod_security_policy_config {
    enabled = false
  }

  database_encryption {
    state    = var.database_encryption_state
    key_name = var.database_encryption_key_name
  }

  workload_identity_config {
    identity_namespace = "${var.project}.svc.id.goog"
  }

  master_authorized_networks_config {
    dynamic "cidr_blocks" {
      for_each = each.value["authorized_cidr_blocks_list"]
      content {
        cidr_block   = cidr_blocks.value["cidr_block"]
        display_name = cidr_blocks.value["display_name"]
      }
    }
  }

  enable_tpu              = false
  enable_kubernetes_alpha = false

  monitoring_service = "monitoring.googleapis.com/kubernetes"
  logging_service    = "logging.googleapis.com/kubernetes"

  resource_usage_export_config {
    enable_network_egress_metering       = true
    enable_resource_consumption_metering = true

    bigquery_destination {
      dataset_id = var.bigquery_destination_dataset_id
    }
  }
}
```

### Panic Output

https://gist.github.com/Barbarians/1d843aedaca8d83d3edf82f645a01148

### Expected Behavior

Create a new cluster

### Actual Behavior

Nothing

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment]
@Barbarians it is hard to say for below error. it could be api that was experiencing difficulties. Have you run the config before?  

> Error code 500,  Internal error encountered.

For debug, does the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended) work for you? If yes, maybe try to gradually add more code blocks to see which one causes the issue?

**Comment by Barbarians** [comment]
@edwardmedia this config work fine, it's been 2-3 days since it works anymore.

It's been 3 months since I deployed my infrastructure on gcp and mongo atlas without any problem.

I tried to deploy blocks by block and i back

**Comment by Barbarians** [comment]
@edwardmedia i have resolve my problem.

The [security group](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/container_cluster#security_group) "gke-security-groups@****" is not set in my organisation.

Now is good all clusters is deploy on my infrastructure.

But i think its better a message "Security group does not exist" but not "Error: timeout while waiting for state to become 'success' (timeout: 1m0s)" in terraform and gcp api return "backendError"
