### ISSUE TITLE
3.79.0 released without documentation

### ISSUE THREAD

**Issue by awendt** [hashicorp/terraform-provider-google#9800]
A 3.79.0 tag was pushed [3 days ago](https://github.com/hashicorp/terraform-provider-google/tags), which resulted in a release on https://registry.terraform.io/providers/hashicorp/google/latest – but as of 2021-08-13, the [changelog](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md) still says "Unreleased."

This means Dependabot is sending version updates for 3.79.0 without a proper changelog.

**Comment by rileykarson** [comment]
Sorry about that! It's a manual process to fill that information in from a release branch like https://github.com/hashicorp/terraform-provider-google/tree/release-3.79.0, and I was a couple days behind. Done now for both providers!
