### ISSUE TITLE
reconcile serialization with dcl sample updates

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#9811]
### Affected Resource(s)

* google_*

the update workflow was not correctly initially. It will take some work and collaboration with dcl team to get this working correctly.

Below are my notes from my sync with @ndmckinley 

## Dcl sample updates to hcl 
* Two issues
    * Figuring out which resource to update
        * Solved - look at the name of file to determine which type of resource to update
        * Then parse the file into a dcl object 
            * What about reading - {{ref:sfdd}}
            * Additional step ?
            * Check whether references are correctly resolved.. If they are .. great, if not, will export tool to assist 
        * call .ID to map to the resource we are updating -> map to terraform hcl header
    * Resource back references
        * References to resources that aren’t being replaced
            * Fine
        * References to resources that are 
            * declared in the previous config (ok)
            * server generated and not already declared
        * Solution, since we are only replacing one resource at a time, 
            * Omit references that are not declared in the previous config
            * Backtrack ones that are

**Comment by c2thorn** [comment]
DCL to:

- Give full list of DCL dependencies for each update
- Remove non-computed references to previous states and replace them with a value
- Indicate computed references to previous states with something like `{{ref:__previous_state__:fieldName}}` that would allow us to remove the field from config (since it is computed and set in a previous state)

**Comment by ScottSuarez** [comment]
Is there an internal bug against the dcl for this that we can track separately ?

@c2thorn

**Comment by ndmckinley** [comment]
I've been using b/192083636.  I'll copy this here into that bug.

**Comment by trodge** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/5290 partially resolves this issue. It is now possible to update dependencies in terraform tests generated by tpgtools.
