### ISSUE TITLE
google_secret_manager_secret_version should export "version" attribute

### ISSUE THREAD

**Issue by albrechtflo-hg** [hashicorp/terraform-provider-google#9828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As Google more and more enables references to secrets e.g. in Cloud Run instances (e.g. for env variables or even for file mounts), an easy way should be offered to access the "version" of a given secret version managed by Terraform. 

If you just refer to "latest" in the Cloud Run .tf configuration, Terraform won't recognize that a change in the contents of the secret makes a redeployment of the Cloud Run necessary.

Currently, as a workaround, I extract the "version" (the version number) of the secret_version with the `regex` function from the ID of the secret_version:

```tf
env {
  name = "SPRING_APPLICATION_JSON"
  value_from {
    secret_key_ref {
      name = "app-config"
      key = regex("/([0-9]+)$", google_secret_manager_secret_version.app_config.id)[0]
    }
  }
}
```

This is not really concise and especially error-prone when doing copy-paste.

### New or Affected Resource(s)

* google_secret_manager_secret_version

### Potential Terraform Configuration

I'd recommend, well, a simple new exported attribute `version`:

```tf
env {
  name = "SPRING_APPLICATION_JSON"
  value_from {
    secret_key_ref {
      name = "app-config"
      key = google_secret_manager_secret_version.app_config.version
    }
  }
}
```

BTW, same applies to the "name" of the secret, which, in `secret_key_ref` must also be the **simple** name of the secret, but the `google_secret_manager_secret` resource only exports the **fully qualified** name. As this name is usually constant, it is easier to just set a constant string as in my example (`"app-config"`), but this is also error-prone if the secret is being renamed. But that would be another issue, I assume...

**Comment by melinath** [comment]
Here's a link to the API: https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions

I think that the request is to add support for the `replicationStatus` field, which includes `kmsKeyVersionName` as a nested subfield.

The key name is in `projects/*/locations/*/keyRings/*/cryptoKeys/*/versions/*` format; shortening that in output might be fine, but it would be worth double-checking what the best practice is.

Regarding the name field - there's an issue that `name` in the terraform provider is generally reserved for full paths. Possibly could make sense to add a secret_version_id field? Not sure what the best practice is.

**Comment by albrechtflo-hg** [comment]
@melinath You mention something about key rings and keys, but I do not really get the point here. Is this request here analogous to something from key management, or is there something mixed up?

**Comment by melinath** [comment]
@albrechtflo-hg apologies, I misread the initial request.

If I understand correctly now, what you're asking for is for a `version` field to be available on the resource, similar to the one on the data source. That seems doable. It would just be a convenience method that uses the same regex described in the workaround.

There's also a separate request for exporting the ["secretId" field](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets/create) - i.e. the short name of the secret, not the fully qualified secret.

Could you explain / link to the use case? i.e. What is secret_key_ref and what are you using it for?

**Comment by melinath** [comment]
docs for secretKeyRef: https://cloud.google.com/run/docs/reference/rest/v1/Container#secretkeyselector

**Comment by albrechtflo-hg** [comment]
Additional note: In the linked docs, they use "key" for this "latest" or integer value field. I am not sure if this is consistent throughout the Google API, but that is why I initially suggested "key" as name for the attribute. "version" is totally fine to me (and IMO semantically more clear), but maybe inconsistent to Google API docs - don't know if any rules for this apply here.

**Comment by melinath** [comment]
we'd want to use `version` on the secret version resource to be consistent with the datasource. :-) The secretKeyRef would still refer to it as `key` since that's how that API works.

**Comment by melinath** [comment]
@mitj04

**Comment by mitj04** [comment]
@melinath, just to make sure that we're on the same side, we've to add 2 output fields named 'version'(the version of the Secret) and 'secret_name'(the name of the Secret) which are derived from the fully qualified name using regex, correct?

**Comment by melinath** [comment]
I'm not entirely sure that we want the secret_name exposed from the `secret_version` resource - probably it would be best on the `secret` resource, and I'm not sure what the best name for it would be. We could leave it off for now - it seems like there's less clear value (probably since the secret name changes less frequently).
