### ISSUE TITLE
Import `google_compute_network_peering` resources fails for global networks

### ISSUE THREAD

**Issue by mans0954** [hashicorp/terraform-provider-google#9829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.80.0
```

### Affected Resource(s)

`google_compute_network_peering`

### Terraform Configuration Files

```tf
variable "mongo_atlas_network" {
  type = string
}

variable "redis_labs_network" {
  type = string
}

...
resource "google_compute_network" "ol-net01" {
  name                    = "ol-net01"
  auto_create_subnetworks = false
  description             = "Shared VPC"
}

resource "google_compute_network_peering" "mongo-atlas" {
  name         = "mongo-atlas-vpc-peering"
  network      = "${google_compute_network.ol-net01.self_link}"
  peer_network = var.mongo_atlas_network
}

resource "google_compute_network_peering" "redis-labs" {
  name         = "redis-labs-vpc-peering"
  network      = "${google_compute_network.ol-net01.self_link}"
  peer_network = var.redis_labs_network
}
```

### Panic Output

```
terraform import --var-file=stag.tfvars google_compute_network_peering.mongo-atlas mongo-atlas-vpc-peering
google_compute_network_peering.mongo-atlas: Importing from ID "mongo-atlas-vpc-peering"...
╷
│ Error: Error parsing network peering import format, expected: {project}/{network}/{name}
│ 
│ 
╵

terraform import --var-file=stag.tfvars google_compute_network_peering.redis-labs redis-labs-vpc-peering
google_compute_network_peering.redis-labs: Importing from ID "redis-labs-vpc-peering"...
╷
│ Error: Error parsing network peering import format, expected: {project}/{network}/{name}
│ 
│ 
```
╵

### Expected Behavior

I was expecting the `mongo-atlas-vpc-peering` peering to be imported to the `google_compute_network_peering.mongo-atlas mongo-atlas-vpc-peering` resource and the `redis-labs-vpc-peering` peering to be imported to the `google_compute_network_peering.redis-labs` resource.

### Actual Behavior

The resources are not imported due to the error above.

### Steps to Reproduce

1. `terraform import`

### Important Factoids

The external networks are formatted as follows:
```
mongo_atlas_network = "projects/<project>/global/networks/<network>"
redis_labs_network = "projects/<project>/global/networks/<network>"
```

### References

* #0000

**Comment by edwardmedia** [comment]
@mans0954 can you review the issue [here](https://github.com/hashicorp/terraform-provider-google/issues/9508) to see if that helps?

**Comment by mans0954** [comment]
> @mans0954 can you review the issue [here](https://github.com/hashicorp/terraform-provider-google/issues/9508) to see if that helps?

Do you mean
```
export GOOGLE_CLOUD_PROJECT=<my_project_id>
terraform import --var-file=stag.tfvars google_compute_network_peering.mongo-atlas mongo-atlas-vpc-peering
```
? That still gives the same error.

**Comment by mans0954** [comment]
I think the problem is probably here: https://github.com/hashicorp/terraform-provider-google/blob/e2e533f83c388fecbf51ae8ca541326b152cede0/google/resource_compute_network_peering.go#L320 - it's not allowing for the possibility of the extra `/global/` in the network name?

**Comment by edwardmedia** [comment]
@mans0954 can you try something like below?

```tf
resource "google_compute_network_peering" "mongo-atlas" {
}
```

> terraform import google_compute_network_peering.mongo-atlas project-name/network-name/peering-name

**Comment by mans0954** [comment]
@edwardmedia Thanks. Same response as before:
```
terraform import --var-file=stag.tfvars google_compute_network_peering.redis-labs redis-labs-vpc-peering
google_compute_network_peering.redis-labs: Importing from ID "redis-labs-vpc-peering"...
╷
│ Error: Error parsing network peering import format, expected: {project}/{network}/{name}
│ 
│ 
╵

terraform import --var-file=stag.tfvars google_compute_network_peering.mongo-atlas mongo-atlas-vpc-peering
google_compute_network_peering.mongo-atlas: Importing from ID "mongo-atlas-vpc-peering"...
╷
│ Error: Error parsing network peering import format, expected: {project}/{network}/{name}
│ 
│ 
╵
```

**Comment by edwardmedia** [comment]
@mans0954 do you have `project-name/network-name/` in your command?

> project-name/network-name/peering-name ( from example )

> redis-labs-vpc-peering  (from yours)

**Comment by mans0954** [comment]
> @mans0954 do you have `project-name/network-name/` in your command?

This works!

```
terraform import --var-file=stag.tfvars google_compute_network_peering.mongo-atlas my-project/my-network/mongo-atlas-vpc-peering
google_compute_network_peering.mongo-atlas: Importing from ID "my-project/my-network/mongo-atlas-vpc-peering"...
google_compute_network_peering.mongo-atlas: Import prepared!
  Prepared google_compute_network_peering for import
google_compute_network_peering.mongo-atlas: Refreshing state... [id=my-network/mongo-atlas-vpc-peering]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Thank you!
