### ISSUE TITLE
Terraform Support for ILB as next hop with tags

### ISSUE THREAD

**Issue by sankit2020** [hashicorp/terraform-provider-google#9833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add Terraform Support for ILB as next hop with tags

### New or Affected Resource(s)

This is an update of the routes resource. This allows users now to specify the nexthop ILB via the IP address to attach a tag to the route.

Documentation - https://cloud.google.com/load-balancing/docs/internal/ilb-next-hop-overview#ilb-next-hop-specify

**Comment by sankit2020** [comment]
https://buganizer.corp.google.com/issues/195934340

**Comment by juliocc** [comment]
I have a PR for this issue
