### ISSUE TITLE
Subordinate Certificate Authority CSR data source

### ISSUE THREAD

**Issue by drebes** [hashicorp/terraform-provider-google#9843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Subordinate Certificate Authority CSR data source

On GoogleCloudPlatform/magic-modules#5055 we fixed the creation of subordinate CAs. To continue work on supporting easier activation of those, we need a data source that can fetch the CSR of a subordinate CA that has been created but is still pending activation (`AWAITING_USER_ACTIVATION`). That CSR can then be used offline to issue a CA certificate for later activation.

### New or Affected Resource(s)

* google_privateca_certificate_authority_csr

### Potential Terraform Configuration

```tf
resource "google_privateca_certificate_authority" "sub" {
  ... 
  type = "SUBORDINATE"
}

data "google_privateca_certificate_authority_csr" "example" {
{
  certificate_authority = google_privateca_certificate_authority.sub.id
}

output "sub_csr" {
  value = google_privateca_certificate_authority_csr.example.pem_csr
}
```

### References

https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificateAuthorities/fetch

Internal Issue: [http://b/197098132](http://b/197098132)

* #9604

**Comment by sankit2020** [comment]
https://buganizer.corp.google.com/issues/197098132
