### ISSUE TITLE
Subordinate CA activation resource

### ISSUE THREAD

**Issue by drebes** [hashicorp/terraform-provider-google#9844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Subordinate CA activation resource

On GoogleCloudPlatform/magic-modules#5055 we fixed the creation of subordinate CAs. To continue work on supporting easier activation of those, we need a resource that can activate a subordinate CA that has been created but is still pending activation (`AWAITING_USER_ACTIVATION`). That signed sub CA cert is issued offline and then passed to this resource for activation.

### New or Affected Resource(s)

* google_privateca_certificate_authority_activation

### Potential Terraform Configuration

```tf
resource "google_privateca_certificate_authority" "sub" {
  ... 
  type = "SUBORDINATE"
}

resource "google_privateca_certificate_authority_activation" "example" {
{
  certificate_authority = google_privateca_certificate_authority.sub.id
  pem_ca_certificate = file("${path.root}/sub_ca_cert.pem")
  subordinate_config {
    pem_issuer_chain {
      pem_certificates = [
        file("${path.root}/root_ca_cert.pem"),
      ]
    }
  }  
}

```

### References

https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1/projects.locations.caPools.certificateAuthorities/activate

* #9604

**Comment by melinath** [comment]
b/259264561

**Comment by gfxcc** [comment]
Requested feature is added via https://github.com/GoogleCloudPlatform/magic-modules/pull/6161

**Comment by melinath** [comment]
👍  it looks like the PR only added the link to the issue without noting that it fixed the issue, so Github automation didn't automatically close this issue. Thanks!
