### ISSUE TITLE
google_cloud_identity_group_membership fieldViolations "MEMBER role must be specified"

### ISSUE THREAD

**Issue by cathex-matt** [hashicorp/terraform-provider-google#9855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.2.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/google v3.80.0
+ provider registry.terraform.io/hashicorp/google-beta v3.80.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

* google_cloud_identity_group_membership

### Terraform Configuration Files

```tf
resource "google_cloud_identity_group_membership" "this" {
  provider = google

  for_each = { for member in local.members_list: "customers/${member.customer_id}/${member.group_email}/${member.member_email}/${member.member_privilege}" => member }

  group = each.value.group_id
  preferred_member_key {
    id = each.value.member_email
  }
  roles {
    name = each.value.member_privilege
    #name = "MEMBER"
  }
}
```

### Expected Behavior

Terraform should have run without throwing any field violation error.

### Actual Behavior

Terraform is throwing a field violation error while I pass an authorised value (`MEMBER`) and the group memberships are correctly updated.
Also interesting to note that a 2nd apply would fail too throwing a: `Error creating GroupMembership: googleapi: Error 409: Error(4003): Cannot create membership 'user.one@ourdomain.io' in 'groups/00gjdgxs3mrij3o' because it already exists.`

### Steps to Reproduce

1. Pass any membership role to any user using a for_each to pass the role dynamically from a list and using the upper() function to convert `member` to `MEMBER`, `owner` to `OWNER`

2. `terraform apply`

### Important Factoids

I'm authenticated using a service account.
I enabled the cloud identity api for the project.
I tried with either the google provider or the google-beta one in their last version.

**Comment by edwardmedia** [comment]
@cathex-matt can you share the full debug log?

**Comment by cathex-matt** [comment]
> @cathex-matt can you share the full debug log?

Sorry for the late reply. Here it is: https://gist.github.com/cathex-matt/58ee0802ee0cc18200af216f5c3ce5a5

**Comment by cathex-matt** [comment]
@edwardmedia 
I fixed it myself after revisiting how I was architecting my module. It was on my side, certainly around how I was passing namespaces or roles to the membership resource... Sorry for the inconvenience.
