### ISSUE TITLE
KMS Secret Ciphertext requires more permissions than it should

### ISSUE THREAD

**Issue by Illidanek** [hashicorp/terraform-provider-google#9857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 1.0.5 with Google provider 3.80.0

### Affected Resource(s)

google_kms_secret_ciphertext

### Expected Behavior

The resource should encrypt the plaintext password and provide me with an option to view this output

### Actual Behavior

The following error:

"Error when reading or editing KMSSecretCiphertext "my_path_here" googleapi: Error 403: Permission 'cloudkms.cryptoKeys.get' denied on resource 'my_path_here'"

The resource exists for sure, because when I run "gloud kms encrypt" with the same user as the one used in terraform, it works and encrypts the plaintext.

According to the documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_secret_ciphertext (under "API documentation"), this resource should only require the `cloudkms.cryptoKeyVersions.useToEncrypt` permission, but here it is requesting to have an additional one, which is completely unnecessary for encrypting.

If I am understanding correctly, this resource is forcing users to reduce the security of their system? Why is this permission being requested when "gcloud kms encrypt" does not need it?

### Steps to Reproduce

1. Set up a user which has cloudkms.cryptoKeyVersions.useToEncrypt permissions on a key
2. Use the google_kms_secret_ciphertext resource on that key with some random plaintext
3. `terraform plan` or apply

**Comment by edwardmedia** [comment]
@Illidanek you know how Terraform works, right? It needs a local/remote copy of the state. Do you think it can avoid `read` in order to obtain your settings from the API?

**Comment by edwardmedia** [comment]
@Illidanek does [that]([url](https://github.com/hashicorp/terraform-provider-google/issues/9857#issuecomment-901997537)) make sense?

**Comment by Illidanek** [comment]
To be honest I'm not at all an expert on terraform. I saw the source code for the resource and saw that for some reason it does a Get to the API despite the fact that it would seem all it needs is to do a Post with the encryption.

If for some reason there's no way around that, we should probably request to have this changed in the documentation, as there it says only encrypt permissions are necessary (like for the standard encryption command)

**Comment by edwardmedia** [comment]
@Illidanek I guess the `documentation` you referred [here](https://github.com/hashicorp/terraform-provider-google/issues/9857#issuecomment-904089869) is for APi's. That is separate and that is specific for one API request. Terraform provider is different, and usually it does need to call `get` to sync for the local state. Closing the issue now. Feel free if you need further disccusion.
