### ISSUE TITLE
Exporting GOOGLE_CREDENTIALS with a JSON Object does not work

### ISSUE THREAD

**Issue by Felistas** [hashicorp/terraform-provider-google#9858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.0.0

### Affected Resource(s)

* all

### Terraform Configuration Files

We have a requirement to run our terraform scripts that create our gcp resources in the pipeline. Exporting the JSON object of our service account key to GOOGLE_CREDENTIALS does not authenticate terraform. How do we properly do this so as to run our scripts in the pipeline

PS. We dont want to check out our credential file to git as this is not ideal from a security perspective. 

### Expected Behavior

Terraform init to be successfull

### Actual Behavior

Error: storage.NewClient() failed: dialing: invalid character 't' looking for beginning of object key string│

### Steps to Reproduce

1. Create Service Account Key and obtain the credentials in a JSON formart
2. Export the contents of the credential file you get to `GOOGLE_CREDENTIALS `
3. Run `terraform init`

**Comment by upodroid** [comment]
Hi

You need to write the key to disk, usually in /tmp so the CI system that you are using deletes the key after each run.

Something like this:

Load the json key as a GCLOUD_SERVICE_KEY environment variable in your CI/CD system.

```sh
echo "$GCLOUD_SERVICE_KEY" > /tmp/key.json
export GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
terraform init
```

Thank you

**Comment by Felistas** [comment]
thanks!
