### ISSUE TITLE
The instances element of compute_instance_group does not work with ids on resource change

### ISSUE THREAD

**Issue by xaxo05** [hashicorp/terraform-provider-google#9869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

% terraform -v
Terraform v1.0.2
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.0.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* google_compute_instance_group

### Terraform Configuration Files

```tf
resource "google_compute_instance_group" "instance-group" {
  project   = module.project.project_id
  name      = "instance-group-${local.zone}"
  zone      = local.zone
  instances = [for e in module.vault : e.id]

  named_port {
    name = "https"
    port = "443"
  }
}
```

### Debug Output

╷
│ Error: Error invalid instance URLs: [projects/my-project-4348/zones/europe-west3-a/instances/vault-2-europe-west3-a-4f77dd7fa97475a5 projects/my-project-4348/zones/europe-west3-a/instances/vault-1-europe-west3-a-4f77dd7fa97475a5 projects/my-project-4348/zones/europe-west3-a/instances/vault-0-europe-west3-a-4f77dd7fa97475a5]
│ 
│   with google_compute_instance_group.instance-group,
│   on backend.tf line 1, in resource "google_compute_instance_group" "instance-group":
│    1: resource "google_compute_instance_group" "instance-group" {
│ 
╵

### Expected Behavior

The instance group should be updated with the new set of
instances when these are changed.

### Actual Behavior

The old instances are removed from the instance group, however,
the new instances are not added to the instance group.

### Steps to Reproduce

1. Create an instance group instance elements referenced by id.
2. Apply your configuration.
3. Update the instance elements so that they need to be removed
and new ones need to be generated.
4. Apply your configuration.
5. Observe an error.

The problem seems to be related to the following pieces of code:

https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_instance_group.go#L332-L337

https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_instance_group.go#L131

where URLs instead of ids of the instances are expected.

However, the documentation here

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group

states that ids are accepted:

instances - (Optional) List of instances in the group. They should be given as either self_link or id. When adding instances they must all be in the same network and zone as the instance group.

### References

* #0000

**Comment by edwardmedia** [comment]
@xaxo05 can you share the full debug log?

**Comment by edwardmedia** [comment]
@xaxo05 is this still an issue?

**Comment by edwardmedia** [comment]
@xaxo05 closing assuming this is no longer an issue
