### ISSUE TITLE
adding consumer_accept_lists cause service attachment to be recreated

### ISSUE THREAD

**Issue by sfc-gh-emonsef** [hashicorp/terraform-provider-google#9877]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform version: 0.13.5
Provider version:  Tested on v3.80

### Affected Resource(s)

google_compute_service_attachment

### Terraform Configuration Files

```tf
resource "google_compute_service_attachment" "private_service_attachment" {
  provider = google-beta

  name   = local.add_on_vpc_subnetwork_name["psc-nat"][local.region]
  region = local.region

  description = "a service attachment configured with Terraform"
  project     = local.deployment_project_id

  enable_proxy_protocol = true
  connection_preference = "ACCEPT_MANUAL"
  nat_subnets = [
    local.add_on_vpc_subnetwork["psc-nat"][local.region]
  ]

  target_service = local.private_nginx_forwarding_rule

  consumer_accept_lists {
    project_id_or_num = local.private_approved_ids[0][0]
    connection_limit  = local.private_approved_ids[0][1]
  }
  consumer_accept_lists {
    project_id_or_num = local.private_approved_ids[1][0]
    connection_limit  = local.private_approved_ids[1][1]
  }

}
```

### Expected Behavior
terraform-provider-google-beta has recently added feature for MANUAL_APPROVAL. However, when new `consumer_accept_lists` is added, instead of updating the service attachment in-place, it will try to destroy/create a new resource.  

### Actual Behavior

Provider destroys and creates a new service attachment while all it needs is in-place update

### Steps to Reproduce

1. Add a new consumer_accept_lists to service attachment resource . ex:
```
 consumer_accept_lists {
    project_id_or_num = local.private_approved_ids[1][0]
    connection_limit  = local.private_approved_ids[1][1]
  }
```
2. Run a plan and provider will destroy/create a new service attachment.  

OUTPUT of plan:
```
 # google_compute_service_attachment.private_service_attachment must be replaced
-/+ resource "google_compute_service_attachment" "private_service_attachment" {
      ~ connected_endpoints   = [] -> (known after apply)
        connection_preference = "ACCEPT_MANUAL"
      - consumer_reject_lists = [] -> null
        description           = "a service attachment configured with Terraform"
        enable_proxy_protocol = true
      ~ id                    = "projects/service-proivder-project-id/regions/us-central1/serviceAttachments/psc-nat-cidr-us-central1" -> (known after apply)
        name                  = "psc-nat-cidr-us"
        nat_subnets           = [
            "https://www.googleapis.com/compute/v1/projects/service-proivder-project-id/regions/us-central1/subnetworks/psc-nat-cidr-us",
        ]
        project               = "service-proivder-project-id"
      ~ region                = "https://www.googleapis.com/compute/v1/projects/service-proivder-project-id/regions/us-central1" -> "us-central1"
      ~ self_link             = "https://www.googleapis.com/compute/v1/projects/service-proivder-project-id/regions/us-central1/serviceAttachments/psc-nat-cidr" -> (known after apply)
      ~ target_service        = "https://www.googleapis.com/compute/v1/projects/service-proivder-project-id/regions/us-central1/forwardingRules/us-central1-privatelink-forwarding-rule-us-central1" -> "projects/service-proivder-project-id/regions/us-central1/forwardingRules/privatelink-forwarding-rule"

        consumer_accept_lists {
            connection_limit  = 2
            project_id_or_num = "psc-cosumer1_project_id"
        }
      + consumer_accept_lists { # forces replacement
          + connection_limit  = 4 # forces replacement
          + project_id_or_num = "psc-cosumer2_project_id" # forces replacement
        }
    }
```

**Comment by edwardmedia** [comment]
All fields are ForceNew() right now. Update support is needed for certain fields. API supports PATCH 

https://cloud.google.com/compute/docs/reference/rest/beta/serviceAttachments/patch

**Comment by rileykarson** [comment]
This is a known behaviour and will be addressed in https://github.com/hashicorp/terraform-provider-google/issues/9647
