### ISSUE TITLE
Cloud Build - Add approval config

### ISSUE THREAD

**Issue by rotilho** [hashicorp/terraform-provider-google#9880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud Build added support to approvals and already released to their rest API as you can see here https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers#BuildTrigger

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "filename-trigger" {
  trigger_template {
    branch_name = "master"
    repo_name   = "my-repo"
  }

  substitutions = {
    _FOO = "bar"
    _BAZ = "qux"
  }

  approval_required = true

  filename = "cloudbuild.yaml"
}
```

**Comment by simonkarman** [comment]
Any indication on if/when this will be added?

**Comment by parekhnaman** [comment]
Any update on feature release ?

**Comment by ismailsimsek** [comment]
Any update ?

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_approvalconfig). I will be submitting a PR soon

**Comment by wyardley** [comment]
Thanks again @abhinavrau (cc: @slevenick @shuyama1)
