### ISSUE TITLE
DNS record set - can't create AAAA record as rrset data remains empty while adding previously known ip address

### ISSUE THREAD

**Issue by tgirier** [hashicorp/terraform-provider-google#9882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v3.65.0
+ provider registry.terraform.io/hashicorp/google-beta v3.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* google_dns_record_set

### Terraform Configuration Files

Full configuration :
[platform copy.zip](https://github.com/hashicorp/terraform-provider-google/files/7032072/platform.copy.zip)

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

# DNS Zone

resource "google_dns_managed_zone" "dns_zone" {
  name        = "demo"
  project     = var.project
  dns_name    = "meedl.io."
  description = "Zone used for demonstration"
}

# DNS Records

resource "google_dns_record_set" "camunda_ee_dns_record" {
  name         = "camunda-ee.meedl.io."
  project      = var.project
  managed_zone = google_dns_managed_zone.dns_zone.name
  type         = "AAAA"
  rrdatas      = [google_compute_global_address.camunda_ee_ip.address]
  ttl          = 86400
}


resource "google_compute_global_address" "camunda_ee_ip" {
  name         = "camunda-ee-ip"
  project      = var.project
  address_type = "EXTERNAL"
  ip_version   = "IPV6"
}

```

### Debug Output

https://gist.github.com/tgirier/533ba2ae778ba261d0287daa0501988c

### Expected Behavior

The created IP address should be passed as rrdatas upon the record set creation.
Actually this behaviour is working when applying a "small" terraform configuration.
But when applying a large config it produces an inconsistent plan.

### Actual Behavior

The rrdatas field is empty on each apply.
The dns record set is not created.

### Steps to Reproduce

1. `terraform apply`
2. Enter yes

### Important Factoids

I'm authenticating as a user.

### References

* #0000

**Comment by megan07** [comment]
Hi @tgirier ! Is this still an issue?

**Comment by megan07** [comment]
Closing assuming this is no longer an issue
