### ISSUE TITLE
google_cloudbuild_trigger add fields `sourceToBuild` and `GitFileSource`

### ISSUE THREAD

**Issue by frehov** [hashicorp/terraform-provider-google#9883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Cloud build has updated their [api spec](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers) , and added the fields `sourceToBuild` and `GitFileSource`.
In the referenced issue, the webhook trigger needs these fields to set up a working trigger.

The property `GitfileSource` can most likely be inferred from `filename` and `sourceToBuild`, as the `sourceToBuild` contains 75% of what's needed in the GitFileSource, combining with filename, it should provide the full field.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_secret_manager_secret" "sanity_webhook_secret" {
  secret_id = "sanity_webhook_secret"
  labels    = {}

  replication {
    automatic = true
  }
}

data "google_secret_manager_secret_version" "sanity_webhook_secret_content" {
  secret = google_secret_manager_secret.sanity_webhook_secret.id
}

resource "google_cloudbuild_trigger" "website-sanity-deploy-dev" {
   provider    = google
   name        = "sanity-webhook-trigger-dev"
   description = "Trigger build on changes from sanity"
   filename    = ".cloudbuild/gatsby_sanity_build.yml"

   build_source = {
     uri = "<path to github repo>"
     ref = "" # this should probably be branch, and instead add "/refs/heads/<branchname>" in code, no regex allowed.
     type = "GITHUB"
   }

   webhook_config {
     secret = data.google_secret_manager_secret_version.sanity_webhook_secret_content.name
   }

   substitutions = {
     _DIR = "website/"
     _BUILD_ENV = "development"
     _NODE_VERSION = "12-alpine3.12"
     _SUPPRESS_OUTPUT = "true"
   }
}

```

### References

* #9827

**Comment by pattishin** [comment]
Would like to bump this up as I'm facing a similar use-case as @jcanseco to use this in tandem with `pubsub_config` Anyway to get a clear picture of where this issue sits in the priority queue for the team? 

Ref: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger.GitFileSource

**Comment by enchorb** [comment]
Bump, need this for `webhook_config`. Currently need to manually specify the repo to build from once a webhook event is received

**Comment by abhinavrau** [comment]
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon

**Comment by mariomachado94** [comment]
@abhinavrau I too was working on this, oh no.

**Comment by abhinavrau** [comment]
Sorry @mariomachado94. I guess we both had a need to fix this long outstanding issue. Please let me know thoughts on my solution and how it could be better. I would really appreciate it. Fingers crossed if my solution passes all the tests!
