### ISSUE TITLE
GCP os config patch metadata keep trying to change 

### ISSUE THREAD

**Issue by matdtr** [hashicorp/terraform-provider-google#9897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

I am trying to understand why this is happening. On TF 0.14 when I do terraform apply everything is clean and it returns with no infrastructure change, now that i have migrated to TF 0.15 i get all these changes. 

On TF 0.15, with the GCP provider version of: v3.65.0 it spits out a bunch of scary looking changes about last execute time.

### Terraform Version
0.15.4

### Affected Resource(s)
```tf
* Note: Objects have changed outside of Terraform
1469 Terraform detected the following changes made outside of Terraform since the
1470 last "terraform apply":
1471   # module.project_it.google_os_config_patch_deployment.default-patch has been changed
   ~ resource "google_os_config_patch_deployment" "default-patch" {
         id                  = "projects/XXXXXXXXX/patchDeployments/default-patch"
       ~ last_execute_time   = "2021-08-17T00:00:00.288585Z" -> "2021-08-24T00:00:00.565212Z"
         name                = "projects/447798402700/patchDeployments/generali-default-patch"
       ~ update_time         = "2021-08-17T00:00:00.302442Z" -> "2021-08-24T00:00:00.579492Z"
         # (4 unchanged attributes hidden)
       ~ recurring_schedule {
           ~ last_execute_time = "2021-08-17T00:00:00.288585Z" -> "2021-08-24T00:00:00.565212Z"
           ~ next_execute_time = "2021-08-24T00:00:00Z" -> "2021-08-31T00:00:00Z"
             # (3 unchanged blocks hidden)
         }
         # (3 unchanged blocks hidden)
     }

```
### Terraform Configuration Files

```tf
resource "google_os_config_patch_deployment" "default-patch" {
  patch_deployment_id = "default-patch"
  project             = google_project.project.project_id

  instance_filter {
     group_labels {
      labels = {
        patch = "true"
      }
    }
  }

  patch_config {
    reboot_config = "DEFAULT"
    
    zypper {
      categories = ["security"]
    }
    yum {
      security = true
    }
    windows_update {
      classifications = ["CRITICAL", "SECURITY", "DEFINITION"]
    }
  }

  duration = "3600s"

  recurring_schedule {
    time_zone {
      id = "Europe/Rome"
    }

    time_of_day {
      hours = 02
      minutes = 00
      seconds = 00
      nanos = 00
    }

    weekly {
      day_of_week = "TUESDAY"
    }
  }

  rollout {
    mode = "ZONE_BY_ZONE"
    disruption_budget {
      fixed = 1
    }
  } 

} 

```

### Expected Behavior

I expect that, that long message about execution times change shouldn't come up.

### Actual Behavior

A lot of changes are happening to the execution times metadata

### Steps to Reproduce

1. `terraform plan`

**Comment by edwardmedia** [comment]
@matdtr can you repro this issue repeatedly?

**Comment by matdtr** [comment]
Hi @edwardmedia, 

Actually once we did the apply, terraform doesn't not pop up the changes anymore. Tonight it should run again (on GCP) so i will see if terraform detect some changes again.

BR

**Comment by edwardmedia** [comment]
@matdtr the diffs show in the plan. Which suggestion (below) did you see?

> Plan: 1 to add, 0 to change, 1 to destroy.

> Plan: 0 to add, 1 to change, 0 to destroy.

> No changes. Your infrastructure matches the configuration.

**Comment by matdtr** [comment]
Hi @edwardmedia,

I get:  "No changes. Your infrastructure matches the configuration". 
All the metadata changes are under "Note: Objects have changed outside of Terraform"

**Comment by edwardmedia** [comment]
@matdtr What this means is that Terraform has detected the difference but they can be ignored. Since you have got `No changes. Your infrastructure matches the configuration`, it should not be seen as `keep trying to change`, unless I misunderstood the `issue`

**Comment by matdtr** [comment]
@edwardmedia ok understood. Is there a way to suppress these info to show up in the terraform plan?

**Comment by edwardmedia** [comment]
@matdtr I don't think so. For certain reasons, these info are useful. For regular users or automation processes, the last line is more important. Closing this issue now. Feel free to reopen if you want to continue the conversation. Thank you
