### ISSUE TITLE
Bypass Cache on Request Header for Backend Bucket

### ISSUE THREAD

**Issue by brianpham** [hashicorp/terraform-provider-google#9899]
I was wondering if there is a way to add a header name to the bypassing cache option for the google_compute_backend_bucket resource. https://cloud.google.com/cdn/docs/caching#bypassing-cache

It doesn't seem to be supported but wanted to double check https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket

**Comment by edwardmedia** [comment]
@brianpham this resource supports certain cache features. Can you checkout if `cache_mode` works for you?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket#cache_mode

**Comment by edwardmedia** [comment]
@brianpham does that help?

**Comment by brianpham** [comment]
@edwardmedia Doesn't seem like it. There only seems to be 3 options for the cache mode. I actually want to bypass the cache setting a HTTP header using something like this https://cloud.google.com/cdn/docs/caching#bypassing-cache

**Comment by brianpham** [comment]
Thanks! Created an enhancement #9961
