### ISSUE TITLE
google_artifact_registry_repository seems to ignore the 'depends_on' attribute?

### ISSUE THREAD

**Issue by jankrynauw** [hashicorp/terraform-provider-google#9902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Using `hashicorp/terraform:light` image as part of a build process.

### Affected Resource(s)

* google_artifact_registry_repository

### Terraform Configuration Files

```tf
resource "google_project" "my_project" {
  name = "My Project Name"
  project_id = "my-project-id-abc"
  billing_account = "BILLING-ACCOUNT-ID"
}

resource "google_artifact_registry_repository" "my_ar" {
  provider = google-beta
  format = "DOCKER"
  repository_id = "myreponame"
  location = "europe-west1"
  project = google_project.my_project.project_id
  depends_on = [google_project_service.artifactregistry_googleapis_com]
}

resource "google_project_service" "artifactregistry_googleapis_com" {
  project = google_project.my_project.project_id
  service = "artifactregistry.googleapis.com"
}
```

### Expected Behavior

Is the role of the `depends_on = [google_project_service.artifactregistry_googleapis_com]` attribute not supposed to wait for everything to be ready before creating the artifact repository?

Are there other dependencies one needs to add to the `depends_on` attribute?

### Actual Behavior

The above terraform configuration almost always fails on first the terraform apply with the following error message:

```
Error: Error creating Repository: googleapi: Error 403: Permission 'artifactregistry.repositories.create' denied on resource '//artifactregistry.googleapis.com/projects/my-project-id-abc/locations/europe-west1' (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "artifactregistry.googleapis.com",
    "metadata": {
      "permission": "artifactregistry.repositories.create",
      "resource": "projects/my-project-id-abc/locations/europe-west1"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
```

Running the same command immediately again always succeeds with the following message:

```
Terraform will perform the following actions:

  # google_artifact_registry_repository.my_ar will be created
  + resource "google_artifact_registry_repository" "my_ar" {
      + create_time   = (known after apply)
      + format        = "DOCKER"
      + id            = (known after apply)
      + location      = "europe-west1"
      + name          = (known after apply)
      + project       = "my-project-id-abc"
      + repository_id = "myreponame"
      + update_time   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
google_artifact_registry_repository.my_ar: Creating...
google_artifact_registry_repository.my_ar: Still creating... [10s elapsed]
google_artifact_registry_repository.my_ar: Creation complete after 12s [id=projects/my-project-id-abc/locations/europe-west1/repositories/myreponame]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

### Steps to Reproduce

1. `terraform apply` which fails
2. `terraform apply` completes successfully on the 2nd attempt.

**Comment by edwardmedia** [comment]
@jankrynauw provision of some resources may take extra long time to complete. This might be a case. Can you check if implementing [sleep](https://github.com/hashicorp/terraform-provider-google/issues/6377#issuecomment-628978514) helps?

**Comment by edwardmedia** [comment]
@jankrynauw is this still an issue?

**Comment by edwardmedia** [comment]
@jankrynauw closing assuming this is no longer an issue
