### ISSUE TITLE
Support Api Gateway on google_compute_region_network_endpoint_group

### ISSUE THREAD

**Issue by guibirow** [hashicorp/terraform-provider-google#9907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google has release the [Api Gateway](https://cloud.google.com/api-gateway/docs/about-api-gateway) service to control access to resources like Cloud Functions, Cloud Run and AppEngine.
In order to setup custom domains, an External Https Load Balancer and a Serverless Network Endpoint Group need to be created, as described [here](https://cloud.google.com/api-gateway/docs/gateway-load-balancing).

To create the Serverless Network Endpoint Group, the [docs suggest ](https://cloud.google.com/api-gateway/docs/quickstart)the following command:

```
//create a gateway GATEWAYNAME and then...

gcloud beta compute network-endpoint-groups create NEG_NAME \
   --region=europe-west2 \
   --network-endpoint-type=serverless \
   --serverless-deployment-platform=apigateway.googleapis.com \
   --serverless-deployment-resource=GATEWAYNAME
```

### New or Affected Resource(s)

[*google_compute_region_network_endpoint_group*](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_region_network_endpoint_group) 

The Serverless Network Endpoint Group works exactly like the others used by functions and currently supported by the resource as follow:

```tf
resource "google_compute_region_network_endpoint_group" "function_neg" {
  name                  = "function-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"
  cloud_function {
    function = google_cloudfunctions_function.function_neg.name
  }
}
```

### Potential Terraform Configuration

```tf
resource "google_compute_region_network_endpoint_group" "gateway_neg" {
  name                  = "gateway-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "europe-west2"
  api_gateway {
    gateway = "GATEWAYID"
  }
}
```
or using serverless_deployment to match the new [rest api definition](https://cloud.google.com/compute/docs/reference/rest/beta/globalNetworkEndpointGroups)

```tf
resource "google_compute_region_network_endpoint_group" "gateway_neg" {
  name                  = "gateway-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "europe-west2"
  serverless_deployment {
    "platform": "apigateway.googleapis.com",
    "resource": "GATEWAYID"
  }
}
```

### References

- https://cloud.google.com/api-gateway/docs/about-api-gateway
- https://cloud.google.com/api-gateway/docs/gateway-load-balancing
- https://cloud.google.com/api-gateway/docs/quickstart
- https://cloud.google.com/compute/docs/reference/rest/beta/globalNetworkEndpointGroups

**Comment by roaks3** [comment]
Per https://github.com/hashicorp/terraform-provider-google/issues/10729, this is now implemented in the beta provider.
