### ISSUE TITLE
Since provider 3.80 one get :  Provider configuration not present

### ISSUE THREAD

**Issue by mldmld68** [hashicorp/terraform-provider-google#9910]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform 
Version 0.13.7

### Affected Resource(s)
google_project_iam_member

### Terraform Configuration Files
```terraform {
  required_version = ">= 0.13"
  required_providers {
    google = {
      source = "registry.terraform.io/-/google"
      source = "hashicorp/google"
      version = "~> 3.80.0"
    }
    google-beta = {
      source = "hashicorp/google-beta"
      # version = "~> 3.80.0"
    }
    null = {
      source = "hashicorp/null"
      version = "~> 3.1.0"
    }
    random    = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
    template  = {
      source  = "hashicorp/template"
      version = "~> 2.2.0"
    }
  }
}

provider "google" {
      region = "europe-west1"
}

provider "google-beta" {
      region = "europe-west1"
}
```

### Expected Behavior

Terraform plan do not generate errors

### Actual Behavior

Error: Provider configuration not present
To work with google_project_iam_member.sas[0] its original provider
configuration at provider["registry.terraform.io/-/google"] is required, but
it has been removed. This occurs when a provider configuration is removed
while objects created by that provider still exist in the state. Re-add the
provider configuration to destroy google_project_iam_member.sas[0], after
which you can remove the provider configuration again.
Cleaning up file based variables

### Steps to Reproduce

Not sure how this issue may be reproduced. But here what we know : 

1. Terraform plan/apply with terraform 0.13.7 and a Google provider 3.79 or a little less

2. Terraform plan/apply with terraform 0.13.7 and a Google provider >=3.80.

1. `terraform apply`

### Important Factoids

The workaround when meeting this issue is to fix the Google and Google-beta provider to 3.56 then terraform plan/apply,
After that, one may use a provider > 3.80 without issue

### References

* #0000

**Comment by megan07** [comment]
Hi @mldmld68 ! Is this still an issue?

**Comment by megan07** [comment]
Closing  assuming this is no longer an issue
