### ISSUE TITLE
google_cloud_identity_group - Enabling the 'Allow Members Outside Your Organization' setting to be enabled on creation

### ISSUE THREAD

**Issue by Forcebyte** [hashicorp/terraform-provider-google#9925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In our org, we use this terraform GCP module to create and manage groups and group memberships

We've noticed that during deployment, if we define or add groups in a multi-organizational GCP tenant (For example, groups where members from `google.com` and `alphabet.com` are both registered via the same group) we typically get errors

To fix this, after the first TF Apply when creating a new group, a person manually has to select "Allow members outside your organization" to fix this, related GCP support article can be found here (https://support.google.com/a/answer/9007750?hl=en) at the bottom

![image](https://user-images.githubusercontent.com/44551053/131045770-dc159783-0647-4f87-8db8-731ad0dece48.png)

### New or Affected Resource(s)

* google_cloud_identity_group

### Potential Terraform Configuration

To fix this, it would probably be ideal to enable a similar optional parameter inside of the `group_key` dict that dictates this setting, as it is an individual boolean that defaults to false within Googles API
```tf
resource "google_cloud_identity_group" "cloud_identity_group_basic" {
  display_name         = "my-identity-group"
  initial_group_config = "WITH_INITIAL_OWNER"

  parent = "customers/A01b123xz"

  group_key {
      id = "my-identity-group@example.com"
      allow_external_access = "true"
  }

  labels = {
    "cloudidentity.googleapis.com/groups.discussion_forum" = ""
  }
}
.
```

According to reference documents, the 'group' resource uses a similar attribute mapping (see https://cloud.google.com/identity/docs/reference/rest/v1beta1/groups#Group)

**Comment by anderson-marques** [comment]
Please keep this ticket open. @Forcebyte is right. The way the provider works requires manual intervention before being able to add non Cloud Identity users in my groups. Since there is no other resource to manage groups, and we have that option in the console, it do make sense to have the same in Terraform. Otherwise, the automation is broken.

**Comment by upodroid** [comment]
@rileykarson We can close this issue.

Right now, there is no feature parity between 

https://cloud.google.com/identity/docs/reference/rest/v1beta1/groups

**Comment by upodroid** [comment]
Have a look at https://github.com/hashicorp/terraform-provider-googleworkspace

**Comment by Forcebyte** [comment]
Ah bummer, I see now that they are two different API

Closing issue, thanks for the explanation and workaround @upodroid!
