### ISSUE TITLE
google_container_registry_repository yields invalid repository url

### ISSUE THREAD

**Issue by partywave** [hashicorp/terraform-provider-google#9928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.5 on darwin_amd64

### Affected Resource(s)

* google_container_registry_repository (Data Source)

### Terraform Configuration Files

```tf
data "google_container_registry_repository" "default" {
  region = "europe-west3"
}
```

### Expected Behavior

`data.google_container_registry_repository.default.repository_url` should return `eu.gcr.io`

### Actual Behavior

`data.google_container_registry_repository.default.repository_url` returns `europe-west3.gcr.io`

### Steps to Reproduce

1. `terraform plan` will show the invalid url

### Important Factoids

Valid GCR endpoints are listed here: https://cloud.google.com/container-registry/docs/pushing-and-pulling

**Comment by melinath** [comment]
Try specifying `eu` as the region, as documented here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_registry_repository#region

Unfortunately, there's not a future-proof way for us to validate this.
