### ISSUE TITLE
Big query dataset 

### ISSUE THREAD

**Issue by armaan111** [hashicorp/terraform-provider-google#9929]
Hi Team,
I want to create a BIg query dataset and want to use the default google managed encryption keys, what snippet of code shall i write to achieve the same

**Comment by armaan111** [comment]
Okay thanks. I more point is there is any way where we can verify it is
using default encryption.


Regards,
Armaan Mahajan

**Comment by edwardmedia** [comment]
@armaan111 can you export the data and verify it at the new location?

https://cloud.google.com/bigquery/docs/exporting-data

**Comment by edwardmedia** [comment]
@armaan111 closing this question then
