### ISSUE TITLE
google_compute_instance_group does not properly update when a constituent google_compute_instance is re-created because of a taint

### ISSUE THREAD

**Issue by qwerty1979bg** [hashicorp/terraform-provider-google#9930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.81.0
```

### Affected Resource(s)

`google_compute_instance_group`

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.81.0"
    }
  }
}

provider "google" {
  # Configuration options
  project = "PROJECT"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_compute_instance_group" "test" {
  name = "test"

  instances = google_compute_instance.test.*.self_link
}

resource "google_compute_instance" "test" {
  name         = "test"
  machine_type = "e2-small"

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network = "default"
  }
}
```

### Debug Output

https://gist.github.com/4e955261dd2937af6e7d17d6387fb9d1
https://gist.github.com/be64b70cf04486ee337e7b1c1eba08fa
https://gist.github.com/e0e5b91031cfdc9aa7eb42f714932ae5
https://gist.github.com/6af789fd0378d5af7ea04d772d18ca19
https://gist.github.com/39fda2428b3f940278a5702a5363a8a2
https://gist.github.com/aa31ca07fd294da946825408e1fa17e2
https://gist.github.com/2503f9cadc09dacc2d5435389abc1c0d
https://gist.github.com/74317bb4838ead470047960045275f0f

### Expected Behavior

Terraform should have updated `google_compute_instance_group` as it planned.

### Actual Behavior

Terraform needed one more apply to update the `google_compute_instance_group` resource.

### Steps to Reproduce

1. `terraform apply` -> resources are created
2. `terraform apply` -> no changes planned changes
3. `terraform taint google_compute_instance.test`
4. `terraform apply` -> compute instance gets recreated and instance group should be updated in place
5. `terraform state show google_compute_instance_group.test` -> it supposedly contains the proper data
6. `terraform apply` -> the instance group needs to be "changed" again
7. `terraform apply` -> finally, no changes planned
8. `terraform state show google_compute_instance_group.test` -> the data is still the same as in step 4

### Important Factoids

The "google_compute_instance_group" resource requires the IDs / self links of the constituent "compute_instance" resources.
However, the ID / self link of the instances are the same, even if the compute instance is actually recreated.
(for example: https://www.googleapis.com/compute/v1/projects/PROJECT/zones/us-central1-c/instances/INSTANCE_NAME)

If you replace an instance with "terraform taint", Terraform knows it will also perform the change in the instance group. It removes the old ID, but when it has to add the new ID, it figures out that the new ID is the same as the previous and therefore it does not add it to the instance group. This gets fixed on a subsequent apply.

I am not sure if this is a bug in the Google provider or some limitation in the Terraform core around how change detection during "taint" works.

**Comment by zraider7** [comment]
Just to throw my hat in the ring. I am also hitting this issue, but more specifically 'google_compute_instance_group' fails to re-add a re-created instance (with the same name) back to it's instances attribute.

**Comment by rileykarson** [comment]
This is a variant of https://github.com/hashicorp/terraform-provider-google/issues/1938. The new `replace_triggered_by` feature should work if recreating the instance group resource is acceptable. The issue here is that Terraform doesn't give the provider enough information to take any action.

**Comment by Chupaka** [comment]
Recreating the instance group is not acceptable. Do we expect some "update_triggered_by" in near future?

**Comment by paulspiegel** [comment]
Recreating the instance group using replace_triggered_by is problematic if you have load balancer backends pointing to the instance group.  You run into a resourceInUseByAnotherResource from the backend service.  Adding create_before_destroy doesn't work because that forced behavior infects the compute instance members of the group and you run into VM name conflicts.

I feel like this needs either better update behavior (detecting when the instance IDs have changed and updating the group membership appropriately) or perhaps by providing a compute_instance_group_member resource where we can maintain membership outside of the group resource itself.

**Comment by rileykarson** [comment]
Yeah, `google_compute_instance_group_member` / `google_compute_instance_group_instance` seems like a reasonable approach.

**Comment by paulspiegel** [comment]
Thanks Riley, there's a previous issue proposing this: https://github.com/hashicorp/terraform-provider-google/issues/8605

I see that you added it as a Goal.  Has there been any movement on this?

**Comment by rileykarson** [comment]
No additional movement yet! Deduplicating to https://github.com/hashicorp/terraform-provider-google/issues/8605, thanks.
