### ISSUE TITLE
Promote google_dataproc_metastore_service and related fields in google_dataproc_cluster to GA

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#9938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_dataproc_metastore_service
* google_dataproc_cluster

### References

* https://github.com/GoogleCloudPlatform/magic-modules/pull/5146#pullrequestreview-740681636
* https://cloud.google.com/dataproc-metastore/docs/attach-dataproc
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_metastore_service

**Comment by zubayr-ahmed** [comment]
Hi @shuyama1 , Just want to know if these enhancements are being picked up for promotion from `beta` -> `ga` anytime soon or atleast it is in queue :) 
Thank you.

**Comment by melinath** [comment]
b/237108585

**Comment by DrFaust92** [comment]
will take a look as this is a potential blocker for #12009
