### ISSUE TITLE
Add support to configure JSON parsing and log level in google_compute_security_policy

### ISSUE THREAD

**Issue by saifulwebid** [hashicorp/terraform-provider-google#9939]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support to configure JSON parsing and log level on `google_compute_security_policy`. Without this, the only way to configure them is by using `gcloud` commands ([here](https://cloud.google.com/armor/docs/configure-security-policies#enable-json-parsing), [here](https://cloud.google.com/armor/docs/configure-security-policies#enable-verbose-logging)).

The corresponding API resource is https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies#resource:-securitypolicy. We expect the `google_compute_security_policy` to also configure the `advancedOptionsConfig.jsonParsing` and `advancedOptionsConfig.logLevel` fields.

### New or Affected Resource(s)

* google_compute_security_policy

### Potential Terraform Configuration

```tf
resource "google_compute_security_policy" "policy" {
  name = "my-policy"

  rule {
    # ...
  }

  rule {
    # ...
  }

  advanced_options_config {
    json_parsing = "DISABLED" # or "STANDARD"
    log_level    = "NORMAL" # or "VERBOSE"
  }
}
```

### References

N/A

**Comment by roobert** [comment]
This looks related to https://github.com/hashicorp/terraform-provider-google/issues/10497
