### ISSUE TITLE
`google_cloudfunctions_function` Unable to reference a secret

### ISSUE THREAD

**Issue by philippeboyd** [hashicorp/terraform-provider-google#9946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, there doesn't seem to be a way to reference a secret stored in Google's Secret manager when creating a function with the TF resource (available in the UI)

![image](https://user-images.githubusercontent.com/3239656/131923404-5d91fd1e-6ab2-4b99-8b67-c3ae0ea47fc2.png)

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
resource "google_cloudfunctions_function" "func" {
  project   = var.project_id
  name        = "my-func"
  runtime     = "python38"

  ...

  secrets {
      secret_id = "my-secret-1"
      reference_method = "VOLUME"
      mount_path = "/my-secret-1"
      paths = [
        {
          path = "/v1"
          version = "1"
        }
      ]
  }

  secrets {
      secret_id = "my-secret-2"
      reference_method = "ENVIRONMENT_VARIABLE"
      variables = [
        {
          name = "MY_SECRET_2"
          version = "latest"
        }
      ]
  }
}
```

**Comment by upodroid** [comment]
Hi

The provider doesn't implement features in Private Preview. Also, provider doesn't implement the new version of Functions yet as it is Private Preview.

Thank you

**Comment by vponnam** [comment]
As a side note: while the support for this feature is yet to be added to the provider, assuming the other dependencies are met, an interim option to automate this secret manager integration is by wrapping the [gcloud command](https://cloud.google.com/functions/docs/configuring/secrets#making_a_secret_accessible_to_a_function) in a [gcloud module](https://github.com/terraform-google-modules/terraform-google-gcloud) or as a local-exec step.

**Comment by djfinnoy** [comment]
> As a side note: while the support for this feature is yet to be added to the provider, assuming the other dependencies are met, an interim option to automate this secret manager integration is by wrapping the [gcloud command](https://cloud.google.com/functions/docs/configuring/secrets#making_a_secret_accessible_to_a_function) in a [gcloud module](https://github.com/terraform-google-modules/terraform-google-gcloud) or as a local-exec step.

Would you mind sharing a snippet of your `local-exec`?
I'm trying to replicate this, but I'm finding the `gcloud beta functions` command to be very fiddly.

I've deployed a function using the `google_cloudfunctions_function` resource.
When running the SDK, I'm told that one of the trigger flags is required when specifying a new function; looks like it doesn't recognize that my function already exists:

```
gcloud beta functions deploy <correctFunctionName> --region <correctFunctionRegion> \
  --set-secrets '...'
```

**Comment by jenshonkan84** [comment]
Any updates on this?

**Comment by djfinnoy** [comment]
+1

This is blocking us from adopting Terraform for our cloud functions. Eagerly support for function secrets in the provider.

**Comment by kakarott1511** [comment]
Really need this feature in terraform as we are blocked and can't go in prod. We don't want to do workaround to use this feature.
