### ISSUE TITLE
`google_spanner_instance` processing_units update fails

### ISSUE THREAD

**Issue by adamallred** [hashicorp/terraform-provider-google#9947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment or [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the pull request to this issue.

### Terraform Version

Terraform v0.12.31
+ provider.google v3.81.0
+ provider.google-beta v3.81.0

### Affected Resource(s)

`google_spanner_instance`

### Terraform Configuration Files (if applicable)

```tf
resource "google_spanner_instance" "spanner" {
  name                = "test-spanner"
  config              = "regional-us-east1"
  display_name        = "test-spanner"
  processing_units    = 3000
}
```

### Issue Description
After making a spanner instance using processing_units, attempting to update the value leads to a field error when applying:

```
Error: Error updating Instance "test-spanner/test-spanner": googleapi: Error 400: Invalid UpdateInstance request.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Must specify a non-empty field mask.",
        "field": "field_mask"
      }
    ]
  }
]
```

I would expect to be able to modify this value.

### References

* #7732

**Comment by edwardmedia** [comment]
@adamallred dup with https://github.com/hashicorp/terraform-provider-google/issues/9908 and it has been fixed 5 days ago with PR https://github.com/GoogleCloudPlatform/magic-modules/pull/5147.  Wait for next release.

**Comment by adamallred** [comment]
Wow, I totally missed that. Closing this.
