### ISSUE TITLE
Service account account_id can start with a digit

### ISSUE THREAD

**Issue by dima-vm** [hashicorp/terraform-provider-google#9954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.82.0
+ provider registry.terraform.io/hashicorp/google-beta v3.82.0

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
resource "google_service_account" "compute-default" {
  account_id = "321035333006-compute"
  display_name = "Compute Engine default service account"
}
```

### Debug Output

```
│ Error: "account_id" ("321035333006-compute") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
│ 
│   with google_service_account.compute-default,
│   on main.tf line 94, in resource "google_service_account" "compute-default":
│   94:   account_id = "321035333006-compute"
```

### Expected Behavior
Accept service account with IDs beginning with numerals, because that Service Account was created automatically by Google. 

### Actual Behavior

Cannot import existing default Compute Engine service account.

### Steps to Reproduce

1. `terraform apply`

### References
Similar issue: #3212

**Comment by upodroid** [comment]
Hi 

That isn't exactly a bug. 

1. You don't want to import this resource and manage it by terraform as you will fail field validation. Also it is created by Google automatically so there is no reason to manage it in Terraform.
2. There is a specific datasource for referencing this service account. It is called `google_compute_default_service_account `
3. Google API has a restriction on the format of of account_id and TF will validate it.


Thank you

**Comment by melinath** [comment]
Looking at the API, this seems to be the correct validation for us to apply for this resource. https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/create#request-body

I'm not sure how that interacts with the default service account. @dima-vm could you elaborate on your use case? Would using the `google_compute_default_service_account` data source be sufficient for you?

**Comment by melinath** [comment]
After looking into this some more, I'm going to go ahead and close the ticket. It looks like you're talking about https://cloud.google.com/iam/docs/service-accounts#default. We don't support that with the service_account resource.

You can reference the default compute service account with [`google_compute_default_service_account`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_default_service_account), or you can take some actions to manage the account using [`google_project_default_service_accounts`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_default_service_accounts). 

Please feel free to respond with some more details about your issue if those resources do not resolve it.
