### ISSUE TITLE
Setting a cloudbuild trigger from enterprise self hosted github

### ISSUE THREAD

**Issue by chitha20** [hashicorp/terraform-provider-google#9956]
### Affected Resource(s)

* google_cloudbuild_trigger

###  Current  Problem  : 

Hi with the recent GA'ed of cloudbuild private github enterprise feature as mentioned [here](https://cloud.google.com/build/docs/automating-builds/build-repos-from-github-enterprise) , 

we would like to leverage terraform automation in configuring the trigger for cloudbuild job from self hosted github. Current provider doc [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger)

Right now the below terraform snippet tried to create a trigger from github which expects like this : 

**_github.com/my-org/my-repo_** 

And it fails for our case as we want to have capability to change the github.com towards self hosted github url.

```
resource "google_cloudbuild_trigger" "my-resources" {
  github {
    name  = "my-repo
    owner = "my-org"

    push {
      branch       = "^master$"
      invert_regex = false
    }
  }

  filename = "cloudbuild.yaml"
} 
```

###  Expected outcome : 

We should have ability to configure the self hosted github_url in google_cloudbuild_trigger github section of the provider.

Let us know if there is a support for it already or if thats upcoming.

**Comment by rileykarson** [comment]
I think this is a matter of adding both a resource for https://cloud.google.com/build/docs/api/reference/rest/v1/projects.githubEnterpriseConfigs#GitHubEnterpriseConfig and the `enterpriseConfigResourceName` field to trigger. The API guide is confusing, and talks about creating JSON files and pushing them using curl rather than using a language client.

**Comment by NaurisSadovskis** [comment]
hey folks, any update on this?

**Comment by nickozilla** [comment]
Hi is anyone working on this?

**Comment by itsavvy-ankur** [comment]
Hi, I have recently stumbled on this as well. Just wondering if this is being worked upon or any workarounds exist for creating the trigger for GitHub enterprise repositories?

**Comment by sebxgd** [comment]
I have same issue

**Comment by ramiresdallago** [comment]
Hi, same issue here!

**Comment by prateek2408** [comment]
Working on it.

**Comment by kuba-solid** [comment]
anyone knows when this change will be included in the release?

**Comment by rileykarson** [comment]
Likely next Monday's release

**Comment by kuba-solid** [comment]
hello,

 do you know when today's release is expected?

**Comment by rileykarson** [comment]
Hmm- didn't look like it happened. I'll follow up w/ the release owner tomorrow (we're past their core hours right now).

**Comment by parmus** [comment]
We are also eagerly awaiting this next release.
