### ISSUE TITLE
google_vpc_access_connector ip_cidr_range is not optional

### ISSUE THREAD

**Issue by estensen** [hashicorp/terraform-provider-google#9957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.0

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

```tf
# project and region are anonymised
resource "google_vpc_access_connector" "connector" {
  project       = "projectId"
  region        = "location"
  name          = "connector"
  network       = "default"
}
```

### Expected Behavior

The [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector#argument-reference) states that `ip_cidr_range` is an optional argument, but trying to creat a Connector without it fails.

### Actual Behavior

```tf
│ Error: Error creating Connector: googleapi: Error 400: Connector IP CIDR range is required.
│
│   with google_vpc_access_connector.connector,
│   on main.tf line 163, in resource "google_vpc_access_connector" "connector":
│  163: resource "google_vpc_access_connector" "connector" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
`ip_cidr_range` was required but it was set to optional https://github.com/hashicorp/terraform-provider-google/commit/c56c27784c23a9db77689b9d114aa16ca259602c

**Comment by edwardmedia** [comment]
@estensen does this make sense?

**Comment by estensen** [comment]
I think this happened while transitioning from using a Shared VPC Connector to a normal one.
The linked example with a Shared VPC Connector using the beta provider works.

I don't think I'll be able to recreate the error.

**Comment by edwardmedia** [comment]
@estensen what I was trying to say is in some cases, this field is optional. In other cases, it is required. Because of this, the doc usually specifies it is optional. Closing the issue then. Feel free to reopen if you see differently.
