### ISSUE TITLE
Flakey test: TestAccTPUNode_tpuNodeBUpdateTensorFlowVersion

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9967]
### Affected Resource(s)

* google_tpu_node

`TestAccTPUNode_tpuNodeBUpdateTensorFlowVersion` is flakey - failed 45% of the time last month.

Failure case is:

```
Error: Error waiting to create Node: Error waiting for Creating Node: Error code 3, message: Cloud TPU received an invalid argument. The 'CIDR Range' value "10.1.0.0/29" on network "tp-networkdefault4153782072545391213" conflicts with another subnet or object in the (peered) customer network. [EID: 0xf6f9d5666e2cf752]
```

Example failure: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=7910401290365399987

**Comment by melinath** [comment]
Possibly related: https://github.com/hashicorp/terraform-provider-google/issues/5572

**Comment by sanghaniJ** [comment]
- TestAccTPUNode_tpuNodeBUpdateTensorFlowVersion

  [Google Cloud](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=7910401290365399987&tab=testDetails) - 85% failure
  [Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloudBeta&testNameId=7910401290365399987&tab=testDetails) - 67% failure

**Comment by sanghaniJ** [comment]
b/261970017

**Comment by roaks3** [comment]
I'm not entirely sure why, but `cidr_range = "10.1.0.0/29"` appears to have been removed with https://github.com/GoogleCloudPlatform/magic-modules/pull/5435. Closing because we are not seeing this error, and very likely will not see it again unless it needs to be added back for https://github.com/hashicorp/terraform-provider-google/issues/10222
