### ISSUE TITLE
Flakey tests: TestAccNetworkServicesEdgeCacheService and TestAccNetworkServicesEdgeCacheOrigin (quota)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9968]
TestAccNetworkServicesEdgeCacheService_updateAndImport has been failing consistently since August 19.

Failure looks like: Quota 'EdgeCacheOrigins' exhausted.

Example: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=-4680362232161979201

Impacted tests:

- TestAccNetworkServicesEdgeCacheService_updateAndImport
- TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceAdvancedExample
- TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceBasicExample
- TestAccNetworkServicesEdgeCacheOrigin_updateAndImport
- TestAccNetworkServicesEdgeCacheOrigin_networkServicesEdgeCacheOriginAdvancedExample
- TestAccNetworkServicesEdgeCacheOrigin_networkServicesEdgeCacheOriginBasicExample

It looks like these resources are building up over time i.e. not getting deleted properly.

**Comment by melinath** [comment]
EdgeCacheOrigin & EdgeCacheService examples don't generate tests with tf-test prefixes

**Comment by megan07** [comment]
I'm going to reopen this because some are still failing, only for different reasons, so I'll look into it more.

**Comment by megan07** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5243
