### ISSUE TITLE
Service account service-<project_number>@gs-project-accounts.iam.gserviceaccount.com does not exist

### ISSUE THREAD

**Issue by Barbarians** [hashicorp/terraform-provider-google#9969]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.0.4

### Affected Resource(s)
*google_kms_crypto_key_iam_member*

### Terraform Configuration Files
```tf
resource "google_kms_crypto_key_iam_member" "kms-member" {
  for_each      = var.kms_iam_map
  crypto_key_id = each.value["crypto_key_id"]
  role          = each.value["role"]
  member        = each.value["member"]
}
```

### Panic Output
https://gist.github.com/Barbarians/9d20158a9c582f2aab5ae994d4f12943

### Steps to Reproduce
1. `terraform apply`

### Correct error
I noticed the service account is activated only once we create a bucket or after calling it from the google [api](https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount/get).

So I added an "http" data resource to activate the account

```tf
data "http" "enabled_gcs_service_account" {
  count = var.enabled_gcs_service_account ? 1 : 0
  url   = "https://storage.googleapis.com/storage/v1/projects/${var.project_id}/serviceAccount"
  request_headers = {
    Accept        = "application/json"
    Authorization = "Bearer ${var.token}"
  }
}
```

To retrieve the token I used this cmd

```
gcloud auth application-default print-access-token
```

**Comment by edwardmedia** [comment]
@Barbarians it's hard to guess without seeing the data. Can you verify if the Service Account exists?

> googleapi: Error 400: Service account service-1090579446678@gs-project-accounts.iam.gserviceaccount.com does not exist., 
badRequest

Checkout below doc for reference

https://cloud.google.com/storage/docs/projects#service-agents

**Comment by Barbarians** [comment]
@edwardmedia yes i have a dependency with my *google_project_service*

it's ok. i have solved this error with that

```tf
data "http" "enabled_gcs_service_account" {
  count = var.enabled_gcs_service_account ? 1 : 0
  url   = "https://storage.googleapis.com/storage/v1/projects/${var.project_id}/serviceAccount"
  request_headers = {
    Accept        = "application/json"
    Authorization = "Bearer ${var.token}"
  }
}
```

To retrieve the token I used this cmd
```
gcloud auth application-default print-access-token
```

I posted this issue just to help other person with the same issue
