### ISSUE TITLE
Add enable-workload-certificates for container_cluster resource

### ISSUE THREAD

**Issue by sankit2020** [hashicorp/terraform-provider-google#9973]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add enable-workload-certificates for container_cluster resource

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

Support --enable-workload-certificates in the google_container_cluster resource

# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

https://buganizer.corp.google.com/issues/198206223

**Comment by sankit2020** [comment]
https://buganizer.corp.google.com/issues/198206223

**Comment by rileykarson** [comment]
Appears to have been closed in https://github.com/GoogleCloudPlatform/magic-modules/pull/6328
