### ISSUE TITLE
Test failure: Permadiff in google_monitoring_dashboard

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9976]
### Affected Resource(s)

* google_monitoring_dashboard

Consistent failure since August 13, 2021.
Impacted tests:
- TestAccMonitoringDashboard_update
- TestAccMonitoringDashboard_gridLayout
Example: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=-6689074540955700992
Message:
```
- targetAxis      = "Y1" -> null
```

Looks like a permadiff on targetAxis - probably a new default?

b/275112679

**Comment by jeremyvisser** [comment]
This is likely the same issue as https://github.com/hashicorp/terraform-provider-google/issues/7242.

**Comment by mitj04** [comment]
b/262375147

**Comment by megan07** [comment]
this is fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5595
it's as breaking change and will be in the next release

**Comment by c2thorn** [comment]
closing in favor of https://github.com/hashicorp/terraform-provider-google/issues/7242
