### ISSUE TITLE
Test failure: google_compute_router encrypted_interconnect_router

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9977]
Consistent failure since July 4th.
Impacted tests:
- TestAccComputeInterconnectAttachment_computeInterconnectAttachmentIpsecEncryptionExample
- TestAccComputeRouter_computeRouterEncryptedInterconnectExample
- TestAccComputeHaVpnGateway_computeHaVpnGatewayEncryptedInterconnectExample

Example: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=-794809155939851094
Message:

```
Error: Unsupported argument
on terraform_plugin_test.tf line 5, in resource "google_compute_router" "encrypted-interconnect-router":
5:   encrypted_interconnect_router = true
An argument named "encrypted_interconnect_router" is not expected here.
```

Perhaps this feature is beta-only?

**Comment by rileykarson** [comment]
Fixed by GAing the feature
