### ISSUE TITLE
google_compute_resource_policy Scheduler Destroys all VMs

### ISSUE THREAD

**Issue by Ariestattoo** [hashicorp/terraform-provider-google#9981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.82.0
+ provider registry.terraform.io/hashicorp/google-beta v3.82.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

resource "google_compute_resource_policy" "downtime" {
  name   = "vm-machine-state"
  region = "us-central1"
  description = "Start and stop instances"
  instance_schedule_policy {
    vm_start_schedule {
      schedule = var.instance-schedule-start
    }
    vm_stop_schedule {
      schedule = var.instance-schedule-stop
    }
    time_zone = "America/Edmonton"
  }
}
```
#### Attached to instance declaration
```
  resource_policies         = [
          google_compute_resource_policy.downtime.id
        ]
```
### Expected Behavior

Schedules changes and attachments to instance should update and attach 

### Actual Behavior

When modifying or adding an instance schedule to an instance the instance requires destruction and rebuild. Even if you use the gcloud  command which does not destroy the instance
gcloud compute instances add-resource-policies VM_NAME \
    --resource-policies=SCHEDULE_NAME \
    [--zone=ZONE]
Terraform will try and incorporate the change into its state and destroy and rebuild the instance. Additionally, if you change the schedule it will also destroy and rebuild the instance. 
### Steps to Reproduce

1. Create a basic compute instance
```
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  tags = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
```
2. Create a scheduling resource policy
```
resource "google_compute_resource_policy" "downtime" {
  name   = "vm-machine-state"
  region = "us-central1"
  description = "Start and stop instances"
  instance_schedule_policy {
    vm_start_schedule {
      schedule = var.instance-schedule-start
    }
    vm_stop_schedule {
      schedule = var.instance-schedule-stop
    }
    time_zone = "America/Edmonton"
  }
}
```
3. Terraform apply
4. Add the schedule to the instance
```
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  tags = ["foo", "bar"]
  resource_policies         = [
          google_compute_resource_policy.downtime.id
        ]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
```
5. Terraform apply
Plan will destroy the instance to attach the schedule.
    _- resource_policies         = [
          - "https://www.googleapis.com/compute/beta/projects/xxxxxxx/regions/us-central1/resourcePolicies/vm-machine-state",
        ] -> null # forces replacement_

### References

* #0000

**Comment by edwardmedia** [comment]
@Ariestattoo can you detail the steps to repro the issue? What is excepted and what is the actual result?

**Comment by Ariestattoo** [comment]
Hi @edwardmedia I have updated the initial comment with more details

**Comment by edwardmedia** [comment]
I see. There are two POST request available [addResourcePolicies](https://cloud.google.com/compute/docs/reference/rest/v1/instances/addResourcePolicies) and [removeResourcePolicies](https://cloud.google.com/compute/docs/reference/rest/v1/instances/removeResourcePolicies)

**Comment by hanneshayashi** [comment]
I have this working locally now with a small patch. Can I submit a PR or is there any procedure I need to follow?

**Comment by hanneshayashi** [comment]
I opened a PR with the changes I made locally. I hope that's ok. If I need to follow any additional steps, please let me know.

**Comment by Ariestattoo** [comment]
Thanks for your time on this @hanneshayashi  and @edwardmedia. My understandng that Hashicorp is short staffed right now and not working through community pull requests. Hopefully soon.

**Comment by hanneshayashi** [comment]
As far as I understand, that only applies to the main Terraform repo and not the providers:
https://www.hashicorp.com/blog/terraform-community-contributions

> The broader Terraform ecosystem is not impacted, and we are continuing to review a large number of contributions to our ecosystem of providers on a daily basis.

Although I guess everyone at HashiCorp is pretty busy in general. If there is anything I can do to help get this merged, please let me know @edwardmedia

**Comment by hanneshayashi** [comment]
@ndmckinley Since my PR was merged, should this issue be closed?

**Comment by ndmckinley** [comment]
Ah, yes, thank you!
