### ISSUE TITLE
Failing test(s): TestAccComposerEnvironment_update

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9987]
Failure rate: Consistently since August 28

Impacted tests:
- TestAccComposerEnvironment_update

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=-3074006311885699769

Message:

```
Error: googleapi: Error 400: Found 1 problem:
  1) Image version update (composer-1.16.15-airflow-1.10.15 -> composer-1.16.14-airflow-1.10.15) must not decrease the Composer version or Airflow version., badRequest
```

Note: previously this test was failing with a slightly different error, until August 25. See https://github.com/hashicorp/terraform-provider-google/issues/9488 for details.

**Comment by rileykarson** [comment]
This one appears to have resolved itself
