### ISSUE TITLE
Failing test(s): Apigee Instance permadiff

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9988]
Failure rate: Consistently since June 4

Impacted tests:
- TestAccApigeeInstanceAttachment_apigeeInstanceAttachmentBasicTestExample
- TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample
- TestAccApigeeInstance_apigeeInstanceBasicTestExample
- TestAccApigeeInstance_apigeeInstanceIpRangeTestExample
- (beta) TestAccApigeeInstance_apigeeInstanceFullTestExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/203810?buildTab=tests&expandedTest=-1088947708178477728
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/208057?buildTab=tests&expandedTest=-1088947708178477728
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/220033?buildTab=tests&expandedTest=-1088947708178477728

Message:

```
~ location           = "us-central1" -> "us-central1-b"
name               = "tf-tests088go6r7k"
- peering_cidr_range = "SLASH_22" -> null
```

Looks like a permadiff caused by the peering_cidr_range and location fields.

**Comment by matihost** [comment]
Seem location is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/10849
And peering_cidr_range is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9324

both seems not related to Apigee NAT address resource addon which is nice to have in 4.6.0 google provider version

**Comment by melinath** [comment]
The other issues have been resolved; these fields no longer cause permadiff.
