### ISSUE TITLE
Failing test(s): TestAccCloudbuildWorkerPool_withNetwork

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9994]
Failure rate: 100% since August 22

Impacted tests:
- TestAccCloudbuildWorkerPool_withNetwork

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/203835?buildTab=tests&expandedTest=2443308878520888895
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/208265?buildTab=tests&pager.currentPage=1&status=failed&expandedTest=2443308878520888895

Message:

```
Error: Error creating GlobalAddress: googleapi: Error 409: The resource 'projects/<project-id>/global/addresses/worker-pool-range' already exists, alreadyExists
```

**Comment by megan07** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5383
